Seamly2D: XMLStringPool Class Reference
XMLStringPool Class Reference
#include <StringPool.hpp>
Classes
struct PoolElem
Public Member Functions
XMLStringPool (const unsigned int modulus=109, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~XMLStringPool ()
virtual unsigned int addOrFind (const XMLCh *const newString)
virtual bool exists (const XMLCh *const newString) const
virtual bool exists (const unsigned int id) const
virtual void flushAll ()
virtual unsigned int getId (const XMLCh *const toFind) const
virtual const XMLCh * getValueForId (const unsigned int id) const
virtual unsigned int getStringCount () const
XMLStringPool (MemoryManager *const manager)
XMLStringPool (const unsigned int modulus=109, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~XMLStringPool ()
virtual unsigned int addOrFind (const XMLCh *const newString)
virtual bool exists (const XMLCh *const newString) const
virtual bool exists (const unsigned int id) const
virtual void flushAll ()
virtual unsigned int getId (const XMLCh *const toFind) const
virtual const XMLCh * getValueForId (const unsigned int id) const
virtual unsigned int getStringCount () const
XMLStringPool (MemoryManager *const manager)
XMLStringPool (const unsigned int modulus=109, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~XMLStringPool ()
virtual unsigned int addOrFind (const XMLCh *const newString)
virtual bool exists (const XMLCh *const newString) const
virtual bool exists (const unsigned int id) const
virtual void flushAll ()
virtual unsigned int getId (const XMLCh *const toFind) const
virtual const XMLCh * getValueForId (const unsigned int id) const
virtual unsigned int getStringCount () const
XMLStringPool (MemoryManager *const manager)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Protected Attributes
unsigned int fCurId
Private Member Functions
XMLStringPool (const XMLStringPool &)
XMLStringPool & operator= (const XMLStringPool &)
unsigned int addNewEntry (const XMLCh *const newString)
XMLStringPool (const XMLStringPool &)
XMLStringPool & operator= (const XMLStringPool &)
unsigned int addNewEntry (const XMLCh *const newString)
XMLStringPool (const XMLStringPool &)
XMLStringPool & operator= (const XMLStringPool &)
unsigned int addNewEntry (const XMLCh *const newString)
Private Attributes
MemoryManager * fMemoryManager
PoolElem ** fIdMap
RefHashTableOf< PoolElem > * fHashTable
unsigned int fMapCapacity
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 43 of file StringPool.hpp.
Constructor & Destructor Documentation
XMLStringPool() [1/9]
XMLStringPool::XMLStringPool (const unsigned int modulus = 109, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XMLStringPool() [1/3]
virtual XMLStringPool::~XMLStringPool () virtual
XMLStringPool() [2/9]
XMLStringPool::XMLStringPool (MemoryManager *const manager)
XMLStringPool() [3/9]
XMLStringPool::XMLStringPool (const XMLStringPool &) private
XMLStringPool() [4/9]
XMLStringPool::XMLStringPool (const unsigned int modulus = 109, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XMLStringPool() [2/3]
virtual XMLStringPool::~XMLStringPool () virtual
XMLStringPool() [5/9]
XMLStringPool::XMLStringPool (MemoryManager *const manager)
XMLStringPool() [6/9]
XMLStringPool::XMLStringPool (const XMLStringPool &) private
XMLStringPool() [7/9]
XMLStringPool::XMLStringPool (const unsigned int modulus = 109, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XMLStringPool() [3/3]
virtual XMLStringPool::~XMLStringPool () virtual
XMLStringPool() [8/9]
XMLStringPool::XMLStringPool (MemoryManager *const manager)
XMLStringPool() [9/9]
XMLStringPool::XMLStringPool (const XMLStringPool &) private
Member Function Documentation
addNewEntry() [1/3]
unsigned int XMLStringPool::addNewEntry (const XMLCh *const newString) private
Referenced by addOrFind().
addNewEntry() [2/3]
unsigned int XMLStringPool::addNewEntry (const XMLCh *const newString) private
addNewEntry() [3/3]
unsigned int XMLStringPool::addNewEntry (const XMLCh *const newString) private
addOrFind() [1/3]
unsigned int XMLStringPool::addOrFind (const XMLCh *const newString) inline virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
Definition at line 130 of file StringPool.hpp.
References addNewEntry(), fHashTable, and XMLStringPool::PoolElem::fId.
Referenced by TraverseSchema::genAnonTypeName(), TraverseSchema::getLocalPart(), and TraverseSchema::getPrefix().
addOrFind() [2/3]
virtual unsigned int XMLStringPool::addOrFind (const XMLCh *const newString) virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
addOrFind() [3/3]
virtual unsigned int XMLStringPool::addOrFind (const XMLCh *const newString) virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
exists() [1/6]
bool XMLStringPool::exists (const unsigned int id) const inline virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
Definition at line 154 of file StringPool.hpp.
References fCurId.
exists() [2/6]
virtual bool XMLStringPool::exists (const unsigned int id) const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
exists() [3/6]
virtual bool XMLStringPool::exists (const unsigned int id) const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
exists() [4/6]
bool XMLStringPool::exists (const XMLCh *const newString) const inline virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
Definition at line 149 of file StringPool.hpp.
References fHashTable.
exists() [5/6]
virtual bool XMLStringPool::exists (const XMLCh *const newString) const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
exists() [6/6]
virtual bool XMLStringPool::exists (const XMLCh *const newString) const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
flushAll() [1/3]
virtual void XMLStringPool::flushAll () virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
flushAll() [2/3]
virtual void XMLStringPool::flushAll () virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
flushAll() [3/3]
virtual void XMLStringPool::flushAll () virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
getId() [1/3]
unsigned int XMLStringPool::getId (const XMLCh *const toFind) const inline virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
Definition at line 139 of file StringPool.hpp.
References fHashTable, and XMLStringPool::PoolElem::fId.
Referenced by ElemStack::getPrefixId().
getId() [2/3]
virtual unsigned int XMLStringPool::getId (const XMLCh *const toFind) const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
getId() [3/3]
virtual unsigned int XMLStringPool::getId (const XMLCh *const toFind) const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
getStringCount() [1/3]
unsigned int XMLStringPool::getStringCount () const inline virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
Definition at line 168 of file StringPool.hpp.
References fCurId.
getStringCount() [2/3]
virtual unsigned int XMLStringPool::getStringCount () const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
getStringCount() [3/3]
virtual unsigned int XMLStringPool::getStringCount () const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
getValueForId() [1/3]
const XMLCh * XMLStringPool::getValueForId (const unsigned int id) const inline virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
Definition at line 159 of file StringPool.hpp.
References fCurId, fIdMap, fMemoryManager, XMLStringPool::PoolElem::fString, XMLExcepts::StrPool_IllegalId, and ThrowXMLwithMemMgr.
Referenced by TraverseSchema::genAnonTypeName(), TraverseSchema::getLocalPart(), TraverseSchema::getPrefix(), and ElemStack::getPrefixForId().
getValueForId() [2/3]
virtual const XMLCh* XMLStringPool::getValueForId (const unsigned int id) const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
getValueForId() [3/3]
virtual const XMLCh* XMLStringPool::getValueForId (const unsigned int id) const virtual
Reimplemented in XMLSynchronizedStringPool, XMLSynchronizedStringPool, and XMLSynchronizedStringPool.
operator=() [1/3]
XMLStringPool& XMLStringPool::operator= (const XMLStringPool &) private
operator=() [2/3]
XMLStringPool& XMLStringPool::operator= (const XMLStringPool &) private
operator=() [3/3]
XMLStringPool& XMLStringPool::operator= (const XMLStringPool &) private
Member Data Documentation
fCurId
unsigned int XMLStringPool::fCurId protected
Definition at line 125 of file StringPool.hpp.
Referenced by exists(), getStringCount(), and getValueForId().
fHashTable
RefHashTableOf< PoolElem > * XMLStringPool::fHashTable private
Definition at line 117 of file StringPool.hpp.
Referenced by addOrFind(), exists(), and getId().
fIdMap
PoolElem ** XMLStringPool::fIdMap private
Definition at line 116 of file StringPool.hpp.
Referenced by getValueForId().
fMapCapacity
unsigned int XMLStringPool::fMapCapacity private
Definition at line 118 of file StringPool.hpp.
fMemoryManager
MemoryManager * XMLStringPool::fMemoryManager private
Definition at line 115 of file StringPool.hpp.
Referenced by getValueForId().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/StringPool.hpp