Seamly2D: src/libs/xerces-c/macx/include/xercesc/dom/impl/DOMCasts.hpp File Reference
DOMCasts.hpp File Reference
#include <xercesc/dom/DOMException.hpp>
#include "DOMNodeBase.hpp"
#include "DOMElementImpl.hpp"
#include "DOMTextImpl.hpp"
Functions
static XERCES_CPP_NAMESPACE_BEGIN const DOMNodeImpl * castToNodeImpl (const DOMNode *p)
static DOMNodeImpl * castToNodeImpl (DOMNode *p)
static const DOMParentNode * castToParentImpl (const DOMNode *p)
static DOMParentNode * castToParentImpl (DOMNode *p)
static const DOMChildNode * castToChildImpl (const DOMNode *p)
static DOMChildNode * castToChildImpl (DOMNode *p)
Function Documentation
castToChildImpl() [1/2]
static const DOMChildNode* castToChildImpl (const DOMNode * p) inline static
Definition at line 91 of file DOMCasts.hpp.
References XMLPlatformUtils::fgMemoryManager, HasDOMChildImpl::getChildNodeImpl(), and DOMException::INVALID_STATE_ERR.
castToChildImpl() [2/2]
static DOMChildNode* castToChildImpl (DOMNode * p) inline static
Definition at line 99 of file DOMCasts.hpp.
References XMLPlatformUtils::fgMemoryManager, HasDOMChildImpl::getChildNodeImpl(), and DOMException::INVALID_STATE_ERR.
castToNodeImpl() [1/2]
static XERCES_CPP_NAMESPACE_BEGIN const DOMNodeImpl* castToNodeImpl (const DOMNode * p) inline static
Definition at line 57 of file DOMCasts.hpp.
References XMLPlatformUtils::fgMemoryManager, HasDOMNodeImpl::getNodeImpl(), and DOMException::INVALID_STATE_ERR.
castToNodeImpl() [2/2]
static DOMNodeImpl* castToNodeImpl (DOMNode * p) inline static
Definition at line 66 of file DOMCasts.hpp.
References XMLPlatformUtils::fgMemoryManager, HasDOMNodeImpl::getNodeImpl(), and DOMException::INVALID_STATE_ERR.
castToParentImpl() [1/2]
static const DOMParentNode* castToParentImpl (const DOMNode * p) inline static
Definition at line 75 of file DOMCasts.hpp.
References XMLPlatformUtils::fgMemoryManager, HasDOMParentImpl::getParentNodeImpl(), and DOMException::INVALID_STATE_ERR.
castToParentImpl() [2/2]
static DOMParentNode* castToParentImpl (DOMNode * p) inline static
Definition at line 83 of file DOMCasts.hpp.
References XMLPlatformUtils::fgMemoryManager, HasDOMParentImpl::getParentNodeImpl(), and DOMException::INVALID_STATE_ERR.