Seamly2D: src/libs/qmuparser/qmudef.h File Reference
qmudef.h File Reference
#include <qcompilerdetection.h>
#include <QtGlobal>
#include <QChar>
#include <QString>
#include <QLocale>
Macros
#define INIT_LOCALE_VARIABLES(locale)
Functions
QString NameRegExp ()
QT_WARNING_POP static Q_REQUIRED_RESULT bool QmuFuzzyComparePossibleNulls (double p1, double p2)
int ReadVal (const QString &formula, qreal &val, const QLocale &locale, const QChar &decimal, const QChar &thousand)
Macro Definition Documentation
INIT_LOCALE_VARIABLES
#define INIT_LOCALE_VARIABLES (locale)
Value:
const QChar positiveSign   = (locale).positiveSign();          \
const QChar negativeSign   = (locale).negativeSign();          \
const QChar sign0          = (locale).toString(0).at(0);       \
const QChar sign1          = (locale).toString(1).at(0);       \
const QChar sign2          = (locale).toString(2).at(0);       \
const QChar sign3          = (locale).toString(3).at(0);       \
const QChar sign4          = (locale).toString(4).at(0);       \
const QChar sign5          = (locale).toString(5).at(0);       \
const QChar sign6          = (locale).toString(6).at(0);       \
const QChar sign7          = (locale).toString(7).at(0);       \
const QChar sign8          = (locale).toString(8).at(0);       \
const QChar sign9          = (locale).toString(9).at(0);       \
const QChar expUpper       = (locale).exponential().toUpper(); \
const QChar expLower       = (locale).exponential().toLower(); \
const QChar decimalPoint   = (locale).decimalPoint();          \
const QChar groupSeparator = (locale).groupSeparator()         \
Definition at line 38 of file qmudef.h.
Function Documentation
NameRegExp()
QString NameRegExp ()
Definition at line 281 of file qmudef.cpp.
Referenced by DialogTrueDarts::CheckName(), DialogVariables::DialogVariables(), TMainWindow::InitWindow(), DialogTool::NamePointChanged(), VToolOptionsPropertyBrowser::setOperationSuffix(), VToolOptionsPropertyBrowser::setPointName(), VToolOptionsPropertyBrowser::setPointName1(), VToolOptionsPropertyBrowser::setPointName2(), DialogMirrorByAxis::suffixChanged(), DialogMirrorByLine::suffixChanged(), DialogMove::suffixChanged(), and DialogRotation::suffixChanged().
QmuFuzzyComparePossibleNulls()
static bool QmuFuzzyComparePossibleNulls (double p1, double p2) inline static
Definition at line 61 of file qmudef.h.
Referenced by qmu::QmuParserByteCode::ConstantFolding(), qmu::Test::QmuParserTester::EqnTest(), and qmu::QmuParserBase::ParseCmdCodeBulk().
ReadVal()
int ReadVal (const QString & formula, qreal & val, const QLocale & locale, const QChar & decimal, const QChar & thousand)
Definition at line 170 of file qmudef.cpp.
References Abscissa, CheckChar(), Done, Dot, EatWhiteSpace(), ExpMark, Exponent, ExpSign, GetChar(), Init, INIT_LOCALE_VARIABLES, Mantissa, Sign, and Thousand.
Referenced by qmu::QmuParser::IsVal().