Seamly2D: ValueVectorOf< TElem > Class Template Reference
ValueVectorOf< TElem > Class Template Reference
#include <ValueVectorOf.hpp>
Public Member Functions
ValueVectorOf (const XMLSize_t maxElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, const bool toCallDestructor=false)
ValueVectorOf (const ValueVectorOf< TElem > &toCopy)
~ValueVectorOf ()
ValueVectorOf< TElem > & operator= (const ValueVectorOf< TElem > &toAssign)
void addElement (const TElem &toAdd)
void setElementAt (const TElem &toSet, const XMLSize_t setAt)
void insertElementAt (const TElem &toInsert, const XMLSize_t insertAt)
void removeElementAt (const XMLSize_t removeAt)
void removeAllElements ()
bool containsElement (const TElem &toCheck, const XMLSize_t startIndex=0)
const TElem & elementAt (const XMLSize_t getAt) const
TElem & elementAt (const XMLSize_t getAt)
XMLSize_t curCapacity () const
XMLSize_t size () const
MemoryManager * getMemoryManager () const
void ensureExtraCapacity (const XMLSize_t length)
const TElem * rawData () const
ValueVectorOf (const XMLSize_t maxElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, const bool toCallDestructor=false)
ValueVectorOf (const ValueVectorOf< TElem > &toCopy)
~ValueVectorOf ()
ValueVectorOf< TElem > & operator= (const ValueVectorOf< TElem > &toAssign)
void addElement (const TElem &toAdd)
void setElementAt (const TElem &toSet, const XMLSize_t setAt)
void insertElementAt (const TElem &toInsert, const XMLSize_t insertAt)
void removeElementAt (const XMLSize_t removeAt)
void removeAllElements ()
bool containsElement (const TElem &toCheck, const XMLSize_t startIndex=0)
const TElem & elementAt (const XMLSize_t getAt) const
TElem & elementAt (const XMLSize_t getAt)
XMLSize_t curCapacity () const
XMLSize_t size () const
MemoryManager * getMemoryManager () const
void ensureExtraCapacity (const XMLSize_t length)
const TElem * rawData () const
ValueVectorOf (const XMLSize_t maxElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, const bool toCallDestructor=false)
ValueVectorOf (const ValueVectorOf< TElem > &toCopy)
~ValueVectorOf ()
ValueVectorOf< TElem > & operator= (const ValueVectorOf< TElem > &toAssign)
void addElement (const TElem &toAdd)
void setElementAt (const TElem &toSet, const XMLSize_t setAt)
void insertElementAt (const TElem &toInsert, const XMLSize_t insertAt)
void removeElementAt (const XMLSize_t removeAt)
void removeAllElements ()
bool containsElement (const TElem &toCheck, const XMLSize_t startIndex=0)
const TElem & elementAt (const XMLSize_t getAt) const
TElem & elementAt (const XMLSize_t getAt)
XMLSize_t curCapacity () const
XMLSize_t size () const
MemoryManager * getMemoryManager () const
void ensureExtraCapacity (const XMLSize_t length)
const TElem * rawData () const
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Attributes
bool fCallDestructor
XMLSize_t fCurCount
XMLSize_t fMaxCount
TElem * fElemList
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
template<class TElem>
class ValueVectorOf< TElem >
Definition at line 32 of file ValueVectorOf.hpp.
Constructor & Destructor Documentation
ValueVectorOf() [1/6]
template<class TElem > XERCES_CPP_NAMESPACE_BEGIN ValueVectorOf< TElem >::ValueVectorOf (const XMLSize_t maxElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, const bool toCallDestructor = false)
Definition at line 37 of file ValueVectorOf.c.
ValueVectorOf() [2/6]
template<class TElem > ValueVectorOf< TElem >::ValueVectorOf (const ValueVectorOf< TElem > & toCopy)
Definition at line 56 of file ValueVectorOf.c.
~ValueVectorOf() [1/3]
template<class TElem > ValueVectorOf< TElem >::~ValueVectorOf
Definition at line 74 of file ValueVectorOf.c.
ValueVectorOf() [3/6]
template<class TElem > ValueVectorOf< TElem >::ValueVectorOf (const XMLSize_t maxElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, const bool toCallDestructor = false)
ValueVectorOf() [4/6]
template<class TElem > ValueVectorOf< TElem >::ValueVectorOf (const ValueVectorOf< TElem > & toCopy)
~ValueVectorOf() [2/3]
template<class TElem > ValueVectorOf< TElem >::~ValueVectorOf ()
ValueVectorOf() [5/6]
template<class TElem > ValueVectorOf< TElem >::ValueVectorOf (const XMLSize_t maxElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, const bool toCallDestructor = false)
ValueVectorOf() [6/6]
template<class TElem > ValueVectorOf< TElem >::ValueVectorOf (const ValueVectorOf< TElem > & toCopy)
~ValueVectorOf() [3/3]
template<class TElem > ValueVectorOf< TElem >::~ValueVectorOf ()
Member Function Documentation
addElement() [1/3]
template<class TElem > void ValueVectorOf< TElem >::addElement (const TElem & toAdd)
Definition at line 120 of file ValueVectorOf.c.
Referenced by SchemaInfo::addFailedRedefine(), TraverseSchema::addImportedNS(), SchemaInfo::addRecursingType(), XPathScanner::addToken(), and FieldValueMap::put().
addElement() [2/3]
template<class TElem > void ValueVectorOf< TElem >::addElement (const TElem & toAdd)
addElement() [3/3]
template<class TElem > void ValueVectorOf< TElem >::addElement (const TElem & toAdd)
containsElement() [1/3]
template<class TElem > bool ValueVectorOf< TElem >::containsElement (const TElem & toCheck, const XMLSize_t startIndex = 0)
Definition at line 176 of file ValueVectorOf.c.
Referenced by TraverseSchema::addImportedNS(), SchemaInfo::isFailedRedefine(), and TraverseSchema::isImportingNS().
containsElement() [2/3]
template<class TElem > bool ValueVectorOf< TElem >::containsElement (const TElem & toCheck, const XMLSize_t startIndex = 0)
containsElement() [3/3]
template<class TElem > bool ValueVectorOf< TElem >::containsElement (const TElem & toCheck, const XMLSize_t startIndex = 0)
curCapacity() [1/3]
template<class TElem > XMLSize_t ValueVectorOf< TElem >::curCapacity
Definition at line 208 of file ValueVectorOf.c.
curCapacity() [2/3]
template<class TElem > XMLSize_t ValueVectorOf< TElem >::curCapacity () const
curCapacity() [3/3]
template<class TElem > XMLSize_t ValueVectorOf< TElem >::curCapacity () const
elementAt() [1/6]
template<class TElem > TElem & ValueVectorOf< TElem >::elementAt (const XMLSize_t getAt)
Definition at line 200 of file ValueVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
elementAt() [2/6]
template<class TElem > TElem& ValueVectorOf< TElem >::elementAt (const XMLSize_t getAt)
elementAt() [3/6]
template<class TElem > TElem& ValueVectorOf< TElem >::elementAt (const XMLSize_t getAt)
elementAt() [4/6]
template<class TElem > const TElem & ValueVectorOf< TElem >::elementAt (const XMLSize_t getAt) const
Definition at line 192 of file ValueVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
Referenced by FieldValueMap::getDatatypeValidatorAt(), FieldValueMap::getDatatypeValidatorFor(), and FieldValueMap::keyAt().
elementAt() [5/6]
template<class TElem > const TElem& ValueVectorOf< TElem >::elementAt (const XMLSize_t getAt) const
elementAt() [6/6]
template<class TElem > const TElem& ValueVectorOf< TElem >::elementAt (const XMLSize_t getAt) const
ensureExtraCapacity() [1/3]
template<class TElem > void ValueVectorOf< TElem >::ensureExtraCapacity (const XMLSize_t length)
Definition at line 227 of file ValueVectorOf.c.
ensureExtraCapacity() [2/3]
template<class TElem > void ValueVectorOf< TElem >::ensureExtraCapacity (const XMLSize_t length)
ensureExtraCapacity() [3/3]
template<class TElem > void ValueVectorOf< TElem >::ensureExtraCapacity (const XMLSize_t length)
getMemoryManager() [1/3]
template<class TElem > MemoryManager * ValueVectorOf< TElem >::getMemoryManager
Definition at line 219 of file ValueVectorOf.c.
getMemoryManager() [2/3]
template<class TElem > MemoryManager* ValueVectorOf< TElem >::getMemoryManager () const
getMemoryManager() [3/3]
template<class TElem > MemoryManager* ValueVectorOf< TElem >::getMemoryManager () const
insertElementAt() [1/3]
template<class TElem > void ValueVectorOf< TElem >::insertElementAt (const TElem & toInsert, const XMLSize_t insertAt)
Definition at line 134 of file ValueVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
insertElementAt() [2/3]
template<class TElem > void ValueVectorOf< TElem >::insertElementAt (const TElem & toInsert, const XMLSize_t insertAt)
insertElementAt() [3/3]
template<class TElem > void ValueVectorOf< TElem >::insertElementAt (const TElem & toInsert, const XMLSize_t insertAt)
operator=() [1/3]
template<class TElem > ValueVectorOf< TElem > & ValueVectorOf< TElem >::operator= (const ValueVectorOf< TElem > & toAssign)
Definition at line 88 of file ValueVectorOf.c.
References ValueVectorOf< TElem >::fCurCount, ValueVectorOf< TElem >::fElemList, and ValueVectorOf< TElem >::fMaxCount.
operator=() [2/3]
template<class TElem > ValueVectorOf<TElem>& ValueVectorOf< TElem >::operator= (const ValueVectorOf< TElem > & toAssign)
operator=() [3/3]
template<class TElem > ValueVectorOf<TElem>& ValueVectorOf< TElem >::operator= (const ValueVectorOf< TElem > & toAssign)
rawData() [1/3]
template<class TElem > const TElem * ValueVectorOf< TElem >::rawData
Definition at line 252 of file ValueVectorOf.c.
rawData() [2/3]
template<class TElem > const TElem* ValueVectorOf< TElem >::rawData () const
rawData() [3/3]
template<class TElem > const TElem* ValueVectorOf< TElem >::rawData () const
removeAllElements() [1/3]
template<class TElem > void ValueVectorOf< TElem >::removeAllElements
Definition at line 170 of file ValueVectorOf.c.
Referenced by SchemaAttDef::resetNamespaceList().
removeAllElements() [2/3]
template<class TElem > void ValueVectorOf< TElem >::removeAllElements ()
removeAllElements() [3/3]
template<class TElem > void ValueVectorOf< TElem >::removeAllElements ()
removeElementAt() [1/3]
template<class TElem > void ValueVectorOf< TElem >::removeElementAt (const XMLSize_t removeAt)
Definition at line 156 of file ValueVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
Referenced by TraverseSchema::popCurrentTypeNameStack().
removeElementAt() [2/3]
template<class TElem > void ValueVectorOf< TElem >::removeElementAt (const XMLSize_t removeAt)
removeElementAt() [3/3]
template<class TElem > void ValueVectorOf< TElem >::removeElementAt (const XMLSize_t removeAt)
setElementAt() [1/3]
template<class TElem > void ValueVectorOf< TElem >::setElementAt (const TElem & toSet, const XMLSize_t setAt)
Definition at line 126 of file ValueVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
Referenced by FieldValueMap::put().
setElementAt() [2/3]
template<class TElem > void ValueVectorOf< TElem >::setElementAt (const TElem & toSet, const XMLSize_t setAt)
setElementAt() [3/3]
template<class TElem > void ValueVectorOf< TElem >::setElementAt (const TElem & toSet, const XMLSize_t setAt)
size() [1/3]
template<class TElem > XMLSize_t ValueVectorOf< TElem >::size
Definition at line 213 of file ValueVectorOf.c.
Referenced by TraverseSchema::popCurrentTypeNameStack(), SchemaAttDef::resetNamespaceList(), SchemaAttDef::setNamespaceList(), and FieldValueMap::size().
size() [2/3]
template<class TElem > XMLSize_t ValueVectorOf< TElem >::size () const
size() [3/3]
template<class TElem > XMLSize_t ValueVectorOf< TElem >::size () const
Member Data Documentation
fCallDestructor
template<class TElem > bool ValueVectorOf< TElem >::fCallDestructor private
Definition at line 97 of file ValueVectorOf.hpp.
fCurCount
template<class TElem > XMLSize_t ValueVectorOf< TElem >::fCurCount private
Definition at line 98 of file ValueVectorOf.hpp.
Referenced by ValueVectorOf< TElem >::operator=().
fElemList
template<class TElem > TElem * ValueVectorOf< TElem >::fElemList private
Definition at line 100 of file ValueVectorOf.hpp.
Referenced by ValueVectorOf< TElem >::operator=().
fMaxCount
template<class TElem > XMLSize_t ValueVectorOf< TElem >::fMaxCount private
Definition at line 99 of file ValueVectorOf.hpp.
Referenced by ValueVectorOf< TElem >::operator=().
fMemoryManager
template<class TElem > MemoryManager * ValueVectorOf< TElem >::fMemoryManager private
Definition at line 101 of file ValueVectorOf.hpp.
The documentation for this class was generated from the following files:
src/libs/xerces-c/macx/include/xercesc/util/ValueVectorOf.hpp
src/libs/xerces-c/macx/include/xercesc/util/ValueVectorOf.c