Seamly2D: XMLElementDecl Class Reference
XMLElementDecl Class Reference abstract
#include <XMLElementDecl.hpp>
Public Types
enum CreateReasons {
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn , NoReason , Declared ,
AttList , InContentModel , AsRootElem , JustFaultIn ,
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn
}
enum CharDataOpts {
NoCharData , SpacesOk , AllCharData , NoCharData ,
SpacesOk , AllCharData , NoCharData , SpacesOk ,
AllCharData
}
enum CreateReasons {
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn , NoReason , Declared ,
AttList , InContentModel , AsRootElem , JustFaultIn ,
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn
}
enum CharDataOpts {
NoCharData , SpacesOk , AllCharData , NoCharData ,
SpacesOk , AllCharData , NoCharData , SpacesOk ,
AllCharData
}
enum CreateReasons {
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn , NoReason , Declared ,
AttList , InContentModel , AsRootElem , JustFaultIn ,
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn
}
enum CharDataOpts {
NoCharData , SpacesOk , AllCharData , NoCharData ,
SpacesOk , AllCharData , NoCharData , SpacesOk ,
AllCharData
}
Public Member Functions
Destructor
virtual ~XMLElementDecl ()
virtual ~XMLElementDecl ()
virtual ~XMLElementDecl ()
Virual ElementDecl interface
virtual XMLAttDefList & getAttDefList () const =0
virtual CharDataOpts getCharDataOpts () const =0
virtual bool hasAttDefs () const =0
virtual const ContentSpecNode * getContentSpec () const =0
virtual ContentSpecNode * getContentSpec ()=0
virtual void setContentSpec (ContentSpecNode *toAdopt)=0
virtual XMLContentModel * getContentModel ()=0
virtual void setContentModel (XMLContentModel *const newModelToAdopt)=0
virtual const XMLCh * getFormattedContentModel () const =0
virtual XMLAttDefList & getAttDefList () const =0
virtual CharDataOpts getCharDataOpts () const =0
virtual bool hasAttDefs () const =0
virtual const ContentSpecNode * getContentSpec () const =0
virtual ContentSpecNode * getContentSpec ()=0
virtual void setContentSpec (ContentSpecNode *toAdopt)=0
virtual XMLContentModel * getContentModel ()=0
virtual void setContentModel (XMLContentModel *const newModelToAdopt)=0
virtual const XMLCh * getFormattedContentModel () const =0
virtual XMLAttDefList & getAttDefList () const =0
virtual CharDataOpts getCharDataOpts () const =0
virtual bool hasAttDefs () const =0
virtual const ContentSpecNode * getContentSpec () const =0
virtual ContentSpecNode * getContentSpec ()=0
virtual void setContentSpec (ContentSpecNode *toAdopt)=0
virtual XMLContentModel * getContentModel ()=0
virtual void setContentModel (XMLContentModel *const newModelToAdopt)=0
virtual const XMLCh * getFormattedContentModel () const =0
Getter methods
const XMLCh * getBaseName () const
XMLCh * getBaseName ()
unsigned int getURI () const
const QName * getElementName () const
QName * getElementName ()
const XMLCh * getFullName () const
CreateReasons getCreateReason () const
XMLSize_t getId () const
bool isDeclared () const
bool isExternal () const
MemoryManager * getMemoryManager () const
const XMLCh * getBaseName () const
XMLCh * getBaseName ()
unsigned int getURI () const
const QName * getElementName () const
QName * getElementName ()
const XMLCh * getFullName () const
CreateReasons getCreateReason () const
XMLSize_t getId () const
bool isDeclared () const
bool isExternal () const
MemoryManager * getMemoryManager () const
const XMLCh * getBaseName () const
XMLCh * getBaseName ()
unsigned int getURI () const
const QName * getElementName () const
QName * getElementName ()
const XMLCh * getFullName () const
CreateReasons getCreateReason () const
XMLSize_t getId () const
bool isDeclared () const
bool isExternal () const
MemoryManager * getMemoryManager () const
Setter methods
void setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
void setElementName (const XMLCh *const rawName, const int uriId)
void setElementName (const QName *const elementName)
void setCreateReason (const CreateReasons newReason)
void setId (const XMLSize_t newId)
void setExternalElemDeclaration (const bool aValue)
void setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
void setElementName (const XMLCh *const rawName, const int uriId)
void setElementName (const QName *const elementName)
void setCreateReason (const CreateReasons newReason)
void setId (const XMLSize_t newId)
void setExternalElemDeclaration (const bool aValue)
void setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
void setElementName (const XMLCh *const rawName, const int uriId)
void setElementName (const QName *const elementName)
void setCreateReason (const CreateReasons newReason)
void setId (const XMLSize_t newId)
void setExternalElemDeclaration (const bool aValue)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Static Public Attributes
static const unsigned int fgInvalidElemId
static const unsigned int fgPCDataElemId
static const XMLCh fgPCDataElemName []
Miscellaneous methods
enum objectType {
Schema , DTD , UnKnown , Schema ,
DTD , UnKnown , Schema , DTD ,
UnKnown
}
enum objectType {
Schema , DTD , UnKnown , Schema ,
DTD , UnKnown , Schema , DTD ,
UnKnown
}
enum objectType {
Schema , DTD , UnKnown , Schema ,
DTD , UnKnown , Schema , DTD ,
UnKnown
}
MemoryManager * fMemoryManager
QName * fElementName
CreateReasons fCreateReason
XMLSize_t fId
bool fExternalElement
virtual XMLElementDecl::objectType getObjectType () const =0
virtual XMLElementDecl::objectType getObjectType () const =0
virtual XMLElementDecl::objectType getObjectType () const =0
static void storeElementDecl (XSerializeEngine &serEng, XMLElementDecl *const element)
static XMLElementDecl * loadElementDecl (XSerializeEngine &serEng)
static void storeElementDecl (XSerializeEngine &serEng, XMLElementDecl *const element)
static XMLElementDecl * loadElementDecl (XSerializeEngine &serEng)
static void storeElementDecl (XSerializeEngine &serEng, XMLElementDecl *const element)
static XMLElementDecl * loadElementDecl (XSerializeEngine &serEng)
XMLElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLElementDecl (const XMLElementDecl &)
XMLElementDecl & operator= (const XMLElementDecl &)
XMLElementDecl (const XMLElementDecl &)
XMLElementDecl & operator= (const XMLElementDecl &)
XMLElementDecl (const XMLElementDecl &)
XMLElementDecl & operator= (const XMLElementDecl &)
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
This class defines the core information of an element declaration. Each validator (DTD, Schema, etc...) will have its own information that it associations with the declaration of an element, but they must all share at least this core information, i.e. they must all derive from this class. The set of info enforced at this level is driven by the needs of XML 1.0 spec validation and well formedness checks.
This class defines some special element id values for invalid elements and PCDATA elements, as well as a string for the special PCDATA element name. All validators must honor these special values in order to allow content models to work generically (i.e. to let code know when its dealing with invalid or PCDATA element ids without having to know what type of validator its messing with.)
Definition at line 51 of file XMLElementDecl.hpp.
Member Enumeration Documentation
CharDataOpts [1/3]
enum XMLElementDecl::CharDataOpts
Enumerator
NoCharData
SpacesOk
AllCharData
NoCharData
SpacesOk
AllCharData
NoCharData
SpacesOk
AllCharData
Definition at line 79 of file XMLElementDecl.hpp.
CharDataOpts [2/3]
enum XMLElementDecl::CharDataOpts
Enumerator
NoCharData
SpacesOk
AllCharData
NoCharData
SpacesOk
AllCharData
NoCharData
SpacesOk
AllCharData
Definition at line 79 of file XMLElementDecl.hpp.
CharDataOpts [3/3]
enum XMLElementDecl::CharDataOpts
Enumerator
NoCharData
SpacesOk
AllCharData
NoCharData
SpacesOk
AllCharData
NoCharData
SpacesOk
AllCharData
Definition at line 79 of file XMLElementDecl.hpp.
CreateReasons [1/3]
enum XMLElementDecl::CreateReasons
Enumerator
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
Definition at line 69 of file XMLElementDecl.hpp.
CreateReasons [2/3]
enum XMLElementDecl::CreateReasons
Enumerator
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
Definition at line 69 of file XMLElementDecl.hpp.
CreateReasons [3/3]
enum XMLElementDecl::CreateReasons
Enumerator
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
NoReason
Declared
AttList
InContentModel
AsRootElem
JustFaultIn
Definition at line 69 of file XMLElementDecl.hpp.
objectType [1/3]
enum XMLElementDecl::objectType
Enumerator
Schema
DTD
UnKnown
Schema
DTD
UnKnown
Schema
DTD
UnKnown
Definition at line 411 of file XMLElementDecl.hpp.
objectType [2/3]
enum XMLElementDecl::objectType
Enumerator
Schema
DTD
UnKnown
Schema
DTD
UnKnown
Schema
DTD
UnKnown
Definition at line 411 of file XMLElementDecl.hpp.
objectType [3/3]
enum XMLElementDecl::objectType
Enumerator
Schema
DTD
UnKnown
Schema
DTD
UnKnown
Schema
DTD
UnKnown
Definition at line 411 of file XMLElementDecl.hpp.
Constructor & Destructor Documentation
~XMLElementDecl() [1/3]
virtual XMLElementDecl::~XMLElementDecl () virtual
XMLElementDecl() [1/6]
XMLElementDecl::XMLElementDecl (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLElementDecl() [2/6]
XMLElementDecl::XMLElementDecl (const XMLElementDecl &) private
~XMLElementDecl() [2/3]
virtual XMLElementDecl::~XMLElementDecl () virtual
XMLElementDecl() [3/6]
XMLElementDecl::XMLElementDecl (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLElementDecl() [4/6]
XMLElementDecl::XMLElementDecl (const XMLElementDecl &) private
~XMLElementDecl() [3/3]
virtual XMLElementDecl::~XMLElementDecl () virtual
XMLElementDecl() [5/6]
XMLElementDecl::XMLElementDecl (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLElementDecl() [6/6]
XMLElementDecl::XMLElementDecl (const XMLElementDecl &) private
Member Function Documentation
getAttDefList() [1/3]
virtual XMLAttDefList& XMLElementDecl::getAttDefList () const pure virtual
Get a list of attributes defined for this element.
The derived class should return a reference to some member object which implements the XMLAttDefList interface. This object gives the scanner the ability to look through the attributes defined for this element.
It is done this way for efficiency, though of course this is not thread safe. The scanner guarantees that it won't ever call this method in any nested way, but the outside world must be careful about when it calls this method, and optimally never would.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getAttDefList() [2/3]
virtual XMLAttDefList& XMLElementDecl::getAttDefList () const pure virtual
Get a list of attributes defined for this element.
The derived class should return a reference to some member object which implements the XMLAttDefList interface. This object gives the scanner the ability to look through the attributes defined for this element.
It is done this way for efficiency, though of course this is not thread safe. The scanner guarantees that it won't ever call this method in any nested way, but the outside world must be careful about when it calls this method, and optimally never would.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getAttDefList() [3/3]
virtual XMLAttDefList& XMLElementDecl::getAttDefList () const pure virtual
Get a list of attributes defined for this element.
The derived class should return a reference to some member object which implements the XMLAttDefList interface. This object gives the scanner the ability to look through the attributes defined for this element.
It is done this way for efficiency, though of course this is not thread safe. The scanner guarantees that it won't ever call this method in any nested way, but the outside world must be careful about when it calls this method, and optimally never would.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getBaseName() [1/6]
XMLCh * XMLElementDecl::getBaseName () inline
Definition at line 478 of file XMLElementDecl.hpp.
References fElementName, and QName::getLocalPart().
getBaseName() [2/6]
XMLCh* XMLElementDecl::getBaseName ()
getBaseName() [3/6]
XMLCh* XMLElementDecl::getBaseName ()
getBaseName() [4/6]
const XMLCh * XMLElementDecl::getBaseName () const inline
Get the base name of this element type.
Return the base name part of the element's name. This is the same regardless of whether namespaces are enabled or not.
Returns
A const pointer to the base name of the element decl.
Definition at line 473 of file XMLElementDecl.hpp.
References fElementName, and QName::getLocalPart().
Referenced by SchemaGrammar::putElemDecl(), and SchemaGrammar::putGroupElemDecl().
getBaseName() [5/6]
const XMLCh* XMLElementDecl::getBaseName () const
Get the base name of this element type.
Return the base name part of the element's name. This is the same regardless of whether namespaces are enabled or not.
Returns
A const pointer to the base name of the element decl.
getBaseName() [6/6]
const XMLCh* XMLElementDecl::getBaseName () const
Get the base name of this element type.
Return the base name part of the element's name. This is the same regardless of whether namespaces are enabled or not.
Returns
A const pointer to the base name of the element decl.
getCharDataOpts() [1/3]
virtual CharDataOpts XMLElementDecl::getCharDataOpts () const pure virtual
The character data options for this element type
The derived class should return an appropriate character data opts value which correctly represents its tolerance towards whitespace or character data inside of its instances. This allows the scanner to do all of the validation of character data.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getCharDataOpts() [2/3]
virtual CharDataOpts XMLElementDecl::getCharDataOpts () const pure virtual
The character data options for this element type
The derived class should return an appropriate character data opts value which correctly represents its tolerance towards whitespace or character data inside of its instances. This allows the scanner to do all of the validation of character data.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getCharDataOpts() [3/3]
virtual CharDataOpts XMLElementDecl::getCharDataOpts () const pure virtual
The character data options for this element type
The derived class should return an appropriate character data opts value which correctly represents its tolerance towards whitespace or character data inside of its instances. This allows the scanner to do all of the validation of character data.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentModel() [1/3]
virtual XMLContentModel* XMLElementDecl::getContentModel () pure virtual
Get a pointer to the abstract content model
This method will return a const pointer to the content model object of this element. This class is a simple abstraction that allows an element to define and use multiple, specialized content model types internally but still allow the outside world to do simple stuff with them.
Returns
A pointer to the element's content model, via the basic abstract content model type.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentModel() [2/3]
virtual XMLContentModel* XMLElementDecl::getContentModel () pure virtual
Get a pointer to the abstract content model
This method will return a const pointer to the content model object of this element. This class is a simple abstraction that allows an element to define and use multiple, specialized content model types internally but still allow the outside world to do simple stuff with them.
Returns
A pointer to the element's content model, via the basic abstract content model type.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentModel() [3/3]
virtual XMLContentModel* XMLElementDecl::getContentModel () pure virtual
Get a pointer to the abstract content model
This method will return a const pointer to the content model object of this element. This class is a simple abstraction that allows an element to define and use multiple, specialized content model types internally but still allow the outside world to do simple stuff with them.
Returns
A pointer to the element's content model, via the basic abstract content model type.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentSpec() [1/6]
virtual const ContentSpecNode* XMLElementDecl::getContentSpec () const pure virtual
Get a pointer to the content spec node
This method will return a const pointer to the content spec node object of this element.
Returns
A const pointer to the element's content spec node
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentSpec() [2/6]
virtual const ContentSpecNode* XMLElementDecl::getContentSpec () const pure virtual
Get a pointer to the content spec node
This method will return a const pointer to the content spec node object of this element.
Returns
A const pointer to the element's content spec node
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentSpec() [3/6]
virtual const ContentSpecNode* XMLElementDecl::getContentSpec () const pure virtual
Get a pointer to the content spec node
This method will return a const pointer to the content spec node object of this element.
Returns
A const pointer to the element's content spec node
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentSpec() [4/6]
virtual ContentSpecNode* XMLElementDecl::getContentSpec () pure virtual
Get a pointer to the content spec node
This method is identical to the previous one, except that it is non const.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentSpec() [5/6]
virtual ContentSpecNode* XMLElementDecl::getContentSpec () pure virtual
Get a pointer to the content spec node
This method is identical to the previous one, except that it is non const.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getContentSpec() [6/6]
virtual ContentSpecNode* XMLElementDecl::getContentSpec () pure virtual
Get a pointer to the content spec node
This method is identical to the previous one, except that it is non const.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getCreateReason() [1/3]
XMLElementDecl::CreateReasons XMLElementDecl::getCreateReason () const inline
Get the create reason for this element type
This method returns an enumeration which indicates why this element declaration exists. Elements can be used before they are actually declared, so they will often be faulted into the pool and marked as to why they are there.
Returns
An enumerated value that indicates the reason why this element was added to the element decl pool.
Definition at line 503 of file XMLElementDecl.hpp.
References fCreateReason.
getCreateReason() [2/3]
CreateReasons XMLElementDecl::getCreateReason () const
Get the create reason for this element type
This method returns an enumeration which indicates why this element declaration exists. Elements can be used before they are actually declared, so they will often be faulted into the pool and marked as to why they are there.
Returns
An enumerated value that indicates the reason why this element was added to the element decl pool.
getCreateReason() [3/3]
CreateReasons XMLElementDecl::getCreateReason () const
Get the create reason for this element type
This method returns an enumeration which indicates why this element declaration exists. Elements can be used before they are actually declared, so they will often be faulted into the pool and marked as to why they are there.
Returns
An enumerated value that indicates the reason why this element was added to the element decl pool.
getElementName() [1/6]
QName * XMLElementDecl::getElementName () inline
Definition at line 493 of file XMLElementDecl.hpp.
References fElementName.
getElementName() [2/6]
QName* XMLElementDecl::getElementName ()
getElementName() [3/6]
QName* XMLElementDecl::getElementName ()
getElementName() [4/6]
const QName * XMLElementDecl::getElementName () const inline
Get the QName of this element type.
Return the QName part of the element's name. This is the same regardless of whether namespaces are enabled or not.
Returns
A const pointer to the QName of the element decl.
Definition at line 488 of file XMLElementDecl.hpp.
References fElementName.
Referenced by ContentSpecNode::ContentSpecNode().
getElementName() [5/6]
const QName* XMLElementDecl::getElementName () const
Get the QName of this element type.
Return the QName part of the element's name. This is the same regardless of whether namespaces are enabled or not.
Returns
A const pointer to the QName of the element decl.
getElementName() [6/6]
const QName* XMLElementDecl::getElementName () const
Get the QName of this element type.
Return the QName part of the element's name. This is the same regardless of whether namespaces are enabled or not.
Returns
A const pointer to the QName of the element decl.
getFormattedContentModel() [1/3]
virtual const XMLCh* XMLElementDecl::getFormattedContentModel () const pure virtual
Geta formatted string of the content model
This method is a convenience method which will create a formatted representation of the content model of the element. It will not always exactly recreate the original model, since some normalization or or reformatting may occur. But, it will be a technically accurate representation of the original content model.
Returns
A pointer to an internal buffer which contains the formatted content model. The caller does not own this buffer and should copy it if it needs to be kept around.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getFormattedContentModel() [2/3]
virtual const XMLCh* XMLElementDecl::getFormattedContentModel () const pure virtual
Geta formatted string of the content model
This method is a convenience method which will create a formatted representation of the content model of the element. It will not always exactly recreate the original model, since some normalization or or reformatting may occur. But, it will be a technically accurate representation of the original content model.
Returns
A pointer to an internal buffer which contains the formatted content model. The caller does not own this buffer and should copy it if it needs to be kept around.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getFormattedContentModel() [3/3]
virtual const XMLCh* XMLElementDecl::getFormattedContentModel () const pure virtual
Geta formatted string of the content model
This method is a convenience method which will create a formatted representation of the content model of the element. It will not always exactly recreate the original model, since some normalization or or reformatting may occur. But, it will be a technically accurate representation of the original content model.
Returns
A pointer to an internal buffer which contains the formatted content model. The caller does not own this buffer and should copy it if it needs to be kept around.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getFullName() [1/3]
const XMLCh * XMLElementDecl::getFullName () const inline
Get the full name of this element type.
Return the full name of the element. If namespaces are not enabled, then this is the qName. Else it is the {uri}baseName form. For those validators that always require namespace processing, it will always be in the latter form because namespace processing will always be on.
Definition at line 498 of file XMLElementDecl.hpp.
References fElementName, and QName::getRawName().
Referenced by DTDElementDecl::getKey().
getFullName() [2/3]
const XMLCh* XMLElementDecl::getFullName () const
Get the full name of this element type.
Return the full name of the element. If namespaces are not enabled, then this is the qName. Else it is the {uri}baseName form. For those validators that always require namespace processing, it will always be in the latter form because namespace processing will always be on.
getFullName() [3/3]
const XMLCh* XMLElementDecl::getFullName () const
Get the full name of this element type.
Return the full name of the element. If namespaces are not enabled, then this is the qName. Else it is the {uri}baseName form. For those validators that always require namespace processing, it will always be in the latter form because namespace processing will always be on.
getId() [1/3]
XMLSize_t XMLElementDecl::getId () const inline
Get the element decl pool id for this element type
This method will return the element decl pool id of this element declaration. This uniquely identifies this element type within the parse event that it is declared within. This value is assigned by the grammar whose decl pool this object belongs to.
Returns
The element decl id of this element declaration.
Definition at line 508 of file XMLElementDecl.hpp.
References fId.
Referenced by DTDGrammar::getElemId(), and SchemaGrammar::getElemId().
getId() [2/3]
XMLSize_t XMLElementDecl::getId () const
Get the element decl pool id for this element type
This method will return the element decl pool id of this element declaration. This uniquely identifies this element type within the parse event that it is declared within. This value is assigned by the grammar whose decl pool this object belongs to.
Returns
The element decl id of this element declaration.
getId() [3/3]
XMLSize_t XMLElementDecl::getId () const
Get the element decl pool id for this element type
This method will return the element decl pool id of this element declaration. This uniquely identifies this element type within the parse event that it is declared within. This value is assigned by the grammar whose decl pool this object belongs to.
Returns
The element decl id of this element declaration.
getMemoryManager() [1/3]
MemoryManager * XMLElementDecl::getMemoryManager () const inline
Get the memory manager
This method returns the configurable memory manager used by the element declaration for dynamic allocation/deallocation.
Returns
the memory manager
Definition at line 524 of file XMLElementDecl.hpp.
References fMemoryManager.
Referenced by SchemaElementDecl::addIdentityConstraint(), DTDElementDecl::setContentModel(), and SchemaElementDecl::setDefaultValue().
getMemoryManager() [2/3]
MemoryManager* XMLElementDecl::getMemoryManager () const
Get the memory manager
This method returns the configurable memory manager used by the element declaration for dynamic allocation/deallocation.
Returns
the memory manager
getMemoryManager() [3/3]
MemoryManager* XMLElementDecl::getMemoryManager () const
Get the memory manager
This method returns the configurable memory manager used by the element declaration for dynamic allocation/deallocation.
Returns
the memory manager
getObjectType() [1/3]
virtual XMLElementDecl::objectType XMLElementDecl::getObjectType () const pure virtual
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getObjectType() [2/3]
virtual XMLElementDecl::objectType XMLElementDecl::getObjectType () const pure virtual
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getObjectType() [3/3]
virtual XMLElementDecl::objectType XMLElementDecl::getObjectType () const pure virtual
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
getURI() [1/3]
unsigned int XMLElementDecl::getURI () const inline
Get the URI id of this element type.
Return the URI Id of this element.
Returns
The URI Id of the element decl, or the emptyNamespaceId if not applicable.
Definition at line 483 of file XMLElementDecl.hpp.
References fElementName, and QName::getURI().
Referenced by SchemaGrammar::putElemDecl(), and SchemaGrammar::putGroupElemDecl().
getURI() [2/3]
unsigned int XMLElementDecl::getURI () const
Get the URI id of this element type.
Return the URI Id of this element.
Returns
The URI Id of the element decl, or the emptyNamespaceId if not applicable.
getURI() [3/3]
unsigned int XMLElementDecl::getURI () const
Get the URI id of this element type.
Return the URI Id of this element.
Returns
The URI Id of the element decl, or the emptyNamespaceId if not applicable.
hasAttDefs() [1/3]
virtual bool XMLElementDecl::hasAttDefs () const pure virtual
Indicate whether this element type defined any attributes
The derived class should return a boolean that indicates whether this element has any attributes defined for it or not. This is an optimization that allows the scanner to skip some work if no attributes exist.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
hasAttDefs() [2/3]
virtual bool XMLElementDecl::hasAttDefs () const pure virtual
Indicate whether this element type defined any attributes
The derived class should return a boolean that indicates whether this element has any attributes defined for it or not. This is an optimization that allows the scanner to skip some work if no attributes exist.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
hasAttDefs() [3/3]
virtual bool XMLElementDecl::hasAttDefs () const pure virtual
Indicate whether this element type defined any attributes
The derived class should return a boolean that indicates whether this element has any attributes defined for it or not. This is an optimization that allows the scanner to skip some work if no attributes exist.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
isDeclared() [1/3]
bool XMLElementDecl::isDeclared () const inline
Indicate whether this element type has been declared yet
This method returns a boolean that indicates whether this element has been declared yet. There are a number of reasons why an element declaration can be faulted in, but eventually it must be declared or its an error. See the CreateReasons enumeration.
Returns
true if this element has been declared, else false.
Definition at line 513 of file XMLElementDecl.hpp.
References Declared, and fCreateReason.
isDeclared() [2/3]
bool XMLElementDecl::isDeclared () const
Indicate whether this element type has been declared yet
This method returns a boolean that indicates whether this element has been declared yet. There are a number of reasons why an element declaration can be faulted in, but eventually it must be declared or its an error. See the CreateReasons enumeration.
Returns
true if this element has been declared, else false.
isDeclared() [3/3]
bool XMLElementDecl::isDeclared () const
Indicate whether this element type has been declared yet
This method returns a boolean that indicates whether this element has been declared yet. There are a number of reasons why an element declaration can be faulted in, but eventually it must be declared or its an error. See the CreateReasons enumeration.
Returns
true if this element has been declared, else false.
isExternal() [1/3]
bool XMLElementDecl::isExternal () const inline
Indicate whether this element type has been declared externally
This method returns a boolean that indicates whether this element has been declared externally.
Returns
true if this element has been declared externally, else false.
Definition at line 519 of file XMLElementDecl.hpp.
References fExternalElement.
isExternal() [2/3]
bool XMLElementDecl::isExternal () const
Indicate whether this element type has been declared externally
This method returns a boolean that indicates whether this element has been declared externally.
Returns
true if this element has been declared externally, else false.
isExternal() [3/3]
bool XMLElementDecl::isExternal () const
Indicate whether this element type has been declared externally
This method returns a boolean that indicates whether this element has been declared externally.
Returns
true if this element has been declared externally, else false.
loadElementDecl() [1/3]
static XMLElementDecl* XMLElementDecl::loadElementDecl (XSerializeEngine & serEng) static
loadElementDecl() [2/3]
static XMLElementDecl* XMLElementDecl::loadElementDecl (XSerializeEngine & serEng) static
loadElementDecl() [3/3]
static XMLElementDecl* XMLElementDecl::loadElementDecl (XSerializeEngine & serEng) static
operator=() [1/3]
XMLElementDecl& XMLElementDecl::operator= (const XMLElementDecl &) private
operator=() [2/3]
XMLElementDecl& XMLElementDecl::operator= (const XMLElementDecl &) private
operator=() [3/3]
XMLElementDecl& XMLElementDecl::operator= (const XMLElementDecl &) private
setContentModel() [1/3]
virtual void XMLElementDecl::setContentModel (XMLContentModel *const newModelToAdopt) pure virtual
Set the content model object for this element type
This method will adopt the based content model object. This is called by the actual validator which is parsing its DTD or Schema or whatever a creating an element decl. It will build what it feels is the correct content model type object and store it on the element decl object via this method.
Parameters
newModelToAdopt This method will adopt the passed content model object. Any previous object is destroyed.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
setContentModel() [2/3]
virtual void XMLElementDecl::setContentModel (XMLContentModel *const newModelToAdopt) pure virtual
Set the content model object for this element type
This method will adopt the based content model object. This is called by the actual validator which is parsing its DTD or Schema or whatever a creating an element decl. It will build what it feels is the correct content model type object and store it on the element decl object via this method.
Parameters
newModelToAdopt This method will adopt the passed content model object. Any previous object is destroyed.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
setContentModel() [3/3]
virtual void XMLElementDecl::setContentModel (XMLContentModel *const newModelToAdopt) pure virtual
Set the content model object for this element type
This method will adopt the based content model object. This is called by the actual validator which is parsing its DTD or Schema or whatever a creating an element decl. It will build what it feels is the correct content model type object and store it on the element decl object via this method.
Parameters
newModelToAdopt This method will adopt the passed content model object. Any previous object is destroyed.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
setContentSpec() [1/3]
virtual void XMLElementDecl::setContentSpec (ContentSpecNode * toAdopt) pure virtual
Set the content spec node object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
toAdopt This method will adopt the passed content node spec object. Any previous object is destroyed.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
setContentSpec() [2/3]
virtual void XMLElementDecl::setContentSpec (ContentSpecNode * toAdopt) pure virtual
Set the content spec node object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
toAdopt This method will adopt the passed content node spec object. Any previous object is destroyed.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
setContentSpec() [3/3]
virtual void XMLElementDecl::setContentSpec (ContentSpecNode * toAdopt) pure virtual
Set the content spec node object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
toAdopt This method will adopt the passed content node spec object. Any previous object is destroyed.
Implemented in SchemaElementDecl, DTDElementDecl, SchemaElementDecl, DTDElementDecl, SchemaElementDecl, and DTDElementDecl.
setCreateReason() [1/3]
void XMLElementDecl::setCreateReason (const CreateReasons newReason) inline
Update the create reason for this element type.
This method will update the 'create reason' field for this element decl object. As the validator parses its DTD, Schema, etc... it will encounter various references to an element declaration, which will cause the element declaration to either be declared or to be faulted into the pool in preparation for some future declaration. As it does so,it will update this field to indicate the current status of the decl object.
Definition at line 534 of file XMLElementDecl.hpp.
References fCreateReason.
setCreateReason() [2/3]
void XMLElementDecl::setCreateReason (const CreateReasons newReason)
Update the create reason for this element type.
This method will update the 'create reason' field for this element decl object. As the validator parses its DTD, Schema, etc... it will encounter various references to an element declaration, which will cause the element declaration to either be declared or to be faulted into the pool in preparation for some future declaration. As it does so,it will update this field to indicate the current status of the decl object.
setCreateReason() [3/3]
void XMLElementDecl::setCreateReason (const CreateReasons newReason)
Update the create reason for this element type.
This method will update the 'create reason' field for this element decl object. As the validator parses its DTD, Schema, etc... it will encounter various references to an element declaration, which will cause the element declaration to either be declared or to be faulted into the pool in preparation for some future declaration. As it does so,it will update this field to indicate the current status of the decl object.
setElementName() [1/9]
void XMLElementDecl::setElementName (const QName *const elementName)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
elementName QName of the element
setElementName() [2/9]
void XMLElementDecl::setElementName (const QName *const elementName)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
elementName QName of the element
setElementName() [3/9]
void XMLElementDecl::setElementName (const QName *const elementName)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
elementName QName of the element
setElementName() [4/9]
void XMLElementDecl::setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
prefix Prefix of the element
localPart Base Name of the element
uriId The uriId of the element
setElementName() [5/9]
void XMLElementDecl::setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
prefix Prefix of the element
localPart Base Name of the element
uriId The uriId of the element
setElementName() [6/9]
void XMLElementDecl::setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
prefix Prefix of the element
localPart Base Name of the element
uriId The uriId of the element
setElementName() [7/9]
void XMLElementDecl::setElementName (const XMLCh *const rawName, const int uriId)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
rawName Full Name of the element
uriId The uriId of the element
setElementName() [8/9]
void XMLElementDecl::setElementName (const XMLCh *const rawName, const int uriId)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
rawName Full Name of the element
uriId The uriId of the element
setElementName() [9/9]
void XMLElementDecl::setElementName (const XMLCh *const rawName, const int uriId)
Set the element name object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
rawName Full Name of the element
uriId The uriId of the element
setExternalElemDeclaration() [1/3]
void XMLElementDecl::setExternalElemDeclaration (const bool aValue) inline
Set the element decl to indicate external declaration
Definition at line 545 of file XMLElementDecl.hpp.
References fExternalElement.
setExternalElemDeclaration() [2/3]
void XMLElementDecl::setExternalElemDeclaration (const bool aValue)
Set the element decl to indicate external declaration
setExternalElemDeclaration() [3/3]
void XMLElementDecl::setExternalElemDeclaration (const bool aValue)
Set the element decl to indicate external declaration
setId() [1/3]
void XMLElementDecl::setId (const XMLSize_t newId) inline
Set the element decl pool id for this element type
This method will set the pool id of this element decl. This is called by the grammar which created this object, and will provide this decl object with a unique id within the parse event that created it.
Definition at line 539 of file XMLElementDecl.hpp.
References fId.
setId() [2/3]
void XMLElementDecl::setId (const XMLSize_t newId)
Set the element decl pool id for this element type
This method will set the pool id of this element decl. This is called by the grammar which created this object, and will provide this decl object with a unique id within the parse event that created it.
setId() [3/3]
void XMLElementDecl::setId (const XMLSize_t newId)
Set the element decl pool id for this element type
This method will set the pool id of this element decl. This is called by the grammar which created this object, and will provide this decl object with a unique id within the parse event that created it.
storeElementDecl() [1/3]
static void XMLElementDecl::storeElementDecl (XSerializeEngine & serEng, XMLElementDecl *const element) static
storeElementDecl() [2/3]
static void XMLElementDecl::storeElementDecl (XSerializeEngine & serEng, XMLElementDecl *const element) static
storeElementDecl() [3/3]
static void XMLElementDecl::storeElementDecl (XSerializeEngine & serEng, XMLElementDecl *const element) static
Member Data Documentation
fCreateReason
CreateReasons XMLElementDecl::fCreateReason private
Definition at line 464 of file XMLElementDecl.hpp.
Referenced by getCreateReason(), isDeclared(), and setCreateReason().
fElementName
QName * XMLElementDecl::fElementName private
Definition at line 463 of file XMLElementDecl.hpp.
Referenced by getBaseName(), getElementName(), getFullName(), and getURI().
fExternalElement
bool XMLElementDecl::fExternalElement private
Definition at line 466 of file XMLElementDecl.hpp.
Referenced by isExternal(), and setExternalElemDeclaration().
fgInvalidElemId
static const unsigned int XMLElementDecl::fgInvalidElemId static
Definition at line 101 of file XMLElementDecl.hpp.
Referenced by MixedContentModel::checkUniqueParticleAttribution(), CMLeaf::CMLeaf(), DTDGrammar::getElemId(), SchemaGrammar::getElemId(), and SimpleContentModel::SimpleContentModel().
fgPCDataElemId
static const unsigned int XMLElementDecl::fgPCDataElemId static
Definition at line 102 of file XMLElementDecl.hpp.
Referenced by MixedContentModel::checkUniqueParticleAttribution().
fgPCDataElemName
static const XMLCh XMLElementDecl::fgPCDataElemName static
Definition at line 103 of file XMLElementDecl.hpp.
fId
XMLSize_t XMLElementDecl::fId private
Definition at line 465 of file XMLElementDecl.hpp.
Referenced by getId(), and setId().
fMemoryManager
MemoryManager * XMLElementDecl::fMemoryManager private
Definition at line 462 of file XMLElementDecl.hpp.
Referenced by getMemoryManager().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/XMLElementDecl.hpp