Seamly2D: src/libs/vmisc/vseamlymesettings.cpp File Reference
vseamlymesettings.cpp File Reference
#include "vseamlymesettings.h"
#include <QStaticStringData>
#include <QStringData>
#include <QStringDataPtr>
#include <QVariant>
Variables
const QString settingDataBaseGeometry = QStringLiteral("database/geometry")
const QString settingDefHeight = QStringLiteral("gradation/defHeight")
const QString settingDefSize = QStringLiteral("gradation/defSize")
Variable Documentation
settingDataBaseGeometry
const QString settingDataBaseGeometry = QStringLiteral("database/geometry")
Definition at line 59 of file vseamlymesettings.cpp.
Referenced by VSeamlyMeSettings::getDataBaseGeometry(), and VSeamlyMeSettings::setDataBaseGeometry().
settingDefHeight
const QString settingDefHeight = QStringLiteral("gradation/defHeight")
Definition at line 61 of file vseamlymesettings.cpp.
Referenced by VSeamlyMeSettings::GetDefHeight(), and VSeamlyMeSettings::SetDefHeight().
settingDefSize
const QString settingDefSize = QStringLiteral("gradation/defSize")
Definition at line 62 of file vseamlymesettings.cpp.
Referenced by VSeamlyMeSettings::GetDefSize(), and VSeamlyMeSettings::SetDefSize().