Seamly2D: TST_VSpline Class Reference
TST_VSpline Class Reference
#include <tst_vspline.h>
Public Member Functions
TST_VSpline (QObject *parent=nullptr)
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Private Slots
void GetSegmentPoints ()
void GetSegmentPoints_issue412 ()
void GetSegmentPoints_TestPuzzle ()
void GetSegmentPoints_NullSegment ()
void GetSegmentPoints_RotateTool ()
void CompareThreeWays ()
void TestParametrT ()
void TestLengthByPoint_data ()
void TestLengthByPoint ()
void TestFlip_data ()
void TestFlip ()
Private Member Functions
void CompareSplines (const VSpline &spl1, const VSpline &spl2) const
Additional Inherited Members
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Detailed Description
Definition at line 59 of file tst_vspline.h.
Constructor & Destructor Documentation
TST_VSpline()
TST_VSpline::TST_VSpline (QObject * parent = nullptr) explicit
Definition at line 63 of file tst_vspline.cpp.
Member Function Documentation
CompareSplines()
void TST_VSpline::CompareSplines (const VSpline & spl1, const VSpline & spl2) const private
Definition at line 462 of file tst_vspline.cpp.
References AbstractTest::Comparison(), VSpline::GetC1Length(), VSpline::GetC2Length(), VSpline::GetEndAngle(), VSpline::GetKasm1(), VSpline::GetKasm2(), VSpline::GetKcurve(), VSpline::GetLength(), VSpline::GetP1(), VSpline::GetP2(), VSpline::GetP3(), VSpline::GetP4(), VSpline::getPoints(), VSpline::GetStartAngle(), and VPointF::toQPointF().
Referenced by CompareThreeWays().
CompareThreeWays
void TST_VSpline::CompareThreeWays () private slot
Definition at line 347 of file tst_vspline.cpp.
References CompareSplines(), VSpline::GetC1Length(), VSpline::GetC2Length(), VSpline::GetEndAngle(), VSpline::GetP1(), VSpline::GetP2(), VSpline::GetP3(), VSpline::GetP4(), and VSpline::GetStartAngle().
GetSegmentPoints
void TST_VSpline::GetSegmentPoints () private slot
Definition at line 69 of file tst_vspline.cpp.
References AbstractTest::Comparison(), and VAbstractCurve::GetSegmentPoints().
GetSegmentPoints_issue412
void TST_VSpline::GetSegmentPoints_issue412 () private slot
Definition at line 121 of file tst_vspline.cpp.
References AbstractTest::Comparison(), and VAbstractCurve::GetSegmentPoints().
GetSegmentPoints_NullSegment
void TST_VSpline::GetSegmentPoints_NullSegment () private slot
Definition at line 211 of file tst_vspline.cpp.
References AbstractTest::Comparison(), and VAbstractCurve::GetSegmentPoints().
GetSegmentPoints_RotateTool
void TST_VSpline::GetSegmentPoints_RotateTool () private slot
Definition at line 301 of file tst_vspline.cpp.
References AbstractTest::Comparison(), and VAbstractCurve::GetSegmentPoints().
GetSegmentPoints_TestPuzzle
void TST_VSpline::GetSegmentPoints_TestPuzzle () private slot
Definition at line 160 of file tst_vspline.cpp.
References AbstractTest::Comparison(), and VAbstractCurve::GetSegmentPoints().
TestFlip
void TST_VSpline::TestFlip () private slot
Definition at line 445 of file tst_vspline.cpp.
References VSpline::Flip(), VSpline::GetC1Length(), VSpline::GetC2Length(), VSpline::GetLength(), and VGObject::name().
TestFlip_data
void TST_VSpline::TestFlip_data () private slot
Definition at line 419 of file tst_vspline.cpp.
TestLengthByPoint
void TST_VSpline::TestLengthByPoint () private slot
Definition at line 407 of file tst_vspline.cpp.
References Mm, and ToPixel().
TestLengthByPoint_data
void TST_VSpline::TestLengthByPoint_data () private slot
Definition at line 384 of file tst_vspline.cpp.
References VSpline::CutSpline(), VSpline::GetLength(), and VPointF::toQPointF().
TestParametrT
void TST_VSpline::TestParametrT () private slot
Definition at line 370 of file tst_vspline.cpp.
References VSpline::GetLength(), VAbstractCubicBezier::GetParmT(), VAbstractCubicBezier::LengthT(), Mm, Px, and UnitConvertor().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vspline.h
src/test/Seamly2DTest/tst_vspline.cpp