Seamly2D: VPiece Class Reference
VPiece Class Reference
#include <vpiece.h>
Public Member Functions
VPiece ()
VPiece (const VPiece &piece)
virtual ~VPiece ()
VPiece & operator= (const VPiece &piece)
void Swap (VPiece &piece) Q_DECL_NOTHROW
VPiecePath GetPath () const
VPiecePath & GetPath ()
void SetPath (const VPiecePath &path)
QVector< QPointF > MainPathPoints (const VContainer *data) const
QVector< VPointF > MainPathNodePoints (const VContainer *data, bool showExcluded=false) const
QVector< QPointF > SeamAllowancePoints (const VContainer *data) const
QVector< QLineF > createNotchLines (const VContainer *data, const QVector< QPointF > &seamAllowance=QVector< QPointF >()) const
QPainterPath MainPathPath (const VContainer *data) const
QPainterPath SeamAllowancePath (const VContainer *data) const
QPainterPath SeamAllowancePath (const QVector< QPointF > &points) const
QPainterPath getNotchesPath (const VContainer *data, const QVector< QPointF > &seamAllowance=QVector< QPointF >()) const
bool isInLayout () const
void SetInLayout (bool inLayout)
bool isLocked () const
void setIsLocked (bool isLocked)
bool IsUnited () const
void SetUnited (bool united)
QString getSeamAllowanceWidthFormula () const
void setSeamAllowanceWidthFormula (const QString &formula, qreal value)
QVector< quint32 > GetInternalPaths () const
QVector< quint32 > & GetInternalPaths ()
void SetInternalPaths (const QVector< quint32 > &iPaths)
QVector< CustomSARecord > GetCustomSARecords () const
QVector< CustomSARecord > & GetCustomSARecords ()
void SetCustomSARecords (const QVector< CustomSARecord > &records)
QVector< quint32 > getAnchors () const
QVector< quint32 > & getAnchors ()
void setAnchors (const QVector< quint32 > &anchors)
QVector< quint32 > MissingNodes (const VPiece &piece) const
MissingNodes find missing nodes in piece. When we deleted object in piece and return this piece need understand, what nodes need make invisible.
QVector< quint32 > MissingCSAPath (const VPiece &piece) const
QVector< quint32 > MissingInternalPaths (const VPiece &piece) const
QVector< quint32 > missingAnchors (const VPiece &piece) const
void SetPatternPieceData (const VPieceLabelData &data)
VPieceLabelData & GetPatternPieceData ()
Returns full access to the pattern piece data object.
const VPieceLabelData & GetPatternPieceData () const
Returns the read only reference to the pattern piece data object.
void SetPatternInfo (const VPatternLabelData &info)
VPatternLabelData & GetPatternInfo ()
Returns full access to the pattern info geometry object.
const VPatternLabelData & GetPatternInfo () const
Returns the read only reference to the pattern info geometry object.
VGrainlineData & GetGrainlineGeometry ()
VDetail::GetGrainlineGeometry full access to the grainline geometry object.
const VGrainlineData & GetGrainlineGeometry () const
VDetail::GetGrainlineGeometry returns the read-only reference to the grainline geometry object.
Public Member Functions inherited from VAbstractPiece
VAbstractPiece ()
VAbstractPiece (const VAbstractPiece &piece)
virtual ~VAbstractPiece ()
VAbstractPiece & operator= (const VAbstractPiece &piece)
void Swap (VAbstractPiece &piece) Q_DECL_NOTHROW
QString GetName () const
void SetName (const QString &value)
QString getColor () const
void setColor (const QString &value)
QString getFill () const
void setFill (const QString &value)
bool getLock () const
void setLock (bool value)
bool IsForbidFlipping () const
void SetForbidFlipping (bool value)
bool IsSeamAllowance () const
void SetSeamAllowance (bool value)
bool IsSeamAllowanceBuiltIn () const
void SetSeamAllowanceBuiltIn (bool value)
bool isHideSeamLine () const
void setHideSeamLine (bool value)
qreal GetSAWidth () const
void SetSAWidth (qreal value)
qreal GetMx () const
void SetMx (qreal value)
qreal GetMy () const
void SetMy (qreal value)
Private Member Functions
QVector< VPieceNode > GetUnitedPath (const VContainer *data) const
QVector< CustomSARecord > GetValidRecords () const
QVector< CustomSARecord > FilterRecords (QVector< CustomSARecord > records) const
QVector< VSAPoint > getNodeSAPoints (const QVector< VPieceNode > &path, int index, const VContainer *data) const
bool getNotchSAPoint (const QVector< VPieceNode > &path, int index, const VContainer *data, VSAPoint &point) const
bool getNotchPreviousSAPoints (const QVector< VPieceNode > &path, int index, const VSAPoint &notchSAPoint, const VContainer *data, VSAPoint &point) const
int getNextNotchSAPoints (const QVector< VPieceNode > &path, int index, const VSAPoint &notchSAPoint, const VContainer *data, VSAPoint &point) const
bool getSeamNotchSAPoint (const VSAPoint &previousSAPoint, const VSAPoint &notchSAPoint, const VSAPoint &nextSAPoint, const VContainer *data, QPointF &point) const
bool isNotchVisible (const QVector< VPieceNode > &path, int notchIndex) const
QVector< QLineF > createNotch (const QVector< VPieceNode > &path, int previousIndex, int notchIndex, int nextIndex, const VContainer *data, const QVector< QPointF > &pathPoints=QVector< QPointF >()) const
QVector< QLineF > createSeamAllowanceNotch (const QVector< VPieceNode > &path, VSAPoint &previousSAPoint, const VSAPoint &notchSAPoint, VSAPoint &nextSAPoint, const VContainer *data, int notchIndex, const QVector< QPointF > &pathPoints=QVector< QPointF >()) const
QVector< QLineF > createBuiltInSaNotch (const QVector< VPieceNode > &path, const VSAPoint &previousSAPoint, const VSAPoint &notchSAPoint, const VSAPoint &nextSAPoint, const VContainer *data, int notchIndex, const QVector< QPointF > &pathPoints) const
QVector< QLineF > createSlitNotch (NotchData notchData, const QVector< QPointF > &seamAllowance) const
QVector< QLineF > createTNotch (NotchData notchData, const QVector< QPointF > &pathPoints) const
QVector< QLineF > createUNotch (const NotchData notchData, const QVector< QPointF > &seamAllowance) const
QVector< QLineF > createVInternalNotch (NotchData notchData, const QVector< QPointF > &pathPoints) const
QVector< QLineF > createVExternalNotch (NotchData notchData, const QVector< QPointF > &seamAllowance) const
QVector< QLineF > createCastleNotch (const NotchData notchData, const QVector< QPointF > &seamAllowance) const
QVector< QLineF > createDiamondNotch (NotchData notchData, const QVector< QPointF > &seamAllowance) const
QVector< QLineF > createNotches (NotchData notchData, const QVector< QPointF > &seamAllowance) const
QLineF findIntersection (const QVector< QPointF > &seamAllowance, const QLineF &line) const
Static Private Member Functions
static int IsCSAStart (const QVector< CustomSARecord > &records, quint32 id)
Private Attributes
QSharedDataPointer< VPieceData > d
Additional Inherited Members
Static Public Member Functions inherited from VAbstractPiece
static QVector< QPointF > Equidistant (const QVector< VSAPoint > &points, qreal width)
static qreal sumTrapezoids (const QVector< QPointF > &points)
static bool isClockwise (const QVector< QPointF > &points)
static QVector< QPointF > CheckLoops (const QVector< QPointF > &points)
CheckLoops seek and delete loops in equidistant.
static QVector< QPointF > EkvPoint (const VSAPoint &p1Line1, const VSAPoint &p2Line1, const VSAPoint &p1Line2, const VSAPoint &p2Line2, qreal width)
EkvPoint return seam allowance points in place of intersection of two edges. Last points of two edges should be equal.
static QLineF createParallelLine (const VSAPoint &p1, const VSAPoint &p2, qreal width)
static QLineF createParallelLine (const QPointF &p1, const QPointF &p2, qreal width)
template<class T >
static QVector< T > CorrectEquidistantPoints (const QVector< T > &points, bool removeFirstAndLast=true)
CorrectEquidistantPoints clear equivalent points and remove point on line from equdistant.
Static Protected Member Functions inherited from VAbstractPiece
template<class T >
static QVector< T > RemoveDublicates (const QVector< T > &points, bool removeFirstAndLast=true)
static qreal MaxLocalSA (const VSAPoint &p, qreal width)
static bool IsEkvPointOnLine (const QPointF &iPoint, const QPointF &prevPoint, const QPointF &nextPoint)
static bool IsEkvPointOnLine (const VSAPoint &iPoint, const VSAPoint &prevPoint, const VSAPoint &nextPoint)
Detailed Description
Definition at line 87 of file vpiece.h.
Constructor & Destructor Documentation
VPiece() [1/2]
VPiece::VPiece ()
Definition at line 128 of file vpiece.cpp.
References PiecePath.
VPiece() [2/2]
VPiece::VPiece (const VPiece & piece)
Definition at line 134 of file vpiece.cpp.
~VPiece()
VPiece::~VPiece () virtual
Definition at line 152 of file vpiece.cpp.
Member Function Documentation
createBuiltInSaNotch()
QVector< QLineF > VPiece::createBuiltInSaNotch (const QVector< VPieceNode > & path, const VSAPoint & previousSAPoint, const VSAPoint & notchSAPoint, const VSAPoint & nextSAPoint, const VContainer * data, int notchIndex, const QVector< QPointF > & pathPoints) const private
Definition at line 1074 of file vpiece.cpp.
References NotchData::angle, NotchData::count, createNotches(), VPieceNode::getNotchAngle(), VPieceNode::getNotchCount(), VPieceNode::getNotchLength(), VPieceNode::getNotchSubType(), VPieceNode::getNotchType(), VPieceNode::getNotchWidth(), VContainer::GetPatternUnit(), NotchData::length, NotchData::line, NotchData::subType, ToPixel(), NotchData::type, and NotchData::width.
Referenced by createNotch().
createCastleNotch()
QVector< QLineF > VPiece::createCastleNotch (const NotchData notchData, const QVector< QPointF > & seamAllowance) const private
Definition at line 1270 of file vpiece.cpp.
References NotchData::angle, VAbstractPiece::createParallelLine(), findIntersection(), NotchData::line, NotchData::offset, and NotchData::width.
Referenced by createNotches().
createDiamondNotch()
QVector< QLineF > VPiece::createDiamondNotch (NotchData notchData, const QVector< QPointF > & seamAllowance) const private
Definition at line 1292 of file vpiece.cpp.
References NotchData::angle, and createVExternalNotch().
Referenced by createNotches().
createNotch()
QVector< QLineF > VPiece::createNotch (const QVector< VPieceNode > & path, int previousIndex, int notchIndex, int nextIndex, const VContainer * data, const QVector< QPointF > & pathPoints = QVector<QPointF>()) const private
Definition at line 929 of file vpiece.cpp.
References createBuiltInSaNotch(), createSeamAllowanceNotch(), getNextNotchSAPoints(), getNotchPreviousSAPoints(), getNotchSAPoint(), Intersection, VAbstractPiece::isHideSeamLine(), isNotchVisible(), VAbstractPiece::IsSeamAllowanceBuiltIn(), MainPathPoints(), and SCASSERT.
Referenced by createNotchLines().
createNotches()
QVector< QLineF > VPiece::createNotches (NotchData notchData, const QVector< QPointF > & seamAllowance) const private
Definition at line 1308 of file vpiece.cpp.
References Castle, NotchData::count, createCastleNotch(), createDiamondNotch(), createSlitNotch(), createTNotch(), createUNotch(), createVExternalNotch(), createVInternalNotch(), Diamond, NotchData::offset, Slit, Straightforward, NotchData::subType, TNotch, NotchData::type, UNotch, VExternal, VInternal, and NotchData::width.
Referenced by createBuiltInSaNotch(), and createSeamAllowanceNotch().
createNotchLines()
QVector< QLineF > VPiece::createNotchLines (const VContainer * data, const QVector< QPointF > & seamAllowance = QVector<QPointF>()) const
Definition at line 275 of file vpiece.cpp.
References createNotch(), VPiecePath::FindInLoopNotExcludedDown(), VPiecePath::FindInLoopNotExcludedUp(), GetUnitedPath(), VPieceNode::isExcluded(), VPieceNode::isNotch(), and anonymous_namespace{vpiece.cpp}::notchesPossible().
Referenced by VLayoutPiece::Create(), and getNotchesPath().
createSeamAllowanceNotch()
QVector< QLineF > VPiece::createSeamAllowanceNotch (const QVector< VPieceNode > & path, VSAPoint & previousSAPoint, const VSAPoint & notchSAPoint, VSAPoint & nextSAPoint, const VContainer * data, int notchIndex, const QVector< QPointF > & pathPoints = QVector<QPointF>()) const private
Definition at line 984 of file vpiece.cpp.
References NotchData::angle, Bisector, NotchData::count, createNotches(), VAbstractPiece::createParallelLine(), VAbstractCurve::CurveIntersectLine(), VPieceNode::getNotchAngle(), VPieceNode::getNotchCount(), VPieceNode::getNotchLength(), VPieceNode::getNotchSubType(), VPieceNode::getNotchType(), VPieceNode::getNotchWidth(), VContainer::GetPatternUnit(), getSeamNotchSAPoint(), Intersection, NotchData::length, NotchData::line, SeamAllowancePoints(), Straightforward, NotchData::subType, ToPixel(), NotchData::type, and NotchData::width.
Referenced by createNotch().
createSlitNotch()
QVector< QLineF > VPiece::createSlitNotch (NotchData notchData, const QVector< QPointF > & seamAllowance) const private
Definition at line 1117 of file vpiece.cpp.
References NotchData::angle, VAbstractPiece::createParallelLine(), findIntersection(), NotchData::line, and NotchData::offset.
Referenced by createNotches().
createTNotch()
QVector< QLineF > VPiece::createTNotch (NotchData notchData, const QVector< QPointF > & pathPoints) const private
Definition at line 1132 of file vpiece.cpp.
References NotchData::angle, VAbstractPiece::createParallelLine(), findIntersection(), NotchData::length, NotchData::line, NotchData::offset, and NotchData::width.
Referenced by createNotches().
createUNotch()
QVector< QLineF > VPiece::createUNotch (const NotchData notchData, const QVector< QPointF > & seamAllowance) const private
Definition at line 1169 of file vpiece.cpp.
References NotchData::angle, VAbstractPiece::createParallelLine(), findIntersection(), VArc::getSegments(), NotchData::length, NotchData::line, NotchData::offset, and NotchData::width.
Referenced by createNotches().
createVExternalNotch()
QVector< QLineF > VPiece::createVExternalNotch (NotchData notchData, const QVector< QPointF > & seamAllowance) const private
Definition at line 1237 of file vpiece.cpp.
References NotchData::angle, VAbstractPiece::createParallelLine(), findIntersection(), NotchData::line, NotchData::offset, and NotchData::width.
Referenced by createDiamondNotch(), and createNotches().
createVInternalNotch()
QVector< QLineF > VPiece::createVInternalNotch (NotchData notchData, const QVector< QPointF > & pathPoints) const private
Definition at line 1200 of file vpiece.cpp.
References NotchData::angle, VAbstractPiece::createParallelLine(), findIntersection(), NotchData::length, NotchData::line, NotchData::offset, and NotchData::width.
Referenced by createNotches().
FilterRecords()
QVector< CustomSARecord > VPiece::FilterRecords (QVector< CustomSARecord > records) const private
Definition at line 680 of file vpiece.cpp.
References d, and CustomSARecord::endPoint.
Referenced by GetUnitedPath(), isNotchVisible(), and SeamAllowancePoints().
findIntersection()
QLineF VPiece::findIntersection (const QVector< QPointF > & seamAllowance, const QLineF & line) const private
Definition at line 1502 of file vpiece.cpp.
References VAbstractCurve::CurveIntersectLine().
Referenced by createCastleNotch(), createSlitNotch(), createTNotch(), createUNotch(), createVExternalNotch(), and createVInternalNotch().
getAnchors() [1/2]
QVector< quint32 > & VPiece::getAnchors ()
Definition at line 468 of file vpiece.cpp.
References d.
getAnchors() [2/2]
QVector< quint32 > VPiece::getAnchors () const
Definition at line 462 of file vpiece.cpp.
References d.
Referenced by UnionTool::addPiece(), AnchorPointTool::AddToFile(), PatternPieceTool::AddToFile(), QT_WARNING_POP::createUnionAnchors(), QT_WARNING_POP::createUnitedAnchors(), PatternPieceTool::initializeAnchorPoints(), missingAnchors(), DeletePiece::redo(), SavePieceOptions::redo(), PatternPieceTool::RefreshDataInFile(), PatternPieceDialog::SetPiece(), AddPiece::undo(), and SavePieceOptions::undo().
GetCustomSARecords() [1/2]
QVector< CustomSARecord > & VPiece::GetCustomSARecords ()
Definition at line 450 of file vpiece.cpp.
References d.
GetCustomSARecords() [2/2]
QVector< CustomSARecord > VPiece::GetCustomSARecords () const
Definition at line 444 of file vpiece.cpp.
References d.
Referenced by UnionTool::addPiece(), VToolInternalPath::AddToFile(), PatternPieceTool::AddToFile(), QT_WARNING_POP::createCSAUnion(), QT_WARNING_POP::CreateUnitedCSA(), PatternPieceTool::InitCSAPaths(), MissingCSAPath(), DeletePiece::redo(), SavePieceOptions::redo(), PatternPieceTool::RefreshDataInFile(), PatternPieceDialog::SetPiece(), AddPiece::undo(), and SavePieceOptions::undo().
GetGrainlineGeometry() [1/2]
VGrainlineData & VPiece::GetGrainlineGeometry ()
VDetail::GetGrainlineGeometry full access to the grainline geometry object.
Returns
reference to grainline geometry object
Definition at line 578 of file vpiece.cpp.
References d.
Referenced by PatternPieceTool::AddGrainline(), PatternPieceTool::contextMenuEvent(), VLayoutPiece::Create(), PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), PatternPieceTool::keyReleaseEvent(), VPattern::ParsePieceGrainline(), PatternPieceTool::ResetChildren(), PatternPieceTool::SaveMoveGrainline(), PatternPieceTool::SaveResizeGrainline(), PatternPieceTool::SaveRotateGrainline(), PatternPieceDialog::SetPiece(), PatternPieceTool::toggleGrainline(), and PatternPieceTool::UpdateGrainline().
GetGrainlineGeometry() [2/2]
const VGrainlineData & VPiece::GetGrainlineGeometry () const
VDetail::GetGrainlineGeometry returns the read-only reference to the grainline geometry object.
Returns
reference to grainline geometry object
Definition at line 588 of file vpiece.cpp.
References d.
GetInternalPaths() [1/2]
QVector< quint32 > & VPiece::GetInternalPaths ()
Definition at line 432 of file vpiece.cpp.
References d.
GetInternalPaths() [2/2]
QVector< quint32 > VPiece::GetInternalPaths () const
Definition at line 426 of file vpiece.cpp.
References d.
Referenced by UnionTool::addPiece(), VToolInternalPath::AddToFile(), PatternPieceTool::AddToFile(), anonymous_namespace{vlayoutpiece.cpp}::ConvertInternalPaths(), QT_WARNING_POP::createUnionInternalPaths(), QT_WARNING_POP::CreateUnitedInternalPaths(), PatternPieceTool::InitInternalPaths(), MissingInternalPaths(), DeletePiece::redo(), SavePieceOptions::redo(), PatternPieceTool::RefreshDataInFile(), PatternPieceDialog::SetPiece(), AddPiece::undo(), and SavePieceOptions::undo().
getNextNotchSAPoints()
int VPiece::getNextNotchSAPoints (const QVector< VPieceNode > & path, int index, const VSAPoint & notchSAPoint, const VContainer * data, VSAPoint & point) const private
Definition at line 808 of file vpiece.cpp.
References getNodeSAPoints(), and SCASSERT.
Referenced by createNotch().
getNodeSAPoints()
QVector< VSAPoint > VPiece::getNodeSAPoints (const QVector< VPieceNode > & path, int index, const VContainer * data) const private
Definition at line 731 of file vpiece.cpp.
References VPiecePath::CurveSeamAllowanceSegment(), VContainer::GeometricObject(), VPieceNode::GetId(), VContainer::GetPatternUnit(), VPieceNode::GetReverse(), VAbstractPiece::GetSAWidth(), VPieceNode::GetTypeTool(), NodePoint, VPiecePath::PreparePointEkv(), SCASSERT, and ToPixel().
Referenced by getNextNotchSAPoints(), getNotchPreviousSAPoints(), and getNotchSAPoint().
getNotchesPath()
QPainterPath VPiece::getNotchesPath (const VContainer * data, const QVector< QPointF > & seamAllowance = QVector<QPointF>()) const
Definition at line 352 of file vpiece.cpp.
References createNotchLines(), and VAbstractPiece::IsSeamAllowance().
Referenced by PatternPieceTool::RefreshGeometry().
getNotchPreviousSAPoints()
bool VPiece::getNotchPreviousSAPoints (const QVector< VPieceNode > & path, int index, const VSAPoint & notchSAPoint, const VContainer * data, VSAPoint & point) const private
Definition at line 775 of file vpiece.cpp.
References getNodeSAPoints(), and SCASSERT.
Referenced by createNotch().
getNotchSAPoint()
bool VPiece::getNotchSAPoint (const QVector< VPieceNode > & path, int index, const VContainer * data, VSAPoint & point) const private
Definition at line 758 of file vpiece.cpp.
References getNodeSAPoints(), and SCASSERT.
Referenced by createNotch().
GetPath() [1/2]
VPiecePath & VPiece::GetPath ()
Definition at line 162 of file vpiece.cpp.
References d.
GetPath() [2/2]
VPiecePath VPiece::GetPath () const
Definition at line 156 of file vpiece.cpp.
References d.
Referenced by VAbstractTool::AddNodes(), UnionDialog::CheckObject(), UnionDialog::checkPiece(), PatternPieceDialog::ChosenObject(), UnionDialog::chosenPiece(), TST_VPiece::ClearLoop(), PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), QT_WARNING_POP::CreateUnitedNodes(), PatternPieceTool::EnableToolMove(), PatternPieceTool::initializeNodes(), PatternPieceTool::insertNodes(), TST_VPiece::Issue620(), MainPathNodePoints(), MainPathPoints(), MissingNodes(), PatternPieceDialog::nodeChanged(), PatternPieceDialog::notchChanged(), VPattern::parsePieceNodes(), PatternPieceTool::pieceLockedChanged(), DeletePiece::redo(), PatternPieceVisual::RefreshGeometry(), PatternPieceDialog::SetPiece(), AddPiece::undo(), QT_WARNING_POP::unitePieces(), and PatternPieceTool::UpdateExcludeState().
GetPatternInfo() [1/2]
VPatternLabelData & VPiece::GetPatternInfo ()
Returns full access to the pattern info geometry object.
Returns
pattern info geometry object
Definition at line 558 of file vpiece.cpp.
References d.
Referenced by PatternPieceTool::AddPatternInfo(), PatternPieceTool::contextMenuEvent(), VLayoutPiece::Create(), PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), PatternPieceTool::keyReleaseEvent(), VPattern::ParsePiecePatternInfo(), PatternPieceTool::ResetChildren(), PatternPieceTool::SaveMovePattern(), PatternPieceTool::SaveResizePattern(), PatternPieceTool::SaveRotationPattern(), PatternPieceDialog::SetPiece(), PatternPieceTool::togglePatternLabel(), and PatternPieceTool::UpdatePatternLabel().
GetPatternInfo() [2/2]
const VPatternLabelData & VPiece::GetPatternInfo () const
Returns the read only reference to the pattern info geometry object.
Returns
pattern info geometry object
Definition at line 568 of file vpiece.cpp.
References d.
GetPatternPieceData() [1/2]
VPieceLabelData & VPiece::GetPatternPieceData ()
Returns full access to the pattern piece data object.
Returns
pattern piece data object
Definition at line 532 of file vpiece.cpp.
References d.
Referenced by PatternPieceTool::AddPatternPieceData(), PatternPieceTool::contextMenuEvent(), VLayoutPiece::Create(), PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), PiecesWidget::formatLetterString(), PatternPieceTool::keyReleaseEvent(), VPattern::ParsePieceDataTag(), PatternPieceTool::ResetChildren(), PatternPieceTool::saveMovePiece(), PatternPieceTool::savePieceRotation(), PatternPieceTool::saveResizePiece(), EditLabelTemplateDialog::SetPiece(), PatternPieceDialog::SetPiece(), PatternPieceTool::togglePieceLabel(), and PatternPieceTool::UpdatePieceLabel().
GetPatternPieceData() [2/2]
const VPieceLabelData & VPiece::GetPatternPieceData () const
Returns the read only reference to the pattern piece data object.
Returns
pattern piece data object
Definition at line 542 of file vpiece.cpp.
References d.
getSeamAllowanceWidthFormula()
QString VPiece::getSeamAllowanceWidthFormula () const
Definition at line 412 of file vpiece.cpp.
References d.
Referenced by PatternPieceTool::AddAttributes(), QT_WARNING_POP::createUnion(), and PatternPieceDialog::SetPiece().
getSeamNotchSAPoint()
bool VPiece::getSeamNotchSAPoint (const VSAPoint & previousSAPoint, const VSAPoint & notchSAPoint, const VSAPoint & nextSAPoint, const VContainer * data, QPointF & point) const private
Definition at line 842 of file vpiece.cpp.
References VGObject::accuracyPointOnLine, VAbstractPiece::EkvPoint(), VContainer::GetPatternUnit(), VSAPoint::GetSAAfter(), VSAPoint::GetSABefore(), VAbstractPiece::GetSAWidth(), VAbstractPiece::IsEkvPointOnLine(), VAbstractPiece::MaxLocalSA(), SCASSERT, and ToPixel().
Referenced by createSeamAllowanceNotch().
GetUnitedPath()
QVector< VPieceNode > VPiece::GetUnitedPath (const VContainer * data) const private
Definition at line 594 of file vpiece.cpp.
References AsMainPath, d, FilterRecords(), VPiecePath::GetNodes(), VContainer::GetPiecePath(), VGObject::GetReversePoints(), GetValidRecords(), VPiecePath::indexOfNode(), VAbstractPiece::IsSeamAllowance(), VAbstractPiece::IsSeamAllowanceBuiltIn(), and SCASSERT.
Referenced by createNotchLines(), and SeamAllowancePoints().
GetValidRecords()
QVector< CustomSARecord > VPiece::GetValidRecords () const private
Definition at line 655 of file vpiece.cpp.
References d, CustomSARecord::endPoint, NULL_ID, CustomSARecord::path, and CustomSARecord::startPoint.
Referenced by GetUnitedPath(), isNotchVisible(), and SeamAllowancePoints().
IsCSAStart()
int VPiece::IsCSAStart (const QVector< CustomSARecord > & records, quint32 id) static private
Definition at line 1103 of file vpiece.cpp.
Referenced by SeamAllowancePoints().
isInLayout()
bool VPiece::isInLayout () const
Definition at line 376 of file vpiece.cpp.
References d.
Referenced by PatternPieceTool::AddAttributes(), PatternPieceTool::contextMenuEvent(), PiecesWidget::fillTable(), PatternPieceTool::keyReleaseEvent(), PieceTableWidgetItem::operator<(), PatternPieceDialog::SetPiece(), and PiecesWidget::togglePiece().
isLocked()
bool VPiece::isLocked () const
Definition at line 388 of file vpiece.cpp.
References d.
Referenced by PatternPieceTool::AddAttributes(), UnionDialog::checkPiece(), PatternPieceTool::contextMenuEvent(), QT_WARNING_POP::createUnion(), PiecesWidget::fillTable(), PatternPieceTool::keyReleaseEvent(), PieceTableWidgetItem::operator<(), PatternPieceTool::PatternPieceTool(), setIsLocked(), PatternPieceDialog::SetPiece(), and PiecesWidget::togglePiece().
isNotchVisible()
bool VPiece::isNotchVisible (const QVector< VPieceNode > & path, int notchIndex) const private
Definition at line 889 of file vpiece.cpp.
References AsCustomSA, FilterRecords(), VPieceNode::GetTypeTool(), GetValidRecords(), VPiecePath::indexOfNode(), VPieceNode::isExcluded(), VPieceNode::isNotch(), VAbstractPiece::IsSeamAllowance(), VAbstractPiece::IsSeamAllowanceBuiltIn(), and NodePoint.
Referenced by createNotch().
IsUnited()
bool VPiece::IsUnited () const
Definition at line 400 of file vpiece.cpp.
References d.
Referenced by PatternPieceTool::AddAttributes().
MainPathNodePoints()
QVector< VPointF > VPiece::MainPathNodePoints (const VContainer * data, bool showExcluded = false) const
Definition at line 182 of file vpiece.cpp.
References GetPath(), and VPiecePath::PathNodePoints().
Referenced by PatternPieceVisual::RefreshGeometry().
MainPathPath()
QPainterPath VPiece::MainPathPath (const VContainer * data) const
Definition at line 303 of file vpiece.cpp.
References MainPathPoints().
Referenced by PatternPieceTool::RefreshGeometry(), and PatternPieceVisual::RefreshGeometry().
MainPathPoints()
QVector< QPointF > VPiece::MainPathPoints (const VContainer * data) const
Definition at line 174 of file vpiece.cpp.
References VAbstractPiece::CheckLoops(), VAbstractPiece::CorrectEquidistantPoints(), GetPath(), and VPiecePath::PathPoints().
Referenced by PatternPieceDialog::ChosenObject(), VLayoutPiece::Create(), createNotch(), PatternPieceDialog::isMainPathClockwise(), TST_VPiece::Issue620(), and MainPathPath().
missingAnchors()
QVector< quint32 > VPiece::missingAnchors (const VPiece & piece) const
Definition at line 516 of file vpiece.cpp.
References d, getAnchors(), and anonymous_namespace{vpiece.cpp}::PieceMissingNodes().
Referenced by SavePieceOptions::redo(), and SavePieceOptions::undo().
MissingCSAPath()
QVector< quint32 > VPiece::MissingCSAPath (const VPiece & piece) const
Definition at line 492 of file vpiece.cpp.
References d, GetCustomSARecords(), and anonymous_namespace{vpiece.cpp}::PieceMissingNodes().
Referenced by SavePieceOptions::redo(), and SavePieceOptions::undo().
MissingInternalPaths()
QVector< quint32 > VPiece::MissingInternalPaths (const VPiece & piece) const
Definition at line 510 of file vpiece.cpp.
References d, GetInternalPaths(), and anonymous_namespace{vpiece.cpp}::PieceMissingNodes().
Referenced by SavePieceOptions::redo(), and SavePieceOptions::undo().
MissingNodes()
QVector< quint32 > VPiece::MissingNodes (const VPiece & piece) const
MissingNodes find missing nodes in piece. When we deleted object in piece and return this piece need understand, what nodes need make invisible.
Parameters
piece changed piece.
Returns
list with missing nodes.
Definition at line 486 of file vpiece.cpp.
References d, and GetPath().
Referenced by SavePieceOptions::redo(), and SavePieceOptions::undo().
operator=()
VPiece & VPiece::operator= (const VPiece & piece)
Definition at line 140 of file vpiece.cpp.
References d, and VAbstractPiece::operator=().
SeamAllowancePath() [1/2]
QPainterPath VPiece::SeamAllowancePath (const QVector< QPointF > & points) const
Definition at line 329 of file vpiece.cpp.
References VAbstractPiece::IsSeamAllowance(), and VAbstractPiece::IsSeamAllowanceBuiltIn().
SeamAllowancePath() [2/2]
QPainterPath VPiece::SeamAllowancePath (const VContainer * data) const
Definition at line 323 of file vpiece.cpp.
References SeamAllowancePoints().
Referenced by PatternPieceTool::RefreshGeometry().
SeamAllowancePoints()
QVector< QPointF > VPiece::SeamAllowancePoints (const VContainer * data) const
Definition at line 188 of file vpiece.cpp.
References AsCustomSA, ByLength, VPiecePath::CurveSeamAllowanceSegment(), VAbstractPiece::Equidistant(), FilterRecords(), VContainer::GeometricObject(), VPieceNode::GetId(), VContainer::GetPatternUnit(), VContainer::GetPiecePath(), VPieceNode::GetReverse(), VAbstractPiece::GetSAWidth(), VPieceNode::GetTypeTool(), GetUnitedPath(), GetValidRecords(), IsCSAStart(), VPieceNode::isExcluded(), VAbstractPiece::IsSeamAllowance(), VAbstractPiece::IsSeamAllowanceBuiltIn(), NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, VPiecePath::PreparePointEkv(), SCASSERT, VPiecePath::SeamAllowancePoints(), and ToPixel().
Referenced by TST_VPiece::ClearLoop(), VLayoutPiece::Create(), createSeamAllowanceNotch(), PatternPieceTool::RefreshGeometry(), and SeamAllowancePath().
setAnchors()
void VPiece::setAnchors (const QVector< quint32 > & anchors)
Definition at line 474 of file vpiece.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::parsePieceElement().
SetCustomSARecords()
void VPiece::SetCustomSARecords (const QVector< CustomSARecord > & records)
Definition at line 456 of file vpiece.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::parsePieceElement().
SetInLayout()
void VPiece::SetInLayout (bool inLayout)
Definition at line 382 of file vpiece.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), TogglePieceInLayout::doCmd(), and VPattern::parsePieceElement().
SetInternalPaths()
void VPiece::SetInternalPaths (const QVector< quint32 > & iPaths)
Definition at line 438 of file vpiece.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::parsePieceElement().
setIsLocked()
void VPiece::setIsLocked (bool isLocked)
Definition at line 394 of file vpiece.cpp.
References d, and isLocked().
Referenced by PatternPieceDialog::CreatePiece(), TogglePieceLock::doCmd(), and VPattern::parsePieceElement().
SetPath()
void VPiece::SetPath (const VPiecePath & path)
Definition at line 168 of file vpiece.cpp.
References d.
Referenced by QT_WARNING_POP::CreateUnitedNodes(), and VPattern::parsePieceElement().
SetPatternInfo()
void VPiece::SetPatternInfo (const VPatternLabelData & info)
Definition at line 548 of file vpiece.cpp.
References d.
SetPatternPieceData()
void VPiece::SetPatternPieceData (const VPieceLabelData & data)
Definition at line 522 of file vpiece.cpp.
References d.
setSeamAllowanceWidthFormula()
void VPiece::setSeamAllowanceWidthFormula (const QString & formula, qreal value)
Definition at line 418 of file vpiece.cpp.
References d, VAbstractPiece::GetSAWidth(), and VAbstractPiece::SetSAWidth().
Referenced by PatternPieceTool::Create(), PatternPieceDialog::CreatePiece(), and QT_WARNING_POP::createUnion().
SetUnited()
void VPiece::SetUnited (bool united)
Definition at line 406 of file vpiece.cpp.
References d.
Referenced by QT_WARNING_POP::createUnion(), and VPattern::parsePieceElement().
Swap()
void VPiece::Swap (VPiece & piece)
Definition at line 124 of file vpiece.cpp.
References VAbstractPiece::Swap().
Member Data Documentation
d
QSharedDataPointer<VPieceData> VPiece::d private
Definition at line 160 of file vpiece.h.
Referenced by FilterRecords(), getAnchors(), GetCustomSARecords(), GetGrainlineGeometry(), GetInternalPaths(), GetPath(), GetPatternInfo(), GetPatternPieceData(), getSeamAllowanceWidthFormula(), GetUnitedPath(), GetValidRecords(), isInLayout(), isLocked(), IsUnited(), missingAnchors(), MissingCSAPath(), MissingInternalPaths(), MissingNodes(), operator=(), setAnchors(), SetCustomSARecords(), SetInLayout(), SetInternalPaths(), setIsLocked(), SetPath(), SetPatternInfo(), SetPatternPieceData(), setSeamAllowanceWidthFormula(), and SetUnited().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/vpiece.h
src/libs/vpatterndb/vpiece.cpp