Seamly2D: VToolBasePoint Class Reference
VToolBasePoint Class Reference
The VToolBasePoint class tool for creation pattern base point. Only base point can move. All object pattern peace depend on base point.
#include <vtoolbasepoint.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::BasePoint) }
Public Types inherited from VToolSinglePoint
enum { Type = UserType + static_cast<int>(Tool::SinglePoint) }
Public Types inherited from VScenePoint
enum { Type = UserType + static_cast<int>(Vis::ScenePoint) }
Public Slots
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
Public Slots inherited from VToolSinglePoint
void pointnameChangedPosition (const QPointF &pos)
pointnameChangedPosition handle change position point text.
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
void pointChosen ()
void pointSelected (bool selected)
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
void allowTextHover (bool enabled)
void allowTextSelectable (bool enabled)
virtual void ToolSelectionType (const SelectionType &type) Q_DECL_OVERRIDE
Public Slots inherited from VAbstractPoint
virtual void ShowTool (quint32 id, bool enable) Q_DECL_OVERRIDE
ShowTool highlight tool.
void deletePoint ()
Public Slots inherited from VDrawTool
virtual void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Signals
void LiteUpdateTree ()
FullUpdateTree handle if need update pattern file.
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Public Member Functions
virtual ~VToolBasePoint ()=default
virtual void setDialog () Q_DECL_OVERRIDE
setDialog set dialog when user want change tool option.
virtual int type () const Q_DECL_OVERRIDE
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
virtual void decrementReferens () Q_DECL_OVERRIDE
decrementReferens decrement referens parents objects.
QPointF GetBasePointPos () const
void SetBasePointPos (const QPointF &pos)
Public Member Functions inherited from VToolSinglePoint
VToolSinglePoint (VAbstractPattern *doc, VContainer *data, quint32 id, const QColor &lineColor, QGraphicsItem *parent=nullptr)
VToolSinglePoint constructor.
virtual ~VToolSinglePoint () Q_DECL_EQ_DEFAULT
QString name () const
void setName (const QString &name)
void SetEnabled (bool enabled)
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
virtual bool isPointNameVisible (quint32 id) const Q_DECL_OVERRIDE
virtual void setPointNameVisiblity (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void setPointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractPoint
VAbstractPoint (VAbstractPattern *doc, VContainer *data, quint32 id)
virtual ~VAbstractPoint () Q_DECL_EQ_DEFAULT
virtual QString getTagName () const Q_DECL_OVERRIDE
template<typename T >
void ShowToolVisualization (bool show)
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual void setLineWeight (const QString &value)
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
Public Member Functions inherited from VScenePoint
VScenePoint (const QColor &lineColor, QGraphicsItem *parent=nullptr)
virtual ~VScenePoint ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
virtual void refreshPointGeometry (const VPointF &point)
void refreshLeader ()
Static Public Member Functions
static VToolBasePoint * Create (quint32 _id, const QString &activeDraftBlock, VPointF *point, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation)
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString ToolType = QStringLiteral("single")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Slots
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID) Q_DECL_OVERRIDE
showContextMenu handle context menu events.
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Protected Member Functions
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) Q_DECL_OVERRIDE
itemChange handle tool change.
virtual void deleteTool (bool ask=true) Q_DECL_OVERRIDE
deleteTool full delete object form scene and file.
virtual void SaveDialog (QDomElement &domElement) Q_DECL_OVERRIDE
SaveDialog save options into file after change in dialog.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
mouseReleaseEvent handle mouse release events.
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
virtual void ReadToolAttributes (const QDomElement &domElement) Q_DECL_OVERRIDE
virtual void SetVisualization () Q_DECL_OVERRIDE
virtual QString makeToolTip () const Q_DECL_OVERRIDE
Protected Member Functions inherited from VToolSinglePoint
virtual void updatePointNameVisibility (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void updatePointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
updatePointNamePosition save new position text to the pattern file.
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyReleaseEvent handle key release events.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractPoint
void SetPointName (quint32 id, const QString &name)
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialogChange () Q_DECL_FINAL
void SaveOption (QSharedPointer< VGObject > &obj)
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void RemoveReferens ()
RemoveReferens decrement value of reference.
template<typename T >
void AddVisualization ()
virtual void ToolCreation (const Source &typeCreation)
Protected Member Functions inherited from VScenePoint
void setOnlyPoint (bool value)
bool isOnlyPoint () const
void setPointColor (const QString &value)
Private Member Functions
VToolBasePoint (VAbstractPattern *doc, VContainer *data, quint32 id, const Source &typeCreation, const QString &draftBlockName, QGraphicsItem *parent=nullptr)
VToolBasePoint constructor.
Private Attributes
QString draftBlockName
Additional Inherited Members
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Static Protected Member Functions inherited from VAbstractPoint
template<typename T >
static void InitToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Protected Attributes inherited from VScenePoint
VGraphicsSimpleTextItem * m_pointName
VScaledLine * m_pointLeader
namePoint point text.
QColor m_pointColor
pointL line that we see if Text is moved too away from point.
bool m_onlyPoint
m_pointColor color of point.
bool m_isHovered
bool m_showPointName
Detailed Description
The VToolBasePoint class tool for creation pattern base point. Only base point can move. All object pattern peace depend on base point.
Definition at line 75 of file vtoolbasepoint.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 88 of file vtoolbasepoint.h.
Constructor & Destructor Documentation
~VToolBasePoint()
virtual VToolBasePoint::~VToolBasePoint () virtual default
VToolBasePoint()
VToolBasePoint::VToolBasePoint (VAbstractPattern * doc, VContainer * data, quint32 id, const Source & typeCreation, const QString & draftBlockName, QGraphicsItem * parent = nullptr) private
VToolBasePoint constructor.
Parameters
doc dom document container.
data container with variables.
id object id in container.
typeCreation way we create this tool.
parent parent object.
Definition at line 106 of file vtoolbasepoint.cpp.
References VAbstractTool::ToolCreation().
Referenced by Create().
Member Function Documentation
AddToFile()
void VToolBasePoint::AddToFile () protected virtual
AddToFile add tag with Information about tool into file.
Reimplemented from VDrawTool.
Definition at line 173 of file vtoolbasepoint.cpp.
References AddDraftBlock, AttrName, VAbstractPattern::ClearScene(), VUndoCommand::ClearScene(), VDataTool::data, VAbstractTool::doc, draftBlockName, VContainer::GetGObject(), VAbstractPoint::getTagName(), VAbstractTool::m_id, VAbstractPattern::NeedFullParsing(), VUndoCommand::NeedFullParsing(), qApp, SaveOptions(), VDomDocument::SetAttribute(), VAbstractPattern::TagCalculation, VAbstractPattern::TagDraftBlock, VAbstractPattern::TagModeling, and VAbstractPattern::TagPieces.
Create()
VToolBasePoint * VToolBasePoint::Create (quint32 _id, const QString & activeDraftBlock, VPointF * point, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation) static
Definition at line 131 of file vtoolbasepoint.cpp.
References VContainer::AddGObject(), VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), BasePoint, VDataTool::data, VAbstractTool::doc, FromGui, FullParse, VAbstractPoint::InitToolConnections(), SCASSERT, VContainer::UpdateGObject(), VAbstractPattern::UpdateToolData(), and VToolBasePoint().
Referenced by MainWindow::addDraftBlock(), and VPattern::ParseToolBasePoint().
decrementReferens()
void VToolBasePoint::decrementReferens () virtual
decrementReferens decrement referens parents objects.
Reimplemented from VDataTool.
Definition at line 260 of file vtoolbasepoint.cpp.
References VDataTool::_referens.
deleteTool()
void VToolBasePoint::deleteTool (bool ask = true) protected virtual
deleteTool full delete object form scene and file.
Reimplemented from VAbstractTool.
Definition at line 289 of file vtoolbasepoint.cpp.
References VDrawTool::activeBlockName, VAbstractTool::ConfirmDeletion(), DeleteDraftBlock, VAbstractTool::doc, VAbstractPattern::NeedFullParsing(), VUndoCommand::NeedFullParsing(), and qApp.
EnableToolMove
void VToolBasePoint::EnableToolMove (bool move) virtual slot
Definition at line 455 of file vtoolbasepoint.cpp.
References VToolSinglePoint::EnableToolMove().
FullUpdateFromFile
void VToolBasePoint::FullUpdateFromFile () virtual slot
FullUpdateFromFile update tool data form file.
Definition at line 449 of file vtoolbasepoint.cpp.
References VDataTool::data, VAbstractTool::m_id, and VScenePoint::refreshPointGeometry().
GetBasePointPos()
QPointF VToolBasePoint::GetBasePointPos () const
Definition at line 269 of file vtoolbasepoint.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractTool::m_id, and qApp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolSinglePoint(), and VToolOptionsPropertyBrowser::updateOptionsToolSinglePoint().
hoverEnterEvent()
void VToolBasePoint::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected virtual
Reimplemented from VToolSinglePoint.
Definition at line 330 of file vtoolbasepoint.cpp.
References cursorArrowOpenHand, VToolSinglePoint::hoverEnterEvent(), and SetItemOverrideCursor().
hoverLeaveEvent()
void VToolBasePoint::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected virtual
Reimplemented from VScenePoint.
Definition at line 341 of file vtoolbasepoint.cpp.
References VScenePoint::hoverLeaveEvent().
itemChange()
QVariant VToolBasePoint::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
itemChange handle tool change.
Parameters
change change.
value value.
Returns
value.
Reimplemented from VToolSinglePoint.
Definition at line 207 of file vtoolbasepoint.cpp.
References VAbstractTool::doc, VMainGraphicsScene::getScenePos(), VToolSinglePoint::itemChange(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, MoveSPoint, VUndoCommand::NeedLiteParsing(), qApp, SCASSERT, and VMainGraphicsView::SceneVisibleArea().
LiteUpdateTree
void VToolBasePoint::LiteUpdateTree () signal
FullUpdateTree handle if need update pattern file.
makeToolTip()
QString VToolBasePoint::makeToolTip () const protected virtual
Reimplemented from VDrawTool.
Definition at line 398 of file vtoolbasepoint.cpp.
References VDataTool::data, VContainer::GeometricObject(), and VAbstractTool::m_id.
mousePressEvent()
void VToolBasePoint::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented from VToolSinglePoint.
Definition at line 352 of file vtoolbasepoint.cpp.
References cursorArrowCloseHand, VToolSinglePoint::mousePressEvent(), and SetItemOverrideCursor().
mouseReleaseEvent()
void VToolBasePoint::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
mouseReleaseEvent handle mouse release events.
Parameters
event mouse release event.
Reimplemented from VToolSinglePoint.
Definition at line 365 of file vtoolbasepoint.cpp.
References cursorArrowOpenHand, VToolSinglePoint::mouseReleaseEvent(), and SetItemOverrideCursor().
ReadToolAttributes()
void VToolBasePoint::ReadToolAttributes (const QDomElement & domElement) protected virtual
Implements VDrawTool.
Definition at line 391 of file vtoolbasepoint.cpp.
SaveDialog()
void VToolBasePoint::SaveDialog (QDomElement & domElement) protected virtual
SaveDialog save options into file after change in dialog.
Implements VDrawTool.
Definition at line 317 of file vtoolbasepoint.cpp.
References AttrName, AttrX, AttrY, VAbstractTool::doc, VInteractiveTool::m_dialog, VToolSinglePoint::name(), qApp, SCASSERT, and VDomDocument::SetAttribute().
SaveOptions()
void VToolBasePoint::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VToolSinglePoint.
Definition at line 378 of file vtoolbasepoint.cpp.
References AttrType, AttrX, AttrY, VAbstractTool::doc, qApp, VToolSinglePoint::SaveOptions(), SCASSERT, VDomDocument::SetAttribute(), and ToolType.
Referenced by AddToFile().
SetBasePointPos()
void VToolBasePoint::SetBasePointPos (const QPointF & pos)
Definition at line 277 of file vtoolbasepoint.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractTool::m_id, qApp, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolSinglePoint().
setDialog()
void VToolBasePoint::setDialog () virtual
setDialog set dialog when user want change tool option.
Reimplemented from VInteractiveTool.
Definition at line 121 of file vtoolbasepoint.cpp.
References VDataTool::data, VContainer::GeometricObject(), VInteractiveTool::m_dialog, VAbstractTool::m_id, and SCASSERT.
SetVisualization()
virtual void VToolBasePoint::SetVisualization () inline protected virtual
Implements VAbstractTool.
Definition at line 120 of file vtoolbasepoint.h.
showContextMenu
void VToolBasePoint::showContextMenu (QGraphicsSceneContextMenuEvent * event, quint32 id = NULL_ID) protected virtual slot
showContextMenu handle context menu events.
Parameters
event context menu event.
Definition at line 415 of file vtoolbasepoint.cpp.
References VDrawTool::Disable, VAbstractTool::doc, VAbstractPattern::draftBlockCount(), VDrawTool::Enable, and VDrawTool::Ignore.
ShowVisualization()
void VToolBasePoint::ShowVisualization (bool show) virtual
Implements VAbstractTool.
Definition at line 164 of file vtoolbasepoint.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolSinglePoint().
type()
virtual int VToolBasePoint::type () const inline virtual
Reimplemented from VToolSinglePoint.
Definition at line 87 of file vtoolbasepoint.h.
References Type.
Member Data Documentation
draftBlockName
QString VToolBasePoint::draftBlockName private
Definition at line 126 of file vtoolbasepoint.h.
Referenced by AddToFile().
ToolType
const QString VToolBasePoint::ToolType = QStringLiteral("single") static
Definition at line 86 of file vtoolbasepoint.h.
Referenced by VPattern::getActiveBasePoint(), VPattern::ParsePointElement(), and SaveOptions().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolbasepoint.h
src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolbasepoint.cpp