Seamly2D: TST_VCubicBezierPath Class Reference
TST_VCubicBezierPath Class Reference
#include <tst_vcubicbezierpath.h>
Public Member Functions
TST_VCubicBezierPath (QObject *parent=nullptr)
Private Slots
void TestCountSubSpl_data () const
void TestCountSubSpl () const
void TestSubSplOffset_data () const
void TestSubSplOffset () const
void TestSubSplPointsCount_data () const
void TestSubSplPointsCount () const
Detailed Description
Definition at line 57 of file tst_vcubicbezierpath.h.
Constructor & Destructor Documentation
TST_VCubicBezierPath()
TST_VCubicBezierPath::TST_VCubicBezierPath (QObject * parent = nullptr) explicit
Definition at line 58 of file tst_vcubicbezierpath.cpp.
Member Function Documentation
TestCountSubSpl
void TST_VCubicBezierPath::TestCountSubSpl () const private slot
Definition at line 86 of file tst_vcubicbezierpath.cpp.
References VCubicBezierPath::CountSubSpl().
TestCountSubSpl_data
void TST_VCubicBezierPath::TestCountSubSpl_data () const private slot
Definition at line 64 of file tst_vcubicbezierpath.cpp.
TestSubSplOffset
void TST_VCubicBezierPath::TestSubSplOffset () const private slot
Definition at line 112 of file tst_vcubicbezierpath.cpp.
References VCubicBezierPath::SubSplOffset().
TestSubSplOffset_data
void TST_VCubicBezierPath::TestSubSplOffset_data () const private slot
Definition at line 96 of file tst_vcubicbezierpath.cpp.
TestSubSplPointsCount
void TST_VCubicBezierPath::TestSubSplPointsCount () const private slot
Definition at line 138 of file tst_vcubicbezierpath.cpp.
References VCubicBezierPath::SubSplPointsCount().
TestSubSplPointsCount_data
void TST_VCubicBezierPath::TestSubSplPointsCount_data () const private slot
Definition at line 122 of file tst_vcubicbezierpath.cpp.
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vcubicbezierpath.h
src/test/Seamly2DTest/tst_vcubicbezierpath.cpp