Seamly2D: src/libs/vmisc/customevents.h File Reference
customevents.h File Reference
#include <qcompilerdetection.h>
#include <QEvent>
Classes
class UndoEvent
class LiteParseEvent
Enumerations
enum CustomEventType { UndoEventType = 1 , LiteParseEventType = 2 }
Variables
const QEvent::Type UNDO_EVENT = static_cast<QEvent::Type>(QEvent::User + CustomEventType::UndoEventType)
const QEvent::Type LITE_PARSE_EVENT = static_cast<QEvent::Type>(QEvent::User + CustomEventType::LiteParseEventType)
Enumeration Type Documentation
CustomEventType
enum CustomEventType
Enumerator
UndoEventType
LiteParseEventType
Definition at line 58 of file customevents.h.
Variable Documentation
LITE_PARSE_EVENT
const QEvent::Type LITE_PARSE_EVENT = static_cast<QEvent::Type>(QEvent::User + CustomEventType::LiteParseEventType)
Definition at line 73 of file customevents.h.
Referenced by VPattern::customEvent().
UNDO_EVENT
const QEvent::Type UNDO_EVENT = static_cast<QEvent::Type>(QEvent::User + CustomEventType::UndoEventType)
Definition at line 61 of file customevents.h.
Referenced by MainWindow::customEvent(), and VPattern::customEvent().