Seamly2D: SAXException Class Reference
SAXException Class Reference
#include <SAXException.hpp>
Public Member Functions
Constructors and Destructor
SAXException (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const XMLCh *const msg, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const char *const msg, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const SAXException &toCopy)
virtual ~SAXException ()
SAXException (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const XMLCh *const msg, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const char *const msg, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const SAXException &toCopy)
virtual ~SAXException ()
SAXException (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const XMLCh *const msg, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const char *const msg, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SAXException (const SAXException &toCopy)
virtual ~SAXException ()
Public Operators
SAXException & operator= (const SAXException &toCopy)
SAXException & operator= (const SAXException &toCopy)
SAXException & operator= (const SAXException &toCopy)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Getter Methods
XMLCh * fMsg
MemoryManager * fMemoryManager
virtual const XMLCh * getMessage () const
virtual const XMLCh * getMessage () const
virtual const XMLCh * getMessage () const
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Encapsulate a general SAX error or warning.
This class can contain basic error or warning information from either the XML SAX parser or the application: a parser writer or application writer can subclass it to provide additional functionality. SAX handlers may throw this exception or any exception subclassed from it.
If the application needs to pass through other types of exceptions, it must wrap those exceptions in a SAXException or an exception derived from a SAXException.
If the parser or application needs to include information about a specific location in an XML document, it should use the SAXParseException subclass.
See also
SAXParseException::SAXParseException
Definition at line 51 of file SAXException.hpp.
Constructor & Destructor Documentation
SAXException() [1/12]
SAXException::SAXException (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Default constructor
Parameters
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 60 of file SAXException.hpp.
SAXException() [2/12]
SAXException::SAXException (const XMLCh *const msg, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Create a new SAXException.
Parameters
msg The error or warning message.
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 74 of file SAXException.hpp.
SAXException() [3/12]
SAXException::SAXException (const char *const msg, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Create a new SAXException.
Parameters
msg The error or warning message.
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 89 of file SAXException.hpp.
SAXException() [4/12]
SAXException::SAXException (const SAXException & toCopy) inline
Copy constructor
Parameters
toCopy The exception to be copy constructed
Definition at line 102 of file SAXException.hpp.
~SAXException() [1/3]
virtual SAXException::~SAXException () inline virtual
Destructor
Definition at line 110 of file SAXException.hpp.
SAXException() [5/12]
SAXException::SAXException (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Default constructor
Parameters
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 60 of file SAXException.hpp.
SAXException() [6/12]
SAXException::SAXException (const XMLCh *const msg, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Create a new SAXException.
Parameters
msg The error or warning message.
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 74 of file SAXException.hpp.
SAXException() [7/12]
SAXException::SAXException (const char *const msg, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Create a new SAXException.
Parameters
msg The error or warning message.
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 89 of file SAXException.hpp.
SAXException() [8/12]
SAXException::SAXException (const SAXException & toCopy) inline
Copy constructor
Parameters
toCopy The exception to be copy constructed
Definition at line 102 of file SAXException.hpp.
~SAXException() [2/3]
virtual SAXException::~SAXException () inline virtual
Destructor
Definition at line 110 of file SAXException.hpp.
SAXException() [9/12]
SAXException::SAXException (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Default constructor
Parameters
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 60 of file SAXException.hpp.
SAXException() [10/12]
SAXException::SAXException (const XMLCh *const msg, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Create a new SAXException.
Parameters
msg The error or warning message.
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 74 of file SAXException.hpp.
SAXException() [11/12]
SAXException::SAXException (const char *const msg, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Create a new SAXException.
Parameters
msg The error or warning message.
manager Pointer to the memory manager to be used to allocate objects.
Definition at line 89 of file SAXException.hpp.
SAXException() [12/12]
SAXException::SAXException (const SAXException & toCopy) inline
Copy constructor
Parameters
toCopy The exception to be copy constructed
Definition at line 102 of file SAXException.hpp.
~SAXException() [3/3]
virtual SAXException::~SAXException () inline virtual
Destructor
Definition at line 110 of file SAXException.hpp.
Member Function Documentation
getMessage() [1/3]
virtual const XMLCh* SAXException::getMessage () const inline virtual
Get the contents of the message
Definition at line 143 of file SAXException.hpp.
getMessage() [2/3]
virtual const XMLCh* SAXException::getMessage () const inline virtual
Get the contents of the message
Definition at line 143 of file SAXException.hpp.
getMessage() [3/3]
virtual const XMLCh* SAXException::getMessage () const inline virtual
Get the contents of the message
Definition at line 143 of file SAXException.hpp.
operator=() [1/3]
SAXException& SAXException::operator= (const SAXException & toCopy) inline
Assignment operator
Parameters
toCopy The object to be copied
Definition at line 125 of file SAXException.hpp.
References fMemoryManager, fMsg, and XMLString::replicate().
operator=() [2/3]
SAXException& SAXException::operator= (const SAXException & toCopy) inline
Assignment operator
Parameters
toCopy The object to be copied
Definition at line 125 of file SAXException.hpp.
References fMemoryManager, fMsg, and XMLString::replicate().
operator=() [3/3]
SAXException& SAXException::operator= (const SAXException & toCopy) inline
Assignment operator
Parameters
toCopy The object to be copied
Definition at line 125 of file SAXException.hpp.
References fMemoryManager, fMsg, and XMLString::replicate().
Member Data Documentation
fMemoryManager
MemoryManager * SAXException::fMemoryManager protected
Definition at line 158 of file SAXException.hpp.
Referenced by operator=().
fMsg
XMLCh * SAXException::fMsg protected
Definition at line 157 of file SAXException.hpp.
Referenced by operator=().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/sax/SAXException.hpp