Seamly2D: src/app/seamly2d/core/vapplication.cpp File Reference
vapplication.cpp File Reference
#include "vapplication.h"
#include "../ifc/exception/vexceptionobjecterror.h"
#include "../ifc/exception/vexceptionbadid.h"
#include "../ifc/exception/vexceptionconversionerror.h"
#include "../ifc/exception/vexceptionemptyparameter.h"
#include "../ifc/exception/vexceptionwrongid.h"
#include "../vwidgets/vmaingraphicsview.h"
#include "../version.h"
#include "../vmisc/logging.h"
#include "../vmisc/vmath.h"
#include "../qmuparser/qmuparsererror.h"
#include "../mainwindow.h"
#include <Qt>
#include <QtDebug>
#include <QDir>
#include <QProcess>
#include <QTemporaryFile>
#include <QUndoStack>
#include <QFile>
#include <QStandardPaths>
#include <QMessageBox>
#include <QThread>
#include <QDateTime>
#include <QtXmlPatterns>
#include <QIcon>
Macros
#define DefWidth 1.2
Functions
void noisyFailureMsgHandler (QtMsgType type, const QMessageLogContext &context, const QString &msg)
Variables
QT_WARNING_PUSH QT_WARNING_POP Q_DECL_CONSTEXPR auto DAYS_TO_KEEP_LOGS = 3
Macro Definition Documentation
DefWidth
#define DefWidth 1.2
Definition at line 267 of file vapplication.cpp.
Function Documentation
noisyFailureMsgHandler()
void noisyFailureMsgHandler (QtMsgType type, const QMessageLogContext & context, const QString & msg) inline
Definition at line 91 of file vapplication.cpp.
References VApplication::IsGUIMode(), qApp, translate, vStdErr(), and vStdOut().
Referenced by VApplication::BeginLogging().
Variable Documentation
DAYS_TO_KEEP_LOGS
QT_WARNING_PUSH QT_WARNING_POP Q_DECL_CONSTEXPR auto DAYS_TO_KEEP_LOGS = 3
Definition at line 88 of file vapplication.cpp.
Referenced by VApplication::ClearOldLogs().