Seamly2D: TST_AbstractRegExp Class Reference
TST_AbstractRegExp Class Reference abstract
#include <tst_abstractregexp.h>
Public Member Functions
TST_AbstractRegExp (const QString &locale, QObject *parent=nullptr)
virtual ~TST_AbstractRegExp ()
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Protected Member Functions
virtual void PrepareData ()=0
virtual QStringList AllNames ()=0
int LoadVariables (const QString &checkedLocale)
void RemoveTrVariables (const QString &checkedLocale)
void InitTrMs ()
void CallTestCheckNoEndLine ()
void CallTestCheckRegExpNames ()
void CallTestCheckIsNamesUnique ()
void CallTestCheckNoOriginalNamesInTranslation ()
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Protected Attributes
QString m_locale
QPointer< QTranslator > m_vTranslator
VTranslateVars * m_trMs
Detailed Description
Definition at line 62 of file tst_abstractregexp.h.
Constructor & Destructor Documentation
TST_AbstractRegExp()
TST_AbstractRegExp::TST_AbstractRegExp (const QString & locale, QObject * parent = nullptr)
Definition at line 63 of file tst_abstractregexp.cpp.
~TST_AbstractRegExp()
TST_AbstractRegExp::~TST_AbstractRegExp () virtual
Definition at line 72 of file tst_abstractregexp.cpp.
References m_trMs, and m_vTranslator.
Member Function Documentation
AllNames()
virtual QStringList TST_AbstractRegExp::AllNames () protected pure virtual
Implemented in TST_MeasurementRegExp, and TST_BuitInRegExp.
Referenced by CallTestCheckNoOriginalNamesInTranslation().
CallTestCheckIsNamesUnique()
void TST_AbstractRegExp::CallTestCheckIsNamesUnique () protected
Definition at line 185 of file tst_abstractregexp.cpp.
References m_trMs, and VTranslateVars::VarToUser().
Referenced by TST_BuitInRegExp::TestCheckIsNamesUnique(), and TST_MeasurementRegExp::TestCheckIsNamesUnique().
CallTestCheckNoEndLine()
void TST_AbstractRegExp::CallTestCheckNoEndLine () protected
Definition at line 157 of file tst_abstractregexp.cpp.
References m_trMs, and VTranslateVars::VarToUser().
Referenced by TST_BuitInRegExp::TestCheckNoEndLine(), and TST_MeasurementRegExp::TestCheckNoEndLine().
CallTestCheckNoOriginalNamesInTranslation()
void TST_AbstractRegExp::CallTestCheckNoOriginalNamesInTranslation () protected
Definition at line 202 of file tst_abstractregexp.cpp.
References AllNames(), m_trMs, and VTranslateVars::VarToUser().
Referenced by TST_BuitInRegExp::TestCheckNoOriginalNamesInTranslation(), and TST_MeasurementRegExp::TestCheckNoOriginalNamesInTranslation().
CallTestCheckRegExpNames()
void TST_AbstractRegExp::CallTestCheckRegExpNames () protected
Definition at line 171 of file tst_abstractregexp.cpp.
References m_trMs, NameRegExp(), and VTranslateVars::VarToUser().
Referenced by TST_BuitInRegExp::TestCheckRegExpNames(), and TST_MeasurementRegExp::TestCheckRegExpNames().
InitTrMs()
void TST_AbstractRegExp::InitTrMs () protected
Definition at line 144 of file tst_abstractregexp.cpp.
References m_trMs, and VTranslateVars::Retranslate().
Referenced by TST_BuitInRegExp::initTestCase(), and TST_MeasurementRegExp::initTestCase().
LoadVariables()
int TST_AbstractRegExp::LoadVariables (const QString & checkedLocale) protected
Definition at line 79 of file tst_abstractregexp.cpp.
References ErrorInstall, ErrorLoad, ErrorSize, m_vTranslator, NoError, and AbstractTest::TranslationsPath().
Referenced by TST_BuitInRegExp::initTestCase(), and TST_MeasurementRegExp::initTestCase().
PrepareData()
virtual void TST_AbstractRegExp::PrepareData () protected pure virtual
Implemented in TST_MeasurementRegExp, and TST_BuitInRegExp.
RemoveTrVariables()
void TST_AbstractRegExp::RemoveTrVariables (const QString & checkedLocale) protected
Definition at line 127 of file tst_abstractregexp.cpp.
References m_vTranslator.
Referenced by TST_BuitInRegExp::cleanupTestCase(), and TST_MeasurementRegExp::cleanupTestCase().
Member Data Documentation
m_locale
QString TST_AbstractRegExp::m_locale protected
Definition at line 70 of file tst_abstractregexp.h.
Referenced by TST_BuitInRegExp::cleanupTestCase(), TST_MeasurementRegExp::cleanupTestCase(), TST_BuitInRegExp::initTestCase(), TST_MeasurementRegExp::initTestCase(), TST_BuitInRegExp::PrepareData(), TST_MeasurementRegExp::PrepareData(), TST_BuitInRegExp::TestCheckInternalVaribleRegExp_data(), and TST_BuitInRegExp::TestCheckUnderlineExists_data().
m_trMs
VTranslateVars* TST_AbstractRegExp::m_trMs protected
Definition at line 72 of file tst_abstractregexp.h.
Referenced by CallTestCheckIsNamesUnique(), CallTestCheckNoEndLine(), CallTestCheckNoOriginalNamesInTranslation(), CallTestCheckRegExpNames(), InitTrMs(), TST_BuitInRegExp::TestCheckInternalVaribleRegExp(), TST_BuitInRegExp::TestCheckUnderlineExists(), TST_BuitInRegExp::TestTemplatePlaceholders(), and ~TST_AbstractRegExp().
m_vTranslator
QPointer<QTranslator> TST_AbstractRegExp::m_vTranslator protected
Definition at line 71 of file tst_abstractregexp.h.
Referenced by LoadVariables(), RemoveTrVariables(), and ~TST_AbstractRegExp().
The documentation for this class was generated from the following files:
src/test/TranslationsTest/tst_abstractregexp.h
src/test/TranslationsTest/tst_abstractregexp.cpp