Seamly2D: XMLBufBid Class Reference
XMLBufBid Class Reference
#include <XMLBufferMgr.hpp>
Public Member Functions
XMLBufBid (XMLBufferMgr *const srcMgr)
~XMLBufBid ()
void append (const XMLCh toAppend)
void append (const XMLCh *const toAppend, const XMLSize_t count=0)
const XMLBuffer & getBuffer () const
XMLBuffer & getBuffer ()
const XMLCh * getRawBuffer () const
XMLCh * getRawBuffer ()
XMLSize_t getLen () const
bool isEmpty () const
void reset ()
void set (const XMLCh *const chars, const XMLSize_t count=0)
XMLBufBid (XMLBufferMgr *const srcMgr)
~XMLBufBid ()
void append (const XMLCh toAppend)
void append (const XMLCh *const toAppend, const XMLSize_t count=0)
const XMLBuffer & getBuffer () const
XMLBuffer & getBuffer ()
const XMLCh * getRawBuffer () const
XMLCh * getRawBuffer ()
XMLSize_t getLen () const
bool isEmpty () const
void reset ()
void set (const XMLCh *const chars, const XMLSize_t count=0)
XMLBufBid (XMLBufferMgr *const srcMgr)
~XMLBufBid ()
void append (const XMLCh toAppend)
void append (const XMLCh *const toAppend, const XMLSize_t count=0)
const XMLBuffer & getBuffer () const
XMLBuffer & getBuffer ()
const XMLCh * getRawBuffer () const
XMLCh * getRawBuffer ()
XMLSize_t getLen () const
bool isEmpty () const
void reset ()
void set (const XMLCh *const chars, const XMLSize_t count=0)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
XMLBufBid (const XMLBufBid &)
XMLBufBid & operator= (const XMLBufBid &)
XMLBufBid (const XMLBufBid &)
XMLBufBid & operator= (const XMLBufBid &)
XMLBufBid (const XMLBufBid &)
XMLBufBid & operator= (const XMLBufBid &)
Private Attributes
XMLBuffer & fBuffer
XMLBufferMgr *const fMgr
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
XMLBufBid is a scoped based janitor that allows the scanner code to ask for a buffer on a scoped basis and then insure that it gets freed back into the pool no matter how the scope is exited (exception or normal exit.)
Definition at line 113 of file XMLBufferMgr.hpp.
Constructor & Destructor Documentation
XMLBufBid() [1/6]
XMLBufBid::XMLBufBid (XMLBufferMgr *const srcMgr) inline
Definition at line 119 of file XMLBufferMgr.hpp.
~XMLBufBid() [1/3]
XMLBufBid::~XMLBufBid () inline
Definition at line 126 of file XMLBufferMgr.hpp.
References fBuffer, fMgr, and XMLBufferMgr::releaseBuffer().
XMLBufBid() [2/6]
XMLBufBid::XMLBufBid (const XMLBufBid &) private
XMLBufBid() [3/6]
XMLBufBid::XMLBufBid (XMLBufferMgr *const srcMgr) inline
Definition at line 119 of file XMLBufferMgr.hpp.
~XMLBufBid() [2/3]
XMLBufBid::~XMLBufBid () inline
Definition at line 126 of file XMLBufferMgr.hpp.
References fBuffer, fMgr, and XMLBufferMgr::releaseBuffer().
XMLBufBid() [4/6]
XMLBufBid::XMLBufBid (const XMLBufBid &) private
XMLBufBid() [5/6]
XMLBufBid::XMLBufBid (XMLBufferMgr *const srcMgr) inline
Definition at line 119 of file XMLBufferMgr.hpp.
~XMLBufBid() [3/3]
XMLBufBid::~XMLBufBid () inline
Definition at line 126 of file XMLBufferMgr.hpp.
References fBuffer, fMgr, and XMLBufferMgr::releaseBuffer().
XMLBufBid() [6/6]
XMLBufBid::XMLBufBid (const XMLBufBid &) private
Member Function Documentation
append() [1/6]
void XMLBufBid::append (const XMLCh *const toAppend, const XMLSize_t count = 0) inline
Definition at line 141 of file XMLBufferMgr.hpp.
References XMLBuffer::append(), and fBuffer.
append() [2/6]
void XMLBufBid::append (const XMLCh *const toAppend, const XMLSize_t count = 0) inline
Definition at line 141 of file XMLBufferMgr.hpp.
References XMLBuffer::append(), and fBuffer.
append() [3/6]
void XMLBufBid::append (const XMLCh *const toAppend, const XMLSize_t count = 0) inline
Definition at line 141 of file XMLBufferMgr.hpp.
References XMLBuffer::append(), and fBuffer.
append() [4/6]
void XMLBufBid::append (const XMLCh toAppend) inline
Definition at line 136 of file XMLBufferMgr.hpp.
References XMLBuffer::append(), and fBuffer.
append() [5/6]
void XMLBufBid::append (const XMLCh toAppend) inline
Definition at line 136 of file XMLBufferMgr.hpp.
References XMLBuffer::append(), and fBuffer.
append() [6/6]
void XMLBufBid::append (const XMLCh toAppend) inline
Definition at line 136 of file XMLBufferMgr.hpp.
References XMLBuffer::append(), and fBuffer.
getBuffer() [1/6]
XMLBuffer& XMLBufBid::getBuffer () inline
Definition at line 151 of file XMLBufferMgr.hpp.
References fBuffer.
getBuffer() [2/6]
XMLBuffer& XMLBufBid::getBuffer () inline
Definition at line 151 of file XMLBufferMgr.hpp.
References fBuffer.
getBuffer() [3/6]
XMLBuffer& XMLBufBid::getBuffer () inline
Definition at line 151 of file XMLBufferMgr.hpp.
References fBuffer.
getBuffer() [4/6]
const XMLBuffer& XMLBufBid::getBuffer () const inline
Definition at line 146 of file XMLBufferMgr.hpp.
References fBuffer.
getBuffer() [5/6]
const XMLBuffer& XMLBufBid::getBuffer () const inline
Definition at line 146 of file XMLBufferMgr.hpp.
References fBuffer.
getBuffer() [6/6]
const XMLBuffer& XMLBufBid::getBuffer () const inline
Definition at line 146 of file XMLBufferMgr.hpp.
References fBuffer.
getLen() [1/3]
XMLSize_t XMLBufBid::getLen () const inline
Definition at line 168 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::fIndex.
getLen() [2/3]
XMLSize_t XMLBufBid::getLen () const inline
Definition at line 168 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::fIndex.
getLen() [3/3]
XMLSize_t XMLBufBid::getLen () const inline
Definition at line 168 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::fIndex.
getRawBuffer() [1/6]
XMLCh* XMLBufBid::getRawBuffer () inline
Definition at line 162 of file XMLBufferMgr.hpp.
References XMLBuffer::fBuffer, fBuffer, and XMLBuffer::fIndex.
getRawBuffer() [2/6]
XMLCh* XMLBufBid::getRawBuffer () inline
Definition at line 162 of file XMLBufferMgr.hpp.
References XMLBuffer::fBuffer, fBuffer, and XMLBuffer::fIndex.
getRawBuffer() [3/6]
XMLCh* XMLBufBid::getRawBuffer () inline
Definition at line 162 of file XMLBufferMgr.hpp.
References XMLBuffer::fBuffer, fBuffer, and XMLBuffer::fIndex.
getRawBuffer() [4/6]
const XMLCh* XMLBufBid::getRawBuffer () const inline
Definition at line 156 of file XMLBufferMgr.hpp.
References XMLBuffer::fBuffer, fBuffer, and XMLBuffer::fIndex.
getRawBuffer() [5/6]
const XMLCh* XMLBufBid::getRawBuffer () const inline
Definition at line 156 of file XMLBufferMgr.hpp.
References XMLBuffer::fBuffer, fBuffer, and XMLBuffer::fIndex.
getRawBuffer() [6/6]
const XMLCh* XMLBufBid::getRawBuffer () const inline
Definition at line 156 of file XMLBufferMgr.hpp.
References XMLBuffer::fBuffer, fBuffer, and XMLBuffer::fIndex.
isEmpty() [1/3]
bool XMLBufBid::isEmpty () const inline
Definition at line 173 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::fIndex.
isEmpty() [2/3]
bool XMLBufBid::isEmpty () const inline
Definition at line 173 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::fIndex.
isEmpty() [3/3]
bool XMLBufBid::isEmpty () const inline
Definition at line 173 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::fIndex.
operator=() [1/3]
XMLBufBid& XMLBufBid::operator= (const XMLBufBid &) private
operator=() [2/3]
XMLBufBid& XMLBufBid::operator= (const XMLBufBid &) private
operator=() [3/3]
XMLBufBid& XMLBufBid::operator= (const XMLBufBid &) private
reset() [1/3]
void XMLBufBid::reset () inline
Definition at line 178 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::reset().
reset() [2/3]
void XMLBufBid::reset () inline
Definition at line 178 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::reset().
reset() [3/3]
void XMLBufBid::reset () inline
Definition at line 178 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::reset().
set() [1/3]
void XMLBufBid::set (const XMLCh *const chars, const XMLSize_t count = 0) inline
Definition at line 183 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::set().
set() [2/3]
void XMLBufBid::set (const XMLCh *const chars, const XMLSize_t count = 0) inline
Definition at line 183 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::set().
set() [3/3]
void XMLBufBid::set (const XMLCh *const chars, const XMLSize_t count = 0) inline
Definition at line 183 of file XMLBufferMgr.hpp.
References fBuffer, and XMLBuffer::set().
Member Data Documentation
fBuffer
XMLBuffer & XMLBufBid::fBuffer private
Definition at line 206 of file XMLBufferMgr.hpp.
Referenced by append(), getBuffer(), getLen(), getRawBuffer(), isEmpty(), reset(), set(), and ~XMLBufBid().
fMgr
XMLBufferMgr *const XMLBufBid::fMgr private
Definition at line 207 of file XMLBufferMgr.hpp.
Referenced by ~XMLBufBid().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/XMLBufferMgr.hpp