Seamly2D: VAbstractPattern Class Reference
VAbstractPattern Class Reference abstract
#include <vabstractpattern.h>
Public Slots
virtual void LiteParseTree (const Document &parse)=0
void haveLiteChange ()
haveLiteChange we have unsaved change.
void NeedFullParsing ()
void ClearScene ()
void updatePieceList (quint32 id)
void selectedPiece (quint32 id)
Signals
void activeDraftBlockChanged (const QString &newName)
activeDraftBlockChanged change active draft block.
void ChangedCursor (quint32 id)
ChangedCursor change cursor position.
void draftBlockNameChanged (const QString &oldName, const QString &newName)
draftBlockNameChanged save new name draft block.
void FullUpdateFromFile ()
FullUpdateFromFile update tool data form file.
void patternChanged (bool saved)
patternChanged emit if we have unsaved change.
void UpdatePatternLabel ()
void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
void ClearMainWindow ()
void UndoCommand ()
void setGuiEnabled (bool enabled)
void CheckLayout ()
void UpdateInLayoutList (quint32 id)
void showPiece (quint32 id)
void setCurrentDraftBlock (const QString &patterPiece)
void patternHasGroups (bool value)
void updateGroups ()
Public Member Functions
VAbstractPattern (QObject *parent=nullptr)
virtual ~VAbstractPattern () Q_DECL_EQ_DEFAULT
QStringList ListMeasurements () const
QVector< VFormulaField > ListExpressions () const
QVector< VFormulaField > ListIncrementExpressions () const
virtual void CreateEmptyFile ()=0
void changeActiveDraftBlock (const QString &name, const Document &parse=Document::FullParse)
changeActiveDraftBlock set new active draft block name.
QString getActiveDraftBlockName () const
getActiveDraftBlockName return current draft block name.
bool draftBlockNameExists (const QString &name) const
draftBlockNameExists check if draft block with this name exists.
int draftBlockCount () const
QDomElement getDraftBlockElement (const QString &name)
bool renameDraftBlock (const QString &oldName, const QString &newName)
renameDraftBlock change draft block name.
bool appendDraftBlock (const QString &name)
appendDraftBlock add new draft block.
bool getActiveNodeElement (const QString &name, QDomElement &element) const
getActiveNodeElement find element in current draft block by name.
quint32 getCursor () const
void setCursor (const quint32 &value)
void setDefaultPen (Pen pen)
QString getDefaultLineColor () const
qreal getDefaultLineWeight () const
QString getDefaultLineType () const
virtual void IncrementReferens (quint32 id) const =0
virtual void DecrementReferens (quint32 id) const =0
virtual QString GenerateLabel (const LabelType &type, const QString &reservedName=QString()) const =0
virtual QString GenerateSuffix (const QString &type) const =0
virtual void UpdateToolData (const quint32 &id, VContainer *data)=0
void AddToolOnRemove (VDataTool *tool)
QVector< VToolRecord > * getHistory ()
getHistory return list with list of history records.
QVector< VToolRecord > getBlockHistory () const
QMap< quint32, Tool > getGroupObjHistory () const
QString MPath () const
void SetMPath (const QString &path)
quint32 SiblingNodeId (const quint32 &nodeId) const
QStringList getPatternPieces () const
QMap< GHeights, bool > GetGradationHeights () const
void SetGradationHeights (const QMap< GHeights, bool > &options)
QMap< GSizes, bool > GetGradationSizes () const
void SetGradationSizes (const QMap< GSizes, bool > &options)
QString GetDescription () const
void SetDescription (const QString &text)
QString GetNotes () const
void SetNotes (const QString &text)
QString GetPatternName () const
void SetPatternName (const QString &qsName)
QString GetCompanyName () const
void SetCompanyName (const QString &qsName)
QString GetPatternNumber () const
void SetPatternNumber (const QString &qsNum)
QString GetCustomerName () const
void SetCustomerName (const QString &qsName)
QString GetLabelDateFormat () const
void SetLabelDateFormat (const QString &format)
QString GetLabelTimeFormat () const
void SetLabelTimeFormat (const QString &format)
void setPatternLabelTemplate (const QVector< VLabelTemplateLine > &lines)
QVector< VLabelTemplateLine > getPatternLabelTemplate () const
void SetPatternWasChanged (bool changed)
bool GetPatternWasChanged () const
QString GetImage () const
QString GetImageExtension () const
void SetImage (const QString &text, const QString &extension)
void DeleteImage ()
QString GetVersion () const
void SetVersion ()
QVector< quint32 > getOpItems (const quint32 &toolId, const QString &itemType)
getOpItems get vector of operation tool obects.
QVector< quint32 > getDartItems (const quint32 &toolId)
bool IsModified () const
void SetModified (bool modified)
QDomElement getDraw (const QString &name) const
void parseGroups (const QDomElement &domElement)
QDomElement createGroups ()
QDomElement createGroup (quint32 id, const QString &name, const QString &color, const QString &type, const QString &weight, const QMap< quint32, quint32 > &groupData)
QDomElement addGroupItems (const QString &name, const QMap< quint32, quint32 > &groupData)
QString getGroupName (quint32 id)
void setGroupName (quint32 id, const QString &name)
QMap< quint32, GroupAttributes > getGroups ()
QStringList groupListByName ()
QDomElement getGroupByName (const QString &name)
quint32 getGroupIdByName (const QString &name)
QMap< quint32, QString > getGroupsContainingItem (quint32 toolId, quint32 objectId, bool containsItem)
Returns the groups that contain or do not contain the item identified by the toolid and the objectid.
void deleteToolFromGroup (quint32 toolId)
Deletes an item from the group containing the toolId.
void addToolToGroup (quint32 toolId, quint32 objectId, const QString &groupName)
Adds an item to the given group with the given toolId and objectId.
QDomElement addGroupItem (quint32 toolId, quint32 objectId, quint32 groupId)
Adds an item to the given group with the given toolId and objectId.
QDomElement removeGroupItem (quint32 toolId, quint32 objectId, quint32 groupId)
Removes the item of given toolId and objectId from the group of given groupId.
bool isGroupEmpty (quint32 id)
Returns true if the given group is empty.
bool getGroupVisibility (quint32 id)
void setGroupVisibility (quint32 id, bool visible)
bool getGroupLock (quint32 id)
void setGroupLock (quint32 id, bool locked)
QString getGroupColor (quint32 id)
void setGroupColor (quint32 id, QString color)
QString getGroupLineType (quint32 id)
void setGroupLineType (quint32 id, QString type)
QString getGroupLineWeight (quint32 id)
void setGroupLineWeight (quint32 id, QString weight)
bool groupNameExists (const QString &groupName)
QString useGroupColor (quint32 toolId, QString color)
QString useGroupLineType (quint32 toolId, QString type)
QString useGroupLineWeight (quint32 toolId, QString weight)
QPair< bool, QMap< quint32, quint32 > > parseItemElement (const QDomElement &domElement)
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit MUnit () const
virtual void setXMLContent (const QString &fileName)
virtual bool SaveDocument (const QString &fileName, QString &error)
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Static Public Member Functions
static VDataTool * getTool (quint32 id)
getTool return tool from tool list.
static void AddTool (quint32 id, VDataTool *tool)
AddTool add tool to list tools.
static void RemoveTool (quint32 id)
static VPiecePath ParsePieceNodes (const QDomElement &domElement)
static QVector< CustomSARecord > ParsePieceCSARecords (const QDomElement &domElement)
static QVector< quint32 > ParsePieceInternalPaths (const QDomElement &domElement)
static QVector< quint32 > ParsePieceAnchors (const QDomElement &domElement)
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Static Public Attributes
static const QString TagPattern = QStringLiteral("pattern")
static const QString TagCalculation = QStringLiteral("calculation")
static const QString TagModeling = QStringLiteral("modeling")
static const QString TagPieces = QStringLiteral("pieces")
static const QString TagPiece = QStringLiteral("piece")
static const QString TagDescription = QStringLiteral("description")
static const QString TagImage = QStringLiteral("image")
static const QString TagNotes = QStringLiteral("notes")
static const QString TagMeasurements = QStringLiteral("measurements")
static const QString TagIncrements = QStringLiteral("increments")
static const QString TagIncrement = QStringLiteral("increment")
static const QString TagDraftBlock = QStringLiteral("draftBlock")
static const QString TagGroups = QStringLiteral("groups")
static const QString TagGroup = QStringLiteral("group")
static const QString TagGroupItem = QStringLiteral("item")
static const QString TagPoint = QStringLiteral("point")
static const QString TagSpline = QStringLiteral("spline")
static const QString TagArc = QStringLiteral("arc")
static const QString TagElArc = QStringLiteral("elArc")
static const QString TagTools = QStringLiteral("tools")
static const QString TagOperation = QStringLiteral("operation")
static const QString TagGradation = QStringLiteral("gradation")
static const QString TagHeights = QStringLiteral("heights")
static const QString TagSizes = QStringLiteral("sizes")
static const QString TagData = QStringLiteral("data")
static const QString TagPatternInfo = QStringLiteral("patternInfo")
static const QString TagPatternName = QStringLiteral("patternName")
static const QString TagPatternNum = QStringLiteral("patternNumber")
static const QString TagCompanyName = QStringLiteral("company")
static const QString TagCustomerName = QStringLiteral("customer")
static const QString TagPatternLabel = QStringLiteral("patternLabel")
static const QString TagGrainline = QStringLiteral("grainline")
static const QString TagPath = QStringLiteral("path")
static const QString TagNodes = QStringLiteral("nodes")
static const QString TagNode = QStringLiteral("node")
static const QString TagLine = QStringLiteral("line")
static const QString AttrName = QStringLiteral("name")
static const QString AttrVisible = QStringLiteral("visible")
static const QString AttrGroupLocked = QStringLiteral("locked")
static const QString AttrGroupColor = QStringLiteral("groupColor")
static const QString AttrObject = QStringLiteral("object")
static const QString AttrTool = QStringLiteral("tool")
static const QString AttrType = QStringLiteral("type")
static const QString AttrLetter = QStringLiteral("letter")
static const QString AttrAnnotation = QStringLiteral("annotation")
static const QString AttrOrientation = QStringLiteral("orientation")
static const QString AttrRotationWay = QStringLiteral("rotationWay")
static const QString AttrTilt = QStringLiteral("tilt")
static const QString AttrFoldPosition = QStringLiteral("foldPosition")
static const QString AttrQuantity = QStringLiteral("quantity")
static const QString AttrOnFold = QStringLiteral("onFold")
static const QString AttrDateFormat = QStringLiteral("dateFormat")
static const QString AttrTimeFormat = QStringLiteral("timeFormat")
static const QString AttrArrows = QStringLiteral("arrows")
static const QString AttrNodeReverse = QStringLiteral("reverse")
static const QString AttrNodeExcluded = QStringLiteral("excluded")
static const QString AttrNodeIsNotch = QStringLiteral("notch")
static const QString AttrNodeNotchType = QStringLiteral("notchType")
static const QString AttrNodeNotchSubType = QStringLiteral("notchSubtype")
static const QString AttrNodeShowNotch = QStringLiteral("showNotch")
static const QString AttrNodeShowSecondNotch = QStringLiteral("showSecondNotch")
static const QString AttrNodeNotchLength = QStringLiteral("notchLength")
static const QString AttrNodeNotchWidth = QStringLiteral("notchWidth")
static const QString AttrNodeNotchAngle = QStringLiteral("notchAngle")
static const QString AttrNodeNotchCount = QStringLiteral("notchCount")
static const QString AttrSABefore = QStringLiteral("before")
static const QString AttrSAAfter = QStringLiteral("after")
static const QString AttrStart = QStringLiteral("start")
static const QString AttrPath = QStringLiteral("path")
static const QString AttrEnd = QStringLiteral("end")
static const QString AttrIncludeAs = QStringLiteral("includeAs")
static const QString AttrWidth = QStringLiteral("width")
static const QString AttrRotation = QStringLiteral("rotation")
static const QString AttrAll = QStringLiteral("all")
static const QString AttrH50 = QStringLiteral("h50")
static const QString AttrH56 = QStringLiteral("h56")
static const QString AttrH62 = QStringLiteral("h62")
static const QString AttrH68 = QStringLiteral("h68")
static const QString AttrH74 = QStringLiteral("h74")
static const QString AttrH80 = QStringLiteral("h80")
static const QString AttrH86 = QStringLiteral("h86")
static const QString AttrH92 = QStringLiteral("h92")
static const QString AttrH98 = QStringLiteral("h98")
static const QString AttrH104 = QStringLiteral("h104")
static const QString AttrH110 = QStringLiteral("h110")
static const QString AttrH116 = QStringLiteral("h116")
static const QString AttrH122 = QStringLiteral("h122")
static const QString AttrH128 = QStringLiteral("h128")
static const QString AttrH134 = QStringLiteral("h134")
static const QString AttrH140 = QStringLiteral("h140")
static const QString AttrH146 = QStringLiteral("h146")
static const QString AttrH152 = QStringLiteral("h152")
static const QString AttrH158 = QStringLiteral("h158")
static const QString AttrH164 = QStringLiteral("h164")
static const QString AttrH170 = QStringLiteral("h170")
static const QString AttrH176 = QStringLiteral("h176")
static const QString AttrH182 = QStringLiteral("h182")
static const QString AttrH188 = QStringLiteral("h188")
static const QString AttrH194 = QStringLiteral("h194")
static const QString AttrH200 = QStringLiteral("h200")
static const QString AttrS22 = QStringLiteral("s22")
static const QString AttrS24 = QStringLiteral("s24")
static const QString AttrS26 = QStringLiteral("s26")
static const QString AttrS28 = QStringLiteral("s28")
static const QString AttrS30 = QStringLiteral("s30")
static const QString AttrS32 = QStringLiteral("s32")
static const QString AttrS34 = QStringLiteral("s34")
static const QString AttrS36 = QStringLiteral("s36")
static const QString AttrS38 = QStringLiteral("s38")
static const QString AttrS40 = QStringLiteral("s40")
static const QString AttrS42 = QStringLiteral("s42")
static const QString AttrS44 = QStringLiteral("s44")
static const QString AttrS46 = QStringLiteral("s46")
static const QString AttrS48 = QStringLiteral("s48")
static const QString AttrS50 = QStringLiteral("s50")
static const QString AttrS52 = QStringLiteral("s52")
static const QString AttrS54 = QStringLiteral("s54")
static const QString AttrS56 = QStringLiteral("s56")
static const QString AttrS58 = QStringLiteral("s58")
static const QString AttrS60 = QStringLiteral("s60")
static const QString AttrS62 = QStringLiteral("s62")
static const QString AttrS64 = QStringLiteral("s64")
static const QString AttrS66 = QStringLiteral("s66")
static const QString AttrS68 = QStringLiteral("s68")
static const QString AttrS70 = QStringLiteral("s70")
static const QString AttrS72 = QStringLiteral("s72")
static const QString AttrCustom = QStringLiteral("custom")
static const QString AttrDefHeight = QStringLiteral("defHeight")
static const QString AttrDefSize = QStringLiteral("defSize")
static const QString AttrExtension = QStringLiteral("extension")
static const QString IncrementName = QStringLiteral("name")
static const QString IncrementFormula = QStringLiteral("formula")
static const QString IncrementDescription = QStringLiteral("description")
static const QString NodeArc = QStringLiteral("NodeArc")
static const QString NodeElArc = QStringLiteral("NodeElArc")
static const QString NodePoint = QStringLiteral("NodePoint")
static const QString NodeSpline = QStringLiteral("NodeSpline")
static const QString NodeSplinePath = QStringLiteral("NodeSplinePath")
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Protected Member Functions
void setActiveDraftBlock (const QString &name)
setActiveDraftBlock set current draft block.
QDomElement CheckTagExists (const QString &tag)
void InsertTag (const QStringList &tags, const QDomElement &element)
void SetChildTag (const QString &qsParent, const QString &qsChild, const QString &qsValue)
int getActiveDraftBlockIndex () const
bool getActiveDraftElement (QDomElement &element) const
getActiveDraftElement return draftBlock element for current draft block.
bool hasGroupItem (const QDomElement &domElement, quint32 toolId, quint32 objectId)
Checks if the given group has the item with the given toolId and objectId.
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Static Protected Member Functions
static void ToolExists (const quint32 &id)
static VPiecePath ParsePathNodes (const QDomElement &domElement)
static VPieceNode ParseSANode (const QDomElement &domElement)
Protected Attributes
QString activeDraftBlock
activeBlockName name current pattern peace.
QString m_DefaultLineColor
qreal m_DefaultLineWeight
QString m_DefaultLineType
QString lastSavedExportFormat
quint32 cursor
cursor cursor keep id tool after which we will add new tool in file.
QVector< VDataTool * > toolsOnRemove
QVector< VToolRecord > history
history history records.
QStringList patternPieces
patternPieces list of patern pieces names for combobox
bool modified
modified keep state of the document for cases that do not cover QUndoStack
Static Protected Attributes
static QHash< quint32, VDataTool * > tools = QHash<quint32, VDataTool*>()
tools list with pointer on tools.
static QVector< VLabelTemplateLine > patternLabelLines = QVector<VLabelTemplateLine>()
patternLabelLines list to speed up reading a template by many pieces.
static bool patternLabelWasChanged = false
Private Member Functions
QStringList ListIncrements () const
QVector< VFormulaField > ListPointExpressions () const
QVector< VFormulaField > ListArcExpressions () const
QVector< VFormulaField > ListElArcExpressions () const
QVector< VFormulaField > ListSplineExpressions () const
QVector< VFormulaField > ListPathPointExpressions () const
QVector< VFormulaField > ListOperationExpressions () const
QVector< VFormulaField > ListNodesExpressions (const QDomElement &nodes) const
QVector< VFormulaField > ListPathExpressions () const
QVector< VFormulaField > ListGrainlineExpressions (const QDomElement &element) const
QVector< VFormulaField > ListPieceExpressions () const
bool IsVariable (const QString &token) const
bool IsPostfixOperator (const QString &token) const
bool IsFunction (const QString &token) const
QPair< bool, QMap< quint32, quint32 > > ParseItemElement (const QDomElement &domElement)
Detailed Description
Definition at line 112 of file vabstractpattern.h.
Constructor & Destructor Documentation
VAbstractPattern()
VAbstractPattern::VAbstractPattern (QObject * parent = nullptr) explicit
Definition at line 257 of file vabstractpattern.cpp.
~VAbstractPattern()
virtual VAbstractPattern::~VAbstractPattern () virtual
Member Function Documentation
activeDraftBlockChanged
void VAbstractPattern::activeDraftBlockChanged (const QString & newName) signal
activeDraftBlockChanged change active draft block.
Parameters
newName new pattern peace name.
Referenced by changeActiveDraftBlock(), setActiveDraftBlock(), and VDrawTool::VDrawTool().
addGroupItem()
QDomElement VAbstractPattern::addGroupItem (quint32 toolId, quint32 objectId, quint32 groupId)
Adds an item to the given group with the given toolId and objectId.
Parameters
toolId
objectId
groupId
Definition at line 2687 of file vabstractpattern.cpp.
References AttrObject, AttrTool, createGroups(), VDomDocument::elementById(), getGroupLock(), modified, parseGroups(), patternChanged(), TagGroup, TagGroupItem, and updateGroups().
Referenced by addToolToGroup(), VDrawTool::ContextMenu(), and GroupsWidget::groupItemContextMenu().
addGroupItems()
QDomElement VAbstractPattern::addGroupItems (const QString & name, const QMap< quint32, quint32 > & groupData)
Definition at line 2237 of file vabstractpattern.cpp.
References AttrGroupLocked, AttrObject, AttrTool, getGroupByName(), getGroupIdByName(), getGroupLock(), VDomDocument::getParameterBool(), modified, patternChanged(), TagGroupItem, trueStr, and updateGroups().
Referenced by MainWindow::ClosedEditGroupDialog().
AddTool()
void VAbstractPattern::AddTool (quint32 id, VDataTool * tool) static
AddTool add tool to list tools.
Parameters
id tool id.
tool tool.
Definition at line 661 of file vabstractpattern.cpp.
References SCASSERT, and tools.
Referenced by VToolLine::Create(), PointIntersectXYTool::Create(), VToolCurveIntersectAxis::Create(), VToolLineIntersectAxis::Create(), VToolEndLine::Create(), VToolHeight::Create(), VToolAlongLine::Create(), VToolPointOfIntersectionArcs::Create(), VToolCutSpline::Create(), VToolCutArc::Create(), VToolCutSplinePath::Create(), VToolPointFromArcAndTangent::Create(), VToolTriangle::Create(), IntersectCircleTangentTool::Create(), IntersectCirclesTool::Create(), VToolPointOfIntersectionCurves::Create(), VToolArc::Create(), VToolArcWithLength::Create(), VToolEllipticalArc::Create(), VToolRotation::Create(), VToolLineIntersect::Create(), UnionTool::Create(), VToolNormal::Create(), VToolBisector::Create(), VToolShoulderPoint::Create(), VToolPointOfContact::Create(), VToolMirrorByLine::Create(), VToolMirrorByAxis::Create(), VToolCubicBezier::Create(), VToolCubicBezierPath::Create(), VToolSpline::Create(), VToolSplinePath::Create(), VToolBasePoint::Create(), VToolTrueDarts::Create(), VToolInternalPath::Create(), VToolMove::Create(), AnchorPointTool::Create(), PatternPieceTool::Create(), VNodeArc::Create(), VNodeEllipticalArc::Create(), VNodeSpline::Create(), VNodeSplinePath::Create(), and VNodePoint::Create().
AddToolOnRemove()
void VAbstractPattern::AddToolOnRemove (VDataTool * tool)
Definition at line 832 of file vabstractpattern.cpp.
References SCASSERT, and toolsOnRemove.
Referenced by UnionTool::Create(), AnchorPointTool::Create(), VNodeArc::Create(), VNodeEllipticalArc::Create(), VNodeSpline::Create(), and VNodeSplinePath::Create().
addToolToGroup()
void VAbstractPattern::addToolToGroup (quint32 toolId, quint32 objectId, const QString & groupName)
Adds an item to the given group with the given toolId and objectId.
Parameters
toolId
Definition at line 2638 of file vabstractpattern.cpp.
References addGroupItem(), createGroups(), getGroupIdByName(), getGroupLock(), getGroupsContainingItem(), modified, parseGroups(), patternChanged(), removeGroupItem(), and updateGroups().
appendDraftBlock()
bool VAbstractPattern::appendDraftBlock (const QString & name)
appendDraftBlock add new draft block.
Method check if not exist draft block with the same name and change name active draft block name, send signal about change draft block. Doen't add draft block to file structure. This task make SPoint tool.
Parameters
name draft block name.
Returns
true if success.
Definition at line 585 of file vabstractpattern.cpp.
References draftBlockNameExists(), and setActiveDraftBlock().
Referenced by MainWindow::addDraftBlock().
changeActiveDraftBlock()
void VAbstractPattern::changeActiveDraftBlock (const QString & name, const Document & parse = Document::FullParse)
changeActiveDraftBlock set new active draft block name.
Parameters
name new name.
parse parser file mode.
Definition at line 330 of file vabstractpattern.cpp.
References activeDraftBlock, activeDraftBlockChanged(), draftBlockNameExists(), and FullParse.
Referenced by MainWindow::changeDraftBlock(), MainWindow::exportDraftBlocksAs(), VPattern::Parse(), AddGroupItem::redo(), AddGroup::redo(), AddToCalc::redo(), MoveGroupItem::redo(), RemoveGroupItem::redo(), AddGroupItem::undo(), AddGroup::undo(), AddToCalc::undo(), DeleteDraftBlock::undo(), MoveGroupItem::undo(), and RemoveGroupItem::undo().
ChangedCursor
void VAbstractPattern::ChangedCursor (quint32 id) signal
ChangedCursor change cursor position.
Parameters
id tool id.
Referenced by HistoryDialog::HistoryDialog(), and setCursor().
CheckLayout
void VAbstractPattern::CheckLayout () signal
Referenced by MainWindow::MainWindow(), VPattern::Parse(), VPattern::parseCurrentDraftBlock(), and PatternPieceTool::PatternPieceTool().
CheckTagExists()
QDomElement VAbstractPattern::CheckTagExists (const QString & tag) protected
Definition at line 1706 of file vabstractpattern.cpp.
References AttrAll, InsertTag(), TagCompanyName, TagCustomerName, TagDescription, TagGradation, TagHeights, TagImage, TagNotes, TagPatternLabel, TagPatternName, TagPatternNum, TagSizes, and VDomDocument::TagUnit.
Referenced by DeleteImage(), SetCompanyName(), SetCustomerName(), VPattern::SetDefCustom(), VPattern::SetDefCustomHeight(), VPattern::SetDefCustomSize(), SetDescription(), SetGradationHeights(), SetGradationSizes(), SetImage(), SetLabelDateFormat(), SetLabelTimeFormat(), SetNotes(), setPatternLabelTemplate(), SetPatternName(), and SetPatternNumber().
ClearMainWindow
void VAbstractPattern::ClearMainWindow () signal
Referenced by ClearScene(), and MainWindow::MainWindow().
ClearScene
void VAbstractPattern::ClearScene () slot
Definition at line 1651 of file vabstractpattern.cpp.
References ClearMainWindow().
Referenced by VToolBasePoint::AddToFile().
CreateEmptyFile()
virtual void VAbstractPattern::CreateEmptyFile () pure virtual
Implemented in VLitePattern, and VPattern.
Referenced by AddDraftBlock::redo().
createGroup()
QDomElement VAbstractPattern::createGroup (quint32 id, const QString & name, const QString & color, const QString & type, const QString & weight, const QMap< quint32, quint32 > & groupData)
Definition at line 2199 of file vabstractpattern.cpp.
References AttrGroupColor, AttrGroupLocked, VDomDocument::AttrId, AttrLineType, AttrLineWeight, AttrName, AttrObject, AttrTool, AttrVisible, NULL_ID, VDomDocument::SetAttribute(), TagGroup, and TagGroupItem.
Referenced by GroupsWidget::addGroupToList().
createGroups()
QDomElement VAbstractPattern::createGroups ()
Definition at line 2180 of file vabstractpattern.cpp.
References getActiveDraftElement(), and TagGroups.
Referenced by addGroupItem(), addToolToGroup(), getGroupByName(), getGroupIdByName(), getGroupName(), getGroups(), getGroupsContainingItem(), groupListByName(), AddGroupItem::redo(), AddGroup::redo(), DelGroup::redo(), MoveGroupItem::redo(), RemoveGroupItem::redo(), removeGroupItem(), setGroupLock(), setGroupName(), setGroupVisibility(), AddGroupItem::undo(), AddGroup::undo(), DelGroup::undo(), MoveGroupItem::undo(), and RemoveGroupItem::undo().
DecrementReferens()
virtual void VAbstractPattern::DecrementReferens (quint32 id) const pure virtual
Implemented in VLitePattern, and VPattern.
Referenced by VToolInternalPath::DecrementNodes(), VUndoCommand::DecrementReferences(), VAbstractNode::decrementReferens(), VToolInternalPath::decrementReferens(), UnionTool::decrementReferens(), VToolArc::RemoveReferens(), VToolArcWithLength::RemoveReferens(), VToolCubicBezier::RemoveReferens(), VToolCubicBezierPath::RemoveReferens(), VToolEllipticalArc::RemoveReferens(), VToolSpline::RemoveReferens(), VToolSplinePath::RemoveReferens(), VToolTrueDarts::RemoveReferens(), IntersectCirclesTool::RemoveReferens(), IntersectCircleTangentTool::RemoveReferens(), PointIntersectXYTool::RemoveReferens(), VToolCut::RemoveReferens(), DoubleLinePointTool::RemoveReferens(), VToolAlongLine::RemoveReferens(), VToolBisector::RemoveReferens(), VToolLinePoint::RemoveReferens(), VToolNormal::RemoveReferens(), VToolShoulderPoint::RemoveReferens(), VToolLineIntersect::RemoveReferens(), VToolPointFromArcAndTangent::RemoveReferens(), VToolPointOfContact::RemoveReferens(), VToolPointOfIntersectionArcs::RemoveReferens(), VToolPointOfIntersectionCurves::RemoveReferens(), VToolTriangle::RemoveReferens(), and VToolLine::RemoveReferens().
DeleteImage()
void VAbstractPattern::DeleteImage ()
Definition at line 1564 of file vabstractpattern.cpp.
References CheckTagExists(), modified, patternChanged(), and TagImage.
Referenced by DialogPatternProperties::InitImage().
deleteToolFromGroup()
void VAbstractPattern::deleteToolFromGroup (quint32 toolId)
Deletes an item from the group containing the toolId.
Parameters
toolId
Definition at line 2618 of file vabstractpattern.cpp.
References getGroupLock(), getGroupsContainingItem(), and removeGroupItem().
draftBlockCount()
int VAbstractPattern::draftBlockCount () const
Definition at line 497 of file vabstractpattern.cpp.
References TagDraftBlock.
Referenced by AddDraftBlock::redo(), VPattern::setCurrentData(), VToolBasePoint::showContextMenu(), and AddDraftBlock::undo().
draftBlockNameChanged
void VAbstractPattern::draftBlockNameChanged (const QString & oldName, const QString & newName) signal
draftBlockNameChanged save new name draft block.
Parameters
oldName old name.
newName new name.
Referenced by renameDraftBlock(), and VDrawTool::VDrawTool().
draftBlockNameExists()
bool VAbstractPattern::draftBlockNameExists (const QString & name) const
draftBlockNameExists check if draft block with this name exists.
Parameters
name draft block name.
Returns
true if exist.
Definition at line 391 of file vabstractpattern.cpp.
References AttrName, VDomDocument::GetParametrString(), and TagDraftBlock.
Referenced by appendDraftBlock(), changeActiveDraftBlock(), and renameDraftBlock().
FullUpdateFromFile
void VAbstractPattern::FullUpdateFromFile () signal
FullUpdateFromFile update tool data form file.
Referenced by DialogVariables::DialogVariables(), MainWindow::InitDocksContain(), VPattern::LiteParseTree(), and VAbstractTool::VAbstractTool().
GenerateLabel()
virtual QString VAbstractPattern::GenerateLabel (const LabelType & type, const QString & reservedName = QString()) const pure virtual
Implemented in VLitePattern, and VPattern.
GenerateSuffix()
virtual QString VAbstractPattern::GenerateSuffix (const QString & type) const pure virtual
Implemented in VLitePattern, and VPattern.
getActiveDraftBlockIndex()
int VAbstractPattern::getActiveDraftBlockIndex () const protected
Definition at line 1781 of file vabstractpattern.cpp.
References activeDraftBlock, AttrName, and TagDraftBlock.
Referenced by VPattern::GenerateLabel(), and VPattern::GenerateSuffix().
getActiveDraftBlockName()
QString VAbstractPattern::getActiveDraftBlockName () const
getActiveDraftBlockName return current draft block name.
Returns
draft block name.
Definition at line 348 of file vabstractpattern.cpp.
References activeDraftBlock.
Referenced by VAbstractTool::AddRecord(), MainWindow::exportDraftBlocksAs(), getBlockHistory(), getGroupObjHistory(), RenameDraftBlock::RenameDraftBlock(), and MainWindow::setWidgetsEnabled().
getActiveDraftElement()
bool VAbstractPattern::getActiveDraftElement (QDomElement & element) const protected
getActiveDraftElement return draftBlock element for current draft block.
Parameters
element draftBlock element.
Returns
true if found.
Definition at line 359 of file vabstractpattern.cpp.
References activeDraftBlock, AttrName, and TagDraftBlock.
Referenced by createGroups(), getActiveNodeElement(), VPattern::getActivePatternPieces(), and VPattern::parseCurrentDraftBlock().
getActiveNodeElement()
bool VAbstractPattern::getActiveNodeElement (const QString & name, QDomElement & element) const
getActiveNodeElement find element in current draft block by name.
Parameters
name name tag.
element element.
Returns
true if found.
Definition at line 420 of file vabstractpattern.cpp.
References getActiveDraftElement().
Referenced by VPattern::getActiveBasePoint(), AddDetNode::GetModelingSection(), AddPiece::getPiecesElement(), AddToCalc::redo(), and AddToCalc::undo().
getBlockHistory()
QVector< VToolRecord > VAbstractPattern::getBlockHistory () const
Definition at line 849 of file vabstractpattern.cpp.
References getActiveDraftBlockName(), VToolRecord::getDraftBlockName(), and history.
Referenced by HistoryDialog::fillTable(), and SiblingNodeId().
GetCompanyName()
QString VAbstractPattern::GetCompanyName () const
Definition at line 1384 of file vabstractpattern.cpp.
References TagCompanyName, and VDomDocument::UniqueTagText().
Referenced by DialogPatternProperties::DialogPatternProperties(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and ShowInfoDialog::ShowInfoDialog().
getCursor()
quint32 VAbstractPattern::getCursor () const
Definition at line 601 of file vabstractpattern.cpp.
References cursor.
Referenced by VAbstractTool::AddRecord(), MainWindow::ClosedDialogWithApply(), and HistoryDialog::cursorRow().
GetCustomerName()
QString VAbstractPattern::GetCustomerName () const
Definition at line 1416 of file vabstractpattern.cpp.
References TagCustomerName, and VDomDocument::UniqueTagText().
Referenced by DialogPatternProperties::DialogPatternProperties(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and ShowInfoDialog::ShowInfoDialog().
getDartItems()
QVector< quint32 > VAbstractPattern::getDartItems (const quint32 & toolId)
Definition at line 1620 of file vabstractpattern.cpp.
References AttrPoint1, AttrPoint2, VDomDocument::elementById(), VDomDocument::GetParametrUInt(), and NULL_ID_STR.
getDefaultLineColor()
QString VAbstractPattern::getDefaultLineColor () const
Definition at line 626 of file vabstractpattern.cpp.
References m_DefaultLineColor.
getDefaultLineType()
QString VAbstractPattern::getDefaultLineType () const
Definition at line 638 of file vabstractpattern.cpp.
References m_DefaultLineType.
getDefaultLineWeight()
qreal VAbstractPattern::getDefaultLineWeight () const
Definition at line 632 of file vabstractpattern.cpp.
References m_DefaultLineWeight.
GetDescription()
QString VAbstractPattern::GetDescription () const
Definition at line 1338 of file vabstractpattern.cpp.
References TagDescription, and VDomDocument::UniqueTagText().
Referenced by DialogPatternProperties::DialogPatternProperties(), MainWindowsNoGUI::exportSVG(), and ShowInfoDialog::ShowInfoDialog().
getDraftBlockElement()
QDomElement VAbstractPattern::getDraftBlockElement (const QString & name)
Definition at line 509 of file vabstractpattern.cpp.
References AttrName, and TagDraftBlock.
Referenced by UnionTool::AddToModeling(), DeleteDraftBlock::DeleteDraftBlock(), AddDetNode::GetModelingSection(), AddPiece::getPiecesElement(), DeleteDraftBlock::redo(), renameDraftBlock(), AddDraftBlock::undo(), and DeleteDraftBlock::undo().
getDraw()
QDomElement VAbstractPattern::getDraw (const QString & name) const
GetGradationHeights()
QMap< GHeights, bool > VAbstractPattern::GetGradationHeights () const
Definition at line 949 of file vabstractpattern.cpp.
References ALL, AttrAll, AttrH104, AttrH110, AttrH116, AttrH122, AttrH128, AttrH134, AttrH140, AttrH146, AttrH152, AttrH158, AttrH164, AttrH170, AttrH176, AttrH182, AttrH188, AttrH194, AttrH200, AttrH50, AttrH56, AttrH62, AttrH68, AttrH74, AttrH80, AttrH86, AttrH92, AttrH98, VDomDocument::getParameterBool(), H104, H110, H116, H122, H128, H134, H140, H146, H152, H158, H164, H170, H176, H182, H188, H194, H200, H50, H56, H62, H68, H74, H80, H86, H92, H98, VDomDocument::map, TagGradation, TagHeights, TagSizes, and trueStr.
Referenced by DialogPatternProperties::DialogPatternProperties(), and MainWindow::initStatusBar().
GetGradationSizes()
QMap< GSizes, bool > VAbstractPattern::GetGradationSizes () const
Definition at line 1144 of file vabstractpattern.cpp.
References ALL, AttrAll, AttrS22, AttrS24, AttrS26, AttrS28, AttrS30, AttrS32, AttrS34, AttrS36, AttrS38, AttrS40, AttrS42, AttrS44, AttrS46, AttrS48, AttrS50, AttrS52, AttrS54, AttrS56, AttrS58, AttrS60, AttrS62, AttrS64, AttrS66, AttrS68, AttrS70, AttrS72, VDomDocument::getParameterBool(), VDomDocument::map, S22, S24, S26, S28, S30, S32, S34, S36, S38, S40, S42, S44, S46, S48, S50, S52, S54, S56, S58, S60, S62, S64, S66, S68, S70, S72, TagGradation, TagHeights, TagSizes, and trueStr.
Referenced by DialogPatternProperties::DialogPatternProperties(), and MainWindow::initStatusBar().
getGroupByName()
QDomElement VAbstractPattern::getGroupByName (const QString & name)
Definition at line 2447 of file vabstractpattern.cpp.
References AttrName, createGroups(), VDomDocument::GetParametrString(), patternHasGroups(), and TagGroup.
Referenced by addGroupItems(), GroupsWidget::fillGroupItemList(), useGroupColor(), useGroupLineType(), and useGroupLineWeight().
getGroupColor()
QString VAbstractPattern::getGroupColor (quint32 id)
Definition at line 2909 of file vabstractpattern.cpp.
References AttrGroupColor, ColorBlack, VDomDocument::elementById(), VDomDocument::GetParametrString(), and TagGroup.
Referenced by GroupsWidget::editGroup(), GroupsWidget::groupContextMenu(), and useGroupColor().
getGroupIdByName()
quint32 VAbstractPattern::getGroupIdByName (const QString & name)
Definition at line 2491 of file vabstractpattern.cpp.
References VDomDocument::AttrId, AttrName, createGroups(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), and TagGroup.
Referenced by addGroupItems(), addToolToGroup(), useGroupColor(), useGroupLineType(), and useGroupLineWeight().
getGroupLineType()
QString VAbstractPattern::getGroupLineType (quint32 id)
Definition at line 2949 of file vabstractpattern.cpp.
References AttrLineType, VDomDocument::elementById(), VDomDocument::GetParametrString(), LineTypeSolidLine, and TagGroup.
Referenced by GroupsWidget::editGroup(), GroupsWidget::groupContextMenu(), and useGroupLineType().
getGroupLineWeight()
QString VAbstractPattern::getGroupLineWeight (quint32 id)
Definition at line 2989 of file vabstractpattern.cpp.
References AttrLineWeight, ColorBlack, VDomDocument::elementById(), VDomDocument::GetParametrString(), and TagGroup.
Referenced by GroupsWidget::editGroup(), GroupsWidget::groupContextMenu(), and useGroupLineWeight().
getGroupLock()
bool VAbstractPattern::getGroupLock (quint32 id)
Definition at line 2865 of file vabstractpattern.cpp.
References AttrGroupLocked, VDomDocument::elementById(), VDomDocument::getParameterBool(), TagGroup, and trueStr.
Referenced by addGroupItem(), addGroupItems(), addToolToGroup(), GroupsWidget::deleteGroupFromList(), deleteToolFromGroup(), GroupsWidget::editGroup(), GroupsWidget::groupContextMenu(), GroupsWidget::groupItemContextMenu(), GroupsWidget::groupLockChanged(), GroupsWidget::groupVisibilityChanged(), GroupsWidget::hideAllGroups(), GroupTableWidgetItem::operator<(), removeGroupItem(), GroupsWidget::renameGroup(), and GroupsWidget::showAllGroups().
getGroupName()
QString VAbstractPattern::getGroupName (quint32 id)
Definition at line 2271 of file vabstractpattern.cpp.
References AttrName, createGroups(), VDomDocument::elementById(), VDomDocument::GetParametrString(), and TagGroup.
Referenced by GroupsWidget::editGroup(), and GroupsWidget::groupContextMenu().
getGroupObjHistory()
QMap< quint32, Tool > VAbstractPattern::getGroupObjHistory () const
Definition at line 865 of file vabstractpattern.cpp.
References getActiveDraftBlockName(), VToolRecord::getDraftBlockName(), VToolRecord::getId(), VToolRecord::getTypeTool(), and history.
Referenced by GroupsWidget::fillGroupItemList().
getGroups()
QMap< quint32, GroupAttributes > VAbstractPattern::getGroups ()
Definition at line 2333 of file vabstractpattern.cpp.
References AttrGroupColor, AttrGroupLocked, VDomDocument::AttrId, AttrLineType, AttrLineWeight, AttrName, AttrVisible, GroupAttributes::color, ColorBlack, createGroups(), VDomDocument::getParameterBool(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), GroupAttributes::linetype, LineTypeSolidLine, GroupAttributes::lineweight, GroupAttributes::locked, GroupAttributes::name, patternHasGroups(), TagGroup, trueStr, and GroupAttributes::visible.
Referenced by AddToGroupDialog::fillNameBox(), and GroupsWidget::updateGroups().
getGroupsContainingItem()
QMap< quint32, QString > VAbstractPattern::getGroupsContainingItem (quint32 toolId, quint32 objectId, bool containsItem)
Returns the groups that contain or do not contain the item identified by the toolid and the objectid.
Parameters
toolId
objectId
containsItem |true if the groups contain the given item, false if they don't contain the item
Returns
Definition at line 2537 of file vabstractpattern.cpp.
References VDomDocument::AttrId, AttrName, createGroups(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), hasGroupItem(), and TagGroup.
Referenced by addToolToGroup(), VDrawTool::ContextMenu(), deleteToolFromGroup(), GroupsWidget::groupItemContextMenu(), useGroupColor(), useGroupLineType(), useGroupLineWeight(), GroupsWidget::zoomToObject(), and MainWindow::zoomToPoint().
getGroupVisibility()
bool VAbstractPattern::getGroupVisibility (quint32 id)
Definition at line 2821 of file vabstractpattern.cpp.
References AttrVisible, VDomDocument::elementById(), VDomDocument::getParameterBool(), TagGroup, and trueStr.
Referenced by GroupsWidget::groupVisibilityChanged(), and GroupTableWidgetItem::operator<().
getHistory()
QVector< VToolRecord > * VAbstractPattern::getHistory ()
getHistory return list with list of history records.
Returns
list of history records.
Definition at line 843 of file vabstractpattern.cpp.
References history.
Referenced by VAbstractTool::AddRecord(), and HistoryDialog::showTool().
GetImage()
QString VAbstractPattern::GetImage () const
Definition at line 1523 of file vabstractpattern.cpp.
References TagImage, and VDomDocument::UniqueTagText().
Referenced by DialogPatternProperties::GetImage(), DialogPatternProperties::SaveImage(), and ShowInfoDialog::ShowInfoDialog().
GetImageExtension()
QString VAbstractPattern::GetImageExtension () const
Definition at line 1529 of file vabstractpattern.cpp.
References AttrExtension, and TagImage.
Referenced by DialogPatternProperties::GetImage(), and DialogPatternProperties::SaveImage().
GetLabelDateFormat()
QString VAbstractPattern::GetLabelDateFormat () const
Definition at line 1432 of file vabstractpattern.cpp.
References AttrDateFormat, VDomDocument::GetParametrString(), qApp, and TagPatternLabel.
Referenced by DialogPatternProperties::DialogPatternProperties(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
GetLabelTimeFormat()
QString VAbstractPattern::GetLabelTimeFormat () const
Definition at line 1457 of file vabstractpattern.cpp.
References AttrTimeFormat, VDomDocument::GetParametrString(), qApp, and TagPatternLabel.
Referenced by DialogPatternProperties::DialogPatternProperties(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
GetNotes()
QString VAbstractPattern::GetNotes () const
Definition at line 1353 of file vabstractpattern.cpp.
References TagNotes, and VDomDocument::UniqueTagText().
Referenced by DialogPatternProperties::DialogPatternProperties(), and ShowInfoDialog::ShowInfoDialog().
getOpItems()
QVector< quint32 > VAbstractPattern::getOpItems (const quint32 & toolId, const QString & itemType)
getOpItems get vector of operation tool obects.
Parameters
toolId operation tool id.
itemType type of item - either source or destination.
Returns
vector of item element object ids.
Definition at line 1592 of file vabstractpattern.cpp.
References AttrIdObject, VDomDocument::elementById(), VDomDocument::GetParametrUInt(), and NULL_ID_STR.
getPatternLabelTemplate()
QVector< VLabelTemplateLine > VAbstractPattern::getPatternLabelTemplate () const
Definition at line 1494 of file vabstractpattern.cpp.
References VDomDocument::GetLabelTemplate(), patternLabelLines, and TagPatternLabel.
Referenced by DialogPatternProperties::EditLabel(), and VTextManager::Update().
GetPatternName()
QString VAbstractPattern::GetPatternName () const
Definition at line 1368 of file vabstractpattern.cpp.
References TagPatternName, and VDomDocument::UniqueTagText().
Referenced by DialogPatternProperties::DialogPatternProperties(), ShowInfoDialog::exportPdf(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and ShowInfoDialog::ShowInfoDialog().
GetPatternNumber()
QString VAbstractPattern::GetPatternNumber () const
Definition at line 1400 of file vabstractpattern.cpp.
References TagPatternNum, and VDomDocument::UniqueTagText().
Referenced by DialogPatternProperties::DialogPatternProperties(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and ShowInfoDialog::ShowInfoDialog().
getPatternPieces()
QStringList VAbstractPattern::getPatternPieces () const
Definition at line 943 of file vabstractpattern.cpp.
References patternPieces.
Referenced by MainWindow::fullParseFile().
GetPatternWasChanged()
bool VAbstractPattern::GetPatternWasChanged () const
Definition at line 1517 of file vabstractpattern.cpp.
References patternLabelWasChanged.
Referenced by VTextManager::Update().
getTool()
VDataTool * VAbstractPattern::getTool (quint32 id) static
getTool return tool from tool list.
Parameters
id tool id.
Returns
tool.
Definition at line 649 of file vabstractpattern.cpp.
References ToolExists(), and tools.
Referenced by PiecesWidget::cellDoubleClicked(), VToolInternalPath::Create(), AnchorPointTool::Create(), VNodeArc::Create(), VNodeEllipticalArc::Create(), VNodeSpline::Create(), VNodeSplinePath::Create(), VNodePoint::Create(), QT_WARNING_POP::createUnion(), ShowOperationPointName::Do(), MoveDoubleLabel::Do(), MoveLabel::Do(), MoveOperationLabel::Do(), PatternPieceTool::EnableToolMove(), PatternPieceTool::initializeNode(), PatternPieceTool::InitInternalPaths(), PatternPieceTool::insertNodes(), PatternPieceTool::pieceLockedChanged(), MainWindowsNoGUI::preparePiecesForLayout(), DeletePiece::redo(), RemoveGroupItem::redo(), MainWindowsNoGUI::refreshGrainLines(), MainWindowsNoGUI::refreshLabels(), MainWindowsNoGUI::refreshSeamAllowances(), ShowDoublePointName::setVisibility(), ShowPointName::setVisibility(), PatternPieceDialog::showAnchorPoints(), VToolCut::ShowToolVisualization(), AnchorPointDialog::ShowVisualization(), DialogInternalPath::ShowVisualization(), AddGroupItem::undo(), PatternPieceTool::UpdateExcludeState(), GroupsWidget::zoomToObject(), and MainWindow::zoomToPoint().
GetVersion()
QString VAbstractPattern::GetVersion () const
Definition at line 1573 of file vabstractpattern.cpp.
References VPatternConverter::PatternMaxVerStr, VDomDocument::TagVersion, and VDomDocument::UniqueTagText().
Referenced by ShowInfoDialog::ShowInfoDialog().
groupListByName()
QStringList VAbstractPattern::groupListByName ()
Definition at line 2397 of file vabstractpattern.cpp.
References AttrName, createGroups(), VDomDocument::GetParametrString(), patternHasGroups(), and TagGroup.
Referenced by groupNameExists().
groupNameExists()
bool VAbstractPattern::groupNameExists (const QString & groupName)
Definition at line 3027 of file vabstractpattern.cpp.
References groupListByName().
Referenced by GroupsWidget::addGroupToList(), GroupsWidget::editGroup(), and GroupsWidget::groupContextMenu().
hasGroupItem()
bool VAbstractPattern::hasGroupItem (const QDomElement & groupDomElement, quint32 toolId, quint32 objectId) protected
Checks if the given group has the item with the given toolId and objectId.
Parameters
groupDomElement
toolId
objectId
Returns
Definition at line 2587 of file vabstractpattern.cpp.
References AttrObject, AttrTool, and VDomDocument::GetParametrUInt().
Referenced by getGroupsContainingItem(), useGroupColor(), useGroupLineType(), and useGroupLineWeight().
haveLiteChange
void VAbstractPattern::haveLiteChange () slot
haveLiteChange we have unsaved change.
Definition at line 1639 of file vabstractpattern.cpp.
References patternChanged().
Referenced by VPattern::parsePieceElement(), VPattern::ParseToolAlongLine(), VPattern::ParseToolArc(), VPattern::ParseToolArcWithLength(), VPattern::ParseToolBisector(), VPattern::ParseToolCurveIntersectAxis(), VPattern::ParseToolCutArc(), VPattern::ParseToolCutSpline(), VPattern::ParseToolCutSplinePath(), VPattern::ParseToolEllipticalArc(), VPattern::ParseToolEndLine(), VPattern::ParseToolLineIntersectAxis(), VPattern::ParseToolMove(), VPattern::ParseToolNormal(), VPattern::ParseToolPointFromCircleAndTangent(), VPattern::ParseToolPointOfContact(), VPattern::ParseToolPointOfIntersectionCircles(), VPattern::ParseToolRotation(), VPattern::ParseToolShoulderPoint(), VPattern::ParseToolSpline(), VPattern::ParseToolSplinePath(), and VAbstractTool::VAbstractTool().
IncrementReferens()
virtual void VAbstractPattern::IncrementReferens (quint32 id) const pure virtual
Implemented in VLitePattern, and VPattern.
Referenced by VToolLine::Create(), PointIntersectXYTool::Create(), VToolCurveIntersectAxis::Create(), VToolLineIntersectAxis::Create(), VToolEndLine::Create(), VToolHeight::Create(), VToolAlongLine::Create(), VToolPointOfIntersectionArcs::Create(), VToolCutSpline::Create(), VToolCutArc::Create(), VToolCutSplinePath::Create(), VToolPointFromArcAndTangent::Create(), VToolTriangle::Create(), IntersectCircleTangentTool::Create(), IntersectCirclesTool::Create(), VToolPointOfIntersectionCurves::Create(), VToolArc::Create(), VToolArcWithLength::Create(), VToolEllipticalArc::Create(), VToolRotation::Create(), VToolLineIntersect::Create(), VToolNormal::Create(), VToolBisector::Create(), VToolShoulderPoint::Create(), VToolPointOfContact::Create(), VToolMirrorByLine::Create(), VToolMirrorByAxis::Create(), VToolCubicBezier::Create(), VToolSpline::Create(), VToolCubicBezierPath::Create(), VToolSplinePath::Create(), VToolTrueDarts::Create(), VToolMove::Create(), VToolInternalPath::IncrementNodes(), VUndoCommand::IncrementReferences(), VAbstractNode::incrementReferens(), VToolInternalPath::incrementReferens(), UnionTool::incrementReferens(), PatternPieceTool::InitCSAPaths(), PatternPieceTool::initializeAnchorPoints(), PatternPieceTool::initializeNode(), and PatternPieceTool::InitInternalPaths().
InsertTag()
void VAbstractPattern::InsertTag (const QStringList & tags, const QDomElement & element) protected
Definition at line 1765 of file vabstractpattern.cpp.
References SetVersion().
Referenced by CheckTagExists().
IsFunction()
bool VAbstractPattern::IsFunction (const QString & token) const private
Definition at line 2112 of file vabstractpattern.cpp.
References builInFunctions.
Referenced by ListMeasurements().
isGroupEmpty()
bool VAbstractPattern::isGroupEmpty (quint32 id)
Returns true if the given group is empty.
Parameters
id
Returns
Definition at line 2805 of file vabstractpattern.cpp.
References VDomDocument::elementById(), and TagGroup.
Referenced by GroupsWidget::fillTable(), and GroupTableWidgetItem::operator<().
IsModified()
bool VAbstractPattern::IsModified () const
Definition at line 2168 of file vabstractpattern.cpp.
References modified.
Referenced by MainWindow::patternChangesWereSaved(), and MainWindow::SaveAs().
IsPostfixOperator()
bool VAbstractPattern::IsPostfixOperator (const QString & token) const private
Definition at line 2098 of file vabstractpattern.cpp.
References builInPostfixOperators.
Referenced by ListMeasurements().
IsVariable()
bool VAbstractPattern::IsVariable (const QString & token) const private
Definition at line 2077 of file vabstractpattern.cpp.
References builInVariables, currentLength, and currentSeamAllowance.
Referenced by ListMeasurements().
ListArcExpressions()
QVector< VFormulaField > VAbstractPattern::ListArcExpressions () const private
Definition at line 1871 of file vabstractpattern.cpp.
References AttrAngle1, AttrAngle2, AttrLength, AttrRadius, LAST_ONE_DO_NOT_USE, anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute(), and TagArc.
Referenced by ListExpressions().
ListElArcExpressions()
QVector< VFormulaField > VAbstractPattern::ListElArcExpressions () const private
Definition at line 1895 of file vabstractpattern.cpp.
References AttrAngle1, AttrAngle2, AttrRadius1, AttrRadius2, AttrRotationAngle, LAST_ONE_DO_NOT_USE, anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute(), and TagElArc.
Referenced by ListExpressions().
ListExpressions()
QVector< VFormulaField > VAbstractPattern::ListExpressions () const
Definition at line 1825 of file vabstractpattern.cpp.
References ListArcExpressions(), ListElArcExpressions(), ListIncrementExpressions(), ListOperationExpressions(), ListPathExpressions(), ListPieceExpressions(), ListPointExpressions(), and ListSplineExpressions().
Referenced by ListMeasurements(), DialogVariables::refreshPattern(), and DialogVariables::variableUsed().
ListGrainlineExpressions()
QVector< VFormulaField > VAbstractPattern::ListGrainlineExpressions (const QDomElement & element) const private
Definition at line 2035 of file vabstractpattern.cpp.
References AttrLength, AttrRotation, and anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute().
Referenced by ListPieceExpressions().
ListIncrementExpressions()
QVector< VFormulaField > VAbstractPattern::ListIncrementExpressions () const
Definition at line 1951 of file vabstractpattern.cpp.
References IncrementFormula, anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute(), and TagIncrement.
Referenced by ListExpressions(), and DialogVariables::saveCustomVariableName().
ListIncrements()
QStringList VAbstractPattern::ListIncrements () const private
Definition at line 1803 of file vabstractpattern.cpp.
References VDomDocument::GetParametrString(), IncrementName, and TagIncrement.
Referenced by ListMeasurements().
ListMeasurements()
QStringList VAbstractPattern::ListMeasurements () const
Definition at line 273 of file vabstractpattern.cpp.
References IsFunction(), IsPostfixOperator(), IsVariable(), ListExpressions(), and ListIncrements().
Referenced by MainWindow::CheckRequiredMeasurements(), and MainWindow::UnloadMeasurements().
ListNodesExpressions()
QVector< VFormulaField > VAbstractPattern::ListNodesExpressions (const QDomElement & nodes) const private
Definition at line 1988 of file vabstractpattern.cpp.
References AttrSAAfter, AttrSABefore, LAST_ONE_DO_NOT_USE, anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute(), and TagNode.
Referenced by ListPathExpressions(), and ListPieceExpressions().
ListOperationExpressions()
QVector< VFormulaField > VAbstractPattern::ListOperationExpressions () const private
Definition at line 1966 of file vabstractpattern.cpp.
References AttrAngle, AttrLength, LAST_ONE_DO_NOT_USE, anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute(), and TagOperation.
Referenced by ListExpressions().
ListPathExpressions()
QVector< VFormulaField > VAbstractPattern::ListPathExpressions () const private
Definition at line 2011 of file vabstractpattern.cpp.
References LAST_ONE_DO_NOT_USE, ListNodesExpressions(), TagNodes, and TagPath.
Referenced by ListExpressions().
ListPathPointExpressions()
QVector< VFormulaField > VAbstractPattern::ListPathPointExpressions () const private
Definition at line 1928 of file vabstractpattern.cpp.
References AttrAngle, AttrKAsm1, AttrKAsm2, AttrPathPoint, LAST_ONE_DO_NOT_USE, and anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute().
Referenced by ListSplineExpressions().
ListPieceExpressions()
QVector< VFormulaField > VAbstractPattern::ListPieceExpressions () const private
Definition at line 2049 of file vabstractpattern.cpp.
References AttrWidth, LAST_ONE_DO_NOT_USE, ListGrainlineExpressions(), ListNodesExpressions(), anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute(), TagGrainline, TagNodes, and TagPiece.
Referenced by ListExpressions().
ListPointExpressions()
QVector< VFormulaField > VAbstractPattern::ListPointExpressions () const private
Definition at line 1845 of file vabstractpattern.cpp.
References AttrAngle, AttrC1Radius, AttrC2Radius, AttrCRadius, AttrLength, AttrRadius, LAST_ONE_DO_NOT_USE, anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute(), and TagPoint.
Referenced by ListExpressions().
ListSplineExpressions()
QVector< VFormulaField > VAbstractPattern::ListSplineExpressions () const private
Definition at line 1920 of file vabstractpattern.cpp.
References ListPathPointExpressions().
Referenced by ListExpressions().
LiteParseTree
virtual void VAbstractPattern::LiteParseTree (const Document & parse) pure virtual slot
Referenced by AnchorPointTool::AddToFile(), VToolInternalPath::AddToFile(), VToolSpline::ControlPointChangePosition(), VToolSplinePath::ControlPointChangePosition(), PatternPieceTool::insertNodes(), VToolBasePoint::itemChange(), VToolSpline::mouseMoveEvent(), VToolSplinePath::mouseMoveEvent(), PatternPieceTool::renamePiece(), VDrawTool::SaveDialogChange(), PatternPieceTool::SaveDialogChange(), PatternPieceTool::SaveMoveGrainline(), PatternPieceTool::SaveMovePattern(), PatternPieceTool::saveMovePiece(), VDrawTool::SaveOption(), PatternPieceTool::savePieceRotation(), PatternPieceTool::SaveResizeGrainline(), PatternPieceTool::SaveResizePattern(), PatternPieceTool::saveResizePiece(), PatternPieceTool::SaveRotateGrainline(), PatternPieceTool::SaveRotationPattern(), PatternPieceTool::toggleFlipping(), PatternPieceTool::toggleGrainline(), PatternPieceTool::togglePatternLabel(), PatternPieceTool::togglePieceLabel(), PatternPieceTool::toggleSeamAllowance(), PatternPieceTool::toggleSeamLine(), and VAbstractTool::VAbstractTool().
MPath()
QString VAbstractPattern::MPath () const
Definition at line 881 of file vabstractpattern.cpp.
References TagMeasurements, and VDomDocument::UniqueTagText().
Referenced by MainWindow::ChangedHeight(), MainWindow::ChangedSize(), MainWindow::Clear(), MainWindow::GetMeasurementFileName(), EditLabelTemplateDialog::InitPlaceholders(), MainWindow::LoadIndividual(), MainWindow::LoadMultisize(), MainWindow::LoadPattern(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), MainWindow::SavePattern(), ShowInfoDialog::ShowInfoDialog(), MainWindow::ShowMeasurements(), MainWindow::SyncMeasurements(), and MainWindow::UnloadMeasurements().
NeedFullParsing
void VAbstractPattern::NeedFullParsing () slot
Definition at line 1645 of file vabstractpattern.cpp.
References UndoCommand().
Referenced by VDrawTool::AddToCalculation(), VToolBasePoint::AddToFile(), PatternPieceTool::AddToFile(), VAbstractTool::deleteTool(), VToolBasePoint::deleteTool(), and PatternPieceTool::deleteTool().
parseGroups()
void VAbstractPattern::parseGroups (const QDomElement & domElement)
Definition at line 445 of file vabstractpattern.cpp.
References VDomDocument::AttrId, VDomDocument::GetParametrUInt(), VDataTool::GroupVisibility(), NULL_ID_STR, parseItemElement(), TagGroup, tools, and VContainer::UpdateId().
Referenced by addGroupItem(), addToolToGroup(), VPattern::parseDraftBlockElement(), AddGroupItem::redo(), AddGroup::redo(), DelGroup::redo(), MoveGroupItem::redo(), RemoveGroupItem::redo(), removeGroupItem(), setGroupLock(), setGroupVisibility(), AddGroupItem::undo(), AddGroup::undo(), DelGroup::undo(), MoveGroupItem::undo(), and RemoveGroupItem::undo().
parseItemElement()
QPair< bool, QMap< quint32, quint32 > > VAbstractPattern::parseItemElement (const QDomElement & domElement)
Definition at line 2126 of file vabstractpattern.cpp.
References VException::AddMoreInformation(), AttrObject, AttrTool, AttrVisible, VExceptionBadId::ErrorMessage(), VDomDocument::getParameterBool(), VDomDocument::GetParametrUInt(), NULL_ID_STR, TagGroupItem, and trueStr.
Referenced by GroupsWidget::fillGroupItemList(), and parseGroups().
ParseItemElement()
QPair<bool, QMap<quint32, quint32> > VAbstractPattern::ParseItemElement (const QDomElement & domElement) private
ParsePathNodes()
VPiecePath VAbstractPattern::ParsePathNodes (const QDomElement & domElement) static protected
Definition at line 1678 of file vabstractpattern.cpp.
References VPiecePath::Append(), VPiecePath::at(), ParseSANode(), and TagNode.
Referenced by VPattern::ParsePathElement().
ParsePieceAnchors()
QVector< quint32 > VAbstractPattern::ParsePieceAnchors (const QDomElement & domElement) static
Definition at line 735 of file vabstractpattern.cpp.
References NULL_ID.
Referenced by QT_WARNING_POP::GetPiece2Anchors(), and VPattern::parsePieceElement().
ParsePieceCSARecords()
QVector< CustomSARecord > VAbstractPattern::ParsePieceCSARecords (const QDomElement & domElement) static
Definition at line 691 of file vabstractpattern.cpp.
References AttrEnd, AttrIncludeAs, AttrNodeReverse, AttrPath, AttrStart, CustomSARecord::endPoint, falseStr, VDomDocument::getParameterBool(), VDomDocument::GetParametrUInt(), CustomSARecord::includeType, NULL_ID_STR, CustomSARecord::path, CustomSARecord::reverse, and CustomSARecord::startPoint.
Referenced by QT_WARNING_POP::GetPiece2CSAPaths(), and VPattern::parsePieceElement().
ParsePieceInternalPaths()
QVector< quint32 > VAbstractPattern::ParsePieceInternalPaths (const QDomElement & domElement) static
Definition at line 715 of file vabstractpattern.cpp.
References AttrPath, VDomDocument::GetParametrUInt(), NULL_ID, and NULL_ID_STR.
Referenced by QT_WARNING_POP::GetPiece2InternalPaths(), and VPattern::parsePieceElement().
ParsePieceNodes()
VPiecePath VAbstractPattern::ParsePieceNodes (const QDomElement & domElement) static
Definition at line 675 of file vabstractpattern.cpp.
References VPiecePath::Append(), VPiecePath::at(), and ParseSANode().
Referenced by QT_WARNING_POP::GetPiecePath(), and VPattern::parsePieceElement().
ParseSANode()
VPieceNode VAbstractPattern::ParseSANode (const QDomElement & domElement) static protected
Definition at line 755 of file vabstractpattern.cpp.
References AttrAngle, AttrIdObject, AttrNodeExcluded, AttrNodeIsNotch, AttrNodeNotchAngle, AttrNodeNotchCount, AttrNodeNotchLength, AttrNodeNotchSubType, AttrNodeNotchType, AttrNodeNotchWidth, AttrNodeReverse, AttrNodeShowNotch, AttrNodeShowSecondNotch, AttrSAAfter, AttrSABefore, AttrType, currentSeamAllowance, falseStr, VDomDocument::getParameterBool(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), NodeArc, NodeArc, NodeElArc, NodeElArc, NodePoint, NodePoint, NodeSpline, NodeSpline, NodeSplinePath, NodeSplinePath, NULL_ID_STR, qApp, VPieceNode::setAfterSAFormula(), VPieceNode::SetAngleType(), VPieceNode::setBeforeSAFormula(), VPieceNode::SetExcluded(), VPieceNode::setNotch(), VPieceNode::setNotchAngle(), VPieceNode::setNotchCount(), VPieceNode::setNotchLength(), VPieceNode::setNotchSubType(), VPieceNode::setNotchType(), VPieceNode::setNotchWidth(), VPieceNode::setShowNotch(), VPieceNode::setShowSeamlineNotch(), stringToNotchSubType(), stringToNotchType(), strSlit, strStraightforward, and trueStr.
Referenced by ParsePathNodes(), and ParsePieceNodes().
patternChanged
void VAbstractPattern::patternChanged (bool saved) signal
patternChanged emit if we have unsaved change.
Referenced by VPattern::addEmptyCustomVariable(), VPattern::addEmptyCustomVariableAfter(), addGroupItem(), addGroupItems(), addToolToGroup(), DeleteImage(), haveLiteChange(), HistoryDialog::HistoryDialog(), MainWindow::MainWindow(), VPattern::MoveDownIncrement(), VPattern::MoveUpIncrement(), VPattern::removeCustomVariable(), removeGroupItem(), renameDraftBlock(), VPattern::replaceNameInFormula(), DialogPatternProperties::SaveDefValues(), DialogPatternProperties::SaveDescription(), DialogPatternProperties::SaveGradation(), DialogPatternProperties::SaveLabelData(), DialogPatternProperties::SaveReadOnlyState(), DialogPatternProperties::SaveTemplateData(), SetCompanyName(), SetCustomerName(), SetDescription(), SetGradationHeights(), SetGradationSizes(), setGroupColor(), setGroupLineType(), setGroupLineWeight(), setGroupLock(), setGroupName(), setGroupVisibility(), SetImage(), VPattern::setIncrementDescription(), VPattern::SetIncrementFormula(), VPattern::setIncrementName(), SetLabelDateFormat(), SetLabelTimeFormat(), SetMPath(), SetNotes(), setPatternLabelTemplate(), SetPatternName(), SetPatternNumber(), and SetVersion().
patternHasGroups
void VAbstractPattern::patternHasGroups (bool value) signal
Referenced by getGroupByName(), getGroups(), groupListByName(), and GroupsWidget::GroupsWidget().
removeGroupItem()
QDomElement VAbstractPattern::removeGroupItem (quint32 toolId, quint32 objectId, quint32 groupId)
Removes the item of given toolId and objectId from the group of given groupId.
Parameters
toolId
objectId
groupId
Definition at line 2738 of file vabstractpattern.cpp.
References AttrObject, AttrTool, createGroups(), VDomDocument::elementById(), getGroupLock(), VDomDocument::GetParametrUInt(), modified, parseGroups(), patternChanged(), TagGroup, and updateGroups().
Referenced by addToolToGroup(), VDrawTool::ContextMenu(), deleteToolFromGroup(), and GroupsWidget::groupItemContextMenu().
RemoveTool()
void VAbstractPattern::RemoveTool (quint32 id) static
Definition at line 669 of file vabstractpattern.cpp.
References tools.
Referenced by QT_WARNING_POP::createUnion().
renameDraftBlock()
bool VAbstractPattern::renameDraftBlock (const QString & oldName, const QString & newName)
renameDraftBlock change draft block name.
Parameters
oldName old draft block name.
newName new draft block name.
Returns
true if success.
Definition at line 540 of file vabstractpattern.cpp.
References activeDraftBlock, AttrName, draftBlockNameChanged(), draftBlockNameExists(), getDraftBlockElement(), and patternChanged().
Referenced by RenameDraftBlock::changeName().
selectedPiece
void VAbstractPattern::selectedPiece (quint32 id) slot
Definition at line 1663 of file vabstractpattern.cpp.
References showPiece().
Referenced by PatternPieceTool::mousePressEvent().
setActiveDraftBlock()
void VAbstractPattern::setActiveDraftBlock (const QString & name) protected
setActiveDraftBlock set current draft block.
Parameters
name draft block name.
Definition at line 1698 of file vabstractpattern.cpp.
References activeDraftBlock, and activeDraftBlockChanged().
Referenced by appendDraftBlock(), and VPattern::Parse().
SetChildTag()
void VAbstractPattern::SetChildTag (const QString & qsParent, const QString & qsChild, const QString & qsValue) protected
SetCompanyName()
void VAbstractPattern::SetCompanyName (const QString & qsName)
Definition at line 1390 of file vabstractpattern.cpp.
References CheckTagExists(), modified, patternChanged(), patternLabelWasChanged, VDomDocument::setTagText(), and TagCompanyName.
Referenced by DialogPatternProperties::SaveLabelData().
setCurrentDraftBlock
void VAbstractPattern::setCurrentDraftBlock (const QString & patterPiece) signal
Referenced by AddGroupItem::redo(), DelGroup::redo(), DelTool::redo(), MoveGroupItem::redo(), RemoveGroupItem::redo(), AddToCalc::RedoFullParsing(), AddGroupItem::undo(), AddGroup::undo(), AddToCalc::undo(), DelGroup::undo(), DelTool::undo(), MoveGroupItem::undo(), and RemoveGroupItem::undo().
setCursor()
void VAbstractPattern::setCursor (const quint32 & value)
Definition at line 607 of file vabstractpattern.cpp.
References ChangedCursor(), and cursor.
Referenced by HistoryDialog::cellClicked(), and AddToCalc::redo().
SetCustomerName()
void VAbstractPattern::SetCustomerName (const QString & qsName)
Definition at line 1422 of file vabstractpattern.cpp.
References CheckTagExists(), modified, patternChanged(), patternLabelWasChanged, VDomDocument::setTagText(), and TagCustomerName.
Referenced by DialogPatternProperties::SaveLabelData().
setDefaultPen()
void VAbstractPattern::setDefaultPen (Pen pen)
Definition at line 618 of file vabstractpattern.cpp.
References Pen::color, Pen::lineType, Pen::lineWeight, m_DefaultLineColor, m_DefaultLineType, and m_DefaultLineWeight.
Referenced by MainWindow::penChanged().
SetDescription()
void VAbstractPattern::SetDescription (const QString & text)
Definition at line 1344 of file vabstractpattern.cpp.
References CheckTagExists(), modified, patternChanged(), VDomDocument::setTagText(), and TagDescription.
Referenced by DialogPatternProperties::SaveDescription().
SetGradationHeights()
void VAbstractPattern::SetGradationHeights (const QMap< GHeights, bool > & options)
Definition at line 1048 of file vabstractpattern.cpp.
References ALL, AttrAll, AttrH104, AttrH110, AttrH116, AttrH122, AttrH128, AttrH134, AttrH140, AttrH146, AttrH152, AttrH158, AttrH164, AttrH170, AttrH176, AttrH182, AttrH188, AttrH194, AttrH200, AttrH50, AttrH56, AttrH62, AttrH68, AttrH74, AttrH80, AttrH86, AttrH92, AttrH98, CheckTagExists(), H104, H110, H116, H122, H128, H134, H140, H146, H152, H158, H164, H170, H176, H182, H188, H194, H200, H50, H56, H62, H68, H74, H80, H86, H92, H98, modified, patternChanged(), VDomDocument::SetAttribute(), TagGradation, TagHeights, and TagSizes.
Referenced by DialogPatternProperties::SaveGradation().
SetGradationSizes()
void VAbstractPattern::SetGradationSizes (const QMap< GSizes, bool > & options)
Definition at line 1242 of file vabstractpattern.cpp.
References ALL, AttrAll, AttrS22, AttrS24, AttrS26, AttrS28, AttrS30, AttrS32, AttrS34, AttrS36, AttrS38, AttrS40, AttrS42, AttrS44, AttrS46, AttrS48, AttrS50, AttrS52, AttrS54, AttrS56, AttrS58, AttrS60, AttrS62, AttrS64, AttrS66, AttrS68, AttrS70, AttrS72, CheckTagExists(), modified, patternChanged(), S22, S24, S26, S28, S30, S32, S34, S36, S38, S40, S42, S44, S46, S48, S50, S52, S54, S56, S58, S60, S62, S64, S66, S68, S70, S72, VDomDocument::SetAttribute(), TagGradation, TagHeights, and TagSizes.
Referenced by DialogPatternProperties::SaveGradation().
setGroupColor()
void VAbstractPattern::setGroupColor (quint32 id, QString color)
Definition at line 2927 of file vabstractpattern.cpp.
References AttrGroupColor, VDomDocument::elementById(), modified, patternChanged(), VDomDocument::SetAttribute(), and TagGroup.
Referenced by GroupsWidget::editGroup(), and GroupsWidget::groupContextMenu().
setGroupLineType()
void VAbstractPattern::setGroupLineType (quint32 id, QString type)
Definition at line 2967 of file vabstractpattern.cpp.
References AttrLineType, VDomDocument::elementById(), modified, patternChanged(), VDomDocument::SetAttribute(), and TagGroup.
Referenced by GroupsWidget::editGroup(), and GroupsWidget::groupContextMenu().
setGroupLineWeight()
void VAbstractPattern::setGroupLineWeight (quint32 id, QString weight)
Definition at line 3007 of file vabstractpattern.cpp.
References AttrLineWeight, VDomDocument::elementById(), modified, patternChanged(), VDomDocument::SetAttribute(), and TagGroup.
Referenced by GroupsWidget::editGroup(), and GroupsWidget::groupContextMenu().
setGroupLock()
void VAbstractPattern::setGroupLock (quint32 id, bool locked)
Definition at line 2880 of file vabstractpattern.cpp.
References AttrGroupLocked, createGroups(), VDomDocument::elementById(), modified, parseGroups(), patternChanged(), VDomDocument::SetAttribute(), and TagGroup.
Referenced by GroupsWidget::groupLockChanged(), GroupsWidget::lockAllGroups(), and GroupsWidget::unlockAllGroups().
setGroupName()
void VAbstractPattern::setGroupName (quint32 id, const QString & name)
Definition at line 2303 of file vabstractpattern.cpp.
References AttrName, createGroups(), VDomDocument::elementById(), modified, patternChanged(), and TagGroup.
Referenced by GroupsWidget::editGroup(), GroupsWidget::groupContextMenu(), and GroupsWidget::renameGroup().
setGroupVisibility()
void VAbstractPattern::setGroupVisibility (quint32 id, bool visible)
Definition at line 2836 of file vabstractpattern.cpp.
References AttrVisible, createGroups(), VDomDocument::elementById(), modified, parseGroups(), patternChanged(), VDomDocument::SetAttribute(), and TagGroup.
Referenced by GroupsWidget::setGroupVisibility().
setGuiEnabled
void VAbstractPattern::setGuiEnabled (bool enabled) signal
Referenced by VPattern::LiteParseIncrements(), VPattern::LiteParseTree(), and MainWindow::MainWindow().
SetImage()
void VAbstractPattern::SetImage (const QString & text, const QString & extension)
Definition at line 1554 of file vabstractpattern.cpp.
References AttrExtension, CheckTagExists(), modified, patternChanged(), VDomDocument::setTagText(), and TagImage.
Referenced by DialogPatternProperties::ChangeImage().
SetLabelDateFormat()
void VAbstractPattern::SetLabelDateFormat (const QString & format)
Definition at line 1447 of file vabstractpattern.cpp.
References AttrDateFormat, CheckTagExists(), modified, patternChanged(), patternLabelWasChanged, VDomDocument::SetAttribute(), and TagPatternLabel.
Referenced by DialogPatternProperties::SaveLabelData().
SetLabelTimeFormat()
void VAbstractPattern::SetLabelTimeFormat (const QString & format)
Definition at line 1472 of file vabstractpattern.cpp.
References AttrTimeFormat, CheckTagExists(), modified, patternChanged(), patternLabelWasChanged, VDomDocument::SetAttribute(), and TagPatternLabel.
Referenced by DialogPatternProperties::SaveLabelData().
SetModified()
void VAbstractPattern::SetModified (bool modified)
Definition at line 2174 of file vabstractpattern.cpp.
References modified.
Referenced by AddGroupItem::redo(), MoveGroupItem::redo(), RemoveGroupItem::redo(), MainWindow::SaveAs(), AddGroupItem::undo(), MoveGroupItem::undo(), and RemoveGroupItem::undo().
SetMPath()
void VAbstractPattern::SetMPath (const QString & path)
Definition at line 887 of file vabstractpattern.cpp.
References patternChanged(), patternLabelWasChanged, VDomDocument::setTagText(), and TagMeasurements.
Referenced by MainWindow::CheckPathToMeasurements(), MainWindow::LoadIndividual(), MainWindow::LoadMultisize(), MainWindow::LoadPattern(), MainWindow::SavePattern(), and MainWindow::UnloadMeasurements().
SetNotes()
void VAbstractPattern::SetNotes (const QString & text)
Definition at line 1359 of file vabstractpattern.cpp.
References CheckTagExists(), modified, patternChanged(), VDomDocument::setTagText(), and TagNotes.
Referenced by DialogPatternProperties::SaveDescription().
setPatternLabelTemplate()
void VAbstractPattern::setPatternLabelTemplate (const QVector< VLabelTemplateLine > & lines)
Definition at line 1482 of file vabstractpattern.cpp.
References CheckTagExists(), modified, patternChanged(), patternLabelLines, patternLabelWasChanged, VDomDocument::RemoveAllChildren(), VDomDocument::SetLabelTemplate(), and TagPatternLabel.
Referenced by DialogPatternProperties::SaveTemplateData().
SetPatternName()
void VAbstractPattern::SetPatternName (const QString & qsName)
Definition at line 1374 of file vabstractpattern.cpp.
References CheckTagExists(), modified, patternChanged(), patternLabelWasChanged, VDomDocument::setTagText(), and TagPatternName.
Referenced by DialogPatternProperties::SaveLabelData().
SetPatternNumber()
void VAbstractPattern::SetPatternNumber (const QString & qsNum)
Definition at line 1406 of file vabstractpattern.cpp.
References CheckTagExists(), modified, patternChanged(), patternLabelWasChanged, VDomDocument::setTagText(), and TagPatternNum.
Referenced by DialogPatternProperties::SaveLabelData().
SetPatternWasChanged()
void VAbstractPattern::SetPatternWasChanged (bool changed)
Definition at line 1511 of file vabstractpattern.cpp.
References patternLabelWasChanged.
Referenced by MainWindow::LoadMeasurements(), MainWindow::setCurrentFile(), MainWindowsNoGUI::SetSizeHeightForIndividualM(), VTextManager::Update(), and MainWindow::UpdateMeasurements().
SetVersion()
void VAbstractPattern::SetVersion ()
Definition at line 1579 of file vabstractpattern.cpp.
References patternChanged(), VPatternConverter::PatternMaxVerStr, VDomDocument::setTagText(), and VDomDocument::TagVersion.
Referenced by InsertTag().
showPiece
void VAbstractPattern::showPiece (quint32 id) signal
Referenced by MainWindow::InitDocksContain(), and selectedPiece().
ShowTool
void VAbstractPattern::ShowTool (quint32 id, bool enable) signal
ShowTool highlight tool.
Parameters
id tool id.
enable enable or disable highlight.
Referenced by HistoryDialog::HistoryDialog(), and VDrawTool::VDrawTool().
SiblingNodeId()
quint32 VAbstractPattern::SiblingNodeId (const quint32 & nodeId) const
Definition at line 901 of file vabstractpattern.cpp.
References getBlockHistory(), VToolRecord::getId(), VToolRecord::getTypeTool(), history, NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, NULL_ID, Piece, and Union.
Referenced by DelTool::DelTool().
ToolExists()
void VAbstractPattern::ToolExists (const quint32 & id) static protected
Definition at line 1669 of file vabstractpattern.cpp.
References tools.
Referenced by VPattern::DecrementReferens(), getTool(), VPattern::IncrementReferens(), VPattern::setCurrentData(), and VPattern::UpdateToolData().
UndoCommand
void VAbstractPattern::UndoCommand () signal
Referenced by MainWindow::MainWindow(), and NeedFullParsing().
updateGroups
void VAbstractPattern::updateGroups () signal
Referenced by addGroupItem(), addGroupItems(), addToolToGroup(), MainWindow::InitDocksContain(), and removeGroupItem().
UpdateInLayoutList
void VAbstractPattern::UpdateInLayoutList (quint32 id) signal
Referenced by MainWindow::InitDocksContain(), and updatePieceList().
UpdatePatternLabel
void VAbstractPattern::UpdatePatternLabel () signal
Referenced by DialogPatternProperties::Apply(), MainWindow::LoadMeasurements(), DialogPatternProperties::Ok(), PatternPieceTool::PatternPieceTool(), DialogPatternProperties::SaveLabelData(), MainWindow::SavePattern(), DialogPatternProperties::SaveTemplateData(), MainWindow::setCurrentFile(), MainWindowsNoGUI::SetSizeHeightForIndividualM(), MainWindow::UnloadMeasurements(), and MainWindow::UpdateMeasurements().
updatePieceList
void VAbstractPattern::updatePieceList (quint32 id) slot
Definition at line 1657 of file vabstractpattern.cpp.
References UpdateInLayoutList().
Referenced by PatternPieceTool::toggleInLayout(), and PatternPieceTool::togglePieceLock().
UpdateToolData()
virtual void VAbstractPattern::UpdateToolData (const quint32 & id, VContainer * data) pure virtual
Implemented in VLitePattern, and VPattern.
Referenced by VToolLine::Create(), PointIntersectXYTool::Create(), VToolCurveIntersectAxis::Create(), VToolLineIntersectAxis::Create(), VToolEndLine::Create(), VToolHeight::Create(), VToolAlongLine::Create(), VToolPointOfIntersectionArcs::Create(), VToolCutSpline::Create(), VToolCutArc::Create(), VToolCutSplinePath::Create(), VToolPointFromArcAndTangent::Create(), VToolTriangle::Create(), IntersectCircleTangentTool::Create(), IntersectCirclesTool::Create(), VToolPointOfIntersectionCurves::Create(), VToolArc::Create(), VToolArcWithLength::Create(), VToolEllipticalArc::Create(), VToolRotation::Create(), VToolLineIntersect::Create(), UnionTool::Create(), VToolNormal::Create(), VToolBisector::Create(), VToolShoulderPoint::Create(), VToolPointOfContact::Create(), VToolCubicBezier::Create(), VToolCubicBezierPath::Create(), VToolSpline::Create(), VToolSplinePath::Create(), VToolBasePoint::Create(), VToolTrueDarts::Create(), VToolInternalPath::Create(), VToolMove::Create(), AnchorPointTool::Create(), PatternPieceTool::Create(), VNodeArc::Create(), VNodeEllipticalArc::Create(), VNodeSpline::Create(), VNodeSplinePath::Create(), VNodePoint::Create(), and VAbstractMirror::createDestination().
useGroupColor()
QString VAbstractPattern::useGroupColor (quint32 toolId, QString color)
Definition at line 3034 of file vabstractpattern.cpp.
References ColorByGroup, getGroupByName(), getGroupColor(), getGroupIdByName(), getGroupsContainingItem(), and hasGroupItem().
Referenced by VAbstractSpline::paint(), VToolLinePoint::paint(), and VToolLine::paint().
useGroupLineType()
QString VAbstractPattern::useGroupLineType (quint32 toolId, QString type)
Definition at line 3058 of file vabstractpattern.cpp.
References getGroupByName(), getGroupIdByName(), getGroupLineType(), getGroupsContainingItem(), hasGroupItem(), and LineTypeByGroup.
Referenced by VAbstractSpline::paint(), VToolLinePoint::paint(), and VToolLine::paint().
useGroupLineWeight()
QString VAbstractPattern::useGroupLineWeight (quint32 toolId, QString weight)
Definition at line 3082 of file vabstractpattern.cpp.
References getGroupByName(), getGroupIdByName(), getGroupLineWeight(), getGroupsContainingItem(), hasGroupItem(), and LineWeightByGroup.
Referenced by VAbstractSpline::paint(), VToolLinePoint::paint(), and VToolLine::paint().
Member Data Documentation
activeDraftBlock
QString VAbstractPattern::activeDraftBlock protected
activeBlockName name current pattern peace.
Definition at line 473 of file vabstractpattern.h.
Referenced by changeActiveDraftBlock(), getActiveDraftBlockIndex(), getActiveDraftBlockName(), getActiveDraftElement(), VPattern::LiteParseTree(), VPattern::Parse(), VPattern::ParseToolBasePoint(), VPattern::PrepareForParse(), renameDraftBlock(), setActiveDraftBlock(), and VPattern::setCurrentData().
AttrAll
const QString VAbstractPattern::AttrAll = QStringLiteral("all") static
Definition at line 348 of file vabstractpattern.h.
Referenced by CheckTagExists(), GetGradationHeights(), GetGradationSizes(), SetGradationHeights(), and SetGradationSizes().
AttrAnnotation
const QString VAbstractPattern::AttrAnnotation = QStringLiteral("annotation") static
Definition at line 318 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::ParsePieceDataTag().
AttrArrows
const QString VAbstractPattern::AttrArrows = QStringLiteral("arrows") static
Definition at line 327 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddGrainline(), and VPattern::ParsePieceGrainline().
AttrCustom
const QString VAbstractPattern::AttrCustom = QStringLiteral("custom") static
Definition at line 404 of file vabstractpattern.h.
Referenced by VPattern::IsDefCustom(), and VPattern::SetDefCustom().
AttrDateFormat
const QString VAbstractPattern::AttrDateFormat = QStringLiteral("dateFormat") static
Definition at line 325 of file vabstractpattern.h.
Referenced by GetLabelDateFormat(), and SetLabelDateFormat().
AttrDefHeight
const QString VAbstractPattern::AttrDefHeight = QStringLiteral("defHeight") static
Definition at line 405 of file vabstractpattern.h.
Referenced by VPattern::GetDefCustomHeight(), VPattern::SetDefCustom(), and VPattern::SetDefCustomHeight().
AttrDefSize
const QString VAbstractPattern::AttrDefSize = QStringLiteral("defSize") static
Definition at line 406 of file vabstractpattern.h.
Referenced by VPattern::GetDefCustomSize(), and VPattern::SetDefCustomSize().
AttrEnd
const QString VAbstractPattern::AttrEnd = QStringLiteral("end") static
Definition at line 343 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddCSARecord(), and ParsePieceCSARecords().
AttrExtension
const QString VAbstractPattern::AttrExtension = QStringLiteral("extension") static
Definition at line 407 of file vabstractpattern.h.
Referenced by GetImageExtension(), and SetImage().
AttrFoldPosition
const QString VAbstractPattern::AttrFoldPosition = QStringLiteral("foldPosition") static
Definition at line 322 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::ParsePieceDataTag().
AttrGroupColor
const QString VAbstractPattern::AttrGroupColor = QStringLiteral("groupColor") static
Definition at line 313 of file vabstractpattern.h.
Referenced by createGroup(), getGroupColor(), getGroups(), and setGroupColor().
AttrGroupLocked
const QString VAbstractPattern::AttrGroupLocked = QStringLiteral("locked") static
Definition at line 312 of file vabstractpattern.h.
Referenced by addGroupItems(), createGroup(), getGroupLock(), getGroups(), and setGroupLock().
AttrH104
const QString VAbstractPattern::AttrH104 = QStringLiteral("h104") static
Definition at line 359 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH110
const QString VAbstractPattern::AttrH110 = QStringLiteral("h110") static
Definition at line 360 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH116
const QString VAbstractPattern::AttrH116 = QStringLiteral("h116") static
Definition at line 361 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH122
const QString VAbstractPattern::AttrH122 = QStringLiteral("h122") static
Definition at line 362 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH128
const QString VAbstractPattern::AttrH128 = QStringLiteral("h128") static
Definition at line 363 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH134
const QString VAbstractPattern::AttrH134 = QStringLiteral("h134") static
Definition at line 364 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH140
const QString VAbstractPattern::AttrH140 = QStringLiteral("h140") static
Definition at line 365 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH146
const QString VAbstractPattern::AttrH146 = QStringLiteral("h146") static
Definition at line 366 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH152
const QString VAbstractPattern::AttrH152 = QStringLiteral("h152") static
Definition at line 367 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH158
const QString VAbstractPattern::AttrH158 = QStringLiteral("h158") static
Definition at line 368 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH164
const QString VAbstractPattern::AttrH164 = QStringLiteral("h164") static
Definition at line 369 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH170
const QString VAbstractPattern::AttrH170 = QStringLiteral("h170") static
Definition at line 370 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH176
const QString VAbstractPattern::AttrH176 = QStringLiteral("h176") static
Definition at line 371 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH182
const QString VAbstractPattern::AttrH182 = QStringLiteral("h182") static
Definition at line 372 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH188
const QString VAbstractPattern::AttrH188 = QStringLiteral("h188") static
Definition at line 373 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH194
const QString VAbstractPattern::AttrH194 = QStringLiteral("h194") static
Definition at line 374 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH200
const QString VAbstractPattern::AttrH200 = QStringLiteral("h200") static
Definition at line 375 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH50
const QString VAbstractPattern::AttrH50 = QStringLiteral("h50") static
Definition at line 350 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH56
const QString VAbstractPattern::AttrH56 = QStringLiteral("h56") static
Definition at line 351 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH62
const QString VAbstractPattern::AttrH62 = QStringLiteral("h62") static
Definition at line 352 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH68
const QString VAbstractPattern::AttrH68 = QStringLiteral("h68") static
Definition at line 353 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH74
const QString VAbstractPattern::AttrH74 = QStringLiteral("h74") static
Definition at line 354 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH80
const QString VAbstractPattern::AttrH80 = QStringLiteral("h80") static
Definition at line 355 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH86
const QString VAbstractPattern::AttrH86 = QStringLiteral("h86") static
Definition at line 356 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH92
const QString VAbstractPattern::AttrH92 = QStringLiteral("h92") static
Definition at line 357 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrH98
const QString VAbstractPattern::AttrH98 = QStringLiteral("h98") static
Definition at line 358 of file vabstractpattern.h.
Referenced by GetGradationHeights(), and SetGradationHeights().
AttrIncludeAs
const QString VAbstractPattern::AttrIncludeAs = QStringLiteral("includeAs") static
Definition at line 344 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddCSARecord(), and ParsePieceCSARecords().
AttrLetter
const QString VAbstractPattern::AttrLetter = QStringLiteral("letter") static
Definition at line 317 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::ParsePieceDataTag().
AttrName
const QString VAbstractPattern::AttrName = QStringLiteral("name") static
Definition at line 310 of file vabstractpattern.h.
Referenced by createGroup(), DeleteDraftBlock::DeleteDraftBlock(), draftBlockNameExists(), getActiveDraftBlockIndex(), getActiveDraftElement(), QT_WARNING_POP::getBlockName(), getDraftBlockElement(), getGroupByName(), getGroupIdByName(), getGroupName(), getGroups(), getGroupsContainingItem(), groupListByName(), VPattern::Parse(), VPattern::ParsePathElement(), VPattern::parsePieceElement(), VPattern::PointsCommonAttributes(), renameDraftBlock(), and setGroupName().
AttrNodeExcluded
const QString VAbstractPattern::AttrNodeExcluded = QStringLiteral("excluded") static
Definition at line 329 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeIsNotch
const QString VAbstractPattern::AttrNodeIsNotch = QStringLiteral("notch") static
Definition at line 330 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeNotchAngle
const QString VAbstractPattern::AttrNodeNotchAngle = QStringLiteral("notchAngle") static
Definition at line 337 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeNotchCount
const QString VAbstractPattern::AttrNodeNotchCount = QStringLiteral("notchCount") static
Definition at line 338 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeNotchLength
const QString VAbstractPattern::AttrNodeNotchLength = QStringLiteral("notchLength") static
Definition at line 335 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeNotchSubType
const QString VAbstractPattern::AttrNodeNotchSubType = QStringLiteral("notchSubtype") static
Definition at line 332 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeNotchType
const QString VAbstractPattern::AttrNodeNotchType = QStringLiteral("notchType") static
Definition at line 331 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeNotchWidth
const QString VAbstractPattern::AttrNodeNotchWidth = QStringLiteral("notchWidth") static
Definition at line 336 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeReverse
const QString VAbstractPattern::AttrNodeReverse = QStringLiteral("reverse") static
Definition at line 328 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddCSARecord(), VAbstractTool::AddSANode(), ParsePieceCSARecords(), VPattern::parsePieceNode(), and ParseSANode().
AttrNodeShowNotch
const QString VAbstractPattern::AttrNodeShowNotch = QStringLiteral("showNotch") static
Definition at line 333 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrNodeShowSecondNotch
const QString VAbstractPattern::AttrNodeShowSecondNotch = QStringLiteral("showSecondNotch") static
Definition at line 334 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), and ParseSANode().
AttrObject
const QString VAbstractPattern::AttrObject = QStringLiteral("object") static
Definition at line 314 of file vabstractpattern.h.
Referenced by addGroupItem(), addGroupItems(), createGroup(), hasGroupItem(), parseItemElement(), and removeGroupItem().
AttrOnFold
const QString VAbstractPattern::AttrOnFold = QStringLiteral("onFold") static
Definition at line 324 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::ParsePieceDataTag().
AttrOrientation
const QString VAbstractPattern::AttrOrientation = QStringLiteral("orientation") static
Definition at line 319 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::ParsePieceDataTag().
AttrPath
const QString VAbstractPattern::AttrPath = QStringLiteral("path") static
Definition at line 342 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddCSARecord(), PatternPieceTool::AddInternalPaths(), UnionTool::GetReferenceObjects(), ParsePieceCSARecords(), and ParsePieceInternalPaths().
AttrQuantity
const QString VAbstractPattern::AttrQuantity = QStringLiteral("quantity") static
Definition at line 323 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::ParsePieceDataTag().
AttrRotation
const QString VAbstractPattern::AttrRotation = QStringLiteral("rotation") static
Definition at line 346 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddGrainline(), PatternPieceTool::AddPatternInfo(), PatternPieceTool::AddPatternPieceData(), ListGrainlineExpressions(), VPattern::ParsePieceDataTag(), VPattern::ParsePieceGrainline(), and VPattern::ParsePiecePatternInfo().
AttrRotationWay
const QString VAbstractPattern::AttrRotationWay = QStringLiteral("rotationWay") static
Definition at line 320 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::ParsePieceDataTag().
AttrS22
const QString VAbstractPattern::AttrS22 = QStringLiteral("s22") static
Definition at line 377 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS24
const QString VAbstractPattern::AttrS24 = QStringLiteral("s24") static
Definition at line 378 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS26
const QString VAbstractPattern::AttrS26 = QStringLiteral("s26") static
Definition at line 379 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS28
const QString VAbstractPattern::AttrS28 = QStringLiteral("s28") static
Definition at line 380 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS30
const QString VAbstractPattern::AttrS30 = QStringLiteral("s30") static
Definition at line 381 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS32
const QString VAbstractPattern::AttrS32 = QStringLiteral("s32") static
Definition at line 382 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS34
const QString VAbstractPattern::AttrS34 = QStringLiteral("s34") static
Definition at line 383 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS36
const QString VAbstractPattern::AttrS36 = QStringLiteral("s36") static
Definition at line 384 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS38
const QString VAbstractPattern::AttrS38 = QStringLiteral("s38") static
Definition at line 385 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS40
const QString VAbstractPattern::AttrS40 = QStringLiteral("s40") static
Definition at line 386 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS42
const QString VAbstractPattern::AttrS42 = QStringLiteral("s42") static
Definition at line 387 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS44
const QString VAbstractPattern::AttrS44 = QStringLiteral("s44") static
Definition at line 388 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS46
const QString VAbstractPattern::AttrS46 = QStringLiteral("s46") static
Definition at line 389 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS48
const QString VAbstractPattern::AttrS48 = QStringLiteral("s48") static
Definition at line 390 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS50
const QString VAbstractPattern::AttrS50 = QStringLiteral("s50") static
Definition at line 391 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS52
const QString VAbstractPattern::AttrS52 = QStringLiteral("s52") static
Definition at line 392 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS54
const QString VAbstractPattern::AttrS54 = QStringLiteral("s54") static
Definition at line 393 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS56
const QString VAbstractPattern::AttrS56 = QStringLiteral("s56") static
Definition at line 394 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS58
const QString VAbstractPattern::AttrS58 = QStringLiteral("s58") static
Definition at line 395 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS60
const QString VAbstractPattern::AttrS60 = QStringLiteral("s60") static
Definition at line 396 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS62
const QString VAbstractPattern::AttrS62 = QStringLiteral("s62") static
Definition at line 397 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS64
const QString VAbstractPattern::AttrS64 = QStringLiteral("s64") static
Definition at line 398 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS66
const QString VAbstractPattern::AttrS66 = QStringLiteral("s66") static
Definition at line 399 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS68
const QString VAbstractPattern::AttrS68 = QStringLiteral("s68") static
Definition at line 400 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS70
const QString VAbstractPattern::AttrS70 = QStringLiteral("s70") static
Definition at line 401 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrS72
const QString VAbstractPattern::AttrS72 = QStringLiteral("s72") static
Definition at line 402 of file vabstractpattern.h.
Referenced by GetGradationSizes(), and SetGradationSizes().
AttrSAAfter
const QString VAbstractPattern::AttrSAAfter = QStringLiteral("after") static
Definition at line 340 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), ListNodesExpressions(), and ParseSANode().
AttrSABefore
const QString VAbstractPattern::AttrSABefore = QStringLiteral("before") static
Definition at line 339 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), ListNodesExpressions(), and ParseSANode().
AttrStart
const QString VAbstractPattern::AttrStart = QStringLiteral("start") static
Definition at line 341 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddCSARecord(), and ParsePieceCSARecords().
AttrTilt
const QString VAbstractPattern::AttrTilt = QStringLiteral("tilt") static
Definition at line 321 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::ParsePieceDataTag().
AttrTimeFormat
const QString VAbstractPattern::AttrTimeFormat = QStringLiteral("timeFormat") static
Definition at line 326 of file vabstractpattern.h.
Referenced by GetLabelTimeFormat(), and SetLabelTimeFormat().
AttrTool
const QString VAbstractPattern::AttrTool = QStringLiteral("tool") static
Definition at line 315 of file vabstractpattern.h.
Referenced by addGroupItem(), addGroupItems(), createGroup(), hasGroupItem(), parseItemElement(), and removeGroupItem().
AttrType
const QString VAbstractPattern::AttrType = QStringLiteral("type") static
Definition at line 316 of file vabstractpattern.h.
Referenced by VPattern::getActiveBasePoint(), VPattern::ParseDrawMode(), VPattern::ParsePathElement(), VPattern::parsePieceNode(), and ParseSANode().
AttrVisible
const QString VAbstractPattern::AttrVisible = QStringLiteral("visible") static
Definition at line 311 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddGrainline(), PatternPieceTool::AddPatternInfo(), PatternPieceTool::AddPatternPieceData(), createGroup(), getGroups(), getGroupVisibility(), parseItemElement(), VPattern::ParsePieceDataTag(), VPattern::ParsePieceGrainline(), VPattern::ParsePiecePatternInfo(), DelGroup::redo(), setGroupVisibility(), and AddGroup::undo().
AttrWidth
const QString VAbstractPattern::AttrWidth = QStringLiteral("width") static
Definition at line 345 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddAttributes(), PatternPieceTool::AddPatternInfo(), PatternPieceTool::AddPatternPieceData(), ListPieceExpressions(), VPattern::ParsePieceDataTag(), VPattern::parsePieceElement(), and VPattern::ParsePiecePatternInfo().
cursor
quint32 VAbstractPattern::cursor protected
cursor cursor keep id tool after which we will add new tool in file.
Definition at line 482 of file vabstractpattern.h.
Referenced by getCursor(), VPattern::PrepareForParse(), and setCursor().
history
QVector<VToolRecord> VAbstractPattern::history protected
history history records.
Definition at line 487 of file vabstractpattern.h.
Referenced by getBlockHistory(), getGroupObjHistory(), getHistory(), VPattern::PrepareForParse(), VPattern::setCurrentData(), and SiblingNodeId().
IncrementDescription
const QString VAbstractPattern::IncrementDescription = QStringLiteral("description") static
Definition at line 411 of file vabstractpattern.h.
Referenced by VPattern::MakeEmptyIncrement(), VPattern::ParseIncrementsElement(), and VPattern::setIncrementDescription().
IncrementFormula
const QString VAbstractPattern::IncrementFormula = QStringLiteral("formula") static
Definition at line 410 of file vabstractpattern.h.
Referenced by ListIncrementExpressions(), VPattern::MakeEmptyIncrement(), VPattern::ParseIncrementsElement(), and VPattern::SetIncrementFormula().
IncrementName
const QString VAbstractPattern::IncrementName = QStringLiteral("name") static
Definition at line 409 of file vabstractpattern.h.
Referenced by VPattern::FindIncrement(), ListIncrements(), VPattern::MakeEmptyIncrement(), VPattern::ParseIncrementsElement(), and VPattern::setIncrementName().
lastSavedExportFormat
QString VAbstractPattern::lastSavedExportFormat protected
Definition at line 479 of file vabstractpattern.h.
m_DefaultLineColor
QString VAbstractPattern::m_DefaultLineColor protected
Definition at line 475 of file vabstractpattern.h.
Referenced by getDefaultLineColor(), and setDefaultPen().
m_DefaultLineType
QString VAbstractPattern::m_DefaultLineType protected
Definition at line 477 of file vabstractpattern.h.
Referenced by getDefaultLineType(), and setDefaultPen().
m_DefaultLineWeight
qreal VAbstractPattern::m_DefaultLineWeight protected
Definition at line 476 of file vabstractpattern.h.
Referenced by getDefaultLineWeight(), and setDefaultPen().
modified
bool VAbstractPattern::modified mutable protected
modified keep state of the document for cases that do not cover QUndoStack
Definition at line 493 of file vabstractpattern.h.
Referenced by addGroupItem(), addGroupItems(), addToolToGroup(), DeleteImage(), IsModified(), VPattern::parsePieceElement(), VPattern::ParseToolAlongLine(), VPattern::ParseToolArc(), VPattern::ParseToolArcWithLength(), VPattern::ParseToolBisector(), VPattern::ParseToolCurveIntersectAxis(), VPattern::ParseToolCutArc(), VPattern::ParseToolCutSpline(), VPattern::ParseToolCutSplinePath(), VPattern::ParseToolEllipticalArc(), VPattern::ParseToolEndLine(), VPattern::ParseToolLineIntersectAxis(), VPattern::ParseToolMove(), VPattern::ParseToolNormal(), VPattern::ParseToolPointFromCircleAndTangent(), VPattern::ParseToolPointOfContact(), VPattern::ParseToolPointOfIntersectionCircles(), VPattern::ParseToolRotation(), VPattern::ParseToolShoulderPoint(), VPattern::ParseToolSpline(), VPattern::ParseToolSplinePath(), removeGroupItem(), VPattern::SaveDocument(), SetCompanyName(), SetCustomerName(), VPattern::SetDefCustom(), VPattern::SetDefCustomHeight(), VPattern::SetDefCustomSize(), SetDescription(), SetGradationHeights(), SetGradationSizes(), setGroupColor(), setGroupLineType(), setGroupLineWeight(), setGroupLock(), setGroupName(), setGroupVisibility(), SetImage(), SetLabelDateFormat(), SetLabelTimeFormat(), SetModified(), SetNotes(), setPatternLabelTemplate(), SetPatternName(), SetPatternNumber(), and VPattern::SetReadOnly().
NodeArc
const QString VAbstractPattern::NodeArc = QStringLiteral("NodeArc") static
Definition at line 413 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), VPattern::parsePieceNode(), and ParseSANode().
NodeElArc
const QString VAbstractPattern::NodeElArc = QStringLiteral("NodeElArc") static
Definition at line 414 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), VPattern::parsePieceNode(), and ParseSANode().
NodePoint
const QString VAbstractPattern::NodePoint = QStringLiteral("NodePoint") static
Definition at line 415 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), VPattern::parsePieceNode(), and ParseSANode().
NodeSpline
const QString VAbstractPattern::NodeSpline = QStringLiteral("NodeSpline") static
Definition at line 416 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), VPattern::parsePieceNode(), and ParseSANode().
NodeSplinePath
const QString VAbstractPattern::NodeSplinePath = QStringLiteral("NodeSplinePath") static
Definition at line 417 of file vabstractpattern.h.
Referenced by VAbstractTool::AddSANode(), VPattern::parsePieceNode(), and ParseSANode().
patternLabelLines
QVector< VLabelTemplateLine > VAbstractPattern::patternLabelLines = QVector<VLabelTemplateLine>() static protected
patternLabelLines list to speed up reading a template by many pieces.
Definition at line 498 of file vabstractpattern.h.
Referenced by getPatternLabelTemplate(), and setPatternLabelTemplate().
patternLabelWasChanged
bool VAbstractPattern::patternLabelWasChanged = false static protected
Definition at line 499 of file vabstractpattern.h.
Referenced by GetPatternWasChanged(), SetCompanyName(), SetCustomerName(), SetLabelDateFormat(), SetLabelTimeFormat(), SetMPath(), setPatternLabelTemplate(), SetPatternName(), SetPatternNumber(), and SetPatternWasChanged().
patternPieces
QStringList VAbstractPattern::patternPieces protected
patternPieces list of patern pieces names for combobox
Definition at line 490 of file vabstractpattern.h.
Referenced by getPatternPieces(), VPattern::Parse(), and VPattern::PrepareForParse().
TagArc
const QString VAbstractPattern::TagArc = QStringLiteral("arc") static
Definition at line 290 of file vabstractpattern.h.
Referenced by VToolArc::getTagName(), VToolArcWithLength::getTagName(), VNodeArc::getTagName(), ListArcExpressions(), and VPattern::ParseDrawMode().
TagCalculation
const QString VAbstractPattern::TagCalculation = QStringLiteral("calculation") static
Definition at line 274 of file vabstractpattern.h.
Referenced by VToolBasePoint::AddToFile(), VPattern::getActiveBasePoint(), VPattern::parseDraftBlockElement(), AddToCalc::redo(), and AddToCalc::undo().
TagCompanyName
const QString VAbstractPattern::TagCompanyName = QStringLiteral("company") static
Definition at line 301 of file vabstractpattern.h.
Referenced by CheckTagExists(), GetCompanyName(), VPattern::Parse(), and SetCompanyName().
TagCustomerName
const QString VAbstractPattern::TagCustomerName = QStringLiteral("customer") static
Definition at line 302 of file vabstractpattern.h.
Referenced by CheckTagExists(), GetCustomerName(), VPattern::Parse(), and SetCustomerName().
TagData
const QString VAbstractPattern::TagData = QStringLiteral("data") static
Definition at line 297 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternPieceData(), and VPattern::parsePieceElement().
TagDescription
const QString VAbstractPattern::TagDescription = QStringLiteral("description") static
Definition at line 278 of file vabstractpattern.h.
Referenced by CheckTagExists(), VPattern::CreateEmptyFile(), GetDescription(), VPattern::Parse(), and SetDescription().
TagDraftBlock
const QString VAbstractPattern::TagDraftBlock = QStringLiteral("draftBlock") static
Definition at line 284 of file vabstractpattern.h.
Referenced by VToolBasePoint::AddToFile(), DeleteDraftBlock::DeleteDraftBlock(), draftBlockCount(), draftBlockNameExists(), VPattern::GenerateLabel(), getActiveDraftBlockIndex(), getActiveDraftElement(), QT_WARNING_POP::getBlockName(), getDraftBlockElement(), VPattern::Parse(), and DeleteDraftBlock::undo().
TagElArc
const QString VAbstractPattern::TagElArc = QStringLiteral("elArc") static
Definition at line 291 of file vabstractpattern.h.
Referenced by VToolEllipticalArc::getTagName(), VNodeEllipticalArc::getTagName(), ListElArcExpressions(), and VPattern::ParseDrawMode().
TagGradation
const QString VAbstractPattern::TagGradation = QStringLiteral("gradation") static
Definition at line 294 of file vabstractpattern.h.
Referenced by CheckTagExists(), VPattern::GetDefCustomHeight(), VPattern::GetDefCustomSize(), GetGradationHeights(), GetGradationSizes(), VPattern::IsDefCustom(), VPattern::Parse(), VPattern::SetDefCustom(), VPattern::SetDefCustomHeight(), VPattern::SetDefCustomSize(), SetGradationHeights(), and SetGradationSizes().
TagGrainline
const QString VAbstractPattern::TagGrainline = QStringLiteral("grainline") static
Definition at line 304 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddGrainline(), ListPieceExpressions(), and VPattern::parsePieceElement().
TagGroup
const QString VAbstractPattern::TagGroup = QStringLiteral("group") static
Definition at line 286 of file vabstractpattern.h.
Referenced by addGroupItem(), createGroup(), getGroupByName(), getGroupColor(), getGroupIdByName(), getGroupLineType(), getGroupLineWeight(), getGroupLock(), getGroupName(), getGroups(), getGroupsContainingItem(), getGroupVisibility(), groupListByName(), isGroupEmpty(), parseGroups(), AddGroupItem::redo(), DelGroup::redo(), MoveGroupItem::redo(), RemoveGroupItem::redo(), removeGroupItem(), setGroupColor(), setGroupLineType(), setGroupLineWeight(), setGroupLock(), setGroupName(), setGroupVisibility(), AddGroupItem::undo(), AddGroup::undo(), MoveGroupItem::undo(), and RemoveGroupItem::undo().
TagGroupItem
const QString VAbstractPattern::TagGroupItem = QStringLiteral("item") static
Definition at line 287 of file vabstractpattern.h.
Referenced by addGroupItem(), addGroupItems(), createGroup(), and parseItemElement().
TagGroups
const QString VAbstractPattern::TagGroups = QStringLiteral("groups") static
Definition at line 285 of file vabstractpattern.h.
Referenced by createGroups(), and VPattern::parseDraftBlockElement().
TagHeights
const QString VAbstractPattern::TagHeights = QStringLiteral("heights") static
Definition at line 295 of file vabstractpattern.h.
Referenced by CheckTagExists(), GetGradationHeights(), GetGradationSizes(), SetGradationHeights(), and SetGradationSizes().
TagImage
const QString VAbstractPattern::TagImage = QStringLiteral("image") static
Definition at line 279 of file vabstractpattern.h.
Referenced by CheckTagExists(), DeleteImage(), GetImage(), GetImageExtension(), VPattern::Parse(), and SetImage().
TagIncrement
const QString VAbstractPattern::TagIncrement = QStringLiteral("increment") static
Definition at line 283 of file vabstractpattern.h.
Referenced by VPattern::FindIncrement(), ListIncrementExpressions(), ListIncrements(), VPattern::MakeEmptyIncrement(), VPattern::MoveDownIncrement(), VPattern::MoveUpIncrement(), and VPattern::ParseIncrementsElement().
TagIncrements
const QString VAbstractPattern::TagIncrements = QStringLiteral("increments") static
Definition at line 282 of file vabstractpattern.h.
Referenced by VPattern::addEmptyCustomVariable(), VPattern::addEmptyCustomVariableAfter(), VPattern::CreateEmptyFile(), VPattern::LiteParseIncrements(), VPattern::MoveDownIncrement(), VPattern::MoveUpIncrement(), VPattern::Parse(), and VPattern::removeCustomVariable().
TagLine
const QString VAbstractPattern::TagLine = QStringLiteral("line") static
Definition at line 308 of file vabstractpattern.h.
Referenced by VToolLine::getTagName(), GroupsWidget::itemDoubleClicked(), and VPattern::ParseDrawMode().
TagMeasurements
const QString VAbstractPattern::TagMeasurements = QStringLiteral("measurements") static
Definition at line 281 of file vabstractpattern.h.
Referenced by VPattern::CreateEmptyFile(), MPath(), VPattern::Parse(), and SetMPath().
TagModeling
const QString VAbstractPattern::TagModeling = QStringLiteral("modeling") static
Definition at line 275 of file vabstractpattern.h.
Referenced by VToolBasePoint::AddToFile(), UnionTool::AddToModeling(), VPattern::GarbageCollector(), AddDetNode::GetModelingSection(), VPattern::parseDraftBlockElement(), AddDetNode::redo(), and AddDetNode::undo().
TagNode
const QString VAbstractPattern::TagNode = QStringLiteral("node") static
Definition at line 307 of file vabstractpattern.h.
Referenced by VAbstractTool::AddNode(), ListNodesExpressions(), ParsePathNodes(), and VPattern::parsePieceNodes().
TagNodes
const QString VAbstractPattern::TagNodes = QStringLiteral("nodes") static
Definition at line 306 of file vabstractpattern.h.
Referenced by VAbstractTool::AddNodes(), QT_WARNING_POP::GetNodesChildren(), QT_WARNING_POP::GetPiecePath(), UnionTool::GetReferenceObjects(), ListPathExpressions(), ListPieceExpressions(), VPattern::ParsePathElement(), VPattern::parsePieceElement(), and QT_WARNING_POP::SaveNodesChildren().
TagNotes
const QString VAbstractPattern::TagNotes = QStringLiteral("notes") static
Definition at line 280 of file vabstractpattern.h.
Referenced by CheckTagExists(), VPattern::CreateEmptyFile(), GetNotes(), VPattern::Parse(), and SetNotes().
TagOperation
const QString VAbstractPattern::TagOperation = QStringLiteral("operation") static
Definition at line 293 of file vabstractpattern.h.
Referenced by VUndoCommand::getDestinationObject(), VAbstractOperation::getTagName(), ListOperationExpressions(), and VPattern::ParseDrawMode().
TagPath
const QString VAbstractPattern::TagPath = QStringLiteral("path") static
Definition at line 305 of file vabstractpattern.h.
Referenced by VToolInternalPath::getTagName(), ListPathExpressions(), VPattern::ParseDrawMode(), SavePiecePathOptions::redo(), and SavePiecePathOptions::undo().
TagPattern
const QString VAbstractPattern::TagPattern = QStringLiteral("pattern") static
Definition at line 273 of file vabstractpattern.h.
Referenced by VPattern::CreateEmptyFile().
TagPatternInfo
const QString VAbstractPattern::TagPatternInfo = QStringLiteral("patternInfo") static
Definition at line 298 of file vabstractpattern.h.
Referenced by PatternPieceTool::AddPatternInfo(), and VPattern::parsePieceElement().
TagPatternLabel
const QString VAbstractPattern::TagPatternLabel = QStringLiteral("patternLabel") static
Definition at line 303 of file vabstractpattern.h.
Referenced by CheckTagExists(), GetLabelDateFormat(), GetLabelTimeFormat(), getPatternLabelTemplate(), VPattern::Parse(), SetLabelDateFormat(), SetLabelTimeFormat(), and setPatternLabelTemplate().
TagPatternName
const QString VAbstractPattern::TagPatternName = QStringLiteral("patternName") static
Definition at line 299 of file vabstractpattern.h.
Referenced by CheckTagExists(), GetPatternName(), VPattern::Parse(), and SetPatternName().
TagPatternNum
const QString VAbstractPattern::TagPatternNum = QStringLiteral("patternNumber") static
Definition at line 300 of file vabstractpattern.h.
Referenced by CheckTagExists(), GetPatternNumber(), VPattern::Parse(), and SetPatternNumber().
TagPiece
const QString VAbstractPattern::TagPiece = QStringLiteral("piece") static
Definition at line 277 of file vabstractpattern.h.
Referenced by DeletePiece::DeletePiece(), TogglePieceLock::doCmd(), TogglePieceInLayout::doCmd(), SetPieceColor::doCmd(), VPattern::getActivePatternPieces(), QT_WARNING_POP::getBlockName(), PatternPieceTool::getTagName(), ListPieceExpressions(), MovePiece::MovePiece(), VPattern::parsePatternPieces(), DeletePiece::redo(), MovePiece::redo(), SavePieceOptions::redo(), AddPiece::undo(), MovePiece::undo(), and SavePieceOptions::undo().
TagPieces
const QString VAbstractPattern::TagPieces = QStringLiteral("pieces") static
Definition at line 276 of file vabstractpattern.h.
Referenced by VToolBasePoint::AddToFile(), VPattern::getActivePatternPieces(), AddPiece::getPiecesElement(), VPattern::parseDraftBlockElement(), AddPiece::redo(), and AddPiece::undo().
TagPoint
const QString VAbstractPattern::TagPoint = QStringLiteral("point") static
Definition at line 288 of file vabstractpattern.h.
Referenced by MoveDoubleLabel::Do(), MoveLabel::Do(), MoveSPoint::Do(), VPattern::getActiveBasePoint(), VAbstractPoint::getTagName(), AnchorPointTool::getTagName(), VNodePoint::getTagName(), ListPointExpressions(), MoveDoubleLabel::MoveDoubleLabel(), MoveLabel::MoveLabel(), MoveSPoint::MoveSPoint(), VPattern::ParseDrawMode(), ShowDoublePointName::setVisibility(), ShowPointName::setVisibility(), ShowDoublePointName::ShowDoublePointName(), and ShowPointName::ShowPointName().
TagSizes
const QString VAbstractPattern::TagSizes = QStringLiteral("sizes") static
Definition at line 296 of file vabstractpattern.h.
Referenced by CheckTagExists(), GetGradationHeights(), GetGradationSizes(), SetGradationHeights(), and SetGradationSizes().
TagSpline
const QString VAbstractPattern::TagSpline = QStringLiteral("spline") static
Definition at line 289 of file vabstractpattern.h.
Referenced by MoveSpline::Do(), MoveSplinePath::Do(), VAbstractSpline::getTagName(), VNodeSpline::getTagName(), VNodeSplinePath::getTagName(), and VPattern::ParseDrawMode().
TagTools
const QString VAbstractPattern::TagTools = QStringLiteral("tools") static
Definition at line 292 of file vabstractpattern.h.
Referenced by QT_WARNING_POP::GetChildren(), QT_WARNING_POP::GetPiece2Anchors(), QT_WARNING_POP::GetPiece2CSAPaths(), QT_WARNING_POP::GetPiece2InternalPaths(), QT_WARNING_POP::GetPiecePath(), QT_WARNING_POP::GetTagChildren(), UnionTool::getTagName(), and VPattern::ParseDrawMode().
tools
QHash< quint32, VDataTool * > VAbstractPattern::tools = QHash<quint32, VDataTool*>() static protected
tools list with pointer on tools.
Definition at line 496 of file vabstractpattern.h.
Referenced by AddTool(), VPattern::DecrementReferens(), getTool(), VPattern::IncrementReferens(), parseGroups(), VPattern::ParseToolsElement(), VPattern::PrepareForParse(), RemoveTool(), VPattern::setCurrentData(), VPattern::ToolBoundingRect(), ToolExists(), and VPattern::UpdateToolData().
toolsOnRemove
QVector<VDataTool*> VAbstractPattern::toolsOnRemove protected
Definition at line 484 of file vabstractpattern.h.
Referenced by AddToolOnRemove(), and VPattern::PrepareForParse().
The documentation for this class was generated from the following files:
src/libs/ifc/xml/vabstractpattern.h
src/libs/ifc/xml/vabstractpattern.cpp