Seamly2D: VToolSplinePath Class Reference
VToolSplinePath Class Reference
The VToolSplinePath class tool for creation spline path.
#include <vtoolsplinepath.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::SplinePath) }
Public Types inherited from VAbstractSpline
enum { Type = UserType + static_cast<int>(Tool::AbstractSpline) }
Public Slots
void ControlPointChangePosition (const qint32 &indexSpline, const SplinePointPosition &position, const QPointF &pos)
ControlPointChangePosition handle change position control point.
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
Public Slots inherited from VAbstractSpline
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void piecesMode (bool mode) Q_DECL_OVERRIDE
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
virtual QString makeToolTip () const Q_DECL_OVERRIDE
Public Slots inherited from VDrawTool
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Signals
void RefreshLine (const qint32 &indexSpline, SplinePointPosition pos, const QPointF &controlPoint, const QPointF &splinePoint)
RefreshLine refresh control line.
Signals inherited from VAbstractSpline
void setEnabledPoint (bool enable)
setEnabledPoint disable control points.
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Public Member Functions
virtual ~VToolSplinePath ()=default
virtual void setDialog () Q_DECL_OVERRIDE
setDialog set dialog when user want change tool option.
virtual int type () const Q_DECL_OVERRIDE
VSplinePath getSplinePath () const
void setSplinePath (const VSplinePath &splPath)
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractSpline
VAbstractSpline (VAbstractPattern *doc, VContainer *data, quint32 id, QGraphicsItem *parent=nullptr)
virtual ~VAbstractSpline () Q_DECL_EQ_DEFAULT
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) Q_DECL_OVERRIDE
virtual QString getTagName () const Q_DECL_OVERRIDE
void ShowHandles (bool show)
QString getLineColor () const
void setLineColor (const QString &value)
QString GetPenStyle () const
void SetPenStyle (const QString &value)
QString getLineWeight () const
getLineWeight return line weight of the spline
void setLineWeight (const QString &value)
setLineWeight set line weight of the spline
QString name () const
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual bool isPointNameVisible (quint32 id) const
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
virtual void setPointNamePosition (quint32 id, const QPointF &pos)
virtual void setPointNameVisiblity (quint32 id, bool visible)
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Static Public Member Functions
static VToolSplinePath * Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Create help create tool from GUI.
static VToolSplinePath * Create (const quint32 _id, VSplinePath *path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation)
Create help create tool.
static VToolSplinePath * Create (const quint32 _id, const QVector< quint32 > &points, QVector< QString > &a1, QVector< QString > &a2, QVector< QString > &l1, QVector< QString > &l2, const QString &color, const QString &penStyle, const QString &lineWeight, quint32 duplicate, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation)
static void UpdatePathPoints (VAbstractPattern *doc, QDomElement &element, const VSplinePath &path)
UpdatePathPoints update spline path in pattern file.
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString ToolType = QStringLiteral("pathInteractive")
static const QString OldToolType = QStringLiteral("path")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Slots
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID) Q_DECL_OVERRIDE
contextMenuEvent handle context menu events.
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Protected Member Functions
virtual void RemoveReferens () Q_DECL_OVERRIDE
RemoveReferens decrement value of reference.
virtual void SaveDialog (QDomElement &domElement) Q_DECL_OVERRIDE
SaveDialog save options into file after change in dialog.
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
mouseReleaseEvent handle mouse release events.
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
hoverEnterEvent handle hover enter events.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
hoverLeaveEvent handle hover leave events.
virtual void SetVisualization () Q_DECL_OVERRIDE
virtual void refreshCtrlPoints () Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractSpline
virtual void RefreshGeometry ()
RefreshGeometry refresh item on scene.
virtual void ShowTool (quint32 id, bool enable) Q_DECL_OVERRIDE
ShowTool highlight tool.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) Q_DECL_OVERRIDE
itemChange hadle item change.
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyReleaseEvent handle key release events.
virtual void ReadToolAttributes (const QDomElement &domElement) Q_DECL_OVERRIDE
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) Q_DECL_OVERRIDE
VSpline CorrectedSpline (const VSpline &spline, const SplinePointPosition &position, const QPointF &pos) const
template<typename T >
void ShowToolVisualization (bool show)
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialogChange () Q_DECL_FINAL
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
void SaveOption (QSharedPointer< VGObject > &obj)
virtual QString makeToolTip () const
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
virtual void updatePointNameVisibility (quint32 id, bool visible)
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
virtual void ToolCreation (const Source &typeCreation)
Private Member Functions
VToolSplinePath (VAbstractPattern *doc, VContainer *data, quint32 id, const Source &typeCreation, QGraphicsItem *parent=nullptr)
VToolSplinePath constructor.
bool IsMovable (int index) const
void UpdateControlPoints (const VSpline &spl, VSplinePath &splPath, const qint32 &indexSpline) const
UpdateControlPoints update position points control points in file.
void SetSplinePathAttributes (QDomElement &domElement, const VSplinePath &path)
Static Private Member Functions
static void AddPathPoint (VAbstractPattern *doc, QDomElement &domElement, const VSplinePoint &splPoint)
AddPathPoint write path point to pattern file.
Private Attributes
QPointF oldPosition
int splIndex
Additional Inherited Members
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Static Protected Member Functions inherited from VAbstractSpline
template<typename T >
static void InitSplineToolConnections (VMainGraphicsScene *scene, T *tool)
template<typename T >
static void InitSplinePathToolConnections (VMainGraphicsScene *scene, T *tool)
template<typename T >
static void InitArcToolConnections (VMainGraphicsScene *scene, T *tool)
template<typename T >
static void InitElArcToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VAbstractSpline
QVector< VControlPointSpline * > controlPoints
controlPoints list pointers of control points.
SceneObject sceneType
bool m_isHovered
bool m_piecesMode
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Detailed Description
The VToolSplinePath class tool for creation spline path.
Definition at line 75 of file vtoolsplinepath.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 95 of file vtoolsplinepath.h.
Constructor & Destructor Documentation
~VToolSplinePath()
virtual VToolSplinePath::~VToolSplinePath () virtual default
VToolSplinePath()
VToolSplinePath::VToolSplinePath (VAbstractPattern * doc, VContainer * data, quint32 id, const Source & typeCreation, QGraphicsItem * parent = nullptr) private
VToolSplinePath constructor.
Parameters
doc dom document container.
data container with variables.
id object id in container.
typeCreation way we create this tool.
parent parent object.
Definition at line 111 of file vtoolsplinepath.cpp.
References VAbstractSpline::contextMenuEvent(), ControlPointChangePosition(), VControlPointSpline::ControlPointChangePosition(), VAbstractSpline::controlPoints, VDataTool::data, FirstPoint, VContainer::GeometricObject(), VSpline::GetC1LengthFormula(), VSpline::GetC2LengthFormula(), VSpline::GetEndAngleFormula(), VSpline::GetP1(), VSpline::GetP2(), VSpline::GetP3(), VSpline::GetP4(), VSpline::GetStartAngleFormula(), qmu::QmuTokenParser::IsSingle(), LastPoint, VAbstractSpline::m_piecesMode, VAbstractSpline::sceneType, VAbstractSpline::setEnabledPoint(), VControlPointSpline::setEnabledPoint(), VControlPointSpline::showContextMenu(), VAbstractSpline::ShowHandles(), SplinePath, splPath, and VAbstractTool::ToolCreation().
Referenced by Create().
Member Function Documentation
AddPathPoint()
void VToolSplinePath::AddPathPoint (VAbstractPattern * doc, QDomElement & domElement, const VSplinePoint & splPoint) static private
AddPathPoint write path point to pattern file.
Parameters
domElement dom element.
splPoint spline path point.
Definition at line 419 of file vtoolsplinepath.cpp.
References VSplinePoint::Angle1Formula(), VSplinePoint::Angle2Formula(), AttrAngle, AttrAngle1, AttrAngle2, AttrKAsm1, AttrKAsm2, AttrLength1, AttrLength2, AttrPathPoint, AttrPSpline, VAbstractTool::doc, VGObject::id(), VSplinePoint::Length1Formula(), VSplinePoint::Length2Formula(), VSplinePoint::P(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by UpdatePathPoints().
ControlPointChangePosition
void VToolSplinePath::ControlPointChangePosition (const qint32 & indexSpline, const SplinePointPosition & position, const QPointF & pos) slot
ControlPointChangePosition handle change position control point.
Parameters
indexSpline position spline in spline list.
position position point in spline.
pos new position.
Definition at line 291 of file vtoolsplinepath.cpp.
References VAbstractSpline::CorrectedSpline(), VDataTool::data, VAbstractTool::doc, VContainer::GeometricObject(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, MoveSplinePath, VUndoCommand::NeedLiteParsing(), qApp, and UpdateControlPoints().
Referenced by VToolSplinePath().
Create() [1/3]
VToolSplinePath * VToolSplinePath::Create (const quint32 _id, const QVector< quint32 > & points, QVector< QString > & a1, QVector< QString > & a2, QVector< QString > & l1, QVector< QString > & l2, const QString & color, const QString & penStyle, const QString & lineWeight, quint32 duplicate, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation) static
Definition at line 250 of file vtoolsplinepath.cpp.
References VAbstractTool::CheckFormula(), Create(), VDataTool::data, VAbstractTool::doc, VContainer::GeometricObject(), and qApp.
Create() [2/3]
VToolSplinePath * VToolSplinePath::Create (const quint32 _id, VSplinePath * path, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation) static
Create help create tool.
Parameters
_id tool id, 0 if tool doesn't exist yet.
path spline path.
scene pointer to scene.
doc dom document container.
data container with variables.
parse parser file mode.
typeCreation way we create this tool.
Definition at line 216 of file vtoolsplinepath.cpp.
References VContainer::AddCurveWithSegments(), VContainer::AddGObject(), VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), VDataTool::data, VAbstractTool::doc, FromGui, FullParse, VContainer::GeometricObject(), VAbstractSpline::InitSplinePathToolConnections(), SplinePath, VContainer::UpdateGObject(), VAbstractPattern::UpdateToolData(), and VToolSplinePath().
Create() [3/3]
VToolSplinePath * VToolSplinePath::Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data) static
Create help create tool from GUI.
Parameters
dialog dialog.
scene pointer to scene.
doc dom document container.
data container with variables.
Definition at line 181 of file vtoolsplinepath.cpp.
References VDataTool::data, VAbstractTool::doc, FromGui, FullParse, VAbstractPattern::IncrementReferens(), VInteractiveTool::m_dialog, and SCASSERT.
Referenced by Create(), VPattern::ParseOldToolSplinePath(), and VPattern::ParseToolSplinePath().
EnableToolMove
void VToolSplinePath::EnableToolMove (bool move) virtual slot
Definition at line 305 of file vtoolsplinepath.cpp.
getSplinePath()
VSplinePath VToolSplinePath::getSplinePath () const
Definition at line 372 of file vtoolsplinepath.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractTool::m_id, and splPath.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolSplinePath().
hoverEnterEvent()
void VToolSplinePath::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected virtual
hoverEnterEvent handle hover enter events.
Parameters
event hover enter event.
Reimplemented from VAbstractSpline.
Definition at line 621 of file vtoolsplinepath.cpp.
References cursorArrowOpenHand, VDataTool::data, VContainer::GeometricObject(), VAbstractSpline::hoverEnterEvent(), IsMovable(), VAbstractTool::m_id, oldPosition, SetItemOverrideCursor(), splIndex, and splPath.
hoverLeaveEvent()
void VToolSplinePath::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected virtual
hoverLeaveEvent handle hover leave events.
Parameters
event hover leave event.
Reimplemented from VAbstractSpline.
Definition at line 638 of file vtoolsplinepath.cpp.
References VAbstractSpline::hoverLeaveEvent(), and oldPosition.
IsMovable()
bool VToolSplinePath::IsMovable (int index) const private
Definition at line 667 of file vtoolsplinepath.cpp.
References VDataTool::data, FirstPoint, VContainer::GeometricObject(), VSplinePoint::IsMovable(), LastPoint, VAbstractTool::m_id, and splPath.
Referenced by hoverEnterEvent(), mouseMoveEvent(), and mousePressEvent().
mouseMoveEvent()
void VToolSplinePath::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
Definition at line 539 of file vtoolsplinepath.cpp.
References VDataTool::data, VAbstractTool::doc, VContainer::GeometricObject(), VSpline::GetP1(), VSpline::GetP2(), VSpline::GetP3(), VSpline::GetP4(), VMainGraphicsScene::getScenePos(), IsMovable(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, MoveSplinePath, VUndoCommand::NeedLiteParsing(), oldPosition, VSpline::ParamT(), qApp, SCASSERT, splIndex, and UpdateControlPoints().
mousePressEvent()
void VToolSplinePath::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented from VAbstractSpline.
Definition at line 505 of file vtoolsplinepath.cpp.
References cursorArrowCloseHand, VDataTool::data, VContainer::GeometricObject(), IsMovable(), VAbstractTool::m_id, VAbstractSpline::mousePressEvent(), oldPosition, SetItemOverrideCursor(), splIndex, and splPath.
mouseReleaseEvent()
void VToolSplinePath::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
mouseReleaseEvent handle mouse release events.
Parameters
event mouse release event.
Reimplemented from VAbstractSpline.
Definition at line 525 of file vtoolsplinepath.cpp.
References cursorArrowOpenHand, VAbstractSpline::mouseReleaseEvent(), oldPosition, and SetItemOverrideCursor().
refreshCtrlPoints()
void VToolSplinePath::refreshCtrlPoints () protected virtual
Reimplemented from VAbstractSpline.
Definition at line 684 of file vtoolsplinepath.cpp.
References VAbstractSpline::controlPoints, VDataTool::data, FirstPoint, VContainer::GeometricObject(), qmu::QmuTokenParser::IsSingle(), LastPoint, VAbstractTool::m_id, and splPath.
RefreshLine
void VToolSplinePath::RefreshLine (const qint32 & indexSpline, SplinePointPosition pos, const QPointF & controlPoint, const QPointF & splinePoint) signal
RefreshLine refresh control line.
Parameters
indexSpline position spline in spline list.
pos position point in spline.
controlPoint new position control point.
splinePoint new position spline point.
RemoveReferens()
void VToolSplinePath::RemoveReferens () protected virtual
RemoveReferens decrement value of reference.
Reimplemented from VAbstractTool.
Definition at line 452 of file vtoolsplinepath.cpp.
References VDataTool::data, VAbstractPattern::DecrementReferens(), VAbstractTool::doc, VContainer::GeometricObject(), VAbstractTool::m_id, and splPath.
SaveDialog()
void VToolSplinePath::SaveDialog (QDomElement & domElement) protected virtual
SaveDialog save options into file after change in dialog.
Implements VDrawTool.
Definition at line 465 of file vtoolsplinepath.cpp.
References AttrColor, AttrLineWeight, AttrPenStyle, VAbstractSpline::controlPoints, VAbstractTool::doc, VSpline::GetP2(), VSpline::GetP3(), VInteractiveTool::m_dialog, SCASSERT, VDomDocument::SetAttribute(), SetSplinePathAttributes(), and splPath.
SaveOptions()
void VToolSplinePath::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VAbstractSpline.
Definition at line 494 of file vtoolsplinepath.cpp.
References VAbstractSpline::SaveOptions(), SCASSERT, SetSplinePathAttributes(), and splPath.
setDialog()
void VToolSplinePath::setDialog () virtual
setDialog set dialog when user want change tool option.
Reimplemented from VInteractiveTool.
Definition at line 161 of file vtoolsplinepath.cpp.
References VDataTool::data, VContainer::GeometricObject(), VInteractiveTool::m_dialog, VAbstractTool::m_id, SCASSERT, and splPath.
setSplinePath()
void VToolSplinePath::setSplinePath (const VSplinePath & splPath)
Definition at line 379 of file vtoolsplinepath.cpp.
References VDataTool::data, VContainer::GetGObject(), VAbstractTool::m_id, VDrawTool::SaveOption(), and splPath.
SetSplinePathAttributes()
void VToolSplinePath::SetSplinePathAttributes (QDomElement & domElement, const VSplinePath & path) private
Definition at line 331 of file vtoolsplinepath.cpp.
References AttrDuplicate, AttrKCurve, AttrType, VAbstractTool::doc, VAbstractCurve::GetDuplicate(), VDomDocument::SetAttribute(), ToolType, and UpdatePathPoints().
Referenced by SaveDialog(), and SaveOptions().
SetVisualization()
void VToolSplinePath::SetVisualization () protected virtual
Implements VAbstractTool.
Definition at line 650 of file vtoolsplinepath.cpp.
References VDataTool::data, VContainer::GeometricObject(), lineTypeToPenStyle(), VAbstractTool::m_id, VisToolSplinePath::RefreshGeometry(), SCASSERT, Visualization::setLineStyle(), Visualization::setLineWeight(), Visualization::SetMode(), VisToolSplinePath::setPath(), Show, splPath, and VAbstractTool::vis.
showContextMenu
void VToolSplinePath::showContextMenu (QGraphicsSceneContextMenuEvent * event, quint32 id = NULL_ID) protected virtual slot
contextMenuEvent handle context menu events.
Parameters
event context menu event.
Definition at line 398 of file vtoolsplinepath.cpp.
ShowVisualization()
void VToolSplinePath::ShowVisualization (bool show) virtual
Implements VAbstractTool.
Definition at line 388 of file vtoolsplinepath.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolSplinePath().
type()
virtual int VToolSplinePath::type () const inline virtual
Reimplemented from VAbstractSpline.
Definition at line 94 of file vtoolsplinepath.h.
References Type.
UpdateControlPoints()
void VToolSplinePath::UpdateControlPoints (const VSpline & spl, VSplinePath & splPath, const qint32 & indexSpline) const private
UpdateControlPoints update position points control points in file.
Parameters
spl spline what was changed.
splPath spline path.
indexSpline index spline in spline path.
Definition at line 317 of file vtoolsplinepath.cpp.
References FirstPoint, VSpline::GetC1Length(), VSpline::GetC1LengthFormula(), VSpline::GetC2Length(), VSpline::GetC2LengthFormula(), VSpline::GetEndAngle(), VSpline::GetEndAngleFormula(), VSpline::GetStartAngle(), VSpline::GetStartAngleFormula(), LastPoint, VSplinePoint::SetAngle1(), VSplinePoint::SetAngle2(), VSplinePoint::SetLength1(), VSplinePoint::SetLength2(), and splPath.
Referenced by ControlPointChangePosition(), and mouseMoveEvent().
UpdatePathPoints()
void VToolSplinePath::UpdatePathPoints (VAbstractPattern * doc, QDomElement & element, const VSplinePath & path) static
UpdatePathPoints update spline path in pattern file.
Parameters
doc dom document container.
element tag in file.
path spline path.
Definition at line 362 of file vtoolsplinepath.cpp.
References AddPathPoint(), VSplinePath::at(), VSplinePath::CountPoints(), VAbstractTool::doc, and VDomDocument::RemoveAllChildren().
Referenced by MoveSplinePath::Do(), and SetSplinePathAttributes().
Member Data Documentation
oldPosition
QPointF VToolSplinePath::oldPosition private
Definition at line 135 of file vtoolsplinepath.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
OldToolType
const QString VToolSplinePath::OldToolType = QStringLiteral("path") static
Definition at line 92 of file vtoolsplinepath.h.
Referenced by VPattern::ParseSplineElement().
splIndex
int VToolSplinePath::splIndex private
Definition at line 136 of file vtoolsplinepath.h.
Referenced by hoverEnterEvent(), mouseMoveEvent(), and mousePressEvent().
ToolType
const QString VToolSplinePath::ToolType = QStringLiteral("pathInteractive") static
Definition at line 91 of file vtoolsplinepath.h.
Referenced by VPattern::ParseSplineElement(), and SetSplinePathAttributes().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/toolcurve/vtoolsplinepath.h
src/libs/vtools/tools/drawTools/toolcurve/vtoolsplinepath.cpp