Seamly2D: DialogUndo Class Reference
DialogUndo Class Reference
#include <dialogundo.h>
Public Member Functions
DialogUndo (QWidget *parent=nullptr)
UndoButton Result () const
virtual ~DialogUndo () Q_DECL_OVERRIDE
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
Private Slots
void Cancel ()
Private Attributes
Ui::DialogUndo * ui
UndoButton result
Detailed Description
Definition at line 69 of file dialogundo.h.
Constructor & Destructor Documentation
DialogUndo()
DialogUndo::DialogUndo (QWidget * parent = nullptr) explicit
Definition at line 64 of file dialogundo.cpp.
References Cancel, Cancel(), qApp, and ui.
~DialogUndo()
DialogUndo::~DialogUndo () virtual
Definition at line 95 of file dialogundo.cpp.
References ui.
Member Function Documentation
Cancel
void DialogUndo::Cancel () private slot
Definition at line 101 of file dialogundo.cpp.
References Cancel, and result.
Referenced by closeEvent(), and DialogUndo().
closeEvent()
void DialogUndo::closeEvent (QCloseEvent * event) protected virtual
Definition at line 108 of file dialogundo.cpp.
References Cancel().
Result()
UndoButton DialogUndo::Result () const inline
Definition at line 86 of file dialogundo.h.
References result.
Member Data Documentation
result
UndoButton DialogUndo::result private
Definition at line 83 of file dialogundo.h.
Referenced by Cancel(), and Result().
ui
Ui::DialogUndo* DialogUndo::ui private
Definition at line 82 of file dialogundo.h.
Referenced by DialogUndo(), and ~DialogUndo().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/support/dialogundo.h
src/libs/vtools/dialogs/support/dialogundo.cpp