Seamly2D: QName Class Reference
QName Class Reference
#include <QName.hpp>
Public Member Functions
QName (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const XMLCh *const rawName, const unsigned int uriId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const QName &qname)
~QName ()
const XMLCh * getPrefix () const
XMLCh * getPrefix ()
const XMLCh * getLocalPart () const
XMLCh * getLocalPart ()
unsigned int getURI () const
const XMLCh * getRawName () const
XMLCh * getRawName ()
MemoryManager * getMemoryManager () const
void setName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId)
void setName (const XMLCh *const rawName, const unsigned int uriId)
void setPrefix (const XMLCh *)
void setLocalPart (const XMLCh *)
void setNPrefix (const XMLCh *, const XMLSize_t)
void setNLocalPart (const XMLCh *, const XMLSize_t)
void setURI (const unsigned int)
void setValues (const QName &qname)
bool operator== (const QName &) const
void cleanUp ()
QName (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const XMLCh *const rawName, const unsigned int uriId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const QName &qname)
~QName ()
const XMLCh * getPrefix () const
XMLCh * getPrefix ()
const XMLCh * getLocalPart () const
XMLCh * getLocalPart ()
unsigned int getURI () const
const XMLCh * getRawName () const
XMLCh * getRawName ()
MemoryManager * getMemoryManager () const
void setName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId)
void setName (const XMLCh *const rawName, const unsigned int uriId)
void setPrefix (const XMLCh *)
void setLocalPart (const XMLCh *)
void setNPrefix (const XMLCh *, const XMLSize_t)
void setNLocalPart (const XMLCh *, const XMLSize_t)
void setURI (const unsigned int)
void setValues (const QName &qname)
bool operator== (const QName &) const
void cleanUp ()
QName (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const XMLCh *const rawName, const unsigned int uriId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
QName (const QName &qname)
~QName ()
const XMLCh * getPrefix () const
XMLCh * getPrefix ()
const XMLCh * getLocalPart () const
XMLCh * getLocalPart ()
unsigned int getURI () const
const XMLCh * getRawName () const
XMLCh * getRawName ()
MemoryManager * getMemoryManager () const
void setName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId)
void setName (const XMLCh *const rawName, const unsigned int uriId)
void setPrefix (const XMLCh *)
void setLocalPart (const XMLCh *)
void setNPrefix (const XMLCh *, const XMLSize_t)
void setNLocalPart (const XMLCh *, const XMLSize_t)
void setURI (const unsigned int)
void setValues (const QName &qname)
bool operator== (const QName &) const
void cleanUp ()
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
QName & operator= (const QName &)
QName & operator= (const QName &)
QName & operator= (const QName &)
Private Attributes
XMLSize_t fPrefixBufSz
XMLSize_t fLocalPartBufSz
XMLSize_t fRawNameBufSz
unsigned int fURIId
XMLCh * fPrefix
XMLCh * fLocalPart
XMLCh * fRawName
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 34 of file QName.hpp.
Constructor & Destructor Documentation
QName() [1/12]
QName::QName (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Default constructor.
QName() [2/12]
QName::QName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a specified qname using prefix, and localpart.
QName() [3/12]
QName::QName (const XMLCh *const rawName, const unsigned int uriId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a specified qname using rawName.
QName() [4/12]
QName::QName (const QName & qname)
Copy constructor.
~QName() [1/3]
QName::~QName ()
QName() [5/12]
QName::QName (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Default constructor.
QName() [6/12]
QName::QName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a specified qname using prefix, and localpart.
QName() [7/12]
QName::QName (const XMLCh *const rawName, const unsigned int uriId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a specified qname using rawName.
QName() [8/12]
QName::QName (const QName & qname)
Copy constructor.
~QName() [2/3]
QName::~QName ()
QName() [9/12]
QName::QName (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Default constructor.
QName() [10/12]
QName::QName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a specified qname using prefix, and localpart.
QName() [11/12]
QName::QName (const XMLCh *const rawName, const unsigned int uriId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a specified qname using rawName.
QName() [12/12]
QName::QName (const QName & qname)
Copy constructor.
~QName() [3/3]
QName::~QName ()
Member Function Documentation
cleanUp() [1/3]
void QName::cleanUp ()
cleanUp() [2/3]
void QName::cleanUp ()
cleanUp() [3/3]
void QName::cleanUp ()
getLocalPart() [1/6]
XMLCh * QName::getLocalPart () inline
Definition at line 182 of file QName.hpp.
References fLocalPart.
getLocalPart() [2/6]
XMLCh* QName::getLocalPart ()
getLocalPart() [3/6]
XMLCh* QName::getLocalPart ()
getLocalPart() [4/6]
const XMLCh * QName::getLocalPart () const inline
Definition at line 177 of file QName.hpp.
References fLocalPart.
Referenced by ComplexTypeInfo::contains(), XMLElementDecl::getBaseName(), and XMLAttr::getName().
getLocalPart() [5/6]
const XMLCh* QName::getLocalPart () const
getLocalPart() [6/6]
const XMLCh* QName::getLocalPart () const
getMemoryManager() [1/3]
MemoryManager * QName::getMemoryManager () const inline
Definition at line 192 of file QName.hpp.
References fMemoryManager.
getMemoryManager() [2/3]
MemoryManager* QName::getMemoryManager () const
getMemoryManager() [3/3]
MemoryManager* QName::getMemoryManager () const
getPrefix() [1/6]
XMLCh * QName::getPrefix () inline
Definition at line 172 of file QName.hpp.
References fPrefix.
getPrefix() [2/6]
XMLCh* QName::getPrefix ()
getPrefix() [3/6]
XMLCh* QName::getPrefix ()
getPrefix() [4/6]
const XMLCh * QName::getPrefix () const inline
Definition at line 167 of file QName.hpp.
References fPrefix.
Referenced by XMLAttr::getPrefix().
getPrefix() [5/6]
const XMLCh* QName::getPrefix () const
getPrefix() [6/6]
const XMLCh* QName::getPrefix () const
getRawName() [1/6]
XMLCh* QName::getRawName ()
getRawName() [2/6]
XMLCh* QName::getRawName ()
getRawName() [3/6]
XMLCh* QName::getRawName ()
getRawName() [4/6]
const XMLCh* QName::getRawName () const
Referenced by XMLElementDecl::getFullName().
getRawName() [5/6]
const XMLCh* QName::getRawName () const
getRawName() [6/6]
const XMLCh* QName::getRawName () const
getURI() [1/3]
unsigned int QName::getURI () const inline
Definition at line 187 of file QName.hpp.
References fURIId.
Referenced by MixedContentModel::checkUniqueParticleAttribution(), TraverseSchema::copyWildCardData(), XMLElementDecl::getURI(), and XMLAttr::getURIId().
getURI() [2/3]
unsigned int QName::getURI () const
getURI() [3/3]
unsigned int QName::getURI () const
operator=() [1/3]
QName& QName::operator= (const QName &) private
operator=() [2/3]
QName& QName::operator= (const QName &) private
operator=() [3/3]
QName& QName::operator= (const QName &) private
operator==() [1/3]
bool QName::operator== (const QName &) const
operator==() [2/3]
bool QName::operator== (const QName &) const
operator==() [3/3]
bool QName::operator== (const QName &) const
setLocalPart() [1/3]
void QName::setLocalPart (const XMLCh * localPart) inline
Definition at line 210 of file QName.hpp.
References setNLocalPart(), and XMLString::stringLen().
setLocalPart() [2/3]
void QName::setLocalPart (const XMLCh *)
setLocalPart() [3/3]
void QName::setLocalPart (const XMLCh *)
setName() [1/6]
void QName::setName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId)
Referenced by XMLAttr::set().
setName() [2/6]
void QName::setName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId)
setName() [3/6]
void QName::setName (const XMLCh *const prefix, const XMLCh *const localPart, const unsigned int uriId)
setName() [4/6]
void QName::setName (const XMLCh *const rawName, const unsigned int uriId)
setName() [5/6]
void QName::setName (const XMLCh *const rawName, const unsigned int uriId)
setName() [6/6]
void QName::setName (const XMLCh *const rawName, const unsigned int uriId)
setNLocalPart() [1/3]
void QName::setNLocalPart (const XMLCh * , const XMLSize_t)
Referenced by setLocalPart().
setNLocalPart() [2/3]
void QName::setNLocalPart (const XMLCh * , const XMLSize_t)
setNLocalPart() [3/3]
void QName::setNLocalPart (const XMLCh * , const XMLSize_t)
setNPrefix() [1/3]
void QName::setNPrefix (const XMLCh * , const XMLSize_t)
Referenced by setPrefix().
setNPrefix() [2/3]
void QName::setNPrefix (const XMLCh * , const XMLSize_t)
setNPrefix() [3/3]
void QName::setNPrefix (const XMLCh * , const XMLSize_t)
setPrefix() [1/3]
void QName::setPrefix (const XMLCh * prefix) inline
Definition at line 205 of file QName.hpp.
References setNPrefix(), and XMLString::stringLen().
setPrefix() [2/3]
void QName::setPrefix (const XMLCh *)
setPrefix() [3/3]
void QName::setPrefix (const XMLCh *)
setURI() [1/3]
void QName::setURI (const unsigned int uriId) inline
Definition at line 200 of file QName.hpp.
References fURIId.
Referenced by MixedContentModel::checkUniqueParticleAttribution(), and TraverseSchema::copyWildCardData().
setURI() [2/3]
void QName::setURI (const unsigned int)
setURI() [3/3]
void QName::setURI (const unsigned int)
setValues() [1/3]
void QName::setValues (const QName & qname)
setValues() [2/3]
void QName::setValues (const QName & qname)
setValues() [3/3]
void QName::setValues (const QName & qname)
Member Data Documentation
fLocalPart
XMLCh * QName::fLocalPart private
Definition at line 159 of file QName.hpp.
Referenced by getLocalPart().
fLocalPartBufSz
XMLSize_t QName::fLocalPartBufSz private
Definition at line 155 of file QName.hpp.
fMemoryManager
MemoryManager * QName::fMemoryManager private
Definition at line 161 of file QName.hpp.
Referenced by getMemoryManager().
fPrefix
XMLCh * QName::fPrefix private
Definition at line 158 of file QName.hpp.
Referenced by getPrefix().
fPrefixBufSz
XMLSize_t QName::fPrefixBufSz private
Definition at line 154 of file QName.hpp.
fRawName
XMLCh * QName::fRawName private
Definition at line 160 of file QName.hpp.
fRawNameBufSz
XMLSize_t QName::fRawNameBufSz private
Definition at line 156 of file QName.hpp.
fURIId
unsigned int QName::fURIId private
Definition at line 157 of file QName.hpp.
Referenced by getURI(), and setURI().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/QName.hpp