Seamly2D: VPattern Class Reference
VPattern Class Reference
The VPattern class working with pattern file.
#include <vpattern.h>
Public Slots
virtual void LiteParseTree (const Document &parse) Q_DECL_OVERRIDE
LiteParseTree lite parse file.
Public Slots inherited from VAbstractPattern
virtual void LiteParseTree (const Document &parse)=0
void haveLiteChange ()
haveLiteChange we have unsaved change.
void NeedFullParsing ()
void ClearScene ()
void updatePieceList (quint32 id)
void selectedPiece (quint32 id)
Public Member Functions
VPattern (VContainer *data, Draw *mode, VMainGraphicsScene *draftScene, VMainGraphicsScene *pieceScene, QObject *parent=nullptr)
virtual void CreateEmptyFile () Q_DECL_OVERRIDE
CreateEmptyFile create minimal empty file.
void Parse (const Document &parse)
Parse parse file.
void setCurrentData ()
setCurrentData set current data set.
virtual void UpdateToolData (const quint32 &id, VContainer *data) Q_DECL_OVERRIDE
UpdateToolData update tool in list tools.
virtual void IncrementReferens (quint32 id) const Q_DECL_OVERRIDE
IncrementReferens increment reference parent objects.
virtual void DecrementReferens (quint32 id) const Q_DECL_OVERRIDE
DecrementReferens decrement reference parent objects.
quint32 getActiveBasePoint ()
getActiveBasePoint return id base point current draft block.
QVector< quint32 > getActivePatternPieces () const
virtual void setXMLContent (const QString &fileName) Q_DECL_OVERRIDE
virtual bool SaveDocument (const QString &fileName, QString &error) Q_DECL_OVERRIDE
QRectF ActiveDrawBoundingRect () const
void addEmptyCustomVariable (const QString &name)
void addEmptyCustomVariableAfter (const QString &after, const QString &name)
void removeCustomVariable (const QString &name)
void MoveUpIncrement (const QString &name)
void MoveDownIncrement (const QString &name)
void setIncrementName (const QString &name, const QString &text)
void SetIncrementFormula (const QString &name, const QString &text)
void setIncrementDescription (const QString &name, const QString &text)
void replaceNameInFormula (QVector< VFormulaField > &expressions, const QString &name, const QString &newName)
virtual QString GenerateLabel (const LabelType &type, const QString &reservedName=QString()) const Q_DECL_OVERRIDE
GenerateLabel create name for draft block basepoint.
virtual QString GenerateSuffix (const QString &type) const Q_DECL_OVERRIDE
bool IsDefCustom () const
void SetDefCustom (bool value)
int GetDefCustomHeight () const
void SetDefCustomHeight (int value)
int GetDefCustomSize () const
void SetDefCustomSize (int value)
bool isReadOnly () const
void SetReadOnly (bool rOnly)
void LiteParseIncrements ()
template<typename T >
QT_WARNING_POP QRectF ToolBoundingRect (const QRectF &rect, const quint32 &id) const
Public Member Functions inherited from VAbstractPattern
VAbstractPattern (QObject *parent=nullptr)
virtual ~VAbstractPattern () Q_DECL_EQ_DEFAULT
QStringList ListMeasurements () const
QVector< VFormulaField > ListExpressions () const
QVector< VFormulaField > ListIncrementExpressions () const
void changeActiveDraftBlock (const QString &name, const Document &parse=Document::FullParse)
changeActiveDraftBlock set new active draft block name.
QString getActiveDraftBlockName () const
getActiveDraftBlockName return current draft block name.
bool draftBlockNameExists (const QString &name) const
draftBlockNameExists check if draft block with this name exists.
int draftBlockCount () const
QDomElement getDraftBlockElement (const QString &name)
bool renameDraftBlock (const QString &oldName, const QString &newName)
renameDraftBlock change draft block name.
bool appendDraftBlock (const QString &name)
appendDraftBlock add new draft block.
bool getActiveNodeElement (const QString &name, QDomElement &element) const
getActiveNodeElement find element in current draft block by name.
quint32 getCursor () const
void setCursor (const quint32 &value)
void setDefaultPen (Pen pen)
QString getDefaultLineColor () const
qreal getDefaultLineWeight () const
QString getDefaultLineType () const
void AddToolOnRemove (VDataTool *tool)
QVector< VToolRecord > * getHistory ()
getHistory return list with list of history records.
QVector< VToolRecord > getBlockHistory () const
QMap< quint32, Tool > getGroupObjHistory () const
QString MPath () const
void SetMPath (const QString &path)
quint32 SiblingNodeId (const quint32 &nodeId) const
QStringList getPatternPieces () const
QMap< GHeights, bool > GetGradationHeights () const
void SetGradationHeights (const QMap< GHeights, bool > &options)
QMap< GSizes, bool > GetGradationSizes () const
void SetGradationSizes (const QMap< GSizes, bool > &options)
QString GetDescription () const
void SetDescription (const QString &text)
QString GetNotes () const
void SetNotes (const QString &text)
QString GetPatternName () const
void SetPatternName (const QString &qsName)
QString GetCompanyName () const
void SetCompanyName (const QString &qsName)
QString GetPatternNumber () const
void SetPatternNumber (const QString &qsNum)
QString GetCustomerName () const
void SetCustomerName (const QString &qsName)
QString GetLabelDateFormat () const
void SetLabelDateFormat (const QString &format)
QString GetLabelTimeFormat () const
void SetLabelTimeFormat (const QString &format)
void setPatternLabelTemplate (const QVector< VLabelTemplateLine > &lines)
QVector< VLabelTemplateLine > getPatternLabelTemplate () const
void SetPatternWasChanged (bool changed)
bool GetPatternWasChanged () const
QString GetImage () const
QString GetImageExtension () const
void SetImage (const QString &text, const QString &extension)
void DeleteImage ()
QString GetVersion () const
void setVersion ()
QVector< quint32 > getOpItems (const quint32 &toolId, const QString &itemType)
getOpItems get vector of operation tool obects.
QVector< quint32 > getDartItems (const quint32 &toolId)
bool IsModified () const
void SetModified (bool modified)
QDomElement getDraw (const QString &name) const
void parseGroups (const QDomElement &domElement)
QDomElement createGroups ()
QDomElement createGroup (quint32 id, const QString &name, const QString &color, const QString &type, const QString &weight, const QMap< quint32, quint32 > &groupData)
QDomElement addGroupItems (const QString &name, const QMap< quint32, quint32 > &groupData)
QString getGroupName (quint32 id)
void setGroupName (quint32 id, const QString &name)
QMap< quint32, GroupAttributes > getGroups ()
QStringList groupListByName ()
QDomElement getGroupByName (const QString &name)
quint32 getGroupIdByName (const QString &name)
QMap< quint32, QString > getGroupsContainingItem (quint32 toolId, quint32 objectId, bool containsItem)
Returns the groups that contain or do not contain the item identified by the toolid and the objectid.
void deleteToolFromGroup (quint32 toolId)
Deletes an item from the group containing the toolId.
void addToolToGroup (quint32 toolId, quint32 objectId, const QString &groupName)
Adds an item to the given group with the given toolId and objectId.
QDomElement addGroupItem (quint32 toolId, quint32 objectId, quint32 groupId)
Adds an item to the given group with the given toolId and objectId.
QDomElement removeGroupItem (quint32 toolId, quint32 objectId, quint32 groupId)
Removes the item of given toolId and objectId from the group of given groupId.
bool isGroupEmpty (quint32 id)
Returns true if the given group is empty.
bool getGroupVisibility (quint32 id)
void setGroupVisibility (quint32 id, bool visible)
bool getGroupLock (quint32 id)
void setGroupLock (quint32 id, bool locked)
QString getGroupColor (quint32 id)
void setGroupColor (quint32 id, QString color)
QString getGroupLineType (quint32 id)
void setGroupLineType (quint32 id, QString type)
QString getGroupLineWeight (quint32 id)
void setGroupLineWeight (quint32 id, QString weight)
bool groupNameExists (const QString &groupName)
QString useGroupColor (quint32 toolId, QString color)
QString useGroupLineType (quint32 toolId, QString type)
QString useGroupLineWeight (quint32 toolId, QString weight)
QPair< bool, QMap< quint32, quint32 > > parseItemElement (const QDomElement &domElement)
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit measurementUnits () const
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Static Public Attributes
static const QString AttrReadOnly = QStringLiteral("readOnly")
Static Public Attributes inherited from VAbstractPattern
static const QString TagPattern = QStringLiteral("pattern")
static const QString TagCalculation = QStringLiteral("calculation")
static const QString TagModeling = QStringLiteral("modeling")
static const QString TagPieces = QStringLiteral("pieces")
static const QString TagPiece = QStringLiteral("piece")
static const QString TagDescription = QStringLiteral("description")
static const QString TagImage = QStringLiteral("image")
static const QString TagNotes = QStringLiteral("notes")
static const QString TagMeasurements = QStringLiteral("measurements")
static const QString TagIncrements = QStringLiteral("increments")
static const QString TagIncrement = QStringLiteral("increment")
static const QString TagDraftBlock = QStringLiteral("draftBlock")
static const QString TagGroups = QStringLiteral("groups")
static const QString TagGroup = QStringLiteral("group")
static const QString TagGroupItem = QStringLiteral("item")
static const QString TagPoint = QStringLiteral("point")
static const QString TagSpline = QStringLiteral("spline")
static const QString TagArc = QStringLiteral("arc")
static const QString TagElArc = QStringLiteral("elArc")
static const QString TagTools = QStringLiteral("tools")
static const QString TagOperation = QStringLiteral("operation")
static const QString TagGradation = QStringLiteral("gradation")
static const QString TagHeights = QStringLiteral("heights")
static const QString TagSizes = QStringLiteral("sizes")
static const QString TagData = QStringLiteral("data")
static const QString TagPatternInfo = QStringLiteral("patternInfo")
static const QString TagPatternName = QStringLiteral("patternName")
static const QString TagPatternNum = QStringLiteral("patternNumber")
static const QString TagCompanyName = QStringLiteral("company")
static const QString TagCustomerName = QStringLiteral("customer")
static const QString TagPatternLabel = QStringLiteral("patternLabel")
static const QString TagGrainline = QStringLiteral("grainline")
static const QString TagPath = QStringLiteral("path")
static const QString TagNodes = QStringLiteral("nodes")
static const QString TagNode = QStringLiteral("node")
static const QString TagLine = QStringLiteral("line")
static const QString AttrName = QStringLiteral("name")
static const QString AttrVisible = QStringLiteral("visible")
static const QString AttrGroupLocked = QStringLiteral("locked")
static const QString AttrGroupColor = QStringLiteral("groupColor")
static const QString AttrObject = QStringLiteral("object")
static const QString AttrTool = QStringLiteral("tool")
static const QString AttrType = QStringLiteral("type")
static const QString AttrLetter = QStringLiteral("letter")
static const QString AttrAnnotation = QStringLiteral("annotation")
static const QString AttrOrientation = QStringLiteral("orientation")
static const QString AttrRotationWay = QStringLiteral("rotationWay")
static const QString AttrTilt = QStringLiteral("tilt")
static const QString AttrFoldPosition = QStringLiteral("foldPosition")
static const QString AttrQuantity = QStringLiteral("quantity")
static const QString AttrOnFold = QStringLiteral("onFold")
static const QString AttrDateFormat = QStringLiteral("dateFormat")
static const QString AttrTimeFormat = QStringLiteral("timeFormat")
static const QString AttrArrows = QStringLiteral("arrows")
static const QString AttrNodeReverse = QStringLiteral("reverse")
static const QString AttrNodeExcluded = QStringLiteral("excluded")
static const QString AttrNodeIsNotch = QStringLiteral("notch")
static const QString AttrNodeNotchType = QStringLiteral("notchType")
static const QString AttrNodeNotchSubType = QStringLiteral("notchSubtype")
static const QString AttrNodeShowNotch = QStringLiteral("showNotch")
static const QString AttrNodeShowSecondNotch = QStringLiteral("showSecondNotch")
static const QString AttrNodeNotchLength = QStringLiteral("notchLength")
static const QString AttrNodeNotchWidth = QStringLiteral("notchWidth")
static const QString AttrNodeNotchAngle = QStringLiteral("notchAngle")
static const QString AttrNodeNotchCount = QStringLiteral("notchCount")
static const QString AttrSABefore = QStringLiteral("before")
static const QString AttrSAAfter = QStringLiteral("after")
static const QString AttrStart = QStringLiteral("start")
static const QString AttrPath = QStringLiteral("path")
static const QString AttrEnd = QStringLiteral("end")
static const QString AttrIncludeAs = QStringLiteral("includeAs")
static const QString AttrWidth = QStringLiteral("width")
static const QString AttrRotation = QStringLiteral("rotation")
static const QString AttrAll = QStringLiteral("all")
static const QString AttrH50 = QStringLiteral("h50")
static const QString AttrH56 = QStringLiteral("h56")
static const QString AttrH62 = QStringLiteral("h62")
static const QString AttrH68 = QStringLiteral("h68")
static const QString AttrH74 = QStringLiteral("h74")
static const QString AttrH80 = QStringLiteral("h80")
static const QString AttrH86 = QStringLiteral("h86")
static const QString AttrH92 = QStringLiteral("h92")
static const QString AttrH98 = QStringLiteral("h98")
static const QString AttrH104 = QStringLiteral("h104")
static const QString AttrH110 = QStringLiteral("h110")
static const QString AttrH116 = QStringLiteral("h116")
static const QString AttrH122 = QStringLiteral("h122")
static const QString AttrH128 = QStringLiteral("h128")
static const QString AttrH134 = QStringLiteral("h134")
static const QString AttrH140 = QStringLiteral("h140")
static const QString AttrH146 = QStringLiteral("h146")
static const QString AttrH152 = QStringLiteral("h152")
static const QString AttrH158 = QStringLiteral("h158")
static const QString AttrH164 = QStringLiteral("h164")
static const QString AttrH170 = QStringLiteral("h170")
static const QString AttrH176 = QStringLiteral("h176")
static const QString AttrH182 = QStringLiteral("h182")
static const QString AttrH188 = QStringLiteral("h188")
static const QString AttrH194 = QStringLiteral("h194")
static const QString AttrH200 = QStringLiteral("h200")
static const QString AttrS22 = QStringLiteral("s22")
static const QString AttrS24 = QStringLiteral("s24")
static const QString AttrS26 = QStringLiteral("s26")
static const QString AttrS28 = QStringLiteral("s28")
static const QString AttrS30 = QStringLiteral("s30")
static const QString AttrS32 = QStringLiteral("s32")
static const QString AttrS34 = QStringLiteral("s34")
static const QString AttrS36 = QStringLiteral("s36")
static const QString AttrS38 = QStringLiteral("s38")
static const QString AttrS40 = QStringLiteral("s40")
static const QString AttrS42 = QStringLiteral("s42")
static const QString AttrS44 = QStringLiteral("s44")
static const QString AttrS46 = QStringLiteral("s46")
static const QString AttrS48 = QStringLiteral("s48")
static const QString AttrS50 = QStringLiteral("s50")
static const QString AttrS52 = QStringLiteral("s52")
static const QString AttrS54 = QStringLiteral("s54")
static const QString AttrS56 = QStringLiteral("s56")
static const QString AttrS58 = QStringLiteral("s58")
static const QString AttrS60 = QStringLiteral("s60")
static const QString AttrS62 = QStringLiteral("s62")
static const QString AttrS64 = QStringLiteral("s64")
static const QString AttrS66 = QStringLiteral("s66")
static const QString AttrS68 = QStringLiteral("s68")
static const QString AttrS70 = QStringLiteral("s70")
static const QString AttrS72 = QStringLiteral("s72")
static const QString AttrCustom = QStringLiteral("custom")
static const QString AttrDefHeight = QStringLiteral("defHeight")
static const QString AttrDefSize = QStringLiteral("defSize")
static const QString AttrExtension = QStringLiteral("extension")
static const QString IncrementName = QStringLiteral("name")
static const QString IncrementFormula = QStringLiteral("formula")
static const QString IncrementDescription = QStringLiteral("description")
static const QString NodeArc = QStringLiteral("NodeArc")
static const QString NodeElArc = QStringLiteral("NodeElArc")
static const QString NodePoint = QStringLiteral("NodePoint")
static const QString NodeSpline = QStringLiteral("NodeSpline")
static const QString NodeSplinePath = QStringLiteral("NodeSplinePath")
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Protected Member Functions
virtual void customEvent (QEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractPattern
void setActiveDraftBlock (const QString &name)
setActiveDraftBlock set current draft block.
QDomElement CheckTagExists (const QString &tag)
void InsertTag (const QStringList &tags, const QDomElement &element)
void SetChildTag (const QString &qsParent, const QString &qsChild, const QString &qsValue)
int getActiveDraftBlockIndex () const
bool getActiveDraftElement (QDomElement &element) const
getActiveDraftElement return draftBlock element for current draft block.
bool hasGroupItem (const QDomElement &domElement, quint32 toolId, quint32 objectId)
Checks if the given group has the item with the given toolId and objectId.
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Private Member Functions
VNodeDetail parsePieceNode (const QDomElement &domElement) const
void parseDraftBlockElement (const QDomNode &node, const Document &parse)
parseDraftBlockElement parse draw tag.
void ParseDrawMode (const QDomNode &node, const Document &parse, const Draw &mode)
ParseDrawMode parse draw tag with draw mode.
void parsePieceElement (QDomElement &domElement, const Document &parse)
parsePieceElement parse piece tag.
void parsePieceNodes (const QDomElement &domElement, VPiece &piece, qreal width, bool closed) const
void ParsePieceDataTag (const QDomElement &domElement, VPiece &piece) const
void ParsePiecePatternInfo (const QDomElement &domElement, VPiece &piece) const
void ParsePieceGrainline (const QDomElement &domElement, VPiece &piece) const
void parsePatternPieces (const QDomElement &domElement, const Document &parse)
parsePatternPieces parse pieces tag.
void ParsePointElement (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse, const QString &type)
ParsePointElement parse point tag.
void ParseLineElement (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
ParseLineElement parse line tag.
void ParseSplineElement (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse, const QString &type)
ParseSplineElement parse spline tag.
void ParseArcElement (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse, const QString &type)
ParseArcElement parse arc tag.
void ParseEllipticalArcElement (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse, const QString &type)
ParseEllipticalArcElement parse elliptical arc tag.
void ParseToolsElement (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse, const QString &type)
ParseToolsElement parse tools tag.
void ParseOperationElement (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse, const QString &type)
void ParsePathElement (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseIncrementsElement (const QDomNode &node)
ParseIncrementsElement parse increments tag.
void PrepareForParse (const Document &parse)
void ToolsCommonAttributes (const QDomElement &domElement, quint32 &id)
void PointsCommonAttributes (const QDomElement &domElement, quint32 &id, QString &name, qreal &mx, qreal &my, bool &labelVisible, QString &lineType, QString &lineWeight, QString &lineColor)
void PointsCommonAttributes (const QDomElement &domElement, quint32 &id, QString &name, qreal &mx, qreal &my, bool &labelVisible)
void PointsCommonAttributes (const QDomElement &domElement, quint32 &id, qreal &mx, qreal &my)
void SplinesCommonAttributes (const QDomElement &domElement, quint32 &id, quint32 &idObject, quint32 &idTool)
template<typename T >
QRectF ToolBoundingRect (const QRectF &rec, const quint32 &id) const
void parseCurrentDraftBlock ()
QString GetLabelBase (quint32 index) const
void ParseToolBasePoint (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolEndLine (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolAlongLine (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolShoulderPoint (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolNormal (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolBisector (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolLineIntersect (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolPointOfContact (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseNodePoint (const QDomElement &domElement, const Document &parse)
void ParseAnchorPoint (const QDomElement &domElement, const Document &parse)
void ParseToolHeight (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolTriangle (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void parseIntersectXYTool (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolCutSpline (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolCutSplinePath (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolCutArc (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolLineIntersectAxis (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolCurveIntersectAxis (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolPointOfIntersectionArcs (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolPointOfIntersectionCircles (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolPointOfIntersectionCurves (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolPointFromCircleAndTangent (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolPointFromArcAndTangent (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolTrueDarts (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
Q_STATIC_ASSERT_X (VPatternConverter::PatternMinVer< CONVERTER_VERSION_CHECK(0, 2, 7), "Time to refactor the code.")
void ParseOldToolSpline (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolSpline (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolCubicBezier (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
Q_STATIC_ASSERT_X (VPatternConverter::PatternMinVer< CONVERTER_VERSION_CHECK(0, 2, 7), "Time to refactor the code.")
void ParseOldToolSplinePath (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolSplinePath (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseToolCubicBezierPath (VMainGraphicsScene *scene, const QDomElement &domElement, const Document &parse)
void ParseNodeSpline (const QDomElement &domElement, const Document &parse)
void ParseNodeSplinePath (const QDomElement &domElement, const Document &parse)
void ParseToolArc (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseNodeArc (const QDomElement &domElement, const Document &parse)
void ParseToolArcWithLength (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolEllipticalArc (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseNodeEllipticalArc (const QDomElement &domElement, const Document &parse)
void ParseToolRotation (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolMirrorByLine (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolMirrorByAxis (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
void ParseToolMove (VMainGraphicsScene *scene, QDomElement &domElement, const Document &parse)
qreal EvalFormula (VContainer *data, const QString &formula, bool *ok) const
QDomElement MakeEmptyIncrement (const QString &name)
QDomElement FindIncrement (const QString &name) const
void GarbageCollector ()
Private Attributes
VContainer * data
Draw * mode
data container with data.
VMainGraphicsScene * draftScene
mode current draw mode.
VMainGraphicsScene * pieceScene
Additional Inherited Members
Signals inherited from VAbstractPattern
void activeDraftBlockChanged (const QString &newName)
activeDraftBlockChanged change active draft block.
void ChangedCursor (quint32 id)
ChangedCursor change cursor position.
void draftBlockNameChanged (const QString &oldName, const QString &newName)
draftBlockNameChanged save new name draft block.
void FullUpdateFromFile ()
FullUpdateFromFile update tool data form file.
void patternChanged (bool saved)
patternChanged emit if we have unsaved change.
void UpdatePatternLabel ()
void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
void ClearMainWindow ()
void UndoCommand ()
void setGuiEnabled (bool enabled)
void CheckLayout ()
void UpdateInLayoutList (quint32 id)
void showPiece (quint32 id)
void setCurrentDraftBlock (const QString &patterPiece)
void patternHasGroups (bool value)
void updateGroups ()
Static Public Member Functions inherited from VAbstractPattern
static VDataTool * getTool (quint32 id)
getTool return tool from tool list.
static void AddTool (quint32 id, VDataTool *tool)
AddTool add tool to list tools.
static void RemoveTool (quint32 id)
static VPiecePath ParsePieceNodes (const QDomElement &domElement)
static QVector< CustomSARecord > ParsePieceCSARecords (const QDomElement &domElement)
static QVector< quint32 > ParsePieceInternalPaths (const QDomElement &domElement)
static QVector< quint32 > ParsePieceAnchors (const QDomElement &domElement)
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Static Protected Member Functions inherited from VAbstractPattern
static void ToolExists (const quint32 &id)
static VPiecePath ParsePathNodes (const QDomElement &domElement)
static VPieceNode ParseSANode (const QDomElement &domElement)
Protected Attributes inherited from VAbstractPattern
QString activeDraftBlock
activeBlockName name current pattern peace.
QString m_DefaultLineColor
qreal m_DefaultLineWeight
QString m_DefaultLineType
QString lastSavedExportFormat
quint32 cursor
cursor cursor keep id tool after which we will add new tool in file.
QVector< VDataTool * > toolsOnRemove
QVector< VToolRecord > history
history history records.
QStringList patternPieces
patternPieces list of patern pieces names for combobox
bool modified
modified keep state of the document for cases that do not cover QUndoStack
Static Protected Attributes inherited from VAbstractPattern
static QHash< quint32, VDataTool * > tools = QHash<quint32, VDataTool*>()
tools list with pointer on tools.
static QVector< VLabelTemplateLine > patternLabelLines = QVector<VLabelTemplateLine>()
patternLabelLines list to speed up reading a template by many pieces.
static bool patternLabelWasChanged = false
Detailed Description
The VPattern class working with pattern file.
Definition at line 67 of file vpattern.h.
Constructor & Destructor Documentation
VPattern()
VPattern::VPattern (VContainer * data, Draw * mode, VMainGraphicsScene * draftScene, VMainGraphicsScene * pieceScene, QObject * parent = nullptr)
Definition at line 105 of file vpattern.cpp.
References draftScene, pieceScene, and SCASSERT.
Member Function Documentation
ActiveDrawBoundingRect()
QT_WARNING_PUSH QRectF VPattern::ActiveDrawBoundingRect () const
Definition at line 3959 of file vpattern.cpp.
References AbstractSpline, AlongLine, AnchorPoint, Arc, ArcIntersectAxis, ArcWithLength, Arrow, BasePoint, Bisector, CubicBezier, CubicBezierPath, CurveIntersectAxis, Cut, CutArc, CutSpline, CutSplinePath, DoublePoint, EllipticalArc, EndLine, VToolRecord::getDraftBlockName(), VToolRecord::getId(), VToolRecord::getTypeTool(), Group, Height, InsertNodes, InternalPath, LAST_ONE_DO_NOT_USE, Line, LineIntersect, LineIntersectAxis, LinePoint, Midpoint, MirrorByAxis, MirrorByLine, Move, NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, Normal, Piece, PointFromArcAndTangent, PointFromCircleAndTangent, PointOfContact, PointOfIntersection, PointOfIntersectionArcs, PointOfIntersectionCircles, PointOfIntersectionCurves, Rotation, ShoulderPoint, SinglePoint, Spline, SplinePath, Triangle, TrueDarts, and Union.
Referenced by MainWindow::zoomToSelected().
addEmptyCustomVariable()
void VPattern::addEmptyCustomVariable (const QString & name)
Definition at line 3465 of file vpattern.cpp.
References MakeEmptyIncrement(), VAbstractPattern::patternChanged(), and VAbstractPattern::TagIncrements.
Referenced by DialogVariables::addCustomVariable().
addEmptyCustomVariableAfter()
void VPattern::addEmptyCustomVariableAfter (const QString & after, const QString & name)
Definition at line 3475 of file vpattern.cpp.
References FindIncrement(), MakeEmptyIncrement(), VAbstractPattern::patternChanged(), and VAbstractPattern::TagIncrements.
Referenced by DialogVariables::addCustomVariable().
CreateEmptyFile()
void VPattern::CreateEmptyFile () virtual
CreateEmptyFile create minimal empty file.
Implements VAbstractPattern.
Definition at line 121 of file vpattern.cpp.
References anonymous_namespace{vpattern.cpp}::FileComment(), VPatternConverter::PatternMaxVerStr, qApp, VAbstractPattern::TagDescription, VAbstractPattern::TagIncrements, VAbstractPattern::TagMeasurements, VAbstractPattern::TagNotes, VAbstractPattern::TagPattern, VDomDocument::TagUnit, VDomDocument::TagVersion, and UnitsToStr().
customEvent()
void VPattern::customEvent (QEvent * event) protected virtual
Definition at line 625 of file vpattern.cpp.
References LITE_PARSE_EVENT, LiteParse, LiteParseTree(), qApp, and UNDO_EVENT.
DecrementReferens()
void VPattern::DecrementReferens (quint32 id) const virtual
DecrementReferens decrement reference parent objects.
Parameters
id parent object id.
Implements VAbstractPattern.
Definition at line 4094 of file vpattern.cpp.
References VDataTool::decrementReferens(), SCASSERT, VAbstractPattern::ToolExists(), and VAbstractPattern::tools.
EvalFormula()
qreal VPattern::EvalFormula (VContainer * data, const QString & formula, bool * ok) const private
Definition at line 3072 of file vpattern.cpp.
References data, and VContainer::DataVariables().
Referenced by ParseIncrementsElement().
FindIncrement()
QDomElement VPattern::FindIncrement (const QString & name) const private
Definition at line 3112 of file vpattern.cpp.
References VAbstractPattern::IncrementName, and VAbstractPattern::TagIncrement.
Referenced by addEmptyCustomVariableAfter(), MoveDownIncrement(), MoveUpIncrement(), removeCustomVariable(), setIncrementDescription(), SetIncrementFormula(), and setIncrementName().
GarbageCollector()
void VPattern::GarbageCollector () private
Definition at line 3133 of file vpattern.cpp.
References VAbstractTool::AttrInUse, VDomDocument::GetParametrUsage(), InUse, NotInUse, VDomDocument::SetParametrUsage(), and VAbstractPattern::TagModeling.
Referenced by setXMLContent().
GenerateLabel()
QString VPattern::GenerateLabel (const LabelType & type, const QString & reservedName = QString()) const virtual
GenerateLabel create name for draft block basepoint.
Parameters
type type of the label.
reservedName reversed point name. Use when need reserve name, but point is not in data base yet.
Returns
unique name for current draft block.
Implements VAbstractPattern.
Definition at line 3630 of file vpattern.cpp.
References data, VAbstractPattern::getActiveDraftBlockIndex(), GetLabelBase(), VContainer::IsUnique(), NewLabel, NewPatternPiece, and VAbstractPattern::TagDraftBlock.
Referenced by MainWindow::addDraftBlock().
GenerateSuffix()
QString VPattern::GenerateSuffix (const QString & type) const virtual
Implements VAbstractPattern.
Definition at line 3676 of file vpattern.cpp.
References VContainer::AllUniqueNames(), data, VAbstractPattern::getActiveDraftBlockIndex(), GetLabelBase(), and VContainer::IsUnique().
getActiveBasePoint()
quint32 VPattern::getActiveBasePoint ()
getActiveBasePoint return id base point current draft block.
Returns
id base point.
Definition at line 363 of file vpattern.cpp.
References VAbstractPattern::AttrType, VAbstractPattern::getActiveNodeElement(), VDomDocument::getParameterId(), VAbstractPattern::TagCalculation, VAbstractPattern::TagPoint, and VToolBasePoint::ToolType.
getActivePatternPieces()
QVector< quint32 > VPattern::getActivePatternPieces () const
Definition at line 385 of file vpattern.cpp.
References PatternPieceTool::AttrUnited, falseStr, VAbstractPattern::getActiveDraftElement(), VDomDocument::getParameterBool(), VDomDocument::getParameterId(), VAbstractPattern::TagPiece, and VAbstractPattern::TagPieces.
Referenced by MainWindow::SetToolButton().
GetDefCustomHeight()
int VPattern::GetDefCustomHeight () const
Definition at line 3764 of file vpattern.cpp.
References VAbstractPattern::AttrDefHeight, VDomDocument::GetParametrUInt(), IsDefCustom(), and VAbstractPattern::TagGradation.
Referenced by DialogPatternProperties::DialogPatternProperties(), and MainWindow::SetDefaultHeight().
GetDefCustomSize()
int VPattern::GetDefCustomSize () const
Definition at line 3823 of file vpattern.cpp.
References VAbstractPattern::AttrDefSize, VDomDocument::GetParametrUInt(), IsDefCustom(), and VAbstractPattern::TagGradation.
Referenced by DialogPatternProperties::DialogPatternProperties(), and MainWindow::SetDefaultSize().
GetLabelBase()
QString VPattern::GetLabelBase (quint32 index) const private
Definition at line 1203 of file vpattern.cpp.
References VApplication::LabelLanguages(), and qApp.
Referenced by GenerateLabel(), and GenerateSuffix().
IncrementReferens()
void VPattern::IncrementReferens (quint32 id) const virtual
IncrementReferens increment reference parent objects.
Parameters
id parent object id.
Implements VAbstractPattern.
Definition at line 4080 of file vpattern.cpp.
References VDataTool::incrementReferens(), SCASSERT, VAbstractPattern::ToolExists(), and VAbstractPattern::tools.
Referenced by ParseOldToolSplinePath(), ParseToolCubicBezierPath(), and ParseToolSplinePath().
IsDefCustom()
bool VPattern::IsDefCustom () const
Definition at line 3710 of file vpattern.cpp.
References VAbstractPattern::AttrCustom, falseStr, VDomDocument::getParameterBool(), and VAbstractPattern::TagGradation.
Referenced by DialogPatternProperties::DialogPatternProperties(), GetDefCustomHeight(), and GetDefCustomSize().
isReadOnly()
bool VPattern::isReadOnly () const
Definition at line 3882 of file vpattern.cpp.
References AttrReadOnly, falseStr, and VDomDocument::getParameterBool().
Referenced by DialogPatternProperties::DialogPatternProperties(), and MainWindow::LoadPattern().
LiteParseIncrements()
void VPattern::LiteParseIncrements ()
Definition at line 441 of file vpattern.cpp.
References VContainer::ClearUniqueIncrementNames(), VContainer::ClearVariables(), data, VException::DetailedInformation(), VException::ErrorMessage(), Increment, ParseIncrementsElement(), VAbstractPattern::setGuiEnabled(), and VAbstractPattern::TagIncrements.
Referenced by DialogVariables::localUpdateTree().
LiteParseTree
void VPattern::LiteParseTree (const Document & parse) virtual slot
LiteParseTree lite parse file.
Definition at line 515 of file vpattern.cpp.
References VAbstractPattern::activeDraftBlock, VException::DetailedInformation(), draftScene, VException::ErrorMessage(), FullParse, VAbstractPattern::FullUpdateFromFile(), VApplication::IsGUIMode(), LiteBlockParse, LiteParse, VMainGraphicsView::NewSceneRect(), Parse(), parseCurrentDraftBlock(), pieceScene, qApp, setCurrentData(), VAbstractPattern::setGuiEnabled(), and V_EX_NOINPUT.
Referenced by MainWindow::ChangedHeight(), MainWindow::ChangedSize(), MainWindow::ClosedDialogAnchorPoint(), MainWindow::ClosedDialogInternalPath(), MainWindow::ClosedDialogWithApply(), MainWindow::ClosedInsertNodesDialog(), MainWindow::closeUnionDialog(), customEvent(), MainWindow::LoadIndividual(), MainWindow::LoadMultisize(), DialogVariables::refreshPattern(), and MainWindow::SyncMeasurements().
MakeEmptyIncrement()
QDomElement VPattern::MakeEmptyIncrement (const QString & name) private
Definition at line 3102 of file vpattern.cpp.
References VAbstractPattern::IncrementDescription, VAbstractPattern::IncrementFormula, VAbstractPattern::IncrementName, VDomDocument::SetAttribute(), and VAbstractPattern::TagIncrement.
Referenced by addEmptyCustomVariable(), and addEmptyCustomVariableAfter().
MoveDownIncrement()
void VPattern::MoveDownIncrement (const QString & name)
Definition at line 3518 of file vpattern.cpp.
References FindIncrement(), VAbstractPattern::patternChanged(), VAbstractPattern::TagIncrement, and VAbstractPattern::TagIncrements.
Referenced by DialogVariables::moveDown().
MoveUpIncrement()
void VPattern::MoveUpIncrement (const QString & name)
Definition at line 3502 of file vpattern.cpp.
References FindIncrement(), VAbstractPattern::patternChanged(), VAbstractPattern::TagIncrement, and VAbstractPattern::TagIncrements.
Referenced by DialogVariables::moveUp().
Parse()
void VPattern::Parse (const Document & parse)
Parse parse file.
Parameters
parse parser file mode.
Definition at line 160 of file vpattern.cpp.
References VAbstractPattern::activeDraftBlock, VAbstractPattern::AttrName, VAbstractPattern::changeActiveDraftBlock(), VAbstractPattern::CheckLayout(), draftScene, FullParse, VDomDocument::GetParametrString(), LiteBlockParse, LiteParse, parseDraftBlockElement(), ParseIncrementsElement(), VAbstractPattern::patternPieces, pieceScene, PrepareForParse(), SCASSERT, VAbstractPattern::setActiveDraftBlock(), VAbstractPattern::TagCompanyName, VAbstractPattern::TagCustomerName, VAbstractPattern::TagDescription, VAbstractPattern::TagDraftBlock, VAbstractPattern::TagGradation, VAbstractPattern::TagImage, VAbstractPattern::TagIncrements, VAbstractPattern::TagMeasurements, VAbstractPattern::TagNotes, VAbstractPattern::TagPatternLabel, VAbstractPattern::TagPatternName, VAbstractPattern::TagPatternNum, VDomDocument::TagUnit, and VDomDocument::TagVersion.
Referenced by MainWindow::fullParseFile(), and LiteParseTree().
ParseAnchorPoint()
void VPattern::ParseAnchorPoint (const QDomElement & domElement, const Document & parse) private
Definition at line 1659 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrIdObject, VAbstractNode::AttrIdTool, AnchorPointTool::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), NULL_ID, NULL_ID_STR, and ToolsCommonAttributes().
Referenced by ParsePointElement().
ParseArcElement()
void VPattern::ParseArcElement (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse, const QString & type) private
ParseArcElement parse arc tag.
Parameters
scene scene.
domElement tag in xml tree.
parse parser file mode.
type type of spline.
Definition at line 3241 of file vpattern.cpp.
References ParseNodeArc(), ParseToolArc(), ParseToolArcWithLength(), SCASSERT, VToolArc::ToolType, VToolArcWithLength::ToolType, and VNodeArc::ToolType.
Referenced by ParseDrawMode().
parseCurrentDraftBlock()
void VPattern::parseCurrentDraftBlock () private
Definition at line 1192 of file vpattern.cpp.
References VAbstractPattern::CheckLayout(), VAbstractPattern::getActiveDraftElement(), LiteParse, and parseDraftBlockElement().
Referenced by LiteParseTree().
parseDraftBlockElement()
void VPattern::parseDraftBlockElement (const QDomNode & node, const Document & parse) private
parseDraftBlockElement parse draw tag.
Parameters
node node.
parse parser file mode.
Definition at line 684 of file vpattern.cpp.
References Calculation, VContainer::ClearCalculationGObjects(), data, Modeling, ParseDrawMode(), VAbstractPattern::parseGroups(), parsePatternPieces(), VAbstractPattern::TagCalculation, VAbstractPattern::TagGroups, VAbstractPattern::TagModeling, and VAbstractPattern::TagPieces.
Referenced by Parse(), and parseCurrentDraftBlock().
ParseDrawMode()
void VPattern::ParseDrawMode (const QDomNode & node, const Document & parse, const Draw & mode) private
ParseDrawMode parse draw tag with draw mode.
Parameters
node node.
parse parser file mode.
mode draw mode.
Definition at line 731 of file vpattern.cpp.
References VAbstractPattern::AttrType, Calculation, draftScene, mode, ParseArcElement(), ParseEllipticalArcElement(), ParseLineElement(), ParseOperationElement(), ParsePathElement(), ParsePointElement(), ParseSplineElement(), ParseToolsElement(), pieceScene, SCASSERT, VAbstractPattern::TagArc, VAbstractPattern::TagElArc, VAbstractPattern::TagLine, VAbstractPattern::TagOperation, VAbstractPattern::TagPath, VAbstractPattern::TagPoint, VAbstractPattern::TagSpline, and VAbstractPattern::TagTools.
Referenced by parseDraftBlockElement().
ParseEllipticalArcElement()
void VPattern::ParseEllipticalArcElement (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse, const QString & type) private
ParseEllipticalArcElement parse elliptical arc tag.
Parameters
scene scene.
domElement tag in xml tree.
parse parser file mode.
type type of spline.
Definition at line 3277 of file vpattern.cpp.
References ParseNodeEllipticalArc(), ParseToolEllipticalArc(), SCASSERT, VToolEllipticalArc::ToolType, and VNodeEllipticalArc::ToolType.
Referenced by ParseDrawMode().
ParseIncrementsElement()
void VPattern::ParseIncrementsElement (const QDomNode & node) private
ParseIncrementsElement parse increments tag.
Parameters
node tag in xml tree.
Definition at line 3425 of file vpattern.cpp.
References VContainer::AddVariable(), data, EvalFormula(), VDomDocument::GetParametrString(), VAbstractPattern::IncrementDescription, VAbstractPattern::IncrementFormula, VAbstractPattern::IncrementName, and VAbstractPattern::TagIncrement.
Referenced by LiteParseIncrements(), and Parse().
parseIntersectXYTool()
void VPattern::parseIntersectXYTool (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 1745 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrFirstPoint, AttrSecondPoint, PointIntersectXYTool::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), NULL_ID_STR, PointsCommonAttributes(), and SCASSERT.
Referenced by ParsePointElement().
ParseLineElement()
void VPattern::ParseLineElement (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
ParseLineElement parse line tag.
Parameters
scene scene.
domElement tag in xml tree.
parse parser file mode.
Definition at line 1158 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrFirstPoint, AttrLineColor, AttrLineType, AttrLineWeight, AttrSecondPoint, ColorBlack, VToolLine::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), LineTypeSolidLine, NULL_ID_STR, SCASSERT, and ToolsCommonAttributes().
Referenced by ParseDrawMode().
ParseNodeArc()
void VPattern::ParseNodeArc (const QDomElement & domElement, const Document & parse) private
Definition at line 2833 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrIdObject, VAbstractNode::AttrIdTool, VNodeArc::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VContainer::GeometricObject(), VDomDocument::GetParametrUInt(), Modeling, NULL_ID_STR, VGObject::setIdObject(), VGObject::setMode(), ToolsCommonAttributes(), and VContainer::UpdateGObject().
Referenced by ParseArcElement().
ParseNodeEllipticalArc()
void VPattern::ParseNodeEllipticalArc (const QDomElement & domElement, const Document & parse) private
Definition at line 2798 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrIdObject, VAbstractNode::AttrIdTool, VNodeEllipticalArc::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VContainer::GeometricObject(), VDomDocument::GetParametrUInt(), Modeling, NULL_ID_STR, VGObject::setIdObject(), VGObject::setMode(), ToolsCommonAttributes(), and VContainer::UpdateGObject().
Referenced by ParseEllipticalArcElement().
ParseNodePoint()
void VPattern::ParseNodePoint (const QDomElement & domElement, const Document & parse) private
Definition at line 1620 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrIdObject, VAbstractNode::AttrIdTool, AttrShowPointName, VNodePoint::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VContainer::GeometricObject(), VDomDocument::getParameterBool(), VDomDocument::GetParametrUInt(), Modeling, NULL_ID_STR, pieceScene, PointsCommonAttributes(), VPointF::setShowPointName(), trueStr, and VContainer::UpdateGObject().
Referenced by ParsePointElement().
ParseNodeSpline()
void VPattern::ParseNodeSpline (const QDomElement & domElement, const Document & parse) private
Definition at line 2604 of file vpattern.cpp.
References VException::AddMoreInformation(), VNodeSpline::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VContainer::GeometricObject(), VContainer::GetGObject(), Modeling, VGObject::setIdObject(), VGObject::setMode(), Spline, SplinesCommonAttributes(), and VContainer::UpdateGObject().
Referenced by ParseSplineElement().
ParseNodeSplinePath()
void VPattern::ParseNodeSplinePath (const QDomElement & domElement, const Document & parse) private
Definition at line 2650 of file vpattern.cpp.
References VException::AddMoreInformation(), VNodeSplinePath::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VContainer::GeometricObject(), VContainer::GetGObject(), Modeling, VGObject::setIdObject(), VGObject::setMode(), SplinePath, SplinesCommonAttributes(), and VContainer::UpdateGObject().
Referenced by ParseSplineElement().
ParseOldToolSpline()
void VPattern::ParseOldToolSpline (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 2239 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle1, AttrAngle2, AttrColor, AttrDuplicate, AttrKAsm1, AttrKAsm2, AttrKCurve, AttrPoint1, AttrPoint4, ColorBlack, VToolSpline::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VContainer::GeometricObject(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), NULL_ID_STR, SCASSERT, and ToolsCommonAttributes().
Referenced by ParseSplineElement().
ParseOldToolSplinePath()
void VPattern::ParseOldToolSplinePath (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 2391 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle, AttrColor, AttrDuplicate, AttrKAsm1, AttrKAsm2, AttrKCurve, AttrPathPoint, AttrPSpline, ColorBlack, VToolSplinePath::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, FullParse, VContainer::GeometricObject(), VGObject::getIdTool(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), IncrementReferens(), NULL_ID_STR, SCASSERT, and ToolsCommonAttributes().
Referenced by ParseSplineElement().
ParseOperationElement()
void VPattern::ParseOperationElement (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse, const QString & type) private
Definition at line 3350 of file vpattern.cpp.
References ParseToolMirrorByAxis(), ParseToolMirrorByLine(), ParseToolMove(), ParseToolRotation(), SCASSERT, VToolMirrorByAxis::ToolType, VToolMirrorByLine::ToolType, VToolMove::ToolType, and VToolRotation::ToolType.
Referenced by ParseDrawMode().
ParsePathElement()
void VPattern::ParsePathElement (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 3383 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrCut, VAbstractNode::AttrIdTool, AttrLineType, VAbstractPattern::AttrName, VAbstractPattern::AttrType, VToolInternalPath::Create(), CustomSeamAllowance, data, VExceptionBadId::ErrorMessage(), falseStr, FromFile, VDomDocument::getParameterBool(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), LineTypeSolidLine, lineTypeToPenStyle(), NULL_ID_STR, VAbstractPattern::ParsePathNodes(), SCASSERT, VPiecePath::SetCutPath(), VPiecePath::SetName(), VPiecePath::SetPenType(), VPiecePath::SetType(), VAbstractPattern::TagNodes, and ToolsCommonAttributes().
Referenced by ParseDrawMode().
parsePatternPieces()
void VPattern::parsePatternPieces (const QDomElement & domElement, const Document & parse) private
parsePatternPieces parse pieces tag.
Parameters
domElement tag in xml tree.
parse parser file mode.
Definition at line 983 of file vpattern.cpp.
References parsePieceElement(), and VAbstractPattern::TagPiece.
Referenced by parseDraftBlockElement().
ParsePieceDataTag()
void VPattern::ParsePieceDataTag (const QDomElement & domElement, VPiece & piece) const private
Definition at line 925 of file vpattern.cpp.
References VAbstractPattern::AttrAnnotation, PatternPieceTool::AttrBottomRightAnchor, PatternPieceTool::AttrCenterAnchor, VAbstractPattern::AttrFoldPosition, PatternPieceTool::AttrFont, PatternPieceTool::AttrHeight, VAbstractPattern::AttrLetter, AttrMx, AttrMy, VAbstractPattern::AttrOnFold, VAbstractPattern::AttrOrientation, VAbstractPattern::AttrQuantity, VAbstractPattern::AttrRotation, VAbstractPattern::AttrRotationWay, VAbstractPattern::AttrTilt, PatternPieceTool::AttrTopLeftAnchor, VAbstractPattern::AttrVisible, VAbstractPattern::AttrWidth, falseStr, VDomDocument::GetLabelTemplate(), VDomDocument::getParameterBool(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrEmptyString(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VPiece::GetPatternPieceData(), NULL_ID_STR, VPieceLabelData::SetAnnotation(), VPatternLabelData::setBottomRightAnchorPoint(), VPatternLabelData::setCenterAnchorPoint(), VPieceLabelData::SetFoldPosition(), VPatternLabelData::SetFontSize(), VPatternLabelData::SetLabelHeight(), VPieceLabelData::SetLabelTemplate(), VPatternLabelData::SetLabelWidth(), VPieceLabelData::SetLetter(), VPieceLabelData::SetOnFold(), VPieceLabelData::SetOrientation(), VAbstractFloatItemData::SetPos(), VPieceLabelData::SetQuantity(), VPatternLabelData::SetRotation(), VPieceLabelData::SetRotationWay(), VPieceLabelData::SetTilt(), VPatternLabelData::setTopLeftAnchorPoint(), VAbstractFloatItemData::SetVisible(), and trueStr.
Referenced by parsePieceElement().
parsePieceElement()
void VPattern::parsePieceElement (QDomElement & domElement, const Document & parse) private
parsePieceElement parse piece tag.
Parameters
domElement tag in xml tree.
parse parser file mode.
Definition at line 807 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrClosed, PatternPieceTool::AttrForbidFlipping, PatternPieceTool::AttrHideSeamLine, AttrInLayout, AttrMx, AttrMy, VAbstractPattern::AttrName, PatternPieceTool::AttrPieceColor, PatternPieceTool::AttrPieceFill, AttrPieceLocked, PatternPieceTool::AttrSeamAllowance, PatternPieceTool::AttrSeamAllowanceBuiltIn, PatternPieceTool::AttrUnited, PatternPieceTool::AttrVersion, VAbstractPattern::AttrWidth, CONVERTER_VERSION_CHECK, PatternPieceTool::Create(), data, VExceptionBadId::ErrorMessage(), falseStr, FromFile, VDomDocument::getParameterBool(), VDomDocument::getParameterId(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, VAbstractPattern::ParsePieceAnchors(), VAbstractPattern::ParsePieceCSARecords(), ParsePieceDataTag(), ParsePieceGrainline(), VAbstractPattern::ParsePieceInternalPaths(), VAbstractPattern::ParsePieceNodes(), parsePieceNodes(), ParsePiecePatternInfo(), VPatternConverter::PatternMinVer, pieceScene, Q_STATIC_ASSERT_X(), qApp, VPiece::setAnchors(), VDomDocument::SetAttribute(), VAbstractPiece::setColor(), VPiece::SetCustomSARecords(), VAbstractPiece::setFill(), VAbstractPiece::SetForbidFlipping(), VAbstractPiece::setHideSeamLine(), VPiece::SetInLayout(), VPiece::SetInternalPaths(), VPiece::setIsLocked(), VAbstractPiece::SetMx(), VAbstractPiece::SetMy(), VAbstractPiece::SetName(), VPiece::SetPath(), VAbstractPiece::SetSeamAllowance(), VAbstractPiece::SetSeamAllowanceBuiltIn(), VPiece::SetUnited(), PatternPieceTool::TagAnchors, PatternPieceTool::TagCSA, VAbstractPattern::TagData, VAbstractPattern::TagGrainline, PatternPieceTool::TagIPaths, VAbstractPattern::TagNodes, VAbstractPattern::TagPatternInfo, and trueStr.
Referenced by parsePatternPieces().
ParsePieceGrainline()
void VPattern::ParsePieceGrainline (const QDomElement & domElement, VPiece & piece) const private
Definition at line 964 of file vpattern.cpp.
References VAbstractPattern::AttrArrows, PatternPieceTool::AttrBottomAnchorPoint, PatternPieceTool::AttrCenterAnchor, AttrLength, AttrMx, AttrMy, VAbstractPattern::AttrRotation, PatternPieceTool::AttrTopAnchorPoint, VAbstractPattern::AttrVisible, falseStr, VPiece::GetGrainlineGeometry(), VDomDocument::getParameterBool(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), NULL_ID_STR, VGrainlineData::SetArrowType(), VGrainlineData::setBottomAnchorPoint(), VGrainlineData::setCenterAnchorPoint(), VGrainlineData::SetLength(), VAbstractFloatItemData::SetPos(), VGrainlineData::SetRotation(), VGrainlineData::setTopAnchorPoint(), and VAbstractFloatItemData::SetVisible().
Referenced by parsePieceElement().
parsePieceNode()
VNodeDetail VPattern::parsePieceNode (const QDomElement & domElement) const private
Definition at line 638 of file vpattern.cpp.
References AttrIdObject, AttrMx, AttrMy, VAbstractPattern::AttrNodeReverse, VAbstractPattern::AttrType, Contour, VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::NodeArc, NodeArc, VAbstractPattern::NodeElArc, NodeElArc, VAbstractPattern::NodePoint, NodePoint, VAbstractPattern::NodeSpline, NodeSpline, VAbstractPattern::NodeSplinePath, NodeSplinePath, and NULL_ID_STR.
Referenced by parsePieceNodes().
parsePieceNodes()
void VPattern::parsePieceNodes (const QDomElement & domElement, VPiece & piece, qreal width, bool closed) const private
Definition at line 907 of file vpattern.cpp.
References VNodeDetail::Convert(), data, VPiece::GetPath(), parsePieceNode(), VPiecePath::SetNodes(), and VAbstractPattern::TagNode.
Referenced by parsePieceElement().
ParsePiecePatternInfo()
void VPattern::ParsePiecePatternInfo (const QDomElement & domElement, VPiece & piece) const private
Definition at line 949 of file vpattern.cpp.
References PatternPieceTool::AttrBottomRightAnchor, PatternPieceTool::AttrCenterAnchor, PatternPieceTool::AttrFont, PatternPieceTool::AttrHeight, AttrMx, AttrMy, VAbstractPattern::AttrRotation, PatternPieceTool::AttrTopLeftAnchor, VAbstractPattern::AttrVisible, VAbstractPattern::AttrWidth, VDomDocument::getParameterBool(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VPiece::GetPatternInfo(), NULL_ID_STR, VPatternLabelData::setBottomRightAnchorPoint(), VPatternLabelData::setCenterAnchorPoint(), VPatternLabelData::SetFontSize(), VPatternLabelData::SetLabelHeight(), VPatternLabelData::SetLabelWidth(), VAbstractFloatItemData::SetPos(), VPatternLabelData::SetRotation(), VPatternLabelData::setTopLeftAnchorPoint(), VAbstractFloatItemData::SetVisible(), and trueStr.
Referenced by parsePieceElement().
ParsePointElement()
void VPattern::ParsePointElement (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse, const QString & type) private
ParsePointElement parse point tag.
Parameters
scene scene.
domElement tag in xml tree.
parse parser file mode.
type type of point.
Definition at line 1040 of file vpattern.cpp.
References ParseAnchorPoint(), parseIntersectXYTool(), ParseNodePoint(), ParseToolAlongLine(), ParseToolBasePoint(), ParseToolBisector(), ParseToolCurveIntersectAxis(), ParseToolCutArc(), ParseToolCutSpline(), ParseToolCutSplinePath(), ParseToolEndLine(), ParseToolHeight(), ParseToolLineIntersect(), ParseToolLineIntersectAxis(), ParseToolNormal(), ParseToolPointFromArcAndTangent(), ParseToolPointFromCircleAndTangent(), ParseToolPointOfContact(), ParseToolPointOfIntersectionArcs(), ParseToolPointOfIntersectionCircles(), ParseToolPointOfIntersectionCurves(), ParseToolShoulderPoint(), ParseToolTriangle(), ParseToolTrueDarts(), SCASSERT, VToolTrueDarts::ToolType, IntersectCirclesTool::ToolType, IntersectCircleTangentTool::ToolType, PointIntersectXYTool::ToolType, VToolCutArc::ToolType, VToolCutSpline::ToolType, VToolCutSplinePath::ToolType, VToolAlongLine::ToolType, VToolBisector::ToolType, VToolCurveIntersectAxis::ToolType, VToolEndLine::ToolType, VToolHeight::ToolType, VToolLineIntersectAxis::ToolType, VToolNormal::ToolType, VToolShoulderPoint::ToolType, VToolBasePoint::ToolType, VToolLineIntersect::ToolType, VToolPointFromArcAndTangent::ToolType, VToolPointOfContact::ToolType, VToolPointOfIntersectionArcs::ToolType, VToolPointOfIntersectionCurves::ToolType, VToolTriangle::ToolType, AnchorPointTool::ToolType, and VNodePoint::ToolType.
Referenced by ParseDrawMode().
ParseSplineElement()
void VPattern::ParseSplineElement (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse, const QString & type) private
ParseSplineElement parse spline tag.
Parameters
scene scene.
domElement tag in xml tree.
parse parser file mode.
type type of spline.
Definition at line 3178 of file vpattern.cpp.
References VToolSpline::OldToolType, VToolSplinePath::OldToolType, ParseNodeSpline(), ParseNodeSplinePath(), ParseOldToolSpline(), ParseOldToolSplinePath(), ParseToolCubicBezier(), ParseToolCubicBezierPath(), ParseToolSpline(), ParseToolSplinePath(), SCASSERT, VToolCubicBezier::ToolType, VToolCubicBezierPath::ToolType, VToolSpline::ToolType, VToolSplinePath::ToolType, VNodeSpline::ToolType, and VNodeSplinePath::ToolType.
Referenced by ParseDrawMode().
ParseToolAlongLine()
void VPattern::ParseToolAlongLine (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1353 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrFirstPoint, AttrLength, AttrSecondPoint, VToolAlongLine::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolArc()
void VPattern::ParseToolArc (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2695 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle1, AttrAngle2, AttrCenter, AttrColor, AttrLineWeight, AttrPenStyle, AttrRadius, ColorBlack, VToolArc::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), LineTypeSolidLine, VAbstractPattern::modified, NULL_ID_STR, SCASSERT, VDomDocument::SetAttribute(), and ToolsCommonAttributes().
Referenced by ParseArcElement().
ParseToolArcWithLength()
void VPattern::ParseToolArcWithLength (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2868 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle1, AttrCenter, AttrColor, AttrLength, AttrLineWeight, AttrPenStyle, AttrRadius, ColorBlack, VToolArcWithLength::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), LineTypeSolidLine, VAbstractPattern::modified, NULL_ID_STR, SCASSERT, VDomDocument::SetAttribute(), and ToolsCommonAttributes().
Referenced by ParseArcElement().
ParseToolBasePoint()
void VPattern::ParseToolBasePoint (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 1268 of file vpattern.cpp.
References VAbstractPattern::activeDraftBlock, VException::AddMoreInformation(), AttrX, AttrY, VToolBasePoint::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrDouble(), PointsCommonAttributes(), qApp, SCASSERT, and VPointF::setShowPointName().
Referenced by ParsePointElement().
ParseToolBisector()
void VPattern::ParseToolBisector (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1496 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrFirstPoint, AttrLength, AttrSecondPoint, AttrThirdPoint, VToolBisector::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolCubicBezier()
void VPattern::ParseToolCubicBezier (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 2346 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrColor, AttrDuplicate, AttrLineWeight, AttrPenStyle, AttrPoint1, AttrPoint2, AttrPoint3, AttrPoint4, ColorBlack, VToolCubicBezier::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VContainer::GeometricObject(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), LineTypeSolidLine, NULL_ID_STR, SCASSERT, and ToolsCommonAttributes().
Referenced by ParseSplineElement().
ParseToolCubicBezierPath()
void VPattern::ParseToolCubicBezierPath (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 2547 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrColor, AttrDuplicate, AttrLineWeight, AttrPathPoint, AttrPenStyle, AttrPSpline, ColorBlack, VToolCubicBezierPath::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, FullParse, VContainer::GeometricObject(), VGObject::getIdTool(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), IncrementReferens(), LineTypeSolidLine, NULL_ID_STR, SCASSERT, and ToolsCommonAttributes().
Referenced by ParseSplineElement().
ParseToolCurveIntersectAxis()
void VPattern::ParseToolCurveIntersectAxis (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1958 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle, AttrBasePoint, AttrCurve, VToolCurveIntersectAxis::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolCutArc()
void VPattern::ParseToolCutArc (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1863 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrArc, AttrLength, VToolCutArc::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolCutSpline()
void VPattern::ParseToolCutSpline (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1778 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrLength, VToolCutSpline::AttrSpline, VToolCutSpline::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolCutSplinePath()
void VPattern::ParseToolCutSplinePath (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1820 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrLength, VToolCutSplinePath::AttrSplinePath, VToolCutSplinePath::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolEllipticalArc()
void VPattern::ParseToolEllipticalArc (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2743 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle1, AttrAngle2, AttrCenter, AttrColor, AttrLineWeight, AttrPenStyle, AttrRadius1, AttrRadius2, AttrRotationAngle, ColorBlack, VToolEllipticalArc::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), LineTypeSolidLine, VAbstractPattern::modified, NULL_ID_STR, SCASSERT, VDomDocument::SetAttribute(), and ToolsCommonAttributes().
Referenced by ParseEllipticalArcElement().
ParseToolEndLine()
void VPattern::ParseToolEndLine (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1301 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle, AttrBasePoint, AttrLength, VToolEndLine::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolHeight()
void VPattern::ParseToolHeight (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 1681 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrBasePoint, AttrP1Line, AttrP2Line, VToolHeight::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), NULL_ID_STR, PointsCommonAttributes(), and SCASSERT.
Referenced by ParsePointElement().
ParseToolLineIntersect()
void VPattern::ParseToolLineIntersect (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 1544 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrP1Line1, AttrP1Line2, AttrP2Line1, AttrP2Line2, VToolLineIntersect::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), NULL_ID_STR, PointsCommonAttributes(), and SCASSERT.
Referenced by ParsePointElement().
ParseToolLineIntersectAxis()
void VPattern::ParseToolLineIntersectAxis (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1905 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle, AttrBasePoint, AttrP1Line, AttrP2Line, VToolLineIntersectAxis::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolMirrorByAxis()
void VPattern::ParseToolMirrorByAxis (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2990 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAxisType, AttrCenter, AttrSuffix, VToolMirrorByAxis::Create(), data, VExceptionBadId::ErrorMessage(), VAbstractOperation::ExtractData(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), NULL_ID, NULL_ID_STR, SCASSERT, and ToolsCommonAttributes().
Referenced by ParseOperationElement().
ParseToolMirrorByLine()
void VPattern::ParseToolMirrorByLine (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2960 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrP1Line, AttrP2Line, AttrSuffix, VToolMirrorByLine::Create(), data, VExceptionBadId::ErrorMessage(), VAbstractOperation::ExtractData(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), NULL_ID, NULL_ID_STR, SCASSERT, and ToolsCommonAttributes().
Referenced by ParseOperationElement().
ParseToolMove()
void VPattern::ParseToolMove (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 3020 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle, AttrCenter, AttrLength, AttrRotationAngle, AttrSuffix, VToolMove::Create(), data, VExceptionBadId::ErrorMessage(), VAbstractOperation::ExtractData(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID, NULL_ID_STR, SCASSERT, VDomDocument::SetAttribute(), and ToolsCommonAttributes().
Referenced by ParseOperationElement().
ParseToolNormal()
void VPattern::ParseToolNormal (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1448 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle, AttrFirstPoint, AttrLength, AttrSecondPoint, VToolNormal::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolPointFromArcAndTangent()
void VPattern::ParseToolPointFromArcAndTangent (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 2160 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrArc, AttrCrossPoint, AttrTangent, VToolPointFromArcAndTangent::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), NULL_ID_STR, PointsCommonAttributes(), and SCASSERT.
Referenced by ParsePointElement().
ParseToolPointFromCircleAndTangent()
void VPattern::ParseToolPointFromCircleAndTangent (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2118 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrCCenter, AttrCRadius, AttrCrossPoint, AttrTangent, IntersectCircleTangentTool::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolPointOfContact()
void VPattern::ParseToolPointOfContact (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1575 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrCenter, AttrFirstPoint, AttrRadius, AttrSecondPoint, VToolPointOfContact::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolPointOfIntersectionArcs()
void VPattern::ParseToolPointOfIntersectionArcs (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 2009 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrCrossPoint, AttrFirstArc, AttrSecondArc, VToolPointOfIntersectionArcs::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), NULL_ID_STR, PointsCommonAttributes(), and SCASSERT.
Referenced by ParsePointElement().
ParseToolPointOfIntersectionCircles()
void VPattern::ParseToolPointOfIntersectionCircles (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2042 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrC1Center, AttrC1Radius, AttrC2Center, AttrC2Radius, AttrCrossPoint, IntersectCirclesTool::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolPointOfIntersectionCurves()
void VPattern::ParseToolPointOfIntersectionCurves (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2086 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrCurve1, AttrCurve2, AttrHCrossPoint, AttrVCrossPoint, VToolPointOfIntersectionCurves::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), NULL_ID_STR, PointsCommonAttributes(), and SCASSERT.
Referenced by ParsePointElement().
ParseToolRotation()
void VPattern::ParseToolRotation (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2917 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle, AttrCenter, AttrSuffix, VToolRotation::Create(), data, VExceptionBadId::ErrorMessage(), VAbstractOperation::ExtractData(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID, NULL_ID_STR, SCASSERT, VDomDocument::SetAttribute(), and ToolsCommonAttributes().
Referenced by ParseOperationElement().
ParseToolsElement()
void VPattern::ParseToolsElement (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse, const QString & type) private
ParseToolsElement parse tools tag.
Parameters
scene scene.
domElement tag in xml tree.
parse parser file mode.
type type of spline.
Definition at line 3309 of file vpattern.cpp.
References VException::AddMoreInformation(), UnionTool::AttrIndexD1, UnionTool::AttrIndexD2, UnionTool::Create(), data, UnionToolInitData::data, UnionToolInitData::doc, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), UnionToolInitData::parse, UnionToolInitData::piece1_Index, UnionToolInitData::piece2_Index, SCASSERT, UnionToolInitData::scene, VAbstractPattern::tools, ToolsCommonAttributes(), UnionTool::ToolType, and UnionToolInitData::typeCreation.
Referenced by ParseDrawMode().
ParseToolShoulderPoint()
void VPattern::ParseToolShoulderPoint (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 1400 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrLength, AttrP1Line, AttrP2Line, AttrPShoulder, VToolShoulderPoint::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), VAbstractPattern::modified, NULL_ID_STR, PointsCommonAttributes(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by ParsePointElement().
ParseToolSpline()
void VPattern::ParseToolSpline (VMainGraphicsScene * scene, QDomElement & domElement, const Document & parse) private
Definition at line 2280 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle1, AttrAngle2, AttrColor, AttrDuplicate, AttrLength1, AttrLength2, AttrLineWeight, AttrPenStyle, AttrPoint1, AttrPoint4, ColorBlack, VToolSpline::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), LineTypeSolidLine, VAbstractPattern::modified, NULL_ID_STR, qApp, SCASSERT, VDomDocument::SetAttribute(), VAbstractMainWindow::ShowToolTip(), ToolsCommonAttributes(), and VAbstractTool::ToolTip().
Referenced by ParseSplineElement().
ParseToolSplinePath()
void VPattern::ParseToolSplinePath (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 2453 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAngle1, AttrAngle2, AttrColor, AttrDuplicate, AttrLength1, AttrLength2, AttrLineWeight, AttrPathPoint, AttrPenStyle, AttrPSpline, ColorBlack, VToolSplinePath::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, FullParse, VContainer::GeometricObject(), VGObject::getIdTool(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VAbstractPattern::haveLiteChange(), IncrementReferens(), LineTypeSolidLine, VAbstractPattern::modified, NULL_ID_STR, qApp, SCASSERT, VDomDocument::SetAttribute(), VAbstractMainWindow::ShowToolTip(), ToolsCommonAttributes(), and VAbstractTool::ToolTip().
Referenced by ParseSplineElement().
ParseToolTriangle()
void VPattern::ParseToolTriangle (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 1714 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrAxisP1, AttrAxisP2, AttrFirstPoint, AttrSecondPoint, VToolTriangle::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::GetParametrUInt(), NULL_ID_STR, PointsCommonAttributes(), and SCASSERT.
Referenced by ParsePointElement().
ParseToolTrueDarts()
void VPattern::ParseToolTrueDarts (VMainGraphicsScene * scene, const QDomElement & domElement, const Document & parse) private
Definition at line 2193 of file vpattern.cpp.
References VException::AddMoreInformation(), AttrBaseLineP1, AttrBaseLineP2, AttrDartP1, AttrDartP2, AttrDartP3, AttrMx1, AttrMx2, AttrMy1, AttrMy2, AttrName1, AttrName2, AttrPoint1, AttrPoint2, AttrShowPointName1, AttrShowPointName2, VToolTrueDarts::Create(), data, VExceptionBadId::ErrorMessage(), FromFile, VDomDocument::getParameterBool(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), NULL_ID_STR, qApp, SCASSERT, ToolsCommonAttributes(), and trueStr.
Referenced by ParsePointElement().
PointsCommonAttributes() [1/3]
void VPattern::PointsCommonAttributes (const QDomElement & domElement, quint32 & id, qreal & mx, qreal & my) private
Definition at line 1025 of file vpattern.cpp.
References AttrMx, AttrMy, VDomDocument::GetParametrDouble(), qApp, and ToolsCommonAttributes().
PointsCommonAttributes() [2/3]
void VPattern::PointsCommonAttributes (const QDomElement & domElement, quint32 & id, QString & name, qreal & mx, qreal & my, bool & labelVisible) private
Definition at line 1015 of file vpattern.cpp.
References VAbstractPattern::AttrName, AttrShowPointName, VDomDocument::getParameterBool(), VDomDocument::GetParametrString(), PointsCommonAttributes(), and trueStr.
PointsCommonAttributes() [3/3]
void VPattern::PointsCommonAttributes (const QDomElement & domElement, quint32 & id, QString & name, qreal & mx, qreal & my, bool & labelVisible, QString & lineType, QString & lineWeight, QString & lineColor) private
Definition at line 1005 of file vpattern.cpp.
References AttrLineColor, AttrLineType, AttrLineWeight, VDomDocument::GetParametrString(), LineTypeSolidLine, and qApp.
Referenced by parseIntersectXYTool(), ParseNodePoint(), ParseToolAlongLine(), ParseToolBasePoint(), ParseToolBisector(), ParseToolCurveIntersectAxis(), ParseToolCutArc(), ParseToolCutSpline(), ParseToolCutSplinePath(), ParseToolEndLine(), ParseToolHeight(), ParseToolLineIntersect(), ParseToolLineIntersectAxis(), ParseToolNormal(), ParseToolPointFromArcAndTangent(), ParseToolPointFromCircleAndTangent(), ParseToolPointOfContact(), ParseToolPointOfIntersectionArcs(), ParseToolPointOfIntersectionCircles(), ParseToolPointOfIntersectionCurves(), ParseToolShoulderPoint(), ParseToolTriangle(), and PointsCommonAttributes().
PrepareForParse()
void VPattern::PrepareForParse (const Document & parse) private
Definition at line 3914 of file vpattern.cpp.
References VAbstractPattern::activeDraftBlock, ArcRadius, VContainer::ClearForFullParse(), VContainer::ClearUniqueNames(), VContainer::ClearVariables(), VAbstractPattern::cursor, CurveAngle, CurveCLength, CurveLength, data, draftScene, FullParse, VAbstractPattern::history, Increment, VMainGraphicsScene::InitOrigins(), LineAngle, LineLength, LiteParse, VAbstractPattern::patternPieces, pieceScene, SCASSERT, VDomDocument::TestUniqueId(), VAbstractPattern::tools, and VAbstractPattern::toolsOnRemove.
Referenced by Parse().
Q_STATIC_ASSERT_X() [1/2]
VPattern::Q_STATIC_ASSERT_X () private
Referenced by parsePieceElement().
Q_STATIC_ASSERT_X() [2/2]
VPattern::Q_STATIC_ASSERT_X () private
removeCustomVariable()
void VPattern::removeCustomVariable (const QString & name)
Definition at line 3494 of file vpattern.cpp.
References FindIncrement(), VAbstractPattern::patternChanged(), and VAbstractPattern::TagIncrements.
Referenced by DialogVariables::removeCustomVariable().
replaceNameInFormula()
void VPattern::replaceNameInFormula (QVector< VFormulaField > & expressions, const QString & name, const QString & newName)
Definition at line 3567 of file vpattern.cpp.
References VTranslateVars::BiasTokens(), and VAbstractPattern::patternChanged().
Referenced by DialogVariables::refreshPattern(), and DialogVariables::saveCustomVariableName().
SaveDocument()
bool VPattern::SaveDocument (const QString & fileName, QString & error) virtual
Reimplemented from VDomDocument.
Definition at line 410 of file vpattern.cpp.
References anonymous_namespace{vpattern.cpp}::FileComment(), VAbstractPattern::modified, VDomDocument::SaveDocument(), and VDomDocument::TestUniqueId().
Referenced by MainWindow::SavePattern().
setCurrentData()
void VPattern::setCurrentData ()
setCurrentData set current data set.
Each time after parsing need set correct data set for current draft block. After parsing it is always last. Current data set for draft block it is data set for last object in draft block (point, arc, spline, spline path so on).
Definition at line 274 of file vpattern.cpp.
References VAbstractPattern::activeDraftBlock, Calculation, currentLength, currentSeamAllowance, data, VAbstractPattern::draftBlockCount(), VDataTool::getData(), VToolRecord::getDraftBlockName(), VToolRecord::getId(), VAbstractPattern::history, mode, NULL_ID, VContainer::RemoveVariable(), VAbstractPattern::ToolExists(), and VAbstractPattern::tools.
Referenced by MainWindow::changeDraftBlock(), and LiteParseTree().
SetDefCustom()
void VPattern::SetDefCustom (bool value)
Definition at line 3731 of file vpattern.cpp.
References VAbstractPattern::AttrCustom, VAbstractPattern::AttrDefHeight, VAbstractPattern::CheckTagExists(), VAbstractPattern::modified, VDomDocument::SetAttribute(), SetDefCustomHeight(), SetDefCustomSize(), and VAbstractPattern::TagGradation.
Referenced by DialogPatternProperties::SaveDefValues().
SetDefCustomHeight()
void VPattern::SetDefCustomHeight (int value)
Definition at line 3792 of file vpattern.cpp.
References VAbstractPattern::AttrDefHeight, VAbstractPattern::CheckTagExists(), VAbstractPattern::modified, VDomDocument::SetAttribute(), and VAbstractPattern::TagGradation.
Referenced by DialogPatternProperties::SaveDefValues(), and SetDefCustom().
SetDefCustomSize()
void VPattern::SetDefCustomSize (int value)
Definition at line 3851 of file vpattern.cpp.
References VAbstractPattern::AttrDefSize, VAbstractPattern::CheckTagExists(), VAbstractPattern::modified, VDomDocument::SetAttribute(), and VAbstractPattern::TagGradation.
Referenced by DialogPatternProperties::SaveDefValues(), and SetDefCustom().
setIncrementDescription()
void VPattern::setIncrementDescription (const QString & name, const QString & text)
Definition at line 3556 of file vpattern.cpp.
References FindIncrement(), VAbstractPattern::IncrementDescription, VAbstractPattern::patternChanged(), and VDomDocument::SetAttribute().
Referenced by DialogVariables::saveCustomVariableDescription().
SetIncrementFormula()
void VPattern::SetIncrementFormula (const QString & name, const QString & text)
Definition at line 3545 of file vpattern.cpp.
References FindIncrement(), VAbstractPattern::IncrementFormula, VAbstractPattern::patternChanged(), and VDomDocument::SetAttribute().
Referenced by DialogVariables::Fx(), and DialogVariables::saveCustomVariableFormula().
setIncrementName()
void VPattern::setIncrementName (const QString & name, const QString & text)
Definition at line 3534 of file vpattern.cpp.
References FindIncrement(), VAbstractPattern::IncrementName, VAbstractPattern::patternChanged(), and VDomDocument::SetAttribute().
Referenced by DialogVariables::saveCustomVariableName().
SetReadOnly()
void VPattern::SetReadOnly (bool rOnly)
Definition at line 3895 of file vpattern.cpp.
References AttrReadOnly, VAbstractPattern::modified, and VDomDocument::SetAttribute().
Referenced by DialogPatternProperties::SaveReadOnlyState().
setXMLContent()
void VPattern::setXMLContent (const QString & fileName) virtual
Reimplemented from VDomDocument.
Definition at line 149 of file vpattern.cpp.
References GarbageCollector(), and VDomDocument::setXMLContent().
Referenced by MainWindow::LoadPattern().
SplinesCommonAttributes()
void VPattern::SplinesCommonAttributes (const QDomElement & domElement, quint32 & id, quint32 & idObject, quint32 & idTool) private
Definition at line 1184 of file vpattern.cpp.
References AttrIdObject, VAbstractNode::AttrIdTool, VDomDocument::GetParametrUInt(), NULL_ID_STR, and ToolsCommonAttributes().
Referenced by ParseNodeSpline(), and ParseNodeSplinePath().
ToolBoundingRect() [1/2]
template<typename T > QRectF VPattern::ToolBoundingRect (const QRectF & rec, const quint32 & id) const private
ToolBoundingRect() [2/2]
template<typename T > QT_WARNING_POP QRectF VPattern::ToolBoundingRect (const QRectF & rect, const quint32 & id) const
Definition at line 4053 of file vpattern.cpp.
References SCASSERT, and VAbstractPattern::tools.
ToolsCommonAttributes()
void VPattern::ToolsCommonAttributes (const QDomElement & domElement, quint32 & id) private
Definition at line 3950 of file vpattern.cpp.
References VDomDocument::getParameterId().
Referenced by ParseAnchorPoint(), ParseLineElement(), ParseNodeArc(), ParseNodeEllipticalArc(), ParseOldToolSpline(), ParseOldToolSplinePath(), ParsePathElement(), ParseToolArc(), ParseToolArcWithLength(), ParseToolCubicBezier(), ParseToolCubicBezierPath(), ParseToolEllipticalArc(), ParseToolMirrorByAxis(), ParseToolMirrorByLine(), ParseToolMove(), ParseToolRotation(), ParseToolsElement(), ParseToolSpline(), ParseToolSplinePath(), ParseToolTrueDarts(), PointsCommonAttributes(), and SplinesCommonAttributes().
UpdateToolData()
void VPattern::UpdateToolData (const quint32 & id, VContainer * data) virtual
UpdateToolData update tool in list tools.
Parameters
id tool id.
data container with variables.
Implements VAbstractPattern.
Definition at line 347 of file vpattern.cpp.
References data, SCASSERT, VAbstractPattern::ToolExists(), and VAbstractPattern::tools.
Member Data Documentation
AttrReadOnly
const QString VPattern::AttrReadOnly = QStringLiteral("readOnly") static
Definition at line 122 of file vpattern.h.
Referenced by isReadOnly(), and SetReadOnly().
data
VContainer* VPattern::data private
Definition at line 133 of file vpattern.h.
Referenced by EvalFormula(), GenerateLabel(), GenerateSuffix(), LiteParseIncrements(), ParseAnchorPoint(), parseDraftBlockElement(), ParseIncrementsElement(), parseIntersectXYTool(), ParseLineElement(), ParseNodeArc(), ParseNodeEllipticalArc(), ParseNodePoint(), ParseNodeSpline(), ParseNodeSplinePath(), ParseOldToolSpline(), ParseOldToolSplinePath(), ParsePathElement(), parsePieceElement(), parsePieceNodes(), ParseToolAlongLine(), ParseToolArc(), ParseToolArcWithLength(), ParseToolBasePoint(), ParseToolBisector(), ParseToolCubicBezier(), ParseToolCubicBezierPath(), ParseToolCurveIntersectAxis(), ParseToolCutArc(), ParseToolCutSpline(), ParseToolCutSplinePath(), ParseToolEllipticalArc(), ParseToolEndLine(), ParseToolHeight(), ParseToolLineIntersect(), ParseToolLineIntersectAxis(), ParseToolMirrorByAxis(), ParseToolMirrorByLine(), ParseToolMove(), ParseToolNormal(), ParseToolPointFromArcAndTangent(), ParseToolPointFromCircleAndTangent(), ParseToolPointOfContact(), ParseToolPointOfIntersectionArcs(), ParseToolPointOfIntersectionCircles(), ParseToolPointOfIntersectionCurves(), ParseToolRotation(), ParseToolsElement(), ParseToolShoulderPoint(), ParseToolSpline(), ParseToolSplinePath(), ParseToolTriangle(), ParseToolTrueDarts(), PrepareForParse(), setCurrentData(), and UpdateToolData().
draftScene
VMainGraphicsScene* VPattern::draftScene private
mode current draw mode.
Definition at line 135 of file vpattern.h.
Referenced by LiteParseTree(), Parse(), ParseDrawMode(), PrepareForParse(), and VPattern().
mode
Draw* VPattern::mode private
data container with data.
Definition at line 134 of file vpattern.h.
Referenced by ParseDrawMode(), and setCurrentData().
pieceScene
VMainGraphicsScene* VPattern::pieceScene private
Definition at line 136 of file vpattern.h.
Referenced by LiteParseTree(), Parse(), ParseDrawMode(), ParseNodePoint(), parsePieceElement(), PrepareForParse(), and VPattern().
The documentation for this class was generated from the following files:
src/app/seamly2d/xml/vpattern.h
src/app/seamly2d/xml/vpattern.cpp