Seamly2D: VisToolPointOfIntersectionCurves Class Reference
VisToolPointOfIntersectionCurves Class Reference
#include <vistoolpointofintersectioncurves.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolPointOfIntersectionCurves) }
Public Types inherited from VisPath
enum { Type = UserType + static_cast<int>(Vis::Path) }
Public Types inherited from VCurvePathItem
enum { Type = UserType + static_cast<int>(Vis::CurvePathItem) }
Public Member Functions
VisToolPointOfIntersectionCurves (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolPointOfIntersectionCurves () Q_DECL_EQ_DEFAULT
virtual void RefreshGeometry () Q_DECL_OVERRIDE
virtual void VisualMode (const quint32 &id) Q_DECL_OVERRIDE
void setObject2Id (const quint32 &value)
void setVCrossPoint (const VCrossCurvesPoint &value)
void setHCrossPoint (const HCrossCurvesPoint &value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisPath
VisPath (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisPath ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VCurvePathItem
VCurvePathItem (QGraphicsItem *parent=nullptr)
virtual ~VCurvePathItem ()=default
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
void SetDirectionArrows (const QVector< QPair< QLineF, QLineF >> &arrows)
void SetPoints (const QVector< QPointF > &points)
Private Attributes
quint32 object2Id
VCrossCurvesPoint vCrossPoint
HCrossCurvesPoint hCrossPoint
VScaledEllipse * point
VCurvePathItem * visCurve2
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisPath
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
VSimplePoint * GetPoint (QVector< VSimplePoint * > &points, quint32 i, const QColor &color)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Protected Member Functions inherited from VCurvePathItem
virtual void ScalePenWidth ()
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 66 of file vistoolpointofintersectioncurves.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 81 of file vistoolpointofintersectioncurves.h.
Constructor & Destructor Documentation
VisToolPointOfIntersectionCurves()
VisToolPointOfIntersectionCurves::VisToolPointOfIntersectionCurves (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 71 of file vistoolpointofintersectioncurves.cpp.
References HighestPoint, Visualization::InitPoint(), LeftmostPoint, Visualization::mainColor, point, Visualization::supportColor, and visCurve2.
~VisToolPointOfIntersectionCurves()
virtual VisToolPointOfIntersectionCurves::~VisToolPointOfIntersectionCurves () virtual
Member Function Documentation
RefreshGeometry()
void VisToolPointOfIntersectionCurves::RefreshGeometry () virtual
Implements Visualization.
Definition at line 84 of file vistoolpointofintersectioncurves.cpp.
References Visualization::data, Visualization::DrawPath(), Visualization::DrawPoint(), VToolPointOfIntersectionCurves::FindPoint(), VContainer::GeometricObject(), hCrossPoint, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, object2Id, point, Visualization::supportColor, vCrossPoint, and visCurve2.
Referenced by VisualMode().
setHCrossPoint()
void VisToolPointOfIntersectionCurves::setHCrossPoint (const HCrossCurvesPoint & value)
Definition at line 131 of file vistoolpointofintersectioncurves.cpp.
References hCrossPoint.
setObject2Id()
void VisToolPointOfIntersectionCurves::setObject2Id (const quint32 & value)
Definition at line 119 of file vistoolpointofintersectioncurves.cpp.
References object2Id.
setVCrossPoint()
void VisToolPointOfIntersectionCurves::setVCrossPoint (const VCrossCurvesPoint & value)
Definition at line 125 of file vistoolpointofintersectioncurves.cpp.
References vCrossPoint.
type()
virtual int VisToolPointOfIntersectionCurves::type () const inline virtual
Reimplemented from VisPath.
Definition at line 80 of file vistoolpointofintersectioncurves.h.
References Type.
VisualMode()
void VisToolPointOfIntersectionCurves::VisualMode (const quint32 & id) virtual
Reimplemented from Visualization.
Definition at line 106 of file vistoolpointofintersectioncurves.cpp.
References VisPath::AddOnScene(), Visualization::object1Id, qApp, RefreshGeometry(), SCASSERT, and Visualization::scenePos.
Member Data Documentation
hCrossPoint
HCrossCurvesPoint VisToolPointOfIntersectionCurves::hCrossPoint private
Definition at line 86 of file vistoolpointofintersectioncurves.h.
Referenced by RefreshGeometry(), and setHCrossPoint().
object2Id
quint32 VisToolPointOfIntersectionCurves::object2Id private
Definition at line 84 of file vistoolpointofintersectioncurves.h.
Referenced by RefreshGeometry(), and setObject2Id().
point
VScaledEllipse* VisToolPointOfIntersectionCurves::point private
Definition at line 87 of file vistoolpointofintersectioncurves.h.
Referenced by RefreshGeometry(), and VisToolPointOfIntersectionCurves().
vCrossPoint
VCrossCurvesPoint VisToolPointOfIntersectionCurves::vCrossPoint private
Definition at line 85 of file vistoolpointofintersectioncurves.h.
Referenced by RefreshGeometry(), and setVCrossPoint().
visCurve2
VCurvePathItem* VisToolPointOfIntersectionCurves::visCurve2 private
Definition at line 88 of file vistoolpointofintersectioncurves.h.
Referenced by RefreshGeometry(), and VisToolPointOfIntersectionCurves().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/path/vistoolpointofintersectioncurves.h
src/libs/vtools/visualization/path/vistoolpointofintersectioncurves.cpp