Seamly2D: VPE::VFileProperty Class Reference
VPE::VFileProperty Class Reference
#include <vfileproperty.h>
Public Member Functions
VFileProperty (const QString &name)
virtual ~VFileProperty () Q_DECL_OVERRIDE
The destructor.
virtual void setFileFilters (const QString &filefilters)
Sets the file filters. The file filters have to be like the ones passed a QFileOpenDialog.
virtual QString getFileFilters () const
Returns the current file filters as a string.
virtual void setFile (const QString &file)
Set file.
virtual QString getFile () const
Get file.
virtual QVariant data (int column=DPC_Name, int role=Qt::DisplayRole) const Q_DECL_OVERRIDE
Get the data how it should be displayed.
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &options, const QAbstractItemDelegate *delegate) Q_DECL_OVERRIDE
Returns an editor widget, or NULL if it doesn't supply one.
virtual bool setEditorData (QWidget *editor) Q_DECL_OVERRIDE
Sets the property's data to the editor (returns false, if the standard delegate should do that)
virtual QVariant getEditorData (const QWidget *editor) const Q_DECL_OVERRIDE
Gets the data from the widget.
virtual void setSetting (const QString &key, const QVariant &value) Q_DECL_OVERRIDE
Sets the settings. Available settings:
virtual QVariant getSetting (const QString &key) const Q_DECL_OVERRIDE
Get the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QStringList getSettingKeys () const Q_DECL_OVERRIDE
Returns the list of keys of the property's settings.
virtual QString type () const Q_DECL_OVERRIDE
Returns a string containing the type of the property.
virtual Q_REQUIRED_RESULT VProperty * clone (bool include_children=true, VProperty *container=nullptr) const Q_DECL_OVERRIDE
Clones this property.
virtual bool isDirectory () const
Returns whether this is a file (false) or a directory (true)
virtual void setDirectory (bool is_directory)
Sets whether this is a file (false) or a directory (true)
Public Member Functions inherited from VPE::VProperty
VProperty (const QString &name, QVariant::Type type=QVariant::String)
Standard constructor, takes a name and a parent property as argument.
virtual ~VProperty () Q_DECL_OVERRIDE
Destructor.
virtual bool setData (const QVariant &data, int role=Qt::EditRole)
This is used by the model to set the data.
virtual bool paint (QPainter *, const QStyleOptionViewItem &, const QModelIndex &, const QAbstractItemDelegate *) const
This is called by the delegate when the property value is being drawn. The standard implementation doesn't do anything. If you reimplement this in a sub property, make sure to return true or the delegate will draw the item.
virtual Qt::ItemFlags flags (int column=DPC_Name) const
Returns item flags.
virtual void setValue (const QVariant &value)
Sets the value of the property.
virtual QVariant getValue () const
Returns the value of the property as a QVariant.
virtual QString serialize () const
Serializes the value to a string.
virtual void deserialize (const QString &value)
Deserializes the value from a string.
virtual void setName (const QString &name)
Sets the name of the property.
virtual QString getName () const
Gets the name of the property.
virtual void setDescription (const QString &desc)
Sets the name of the property.
virtual QString getDescription () const
Gets the name of the property.
virtual int addChild (VProperty *child)
Adds a child to this property.
virtual QList< VProperty * > & getChildren ()
Returns a reference to the list of children.
virtual const QList< VProperty * > & getChildren () const
Returns a reference to the list of children.
virtual VProperty * getChild (int row) const
Returns the child at a certain row.
virtual int getRowCount () const
Gets the number of children.
virtual VProperty * getParent () const
Gets the parent of this property.
virtual void setParent (VProperty *parent)
Sets the parent of this property.
virtual void removeChild (VProperty *child)
Removes a child from the children list, doesn't delete the child!
virtual int getChildRow (VProperty *child) const
Returns the row the child has.
virtual bool getUpdateParent () const
Returns whether the views have to update the parent of this property if it changes.
virtual bool getUpdateChildren () const
Returns whether the views have to update the children of this property if it changes.
virtual void setUpdateBehaviour (bool update_parent, bool update_children)
Sets whether the views should update Parents or children after this property changes.
virtual void setSettings (const QMap< QString, QVariant > &settings)
Sets the settings by calling the overloaded setSetting(const QString &key, const QVariant &value) for each item in the map.
virtual QMap< QString, QVariant > getSettings () const
Get the settings.
Property propertyType () const
void setPropertyType (const Property &type)
virtual void updateParent (const QVariant &value)
Additional Inherited Members
Public Types inherited from VPE::VProperty
enum DPC_DisplayColumn { DPC_Name = 0 , DPC_Data }
Public Slots inherited from VPE::VProperty
virtual void childValueChanged (const QVariant &value, int typeForParent)
Signals inherited from VPE::VProperty
void childChanged (const QVariant &value, int typeForParent)
Protected Member Functions inherited from VPE::VProperty
VProperty (VPropertyPrivate *d)
Protected constructor.
Protected Attributes inherited from VPE::VProperty
VPropertyPrivate * d_ptr
The protected structure holding the member variables (to assure binary compatibility)
Detailed Description
Definition at line 40 of file vfileproperty.h.
Constructor & Destructor Documentation
VFileProperty()
VPE::VFileProperty::VFileProperty (const QString & name) explicit
Definition at line 32 of file vfileproperty.cpp.
~VFileProperty()
VPE::VFileProperty::~VFileProperty () virtual
The destructor.
Definition at line 38 of file vfileproperty.cpp.
Member Function Documentation
clone()
VPE::VProperty * VPE::VFileProperty::clone (bool include_children = true, VProperty * container = nullptr) const virtual
Clones this property.
Parameters
include_children Indicates whether to also clone the children
container If a property is being passed here, no new VProperty is being created but instead it is tried to fill all the data into container. This can also be used when subclassing this function.
Returns
Returns the newly created property (or container, if it was not NULL)
Reimplemented from VPE::VProperty.
Definition at line 160 of file vfileproperty.cpp.
References VPE::VProperty::clone().
createEditor()
QWidget * VPE::VFileProperty::createEditor (QWidget * parent, const QStyleOptionViewItem & options, const QAbstractItemDelegate * delegate) virtual
Returns an editor widget, or NULL if it doesn't supply one.
Parameters
parent The widget to which the editor will be added as a child \options Render options \delegate A pointer to the QAbstractItemDelegate requesting the editor. This can be used to connect signals and slots.
Reimplemented from VPE::VProperty.
Definition at line 80 of file vfileproperty.cpp.
References VPE::VFileEditWidget::setDirectory(), VPE::VFileEditWidget::setFile(), and VPE::VFileEditWidget::setFilter().
data()
QVariant VPE::VFileProperty::data (int column = DPC_Name, int role = Qt::DisplayRole) const virtual
Get the data how it should be displayed.
Reimplemented from VPE::VProperty.
Definition at line 68 of file vfileproperty.cpp.
References VPE::VProperty::data().
getEditorData()
QVariant VPE::VFileProperty::getEditorData (const QWidget * editor) const virtual
Gets the data from the widget.
Reimplemented from VPE::VProperty.
Definition at line 113 of file vfileproperty.cpp.
References VPE::VFileEditWidget::getFile().
getFile()
QString VPE::VFileProperty::getFile () const virtual
Get file.
Definition at line 62 of file vfileproperty.cpp.
getFileFilters()
QString VPE::VFileProperty::getFileFilters () const virtual
Returns the current file filters as a string.
Definition at line 50 of file vfileproperty.cpp.
getSetting()
QVariant VPE::VFileProperty::getSetting (const QString & key) const virtual
Get the settings. This function has to be implemented in a subclass in order to have an effect.
Reimplemented from VPE::VProperty.
Definition at line 136 of file vfileproperty.cpp.
References VPE::VProperty::getSetting().
getSettingKeys()
QStringList VPE::VFileProperty::getSettingKeys () const virtual
Returns the list of keys of the property's settings.
Reimplemented from VPE::VProperty.
Definition at line 150 of file vfileproperty.cpp.
isDirectory()
bool VPE::VFileProperty::isDirectory () const virtual
Returns whether this is a file (false) or a directory (true)
Definition at line 165 of file vfileproperty.cpp.
setDirectory()
void VPE::VFileProperty::setDirectory (bool is_directory) virtual
Sets whether this is a file (false) or a directory (true)
Definition at line 171 of file vfileproperty.cpp.
setEditorData()
bool VPE::VFileProperty::setEditorData (QWidget * editor) virtual
Sets the property's data to the editor (returns false, if the standard delegate should do that)
Reimplemented from VPE::VProperty.
Definition at line 99 of file vfileproperty.cpp.
References VPE::VFileEditWidget::setFile().
setFile()
void VPE::VFileProperty::setFile (const QString & file) virtual
Set file.
Definition at line 56 of file vfileproperty.cpp.
setFileFilters()
void VPE::VFileProperty::setFileFilters (const QString & filefilters) virtual
Sets the file filters. The file filters have to be like the ones passed a QFileOpenDialog.
Definition at line 44 of file vfileproperty.cpp.
setSetting()
void VPE::VFileProperty::setSetting (const QString & key, const QVariant & value) virtual
Sets the settings. Available settings:
key: "FileFilters" - value: File filters in the same format the QFileDialog expects it
Reimplemented from VPE::VProperty.
Definition at line 124 of file vfileproperty.cpp.
type()
QString VPE::VFileProperty::type () const virtual
Returns a string containing the type of the property.
Reimplemented from VPE::VProperty.
Definition at line 155 of file vfileproperty.cpp.
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/plugins/vfileproperty.h
src/libs/vpropertyexplorer/plugins/vfileproperty.cpp