Seamly2D: VAbstractOperation Class Reference
VAbstractOperation Class Reference
#include <vabstractoperation.h>
Public Slots
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
void AllowPointHover (bool enabled)
void AllowPointSelecting (bool enabled)
void AllowPointLabelHover (bool enabled)
void AllowPointLabelSelecting (bool enabled)
void AllowSplineHover (bool enabled)
void AllowSplineSelecting (bool enabled)
void AllowSplinePathHover (bool enabled)
void AllowSplinePathSelecting (bool enabled)
void AllowArcHover (bool enabled)
void AllowArcSelecting (bool enabled)
void AllowElArcHover (bool enabled)
void AllowElArcSelecting (bool enabled)
virtual void ToolSelectionType (const SelectionType &type) Q_DECL_OVERRIDE
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
void ObjectSelected (bool selected, quint32 objId)
void deletePoint ()
void pointNamePositionChanged (const QPointF &pos, quint32 labelId)
virtual void updatePointNameVisibility (quint32 id, bool visible) Q_DECL_OVERRIDE
Public Slots inherited from VDrawTool
virtual void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Public Member Functions
virtual ~VAbstractOperation () Q_DECL_EQ_DEFAULT
virtual QString getTagName () const Q_DECL_OVERRIDE
QString Suffix () const
void setSuffix (const QString &suffix)
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) Q_DECL_OVERRIDE
virtual bool isPointNameVisible (quint32 id) const Q_DECL_OVERRIDE
virtual void setPointNameVisiblity (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void setPointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual void setLineWeight (const QString &value)
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
virtual void ShowVisualization (bool show)=0
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Static Public Member Functions
static void ExtractData (const QDomElement &domElement, QVector< SourceItem > &source, QVector< DestinationItem > &destination)
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString TagItem = QStringLiteral("item")
static const QString TagSource = QStringLiteral("source")
static const QString TagDestination = QStringLiteral("destination")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Member Functions
VAbstractOperation (VAbstractPattern *doc, VContainer *data, quint32 id, const QString &suffix, const QVector< SourceItem > &source, const QVector< DestinationItem > &destination, QGraphicsItem *parent=nullptr)
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
virtual void ReadToolAttributes (const QDomElement &domElement) Q_DECL_OVERRIDE
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
void updatePointNamePosition (quint32 id, const QPointF &pos)
void SaveSourceDestination (QDomElement &tag)
template<typename T >
void ShowToolVisualization (bool show)
void InitCurve (quint32 id, VContainer *data, GOType curveType, SceneObject sceneType)
void InitOperatedObjects ()
QString complexPointToolTip (quint32 itemId) const
QString complexCurveToolTip (quint32 itemId) const
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialog (QDomElement &domElement)=0
SaveDialog save options into file after change in dialog.
virtual void SaveDialogChange () Q_DECL_FINAL
void SaveOption (QSharedPointer< VGObject > &obj)
virtual QString makeToolTip () const
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
virtual void updatePointNameVisibility (quint32 id, bool visible)
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VInteractiveTool
virtual void setDialog ()
setDialog set dialog when user want change tool option.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void RemoveReferens ()
RemoveReferens decrement value of reference.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
virtual void SetVisualization ()=0
virtual void ToolCreation (const Source &typeCreation)
Static Protected Member Functions
template<typename T >
static void initOperationToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes
QString suffix
QVector< SourceItem > source
QVector< DestinationItem > destination
QMap< quint32, VAbstractSimple * > operatedObjects
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Private Member Functions
void AllowCurveHover (bool enabled, GOType type)
void AllowCurveSelecting (bool enabled, GOType type)
Additional Inherited Members
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Detailed Description
Definition at line 93 of file vabstractoperation.h.
Constructor & Destructor Documentation
~VAbstractOperation()
virtual VAbstractOperation::~VAbstractOperation () virtual
VAbstractOperation()
VAbstractOperation::VAbstractOperation (VAbstractPattern * doc, VContainer * data, quint32 id, const QString & suffix, const QVector< SourceItem > & source, const QVector< DestinationItem > & destination, QGraphicsItem * parent = nullptr) protected
Definition at line 548 of file vabstractoperation.cpp.
Member Function Documentation
AddToFile()
void VAbstractOperation::AddToFile () protected virtual
AddToFile add tag with Information about tool into file.
Reimplemented from VDrawTool.
Definition at line 561 of file vabstractoperation.cpp.
References VDrawTool::AddToCalculation(), VAbstractTool::doc, VContainer::GetFakeGObject(), getTagName(), VAbstractTool::m_id, and SaveOptions().
AllowArcHover
void VAbstractOperation::AllowArcHover (bool enabled) slot
Definition at line 462 of file vabstractoperation.cpp.
References AllowCurveHover(), and Arc.
AllowArcSelecting
void VAbstractOperation::AllowArcSelecting (bool enabled) slot
Definition at line 468 of file vabstractoperation.cpp.
References AllowCurveSelecting(), and Arc.
AllowCurveHover()
void VAbstractOperation::AllowCurveHover (bool enabled, GOType type) private
Definition at line 645 of file vabstractoperation.cpp.
References VAbstractSimple::GetType(), operatedObjects, Point, and SCASSERT.
Referenced by AllowArcHover(), AllowElArcHover(), AllowSplineHover(), and AllowSplinePathHover().
AllowCurveSelecting()
void VAbstractOperation::AllowCurveSelecting (bool enabled, GOType type) private
Definition at line 664 of file vabstractoperation.cpp.
References VAbstractSimple::GetType(), operatedObjects, Point, and SCASSERT.
Referenced by AllowArcSelecting(), AllowElArcSelecting(), AllowSplinePathSelecting(), and AllowSplineSelecting().
AllowElArcHover
void VAbstractOperation::AllowElArcHover (bool enabled) slot
Definition at line 474 of file vabstractoperation.cpp.
References AllowCurveHover(), and EllipticalArc.
AllowElArcSelecting
void VAbstractOperation::AllowElArcSelecting (bool enabled) slot
Definition at line 480 of file vabstractoperation.cpp.
References AllowCurveSelecting(), and EllipticalArc.
AllowHover
void VAbstractOperation::AllowHover (bool enabled) virtual slot
Definition at line 310 of file vabstractoperation.cpp.
References operatedObjects, Point, and SCASSERT.
AllowPointHover
void VAbstractOperation::AllowPointHover (bool enabled) slot
Definition at line 370 of file vabstractoperation.cpp.
References operatedObjects, Point, and SCASSERT.
AllowPointLabelHover
void VAbstractOperation::AllowPointLabelHover (bool enabled) slot
Definition at line 402 of file vabstractoperation.cpp.
References VSimplePoint::allowTextHover(), operatedObjects, Point, and SCASSERT.
AllowPointLabelSelecting
void VAbstractOperation::AllowPointLabelSelecting (bool enabled) slot
Definition at line 418 of file vabstractoperation.cpp.
References VSimplePoint::allowTextSelectable(), operatedObjects, Point, and SCASSERT.
AllowPointSelecting
void VAbstractOperation::AllowPointSelecting (bool enabled) slot
Definition at line 386 of file vabstractoperation.cpp.
References operatedObjects, Point, and SCASSERT.
AllowSelecting
void VAbstractOperation::AllowSelecting (bool enabled) virtual slot
Definition at line 332 of file vabstractoperation.cpp.
References operatedObjects, Point, and SCASSERT.
AllowSplineHover
void VAbstractOperation::AllowSplineHover (bool enabled) slot
Definition at line 434 of file vabstractoperation.cpp.
References AllowCurveHover(), CubicBezier, and Spline.
AllowSplinePathHover
void VAbstractOperation::AllowSplinePathHover (bool enabled) slot
Definition at line 448 of file vabstractoperation.cpp.
References AllowCurveHover(), CubicBezierPath, and SplinePath.
AllowSplinePathSelecting
void VAbstractOperation::AllowSplinePathSelecting (bool enabled) slot
Definition at line 455 of file vabstractoperation.cpp.
References AllowCurveSelecting(), CubicBezierPath, and SplinePath.
AllowSplineSelecting
void VAbstractOperation::AllowSplineSelecting (bool enabled) slot
Definition at line 441 of file vabstractoperation.cpp.
References AllowCurveSelecting(), CubicBezier, and Spline.
complexCurveToolTip()
QString VAbstractOperation::complexCurveToolTip (quint32 itemId) const protected
Definition at line 758 of file vabstractoperation.cpp.
References VDataTool::data, VContainer::GeometricObject(), VDrawTool::makeToolTip(), qApp, and UnitsToStr().
Referenced by FullUpdateFromFile(), and InitCurve().
complexPointToolTip()
QString VAbstractOperation::complexPointToolTip (quint32 itemId) const protected
Definition at line 745 of file vabstractoperation.cpp.
References VDataTool::data, VContainer::GeometricObject(), and VDrawTool::makeToolTip().
Referenced by FullUpdateFromFile(), and InitOperatedObjects().
deletePoint
void VAbstractOperation::deletePoint () slot
Definition at line 534 of file vabstractoperation.cpp.
References VAbstractTool::deleteTool().
Referenced by InitCurve(), and InitOperatedObjects().
Disable
void VAbstractOperation::Disable (bool disable, const QString & draftBlockName) virtual slot
Definition at line 503 of file vabstractoperation.cpp.
References VDrawTool::CorrectDisable(), operatedObjects, Point, SCASSERT, and VSimplePoint::SetEnabled().
EnableToolMove
void VAbstractOperation::EnableToolMove (bool move) virtual slot
Definition at line 354 of file vabstractoperation.cpp.
References VSimplePoint::EnableToolMove(), operatedObjects, Point, and SCASSERT.
ExtractData()
void VAbstractOperation::ExtractData (const QDomElement & domElement, QVector< SourceItem > & source, QVector< DestinationItem > & destination) static
Definition at line 236 of file vabstractoperation.cpp.
References SourceItem::alias, AttrAlias, AttrColor, AttrIdObject, AttrLineType, AttrMx, AttrMy, AttrShowPointName, SourceItem::color, destination, VDomDocument::getParameterBool(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrEmptyString(), VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), SourceItem::id, DestinationItem::id, SourceItem::lineType, LineTypeSolidLine, DestinationItem::mx, DestinationItem::my, NULL_ID_STR, qApp, DestinationItem::showPointName, source, TagDestination, TagSource, and trueStr.
Referenced by VPattern::ParseToolMirrorByAxis(), VPattern::ParseToolMirrorByLine(), VPattern::ParseToolMove(), VPattern::ParseToolRotation(), and ReadToolAttributes().
FullUpdateFromFile
void VAbstractOperation::FullUpdateFromFile () virtual slot
Definition at line 284 of file vabstractoperation.cpp.
References complexCurveToolTip(), complexPointToolTip(), VDataTool::data, operatedObjects, Point, VDrawTool::ReadAttributes(), VSimpleCurve::RefreshGeometry(), VScenePoint::refreshPointGeometry(), SCASSERT, and VAbstractTool::SetVisualization().
getTagName()
QString VAbstractOperation::getTagName () const virtual
Implements VAbstractTool.
Definition at line 77 of file vabstractoperation.cpp.
References VAbstractPattern::TagOperation.
Referenced by AddToFile().
GroupVisibility()
void VAbstractOperation::GroupVisibility (quint32 object, bool visible) virtual
Implements VDataTool.
Definition at line 98 of file vabstractoperation.cpp.
References VAbstractSimple::GetType(), operatedObjects, Point, and SCASSERT.
InitCurve()
void VAbstractOperation::InitCurve (quint32 id, VContainer * data, GOType curveType, SceneObject sceneType) protected
Definition at line 623 of file vabstractoperation.cpp.
References VSimpleCurve::Choosed(), VAbstractTool::chosenTool(), complexCurveToolTip(), VDataTool::data, VAbstractSimple::Delete(), deletePoint(), VContainer::GeometricObject(), ObjectSelected(), operatedObjects, VSimpleCurve::Selected(), VAbstractSimple::showContextMenu(), and VDrawTool::showContextMenu().
Referenced by InitOperatedObjects().
InitOperatedObjects()
void VAbstractOperation::InitOperatedObjects () protected
Definition at line 683 of file vabstractoperation.cpp.
References AllCurves, Arc, VSimplePoint::Choosed(), VAbstractTool::chosenTool(), complexPointToolTip(), CubicBezier, CubicBezierPath, Curve, VDataTool::data, VAbstractSimple::Delete(), deletePoint(), destination, ElArc, EllipticalArc, VContainer::GetGObject(), DestinationItem::id, InitCurve(), VSimplePoint::nameChangedPosition(), ObjectSelected(), operatedObjects, Path, Point, pointNamePositionChanged(), VScenePoint::refreshPointGeometry(), VSimplePoint::Selected(), VAbstractSimple::SetType(), VAbstractSimple::showContextMenu(), VDrawTool::showContextMenu(), Spline, SplinePath, and Unknown.
Referenced by VToolMirrorByAxis::VToolMirrorByAxis(), VToolMirrorByLine::VToolMirrorByLine(), VToolMove::VToolMove(), and VToolRotation::VToolRotation().
initOperationToolConnections()
template<typename T > void VAbstractOperation::initOperationToolConnections (VMainGraphicsScene * scene, T * tool) static protected
Definition at line 223 of file vabstractoperation.h.
References VMainGraphicsScene::EnableArcItemHover(), VMainGraphicsScene::EnableArcItemSelection(), VMainGraphicsScene::EnableElArcItemHover(), VMainGraphicsScene::EnableElArcItemSelection(), VMainGraphicsScene::EnablePointItemHover(), VMainGraphicsScene::EnablePointItemSelection(), VMainGraphicsScene::EnableSplineItemHover(), VMainGraphicsScene::EnableSplineItemSelection(), VMainGraphicsScene::EnableSplinePathItemHover(), VMainGraphicsScene::EnableSplinePathItemSelection(), VMainGraphicsScene::enableTextItemHover(), VMainGraphicsScene::enableTextItemSelection(), VDrawTool::InitDrawToolConnections(), and SCASSERT.
Referenced by VToolRotation::Create(), VToolMirrorByLine::Create(), VToolMirrorByAxis::Create(), and VToolMove::Create().
isPointNameVisible()
bool VAbstractOperation::isPointNameVisible (quint32 id) const virtual
Reimplemented from VDrawTool.
Definition at line 127 of file vabstractoperation.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractSimple::GetType(), operatedObjects, and Point.
ObjectSelected
void VAbstractOperation::ObjectSelected (bool selected, quint32 objId) slot
Definition at line 528 of file vabstractoperation.cpp.
References VDrawTool::ChangedToolSelection(), and VAbstractTool::m_id.
Referenced by InitCurve(), and InitOperatedObjects().
paint()
void VAbstractOperation::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
Definition at line 119 of file vabstractoperation.cpp.
pointNamePositionChanged
void VAbstractOperation::pointNamePositionChanged (const QPointF & pos, quint32 labelId) slot
Definition at line 201 of file vabstractoperation.cpp.
References VAbstractSimple::GetType(), operatedObjects, Point, SCASSERT, and updatePointNamePosition().
Referenced by InitOperatedObjects().
ReadToolAttributes()
void VAbstractOperation::ReadToolAttributes (const QDomElement & domElement) protected virtual
Implements VDrawTool.
Reimplemented in VToolRotation, VToolMove, VToolMirrorByLine, and VToolMirrorByAxis.
Definition at line 570 of file vabstractoperation.cpp.
References AttrSuffix, destination, VAbstractTool::doc, ExtractData(), VDomDocument::GetParametrString(), source, and suffix.
Referenced by VToolMove::ReadToolAttributes().
SaveOptions()
void VAbstractOperation::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VDrawTool.
Reimplemented in VToolRotation, VToolMove, VToolMirrorByLine, and VToolMirrorByAxis.
Definition at line 577 of file vabstractoperation.cpp.
References AttrSuffix, VAbstractTool::doc, VDrawTool::SaveOptions(), SaveSourceDestination(), VDomDocument::SetAttribute(), and suffix.
Referenced by AddToFile(), and VToolMove::SaveOptions().
SaveSourceDestination()
void VAbstractOperation::SaveSourceDestination (QDomElement & tag) protected
Definition at line 587 of file vabstractoperation.cpp.
References AttrAlias, AttrColor, AttrIdObject, AttrLineType, AttrMx, AttrMy, AttrShowPointName, destination, VAbstractTool::doc, qApp, VDomDocument::RemoveAllChildren(), VDomDocument::SetAttribute(), source, TagDestination, TagItem, TagSource, and VFuzzyComparePossibleNulls().
Referenced by VToolMove::SaveDialog(), VToolMirrorByAxis::SaveOptions(), VToolMirrorByLine::SaveOptions(), SaveOptions(), and VToolRotation::SaveOptions().
setPointNamePosition()
void VAbstractOperation::setPointNamePosition (quint32 id, const QPointF & pos) virtual
Reimplemented from VAbstractTool.
Definition at line 178 of file vabstractoperation.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractSimple::GetType(), VMainGraphicsView::NewSceneRect(), operatedObjects, Point, qApp, VScenePoint::refreshPointGeometry(), and SCASSERT.
setPointNameVisiblity()
void VAbstractOperation::setPointNameVisiblity (quint32 id, bool visible) virtual
Reimplemented from VAbstractTool.
Definition at line 142 of file vabstractoperation.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractSimple::GetType(), operatedObjects, Point, VScenePoint::refreshPointGeometry(), and SCASSERT.
setSuffix()
void VAbstractOperation::setSuffix (const QString & suffix)
Definition at line 89 of file vabstractoperation.cpp.
References VContainer::GetFakeGObject(), VAbstractTool::m_id, VDrawTool::SaveOption(), and suffix.
ShowToolVisualization()
template<typename T > void VAbstractOperation::ShowToolVisualization (bool show) protected
Definition at line 198 of file vabstractoperation.h.
References VAbstractTool::SetVisualization(), and VAbstractTool::vis.
Suffix()
QString VAbstractOperation::Suffix () const
Definition at line 83 of file vabstractoperation.cpp.
References suffix.
Referenced by VToolOptionsPropertyBrowser::updateOptionsToolMirrorByAxis(), VToolOptionsPropertyBrowser::updateOptionsToolMirrorByLine(), VToolOptionsPropertyBrowser::updateOptionsToolMove(), and VToolOptionsPropertyBrowser::updateOptionsToolRotation().
ToolSelectionType
void VAbstractOperation::ToolSelectionType (const SelectionType & type) virtual slot
Definition at line 486 of file vabstractoperation.cpp.
References operatedObjects, Point, SCASSERT, VAbstractTool::selectionType, VAbstractTool::ToolSelectionType(), and VSimplePoint::ToolSelectionType().
updatePointNamePosition()
void VAbstractOperation::updatePointNamePosition (quint32 id, const QPointF & pos) protected
Definition at line 216 of file vabstractoperation.cpp.
References destination, VAbstractTool::doc, VAbstractSimple::GetType(), VAbstractTool::m_id, DestinationItem::mx, DestinationItem::my, operatedObjects, Point, and qApp.
Referenced by pointNamePositionChanged().
updatePointNameVisibility
void VAbstractOperation::updatePointNameVisibility (quint32 id, bool visible) virtual slot
Definition at line 159 of file vabstractoperation.cpp.
References destination, VAbstractTool::doc, VAbstractSimple::GetType(), VAbstractTool::m_id, operatedObjects, Point, qApp, and DestinationItem::showPointName.
Member Data Documentation
destination
QVector<DestinationItem> VAbstractOperation::destination protected
Definition at line 159 of file vabstractoperation.h.
Referenced by VToolRotation::Create(), VToolMirrorByLine::Create(), VToolMirrorByAxis::Create(), VToolMove::Create(), ExtractData(), InitOperatedObjects(), ReadToolAttributes(), SaveSourceDestination(), updatePointNamePosition(), and updatePointNameVisibility().
operatedObjects
QMap<quint32, VAbstractSimple *> VAbstractOperation::operatedObjects protected
Definition at line 160 of file vabstractoperation.h.
Referenced by AllowCurveHover(), AllowCurveSelecting(), AllowHover(), AllowPointHover(), AllowPointLabelHover(), AllowPointLabelSelecting(), AllowPointSelecting(), AllowSelecting(), Disable(), EnableToolMove(), FullUpdateFromFile(), GroupVisibility(), InitCurve(), InitOperatedObjects(), isPointNameVisible(), pointNamePositionChanged(), setPointNamePosition(), setPointNameVisiblity(), ToolSelectionType(), updatePointNamePosition(), and updatePointNameVisibility().
source
QVector<SourceItem> VAbstractOperation::source protected
Definition at line 158 of file vabstractoperation.h.
Referenced by VToolMirrorByAxis::Create(), VToolMirrorByLine::Create(), VToolMove::Create(), VToolRotation::Create(), VAbstractMirror::createDestination(), ExtractData(), ReadToolAttributes(), VToolMove::SaveDialog(), SaveSourceDestination(), VToolMove::setDialog(), VToolMirrorByAxis::SetVisualization(), VToolMirrorByLine::SetVisualization(), VToolMove::SetVisualization(), and VToolRotation::SetVisualization().
suffix
QString VAbstractOperation::suffix protected
Definition at line 157 of file vabstractoperation.h.
Referenced by VToolMirrorByAxis::Create(), VToolMirrorByLine::Create(), VToolMove::Create(), VToolRotation::Create(), VAbstractMirror::createArc(), VToolRotation::createArc(), VToolMove::createArc(), VAbstractMirror::createCurve(), VToolRotation::createCurve(), VToolMove::createCurve(), VAbstractMirror::createCurveWithSegments(), VToolRotation::createCurveWithSegments(), VToolMove::createCurveWithSegments(), VAbstractMirror::createDestination(), VAbstractMirror::createItem(), VToolRotation::createItem(), VToolMove::createItem(), VAbstractMirror::createPoint(), VToolRotation::createPoint(), VToolMove::createPoint(), VToolMirrorByAxis::ReadToolAttributes(), VToolMirrorByLine::ReadToolAttributes(), ReadToolAttributes(), VToolMove::ReadToolAttributes(), VToolRotation::ReadToolAttributes(), VToolMirrorByAxis::SaveOptions(), VToolMirrorByLine::SaveOptions(), SaveOptions(), VToolMove::SaveOptions(), VToolRotation::SaveOptions(), VToolMirrorByAxis::setDialog(), VToolMirrorByLine::setDialog(), VToolMove::setDialog(), VToolRotation::setDialog(), setSuffix(), Suffix(), VAbstractMirror::updateArc(), VToolRotation::updateArc(), VToolMove::updateArc(), VAbstractMirror::updateCurve(), VToolRotation::updateCurve(), VToolMove::updateCurve(), VAbstractMirror::updateCurveWithSegments(), VToolRotation::updateCurveWithSegments(), VToolMove::updateCurveWithSegments(), VAbstractMirror::updateItem(), VToolRotation::updateItem(), VToolMove::updateItem(), VAbstractMirror::updatePoint(), VToolRotation::updatePoint(), and VToolMove::updatePoint().
TagDestination
const QString VAbstractOperation::TagDestination = QStringLiteral("destination") static
Definition at line 105 of file vabstractoperation.h.
Referenced by ExtractData(), VUndoCommand::getDestinationObject(), and SaveSourceDestination().
TagItem
const QString VAbstractOperation::TagItem = QStringLiteral("item") static
Definition at line 103 of file vabstractoperation.h.
Referenced by SaveSourceDestination().
TagSource
const QString VAbstractOperation::TagSource = QStringLiteral("source") static
Definition at line 104 of file vabstractoperation.h.
Referenced by ExtractData(), and SaveSourceDestination().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/operation/vabstractoperation.h
src/libs/vtools/tools/drawTools/operation/vabstractoperation.cpp