Seamly2D: VPE::DoubleSpinboxProperty Class Reference
VPE::DoubleSpinboxProperty Class Reference
Class for holding a double property.
#include <vnumberproperty.h>
Public Member Functions
DoubleSpinboxProperty (const QString &name, const QMap< QString, QVariant > &settings)
DoubleSpinboxProperty (const QString &name)
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &options, const QAbstractItemDelegate *delegate)
Returns an editor widget, or NULL if it doesn't supply one.
virtual QVariant getEditorData (const QWidget *editor) const
Gets the data from the widget.
virtual void setSetting (const QString &key, const QVariant &value)
Sets the settings. Available settings:
virtual QVariant getSetting (const QString &key) const
Get the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QStringList getSettingKeys () const
Returns the list of keys of the property's settings.
virtual QString type () const
Returns a string containing the type of the property.
virtual VProperty * clone (bool include_children=true, VProperty *container=NULL) const
Clones this property.
Public Member Functions inherited from VPE::SpinboxProperty
SpinboxProperty (const QString &name, const QMap< QString, QVariant > &settings)
SpinboxProperty (const QString &name)
Public Member Functions inherited from VPE::VProperty
VProperty (const QString &name, QVariant::Type type=QVariant::String)
Standard constructor, takes a name and a parent property as argument.
virtual ~VProperty () Q_DECL_OVERRIDE
Destructor.
virtual QVariant data (int column=DPC_Name, int role=Qt::DisplayRole) const
Get the data how it should be displayed.
virtual bool setData (const QVariant &data, int role=Qt::EditRole)
This is used by the model to set the data.
virtual bool paint (QPainter *, const QStyleOptionViewItem &, const QModelIndex &, const QAbstractItemDelegate *) const
This is called by the delegate when the property value is being drawn. The standard implementation doesn't do anything. If you reimplement this in a sub property, make sure to return true or the delegate will draw the item.
virtual bool setEditorData (QWidget *editor)
Sets the property's data to the editor (returns false, if the standard delegate should do that)
virtual Qt::ItemFlags flags (int column=DPC_Name) const
Returns item flags.
virtual void setValue (const QVariant &value)
Sets the value of the property.
virtual QVariant getValue () const
Returns the value of the property as a QVariant.
virtual QString serialize () const
Serializes the value to a string.
virtual void deserialize (const QString &value)
Deserializes the value from a string.
virtual void setName (const QString &name)
Sets the name of the property.
virtual QString getName () const
Gets the name of the property.
virtual void setDescription (const QString &desc)
Sets the name of the property.
virtual QString getDescription () const
Gets the name of the property.
virtual int addChild (VProperty *child)
Adds a child to this property.
virtual QList< VProperty * > & getChildren ()
Returns a reference to the list of children.
virtual const QList< VProperty * > & getChildren () const
Returns a reference to the list of children.
virtual VProperty * getChild (int row) const
Returns the child at a certain row.
virtual int getRowCount () const
Gets the number of children.
virtual VProperty * getParent () const
Gets the parent of this property.
virtual void setParent (VProperty *parent)
Sets the parent of this property.
virtual void removeChild (VProperty *child)
Removes a child from the children list, doesn't delete the child!
virtual int getChildRow (VProperty *child) const
Returns the row the child has.
virtual bool getUpdateParent () const
Returns whether the views have to update the parent of this property if it changes.
virtual bool getUpdateChildren () const
Returns whether the views have to update the children of this property if it changes.
virtual void setUpdateBehaviour (bool update_parent, bool update_children)
Sets whether the views should update Parents or children after this property changes.
virtual void setSettings (const QMap< QString, QVariant > &settings)
Sets the settings by calling the overloaded setSetting(const QString &key, const QVariant &value) for each item in the map.
virtual QMap< QString, QVariant > getSettings () const
Get the settings.
Property propertyType () const
void setPropertyType (const Property &type)
virtual void updateParent (const QVariant &value)
Protected Attributes
int Precision
Number of decimals after the decimal point.
Protected Attributes inherited from VPE::SpinboxProperty
double minValue
double maxValue
double singleStep
Protected Attributes inherited from VPE::VProperty
VPropertyPrivate * d_ptr
The protected structure holding the member variables (to assure binary compatibility)
Static Protected Attributes
static const double StandardPrecision = 5
Static Protected Attributes inherited from VPE::SpinboxProperty
static const int StandardMin = -1000000
static const int StandardMax = 1000000
Additional Inherited Members
Public Types inherited from VPE::VProperty
enum DPC_DisplayColumn { DPC_Name = 0 , DPC_Data }
Public Slots inherited from VPE::SpinboxProperty
void valueChanged (int i)
Public Slots inherited from VPE::VProperty
virtual void childValueChanged (const QVariant &value, int typeForParent)
Signals inherited from VPE::VProperty
void childChanged (const QVariant &value, int typeForParent)
Protected Member Functions inherited from VPE::VProperty
VProperty (VPropertyPrivate *d)
Protected constructor.
Detailed Description
Class for holding a double property.
Definition at line 97 of file vnumberproperty.h.
Constructor & Destructor Documentation
DoubleSpinboxProperty() [1/2]
VPE::DoubleSpinboxProperty::DoubleSpinboxProperty (const QString & name, const QMap< QString, QVariant > & settings)
Definition at line 148 of file vnumberproperty.cpp.
References VPE::VProperty::d_ptr, VPE::VPropertyPrivate::PropertyVariantType, VPE::VProperty::setSettings(), and VPE::VPropertyPrivate::VariantValue.
DoubleSpinboxProperty() [2/2]
VPE::DoubleSpinboxProperty::DoubleSpinboxProperty (const QString & name) explicit
Definition at line 158 of file vnumberproperty.cpp.
References VPE::VProperty::d_ptr, VPE::VPropertyPrivate::PropertyVariantType, and VPE::VPropertyPrivate::VariantValue.
Member Function Documentation
clone()
VPE::VProperty * VPE::DoubleSpinboxProperty::clone (bool include_children = true, VProperty * container = NULL) const virtual
Clones this property.
Parameters
include_children Indicates whether to also clone the children
container If a property is being passed here, no new VProperty is being created but instead it is tried to fill all the data into container. This can also be used when subclassing this function.
Returns
Returns the newly created property (or container, if it was not NULL)
Reimplemented from VPE::SpinboxProperty.
Definition at line 252 of file vnumberproperty.cpp.
References VPE::SpinboxProperty::clone().
createEditor()
QWidget * VPE::DoubleSpinboxProperty::createEditor (QWidget * parent, const QStyleOptionViewItem & options, const QAbstractItemDelegate * delegate) virtual
Returns an editor widget, or NULL if it doesn't supply one.
Parameters
parent The widget to which the editor will be added as a child \options Render options \delegate A pointer to the QAbstractItemDelegate requesting the editor. This can be used to connect signals and slots.
Reimplemented from VPE::SpinboxProperty.
Definition at line 168 of file vnumberproperty.cpp.
References VPE::VProperty::d_ptr, VPE::VPropertyPrivate::editor, and VPE::SpinboxProperty::valueChanged().
getEditorData()
QVariant VPE::DoubleSpinboxProperty::getEditorData (const QWidget * editor) const virtual
Gets the data from the widget.
Reimplemented from VPE::SpinboxProperty.
Definition at line 189 of file vnumberproperty.cpp.
getSetting()
QVariant VPE::DoubleSpinboxProperty::getSetting (const QString & key) const virtual
Get the settings. This function has to be implemented in a subclass in order to have an effect.
Reimplemented from VPE::SpinboxProperty.
Definition at line 220 of file vnumberproperty.cpp.
References VPE::VProperty::getSetting().
getSettingKeys()
QStringList VPE::DoubleSpinboxProperty::getSettingKeys () const virtual
Returns the list of keys of the property's settings.
Reimplemented from VPE::SpinboxProperty.
Definition at line 242 of file vnumberproperty.cpp.
setSetting()
void VPE::DoubleSpinboxProperty::setSetting (const QString & key, const QVariant & value) virtual
Sets the settings. Available settings:
key: "Min" - value: Minimum number as integer key: "Max" - value: Maximum number as integer
Reimplemented from VPE::SpinboxProperty.
Definition at line 200 of file vnumberproperty.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolNormal().
type()
QString VPE::DoubleSpinboxProperty::type () const virtual
Returns a string containing the type of the property.
Reimplemented from VPE::SpinboxProperty.
Definition at line 247 of file vnumberproperty.cpp.
Member Data Documentation
Precision
int VPE::DoubleSpinboxProperty::Precision protected
Number of decimals after the decimal point.
Definition at line 140 of file vnumberproperty.h.
StandardPrecision
const double VPE::DoubleSpinboxProperty::StandardPrecision = 5 static protected
Definition at line 142 of file vnumberproperty.h.
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/plugins/vnumberproperty.h
src/libs/vpropertyexplorer/plugins/vnumberproperty.cpp