Seamly2D: VToolRotation Class Reference
VToolRotation Class Reference
#include <vtoolrotation.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::Rotation) }
Public Member Functions
virtual ~VToolRotation () Q_DECL_EQ_DEFAULT
virtual void setDialog () Q_DECL_OVERRIDE
setDialog set dialog when user want change tool option.
virtual int type () const Q_DECL_OVERRIDE
QString getOriginPointName () const
quint32 getOriginPointId () const
void setOriginPointId (const quint32 &value)
VFormula GetFormulaAngle () const
void SetFormulaAngle (const VFormula &value)
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractOperation
virtual ~VAbstractOperation () Q_DECL_EQ_DEFAULT
virtual QString getTagName () const Q_DECL_OVERRIDE
QString Suffix () const
void setSuffix (const QString &suffix)
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) Q_DECL_OVERRIDE
virtual bool isPointNameVisible (quint32 id) const Q_DECL_OVERRIDE
virtual void setPointNameVisiblity (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void setPointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual void setLineWeight (const QString &value)
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Static Public Member Functions
static VToolRotation * Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static VToolRotation * Create (const quint32 _id, const quint32 &origin, QString &angle, const QString &suffix, const QVector< SourceItem > &source, const QVector< DestinationItem > &destination, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation)
Static Public Member Functions inherited from VAbstractOperation
static void ExtractData (const QDomElement &domElement, QVector< SourceItem > &source, QVector< DestinationItem > &destination)
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString ToolType = QStringLiteral("rotation")
Static Public Attributes inherited from VAbstractOperation
static const QString TagItem = QStringLiteral("item")
static const QString TagSource = QStringLiteral("source")
static const QString TagDestination = QStringLiteral("destination")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Slots
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID) Q_DECL_OVERRIDE
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Protected Member Functions
virtual void SetVisualization () Q_DECL_OVERRIDE
virtual void SaveDialog (QDomElement &domElement) Q_DECL_OVERRIDE
SaveDialog save options into file after change in dialog.
virtual void ReadToolAttributes (const QDomElement &domElement) Q_DECL_OVERRIDE
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
virtual QString makeToolTip () const Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractOperation
VAbstractOperation (VAbstractPattern *doc, VContainer *data, quint32 id, const QString &suffix, const QVector< SourceItem > &source, const QVector< DestinationItem > &destination, QGraphicsItem *parent=nullptr)
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
void updatePointNamePosition (quint32 id, const QPointF &pos)
void SaveSourceDestination (QDomElement &tag)
template<typename T >
void ShowToolVisualization (bool show)
void InitCurve (quint32 id, VContainer *data, GOType curveType, SceneObject sceneType)
void InitOperatedObjects ()
QString complexPointToolTip (quint32 itemId) const
QString complexCurveToolTip (quint32 itemId) const
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialogChange () Q_DECL_FINAL
void SaveOption (QSharedPointer< VGObject > &obj)
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
virtual void updatePointNameVisibility (quint32 id, bool visible)
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void RemoveReferens ()
RemoveReferens decrement value of reference.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
virtual void ToolCreation (const Source &typeCreation)
Private Member Functions
VToolRotation (VAbstractPattern *doc, VContainer *data, quint32 id, quint32 originPointId, const QString &angle, const QString &suffix, const QVector< SourceItem > &source, const QVector< DestinationItem > &destination, const Source &typeCreation, QGraphicsItem *parent=nullptr)
Static Private Member Functions
static DestinationItem createPoint (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data)
template<class Item >
static DestinationItem createItem (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data)
template<class Item >
static DestinationItem createArc (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data)
template<class Item >
static DestinationItem createCurve (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data)
template<class Item >
static DestinationItem createCurveWithSegments (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data)
static void updatePoint (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data, const DestinationItem &item)
template<class Item >
static void updateItem (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data, quint32 id)
template<class Item >
static void updateArc (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data, quint32 id)
template<class Item >
static void updateCurve (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data, quint32 id)
template<class Item >
static void updateCurveWithSegments (quint32 idTool, quint32 idItem, const QPointF &origin, qreal angle, const QString &suffix, VContainer *data, quint32 id)
Private Attributes
quint32 m_originPointId
QString formulaAngle
Additional Inherited Members
Public Slots inherited from VAbstractOperation
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
void AllowPointHover (bool enabled)
void AllowPointSelecting (bool enabled)
void AllowPointLabelHover (bool enabled)
void AllowPointLabelSelecting (bool enabled)
void AllowSplineHover (bool enabled)
void AllowSplineSelecting (bool enabled)
void AllowSplinePathHover (bool enabled)
void AllowSplinePathSelecting (bool enabled)
void AllowArcHover (bool enabled)
void AllowArcSelecting (bool enabled)
void AllowElArcHover (bool enabled)
void AllowElArcSelecting (bool enabled)
virtual void ToolSelectionType (const SelectionType &type) Q_DECL_OVERRIDE
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
void ObjectSelected (bool selected, quint32 objId)
void deletePoint ()
void pointNamePositionChanged (const QPointF &pos, quint32 labelId)
virtual void updatePointNameVisibility (quint32 id, bool visible) Q_DECL_OVERRIDE
Public Slots inherited from VDrawTool
virtual void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Static Protected Member Functions inherited from VAbstractOperation
template<typename T >
static void initOperationToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VAbstractOperation
QString suffix
QVector< SourceItem > source
QVector< DestinationItem > destination
QMap< quint32, VAbstractSimple * > operatedObjects
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Detailed Description
Definition at line 71 of file vtoolrotation.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 88 of file vtoolrotation.h.
Constructor & Destructor Documentation
~VToolRotation()
virtual VToolRotation::~VToolRotation () virtual
VToolRotation()
VToolRotation::VToolRotation (VAbstractPattern * doc, VContainer * data, quint32 id, quint32 originPointId, const QString & angle, const QString & suffix, const QVector< SourceItem > & source, const QVector< DestinationItem > & destination, const Source & typeCreation, QGraphicsItem * parent = nullptr) private
Definition at line 106 of file vtoolrotation.cpp.
References VAbstractOperation::InitOperatedObjects(), and VAbstractTool::ToolCreation().
Referenced by Create().
Member Function Documentation
Create() [1/2]
VToolRotation * VToolRotation::Create (const quint32 _id, const quint32 & origin, QString & angle, const QString & suffix, const QVector< SourceItem > & source, const QVector< DestinationItem > & destination, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation) static
Definition at line 151 of file vtoolrotation.cpp.
References VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), AllCurves, Arc, VAbstractTool::CheckFormula(), createPoint(), CubicBezier, CubicBezierPath, Curve, VDataTool::data, VAbstractOperation::destination, VAbstractTool::doc, EllipticalArc, FromGui, FullParse, VContainer::GeometricObject(), VContainer::GetGObject(), VContainer::getNextId(), SourceItem::id, VAbstractPattern::IncrementReferens(), VAbstractOperation::initOperationToolConnections(), Path, Point, Rotation, VAbstractOperation::source, Spline, SplinePath, VAbstractOperation::suffix, Unknown, updatePoint(), VAbstractPattern::UpdateToolData(), and VToolRotation().
Create() [2/2]
VToolRotation * VToolRotation::Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data) static
Definition at line 130 of file vtoolrotation.cpp.
References VDataTool::data, VAbstractTool::doc, FromGui, FullParse, VInteractiveTool::m_dialog, SCASSERT, VAbstractOperation::source, and VAbstractOperation::suffix.
Referenced by VPattern::ParseToolRotation().
createArc()
template<class Item > DestinationItem VToolRotation::createArc (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data) static private
Definition at line 450 of file vtoolrotation.cpp.
References VContainer::AddArc(), VDataTool::data, VContainer::GeometricObject(), DestinationItem::id, Item, and VAbstractOperation::suffix.
createCurve()
template<class Item > DestinationItem VToolRotation::createCurve (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data) static private
Definition at line 460 of file vtoolrotation.cpp.
References VContainer::AddSpline(), VDataTool::data, VContainer::GeometricObject(), DestinationItem::id, Item, and VAbstractOperation::suffix.
createCurveWithSegments()
template<class Item > DestinationItem VToolRotation::createCurveWithSegments (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data) static private
Definition at line 470 of file vtoolrotation.cpp.
References VContainer::AddCurveWithSegments(), VDataTool::data, VContainer::GeometricObject(), DestinationItem::id, Item, and VAbstractOperation::suffix.
createItem()
template<class Item > DestinationItem VToolRotation::createItem (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data) static private
Definition at line 434 of file vtoolrotation.cpp.
References VContainer::AddGObject(), VDataTool::data, VContainer::GeometricObject(), DestinationItem::id, Item, DestinationItem::mx, DestinationItem::my, and VAbstractOperation::suffix.
createPoint()
DestinationItem VToolRotation::createPoint (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data) static private
Definition at line 417 of file vtoolrotation.cpp.
References VContainer::AddGObject(), VDataTool::data, VContainer::GeometricObject(), DestinationItem::id, DestinationItem::mx, DestinationItem::my, DestinationItem::showPointName, and VAbstractOperation::suffix.
Referenced by Create().
GetFormulaAngle()
VFormula VToolRotation::GetFormulaAngle () const
Definition at line 315 of file vtoolrotation.cpp.
References degreeSymbol, formulaAngle, VAbstractTool::getData(), VAbstractTool::m_id, VFormula::setCheckZero(), VFormula::setPostfix(), and VFormula::setToolId().
Referenced by makeToolTip(), VToolOptionsPropertyBrowser::showOptionsToolRotation(), and VToolOptionsPropertyBrowser::updateOptionsToolRotation().
getOriginPointId()
quint32 VToolRotation::getOriginPointId () const
Definition at line 297 of file vtoolrotation.cpp.
References m_originPointId.
getOriginPointName()
QString VToolRotation::getOriginPointName () const
Definition at line 291 of file vtoolrotation.cpp.
References VDataTool::data, VContainer::GetGObject(), and m_originPointId.
Referenced by makeToolTip(), VToolOptionsPropertyBrowser::showOptionsToolRotation(), and VToolOptionsPropertyBrowser::updateOptionsToolRotation().
makeToolTip()
QString VToolRotation::makeToolTip () const protected virtual
Reimplemented from VDrawTool.
Definition at line 391 of file vtoolrotation.cpp.
References GetFormulaAngle(), and getOriginPointName().
ReadToolAttributes()
void VToolRotation::ReadToolAttributes (const QDomElement & domElement) protected virtual
Reimplemented from VAbstractOperation.
Definition at line 370 of file vtoolrotation.cpp.
References AttrAngle, AttrCenter, AttrSuffix, VAbstractTool::doc, formulaAngle, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), m_originPointId, NULL_ID_STR, and VAbstractOperation::suffix.
SaveDialog()
void VToolRotation::SaveDialog (QDomElement & domElement) protected virtual
SaveDialog save options into file after change in dialog.
Implements VDrawTool.
Definition at line 358 of file vtoolrotation.cpp.
References AttrAngle, AttrCenter, AttrSuffix, VAbstractTool::doc, VInteractiveTool::m_dialog, SCASSERT, and VDomDocument::SetAttribute().
SaveOptions()
void VToolRotation::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VAbstractOperation.
Definition at line 378 of file vtoolrotation.cpp.
References AttrAngle, AttrCenter, AttrSuffix, AttrType, VAbstractTool::doc, formulaAngle, m_originPointId, VDrawTool::SaveOptions(), VAbstractOperation::SaveSourceDestination(), VDomDocument::SetAttribute(), VAbstractOperation::suffix, and ToolType.
setDialog()
void VToolRotation::setDialog () virtual
setDialog set dialog when user want change tool option.
Reimplemented from VInteractiveTool.
Definition at line 119 of file vtoolrotation.cpp.
References formulaAngle, VInteractiveTool::m_dialog, m_originPointId, SCASSERT, and VAbstractOperation::suffix.
SetFormulaAngle()
void VToolRotation::SetFormulaAngle (const VFormula & value)
Definition at line 325 of file vtoolrotation.cpp.
References VFormula::error(), formulaAngle, FromUser, VContainer::GetFakeGObject(), VFormula::GetFormula(), VAbstractTool::m_id, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolRotation().
setOriginPointId()
void VToolRotation::setOriginPointId (const quint32 & value)
Definition at line 303 of file vtoolrotation.cpp.
References VDataTool::data, VContainer::GetFakeGObject(), VAbstractTool::m_id, m_originPointId, NULL_ID, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolRotation().
SetVisualization()
void VToolRotation::SetVisualization () protected virtual
Implements VAbstractTool.
Definition at line 343 of file vtoolrotation.cpp.
References formulaAngle, m_originPointId, qApp, VisToolRotation::RefreshGeometry(), SCASSERT, VisToolRotation::SetAngle(), VisOperation::setObjects(), VisToolRotation::SetOriginPointId(), VAbstractOperation::source, sourceToObjects(), and VAbstractTool::vis.
showContextMenu
void VToolRotation::showContextMenu (QGraphicsSceneContextMenuEvent * event, quint32 id = NULL_ID) protected virtual slot
Definition at line 403 of file vtoolrotation.cpp.
ShowVisualization()
void VToolRotation::ShowVisualization (bool show) virtual
Implements VAbstractTool.
Definition at line 337 of file vtoolrotation.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolRotation().
type()
virtual int VToolRotation::type () const inline virtual
Definition at line 87 of file vtoolrotation.h.
References Type.
updateArc()
template<class Item > void VToolRotation::updateArc (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data, quint32 id) static private
Definition at line 504 of file vtoolrotation.cpp.
References VContainer::AddArc(), VDataTool::data, VContainer::GeometricObject(), Item, and VAbstractOperation::suffix.
updateCurve()
template<class Item > void VToolRotation::updateCurve (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data, quint32 id) static private
Definition at line 513 of file vtoolrotation.cpp.
References VContainer::AddSpline(), VDataTool::data, VContainer::GeometricObject(), Item, and VAbstractOperation::suffix.
updateCurveWithSegments()
template<class Item > void VToolRotation::updateCurveWithSegments (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data, quint32 id) static private
Definition at line 522 of file vtoolrotation.cpp.
References VContainer::AddCurveWithSegments(), VDataTool::data, VContainer::GeometricObject(), Item, and VAbstractOperation::suffix.
updateItem()
template<class Item > void VToolRotation::updateItem (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data, quint32 id) static private
Definition at line 493 of file vtoolrotation.cpp.
References VDataTool::data, VContainer::GeometricObject(), Item, VAbstractOperation::suffix, and VContainer::UpdateGObject().
updatePoint()
void VToolRotation::updatePoint (quint32 idTool, quint32 idItem, const QPointF & origin, qreal angle, const QString & suffix, VContainer * data, const DestinationItem & item) static private
Definition at line 479 of file vtoolrotation.cpp.
References VDataTool::data, VContainer::GeometricObject(), DestinationItem::id, DestinationItem::mx, DestinationItem::my, DestinationItem::showPointName, VAbstractOperation::suffix, and VContainer::UpdateGObject().
Referenced by Create().
Member Data Documentation
formulaAngle
QString VToolRotation::formulaAngle private
Definition at line 112 of file vtoolrotation.h.
Referenced by GetFormulaAngle(), ReadToolAttributes(), SaveOptions(), setDialog(), SetFormulaAngle(), and SetVisualization().
m_originPointId
quint32 VToolRotation::m_originPointId private
Definition at line 111 of file vtoolrotation.h.
Referenced by getOriginPointId(), getOriginPointName(), ReadToolAttributes(), SaveOptions(), setDialog(), setOriginPointId(), and SetVisualization().
ToolType
const QString VToolRotation::ToolType = QStringLiteral("rotation") static
Definition at line 85 of file vtoolrotation.h.
Referenced by VPattern::ParseOperationElement(), and SaveOptions().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/operation/vtoolrotation.h
src/libs/vtools/tools/drawTools/operation/vtoolrotation.cpp