Seamly2D: XercesAttGroupInfo Class Reference
XercesAttGroupInfo Class Reference
#include <XercesAttGroupInfo.hpp>
Public Member Functions
XercesAttGroupInfo (unsigned int attGroupNameId, unsigned int attGroupNamespaceId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XercesAttGroupInfo ()
bool containsTypeWithId () const
XMLSize_t attributeCount () const
XMLSize_t anyAttributeCount () const
unsigned int getNameId () const
unsigned int getNamespaceId () const
SchemaAttDef * attributeAt (const XMLSize_t index)
const SchemaAttDef * attributeAt (const XMLSize_t index) const
SchemaAttDef * anyAttributeAt (const XMLSize_t index)
const SchemaAttDef * anyAttributeAt (const XMLSize_t index) const
SchemaAttDef * getCompleteWildCard () const
const SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId) const
void setTypeWithId (const bool other)
void addAttDef (SchemaAttDef *const toAdd, const bool toClone=false)
void addAnyAttDef (SchemaAttDef *const toAdd, const bool toClone=false)
void setCompleteWildCard (SchemaAttDef *const toSet)
bool containsAttribute (const XMLCh *const name, const unsigned int uri)
XercesAttGroupInfo (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XercesAttGroupInfo (unsigned int attGroupNameId, unsigned int attGroupNamespaceId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XercesAttGroupInfo ()
bool containsTypeWithId () const
XMLSize_t attributeCount () const
XMLSize_t anyAttributeCount () const
unsigned int getNameId () const
unsigned int getNamespaceId () const
SchemaAttDef * attributeAt (const XMLSize_t index)
const SchemaAttDef * attributeAt (const XMLSize_t index) const
SchemaAttDef * anyAttributeAt (const XMLSize_t index)
const SchemaAttDef * anyAttributeAt (const XMLSize_t index) const
SchemaAttDef * getCompleteWildCard () const
const SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId) const
void setTypeWithId (const bool other)
void addAttDef (SchemaAttDef *const toAdd, const bool toClone=false)
void addAnyAttDef (SchemaAttDef *const toAdd, const bool toClone=false)
void setCompleteWildCard (SchemaAttDef *const toSet)
bool containsAttribute (const XMLCh *const name, const unsigned int uri)
XercesAttGroupInfo (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XercesAttGroupInfo (unsigned int attGroupNameId, unsigned int attGroupNamespaceId, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XercesAttGroupInfo ()
bool containsTypeWithId () const
XMLSize_t attributeCount () const
XMLSize_t anyAttributeCount () const
unsigned int getNameId () const
unsigned int getNamespaceId () const
SchemaAttDef * attributeAt (const XMLSize_t index)
const SchemaAttDef * attributeAt (const XMLSize_t index) const
SchemaAttDef * anyAttributeAt (const XMLSize_t index)
const SchemaAttDef * anyAttributeAt (const XMLSize_t index) const
SchemaAttDef * getCompleteWildCard () const
const SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId) const
void setTypeWithId (const bool other)
void addAttDef (SchemaAttDef *const toAdd, const bool toClone=false)
void addAnyAttDef (SchemaAttDef *const toAdd, const bool toClone=false)
void setCompleteWildCard (SchemaAttDef *const toSet)
bool containsAttribute (const XMLCh *const name, const unsigned int uri)
XercesAttGroupInfo (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
XercesAttGroupInfo (const XercesAttGroupInfo &elemInfo)
XercesAttGroupInfo & operator= (const XercesAttGroupInfo &other)
XercesAttGroupInfo (const XercesAttGroupInfo &elemInfo)
XercesAttGroupInfo & operator= (const XercesAttGroupInfo &other)
XercesAttGroupInfo (const XercesAttGroupInfo &elemInfo)
XercesAttGroupInfo & operator= (const XercesAttGroupInfo &other)
Private Attributes
bool fTypeWithId
unsigned int fNameId
unsigned int fNamespaceId
RefVectorOf< SchemaAttDef > * fAttributes
RefVectorOf< SchemaAttDef > * fAnyAttributes
SchemaAttDef * fCompleteWildCard
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
The class act as a place holder to store attributeGroup information.
The class is intended for internal use.
Definition at line 42 of file XercesAttGroupInfo.hpp.
Constructor & Destructor Documentation
XercesAttGroupInfo() [1/9]
XercesAttGroupInfo::XercesAttGroupInfo (unsigned int attGroupNameId, unsigned int attGroupNamespaceId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XercesAttGroupInfo() [1/3]
XercesAttGroupInfo::~XercesAttGroupInfo ()
XercesAttGroupInfo() [2/9]
XercesAttGroupInfo::XercesAttGroupInfo (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XercesAttGroupInfo() [3/9]
XercesAttGroupInfo::XercesAttGroupInfo (const XercesAttGroupInfo & elemInfo) private
XercesAttGroupInfo() [4/9]
XercesAttGroupInfo::XercesAttGroupInfo (unsigned int attGroupNameId, unsigned int attGroupNamespaceId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XercesAttGroupInfo() [2/3]
XercesAttGroupInfo::~XercesAttGroupInfo ()
XercesAttGroupInfo() [5/9]
XercesAttGroupInfo::XercesAttGroupInfo (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XercesAttGroupInfo() [6/9]
XercesAttGroupInfo::XercesAttGroupInfo (const XercesAttGroupInfo & elemInfo) private
XercesAttGroupInfo() [7/9]
XercesAttGroupInfo::XercesAttGroupInfo (unsigned int attGroupNameId, unsigned int attGroupNamespaceId, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XercesAttGroupInfo() [3/3]
XercesAttGroupInfo::~XercesAttGroupInfo ()
XercesAttGroupInfo() [8/9]
XercesAttGroupInfo::XercesAttGroupInfo (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XercesAttGroupInfo() [9/9]
XercesAttGroupInfo::XercesAttGroupInfo (const XercesAttGroupInfo & elemInfo) private
Member Function Documentation
addAnyAttDef() [1/3]
void XercesAttGroupInfo::addAnyAttDef (SchemaAttDef *const toAdd, const bool toClone = false) inline
Definition at line 220 of file XercesAttGroupInfo.hpp.
References SchemaAttDef::getBaseAttDecl(), and SchemaAttDef::setBaseAttDecl().
addAnyAttDef() [2/3]
void XercesAttGroupInfo::addAnyAttDef (SchemaAttDef *const toAdd, const bool toClone = false)
addAnyAttDef() [3/3]
void XercesAttGroupInfo::addAnyAttDef (SchemaAttDef *const toAdd, const bool toClone = false)
addAttDef() [1/3]
void XercesAttGroupInfo::addAttDef (SchemaAttDef *const toAdd, const bool toClone = false) inline
Definition at line 200 of file XercesAttGroupInfo.hpp.
References SchemaAttDef::getBaseAttDecl(), and SchemaAttDef::setBaseAttDecl().
addAttDef() [2/3]
void XercesAttGroupInfo::addAttDef (SchemaAttDef *const toAdd, const bool toClone = false)
addAttDef() [3/3]
void XercesAttGroupInfo::addAttDef (SchemaAttDef *const toAdd, const bool toClone = false)
anyAttributeAt() [1/6]
SchemaAttDef * XercesAttGroupInfo::anyAttributeAt (const XMLSize_t index) inline
Definition at line 167 of file XercesAttGroupInfo.hpp.
anyAttributeAt() [2/6]
SchemaAttDef* XercesAttGroupInfo::anyAttributeAt (const XMLSize_t index)
anyAttributeAt() [3/6]
SchemaAttDef* XercesAttGroupInfo::anyAttributeAt (const XMLSize_t index)
anyAttributeAt() [4/6]
const SchemaAttDef * XercesAttGroupInfo::anyAttributeAt (const XMLSize_t index) const inline
Definition at line 177 of file XercesAttGroupInfo.hpp.
anyAttributeAt() [5/6]
const SchemaAttDef* XercesAttGroupInfo::anyAttributeAt (const XMLSize_t index) const
anyAttributeAt() [6/6]
const SchemaAttDef* XercesAttGroupInfo::anyAttributeAt (const XMLSize_t index) const
anyAttributeCount() [1/3]
XMLSize_t XercesAttGroupInfo::anyAttributeCount () const inline
Definition at line 127 of file XercesAttGroupInfo.hpp.
anyAttributeCount() [2/3]
XMLSize_t XercesAttGroupInfo::anyAttributeCount () const
anyAttributeCount() [3/3]
XMLSize_t XercesAttGroupInfo::anyAttributeCount () const
attributeAt() [1/6]
SchemaAttDef * XercesAttGroupInfo::attributeAt (const XMLSize_t index) inline
Definition at line 147 of file XercesAttGroupInfo.hpp.
attributeAt() [2/6]
SchemaAttDef* XercesAttGroupInfo::attributeAt (const XMLSize_t index)
attributeAt() [3/6]
SchemaAttDef* XercesAttGroupInfo::attributeAt (const XMLSize_t index)
attributeAt() [4/6]
const SchemaAttDef * XercesAttGroupInfo::attributeAt (const XMLSize_t index) const inline
Definition at line 157 of file XercesAttGroupInfo.hpp.
attributeAt() [5/6]
const SchemaAttDef* XercesAttGroupInfo::attributeAt (const XMLSize_t index) const
attributeAt() [6/6]
const SchemaAttDef* XercesAttGroupInfo::attributeAt (const XMLSize_t index) const
attributeCount() [1/3]
XMLSize_t XercesAttGroupInfo::attributeCount () const inline
Definition at line 118 of file XercesAttGroupInfo.hpp.
attributeCount() [2/3]
XMLSize_t XercesAttGroupInfo::attributeCount () const
attributeCount() [3/3]
XMLSize_t XercesAttGroupInfo::attributeCount () const
containsAttribute() [1/3]
bool XercesAttGroupInfo::containsAttribute (const XMLCh *const name, const unsigned int uri)
containsAttribute() [2/3]
bool XercesAttGroupInfo::containsAttribute (const XMLCh *const name, const unsigned int uri)
containsAttribute() [3/3]
bool XercesAttGroupInfo::containsAttribute (const XMLCh *const name, const unsigned int uri)
containsTypeWithId() [1/3]
bool XercesAttGroupInfo::containsTypeWithId () const inline
Definition at line 113 of file XercesAttGroupInfo.hpp.
containsTypeWithId() [2/3]
bool XercesAttGroupInfo::containsTypeWithId () const
containsTypeWithId() [3/3]
bool XercesAttGroupInfo::containsTypeWithId () const
getAttDef() [1/3]
const SchemaAttDef* XercesAttGroupInfo::getAttDef (const XMLCh *const baseName, const int uriId) const
getAttDef() [2/3]
const SchemaAttDef* XercesAttGroupInfo::getAttDef (const XMLCh *const baseName, const int uriId) const
getAttDef() [3/3]
const SchemaAttDef* XercesAttGroupInfo::getAttDef (const XMLCh *const baseName, const int uriId) const
getCompleteWildCard() [1/3]
SchemaAttDef * XercesAttGroupInfo::getCompleteWildCard () const inline
Definition at line 187 of file XercesAttGroupInfo.hpp.
getCompleteWildCard() [2/3]
SchemaAttDef* XercesAttGroupInfo::getCompleteWildCard () const
getCompleteWildCard() [3/3]
SchemaAttDef* XercesAttGroupInfo::getCompleteWildCard () const
getNameId() [1/3]
unsigned int XercesAttGroupInfo::getNameId () const inline
Definition at line 136 of file XercesAttGroupInfo.hpp.
getNameId() [2/3]
unsigned int XercesAttGroupInfo::getNameId () const
getNameId() [3/3]
unsigned int XercesAttGroupInfo::getNameId () const
getNamespaceId() [1/3]
unsigned int XercesAttGroupInfo::getNamespaceId () const inline
Definition at line 141 of file XercesAttGroupInfo.hpp.
getNamespaceId() [2/3]
unsigned int XercesAttGroupInfo::getNamespaceId () const
getNamespaceId() [3/3]
unsigned int XercesAttGroupInfo::getNamespaceId () const
operator=() [1/3]
XercesAttGroupInfo& XercesAttGroupInfo::operator= (const XercesAttGroupInfo & other) private
operator=() [2/3]
XercesAttGroupInfo& XercesAttGroupInfo::operator= (const XercesAttGroupInfo & other) private
operator=() [3/3]
XercesAttGroupInfo& XercesAttGroupInfo::operator= (const XercesAttGroupInfo & other) private
setCompleteWildCard() [1/3]
void XercesAttGroupInfo::setCompleteWildCard (SchemaAttDef *const toSet) inline
Definition at line 241 of file XercesAttGroupInfo.hpp.
setCompleteWildCard() [2/3]
void XercesAttGroupInfo::setCompleteWildCard (SchemaAttDef *const toSet)
setCompleteWildCard() [3/3]
void XercesAttGroupInfo::setCompleteWildCard (SchemaAttDef *const toSet)
setTypeWithId() [1/3]
void XercesAttGroupInfo::setTypeWithId (const bool other) inline
Definition at line 195 of file XercesAttGroupInfo.hpp.
setTypeWithId() [2/3]
void XercesAttGroupInfo::setTypeWithId (const bool other)
setTypeWithId() [3/3]
void XercesAttGroupInfo::setTypeWithId (const bool other)
Member Data Documentation
fAnyAttributes
RefVectorOf< SchemaAttDef > * XercesAttGroupInfo::fAnyAttributes private
Definition at line 105 of file XercesAttGroupInfo.hpp.
fAttributes
RefVectorOf< SchemaAttDef > * XercesAttGroupInfo::fAttributes private
Definition at line 104 of file XercesAttGroupInfo.hpp.
fCompleteWildCard
SchemaAttDef * XercesAttGroupInfo::fCompleteWildCard private
Definition at line 106 of file XercesAttGroupInfo.hpp.
fMemoryManager
MemoryManager * XercesAttGroupInfo::fMemoryManager private
Definition at line 107 of file XercesAttGroupInfo.hpp.
fNameId
unsigned int XercesAttGroupInfo::fNameId private
Definition at line 102 of file XercesAttGroupInfo.hpp.
fNamespaceId
unsigned int XercesAttGroupInfo::fNamespaceId private
Definition at line 103 of file XercesAttGroupInfo.hpp.
fTypeWithId
bool XercesAttGroupInfo::fTypeWithId private
Definition at line 101 of file XercesAttGroupInfo.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/XercesAttGroupInfo.hpp