Seamly2D: VisToolRotation Class Reference
VisToolRotation Class Reference
#include <vistoolrotation.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolRotation) }
Public Types inherited from VisOperation
enum { Type = UserType + static_cast<int>(Vis::ToolRotation) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolRotation (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolRotation ()
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void SetOriginPointId (quint32 value)
QString Angle () const
void SetAngle (const QString &expression)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisOperation
VisOperation (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisOperation ()
void setObjects (QVector< quint32 > objects)
virtual void VisualMode (const quint32 &pointId=NULL_ID) Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Member Functions
template<class Item >
int AddCurve (qreal angle, const QPointF &origin, quint32 id, int i)
Private Attributes
qreal angle
VScaledEllipse * point
VCurvePathItem * angleArc
VScaledLine * xAxis
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisOperation
VScaledEllipse * GetPoint (quint32 i, const QColor &color)
VCurvePathItem * GetCurve (quint32 i, const QColor &color)
template<class Item >
int addFlippedCurve (const QPointF &firstPoint, const QPointF &secondPoint, quint32 id, int i)
void refreshMirroredObjects (const QPointF &firstPoint, const QPointF &secondPoint)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from VisOperation
QVector< quint32 > objects
QColor supportColor2
QColor supportColor3
QVector< VScaledEllipse * > points
QVector< VCurvePathItem * > curves
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 69 of file vistoolrotation.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 84 of file vistoolrotation.h.
Constructor & Destructor Documentation
VisToolRotation()
VisToolRotation::VisToolRotation (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 82 of file vistoolrotation.cpp.
References angleArc, Visualization::InitPoint(), point, VisOperation::supportColor2, and xAxis.
~VisToolRotation()
VisToolRotation::~VisToolRotation () virtual
Definition at line 95 of file vistoolrotation.cpp.
Member Function Documentation
AddCurve()
template<class Item > int VisToolRotation::AddCurve (qreal angle, const QPointF & origin, quint32 id, int i) private
Definition at line 240 of file vistoolrotation.cpp.
References angle, Visualization::data, Visualization::DrawPath(), VisOperation::GetCurve(), Item, Visualization::lineWeight, NULL_ID, Visualization::object1Id, Visualization::supportColor, and VisOperation::supportColor2.
Angle()
QString VisToolRotation::Angle () const
Definition at line 227 of file vistoolrotation.cpp.
References angle.
Referenced by DialogRotation::ShowDialog().
RefreshGeometry()
QT_WARNING_PUSH void VisToolRotation::RefreshGeometry () virtual
Implements Visualization.
Definition at line 103 of file vistoolrotation.cpp.
References AllCurves, Arc, CubicBezier, CubicBezierPath, Curve, Visualization::data, defPointRadiusPixel, EllipticalArc, VContainer::GeometricObject(), VContainer::GetGObject(), VAbstractCurve::GetPath(), NULL_ID, Path, Point, Visualization::scenePos, Spline, SplinePath, Visualization::toolTip, Unknown, and VFuzzyComparePossibleNulls().
Referenced by DialogRotation::ChosenObject(), DialogRotation::SaveData(), and VToolRotation::SetVisualization().
SetAngle()
void VisToolRotation::SetAngle (const QString & expression)
Definition at line 233 of file vistoolrotation.cpp.
References angle, Visualization::data, and Visualization::FindVal().
Referenced by DialogRotation::SaveData(), DialogRotation::SetAngle(), and VToolRotation::SetVisualization().
SetOriginPointId()
QT_WARNING_POP void VisToolRotation::SetOriginPointId (quint32 value)
Definition at line 221 of file vistoolrotation.cpp.
References Visualization::object1Id.
Referenced by DialogRotation::ChosenObject(), DialogRotation::SaveData(), DialogRotation::setOriginPointId(), and VToolRotation::SetVisualization().
type()
virtual int VisToolRotation::type () const inline virtual
Reimplemented from VisOperation.
Definition at line 83 of file vistoolrotation.h.
References Type.
Member Data Documentation
angle
qreal VisToolRotation::angle private
Definition at line 87 of file vistoolrotation.h.
Referenced by AddCurve(), Angle(), and SetAngle().
angleArc
VCurvePathItem* VisToolRotation::angleArc private
Definition at line 89 of file vistoolrotation.h.
Referenced by VisToolRotation().
point
VScaledEllipse* VisToolRotation::point private
Definition at line 88 of file vistoolrotation.h.
Referenced by VisToolRotation().
xAxis
VScaledLine* VisToolRotation::xAxis private
Definition at line 90 of file vistoolrotation.h.
Referenced by VisToolRotation().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/operation/vistoolrotation.h
src/libs/vtools/visualization/line/operation/vistoolrotation.cpp