Seamly2D: VPieceNode Class Reference
VPieceNode Class Reference
#include <vpiecenode.h>
Public Member Functions
VPieceNode ()
VPieceNode (quint32 id, Tool typeTool, bool reverse=false)
VPieceNode (const VPieceNode &node)
~VPieceNode ()
VPieceNode & operator= (const VPieceNode &node)
void Swap (VPieceNode &node) Q_DECL_NOTHROW
quint32 GetId () const
void SetId (quint32 id)
Tool GetTypeTool () const
void SetTypeTool (Tool value)
bool GetReverse () const
void SetReverse (bool reverse)
bool isExcluded () const
void SetExcluded (bool exclude)
qreal GetSABefore (const VContainer *data) const
qreal GetSABefore (const VContainer *data, Unit unit) const
QString GetFormulaSABefore () const
void setBeforeSAFormula (const QString &formula)
qreal GetSAAfter (const VContainer *data) const
qreal GetSAAfter (const VContainer *data, Unit unit) const
QString GetFormulaSAAfter () const
void setAfterSAFormula (const QString &formula)
PieceNodeAngle GetAngleType () const
void SetAngleType (PieceNodeAngle type)
bool isNotch () const
void setNotch (bool notch)
bool IsMainPathNode () const
void SetMainPathNode (bool value)
NotchType getNotchType () const
void setNotchType (NotchType notchType)
NotchSubType getNotchSubType () const
void setNotchSubType (NotchSubType notchSubType)
bool showSeamlineNotch () const
void setShowSeamlineNotch (bool value)
bool showNotch () const
void setShowNotch (bool value)
qreal getNotchLength () const
void setNotchLength (qreal notchLength)
qreal getNotchWidth () const
void setNotchWidth (qreal notchWidth)
qreal getNotchAngle () const
void setNotchAngle (qreal notchAngle)
int getNotchCount () const
void setNotchCount (int notchCount)
Private Attributes
QSharedDataPointer< VPieceNodeData > d
Friends
QDataStream & operator<< (QDataStream &out, const VPieceNode &)
QDataStream & operator>> (QDataStream &in, VPieceNode &p)
Detailed Description
Definition at line 64 of file vpiecenode.h.
Constructor & Destructor Documentation
VPieceNode() [1/3]
VPieceNode::VPieceNode ()
Definition at line 104 of file vpiecenode.cpp.
VPieceNode() [2/3]
VPieceNode::VPieceNode (quint32 id, Tool typeTool, bool reverse = false)
Definition at line 109 of file vpiecenode.cpp.
VPieceNode() [3/3]
VPieceNode::VPieceNode (const VPieceNode & node)
Definition at line 114 of file vpiecenode.cpp.
~VPieceNode()
VPieceNode::~VPieceNode ()
Definition at line 130 of file vpiecenode.cpp.
Member Function Documentation
GetAngleType()
PieceNodeAngle VPieceNode::GetAngleType () const
Definition at line 272 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), anonymous_namespace{vpiecepath.cpp}::CurvePoint(), DialogInternalPath::nodeChanged(), PatternPieceDialog::nodeChanged(), and VPiecePath::PreparePointEkv().
GetFormulaSAAfter()
QString VPieceNode::GetFormulaSAAfter () const
Definition at line 257 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), DialogInternalPath::nodeChanged(), and PatternPieceDialog::nodeChanged().
GetFormulaSABefore()
QString VPieceNode::GetFormulaSABefore () const
Definition at line 215 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), DialogInternalPath::nodeChanged(), and PatternPieceDialog::nodeChanged().
GetId()
quint32 VPieceNode::GetId () const
Definition at line 149 of file vpiecenode.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeArc(), QT_WARNING_POP::AddNodeElArc(), QT_WARNING_POP::AddNodePoint(), QT_WARNING_POP::AddNodeSpline(), QT_WARNING_POP::AddNodeSplinePath(), VAbstractTool::AddSANode(), anonymous_namespace{vpiecepath.cpp}::CurveEndPoint(), anonymous_namespace{vpiecepath.cpp}::CurvePoint(), anonymous_namespace{vpiecepath.cpp}::CurveStartPoint(), VToolInternalPath::DecrementNodes(), PatternPieceTool::EnableToolMove(), QT_WARNING_POP::FindIndexJ(), DialogInternalPath::getItemById(), PatternPieceDialog::getItemById(), DialogInternalPath::GetLastId(), InsertNodesDialog::getLastNodeId(), DialogTool::getNodeInfo(), VPiece::getNodeSAPoints(), PatternPieceDialog::getPreviousId(), VToolInternalPath::IncrementNodes(), PatternPieceDialog::initializeCSAPoint(), PatternPieceTool::initializeNode(), DialogInternalPath::initializeNodesList(), PatternPieceDialog::initializeNodesList(), DialogInternalPath::initializeNotchesList(), PatternPieceDialog::initializeNotchesList(), InsertNodesDialog::insertCurveNodes(), DialogTool::isEachPointNameUnique(), VPiecePath::MissingNodes(), DialogTool::newNodeItem(), VPiecePath::NodeNextPoint(), VPiecePath::NodePreviousPoint(), VPiecePath::PathNodePoints(), VPiecePath::PathPoints(), PatternPieceTool::pieceLockedChanged(), QT_WARNING_POP::PointsOnEdge(), VAbstractTool::PrepareNode(), VPiecePath::PreparePointEkv(), VPiecePath::RemoveEdge(), anonymous_namespace{dialogtool.cpp}::RowId(), VPiece::SeamAllowancePoints(), VPiecePath::SeamAllowancePoints(), QT_WARNING_POP::unitePieces(), PatternPieceTool::UpdateExcludeState(), QT_WARNING_POP::UpdateNodeArc(), QT_WARNING_POP::UpdateNodeElArc(), QT_WARNING_POP::UpdateNodePoint(), QT_WARNING_POP::UpdateNodeSpline(), and QT_WARNING_POP::UpdateNodeSplinePath().
getNotchAngle()
qreal VPieceNode::getNotchAngle () const
Definition at line 393 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), VPiece::createBuiltInSaNotch(), VPiece::createSeamAllowanceNotch(), and PatternPieceDialog::notchChanged().
getNotchCount()
int VPieceNode::getNotchCount () const
Definition at line 405 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), VPiece::createBuiltInSaNotch(), VPiece::createSeamAllowanceNotch(), and PatternPieceDialog::notchChanged().
getNotchLength()
qreal VPieceNode::getNotchLength () const
Definition at line 369 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), VPiece::createBuiltInSaNotch(), VPiece::createSeamAllowanceNotch(), and PatternPieceDialog::notchChanged().
getNotchSubType()
NotchSubType VPieceNode::getNotchSubType () const
Definition at line 326 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), VPiece::createBuiltInSaNotch(), VPiece::createSeamAllowanceNotch(), DialogInternalPath::notchChanged(), and PatternPieceDialog::notchChanged().
getNotchType()
NotchType VPieceNode::getNotchType () const
Definition at line 314 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), VPiece::createBuiltInSaNotch(), VPiece::createSeamAllowanceNotch(), DialogTool::getNodeInfo(), DialogInternalPath::notchChanged(), and PatternPieceDialog::notchChanged().
getNotchWidth()
qreal VPieceNode::getNotchWidth () const
Definition at line 381 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), VPiece::createBuiltInSaNotch(), VPiece::createSeamAllowanceNotch(), and PatternPieceDialog::notchChanged().
GetReverse()
bool VPieceNode::GetReverse () const
Definition at line 173 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), PatternPieceDialog::ChosenObject(), QT_WARNING_POP::createUnionPaths(), anonymous_namespace{vpiecepath.cpp}::CurveEndPoint(), anonymous_namespace{vpiecepath.cpp}::CurveStartPoint(), DialogTool::getNodeInfo(), VPiece::getNodeSAPoints(), VPiecePath::NodeNextPoint(), VPiecePath::NodePreviousPoint(), PatternPieceDialog::reverseNode(), VPiece::SeamAllowancePoints(), VPiecePath::SeamAllowancePoints(), InsertNodesDialog::showContextMenu(), DialogInternalPath::ShowContextMenu(), and PatternPieceDialog::showMainPathContextMenu().
GetSAAfter() [1/2]
qreal VPieceNode::GetSAAfter (const VContainer * data) const
Definition at line 230 of file vpiecenode.cpp.
References currentSeamAllowance, d, and anonymous_namespace{vpiecenode.cpp}::EvalFormula().
Referenced by anonymous_namespace{vpiecepath.cpp}::CurvePoint(), and VPiecePath::PreparePointEkv().
GetSAAfter() [2/2]
qreal VPieceNode::GetSAAfter (const VContainer * data, Unit unit) const
Definition at line 241 of file vpiecenode.cpp.
References currentSeamAllowance, d, anonymous_namespace{vpiecenode.cpp}::EvalFormula(), and ToPixel().
GetSABefore() [1/2]
qreal VPieceNode::GetSABefore (const VContainer * data) const
Definition at line 188 of file vpiecenode.cpp.
References currentSeamAllowance, d, and anonymous_namespace{vpiecenode.cpp}::EvalFormula().
Referenced by anonymous_namespace{vpiecepath.cpp}::CurvePoint(), and VPiecePath::PreparePointEkv().
GetSABefore() [2/2]
qreal VPieceNode::GetSABefore (const VContainer * data, Unit unit) const
Definition at line 199 of file vpiecenode.cpp.
References currentSeamAllowance, d, anonymous_namespace{vpiecenode.cpp}::EvalFormula(), and ToPixel().
GetTypeTool()
Tool VPieceNode::GetTypeTool () const
Definition at line 161 of file vpiecenode.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeToNewPath(), VAbstractTool::AddSANode(), QT_WARNING_POP::createUnionPaths(), anonymous_namespace{vpiecepath.cpp}::CurveEndPoint(), anonymous_namespace{vpiecepath.cpp}::CurvePoint(), anonymous_namespace{vpiecepath.cpp}::CurveStartPoint(), PatternPieceDialog::duplicateNode(), PatternPieceTool::EnableToolMove(), DialogTool::getNodeInfo(), VPiece::getNodeSAPoints(), PatternPieceDialog::initializeCSAPoint(), PatternPieceTool::initializeNode(), DialogInternalPath::initializeNodesList(), PatternPieceDialog::initializeNodesList(), DialogInternalPath::initializeNotchesList(), PatternPieceDialog::initializeNotchesList(), DialogTool::isEachPointNameUnique(), VPiece::isNotchVisible(), DialogTool::newNodeItem(), VPiecePath::NodeNextPoint(), VPiecePath::NodePreviousPoint(), anonymous_namespace{vpiece.cpp}::notchesPossible(), VPiecePath::PathNodePoints(), VPiecePath::PathPoints(), PatternPieceTool::pieceLockedChanged(), PatternPieceDialog::pointNodesExist(), VAbstractTool::PrepareNode(), PatternPieceDialog::reverseNode(), VPiece::SeamAllowancePoints(), VPiecePath::SeamAllowancePoints(), setNotch(), PatternPieceDialog::setNotch(), InsertNodesDialog::showContextMenu(), DialogInternalPath::ShowContextMenu(), PatternPieceDialog::showMainPathContextMenu(), PatternPieceTool::UpdateExcludeState(), and QT_WARNING_POP::UpdatePathNode().
isExcluded()
bool VPieceNode::isExcluded () const
Definition at line 411 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), VPiece::createNotchLines(), PatternPieceDialog::excludeNode(), DialogTool::FindNotExcludedNodeDown(), DialogTool::FindNotExcludedNodeUp(), PatternPieceDialog::initializeCSAPoint(), PatternPieceTool::initializeNode(), PatternPieceDialog::initializeNodesList(), VPiece::isNotchVisible(), DialogTool::newNodeItem(), anonymous_namespace{vpiece.cpp}::notchesPossible(), VPiecePath::PathNodePoints(), VPiecePath::PathPoints(), PatternPieceDialog::pointNodesExist(), VPiece::SeamAllowancePoints(), PatternPieceDialog::showMainPathContextMenu(), and PatternPieceTool::UpdateExcludeState().
IsMainPathNode()
bool VPieceNode::IsMainPathNode () const
Definition at line 302 of file vpiecenode.cpp.
References d.
isNotch()
bool VPieceNode::isNotch () const
Definition at line 287 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), VPiece::createNotchLines(), DialogTool::getNodeInfo(), DialogInternalPath::initializeNotchesList(), PatternPieceDialog::initializeNotchesList(), VPiece::isNotchVisible(), InsertNodesDialog::showContextMenu(), and PatternPieceDialog::showMainPathContextMenu().
operator=()
VPieceNode & VPieceNode::operator= (const VPieceNode & node)
Definition at line 119 of file vpiecenode.cpp.
References d.
setAfterSAFormula()
void VPieceNode::setAfterSAFormula (const QString & formula)
Definition at line 263 of file vpiecenode.cpp.
References d, and NodePoint.
Referenced by anonymous_namespace{vnodedetail.cpp}::ConvertAfter(), VAbstractPattern::ParseSANode(), DialogInternalPath::updateNodeAfterSeamAllowance(), and PatternPieceDialog::updateNodeAfterSeamAllowance().
SetAngleType()
void VPieceNode::SetAngleType (PieceNodeAngle type)
Definition at line 278 of file vpiecenode.cpp.
References d, and NodePoint.
Referenced by DialogInternalPath::nodeAngleChanged(), PatternPieceDialog::nodeAngleChanged(), and VAbstractPattern::ParseSANode().
setBeforeSAFormula()
void VPieceNode::setBeforeSAFormula (const QString & formula)
Definition at line 221 of file vpiecenode.cpp.
References d, and NodePoint.
Referenced by anonymous_namespace{vnodedetail.cpp}::ConvertBefore(), VAbstractPattern::ParseSANode(), DialogInternalPath::updateNodeBeforeSeamAllowance(), and PatternPieceDialog::updateNodeBeforeSeamAllowance().
SetExcluded()
void VPieceNode::SetExcluded (bool exclude)
Definition at line 417 of file vpiecenode.cpp.
References d.
Referenced by PatternPieceDialog::duplicateNode(), PatternPieceDialog::excludeNode(), InsertNodesDialog::insertCurveNodes(), VAbstractPattern::ParseSANode(), and InsertNodesDialog::SelectedObject().
SetId()
void VPieceNode::SetId (quint32 id)
Definition at line 155 of file vpiecenode.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeToNewPath(), and VAbstractTool::PrepareNodes().
SetMainPathNode()
void VPieceNode::SetMainPathNode (bool value)
Definition at line 308 of file vpiecenode.cpp.
References d.
setNotch()
void VPieceNode::setNotch (bool notch)
Definition at line 293 of file vpiecenode.cpp.
References d, GetTypeTool(), and NodePoint.
Referenced by VAbstractPattern::ParseSANode(), PatternPieceDialog::setNotch(), and InsertNodesDialog::showContextMenu().
setNotchAngle()
void VPieceNode::setNotchAngle (qreal notchAngle)
Definition at line 387 of file vpiecenode.cpp.
References d.
Referenced by PatternPieceDialog::notchAngleChanged(), and VAbstractPattern::ParseSANode().
setNotchCount()
void VPieceNode::setNotchCount (int notchCount)
Definition at line 399 of file vpiecenode.cpp.
References d.
Referenced by PatternPieceDialog::notchCountChanged(), and VAbstractPattern::ParseSANode().
setNotchLength()
void VPieceNode::setNotchLength (qreal notchLength)
Definition at line 363 of file vpiecenode.cpp.
References d.
Referenced by PatternPieceDialog::notchLengthChanged(), and VAbstractPattern::ParseSANode().
setNotchSubType()
void VPieceNode::setNotchSubType (NotchSubType notchSubType)
Definition at line 332 of file vpiecenode.cpp.
References d.
Referenced by DialogInternalPath::notchSubTypeChanged(), PatternPieceDialog::notchSubTypeChanged(), and VAbstractPattern::ParseSANode().
setNotchType()
void VPieceNode::setNotchType (NotchType notchType)
Definition at line 320 of file vpiecenode.cpp.
References d.
Referenced by DialogInternalPath::notchTypeChanged(), PatternPieceDialog::notchTypeChanged(), VAbstractPattern::ParseSANode(), PatternPieceDialog::setNotch(), and InsertNodesDialog::showContextMenu().
setNotchWidth()
void VPieceNode::setNotchWidth (qreal notchWidth)
Definition at line 375 of file vpiecenode.cpp.
References d.
Referenced by PatternPieceDialog::notchWidthChanged(), and VAbstractPattern::ParseSANode().
SetReverse()
void VPieceNode::SetReverse (bool reverse)
Definition at line 179 of file vpiecenode.cpp.
References d, and NodePoint.
Referenced by PatternPieceDialog::reverseNode(), InsertNodesDialog::showContextMenu(), and DialogInternalPath::ShowContextMenu().
setShowNotch()
void VPieceNode::setShowNotch (bool value)
Definition at line 344 of file vpiecenode.cpp.
References d.
Referenced by VAbstractPattern::ParseSANode(), and PatternPieceDialog::showNotchChanged().
setShowSeamlineNotch()
void VPieceNode::setShowSeamlineNotch (bool value)
Definition at line 356 of file vpiecenode.cpp.
References d.
Referenced by VAbstractPattern::ParseSANode(), and PatternPieceDialog::showSeamlineNotchChanged().
SetTypeTool()
void VPieceNode::SetTypeTool (Tool value)
Definition at line 167 of file vpiecenode.cpp.
References d.
showNotch()
bool VPieceNode::showNotch () const
Definition at line 338 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), and PatternPieceDialog::notchChanged().
showSeamlineNotch()
bool VPieceNode::showSeamlineNotch () const
Definition at line 350 of file vpiecenode.cpp.
References d.
Referenced by VAbstractTool::AddSANode(), and PatternPieceDialog::notchChanged().
Swap()
void VPieceNode::Swap (VPieceNode & node)
Definition at line 100 of file vpiecenode.cpp.
Friends And Related Function Documentation
operator<<
QDataStream& operator<< (QDataStream & out, const VPieceNode & p) friend
Definition at line 135 of file vpiecenode.cpp.
operator>>
QDataStream& operator>> (QDataStream & in, VPieceNode & p) friend
Definition at line 142 of file vpiecenode.cpp.
Member Data Documentation
d
QSharedDataPointer<VPieceNodeData> VPieceNode::d private
Definition at line 142 of file vpiecenode.h.
Referenced by GetAngleType(), GetFormulaSAAfter(), GetFormulaSABefore(), GetId(), getNotchAngle(), getNotchCount(), getNotchLength(), getNotchSubType(), getNotchType(), getNotchWidth(), GetReverse(), GetSAAfter(), GetSABefore(), GetTypeTool(), isExcluded(), IsMainPathNode(), isNotch(), operator=(), setAfterSAFormula(), SetAngleType(), setBeforeSAFormula(), SetExcluded(), SetId(), SetMainPathNode(), setNotch(), setNotchAngle(), setNotchCount(), setNotchLength(), setNotchSubType(), setNotchType(), setNotchWidth(), SetReverse(), setShowNotch(), setShowSeamlineNotch(), SetTypeTool(), showNotch(), and showSeamlineNotch().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/vpiecenode.h
src/libs/vpatterndb/vpiecenode.cpp