Seamly2D: SeamlyMePreferencesConfigurationPage Class Reference
SeamlyMePreferencesConfigurationPage Class Reference
#include <seamlymepreferencesconfigurationpage.h>
Public Member Functions
SeamlyMePreferencesConfigurationPage (QWidget *parent=nullptr)
virtual ~SeamlyMePreferencesConfigurationPage ()
void Apply ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
Private Attributes
Ui::SeamlyMePreferencesConfigurationPage * ui
bool m_langChanged
bool m_systemChanged
bool m_defGradationChanged
Detailed Description
Definition at line 66 of file seamlymepreferencesconfigurationpage.h.
Constructor & Destructor Documentation
SeamlyMePreferencesConfigurationPage()
SeamlyMePreferencesConfigurationPage::SeamlyMePreferencesConfigurationPage (QWidget * parent = nullptr) explicit
Definition at line 64 of file seamlymepreferencesconfigurationpage.cpp.
References Cm, InitLanguages(), InitPMSystems(), m_defGradationChanged, qApp, ui, MeasurementVariable::WholeListHeights(), and MeasurementVariable::WholeListSizes().
~SeamlyMePreferencesConfigurationPage()
SeamlyMePreferencesConfigurationPage::~SeamlyMePreferencesConfigurationPage () virtual
Definition at line 145 of file seamlymepreferencesconfigurationpage.cpp.
References ui.
Member Function Documentation
Apply()
void SeamlyMePreferencesConfigurationPage::Apply ()
Definition at line 162 of file seamlymepreferencesconfigurationpage.cpp.
References m_defGradationChanged, m_langChanged, m_systemChanged, qApp, VSeamlyMeSettings::SetDefHeight(), VSeamlyMeSettings::SetDefSize(), VCommonSettings::SetLocale(), VCommonSettings::SetOsSeparator(), VCommonSettings::SetPMSystemCode(), VCommonSettings::setShowWelcome(), VCommonSettings::setToolBarStyle(), and ui.
Referenced by DialogSeamlyMePreferences::Apply().
changeEvent()
void SeamlyMePreferencesConfigurationPage::changeEvent (QEvent * event) protected virtual
Definition at line 151 of file seamlymepreferencesconfigurationpage.cpp.
References ui.
Member Data Documentation
m_defGradationChanged
bool SeamlyMePreferencesConfigurationPage::m_defGradationChanged private
Definition at line 84 of file seamlymepreferencesconfigurationpage.h.
Referenced by Apply(), and SeamlyMePreferencesConfigurationPage().
m_langChanged
bool SeamlyMePreferencesConfigurationPage::m_langChanged private
Definition at line 82 of file seamlymepreferencesconfigurationpage.h.
Referenced by Apply().
m_systemChanged
bool SeamlyMePreferencesConfigurationPage::m_systemChanged private
Definition at line 83 of file seamlymepreferencesconfigurationpage.h.
Referenced by Apply().
ui
Ui::SeamlyMePreferencesConfigurationPage* SeamlyMePreferencesConfigurationPage::ui private
Definition at line 81 of file seamlymepreferencesconfigurationpage.h.
Referenced by Apply(), changeEvent(), SeamlyMePreferencesConfigurationPage(), and ~SeamlyMePreferencesConfigurationPage().
The documentation for this class was generated from the following files:
src/app/seamlyme/dialogs/configpages/seamlymepreferencesconfigurationpage.h
src/app/seamlyme/dialogs/configpages/seamlymepreferencesconfigurationpage.cpp