Seamly2D: VisToolHeight Class Reference
VisToolHeight Class Reference
#include <vistoolheight.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolHeight) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolHeight (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolHeight ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setLineP1Id (const quint32 &value)
void setLineP2Id (const quint32 &value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Member Functions
void ShowIntersection (const QLineF &height_line, const QLineF &base_line)
Private Attributes
quint32 lineP1Id
quint32 lineP2Id
VScaledEllipse * point
VScaledEllipse * base_point
VScaledEllipse * lineP1
VScaledEllipse * lineP2
VScaledLine * line
VScaledLine * line_intersection
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 66 of file vistoolheight.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 78 of file vistoolheight.h.
Constructor & Destructor Documentation
VisToolHeight()
VisToolHeight::VisToolHeight (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 69 of file vistoolheight.cpp.
References base_point, Visualization::InitPoint(), line, line_intersection, lineP1, lineP2, Visualization::mainColor, point, and Visualization::supportColor.
~VisToolHeight()
virtual VisToolHeight::~VisToolHeight () virtual default
Member Function Documentation
RefreshGeometry()
void VisToolHeight::RefreshGeometry () virtual
Implements Visualization.
Definition at line 83 of file vistoolheight.cpp.
References base_point, Visualization::data, Visualization::DrawLine(), Visualization::DrawPoint(), VToolHeight::FindPoint(), VContainer::GeometricObject(), line, lineP1, lineP1Id, lineP2, lineP2Id, Visualization::lineStyle, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, point, Visualization::scenePos, ShowIntersection(), and Visualization::supportColor.
Referenced by DialogHeight::ChosenObject(), DialogHeight::SaveData(), and VToolHeight::SetVisualization().
setLineP1Id()
void VisToolHeight::setLineP1Id (const quint32 & value)
Definition at line 127 of file vistoolheight.cpp.
References lineP1Id.
Referenced by DialogHeight::ChosenObject(), DialogHeight::SaveData(), DialogHeight::SetP1LineId(), and VToolHeight::SetVisualization().
setLineP2Id()
void VisToolHeight::setLineP2Id (const quint32 & value)
Definition at line 133 of file vistoolheight.cpp.
References lineP2Id.
Referenced by DialogHeight::ChosenObject(), DialogHeight::SaveData(), DialogHeight::SetP2LineId(), and VToolHeight::SetVisualization().
ShowIntersection()
void VisToolHeight::ShowIntersection (const QLineF & height_line, const QLineF & base_line) private
Definition at line 139 of file vistoolheight.cpp.
References Visualization::DrawLine(), line_intersection, and Visualization::supportColor.
Referenced by RefreshGeometry().
type()
virtual int VisToolHeight::type () const inline virtual
Reimplemented from VisLine.
Definition at line 77 of file vistoolheight.h.
References Type.
Member Data Documentation
base_point
VScaledEllipse* VisToolHeight::base_point private
Definition at line 85 of file vistoolheight.h.
Referenced by RefreshGeometry(), and VisToolHeight().
line
VScaledLine* VisToolHeight::line private
Definition at line 88 of file vistoolheight.h.
Referenced by RefreshGeometry(), and VisToolHeight().
line_intersection
VScaledLine* VisToolHeight::line_intersection private
Definition at line 89 of file vistoolheight.h.
Referenced by ShowIntersection(), and VisToolHeight().
lineP1
VScaledEllipse* VisToolHeight::lineP1 private
Definition at line 86 of file vistoolheight.h.
Referenced by RefreshGeometry(), and VisToolHeight().
lineP1Id
quint32 VisToolHeight::lineP1Id private
Definition at line 82 of file vistoolheight.h.
Referenced by RefreshGeometry(), and setLineP1Id().
lineP2
VScaledEllipse* VisToolHeight::lineP2 private
Definition at line 87 of file vistoolheight.h.
Referenced by RefreshGeometry(), and VisToolHeight().
lineP2Id
quint32 VisToolHeight::lineP2Id private
Definition at line 83 of file vistoolheight.h.
Referenced by RefreshGeometry(), and setLineP2Id().
point
VScaledEllipse* VisToolHeight::point private
Definition at line 84 of file vistoolheight.h.
Referenced by RefreshGeometry(), and VisToolHeight().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/vistoolheight.h
src/libs/vtools/visualization/line/vistoolheight.cpp