Seamly2D: DialogCubicBezier Class Reference
DialogCubicBezier Class Reference
#include <dialogcubicbezier.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
virtual void PointNameChanged () Q_DECL_OVERRIDE
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogCubicBezier (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
virtual ~DialogCubicBezier ()
VCubicBezier GetSpline () const
void SetSpline (const VCubicBezier &spline)
QString getPenStyle () const
void setPenStyle (const QString &value)
QString getLineWeight () const
getLineWeight return weight of the lines
void setLineWeight (const QString &value)
setLineWeight set weight of the lines
QString getLineColor () const
void setLineColor (const QString &value)
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
virtual void CheckState ()
CheckState enable, when all is correct, or disable, when something wrong, button ok.
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Member Functions
const QSharedPointer< VPointF > GetP1 () const
const QSharedPointer< VPointF > GetP2 () const
const QSharedPointer< VPointF > GetP3 () const
const QSharedPointer< VPointF > GetP4 () const
Private Attributes
Ui::DialogCubicBezier * ui
VCubicBezier spl
spl spline
qint32 newDuplicate
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
Definition at line 73 of file dialogcubicbezier.h.
Constructor & Destructor Documentation
DialogCubicBezier()
DialogCubicBezier::DialogCubicBezier (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr) explicit
Definition at line 70 of file dialogcubicbezier.cpp.
References DialogTool::CheckState(), DialogTool::data, DialogTool::FillComboBoxPoints(), DialogTool::initializeOkCancelApply(), LineTypeNone, PointNameChanged(), qApp, ui, and DialogTool::vis.
~DialogCubicBezier()
DialogCubicBezier::~DialogCubicBezier () virtual
Definition at line 122 of file dialogcubicbezier.cpp.
References ui.
Member Function Documentation
ChosenObject
void DialogCubicBezier::ChosenObject (quint32 id, const SceneObject & type) virtual slot
Definition at line 199 of file dialogcubicbezier.cpp.
References DialogTool::DialogAccepted(), DialogTool::getCurrentObjectId(), DialogTool::number, Point, DialogTool::prepare, SCASSERT, DialogTool::SetObject(), ui, and DialogTool::vis.
getLineColor()
QString DialogCubicBezier::getLineColor () const
Definition at line 187 of file dialogcubicbezier.cpp.
References ColorBlack, DialogTool::GetComboBoxCurrentData(), and ui.
getLineWeight()
QString DialogCubicBezier::getLineWeight () const
getLineWeight return weight of the lines
Returns
type
Definition at line 171 of file dialogcubicbezier.cpp.
References DialogTool::GetComboBoxCurrentData(), and ui.
GetP1()
const QSharedPointer< VPointF > DialogCubicBezier::GetP1 () const private
Definition at line 329 of file dialogcubicbezier.cpp.
References DialogTool::data, VContainer::GeometricObject(), DialogTool::getCurrentObjectId(), and ui.
Referenced by PointNameChanged(), and SaveData().
GetP2()
const QSharedPointer< VPointF > DialogCubicBezier::GetP2 () const private
Definition at line 335 of file dialogcubicbezier.cpp.
References DialogTool::data, VContainer::GeometricObject(), DialogTool::getCurrentObjectId(), and ui.
Referenced by PointNameChanged(), and SaveData().
GetP3()
const QSharedPointer< VPointF > DialogCubicBezier::GetP3 () const private
Definition at line 341 of file dialogcubicbezier.cpp.
References DialogTool::data, VContainer::GeometricObject(), DialogTool::getCurrentObjectId(), and ui.
Referenced by PointNameChanged(), and SaveData().
GetP4()
const QSharedPointer< VPointF > DialogCubicBezier::GetP4 () const private
Definition at line 347 of file dialogcubicbezier.cpp.
References DialogTool::data, VContainer::GeometricObject(), DialogTool::getCurrentObjectId(), and ui.
Referenced by PointNameChanged(), and SaveData().
getPenStyle()
QString DialogCubicBezier::getPenStyle () const
Definition at line 155 of file dialogcubicbezier.cpp.
References DialogTool::GetComboBoxCurrentData(), LineTypeSolidLine, and ui.
GetSpline()
VCubicBezier DialogCubicBezier::GetSpline () const
Definition at line 128 of file dialogcubicbezier.cpp.
References spl.
PointNameChanged
void DialogCubicBezier::PointNameChanged () virtual slot
Definition at line 257 of file dialogcubicbezier.cpp.
References DialogTool::ChangeColor(), DialogTool::CheckState(), DialogTool::data, DialogTool::DNumber(), DialogTool::errorColor, DialogTool::flagError, DialogTool::getCurrentObjectId(), GetP1(), VCubicBezier::GetP1(), GetP2(), GetP3(), GetP4(), VCubicBezier::GetP4(), VGObject::id(), VContainer::IsUnique(), VGObject::name(), newDuplicate, DialogTool::okColor, qApp, VAbstractCurve::SetDuplicate(), spl, and ui.
Referenced by DialogCubicBezier().
SaveData()
void DialogCubicBezier::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 305 of file dialogcubicbezier.cpp.
References VAbstractCurve::GetDuplicate(), GetP1(), GetP2(), GetP3(), GetP4(), newDuplicate, SCASSERT, VAbstractCurve::SetDuplicate(), Show, spl, and DialogTool::vis.
setLineColor()
void DialogCubicBezier::setLineColor (const QString & value)
Definition at line 193 of file dialogcubicbezier.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setLineWeight()
void DialogCubicBezier::setLineWeight (const QString & value)
setLineWeight set weight of the lines
Parameters
value type
Definition at line 181 of file dialogcubicbezier.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setPenStyle()
void DialogCubicBezier::setPenStyle (const QString & value)
Definition at line 161 of file dialogcubicbezier.cpp.
References DialogTool::ChangeCurrentData(), and ui.
SetSpline()
void DialogCubicBezier::SetSpline (const VCubicBezier & spline)
Definition at line 134 of file dialogcubicbezier.cpp.
References VCubicBezier::GetP1(), VCubicBezier::GetP2(), VCubicBezier::GetP3(), VCubicBezier::GetP4(), VGObject::id(), VGObject::name(), qApp, SCASSERT, DialogTool::setCurrentPointId(), spl, ui, and DialogTool::vis.
ShowVisualization()
void DialogCubicBezier::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 299 of file dialogcubicbezier.cpp.
Member Data Documentation
newDuplicate
qint32 DialogCubicBezier::newDuplicate private
Definition at line 111 of file dialogcubicbezier.h.
Referenced by PointNameChanged(), and SaveData().
spl
VCubicBezier DialogCubicBezier::spl private
spl spline
Definition at line 109 of file dialogcubicbezier.h.
Referenced by GetSpline(), PointNameChanged(), SaveData(), and SetSpline().
ui
Ui::DialogCubicBezier* DialogCubicBezier::ui private
Definition at line 106 of file dialogcubicbezier.h.
Referenced by ChosenObject(), DialogCubicBezier(), getLineColor(), getLineWeight(), GetP1(), GetP2(), GetP3(), GetP4(), getPenStyle(), PointNameChanged(), setLineColor(), setLineWeight(), setPenStyle(), SetSpline(), and ~DialogCubicBezier().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogcubicbezier.h
src/libs/vtools/dialogs/tools/dialogcubicbezier.cpp