Seamly2D: VisToolPointOfIntersectionArcs Class Reference
VisToolPointOfIntersectionArcs Class Reference
#include <vistoolpointofintersectionarcs.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolPointOfIntersectionArcs) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolPointOfIntersectionArcs (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolPointOfIntersectionArcs ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
virtual void VisualMode (const quint32 &id) Q_DECL_OVERRIDE
void setArc1Id (const quint32 &value)
void setArc2Id (const quint32 &value)
void setCrossPoint (const CrossCirclesPoint &value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Attributes
quint32 arc1Id
quint32 arc2Id
CrossCirclesPoint crossPoint
VScaledEllipse * point
VCurvePathItem * arc1Path
VCurvePathItem * arc2Path
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 66 of file vistoolpointofintersectionarcs.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 81 of file vistoolpointofintersectionarcs.h.
Constructor & Destructor Documentation
VisToolPointOfIntersectionArcs()
VisToolPointOfIntersectionArcs::VisToolPointOfIntersectionArcs (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 74 of file vistoolpointofintersectionarcs.cpp.
References arc1Path, arc2Path, FirstPoint, Visualization::InitPoint(), Visualization::mainColor, and point.
~VisToolPointOfIntersectionArcs()
virtual VisToolPointOfIntersectionArcs::~VisToolPointOfIntersectionArcs () virtual default
Member Function Documentation
RefreshGeometry()
void VisToolPointOfIntersectionArcs::RefreshGeometry () virtual
Implements Visualization.
Definition at line 92 of file vistoolpointofintersectionarcs.cpp.
References arc1Id, arc1Path, arc2Id, arc2Path, crossPoint, Visualization::data, Visualization::DrawPath(), Visualization::DrawPoint(), VToolPointOfIntersectionArcs::FindPoint(), VContainer::GeometricObject(), Visualization::lineWeight, Visualization::mainColor, NULL_ID, and point.
Referenced by DialogPointOfIntersectionArcs::ChosenObject(), DialogPointOfIntersectionArcs::SaveData(), VToolPointOfIntersectionArcs::SetVisualization(), and VisualMode().
setArc1Id()
void VisToolPointOfIntersectionArcs::setArc1Id (const quint32 & value)
Definition at line 126 of file vistoolpointofintersectionarcs.cpp.
References arc1Id.
Referenced by DialogPointOfIntersectionArcs::SaveData(), DialogPointOfIntersectionArcs::SetFirstArcId(), and VToolPointOfIntersectionArcs::SetVisualization().
setArc2Id()
void VisToolPointOfIntersectionArcs::setArc2Id (const quint32 & value)
Definition at line 132 of file vistoolpointofintersectionarcs.cpp.
References arc2Id.
Referenced by DialogPointOfIntersectionArcs::ChosenObject(), DialogPointOfIntersectionArcs::SaveData(), DialogPointOfIntersectionArcs::SetSecondArcId(), and VToolPointOfIntersectionArcs::SetVisualization().
setCrossPoint()
void VisToolPointOfIntersectionArcs::setCrossPoint (const CrossCirclesPoint & value)
Definition at line 138 of file vistoolpointofintersectionarcs.cpp.
References crossPoint.
Referenced by DialogPointOfIntersectionArcs::SaveData(), DialogPointOfIntersectionArcs::SetCrossArcPoint(), and VToolPointOfIntersectionArcs::SetVisualization().
type()
virtual int VisToolPointOfIntersectionArcs::type () const inline virtual
Reimplemented from VisLine.
Definition at line 80 of file vistoolpointofintersectionarcs.h.
References Type.
VisualMode()
void VisToolPointOfIntersectionArcs::VisualMode (const quint32 & id) virtual
Reimplemented from Visualization.
Definition at line 113 of file vistoolpointofintersectionarcs.cpp.
References VisLine::AddOnScene(), arc1Id, VMainGraphicsScene::getScenePos(), qApp, RefreshGeometry(), SCASSERT, and Visualization::scenePos.
Referenced by DialogPointOfIntersectionArcs::ChosenObject().
Member Data Documentation
arc1Id
quint32 VisToolPointOfIntersectionArcs::arc1Id private
Definition at line 84 of file vistoolpointofintersectionarcs.h.
Referenced by RefreshGeometry(), setArc1Id(), and VisualMode().
arc1Path
VCurvePathItem* VisToolPointOfIntersectionArcs::arc1Path private
Definition at line 88 of file vistoolpointofintersectionarcs.h.
Referenced by RefreshGeometry(), and VisToolPointOfIntersectionArcs().
arc2Id
quint32 VisToolPointOfIntersectionArcs::arc2Id private
Definition at line 85 of file vistoolpointofintersectionarcs.h.
Referenced by RefreshGeometry(), and setArc2Id().
arc2Path
VCurvePathItem* VisToolPointOfIntersectionArcs::arc2Path private
Definition at line 89 of file vistoolpointofintersectionarcs.h.
Referenced by RefreshGeometry(), and VisToolPointOfIntersectionArcs().
crossPoint
CrossCirclesPoint VisToolPointOfIntersectionArcs::crossPoint private
Definition at line 86 of file vistoolpointofintersectionarcs.h.
Referenced by RefreshGeometry(), and setCrossPoint().
point
VScaledEllipse* VisToolPointOfIntersectionArcs::point private
Definition at line 87 of file vistoolpointofintersectionarcs.h.
Referenced by RefreshGeometry(), and VisToolPointOfIntersectionArcs().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/vistoolpointofintersectionarcs.h
src/libs/vtools/visualization/line/vistoolpointofintersectionarcs.cpp