Seamly2D: NameIdPool< TElem > Class Template Reference
NameIdPool< TElem > Class Template Reference
#include <NameIdPool.hpp>
Public Member Functions
NameIdPool (const XMLSize_t hashModulus, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~NameIdPool ()
bool containsKey (const XMLCh *const key) const
void removeAll ()
TElem * getByKey (const XMLCh *const key)
const TElem * getByKey (const XMLCh *const key) const
TElem * getById (const XMLSize_t elemId)
const TElem * getById (const XMLSize_t elemId) const
MemoryManager * getMemoryManager () const
XMLSize_t put (TElem *const valueToAdopt)
NameIdPool (const XMLSize_t hashModulus, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~NameIdPool ()
bool containsKey (const XMLCh *const key) const
void removeAll ()
TElem * getByKey (const XMLCh *const key)
const TElem * getByKey (const XMLCh *const key) const
TElem * getById (const XMLSize_t elemId)
const TElem * getById (const XMLSize_t elemId) const
MemoryManager * getMemoryManager () const
XMLSize_t put (TElem *const valueToAdopt)
NameIdPool (const XMLSize_t hashModulus, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~NameIdPool ()
bool containsKey (const XMLCh *const key) const
void removeAll ()
TElem * getByKey (const XMLCh *const key)
const TElem * getByKey (const XMLCh *const key) const
TElem * getById (const XMLSize_t elemId)
const TElem * getById (const XMLSize_t elemId) const
MemoryManager * getMemoryManager () const
XMLSize_t put (TElem *const valueToAdopt)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
NameIdPool (const NameIdPool< TElem > &)
NameIdPool< TElem > & operator= (const NameIdPool< TElem > &)
NameIdPool (const NameIdPool< TElem > &)
NameIdPool< TElem > & operator= (const NameIdPool< TElem > &)
NameIdPool (const NameIdPool< TElem > &)
NameIdPool< TElem > & operator= (const NameIdPool< TElem > &)
Private Attributes
MemoryManager * fMemoryManager
TElem ** fIdPtrs
XMLSize_t fIdPtrsCount
XMLSize_t fIdCounter
RefHashTableOf< TElem > fBucketList
Friends
class NameIdPoolEnumerator< TElem >
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
template<class TElem>
class NameIdPool< TElem >
Definition at line 62 of file NameIdPool.hpp.
Constructor & Destructor Documentation
NameIdPool() [1/6]
template<class TElem > XERCES_CPP_NAMESPACE_BEGIN NameIdPool< TElem >::NameIdPool (const XMLSize_t hashModulus, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Definition at line 42 of file NameIdPool.c.
References MemoryManager::allocate(), NameIdPool< TElem >::fIdPtrs, NameIdPool< TElem >::fIdPtrsCount, NameIdPool< TElem >::fMemoryManager, XMLExcepts::Pool_ZeroModulus, and ThrowXMLwithMemMgr.
~NameIdPool() [1/3]
template<class TElem > NameIdPool< TElem >::~NameIdPool
Definition at line 68 of file NameIdPool.c.
NameIdPool() [2/6]
template<class TElem > NameIdPool< TElem >::NameIdPool (const NameIdPool< TElem > &) private
NameIdPool() [3/6]
template<class TElem > NameIdPool< TElem >::NameIdPool (const XMLSize_t hashModulus, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~NameIdPool() [2/3]
template<class TElem > NameIdPool< TElem >::~NameIdPool ()
NameIdPool() [4/6]
template<class TElem > NameIdPool< TElem >::NameIdPool (const NameIdPool< TElem > &) private
NameIdPool() [5/6]
template<class TElem > NameIdPool< TElem >::NameIdPool (const XMLSize_t hashModulus, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~NameIdPool() [3/3]
template<class TElem > NameIdPool< TElem >::~NameIdPool ()
NameIdPool() [6/6]
template<class TElem > NameIdPool< TElem >::NameIdPool (const NameIdPool< TElem > &) private
Member Function Documentation
containsKey() [1/3]
template<class TElem > bool NameIdPool< TElem >::containsKey (const XMLCh *const key) const inline
Definition at line 82 of file NameIdPool.c.
containsKey() [2/3]
template<class TElem > bool NameIdPool< TElem >::containsKey (const XMLCh *const key) const
containsKey() [3/3]
template<class TElem > bool NameIdPool< TElem >::containsKey (const XMLCh *const key) const
getById() [1/6]
template<class TElem > TElem * NameIdPool< TElem >::getById (const XMLSize_t elemId) inline
Definition at line 121 of file NameIdPool.c.
References XMLExcepts::Pool_InvalidId, and ThrowXMLwithMemMgr.
Referenced by DTDGrammar::getElemDecl().
getById() [2/6]
template<class TElem > TElem* NameIdPool< TElem >::getById (const XMLSize_t elemId)
getById() [3/6]
template<class TElem > TElem* NameIdPool< TElem >::getById (const XMLSize_t elemId)
getById() [4/6]
template<class TElem > const TElem * NameIdPool< TElem >::getById (const XMLSize_t elemId) const inline
Definition at line 132 of file NameIdPool.c.
References XMLExcepts::Pool_InvalidId, and ThrowXMLwithMemMgr.
getById() [5/6]
template<class TElem > const TElem* NameIdPool< TElem >::getById (const XMLSize_t elemId) const
getById() [6/6]
template<class TElem > const TElem* NameIdPool< TElem >::getById (const XMLSize_t elemId) const
getByKey() [1/6]
template<class TElem > TElem * NameIdPool< TElem >::getByKey (const XMLCh *const key) inline
Definition at line 105 of file NameIdPool.c.
Referenced by DTDGrammar::getElemDecl(), DTDGrammar::getElemId(), DTDGrammar::getEntityDecl(), DTDGrammar::getNotationDecl(), and SchemaGrammar::getNotationDecl().
getByKey() [2/6]
template<class TElem > TElem* NameIdPool< TElem >::getByKey (const XMLCh *const key)
getByKey() [3/6]
template<class TElem > TElem* NameIdPool< TElem >::getByKey (const XMLCh *const key)
getByKey() [4/6]
template<class TElem > const TElem * NameIdPool< TElem >::getByKey (const XMLCh *const key) const inline
Definition at line 113 of file NameIdPool.c.
getByKey() [5/6]
template<class TElem > const TElem* NameIdPool< TElem >::getByKey (const XMLCh *const key) const
getByKey() [6/6]
template<class TElem > const TElem* NameIdPool< TElem >::getByKey (const XMLCh *const key) const
getMemoryManager() [1/3]
template<class TElem > MemoryManager * NameIdPool< TElem >::getMemoryManager inline
Definition at line 143 of file NameIdPool.c.
getMemoryManager() [2/3]
template<class TElem > MemoryManager* NameIdPool< TElem >::getMemoryManager () const
getMemoryManager() [3/3]
template<class TElem > MemoryManager* NameIdPool< TElem >::getMemoryManager () const
operator=() [1/3]
template<class TElem > NameIdPool<TElem>& NameIdPool< TElem >::operator= (const NameIdPool< TElem > &) private
operator=() [2/3]
template<class TElem > NameIdPool<TElem>& NameIdPool< TElem >::operator= (const NameIdPool< TElem > &) private
operator=() [3/3]
template<class TElem > NameIdPool<TElem>& NameIdPool< TElem >::operator= (const NameIdPool< TElem > &) private
put() [1/3]
template<class TElem > XMLSize_t NameIdPool< TElem >::put (TElem *const valueToAdopt)
Definition at line 152 of file NameIdPool.c.
References XMLExcepts::Pool_ElemAlreadyExists, and ThrowXMLwithMemMgr1.
Referenced by DTDGrammar::putElemDecl(), DTDGrammar::putEntityDecl(), DTDGrammar::putNotationDecl(), and SchemaGrammar::putNotationDecl().
put() [2/3]
template<class TElem > XMLSize_t NameIdPool< TElem >::put (TElem *const valueToAdopt)
put() [3/3]
template<class TElem > XMLSize_t NameIdPool< TElem >::put (TElem *const valueToAdopt)
removeAll() [1/3]
template<class TElem > void NameIdPool< TElem >::removeAll
Definition at line 90 of file NameIdPool.c.
removeAll() [2/3]
template<class TElem > void NameIdPool< TElem >::removeAll ()
removeAll() [3/3]
template<class TElem > void NameIdPool< TElem >::removeAll ()
Friends And Related Function Documentation
NameIdPoolEnumerator< TElem >
template<class TElem > friend class NameIdPoolEnumerator< TElem > friend
Definition at line 100 of file NameIdPool.hpp.
Member Data Documentation
fBucketList
template<class TElem > RefHashTableOf< TElem > NameIdPool< TElem >::fBucketList private
Definition at line 142 of file NameIdPool.hpp.
fIdCounter
template<class TElem > XMLSize_t NameIdPool< TElem >::fIdCounter private
Definition at line 141 of file NameIdPool.hpp.
fIdPtrs
template<class TElem > TElem ** NameIdPool< TElem >::fIdPtrs private
Definition at line 139 of file NameIdPool.hpp.
Referenced by NameIdPool< TElem >::NameIdPool().
fIdPtrsCount
template<class TElem > XMLSize_t NameIdPool< TElem >::fIdPtrsCount private
Definition at line 140 of file NameIdPool.hpp.
Referenced by NameIdPool< TElem >::NameIdPool().
fMemoryManager
template<class TElem > MemoryManager * NameIdPool< TElem >::fMemoryManager private
Definition at line 138 of file NameIdPool.hpp.
Referenced by NameIdPool< TElem >::NameIdPool().
The documentation for this class was generated from the following files:
src/libs/xerces-c/macx/include/xercesc/util/NameIdPool.hpp
src/libs/xerces-c/macx/include/xercesc/util/NameIdPool.c