Seamly2D: src/test/CollectionTest/tst_seamlymecommandline.cpp File Reference
tst_seamlymecommandline.cpp File Reference
#include "tst_seamlymecommandline.h"
#include "../vmisc/vsysexits.h"
#include "../vmisc/logging.h"
#include <QtTest>
Variables
const QString tmpTestFolder = QStringLiteral("tst_seamlyme_tmp")
Variable Documentation
tmpTestFolder
const QString tmpTestFolder = QStringLiteral("tst_seamlyme_tmp")
Definition at line 62 of file tst_seamlymecommandline.cpp.
Referenced by TST_SeamlyMeCommandLine::cleanupTestCase(), TST_SeamlyMeCommandLine::initTestCase(), and TST_SeamlyMeCommandLine::OpenMeasurements().