Seamly2D: VCurveLength Class Reference
VCurveLength Class Reference
#include <vcurvelength.h>
Public Member Functions
VCurveLength ()
VCurveLength (const quint32 &id, const quint32 &parentId, const VAbstractCurve *curve, Unit patternUnit)
VCurveLength (const quint32 &id, const quint32 &parentId, const QString &baseCurveName, const VSpline &spl, Unit patternUnit, qint32 segment)
VCurveLength (const VCurveLength &var)
VCurveLength & operator= (const VCurveLength &var)
virtual ~VCurveLength () Q_DECL_OVERRIDE
Public Member Functions inherited from VCurveVariable
VCurveVariable ()
VCurveVariable (const quint32 &id, const quint32 &parentId)
VCurveVariable (const VCurveVariable &var)
virtual ~VCurveVariable () Q_DECL_OVERRIDE
VCurveVariable & operator= (const VCurveVariable &var)
void Swap (VCurveVariable &var) Q_DECL_NOTHROW
virtual bool Filter (quint32 id) Q_DECL_OVERRIDE
quint32 GetId () const
void SetId (const quint32 &id)
quint32 GetParentId () const
void SetParentId (const quint32 &value)
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool isNotUsed () const
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
Definition at line 66 of file vcurvelength.h.
Constructor & Destructor Documentation
VCurveLength() [1/4]
VCurveLength::VCurveLength ()
Definition at line 63 of file vcurvelength.cpp.
References CurveLength, and VInternalVariable::SetType().
VCurveLength() [2/4]
VCurveLength::VCurveLength (const quint32 & id, const quint32 & parentId, const VAbstractCurve * curve, Unit patternUnit)
Definition at line 70 of file vcurvelength.cpp.
References CurveLength, FromPixel(), VAbstractCurve::GetLength(), VGObject::name(), SCASSERT, VInternalVariable::SetName(), VInternalVariable::SetType(), and VInternalVariable::SetValue().
VCurveLength() [3/4]
VCurveLength::VCurveLength (const quint32 & id, const quint32 & parentId, const QString & baseCurveName, const VSpline & spl, Unit patternUnit, qint32 segment)
Definition at line 80 of file vcurvelength.cpp.
References CurveLength, FromPixel(), VSpline::GetLength(), SCASSERT, seg_, VInternalVariable::SetName(), VInternalVariable::SetType(), and VInternalVariable::SetValue().
VCurveLength() [4/4]
VCurveLength::VCurveLength (const VCurveLength & var)
Definition at line 92 of file vcurvelength.cpp.
~VCurveLength()
VCurveLength::~VCurveLength () virtual
Definition at line 108 of file vcurvelength.cpp.
Member Function Documentation
operator=()
VCurveLength & VCurveLength::operator= (const VCurveLength & var)
Definition at line 97 of file vcurvelength.cpp.
References VCurveVariable::operator=().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/vcurvelength.h
src/libs/vpatterndb/variables/vcurvelength.cpp