Seamly2D: ResizeHandlesItem Class Reference
ResizeHandlesItem Class Reference
#include <resize_handle.h>
Classes
class HandleItem
Public Types
enum { Type = UserType + static_cast<int>(Vis::ResizeHandlesItem) }
Signals
void sizeChanged (QRectF rect)
void setStatusMessage (QString message)
Public Member Functions
ResizeHandlesItem (QGraphicsItem *parent=nullptr, qreal minDimension=16, qreal maxDimension=16000)
virtual ~ResizeHandlesItem ()=default
virtual int type () const Q_DECL_OVERRIDE
QRectF boundingRect () const override
boundingRect get item's boundingrect.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
paint handle item painting.
void setTopLeft (const QPointF &pos)
void setTop (qreal y)
void setTopRight (const QPointF &pos)
void setRight (qreal x)
void setBottomRight (const QPointF &pos)
void setBottom (qreal y)
void setBottomLeft (const QPointF &pos)
void setLeft (qreal x)
void setParentRect (const QRectF &rect)
void setLockAspectRatio (bool lock)
void parentIsLocked (bool lock)
void setParentRotation (qreal rotation)
void setLimitDimensions (qreal min, qreal max)
Private Member Functions
void updateHandlePositions ()
updateHandlePositions update handle positions on new parent bounding rect.
Private Attributes
QList< HandleItem * > m_handleItems
QRectF m_parentRect
bool m_lockAspectRatio
bool m_parentIsLocked
qreal m_parentRotation
qreal m_minDimension
qreal m_maxDimension
Detailed Description
Definition at line 42 of file resize_handle.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 81 of file resize_handle.h.
Constructor & Destructor Documentation
ResizeHandlesItem()
ResizeHandlesItem::ResizeHandlesItem (QGraphicsItem * parent = nullptr, qreal minDimension = 16, qreal maxDimension = 16000) explicit
ResizeHandlesItem Constructor.
Definition at line 43 of file resize_handle.cpp.
References Bottom, BottomLeft, BottomRight, Left, m_handleItems, m_parentRect, Right, Top, TopLeft, TopRight, and updateHandlePositions().
~ResizeHandlesItem()
virtual ResizeHandlesItem::~ResizeHandlesItem () virtual default
Member Function Documentation
boundingRect()
QRectF ResizeHandlesItem::boundingRect () const override
boundingRect get item's boundingrect.
Returns
QRectF.
Definition at line 72 of file resize_handle.cpp.
References HANDLE_SIZE.
Referenced by ResizeHandlesItem::HandleItem::paint().
paint()
void ResizeHandlesItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
paint handle item painting.
Parameters
QPainter painter.
QStyleOptionGraphicsItem option.
Returns
void.
Definition at line 127 of file resize_handle.cpp.
parentIsLocked()
void ResizeHandlesItem::parentIsLocked (bool lock)
Definition at line 93 of file resize_handle.cpp.
References HANDLE_SIZE, m_handleItems, m_parentIsLocked, and m_parentRect.
Referenced by ImageItem::ImageItem(), and ImageItem::updateImageAndHandles().
setBottom()
void ResizeHandlesItem::setBottom (qreal y)
Definition at line 143 of file resize_handle.cpp.
setBottomLeft()
void ResizeHandlesItem::setBottomLeft (const QPointF & pos)
Definition at line 148 of file resize_handle.cpp.
setBottomRight()
void ResizeHandlesItem::setBottomRight (const QPointF & pos)
Definition at line 147 of file resize_handle.cpp.
setLeft()
void ResizeHandlesItem::setLeft (qreal x)
Definition at line 144 of file resize_handle.cpp.
setLimitDimensions()
void ResizeHandlesItem::setLimitDimensions (qreal min, qreal max)
Definition at line 115 of file resize_handle.cpp.
References m_maxDimension, and m_minDimension.
setLockAspectRatio()
void ResizeHandlesItem::setLockAspectRatio (bool lock)
Definition at line 87 of file resize_handle.cpp.
References m_lockAspectRatio.
Referenced by ImageItem::ImageItem(), and ImageItem::updateImageAndHandles().
setParentRect()
void ResizeHandlesItem::setParentRect (const QRectF & rect)
Definition at line 79 of file resize_handle.cpp.
References m_parentRect, and updateHandlePositions().
Referenced by ImageItem::updateImageAndHandles().
setParentRotation()
void ResizeHandlesItem::setParentRotation (qreal rotation)
Definition at line 108 of file resize_handle.cpp.
References m_parentRotation.
Referenced by ImageItem::ImageItem(), and ImageItem::updateImageAndHandles().
setRight()
void ResizeHandlesItem::setRight (qreal x)
Definition at line 142 of file resize_handle.cpp.
setStatusMessage
void ResizeHandlesItem::setStatusMessage (QString message) signal
Referenced by ImageItem::ImageItem().
setTop()
void ResizeHandlesItem::setTop (qreal y)
Definition at line 141 of file resize_handle.cpp.
setTopLeft()
void ResizeHandlesItem::setTopLeft (const QPointF & pos)
Definition at line 145 of file resize_handle.cpp.
setTopRight()
void ResizeHandlesItem::setTopRight (const QPointF & pos)
Definition at line 146 of file resize_handle.cpp.
sizeChanged
void ResizeHandlesItem::sizeChanged (QRectF rect) signal
Referenced by ImageItem::ImageItem().
type()
virtual int ResizeHandlesItem::type () const inline virtual
Definition at line 80 of file resize_handle.h.
References Type.
updateHandlePositions()
void ResizeHandlesItem::updateHandlePositions () private
updateHandlePositions update handle positions on new parent bounding rect.
Returns
void.
Definition at line 154 of file resize_handle.cpp.
References Bottom, BottomLeft, BottomRight, Center, Left, ResizeHandlesItem::HandleItem::position(), Right, Top, TopLeft, and TopRight.
Referenced by ResizeHandlesItem(), and setParentRect().
Member Data Documentation
m_handleItems
QList<HandleItem*> ResizeHandlesItem::m_handleItems private
Definition at line 107 of file resize_handle.h.
Referenced by parentIsLocked(), and ResizeHandlesItem().
m_lockAspectRatio
bool ResizeHandlesItem::m_lockAspectRatio private
Definition at line 109 of file resize_handle.h.
Referenced by setLockAspectRatio().
m_maxDimension
qreal ResizeHandlesItem::m_maxDimension private
Definition at line 113 of file resize_handle.h.
Referenced by ResizeHandlesItem::HandleItem::limitPosition(), and setLimitDimensions().
m_minDimension
qreal ResizeHandlesItem::m_minDimension private
Definition at line 112 of file resize_handle.h.
Referenced by ResizeHandlesItem::HandleItem::limitPosition(), and setLimitDimensions().
m_parentIsLocked
bool ResizeHandlesItem::m_parentIsLocked private
Definition at line 110 of file resize_handle.h.
Referenced by ResizeHandlesItem::HandleItem::HandleItem(), and parentIsLocked().
m_parentRect
QRectF ResizeHandlesItem::m_parentRect private
Definition at line 108 of file resize_handle.h.
Referenced by parentIsLocked(), ResizeHandlesItem(), and setParentRect().
m_parentRotation
qreal ResizeHandlesItem::m_parentRotation private
Definition at line 111 of file resize_handle.h.
Referenced by setParentRotation().
The documentation for this class was generated from the following files:
src/libs/vwidgets/resize_handle.h
src/libs/vwidgets/resize_handle.cpp