Seamly2D: VisToolPointFromArcAndTangent Class Reference
VisToolPointFromArcAndTangent Class Reference
#include <vistoolpointfromarcandtangent.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolPointFromArcAndTangent) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolPointFromArcAndTangent (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolPointFromArcAndTangent ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setArcId (const quint32 &value)
void setCrossPoint (const CrossCirclesPoint &value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Member Functions
void FindRays (const QPointF &p, const VArc *arc)
Private Attributes
quint32 arcId
CrossCirclesPoint crossPoint
VScaledEllipse * point
VScaledEllipse * tangent
VCurvePathItem * arcPath
VScaledLine * tangentLine2
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 69 of file vistoolpointfromarcandtangent.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 82 of file vistoolpointfromarcandtangent.h.
Constructor & Destructor Documentation
VisToolPointFromArcAndTangent()
VisToolPointFromArcAndTangent::VisToolPointFromArcAndTangent (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 73 of file vistoolpointfromarcandtangent.cpp.
References arcPath, FirstPoint, Visualization::InitPoint(), Visualization::mainColor, point, Visualization::supportColor, tangent, and tangentLine2.
~VisToolPointFromArcAndTangent()
virtual VisToolPointFromArcAndTangent::~VisToolPointFromArcAndTangent () virtual default
Member Function Documentation
FindRays()
void VisToolPointFromArcAndTangent::FindRays (const QPointF & p, const VArc * arc) private
Definition at line 119 of file vistoolpointfromarcandtangent.cpp.
References VGObject::ContactPoints(), VisLine::DrawRay(), VAbstractArc::GetCenter(), VArc::GetRadius(), VAbstractCurve::IsIntersectLine(), Visualization::supportColor, and tangentLine2.
Referenced by RefreshGeometry().
RefreshGeometry()
void VisToolPointFromArcAndTangent::RefreshGeometry () virtual
Implements Visualization.
Definition at line 84 of file vistoolpointfromarcandtangent.cpp.
References arcId, arcPath, crossPoint, Visualization::data, Visualization::DrawPath(), Visualization::DrawPoint(), VToolPointFromArcAndTangent::FindPoint(), FindRays(), VContainer::GeometricObject(), Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, point, Visualization::supportColor, and tangent.
Referenced by DialogPointFromArcAndTangent::ChosenObject(), DialogPointFromArcAndTangent::SaveData(), and VToolPointFromArcAndTangent::SetVisualization().
setArcId()
void VisToolPointFromArcAndTangent::setArcId (const quint32 & value)
Definition at line 107 of file vistoolpointfromarcandtangent.cpp.
References arcId.
Referenced by DialogPointFromArcAndTangent::ChosenObject(), DialogPointFromArcAndTangent::SaveData(), DialogPointFromArcAndTangent::SetArcId(), and VToolPointFromArcAndTangent::SetVisualization().
setCrossPoint()
void VisToolPointFromArcAndTangent::setCrossPoint (const CrossCirclesPoint & value)
Definition at line 113 of file vistoolpointfromarcandtangent.cpp.
References crossPoint.
Referenced by DialogPointFromArcAndTangent::SaveData(), DialogPointFromArcAndTangent::setCirclesCrossPoint(), and VToolPointFromArcAndTangent::SetVisualization().
type()
virtual int VisToolPointFromArcAndTangent::type () const inline virtual
Reimplemented from VisLine.
Definition at line 81 of file vistoolpointfromarcandtangent.h.
References Type.
Member Data Documentation
arcId
quint32 VisToolPointFromArcAndTangent::arcId private
Definition at line 85 of file vistoolpointfromarcandtangent.h.
Referenced by RefreshGeometry(), and setArcId().
arcPath
VCurvePathItem* VisToolPointFromArcAndTangent::arcPath private
Definition at line 89 of file vistoolpointfromarcandtangent.h.
Referenced by RefreshGeometry(), and VisToolPointFromArcAndTangent().
crossPoint
CrossCirclesPoint VisToolPointFromArcAndTangent::crossPoint private
Definition at line 86 of file vistoolpointfromarcandtangent.h.
Referenced by RefreshGeometry(), and setCrossPoint().
point
VScaledEllipse* VisToolPointFromArcAndTangent::point private
Definition at line 87 of file vistoolpointfromarcandtangent.h.
Referenced by RefreshGeometry(), and VisToolPointFromArcAndTangent().
tangent
VScaledEllipse* VisToolPointFromArcAndTangent::tangent private
Definition at line 88 of file vistoolpointfromarcandtangent.h.
Referenced by RefreshGeometry(), and VisToolPointFromArcAndTangent().
tangentLine2
VScaledLine* VisToolPointFromArcAndTangent::tangentLine2 private
Definition at line 90 of file vistoolpointfromarcandtangent.h.
Referenced by FindRays(), and VisToolPointFromArcAndTangent().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/vistoolpointfromarcandtangent.h
src/libs/vtools/visualization/line/vistoolpointfromarcandtangent.cpp