Seamly2D: GroupsWidget Class Reference
GroupsWidget Class Reference
#include <groups_widget.h>
Public Slots
void updateGroups ()
void showGroups (QMap< quint32, QString > groups)
void showAllGroups ()
void hideAllGroups ()
void lockAllGroups ()
void unlockAllGroups ()
void addGroupToList ()
void deleteGroupFromList ()
void editGroup ()
quint32 getGroupId ()
QString getCurrentGroupName ()
void setAddGroupEnabled (bool value)
void clear ()
Public Member Functions
GroupsWidget (VContainer *data, VAbstractPattern *doc, QWidget *parent=nullptr)
virtual ~GroupsWidget ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
changeEvent Handle language change event to retranslate the widget's ui.
Private Slots
void groupVisibilityChanged (int row, int column)
void groupLockChanged (int row, int column)
void renameGroup (int row, int column)
void groupContextMenu (const QPoint &pos)
void draftBlockHasGroups (bool value)
Private Member Functions
void fillTable (const QMap< quint32, GroupAttributes > &groups)
void fillGroupItemList ()
void addGroupItem (const quint32 &toolId, const quint32 &objId, const Tool &tooltype)
addGroupItem Add group item with description in listwidget.
void groupItemContextMenu (const QPoint &pos)
ContextMenu show context menu for group objects.
void cellClicked (int row, int column)
cellClicked Handle clicking of table cell.
void cellDoubleClicked (int row, int column)
cellDoubleClicked Handle double clicking of table cell.
void itemDoubleClicked (QListWidgetItem *item)
Handle double clicking of list item.
void zoomToObject (QSharedPointer< VPointF > point)
zoomToObject zoom to selected (point) object.
void setGroupVisibility (QTableWidgetItem *item, const quint32 &groupId, const bool &visible)
QString getPointName (quint32 pointId)
getPointName get the name of the point by tool id.
quint32 attrUInt (const QDomElement &domElement, const QString &name)
attrUInt get unsigned integer attribute.
QString getObjName (quint32 id)
getObjName get the name of the graphics object.
void splitterMoved (int pos, int index)
splitterMoved Save splitter state whenever it's moved.
void headerClicked (int index)
headerClicked Sort state whenever header section clicked.
Private Attributes
Ui::GroupsWidget * ui
VAbstractPattern * m_doc
VContainer * m_data
bool m_patternHasGroups
quint32 m_currentGroupId
Detailed Description
Definition at line 72 of file groups_widget.h.
Constructor & Destructor Documentation
GroupsWidget()
GroupsWidget::GroupsWidget (VContainer * data, VAbstractPattern * doc, QWidget * parent = nullptr) explicit
Definition at line 104 of file groups_widget.cpp.
References addGroupToList(), cellClicked(), cellDoubleClicked(), deleteGroupFromList(), draftBlockHasGroups(), editGroup(), fillGroupItemList(), groupContextMenu(), groupItemContextMenu(), headerClicked(), hideAllGroups(), itemDoubleClicked(), lockAllGroups(), VAbstractPattern::patternHasGroups(), renameGroup(), showAllGroups(), splitterMoved(), and unlockAllGroups().
~GroupsWidget()
GroupsWidget::~GroupsWidget () virtual
Definition at line 147 of file groups_widget.cpp.
References ui.
Member Function Documentation
addGroupItem()
QT_WARNING_PUSH void GroupsWidget::addGroupItem (const quint32 & toolId, const quint32 & objId, const Tool & tooltype) private
addGroupItem Add group item with description in listwidget.
Parameters
toolID ToolID of item to add to list.
objId ObjectID of item to add to list.
tooltype Tooltype of item to add to list.
Definition at line 740 of file groups_widget.cpp.
References AbstractSpline, AlongLine, AnchorPoint, Arc, ArcIntersectAxis, ArcWithLength, Arrow, AttrArc, AttrDartP1, AttrDartP2, AttrDartP3, AttrFirstPoint, AttrSecondPoint, VToolCutSpline::AttrSpline, VToolCutSplinePath::AttrSplinePath, BasePoint, Bisector, CubicBezier, CubicBezierPath, CurveIntersectAxis, Cut, CutArc, CutSpline, CutSplinePath, DoublePoint, EllipticalArc, EndLine, VExceptionBadId::ErrorMessage(), Group, Height, InsertNodes, InternalPath, LAST_ONE_DO_NOT_USE, Line, LineIntersect, LineIntersectAxis, LinePoint, Midpoint, MirrorByAxis, MirrorByLine, Move, NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, Normal, NULL_ID, Piece, PointFromArcAndTangent, PointFromCircleAndTangent, PointOfContact, PointOfIntersection, PointOfIntersectionArcs, PointOfIntersectionCircles, PointOfIntersectionCurves, Rotation, SCASSERT, ShoulderPoint, SinglePoint, Spline, SplinePath, splPath, Triangle, TrueDarts, and Union.
Referenced by fillGroupItemList().
addGroupToList
void GroupsWidget::addGroupToList () slot
Definition at line 335 of file groups_widget.cpp.
References VAbstractPattern::createGroup(), VContainer::getNextId(), VAbstractPattern::groupNameExists(), m_doc, NULL_ID, qApp, SCASSERT, updateGroups(), and AddGroup::updateGroups().
Referenced by MainWindow::addGroupToList(), and GroupsWidget().
attrUInt()
quint32 GroupsWidget::attrUInt (const QDomElement & domElement, const QString & name) private
attrUInt get unsigned integer attribute.
Parameters
domElement Dom Element.
name Name of Attribute.
Returns
unsigned interger.
Definition at line 1063 of file groups_widget.cpp.
References VDomDocument::GetParametrUInt(), and m_doc.
Referenced by itemDoubleClicked().
cellClicked()
void GroupsWidget::cellClicked (int row, int column) private
cellClicked Handle clicking of table cell.
Parameters
row row of selected table widget item.
column column of selected table widget item.
Definition at line 1209 of file groups_widget.cpp.
References fillGroupItemList(), VAbstractPattern::getGroupLock(), groupLockChanged(), groupVisibilityChanged(), m_doc, and ui.
Referenced by GroupsWidget().
cellDoubleClicked()
void GroupsWidget::cellDoubleClicked (int row, int column) private
cellDoubleClicked Handle double clicking of table cell.
Parameters
row row of selected table widget item.
column column of selected table widget item.
Definition at line 1239 of file groups_widget.cpp.
References editGroup(), VAbstractPattern::getGroupLock(), m_doc, and ui.
Referenced by GroupsWidget().
changeEvent()
void GroupsWidget::changeEvent (QEvent * event) protected virtual
changeEvent Handle language change event to retranslate the widget's ui.
Parameters
event QEvent sent to widget.
Definition at line 157 of file groups_widget.cpp.
References ui, and updateGroups().
clear
void GroupsWidget::clear () slot
Definition at line 669 of file groups_widget.cpp.
References ui.
Referenced by MainWindow::CleanLayout().
deleteGroupFromList
void GroupsWidget::deleteGroupFromList () slot
Definition at line 391 of file groups_widget.cpp.
References getGroupId(), VAbstractPattern::getGroupLock(), m_doc, qApp, ui, updateGroups(), and DelGroup::updateGroups().
Referenced by MainWindow::deleteGroupFromList(), and GroupsWidget().
draftBlockHasGroups
void GroupsWidget::draftBlockHasGroups (bool value) private slot
Definition at line 651 of file groups_widget.cpp.
References m_patternHasGroups, and ui.
Referenced by GroupsWidget().
editGroup
void GroupsWidget::editGroup () slot
Definition at line 410 of file groups_widget.cpp.
References VAbstractPattern::getGroupColor(), VAbstractPattern::getGroupLineType(), VAbstractPattern::getGroupLineWeight(), VAbstractPattern::getGroupLock(), VAbstractPattern::getGroupName(), VAbstractPattern::groupNameExists(), m_doc, NULL_ID, qApp, VAbstractPattern::setGroupColor(), VAbstractPattern::setGroupLineType(), VAbstractPattern::setGroupLineWeight(), VAbstractPattern::setGroupName(), ui, and updateGroups().
Referenced by cellDoubleClicked(), MainWindow::editGroup(), groupContextMenu(), and GroupsWidget().
fillGroupItemList()
void GroupsWidget::fillGroupItemList () private
Definition at line 702 of file groups_widget.cpp.
References addGroupItem(), getCurrentGroupName(), VAbstractPattern::getGroupByName(), VAbstractPattern::getGroupObjHistory(), m_doc, VAbstractPattern::parseItemElement(), and ui.
Referenced by cellClicked(), GroupsWidget(), and updateGroups().
fillTable()
void GroupsWidget::fillTable (const QMap< quint32, GroupAttributes > & groups) private
Definition at line 563 of file groups_widget.cpp.
References GroupAttributes::color, VAbstractPattern::isGroupEmpty(), GroupAttributes::locked, m_doc, makeHeaderName(), GroupAttributes::name, setGroupVisibility(), ui, and GroupAttributes::visible.
Referenced by updateGroups().
getCurrentGroupName
QString GroupsWidget::getCurrentGroupName () slot
Definition at line 689 of file groups_widget.cpp.
References ui.
Referenced by fillGroupItemList().
getGroupId
quint32 GroupsWidget::getGroupId () slot
Definition at line 676 of file groups_widget.cpp.
References ui.
Referenced by deleteGroupFromList(), groupItemContextMenu(), and zoomToObject().
getObjName()
QString GroupsWidget::getObjName (quint32 toolId) private
getObjName get the name of the graphics object.
Parameters
toolId Id of the tool the object belongs to.
Returns
name of object.
Definition at line 1074 of file groups_widget.cpp.
References VException::DetailedInformation(), VExceptionBadId::ErrorMessage(), VContainer::GetGObject(), and m_data.
getPointName()
QT_WARNING_POP QString GroupsWidget::getPointName (quint32 toolId) private
getPointName get the name of the point by tool id.
Parameters
toolId Id of the tool the object belongs to.
Returns
name of point.
Definition at line 1051 of file groups_widget.cpp.
References VContainer::GeometricObject(), and m_data.
groupContextMenu
void GroupsWidget::groupContextMenu (const QPoint & pos) private slot
Definition at line 505 of file groups_widget.cpp.
References editGroup(), VAbstractPattern::getGroupLock(), m_doc, qApp, ui, updateGroups(), and DelGroup::updateGroups().
Referenced by GroupsWidget().
groupItemContextMenu()
void GroupsWidget::groupItemContextMenu (const QPoint & pos) private
ContextMenu show context menu for group objects.
Parameters
pos Mouse position of right click.
Definition at line 1095 of file groups_widget.cpp.
References VAbstractPattern::addGroupItem(), getGroupId(), VAbstractPattern::getGroupLock(), VAbstractPattern::getGroupsContainingItem(), m_doc, qApp, VAbstractPattern::removeGroupItem(), SCASSERT, ui, updateGroups(), MoveGroupItem::updateGroups(), RemoveGroupItem::updateGroups(), and VAbstractMainWindow::updateGroups().
Referenced by GroupsWidget().
groupLockChanged
void GroupsWidget::groupLockChanged (int row, int column) private slot
Definition at line 188 of file groups_widget.cpp.
References VAbstractPattern::getGroupLock(), m_doc, VAbstractPattern::setGroupLock(), and ui.
Referenced by cellClicked().
groupVisibilityChanged
void GroupsWidget::groupVisibilityChanged (int row, int column) private slot
Definition at line 169 of file groups_widget.cpp.
References VAbstractPattern::getGroupLock(), VAbstractPattern::getGroupVisibility(), m_doc, setGroupVisibility(), and ui.
Referenced by cellClicked().
headerClicked()
void GroupsWidget::headerClicked (int index) private
headerClicked Sort state whenever header section clicked.
Parameters
index
Definition at line 1408 of file groups_widget.cpp.
Referenced by GroupsWidget().
hideAllGroups
void GroupsWidget::hideAllGroups () slot
Definition at line 274 of file groups_widget.cpp.
References VAbstractPattern::getGroupLock(), m_doc, setGroupVisibility(), and ui.
Referenced by GroupsWidget(), and MainWindow::hideAllGroups().
itemDoubleClicked()
void GroupsWidget::itemDoubleClicked (QListWidgetItem * item) private
Handle double clicking of list item.
Parameters
item selected list widget item.
Definition at line 1262 of file groups_widget.cpp.
References AllCurves, Arc, AttrFirstPoint, attrUInt(), CubicBezier, CubicBezierPath, Curve, VContainer::DataGObjects(), VDomDocument::elementById(), EllipticalArc, VContainer::GeometricObject(), VContainer::GetGObject(), m_data, m_doc, NULL_ID, Path, Point, Spline, SplinePath, VAbstractPattern::TagLine, Unknown, and zoomToObject().
Referenced by GroupsWidget().
lockAllGroups
void GroupsWidget::lockAllGroups () slot
Definition at line 299 of file groups_widget.cpp.
References m_doc, VAbstractPattern::setGroupLock(), and ui.
Referenced by GroupsWidget(), and MainWindow::lockAllGroups().
renameGroup
void GroupsWidget::renameGroup (int row, int column) private slot
Definition at line 212 of file groups_widget.cpp.
References VAbstractPattern::getGroupLock(), m_doc, VAbstractPattern::setGroupName(), ui, and updateGroups().
Referenced by GroupsWidget().
setAddGroupEnabled
void GroupsWidget::setAddGroupEnabled (bool value) slot
Definition at line 664 of file groups_widget.cpp.
References ui.
Referenced by MainWindow::setWidgetsEnabled().
setGroupVisibility()
void GroupsWidget::setGroupVisibility (QTableWidgetItem * item, const quint32 & groupId, const bool & visible) private
Definition at line 1375 of file groups_widget.cpp.
References m_doc, and VAbstractPattern::setGroupVisibility().
Referenced by fillTable(), groupVisibilityChanged(), hideAllGroups(), showAllGroups(), showGroups(), and zoomToObject().
showAllGroups
void GroupsWidget::showAllGroups () slot
Definition at line 249 of file groups_widget.cpp.
References VAbstractPattern::getGroupLock(), m_doc, setGroupVisibility(), and ui.
Referenced by GroupsWidget(), and MainWindow::showAllGroups().
showGroups
void GroupsWidget::showGroups (QMap< quint32, QString > groups) slot
Definition at line 228 of file groups_widget.cpp.
References setGroupVisibility(), ui, and updateGroups().
Referenced by zoomToObject(), and MainWindow::zoomToPoint().
splitterMoved()
void GroupsWidget::splitterMoved (int pos, int index) private
splitterMoved Save splitter state whenever it's moved.
Parameters
pos
index
Definition at line 1394 of file groups_widget.cpp.
References ui.
Referenced by GroupsWidget().
unlockAllGroups
void GroupsWidget::unlockAllGroups () slot
Definition at line 317 of file groups_widget.cpp.
References m_doc, VAbstractPattern::setGroupLock(), and ui.
Referenced by GroupsWidget(), and MainWindow::unlockAllGroups().
updateGroups
void GroupsWidget::updateGroups () slot
Definition at line 551 of file groups_widget.cpp.
References fillGroupItemList(), fillTable(), VAbstractPattern::getGroups(), m_doc, and ui.
Referenced by MainWindow::addDraftBlock(), addGroupToList(), MainWindow::changeDraftBlock(), changeEvent(), deleteGroupFromList(), editGroup(), groupContextMenu(), groupItemContextMenu(), renameGroup(), showGroups(), and MainWindow::updateGroups().
zoomToObject()
void GroupsWidget::zoomToObject (QSharedPointer< VPointF > point) private
zoomToObject zoom to selected (point) object.
Parameters
point If selected list item is a point use the item's toolId. if the list item is a curve or line then use the tool's first point.
Definition at line 1341 of file groups_widget.cpp.
References getGroupId(), VAbstractPattern::getGroupsContainingItem(), VAbstractPattern::getTool(), m_doc, NULL_ID, qApp, SCASSERT, setGroupVisibility(), showGroups(), ui, and VMainGraphicsView::zoomByScale().
Referenced by itemDoubleClicked().
Member Data Documentation
m_currentGroupId
quint32 GroupsWidget::m_currentGroupId private
Definition at line 110 of file groups_widget.h.
m_data
VContainer* GroupsWidget::m_data private
Definition at line 108 of file groups_widget.h.
Referenced by getObjName(), getPointName(), and itemDoubleClicked().
m_doc
VAbstractPattern* GroupsWidget::m_doc private
Definition at line 107 of file groups_widget.h.
Referenced by addGroupToList(), attrUInt(), cellClicked(), cellDoubleClicked(), deleteGroupFromList(), editGroup(), fillGroupItemList(), fillTable(), groupContextMenu(), groupItemContextMenu(), groupLockChanged(), groupVisibilityChanged(), hideAllGroups(), itemDoubleClicked(), lockAllGroups(), renameGroup(), setGroupVisibility(), showAllGroups(), unlockAllGroups(), updateGroups(), and zoomToObject().
m_patternHasGroups
bool GroupsWidget::m_patternHasGroups private
Definition at line 109 of file groups_widget.h.
Referenced by draftBlockHasGroups().
ui
Ui::GroupsWidget* GroupsWidget::ui private
Definition at line 106 of file groups_widget.h.
Referenced by cellClicked(), cellDoubleClicked(), changeEvent(), clear(), deleteGroupFromList(), draftBlockHasGroups(), editGroup(), fillGroupItemList(), fillTable(), getCurrentGroupName(), getGroupId(), groupContextMenu(), groupItemContextMenu(), groupLockChanged(), groupVisibilityChanged(), hideAllGroups(), lockAllGroups(), renameGroup(), setAddGroupEnabled(), showAllGroups(), showGroups(), splitterMoved(), unlockAllGroups(), updateGroups(), zoomToObject(), and ~GroupsWidget().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/groups_widget.h
src/app/seamly2d/dialogs/groups_widget.cpp