Seamly2D: MeasurementVariable Class Reference
MeasurementVariable Class Reference
The MeasurementVariable class keep data row of multisize table.
#include <measurement_variable.h>
Public Member Functions
MeasurementVariable (quint32 index, const QString &name, qreal baseSize, qreal baseHeight, const qreal &base, const qreal &ksize, const qreal &kheight, const QString &gui_text=QString(), const QString &description=QString(), const QString &tagName=QString())
MeasurementVariable create measurement for multisize table.
MeasurementVariable (VContainer *data, quint32 index, const QString &name, const qreal &base, const QString &formula, bool ok, const QString &gui_text=QString(), const QString &description=QString(), const QString &tagName=QString())
MeasurementVariable create measurement for individual table.
MeasurementVariable (const MeasurementVariable &m)
virtual ~MeasurementVariable () Q_DECL_OVERRIDE
MeasurementVariable & operator= (const MeasurementVariable &m)
void Swap (MeasurementVariable &m) Q_DECL_NOTHROW
QString getGuiText () const
getGuiText measurement name for tooltip
QString TagName () const
void setTagName (const QString &tagName)
QString GetFormula () const
bool isCustom () const
int Index () const
bool IsFormulaOk () const
virtual bool isNotUsed () const Q_DECL_OVERRIDE
virtual qreal GetValue () const Q_DECL_OVERRIDE
virtual qreal * GetValue () Q_DECL_OVERRIDE
VContainer * GetData ()
void setSize (qreal *size)
void setHeight (qreal *height)
void SetUnit (const Unit *unit)
qreal GetBase () const
GetBase return value in base size and height.
void SetBase (const qreal &value)
qreal GetKsize () const
GetKsize return increment in sizes.
void SetKsize (const qreal &value)
qreal GetKheight () const
GetKheight return increment in heights.
void SetKheight (const qreal &value)
Public Member Functions inherited from VVariable
VVariable ()
VVariable (const QString &name, const QString &description=QString())
VVariable (const VVariable &var)
virtual ~VVariable () Q_DECL_OVERRIDE
VVariable & operator= (const VVariable &var)
void Swap (VVariable &var) Q_DECL_NOTHROW
QString GetDescription () const
void SetDescription (const QString &desc)
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool Filter (quint32 id)
Static Public Member Functions
static QStringList ListHeights (QMap< GHeights, bool > heights, Unit patternUnit)
static QStringList ListSizes (QMap< GSizes, bool > sizes, Unit patternUnit)
static QStringList WholeListHeights (Unit patternUnit)
static QStringList WholeListSizes (Unit patternUnit)
static bool IsGradationSizeValid (const QString &size)
static bool IsGradationHeightValid (const QString &height)
Private Member Functions
qreal CalcValue () const
Static Private Member Functions
static void ListValue (QStringList &list, qreal value, Unit patternUnit)
Private Attributes
QSharedDataPointer< MeasurementVariableData > d
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
The MeasurementVariable class keep data row of multisize table.
Definition at line 77 of file measurement_variable.h.
Constructor & Destructor Documentation
MeasurementVariable() [1/3]
MeasurementVariable::MeasurementVariable (quint32 index, const QString & name, qreal baseSize, qreal baseHeight, const qreal & base, const qreal & ksize, const qreal & kheight, const QString & gui_text = QString(), const QString & description = QString(), const QString & tagName = QString())
MeasurementVariable create measurement for multisize table.
Parameters
name measurement's name
base value in base size and height
ksize increment in sizes
kheight increment in heights
gui_text shor tooltip for user
description measurement full description
tagName measurement's tag name in file
Definition at line 85 of file measurement_variable.cpp.
References d, Measurement, VInternalVariable::SetType(), and VInternalVariable::SetValue().
MeasurementVariable() [2/3]
MeasurementVariable::MeasurementVariable (VContainer * data, quint32 index, const QString & name, const qreal & base, const QString & formula, bool ok, const QString & gui_text = QString(), const QString & description = QString(), const QString & tagName = QString())
MeasurementVariable create measurement for individual table.
Parameters
name measurement's name
base value in base size and height
gui_text shor tooltip for user
description measurement full description
tagName measurement's tag name in file
Definition at line 104 of file measurement_variable.cpp.
References Measurement, VInternalVariable::SetType(), and VInternalVariable::SetValue().
MeasurementVariable() [3/3]
MeasurementVariable::MeasurementVariable (const MeasurementVariable & m)
Definition at line 115 of file measurement_variable.cpp.
~MeasurementVariable()
MeasurementVariable::~MeasurementVariable () virtual
Definition at line 133 of file measurement_variable.cpp.
Member Function Documentation
CalcValue()
qreal MeasurementVariable::CalcValue () const private
Definition at line 235 of file measurement_variable.cpp.
References Cm, d, VInternalVariable::GetValue(), Inch, and UnitConvertor().
Referenced by GetValue().
GetBase()
qreal MeasurementVariable::GetBase () const
GetBase return value in base size and height.
Returns
value
Definition at line 359 of file measurement_variable.cpp.
References d.
GetData()
VContainer * MeasurementVariable::GetData ()
Definition at line 331 of file measurement_variable.cpp.
References d.
GetFormula()
QString MeasurementVariable::GetFormula () const
Definition at line 288 of file measurement_variable.cpp.
References d.
getGuiText()
QString MeasurementVariable::getGuiText () const
getGuiText measurement name for tooltip
Returns
measurement name
Definition at line 270 of file measurement_variable.cpp.
References d.
GetKheight()
qreal MeasurementVariable::GetKheight () const
GetKheight return increment in heights.
Returns
increment
Definition at line 392 of file measurement_variable.cpp.
References d.
GetKsize()
qreal MeasurementVariable::GetKsize () const
GetKsize return increment in sizes.
Returns
increment
Definition at line 375 of file measurement_variable.cpp.
References d.
GetValue() [1/2]
qreal MeasurementVariable::GetValue () const virtual
Reimplemented from VInternalVariable.
Definition at line 318 of file measurement_variable.cpp.
References CalcValue().
GetValue() [2/2]
qreal * MeasurementVariable::GetValue () virtual
Reimplemented from VInternalVariable.
Definition at line 324 of file measurement_variable.cpp.
References CalcValue(), VInternalVariable::GetValue(), and VInternalVariable::SetValue().
Index()
int MeasurementVariable::Index () const
Definition at line 300 of file measurement_variable.cpp.
References d.
isCustom()
bool MeasurementVariable::isCustom () const
Definition at line 294 of file measurement_variable.cpp.
References CustomMSign, and VInternalVariable::GetName().
IsFormulaOk()
bool MeasurementVariable::IsFormulaOk () const
Definition at line 306 of file measurement_variable.cpp.
References d.
IsGradationHeightValid()
bool MeasurementVariable::IsGradationHeightValid (const QString & height) static
Definition at line 221 of file measurement_variable.cpp.
References Cm, and WholeListHeights().
Referenced by VCommandLine::OptGradationHeight(), and MApplication::ParseCommandLine().
IsGradationSizeValid()
bool MeasurementVariable::IsGradationSizeValid (const QString & size) static
Definition at line 207 of file measurement_variable.cpp.
References Cm, and WholeListSizes().
Referenced by VCommandLine::OptGradationSize(), and MApplication::ParseCommandLine().
isNotUsed()
bool MeasurementVariable::isNotUsed () const virtual
Reimplemented from VInternalVariable.
Definition at line 312 of file measurement_variable.cpp.
References d.
ListHeights()
QStringList MeasurementVariable::ListHeights (QMap< GHeights, bool > heights, Unit patternUnit) static
Definition at line 137 of file measurement_variable.cpp.
References ALL, ListValue(), and WholeListHeights().
Referenced by MainWindow::initStatusBar().
ListSizes()
QStringList MeasurementVariable::ListSizes (QMap< GSizes, bool > sizes, Unit patternUnit) static
Definition at line 159 of file measurement_variable.cpp.
References ALL, ListValue(), and WholeListSizes().
Referenced by MainWindow::initStatusBar().
ListValue()
void MeasurementVariable::ListValue (QStringList & list, qreal value, Unit patternUnit) static private
Definition at line 258 of file measurement_variable.cpp.
References Cm, and UnitConvertor().
Referenced by ListHeights(), ListSizes(), WholeListHeights(), and WholeListSizes().
operator=()
MeasurementVariable & MeasurementVariable::operator= (const MeasurementVariable & m)
Definition at line 121 of file measurement_variable.cpp.
References d, and VVariable::operator=().
SetBase()
void MeasurementVariable::SetBase (const qreal & value)
Definition at line 365 of file measurement_variable.cpp.
References d.
setHeight()
void MeasurementVariable::setHeight (qreal * height)
Definition at line 343 of file measurement_variable.cpp.
References d.
SetKheight()
void MeasurementVariable::SetKheight (const qreal & value)
Definition at line 399 of file measurement_variable.cpp.
References d.
SetKsize()
void MeasurementVariable::SetKsize (const qreal & value)
Definition at line 382 of file measurement_variable.cpp.
References d.
setSize()
void MeasurementVariable::setSize (qreal * size)
Definition at line 337 of file measurement_variable.cpp.
References d.
setTagName()
void MeasurementVariable::setTagName (const QString & tagName)
Definition at line 282 of file measurement_variable.cpp.
References d.
SetUnit()
void MeasurementVariable::SetUnit (const Unit * unit)
Definition at line 349 of file measurement_variable.cpp.
References d.
Swap()
void MeasurementVariable::Swap (MeasurementVariable & m)
Definition at line 71 of file measurement_variable.cpp.
References VVariable::Swap().
TagName()
QString MeasurementVariable::TagName () const
Definition at line 276 of file measurement_variable.cpp.
References d.
WholeListHeights()
QStringList MeasurementVariable::WholeListHeights (Unit patternUnit) static
Definition at line 181 of file measurement_variable.cpp.
References H200, H50, heightStep, and ListValue().
Referenced by NewMeasurementsDialog::initializeHeightsList(), VCommandLine::InitOptions(), TMainWindow::InitWindow(), IsGradationHeightValid(), ListHeights(), MApplication::ParseCommandLine(), and SeamlyMePreferencesConfigurationPage::SeamlyMePreferencesConfigurationPage().
WholeListSizes()
QStringList MeasurementVariable::WholeListSizes (Unit patternUnit) static
Definition at line 194 of file measurement_variable.cpp.
References ListValue(), S22, S72, and sizeStep.
Referenced by NewMeasurementsDialog::initializeSizesList(), VCommandLine::InitOptions(), TMainWindow::InitWindow(), IsGradationSizeValid(), ListSizes(), MApplication::ParseCommandLine(), and SeamlyMePreferencesConfigurationPage::SeamlyMePreferencesConfigurationPage().
Member Data Documentation
d
QSharedDataPointer<MeasurementVariableData> MeasurementVariable::d private
Definition at line 140 of file measurement_variable.h.
Referenced by CalcValue(), GetBase(), GetData(), GetFormula(), getGuiText(), GetKheight(), GetKsize(), Index(), IsFormulaOk(), isNotUsed(), MeasurementVariable(), operator=(), SetBase(), setHeight(), SetKheight(), SetKsize(), setSize(), setTagName(), SetUnit(), and TagName().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/measurement_variable.h
src/libs/vpatterndb/variables/measurement_variable.cpp