Seamly2D: DTDAttDefList Class Reference
DTDAttDefList Class Reference
#include <DTDAttDefList.hpp>
Public Member Functions
DTDAttDefList (RefHashTableOf< DTDAttDef > *const listToUse, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~DTDAttDefList ()
virtual bool isEmpty () const
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const
virtual XMLSize_t getAttDefCount () const
virtual XMLAttDef & getAttDef (XMLSize_t index)
virtual const XMLAttDef & getAttDef (XMLSize_t index) const
DTDAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
DTDAttDefList (RefHashTableOf< DTDAttDef > *const listToUse, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~DTDAttDefList ()
virtual bool isEmpty () const
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const
virtual XMLSize_t getAttDefCount () const
virtual XMLAttDef & getAttDef (XMLSize_t index)
virtual const XMLAttDef & getAttDef (XMLSize_t index) const
DTDAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
DTDAttDefList (RefHashTableOf< DTDAttDef > *const listToUse, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~DTDAttDefList ()
virtual bool isEmpty () const
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const
virtual XMLSize_t getAttDefCount () const
virtual XMLAttDef & getAttDef (XMLSize_t index)
virtual const XMLAttDef & getAttDef (XMLSize_t index) const
DTDAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Public Member Functions inherited from XMLAttDefList
virtual ~XMLAttDefList ()
virtual ~XMLAttDefList ()
virtual ~XMLAttDefList ()
MemoryManager * getMemoryManager () const
MemoryManager * getMemoryManager () const
MemoryManager * getMemoryManager () const
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
void addAttDef (DTDAttDef *toAdd)
DTDAttDefList (const DTDAttDefList &)
DTDAttDefList & operator= (const DTDAttDefList &)
void addAttDef (DTDAttDef *toAdd)
DTDAttDefList (const DTDAttDefList &)
DTDAttDefList & operator= (const DTDAttDefList &)
void addAttDef (DTDAttDef *toAdd)
DTDAttDefList (const DTDAttDefList &)
DTDAttDefList & operator= (const DTDAttDefList &)
Private Attributes
RefHashTableOfEnumerator< DTDAttDef > * fEnum
RefHashTableOf< DTDAttDef > * fList
DTDAttDef ** fArray
XMLSize_t fSize
XMLSize_t fCount
Friends
class DTDElementDecl
Additional Inherited Members
Protected Member Functions inherited from XMLAttDefList
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 47 of file DTDAttDefList.hpp.
Constructor & Destructor Documentation
DTDAttDefList() [1/9]
DTDAttDefList::DTDAttDefList (RefHashTableOf< DTDAttDef > *const listToUse, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~DTDAttDefList() [1/3]
DTDAttDefList::~DTDAttDefList ()
DTDAttDefList() [2/9]
DTDAttDefList::DTDAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
DTDAttDefList() [3/9]
DTDAttDefList::DTDAttDefList (const DTDAttDefList &) private
DTDAttDefList() [4/9]
DTDAttDefList::DTDAttDefList (RefHashTableOf< DTDAttDef > *const listToUse, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~DTDAttDefList() [2/3]
DTDAttDefList::~DTDAttDefList ()
DTDAttDefList() [5/9]
DTDAttDefList::DTDAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
DTDAttDefList() [6/9]
DTDAttDefList::DTDAttDefList (const DTDAttDefList &) private
DTDAttDefList() [7/9]
DTDAttDefList::DTDAttDefList (RefHashTableOf< DTDAttDef > *const listToUse, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~DTDAttDefList() [3/3]
DTDAttDefList::~DTDAttDefList ()
DTDAttDefList() [8/9]
DTDAttDefList::DTDAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
DTDAttDefList() [9/9]
DTDAttDefList::DTDAttDefList (const DTDAttDefList &) private
Member Function Documentation
addAttDef() [1/3]
void DTDAttDefList::addAttDef (DTDAttDef * toAdd) inline private
Definition at line 145 of file DTDAttDefList.hpp.
References XMLAttDefList::getMemoryManager().
addAttDef() [2/3]
void DTDAttDefList::addAttDef (DTDAttDef * toAdd) private
addAttDef() [3/3]
void DTDAttDefList::addAttDef (DTDAttDef * toAdd) private
findAttDef() [1/12]
virtual XMLAttDef* DTDAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [2/12]
virtual XMLAttDef* DTDAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [3/12]
virtual XMLAttDef* DTDAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [4/12]
virtual const XMLAttDef* DTDAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [5/12]
virtual const XMLAttDef* DTDAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [6/12]
virtual const XMLAttDef* DTDAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [7/12]
virtual XMLAttDef* DTDAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [8/12]
virtual XMLAttDef* DTDAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [9/12]
virtual XMLAttDef* DTDAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [10/12]
virtual const XMLAttDef* DTDAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [11/12]
virtual const XMLAttDef* DTDAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [12/12]
virtual const XMLAttDef* DTDAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
getAttDef() [1/6]
virtual XMLAttDef& DTDAttDefList::getAttDef (XMLSize_t index) virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [2/6]
virtual XMLAttDef& DTDAttDefList::getAttDef (XMLSize_t index) virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [3/6]
virtual XMLAttDef& DTDAttDefList::getAttDef (XMLSize_t index) virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [4/6]
virtual const XMLAttDef& DTDAttDefList::getAttDef (XMLSize_t index) const virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [5/6]
virtual const XMLAttDef& DTDAttDefList::getAttDef (XMLSize_t index) const virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [6/6]
virtual const XMLAttDef& DTDAttDefList::getAttDef (XMLSize_t index) const virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDefCount() [1/3]
virtual XMLSize_t DTDAttDefList::getAttDefCount () const virtual
return total number of attributes in this list
Implements XMLAttDefList.
getAttDefCount() [2/3]
virtual XMLSize_t DTDAttDefList::getAttDefCount () const virtual
return total number of attributes in this list
Implements XMLAttDefList.
getAttDefCount() [3/3]
virtual XMLSize_t DTDAttDefList::getAttDefCount () const virtual
return total number of attributes in this list
Implements XMLAttDefList.
isEmpty() [1/3]
virtual bool DTDAttDefList::isEmpty () const virtual
Implements XMLAttDefList.
isEmpty() [2/3]
virtual bool DTDAttDefList::isEmpty () const virtual
Implements XMLAttDefList.
isEmpty() [3/3]
virtual bool DTDAttDefList::isEmpty () const virtual
Implements XMLAttDefList.
operator=() [1/3]
DTDAttDefList& DTDAttDefList::operator= (const DTDAttDefList &) private
operator=() [2/3]
DTDAttDefList& DTDAttDefList::operator= (const DTDAttDefList &) private
References XMLAttDefList::getMemoryManager().
operator=() [3/3]
DTDAttDefList& DTDAttDefList::operator= (const DTDAttDefList &) private
References XMLAttDefList::getMemoryManager().
Friends And Related Function Documentation
DTDElementDecl
DTDElementDecl friend
Definition at line 142 of file DTDAttDefList.hpp.
Member Data Documentation
fArray
DTDAttDef ** DTDAttDefList::fArray private
Definition at line 138 of file DTDAttDefList.hpp.
fCount
XMLSize_t DTDAttDefList::fCount private
Definition at line 140 of file DTDAttDefList.hpp.
fEnum
RefHashTableOfEnumerator< DTDAttDef > * DTDAttDefList::fEnum private
Definition at line 136 of file DTDAttDefList.hpp.
fList
RefHashTableOf< DTDAttDef > * DTDAttDefList::fList private
Definition at line 137 of file DTDAttDefList.hpp.
fSize
XMLSize_t DTDAttDefList::fSize private
Definition at line 139 of file DTDAttDefList.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/DTD/DTDAttDefList.hpp