Seamly2D: ImageTool Class Reference
ImageTool Class Reference
#include <image_tool.h>
Signals
void setStatusMessage (QString message)
Public Member Functions
ImageTool (QObject *parent, VAbstractPattern *doc, VMainGraphicsScene *draftScene, QString filename)
ImageTool (QObject *parent, VAbstractPattern *doc, VMainGraphicsScene *draftScene, DraftImage image)
void addToFile ()
addToFile add tag with informations about image into file.
Public Attributes
bool creationWasSuccessful =false
DraftImage image
ImageItem * imageItem
Protected Slots
void handleDeleteImage (quint32 id)
void handleImageSelected (quint32 id)
Private Member Functions
void addImage ()
void saveOptions (QDomElement &tag)
void saveChanges ()
Private Attributes
VAbstractPattern * m_doc
VMainGraphicsScene * m_draftScene
QDomElement m_oldDomElement
Detailed Description
Definition at line 42 of file image_tool.h.
Constructor & Destructor Documentation
ImageTool() [1/2]
ImageTool::ImageTool (QObject * parent, VAbstractPattern * doc, VMainGraphicsScene * draftScene, QString filename) explicit
Definition at line 81 of file image_tool.cpp.
References addImage(), DraftImage::filename, VContainer::getNextId(), DraftImage::id, image, DraftImage::name, qApp, and DraftImage::units.
ImageTool() [2/2]
ImageTool::ImageTool (QObject * parent, VAbstractPattern * doc, VMainGraphicsScene * draftScene, DraftImage image) explicit
Definition at line 107 of file image_tool.cpp.
References addImage(), VAbstractPattern::AttrName, VAbstractPattern::AttrSource, VDomDocument::elementById(), DraftImage::filename, getImageFilename(), DraftImage::id, image, m_doc, DraftImage::name, VDomDocument::SetAttribute(), and VAbstractPattern::TagDraftImage.
Member Function Documentation
addImage()
void ImageTool::addImage () private
Definition at line 170 of file image_tool.cpp.
References VAbstractPattern::addBackgroundImage(), creationWasSuccessful, ImageItem::deleteImage(), DraftImage::filename, handleDeleteImage(), DraftImage::id, image, imageItem, ImageItem::imageNeedsSave(), m_doc, m_draftScene, saveChanges(), ImageItem::setStatusMessage(), and setStatusMessage().
Referenced by ImageTool().
addToFile()
void ImageTool::addToFile ()
addToFile add tag with informations about image into file.
Definition at line 251 of file image_tool.cpp.
References m_doc, VAbstractPattern::NeedFullParsing(), VUndoCommand::NeedFullParsing(), qApp, saveOptions(), and VAbstractPattern::TagDraftImage.
Referenced by MainWindow::handleImageTool().
handleDeleteImage
void ImageTool::handleDeleteImage (quint32 id) protected slot
Definition at line 198 of file image_tool.cpp.
References ImageItem::deleteImageItem(), imageItem, Utils::CheckableMessageBox::isChecked, m_doc, VAbstractPattern::NeedFullParsing(), VUndoCommand::NeedFullParsing(), qApp, Utils::CheckableMessageBox::setDefaultButton(), Utils::CheckableMessageBox::setIconPixmap(), Utils::CheckableMessageBox::setStandardButtons(), and Utils::CheckableMessageBox::setText().
Referenced by addImage().
handleImageSelected
void ImageTool::handleImageSelected (quint32 id) protected slot
Definition at line 237 of file image_tool.cpp.
References VAbstractPattern::getBackgroundImage(), and m_doc.
saveChanges()
void ImageTool::saveChanges () private
Definition at line 287 of file image_tool.cpp.
References VDomDocument::elementById(), ImageItem::getImage(), DraftImage::id, imageItem, VAbstractPattern::LiteParseTree(), m_doc, VUndoCommand::NeedLiteParsing(), qApp, saveOptions(), SaveToolOptions, and VAbstractPattern::TagDraftImage.
Referenced by addImage().
saveOptions()
void ImageTool::saveOptions (QDomElement & tag) private
Definition at line 264 of file image_tool.cpp.
References DraftImage::aspectLocked, VAbstractPattern::AttrAspectRatio, VAbstractPattern::AttrBasepoint, VAbstractPattern::AttrHeight, VDomDocument::AttrId, VAbstractPattern::AttrLocked, VAbstractPattern::AttrName, VAbstractPattern::AttrOpacity, VAbstractPattern::AttrOrder, VAbstractPattern::AttrRotation, VAbstractPattern::AttrSource, VAbstractPattern::AttrUnits, VAbstractPattern::AttrVisible, VAbstractPattern::AttrWidth, VAbstractPattern::AttrXOffset, VAbstractPattern::AttrXPos, VAbstractPattern::AttrYOffset, VAbstractPattern::AttrYPos, DraftImage::basepoint, DraftImage::filename, ImageItem::getImage(), DraftImage::height, DraftImage::id, image, imageItem, DraftImage::locked, m_doc, DraftImage::name, DraftImage::opacity, DraftImage::order, DraftImage::rotation, VDomDocument::SetAttribute(), DraftImage::units, UnitsToStr(), DraftImage::visible, DraftImage::width, DraftImage::xOrigin, DraftImage::xPos, DraftImage::yOrigin, and DraftImage::yPos.
Referenced by addToFile(), and saveChanges().
setStatusMessage
void ImageTool::setStatusMessage (QString message) signal
Referenced by addImage(), MainWindow::handleImageTool(), and VPattern::parseImageElement().
Member Data Documentation
creationWasSuccessful
bool ImageTool::creationWasSuccessful =false
Definition at line 50 of file image_tool.h.
Referenced by addImage(), MainWindow::handleImageTool(), and VPattern::parseImageElement().
image
DraftImage ImageTool::image
Definition at line 52 of file image_tool.h.
Referenced by addImage(), ImageTool(), and saveOptions().
imageItem
ImageItem* ImageTool::imageItem
Definition at line 53 of file image_tool.h.
Referenced by addImage(), handleDeleteImage(), saveChanges(), and saveOptions().
m_doc
VAbstractPattern* ImageTool::m_doc private
Definition at line 65 of file image_tool.h.
Referenced by addImage(), addToFile(), handleDeleteImage(), handleImageSelected(), ImageTool(), saveChanges(), and saveOptions().
m_draftScene
VMainGraphicsScene* ImageTool::m_draftScene private
Definition at line 66 of file image_tool.h.
Referenced by addImage().
m_oldDomElement
QDomElement ImageTool::m_oldDomElement private
Definition at line 67 of file image_tool.h.
The documentation for this class was generated from the following files:
src/libs/tools/images/image_tool.h
src/libs/tools/images/image_tool.cpp