Seamly2D: XMLAttr Class Reference
XMLAttr Class Reference
#include <XMLAttr.hpp>
Public Member Functions
Constructors
XMLAttr (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttr (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, const bool specified=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
XMLAttr (const unsigned int uriId, const XMLCh *const rawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, const bool specified=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
XMLAttr (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttr (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, const bool specified=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
XMLAttr (const unsigned int uriId, const XMLCh *const rawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, const bool specified=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
XMLAttr (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttr (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, const bool specified=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
XMLAttr (const unsigned int uriId, const XMLCh *const rawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, const bool specified=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
Destructor
~XMLAttr ()
~XMLAttr ()
~XMLAttr ()
Getter methods
QName * getAttName () const
const XMLCh * getName () const
const XMLCh * getPrefix () const
const XMLCh * getQName () const
bool getSpecified () const
XMLAttDef::AttTypes getType () const
const XMLCh * getValue () const
unsigned int getURIId () const
QName * getAttName () const
const XMLCh * getName () const
const XMLCh * getPrefix () const
const XMLCh * getQName () const
bool getSpecified () const
XMLAttDef::AttTypes getType () const
const XMLCh * getValue () const
unsigned int getURIId () const
QName * getAttName () const
const XMLCh * getName () const
const XMLCh * getPrefix () const
const XMLCh * getQName () const
bool getSpecified () const
XMLAttDef::AttTypes getType () const
const XMLCh * getValue () const
unsigned int getURIId () const
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Setter methods
bool fSpecified
XMLAttDef::AttTypes fType
XMLSize_t fValueBufSz
XMLCh * fValue
QName * fAttName
MemoryManager * fMemoryManager
void set (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
void set (const unsigned int uriId, const XMLCh *const attrRawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
void setName (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix)
void setSpecified (const bool newValue)
void setType (const XMLAttDef::AttTypes newType)
void setValue (const XMLCh *const newValue)
void setURIId (const unsigned int uriId)
void set (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
void set (const unsigned int uriId, const XMLCh *const attrRawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
void setName (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix)
void setSpecified (const bool newValue)
void setType (const XMLAttDef::AttTypes newType)
void setValue (const XMLCh *const newValue)
void setURIId (const unsigned int uriId)
void set (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
void set (const unsigned int uriId, const XMLCh *const attrRawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type=XMLAttDef::CData, DatatypeValidator *datatypeValidator=0, const bool isSchema=false)
void setName (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix)
void setSpecified (const bool newValue)
void setType (const XMLAttDef::AttTypes newType)
void setValue (const XMLCh *const newValue)
void setURIId (const unsigned int uriId)
XMLAttr (const XMLAttr &)
XMLAttr & operator= (const XMLAttr &)
void cleanUp ()
XMLAttr (const XMLAttr &)
XMLAttr & operator= (const XMLAttr &)
void cleanUp ()
XMLAttr (const XMLAttr &)
XMLAttr & operator= (const XMLAttr &)
void cleanUp ()
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
This class defines the information about an attribute that will come out of the scanner during parsing. This information does not depend upon the type of validator because it is not tied to any scheme/DTD type info. Its just the raw XML 1.0 information that will be reported about an attribute in the startElement() callback method of the XMLDocumentHandler class. Hence it is not intended to be extended or derived from. Its designed to be used as is.
The 'specified' field of this class indicates whether the attribute was actually present or whether it was faulted in because it had a fixed or default value.
The code receiving this information can ask its validator for more info about the attribute, i.e. get its declaration from the DTD/Schema info.
Because of the heavy use (and reuse) of instances of this class, and the number of string members it has, this class takes pains to not reallocate string members unless it has to. It keeps up with how long each buffer is and only reallocates if the new value won't fit.
Definition at line 53 of file XMLAttr.hpp.
Constructor & Destructor Documentation
XMLAttr() [1/12]
XMLAttr::XMLAttr (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
The default constructor just setsup an empty attribute to be filled in the later. Though the initial state is a reasonable one, it is not documented because it should not be depended on.
Parameters
manager The configurable memory manager
XMLAttr() [2/12]
XMLAttr::XMLAttr (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, const bool specified = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This is the primary constructor which takes all of the information required to construct a complete attribute object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
attrValue The value string of the attribute, which should be fully normalized by XML rules!
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
specified Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
manager The configurable memory manager
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
XMLAttr() [3/12]
XMLAttr::XMLAttr (const unsigned int uriId, const XMLCh *const rawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, const bool specified = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This is the primary constructor which takes all of the information required to construct a complete attribute object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
rawName The raw name of the attribute.
attrValue The value string of the attribute, which should be fully normalized by XML rules!
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
specified Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
manager The configurable memory manager
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
~XMLAttr() [1/3]
XMLAttr::~XMLAttr () inline
Definition at line 411 of file XMLAttr.hpp.
References cleanUp().
XMLAttr() [4/12]
XMLAttr::XMLAttr (const XMLAttr &) private
XMLAttr() [5/12]
XMLAttr::XMLAttr (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
The default constructor just setsup an empty attribute to be filled in the later. Though the initial state is a reasonable one, it is not documented because it should not be depended on.
Parameters
manager The configurable memory manager
XMLAttr() [6/12]
XMLAttr::XMLAttr (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, const bool specified = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This is the primary constructor which takes all of the information required to construct a complete attribute object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
attrValue The value string of the attribute, which should be fully normalized by XML rules!
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
specified Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
manager The configurable memory manager
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
XMLAttr() [7/12]
XMLAttr::XMLAttr (const unsigned int uriId, const XMLCh *const rawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, const bool specified = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This is the primary constructor which takes all of the information required to construct a complete attribute object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
rawName The raw name of the attribute.
attrValue The value string of the attribute, which should be fully normalized by XML rules!
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
specified Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
manager The configurable memory manager
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
~XMLAttr() [2/3]
XMLAttr::~XMLAttr ()
XMLAttr() [8/12]
XMLAttr::XMLAttr (const XMLAttr &) private
XMLAttr() [9/12]
XMLAttr::XMLAttr (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
The default constructor just setsup an empty attribute to be filled in the later. Though the initial state is a reasonable one, it is not documented because it should not be depended on.
Parameters
manager The configurable memory manager
XMLAttr() [10/12]
XMLAttr::XMLAttr (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, const bool specified = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This is the primary constructor which takes all of the information required to construct a complete attribute object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
attrValue The value string of the attribute, which should be fully normalized by XML rules!
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
specified Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
manager The configurable memory manager
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
XMLAttr() [11/12]
XMLAttr::XMLAttr (const unsigned int uriId, const XMLCh *const rawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, const bool specified = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This is the primary constructor which takes all of the information required to construct a complete attribute object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
rawName The raw name of the attribute.
attrValue The value string of the attribute, which should be fully normalized by XML rules!
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
specified Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
manager The configurable memory manager
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
~XMLAttr() [3/3]
XMLAttr::~XMLAttr ()
XMLAttr() [12/12]
XMLAttr::XMLAttr (const XMLAttr &) private
Member Function Documentation
cleanUp() [1/3]
void XMLAttr::cleanUp () private
Referenced by ~XMLAttr().
cleanUp() [2/3]
void XMLAttr::cleanUp () private
cleanUp() [3/3]
void XMLAttr::cleanUp () private
getAttName() [1/3]
QName * XMLAttr::getAttName () const inline
This method returns the attribute name in a QName format.
Definition at line 420 of file XMLAttr.hpp.
References fAttName.
getAttName() [2/3]
QName* XMLAttr::getAttName () const
This method returns the attribute name in a QName format.
getAttName() [3/3]
QName* XMLAttr::getAttName () const
This method returns the attribute name in a QName format.
getName() [1/3]
const XMLCh * XMLAttr::getName () const inline
This method gets a const pointer to the name of the attribute. The form of this name is defined by the validator in use.
Definition at line 425 of file XMLAttr.hpp.
References fAttName, and QName::getLocalPart().
getName() [2/3]
const XMLCh* XMLAttr::getName () const
This method gets a const pointer to the name of the attribute. The form of this name is defined by the validator in use.
getName() [3/3]
const XMLCh* XMLAttr::getName () const
This method gets a const pointer to the name of the attribute. The form of this name is defined by the validator in use.
getPrefix() [1/3]
const XMLCh * XMLAttr::getPrefix () const inline
This method will get a const pointer to the prefix string of this attribute. Since prefixes are optional, it may be zero.
Definition at line 430 of file XMLAttr.hpp.
References fAttName, and QName::getPrefix().
getPrefix() [2/3]
const XMLCh* XMLAttr::getPrefix () const
This method will get a const pointer to the prefix string of this attribute. Since prefixes are optional, it may be zero.
getPrefix() [3/3]
const XMLCh* XMLAttr::getPrefix () const
This method will get a const pointer to the prefix string of this attribute. Since prefixes are optional, it may be zero.
getQName() [1/3]
const XMLCh* XMLAttr::getQName () const
This method will get the QName of this attribute, which will be the prefix if any, then a colon, then the base name. If there was no prefix, its the same as the getName() method.
getQName() [2/3]
const XMLCh* XMLAttr::getQName () const
This method will get the QName of this attribute, which will be the prefix if any, then a colon, then the base name. If there was no prefix, its the same as the getName() method.
getQName() [3/3]
const XMLCh* XMLAttr::getQName () const
This method will get the QName of this attribute, which will be the prefix if any, then a colon, then the base name. If there was no prefix, its the same as the getName() method.
getSpecified() [1/3]
bool XMLAttr::getSpecified () const inline
This method will get the specified flag, which indicates whether the attribute was explicitly specified or just faulted in.
Definition at line 435 of file XMLAttr.hpp.
References fSpecified.
getSpecified() [2/3]
bool XMLAttr::getSpecified () const
This method will get the specified flag, which indicates whether the attribute was explicitly specified or just faulted in.
getSpecified() [3/3]
bool XMLAttr::getSpecified () const
This method will get the specified flag, which indicates whether the attribute was explicitly specified or just faulted in.
getType() [1/3]
XMLAttDef::AttTypes XMLAttr::getType () const inline
This method will get the type of the attribute. The available types are defined by the XML specification.
Definition at line 440 of file XMLAttr.hpp.
References fType.
getType() [2/3]
XMLAttDef::AttTypes XMLAttr::getType () const
This method will get the type of the attribute. The available types are defined by the XML specification.
getType() [3/3]
XMLAttDef::AttTypes XMLAttr::getType () const
This method will get the type of the attribute. The available types are defined by the XML specification.
getURIId() [1/3]
unsigned int XMLAttr::getURIId () const inline
This method will get the id of the URI that this attribute's prefix mapped to. If namespaces are not on, then its value is meaningless.
Definition at line 450 of file XMLAttr.hpp.
References fAttName, and QName::getURI().
getURIId() [2/3]
unsigned int XMLAttr::getURIId () const
This method will get the id of the URI that this attribute's prefix mapped to. If namespaces are not on, then its value is meaningless.
getURIId() [3/3]
unsigned int XMLAttr::getURIId () const
This method will get the id of the URI that this attribute's prefix mapped to. If namespaces are not on, then its value is meaningless.
getValue() [1/3]
const XMLCh * XMLAttr::getValue () const inline
This method will get the value of the attribute. The value can be be an empty string, but never null if the object is correctly set up.
Definition at line 445 of file XMLAttr.hpp.
References fValue.
getValue() [2/3]
const XMLCh* XMLAttr::getValue () const
This method will get the value of the attribute. The value can be be an empty string, but never null if the object is correctly set up.
getValue() [3/3]
const XMLCh* XMLAttr::getValue () const
This method will get the value of the attribute. The value can be be an empty string, but never null if the object is correctly set up.
operator=() [1/3]
XMLAttr& XMLAttr::operator= (const XMLAttr &) private
operator=() [2/3]
XMLAttr& XMLAttr::operator= (const XMLAttr &) private
operator=() [3/3]
XMLAttr& XMLAttr::operator= (const XMLAttr &) private
set() [1/6]
void XMLAttr::set (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false) inline
This method is called to set up a default constructed object after the fact, or to reuse a previously used object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
attrValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
Definition at line 458 of file XMLAttr.hpp.
References fAttName, fType, QName::setName(), and setValue().
set() [2/6]
void XMLAttr::set (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This method is called to set up a default constructed object after the fact, or to reuse a previously used object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
attrValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
set() [3/6]
void XMLAttr::set (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This method is called to set up a default constructed object after the fact, or to reuse a previously used object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
attrValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
set() [4/6]
void XMLAttr::set (const unsigned int uriId, const XMLCh *const attrRawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false) inline
This method is called to set up a default constructed object after the fact, or to reuse a previously used object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrRawName The raw name of the attribute.
attrValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
Definition at line 474 of file XMLAttr.hpp.
References fAttName, fType, QName::setName(), and setValue().
set() [5/6]
void XMLAttr::set (const unsigned int uriId, const XMLCh *const attrRawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This method is called to set up a default constructed object after the fact, or to reuse a previously used object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrRawName The raw name of the attribute.
attrValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
set() [6/6]
void XMLAttr::set (const unsigned int uriId, const XMLCh *const attrRawName, const XMLCh *const attrValue, const XMLAttDef::AttTypes type = XMLAttDef::CData, DatatypeValidator * datatypeValidator = 0, const bool isSchema = false)
This method is called to set up a default constructed object after the fact, or to reuse a previously used object.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrRawName The raw name of the attribute.
attrValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
type The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
datatypeValidator type used to validate the attribute, if it was validated by an XML Schema
isSchema true if and only if this attribute was validated by an XML Schema
setName() [1/3]
void XMLAttr::setName (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix)
This method will update just the name related fields of the attribute object. The other fields are left as is.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
setName() [2/3]
void XMLAttr::setName (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix)
This method will update just the name related fields of the attribute object. The other fields are left as is.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
setName() [3/3]
void XMLAttr::setName (const unsigned int uriId, const XMLCh *const attrName, const XMLCh *const attrPrefix)
This method will update just the name related fields of the attribute object. The other fields are left as is.
Parameters
uriId The id into the validator's URI pool of the URI that the prefix mapped to. Only used if namespaces are enabled/supported.
attrName The base name of the attribute, i.e. the part after any prefix.
attrPrefix The prefix, if any, of this attribute's name. If this is empty, then uriID is meaningless as well.
setSpecified() [1/3]
void XMLAttr::setSpecified (const bool newValue) inline
This method will update the specified state of the object.
Parameters
newValue Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
Definition at line 494 of file XMLAttr.hpp.
References fSpecified.
setSpecified() [2/3]
void XMLAttr::setSpecified (const bool newValue)
This method will update the specified state of the object.
Parameters
newValue Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
setSpecified() [3/3]
void XMLAttr::setSpecified (const bool newValue)
This method will update the specified state of the object.
Parameters
newValue Indicates whether the attribute was explicitly specified or not. If not, then it was faulted in from a FIXED or DEFAULT value.
setType() [1/3]
void XMLAttr::setType (const XMLAttDef::AttTypes newType) inline
This method will update the attribute type of the object.
Parameters
newType The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
Definition at line 489 of file XMLAttr.hpp.
References fType.
setType() [2/3]
void XMLAttr::setType (const XMLAttDef::AttTypes newType)
This method will update the attribute type of the object.
Parameters
newType The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
setType() [3/3]
void XMLAttr::setType (const XMLAttDef::AttTypes newType)
This method will update the attribute type of the object.
Parameters
newType The type of the attribute. This will indicate the type of normalization done and constrains the value content. Make sure that the value set meets the constraints!
setURIId() [1/3]
void XMLAttr::setURIId (const unsigned int uriId)
This method will set the URI id field of this attribute. This is generally only ever called internally by the parser itself during the parsing process.
Parameters
uriId The uriId of the attribute.
setURIId() [2/3]
void XMLAttr::setURIId (const unsigned int uriId)
This method will set the URI id field of this attribute. This is generally only ever called internally by the parser itself during the parsing process.
Parameters
uriId The uriId of the attribute.
setURIId() [3/3]
void XMLAttr::setURIId (const unsigned int uriId)
This method will set the URI id field of this attribute. This is generally only ever called internally by the parser itself during the parsing process.
Parameters
uriId The uriId of the attribute.
setValue() [1/3]
void XMLAttr::setValue (const XMLCh *const newValue)
This method will update the value field of the attribute.
Parameters
newValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
Referenced by set().
setValue() [2/3]
void XMLAttr::setValue (const XMLCh *const newValue)
This method will update the value field of the attribute.
Parameters
newValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
setValue() [3/3]
void XMLAttr::setValue (const XMLCh *const newValue)
This method will update the value field of the attribute.
Parameters
newValue The value string of the attribute, which should be fully normalized by XML rules according to the attribute type.
Member Data Documentation
fAttName
QName * XMLAttr::fAttName private
Definition at line 404 of file XMLAttr.hpp.
Referenced by getAttName(), getName(), getPrefix(), getURIId(), and set().
fMemoryManager
MemoryManager * XMLAttr::fMemoryManager private
Definition at line 405 of file XMLAttr.hpp.
fSpecified
bool XMLAttr::fSpecified private
Definition at line 400 of file XMLAttr.hpp.
Referenced by getSpecified(), and setSpecified().
fType
XMLAttDef::AttTypes XMLAttr::fType private
Definition at line 401 of file XMLAttr.hpp.
Referenced by getType(), set(), and setType().
fValue
XMLCh * XMLAttr::fValue private
Definition at line 403 of file XMLAttr.hpp.
Referenced by getValue().
fValueBufSz
XMLSize_t XMLAttr::fValueBufSz private
Definition at line 402 of file XMLAttr.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/XMLAttr.hpp