Seamly2D: src/libs/vmisc/def.cpp File Reference
def.cpp File Reference
#include "def.h"
#include <QApplication>
#include <QChar>
#include <QColor>
#include <QComboBox>
#include <QCursor>
#include <QDir>
#include <QDirIterator>
#include <QFileInfo>
#include <QGuiApplication>
#include <QImage>
#include <QLatin1Char>
#include <QList>
#include <QMap>
#include <QMessageLogger>
#include <QObject>
#include <QPixmap>
#include <QPrinterInfo>
#include <QProcess>
#include <QRgb>
#include <QStaticStringData>
#include <QStringData>
#include <QStringDataPtr>
#include <QtDebug>
#include <QPixmapCache>
#include <QGraphicsItem>
#include <QDesktopServices>
#include <QUrl>
#include "vabstractapplication.h"
Functions
void SetItemOverrideCursor (QGraphicsItem *item, const QString &pixmapPath, int hotX, int hotY)
double ToPixel (double val, const Unit &unit)
double FromPixel (double pix, const Unit &unit)
qreal UnitConvertor (qreal value, const Unit &from, const Unit &to)
QMarginsF UnitConvertor (const QMarginsF &margins, const Unit &from, const Unit &to)
UnitConvertor Converts the values of the given margin from given unit to the new unit. returns a new instand of QMarginsF.
QStringList SupportedLocales ()
QString strippedName (const QString &fullFileName)
strippedName the function call around curFile to exclude the path to the file.
QString makeHeaderName (const QString &name)
makeHeaderName make a 1 char tablewidgetitem header name based on a translated string.
QString RelativeMPath (const QString &patternPath, const QString &absoluteMPath)
QString AbsoluteMPath (const QString &patternPath, const QString &relativeMPath)
QSharedPointer< QPrinter > PreparePrinter (const QPrinterInfo &info, QPrinter::PrinterMode mode)
QMarginsF GetMinPrinterFields (const QSharedPointer< QPrinter > &printer)
QMarginsF GetPrinterFields (const QSharedPointer< QPrinter > &printer)
QPixmap darkenPixmap (const QPixmap &pixmap)
void ShowInGraphicalShell (const QString &filePath)
bool IsOptionSet (int argc, char *argv[], const char *option)
void InitHighDpiScaling (int argc, char *argv[])
QString notchTypeToString (NotchType type)
NotchType stringToNotchType (const QString &value)
QString notchSubTypeToString (NotchSubType type)
NotchSubType stringToNotchSubType (const QString &value)
Unit StrToUnits (const QString &unit)
QString UnitsToStr (const Unit &unit, const bool translate)
UnitsToStr translate unit to string.
void InitLanguages (QComboBox *combobox)
Variables
const QString degTorad_F = QStringLiteral("degTorad")
const QString radTodeg_F = QStringLiteral("radTodeg")
const QString sin_F = QStringLiteral("sin")
const QString cos_F = QStringLiteral("cos")
const QString tan_F = QStringLiteral("tan")
const QString asin_F = QStringLiteral("asin")
const QString acos_F = QStringLiteral("acos")
const QString atan_F = QStringLiteral("atan")
const QString sinh_F = QStringLiteral("sinh")
const QString cosh_F = QStringLiteral("cosh")
const QString tanh_F = QStringLiteral("tanh")
const QString asinh_F = QStringLiteral("asinh")
const QString acosh_F = QStringLiteral("acosh")
const QString atanh_F = QStringLiteral("atanh")
const QString sinD_F = QStringLiteral("sinD")
const QString cosD_F = QStringLiteral("cosD")
const QString tanD_F = QStringLiteral("tanD")
const QString asinD_F = QStringLiteral("asinD")
const QString acosD_F = QStringLiteral("acosD")
const QString atanD_F = QStringLiteral("atanD")
const QString log2_F = QStringLiteral("log2")
const QString log10_F = QStringLiteral("log10")
const QString log_F = QStringLiteral("log")
const QString ln_F = QStringLiteral("ln")
const QString exp_F = QStringLiteral("exp")
const QString sqrt_F = QStringLiteral("sqrt")
const QString sign_F = QStringLiteral("sign")
const QString rint_F = QStringLiteral("rint")
const QString abs_F = QStringLiteral("abs")
const QString min_F = QStringLiteral("min")
const QString max_F = QStringLiteral("max")
const QString sum_F = QStringLiteral("sum")
const QString avg_F = QStringLiteral("avg")
const QString fmod_F = QStringLiteral("fmod")
const QStringList builInFunctions
const QString cm_Oprt = QStringLiteral("cm")
const QString mm_Oprt = QStringLiteral("mm")
const QString in_Oprt = QStringLiteral("in")
const QStringList builInPostfixOperators
const QString pl_size = QStringLiteral("size")
const QString pl_height = QStringLiteral("height")
const QString pl_date = QStringLiteral("date")
const QString pl_time = QStringLiteral("time")
const QString pl_patternName = QStringLiteral("patternName")
const QString pl_patternNumber = QStringLiteral("patternNumber")
const QString pl_author = QStringLiteral("author")
const QString pl_customer = QStringLiteral("customer")
const QString pl_pExt = QStringLiteral("pExt")
const QString pl_pFileName = QStringLiteral("pFileName")
const QString pl_mFileName = QStringLiteral("mFileName")
const QString pl_mExt = QStringLiteral("mExt")
const QString pl_pLetter = QStringLiteral("pLetter")
const QString pl_pAnnotation = QStringLiteral("pAnnotation")
const QString pl_pOrientation = QStringLiteral("pOrientation")
const QString pl_pRotation = QStringLiteral("pRotation")
const QString pl_pTilt = QStringLiteral("pTilt")
const QString pl_pFoldPosition = QStringLiteral("pFoldPosition")
const QString pl_pName = QStringLiteral("pName")
const QString pl_pQuantity = QStringLiteral("pQuantity")
const QString pl_mFabric = QStringLiteral("mFabric")
const QString pl_mLining = QStringLiteral("mLining")
const QString pl_mInterfacing = QStringLiteral("mInterfacing")
const QString pl_mInterlining = QStringLiteral("mInterlining")
const QString pl_wCut = QStringLiteral("wCut")
const QString pl_wOnFold = QStringLiteral("wOnFold")
const QStringList labelTemplatePlaceholders
const QString cursorArrowOpenHand = QStringLiteral("://cursor/cursor-arrow-openhand.png")
const QString cursorArrowCloseHand = QStringLiteral("://cursor/cursor-arrow-closehand.png")
const QString degreeSymbol = QStringLiteral("°")
const QString trueStr = QStringLiteral("true")
const QString falseStr = QStringLiteral("false")
const QString unitMM = QStringLiteral("mm")
const QString unitCM = QStringLiteral("cm")
const QString unitINCH = QStringLiteral("inch")
const QString unitPX = QStringLiteral("px")
const qreal PrintDPI = 96.0
const QString LONG_OPTION_NO_HDPI_SCALING = QStringLiteral("no-scaling")
const QString strSlit = QStringLiteral("slit")
const QString strTNotch = QStringLiteral("tNotch")
const QString strUNotch = QStringLiteral("uNotch")
const QString strVInternal = QStringLiteral("vInternal")
const QString strVExternal = QStringLiteral("vExternal")
const QString strCastle = QStringLiteral("castle")
const QString strDiamond = QStringLiteral("diamond")
const QString strStraightforward = QStringLiteral("straightforward")
const QString strBisector = QStringLiteral("bisector")
const QString strIntersection = QStringLiteral("intersection")
Function Documentation
AbsoluteMPath()
QString AbsoluteMPath (const QString & patternPath, const QString & relativeMPath)
Definition at line 424 of file def.cpp.
Referenced by MainWindow::ChangedHeight(), MainWindow::ChangedSize(), MainWindow::Clear(), MainWindow::GetMeasurementFileName(), MainWindow::LoadIndividual(), MainWindow::LoadMultisize(), MainWindow::LoadPattern(), MainWindow::SavePattern(), MainWindow::ShowMeasurements(), MainWindow::SyncMeasurements(), and MainWindow::UnloadMeasurements().
darkenPixmap()
QPixmap darkenPixmap (const QPixmap & pixmap)
Definition at line 489 of file def.cpp.
Referenced by MainWindow::UpdateWindowTitle(), and TMainWindow::UpdateWindowTitle().
FromPixel()
double FromPixel (double pix, const Unit & unit)
Definition at line 250 of file def.cpp.
References Cm, Inch, Mm, PrintDPI, and Px.
Referenced by DialogLayoutSettings::ConvertLayoutSize(), DialogLayoutSettings::ConvertPaperSize(), MainWindowsNoGUI::exportPDF(), PatternPieceTool::FindGrainlineGeometry(), PatternPieceTool::FindLabelGeometry(), VAbstractApplication::fromPixel(), VPatternConverter::LabelTagToV0_4_4(), PatternPieceTool::SaveResizeGrainline(), PatternPieceTool::SaveResizePattern(), PatternPieceTool::saveResizePiece(), DialogLayoutSettings::SetPaperHeight(), DialogLayoutSettings::SetPaperWidth(), MainWindowsNoGUI::SetPrinterSettings(), VLengthLine::SetValue(), DialogLayoutSettings::SheetSize(), VArcRadius::VArcRadius(), VCurveCLength::VCurveCLength(), and VCurveLength::VCurveLength().
GetMinPrinterFields()
QMarginsF GetMinPrinterFields (const QSharedPointer< QPrinter > & printer)
Definition at line 463 of file def.cpp.
References Mm, Px, and UnitConvertor().
Referenced by DialogLayoutSettings::MinPrinterFields().
GetPrinterFields()
QMarginsF GetPrinterFields (const QSharedPointer< QPrinter > & printer)
Definition at line 477 of file def.cpp.
References Mm, Px, and UnitConvertor().
Referenced by DialogLayoutSettings::GetDefPrinterFields(), and DialogLayoutSettings::PrinterMargins().
InitHighDpiScaling()
void InitHighDpiScaling (int argc, char * argv[])
Definition at line 551 of file def.cpp.
References IsOptionSet(), and LONG_OPTION_NO_HDPI_SCALING.
Referenced by main().
InitLanguages()
void InitLanguages (QComboBox * combobox)
Definition at line 725 of file def.cpp.
References qApp, and SCASSERT.
Referenced by PreferencesConfigurationPage::PreferencesConfigurationPage(), and SeamlyMePreferencesConfigurationPage::SeamlyMePreferencesConfigurationPage().
IsOptionSet()
bool IsOptionSet (int argc, char * argv[], const char * option)
Definition at line 538 of file def.cpp.
Referenced by InitHighDpiScaling().
makeHeaderName()
QString makeHeaderName (const QString & name)
makeHeaderName make a 1 char tablewidgetitem header name based on a translated string.
Parameters
name full name of header item.
Returns
1 char name.
Definition at line 401 of file def.cpp.
Referenced by GroupsWidget::fillTable().
notchSubTypeToString()
QString notchSubTypeToString (NotchSubType type)
Definition at line 632 of file def.cpp.
References Bisector, Intersection, Straightforward, strBisector, strIntersection, and strStraightforward.
Referenced by VAbstractTool::AddSANode().
notchTypeToString()
QString notchTypeToString (NotchType type)
Definition at line 574 of file def.cpp.
References Castle, Diamond, Slit, strCastle, strDiamond, strSlit, strTNotch, strUNotch, strVExternal, strVInternal, TNotch, UNotch, VExternal, and VInternal.
Referenced by VAbstractTool::AddSANode().
PreparePrinter()
QSharedPointer<QPrinter> PreparePrinter (const QPrinterInfo & info, QPrinter::PrinterMode mode)
Definition at line 440 of file def.cpp.
References PrintDPI.
Referenced by MainWindowsNoGUI::LayoutPrint(), and MainWindowsNoGUI::PrintPreview().
RelativeMPath()
QString RelativeMPath (const QString & patternPath, const QString & absoluteMPath)
Definition at line 408 of file def.cpp.
Referenced by MainWindow::CheckPathToMeasurements(), MainWindow::LoadIndividual(), MainWindow::LoadMultisize(), MainWindow::LoadPattern(), and MainWindow::SavePattern().
SetItemOverrideCursor()
void SetItemOverrideCursor (QGraphicsItem * item, const QString & pixmapPath, int hotX, int hotY)
Definition at line 206 of file def.cpp.
References SCASSERT.
Referenced by VGrainlineItem::allUserModifications(), VTextGraphicsItem::allUserModifications(), VToolSpline::hoverEnterEvent(), VToolSplinePath::hoverEnterEvent(), VToolBasePoint::hoverEnterEvent(), PatternPieceTool::hoverEnterEvent(), VControlPointSpline::hoverEnterEvent(), VGraphicsSimpleTextItem::hoverEnterEvent(), VTextGraphicsItem::hoverMoveEvent(), VToolSpline::mousePressEvent(), VToolSplinePath::mousePressEvent(), VToolBasePoint::mousePressEvent(), PatternPieceTool::mousePressEvent(), VControlPointSpline::mousePressEvent(), VGraphicsSimpleTextItem::mousePressEvent(), VTextGraphicsItem::mousePressEvent(), VGrainlineItem::mousePressEvent(), VToolSpline::mouseReleaseEvent(), VToolSplinePath::mouseReleaseEvent(), VToolBasePoint::mouseReleaseEvent(), PatternPieceTool::mouseReleaseEvent(), VControlPointSpline::mouseReleaseEvent(), VGraphicsSimpleTextItem::mouseReleaseEvent(), VTextGraphicsItem::mouseReleaseEvent(), VGrainlineItem::mouseReleaseEvent(), VGrainlineItem::userMoveAndResize(), VTextGraphicsItem::userMoveAndResize(), VGrainlineItem::userRotateAndMove(), and VTextGraphicsItem::userRotateAndMove().
ShowInGraphicalShell()
void ShowInGraphicalShell (const QString & filePath)
Definition at line 514 of file def.cpp.
stringToNotchSubType()
NotchSubType stringToNotchSubType (const QString & value)
Definition at line 650 of file def.cpp.
References Bisector, Intersection, Straightforward, strBisector, strIntersection, and strStraightforward.
Referenced by VAbstractPattern::ParseSANode().
stringToNotchType()
NotchType stringToNotchType (const QString & value)
Definition at line 600 of file def.cpp.
References Castle, Diamond, Slit, strCastle, strDiamond, strSlit, strTNotch, strUNotch, strVExternal, strVInternal, TNotch, UNotch, VExternal, and VInternal.
Referenced by PatternPieceDialog::notchTypeChanged(), and VAbstractPattern::ParseSANode().
strippedName()
QString strippedName (const QString & fullFileName)
strippedName the function call around curFile to exclude the path to the file.
Parameters
fullFileName full path to the file.
Returns
file name.
Definition at line 391 of file def.cpp.
Referenced by MainWindow::GetMeasurementFileName(), MainWindow::UpdateRecentFileActions(), and TMainWindow::UpdateRecentFileActions().
StrToUnits()
Unit StrToUnits (const QString & unit)
Definition at line 670 of file def.cpp.
References Cm, Inch, Mm, Px, unitCM, unitINCH, unitMM, and unitPX.
Referenced by VCommonSettings::GetDefaultSeamAllowance(), PreferencesPatternPage::initDefaultSeamAllowance(), PreferencesPatternPage::initGrainlines(), PreferencesPatternPage::initializeLabelsTab(), PatternPieceDialog::initializeSeamAllowanceTab(), DialogLayoutSettings::InitLayoutUnits(), PreferencesPatternPage::initNotches(), DialogLayoutSettings::InitPaperUnits(), DialogLayoutSettings::LayoutUnit(), VDomDocument::MUnit(), DialogLayoutSettings::PaperUnit(), MApplication::ParseCommandLine(), DialogNewPattern::PatternUnit(), and VCommonSettings::SetDefaultSeamAllowance().
SupportedLocales()
QStringList SupportedLocales ()
Definition at line 361 of file def.cpp.
ToPixel()
double ToPixel (double val, const Unit & unit)
Definition at line 231 of file def.cpp.
References Cm, Inch, Mm, PrintDPI, and Px.
Referenced by VLayoutPiece::createAllowanceItem(), VPiece::createBuiltInSaNotch(), VLayoutPiece::createCutoutPathItem(), VPE::LineWeightProperty::createIcon(), VLayoutPiece::createInternalPathItem(), VLayoutPiece::createMainItem(), VPiece::createSeamAllowanceNotch(), VEllipticalArc::CutArc(), VArc::CutArc(), VAbstractCubicBezier::CutSpline(), VAbstractCubicBezierPath::CutSplinePath(), DoubleLinePointTool::DoubleLinePointTool(), MainWindowsNoGUI::exportPiecesAsFlatLayout(), VEllipticalArc::FindF2(), anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), PatternPieceTool::FindGrainlineGeometry(), anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), PatternPieceDialog::getFormulaValue(), VPiece::getNodeSAPoints(), VPieceNode::GetSAAfter(), VPieceNode::GetSABefore(), VPiece::getSeamNotchSAPoint(), DoubleLinePointTool::hoverEnterEvent(), VToolLinePoint::hoverEnterEvent(), DoubleLinePointTool::hoverLeaveEvent(), VToolLinePoint::hoverLeaveEvent(), PatternPieceTool::InitInternalPaths(), VAbstractSpline::paint(), PatternPieceTool::paint(), DoubleLinePointTool::paint(), VToolLinePoint::paint(), VToolLine::paint(), VToolInternalPath::paint(), VGrainlineItem::paint(), PatternPieceTool::PrepareLabelData(), MainWindowsNoGUI::PrintPages(), DoubleLinePointTool::RefreshGeometry(), VToolLinePoint::RefreshGeometry(), VScenePoint::refreshLeader(), VSimpleCurve::ScalePenWidth(), VPiece::SeamAllowancePoints(), Visualization::setLineWeight(), VLayoutPiece::SetPatternInfo(), VLayoutPiece::SetPieceText(), VAbstractApplication::toPixel(), PatternPieceTool::UpdateGrainline(), and VToolLinePoint::VToolLinePoint().
UnitConvertor() [1/2]
QMarginsF UnitConvertor (const QMarginsF & margins, const Unit & from, const Unit & to)
UnitConvertor Converts the values of the given margin from given unit to the new unit. returns a new instand of QMarginsF.
Parameters
margin
from
to
Returns
Definition at line 349 of file def.cpp.
References UnitConvertor().
UnitConvertor() [2/2]
qreal UnitConvertor (qreal value, const Unit & from, const Unit & to)
Definition at line 269 of file def.cpp.
References Cm, Inch, Mm, PrintDPI, and Px.
Referenced by VMeasurement::CalcValue(), AbstractTest::Comparison(), DialogLayoutSettings::ConvertLayoutSize(), DialogLayoutSettings::ConvertPaperSize(), DialogLayoutSettings::DialogAccepted(), DialogNewMeasurements::DialogNewMeasurements(), TMainWindow::EvalFormula(), VCommonSettings::GetDefaultSeamAllowance(), VSettings::GetDefLayoutWidth(), DialogLayoutSettings::GetFields(), VSettings::GetLayoutPaperHeight(), VSettings::GetLayoutPaperWidth(), DialogLayoutSettings::GetLayoutWidth(), GetMinPrinterFields(), DialogLayoutSettings::GetPaperHeight(), DialogLayoutSettings::GetPaperWidth(), GetPrinterFields(), DialogLayoutSettings::GetShift(), VAbstractLayoutDialog::getTemplateSize(), VSettings::GetTiledPDFMargins(), VSettings::getTiledPDFPaperHeight(), VSettings::getTiledPDFPaperWidth(), DialogPatternProperties::InitComboBox(), PatternPieceDialog::initializeSeamAllowanceTab(), DialogInternalPath::InitSeamAllowanceTab(), DialogLayoutSettings::LayoutToPixels(), VMeasurement::ListValue(), MainWindow::LoadMeasurements(), DialogLayoutSettings::MinimumLayoutSize(), DialogLayoutSettings::MinimumPaperSize(), DialogLayoutSettings::PageToPixels(), VMeasurements::ReadMeasurements(), DialogLayoutSettings::ReadSettings(), TMainWindow::RefreshTable(), TMainWindow::SetBaseMHeight(), TMainWindow::SetBaseMSize(), VCommonSettings::SetDefaultSeamAllowance(), DialogLayoutSettings::SetFields(), PatternPieceDialog::setGrainlineLength(), MainWindow::SetHeight(), DialogLayoutSettings::SetLayoutWidth(), DialogLayoutSettings::SetPaperHeight(), DialogLayoutSettings::SetPaperWidth(), PatternPieceDialog::setPatternLabelHeight(), PatternPieceDialog::setPatternLabelWidth(), PatternPieceDialog::setPieceLabelHeight(), PatternPieceDialog::setPieceLabelWidth(), MainWindowsNoGUI::SetPrinterSettings(), DialogLayoutSettings::SetShift(), MainWindow::SetSize(), VSettings::setTiledPDFMargins(), VSettings::setTiledPDFPaperHeight(), VSettings::setTiledPDFPaperWidth(), MainWindow::ShowMeasurements(), TMainWindow::ShowNewMData(), VMeasurements::UniqueTagAttr(), and UnitConvertor().
UnitsToStr()
QString UnitsToStr (const Unit & unit, const bool translate)
UnitsToStr translate unit to string.
This method used when need write unit in xml file and for showing unit in dialogs.
Parameters
unit curent unit
translate true if need show translated name. Default value false.
Returns
string reprezantation for unit.
Definition at line 702 of file def.cpp.
References Cm, Inch, Mm, Px, translate, unitCM, unitINCH, unitMM, and unitPX.
Referenced by DialogInternalPath::afterWidthChanged(), PatternPieceDialog::afterWidthChanged(), DialogInternalPath::beforeWidthChanged(), PatternPieceDialog::beforeWidthChanged(), TMainWindow::changeEvent(), IntersectCirclesDialog::Circle1RadiusChanged(), IntersectCirclesDialog::Circle2RadiusChanged(), IntersectCircleTangentDialog::CircleRadiusChanged(), VAbstractOperation::complexCurveToolTip(), VPattern::CreateEmptyFile(), VMeasurements::CreateEmptyIndividualFile(), VMeasurements::CreateEmptyMultisizeFile(), DialogInternalPath::defaultWidthChanged(), PatternPieceDialog::defaultWidthChanged(), DialogInternalPath::editAfterSeamAllowanceWidth(), PatternPieceDialog::editAfterSeamAllowanceWidth(), DialogInternalPath::editBeforeSeamAllowanceWidth(), PatternPieceDialog::editBeforeSeamAllowanceWidth(), DialogInternalPath::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editDefaultSeamAllowanceWidth(), DialogMove::editLengthFormula(), IntersectCirclesDialog::EvalCircle1Radius(), IntersectCirclesDialog::EvalCircle2Radius(), IntersectCircleTangentDialog::EvalCircleRadius(), DialogTool::EvalFormula(), TMainWindow::EvalFormula(), DialogSpline::EvalLength1(), DialogSplinePath::EvalLength1(), DialogSpline::EvalLength2(), DialogSplinePath::EvalLength2(), DialogArc::EvalRadius(), DialogEllipticalArc::EvalRadiuses(), DialogInternalPath::evaluateAfterWidth(), PatternPieceDialog::evaluateAfterWidth(), DialogInternalPath::evaluateBeforeWidth(), PatternPieceDialog::evaluateBeforeWidth(), DialogInternalPath::evaluateDefaultWidth(), PatternPieceDialog::evaluateDefaultWidth(), DialogMove::evaluateLength(), DialogVariables::evalVariableFormula(), DialogVariables::Fx(), TMainWindow::Fx(), IntersectCirclesDialog::FXCircle1Radius(), IntersectCirclesDialog::FXCircle2Radius(), IntersectCircleTangentDialog::FXCircleRadius(), DialogAlongLine::FXLength(), DialogArcWithLength::FXLength(), DialogBisector::FXLength(), DialogCutArc::FXLength(), DialogCutSpline::FXLength(), DialogCutSplinePath::FXLength(), DialogEndLine::FXLength(), DialogNormal::FXLength(), DialogShoulderPoint::FXLength(), DialogSpline::FXLength1(), DialogSplinePath::FXLength1(), DialogSpline::FXLength2(), DialogSplinePath::FXLength2(), DialogArc::FXRadius(), DialogArcWithLength::FXRadius(), DialogPointOfContact::FXRadius(), DialogEllipticalArc::FXRadius1(), DialogEllipticalArc::FXRadius2(), VToolPointOfContact::getArcRadius(), IntersectCircleTangentTool::GetCircleRadius(), IntersectCirclesTool::GetFirstCircleRadius(), VToolCut::GetFormula(), VToolMove::GetFormulaLength(), VToolArcWithLength::GetFormulaLength(), VToolLinePoint::GetFormulaLength(), VToolArc::GetFormulaRadius(), VToolArcWithLength::GetFormulaRadius(), VToolEllipticalArc::GetFormulaRadius1(), VToolEllipticalArc::GetFormulaRadius2(), IntersectCirclesTool::GetSecondCircleRadius(), TMainWindow::InitComboBoxUnits(), PreferencesPatternPage::initDefaultSeamAllowance(), PreferencesPatternPage::initGrainlines(), PreferencesPatternPage::initializeLabelsTab(), DialogLayoutSettings::InitLayoutUnits(), PreferencesPatternPage::initNotches(), DialogLayoutSettings::InitPaperUnits(), DialogNewPattern::InitUnits(), TMainWindow::InitWindow(), DialogArcWithLength::Length(), DialogSpline::Length1Changed(), DialogSpline::Length2Changed(), DialogArcWithLength::LengthChanged(), VToolMove::makeToolTip(), VAbstractSpline::makeToolTip(), VToolArc::makeToolTip(), VToolArcWithLength::makeToolTip(), VToolEllipticalArc::makeToolTip(), VToolCutArc::makeToolTip(), VToolCutSpline::makeToolTip(), VToolCutSplinePath::makeToolTip(), DoubleLinePointTool::makeToolTip(), VToolAlongLine::makeToolTip(), VToolHeight::makeToolTip(), VToolLineIntersectAxis::makeToolTip(), VToolLinePoint::makeToolTip(), VToolShoulderPoint::makeToolTip(), VToolLineIntersect::makeToolTip(), VToolPointOfContact::makeToolTip(), VToolLine::makeToolTip(), MouseCoordinates::MouseCoordinates(), TMainWindow::printPages(), DialogArcWithLength::Radius(), DialogEllipticalArc::Radius1Changed(), DialogEllipticalArc::Radius2Changed(), DialogArc::RadiusChanged(), DialogArcWithLength::RadiusChanged(), VisToolMove::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), DialogVariables::saveCustomVariableFormula(), TMainWindow::SaveMValue(), ShowInfoDialog::ShowInfoDialog(), MainWindow::ShowMeasurements(), TMainWindow::ShowNewMData(), VToolOptionsPropertyBrowser::showOptionsToolSpline(), DialogVariables::showUnits(), TMainWindow::ShowUnits(), VDomDocument::UnitsHelpString(), PatternPieceDialog::updateGrainlineValues(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), PatternPieceDialog::updatePatternLabelValues(), PatternPieceDialog::updatePieceLabelValues(), and EditFormulaDialog::valueChanged().
Variable Documentation
abs_F
const QString abs_F = QStringLiteral("abs")
Definition at line 113 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
acos_F
const QString acos_F = QStringLiteral("acos")
Definition at line 91 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
acosD_F
const QString acosD_F = QStringLiteral("acosD")
Definition at line 103 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
acosh_F
const QString acosh_F = QStringLiteral("acosh")
Definition at line 97 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
asin_F
const QString asin_F = QStringLiteral("asin")
Definition at line 90 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
asinD_F
const QString asinD_F = QStringLiteral("asinD")
Definition at line 102 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
asinh_F
const QString asinh_F = QStringLiteral("asinh")
Definition at line 96 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
atan_F
const QString atan_F = QStringLiteral("atan")
Definition at line 92 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
atanD_F
const QString atanD_F = QStringLiteral("atanD")
Definition at line 104 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
atanh_F
const QString atanh_F = QStringLiteral("atanh")
Definition at line 98 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
avg_F
const QString avg_F = QStringLiteral("avg")
Definition at line 117 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
builInFunctions
const QStringList builInFunctions
Initial value:
= QStringList() << degTorad_F << radTodeg_F
                                                  << sin_F  << cos_F   << tan_F  << asin_F  << acos_F  << atan_F
                                                  << sinh_F << cosh_F  << tanh_F << asinh_F << acosh_F << atanh_F
                                                  << sinD_F  << cosD_F   << tanD_F  << asinD_F  << acosD_F  << atanD_F
                                                  << log2_F << log10_F << log_F  << ln_F    << exp_F   << sqrt_F
                                                  << sign_F << rint_F  << abs_F  << min_F   << max_F   << sum_F
                                                  << avg_F << fmod_F
Definition at line 120 of file def.cpp.
Referenced by VContainer::AllUniqueNames(), Calculator::EvalFormula(), Calculator::InitVariables(), VAbstractPattern::IsFunction(), and VContainer::IsUnique().
builInPostfixOperators
const QStringList builInPostfixOperators
Initial value:
= QStringList() << cm_Oprt
                                                         << mm_Oprt
                                                         << in_Oprt
Definition at line 133 of file def.cpp.
Referenced by VAbstractPattern::IsPostfixOperator().
cm_Oprt
const QString cm_Oprt = QStringLiteral("cm")
Definition at line 129 of file def.cpp.
Referenced by VTranslateVars::InitPostfixOperators().
cos_F
const QString cos_F = QStringLiteral("cos")
Definition at line 88 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
cosD_F
const QString cosD_F = QStringLiteral("cosD")
Definition at line 100 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
cosh_F
const QString cosh_F = QStringLiteral("cosh")
Definition at line 94 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
cursorArrowCloseHand
const QString cursorArrowCloseHand = QStringLiteral("://cursor/cursor-arrow-closehand.png")
Definition at line 192 of file def.cpp.
Referenced by VGrainlineItem::allUserModifications(), VTextGraphicsItem::allUserModifications(), VToolSpline::mousePressEvent(), VToolSplinePath::mousePressEvent(), VToolBasePoint::mousePressEvent(), PatternPieceTool::mousePressEvent(), VControlPointSpline::mousePressEvent(), VGraphicsSimpleTextItem::mousePressEvent(), VTextGraphicsItem::mousePressEvent(), VGrainlineItem::mousePressEvent(), VGrainlineItem::userMoveAndResize(), VTextGraphicsItem::userMoveAndResize(), VGrainlineItem::userRotateAndMove(), and VTextGraphicsItem::userRotateAndMove().
cursorArrowOpenHand
const QString cursorArrowOpenHand = QStringLiteral("://cursor/cursor-arrow-openhand.png")
Definition at line 191 of file def.cpp.
Referenced by VToolSpline::hoverEnterEvent(), VToolSplinePath::hoverEnterEvent(), VToolBasePoint::hoverEnterEvent(), PatternPieceTool::hoverEnterEvent(), VControlPointSpline::hoverEnterEvent(), VGraphicsSimpleTextItem::hoverEnterEvent(), VTextGraphicsItem::hoverMoveEvent(), VToolSpline::mouseReleaseEvent(), VToolSplinePath::mouseReleaseEvent(), VToolBasePoint::mouseReleaseEvent(), PatternPieceTool::mouseReleaseEvent(), VControlPointSpline::mouseReleaseEvent(), VGraphicsSimpleTextItem::mouseReleaseEvent(), VTextGraphicsItem::mouseReleaseEvent(), and VGrainlineItem::mouseReleaseEvent().
degreeSymbol
const QString degreeSymbol = QStringLiteral("°")
Definition at line 196 of file def.cpp.
Referenced by DialogSpline::Angle1Changed(), DialogSpline::Angle2Changed(), DialogMove::angleChanged(), DialogRotation::angleChanged(), DialogCurveIntersectAxis::AngleTextChanged(), DialogEndLine::AngleTextChanged(), DialogLineIntersectAxis::AngleTextChanged(), DialogMove::editAngleFormula(), DialogRotation::editAngleFormula(), DialogMove::editRotationFormula(), DialogCurveIntersectAxis::EvalAngle(), DialogEndLine::EvalAngle(), DialogLineIntersectAxis::EvalAngle(), DialogSpline::EvalAngle1(), DialogSplinePath::EvalAngle1(), DialogSpline::EvalAngle2(), DialogSplinePath::EvalAngle2(), DialogEllipticalArc::EvalAngles(), DialogArc::EvalF(), DialogArcWithLength::EvalF(), DialogMove::evaluateAngle(), DialogRotation::evaluateAngle(), DialogMove::evaluateRotation(), DialogArc::F1Changed(), DialogArcWithLength::F1Changed(), DialogEllipticalArc::F1Changed(), DialogArc::F2Changed(), DialogEllipticalArc::F2Changed(), DialogCurveIntersectAxis::FXAngle(), DialogEndLine::FXAngle(), DialogLineIntersectAxis::FXAngle(), DialogSpline::FXAngle1(), DialogSplinePath::FXAngle1(), DialogSpline::FXAngle2(), DialogSplinePath::FXAngle2(), DialogArc::FXF1(), DialogArcWithLength::FXF1(), DialogEllipticalArc::FXF1(), DialogArc::FXF2(), DialogEllipticalArc::FXF2(), DialogEllipticalArc::FXRotationAngle(), VToolMove::GetFormulaAngle(), VToolRotation::GetFormulaAngle(), VToolCurveIntersectAxis::GetFormulaAngle(), VToolEndLine::GetFormulaAngle(), VToolLineIntersectAxis::GetFormulaAngle(), VToolArc::GetFormulaF1(), VToolArcWithLength::GetFormulaF1(), VToolEllipticalArc::GetFormulaF1(), VToolArc::GetFormulaF2(), VToolEllipticalArc::GetFormulaF2(), VToolMove::getFormulaRotation(), VToolEllipticalArc::GetFormulaRotationAngle(), DialogMove::lengthChanged(), DialogEllipticalArc::RotationAngleChanged(), DialogMove::rotationChanged(), VToolOptionsPropertyBrowser::showOptionsToolSpline(), DialogVariables::showUnits(), PatternPieceDialog::updateGrainlineValues(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), PatternPieceDialog::updatePatternLabelValues(), PatternPieceDialog::updatePieceLabelValues(), and EditFormulaDialog::valueChanged().
degTorad_F
const QString degTorad_F = QStringLiteral("degTorad")
Definition at line 85 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
exp_F
const QString exp_F = QStringLiteral("exp")
Definition at line 109 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
falseStr
const QString falseStr = QStringLiteral("false")
Definition at line 198 of file def.cpp.
Referenced by VPattern::getActivePatternPieces(), VDomDocument::GetLabelTemplate(), VPattern::IsDefCustom(), VPattern::IsReadOnly(), VMeasurements::IsReadOnly(), VPatternConverter::IsReadOnly(), VVITConverter::IsReadOnly(), VVSTConverter::IsReadOnly(), VPattern::ParsePathElement(), VAbstractPattern::ParsePieceCSARecords(), VPattern::ParsePieceDataTag(), VPattern::parsePieceElement(), VPattern::ParsePieceGrainline(), VAbstractPattern::ParseSANode(), VDomDocument::SetAttribute(), VDomDocument::SetParametrUsage(), and VMeasurements::SetReadOnly().
fmod_F
const QString fmod_F = QStringLiteral("fmod")
Definition at line 118 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
in_Oprt
const QString in_Oprt = QStringLiteral("in")
Definition at line 131 of file def.cpp.
Referenced by VTranslateVars::InitPostfixOperators().
labelTemplatePlaceholders
const QStringList labelTemplatePlaceholders
Initial value:
= QStringList() << pl_size
                                                            << pl_height
                                                            << pl_date
                                                            << pl_time
                                                            << pl_patternName
                                                            << pl_patternNumber
                                                            << pl_author
                                                            << pl_customer
                                                            << pl_pExt
                                                            << pl_pFileName
                                                            << pl_mFileName
                                                            << pl_mExt
                                                            << pl_pLetter
                                                            << pl_pAnnotation
                                                            << pl_pOrientation
                                                            << pl_pRotation
                                                            << pl_pTilt
                                                            << pl_pFoldPosition
                                                            << pl_pName
                                                            << pl_pQuantity
                                                            << pl_mFabric
                                                            << pl_mLining
                                                            << pl_mInterfacing
                                                            << pl_mInterlining
                                                            << pl_wCut
                                                            << pl_wOnFold
Definition at line 164 of file def.cpp.
ln_F
const QString ln_F = QStringLiteral("ln")
Definition at line 108 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
log10_F
const QString log10_F = QStringLiteral("log10")
Definition at line 106 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
log2_F
const QString log2_F = QStringLiteral("log2")
Definition at line 105 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
log_F
const QString log_F = QStringLiteral("log")
Definition at line 107 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
LONG_OPTION_NO_HDPI_SCALING
const QString LONG_OPTION_NO_HDPI_SCALING = QStringLiteral("no-scaling")
Definition at line 535 of file def.cpp.
Referenced by AllKeys(), InitHighDpiScaling(), VCommandLine::InitOptions(), VCommandLine::IsNoScalingEnabled(), MainWindow::LoadPattern(), MApplication::ParseCommandLine(), and MainWindow::ShowMeasurements().
max_F
const QString max_F = QStringLiteral("max")
Definition at line 115 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
min_F
const QString min_F = QStringLiteral("min")
Definition at line 114 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
mm_Oprt
const QString mm_Oprt = QStringLiteral("mm")
Definition at line 130 of file def.cpp.
Referenced by VTranslateVars::InitPostfixOperators().
pl_author
const QString pl_author = QStringLiteral("author")
Definition at line 143 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_customer
const QString pl_customer = QStringLiteral("customer")
Definition at line 144 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_date
const QString pl_date = QStringLiteral("date")
Definition at line 139 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_height
const QString pl_height = QStringLiteral("height")
Definition at line 138 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_mExt
const QString pl_mExt = QStringLiteral("mExt")
Definition at line 148 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_mFabric
const QString pl_mFabric = QStringLiteral("mFabric")
Definition at line 157 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_mFileName
const QString pl_mFileName = QStringLiteral("mFileName")
Definition at line 147 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_mInterfacing
const QString pl_mInterfacing = QStringLiteral("mInterfacing")
Definition at line 159 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_mInterlining
const QString pl_mInterlining = QStringLiteral("mInterlining")
Definition at line 160 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_mLining
const QString pl_mLining = QStringLiteral("mLining")
Definition at line 158 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_pAnnotation
const QString pl_pAnnotation = QStringLiteral("pAnnotation")
Definition at line 150 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
pl_patternName
const QString pl_patternName = QStringLiteral("patternName")
Definition at line 141 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_patternNumber
const QString pl_patternNumber = QStringLiteral("patternNumber")
Definition at line 142 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_pExt
const QString pl_pExt = QStringLiteral("pExt")
Definition at line 145 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_pFileName
const QString pl_pFileName = QStringLiteral("pFileName")
Definition at line 146 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_pFoldPosition
const QString pl_pFoldPosition = QStringLiteral("pFoldPosition")
Definition at line 154 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
pl_pLetter
const QString pl_pLetter = QStringLiteral("pLetter")
Definition at line 149 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
pl_pName
const QString pl_pName = QStringLiteral("pName")
Definition at line 155 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
pl_pOrientation
const QString pl_pOrientation = QStringLiteral("pOrientation")
Definition at line 151 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
pl_pQuantity
const QString pl_pQuantity = QStringLiteral("pQuantity")
Definition at line 156 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
pl_pRotation
const QString pl_pRotation = QStringLiteral("pRotation")
Definition at line 152 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
pl_pTilt
const QString pl_pTilt = QStringLiteral("pTilt")
Definition at line 153 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
pl_size
const QString pl_size = QStringLiteral("size")
Definition at line 137 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_time
const QString pl_time = QStringLiteral("time")
Definition at line 140 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_wCut
const QString pl_wCut = QStringLiteral("wCut")
Definition at line 161 of file def.cpp.
Referenced by VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), and anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders().
pl_wOnFold
const QString pl_wOnFold = QStringLiteral("wOnFold")
Definition at line 162 of file def.cpp.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), VTranslateVars::InitPlaceholder(), EditLabelTemplateDialog::InitPlaceholders(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), and EditLabelTemplateDialog::SetPiece().
PrintDPI
const qreal PrintDPI = 96.0
Definition at line 228 of file def.cpp.
Referenced by MainWindowsNoGUI::AAMADxfFile(), AbstractTest::Comparison(), MainWindowsNoGUI::exportPDF(), MainWindowsNoGUI::exportSVG(), MainWindowsNoGUI::FlatDxfFile(), FromPixel(), VAbstractLayoutDialog::initTemplates(), MainWindowsNoGUI::LayoutPrint(), MainWindowsNoGUI::ObjFile(), MainWindowsNoGUI::PdfTiledFile(), PreparePrinter(), TMainWindow::printPages(), MainWindowsNoGUI::PrintPreview(), ToPixel(), VPoster::ToPixel(), and UnitConvertor().
radTodeg_F
const QString radTodeg_F = QStringLiteral("radTodeg")
Definition at line 86 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
rint_F
const QString rint_F = QStringLiteral("rint")
Definition at line 112 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
sign_F
const QString sign_F = QStringLiteral("sign")
Definition at line 111 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
sin_F
const QString sin_F = QStringLiteral("sin")
Definition at line 87 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
sinD_F
const QString sinD_F = QStringLiteral("sinD")
Definition at line 99 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
sinh_F
const QString sinh_F = QStringLiteral("sinh")
Definition at line 93 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
sqrt_F
const QString sqrt_F = QStringLiteral("sqrt")
Definition at line 110 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
strBisector
const QString strBisector = QStringLiteral("bisector")
Definition at line 628 of file def.cpp.
Referenced by notchSubTypeToString(), and stringToNotchSubType().
strCastle
const QString strCastle = QStringLiteral("castle")
Definition at line 570 of file def.cpp.
Referenced by notchTypeToString(), and stringToNotchType().
strDiamond
const QString strDiamond = QStringLiteral("diamond")
Definition at line 571 of file def.cpp.
Referenced by notchTypeToString(), and stringToNotchType().
strIntersection
const QString strIntersection = QStringLiteral("intersection")
Definition at line 629 of file def.cpp.
Referenced by notchSubTypeToString(), and stringToNotchSubType().
strSlit
const QString strSlit = QStringLiteral("slit")
Definition at line 565 of file def.cpp.
Referenced by notchTypeToString(), VAbstractPattern::ParseSANode(), and stringToNotchType().
strStraightforward
const QString strStraightforward = QStringLiteral("straightforward")
Definition at line 627 of file def.cpp.
Referenced by notchSubTypeToString(), VAbstractPattern::ParseSANode(), and stringToNotchSubType().
strTNotch
const QString strTNotch = QStringLiteral("tNotch")
Definition at line 566 of file def.cpp.
Referenced by notchTypeToString(), and stringToNotchType().
strUNotch
const QString strUNotch = QStringLiteral("uNotch")
Definition at line 567 of file def.cpp.
Referenced by notchTypeToString(), and stringToNotchType().
strVExternal
const QString strVExternal = QStringLiteral("vExternal")
Definition at line 569 of file def.cpp.
Referenced by notchTypeToString(), and stringToNotchType().
strVInternal
const QString strVInternal = QStringLiteral("vInternal")
Definition at line 568 of file def.cpp.
Referenced by notchTypeToString(), and stringToNotchType().
sum_F
const QString sum_F = QStringLiteral("sum")
Definition at line 116 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
tan_F
const QString tan_F = QStringLiteral("tan")
Definition at line 89 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
tanD_F
const QString tanD_F = QStringLiteral("tanD")
Definition at line 101 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
tanh_F
const QString tanh_F = QStringLiteral("tanh")
Definition at line 95 of file def.cpp.
Referenced by VTranslateVars::InitFunctions().
trueStr
const QString trueStr = QStringLiteral("true")
Definition at line 197 of file def.cpp.
Referenced by VAbstractPattern::addGroupItems(), VAbstractOperation::ExtractData(), VAbstractPattern::GetGradationHeights(), VAbstractPattern::GetGradationSizes(), VAbstractPattern::getGroupLock(), VAbstractPattern::getGroups(), VAbstractPattern::getGroupVisibility(), VDomDocument::GetParametrUsage(), VMeasurements::IsReadOnly(), VVITConverter::IsReadOnly(), VVSTConverter::IsReadOnly(), VAbstractPattern::parseItemElement(), VPattern::ParseNodePoint(), VPattern::ParsePieceDataTag(), VPattern::parsePieceElement(), VPattern::ParsePiecePatternInfo(), VAbstractPattern::ParseSANode(), VPattern::ParseToolTrueDarts(), VPattern::PointsCommonAttributes(), VPatternConverter::PortPatternLabeltoV0_6_0(), DelGroup::redo(), VDomDocument::SetAttribute(), VDomDocument::SetParametrUsage(), VMeasurements::SetReadOnly(), ShowDoublePointName::ShowDoublePointName(), ShowOperationPointName::ShowOperationPointName(), ShowPointName::ShowPointName(), and AddGroup::undo().
unitCM
const QString unitCM = QStringLiteral("cm")
Definition at line 201 of file def.cpp.
Referenced by VCommonSettings::GetUnit(), PreferencesConfigurationPage::InitUnits(), VDomDocument::MUnit(), MApplication::ParseCommandLine(), StrToUnits(), and UnitsToStr().
unitINCH
const QString unitINCH = QStringLiteral("inch")
Definition at line 202 of file def.cpp.
Referenced by VCommonSettings::GetUnit(), PreferencesConfigurationPage::InitUnits(), MApplication::ParseCommandLine(), StrToUnits(), and UnitsToStr().
unitMM
const QString unitMM = QStringLiteral("mm")
Definition at line 200 of file def.cpp.
Referenced by PreferencesConfigurationPage::InitUnits(), MApplication::ParseCommandLine(), StrToUnits(), and UnitsToStr().
unitPX
const QString unitPX = QStringLiteral("px")
Definition at line 203 of file def.cpp.
Referenced by StrToUnits(), and UnitsToStr().