Seamly2D: VIncrement Class Reference
VIncrement Class Reference
The VIncrement class keep data row of increment table.
#include <vincrement.h>
Public Member Functions
VIncrement ()
VIncrement create enpty increment.
VIncrement (VContainer *data, const QString &name, quint32 index, qreal base, const QString &formula, bool ok, const QString &description=QString())
VIncrementTableRow create increment.
VIncrement (const VIncrement &incr)
virtual ~VIncrement () Q_DECL_OVERRIDE
VIncrement & operator= (const VIncrement &incr)
void Swap (VIncrement &incr) Q_DECL_NOTHROW
quint32 getIndex () const
getIndex return index of row
QString GetFormula () const
bool IsFormulaOk () const
VContainer * GetData ()
Public Member Functions inherited from VVariable
VVariable ()
VVariable (const QString &name, const QString &description=QString())
VVariable (const VVariable &var)
virtual ~VVariable () Q_DECL_OVERRIDE
VVariable & operator= (const VVariable &var)
void Swap (VVariable &var) Q_DECL_NOTHROW
QString GetDescription () const
void SetDescription (const QString &desc)
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool Filter (quint32 id)
virtual bool isNotUsed () const
Private Attributes
QSharedDataPointer< VIncrementData > d
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
The VIncrement class keep data row of increment table.
Definition at line 69 of file vincrement.h.
Constructor & Destructor Documentation
VIncrement() [1/3]
VIncrement::VIncrement ()
VIncrement create enpty increment.
Definition at line 69 of file vincrement.cpp.
References Increment, and VInternalVariable::SetType().
VIncrement() [2/3]
VIncrement::VIncrement (VContainer * data, const QString & name, quint32 index, qreal base, const QString & formula, bool ok, const QString & description = QString())
VIncrementTableRow create increment.
Parameters
name increment's name
base value
description description of increment
Definition at line 82 of file vincrement.cpp.
References Increment, VInternalVariable::SetType(), and VInternalVariable::SetValue().
VIncrement() [3/3]
VIncrement::VIncrement (const VIncrement & incr)
Definition at line 91 of file vincrement.cpp.
~VIncrement()
VIncrement::~VIncrement () virtual
Definition at line 108 of file vincrement.cpp.
Member Function Documentation
GetData()
VContainer * VIncrement::GetData ()
Definition at line 134 of file vincrement.cpp.
References d.
GetFormula()
QString VIncrement::GetFormula () const
Definition at line 122 of file vincrement.cpp.
References d.
getIndex()
quint32 VIncrement::getIndex () const
getIndex return index of row
Returns
index
Definition at line 116 of file vincrement.cpp.
References d.
IsFormulaOk()
bool VIncrement::IsFormulaOk () const
Definition at line 128 of file vincrement.cpp.
References d.
operator=()
VIncrement & VIncrement::operator= (const VIncrement & incr)
Definition at line 96 of file vincrement.cpp.
References d, and VVariable::operator=().
Swap()
void VIncrement::Swap (VIncrement & incr)
Definition at line 62 of file vincrement.cpp.
References VVariable::Swap().
Member Data Documentation
d
QSharedDataPointer<VIncrementData> VIncrement::d private
Definition at line 92 of file vincrement.h.
Referenced by GetData(), GetFormula(), getIndex(), IsFormulaOk(), and operator=().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/vincrement.h
src/libs/vpatterndb/variables/vincrement.cpp