Seamly2D: StDOMNode< T > Class Template Reference
StDOMNode< T > Class Template Reference
#include <StDOMNode.hpp>
Public Member Functions
StDOMNode (T *node=(T *) 0)
StDOMNode (const StDOMNode &stNode)
~StDOMNode ()
T * operator= (T *node)
bool operator!= (T *node) const
bool operator== (T *node) const
T & operator* ()
const T & operator* () const
T * operator-> () const
operator T* () const
void ClearNode ()
StDOMNode (T *node=(T *) 0)
StDOMNode (const StDOMNode &stNode)
~StDOMNode ()
T * operator= (T *node)
bool operator!= (T *node) const
bool operator== (T *node) const
T & operator* ()
const T & operator* () const
T * operator-> () const
operator T* () const
void ClearNode ()
StDOMNode (T *node=(T *) 0)
StDOMNode (const StDOMNode &stNode)
~StDOMNode ()
T * operator= (T *node)
bool operator!= (T *node) const
bool operator== (T *node) const
T & operator* ()
const T & operator* () const
T * operator-> () const
operator T* () const
void ClearNode ()
Static Private Member Functions
static void INCREFCOUNT (T *x)
static void DECREFCOUNT (T *x)
static void INCREFCOUNT (T *x)
static void DECREFCOUNT (T *x)
static void INCREFCOUNT (T *x)
static void DECREFCOUNT (T *x)
Private Attributes
T * m_node
Detailed Description
template<class T>
class StDOMNode< T >
Definition at line 35 of file StDOMNode.hpp.
Constructor & Destructor Documentation
StDOMNode() [1/6]
template<class T > StDOMNode< T >::StDOMNode (T * node = (T*)0) inline
Definition at line 42 of file StDOMNode.hpp.
References StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
StDOMNode() [2/6]
template<class T > StDOMNode< T >::StDOMNode (const StDOMNode< T > & stNode) inline
Definition at line 43 of file StDOMNode.hpp.
References StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
~StDOMNode() [1/3]
template<class T > StDOMNode< T >::~StDOMNode () inline
Definition at line 44 of file StDOMNode.hpp.
References StDOMNode< T >::DECREFCOUNT(), and StDOMNode< T >::m_node.
StDOMNode() [3/6]
template<class T > StDOMNode< T >::StDOMNode (T * node = (T*)0) inline
Definition at line 42 of file StDOMNode.hpp.
References StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
StDOMNode() [4/6]
template<class T > StDOMNode< T >::StDOMNode (const StDOMNode< T > & stNode) inline
Definition at line 43 of file StDOMNode.hpp.
References StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
~StDOMNode() [2/3]
template<class T > StDOMNode< T >::~StDOMNode () inline
Definition at line 44 of file StDOMNode.hpp.
References StDOMNode< T >::DECREFCOUNT(), and StDOMNode< T >::m_node.
StDOMNode() [5/6]
template<class T > StDOMNode< T >::StDOMNode (T * node = (T*)0) inline
Definition at line 42 of file StDOMNode.hpp.
References StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
StDOMNode() [6/6]
template<class T > StDOMNode< T >::StDOMNode (const StDOMNode< T > & stNode) inline
Definition at line 43 of file StDOMNode.hpp.
References StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
~StDOMNode() [3/3]
template<class T > StDOMNode< T >::~StDOMNode () inline
Definition at line 44 of file StDOMNode.hpp.
References StDOMNode< T >::DECREFCOUNT(), and StDOMNode< T >::m_node.
Member Function Documentation
ClearNode() [1/3]
template<class T > void StDOMNode< T >::ClearNode () inline
Definition at line 63 of file StDOMNode.hpp.
References StDOMNode< T >::operator=().
ClearNode() [2/3]
template<class T > void StDOMNode< T >::ClearNode () inline
Definition at line 63 of file StDOMNode.hpp.
References StDOMNode< T >::operator=().
ClearNode() [3/3]
template<class T > void StDOMNode< T >::ClearNode () inline
Definition at line 63 of file StDOMNode.hpp.
References StDOMNode< T >::operator=().
DECREFCOUNT() [1/3]
template<class T > static void StDOMNode< T >::DECREFCOUNT (T * x) inline static private
Definition at line 39 of file StDOMNode.hpp.
Referenced by StDOMNode< T >::operator=(), and StDOMNode< T >::~StDOMNode().
DECREFCOUNT() [2/3]
template<class T > static void StDOMNode< T >::DECREFCOUNT (T * x) inline static private
Definition at line 39 of file StDOMNode.hpp.
DECREFCOUNT() [3/3]
template<class T > static void StDOMNode< T >::DECREFCOUNT (T * x) inline static private
Definition at line 39 of file StDOMNode.hpp.
INCREFCOUNT() [1/3]
template<class T > static void StDOMNode< T >::INCREFCOUNT (T * x) inline static private
Definition at line 38 of file StDOMNode.hpp.
Referenced by StDOMNode< T >::operator=(), and StDOMNode< T >::StDOMNode().
INCREFCOUNT() [2/3]
template<class T > static void StDOMNode< T >::INCREFCOUNT (T * x) inline static private
Definition at line 38 of file StDOMNode.hpp.
INCREFCOUNT() [3/3]
template<class T > static void StDOMNode< T >::INCREFCOUNT (T * x) inline static private
Definition at line 38 of file StDOMNode.hpp.
operator T*() [1/3]
template<class T > StDOMNode< T >::operator T* () const inline
Definition at line 62 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator T*() [2/3]
template<class T > StDOMNode< T >::operator T* () const inline
Definition at line 62 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator T*() [3/3]
template<class T > StDOMNode< T >::operator T* () const inline
Definition at line 62 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator!=() [1/3]
template<class T > bool StDOMNode< T >::operator!= (T * node) const inline
Definition at line 56 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator!=() [2/3]
template<class T > bool StDOMNode< T >::operator!= (T * node) const inline
Definition at line 56 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator!=() [3/3]
template<class T > bool StDOMNode< T >::operator!= (T * node) const inline
Definition at line 56 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator*() [1/6]
template<class T > T& StDOMNode< T >::operator* () inline
Definition at line 59 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator*() [2/6]
template<class T > T& StDOMNode< T >::operator* () inline
Definition at line 59 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator*() [3/6]
template<class T > T& StDOMNode< T >::operator* () inline
Definition at line 59 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator*() [4/6]
template<class T > const T& StDOMNode< T >::operator* () const inline
Definition at line 60 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator*() [5/6]
template<class T > const T& StDOMNode< T >::operator* () const inline
Definition at line 60 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator*() [6/6]
template<class T > const T& StDOMNode< T >::operator* () const inline
Definition at line 60 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator->() [1/3]
template<class T > T* StDOMNode< T >::operator-> () const inline
Definition at line 61 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator->() [2/3]
template<class T > T* StDOMNode< T >::operator-> () const inline
Definition at line 61 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator->() [3/3]
template<class T > T* StDOMNode< T >::operator-> () const inline
Definition at line 61 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator=() [1/3]
template<class T > T* StDOMNode< T >::operator= (T * node) inline
Definition at line 46 of file StDOMNode.hpp.
References StDOMNode< T >::DECREFCOUNT(), StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
Referenced by StDOMNode< T >::ClearNode().
operator=() [2/3]
template<class T > T* StDOMNode< T >::operator= (T * node) inline
Definition at line 46 of file StDOMNode.hpp.
References StDOMNode< T >::DECREFCOUNT(), StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
operator=() [3/3]
template<class T > T* StDOMNode< T >::operator= (T * node) inline
Definition at line 46 of file StDOMNode.hpp.
References StDOMNode< T >::DECREFCOUNT(), StDOMNode< T >::INCREFCOUNT(), and StDOMNode< T >::m_node.
operator==() [1/3]
template<class T > bool StDOMNode< T >::operator== (T * node) const inline
Definition at line 57 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator==() [2/3]
template<class T > bool StDOMNode< T >::operator== (T * node) const inline
Definition at line 57 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
operator==() [3/3]
template<class T > bool StDOMNode< T >::operator== (T * node) const inline
Definition at line 57 of file StDOMNode.hpp.
References StDOMNode< T >::m_node.
Member Data Documentation
m_node
template<class T > T * StDOMNode< T >::m_node private
Definition at line 36 of file StDOMNode.hpp.
Referenced by StDOMNode< T >::operator T*(), StDOMNode< T >::operator!=(), StDOMNode< T >::operator*(), StDOMNode< T >::operator->(), StDOMNode< T >::operator=(), StDOMNode< T >::operator==(), StDOMNode< T >::StDOMNode(), and StDOMNode< T >::~StDOMNode().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/dom/StDOMNode.hpp