Seamly2D: TST_NameRegExp Class Reference
TST_NameRegExp Class Reference
#include <tst_nameregexp.h>
Public Member Functions
TST_NameRegExp (QObject *parent=nullptr)
Private Slots
void TestNameRegExp_data ()
void TestNameRegExp ()
void TestOriginalMeasurementNamesRegExp_data ()
void TestOriginalMeasurementNamesRegExp ()
void TestCorrectOrderMeasurement_data ()
void TestCorrectOrderMeasurement ()
Detailed Description
Definition at line 57 of file tst_nameregexp.h.
Constructor & Destructor Documentation
TST_NameRegExp()
TST_NameRegExp::TST_NameRegExp (QObject * parent = nullptr) explicit
Definition at line 60 of file tst_nameregexp.cpp.
Member Function Documentation
TestCorrectOrderMeasurement
void TST_NameRegExp::TestCorrectOrderMeasurement () private slot
Definition at line 473 of file tst_nameregexp.cpp.
TestCorrectOrderMeasurement_data
void TST_NameRegExp::TestCorrectOrderMeasurement_data () private slot
Definition at line 214 of file tst_nameregexp.cpp.
References acrossBackB_M, acrossBackCenterToArmfoldFrontToAcrossBackCenter_M, acrossBackHalfB_M, acrossBackToWaistB_M, acrossChestF_M, acrossChestHalfF_M, armAboveElbowCirc_M, armAcrossBackCenterToElbowBent_M, armAcrossBackCenterToWristBent_M, armArmpitToElbow_M, armArmpitToWrist_M, armArmscyeBackCenterToWristBent_M, armElbowCirc_M, armElbowCircBent_M, armElbowToWrist_M, armElbowToWristBent_M, armElbowToWristInside_M, armfoldToArmfoldB_M, armfoldToArmfoldBust_M, armfoldToArmfoldF_M, armfoldToBustFront_M, armLowerCirc_M, armNeckBackToElbowBent_M, armNeckBackToWristBent_M, armNeckSideToElbowBent_M, armNeckSideToFingerTip_M, armNeckSideToOuterElbow_M, armNeckSideToWrist_M, armNeckSideToWristBent_M, armpitToWaistSide_M, armscyeArc_M, armscyeCirc_M, armscyeLength_M, armscyeWidth_M, armShoulderTipToArmfoldLine_M, armShoulderTipToElbow_M, armShoulderTipToElbowBent_M, armShoulderTipToWrist_M, armShoulderTipToWristBent_M, armUpperCirc_M, armWristCirc_M, bodyArmfoldCirc_M, bodyBustCirc_M, bodyTorsoCirc_M, bustArcB_M, bustArcF_M, bustArcHalfB_M, bustArcHalfF_M, bustCirc_M, bustpointNeckSideToWaist_M, bustpointToBustpoint_M, bustpointToBustpointHalf_M, bustpointToBustpointHalter_M, bustpointToLowbust_M, bustpointToNeckFront_M, bustpointToNeckSide_M, bustpointToShoulderCenter_M, bustpointToShoulderTip_M, bustpointToWaist_M, bustpointToWaistFront_M, bustToWaistB_M, bustToWaistF_M, crotchLength_M, crotchLengthB_M, crotchLengthF_M, dartWidthBust_M, dartWidthShoulder_M, dartWidthWaist_M, footCirc_M, footInstepCirc_M, footLength_M, footWidth_M, handCirc_M, handLength_M, handPalmCirc_M, handPalmLength_M, handPalmWidth_M, headChinToNeckBack_M, headCirc_M, headCrownToNeckBack_M, headDepth_M, headLength_M, headWidth_M, height_M, heightAnkle_M, heightAnkleHigh_M, heightArmpit_M, heightBustpoint_M, heightCalf_M, heightGlutealFold_M, heightHighhip_M, heightHip_M, heightKnee_M, heightKneeToAnkle_M, heightNeckBack_M, heightNeckBackToKnee_M, heightNeckBackToWaistSide_M, heightNeckFront_M, heightNeckSide_M, heightScapula_M, heightShoulderTip_M, heightWaistBack_M, heightWaistFront_M, heightWaistSide_M, heightWaistSideToHip_M, heightWaistSideToKnee_M, highbustArcB_M, highbustArcF_M, highbustArcHalfB_M, highbustArcHalfF_M, highbustBackOverShoulderToArmfoldFront_M, highbustBackOverShoulderToWaistFront_M, highbustBOverShoulderToHighbustF_M, highbustCirc_M, highbustToWaistB_M, highbustToWaistF_M, highhipArcB_M, highhipArcF_M, highhipArcHalfB_M, highhipArcHalfF_M, highhipCirc_M, hipArcB_M, hipArcF_M, hipArcHalfB_M, hipArcHalfF_M, hipCirc_M, hipCircWithAbdomen_M, hipWithAbdomenArcF_M, indentAnkleHigh_M, indentNeckBack_M, indentWaistBack_M, legAnkleCirc_M, legAnkleDiagCirc_M, legAnkleHighCirc_M, legCalfCirc_M, legCrotchToAnkle_M, legCrotchToFloor_M, legKneeCirc_M, legKneeCircBent_M, legKneeSmallCirc_M, legThighMidCirc_M, legThighUpperCirc_M, legWaistSideToAnkle_M, legWaistSideToFloor_M, legWaistSideToKnee_M, lowbustArcB_M, lowbustArcF_M, lowbustArcHalfB_M, lowbustArcHalfF_M, lowbustCirc_M, lowbustToWaistB_M, lowbustToWaistF_M, neckArcB_M, neckArcF_M, neckArcHalfB_M, neckArcHalfF_M, neckBackToAcrossBack_M, neckBackToArmfoldFront_M, neckBackToArmfoldFrontToHighbustBack_M, neckBackToArmfoldFrontToNeckBack_M, neckBackToArmfoldFrontToWaistSide_M, neckBackToBustB_M, neckBackToBustFront_M, neckBackToHighbustB_M, neckBackToShoulderTipB_M, neckBackToWaistB_M, neckBackToWaistFront_M, neckBackToWaistSide_M, neckCirc_M, neckFrontToBustF_M, neckFrontToHighbustF_M, neckFrontToShoulderTipF_M, neckFrontToWaistF_M, neckFrontToWaistFlatF_M, neckFrontToWaistSide_M, neckMidCirc_M, neckSideToArmfoldB_M, neckSideToArmfoldF_M, neckSideToArmpitB_M, neckSideToArmpitF_M, neckSideToBustB_M, neckSideToBustF_M, neckSideToBustSideB_M, neckSideToBustSideF_M, neckSideToHighbustB_M, neckSideToHighbustF_M, neckSideToWaistB_M, neckSideToWaistBustpointF_M, neckSideToWaistF_M, neckSideToWaistScapulaB_M, neckSideToWaistSideB_M, neckSideToWaistSideF_M, neckWidth_M, ribArcB_M, ribArcF_M, ribArcHalfB_M, ribArcHalfF_M, ribCirc_M, ribToWaistSide_M, riseLengthB_M, riseLengthDiag_M, riseLengthF_M, riseLengthSide_M, riseLengthSideSitting_M, shoulderCenterToHighbustB_M, shoulderCenterToHighbustF_M, shoulderLength_M, shoulderSlopeNeckBackAngle_M, shoulderSlopeNeckBackHeight_M, shoulderSlopeNeckSideAngle_M, shoulderSlopeNeckSideLength_M, shoulderSlopeShoulderTipAngle_M, shoulderTipToArmfoldB_M, shoulderTipToArmfoldF_M, shoulderTipToShoulderTipB_M, shoulderTipToShoulderTipF_M, shoulderTipToShoulderTipHalfB_M, shoulderTipToShoulderTipHalfF_M, shoulderTipToWaistB_1inOffset_M, shoulderTipToWaistBack_M, shoulderTipToWaistFront_M, shoulderTipToWaistSideB_M, shoulderTipToWaistSideF_M, size_M, waistArcB_M, waistArcF_M, waistArcHalfB_M, waistArcHalfF_M, waistCirc_M, waistNaturalArcB_M, waistNaturalArcF_M, waistNaturalCirc_M, waistToHighhipB_M, waistToHighhipF_M, waistToHighhipSide_M, waistToHipB_M, waistToHipF_M, waistToHipSide_M, waistToNaturalWaistB_M, waistToNaturalWaistF_M, waistToWaistHalter_M, widthAbdomenToHip_M, widthBust_M, widthHip_M, widthShoulder_M, and widthWaist_M.
TestNameRegExp
void TST_NameRegExp::TestNameRegExp () private slot
Definition at line 179 of file tst_nameregexp.cpp.
References NameRegExp().
TestNameRegExp_data
void TST_NameRegExp::TestNameRegExp_data () private slot
Definition at line 67 of file tst_nameregexp.cpp.
References INIT_LOCALE_VARIABLES.
TestOriginalMeasurementNamesRegExp
void TST_NameRegExp::TestOriginalMeasurementNamesRegExp () private slot
Definition at line 204 of file tst_nameregexp.cpp.
References NameRegExp().
TestOriginalMeasurementNamesRegExp_data
void TST_NameRegExp::TestOriginalMeasurementNamesRegExp_data () private slot
Definition at line 190 of file tst_nameregexp.cpp.
References AllGroupNames().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_nameregexp.h
src/test/Seamly2DTest/tst_nameregexp.cpp