Seamly2D: VLengthLine Class Reference
VLengthLine Class Reference
#include <vlinelength.h>
Public Member Functions
VLengthLine ()
VLengthLine (const VPointF *p1, const quint32 &p1Id, const VPointF *p2, const quint32 &p2Id, Unit patternUnit)
VLengthLine (const VLengthLine &var)
virtual ~VLengthLine () Q_DECL_OVERRIDE
VLengthLine & operator= (const VLengthLine &var)
void Swap (VLengthLine &var) Q_DECL_NOTHROW
virtual bool Filter (quint32 id) Q_DECL_OVERRIDE
void SetValue (const VPointF *p1, const VPointF *p2)
quint32 GetP1Id () const
quint32 GetP2Id () const
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool isNotUsed () const
Private Attributes
QSharedDataPointer< VLengthLineData > d
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
Definition at line 67 of file vlinelength.h.
Constructor & Destructor Documentation
VLengthLine() [1/3]
VLengthLine::VLengthLine ()
Definition at line 73 of file vlinelength.cpp.
References LineLength, and VInternalVariable::SetType().
VLengthLine() [2/3]
VLengthLine::VLengthLine (const VPointF * p1, const quint32 & p1Id, const VPointF * p2, const quint32 & p2Id, Unit patternUnit)
Definition at line 80 of file vlinelength.cpp.
References line_, LineLength, VGObject::name(), SCASSERT, VInternalVariable::SetName(), VInternalVariable::SetType(), and SetValue().
VLengthLine() [3/3]
VLengthLine::VLengthLine (const VLengthLine & var)
Definition at line 93 of file vlinelength.cpp.
~VLengthLine()
VLengthLine::~VLengthLine () virtual
Definition at line 110 of file vlinelength.cpp.
Member Function Documentation
Filter()
bool VLengthLine::Filter (quint32 id) virtual
Reimplemented from VInternalVariable.
Definition at line 114 of file vlinelength.cpp.
References d.
GetP1Id()
quint32 VLengthLine::GetP1Id () const
Definition at line 130 of file vlinelength.cpp.
References d.
GetP2Id()
quint32 VLengthLine::GetP2Id () const
Definition at line 136 of file vlinelength.cpp.
References d.
operator=()
VLengthLine & VLengthLine::operator= (const VLengthLine & var)
Definition at line 98 of file vlinelength.cpp.
References d, and VInternalVariable::operator=().
SetValue()
void VLengthLine::SetValue (const VPointF * p1, const VPointF * p2)
Definition at line 120 of file vlinelength.cpp.
References d, FromPixel(), SCASSERT, and VInternalVariable::SetValue().
Referenced by VLengthLine().
Swap()
void VLengthLine::Swap (VLengthLine & var)
Definition at line 69 of file vlinelength.cpp.
References VInternalVariable::Swap().
Member Data Documentation
d
QSharedDataPointer<VLengthLineData> VLengthLine::d private
Definition at line 88 of file vlinelength.h.
Referenced by Filter(), GetP1Id(), GetP2Id(), operator=(), and SetValue().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/vlinelength.h
src/libs/vpatterndb/variables/vlinelength.cpp