Seamly2D: VSAPoint Class Reference
VSAPoint Class Reference
The VSAPoint class seam allowance point.
#include <vabstractpiece.h>
Public Member Functions
Q_DECL_CONSTEXPR VSAPoint ()
Q_DECL_CONSTEXPR VSAPoint (qreal xpos, qreal ypos)
Q_DECL_CONSTEXPR VSAPoint (const QPointF &p)
Q_DECL_CONSTEXPR qreal GetSABefore () const
qreal GetSABefore (qreal width) const
void SetSABefore (qreal value)
Q_DECL_CONSTEXPR qreal GetSAAfter () const
qreal GetSAAfter (qreal width) const
void SetSAAfter (qreal value)
Q_DECL_CONSTEXPR PieceNodeAngle GetAngleType () const
void SetAngleType (PieceNodeAngle value)
Private Attributes
qreal m_before
qreal m_after
PieceNodeAngle m_angle
Detailed Description
The VSAPoint class seam allowance point.
Definition at line 75 of file vabstractpiece.h.
Constructor & Destructor Documentation
VSAPoint() [1/3]
Q_DECL_CONSTEXPR VSAPoint::VSAPoint () inline
Definition at line 103 of file vabstractpiece.h.
VSAPoint() [2/3]
Q_DECL_CONSTEXPR VSAPoint::VSAPoint (qreal xpos, qreal ypos) inline
Definition at line 111 of file vabstractpiece.h.
VSAPoint() [3/3]
Q_DECL_CONSTEXPR VSAPoint::VSAPoint (const QPointF & p) inline explicit
Definition at line 119 of file vabstractpiece.h.
Member Function Documentation
GetAngleType()
Q_DECL_CONSTEXPR PieceNodeAngle VSAPoint::GetAngleType () const inline
Definition at line 151 of file vabstractpiece.h.
References m_angle.
Referenced by VPiecePath::CurveSeamAllowanceSegment(), and VAbstractPiece::EkvPoint().
GetSAAfter() [1/2]
Q_DECL_CONSTEXPR qreal VSAPoint::GetSAAfter () const inline
Definition at line 139 of file vabstractpiece.h.
References m_after.
Referenced by VAbstractPiece::createParallelLine(), VPiecePath::CurveSeamAllowanceSegment(), VPiece::getSeamNotchSAPoint(), VAbstractPiece::IsEkvPointOnLine(), and VAbstractPiece::MaxLocalSA().
GetSAAfter() [2/2]
qreal VSAPoint::GetSAAfter (qreal width) const
Definition at line 1115 of file vabstractpiece.cpp.
References m_after.
GetSABefore() [1/2]
Q_DECL_CONSTEXPR qreal VSAPoint::GetSABefore () const inline
Definition at line 127 of file vabstractpiece.h.
References m_before.
Referenced by VAbstractPiece::createParallelLine(), VPiecePath::CurveSeamAllowanceSegment(), VPiece::getSeamNotchSAPoint(), VAbstractPiece::IsEkvPointOnLine(), and VAbstractPiece::MaxLocalSA().
GetSABefore() [2/2]
qreal VSAPoint::GetSABefore (qreal width) const
Definition at line 1105 of file vabstractpiece.cpp.
References m_before.
SetAngleType()
void VSAPoint::SetAngleType (PieceNodeAngle value) inline
Definition at line 157 of file vabstractpiece.h.
References m_angle.
Referenced by anonymous_namespace{vpiecepath.cpp}::CurvePoint(), and VPiecePath::CurveSeamAllowanceSegment().
SetSAAfter()
void VSAPoint::SetSAAfter (qreal value) inline
Definition at line 145 of file vabstractpiece.h.
References m_after.
Referenced by TST_VAbstractPiece::BrokenDetailEquidistant_data(), anonymous_namespace{vpiecepath.cpp}::CurvePoint(), VPiecePath::CurveSeamAllowanceSegment(), TST_VAbstractPiece::InputPointsCase1(), TST_VAbstractPiece::InputPointsCase2(), TST_VAbstractPiece::InputPointsCase3(), and TST_VAbstractPiece::InputPointsIssue646().
SetSABefore()
void VSAPoint::SetSABefore (qreal value) inline
Definition at line 133 of file vabstractpiece.h.
References m_before.
Referenced by TST_VAbstractPiece::BrokenDetailEquidistant_data(), anonymous_namespace{vpiecepath.cpp}::CurvePoint(), VPiecePath::CurveSeamAllowanceSegment(), TST_VAbstractPiece::InputPointsCase1(), TST_VAbstractPiece::InputPointsCase2(), TST_VAbstractPiece::InputPointsCase3(), and TST_VAbstractPiece::InputPointsIssue646().
Member Data Documentation
m_after
qreal VSAPoint::m_after private
Definition at line 95 of file vabstractpiece.h.
Referenced by GetSAAfter(), and SetSAAfter().
m_angle
PieceNodeAngle VSAPoint::m_angle private
Definition at line 96 of file vabstractpiece.h.
Referenced by GetAngleType(), and SetAngleType().
m_before
qreal VSAPoint::m_before private
Definition at line 94 of file vabstractpiece.h.
Referenced by GetSABefore(), and SetSABefore().
The documentation for this class was generated from the following files:
src/libs/vlayout/vabstractpiece.h
src/libs/vlayout/vabstractpiece.cpp