Seamly2D: DialogExportToCSV Class Reference
DialogExportToCSV Class Reference
#include <dialogexporttocsv.h>
Public Member Functions
DialogExportToCSV (QWidget *parent=nullptr)
virtual ~DialogExportToCSV ()
bool WithHeader () const
int SelectedMib () const
QChar Separator () const
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
Private Member Functions
void SetSeparator (const QChar &separator)
Private Attributes
Ui::DialogExportToCSV * ui
bool isInitialized
Detailed Description
Definition at line 65 of file dialogexporttocsv.h.
Constructor & Destructor Documentation
DialogExportToCSV()
DialogExportToCSV::DialogExportToCSV (QWidget * parent = nullptr) explicit
Definition at line 67 of file dialogexporttocsv.cpp.
References qApp, SCASSERT, SetSeparator(), and ui.
~DialogExportToCSV()
DialogExportToCSV::~DialogExportToCSV () virtual
Definition at line 98 of file dialogexporttocsv.cpp.
References ui.
Member Function Documentation
changeEvent()
void DialogExportToCSV::changeEvent (QEvent * event) protected virtual
Definition at line 137 of file dialogexporttocsv.cpp.
References ui.
SelectedMib()
int DialogExportToCSV::SelectedMib () const
Definition at line 110 of file dialogexporttocsv.cpp.
References ui.
Referenced by VAbstractMainWindow::exportToCSV(), MainWindow::exportToCSVData(), and TMainWindow::exportToCSVData().
Separator()
QChar DialogExportToCSV::Separator () const
Definition at line 116 of file dialogexporttocsv.cpp.
References ui.
Referenced by VAbstractMainWindow::exportToCSV(), MainWindow::exportToCSVData(), and TMainWindow::exportToCSVData().
SetSeparator()
void DialogExportToCSV::SetSeparator (const QChar & separator) private
Definition at line 171 of file dialogexporttocsv.cpp.
References ui.
Referenced by DialogExportToCSV().
showEvent()
void DialogExportToCSV::showEvent (QShowEvent * event) protected virtual
Definition at line 150 of file dialogexporttocsv.cpp.
References isInitialized.
WithHeader()
bool DialogExportToCSV::WithHeader () const
Definition at line 104 of file dialogexporttocsv.cpp.
References ui.
Referenced by VAbstractMainWindow::exportToCSV(), MainWindow::exportToCSVData(), and TMainWindow::exportToCSVData().
Member Data Documentation
isInitialized
bool DialogExportToCSV::isInitialized private
Definition at line 84 of file dialogexporttocsv.h.
Referenced by showEvent().
ui
Ui::DialogExportToCSV* DialogExportToCSV::ui private
Definition at line 83 of file dialogexporttocsv.h.
Referenced by changeEvent(), DialogExportToCSV(), SelectedMib(), Separator(), SetSeparator(), WithHeader(), and ~DialogExportToCSV().
The documentation for this class was generated from the following files:
src/libs/vmisc/dialogs/dialogexporttocsv.h
src/libs/vmisc/dialogs/dialogexporttocsv.cpp