Seamly2D: VTextManager Class Reference
VTextManager Class Reference
The VTextManager class this class is used to determine whether a collection of text lines can fit into specified bounding box and with what font size.
#include <vtextmanager.h>
Public Member Functions
VTextManager ()
VTextManager::VTextManager constructor.
virtual ~VTextManager ()=default
VTextManager (const VTextManager &text)
VTextManager & operator= (const VTextManager &text)
virtual int GetSpacing () const
GetSpacing returns the vertical spacing between the lines.
void setFont (const QFont &font)
SetFont set the text base font.
const QFont & GetFont () const
GetFont returns the text base font.
void SetFontSize (int iFS)
SetFontSize sets the font size.
void FitFontSize (qreal fW, qreal fH)
VTextManager::FitFontSize sets the font size just big enough, so that the text fits into rectangle of size (fW, fH)
QList< TextLine > GetAllSourceLines () const
int GetSourceLinesCount () const
VTextManager::GetSourceLinesCount returns the number of input text lines.
const TextLine & GetSourceLine (int i) const
VTextManager::GetSourceLine returns the reference to i-th text line.
void Update (const QString &qsName, const VPieceLabelData &data)
VTextManager::Update updates the text lines with detail data.
void Update (VAbstractPattern *pDoc)
VTextManager::Update updates the text lines with pattern info.
Private Attributes
QFont m_font
QList< TextLine > m_liLines
Static Private Attributes
static QList< TextLine > m_patternLabelLines = QList<TextLine>()
Detailed Description
The VTextManager class this class is used to determine whether a collection of text lines can fit into specified bounding box and with what font size.
Definition at line 65 of file vtextmanager.h.
Constructor & Destructor Documentation
VTextManager() [1/2]
VTextManager::VTextManager ()
VTextManager::VTextManager constructor.
Definition at line 183 of file vtextmanager.cpp.
~VTextManager()
virtual VTextManager::~VTextManager () virtual default
VTextManager() [2/2]
VTextManager::VTextManager (const VTextManager & text)
Definition at line 188 of file vtextmanager.cpp.
Member Function Documentation
FitFontSize()
void VTextManager::FitFontSize (qreal fW, qreal fH)
VTextManager::FitFontSize sets the font size just big enough, so that the text fits into rectangle of size (fW, fH)
Parameters
fW rectangle width
fH rectangle height
Definition at line 280 of file vtextmanager.cpp.
References TextLine::bold, GetSourceLine(), GetSourceLinesCount(), TextLine::italic, m_font, TextLine::m_iFontSize, TextLine::m_text, MIN_FONT_SIZE, and SetFontSize().
Referenced by VTextGraphicsItem::correctLabel().
GetAllSourceLines()
QList< TextLine > VTextManager::GetAllSourceLines () const
Definition at line 245 of file vtextmanager.cpp.
References m_liLines.
Referenced by operator=().
GetFont()
const QFont & VTextManager::GetFont () const
GetFont returns the text base font.
Returns
text base font
Definition at line 229 of file vtextmanager.cpp.
References m_font.
Referenced by VLayoutPiece::createLabelItem(), VTextGraphicsItem::getFontSize(), VTextGraphicsItem::mouseReleaseEvent(), operator=(), and VTextGraphicsItem::paint().
GetSourceLine()
const TextLine & VTextManager::GetSourceLine (int i) const
VTextManager::GetSourceLine returns the reference to i-th text line.
Parameters
i index of the requested line
Returns
reference to the requested TextLine object
Definition at line 266 of file vtextmanager.cpp.
References m_liLines.
Referenced by VLayoutPiece::createLabelItem(), FitFontSize(), VTextGraphicsItem::paint(), and anonymous_namespace{vlayoutpiece.cpp}::PieceLabelText().
GetSourceLinesCount()
int VTextManager::GetSourceLinesCount () const
VTextManager::GetSourceLinesCount returns the number of input text lines.
Returns
number of text lines that were added to the list by calling AddLine
Definition at line 255 of file vtextmanager.cpp.
References m_liLines.
Referenced by VLayoutPiece::createLabelItem(), FitFontSize(), VTextGraphicsItem::getTextLines(), VTextGraphicsItem::paint(), and anonymous_namespace{vlayoutpiece.cpp}::PieceLabelText().
GetSpacing()
int VTextManager::GetSpacing () const virtual
GetSpacing returns the vertical spacing between the lines.
Returns
spacing
Definition at line 209 of file vtextmanager.cpp.
Referenced by VLayoutPiece::createLabelItem(), and VTextGraphicsItem::paint().
operator=()
VTextManager & VTextManager::operator= (const VTextManager & text)
Definition at line 193 of file vtextmanager.cpp.
References GetAllSourceLines(), GetFont(), m_font, and m_liLines.
setFont()
void VTextManager::setFont (const QFont & font)
SetFont set the text base font.
Parameters
font text base font
Definition at line 219 of file vtextmanager.cpp.
References m_font.
Referenced by VTextGraphicsItem::setFont().
SetFontSize()
void VTextManager::SetFontSize (int iFS)
SetFontSize sets the font size.
Parameters
iFS font size in pixels
Definition at line 239 of file vtextmanager.cpp.
References m_font, and MIN_FONT_SIZE.
Referenced by FitFontSize().
Update() [1/2]
void VTextManager::Update (const QString & qsName, const VPieceLabelData & data)
VTextManager::Update updates the text lines with detail data.
Parameters
qsName detail name
data reference to the detail data
Definition at line 339 of file vtextmanager.cpp.
References VPieceLabelData::GetLabelTemplate(), anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), m_liLines, anonymous_namespace{vtextmanager.cpp}::PrepareLines(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), qApp, and anonymous_namespace{vtextmanager.cpp}::ReplacePlaceholders().
Referenced by VTextGraphicsItem::updateData().
Update() [2/2]
void VTextManager::Update (VAbstractPattern * pDoc)
VTextManager::Update updates the text lines with pattern info.
Parameters
pDoc pointer to the abstract pattern object
Definition at line 361 of file vtextmanager.cpp.
References VAbstractPattern::getPatternLabelTemplate(), VAbstractPattern::GetPatternWasChanged(), m_liLines, m_patternLabelLines, anonymous_namespace{vtextmanager.cpp}::PrepareLines(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), anonymous_namespace{vtextmanager.cpp}::ReplacePlaceholders(), and VAbstractPattern::SetPatternWasChanged().
Member Data Documentation
m_font
QFont VTextManager::m_font private
Definition at line 90 of file vtextmanager.h.
Referenced by FitFontSize(), GetFont(), operator=(), setFont(), and SetFontSize().
m_liLines
QList<TextLine> VTextManager::m_liLines private
Definition at line 91 of file vtextmanager.h.
Referenced by GetAllSourceLines(), GetSourceLine(), GetSourceLinesCount(), operator=(), and Update().
m_patternLabelLines
QList< TextLine > VTextManager::m_patternLabelLines = QList<TextLine>() static private
Definition at line 93 of file vtextmanager.h.
Referenced by Update().
The documentation for this class was generated from the following files:
src/libs/vlayout/vtextmanager.h
src/libs/vlayout/vtextmanager.cpp