Seamly2D: DialogSeamlyMePreferences Class Reference
DialogSeamlyMePreferences Class Reference
#include <dialogseamlymepreferences.h>
Signals
void updateProperties ()
Public Member Functions
DialogSeamlyMePreferences (QWidget *parent=nullptr)
virtual ~DialogSeamlyMePreferences ()
Protected Member Functions
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
virtual void resizeEvent (QResizeEvent *event) Q_DECL_OVERRIDE
Private Slots
void Apply ()
void Ok ()
void PageChanged (QListWidgetItem *current, QListWidgetItem *previous)
Private Attributes
Ui::DialogSeamlyMePreferences * ui
bool m_isInitialized
SeamlyMePreferencesConfigurationPage * m_configurationPage
SeamlyMePreferencesPathPage * m_pathPage
Detailed Description
Definition at line 66 of file dialogseamlymepreferences.h.
Constructor & Destructor Documentation
DialogSeamlyMePreferences()
DialogSeamlyMePreferences::DialogSeamlyMePreferences (QWidget * parent = nullptr) explicit
Definition at line 62 of file dialogseamlymepreferences.cpp.
References Apply(), m_configurationPage, m_pathPage, Ok(), PageChanged(), qApp, SCASSERT, and ui.
~DialogSeamlyMePreferences()
DialogSeamlyMePreferences::~DialogSeamlyMePreferences () virtual
Definition at line 89 of file dialogseamlymepreferences.cpp.
References ui.
Member Function Documentation
Apply
void DialogSeamlyMePreferences::Apply () private slot
Definition at line 134 of file dialogseamlymepreferences.cpp.
References SeamlyMePreferencesConfigurationPage::Apply(), SeamlyMePreferencesPathPage::Apply(), m_configurationPage, m_pathPage, qApp, and updateProperties().
Referenced by DialogSeamlyMePreferences(), and Ok().
Ok
void DialogSeamlyMePreferences::Ok () private slot
Definition at line 145 of file dialogseamlymepreferences.cpp.
References Apply().
Referenced by DialogSeamlyMePreferences().
PageChanged
void DialogSeamlyMePreferences::PageChanged (QListWidgetItem * current, QListWidgetItem * previous) private slot
Definition at line 152 of file dialogseamlymepreferences.cpp.
References ui.
Referenced by DialogSeamlyMePreferences().
resizeEvent()
void DialogSeamlyMePreferences::resizeEvent (QResizeEvent * event) protected virtual
Definition at line 121 of file dialogseamlymepreferences.cpp.
References m_isInitialized, and qApp.
showEvent()
void DialogSeamlyMePreferences::showEvent (QShowEvent * event) protected virtual
Definition at line 95 of file dialogseamlymepreferences.cpp.
References m_isInitialized, and qApp.
updateProperties
void DialogSeamlyMePreferences::updateProperties () signal
Referenced by Apply(), and TMainWindow::Preferences().
Member Data Documentation
m_configurationPage
SeamlyMePreferencesConfigurationPage* DialogSeamlyMePreferences::m_configurationPage private
Definition at line 86 of file dialogseamlymepreferences.h.
Referenced by Apply(), and DialogSeamlyMePreferences().
m_isInitialized
bool DialogSeamlyMePreferences::m_isInitialized private
Definition at line 85 of file dialogseamlymepreferences.h.
Referenced by resizeEvent(), and showEvent().
m_pathPage
SeamlyMePreferencesPathPage* DialogSeamlyMePreferences::m_pathPage private
Definition at line 87 of file dialogseamlymepreferences.h.
Referenced by Apply(), and DialogSeamlyMePreferences().
ui
Ui::DialogSeamlyMePreferences* DialogSeamlyMePreferences::ui private
Definition at line 84 of file dialogseamlymepreferences.h.
Referenced by DialogSeamlyMePreferences(), PageChanged(), and ~DialogSeamlyMePreferences().
The documentation for this class was generated from the following files:
src/app/seamlyme/dialogs/dialogseamlymepreferences.h
src/app/seamlyme/dialogs/dialogseamlymepreferences.cpp