Seamly2D: TST_TSTranslation Class Reference
TST_TSTranslation Class Reference
#include <tst_tstranslation.h>
Public Member Functions
TST_TSTranslation (QObject *parent=nullptr)
Private Slots
void CheckEnglishLocalization_data ()
void CheckEnglishLocalization ()
void CheckEmptyToolButton_data ()
void CheckEmptyToolButton ()
void CheckPlaceMarkerExist_data ()
void CheckPlaceMarkerExist ()
void TestPunctuation_data ()
void TestPunctuation ()
void TestHTMLTags_data ()
void TestHTMLTags ()
Private Member Functions
QDomNodeList LoadTSFile (const QString &filename)
Private Attributes
QSharedPointer< QFile > tsFile
QSharedPointer< QDomDocument > tsXML
Static Private Attributes
static const QString TagName
static const QString TagMessage
static const QString TagSource = QStringLiteral("source")
static const QString TagTranslation = QStringLiteral("translation")
static const QString AttrType = QStringLiteral("type")
static const QString AttrValVanished = QStringLiteral("vanished")
static const QString AttrValUnfinished = QStringLiteral("unfinished")
static const QString AttrValObsolete = QStringLiteral("obsolete")
Detailed Description
Definition at line 60 of file tst_tstranslation.h.
Constructor & Destructor Documentation
TST_TSTranslation()
TST_TSTranslation::TST_TSTranslation (QObject * parent = nullptr) explicit
Definition at line 72 of file tst_tstranslation.cpp.
Member Function Documentation
CheckEmptyToolButton
void TST_TSTranslation::CheckEmptyToolButton () private slot
Definition at line 176 of file tst_tstranslation.cpp.
References AttrType, AttrValObsolete, AttrValVanished, TagName, and TagTranslation.
CheckEmptyToolButton_data
void TST_TSTranslation::CheckEmptyToolButton_data () private slot
Definition at line 140 of file tst_tstranslation.cpp.
References LoadTSFile(), and TagSource.
CheckEnglishLocalization
void TST_TSTranslation::CheckEnglishLocalization () private slot
Definition at line 131 of file tst_tstranslation.cpp.
CheckEnglishLocalization_data
void TST_TSTranslation::CheckEnglishLocalization_data () private slot
Definition at line 80 of file tst_tstranslation.cpp.
References AttrType, AttrValObsolete, AttrValUnfinished, AttrValVanished, LoadTSFile(), TagSource, and TagTranslation.
CheckPlaceMarkerExist
void TST_TSTranslation::CheckPlaceMarkerExist () private slot
Definition at line 269 of file tst_tstranslation.cpp.
CheckPlaceMarkerExist_data
void TST_TSTranslation::CheckPlaceMarkerExist_data () private slot
Definition at line 206 of file tst_tstranslation.cpp.
References AttrType, AttrValObsolete, AttrValUnfinished, AttrValVanished, LoadTSFile(), SupportedLocales(), TagSource, and TagTranslation.
LoadTSFile()
QDomNodeList TST_TSTranslation::LoadTSFile (const QString & filename) private
Definition at line 521 of file tst_tstranslation.cpp.
References TagMessage, tsFile, and tsXML.
Referenced by CheckEmptyToolButton_data(), CheckEnglishLocalization_data(), CheckPlaceMarkerExist_data(), TestHTMLTags_data(), and TestPunctuation_data().
TestHTMLTags
void TST_TSTranslation::TestHTMLTags () private slot
Definition at line 491 of file tst_tstranslation.cpp.
TestHTMLTags_data
void TST_TSTranslation::TestHTMLTags_data () private slot
Definition at line 429 of file tst_tstranslation.cpp.
References AttrType, AttrValObsolete, AttrValUnfinished, AttrValVanished, LoadTSFile(), SupportedLocales(), TagSource, and TagTranslation.
TestPunctuation
void TST_TSTranslation::TestPunctuation () private slot
Definition at line 381 of file tst_tstranslation.cpp.
TestPunctuation_data
void TST_TSTranslation::TestPunctuation_data () private slot
Definition at line 318 of file tst_tstranslation.cpp.
References AttrType, AttrValObsolete, AttrValUnfinished, AttrValVanished, LoadTSFile(), SupportedLocales(), TagSource, and TagTranslation.
Member Data Documentation
AttrType
const QString TST_TSTranslation::AttrType = QStringLiteral("type") static private
Definition at line 88 of file tst_tstranslation.h.
Referenced by CheckEmptyToolButton(), CheckEnglishLocalization_data(), CheckPlaceMarkerExist_data(), TestHTMLTags_data(), and TestPunctuation_data().
AttrValObsolete
const QString TST_TSTranslation::AttrValObsolete = QStringLiteral("obsolete") static private
Definition at line 91 of file tst_tstranslation.h.
Referenced by CheckEmptyToolButton(), CheckEnglishLocalization_data(), CheckPlaceMarkerExist_data(), TestHTMLTags_data(), and TestPunctuation_data().
AttrValUnfinished
const QString TST_TSTranslation::AttrValUnfinished = QStringLiteral("unfinished") static private
Definition at line 90 of file tst_tstranslation.h.
Referenced by CheckEnglishLocalization_data(), CheckPlaceMarkerExist_data(), TestHTMLTags_data(), and TestPunctuation_data().
AttrValVanished
const QString TST_TSTranslation::AttrValVanished = QStringLiteral("vanished") static private
Definition at line 89 of file tst_tstranslation.h.
Referenced by CheckEmptyToolButton(), CheckEnglishLocalization_data(), CheckPlaceMarkerExist_data(), TestHTMLTags_data(), and TestPunctuation_data().
TagMessage
const QString TST_TSTranslation::TagMessage static private
Definition at line 84 of file tst_tstranslation.h.
Referenced by LoadTSFile().
TagName
const QString TST_TSTranslation::TagName static private
Definition at line 83 of file tst_tstranslation.h.
Referenced by CheckEmptyToolButton().
TagSource
const QString TST_TSTranslation::TagSource = QStringLiteral("source") static private
Definition at line 85 of file tst_tstranslation.h.
Referenced by CheckEmptyToolButton_data(), CheckEnglishLocalization_data(), CheckPlaceMarkerExist_data(), TestHTMLTags_data(), and TestPunctuation_data().
TagTranslation
const QString TST_TSTranslation::TagTranslation = QStringLiteral("translation") static private
Definition at line 86 of file tst_tstranslation.h.
Referenced by CheckEmptyToolButton(), CheckEnglishLocalization_data(), CheckPlaceMarkerExist_data(), TestHTMLTags_data(), and TestPunctuation_data().
tsFile
QSharedPointer<QFile> TST_TSTranslation::tsFile private
Definition at line 80 of file tst_tstranslation.h.
Referenced by LoadTSFile().
tsXML
QSharedPointer<QDomDocument> TST_TSTranslation::tsXML private
Definition at line 81 of file tst_tstranslation.h.
Referenced by LoadTSFile().
The documentation for this class was generated from the following files:
src/test/TranslationsTest/tst_tstranslation.h
src/test/TranslationsTest/tst_tstranslation.cpp