Seamly2D: Visualization Class Reference
Visualization Class Reference abstract
#include <visualization.h>
Public Slots
void mousePos (const QPointF &scenePos)
Signals
void ToolTip (const QString &toolTip)
Public Member Functions
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
virtual void RefreshGeometry ()=0
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Static Public Member Functions
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions
virtual void initPen ()=0
virtual void AddOnScene ()=0
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Static Private Member Functions
static VScaledEllipse * initPointItem (const QColor &color, QGraphicsItem *parent, qreal z=0)
Detailed Description
Definition at line 61 of file visualization.h.
Constructor & Destructor Documentation
Visualization()
Visualization::Visualization (const VContainer * data) explicit
Definition at line 67 of file visualization.cpp.
~Visualization()
virtual Visualization::~Visualization () virtual
Member Function Documentation
addItem()
template<typename Item > void Visualization::addItem (Item * item) inline protected
Definition at line 143 of file visualization.h.
References VMainGraphicsScene::mouseMove(), mousePos(), qApp, and SCASSERT.
Referenced by VisLine::AddOnScene(), and VisPath::AddOnScene().
AddOnScene()
virtual void Visualization::AddOnScene () protected pure virtual
Implemented in VisPath, and VisLine.
Referenced by VisualMode().
CurrentToolTip()
QString Visualization::CurrentToolTip () const inline
Definition at line 88 of file visualization.h.
References toolTip.
Referenced by DialogMove::ShowDialog().
drawArrow()
void Visualization::drawArrow (const QLineF & axis, QPainterPath & path, const qreal & arrow_size) protected
Definition at line 304 of file visualization.cpp.
drawArrowedLine()
void Visualization::drawArrowedLine (ArrowedLineItem * item, const QLineF & line, const QColor & color, Qt::PenStyle style = Qt::SolidLine) protected
Definition at line 261 of file visualization.cpp.
References SCASSERT.
Referenced by VisToolMove::RefreshGeometry(), and VisToolTriangle::RefreshGeometry().
DrawLine()
void Visualization::DrawLine (VScaledLine * lineItem, const QLineF & line, const QColor & color, const qreal & lineWeight, Qt::PenStyle style = Qt::SolidLine) protected virtual
Reimplemented in VisToolLine.
Definition at line 218 of file visualization.cpp.
References lineWeight, and SCASSERT.
Referenced by VisToolCubicBezierPath::Creating(), VisLine::DrawRay(), VisToolMirrorByAxis::RefreshGeometry(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCubicBezierPath::RefreshGeometry(), VisToolInternalPath::RefreshGeometry(), VisToolLineIntersectAxis::ShowIntersection(), and VisToolHeight::ShowIntersection().
DrawPath() [1/2]
void Visualization::DrawPath (VCurvePathItem * pathItem, const QPainterPath & path, const QColor & color, Qt::PenStyle style = Qt::SolidLine, const qreal & weight = 0.35, Qt::PenCapStyle cap = Qt::SquareCap) protected
Definition at line 234 of file visualization.cpp.
References lineWeight.
Referenced by VisToolRotation::AddCurve(), VisToolMove::AddDestinationCurve(), VisOperation::addFlippedCurve(), VisToolMove::AddOriginCurve(), VisToolSplinePath::Creating(), VisToolCubicBezierPath::Creating(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolPointFromArcAndTangent::RefreshGeometry(), VisToolPointOfIntersectionArcs::RefreshGeometry(), PatternPieceVisual::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCubicBezierPath::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolInternalPath::RefreshGeometry(), VisToolPointOfIntersectionCurves::RefreshGeometry(), VisToolSpline::RefreshGeometry(), and VisToolSplinePath::RefreshGeometry().
DrawPath() [2/2]
void Visualization::DrawPath (VCurvePathItem * pathItem, const QPainterPath & path, const QVector< DirectionArrow > & directionArrows, const QColor & color, Qt::PenStyle style = Qt::SolidLine, const qreal & weight = 0.35, Qt::PenCapStyle cap = Qt::SquareCap) protected
Definition at line 241 of file visualization.cpp.
References lineWeight, SCASSERT, and VCurvePathItem::SetDirectionArrows().
DrawPoint()
void Visualization::DrawPoint (QGraphicsEllipseItem * point, const QPointF & pos, const QColor & color, Qt::PenStyle style = Qt::SolidLine) protected
Definition at line 203 of file visualization.cpp.
References SCASSERT.
Referenced by VisToolCubicBezierPath::Creating(), IntersectCirclesVisual::RefreshGeometry(), IntersectCircleTangentVisual::RefreshGeometry(), VisToolMirrorByAxis::RefreshGeometry(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointFromArcAndTangent::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolPointOfIntersectionArcs::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), PatternPieceVisual::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCubicBezierPath::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolPointOfIntersectionCurves::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), and PointIntersectXYVisual::showIntersection().
FindLength()
qreal Visualization::FindLength (const QString & expression, const QHash< QString, QSharedPointer< VInternalVariable > > * vars) static
Definition at line 158 of file visualization.cpp.
References FindVal(), and qApp.
Referenced by DialogSpline::CurrentSpline(), DialogSplinePath::Length1Changed(), DialogSplinePath::Length2Changed(), IntersectCirclesVisual::setC1Radius(), IntersectCirclesVisual::setC2Radius(), IntersectCircleTangentVisual::setCRadius(), VisToolMove::SetLength(), VisToolAlongLine::setLength(), VisToolBisector::setLength(), VisToolEndLine::setLength(), VisToolNormal::setLength(), VisToolShoulderPoint::setLength(), VisToolArcWithLength::setLength(), VisToolCutArc::setLength(), VisToolCutSpline::setLength(), VisToolCutSplinePath::setLength(), VisToolPointOfContact::setRadius(), VisToolArc::setRadius(), VisToolArcWithLength::setRadius(), VisToolEllipticalArc::setRadius1(), and VisToolEllipticalArc::setRadius2().
FindVal()
qreal Visualization::FindVal (const QString & expression, const QHash< QString, QSharedPointer< VInternalVariable > > * vars) static
Definition at line 165 of file visualization.cpp.
References qmu::QmuParserError::GetExpr(), qmu::QmuParserError::GetMsg(), and qApp.
Referenced by DialogSplinePath::Angle1Changed(), DialogSplinePath::Angle2Changed(), DialogSpline::CurrentSpline(), FindLength(), VToolCutArc::makeToolTip(), VToolCutSpline::makeToolTip(), VToolCutSplinePath::makeToolTip(), VisToolMove::SetAngle(), VisToolRotation::SetAngle(), VisToolCurveIntersectAxis::SetAngle(), VisToolEndLine::SetAngle(), VisToolLineIntersectAxis::SetAngle(), VisToolArc::setF1(), VisToolArcWithLength::setF1(), VisToolEllipticalArc::setF1(), VisToolArc::setF2(), VisToolEllipticalArc::setF2(), VisToolMove::setRotation(), and VisToolEllipticalArc::setRotationAngle().
getData()
const VContainer * Visualization::getData () const
Definition at line 129 of file visualization.cpp.
References data.
GetMode()
Mode Visualization::GetMode () const
Definition at line 360 of file visualization.cpp.
References mode.
GetPointItem()
VScaledEllipse * Visualization::GetPointItem (QVector< VScaledEllipse * > & points, quint32 i, const QColor & color, QGraphicsItem * parent) static protected
Definition at line 324 of file visualization.cpp.
References initPointItem().
Referenced by VisOperation::GetPoint(), and PatternPieceVisual::GetPoint().
InitItem()
template<class Item > Item * Visualization::InitItem (const QColor & color, QGraphicsItem * parent) inline protected
Definition at line 155 of file visualization.h.
References Item.
initPen()
virtual void Visualization::initPen () protected pure virtual
Implemented in VisPath, and VisLine.
Referenced by setLineStyle(), setLineWeight(), and setMainColor().
InitPoint()
VScaledEllipse * Visualization::InitPoint (const QColor & color, QGraphicsItem * parent, qreal z = 0) const protected
Definition at line 152 of file visualization.cpp.
References initPointItem().
Referenced by VisToolSplinePath::getPoint(), VisToolCubicBezierPath::getPoint(), IntersectCirclesVisual::IntersectCirclesVisual(), IntersectCircleTangentVisual::IntersectCircleTangentVisual(), PointIntersectXYVisual::PointIntersectXYVisual(), VisToolAlongLine::VisToolAlongLine(), VisToolArc::VisToolArc(), VisToolArcWithLength::VisToolArcWithLength(), VisToolBisector::VisToolBisector(), VisToolCubicBezier::VisToolCubicBezier(), VisToolCurveIntersectAxis::VisToolCurveIntersectAxis(), VisToolCutArc::VisToolCutArc(), VisToolCutSpline::VisToolCutSpline(), VisToolCutSplinePath::VisToolCutSplinePath(), VisToolEllipticalArc::VisToolEllipticalArc(), VisToolEndLine::VisToolEndLine(), VisToolHeight::VisToolHeight(), VisToolLineIntersect::VisToolLineIntersect(), VisToolLineIntersectAxis::VisToolLineIntersectAxis(), VisToolMirrorByAxis::VisToolMirrorByAxis(), VisToolMirrorByLine::VisToolMirrorByLine(), VisToolNormal::VisToolNormal(), VisToolPointFromArcAndTangent::VisToolPointFromArcAndTangent(), VisToolPointOfContact::VisToolPointOfContact(), VisToolPointOfIntersectionArcs::VisToolPointOfIntersectionArcs(), VisToolPointOfIntersectionCurves::VisToolPointOfIntersectionCurves(), VisToolRotation::VisToolRotation(), VisToolShoulderPoint::VisToolShoulderPoint(), VisToolSpline::VisToolSpline(), VisToolTriangle::VisToolTriangle(), and VisToolTrueDarts::VisToolTrueDarts().
initPointItem()
VScaledEllipse * Visualization::initPointItem (const QColor & color, QGraphicsItem * parent, qreal z = 0) static private
Definition at line 341 of file visualization.cpp.
References defPointRadiusPixel, and PointRect().
Referenced by GetPointItem(), and InitPoint().
mousePos
void Visualization::mousePos (const QPointF & scenePos) slot
Definition at line 141 of file visualization.cpp.
References RefreshGeometry(), scenePos, ToolTip(), and toolTip.
Referenced by addItem().
RefreshGeometry()
virtual void Visualization::RefreshGeometry () pure virtual
Implemented in VisToolSplinePath, VisToolSpline, VisToolPointOfIntersectionCurves, VisToolInternalPath, VisToolEllipticalArc, VisToolCutSplinePath, VisToolCutSpline, VisToolCutArc, VisToolCubicBezierPath, VisToolCubicBezier, VisToolArcWithLength, VisToolArc, PieceAnchorPointVisual, PatternPieceVisual, VisToolTrueDarts, VisToolTriangle, VisToolShoulderPoint, VisToolPointOfIntersectionArcs, VisToolPointOfContact, VisToolPointFromArcAndTangent, VisToolNormal, VisToolLineIntersectAxis, VisToolLineIntersect, VisToolLine, VisToolHeight, VisToolEndLine, VisToolCurveIntersectAxis, VisToolBisector, VisToolAlongLine, PointIntersectXYVisual, VisToolRotation, VisToolMove, VisToolMirrorByLine, VisToolMirrorByAxis, IntersectCircleTangentVisual, IntersectCirclesVisual, and AnchorPointVisual.
Referenced by mousePos(), VisualMode(), and VisOperation::VisualMode().
setData()
void Visualization::setData (const VContainer * data)
Definition at line 135 of file visualization.cpp.
References data.
setLineStyle()
void Visualization::setLineStyle (const Qt::PenStyle & value)
Definition at line 87 of file visualization.cpp.
References initPen(), and lineStyle.
Referenced by DialogAlongLine::SaveData(), DialogBisector::SaveData(), DialogCurveIntersectAxis::SaveData(), DialogEndLine::SaveData(), DialogHeight::SaveData(), DialogLine::SaveData(), DialogLineIntersectAxis::SaveData(), DialogNormal::SaveData(), DialogShoulderPoint::SaveData(), PointIntersectXYDialog::SaveData(), VToolSpline::SetVisualization(), VToolSplinePath::SetVisualization(), PointIntersectXYTool::SetVisualization(), VToolCutArc::SetVisualization(), VToolCutSpline::SetVisualization(), VToolCutSplinePath::SetVisualization(), VToolAlongLine::SetVisualization(), VToolBisector::SetVisualization(), VToolCurveIntersectAxis::SetVisualization(), VToolEndLine::SetVisualization(), VToolHeight::SetVisualization(), VToolLineIntersectAxis::SetVisualization(), VToolNormal::SetVisualization(), VToolShoulderPoint::SetVisualization(), and VToolLine::SetVisualization().
setLineWeight()
void Visualization::setLineWeight (const QString & value)
Definition at line 94 of file visualization.cpp.
References initPen(), lineWeight, Mm, and ToPixel().
Referenced by DialogAlongLine::SaveData(), DialogBisector::SaveData(), DialogCurveIntersectAxis::SaveData(), DialogEndLine::SaveData(), DialogHeight::SaveData(), DialogLine::SaveData(), DialogLineIntersectAxis::SaveData(), DialogNormal::SaveData(), DialogShoulderPoint::SaveData(), PointIntersectXYDialog::SaveData(), VToolSplinePath::SetVisualization(), PointIntersectXYTool::SetVisualization(), VToolAlongLine::SetVisualization(), VToolBisector::SetVisualization(), VToolCurveIntersectAxis::SetVisualization(), VToolEndLine::SetVisualization(), VToolHeight::SetVisualization(), VToolLineIntersectAxis::SetVisualization(), VToolNormal::SetVisualization(), VToolShoulderPoint::SetVisualization(), and VToolLine::SetVisualization().
setMainColor()
void Visualization::setMainColor (const QColor & value)
Definition at line 122 of file visualization.cpp.
References initPen(), and mainColor.
SetMode()
void Visualization::SetMode (const Mode & value)
Definition at line 366 of file visualization.cpp.
References mode.
Referenced by VToolSpline::SetVisualization(), and VToolSplinePath::SetVisualization().
setObject1Id()
void Visualization::setObject1Id (const quint32 & value)
Definition at line 81 of file visualization.cpp.
References object1Id.
Referenced by DialogAlongLine::SaveData(), DialogArc::SaveData(), DialogArcWithLength::SaveData(), DialogBisector::SaveData(), DialogCurveIntersectAxis::SaveData(), DialogCutArc::SaveData(), DialogCutSpline::SaveData(), DialogCutSplinePath::SaveData(), DialogEllipticalArc::SaveData(), DialogEndLine::SaveData(), DialogHeight::SaveData(), DialogLine::SaveData(), DialogLineIntersect::SaveData(), DialogLineIntersectAxis::SaveData(), DialogNormal::SaveData(), DialogPointFromArcAndTangent::SaveData(), DialogPointOfContact::SaveData(), DialogShoulderPoint::SaveData(), DialogTriangle::SaveData(), DialogTrueDarts::SaveData(), IntersectCirclesDialog::SaveData(), IntersectCircleTangentDialog::SaveData(), DialogCutArc::setArcId(), DialogTriangle::SetAxisP1Id(), DialogEndLine::SetBasePointId(), DialogHeight::SetBasePointId(), DialogCurveIntersectAxis::setCurveId(), DialogTrueDarts::SetFirstBasePointId(), IntersectCirclesDialog::SetFirstCircleCenterId(), DialogLine::setFirstPoint(), DialogPointOfContact::SetFirstPoint(), DialogAlongLine::SetFirstPointId(), DialogBisector::SetFirstPointId(), DialogLineIntersectAxis::SetFirstPointId(), DialogNormal::SetFirstPointId(), DialogLineIntersect::SetP1Line1(), DialogShoulderPoint::SetP3(), AnchorPointDialog::SetPointId(), DialogCutSpline::setSplineId(), DialogCutSplinePath::setSplinePathId(), DialogPointFromArcAndTangent::SetTangentPointId(), IntersectCircleTangentDialog::SetTangentPointId(), VToolSpline::SetVisualization(), VToolTrueDarts::SetVisualization(), IntersectCirclesTool::SetVisualization(), IntersectCircleTangentTool::SetVisualization(), PointIntersectXYTool::SetVisualization(), VToolCutArc::SetVisualization(), VToolCutSpline::SetVisualization(), VToolCutSplinePath::SetVisualization(), VToolAlongLine::SetVisualization(), VToolBisector::SetVisualization(), VToolCurveIntersectAxis::SetVisualization(), VToolEndLine::SetVisualization(), VToolHeight::SetVisualization(), VToolLineIntersectAxis::SetVisualization(), VToolNormal::SetVisualization(), VToolShoulderPoint::SetVisualization(), VToolLineIntersect::SetVisualization(), VToolPointFromArcAndTangent::SetVisualization(), VToolPointOfContact::SetVisualization(), VToolTriangle::SetVisualization(), and VToolLine::SetVisualization().
setScenePos()
void Visualization::setScenePos (const QPointF & value)
Definition at line 102 of file visualization.cpp.
References scenePos.
ToolTip
void Visualization::ToolTip (const QString & toolTip) signal
Referenced by VAbstractTool::AddVisualization(), DialogCubicBezierPath::ChosenObject(), DialogCurveIntersectAxis::ChosenObject(), DialogEndLine::ChosenObject(), DialogLineIntersectAxis::ChosenObject(), DialogRotation::ChosenObject(), DialogSplinePath::ChosenObject(), mousePos(), VisToolSpline::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), VisToolCubicBezierPath::RefreshToolTip(), DialogMove::ShowDialog(), VisToolSpline::~VisToolSpline(), and VisToolSplinePath::~VisToolSplinePath().
VisualMode()
void Visualization::VisualMode (const quint32 & pointId) virtual
Reimplemented in VisOperation, VisToolPointOfIntersectionCurves, VisToolPointOfIntersectionArcs, and IntersectCirclesVisual.
Definition at line 108 of file visualization.cpp.
References AddOnScene(), VMainGraphicsScene::getScenePos(), object1Id, qApp, RefreshGeometry(), SCASSERT, and scenePos.
Referenced by DialogAlongLine::ChosenObject(), DialogBisector::ChosenObject(), DialogCurveIntersectAxis::ChosenObject(), DialogHeight::ChosenObject(), DialogLineIntersect::ChosenObject(), DialogLineIntersectAxis::ChosenObject(), DialogNormal::ChosenObject(), DialogPointFromArcAndTangent::ChosenObject(), DialogPointOfContact::ChosenObject(), DialogShoulderPoint::ChosenObject(), DialogTriangle::ChosenObject(), DialogTrueDarts::ChosenObject(), and IntersectCircleTangentDialog::ChosenObject().
Member Data Documentation
data
const VContainer* Visualization::data protected
Definition at line 97 of file visualization.h.
Referenced by VisToolRotation::AddCurve(), VisToolMove::AddDestinationCurve(), VisOperation::addFlippedCurve(), VisToolMove::AddOriginCurve(), VisToolMove::createOriginObjects(), VisToolMove::createRotatedObjects(), getData(), AnchorPointVisual::RefreshGeometry(), IntersectCirclesVisual::RefreshGeometry(), IntersectCircleTangentVisual::RefreshGeometry(), VisToolMirrorByAxis::RefreshGeometry(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), VisToolRotation::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLine::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointFromArcAndTangent::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolPointOfIntersectionArcs::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), PatternPieceVisual::RefreshGeometry(), PieceAnchorPointVisual::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolInternalPath::RefreshGeometry(), VisToolPointOfIntersectionCurves::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisOperation::refreshMirroredObjects(), VisToolMove::SetAngle(), VisToolRotation::SetAngle(), VisToolCurveIntersectAxis::SetAngle(), VisToolEndLine::SetAngle(), VisToolLineIntersectAxis::SetAngle(), IntersectCirclesVisual::setC1Radius(), IntersectCirclesVisual::setC2Radius(), IntersectCircleTangentVisual::setCRadius(), setData(), VisToolArc::setF1(), VisToolArcWithLength::setF1(), VisToolEllipticalArc::setF1(), VisToolArc::setF2(), VisToolEllipticalArc::setF2(), VisToolMove::SetLength(), VisToolAlongLine::setLength(), VisToolBisector::setLength(), VisToolEndLine::setLength(), VisToolNormal::setLength(), VisToolShoulderPoint::setLength(), VisToolArcWithLength::setLength(), VisToolCutArc::setLength(), VisToolCutSpline::setLength(), VisToolCutSplinePath::setLength(), VisToolPointOfContact::setRadius(), VisToolArc::setRadius(), VisToolArcWithLength::setRadius(), VisToolEllipticalArc::setRadius1(), VisToolEllipticalArc::setRadius2(), VisToolMove::setRotation(), and VisToolEllipticalArc::setRotationAngle().
lineStyle
Qt::PenStyle Visualization::lineStyle protected
Definition at line 101 of file visualization.h.
Referenced by VisLine::initPen(), VisPath::initPen(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLine::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCubicBezierPath::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), and setLineStyle().
lineWeight
qreal Visualization::lineWeight protected
Definition at line 102 of file visualization.h.
Referenced by VisToolRotation::AddCurve(), VisToolMove::AddDestinationCurve(), VisOperation::addFlippedCurve(), VisToolMove::AddOriginCurve(), VisToolSplinePath::Creating(), VisToolCubicBezierPath::Creating(), DrawLine(), VisToolLine::DrawLine(), DrawPath(), VisLine::initPen(), VisPath::initPen(), VisToolMirrorByAxis::RefreshGeometry(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLine::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointFromArcAndTangent::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolPointOfIntersectionArcs::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCubicBezierPath::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolInternalPath::RefreshGeometry(), VisToolPointOfIntersectionCurves::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), setLineWeight(), and VisToolLineIntersectAxis::ShowIntersection().
mainColor
QColor Visualization::mainColor protected
Definition at line 99 of file visualization.h.
Referenced by AnchorPointVisual::AnchorPointVisual(), VisToolSplinePath::Creating(), VisToolCubicBezierPath::Creating(), VisToolCubicBezierPath::getLine(), VisLine::initPen(), VisPath::initPen(), IntersectCirclesVisual::IntersectCirclesVisual(), IntersectCircleTangentVisual::IntersectCircleTangentVisual(), PointIntersectXYVisual::PointIntersectXYVisual(), IntersectCirclesVisual::RefreshGeometry(), IntersectCircleTangentVisual::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLine::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointFromArcAndTangent::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolPointOfIntersectionArcs::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), PatternPieceVisual::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCubicBezierPath::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolInternalPath::RefreshGeometry(), VisToolPointOfIntersectionCurves::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), setMainColor(), VisToolAlongLine::VisToolAlongLine(), VisToolArc::VisToolArc(), VisToolArcWithLength::VisToolArcWithLength(), VisToolBisector::VisToolBisector(), VisToolCubicBezier::VisToolCubicBezier(), VisToolCubicBezierPath::VisToolCubicBezierPath(), VisToolCurveIntersectAxis::VisToolCurveIntersectAxis(), VisToolCutArc::VisToolCutArc(), VisToolCutSpline::VisToolCutSpline(), VisToolCutSplinePath::VisToolCutSplinePath(), VisToolEllipticalArc::VisToolEllipticalArc(), VisToolEndLine::VisToolEndLine(), VisToolHeight::VisToolHeight(), VisToolLine::VisToolLine(), VisToolLineIntersect::VisToolLineIntersect(), VisToolLineIntersectAxis::VisToolLineIntersectAxis(), VisToolNormal::VisToolNormal(), VisToolPointFromArcAndTangent::VisToolPointFromArcAndTangent(), VisToolPointOfContact::VisToolPointOfContact(), VisToolPointOfIntersectionArcs::VisToolPointOfIntersectionArcs(), VisToolPointOfIntersectionCurves::VisToolPointOfIntersectionCurves(), VisToolShoulderPoint::VisToolShoulderPoint(), VisToolSplinePath::VisToolSplinePath(), VisToolTriangle::VisToolTriangle(), and VisToolTrueDarts::VisToolTrueDarts().
mode
Mode Visualization::mode protected
Definition at line 105 of file visualization.h.
Referenced by GetMode(), VisToolSpline::MouseLeftPressed(), VisToolSplinePath::MouseLeftPressed(), VisToolSpline::MouseLeftReleased(), VisToolSplinePath::MouseLeftReleased(), AnchorPointVisual::RefreshGeometry(), VisToolCubicBezierPath::RefreshGeometry(), VisToolInternalPath::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), VisToolCubicBezierPath::RefreshToolTip(), and SetMode().
object1Id
quint32 Visualization::object1Id protected
Definition at line 103 of file visualization.h.
Referenced by VisToolRotation::AddCurve(), VisOperation::addFlippedCurve(), AnchorPointVisual::RefreshGeometry(), IntersectCirclesVisual::RefreshGeometry(), IntersectCircleTangentVisual::RefreshGeometry(), VisToolMirrorByAxis::RefreshGeometry(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLine::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointFromArcAndTangent::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolPointOfIntersectionCurves::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisToolMirrorByLine::setFirstLinePointId(), setObject1Id(), VisToolMirrorByAxis::setOriginPointId(), VisToolMove::setOriginPointId(), VisToolRotation::SetOriginPointId(), PointIntersectXYVisual::setPoint1Id(), IntersectCirclesVisual::VisualMode(), VisToolPointOfIntersectionCurves::VisualMode(), and VisualMode().
scenePos
QPointF Visualization::scenePos protected
Definition at line 98 of file visualization.h.
Referenced by VisToolSplinePath::Creating(), VisToolCubicBezierPath::Creating(), mousePos(), VisLine::Ray(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), VisToolRotation::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLine::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolInternalPath::RefreshGeometry(), VisToolSpline::RefreshGeometry(), setScenePos(), IntersectCirclesVisual::VisualMode(), VisToolPointOfIntersectionArcs::VisualMode(), VisToolPointOfIntersectionCurves::VisualMode(), VisualMode(), and VisOperation::VisualMode().
supportColor
QColor Visualization::supportColor protected
Definition at line 100 of file visualization.h.
Referenced by VisToolRotation::AddCurve(), VisToolMove::AddDestinationCurve(), VisOperation::addFlippedCurve(), IntersectCircleTangentVisual::FindRays(), VisToolPointFromArcAndTangent::FindRays(), VisToolSplinePath::getPoint(), VisToolCubicBezierPath::getPoint(), IntersectCirclesVisual::IntersectCirclesVisual(), IntersectCircleTangentVisual::IntersectCircleTangentVisual(), PatternPieceVisual::PatternPieceVisual(), PointIntersectXYVisual::PointIntersectXYVisual(), IntersectCirclesVisual::RefreshGeometry(), IntersectCircleTangentVisual::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointFromArcAndTangent::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), PieceAnchorPointVisual::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCubicBezierPath::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolInternalPath::RefreshGeometry(), VisToolPointOfIntersectionCurves::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), VisToolLineIntersectAxis::ShowIntersection(), VisToolHeight::ShowIntersection(), VisToolAlongLine::VisToolAlongLine(), VisToolBisector::VisToolBisector(), VisToolCubicBezier::VisToolCubicBezier(), VisToolCurveIntersectAxis::VisToolCurveIntersectAxis(), VisToolHeight::VisToolHeight(), VisToolInternalPath::VisToolInternalPath(), VisToolLineIntersect::VisToolLineIntersect(), VisToolLineIntersectAxis::VisToolLineIntersectAxis(), VisToolNormal::VisToolNormal(), VisToolPointFromArcAndTangent::VisToolPointFromArcAndTangent(), VisToolPointOfContact::VisToolPointOfContact(), VisToolPointOfIntersectionCurves::VisToolPointOfIntersectionCurves(), VisToolShoulderPoint::VisToolShoulderPoint(), VisToolSpline::VisToolSpline(), VisToolTriangle::VisToolTriangle(), and VisToolTrueDarts::VisToolTrueDarts().
toolTip
QString Visualization::toolTip protected
Definition at line 104 of file visualization.h.
Referenced by CurrentToolTip(), mousePos(), VisToolMove::RefreshGeometry(), VisToolRotation::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), and VisToolCubicBezierPath::RefreshToolTip().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/visualization.h
src/libs/vtools/visualization/visualization.cpp