Seamly2D: XMLAttDef Class Reference
XMLAttDef Class Reference abstract
#include <XMLAttDef.hpp>
Public Types
enum AttTypes {
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1 , CData = 0 , ID = 1 ,
IDRef = 2 , IDRefs = 3 , Entity = 4 , Entities = 5 ,
NmToken = 6 , NmTokens = 7 , Notation = 8 , Enumeration = 9 ,
Simple = 10 , Any_Any = 11 , Any_Other = 12 , Any_List = 13 ,
AttTypes_Count , AttTypes_Min = 0 , AttTypes_Max = 13 , AttTypes_Unknown = -1 ,
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1
}
enum DefAttTypes {
Default = 0 , Fixed = 1 , Required = 2 , Required_And_Fixed = 3 ,
Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 , ProcessContents_Strict = 7 ,
Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 , DefAttTypes_Max = 8 ,
DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 , Required = 2 ,
Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 ,
ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 ,
DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 ,
Required = 2 , Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 ,
ProcessContents_Lax = 6 , ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count ,
DefAttTypes_Min = 0 , DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1
}
enum CreateReasons {
NoReason , JustFaultIn , NoReason , JustFaultIn ,
NoReason , JustFaultIn
}
enum AttTypes {
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1 , CData = 0 , ID = 1 ,
IDRef = 2 , IDRefs = 3 , Entity = 4 , Entities = 5 ,
NmToken = 6 , NmTokens = 7 , Notation = 8 , Enumeration = 9 ,
Simple = 10 , Any_Any = 11 , Any_Other = 12 , Any_List = 13 ,
AttTypes_Count , AttTypes_Min = 0 , AttTypes_Max = 13 , AttTypes_Unknown = -1 ,
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1
}
enum DefAttTypes {
Default = 0 , Fixed = 1 , Required = 2 , Required_And_Fixed = 3 ,
Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 , ProcessContents_Strict = 7 ,
Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 , DefAttTypes_Max = 8 ,
DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 , Required = 2 ,
Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 ,
ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 ,
DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 ,
Required = 2 , Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 ,
ProcessContents_Lax = 6 , ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count ,
DefAttTypes_Min = 0 , DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1
}
enum CreateReasons {
NoReason , JustFaultIn , NoReason , JustFaultIn ,
NoReason , JustFaultIn
}
enum AttTypes {
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1 , CData = 0 , ID = 1 ,
IDRef = 2 , IDRefs = 3 , Entity = 4 , Entities = 5 ,
NmToken = 6 , NmTokens = 7 , Notation = 8 , Enumeration = 9 ,
Simple = 10 , Any_Any = 11 , Any_Other = 12 , Any_List = 13 ,
AttTypes_Count , AttTypes_Min = 0 , AttTypes_Max = 13 , AttTypes_Unknown = -1 ,
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1
}
enum DefAttTypes {
Default = 0 , Fixed = 1 , Required = 2 , Required_And_Fixed = 3 ,
Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 , ProcessContents_Strict = 7 ,
Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 , DefAttTypes_Max = 8 ,
DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 , Required = 2 ,
Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 ,
ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 ,
DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 ,
Required = 2 , Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 ,
ProcessContents_Lax = 6 , ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count ,
DefAttTypes_Min = 0 , DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1
}
enum CreateReasons {
NoReason , JustFaultIn , NoReason , JustFaultIn ,
NoReason , JustFaultIn
}
Public Member Functions
Destructor
virtual ~XMLAttDef ()
virtual ~XMLAttDef ()
virtual ~XMLAttDef ()
Virtual interface
virtual const XMLCh * getFullName () const =0
virtual void reset ()=0
virtual const XMLCh * getFullName () const =0
virtual void reset ()=0
virtual const XMLCh * getFullName () const =0
virtual void reset ()=0
Getter methods
DefAttTypes getDefaultType () const
const XMLCh * getEnumeration () const
XMLSize_t getId () const
AttTypes getType () const
const XMLCh * getValue () const
CreateReasons getCreateReason () const
bool isExternal () const
MemoryManager * getMemoryManager () const
DefAttTypes getDefaultType () const
const XMLCh * getEnumeration () const
XMLSize_t getId () const
AttTypes getType () const
const XMLCh * getValue () const
CreateReasons getCreateReason () const
bool isExternal () const
MemoryManager * getMemoryManager () const
DefAttTypes getDefaultType () const
const XMLCh * getEnumeration () const
XMLSize_t getId () const
AttTypes getType () const
const XMLCh * getValue () const
CreateReasons getCreateReason () const
bool isExternal () const
MemoryManager * getMemoryManager () const
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Static Public Member Functions
Public, static methods
static const XMLCh * getAttTypeString (const AttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getAttTypeString (const AttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getAttTypeString (const AttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Static Public Attributes
static const unsigned int fgInvalidAttrId
Setter methods
DefAttTypes fDefaultType
AttTypes fType
CreateReasons fCreateReason
bool fExternalAttribute
XMLSize_t fId
XMLCh * fValue
XMLCh * fEnumeration
MemoryManager * fMemoryManager
void setDefaultType (const XMLAttDef::DefAttTypes newValue)
void setId (const XMLSize_t newId)
void setType (const XMLAttDef::AttTypes newValue)
void setValue (const XMLCh *const newValue)
void setEnumeration (const XMLCh *const newValue)
void setCreateReason (const CreateReasons newReason)
void setExternalAttDeclaration (const bool aValue)
void setDefaultType (const XMLAttDef::DefAttTypes newValue)
void setId (const XMLSize_t newId)
void setType (const XMLAttDef::AttTypes newValue)
void setValue (const XMLCh *const newValue)
void setEnumeration (const XMLCh *const newValue)
void setCreateReason (const CreateReasons newReason)
void setExternalAttDeclaration (const bool aValue)
void setDefaultType (const XMLAttDef::DefAttTypes newValue)
void setId (const XMLSize_t newId)
void setType (const XMLAttDef::AttTypes newValue)
void setValue (const XMLCh *const newValue)
void setEnumeration (const XMLCh *const newValue)
void setCreateReason (const CreateReasons newReason)
void setExternalAttDeclaration (const bool aValue)
XMLAttDef (const AttTypes type=CData, const DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const AttTypes type=CData, const DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const AttTypes type=CData, const DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const XMLAttDef &)
XMLAttDef & operator= (const XMLAttDef &)
void cleanUp ()
XMLAttDef (const XMLAttDef &)
XMLAttDef & operator= (const XMLAttDef &)
void cleanUp ()
XMLAttDef (const XMLAttDef &)
XMLAttDef & operator= (const XMLAttDef &)
void cleanUp ()
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Represents the core information of an attribute definition
This class defines the basic characteristics of an attribute, no matter what type of validator is used. If a particular schema associates more information with an attribute it will create a derivative of this class. So this class provides an abstract way to get basic information on attributes from any type of validator.
This class supports keyed collection semantics on the fully qualified attribute name, by providing a getKey() method to extract the key string. getKey(), in this case, just calls the virtual method getFullName() to get the fully qualified name, as defined by the derived class.
Note that the 'value' of an attribute type definition is the default or of fixed value given to it in its definition. If the attribute is of the enumerated or notation type, it will have an 'enumeration value' as well which is a space separated list of its possible vlaues.
Definition at line 52 of file XMLAttDef.hpp.
Member Enumeration Documentation
AttTypes [1/3]
enum XMLAttDef::AttTypes
Enumerator
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
Definition at line 71 of file XMLAttDef.hpp.
AttTypes [2/3]
enum XMLAttDef::AttTypes
Enumerator
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
Definition at line 71 of file XMLAttDef.hpp.
AttTypes [3/3]
enum XMLAttDef::AttTypes
Enumerator
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
CData
ID
IDRef
IDRefs
Entity
Entities
NmToken
NmTokens
Notation
Enumeration
Simple
Any_Any
Any_Other
Any_List
AttTypes_Count
AttTypes_Min
AttTypes_Max
AttTypes_Unknown
Definition at line 71 of file XMLAttDef.hpp.
CreateReasons [1/3]
enum XMLAttDef::CreateReasons
Enumerator
NoReason
JustFaultIn
NoReason
JustFaultIn
NoReason
JustFaultIn
Definition at line 112 of file XMLAttDef.hpp.
CreateReasons [2/3]
enum XMLAttDef::CreateReasons
Enumerator
NoReason
JustFaultIn
NoReason
JustFaultIn
NoReason
JustFaultIn
Definition at line 112 of file XMLAttDef.hpp.
CreateReasons [3/3]
enum XMLAttDef::CreateReasons
Enumerator
NoReason
JustFaultIn
NoReason
JustFaultIn
NoReason
JustFaultIn
Definition at line 112 of file XMLAttDef.hpp.
DefAttTypes [1/3]
enum XMLAttDef::DefAttTypes
Enumerator
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Definition at line 94 of file XMLAttDef.hpp.
DefAttTypes [2/3]
enum XMLAttDef::DefAttTypes
Enumerator
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Definition at line 94 of file XMLAttDef.hpp.
DefAttTypes [3/3]
enum XMLAttDef::DefAttTypes
Enumerator
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Default
Fixed
Required
Required_And_Fixed
Implied
ProcessContents_Skip
ProcessContents_Lax
ProcessContents_Strict
Prohibited
DefAttTypes_Count
DefAttTypes_Min
DefAttTypes_Max
DefAttTypes_Unknown
Definition at line 94 of file XMLAttDef.hpp.
Constructor & Destructor Documentation
~XMLAttDef() [1/3]
virtual XMLAttDef::~XMLAttDef () virtual
Destructor
XMLAttDef() [1/9]
XMLAttDef::XMLAttDef (const AttTypes type = CData, const DefAttTypes defType = Implied, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAttDef() [2/9]
XMLAttDef::XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAttDef() [3/9]
XMLAttDef::XMLAttDef (const XMLAttDef &) private
~XMLAttDef() [2/3]
virtual XMLAttDef::~XMLAttDef () virtual
Destructor
XMLAttDef() [4/9]
XMLAttDef::XMLAttDef (const AttTypes type = CData, const DefAttTypes defType = Implied, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAttDef() [5/9]
XMLAttDef::XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAttDef() [6/9]
XMLAttDef::XMLAttDef (const XMLAttDef &) private
~XMLAttDef() [3/3]
virtual XMLAttDef::~XMLAttDef () virtual
Destructor
XMLAttDef() [7/9]
XMLAttDef::XMLAttDef (const AttTypes type = CData, const DefAttTypes defType = Implied, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAttDef() [8/9]
XMLAttDef::XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAttDef() [9/9]
XMLAttDef::XMLAttDef (const XMLAttDef &) private
Member Function Documentation
cleanUp() [1/3]
void XMLAttDef::cleanUp () private
cleanUp() [2/3]
void XMLAttDef::cleanUp () private
cleanUp() [3/3]
void XMLAttDef::cleanUp () private
getAttTypeString() [1/3]
static const XMLCh* XMLAttDef::getAttTypeString (const AttTypes attrType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Get a string representation of the passed attribute type enum
This method allows you to get a textual representation of an attribute type, mostly for debug or display.
Parameters
attrType The attribute type value to get the string for.
manager The MemoryManager to use to allocate objects
Returns
A const pointer to the static string that holds the text description of the passed type.
getAttTypeString() [2/3]
static const XMLCh* XMLAttDef::getAttTypeString (const AttTypes attrType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Get a string representation of the passed attribute type enum
This method allows you to get a textual representation of an attribute type, mostly for debug or display.
Parameters
attrType The attribute type value to get the string for.
manager The MemoryManager to use to allocate objects
Returns
A const pointer to the static string that holds the text description of the passed type.
getAttTypeString() [3/3]
static const XMLCh* XMLAttDef::getAttTypeString (const AttTypes attrType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Get a string representation of the passed attribute type enum
This method allows you to get a textual representation of an attribute type, mostly for debug or display.
Parameters
attrType The attribute type value to get the string for.
manager The MemoryManager to use to allocate objects
Returns
A const pointer to the static string that holds the text description of the passed type.
getCreateReason() [1/3]
XMLAttDef::CreateReasons XMLAttDef::getCreateReason () const inline
Get the create reason for this attribute
This method returns an enumeration which indicates why this attribute declaration exists.
Returns
An enumerated value that indicates the reason why this attribute was added to the attribute table.
Definition at line 477 of file XMLAttDef.hpp.
References fCreateReason.
getCreateReason() [2/3]
CreateReasons XMLAttDef::getCreateReason () const
Get the create reason for this attribute
This method returns an enumeration which indicates why this attribute declaration exists.
Returns
An enumerated value that indicates the reason why this attribute was added to the attribute table.
getCreateReason() [3/3]
CreateReasons XMLAttDef::getCreateReason () const
Get the create reason for this attribute
This method returns an enumeration which indicates why this attribute declaration exists.
Returns
An enumerated value that indicates the reason why this attribute was added to the attribute table.
getDefAttTypeString() [1/3]
static const XMLCh* XMLAttDef::getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Get a string representation of the passed def attribute type enum
This method allows you to get a textual representation of an default attributetype, mostly for debug or display.
Parameters
attrType The default attribute type value to get the string for.
manager The MemoryManager to use to allocate objects
Returns
A const pointer to the static string that holds the text description of the passed default type.
getDefAttTypeString() [2/3]
static const XMLCh* XMLAttDef::getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Get a string representation of the passed def attribute type enum
This method allows you to get a textual representation of an default attributetype, mostly for debug or display.
Parameters
attrType The default attribute type value to get the string for.
manager The MemoryManager to use to allocate objects
Returns
A const pointer to the static string that holds the text description of the passed default type.
getDefAttTypeString() [3/3]
static const XMLCh* XMLAttDef::getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Get a string representation of the passed def attribute type enum
This method allows you to get a textual representation of an default attributetype, mostly for debug or display.
Parameters
attrType The default attribute type value to get the string for.
manager The MemoryManager to use to allocate objects
Returns
A const pointer to the static string that holds the text description of the passed default type.
getDefaultType() [1/3]
XMLAttDef::DefAttTypes XMLAttDef::getDefaultType () const inline
Get the default type of this attribute type
This method returns the 'default type' of the attribute. Default type in this case refers to the XML concept of a default type for an attribute, i.e. #FIXED, #IMPLIED, etc...
Returns
The default type enum for this attribute type.
Definition at line 452 of file XMLAttDef.hpp.
References fDefaultType.
Referenced by TraverseSchema::copyWildCardData().
getDefaultType() [2/3]
DefAttTypes XMLAttDef::getDefaultType () const
Get the default type of this attribute type
This method returns the 'default type' of the attribute. Default type in this case refers to the XML concept of a default type for an attribute, i.e. #FIXED, #IMPLIED, etc...
Returns
The default type enum for this attribute type.
getDefaultType() [3/3]
DefAttTypes XMLAttDef::getDefaultType () const
Get the default type of this attribute type
This method returns the 'default type' of the attribute. Default type in this case refers to the XML concept of a default type for an attribute, i.e. #FIXED, #IMPLIED, etc...
Returns
The default type enum for this attribute type.
getEnumeration() [1/3]
const XMLCh * XMLAttDef::getEnumeration () const inline
Get the enumeration value (if any) of this attribute type
If the attribute is of an enumeration or notation type, then this method will return a const reference to a string that contains the space separated values that can the attribute can have.
Returns
A const pointer to a string that contains the space separated legal values for this attribute.
Definition at line 457 of file XMLAttDef.hpp.
References fEnumeration.
getEnumeration() [2/3]
const XMLCh* XMLAttDef::getEnumeration () const
Get the enumeration value (if any) of this attribute type
If the attribute is of an enumeration or notation type, then this method will return a const reference to a string that contains the space separated values that can the attribute can have.
Returns
A const pointer to a string that contains the space separated legal values for this attribute.
getEnumeration() [3/3]
const XMLCh* XMLAttDef::getEnumeration () const
Get the enumeration value (if any) of this attribute type
If the attribute is of an enumeration or notation type, then this method will return a const reference to a string that contains the space separated values that can the attribute can have.
Returns
A const pointer to a string that contains the space separated legal values for this attribute.
getFullName() [1/3]
virtual const XMLCh* XMLAttDef::getFullName () const pure virtual
Get the full name of this attribute type
The derived class should return a const pointer to the full name of this attribute. This will vary depending on the type of validator in use.
Returns
A const pointer to the full name of this attribute type.
Implemented in SchemaAttDef, DTDAttDef, SchemaAttDef, DTDAttDef, SchemaAttDef, and DTDAttDef.
getFullName() [2/3]
virtual const XMLCh* XMLAttDef::getFullName () const pure virtual
Get the full name of this attribute type
The derived class should return a const pointer to the full name of this attribute. This will vary depending on the type of validator in use.
Returns
A const pointer to the full name of this attribute type.
Implemented in SchemaAttDef, DTDAttDef, SchemaAttDef, DTDAttDef, SchemaAttDef, and DTDAttDef.
getFullName() [3/3]
virtual const XMLCh* XMLAttDef::getFullName () const pure virtual
Get the full name of this attribute type
The derived class should return a const pointer to the full name of this attribute. This will vary depending on the type of validator in use.
Returns
A const pointer to the full name of this attribute type.
Implemented in SchemaAttDef, DTDAttDef, SchemaAttDef, DTDAttDef, SchemaAttDef, and DTDAttDef.
getId() [1/3]
XMLSize_t XMLAttDef::getId () const inline
Get the pool id of this attribute type
This method will return the id of this attribute in the validator's attribute pool. It was set by the validator when this attribute was created.
Returns
The pool id of this attribute type.
Definition at line 462 of file XMLAttDef.hpp.
References fId.
getId() [2/3]
XMLSize_t XMLAttDef::getId () const
Get the pool id of this attribute type
This method will return the id of this attribute in the validator's attribute pool. It was set by the validator when this attribute was created.
Returns
The pool id of this attribute type.
getId() [3/3]
XMLSize_t XMLAttDef::getId () const
Get the pool id of this attribute type
This method will return the id of this attribute in the validator's attribute pool. It was set by the validator when this attribute was created.
Returns
The pool id of this attribute type.
getMemoryManager() [1/3]
MemoryManager * XMLAttDef::getMemoryManager () const inline
Get the plugged-in memory manager
This method returns the plugged-in memory manager user for dynamic memory allocation/deallocation.
Returns
the plugged-in memory manager
Definition at line 487 of file XMLAttDef.hpp.
References fMemoryManager.
Referenced by SchemaAttDef::setNamespaceList().
getMemoryManager() [2/3]
MemoryManager* XMLAttDef::getMemoryManager () const
Get the plugged-in memory manager
This method returns the plugged-in memory manager user for dynamic memory allocation/deallocation.
Returns
the plugged-in memory manager
getMemoryManager() [3/3]
MemoryManager* XMLAttDef::getMemoryManager () const
Get the plugged-in memory manager
This method returns the plugged-in memory manager user for dynamic memory allocation/deallocation.
Returns
the plugged-in memory manager
getType() [1/3]
XMLAttDef::AttTypes XMLAttDef::getType () const inline
Get the type of this attribute
Gets the type of this attribute. This type is represented by an enum that converts the types of attributes allowed by XML, e.g. CDATA, NMTOKEN, NOTATION, etc...
Returns
The attribute type enumeration value for this type of attribute.
Definition at line 467 of file XMLAttDef.hpp.
References fType.
Referenced by TraverseSchema::copyWildCardData().
getType() [2/3]
AttTypes XMLAttDef::getType () const
Get the type of this attribute
Gets the type of this attribute. This type is represented by an enum that converts the types of attributes allowed by XML, e.g. CDATA, NMTOKEN, NOTATION, etc...
Returns
The attribute type enumeration value for this type of attribute.
getType() [3/3]
AttTypes XMLAttDef::getType () const
Get the type of this attribute
Gets the type of this attribute. This type is represented by an enum that converts the types of attributes allowed by XML, e.g. CDATA, NMTOKEN, NOTATION, etc...
Returns
The attribute type enumeration value for this type of attribute.
getValue() [1/3]
const XMLCh * XMLAttDef::getValue () const inline
Get the default/fixed value of this attribute (if any.)
If the attribute defined a default/fixed value, then it is stored and this method will retrieve it. If it has non, then a null pointer is returned.
Returns
A const pointer to the default/fixed value for this attribute type.
Definition at line 472 of file XMLAttDef.hpp.
References fValue.
getValue() [2/3]
const XMLCh* XMLAttDef::getValue () const
Get the default/fixed value of this attribute (if any.)
If the attribute defined a default/fixed value, then it is stored and this method will retrieve it. If it has non, then a null pointer is returned.
Returns
A const pointer to the default/fixed value for this attribute type.
getValue() [3/3]
const XMLCh* XMLAttDef::getValue () const
Get the default/fixed value of this attribute (if any.)
If the attribute defined a default/fixed value, then it is stored and this method will retrieve it. If it has non, then a null pointer is returned.
Returns
A const pointer to the default/fixed value for this attribute type.
isExternal() [1/3]
bool XMLAttDef::isExternal () const inline
Indicate whether this attribute has been declared externally
This method returns a boolean that indicates whether this attribute has been declared externally.
Returns
true if this attribute has been declared externally, else false.
Definition at line 482 of file XMLAttDef.hpp.
References fExternalAttribute.
isExternal() [2/3]
bool XMLAttDef::isExternal () const
Indicate whether this attribute has been declared externally
This method returns a boolean that indicates whether this attribute has been declared externally.
Returns
true if this attribute has been declared externally, else false.
isExternal() [3/3]
bool XMLAttDef::isExternal () const
Indicate whether this attribute has been declared externally
This method returns a boolean that indicates whether this attribute has been declared externally.
Returns
true if this attribute has been declared externally, else false.
operator=() [1/3]
XMLAttDef& XMLAttDef::operator= (const XMLAttDef &) private
operator=() [2/3]
XMLAttDef& XMLAttDef::operator= (const XMLAttDef &) private
operator=() [3/3]
XMLAttDef& XMLAttDef::operator= (const XMLAttDef &) private
reset() [1/3]
virtual void XMLAttDef::reset () pure virtual
The derived class should implement any cleaning up required between each use of an instance of this class for validation
Implemented in SchemaAttDef, DTDAttDef, SchemaAttDef, DTDAttDef, SchemaAttDef, and DTDAttDef.
reset() [2/3]
virtual void XMLAttDef::reset () pure virtual
The derived class should implement any cleaning up required between each use of an instance of this class for validation
Implemented in SchemaAttDef, DTDAttDef, SchemaAttDef, DTDAttDef, SchemaAttDef, and DTDAttDef.
reset() [3/3]
virtual void XMLAttDef::reset () pure virtual
The derived class should implement any cleaning up required between each use of an instance of this class for validation
Implemented in SchemaAttDef, DTDAttDef, SchemaAttDef, DTDAttDef, SchemaAttDef, and DTDAttDef.
setCreateReason() [1/3]
void XMLAttDef::setCreateReason (const CreateReasons newReason) inline
Update the create reason for this attribute type.
This method will update the 'create reason' field for this attribute decl object.
Parameters
newReason The new create reason.
Definition at line 527 of file XMLAttDef.hpp.
References fCreateReason.
setCreateReason() [2/3]
void XMLAttDef::setCreateReason (const CreateReasons newReason)
Update the create reason for this attribute type.
This method will update the 'create reason' field for this attribute decl object.
Parameters
newReason The new create reason.
setCreateReason() [3/3]
void XMLAttDef::setCreateReason (const CreateReasons newReason)
Update the create reason for this attribute type.
This method will update the 'create reason' field for this attribute decl object.
Parameters
newReason The new create reason.
setDefaultType() [1/3]
void XMLAttDef::setDefaultType (const XMLAttDef::DefAttTypes newValue) inline
Set the default attribute type
This method sets the default attribute type for this attribute. This setting controls whether the attribute is required, fixed, implied, etc...
Parameters
newValue The new default attribute to set
Definition at line 495 of file XMLAttDef.hpp.
References fDefaultType.
Referenced by TraverseSchema::copyWildCardData().
setDefaultType() [2/3]
void XMLAttDef::setDefaultType (const XMLAttDef::DefAttTypes newValue)
Set the default attribute type
This method sets the default attribute type for this attribute. This setting controls whether the attribute is required, fixed, implied, etc...
Parameters
newValue The new default attribute to set
setDefaultType() [3/3]
void XMLAttDef::setDefaultType (const XMLAttDef::DefAttTypes newValue)
Set the default attribute type
This method sets the default attribute type for this attribute. This setting controls whether the attribute is required, fixed, implied, etc...
Parameters
newValue The new default attribute to set
setEnumeration() [1/3]
void XMLAttDef::setEnumeration (const XMLCh *const newValue) inline
Set the enumerated value of this attribute type.
This method sets the enumerated/notation value list for this attribute type. It is a space separated set of possible values. These values must meet the constrains of the XML spec for such values of this type of attribute. This should only be set if the setType() method is used to set the type to the enumeration or notation types.
Parameters
newValue The new enumerated/notation value list to set.
Definition at line 500 of file XMLAttDef.hpp.
References MemoryManager::deallocate(), fEnumeration, fMemoryManager, and XMLString::replicate().
setEnumeration() [2/3]
void XMLAttDef::setEnumeration (const XMLCh *const newValue)
Set the enumerated value of this attribute type.
This method sets the enumerated/notation value list for this attribute type. It is a space separated set of possible values. These values must meet the constrains of the XML spec for such values of this type of attribute. This should only be set if the setType() method is used to set the type to the enumeration or notation types.
Parameters
newValue The new enumerated/notation value list to set.
setEnumeration() [3/3]
void XMLAttDef::setEnumeration (const XMLCh *const newValue)
Set the enumerated value of this attribute type.
This method sets the enumerated/notation value list for this attribute type. It is a space separated set of possible values. These values must meet the constrains of the XML spec for such values of this type of attribute. This should only be set if the setType() method is used to set the type to the enumeration or notation types.
Parameters
newValue The new enumerated/notation value list to set.
setExternalAttDeclaration() [1/3]
void XMLAttDef::setExternalAttDeclaration (const bool aValue) inline
Set the attribute decl to indicate external declaration
Parameters
aValue The new value to indicate external declaration.
Definition at line 532 of file XMLAttDef.hpp.
References fExternalAttribute.
setExternalAttDeclaration() [2/3]
void XMLAttDef::setExternalAttDeclaration (const bool aValue)
Set the attribute decl to indicate external declaration
Parameters
aValue The new value to indicate external declaration.
setExternalAttDeclaration() [3/3]
void XMLAttDef::setExternalAttDeclaration (const bool aValue)
Set the attribute decl to indicate external declaration
Parameters
aValue The new value to indicate external declaration.
setId() [1/3]
void XMLAttDef::setId (const XMLSize_t newId) inline
Set the pool id for this attribute type.
This method sets the pool id of this attribute type. This is usually called by the validator that creates the actual instance (which is of a derived type known only by the validator.)
Parameters
newId The new pool id to set.
Definition at line 508 of file XMLAttDef.hpp.
References fId.
setId() [2/3]
void XMLAttDef::setId (const XMLSize_t newId)
Set the pool id for this attribute type.
This method sets the pool id of this attribute type. This is usually called by the validator that creates the actual instance (which is of a derived type known only by the validator.)
Parameters
newId The new pool id to set.
setId() [3/3]
void XMLAttDef::setId (const XMLSize_t newId)
Set the pool id for this attribute type.
This method sets the pool id of this attribute type. This is usually called by the validator that creates the actual instance (which is of a derived type known only by the validator.)
Parameters
newId The new pool id to set.
setType() [1/3]
void XMLAttDef::setType (const XMLAttDef::AttTypes newValue) inline
Set the type of this attribute type.
This method will set the type of the attribute. The type of an attribute controls how it is normalized and what kinds of characters it can hold.
Parameters
newValue The new attribute type to set
Definition at line 513 of file XMLAttDef.hpp.
References fType.
Referenced by TraverseSchema::copyWildCardData().
setType() [2/3]
void XMLAttDef::setType (const XMLAttDef::AttTypes newValue)
Set the type of this attribute type.
This method will set the type of the attribute. The type of an attribute controls how it is normalized and what kinds of characters it can hold.
Parameters
newValue The new attribute type to set
setType() [3/3]
void XMLAttDef::setType (const XMLAttDef::AttTypes newValue)
Set the type of this attribute type.
This method will set the type of the attribute. The type of an attribute controls how it is normalized and what kinds of characters it can hold.
Parameters
newValue The new attribute type to set
setValue() [1/3]
void XMLAttDef::setValue (const XMLCh *const newValue) inline
Set the default/fixed value of this attribute type.
This method set the fixed/default value for the attribute. This value will be used when instances of this attribute type are faulted in. It must be a valid value for the type set by setType(). If the type is enumeration or notation, this must be one of the valid values set in the setEnumeration() call.
Parameters
newValue The new fixed/default value to set.
Definition at line 518 of file XMLAttDef.hpp.
References MemoryManager::deallocate(), fMemoryManager, fValue, and XMLString::replicate().
setValue() [2/3]
void XMLAttDef::setValue (const XMLCh *const newValue)
Set the default/fixed value of this attribute type.
This method set the fixed/default value for the attribute. This value will be used when instances of this attribute type are faulted in. It must be a valid value for the type set by setType(). If the type is enumeration or notation, this must be one of the valid values set in the setEnumeration() call.
Parameters
newValue The new fixed/default value to set.
setValue() [3/3]
void XMLAttDef::setValue (const XMLCh *const newValue)
Set the default/fixed value of this attribute type.
This method set the fixed/default value for the attribute. This value will be used when instances of this attribute type are faulted in. It must be a valid value for the type set by setType(). If the type is enumeration or notation, this must be one of the valid values set in the setEnumeration() call.
Parameters
newValue The new fixed/default value to set.
Member Data Documentation
fCreateReason
CreateReasons XMLAttDef::fCreateReason private
Definition at line 440 of file XMLAttDef.hpp.
Referenced by getCreateReason(), and setCreateReason().
fDefaultType
DefAttTypes XMLAttDef::fDefaultType private
Definition at line 438 of file XMLAttDef.hpp.
Referenced by getDefaultType(), and setDefaultType().
fEnumeration
XMLCh * XMLAttDef::fEnumeration private
Definition at line 444 of file XMLAttDef.hpp.
Referenced by getEnumeration(), and setEnumeration().
fExternalAttribute
bool XMLAttDef::fExternalAttribute private
Definition at line 441 of file XMLAttDef.hpp.
Referenced by isExternal(), and setExternalAttDeclaration().
fgInvalidAttrId
static const unsigned int XMLAttDef::fgInvalidAttrId static
Definition at line 121 of file XMLAttDef.hpp.
fId
XMLSize_t XMLAttDef::fId private
Definition at line 442 of file XMLAttDef.hpp.
Referenced by getId(), and setId().
fMemoryManager
MemoryManager * XMLAttDef::fMemoryManager private
Definition at line 445 of file XMLAttDef.hpp.
Referenced by getMemoryManager(), setEnumeration(), and setValue().
fType
AttTypes XMLAttDef::fType private
Definition at line 439 of file XMLAttDef.hpp.
Referenced by getType(), and setType().
fValue
XMLCh * XMLAttDef::fValue private
Definition at line 443 of file XMLAttDef.hpp.
Referenced by getValue(), and setValue().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/XMLAttDef.hpp