Seamly2D: AddPiece Class Reference
AddPiece Class Reference
#include <addpiece.h>
Public Member Functions
AddPiece (const QDomElement &xml, VAbstractPattern *doc, const VPiece &piece, const QString &blockName=QString(), QUndoCommand *parent=nullptr)
virtual ~AddPiece ()
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Member Functions
QDomElement getPiecesElement () const
Private Attributes
VPiece m_piece
QString m_blockName
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 67 of file addpiece.h.
Constructor & Destructor Documentation
AddPiece()
AddPiece::AddPiece (const QDomElement & xml, VAbstractPattern * doc, const VPiece & piece, const QString & blockName = QString(), QUndoCommand * parent = nullptr)
Definition at line 58 of file addpiece.cpp.
References VUndoCommand::doc, VDomDocument::getParameterId(), VUndoCommand::nodeId, and VUndoCommand::xml.
~AddPiece()
AddPiece::~AddPiece () virtual
Definition at line 69 of file addpiece.cpp.
Member Function Documentation
getPiecesElement()
QDomElement AddPiece::getPiecesElement () const private
Definition at line 127 of file addpiece.cpp.
References VUndoCommand::doc, VAbstractPattern::getActiveNodeElement(), VAbstractPattern::getDraftBlockElement(), m_blockName, and VAbstractPattern::TagPieces.
Referenced by redo(), and undo().
redo()
void AddPiece::redo () virtual
Definition at line 109 of file addpiece.cpp.
References getPiecesElement(), VUndoCommand::RedoFullParsing(), VAbstractPattern::TagPieces, and VUndoCommand::xml.
undo()
void AddPiece::undo () virtual
Definition at line 73 of file addpiece.cpp.
References VUndoCommand::DecrementReferences(), VUndoCommand::doc, VDomDocument::elementById(), VPiece::getAnchors(), VPiece::GetCustomSARecords(), VPiece::GetInternalPaths(), VPiecePath::GetNodes(), VPiece::GetPath(), getPiecesElement(), m_piece, VUndoCommand::NeedFullParsing(), VUndoCommand::nodeId, VAbstractPattern::TagPiece, and VAbstractPattern::TagPieces.
Member Data Documentation
m_blockName
QString AddPiece::m_blockName private
Definition at line 81 of file addpiece.h.
Referenced by getPiecesElement().
m_piece
VPiece AddPiece::m_piece private
Definition at line 80 of file addpiece.h.
Referenced by undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/addpiece.h
src/libs/vtools/undocommands/addpiece.cpp