Seamly2D: SaveToolOptions Class Reference
SaveToolOptions Class Reference
#include <savetooloptions.h>
Public Member Functions
SaveToolOptions (const QDomElement &oldXml, const QDomElement &newXml, VAbstractPattern *doc, const quint32 &id, QUndoCommand *parent=nullptr)
virtual ~SaveToolOptions () Q_DECL_OVERRIDE
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
virtual bool mergeWith (const QUndoCommand *command) Q_DECL_OVERRIDE
virtual int id () const Q_DECL_OVERRIDE
QDomElement getNewXml () const
quint32 getToolId () const
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Attributes
const QDomElement oldXml
QDomElement newXml
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 64 of file savetooloptions.h.
Constructor & Destructor Documentation
SaveToolOptions()
SaveToolOptions::SaveToolOptions (const QDomElement & oldXml, const QDomElement & newXml, VAbstractPattern * doc, const quint32 & id, QUndoCommand * parent = nullptr)
Definition at line 62 of file savetooloptions.cpp.
References id(), and VUndoCommand::nodeId.
~SaveToolOptions()
SaveToolOptions::~SaveToolOptions () virtual
Definition at line 71 of file savetooloptions.cpp.
Member Function Documentation
getNewXml()
QDomElement SaveToolOptions::getNewXml () const inline
Definition at line 84 of file savetooloptions.h.
References newXml.
Referenced by mergeWith().
getToolId()
quint32 SaveToolOptions::getToolId () const inline
Definition at line 90 of file savetooloptions.h.
References VUndoCommand::nodeId.
Referenced by mergeWith().
id()
int SaveToolOptions::id () const virtual
Definition at line 129 of file savetooloptions.cpp.
References SaveToolOptions.
Referenced by SaveToolOptions().
mergeWith()
bool SaveToolOptions::mergeWith (const QUndoCommand * command) virtual
Definition at line 113 of file savetooloptions.cpp.
References getNewXml(), getToolId(), newXml, VUndoCommand::nodeId, and SCASSERT.
redo()
void SaveToolOptions::redo () virtual
Definition at line 94 of file savetooloptions.cpp.
References VUndoCommand::doc, VDomDocument::elementById(), LiteParse, VUndoCommand::NeedLiteParsing(), newXml, and VUndoCommand::nodeId.
undo()
void SaveToolOptions::undo () virtual
Definition at line 75 of file savetooloptions.cpp.
References VUndoCommand::doc, VDomDocument::elementById(), LiteParse, VUndoCommand::NeedLiteParsing(), VUndoCommand::nodeId, and oldXml.
Member Data Documentation
newXml
QDomElement SaveToolOptions::newXml private
Definition at line 80 of file savetooloptions.h.
Referenced by getNewXml(), mergeWith(), and redo().
oldXml
const QDomElement SaveToolOptions::oldXml private
Definition at line 79 of file savetooloptions.h.
Referenced by undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/savetooloptions.h
src/libs/vtools/undocommands/savetooloptions.cpp