Seamly2D: PreferencesConfigurationPage Class Reference
PreferencesConfigurationPage Class Reference
#include <preferencesconfigurationpage.h>
Public Member Functions
PreferencesConfigurationPage (QWidget *parent=nullptr)
virtual ~PreferencesConfigurationPage ()
void Apply ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
Private Member Functions
void SetLabelComboBox (const QStringList &list)
void InitUnits ()
void RetranslateUi ()
Private Attributes
Ui::PreferencesConfigurationPage * ui
bool m_langChanged
bool m_systemChanged
bool m_unitChanged
bool m_labelLangChanged
bool m_selectionSoundChanged
bool m_moveSuffixChanged
bool m_rotateSuffixChanged
bool m_mirrorByAxisSuffixChanged
bool m_mirrorByLineSuffixChanged
bool m_defaultExportFormatChanged
Detailed Description
Definition at line 62 of file preferencesconfigurationpage.h.
Constructor & Destructor Documentation
PreferencesConfigurationPage()
PreferencesConfigurationPage::PreferencesConfigurationPage (QWidget * parent = nullptr) explicit
Definition at line 65 of file preferencesconfigurationpage.cpp.
References InitLanguages(), InitPMSystems(), InitUnits(), VApplication::LabelLanguages(), qApp, SetLabelComboBox(), and ui.
~PreferencesConfigurationPage()
PreferencesConfigurationPage::~PreferencesConfigurationPage () virtual
Definition at line 236 of file preferencesconfigurationpage.cpp.
References ui.
Member Function Documentation
Apply()
void PreferencesConfigurationPage::Apply ()
Definition at line 242 of file preferencesconfigurationpage.cpp.
References m_defaultExportFormatChanged, m_labelLangChanged, m_langChanged, m_mirrorByAxisSuffixChanged, m_mirrorByLineSuffixChanged, m_moveSuffixChanged, m_rotateSuffixChanged, m_selectionSoundChanged, m_systemChanged, m_unitChanged, qApp, SCASSERT, VCommonSettings::setAutosaveInterval(), VCommonSettings::SetAutosaveState(), VCommonSettings::setConfirmFormatRewriting(), VCommonSettings::setConfirmItemDelete(), VCommonSettings::setExportFormat(), VSettings::SetLabelLanguage(), VCommonSettings::SetLocale(), VCommonSettings::setMirrorByAxisSuffix(), VCommonSettings::setMirrorByLineSuffix(), VCommonSettings::setMoveSuffix(), VCommonSettings::SetOsSeparator(), VCommonSettings::SetPMSystemCode(), VCommonSettings::setRotateSuffix(), VCommonSettings::setSelectionSound(), VCommonSettings::SetUndoCount(), VCommonSettings::SetUnit(), VCommonSettings::setUseLastExportFormat(), VCommonSettings::setUseModeType(), and ui.
Referenced by DialogPreferences::Apply().
changeEvent()
void PreferencesConfigurationPage::changeEvent (QEvent * event) protected virtual
Definition at line 332 of file preferencesconfigurationpage.cpp.
References RetranslateUi().
InitUnits()
void PreferencesConfigurationPage::InitUnits () private
Definition at line 356 of file preferencesconfigurationpage.cpp.
References qApp, ui, unitCM, unitINCH, and unitMM.
Referenced by PreferencesConfigurationPage().
RetranslateUi()
void PreferencesConfigurationPage::RetranslateUi () private
Definition at line 371 of file preferencesconfigurationpage.cpp.
References ui.
Referenced by changeEvent().
SetLabelComboBox()
void PreferencesConfigurationPage::SetLabelComboBox (const QStringList & list) private
Definition at line 344 of file preferencesconfigurationpage.cpp.
References ui.
Referenced by PreferencesConfigurationPage().
Member Data Documentation
m_defaultExportFormatChanged
bool PreferencesConfigurationPage::m_defaultExportFormatChanged private
Definition at line 87 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_labelLangChanged
bool PreferencesConfigurationPage::m_labelLangChanged private
Definition at line 81 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_langChanged
bool PreferencesConfigurationPage::m_langChanged private
Definition at line 78 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_mirrorByAxisSuffixChanged
bool PreferencesConfigurationPage::m_mirrorByAxisSuffixChanged private
Definition at line 85 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_mirrorByLineSuffixChanged
bool PreferencesConfigurationPage::m_mirrorByLineSuffixChanged private
Definition at line 86 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_moveSuffixChanged
bool PreferencesConfigurationPage::m_moveSuffixChanged private
Definition at line 83 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_rotateSuffixChanged
bool PreferencesConfigurationPage::m_rotateSuffixChanged private
Definition at line 84 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_selectionSoundChanged
bool PreferencesConfigurationPage::m_selectionSoundChanged private
Definition at line 82 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_systemChanged
bool PreferencesConfigurationPage::m_systemChanged private
Definition at line 79 of file preferencesconfigurationpage.h.
Referenced by Apply().
m_unitChanged
bool PreferencesConfigurationPage::m_unitChanged private
Definition at line 80 of file preferencesconfigurationpage.h.
Referenced by Apply().
ui
Ui::PreferencesConfigurationPage* PreferencesConfigurationPage::ui private
Definition at line 77 of file preferencesconfigurationpage.h.
Referenced by Apply(), InitUnits(), PreferencesConfigurationPage(), RetranslateUi(), SetLabelComboBox(), and ~PreferencesConfigurationPage().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/configpages/preferencesconfigurationpage.h
src/app/seamly2d/dialogs/configpages/preferencesconfigurationpage.cpp