Seamly2D: VisToolTrueDarts Class Reference
VisToolTrueDarts Class Reference
#include <vistooltruedarts.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolTrueDarts) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolTrueDarts (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolTrueDarts ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setObject2Id (const quint32 &value)
void setD1PointId (const quint32 &value)
void setD2PointId (const quint32 &value)
void setD3PointId (const quint32 &value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Attributes
quint32 baseLineP2Id
quint32 dartP1Id
quint32 dartP2Id
quint32 dartP3Id
VScaledEllipse * point1
VScaledEllipse * point2
VScaledEllipse * baseLineP1
VScaledEllipse * baseLineP2
VScaledEllipse * dartP1
VScaledEllipse * dartP2
VScaledEllipse * dartP3
VScaledLine * lineblP1P1
VScaledLine * lineblP2P2
VScaledLine * p1d2
VScaledLine * d2p2
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 65 of file vistooltruedarts.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 80 of file vistooltruedarts.h.
Constructor & Destructor Documentation
VisToolTrueDarts()
VisToolTrueDarts::VisToolTrueDarts (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 69 of file vistooltruedarts.cpp.
References baseLineP1, baseLineP2, d2p2, dartP1, dartP2, dartP3, Visualization::InitPoint(), lineblP1P1, lineblP2P2, Visualization::mainColor, p1d2, point1, point2, and Visualization::supportColor.
~VisToolTrueDarts()
virtual VisToolTrueDarts::~VisToolTrueDarts () virtual default
Member Function Documentation
RefreshGeometry()
void VisToolTrueDarts::RefreshGeometry () virtual
Implements Visualization.
Definition at line 103 of file vistooltruedarts.cpp.
References baseLineP1, baseLineP2, baseLineP2Id, d2p2, dartP1, dartP1Id, dartP2, dartP2Id, dartP3, dartP3Id, Visualization::data, Visualization::DrawLine(), Visualization::DrawPoint(), VToolTrueDarts::FindPoint(), VContainer::GeometricObject(), lineblP1P1, lineblP2P2, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, p1d2, point1, point2, Visualization::scenePos, and Visualization::supportColor.
Referenced by DialogTrueDarts::ChosenObject(), DialogTrueDarts::SaveData(), and VToolTrueDarts::SetVisualization().
setD1PointId()
void VisToolTrueDarts::setD1PointId (const quint32 & value)
Definition at line 178 of file vistooltruedarts.cpp.
References dartP1Id.
Referenced by DialogTrueDarts::ChosenObject(), DialogTrueDarts::SaveData(), DialogTrueDarts::SetFirstDartPointId(), and VToolTrueDarts::SetVisualization().
setD2PointId()
void VisToolTrueDarts::setD2PointId (const quint32 & value)
Definition at line 184 of file vistooltruedarts.cpp.
References dartP2Id.
Referenced by DialogTrueDarts::ChosenObject(), DialogTrueDarts::SaveData(), DialogTrueDarts::SetSecondDartPointId(), and VToolTrueDarts::SetVisualization().
setD3PointId()
void VisToolTrueDarts::setD3PointId (const quint32 & value)
Definition at line 190 of file vistooltruedarts.cpp.
References dartP3Id.
Referenced by DialogTrueDarts::ChosenObject(), DialogTrueDarts::SaveData(), DialogTrueDarts::SetThirdDartPointId(), and VToolTrueDarts::SetVisualization().
setObject2Id()
void VisToolTrueDarts::setObject2Id (const quint32 & value)
Definition at line 172 of file vistooltruedarts.cpp.
References baseLineP2Id.
Referenced by DialogTrueDarts::ChosenObject(), DialogTrueDarts::SaveData(), DialogTrueDarts::SetSecondBasePointId(), and VToolTrueDarts::SetVisualization().
type()
virtual int VisToolTrueDarts::type () const inline virtual
Reimplemented from VisLine.
Definition at line 79 of file vistooltruedarts.h.
References Type.
Member Data Documentation
baseLineP1
VScaledEllipse* VisToolTrueDarts::baseLineP1 private
Definition at line 90 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
baseLineP2
VScaledEllipse* VisToolTrueDarts::baseLineP2 private
Definition at line 91 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
baseLineP2Id
quint32 VisToolTrueDarts::baseLineP2Id private
Definition at line 83 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and setObject2Id().
d2p2
VScaledLine* VisToolTrueDarts::d2p2 private
Definition at line 99 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
dartP1
VScaledEllipse* VisToolTrueDarts::dartP1 private
Definition at line 92 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
dartP1Id
quint32 VisToolTrueDarts::dartP1Id private
Definition at line 84 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and setD1PointId().
dartP2
VScaledEllipse* VisToolTrueDarts::dartP2 private
Definition at line 93 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
dartP2Id
quint32 VisToolTrueDarts::dartP2Id private
Definition at line 85 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and setD2PointId().
dartP3
VScaledEllipse* VisToolTrueDarts::dartP3 private
Definition at line 94 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
dartP3Id
quint32 VisToolTrueDarts::dartP3Id private
Definition at line 86 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and setD3PointId().
lineblP1P1
VScaledLine* VisToolTrueDarts::lineblP1P1 private
Definition at line 96 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
lineblP2P2
VScaledLine* VisToolTrueDarts::lineblP2P2 private
Definition at line 97 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
p1d2
VScaledLine* VisToolTrueDarts::p1d2 private
Definition at line 98 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
point1
VScaledEllipse* VisToolTrueDarts::point1 private
Definition at line 88 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
point2
VScaledEllipse* VisToolTrueDarts::point2 private
Definition at line 89 of file vistooltruedarts.h.
Referenced by RefreshGeometry(), and VisToolTrueDarts().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/vistooltruedarts.h
src/libs/vtools/visualization/line/vistooltruedarts.cpp