Seamly2D: MainWindow Class Reference
MainWindow Class Reference
The MainWindow class main windows.
#include <mainwindow.h>
Public Slots
void ProcessCMD ()
void penChanged (Pen pen)
virtual void ShowToolTip (const QString &toolTip) Q_DECL_OVERRIDE
ShowTool highlight tool.Tip show tools tooltip.
virtual void updateGroups () Q_DECL_OVERRIDE
triggers the update of the groups
virtual void zoomToSelected () Q_DECL_OVERRIDE
void showAllGroups ()
void hideAllGroups ()
void lockAllGroups ()
void unlockAllGroups ()
void addGroupToList ()
void deleteGroupFromList ()
void editGroup ()
void addSelectedItemsToGroup ()
Public Slots inherited from MainWindowsNoGUI
void toolLayoutSettings (QToolButton *tButton, bool checked)
void PrintPreviewOrigin ()
void PrintPreviewTiled ()
void PrintOrigin ()
void PrintTiled ()
void refreshLabels ()
refreshLabels call to recalculate piece labels. For example after changing a font.
void refreshGrainLines ()
refreshGrainLines call to recalculate piece grainlines. For example after show / hide grainlines.
void refreshSeamAllowances ()
refreshSeamAllowances call to show / hide seam allowances.
void exportSVG (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene) const
exportSVG save layout to svg file.
void exportPNG (const QString &name, QGraphicsScene *scene) const
exportPNG save layout to png file.
void exportTIF (const QString &name, QGraphicsScene *scene) const
exportTIF save layout to tif file.
void exportJPG (const QString &name, QGraphicsScene *scene) const
exportJPG save layout to jpg file.
void exportBMP (const QString &name, QGraphicsScene *scene) const
exportBMP save layout to bmp file.
void exportPPM (const QString &name, QGraphicsScene *scene) const
exportPPM save layout to gif file.
void exportPDF (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene, bool ignoreMargins, const QMarginsF &margins) const
exportPDF save layout to pdf file.
void exportEPS (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene, bool ignoreMargins, const QMarginsF &margins) const
exportEPS(save layout to eps file.
void exportPS (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene, bool ignoreMargins, const QMarginsF &margins) const
exportPS save layout to ps file.
Public Slots inherited from VAbstractMainWindow
virtual void ShowToolTip (const QString &toolTip)=0
virtual void updateGroups ()=0
virtual void zoomToSelected ()=0
Signals
void RefreshHistory ()
void EnableItemMove (bool move)
void ItemsSelection (SelectionType type) const
void EnableLabelSelection (bool enable) const
void EnablePointSelection (bool enable) const
void EnableLineSelection (bool enable) const
void EnableArcSelection (bool enable) const
void EnableElArcSelection (bool enable) const
void EnableSplineSelection (bool enable) const
void EnableSplinePathSelection (bool enable) const
void EnableNodeLabelSelection (bool enable) const
void EnableNodePointSelection (bool enable) const
void enablePieceSelection (bool enable) const
void EnableLabelHover (bool enable) const
void EnablePointHover (bool enable) const
void EnableLineHover (bool enable) const
void EnableArcHover (bool enable) const
void EnableElArcHover (bool enable) const
void EnableSplineHover (bool enable) const
void EnableSplinePathHover (bool enable) const
void EnableNodeLabelHover (bool enable) const
void EnableNodePointHover (bool enable) const
void enablePieceHover (bool enable) const
void signalZoomToAreaActive (bool enable) const
void signalZoomPanActive (bool enable) const
Public Member Functions
MainWindow (QWidget *parent=nullptr)
MainWindow constructor.
virtual ~MainWindow () Q_DECL_OVERRIDE
bool LoadPattern (const QString &fileName, const QString &customMeasureFile=QString())
LoadPattern open pattern file.
Public Member Functions inherited from MainWindowsNoGUI
MainWindowsNoGUI (QWidget *parent=nullptr)
virtual ~MainWindowsNoGUI () Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractMainWindow
VAbstractMainWindow (QWidget *parent=nullptr)
virtual ~VAbstractMainWindow () Q_DECL_EQ_DEFAULT
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyPressEvent handle key press events.
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyReleaseEvent handle key press events.
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle after show window.
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle after close window.
virtual void customEvent (QEvent *event) Q_DECL_OVERRIDE
virtual void CleanLayout () Q_DECL_OVERRIDE
virtual void PrepareSceneList () Q_DECL_OVERRIDE
virtual void exportToCSVData (const QString &fileName, const DialogExportToCSV &dialog) Q_DECL_FINAL
void handleExportToCSV ()
Protected Member Functions inherited from MainWindowsNoGUI
void ExportData (const QVector< VLayoutPiece > &pieceList, const ExportLayoutDialog &dialog)
void InitTempLayoutScene ()
QIcon ScenePreview (int i) const
bool LayoutSettings (VLayoutGenerator &lGenerator)
int ContinueIfLayoutStale ()
QString FileName () const
void SetSizeHeightForIndividualM () const
Protected Member Functions inherited from VAbstractMainWindow
bool ContinueFormatRewrite (const QString &currentFormatVersion, const QString &maxFormatVersion)
void ToolBarStyle (QToolBar *bar)
Private Types
enum { MaxRecentFiles = 5 }
drawMode true if draft scene active.
Private Slots
void zoomScaleChanged (qreal scale)
void MouseMove (const QPointF &scenePos)
mouseMove save mouse position and show user.
void Clear ()
Clear reset to default window.
void patternChangesWereSaved (bool saved)
haveChange enable action save if we have unsaved change.
void LastUsedTool ()
void fullParseFile ()
void setGuiEnabled (bool enabled)
void changeDraftBlockGlobally (const QString &patternPiece)
void ToolBarStyles ()
void resetOrigins ()
void showLayoutPages (int index)
void Preferences ()
void exportLayoutAs ()
void exportPiecesAs ()
void exportDraftBlocksAs ()
void handleArrowTool (bool checked)
handleArrowTool enable arrow tool.
void handlePointAtDistanceAngleTool (bool checked)
handlePointAtDistanceAngleTool handler for handlePointAtDistanceAngle tool.
void handleAlongLineTool (bool checked)
handleAlongLineTool handler for point along Line tools.
void handleMidpointTool (bool checked)
void handleShoulderPointTool (bool checked)
handleShoulderPointTool handler for shoulderPoint tool.
void handleNormalTool (bool checked)
handleNormalTool handler point on perpendicular tool.
void handleBisectorTool (bool checked)
handleBisectorTool handler for bisector tool.
void handleHeightTool (bool checked)
handleHeightTool handler tool height.
void handleTriangleTool (bool checked)
handleTriangleTool handler Point - Intersect Axis and Triangle.
void handleLineIntersectAxisTool (bool checked)
void handlePointOfContactTool (bool checked)
handlePointOfContactTool handler for pointOfContact tool.
void handlePointIntersectXYTool (bool checked)
handlePointIntersectXYTool handler for pointOfIntersection tool.
void handleLineTool (bool checked)
handleLineTool handler for line tool.
void handleLineIntersectTool (bool checked)
handleLineIntersectTool handler for lineIntersect tool.
void handleCurveTool (bool checked)
handleCurveTool handler for curve tool.
void handleSplineTool (bool checked)
handleSplineTool handler for spline tool.
void handleCurveWithControlPointsTool (bool checked)
void handleSplineWithControlPointsTool (bool checked)
void handlePointAlongCurveTool (bool checked)
handlePointAlongCurveTool handler for point along curve tool.
void handlePointAlongSplineTool (bool checked)
handlePointAlongSplineTool handler for point along spline tool.
void handleCurveIntersectCurveTool (bool checked)
void handleCurveIntersectAxisTool (bool checked)
void handleArcTool (bool checked)
handleArcTool handler for arc tool.
void handlePointAlongArcTool (bool checked)
handlePointAlongArcTool handler for PointAlongArc tool.
void handlePointFromArcAndTangentTool (bool checked)
void handleArcWithLengthTool (bool checked)
void handleArcIntersectAxisTool (bool checked)
void handlePointOfIntersectionArcsTool (bool checked)
void handlePointOfIntersectionCirclesTool (bool checked)
void handlePointFromCircleAndTangentTool (bool checked)
void handleEllipticalArcTool (bool checked)
handleEllipticalArcTool handler for EllipticalArc tool.
void handleGroupTool (bool checked)
void handleRotationTool (bool checked)
void handleMirrorByLineTool (bool checked)
void handleMirrorByAxisTool (bool checked)
void handleMoveTool (bool checked)
void handleTrueDartTool (bool checked)
void handleInternalPathTool (bool checked)
void handleAnchorPointTool (bool checked)
void handleInsertNodesTool (bool checked)
void handlePatternPieceTool (bool checked)
handlePatternPieceTool handler for pattern piece tool.
void handleUnionTool (bool checked)
handleUnionTool handler for Union tool.
void handleNewLayout (bool checked)
handleNewLayout handler for New Layout tool.
void showDraftMode (bool checked)
showDraftMode show draw scene.
void showPieceMode (bool checked)
showPieceMode show Piece scene.
void showLayoutMode (bool checked)
showLayoutMode show layout scene.
void New ()
NewPattern create new empty pattern.
bool SaveAs ()
SaveAs save as pattern file.
bool Save ()
Save save pattern file.
void Open ()
Open ask user select pattern file.
void closeUnionDialog (int result)
closeUnionDialog actions after closing Union tool dialog.
void ClosedEditGroupDialog (int result)
void ClosedDialogInternalPath (int result)
void ClosedDialogAnchorPoint (int result)
void ClosedInsertNodesDialog (int result)
void zoomToPrevious ()
void zoomToArea (bool checked)
void zoomPan (bool checked)
void zoomToPoint (const QString &pointName)
zoomToPoint show dialog for choosing a point and update the graphics view to focus on it.
void showZoomToPointDialog ()
zoomToPoint show dialog for choosing a point and update the graphics view to focus on it.
void LoadIndividual ()
void LoadMultisize ()
void UnloadMeasurements ()
void ShowMeasurements ()
void MeasurementsChanged (const QString &path)
void SyncMeasurements ()
void ChangedSize (int index)
ChangedSize change new size value.
void ChangedHeight (int index)
ChangedGrowth change new height value.
Private Member Functions
void SetDefaultHeight ()
void SetDefaultSize ()
void initStatusBar ()
initStatusBar initialize horizontal bar for presenting status information
void initModesToolBar ()
void initDraftToolBar ()
initDraftToolBar enable draw toolbar.
void initPointNameToolBar ()
initPointNameToolBar enable Point Name toolbar.
void initToolsToolBar ()
void initToolBarVisibility ()
void initPenToolBar ()
initPenToolBar enable default color, line wight & type toolbar.
void updateToolBarVisibility ()
void setToolBarVisibility (QToolBar *toolbar, bool visible)
void InitToolButtons ()
void handlePointsMenu ()
void handleLinesMenu ()
void handleArcsMenu ()
void handleCurvesMenu ()
void handleCirclesMenu ()
void handleOperationsMenu ()
void handlePatternPiecesMenu ()
void handlePieceMenu ()
void handleLayoutMenu ()
void handleImagesMenu ()
void CancelTool ()
CancelTool cancel tool.
void setWidgetsEnabled (bool enable)
setWidgetsEnabled enable action button.
void setToolsEnabled (bool enable)
setToolsEnabled enable button.
void SetLayoutModeActions ()
void SaveCurrentScene ()
SaveCurrentScene save scene options before set another.
void RestoreCurrentScene ()
RestoreCurrentScene restore scene options after change.
void MinimumScrollBar ()
MinimumScrollBar set scroll bar to minimum.
template<typename Dialog , typename Func >
void SetToolButton (bool checked, Tool t, const QString &cursor, const QString &toolTip, Func closeDialogSlot)
SetToolButton set tool and show dialog.
template<typename Dialog , typename Func , typename Func2 >
void SetToolButtonWithApply (bool checked, Tool t, const QString &cursor, const QString &toolTip, Func closeDialogSlot, Func2 applyDialogSlot)
SetToolButtonWithApply set tool and show dialog.
template<typename DrawTool >
void ClosedDialog (int result)
ClosedDialog handle close dialog.
template<typename DrawTool >
void ClosedDialogWithApply (int result, VMainGraphicsScene *scene)
ClosedDialogWithApply handle close dialog that has apply button.
template<typename DrawTool >
void ApplyDialog (VMainGraphicsScene *scene)
ApplyDialog handle apply in dialog.
template<typename DrawTool >
void ClosedDrawDialogWithApply (int result)
template<typename DrawTool >
void ApplyDrawDialog ()
template<typename DrawTool >
void ClosedPiecesDialogWithApply (int result)
template<typename DrawTool >
void applyPiecesDialog ()
bool SavePattern (const QString &fileName, QString &error)
SavePattern save pattern file.
void AutoSavePattern ()
AutoSavePattern start safe saving.
void setCurrentFile (const QString &fileName)
setCurrentFile the function is called to reset the state of a few variables when a file is loaded or saved, or when the user starts editing a new file (in which case fileName is empty).
void ReadSettings ()
ReadSettings read setting for app.
void WriteSettings ()
WriteSettings save setting for app.
bool MaybeSave ()
MaybeSave The function is called to save pending changes.
void UpdateRecentFileActions ()
void CreateMenus ()
void CreateActions ()
void InitAutoSave ()
QString createDraftBlockName (const QString &text)
QString CheckPathToMeasurements (const QString &patternPath, const QString &path)
QComboBox * SetGradationList (QLabel *label, const QStringList &list)
void changeDraftBlock (int index, bool zoomBestFit=true)
void EndVisualization (bool click=false)
EndVisualization try show dialog after and working with tool visualization.
void zoomFirstShow ()
zoomFirstShow Fit scene size to best size for first show
void UpdateHeightsList (const QStringList &list)
void UpdateSizesList (const QStringList &list)
void AddDocks ()
void InitDocksContain ()
bool OpenNewSeamly2D (const QString &fileName=QString()) const
void FileClosedCorrect ()
QStringList GetUnlokedRestoreFileList () const
void addDraftBlock (const QString &blockName)
QPointF draftBlockStartPosition () const
void InitScenes ()
QSharedPointer< VMeasurements > OpenMeasurementFile (const QString &path)
bool LoadMeasurements (const QString &path)
bool UpdateMeasurements (const QString &path, int size, int height)
void CheckRequiredMeasurements (const VMeasurements *m)
void ReopenFilesAfterCrash (QStringList &args)
void DoExport (const VCommandLinePtr &expParams)
bool SetSize (const QString &text)
bool SetHeight (const QString &text)
QString GetPatternFileName ()
QString GetMeasurementFileName ()
void UpdateWindowTitle ()
void upDateScenes ()
void updateViewToolbar ()
void resetPanShortcuts ()
QStringList draftPointNamesList ()
draftPointNamesList gets the list of points in draft mode.
void updateZoomToPointComboBox (QStringList namesList)
updateZoomToPointComboBox updates the list of points included in the toolbar combobox.
bool IgnoreLocking (int error, const QString &path)
void ToolSelectPoint () const
void ToolSelectPointByPress () const
void ToolSelectPointByRelease () const
void ToolSelectSpline () const
void ToolSelectSplinePath () const
void ToolSelectArc () const
void ToolSelectPointArc () const
void ToolSelectCurve () const
void selectAllDraftObjectsTool () const
void ToolSelectOperationObjects () const
void ToolSelectGroupObjects () const
void selectPieceTool () const
Private Attributes
Ui::MainWindow * ui
ui keeps information about user interface
QFileSystemWatcher * watcher
Tool currentTool
tool current tool
Tool lastUsedTool
tool last used tool
VMainGraphicsScene * draftScene
draftScene draft block scene.
VMainGraphicsScene * pieceScene
pieceScene pattern piece scene.
QPointer< MouseCoordinates > mouseCoordinates
mouseCoordinates pointer to label who show mouse coordinate.
QPointer< QToolButton > infoToolButton
QLabel * helpLabel
helpLabel help show tooltip.
bool isInitialized
isInitialized true after first show window.
bool mChanges
mChanges true if measurement file was changed.
bool mChangesAsked
bool patternReadOnly
QPointer< DialogVariables > dialogTable
QSharedPointer< DialogTool > dialogTool
QPointer< HistoryDialog > historyDialog
QFontComboBox * fontComboBox
QComboBox * fontSizeComboBox
QComboBox * draftBlockComboBox
QLabel * draftBlockLabel
draftBlockComboBox stores names of draft blocks.
Draw mode
qint32 currentBlockIndex
mode stores current draw mode.
qint32 currentToolBoxIndex
currentBlockIndex current selected draft block.
bool isToolOptionsDockVisible
currentToolBoxIndex current set of tools.
bool isGroupsDockVisible
bool isLayoutsDockVisible
bool isToolboxDockVisible
bool drawMode
QAction * recentFileActs [MaxRecentFiles]
QAction * separatorAct
QLabel * leftGoToStage
QLabel * rightGoToStage
QTimer * autoSaveTimer
bool guiEnabled
QPointer< QComboBox > gradationHeights
QPointer< QComboBox > gradationSizes
QPointer< QLabel > gradationHeightsLabel
QPointer< QLabel > gradationSizesLabel
VToolOptionsPropertyBrowser * toolProperties
GroupsWidget * groupsWidget
PiecesWidget * patternPiecesWidget
std::shared_ptr< VLockGuard< char > > lock
QDoubleSpinBox * zoomScaleSpinBox
PenToolBar * m_penToolBar
for selecting the current pen
PenToolBar * m_penReset
QComboBox * m_zoomToPointComboBox
Additional Inherited Members
Protected Slots inherited from VAbstractMainWindow
void WindowsLocale ()
void exportToCSV (QString &file)
Static Protected Member Functions inherited from MainWindowsNoGUI
static QVector< VLayoutPiece > preparePiecesForLayout (const QHash< quint32, VPiece > &pieces)
Protected Attributes inherited from MainWindowsNoGUI
QVector< VLayoutPiece > pieceList
QGraphicsScene * currentScene
QGraphicsScene * tempSceneLayout
currentScene pointer to current scene.
VContainer * pattern
pattern container with data (points, arcs, splines, spline paths, variables)
VPattern * doc
pattern container with data (points, arcs, splines, spline paths, variables)
QList< QGraphicsItem * > papers
doc dom document container
QList< QGraphicsItem * > shadows
QList< QGraphicsScene * > scenes
QList< QList< QGraphicsItem * > > pieces
QVector< QVector< VLayoutPiece > > piecesOnLayout
QAction * undoAction
QAction * redoAction
QAction * actionDockWidgetToolOptions
QAction * actionDockWidgetGroups
QAction * actionDockWidgetLayouts
QAction * actionDockWidgetToolbox
bool isNoScaling
bool isLayoutStale
bool ignoreMargins
QMarginsF margins
QSizeF paperSize
Protected Attributes inherited from VAbstractMainWindow
int m_curFileFormatVersion
QString m_curFileFormatVersionStr
Detailed Description
The MainWindow class main windows.
Definition at line 86 of file mainwindow.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
drawMode true if draft scene active.
Enumerator
MaxRecentFiles
Definition at line 313 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr) explicit
MainWindow constructor.
Parameters
parent parent widget.
Definition at line 134 of file mainwindow.cpp.
References VAbstractPattern::CheckLayout(), Clear(), VAbstractPattern::ClearMainWindow(), fullParseFile(), VAbstractPattern::patternChanged(), patternChangesWereSaved(), setGuiEnabled(), VAbstractPattern::setGuiEnabled(), and VAbstractPattern::UndoCommand().
~MainWindow()
MainWindow::~MainWindow () virtual
Definition at line 5989 of file mainwindow.cpp.
References CancelTool(), CleanLayout(), MainWindowsNoGUI::doc, and ui.
Member Function Documentation
AddDocks()
QT_WARNING_POP void MainWindow::AddDocks () private
Definition at line 5238 of file mainwindow.cpp.
References MainWindowsNoGUI::actionDockWidgetGroups, MainWindowsNoGUI::actionDockWidgetLayouts, MainWindowsNoGUI::actionDockWidgetToolbox, MainWindowsNoGUI::actionDockWidgetToolOptions, and ui.
Referenced by CreateMenus().
addDraftBlock()
void MainWindow::addDraftBlock (const QString & blockName) private
Definition at line 298 of file mainwindow.cpp.
References VAbstractPattern::appendDraftBlock(), VContainer::ClearGObjects(), VToolBasePoint::Create(), MainWindowsNoGUI::doc, draftBlockComboBox, draftBlockStartPosition(), draftScene, VMainGraphicsScene::enablePiecesMode(), FromGui, FullParse, VPattern::GenerateLabel(), groupsWidget, helpLabel, VMainGraphicsScene::InitOrigins(), NewPatternPiece, VMainGraphicsView::NewSceneRect(), MainWindowsNoGUI::pattern, pieceScene, qApp, setToolsEnabled(), setWidgetsEnabled(), ui, and GroupsWidget::updateGroups().
Referenced by New().
addGroupToList
void MainWindow::addGroupToList () slot
Definition at line 1683 of file mainwindow.cpp.
References GroupsWidget::addGroupToList(), and groupsWidget.
addSelectedItemsToGroup
void MainWindow::addSelectedItemsToGroup () slot
Definition at line 1697 of file mainwindow.cpp.
ApplyDialog()
template<typename DrawTool > void MainWindow::ApplyDialog (VMainGraphicsScene * scene) private
ApplyDialog handle apply in dialog.
Definition at line 780 of file mainwindow.cpp.
References dialogTool, MainWindowsNoGUI::doc, MainWindowsNoGUI::pattern, and SCASSERT.
ApplyDrawDialog()
template<typename DrawTool > void MainWindow::ApplyDrawDialog private
Definition at line 808 of file mainwindow.cpp.
References draftScene.
applyPiecesDialog()
template<typename DrawTool > void MainWindow::applyPiecesDialog private
Definition at line 831 of file mainwindow.cpp.
References pieceScene.
AutoSavePattern()
void MainWindow::AutoSavePattern () private
AutoSavePattern start safe saving.
Definition at line 4772 of file mainwindow.cpp.
References autosavePrefix, patternReadOnly, qApp, and SavePattern().
Referenced by InitAutoSave().
CancelTool()
QT_WARNING_PUSH void MainWindow::CancelTool () private
CancelTool cancel tool.
Definition at line 3124 of file mainwindow.cpp.
References AbstractSpline, AlongLine, AnchorPoint, Arc, ArcIntersectAxis, ArcWithLength, Arrow, BasePoint, Bisector, CubicBezier, CubicBezierPath, CurveIntersectAxis, Cut, CutArc, CutSpline, CutSplinePath, DoublePoint, EllipticalArc, EndLine, Group, Height, InsertNodes, InternalPath, LAST_ONE_DO_NOT_USE, Line, LineIntersect, LineIntersectAxis, LinePoint, VAbstractTool::m_suppressContextMenu, Midpoint, MirrorByAxis, MirrorByLine, Move, NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, Normal, Piece, PointFromArcAndTangent, PointFromCircleAndTangent, PointOfContact, PointOfIntersection, PointOfIntersectionArcs, PointOfIntersectionCircles, PointOfIntersectionCurves, qApp, Rotation, ShoulderPoint, SinglePoint, Spline, SplinePath, Triangle, TrueDarts, and Union.
Referenced by handleArrowTool(), SetToolButton(), and ~MainWindow().
ChangedHeight
void MainWindow::ChangedHeight (int index) private slot
ChangedGrowth change new height value.
Parameters
index index of the selected item.
Definition at line 4472 of file mainwindow.cpp.
References AbsoluteMPath(), VMainGraphicsScene::DimensionsChanged(), MainWindowsNoGUI::doc, gradationHeights, VContainer::height(), LiteParse, VPattern::LiteParseTree(), VAbstractPattern::MPath(), pieceScene, qApp, VContainer::size(), and UpdateMeasurements().
Referenced by initStatusBar(), and UpdateHeightsList().
changeDraftBlock()
void MainWindow::changeDraftBlock (int index, bool zoomBestFit = true) private
Definition at line 6748 of file mainwindow.cpp.
References VAbstractPattern::changeActiveDraftBlock(), MainWindowsNoGUI::doc, draftBlockComboBox, drawMode, groupsWidget, handleArrowTool(), VToolOptionsPropertyBrowser::itemClicked(), RefreshHistory(), VPattern::setCurrentData(), toolProperties, GroupsWidget::updateGroups(), and zoomToSelected().
Referenced by changeDraftBlockGlobally(), and initDraftToolBar().
changeDraftBlockGlobally
void MainWindow::changeDraftBlockGlobally (const QString & patternPiece) private slot
Definition at line 4175 of file mainwindow.cpp.
References changeDraftBlock(), VException::DetailedInformation(), draftBlockComboBox, VExceptionBadId::ErrorMessage(), VApplication::IsGUIMode(), qApp, setGuiEnabled(), and V_EX_NOINPUT.
Referenced by fullParseFile().
ChangedSize
void MainWindow::ChangedSize (int index) private slot
ChangedSize change new size value.
Parameters
index index of the selected item.
Definition at line 4441 of file mainwindow.cpp.
References AbsoluteMPath(), VMainGraphicsScene::DimensionsChanged(), MainWindowsNoGUI::doc, gradationSizes, VContainer::height(), LiteParse, VPattern::LiteParseTree(), VAbstractPattern::MPath(), pieceScene, qApp, VContainer::size(), and UpdateMeasurements().
Referenced by initStatusBar(), and UpdateSizesList().
changeEvent()
void MainWindow::changeEvent (QEvent * event) protected virtual
Definition at line 1727 of file mainwindow.cpp.
References draftBlockLabel, helpLabel, VMainGraphicsScene::LanguageChanged(), pieceScene, MainWindowsNoGUI::redoAction, ui, MainWindowsNoGUI::undoAction, and UpdateWindowTitle().
CheckPathToMeasurements()
QString MainWindow::CheckPathToMeasurements (const QString & patternPath, const QString & path) private
Definition at line 6600 of file mainwindow.cpp.
References CheckRequiredMeasurements(), VAbstractConverter::Convert(), MainWindowsNoGUI::doc, VCommonSettings::GetDefPathMultisizeMeasurements(), Individual, VApplication::IsGUIMode(), Multisize, MainWindowsNoGUI::pattern, patternChangesWereSaved(), VCommonSettings::PrepareMultisizeTables(), qApp, RelativeMPath(), VContainer::rheight(), VContainer::rsize(), VAbstractPattern::SetMPath(), and Unknown.
Referenced by LoadPattern().
CheckRequiredMeasurements()
void MainWindow::CheckRequiredMeasurements (const VMeasurements * m) private
Definition at line 602 of file mainwindow.cpp.
References VException::AddMoreInformation(), MainWindowsNoGUI::doc, VMeasurements::ListAll(), VAbstractPattern::ListMeasurements(), and qApp.
Referenced by CheckPathToMeasurements(), and OpenMeasurementFile().
CleanLayout()
void MainWindow::CleanLayout () protected virtual
Implements MainWindowsNoGUI.
Definition at line 1776 of file mainwindow.cpp.
References GroupsWidget::clear(), groupsWidget, MainWindowsNoGUI::papers, MainWindowsNoGUI::scenes, SetLayoutModeActions(), MainWindowsNoGUI::shadows, and ui.
Referenced by Clear(), and ~MainWindow().
Clear
void MainWindow::Clear () private slot
Clear reset to default window.
Definition at line 3952 of file mainwindow.cpp.
References AbsoluteMPath(), CleanLayout(), VContainer::Clear(), VToolOptionsPropertyBrowser::clearPropertyBrowser(), Cm, MainWindowsNoGUI::doc, draftBlockComboBox, draftScene, handleArrowTool(), VToolOptionsPropertyBrowser::itemClicked(), lock, VAbstractPattern::MPath(), MainWindowsNoGUI::pattern, MainWindowsNoGUI::pieceList, pieceScene, qApp, setCurrentFile(), setToolsEnabled(), showDraftMode(), toolProperties, ui, Unknown, watcher, and zoomScaleSpinBox.
Referenced by IgnoreLocking(), LoadPattern(), and MainWindow().
ClosedDialog()
template<typename DrawTool > void MainWindow::ClosedDialog (int result) private
ClosedDialog handle close dialog.
Parameters
result result working dialog.
Definition at line 726 of file mainwindow.cpp.
References MainWindowsNoGUI::currentScene, dialogTool, MainWindowsNoGUI::doc, handleArrowTool(), MainWindowsNoGUI::pattern, SCASSERT, and ui.
ClosedDialogAnchorPoint
void MainWindow::ClosedDialogAnchorPoint (int result) private slot
Definition at line 1534 of file mainwindow.cpp.
References AnchorPointTool::Create(), dialogTool, MainWindowsNoGUI::doc, handleArrowTool(), LiteParse, VPattern::LiteParseTree(), MainWindowsNoGUI::pattern, and SCASSERT.
Referenced by handleAnchorPointTool().
ClosedDialogInternalPath
void MainWindow::ClosedDialogInternalPath (int result) private slot
Definition at line 1560 of file mainwindow.cpp.
References VToolInternalPath::Create(), dialogTool, MainWindowsNoGUI::doc, handleArrowTool(), LiteParse, VPattern::LiteParseTree(), MainWindowsNoGUI::pattern, pieceScene, and SCASSERT.
Referenced by handleInternalPathTool().
ClosedDialogWithApply()
template<typename DrawTool > void MainWindow::ClosedDialogWithApply (int result, VMainGraphicsScene * scene) private
ClosedDialogWithApply handle close dialog that has apply button.
Parameters
result result working dialog.
Definition at line 747 of file mainwindow.cpp.
References dialogTool, MainWindowsNoGUI::doc, VAbstractPattern::getCursor(), handleArrowTool(), historyDialog, LiteParse, VPattern::LiteParseTree(), SCASSERT, ShowToolTip(), and ui.
ClosedDrawDialogWithApply()
template<typename DrawTool > void MainWindow::ClosedDrawDialogWithApply (int result) private
Definition at line 801 of file mainwindow.cpp.
References draftScene.
ClosedEditGroupDialog
void MainWindow::ClosedEditGroupDialog (int result) private slot
Definition at line 1387 of file mainwindow.cpp.
References VAbstractPattern::addGroupItems(), dialogTool, MainWindowsNoGUI::doc, handleArrowTool(), and SCASSERT.
Referenced by handleGroupTool().
ClosedInsertNodesDialog
void MainWindow::ClosedInsertNodesDialog (int result) private slot
Definition at line 1591 of file mainwindow.cpp.
References dialogTool, MainWindowsNoGUI::doc, handleArrowTool(), PatternPieceTool::insertNodes(), LiteParse, VPattern::LiteParseTree(), MainWindowsNoGUI::pattern, pieceScene, and SCASSERT.
Referenced by handleInsertNodesTool().
ClosedPiecesDialogWithApply()
template<typename DrawTool > void MainWindow::ClosedPiecesDialogWithApply (int result) private
Definition at line 815 of file mainwindow.cpp.
References VContainer::DataPieces(), MainWindowsNoGUI::pattern, pieceScene, and ui.
closeEvent()
void MainWindow::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle after close window.
Parameters
event close event.
Definition at line 1749 of file mainwindow.cpp.
References FileClosedCorrect(), and MaybeSave().
closeUnionDialog
void MainWindow::closeUnionDialog (int result) private slot
closeUnionDialog actions after closing Union tool dialog.
Parameters
result result of dialog working.
Definition at line 1627 of file mainwindow.cpp.
References MainWindowsNoGUI::doc, LiteParse, and VPattern::LiteParseTree().
Referenced by handleUnionTool().
CreateActions()
void MainWindow::CreateActions () private
connect(ui->toggleAnchorPoints_Action, &QAction::triggered, this, [this](bool checked) { qApp->Seamly2DSettings()->setShowAnchorPoints(checked); });
Definition at line 5309 of file mainwindow.cpp.
References New(), Open(), Save(), SaveAs(), and ui.
createDraftBlockName()
QString MainWindow::createDraftBlockName (const QString & text) private
Definition at line 5939 of file mainwindow.cpp.
References draftBlockComboBox.
CreateMenus()
void MainWindow::CreateMenus () private
Definition at line 4940 of file mainwindow.cpp.
References AddDocks(), MaxRecentFiles, qApp, recentFileActs, MainWindowsNoGUI::redoAction, VToolOptionsPropertyBrowser::refreshOptions(), separatorAct, toolProperties, ui, MainWindowsNoGUI::undoAction, and UpdateRecentFileActions().
customEvent()
void MainWindow::customEvent (QEvent * event) protected virtual
Definition at line 1767 of file mainwindow.cpp.
References qApp, and UNDO_EVENT.
deleteGroupFromList
void MainWindow::deleteGroupFromList () slot
Definition at line 1687 of file mainwindow.cpp.
References GroupsWidget::deleteGroupFromList(), and groupsWidget.
DoExport()
void MainWindow::DoExport (const VCommandLinePtr & expParams) private
Definition at line 6813 of file mainwindow.cpp.
References VContainer::DataPieces(), VException::ErrorMessage(), MainWindowsNoGUI::ExportData(), Layout, MainWindowsNoGUI::LayoutSettings(), Modeling, MainWindowsNoGUI::pattern, MainWindowsNoGUI::pieceList, MainWindowsNoGUI::pieces, MainWindowsNoGUI::preparePiecesForLayout(), qApp, MainWindowsNoGUI::scenes, ExportLayoutDialog::selectFormat(), ExportLayoutDialog::setBinaryDXFFormat(), ExportLayoutDialog::setDestinationPath(), ExportLayoutDialog::setTextAsPaths(), V_EX_DATAERR, and V_EX_OK.
Referenced by ProcessCMD().
draftBlockStartPosition()
QPointF MainWindow::draftBlockStartPosition () const private
Definition at line 350 of file mainwindow.cpp.
References draftBlockComboBox, draftScene, and VMainGraphicsScene::visibleItemsBoundingRect().
Referenced by addDraftBlock().
draftPointNamesList()
QStringList MainWindow::draftPointNamesList () private
draftPointNamesList gets the list of points in draft mode.
Definition at line 7227 of file mainwindow.cpp.
References VContainer::DataGObjects(), MainWindowsNoGUI::pattern, and Point.
Referenced by LoadPattern(), and showZoomToPointDialog().
editGroup
void MainWindow::editGroup () slot
Definition at line 1692 of file mainwindow.cpp.
References GroupsWidget::editGroup(), and groupsWidget.
EnableArcHover
void MainWindow::EnableArcHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableArcSelection
void MainWindow::EnableArcSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableElArcHover
void MainWindow::EnableElArcHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableElArcSelection
void MainWindow::EnableElArcSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableItemMove
void MainWindow::EnableItemMove (bool move) signal
Referenced by handleArrowTool(), InitScenes(), and SetToolButton().
EnableLabelHover
void MainWindow::EnableLabelHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableLabelSelection
void MainWindow::EnableLabelSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableLineHover
void MainWindow::EnableLineHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectGroupObjects(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableLineSelection
void MainWindow::EnableLineSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectGroupObjects(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableNodeLabelHover
void MainWindow::EnableNodeLabelHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), and selectPieceTool().
EnableNodeLabelSelection
void MainWindow::EnableNodeLabelSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), and selectPieceTool().
EnableNodePointHover
void MainWindow::EnableNodePointHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), and selectPieceTool().
EnableNodePointSelection
void MainWindow::EnableNodePointSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), and selectPieceTool().
enablePieceHover
void MainWindow::enablePieceHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), and selectPieceTool().
enablePieceSelection
void MainWindow::enablePieceSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), and selectPieceTool().
EnablePointHover
void MainWindow::EnablePointHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnablePointSelection
void MainWindow::EnablePointSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableSplineHover
void MainWindow::EnableSplineHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableSplinePathHover
void MainWindow::EnableSplinePathHover (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableSplinePathSelection
void MainWindow::EnableSplinePathSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EnableSplineSelection
void MainWindow::EnableSplineSelection (bool enable) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), and ToolSelectSplinePath().
EndVisualization()
void MainWindow::EndVisualization (bool click = false) private
EndVisualization try show dialog after and working with tool visualization.
Definition at line 6769 of file mainwindow.cpp.
References dialogTool.
Referenced by keyPressEvent().
exportDraftBlocksAs
void MainWindow::exportDraftBlocksAs () private slot
Definition at line 6404 of file mainwindow.cpp.
References BMP, Calculation, VAbstractPattern::changeActiveDraftBlock(), MainWindowsNoGUI::doc, draftScene, DXF_AC1006_AAMA, DXF_AC1006_ASTM, DXF_AC1006_Flat, DXF_AC1009_AAMA, DXF_AC1009_ASTM, DXF_AC1009_Flat, DXF_AC1012_AAMA, DXF_AC1012_ASTM, DXF_AC1012_Flat, DXF_AC1014_AAMA, DXF_AC1014_ASTM, DXF_AC1014_Flat, DXF_AC1015_AAMA, DXF_AC1015_ASTM, DXF_AC1015_Flat, DXF_AC1018_AAMA, DXF_AC1018_ASTM, DXF_AC1018_Flat, DXF_AC1021_AAMA, DXF_AC1021_ASTM, DXF_AC1021_Flat, DXF_AC1024_AAMA, DXF_AC1024_ASTM, DXF_AC1024_Flat, DXF_AC1027_AAMA, DXF_AC1027_ASTM, DXF_AC1027_Flat, EPS, MainWindowsNoGUI::exportBMP(), MainWindowsNoGUI::exportEPS(), ExportLayoutDialog::exportFormatSuffix(), MainWindowsNoGUI::exportJPG(), MainWindowsNoGUI::exportPDF(), MainWindowsNoGUI::exportPNG(), MainWindowsNoGUI::exportPPM(), MainWindowsNoGUI::exportPS(), MainWindowsNoGUI::exportSVG(), MainWindowsNoGUI::exportTIF(), ExportLayoutDialog::fileName(), MainWindowsNoGUI::FileName(), ExportLayoutDialog::format(), FullParse, VAbstractPattern::getActiveDraftBlockName(), JPG, MainWindowsNoGUI::margins, VMainGraphicsView::NewSceneRect(), OBJ, ExportLayoutDialog::path(), PDF, PDFTiled, PNG, PPM, PS, qApp, VMainGraphicsScene::setOriginsVisible(), SVG, TIF, ui, and zoomScaleChanged().
Referenced by handleOperationsMenu(), and InitToolButtons().
exportLayoutAs
void MainWindow::exportLayoutAs () private slot
Definition at line 6302 of file mainwindow.cpp.
References MainWindowsNoGUI::ContinueIfLayoutStale(), VException::DetailedInformation(), VException::ErrorMessage(), MainWindowsNoGUI::ExportData(), MainWindowsNoGUI::FileName(), MainWindowsNoGUI::isLayoutStale, Layout, MainWindowsNoGUI::scenes, and ui.
Referenced by handleLayoutMenu(), and InitToolButtons().
exportPiecesAs
void MainWindow::exportPiecesAs () private slot
Definition at line 6338 of file mainwindow.cpp.
References VContainer::DataPieces(), VException::DetailedInformation(), VException::ErrorMessage(), MainWindowsNoGUI::ExportData(), MainWindowsNoGUI::FileName(), Modeling, MainWindowsNoGUI::pattern, MainWindowsNoGUI::pieceList, MainWindowsNoGUI::preparePiecesForLayout(), and ui.
Referenced by handlePatternPiecesMenu(), and InitToolButtons().
exportToCSVData()
void MainWindow::exportToCSVData (const QString & fileName, const DialogExportToCSV & dialog) protected virtual
Implements VAbstractMainWindow.
Definition at line 1804 of file mainwindow.cpp.
References QxtCsvModel::insertColumn(), QxtCsvModel::insertRow(), MainWindowsNoGUI::pattern, qApp, DialogExportToCSV::SelectedMib(), DialogExportToCSV::Separator(), QxtCsvModel::setHeaderText(), QxtCsvModel::setText(), QxtCsvModel::toCSV(), VContainer::variablesData(), and DialogExportToCSV::WithHeader().
FileClosedCorrect()
void MainWindow::FileClosedCorrect () private
Definition at line 4035 of file mainwindow.cpp.
References autosavePrefix, qApp, and WriteSettings().
Referenced by closeEvent().
fullParseFile
void MainWindow::fullParseFile () private slot
Definition at line 4054 of file mainwindow.cpp.
References changeDraftBlockGlobally(), VToolOptionsPropertyBrowser::clearPropertyBrowser(), VException::DetailedInformation(), MainWindowsNoGUI::doc, draftBlockComboBox, draftScene, drawMode, VException::ErrorMessage(), FullParse, VAbstractPattern::getPatternPieces(), VApplication::IsGUIMode(), VMainGraphicsView::NewSceneRect(), VPattern::Parse(), patternPiecesWidget, pieceScene, qApp, setGuiEnabled(), setToolsEnabled(), toolProperties, ui, PiecesWidget::updateList(), and V_EX_NOINPUT.
Referenced by initDraftToolBar(), LoadPattern(), and MainWindow().
GetMeasurementFileName()
QString MainWindow::GetMeasurementFileName () private
Definition at line 7049 of file mainwindow.cpp.
References AbsoluteMPath(), MainWindowsNoGUI::doc, mChanges, VAbstractPattern::MPath(), qApp, and strippedName().
Referenced by UpdateWindowTitle().
GetPatternFileName()
QString MainWindow::GetPatternFileName () private
Definition at line 7037 of file mainwindow.cpp.
References qApp.
Referenced by UpdateWindowTitle().
GetUnlokedRestoreFileList()
QStringList MainWindow::GetUnlokedRestoreFileList () const private
Definition at line 6172 of file mainwindow.cpp.
References VLockGuard< Guarded >::IsLocked(), and qApp.
Referenced by ReopenFilesAfterCrash().
handleAlongLineTool
void MainWindow::handleAlongLineTool (bool checked) private slot
handleAlongLineTool handler for point along Line tools.
Parameters
checked true - button checked.
Definition at line 877 of file mainwindow.cpp.
References AlongLine, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handleAnchorPointTool
void MainWindow::handleAnchorPointTool (bool checked) private slot
Definition at line 1521 of file mainwindow.cpp.
References AnchorPoint, ClosedDialogAnchorPoint(), and ToolSelectPointByRelease().
Referenced by handlePieceMenu(), and InitToolButtons().
handleArcIntersectAxisTool
void MainWindow::handleArcIntersectAxisTool (bool checked) private slot
Definition at line 1254 of file mainwindow.cpp.
References ArcIntersectAxis, and selectAllDraftObjectsTool().
Referenced by handleArcsMenu(), and InitToolButtons().
handleArcsMenu()
void MainWindow::handleArcsMenu () private
Definition at line 2790 of file mainwindow.cpp.
References handleArcIntersectAxisTool(), handleArcTool(), handleArcWithLengthTool(), handleEllipticalArcTool(), handlePointAlongArcTool(), handlePointFromArcAndTangentTool(), handlePointFromCircleAndTangentTool(), handlePointOfIntersectionArcsTool(), handlePointOfIntersectionCirclesTool(), and ui.
handleArcTool
void MainWindow::handleArcTool (bool checked) private slot
handleArcTool handler for arc tool.
Parameters
checked true - button checked.
Definition at line 1220 of file mainwindow.cpp.
References Arc, and ToolSelectPointByRelease().
Referenced by handleArcsMenu(), and InitToolButtons().
handleArcWithLengthTool
void MainWindow::handleArcWithLengthTool (bool checked) private slot
Definition at line 1332 of file mainwindow.cpp.
References ArcWithLength, and ToolSelectPointByRelease().
Referenced by handleArcsMenu(), and InitToolButtons().
handleArrowTool
QT_WARNING_POP void MainWindow::handleArrowTool (bool checked) private slot
handleArrowTool enable arrow tool.
Definition at line 3306 of file mainwindow.cpp.
References Arrow, ByMouseRelease, CancelTool(), currentTool, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableItemMove(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnableNodeLabelHover(), EnableNodeLabelSelection(), EnableNodePointHover(), EnableNodePointSelection(), enablePieceHover(), enablePieceSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), helpLabel, ItemsSelection(), VAbstractTool::m_suppressContextMenu, and ui.
Referenced by changeDraftBlock(), Clear(), ClosedDialog(), ClosedDialogAnchorPoint(), ClosedDialogInternalPath(), ClosedDialogWithApply(), ClosedEditGroupDialog(), ClosedInsertNodesDialog(), InitToolButtons(), keyPressEvent(), setGuiEnabled(), showDraftMode(), showLayoutMode(), and showPieceMode().
handleBisectorTool
void MainWindow::handleBisectorTool (bool checked) private slot
handleBisectorTool handler for bisector tool.
Parameters
checked true - button checked.
Definition at line 915 of file mainwindow.cpp.
References Bisector, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handleCirclesMenu()
void MainWindow::handleCirclesMenu () private
Definition at line 2937 of file mainwindow.cpp.
handleCurveIntersectAxisTool
void MainWindow::handleCurveIntersectAxisTool (bool checked) private slot
Definition at line 1200 of file mainwindow.cpp.
References CurveIntersectAxis, and selectAllDraftObjectsTool().
Referenced by handleCurvesMenu(), and InitToolButtons().
handleCurveIntersectCurveTool
void MainWindow::handleCurveIntersectCurveTool (bool checked) private slot
Definition at line 1185 of file mainwindow.cpp.
References PointOfIntersectionCurves, and ToolSelectCurve().
Referenced by handleCurvesMenu(), and InitToolButtons().
handleCurvesMenu()
void MainWindow::handleCurvesMenu () private
Definition at line 2867 of file mainwindow.cpp.
References handleCurveIntersectAxisTool(), handleCurveIntersectCurveTool(), handleCurveTool(), handleCurveWithControlPointsTool(), handlePointAlongCurveTool(), handlePointAlongSplineTool(), handleSplineTool(), handleSplineWithControlPointsTool(), and ui.
handleCurveTool
void MainWindow::handleCurveTool (bool checked) private slot
handleCurveTool handler for curve tool.
Parameters
checked true - button checked.
Definition at line 1083 of file mainwindow.cpp.
References Spline, and ToolSelectPointByPress().
Referenced by handleCurvesMenu(), and InitToolButtons().
handleCurveWithControlPointsTool
void MainWindow::handleCurveWithControlPointsTool (bool checked) private slot
Definition at line 1117 of file mainwindow.cpp.
References CubicBezier, and ToolSelectPointByRelease().
Referenced by handleCurvesMenu(), and InitToolButtons().
handleEllipticalArcTool
void MainWindow::handleEllipticalArcTool (bool checked) private slot
handleEllipticalArcTool handler for EllipticalArc tool.
Parameters
checked true - button checked.
Definition at line 1352 of file mainwindow.cpp.
References EllipticalArc, and ToolSelectPointByRelease().
Referenced by handleArcsMenu(), and InitToolButtons().
handleExportToCSV()
void MainWindow::handleExportToCSV () protected
Definition at line 1858 of file mainwindow.cpp.
References VAbstractMainWindow::exportToCSV(), and qApp.
handleGroupTool
void MainWindow::handleGroupTool (bool checked) private slot
Definition at line 1368 of file mainwindow.cpp.
References ClosedEditGroupDialog(), Group, strCtrl, strQShortcut, ToolSelectGroupObjects(), and translate.
Referenced by handleOperationsMenu(), and InitToolButtons().
handleHeightTool
void MainWindow::handleHeightTool (bool checked) private slot
handleHeightTool handler tool height.
Parameters
checked true - button checked.
Definition at line 1009 of file mainwindow.cpp.
References Height, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handleImagesMenu()
void MainWindow::handleImagesMenu () private
handleInsertNodesTool
void MainWindow::handleInsertNodesTool (bool checked) private slot
Definition at line 1572 of file mainwindow.cpp.
References ClosedInsertNodesDialog(), InsertNodes, strCtrl, strQShortcut, ToolSelectOperationObjects(), and translate.
Referenced by handlePieceMenu(), and InitToolButtons().
handleInternalPathTool
void MainWindow::handleInternalPathTool (bool checked) private slot
Definition at line 1546 of file mainwindow.cpp.
References ClosedDialogInternalPath(), InternalPath, and selectAllDraftObjectsTool().
Referenced by handlePieceMenu(), and InitToolButtons().
handleLayoutMenu()
void MainWindow::handleLayoutMenu () private
Definition at line 3076 of file mainwindow.cpp.
References exportLayoutAs(), handleNewLayout(), and ui.
handleLineIntersectAxisTool
void MainWindow::handleLineIntersectAxisTool (bool checked) private slot
Definition at line 1024 of file mainwindow.cpp.
References LineIntersectAxis, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handleLineIntersectTool
void MainWindow::handleLineIntersectTool (bool checked) private slot
handleLineIntersectTool handler for lineIntersect tool.
Parameters
checked true - button checked.
Definition at line 1063 of file mainwindow.cpp.
References LineIntersect, and ToolSelectPointByRelease().
Referenced by handleLinesMenu(), and InitToolButtons().
handleLinesMenu()
void MainWindow::handleLinesMenu () private
Definition at line 2762 of file mainwindow.cpp.
References handleLineIntersectTool(), handleLineTool(), and ui.
handleLineTool
void MainWindow::handleLineTool (bool checked) private slot
handleLineTool handler for line tool.
Parameters
checked true - button checked.
Definition at line 1044 of file mainwindow.cpp.
References Line, and ToolSelectPointByRelease().
Referenced by handleLinesMenu(), and InitToolButtons().
handleMidpointTool
void MainWindow::handleMidpointTool (bool checked) private slot
Definition at line 838 of file mainwindow.cpp.
References Midpoint, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handleMirrorByAxisTool
void MainWindow::handleMirrorByAxisTool (bool checked) private slot
Definition at line 1447 of file mainwindow.cpp.
References MirrorByAxis, strCtrl, strQShortcut, ToolSelectOperationObjects(), and translate.
Referenced by handleOperationsMenu(), and InitToolButtons().
handleMirrorByLineTool
void MainWindow::handleMirrorByLineTool (bool checked) private slot
Definition at line 1428 of file mainwindow.cpp.
References MirrorByLine, strCtrl, strQShortcut, ToolSelectOperationObjects(), and translate.
Referenced by handleOperationsMenu(), and InitToolButtons().
handleMoveTool
void MainWindow::handleMoveTool (bool checked) private slot
Definition at line 1467 of file mainwindow.cpp.
References Move, strCtrl, strQShortcut, ToolSelectOperationObjects(), and translate.
Referenced by handleOperationsMenu(), and InitToolButtons().
handleNewLayout
void MainWindow::handleNewLayout (bool checked) private slot
handleNewLayout handler for New Layout tool.
Parameters
tButton - toolbutton.
checked true - button checked.
Definition at line 1639 of file mainwindow.cpp.
References MainWindowsNoGUI::toolLayoutSettings(), and ui.
Referenced by handleLayoutMenu(), and InitToolButtons().
handleNormalTool
void MainWindow::handleNormalTool (bool checked) private slot
handleNormalTool handler point on perpendicular tool.
Parameters
checked true - button checked.
Definition at line 896 of file mainwindow.cpp.
References Normal, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handleOperationsMenu()
void MainWindow::handleOperationsMenu () private
Definition at line 2943 of file mainwindow.cpp.
References exportDraftBlocksAs(), handleGroupTool(), handleMirrorByAxisTool(), handleMirrorByLineTool(), handleMoveTool(), handleRotationTool(), handleTrueDartTool(), and ui.
handlePatternPiecesMenu()
void MainWindow::handlePatternPiecesMenu () private
Definition at line 3050 of file mainwindow.cpp.
References exportPiecesAs(), handleUnionTool(), and ui.
handlePatternPieceTool
void MainWindow::handlePatternPieceTool (bool checked) private slot
handlePatternPieceTool handler for pattern piece tool.
Parameters
checked true - button checked.
Definition at line 1506 of file mainwindow.cpp.
References Piece, and selectAllDraftObjectsTool().
Referenced by handlePieceMenu(), and InitToolButtons().
handlePieceMenu()
void MainWindow::handlePieceMenu () private
Definition at line 3005 of file mainwindow.cpp.
References VContainer::DataPieces(), handleAnchorPointTool(), handleInsertNodesTool(), handleInternalPathTool(), handlePatternPieceTool(), MainWindowsNoGUI::pattern, and ui.
handlePointAlongArcTool
void MainWindow::handlePointAlongArcTool (bool checked) private slot
handlePointAlongArcTool handler for PointAlongArc tool.
Parameters
checked true - button checked.
Definition at line 1239 of file mainwindow.cpp.
References CutArc, and ToolSelectArc().
Referenced by handleArcsMenu(), and InitToolButtons().
handlePointAlongCurveTool
void MainWindow::handlePointAlongCurveTool (bool checked) private slot
handlePointAlongCurveTool handler for point along curve tool.
Parameters
checked true - button is checked
Definition at line 1151 of file mainwindow.cpp.
References CutSpline, and ToolSelectSpline().
Referenced by handleCurvesMenu(), and InitToolButtons().
handlePointAlongSplineTool
void MainWindow::handlePointAlongSplineTool (bool checked) private slot
handlePointAlongSplineTool handler for point along spline tool.
Parameters
checked true - button is checked
Definition at line 1170 of file mainwindow.cpp.
References CutSplinePath, and ToolSelectSplinePath().
Referenced by handleCurvesMenu(), and InitToolButtons().
handlePointAtDistanceAngleTool
void MainWindow::handlePointAtDistanceAngleTool (bool checked) private slot
handlePointAtDistanceAngleTool handler for handlePointAtDistanceAngle tool.
Parameters
checked true - button checked.
Definition at line 858 of file mainwindow.cpp.
References EndLine, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handlePointFromArcAndTangentTool
void MainWindow::handlePointFromArcAndTangentTool (bool checked) private slot
Definition at line 1317 of file mainwindow.cpp.
References PointFromArcAndTangent, and ToolSelectPointArc().
Referenced by handleArcsMenu(), and InitToolButtons().
handlePointFromCircleAndTangentTool
void MainWindow::handlePointFromCircleAndTangentTool (bool checked) private slot
Definition at line 1302 of file mainwindow.cpp.
References PointFromCircleAndTangent, and ToolSelectPointByRelease().
Referenced by handleArcsMenu(), and InitToolButtons().
handlePointIntersectXYTool
void MainWindow::handlePointIntersectXYTool (bool checked) private slot
handlePointIntersectXYTool handler for pointOfIntersection tool.
Parameters
checked true - button checked.
Definition at line 990 of file mainwindow.cpp.
References PointOfIntersection, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handlePointOfContactTool
void MainWindow::handlePointOfContactTool (bool checked) private slot
handlePointOfContactTool handler for pointOfContact tool.
Parameters
checked true - button checked.
Definition at line 953 of file mainwindow.cpp.
References PointOfContact, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handlePointOfIntersectionArcsTool
void MainWindow::handlePointOfIntersectionArcsTool (bool checked) private slot
Definition at line 1270 of file mainwindow.cpp.
References PointOfIntersectionArcs, and ToolSelectArc().
Referenced by handleArcsMenu(), and InitToolButtons().
handlePointOfIntersectionCirclesTool
void MainWindow::handlePointOfIntersectionCirclesTool (bool checked) private slot
Definition at line 1285 of file mainwindow.cpp.
References PointOfIntersectionCircles, and ToolSelectPointByRelease().
Referenced by handleArcsMenu(), and InitToolButtons().
handlePointsMenu()
void MainWindow::handlePointsMenu () private
Definition at line 2670 of file mainwindow.cpp.
References handleAlongLineTool(), handleBisectorTool(), handleHeightTool(), handleLineIntersectAxisTool(), handleMidpointTool(), handleNormalTool(), handlePointAtDistanceAngleTool(), handlePointIntersectXYTool(), handlePointOfContactTool(), handleShoulderPointTool(), handleTriangleTool(), and ui.
handleRotationTool
void MainWindow::handleRotationTool (bool checked) private slot
Definition at line 1408 of file mainwindow.cpp.
References Rotation, strCtrl, strQShortcut, ToolSelectOperationObjects(), and translate.
Referenced by handleOperationsMenu(), and InitToolButtons().
handleShoulderPointTool
void MainWindow::handleShoulderPointTool (bool checked) private slot
handleShoulderPointTool handler for shoulderPoint tool.
Parameters
checked true - button checked.
Definition at line 934 of file mainwindow.cpp.
References ShoulderPoint, and ToolSelectPointByRelease().
Referenced by handlePointsMenu(), and InitToolButtons().
handleSplineTool
void MainWindow::handleSplineTool (bool checked) private slot
handleSplineTool handler for spline tool.
Parameters
checked true - button checked.
Definition at line 1102 of file mainwindow.cpp.
References SplinePath, and ToolSelectPointByPress().
Referenced by handleCurvesMenu(), and InitToolButtons().
handleSplineWithControlPointsTool
void MainWindow::handleSplineWithControlPointsTool (bool checked) private slot
Definition at line 1132 of file mainwindow.cpp.
References CubicBezierPath, and ToolSelectPointByRelease().
Referenced by handleCurvesMenu(), and InitToolButtons().
handleTriangleTool
void MainWindow::handleTriangleTool (bool checked) private slot
handleTriangleTool handler Point - Intersect Axis and Triangle.
Parameters
checked true - button checked.
Definition at line 971 of file mainwindow.cpp.
References ToolSelectPointByRelease(), and Triangle.
Referenced by handlePointsMenu(), and InitToolButtons().
handleTrueDartTool
void MainWindow::handleTrueDartTool (bool checked) private slot
Definition at line 1487 of file mainwindow.cpp.
References ToolSelectPointByRelease(), and TrueDarts.
Referenced by handleOperationsMenu(), and InitToolButtons().
handleUnionTool
void MainWindow::handleUnionTool (bool checked) private slot
handleUnionTool handler for Union tool.
Parameters
checked true - button checked.
Definition at line 1609 of file mainwindow.cpp.
References closeUnionDialog(), selectPieceTool(), and Union.
Referenced by handlePatternPiecesMenu(), and InitToolButtons().
hideAllGroups
void MainWindow::hideAllGroups () slot
Definition at line 1668 of file mainwindow.cpp.
References groupsWidget, and GroupsWidget::hideAllGroups().
IgnoreLocking()
bool MainWindow::IgnoreLocking (int error, const QString & path) private
Definition at line 7157 of file mainwindow.cpp.
References Clear(), VApplication::IsGUIMode(), qApp, and V_EX_NOINPUT.
Referenced by LoadPattern().
InitAutoSave()
void MainWindow::InitAutoSave () private
Definition at line 5918 of file mainwindow.cpp.
References AutoSavePattern(), autoSaveTimer, and qApp.
Referenced by Preferences().
InitDocksContain()
void MainWindow::InitDocksContain () private
Definition at line 5271 of file mainwindow.cpp.
References MainWindowsNoGUI::doc, VAbstractPattern::FullUpdateFromFile(), groupsWidget, PiecesWidget::Highlight(), VMainGraphicsScene::HighlightItem(), VToolOptionsPropertyBrowser::itemClicked(), VMainGraphicsView::itemClicked(), MainWindowsNoGUI::pattern, patternPiecesWidget, pieceScene, PiecesWidget::selectPiece(), VAbstractPattern::showPiece(), PiecesWidget::togglePiece(), toolProperties, ui, VAbstractPattern::updateGroups(), updateGroups(), VAbstractPattern::UpdateInLayoutList(), PiecesWidget::updateList(), and VToolOptionsPropertyBrowser::updateOptions().
initDraftToolBar()
void MainWindow::initDraftToolBar () private
initDraftToolBar enable draw toolbar.
Definition at line 2276 of file mainwindow.cpp.
References changeDraftBlock(), MainWindowsNoGUI::doc, draftBlockComboBox, draftBlockLabel, fullParseFile(), qApp, and ui.
initModesToolBar()
void MainWindow::initModesToolBar () private
Definition at line 2195 of file mainwindow.cpp.
References leftGoToStage, rightGoToStage, and ui.
initPenToolBar()
void MainWindow::initPenToolBar () private
initPenToolBar enable default color, line wight & type toolbar.
Definition at line 2439 of file mainwindow.cpp.
References m_penToolBar, penChanged(), and PenToolBar::penChanged().
initPointNameToolBar()
void MainWindow::initPointNameToolBar () private
initPointNameToolBar enable Point Name toolbar.
Definition at line 2210 of file mainwindow.cpp.
References fontComboBox, fontSizeComboBox, qApp, ui, and upDateScenes().
InitScenes()
void MainWindow::InitScenes () private
Definition at line 374 of file mainwindow.cpp.
References MainWindowsNoGUI::currentScene, draftScene, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableItemMove(), VMainGraphicsScene::EnableItemMove(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnableNodeLabelHover(), EnableNodeLabelSelection(), EnableNodePointHover(), EnableNodePointSelection(), enablePieceHover(), enablePieceSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), VMainGraphicsScene::ItemsSelection(), ItemsSelection(), MouseMove(), VMainGraphicsScene::mouseMove(), VMainGraphicsView::mouseRelease(), pieceScene, qApp, VMainGraphicsScene::setCurrentTransform(), VMainGraphicsView::signalZoomScaleChanged(), VMainGraphicsScene::ToggleArcHover(), VMainGraphicsScene::ToggleArcSelection(), VMainGraphicsScene::ToggleElArcHover(), VMainGraphicsScene::ToggleElArcSelection(), VMainGraphicsScene::ToggleLabelHover(), VMainGraphicsScene::ToggleLabelSelection(), VMainGraphicsScene::ToggleLineHover(), VMainGraphicsScene::ToggleLineSelection(), VMainGraphicsScene::ToggleNodeLabelHover(), VMainGraphicsScene::ToggleNodeLabelSelection(), VMainGraphicsScene::ToggleNodePointHover(), VMainGraphicsScene::ToggleNodePointSelection(), VMainGraphicsScene::togglePieceHover(), VMainGraphicsScene::togglePieceSelection(), VMainGraphicsScene::TogglePointHover(), VMainGraphicsScene::TogglePointSelection(), VMainGraphicsScene::ToggleSplineHover(), VMainGraphicsScene::ToggleSplinePathHover(), VMainGraphicsScene::ToggleSplinePathSelection(), VMainGraphicsScene::ToggleSplineSelection(), ui, and zoomScaleChanged().
initStatusBar()
void MainWindow::initStatusBar () private
initStatusBar initialize horizontal bar for presenting status information
Definition at line 2123 of file mainwindow.cpp.
References ChangedHeight(), ChangedSize(), MainWindowsNoGUI::doc, VAbstractPattern::GetGradationHeights(), VAbstractPattern::GetGradationSizes(), gradationHeights, gradationHeightsLabel, gradationSizes, gradationSizesLabel, infoToolButton, VMeasurement::ListHeights(), VMeasurement::ListSizes(), mouseCoordinates, Multisize, qApp, SetDefaultHeight(), SetDefaultSize(), SetGradationList(), and ui.
Referenced by LoadMeasurements(), LoadPattern(), and UnloadMeasurements().
initToolBarVisibility()
void MainWindow::initToolBarVisibility () private
Definition at line 2385 of file mainwindow.cpp.
References ui, and updateToolBarVisibility().
InitToolButtons()
void MainWindow::InitToolButtons () private
Definition at line 2610 of file mainwindow.cpp.
References exportDraftBlocksAs(), exportLayoutAs(), exportPiecesAs(), handleAlongLineTool(), handleAnchorPointTool(), handleArcIntersectAxisTool(), handleArcTool(), handleArcWithLengthTool(), handleArrowTool(), handleBisectorTool(), handleCurveIntersectAxisTool(), handleCurveIntersectCurveTool(), handleCurveTool(), handleCurveWithControlPointsTool(), handleEllipticalArcTool(), handleGroupTool(), handleHeightTool(), handleInsertNodesTool(), handleInternalPathTool(), handleLineIntersectAxisTool(), handleLineIntersectTool(), handleLineTool(), handleMidpointTool(), handleMirrorByAxisTool(), handleMirrorByLineTool(), handleMoveTool(), handleNewLayout(), handleNormalTool(), handlePatternPieceTool(), handlePointAlongArcTool(), handlePointAlongCurveTool(), handlePointAlongSplineTool(), handlePointAtDistanceAngleTool(), handlePointFromArcAndTangentTool(), handlePointFromCircleAndTangentTool(), handlePointIntersectXYTool(), handlePointOfContactTool(), handlePointOfIntersectionArcsTool(), handlePointOfIntersectionCirclesTool(), handleRotationTool(), handleShoulderPointTool(), handleSplineTool(), handleSplineWithControlPointsTool(), handleTriangleTool(), handleTrueDartTool(), handleUnionTool(), LAST_ONE_DO_NOT_USE, and ui.
initToolsToolBar()
void MainWindow::initToolsToolBar () private
Definition at line 2305 of file mainwindow.cpp.
References m_zoomToPointComboBox, VMainGraphicsView::MaxScale(), VMainGraphicsView::MinScale(), resetPanShortcuts(), showZoomToPointDialog(), ui, VMainGraphicsView::zoom100Percent(), VMainGraphicsView::zoomIn(), VMainGraphicsView::zoomOut(), zoomPan(), zoomScaleChanged(), zoomScaleSpinBox, zoomToArea(), VMainGraphicsView::zoomToFit(), zoomToPoint(), zoomToPrevious(), and zoomToSelected().
ItemsSelection
void MainWindow::ItemsSelection (SelectionType type) const signal
Referenced by handleArrowTool(), InitScenes(), selectAllDraftObjectsTool(), selectPieceTool(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPointArc(), ToolSelectPointByPress(), ToolSelectPointByRelease(), ToolSelectSpline(), and ToolSelectSplinePath().
keyPressEvent()
void MainWindow::keyPressEvent (QKeyEvent * event) protected virtual
keyPressEvent handle key press events.
Parameters
event key event.
Definition at line 3363 of file mainwindow.cpp.
References EndVisualization(), handleArrowTool(), qApp, and ui.
keyReleaseEvent()
void MainWindow::keyReleaseEvent (QKeyEvent * event) protected virtual
keyReleaseEvent handle key press events.
Parameters
event key event.
Definition at line 3391 of file mainwindow.cpp.
References qApp, and ui.
LastUsedTool
QT_WARNING_PUSH void MainWindow::LastUsedTool () private slot
Definition at line 5036 of file mainwindow.cpp.
References AbstractSpline, AlongLine, AnchorPoint, Arc, ArcIntersectAxis, ArcWithLength, Arrow, BasePoint, Bisector, CubicBezier, CubicBezierPath, CurveIntersectAxis, Cut, CutArc, CutSpline, CutSplinePath, DoublePoint, EllipticalArc, EndLine, Group, Height, InsertNodes, InternalPath, LAST_ONE_DO_NOT_USE, Line, LineIntersect, LineIntersectAxis, LinePoint, Midpoint, MirrorByAxis, MirrorByLine, Move, NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, Normal, Piece, PointFromArcAndTangent, PointFromCircleAndTangent, PointOfContact, PointOfIntersection, PointOfIntersectionArcs, PointOfIntersectionCircles, PointOfIntersectionCurves, Rotation, ShoulderPoint, SinglePoint, Spline, SplinePath, Triangle, TrueDarts, and Union.
LoadIndividual
void MainWindow::LoadIndividual () private slot
Definition at line 1870 of file mainwindow.cpp.
References AbsoluteMPath(), MainWindowsNoGUI::doc, helpLabel, LiteParse, VPattern::LiteParseTree(), LoadMeasurements(), VAbstractPattern::MPath(), patternChangesWereSaved(), qApp, RelativeMPath(), VAbstractPattern::SetMPath(), ui, UpdateWindowTitle(), and watcher.
LoadMeasurements()
bool MainWindow::LoadMeasurements (const QString & path) private
Definition at line 498 of file mainwindow.cpp.
References VContainer::ClearVariables(), VExceptionEmptyParameter::DetailedInformation(), MainWindowsNoGUI::doc, VExceptionEmptyParameter::ErrorMessage(), Inch, Individual, initStatusBar(), VApplication::IsGUIMode(), Measurement, Multisize, OpenMeasurementFile(), MainWindowsNoGUI::pattern, qApp, VContainer::SetHeight(), VAbstractPattern::SetPatternWasChanged(), VContainer::SetSize(), MainWindowsNoGUI::SetSizeHeightForIndividualM(), UnitConvertor(), VAbstractPattern::UpdatePatternLabel(), and V_EX_NOINPUT.
Referenced by LoadIndividual(), LoadMultisize(), and LoadPattern().
LoadMultisize
void MainWindow::LoadMultisize () private slot
Definition at line 1915 of file mainwindow.cpp.
References AbsoluteMPath(), MainWindowsNoGUI::doc, gradationHeights, gradationSizes, helpLabel, LiteParse, VPattern::LiteParseTree(), LoadMeasurements(), VAbstractPattern::MPath(), Multisize, patternChangesWereSaved(), VCommonSettings::PrepareMultisizeTables(), qApp, RelativeMPath(), VAbstractPattern::SetMPath(), ui, UpdateWindowTitle(), and watcher.
LoadPattern()
bool MainWindow::LoadPattern (const QString & fileName, const QString & customMeasureFile = QString())
LoadPattern open pattern file.
Parameters
fileName name of file.
Definition at line 6003 of file mainwindow.cpp.
References AbsoluteMPath(), CheckPathToMeasurements(), Clear(), VAbstractConverter::Convert(), VException::DetailedInformation(), MainWindowsNoGUI::doc, draftPointNamesList(), draftScene, VException::ErrorMessage(), fullParseFile(), VAbstractConverter::GetCurrentFormatVarsion(), VAbstractConverter::GetVersionStr(), guiEnabled, helpLabel, IgnoreLocking(), Individual, initStatusBar(), VApplication::IsGUIMode(), MainWindowsNoGUI::isNoScaling, VPattern::IsReadOnly(), LoadMeasurements(), lock, LONG_OPTION_NO_HDPI_SCALING, VAbstractMainWindow::m_curFileFormatVersion, VAbstractMainWindow::m_curFileFormatVersionStr, VAbstractPattern::MPath(), Multisize, VDomDocument::MUnit(), VMainGraphicsView::NewSceneRect(), OpenNewSeamly2D(), MainWindowsNoGUI::pattern, patternReadOnly, pieceScene, qApp, RelativeMPath(), VContainer::rheight(), VContainer::rsize(), setCurrentFile(), VMeasurements::SetHeight(), VAbstractPattern::SetMPath(), VMeasurements::SetSize(), setWidgetsEnabled(), VPattern::setXMLContent(), VMeasurements::setXMLContent(), showDraftMode(), VMeasurements::Type(), ui, Unknown, updateZoomToPointComboBox(), V_EX_NOINPUT, V_EX_OK, VlpCreateLock(), watcher, and zoomFirstShow().
Referenced by VApplication::event(), Open(), ProcessCMD(), and ReopenFilesAfterCrash().
lockAllGroups
void MainWindow::lockAllGroups () slot
Definition at line 1673 of file mainwindow.cpp.
References groupsWidget, and GroupsWidget::lockAllGroups().
MaybeSave()
bool MainWindow::MaybeSave () private
MaybeSave The function is called to save pending changes.
Returns
returns true in all cases, except when the user clicks Cancel.
Definition at line 4875 of file mainwindow.cpp.
References guiEnabled, patternReadOnly, qApp, Save(), and SaveAs().
Referenced by closeEvent().
MeasurementsChanged
void MainWindow::MeasurementsChanged (const QString & path) private slot
Definition at line 2045 of file mainwindow.cpp.
References mChanges, mChangesAsked, ui, and UpdateWindowTitle().
MinimumScrollBar()
void MainWindow::MinimumScrollBar () private
MinimumScrollBar set scroll bar to minimum.
Definition at line 4723 of file mainwindow.cpp.
References ui.
Referenced by showEvent().
MouseMove
void MainWindow::MouseMove (const QPointF & scenePos) private slot
mouseMove save mouse position and show user.
Parameters
scenePos position mouse.
Definition at line 3110 of file mainwindow.cpp.
References mouseCoordinates.
Referenced by InitScenes().
New
void MainWindow::New () private slot
NewPattern create new empty pattern.
Definition at line 4380 of file mainwindow.cpp.
References addDraftBlock(), draftBlockComboBox, draftScene, VAbstractMainWindow::m_curFileFormatVersion, VAbstractMainWindow::m_curFileFormatVersionStr, mouseCoordinates, DialogNewPattern::name(), VMainGraphicsView::NewSceneRect(), OpenNewSeamly2D(), MainWindowsNoGUI::pattern, VPatternConverter::PatternMaxVer, VPatternConverter::PatternMaxVerStr, DialogNewPattern::PatternUnit(), pieceScene, qApp, and ui.
Referenced by CreateActions().
Open
void MainWindow::Open () private slot
Open ask user select pattern file.
Definition at line 3922 of file mainwindow.cpp.
References LoadPattern(), and qApp.
Referenced by CreateActions().
OpenMeasurementFile()
QSharedPointer< VMeasurements > MainWindow::OpenMeasurementFile (const QString & path) private
Definition at line 428 of file mainwindow.cpp.
References CheckRequiredMeasurements(), VAbstractConverter::Convert(), VException::DetailedInformation(), VException::ErrorMessage(), Inch, VApplication::IsGUIMode(), Multisize, MainWindowsNoGUI::pattern, qApp, VContainer::rheight(), VContainer::rsize(), Unknown, V_EX_DATAERR, and V_EX_NOINPUT.
Referenced by LoadMeasurements(), and UpdateMeasurements().
OpenNewSeamly2D()
bool MainWindow::OpenNewSeamly2D (const QString & fileName = QString()) const private
Definition at line 5298 of file mainwindow.cpp.
References VApplication::NewSeamly2D(), and qApp.
Referenced by LoadPattern(), and New().
patternChangesWereSaved
void MainWindow::patternChangesWereSaved (bool saved) private slot
haveChange enable action save if we have unsaved change.
Definition at line 4425 of file mainwindow.cpp.
References MainWindowsNoGUI::doc, guiEnabled, MainWindowsNoGUI::isLayoutStale, VAbstractPattern::IsModified(), patternReadOnly, and ui.
Referenced by CheckPathToMeasurements(), LoadIndividual(), LoadMultisize(), MainWindow(), SavePattern(), and UnloadMeasurements().
penChanged
void MainWindow::penChanged (Pen pen) slot
Called when something changed in the pen tool bar (e.g. color, weight, or type).
Definition at line 2457 of file mainwindow.cpp.
References MainWindowsNoGUI::doc, and VAbstractPattern::setDefaultPen().
Referenced by initPenToolBar().
Preferences
void MainWindow::Preferences () private slot
Definition at line 6248 of file mainwindow.cpp.
References InitAutoSave(), MainWindowsNoGUI::refreshLabels(), VToolOptionsPropertyBrowser::refreshOptions(), resetOrigins(), resetPanShortcuts(), VMainGraphicsView::resetScrollAnimations(), VMainGraphicsView::resetScrollBars(), ToolBarStyles(), toolProperties, ui, DialogPreferences::updateProperties(), upDateScenes(), updateToolBarVisibility(), updateViewToolbar(), and VAbstractMainWindow::WindowsLocale().
PrepareSceneList()
void MainWindow::PrepareSceneList () protected virtual
Implements MainWindowsNoGUI.
Definition at line 1788 of file mainwindow.cpp.
References MainWindowsNoGUI::ScenePreview(), MainWindowsNoGUI::scenes, SetLayoutModeActions(), and ui.
ProcessCMD
void MainWindow::ProcessCMD () slot
Definition at line 6966 of file mainwindow.cpp.
References DoExport(), VApplication::IsGUIMode(), MainWindowsNoGUI::isNoScaling, LoadPattern(), qApp, ReopenFilesAfterCrash(), SetHeight(), SetSize(), V_EX_DATAERR, V_EX_NOINPUT, and V_EX_OK.
ReadSettings()
void MainWindow::ReadSettings () private
ReadSettings read setting for app.
Definition at line 4831 of file mainwindow.cpp.
References APP_VERSION, VCommonSettings::GetGeometry(), VSettings::GetGraphicalOutput(), VCommonSettings::GetToolbarsState(), VCommonSettings::GetUndoCount(), VCommonSettings::GetWindowState(), isGroupsDockVisible, isLayoutsDockVisible, isToolboxDockVisible, isToolOptionsDockVisible, qApp, ToolBarStyles(), and ui.
RefreshHistory
void MainWindow::RefreshHistory () signal
Referenced by changeDraftBlock().
ReopenFilesAfterCrash()
void MainWindow::ReopenFilesAfterCrash (QStringList & args) private
Definition at line 6549 of file mainwindow.cpp.
References autosavePrefix, GetUnlokedRestoreFileList(), LoadPattern(), and VDomDocument::SafeCopy().
Referenced by ProcessCMD().
resetOrigins
void MainWindow::resetOrigins () private slot
Definition at line 6224 of file mainwindow.cpp.
References draftScene, VMainGraphicsScene::InitOrigins(), pieceScene, and VMainGraphicsScene::setOriginsVisible().
Referenced by Preferences().
resetPanShortcuts()
void MainWindow::resetPanShortcuts () private
Definition at line 7144 of file mainwindow.cpp.
References qApp, and ui.
Referenced by initToolsToolBar(), and Preferences().
RestoreCurrentScene()
void MainWindow::RestoreCurrentScene () private
RestoreCurrentScene restore scene options after change.
Definition at line 3431 of file mainwindow.cpp.
References MainWindowsNoGUI::currentScene, VMainGraphicsScene::getHorScrollBar(), VMainGraphicsScene::getVerScrollBar(), SCASSERT, VMainGraphicsScene::transform(), ui, and zoomScaleChanged().
Referenced by showDraftMode(), and showPieceMode().
Save
bool MainWindow::Save () private slot
Save save pattern file.
Returns
true for successes saving.
Definition at line 3831 of file mainwindow.cpp.
References autosavePrefix, VAbstractMainWindow::ContinueFormatRewrite(), VAbstractMainWindow::m_curFileFormatVersion, VAbstractMainWindow::m_curFileFormatVersionStr, VPatternConverter::PatternMaxVer, VPatternConverter::PatternMaxVerStr, patternReadOnly, qApp, SaveAs(), and SavePattern().
Referenced by CreateActions(), and MaybeSave().
SaveAs
bool MainWindow::SaveAs () private slot
SaveAs save as pattern file.
Returns
true for successes saving.
Definition at line 3711 of file mainwindow.cpp.
References autosavePrefix, MainWindowsNoGUI::doc, VLockGuard< Guarded >::IsLocked(), VAbstractPattern::IsModified(), lock, VAbstractMainWindow::m_curFileFormatVersion, VAbstractMainWindow::m_curFileFormatVersionStr, VPatternConverter::PatternMaxVer, VPatternConverter::PatternMaxVerStr, patternReadOnly, qApp, SavePattern(), VAbstractPattern::SetModified(), and VlpCreateLock().
Referenced by CreateActions(), MaybeSave(), and Save().
SaveCurrentScene()
void MainWindow::SaveCurrentScene () private
SaveCurrentScene save scene options before set another.
Definition at line 3410 of file mainwindow.cpp.
References Calculation, MainWindowsNoGUI::currentScene, mode, Modeling, SCASSERT, VMainGraphicsScene::setCurrentTransform(), VMainGraphicsScene::setHorScrollBar(), VMainGraphicsScene::setVerScrollBar(), and ui.
Referenced by showDraftMode(), showLayoutMode(), and showPieceMode().
SavePattern()
bool MainWindow::SavePattern (const QString & fileName, QString & error) private
SavePattern save pattern file.
Parameters
fileName pattern file name.
Returns
true if all is good.
Definition at line 4737 of file mainwindow.cpp.
References AbsoluteMPath(), MainWindowsNoGUI::doc, helpLabel, VAbstractPattern::MPath(), patternChangesWereSaved(), qApp, RelativeMPath(), VPattern::SaveDocument(), setCurrentFile(), VAbstractPattern::SetMPath(), and VAbstractPattern::UpdatePatternLabel().
Referenced by AutoSavePattern(), Save(), and SaveAs().
selectAllDraftObjectsTool()
void MainWindow::selectAllDraftObjectsTool () const private
Definition at line 7423 of file mainwindow.cpp.
References ByMouseRelease, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), ItemsSelection(), and ui.
Referenced by handleArcIntersectAxisTool(), handleCurveIntersectAxisTool(), handleInternalPathTool(), and handlePatternPieceTool().
selectPieceTool()
void MainWindow::selectPieceTool () const private
Definition at line 7486 of file mainwindow.cpp.
References ByMouseRelease, EnableNodeLabelHover(), EnableNodeLabelSelection(), EnableNodePointHover(), EnableNodePointSelection(), enablePieceHover(), enablePieceSelection(), ItemsSelection(), and ui.
Referenced by handleUnionTool().
setCurrentFile()
void MainWindow::setCurrentFile (const QString & fileName) private
setCurrentFile the function is called to reset the state of a few variables when a file is loaded or saved, or when the user starts editing a new file (in which case fileName is empty).
Parameters
fileName file name.
Definition at line 4794 of file mainwindow.cpp.
References MainWindowsNoGUI::doc, VCommonSettings::GetRecentFileList(), VCommonSettings::GetRestoreFileList(), VApplication::IsGUIMode(), MaxRecentFiles, qApp, VAbstractPattern::SetPatternWasChanged(), VCommonSettings::SetRecentFileList(), VCommonSettings::SetRestoreFileList(), VAbstractPattern::UpdatePatternLabel(), UpdateRecentFileActions(), and UpdateWindowTitle().
Referenced by Clear(), LoadPattern(), and SavePattern().
SetDefaultHeight()
void MainWindow::SetDefaultHeight () private
Definition at line 4498 of file mainwindow.cpp.
References MainWindowsNoGUI::doc, VPattern::GetDefCustomHeight(), gradationHeights, VContainer::height(), and VContainer::SetHeight().
Referenced by initStatusBar().
SetDefaultSize()
void MainWindow::SetDefaultSize () private
Definition at line 4518 of file mainwindow.cpp.
References MainWindowsNoGUI::doc, VPattern::GetDefCustomSize(), gradationSizes, VContainer::SetSize(), and VContainer::size().
Referenced by initStatusBar().
SetGradationList()
QComboBox * MainWindow::SetGradationList (QLabel * label, const QStringList & list) private
Definition at line 2184 of file mainwindow.cpp.
References ui.
Referenced by initStatusBar().
setGuiEnabled
void MainWindow::setGuiEnabled (bool enabled) private slot
Definition at line 4217 of file mainwindow.cpp.
References guiEnabled, handleArrowTool(), qApp, setToolsEnabled(), setWidgetsEnabled(), and ui.
Referenced by changeDraftBlockGlobally(), fullParseFile(), and MainWindow().
SetHeight()
bool MainWindow::SetHeight (const QString & text) private
Definition at line 6923 of file mainwindow.cpp.
References Cm, VContainer::GetPatternUnit(), gradationHeights, VApplication::IsGUIMode(), Multisize, MainWindowsNoGUI::pattern, qApp, and UnitConvertor().
Referenced by ProcessCMD().
SetLayoutModeActions()
void MainWindow::SetLayoutModeActions () private
Definition at line 4707 of file mainwindow.cpp.
References MainWindowsNoGUI::scenes, and ui.
Referenced by CleanLayout(), and PrepareSceneList().
SetSize()
bool MainWindow::SetSize (const QString & text) private
Definition at line 6880 of file mainwindow.cpp.
References Cm, VContainer::GetPatternUnit(), gradationSizes, VApplication::IsGUIMode(), Multisize, MainWindowsNoGUI::pattern, qApp, and UnitConvertor().
Referenced by ProcessCMD().
setToolBarVisibility()
void MainWindow::setToolBarVisibility (QToolBar * toolbar, bool visible) private
Definition at line 2475 of file mainwindow.cpp.
Referenced by updateToolBarVisibility().
SetToolButton()
template<typename Dialog , typename Func > void MainWindow::SetToolButton (bool checked, Tool t, const QString & cursor, const QString & toolTip, Func closeDialogSlot) private
SetToolButton set tool and show dialog.
Parameters
checked true if tool button checked.
t tool type.
cursor path tool cursor icon.
toolTip first tooltipe.
closeDialogSlot function what handle after close dialog.
Definition at line 632 of file mainwindow.cpp.
References AnchorPoint, ArcIntersectAxis, CancelTool(), DialogTool::ChosenObject(), VMainGraphicsScene::ChosenObject(), MainWindowsNoGUI::currentScene, currentTool, DialogTool::DialogClosed(), dialogTool, MainWindowsNoGUI::doc, EnableItemMove(), VPattern::getActivePatternPieces(), helpLabel, InsertNodes, InternalPath, lastUsedTool, Midpoint, MainWindowsNoGUI::pattern, qApp, SCASSERT, DialogTool::SelectedObject(), VMainGraphicsScene::SelectedObject(), ShowToolTip(), DialogTool::ToolTip(), and ui.
SetToolButtonWithApply()
template<typename Dialog , typename Func , typename Func2 > void MainWindow::SetToolButtonWithApply (bool checked, Tool t, const QString & cursor, const QString & toolTip, Func closeDialogSlot, Func2 applyDialogSlot) private
SetToolButtonWithApply set tool and show dialog.
Parameters
checked true if tool button checked.
t tool type.
cursor path tool cursor icon.
toolTip first tooltipe.
closeDialogSlot function to handle close of dialog.
applyDialogSlot function to handle apply in dialog.
Definition at line 703 of file mainwindow.cpp.
References DialogTool::DialogApplied(), and dialogTool.
setToolsEnabled()
void MainWindow::setToolsEnabled (bool enable) private
setToolsEnabled enable button.
Parameters
enable enable value.
Definition at line 4542 of file mainwindow.cpp.
References Calculation, VContainer::DataPieces(), LAST_ONE_DO_NOT_USE, Layout, mode, Modeling, MainWindowsNoGUI::pattern, and ui.
Referenced by addDraftBlock(), Clear(), fullParseFile(), setGuiEnabled(), showDraftMode(), showLayoutMode(), and showPieceMode().
setWidgetsEnabled()
void MainWindow::setWidgetsEnabled (bool enable) private
setWidgetsEnabled enable action button.
Parameters
enable enable value.
Definition at line 4243 of file mainwindow.cpp.
References MainWindowsNoGUI::actionDockWidgetGroups, MainWindowsNoGUI::actionDockWidgetLayouts, MainWindowsNoGUI::actionDockWidgetToolOptions, Calculation, MainWindowsNoGUI::doc, draftBlockComboBox, draftScene, VAbstractPattern::getActiveDraftBlockName(), groupsWidget, Layout, m_zoomToPointComboBox, mode, Modeling, patternReadOnly, qApp, MainWindowsNoGUI::redoAction, GroupsWidget::setAddGroupEnabled(), VMainGraphicsScene::setToolsDisabled(), ui, MainWindowsNoGUI::undoAction, and zoomScaleSpinBox.
Referenced by addDraftBlock(), LoadPattern(), setGuiEnabled(), showDraftMode(), showLayoutMode(), and showPieceMode().
showAllGroups
void MainWindow::showAllGroups () slot
Definition at line 1663 of file mainwindow.cpp.
References groupsWidget, and GroupsWidget::showAllGroups().
showDraftMode
void MainWindow::showDraftMode (bool checked) private slot
showDraftMode show draw scene.
Parameters
checked true - button checked.
Definition at line 3451 of file mainwindow.cpp.
References Calculation, currentBlockIndex, MainWindowsNoGUI::currentScene, currentToolBoxIndex, draftBlockComboBox, draftScene, drawMode, VMainGraphicsScene::enablePiecesMode(), gradationHeights, gradationHeightsLabel, gradationSizes, gradationSizesLabel, groupsWidget, handleArrowTool(), leftGoToStage, mode, Multisize, qApp, RestoreCurrentScene(), rightGoToStage, SaveCurrentScene(), VMainGraphicsScene::setOriginsVisible(), setToolsEnabled(), setWidgetsEnabled(), ui, and updateViewToolbar().
Referenced by Clear(), LoadPattern(), showLayoutMode(), showPieceMode(), WriteSettings(), and zoomFirstShow().
showEvent()
void MainWindow::showEvent (QShowEvent * event) protected virtual
showEvent handle after show window.
Parameters
event show event.
Definition at line 1707 of file mainwindow.cpp.
References isInitialized, and MinimumScrollBar().
showLayoutMode
void MainWindow::showLayoutMode (bool checked) private slot
showLayoutMode show layout scene.
Parameters
checked true - button checked.
Definition at line 3592 of file mainwindow.cpp.
References Calculation, currentBlockIndex, MainWindowsNoGUI::currentScene, currentToolBoxIndex, VContainer::DataPieces(), draftBlockComboBox, drawMode, VException::ErrorMessage(), gradationHeights, gradationHeightsLabel, gradationSizes, gradationSizesLabel, handleArrowTool(), helpLabel, Layout, leftGoToStage, mode, mouseCoordinates, Multisize, MainWindowsNoGUI::pattern, MainWindowsNoGUI::pieceList, MainWindowsNoGUI::pieces, MainWindowsNoGUI::preparePiecesForLayout(), qApp, rightGoToStage, SaveCurrentScene(), MainWindowsNoGUI::scenes, setToolsEnabled(), setWidgetsEnabled(), showDraftMode(), showLayoutPages(), showPieceMode(), MainWindowsNoGUI::tempSceneLayout, and ui.
showLayoutPages
void MainWindow::showLayoutPages (int index) private slot
Definition at line 6233 of file mainwindow.cpp.
References MainWindowsNoGUI::scenes, MainWindowsNoGUI::tempSceneLayout, and ui.
Referenced by showLayoutMode().
ShowMeasurements
void MainWindow::ShowMeasurements () private slot
Definition at line 2004 of file mainwindow.cpp.
References AbsoluteMPath(), Cm, MainWindowsNoGUI::doc, VContainer::height(), MainWindowsNoGUI::isNoScaling, LONG_OPTION_NO_HDPI_SCALING, VAbstractPattern::MPath(), Multisize, VDomDocument::MUnit(), qApp, VContainer::size(), ui, UnitConvertor(), and UnitsToStr().
showPieceMode
void MainWindow::showPieceMode (bool checked) private slot
showPieceMode show Piece scene.
Parameters
checked true - button checked.
Definition at line 3512 of file mainwindow.cpp.
References Calculation, currentBlockIndex, MainWindowsNoGUI::currentScene, currentToolBoxIndex, VContainer::DataPieces(), draftBlockComboBox, drawMode, gradationHeights, gradationHeightsLabel, gradationSizes, gradationSizesLabel, handleArrowTool(), helpLabel, leftGoToStage, mode, Modeling, Multisize, MainWindowsNoGUI::pattern, patternPiecesWidget, pieceScene, qApp, RestoreCurrentScene(), rightGoToStage, SaveCurrentScene(), VMainGraphicsScene::setOriginsVisible(), setToolsEnabled(), setWidgetsEnabled(), showDraftMode(), ui, PiecesWidget::updateList(), and updateViewToolbar().
Referenced by showLayoutMode(), and zoomFirstShow().
ShowToolTip
void MainWindow::ShowToolTip (const QString & toolTip) virtual slot
ShowTool highlight tool.Tip show tools tooltip.
Parameters
toolTip tooltip text.
Definition at line 1649 of file mainwindow.cpp.
References helpLabel.
Referenced by ClosedDialogWithApply(), and SetToolButton().
showZoomToPointDialog
void MainWindow::showZoomToPointDialog () private slot
zoomToPoint show dialog for choosing a point and update the graphics view to focus on it.
Definition at line 2548 of file mainwindow.cpp.
References draftPointNamesList(), and zoomToPoint().
Referenced by initToolsToolBar().
signalZoomPanActive
void MainWindow::signalZoomPanActive (bool enable) const signal
signalZoomToAreaActive
void MainWindow::signalZoomToAreaActive (bool enable) const signal
SyncMeasurements
void MainWindow::SyncMeasurements () private slot
Definition at line 2076 of file mainwindow.cpp.
References AbsoluteMPath(), MainWindowsNoGUI::doc, VContainer::height(), helpLabel, LiteParse, VPattern::LiteParseTree(), mChanges, mChangesAsked, VAbstractPattern::MPath(), VWidgetPopup::PopupMessage(), qApp, VContainer::size(), ui, UpdateMeasurements(), UpdateWindowTitle(), and watcher.
ToolBarStyles
void MainWindow::ToolBarStyles () private slot
Definition at line 6211 of file mainwindow.cpp.
References fontComboBox, fontSizeComboBox, qApp, VAbstractMainWindow::ToolBarStyle(), and ui.
Referenced by Preferences(), and ReadSettings().
ToolSelectArc()
void MainWindow::ToolSelectArc () const private
Definition at line 7345 of file mainwindow.cpp.
References ByMouseRelease, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), ItemsSelection(), and ui.
Referenced by handlePointAlongArcTool(), and handlePointOfIntersectionArcsTool().
ToolSelectCurve()
void MainWindow::ToolSelectCurve () const private
Definition at line 7397 of file mainwindow.cpp.
References ByMouseRelease, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), ItemsSelection(), and ui.
Referenced by handleCurveIntersectCurveTool().
ToolSelectGroupObjects()
void MainWindow::ToolSelectGroupObjects () const private
Definition at line 7475 of file mainwindow.cpp.
References EnableLineHover(), EnableLineSelection(), and ToolSelectOperationObjects().
Referenced by handleGroupTool().
ToolSelectOperationObjects()
void MainWindow::ToolSelectOperationObjects () const private
Definition at line 7449 of file mainwindow.cpp.
References ByMouseRelease, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), ItemsSelection(), and ui.
Referenced by handleInsertNodesTool(), handleMirrorByAxisTool(), handleMirrorByLineTool(), handleMoveTool(), handleRotationTool(), and ToolSelectGroupObjects().
ToolSelectPoint()
void MainWindow::ToolSelectPoint () const private
Definition at line 7255 of file mainwindow.cpp.
References EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), and ui.
Referenced by ToolSelectPointByPress(), and ToolSelectPointByRelease().
ToolSelectPointArc()
void MainWindow::ToolSelectPointArc () const private
Definition at line 7371 of file mainwindow.cpp.
References ByMouseRelease, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), ItemsSelection(), and ui.
Referenced by handlePointFromArcAndTangentTool().
ToolSelectPointByPress()
void MainWindow::ToolSelectPointByPress () const private
Definition at line 7286 of file mainwindow.cpp.
References ByMousePress, ItemsSelection(), and ToolSelectPoint().
Referenced by handleCurveTool(), and handleSplineTool().
ToolSelectPointByRelease()
void MainWindow::ToolSelectPointByRelease () const private
Definition at line 7279 of file mainwindow.cpp.
References ByMouseRelease, ItemsSelection(), and ToolSelectPoint().
Referenced by handleAlongLineTool(), handleAnchorPointTool(), handleArcTool(), handleArcWithLengthTool(), handleBisectorTool(), handleCurveWithControlPointsTool(), handleEllipticalArcTool(), handleHeightTool(), handleLineIntersectAxisTool(), handleLineIntersectTool(), handleLineTool(), handleMidpointTool(), handleNormalTool(), handlePointAtDistanceAngleTool(), handlePointFromCircleAndTangentTool(), handlePointIntersectXYTool(), handlePointOfContactTool(), handlePointOfIntersectionCirclesTool(), handleShoulderPointTool(), handleSplineWithControlPointsTool(), handleTriangleTool(), and handleTrueDartTool().
ToolSelectSpline()
void MainWindow::ToolSelectSpline () const private
Definition at line 7293 of file mainwindow.cpp.
References ByMouseRelease, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), ItemsSelection(), and ui.
Referenced by handlePointAlongCurveTool().
ToolSelectSplinePath()
void MainWindow::ToolSelectSplinePath () const private
Definition at line 7319 of file mainwindow.cpp.
References ByMouseRelease, EnableArcHover(), EnableArcSelection(), EnableElArcHover(), EnableElArcSelection(), EnableLabelHover(), EnableLabelSelection(), EnableLineHover(), EnableLineSelection(), EnablePointHover(), EnablePointSelection(), EnableSplineHover(), EnableSplinePathHover(), EnableSplinePathSelection(), EnableSplineSelection(), ItemsSelection(), and ui.
Referenced by handlePointAlongSplineTool().
UnloadMeasurements
void MainWindow::UnloadMeasurements () private slot
Definition at line 1971 of file mainwindow.cpp.
References AbsoluteMPath(), MainWindowsNoGUI::doc, helpLabel, initStatusBar(), VAbstractPattern::ListMeasurements(), VAbstractPattern::MPath(), Multisize, patternChangesWereSaved(), qApp, VAbstractPattern::SetMPath(), ui, Unknown, VAbstractPattern::UpdatePatternLabel(), UpdateWindowTitle(), and watcher.
unlockAllGroups
void MainWindow::unlockAllGroups () slot
Definition at line 1678 of file mainwindow.cpp.
References groupsWidget, and GroupsWidget::unlockAllGroups().
updateGroups
void MainWindow::updateGroups () virtual slot
triggers the update of the groups
Definition at line 1658 of file mainwindow.cpp.
References groupsWidget, and GroupsWidget::updateGroups().
Referenced by InitDocksContain().
UpdateHeightsList()
void MainWindow::UpdateHeightsList (const QStringList & list) private
Definition at line 4327 of file mainwindow.cpp.
References ChangedHeight(), and gradationHeights.
UpdateMeasurements()
bool MainWindow::UpdateMeasurements (const QString & path, int size, int height) private
Definition at line 550 of file mainwindow.cpp.
References VContainer::ClearVariables(), VExceptionEmptyParameter::DetailedInformation(), MainWindowsNoGUI::doc, VExceptionEmptyParameter::ErrorMessage(), Individual, VApplication::IsGUIMode(), Measurement, Multisize, OpenMeasurementFile(), MainWindowsNoGUI::pattern, qApp, VContainer::SetHeight(), VAbstractPattern::SetPatternWasChanged(), VContainer::SetSize(), MainWindowsNoGUI::SetSizeHeightForIndividualM(), VAbstractPattern::UpdatePatternLabel(), V_EX_DATAERR, and V_EX_NOINPUT.
Referenced by ChangedHeight(), ChangedSize(), and SyncMeasurements().
UpdateRecentFileActions()
void MainWindow::UpdateRecentFileActions () private
Definition at line 4918 of file mainwindow.cpp.
References MaxRecentFiles, qApp, recentFileActs, separatorAct, and strippedName().
Referenced by CreateMenus(), and setCurrentFile().
upDateScenes()
void MainWindow::upDateScenes () private
Definition at line 7121 of file mainwindow.cpp.
References draftScene, and pieceScene.
Referenced by initPointNameToolBar(), and Preferences().
UpdateSizesList()
void MainWindow::UpdateSizesList (const QStringList & list) private
Definition at line 4352 of file mainwindow.cpp.
References ChangedSize(), and gradationSizes.
updateToolBarVisibility()
void MainWindow::updateToolBarVisibility () private
Definition at line 2462 of file mainwindow.cpp.
References qApp, setToolBarVisibility(), and ui.
Referenced by initToolBarVisibility(), and Preferences().
updateViewToolbar()
void MainWindow::updateViewToolbar () private
Definition at line 7134 of file mainwindow.cpp.
References qApp, and ui.
Referenced by Preferences(), showDraftMode(), and showPieceMode().
UpdateWindowTitle()
void MainWindow::UpdateWindowTitle () private
Definition at line 7071 of file mainwindow.cpp.
References darkenPixmap(), GetMeasurementFileName(), GetPatternFileName(), patternReadOnly, qApp, and VER_INTERNALNAME_STR.
Referenced by changeEvent(), LoadIndividual(), LoadMultisize(), MeasurementsChanged(), setCurrentFile(), SyncMeasurements(), and UnloadMeasurements().
updateZoomToPointComboBox()
void MainWindow::updateZoomToPointComboBox (QStringList namesList) private
updateZoomToPointComboBox updates the list of points included in the toolbar combobox.
Definition at line 7246 of file mainwindow.cpp.
References m_zoomToPointComboBox.
Referenced by LoadPattern().
WriteSettings()
void MainWindow::WriteSettings () private
WriteSettings save setting for app.
Definition at line 4860 of file mainwindow.cpp.
References APP_VERSION, qApp, VCommonSettings::SetGeometry(), VCommonSettings::SetToolbarsState(), VCommonSettings::SetWindowState(), and showDraftMode().
Referenced by FileClosedCorrect().
zoomFirstShow()
void MainWindow::zoomFirstShow () private
zoomFirstShow Fit scene size to best size for first show
Definition at line 6781 of file mainwindow.cpp.
References VContainer::DataPieces(), draftScene, VMainGraphicsView::NewSceneRect(), MainWindowsNoGUI::pattern, pieceScene, showDraftMode(), showPieceMode(), ui, and zoomToSelected().
Referenced by LoadPattern().
zoomPan
void MainWindow::zoomPan (bool checked) private slot
Definition at line 2535 of file mainwindow.cpp.
References ui.
Referenced by initToolsToolBar().
zoomScaleChanged
void MainWindow::zoomScaleChanged (qreal scale) private slot
Definition at line 2482 of file mainwindow.cpp.
References zoomScaleSpinBox.
Referenced by exportDraftBlocksAs(), InitScenes(), initToolsToolBar(), RestoreCurrentScene(), and zoomToPrevious().
zoomToArea
void MainWindow::zoomToArea (bool checked) private slot
Definition at line 2524 of file mainwindow.cpp.
References ui.
Referenced by initToolsToolBar().
zoomToPoint
void MainWindow::zoomToPoint (const QString & pointName) private slot
zoomToPoint show dialog for choosing a point and update the graphics view to focus on it.
Parameters
pointName name of to zoom into.
Definition at line 2565 of file mainwindow.cpp.
References VContainer::DataGObjects(), MainWindowsNoGUI::doc, VAbstractPattern::getGroupsContainingItem(), VGObject::getIdObject(), VGObject::getIdTool(), VAbstractPattern::getTool(), groupsWidget, m_zoomToPointComboBox, NULL_ID, MainWindowsNoGUI::pattern, GroupsWidget::showGroups(), VPointF::toQPointF(), and ui.
Referenced by initToolsToolBar(), and showZoomToPointDialog().
zoomToPrevious
void MainWindow::zoomToPrevious () private slot
Definition at line 2512 of file mainwindow.cpp.
References MainWindowsNoGUI::currentScene, SCASSERT, VMainGraphicsScene::swapTransforms(), VMainGraphicsScene::transform(), ui, and zoomScaleChanged().
Referenced by initToolsToolBar().
zoomToSelected
void MainWindow::zoomToSelected () virtual slot
Definition at line 2491 of file mainwindow.cpp.
References VPattern::ActiveDrawBoundingRect(), MainWindowsNoGUI::doc, draftScene, Piece, pieceScene, qApp, and ui.
Referenced by changeDraftBlock(), initToolsToolBar(), and zoomFirstShow().
Member Data Documentation
autoSaveTimer
QTimer* MainWindow::autoSaveTimer private
Definition at line 319 of file mainwindow.h.
Referenced by InitAutoSave().
currentBlockIndex
qint32 MainWindow::currentBlockIndex private
mode stores current draw mode.
Definition at line 305 of file mainwindow.h.
Referenced by showDraftMode(), showLayoutMode(), and showPieceMode().
currentTool
Tool MainWindow::currentTool private
tool current tool
Definition at line 268 of file mainwindow.h.
Referenced by handleArrowTool(), and SetToolButton().
currentToolBoxIndex
qint32 MainWindow::currentToolBoxIndex private
currentBlockIndex current selected draft block.
Definition at line 306 of file mainwindow.h.
Referenced by showDraftMode(), showLayoutMode(), and showPieceMode().
dialogTable
QPointer<DialogVariables> MainWindow::dialogTable private
Definition at line 296 of file mainwindow.h.
dialogTool
QSharedPointer<DialogTool> MainWindow::dialogTool private
Definition at line 297 of file mainwindow.h.
Referenced by ApplyDialog(), ClosedDialog(), ClosedDialogAnchorPoint(), ClosedDialogInternalPath(), ClosedDialogWithApply(), ClosedEditGroupDialog(), ClosedInsertNodesDialog(), EndVisualization(), SetToolButton(), and SetToolButtonWithApply().
draftBlockComboBox
QComboBox* MainWindow::draftBlockComboBox private
Definition at line 302 of file mainwindow.h.
Referenced by addDraftBlock(), changeDraftBlock(), changeDraftBlockGlobally(), Clear(), createDraftBlockName(), draftBlockStartPosition(), fullParseFile(), initDraftToolBar(), New(), setWidgetsEnabled(), showDraftMode(), showLayoutMode(), and showPieceMode().
draftBlockLabel
QLabel* MainWindow::draftBlockLabel private
draftBlockComboBox stores names of draft blocks.
Definition at line 303 of file mainwindow.h.
Referenced by changeEvent(), and initDraftToolBar().
draftScene
VMainGraphicsScene* MainWindow::draftScene private
draftScene draft block scene.
Definition at line 274 of file mainwindow.h.
Referenced by addDraftBlock(), ApplyDrawDialog(), Clear(), ClosedDrawDialogWithApply(), draftBlockStartPosition(), exportDraftBlocksAs(), fullParseFile(), InitScenes(), LoadPattern(), New(), resetOrigins(), setWidgetsEnabled(), showDraftMode(), upDateScenes(), zoomFirstShow(), and zoomToSelected().
drawMode
bool MainWindow::drawMode private
Definition at line 311 of file mainwindow.h.
Referenced by changeDraftBlock(), fullParseFile(), showDraftMode(), showLayoutMode(), and showPieceMode().
fontComboBox
QFontComboBox* MainWindow::fontComboBox private
Definition at line 300 of file mainwindow.h.
Referenced by initPointNameToolBar(), and ToolBarStyles().
fontSizeComboBox
QComboBox* MainWindow::fontSizeComboBox private
Definition at line 301 of file mainwindow.h.
Referenced by initPointNameToolBar(), and ToolBarStyles().
gradationHeights
QPointer<QComboBox> MainWindow::gradationHeights private
Definition at line 321 of file mainwindow.h.
Referenced by ChangedHeight(), initStatusBar(), LoadMultisize(), SetDefaultHeight(), SetHeight(), showDraftMode(), showLayoutMode(), showPieceMode(), and UpdateHeightsList().
gradationHeightsLabel
QPointer<QLabel> MainWindow::gradationHeightsLabel private
Definition at line 323 of file mainwindow.h.
Referenced by initStatusBar(), showDraftMode(), showLayoutMode(), and showPieceMode().
gradationSizes
QPointer<QComboBox> MainWindow::gradationSizes private
Definition at line 322 of file mainwindow.h.
Referenced by ChangedSize(), initStatusBar(), LoadMultisize(), SetDefaultSize(), SetSize(), showDraftMode(), showLayoutMode(), showPieceMode(), and UpdateSizesList().
gradationSizesLabel
QPointer<QLabel> MainWindow::gradationSizesLabel private
Definition at line 324 of file mainwindow.h.
Referenced by initStatusBar(), showDraftMode(), showLayoutMode(), and showPieceMode().
groupsWidget
GroupsWidget* MainWindow::groupsWidget private
Definition at line 326 of file mainwindow.h.
Referenced by addDraftBlock(), addGroupToList(), changeDraftBlock(), CleanLayout(), deleteGroupFromList(), editGroup(), hideAllGroups(), InitDocksContain(), lockAllGroups(), setWidgetsEnabled(), showAllGroups(), showDraftMode(), unlockAllGroups(), updateGroups(), and zoomToPoint().
guiEnabled
bool MainWindow::guiEnabled private
Definition at line 320 of file mainwindow.h.
Referenced by LoadPattern(), MaybeSave(), patternChangesWereSaved(), and setGuiEnabled().
helpLabel
QLabel* MainWindow::helpLabel private
helpLabel help show tooltip.
Definition at line 285 of file mainwindow.h.
Referenced by addDraftBlock(), changeEvent(), handleArrowTool(), LoadIndividual(), LoadMultisize(), LoadPattern(), SavePattern(), SetToolButton(), showLayoutMode(), showPieceMode(), ShowToolTip(), SyncMeasurements(), and UnloadMeasurements().
historyDialog
QPointer<HistoryDialog> MainWindow::historyDialog private
Definition at line 298 of file mainwindow.h.
Referenced by ClosedDialogWithApply().
infoToolButton
QPointer<QToolButton> MainWindow::infoToolButton private
Definition at line 282 of file mainwindow.h.
Referenced by initStatusBar().
isGroupsDockVisible
bool MainWindow::isGroupsDockVisible private
Definition at line 308 of file mainwindow.h.
Referenced by ReadSettings().
isInitialized
bool MainWindow::isInitialized private
isInitialized true after first show window.
Definition at line 288 of file mainwindow.h.
Referenced by showEvent().
isLayoutsDockVisible
bool MainWindow::isLayoutsDockVisible private
Definition at line 309 of file mainwindow.h.
Referenced by ReadSettings().
isToolboxDockVisible
bool MainWindow::isToolboxDockVisible private
Definition at line 310 of file mainwindow.h.
Referenced by ReadSettings().
isToolOptionsDockVisible
bool MainWindow::isToolOptionsDockVisible private
currentToolBoxIndex current set of tools.
Definition at line 307 of file mainwindow.h.
Referenced by ReadSettings().
lastUsedTool
Tool MainWindow::lastUsedTool private
tool last used tool
Definition at line 271 of file mainwindow.h.
Referenced by SetToolButton().
leftGoToStage
QLabel* MainWindow::leftGoToStage private
Definition at line 317 of file mainwindow.h.
Referenced by initModesToolBar(), showDraftMode(), showLayoutMode(), and showPieceMode().
lock
std::shared_ptr<VLockGuard<char> > MainWindow::lock private
Definition at line 328 of file mainwindow.h.
Referenced by Clear(), LoadPattern(), and SaveAs().
m_penReset
PenToolBar* MainWindow::m_penReset private
Definition at line 332 of file mainwindow.h.
m_penToolBar
PenToolBar* MainWindow::m_penToolBar private
for selecting the current pen
Definition at line 331 of file mainwindow.h.
Referenced by initPenToolBar().
m_zoomToPointComboBox
QComboBox* MainWindow::m_zoomToPointComboBox private
Definition at line 333 of file mainwindow.h.
Referenced by initToolsToolBar(), setWidgetsEnabled(), updateZoomToPointComboBox(), and zoomToPoint().
mChanges
bool MainWindow::mChanges private
mChanges true if measurement file was changed.
Definition at line 291 of file mainwindow.h.
Referenced by GetMeasurementFileName(), MeasurementsChanged(), and SyncMeasurements().
mChangesAsked
bool MainWindow::mChangesAsked private
Definition at line 292 of file mainwindow.h.
Referenced by MeasurementsChanged(), and SyncMeasurements().
mode
Draw MainWindow::mode private
Definition at line 304 of file mainwindow.h.
Referenced by SaveCurrentScene(), setToolsEnabled(), setWidgetsEnabled(), showDraftMode(), showLayoutMode(), and showPieceMode().
mouseCoordinates
QPointer<MouseCoordinates> MainWindow::mouseCoordinates private
mouseCoordinates pointer to label who show mouse coordinate.
Definition at line 280 of file mainwindow.h.
Referenced by initStatusBar(), MouseMove(), New(), and showLayoutMode().
patternPiecesWidget
PiecesWidget* MainWindow::patternPiecesWidget private
Definition at line 327 of file mainwindow.h.
Referenced by fullParseFile(), InitDocksContain(), and showPieceMode().
patternReadOnly
bool MainWindow::patternReadOnly private
Definition at line 294 of file mainwindow.h.
Referenced by AutoSavePattern(), LoadPattern(), MaybeSave(), patternChangesWereSaved(), Save(), SaveAs(), setWidgetsEnabled(), and UpdateWindowTitle().
pieceScene
VMainGraphicsScene* MainWindow::pieceScene private
pieceScene pattern piece scene.
Definition at line 277 of file mainwindow.h.
Referenced by addDraftBlock(), applyPiecesDialog(), ChangedHeight(), ChangedSize(), changeEvent(), Clear(), ClosedDialogInternalPath(), ClosedInsertNodesDialog(), ClosedPiecesDialogWithApply(), fullParseFile(), InitDocksContain(), InitScenes(), LoadPattern(), New(), resetOrigins(), showPieceMode(), upDateScenes(), zoomFirstShow(), and zoomToSelected().
recentFileActs
QAction* MainWindow::recentFileActs[MaxRecentFiles] private
Definition at line 314 of file mainwindow.h.
Referenced by CreateMenus(), and UpdateRecentFileActions().
rightGoToStage
QLabel* MainWindow::rightGoToStage private
Definition at line 318 of file mainwindow.h.
Referenced by initModesToolBar(), showDraftMode(), showLayoutMode(), and showPieceMode().
separatorAct
QAction* MainWindow::separatorAct private
Definition at line 315 of file mainwindow.h.
Referenced by CreateMenus(), and UpdateRecentFileActions().
toolProperties
VToolOptionsPropertyBrowser* MainWindow::toolProperties private
Definition at line 325 of file mainwindow.h.
Referenced by changeDraftBlock(), Clear(), CreateMenus(), fullParseFile(), InitDocksContain(), and Preferences().
ui
Ui::MainWindow* MainWindow::ui private
ui keeps information about user interface
Definition at line 263 of file mainwindow.h.
Referenced by AddDocks(), addDraftBlock(), changeEvent(), CleanLayout(), Clear(), ClosedDialog(), ClosedDialogWithApply(), ClosedPiecesDialogWithApply(), CreateActions(), CreateMenus(), exportDraftBlocksAs(), exportLayoutAs(), exportPiecesAs(), fullParseFile(), handleArcsMenu(), handleArrowTool(), handleCurvesMenu(), handleLayoutMenu(), handleLinesMenu(), handleNewLayout(), handleOperationsMenu(), handlePatternPiecesMenu(), handlePieceMenu(), handlePointsMenu(), InitDocksContain(), initDraftToolBar(), initModesToolBar(), initPointNameToolBar(), InitScenes(), initStatusBar(), initToolBarVisibility(), InitToolButtons(), initToolsToolBar(), keyPressEvent(), keyReleaseEvent(), LoadIndividual(), LoadMultisize(), LoadPattern(), MeasurementsChanged(), MinimumScrollBar(), New(), patternChangesWereSaved(), Preferences(), PrepareSceneList(), ReadSettings(), resetPanShortcuts(), RestoreCurrentScene(), SaveCurrentScene(), selectAllDraftObjectsTool(), selectPieceTool(), SetGradationList(), setGuiEnabled(), SetLayoutModeActions(), SetToolButton(), setToolsEnabled(), setWidgetsEnabled(), showDraftMode(), showLayoutMode(), showLayoutPages(), ShowMeasurements(), showPieceMode(), SyncMeasurements(), ToolBarStyles(), ToolSelectArc(), ToolSelectCurve(), ToolSelectOperationObjects(), ToolSelectPoint(), ToolSelectPointArc(), ToolSelectSpline(), ToolSelectSplinePath(), UnloadMeasurements(), updateToolBarVisibility(), updateViewToolbar(), zoomFirstShow(), zoomPan(), zoomToArea(), zoomToPoint(), zoomToPrevious(), zoomToSelected(), and ~MainWindow().
watcher
QFileSystemWatcher* MainWindow::watcher private
Definition at line 265 of file mainwindow.h.
Referenced by Clear(), LoadIndividual(), LoadMultisize(), LoadPattern(), SyncMeasurements(), and UnloadMeasurements().
zoomScaleSpinBox
QDoubleSpinBox* MainWindow::zoomScaleSpinBox private
Definition at line 330 of file mainwindow.h.
Referenced by Clear(), initToolsToolBar(), setWidgetsEnabled(), and zoomScaleChanged().
The documentation for this class was generated from the following files:
src/app/seamly2d/mainwindow.h
src/app/seamly2d/mainwindow.cpp