Seamly2D: VToolArcWithLength Class Reference
VToolArcWithLength Class Reference
#include <vtoolarcwithlength.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::ArcWithLength) }
Public Types inherited from VAbstractSpline
enum { Type = UserType + static_cast<int>(Tool::AbstractSpline) }
Public Member Functions
virtual void setDialog () Q_DECL_OVERRIDE
setDialog set dialog when user want change tool option.
virtual int type () const Q_DECL_OVERRIDE
virtual QString getTagName () const Q_DECL_OVERRIDE
QString CenterPointName () const
quint32 getCenter () const
void setCenter (const quint32 &value)
VFormula GetFormulaRadius () const
void SetFormulaRadius (const VFormula &value)
VFormula GetFormulaF1 () const
void SetFormulaF1 (const VFormula &value)
VFormula GetFormulaLength () const
void SetFormulaLength (const VFormula &value)
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractSpline
VAbstractSpline (VAbstractPattern *doc, VContainer *data, quint32 id, QGraphicsItem *parent=nullptr)
virtual ~VAbstractSpline () Q_DECL_EQ_DEFAULT
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) Q_DECL_OVERRIDE
void ShowHandles (bool show)
QString getLineColor () const
void setLineColor (const QString &value)
QString GetPenStyle () const
void SetPenStyle (const QString &value)
QString getLineWeight () const
getLineWeight return line weight of the spline
void setLineWeight (const QString &value)
setLineWeight set line weight of the spline
QString name () const
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual bool isPointNameVisible (quint32 id) const
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
virtual void setPointNamePosition (quint32 id, const QPointF &pos)
virtual void setPointNameVisiblity (quint32 id, bool visible)
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Static Public Member Functions
static VToolArcWithLength * Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static VToolArcWithLength * Create (const quint32 _id, const quint32 &center, QString &radius, QString &f1, QString &length, const QString &color, const QString &penStyle, const QString &lineWeight, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation)
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString ToolType = QStringLiteral("arcWithLength")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Slots
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID) Q_DECL_OVERRIDE
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Protected Member Functions
virtual void RemoveReferens () Q_DECL_OVERRIDE
RemoveReferens decrement value of reference.
virtual void SaveDialog (QDomElement &domElement) Q_DECL_OVERRIDE
SaveDialog save options into file after change in dialog.
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
virtual void SetVisualization () Q_DECL_OVERRIDE
virtual QString makeToolTip () const Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractSpline
virtual void RefreshGeometry ()
RefreshGeometry refresh item on scene.
virtual void ShowTool (quint32 id, bool enable) Q_DECL_OVERRIDE
ShowTool highlight tool.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
hoverEnterEvent handle hover enter events.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
hoverLeaveEvent handle hover leave events.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) Q_DECL_OVERRIDE
itemChange hadle item change.
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyReleaseEvent handle key release events.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
mouseReleaseEvent handle mouse release events.
virtual void ReadToolAttributes (const QDomElement &domElement) Q_DECL_OVERRIDE
virtual void refreshCtrlPoints ()
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) Q_DECL_OVERRIDE
VSpline CorrectedSpline (const VSpline &spline, const SplinePointPosition &position, const QPointF &pos) const
template<typename T >
void ShowToolVisualization (bool show)
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialogChange () Q_DECL_FINAL
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
void SaveOption (QSharedPointer< VGObject > &obj)
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
virtual void updatePointNameVisibility (quint32 id, bool visible)
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
virtual void ToolCreation (const Source &typeCreation)
Private Member Functions
VToolArcWithLength (VAbstractPattern *doc, VContainer *data, quint32 id, const Source &typeCreation, QGraphicsItem *parent=nullptr)
Additional Inherited Members
Public Slots inherited from VAbstractSpline
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void piecesMode (bool mode) Q_DECL_OVERRIDE
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
Public Slots inherited from VDrawTool
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Signals inherited from VAbstractSpline
void setEnabledPoint (bool enable)
setEnabledPoint disable control points.
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Static Protected Member Functions inherited from VAbstractSpline
template<typename T >
static void InitSplineToolConnections (VMainGraphicsScene *scene, T *tool)
template<typename T >
static void InitSplinePathToolConnections (VMainGraphicsScene *scene, T *tool)
template<typename T >
static void InitArcToolConnections (VMainGraphicsScene *scene, T *tool)
template<typename T >
static void InitElArcToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VAbstractSpline
QVector< VControlPointSpline * > controlPoints
controlPoints list pointers of control points.
SceneObject sceneType
bool m_isHovered
bool m_piecesMode
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Detailed Description
Definition at line 64 of file vtoolarcwithlength.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 79 of file vtoolarcwithlength.h.
Constructor & Destructor Documentation
VToolArcWithLength()
VToolArcWithLength::VToolArcWithLength (VAbstractPattern * doc, VContainer * data, quint32 id, const Source & typeCreation, QGraphicsItem * parent = nullptr) private
Definition at line 85 of file vtoolarcwithlength.cpp.
References Arc, VAbstractSpline::sceneType, and VAbstractTool::ToolCreation().
Referenced by Create().
Member Function Documentation
CenterPointName()
QString VToolArcWithLength::CenterPointName () const
Definition at line 190 of file vtoolarcwithlength.cpp.
References VDataTool::data, getCenter(), and VContainer::GetGObject().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolArcWithLength(), and VToolOptionsPropertyBrowser::updateOptionsToolArcWithLength().
Create() [1/2]
VToolArcWithLength * VToolArcWithLength::Create (const quint32 _id, const quint32 & center, QString & radius, QString & f1, QString & length, const QString & color, const QString & penStyle, const QString & lineWeight, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation) static
Definition at line 138 of file vtoolarcwithlength.cpp.
References VContainer::AddArc(), VContainer::AddGObject(), VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), ArcWithLength, VAbstractTool::CheckFormula(), VDataTool::data, VAbstractTool::doc, FromGui, FullParse, VContainer::GeometricObject(), VGObject::getIdTool(), VAbstractPattern::IncrementReferens(), VAbstractSpline::InitArcToolConnections(), qApp, VContainer::UpdateGObject(), VAbstractPattern::UpdateToolData(), and VToolArcWithLength().
Create() [2/2]
VToolArcWithLength * VToolArcWithLength::Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data) static
Definition at line 114 of file vtoolarcwithlength.cpp.
References VDataTool::data, VAbstractTool::doc, FromGui, FullParse, VInteractiveTool::m_dialog, and SCASSERT.
Referenced by VPattern::ParseToolArcWithLength().
getCenter()
quint32 VToolArcWithLength::getCenter () const
Definition at line 196 of file vtoolarcwithlength.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractTool::m_id, and SCASSERT.
Referenced by CenterPointName().
GetFormulaF1()
VFormula VToolArcWithLength::GetFormulaF1 () const
Definition at line 247 of file vtoolarcwithlength.cpp.
References VDataTool::data, degreeSymbol, VContainer::GeometricObject(), VAbstractTool::getData(), VAbstractTool::m_id, and SCASSERT.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolArcWithLength(), and VToolOptionsPropertyBrowser::updateOptionsToolArcWithLength().
GetFormulaLength()
VFormula VToolArcWithLength::GetFormulaLength () const
Definition at line 276 of file vtoolarcwithlength.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractTool::getData(), VAbstractTool::m_id, qApp, SCASSERT, and UnitsToStr().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolArcWithLength(), and VToolOptionsPropertyBrowser::updateOptionsToolArcWithLength().
GetFormulaRadius()
VFormula VToolArcWithLength::GetFormulaRadius () const
Definition at line 219 of file vtoolarcwithlength.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractTool::getData(), VAbstractTool::m_id, qApp, SCASSERT, and UnitsToStr().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolArcWithLength(), and VToolOptionsPropertyBrowser::updateOptionsToolArcWithLength().
getTagName()
QString VToolArcWithLength::getTagName () const virtual
Reimplemented from VAbstractSpline.
Definition at line 184 of file vtoolarcwithlength.cpp.
References VAbstractPattern::TagArc.
makeToolTip()
QString VToolArcWithLength::makeToolTip () const protected virtual
Reimplemented from VAbstractSpline.
Definition at line 380 of file vtoolarcwithlength.cpp.
References VDataTool::data, VContainer::GeometricObject(), VAbstractTool::m_id, qApp, and UnitsToStr().
RemoveReferens()
void VToolArcWithLength::RemoveReferens () protected virtual
RemoveReferens decrement value of reference.
Reimplemented from VAbstractTool.
Definition at line 323 of file vtoolarcwithlength.cpp.
References VDataTool::data, VAbstractPattern::DecrementReferens(), VAbstractTool::doc, VContainer::GeometricObject(), and VAbstractTool::m_id.
SaveDialog()
void VToolArcWithLength::SaveDialog (QDomElement & domElement) protected virtual
SaveDialog save options into file after change in dialog.
Implements VDrawTool.
Definition at line 330 of file vtoolarcwithlength.cpp.
References AttrAngle1, AttrCenter, AttrColor, AttrLength, AttrLineWeight, AttrPenStyle, AttrRadius, VAbstractTool::doc, VInteractiveTool::m_dialog, SCASSERT, and VDomDocument::SetAttribute().
SaveOptions()
void VToolArcWithLength::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VAbstractSpline.
Definition at line 345 of file vtoolarcwithlength.cpp.
References AttrAngle1, AttrCenter, AttrLength, AttrRadius, AttrType, VAbstractTool::doc, VAbstractSpline::SaveOptions(), SCASSERT, VDomDocument::SetAttribute(), and ToolType.
setCenter()
void VToolArcWithLength::setCenter (const quint32 & value)
Definition at line 205 of file vtoolarcwithlength.cpp.
References VDataTool::data, VContainer::GeometricObject(), VContainer::GetGObject(), VAbstractTool::m_id, NULL_ID, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolArcWithLength().
setDialog()
void VToolArcWithLength::setDialog () virtual
setDialog set dialog when user want change tool option.
Reimplemented from VInteractiveTool.
Definition at line 97 of file vtoolarcwithlength.cpp.
References VDataTool::data, VContainer::GeometricObject(), VInteractiveTool::m_dialog, VAbstractTool::m_id, and SCASSERT.
SetFormulaF1()
void VToolArcWithLength::SetFormulaF1 (const VFormula & value)
Definition at line 260 of file vtoolarcwithlength.cpp.
References VDataTool::data, VFormula::error(), FromUser, VFormula::getDoubleValue(), VFormula::GetFormula(), VContainer::GetGObject(), VAbstractTool::m_id, VDrawTool::SaveOption(), and VFuzzyComparePossibleNulls().
Referenced by VToolOptionsPropertyBrowser::changeDataToolArcWithLength().
SetFormulaLength()
void VToolArcWithLength::SetFormulaLength (const VFormula & value)
Definition at line 289 of file vtoolarcwithlength.cpp.
References VDataTool::data, VFormula::error(), FromUser, VFormula::getDoubleValue(), VFormula::GetFormula(), VContainer::GetGObject(), VAbstractTool::m_id, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolArcWithLength().
SetFormulaRadius()
void VToolArcWithLength::SetFormulaRadius (const VFormula & value)
Definition at line 232 of file vtoolarcwithlength.cpp.
References VDataTool::data, VFormula::error(), FromUser, VFormula::getDoubleValue(), VFormula::GetFormula(), VContainer::GetGObject(), VAbstractTool::m_id, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolArcWithLength().
SetVisualization()
void VToolArcWithLength::SetVisualization () protected virtual
Implements VAbstractTool.
Definition at line 360 of file vtoolarcwithlength.cpp.
References VDataTool::data, VTranslateVars::FormulaToUser(), VContainer::GeometricObject(), lineTypeToPenStyle(), VAbstractTool::m_id, qApp, SCASSERT, and VAbstractTool::vis.
showContextMenu
void VToolArcWithLength::showContextMenu (QGraphicsSceneContextMenuEvent * event, quint32 id = NULL_ID) protected virtual slot
Definition at line 307 of file vtoolarcwithlength.cpp.
ShowVisualization()
void VToolArcWithLength::ShowVisualization (bool show) virtual
Implements VAbstractTool.
Definition at line 301 of file vtoolarcwithlength.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolArcWithLength().
type()
virtual int VToolArcWithLength::type () const inline virtual
Reimplemented from VAbstractSpline.
Definition at line 78 of file vtoolarcwithlength.h.
References Type.
Member Data Documentation
ToolType
const QString VToolArcWithLength::ToolType = QStringLiteral("arcWithLength") static
Definition at line 77 of file vtoolarcwithlength.h.
Referenced by VPattern::ParseArcElement(), and SaveOptions().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/toolcurve/vtoolarcwithlength.h
src/libs/vtools/tools/drawTools/toolcurve/vtoolarcwithlength.cpp