Seamly2D: VArcRadius Class Reference
VArcRadius Class Reference
#include <varcradius.h>
Public Member Functions
VArcRadius ()
VArcRadius (const quint32 &id, const quint32 &parentId, const VArc *arc, Unit patternUnit)
VArcRadius (const quint32 &id, const quint32 &parentId, const VEllipticalArc *elArc, const int numberRadius, Unit patternUnit)
VArcRadius (const VArcRadius &var)
VArcRadius & operator= (const VArcRadius &var)
virtual ~VArcRadius () Q_DECL_OVERRIDE
Public Member Functions inherited from VCurveVariable
VCurveVariable ()
VCurveVariable (const quint32 &id, const quint32 &parentId)
VCurveVariable (const VCurveVariable &var)
virtual ~VCurveVariable () Q_DECL_OVERRIDE
VCurveVariable & operator= (const VCurveVariable &var)
void Swap (VCurveVariable &var) Q_DECL_NOTHROW
virtual bool Filter (quint32 id) Q_DECL_OVERRIDE
quint32 GetId () const
void SetId (const quint32 &id)
quint32 GetParentId () const
void SetParentId (const quint32 &value)
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool isNotUsed () const
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
Definition at line 65 of file varcradius.h.
Constructor & Destructor Documentation
VArcRadius() [1/4]
VArcRadius::VArcRadius ()
Definition at line 62 of file varcradius.cpp.
References ArcRadius, and VInternalVariable::SetType().
VArcRadius() [2/4]
VArcRadius::VArcRadius (const quint32 & id, const quint32 & parentId, const VArc * arc, Unit patternUnit)
Definition at line 69 of file varcradius.cpp.
References ArcRadius, FromPixel(), VArc::GetRadius(), VGObject::name(), radius_V, SCASSERT, VInternalVariable::SetName(), VInternalVariable::SetType(), and VInternalVariable::SetValue().
VArcRadius() [3/4]
VArcRadius::VArcRadius (const quint32 & id, const quint32 & parentId, const VEllipticalArc * elArc, const int numberRadius, Unit patternUnit)
Definition at line 80 of file varcradius.cpp.
References ArcRadius, FromPixel(), VEllipticalArc::GetRadius1(), VEllipticalArc::GetRadius2(), VGObject::name(), radius_V, SCASSERT, VInternalVariable::SetName(), VInternalVariable::SetType(), and VInternalVariable::SetValue().
VArcRadius() [4/4]
VArcRadius::VArcRadius (const VArcRadius & var)
Definition at line 99 of file varcradius.cpp.
~VArcRadius()
VArcRadius::~VArcRadius () virtual
Definition at line 115 of file varcradius.cpp.
Member Function Documentation
operator=()
VArcRadius & VArcRadius::operator= (const VArcRadius & var)
Definition at line 104 of file varcradius.cpp.
References VCurveVariable::operator=().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/varcradius.h
src/libs/vpatterndb/variables/varcradius.cpp