Seamly2D: SavePieceOptions Class Reference
SavePieceOptions Class Reference
#include <savepieceoptions.h>
Public Member Functions
SavePieceOptions (const VPiece &oldPiece, const VPiece &newPiece, VAbstractPattern *doc, quint32 id, QUndoCommand *parent=nullptr)
virtual ~SavePieceOptions ()
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
virtual bool mergeWith (const QUndoCommand *command) Q_DECL_OVERRIDE
virtual int id () const Q_DECL_OVERRIDE
quint32 pieceId () const
VPiece getNewPiece () const
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Attributes
const VPiece m_oldPiece
VPiece m_newPiece
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 61 of file savepieceoptions.h.
Constructor & Destructor Documentation
SavePieceOptions()
SavePieceOptions::SavePieceOptions (const VPiece & oldPiece, const VPiece & newPiece, VAbstractPattern * doc, quint32 id, QUndoCommand * parent = nullptr)
Definition at line 72 of file savepieceoptions.cpp.
References id(), and VUndoCommand::nodeId.
~SavePieceOptions()
SavePieceOptions::~SavePieceOptions () virtual
Definition at line 83 of file savepieceoptions.cpp.
Member Function Documentation
getNewPiece()
VPiece SavePieceOptions::getNewPiece () const inline
Definition at line 90 of file savepieceoptions.h.
References m_newPiece.
Referenced by mergeWith().
id()
int SavePieceOptions::id () const virtual
Definition at line 166 of file savepieceoptions.cpp.
References SavePieceOptions.
Referenced by SavePieceOptions().
mergeWith()
bool SavePieceOptions::mergeWith (const QUndoCommand * command) virtual
Definition at line 150 of file savepieceoptions.cpp.
References getNewPiece(), m_newPiece, VUndoCommand::nodeId, pieceId(), and SCASSERT.
pieceId()
quint32 SavePieceOptions::pieceId () const inline
Definition at line 84 of file savepieceoptions.h.
References VUndoCommand::nodeId.
Referenced by mergeWith().
redo()
void SavePieceOptions::redo () virtual
Definition at line 118 of file savepieceoptions.cpp.
References PatternPieceTool::addAnchors(), PatternPieceTool::AddAttributes(), PatternPieceTool::AddCSARecords(), PatternPieceTool::AddGrainline(), PatternPieceTool::AddInternalPaths(), VAbstractTool::AddNodes(), PatternPieceTool::AddPatternInfo(), PatternPieceTool::AddPatternPieceData(), VUndoCommand::DecrementReferences(), VUndoCommand::doc, VDomDocument::elementById(), VPiece::getAnchors(), VPiece::GetCustomSARecords(), VPiece::GetInternalPaths(), LiteParse, m_newPiece, m_oldPiece, VPiece::missingAnchors(), VPiece::MissingCSAPath(), VPiece::MissingInternalPaths(), VPiece::MissingNodes(), VUndoCommand::NeedLiteParsing(), VUndoCommand::nodeId, VDomDocument::RemoveAllChildren(), and VAbstractPattern::TagPiece.
undo()
void SavePieceOptions::undo () virtual
Definition at line 87 of file savepieceoptions.cpp.
References PatternPieceTool::addAnchors(), PatternPieceTool::AddAttributes(), PatternPieceTool::AddCSARecords(), PatternPieceTool::AddGrainline(), PatternPieceTool::AddInternalPaths(), VAbstractTool::AddNodes(), PatternPieceTool::AddPatternInfo(), PatternPieceTool::AddPatternPieceData(), VUndoCommand::doc, VDomDocument::elementById(), VPiece::getAnchors(), VPiece::GetCustomSARecords(), VPiece::GetInternalPaths(), VUndoCommand::IncrementReferences(), LiteParse, m_newPiece, m_oldPiece, VPiece::missingAnchors(), VPiece::MissingCSAPath(), VPiece::MissingInternalPaths(), VPiece::MissingNodes(), VUndoCommand::NeedLiteParsing(), VUndoCommand::nodeId, VDomDocument::RemoveAllChildren(), and VAbstractPattern::TagPiece.
Member Data Documentation
m_newPiece
VPiece SavePieceOptions::m_newPiece private
Definition at line 80 of file savepieceoptions.h.
Referenced by getNewPiece(), mergeWith(), redo(), and undo().
m_oldPiece
const VPiece SavePieceOptions::m_oldPiece private
Definition at line 79 of file savepieceoptions.h.
Referenced by redo(), and undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/savepieceoptions.h
src/libs/vtools/undocommands/savepieceoptions.cpp