Seamly2D: anonymous_namespace{vpiecepath.cpp} Namespace Reference
anonymous_namespace{vpiecepath.cpp} Namespace Reference
Functions
VSAPoint CurvePoint (VSAPoint candidate, const VContainer *data, const VPieceNode &node, const QVector< QPointF > &curvePoints)
VSAPoint CurveStartPoint (VSAPoint candidate, const VContainer *data, const VPieceNode &node, const QVector< QPointF > &curvePoints)
VSAPoint CurveEndPoint (VSAPoint candidate, const VContainer *data, const VPieceNode &node, const QVector< QPointF > &curvePoints)
int IndexOfNode (const QVector< VPieceNode > &list, quint32 id)
indexOfNode return index in list node using id object.
Function Documentation
CurveEndPoint()
VSAPoint anonymous_namespace{vpiecepath.cpp}::CurveEndPoint (VSAPoint candidate, const VContainer * data, const VPieceNode & node, const QVector< QPointF > & curvePoints)
Definition at line 109 of file vpiecepath.cpp.
References CurvePoint(), VContainer::GeometricObject(), VPieceNode::GetId(), VPieceNode::GetReverse(), VPieceNode::GetTypeTool(), VAbstractCurve::isPointOnCurve(), and NodePoint.
Referenced by VPiecePath::EndSegment().
CurvePoint()
VSAPoint anonymous_namespace{vpiecepath.cpp}::CurvePoint (VSAPoint candidate, const VContainer * data, const VPieceNode & node, const QVector< QPointF > & curvePoints)
Definition at line 64 of file vpiecepath.cpp.
References VContainer::GeometricObject(), VPieceNode::GetAngleType(), VPieceNode::GetId(), VContainer::GetPatternUnit(), VPieceNode::GetSAAfter(), VPieceNode::GetSABefore(), VPieceNode::GetTypeTool(), VAbstractCurve::isPointOnCurve(), NodePoint, VSAPoint::SetAngleType(), VSAPoint::SetSAAfter(), and VSAPoint::SetSABefore().
Referenced by CurveEndPoint(), and CurveStartPoint().
CurveStartPoint()
VSAPoint anonymous_namespace{vpiecepath.cpp}::CurveStartPoint (VSAPoint candidate, const VContainer * data, const VPieceNode & node, const QVector< QPointF > & curvePoints)
Definition at line 82 of file vpiecepath.cpp.
References CurvePoint(), VContainer::GeometricObject(), VPieceNode::GetId(), VPieceNode::GetReverse(), VPieceNode::GetTypeTool(), VAbstractCurve::isPointOnCurve(), and NodePoint.
Referenced by VPiecePath::StartSegment().
IndexOfNode()
int anonymous_namespace{vpiecepath.cpp}::IndexOfNode (const QVector< VPieceNode > & list, quint32 id)
indexOfNode return index in list node using id object.
Parameters
list list nodes detail.
id object (arc, point, spline, splinePath) id.
Returns
index in list or -1 id can't find.
Definition at line 142 of file vpiecepath.cpp.
Referenced by VPiecePath::Edge(), and VPiecePath::OnEdge().