Seamly2D: TST_VSplinePath Class Reference
TST_VSplinePath Class Reference
#include <tst_vsplinepath.h>
Public Member Functions
TST_VSplinePath (QObject *parent=nullptr)
Private Slots
void TestRotation_data ()
void TestRotation ()
void TestFlip_data ()
void TestFlip ()
Detailed Description
Definition at line 57 of file tst_vsplinepath.h.
Constructor & Destructor Documentation
TST_VSplinePath()
TST_VSplinePath::TST_VSplinePath (QObject * parent = nullptr) explicit
Definition at line 59 of file tst_vsplinepath.cpp.
Member Function Documentation
TestFlip
void TST_VSplinePath::TestFlip () private slot
Definition at line 206 of file tst_vsplinepath.cpp.
References VSplinePath::CountPoints(), VAbstractCubicBezierPath::GetLength(), VGObject::name(), and splPath.
TestFlip_data
void TST_VSplinePath::TestFlip_data () private slot
Definition at line 162 of file tst_vsplinepath.cpp.
TestRotation
void TST_VSplinePath::TestRotation () private slot
Definition at line 126 of file tst_vsplinepath.cpp.
References VSplinePoint::Angle1(), VSplinePoint::Angle2(), VSplinePath::CountPoints(), VAbstractCubicBezierPath::GetLength(), VSplinePath::GetSplinePath(), VSplinePoint::Length1(), VSplinePoint::Length2(), VGObject::name(), VSplinePoint::P(), VSplinePath::Rotate(), and VPointF::toQPointF().
TestRotation_data
void TST_VSplinePath::TestRotation_data () private slot
Definition at line 66 of file tst_vsplinepath.cpp.
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vsplinepath.h
src/test/Seamly2DTest/tst_vsplinepath.cpp