Seamly2D: VUndoCommand Class Reference
VUndoCommand Class Reference
#include <vundocommand.h>
Signals
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Public Member Functions
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Protected Member Functions
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 92 of file vundocommand.h.
Constructor & Destructor Documentation
VUndoCommand()
VUndoCommand::VUndoCommand (const QDomElement & xml, VAbstractPattern * doc, QUndoCommand * parent = nullptr)
Definition at line 67 of file vundocommand.cpp.
References SCASSERT.
~VUndoCommand()
virtual VUndoCommand::~VUndoCommand () virtual default
Member Function Documentation
ClearScene
void VUndoCommand::ClearScene () signal
Referenced by VToolBasePoint::AddToFile(), and AddDraftBlock::undo().
DecrementReferences() [1/3]
void VUndoCommand::DecrementReferences (const QVector< CustomSARecord > & nodes) const protected
Definition at line 137 of file vundocommand.cpp.
References DecrementReferences().
DecrementReferences() [2/3]
void VUndoCommand::DecrementReferences (const QVector< quint32 > & nodes) const protected
Definition at line 115 of file vundocommand.cpp.
References VAbstractPattern::DecrementReferens(), and doc.
Referenced by DecrementReferences(), DeletePiece::redo(), SavePieceOptions::redo(), SavePiecePathOptions::redo(), and AddPiece::undo().
DecrementReferences() [3/3]
void VUndoCommand::DecrementReferences (const QVector< VPieceNode > & nodes) const protected
Definition at line 163 of file vundocommand.cpp.
References DecrementReferences().
getDestinationObject()
QDomElement VUndoCommand::getDestinationObject (quint32 idTool, quint32 idPoint) const protected
Definition at line 176 of file vundocommand.cpp.
References AttrIdObject, doc, VDomDocument::elementById(), VDomDocument::GetParametrUInt(), NULL_ID_STR, VAbstractOperation::TagDestination, and VAbstractPattern::TagOperation.
Referenced by ShowOperationPointName::Do(), MoveOperationLabel::Do(), MoveOperationLabel::MoveOperationLabel(), and ShowOperationPointName::ShowOperationPointName().
IncrementReferences() [1/3]
void VUndoCommand::IncrementReferences (const QVector< CustomSARecord > & nodes) const protected
Definition at line 124 of file vundocommand.cpp.
References IncrementReferences().
IncrementReferences() [2/3]
void VUndoCommand::IncrementReferences (const QVector< quint32 > & nodes) const protected
Definition at line 106 of file vundocommand.cpp.
References doc, and VAbstractPattern::IncrementReferens().
Referenced by IncrementReferences(), SavePieceOptions::undo(), and SavePiecePathOptions::undo().
IncrementReferences() [3/3]
void VUndoCommand::IncrementReferences (const QVector< VPieceNode > & nodes) const protected
Definition at line 150 of file vundocommand.cpp.
References IncrementReferences().
NeedFullParsing
void VUndoCommand::NeedFullParsing () signal
Referenced by VDrawTool::AddToCalculation(), VToolBasePoint::AddToFile(), PatternPieceTool::AddToFile(), VAbstractTool::deleteTool(), VToolBasePoint::deleteTool(), PatternPieceTool::deleteTool(), DeleteDraftBlock::redo(), DeletePiece::redo(), DelTool::redo(), RedoFullParsing(), AddToCalc::RedoFullParsing(), AddDraftBlock::undo(), AddPiece::undo(), AddToCalc::undo(), DeleteDraftBlock::undo(), DeletePiece::undo(), and DelTool::undo().
NeedLiteParsing
void VUndoCommand::NeedLiteParsing (const Document & parse) signal
Referenced by AnchorPointTool::AddToFile(), VToolInternalPath::AddToFile(), VToolSpline::ControlPointChangePosition(), VToolSplinePath::ControlPointChangePosition(), MoveSpline::Do(), MoveSplinePath::Do(), MoveSPoint::Do(), PatternPieceTool::insertNodes(), VToolBasePoint::itemChange(), VToolSpline::mouseMoveEvent(), VToolSplinePath::mouseMoveEvent(), MovePiece::redo(), SavePieceOptions::redo(), SaveToolOptions::redo(), PatternPieceTool::renamePiece(), VDrawTool::SaveDialogChange(), PatternPieceTool::SaveDialogChange(), PatternPieceTool::SaveMoveGrainline(), PatternPieceTool::SaveMovePattern(), PatternPieceTool::saveMovePiece(), VDrawTool::SaveOption(), PatternPieceTool::savePieceRotation(), PatternPieceTool::SaveResizeGrainline(), PatternPieceTool::SaveResizePattern(), PatternPieceTool::saveResizePiece(), PatternPieceTool::SaveRotateGrainline(), PatternPieceTool::SaveRotationPattern(), PatternPieceTool::toggleFlipping(), PatternPieceTool::toggleGrainline(), PatternPieceTool::togglePatternLabel(), PatternPieceTool::togglePieceLabel(), PatternPieceTool::toggleSeamAllowance(), PatternPieceTool::toggleSeamLine(), MovePiece::undo(), SavePieceOptions::undo(), and SaveToolOptions::undo().
RedoFullParsing()
void VUndoCommand::RedoFullParsing () protected virtual
Reimplemented in AddToCalc.
Definition at line 78 of file vundocommand.cpp.
References doc, NeedFullParsing(), and redoFlag.
Referenced by AddDraftBlock::redo(), and AddPiece::redo().
UndoDeleteAfterSibling()
void VUndoCommand::UndoDeleteAfterSibling (QDomNode & parentNode, const quint32 & siblingId) const protected
Definition at line 92 of file vundocommand.cpp.
References doc, VDomDocument::NodeById(), NULL_ID, and xml.
Referenced by DeletePiece::undo(), and DelTool::undo().
Member Data Documentation
doc
VAbstractPattern* VUndoCommand::doc protected
Definition at line 106 of file vundocommand.h.
Referenced by AddDetNode::AddDetNode(), AddGroup::AddGroup(), AddPiece::AddPiece(), AddToCalc::AddToCalc(), RenameDraftBlock::changeName(), DecrementReferences(), DeleteDraftBlock::DeleteDraftBlock(), DeletePiece::DeletePiece(), DelGroup::DelGroup(), DelTool::DelTool(), ShowOperationPointName::Do(), MoveDoubleLabel::Do(), MoveLabel::Do(), MoveOperationLabel::Do(), MoveSpline::Do(), MoveSplinePath::Do(), MoveSPoint::Do(), TogglePieceLock::doCmd(), TogglePieceInLayout::doCmd(), SetPieceColor::doCmd(), getDestinationObject(), AddDetNode::GetModelingSection(), AddPiece::getPiecesElement(), IncrementReferences(), MoveDoubleLabel::MoveDoubleLabel(), MoveLabel::MoveLabel(), MoveOperationLabel::MoveOperationLabel(), MovePiece::MovePiece(), MoveSPoint::MoveSPoint(), AddDraftBlock::redo(), AddGroupItem::redo(), AddGroup::redo(), AddToCalc::redo(), DeleteDraftBlock::redo(), DeletePiece::redo(), DelGroup::redo(), DelTool::redo(), MoveGroupItem::redo(), MovePiece::redo(), RemoveGroupItem::redo(), SavePieceOptions::redo(), SavePiecePathOptions::redo(), SaveToolOptions::redo(), RedoFullParsing(), AddToCalc::RedoFullParsing(), RenameDraftBlock::RenameDraftBlock(), MovePiece::SaveCoordinates(), ShowDoublePointName::setVisibility(), ShowPointName::setVisibility(), ShowDoublePointName::ShowDoublePointName(), ShowOperationPointName::ShowOperationPointName(), ShowPointName::ShowPointName(), AddDraftBlock::undo(), AddGroupItem::undo(), AddDetNode::undo(), AddGroup::undo(), AddPiece::undo(), AddToCalc::undo(), DeleteDraftBlock::undo(), DelGroup::undo(), DelTool::undo(), MoveGroupItem::undo(), MovePiece::undo(), RemoveGroupItem::undo(), SavePieceOptions::undo(), SavePiecePathOptions::undo(), SaveToolOptions::undo(), and UndoDeleteAfterSibling().
nodeId
quint32 VUndoCommand::nodeId protected
Definition at line 107 of file vundocommand.h.
Referenced by AddDetNode::AddDetNode(), AddGroup::AddGroup(), AddGroupItem::AddGroupItem(), AddPiece::AddPiece(), AddToCalc::AddToCalc(), DeletePiece::DeletePiece(), DelGroup::DelGroup(), DelTool::DelTool(), ShowOperationPointName::Do(), MoveDoubleLabel::Do(), MoveLabel::Do(), MoveOperationLabel::Do(), MoveSpline::Do(), MoveSplinePath::Do(), MoveSPoint::Do(), MovePiece::getPieceId(), MoveAbstractLabel::GetPointId(), MoveSpline::getSplineId(), MoveSplinePath::getSplinePathId(), MoveSPoint::getSPointId(), SaveToolOptions::getToolId(), MoveDoubleLabel::mergeWith(), MoveLabel::mergeWith(), MoveOperationLabel::mergeWith(), MovePiece::mergeWith(), MoveSpline::mergeWith(), MoveSplinePath::mergeWith(), MoveSPoint::mergeWith(), SavePieceOptions::mergeWith(), SavePiecePathOptions::mergeWith(), SaveToolOptions::mergeWith(), MoveAbstractLabel::MoveAbstractLabel(), MoveDoubleLabel::MoveDoubleLabel(), MoveLabel::MoveLabel(), MoveOperationLabel::MoveOperationLabel(), MovePiece::MovePiece(), MoveSpline::MoveSpline(), MoveSplinePath::MoveSplinePath(), MoveSPoint::MoveSPoint(), SavePiecePathOptions::PathId(), SavePieceOptions::pieceId(), AddGroupItem::redo(), DeletePiece::redo(), DelGroup::redo(), DelTool::redo(), MovePiece::redo(), RemoveGroupItem::redo(), SavePieceOptions::redo(), SavePiecePathOptions::redo(), SaveToolOptions::redo(), RemoveGroupItem::RemoveGroupItem(), SavePieceOptions::SavePieceOptions(), SavePiecePathOptions::SavePiecePathOptions(), SaveToolOptions::SaveToolOptions(), ShowDoublePointName::setVisibility(), ShowPointName::setVisibility(), ShowDoublePointName::ShowDoublePointName(), ShowOperationPointName::ShowOperationPointName(), ShowPointName::ShowPointName(), AddGroupItem::undo(), AddDetNode::undo(), AddGroup::undo(), AddPiece::undo(), AddToCalc::undo(), MovePiece::undo(), RemoveGroupItem::undo(), SavePieceOptions::undo(), SavePiecePathOptions::undo(), and SaveToolOptions::undo().
redoFlag
bool VUndoCommand::redoFlag protected
Definition at line 108 of file vundocommand.h.
Referenced by MovePiece::redo(), RedoFullParsing(), and AddToCalc::RedoFullParsing().
xml
QDomElement VUndoCommand::xml protected
Definition at line 105 of file vundocommand.h.
Referenced by AddDetNode::AddDetNode(), AddGroup::AddGroup(), AddPiece::AddPiece(), AddToCalc::AddToCalc(), DeletePiece::DeletePiece(), DelGroup::DelGroup(), DelTool::DelTool(), AddDraftBlock::redo(), AddGroupItem::redo(), AddDetNode::redo(), AddGroup::redo(), AddPiece::redo(), AddToCalc::redo(), RemoveGroupItem::redo(), AddGroupItem::undo(), DelGroup::undo(), RemoveGroupItem::undo(), and UndoDeleteAfterSibling().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/vundocommand.h
src/libs/vtools/undocommands/vundocommand.cpp