Seamly2D: AddGroupItem Class Reference
AddGroupItem Class Reference
#include <add_groupitem.h>
Signals
void updateGroups ()
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Public Member Functions
AddGroupItem (const QDomElement &xml, VAbstractPattern *doc, quint32 nodeId, QUndoCommand *parent=nullptr)
virtual ~AddGroupItem ()
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Attributes
const QString m_activeDraftblockName
Additional Inherited Members
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 37 of file add_groupitem.h.
Constructor & Destructor Documentation
AddGroupItem()
AddGroupItem::AddGroupItem (const QDomElement & xml, VAbstractPattern * doc, quint32 nodeId, QUndoCommand * parent = nullptr)
Definition at line 39 of file add_groupitem.cpp.
References VUndoCommand::nodeId.
~AddGroupItem()
AddGroupItem::~AddGroupItem () virtual
Definition at line 48 of file add_groupitem.cpp.
Member Function Documentation
redo()
void AddGroupItem::redo () virtual
Definition at line 101 of file add_groupitem.cpp.
References VAbstractPattern::changeActiveDraftBlock(), VAbstractPattern::createGroups(), VUndoCommand::doc, VDomDocument::elementById(), m_activeDraftblockName, VMainGraphicsView::NewSceneRect(), VUndoCommand::nodeId, VAbstractPattern::parseGroups(), qApp, VAbstractPattern::setCurrentDraftBlock(), VAbstractPattern::SetModified(), VAbstractPattern::TagGroup, updateGroups(), and VUndoCommand::xml.
undo()
void AddGroupItem::undo () virtual
Definition at line 53 of file add_groupitem.cpp.
References VAbstractPattern::changeActiveDraftBlock(), VAbstractPattern::createGroups(), VUndoCommand::doc, VDomDocument::elementById(), VDomDocument::GetParametrUInt(), VAbstractPattern::getTool(), VDataTool::GroupVisibility(), m_activeDraftblockName, VMainGraphicsView::NewSceneRect(), VUndoCommand::nodeId, NULL_ID_STR, VAbstractPattern::parseGroups(), qApp, VAbstractPattern::setCurrentDraftBlock(), VAbstractPattern::SetModified(), VAbstractPattern::TagGroup, updateGroups(), and VUndoCommand::xml.
updateGroups
void AddGroupItem::updateGroups () signal
Referenced by VDrawTool::ContextMenu(), redo(), and undo().
Member Data Documentation
m_activeDraftblockName
const QString AddGroupItem::m_activeDraftblockName private
Definition at line 52 of file add_groupitem.h.
Referenced by redo(), and undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/add_groupitem.h
src/libs/vtools/undocommands/add_groupitem.cpp