Seamly2D: VisToolEllipticalArc Class Reference
VisToolEllipticalArc Class Reference
#include <vistoolellipticalarc.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolEllipticalArc) }
Public Types inherited from VisPath
enum { Type = UserType + static_cast<int>(Vis::Path) }
Public Types inherited from VCurvePathItem
enum { Type = UserType + static_cast<int>(Vis::CurvePathItem) }
Public Member Functions
VisToolEllipticalArc (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolEllipticalArc () Q_DECL_EQ_DEFAULT
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setRadius1 (const QString &expression)
void setRadius2 (const QString &expression)
void setF1 (const QString &expression)
void setF2 (const QString &expression)
void setRotationAngle (const QString &expression)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisPath
VisPath (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisPath ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VCurvePathItem
VCurvePathItem (QGraphicsItem *parent=nullptr)
virtual ~VCurvePathItem ()=default
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
void SetDirectionArrows (const QVector< QPair< QLineF, QLineF >> &arrows)
void SetPoints (const QVector< QPointF > &points)
Private Attributes
VScaledEllipse * arcCenter
qreal radius1
qreal radius2
qreal f1
qreal f2
qreal rotationAngle
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisPath
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
VSimplePoint * GetPoint (QVector< VSimplePoint * > &points, quint32 i, const QColor &color)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Protected Member Functions inherited from VCurvePathItem
virtual void ScalePenWidth ()
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 41 of file vistoolellipticalarc.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 56 of file vistoolellipticalarc.h.
Constructor & Destructor Documentation
VisToolEllipticalArc()
VisToolEllipticalArc::VisToolEllipticalArc (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 43 of file vistoolellipticalarc.cpp.
References arcCenter, Visualization::InitPoint(), and Visualization::mainColor.
~VisToolEllipticalArc()
virtual VisToolEllipticalArc::~VisToolEllipticalArc () virtual
Member Function Documentation
RefreshGeometry()
void VisToolEllipticalArc::RefreshGeometry () virtual
Implements Visualization.
Definition at line 50 of file vistoolellipticalarc.cpp.
References arcCenter, Visualization::data, VAbstractCurve::DirectionArrows(), Visualization::DrawPath(), Visualization::DrawPoint(), f1, f2, VContainer::GeometricObject(), VAbstractCurve::GetPath(), Visualization::lineStyle, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, radius1, radius2, rotationAngle, and Visualization::supportColor.
Referenced by DialogEllipticalArc::SaveData().
setF1()
void VisToolEllipticalArc::setF1 (const QString & expression)
Definition at line 78 of file vistoolellipticalarc.cpp.
References Visualization::data, f1, and Visualization::FindVal().
Referenced by DialogEllipticalArc::SaveData(), and DialogEllipticalArc::SetF1().
setF2()
void VisToolEllipticalArc::setF2 (const QString & expression)
Definition at line 84 of file vistoolellipticalarc.cpp.
References Visualization::data, f2, and Visualization::FindVal().
Referenced by DialogEllipticalArc::SaveData(), and DialogEllipticalArc::SetF2().
setRadius1()
void VisToolEllipticalArc::setRadius1 (const QString & expression)
Definition at line 66 of file vistoolellipticalarc.cpp.
References Visualization::data, Visualization::FindLength(), and radius1.
Referenced by DialogEllipticalArc::SaveData(), and DialogEllipticalArc::SetRadius1().
setRadius2()
void VisToolEllipticalArc::setRadius2 (const QString & expression)
Definition at line 72 of file vistoolellipticalarc.cpp.
References Visualization::data, Visualization::FindLength(), and radius2.
Referenced by DialogEllipticalArc::SaveData(), and DialogEllipticalArc::SetRadius2().
setRotationAngle()
void VisToolEllipticalArc::setRotationAngle (const QString & expression)
Definition at line 90 of file vistoolellipticalarc.cpp.
References Visualization::data, Visualization::FindVal(), and rotationAngle.
Referenced by DialogEllipticalArc::SaveData(), and DialogEllipticalArc::SetRotationAngle().
type()
virtual int VisToolEllipticalArc::type () const inline virtual
Reimplemented from VisPath.
Definition at line 55 of file vistoolellipticalarc.h.
References Type.
Member Data Documentation
arcCenter
VScaledEllipse* VisToolEllipticalArc::arcCenter private
Definition at line 59 of file vistoolellipticalarc.h.
Referenced by RefreshGeometry(), and VisToolEllipticalArc().
f1
qreal VisToolEllipticalArc::f1 private
Definition at line 62 of file vistoolellipticalarc.h.
Referenced by RefreshGeometry(), and setF1().
f2
qreal VisToolEllipticalArc::f2 private
Definition at line 63 of file vistoolellipticalarc.h.
Referenced by RefreshGeometry(), and setF2().
radius1
qreal VisToolEllipticalArc::radius1 private
Definition at line 60 of file vistoolellipticalarc.h.
Referenced by RefreshGeometry(), and setRadius1().
radius2
qreal VisToolEllipticalArc::radius2 private
Definition at line 61 of file vistoolellipticalarc.h.
Referenced by RefreshGeometry(), and setRadius2().
rotationAngle
qreal VisToolEllipticalArc::rotationAngle private
Definition at line 64 of file vistoolellipticalarc.h.
Referenced by RefreshGeometry(), and setRotationAngle().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/path/vistoolellipticalarc.h
src/libs/vtools/visualization/path/vistoolellipticalarc.cpp