Seamly2D: CMStateSet Class Reference
CMStateSet Class Reference
#include <CMStateSet.hpp>
Public Member Functions
CMStateSet (const XMLSize_t bitCount, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
CMStateSet (const CMStateSet &toCopy)
~CMStateSet ()
void operator|= (const CMStateSet &setToOr)
bool operator== (const CMStateSet &setToCompare) const
CMStateSet & operator= (const CMStateSet &srcSet)
XMLSize_t getBitCountInRange (XMLSize_t start, XMLSize_t end) const
bool getBit (const XMLSize_t bitToGet) const
bool isEmpty () const
void setBit (const XMLSize_t bitToSet)
void zeroBits ()
XMLSize_t hashCode () const
CMStateSet (const XMLSize_t bitCount, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
CMStateSet (const CMStateSet &toCopy)
~CMStateSet ()
void operator|= (const CMStateSet &setToOr)
bool operator== (const CMStateSet &setToCompare) const
CMStateSet & operator= (const CMStateSet &srcSet)
XMLSize_t getBitCountInRange (XMLSize_t start, XMLSize_t end) const
bool getBit (const XMLSize_t bitToGet) const
bool isEmpty () const
void setBit (const XMLSize_t bitToSet)
void zeroBits ()
XMLSize_t hashCode () const
CMStateSet (const XMLSize_t bitCount, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
CMStateSet (const CMStateSet &toCopy)
~CMStateSet ()
void operator|= (const CMStateSet &setToOr)
bool operator== (const CMStateSet &setToCompare) const
CMStateSet & operator= (const CMStateSet &srcSet)
XMLSize_t getBitCountInRange (XMLSize_t start, XMLSize_t end) const
bool getBit (const XMLSize_t bitToGet) const
bool isEmpty () const
void setBit (const XMLSize_t bitToSet)
void zeroBits ()
XMLSize_t hashCode () const
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
CMStateSet ()
void allocateChunk (const XMLSize_t index)
void deallocateChunk (const XMLSize_t index)
CMStateSet ()
void allocateChunk (const XMLSize_t index)
void deallocateChunk (const XMLSize_t index)
CMStateSet ()
void allocateChunk (const XMLSize_t index)
void deallocateChunk (const XMLSize_t index)
Private Attributes
XMLSize_t fBitCount
XMLInt32 fBits [4]
CMDynamicBuffer * fDynamicBuffer
Friends
class CMStateSetEnumerator
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 73 of file CMStateSet.hpp.
Constructor & Destructor Documentation
CMStateSet() [1/9]
CMStateSet::CMStateSet (const XMLSize_t bitCount, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 79 of file CMStateSet.hpp.
References MemoryManager::allocate(), CMSTATE_BITFIELD_CHUNK, CMSTATE_CACHED_INT32_SIZE, MemoryManager::deallocate(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
CMStateSet() [2/9]
CMStateSet::CMStateSet (const CMStateSet & toCopy) inline
Definition at line 116 of file CMStateSet.hpp.
References MemoryManager::allocate(), allocateChunk(), CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
~CMStateSet() [1/3]
CMStateSet::~CMStateSet () inline
Definition at line 154 of file CMStateSet.hpp.
References MemoryManager::deallocate(), deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
CMStateSet() [3/9]
CMStateSet::CMStateSet () private
CMStateSet() [4/9]
CMStateSet::CMStateSet (const XMLSize_t bitCount, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 79 of file CMStateSet.hpp.
References MemoryManager::allocate(), CMSTATE_BITFIELD_CHUNK, CMSTATE_CACHED_INT32_SIZE, MemoryManager::deallocate(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
CMStateSet() [5/9]
CMStateSet::CMStateSet (const CMStateSet & toCopy) inline
Definition at line 116 of file CMStateSet.hpp.
References MemoryManager::allocate(), allocateChunk(), CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
~CMStateSet() [2/3]
CMStateSet::~CMStateSet () inline
Definition at line 154 of file CMStateSet.hpp.
References MemoryManager::deallocate(), deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
CMStateSet() [6/9]
CMStateSet::CMStateSet () private
CMStateSet() [7/9]
CMStateSet::CMStateSet (const XMLSize_t bitCount, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 79 of file CMStateSet.hpp.
References MemoryManager::allocate(), CMSTATE_BITFIELD_CHUNK, CMSTATE_CACHED_INT32_SIZE, MemoryManager::deallocate(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
CMStateSet() [8/9]
CMStateSet::CMStateSet (const CMStateSet & toCopy) inline
Definition at line 116 of file CMStateSet.hpp.
References MemoryManager::allocate(), allocateChunk(), CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
~CMStateSet() [3/3]
CMStateSet::~CMStateSet () inline
Definition at line 154 of file CMStateSet.hpp.
References MemoryManager::deallocate(), deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fDynamicBuffer, and CMDynamicBuffer::fMemoryManager.
CMStateSet() [9/9]
CMStateSet::CMStateSet () private
Member Function Documentation
allocateChunk() [1/3]
void CMStateSet::allocateChunk (const XMLSize_t index) inline private
Definition at line 497 of file CMStateSet.hpp.
References MemoryManager::allocate(), CMSTATE_BITFIELD_INT32_SIZE, CMDynamicBuffer::fBitArray, fDynamicBuffer, XMLPlatformUtils::fgSSE2ok, and CMDynamicBuffer::fMemoryManager.
Referenced by CMStateSet(), operator=(), operator|=(), and setBit().
allocateChunk() [2/3]
void CMStateSet::allocateChunk (const XMLSize_t index) inline private
Definition at line 497 of file CMStateSet.hpp.
References MemoryManager::allocate(), CMSTATE_BITFIELD_INT32_SIZE, CMDynamicBuffer::fBitArray, fDynamicBuffer, XMLPlatformUtils::fgSSE2ok, and CMDynamicBuffer::fMemoryManager.
allocateChunk() [3/3]
void CMStateSet::allocateChunk (const XMLSize_t index) inline private
Definition at line 497 of file CMStateSet.hpp.
References MemoryManager::allocate(), CMSTATE_BITFIELD_INT32_SIZE, CMDynamicBuffer::fBitArray, fDynamicBuffer, XMLPlatformUtils::fgSSE2ok, and CMDynamicBuffer::fMemoryManager.
deallocateChunk() [1/3]
void CMStateSet::deallocateChunk (const XMLSize_t index) inline private
Definition at line 507 of file CMStateSet.hpp.
References MemoryManager::deallocate(), CMDynamicBuffer::fBitArray, fDynamicBuffer, XMLPlatformUtils::fgSSE2ok, and CMDynamicBuffer::fMemoryManager.
Referenced by operator=(), zeroBits(), and ~CMStateSet().
deallocateChunk() [2/3]
void CMStateSet::deallocateChunk (const XMLSize_t index) inline private
Definition at line 507 of file CMStateSet.hpp.
References MemoryManager::deallocate(), CMDynamicBuffer::fBitArray, fDynamicBuffer, XMLPlatformUtils::fgSSE2ok, and CMDynamicBuffer::fMemoryManager.
deallocateChunk() [3/3]
void CMStateSet::deallocateChunk (const XMLSize_t index) inline private
Definition at line 507 of file CMStateSet.hpp.
References MemoryManager::deallocate(), CMDynamicBuffer::fBitArray, fDynamicBuffer, XMLPlatformUtils::fgSSE2ok, and CMDynamicBuffer::fMemoryManager.
getBit() [1/3]
bool CMStateSet::getBit (const XMLSize_t bitToGet) const inline
Definition at line 360 of file CMStateSet.hpp.
References XMLExcepts::Bitset_BadIndex, CMSTATE_BITFIELD_CHUNK, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
getBit() [2/3]
bool CMStateSet::getBit (const XMLSize_t bitToGet) const inline
Definition at line 360 of file CMStateSet.hpp.
References XMLExcepts::Bitset_BadIndex, CMSTATE_BITFIELD_CHUNK, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
getBit() [3/3]
bool CMStateSet::getBit (const XMLSize_t bitToGet) const inline
Definition at line 360 of file CMStateSet.hpp.
References XMLExcepts::Bitset_BadIndex, CMSTATE_BITFIELD_CHUNK, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
getBitCountInRange() [1/3]
XMLSize_t CMStateSet::getBitCountInRange (XMLSize_t start, XMLSize_t end) const inline
Definition at line 318 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
getBitCountInRange() [2/3]
XMLSize_t CMStateSet::getBitCountInRange (XMLSize_t start, XMLSize_t end) const inline
Definition at line 318 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
getBitCountInRange() [3/3]
XMLSize_t CMStateSet::getBitCountInRange (XMLSize_t start, XMLSize_t end) const inline
Definition at line 318 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
hashCode() [1/3]
XMLSize_t CMStateSet::hashCode () const inline
Definition at line 464 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
hashCode() [2/3]
XMLSize_t CMStateSet::hashCode () const inline
Definition at line 464 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
hashCode() [3/3]
XMLSize_t CMStateSet::hashCode () const inline
Definition at line 464 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
isEmpty() [1/3]
bool CMStateSet::isEmpty () const inline
Definition at line 388 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
isEmpty() [2/3]
bool CMStateSet::isEmpty () const inline
Definition at line 388 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
isEmpty() [3/3]
bool CMStateSet::isEmpty () const inline
Definition at line 388 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
operator=() [1/3]
CMStateSet& CMStateSet::operator= (const CMStateSet & srcSet) inline
Definition at line 277 of file CMStateSet.hpp.
References allocateChunk(), XMLExcepts::Bitset_NotEqualSize, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
operator=() [2/3]
CMStateSet& CMStateSet::operator= (const CMStateSet & srcSet) inline
Definition at line 277 of file CMStateSet.hpp.
References allocateChunk(), XMLExcepts::Bitset_NotEqualSize, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
operator=() [3/3]
CMStateSet& CMStateSet::operator= (const CMStateSet & srcSet) inline
Definition at line 277 of file CMStateSet.hpp.
References allocateChunk(), XMLExcepts::Bitset_NotEqualSize, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
operator==() [1/3]
bool CMStateSet::operator== (const CMStateSet & setToCompare) const inline
Definition at line 243 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, and fDynamicBuffer.
operator==() [2/3]
bool CMStateSet::operator== (const CMStateSet & setToCompare) const inline
Definition at line 243 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, and fDynamicBuffer.
operator==() [3/3]
bool CMStateSet::operator== (const CMStateSet & setToCompare) const inline
Definition at line 243 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBitCount, fBits, and fDynamicBuffer.
operator|=() [1/3]
void CMStateSet::operator|= (const CMStateSet & setToOr) inline
Definition at line 170 of file CMStateSet.hpp.
References allocateChunk(), CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, fDynamicBuffer, and XMLPlatformUtils::fgSSE2ok.
operator|=() [2/3]
void CMStateSet::operator|= (const CMStateSet & setToOr) inline
Definition at line 170 of file CMStateSet.hpp.
References allocateChunk(), CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, fDynamicBuffer, and XMLPlatformUtils::fgSSE2ok.
operator|=() [3/3]
void CMStateSet::operator|= (const CMStateSet & setToOr) inline
Definition at line 170 of file CMStateSet.hpp.
References allocateChunk(), CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, fDynamicBuffer, and XMLPlatformUtils::fgSSE2ok.
setBit() [1/3]
void CMStateSet::setBit (const XMLSize_t bitToSet) inline
Definition at line 414 of file CMStateSet.hpp.
References allocateChunk(), XMLExcepts::Bitset_BadIndex, CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
Referenced by CMLeaf::calcFirstPos(), and CMLeaf::calcLastPos().
setBit() [2/3]
void CMStateSet::setBit (const XMLSize_t bitToSet) inline
Definition at line 414 of file CMStateSet.hpp.
References allocateChunk(), XMLExcepts::Bitset_BadIndex, CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
setBit() [3/3]
void CMStateSet::setBit (const XMLSize_t bitToSet) inline
Definition at line 414 of file CMStateSet.hpp.
References allocateChunk(), XMLExcepts::Bitset_BadIndex, CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMDynamicBuffer::fBitArray, fBitCount, fBits, fDynamicBuffer, CMDynamicBuffer::fMemoryManager, ThrowXML, and ThrowXMLwithMemMgr.
zeroBits() [1/3]
void CMStateSet::zeroBits () inline
Definition at line 448 of file CMStateSet.hpp.
References CMSTATE_CACHED_INT32_SIZE, deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
Referenced by CMLeaf::calcFirstPos(), and CMLeaf::calcLastPos().
zeroBits() [2/3]
void CMStateSet::zeroBits () inline
Definition at line 448 of file CMStateSet.hpp.
References CMSTATE_CACHED_INT32_SIZE, deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
zeroBits() [3/3]
void CMStateSet::zeroBits () inline
Definition at line 448 of file CMStateSet.hpp.
References CMSTATE_CACHED_INT32_SIZE, deallocateChunk(), CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, fBits, and fDynamicBuffer.
Friends And Related Function Documentation
CMStateSetEnumerator
CMStateSetEnumerator friend
Definition at line 539 of file CMStateSet.hpp.
Member Data Documentation
fBitCount
XMLSize_t CMStateSet::fBitCount private
Definition at line 535 of file CMStateSet.hpp.
Referenced by CMStateSet(), getBit(), operator=(), operator==(), and setBit().
fBits
XMLInt32 CMStateSet::fBits private
Definition at line 536 of file CMStateSet.hpp.
Referenced by CMStateSet(), CMStateSetEnumerator::findNext(), getBit(), getBitCountInRange(), hashCode(), isEmpty(), operator=(), operator==(), operator|=(), setBit(), and zeroBits().
fDynamicBuffer
CMDynamicBuffer * CMStateSet::fDynamicBuffer private
Definition at line 537 of file CMStateSet.hpp.
Referenced by allocateChunk(), CMStateSet(), deallocateChunk(), CMStateSetEnumerator::findNext(), getBit(), getBitCountInRange(), hashCode(), isEmpty(), operator=(), operator==(), operator|=(), setBit(), zeroBits(), and ~CMStateSet().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/common/CMStateSet.hpp