Seamly2D: VPE::VPropertyTreeView Class Reference
VPE::VPropertyTreeView Class Reference
#include <vpropertytreeview.h>
Public Member Functions
VPropertyTreeView (QWidget *parent=nullptr)
Default constructor.
VPropertyTreeView (VPropertyModel *model, QWidget *parent=nullptr)
The destructor, taking a model and setting it to the tree view.
virtual ~VPropertyTreeView () Q_DECL_OVERRIDE
Destructor.
void setRowHeight (int height=0, bool add_to_standard=false)
Sets the height for each row. Set this to 0 in order to let the standard delegate decide.
Protected Member Functions
virtual void init ()
This method is called by the constructors to initialize the view.
VPropertyTreeView (VPropertyTreeViewPrivate *d, bool init_, QWidget *parent=nullptr)
protected constructor
Protected Attributes
VPropertyTreeViewPrivate * d_ptr
The protected data.
Detailed Description
Definition at line 38 of file vpropertytreeview.h.
Constructor & Destructor Documentation
VPropertyTreeView() [1/3]
VPE::VPropertyTreeView::VPropertyTreeView (QWidget * parent = nullptr) explicit
Default constructor.
Definition at line 30 of file vpropertytreeview.cpp.
References init().
VPropertyTreeView() [2/3]
VPE::VPropertyTreeView::VPropertyTreeView (VPropertyModel * model, QWidget * parent = nullptr) explicit
The destructor, taking a model and setting it to the tree view.
Parameters
model The model to set as model for this tree view
Definition at line 36 of file vpropertytreeview.cpp.
References init().
~VPropertyTreeView()
VPE::VPropertyTreeView::~VPropertyTreeView () virtual
Destructor.
Definition at line 56 of file vpropertytreeview.cpp.
VPropertyTreeView() [3/3]
VPE::VPropertyTreeView::VPropertyTreeView (VPropertyTreeViewPrivate * d, bool init_, QWidget * parent = nullptr) protected
protected constructor
Definition at line 47 of file vpropertytreeview.cpp.
References init().
Member Function Documentation
init()
void VPE::VPropertyTreeView::init () protected virtual
This method is called by the constructors to initialize the view.
Definition at line 67 of file vpropertytreeview.cpp.
Referenced by VPropertyTreeView().
setRowHeight()
void VPE::VPropertyTreeView::setRowHeight (int height = 0, bool add_to_standard = false)
Sets the height for each row. Set this to 0 in order to let the standard delegate decide.
Definition at line 62 of file vpropertytreeview.cpp.
Member Data Documentation
d_ptr
VPropertyTreeViewPrivate* VPE::VPropertyTreeView::d_ptr protected
The protected data.
Definition at line 64 of file vpropertytreeview.h.
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/vpropertytreeview.h
src/libs/vpropertyexplorer/vpropertytreeview.cpp