Seamly2D: XMLStringTokenizer Class Reference
XMLStringTokenizer Class Reference
#include <XMLStringTokenizer.hpp>
Public Member Functions
Constructors
XMLStringTokenizer (const XMLCh *const srcStr, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLStringTokenizer (const XMLCh *const srcStr, const XMLCh *const delim, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLStringTokenizer (const XMLCh *const srcStr, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLStringTokenizer (const XMLCh *const srcStr, const XMLCh *const delim, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLStringTokenizer (const XMLCh *const srcStr, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLStringTokenizer (const XMLCh *const srcStr, const XMLCh *const delim, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Destructor.
~XMLStringTokenizer ()
~XMLStringTokenizer ()
~XMLStringTokenizer ()
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Management Function
XMLSize_t fOffset
XMLSize_t fStringLen
XMLCh * fString
const XMLCh * fDelimeters
RefArrayVectorOf< XMLCh > * fTokens
MemoryManager * fMemoryManager
bool hasMoreTokens ()
unsigned int countTokens ()
XMLCh * nextToken ()
bool hasMoreTokens ()
unsigned int countTokens ()
XMLCh * nextToken ()
bool hasMoreTokens ()
unsigned int countTokens ()
XMLCh * nextToken ()
XMLStringTokenizer (const XMLStringTokenizer &)
XMLStringTokenizer & operator= (const XMLStringTokenizer &)
void cleanUp ()
bool isDelimeter (const XMLCh ch)
XMLStringTokenizer (const XMLStringTokenizer &)
XMLStringTokenizer & operator= (const XMLStringTokenizer &)
void cleanUp ()
bool isDelimeter (const XMLCh ch)
XMLStringTokenizer (const XMLStringTokenizer &)
XMLStringTokenizer & operator= (const XMLStringTokenizer &)
void cleanUp ()
bool isDelimeter (const XMLCh ch)
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
The string tokenizer class breaks a string into tokens.
The XMLStringTokenizer methods do not distinguish among identifiers, numbers, and quoted strings, nor do they recognize and skip comments
A XMLStringTokenizer object internally maintains a current position within the string to be tokenized. Some operations advance this current position past the characters processed.
Definition at line 42 of file XMLStringTokenizer.hpp.
Constructor & Destructor Documentation
XMLStringTokenizer() [1/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLCh *const srcStr, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a string tokenizer for the specified string. The tokenizer uses the default delimiter set, which is "\t\n\r\f": the space character, the tab character, the newline character, the carriage-return character, and the form-feed character. Delimiter characters themselves will not be treated as tokens.
Parameters
srcStr The string to be parsed.
manager Pointer to the memory manager to be used to allocate objects.
XMLStringTokenizer() [2/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLCh *const srcStr, const XMLCh *const delim, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a string tokenizer for the specified string. The characters in the delim argument are the delimiters for separating tokens. Delimiter characters themselves will not be treated as tokens.
Parameters
srcStr The string to be parsed.
delim The set of delimiters.
manager Pointer to the memory manager to be used to allocate objects.
~XMLStringTokenizer() [1/3]
XMLStringTokenizer::~XMLStringTokenizer ()
XMLStringTokenizer() [3/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLStringTokenizer &) private
XMLStringTokenizer() [4/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLCh *const srcStr, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a string tokenizer for the specified string. The tokenizer uses the default delimiter set, which is "\t\n\r\f": the space character, the tab character, the newline character, the carriage-return character, and the form-feed character. Delimiter characters themselves will not be treated as tokens.
Parameters
srcStr The string to be parsed.
manager Pointer to the memory manager to be used to allocate objects.
XMLStringTokenizer() [5/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLCh *const srcStr, const XMLCh *const delim, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a string tokenizer for the specified string. The characters in the delim argument are the delimiters for separating tokens. Delimiter characters themselves will not be treated as tokens.
Parameters
srcStr The string to be parsed.
delim The set of delimiters.
manager Pointer to the memory manager to be used to allocate objects.
~XMLStringTokenizer() [2/3]
XMLStringTokenizer::~XMLStringTokenizer ()
XMLStringTokenizer() [6/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLStringTokenizer &) private
XMLStringTokenizer() [7/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLCh *const srcStr, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a string tokenizer for the specified string. The tokenizer uses the default delimiter set, which is "\t\n\r\f": the space character, the tab character, the newline character, the carriage-return character, and the form-feed character. Delimiter characters themselves will not be treated as tokens.
Parameters
srcStr The string to be parsed.
manager Pointer to the memory manager to be used to allocate objects.
XMLStringTokenizer() [8/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLCh *const srcStr, const XMLCh *const delim, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a string tokenizer for the specified string. The characters in the delim argument are the delimiters for separating tokens. Delimiter characters themselves will not be treated as tokens.
Parameters
srcStr The string to be parsed.
delim The set of delimiters.
manager Pointer to the memory manager to be used to allocate objects.
~XMLStringTokenizer() [3/3]
XMLStringTokenizer::~XMLStringTokenizer ()
XMLStringTokenizer() [9/9]
XMLStringTokenizer::XMLStringTokenizer (const XMLStringTokenizer &) private
Member Function Documentation
cleanUp() [1/3]
void XMLStringTokenizer::cleanUp () private
cleanUp() [2/3]
void XMLStringTokenizer::cleanUp () private
cleanUp() [3/3]
void XMLStringTokenizer::cleanUp () private
countTokens() [1/3]
unsigned int XMLStringTokenizer::countTokens () inline
Calculates the number of times that this tokenizer's nextToken method can be called to return a valid token. The current position is not advanced.
Returns the number of tokens remaining in the string using the current delimiter set.
Definition at line 181 of file XMLStringTokenizer.hpp.
References fOffset, fString, fStringLen, and isDelimeter().
countTokens() [2/3]
unsigned int XMLStringTokenizer::countTokens ()
Calculates the number of times that this tokenizer's nextToken method can be called to return a valid token. The current position is not advanced.
Returns the number of tokens remaining in the string using the current delimiter set.
countTokens() [3/3]
unsigned int XMLStringTokenizer::countTokens ()
Calculates the number of times that this tokenizer's nextToken method can be called to return a valid token. The current position is not advanced.
Returns the number of tokens remaining in the string using the current delimiter set.
hasMoreTokens() [1/3]
bool XMLStringTokenizer::hasMoreTokens ()
Tests if there are more tokens available from this tokenizer's string.
Returns true if and only if there is at least one token in the string after the current position; false otherwise.
hasMoreTokens() [2/3]
bool XMLStringTokenizer::hasMoreTokens ()
Tests if there are more tokens available from this tokenizer's string.
Returns true if and only if there is at least one token in the string after the current position; false otherwise.
hasMoreTokens() [3/3]
bool XMLStringTokenizer::hasMoreTokens ()
Tests if there are more tokens available from this tokenizer's string.
Returns true if and only if there is at least one token in the string after the current position; false otherwise.
isDelimeter() [1/3]
bool XMLStringTokenizer::isDelimeter (const XMLCh ch) inline private
Definition at line 172 of file XMLStringTokenizer.hpp.
References fDelimeters, and XMLString::indexOf().
Referenced by countTokens().
isDelimeter() [2/3]
bool XMLStringTokenizer::isDelimeter (const XMLCh ch) private
isDelimeter() [3/3]
bool XMLStringTokenizer::isDelimeter (const XMLCh ch) private
nextToken() [1/3]
XMLCh* XMLStringTokenizer::nextToken ()
Returns the next token from this string tokenizer.
Function allocated, function managed (fafm). The calling function does not need to worry about deleting the returned pointer.
nextToken() [2/3]
XMLCh* XMLStringTokenizer::nextToken ()
Returns the next token from this string tokenizer.
Function allocated, function managed (fafm). The calling function does not need to worry about deleting the returned pointer.
nextToken() [3/3]
XMLCh* XMLStringTokenizer::nextToken ()
Returns the next token from this string tokenizer.
Function allocated, function managed (fafm). The calling function does not need to worry about deleting the returned pointer.
operator=() [1/3]
XMLStringTokenizer& XMLStringTokenizer::operator= (const XMLStringTokenizer &) private
operator=() [2/3]
XMLStringTokenizer& XMLStringTokenizer::operator= (const XMLStringTokenizer &) private
operator=() [3/3]
XMLStringTokenizer& XMLStringTokenizer::operator= (const XMLStringTokenizer &) private
Member Data Documentation
fDelimeters
const XMLCh * XMLStringTokenizer::fDelimeters private
Definition at line 164 of file XMLStringTokenizer.hpp.
Referenced by isDelimeter().
fMemoryManager
MemoryManager * XMLStringTokenizer::fMemoryManager private
Definition at line 166 of file XMLStringTokenizer.hpp.
fOffset
XMLSize_t XMLStringTokenizer::fOffset private
Definition at line 161 of file XMLStringTokenizer.hpp.
Referenced by countTokens().
fString
XMLCh * XMLStringTokenizer::fString private
Definition at line 163 of file XMLStringTokenizer.hpp.
Referenced by countTokens().
fStringLen
XMLSize_t XMLStringTokenizer::fStringLen private
Definition at line 162 of file XMLStringTokenizer.hpp.
Referenced by countTokens().
fTokens
RefArrayVectorOf< XMLCh > * XMLStringTokenizer::fTokens private
Definition at line 165 of file XMLStringTokenizer.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/XMLStringTokenizer.hpp