Seamly2D: VScaledLine Class Reference
VScaledLine Class Reference
#include <scalesceneitems.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual int type () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal getDefaultWidth () const
void setDefaultWidth (const qreal &value)
Private Attributes
qreal m_defaultWidth
Detailed Description
Definition at line 61 of file scalesceneitems.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 69 of file scalesceneitems.h.
Constructor & Destructor Documentation
VScaledLine() [1/2]
VScaledLine::VScaledLine (QGraphicsItem * parent = nullptr) explicit
Definition at line 59 of file scalesceneitems.cpp.
VScaledLine() [2/2]
VScaledLine::VScaledLine (const QLineF & line, QGraphicsItem * parent = nullptr)
Definition at line 65 of file scalesceneitems.cpp.
~VScaledLine()
virtual VScaledLine::~VScaledLine () virtual default
Member Function Documentation
getDefaultWidth()
qreal VScaledLine::getDefaultWidth () const
Definition at line 81 of file scalesceneitems.cpp.
References m_defaultWidth.
paint()
void VScaledLine::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
Definition at line 71 of file scalesceneitems.cpp.
References m_defaultWidth, scaleWidth(), and sceneScale().
setDefaultWidth()
void VScaledLine::setDefaultWidth (const qreal & value)
Definition at line 87 of file scalesceneitems.cpp.
References m_defaultWidth.
Referenced by DoubleLinePointTool::DoubleLinePointTool(), DoubleLinePointTool::hoverEnterEvent(), VToolLinePoint::hoverEnterEvent(), DoubleLinePointTool::hoverLeaveEvent(), VToolLinePoint::hoverLeaveEvent(), VControlPointSpline::init(), DoubleLinePointTool::RefreshGeometry(), VToolLinePoint::RefreshGeometry(), VScenePoint::VScenePoint(), and VToolLinePoint::VToolLinePoint().
type()
virtual int VScaledLine::type () const inline virtual
Reimplemented in VisToolTrueDarts, VisToolTriangle, VisToolShoulderPoint, VisToolPointOfIntersectionArcs, VisToolPointOfContact, VisToolPointFromArcAndTangent, VisToolNormal, VisToolLineIntersectAxis, VisToolLineIntersect, VisToolLine, VisToolHeight, VisToolEndLine, VisToolCurveIntersectAxis, VisToolBisector, VisToolAlongLine, VisLine, PointIntersectXYVisual, VisToolRotation, VisToolMove, VisToolMirrorByLine, VisToolMirrorByAxis, VisOperation, IntersectCircleTangentVisual, IntersectCirclesVisual, and AnchorPointVisual.
Definition at line 68 of file scalesceneitems.h.
References Type.
Member Data Documentation
m_defaultWidth
qreal VScaledLine::m_defaultWidth private
Definition at line 80 of file scalesceneitems.h.
Referenced by getDefaultWidth(), paint(), and setDefaultWidth().
The documentation for this class was generated from the following files:
src/libs/vwidgets/scalesceneitems.h
src/libs/vwidgets/scalesceneitems.cpp