Seamly2D: DialogCutArc Class Reference
DialogCutArc Class Reference
The DialogCutArc class dialog for ToolCutArc.
#include <dialogcutarc.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
void DeployFormulaTextEdit ()
DeployFormulaTextEdit grow or shrink formula input.
void FormulaTextChanged ()
FormulaTextChanged when formula text changes for validation and calc.
void FXLength ()
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogCutArc (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogCutArc create dialog.
virtual ~DialogCutArc () Q_DECL_OVERRIDE
void SetPointName (const QString &value)
SetPointName set name point on arc.
QString GetFormula () const
GetFormula return string with formula length.
void SetFormula (const QString &value)
SetFormula set string with formula length.
quint32 getArcId () const
getArcId return id of arc
void setArcId (const quint32 &value)
setArcId set id of arc
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
virtual void CheckState ()
CheckState enable, when all is correct, or disable, when something wrong, button ok.
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Attributes
Ui::DialogCutArc * ui
ui keeps information about user interface
QString formula
formula string with formula
int formulaBaseHeight
formulaBaseHeight base height defined by dialogui
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
The DialogCutArc class dialog for ToolCutArc.
Definition at line 72 of file dialogcutarc.h.
Constructor & Destructor Documentation
DialogCutArc()
DialogCutArc::DialogCutArc (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
DialogCutArc create dialog.
Parameters
data container with data
parent parent widget
Definition at line 77 of file dialogcutarc.cpp.
References DialogTool::CheckState(), DialogTool::data, DeployFormulaTextEdit(), DialogTool::FillComboBoxArcs(), DialogTool::flagFormula, formulaBaseHeight, FormulaTextChanged(), FXLength(), DialogTool::initializeFormulaUi(), DialogTool::initializeOkCancelApply(), DialogTool::labelEditNamePoint, DialogTool::NamePointChanged(), NewLabel, qApp, ui, and DialogTool::vis.
~DialogCutArc()
DialogCutArc::~DialogCutArc () virtual
Definition at line 142 of file dialogcutarc.cpp.
References ui.
Member Function Documentation
ChosenObject
void DialogCutArc::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
Parameters
id id of point or detail
type type of object
Definition at line 153 of file dialogcutarc.cpp.
References Arc, DialogTool::prepare, DialogTool::SetObject(), ui, and DialogTool::vis.
closeEvent()
void DialogCutArc::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 186 of file dialogcutarc.cpp.
References DialogTool::closeEvent(), and ui.
DeployFormulaTextEdit
void DialogCutArc::DeployFormulaTextEdit () slot
DeployFormulaTextEdit grow or shrink formula input.
Definition at line 136 of file dialogcutarc.cpp.
References DialogTool::DeployFormula(), formulaBaseHeight, and ui.
Referenced by DialogCutArc(), and SetFormula().
FormulaTextChanged
void DialogCutArc::FormulaTextChanged () slot
FormulaTextChanged when formula text changes for validation and calc.
Definition at line 110 of file dialogcutarc.cpp.
References DialogTool::FormulaChangedPlainText().
Referenced by DialogCutArc().
FXLength
void DialogCutArc::FXLength () slot
Definition at line 116 of file dialogcutarc.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), GetFormula(), qApp, EditFormulaDialog::SetFormula(), SetFormula(), EditFormulaDialog::setPostfix(), DialogTool::toolId, and UnitsToStr().
Referenced by DialogCutArc().
getArcId()
quint32 DialogCutArc::getArcId () const
getArcId return id of arc
Returns
id
Definition at line 254 of file dialogcutarc.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
GetFormula()
QString DialogCutArc::GetFormula () const
GetFormula return string with formula length.
Returns
formula
Definition at line 244 of file dialogcutarc.cpp.
References formula, and qApp.
Referenced by FXLength().
SaveData()
void DialogCutArc::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 171 of file dialogcutarc.cpp.
References formula, getArcId(), DialogTool::pointName, VisToolCutArc::RefreshGeometry(), SCASSERT, VisToolCutArc::setLength(), Visualization::setObject1Id(), ui, and DialogTool::vis.
setArcId()
void DialogCutArc::setArcId (const quint32 & value)
setArcId set id of arc
Parameters
value id
Definition at line 197 of file dialogcutarc.cpp.
References SCASSERT, DialogTool::setCurrentArcId(), Visualization::setObject1Id(), ui, and DialogTool::vis.
SetFormula()
void DialogCutArc::SetFormula (const QString & value)
SetFormula set string with formula length.
Parameters
value string with formula
Definition at line 211 of file dialogcutarc.cpp.
References DeployFormulaTextEdit(), formula, DialogTool::MoveCursorToEnd(), qApp, SCASSERT, VisToolCutArc::setLength(), ui, and DialogTool::vis.
Referenced by FXLength().
SetPointName()
void DialogCutArc::SetPointName (const QString & value)
SetPointName set name point on arc.
Parameters
value name
Definition at line 233 of file dialogcutarc.cpp.
References DialogTool::pointName, and ui.
ShowVisualization()
void DialogCutArc::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 130 of file dialogcutarc.cpp.
Member Data Documentation
formula
QString DialogCutArc::formula private
formula string with formula
Definition at line 111 of file dialogcutarc.h.
Referenced by GetFormula(), SaveData(), and SetFormula().
formulaBaseHeight
int DialogCutArc::formulaBaseHeight private
formulaBaseHeight base height defined by dialogui
Definition at line 114 of file dialogcutarc.h.
Referenced by DeployFormulaTextEdit(), and DialogCutArc().
ui
Ui::DialogCutArc* DialogCutArc::ui private
ui keeps information about user interface
Definition at line 108 of file dialogcutarc.h.
Referenced by ChosenObject(), closeEvent(), DeployFormulaTextEdit(), DialogCutArc(), getArcId(), SaveData(), setArcId(), SetFormula(), SetPointName(), and ~DialogCutArc().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogcutarc.h
src/libs/vtools/dialogs/tools/dialogcutarc.cpp