Seamly2D: VTableSearch Class Reference
VTableSearch Class Reference
#include <vtablesearch.h>
Signals
void HasResult (bool state)
Public Member Functions
VTableSearch (QTableWidget *table, QObject *parent=nullptr)
void Find (const QString &term)
void FindPrevious ()
void FindNext ()
void RemoveRow (int row)
void AddRow (int row)
void RefreshList (const QString &term)
Private Member Functions
void Clear ()
void ShowNext (int newIndex)
Private Attributes
QTableWidget * table
int searchIndex
QList< QTableWidgetItem * > searchList
Detailed Description
Definition at line 61 of file vtablesearch.h.
Constructor & Destructor Documentation
VTableSearch()
VTableSearch::VTableSearch (QTableWidget * table, QObject * parent = nullptr) explicit
Definition at line 62 of file vtablesearch.cpp.
Member Function Documentation
AddRow()
void VTableSearch::AddRow (int row)
Definition at line 195 of file vtablesearch.cpp.
References searchIndex, and searchList.
Clear()
void VTableSearch::Clear () private
Definition at line 71 of file vtablesearch.cpp.
References HasResult(), SCASSERT, searchIndex, searchList, and table.
Referenced by Find(), and ShowNext().
Find()
void VTableSearch::Find (const QString & term)
Definition at line 119 of file vtablesearch.cpp.
References Clear(), HasResult(), SCASSERT, searchIndex, searchList, and table.
FindNext()
void VTableSearch::FindNext ()
Definition at line 160 of file vtablesearch.cpp.
References searchIndex, searchList, and ShowNext().
FindPrevious()
void VTableSearch::FindPrevious ()
Definition at line 147 of file vtablesearch.cpp.
References searchIndex, searchList, and ShowNext().
HasResult
void VTableSearch::HasResult (bool state) signal
Referenced by Clear(), Find(), TMainWindow::InitWindow(), and RefreshList().
RefreshList()
void VTableSearch::RefreshList (const QString & term)
Definition at line 217 of file vtablesearch.cpp.
References HasResult(), SCASSERT, searchIndex, searchList, and table.
RemoveRow()
void VTableSearch::RemoveRow (int row)
Definition at line 173 of file vtablesearch.cpp.
References searchIndex, and searchList.
ShowNext()
void VTableSearch::ShowNext (int newIndex) private
Definition at line 100 of file vtablesearch.cpp.
References Clear(), searchIndex, searchList, and table.
Referenced by FindNext(), and FindPrevious().
Member Data Documentation
searchIndex
int VTableSearch::searchIndex private
Definition at line 81 of file vtablesearch.h.
Referenced by AddRow(), Clear(), Find(), FindNext(), FindPrevious(), RefreshList(), RemoveRow(), and ShowNext().
searchList
QList<QTableWidgetItem *> VTableSearch::searchList private
Definition at line 82 of file vtablesearch.h.
Referenced by AddRow(), Clear(), Find(), FindNext(), FindPrevious(), RefreshList(), RemoveRow(), and ShowNext().
table
QTableWidget* VTableSearch::table private
Definition at line 80 of file vtablesearch.h.
Referenced by Clear(), Find(), RefreshList(), and ShowNext().
The documentation for this class was generated from the following files:
src/libs/vmisc/vtablesearch.h
src/libs/vmisc/vtablesearch.cpp