Seamly2D: DialogInternalPath Class Reference
DialogInternalPath Class Reference
#include <dialoginternalpath.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
virtual void ShowDialog (bool click) Q_DECL_OVERRIDE
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogInternalPath (const VContainer *data, quint32 toolId, QWidget *parent=nullptr)
virtual ~DialogInternalPath ()
void EnbleShowMode (bool disable)
VPiecePath GetPiecePath () const
void SetPiecePath (const VPiecePath &path)
quint32 GetPieceId () const
void SetPieceId (quint32 id)
QString getSeamAllowanceWidthFormula () const
void setSeamAllowanceWidthFormula (const QString &formula)
virtual void SetPiecesList (const QVector< quint32 > &list) Q_DECL_OVERRIDE
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void CheckState () Q_DECL_FINAL
CheckState enable, when all is correct, or disable, when something wrong, button ok.
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
virtual void SaveData ()
SaveData Put dialog data in local variables.
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Slots
void ShowContextMenu (const QPoint &pos)
void ListChanged ()
void NameChanged ()
void nodeChanged (int index)
void notchChanged (int index)
void enableDefaultBeforeButton ()
void enableDefaultAfterButton ()
void notchTypeChanged (int id)
void notchSubTypeChanged (int id)
void evaluateDefaultWidth ()
void evaluateBeforeWidth ()
void evaluateAfterWidth ()
void editDefaultSeamAllowanceWidth ()
void editBeforeSeamAllowanceWidth ()
void editAfterSeamAllowanceWidth ()
void defaultWidthChanged ()
void beforeWidthChanged ()
void afterWidthChanged ()
void expandWidthFormulaTextEdit ()
void expandWidthBeforeFormulaTextEdit ()
void expandWidthAfterFormulaTextEdit ()
Private Member Functions
void InitPathTab ()
void InitSeamAllowanceTab ()
void InitNotchesTab ()
void InitPathTypes ()
void initializeNodesList ()
void initializeNotchesList ()
void nodeAngleChanged (int index)
VPiecePath CreatePath () const
bool PathIsValid () const
void ValidObjects (bool value)
void NewItem (const VPieceNode &node)
PiecePathType GetType () const
void SetType (PiecePathType type)
Qt::PenStyle GetPenType () const
void SetPenType (const Qt::PenStyle &type)
bool IsCutPath () const
void SetCutPath (bool value)
QListWidgetItem * getItemById (quint32 id)
quint32 GetLastId () const
void SetCurrentSABefore (const QString &formula)
void setCurrentAfterSeamAllowance (const QString &formula)
void updateNodeBeforeSeamAllowance (const QString &formula)
void updateNodeAfterSeamAllowance (const QString &formula)
QString getSeamAllowanceWidthFormulaBefore () const
QString getSeamAllowanceWidthFormulaAfter () const
void setMoveExclusions ()
Private Attributes
Ui::DialogInternalPath * ui
bool m_showMode
qreal m_saWidth
QTimer * m_timerWidth
QTimer * m_timerWidthBefore
QTimer * m_timerWidthAfter
int m_widthFormula
int m_beforeWidthFormula
int m_afterWidthFormula
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
Definition at line 62 of file dialoginternalpath.h.
Constructor & Destructor Documentation
DialogInternalPath()
DialogInternalPath::DialogInternalPath (const VContainer * data, quint32 toolId, QWidget * parent = nullptr) explicit
Definition at line 64 of file dialoginternalpath.cpp.
References CheckState(), DialogTool::data, DialogTool::flagError, DialogTool::flagName, DialogTool::initializeOkCancel(), InitNotchesTab(), InitPathTab(), InitSeamAllowanceTab(), PathIsValid(), ui, and DialogTool::vis.
~DialogInternalPath()
DialogInternalPath::~DialogInternalPath () virtual
Definition at line 102 of file dialoginternalpath.cpp.
References ui.
Member Function Documentation
afterWidthChanged
void DialogInternalPath::afterWidthChanged () private slot
Definition at line 730 of file dialoginternalpath.cpp.
References DialogTool::flagFormula, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, m_timerWidthAfter, qApp, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by InitSeamAllowanceTab().
beforeWidthChanged
void DialogInternalPath::beforeWidthChanged () private slot
Definition at line 720 of file dialoginternalpath.cpp.
References DialogTool::flagFormula, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, m_timerWidthBefore, qApp, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by InitSeamAllowanceTab().
CheckState()
void DialogInternalPath::CheckState () protected virtual
CheckState enable, when all is correct, or disable, when something wrong, button ok.
Reimplemented from DialogTool.
Definition at line 215 of file dialoginternalpath.cpp.
References DialogTool::flagError, DialogTool::flagName, DialogTool::ok_Button, and SCASSERT.
Referenced by DialogInternalPath(), NameChanged(), and ValidObjects().
ChosenObject
void DialogInternalPath::ChosenObject (quint32 id, const SceneObject & type) virtual slot
Definition at line 116 of file dialoginternalpath.cpp.
References Arc, VPiecePath::CountNodes(), CreatePath(), ElArc, getItemById(), GetLastId(), Line, m_showMode, NewItem(), NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, NULL_ID, PathIsValid(), Piece, Point, DialogTool::prepare, qApp, SCASSERT, Spline, SplinePath, DialogTool::ToolTip(), ui, Unknown, ValidObjects(), and DialogTool::vis.
closeEvent()
void DialogInternalPath::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 237 of file dialoginternalpath.cpp.
References DialogTool::closeEvent(), and ui.
CreatePath()
VPiecePath DialogInternalPath::CreatePath () const private
Definition at line 1175 of file dialoginternalpath.cpp.
References VPiecePath::Append(), GetPenType(), GetType(), InternalPath, IsCutPath(), VPiecePath::SetCutPath(), VPiecePath::SetName(), VPiecePath::SetPenType(), VPiecePath::SetType(), and ui.
Referenced by ChosenObject(), GetPiecePath(), initializeNodesList(), ListChanged(), nodeChanged(), notchChanged(), PathIsValid(), setSeamAllowanceWidthFormula(), and ShowDialog().
defaultWidthChanged
void DialogInternalPath::defaultWidthChanged () private slot
Definition at line 711 of file dialoginternalpath.cpp.
References DialogTool::flagFormula, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, m_timerWidth, qApp, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by InitSeamAllowanceTab().
editAfterSeamAllowanceWidth
void DialogInternalPath::editAfterSeamAllowanceWidth () private slot
Definition at line 696 of file dialoginternalpath.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), getSeamAllowanceWidthFormulaAfter(), qApp, EditFormulaDialog::setCheckLessThanZero(), setCurrentAfterSeamAllowance(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), DialogTool::toolId, and UnitsToStr().
Referenced by InitSeamAllowanceTab().
editBeforeSeamAllowanceWidth
void DialogInternalPath::editBeforeSeamAllowanceWidth () private slot
Definition at line 681 of file dialoginternalpath.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), getSeamAllowanceWidthFormulaBefore(), qApp, EditFormulaDialog::setCheckLessThanZero(), SetCurrentSABefore(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), DialogTool::toolId, and UnitsToStr().
Referenced by InitSeamAllowanceTab().
editDefaultSeamAllowanceWidth
void DialogInternalPath::editDefaultSeamAllowanceWidth () private slot
Definition at line 666 of file dialoginternalpath.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), getSeamAllowanceWidthFormula(), qApp, EditFormulaDialog::setCheckLessThanZero(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), setSeamAllowanceWidthFormula(), DialogTool::toolId, and UnitsToStr().
Referenced by InitSeamAllowanceTab().
enableDefaultAfterButton
void DialogInternalPath::enableDefaultAfterButton () private slot
Definition at line 514 of file dialoginternalpath.cpp.
References currentSeamAllowance, and ui.
Referenced by InitSeamAllowanceTab().
enableDefaultBeforeButton
void DialogInternalPath::enableDefaultBeforeButton () private slot
Definition at line 504 of file dialoginternalpath.cpp.
References currentSeamAllowance, and ui.
Referenced by InitSeamAllowanceTab().
EnbleShowMode()
void DialogInternalPath::EnbleShowMode (bool disable)
Definition at line 108 of file dialoginternalpath.cpp.
References m_showMode, and ui.
evaluateAfterWidth
void DialogInternalPath::evaluateAfterWidth () private slot
Definition at line 648 of file dialoginternalpath.cpp.
References currentSeamAllowance, DialogTool::Eval(), DialogTool::flagFormula, getSeamAllowanceWidthFormulaAfter(), DialogTool::labelEditFormula, qApp, ui, UnitsToStr(), and updateNodeAfterSeamAllowance().
Referenced by evaluateDefaultWidth(), and InitSeamAllowanceTab().
evaluateBeforeWidth
void DialogInternalPath::evaluateBeforeWidth () private slot
Definition at line 630 of file dialoginternalpath.cpp.
References currentSeamAllowance, DialogTool::Eval(), DialogTool::flagFormula, getSeamAllowanceWidthFormulaBefore(), DialogTool::labelEditFormula, qApp, ui, UnitsToStr(), and updateNodeBeforeSeamAllowance().
Referenced by evaluateDefaultWidth(), and InitSeamAllowanceTab().
evaluateDefaultWidth
void DialogInternalPath::evaluateDefaultWidth () private slot
Definition at line 610 of file dialoginternalpath.cpp.
References VContainer::AddVariable(), currentSeamAllowance, DialogTool::data, DialogTool::Eval(), evaluateAfterWidth(), evaluateBeforeWidth(), DialogTool::flagFormula, DialogTool::labelEditFormula, m_saWidth, qApp, ui, and UnitsToStr().
Referenced by InitSeamAllowanceTab().
expandWidthAfterFormulaTextEdit
void DialogInternalPath::expandWidthAfterFormulaTextEdit () private slot
Definition at line 752 of file dialoginternalpath.cpp.
References DialogTool::DeployFormula(), m_afterWidthFormula, and ui.
Referenced by InitSeamAllowanceTab(), and nodeChanged().
expandWidthBeforeFormulaTextEdit
void DialogInternalPath::expandWidthBeforeFormulaTextEdit () private slot
Definition at line 746 of file dialoginternalpath.cpp.
References DialogTool::DeployFormula(), m_beforeWidthFormula, and ui.
Referenced by InitSeamAllowanceTab(), and nodeChanged().
expandWidthFormulaTextEdit
void DialogInternalPath::expandWidthFormulaTextEdit () private slot
Definition at line 740 of file dialoginternalpath.cpp.
References DialogTool::DeployFormula(), m_widthFormula, and ui.
Referenced by InitSeamAllowanceTab(), and setSeamAllowanceWidthFormula().
getItemById()
QListWidgetItem * DialogInternalPath::getItemById (quint32 id) private
Definition at line 1023 of file dialoginternalpath.cpp.
References VPieceNode::GetId(), and ui.
Referenced by ChosenObject(), nodeAngleChanged(), notchSubTypeChanged(), notchTypeChanged(), updateNodeAfterSeamAllowance(), and updateNodeBeforeSeamAllowance().
GetLastId()
quint32 DialogInternalPath::GetLastId () const private
Definition at line 1039 of file dialoginternalpath.cpp.
References VPieceNode::GetId(), NULL_ID, and ui.
Referenced by ChosenObject().
GetPenType()
Qt::PenStyle DialogInternalPath::GetPenType () const private
Definition at line 998 of file dialoginternalpath.cpp.
References DialogTool::GetComboBoxCurrentData(), LineTypeSolidLine, lineTypeToPenStyle(), and ui.
Referenced by CreatePath().
GetPieceId()
quint32 DialogInternalPath::GetPieceId () const
Definition at line 1134 of file dialoginternalpath.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by ShowVisualization().
GetPiecePath()
VPiecePath DialogInternalPath::GetPiecePath () const
Definition at line 950 of file dialoginternalpath.cpp.
References CreatePath().
Referenced by PatternPieceDialog::pathDialogClosed().
getSeamAllowanceWidthFormula()
QString DialogInternalPath::getSeamAllowanceWidthFormula () const
Definition at line 1161 of file dialoginternalpath.cpp.
References qApp, and ui.
Referenced by editDefaultSeamAllowanceWidth().
getSeamAllowanceWidthFormulaAfter()
QString DialogInternalPath::getSeamAllowanceWidthFormulaAfter () const private
Definition at line 1264 of file dialoginternalpath.cpp.
References qApp, and ui.
Referenced by editAfterSeamAllowanceWidth(), and evaluateAfterWidth().
getSeamAllowanceWidthFormulaBefore()
QString DialogInternalPath::getSeamAllowanceWidthFormulaBefore () const private
Definition at line 1256 of file dialoginternalpath.cpp.
References qApp, and ui.
Referenced by editBeforeSeamAllowanceWidth(), and evaluateBeforeWidth().
GetType()
PiecePathType DialogInternalPath::GetType () const private
Definition at line 979 of file dialoginternalpath.cpp.
References ui.
Referenced by CreatePath(), InitPathTypes(), and PathIsValid().
initializeNodesList()
void DialogInternalPath::initializeNodesList () private
Definition at line 864 of file dialoginternalpath.cpp.
References VPiecePath::at(), VPiecePath::CountNodes(), CreatePath(), VPieceNode::GetId(), DialogTool::getNodeInfo(), VPieceNode::GetTypeTool(), NodeInfo::name, nodeChanged(), NodePoint, and ui.
Referenced by InitSeamAllowanceTab(), and ListChanged().
initializeNotchesList()
void DialogInternalPath::initializeNotchesList () private
Definition at line 897 of file dialoginternalpath.cpp.
References VPieceNode::GetId(), DialogTool::getNodeInfo(), VPieceNode::GetTypeTool(), NodeInfo::icon, VPieceNode::isNotch(), NodeInfo::name, NodePoint, notchChanged(), and ui.
Referenced by InitNotchesTab(), and ListChanged().
InitNotchesTab()
void DialogInternalPath::InitNotchesTab () private
Definition at line 843 of file dialoginternalpath.cpp.
References initializeNotchesList(), notchChanged(), notchSubTypeChanged(), notchTypeChanged(), and ui.
Referenced by DialogInternalPath().
InitPathTab()
void DialogInternalPath::InitPathTab () private
Definition at line 758 of file dialoginternalpath.cpp.
References InitPathTypes(), LineTypeNone, NameChanged(), setMoveExclusions(), ShowContextMenu(), and ui.
Referenced by DialogInternalPath().
InitPathTypes()
void DialogInternalPath::InitPathTypes () private
Definition at line 854 of file dialoginternalpath.cpp.
References CustomSeamAllowance, GetType(), InternalPath, and ui.
Referenced by InitPathTab().
InitSeamAllowanceTab()
void DialogInternalPath::InitSeamAllowanceTab () private
Definition at line 790 of file dialoginternalpath.cpp.
References afterWidthChanged(), beforeWidthChanged(), Cm, defaultWidthChanged(), editAfterSeamAllowanceWidth(), editBeforeSeamAllowanceWidth(), editDefaultSeamAllowanceWidth(), enableDefaultAfterButton(), enableDefaultBeforeButton(), evaluateAfterWidth(), evaluateBeforeWidth(), evaluateDefaultWidth(), expandWidthAfterFormulaTextEdit(), expandWidthBeforeFormulaTextEdit(), expandWidthFormulaTextEdit(), DialogTool::initializeNodeAngles(), initializeNodesList(), m_afterWidthFormula, m_beforeWidthFormula, m_saWidth, m_timerWidth, m_timerWidthAfter, m_timerWidthBefore, m_widthFormula, nodeAngleChanged(), nodeChanged(), DialogTool::plainTextEditFormula, qApp, ui, and UnitConvertor().
Referenced by DialogInternalPath().
IsCutPath()
bool DialogInternalPath::IsCutPath () const private
Definition at line 1011 of file dialoginternalpath.cpp.
References ui.
Referenced by CreatePath().
ListChanged
void DialogInternalPath::ListChanged () private slot
Definition at line 307 of file dialoginternalpath.cpp.
References CreatePath(), initializeNodesList(), initializeNotchesList(), m_showMode, SCASSERT, and DialogTool::vis.
Referenced by nodeAngleChanged(), notchSubTypeChanged(), notchTypeChanged(), setCurrentAfterSeamAllowance(), SetCurrentSABefore(), SetPiecePath(), and ShowContextMenu().
NameChanged
void DialogInternalPath::NameChanged () private slot
Definition at line 322 of file dialoginternalpath.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::flagName, DialogTool::okColor, and ui.
Referenced by InitPathTab().
NewItem()
void DialogInternalPath::NewItem (const VPieceNode & node) private
Definition at line 1250 of file dialoginternalpath.cpp.
References DialogTool::newNodeItem(), and ui.
Referenced by ChosenObject(), and SetPiecePath().
nodeAngleChanged()
void DialogInternalPath::nodeAngleChanged (int index) private
Definition at line 931 of file dialoginternalpath.cpp.
References getItemById(), ListChanged(), VPieceNode::SetAngleType(), and ui.
Referenced by InitSeamAllowanceTab().
nodeChanged
void DialogInternalPath::nodeChanged (int index) private slot
Definition at line 338 of file dialoginternalpath.cpp.
References VPiecePath::at(), CreatePath(), currentSeamAllowance, expandWidthAfterFormulaTextEdit(), expandWidthBeforeFormulaTextEdit(), VPieceNode::GetAngleType(), VPieceNode::GetFormulaSAAfter(), VPieceNode::GetFormulaSABefore(), VPiecePath::indexOfNode(), DialogTool::MoveCursorToEnd(), qApp, and ui.
Referenced by initializeNodesList(), and InitSeamAllowanceTab().
notchChanged
void DialogInternalPath::notchChanged (int index) private slot
Definition at line 414 of file dialoginternalpath.cpp.
References VPiecePath::at(), Bisector, Castle, CreatePath(), Diamond, VPieceNode::getNotchSubType(), VPieceNode::getNotchType(), VPiecePath::indexOfNode(), Intersection, Slit, Straightforward, TNotch, ui, UNotch, VExternal, and VInternal.
Referenced by initializeNotchesList(), and InitNotchesTab().
notchSubTypeChanged
void DialogInternalPath::notchSubTypeChanged (int id) private slot
Definition at line 576 of file dialoginternalpath.cpp.
References Bisector, getItemById(), Intersection, ListChanged(), VPieceNode::setNotchSubType(), Straightforward, and ui.
Referenced by InitNotchesTab().
notchTypeChanged
void DialogInternalPath::notchTypeChanged (int id) private slot
Definition at line 524 of file dialoginternalpath.cpp.
References Castle, Diamond, getItemById(), DialogTool::getNodeInfo(), NodeInfo::icon, ListChanged(), NodeInfo::name, VPieceNode::setNotchType(), Slit, TNotch, ui, UNotch, VExternal, and VInternal.
Referenced by InitNotchesTab().
PathIsValid()
bool DialogInternalPath::PathIsValid () const private
Definition at line 1193 of file dialoginternalpath.cpp.
References CreatePath(), CustomSeamAllowance, DialogTool::data, DialogTool::DialogWarningIcon(), DialogTool::doublePointsExist(), GetType(), DialogTool::isEachPointNameUnique(), DialogTool::isFirstPointSameAsLast(), m_showMode, and ui.
Referenced by ChosenObject(), DialogInternalPath(), SetPiecePath(), and ShowContextMenu().
setCurrentAfterSeamAllowance()
void DialogInternalPath::setCurrentAfterSeamAllowance (const QString & formula) private
Definition at line 1062 of file dialoginternalpath.cpp.
References ListChanged(), and updateNodeAfterSeamAllowance().
Referenced by editAfterSeamAllowanceWidth().
SetCurrentSABefore()
void DialogInternalPath::SetCurrentSABefore (const QString & formula) private
Definition at line 1055 of file dialoginternalpath.cpp.
References ListChanged(), and updateNodeBeforeSeamAllowance().
Referenced by editBeforeSeamAllowanceWidth().
SetCutPath()
void DialogInternalPath::SetCutPath (bool value) private
Definition at line 1017 of file dialoginternalpath.cpp.
References ui.
Referenced by SetPiecePath().
setMoveExclusions()
void DialogInternalPath::setMoveExclusions () private
Definition at line 1272 of file dialoginternalpath.cpp.
References ui.
Referenced by InitPathTab().
SetPenType()
void DialogInternalPath::SetPenType (const Qt::PenStyle & type) private
Definition at line 1004 of file dialoginternalpath.cpp.
References DialogTool::ChangeCurrentData(), PenStyleToLineType(), ui, and DialogTool::vis.
Referenced by SetPiecePath().
SetPieceId()
void DialogInternalPath::SetPieceId (quint32 id)
Definition at line 1140 of file dialoginternalpath.cpp.
References DialogTool::data, VAbstractPiece::GetName(), VContainer::GetPiece(), and ui.
SetPiecePath()
void DialogInternalPath::SetPiecePath (const VPiecePath & path)
Definition at line 956 of file dialoginternalpath.cpp.
References VPiecePath::at(), VPiecePath::CountNodes(), VPiecePath::GetName(), VPiecePath::GetPenType(), VPiecePath::GetType(), VPiecePath::IsCutPath(), ListChanged(), NewItem(), PathIsValid(), SCASSERT, SetCutPath(), VisToolInternalPath::SetPath(), SetPenType(), SetType(), ui, ValidObjects(), and DialogTool::vis.
SetPiecesList()
void DialogInternalPath::SetPiecesList (const QVector< quint32 > & list) virtual
Reimplemented from DialogTool.
Definition at line 1169 of file dialoginternalpath.cpp.
References DialogTool::FillComboBoxPiecesList(), and ui.
setSeamAllowanceWidthFormula()
void DialogInternalPath::setSeamAllowanceWidthFormula (const QString & formula)
Definition at line 1101 of file dialoginternalpath.cpp.
References CreatePath(), expandWidthFormulaTextEdit(), DialogTool::MoveCursorToEnd(), qApp, SCASSERT, VisToolInternalPath::SetPath(), ui, and DialogTool::vis.
Referenced by editDefaultSeamAllowanceWidth().
SetType()
void DialogInternalPath::SetType (PiecePathType type) private
Definition at line 985 of file dialoginternalpath.cpp.
References InternalPath, and ui.
Referenced by SetPiecePath().
ShowContextMenu
void DialogInternalPath::ShowContextMenu (const QPoint & pos) private slot
Definition at line 246 of file dialoginternalpath.cpp.
References DialogTool::getNodeInfo(), VPieceNode::GetReverse(), VPieceNode::GetTypeTool(), NodeInfo::icon, ListChanged(), NodeInfo::name, NodePoint, PathIsValid(), SCASSERT, VPieceNode::SetReverse(), ui, and ValidObjects().
Referenced by InitPathTab().
ShowDialog
void DialogInternalPath::ShowDialog (bool click) virtual slot
Definition at line 192 of file dialoginternalpath.cpp.
References CreatePath(), m_showMode, DialogTool::prepare, SCASSERT, Show, DialogTool::ToolTip(), and DialogTool::vis.
ShowVisualization()
void DialogInternalPath::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 222 of file dialoginternalpath.cpp.
References GetPieceId(), VAbstractPattern::getTool(), m_showMode, SCASSERT, and DialogTool::vis.
updateNodeAfterSeamAllowance()
void DialogInternalPath::updateNodeAfterSeamAllowance (const QString & formula) private
Definition at line 1085 of file dialoginternalpath.cpp.
References getItemById(), VPieceNode::setAfterSAFormula(), and ui.
Referenced by evaluateAfterWidth(), and setCurrentAfterSeamAllowance().
updateNodeBeforeSeamAllowance()
void DialogInternalPath::updateNodeBeforeSeamAllowance (const QString & formula) private
Definition at line 1069 of file dialoginternalpath.cpp.
References getItemById(), VPieceNode::setBeforeSAFormula(), and ui.
Referenced by evaluateBeforeWidth(), and SetCurrentSABefore().
ValidObjects()
void DialogInternalPath::ValidObjects (bool value) private
Definition at line 1243 of file dialoginternalpath.cpp.
References CheckState(), and DialogTool::flagError.
Referenced by ChosenObject(), SetPiecePath(), and ShowContextMenu().
Member Data Documentation
m_afterWidthFormula
int DialogInternalPath::m_afterWidthFormula private
Definition at line 130 of file dialoginternalpath.h.
Referenced by expandWidthAfterFormulaTextEdit(), and InitSeamAllowanceTab().
m_beforeWidthFormula
int DialogInternalPath::m_beforeWidthFormula private
Definition at line 129 of file dialoginternalpath.h.
Referenced by expandWidthBeforeFormulaTextEdit(), and InitSeamAllowanceTab().
m_saWidth
qreal DialogInternalPath::m_saWidth private
Definition at line 122 of file dialoginternalpath.h.
Referenced by evaluateDefaultWidth(), and InitSeamAllowanceTab().
m_showMode
bool DialogInternalPath::m_showMode private
Definition at line 121 of file dialoginternalpath.h.
Referenced by ChosenObject(), EnbleShowMode(), ListChanged(), PathIsValid(), ShowDialog(), and ShowVisualization().
m_timerWidth
QTimer* DialogInternalPath::m_timerWidth private
Definition at line 124 of file dialoginternalpath.h.
Referenced by defaultWidthChanged(), and InitSeamAllowanceTab().
m_timerWidthAfter
QTimer* DialogInternalPath::m_timerWidthAfter private
Definition at line 126 of file dialoginternalpath.h.
Referenced by afterWidthChanged(), and InitSeamAllowanceTab().
m_timerWidthBefore
QTimer* DialogInternalPath::m_timerWidthBefore private
Definition at line 125 of file dialoginternalpath.h.
Referenced by beforeWidthChanged(), and InitSeamAllowanceTab().
m_widthFormula
int DialogInternalPath::m_widthFormula private
Definition at line 128 of file dialoginternalpath.h.
Referenced by expandWidthFormulaTextEdit(), and InitSeamAllowanceTab().
ui
Ui::DialogInternalPath* DialogInternalPath::ui private
Definition at line 120 of file dialoginternalpath.h.
Referenced by afterWidthChanged(), beforeWidthChanged(), ChosenObject(), closeEvent(), CreatePath(), defaultWidthChanged(), DialogInternalPath(), enableDefaultAfterButton(), enableDefaultBeforeButton(), EnbleShowMode(), evaluateAfterWidth(), evaluateBeforeWidth(), evaluateDefaultWidth(), expandWidthAfterFormulaTextEdit(), expandWidthBeforeFormulaTextEdit(), expandWidthFormulaTextEdit(), getItemById(), GetLastId(), GetPenType(), GetPieceId(), getSeamAllowanceWidthFormula(), getSeamAllowanceWidthFormulaAfter(), getSeamAllowanceWidthFormulaBefore(), GetType(), initializeNodesList(), initializeNotchesList(), InitNotchesTab(), InitPathTab(), InitPathTypes(), InitSeamAllowanceTab(), IsCutPath(), NameChanged(), NewItem(), nodeAngleChanged(), nodeChanged(), notchChanged(), notchSubTypeChanged(), notchTypeChanged(), PathIsValid(), SetCutPath(), setMoveExclusions(), SetPenType(), SetPieceId(), SetPiecePath(), SetPiecesList(), setSeamAllowanceWidthFormula(), SetType(), ShowContextMenu(), updateNodeAfterSeamAllowance(), updateNodeBeforeSeamAllowance(), and ~DialogInternalPath().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/piece/dialoginternalpath.h
src/libs/vtools/dialogs/tools/piece/dialoginternalpath.cpp