Seamly2D: PieceFillComboBox Class Reference
PieceFillComboBox Class Reference
#include <fill_combobox.h>
Signals
void fillChangedSignal (const QString &fill)
Public Member Functions
PieceFillComboBox (QWidget *parent=nullptr, const char *name=nullptr)
PieceFillComboBox (int width, int height, QWidget *parent=nullptr, const char *name=nullptr)
virtual ~PieceFillComboBox ()
QString getFill () const
void setFill (const QString &fill)
QPixmap createFillIcon (const int w, const int h, Qt::BrushStyle style)
int getIconWidth ()
int getIconHeight ()
Private Slots
void fillChanged (int index)
Private Member Functions
void init ()
Private Attributes
QString m_currentFill
int m_iconWidth
int m_iconHeight
Detailed Description
A comboBox for choosing a fill pattern.
Definition at line 35 of file fill_combobox.h.
Constructor & Destructor Documentation
PieceFillComboBox() [1/2]
PieceFillComboBox::PieceFillComboBox (QWidget * parent = nullptr, const char * name = nullptr)
Definition at line 41 of file fill_combobox.cpp.
PieceFillComboBox() [2/2]
PieceFillComboBox::PieceFillComboBox (int width, int height, QWidget * parent = nullptr, const char * name = nullptr)
Definition at line 56 of file fill_combobox.cpp.
References init().
~PieceFillComboBox()
PieceFillComboBox::~PieceFillComboBox () virtual
Destructor
Definition at line 70 of file fill_combobox.cpp.
Member Function Documentation
createFillIcon()
QPixmap PieceFillComboBox::createFillIcon (const int w, const int h, Qt::BrushStyle style)
Definition at line 135 of file fill_combobox.cpp.
Referenced by init().
fillChanged
void PieceFillComboBox::fillChanged (int index) private slot
Definition at line 151 of file fill_combobox.cpp.
References fillChangedSignal(), and m_currentFill.
Referenced by init(), and setFill().
fillChangedSignal
void PieceFillComboBox::fillChangedSignal (const QString & fill) signal
Referenced by fillChanged().
getFill()
QString PieceFillComboBox::getFill () const
Definition at line 129 of file fill_combobox.cpp.
References m_currentFill.
getIconHeight()
int PieceFillComboBox::getIconHeight ()
Definition at line 167 of file fill_combobox.cpp.
References m_iconHeight.
getIconWidth()
int PieceFillComboBox::getIconWidth ()
Definition at line 162 of file fill_combobox.cpp.
References m_iconWidth.
init()
void PieceFillComboBox::init () private
Definition at line 75 of file fill_combobox.cpp.
References createFillIcon(), FillBackwardDiagonal, fillChanged(), FillCross, FilldDiagonalCross, FillDense1, FillDense2, FillDense3, FillDense4, FillDense5, FillDense6, FillDense7, FillForwardDiagonal, FillHorizLines, FillNone, FillSolid, FillVertLines, m_iconHeight, and m_iconWidth.
Referenced by PieceFillComboBox().
setFill()
void PieceFillComboBox::setFill (const QString & fill)
Definition at line 117 of file fill_combobox.cpp.
References fillChanged(), and m_currentFill.
Member Data Documentation
m_currentFill
QString PieceFillComboBox::m_currentFill private
Definition at line 60 of file fill_combobox.h.
Referenced by fillChanged(), getFill(), and setFill().
m_iconHeight
int PieceFillComboBox::m_iconHeight private
Definition at line 62 of file fill_combobox.h.
Referenced by getIconHeight(), and init().
m_iconWidth
int PieceFillComboBox::m_iconWidth private
Definition at line 61 of file fill_combobox.h.
Referenced by getIconWidth(), and init().
The documentation for this class was generated from the following files:
src/libs/vwidgets/fill_combobox.h
src/libs/vwidgets/fill_combobox.cpp