Seamly2D: BaseRefVectorOf< TElem > Class Template Reference
BaseRefVectorOf< TElem > Class Template Reference
#include <BaseRefVectorOf.hpp>
Inherits XMemory, XMemory, and XMemory.
Inherited by RefArrayVectorOf< XMLCh >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< XMLCh >, RefVectorOf< Op >, RefVectorOf< ValueStackOf< XMLSize_t > >, RefVectorOf< Token >, RefVectorOf< XMLAttr >, RefVectorOf< RefHashTableOf< XMLCh > >, RefVectorOf< SchemaElementDecl >, RefVectorOf< XMLElementDecl >, RefVectorOf< DatatypeValidator >, RefVectorOf< DOMNormalizer::InScopeNamespaces::Scope >, RefVectorOf< XercesLocationPath >, RefVectorOf< XMLNumber >, RefVectorOf< ENameMap >, RefVectorOf< DOMImplementation >, RefVectorOf< RegxParser::ReferencePosition >, RefVectorOf< XSObject >, RefVectorOf< IC_Field >, RefVectorOf< KVStringPair >, RefVectorOf< SchemaInfo >, RefVectorOf< DOMNode >, RefVectorOf< SchemaAttDef >, RefVectorOf< XPathMatcher >, RefVectorOf< XMLCh >, RefVectorOf< IdentityConstraint >, RefVectorOf< DOMDocumentImpl >, RefVectorOf< XercesStep >, RefVectorOf< TVal >, RefVectorOf< XSNamespaceItem >, RefVectorOf< ValueStore >, RefVectorOf< PSVIAttributeStorage >, RefVectorOf< Op >, RefVectorOf< ValueStackOf< XMLSize_t > >, RefVectorOf< Token >, RefVectorOf< XMLAttr >, RefVectorOf< RefHashTableOf< XMLCh > >, RefVectorOf< SchemaElementDecl >, RefVectorOf< XMLElementDecl >, RefVectorOf< DatatypeValidator >, RefVectorOf< DOMNormalizer::InScopeNamespaces::Scope >, RefVectorOf< XercesLocationPath >, RefVectorOf< XMLNumber >, RefVectorOf< ENameMap >, RefVectorOf< DOMImplementation >, RefVectorOf< RegxParser::ReferencePosition >, RefVectorOf< XSObject >, RefVectorOf< IC_Field >, RefVectorOf< KVStringPair >, RefVectorOf< SchemaInfo >, RefVectorOf< DOMNode >, RefVectorOf< SchemaAttDef >, RefVectorOf< XPathMatcher >, RefVectorOf< XMLCh >, RefVectorOf< IdentityConstraint >, RefVectorOf< DOMDocumentImpl >, RefVectorOf< XercesStep >, RefVectorOf< TVal >, RefVectorOf< XSNamespaceItem >, RefVectorOf< ValueStore >, RefVectorOf< PSVIAttributeStorage >, RefVectorOf< Op >, RefVectorOf< ValueStackOf< XMLSize_t > >, RefVectorOf< Token >, RefVectorOf< XMLAttr >, RefVectorOf< RefHashTableOf< XMLCh > >, RefVectorOf< SchemaElementDecl >, RefVectorOf< XMLElementDecl >, RefVectorOf< DatatypeValidator >, RefVectorOf< DOMNormalizer::InScopeNamespaces::Scope >, RefVectorOf< XercesLocationPath >, RefVectorOf< XMLNumber >, RefVectorOf< ENameMap >, RefVectorOf< DOMImplementation >, RefVectorOf< RegxParser::ReferencePosition >, RefVectorOf< XSObject >, RefVectorOf< IC_Field >, RefVectorOf< KVStringPair >, RefVectorOf< SchemaInfo >, RefVectorOf< DOMNode >, RefVectorOf< SchemaAttDef >, RefVectorOf< XPathMatcher >, RefVectorOf< XMLCh >, RefVectorOf< IdentityConstraint >, RefVectorOf< DOMDocumentImpl >, RefVectorOf< XercesStep >, RefVectorOf< TVal >, RefVectorOf< XSNamespaceItem >, RefVectorOf< ValueStore >, RefVectorOf< PSVIAttributeStorage >, RefArrayVectorOf< TElem >, RefArrayVectorOf< TElem >, RefArrayVectorOf< TElem >, RefVectorOf< TElem >, RefVectorOf< TElem >, and RefVectorOf< TElem >.
Public Member Functions
BaseRefVectorOf (const XMLSize_t maxElems, const bool adoptElems=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~BaseRefVectorOf ()
void addElement (TElem *const toAdd)
virtual void setElementAt (TElem *const toSet, const XMLSize_t setAt)
void insertElementAt (TElem *const toInsert, const XMLSize_t insertAt)
TElem * orphanElementAt (const XMLSize_t orphanAt)
virtual void removeAllElements ()
virtual void removeElementAt (const XMLSize_t removeAt)
virtual void removeLastElement ()
bool containsElement (const TElem *const toCheck)
virtual void cleanup ()
void reinitialize ()
XMLSize_t curCapacity () const
const TElem * elementAt (const XMLSize_t getAt) const
TElem * elementAt (const XMLSize_t getAt)
XMLSize_t size () const
MemoryManager * getMemoryManager () const
void ensureExtraCapacity (const XMLSize_t length)
BaseRefVectorOf (const XMLSize_t maxElems, const bool adoptElems=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~BaseRefVectorOf ()
void addElement (TElem *const toAdd)
virtual void setElementAt (TElem *const toSet, const XMLSize_t setAt)
void insertElementAt (TElem *const toInsert, const XMLSize_t insertAt)
TElem * orphanElementAt (const XMLSize_t orphanAt)
virtual void removeAllElements ()
virtual void removeElementAt (const XMLSize_t removeAt)
virtual void removeLastElement ()
bool containsElement (const TElem *const toCheck)
virtual void cleanup ()
void reinitialize ()
XMLSize_t curCapacity () const
const TElem * elementAt (const XMLSize_t getAt) const
TElem * elementAt (const XMLSize_t getAt)
XMLSize_t size () const
MemoryManager * getMemoryManager () const
void ensureExtraCapacity (const XMLSize_t length)
BaseRefVectorOf (const XMLSize_t maxElems, const bool adoptElems=true, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~BaseRefVectorOf ()
void addElement (TElem *const toAdd)
virtual void setElementAt (TElem *const toSet, const XMLSize_t setAt)
void insertElementAt (TElem *const toInsert, const XMLSize_t insertAt)
TElem * orphanElementAt (const XMLSize_t orphanAt)
virtual void removeAllElements ()
virtual void removeElementAt (const XMLSize_t removeAt)
virtual void removeLastElement ()
bool containsElement (const TElem *const toCheck)
virtual void cleanup ()
void reinitialize ()
XMLSize_t curCapacity () const
const TElem * elementAt (const XMLSize_t getAt) const
TElem * elementAt (const XMLSize_t getAt)
XMLSize_t size () const
MemoryManager * getMemoryManager () const
void ensureExtraCapacity (const XMLSize_t length)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Protected Attributes
bool fAdoptedElems
XMLSize_t fCurCount
XMLSize_t fMaxCount
TElem ** fElemList
MemoryManager * fMemoryManager
Private Member Functions
BaseRefVectorOf (const BaseRefVectorOf< TElem > &copy)
BaseRefVectorOf & operator= (const BaseRefVectorOf< TElem > &copy)
BaseRefVectorOf (const BaseRefVectorOf< TElem > &copy)
BaseRefVectorOf & operator= (const BaseRefVectorOf< TElem > &copy)
BaseRefVectorOf (const BaseRefVectorOf< TElem > &copy)
BaseRefVectorOf & operator= (const BaseRefVectorOf< TElem > &copy)
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
template<class TElem>
class BaseRefVectorOf< TElem >
Abstract base class for the xerces internal representation of Vector.
The destructor is abstract, forcing each of RefVectorOf and RefArrayVectorOf to implement their own appropriate one.
Definition at line 39 of file BaseRefVectorOf.hpp.
Constructor & Destructor Documentation
BaseRefVectorOf() [1/6]
template<class TElem > XERCES_CPP_NAMESPACE_BEGIN BaseRefVectorOf< TElem >::BaseRefVectorOf (const XMLSize_t maxElems, const bool adoptElems = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Definition at line 30 of file BaseRefVectorOf.c.
References MemoryManager::allocate(), BaseRefVectorOf< TElem >::fElemList, and BaseRefVectorOf< TElem >::fMemoryManager.
~BaseRefVectorOf() [1/3]
template<class TElem > BaseRefVectorOf< TElem >::~BaseRefVectorOf virtual
Definition at line 48 of file BaseRefVectorOf.c.
BaseRefVectorOf() [2/6]
template<class TElem > BaseRefVectorOf< TElem >::BaseRefVectorOf (const BaseRefVectorOf< TElem > & copy) private
BaseRefVectorOf() [3/6]
template<class TElem > BaseRefVectorOf< TElem >::BaseRefVectorOf (const XMLSize_t maxElems, const bool adoptElems = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~BaseRefVectorOf() [2/3]
template<class TElem > virtual BaseRefVectorOf< TElem >::~BaseRefVectorOf () virtual
BaseRefVectorOf() [4/6]
template<class TElem > BaseRefVectorOf< TElem >::BaseRefVectorOf (const BaseRefVectorOf< TElem > & copy) private
BaseRefVectorOf() [5/6]
template<class TElem > BaseRefVectorOf< TElem >::BaseRefVectorOf (const XMLSize_t maxElems, const bool adoptElems = true, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~BaseRefVectorOf() [3/3]
template<class TElem > virtual BaseRefVectorOf< TElem >::~BaseRefVectorOf () virtual
BaseRefVectorOf() [6/6]
template<class TElem > BaseRefVectorOf< TElem >::BaseRefVectorOf (const BaseRefVectorOf< TElem > & copy) private
Member Function Documentation
addElement() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::addElement (TElem *const toAdd)
Definition at line 56 of file BaseRefVectorOf.c.
Referenced by ComplexTypeInfo::addElement(), IdentityConstraint::addField(), SchemaElementDecl::addIdentityConstraint(), XPathMatcherStack::addMatcher(), SchemaInfo::addSchemaInfo(), PSVIAttributeList::getPSVIAttributeToFill(), and FieldValueMap::put().
addElement() [2/3]
template<class TElem > void BaseRefVectorOf< TElem >::addElement (TElem *const toAdd)
addElement() [3/3]
template<class TElem > void BaseRefVectorOf< TElem >::addElement (TElem *const toAdd)
cleanup() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::cleanup virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
Definition at line 196 of file BaseRefVectorOf.c.
cleanup() [2/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::cleanup () virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
cleanup() [3/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::cleanup () virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
containsElement() [1/3]
template<class TElem > bool BaseRefVectorOf< TElem >::containsElement (const TElem *const toCheck)
Definition at line 180 of file BaseRefVectorOf.c.
Referenced by ComplexTypeInfo::addElement(), SchemaInfo::addSchemaInfo(), and SchemaInfo::containsInfo().
containsElement() [2/3]
template<class TElem > bool BaseRefVectorOf< TElem >::containsElement (const TElem *const toCheck)
containsElement() [3/3]
template<class TElem > bool BaseRefVectorOf< TElem >::containsElement (const TElem *const toCheck)
curCapacity() [1/3]
template<class TElem > XMLSize_t BaseRefVectorOf< TElem >::curCapacity
Definition at line 233 of file BaseRefVectorOf.c.
curCapacity() [2/3]
template<class TElem > XMLSize_t BaseRefVectorOf< TElem >::curCapacity () const
curCapacity() [3/3]
template<class TElem > XMLSize_t BaseRefVectorOf< TElem >::curCapacity () const
elementAt() [1/6]
template<class TElem > TElem * BaseRefVectorOf< TElem >::elementAt (const XMLSize_t getAt)
Definition at line 247 of file BaseRefVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
elementAt() [2/6]
template<class TElem > TElem* BaseRefVectorOf< TElem >::elementAt (const XMLSize_t getAt)
elementAt() [3/6]
template<class TElem > TElem* BaseRefVectorOf< TElem >::elementAt (const XMLSize_t getAt)
elementAt() [4/6]
template<class TElem > const TElem * BaseRefVectorOf< TElem >::elementAt (const XMLSize_t getAt) const
Definition at line 238 of file BaseRefVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
Referenced by SchemaInfo::addSchemaInfo(), SchemaInfo::circularImportExist(), ComplexTypeInfo::elementAt(), UnionToken::getChild(), SchemaInfo::getImportInfo(), XPathMatcherStack::getMatcherAt(), PSVIAttributeList::getPSVIAttributeToFill(), FieldValueMap::getValueAt(), FieldValueMap::getValueFor(), UnionDatatypeValidator::isAtomic(), and UnionDatatypeValidator::isSubstitutableBy().
elementAt() [5/6]
template<class TElem > const TElem* BaseRefVectorOf< TElem >::elementAt (const XMLSize_t getAt) const
elementAt() [6/6]
template<class TElem > const TElem* BaseRefVectorOf< TElem >::elementAt (const XMLSize_t getAt) const
ensureExtraCapacity() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::ensureExtraCapacity (const XMLSize_t length)
Definition at line 263 of file BaseRefVectorOf.c.
ensureExtraCapacity() [2/3]
template<class TElem > void BaseRefVectorOf< TElem >::ensureExtraCapacity (const XMLSize_t length)
ensureExtraCapacity() [3/3]
template<class TElem > void BaseRefVectorOf< TElem >::ensureExtraCapacity (const XMLSize_t length)
getMemoryManager() [1/3]
template<class TElem > MemoryManager * BaseRefVectorOf< TElem >::getMemoryManager
Definition at line 224 of file BaseRefVectorOf.c.
getMemoryManager() [2/3]
template<class TElem > MemoryManager* BaseRefVectorOf< TElem >::getMemoryManager () const
getMemoryManager() [3/3]
template<class TElem > MemoryManager* BaseRefVectorOf< TElem >::getMemoryManager () const
insertElementAt() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::insertElementAt (TElem *const toInsert, const XMLSize_t insertAt)
Definition at line 75 of file BaseRefVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
insertElementAt() [2/3]
template<class TElem > void BaseRefVectorOf< TElem >::insertElementAt (TElem *const toInsert, const XMLSize_t insertAt)
insertElementAt() [3/3]
template<class TElem > void BaseRefVectorOf< TElem >::insertElementAt (TElem *const toInsert, const XMLSize_t insertAt)
operator=() [1/3]
template<class TElem > BaseRefVectorOf& BaseRefVectorOf< TElem >::operator= (const BaseRefVectorOf< TElem > & copy) private
operator=() [2/3]
template<class TElem > BaseRefVectorOf& BaseRefVectorOf< TElem >::operator= (const BaseRefVectorOf< TElem > & copy) private
operator=() [3/3]
template<class TElem > BaseRefVectorOf& BaseRefVectorOf< TElem >::operator= (const BaseRefVectorOf< TElem > & copy) private
orphanElementAt() [1/3]
template<class TElem > TElem * BaseRefVectorOf< TElem >::orphanElementAt (const XMLSize_t orphanAt)
Definition at line 98 of file BaseRefVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
orphanElementAt() [2/3]
template<class TElem > TElem* BaseRefVectorOf< TElem >::orphanElementAt (const XMLSize_t orphanAt)
orphanElementAt() [3/3]
template<class TElem > TElem* BaseRefVectorOf< TElem >::orphanElementAt (const XMLSize_t orphanAt)
reinitialize() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::reinitialize
Definition at line 211 of file BaseRefVectorOf.c.
reinitialize() [2/3]
template<class TElem > void BaseRefVectorOf< TElem >::reinitialize ()
reinitialize() [3/3]
template<class TElem > void BaseRefVectorOf< TElem >::reinitialize ()
removeAllElements() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::removeAllElements virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
Definition at line 128 of file BaseRefVectorOf.c.
Referenced by OpFactory::reset().
removeAllElements() [2/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::removeAllElements () virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
removeAllElements() [3/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::removeAllElements () virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
removeElementAt() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::removeElementAt (const XMLSize_t removeAt) virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
Definition at line 141 of file BaseRefVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
removeElementAt() [2/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::removeElementAt (const XMLSize_t removeAt) virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
removeElementAt() [3/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::removeElementAt (const XMLSize_t removeAt) virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
removeLastElement() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::removeLastElement virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
Definition at line 169 of file BaseRefVectorOf.c.
removeLastElement() [2/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::removeLastElement () virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
removeLastElement() [3/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::removeLastElement () virtual
Reimplemented in RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< XMLCh >.
setElementAt() [1/3]
template<class TElem > void BaseRefVectorOf< TElem >::setElementAt (TElem *const toSet, const XMLSize_t setAt) virtual
Reimplemented in RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< TElem >.
Definition at line 65 of file BaseRefVectorOf.c.
References ThrowXMLwithMemMgr, and XMLExcepts::Vector_BadIndex.
Referenced by XPathMatcherStack::addMatcher().
setElementAt() [2/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::setElementAt (TElem *const toSet, const XMLSize_t setAt) virtual
Reimplemented in RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< TElem >.
setElementAt() [3/3]
template<class TElem > virtual void BaseRefVectorOf< TElem >::setElementAt (TElem *const toSet, const XMLSize_t setAt) virtual
Reimplemented in RefArrayVectorOf< XMLCh >, RefArrayVectorOf< TElem >, RefArrayVectorOf< TElem >, and RefArrayVectorOf< TElem >.
size() [1/3]
template<class TElem > XMLSize_t BaseRefVectorOf< TElem >::size
Definition at line 254 of file BaseRefVectorOf.c.
Referenced by XPathMatcherStack::addMatcher(), SchemaInfo::addSchemaInfo(), SchemaInfo::circularImportExist(), ComplexTypeInfo::elementCount(), SchemaInfo::getImportInfo(), PSVIAttributeList::getPSVIAttributeToFill(), UnionDatatypeValidator::isAtomic(), UnionDatatypeValidator::isSubstitutableBy(), and UnionToken::size().
size() [2/3]
template<class TElem > XMLSize_t BaseRefVectorOf< TElem >::size () const
size() [3/3]
template<class TElem > XMLSize_t BaseRefVectorOf< TElem >::size () const
Member Data Documentation
fAdoptedElems
template<class TElem > bool BaseRefVectorOf< TElem >::fAdoptedElems protected
Definition at line 95 of file BaseRefVectorOf.hpp.
fCurCount
template<class TElem > XMLSize_t BaseRefVectorOf< TElem >::fCurCount protected
Definition at line 96 of file BaseRefVectorOf.hpp.
fElemList
template<class TElem > TElem ** BaseRefVectorOf< TElem >::fElemList protected
Definition at line 98 of file BaseRefVectorOf.hpp.
Referenced by BaseRefVectorOf< TElem >::BaseRefVectorOf().
fMaxCount
template<class TElem > XMLSize_t BaseRefVectorOf< TElem >::fMaxCount protected
Definition at line 97 of file BaseRefVectorOf.hpp.
fMemoryManager
template<class TElem > MemoryManager * BaseRefVectorOf< TElem >::fMemoryManager protected
Definition at line 99 of file BaseRefVectorOf.hpp.
Referenced by BaseRefVectorOf< TElem >::BaseRefVectorOf().
The documentation for this class was generated from the following files:
src/libs/xerces-c/macx/include/xercesc/util/BaseRefVectorOf.hpp
src/libs/xerces-c/macx/include/xercesc/util/BaseRefVectorOf.c