Seamly2D: VisToolLineIntersect Class Reference
VisToolLineIntersect Class Reference
#include <vistoollineintersect.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolLineIntersect) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolLineIntersect (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolLineIntersect ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setLine1P2Id (const quint32 &value)
void setLine2P1Id (const quint32 &value)
void setLine2P2Id (const quint32 &value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Attributes
quint32 line1P2Id
quint32 line2P1Id
quint32 line2P2Id
VScaledEllipse * point
VScaledEllipse * line1P1
VScaledEllipse * line1P2
VScaledLine * line1
VScaledEllipse * line2P1
VScaledEllipse * line2P2
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 65 of file vistoollineintersect.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 78 of file vistoollineintersect.h.
Constructor & Destructor Documentation
VisToolLineIntersect()
VisToolLineIntersect::VisToolLineIntersect (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 68 of file vistoollineintersect.cpp.
References Visualization::InitPoint(), line1, line1P1, line1P2, line2P1, line2P2, Visualization::mainColor, point, and Visualization::supportColor.
~VisToolLineIntersect()
virtual VisToolLineIntersect::~VisToolLineIntersect () virtual default
Member Function Documentation
RefreshGeometry()
void VisToolLineIntersect::RefreshGeometry () virtual
Implements Visualization.
Definition at line 83 of file vistoollineintersect.cpp.
References Visualization::data, Visualization::DrawLine(), Visualization::DrawPoint(), VContainer::GeometricObject(), line1, line1P1, line1P2, line1P2Id, line2P1, line2P1Id, line2P2, line2P2Id, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, point, Visualization::scenePos, and Visualization::supportColor.
Referenced by DialogLineIntersect::ChosenObject(), DialogLineIntersect::SaveData(), and VToolLineIntersect::SetVisualization().
setLine1P2Id()
void VisToolLineIntersect::setLine1P2Id (const quint32 & value)
Definition at line 148 of file vistoollineintersect.cpp.
References line1P2Id.
Referenced by DialogLineIntersect::ChosenObject(), DialogLineIntersect::SaveData(), DialogLineIntersect::SetP2Line1(), and VToolLineIntersect::SetVisualization().
setLine2P1Id()
void VisToolLineIntersect::setLine2P1Id (const quint32 & value)
Definition at line 154 of file vistoollineintersect.cpp.
References line2P1Id.
Referenced by DialogLineIntersect::ChosenObject(), DialogLineIntersect::SaveData(), DialogLineIntersect::SetP1Line2(), and VToolLineIntersect::SetVisualization().
setLine2P2Id()
void VisToolLineIntersect::setLine2P2Id (const quint32 & value)
Definition at line 160 of file vistoollineintersect.cpp.
References line2P2Id.
Referenced by DialogLineIntersect::ChosenObject(), DialogLineIntersect::SaveData(), DialogLineIntersect::SetP2Line2(), and VToolLineIntersect::SetVisualization().
type()
virtual int VisToolLineIntersect::type () const inline virtual
Reimplemented from VisLine.
Definition at line 77 of file vistoollineintersect.h.
References Type.
Member Data Documentation
line1
VScaledLine* VisToolLineIntersect::line1 private
Definition at line 87 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and VisToolLineIntersect().
line1P1
VScaledEllipse* VisToolLineIntersect::line1P1 private
Definition at line 85 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and VisToolLineIntersect().
line1P2
VScaledEllipse* VisToolLineIntersect::line1P2 private
Definition at line 86 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and VisToolLineIntersect().
line1P2Id
quint32 VisToolLineIntersect::line1P2Id private
Definition at line 81 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and setLine1P2Id().
line2P1
VScaledEllipse* VisToolLineIntersect::line2P1 private
Definition at line 88 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and VisToolLineIntersect().
line2P1Id
quint32 VisToolLineIntersect::line2P1Id private
Definition at line 82 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and setLine2P1Id().
line2P2
VScaledEllipse* VisToolLineIntersect::line2P2 private
Definition at line 89 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and VisToolLineIntersect().
line2P2Id
quint32 VisToolLineIntersect::line2P2Id private
Definition at line 83 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and setLine2P2Id().
point
VScaledEllipse* VisToolLineIntersect::point private
Definition at line 84 of file vistoollineintersect.h.
Referenced by RefreshGeometry(), and VisToolLineIntersect().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/vistoollineintersect.h
src/libs/vtools/visualization/line/vistoollineintersect.cpp