Seamly2D: VAbstractLayoutDialog Class Reference
VAbstractLayoutDialog Class Reference
#include <vabstractlayoutdialog.h>
Public Types
enum class PaperSizeTemplate : char {
A0 = 0 , A1 , A2 , A3 ,
A4 , Letter , Legal , Roll24in = 7 ,
Roll30in , Roll36in , Roll42in , Roll44in = 11 ,
Custom = 12
}
Public Member Functions
VAbstractLayoutDialog (QWidget *parent=nullptr)
Protected Types
typedef QStringList FormatsVector
typedef int VIndexType
Protected Member Functions
QSizeF getTemplateSize (const PaperSizeTemplate &tmpl, const Unit &unit) const
DialogLayoutSettings::TemplateSize.
QSizeF RoundTemplateSize (qreal width, qreal height, Unit unit) const
void initTemplates (QComboBox *comboBoxTemplates)
Static Protected Attributes
static const FormatsVector pageFormatNames
Detailed Description
Definition at line 11 of file vabstractlayoutdialog.h.
Member Typedef Documentation
FormatsVector
typedef QStringList VAbstractLayoutDialog::FormatsVector protected
Definition at line 31 of file vabstractlayoutdialog.h.
VIndexType
typedef int VAbstractLayoutDialog::VIndexType protected
Definition at line 33 of file vabstractlayoutdialog.h.
Member Enumeration Documentation
PaperSizeTemplate
enum VAbstractLayoutDialog::PaperSizeTemplate : char strong
Enumerator
A0
A1
A2
A3
A4
Letter
Legal
Roll24in
Roll30in
Roll36in
Roll42in
Roll44in
Custom
Definition at line 14 of file vabstractlayoutdialog.h.
Constructor & Destructor Documentation
VAbstractLayoutDialog()
VAbstractLayoutDialog::VAbstractLayoutDialog (QWidget * parent = nullptr) explicit
Definition at line 24 of file vabstractlayoutdialog.cpp.
Member Function Documentation
getTemplateSize()
QSizeF VAbstractLayoutDialog::getTemplateSize (const PaperSizeTemplate & tmpl, const Unit & unit) const protected
DialogLayoutSettings::TemplateSize.
Parameters
tmpl
unit
Returns
Definition at line 64 of file vabstractlayoutdialog.cpp.
References A0, A1, A2, A3, A4, Inch, Legal, Letter, Mm, Px, QIMAGE_MAX, Roll24in, Roll30in, Roll36in, Roll42in, Roll44in, RoundTemplateSize(), and UnitConvertor().
Referenced by DialogLayoutSettings::getTemplateSize(), ExportLayoutDialog::readSettings(), and ExportLayoutDialog::writeSettings().
initTemplates()
void VAbstractLayoutDialog::initTemplates (QComboBox * comboBoxTemplates) protected
Definition at line 30 of file vabstractlayoutdialog.cpp.
References A0, Legal, pageFormatNames, PrintDPI, Roll44in, and SCASSERT.
Referenced by DialogLayoutSettings::DialogLayoutSettings(), and ExportLayoutDialog::initTemplates().
RoundTemplateSize()
QSizeF VAbstractLayoutDialog::RoundTemplateSize (qreal width, qreal height, Unit unit) const protected
Definition at line 126 of file vabstractlayoutdialog.cpp.
References Cm, Inch, Mm, and Px.
Referenced by DialogLayoutSettings::getTemplateSize(), and getTemplateSize().
Member Data Documentation
pageFormatNames
const VAbstractLayoutDialog::FormatsVector VAbstractLayoutDialog::pageFormatNames static protected
Initial value:
=
        VAbstractLayoutDialog::FormatsVector () << QLatin1String("A0")
                                               << QLatin1String("A1")
                                               << QLatin1String("A2")
                                               << QLatin1String("A3")
                                               << QLatin1String("A4")
                                               << QApplication::translate("DialogLayoutSettings", "Letter")
                                               << QApplication::translate("DialogLayoutSettings", "Legal")
                                               << QApplication::translate("DialogLayoutSettings", "Roll 24in")
                                               << QApplication::translate("DialogLayoutSettings", "Roll 30in")
                                               << QApplication::translate("DialogLayoutSettings", "Roll 36in")
                                               << QApplication::translate("DialogLayoutSettings", "Roll 42in")
                                               << QApplication::translate("DialogLayoutSettings", "Roll 44in")
                                               << QApplication::translate("DialogLayoutSettings", "Custom")
Definition at line 32 of file vabstractlayoutdialog.h.
Referenced by initTemplates(), and DialogLayoutSettings::MakeHelpTemplateList().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/vabstractlayoutdialog.h
src/app/seamly2d/dialogs/vabstractlayoutdialog.cpp