Seamly2D: DialogSplinePath Class Reference
DialogSplinePath Class Reference
The DialogSplinePath class dialog for ToolSplinePath. Help create spline path and edit option.
#include <dialogsplinepath.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
virtual void ShowDialog (bool click) Q_DECL_OVERRIDE
void PathUpdated (const VSplinePath &path)
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogSplinePath (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogSplinePath create dialog.
virtual ~DialogSplinePath () Q_DECL_OVERRIDE
VSplinePath GetPath () const
GetPath return spline path.
void SetPath (const VSplinePath &value)
SetPath set spline path.
QString getPenStyle () const
void setPenStyle (const QString &value)
QString getLineWeight () const
getLineWeight return weight of the lines
void setLineWeight (const QString &value)
setLineWeight set weight of the lines
QString getLineColor () const
void setLineColor (const QString &value)
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void CheckState () Q_DECL_FINAL
CheckState enable, when all is correct, or disable, when something wrong, button ok.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Slots
void PointChanged (int row)
PointChanged selected another point in list.
void currentPointChanged (int index)
currentPointChanged changed point in combo box
void DeployAngle1TextEdit ()
void DeployAngle2TextEdit ()
void DeployLength1TextEdit ()
void DeployLength2TextEdit ()
void Angle1Changed ()
void Angle2Changed ()
void Length1Changed ()
void Length2Changed ()
void FXAngle1 ()
void FXAngle2 ()
void FXLength1 ()
void FXLength2 ()
Private Member Functions
void EvalAngle1 ()
void EvalAngle2 ()
void EvalLength1 ()
void EvalLength2 ()
void NewItem (const VSplinePoint &point)
NewItem add point to list.
void DataPoint (const VSplinePoint &p)
dataPoint show data of point in fields
void SavePath ()
QSet< quint32 > AllIds () const
bool IsPathValid () const
VSplinePath ExtractPath () const
void ShowPointIssue (const QString &pName)
void collapseFormula (QPlainTextEdit *textEdit, QPushButton *pushButton, int height)
Private Attributes
Ui::DialogSplinePath * ui
ui keeps information about user interface
VSplinePath path
path spline path
qint32 newDuplicate
int formulaBaseHeightAngle1
formulaBaseHeight base height defined by dialogui
int formulaBaseHeightAngle2
int formulaBaseHeightLength1
int formulaBaseHeightLength2
QVector< bool > flagAngle1
flagAngle1 true if value of first angle is correct
QVector< bool > flagAngle2
QVector< bool > flagLength1
QVector< bool > flagLength2
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
The DialogSplinePath class dialog for ToolSplinePath. Help create spline path and edit option.
Definition at line 75 of file dialogsplinepath.h.
Constructor & Destructor Documentation
DialogSplinePath()
DialogSplinePath::DialogSplinePath (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
DialogSplinePath create dialog.
Parameters
data container with data
parent parent widget
Definition at line 97 of file dialogsplinepath.cpp.
References Angle1Changed(), Angle2Changed(), currentPointChanged(), DialogTool::data, DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), DeployLength2TextEdit(), DialogTool::FillComboBoxPoints(), formulaBaseHeightAngle1, formulaBaseHeightAngle2, formulaBaseHeightLength1, formulaBaseHeightLength2, FXAngle1(), FXAngle2(), FXLength1(), FXLength2(), DialogTool::initializeOkCancelApply(), Length1Changed(), Length2Changed(), LineTypeNone, VisToolSplinePath::MouseLeftPressed(), VMainGraphicsScene::MouseLeftPressed(), VisToolSplinePath::MouseLeftReleased(), VMainGraphicsScene::MouseLeftReleased(), DialogTool::ok_Button, path, DialogTool::plainTextEditFormula, PointChanged(), qApp, SCASSERT, ui, and DialogTool::vis.
~DialogSplinePath()
DialogSplinePath::~DialogSplinePath () virtual
Definition at line 186 of file dialogsplinepath.cpp.
References ui.
Member Function Documentation
AllIds()
QSet< quint32 > DialogSplinePath::AllIds () const private
Definition at line 1019 of file dialogsplinepath.cpp.
References ui.
Referenced by ChosenObject(), and IsPathValid().
Angle1Changed
void DialogSplinePath::Angle1Changed () private slot
Definition at line 393 of file dialogsplinepath.cpp.
References VSplinePoint::Angle2Formula(), DialogTool::data, VContainer::DataVariables(), EvalAngle1(), EvalAngle2(), Visualization::FindVal(), qApp, SCASSERT, VSplinePoint::SetAngle1(), and ui.
Referenced by DialogSplinePath().
Angle2Changed
void DialogSplinePath::Angle2Changed () private slot
Definition at line 436 of file dialogsplinepath.cpp.
References VSplinePoint::Angle1Formula(), DialogTool::data, VContainer::DataVariables(), EvalAngle1(), EvalAngle2(), Visualization::FindVal(), qApp, SCASSERT, VSplinePoint::SetAngle2(), and ui.
Referenced by DialogSplinePath().
CheckState()
void DialogSplinePath::CheckState () protected virtual
CheckState enable, when all is correct, or disable, when something wrong, button ok.
Reimplemented from DialogTool.
Definition at line 324 of file dialogsplinepath.cpp.
References DialogTool::apply_Button, flagAngle1, flagAngle2, DialogTool::flagError, flagLength1, flagLength2, DialogTool::ok_Button, SCASSERT, and ui.
Referenced by currentPointChanged(), EvalLength1(), and EvalLength2().
ChosenObject
void DialogSplinePath::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
Parameters
id id of point or detail
type don't show this id in list
Definition at line 269 of file dialogsplinepath.cpp.
References AllIds(), VSplinePath::CountPoints(), DialogTool::data, VContainer::GeometricObject(), NewItem(), NULL_ID, path, VisToolSplinePath::PathChanged(), PathUpdated(), Point, qApp, SavePath(), SCASSERT, VSplinePoint::SetP(), VAbstractMainWindow::ShowToolTip(), DialogTool::ToolTip(), Visualization::ToolTip(), and DialogTool::vis.
closeEvent()
void DialogSplinePath::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 347 of file dialogsplinepath.cpp.
References DialogTool::closeEvent(), and ui.
collapseFormula()
void DialogSplinePath::collapseFormula (QPlainTextEdit * textEdit, QPushButton * pushButton, int height) private
Definition at line 1075 of file dialogsplinepath.cpp.
References SCASSERT.
Referenced by DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), and DeployLength2TextEdit().
currentPointChanged
void DialogSplinePath::currentPointChanged (int index) private slot
currentPointChanged changed point in combo box
Parameters
index index in list
Definition at line 767 of file dialogsplinepath.cpp.
References VSplinePath::at(), DialogTool::ChangeColor(), CheckState(), VSplinePath::CountPoints(), DialogTool::data, DataPoint(), DialogTool::DNumber(), DialogTool::errorColor, ExtractPath(), DialogTool::flagError, VContainer::GeometricObject(), VGObject::id(), IsPathValid(), VContainer::IsUnique(), VGObject::name(), newDuplicate, DialogTool::okColor, VSplinePoint::P(), path, qApp, VAbstractCurve::SetDuplicate(), VSplinePoint::SetP(), ShowPointIssue(), and ui.
Referenced by DialogSplinePath().
DataPoint()
void DialogSplinePath::DataPoint (const VSplinePoint & p) private
dataPoint show data of point in fields
Parameters
p spline path point
Definition at line 879 of file dialogsplinepath.cpp.
References VSplinePoint::Angle1Formula(), VSplinePoint::Angle2Formula(), DialogTool::ChangeColor(), DialogTool::ChangeCurrentData(), EvalAngle1(), EvalAngle2(), EvalLength1(), EvalLength2(), VGObject::id(), VSplinePoint::Length1Formula(), VSplinePoint::Length2Formula(), DialogTool::okColor, VSplinePoint::P(), qApp, and ui.
Referenced by currentPointChanged(), NewItem(), and PointChanged().
DeployAngle1TextEdit
void DialogSplinePath::DeployAngle1TextEdit () private slot
Definition at line 357 of file dialogsplinepath.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightAngle1, formulaBaseHeightAngle2, formulaBaseHeightLength1, formulaBaseHeightLength2, and ui.
Referenced by DialogSplinePath(), FXAngle1(), and FXAngle2().
DeployAngle2TextEdit
void DialogSplinePath::DeployAngle2TextEdit () private slot
Definition at line 366 of file dialogsplinepath.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightAngle1, formulaBaseHeightAngle2, formulaBaseHeightLength1, formulaBaseHeightLength2, and ui.
Referenced by DialogSplinePath().
DeployLength1TextEdit
void DialogSplinePath::DeployLength1TextEdit () private slot
Definition at line 375 of file dialogsplinepath.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightAngle1, formulaBaseHeightAngle2, formulaBaseHeightLength1, formulaBaseHeightLength2, and ui.
Referenced by DialogSplinePath(), and FXLength1().
DeployLength2TextEdit
void DialogSplinePath::DeployLength2TextEdit () private slot
Definition at line 384 of file dialogsplinepath.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightAngle1, formulaBaseHeightAngle2, formulaBaseHeightLength1, formulaBaseHeightLength2, and ui.
Referenced by DialogSplinePath(), and FXLength2().
EvalAngle1()
void DialogSplinePath::EvalAngle1 () private
Definition at line 647 of file dialogsplinepath.cpp.
References degreeSymbol, DialogTool::Eval(), flagAngle1, DialogTool::labelEditFormula, VGObject::name(), VSplinePoint::P(), SCASSERT, ShowPointIssue(), and ui.
Referenced by Angle1Changed(), Angle2Changed(), and DataPoint().
EvalAngle2()
void DialogSplinePath::EvalAngle2 () private
Definition at line 666 of file dialogsplinepath.cpp.
References degreeSymbol, DialogTool::Eval(), flagAngle2, DialogTool::labelEditFormula, VGObject::name(), VSplinePoint::P(), SCASSERT, ShowPointIssue(), and ui.
Referenced by Angle1Changed(), Angle2Changed(), and DataPoint().
EvalLength1()
void DialogSplinePath::EvalLength1 () private
Definition at line 685 of file dialogsplinepath.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::Eval(), flagLength1, DialogTool::labelEditFormula, VGObject::name(), VSplinePoint::P(), qApp, SCASSERT, ShowPointIssue(), ui, and UnitsToStr().
Referenced by DataPoint(), and Length1Changed().
EvalLength2()
void DialogSplinePath::EvalLength2 () private
Definition at line 716 of file dialogsplinepath.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::Eval(), flagLength2, DialogTool::labelEditFormula, VGObject::name(), VSplinePoint::P(), qApp, SCASSERT, ShowPointIssue(), ui, and UnitsToStr().
Referenced by DataPoint(), and Length2Changed().
ExtractPath()
VSplinePath DialogSplinePath::ExtractPath () const private
Definition at line 1042 of file dialogsplinepath.cpp.
References ui.
Referenced by currentPointChanged(), and SavePath().
FXAngle1
void DialogSplinePath::FXAngle1 () private slot
Definition at line 547 of file dialogsplinepath.cpp.
References DialogTool::data, degreeSymbol, DeployAngle1TextEdit(), DialogTool::MoveCursorToEnd(), qApp, DialogTool::toolId, and ui.
Referenced by DialogSplinePath().
FXAngle2
void DialogSplinePath::FXAngle2 () private slot
Definition at line 572 of file dialogsplinepath.cpp.
References DialogTool::data, degreeSymbol, DeployAngle1TextEdit(), DialogTool::MoveCursorToEnd(), qApp, DialogTool::toolId, and ui.
Referenced by DialogSplinePath().
FXLength1
void DialogSplinePath::FXLength1 () private slot
Definition at line 597 of file dialogsplinepath.cpp.
References DialogTool::data, DeployLength1TextEdit(), DialogTool::MoveCursorToEnd(), qApp, DialogTool::toolId, ui, and UnitsToStr().
Referenced by DialogSplinePath().
FXLength2
void DialogSplinePath::FXLength2 () private slot
Definition at line 622 of file dialogsplinepath.cpp.
References DialogTool::data, DeployLength2TextEdit(), DialogTool::MoveCursorToEnd(), qApp, DialogTool::toolId, ui, and UnitsToStr().
Referenced by DialogSplinePath().
getLineColor()
QString DialogSplinePath::getLineColor () const
Definition at line 252 of file dialogsplinepath.cpp.
References ColorBlack, DialogTool::GetComboBoxCurrentData(), and ui.
getLineWeight()
QString DialogSplinePath::getLineWeight () const
getLineWeight return weight of the lines
Returns
type
Definition at line 236 of file dialogsplinepath.cpp.
References DialogTool::GetComboBoxCurrentData(), and ui.
GetPath()
VSplinePath DialogSplinePath::GetPath () const inline
GetPath return spline path.
Returns
path
Definition at line 168 of file dialogsplinepath.h.
References path.
getPenStyle()
QString DialogSplinePath::getPenStyle () const
Definition at line 220 of file dialogsplinepath.cpp.
References DialogTool::GetComboBoxCurrentData(), LineTypeSolidLine, and ui.
IsPathValid()
bool DialogSplinePath::IsPathValid () const private
Definition at line 1031 of file dialogsplinepath.cpp.
References AllIds(), VSplinePath::CountPoints(), and path.
Referenced by currentPointChanged().
Length1Changed
void DialogSplinePath::Length1Changed () private slot
Definition at line 479 of file dialogsplinepath.cpp.
References DialogTool::data, VContainer::DataVariables(), EvalLength1(), Visualization::FindLength(), qApp, SCASSERT, VSplinePoint::SetLength1(), and ui.
Referenced by DialogSplinePath().
Length2Changed
void DialogSplinePath::Length2Changed () private slot
Definition at line 513 of file dialogsplinepath.cpp.
References DialogTool::data, VContainer::DataVariables(), EvalLength2(), Visualization::FindLength(), qApp, SCASSERT, VSplinePoint::SetLength2(), and ui.
Referenced by DialogSplinePath().
NewItem()
void DialogSplinePath::NewItem (const VSplinePoint & point) private
NewItem add point to list.
Parameters
point spline path point
Definition at line 853 of file dialogsplinepath.cpp.
References DataPoint(), flagAngle1, flagAngle2, flagLength1, flagLength2, VGObject::name(), DialogTool::ok_Button, VSplinePoint::P(), and ui.
Referenced by ChosenObject(), and SetPath().
PathUpdated
void DialogSplinePath::PathUpdated (const VSplinePath & path) slot
Definition at line 837 of file dialogsplinepath.cpp.
References path, and SetPath().
Referenced by ChosenObject().
PointChanged
void DialogSplinePath::PointChanged (int row) private slot
PointChanged selected another point in list.
Parameters
row number of row
Definition at line 751 of file dialogsplinepath.cpp.
References DataPoint(), and ui.
Referenced by DialogSplinePath().
SaveData()
void DialogSplinePath::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 310 of file dialogsplinepath.cpp.
References VAbstractCurve::GetDuplicate(), newDuplicate, path, SavePath(), SCASSERT, VAbstractCurve::SetDuplicate(), Show, and DialogTool::vis.
SavePath()
void DialogSplinePath::SavePath () private
Definition at line 1012 of file dialogsplinepath.cpp.
References VSplinePath::Clear(), ExtractPath(), and path.
Referenced by ChosenObject(), and SaveData().
setLineColor()
void DialogSplinePath::setLineColor (const QString & value)
Definition at line 258 of file dialogsplinepath.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setLineWeight()
void DialogSplinePath::setLineWeight (const QString & value)
setLineWeight set weight of the lines
Parameters
value type
Definition at line 246 of file dialogsplinepath.cpp.
References DialogTool::ChangeCurrentData(), and ui.
SetPath()
void DialogSplinePath::SetPath (const VSplinePath & value)
SetPath set spline path.
Parameters
value path
Definition at line 196 of file dialogsplinepath.cpp.
References VSplinePath::at(), VSplinePath::CountPoints(), flagAngle1, flagAngle2, flagLength1, flagLength2, VGObject::name(), NewItem(), path, qApp, SCASSERT, ui, and DialogTool::vis.
Referenced by PathUpdated().
setPenStyle()
void DialogSplinePath::setPenStyle (const QString & value)
Definition at line 226 of file dialogsplinepath.cpp.
References DialogTool::ChangeCurrentData(), and ui.
ShowDialog
void DialogSplinePath::ShowDialog (bool click) virtual slot
Definition at line 818 of file dialogsplinepath.cpp.
References VSplinePath::CountPoints(), DialogTool::data, DialogTool::DialogAccepted(), DialogTool::DNumber(), VContainer::IsUnique(), VGObject::name(), path, VAbstractCurve::SetDuplicate(), and DialogTool::ToolTip().
ShowPointIssue()
void DialogSplinePath::ShowPointIssue (const QString & pName) private
Definition at line 1053 of file dialogsplinepath.cpp.
References flagAngle1, flagAngle2, flagLength1, flagLength2, SCASSERT, and ui.
Referenced by currentPointChanged(), EvalAngle1(), EvalAngle2(), EvalLength1(), and EvalLength2().
ShowVisualization()
void DialogSplinePath::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 843 of file dialogsplinepath.cpp.
Member Data Documentation
flagAngle1
QVector<bool> DialogSplinePath::flagAngle1 private
flagAngle1 true if value of first angle is correct
Definition at line 142 of file dialogsplinepath.h.
Referenced by CheckState(), EvalAngle1(), NewItem(), SetPath(), and ShowPointIssue().
flagAngle2
QVector<bool> DialogSplinePath::flagAngle2 private
Definition at line 143 of file dialogsplinepath.h.
Referenced by CheckState(), EvalAngle2(), NewItem(), SetPath(), and ShowPointIssue().
flagLength1
QVector<bool> DialogSplinePath::flagLength1 private
Definition at line 144 of file dialogsplinepath.h.
Referenced by CheckState(), EvalLength1(), NewItem(), SetPath(), and ShowPointIssue().
flagLength2
QVector<bool> DialogSplinePath::flagLength2 private
Definition at line 145 of file dialogsplinepath.h.
Referenced by CheckState(), EvalLength2(), NewItem(), SetPath(), and ShowPointIssue().
formulaBaseHeightAngle1
int DialogSplinePath::formulaBaseHeightAngle1 private
formulaBaseHeight base height defined by dialogui
Definition at line 136 of file dialogsplinepath.h.
Referenced by DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), DeployLength2TextEdit(), and DialogSplinePath().
formulaBaseHeightAngle2
int DialogSplinePath::formulaBaseHeightAngle2 private
Definition at line 137 of file dialogsplinepath.h.
Referenced by DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), DeployLength2TextEdit(), and DialogSplinePath().
formulaBaseHeightLength1
int DialogSplinePath::formulaBaseHeightLength1 private
Definition at line 138 of file dialogsplinepath.h.
Referenced by DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), DeployLength2TextEdit(), and DialogSplinePath().
formulaBaseHeightLength2
int DialogSplinePath::formulaBaseHeightLength2 private
Definition at line 139 of file dialogsplinepath.h.
Referenced by DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), DeployLength2TextEdit(), and DialogSplinePath().
newDuplicate
qint32 DialogSplinePath::newDuplicate private
Definition at line 133 of file dialogsplinepath.h.
Referenced by currentPointChanged(), and SaveData().
path
VSplinePath DialogSplinePath::path private
path spline path
Definition at line 131 of file dialogsplinepath.h.
Referenced by ChosenObject(), currentPointChanged(), DialogSplinePath(), GetPath(), IsPathValid(), PathUpdated(), SaveData(), SavePath(), SetPath(), and ShowDialog().
ui
Ui::DialogSplinePath* DialogSplinePath::ui private
ui keeps information about user interface
Definition at line 128 of file dialogsplinepath.h.
Referenced by AllIds(), Angle1Changed(), Angle2Changed(), CheckState(), closeEvent(), currentPointChanged(), DataPoint(), DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), DeployLength2TextEdit(), DialogSplinePath(), EvalAngle1(), EvalAngle2(), EvalLength1(), EvalLength2(), ExtractPath(), FXAngle1(), FXAngle2(), FXLength1(), FXLength2(), getLineColor(), getLineWeight(), getPenStyle(), Length1Changed(), Length2Changed(), NewItem(), PointChanged(), setLineColor(), setLineWeight(), SetPath(), setPenStyle(), ShowPointIssue(), and ~DialogSplinePath().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogsplinepath.h
src/libs/vtools/dialogs/tools/dialogsplinepath.cpp