Seamly2D: VLineAngle Class Reference
VLineAngle Class Reference
#include <vlineangle.h>
Public Member Functions
VLineAngle ()
VLineAngle (const VPointF *p1, const quint32 &p1Id, const VPointF *p2, const quint32 &p2Id)
VLineAngle (const VLineAngle &var)
virtual ~VLineAngle () Q_DECL_OVERRIDE
VLineAngle & operator= (const VLineAngle &var)
void Swap (VLineAngle &var) Q_DECL_NOTHROW
virtual bool Filter (quint32 id) Q_DECL_OVERRIDE
void SetValue (const VPointF *p1, const VPointF *p2)
quint32 GetP1Id () const
quint32 GetP2Id () const
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool isNotUsed () const
Private Attributes
QSharedDataPointer< VLineAngleData > d
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
Definition at line 65 of file vlineangle.h.
Constructor & Destructor Documentation
VLineAngle() [1/3]
VLineAngle::VLineAngle ()
Definition at line 75 of file vlineangle.cpp.
References LineAngle, and VInternalVariable::SetType().
VLineAngle() [2/3]
VLineAngle::VLineAngle (const VPointF * p1, const quint32 & p1Id, const VPointF * p2, const quint32 & p2Id)
Definition at line 82 of file vlineangle.cpp.
References angleLine_, LineAngle, VGObject::name(), SCASSERT, VInternalVariable::SetName(), VInternalVariable::SetType(), and SetValue().
VLineAngle() [3/3]
VLineAngle::VLineAngle (const VLineAngle & var)
Definition at line 95 of file vlineangle.cpp.
~VLineAngle()
VLineAngle::~VLineAngle () virtual
Definition at line 112 of file vlineangle.cpp.
Member Function Documentation
Filter()
bool VLineAngle::Filter (quint32 id) virtual
Reimplemented from VInternalVariable.
Definition at line 116 of file vlineangle.cpp.
References d.
GetP1Id()
quint32 VLineAngle::GetP1Id () const
Definition at line 134 of file vlineangle.cpp.
References d.
GetP2Id()
quint32 VLineAngle::GetP2Id () const
Definition at line 141 of file vlineangle.cpp.
References d.
operator=()
VLineAngle & VLineAngle::operator= (const VLineAngle & var)
Definition at line 100 of file vlineangle.cpp.
References d, and VInternalVariable::operator=().
SetValue()
void VLineAngle::SetValue (const VPointF * p1, const VPointF * p2)
Definition at line 122 of file vlineangle.cpp.
References SCASSERT, and VInternalVariable::SetValue().
Referenced by VLineAngle().
Swap()
void VLineAngle::Swap (VLineAngle & var)
Definition at line 71 of file vlineangle.cpp.
References VInternalVariable::Swap().
Member Data Documentation
d
QSharedDataPointer<VLineAngleData> VLineAngle::d private
Definition at line 86 of file vlineangle.h.
Referenced by Filter(), GetP1Id(), GetP2Id(), and operator=().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/vlineangle.h
src/libs/vpatterndb/variables/vlineangle.cpp