Seamly2D: VToolDoublePoint Class Reference
VToolDoublePoint Class Reference
#include <vtooldoublepoint.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::DoublePoint) }
Public Slots
void changePointName1Position (const QPointF &pos)
void changePointName2Position (const QPointF &pos)
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
void point1Chosen ()
void point2Chosen ()
void point1Selected (bool selected)
void point2Selected (bool selected)
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
void allowTextHover (bool enabled)
void allowTextSelectable (bool enabled)
virtual void ToolSelectionType (const SelectionType &type) Q_DECL_OVERRIDE
Public Slots inherited from VAbstractPoint
virtual void ShowTool (quint32 id, bool enable) Q_DECL_OVERRIDE
ShowTool highlight tool.
void deletePoint ()
Public Slots inherited from VDrawTool
virtual void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Public Member Functions
VToolDoublePoint (VAbstractPattern *doc, VContainer *data, quint32 id, quint32 p1id, quint32 p2id, QGraphicsItem *parent=nullptr)
virtual ~VToolDoublePoint () Q_DECL_EQ_DEFAULT
virtual int type () const Q_DECL_OVERRIDE
QString nameP1 () const
void setNameP1 (const QString &name)
QString nameP2 () const
void setNameP2 (const QString &name)
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
virtual void setPointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
virtual bool isPointNameVisible (quint32 id) const Q_DECL_OVERRIDE
virtual void setPointNameVisiblity (quint32 id, bool visible) Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractPoint
VAbstractPoint (VAbstractPattern *doc, VContainer *data, quint32 id)
virtual ~VAbstractPoint () Q_DECL_EQ_DEFAULT
virtual QString getTagName () const Q_DECL_OVERRIDE
template<typename T >
void ShowToolVisualization (bool show)
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual void setLineWeight (const QString &value)
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
virtual void ShowVisualization (bool show)=0
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Protected Member Functions
virtual void updatePointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) Q_DECL_OVERRIDE
itemChange hadle item change.
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyReleaseEvent handle key release events.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) Q_DECL_OVERRIDE
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
virtual void updatePointNameVisibility (quint32 id, bool visible) Q_DECL_OVERRIDE
QString complexToolTip (quint32 itemId) const
Protected Member Functions inherited from VAbstractPoint
void SetPointName (quint32 id, const QString &name)
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialog (QDomElement &domElement)=0
SaveDialog save options into file after change in dialog.
virtual void SaveDialogChange () Q_DECL_FINAL
void SaveOption (QSharedPointer< VGObject > &obj)
virtual QString makeToolTip () const
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
virtual void ReadToolAttributes (const QDomElement &domElement)=0
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VInteractiveTool
virtual void setDialog ()
setDialog set dialog when user want change tool option.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void RemoveReferens ()
RemoveReferens decrement value of reference.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
virtual void SetVisualization ()=0
virtual void ToolCreation (const Source &typeCreation)
Protected Attributes
VSimplePoint * firstPoint
VSimplePoint * secondPoint
quint32 p1id
quint32 p2id
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Additional Inherited Members
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Static Protected Member Functions inherited from VAbstractPoint
template<typename T >
static void InitToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Detailed Description
Definition at line 71 of file vtooldoublepoint.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 80 of file vtooldoublepoint.h.
Constructor & Destructor Documentation
VToolDoublePoint()
VToolDoublePoint::VToolDoublePoint (VAbstractPattern * doc, VContainer * data, quint32 id, quint32 p1id, quint32 p2id, QGraphicsItem * parent = nullptr)
Definition at line 81 of file vtooldoublepoint.cpp.
References changePointName1Position(), changePointName2Position(), VSimplePoint::Choosed(), complexToolTip(), VDataTool::data, VAbstractSimple::Delete(), VAbstractPoint::deletePoint(), firstPoint, VSimplePoint::nameChangedPosition(), p1id, p2id, point1Chosen(), point1Selected(), point2Chosen(), point2Selected(), qApp, VScenePoint::refreshPointGeometry(), secondPoint, VSimplePoint::Selected(), VAbstractSimple::showContextMenu(), and VDrawTool::showContextMenu().
~VToolDoublePoint()
virtual VToolDoublePoint::~VToolDoublePoint () virtual
Member Function Documentation
AddToFile()
void VToolDoublePoint::AddToFile () protected virtual
AddToFile add tag with Information about tool into file.
Reimplemented from VDrawTool.
Definition at line 426 of file vtooldoublepoint.cpp.
References VDrawTool::AddToCalculation(), VAbstractTool::doc, VContainer::GetFakeGObject(), VAbstractPoint::getTagName(), VAbstractTool::m_id, and SaveOptions().
AllowHover
void VToolDoublePoint::AllowHover (bool enabled) virtual slot
Definition at line 276 of file vtooldoublepoint.cpp.
References firstPoint, and secondPoint.
AllowSelecting
void VToolDoublePoint::AllowSelecting (bool enabled) virtual slot
Definition at line 283 of file vtooldoublepoint.cpp.
References firstPoint, and secondPoint.
allowTextHover
void VToolDoublePoint::allowTextHover (bool enabled) slot
Definition at line 290 of file vtooldoublepoint.cpp.
References VSimplePoint::allowTextHover(), firstPoint, and secondPoint.
allowTextSelectable
void VToolDoublePoint::allowTextSelectable (bool enabled) slot
Definition at line 297 of file vtooldoublepoint.cpp.
References VSimplePoint::allowTextSelectable(), firstPoint, and secondPoint.
changePointName1Position
void VToolDoublePoint::changePointName1Position (const QPointF & pos) slot
Definition at line 183 of file vtooldoublepoint.cpp.
References firstPoint, p1id, and updatePointNamePosition().
Referenced by VToolDoublePoint().
changePointName2Position
void VToolDoublePoint::changePointName2Position (const QPointF & pos) slot
Definition at line 189 of file vtooldoublepoint.cpp.
References p2id, secondPoint, and updatePointNamePosition().
Referenced by VToolDoublePoint().
complexToolTip()
QString VToolDoublePoint::complexToolTip (quint32 itemId) const protected
Definition at line 448 of file vtooldoublepoint.cpp.
References VDataTool::data, VContainer::GeometricObject(), and VDrawTool::makeToolTip().
Referenced by FullUpdateFromFile(), and VToolDoublePoint().
contextMenuEvent()
void VToolDoublePoint::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected virtual
Definition at line 376 of file vtooldoublepoint.cpp.
References VDrawTool::showContextMenu().
Disable
void VToolDoublePoint::Disable (bool disable, const QString & draftBlockName) virtual slot
Definition at line 195 of file vtooldoublepoint.cpp.
References VDrawTool::CorrectDisable(), firstPoint, secondPoint, and VSimplePoint::SetEnabled().
EnableToolMove
void VToolDoublePoint::EnableToolMove (bool move) virtual slot
Definition at line 204 of file vtooldoublepoint.cpp.
References VSimplePoint::EnableToolMove(), firstPoint, and secondPoint.
FullUpdateFromFile
void VToolDoublePoint::FullUpdateFromFile () virtual slot
Definition at line 235 of file vtooldoublepoint.cpp.
References complexToolTip(), VDataTool::data, firstPoint, p1id, p2id, VDrawTool::ReadAttributes(), VScenePoint::refreshPointGeometry(), secondPoint, and VAbstractTool::SetVisualization().
GroupVisibility()
void VToolDoublePoint::GroupVisibility (quint32 object, bool visible) virtual
Implements VDataTool.
Definition at line 136 of file vtooldoublepoint.cpp.
References firstPoint, p1id, p2id, and secondPoint.
isPointNameVisible()
bool VToolDoublePoint::isPointNameVisible (quint32 id) const virtual
Reimplemented from VDrawTool.
Definition at line 149 of file vtooldoublepoint.cpp.
References VDataTool::data, VContainer::GeometricObject(), p1id, and p2id.
itemChange()
QVariant VToolDoublePoint::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
itemChange hadle item change.
Parameters
change change.
value value.
Returns
value.
Definition at line 331 of file vtooldoublepoint.cpp.
keyReleaseEvent()
void VToolDoublePoint::keyReleaseEvent (QKeyEvent * event) protected virtual
keyReleaseEvent handle key release events.
Parameters
event key release event.
Definition at line 354 of file vtooldoublepoint.cpp.
References VAbstractTool::deleteTool().
nameP1()
QString VToolDoublePoint::nameP1 () const
Definition at line 112 of file vtooldoublepoint.cpp.
References p1id.
Referenced by VToolOptionsPropertyBrowser::updateOptionsToolTrueDarts().
nameP2()
QString VToolDoublePoint::nameP2 () const
Definition at line 124 of file vtooldoublepoint.cpp.
References p2id.
Referenced by VToolOptionsPropertyBrowser::updateOptionsToolTrueDarts().
point1Chosen
void VToolDoublePoint::point1Chosen () slot
Definition at line 211 of file vtooldoublepoint.cpp.
References VAbstractTool::chosenTool(), p1id, and Point.
Referenced by VToolDoublePoint().
point1Selected
void VToolDoublePoint::point1Selected (bool selected) slot
Definition at line 223 of file vtooldoublepoint.cpp.
References VDrawTool::ChangedToolSelection(), VAbstractTool::m_id, and p1id.
Referenced by VToolDoublePoint().
point2Chosen
void VToolDoublePoint::point2Chosen () slot
Definition at line 217 of file vtooldoublepoint.cpp.
References VAbstractTool::chosenTool(), p2id, and Point.
Referenced by VToolDoublePoint().
point2Selected
void VToolDoublePoint::point2Selected (bool selected) slot
Definition at line 229 of file vtooldoublepoint.cpp.
References VDrawTool::ChangedToolSelection(), VAbstractTool::m_id, and p2id.
Referenced by VToolDoublePoint().
SaveOptions()
void VToolDoublePoint::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VDrawTool.
Reimplemented in VToolTrueDarts.
Definition at line 382 of file vtooldoublepoint.cpp.
References AttrMx1, AttrMx2, AttrMy1, AttrMy2, AttrName1, AttrName2, AttrPoint1, AttrPoint2, AttrShowPointName1, AttrShowPointName2, VDataTool::data, VAbstractTool::doc, VContainer::GeometricObject(), VPointF::isShowPointName(), VPointF::mx(), VPointF::my(), VGObject::name(), p1id, p2id, qApp, VDrawTool::SaveOptions(), SCASSERT, and VDomDocument::SetAttribute().
Referenced by AddToFile(), and VToolTrueDarts::SaveOptions().
setNameP1()
void VToolDoublePoint::setNameP1 (const QString & name)
Definition at line 118 of file vtooldoublepoint.cpp.
References p1id, and VAbstractPoint::SetPointName().
setNameP2()
void VToolDoublePoint::setNameP2 (const QString & name)
Definition at line 130 of file vtooldoublepoint.cpp.
References p2id, and VAbstractPoint::SetPointName().
setPointNamePosition()
void VToolDoublePoint::setPointNamePosition (quint32 id, const QPointF & pos) virtual
Reimplemented from VAbstractTool.
Definition at line 247 of file vtooldoublepoint.cpp.
References VDataTool::data, firstPoint, VMainGraphicsView::NewSceneRect(), p1id, p2id, qApp, VScenePoint::refreshPointGeometry(), secondPoint, VPointF::setMx(), and VPointF::setMy().
setPointNameVisiblity()
void VToolDoublePoint::setPointNameVisiblity (quint32 id, bool visible) virtual
Reimplemented from VAbstractTool.
Definition at line 166 of file vtooldoublepoint.cpp.
References VDataTool::data, firstPoint, VContainer::GeometricObject(), p1id, p2id, VScenePoint::refreshPointGeometry(), and secondPoint.
ToolSelectionType
void VToolDoublePoint::ToolSelectionType (const SelectionType & type) virtual slot
Definition at line 304 of file vtooldoublepoint.cpp.
References firstPoint, secondPoint, VAbstractTool::ToolSelectionType(), VSimplePoint::ToolSelectionType(), and type().
type()
virtual int VToolDoublePoint::type () const inline virtual
Reimplemented in VToolTrueDarts.
Definition at line 79 of file vtooldoublepoint.h.
References Type.
Referenced by ToolSelectionType().
updatePointNamePosition()
void VToolDoublePoint::updatePointNamePosition (quint32 id, const QPointF & pos) protected virtual
Implements VAbstractPoint.
Definition at line 312 of file vtooldoublepoint.cpp.
References VAbstractTool::doc, FirstPoint, VAbstractTool::m_id, MoveDoubleLabel, p1id, p2id, qApp, and SecondPoint.
Referenced by changePointName1Position(), and changePointName2Position().
updatePointNameVisibility()
void VToolDoublePoint::updatePointNameVisibility (quint32 id, bool visible) protected virtual
Reimplemented from VDrawTool.
Definition at line 435 of file vtooldoublepoint.cpp.
References VAbstractTool::doc, FirstPoint, VAbstractTool::m_id, p1id, p2id, qApp, and SecondPoint.
Member Data Documentation
firstPoint
VSimplePoint* VToolDoublePoint::firstPoint protected
Definition at line 110 of file vtooldoublepoint.h.
Referenced by AllowHover(), AllowSelecting(), allowTextHover(), allowTextSelectable(), changePointName1Position(), Disable(), EnableToolMove(), FullUpdateFromFile(), GroupVisibility(), setPointNamePosition(), setPointNameVisiblity(), ToolSelectionType(), and VToolDoublePoint().
p1id
quint32 VToolDoublePoint::p1id protected
Definition at line 113 of file vtooldoublepoint.h.
Referenced by changePointName1Position(), VToolTrueDarts::Create(), FullUpdateFromFile(), GroupVisibility(), isPointNameVisible(), nameP1(), point1Chosen(), point1Selected(), SaveOptions(), VToolTrueDarts::setDialog(), setNameP1(), setPointNamePosition(), setPointNameVisiblity(), updatePointNamePosition(), updatePointNameVisibility(), and VToolDoublePoint().
p2id
quint32 VToolDoublePoint::p2id protected
Definition at line 114 of file vtooldoublepoint.h.
Referenced by changePointName2Position(), VToolTrueDarts::Create(), FullUpdateFromFile(), GroupVisibility(), isPointNameVisible(), nameP2(), point2Chosen(), point2Selected(), SaveOptions(), VToolTrueDarts::setDialog(), setNameP2(), setPointNamePosition(), setPointNameVisiblity(), updatePointNamePosition(), updatePointNameVisibility(), and VToolDoublePoint().
secondPoint
VSimplePoint* VToolDoublePoint::secondPoint protected
Definition at line 111 of file vtooldoublepoint.h.
Referenced by AllowHover(), AllowSelecting(), allowTextHover(), allowTextSelectable(), changePointName2Position(), Disable(), EnableToolMove(), FullUpdateFromFile(), GroupVisibility(), setPointNamePosition(), setPointNameVisiblity(), ToolSelectionType(), and VToolDoublePoint().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/toolpoint/tooldoublepoint/vtooldoublepoint.h
src/libs/vtools/tools/drawTools/toolpoint/tooldoublepoint/vtooldoublepoint.cpp