Seamly2D: VPE::VBoolProperty Class Reference
VPE::VBoolProperty Class Reference
The VBoolProperty can take two states: True or False.
#include <vboolproperty.h>
Public Member Functions
VBoolProperty (const QString &name)
Default constructor.
virtual ~VBoolProperty () Q_DECL_OVERRIDE
Destructor.
virtual QVariant data (int column=DPC_Name, int role=Qt::DisplayRole) const Q_DECL_OVERRIDE
Get the data how it should be displayed.
virtual bool setData (const QVariant &data, int role=Qt::EditRole) Q_DECL_OVERRIDE
This is used by the model to set the data.
virtual Qt::ItemFlags flags (int column=DPC_Name) const Q_DECL_OVERRIDE
Returns item flags.
virtual QString type () const Q_DECL_OVERRIDE
Returns a string containing the type of the property.
virtual VProperty * clone (bool include_children=true, VProperty *container=NULL) const Q_DECL_OVERRIDE
Clones this property.
Public Member Functions inherited from VPE::VProperty
VProperty (const QString &name, QVariant::Type type=QVariant::String)
Standard constructor, takes a name and a parent property as argument.
virtual ~VProperty () Q_DECL_OVERRIDE
Destructor.
virtual bool paint (QPainter *, const QStyleOptionViewItem &, const QModelIndex &, const QAbstractItemDelegate *) const
This is called by the delegate when the property value is being drawn. The standard implementation doesn't do anything. If you reimplement this in a sub property, make sure to return true or the delegate will draw the item.
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &, const QAbstractItemDelegate *)
Returns an editor widget, or NULL if it doesn't supply one.
virtual bool setEditorData (QWidget *editor)
Sets the property's data to the editor (returns false, if the standard delegate should do that)
virtual QVariant getEditorData (const QWidget *editor) const
Gets the data from the widget.
virtual void setValue (const QVariant &value)
Sets the value of the property.
virtual QVariant getValue () const
Returns the value of the property as a QVariant.
virtual QString serialize () const
Serializes the value to a string.
virtual void deserialize (const QString &value)
Deserializes the value from a string.
virtual void setName (const QString &name)
Sets the name of the property.
virtual QString getName () const
Gets the name of the property.
virtual void setDescription (const QString &desc)
Sets the name of the property.
virtual QString getDescription () const
Gets the name of the property.
virtual int addChild (VProperty *child)
Adds a child to this property.
virtual QList< VProperty * > & getChildren ()
Returns a reference to the list of children.
virtual const QList< VProperty * > & getChildren () const
Returns a reference to the list of children.
virtual VProperty * getChild (int row) const
Returns the child at a certain row.
virtual int getRowCount () const
Gets the number of children.
virtual VProperty * getParent () const
Gets the parent of this property.
virtual void setParent (VProperty *parent)
Sets the parent of this property.
virtual void removeChild (VProperty *child)
Removes a child from the children list, doesn't delete the child!
virtual int getChildRow (VProperty *child) const
Returns the row the child has.
virtual bool getUpdateParent () const
Returns whether the views have to update the parent of this property if it changes.
virtual bool getUpdateChildren () const
Returns whether the views have to update the children of this property if it changes.
virtual void setUpdateBehaviour (bool update_parent, bool update_children)
Sets whether the views should update Parents or children after this property changes.
virtual void setSettings (const QMap< QString, QVariant > &settings)
Sets the settings by calling the overloaded setSetting(const QString &key, const QVariant &value) for each item in the map.
virtual QMap< QString, QVariant > getSettings () const
Get the settings.
virtual void setSetting (const QString &key, const QVariant &value)
Sets the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QVariant getSetting (const QString &key) const
Get the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QStringList getSettingKeys () const
Returns the list of keys of the property's settings.
Property propertyType () const
void setPropertyType (const Property &type)
virtual void updateParent (const QVariant &value)
Static Protected Attributes
static QVariant TrueText
The (translatable) text displayed when the property is set to true (default: "True")
static QVariant FalseText
The (translatable) text displayed when the property is set to false (default: "False")
Additional Inherited Members
Public Types inherited from VPE::VProperty
enum DPC_DisplayColumn { DPC_Name = 0 , DPC_Data }
Public Slots inherited from VPE::VProperty
virtual void childValueChanged (const QVariant &value, int typeForParent)
Signals inherited from VPE::VProperty
void childChanged (const QVariant &value, int typeForParent)
Protected Member Functions inherited from VPE::VProperty
VProperty (VPropertyPrivate *d)
Protected constructor.
Protected Attributes inherited from VPE::VProperty
VPropertyPrivate * d_ptr
The protected structure holding the member variables (to assure binary compatibility)
Detailed Description
The VBoolProperty can take two states: True or False.
Definition at line 39 of file vboolproperty.h.
Constructor & Destructor Documentation
VBoolProperty()
VPE::VBoolProperty::VBoolProperty (const QString & name) explicit
Default constructor.
Definition at line 32 of file vboolproperty.cpp.
References VPE::VProperty::d_ptr, FalseText, TrueText, and VPE::VPropertyPrivate::VariantValue.
~VBoolProperty()
virtual VPE::VBoolProperty::~VBoolProperty () inline virtual
Destructor.
Definition at line 47 of file vboolproperty.h.
Member Function Documentation
clone()
VPE::VProperty * VPE::VBoolProperty::clone (bool include_children = true, VProperty * container = NULL) const virtual
Clones this property.
Parameters
include_children Indicates whether to also clone the children
container If a property is being passed here, no new VProperty is being created but instead it is tried to fill all the data into container. This can also be used when subclassing this function.
Returns
Returns the newly created property (or container, if it was not NULL)
Reimplemented from VPE::VProperty.
Definition at line 92 of file vboolproperty.cpp.
References VPE::VProperty::clone().
data()
QVariant VPE::VBoolProperty::data (int column = DPC_Name, int role = Qt::DisplayRole) const virtual
Get the data how it should be displayed.
Reimplemented from VPE::VProperty.
Definition at line 51 of file vboolproperty.cpp.
References VPE::VProperty::data().
flags()
Qt::ItemFlags VPE::VBoolProperty::flags (int column = DPC_Name) const virtual
Returns item flags.
Reimplemented from VPE::VProperty.
Definition at line 77 of file vboolproperty.cpp.
References VPE::VProperty::flags().
setData()
bool VPE::VBoolProperty::setData (const QVariant & data, int role = Qt::EditRole) virtual
This is used by the model to set the data.
Parameters
data The data to set
role The role. Default is Qt::EditRole
Returns
Returns true, if the data was changed, false if not.
Reimplemented from VPE::VProperty.
Definition at line 65 of file vboolproperty.cpp.
type()
QString VPE::VBoolProperty::type () const virtual
Returns a string containing the type of the property.
Reimplemented from VPE::VProperty.
Definition at line 87 of file vboolproperty.cpp.
Member Data Documentation
FalseText
QVariant VPE::VBoolProperty::FalseText static protected
The (translatable) text displayed when the property is set to false (default: "False")
Definition at line 76 of file vboolproperty.h.
Referenced by VBoolProperty().
TrueText
QVariant VPE::VBoolProperty::TrueText static protected
The (translatable) text displayed when the property is set to true (default: "True")
Definition at line 73 of file vboolproperty.h.
Referenced by VBoolProperty().
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/plugins/vboolproperty.h
src/libs/vpropertyexplorer/plugins/vboolproperty.cpp