Seamly2D: TST_Measurements Class Reference
TST_Measurements Class Reference
#include <tst_vmeasurements.h>
Public Member Functions
TST_Measurements (QObject *parent=nullptr)
Private Slots
void CreateEmptyMultisizeFile ()
CreateEmptyMultisizeFile check if empty multisize measurement file is valid.
void CreateEmptyIndividualFile ()
CreateEmptyIndividualFile check if empty individual measurement file is valid.
void ValidPMCodesMultisizeFile ()
ValidPMCodesMultisizeFile helps to check that all current pattern making systems match pattern inside XSD scheme.
void ValidPMCodesIndividualFile ()
ValidPMCodesIndividualFile helps to check that all current pattern making systems match pattern inside XSD scheme.
Detailed Description
Definition at line 57 of file tst_vmeasurements.h.
Constructor & Destructor Documentation
TST_Measurements()
TST_Measurements::TST_Measurements (QObject * parent = nullptr) explicit
Definition at line 66 of file tst_vmeasurements.cpp.
Member Function Documentation
CreateEmptyIndividualFile
void TST_Measurements::CreateEmptyIndividualFile () private slot
CreateEmptyIndividualFile check if empty individual measurement file is valid.
Definition at line 124 of file tst_vmeasurements.cpp.
References Cm, IndividualSizeConverter::CurrentSchema, VException::ErrorMessage(), and VDomDocument::ValidateXML().
CreateEmptyMultisizeFile
void TST_Measurements::CreateEmptyMultisizeFile () private slot
CreateEmptyMultisizeFile check if empty multisize measurement file is valid.
Definition at line 75 of file tst_vmeasurements.cpp.
References Cm, MultiSizeConverter::CurrentSchema, VException::ErrorMessage(), VContainer::rheight(), VContainer::rsize(), VContainer::setHeight(), VContainer::setSize(), and VDomDocument::ValidateXML().
ValidPMCodesIndividualFile
void TST_Measurements::ValidPMCodesIndividualFile () private slot
ValidPMCodesIndividualFile helps to check that all current pattern making systems match pattern inside XSD scheme.
Definition at line 222 of file tst_vmeasurements.cpp.
References Cm, IndividualSizeConverter::CurrentSchema, VException::ErrorMessage(), ListPMSystems(), and VDomDocument::ValidateXML().
ValidPMCodesMultisizeFile
void TST_Measurements::ValidPMCodesMultisizeFile () private slot
ValidPMCodesMultisizeFile helps to check that all current pattern making systems match pattern inside XSD scheme.
Definition at line 165 of file tst_vmeasurements.cpp.
References Cm, MultiSizeConverter::CurrentSchema, VException::ErrorMessage(), ListPMSystems(), VContainer::rheight(), VContainer::rsize(), VContainer::setHeight(), VContainer::setSize(), and VDomDocument::ValidateXML().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vmeasurements.h
src/test/Seamly2DTest/tst_vmeasurements.cpp