Seamly2D: SchemaElementDecl Class Reference
SchemaElementDecl Class Reference
#include <SchemaElementDecl.hpp>
Public Types
enum ModelTypes {
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count ,
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count ,
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count
}
enum ModelTypes {
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count ,
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count ,
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count
}
enum ModelTypes {
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count ,
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count ,
Empty , Any , Mixed_Simple , Mixed_Complex ,
Children , Simple , ElementOnlyEmpty , ModelTypes_Count
}
Public Types inherited from XMLElementDecl
enum CreateReasons {
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn , NoReason , Declared ,
AttList , InContentModel , AsRootElem , JustFaultIn ,
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn
}
enum CharDataOpts {
NoCharData , SpacesOk , AllCharData , NoCharData ,
SpacesOk , AllCharData , NoCharData , SpacesOk ,
AllCharData
}
enum CreateReasons {
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn , NoReason , Declared ,
AttList , InContentModel , AsRootElem , JustFaultIn ,
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn
}
enum CharDataOpts {
NoCharData , SpacesOk , AllCharData , NoCharData ,
SpacesOk , AllCharData , NoCharData , SpacesOk ,
AllCharData
}
enum CreateReasons {
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn , NoReason , Declared ,
AttList , InContentModel , AsRootElem , JustFaultIn ,
NoReason , Declared , AttList , InContentModel ,
AsRootElem , JustFaultIn
}
enum CharDataOpts {
NoCharData , SpacesOk , AllCharData , NoCharData ,
SpacesOk , AllCharData , NoCharData , SpacesOk ,
AllCharData
}
enum objectType {
Schema , DTD , UnKnown , Schema ,
DTD , UnKnown , Schema , DTD ,
UnKnown
}
enum objectType {
Schema , DTD , UnKnown , Schema ,
DTD , UnKnown , Schema , DTD ,
UnKnown
}
enum objectType {
Schema , DTD , UnKnown , Schema ,
DTD , UnKnown , Schema , DTD ,
UnKnown
}
Public Member Functions
SchemaElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const ModelTypes modelType=Any, const unsigned int enclosingScope=Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl (const QName *const elementName, const ModelTypes modelType=Any, const unsigned int enclosingScope=Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~SchemaElementDecl ()
virtual XMLAttDefList & getAttDefList () const
virtual CharDataOpts getCharDataOpts () const
virtual bool hasAttDefs () const
virtual const ContentSpecNode * getContentSpec () const
virtual ContentSpecNode * getContentSpec ()
virtual void setContentSpec (ContentSpecNode *toAdopt)
virtual XMLContentModel * getContentModel ()
virtual void setContentModel (XMLContentModel *const newModelToAdopt)
virtual const XMLCh * getFormattedContentModel () const
const SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId) const
SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId)
const SchemaAttDef * getAttWildCard () const
SchemaAttDef * getAttWildCard ()
ModelTypes getModelType () const
PSVIDefs::PSVIScope getPSVIScope () const
DatatypeValidator * getDatatypeValidator () const
unsigned int getEnclosingScope () const
int getFinalSet () const
int getBlockSet () const
int getMiscFlags () const
XMLCh * getDefaultValue () const
ComplexTypeInfo * getComplexTypeInfo () const
virtual bool isGlobalDecl () const
SchemaElementDecl * getSubstitutionGroupElem () const
void setModelType (const SchemaElementDecl::ModelTypes toSet)
void setPSVIScope (const PSVIDefs::PSVIScope toSet)
void setDatatypeValidator (DatatypeValidator *newDatatypeValidator)
void setEnclosingScope (const unsigned int enclosingScope)
void setFinalSet (const int finalSet)
void setBlockSet (const int blockSet)
void setMiscFlags (const int flags)
void setDefaultValue (const XMLCh *const value)
void setComplexTypeInfo (ComplexTypeInfo *const typeInfo)
void setAttWildCard (SchemaAttDef *const attWildCard)
void setSubstitutionGroupElem (SchemaElementDecl *const elemDecl)
void addIdentityConstraint (IdentityConstraint *const ic)
XMLSize_t getIdentityConstraintCount () const
IdentityConstraint * getIdentityConstraintAt (XMLSize_t index) const
virtual XMLElementDecl::objectType getObjectType () const
SchemaElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const ModelTypes modelType=Any, const unsigned int enclosingScope=Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl (const QName *const elementName, const ModelTypes modelType=Any, const unsigned int enclosingScope=Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~SchemaElementDecl ()
virtual XMLAttDefList & getAttDefList () const
virtual CharDataOpts getCharDataOpts () const
virtual bool hasAttDefs () const
virtual const ContentSpecNode * getContentSpec () const
virtual ContentSpecNode * getContentSpec ()
virtual void setContentSpec (ContentSpecNode *toAdopt)
virtual XMLContentModel * getContentModel ()
virtual void setContentModel (XMLContentModel *const newModelToAdopt)
virtual const XMLCh * getFormattedContentModel () const
const SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId) const
SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId)
const SchemaAttDef * getAttWildCard () const
SchemaAttDef * getAttWildCard ()
ModelTypes getModelType () const
PSVIDefs::PSVIScope getPSVIScope () const
DatatypeValidator * getDatatypeValidator () const
unsigned int getEnclosingScope () const
int getFinalSet () const
int getBlockSet () const
int getMiscFlags () const
XMLCh * getDefaultValue () const
ComplexTypeInfo * getComplexTypeInfo () const
virtual bool isGlobalDecl () const
SchemaElementDecl * getSubstitutionGroupElem () const
void setModelType (const SchemaElementDecl::ModelTypes toSet)
void setPSVIScope (const PSVIDefs::PSVIScope toSet)
void setDatatypeValidator (DatatypeValidator *newDatatypeValidator)
void setEnclosingScope (const unsigned int enclosingScope)
void setFinalSet (const int finalSet)
void setBlockSet (const int blockSet)
void setMiscFlags (const int flags)
void setDefaultValue (const XMLCh *const value)
void setComplexTypeInfo (ComplexTypeInfo *const typeInfo)
void setAttWildCard (SchemaAttDef *const attWildCard)
void setSubstitutionGroupElem (SchemaElementDecl *const elemDecl)
void addIdentityConstraint (IdentityConstraint *const ic)
XMLSize_t getIdentityConstraintCount () const
IdentityConstraint * getIdentityConstraintAt (XMLSize_t index) const
virtual XMLElementDecl::objectType getObjectType () const
SchemaElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const ModelTypes modelType=Any, const unsigned int enclosingScope=Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl (const QName *const elementName, const ModelTypes modelType=Any, const unsigned int enclosingScope=Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~SchemaElementDecl ()
virtual XMLAttDefList & getAttDefList () const
virtual CharDataOpts getCharDataOpts () const
virtual bool hasAttDefs () const
virtual const ContentSpecNode * getContentSpec () const
virtual ContentSpecNode * getContentSpec ()
virtual void setContentSpec (ContentSpecNode *toAdopt)
virtual XMLContentModel * getContentModel ()
virtual void setContentModel (XMLContentModel *const newModelToAdopt)
virtual const XMLCh * getFormattedContentModel () const
const SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId) const
SchemaAttDef * getAttDef (const XMLCh *const baseName, const int uriId)
const SchemaAttDef * getAttWildCard () const
SchemaAttDef * getAttWildCard ()
ModelTypes getModelType () const
PSVIDefs::PSVIScope getPSVIScope () const
DatatypeValidator * getDatatypeValidator () const
unsigned int getEnclosingScope () const
int getFinalSet () const
int getBlockSet () const
int getMiscFlags () const
XMLCh * getDefaultValue () const
ComplexTypeInfo * getComplexTypeInfo () const
virtual bool isGlobalDecl () const
SchemaElementDecl * getSubstitutionGroupElem () const
void setModelType (const SchemaElementDecl::ModelTypes toSet)
void setPSVIScope (const PSVIDefs::PSVIScope toSet)
void setDatatypeValidator (DatatypeValidator *newDatatypeValidator)
void setEnclosingScope (const unsigned int enclosingScope)
void setFinalSet (const int finalSet)
void setBlockSet (const int blockSet)
void setMiscFlags (const int flags)
void setDefaultValue (const XMLCh *const value)
void setComplexTypeInfo (ComplexTypeInfo *const typeInfo)
void setAttWildCard (SchemaAttDef *const attWildCard)
void setSubstitutionGroupElem (SchemaElementDecl *const elemDecl)
void addIdentityConstraint (IdentityConstraint *const ic)
XMLSize_t getIdentityConstraintCount () const
IdentityConstraint * getIdentityConstraintAt (XMLSize_t index) const
virtual XMLElementDecl::objectType getObjectType () const
Public Member Functions inherited from XMLElementDecl
virtual ~XMLElementDecl ()
virtual ~XMLElementDecl ()
virtual ~XMLElementDecl ()
const XMLCh * getBaseName () const
XMLCh * getBaseName ()
unsigned int getURI () const
const QName * getElementName () const
QName * getElementName ()
const XMLCh * getFullName () const
CreateReasons getCreateReason () const
XMLSize_t getId () const
bool isDeclared () const
bool isExternal () const
MemoryManager * getMemoryManager () const
const XMLCh * getBaseName () const
XMLCh * getBaseName ()
unsigned int getURI () const
const QName * getElementName () const
QName * getElementName ()
const XMLCh * getFullName () const
CreateReasons getCreateReason () const
XMLSize_t getId () const
bool isDeclared () const
bool isExternal () const
MemoryManager * getMemoryManager () const
const XMLCh * getBaseName () const
XMLCh * getBaseName ()
unsigned int getURI () const
const QName * getElementName () const
QName * getElementName ()
const XMLCh * getFullName () const
CreateReasons getCreateReason () const
XMLSize_t getId () const
bool isDeclared () const
bool isExternal () const
MemoryManager * getMemoryManager () const
void setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
void setElementName (const XMLCh *const rawName, const int uriId)
void setElementName (const QName *const elementName)
void setCreateReason (const CreateReasons newReason)
void setId (const XMLSize_t newId)
void setExternalElemDeclaration (const bool aValue)
void setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
void setElementName (const XMLCh *const rawName, const int uriId)
void setElementName (const QName *const elementName)
void setCreateReason (const CreateReasons newReason)
void setId (const XMLSize_t newId)
void setExternalElemDeclaration (const bool aValue)
void setElementName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId)
void setElementName (const XMLCh *const rawName, const int uriId)
void setElementName (const QName *const elementName)
void setCreateReason (const CreateReasons newReason)
void setId (const XMLSize_t newId)
void setExternalElemDeclaration (const bool aValue)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
SchemaElementDecl (const SchemaElementDecl &)
SchemaElementDecl & operator= (const SchemaElementDecl &)
SchemaElementDecl (const SchemaElementDecl &)
SchemaElementDecl & operator= (const SchemaElementDecl &)
SchemaElementDecl (const SchemaElementDecl &)
SchemaElementDecl & operator= (const SchemaElementDecl &)
Private Attributes
ModelTypes fModelType
PSVIDefs::PSVIScope fPSVIScope
unsigned int fEnclosingScope
int fFinalSet
int fBlockSet
int fMiscFlags
XMLCh * fDefaultValue
ComplexTypeInfo * fComplexTypeInfo
RefHash2KeysTableOf< SchemaAttDef > * fAttDefs
RefVectorOf< IdentityConstraint > * fIdentityConstraints
SchemaAttDef * fAttWildCard
SchemaElementDecl * fSubstitutionGroupElem
DatatypeValidator * fDatatypeValidator
Additional Inherited Members
Static Public Member Functions inherited from XMLElementDecl
static void storeElementDecl (XSerializeEngine &serEng, XMLElementDecl *const element)
static XMLElementDecl * loadElementDecl (XSerializeEngine &serEng)
static void storeElementDecl (XSerializeEngine &serEng, XMLElementDecl *const element)
static XMLElementDecl * loadElementDecl (XSerializeEngine &serEng)
static void storeElementDecl (XSerializeEngine &serEng, XMLElementDecl *const element)
static XMLElementDecl * loadElementDecl (XSerializeEngine &serEng)
Static Public Attributes inherited from XMLElementDecl
static const unsigned int fgInvalidElemId
static const unsigned int fgPCDataElemId
static const XMLCh fgPCDataElemName []
Protected Member Functions inherited from XMLElementDecl
XMLElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLElementDecl (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 41 of file SchemaElementDecl.hpp.
Member Enumeration Documentation
ModelTypes [1/3]
enum SchemaElementDecl::ModelTypes
Enumerator
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Definition at line 52 of file SchemaElementDecl.hpp.
ModelTypes [2/3]
enum SchemaElementDecl::ModelTypes
Enumerator
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Definition at line 52 of file SchemaElementDecl.hpp.
ModelTypes [3/3]
enum SchemaElementDecl::ModelTypes
Enumerator
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Empty
Any
Mixed_Simple
Mixed_Complex
Children
Simple
ElementOnlyEmpty
ModelTypes_Count
Definition at line 52 of file SchemaElementDecl.hpp.
Constructor & Destructor Documentation
SchemaElementDecl() [1/12]
SchemaElementDecl::SchemaElementDecl (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl() [2/12]
SchemaElementDecl::SchemaElementDecl (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const ModelTypes modelType = Any, const unsigned int enclosingScope = Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl() [3/12]
SchemaElementDecl::SchemaElementDecl (const QName *const elementName, const ModelTypes modelType = Any, const unsigned int enclosingScope = Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaElementDecl() [1/3]
SchemaElementDecl::~SchemaElementDecl ()
SchemaElementDecl() [4/12]
SchemaElementDecl::SchemaElementDecl (const SchemaElementDecl &) private
SchemaElementDecl() [5/12]
SchemaElementDecl::SchemaElementDecl (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl() [6/12]
SchemaElementDecl::SchemaElementDecl (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const ModelTypes modelType = Any, const unsigned int enclosingScope = Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl() [7/12]
SchemaElementDecl::SchemaElementDecl (const QName *const elementName, const ModelTypes modelType = Any, const unsigned int enclosingScope = Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaElementDecl() [2/3]
SchemaElementDecl::~SchemaElementDecl ()
SchemaElementDecl() [8/12]
SchemaElementDecl::SchemaElementDecl (const SchemaElementDecl &) private
SchemaElementDecl() [9/12]
SchemaElementDecl::SchemaElementDecl (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl() [10/12]
SchemaElementDecl::SchemaElementDecl (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const ModelTypes modelType = Any, const unsigned int enclosingScope = Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaElementDecl() [11/12]
SchemaElementDecl::SchemaElementDecl (const QName *const elementName, const ModelTypes modelType = Any, const unsigned int enclosingScope = Grammar::TOP_LEVEL_SCOPE, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaElementDecl() [3/3]
SchemaElementDecl::~SchemaElementDecl ()
SchemaElementDecl() [12/12]
SchemaElementDecl::SchemaElementDecl (const SchemaElementDecl &) private
Member Function Documentation
addIdentityConstraint() [1/3]
void SchemaElementDecl::addIdentityConstraint (IdentityConstraint *const ic) inline
Definition at line 408 of file SchemaElementDecl.hpp.
References BaseRefVectorOf< TElem >::addElement(), and XMLElementDecl::getMemoryManager().
addIdentityConstraint() [2/3]
void SchemaElementDecl::addIdentityConstraint (IdentityConstraint *const ic)
addIdentityConstraint() [3/3]
void SchemaElementDecl::addIdentityConstraint (IdentityConstraint *const ic)
getAttDef() [1/6]
SchemaAttDef* SchemaElementDecl::getAttDef (const XMLCh *const baseName, const int uriId)
getAttDef() [2/6]
SchemaAttDef* SchemaElementDecl::getAttDef (const XMLCh *const baseName, const int uriId)
getAttDef() [3/6]
SchemaAttDef* SchemaElementDecl::getAttDef (const XMLCh *const baseName, const int uriId)
getAttDef() [4/6]
const SchemaAttDef* SchemaElementDecl::getAttDef (const XMLCh *const baseName, const int uriId) const
getAttDef() [5/6]
const SchemaAttDef* SchemaElementDecl::getAttDef (const XMLCh *const baseName, const int uriId) const
getAttDef() [6/6]
const SchemaAttDef* SchemaElementDecl::getAttDef (const XMLCh *const baseName, const int uriId) const
getAttDefList() [1/3]
virtual XMLAttDefList& SchemaElementDecl::getAttDefList () const virtual
Get a list of attributes defined for this element.
The derived class should return a reference to some member object which implements the XMLAttDefList interface. This object gives the scanner the ability to look through the attributes defined for this element.
It is done this way for efficiency, though of course this is not thread safe. The scanner guarantees that it won't ever call this method in any nested way, but the outside world must be careful about when it calls this method, and optimally never would.
Implements XMLElementDecl.
getAttDefList() [2/3]
virtual XMLAttDefList& SchemaElementDecl::getAttDefList () const virtual
Get a list of attributes defined for this element.
The derived class should return a reference to some member object which implements the XMLAttDefList interface. This object gives the scanner the ability to look through the attributes defined for this element.
It is done this way for efficiency, though of course this is not thread safe. The scanner guarantees that it won't ever call this method in any nested way, but the outside world must be careful about when it calls this method, and optimally never would.
Implements XMLElementDecl.
getAttDefList() [3/3]
virtual XMLAttDefList& SchemaElementDecl::getAttDefList () const virtual
Get a list of attributes defined for this element.
The derived class should return a reference to some member object which implements the XMLAttDefList interface. This object gives the scanner the ability to look through the attributes defined for this element.
It is done this way for efficiency, though of course this is not thread safe. The scanner guarantees that it won't ever call this method in any nested way, but the outside world must be careful about when it calls this method, and optimally never would.
Implements XMLElementDecl.
getAttWildCard() [1/6]
SchemaAttDef * SchemaElementDecl::getAttWildCard () inline
Definition at line 319 of file SchemaElementDecl.hpp.
getAttWildCard() [2/6]
SchemaAttDef* SchemaElementDecl::getAttWildCard ()
getAttWildCard() [3/6]
SchemaAttDef* SchemaElementDecl::getAttWildCard ()
getAttWildCard() [4/6]
const SchemaAttDef * SchemaElementDecl::getAttWildCard () const inline
Definition at line 315 of file SchemaElementDecl.hpp.
getAttWildCard() [5/6]
const SchemaAttDef* SchemaElementDecl::getAttWildCard () const
getAttWildCard() [6/6]
const SchemaAttDef* SchemaElementDecl::getAttWildCard () const
getBlockSet() [1/3]
int SchemaElementDecl::getBlockSet () const inline
Definition at line 295 of file SchemaElementDecl.hpp.
getBlockSet() [2/3]
int SchemaElementDecl::getBlockSet () const
getBlockSet() [3/3]
int SchemaElementDecl::getBlockSet () const
getCharDataOpts() [1/3]
virtual CharDataOpts SchemaElementDecl::getCharDataOpts () const virtual
The character data options for this element type
The derived class should return an appropriate character data opts value which correctly represents its tolerance towards whitespace or character data inside of its instances. This allows the scanner to do all of the validation of character data.
Implements XMLElementDecl.
getCharDataOpts() [2/3]
virtual CharDataOpts SchemaElementDecl::getCharDataOpts () const virtual
The character data options for this element type
The derived class should return an appropriate character data opts value which correctly represents its tolerance towards whitespace or character data inside of its instances. This allows the scanner to do all of the validation of character data.
Implements XMLElementDecl.
getCharDataOpts() [3/3]
virtual CharDataOpts SchemaElementDecl::getCharDataOpts () const virtual
The character data options for this element type
The derived class should return an appropriate character data opts value which correctly represents its tolerance towards whitespace or character data inside of its instances. This allows the scanner to do all of the validation of character data.
Implements XMLElementDecl.
getComplexTypeInfo() [1/3]
ComplexTypeInfo * SchemaElementDecl::getComplexTypeInfo () const inline
Definition at line 310 of file SchemaElementDecl.hpp.
getComplexTypeInfo() [2/3]
ComplexTypeInfo* SchemaElementDecl::getComplexTypeInfo () const
getComplexTypeInfo() [3/3]
ComplexTypeInfo* SchemaElementDecl::getComplexTypeInfo () const
getContentModel() [1/3]
XMLContentModel * SchemaElementDecl::getContentModel () inline virtual
Get a pointer to the abstract content model
This method will return a const pointer to the content model object of this element. This class is a simple abstraction that allows an element to define and use multiple, specialized content model types internally but still allow the outside world to do simple stuff with them.
Returns
A pointer to the element's content model, via the basic abstract content model type.
Implements XMLElementDecl.
Definition at line 248 of file SchemaElementDecl.hpp.
getContentModel() [2/3]
virtual XMLContentModel* SchemaElementDecl::getContentModel () virtual
Get a pointer to the abstract content model
This method will return a const pointer to the content model object of this element. This class is a simple abstraction that allows an element to define and use multiple, specialized content model types internally but still allow the outside world to do simple stuff with them.
Returns
A pointer to the element's content model, via the basic abstract content model type.
Implements XMLElementDecl.
getContentModel() [3/3]
virtual XMLContentModel* SchemaElementDecl::getContentModel () virtual
Get a pointer to the abstract content model
This method will return a const pointer to the content model object of this element. This class is a simple abstraction that allows an element to define and use multiple, specialized content model types internally but still allow the outside world to do simple stuff with them.
Returns
A pointer to the element's content model, via the basic abstract content model type.
Implements XMLElementDecl.
getContentSpec() [1/6]
ContentSpecNode * SchemaElementDecl::getContentSpec () inline virtual
Get a pointer to the content spec node
This method is identical to the previous one, except that it is non const.
Implements XMLElementDecl.
Definition at line 224 of file SchemaElementDecl.hpp.
References ComplexTypeInfo::getContentSpec().
getContentSpec() [2/6]
virtual ContentSpecNode* SchemaElementDecl::getContentSpec () virtual
Get a pointer to the content spec node
This method is identical to the previous one, except that it is non const.
Implements XMLElementDecl.
getContentSpec() [3/6]
virtual ContentSpecNode* SchemaElementDecl::getContentSpec () virtual
Get a pointer to the content spec node
This method is identical to the previous one, except that it is non const.
Implements XMLElementDecl.
getContentSpec() [4/6]
const ContentSpecNode * SchemaElementDecl::getContentSpec () const inline virtual
Get a pointer to the content spec node
This method will return a const pointer to the content spec node object of this element.
Returns
A const pointer to the element's content spec node
Implements XMLElementDecl.
Definition at line 233 of file SchemaElementDecl.hpp.
getContentSpec() [5/6]
virtual const ContentSpecNode* SchemaElementDecl::getContentSpec () const virtual
Get a pointer to the content spec node
This method will return a const pointer to the content spec node object of this element.
Returns
A const pointer to the element's content spec node
Implements XMLElementDecl.
getContentSpec() [6/6]
virtual const ContentSpecNode* SchemaElementDecl::getContentSpec () const virtual
Get a pointer to the content spec node
This method will return a const pointer to the content spec node object of this element.
Returns
A const pointer to the element's content spec node
Implements XMLElementDecl.
getDatatypeValidator() [1/3]
DatatypeValidator * SchemaElementDecl::getDatatypeValidator () const inline
Definition at line 280 of file SchemaElementDecl.hpp.
getDatatypeValidator() [2/3]
DatatypeValidator* SchemaElementDecl::getDatatypeValidator () const
getDatatypeValidator() [3/3]
DatatypeValidator* SchemaElementDecl::getDatatypeValidator () const
getDefaultValue() [1/3]
XMLCh * SchemaElementDecl::getDefaultValue () const inline
Definition at line 305 of file SchemaElementDecl.hpp.
getDefaultValue() [2/3]
XMLCh* SchemaElementDecl::getDefaultValue () const
getDefaultValue() [3/3]
XMLCh* SchemaElementDecl::getDefaultValue () const
getEnclosingScope() [1/3]
unsigned int SchemaElementDecl::getEnclosingScope () const inline
Definition at line 285 of file SchemaElementDecl.hpp.
getEnclosingScope() [2/3]
unsigned int SchemaElementDecl::getEnclosingScope () const
getEnclosingScope() [3/3]
unsigned int SchemaElementDecl::getEnclosingScope () const
getFinalSet() [1/3]
int SchemaElementDecl::getFinalSet () const inline
Definition at line 290 of file SchemaElementDecl.hpp.
getFinalSet() [2/3]
int SchemaElementDecl::getFinalSet () const
getFinalSet() [3/3]
int SchemaElementDecl::getFinalSet () const
getFormattedContentModel() [1/3]
virtual const XMLCh* SchemaElementDecl::getFormattedContentModel () const virtual
Geta formatted string of the content model
This method is a convenience method which will create a formatted representation of the content model of the element. It will not always exactly recreate the original model, since some normalization or or reformatting may occur. But, it will be a technically accurate representation of the original content model.
Returns
A pointer to an internal buffer which contains the formatted content model. The caller does not own this buffer and should copy it if it needs to be kept around.
Implements XMLElementDecl.
getFormattedContentModel() [2/3]
virtual const XMLCh* SchemaElementDecl::getFormattedContentModel () const virtual
Geta formatted string of the content model
This method is a convenience method which will create a formatted representation of the content model of the element. It will not always exactly recreate the original model, since some normalization or or reformatting may occur. But, it will be a technically accurate representation of the original content model.
Returns
A pointer to an internal buffer which contains the formatted content model. The caller does not own this buffer and should copy it if it needs to be kept around.
Implements XMLElementDecl.
getFormattedContentModel() [3/3]
virtual const XMLCh* SchemaElementDecl::getFormattedContentModel () const virtual
Geta formatted string of the content model
This method is a convenience method which will create a formatted representation of the content model of the element. It will not always exactly recreate the original model, since some normalization or or reformatting may occur. But, it will be a technically accurate representation of the original content model.
Returns
A pointer to an internal buffer which contains the formatted content model. The caller does not own this buffer and should copy it if it needs to be kept around.
Implements XMLElementDecl.
getIdentityConstraintAt() [1/3]
IdentityConstraint * SchemaElementDecl::getIdentityConstraintAt (XMLSize_t index) const inline
Definition at line 427 of file SchemaElementDecl.hpp.
getIdentityConstraintAt() [2/3]
IdentityConstraint* SchemaElementDecl::getIdentityConstraintAt (XMLSize_t index) const
getIdentityConstraintAt() [3/3]
IdentityConstraint* SchemaElementDecl::getIdentityConstraintAt (XMLSize_t index) const
getIdentityConstraintCount() [1/3]
XMLSize_t SchemaElementDecl::getIdentityConstraintCount () const inline
Definition at line 417 of file SchemaElementDecl.hpp.
getIdentityConstraintCount() [2/3]
XMLSize_t SchemaElementDecl::getIdentityConstraintCount () const
getIdentityConstraintCount() [3/3]
XMLSize_t SchemaElementDecl::getIdentityConstraintCount () const
getMiscFlags() [1/3]
int SchemaElementDecl::getMiscFlags () const inline
Definition at line 300 of file SchemaElementDecl.hpp.
getMiscFlags() [2/3]
int SchemaElementDecl::getMiscFlags () const
getMiscFlags() [3/3]
int SchemaElementDecl::getMiscFlags () const
getModelType() [1/3]
SchemaElementDecl::ModelTypes SchemaElementDecl::getModelType () const inline
Definition at line 266 of file SchemaElementDecl.hpp.
getModelType() [2/3]
ModelTypes SchemaElementDecl::getModelType () const
getModelType() [3/3]
ModelTypes SchemaElementDecl::getModelType () const
getObjectType() [1/3]
virtual XMLElementDecl::objectType SchemaElementDecl::getObjectType () const virtual
Implements XMLElementDecl.
getObjectType() [2/3]
virtual XMLElementDecl::objectType SchemaElementDecl::getObjectType () const virtual
Implements XMLElementDecl.
getObjectType() [3/3]
virtual XMLElementDecl::objectType SchemaElementDecl::getObjectType () const virtual
Implements XMLElementDecl.
getPSVIScope() [1/3]
PSVIDefs::PSVIScope SchemaElementDecl::getPSVIScope () const inline
Definition at line 275 of file SchemaElementDecl.hpp.
getPSVIScope() [2/3]
PSVIDefs::PSVIScope SchemaElementDecl::getPSVIScope () const
getPSVIScope() [3/3]
PSVIDefs::PSVIScope SchemaElementDecl::getPSVIScope () const
getSubstitutionGroupElem() [1/3]
SchemaElementDecl * SchemaElementDecl::getSubstitutionGroupElem () const inline
Definition at line 329 of file SchemaElementDecl.hpp.
getSubstitutionGroupElem() [2/3]
SchemaElementDecl* SchemaElementDecl::getSubstitutionGroupElem () const
getSubstitutionGroupElem() [3/3]
SchemaElementDecl* SchemaElementDecl::getSubstitutionGroupElem () const
hasAttDefs() [1/3]
virtual bool SchemaElementDecl::hasAttDefs () const virtual
Indicate whether this element type defined any attributes
The derived class should return a boolean that indicates whether this element has any attributes defined for it or not. This is an optimization that allows the scanner to skip some work if no attributes exist.
Implements XMLElementDecl.
hasAttDefs() [2/3]
virtual bool SchemaElementDecl::hasAttDefs () const virtual
Indicate whether this element type defined any attributes
The derived class should return a boolean that indicates whether this element has any attributes defined for it or not. This is an optimization that allows the scanner to skip some work if no attributes exist.
Implements XMLElementDecl.
hasAttDefs() [3/3]
virtual bool SchemaElementDecl::hasAttDefs () const virtual
Indicate whether this element type defined any attributes
The derived class should return a boolean that indicates whether this element has any attributes defined for it or not. This is an optimization that allows the scanner to skip some work if no attributes exist.
Implements XMLElementDecl.
isGlobalDecl() [1/3]
bool SchemaElementDecl::isGlobalDecl () const inline virtual
Definition at line 323 of file SchemaElementDecl.hpp.
References Grammar::TOP_LEVEL_SCOPE.
isGlobalDecl() [2/3]
virtual bool SchemaElementDecl::isGlobalDecl () const virtual
isGlobalDecl() [3/3]
virtual bool SchemaElementDecl::isGlobalDecl () const virtual
operator=() [1/3]
SchemaElementDecl& SchemaElementDecl::operator= (const SchemaElementDecl &) private
operator=() [2/3]
SchemaElementDecl& SchemaElementDecl::operator= (const SchemaElementDecl &) private
References ComplexTypeInfo::getContentSpec().
operator=() [3/3]
SchemaElementDecl& SchemaElementDecl::operator= (const SchemaElementDecl &) private
References ComplexTypeInfo::getContentSpec().
setAttWildCard() [1/3]
void SchemaElementDecl::setAttWildCard (SchemaAttDef *const attWildCard) inline
Definition at line 390 of file SchemaElementDecl.hpp.
setAttWildCard() [2/3]
void SchemaElementDecl::setAttWildCard (SchemaAttDef *const attWildCard)
setAttWildCard() [3/3]
void SchemaElementDecl::setAttWildCard (SchemaAttDef *const attWildCard)
setBlockSet() [1/3]
void SchemaElementDecl::setBlockSet (const int blockSet) inline
Definition at line 364 of file SchemaElementDecl.hpp.
setBlockSet() [2/3]
void SchemaElementDecl::setBlockSet (const int blockSet)
setBlockSet() [3/3]
void SchemaElementDecl::setBlockSet (const int blockSet)
setComplexTypeInfo() [1/3]
void SchemaElementDecl::setComplexTypeInfo (ComplexTypeInfo *const typeInfo) inline
Definition at line 384 of file SchemaElementDecl.hpp.
setComplexTypeInfo() [2/3]
void SchemaElementDecl::setComplexTypeInfo (ComplexTypeInfo *const typeInfo)
setComplexTypeInfo() [3/3]
void SchemaElementDecl::setComplexTypeInfo (ComplexTypeInfo *const typeInfo)
setContentModel() [1/3]
void SchemaElementDecl::setContentModel (XMLContentModel *const newModelToAdopt) inline virtual
Set the content model object for this element type
This method will adopt the based content model object. This is called by the actual validator which is parsing its DTD or Schema or whatever a creating an element decl. It will build what it feels is the correct content model type object and store it on the element decl object via this method.
Parameters
newModelToAdopt This method will adopt the passed content model object. Any previous object is destroyed.
Implements XMLElementDecl.
Definition at line 257 of file SchemaElementDecl.hpp.
setContentModel() [2/3]
virtual void SchemaElementDecl::setContentModel (XMLContentModel *const newModelToAdopt) virtual
Set the content model object for this element type
This method will adopt the based content model object. This is called by the actual validator which is parsing its DTD or Schema or whatever a creating an element decl. It will build what it feels is the correct content model type object and store it on the element decl object via this method.
Parameters
newModelToAdopt This method will adopt the passed content model object. Any previous object is destroyed.
Implements XMLElementDecl.
setContentModel() [3/3]
virtual void SchemaElementDecl::setContentModel (XMLContentModel *const newModelToAdopt) virtual
Set the content model object for this element type
This method will adopt the based content model object. This is called by the actual validator which is parsing its DTD or Schema or whatever a creating an element decl. It will build what it feels is the correct content model type object and store it on the element decl object via this method.
Parameters
newModelToAdopt This method will adopt the passed content model object. Any previous object is destroyed.
Implements XMLElementDecl.
setContentSpec() [1/3]
void SchemaElementDecl::setContentSpec (ContentSpecNode * toAdopt) inline virtual
Set the content spec node object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
toAdopt This method will adopt the passed content node spec object. Any previous object is destroyed.
Implements XMLElementDecl.
Definition at line 243 of file SchemaElementDecl.hpp.
setContentSpec() [2/3]
virtual void SchemaElementDecl::setContentSpec (ContentSpecNode * toAdopt) virtual
Set the content spec node object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
toAdopt This method will adopt the passed content node spec object. Any previous object is destroyed.
Implements XMLElementDecl.
setContentSpec() [3/3]
virtual void SchemaElementDecl::setContentSpec (ContentSpecNode * toAdopt) virtual
Set the content spec node object for this element type
This method will adopt the based content spec node object. This is called by the actual validator which is parsing its DTD or Schema or whatever and store it on the element decl object via this method.
Parameters
toAdopt This method will adopt the passed content node spec object. Any previous object is destroyed.
Implements XMLElementDecl.
setDatatypeValidator() [1/3]
void SchemaElementDecl::setDatatypeValidator (DatatypeValidator * newDatatypeValidator) inline
Definition at line 349 of file SchemaElementDecl.hpp.
setDatatypeValidator() [2/3]
void SchemaElementDecl::setDatatypeValidator (DatatypeValidator * newDatatypeValidator)
setDatatypeValidator() [3/3]
void SchemaElementDecl::setDatatypeValidator (DatatypeValidator * newDatatypeValidator)
setDefaultValue() [1/3]
void SchemaElementDecl::setDefaultValue (const XMLCh *const value) inline
Definition at line 374 of file SchemaElementDecl.hpp.
References MemoryManager::deallocate(), XMLElementDecl::getMemoryManager(), and XMLString::replicate().
setDefaultValue() [2/3]
void SchemaElementDecl::setDefaultValue (const XMLCh *const value)
setDefaultValue() [3/3]
void SchemaElementDecl::setDefaultValue (const XMLCh *const value)
setEnclosingScope() [1/3]
void SchemaElementDecl::setEnclosingScope (const unsigned int enclosingScope) inline
Definition at line 354 of file SchemaElementDecl.hpp.
setEnclosingScope() [2/3]
void SchemaElementDecl::setEnclosingScope (const unsigned int enclosingScope)
setEnclosingScope() [3/3]
void SchemaElementDecl::setEnclosingScope (const unsigned int enclosingScope)
setFinalSet() [1/3]
void SchemaElementDecl::setFinalSet (const int finalSet) inline
Definition at line 359 of file SchemaElementDecl.hpp.
setFinalSet() [2/3]
void SchemaElementDecl::setFinalSet (const int finalSet)
setFinalSet() [3/3]
void SchemaElementDecl::setFinalSet (const int finalSet)
setMiscFlags() [1/3]
void SchemaElementDecl::setMiscFlags (const int flags) inline
Definition at line 369 of file SchemaElementDecl.hpp.
setMiscFlags() [2/3]
void SchemaElementDecl::setMiscFlags (const int flags)
setMiscFlags() [3/3]
void SchemaElementDecl::setMiscFlags (const int flags)
setModelType() [1/3]
void SchemaElementDecl::setModelType (const SchemaElementDecl::ModelTypes toSet) inline
Definition at line 338 of file SchemaElementDecl.hpp.
setModelType() [2/3]
void SchemaElementDecl::setModelType (const SchemaElementDecl::ModelTypes toSet)
setModelType() [3/3]
void SchemaElementDecl::setModelType (const SchemaElementDecl::ModelTypes toSet)
setPSVIScope() [1/3]
void SchemaElementDecl::setPSVIScope (const PSVIDefs::PSVIScope toSet) inline
Definition at line 344 of file SchemaElementDecl.hpp.
setPSVIScope() [2/3]
void SchemaElementDecl::setPSVIScope (const PSVIDefs::PSVIScope toSet)
setPSVIScope() [3/3]
void SchemaElementDecl::setPSVIScope (const PSVIDefs::PSVIScope toSet)
setSubstitutionGroupElem() [1/3]
void SchemaElementDecl::setSubstitutionGroupElem (SchemaElementDecl *const elemDecl) inline
Definition at line 399 of file SchemaElementDecl.hpp.
setSubstitutionGroupElem() [2/3]
void SchemaElementDecl::setSubstitutionGroupElem (SchemaElementDecl *const elemDecl)
setSubstitutionGroupElem() [3/3]
void SchemaElementDecl::setSubstitutionGroupElem (SchemaElementDecl *const elemDecl)
Member Data Documentation
fAttDefs
RefHash2KeysTableOf< SchemaAttDef > * SchemaElementDecl::fAttDefs private
Definition at line 214 of file SchemaElementDecl.hpp.
fAttWildCard
SchemaAttDef * SchemaElementDecl::fAttWildCard private
Definition at line 216 of file SchemaElementDecl.hpp.
fBlockSet
int SchemaElementDecl::fBlockSet private
Definition at line 210 of file SchemaElementDecl.hpp.
fComplexTypeInfo
ComplexTypeInfo * SchemaElementDecl::fComplexTypeInfo private
Definition at line 213 of file SchemaElementDecl.hpp.
fDatatypeValidator
DatatypeValidator * SchemaElementDecl::fDatatypeValidator private
Definition at line 218 of file SchemaElementDecl.hpp.
fDefaultValue
XMLCh * SchemaElementDecl::fDefaultValue private
Definition at line 212 of file SchemaElementDecl.hpp.
fEnclosingScope
unsigned int SchemaElementDecl::fEnclosingScope private
Definition at line 208 of file SchemaElementDecl.hpp.
fFinalSet
int SchemaElementDecl::fFinalSet private
Definition at line 209 of file SchemaElementDecl.hpp.
fIdentityConstraints
RefVectorOf< IdentityConstraint > * SchemaElementDecl::fIdentityConstraints private
Definition at line 215 of file SchemaElementDecl.hpp.
fMiscFlags
int SchemaElementDecl::fMiscFlags private
Definition at line 211 of file SchemaElementDecl.hpp.
fModelType
ModelTypes SchemaElementDecl::fModelType private
Definition at line 205 of file SchemaElementDecl.hpp.
fPSVIScope
PSVIDefs::PSVIScope SchemaElementDecl::fPSVIScope private
Definition at line 206 of file SchemaElementDecl.hpp.
fSubstitutionGroupElem
SchemaElementDecl * SchemaElementDecl::fSubstitutionGroupElem private
Definition at line 217 of file SchemaElementDecl.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/SchemaElementDecl.hpp