Seamly2D: TST_VPointF Class Reference
TST_VPointF Class Reference
#include <tst_vpointf.h>
Public Member Functions
TST_VPointF (QObject *parent=nullptr)
Private Slots
void TestFlip_data ()
void TestFlip ()
Detailed Description
Definition at line 58 of file tst_vpointf.h.
Constructor & Destructor Documentation
TST_VPointF()
TST_VPointF::TST_VPointF (QObject * parent = nullptr) explicit
Definition at line 59 of file tst_vpointf.cpp.
Member Function Documentation
TestFlip
void TST_VPointF::TestFlip () private slot
Definition at line 95 of file tst_vpointf.cpp.
References VPointF::Flip(), VGObject::name(), and VPointF::toQPointF().
TestFlip_data
void TST_VPointF::TestFlip_data () private slot
Definition at line 65 of file tst_vpointf.cpp.
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vpointf.h
src/test/Seamly2DTest/tst_vpointf.cpp