Seamly2D: MainWindowsNoGUI Class Reference
MainWindowsNoGUI Class Reference abstract
#include <mainwindowsnogui.h>
Public Slots
void toolLayoutSettings (QToolButton *tButton, bool checked)
void PrintPreviewOrigin ()
void PrintPreviewTiled ()
void PrintOrigin ()
void PrintTiled ()
void refreshLabels ()
refreshLabels call to recalculate piece labels. For example after changing a font.
void refreshGrainLines ()
refreshGrainLines call to recalculate piece grainlines. For example after show / hide grainlines.
void refreshSeamAllowances ()
refreshSeamAllowances call to show / hide seam allowances.
void exportSVG (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene) const
exportSVG save layout to svg file.
void exportPNG (const QString &name, QGraphicsScene *scene) const
exportPNG save layout to png file.
void exportTIF (const QString &name, QGraphicsScene *scene) const
exportTIF save layout to tif file.
void exportJPG (const QString &name, QGraphicsScene *scene) const
exportJPG save layout to jpg file.
void exportBMP (const QString &name, QGraphicsScene *scene) const
exportBMP save layout to bmp file.
void exportPPM (const QString &name, QGraphicsScene *scene) const
exportPPM save layout to gif file.
void exportPDF (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene, bool ignoreMargins, const QMarginsF &margins) const
exportPDF save layout to pdf file.
void exportEPS (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene, bool ignoreMargins, const QMarginsF &margins) const
exportEPS(save layout to eps file.
void exportPS (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene, bool ignoreMargins, const QMarginsF &margins) const
exportPS save layout to ps file.
Public Slots inherited from VAbstractMainWindow
virtual void ShowToolTip (const QString &toolTip)=0
virtual void updateGroups ()=0
virtual void zoomToSelected ()=0
Public Member Functions
MainWindowsNoGUI (QWidget *parent=nullptr)
virtual ~MainWindowsNoGUI () Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractMainWindow
VAbstractMainWindow (QWidget *parent=nullptr)
virtual ~VAbstractMainWindow () Q_DECL_EQ_DEFAULT
Protected Member Functions
void ExportData (const QVector< VLayoutPiece > &pieceList, const ExportLayoutDialog &dialog)
void InitTempLayoutScene ()
virtual void CleanLayout ()=0
virtual void PrepareSceneList ()=0
QIcon ScenePreview (int i) const
bool LayoutSettings (VLayoutGenerator &lGenerator)
int ContinueIfLayoutStale ()
QString FileName () const
void SetSizeHeightForIndividualM () const
Protected Member Functions inherited from VAbstractMainWindow
bool ContinueFormatRewrite (const QString &currentFormatVersion, const QString &maxFormatVersion)
void ToolBarStyle (QToolBar *bar)
virtual void exportToCSVData (const QString &fileName, const DialogExportToCSV &dialog)=0
Static Protected Member Functions
static QVector< VLayoutPiece > preparePiecesForLayout (const QHash< quint32, VPiece > &pieces)
Protected Attributes
QVector< VLayoutPiece > pieceList
QGraphicsScene * currentScene
QGraphicsScene * tempSceneLayout
currentScene pointer to current scene.
VContainer * pattern
pattern container with data (points, arcs, splines, spline paths, variables)
VPattern * doc
pattern container with data (points, arcs, splines, spline paths, variables)
QList< QGraphicsItem * > papers
doc dom document container
QList< QGraphicsItem * > shadows
QList< QGraphicsScene * > scenes
QList< QList< QGraphicsItem * > > pieces
QVector< QVector< VLayoutPiece > > piecesOnLayout
QAction * undoAction
QAction * redoAction
QAction * actionDockWidgetToolOptions
QAction * actionDockWidgetGroups
QAction * actionDockWidgetLayouts
QAction * actionDockWidgetToolbox
bool isNoScaling
bool isLayoutStale
bool ignoreMargins
QMarginsF margins
QSizeF paperSize
Protected Attributes inherited from VAbstractMainWindow
int m_curFileFormatVersion
QString m_curFileFormatVersionStr
Private Types
enum class PrintType : char { PrintPDF , PrintPreview , PrintNative }
Private Slots
void PrintPages (QPrinter *printer)
void ErrorConsoleMode (const LayoutErrors &state)
Private Member Functions
void PdfTiledFile (const QString &name)
void convertPdfToPs (const QStringList &params) const
convertPdfToPs use external tool "pdftops" for converting pdf to eps or ps format.
void ObjFile (const QString &name, QGraphicsRectItem *paper, QGraphicsScene *scene) const
void FlatDxfFile (const QString &name, int version, bool binary, QGraphicsRectItem *paper, QGraphicsScene *scene, const QList< QList< QGraphicsItem * > > &pieces) const
void AAMADxfFile (const QString &name, int version, bool binary, const QSize &size, const QVector< VLayoutPiece > &pieces) const
void PreparePaper (int index) const
void RestorePaper (int index) const
void PrepareTextForDXF (const QString &placeholder, const QList< QList< QGraphicsItem * > > &pieces) const
PrepareTextForDXF prepare QGraphicsSimpleTextItem items for export to flat dxf.
void RestoreTextAfterDXF (const QString &placeholder, const QList< QList< QGraphicsItem * > > &pieces) const
MainWindowsNoGUI::RestoreTextAfterDXF restore QGraphicsSimpleTextItem items after export to flat dxf.
void PrintPreview ()
void LayoutPrint ()
void SetPrinterSettings (QPrinter *printer, const PrintType &printType)
bool IsLayoutGrayscale () const
QPageSize FindQPrinterPageSize (const QSizeF &size) const
MainWindowsNoGUI::FindTemplate.
bool isPagesUniform () const
bool IsPagesFit (const QSizeF &printPaper) const
void ExportScene (const ExportLayoutDialog &dialog, const QList< QGraphicsScene * > &scenes, const QList< QGraphicsItem * > &papers, const QList< QGraphicsItem * > &shadows, const QList< QList< QGraphicsItem * > > &pieces, bool ignoreMargins, const QMarginsF &margins) const
void ExportApparelLayout (const ExportLayoutDialog &dialog, const QVector< VLayoutPiece > &pieces, const QString &name, const QSize &size) const
void exportPiecesAsApparelLayout (const ExportLayoutDialog &dialog, QVector< VLayoutPiece > pieceList)
void ExportFlatLayout (const ExportLayoutDialog &dialog, const QList< QGraphicsScene * > &scenes, const QList< QGraphicsItem * > &papers, const QList< QGraphicsItem * > &shadows, const QList< QList< QGraphicsItem * > > &pieces, bool ignoreMargins, const QMarginsF &margins)
void exportPiecesAsFlatLayout (const ExportLayoutDialog &dialog, const QVector< VLayoutPiece > &pieceList)
Static Private Member Functions
static QList< QGraphicsItem * > CreateShadows (const QList< QGraphicsItem * > &papers)
static QList< QGraphicsScene * > CreateScenes (const QList< QGraphicsItem * > &papers, const QList< QGraphicsItem * > &shadows, const QList< QList< QGraphicsItem * > > &pieces)
Private Attributes
bool isTiled
bool isAutoCrop
bool isUnitePages
QString layoutPrinterName
Additional Inherited Members
Protected Slots inherited from VAbstractMainWindow
void WindowsLocale ()
void exportToCSV (QString &file)
Detailed Description
Definition at line 70 of file mainwindowsnogui.h.
Member Enumeration Documentation
PrintType
enum MainWindowsNoGUI::PrintType : char strong private
Enumerator
PrintPDF
PrintPreview
PrintNative
Definition at line 177 of file mainwindowsnogui.h.
Constructor & Destructor Documentation
MainWindowsNoGUI()
MainWindowsNoGUI::MainWindowsNoGUI (QWidget * parent = nullptr) explicit
Definition at line 114 of file mainwindowsnogui.cpp.
References InitTempLayoutScene().
~MainWindowsNoGUI()
MainWindowsNoGUI::~MainWindowsNoGUI () virtual
Definition at line 147 of file mainwindowsnogui.cpp.
References pattern, and tempSceneLayout.
Member Function Documentation
AAMADxfFile()
void MainWindowsNoGUI::AAMADxfFile (const QString & name, int version, bool binary, const QSize & size, const QVector< VLayoutPiece > & pieces) const private
Definition at line 1186 of file mainwindowsnogui.cpp.
References VDxfPaintDevice::ExportToAAMA(), Millimeters, pieces, PrintDPI, VDxfPaintDevice::SetBinaryFormat(), VDxfPaintDevice::setFileName(), VDxfPaintDevice::setInsunits(), VDxfPaintDevice::setResolution(), VDxfPaintDevice::setSize(), and VDxfPaintDevice::SetVersion().
Referenced by ExportApparelLayout().
CleanLayout()
virtual void MainWindowsNoGUI::CleanLayout () protected pure virtual
Implemented in MainWindow.
Referenced by LayoutSettings().
ContinueIfLayoutStale()
int MainWindowsNoGUI::ContinueIfLayoutStale () protected
Definition at line 1763 of file mainwindowsnogui.cpp.
References SCASSERT.
Referenced by MainWindow::exportLayoutAs(), LayoutPrint(), PdfTiledFile(), and PrintPreview().
convertPdfToPs()
void MainWindowsNoGUI::convertPdfToPs (const QStringList & params) const private
convertPdfToPs use external tool "pdftops" for converting pdf to eps or ps format.
Parameters
params string with parameter for tool. Parameters have format: "-eps input_file out_file". Use -eps when need create eps file.
Definition at line 1117 of file mainwindowsnogui.cpp.
References PDFTOPS, and qApp.
Referenced by exportEPS(), and exportPS().
CreateScenes()
QList< QGraphicsScene * > MainWindowsNoGUI::CreateScenes (const QList< QGraphicsItem * > & papers, const QList< QGraphicsItem * > & shadows, const QList< QList< QGraphicsItem * > > & pieces) static private
Definition at line 860 of file mainwindowsnogui.cpp.
References papers, pieces, scenes, and shadows.
Referenced by exportPiecesAsFlatLayout(), and LayoutSettings().
CreateShadows()
QList< QGraphicsItem * > MainWindowsNoGUI::CreateShadows (const QList< QGraphicsItem * > & papers) static private
Definition at line 835 of file mainwindowsnogui.cpp.
References papers, and shadows.
Referenced by exportPiecesAsFlatLayout(), and LayoutSettings().
ErrorConsoleMode
void MainWindowsNoGUI::ErrorConsoleMode (const LayoutErrors & state) private slot
Definition at line 234 of file mainwindowsnogui.cpp.
References EmptyPaperError, NoError, PrepareLayoutError, ProcessStoped, qApp, and V_EX_DATAERR.
Referenced by LayoutSettings().
ExportApparelLayout()
void MainWindowsNoGUI::ExportApparelLayout (const ExportLayoutDialog & dialog, const QVector< VLayoutPiece > & pieces, const QString & name, const QSize & size) const private
Definition at line 397 of file mainwindowsnogui.cpp.
References AAMADxfFile(), anonymous_namespace{mainwindowsnogui.cpp}::CreateLayoutPath(), DXF_AC1006_AAMA, DXF_AC1006_ASTM, DXF_AC1009_AAMA, DXF_AC1009_ASTM, DXF_AC1012_AAMA, DXF_AC1012_ASTM, DXF_AC1014_AAMA, DXF_AC1014_ASTM, DXF_AC1015_AAMA, DXF_AC1015_ASTM, DXF_AC1018_AAMA, DXF_AC1018_ASTM, DXF_AC1021_AAMA, DXF_AC1021_ASTM, DXF_AC1024_AAMA, DXF_AC1024_ASTM, DXF_AC1027_AAMA, DXF_AC1027_ASTM, ExportLayoutDialog::format(), ExportLayoutDialog::isBinaryDXFFormat(), ExportLayoutDialog::path(), pieces, qApp, and anonymous_namespace{mainwindowsnogui.cpp}::RemoveLayoutPath().
Referenced by ExportData(), and exportPiecesAsApparelLayout().
exportBMP
void MainWindowsNoGUI::exportBMP (const QString & fileName, QGraphicsScene * scene) const slot
exportBMP save layout to bmp file.
Parameters
fileName name layout file.
Definition at line 969 of file mainwindowsnogui.cpp.
References qApp.
Referenced by MainWindow::exportDraftBlocksAs(), and ExportScene().
ExportData()
void MainWindowsNoGUI::ExportData (const QVector< VLayoutPiece > & pieceList, const ExportLayoutDialog & dialog) protected
Definition at line 255 of file mainwindowsnogui.cpp.
References DXF_AC1006_AAMA, DXF_AC1009_AAMA, DXF_AC1012_AAMA, DXF_AC1014_AAMA, DXF_AC1015_AAMA, DXF_AC1018_AAMA, DXF_AC1021_AAMA, DXF_AC1024_AAMA, DXF_AC1027_AAMA, ExportApparelLayout(), ExportFlatLayout(), ExportLayoutDialog::exportFormatSuffix(), exportPiecesAsApparelLayout(), exportPiecesAsFlatLayout(), ExportLayoutDialog::fileName(), ExportLayoutDialog::format(), ignoreMargins, Layout, margins, ExportLayoutDialog::mode(), papers, ExportLayoutDialog::path(), pieceList, pieces, piecesOnLayout, SCASSERT, scenes, and shadows.
Referenced by MainWindow::DoExport(), MainWindow::exportLayoutAs(), and MainWindow::exportPiecesAs().
exportEPS
void MainWindowsNoGUI::exportEPS (const QString & name, QGraphicsRectItem * paper, QGraphicsScene * scene, bool ignoreMargins, const QMarginsF & margins) const slot
exportEPS(save layout to eps file.
Parameters
fileName name layout file.
Definition at line 1082 of file mainwindowsnogui.cpp.
References convertPdfToPs(), exportPDF(), ignoreMargins, and margins.
Referenced by MainWindow::exportDraftBlocksAs(), and ExportScene().
ExportFlatLayout()
void MainWindowsNoGUI::ExportFlatLayout (const ExportLayoutDialog & dialog, const QList< QGraphicsScene * > & scenes, const QList< QGraphicsItem * > & papers, const QList< QGraphicsItem * > & shadows, const QList< QList< QGraphicsItem * > > & pieces, bool ignoreMargins, const QMarginsF & margins) private
Definition at line 304 of file mainwindowsnogui.cpp.
References anonymous_namespace{mainwindowsnogui.cpp}::CreateLayoutPath(), ExportLayoutDialog::exportFormatSuffix(), ExportScene(), ExportLayoutDialog::fileName(), ExportLayoutDialog::format(), ignoreMargins, Layout, margins, ExportLayoutDialog::mode(), papers, ExportLayoutDialog::path(), PDFTiled, PdfTiledFile(), pieces, qApp, anonymous_namespace{mainwindowsnogui.cpp}::RemoveLayoutPath(), scenes, and shadows.
Referenced by ExportData(), and exportPiecesAsFlatLayout().
exportJPG
void MainWindowsNoGUI::exportJPG (const QString & fileName, QGraphicsScene * scene) const slot
exportJPG save layout to jpg file.
Parameters
fileName name layout file.
Definition at line 952 of file mainwindowsnogui.cpp.
References qApp.
Referenced by MainWindow::exportDraftBlocksAs(), and ExportScene().
exportPDF
void MainWindowsNoGUI::exportPDF (const QString & name, QGraphicsRectItem * paper, QGraphicsScene * scene, bool ignoreMargins, const QMarginsF & margins) const slot
exportPDF save layout to pdf file.
Parameters
fileName name layout file.
Definition at line 1003 of file mainwindowsnogui.cpp.
References FileName(), FromPixel(), ignoreMargins, margins, Mm, PrintDPI, and widthMainLine.
Referenced by MainWindow::exportDraftBlocksAs(), exportEPS(), exportPS(), and ExportScene().
exportPiecesAsApparelLayout()
void MainWindowsNoGUI::exportPiecesAsApparelLayout (const ExportLayoutDialog & dialog, QVector< VLayoutPiece > pieceList) private
Definition at line 460 of file mainwindowsnogui.cpp.
References ExportApparelLayout(), ExportLayoutDialog::exportFormatSuffix(), ExportLayoutDialog::fileName(), ExportLayoutDialog::format(), ExportLayoutDialog::isTextAsPaths(), Layout, ExportLayoutDialog::mode(), ExportLayoutDialog::path(), and pieceList.
Referenced by ExportData().
exportPiecesAsFlatLayout()
void MainWindowsNoGUI::exportPiecesAsFlatLayout (const ExportLayoutDialog & dialog, const QVector< VLayoutPiece > & pieceList) private
Definition at line 338 of file mainwindowsnogui.cpp.
References Cm, CreateScenes(), CreateShadows(), ExportFlatLayout(), ignoreMargins, ExportLayoutDialog::isTextAsPaths(), papers, pieceList, pieces, scenes, shadows, and ToPixel().
Referenced by ExportData().
exportPNG
void MainWindowsNoGUI::exportPNG (const QString & fileName, QGraphicsScene * scene) const slot
exportPNG save layout to png file.
Parameters
fileName name layout file.
Definition at line 913 of file mainwindowsnogui.cpp.
References qApp.
Referenced by MainWindow::exportDraftBlocksAs(), and ExportScene().
exportPPM
void MainWindowsNoGUI::exportPPM (const QString & fileName, QGraphicsScene * scene) const slot
exportPPM save layout to gif file.
Parameters
fileName name layout file.
Definition at line 986 of file mainwindowsnogui.cpp.
References qApp.
Referenced by MainWindow::exportDraftBlocksAs(), and ExportScene().
exportPS
void MainWindowsNoGUI::exportPS (const QString & name, QGraphicsRectItem * paper, QGraphicsScene * scene, bool ignoreMargins, const QMarginsF & margins) const slot
exportPS save layout to ps file.
Parameters
fileName name layout file.
Definition at line 1099 of file mainwindowsnogui.cpp.
References convertPdfToPs(), exportPDF(), ignoreMargins, and margins.
Referenced by MainWindow::exportDraftBlocksAs(), and ExportScene().
ExportScene()
void MainWindowsNoGUI::ExportScene (const ExportLayoutDialog & dialog, const QList< QGraphicsScene * > & scenes, const QList< QGraphicsItem * > & papers, const QList< QGraphicsItem * > & shadows, const QList< QList< QGraphicsItem * > > & pieces, bool ignoreMargins, const QMarginsF & margins) const private
Definition at line 1604 of file mainwindowsnogui.cpp.
References BMP, DXF_AC1006_Flat, DXF_AC1009_Flat, DXF_AC1012_Flat, DXF_AC1014_Flat, DXF_AC1015_Flat, DXF_AC1018_Flat, DXF_AC1021_Flat, DXF_AC1024_Flat, DXF_AC1027_Flat, EPS, exportBMP(), exportEPS(), ExportLayoutDialog::exportFormatSuffix(), exportJPG(), exportPDF(), exportPNG(), exportPPM(), exportPS(), exportSVG(), exportTIF(), ExportLayoutDialog::fileName(), FlatDxfFile(), ExportLayoutDialog::format(), ignoreMargins, ExportLayoutDialog::isBinaryDXFFormat(), JPG, Layout, margins, ExportLayoutDialog::mode(), OBJ, ObjFile(), papers, ExportLayoutDialog::path(), PDF, pieces, PNG, PPM, PS, scenes, shadows, SVG, and TIF.
Referenced by ExportFlatLayout().
exportSVG
void MainWindowsNoGUI::exportSVG (const QString & name, QGraphicsRectItem * paper, QGraphicsScene * scene) const slot
exportSVG save layout to svg file.
Parameters
fileName name layout file.
Definition at line 889 of file mainwindowsnogui.cpp.
References doc, VAbstractPattern::GetDescription(), and PrintDPI.
Referenced by MainWindow::exportDraftBlocksAs(), and ExportScene().
exportTIF
void MainWindowsNoGUI::exportTIF (const QString & fileName, QGraphicsScene * scene) const slot
exportTIF save layout to tif file.
Parameters
fileName name layout file.
Definition at line 930 of file mainwindowsnogui.cpp.
References qApp.
Referenced by MainWindow::exportDraftBlocksAs(), and ExportScene().
FileName()
QString MainWindowsNoGUI::FileName () const protected
Definition at line 1728 of file mainwindowsnogui.cpp.
References qApp.
Referenced by MainWindow::exportDraftBlocksAs(), MainWindow::exportLayoutAs(), exportPDF(), MainWindow::exportPiecesAs(), and SetPrinterSettings().
FindQPrinterPageSize()
QPageSize MainWindowsNoGUI::FindQPrinterPageSize (const QSizeF & size) const private
MainWindowsNoGUI::FindTemplate.
Parameters
size has to be in Mm
Returns
Definition at line 1523 of file mainwindowsnogui.cpp.
References Custom.
Referenced by SetPrinterSettings().
FlatDxfFile()
QT_WARNING_PUSH void MainWindowsNoGUI::FlatDxfFile (const QString & name, int version, bool binary, QGraphicsRectItem * paper, QGraphicsScene * scene, const QList< QList< QGraphicsItem * > > & pieces) const private
Definition at line 1164 of file mainwindowsnogui.cpp.
References endStringPlaceholder, Millimeters, PrintDPI, VDxfPaintDevice::SetBinaryFormat(), VDxfPaintDevice::setFileName(), VDxfPaintDevice::setInsunits(), VDxfPaintDevice::setResolution(), VDxfPaintDevice::setSize(), and VDxfPaintDevice::SetVersion().
Referenced by ExportScene().
InitTempLayoutScene()
void MainWindowsNoGUI::InitTempLayoutScene () protected
Definition at line 793 of file mainwindowsnogui.cpp.
References tempSceneLayout.
Referenced by MainWindowsNoGUI().
IsLayoutGrayscale()
bool MainWindowsNoGUI::IsLayoutGrayscale () const private
Definition at line 1483 of file mainwindowsnogui.cpp.
References papers, PreparePaper(), RestorePaper(), scenes, and widthMainLine.
Referenced by SetPrinterSettings().
IsPagesFit()
bool MainWindowsNoGUI::IsPagesFit (const QSizeF & printPaper) const private
Definition at line 1588 of file mainwindowsnogui.cpp.
References papers, and SCASSERT.
Referenced by PdfTiledFile().
isPagesUniform()
bool MainWindowsNoGUI::isPagesUniform () const private
Definition at line 1564 of file mainwindowsnogui.cpp.
References papers, and SCASSERT.
Referenced by PrintOrigin(), and PrintPreviewOrigin().
LayoutPrint()
void MainWindowsNoGUI::LayoutPrint () private
Definition at line 1330 of file mainwindowsnogui.cpp.
References ContinueIfLayoutStale(), isLayoutStale, layoutPrinterName, PreparePrinter(), PrintDPI, PrintNative, PrintPages(), and SetPrinterSettings().
Referenced by PrintOrigin(), and PrintTiled().
LayoutSettings()
bool MainWindowsNoGUI::LayoutSettings (VLayoutGenerator & lGenerator) protected
Definition at line 180 of file mainwindowsnogui.cpp.
References DialogLayoutProgress::Abort(), VLayoutGenerator::Abort(), DialogLayoutProgress::Arranged(), VLayoutGenerator::Arranged(), CleanLayout(), CreateScenes(), CreateShadows(), EmptyPaperError, DialogLayoutProgress::Error(), VLayoutGenerator::Error(), ErrorConsoleMode(), DialogLayoutProgress::Finished(), VLayoutGenerator::Finished(), VLayoutGenerator::Generate(), VLayoutGenerator::getAllPieceItems(), VLayoutGenerator::getAllPieces(), VLayoutGenerator::GetAutoCrop(), VLayoutGenerator::GetPaperHeight(), VLayoutGenerator::GetPapersItems(), VLayoutGenerator::GetPaperWidth(), VLayoutGenerator::GetPrinterFields(), ignoreMargins, isAutoCrop, VApplication::IsGUIMode(), isLayoutStale, isUnitePages, VLayoutGenerator::IsUnitePages(), VLayoutGenerator::IsUsePrinterFields(), margins, NoError, papers, paperSize, pieceList, pieces, piecesOnLayout, PrepareLayoutError, PrepareSceneList(), ProcessStoped, scenes, VLayoutGenerator::setPieces(), shadows, DialogLayoutProgress::Start(), VLayoutGenerator::Start(), and VLayoutGenerator::State().
Referenced by MainWindow::DoExport(), and toolLayoutSettings().
ObjFile()
void MainWindowsNoGUI::ObjFile (const QString & name, QGraphicsRectItem * paper, QGraphicsScene * scene) const private
Definition at line 1148 of file mainwindowsnogui.cpp.
References PrintDPI, VObjPaintDevice::setFileName(), VObjPaintDevice::setResolution(), and VObjPaintDevice::setSize().
Referenced by ExportScene().
PdfTiledFile()
void MainWindowsNoGUI::PdfTiledFile (const QString & name) private
Definition at line 1052 of file mainwindowsnogui.cpp.
References ContinueIfLayoutStale(), isLayoutStale, IsPagesFit(), isTiled, PrintDPI, PrintPages(), PrintPDF, and SetPrinterSettings().
Referenced by ExportFlatLayout().
PreparePaper()
QT_WARNING_POP void MainWindowsNoGUI::PreparePaper (int index) const private
Definition at line 1202 of file mainwindowsnogui.cpp.
References papers, scenes, and shadows.
Referenced by IsLayoutGrayscale(), and PrintPages().
preparePiecesForLayout()
QVector< VLayoutPiece > MainWindowsNoGUI::preparePiecesForLayout (const QHash< quint32, VPiece > & pieces) static protected
Definition at line 774 of file mainwindowsnogui.cpp.
References VLayoutPiece::Create(), VAbstractTool::getData(), VAbstractPattern::getTool(), pieceList, pieces, and SCASSERT.
Referenced by MainWindow::DoExport(), MainWindow::exportPiecesAs(), and MainWindow::showLayoutMode().
PrepareSceneList()
virtual void MainWindowsNoGUI::PrepareSceneList () protected pure virtual
Implemented in MainWindow.
Referenced by LayoutSettings().
PrepareTextForDXF()
void MainWindowsNoGUI::PrepareTextForDXF (const QString & placeholder, const QList< QList< QGraphicsItem * > > & pieces) const private
PrepareTextForDXF prepare QGraphicsSimpleTextItem items for export to flat dxf.
Because QPaintEngine::drawTextItem doesn't pass whole string per time we mark end of each string by adding special placeholder. This method append it.
Parameters
placeholder placeholder that will be appended to each QGraphicsSimpleTextItem item's text string.
Definition at line 1238 of file mainwindowsnogui.cpp.
References pieces.
PrintOrigin
void MainWindowsNoGUI::PrintOrigin () slot
Definition at line 699 of file mainwindowsnogui.cpp.
References isPagesUniform(), isTiled, and LayoutPrint().
PrintPages
void MainWindowsNoGUI::PrintPages (QPrinter * printer) private slot
Definition at line 522 of file mainwindowsnogui.cpp.
References VSettings::getTiledPDFOrientation(), isTiled, Landscape, Mm, papers, PreparePaper(), qApp, RestorePaper(), scenes, ToPixel(), and widthMainLine.
Referenced by LayoutPrint(), PdfTiledFile(), and PrintPreview().
PrintPreview()
void MainWindowsNoGUI::PrintPreview () private
Definition at line 1298 of file mainwindowsnogui.cpp.
References ContinueIfLayoutStale(), isLayoutStale, layoutPrinterName, PreparePrinter(), PrintDPI, PrintPages(), PrintPreview, and SetPrinterSettings().
Referenced by PrintPreviewOrigin(), and PrintPreviewTiled().
PrintPreviewOrigin
void MainWindowsNoGUI::PrintPreviewOrigin () slot
Definition at line 679 of file mainwindowsnogui.cpp.
References isPagesUniform(), isTiled, and PrintPreview().
PrintPreviewTiled
void MainWindowsNoGUI::PrintPreviewTiled () slot
Definition at line 692 of file mainwindowsnogui.cpp.
References isTiled, and PrintPreview().
PrintTiled
void MainWindowsNoGUI::PrintTiled () slot
Definition at line 712 of file mainwindowsnogui.cpp.
References isTiled, and LayoutPrint().
refreshGrainLines
void MainWindowsNoGUI::refreshGrainLines () slot
refreshGrainLines call to recalculate piece grainlines. For example after show / hide grainlines.
Definition at line 741 of file mainwindowsnogui.cpp.
References VContainer::DataPieces(), VAbstractPattern::getTool(), and pattern.
refreshLabels
void MainWindowsNoGUI::refreshLabels () slot
refreshLabels call to recalculate piece labels. For example after changing a font.
Definition at line 722 of file mainwindowsnogui.cpp.
References VContainer::DataPieces(), VAbstractPattern::getTool(), and pattern.
Referenced by MainWindow::Preferences().
refreshSeamAllowances
void MainWindowsNoGUI::refreshSeamAllowances () slot
refreshSeamAllowances call to show / hide seam allowances.
Definition at line 759 of file mainwindowsnogui.cpp.
References VContainer::DataPieces(), VAbstractPattern::getTool(), and pattern.
RestorePaper()
void MainWindowsNoGUI::RestorePaper (int index) const private
Definition at line 1216 of file mainwindowsnogui.cpp.
References papers, scenes, shadows, and widthMainLine.
Referenced by IsLayoutGrayscale(), and PrintPages().
RestoreTextAfterDXF()
void MainWindowsNoGUI::RestoreTextAfterDXF (const QString & placeholder, const QList< QList< QGraphicsItem * > > & pieces) const private
MainWindowsNoGUI::RestoreTextAfterDXF restore QGraphicsSimpleTextItem items after export to flat dxf.
Because QPaintEngine::drawTextItem doesn't pass whole string per time we mark end of each string by adding special placeholder. This method remove it.
Parameters
placeholder placeholder that will be removed from each QGraphicsSimpleTextItem item's text string.
Definition at line 1271 of file mainwindowsnogui.cpp.
References pieces.
ScenePreview()
QIcon MainWindowsNoGUI::ScenePreview (int i) const protected
Definition at line 800 of file mainwindowsnogui.cpp.
References papers, scenes, and widthMainLine.
Referenced by MainWindow::PrepareSceneList().
SetPrinterSettings()
void MainWindowsNoGUI::SetPrinterSettings (QPrinter * printer, const PrintType & printType) private
Definition at line 1365 of file mainwindowsnogui.cpp.
References Custom, FileName(), FindQPrinterPageSize(), FromPixel(), VSettings::GetTiledPDFMargins(), VSettings::getTiledPDFOrientation(), VSettings::getTiledPDFPaperHeight(), VSettings::getTiledPDFPaperWidth(), isAutoCrop, IsLayoutGrayscale(), isTiled, isUnitePages, Landscape, margins, Mm, papers, paperSize, PrintNative, PrintPDF, PrintPreview, Px, qApp, SCASSERT, and UnitConvertor().
Referenced by LayoutPrint(), PdfTiledFile(), and PrintPreview().
SetSizeHeightForIndividualM()
void MainWindowsNoGUI::SetSizeHeightForIndividualM () const protected
Definition at line 1736 of file mainwindowsnogui.cpp.
References VContainer::DataVariables(), doc, height_M, pattern, VContainer::SetHeight(), VAbstractPattern::SetPatternWasChanged(), VContainer::SetSize(), size_M, and VAbstractPattern::UpdatePatternLabel().
Referenced by MainWindow::LoadMeasurements(), and MainWindow::UpdateMeasurements().
toolLayoutSettings
void MainWindowsNoGUI::toolLayoutSettings (QToolButton * tButton, bool checked) slot
Definition at line 154 of file mainwindowsnogui.cpp.
References layoutPrinterName, LayoutSettings(), SCASSERT, and DialogLayoutSettings::SelectedPrinter().
Referenced by MainWindow::handleNewLayout().
Member Data Documentation
actionDockWidgetGroups
QAction* MainWindowsNoGUI::actionDockWidgetGroups protected
Definition at line 116 of file mainwindowsnogui.h.
Referenced by MainWindow::AddDocks(), and MainWindow::setWidgetsEnabled().
actionDockWidgetLayouts
QAction* MainWindowsNoGUI::actionDockWidgetLayouts protected
Definition at line 117 of file mainwindowsnogui.h.
Referenced by MainWindow::AddDocks(), and MainWindow::setWidgetsEnabled().
actionDockWidgetToolbox
QAction* MainWindowsNoGUI::actionDockWidgetToolbox protected
Definition at line 118 of file mainwindowsnogui.h.
Referenced by MainWindow::AddDocks().
actionDockWidgetToolOptions
QAction* MainWindowsNoGUI::actionDockWidgetToolOptions protected
Definition at line 115 of file mainwindowsnogui.h.
Referenced by MainWindow::AddDocks(), and MainWindow::setWidgetsEnabled().
currentScene
QGraphicsScene* MainWindowsNoGUI::currentScene protected
Definition at line 102 of file mainwindowsnogui.h.
Referenced by MainWindow::ClosedDialog(), MainWindow::InitScenes(), MainWindow::RestoreCurrentScene(), MainWindow::SaveCurrentScene(), MainWindow::SetToolButton(), MainWindow::showDraftMode(), MainWindow::showLayoutMode(), MainWindow::showPieceMode(), and MainWindow::zoomToPrevious().
doc
VPattern* MainWindowsNoGUI::doc protected
pattern container with data (points, arcs, splines, spline paths, variables)
Definition at line 105 of file mainwindowsnogui.h.
Referenced by MainWindow::addDraftBlock(), MainWindow::ApplyDialog(), MainWindow::ChangedHeight(), MainWindow::changeDraftBlock(), MainWindow::ChangedSize(), MainWindow::CheckPathToMeasurements(), MainWindow::CheckRequiredMeasurements(), MainWindow::Clear(), MainWindow::ClosedDialog(), MainWindow::ClosedDialogAnchorPoint(), MainWindow::ClosedDialogInternalPath(), MainWindow::ClosedDialogWithApply(), MainWindow::ClosedEditGroupDialog(), MainWindow::ClosedInsertNodesDialog(), MainWindow::closeUnionDialog(), MainWindow::exportDraftBlocksAs(), exportSVG(), MainWindow::fullParseFile(), MainWindow::GetMeasurementFileName(), MainWindow::InitDocksContain(), MainWindow::initDraftToolBar(), MainWindow::initStatusBar(), MainWindow::LoadIndividual(), MainWindow::LoadMeasurements(), MainWindow::LoadMultisize(), MainWindow::LoadPattern(), MainWindow::patternChangesWereSaved(), MainWindow::penChanged(), MainWindow::SaveAs(), MainWindow::SavePattern(), MainWindow::setCurrentFile(), MainWindow::SetDefaultHeight(), MainWindow::SetDefaultSize(), SetSizeHeightForIndividualM(), MainWindow::SetToolButton(), MainWindow::setWidgetsEnabled(), MainWindow::ShowMeasurements(), MainWindow::SyncMeasurements(), MainWindow::UnloadMeasurements(), MainWindow::UpdateMeasurements(), MainWindow::zoomToPoint(), MainWindow::zoomToSelected(), and MainWindow::~MainWindow().
ignoreMargins
bool MainWindowsNoGUI::ignoreMargins protected
Definition at line 122 of file mainwindowsnogui.h.
Referenced by ExportData(), exportEPS(), ExportFlatLayout(), exportPDF(), exportPiecesAsFlatLayout(), exportPS(), ExportScene(), and LayoutSettings().
isAutoCrop
bool MainWindowsNoGUI::isAutoCrop private
Definition at line 147 of file mainwindowsnogui.h.
Referenced by LayoutSettings(), and SetPrinterSettings().
isLayoutStale
bool MainWindowsNoGUI::isLayoutStale protected
Definition at line 121 of file mainwindowsnogui.h.
Referenced by MainWindow::exportLayoutAs(), LayoutPrint(), LayoutSettings(), MainWindow::patternChangesWereSaved(), PdfTiledFile(), and PrintPreview().
isNoScaling
bool MainWindowsNoGUI::isNoScaling protected
Definition at line 120 of file mainwindowsnogui.h.
Referenced by MainWindow::LoadPattern(), MainWindow::ProcessCMD(), and MainWindow::ShowMeasurements().
isTiled
bool MainWindowsNoGUI::isTiled private
Definition at line 146 of file mainwindowsnogui.h.
Referenced by PdfTiledFile(), PrintOrigin(), PrintPages(), PrintPreviewOrigin(), PrintPreviewTiled(), PrintTiled(), and SetPrinterSettings().
isUnitePages
bool MainWindowsNoGUI::isUnitePages private
Definition at line 148 of file mainwindowsnogui.h.
Referenced by LayoutSettings(), and SetPrinterSettings().
layoutPrinterName
QString MainWindowsNoGUI::layoutPrinterName private
Definition at line 150 of file mainwindowsnogui.h.
Referenced by LayoutPrint(), PrintPreview(), and toolLayoutSettings().
margins
QMarginsF MainWindowsNoGUI::margins protected
Definition at line 123 of file mainwindowsnogui.h.
Referenced by ExportData(), MainWindow::exportDraftBlocksAs(), exportEPS(), ExportFlatLayout(), exportPDF(), exportPS(), ExportScene(), LayoutSettings(), and SetPrinterSettings().
papers
QList<QGraphicsItem *> MainWindowsNoGUI::papers protected
doc dom document container
Definition at line 107 of file mainwindowsnogui.h.
Referenced by MainWindow::CleanLayout(), CreateScenes(), CreateShadows(), ExportData(), ExportFlatLayout(), exportPiecesAsFlatLayout(), ExportScene(), IsLayoutGrayscale(), IsPagesFit(), isPagesUniform(), LayoutSettings(), PreparePaper(), PrintPages(), RestorePaper(), ScenePreview(), and SetPrinterSettings().
paperSize
QSizeF MainWindowsNoGUI::paperSize protected
Definition at line 124 of file mainwindowsnogui.h.
Referenced by LayoutSettings(), and SetPrinterSettings().
pattern
VContainer* MainWindowsNoGUI::pattern protected
pattern container with data (points, arcs, splines, spline paths, variables)
Definition at line 104 of file mainwindowsnogui.h.
Referenced by MainWindow::addDraftBlock(), MainWindow::ApplyDialog(), MainWindow::CheckPathToMeasurements(), MainWindow::Clear(), MainWindow::ClosedDialog(), MainWindow::ClosedDialogAnchorPoint(), MainWindow::ClosedDialogInternalPath(), MainWindow::ClosedInsertNodesDialog(), MainWindow::ClosedPiecesDialogWithApply(), MainWindow::DoExport(), MainWindow::draftPointNamesList(), MainWindow::exportPiecesAs(), MainWindow::exportToCSVData(), MainWindow::handlePieceMenu(), MainWindow::InitDocksContain(), MainWindow::LoadMeasurements(), MainWindow::LoadPattern(), MainWindow::New(), MainWindow::OpenMeasurementFile(), refreshGrainLines(), refreshLabels(), refreshSeamAllowances(), MainWindow::SetHeight(), MainWindow::SetSize(), SetSizeHeightForIndividualM(), MainWindow::SetToolButton(), MainWindow::setToolsEnabled(), MainWindow::showLayoutMode(), MainWindow::showPieceMode(), MainWindow::UpdateMeasurements(), MainWindow::zoomFirstShow(), MainWindow::zoomToPoint(), and ~MainWindowsNoGUI().
pieceList
QVector<VLayoutPiece> MainWindowsNoGUI::pieceList protected
Definition at line 100 of file mainwindowsnogui.h.
Referenced by MainWindow::Clear(), MainWindow::DoExport(), ExportData(), MainWindow::exportPiecesAs(), exportPiecesAsApparelLayout(), exportPiecesAsFlatLayout(), LayoutSettings(), preparePiecesForLayout(), and MainWindow::showLayoutMode().
pieces
QList<QList<QGraphicsItem *> > MainWindowsNoGUI::pieces protected
Definition at line 110 of file mainwindowsnogui.h.
Referenced by AAMADxfFile(), CreateScenes(), MainWindow::DoExport(), ExportApparelLayout(), ExportData(), ExportFlatLayout(), exportPiecesAsFlatLayout(), ExportScene(), LayoutSettings(), preparePiecesForLayout(), PrepareTextForDXF(), RestoreTextAfterDXF(), and MainWindow::showLayoutMode().
piecesOnLayout
QVector<QVector<VLayoutPiece> > MainWindowsNoGUI::piecesOnLayout protected
Definition at line 111 of file mainwindowsnogui.h.
Referenced by ExportData(), and LayoutSettings().
redoAction
QAction* MainWindowsNoGUI::redoAction protected
Definition at line 114 of file mainwindowsnogui.h.
Referenced by MainWindow::changeEvent(), MainWindow::CreateMenus(), and MainWindow::setWidgetsEnabled().
scenes
QList<QGraphicsScene *> MainWindowsNoGUI::scenes protected
Definition at line 109 of file mainwindowsnogui.h.
Referenced by MainWindow::CleanLayout(), CreateScenes(), MainWindow::DoExport(), ExportData(), ExportFlatLayout(), MainWindow::exportLayoutAs(), exportPiecesAsFlatLayout(), ExportScene(), IsLayoutGrayscale(), LayoutSettings(), PreparePaper(), MainWindow::PrepareSceneList(), PrintPages(), RestorePaper(), ScenePreview(), MainWindow::SetLayoutModeActions(), MainWindow::showLayoutMode(), and MainWindow::showLayoutPages().
shadows
QList<QGraphicsItem *> MainWindowsNoGUI::shadows protected
Definition at line 108 of file mainwindowsnogui.h.
Referenced by MainWindow::CleanLayout(), CreateScenes(), CreateShadows(), ExportData(), ExportFlatLayout(), exportPiecesAsFlatLayout(), ExportScene(), LayoutSettings(), PreparePaper(), and RestorePaper().
tempSceneLayout
QGraphicsScene* MainWindowsNoGUI::tempSceneLayout protected
currentScene pointer to current scene.
Definition at line 103 of file mainwindowsnogui.h.
Referenced by InitTempLayoutScene(), MainWindow::showLayoutMode(), MainWindow::showLayoutPages(), and ~MainWindowsNoGUI().
undoAction
QAction* MainWindowsNoGUI::undoAction protected
Definition at line 113 of file mainwindowsnogui.h.
Referenced by MainWindow::changeEvent(), MainWindow::CreateMenus(), and MainWindow::setWidgetsEnabled().
The documentation for this class was generated from the following files:
src/app/seamly2d/mainwindowsnogui.h
src/app/seamly2d/mainwindowsnogui.cpp