Seamly2D: PatternPieceDialog Class Reference
PatternPieceDialog Class Reference
#include <pattern_piece_dialog.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
ChosenObject adds selected object of id and type to list of path items.
virtual void ShowDialog (bool click) Q_DECL_OVERRIDE
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
PatternPieceDialog (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
virtual ~PatternPieceDialog ()
void pageChanged (QListWidgetItem *current, QListWidgetItem *previous)
void enableApply (bool enable)
VPiece GetPiece () const
void SetPiece (const VPiece &piece)
QString getSeamAllowanceWidthFormula () const
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void CheckState () Q_DECL_FINAL
SaveData Put dialog data in local variables.
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
virtual void resizeEvent (QResizeEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
virtual void ShowVisualization ()
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Slots
void setErrorText (TabOrder tab, QString text)
void clearErrorText (TabOrder tab, QString text)
void pieceNameChanged ()
void pieceColorChanged ()
void showMainPathContextMenu (const QPoint &pos)
void showCustomSAContextMenu (const QPoint &pos)
void showInternalPathsContextMenu (const QPoint &pos)
void showAnchorsContextMenu (const QPoint &pos)
void nodeListChanged ()
void enableSeamAllowance (bool enable)
void enableBuiltIn (bool enable)
void nodeChanged (int index)
void notchChanged (int index)
void customSAStartPointChanged (int index)
void customSAEndPointChanged (int index)
void customSAIncludeTypeChanged (int index)
void nodeAngleChanged (int index)
void enableDefaultBeforeButton ()
void enableDefaultAfterButton ()
void customSeamAllowanceChanged (int row)
void pathDialogClosed (int result)
void notchTypeChanged (int id)
void notchSubTypeChanged (int id)
void showNotchChanged (int state)
void showSeamlineNotchChanged (int state)
void notchLengthChanged (qreal value)
void resetNotchLength ()
void notchWidthChanged (qreal value)
void resetNotchWidth ()
void notchAngleChanged (qreal value)
void resetNotchAngle ()
void notchCountChanged (int value)
void updateGrainlineValues ()
void updatePieceLabelValues ()
void updatePatternLabelValues ()
void editGrainlineFormula ()
void editPieceLabelFormula ()
void editPatternLabelFormula ()
void resetGrainlineWarning ()
void resetLabelsWarning ()
void enabledGrainline ()
void enabledPieceLabel ()
void enabledPatternLabel ()
void evaluateDefaultWidth ()
void evaluateBeforeWidth ()
void evaluateAfterWidth ()
void editDefaultSeamAllowanceWidth ()
void editBeforeSeamAllowanceWidth ()
void editAfterSeamAllowanceWidth ()
void defaultWidthChanged ()
void beforeWidthChanged ()
void afterWidthChanged ()
void grainlineAnchorChanged ()
void pieceLabelAnchorChanged ()
void patternLabelAnchorChanged ()
void editPieceLabel ()
void editPatternLabel ()
Private Member Functions
VPiece CreatePiece () const
void newMainPathItem (const VPieceNode &node)
void newCustomSeamAllowance (const CustomSARecord &record)
void newInternalPath (quint32 path)
void newAnchorPoint (quint32 anchorPoint)
QString getPathName (quint32 path, bool reverse=false) const
QString getPieceColor () const
void setPieceColor (const QString &value)
QString getPieceFill () const
void setPieceFill (const QString &value)
bool isInLayout () const
void setInLayout (const bool &state)
bool getPieceLock () const
void setPieceLock (const bool &state)
bool isMainPathValid () const
void validateObjects (bool value)
bool isMainPathClockwise () const
void updateCurrentCustomSARecord ()
void updateCurrentInternalPathRecord ()
QListWidgetItem * getItemById (quint32 id)
quint32 getPreviousId () const
VPieceNode getLastNode () const
bool pointNodesExist () const
void setCurrentBeforeSeamAllowance (const QString &formula)
void setCurrentAfterSeamAllowance (const QString &formula)
void updateNodeBeforeSeamAllowance (const QString &formula)
void updateNodeAfterSeamAllowance (const QString &formula)
void initializeMainPathTab ()
void initializeSeamAllowanceTab ()
void initializeNodesList ()
void initializeNotchesList ()
void initializeCSAPoint (QComboBox *box)
void initAnchorPoint (QComboBox *box)
void initializeSAIncludeType ()
void initializeInternalPathsTab ()
void initializePropertiesTab ()
void initializeLabelsTab ()
void initializeGrainlineTab ()
void initializeAnchorsTab ()
void initializeNotchesTab ()
void initAnchorPointComboboxes ()
void setSeamAllowanceWidthFormula (const QString &formula)
void setGrainlineAngle (QString angleFormula)
void setGrainlineLength (QString lengthFormula)
void setPieceLabelWidth (QString widthFormula)
void setPieceLabelHeight (QString heightFormula)
void setPieceLabelAngle (QString angleFormula)
void setPatternLabelWidth (QString widthFormula)
void setPatternLabelHeight (QString heightFormula)
void setPatternLabelAngle (QString angleFormula)
void showAnchorPoints ()
void setMoveExclusions ()
QString createPieceName () const
void reverseNode (QListWidgetItem *rowItem)
void duplicateNode (QListWidgetItem *rowItem)
void excludeNode (QListWidgetItem *rowItem)
void setNotch (QListWidgetItem *rowItem, bool isNotch, NotchType notchType, NotchSubType notchSubType)
void setCurrentText (QComboBox *box, const QString &text) const
qreal getFormulaValue (QPlainTextEdit *text) const
Private Attributes
Ui::PatternPieceDialog * ui
bool applyAllowed
bool flagGrainlineAnchor
bool flagPieceLabelAnchor
bool flagPatternLabelAnchor
bool flagGrainlineFormula
bool flagPieceLabelAngle
bool flagPieceLabelFormula
bool flagPatternLabelAngle
bool flagPatternLabelFormula
bool flagBeforeFormula
bool flagAfterFormula
bool flagMainPath
bool m_bAddMode
qreal m_mx
qreal m_my
bool m_inLayout
bool m_isLocked
QPointer< DialogTool > m_dialog
QPointer< PieceAnchorPointVisual > m_anchorPoints
VPieceLabelData m_oldData
VPatternLabelData m_oldGeom
VGrainlineData m_oldGrainline
QTimer * m_timerWidth
QTimer * m_timerWidthBefore
QTimer * m_timerWidthAfter
qreal m_saWidth
QVector< VLabelTemplateLine > m_patternLabelLines
QVector< VLabelTemplateLine > m_pieceLabelLines
QSound * m_beep
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
Definition at line 78 of file pattern_piece_dialog.h.
Constructor & Destructor Documentation
PatternPieceDialog()
PatternPieceDialog::PatternPieceDialog (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
Definition at line 113 of file pattern_piece_dialog.cpp.
References applyAllowed, DialogTool::ChangeColor(), CheckState(), DialogTool::data, enableApply(), flagMainPath, DialogTool::flagName, initializeAnchorsTab(), initializeGrainlineTab(), initializeInternalPathsTab(), initializeLabelsTab(), initializeMainPathTab(), initializeNotchesTab(), DialogTool::initializeOkCancelApply(), initializePropertiesTab(), initializeSeamAllowanceTab(), isMainPathValid(), DialogTool::okColor, pageChanged(), Properties, ui, and DialogTool::vis.
~PatternPieceDialog()
PatternPieceDialog::~PatternPieceDialog () virtual
Definition at line 183 of file pattern_piece_dialog.cpp.
References m_anchorPoints, and ui.
Member Function Documentation
afterWidthChanged
void PatternPieceDialog::afterWidthChanged () private slot
Definition at line 2273 of file pattern_piece_dialog.cpp.
References flagAfterFormula, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, m_timerWidthAfter, qApp, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by initializeSeamAllowanceTab().
beforeWidthChanged
void PatternPieceDialog::beforeWidthChanged () private slot
Definition at line 2263 of file pattern_piece_dialog.cpp.
References flagBeforeFormula, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, m_timerWidthBefore, qApp, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by initializeSeamAllowanceTab().
CheckState()
void PatternPieceDialog::CheckState () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 525 of file pattern_piece_dialog.cpp.
References DialogTool::apply_Button, applyAllowed, clearErrorText(), flagAfterFormula, flagBeforeFormula, DialogTool::flagFormula, flagGrainlineAnchor, flagGrainlineFormula, flagMainPath, DialogTool::flagName, flagPatternLabelAnchor, flagPatternLabelAngle, flagPatternLabelFormula, flagPieceLabelAnchor, flagPieceLabelAngle, flagPieceLabelFormula, DialogTool::ok_Button, Paths, SCASSERT, SeamAllowance, setErrorText(), and ui.
Referenced by enabledGrainline(), enabledPatternLabel(), enabledPieceLabel(), grainlineAnchorChanged(), patternLabelAnchorChanged(), PatternPieceDialog(), pieceColorChanged(), pieceLabelAnchorChanged(), pieceNameChanged(), updateGrainlineValues(), updatePatternLabelValues(), updatePieceLabelValues(), and validateObjects().
ChosenObject
void PatternPieceDialog::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChosenObject adds selected object of id and type to list of path items.
Parameters
id id of object (points, arcs, splines, spline paths)
type type of scene object
Definition at line 357 of file pattern_piece_dialog.cpp.
References applyAllowed, Arc, VPiecePath::CountNodes(), CreatePiece(), DialogTool::data, ElArc, VContainer::GeometricObject(), VContainer::GetGObject(), getItemById(), getLastNode(), VPiece::GetPath(), getPreviousId(), VPieceNode::GetReverse(), VAbstractPiece::isClockwise(), isMainPathValid(), Line, m_beep, VPiece::MainPathPoints(), newMainPathItem(), NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, NULL_ID, Piece, Point, DialogTool::prepare, qApp, SCASSERT, Spline, SplinePath, DialogTool::ToolTip(), ui, Unknown, validateObjects(), and DialogTool::vis.
clearErrorText
void PatternPieceDialog::clearErrorText (TabOrder tab, QString text) private slot
Definition at line 574 of file pattern_piece_dialog.cpp.
References ui.
Referenced by CheckState(), patternLabelAnchorChanged(), pieceLabelAnchorChanged(), pieceNameChanged(), resetGrainlineWarning(), and resetLabelsWarning().
closeEvent()
void PatternPieceDialog::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 705 of file pattern_piece_dialog.cpp.
References DialogTool::closeEvent(), and ui.
CreatePiece()
VPiece PatternPieceDialog::CreatePiece () const private
Definition at line 2407 of file pattern_piece_dialog.cpp.
References applyAllowed, DialogTool::data, DialogTool::getCurrentObjectId(), VPatternLabelData::getFontSize(), anonymous_namespace{pattern_piece_dialog.cpp}::getFormulaFromUser(), getFormulaValue(), VPiece::GetGrainlineGeometry(), VPiece::GetPath(), VPiece::GetPatternInfo(), VPiece::GetPatternPieceData(), getPieceColor(), getPieceFill(), getPieceLock(), isInLayout(), m_mx, m_my, m_oldData, m_oldGeom, m_oldGrainline, m_pieceLabelLines, m_saWidth, VPiecePath::PathPoints(), VPiece::setAnchors(), VPieceLabelData::SetAnnotation(), VGrainlineData::SetArrowType(), VGrainlineData::setBottomAnchorPoint(), VPatternLabelData::setBottomRightAnchorPoint(), VPatternLabelData::setCenterAnchorPoint(), VGrainlineData::setCenterAnchorPoint(), VAbstractPiece::setColor(), VPiece::SetCustomSARecords(), VAbstractPiece::setFill(), VPieceLabelData::SetFoldPosition(), VPatternLabelData::SetFontSize(), VAbstractPiece::SetForbidFlipping(), VAbstractPiece::setHideSeamLine(), VPiece::SetInLayout(), VPiece::SetInternalPaths(), VPiece::setIsLocked(), VPatternLabelData::SetLabelHeight(), VPieceLabelData::SetLabelTemplate(), VPatternLabelData::SetLabelWidth(), VGrainlineData::SetLength(), VPieceLabelData::SetLetter(), VAbstractPiece::SetMx(), VAbstractPiece::SetMy(), VAbstractPiece::SetName(), VPiecePath::SetNodes(), VPieceLabelData::SetOnFold(), VPieceLabelData::SetOrientation(), VAbstractFloatItemData::SetPos(), VPieceLabelData::SetQuantity(), VPatternLabelData::SetRotation(), VGrainlineData::SetRotation(), VPieceLabelData::SetRotationWay(), VAbstractPiece::SetSeamAllowance(), VAbstractPiece::SetSeamAllowanceBuiltIn(), VPiece::setSeamAllowanceWidthFormula(), VPieceLabelData::SetTilt(), VGrainlineData::setTopAnchorPoint(), VPatternLabelData::setTopLeftAnchorPoint(), VAbstractFloatItemData::SetVisible(), and ui.
Referenced by ChosenObject(), GetPiece(), isMainPathClockwise(), isMainPathValid(), nodeChanged(), nodeListChanged(), notchChanged(), and setSeamAllowanceWidthFormula().
createPieceName()
QString PatternPieceDialog::createPieceName () const private
Definition at line 3456 of file pattern_piece_dialog.cpp.
References DialogTool::data, and VContainer::DataPieces().
Referenced by initializeLabelsTab().
customSAEndPointChanged
void PatternPieceDialog::customSAEndPointChanged (int index) private slot
Definition at line 1287 of file pattern_piece_dialog.cpp.
References CustomSARecord::endPoint, SCASSERT, and ui.
Referenced by initializeSeamAllowanceTab().
customSAIncludeTypeChanged
void PatternPieceDialog::customSAIncludeTypeChanged (int index) private slot
Definition at line 1305 of file pattern_piece_dialog.cpp.
References CustomSARecord::includeType, SCASSERT, and ui.
Referenced by initializeSeamAllowanceTab().
customSAStartPointChanged
void PatternPieceDialog::customSAStartPointChanged (int index) private slot
Definition at line 1269 of file pattern_piece_dialog.cpp.
References SCASSERT, CustomSARecord::startPoint, and ui.
Referenced by initializeSeamAllowanceTab().
customSeamAllowanceChanged
void PatternPieceDialog::customSeamAllowanceChanged (int row) private slot
Definition at line 1363 of file pattern_piece_dialog.cpp.
References CustomSARecord::endPoint, CustomSARecord::includeType, initializeCSAPoint(), initializeSAIncludeType(), SCASSERT, CustomSARecord::startPoint, and ui.
Referenced by initializeSeamAllowanceTab(), nodeListChanged(), and SetPiece().
defaultWidthChanged
void PatternPieceDialog::defaultWidthChanged () private slot
Definition at line 2254 of file pattern_piece_dialog.cpp.
References DialogTool::flagFormula, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, m_timerWidth, qApp, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by initializeSeamAllowanceTab().
duplicateNode()
void PatternPieceDialog::duplicateNode (QListWidgetItem * rowItem) private
Definition at line 3501 of file pattern_piece_dialog.cpp.
References VPieceNode::GetTypeTool(), DialogTool::newNodeItem(), NodePoint, VPieceNode::SetExcluded(), and ui.
Referenced by eventFilter(), and showMainPathContextMenu().
editAfterSeamAllowanceWidth
void PatternPieceDialog::editAfterSeamAllowanceWidth () private slot
Definition at line 2239 of file pattern_piece_dialog.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), anonymous_namespace{pattern_piece_dialog.cpp}::getFormulaFromUser(), qApp, EditFormulaDialog::setCheckLessThanZero(), setCurrentAfterSeamAllowance(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), DialogTool::toolId, ui, and UnitsToStr().
Referenced by initializeSeamAllowanceTab().
editBeforeSeamAllowanceWidth
void PatternPieceDialog::editBeforeSeamAllowanceWidth () private slot
Definition at line 2224 of file pattern_piece_dialog.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), anonymous_namespace{pattern_piece_dialog.cpp}::getFormulaFromUser(), qApp, EditFormulaDialog::setCheckLessThanZero(), setCurrentBeforeSeamAllowance(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), DialogTool::toolId, ui, and UnitsToStr().
Referenced by initializeSeamAllowanceTab().
editDefaultSeamAllowanceWidth
void PatternPieceDialog::editDefaultSeamAllowanceWidth () private slot
Definition at line 2209 of file pattern_piece_dialog.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), getSeamAllowanceWidthFormula(), qApp, EditFormulaDialog::setCheckLessThanZero(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), setSeamAllowanceWidthFormula(), DialogTool::toolId, and UnitsToStr().
Referenced by initializeSeamAllowanceTab().
editGrainlineFormula
void PatternPieceDialog::editGrainlineFormula () private slot
Definition at line 1960 of file pattern_piece_dialog.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), NULL_ID, qApp, EditFormulaDialog::setCheckZero(), EditFormulaDialog::SetFormula(), setGrainlineAngle(), setGrainlineLength(), ui, and updateGrainlineValues().
Referenced by initializeGrainlineTab().
editPatternLabel
void PatternPieceDialog::editPatternLabel () private slot
Definition at line 2378 of file pattern_piece_dialog.cpp.
References GetPiece(), EditLabelTemplateDialog::GetTemplate(), qApp, EditLabelTemplateDialog::SetPiece(), and EditLabelTemplateDialog::SetTemplate().
Referenced by initializeLabelsTab().
editPatternLabelFormula
void PatternPieceDialog::editPatternLabelFormula () private slot
Definition at line 2071 of file pattern_piece_dialog.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), NULL_ID, qApp, EditFormulaDialog::setCheckZero(), EditFormulaDialog::SetFormula(), setPatternLabelAngle(), setPatternLabelHeight(), setPatternLabelWidth(), ui, and updatePatternLabelValues().
Referenced by initializeLabelsTab().
editPieceLabel
void PatternPieceDialog::editPieceLabel () private slot
Definition at line 2394 of file pattern_piece_dialog.cpp.
References GetPiece(), EditLabelTemplateDialog::GetTemplate(), m_pieceLabelLines, qApp, EditLabelTemplateDialog::SetPiece(), and EditLabelTemplateDialog::SetTemplate().
Referenced by initializeLabelsTab().
editPieceLabelFormula
void PatternPieceDialog::editPieceLabelFormula () private slot
Definition at line 2011 of file pattern_piece_dialog.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), NULL_ID, qApp, EditFormulaDialog::setCheckZero(), EditFormulaDialog::SetFormula(), setPieceLabelAngle(), setPieceLabelHeight(), setPieceLabelWidth(), ui, and updatePieceLabelValues().
Referenced by initializeLabelsTab().
enableApply()
void PatternPieceDialog::enableApply (bool enable)
Definition at line 213 of file pattern_piece_dialog.cpp.
References DialogTool::apply_Button, applyAllowed, Count, SCASSERT, SeamAllowance, and ui.
Referenced by PatternPieceDialog().
enableBuiltIn
void PatternPieceDialog::enableBuiltIn (bool enable) private slot
Definition at line 1077 of file pattern_piece_dialog.cpp.
References initializeNodesList(), and ui.
Referenced by initializeSeamAllowanceTab().
enableDefaultAfterButton
void PatternPieceDialog::enableDefaultAfterButton () private slot
Definition at line 1352 of file pattern_piece_dialog.cpp.
References currentSeamAllowance, qApp, and ui.
Referenced by initializeSeamAllowanceTab().
enableDefaultBeforeButton
void PatternPieceDialog::enableDefaultBeforeButton () private slot
Definition at line 1341 of file pattern_piece_dialog.cpp.
References currentSeamAllowance, qApp, and ui.
Referenced by initializeSeamAllowanceTab().
enabledGrainline
void PatternPieceDialog::enabledGrainline () private slot
Definition at line 1910 of file pattern_piece_dialog.cpp.
References CheckState(), flagGrainlineFormula, grainlineAnchorChanged(), resetGrainlineWarning(), ui, and updateGrainlineValues().
Referenced by initializeGrainlineTab(), and SetPiece().
enabledPatternLabel
void PatternPieceDialog::enabledPatternLabel () private slot
Definition at line 1943 of file pattern_piece_dialog.cpp.
References CheckState(), flagPatternLabelAngle, flagPatternLabelFormula, patternLabelAnchorChanged(), resetLabelsWarning(), ui, and updatePatternLabelValues().
Referenced by initializeLabelsTab(), and SetPiece().
enabledPieceLabel
void PatternPieceDialog::enabledPieceLabel () private slot
Definition at line 1926 of file pattern_piece_dialog.cpp.
References CheckState(), flagPieceLabelAngle, flagPieceLabelFormula, pieceLabelAnchorChanged(), resetLabelsWarning(), ui, and updatePieceLabelValues().
Referenced by initializeLabelsTab(), and SetPiece().
enableSeamAllowance
void PatternPieceDialog::enableSeamAllowance (bool enable) private slot
Definition at line 1061 of file pattern_piece_dialog.cpp.
References ui.
Referenced by initializeSeamAllowanceTab().
evaluateAfterWidth
void PatternPieceDialog::evaluateAfterWidth () private slot
Definition at line 2193 of file pattern_piece_dialog.cpp.
References anonymous_namespace{pattern_piece_dialog.cpp}::enableDefaultButton(), DialogTool::Eval(), flagAfterFormula, anonymous_namespace{pattern_piece_dialog.cpp}::getFormulaFromUser(), DialogTool::labelEditFormula, qApp, ui, UnitsToStr(), and updateNodeAfterSeamAllowance().
Referenced by evaluateDefaultWidth(), and initializeSeamAllowanceTab().
evaluateBeforeWidth
void PatternPieceDialog::evaluateBeforeWidth () private slot
Definition at line 2177 of file pattern_piece_dialog.cpp.
References anonymous_namespace{pattern_piece_dialog.cpp}::enableDefaultButton(), DialogTool::Eval(), flagBeforeFormula, anonymous_namespace{pattern_piece_dialog.cpp}::getFormulaFromUser(), DialogTool::labelEditFormula, qApp, ui, UnitsToStr(), and updateNodeBeforeSeamAllowance().
Referenced by evaluateDefaultWidth(), and initializeSeamAllowanceTab().
evaluateDefaultWidth
void PatternPieceDialog::evaluateDefaultWidth () private slot
Definition at line 2157 of file pattern_piece_dialog.cpp.
References VContainer::AddVariable(), currentSeamAllowance, DialogTool::data, DialogTool::Eval(), evaluateAfterWidth(), evaluateBeforeWidth(), DialogTool::flagFormula, DialogTool::labelEditFormula, m_saWidth, qApp, ui, and UnitsToStr().
Referenced by initializeSeamAllowanceTab().
eventFilter()
bool PatternPieceDialog::eventFilter (QObject * object, QEvent * event) protected virtual
Reimplemented from DialogTool.
Definition at line 589 of file pattern_piece_dialog.cpp.
References Bisector, Castle, Diamond, duplicateNode(), DialogTool::eventFilter(), excludeNode(), VPieceNode::getNotchSubType(), VPieceNode::getNotchType(), Intersection, reverseNode(), SCASSERT, setNotch(), Slit, Straightforward, TNotch, ui, UNotch, VExternal, and VInternal.
excludeNode()
void PatternPieceDialog::excludeNode (QListWidgetItem * rowItem) private
Definition at line 3516 of file pattern_piece_dialog.cpp.
References DialogTool::getNodeInfo(), NodeInfo::icon, VPieceNode::isExcluded(), NodeInfo::name, DialogTool::NodeFont(), and VPieceNode::SetExcluded().
Referenced by eventFilter(), and showMainPathContextMenu().
getFormulaValue()
qreal PatternPieceDialog::getFormulaValue (QPlainTextEdit * text) const private
Definition at line 3565 of file pattern_piece_dialog.cpp.
References DialogTool::data, VContainer::DataVariables(), Calculator::EvalFormula(), VContainer::GetPatternUnit(), qApp, and ToPixel().
Referenced by CreatePiece().
getItemById()
QListWidgetItem * PatternPieceDialog::getItemById (quint32 id) private
Definition at line 2737 of file pattern_piece_dialog.cpp.
References VPieceNode::GetId(), and ui.
Referenced by ChosenObject(), nodeAngleChanged(), notchAngleChanged(), notchCountChanged(), notchLengthChanged(), notchSubTypeChanged(), notchTypeChanged(), notchWidthChanged(), showNotchChanged(), showSeamlineNotchChanged(), updateNodeAfterSeamAllowance(), and updateNodeBeforeSeamAllowance().
getLastNode()
VPieceNode PatternPieceDialog::getLastNode () const private
Definition at line 2769 of file pattern_piece_dialog.cpp.
References ui.
Referenced by ChosenObject().
getPathName()
QString PatternPieceDialog::getPathName (quint32 path, bool reverse = false) const private
Definition at line 2536 of file pattern_piece_dialog.cpp.
References DialogTool::data, VPiecePath::GetName(), VContainer::GetPiecePath(), and NULL_ID.
Referenced by newCustomSeamAllowance(), newInternalPath(), showCustomSAContextMenu(), updateCurrentCustomSARecord(), and updateCurrentInternalPathRecord().
GetPiece()
VPiece PatternPieceDialog::GetPiece () const
Definition at line 241 of file pattern_piece_dialog.cpp.
References CreatePiece().
Referenced by editPatternLabel(), editPieceLabel(), and PatternPieceTool::SaveDialogChange().
getPieceColor()
QString PatternPieceDialog::getPieceColor () const private
Definition at line 2554 of file pattern_piece_dialog.cpp.
References ui.
Referenced by CreatePiece().
getPieceFill()
QString PatternPieceDialog::getPieceFill () const private
Definition at line 2568 of file pattern_piece_dialog.cpp.
References FillNone, DialogTool::GetComboBoxCurrentData(), and ui.
Referenced by CreatePiece().
getPieceLock()
bool PatternPieceDialog::getPieceLock () const private
Definition at line 2593 of file pattern_piece_dialog.cpp.
References m_isLocked.
Referenced by CreatePiece().
getPreviousId()
quint32 PatternPieceDialog::getPreviousId () const private
Definition at line 2753 of file pattern_piece_dialog.cpp.
References VPieceNode::GetId(), NULL_ID, and ui.
Referenced by ChosenObject().
getSeamAllowanceWidthFormula()
QString PatternPieceDialog::getSeamAllowanceWidthFormula () const
Definition at line 3238 of file pattern_piece_dialog.cpp.
References qApp, and ui.
Referenced by editDefaultSeamAllowanceWidth(), and showCustomSAContextMenu().
grainlineAnchorChanged
void PatternPieceDialog::grainlineAnchorChanged () private slot
Definition at line 2283 of file pattern_piece_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::errorColor, flagGrainlineAnchor, flagGrainlineFormula, DialogTool::getCurrentObjectId(), Grainline, NULL_ID, DialogTool::okColor, resetGrainlineWarning(), ui, and updateGrainlineValues().
Referenced by enabledGrainline(), and initializeGrainlineTab().
initAnchorPoint()
void PatternPieceDialog::initAnchorPoint (QComboBox * box) private
Definition at line 2973 of file pattern_piece_dialog.cpp.
References DialogTool::data, VContainer::GetGObject(), NULL_ID, SCASSERT, and ui.
Referenced by initAnchorPointComboboxes(), initializeGrainlineTab(), and initializeLabelsTab().
initAnchorPointComboboxes()
void PatternPieceDialog::initAnchorPointComboboxes () private
Definition at line 3222 of file pattern_piece_dialog.cpp.
References initAnchorPoint(), and ui.
Referenced by SetPiece(), and showAnchorsContextMenu().
initializeAnchorsTab()
void PatternPieceDialog::initializeAnchorsTab () private
Definition at line 3170 of file pattern_piece_dialog.cpp.
References showAnchorsContextMenu(), and ui.
Referenced by PatternPieceDialog().
initializeCSAPoint()
void PatternPieceDialog::initializeCSAPoint (QComboBox * box) private
Definition at line 2953 of file pattern_piece_dialog.cpp.
References VPieceNode::GetId(), DialogTool::getNodeInfo(), VPieceNode::GetTypeTool(), VPieceNode::isExcluded(), NodeInfo::name, NodePoint, NULL_ID, SCASSERT, and ui.
Referenced by customSeamAllowanceChanged().
initializeGrainlineTab()
void PatternPieceDialog::initializeGrainlineTab () private
Definition at line 3137 of file pattern_piece_dialog.cpp.
References editGrainlineFormula(), enabledGrainline(), grainlineAnchorChanged(), initAnchorPoint(), qApp, ui, and updateGrainlineValues().
Referenced by PatternPieceDialog().
initializeInternalPathsTab()
void PatternPieceDialog::initializeInternalPathsTab () private
Definition at line 3013 of file pattern_piece_dialog.cpp.
References showInternalPathsContextMenu(), and ui.
Referenced by PatternPieceDialog().
initializeLabelsTab()
void PatternPieceDialog::initializeLabelsTab () private
Definition at line 3036 of file pattern_piece_dialog.cpp.
References createPieceName(), editPatternLabel(), editPatternLabelFormula(), editPieceLabel(), editPieceLabelFormula(), enabledPatternLabel(), enabledPieceLabel(), initAnchorPoint(), m_patternLabelLines, m_pieceLabelLines, patternLabelAnchorChanged(), pieceLabelAnchorChanged(), qApp, VLabelTemplate::ReadLines(), VDomDocument::setXMLContent(), ui, updatePatternLabelValues(), and updatePieceLabelValues().
Referenced by PatternPieceDialog().
initializeMainPathTab()
void PatternPieceDialog::initializeMainPathTab () private
Definition at line 2848 of file pattern_piece_dialog.cpp.
References qApp, setMoveExclusions(), showMainPathContextMenu(), and ui.
Referenced by PatternPieceDialog().
initializeNodesList()
void PatternPieceDialog::initializeNodesList () private
Definition at line 2661 of file pattern_piece_dialog.cpp.
References VPieceNode::GetId(), DialogTool::getNodeInfo(), VPieceNode::GetTypeTool(), VPieceNode::isExcluded(), NodeInfo::name, nodeChanged(), NodePoint, pointNodesExist(), and ui.
Referenced by enableBuiltIn(), initializeSeamAllowanceTab(), and nodeListChanged().
initializeNotchesList()
void PatternPieceDialog::initializeNotchesList () private
Definition at line 2703 of file pattern_piece_dialog.cpp.
References VPieceNode::GetId(), DialogTool::getNodeInfo(), VPieceNode::GetTypeTool(), NodeInfo::icon, VPieceNode::isNotch(), NodeInfo::name, NodePoint, notchChanged(), and ui.
Referenced by initializeNotchesTab(), and nodeListChanged().
initializeNotchesTab()
void PatternPieceDialog::initializeNotchesTab () private
Definition at line 3178 of file pattern_piece_dialog.cpp.
References initializeNotchesList(), notchAngleChanged(), notchChanged(), notchCountChanged(), notchLengthChanged(), notchSubTypeChanged(), notchTypeChanged(), notchWidthChanged(), qApp, resetNotchAngle(), resetNotchLength(), resetNotchWidth(), showNotchChanged(), showSeamlineNotchChanged(), and ui.
Referenced by PatternPieceDialog().
initializePropertiesTab()
void PatternPieceDialog::initializePropertiesTab () private
Definition at line 3021 of file pattern_piece_dialog.cpp.
References pieceColorChanged(), pieceNameChanged(), and ui.
Referenced by PatternPieceDialog().
initializeSAIncludeType()
void PatternPieceDialog::initializeSAIncludeType () private
Definition at line 3002 of file pattern_piece_dialog.cpp.
References AsCustomSA, AsMainPath, and ui.
Referenced by customSeamAllowanceChanged().
initializeSeamAllowanceTab()
void PatternPieceDialog::initializeSeamAllowanceTab () private
Definition at line 2889 of file pattern_piece_dialog.cpp.
References afterWidthChanged(), beforeWidthChanged(), customSAEndPointChanged(), customSAIncludeTypeChanged(), customSAStartPointChanged(), customSeamAllowanceChanged(), defaultWidthChanged(), editAfterSeamAllowanceWidth(), editBeforeSeamAllowanceWidth(), editDefaultSeamAllowanceWidth(), enableBuiltIn(), enableDefaultAfterButton(), enableDefaultBeforeButton(), enableSeamAllowance(), evaluateAfterWidth(), evaluateBeforeWidth(), evaluateDefaultWidth(), DialogTool::initializeNodeAngles(), initializeNodesList(), m_saWidth, m_timerWidth, m_timerWidthAfter, m_timerWidthBefore, nodeAngleChanged(), nodeChanged(), DialogTool::plainTextEditFormula, qApp, showCustomSAContextMenu(), StrToUnits(), ui, and UnitConvertor().
Referenced by PatternPieceDialog().
isInLayout()
bool PatternPieceDialog::isInLayout () const private
Definition at line 2581 of file pattern_piece_dialog.cpp.
References m_inLayout.
Referenced by CreatePiece().
isMainPathClockwise()
bool PatternPieceDialog::isMainPathClockwise () const private
Definition at line 2654 of file pattern_piece_dialog.cpp.
References CreatePiece(), DialogTool::data, VAbstractPiece::isClockwise(), and VPiece::MainPathPoints().
Referenced by isMainPathValid().
isMainPathValid()
bool PatternPieceDialog::isMainPathValid () const private
Definition at line 2605 of file pattern_piece_dialog.cpp.
References CreatePiece(), DialogTool::data, DialogTool::DialogWarningIcon(), DialogTool::doublePointsExist(), DialogTool::isEachPointNameUnique(), DialogTool::isFirstPointSameAsLast(), isMainPathClockwise(), and ui.
Referenced by ChosenObject(), PatternPieceDialog(), SetPiece(), and showMainPathContextMenu().
newAnchorPoint()
void PatternPieceDialog::newAnchorPoint (quint32 anchorPoint) private
Definition at line 2522 of file pattern_piece_dialog.cpp.
References DialogTool::data, VContainer::GetGObject(), NULL_ID, and ui.
Referenced by SetPiece().
newCustomSeamAllowance()
void PatternPieceDialog::newCustomSeamAllowance (const CustomSARecord & record) private
Definition at line 2494 of file pattern_piece_dialog.cpp.
References getPathName(), NULL_ID, CustomSARecord::path, CustomSARecord::reverse, and ui.
Referenced by SetPiece().
newInternalPath()
void PatternPieceDialog::newInternalPath (quint32 path) private
Definition at line 2508 of file pattern_piece_dialog.cpp.
References getPathName(), NULL_ID, and ui.
Referenced by SetPiece().
newMainPathItem()
void PatternPieceDialog::newMainPathItem (const VPieceNode & node) private
Definition at line 2488 of file pattern_piece_dialog.cpp.
References DialogTool::newNodeItem(), and ui.
Referenced by ChosenObject(), and SetPiece().
nodeAngleChanged
void PatternPieceDialog::nodeAngleChanged (int index) private slot
Definition at line 1323 of file pattern_piece_dialog.cpp.
References getItemById(), nodeListChanged(), VPieceNode::SetAngleType(), and ui.
Referenced by initializeSeamAllowanceTab().
nodeChanged
void PatternPieceDialog::nodeChanged (int index) private slot
Definition at line 1088 of file pattern_piece_dialog.cpp.
References VPiecePath::at(), CreatePiece(), currentSeamAllowance, anonymous_namespace{pattern_piece_dialog.cpp}::enableDefaultButton(), VPieceNode::GetAngleType(), VPieceNode::GetFormulaSAAfter(), VPieceNode::GetFormulaSABefore(), VPiece::GetPath(), VPiecePath::indexOfNode(), DialogTool::MoveCursorToEnd(), qApp, and ui.
Referenced by initializeNodesList(), and initializeSeamAllowanceTab().
nodeListChanged
void PatternPieceDialog::nodeListChanged () private slot
Definition at line 1045 of file pattern_piece_dialog.cpp.
References applyAllowed, CreatePiece(), customSeamAllowanceChanged(), initializeNodesList(), initializeNotchesList(), SCASSERT, setMoveExclusions(), ui, and DialogTool::vis.
Referenced by nodeAngleChanged(), notchAngleChanged(), notchCountChanged(), notchLengthChanged(), notchSubTypeChanged(), notchTypeChanged(), notchWidthChanged(), setCurrentAfterSeamAllowance(), setCurrentBeforeSeamAllowance(), SetPiece(), showMainPathContextMenu(), showNotchChanged(), and showSeamlineNotchChanged().
notchAngleChanged
void PatternPieceDialog::notchAngleChanged (qreal value) private slot
Definition at line 1624 of file pattern_piece_dialog.cpp.
References getItemById(), nodeListChanged(), VPieceNode::setNotchAngle(), and ui.
Referenced by initializeNotchesTab().
notchChanged
void PatternPieceDialog::notchChanged (int index) private slot
Definition at line 1151 of file pattern_piece_dialog.cpp.
References VPiecePath::at(), Bisector, Castle, CreatePiece(), Diamond, VPieceNode::getNotchAngle(), VPieceNode::getNotchCount(), VPieceNode::getNotchLength(), VPieceNode::getNotchSubType(), VPieceNode::getNotchType(), VPieceNode::getNotchWidth(), VPiece::GetPath(), VPiecePath::indexOfNode(), Intersection, VPieceNode::showNotch(), VPieceNode::showSeamlineNotch(), Slit, Straightforward, TNotch, ui, UNotch, VExternal, and VInternal.
Referenced by initializeNotchesList(), and initializeNotchesTab().
notchCountChanged
void PatternPieceDialog::notchCountChanged (int value) private slot
Definition at line 1647 of file pattern_piece_dialog.cpp.
References getItemById(), nodeListChanged(), VPieceNode::setNotchCount(), and ui.
Referenced by initializeNotchesTab().
notchLengthChanged
void PatternPieceDialog::notchLengthChanged (qreal value) private slot
Definition at line 1576 of file pattern_piece_dialog.cpp.
References getItemById(), nodeListChanged(), VPieceNode::setNotchLength(), and ui.
Referenced by initializeNotchesTab().
notchSubTypeChanged
void PatternPieceDialog::notchSubTypeChanged (int id) private slot
Definition at line 1506 of file pattern_piece_dialog.cpp.
References Bisector, getItemById(), Intersection, nodeListChanged(), VPieceNode::setNotchSubType(), Straightforward, and ui.
Referenced by initializeNotchesTab().
notchTypeChanged
void PatternPieceDialog::notchTypeChanged (int id) private slot
Definition at line 1449 of file pattern_piece_dialog.cpp.
References Castle, Diamond, getItemById(), DialogTool::getNodeInfo(), NodeInfo::icon, NodeInfo::name, nodeListChanged(), qApp, VPieceNode::setNotchType(), Slit, stringToNotchType(), TNotch, ui, UNotch, VExternal, and VInternal.
Referenced by initializeNotchesTab().
notchWidthChanged
void PatternPieceDialog::notchWidthChanged (qreal value) private slot
Definition at line 1600 of file pattern_piece_dialog.cpp.
References getItemById(), nodeListChanged(), VPieceNode::setNotchWidth(), and ui.
Referenced by initializeNotchesTab().
pageChanged()
void PatternPieceDialog::pageChanged (QListWidgetItem * current, QListWidgetItem * previous)
Definition at line 190 of file pattern_piece_dialog.cpp.
References AnchorPoints, Grainline, Labels, m_anchorPoints, showAnchorPoints(), and ui.
Referenced by PatternPieceDialog().
pathDialogClosed
void PatternPieceDialog::pathDialogClosed (int result) private slot
Definition at line 1420 of file pattern_piece_dialog.cpp.
References DialogTool::data, VException::DetailedInformation(), VExceptionBadId::ErrorMessage(), DialogInternalPath::GetPiecePath(), VContainer::GetPiecePath(), DialogTool::GetToolId(), m_dialog, qApp, SavePiecePathOptions, SCASSERT, updateCurrentCustomSARecord(), and updateCurrentInternalPathRecord().
Referenced by showCustomSAContextMenu(), and showInternalPathsContextMenu().
patternLabelAnchorChanged
void PatternPieceDialog::patternLabelAnchorChanged () private slot
Definition at line 2345 of file pattern_piece_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), clearErrorText(), DialogTool::errorColor, flagPatternLabelAnchor, flagPieceLabelAnchor, DialogTool::getCurrentObjectId(), Labels, NULL_ID, DialogTool::okColor, setErrorText(), ui, and updatePatternLabelValues().
Referenced by enabledPatternLabel(), and initializeLabelsTab().
pieceColorChanged
void PatternPieceDialog::pieceColorChanged () private slot
Definition at line 768 of file pattern_piece_dialog.cpp.
References CheckState(), and ui.
Referenced by initializePropertiesTab().
pieceLabelAnchorChanged
void PatternPieceDialog::pieceLabelAnchorChanged () private slot
Definition at line 2312 of file pattern_piece_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), clearErrorText(), DialogTool::errorColor, flagPatternLabelAnchor, flagPieceLabelAnchor, DialogTool::getCurrentObjectId(), Labels, NULL_ID, DialogTool::okColor, setErrorText(), ui, and updatePieceLabelValues().
Referenced by enabledPieceLabel(), and initializeLabelsTab().
pieceNameChanged
void PatternPieceDialog::pieceNameChanged () private slot
Definition at line 746 of file pattern_piece_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), clearErrorText(), DialogTool::flagName, DialogTool::okColor, Properties, setErrorText(), and ui.
Referenced by initializePropertiesTab().
pointNodesExist()
bool PatternPieceDialog::pointNodesExist () const private
Definition at line 2785 of file pattern_piece_dialog.cpp.
References VPieceNode::GetTypeTool(), VPieceNode::isExcluded(), NodePoint, and ui.
Referenced by initializeNodesList().
resetGrainlineWarning
void PatternPieceDialog::resetGrainlineWarning () private slot
Definition at line 2131 of file pattern_piece_dialog.cpp.
References clearErrorText(), flagGrainlineAnchor, flagGrainlineFormula, and Grainline.
Referenced by enabledGrainline(), grainlineAnchorChanged(), and updateGrainlineValues().
resetLabelsWarning
void PatternPieceDialog::resetLabelsWarning () private slot
Definition at line 2140 of file pattern_piece_dialog.cpp.
References clearErrorText(), flagPatternLabelAnchor, flagPatternLabelAngle, flagPatternLabelFormula, flagPieceLabelAnchor, flagPieceLabelAngle, flagPieceLabelFormula, Labels, and ui.
Referenced by enabledPatternLabel(), enabledPieceLabel(), updatePatternLabelValues(), and updatePieceLabelValues().
resetNotchAngle
void PatternPieceDialog::resetNotchAngle () private slot
Definition at line 1641 of file pattern_piece_dialog.cpp.
References ui.
Referenced by initializeNotchesTab().
resetNotchLength
void PatternPieceDialog::resetNotchLength () private slot
Definition at line 1594 of file pattern_piece_dialog.cpp.
References qApp, and ui.
Referenced by initializeNotchesTab().
resetNotchWidth
void PatternPieceDialog::resetNotchWidth () private slot
Definition at line 1618 of file pattern_piece_dialog.cpp.
References qApp, and ui.
Referenced by initializeNotchesTab().
resizeEvent()
void PatternPieceDialog::resizeEvent (QResizeEvent * event) protected virtual
Definition at line 734 of file pattern_piece_dialog.cpp.
References DialogTool::isInitialized, and qApp.
reverseNode()
void PatternPieceDialog::reverseNode (QListWidgetItem * rowItem) private
Definition at line 3482 of file pattern_piece_dialog.cpp.
References DialogTool::getNodeInfo(), VPieceNode::GetReverse(), VPieceNode::GetTypeTool(), NodeInfo::icon, NodeInfo::name, NodePoint, and VPieceNode::SetReverse().
Referenced by eventFilter(), and showMainPathContextMenu().
SaveData()
void PatternPieceDialog::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 521 of file pattern_piece_dialog.cpp.
setCurrentAfterSeamAllowance()
void PatternPieceDialog::setCurrentAfterSeamAllowance (const QString & formula) private
Definition at line 2809 of file pattern_piece_dialog.cpp.
References nodeListChanged(), and updateNodeAfterSeamAllowance().
Referenced by editAfterSeamAllowanceWidth().
setCurrentBeforeSeamAllowance()
void PatternPieceDialog::setCurrentBeforeSeamAllowance (const QString & formula) private
Definition at line 2802 of file pattern_piece_dialog.cpp.
References nodeListChanged(), and updateNodeBeforeSeamAllowance().
Referenced by editBeforeSeamAllowanceWidth().
setCurrentText()
void PatternPieceDialog::setCurrentText (QComboBox * box, const QString & text) const private
Definition at line 3551 of file pattern_piece_dialog.cpp.
References SCASSERT.
setErrorText
void PatternPieceDialog::setErrorText (TabOrder tab, QString text) private slot
Definition at line 569 of file pattern_piece_dialog.cpp.
References ui.
Referenced by CheckState(), patternLabelAnchorChanged(), pieceLabelAnchorChanged(), pieceNameChanged(), updateGrainlineValues(), updatePatternLabelValues(), and updatePieceLabelValues().
setGrainlineAngle()
void PatternPieceDialog::setGrainlineAngle (QString angleFormula) private
Definition at line 3290 of file pattern_piece_dialog.cpp.
References DialogTool::MoveCursorToEnd(), qApp, and ui.
Referenced by editGrainlineFormula(), and SetPiece().
setGrainlineLength()
void PatternPieceDialog::setGrainlineLength (QString lengthFormula) private
Definition at line 3304 of file pattern_piece_dialog.cpp.
References Cm, DialogTool::data, VContainer::GetPatternUnit(), DialogTool::MoveCursorToEnd(), qApp, ui, and UnitConvertor().
Referenced by editGrainlineFormula(), and SetPiece().
setInLayout()
void PatternPieceDialog::setInLayout (const bool & state) private
Definition at line 2587 of file pattern_piece_dialog.cpp.
References m_inLayout.
Referenced by SetPiece().
setMoveExclusions()
void PatternPieceDialog::setMoveExclusions () private
Definition at line 3426 of file pattern_piece_dialog.cpp.
References ui.
Referenced by initializeMainPathTab(), and nodeListChanged().
setNotch()
void PatternPieceDialog::setNotch (QListWidgetItem * rowItem, bool isNotch, NotchType notchType, NotchSubType notchSubType) private
Definition at line 3534 of file pattern_piece_dialog.cpp.
References DialogTool::getNodeInfo(), VPieceNode::GetTypeTool(), NodeInfo::icon, NodeInfo::name, NodePoint, VPieceNode::setNotch(), VPieceNode::setNotchSubType(), and VPieceNode::setNotchType().
Referenced by eventFilter(), and showMainPathContextMenu().
setPatternLabelAngle()
void PatternPieceDialog::setPatternLabelAngle (QString angleFormula) private
Definition at line 3388 of file pattern_piece_dialog.cpp.
References DialogTool::MoveCursorToEnd(), qApp, and ui.
Referenced by editPatternLabelFormula(), and SetPiece().
setPatternLabelHeight()
void PatternPieceDialog::setPatternLabelHeight (QString heightFormula) private
Definition at line 3374 of file pattern_piece_dialog.cpp.
References Cm, DialogTool::data, VContainer::GetPatternUnit(), DialogTool::MoveCursorToEnd(), qApp, ui, and UnitConvertor().
Referenced by editPatternLabelFormula(), and SetPiece().
setPatternLabelWidth()
void PatternPieceDialog::setPatternLabelWidth (QString widthFormula) private
Definition at line 3360 of file pattern_piece_dialog.cpp.
References Cm, DialogTool::data, VContainer::GetPatternUnit(), DialogTool::MoveCursorToEnd(), qApp, ui, and UnitConvertor().
Referenced by editPatternLabelFormula(), and SetPiece().
SetPiece()
void PatternPieceDialog::SetPiece (const VPiece & piece)
Definition at line 247 of file pattern_piece_dialog.cpp.
References VPiecePath::at(), VGrainlineData::bottomAnchorPoint(), VPatternLabelData::bottomRightAnchorPoint(), VGrainlineData::centerAnchorPoint(), VPatternLabelData::centerAnchorPoint(), DialogTool::ChangeCurrentData(), customSeamAllowanceChanged(), enabledGrainline(), enabledPatternLabel(), enabledPieceLabel(), VPiece::getAnchors(), VPieceLabelData::GetAnnotation(), VGrainlineData::GetArrowType(), VAbstractPiece::getColor(), VPiece::GetCustomSARecords(), VAbstractPiece::getFill(), VPieceLabelData::GetFoldPosition(), VPiece::GetGrainlineGeometry(), VPiece::GetInternalPaths(), VPatternLabelData::GetLabelHeight(), VPieceLabelData::GetLabelTemplate(), VPatternLabelData::GetLabelWidth(), VGrainlineData::GetLength(), VPieceLabelData::GetLetter(), VAbstractPiece::GetMx(), VAbstractPiece::GetMy(), VAbstractPiece::GetName(), VPieceLabelData::GetOrientation(), VPiece::GetPath(), VPiece::GetPatternInfo(), VPiece::GetPatternPieceData(), VPieceLabelData::GetQuantity(), VGrainlineData::GetRotation(), VPatternLabelData::GetRotation(), VPieceLabelData::GetRotationWay(), VAbstractPiece::GetSAWidth(), VPiece::getSeamAllowanceWidthFormula(), VPieceLabelData::GetTilt(), initAnchorPointComboboxes(), VAbstractPiece::IsForbidFlipping(), VAbstractPiece::isHideSeamLine(), VPiece::isInLayout(), VPiece::isLocked(), isMainPathValid(), VPieceLabelData::IsOnFold(), VAbstractPiece::IsSeamAllowance(), VAbstractPiece::IsSeamAllowanceBuiltIn(), VAbstractFloatItemData::IsVisible(), m_mx, m_my, m_oldData, m_oldGeom, m_oldGrainline, m_pieceLabelLines, m_saWidth, newAnchorPoint(), newCustomSeamAllowance(), newInternalPath(), newMainPathItem(), nodeListChanged(), qApp, setGrainlineAngle(), setGrainlineLength(), setInLayout(), setPatternLabelAngle(), setPatternLabelHeight(), setPatternLabelWidth(), setPieceColor(), setPieceFill(), setPieceLabelAngle(), setPieceLabelHeight(), setPieceLabelWidth(), setPieceLock(), VGrainlineData::topAnchorPoint(), VPatternLabelData::topLeftAnchorPoint(), ui, and validateObjects().
setPieceColor()
void PatternPieceDialog::setPieceColor (const QString & value) private
Definition at line 2561 of file pattern_piece_dialog.cpp.
References ui.
Referenced by SetPiece().
setPieceFill()
void PatternPieceDialog::setPieceFill (const QString & value) private
Definition at line 2575 of file pattern_piece_dialog.cpp.
References DialogTool::ChangeCurrentData(), and ui.
Referenced by SetPiece().
setPieceLabelAngle()
void PatternPieceDialog::setPieceLabelAngle (QString angleFormula) private
Definition at line 3346 of file pattern_piece_dialog.cpp.
References DialogTool::MoveCursorToEnd(), qApp, and ui.
Referenced by editPieceLabelFormula(), and SetPiece().
setPieceLabelHeight()
void PatternPieceDialog::setPieceLabelHeight (QString heightFormula) private
Definition at line 3332 of file pattern_piece_dialog.cpp.
References Cm, DialogTool::data, VContainer::GetPatternUnit(), DialogTool::MoveCursorToEnd(), qApp, ui, and UnitConvertor().
Referenced by editPieceLabelFormula(), and SetPiece().
setPieceLabelWidth()
void PatternPieceDialog::setPieceLabelWidth (QString widthFormula) private
Definition at line 3318 of file pattern_piece_dialog.cpp.
References Cm, DialogTool::data, VContainer::GetPatternUnit(), DialogTool::MoveCursorToEnd(), qApp, ui, and UnitConvertor().
Referenced by editPieceLabelFormula(), and SetPiece().
setPieceLock()
void PatternPieceDialog::setPieceLock (const bool & state) private
Definition at line 2599 of file pattern_piece_dialog.cpp.
References m_isLocked.
Referenced by SetPiece().
setSeamAllowanceWidthFormula()
void PatternPieceDialog::setSeamAllowanceWidthFormula (const QString & formula) private
Definition at line 3246 of file pattern_piece_dialog.cpp.
References CreatePiece(), DialogTool::MoveCursorToEnd(), qApp, SCASSERT, PatternPieceVisual::SetPiece(), ui, and DialogTool::vis.
Referenced by editDefaultSeamAllowanceWidth().
showAnchorPoints()
void PatternPieceDialog::showAnchorPoints () private
Definition at line 3402 of file pattern_piece_dialog.cpp.
References DialogTool::data, VAbstractPattern::getTool(), m_anchorPoints, NULL_ID, qApp, SCASSERT, DialogTool::toolId, and ui.
Referenced by pageChanged().
showAnchorsContextMenu
void PatternPieceDialog::showAnchorsContextMenu (const QPoint & pos) private slot
Definition at line 1024 of file pattern_piece_dialog.cpp.
References initAnchorPointComboboxes(), and ui.
Referenced by initializeAnchorsTab().
showCustomSAContextMenu
void PatternPieceDialog::showCustomSAContextMenu (const QPoint & pos) private slot
Definition at line 936 of file pattern_piece_dialog.cpp.
References AsMainPath, DialogTool::data, DialogTool::DialogClosed(), getPathName(), VContainer::GetPiecePath(), getSeamAllowanceWidthFormula(), CustomSARecord::includeType, m_dialog, CustomSARecord::path, pathDialogClosed(), CustomSARecord::reverse, SCASSERT, DialogTool::toolId, and ui.
Referenced by initializeSeamAllowanceTab().
ShowDialog
void PatternPieceDialog::ShowDialog (bool click) virtual slot
Definition at line 499 of file pattern_piece_dialog.cpp.
References applyAllowed, DialogTool::prepare, SCASSERT, Show, DialogTool::ToolTip(), and DialogTool::vis.
showEvent()
void PatternPieceDialog::showEvent (QShowEvent * event) protected virtual
showEvent handle when window show
Parameters
event event
Reimplemented from DialogTool.
Definition at line 716 of file pattern_piece_dialog.cpp.
References DialogTool::isInitialized, and qApp.
showInternalPathsContextMenu
void PatternPieceDialog::showInternalPathsContextMenu (const QPoint & pos) private slot
Definition at line 987 of file pattern_piece_dialog.cpp.
References DialogTool::data, DialogTool::DialogClosed(), VContainer::GetPiecePath(), m_dialog, pathDialogClosed(), SCASSERT, DialogTool::toolId, and ui.
Referenced by initializeInternalPathsTab().
showMainPathContextMenu
void PatternPieceDialog::showMainPathContextMenu (const QPoint & pos) private slot
Definition at line 781 of file pattern_piece_dialog.cpp.
References Bisector, Castle, Diamond, duplicateNode(), excludeNode(), VPieceNode::GetReverse(), VPieceNode::GetTypeTool(), Intersection, VPieceNode::isExcluded(), isMainPathValid(), VPieceNode::isNotch(), nodeListChanged(), NodePoint, reverseNode(), SCASSERT, setNotch(), Slit, Straightforward, TNotch, ui, UNotch, validateObjects(), VExternal, and VInternal.
Referenced by initializeMainPathTab().
showNotchChanged
void PatternPieceDialog::showNotchChanged (int state) private slot
Definition at line 1539 of file pattern_piece_dialog.cpp.
References getItemById(), nodeListChanged(), VPieceNode::setShowNotch(), and ui.
Referenced by initializeNotchesTab().
showSeamlineNotchChanged
void PatternPieceDialog::showSeamlineNotchChanged (int state) private slot
Definition at line 1557 of file pattern_piece_dialog.cpp.
References getItemById(), nodeListChanged(), VPieceNode::setShowSeamlineNotch(), and ui.
Referenced by initializeNotchesTab().
updateCurrentCustomSARecord()
void PatternPieceDialog::updateCurrentCustomSARecord () private
Definition at line 3260 of file pattern_piece_dialog.cpp.
References getPathName(), CustomSARecord::path, CustomSARecord::reverse, SCASSERT, and ui.
Referenced by pathDialogClosed().
updateCurrentInternalPathRecord()
void PatternPieceDialog::updateCurrentInternalPathRecord () private
Definition at line 3275 of file pattern_piece_dialog.cpp.
References getPathName(), SCASSERT, and ui.
Referenced by pathDialogClosed().
updateGrainlineValues
void PatternPieceDialog::updateGrainlineValues () private slot
Definition at line 1665 of file pattern_piece_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::data, VContainer::DataVariables(), degreeSymbol, Calculator::EvalFormula(), flagGrainlineAnchor, flagGrainlineFormula, qmu::QmuParserError::GetMsg(), Grainline, DialogTool::okColor, qApp, resetGrainlineWarning(), setErrorText(), ui, and UnitsToStr().
Referenced by editGrainlineFormula(), enabledGrainline(), grainlineAnchorChanged(), and initializeGrainlineTab().
updateNodeAfterSeamAllowance()
void PatternPieceDialog::updateNodeAfterSeamAllowance (const QString & formula) private
Definition at line 2832 of file pattern_piece_dialog.cpp.
References getItemById(), VPieceNode::setAfterSAFormula(), and ui.
Referenced by evaluateAfterWidth(), and setCurrentAfterSeamAllowance().
updateNodeBeforeSeamAllowance()
void PatternPieceDialog::updateNodeBeforeSeamAllowance (const QString & formula) private
Definition at line 2816 of file pattern_piece_dialog.cpp.
References getItemById(), VPieceNode::setBeforeSAFormula(), and ui.
Referenced by evaluateBeforeWidth(), and setCurrentBeforeSeamAllowance().
updatePatternLabelValues
void PatternPieceDialog::updatePatternLabelValues () private slot
Definition at line 1825 of file pattern_piece_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::data, VContainer::DataVariables(), degreeSymbol, Calculator::EvalFormula(), flagPatternLabelAnchor, flagPatternLabelAngle, flagPatternLabelFormula, qmu::QmuParserError::GetMsg(), Labels, DialogTool::okColor, qApp, resetLabelsWarning(), setErrorText(), ui, and UnitsToStr().
Referenced by editPatternLabelFormula(), enabledPatternLabel(), initializeLabelsTab(), and patternLabelAnchorChanged().
updatePieceLabelValues
void PatternPieceDialog::updatePieceLabelValues () private slot
Definition at line 1740 of file pattern_piece_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::data, VContainer::DataVariables(), degreeSymbol, Calculator::EvalFormula(), flagPieceLabelAnchor, flagPieceLabelAngle, flagPieceLabelFormula, qmu::QmuParserError::GetMsg(), Labels, DialogTool::okColor, qApp, resetLabelsWarning(), setErrorText(), ui, and UnitsToStr().
Referenced by editPieceLabelFormula(), enabledPieceLabel(), initializeLabelsTab(), and pieceLabelAnchorChanged().
validateObjects()
void PatternPieceDialog::validateObjects (bool value) private
Definition at line 2647 of file pattern_piece_dialog.cpp.
References CheckState(), and flagMainPath.
Referenced by ChosenObject(), SetPiece(), and showMainPathContextMenu().
Member Data Documentation
applyAllowed
bool PatternPieceDialog::applyAllowed private
Definition at line 184 of file pattern_piece_dialog.h.
Referenced by CheckState(), ChosenObject(), CreatePiece(), enableApply(), nodeListChanged(), PatternPieceDialog(), and ShowDialog().
flagAfterFormula
bool PatternPieceDialog::flagAfterFormula private
Definition at line 194 of file pattern_piece_dialog.h.
Referenced by afterWidthChanged(), CheckState(), and evaluateAfterWidth().
flagBeforeFormula
bool PatternPieceDialog::flagBeforeFormula private
Definition at line 193 of file pattern_piece_dialog.h.
Referenced by beforeWidthChanged(), CheckState(), and evaluateBeforeWidth().
flagGrainlineAnchor
bool PatternPieceDialog::flagGrainlineAnchor private
Definition at line 185 of file pattern_piece_dialog.h.
Referenced by CheckState(), grainlineAnchorChanged(), resetGrainlineWarning(), and updateGrainlineValues().
flagGrainlineFormula
bool PatternPieceDialog::flagGrainlineFormula private
Definition at line 188 of file pattern_piece_dialog.h.
Referenced by CheckState(), enabledGrainline(), grainlineAnchorChanged(), resetGrainlineWarning(), and updateGrainlineValues().
flagMainPath
bool PatternPieceDialog::flagMainPath private
Definition at line 195 of file pattern_piece_dialog.h.
Referenced by CheckState(), PatternPieceDialog(), and validateObjects().
flagPatternLabelAnchor
bool PatternPieceDialog::flagPatternLabelAnchor private
Definition at line 187 of file pattern_piece_dialog.h.
Referenced by CheckState(), patternLabelAnchorChanged(), pieceLabelAnchorChanged(), resetLabelsWarning(), and updatePatternLabelValues().
flagPatternLabelAngle
bool PatternPieceDialog::flagPatternLabelAngle private
Definition at line 191 of file pattern_piece_dialog.h.
Referenced by CheckState(), enabledPatternLabel(), resetLabelsWarning(), and updatePatternLabelValues().
flagPatternLabelFormula
bool PatternPieceDialog::flagPatternLabelFormula private
Definition at line 192 of file pattern_piece_dialog.h.
Referenced by CheckState(), enabledPatternLabel(), resetLabelsWarning(), and updatePatternLabelValues().
flagPieceLabelAnchor
bool PatternPieceDialog::flagPieceLabelAnchor private
Definition at line 186 of file pattern_piece_dialog.h.
Referenced by CheckState(), patternLabelAnchorChanged(), pieceLabelAnchorChanged(), resetLabelsWarning(), and updatePieceLabelValues().
flagPieceLabelAngle
bool PatternPieceDialog::flagPieceLabelAngle private
Definition at line 189 of file pattern_piece_dialog.h.
Referenced by CheckState(), enabledPieceLabel(), resetLabelsWarning(), and updatePieceLabelValues().
flagPieceLabelFormula
bool PatternPieceDialog::flagPieceLabelFormula private
Definition at line 190 of file pattern_piece_dialog.h.
Referenced by CheckState(), enabledPieceLabel(), resetLabelsWarning(), and updatePieceLabelValues().
m_anchorPoints
QPointer<PieceAnchorPointVisual> PatternPieceDialog::m_anchorPoints private
Definition at line 203 of file pattern_piece_dialog.h.
Referenced by pageChanged(), showAnchorPoints(), and ~PatternPieceDialog().
m_bAddMode
bool PatternPieceDialog::m_bAddMode private
Definition at line 196 of file pattern_piece_dialog.h.
m_beep
QSound* PatternPieceDialog::m_beep private
Definition at line 214 of file pattern_piece_dialog.h.
Referenced by ChosenObject().
m_dialog
QPointer<DialogTool> PatternPieceDialog::m_dialog private
Definition at line 202 of file pattern_piece_dialog.h.
Referenced by pathDialogClosed(), showCustomSAContextMenu(), and showInternalPathsContextMenu().
m_inLayout
bool PatternPieceDialog::m_inLayout private
Definition at line 199 of file pattern_piece_dialog.h.
Referenced by isInLayout(), and setInLayout().
m_isLocked
bool PatternPieceDialog::m_isLocked private
Definition at line 200 of file pattern_piece_dialog.h.
Referenced by getPieceLock(), and setPieceLock().
m_mx
qreal PatternPieceDialog::m_mx private
Definition at line 197 of file pattern_piece_dialog.h.
Referenced by CreatePiece(), and SetPiece().
m_my
qreal PatternPieceDialog::m_my private
Definition at line 198 of file pattern_piece_dialog.h.
Referenced by CreatePiece(), and SetPiece().
m_oldData
VPieceLabelData PatternPieceDialog::m_oldData private
Definition at line 205 of file pattern_piece_dialog.h.
Referenced by CreatePiece(), and SetPiece().
m_oldGeom
VPatternLabelData PatternPieceDialog::m_oldGeom private
Definition at line 206 of file pattern_piece_dialog.h.
Referenced by CreatePiece(), and SetPiece().
m_oldGrainline
VGrainlineData PatternPieceDialog::m_oldGrainline private
Definition at line 207 of file pattern_piece_dialog.h.
Referenced by CreatePiece(), and SetPiece().
m_patternLabelLines
QVector<VLabelTemplateLine> PatternPieceDialog::m_patternLabelLines private
Definition at line 212 of file pattern_piece_dialog.h.
Referenced by initializeLabelsTab().
m_pieceLabelLines
QVector<VLabelTemplateLine> PatternPieceDialog::m_pieceLabelLines private
Definition at line 213 of file pattern_piece_dialog.h.
Referenced by CreatePiece(), editPieceLabel(), initializeLabelsTab(), and SetPiece().
m_saWidth
qreal PatternPieceDialog::m_saWidth private
Definition at line 211 of file pattern_piece_dialog.h.
Referenced by CreatePiece(), evaluateDefaultWidth(), initializeSeamAllowanceTab(), and SetPiece().
m_timerWidth
QTimer* PatternPieceDialog::m_timerWidth private
Definition at line 208 of file pattern_piece_dialog.h.
Referenced by defaultWidthChanged(), and initializeSeamAllowanceTab().
m_timerWidthAfter
QTimer* PatternPieceDialog::m_timerWidthAfter private
Definition at line 210 of file pattern_piece_dialog.h.
Referenced by afterWidthChanged(), and initializeSeamAllowanceTab().
m_timerWidthBefore
QTimer* PatternPieceDialog::m_timerWidthBefore private
Definition at line 209 of file pattern_piece_dialog.h.
Referenced by beforeWidthChanged(), and initializeSeamAllowanceTab().
ui
Ui::PatternPieceDialog* PatternPieceDialog::ui private
Definition at line 183 of file pattern_piece_dialog.h.
Referenced by afterWidthChanged(), beforeWidthChanged(), CheckState(), ChosenObject(), clearErrorText(), closeEvent(), CreatePiece(), customSAEndPointChanged(), customSAIncludeTypeChanged(), customSAStartPointChanged(), customSeamAllowanceChanged(), defaultWidthChanged(), duplicateNode(), editAfterSeamAllowanceWidth(), editBeforeSeamAllowanceWidth(), editGrainlineFormula(), editPatternLabelFormula(), editPieceLabelFormula(), enableApply(), enableBuiltIn(), enableDefaultAfterButton(), enableDefaultBeforeButton(), enabledGrainline(), enabledPatternLabel(), enabledPieceLabel(), enableSeamAllowance(), evaluateAfterWidth(), evaluateBeforeWidth(), evaluateDefaultWidth(), eventFilter(), getItemById(), getLastNode(), getPieceColor(), getPieceFill(), getPreviousId(), getSeamAllowanceWidthFormula(), grainlineAnchorChanged(), initAnchorPoint(), initAnchorPointComboboxes(), initializeAnchorsTab(), initializeCSAPoint(), initializeGrainlineTab(), initializeInternalPathsTab(), initializeLabelsTab(), initializeMainPathTab(), initializeNodesList(), initializeNotchesList(), initializeNotchesTab(), initializePropertiesTab(), initializeSAIncludeType(), initializeSeamAllowanceTab(), isMainPathValid(), newAnchorPoint(), newCustomSeamAllowance(), newInternalPath(), newMainPathItem(), nodeAngleChanged(), nodeChanged(), nodeListChanged(), notchAngleChanged(), notchChanged(), notchCountChanged(), notchLengthChanged(), notchSubTypeChanged(), notchTypeChanged(), notchWidthChanged(), pageChanged(), patternLabelAnchorChanged(), PatternPieceDialog(), pieceColorChanged(), pieceLabelAnchorChanged(), pieceNameChanged(), pointNodesExist(), resetLabelsWarning(), resetNotchAngle(), resetNotchLength(), resetNotchWidth(), setErrorText(), setGrainlineAngle(), setGrainlineLength(), setMoveExclusions(), setPatternLabelAngle(), setPatternLabelHeight(), setPatternLabelWidth(), SetPiece(), setPieceColor(), setPieceFill(), setPieceLabelAngle(), setPieceLabelHeight(), setPieceLabelWidth(), setSeamAllowanceWidthFormula(), showAnchorPoints(), showAnchorsContextMenu(), showCustomSAContextMenu(), showInternalPathsContextMenu(), showMainPathContextMenu(), showNotchChanged(), showSeamlineNotchChanged(), updateCurrentCustomSARecord(), updateCurrentInternalPathRecord(), updateGrainlineValues(), updateNodeAfterSeamAllowance(), updateNodeBeforeSeamAllowance(), updatePatternLabelValues(), updatePieceLabelValues(), and ~PatternPieceDialog().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/piece/pattern_piece_dialog.h
src/libs/vtools/dialogs/tools/piece/pattern_piece_dialog.cpp