Seamly2D: VSplinePoint Class Reference
VSplinePoint Class Reference
The VSplinePoint class keep information about point in spline path. Each point have two angles and two lengths. Point represent at the same time first and last point of a spline.
#include <vsplinepoint.h>
Public Member Functions
VSplinePoint ()
VSplinePoint (const VPointF &pSpline, qreal angle1, const QString &angle1F, qreal angle2, const QString &angle2F, qreal length1, const QString &length1F, qreal length2, const QString &length2F)
VSplinePoint (const VSplinePoint &point)
~VSplinePoint ()
VSplinePoint & operator= (const VSplinePoint &point)
void Swap (VSplinePoint &point) Q_DECL_NOTHROW
VPointF P () const
void SetP (const VPointF &value)
qreal Angle1 () const
QString Angle1Formula () const
void SetAngle1 (const qreal &value, const QString &angle1F)
qreal Angle2 () const
QString Angle2Formula () const
void SetAngle2 (const qreal &value, const QString &angle2F)
qreal Length1 () const
QString Length1Formula () const
void SetLength1 (const qreal &value, const QString &length1F)
qreal Length2 () const
QString Length2Formula () const
void SetLength2 (const qreal &value, const QString &length2F)
bool IsMovable () const
Protected Attributes
QSharedDataPointer< VSplinePointData > d
Detailed Description
The VSplinePoint class keep information about point in spline path. Each point have two angles and two lengths. Point represent at the same time first and last point of a spline.
Definition at line 107 of file vsplinepoint.h.
Constructor & Destructor Documentation
VSplinePoint() [1/3]
VSplinePoint::VSplinePoint ()
Definition at line 231 of file vsplinepoint.cpp.
VSplinePoint() [2/3]
VSplinePoint::VSplinePoint (const VPointF & pSpline, qreal angle1, const QString & angle1F, qreal angle2, const QString & angle2F, qreal length1, const QString & length1F, qreal length2, const QString & length2F)
Definition at line 237 of file vsplinepoint.cpp.
VSplinePoint() [3/3]
VSplinePoint::VSplinePoint (const VSplinePoint & point)
Definition at line 245 of file vsplinepoint.cpp.
~VSplinePoint()
VSplinePoint::~VSplinePoint ()
Definition at line 262 of file vsplinepoint.cpp.
Member Function Documentation
Angle1()
qreal VSplinePoint::Angle1 () const
Definition at line 279 of file vsplinepoint.cpp.
References d.
Referenced by VSplinePath::GetFSplinePath(), and VSplinePath::GetSpline().
Angle1Formula()
QString VSplinePoint::Angle1Formula () const
Definition at line 285 of file vsplinepoint.cpp.
References d.
Referenced by VToolSplinePath::AddPathPoint(), DialogSplinePath::Angle2Changed(), DialogSplinePath::DataPoint(), VSplinePath::GetFSplinePath(), and VSplinePath::GetSpline().
Angle2()
qreal VSplinePoint::Angle2 () const
Definition at line 305 of file vsplinepoint.cpp.
References d.
Referenced by VSplinePath::GetFSplinePath(), and VSplinePath::GetSpline().
Angle2Formula()
QString VSplinePoint::Angle2Formula () const
Definition at line 311 of file vsplinepoint.cpp.
References d.
Referenced by VToolSplinePath::AddPathPoint(), DialogSplinePath::Angle1Changed(), DialogSplinePath::DataPoint(), VSplinePath::GetFSplinePath(), and VSplinePath::GetSpline().
IsMovable()
bool VSplinePoint::IsMovable () const
Definition at line 369 of file vsplinepoint.cpp.
References d, and qmu::QmuTokenParser::IsSingle().
Referenced by VToolSplinePath::IsMovable().
Length1()
qreal VSplinePoint::Length1 () const
Definition at line 331 of file vsplinepoint.cpp.
References d.
Referenced by VToolCutSplinePath::CutSplinePath(), VSplinePath::GetFSplinePath(), and VSplinePath::GetSpline().
Length1Formula()
QString VSplinePoint::Length1Formula () const
Definition at line 337 of file vsplinepoint.cpp.
References d.
Referenced by VToolSplinePath::AddPathPoint(), VToolCutSplinePath::CutSplinePath(), DialogSplinePath::DataPoint(), VSplinePath::GetFSplinePath(), and VSplinePath::GetSpline().
Length2()
qreal VSplinePoint::Length2 () const
Definition at line 350 of file vsplinepoint.cpp.
References d.
Referenced by VToolCutSplinePath::CutSplinePath(), VSplinePath::GetFSplinePath(), and VSplinePath::GetSpline().
Length2Formula()
QString VSplinePoint::Length2Formula () const
Definition at line 356 of file vsplinepoint.cpp.
References d.
Referenced by VToolSplinePath::AddPathPoint(), VToolCutSplinePath::CutSplinePath(), DialogSplinePath::DataPoint(), VSplinePath::GetFSplinePath(), and VSplinePath::GetSpline().
operator=()
VSplinePoint & VSplinePoint::operator= (const VSplinePoint & point)
Definition at line 251 of file vsplinepoint.cpp.
References d.
P()
VPointF VSplinePoint::P () const
Definition at line 267 of file vsplinepoint.cpp.
References d.
Referenced by VToolSplinePath::AddPathPoint(), VSplinePath::append(), DialogSplinePath::currentPointChanged(), VToolCutSplinePath::CutSplinePath(), DialogSplinePath::DataPoint(), DialogSplinePath::EvalAngle1(), DialogSplinePath::EvalAngle2(), DialogSplinePath::EvalLength1(), DialogSplinePath::EvalLength2(), VSplinePath::GetFSplinePath(), VSplinePath::GetSpline(), and DialogSplinePath::NewItem().
SetAngle1()
void VSplinePoint::SetAngle1 (const qreal & value, const QString & angle1F)
Definition at line 291 of file vsplinepoint.cpp.
References d.
Referenced by DialogSplinePath::Angle1Changed(), VCubicBezierPath::GetSplinePath(), and VToolSplinePath::UpdateControlPoints().
SetAngle2()
void VSplinePoint::SetAngle2 (const qreal & value, const QString & angle2F)
Definition at line 317 of file vsplinepoint.cpp.
References d.
Referenced by DialogSplinePath::Angle2Changed(), VCubicBezierPath::GetSplinePath(), and VToolSplinePath::UpdateControlPoints().
SetLength1()
void VSplinePoint::SetLength1 (const qreal & value, const QString & length1F)
Definition at line 343 of file vsplinepoint.cpp.
References d.
Referenced by VCubicBezierPath::GetSplinePath(), DialogSplinePath::Length1Changed(), and VToolSplinePath::UpdateControlPoints().
SetLength2()
void VSplinePoint::SetLength2 (const qreal & value, const QString & length2F)
Definition at line 362 of file vsplinepoint.cpp.
References d.
Referenced by VCubicBezierPath::GetSplinePath(), DialogSplinePath::Length2Changed(), and VToolSplinePath::UpdateControlPoints().
SetP()
void VSplinePoint::SetP (const VPointF & value)
Definition at line 273 of file vsplinepoint.cpp.
References d.
Referenced by DialogSplinePath::ChosenObject(), DialogSplinePath::currentPointChanged(), and VCubicBezierPath::GetSplinePath().
Swap()
void VSplinePoint::Swap (VSplinePoint & point)
Definition at line 228 of file vsplinepoint.cpp.
Member Data Documentation
d
QSharedDataPointer<VSplinePointData> VSplinePoint::d protected
Definition at line 144 of file vsplinepoint.h.
Referenced by Angle1(), Angle1Formula(), Angle2(), Angle2Formula(), IsMovable(), Length1(), Length1Formula(), Length2(), Length2Formula(), operator=(), P(), SetAngle1(), SetAngle2(), SetLength1(), SetLength2(), and SetP().
The documentation for this class was generated from the following files:
src/libs/vgeometry/vsplinepoint.h
src/libs/vgeometry/vsplinepoint.cpp