Seamly2D: IntersectCirclesDialog Class Reference
IntersectCirclesDialog Class Reference
#include <intersect_circles_dialog.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
void PointChanged ()
void Circle1RadiusChanged ()
void Circle2RadiusChanged ()
void FXCircle1Radius ()
void FXCircle2Radius ()
void EvalCircle1Radius ()
void EvalCircle2Radius ()
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
IntersectCirclesDialog (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
virtual ~IntersectCirclesDialog () Q_DECL_OVERRIDE
void SetPointName (const QString &value)
quint32 GetFirstCircleCenterId () const
void SetFirstCircleCenterId (const quint32 &value)
quint32 GetSecondCircleCenterId () const
void SetSecondCircleCenterId (const quint32 &value)
QString GetFirstCircleRadius () const
void SetFirstCircleRadius (const QString &value)
QString GetSecondCircleRadius () const
void SetSecondCircleRadius (const QString &value)
CrossCirclesPoint GetCrossCirclesPoint () const
void setCirclesCrossPoint (const CrossCirclesPoint &p)
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
virtual void CheckState () Q_DECL_FINAL
CheckState enable, when all is correct, or disable, when something wrong, button ok.
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Attributes
Ui::IntersectCirclesDialog * ui
bool flagCircle1Radius
bool flagCircle2Radius
QTimer * timerCircle1Radius
QTimer * timerCircle2Radius
QString circle1Radius
QString circle2Radius
int formulaBaseHeightCircle1Radius
int formulaBaseHeightCircle2Radius
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
Definition at line 50 of file intersect_circles_dialog.h.
Constructor & Destructor Documentation
IntersectCirclesDialog()
IntersectCirclesDialog::IntersectCirclesDialog (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
Definition at line 57 of file intersect_circles_dialog.cpp.
References CheckState(), Circle1RadiusChanged(), Circle2RadiusChanged(), DialogTool::data, EvalCircle1Radius(), EvalCircle2Radius(), DialogTool::FillComboBoxCrossCirclesPoints(), DialogTool::FillComboBoxPoints(), formulaBaseHeightCircle1Radius, formulaBaseHeightCircle2Radius, FXCircle1Radius(), FXCircle2Radius(), DialogTool::initializeOkCancelApply(), DialogTool::labelEditNamePoint, DialogTool::NamePointChanged(), NewLabel, DialogTool::plainTextEditFormula, PointChanged(), qApp, timerCircle1Radius, timerCircle2Radius, ui, and DialogTool::vis.
~IntersectCirclesDialog()
IntersectCirclesDialog::~IntersectCirclesDialog () virtual
Definition at line 123 of file intersect_circles_dialog.cpp.
References ui.
Member Function Documentation
CheckState()
void IntersectCirclesDialog::CheckState () protected virtual
CheckState enable, when all is correct, or disable, when something wrong, button ok.
Reimplemented from DialogTool.
Definition at line 407 of file intersect_circles_dialog.cpp.
References DialogTool::apply_Button, flagCircle1Radius, flagCircle2Radius, DialogTool::flagError, DialogTool::flagFormula, DialogTool::flagName, DialogTool::ok_Button, and SCASSERT.
Referenced by EvalCircle1Radius(), EvalCircle2Radius(), IntersectCirclesDialog(), and PointChanged().
ChosenObject
void IntersectCirclesDialog::ChosenObject (quint32 id, const SceneObject & type) virtual slot
Definition at line 228 of file intersect_circles_dialog.cpp.
References DialogTool::getCurrentObjectId(), DialogTool::number, Point, DialogTool::prepare, IntersectCirclesVisual::RefreshGeometry(), SCASSERT, DialogTool::SetObject(), IntersectCirclesVisual::setObject2Id(), ui, DialogTool::vis, and IntersectCirclesVisual::VisualMode().
Circle1RadiusChanged
void IntersectCirclesDialog::Circle1RadiusChanged () slot
Definition at line 287 of file intersect_circles_dialog.cpp.
References flagCircle1Radius, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, qApp, timerCircle1Radius, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by IntersectCirclesDialog().
Circle2RadiusChanged
void IntersectCirclesDialog::Circle2RadiusChanged () slot
Definition at line 296 of file intersect_circles_dialog.cpp.
References flagCircle2Radius, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, qApp, timerCircle2Radius, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by IntersectCirclesDialog().
closeEvent()
void IntersectCirclesDialog::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 399 of file intersect_circles_dialog.cpp.
References DialogTool::closeEvent(), and ui.
EvalCircle1Radius
void IntersectCirclesDialog::EvalCircle1Radius () slot
Definition at line 333 of file intersect_circles_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::Eval(), flagCircle1Radius, flagCircle2Radius, DialogTool::labelEditFormula, qApp, ui, and UnitsToStr().
Referenced by IntersectCirclesDialog().
EvalCircle2Radius
void IntersectCirclesDialog::EvalCircle2Radius () slot
Definition at line 352 of file intersect_circles_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::Eval(), flagCircle2Radius, DialogTool::labelEditFormula, qApp, ui, and UnitsToStr().
Referenced by IntersectCirclesDialog().
FXCircle1Radius
void IntersectCirclesDialog::FXCircle1Radius () slot
Definition at line 305 of file intersect_circles_dialog.cpp.
References DialogTool::data, GetFirstCircleRadius(), EditFormulaDialog::GetFormula(), qApp, SetFirstCircleRadius(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), DialogTool::toolId, and UnitsToStr().
Referenced by IntersectCirclesDialog().
FXCircle2Radius
void IntersectCirclesDialog::FXCircle2Radius () slot
Definition at line 319 of file intersect_circles_dialog.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), GetSecondCircleRadius(), qApp, EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), SetSecondCircleRadius(), DialogTool::toolId, and UnitsToStr().
Referenced by IntersectCirclesDialog().
GetCrossCirclesPoint()
CrossCirclesPoint IntersectCirclesDialog::GetCrossCirclesPoint () const
Definition at line 208 of file intersect_circles_dialog.cpp.
References ui.
Referenced by SaveData().
GetFirstCircleCenterId()
quint32 IntersectCirclesDialog::GetFirstCircleCenterId () const
Definition at line 136 of file intersect_circles_dialog.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
GetFirstCircleRadius()
QString IntersectCirclesDialog::GetFirstCircleRadius () const
Definition at line 168 of file intersect_circles_dialog.cpp.
References qApp, and ui.
Referenced by FXCircle1Radius().
GetSecondCircleCenterId()
quint32 IntersectCirclesDialog::GetSecondCircleCenterId () const
Definition at line 152 of file intersect_circles_dialog.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
GetSecondCircleRadius()
QString IntersectCirclesDialog::GetSecondCircleRadius () const
Definition at line 188 of file intersect_circles_dialog.cpp.
References qApp, and ui.
Referenced by FXCircle2Radius().
PointChanged
void IntersectCirclesDialog::PointChanged () slot
Definition at line 268 of file intersect_circles_dialog.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::errorColor, DialogTool::flagError, DialogTool::getCurrentObjectId(), DialogTool::okColor, and ui.
Referenced by IntersectCirclesDialog().
SaveData()
void IntersectCirclesDialog::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 377 of file intersect_circles_dialog.cpp.
References GetCrossCirclesPoint(), GetFirstCircleCenterId(), GetSecondCircleCenterId(), DialogTool::pointName, IntersectCirclesVisual::RefreshGeometry(), SCASSERT, IntersectCirclesVisual::setC1Radius(), IntersectCirclesVisual::setC2Radius(), IntersectCirclesVisual::setCrossPoint(), Visualization::setObject1Id(), IntersectCirclesVisual::setObject2Id(), ui, and DialogTool::vis.
setCirclesCrossPoint()
void IntersectCirclesDialog::setCirclesCrossPoint (const CrossCirclesPoint & p)
Definition at line 214 of file intersect_circles_dialog.cpp.
References SCASSERT, IntersectCirclesVisual::setCrossPoint(), ui, and DialogTool::vis.
SetFirstCircleCenterId()
void IntersectCirclesDialog::SetFirstCircleCenterId (const quint32 & value)
Definition at line 142 of file intersect_circles_dialog.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), Visualization::setObject1Id(), ui, and DialogTool::vis.
SetFirstCircleRadius()
void IntersectCirclesDialog::SetFirstCircleRadius (const QString & value)
Definition at line 175 of file intersect_circles_dialog.cpp.
References DialogTool::MoveCursorToEnd(), qApp, SCASSERT, IntersectCirclesVisual::setC1Radius(), ui, and DialogTool::vis.
Referenced by FXCircle1Radius().
SetPointName()
void IntersectCirclesDialog::SetPointName (const QString & value)
Definition at line 129 of file intersect_circles_dialog.cpp.
References DialogTool::pointName, and ui.
SetSecondCircleCenterId()
void IntersectCirclesDialog::SetSecondCircleCenterId (const quint32 & value)
Definition at line 158 of file intersect_circles_dialog.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), IntersectCirclesVisual::setObject2Id(), ui, and DialogTool::vis.
SetSecondCircleRadius()
void IntersectCirclesDialog::SetSecondCircleRadius (const QString & value)
Definition at line 195 of file intersect_circles_dialog.cpp.
References DialogTool::MoveCursorToEnd(), qApp, SCASSERT, IntersectCirclesVisual::setC2Radius(), ui, and DialogTool::vis.
Referenced by FXCircle2Radius().
ShowVisualization()
void IntersectCirclesDialog::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 371 of file intersect_circles_dialog.cpp.
Member Data Documentation
circle1Radius
QString IntersectCirclesDialog::circle1Radius private
Definition at line 108 of file intersect_circles_dialog.h.
circle2Radius
QString IntersectCirclesDialog::circle2Radius private
Definition at line 109 of file intersect_circles_dialog.h.
flagCircle1Radius
bool IntersectCirclesDialog::flagCircle1Radius private
Definition at line 102 of file intersect_circles_dialog.h.
Referenced by CheckState(), Circle1RadiusChanged(), and EvalCircle1Radius().
flagCircle2Radius
bool IntersectCirclesDialog::flagCircle2Radius private
Definition at line 103 of file intersect_circles_dialog.h.
Referenced by CheckState(), Circle2RadiusChanged(), EvalCircle1Radius(), and EvalCircle2Radius().
formulaBaseHeightCircle1Radius
int IntersectCirclesDialog::formulaBaseHeightCircle1Radius private
Definition at line 111 of file intersect_circles_dialog.h.
Referenced by IntersectCirclesDialog().
formulaBaseHeightCircle2Radius
int IntersectCirclesDialog::formulaBaseHeightCircle2Radius private
Definition at line 112 of file intersect_circles_dialog.h.
Referenced by IntersectCirclesDialog().
timerCircle1Radius
QTimer* IntersectCirclesDialog::timerCircle1Radius private
Definition at line 105 of file intersect_circles_dialog.h.
Referenced by Circle1RadiusChanged(), and IntersectCirclesDialog().
timerCircle2Radius
QTimer* IntersectCirclesDialog::timerCircle2Radius private
Definition at line 106 of file intersect_circles_dialog.h.
Referenced by Circle2RadiusChanged(), and IntersectCirclesDialog().
ui
Ui::IntersectCirclesDialog* IntersectCirclesDialog::ui private
Definition at line 100 of file intersect_circles_dialog.h.
Referenced by ChosenObject(), Circle1RadiusChanged(), Circle2RadiusChanged(), closeEvent(), EvalCircle1Radius(), EvalCircle2Radius(), GetCrossCirclesPoint(), GetFirstCircleCenterId(), GetFirstCircleRadius(), GetSecondCircleCenterId(), GetSecondCircleRadius(), IntersectCirclesDialog(), PointChanged(), SaveData(), setCirclesCrossPoint(), SetFirstCircleCenterId(), SetFirstCircleRadius(), SetPointName(), SetSecondCircleCenterId(), SetSecondCircleRadius(), and ~IntersectCirclesDialog().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/intersect_circles_dialog.h
src/libs/vtools/dialogs/tools/intersect_circles_dialog.cpp