Seamly2D: PieceTableWidgetItem Class Reference
PieceTableWidgetItem Class Reference
#include <piece_tablewidgetitem.h>
Public Member Functions
PieceTableWidgetItem (VContainer *data)
virtual bool operator< (const QTableWidgetItem &other) const Q_DECL_OVERRIDE
Private Attributes
VContainer * m_data
Detailed Description
Definition at line 32 of file piece_tablewidgetitem.h.
Constructor & Destructor Documentation
PieceTableWidgetItem()
PieceTableWidgetItem::PieceTableWidgetItem (VContainer * data) explicit
Definition at line 30 of file piece_tablewidgetitem.cpp.
Member Function Documentation
operator<()
bool PieceTableWidgetItem::operator< (const QTableWidgetItem & other) const virtual
Definition at line 36 of file piece_tablewidgetitem.cpp.
References VContainer::GetPiece(), VPiece::isInLayout(), VPiece::isLocked(), and m_data.
Member Data Documentation
m_data
VContainer* PieceTableWidgetItem::m_data private
Definition at line 40 of file piece_tablewidgetitem.h.
Referenced by operator<().
The documentation for this class was generated from the following files:
src/libs/vwidgets/piece_tablewidgetitem.h
src/libs/vwidgets/piece_tablewidgetitem.cpp