Seamly2D: VisToolShoulderPoint Class Reference
VisToolShoulderPoint Class Reference
#include <vistoolshoulderpoint.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolShoulderPoint) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolShoulderPoint (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolShoulderPoint ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setLineP1Id (const quint32 &value)
void setLineP2Id (const quint32 &value)
void setLength (const QString &expression)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Attributes
quint32 lineP1Id
quint32 lineP2Id
VScaledEllipse * point
VScaledEllipse * line1P1
VScaledEllipse * line1P2
VScaledLine * line1
VScaledEllipse * line2P2
VScaledLine * line2
VScaledLine * line3
qreal length
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 65 of file vistoolshoulderpoint.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 77 of file vistoolshoulderpoint.h.
Constructor & Destructor Documentation
VisToolShoulderPoint()
VisToolShoulderPoint::VisToolShoulderPoint (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 70 of file vistoolshoulderpoint.cpp.
References Visualization::InitPoint(), line1, line1P1, line1P2, line2, line2P2, line3, Visualization::mainColor, point, and Visualization::supportColor.
~VisToolShoulderPoint()
virtual VisToolShoulderPoint::~VisToolShoulderPoint () virtual default
Member Function Documentation
RefreshGeometry()
void VisToolShoulderPoint::RefreshGeometry () virtual
Implements Visualization.
Definition at line 86 of file vistoolshoulderpoint.cpp.
References VGObject::BuildLine(), Visualization::data, Visualization::DrawLine(), Visualization::DrawPoint(), VToolShoulderPoint::FindPoint(), VContainer::GeometricObject(), length, line1, line1P1, line1P2, line2, line2P2, line3, lineP1Id, lineP2Id, Visualization::lineStyle, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, point, VisLine::Ray(), Visualization::scenePos, and Visualization::supportColor.
Referenced by DialogShoulderPoint::ChosenObject(), DialogShoulderPoint::SaveData(), and VToolShoulderPoint::SetVisualization().
setLength()
void VisToolShoulderPoint::setLength (const QString & expression)
Definition at line 157 of file vistoolshoulderpoint.cpp.
References Visualization::data, Visualization::FindLength(), and length.
Referenced by DialogShoulderPoint::SaveData(), DialogShoulderPoint::SetFormula(), and VToolShoulderPoint::SetVisualization().
setLineP1Id()
void VisToolShoulderPoint::setLineP1Id (const quint32 & value)
Definition at line 145 of file vistoolshoulderpoint.cpp.
References lineP1Id.
Referenced by DialogShoulderPoint::ChosenObject(), DialogShoulderPoint::SaveData(), DialogShoulderPoint::SetP1Line(), and VToolShoulderPoint::SetVisualization().
setLineP2Id()
void VisToolShoulderPoint::setLineP2Id (const quint32 & value)
Definition at line 151 of file vistoolshoulderpoint.cpp.
References lineP2Id.
Referenced by DialogShoulderPoint::ChosenObject(), DialogShoulderPoint::SaveData(), DialogShoulderPoint::SetP2Line(), and VToolShoulderPoint::SetVisualization().
type()
virtual int VisToolShoulderPoint::type () const inline virtual
Reimplemented from VisLine.
Definition at line 76 of file vistoolshoulderpoint.h.
References Type.
Member Data Documentation
length
qreal VisToolShoulderPoint::length private
Definition at line 89 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and setLength().
line1
VScaledLine* VisToolShoulderPoint::line1 private
Definition at line 85 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and VisToolShoulderPoint().
line1P1
VScaledEllipse* VisToolShoulderPoint::line1P1 private
Definition at line 83 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and VisToolShoulderPoint().
line1P2
VScaledEllipse* VisToolShoulderPoint::line1P2 private
Definition at line 84 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and VisToolShoulderPoint().
line2
VScaledLine* VisToolShoulderPoint::line2 private
Definition at line 87 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and VisToolShoulderPoint().
line2P2
VScaledEllipse* VisToolShoulderPoint::line2P2 private
Definition at line 86 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and VisToolShoulderPoint().
line3
VScaledLine* VisToolShoulderPoint::line3 private
Definition at line 88 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and VisToolShoulderPoint().
lineP1Id
quint32 VisToolShoulderPoint::lineP1Id private
Definition at line 80 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and setLineP1Id().
lineP2Id
quint32 VisToolShoulderPoint::lineP2Id private
Definition at line 81 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and setLineP2Id().
point
VScaledEllipse* VisToolShoulderPoint::point private
Definition at line 82 of file vistoolshoulderpoint.h.
Referenced by RefreshGeometry(), and VisToolShoulderPoint().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/vistoolshoulderpoint.h
src/libs/vtools/visualization/line/vistoolshoulderpoint.cpp