Seamly2D: VisOperation Class Reference
VisOperation Class Reference
#include <visoperation.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolRotation) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisOperation (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisOperation ()
void setObjects (QVector< quint32 > objects)
virtual void VisualMode (const quint32 &pointId=NULL_ID) Q_DECL_OVERRIDE
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
virtual void RefreshGeometry ()=0
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Protected Member Functions
VScaledEllipse * GetPoint (quint32 i, const QColor &color)
VCurvePathItem * GetCurve (quint32 i, const QColor &color)
template<class Item >
int addFlippedCurve (const QPointF &firstPoint, const QPointF &secondPoint, quint32 id, int i)
void refreshMirroredObjects (const QPointF &firstPoint, const QPointF &secondPoint)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Protected Attributes
QVector< quint32 > objects
QColor supportColor2
QColor supportColor3
QVector< VScaledEllipse * > points
QVector< VCurvePathItem * > curves
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Detailed Description
Definition at line 60 of file visoperation.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 72 of file visoperation.h.
Constructor & Destructor Documentation
VisOperation()
VisOperation::VisOperation (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 66 of file visoperation.cpp.
~VisOperation()
VisOperation::~VisOperation () virtual
Definition at line 77 of file visoperation.cpp.
References curves, and points.
Member Function Documentation
addFlippedCurve()
template<class Item > int VisOperation::addFlippedCurve (const QPointF & firstPoint, const QPointF & secondPoint, quint32 id, int i) protected
Definition at line 94 of file visoperation.h.
References Visualization::data, Visualization::DrawPath(), GetCurve(), Item, Visualization::lineWeight, NULL_ID, Visualization::object1Id, Visualization::supportColor, and supportColor2.
GetCurve()
VCurvePathItem * VisOperation::GetCurve (quint32 i, const QColor & color) protected
Definition at line 109 of file visoperation.cpp.
References curves.
Referenced by VisToolRotation::AddCurve(), VisToolMove::AddDestinationCurve(), addFlippedCurve(), and VisToolMove::AddOriginCurve().
GetPoint()
VScaledEllipse * VisOperation::GetPoint (quint32 i, const QColor & color) protected
Definition at line 103 of file visoperation.cpp.
References Visualization::GetPointItem(), and points.
refreshMirroredObjects()
QT_WARNING_PUSH void VisOperation::refreshMirroredObjects (const QPointF & firstPoint, const QPointF & secondPoint) protected
Definition at line 127 of file visoperation.cpp.
References AllCurves, Arc, CubicBezier, CubicBezierPath, Curve, Visualization::data, EllipticalArc, VContainer::GeometricObject(), VContainer::GetGObject(), NULL_ID, Path, Point, Spline, SplinePath, and Unknown.
Referenced by VisToolMirrorByAxis::RefreshGeometry(), and VisToolMirrorByLine::RefreshGeometry().
setObjects()
void VisOperation::setObjects (QVector< quint32 > objects)
Definition at line 84 of file visoperation.cpp.
References objects.
Referenced by DialogRotation::ChosenObject(), DialogMirrorByAxis::SaveData(), DialogMirrorByLine::SaveData(), DialogMove::SaveData(), DialogRotation::SaveData(), DialogMirrorByAxis::setSourceObjects(), DialogMirrorByLine::setSourceObjects(), DialogMove::setSourceObjects(), DialogRotation::setSourceObjects(), VToolMirrorByAxis::SetVisualization(), VToolMirrorByLine::SetVisualization(), VToolMove::SetVisualization(), VToolRotation::SetVisualization(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
type()
virtual int VisOperation::type () const inline virtual
Reimplemented from VisLine.
Reimplemented in VisToolRotation, VisToolMove, VisToolMirrorByLine, and VisToolMirrorByAxis.
Definition at line 71 of file visoperation.h.
References Type.
VisualMode()
void VisOperation::VisualMode (const quint32 & pointId = NULL_ID) virtual
Reimplemented from Visualization.
Definition at line 90 of file visoperation.cpp.
References VisLine::AddOnScene(), VMainGraphicsScene::getScenePos(), qApp, Visualization::RefreshGeometry(), SCASSERT, and Visualization::scenePos.
Referenced by DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
Member Data Documentation
curves
QVector<VCurvePathItem *> VisOperation::curves protected
Definition at line 79 of file visoperation.h.
Referenced by GetCurve(), and ~VisOperation().
objects
QVector<quint32> VisOperation::objects protected
Definition at line 74 of file visoperation.h.
Referenced by VisToolMirrorByAxis::RefreshGeometry(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), and setObjects().
points
QVector<VScaledEllipse *> VisOperation::points protected
Definition at line 78 of file visoperation.h.
Referenced by GetPoint(), and ~VisOperation().
supportColor2
QColor VisOperation::supportColor2 protected
Definition at line 75 of file visoperation.h.
Referenced by VisToolRotation::AddCurve(), addFlippedCurve(), VisToolMove::AddOriginCurve(), VisToolMirrorByAxis::RefreshGeometry(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), VisToolMirrorByAxis::VisToolMirrorByAxis(), VisToolMirrorByLine::VisToolMirrorByLine(), and VisToolRotation::VisToolRotation().
supportColor3
QColor VisOperation::supportColor3 protected
Definition at line 76 of file visoperation.h.
Referenced by VisToolMove::RefreshGeometry().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/operation/visoperation.h
src/libs/vtools/visualization/line/operation/visoperation.cpp