Seamly2D: VFormula Class Reference
VFormula Class Reference
#include <vformula.h>
Public Member Functions
VFormula ()
VFormula (const QString &formula, const VContainer *container)
VFormula & operator= (const VFormula &formula)
VFormula (const VFormula &formula)
bool operator== (const VFormula &formula) const
bool operator!= (const VFormula &formula) const
QString GetFormula (FormulaType type=FormulaType::ToUser) const
void SetFormula (const QString &value, FormulaType type=FormulaType::ToUser)
QString getStringValue () const
qreal getDoubleValue () const
bool getCheckZero () const
void setCheckZero (bool value)
const VContainer * getData () const
void setData (const VContainer *value)
quint32 getToolId () const
void setToolId (const quint32 &value)
QString getPostfix () const
void setPostfix (const QString &value)
bool error () const
void Eval ()
Static Public Member Functions
static int FormulaTypeId ()
Private Attributes
QString formula
QString value
bool checkZero
const VContainer * data
quint32 toolId
QString postfix
bool _error
qreal dValue
Detailed Description
Definition at line 64 of file vformula.h.
Constructor & Destructor Documentation
VFormula() [1/3]
VFormula::VFormula ()
Definition at line 71 of file vformula.cpp.
VFormula() [2/3]
VFormula::VFormula (const QString & formula, const VContainer * container)
Definition at line 77 of file vformula.cpp.
References Eval().
VFormula() [3/3]
VFormula::VFormula (const VFormula & formula)
Definition at line 110 of file vformula.cpp.
Member Function Documentation
error()
bool VFormula::error () const
Definition at line 239 of file vformula.cpp.
References _error.
Referenced by VToolOptionsPropertyBrowser::changeDataToolSpline(), Eval(), operator=(), VToolPointOfContact::setArcRadius(), IntersectCircleTangentTool::SetCircleRadius(), IntersectCirclesTool::SetFirstCircleRadius(), VToolCut::SetFormula(), VToolMove::SetFormulaAngle(), VToolRotation::SetFormulaAngle(), VToolCurveIntersectAxis::SetFormulaAngle(), VToolEndLine::SetFormulaAngle(), VToolLineIntersectAxis::SetFormulaAngle(), VToolArc::SetFormulaF1(), VToolArcWithLength::SetFormulaF1(), VToolEllipticalArc::SetFormulaF1(), VToolArc::SetFormulaF2(), VToolEllipticalArc::SetFormulaF2(), VToolMove::SetFormulaLength(), VToolArcWithLength::SetFormulaLength(), VToolLinePoint::SetFormulaLength(), VToolArc::SetFormulaRadius(), VToolArcWithLength::SetFormulaRadius(), VToolEllipticalArc::SetFormulaRadius1(), VToolEllipticalArc::SetFormulaRadius2(), VToolMove::setFormulaRotation(), VToolEllipticalArc::SetFormulaRotationAngle(), and IntersectCirclesTool::SetSecondCircleRadius().
Eval()
void VFormula::Eval ()
Definition at line 251 of file vformula.cpp.
References _error, checkZero, data, VContainer::DataVariables(), dValue, error(), formula, postfix, qApp, and value.
Referenced by VToolMove::GetFormulaAngle(), VToolMove::GetFormulaLength(), VToolMove::getFormulaRotation(), setCheckZero(), setData(), SetFormula(), setPostfix(), and VFormula().
FormulaTypeId()
int VFormula::FormulaTypeId () static
Definition at line 245 of file vformula.cpp.
Referenced by VFormulaProperty::SetFormula().
getCheckZero()
bool VFormula::getCheckZero () const
Definition at line 179 of file vformula.cpp.
References checkZero.
Referenced by VFormulaPropertyEditor::onToolButtonClicked(), and operator=().
getData()
const VContainer * VFormula::getData () const
Definition at line 195 of file vformula.cpp.
References data.
Referenced by VFormulaPropertyEditor::onToolButtonClicked(), and operator=().
getDoubleValue()
qreal VFormula::getDoubleValue () const
Definition at line 173 of file vformula.cpp.
References dValue.
Referenced by VToolOptionsPropertyBrowser::changeDataToolSpline(), operator=(), operator==(), IntersectCircleTangentTool::SetCircleRadius(), IntersectCirclesTool::SetFirstCircleRadius(), VToolArc::SetFormulaF1(), VToolArcWithLength::SetFormulaF1(), VToolEllipticalArc::SetFormulaF1(), VToolArc::SetFormulaF2(), VToolEllipticalArc::SetFormulaF2(), VToolArcWithLength::SetFormulaLength(), VToolArc::SetFormulaRadius(), VToolArcWithLength::SetFormulaRadius(), VToolEllipticalArc::SetFormulaRadius1(), VToolEllipticalArc::SetFormulaRadius2(), VToolEllipticalArc::SetFormulaRotationAngle(), and IntersectCirclesTool::SetSecondCircleRadius().
GetFormula()
QString VFormula::GetFormula (FormulaType type = FormulaType::ToUser) const
Definition at line 136 of file vformula.cpp.
References formula, qApp, and ToUser.
Referenced by VToolOptionsPropertyBrowser::changeDataToolSpline(), VFormulaPropertyEditor::onToolButtonClicked(), VToolPointOfContact::setArcRadius(), IntersectCircleTangentTool::SetCircleRadius(), IntersectCirclesTool::SetFirstCircleRadius(), VFormulaProperty::SetFormula(), VToolCut::SetFormula(), VToolMove::SetFormulaAngle(), VToolRotation::SetFormulaAngle(), VToolCurveIntersectAxis::SetFormulaAngle(), VToolEndLine::SetFormulaAngle(), VToolLineIntersectAxis::SetFormulaAngle(), VToolArc::SetFormulaF1(), VToolArcWithLength::SetFormulaF1(), VToolEllipticalArc::SetFormulaF1(), VToolArc::SetFormulaF2(), VToolEllipticalArc::SetFormulaF2(), VToolMove::SetFormulaLength(), VToolArcWithLength::SetFormulaLength(), VToolLinePoint::SetFormulaLength(), VToolArc::SetFormulaRadius(), VToolArcWithLength::SetFormulaRadius(), VToolEllipticalArc::SetFormulaRadius1(), VToolEllipticalArc::SetFormulaRadius2(), VToolMove::setFormulaRotation(), VToolEllipticalArc::SetFormulaRotationAngle(), and IntersectCirclesTool::SetSecondCircleRadius().
getPostfix()
QString VFormula::getPostfix () const
Definition at line 223 of file vformula.cpp.
References postfix.
Referenced by VFormulaPropertyEditor::onToolButtonClicked(), and operator=().
getStringValue()
QString VFormula::getStringValue () const
Definition at line 167 of file vformula.cpp.
References value.
Referenced by VFormulaPropertyEditor::onToolButtonClicked(), operator=(), VFormulaPropertyEditor::SetFormula(), and VFormulaPropertyEditor::VFormulaPropertyEditor().
getToolId()
quint32 VFormula::getToolId () const
Definition at line 211 of file vformula.cpp.
References toolId.
Referenced by VFormulaPropertyEditor::onToolButtonClicked(), and operator=().
operator!=()
bool VFormula::operator!= (const VFormula & formula) const
Definition at line 130 of file vformula.cpp.
References formula, and operator==().
operator=()
VFormula & VFormula::operator= (const VFormula & formula)
Definition at line 92 of file vformula.cpp.
References _error, checkZero, data, dValue, error(), formula, getCheckZero(), getData(), getDoubleValue(), getPostfix(), getStringValue(), getToolId(), postfix, toolId, and value.
operator==()
bool VFormula::operator== (const VFormula & formula) const
Definition at line 117 of file vformula.cpp.
References dValue, formula, getDoubleValue(), and VFuzzyComparePossibleNulls().
Referenced by operator!=().
setCheckZero()
void VFormula::setCheckZero (bool value)
Definition at line 185 of file vformula.cpp.
References checkZero, Eval(), and value.
Referenced by VToolPointOfContact::getArcRadius(), IntersectCircleTangentTool::GetCircleRadius(), IntersectCirclesTool::GetFirstCircleRadius(), VToolCut::GetFormula(), VToolMove::GetFormulaAngle(), VToolRotation::GetFormulaAngle(), VToolCurveIntersectAxis::GetFormulaAngle(), VToolEndLine::GetFormulaAngle(), VToolLineIntersectAxis::GetFormulaAngle(), VToolMove::GetFormulaLength(), VToolLinePoint::GetFormulaLength(), VToolMove::getFormulaRotation(), IntersectCirclesTool::GetSecondCircleRadius(), VToolOptionsPropertyBrowser::showOptionsToolSpline(), and VToolOptionsPropertyBrowser::updateOptionsToolSpline().
setData()
void VFormula::setData (const VContainer * value)
Definition at line 201 of file vformula.cpp.
References data, Eval(), and value.
SetFormula()
void VFormula::SetFormula (const QString & value, FormulaType type = FormulaType::ToUser)
Definition at line 149 of file vformula.cpp.
References Eval(), formula, qApp, ToUser, and value.
Referenced by VFormulaProperty::childValueChanged(), and VFormulaPropertyEditor::onToolButtonClicked().
setPostfix()
void VFormula::setPostfix (const QString & value)
Definition at line 229 of file vformula.cpp.
References Eval(), postfix, and value.
Referenced by VToolPointOfContact::getArcRadius(), IntersectCircleTangentTool::GetCircleRadius(), IntersectCirclesTool::GetFirstCircleRadius(), VToolCut::GetFormula(), VToolMove::GetFormulaAngle(), VToolRotation::GetFormulaAngle(), VToolCurveIntersectAxis::GetFormulaAngle(), VToolEndLine::GetFormulaAngle(), VToolLineIntersectAxis::GetFormulaAngle(), VToolMove::GetFormulaLength(), VToolLinePoint::GetFormulaLength(), VToolMove::getFormulaRotation(), IntersectCirclesTool::GetSecondCircleRadius(), VToolOptionsPropertyBrowser::showOptionsToolSpline(), and VToolOptionsPropertyBrowser::updateOptionsToolSpline().
setToolId()
void VFormula::setToolId (const quint32 & value)
Definition at line 217 of file vformula.cpp.
References toolId, and value.
Referenced by VToolPointOfContact::getArcRadius(), IntersectCircleTangentTool::GetCircleRadius(), IntersectCirclesTool::GetFirstCircleRadius(), VToolCut::GetFormula(), VToolMove::GetFormulaAngle(), VToolRotation::GetFormulaAngle(), VToolCurveIntersectAxis::GetFormulaAngle(), VToolEndLine::GetFormulaAngle(), VToolLineIntersectAxis::GetFormulaAngle(), VToolMove::GetFormulaLength(), VToolLinePoint::GetFormulaLength(), VToolMove::getFormulaRotation(), IntersectCirclesTool::GetSecondCircleRadius(), VToolOptionsPropertyBrowser::showOptionsToolSpline(), and VToolOptionsPropertyBrowser::updateOptionsToolSpline().
Member Data Documentation
_error
bool VFormula::_error private
Definition at line 105 of file vformula.h.
Referenced by error(), Eval(), and operator=().
checkZero
bool VFormula::checkZero private
Definition at line 101 of file vformula.h.
Referenced by Eval(), getCheckZero(), operator=(), and setCheckZero().
data
const VContainer* VFormula::data private
Definition at line 102 of file vformula.h.
Referenced by Eval(), getData(), operator=(), and setData().
dValue
qreal VFormula::dValue private
Definition at line 106 of file vformula.h.
Referenced by Eval(), getDoubleValue(), operator=(), and operator==().
formula
QString VFormula::formula private
Definition at line 99 of file vformula.h.
Referenced by Eval(), GetFormula(), operator!=(), operator=(), operator==(), and SetFormula().
postfix
QString VFormula::postfix private
Definition at line 104 of file vformula.h.
Referenced by Eval(), getPostfix(), operator=(), and setPostfix().
toolId
quint32 VFormula::toolId private
Definition at line 103 of file vformula.h.
Referenced by getToolId(), operator=(), and setToolId().
value
QString VFormula::value private
Definition at line 100 of file vformula.h.
Referenced by VToolOptionsPropertyBrowser::changeDataToolSpline(), VFormulaProperty::createEditor(), Eval(), VFormulaProperty::GetFormula(), getStringValue(), operator=(), setCheckZero(), setData(), VFormulaProperty::setEditorData(), SetFormula(), setPostfix(), setToolId(), and VFormulaProperty::setValue().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/vformula.h
src/libs/vpatterndb/vformula.cpp