Seamly2D: ValueHashTableOf< TVal, THasher > Class Template Reference
ValueHashTableOf< TVal, THasher > Class Template Reference
#include <ValueHashTableOf.hpp>
Public Member Functions
ValueHashTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
ValueHashTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ValueHashTableOf ()
bool isEmpty () const
bool containsKey (const void *const key) const
void removeKey (const void *const key)
void removeAll ()
TVal & get (const void *const key, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
const TVal & get (const void *const key) const
void put (void *key, const TVal &valueToAdopt)
ValueHashTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
ValueHashTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ValueHashTableOf ()
bool isEmpty () const
bool containsKey (const void *const key) const
void removeKey (const void *const key)
void removeAll ()
TVal & get (const void *const key, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
const TVal & get (const void *const key) const
void put (void *key, const TVal &valueToAdopt)
ValueHashTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
ValueHashTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ValueHashTableOf ()
bool isEmpty () const
bool containsKey (const void *const key) const
void removeKey (const void *const key)
void removeAll ()
TVal & get (const void *const key, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
const TVal & get (const void *const key) const
void put (void *key, const TVal &valueToAdopt)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
ValueHashTableOf (const ValueHashTableOf< TVal, THasher > &)
ValueHashTableOf< TVal, THasher > & operator= (const ValueHashTableOf< TVal, THasher > &)
ValueHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal)
const ValueHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal) const
void removeBucketElem (const void *const key, XMLSize_t &hashVal)
void initialize (const XMLSize_t modulus)
void rehash ()
ValueHashTableOf (const ValueHashTableOf< TVal, THasher > &)
ValueHashTableOf< TVal, THasher > & operator= (const ValueHashTableOf< TVal, THasher > &)
ValueHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal)
const ValueHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal) const
void removeBucketElem (const void *const key, XMLSize_t &hashVal)
void initialize (const XMLSize_t modulus)
void rehash ()
ValueHashTableOf (const ValueHashTableOf< TVal, THasher > &)
ValueHashTableOf< TVal, THasher > & operator= (const ValueHashTableOf< TVal, THasher > &)
ValueHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal)
const ValueHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal) const
void removeBucketElem (const void *const key, XMLSize_t &hashVal)
void initialize (const XMLSize_t modulus)
void rehash ()
Private Attributes
MemoryManager * fMemoryManager
ValueHashTableBucketElem< TVal > ** fBucketList
XMLSize_t fHashModulus
XMLSize_t fInitialModulus
XMLSize_t fCount
THasher fHasher
Friends
class ValueHashTableOfEnumerator< TVal, THasher >
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
template<class TVal, class THasher = StringHasher>
class ValueHashTableOf< TVal, THasher >
Definition at line 68 of file ValueHashTableOf.hpp.
Constructor & Destructor Documentation
ValueHashTableOf() [1/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
ValueHashTableOf() [2/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ValueHashTableOf() [1/3]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::~ValueHashTableOf ()
ValueHashTableOf() [3/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const ValueHashTableOf< TVal, THasher > &) private
ValueHashTableOf() [4/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
ValueHashTableOf() [5/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ValueHashTableOf() [2/3]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::~ValueHashTableOf ()
ValueHashTableOf() [6/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const ValueHashTableOf< TVal, THasher > &) private
ValueHashTableOf() [7/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
ValueHashTableOf() [8/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ValueHashTableOf() [3/3]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::~ValueHashTableOf ()
ValueHashTableOf() [9/9]
template<class TVal , class THasher = StringHasher> ValueHashTableOf< TVal, THasher >::ValueHashTableOf (const ValueHashTableOf< TVal, THasher > &) private
Member Function Documentation
containsKey() [1/3]
template<class TVal , class THasher = StringHasher> bool ValueHashTableOf< TVal, THasher >::containsKey (const void *const key) const
containsKey() [2/3]
template<class TVal , class THasher = StringHasher> bool ValueHashTableOf< TVal, THasher >::containsKey (const void *const key) const
containsKey() [3/3]
template<class TVal , class THasher = StringHasher> bool ValueHashTableOf< TVal, THasher >::containsKey (const void *const key) const
findBucketElem() [1/6]
template<class TVal , class THasher = StringHasher> ValueHashTableBucketElem<TVal>* ValueHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) private
findBucketElem() [2/6]
template<class TVal , class THasher = StringHasher> ValueHashTableBucketElem<TVal>* ValueHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) private
findBucketElem() [3/6]
template<class TVal , class THasher = StringHasher> ValueHashTableBucketElem<TVal>* ValueHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) private
findBucketElem() [4/6]
template<class TVal , class THasher = StringHasher> const ValueHashTableBucketElem<TVal>* ValueHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) const private
findBucketElem() [5/6]
template<class TVal , class THasher = StringHasher> const ValueHashTableBucketElem<TVal>* ValueHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) const private
findBucketElem() [6/6]
template<class TVal , class THasher = StringHasher> const ValueHashTableBucketElem<TVal>* ValueHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) const private
get() [1/6]
template<class TVal , class THasher = StringHasher> const TVal& ValueHashTableOf< TVal, THasher >::get (const void *const key) const
get() [2/6]
template<class TVal , class THasher = StringHasher> const TVal& ValueHashTableOf< TVal, THasher >::get (const void *const key) const
get() [3/6]
template<class TVal , class THasher = StringHasher> const TVal& ValueHashTableOf< TVal, THasher >::get (const void *const key) const
get() [4/6]
template<class TVal , class THasher = StringHasher> TVal& ValueHashTableOf< TVal, THasher >::get (const void *const key, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Referenced by GeneralAttributeCheck::getFacetId(), and FieldActivator::getMayMatch().
get() [5/6]
template<class TVal , class THasher = StringHasher> TVal& ValueHashTableOf< TVal, THasher >::get (const void *const key, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
get() [6/6]
template<class TVal , class THasher = StringHasher> TVal& ValueHashTableOf< TVal, THasher >::get (const void *const key, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
initialize() [1/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [2/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [3/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
isEmpty() [1/3]
template<class TVal , class THasher = StringHasher> bool ValueHashTableOf< TVal, THasher >::isEmpty () const
isEmpty() [2/3]
template<class TVal , class THasher = StringHasher> bool ValueHashTableOf< TVal, THasher >::isEmpty () const
isEmpty() [3/3]
template<class TVal , class THasher = StringHasher> bool ValueHashTableOf< TVal, THasher >::isEmpty () const
operator=() [1/3]
template<class TVal , class THasher = StringHasher> ValueHashTableOf<TVal, THasher>& ValueHashTableOf< TVal, THasher >::operator= (const ValueHashTableOf< TVal, THasher > &) private
operator=() [2/3]
template<class TVal , class THasher = StringHasher> ValueHashTableOf<TVal, THasher>& ValueHashTableOf< TVal, THasher >::operator= (const ValueHashTableOf< TVal, THasher > &) private
operator=() [3/3]
template<class TVal , class THasher = StringHasher> ValueHashTableOf<TVal, THasher>& ValueHashTableOf< TVal, THasher >::operator= (const ValueHashTableOf< TVal, THasher > &) private
put() [1/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::put (void * key, const TVal & valueToAdopt)
Referenced by FieldActivator::setMayMatch().
put() [2/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::put (void * key, const TVal & valueToAdopt)
put() [3/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::put (void * key, const TVal & valueToAdopt)
rehash() [1/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::rehash () private
rehash() [2/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::rehash () private
rehash() [3/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::rehash () private
removeAll() [1/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeAll ()
removeAll() [2/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeAll ()
removeAll() [3/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeAll ()
removeBucketElem() [1/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeBucketElem (const void *const key, XMLSize_t & hashVal) private
removeBucketElem() [2/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeBucketElem (const void *const key, XMLSize_t & hashVal) private
removeBucketElem() [3/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeBucketElem (const void *const key, XMLSize_t & hashVal) private
removeKey() [1/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeKey (const void *const key)
removeKey() [2/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeKey (const void *const key)
removeKey() [3/3]
template<class TVal , class THasher = StringHasher> void ValueHashTableOf< TVal, THasher >::removeKey (const void *const key)
Friends And Related Function Documentation
ValueHashTableOfEnumerator< TVal, THasher >
template<class TVal , class THasher = StringHasher> friend class ValueHashTableOfEnumerator< TVal, THasher > friend
Definition at line 105 of file ValueHashTableOf.hpp.
Member Data Documentation
fBucketList
template<class TVal , class THasher = StringHasher> ValueHashTableBucketElem< TVal > ** ValueHashTableOf< TVal, THasher >::fBucketList private
Definition at line 146 of file ValueHashTableOf.hpp.
fCount
template<class TVal , class THasher = StringHasher> XMLSize_t ValueHashTableOf< TVal, THasher >::fCount private
Definition at line 149 of file ValueHashTableOf.hpp.
fHasher
template<class TVal , class THasher = StringHasher> THasher ValueHashTableOf< TVal, THasher >::fHasher private
Definition at line 150 of file ValueHashTableOf.hpp.
fHashModulus
template<class TVal , class THasher = StringHasher> XMLSize_t ValueHashTableOf< TVal, THasher >::fHashModulus private
Definition at line 147 of file ValueHashTableOf.hpp.
fInitialModulus
template<class TVal , class THasher = StringHasher> XMLSize_t ValueHashTableOf< TVal, THasher >::fInitialModulus private
Definition at line 148 of file ValueHashTableOf.hpp.
fMemoryManager
template<class TVal , class THasher = StringHasher> MemoryManager * ValueHashTableOf< TVal, THasher >::fMemoryManager private
Definition at line 145 of file ValueHashTableOf.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/ValueHashTableOf.hpp