Seamly2D: XMLAttDefList Class Reference
XMLAttDefList Class Reference abstract
#include <XMLAttDefList.hpp>
Public Member Functions
Destructor
virtual ~XMLAttDefList ()
virtual bool isEmpty () const =0
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)=0
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const =0
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)=0
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const =0
virtual XMLSize_t getAttDefCount () const =0
virtual XMLAttDef & getAttDef (XMLSize_t index)=0
virtual const XMLAttDef & getAttDef (XMLSize_t index) const =0
virtual ~XMLAttDefList ()
virtual bool isEmpty () const =0
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)=0
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const =0
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)=0
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const =0
virtual XMLSize_t getAttDefCount () const =0
virtual XMLAttDef & getAttDef (XMLSize_t index)=0
virtual const XMLAttDef & getAttDef (XMLSize_t index) const =0
virtual ~XMLAttDefList ()
virtual bool isEmpty () const =0
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)=0
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const =0
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)=0
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const =0
virtual XMLSize_t getAttDefCount () const =0
virtual XMLAttDef & getAttDef (XMLSize_t index)=0
virtual const XMLAttDef & getAttDef (XMLSize_t index) const =0
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Getter methods
MemoryManager * fMemoryManager
MemoryManager * getMemoryManager () const
MemoryManager * getMemoryManager () const
MemoryManager * getMemoryManager () const
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDefList (const XMLAttDefList &)
XMLAttDefList & operator= (const XMLAttDefList &)
XMLAttDefList (const XMLAttDefList &)
XMLAttDefList & operator= (const XMLAttDefList &)
XMLAttDefList (const XMLAttDefList &)
XMLAttDefList & operator= (const XMLAttDefList &)
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
This class defines an abstract interface that all validators must support. When the scanner scans the attributes in a start tag, it must have a list of the defined attributes for that element. This is used to fault in defaulted and fixed attributes, to know which ones are required, and to know the their types in order to do the correct normalization.
Since each validator will have its own derivatives of XMLAttDef and will have its own specialized storage mechanisms for elements and the att defs that they own, there must be an abstracted way for the scanner to deal with this list.
It does not derive from the generic Enumerator template class, because there are portability issues with deriving from a template class in a DLL. It does though provide a similar enumerator interface.
Definition at line 50 of file XMLAttDefList.hpp.
Constructor & Destructor Documentation
~XMLAttDefList() [1/3]
XMLAttDefList::~XMLAttDefList () inline virtual
Definition at line 156 of file XMLAttDefList.hpp.
XMLAttDefList() [1/6]
XMLAttDefList::XMLAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline protected
Definition at line 164 of file XMLAttDefList.hpp.
XMLAttDefList() [2/6]
XMLAttDefList::XMLAttDefList (const XMLAttDefList &) private
~XMLAttDefList() [2/3]
virtual XMLAttDefList::~XMLAttDefList () virtual
XMLAttDefList() [3/6]
XMLAttDefList::XMLAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAttDefList() [4/6]
XMLAttDefList::XMLAttDefList (const XMLAttDefList &) private
~XMLAttDefList() [3/3]
virtual XMLAttDefList::~XMLAttDefList () virtual
XMLAttDefList() [5/6]
XMLAttDefList::XMLAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAttDefList() [6/6]
XMLAttDefList::XMLAttDefList (const XMLAttDefList &) private
Member Function Documentation
findAttDef() [1/12]
virtual const XMLAttDef* XMLAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [2/12]
virtual const XMLAttDef* XMLAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [3/12]
virtual const XMLAttDef* XMLAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [4/12]
virtual XMLAttDef* XMLAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [5/12]
virtual XMLAttDef* XMLAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [6/12]
virtual XMLAttDef* XMLAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [7/12]
virtual const XMLAttDef* XMLAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [8/12]
virtual const XMLAttDef* XMLAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [9/12]
virtual const XMLAttDef* XMLAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [10/12]
virtual XMLAttDef* XMLAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [11/12]
virtual XMLAttDef* XMLAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
findAttDef() [12/12]
virtual XMLAttDef* XMLAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDef() [1/6]
virtual const XMLAttDef& XMLAttDefList::getAttDef (XMLSize_t index) const pure virtual
return attribute at the index-th position in the list.
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDef() [2/6]
virtual const XMLAttDef& XMLAttDefList::getAttDef (XMLSize_t index) const pure virtual
return attribute at the index-th position in the list.
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDef() [3/6]
virtual const XMLAttDef& XMLAttDefList::getAttDef (XMLSize_t index) const pure virtual
return attribute at the index-th position in the list.
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDef() [4/6]
virtual XMLAttDef& XMLAttDefList::getAttDef (XMLSize_t index) pure virtual
return attribute at the index-th position in the list.
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDef() [5/6]
virtual XMLAttDef& XMLAttDefList::getAttDef (XMLSize_t index) pure virtual
return attribute at the index-th position in the list.
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDef() [6/6]
virtual XMLAttDef& XMLAttDefList::getAttDef (XMLSize_t index) pure virtual
return attribute at the index-th position in the list.
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDefCount() [1/3]
virtual XMLSize_t XMLAttDefList::getAttDefCount () const pure virtual
return total number of attributes in this list
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDefCount() [2/3]
virtual XMLSize_t XMLAttDefList::getAttDefCount () const pure virtual
return total number of attributes in this list
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getAttDefCount() [3/3]
virtual XMLSize_t XMLAttDefList::getAttDefCount () const pure virtual
return total number of attributes in this list
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
getMemoryManager() [1/3]
MemoryManager * XMLAttDefList::getMemoryManager () const inline
Get the memory manager
This method returns the configurable memory manager used by the element declaration for dynamic allocation/deallocation.
Returns
the memory manager
Definition at line 148 of file XMLAttDefList.hpp.
References fMemoryManager.
Referenced by DTDAttDefList::addAttDef(), SchemaAttDefList::addAttDef(), and DTDAttDefList::operator=().
getMemoryManager() [2/3]
MemoryManager* XMLAttDefList::getMemoryManager () const
Get the memory manager
This method returns the configurable memory manager used by the element declaration for dynamic allocation/deallocation.
Returns
the memory manager
getMemoryManager() [3/3]
MemoryManager* XMLAttDefList::getMemoryManager () const
Get the memory manager
This method returns the configurable memory manager used by the element declaration for dynamic allocation/deallocation.
Returns
the memory manager
isEmpty() [1/3]
virtual bool XMLAttDefList::isEmpty () const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
isEmpty() [2/3]
virtual bool XMLAttDefList::isEmpty () const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
isEmpty() [3/3]
virtual bool XMLAttDefList::isEmpty () const pure virtual
Implemented in SchemaAttDefList, DTDAttDefList, SchemaAttDefList, DTDAttDefList, SchemaAttDefList, and DTDAttDefList.
operator=() [1/3]
XMLAttDefList& XMLAttDefList::operator= (const XMLAttDefList &) private
operator=() [2/3]
XMLAttDefList& XMLAttDefList::operator= (const XMLAttDefList &) private
operator=() [3/3]
XMLAttDefList& XMLAttDefList::operator= (const XMLAttDefList &) private
Member Data Documentation
fMemoryManager
MemoryManager * XMLAttDefList::fMemoryManager private
Definition at line 139 of file XMLAttDefList.hpp.
Referenced by getMemoryManager().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/XMLAttDefList.hpp