Seamly2D: KVStringPair Class Reference
KVStringPair Class Reference
#include <KVStringPair.hpp>
Public Member Functions
KVStringPair (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLCh *const value, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLSize_t keyLength, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const KVStringPair &toCopy)
~KVStringPair ()
const XMLCh * getKey () const
XMLCh * getKey ()
const XMLCh * getValue () const
XMLCh * getValue ()
void setKey (const XMLCh *const newKey)
void setValue (const XMLCh *const newValue)
void setKey (const XMLCh *const newKey, const XMLSize_t newKeyLength)
void setValue (const XMLCh *const newValue, const XMLSize_t newValueLength)
void set (const XMLCh *const newKey, const XMLCh *const newValue)
void set (const XMLCh *const newKey, const XMLSize_t newKeyLength, const XMLCh *const newValue, const XMLSize_t newValueLength)
KVStringPair (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLCh *const value, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLSize_t keyLength, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const KVStringPair &toCopy)
~KVStringPair ()
const XMLCh * getKey () const
XMLCh * getKey ()
const XMLCh * getValue () const
XMLCh * getValue ()
void setKey (const XMLCh *const newKey)
void setValue (const XMLCh *const newValue)
void setKey (const XMLCh *const newKey, const XMLSize_t newKeyLength)
void setValue (const XMLCh *const newValue, const XMLSize_t newValueLength)
void set (const XMLCh *const newKey, const XMLCh *const newValue)
void set (const XMLCh *const newKey, const XMLSize_t newKeyLength, const XMLCh *const newValue, const XMLSize_t newValueLength)
KVStringPair (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLCh *const value, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const XMLCh *const key, const XMLSize_t keyLength, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
KVStringPair (const KVStringPair &toCopy)
~KVStringPair ()
const XMLCh * getKey () const
XMLCh * getKey ()
const XMLCh * getValue () const
XMLCh * getValue ()
void setKey (const XMLCh *const newKey)
void setValue (const XMLCh *const newValue)
void setKey (const XMLCh *const newKey, const XMLSize_t newKeyLength)
void setValue (const XMLCh *const newValue, const XMLSize_t newValueLength)
void set (const XMLCh *const newKey, const XMLCh *const newValue)
void set (const XMLCh *const newKey, const XMLSize_t newKeyLength, const XMLCh *const newValue, const XMLSize_t newValueLength)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
KVStringPair & operator= (const KVStringPair &)
KVStringPair & operator= (const KVStringPair &)
KVStringPair & operator= (const KVStringPair &)
Private Attributes
XMLSize_t fKeyAllocSize
XMLSize_t fValueAllocSize
XMLCh * fKey
XMLCh * fValue
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 37 of file KVStringPair.hpp.
Constructor & Destructor Documentation
KVStringPair() [1/15]
KVStringPair::KVStringPair (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [2/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLCh *const value, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [3/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [4/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLSize_t keyLength, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [5/15]
KVStringPair::KVStringPair (const KVStringPair & toCopy)
~KVStringPair() [1/3]
KVStringPair::~KVStringPair ()
KVStringPair() [6/15]
KVStringPair::KVStringPair (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [7/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLCh *const value, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [8/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [9/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLSize_t keyLength, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [10/15]
KVStringPair::KVStringPair (const KVStringPair & toCopy)
~KVStringPair() [2/3]
KVStringPair::~KVStringPair ()
KVStringPair() [11/15]
KVStringPair::KVStringPair (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [12/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLCh *const value, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [13/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [14/15]
KVStringPair::KVStringPair (const XMLCh *const key, const XMLSize_t keyLength, const XMLCh *const value, const XMLSize_t valueLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
KVStringPair() [15/15]
KVStringPair::KVStringPair (const KVStringPair & toCopy)
~KVStringPair() [3/3]
KVStringPair::~KVStringPair ()
Member Function Documentation
getKey() [1/6]
XMLCh * KVStringPair::getKey () inline
Definition at line 148 of file KVStringPair.hpp.
References fKey.
getKey() [2/6]
XMLCh* KVStringPair::getKey ()
getKey() [3/6]
XMLCh* KVStringPair::getKey ()
getKey() [4/6]
const XMLCh * KVStringPair::getKey () const inline
Definition at line 143 of file KVStringPair.hpp.
References fKey.
getKey() [5/6]
const XMLCh* KVStringPair::getKey () const
getKey() [6/6]
const XMLCh* KVStringPair::getKey () const
getValue() [1/6]
XMLCh * KVStringPair::getValue () inline
Definition at line 158 of file KVStringPair.hpp.
References fValue.
getValue() [2/6]
XMLCh* KVStringPair::getValue ()
getValue() [3/6]
XMLCh* KVStringPair::getValue ()
getValue() [4/6]
const XMLCh * KVStringPair::getValue () const inline
Definition at line 153 of file KVStringPair.hpp.
References fValue.
getValue() [5/6]
const XMLCh* KVStringPair::getValue () const
getValue() [6/6]
const XMLCh* KVStringPair::getValue () const
operator=() [1/3]
KVStringPair& KVStringPair::operator= (const KVStringPair &) private
operator=() [2/3]
KVStringPair& KVStringPair::operator= (const KVStringPair &) private
operator=() [3/3]
KVStringPair& KVStringPair::operator= (const KVStringPair &) private
set() [1/6]
void KVStringPair::set (const XMLCh *const newKey, const XMLCh *const newValue) inline
Definition at line 204 of file KVStringPair.hpp.
References setKey(), setValue(), and XMLString::stringLen().
set() [2/6]
void KVStringPair::set (const XMLCh *const newKey, const XMLCh *const newValue)
set() [3/6]
void KVStringPair::set (const XMLCh *const newKey, const XMLCh *const newValue)
set() [4/6]
void KVStringPair::set (const XMLCh *const newKey, const XMLSize_t newKeyLength, const XMLCh *const newValue, const XMLSize_t newValueLength) inline
Definition at line 211 of file KVStringPair.hpp.
References setKey(), and setValue().
set() [5/6]
void KVStringPair::set (const XMLCh *const newKey, const XMLSize_t newKeyLength, const XMLCh *const newValue, const XMLSize_t newValueLength)
set() [6/6]
void KVStringPair::set (const XMLCh *const newKey, const XMLSize_t newKeyLength, const XMLCh *const newValue, const XMLSize_t newValueLength)
setKey() [1/6]
void KVStringPair::setKey (const XMLCh *const newKey) inline
Definition at line 166 of file KVStringPair.hpp.
References XMLString::stringLen().
Referenced by set().
setKey() [2/6]
void KVStringPair::setKey (const XMLCh *const newKey)
setKey() [3/6]
void KVStringPair::setKey (const XMLCh *const newKey)
setKey() [4/6]
void KVStringPair::setKey (const XMLCh *const newKey, const XMLSize_t newKeyLength) inline
Definition at line 176 of file KVStringPair.hpp.
References MemoryManager::allocate(), MemoryManager::deallocate(), fKey, fKeyAllocSize, and fMemoryManager.
setKey() [5/6]
void KVStringPair::setKey (const XMLCh *const newKey, const XMLSize_t newKeyLength)
setKey() [6/6]
void KVStringPair::setKey (const XMLCh *const newKey, const XMLSize_t newKeyLength)
setValue() [1/6]
void KVStringPair::setValue (const XMLCh *const newValue) inline
Definition at line 171 of file KVStringPair.hpp.
References XMLString::stringLen().
Referenced by set().
setValue() [2/6]
void KVStringPair::setValue (const XMLCh *const newValue)
setValue() [3/6]
void KVStringPair::setValue (const XMLCh *const newValue)
setValue() [4/6]
void KVStringPair::setValue (const XMLCh *const newValue, const XMLSize_t newValueLength) inline
Definition at line 190 of file KVStringPair.hpp.
References MemoryManager::allocate(), MemoryManager::deallocate(), fMemoryManager, fValue, and fValueAllocSize.
setValue() [5/6]
void KVStringPair::setValue (const XMLCh *const newValue, const XMLSize_t newValueLength)
setValue() [6/6]
void KVStringPair::setValue (const XMLCh *const newValue, const XMLSize_t newValueLength)
Member Data Documentation
fKey
XMLCh * KVStringPair::fKey private
Definition at line 135 of file KVStringPair.hpp.
Referenced by getKey(), and setKey().
fKeyAllocSize
XMLSize_t KVStringPair::fKeyAllocSize private
Definition at line 133 of file KVStringPair.hpp.
Referenced by setKey().
fMemoryManager
MemoryManager * KVStringPair::fMemoryManager private
Definition at line 137 of file KVStringPair.hpp.
Referenced by setKey(), and setValue().
fValue
XMLCh * KVStringPair::fValue private
Definition at line 136 of file KVStringPair.hpp.
Referenced by getValue(), and setValue().
fValueAllocSize
XMLSize_t KVStringPair::fValueAllocSize private
Definition at line 134 of file KVStringPair.hpp.
Referenced by setValue().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/KVStringPair.hpp