Seamly2D: src/libs/vmisc/vcommonsettings.cpp File Reference
vcommonsettings.cpp File Reference
#include "vcommonsettings.h"
#include <QApplication>
#include <QDate>
#include <QDir>
#include <QFont>
#include <QLocale>
#include <QMessageLogger>
#include <QSound>
#include <QStaticStringData>
#include <QStringData>
#include <QStringDataPtr>
#include <QVariant>
#include <QtDebug>
#include <QTextCodec>
#include "../ifc/ifcdef.h"
#include "../vmisc/def.h"
#include "../vmisc/vmath.h"
#include "../vpatterndb/pmsystems.h"
Namespaces
anonymous_namespace{vcommonsettings.cpp}
Functions
QStringList anonymous_namespace{vcommonsettings.cpp}::ClearFormats (const QStringList &predefinedFormats, QStringList formats)
void anonymous_namespace{vcommonsettings.cpp}::SymlinkCopyDirRecursive (const QString &fromDir, const QString &toDir, bool replaceOnConflit)
QString anonymous_namespace{vcommonsettings.cpp}::PrepareStandardFiles (const QString &currentPath, const QString &standardPath, const QString &defPath)
Variables
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsIndividualMeasurements = QStringLiteral("paths/individual_measurements")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsMultisizeMeasurements = QStringLiteral("paths/standard_measurements")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsTemplates = QStringLiteral("paths/templates")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsLabelTemplate = QStringLiteral("paths/labels")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationOsSeparator = QStringLiteral("configuration/osSeparator")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAutosaveState = QStringLiteral("configuration/autosave/state")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAutosaveTime = QStringLiteral("configuration/autosave/time")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUseModeType = QStringLiteral("configuration/autosave/useModeType")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUseLastExportFormat = QStringLiteral("configuration/autosave/useLastExportFormat")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationExportFormat = QStringLiteral("configuration/autosave/exportFormat")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationSendReportState = QStringLiteral("configuration/send_report/state")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationLocale = QStringLiteral("configuration/locale")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPMSystemCode = QStringLiteral("configuration/pmscode")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUnit = QStringLiteral("configuration/unit")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationConfirmItemDeletion = QStringLiteral("configuration/confirm_item_deletion")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationConfirmFormatRewriting = QStringLiteral("configuration/confirm_format_rewriting")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMoveSuffix = QStringLiteral("configuration/moveSuffix")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationRotateSuffix = QStringLiteral("configuration/rotateSuffix")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMirrorByAxisSuffix = QStringLiteral("configuration/mirrorByAxisSuffix")
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMirrorByLineSuffix = QStringLiteral("configuration/mirrorByLineSuffix")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewToolBarStyle = QStringLiteral("graphicsview/tool_bar_style")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowToolsToolBar = QStringLiteral("graphicsview/showToolsToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowPointToolBar = QStringLiteral("graphicsview/showPointToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowLineToolBar = QStringLiteral("graphicsview/showLineToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowCurveToolBar = QStringLiteral("graphicsview/showCurveToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowArcToolBar = QStringLiteral("graphicsview/showArcToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowOpsToolBar = QStringLiteral("graphicsview/showOpsToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowPieceToolBar = QStringLiteral("graphicsview/showPieceToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowDetailsToolBar = QStringLiteral("graphicsview/showDetailsToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowLayoutToolBar = QStringLiteral("graphicsview/showLayoutToolbar")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowScrollBars = QStringLiteral("graphicsview/showScrollBars")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollBarWidth = QStringLiteral("graphicsview/scrollBarWidth")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollDuration = QStringLiteral("graphicsview/scrollDuration")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollUpdateInterval = QStringLiteral("graphicsview/scrollUpdateInterval")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollSpeedFactor = QStringLiteral("graphicsview/scrollSpeedFactor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPixelDelta = QStringLiteral("graphicsview/pixelDelta")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewAngleDelta = QStringLiteral("graphicsview/angleDelta")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomModKey = QStringLiteral("graphicsview/zoomModKey")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomDoubleClick = QStringLiteral("graphicsview/zoomDoubleClick")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPanActiveSpaceKey = QStringLiteral("graphicsview/panActiveSpaceKey")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomSpeedFactor = QStringLiteral("graphicsview/zoomSpeedFactor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewExportQuality = QStringLiteral("graphicsview/exportQuality")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomRBPositiveColor = QStringLiteral("graphicsview/zoomRBPositiveColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomRBNegativeColor = QStringLiteral("graphicsview/zoomRBNegativeColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameColor = QStringLiteral("graphicsview/pointNameColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameHoverColor = QStringLiteral("graphicsview/pointNameHoverColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewAxisOrginColor = QStringLiteral("graphicsview/axisOrginColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineColor = QStringLiteral("graphicsview/defaultLineColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineWeight = QStringLiteral("graphicsview/defaultLineWeight")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineType = QStringLiteral("graphicsview/defaultLineType")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPrimaryColor = QStringLiteral("graphicsview/primarySupportColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewSecondaryColor = QStringLiteral("graphicsview/secondarySupportColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewTertiaryColor = QStringLiteral("graphicsview/tertiarySupportColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewConstrainValue = QStringLiteral("graphicsview/constrainValue")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewConstrainModKey = QStringLiteral("graphicsview/constrainModKey")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameSize = QStringLiteral("graphicsview/pointNameSize")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewGuiFontSize = QStringLiteral("graphicsview/guiFontSize")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewHidePointNames = QStringLiteral("graphicsview/hidePointNames")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowAxisOrigin = QStringLiteral("graphicsview/showAxisOrigin")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewWireframe = QStringLiteral("graphicsview/wireframe")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowControlPoints = QStringLiteral("graphicsview/showControlPoints")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowAnchorPoints = QStringLiteral("graphicsview/showAnchorPoints")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsUseToolColor = QStringLiteral("graphicsview/useToolColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternUndo = QStringLiteral("pattern/undo")
const QString anonymous_namespace{vcommonsettings.cpp}::settingSelectionSound = QStringLiteral("pattern/selectionSound")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternForbidFlipping = QStringLiteral("pattern/forbidFlipping")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternHideSeamLine = QStringLiteral("pattern/hideMainPath")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchLength = QStringLiteral("pattern/defaultNotchLength")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchWidth = QStringLiteral("pattern/defaultNotchWidth")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchType = QStringLiteral("pattern/defaultNotchType")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchColor = QStringLiteral("pattern/defaultNotchColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingSeamlineNotch = QStringLiteral("pattern/doubleNotch")
const QString anonymous_namespace{vcommonsettings.cpp}::settingSeamAllowanceNotch = QStringLiteral("pattern/showSeamAllowanceNotch")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternDefaultSeamAllowance = QStringLiteral("pattern/defaultSeamAllowance")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamColor = QStringLiteral("pattern/defaultSeamColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamLinetype = QStringLiteral("pattern/defaultSeamLinetype")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamLineweight = QStringLiteral("pattern/defaultSeamLineweight")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutColor = QStringLiteral("pattern/defaultCutColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutLinetype = QStringLiteral("pattern/defaultCutLinetype")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutLineweight = QStringLiteral("pattern/defaultCutLineweight")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalColor = QStringLiteral("pattern/defaultInternalColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalLinetype = QStringLiteral("pattern/defaultInternalLinetype")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalLineweight = QStringLiteral("pattern/defaultInternalLineweight")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutColor = QStringLiteral("pattern/defaultCutoutColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutLinetype = QStringLiteral("pattern/defaultCutoutLinetype")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutLineweight = QStringLiteral("pattern/defaultCutoutLineweight")
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowSeamAllowances = QStringLiteral("pattern/showShowSeamAllowances")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamAllowanceVisibilty = QStringLiteral("pattern/defaultSeamAllowanceVisibilty")
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowGrainlines = QStringLiteral("pattern/showGrainlines")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineVisibilty = QStringLiteral("pattern/defaultGrainlineVisibilty")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineLength = QStringLiteral("pattern/defaultGrainlineLength")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineColor = QStringLiteral("pattern/defaultGrainlineColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineLineweight = QStringLiteral("pattern/defaultGrainlineLineweight")
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowLabels = QStringLiteral("pattern/showLabels")
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowPatternLabels = QStringLiteral("pattern/showPatternLabels")
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowPieceLabels = QStringLiteral("pattern/showPieceLabels")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelWidth = QStringLiteral("pattern/defaultLabelWidth")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelHeight = QStringLiteral("pattern/defaultLabelHeight")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelColor = QStringLiteral("pattern/defaultLabelColor")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultPatternTemplate = QStringLiteral("pattern/defaultPatternTemplate")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultPieceTemplate = QStringLiteral("pattern/defaultPieceTemplate")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternLabelFont = QStringLiteral("pattern/labelFont")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternGuiFont = QStringLiteral("pattern/guiFont")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternPointNameFont = QStringLiteral("pattern/pointNameFont")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralRecentFileList = QStringLiteral("recentFileList")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralRestoreFileList = QStringLiteral("restoreFileList")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralGeometry = QStringLiteral("geometry")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralWindowState = QStringLiteral("windowState")
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralToolbarsState = QStringLiteral("toolbarsState")
const QString anonymous_namespace{vcommonsettings.cpp}::settingPreferenceDialogSize = QStringLiteral("preferenceDialogSize")
const QString anonymous_namespace{vcommonsettings.cpp}::settingToolSeamAllowanceDialogSize = QStringLiteral("toolSeamAllowanceDialogSize")
const QString anonymous_namespace{vcommonsettings.cpp}::settingIncrementsDialogSize = QStringLiteral("toolIncrementsDialogSize")
const QString anonymous_namespace{vcommonsettings.cpp}::settingFormulaWizardDialogSize = QStringLiteral("formulaWizardDialogSize")
const QString anonymous_namespace{vcommonsettings.cpp}::settingLatestSkippedVersion = QStringLiteral("lastestSkippedVersion")
const QString anonymous_namespace{vcommonsettings.cpp}::settingDateOfLastRemind = QStringLiteral("dateOfLastRemind")
const QString anonymous_namespace{vcommonsettings.cpp}::settingCSVWithHeader = QStringLiteral("csv/withHeader")
const QString anonymous_namespace{vcommonsettings.cpp}::settingCSVCodec = QStringLiteral("csv/withCodec")
const QString anonymous_namespace{vcommonsettings.cpp}::settingCSVSeparator = QStringLiteral("csv/withSeparator")
const QString anonymous_namespace{vcommonsettings.cpp}::settingLabelDateFormat = QStringLiteral("label/dateFormat")
const QString anonymous_namespace{vcommonsettings.cpp}::settingLabelUserDateFormats = QStringLiteral("label/userDateFormats")
const QString anonymous_namespace{vcommonsettings.cpp}::settingLabelTimeFormat = QStringLiteral("label/timeFormat")
const QString anonymous_namespace{vcommonsettings.cpp}::settingLabelUserTimeFormats = QStringLiteral("label/userTimeFormats")
int anonymous_namespace{vcommonsettings.cpp}::pointNameSize = 0
static const QString commonIniFilename = QStringLiteral("common")
Variable Documentation
commonIniFilename
const QString commonIniFilename = QStringLiteral("common") static
Definition at line 227 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetCSVCodec(), VCommonSettings::GetCSVSeparator(), VCommonSettings::GetCSVWithHeader(), VCommonSettings::GetDateOfLastRemind(), VCommonSettings::GetLatestSkippedVersion(), VCommonSettings::GetPathIndividualMeasurements(), VCommonSettings::GetPathMultisizeMeasurements(), VCommonSettings::GetPathTemplate(), VCommonSettings::SetCSVCodec(), VCommonSettings::SetCSVSeparator(), VCommonSettings::SetCSVWithHeader(), VCommonSettings::SetDateOfLastRemind(), VCommonSettings::SetLatestSkippedVersion(), VCommonSettings::SetPathIndividualMeasurements(), VCommonSettings::SetPathMultisizeMeasurements(), and VCommonSettings::SetPathTemplate().