Seamly2D: SeamlyMeWelcomeDialog Class Reference
SeamlyMeWelcomeDialog Class Reference
#include <me_welcome_dialog.h>
Public Member Functions
SeamlyMeWelcomeDialog (QWidget *parent=nullptr)
~SeamlyMeWelcomeDialog ()
void apply ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
void seperatorChanged ()
Private Member Functions
void initUnits (const MeasurementsType &type)
Private Attributes
Ui::SeamlyMeWelcomeDialog * ui
bool m_langChanged
VSeamlyMeSettings * settings
Detailed Description
Definition at line 38 of file me_welcome_dialog.h.
Constructor & Destructor Documentation
SeamlyMeWelcomeDialog()
SeamlyMeWelcomeDialog::SeamlyMeWelcomeDialog (QWidget * parent = nullptr) explicit
Definition at line 37 of file me_welcome_dialog.cpp.
References apply(), VCommonSettings::GetOsSeparator(), VCommonSettings::getShowWelcome(), Individual, InitLanguages(), initUnits(), SCASSERT, seperatorChanged(), settings, and ui.
~SeamlyMeWelcomeDialog()
SeamlyMeWelcomeDialog::~SeamlyMeWelcomeDialog ()
Definition at line 70 of file me_welcome_dialog.cpp.
References ui.
Member Function Documentation
apply()
void SeamlyMeWelcomeDialog::apply ()
Definition at line 77 of file me_welcome_dialog.cpp.
References VCommonSettings::GetOsSeparator(), m_langChanged, VCommonSettings::SetLocale(), VCommonSettings::SetOsSeparator(), VCommonSettings::setShowWelcome(), settings, VCommonSettings::SetUnit(), and ui.
Referenced by SeamlyMeWelcomeDialog().
changeEvent()
void SeamlyMeWelcomeDialog::changeEvent (QEvent * event) protected virtual
Definition at line 97 of file me_welcome_dialog.cpp.
References ui.
initUnits()
void SeamlyMeWelcomeDialog::initUnits (const MeasurementsType & type) private
Definition at line 123 of file me_welcome_dialog.cpp.
References VCommonSettings::GetUnit(), settings, ui, unitCM, unitINCH, and unitMM.
Referenced by SeamlyMeWelcomeDialog().
seperatorChanged()
void SeamlyMeWelcomeDialog::seperatorChanged () protected
Definition at line 111 of file me_welcome_dialog.cpp.
References ui.
Referenced by SeamlyMeWelcomeDialog().
Member Data Documentation
m_langChanged
bool SeamlyMeWelcomeDialog::m_langChanged private
Definition at line 54 of file me_welcome_dialog.h.
Referenced by apply().
settings
VSeamlyMeSettings* SeamlyMeWelcomeDialog::settings private
Definition at line 55 of file me_welcome_dialog.h.
Referenced by apply(), initUnits(), and SeamlyMeWelcomeDialog().
ui
Ui::SeamlyMeWelcomeDialog* SeamlyMeWelcomeDialog::ui private
Definition at line 53 of file me_welcome_dialog.h.
Referenced by apply(), changeEvent(), initUnits(), SeamlyMeWelcomeDialog(), seperatorChanged(), and ~SeamlyMeWelcomeDialog().
The documentation for this class was generated from the following files:
src/app/seamlyme/dialogs/me_welcome_dialog.h
src/app/seamlyme/dialogs/me_welcome_dialog.cpp