Seamly2D: RegularExpression Class Reference
RegularExpression Class Reference
#include <RegularExpression.hpp>
Classes
class Context
Public Member Functions
Matching methods
bool matches (const char *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
void allMatches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, RefVectorOf< Match > *subEx, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
void allMatches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, RefVectorOf< Match > *subEx, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
bool matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
void allMatches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, RefVectorOf< Match > *subEx, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
Tokenize methods
RefArrayVectorOf< XMLCh > * tokenize (const char *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const XMLCh *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const char *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const XMLCh *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const char *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const XMLCh *const matchString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
RefArrayVectorOf< XMLCh > * tokenize (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
Replace methods
XMLCh * replace (const char *const matchString, const char *const replaceString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const char *const matchString, const char *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const XMLCh *const matchString, const XMLCh *const replaceString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const XMLCh *const matchString, const XMLCh *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const char *const matchString, const char *const replaceString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const char *const matchString, const char *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const XMLCh *const matchString, const XMLCh *const replaceString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const XMLCh *const matchString, const XMLCh *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const char *const matchString, const char *const replaceString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const char *const matchString, const char *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const XMLCh *const matchString, const XMLCh *const replaceString, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
XMLCh * replace (const XMLCh *const matchString, const XMLCh *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager) const
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Static Public Member Functions
Public helper methods
static int getOptionValue (const XMLCh ch)
static bool isSet (const int options, const int flag)
static int getOptionValue (const XMLCh ch)
static bool isSet (const int options, const int flag)
static int getOptionValue (const XMLCh ch)
static bool isSet (const int options, const int flag)
Constructors and destructor
enum wordType {
wordTypeIgnore = 0 , wordTypeLetter = 1 , wordTypeOther = 2 , wordTypeIgnore = 0 ,
wordTypeLetter = 1 , wordTypeOther = 2 , wordTypeIgnore = 0 , wordTypeLetter = 1 ,
wordTypeOther = 2
}
enum wordType {
wordTypeIgnore = 0 , wordTypeLetter = 1 , wordTypeOther = 2 , wordTypeIgnore = 0 ,
wordTypeLetter = 1 , wordTypeOther = 2 , wordTypeIgnore = 0 , wordTypeLetter = 1 ,
wordTypeOther = 2
}
enum wordType {
wordTypeIgnore = 0 , wordTypeLetter = 1 , wordTypeOther = 2 , wordTypeIgnore = 0 ,
wordTypeLetter = 1 , wordTypeOther = 2 , wordTypeIgnore = 0 , wordTypeLetter = 1 ,
wordTypeOther = 2
}
static const unsigned int IGNORE_CASE
static const unsigned int SINGLE_LINE
static const unsigned int MULTIPLE_LINE
static const unsigned int EXTENDED_COMMENT
static const unsigned int PROHIBIT_HEAD_CHARACTER_OPTIMIZATION
static const unsigned int PROHIBIT_FIXED_STRING_OPTIMIZATION
static const unsigned int XMLSCHEMA_MODE
RegularExpression (const char *const pattern, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const char *const pattern, const char *const options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const XMLCh *const pattern, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const XMLCh *const pattern, const XMLCh *const options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~RegularExpression ()
RegularExpression (const char *const pattern, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const char *const pattern, const char *const options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const XMLCh *const pattern, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const XMLCh *const pattern, const XMLCh *const options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~RegularExpression ()
RegularExpression (const char *const pattern, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const char *const pattern, const char *const options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const XMLCh *const pattern, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RegularExpression (const XMLCh *const pattern, const XMLCh *const options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~RegularExpression ()
Static initilize and cleanup methods
bool fHasBackReferences
bool fFixedStringOnly
int fNoGroups
XMLSize_t fMinLength
unsigned int fNoClosures
unsigned int fOptions
const BMPattern * fBMPattern
XMLCh * fPattern
XMLCh * fFixedString
const Op * fOperations
Token * fTokenTree
RangeToken * fFirstChar
OpFactory fOpFactory
TokenFactory * fTokenFactory
MemoryManager * fMemoryManager
static RangeToken * fWordRange
static void staticInitialize (MemoryManager *memoryManager)
static void staticCleanup ()
static void staticInitialize (MemoryManager *memoryManager)
static void staticCleanup ()
static void staticInitialize (MemoryManager *memoryManager)
static void staticCleanup ()
virtual RegxParser * getRegexParser (const int options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void cleanUp ()
void setPattern (const XMLCh *const pattern, const XMLCh *const options=0)
RegularExpression (const RegularExpression &)
RegularExpression & operator= (const RegularExpression &)
void prepare ()
int parseOptions (const XMLCh *const options)
int match (Context *const context, const Op *const operations, XMLSize_t offset) const
bool matchIgnoreCase (const XMLInt32 ch1, const XMLInt32 ch2) const
bool matchChar (Context *const context, const XMLInt32 ch, XMLSize_t &offset, const bool ignoreCase) const
bool matchDot (Context *const context, XMLSize_t &offset) const
bool matchRange (Context *const context, const Op *const op, XMLSize_t &offset, const bool ignoreCase) const
bool matchAnchor (Context *const context, const XMLInt32 ch, const XMLSize_t offset) const
bool matchBackReference (Context *const context, const XMLInt32 ch, XMLSize_t &offset, const bool ignoreCase) const
bool matchString (Context *const context, const XMLCh *const literal, XMLSize_t &offset, const bool ignoreCase) const
int matchUnion (Context *const context, const Op *const op, XMLSize_t offset) const
int matchCapture (Context *const context, const Op *const op, XMLSize_t offset) const
void subInExp (const XMLCh *const repString, const XMLCh *const origString, const Match *subEx, XMLBuffer &result, MemoryManager *const manager) const
void compile (const Token *const token)
Op * compile (const Token *const token, Op *const next, const bool reverse)
Op * compileUnion (const Token *const token, Op *const next, const bool reverse)
Op * compileParenthesis (const Token *const token, Op *const next, const bool reverse)
Op * compileConcat (const Token *const token, Op *const next, const bool reverse)
Op * compileClosure (const Token *const token, Op *const next, const bool reverse, const Token::tokType tkType)
bool doTokenOverlap (const Op *op, Token *token)
virtual RegxParser * getRegexParser (const int options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void cleanUp ()
void setPattern (const XMLCh *const pattern, const XMLCh *const options=0)
RegularExpression (const RegularExpression &)
RegularExpression & operator= (const RegularExpression &)
void prepare ()
int parseOptions (const XMLCh *const options)
int match (Context *const context, const Op *const operations, XMLSize_t offset) const
bool matchIgnoreCase (const XMLInt32 ch1, const XMLInt32 ch2) const
bool matchChar (Context *const context, const XMLInt32 ch, XMLSize_t &offset, const bool ignoreCase) const
bool matchDot (Context *const context, XMLSize_t &offset) const
bool matchRange (Context *const context, const Op *const op, XMLSize_t &offset, const bool ignoreCase) const
bool matchAnchor (Context *const context, const XMLInt32 ch, const XMLSize_t offset) const
bool matchBackReference (Context *const context, const XMLInt32 ch, XMLSize_t &offset, const bool ignoreCase) const
bool matchString (Context *const context, const XMLCh *const literal, XMLSize_t &offset, const bool ignoreCase) const
int matchUnion (Context *const context, const Op *const op, XMLSize_t offset) const
int matchCapture (Context *const context, const Op *const op, XMLSize_t offset) const
void subInExp (const XMLCh *const repString, const XMLCh *const origString, const Match *subEx, XMLBuffer &result, MemoryManager *const manager) const
void compile (const Token *const token)
Op * compile (const Token *const token, Op *const next, const bool reverse)
Op * compileUnion (const Token *const token, Op *const next, const bool reverse)
Op * compileParenthesis (const Token *const token, Op *const next, const bool reverse)
Op * compileConcat (const Token *const token, Op *const next, const bool reverse)
Op * compileClosure (const Token *const token, Op *const next, const bool reverse, const Token::tokType tkType)
bool doTokenOverlap (const Op *op, Token *token)
virtual RegxParser * getRegexParser (const int options, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void cleanUp ()
void setPattern (const XMLCh *const pattern, const XMLCh *const options=0)
RegularExpression (const RegularExpression &)
RegularExpression & operator= (const RegularExpression &)
void prepare ()
int parseOptions (const XMLCh *const options)
int match (Context *const context, const Op *const operations, XMLSize_t offset) const
bool matchIgnoreCase (const XMLInt32 ch1, const XMLInt32 ch2) const
bool matchChar (Context *const context, const XMLInt32 ch, XMLSize_t &offset, const bool ignoreCase) const
bool matchDot (Context *const context, XMLSize_t &offset) const
bool matchRange (Context *const context, const Op *const op, XMLSize_t &offset, const bool ignoreCase) const
bool matchAnchor (Context *const context, const XMLInt32 ch, const XMLSize_t offset) const
bool matchBackReference (Context *const context, const XMLInt32 ch, XMLSize_t &offset, const bool ignoreCase) const
bool matchString (Context *const context, const XMLCh *const literal, XMLSize_t &offset, const bool ignoreCase) const
int matchUnion (Context *const context, const Op *const op, XMLSize_t offset) const
int matchCapture (Context *const context, const Op *const op, XMLSize_t offset) const
void subInExp (const XMLCh *const repString, const XMLCh *const origString, const Match *subEx, XMLBuffer &result, MemoryManager *const manager) const
void compile (const Token *const token)
Op * compile (const Token *const token, Op *const next, const bool reverse)
Op * compileUnion (const Token *const token, Op *const next, const bool reverse)
Op * compileParenthesis (const Token *const token, Op *const next, const bool reverse)
Op * compileConcat (const Token *const token, Op *const next, const bool reverse)
Op * compileClosure (const Token *const token, Op *const next, const bool reverse, const Token::tokType tkType)
bool doTokenOverlap (const Op *op, Token *token)
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
The RegularExpression class represents a parsed executable regular expression. This class is thread safe. Two similar regular expression syntaxes are supported:
The XPath 2.0 / XQuery regular expression syntax.
The XML Schema regular expression syntax.
XPath 2.0 regular expression syntax is used unless the "X" option is specified during construction.
Options can be specified during construction to change the way that the regular expression is handled. Options are specified by a string consisting of any number of the following characters:
Character Meaning
i Ignore case when matching the regular expression.
m Multi-line mode. The meta characters "^" and "$" will match the beginning and end of lines.
s Single-line mode. The meta character "." will match a newline character.
x Allow extended comments.
F Prohibit the fixed string optimization.
H Prohibit the head character optimization.
X Parse the regular expression according to the XML Schema regular expression syntax.
Definition at line 100 of file RegularExpression.hpp.
Member Enumeration Documentation
wordType [1/3]
enum RegularExpression::wordType
Enumerator
wordTypeIgnore
wordTypeLetter
wordTypeOther
wordTypeIgnore
wordTypeLetter
wordTypeOther
wordTypeIgnore
wordTypeLetter
wordTypeOther
Definition at line 172 of file RegularExpression.hpp.
wordType [2/3]
enum RegularExpression::wordType
Enumerator
wordTypeIgnore
wordTypeLetter
wordTypeOther
wordTypeIgnore
wordTypeLetter
wordTypeOther
wordTypeIgnore
wordTypeLetter
wordTypeOther
Definition at line 172 of file RegularExpression.hpp.
wordType [3/3]
enum RegularExpression::wordType
Enumerator
wordTypeIgnore
wordTypeLetter
wordTypeOther
wordTypeIgnore
wordTypeLetter
wordTypeOther
wordTypeIgnore
wordTypeLetter
wordTypeOther
Definition at line 172 of file RegularExpression.hpp.
Constructor & Destructor Documentation
RegularExpression() [1/15]
RegularExpression::RegularExpression (const char *const pattern, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression.
Parameters
pattern the regular expression in the local code page
manager the memory manager to use
RegularExpression() [2/15]
RegularExpression::RegularExpression (const char *const pattern, const char *const options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression using the options specified.
Parameters
pattern the regular expression in the local code page
options the options string in the local code page
manager the memory manager to use
RegularExpression() [3/15]
RegularExpression::RegularExpression (const XMLCh *const pattern, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression.
Parameters
pattern the regular expression
manager the memory manager to use
RegularExpression() [4/15]
RegularExpression::RegularExpression (const XMLCh *const pattern, const XMLCh *const options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression using the options specified.
Parameters
pattern the regular expression
options the options string
manager the memory manager to use
~RegularExpression() [1/3]
virtual RegularExpression::~RegularExpression () virtual
RegularExpression() [5/15]
RegularExpression::RegularExpression (const RegularExpression &) protected
RegularExpression() [6/15]
RegularExpression::RegularExpression (const char *const pattern, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression.
Parameters
pattern the regular expression in the local code page
manager the memory manager to use
RegularExpression() [7/15]
RegularExpression::RegularExpression (const char *const pattern, const char *const options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression using the options specified.
Parameters
pattern the regular expression in the local code page
options the options string in the local code page
manager the memory manager to use
RegularExpression() [8/15]
RegularExpression::RegularExpression (const XMLCh *const pattern, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression.
Parameters
pattern the regular expression
manager the memory manager to use
RegularExpression() [9/15]
RegularExpression::RegularExpression (const XMLCh *const pattern, const XMLCh *const options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression using the options specified.
Parameters
pattern the regular expression
options the options string
manager the memory manager to use
~RegularExpression() [2/3]
virtual RegularExpression::~RegularExpression () virtual
RegularExpression() [10/15]
RegularExpression::RegularExpression (const RegularExpression &) protected
RegularExpression() [11/15]
RegularExpression::RegularExpression (const char *const pattern, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression.
Parameters
pattern the regular expression in the local code page
manager the memory manager to use
RegularExpression() [12/15]
RegularExpression::RegularExpression (const char *const pattern, const char *const options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression using the options specified.
Parameters
pattern the regular expression in the local code page
options the options string in the local code page
manager the memory manager to use
RegularExpression() [13/15]
RegularExpression::RegularExpression (const XMLCh *const pattern, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression.
Parameters
pattern the regular expression
manager the memory manager to use
RegularExpression() [14/15]
RegularExpression::RegularExpression (const XMLCh *const pattern, const XMLCh *const options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Parses the given regular expression using the options specified.
Parameters
pattern the regular expression
options the options string
manager the memory manager to use
~RegularExpression() [3/3]
virtual RegularExpression::~RegularExpression () virtual
RegularExpression() [15/15]
RegularExpression::RegularExpression (const RegularExpression &) protected
Member Function Documentation
allMatches() [1/3]
void RegularExpression::allMatches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, RefVectorOf< Match > * subEx, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression. The subEx vector is populated with the details for every non-overlapping occurrence of a match in the string.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
subEx a RefVectorOf Match objects, populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
allMatches() [2/3]
void RegularExpression::allMatches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, RefVectorOf< Match > * subEx, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression. The subEx vector is populated with the details for every non-overlapping occurrence of a match in the string.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
subEx a RefVectorOf Match objects, populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
allMatches() [3/3]
void RegularExpression::allMatches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, RefVectorOf< Match > * subEx, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression. The subEx vector is populated with the details for every non-overlapping occurrence of a match in the string.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
subEx a RefVectorOf Match objects, populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
cleanUp() [1/3]
void RegularExpression::cleanUp () inline protected
Definition at line 613 of file RegularExpression.hpp.
References MemoryManager::deallocate(), fBMPattern, fFixedString, fMemoryManager, fPattern, and fTokenFactory.
cleanUp() [2/3]
void RegularExpression::cleanUp () protected
cleanUp() [3/3]
void RegularExpression::cleanUp () protected
compile() [1/6]
void RegularExpression::compile (const Token *const token) protected
Converts a token tree into an operation tree
Referenced by compileClosure(), compileConcat(), compileParenthesis(), and compileUnion().
compile() [2/6]
void RegularExpression::compile (const Token *const token) protected
Converts a token tree into an operation tree
compile() [3/6]
void RegularExpression::compile (const Token *const token) protected
Converts a token tree into an operation tree
compile() [4/6]
Op* RegularExpression::compile (const Token *const token, Op *const next, const bool reverse) protected
compile() [5/6]
Op* RegularExpression::compile (const Token *const token, Op *const next, const bool reverse) protected
compile() [6/6]
Op* RegularExpression::compile (const Token *const token, Op *const next, const bool reverse) protected
compileClosure() [1/3]
Op * RegularExpression::compileClosure (const Token *const token, Op *const next, const bool reverse, const Token::tokType tkType) inline protected
Definition at line 692 of file RegularExpression.hpp.
References compile(), OpFactory::createClosureOp(), OpFactory::createNonGreedyClosureOp(), OpFactory::createQuestionOp(), doTokenOverlap(), fNoClosures, fOpFactory, Token::getChild(), Token::getMax(), Token::getMin(), Token::getMinLength(), Op::O_FINITE_CLOSURE, Op::O_FINITE_NONGREEDYCLOSURE, ChildOp::setChild(), Op::setNextOp(), Op::setOpType(), and Token::T_NONGREEDYCLOSURE.
compileClosure() [2/3]
Op* RegularExpression::compileClosure (const Token *const token, Op *const next, const bool reverse, const Token::tokType tkType) protected
compileClosure() [3/3]
Op* RegularExpression::compileClosure (const Token *const token, Op *const next, const bool reverse, const Token::tokType tkType) protected
compileConcat() [1/3]
Op * RegularExpression::compileConcat (const Token *const token, Op *const next, const bool reverse) inline protected
Definition at line 669 of file RegularExpression.hpp.
References compile(), Token::getChild(), and Token::size().
compileConcat() [2/3]
Op* RegularExpression::compileConcat (const Token *const token, Op *const next, const bool reverse) protected
compileConcat() [3/3]
Op* RegularExpression::compileConcat (const Token *const token, Op *const next, const bool reverse) protected
compileParenthesis() [1/3]
Op * RegularExpression::compileParenthesis (const Token *const token, Op *const next, const bool reverse) inline protected
Definition at line 646 of file RegularExpression.hpp.
References compile(), OpFactory::createCaptureOp(), fOpFactory, Token::getChild(), and Token::getNoParen().
compileParenthesis() [2/3]
Op* RegularExpression::compileParenthesis (const Token *const token, Op *const next, const bool reverse) protected
compileParenthesis() [3/3]
Op* RegularExpression::compileParenthesis (const Token *const token, Op *const next, const bool reverse) protected
compileUnion() [1/3]
Op * RegularExpression::compileUnion (const Token *const token, Op *const next, const bool reverse) inline protected
Helper methods used by compile
Definition at line 630 of file RegularExpression.hpp.
References UnionOp::addElement(), compile(), OpFactory::createUnionOp(), fOpFactory, Token::getChild(), and Token::size().
compileUnion() [2/3]
Op* RegularExpression::compileUnion (const Token *const token, Op *const next, const bool reverse) protected
Helper methods used by compile
compileUnion() [3/3]
Op* RegularExpression::compileUnion (const Token *const token, Op *const next, const bool reverse) protected
Helper methods used by compile
doTokenOverlap() [1/3]
bool RegularExpression::doTokenOverlap (const Op * op, Token * token) protected
Referenced by compileClosure().
doTokenOverlap() [2/3]
bool RegularExpression::doTokenOverlap (const Op * op, Token * token) protected
doTokenOverlap() [3/3]
bool RegularExpression::doTokenOverlap (const Op * op, Token * token) protected
getOptionValue() [1/3]
static int RegularExpression::getOptionValue (const XMLCh ch) static
getOptionValue() [2/3]
static int RegularExpression::getOptionValue (const XMLCh ch) static
getOptionValue() [3/3]
static int RegularExpression::getOptionValue (const XMLCh ch) static
getRegexParser() [1/3]
virtual RegxParser* RegularExpression::getRegexParser (const int options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected virtual
getRegexParser() [2/3]
virtual RegxParser* RegularExpression::getRegexParser (const int options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected virtual
getRegexParser() [3/3]
virtual RegxParser* RegularExpression::getRegexParser (const int options, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected virtual
isSet() [1/3]
bool RegularExpression::isSet (const int options, const int flag) inline static
Definition at line 624 of file RegularExpression.hpp.
isSet() [2/3]
static bool RegularExpression::isSet (const int options, const int flag) static
isSet() [3/3]
static bool RegularExpression::isSet (const int options, const int flag) static
match() [1/3]
int RegularExpression::match (Context *const context, const Op *const operations, XMLSize_t offset) const protected
Matching helpers
match() [2/3]
int RegularExpression::match (Context *const context, const Op *const operations, XMLSize_t offset) const protected
Matching helpers
match() [3/3]
int RegularExpression::match (Context *const context, const Op *const operations, XMLSize_t offset) const protected
Matching helpers
matchAnchor() [1/3]
bool RegularExpression::matchAnchor (Context *const context, const XMLInt32 ch, const XMLSize_t offset) const protected
matchAnchor() [2/3]
bool RegularExpression::matchAnchor (Context *const context, const XMLInt32 ch, const XMLSize_t offset) const protected
matchAnchor() [3/3]
bool RegularExpression::matchAnchor (Context *const context, const XMLInt32 ch, const XMLSize_t offset) const protected
matchBackReference() [1/3]
bool RegularExpression::matchBackReference (Context *const context, const XMLInt32 ch, XMLSize_t & offset, const bool ignoreCase) const protected
matchBackReference() [2/3]
bool RegularExpression::matchBackReference (Context *const context, const XMLInt32 ch, XMLSize_t & offset, const bool ignoreCase) const protected
matchBackReference() [3/3]
bool RegularExpression::matchBackReference (Context *const context, const XMLInt32 ch, XMLSize_t & offset, const bool ignoreCase) const protected
matchCapture() [1/3]
int RegularExpression::matchCapture (Context *const context, const Op *const op, XMLSize_t offset) const protected
matchCapture() [2/3]
int RegularExpression::matchCapture (Context *const context, const Op *const op, XMLSize_t offset) const protected
matchCapture() [3/3]
int RegularExpression::matchCapture (Context *const context, const Op *const op, XMLSize_t offset) const protected
matchChar() [1/3]
bool RegularExpression::matchChar (Context *const context, const XMLInt32 ch, XMLSize_t & offset, const bool ignoreCase) const protected
Helper methods used by match(Context* ...)
matchChar() [2/3]
bool RegularExpression::matchChar (Context *const context, const XMLInt32 ch, XMLSize_t & offset, const bool ignoreCase) const protected
Helper methods used by match(Context* ...)
matchChar() [3/3]
bool RegularExpression::matchChar (Context *const context, const XMLInt32 ch, XMLSize_t & offset, const bool ignoreCase) const protected
Helper methods used by match(Context* ...)
matchDot() [1/3]
bool RegularExpression::matchDot (Context *const context, XMLSize_t & offset) const protected
matchDot() [2/3]
bool RegularExpression::matchDot (Context *const context, XMLSize_t & offset) const protected
matchDot() [3/3]
bool RegularExpression::matchDot (Context *const context, XMLSize_t & offset) const protected
matches() [1/24]
bool RegularExpression::matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [2/24]
bool RegularExpression::matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [3/24]
bool RegularExpression::matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [4/24]
bool RegularExpression::matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [5/24]
bool RegularExpression::matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [6/24]
bool RegularExpression::matches (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [7/24]
bool RegularExpression::matches (const char *const matchString, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [8/24]
bool RegularExpression::matches (const char *const matchString, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [9/24]
bool RegularExpression::matches (const char *const matchString, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [10/24]
bool RegularExpression::matches (const char *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [11/24]
bool RegularExpression::matches (const char *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [12/24]
bool RegularExpression::matches (const char *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match in the local code page
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [13/24]
bool RegularExpression::matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [14/24]
bool RegularExpression::matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [15/24]
bool RegularExpression::matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [16/24]
bool RegularExpression::matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [17/24]
bool RegularExpression::matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [18/24]
bool RegularExpression::matches (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given string between the specified start and end offsets against the regular expression, returning true if successful.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [19/24]
bool RegularExpression::matches (const XMLCh *const matchString, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [20/24]
bool RegularExpression::matches (const XMLCh *const matchString, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [21/24]
bool RegularExpression::matches (const XMLCh *const matchString, Match *const pMatch, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match
pMatch a Match object, which will be populated with the offsets for the regular expression match and sub-matches.
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [22/24]
bool RegularExpression::matches (const XMLCh *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [23/24]
bool RegularExpression::matches (const XMLCh *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matches() [24/24]
bool RegularExpression::matches (const XMLCh *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tries to match the given null terminated string against the regular expression, returning true if successful.
Parameters
matchString the string to match
manager the memory manager to use
Returns
Whether the string matched the regular expression or not.
matchIgnoreCase() [1/3]
bool RegularExpression::matchIgnoreCase (const XMLInt32 ch1, const XMLInt32 ch2) const protected
matchIgnoreCase() [2/3]
bool RegularExpression::matchIgnoreCase (const XMLInt32 ch1, const XMLInt32 ch2) const protected
matchIgnoreCase() [3/3]
bool RegularExpression::matchIgnoreCase (const XMLInt32 ch1, const XMLInt32 ch2) const protected
matchRange() [1/3]
bool RegularExpression::matchRange (Context *const context, const Op *const op, XMLSize_t & offset, const bool ignoreCase) const protected
matchRange() [2/3]
bool RegularExpression::matchRange (Context *const context, const Op *const op, XMLSize_t & offset, const bool ignoreCase) const protected
matchRange() [3/3]
bool RegularExpression::matchRange (Context *const context, const Op *const op, XMLSize_t & offset, const bool ignoreCase) const protected
matchString() [1/3]
bool RegularExpression::matchString (Context *const context, const XMLCh *const literal, XMLSize_t & offset, const bool ignoreCase) const protected
matchString() [2/3]
bool RegularExpression::matchString (Context *const context, const XMLCh *const literal, XMLSize_t & offset, const bool ignoreCase) const protected
matchString() [3/3]
bool RegularExpression::matchString (Context *const context, const XMLCh *const literal, XMLSize_t & offset, const bool ignoreCase) const protected
matchUnion() [1/3]
int RegularExpression::matchUnion (Context *const context, const Op *const op, XMLSize_t offset) const protected
matchUnion() [2/3]
int RegularExpression::matchUnion (Context *const context, const Op *const op, XMLSize_t offset) const protected
matchUnion() [3/3]
int RegularExpression::matchUnion (Context *const context, const Op *const op, XMLSize_t offset) const protected
operator=() [1/3]
RegularExpression& RegularExpression::operator= (const RegularExpression &) protected
operator=() [2/3]
RegularExpression& RegularExpression::operator= (const RegularExpression &) protected
operator=() [3/3]
RegularExpression& RegularExpression::operator= (const RegularExpression &) protected
parseOptions() [1/3]
int RegularExpression::parseOptions (const XMLCh *const options) protected
parseOptions() [2/3]
int RegularExpression::parseOptions (const XMLCh *const options) protected
parseOptions() [3/3]
int RegularExpression::parseOptions (const XMLCh *const options) protected
prepare() [1/3]
void RegularExpression::prepare () protected
prepare() [2/3]
void RegularExpression::prepare () protected
prepare() [3/3]
void RegularExpression::prepare () protected
replace() [1/12]
XMLCh* RegularExpression::replace (const char *const matchString, const char *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given string between the specified start and end offsets, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match in the local code page
replaceString the string to replace in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [2/12]
XMLCh* RegularExpression::replace (const char *const matchString, const char *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given string between the specified start and end offsets, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match in the local code page
replaceString the string to replace in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [3/12]
XMLCh* RegularExpression::replace (const char *const matchString, const char *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given string between the specified start and end offsets, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match in the local code page
replaceString the string to replace in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [4/12]
XMLCh* RegularExpression::replace (const char *const matchString, const char *const replaceString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given null terminated string, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match in the local code page
replaceString the string to replace in the local code page
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [5/12]
XMLCh* RegularExpression::replace (const char *const matchString, const char *const replaceString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given null terminated string, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match in the local code page
replaceString the string to replace in the local code page
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [6/12]
XMLCh* RegularExpression::replace (const char *const matchString, const char *const replaceString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given null terminated string, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match in the local code page
replaceString the string to replace in the local code page
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [7/12]
XMLCh* RegularExpression::replace (const XMLCh *const matchString, const XMLCh *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given string between the specified start and end offsets, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match
replaceString the string to replace
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [8/12]
XMLCh* RegularExpression::replace (const XMLCh *const matchString, const XMLCh *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given string between the specified start and end offsets, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match
replaceString the string to replace
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [9/12]
XMLCh* RegularExpression::replace (const XMLCh *const matchString, const XMLCh *const replaceString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given string between the specified start and end offsets, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match
replaceString the string to replace
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [10/12]
XMLCh* RegularExpression::replace (const XMLCh *const matchString, const XMLCh *const replaceString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given null terminated string, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match
replaceString the string to replace
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [11/12]
XMLCh* RegularExpression::replace (const XMLCh *const matchString, const XMLCh *const replaceString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given null terminated string, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match
replaceString the string to replace
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
replace() [12/12]
XMLCh* RegularExpression::replace (const XMLCh *const matchString, const XMLCh *const replaceString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Performs a search and replace on the given null terminated string, replacing any substring that matches the regular expression with a string derived from the replacement string.
Parameters
matchString the string to match
replaceString the string to replace
manager the memory manager to use
Returns
The resulting string allocated using the given MemoryManager. The caller owns the string that is returned, and is responsible for deleting it.
setPattern() [1/3]
void RegularExpression::setPattern (const XMLCh *const pattern, const XMLCh *const options = 0) protected
setPattern() [2/3]
void RegularExpression::setPattern (const XMLCh *const pattern, const XMLCh *const options = 0) protected
setPattern() [3/3]
void RegularExpression::setPattern (const XMLCh *const pattern, const XMLCh *const options = 0) protected
staticCleanup() [1/3]
void RegularExpression::staticCleanup () inline static
Definition at line 605 of file RegularExpression.hpp.
References fWordRange.
staticCleanup() [2/3]
static void RegularExpression::staticCleanup () static
staticCleanup() [3/3]
static void RegularExpression::staticCleanup () static
staticInitialize() [1/3]
static void RegularExpression::staticInitialize (MemoryManager * memoryManager) static
staticInitialize() [2/3]
static void RegularExpression::staticInitialize (MemoryManager * memoryManager) static
staticInitialize() [3/3]
static void RegularExpression::staticInitialize (MemoryManager * memoryManager) static
subInExp() [1/3]
void RegularExpression::subInExp (const XMLCh *const repString, const XMLCh *const origString, const Match * subEx, XMLBuffer & result, MemoryManager *const manager) const protected
Replace helpers
subInExp() [2/3]
void RegularExpression::subInExp (const XMLCh *const repString, const XMLCh *const origString, const Match * subEx, XMLBuffer & result, MemoryManager *const manager) const protected
Replace helpers
subInExp() [3/3]
void RegularExpression::subInExp (const XMLCh *const repString, const XMLCh *const origString, const Match * subEx, XMLBuffer & result, MemoryManager *const manager) const protected
Replace helpers
tokenize() [1/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the string between the specified start and end offsets according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [2/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the string between the specified start and end offsets according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [3/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const char *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the string between the specified start and end offsets according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match in the local code page
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [4/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const char *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the null terminated string according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match in the local code page
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [5/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const char *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the null terminated string according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match in the local code page
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [6/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const char *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the null terminated string according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match in the local code page
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [7/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the string between the specified start and end offsets according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [8/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the string between the specified start and end offsets according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [9/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const XMLCh *const matchString, const XMLSize_t start, const XMLSize_t end, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the string between the specified start and end offsets according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match
start the offset of the start of the string
end the offset of the end of the string
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [10/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const XMLCh *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the null terminated string according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [11/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const XMLCh *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the null terminated string according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
tokenize() [12/12]
RefArrayVectorOf<XMLCh>* RegularExpression::tokenize (const XMLCh *const matchString, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) const
Tokenizes the null terminated string according to the regular expression, returning the parts of the string that do not match the regular expression.
Parameters
matchString the string to match
manager the memory manager to use
Returns
A RefArrayVectorOf sub-strings that do not match the regular expression allocated using the given MemoryManager. The caller owns the string vector that is returned, and is responsible for deleting it.
Member Data Documentation
EXTENDED_COMMENT
static const unsigned int RegularExpression::EXTENDED_COMMENT static
Definition at line 168 of file RegularExpression.hpp.
fBMPattern
const BMPattern * RegularExpression::fBMPattern protected
Definition at line 588 of file RegularExpression.hpp.
Referenced by cleanUp().
fFirstChar
RangeToken * RegularExpression::fFirstChar protected
Definition at line 593 of file RegularExpression.hpp.
fFixedString
XMLCh * RegularExpression::fFixedString protected
Definition at line 590 of file RegularExpression.hpp.
Referenced by cleanUp().
fFixedStringOnly
bool RegularExpression::fFixedStringOnly protected
Definition at line 583 of file RegularExpression.hpp.
fHasBackReferences
bool RegularExpression::fHasBackReferences protected
Definition at line 582 of file RegularExpression.hpp.
fMemoryManager
MemoryManager * RegularExpression::fMemoryManager protected
Definition at line 597 of file RegularExpression.hpp.
Referenced by cleanUp().
fMinLength
XMLSize_t RegularExpression::fMinLength protected
Definition at line 585 of file RegularExpression.hpp.
fNoClosures
unsigned int RegularExpression::fNoClosures protected
Definition at line 586 of file RegularExpression.hpp.
Referenced by compileClosure().
fNoGroups
int RegularExpression::fNoGroups protected
Definition at line 584 of file RegularExpression.hpp.
fOperations
const Op * RegularExpression::fOperations protected
Definition at line 591 of file RegularExpression.hpp.
fOpFactory
OpFactory RegularExpression::fOpFactory protected
Definition at line 595 of file RegularExpression.hpp.
Referenced by compileClosure(), compileParenthesis(), and compileUnion().
fOptions
unsigned int RegularExpression::fOptions protected
Definition at line 587 of file RegularExpression.hpp.
fPattern
XMLCh * RegularExpression::fPattern protected
Definition at line 589 of file RegularExpression.hpp.
Referenced by cleanUp().
fTokenFactory
TokenFactory * RegularExpression::fTokenFactory protected
Definition at line 596 of file RegularExpression.hpp.
Referenced by cleanUp().
fTokenTree
Token * RegularExpression::fTokenTree protected
Definition at line 592 of file RegularExpression.hpp.
fWordRange
static RangeToken * RegularExpression::fWordRange static protected
Definition at line 594 of file RegularExpression.hpp.
Referenced by staticCleanup().
IGNORE_CASE
static const unsigned int RegularExpression::IGNORE_CASE static
Definition at line 165 of file RegularExpression.hpp.
MULTIPLE_LINE
static const unsigned int RegularExpression::MULTIPLE_LINE static
Definition at line 167 of file RegularExpression.hpp.
PROHIBIT_FIXED_STRING_OPTIMIZATION
static const unsigned int RegularExpression::PROHIBIT_FIXED_STRING_OPTIMIZATION static
Definition at line 170 of file RegularExpression.hpp.
PROHIBIT_HEAD_CHARACTER_OPTIMIZATION
static const unsigned int RegularExpression::PROHIBIT_HEAD_CHARACTER_OPTIMIZATION static
Definition at line 169 of file RegularExpression.hpp.
SINGLE_LINE
static const unsigned int RegularExpression::SINGLE_LINE static
Definition at line 166 of file RegularExpression.hpp.
XMLSCHEMA_MODE
static const unsigned int RegularExpression::XMLSCHEMA_MODE static
Definition at line 171 of file RegularExpression.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/regx/RegularExpression.hpp