Seamly2D: VExceptionWrongId Class Reference
VExceptionWrongId Class Reference
The VExceptionWrongId class for exception wrong id.
#include <vexceptionwrongid.h>
Public Member Functions
VExceptionWrongId (const QString &what, const QDomElement &domElement)
VExceptionWrongId exception wrong parameter id.
VExceptionWrongId (const VExceptionWrongId &e)
VExceptionWrongId copy constructor.
VExceptionWrongId & operator= (const VExceptionWrongId &e)
virtual ~VExceptionWrongId () Q_DECL_EQ_DEFAULT
virtual QString ErrorMessage () const Q_DECL_OVERRIDE
ErrorMessage return main error message.
virtual QString DetailedInformation () const Q_DECL_OVERRIDE
DetailedInformation return detailed information about error.
QString TagText () const
TagText return tag text.
QString TagName () const
TagName return tag name.
qint32 LineNumber () const
LineNumber return line number in file.
Public Member Functions inherited from VException
VException (const QString &error)
VException constructor exception.
VException (const VException &e)
VException copy constructor.
VException & operator= (const VException &e)
virtual ~VException () Q_DECL_EQ_DEFAULT
virtual Q_NORETURN void raise () const Q_DECL_OVERRIDE
raise method raise for exception
virtual Q_REQUIRED_RESULT VException * clone () const Q_DECL_OVERRIDE
clone clone exception
QString WhatUtf8 () const
What return string with error.
void AddMoreInformation (const QString &info)
AddMoreInformation add more information for error.
QString MoreInformation () const
MoreInformation return more information for error.
virtual const char * what () const Q_DECL_OVERRIDE
Protected Attributes
QString tagText
tagText tag text
QString tagName
tagName tag name
qint32 lineNumber
lineNumber line number
Protected Attributes inherited from VException
QString error
error string with error
QString moreInfo
moreInfo more information about error
Additional Inherited Members
Protected Member Functions inherited from VException
QString MoreInfo (const QString &detInfo) const
Detailed Description
The VExceptionWrongId class for exception wrong id.
Definition at line 67 of file vexceptionwrongid.h.
Constructor & Destructor Documentation
VExceptionWrongId() [1/2]
VExceptionWrongId::VExceptionWrongId (const QString & what, const QDomElement & domElement)
VExceptionWrongId exception wrong parameter id.
Parameters
what string with error
domElement som element
Definition at line 65 of file vexceptionwrongid.cpp.
References lineNumber, tagName, and tagText.
VExceptionWrongId() [2/2]
VExceptionWrongId::VExceptionWrongId (const VExceptionWrongId & e)
VExceptionWrongId copy constructor.
Parameters
e exception
Definition at line 80 of file vexceptionwrongid.cpp.
~VExceptionWrongId()
virtual VExceptionWrongId::~VExceptionWrongId () virtual
Member Function Documentation
DetailedInformation()
QString VExceptionWrongId::DetailedInformation () const virtual
DetailedInformation return detailed information about error.
Returns
detailed information
Reimplemented from VException.
Definition at line 113 of file vexceptionwrongid.cpp.
References lineNumber, VException::MoreInfo(), tagName, and tagText.
Referenced by VPattern::SaveDocument().
ErrorMessage()
QString VExceptionWrongId::ErrorMessage () const virtual
ErrorMessage return main error message.
Returns
main error message
Reimplemented from VException.
Definition at line 103 of file vexceptionwrongid.cpp.
References VException::error.
Referenced by VPattern::SaveDocument().
LineNumber()
qint32 VExceptionWrongId::LineNumber () const inline
LineNumber return line number in file.
Returns
line number
Definition at line 115 of file vexceptionwrongid.h.
References lineNumber.
Referenced by operator=().
operator=()
VExceptionWrongId & VExceptionWrongId::operator= (const VExceptionWrongId & e)
Definition at line 85 of file vexceptionwrongid.cpp.
References LineNumber(), lineNumber, VException::operator=(), TagName(), tagName, TagText(), and tagText.
TagName()
QString VExceptionWrongId::TagName () const inline
TagName return tag name.
Returns
tag name
Definition at line 105 of file vexceptionwrongid.h.
References tagName.
Referenced by operator=().
TagText()
QString VExceptionWrongId::TagText () const inline
TagText return tag text.
Returns
tag text
Definition at line 95 of file vexceptionwrongid.h.
References tagText.
Referenced by operator=().
Member Data Documentation
lineNumber
qint32 VExceptionWrongId::lineNumber protected
lineNumber line number
Definition at line 87 of file vexceptionwrongid.h.
Referenced by DetailedInformation(), LineNumber(), operator=(), and VExceptionWrongId().
tagName
QString VExceptionWrongId::tagName protected
tagName tag name
Definition at line 84 of file vexceptionwrongid.h.
Referenced by DetailedInformation(), operator=(), TagName(), and VExceptionWrongId().
tagText
QString VExceptionWrongId::tagText protected
tagText tag text
Definition at line 81 of file vexceptionwrongid.h.
Referenced by DetailedInformation(), operator=(), TagText(), and VExceptionWrongId().
The documentation for this class was generated from the following files:
src/libs/ifc/exception/vexceptionwrongid.h
src/libs/ifc/exception/vexceptionwrongid.cpp