Seamly2D: MouseCoordinates Class Reference
MouseCoordinates Class Reference
#include <mouse_coordinates.h>
Public Slots
void updateCoordinates (const QPointF &scenePos)
Public Member Functions
MouseCoordinates (const Unit &units, QWidget *parent=nullptr)
virtual ~MouseCoordinates ()
Private Attributes
Ui::MouseCoordinates * ui
Unit m_units
Detailed Description
Definition at line 40 of file mouse_coordinates.h.
Constructor & Destructor Documentation
MouseCoordinates()
MouseCoordinates::MouseCoordinates (const Unit & units, QWidget * parent = nullptr)
Definition at line 39 of file mouse_coordinates.cpp.
References m_units, ui, UnitsToStr(), and updateCoordinates().
~MouseCoordinates()
MouseCoordinates::~MouseCoordinates () virtual
Definition at line 53 of file mouse_coordinates.cpp.
Member Function Documentation
updateCoordinates
void MouseCoordinates::updateCoordinates (const QPointF & scenePos) slot
Definition at line 60 of file mouse_coordinates.cpp.
References qApp, and ui.
Referenced by MouseCoordinates().
Member Data Documentation
m_units
Unit MouseCoordinates::m_units private
Definition at line 53 of file mouse_coordinates.h.
Referenced by MouseCoordinates().
ui
Ui::MouseCoordinates* MouseCoordinates::ui private
Definition at line 52 of file mouse_coordinates.h.
Referenced by MouseCoordinates(), and updateCoordinates().
The documentation for this class was generated from the following files:
src/libs/vwidgets/mouse_coordinates.h
src/libs/vwidgets/mouse_coordinates.cpp