Seamly2D: anonymous_namespace{vcommonsettings.cpp} Namespace Reference
anonymous_namespace{vcommonsettings.cpp} Namespace Reference
Functions
QStringList ClearFormats (const QStringList &predefinedFormats, QStringList formats)
void SymlinkCopyDirRecursive (const QString &fromDir, const QString &toDir, bool replaceOnConflit)
QString PrepareStandardFiles (const QString &currentPath, const QString &standardPath, const QString &defPath)
Variables
const QString settingPathsIndividualMeasurements = QStringLiteral("paths/individual_size_measurements")
const QString settingPathsMultisizeMeasurements = QStringLiteral("paths/multi_size_measurements")
const QString settingPathsTemplates = QStringLiteral("paths/templates")
const QString settingPathsBodyScans = QStringLiteral("paths/bodyscans")
const QString settingPathsLabelTemplate = QStringLiteral("paths/labels")
const QString settingConfigurationCompanyName = QStringLiteral("graphicsview/companyName")
const QString settingConfigurationContact = QStringLiteral("graphicsview/contact")
const QString settingConfigurationAddress = QStringLiteral("graphicsview/address")
const QString settingConfigurationCity = QStringLiteral("graphicsview/city")
const QString settingConfigurationState = QStringLiteral("graphicsview/state")
const QString settingConfigurationZipcode = QStringLiteral("graphicsview/zipcode")
const QString settingConfigurationCountry = QStringLiteral("graphicsview/country")
const QString settingConfigurationTelephone = QStringLiteral("graphicsview/telephone")
const QString settingConfigurationFax = QStringLiteral("graphicsview/fax")
const QString settingConfigurationEmail = QStringLiteral("graphicsview/email")
const QString settingConfigurationWebsite = QStringLiteral("graphicsview/website")
const QString settingConfigurationShowWelcome = QStringLiteral("configuration/showWelcome")
const QString settingConfigurationOsSeparator = QStringLiteral("configuration/osSeparator")
const QString settingConfigurationAutosaveState = QStringLiteral("configuration/autosave/state")
const QString settingConfigurationAutosaveTime = QStringLiteral("configuration/autosave/time")
const QString settingConfigurationUseModeType = QStringLiteral("configuration/autosave/useModeType")
const QString settingConfigurationUseLastExportFormat = QStringLiteral("configuration/autosave/useLastExportFormat")
const QString settingConfigurationExportFormat = QStringLiteral("configuration/autosave/exportFormat")
const QString settingConfigurationSendReportState = QStringLiteral("configuration/send_report/state")
const QString settingConfigurationLocale = QStringLiteral("configuration/locale")
const QString settingPMSystemCode = QStringLiteral("configuration/pmscode")
const QString settingConfigurationUnit = QStringLiteral("configuration/unit")
const QString settingConfigurationConfirmItemDeletion = QStringLiteral("configuration/confirm_item_deletion")
const QString settingConfigurationConfirmFormatRewriting = QStringLiteral("configuration/confirm_format_rewriting")
const QString settingConfigurationMoveSuffix = QStringLiteral("configuration/moveSuffix")
const QString settingConfigurationRotateSuffix = QStringLiteral("configuration/rotateSuffix")
const QString settingConfigurationMirrorByAxisSuffix = QStringLiteral("configuration/mirrorByAxisSuffix")
const QString settingConfigurationMirrorByLineSuffix = QStringLiteral("configuration/mirrorByLineSuffix")
const QString settingGraphicsViewToolBarStyle = QStringLiteral("graphicsview/tool_bar_style")
const QString settingGraphicsViewShowToolsToolBar = QStringLiteral("graphicsview/showToolsToolbar")
const QString settingGraphicsViewShowPointToolBar = QStringLiteral("graphicsview/showPointToolbar")
const QString settingGraphicsViewShowLineToolBar = QStringLiteral("graphicsview/showLineToolbar")
const QString settingGraphicsViewShowCurveToolBar = QStringLiteral("graphicsview/showCurveToolbar")
const QString settingGraphicsViewShowArcToolBar = QStringLiteral("graphicsview/showArcToolbar")
const QString settingGraphicsViewShowOpsToolBar = QStringLiteral("graphicsview/showOpsToolbar")
const QString settingGraphicsViewShowPieceToolBar = QStringLiteral("graphicsview/showPieceToolbar")
const QString settingGraphicsViewShowDetailsToolBar = QStringLiteral("graphicsview/showDetailsToolbar")
const QString settingGraphicsViewShowLayoutToolBar = QStringLiteral("graphicsview/showLayoutToolbar")
const QString settingGraphicsViewShowScrollBars = QStringLiteral("graphicsview/showScrollBars")
const QString settingGraphicsViewScrollBarWidth = QStringLiteral("graphicsview/scrollBarWidth")
const QString settingGraphicsViewScrollDuration = QStringLiteral("graphicsview/scrollDuration")
const QString settingGraphicsViewScrollUpdateInterval = QStringLiteral("graphicsview/scrollUpdateInterval")
const QString settingGraphicsViewScrollSpeedFactor = QStringLiteral("graphicsview/scrollSpeedFactor")
const QString settingGraphicsViewPixelDelta = QStringLiteral("graphicsview/pixelDelta")
const QString settingGraphicsViewAngleDelta = QStringLiteral("graphicsview/angleDelta")
const QString settingGraphicsViewZoomModKey = QStringLiteral("graphicsview/zoomModKey")
const QString settingGraphicsViewZoomDoubleClick = QStringLiteral("graphicsview/zoomDoubleClick")
const QString settingGraphicsViewPanActiveSpaceKey = QStringLiteral("graphicsview/panActiveSpaceKey")
const QString settingGraphicsViewZoomSpeedFactor = QStringLiteral("graphicsview/zoomSpeedFactor")
const QString settingGraphicsViewExportQuality = QStringLiteral("graphicsview/exportQuality")
const QString settingGraphicsViewZoomRBPositiveColor = QStringLiteral("graphicsview/zoomRBPositiveColor")
const QString settingGraphicsViewZoomRBNegativeColor = QStringLiteral("graphicsview/zoomRBNegativeColor")
const QString settingGraphicsViewPointNameColor = QStringLiteral("graphicsview/pointNameColor")
const QString settingGraphicsViewPointNameHoverColor = QStringLiteral("graphicsview/pointNameHoverColor")
const QString settingGraphicsViewAxisOrginColor = QStringLiteral("graphicsview/axisOrginColor")
const QString settingGraphicsViewDefaultLineColor = QStringLiteral("graphicsview/defaultLineColor")
const QString settingGraphicsViewDefaultLineWeight = QStringLiteral("graphicsview/defaultLineWeight")
const QString settingGraphicsViewDefaultLineType = QStringLiteral("graphicsview/defaultLineType")
const QString settingGraphicsViewPrimaryColor = QStringLiteral("graphicsview/primarySupportColor")
const QString settingGraphicsViewSecondaryColor = QStringLiteral("graphicsview/secondarySupportColor")
const QString settingGraphicsViewTertiaryColor = QStringLiteral("graphicsview/tertiarySupportColor")
const QString settingGraphicsViewConstrainValue = QStringLiteral("graphicsview/constrainValue")
const QString settingGraphicsViewConstrainModKey = QStringLiteral("graphicsview/constrainModKey")
const QString settingGraphicsViewPointNameSize = QStringLiteral("graphicsview/pointNameSize")
const QString settingGraphicsViewGuiFontSize = QStringLiteral("graphicsview/guiFontSize")
const QString settingGraphicsViewHidePointNames = QStringLiteral("graphicsview/hidePointNames")
const QString settingGraphicsViewShowAxisOrigin = QStringLiteral("graphicsview/showAxisOrigin")
const QString settingGraphicsViewWireframe = QStringLiteral("graphicsview/wireframe")
const QString settingGraphicsViewShowControlPoints = QStringLiteral("graphicsview/showControlPoints")
const QString settingGraphicsViewShowAnchorPoints = QStringLiteral("graphicsview/showAnchorPoints")
const QString settingGraphicsUseToolColor = QStringLiteral("graphicsview/useToolColor")
const QString settingPatternUndo = QStringLiteral("pattern/undo")
const QString settingSelectionSound = QStringLiteral("pattern/selectionSound")
const QString settingPatternForbidFlipping = QStringLiteral("pattern/forbidFlipping")
const QString settingPatternHideSeamLine = QStringLiteral("pattern/hideMainPath")
const QString settingDefaultNotchLength = QStringLiteral("pattern/defaultNotchLength")
const QString settingDefaultNotchWidth = QStringLiteral("pattern/defaultNotchWidth")
const QString settingDefaultNotchType = QStringLiteral("pattern/defaultNotchType")
const QString settingDefaultNotchColor = QStringLiteral("pattern/defaultNotchColor")
const QString settingSeamlineNotch = QStringLiteral("pattern/doubleNotch")
const QString settingSeamAllowanceNotch = QStringLiteral("pattern/showSeamAllowanceNotch")
const QString settingPatternDefaultSeamAllowance = QStringLiteral("pattern/defaultSeamAllowance")
const QString settingDefaultSeamColor = QStringLiteral("pattern/defaultSeamColor")
const QString settingDefaultSeamLinetype = QStringLiteral("pattern/defaultSeamLinetype")
const QString settingDefaultSeamLineweight = QStringLiteral("pattern/defaultSeamLineweight")
const QString settingDefaultCutColor = QStringLiteral("pattern/defaultCutColor")
const QString settingDefaultCutLinetype = QStringLiteral("pattern/defaultCutLinetype")
const QString settingDefaultCutLineweight = QStringLiteral("pattern/defaultCutLineweight")
const QString settingDefaultInternalColor = QStringLiteral("pattern/defaultInternalColor")
const QString settingDefaultInternalLinetype = QStringLiteral("pattern/defaultInternalLinetype")
const QString settingDefaultInternalLineweight = QStringLiteral("pattern/defaultInternalLineweight")
const QString settingDefaultCutoutColor = QStringLiteral("pattern/defaultCutoutColor")
const QString settingDefaultCutoutLinetype = QStringLiteral("pattern/defaultCutoutLinetype")
const QString settingDefaultCutoutLineweight = QStringLiteral("pattern/defaultCutoutLineweight")
const QString settingShowSeamAllowances = QStringLiteral("pattern/showShowSeamAllowances")
const QString settingDefaultSeamAllowanceVisibilty = QStringLiteral("pattern/defaultSeamAllowanceVisibilty")
const QString settingShowGrainlines = QStringLiteral("pattern/showGrainlines")
const QString settingDefaultGrainlineVisibilty = QStringLiteral("pattern/defaultGrainlineVisibilty")
const QString settingDefaultGrainlineLength = QStringLiteral("pattern/defaultGrainlineLength")
const QString settingDefaultGrainlineColor = QStringLiteral("pattern/defaultGrainlineColor")
const QString settingDefaultGrainlineLineweight = QStringLiteral("pattern/defaultGrainlineLineweight")
const QString settingShowLabels = QStringLiteral("pattern/showLabels")
const QString settingShowPatternLabels = QStringLiteral("pattern/showPatternLabels")
const QString settingShowPieceLabels = QStringLiteral("pattern/showPieceLabels")
const QString settingDefaultLabelWidth = QStringLiteral("pattern/defaultLabelWidth")
const QString settingDefaultLabelHeight = QStringLiteral("pattern/defaultLabelHeight")
const QString settingDefaultLabelColor = QStringLiteral("pattern/defaultLabelColor")
const QString settingDefaultPatternTemplate = QStringLiteral("pattern/defaultPatternTemplate")
const QString settingDefaultPieceTemplate = QStringLiteral("pattern/defaultPieceTemplate")
const QString settingPatternLabelFont = QStringLiteral("pattern/labelFont")
const QString settingPatternGuiFont = QStringLiteral("pattern/guiFont")
const QString settingPatternPointNameFont = QStringLiteral("pattern/pointNameFont")
const QString settingGeneralRecentFileList = QStringLiteral("recentFileList")
const QString settingGeneralRestoreFileList = QStringLiteral("restoreFileList")
const QString settingGeneralGeometry = QStringLiteral("geometry")
const QString settingGeneralWindowState = QStringLiteral("windowState")
const QString settingGeneralToolbarsState = QStringLiteral("toolbarsState")
const QString settingPreferenceDialogSize = QStringLiteral("preferenceDialogSize")
const QString settingToolSeamAllowanceDialogSize = QStringLiteral("toolSeamAllowanceDialogSize")
const QString settingIncrementsDialogSize = QStringLiteral("toolIncrementsDialogSize")
const QString settingFormulaWizardDialogSize = QStringLiteral("formulaWizardDialogSize")
const QString settingLatestSkippedVersion = QStringLiteral("lastestSkippedVersion")
const QString settingDateOfLastRemind = QStringLiteral("dateOfLastRemind")
const QString settingCSVWithHeader = QStringLiteral("csv/withHeader")
const QString settingCSVCodec = QStringLiteral("csv/withCodec")
const QString settingCSVSeparator = QStringLiteral("csv/withSeparator")
const QString settingLabelDateFormat = QStringLiteral("label/dateFormat")
const QString settingLabelUserDateFormats = QStringLiteral("label/userDateFormats")
const QString settingLabelTimeFormat = QStringLiteral("label/timeFormat")
const QString settingLabelUserTimeFormats = QStringLiteral("label/userTimeFormats")
int pointNameSize = 0
Function Documentation
ClearFormats()
QStringList anonymous_namespace{vcommonsettings.cpp}::ClearFormats (const QStringList & predefinedFormats, QStringList formats)
Definition at line 232 of file vcommonsettings.cpp.
Referenced by VCommonSettings::SetUserDefinedDateFormats(), and VCommonSettings::SetUserDefinedTimeFormats().
PrepareStandardFiles()
QString anonymous_namespace{vcommonsettings.cpp}::PrepareStandardFiles (const QString & currentPath, const QString & standardPath, const QString & defPath)
Definition at line 317 of file vcommonsettings.cpp.
References SymlinkCopyDirRecursive().
Referenced by VCommonSettings::prepareMultisizeTables(), and VCommonSettings::PrepareStandardTemplates().
SymlinkCopyDirRecursive()
void anonymous_namespace{vcommonsettings.cpp}::SymlinkCopyDirRecursive (const QString & fromDir, const QString & toDir, bool replaceOnConflit)
Definition at line 251 of file vcommonsettings.cpp.
Referenced by PrepareStandardFiles().
Variable Documentation
pointNameSize
int anonymous_namespace{vcommonsettings.cpp}::pointNameSize = 0
Definition at line 229 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getPointNameSize(), and VCommonSettings::setPointNameSize().
settingConfigurationAddress
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAddress = QStringLiteral("graphicsview/address")
Definition at line 84 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getAddress(), and VCommonSettings::setAddress().
settingConfigurationAutosaveState
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAutosaveState = QStringLiteral("configuration/autosave/state")
Definition at line 96 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetAutosaveState(), and VCommonSettings::SetAutosaveState().
settingConfigurationAutosaveTime
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAutosaveTime = QStringLiteral("configuration/autosave/time")
Definition at line 97 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getAutosaveInterval(), and VCommonSettings::setAutosaveInterval().
settingConfigurationCity
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCity = QStringLiteral("graphicsview/city")
Definition at line 85 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getCity(), and VCommonSettings::setCity().
settingConfigurationCompanyName
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCompanyName = QStringLiteral("graphicsview/companyName")
Definition at line 82 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getCompanyName(), and VCommonSettings::setCompanyName().
settingConfigurationConfirmFormatRewriting
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationConfirmFormatRewriting = QStringLiteral("configuration/confirm_format_rewriting")
Definition at line 108 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getConfirmFormatRewriting(), and VCommonSettings::setConfirmFormatRewriting().
settingConfigurationConfirmItemDeletion
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationConfirmItemDeletion = QStringLiteral("configuration/confirm_item_deletion")
Definition at line 107 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getConfirmItemDelete(), and VCommonSettings::setConfirmItemDelete().
settingConfigurationContact
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationContact = QStringLiteral("graphicsview/contact")
Definition at line 83 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getContact(), and VCommonSettings::setContact().
settingConfigurationCountry
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCountry = QStringLiteral("graphicsview/country")
Definition at line 88 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getCountry(), and VCommonSettings::setCountry().
settingConfigurationEmail
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationEmail = QStringLiteral("graphicsview/email")
Definition at line 91 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getEmail(), and VCommonSettings::setEmail().
settingConfigurationExportFormat
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationExportFormat = QStringLiteral("configuration/autosave/exportFormat")
Definition at line 101 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getExportFormat(), and VCommonSettings::setExportFormat().
settingConfigurationFax
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationFax = QStringLiteral("graphicsview/fax")
Definition at line 90 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getFax(), and VCommonSettings::setFax().
settingConfigurationLocale
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationLocale = QStringLiteral("configuration/locale")
Definition at line 104 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetLocale(), and VCommonSettings::SetLocale().
settingConfigurationMirrorByAxisSuffix
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMirrorByAxisSuffix = QStringLiteral("configuration/mirrorByAxisSuffix")
Definition at line 111 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getMirrorByAxisSuffix(), and VCommonSettings::setMirrorByAxisSuffix().
settingConfigurationMirrorByLineSuffix
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMirrorByLineSuffix = QStringLiteral("configuration/mirrorByLineSuffix")
Definition at line 112 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getMirrorByLineSuffix(), and VCommonSettings::setMirrorByLineSuffix().
settingConfigurationMoveSuffix
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMoveSuffix = QStringLiteral("configuration/moveSuffix")
Definition at line 109 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getMoveSuffix(), and VCommonSettings::setMoveSuffix().
settingConfigurationOsSeparator
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationOsSeparator = QStringLiteral("configuration/osSeparator")
Definition at line 95 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetOsSeparator(), and VCommonSettings::SetOsSeparator().
settingConfigurationRotateSuffix
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationRotateSuffix = QStringLiteral("configuration/rotateSuffix")
Definition at line 110 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getRotateSuffix(), and VCommonSettings::setRotateSuffix().
settingConfigurationSendReportState
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationSendReportState = QStringLiteral("configuration/send_report/state")
Definition at line 103 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetSendReportState(), and VCommonSettings::SetSendReportState().
settingConfigurationShowWelcome
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationShowWelcome = QStringLiteral("configuration/showWelcome")
Definition at line 94 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowWelcome(), and VCommonSettings::setShowWelcome().
settingConfigurationState
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationState = QStringLiteral("graphicsview/state")
Definition at line 86 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getState(), and VCommonSettings::setState().
settingConfigurationTelephone
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationTelephone = QStringLiteral("graphicsview/telephone")
Definition at line 89 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getTelephone(), and VCommonSettings::setTelephone().
settingConfigurationUnit
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUnit = QStringLiteral("configuration/unit")
Definition at line 106 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetUnit(), and VCommonSettings::SetUnit().
settingConfigurationUseLastExportFormat
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUseLastExportFormat = QStringLiteral("configuration/autosave/useLastExportFormat")
Definition at line 100 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setUseLastExportFormat(), and VCommonSettings::useLastExportFormat().
settingConfigurationUseModeType
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUseModeType = QStringLiteral("configuration/autosave/useModeType")
Definition at line 99 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setUseModeType(), and VCommonSettings::useModeType().
settingConfigurationWebsite
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationWebsite = QStringLiteral("graphicsview/website")
Definition at line 92 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getWebsite(), and VCommonSettings::setWebsite().
settingConfigurationZipcode
const QString anonymous_namespace{vcommonsettings.cpp}::settingConfigurationZipcode = QStringLiteral("graphicsview/zipcode")
Definition at line 87 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getZipcode(), and VCommonSettings::setZipcode().
settingCSVCodec
const QString anonymous_namespace{vcommonsettings.cpp}::settingCSVCodec = QStringLiteral("csv/withCodec")
Definition at line 221 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetCSVCodec(), and VCommonSettings::SetCSVCodec().
settingCSVSeparator
const QString anonymous_namespace{vcommonsettings.cpp}::settingCSVSeparator = QStringLiteral("csv/withSeparator")
Definition at line 222 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetCSVSeparator(), and VCommonSettings::SetCSVSeparator().
settingCSVWithHeader
const QString anonymous_namespace{vcommonsettings.cpp}::settingCSVWithHeader = QStringLiteral("csv/withHeader")
Definition at line 220 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetCSVWithHeader(), and VCommonSettings::SetCSVWithHeader().
settingDateOfLastRemind
const QString anonymous_namespace{vcommonsettings.cpp}::settingDateOfLastRemind = QStringLiteral("dateOfLastRemind")
Definition at line 218 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetDateOfLastRemind(), and VCommonSettings::SetDateOfLastRemind().
settingDefaultCutColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutColor = QStringLiteral("pattern/defaultCutColor")
Definition at line 177 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultCutColor(), and VCommonSettings::setDefaultCutColor().
settingDefaultCutLinetype
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutLinetype = QStringLiteral("pattern/defaultCutLinetype")
Definition at line 178 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultCutLinetype(), and VCommonSettings::setDefaultCutLinetype().
settingDefaultCutLineweight
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutLineweight = QStringLiteral("pattern/defaultCutLineweight")
Definition at line 179 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultCutLineweight(), and VCommonSettings::setDefaultCutLineweight().
settingDefaultCutoutColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutColor = QStringLiteral("pattern/defaultCutoutColor")
Definition at line 183 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultCutoutColor(), and VCommonSettings::setDefaultCutoutColor().
settingDefaultCutoutLinetype
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutLinetype = QStringLiteral("pattern/defaultCutoutLinetype")
Definition at line 184 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultCutoutLinetype(), and VCommonSettings::setDefaultCutoutLinetype().
settingDefaultCutoutLineweight
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutLineweight = QStringLiteral("pattern/defaultCutoutLineweight")
Definition at line 185 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultCutoutLineweight(), and VCommonSettings::setDefaultCutoutLineweight().
settingDefaultGrainlineColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineColor = QStringLiteral("pattern/defaultGrainlineColor")
Definition at line 192 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultGrainlineColor(), and VCommonSettings::setDefaultGrainlineColor().
settingDefaultGrainlineLength
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineLength = QStringLiteral("pattern/defaultGrainlineLength")
Definition at line 191 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultGrainlineLength(), and VCommonSettings::setDefaultGrainlineLength().
settingDefaultGrainlineLineweight
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineLineweight = QStringLiteral("pattern/defaultGrainlineLineweight")
Definition at line 193 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultGrainlineLineweight(), and VCommonSettings::setDefaultGrainlineLineweight().
settingDefaultGrainlineVisibilty
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineVisibilty = QStringLiteral("pattern/defaultGrainlineVisibilty")
Definition at line 190 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultGrainlineVisibilty(), and VCommonSettings::setDefaultGrainlineVisibilty().
settingDefaultInternalColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalColor = QStringLiteral("pattern/defaultInternalColor")
Definition at line 180 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultInternalColor(), and VCommonSettings::setDefaultInternalColor().
settingDefaultInternalLinetype
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalLinetype = QStringLiteral("pattern/defaultInternalLinetype")
Definition at line 181 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultInternalLinetype(), and VCommonSettings::setDefaultInternalLinetype().
settingDefaultInternalLineweight
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalLineweight = QStringLiteral("pattern/defaultInternalLineweight")
Definition at line 182 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultInternalLineweight(), and VCommonSettings::setDefaultInternalLineweight().
settingDefaultLabelColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelColor = QStringLiteral("pattern/defaultLabelColor")
Definition at line 200 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultLabelColor(), and VCommonSettings::setDefaultLabelColor().
settingDefaultLabelHeight
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelHeight = QStringLiteral("pattern/defaultLabelHeight")
Definition at line 199 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultLabelHeight(), and VCommonSettings::setDefaultLabelHeight().
settingDefaultLabelWidth
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelWidth = QStringLiteral("pattern/defaultLabelWidth")
Definition at line 198 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultLabelWidth(), and VCommonSettings::setDefaultLabelWidth().
settingDefaultNotchColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchColor = QStringLiteral("pattern/defaultNotchColor")
Definition at line 169 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultNotchColor(), and VCommonSettings::setDefaultNotchColor().
settingDefaultNotchLength
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchLength = QStringLiteral("pattern/defaultNotchLength")
Definition at line 166 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultNotchLength(), and VCommonSettings::setDefaultNotchLength().
settingDefaultNotchType
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchType = QStringLiteral("pattern/defaultNotchType")
Definition at line 168 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultNotchType(), and VCommonSettings::setDefaultNotchType().
settingDefaultNotchWidth
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchWidth = QStringLiteral("pattern/defaultNotchWidth")
Definition at line 167 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultNotchWidth(), and VCommonSettings::setDefaultNotchWidth().
settingDefaultPatternTemplate
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultPatternTemplate = QStringLiteral("pattern/defaultPatternTemplate")
Definition at line 201 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultPatternTemplate(), and VCommonSettings::setDefaultPatternTemplate().
settingDefaultPieceTemplate
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultPieceTemplate = QStringLiteral("pattern/defaultPieceTemplate")
Definition at line 202 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultPieceTemplate(), and VCommonSettings::setDefaultPieceTemplate().
settingDefaultSeamAllowanceVisibilty
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamAllowanceVisibilty = QStringLiteral("pattern/defaultSeamAllowanceVisibilty")
Definition at line 188 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultSeamAllowanceVisibilty(), and VCommonSettings::setDefaultSeamAllowanceVisibilty().
settingDefaultSeamColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamColor = QStringLiteral("pattern/defaultSeamColor")
Definition at line 174 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultSeamColor(), and VCommonSettings::setDefaultSeamColor().
settingDefaultSeamLinetype
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamLinetype = QStringLiteral("pattern/defaultSeamLinetype")
Definition at line 175 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultSeamLinetype(), and VCommonSettings::setDefaultSeamLinetype().
settingDefaultSeamLineweight
const QString anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamLineweight = QStringLiteral("pattern/defaultSeamLineweight")
Definition at line 176 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultSeamLineweight(), and VCommonSettings::setDefaultSeamLineweight().
settingFormulaWizardDialogSize
const QString anonymous_namespace{vcommonsettings.cpp}::settingFormulaWizardDialogSize = QStringLiteral("formulaWizardDialogSize")
Definition at line 216 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetFormulaWizardDialogSize(), and VCommonSettings::SetFormulaWizardDialogSize().
settingGeneralGeometry
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralGeometry = QStringLiteral("geometry")
Definition at line 210 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetGeometry(), and VCommonSettings::SetGeometry().
settingGeneralRecentFileList
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralRecentFileList = QStringLiteral("recentFileList")
Definition at line 208 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetRecentFileList(), and VCommonSettings::SetRecentFileList().
settingGeneralRestoreFileList
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralRestoreFileList = QStringLiteral("restoreFileList")
Definition at line 209 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetRestoreFileList(), and VCommonSettings::SetRestoreFileList().
settingGeneralToolbarsState
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralToolbarsState = QStringLiteral("toolbarsState")
Definition at line 212 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetToolbarsState(), and VCommonSettings::SetToolbarsState().
settingGeneralWindowState
const QString anonymous_namespace{vcommonsettings.cpp}::settingGeneralWindowState = QStringLiteral("windowState")
Definition at line 211 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetWindowState(), and VCommonSettings::SetWindowState().
settingGraphicsUseToolColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsUseToolColor = QStringLiteral("graphicsview/useToolColor")
Definition at line 159 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getUseToolColor(), and VCommonSettings::setUseToolColor().
settingGraphicsViewAngleDelta
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewAngleDelta = QStringLiteral("graphicsview/angleDelta")
Definition at line 131 of file vcommonsettings.cpp.
settingGraphicsViewAxisOrginColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewAxisOrginColor = QStringLiteral("graphicsview/axisOrginColor")
Definition at line 141 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getAxisOrginColor(), and VCommonSettings::setAxisOrginColor().
settingGraphicsViewConstrainModKey
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewConstrainModKey = QStringLiteral("graphicsview/constrainModKey")
Definition at line 150 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getConstrainModKey(), and VCommonSettings::setConstrainModKey().
settingGraphicsViewConstrainValue
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewConstrainValue = QStringLiteral("graphicsview/constrainValue")
Definition at line 149 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getConstrainValue(), and VCommonSettings::setConstrainValue().
settingGraphicsViewDefaultLineColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineColor = QStringLiteral("graphicsview/defaultLineColor")
Definition at line 142 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultLineColor(), and VCommonSettings::setDefaultLineColor().
settingGraphicsViewDefaultLineType
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineType = QStringLiteral("graphicsview/defaultLineType")
Definition at line 144 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultLineType(), and VCommonSettings::setDefaultLineType().
settingGraphicsViewDefaultLineWeight
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineWeight = QStringLiteral("graphicsview/defaultLineWeight")
Definition at line 143 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getDefaultLineWeight(), and VCommonSettings::setDefaultLineWeight().
settingGraphicsViewExportQuality
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewExportQuality = QStringLiteral("graphicsview/exportQuality")
Definition at line 136 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getExportQuality(), and VCommonSettings::setExportQuality().
settingGraphicsViewGuiFontSize
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewGuiFontSize = QStringLiteral("graphicsview/guiFontSize")
Definition at line 153 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getGuiFontSize(), and VCommonSettings::setGuiFontSize().
settingGraphicsViewHidePointNames
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewHidePointNames = QStringLiteral("graphicsview/hidePointNames")
Definition at line 154 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getHidePointNames(), and VCommonSettings::setHidePointNames().
settingGraphicsViewPanActiveSpaceKey
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPanActiveSpaceKey = QStringLiteral("graphicsview/panActiveSpaceKey")
Definition at line 134 of file vcommonsettings.cpp.
Referenced by VCommonSettings::isPanActiveSpaceKey(), and VCommonSettings::setPanActiveSpaceKey().
settingGraphicsViewPixelDelta
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPixelDelta = QStringLiteral("graphicsview/pixelDelta")
Definition at line 130 of file vcommonsettings.cpp.
settingGraphicsViewPointNameColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameColor = QStringLiteral("graphicsview/pointNameColor")
Definition at line 139 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getPointNameColor(), and VCommonSettings::setPointNameColor().
settingGraphicsViewPointNameHoverColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameHoverColor = QStringLiteral("graphicsview/pointNameHoverColor")
Definition at line 140 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getPointNameHoverColor(), and VCommonSettings::setPointNameHoverColor().
settingGraphicsViewPointNameSize
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameSize = QStringLiteral("graphicsview/pointNameSize")
Definition at line 152 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getPointNameSize(), and VCommonSettings::setPointNameSize().
settingGraphicsViewPrimaryColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPrimaryColor = QStringLiteral("graphicsview/primarySupportColor")
Definition at line 145 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getPrimarySupportColor(), and VCommonSettings::setPrimarySupportColor().
settingGraphicsViewScrollBarWidth
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollBarWidth = QStringLiteral("graphicsview/scrollBarWidth")
Definition at line 126 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getScrollBarWidth(), and VCommonSettings::setScrollBarWidth().
settingGraphicsViewScrollDuration
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollDuration = QStringLiteral("graphicsview/scrollDuration")
Definition at line 127 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getScrollDuration(), and VCommonSettings::setScrollDuration().
settingGraphicsViewScrollSpeedFactor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollSpeedFactor = QStringLiteral("graphicsview/scrollSpeedFactor")
Definition at line 129 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getScrollSpeedFactor(), and VCommonSettings::setScrollSpeedFactor().
settingGraphicsViewScrollUpdateInterval
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollUpdateInterval = QStringLiteral("graphicsview/scrollUpdateInterval")
Definition at line 128 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getScrollUpdateInterval(), and VCommonSettings::setScrollUpdateInterval().
settingGraphicsViewSecondaryColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewSecondaryColor = QStringLiteral("graphicsview/secondarySupportColor")
Definition at line 146 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getSecondarySupportColor(), and VCommonSettings::setSecondarySupportColor().
settingGraphicsViewShowAnchorPoints
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowAnchorPoints = QStringLiteral("graphicsview/showAnchorPoints")
Definition at line 158 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowAnchorPoints(), and VCommonSettings::setShowAnchorPoints().
settingGraphicsViewShowArcToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowArcToolBar = QStringLiteral("graphicsview/showArcToolbar")
Definition at line 119 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowArcToolBar(), and VCommonSettings::setShowArcToolBar().
settingGraphicsViewShowAxisOrigin
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowAxisOrigin = QStringLiteral("graphicsview/showAxisOrigin")
Definition at line 155 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowAxisOrigin(), and VCommonSettings::setShowAxisOrigin().
settingGraphicsViewShowControlPoints
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowControlPoints = QStringLiteral("graphicsview/showControlPoints")
Definition at line 157 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowControlPoints(), and VCommonSettings::setShowControlPoints().
settingGraphicsViewShowCurveToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowCurveToolBar = QStringLiteral("graphicsview/showCurveToolbar")
Definition at line 118 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowCurveToolBar(), and VCommonSettings::setShowCurveToolBar().
settingGraphicsViewShowDetailsToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowDetailsToolBar = QStringLiteral("graphicsview/showDetailsToolbar")
Definition at line 122 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowDetailsToolBar(), and VCommonSettings::setShowDetailsToolBar().
settingGraphicsViewShowLayoutToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowLayoutToolBar = QStringLiteral("graphicsview/showLayoutToolbar")
Definition at line 123 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowLayoutToolBar(), and VCommonSettings::setShowLayoutToolBar().
settingGraphicsViewShowLineToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowLineToolBar = QStringLiteral("graphicsview/showLineToolbar")
Definition at line 117 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowLineToolBar(), and VCommonSettings::setShowLineToolBar().
settingGraphicsViewShowOpsToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowOpsToolBar = QStringLiteral("graphicsview/showOpsToolbar")
Definition at line 120 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowOpsToolBar(), and VCommonSettings::setShowOpsToolBar().
settingGraphicsViewShowPieceToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowPieceToolBar = QStringLiteral("graphicsview/showPieceToolbar")
Definition at line 121 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowPieceToolBar(), and VCommonSettings::setShowPieceToolBar().
settingGraphicsViewShowPointToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowPointToolBar = QStringLiteral("graphicsview/showPointToolbar")
Definition at line 116 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowPointToolBar(), and VCommonSettings::setShowPointToolBar().
settingGraphicsViewShowScrollBars
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowScrollBars = QStringLiteral("graphicsview/showScrollBars")
Definition at line 125 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowScrollBars(), and VCommonSettings::setShowScrollBars().
settingGraphicsViewShowToolsToolBar
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowToolsToolBar = QStringLiteral("graphicsview/showToolsToolbar")
Definition at line 115 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getShowToolsToolBar(), and VCommonSettings::setShowToolsToolBar().
settingGraphicsViewTertiaryColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewTertiaryColor = QStringLiteral("graphicsview/tertiarySupportColor")
Definition at line 147 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getTertiarySupportColor(), and VCommonSettings::setTertiarySupportColor().
settingGraphicsViewToolBarStyle
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewToolBarStyle = QStringLiteral("graphicsview/tool_bar_style")
Definition at line 114 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getToolBarStyle(), and VCommonSettings::setToolBarStyle().
settingGraphicsViewWireframe
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewWireframe = QStringLiteral("graphicsview/wireframe")
Definition at line 156 of file vcommonsettings.cpp.
Referenced by VCommonSettings::isWireframe(), and VCommonSettings::setWireframe().
settingGraphicsViewZoomDoubleClick
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomDoubleClick = QStringLiteral("graphicsview/zoomDoubleClick")
Definition at line 133 of file vcommonsettings.cpp.
Referenced by VCommonSettings::isZoomDoubleClick(), and VCommonSettings::setZoomDoubleClick().
settingGraphicsViewZoomModKey
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomModKey = QStringLiteral("graphicsview/zoomModKey")
Definition at line 132 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getZoomModKey(), and VCommonSettings::setZoomModKey().
settingGraphicsViewZoomRBNegativeColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomRBNegativeColor = QStringLiteral("graphicsview/zoomRBNegativeColor")
Definition at line 138 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getZoomRBNegativeColor(), and VCommonSettings::setZoomRBNegativeColor().
settingGraphicsViewZoomRBPositiveColor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomRBPositiveColor = QStringLiteral("graphicsview/zoomRBPositiveColor")
Definition at line 137 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getZoomRBPositiveColor(), and VCommonSettings::setZoomRBPositiveColor().
settingGraphicsViewZoomSpeedFactor
const QString anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomSpeedFactor = QStringLiteral("graphicsview/zoomSpeedFactor")
Definition at line 135 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getZoomSpeedFactor(), and VCommonSettings::setZoomSpeedFactor().
settingIncrementsDialogSize
const QString anonymous_namespace{vcommonsettings.cpp}::settingIncrementsDialogSize = QStringLiteral("toolIncrementsDialogSize")
Definition at line 215 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetIncrementsDialogSize(), and VCommonSettings::SetIncrementsDialogSize().
settingLabelDateFormat
const QString anonymous_namespace{vcommonsettings.cpp}::settingLabelDateFormat = QStringLiteral("label/dateFormat")
Definition at line 224 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetLabelDateFormat(), and VCommonSettings::SetLabelDateFormat().
settingLabelTimeFormat
const QString anonymous_namespace{vcommonsettings.cpp}::settingLabelTimeFormat = QStringLiteral("label/timeFormat")
Definition at line 226 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetLabelTimeFormat(), and VCommonSettings::SetLabelTimeFormat().
settingLabelUserDateFormats
const QString anonymous_namespace{vcommonsettings.cpp}::settingLabelUserDateFormats = QStringLiteral("label/userDateFormats")
Definition at line 225 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetUserDefinedDateFormats(), and VCommonSettings::SetUserDefinedDateFormats().
settingLabelUserTimeFormats
const QString anonymous_namespace{vcommonsettings.cpp}::settingLabelUserTimeFormats = QStringLiteral("label/userTimeFormats")
Definition at line 227 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetUserDefinedTimeFormats(), and VCommonSettings::SetUserDefinedTimeFormats().
settingLatestSkippedVersion
const QString anonymous_namespace{vcommonsettings.cpp}::settingLatestSkippedVersion = QStringLiteral("lastestSkippedVersion")
Definition at line 217 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetLatestSkippedVersion(), and VCommonSettings::SetLatestSkippedVersion().
settingPathsBodyScans
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsBodyScans = QStringLiteral("paths/bodyscans")
Definition at line 79 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getBodyScansPath(), and VCommonSettings::setBodyScansPath().
settingPathsIndividualMeasurements
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsIndividualMeasurements = QStringLiteral("paths/individual_size_measurements")
Definition at line 76 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getIndividualSizePath(), and VCommonSettings::setIndividualSizePath().
settingPathsLabelTemplate
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsLabelTemplate = QStringLiteral("paths/labels")
Definition at line 80 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getLabelTemplatePath(), and VCommonSettings::SetPathLabelTemplate().
settingPathsMultisizeMeasurements
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsMultisizeMeasurements = QStringLiteral("paths/multi_size_measurements")
Definition at line 77 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getMultisizePath(), and VCommonSettings::setMultisizePath().
settingPathsTemplates
const QString anonymous_namespace{vcommonsettings.cpp}::settingPathsTemplates = QStringLiteral("paths/templates")
Definition at line 78 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getTemplatePath(), and VCommonSettings::setTemplatePath().
settingPatternDefaultSeamAllowance
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternDefaultSeamAllowance = QStringLiteral("pattern/defaultSeamAllowance")
Definition at line 173 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetDefaultSeamAllowance(), and VCommonSettings::SetDefaultSeamAllowance().
settingPatternForbidFlipping
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternForbidFlipping = QStringLiteral("pattern/forbidFlipping")
Definition at line 163 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getForbidPieceFlipping(), and VCommonSettings::setForbidPieceFlipping().
settingPatternGuiFont
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternGuiFont = QStringLiteral("pattern/guiFont")
Definition at line 205 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getGuiFont(), and VCommonSettings::setGuiFont().
settingPatternHideSeamLine
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternHideSeamLine = QStringLiteral("pattern/hideMainPath")
Definition at line 164 of file vcommonsettings.cpp.
Referenced by VCommonSettings::isHideSeamLine(), and VCommonSettings::setHideSeamLine().
settingPatternLabelFont
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternLabelFont = QStringLiteral("pattern/labelFont")
Definition at line 204 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getLabelFont(), and VCommonSettings::setLabelFont().
settingPatternPointNameFont
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternPointNameFont = QStringLiteral("pattern/pointNameFont")
Definition at line 206 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getPointNameFont(), and VCommonSettings::setPointNameFont().
settingPatternUndo
const QString anonymous_namespace{vcommonsettings.cpp}::settingPatternUndo = QStringLiteral("pattern/undo")
Definition at line 161 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetUndoCount(), and VCommonSettings::SetUndoCount().
settingPMSystemCode
const QString anonymous_namespace{vcommonsettings.cpp}::settingPMSystemCode = QStringLiteral("configuration/pmscode")
Definition at line 105 of file vcommonsettings.cpp.
Referenced by VCommonSettings::GetPMSystemCode(), and VCommonSettings::SetPMSystemCode().
settingPreferenceDialogSize
const QString anonymous_namespace{vcommonsettings.cpp}::settingPreferenceDialogSize = QStringLiteral("preferenceDialogSize")
Definition at line 213 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getPreferenceDialogSize(), and VCommonSettings::setPreferenceDialogSize().
settingSeamAllowanceNotch
const QString anonymous_namespace{vcommonsettings.cpp}::settingSeamAllowanceNotch = QStringLiteral("pattern/showSeamAllowanceNotch")
Definition at line 171 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setShowSeamAllowanceNotch(), and VCommonSettings::showSeamAllowanceNotch().
settingSeamlineNotch
const QString anonymous_namespace{vcommonsettings.cpp}::settingSeamlineNotch = QStringLiteral("pattern/doubleNotch")
Definition at line 170 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setShowSeamlineNotch(), and VCommonSettings::showSeamlineNotch().
settingSelectionSound
const QString anonymous_namespace{vcommonsettings.cpp}::settingSelectionSound = QStringLiteral("pattern/selectionSound")
Definition at line 162 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getSelectionSound(), VCommonSettings::getSound(), and VCommonSettings::setSelectionSound().
settingShowGrainlines
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowGrainlines = QStringLiteral("pattern/showGrainlines")
Definition at line 189 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setShowGrainlines(), and VCommonSettings::showGrainlines().
settingShowLabels
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowLabels = QStringLiteral("pattern/showLabels")
Definition at line 195 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setShowLabels(), and VCommonSettings::showLabels().
settingShowPatternLabels
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowPatternLabels = QStringLiteral("pattern/showPatternLabels")
Definition at line 196 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setShowPatternLabels(), and VCommonSettings::showPatternLabels().
settingShowPieceLabels
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowPieceLabels = QStringLiteral("pattern/showPieceLabels")
Definition at line 197 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setShowPieceLabels(), and VCommonSettings::showPieceLabels().
settingShowSeamAllowances
const QString anonymous_namespace{vcommonsettings.cpp}::settingShowSeamAllowances = QStringLiteral("pattern/showShowSeamAllowances")
Definition at line 187 of file vcommonsettings.cpp.
Referenced by VCommonSettings::setShowSeamAllowances(), and VCommonSettings::showSeamAllowances().
settingToolSeamAllowanceDialogSize
const QString anonymous_namespace{vcommonsettings.cpp}::settingToolSeamAllowanceDialogSize = QStringLiteral("toolSeamAllowanceDialogSize")
Definition at line 214 of file vcommonsettings.cpp.
Referenced by VCommonSettings::getPatternPieceDialogSize(), and VCommonSettings::setPatternPieceDialogSize().