Seamly2D: XMLBigInteger Class Reference
XMLBigInteger Class Reference
#include <XMLBigInteger.hpp>
Public Member Functions
XMLBigInteger (const XMLCh *const strValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XMLBigInteger ()
XMLBigInteger (const XMLBigInteger &toCopy)
void multiply (const unsigned int byteToShift)
void divide (const unsigned int byteToShift)
unsigned int getTotalDigit () const
XMLCh * getRawData () const
bool operator== (const XMLBigInteger &toCompare) const
int getSign () const
int intValue () const
XMLBigInteger (const XMLCh *const strValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XMLBigInteger ()
XMLBigInteger (const XMLBigInteger &toCopy)
void multiply (const unsigned int byteToShift)
void divide (const unsigned int byteToShift)
unsigned int getTotalDigit () const
XMLCh * getRawData () const
bool operator== (const XMLBigInteger &toCompare) const
int getSign () const
int intValue () const
XMLBigInteger (const XMLCh *const strValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XMLBigInteger ()
XMLBigInteger (const XMLBigInteger &toCopy)
void multiply (const unsigned int byteToShift)
void divide (const unsigned int byteToShift)
unsigned int getTotalDigit () const
XMLCh * getRawData () const
bool operator== (const XMLBigInteger &toCompare) const
int getSign () const
int intValue () const
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Static Public Member Functions
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager, bool isNonPositiveInteger=false)
static void parseBigInteger (const XMLCh *const toConvert, XMLCh *const retBuffer, int &signValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int compareValues (const XMLBigInteger *const lValue, const XMLBigInteger *const rValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int compareValues (const XMLCh *const lString, const int &lSign, const XMLCh *const rString, const int &rSign, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager, bool isNonPositiveInteger=false)
static void parseBigInteger (const XMLCh *const toConvert, XMLCh *const retBuffer, int &signValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int compareValues (const XMLBigInteger *const lValue, const XMLBigInteger *const rValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int compareValues (const XMLCh *const lString, const int &lSign, const XMLCh *const rString, const int &rSign, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager, bool isNonPositiveInteger=false)
static void parseBigInteger (const XMLCh *const toConvert, XMLCh *const retBuffer, int &signValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int compareValues (const XMLBigInteger *const lValue, const XMLBigInteger *const rValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int compareValues (const XMLCh *const lString, const int &lSign, const XMLCh *const rString, const int &rSign, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Private Member Functions
XMLBigInteger & operator= (const XMLBigInteger &)
void setSign (int)
XMLBigInteger & operator= (const XMLBigInteger &)
void setSign (int)
XMLBigInteger & operator= (const XMLBigInteger &)
void setSign (int)
Private Attributes
int fSign
XMLCh * fMagnitude
XMLCh * fRawData
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 30 of file XMLBigInteger.hpp.
Constructor & Destructor Documentation
XMLBigInteger() [1/6]
XMLBigInteger::XMLBigInteger (const XMLCh *const strValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a newly allocated XMLBigInteger object that represents the value represented by the string. The string is converted to an int value as if by the valueOf method.
Parameters
strValue the String to be converted to an XMLBigInteger.
manager Pointer to the memory manager to be used to allocate objects.
Exceptions
NumberFormatException if the String does not contain a parsable XMLBigInteger.
~XMLBigInteger() [1/3]
XMLBigInteger::~XMLBigInteger ()
XMLBigInteger() [2/6]
XMLBigInteger::XMLBigInteger (const XMLBigInteger & toCopy)
XMLBigInteger() [3/6]
XMLBigInteger::XMLBigInteger (const XMLCh *const strValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a newly allocated XMLBigInteger object that represents the value represented by the string. The string is converted to an int value as if by the valueOf method.
Parameters
strValue the String to be converted to an XMLBigInteger.
manager Pointer to the memory manager to be used to allocate objects.
Exceptions
NumberFormatException if the String does not contain a parsable XMLBigInteger.
~XMLBigInteger() [2/3]
XMLBigInteger::~XMLBigInteger ()
XMLBigInteger() [4/6]
XMLBigInteger::XMLBigInteger (const XMLBigInteger & toCopy)
XMLBigInteger() [5/6]
XMLBigInteger::XMLBigInteger (const XMLCh *const strValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a newly allocated XMLBigInteger object that represents the value represented by the string. The string is converted to an int value as if by the valueOf method.
Parameters
strValue the String to be converted to an XMLBigInteger.
manager Pointer to the memory manager to be used to allocate objects.
Exceptions
NumberFormatException if the String does not contain a parsable XMLBigInteger.
~XMLBigInteger() [3/3]
XMLBigInteger::~XMLBigInteger ()
XMLBigInteger() [6/6]
XMLBigInteger::XMLBigInteger (const XMLBigInteger & toCopy)
Member Function Documentation
compareValues() [1/6]
static int XMLBigInteger::compareValues (const XMLBigInteger *const lValue, const XMLBigInteger *const rValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Referenced by operator==().
compareValues() [2/6]
static int XMLBigInteger::compareValues (const XMLBigInteger *const lValue, const XMLBigInteger *const rValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
compareValues() [3/6]
static int XMLBigInteger::compareValues (const XMLBigInteger *const lValue, const XMLBigInteger *const rValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
compareValues() [4/6]
static int XMLBigInteger::compareValues (const XMLCh *const lString, const int & lSign, const XMLCh *const rString, const int & rSign, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
compareValues() [5/6]
static int XMLBigInteger::compareValues (const XMLCh *const lString, const int & lSign, const XMLCh *const rString, const int & rSign, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
compareValues() [6/6]
static int XMLBigInteger::compareValues (const XMLCh *const lString, const int & lSign, const XMLCh *const rString, const int & rSign, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
divide() [1/3]
void XMLBigInteger::divide (const unsigned int byteToShift)
divide() [2/3]
void XMLBigInteger::divide (const unsigned int byteToShift)
divide() [3/3]
void XMLBigInteger::divide (const unsigned int byteToShift)
getCanonicalRepresentation() [1/3]
static XMLCh* XMLBigInteger::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager, bool isNonPositiveInteger = false) static
getCanonicalRepresentation() [2/3]
static XMLCh* XMLBigInteger::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager, bool isNonPositiveInteger = false) static
getCanonicalRepresentation() [3/3]
static XMLCh* XMLBigInteger::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager, bool isNonPositiveInteger = false) static
getRawData() [1/3]
XMLCh * XMLBigInteger::getRawData () const inline
Return a copy of the fMagnitude. This is similar to toString, except the internal buffer is returned directly Caller is not required to delete the returned memory.
Definition at line 168 of file XMLBigInteger.hpp.
References fRawData.
getRawData() [2/3]
XMLCh* XMLBigInteger::getRawData () const inline
Return a copy of the fMagnitude. This is similar to toString, except the internal buffer is returned directly Caller is not required to delete the returned memory.
getRawData() [3/3]
XMLCh* XMLBigInteger::getRawData () const inline
Return a copy of the fMagnitude. This is similar to toString, except the internal buffer is returned directly Caller is not required to delete the returned memory.
getSign() [1/3]
int XMLBigInteger::getSign () const inline
Returns the signum function of this number (i.e., -1, 0 or 1 as the value of this number is negative, zero or positive).
Definition at line 148 of file XMLBigInteger.hpp.
References fSign.
Referenced by getTotalDigit().
getSign() [2/3]
int XMLBigInteger::getSign () const
Returns the signum function of this number (i.e., -1, 0 or 1 as the value of this number is negative, zero or positive).
getSign() [3/3]
int XMLBigInteger::getSign () const
Returns the signum function of this number (i.e., -1, 0 or 1 as the value of this number is negative, zero or positive).
getTotalDigit() [1/3]
unsigned int XMLBigInteger::getTotalDigit () const inline
Definition at line 153 of file XMLBigInteger.hpp.
References fMagnitude, getSign(), and XMLString::stringLen().
getTotalDigit() [2/3]
unsigned int XMLBigInteger::getTotalDigit () const
getTotalDigit() [3/3]
unsigned int XMLBigInteger::getTotalDigit () const
intValue() [1/3]
int XMLBigInteger::intValue () const
intValue() [2/3]
int XMLBigInteger::intValue () const
intValue() [3/3]
int XMLBigInteger::intValue () const
multiply() [1/3]
void XMLBigInteger::multiply (const unsigned int byteToShift)
multiply() [2/3]
void XMLBigInteger::multiply (const unsigned int byteToShift)
multiply() [3/3]
void XMLBigInteger::multiply (const unsigned int byteToShift)
operator=() [1/3]
XMLBigInteger& XMLBigInteger::operator= (const XMLBigInteger &) private
operator=() [2/3]
XMLBigInteger& XMLBigInteger::operator= (const XMLBigInteger &) private
operator=() [3/3]
XMLBigInteger& XMLBigInteger::operator= (const XMLBigInteger &) private
operator==() [1/3]
bool XMLBigInteger::operator== (const XMLBigInteger & toCompare) const inline
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLBigInteger object that contains the same int value as this object.
Parameters
toCompare the object to compare with.
Returns
true if the objects are the same; false otherwise.
Definition at line 158 of file XMLBigInteger.hpp.
References compareValues(), and fMemoryManager.
operator==() [2/3]
bool XMLBigInteger::operator== (const XMLBigInteger & toCompare) const
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLBigInteger object that contains the same int value as this object.
Parameters
toCompare the object to compare with.
Returns
true if the objects are the same; false otherwise.
operator==() [3/3]
bool XMLBigInteger::operator== (const XMLBigInteger & toCompare) const
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLBigInteger object that contains the same int value as this object.
Parameters
toCompare the object to compare with.
Returns
true if the objects are the same; false otherwise.
parseBigInteger() [1/3]
static void XMLBigInteger::parseBigInteger (const XMLCh *const toConvert, XMLCh *const retBuffer, int & signValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
parseBigInteger() [2/3]
static void XMLBigInteger::parseBigInteger (const XMLCh *const toConvert, XMLCh *const retBuffer, int & signValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
parseBigInteger() [3/3]
static void XMLBigInteger::parseBigInteger (const XMLCh *const toConvert, XMLCh *const retBuffer, int & signValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
setSign() [1/3]
void XMLBigInteger::setSign (int newSign) inline private
Definition at line 163 of file XMLBigInteger.hpp.
References fSign.
setSign() [2/3]
void XMLBigInteger::setSign (int) private
setSign() [3/3]
void XMLBigInteger::setSign (int) private
Member Data Documentation
fMagnitude
XMLCh * XMLBigInteger::fMagnitude private
Definition at line 143 of file XMLBigInteger.hpp.
Referenced by getTotalDigit().
fMemoryManager
MemoryManager * XMLBigInteger::fMemoryManager private
Definition at line 145 of file XMLBigInteger.hpp.
Referenced by operator==().
fRawData
XMLCh * XMLBigInteger::fRawData private
Definition at line 144 of file XMLBigInteger.hpp.
Referenced by getRawData().
fSign
int XMLBigInteger::fSign private
Definition at line 142 of file XMLBigInteger.hpp.
Referenced by getSign(), and setSign().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/XMLBigInteger.hpp