Seamly2D: NewMeasurementsDialog Class Reference
NewMeasurementsDialog Class Reference
#include <new_measurements_dialog.h>
Public Member Functions
NewMeasurementsDialog (QWidget *parent=nullptr)
~NewMeasurementsDialog ()
MeasurementsType type () const
Unit measurementUnits () const
int baseSize () const
int baseHeight () const
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
Private Slots
void currentTypeChanged (int index)
void currentUnitChanged (int index)
Private Member Functions
void initializeMeasurementTypes ()
void initializeHeightsList ()
void initializeSizesList ()
void initializeUnits (const MeasurementsType &type)
Private Attributes
Ui::NewMeasurementsDialog * ui
bool isInitialized
Detailed Description
Definition at line 65 of file new_measurements_dialog.h.
Constructor & Destructor Documentation
NewMeasurementsDialog()
NewMeasurementsDialog::NewMeasurementsDialog (QWidget * parent = nullptr) explicit
Definition at line 63 of file new_measurements_dialog.cpp.
References Cm, currentTypeChanged(), currentUnitChanged(), VSeamlyMeSettings::GetDefHeight(), VSeamlyMeSettings::GetDefSize(), Individual, initializeHeightsList(), initializeMeasurementTypes(), initializeSizesList(), initializeUnits(), measurementUnits(), qApp, ui, and UnitConvertor().
~NewMeasurementsDialog()
NewMeasurementsDialog::~NewMeasurementsDialog ()
Definition at line 100 of file new_measurements_dialog.cpp.
References ui.
Member Function Documentation
baseHeight()
int NewMeasurementsDialog::baseHeight () const
Definition at line 124 of file new_measurements_dialog.cpp.
References ui.
Referenced by TMainWindow::FileNew().
baseSize()
int NewMeasurementsDialog::baseSize () const
Definition at line 118 of file new_measurements_dialog.cpp.
References ui.
Referenced by TMainWindow::FileNew().
changeEvent()
void NewMeasurementsDialog::changeEvent (QEvent * event) protected virtual
Definition at line 130 of file new_measurements_dialog.cpp.
References initializeMeasurementTypes(), initializeUnits(), and ui.
currentTypeChanged
void NewMeasurementsDialog::currentTypeChanged (int index) private slot
Definition at line 166 of file new_measurements_dialog.cpp.
References initializeHeightsList(), initializeSizesList(), initializeUnits(), Multisize, type(), and ui.
Referenced by NewMeasurementsDialog().
currentUnitChanged
void NewMeasurementsDialog::currentUnitChanged (int index) private slot
Definition at line 187 of file new_measurements_dialog.cpp.
References initializeHeightsList(), initializeSizesList(), and ui.
Referenced by NewMeasurementsDialog().
initializeHeightsList()
void NewMeasurementsDialog::initializeHeightsList () private
Definition at line 211 of file new_measurements_dialog.cpp.
References Inch, measurementUnits(), ui, and MeasurementVariable::WholeListHeights().
Referenced by currentTypeChanged(), currentUnitChanged(), and NewMeasurementsDialog().
initializeMeasurementTypes()
void NewMeasurementsDialog::initializeMeasurementTypes () private
Definition at line 200 of file new_measurements_dialog.cpp.
References Individual, Multisize, and ui.
Referenced by changeEvent(), and NewMeasurementsDialog().
initializeSizesList()
void NewMeasurementsDialog::initializeSizesList () private
Definition at line 222 of file new_measurements_dialog.cpp.
References Inch, measurementUnits(), ui, and MeasurementVariable::WholeListSizes().
Referenced by currentTypeChanged(), currentUnitChanged(), and NewMeasurementsDialog().
initializeUnits()
void NewMeasurementsDialog::initializeUnits (const MeasurementsType & type) private
Definition at line 233 of file new_measurements_dialog.cpp.
References Cm, Inch, Individual, Mm, qApp, StrToUnits(), type(), and ui.
Referenced by changeEvent(), currentTypeChanged(), and NewMeasurementsDialog().
measurementUnits()
Unit NewMeasurementsDialog::measurementUnits () const
Definition at line 112 of file new_measurements_dialog.cpp.
References ui.
Referenced by TMainWindow::FileNew(), initializeHeightsList(), initializeSizesList(), and NewMeasurementsDialog().
showEvent()
void NewMeasurementsDialog::showEvent (QShowEvent * event) protected virtual
Definition at line 145 of file new_measurements_dialog.cpp.
References isInitialized.
type()
MeasurementsType NewMeasurementsDialog::type () const
Definition at line 106 of file new_measurements_dialog.cpp.
References ui.
Referenced by currentTypeChanged(), TMainWindow::FileNew(), and initializeUnits().
Member Data Documentation
isInitialized
bool NewMeasurementsDialog::isInitialized private
Definition at line 89 of file new_measurements_dialog.h.
Referenced by showEvent().
ui
Ui::NewMeasurementsDialog* NewMeasurementsDialog::ui private
Definition at line 88 of file new_measurements_dialog.h.
Referenced by baseHeight(), baseSize(), changeEvent(), currentTypeChanged(), currentUnitChanged(), initializeHeightsList(), initializeMeasurementTypes(), initializeSizesList(), initializeUnits(), measurementUnits(), NewMeasurementsDialog(), type(), and ~NewMeasurementsDialog().
The documentation for this class was generated from the following files:
src/app/seamlyme/dialogs/new_measurements_dialog.h
src/app/seamlyme/dialogs/new_measurements_dialog.cpp