Seamly2D: VPatternConverter Class Reference
VPatternConverter Class Reference
#include <vpatternconverter.h>
Public Member Functions
VPatternConverter (const QString &fileName)
virtual ~VPatternConverter () Q_DECL_EQ_DEFAULT
Public Member Functions inherited from VAbstractConverter
VAbstractConverter (const QString &fileName)
virtual ~VAbstractConverter () Q_DECL_EQ_DEFAULT
QString Convert ()
int GetCurrentFormatVarsion () const
QString GetVersionStr () const
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit measurementUnits () const
virtual void setXMLContent (const QString &fileName)
virtual bool SaveDocument (const QString &fileName, QString &error)
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Static Public Attributes
static const QString PatternMaxVerStr = QStringLiteral("0.6.8")
static const QString CurrentSchema = QStringLiteral("://schema/pattern/v0.6.8.xsd")
static Q_DECL_CONSTEXPR const int PatternMinVer = ((0 <<16)|(1 <<8)|(0))
static Q_DECL_CONSTEXPR const int PatternMaxVer = ((0 <<16)|(6 <<8)|(8))
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Protected Member Functions
virtual int minVer () const Q_DECL_OVERRIDE
virtual int maxVer () const Q_DECL_OVERRIDE
virtual QString minVerStr () const Q_DECL_OVERRIDE
virtual QString maxVerStr () const Q_DECL_OVERRIDE
virtual QString getSchema (int ver) const Q_DECL_OVERRIDE
virtual void applyPatches () Q_DECL_OVERRIDE
virtual void downgradeToCurrentMaxVersion () Q_DECL_OVERRIDE
virtual bool isReadOnly () const Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractConverter
void ValidateInputFile (const QString &currentSchema) const
Q_NORETURN void InvalidVersion (int ver) const
void Save ()
void setVersion (const QString &version)
void Replace (QString &formula, const QString &newName, int position, const QString &token, int &bias) const
void CorrectionsPositions (int position, int bias, QMap< int, QString > &tokens) const
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Private Member Functions
void toVersion0_1_1 ()
void toVersion0_1_2 ()
void toVersion0_1_3 ()
void toVersion0_1_4 ()
void toVersion0_2_0 ()
void toVersion0_2_1 ()
void toVersion0_2_2 ()
void toVersion0_2_3 ()
void toVersion0_2_4 ()
void toVersion0_2_5 ()
void toVersion0_2_6 ()
void toVersion0_2_7 ()
void toVersion0_3_0 ()
void toVersion0_3_1 ()
void toVersion0_3_2 ()
void toVersion0_3_3 ()
void toVersion0_3_4 ()
void toVersion0_3_5 ()
void toVersion0_3_6 ()
void toVersion0_3_7 ()
void toVersion0_3_8 ()
void toVersion0_3_9 ()
void toVersion0_4_0 ()
void toVersion0_4_1 ()
void toVersion0_4_2 ()
void toVersion0_4_3 ()
void toVersion0_4_4 ()
void toVersion0_4_5 ()
void toVersion0_4_6 ()
void toVersion0_4_7 ()
void toVersion0_4_8 ()
void toVersion0_5_0 ()
void toVersion0_5_1 ()
void toVersion0_6_0 ()
void toVersion0_6_1 ()
void toVersion0_6_2 ()
void toVersion0_6_3 ()
void toVersion0_6_4 ()
void toVersion0_6_5 ()
void toVersion0_6_6 ()
void toVersion0_6_7 ()
void toVersion0_6_8 ()
void TagUnitToV0_2_0 ()
void TagIncrementToV0_2_0 ()
void ConvertMeasurementsToV0_2_0 ()
void TagMeasurementsToV0_2_0 ()
void ConvertMeasurementsToV0_2_1 ()
void RemoveColorToolCutV0_3_1 ()
QSet< QString > FixIncrementsToV0_2_0 ()
QString FixIncrementInFormulaToV0_2_0 (const QString &formula, const QSet< QString > &names)
void FixPointExpressionsToV0_2_0 (const QSet< QString > &names)
void FixArcExpressionsToV0_2_0 (const QSet< QString > &names)
void FixPathPointExpressionsToV0_2_0 (const QSet< QString > &names)
void ConvertPointExpressionsToV0_2_0 (const QMap< QString, QString > &names)
void ConvertArcExpressionsToV0_2_0 (const QMap< QString, QString > &names)
void ConvertPathPointExpressionsToV0_2_0 (const QMap< QString, QString > &names)
QString FixMeasurementInFormulaToV0_2_0 (const QString &formula, const QMap< QString, QString > &names)
QString MUnitV0_1_4 () const
QDomElement TagMeasurementsV0_1_4 () const
QDomElement TagIncrementsV0_1_4 () const
void FixToolUnionToV0_2_4 ()
void ParseModelingToV0_2_4 (const QDomElement &modeling)
void SaveChildrenToolUnionToV0_2_4 (quint32 id, const QVector< quint32 > &children)
void FixCutPoint ()
void FixSubPaths (int i, quint32 id, quint32 baseCurve)
void TagRemoveAttributeTypeObjectInV0_4_0 ()
void TagDetailToV0_4_0 ()
void TagUnionDetailsToV0_4_0 ()
QDomElement GetUnionDetailNodesV0_4_0 (const QDomElement &detail)
QDomElement GetUnionChildrenNodesV0_4_0 (const QDomElement &detail)
void LabelTagToV0_4_4 (const QString &tagName)
QDomElement AddTagPatternLabelV0_5_1 ()
void PortPatternLabeltoV0_6_0 (QDomElement &label)
void AddLabelTemplateLineV0_6_0 (QDomElement &label, const QString &text, bool bold, bool italic, int alignment, int fontSizeIncrement)
void PortPieceLabelstoV0_6_0 ()
void RemoveUnusedTagsV0_6_0 ()
void RemoveUniqueTagV0_6_0 (const QString &tag)
void renameAttribute (QDomElement &element, const QString &oldName, const QString &newName, const QString &value) const
Static Private Member Functions
static QMap< QString, QString > OldNamesToNewNames_InV0_2_0 ()
static QMap< QString, QString > OldNamesToNewNames_InV0_2_1 ()
Static Private Attributes
static const QString PatternMinVerStr = QStringLiteral("0.1.0")
Additional Inherited Members
Static Public Member Functions inherited from VAbstractConverter
static int GetVersion (const QString &version)
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Static Protected Member Functions inherited from VAbstractConverter
static void BiasTokens (int position, int bias, QMap< int, QString > &tokens)
Protected Attributes inherited from VAbstractConverter
int m_ver
QString m_convertedFileName
Detailed Description
Definition at line 73 of file vpatternconverter.h.
Constructor & Destructor Documentation
VPatternConverter()
VPatternConverter::VPatternConverter (const QString & fileName) explicit
Definition at line 249 of file vpatternconverter.cpp.
~VPatternConverter()
virtual VPatternConverter::~VPatternConverter () virtual
Member Function Documentation
AddLabelTemplateLineV0_6_0()
void VPatternConverter::AddLabelTemplateLineV0_6_0 (QDomElement & label, const QString & text, bool bold, bool italic, int alignment, int fontSizeIncrement) private
Definition at line 2701 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VDomDocument::SetAttribute(), strAlignment, strBold, strFSIncrement, strItalic, strLine, and strText.
Referenced by PortPatternLabeltoV0_6_0(), and PortPieceLabelstoV0_6_0().
AddTagPatternLabelV0_5_1()
QDomElement VPatternConverter::AddTagPatternLabelV0_5_1 () private
Definition at line 2611 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, strAuthor, strCompanyName, strCustomerName, strDescription, strGradation, strImage, strNotes, strPatternLabel, strPatternName, strPatternNum, and strUnit.
Referenced by toVersion0_6_0().
applyPatches()
void VPatternConverter::applyPatches () protected virtual
Implements VAbstractConverter.
Definition at line 355 of file vpatternconverter.cpp.
References getSchema(), VAbstractConverter::InvalidVersion(), VAbstractConverter::m_convertedFileName, VAbstractConverter::m_ver, toVersion0_1_1(), toVersion0_1_2(), toVersion0_1_3(), toVersion0_1_4(), toVersion0_2_0(), toVersion0_2_1(), toVersion0_2_2(), toVersion0_2_3(), toVersion0_2_4(), toVersion0_2_5(), toVersion0_2_6(), toVersion0_2_7(), toVersion0_3_0(), toVersion0_3_1(), toVersion0_3_2(), toVersion0_3_3(), toVersion0_3_4(), toVersion0_3_5(), toVersion0_3_6(), toVersion0_3_7(), toVersion0_3_8(), toVersion0_3_9(), toVersion0_4_0(), toVersion0_4_1(), toVersion0_4_2(), toVersion0_4_3(), toVersion0_4_4(), toVersion0_4_5(), toVersion0_4_6(), toVersion0_4_7(), toVersion0_4_8(), toVersion0_5_0(), toVersion0_5_1(), toVersion0_6_0(), toVersion0_6_1(), toVersion0_6_2(), toVersion0_6_3(), toVersion0_6_4(), toVersion0_6_5(), toVersion0_6_6(), toVersion0_6_7(), toVersion0_6_8(), V_FALLTHROUGH, and VDomDocument::ValidateXML().
ConvertArcExpressionsToV0_2_0()
void VPatternConverter::ConvertArcExpressionsToV0_2_0 (const QMap< QString, QString > & names) private
Definition at line 1655 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixMeasurementInFormulaToV0_2_0(), VDomDocument::GetParametrString(), PatternMinVer, strAngle1, strAngle2, strArc, strLength, and strRadius.
Referenced by ConvertMeasurementsToV0_2_0(), and ConvertMeasurementsToV0_2_1().
ConvertMeasurementsToV0_2_0()
void VPatternConverter::ConvertMeasurementsToV0_2_0 () private
Definition at line 1368 of file vpatternconverter.cpp.
References ConvertArcExpressionsToV0_2_0(), CONVERTER_VERSION_CHECK, ConvertPathPointExpressionsToV0_2_0(), ConvertPointExpressionsToV0_2_0(), OldNamesToNewNames_InV0_2_0(), and PatternMinVer.
Referenced by toVersion0_2_0().
ConvertMeasurementsToV0_2_1()
void VPatternConverter::ConvertMeasurementsToV0_2_1 () private
Definition at line 1841 of file vpatternconverter.cpp.
References ConvertArcExpressionsToV0_2_0(), CONVERTER_VERSION_CHECK, ConvertPathPointExpressionsToV0_2_0(), ConvertPointExpressionsToV0_2_0(), OldNamesToNewNames_InV0_2_1(), and PatternMinVer.
Referenced by toVersion0_2_1().
ConvertPathPointExpressionsToV0_2_0()
void VPatternConverter::ConvertPathPointExpressionsToV0_2_0 (const QMap< QString, QString > & names) private
Definition at line 1710 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixMeasurementInFormulaToV0_2_0(), VDomDocument::GetParametrString(), PatternMinVer, strAngle, strKAsm1, strKAsm2, and strPathPoint.
Referenced by ConvertMeasurementsToV0_2_0(), and ConvertMeasurementsToV0_2_1().
ConvertPointExpressionsToV0_2_0()
void VPatternConverter::ConvertPointExpressionsToV0_2_0 (const QMap< QString, QString > & names) private
Definition at line 1591 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixMeasurementInFormulaToV0_2_0(), VDomDocument::GetParametrString(), PatternMinVer, strAngle, strC1Radius, strC2Radius, strCRadius, strLength, and strPoint.
Referenced by ConvertMeasurementsToV0_2_0(), and ConvertMeasurementsToV0_2_1().
downgradeToCurrentMaxVersion()
void VPatternConverter::downgradeToCurrentMaxVersion () protected virtual
Implements VAbstractConverter.
Definition at line 536 of file vpatternconverter.cpp.
References PatternMaxVerStr, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
FixArcExpressionsToV0_2_0()
void VPatternConverter::FixArcExpressionsToV0_2_0 (const QSet< QString > & names) private
Definition at line 1491 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixIncrementInFormulaToV0_2_0(), VDomDocument::GetParametrString(), PatternMinVer, strAngle1, strAngle2, strArc, strLength, and strRadius.
Referenced by TagIncrementToV0_2_0().
FixCutPoint()
void VPatternConverter::FixCutPoint () private
Definition at line 2207 of file vpatternconverter.cpp.
References FixSubPaths(), strArc, strCutArc, strCutSpline, strCutSplinePath, strId, strPoint, strSpline, strSplinePath, and strType.
Referenced by toVersion0_3_0().
FixIncrementInFormulaToV0_2_0()
QString VPatternConverter::FixIncrementInFormulaToV0_2_0 (const QString & formula, const QSet< QString > & names) private
Definition at line 1789 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, VAbstractConverter::CorrectionsPositions(), qmu::QmuParserBase::GetTokens(), PatternMinVer, and VAbstractConverter::Replace().
Referenced by FixArcExpressionsToV0_2_0(), FixPathPointExpressionsToV0_2_0(), and FixPointExpressionsToV0_2_0().
FixIncrementsToV0_2_0()
QSet< QString > VPatternConverter::FixIncrementsToV0_2_0 () private
Definition at line 1381 of file vpatternconverter.cpp.
References VException::AddMoreInformation(), CONVERTER_VERSION_CHECK, VExceptionEmptyParameter::ErrorMessage(), VDomDocument::GetParametrString(), PatternMinVer, strBase, strFormula, strId, strIncrement, strKGrowth, strKSize, strName, and TagIncrementsV0_1_4().
Referenced by TagIncrementToV0_2_0().
FixMeasurementInFormulaToV0_2_0()
QString VPatternConverter::FixMeasurementInFormulaToV0_2_0 (const QString & formula, const QMap< QString, QString > & names) private
Definition at line 1755 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, VAbstractConverter::CorrectionsPositions(), PatternMinVer, and VAbstractConverter::Replace().
Referenced by ConvertArcExpressionsToV0_2_0(), ConvertPathPointExpressionsToV0_2_0(), and ConvertPointExpressionsToV0_2_0().
FixPathPointExpressionsToV0_2_0()
void VPatternConverter::FixPathPointExpressionsToV0_2_0 (const QSet< QString > & names) private
Definition at line 1546 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixIncrementInFormulaToV0_2_0(), VDomDocument::GetParametrString(), PatternMinVer, strAngle, strKAsm1, strKAsm2, and strPathPoint.
Referenced by TagIncrementToV0_2_0().
FixPointExpressionsToV0_2_0()
void VPatternConverter::FixPointExpressionsToV0_2_0 (const QSet< QString > & names) private
Definition at line 1427 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixIncrementInFormulaToV0_2_0(), VDomDocument::GetParametrString(), PatternMinVer, strAngle, strC1Radius, strC2Radius, strCRadius, strLength, and strPoint.
Referenced by TagIncrementToV0_2_0().
FixSubPaths()
void VPatternConverter::FixSubPaths (int i, quint32 id, quint32 baseCurve) private
Definition at line 2251 of file vpatternconverter.cpp.
References strArc, strCurve, strCurve1, strCurve2, strCurveIntersectAxis, strCutSpline, strCutSplinePath, strFirstArc, strIdObject, strModeling, strModelingPath, strModelingSpline, strPoint, strPointFromArcAndTangent, strPointOfIntersectionArcs, strPointOfIntersectionCurves, strSecondArc, strSpline, strSplinePath, and strType.
Referenced by FixCutPoint().
FixToolUnionToV0_2_4()
void VPatternConverter::FixToolUnionToV0_2_4 () private
Definition at line 1932 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, ParseModelingToV0_2_4(), PatternMinVer, and strModeling.
Referenced by toVersion0_2_4().
getSchema()
QString VPatternConverter::getSchema (int ver) const protected virtual
Implements VAbstractConverter.
Definition at line 256 of file vpatternconverter.cpp.
References CurrentSchema, and VAbstractConverter::InvalidVersion().
Referenced by applyPatches().
GetUnionChildrenNodesV0_4_0()
QDomElement VPatternConverter::GetUnionChildrenNodesV0_4_0 (const QDomElement & detail) private
Definition at line 2537 of file vpatternconverter.cpp.
References strNodes.
Referenced by TagUnionDetailsToV0_4_0().
GetUnionDetailNodesV0_4_0()
QDomElement VPatternConverter::GetUnionDetailNodesV0_4_0 (const QDomElement & detail) private
Definition at line 2505 of file vpatternconverter.cpp.
References NULL_ID_STR, strIdObject, strNode, strNodes, strReverse, and strType.
Referenced by TagUnionDetailsToV0_4_0().
isReadOnly()
bool VPatternConverter::isReadOnly () const protected virtual
Implements VAbstractConverter.
Definition at line 543 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, falseStr, VDomDocument::getParameterBool(), PatternMaxVer, and strReadOnly.
LabelTagToV0_4_4()
void VPatternConverter::LabelTagToV0_4_4 (const QString & tagName) private
Definition at line 2559 of file vpatternconverter.cpp.
References Cm, CONVERTER_VERSION_CHECK, FromPixel(), Inch, Mm, PatternMinVer, strHeight, strUnit, strWidth, and VDomDocument::UniqueTagText().
Referenced by toVersion0_4_4().
maxVer()
int VPatternConverter::maxVer () const inline protected virtual
Implements VAbstractConverter.
Definition at line 205 of file vpatternconverter.h.
References PatternMaxVer.
maxVerStr()
QString VPatternConverter::maxVerStr () const inline protected virtual
Implements VAbstractConverter.
Definition at line 217 of file vpatternconverter.h.
References PatternMaxVerStr.
minVer()
int VPatternConverter::minVer () const inline protected virtual
Implements VAbstractConverter.
Definition at line 199 of file vpatternconverter.h.
References PatternMinVer.
minVerStr()
QString VPatternConverter::minVerStr () const inline protected virtual
Implements VAbstractConverter.
Definition at line 211 of file vpatternconverter.h.
References PatternMinVerStr.
MUnitV0_1_4()
QString VPatternConverter::MUnitV0_1_4 () const private
Definition at line 1878 of file vpatternconverter.cpp.
References VException::AddMoreInformation(), CONVERTER_VERSION_CHECK, VExceptionEmptyParameter::ErrorMessage(), VDomDocument::GetParametrString(), PatternMinVer, strUnit, and TagMeasurementsV0_1_4().
Referenced by TagUnitToV0_2_0().
OldNamesToNewNames_InV0_2_0()
QMap< QString, QString > VPatternConverter::OldNamesToNewNames_InV0_2_0 () static private
Definition at line 2011 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, and PatternMinVer.
Referenced by ConvertMeasurementsToV0_2_0().
OldNamesToNewNames_InV0_2_1()
QMap< QString, QString > VPatternConverter::OldNamesToNewNames_InV0_2_1 () static private
Definition at line 2191 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, and PatternMinVer.
Referenced by ConvertMeasurementsToV0_2_1().
ParseModelingToV0_2_4()
void VPatternConverter::ParseModelingToV0_2_4 (const QDomElement & modeling) private
Definition at line 1947 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, SaveChildrenToolUnionToV0_2_4(), strId, strIdObject, strIdTool, and strTools.
Referenced by FixToolUnionToV0_2_4().
PortPatternLabeltoV0_6_0()
void VPatternConverter::PortPatternLabeltoV0_6_0 (QDomElement & label) private
Definition at line 2649 of file vpatternconverter.cpp.
References AddLabelTemplateLineV0_6_0(), CONVERTER_VERSION_CHECK, PatternMinVer, strAuthor, strCompanyName, strCustomerName, strPatternName, strPatternNum, strShowDate, strShowMeasurements, strSize, trueStr, and VDomDocument::UniqueTagText().
Referenced by toVersion0_6_0().
PortPieceLabelstoV0_6_0()
void VPatternConverter::PortPieceLabelstoV0_6_0 () private
Definition at line 2720 of file vpatternconverter.cpp.
References AddLabelTemplateLineV0_6_0(), CONVERTER_VERSION_CHECK, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), PatternMinVer, strData, strLetter, strMaterial, strPlacement, and strUserDefined.
Referenced by toVersion0_6_0().
RemoveColorToolCutV0_3_1()
void VPatternConverter::RemoveColorToolCutV0_3_1 () private
Definition at line 1856 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, strColor, strCutArc, strCutSpline, strCutSplinePath, strPoint, and strType.
Referenced by toVersion0_3_1().
RemoveUniqueTagV0_6_0()
void VPatternConverter::RemoveUniqueTagV0_6_0 (const QString & tag) private
Definition at line 2807 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, and PatternMinVer.
Referenced by RemoveUnusedTagsV0_6_0().
RemoveUnusedTagsV0_6_0()
void VPatternConverter::RemoveUnusedTagsV0_6_0 () private
Definition at line 2783 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, RemoveUniqueTagV0_6_0(), strAuthor, strData, strMCP, strShowDate, strShowMeasurements, and strSize.
Referenced by toVersion0_6_0().
renameAttribute()
void VPatternConverter::renameAttribute (QDomElement & element, const QString & oldName, const QString & newName, const QString & value) const private
Definition at line 2875 of file vpatternconverter.cpp.
Referenced by toVersion0_6_5().
SaveChildrenToolUnionToV0_2_4()
void VPatternConverter::SaveChildrenToolUnionToV0_2_4 (quint32 id, const QVector< quint32 > & children) private
Definition at line 1986 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, VDomDocument::elementById(), PatternMinVer, strChild, and strChildren.
Referenced by ParseModelingToV0_2_4().
TagDetailToV0_4_0()
void VPatternConverter::TagDetailToV0_4_0 () private
Definition at line 2419 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, NULL_ID_STR, PatternMinVer, VDomDocument::RemoveAllChildren(), strData, strDetail, strGrainline, strIdObject, strMx, strMy, strNode, strNodes, strPatternInfo, strReverse, strSeamAllowance, strSupplement, strType, and strVersion.
Referenced by toVersion0_4_0().
TagIncrementsV0_1_4()
QDomElement VPatternConverter::TagIncrementsV0_1_4 () const private
Definition at line 1915 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, and strIncrements.
Referenced by FixIncrementsToV0_2_0().
TagIncrementToV0_2_0()
void VPatternConverter::TagIncrementToV0_2_0 () private
Definition at line 1354 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixArcExpressionsToV0_2_0(), FixIncrementsToV0_2_0(), FixPathPointExpressionsToV0_2_0(), FixPointExpressionsToV0_2_0(), and PatternMinVer.
Referenced by toVersion0_2_0().
TagMeasurementsToV0_2_0()
void VPatternConverter::TagMeasurementsToV0_2_0 () private
Definition at line 1823 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, VDomDocument::GetParametrString(), VAbstractConverter::m_convertedFileName, PatternMinVer, strPath, strType, strUnit, and TagMeasurementsV0_1_4().
Referenced by toVersion0_2_0().
TagMeasurementsV0_1_4()
QDomElement VPatternConverter::TagMeasurementsV0_1_4 () const private
Definition at line 1898 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, and strMeasurements.
Referenced by MUnitV0_1_4(), and TagMeasurementsToV0_2_0().
TagRemoveAttributeTypeObjectInV0_4_0()
void VPatternConverter::TagRemoveAttributeTypeObjectInV0_4_0 () private
Definition at line 2389 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, strModeling, and strTypeObject.
Referenced by toVersion0_4_0().
TagUnionDetailsToV0_4_0()
void VPatternConverter::TagUnionDetailsToV0_4_0 () private
Definition at line 2824 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, GetUnionChildrenNodesV0_4_0(), GetUnionDetailNodesV0_4_0(), PatternMinVer, VDomDocument::RemoveAllChildren(), strChildren, strDet, and strTools.
Referenced by toVersion0_4_0().
TagUnitToV0_2_0()
void VPatternConverter::TagUnitToV0_2_0 () private
Definition at line 1339 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, MUnitV0_1_4(), PatternMinVer, strUnit, and strVersion.
Referenced by toVersion0_2_0().
toVersion0_1_1()
void VPatternConverter::toVersion0_1_1 () private
Definition at line 564 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_1_2()
void VPatternConverter::toVersion0_1_2 () private
Definition at line 575 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_1_3()
void VPatternConverter::toVersion0_1_3 () private
Definition at line 586 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_1_4()
void VPatternConverter::toVersion0_1_4 () private
Definition at line 597 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_2_0()
void VPatternConverter::toVersion0_2_0 () private
Definition at line 608 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, ConvertMeasurementsToV0_2_0(), PatternMinVer, VAbstractConverter::Save(), VAbstractConverter::setVersion(), TagIncrementToV0_2_0(), TagMeasurementsToV0_2_0(), and TagUnitToV0_2_0().
Referenced by applyPatches().
toVersion0_2_1()
void VPatternConverter::toVersion0_2_1 () private
Definition at line 623 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, ConvertMeasurementsToV0_2_1(), PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_2_2()
void VPatternConverter::toVersion0_2_2 () private
Definition at line 635 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_2_3()
void VPatternConverter::toVersion0_2_3 () private
Definition at line 646 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_2_4()
void VPatternConverter::toVersion0_2_4 () private
Definition at line 657 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixToolUnionToV0_2_4(), PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_2_5()
void VPatternConverter::toVersion0_2_5 () private
Definition at line 669 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_2_6()
void VPatternConverter::toVersion0_2_6 () private
Definition at line 680 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_2_7()
void VPatternConverter::toVersion0_2_7 () private
Definition at line 691 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_0()
void VPatternConverter::toVersion0_3_0 () private
Definition at line 702 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, FixCutPoint(), PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_1()
void VPatternConverter::toVersion0_3_1 () private
Definition at line 716 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, RemoveColorToolCutV0_3_1(), VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_2()
void VPatternConverter::toVersion0_3_2 () private
Definition at line 728 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_3()
void VPatternConverter::toVersion0_3_3 () private
Definition at line 739 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_4()
void VPatternConverter::toVersion0_3_4 () private
Definition at line 750 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_5()
void VPatternConverter::toVersion0_3_5 () private
Definition at line 761 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_6()
void VPatternConverter::toVersion0_3_6 () private
Definition at line 772 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_7()
void VPatternConverter::toVersion0_3_7 () private
Definition at line 783 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_8()
void VPatternConverter::toVersion0_3_8 () private
Definition at line 794 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_3_9()
void VPatternConverter::toVersion0_3_9 () private
Definition at line 805 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_4_0()
void VPatternConverter::toVersion0_4_0 () private
Definition at line 816 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), VAbstractConverter::setVersion(), TagDetailToV0_4_0(), TagRemoveAttributeTypeObjectInV0_4_0(), and TagUnionDetailsToV0_4_0().
Referenced by applyPatches().
toVersion0_4_1()
void VPatternConverter::toVersion0_4_1 () private
Definition at line 830 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_4_2()
void VPatternConverter::toVersion0_4_2 () private
Definition at line 841 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_4_3()
void VPatternConverter::toVersion0_4_3 () private
Definition at line 852 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_4_4()
void VPatternConverter::toVersion0_4_4 () private
Definition at line 863 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, LabelTagToV0_4_4(), PatternMinVer, VAbstractConverter::Save(), VAbstractConverter::setVersion(), strData, and strPatternInfo.
Referenced by applyPatches().
toVersion0_4_5()
void VPatternConverter::toVersion0_4_5 () private
Definition at line 876 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_4_6()
void VPatternConverter::toVersion0_4_6 () private
Definition at line 886 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_4_7()
void VPatternConverter::toVersion0_4_7 () private
Definition at line 896 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_4_8()
void VPatternConverter::toVersion0_4_8 () private
Definition at line 906 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_5_0()
void VPatternConverter::toVersion0_5_0 () private
Definition at line 916 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_5_1()
void VPatternConverter::toVersion0_5_1 () private
Definition at line 926 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_6_0()
void VPatternConverter::toVersion0_6_0 () private
Definition at line 936 of file vpatternconverter.cpp.
References AddTagPatternLabelV0_5_1(), CONVERTER_VERSION_CHECK, PatternMinVer, PortPatternLabeltoV0_6_0(), PortPieceLabelstoV0_6_0(), RemoveUnusedTagsV0_6_0(), VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_6_1()
void VPatternConverter::toVersion0_6_1 () private
Replaces " passmarkLine" with "notchType"
Replaces " passmarkAngle" with "notchSubType"
Fixes incorrect name & value for lineType attribute
Fixes incorrect value for penStyle attribute
Definition at line 951 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, VDomDocument::map, PatternMinVer, VAbstractConverter::Save(), VAbstractConverter::setVersion(), strArc, strElArc, strHair, strLine, strLineType, strNode, strNotch, strNotchAngle, strNotchCount, strNotchSubType, strNotchType, strOne, strPassmark, strPassmarkAngle, strPassmarkLine, strPath, strPenStyle, strPoint, strShowNotch, strShowSecond, strShowSecondPassmark, strSlitNotch, strSolidLine, strSpline, strT_Notch, strThree, strTMark, strTrue, strTwo, strTypeLine, strV_External, and strVMark.
Referenced by applyPatches().
toVersion0_6_2()
void VPatternConverter::toVersion0_6_2 () private
Definition at line 1087 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_6_3()
void VPatternConverter::toVersion0_6_3 () private
Definition at line 1097 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_6_4()
void VPatternConverter::toVersion0_6_4 () private
Definition at line 1107 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), VAbstractConverter::setVersion(), strLineColor, strLineType, strLineWeight, strPoint, and strType.
Referenced by applyPatches().
toVersion0_6_5()
void VPatternConverter::toVersion0_6_5 () private
Definition at line 1136 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, renameAttribute(), VAbstractConverter::Save(), VAbstractConverter::setVersion(), strAnchor, strAnchors, strBottomAnchor, strBottomPin, strBottomRightAnchor, strBottomRightPin, strCenterAnchor, strCenterPin, strData, strGrainline, strPatternInfo, strPin, strPins, strPoint, strTopAnchor, strTopLeftAnchor, strTopLeftPin, strTopPin, and strType.
Referenced by applyPatches().
toVersion0_6_6()
void VPatternConverter::toVersion0_6_6 () private
Definition at line 1250 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), VAbstractConverter::setVersion(), strDetail, strDetails, strDraftBlock, strDraw, strPiece, strPieces, strTools, strType, and strUnion.
Referenced by applyPatches().
toVersion0_6_7()
void VPatternConverter::toVersion0_6_7 () private
Definition at line 1319 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
toVersion0_6_8()
void VPatternConverter::toVersion0_6_8 () private
Definition at line 1329 of file vpatternconverter.cpp.
References CONVERTER_VERSION_CHECK, PatternMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
Member Data Documentation
CurrentSchema
const QString VPatternConverter::CurrentSchema = QStringLiteral("://schema/pattern/v0.6.8.xsd") static
Definition at line 81 of file vpatternconverter.h.
Referenced by getSchema().
PatternMaxVer
Q_DECL_CONSTEXPR const int VPatternConverter::PatternMaxVer = ((0 <<16)|(6 <<8)|(8)) static
Definition at line 83 of file vpatternconverter.h.
Referenced by isReadOnly(), maxVer(), MainWindow::New(), MainWindow::Save(), and MainWindow::SaveAs().
PatternMaxVerStr
const QString VPatternConverter::PatternMaxVerStr = QStringLiteral("0.6.8") static
Definition at line 80 of file vpatternconverter.h.
Referenced by VPattern::CreateEmptyFile(), downgradeToCurrentMaxVersion(), VAbstractPattern::GetVersion(), maxVerStr(), MainWindow::New(), MainWindow::Save(), MainWindow::SaveAs(), and VAbstractPattern::setVersion().
PatternMinVer
Q_DECL_CONSTEXPR const int VPatternConverter::PatternMinVer = ((0 <<16)|(1 <<8)|(0)) static
Definition at line 82 of file vpatternconverter.h.
Referenced by AddLabelTemplateLineV0_6_0(), AddTagPatternLabelV0_5_1(), ConvertArcExpressionsToV0_2_0(), ConvertMeasurementsToV0_2_0(), ConvertMeasurementsToV0_2_1(), ConvertPathPointExpressionsToV0_2_0(), ConvertPointExpressionsToV0_2_0(), FixArcExpressionsToV0_2_0(), FixIncrementInFormulaToV0_2_0(), FixIncrementsToV0_2_0(), FixMeasurementInFormulaToV0_2_0(), FixPathPointExpressionsToV0_2_0(), FixPointExpressionsToV0_2_0(), FixToolUnionToV0_2_4(), LabelTagToV0_4_4(), minVer(), MUnitV0_1_4(), OldNamesToNewNames_InV0_2_0(), OldNamesToNewNames_InV0_2_1(), ParseModelingToV0_2_4(), VPattern::parsePieceElement(), PortPatternLabeltoV0_6_0(), PortPieceLabelstoV0_6_0(), PatternPieceTool::RefreshDataInFile(), RemoveColorToolCutV0_3_1(), RemoveUniqueTagV0_6_0(), RemoveUnusedTagsV0_6_0(), SaveChildrenToolUnionToV0_2_4(), TagDetailToV0_4_0(), TagIncrementsV0_1_4(), TagIncrementToV0_2_0(), TagMeasurementsToV0_2_0(), TagMeasurementsV0_1_4(), TagRemoveAttributeTypeObjectInV0_4_0(), TagUnionDetailsToV0_4_0(), TagUnitToV0_2_0(), toVersion0_1_1(), toVersion0_1_2(), toVersion0_1_3(), toVersion0_1_4(), toVersion0_2_0(), toVersion0_2_1(), toVersion0_2_2(), toVersion0_2_3(), toVersion0_2_4(), toVersion0_2_5(), toVersion0_2_6(), toVersion0_2_7(), toVersion0_3_0(), toVersion0_3_1(), toVersion0_3_2(), toVersion0_3_3(), toVersion0_3_4(), toVersion0_3_5(), toVersion0_3_6(), toVersion0_3_7(), toVersion0_3_8(), toVersion0_3_9(), toVersion0_4_0(), toVersion0_4_1(), toVersion0_4_2(), toVersion0_4_3(), toVersion0_4_4(), toVersion0_4_5(), toVersion0_4_6(), toVersion0_4_7(), toVersion0_4_8(), toVersion0_5_0(), toVersion0_5_1(), toVersion0_6_0(), toVersion0_6_1(), toVersion0_6_2(), toVersion0_6_3(), toVersion0_6_4(), toVersion0_6_5(), toVersion0_6_6(), toVersion0_6_7(), toVersion0_6_8(), and QT_WARNING_POP::UpdateUnitedNodes().
PatternMinVerStr
const QString VPatternConverter::PatternMinVerStr = QStringLiteral("0.1.0") static private
Definition at line 100 of file vpatternconverter.h.
Referenced by minVerStr().
The documentation for this class was generated from the following files:
src/libs/ifc/xml/vpatternconverter.h
src/libs/ifc/xml/vpatternconverter.cpp