Seamly2D: VExceptionBadId Class Reference
VExceptionBadId Class Reference
The VExceptionBadId class for exception bad id.
#include <vexceptionbadid.h>
Public Member Functions
VExceptionBadId (const QString &error, const quint32 &id)
VExceptionBadId exception bad id.
VExceptionBadId (const QString &error, const QString &key)
VExceptionBadId exception bad id.
VExceptionBadId (const VExceptionBadId &error)
VExceptionBadId copy constructor.
VExceptionBadId & operator= (const VExceptionBadId &error)
virtual ~VExceptionBadId () Q_DECL_EQ_DEFAULT
virtual QString ErrorMessage () const Q_DECL_OVERRIDE
ErrorMessage return main error message.
quint32 BadId () const
BadId return bad id.
QString BadKey () const
BadKey return bad key.
Public Member Functions inherited from VException
VException (const QString &error)
VException constructor exception.
VException (const VException &error)
VException copy constructor.
VException & operator= (const VException &error)
virtual ~VException () Q_DECL_EQ_DEFAULT
virtual Q_NORETURN void raise () const Q_DECL_OVERRIDE
raise method raise for exception
virtual Q_REQUIRED_RESULT VException * clone () const Q_DECL_OVERRIDE
clone clone exception
virtual QString DetailedInformation () const
DetailedInformation return detailed information about error.
QString WhatUtf8 () const
What return string with error.
void AddMoreInformation (const QString &info)
AddMoreInformation add more information for error.
QString MoreInformation () const
MoreInformation return more information for error.
virtual const char * what () const Q_DECL_OVERRIDE
Protected Attributes
quint32 id
id id
QString key
key key
Protected Attributes inherited from VException
QString error
error string with error
QString moreInfo
moreInfo more information about error
Additional Inherited Members
Protected Member Functions inherited from VException
QString MoreInfo (const QString &detInfo) const
Detailed Description
The VExceptionBadId class for exception bad id.
Definition at line 65 of file vexceptionbadid.h.
Constructor & Destructor Documentation
VExceptionBadId() [1/3]
VExceptionBadId::VExceptionBadId (const QString & error, const quint32 & id)
VExceptionBadId exception bad id.
Parameters
error string with error
id id
Definition at line 62 of file vexceptionbadid.cpp.
VExceptionBadId() [2/3]
VExceptionBadId::VExceptionBadId (const QString & error, const QString & key)
VExceptionBadId exception bad id.
Parameters
error string with error
key string key
Definition at line 73 of file vexceptionbadid.cpp.
VExceptionBadId() [3/3]
VExceptionBadId::VExceptionBadId (const VExceptionBadId & error)
VExceptionBadId copy constructor.
Parameters
e exception
Definition at line 81 of file vexceptionbadid.cpp.
~VExceptionBadId()
virtual VExceptionBadId::~VExceptionBadId () virtual
Member Function Documentation
BadId()
quint32 VExceptionBadId::BadId () const inline
BadId return bad id.
Returns
id
Definition at line 89 of file vexceptionbadid.h.
References id.
Referenced by operator=().
BadKey()
QString VExceptionBadId::BadKey () const inline
BadKey return bad key.
Returns
key
Definition at line 99 of file vexceptionbadid.h.
References key.
Referenced by operator=().
ErrorMessage()
QString VExceptionBadId::ErrorMessage () const virtual
ErrorMessage return main error message.
Returns
main error message
Reimplemented from VException.
Definition at line 104 of file vexceptionbadid.cpp.
References VException::error, and key.
Referenced by GroupsWidget::addGroupItem(), MainWindow::changeDraftBlockGlobally(), VDrawTool::ContextMenu(), TMainWindow::Fx(), GroupsWidget::getObjName(), VDrawTool::ObjectName(), VPattern::ParseAnchorPoint(), VPattern::parseIntersectXYTool(), VAbstractPattern::parseItemElement(), VPattern::ParseLineElement(), VPattern::ParseNodeArc(), VPattern::ParseNodeEllipticalArc(), VPattern::ParseNodePoint(), VPattern::ParseNodeSpline(), VPattern::ParseNodeSplinePath(), VPattern::ParseOldToolSpline(), VPattern::ParseOldToolSplinePath(), VPattern::ParsePathElement(), VPattern::parsePieceElement(), VPattern::ParseToolAlongLine(), VPattern::ParseToolArc(), VPattern::ParseToolArcWithLength(), VPattern::ParseToolBasePoint(), VPattern::ParseToolBisector(), VPattern::ParseToolCubicBezier(), VPattern::ParseToolCubicBezierPath(), VPattern::ParseToolCurveIntersectAxis(), VPattern::ParseToolCutArc(), VPattern::ParseToolCutSpline(), VPattern::ParseToolCutSplinePath(), VPattern::ParseToolEllipticalArc(), VPattern::ParseToolEndLine(), VPattern::ParseToolHeight(), VPattern::ParseToolLineIntersect(), VPattern::ParseToolLineIntersectAxis(), VPattern::ParseToolMirrorByAxis(), VPattern::ParseToolMirrorByLine(), VPattern::ParseToolMove(), VPattern::ParseToolNormal(), VPattern::ParseToolPointFromArcAndTangent(), VPattern::ParseToolPointFromCircleAndTangent(), VPattern::ParseToolPointOfContact(), VPattern::ParseToolPointOfIntersectionArcs(), VPattern::ParseToolPointOfIntersectionCircles(), VPattern::ParseToolPointOfIntersectionCurves(), VPattern::ParseToolRotation(), VPattern::ParseToolsElement(), VPattern::ParseToolShoulderPoint(), VPattern::ParseToolSpline(), VPattern::ParseToolSplinePath(), VPattern::ParseToolTriangle(), VPattern::ParseToolTrueDarts(), PatternPieceDialog::pathDialogClosed(), HistoryDialog::record(), TMainWindow::SaveMFullName(), TMainWindow::SaveMName(), and TMainWindow::SaveMValue().
operator=()
VExceptionBadId & VExceptionBadId::operator= (const VExceptionBadId & error)
Definition at line 87 of file vexceptionbadid.cpp.
References BadId(), BadKey(), VException::error, key, and VException::operator=().
Member Data Documentation
id
quint32 VExceptionBadId::id protected
id id
Definition at line 78 of file vexceptionbadid.h.
Referenced by BadId().
key
QString VExceptionBadId::key protected
key key
Definition at line 81 of file vexceptionbadid.h.
Referenced by BadKey(), ErrorMessage(), and operator=().
The documentation for this class was generated from the following files:
src/libs/ifc/exception/vexceptionbadid.h
src/libs/ifc/exception/vexceptionbadid.cpp