Seamly2D: ShortcutsDialog Class Reference
ShortcutsDialog Class Reference
#include <shortcuts_dialog.h>
Public Member Functions
ShortcutsDialog (QWidget *parent=nullptr)
virtual ~ShortcutsDialog ()
Protected Member Functions
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
Private Member Functions
void copyToClipboard ()
void sendToPrinter ()
void exportPdf ()
Private Attributes
Ui::ShortcutsDialog * ui
bool isInitialized
Detailed Description
Definition at line 39 of file shortcuts_dialog.h.
Constructor & Destructor Documentation
ShortcutsDialog()
ShortcutsDialog::ShortcutsDialog (QWidget * parent = nullptr) explicit
Definition at line 50 of file shortcuts_dialog.cpp.
References copyToClipboard(), exportPdf(), sendToPrinter(), and ui.
~ShortcutsDialog()
ShortcutsDialog::~ShortcutsDialog () virtual
Definition at line 349 of file shortcuts_dialog.cpp.
References ui.
Member Function Documentation
copyToClipboard()
void ShortcutsDialog::copyToClipboard () private
Definition at line 375 of file shortcuts_dialog.cpp.
References ui.
Referenced by ShortcutsDialog().
exportPdf()
void ShortcutsDialog::exportPdf () private
Definition at line 392 of file shortcuts_dialog.cpp.
References ui.
Referenced by ShortcutsDialog().
sendToPrinter()
void ShortcutsDialog::sendToPrinter () private
Definition at line 380 of file shortcuts_dialog.cpp.
References ui.
Referenced by ShortcutsDialog().
showEvent()
void ShortcutsDialog::showEvent (QShowEvent * event) protected virtual
Definition at line 355 of file shortcuts_dialog.cpp.
References isInitialized.
Member Data Documentation
isInitialized
bool ShortcutsDialog::isInitialized private
Definition at line 52 of file shortcuts_dialog.h.
Referenced by showEvent().
ui
Ui::ShortcutsDialog* ShortcutsDialog::ui private
Definition at line 51 of file shortcuts_dialog.h.
Referenced by copyToClipboard(), exportPdf(), sendToPrinter(), ShortcutsDialog(), and ~ShortcutsDialog().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/shortcuts_dialog.h
src/app/seamly2d/dialogs/shortcuts_dialog.cpp