Seamly2D: src/libs/vobj/delaunay.h File Reference
delaunay.h File Reference
Classes
struct del_point2d_t
struct delaunay2d_t
Macros
#define DEL_CIRCLE
#define USE_DOUBLE
#define FAST_PREDICATE 1 /* fast but floating point errors are more likely to occur */
#define LOOSE_PREDICATE 2 /* loose with epsilon defined in the delaunay file - errors will happen but less frequently */
#define EXACT_PREDICATE 3 /* use exact arithmetic - slower, but shouldn't produce any floating point error */
#define PREDICATE EXACT_PREDICATE
Typedefs
typedef double real
typedef int(* incircle_predicate_t) (del_point2d_t *p0, del_point2d_t *p1, del_point2d_t *p2, del_point2d_t *p3)
Functions
delaunay2d_t * delaunay2d_from (del_point2d_t *points, quint32 num_points)
void delaunay2d_release (delaunay2d_t *del)
Macro Definition Documentation
DEL_CIRCLE
#define DEL_CIRCLE
Definition at line 23 of file delaunay.h.
EXACT_PREDICATE
#define EXACT_PREDICATE 3 /* use exact arithmetic - slower, but shouldn't produce any floating point error */
Definition at line 36 of file delaunay.h.
FAST_PREDICATE
#define FAST_PREDICATE 1 /* fast but floating point errors are more likely to occur */
Definition at line 34 of file delaunay.h.
LOOSE_PREDICATE
#define LOOSE_PREDICATE 2 /* loose with epsilon defined in the delaunay file - errors will happen but less frequently */
Definition at line 35 of file delaunay.h.
PREDICATE
#define PREDICATE EXACT_PREDICATE
Definition at line 38 of file delaunay.h.
USE_DOUBLE
#define USE_DOUBLE
Definition at line 32 of file delaunay.h.
Typedef Documentation
incircle_predicate_t
typedef int(* incircle_predicate_t) (del_point2d_t *p0, del_point2d_t *p1, del_point2d_t *p2, del_point2d_t *p3)
Definition at line 68 of file delaunay.h.
real
typedef double real
Definition at line 45 of file delaunay.h.
Function Documentation
delaunay2d_from()
delaunay2d_t* delaunay2d_from (del_point2d_t * points, quint32 num_points)
Definition at line 1008 of file delaunay.cpp.
References cmp_points(), del_build_faces(), del_divide_and_conquer(), del_free_halfedges(), exactinit(), delaunay_s::faces, delaunay2d_t::faces, face_s::he, point2d_s::idx, delaunay_s::num_faces, delaunay2d_t::num_faces, delaunay2d_t::num_points, face_s::num_verts, halfedge_s::pair, point_alloc(), point_free(), delaunay_s::points, delaunay2d_t::points, halfedge_s::prev, halfedge_s::vertex, point2d_s::x, del_point2d_t::x, point2d_s::y, and del_point2d_t::y.
Referenced by VObjEngine::drawPath().
delaunay2d_release()
void delaunay2d_release (delaunay2d_t * del)
Definition at line 1082 of file delaunay.cpp.
References delaunay2d_t::faces, and delaunay2d_t::points.
Referenced by VObjEngine::drawPath().