Seamly2D: VSettings Class Reference
VSettings Class Reference
#include <vsettings.h>
Public Member Functions
VSettings (Format format, Scope scope, const QString &organization, const QString &application=QString(), QObject *parent=nullptr)
QString GetLabelLanguage () const
void SetLabelLanguage (const QString &value)
QString GetPathPattern () const
void SetPathPattern (const QString &value)
QString getLayoutPath () const
void SetPathLayout (const QString &value)
bool GetGraphicalOutput () const
void SetGraphicalOutput (const bool &value)
QString GetServer () const
void SetServer (const QString &value)
bool GetServerSecure () const
void SetServerSecure (const bool &value)
bool GetProxy () const
void SetProxy (const bool &value)
QString GetProxyAddress () const
void SetProxyAddress (const QString &value)
QString GetProxyPort () const
void SetProxyPort (const QString &value)
QString GetProxyUser () const
void SetProxyUser (const QString &value)
QString GetProxyPass () const
void SetProxyPass (const QString &value)
QString GetUsername () const
void SetUsername (const QString &value)
bool GetSavePassword () const
void SetSavePassword (const bool &value)
QString GetUserPassword () const
void SetUserPassword (const QString &value)
qreal GetLayoutPaperHeight () const
void SetLayoutPaperHeight (qreal value)
qreal GetLayoutPaperWidth () const
void SetLayoutPaperWidth (qreal value)
qreal GetLayoutShift () const
void SetLayoutShift (qreal value)
qreal GetLayoutWidth () const
void SetLayoutWidth (qreal value)
QMarginsF GetFields (const QMarginsF &def=QMarginsF()) const
void SetFields (const QMarginsF &value)
Cases GetLayoutGroup () const
void SetLayoutGroup (const Cases &value)
bool GetLayoutRotate () const
void SetLayoutRotate (bool value)
int GetLayoutRotationIncrease () const
void SetLayoutRotationIncrease (int value)
bool GetLayoutAutoCrop () const
void SetLayoutAutoCrop (bool value)
bool GetLayoutSaveLength () const
void SetLayoutSaveLength (bool value)
bool GetLayoutUnitePages () const
void SetLayoutUnitePages (bool value)
bool GetIgnoreAllFields () const
void SetIgnoreAllFields (bool value)
bool GetStripOptimization () const
void SetStripOptimization (bool value)
quint8 GetMultiplier () const
void SetMultiplier (quint8 value)
bool GetTextAsPaths () const
void setTextAsPaths (bool value)
QMarginsF GetTiledPDFMargins (const Unit &unit) const
VSettings::GetTiledPDFMargins returns the tiled pdf margins in the given unit. When the setting is called for the first time, the 4 default margins are 10mm.
void setTiledPDFMargins (const QMarginsF &value, const Unit &unit)
VSettings::setTiledPDFMargins sets the setting tiled pdf margins to the given value.
qreal getTiledPDFPaperHeight (const Unit &unit) const
VSettings::getTiledPDFPaperHeight returns the paper height of tiled pdf in the desired unit.
void setTiledPDFPaperHeight (qreal value, const Unit &unit)
VSettings::setTiledPDFPaperHeight sets the tiled pdf paper height.
qreal getTiledPDFPaperWidth (const Unit &unit) const
VSettings::getTiledPDFPaperWidth returns the paper height of tiled pdf in the desired unit.
void setTiledPDFPaperWidth (qreal value, const Unit &unit)
VSettings::setTiledPDFPaperWidth sets the tiled pdf paper width.
PageOrientation getTiledPDFOrientation () const
void setTiledPDFOrientation (PageOrientation value)
Public Member Functions inherited from VCommonSettings
VCommonSettings (Format format, Scope scope, const QString &organization, const QString &application=QString(), QObject *parent=nullptr)
QString GetPathIndividualMeasurements () const
void SetPathIndividualMeasurements (const QString &value)
QString GetPathMultisizeMeasurements () const
void SetPathMultisizeMeasurements (const QString &value)
QString GetPathTemplate () const
void SetPathTemplate (const QString &value)
QString GetPathLabelTemplate () const
void SetPathLabelTemplate (const QString &value)
QString getDefaultPatternTemplate () const
void setDefaultPatternTemplate (const QString &text)
QString getDefaultPieceTemplate () const
void setDefaultPieceTemplate (const QString &text)
bool GetOsSeparator () const
void SetOsSeparator (const bool &value)
bool GetAutosaveState () const
void SetAutosaveState (const bool &value)
int getAutosaveInterval () const
void setAutosaveInterval (const int &value)
bool useModeType () const
void setUseModeType (const bool &value)
bool useLastExportFormat () const
void setUseLastExportFormat (const bool &value)
QString getExportFormat () const
void setExportFormat (const QString &value)
bool GetSendReportState () const
void SetSendReportState (const bool &value)
QString GetLocale () const
void SetLocale (const QString &value)
QString GetPMSystemCode () const
void SetPMSystemCode (const QString &value)
QString GetUnit () const
void SetUnit (const QString &value)
bool getConfirmItemDelete () const
void setConfirmItemDelete (const bool &value)
bool getConfirmFormatRewriting () const
void setConfirmFormatRewriting (const bool &value)
QString getMoveSuffix () const
void setMoveSuffix (const QString &value)
QString getRotateSuffix () const
void setRotateSuffix (const QString &value)
QString getMirrorByAxisSuffix () const
void setMirrorByAxisSuffix (const QString &value)
QString getMirrorByLineSuffix () const
void setMirrorByLineSuffix (const QString &value)
bool getToolBarStyle () const
void setToolBarStyle (const bool &value)
bool getShowToolsToolBar () const
void setShowToolsToolBar (const bool &value)
bool getShowPointToolBar () const
void setShowPointToolBar (const bool &value)
bool getShowLineToolBar () const
void setShowLineToolBar (const bool &value)
bool getShowCurveToolBar () const
void setShowCurveToolBar (const bool &value)
bool getShowArcToolBar () const
void setShowArcToolBar (const bool &value)
bool getShowOpsToolBar () const
void setShowOpsToolBar (const bool &value)
bool getShowPieceToolBar () const
void setShowPieceToolBar (const bool &value)
bool getShowDetailsToolBar () const
void setShowDetailsToolBar (const bool &value)
bool getShowLayoutToolBar () const
void setShowLayoutToolBar (const bool &value)
bool getShowScrollBars () const
void setShowScrollBars (const bool &value)
int getScrollBarWidth () const
void setScrollBarWidth (const int &width)
int getScrollDuration () const
void setScrollDuration (const int &duration)
int getScrollUpdateInterval () const
void setScrollUpdateInterval (const int &interval)
int getScrollSpeedFactor () const
void setScrollSpeedFactor (const int &factor)
bool getZoomModKey () const
void setZoomModKey (const bool &value)
bool isZoomDoubleClick () const
void setZoomDoubleClick (const bool &value)
bool isPanActiveSpaceKey () const
void setPanActiveSpaceKey (const bool &value)
int getZoomSpeedFactor () const
void setZoomSpeedFactor (const int &factor)
int getExportQuality () const
void setExportQuality (const int &value)
QString getZoomRBPositiveColor () const
void setZoomRBPositiveColor (const QString &value)
QString getZoomRBNegativeColor () const
void setZoomRBNegativeColor (const QString &value)
QString getPointNameColor () const
void setPointNameColor (const QString &value)
QString getPointNameHoverColor () const
void setPointNameHoverColor (const QString &value)
QString getAxisOrginColor () const
void setAxisOrginColor (const QString &value)
QString getDefaultLineColor () const
void setDefaultLineColor (const QString &value)
qreal getDefaultLineWeight () const
void setDefaultLineWeight (const qreal &value)
QString getDefaultLineType () const
void setDefaultLineType (const QString &value)
QString getPrimarySupportColor () const
void setPrimarySupportColor (const QString &value)
QString getSecondarySupportColor () const
void setSecondarySupportColor (const QString &value)
QString getTertiarySupportColor () const
void setTertiarySupportColor (const QString &value)
qreal getConstrainValue () const
void setConstrainValue (const qreal &value)
bool getConstrainModKey () const
void setConstrainModKey (const bool &value)
int GetUndoCount () const
void SetUndoCount (const int &value)
QString getSound () const
QString getSelectionSound () const
void setSelectionSound (const QString &value)
QStringList GetRecentFileList () const
void SetRecentFileList (const QStringList &value)
QStringList GetRestoreFileList () const
void SetRestoreFileList (const QStringList &value)
QByteArray GetGeometry () const
void SetGeometry (const QByteArray &value)
QByteArray GetWindowState () const
void SetWindowState (const QByteArray &value)
QByteArray GetToolbarsState () const
void SetToolbarsState (const QByteArray &value)
QSize getPreferenceDialogSize () const
void setPreferenceDialogSize (const QSize &sz)
QSize getPatternPieceDialogSize () const
void setPatternPieceDialogSize (const QSize &sz)
QSize GetFormulaWizardDialogSize () const
void SetFormulaWizardDialogSize (const QSize &sz)
QSize GetIncrementsDialogSize () const
void SetIncrementsDialogSize (const QSize &sz)
int GetLatestSkippedVersion () const
void SetLatestSkippedVersion (int value)
QDate GetDateOfLastRemind () const
void SetDateOfLastRemind (const QDate &date)
bool getForbidPieceFlipping () const
void setForbidPieceFlipping (bool value)
bool isHideSeamLine () const
void setHideSeamLine (bool value)
bool showSeamlineNotch () const
void setShowSeamlineNotch (bool value)
bool showSeamAllowanceNotch () const
void setShowSeamAllowanceNotch (bool value)
qreal getDefaultNotchLength () const
void setDefaultNotchLength (const qreal &value)
qreal getDefaultNotchWidth () const
void setDefaultNotchWidth (const qreal &value)
QString getDefaultNotchType () const
void setDefaultNotchType (const QString &value)
QString getDefaultNotchColor () const
void setDefaultNotchColor (const QString &value)
void SetCSVWithHeader (bool withHeader)
bool GetCSVWithHeader () const
bool GetDefCSVWithHeader () const
void SetCSVCodec (int mib)
int GetCSVCodec () const
int GetDefCSVCodec () const
void SetCSVSeparator (const QChar &separator)
QChar GetCSVSeparator () const
QChar GetDefCSVSeparator () const
void SetDefaultSeamAllowance (double value)
double GetDefaultSeamAllowance ()
returns the default seam allowance. The corresponding unit is the default unit.
QString getDefaultSeamColor () const
void setDefaultSeamColor (const QString &value)
QString getDefaultSeamLinetype () const
void setDefaultSeamLinetype (const QString &value)
qreal getDefaultSeamLineweight () const
void setDefaultSeamLineweight (const qreal &value)
QString getDefaultCutColor () const
void setDefaultCutColor (const QString &value)
QString getDefaultCutLinetype () const
void setDefaultCutLinetype (const QString &value)
qreal getDefaultCutLineweight () const
void setDefaultCutLineweight (const qreal &value)
QString getDefaultInternalColor () const
void setDefaultInternalColor (const QString &value)
QString getDefaultInternalLinetype () const
void setDefaultInternalLinetype (const QString &value)
qreal getDefaultInternalLineweight () const
void setDefaultInternalLineweight (const qreal &value)
QString getDefaultCutoutColor () const
void setDefaultCutoutColor (const QString &value)
QString getDefaultCutoutLinetype () const
void setDefaultCutoutLinetype (const QString &value)
qreal getDefaultCutoutLineweight () const
void setDefaultCutoutLineweight (const qreal &value)
bool showSeamAllowances () const
void setShowSeamAllowances (const bool &value)
bool getDefaultSeamAllowanceVisibilty () const
void setDefaultSeamAllowanceVisibilty (const bool &value)
bool showGrainlines () const
void setShowGrainlines (const bool &value)
bool getDefaultGrainlineVisibilty () const
void setDefaultGrainlineVisibilty (const bool &value)
qreal getDefaultGrainlineLength () const
void setDefaultGrainlineLength (const qreal &value)
QString getDefaultGrainlineColor () const
void setDefaultGrainlineColor (const QString &value)
qreal getDefaultGrainlineLineweight () const
void setDefaultGrainlineLineweight (const qreal &value)
bool showLabels () const
void setShowLabels (const bool &value)
bool showPatternLabels () const
void setShowPatternLabels (const bool &value)
bool showPieceLabels () const
void setShowPieceLabels (const bool &value)
qreal getDefaultLabelWidth () const
void setDefaultLabelWidth (const qreal &value)
qreal getDefaultLabelHeight () const
void setDefaultLabelHeight (const qreal &value)
QString getDefaultLabelColor () const
void setDefaultLabelColor (const QString &value)
QFont getLabelFont () const
void setLabelFont (const QFont &f)
QFont getGuiFont () const
void setGuiFont (const QFont &f)
QFont getPointNameFont () const
void setPointNameFont (const QFont &f)
int getPointNameSize () const
void setPointNameSize (int value)
bool getHidePointNames () const
void setHidePointNames (bool value)
bool getShowAxisOrigin () const
void setShowAxisOrigin (bool value)
bool isWireframe () const
void setWireframe (bool value)
bool getShowControlPoints () const
void setShowControlPoints (bool value)
bool getShowAnchorPoints () const
void setShowAnchorPoints (bool value)
bool getUseToolColor () const
void setUseToolColor (bool value)
int getGuiFontSize () const
void setGuiFontSize (int value)
QString GetLabelDateFormat () const
void SetLabelDateFormat (const QString &format)
QStringList GetUserDefinedDateFormats () const
void SetUserDefinedDateFormats (const QStringList &formats)
QString GetLabelTimeFormat () const
void SetLabelTimeFormat (const QString &format)
QStringList GetUserDefinedTimeFormats () const
void SetUserDefinedTimeFormats (const QStringList &formats)
Static Public Member Functions
static QString GetDefPathPattern ()
static QString GetDefPathLayout ()
static qreal GetDefLayoutShift ()
static qreal GetDefLayoutWidth ()
static Cases GetDefLayoutGroup ()
static bool GetDefLayoutRotate ()
static int GetDefLayoutRotationIncrease ()
static bool GetDefLayoutAutoCrop ()
static bool GetDefLayoutSaveLength ()
static bool GetDefLayoutUnitePages ()
static bool GetDefIgnoreAllFields ()
static bool GetDefStripOptimization ()
static quint8 GetDefMultiplier ()
static bool GetDefTextAsPaths ()
Static Public Member Functions inherited from VCommonSettings
static QString SharePath (const QString &shareItem)
static QString MultisizeTablesPath ()
static QString StandardTemplatesPath ()
static QString PrepareStandardTemplates (const QString &currentPath)
static QString PrepareMultisizeTables (const QString &currentPath)
static QString GetDefPathIndividualMeasurements ()
static QString GetDefPathMultisizeMeasurements ()
static QString GetDefPathTemplate ()
static QString GetDefPathLabelTemplate ()
static QStringList PredefinedDateFormats ()
static QStringList PredefinedTimeFormats ()
Additional Inherited Members
Static Public Attributes inherited from VCommonSettings
static const QString unixStandardSharePath = QStringLiteral("/usr/share/seamly2d")
Detailed Description
Definition at line 68 of file vsettings.h.
Constructor & Destructor Documentation
VSettings()
VSettings::VSettings (Format format, Scope scope, const QString & organization, const QString & application = QString(), QObject * parent = nullptr)
Definition at line 114 of file vsettings.cpp.
Member Function Documentation
GetDefIgnoreAllFields()
bool VSettings::GetDefIgnoreAllFields () static
Definition at line 573 of file vsettings.cpp.
Referenced by GetIgnoreAllFields(), and DialogLayoutSettings::RestoreDefaults().
GetDefLayoutAutoCrop()
bool VSettings::GetDefLayoutAutoCrop () static
Definition at line 519 of file vsettings.cpp.
Referenced by GetLayoutAutoCrop().
GetDefLayoutGroup()
Cases VSettings::GetDefLayoutGroup () static
Definition at line 448 of file vsettings.cpp.
References CaseDesc.
Referenced by GetLayoutGroup(), and DialogLayoutSettings::RestoreDefaults().
GetDefLayoutRotate()
bool VSettings::GetDefLayoutRotate () static
Definition at line 466 of file vsettings.cpp.
Referenced by GetLayoutRotate(), and DialogLayoutSettings::RestoreDefaults().
GetDefLayoutRotationIncrease()
int VSettings::GetDefLayoutRotationIncrease () static
Definition at line 501 of file vsettings.cpp.
Referenced by VCommandLine::DefaultGenerator(), GetLayoutRotationIncrease(), VCommandLine::OptRotation(), DialogLayoutSettings::RestoreDefaults(), and DialogLayoutSettings::SetIncrease().
GetDefLayoutSaveLength()
bool VSettings::GetDefLayoutSaveLength () static
Definition at line 537 of file vsettings.cpp.
Referenced by GetLayoutSaveLength().
GetDefLayoutShift()
qreal VSettings::GetDefLayoutShift () static
Definition at line 368 of file vsettings.cpp.
Referenced by GetLayoutShift(), and DialogLayoutSettings::RestoreDefaults().
GetDefLayoutUnitePages()
bool VSettings::GetDefLayoutUnitePages () static
Definition at line 555 of file vsettings.cpp.
Referenced by GetLayoutUnitePages().
GetDefLayoutWidth()
qreal VSettings::GetDefLayoutWidth () static
Definition at line 396 of file vsettings.cpp.
References Mm, Px, and UnitConvertor().
Referenced by GetLayoutWidth(), and DialogLayoutSettings::RestoreDefaults().
GetDefMultiplier()
quint8 VSettings::GetDefMultiplier () static
Definition at line 609 of file vsettings.cpp.
Referenced by GetMultiplier(), and DialogLayoutSettings::RestoreDefaults().
GetDefPathLayout()
QString VSettings::GetDefPathLayout () static
Definition at line 155 of file vsettings.cpp.
Referenced by PreferencesPathPage::DefaultPath(), and getLayoutPath().
GetDefPathPattern()
QString VSettings::GetDefPathPattern () static
Definition at line 134 of file vsettings.cpp.
Referenced by PreferencesPathPage::DefaultPath(), and GetPathPattern().
GetDefStripOptimization()
bool VSettings::GetDefStripOptimization () static
Definition at line 591 of file vsettings.cpp.
Referenced by GetStripOptimization().
GetDefTextAsPaths()
bool VSettings::GetDefTextAsPaths () static
Definition at line 627 of file vsettings.cpp.
Referenced by GetTextAsPaths().
GetFields()
QMarginsF VSettings::GetFields (const QMarginsF & def = QMarginsF()) const
Definition at line 408 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingFields.
Referenced by DialogLayoutSettings::ReadSettings().
GetGraphicalOutput()
bool VSettings::GetGraphicalOutput () const
Definition at line 176 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingPatternGraphicalOutput.
Referenced by MainWindow::ReadSettings().
GetIgnoreAllFields()
bool VSettings::GetIgnoreAllFields () const
Definition at line 567 of file vsettings.cpp.
References GetDefIgnoreAllFields(), and anonymous_namespace{vsettings.cpp}::settingIgnoreFields.
Referenced by DialogLayoutSettings::ReadSettings().
GetLabelLanguage()
QString VSettings::GetLabelLanguage () const
Definition at line 122 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingConfigurationLabelLanguage.
GetLayoutAutoCrop()
bool VSettings::GetLayoutAutoCrop () const
Definition at line 513 of file vsettings.cpp.
References GetDefLayoutAutoCrop(), and anonymous_namespace{vsettings.cpp}::settingLayoutAutoCrop.
Referenced by DialogLayoutSettings::ReadSettings().
GetLayoutGroup()
Cases VSettings::GetLayoutGroup () const
Definition at line 425 of file vsettings.cpp.
References GetDefLayoutGroup(), anonymous_namespace{vsettings.cpp}::settingLayoutSorting, and UnknownCase.
Referenced by DialogLayoutSettings::ReadSettings().
GetLayoutPaperHeight()
qreal VSettings::GetLayoutPaperHeight () const
Definition at line 308 of file vsettings.cpp.
References Mm, Px, anonymous_namespace{vsettings.cpp}::settingLayoutPaperHeight, and UnitConvertor().
Referenced by DialogLayoutSettings::ReadSettings().
GetLayoutPaperWidth()
qreal VSettings::GetLayoutPaperWidth () const
Definition at line 330 of file vsettings.cpp.
References Mm, Px, anonymous_namespace{vsettings.cpp}::settingLayoutPaperWidth, and UnitConvertor().
Referenced by DialogLayoutSettings::ReadSettings().
getLayoutPath()
QString VSettings::getLayoutPath () const
Definition at line 161 of file vsettings.cpp.
References GetDefPathLayout(), and anonymous_namespace{vsettings.cpp}::settingPathsLayout.
Referenced by PreferencesPathPage::InitTable().
GetLayoutRotate()
bool VSettings::GetLayoutRotate () const
Definition at line 460 of file vsettings.cpp.
References GetDefLayoutRotate(), and anonymous_namespace{vsettings.cpp}::settingLayoutRotate.
Referenced by DialogLayoutSettings::ReadSettings().
GetLayoutRotationIncrease()
int VSettings::GetLayoutRotationIncrease () const
Definition at line 478 of file vsettings.cpp.
References GetDefLayoutRotationIncrease(), and anonymous_namespace{vsettings.cpp}::settingLayoutRotationIncrease.
Referenced by DialogLayoutSettings::ReadSettings().
GetLayoutSaveLength()
bool VSettings::GetLayoutSaveLength () const
Definition at line 531 of file vsettings.cpp.
References GetDefLayoutSaveLength(), and anonymous_namespace{vsettings.cpp}::settingLayoutSaveLength.
Referenced by DialogLayoutSettings::ReadSettings().
GetLayoutShift()
qreal VSettings::GetLayoutShift () const
Definition at line 352 of file vsettings.cpp.
References GetDefLayoutShift(), and anonymous_namespace{vsettings.cpp}::settingLayoutShift.
Referenced by DialogLayoutSettings::ReadSettings().
GetLayoutUnitePages()
bool VSettings::GetLayoutUnitePages () const
Definition at line 549 of file vsettings.cpp.
References GetDefLayoutUnitePages(), and anonymous_namespace{vsettings.cpp}::settingLayoutUnitePages.
Referenced by DialogLayoutSettings::ReadSettings().
GetLayoutWidth()
qreal VSettings::GetLayoutWidth () const
Definition at line 380 of file vsettings.cpp.
References GetDefLayoutWidth(), and anonymous_namespace{vsettings.cpp}::settingLayoutWidth.
Referenced by DialogLayoutSettings::ReadSettings().
GetMultiplier()
quint8 VSettings::GetMultiplier () const
Definition at line 603 of file vsettings.cpp.
References GetDefMultiplier(), and anonymous_namespace{vsettings.cpp}::settingMultiplier.
Referenced by DialogLayoutSettings::ReadSettings().
GetPathPattern()
QString VSettings::GetPathPattern () const
Definition at line 140 of file vsettings.cpp.
References GetDefPathPattern(), and anonymous_namespace{vsettings.cpp}::settingPathsPattern.
Referenced by PreferencesPathPage::InitTable().
GetProxy()
bool VSettings::GetProxy () const
Definition at line 212 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityUseProxy.
GetProxyAddress()
QString VSettings::GetProxyAddress () const
Definition at line 224 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityProxyAddress.
GetProxyPass()
QString VSettings::GetProxyPass () const
Definition at line 260 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityProxyPass.
GetProxyPort()
QString VSettings::GetProxyPort () const
Definition at line 236 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityProxyPort.
GetProxyUser()
QString VSettings::GetProxyUser () const
Definition at line 248 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityProxyUser.
GetSavePassword()
bool VSettings::GetSavePassword () const
Definition at line 284 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunitySavePassword.
GetServer()
QString VSettings::GetServer () const
Definition at line 188 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityServer.
GetServerSecure()
bool VSettings::GetServerSecure () const
Definition at line 200 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityServerSecure.
GetStripOptimization()
bool VSettings::GetStripOptimization () const
Definition at line 585 of file vsettings.cpp.
References GetDefStripOptimization(), and anonymous_namespace{vsettings.cpp}::settingStripOptimization.
Referenced by DialogLayoutSettings::ReadSettings().
GetTextAsPaths()
bool VSettings::GetTextAsPaths () const
Definition at line 621 of file vsettings.cpp.
References GetDefTextAsPaths(), and anonymous_namespace{vsettings.cpp}::settingTextAsPaths.
Referenced by DialogLayoutSettings::ReadSettings().
GetTiledPDFMargins()
QMarginsF VSettings::GetTiledPDFMargins (const Unit & unit) const
VSettings::GetTiledPDFMargins returns the tiled pdf margins in the given unit. When the setting is called for the first time, the 4 default margins are 10mm.
Parameters
unit
Returns
Definition at line 646 of file vsettings.cpp.
References Mm, anonymous_namespace{vsettings.cpp}::settingTiledPDFMargins, and UnitConvertor().
Referenced by ExportLayoutDialog::readSettings(), and MainWindowsNoGUI::SetPrinterSettings().
getTiledPDFOrientation()
PageOrientation VSettings::getTiledPDFOrientation () const
Definition at line 742 of file vsettings.cpp.
References Portrait, and anonymous_namespace{vsettings.cpp}::settingTiledPDFOrientation.
Referenced by MainWindowsNoGUI::PrintPages(), ExportLayoutDialog::readSettings(), and MainWindowsNoGUI::SetPrinterSettings().
getTiledPDFPaperHeight()
qreal VSettings::getTiledPDFPaperHeight (const Unit & unit) const
VSettings::getTiledPDFPaperHeight returns the paper height of tiled pdf in the desired unit.
Parameters
unit the unit to return the value to (internally it's saved as mm)
Returns
Definition at line 681 of file vsettings.cpp.
References Mm, anonymous_namespace{vsettings.cpp}::settingTiledPDFPaperHeight, and UnitConvertor().
Referenced by ExportLayoutDialog::readSettings(), and MainWindowsNoGUI::SetPrinterSettings().
getTiledPDFPaperWidth()
qreal VSettings::getTiledPDFPaperWidth (const Unit & unit) const
VSettings::getTiledPDFPaperWidth returns the paper height of tiled pdf in the desired unit.
Parameters
unit the unit to return the value to (internally it's saved as mm)
Returns
Definition at line 713 of file vsettings.cpp.
References Mm, anonymous_namespace{vsettings.cpp}::settingTiledPDFPaperWidth, and UnitConvertor().
Referenced by ExportLayoutDialog::readSettings(), and MainWindowsNoGUI::SetPrinterSettings().
GetUsername()
QString VSettings::GetUsername () const
Definition at line 272 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityUsername.
GetUserPassword()
QString VSettings::GetUserPassword () const
Definition at line 296 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityUserPassword.
SetFields()
void VSettings::SetFields (const QMarginsF & value)
Definition at line 419 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingFields.
Referenced by DialogLayoutSettings::WriteSettings().
SetGraphicalOutput()
void VSettings::SetGraphicalOutput (const bool & value)
Definition at line 182 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingPatternGraphicalOutput.
Referenced by PreferencesGraphicsViewPage::Apply().
SetIgnoreAllFields()
void VSettings::SetIgnoreAllFields (bool value)
Definition at line 579 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingIgnoreFields.
Referenced by DialogLayoutSettings::WriteSettings().
SetLabelLanguage()
void VSettings::SetLabelLanguage (const QString & value)
Definition at line 128 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingConfigurationLabelLanguage.
Referenced by PreferencesConfigurationPage::Apply().
SetLayoutAutoCrop()
void VSettings::SetLayoutAutoCrop (bool value)
Definition at line 525 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutAutoCrop.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutGroup()
void VSettings::SetLayoutGroup (const Cases & value)
Definition at line 454 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutSorting.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutPaperHeight()
void VSettings::SetLayoutPaperHeight (qreal value)
Definition at line 324 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutPaperHeight.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutPaperWidth()
void VSettings::SetLayoutPaperWidth (qreal value)
Definition at line 346 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutPaperWidth.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutRotate()
void VSettings::SetLayoutRotate (bool value)
Definition at line 472 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutRotate.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutRotationIncrease()
void VSettings::SetLayoutRotationIncrease (int value)
Definition at line 507 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutRotationIncrease.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutSaveLength()
void VSettings::SetLayoutSaveLength (bool value)
Definition at line 543 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutSaveLength.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutShift()
void VSettings::SetLayoutShift (qreal value)
Definition at line 374 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutShift.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutUnitePages()
void VSettings::SetLayoutUnitePages (bool value)
Definition at line 561 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutUnitePages.
Referenced by DialogLayoutSettings::WriteSettings().
SetLayoutWidth()
void VSettings::SetLayoutWidth (qreal value)
Definition at line 402 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingLayoutWidth.
Referenced by DialogLayoutSettings::WriteSettings().
SetMultiplier()
void VSettings::SetMultiplier (quint8 value)
Definition at line 615 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingMultiplier.
Referenced by DialogLayoutSettings::WriteSettings().
SetPathLayout()
void VSettings::SetPathLayout (const QString & value)
Definition at line 168 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingPathsLayout.
Referenced by PreferencesPathPage::Apply().
SetPathPattern()
void VSettings::SetPathPattern (const QString & value)
Definition at line 147 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingPathsPattern.
Referenced by PreferencesPathPage::Apply().
SetProxy()
void VSettings::SetProxy (const bool & value)
Definition at line 218 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityUseProxy.
SetProxyAddress()
void VSettings::SetProxyAddress (const QString & value)
Definition at line 230 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityProxyAddress.
SetProxyPass()
void VSettings::SetProxyPass (const QString & value)
Definition at line 266 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityProxyPass.
SetProxyPort()
void VSettings::SetProxyPort (const QString & value)
Definition at line 242 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityProxyPort.
SetProxyUser()
void VSettings::SetProxyUser (const QString & value)
Definition at line 254 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityProxyUser.
SetSavePassword()
void VSettings::SetSavePassword (const bool & value)
Definition at line 290 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunitySavePassword.
SetServer()
void VSettings::SetServer (const QString & value)
Definition at line 194 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityServer.
SetServerSecure()
void VSettings::SetServerSecure (const bool & value)
Definition at line 206 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityServerSecure.
SetStripOptimization()
void VSettings::SetStripOptimization (bool value)
Definition at line 597 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingStripOptimization.
Referenced by DialogLayoutSettings::WriteSettings().
setTextAsPaths()
void VSettings::setTextAsPaths (bool value)
Definition at line 633 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingTextAsPaths.
Referenced by DialogLayoutSettings::WriteSettings().
setTiledPDFMargins()
void VSettings::setTiledPDFMargins (const QMarginsF & value, const Unit & unit)
VSettings::setTiledPDFMargins sets the setting tiled pdf margins to the given value.
Parameters
value the margins to save
unit the unit in which are the value. Necessary because we save the values internaly as mm so there is conversion beeing made.
Definition at line 667 of file vsettings.cpp.
References Mm, anonymous_namespace{vsettings.cpp}::settingTiledPDFMargins, and UnitConvertor().
Referenced by ExportLayoutDialog::writeSettings().
setTiledPDFOrientation()
void VSettings::setTiledPDFOrientation (PageOrientation value)
Definition at line 752 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingTiledPDFOrientation.
Referenced by ExportLayoutDialog::writeSettings().
setTiledPDFPaperHeight()
void VSettings::setTiledPDFPaperHeight (qreal value, const Unit & unit)
VSettings::setTiledPDFPaperHeight sets the tiled pdf paper height.
Parameters
value in Mm
unit unit of the given value
Definition at line 702 of file vsettings.cpp.
References Mm, anonymous_namespace{vsettings.cpp}::settingTiledPDFPaperHeight, and UnitConvertor().
Referenced by ExportLayoutDialog::writeSettings().
setTiledPDFPaperWidth()
void VSettings::setTiledPDFPaperWidth (qreal value, const Unit & unit)
VSettings::setTiledPDFPaperWidth sets the tiled pdf paper width.
Parameters
unit unit of the given value
value in Mm
Definition at line 736 of file vsettings.cpp.
References Mm, anonymous_namespace{vsettings.cpp}::settingTiledPDFPaperWidth, and UnitConvertor().
Referenced by ExportLayoutDialog::writeSettings().
SetUsername()
void VSettings::SetUsername (const QString & value)
Definition at line 278 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityUsername.
SetUserPassword()
void VSettings::SetUserPassword (const QString & value)
Definition at line 302 of file vsettings.cpp.
References anonymous_namespace{vsettings.cpp}::settingCommunityUserPassword.
The documentation for this class was generated from the following files:
src/libs/vmisc/vsettings.h
src/libs/vmisc/vsettings.cpp