Seamly2D: XSerializeEngine Class Reference
XSerializeEngine Class Reference
#include <XSerializeEngine.hpp>
Public Types
enum { mode_Store , mode_Load }
enum { mode_Store , mode_Load }
enum { mode_Store , mode_Load }
typedef unsigned int XSerializedObjectId_t
typedef unsigned int XSerializedObjectId_t
typedef unsigned int XSerializedObjectId_t
Public Member Functions
~XSerializeEngine ()
XSerializeEngine (BinInputStream *inStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize=8192)
XSerializeEngine (BinOutputStream *outStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize=8192)
void flush ()
bool isStoring () const
bool isLoading () const
XMLGrammarPool * getGrammarPool () const
XMLStringPool * getStringPool () const
MemoryManager * getMemoryManager () const
unsigned int getStorerLevel () const
void write (XSerializable *const objectToWrite)
void write (XProtoType *const protoType)
void write (const XMLByte *const toWrite, XMLSize_t writeLen)
void write (const XMLCh *const toWrite, XMLSize_t writeLen)
void writeString (const XMLCh *const toWrite, const XMLSize_t bufferLen=0, bool toWriteBufLen=false)
void writeString (const XMLByte *const toWrite, const XMLSize_t bufferLen=0, bool toWriteBufLen=false)
XSerializable * read (XProtoType *const protoType)
bool read (XProtoType *const protoType, XSerializedObjectId_t *objTag)
void read (XMLByte *const toRead, XMLSize_t readLen)
void read (XMLCh *const toRead, XMLSize_t readLen)
void readString (XMLCh *&toRead, XMLSize_t &bufferLen, XMLSize_t &dataLen, bool toReadBufLen=false)
void readString (XMLCh *&toRead, XMLSize_t &bufferLen)
void readString (XMLCh *&toRead)
void readString (XMLByte *&toRead, XMLSize_t &bufferLen, XMLSize_t &dataLen, bool toReadBufLen=false)
void readString (XMLByte *&toRead, XMLSize_t &bufferLen)
void readString (XMLByte *&toRead)
bool needToStoreObject (void *const templateObjectToWrite)
bool needToLoadObject (void **templateObjectToRead)
void registerObject (void *const templateObjectToRegister)
XSerializeEngine & operator<< (XMLByte)
XSerializeEngine & operator<< (XMLCh)
XSerializeEngine & operator<< (char)
XSerializeEngine & operator<< (short)
XSerializeEngine & operator<< (int)
XSerializeEngine & operator<< (unsigned int)
XSerializeEngine & operator<< (long)
XSerializeEngine & operator<< (unsigned long)
XSerializeEngine & operator<< (float)
XSerializeEngine & operator<< (double)
XSerializeEngine & operator<< (bool)
void writeSize (XMLSize_t)
void writeInt64 (XMLInt64)
void writeUInt64 (XMLUInt64)
XSerializeEngine & operator>> (XMLByte &)
XSerializeEngine & operator>> (XMLCh &)
XSerializeEngine & operator>> (char &)
XSerializeEngine & operator>> (short &)
XSerializeEngine & operator>> (int &)
XSerializeEngine & operator>> (unsigned int &)
XSerializeEngine & operator>> (long &)
XSerializeEngine & operator>> (unsigned long &)
XSerializeEngine & operator>> (float &)
XSerializeEngine & operator>> (double &)
XSerializeEngine & operator>> (bool &)
void readSize (XMLSize_t &)
void readInt64 (XMLInt64 &)
void readUInt64 (XMLUInt64 &)
XMLSize_t getBufSize () const
XMLSize_t getBufCur () const
XMLSize_t getBufCurAccumulated () const
unsigned long getBufCount () const
void trace (char *) const
~XSerializeEngine ()
XSerializeEngine (BinInputStream *inStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize=8192)
XSerializeEngine (BinOutputStream *outStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize=8192)
void flush ()
bool isStoring () const
bool isLoading () const
XMLGrammarPool * getGrammarPool () const
XMLStringPool * getStringPool () const
MemoryManager * getMemoryManager () const
unsigned int getStorerLevel () const
void write (XSerializable *const objectToWrite)
void write (XProtoType *const protoType)
void write (const XMLByte *const toWrite, XMLSize_t writeLen)
void write (const XMLCh *const toWrite, XMLSize_t writeLen)
void writeString (const XMLCh *const toWrite, const XMLSize_t bufferLen=0, bool toWriteBufLen=false)
void writeString (const XMLByte *const toWrite, const XMLSize_t bufferLen=0, bool toWriteBufLen=false)
XSerializable * read (XProtoType *const protoType)
bool read (XProtoType *const protoType, XSerializedObjectId_t *objTag)
void read (XMLByte *const toRead, XMLSize_t readLen)
void read (XMLCh *const toRead, XMLSize_t readLen)
void readString (XMLCh *&toRead, XMLSize_t &bufferLen, XMLSize_t &dataLen, bool toReadBufLen=false)
void readString (XMLCh *&toRead, XMLSize_t &bufferLen)
void readString (XMLCh *&toRead)
void readString (XMLByte *&toRead, XMLSize_t &bufferLen, XMLSize_t &dataLen, bool toReadBufLen=false)
void readString (XMLByte *&toRead, XMLSize_t &bufferLen)
void readString (XMLByte *&toRead)
bool needToStoreObject (void *const templateObjectToWrite)
bool needToLoadObject (void **templateObjectToRead)
void registerObject (void *const templateObjectToRegister)
XSerializeEngine & operator<< (XMLByte)
XSerializeEngine & operator<< (XMLCh)
XSerializeEngine & operator<< (char)
XSerializeEngine & operator<< (short)
XSerializeEngine & operator<< (int)
XSerializeEngine & operator<< (unsigned int)
XSerializeEngine & operator<< (long)
XSerializeEngine & operator<< (unsigned long)
XSerializeEngine & operator<< (float)
XSerializeEngine & operator<< (double)
XSerializeEngine & operator<< (bool)
void writeSize (XMLSize_t)
void writeInt64 (XMLInt64)
void writeUInt64 (XMLUInt64)
XSerializeEngine & operator>> (XMLByte &)
XSerializeEngine & operator>> (XMLCh &)
XSerializeEngine & operator>> (char &)
XSerializeEngine & operator>> (short &)
XSerializeEngine & operator>> (int &)
XSerializeEngine & operator>> (unsigned int &)
XSerializeEngine & operator>> (long &)
XSerializeEngine & operator>> (unsigned long &)
XSerializeEngine & operator>> (float &)
XSerializeEngine & operator>> (double &)
XSerializeEngine & operator>> (bool &)
void readSize (XMLSize_t &)
void readInt64 (XMLInt64 &)
void readUInt64 (XMLUInt64 &)
XMLSize_t getBufSize () const
XMLSize_t getBufCur () const
XMLSize_t getBufCurAccumulated () const
unsigned long getBufCount () const
void trace (char *) const
~XSerializeEngine ()
XSerializeEngine (BinInputStream *inStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize=8192)
XSerializeEngine (BinOutputStream *outStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize=8192)
void flush ()
bool isStoring () const
bool isLoading () const
XMLGrammarPool * getGrammarPool () const
XMLStringPool * getStringPool () const
MemoryManager * getMemoryManager () const
unsigned int getStorerLevel () const
void write (XSerializable *const objectToWrite)
void write (XProtoType *const protoType)
void write (const XMLByte *const toWrite, XMLSize_t writeLen)
void write (const XMLCh *const toWrite, XMLSize_t writeLen)
void writeString (const XMLCh *const toWrite, const XMLSize_t bufferLen=0, bool toWriteBufLen=false)
void writeString (const XMLByte *const toWrite, const XMLSize_t bufferLen=0, bool toWriteBufLen=false)
XSerializable * read (XProtoType *const protoType)
bool read (XProtoType *const protoType, XSerializedObjectId_t *objTag)
void read (XMLByte *const toRead, XMLSize_t readLen)
void read (XMLCh *const toRead, XMLSize_t readLen)
void readString (XMLCh *&toRead, XMLSize_t &bufferLen, XMLSize_t &dataLen, bool toReadBufLen=false)
void readString (XMLCh *&toRead, XMLSize_t &bufferLen)
void readString (XMLCh *&toRead)
void readString (XMLByte *&toRead, XMLSize_t &bufferLen, XMLSize_t &dataLen, bool toReadBufLen=false)
void readString (XMLByte *&toRead, XMLSize_t &bufferLen)
void readString (XMLByte *&toRead)
bool needToStoreObject (void *const templateObjectToWrite)
bool needToLoadObject (void **templateObjectToRead)
void registerObject (void *const templateObjectToRegister)
XSerializeEngine & operator<< (XMLByte)
XSerializeEngine & operator<< (XMLCh)
XSerializeEngine & operator<< (char)
XSerializeEngine & operator<< (short)
XSerializeEngine & operator<< (int)
XSerializeEngine & operator<< (unsigned int)
XSerializeEngine & operator<< (long)
XSerializeEngine & operator<< (unsigned long)
XSerializeEngine & operator<< (float)
XSerializeEngine & operator<< (double)
XSerializeEngine & operator<< (bool)
void writeSize (XMLSize_t)
void writeInt64 (XMLInt64)
void writeUInt64 (XMLUInt64)
XSerializeEngine & operator>> (XMLByte &)
XSerializeEngine & operator>> (XMLCh &)
XSerializeEngine & operator>> (char &)
XSerializeEngine & operator>> (short &)
XSerializeEngine & operator>> (int &)
XSerializeEngine & operator>> (unsigned int &)
XSerializeEngine & operator>> (long &)
XSerializeEngine & operator>> (unsigned long &)
XSerializeEngine & operator>> (float &)
XSerializeEngine & operator>> (double &)
XSerializeEngine & operator>> (bool &)
void readSize (XMLSize_t &)
void readInt64 (XMLInt64 &)
void readUInt64 (XMLUInt64 &)
XMLSize_t getBufSize () const
XMLSize_t getBufCur () const
XMLSize_t getBufCurAccumulated () const
unsigned long getBufCount () const
void trace (char *) const
Static Public Attributes
static const bool toReadBufferLen
static const bool toWriteBufferLen
Private Member Functions
XSerializeEngine ()
XSerializeEngine (const XSerializeEngine &)
XSerializeEngine & operator= (const XSerializeEngine &)
XSerializedObjectId_t lookupStorePool (void *const objectPtr) const
void addStorePool (void *const objectPtr)
XSerializable * lookupLoadPool (XSerializedObjectId_t objectTag) const
void addLoadPool (void *const objectPtr)
void checkAndFillBuffer (XMLSize_t bytesNeedToRead)
void checkAndFlushBuffer (XMLSize_t bytesNeedToWrite)
void fillBuffer ()
void flushBuffer ()
void pumpCount ()
void resetBuffer ()
void ensureStoring () const
void ensureLoading () const
void ensureStoreBuffer () const
void ensureLoadBuffer () const
void ensurePointer (void *const) const
void Assert (bool toEval, const XMLExcepts::Codes toThrow) const
XMLSize_t calBytesNeeded (XMLSize_t) const
XMLSize_t alignAdjust (XMLSize_t) const
void alignBufCur (XMLSize_t)
XSerializeEngine ()
XSerializeEngine (const XSerializeEngine &)
XSerializeEngine & operator= (const XSerializeEngine &)
XSerializedObjectId_t lookupStorePool (void *const objectPtr) const
void addStorePool (void *const objectPtr)
XSerializable * lookupLoadPool (XSerializedObjectId_t objectTag) const
void addLoadPool (void *const objectPtr)
void checkAndFillBuffer (XMLSize_t bytesNeedToRead)
void checkAndFlushBuffer (XMLSize_t bytesNeedToWrite)
void fillBuffer ()
void flushBuffer ()
void pumpCount ()
void resetBuffer ()
void ensureStoring () const
void ensureLoading () const
void ensureStoreBuffer () const
void ensureLoadBuffer () const
void ensurePointer (void *const) const
void Assert (bool toEval, const XMLExcepts::Codes toThrow) const
XMLSize_t calBytesNeeded (XMLSize_t) const
XMLSize_t alignAdjust (XMLSize_t) const
void alignBufCur (XMLSize_t)
XSerializeEngine ()
XSerializeEngine (const XSerializeEngine &)
XSerializeEngine & operator= (const XSerializeEngine &)
XSerializedObjectId_t lookupStorePool (void *const objectPtr) const
void addStorePool (void *const objectPtr)
XSerializable * lookupLoadPool (XSerializedObjectId_t objectTag) const
void addLoadPool (void *const objectPtr)
void checkAndFillBuffer (XMLSize_t bytesNeedToRead)
void checkAndFlushBuffer (XMLSize_t bytesNeedToWrite)
void fillBuffer ()
void flushBuffer ()
void pumpCount ()
void resetBuffer ()
void ensureStoring () const
void ensureLoading () const
void ensureStoreBuffer () const
void ensureLoadBuffer () const
void ensurePointer (void *const) const
void Assert (bool toEval, const XMLExcepts::Codes toThrow) const
XMLSize_t calBytesNeeded (XMLSize_t) const
XMLSize_t alignAdjust (XMLSize_t) const
void alignBufCur (XMLSize_t)
Private Attributes
const short fStoreLoad
unsigned int fStorerLevel
XMLGrammarPool *const fGrammarPool
BinInputStream *const fInputStream
BinOutputStream *const fOutputStream
unsigned long fBufCount
const XMLSize_t fBufSize
XMLByte *const fBufStart
XMLByte *const fBufEnd
XMLByte * fBufCur
XMLByte * fBufLoadMax
RefHashTableOf< XSerializedObjectId, PtrHasher > * fStorePool
ValueVectorOf< void * > * fLoadPool
XSerializedObjectId_t fObjectCount
Friends
class XTemplateSerializer
class XMLGrammarPoolImpl
XSerializeEngine & operator<< (XSerializeEngine &, XSerializable *const)
XSerializeEngine & operator<< (XSerializeEngine &, XSerializable *const)
XSerializeEngine & operator<< (XSerializeEngine &, XSerializable *const)
Detailed Description
Definition at line 43 of file XSerializeEngine.hpp.
Member Typedef Documentation
XSerializedObjectId_t [1/3]
typedef unsigned int XSerializeEngine::XSerializedObjectId_t
Definition at line 54 of file XSerializeEngine.hpp.
XSerializedObjectId_t [2/3]
typedef unsigned int XSerializeEngine::XSerializedObjectId_t
Definition at line 54 of file XSerializeEngine.hpp.
XSerializedObjectId_t [3/3]
typedef unsigned int XSerializeEngine::XSerializedObjectId_t
Definition at line 54 of file XSerializeEngine.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
mode_Store
mode_Load
Definition at line 47 of file XSerializeEngine.hpp.
anonymous enum
anonymous enum
Enumerator
mode_Store
mode_Load
Definition at line 47 of file XSerializeEngine.hpp.
anonymous enum
anonymous enum
Enumerator
mode_Store
mode_Load
Definition at line 47 of file XSerializeEngine.hpp.
Constructor & Destructor Documentation
~XSerializeEngine() [1/3]
XSerializeEngine::~XSerializeEngine ()
XSerializeEngine() [1/12]
XSerializeEngine::XSerializeEngine (BinInputStream * inStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize = 8192)
XSerializeEngine() [2/12]
XSerializeEngine::XSerializeEngine (BinOutputStream * outStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize = 8192)
XSerializeEngine() [3/12]
XSerializeEngine::XSerializeEngine () private
XSerializeEngine() [4/12]
XSerializeEngine::XSerializeEngine (const XSerializeEngine &) private
~XSerializeEngine() [2/3]
XSerializeEngine::~XSerializeEngine ()
XSerializeEngine() [5/12]
XSerializeEngine::XSerializeEngine (BinInputStream * inStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize = 8192)
XSerializeEngine() [6/12]
XSerializeEngine::XSerializeEngine (BinOutputStream * outStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize = 8192)
XSerializeEngine() [7/12]
XSerializeEngine::XSerializeEngine () private
XSerializeEngine() [8/12]
XSerializeEngine::XSerializeEngine (const XSerializeEngine &) private
~XSerializeEngine() [3/3]
XSerializeEngine::~XSerializeEngine ()
XSerializeEngine() [9/12]
XSerializeEngine::XSerializeEngine (BinInputStream * inStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize = 8192)
XSerializeEngine() [10/12]
XSerializeEngine::XSerializeEngine (BinOutputStream * outStream, XMLGrammarPool *const gramPool, XMLSize_t bufSize = 8192)
XSerializeEngine() [11/12]
XSerializeEngine::XSerializeEngine () private
XSerializeEngine() [12/12]
XSerializeEngine::XSerializeEngine (const XSerializeEngine &) private
Member Function Documentation
addLoadPool() [1/3]
void XSerializeEngine::addLoadPool (void *const objectPtr) private
addLoadPool() [2/3]
void XSerializeEngine::addLoadPool (void *const objectPtr) private
addLoadPool() [3/3]
void XSerializeEngine::addLoadPool (void *const objectPtr) private
addStorePool() [1/3]
void XSerializeEngine::addStorePool (void *const objectPtr) private
addStorePool() [2/3]
void XSerializeEngine::addStorePool (void *const objectPtr) private
addStorePool() [3/3]
void XSerializeEngine::addStorePool (void *const objectPtr) private
alignAdjust() [1/3]
XMLSize_t XSerializeEngine::alignAdjust (XMLSize_t) const inline private
alignAdjust() [2/3]
XMLSize_t XSerializeEngine::alignAdjust (XMLSize_t) const inline private
alignAdjust() [3/3]
XMLSize_t XSerializeEngine::alignAdjust (XMLSize_t) const inline private
alignBufCur() [1/3]
void XSerializeEngine::alignBufCur (XMLSize_t) inline private
alignBufCur() [2/3]
void XSerializeEngine::alignBufCur (XMLSize_t) inline private
alignBufCur() [3/3]
void XSerializeEngine::alignBufCur (XMLSize_t) inline private
Assert() [1/3]
void XSerializeEngine::Assert (bool toEval, const XMLExcepts::Codes toThrow) const inline private
Definition at line 740 of file XSerializeEngine.hpp.
References getMemoryManager(), and ThrowXMLwithMemMgr.
Referenced by ensureLoading(), and ensureStoring().
Assert() [2/3]
void XSerializeEngine::Assert (bool toEval, const XMLExcepts::Codes toThrow) const inline private
Assert() [3/3]
void XSerializeEngine::Assert (bool toEval, const XMLExcepts::Codes toThrow) const inline private
calBytesNeeded() [1/3]
XMLSize_t XSerializeEngine::calBytesNeeded (XMLSize_t) const inline private
calBytesNeeded() [2/3]
XMLSize_t XSerializeEngine::calBytesNeeded (XMLSize_t) const inline private
calBytesNeeded() [3/3]
XMLSize_t XSerializeEngine::calBytesNeeded (XMLSize_t) const inline private
checkAndFillBuffer() [1/3]
void XSerializeEngine::checkAndFillBuffer (XMLSize_t bytesNeedToRead) inline private
checkAndFillBuffer() [2/3]
void XSerializeEngine::checkAndFillBuffer (XMLSize_t bytesNeedToRead) inline private
checkAndFillBuffer() [3/3]
void XSerializeEngine::checkAndFillBuffer (XMLSize_t bytesNeedToRead) inline private
checkAndFlushBuffer() [1/3]
void XSerializeEngine::checkAndFlushBuffer (XMLSize_t bytesNeedToWrite) inline private
checkAndFlushBuffer() [2/3]
void XSerializeEngine::checkAndFlushBuffer (XMLSize_t bytesNeedToWrite) inline private
checkAndFlushBuffer() [3/3]
void XSerializeEngine::checkAndFlushBuffer (XMLSize_t bytesNeedToWrite) inline private
ensureLoadBuffer() [1/3]
void XSerializeEngine::ensureLoadBuffer () const inline private
ensureLoadBuffer() [2/3]
void XSerializeEngine::ensureLoadBuffer () const inline private
ensureLoadBuffer() [3/3]
void XSerializeEngine::ensureLoadBuffer () const inline private
ensureLoading() [1/3]
void XSerializeEngine::ensureLoading () const inline private
Definition at line 733 of file XSerializeEngine.hpp.
References Assert(), isLoading(), and XMLExcepts::XSer_Loading_Violation.
ensureLoading() [2/3]
void XSerializeEngine::ensureLoading () const inline private
ensureLoading() [3/3]
void XSerializeEngine::ensureLoading () const inline private
ensurePointer() [1/3]
void XSerializeEngine::ensurePointer (void * const) const inline private
ensurePointer() [2/3]
void XSerializeEngine::ensurePointer (void * const) const inline private
ensurePointer() [3/3]
void XSerializeEngine::ensurePointer (void * const) const inline private
ensureStoreBuffer() [1/3]
void XSerializeEngine::ensureStoreBuffer () const inline private
ensureStoreBuffer() [2/3]
void XSerializeEngine::ensureStoreBuffer () const inline private
ensureStoreBuffer() [3/3]
void XSerializeEngine::ensureStoreBuffer () const inline private
ensureStoring() [1/3]
void XSerializeEngine::ensureStoring () const inline private
Definition at line 728 of file XSerializeEngine.hpp.
References Assert(), isStoring(), and XMLExcepts::XSer_Storing_Violation.
ensureStoring() [2/3]
void XSerializeEngine::ensureStoring () const inline private
ensureStoring() [3/3]
void XSerializeEngine::ensureStoring () const inline private
fillBuffer() [1/3]
void XSerializeEngine::fillBuffer () private
fillBuffer() [2/3]
void XSerializeEngine::fillBuffer () private
fillBuffer() [3/3]
void XSerializeEngine::fillBuffer () private
flush() [1/3]
void XSerializeEngine::flush ()
flush() [2/3]
void XSerializeEngine::flush ()
flush() [3/3]
void XSerializeEngine::flush ()
flushBuffer() [1/3]
void XSerializeEngine::flushBuffer () private
flushBuffer() [2/3]
void XSerializeEngine::flushBuffer () private
flushBuffer() [3/3]
void XSerializeEngine::flushBuffer () private
getBufCount() [1/3]
unsigned long XSerializeEngine::getBufCount () const inline
Definition at line 797 of file XSerializeEngine.hpp.
References fBufCount.
getBufCount() [2/3]
unsigned long XSerializeEngine::getBufCount () const inline
getBufCount() [3/3]
unsigned long XSerializeEngine::getBufCount () const inline
getBufCur() [1/3]
XMLSize_t XSerializeEngine::getBufCur () const inline
Definition at line 785 of file XSerializeEngine.hpp.
References fBufCur, and fBufStart.
getBufCur() [2/3]
XMLSize_t XSerializeEngine::getBufCur () const inline
getBufCur() [3/3]
XMLSize_t XSerializeEngine::getBufCur () const inline
getBufCurAccumulated() [1/3]
XMLSize_t XSerializeEngine::getBufCurAccumulated () const inline
Definition at line 791 of file XSerializeEngine.hpp.
References fBufCount, fBufCur, fBufSize, fBufStart, and isStoring().
getBufCurAccumulated() [2/3]
XMLSize_t XSerializeEngine::getBufCurAccumulated () const inline
getBufCurAccumulated() [3/3]
XMLSize_t XSerializeEngine::getBufCurAccumulated () const inline
getBufSize() [1/3]
XMLSize_t XSerializeEngine::getBufSize () const inline
Definition at line 779 of file XSerializeEngine.hpp.
References fBufSize.
getBufSize() [2/3]
XMLSize_t XSerializeEngine::getBufSize () const inline
getBufSize() [3/3]
XMLSize_t XSerializeEngine::getBufSize () const inline
getGrammarPool() [1/3]
XMLGrammarPool* XSerializeEngine::getGrammarPool () const
getGrammarPool() [2/3]
XMLGrammarPool* XSerializeEngine::getGrammarPool () const
getGrammarPool() [3/3]
XMLGrammarPool* XSerializeEngine::getGrammarPool () const
getMemoryManager() [1/3]
MemoryManager* XSerializeEngine::getMemoryManager () const
Referenced by Assert().
getMemoryManager() [2/3]
MemoryManager* XSerializeEngine::getMemoryManager () const
getMemoryManager() [3/3]
MemoryManager* XSerializeEngine::getMemoryManager () const
getStorerLevel() [1/3]
unsigned int XSerializeEngine::getStorerLevel () const inline
Definition at line 803 of file XSerializeEngine.hpp.
References fStorerLevel.
getStorerLevel() [2/3]
unsigned int XSerializeEngine::getStorerLevel () const inline
getStorerLevel() [3/3]
unsigned int XSerializeEngine::getStorerLevel () const inline
getStringPool() [1/3]
XMLStringPool* XSerializeEngine::getStringPool () const
getStringPool() [2/3]
XMLStringPool* XSerializeEngine::getStringPool () const
getStringPool() [3/3]
XMLStringPool* XSerializeEngine::getStringPool () const
isLoading() [1/3]
bool XSerializeEngine::isLoading () const inline
Definition at line 716 of file XSerializeEngine.hpp.
References fStoreLoad, and mode_Load.
Referenced by ensureLoading().
isLoading() [2/3]
bool XSerializeEngine::isLoading () const inline
isLoading() [3/3]
bool XSerializeEngine::isLoading () const inline
isStoring() [1/3]
bool XSerializeEngine::isStoring () const inline
Definition at line 711 of file XSerializeEngine.hpp.
References fStoreLoad, and mode_Store.
Referenced by ensureStoring(), and getBufCurAccumulated().
isStoring() [2/3]
bool XSerializeEngine::isStoring () const inline
isStoring() [3/3]
bool XSerializeEngine::isStoring () const inline
lookupLoadPool() [1/3]
XSerializable* XSerializeEngine::lookupLoadPool (XSerializedObjectId_t objectTag) const private
lookupLoadPool() [2/3]
XSerializable* XSerializeEngine::lookupLoadPool (XSerializedObjectId_t objectTag) const private
lookupLoadPool() [3/3]
XSerializable* XSerializeEngine::lookupLoadPool (XSerializedObjectId_t objectTag) const private
lookupStorePool() [1/3]
XSerializedObjectId_t XSerializeEngine::lookupStorePool (void *const objectPtr) const private
lookupStorePool() [2/3]
XSerializedObjectId_t XSerializeEngine::lookupStorePool (void *const objectPtr) const private
lookupStorePool() [3/3]
XSerializedObjectId_t XSerializeEngine::lookupStorePool (void *const objectPtr) const private
needToLoadObject() [1/3]
bool XSerializeEngine::needToLoadObject (void ** templateObjectToRead)
needToLoadObject() [2/3]
bool XSerializeEngine::needToLoadObject (void ** templateObjectToRead)
needToLoadObject() [3/3]
bool XSerializeEngine::needToLoadObject (void ** templateObjectToRead)
needToStoreObject() [1/3]
bool XSerializeEngine::needToStoreObject (void *const templateObjectToWrite)
needToStoreObject() [2/3]
bool XSerializeEngine::needToStoreObject (void *const templateObjectToWrite)
needToStoreObject() [3/3]
bool XSerializeEngine::needToStoreObject (void *const templateObjectToWrite)
operator<<() [1/33]
XSerializeEngine& XSerializeEngine::operator<< (bool)
operator<<() [2/33]
XSerializeEngine& XSerializeEngine::operator<< (bool)
operator<<() [3/33]
XSerializeEngine& XSerializeEngine::operator<< (bool)
operator<<() [4/33]
XSerializeEngine& XSerializeEngine::operator<< (char)
operator<<() [5/33]
XSerializeEngine& XSerializeEngine::operator<< (char)
operator<<() [6/33]
XSerializeEngine& XSerializeEngine::operator<< (char)
operator<<() [7/33]
XSerializeEngine& XSerializeEngine::operator<< (double)
operator<<() [8/33]
XSerializeEngine& XSerializeEngine::operator<< (double)
operator<<() [9/33]
XSerializeEngine& XSerializeEngine::operator<< (double)
operator<<() [10/33]
XSerializeEngine& XSerializeEngine::operator<< (float)
operator<<() [11/33]
XSerializeEngine& XSerializeEngine::operator<< (float)
operator<<() [12/33]
XSerializeEngine& XSerializeEngine::operator<< (float)
operator<<() [13/33]
XSerializeEngine& XSerializeEngine::operator<< (int)
operator<<() [14/33]
XSerializeEngine& XSerializeEngine::operator<< (int)
operator<<() [15/33]
XSerializeEngine& XSerializeEngine::operator<< (int)
operator<<() [16/33]
XSerializeEngine& XSerializeEngine::operator<< (long)
operator<<() [17/33]
XSerializeEngine& XSerializeEngine::operator<< (long)
operator<<() [18/33]
XSerializeEngine& XSerializeEngine::operator<< (long)
operator<<() [19/33]
XSerializeEngine& XSerializeEngine::operator<< (short)
operator<<() [20/33]
XSerializeEngine& XSerializeEngine::operator<< (short)
operator<<() [21/33]
XSerializeEngine& XSerializeEngine::operator<< (short)
operator<<() [22/33]
XSerializeEngine& XSerializeEngine::operator<< (unsigned int)
operator<<() [23/33]
XSerializeEngine& XSerializeEngine::operator<< (unsigned int)
operator<<() [24/33]
XSerializeEngine& XSerializeEngine::operator<< (unsigned int)
operator<<() [25/33]
XSerializeEngine& XSerializeEngine::operator<< (unsigned long)
operator<<() [26/33]
XSerializeEngine& XSerializeEngine::operator<< (unsigned long)
operator<<() [27/33]
XSerializeEngine& XSerializeEngine::operator<< (unsigned long)
operator<<() [28/33]
XSerializeEngine& XSerializeEngine::operator<< (XMLByte)
operator<<() [29/33]
XSerializeEngine& XSerializeEngine::operator<< (XMLByte)
operator<<() [30/33]
XSerializeEngine& XSerializeEngine::operator<< (XMLByte)
operator<<() [31/33]
XSerializeEngine& XSerializeEngine::operator<< (XMLCh)
operator<<() [32/33]
XSerializeEngine& XSerializeEngine::operator<< (XMLCh)
operator<<() [33/33]
XSerializeEngine& XSerializeEngine::operator<< (XMLCh)
operator=() [1/3]
XSerializeEngine& XSerializeEngine::operator= (const XSerializeEngine &) private
operator=() [2/3]
XSerializeEngine& XSerializeEngine::operator= (const XSerializeEngine &) private
operator=() [3/3]
XSerializeEngine& XSerializeEngine::operator= (const XSerializeEngine &) private
operator>>() [1/33]
XSerializeEngine& XSerializeEngine::operator>> (bool &)
operator>>() [2/33]
XSerializeEngine& XSerializeEngine::operator>> (bool &)
operator>>() [3/33]
XSerializeEngine& XSerializeEngine::operator>> (bool &)
operator>>() [4/33]
XSerializeEngine& XSerializeEngine::operator>> (char &)
operator>>() [5/33]
XSerializeEngine& XSerializeEngine::operator>> (char &)
operator>>() [6/33]
XSerializeEngine& XSerializeEngine::operator>> (char &)
operator>>() [7/33]
XSerializeEngine& XSerializeEngine::operator>> (double &)
operator>>() [8/33]
XSerializeEngine& XSerializeEngine::operator>> (double &)
operator>>() [9/33]
XSerializeEngine& XSerializeEngine::operator>> (double &)
operator>>() [10/33]
XSerializeEngine& XSerializeEngine::operator>> (float &)
operator>>() [11/33]
XSerializeEngine& XSerializeEngine::operator>> (float &)
operator>>() [12/33]
XSerializeEngine& XSerializeEngine::operator>> (float &)
operator>>() [13/33]
XSerializeEngine& XSerializeEngine::operator>> (int &)
operator>>() [14/33]
XSerializeEngine& XSerializeEngine::operator>> (int &)
operator>>() [15/33]
XSerializeEngine& XSerializeEngine::operator>> (int &)
operator>>() [16/33]
XSerializeEngine& XSerializeEngine::operator>> (long &)
operator>>() [17/33]
XSerializeEngine& XSerializeEngine::operator>> (long &)
operator>>() [18/33]
XSerializeEngine& XSerializeEngine::operator>> (long &)
operator>>() [19/33]
XSerializeEngine& XSerializeEngine::operator>> (short &)
operator>>() [20/33]
XSerializeEngine& XSerializeEngine::operator>> (short &)
operator>>() [21/33]
XSerializeEngine& XSerializeEngine::operator>> (short &)
operator>>() [22/33]
XSerializeEngine& XSerializeEngine::operator>> (unsigned int &)
operator>>() [23/33]
XSerializeEngine& XSerializeEngine::operator>> (unsigned int &)
operator>>() [24/33]
XSerializeEngine& XSerializeEngine::operator>> (unsigned int &)
operator>>() [25/33]
XSerializeEngine& XSerializeEngine::operator>> (unsigned long &)
operator>>() [26/33]
XSerializeEngine& XSerializeEngine::operator>> (unsigned long &)
operator>>() [27/33]
XSerializeEngine& XSerializeEngine::operator>> (unsigned long &)
operator>>() [28/33]
XSerializeEngine& XSerializeEngine::operator>> (XMLByte &)
operator>>() [29/33]
XSerializeEngine& XSerializeEngine::operator>> (XMLByte &)
operator>>() [30/33]
XSerializeEngine& XSerializeEngine::operator>> (XMLByte &)
operator>>() [31/33]
XSerializeEngine& XSerializeEngine::operator>> (XMLCh &)
operator>>() [32/33]
XSerializeEngine& XSerializeEngine::operator>> (XMLCh &)
operator>>() [33/33]
XSerializeEngine& XSerializeEngine::operator>> (XMLCh &)
pumpCount() [1/3]
void XSerializeEngine::pumpCount () private
pumpCount() [2/3]
void XSerializeEngine::pumpCount () private
pumpCount() [3/3]
void XSerializeEngine::pumpCount () private
read() [1/12]
void XSerializeEngine::read (XMLByte *const toRead, XMLSize_t readLen)
read() [2/12]
void XSerializeEngine::read (XMLByte *const toRead, XMLSize_t readLen)
read() [3/12]
void XSerializeEngine::read (XMLByte *const toRead, XMLSize_t readLen)
read() [4/12]
void XSerializeEngine::read (XMLCh *const toRead, XMLSize_t readLen)
read() [5/12]
void XSerializeEngine::read (XMLCh *const toRead, XMLSize_t readLen)
read() [6/12]
void XSerializeEngine::read (XMLCh *const toRead, XMLSize_t readLen)
read() [7/12]
XSerializable* XSerializeEngine::read (XProtoType *const protoType)
read() [8/12]
XSerializable* XSerializeEngine::read (XProtoType *const protoType)
read() [9/12]
XSerializable* XSerializeEngine::read (XProtoType *const protoType)
read() [10/12]
bool XSerializeEngine::read (XProtoType *const protoType, XSerializedObjectId_t * objTag)
read() [11/12]
bool XSerializeEngine::read (XProtoType *const protoType, XSerializedObjectId_t * objTag)
read() [12/12]
bool XSerializeEngine::read (XProtoType *const protoType, XSerializedObjectId_t * objTag)
readInt64() [1/3]
void XSerializeEngine::readInt64 (XMLInt64 &)
readInt64() [2/3]
void XSerializeEngine::readInt64 (XMLInt64 &)
readInt64() [3/3]
void XSerializeEngine::readInt64 (XMLInt64 &)
readSize() [1/3]
void XSerializeEngine::readSize (XMLSize_t &)
readSize() [2/3]
void XSerializeEngine::readSize (XMLSize_t &)
readSize() [3/3]
void XSerializeEngine::readSize (XMLSize_t &)
readString() [1/18]
void XSerializeEngine::readString (XMLByte *& toRead) inline
Definition at line 771 of file XSerializeEngine.hpp.
References readString().
readString() [2/18]
void XSerializeEngine::readString (XMLByte *& toRead) inline
readString() [3/18]
void XSerializeEngine::readString (XMLByte *& toRead) inline
readString() [4/18]
void XSerializeEngine::readString (XMLByte *& toRead, XMLSize_t & bufferLen) inline
Definition at line 764 of file XSerializeEngine.hpp.
References readString().
readString() [5/18]
void XSerializeEngine::readString (XMLByte *& toRead, XMLSize_t & bufferLen) inline
readString() [6/18]
void XSerializeEngine::readString (XMLByte *& toRead, XMLSize_t & bufferLen) inline
readString() [7/18]
void XSerializeEngine::readString (XMLByte *& toRead, XMLSize_t & bufferLen, XMLSize_t & dataLen, bool toReadBufLen = false)
readString() [8/18]
void XSerializeEngine::readString (XMLByte *& toRead, XMLSize_t & bufferLen, XMLSize_t & dataLen, bool toReadBufLen = false)
readString() [9/18]
void XSerializeEngine::readString (XMLByte *& toRead, XMLSize_t & bufferLen, XMLSize_t & dataLen, bool toReadBufLen = false)
readString() [10/18]
void XSerializeEngine::readString (XMLCh *& toRead) inline
Definition at line 757 of file XSerializeEngine.hpp.
References readString().
readString() [11/18]
void XSerializeEngine::readString (XMLCh *& toRead) inline
readString() [12/18]
void XSerializeEngine::readString (XMLCh *& toRead) inline
readString() [13/18]
void XSerializeEngine::readString (XMLCh *& toRead, XMLSize_t & bufferLen) inline
Definition at line 750 of file XSerializeEngine.hpp.
References readString().
readString() [14/18]
void XSerializeEngine::readString (XMLCh *& toRead, XMLSize_t & bufferLen) inline
readString() [15/18]
void XSerializeEngine::readString (XMLCh *& toRead, XMLSize_t & bufferLen) inline
readString() [16/18]
void XSerializeEngine::readString (XMLCh *& toRead, XMLSize_t & bufferLen, XMLSize_t & dataLen, bool toReadBufLen = false)
Referenced by readString().
readString() [17/18]
void XSerializeEngine::readString (XMLCh *& toRead, XMLSize_t & bufferLen, XMLSize_t & dataLen, bool toReadBufLen = false)
readString() [18/18]
void XSerializeEngine::readString (XMLCh *& toRead, XMLSize_t & bufferLen, XMLSize_t & dataLen, bool toReadBufLen = false)
readUInt64() [1/3]
void XSerializeEngine::readUInt64 (XMLUInt64 &)
readUInt64() [2/3]
void XSerializeEngine::readUInt64 (XMLUInt64 &)
readUInt64() [3/3]
void XSerializeEngine::readUInt64 (XMLUInt64 &)
registerObject() [1/3]
void XSerializeEngine::registerObject (void *const templateObjectToRegister)
registerObject() [2/3]
void XSerializeEngine::registerObject (void *const templateObjectToRegister)
registerObject() [3/3]
void XSerializeEngine::registerObject (void *const templateObjectToRegister)
resetBuffer() [1/3]
void XSerializeEngine::resetBuffer () inline private
resetBuffer() [2/3]
void XSerializeEngine::resetBuffer () inline private
resetBuffer() [3/3]
void XSerializeEngine::resetBuffer () inline private
trace() [1/3]
void XSerializeEngine::trace (char *) const
trace() [2/3]
void XSerializeEngine::trace (char *) const
trace() [3/3]
void XSerializeEngine::trace (char *) const
write() [1/12]
void XSerializeEngine::write (const XMLByte *const toWrite, XMLSize_t writeLen)
write() [2/12]
void XSerializeEngine::write (const XMLByte *const toWrite, XMLSize_t writeLen)
write() [3/12]
void XSerializeEngine::write (const XMLByte *const toWrite, XMLSize_t writeLen)
write() [4/12]
void XSerializeEngine::write (const XMLCh *const toWrite, XMLSize_t writeLen)
write() [5/12]
void XSerializeEngine::write (const XMLCh *const toWrite, XMLSize_t writeLen)
write() [6/12]
void XSerializeEngine::write (const XMLCh *const toWrite, XMLSize_t writeLen)
write() [7/12]
void XSerializeEngine::write (XProtoType *const protoType)
write() [8/12]
void XSerializeEngine::write (XProtoType *const protoType)
write() [9/12]
void XSerializeEngine::write (XProtoType *const protoType)
write() [10/12]
void XSerializeEngine::write (XSerializable *const objectToWrite)
Referenced by operator<<().
write() [11/12]
void XSerializeEngine::write (XSerializable *const objectToWrite)
write() [12/12]
void XSerializeEngine::write (XSerializable *const objectToWrite)
writeInt64() [1/3]
void XSerializeEngine::writeInt64 (XMLInt64)
writeInt64() [2/3]
void XSerializeEngine::writeInt64 (XMLInt64)
writeInt64() [3/3]
void XSerializeEngine::writeInt64 (XMLInt64)
writeSize() [1/3]
void XSerializeEngine::writeSize (XMLSize_t)
writeSize() [2/3]
void XSerializeEngine::writeSize (XMLSize_t)
writeSize() [3/3]
void XSerializeEngine::writeSize (XMLSize_t)
writeString() [1/6]
void XSerializeEngine::writeString (const XMLByte *const toWrite, const XMLSize_t bufferLen = 0, bool toWriteBufLen = false)
writeString() [2/6]
void XSerializeEngine::writeString (const XMLByte *const toWrite, const XMLSize_t bufferLen = 0, bool toWriteBufLen = false)
writeString() [3/6]
void XSerializeEngine::writeString (const XMLByte *const toWrite, const XMLSize_t bufferLen = 0, bool toWriteBufLen = false)
writeString() [4/6]
void XSerializeEngine::writeString (const XMLCh *const toWrite, const XMLSize_t bufferLen = 0, bool toWriteBufLen = false)
writeString() [5/6]
void XSerializeEngine::writeString (const XMLCh *const toWrite, const XMLSize_t bufferLen = 0, bool toWriteBufLen = false)
writeString() [6/6]
void XSerializeEngine::writeString (const XMLCh *const toWrite, const XMLSize_t bufferLen = 0, bool toWriteBufLen = false)
writeUInt64() [1/3]
void XSerializeEngine::writeUInt64 (XMLUInt64)
writeUInt64() [2/3]
void XSerializeEngine::writeUInt64 (XMLUInt64)
writeUInt64() [3/3]
void XSerializeEngine::writeUInt64 (XMLUInt64)
Friends And Related Function Documentation
operator<< [1/3]
XSerializeEngine& operator<< (XSerializeEngine & serEng, XSerializable * const serObj) friend
Definition at line 721 of file XSerializeEngine.hpp.
operator<< [2/3]
XSerializeEngine& operator<< (XSerializeEngine & serEng, XSerializable * const serObj) friend
Definition at line 721 of file XSerializeEngine.hpp.
operator<< [3/3]
XSerializeEngine& operator<< (XSerializeEngine & serEng, XSerializable * const serObj) friend
Definition at line 721 of file XSerializeEngine.hpp.
XMLGrammarPoolImpl
XMLGrammarPoolImpl friend
Definition at line 708 of file XSerializeEngine.hpp.
XTemplateSerializer
XTemplateSerializer friend
Definition at line 614 of file XSerializeEngine.hpp.
Member Data Documentation
fBufCount
unsigned long XSerializeEngine::fBufCount private
Definition at line 671 of file XSerializeEngine.hpp.
Referenced by getBufCount(), and getBufCurAccumulated().
fBufCur
XMLByte * XSerializeEngine::fBufCur private
Definition at line 677 of file XSerializeEngine.hpp.
Referenced by getBufCur(), and getBufCurAccumulated().
fBufEnd
XMLByte *const XSerializeEngine::fBufEnd private
Definition at line 676 of file XSerializeEngine.hpp.
fBufLoadMax
XMLByte * XSerializeEngine::fBufLoadMax private
Definition at line 678 of file XSerializeEngine.hpp.
fBufSize
const XMLSize_t XSerializeEngine::fBufSize private
Definition at line 674 of file XSerializeEngine.hpp.
Referenced by getBufCurAccumulated(), and getBufSize().
fBufStart
XMLByte *const XSerializeEngine::fBufStart private
Definition at line 675 of file XSerializeEngine.hpp.
Referenced by getBufCur(), and getBufCurAccumulated().
fGrammarPool
XMLGrammarPool *const XSerializeEngine::fGrammarPool private
Definition at line 667 of file XSerializeEngine.hpp.
fInputStream
BinInputStream *const XSerializeEngine::fInputStream private
Definition at line 668 of file XSerializeEngine.hpp.
fLoadPool
ValueVectorOf< void * > * XSerializeEngine::fLoadPool private
Definition at line 700 of file XSerializeEngine.hpp.
fObjectCount
XSerializedObjectId_t XSerializeEngine::fObjectCount private
Definition at line 705 of file XSerializeEngine.hpp.
fOutputStream
BinOutputStream *const XSerializeEngine::fOutputStream private
Definition at line 669 of file XSerializeEngine.hpp.
fStoreLoad
const short XSerializeEngine::fStoreLoad private
Definition at line 664 of file XSerializeEngine.hpp.
Referenced by isLoading(), and isStoring().
fStorePool
RefHashTableOf< XSerializedObjectId, PtrHasher > * XSerializeEngine::fStorePool private
Definition at line 691 of file XSerializeEngine.hpp.
fStorerLevel
unsigned int XSerializeEngine::fStorerLevel private
Definition at line 665 of file XSerializeEngine.hpp.
Referenced by getStorerLevel().
toReadBufferLen
static const bool XSerializeEngine::toReadBufferLen static
Definition at line 52 of file XSerializeEngine.hpp.
toWriteBufferLen
static const bool XSerializeEngine::toWriteBufferLen static
Definition at line 260 of file XSerializeEngine.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/internal/XSerializeEngine.hpp