Seamly2D: anonymous_namespace{vabstracttool.cpp} Namespace Reference
anonymous_namespace{vabstracttool.cpp} Namespace Reference
Functions
quint32 CreateNodeSpline (VContainer *data, quint32 id)
quint32 CreateNodeSplinePath (VContainer *data, quint32 id)
Function Documentation
CreateNodeSpline()
quint32 anonymous_namespace{vabstracttool.cpp}::CreateNodeSpline (VContainer * data, quint32 id)
Definition at line 113 of file vabstracttool.cpp.
References VContainer::GetGObject(), and Spline.
Referenced by VAbstractTool::PrepareNode().
CreateNodeSplinePath()
quint32 anonymous_namespace{vabstracttool.cpp}::CreateNodeSplinePath (VContainer * data, quint32 id)
Definition at line 126 of file vabstracttool.cpp.
References VContainer::GetGObject(), and SplinePath.
Referenced by VAbstractTool::PrepareNode().