Seamly2D: XMLAbstractDoubleFloat Class Reference
XMLAbstractDoubleFloat Class Reference abstract
#include <XMLAbstractDoubleFloat.hpp>
Public Types
enum LiteralType {
NegINF , PosINF , NaN , SpecialTypeNum ,
Normal , NegINF , PosINF , NaN ,
SpecialTypeNum , Normal , NegINF , PosINF ,
NaN , SpecialTypeNum , Normal
}
enum LiteralType {
NegINF , PosINF , NaN , SpecialTypeNum ,
Normal , NegINF , PosINF , NaN ,
SpecialTypeNum , Normal , NegINF , PosINF ,
NaN , SpecialTypeNum , Normal
}
enum LiteralType {
NegINF , PosINF , NaN , SpecialTypeNum ,
Normal , NegINF , PosINF , NaN ,
SpecialTypeNum , Normal , NegINF , PosINF ,
NaN , SpecialTypeNum , Normal
}
Public Types inherited from XMLNumber
enum { LESS_THAN = -1 , EQUAL = 0 , GREATER_THAN = 1 , INDETERMINATE = 2 }
enum NumberType {
Float , Double , BigDecimal , DateTime ,
UnKnown , Float , Double , BigDecimal ,
DateTime , UnKnown , Float , Double ,
BigDecimal , DateTime , UnKnown
}
enum { LESS_THAN = -1 , EQUAL = 0 , GREATER_THAN = 1 , INDETERMINATE = 2 }
enum NumberType {
Float , Double , BigDecimal , DateTime ,
UnKnown , Float , Double , BigDecimal ,
DateTime , UnKnown , Float , Double ,
BigDecimal , DateTime , UnKnown
}
enum { LESS_THAN = -1 , EQUAL = 0 , GREATER_THAN = 1 , INDETERMINATE = 2 }
enum NumberType {
Float , Double , BigDecimal , DateTime ,
UnKnown , Float , Double , BigDecimal ,
DateTime , UnKnown , Float , Double ,
BigDecimal , DateTime , UnKnown
}
Public Member Functions
virtual ~XMLAbstractDoubleFloat ()
virtual XMLCh * getRawData () const
virtual const XMLCh * getFormattedString () const
virtual int getSign () const
MemoryManager * getMemoryManager () const
bool isDataConverted () const
bool isDataOverflowed () const
double getValue () const
LiteralType getType () const
virtual ~XMLAbstractDoubleFloat ()
virtual XMLCh * getRawData () const
virtual const XMLCh * getFormattedString () const
virtual int getSign () const
MemoryManager * getMemoryManager () const
bool isDataConverted () const
bool isDataOverflowed () const
double getValue () const
LiteralType getType () const
virtual ~XMLAbstractDoubleFloat ()
virtual XMLCh * getRawData () const
virtual const XMLCh * getFormattedString () const
virtual int getSign () const
MemoryManager * getMemoryManager () const
bool isDataConverted () const
bool isDataOverflowed () const
double getValue () const
LiteralType getType () const
Public Member Functions inherited from XMLNumber
virtual ~XMLNumber ()
virtual ~XMLNumber ()
virtual ~XMLNumber ()
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Static Public Member Functions
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
static void normalizeDecimalPoint (char *const toNormal)
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
static void normalizeDecimalPoint (char *const toNormal)
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
static void normalizeDecimalPoint (char *const toNormal)
Static Public Member Functions inherited from XMLNumber
static XMLNumber * loadNumber (XMLNumber::NumberType numType, XSerializeEngine &serEng)
static XMLNumber * loadNumber (XMLNumber::NumberType numType, XSerializeEngine &serEng)
static XMLNumber * loadNumber (XMLNumber::NumberType numType, XSerializeEngine &serEng)
Protected Member Functions
XMLAbstractDoubleFloat (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void init (const XMLCh *const strValue)
virtual void checkBoundary (char *const strValue)=0
void convert (char *const strValue)
XMLAbstractDoubleFloat (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void init (const XMLCh *const strValue)
virtual void checkBoundary (char *const strValue)=0
void convert (char *const strValue)
XMLAbstractDoubleFloat (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void init (const XMLCh *const strValue)
virtual void checkBoundary (char *const strValue)=0
void convert (char *const strValue)
Protected Member Functions inherited from XMLNumber
XMLNumber ()
XMLNumber (const XMLNumber &)
XMLNumber ()
XMLNumber (const XMLNumber &)
XMLNumber ()
XMLNumber (const XMLNumber &)
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Static Protected Member Functions
static int compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager)
static int compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager)
static int compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager)
Protected Attributes
double fValue
LiteralType fType
bool fDataConverted
bool fDataOverflowed
Private Member Functions
XMLAbstractDoubleFloat (const XMLAbstractDoubleFloat &toCopy)
XMLAbstractDoubleFloat & operator= (const XMLAbstractDoubleFloat &toAssign)
void normalizeZero (XMLCh *const)
bool isSpecialValue () const
void formatString ()
XMLAbstractDoubleFloat (const XMLAbstractDoubleFloat &toCopy)
XMLAbstractDoubleFloat & operator= (const XMLAbstractDoubleFloat &toAssign)
void normalizeZero (XMLCh *const)
bool isSpecialValue () const
void formatString ()
XMLAbstractDoubleFloat (const XMLAbstractDoubleFloat &toCopy)
XMLAbstractDoubleFloat & operator= (const XMLAbstractDoubleFloat &toAssign)
void normalizeZero (XMLCh *const)
bool isSpecialValue () const
void formatString ()
Static Private Member Functions
static int compareSpecial (const XMLAbstractDoubleFloat *const specialValue, MemoryManager *const manager)
static int compareSpecial (const XMLAbstractDoubleFloat *const specialValue, MemoryManager *const manager)
static int compareSpecial (const XMLAbstractDoubleFloat *const specialValue, MemoryManager *const manager)
Private Attributes
int fSign
XMLCh * fRawData
XMLCh * fFormattedString
MemoryManager * fMemoryManager
Detailed Description
Definition at line 61 of file XMLAbstractDoubleFloat.hpp.
Member Enumeration Documentation
LiteralType [1/3]
enum XMLAbstractDoubleFloat::LiteralType
Enumerator
NegINF
PosINF
NaN
SpecialTypeNum
Normal
NegINF
PosINF
NaN
SpecialTypeNum
Normal
NegINF
PosINF
NaN
SpecialTypeNum
Normal
Definition at line 65 of file XMLAbstractDoubleFloat.hpp.
LiteralType [2/3]
enum XMLAbstractDoubleFloat::LiteralType
Enumerator
NegINF
PosINF
NaN
SpecialTypeNum
Normal
NegINF
PosINF
NaN
SpecialTypeNum
Normal
NegINF
PosINF
NaN
SpecialTypeNum
Normal
Definition at line 65 of file XMLAbstractDoubleFloat.hpp.
LiteralType [3/3]
enum XMLAbstractDoubleFloat::LiteralType
Enumerator
NegINF
PosINF
NaN
SpecialTypeNum
Normal
NegINF
PosINF
NaN
SpecialTypeNum
Normal
NegINF
PosINF
NaN
SpecialTypeNum
Normal
Definition at line 65 of file XMLAbstractDoubleFloat.hpp.
Constructor & Destructor Documentation
~XMLAbstractDoubleFloat() [1/3]
virtual XMLAbstractDoubleFloat::~XMLAbstractDoubleFloat () virtual
XMLAbstractDoubleFloat() [1/6]
XMLAbstractDoubleFloat::XMLAbstractDoubleFloat (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAbstractDoubleFloat() [2/6]
XMLAbstractDoubleFloat::XMLAbstractDoubleFloat (const XMLAbstractDoubleFloat & toCopy) private
~XMLAbstractDoubleFloat() [2/3]
virtual XMLAbstractDoubleFloat::~XMLAbstractDoubleFloat () virtual
XMLAbstractDoubleFloat() [3/6]
XMLAbstractDoubleFloat::XMLAbstractDoubleFloat (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAbstractDoubleFloat() [4/6]
XMLAbstractDoubleFloat::XMLAbstractDoubleFloat (const XMLAbstractDoubleFloat & toCopy) private
~XMLAbstractDoubleFloat() [3/3]
virtual XMLAbstractDoubleFloat::~XMLAbstractDoubleFloat () virtual
XMLAbstractDoubleFloat() [5/6]
XMLAbstractDoubleFloat::XMLAbstractDoubleFloat (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
XMLAbstractDoubleFloat() [6/6]
XMLAbstractDoubleFloat::XMLAbstractDoubleFloat (const XMLAbstractDoubleFloat & toCopy) private
Member Function Documentation
checkBoundary() [1/3]
virtual void XMLAbstractDoubleFloat::checkBoundary (char *const strValue) protected pure virtual
Implemented in XMLFloat, XMLDouble, XMLFloat, XMLDouble, XMLFloat, and XMLDouble.
checkBoundary() [2/3]
virtual void XMLAbstractDoubleFloat::checkBoundary (char *const strValue) protected pure virtual
Implemented in XMLFloat, XMLDouble, XMLFloat, XMLDouble, XMLFloat, and XMLDouble.
checkBoundary() [3/3]
virtual void XMLAbstractDoubleFloat::checkBoundary (char *const strValue) protected pure virtual
Implemented in XMLFloat, XMLDouble, XMLFloat, XMLDouble, XMLFloat, and XMLDouble.
compareSpecial() [1/3]
static int XMLAbstractDoubleFloat::compareSpecial (const XMLAbstractDoubleFloat *const specialValue, MemoryManager *const manager) static private
compareSpecial() [2/3]
static int XMLAbstractDoubleFloat::compareSpecial (const XMLAbstractDoubleFloat *const specialValue, MemoryManager *const manager) static private
compareSpecial() [3/3]
static int XMLAbstractDoubleFloat::compareSpecial (const XMLAbstractDoubleFloat *const specialValue, MemoryManager *const manager) static private
compareValues() [1/3]
static int XMLAbstractDoubleFloat::compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager) static protected
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLAbstractDoubleFloat object that contains the same int value as this object.
Parameters
lValue the object to compare with.
rValue the object to compare against.
manager The MemoryManager to use to allocate objects
Returns
true if the objects are the same; false otherwise.
Referenced by XMLDouble::compareValues(), XMLFloat::compareValues(), XMLDouble::operator=(), and XMLFloat::operator=().
compareValues() [2/3]
static int XMLAbstractDoubleFloat::compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager) static protected
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLAbstractDoubleFloat object that contains the same int value as this object.
Parameters
lValue the object to compare with.
rValue the object to compare against.
manager The MemoryManager to use to allocate objects
Returns
true if the objects are the same; false otherwise.
compareValues() [3/3]
static int XMLAbstractDoubleFloat::compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager) static protected
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLAbstractDoubleFloat object that contains the same int value as this object.
Parameters
lValue the object to compare with.
rValue the object to compare against.
manager The MemoryManager to use to allocate objects
Returns
true if the objects are the same; false otherwise.
convert() [1/3]
void XMLAbstractDoubleFloat::convert (char *const strValue) protected
convert() [2/3]
void XMLAbstractDoubleFloat::convert (char *const strValue) protected
convert() [3/3]
void XMLAbstractDoubleFloat::convert (char *const strValue) protected
formatString() [1/3]
void XMLAbstractDoubleFloat::formatString () private
formatString() [2/3]
void XMLAbstractDoubleFloat::formatString () private
formatString() [3/3]
void XMLAbstractDoubleFloat::formatString () private
getCanonicalRepresentation() [1/3]
static XMLCh* XMLAbstractDoubleFloat::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager) static
getCanonicalRepresentation() [2/3]
static XMLCh* XMLAbstractDoubleFloat::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager) static
getCanonicalRepresentation() [3/3]
static XMLCh* XMLAbstractDoubleFloat::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager) static
getFormattedString() [1/3]
virtual const XMLCh* XMLAbstractDoubleFloat::getFormattedString () const virtual
Return the original and converted value of the original data. (applicable to double/float)
The internal buffer is returned directly, user is not required to delete the returned buffer
Implements XMLNumber.
getFormattedString() [2/3]
virtual const XMLCh* XMLAbstractDoubleFloat::getFormattedString () const virtual
Return the original and converted value of the original data. (applicable to double/float)
The internal buffer is returned directly, user is not required to delete the returned buffer
Implements XMLNumber.
getFormattedString() [3/3]
virtual const XMLCh* XMLAbstractDoubleFloat::getFormattedString () const virtual
Return the original and converted value of the original data. (applicable to double/float)
The internal buffer is returned directly, user is not required to delete the returned buffer
Implements XMLNumber.
getMemoryManager() [1/3]
MemoryManager * XMLAbstractDoubleFloat::getMemoryManager () const inline
Definition at line 194 of file XMLAbstractDoubleFloat.hpp.
References fMemoryManager.
Referenced by XMLDouble::compareValues(), XMLFloat::compareValues(), XMLDouble::operator=(), and XMLFloat::operator=().
getMemoryManager() [2/3]
MemoryManager* XMLAbstractDoubleFloat::getMemoryManager () const
getMemoryManager() [3/3]
MemoryManager* XMLAbstractDoubleFloat::getMemoryManager () const
getRawData() [1/3]
virtual XMLCh* XMLAbstractDoubleFloat::getRawData () const virtual
Return string representation of the decimal value. A decimal point will be included as necessary. Similar to toString above, but the internal buffer is returned directly, user is not required to delete the returned buffer
Implements XMLNumber.
getRawData() [2/3]
virtual XMLCh* XMLAbstractDoubleFloat::getRawData () const virtual
Return string representation of the decimal value. A decimal point will be included as necessary. Similar to toString above, but the internal buffer is returned directly, user is not required to delete the returned buffer
Implements XMLNumber.
getRawData() [3/3]
virtual XMLCh* XMLAbstractDoubleFloat::getRawData () const virtual
Return string representation of the decimal value. A decimal point will be included as necessary. Similar to toString above, but the internal buffer is returned directly, user is not required to delete the returned buffer
Implements XMLNumber.
getSign() [1/3]
virtual int XMLAbstractDoubleFloat::getSign () const virtual
Returns the sign of this number
-1 negative 0 zero 1 positive
Implements XMLNumber.
getSign() [2/3]
virtual int XMLAbstractDoubleFloat::getSign () const virtual
Returns the sign of this number
-1 negative 0 zero 1 positive
Implements XMLNumber.
getSign() [3/3]
virtual int XMLAbstractDoubleFloat::getSign () const virtual
Returns the sign of this number
-1 negative 0 zero 1 positive
Implements XMLNumber.
getType() [1/3]
XMLAbstractDoubleFloat::LiteralType XMLAbstractDoubleFloat::getType () const inline
Definition at line 214 of file XMLAbstractDoubleFloat.hpp.
References fType.
getType() [2/3]
LiteralType XMLAbstractDoubleFloat::getType () const inline
getType() [3/3]
LiteralType XMLAbstractDoubleFloat::getType () const inline
getValue() [1/3]
double XMLAbstractDoubleFloat::getValue () const inline
Definition at line 209 of file XMLAbstractDoubleFloat.hpp.
References fValue.
getValue() [2/3]
double XMLAbstractDoubleFloat::getValue () const inline
getValue() [3/3]
double XMLAbstractDoubleFloat::getValue () const inline
init() [1/3]
void XMLAbstractDoubleFloat::init (const XMLCh *const strValue) protected
init() [2/3]
void XMLAbstractDoubleFloat::init (const XMLCh *const strValue) protected
init() [3/3]
void XMLAbstractDoubleFloat::init (const XMLCh *const strValue) protected
isDataConverted() [1/3]
bool XMLAbstractDoubleFloat::isDataConverted () const inline
Definition at line 199 of file XMLAbstractDoubleFloat.hpp.
References fDataConverted.
isDataConverted() [2/3]
bool XMLAbstractDoubleFloat::isDataConverted () const inline
isDataConverted() [3/3]
bool XMLAbstractDoubleFloat::isDataConverted () const inline
isDataOverflowed() [1/3]
bool XMLAbstractDoubleFloat::isDataOverflowed () const inline
Definition at line 204 of file XMLAbstractDoubleFloat.hpp.
References fDataOverflowed.
isDataOverflowed() [2/3]
bool XMLAbstractDoubleFloat::isDataOverflowed () const inline
isDataOverflowed() [3/3]
bool XMLAbstractDoubleFloat::isDataOverflowed () const inline
isSpecialValue() [1/3]
bool XMLAbstractDoubleFloat::isSpecialValue () const inline private
Definition at line 189 of file XMLAbstractDoubleFloat.hpp.
References fType, and SpecialTypeNum.
isSpecialValue() [2/3]
bool XMLAbstractDoubleFloat::isSpecialValue () const inline private
isSpecialValue() [3/3]
bool XMLAbstractDoubleFloat::isSpecialValue () const inline private
normalizeDecimalPoint() [1/3]
static void XMLAbstractDoubleFloat::normalizeDecimalPoint (char *const toNormal) static
normalizeDecimalPoint() [2/3]
static void XMLAbstractDoubleFloat::normalizeDecimalPoint (char *const toNormal) static
normalizeDecimalPoint() [3/3]
static void XMLAbstractDoubleFloat::normalizeDecimalPoint (char *const toNormal) static
normalizeZero() [1/3]
void XMLAbstractDoubleFloat::normalizeZero (XMLCh * const) private
normalizeZero() [2/3]
void XMLAbstractDoubleFloat::normalizeZero (XMLCh * const) private
normalizeZero() [3/3]
void XMLAbstractDoubleFloat::normalizeZero (XMLCh * const) private
operator=() [1/3]
XMLAbstractDoubleFloat& XMLAbstractDoubleFloat::operator= (const XMLAbstractDoubleFloat & toAssign) private
operator=() [2/3]
XMLAbstractDoubleFloat& XMLAbstractDoubleFloat::operator= (const XMLAbstractDoubleFloat & toAssign) private
operator=() [3/3]
XMLAbstractDoubleFloat& XMLAbstractDoubleFloat::operator= (const XMLAbstractDoubleFloat & toAssign) private
Member Data Documentation
fDataConverted
bool XMLAbstractDoubleFloat::fDataConverted protected
Definition at line 169 of file XMLAbstractDoubleFloat.hpp.
Referenced by isDataConverted().
fDataOverflowed
bool XMLAbstractDoubleFloat::fDataOverflowed protected
Definition at line 170 of file XMLAbstractDoubleFloat.hpp.
Referenced by isDataOverflowed().
fFormattedString
XMLCh * XMLAbstractDoubleFloat::fFormattedString private
Definition at line 184 of file XMLAbstractDoubleFloat.hpp.
fMemoryManager
MemoryManager * XMLAbstractDoubleFloat::fMemoryManager private
Definition at line 185 of file XMLAbstractDoubleFloat.hpp.
Referenced by getMemoryManager().
fRawData
XMLCh * XMLAbstractDoubleFloat::fRawData private
Definition at line 174 of file XMLAbstractDoubleFloat.hpp.
fSign
int XMLAbstractDoubleFloat::fSign private
Definition at line 173 of file XMLAbstractDoubleFloat.hpp.
fType
LiteralType XMLAbstractDoubleFloat::fType protected
Definition at line 168 of file XMLAbstractDoubleFloat.hpp.
Referenced by getType(), and isSpecialValue().
fValue
double XMLAbstractDoubleFloat::fValue protected
Definition at line 167 of file XMLAbstractDoubleFloat.hpp.
Referenced by getValue().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/XMLAbstractDoubleFloat.hpp