Seamly2D: VFormulaProperty Class Reference
VFormulaProperty Class Reference
#include <vformulaproperty.h>
Public Slots
virtual void childValueChanged (const QVariant &value, int typeForParent) Q_DECL_OVERRIDE
Public Slots inherited from VPE::VProperty
virtual void childValueChanged (const QVariant &value, int typeForParent)
Public Member Functions
VFormulaProperty (const QString &name)
virtual QVariant data (int column=DPC_Name, int role=Qt::DisplayRole) const Q_DECL_OVERRIDE
Get the data how it should be displayed.
virtual Qt::ItemFlags flags (int column=DPC_Name) const Q_DECL_OVERRIDE
Returns item flags.
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &options, const QAbstractItemDelegate *delegate) Q_DECL_OVERRIDE
Returns an editor widget, or NULL if it doesn't supply one.
virtual bool setEditorData (QWidget *editor) Q_DECL_OVERRIDE
Sets the property's data to the editor (returns false, if the standard delegate should do that)
virtual QVariant getEditorData (const QWidget *editor) const Q_DECL_OVERRIDE
Gets the data from the widget.
virtual QString type () const Q_DECL_OVERRIDE
Returns a string containing the type of the property.
virtual Q_REQUIRED_RESULT VProperty * clone (bool include_children=true, VProperty *container=nullptr) const Q_DECL_OVERRIDE
Clones this property.
virtual void setValue (const QVariant &value) Q_DECL_OVERRIDE
Sets the value of the property.
virtual QVariant getValue () const Q_DECL_OVERRIDE
Returns the value of the property as a QVariant.
VFormula GetFormula () const
Returns the formula.
void SetFormula (const VFormula &formula)
Sets the formula.
Public Member Functions inherited from VPE::VProperty
VProperty (const QString &name, QVariant::Type type=QVariant::String)
Standard constructor, takes a name and a parent property as argument.
virtual ~VProperty () Q_DECL_OVERRIDE
Destructor.
virtual bool setData (const QVariant &data, int role=Qt::EditRole)
This is used by the model to set the data.
virtual bool paint (QPainter *, const QStyleOptionViewItem &, const QModelIndex &, const QAbstractItemDelegate *) const
This is called by the delegate when the property value is being drawn. The standard implementation doesn't do anything. If you reimplement this in a sub property, make sure to return true or the delegate will draw the item.
virtual QString serialize () const
Serializes the value to a string.
virtual void deserialize (const QString &value)
Deserializes the value from a string.
virtual void setName (const QString &name)
Sets the name of the property.
virtual QString getName () const
Gets the name of the property.
virtual void setDescription (const QString &desc)
Sets the name of the property.
virtual QString getDescription () const
Gets the name of the property.
virtual int addChild (VProperty *child)
Adds a child to this property.
virtual QList< VProperty * > & getChildren ()
Returns a reference to the list of children.
virtual const QList< VProperty * > & getChildren () const
Returns a reference to the list of children.
virtual VProperty * getChild (int row) const
Returns the child at a certain row.
virtual int getRowCount () const
Gets the number of children.
virtual VProperty * getParent () const
Gets the parent of this property.
virtual void setParent (VProperty *parent)
Sets the parent of this property.
virtual void removeChild (VProperty *child)
Removes a child from the children list, doesn't delete the child!
virtual int getChildRow (VProperty *child) const
Returns the row the child has.
virtual bool getUpdateParent () const
Returns whether the views have to update the parent of this property if it changes.
virtual bool getUpdateChildren () const
Returns whether the views have to update the children of this property if it changes.
virtual void setUpdateBehaviour (bool update_parent, bool update_children)
Sets whether the views should update Parents or children after this property changes.
virtual void setSettings (const QMap< QString, QVariant > &settings)
Sets the settings by calling the overloaded setSetting(const QString &key, const QVariant &value) for each item in the map.
virtual QMap< QString, QVariant > getSettings () const
Get the settings.
virtual void setSetting (const QString &key, const QVariant &value)
Sets the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QVariant getSetting (const QString &key) const
Get the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QStringList getSettingKeys () const
Returns the list of keys of the property's settings.
virtual Q_REQUIRED_RESULT VProperty * clone (bool include_children=true, VProperty *container=nullptr) const
Clones this property.
Property propertyType () const
void setPropertyType (const Property &type)
virtual void updateParent (const QVariant &value)
Additional Inherited Members
Public Types inherited from VPE::VProperty
enum DPC_DisplayColumn { DPC_Name = 0 , DPC_Data }
Signals inherited from VPE::VProperty
void childChanged (const QVariant &value, int typeForParent)
Protected Member Functions inherited from VPE::VProperty
VProperty (VPropertyPrivate *d)
Protected constructor.
Protected Attributes inherited from VPE::VProperty
VPropertyPrivate * d_ptr
The protected structure holding the member variables (to assure binary compatibility)
Detailed Description
Definition at line 59 of file vformulaproperty.h.
Constructor & Destructor Documentation
VFormulaProperty()
VFormulaProperty::VFormulaProperty (const QString & name) explicit
Definition at line 62 of file vformulaproperty.cpp.
References VPE::VProperty::addChild(), VPE::Complex, VPE::VProperty::d_ptr, qApp, VPE::PlainTextProperty::setOsSeparator(), VPE::VProperty::setUpdateBehaviour(), setValue(), and VPE::VPropertyPrivate::type.
Referenced by clone().
Member Function Documentation
childValueChanged
void VFormulaProperty::childValueChanged (const QVariant & value, int typeForParent) virtual slot
Definition at line 223 of file vformulaproperty.cpp.
References FromUser, GetFormula(), VFormula::SetFormula(), and SetFormula().
clone()
VPE::VProperty * VFormulaProperty::clone (bool include_children = true, VProperty * container = nullptr) const virtual
Clones this property.
Parameters
include_children Indicates whether to also clone the children
container If a property is being passed here, no new VProperty is being created but instead it is tried to fill all the data into container. This can also be used when subclassing this function.
Returns
Returns the newly created property (or container, if it was not NULL)
Definition at line 156 of file vformulaproperty.cpp.
References VPE::VProperty::getName(), VFormulaProperty(), and VPE::VProperty::VProperty().
createEditor()
QWidget * VFormulaProperty::createEditor (QWidget * parent, const QStyleOptionViewItem & options, const QAbstractItemDelegate * delegate) virtual
Returns an editor widget, or NULL if it doesn't supply one.
Parameters
parent The widget to which the editor will be added as a child \options Render options \delegate A pointer to the QAbstractItemDelegate requesting the editor. This can be used to connect signals and slots.
Reimplemented from VPE::VProperty.
Definition at line 103 of file vformulaproperty.cpp.
References VFormula::value.
data()
QVariant VFormulaProperty::data (int column = DPC_Name, int role = Qt::DisplayRole) const virtual
Get the data how it should be displayed.
Reimplemented from VPE::VProperty.
Definition at line 76 of file vformulaproperty.cpp.
References VPE::VProperty::DPC_Data, and getValue().
flags()
Qt::ItemFlags VFormulaProperty::flags (int column = DPC_Name) const virtual
Returns item flags.
Reimplemented from VPE::VProperty.
Definition at line 89 of file vformulaproperty.cpp.
References VPE::VProperty::DPC_Data, and VPE::VProperty::DPC_Name.
getEditorData()
QVariant VFormulaProperty::getEditorData (const QWidget * editor) const virtual
Gets the data from the widget.
Reimplemented from VPE::VProperty.
Definition at line 136 of file vformulaproperty.cpp.
References VFormulaPropertyEditor::GetFormula().
GetFormula()
VFormula VFormulaProperty::GetFormula () const
Returns the formula.
Definition at line 194 of file vformulaproperty.cpp.
References VFormula::value.
Referenced by childValueChanged(), and getValue().
getValue()
QVariant VFormulaProperty::getValue () const virtual
Returns the value of the property as a QVariant.
Reimplemented from VPE::VProperty.
Definition at line 185 of file vformulaproperty.cpp.
References GetFormula().
Referenced by data().
setEditorData()
bool VFormulaProperty::setEditorData (QWidget * editor) virtual
Sets the property's data to the editor (returns false, if the standard delegate should do that)
Reimplemented from VPE::VProperty.
Definition at line 120 of file vformulaproperty.cpp.
References VFormulaPropertyEditor::SetFormula(), and VFormula::value.
Referenced by SetFormula().
SetFormula()
void VFormulaProperty::SetFormula (const VFormula & formula)
Sets the formula.
Definition at line 200 of file vformulaproperty.cpp.
References VPE::VPropertyPrivate::Children, VPE::VProperty::d_ptr, VFormula::FormulaTypeId(), VFormula::GetFormula(), and setEditorData().
Referenced by VToolOptionsPropertyBrowser::addPropertyFormula(), childValueChanged(), and setValue().
setValue()
void VFormulaProperty::setValue (const QVariant & value) virtual
Sets the value of the property.
Reimplemented from VPE::VProperty.
Definition at line 178 of file vformulaproperty.cpp.
References SetFormula(), and VFormula::value.
Referenced by VFormulaProperty().
type()
QString VFormulaProperty::type () const virtual
Returns a string containing the type of the property.
Reimplemented from VPE::VProperty.
Definition at line 150 of file vformulaproperty.cpp.
The documentation for this class was generated from the following files:
src/app/seamly2d/core/vformulaproperty.h
src/app/seamly2d/core/vformulaproperty.cpp