Seamly2D: RefHash3KeysIdPool< TVal, THasher > Class Template Reference
RefHash3KeysIdPool< TVal, THasher > Class Template Reference
#include <RefHash3KeysIdPool.hpp>
Public Member Functions
RefHash3KeysIdPool (const XMLSize_t modulus, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const THasher &hasher, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHash3KeysIdPool ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2, const int key3) const
void removeAll ()
TVal * getByKey (const void *const key1, const int key2, const int key3)
const TVal * getByKey (const void *const key1, const int key2, const int key3) const
TVal * getById (const unsigned int elemId)
const TVal * getById (const unsigned int elemId) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
XMLSize_t put (void *key1, int key2, int key3, TVal *const valueToAdopt)
RefHash3KeysIdPool (const XMLSize_t modulus, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const THasher &hasher, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHash3KeysIdPool ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2, const int key3) const
void removeAll ()
TVal * getByKey (const void *const key1, const int key2, const int key3)
const TVal * getByKey (const void *const key1, const int key2, const int key3) const
TVal * getById (const unsigned int elemId)
const TVal * getById (const unsigned int elemId) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
XMLSize_t put (void *key1, int key2, int key3, TVal *const valueToAdopt)
RefHash3KeysIdPool (const XMLSize_t modulus, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const THasher &hasher, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, const XMLSize_t initSize=128, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHash3KeysIdPool ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2, const int key3) const
void removeAll ()
TVal * getByKey (const void *const key1, const int key2, const int key3)
const TVal * getByKey (const void *const key1, const int key2, const int key3) const
TVal * getById (const unsigned int elemId)
const TVal * getById (const unsigned int elemId) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
XMLSize_t put (void *key1, int key2, int key3, TVal *const valueToAdopt)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
RefHash3KeysIdPool (const RefHash3KeysIdPool< TVal, THasher > &)
RefHash3KeysIdPool< TVal, THasher > & operator= (const RefHash3KeysIdPool< TVal, THasher > &)
RefHash3KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t &hashVal)
const RefHash3KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
RefHash3KeysIdPool (const RefHash3KeysIdPool< TVal, THasher > &)
RefHash3KeysIdPool< TVal, THasher > & operator= (const RefHash3KeysIdPool< TVal, THasher > &)
RefHash3KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t &hashVal)
const RefHash3KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
RefHash3KeysIdPool (const RefHash3KeysIdPool< TVal, THasher > &)
RefHash3KeysIdPool< TVal, THasher > & operator= (const RefHash3KeysIdPool< TVal, THasher > &)
RefHash3KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t &hashVal)
const RefHash3KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
Private Attributes
MemoryManager * fMemoryManager
bool fAdoptedElems
RefHash3KeysTableBucketElem< TVal > ** fBucketList
XMLSize_t fHashModulus
TVal ** fIdPtrs
XMLSize_t fIdPtrsCount
XMLSize_t fIdCounter
THasher fHasher
Friends
class RefHash3KeysIdPoolEnumerator< TVal, THasher >
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
template<class TVal, class THasher = StringHasher>
class RefHash3KeysIdPool< TVal, THasher >
Definition at line 83 of file RefHash3KeysIdPool.hpp.
Constructor & Destructor Documentation
RefHash3KeysIdPool() [1/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [2/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const THasher & hasher, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [3/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [4/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHash3KeysIdPool() [1/3]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::~RefHash3KeysIdPool ()
RefHash3KeysIdPool() [5/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const RefHash3KeysIdPool< TVal, THasher > &) private
RefHash3KeysIdPool() [6/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [7/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const THasher & hasher, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [8/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [9/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHash3KeysIdPool() [2/3]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::~RefHash3KeysIdPool ()
RefHash3KeysIdPool() [10/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const RefHash3KeysIdPool< TVal, THasher > &) private
RefHash3KeysIdPool() [11/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [12/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const THasher & hasher, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [13/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash3KeysIdPool() [14/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, const XMLSize_t initSize = 128, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHash3KeysIdPool() [3/3]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::~RefHash3KeysIdPool ()
RefHash3KeysIdPool() [15/15]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool< TVal, THasher >::RefHash3KeysIdPool (const RefHash3KeysIdPool< TVal, THasher > &) private
Member Function Documentation
containsKey() [1/3]
template<class TVal , class THasher = StringHasher> bool RefHash3KeysIdPool< TVal, THasher >::containsKey (const void *const key1, const int key2, const int key3) const
containsKey() [2/3]
template<class TVal , class THasher = StringHasher> bool RefHash3KeysIdPool< TVal, THasher >::containsKey (const void *const key1, const int key2, const int key3) const
containsKey() [3/3]
template<class TVal , class THasher = StringHasher> bool RefHash3KeysIdPool< TVal, THasher >::containsKey (const void *const key1, const int key2, const int key3) const
findBucketElem() [1/6]
template<class TVal , class THasher = StringHasher> RefHash3KeysTableBucketElem<TVal>* RefHash3KeysIdPool< TVal, THasher >::findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t & hashVal) private
findBucketElem() [2/6]
template<class TVal , class THasher = StringHasher> RefHash3KeysTableBucketElem<TVal>* RefHash3KeysIdPool< TVal, THasher >::findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t & hashVal) private
findBucketElem() [3/6]
template<class TVal , class THasher = StringHasher> RefHash3KeysTableBucketElem<TVal>* RefHash3KeysIdPool< TVal, THasher >::findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t & hashVal) private
findBucketElem() [4/6]
template<class TVal , class THasher = StringHasher> const RefHash3KeysTableBucketElem<TVal>* RefHash3KeysIdPool< TVal, THasher >::findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t & hashVal) const private
findBucketElem() [5/6]
template<class TVal , class THasher = StringHasher> const RefHash3KeysTableBucketElem<TVal>* RefHash3KeysIdPool< TVal, THasher >::findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t & hashVal) const private
findBucketElem() [6/6]
template<class TVal , class THasher = StringHasher> const RefHash3KeysTableBucketElem<TVal>* RefHash3KeysIdPool< TVal, THasher >::findBucketElem (const void *const key1, const int key2, const int key3, XMLSize_t & hashVal) const private
getById() [1/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash3KeysIdPool< TVal, THasher >::getById (const unsigned int elemId)
Referenced by SchemaGrammar::getElemDecl().
getById() [2/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash3KeysIdPool< TVal, THasher >::getById (const unsigned int elemId)
getById() [3/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash3KeysIdPool< TVal, THasher >::getById (const unsigned int elemId)
getById() [4/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash3KeysIdPool< TVal, THasher >::getById (const unsigned int elemId) const
getById() [5/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash3KeysIdPool< TVal, THasher >::getById (const unsigned int elemId) const
getById() [6/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash3KeysIdPool< TVal, THasher >::getById (const unsigned int elemId) const
getByKey() [1/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash3KeysIdPool< TVal, THasher >::getByKey (const void *const key1, const int key2, const int key3)
Referenced by SchemaGrammar::getElemDecl(), and SchemaGrammar::getElemId().
getByKey() [2/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash3KeysIdPool< TVal, THasher >::getByKey (const void *const key1, const int key2, const int key3)
getByKey() [3/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash3KeysIdPool< TVal, THasher >::getByKey (const void *const key1, const int key2, const int key3)
getByKey() [4/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash3KeysIdPool< TVal, THasher >::getByKey (const void *const key1, const int key2, const int key3) const
getByKey() [5/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash3KeysIdPool< TVal, THasher >::getByKey (const void *const key1, const int key2, const int key3) const
getByKey() [6/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash3KeysIdPool< TVal, THasher >::getByKey (const void *const key1, const int key2, const int key3) const
getHashModulus() [1/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::getHashModulus () const
getHashModulus() [2/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::getHashModulus () const
getHashModulus() [3/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::getHashModulus () const
getMemoryManager() [1/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHash3KeysIdPool< TVal, THasher >::getMemoryManager () const
getMemoryManager() [2/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHash3KeysIdPool< TVal, THasher >::getMemoryManager () const
getMemoryManager() [3/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHash3KeysIdPool< TVal, THasher >::getMemoryManager () const
initialize() [1/3]
template<class TVal , class THasher = StringHasher> void RefHash3KeysIdPool< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [2/3]
template<class TVal , class THasher = StringHasher> void RefHash3KeysIdPool< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [3/3]
template<class TVal , class THasher = StringHasher> void RefHash3KeysIdPool< TVal, THasher >::initialize (const XMLSize_t modulus) private
isEmpty() [1/3]
template<class TVal , class THasher = StringHasher> bool RefHash3KeysIdPool< TVal, THasher >::isEmpty () const
isEmpty() [2/3]
template<class TVal , class THasher = StringHasher> bool RefHash3KeysIdPool< TVal, THasher >::isEmpty () const
isEmpty() [3/3]
template<class TVal , class THasher = StringHasher> bool RefHash3KeysIdPool< TVal, THasher >::isEmpty () const
operator=() [1/3]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool<TVal, THasher>& RefHash3KeysIdPool< TVal, THasher >::operator= (const RefHash3KeysIdPool< TVal, THasher > &) private
operator=() [2/3]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool<TVal, THasher>& RefHash3KeysIdPool< TVal, THasher >::operator= (const RefHash3KeysIdPool< TVal, THasher > &) private
operator=() [3/3]
template<class TVal , class THasher = StringHasher> RefHash3KeysIdPool<TVal, THasher>& RefHash3KeysIdPool< TVal, THasher >::operator= (const RefHash3KeysIdPool< TVal, THasher > &) private
put() [1/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::put (void * key1, int key2, int key3, TVal *const valueToAdopt)
Referenced by SchemaGrammar::putElemDecl(), and SchemaGrammar::putGroupElemDecl().
put() [2/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::put (void * key1, int key2, int key3, TVal *const valueToAdopt)
put() [3/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::put (void * key1, int key2, int key3, TVal *const valueToAdopt)
removeAll() [1/3]
template<class TVal , class THasher = StringHasher> void RefHash3KeysIdPool< TVal, THasher >::removeAll ()
removeAll() [2/3]
template<class TVal , class THasher = StringHasher> void RefHash3KeysIdPool< TVal, THasher >::removeAll ()
removeAll() [3/3]
template<class TVal , class THasher = StringHasher> void RefHash3KeysIdPool< TVal, THasher >::removeAll ()
Friends And Related Function Documentation
RefHash3KeysIdPoolEnumerator< TVal, THasher >
template<class TVal , class THasher = StringHasher> friend class RefHash3KeysIdPoolEnumerator< TVal, THasher > friend
Definition at line 138 of file RefHash3KeysIdPool.hpp.
Member Data Documentation
fAdoptedElems
template<class TVal , class THasher = StringHasher> bool RefHash3KeysIdPool< TVal, THasher >::fAdoptedElems private
Definition at line 196 of file RefHash3KeysIdPool.hpp.
fBucketList
template<class TVal , class THasher = StringHasher> RefHash3KeysTableBucketElem< TVal > ** RefHash3KeysIdPool< TVal, THasher >::fBucketList private
Definition at line 197 of file RefHash3KeysIdPool.hpp.
fHasher
template<class TVal , class THasher = StringHasher> THasher RefHash3KeysIdPool< TVal, THasher >::fHasher private
Definition at line 202 of file RefHash3KeysIdPool.hpp.
fHashModulus
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::fHashModulus private
Definition at line 198 of file RefHash3KeysIdPool.hpp.
fIdCounter
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::fIdCounter private
Definition at line 201 of file RefHash3KeysIdPool.hpp.
fIdPtrs
template<class TVal , class THasher = StringHasher> TVal ** RefHash3KeysIdPool< TVal, THasher >::fIdPtrs private
Definition at line 199 of file RefHash3KeysIdPool.hpp.
fIdPtrsCount
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash3KeysIdPool< TVal, THasher >::fIdPtrsCount private
Definition at line 200 of file RefHash3KeysIdPool.hpp.
fMemoryManager
template<class TVal , class THasher = StringHasher> MemoryManager * RefHash3KeysIdPool< TVal, THasher >::fMemoryManager private
Definition at line 195 of file RefHash3KeysIdPool.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/RefHash3KeysIdPool.hpp