Seamly2D: HistoryDialog Class Reference
HistoryDialog Class Reference
The HistoryDialog class show dialog history.
#include <history_dialog.h>
Public Slots
virtual void DialogAccepted () Q_DECL_OVERRIDE
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply () Q_DECL_OVERRIDE
DialogApply apply data and emit signal about applied dialog.
void cellClicked (int row, int column)
cellClicked changed history record
void changedCursor (quint32 id)
changedCursor changed cursor of input. Cursor show after which record we will insert new object
void updateHistory ()
updateHistory update history table
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Signals
void showHistoryTool (quint32 id, bool enable)
showHistoryTool signal change color of selected in records tool
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Public Member Functions
HistoryDialog (VContainer *data, VPattern *doc, QWidget *parent=nullptr)
HistoryDialog create dialog.
virtual ~HistoryDialog () Q_DECL_OVERRIDE
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when windows is closing
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
virtual void CheckState ()
CheckState enable, when all is correct, or disable, when something wrong, button ok.
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
virtual void ShowVisualization ()
virtual void SaveData ()
SaveData Put dialog data in local variables.
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Member Functions
void fillTable ()
cursorToolRecordRow save number of row selected record
RowData record (const VToolRecord &tool)
Record return description for record.
void initializeTable ()
initializeTable set initial option of table
void showTool ()
showTool show selected point
QString getPointName (quint32 pointId)
HistoryDialog::PointName return point name by id.
quint32 attrUInt (const QDomElement &domElement, const QString &name)
void retranslateUi ()
int cursorRow () const
void findText (const QString &text)
void copyToClipboard ()
copyToClipboard copy dialog selection to clipboard as comma separated values.
Private Attributes
Ui::HistoryDialog * ui
VPattern * m_doc
ui keeps information about user interface
qint32 m_cursorRow
doc dom document container
qint32 m_cursorToolRecordRow
cursorRow save number of row where is cursor
Additional Inherited Members
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
The HistoryDialog class show dialog history.
Definition at line 78 of file history_dialog.h.
Constructor & Destructor Documentation
HistoryDialog()
HistoryDialog::HistoryDialog (VContainer * data, VPattern * doc, QWidget * parent = nullptr)
HistoryDialog create dialog.
Parameters
data container with data
doc dom document container
parent parent widget
Definition at line 84 of file history_dialog.cpp.
References cellClicked(), changedCursor(), VAbstractPattern::ChangedCursor(), copyToClipboard(), DialogAccepted(), fillTable(), findText(), initializeTable(), m_doc, DialogTool::ok_Button, VAbstractPattern::patternChanged(), qApp, showHistoryTool(), showTool(), VAbstractPattern::ShowTool(), ui, and updateHistory().
~HistoryDialog()
HistoryDialog::~HistoryDialog () virtual
Definition at line 121 of file history_dialog.cpp.
References ui.
Member Function Documentation
attrUInt()
quint32 HistoryDialog::attrUInt (const QDomElement & domElement, const QString & name) private
Definition at line 665 of file history_dialog.cpp.
References VDomDocument::GetParametrUInt(), and m_doc.
cellClicked
void HistoryDialog::cellClicked (int row, int column) slot
cellClicked changed history record
Parameters
row number row in table
column number column in table
Definition at line 144 of file history_dialog.cpp.
References m_cursorRow, m_cursorToolRecordRow, m_doc, VAbstractPattern::setCursor(), showHistoryTool(), and ui.
Referenced by HistoryDialog(), and retranslateUi().
changedCursor
void HistoryDialog::changedCursor (quint32 id) slot
changedCursor changed cursor of input. Cursor show after which record we will insert new object
Parameters
id id of object
Definition at line 177 of file history_dialog.cpp.
References m_cursorRow, and ui.
Referenced by HistoryDialog().
changeEvent()
void HistoryDialog::changeEvent (QEvent * event) protected virtual
Definition at line 684 of file history_dialog.cpp.
References retranslateUi(), and ui.
closeEvent()
void HistoryDialog::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when windows is closing
Parameters
event event
Reimplemented from DialogTool.
Definition at line 675 of file history_dialog.cpp.
References DialogTool::closeEvent(), m_cursorToolRecordRow, showHistoryTool(), and ui.
copyToClipboard()
void HistoryDialog::copyToClipboard () private
copyToClipboard copy dialog selection to clipboard as comma separated values.
Definition at line 782 of file history_dialog.cpp.
References ui.
Referenced by HistoryDialog().
cursorRow()
int HistoryDialog::cursorRow () const private
Definition at line 742 of file history_dialog.cpp.
References VAbstractPattern::getCursor(), m_doc, and ui.
Referenced by fillTable().
DialogAccepted
void HistoryDialog::DialogAccepted () virtual slot
DialogAccepted save data and emit signal about closed dialog.
Definition at line 130 of file history_dialog.cpp.
References DialogTool::DialogClosed(), m_cursorToolRecordRow, showHistoryTool(), and ui.
Referenced by HistoryDialog().
DialogApply
virtual void HistoryDialog::DialogApply () inline virtual slot
DialogApply apply data and emit signal about applied dialog.
TODO ISSUE 79 : create real function
Definition at line 90 of file history_dialog.h.
eventFilter()
bool HistoryDialog::eventFilter (QObject * object, QEvent * event) protected virtual
Reimplemented from DialogTool.
Definition at line 698 of file history_dialog.cpp.
References DialogTool::eventFilter(), and qApp.
fillTable()
void HistoryDialog::fillTable () private
cursorToolRecordRow save number of row selected record
fillTable fill table
Definition at line 207 of file history_dialog.cpp.
References cursorRow(), VAbstractPattern::getBlockHistory(), RowData::icon, RowData::id, m_cursorRow, m_doc, RowData::name, record(), SCASSERT, RowData::tool, and ui.
Referenced by HistoryDialog(), and updateHistory().
findText()
void HistoryDialog::findText (const QString & text) private
Definition at line 762 of file history_dialog.cpp.
References ui, and updateHistory().
Referenced by HistoryDialog().
getPointName()
QString HistoryDialog::getPointName (quint32 pointId) private
HistoryDialog::PointName return point name by id.
Refacoring what hide ugly string getting point name by id.
Parameters
pointId point if in data.
Returns
point name.
Definition at line 659 of file history_dialog.cpp.
References DialogTool::data, and VContainer::GeometricObject().
initializeTable()
QT_WARNING_POP void HistoryDialog::initializeTable () private
initializeTable set initial option of table
Definition at line 623 of file history_dialog.cpp.
References ui.
Referenced by HistoryDialog(), and updateHistory().
record()
QT_WARNING_PUSH RowData HistoryDialog::record (const VToolRecord & tool) private
Record return description for record.
Parameters
tool record data
Returns
RowData
Definition at line 270 of file history_dialog.cpp.
References AbstractSpline, AlongLine, AnchorPoint, Arc, ArcIntersectAxis, ArcWithLength, Arrow, AttrArc, AttrAxisP1, AttrAxisP2, AttrBasePoint, AttrCenter, AttrDartP1, AttrDartP2, AttrFirstPoint, AttrP1Line, AttrP1Line1, AttrP1Line2, AttrP2Line, AttrP2Line1, AttrP2Line2, AttrSecondPoint, VToolCutSpline::AttrSpline, VToolCutSplinePath::AttrSplinePath, AttrSuffix, AttrThirdPoint, BasePoint, Bisector, CubicBezier, CubicBezierPath, CurveIntersectAxis, Cut, CutArc, CutSpline, CutSplinePath, DoublePoint, EllipticalArc, EndLine, VExceptionBadId::ErrorMessage(), Group, Height, RowData::icon, RowData::id, InsertNodes, InternalPath, LAST_ONE_DO_NOT_USE, Line, LineIntersect, LineIntersectAxis, LinePoint, Midpoint, MirrorByAxis, MirrorByLine, Move, RowData::name, NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, Normal, Piece, PointFromArcAndTangent, PointFromCircleAndTangent, PointOfContact, PointOfIntersection, PointOfIntersectionArcs, PointOfIntersectionCircles, PointOfIntersectionCurves, Rotation, SCASSERT, ShoulderPoint, SinglePoint, Spline, SplinePath, splPath, RowData::tool, Triangle, TrueDarts, and Union.
Referenced by fillTable().
retranslateUi()
void HistoryDialog::retranslateUi () private
Definition at line 728 of file history_dialog.cpp.
References cellClicked(), m_cursorRow, SCASSERT, ui, and updateHistory().
Referenced by changeEvent().
showHistoryTool
void HistoryDialog::showHistoryTool (quint32 id, bool enable) signal
showHistoryTool signal change color of selected in records tool
Parameters
id id of tool
enable true enable selection, false disable selection
Referenced by cellClicked(), closeEvent(), DialogAccepted(), HistoryDialog(), and showTool().
showTool()
void HistoryDialog::showTool () private
showTool show selected point
Definition at line 637 of file history_dialog.cpp.
References VAbstractPattern::getHistory(), m_cursorToolRecordRow, m_doc, showHistoryTool(), and ui.
Referenced by HistoryDialog().
updateHistory
void HistoryDialog::updateHistory () slot
updateHistory update history table
Definition at line 197 of file history_dialog.cpp.
References fillTable(), and initializeTable().
Referenced by findText(), HistoryDialog(), and retranslateUi().
Member Data Documentation
m_cursorRow
qint32 HistoryDialog::m_cursorRow private
doc dom document container
Definition at line 113 of file history_dialog.h.
Referenced by cellClicked(), changedCursor(), fillTable(), and retranslateUi().
m_cursorToolRecordRow
qint32 HistoryDialog::m_cursorToolRecordRow private
cursorRow save number of row where is cursor
Definition at line 114 of file history_dialog.h.
Referenced by cellClicked(), closeEvent(), DialogAccepted(), and showTool().
m_doc
VPattern* HistoryDialog::m_doc private
ui keeps information about user interface
Definition at line 112 of file history_dialog.h.
Referenced by attrUInt(), cellClicked(), cursorRow(), fillTable(), HistoryDialog(), and showTool().
ui
Ui::HistoryDialog* HistoryDialog::ui private
Definition at line 111 of file history_dialog.h.
Referenced by cellClicked(), changedCursor(), changeEvent(), closeEvent(), copyToClipboard(), cursorRow(), DialogAccepted(), fillTable(), findText(), HistoryDialog(), initializeTable(), retranslateUi(), showTool(), and ~HistoryDialog().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/history_dialog.h
src/app/seamly2d/dialogs/history_dialog.cpp