Seamly2D: VContour Class Reference
VContour Class Reference
#include <vcontour.h>
Public Member Functions
VContour ()
VContour (int height, int width)
VContour (const VContour &contour)
~VContour ()
VContour & operator= (const VContour &contour)
void Swap (VContour &contour) Q_DECL_NOTHROW
void SetContour (const QVector< QPointF > &contour)
QVector< QPointF > GetContour () const
quint32 GetShift () const
void SetShift (quint32 shift)
int GetHeight () const
void setHeight (int height)
int GetWidth () const
void SetWidth (int width)
QSizeF GetSize () const
QVector< QPointF > UniteWithContour (const VLayoutPiece &detail, int globalI, int detJ, BestFrom type) const
QLineF EmptySheetEdge () const
int GlobalEdgesCount () const
QLineF GlobalEdge (int i) const
QVector< QPointF > CutEdge (const QLineF &edge) const
QVector< QPointF > CutEmptySheetEdge () const
const QPointF & at (int i) const
QRectF BoundingRect () const
QPainterPath ContourPath () const
Private Member Functions
void AppendWhole (QVector< QPointF > &contour, const VLayoutPiece &detail, int detJ) const
Private Attributes
QSharedDataPointer< VContourData > d
Detailed Description
Definition at line 70 of file vcontour.h.
Constructor & Destructor Documentation
VContour() [1/3]
VContour::VContour ()
Definition at line 74 of file vcontour.cpp.
VContour() [2/3]
VContour::VContour (int height, int width)
Definition at line 79 of file vcontour.cpp.
VContour() [3/3]
VContour::VContour (const VContour & contour)
Definition at line 84 of file vcontour.cpp.
~VContour()
VContour::~VContour ()
Definition at line 100 of file vcontour.cpp.
Member Function Documentation
AppendWhole()
void VContour::AppendWhole (QVector< QPointF > & contour, const VLayoutPiece & detail, int detJ) const private
Definition at line 366 of file vcontour.cpp.
References CutEdge(), VLayoutPiece::LayoutEdge(), and VLayoutPiece::LayoutEdgesCount().
Referenced by UniteWithContour().
at()
const QPointF & VContour::at (int i) const
Definition at line 331 of file vcontour.cpp.
References d.
BoundingRect()
QRectF VContour::BoundingRect () const
Definition at line 337 of file vcontour.cpp.
References GetContour().
Referenced by VPosition::Crossing().
ContourPath()
QPainterPath VContour::ContourPath () const
Definition at line 349 of file vcontour.cpp.
References GetContour().
Referenced by VPosition::Crossing().
CutEdge()
QVector< QPointF > VContour::CutEdge (const QLineF & edge) const
Definition at line 285 of file vcontour.cpp.
References d.
Referenced by AppendWhole(), and UniteWithContour().
CutEmptySheetEdge()
QVector< QPointF > VContour::CutEmptySheetEdge () const
Definition at line 317 of file vcontour.cpp.
References EmptySheetEdge(), and GlobalEdgesCount().
Referenced by VPosition::DrawDebug().
EmptySheetEdge()
QLineF VContour::EmptySheetEdge () const
Definition at line 388 of file vcontour.cpp.
References d.
Referenced by CutEmptySheetEdge(), and GlobalEdge().
GetContour()
QVector< QPointF > VContour::GetContour () const
Definition at line 110 of file vcontour.cpp.
References d.
Referenced by BoundingRect(), VPosition::CheckCombineEdges(), VPosition::CombineEdges(), ContourPath(), VPosition::DrawDebug(), VPosition::RotateEdges(), and VPosition::run().
GetHeight()
int VContour::GetHeight () const
Definition at line 128 of file vcontour.cpp.
References d.
Referenced by VPosition::DrawDebug(), and VPosition::SheetContains().
GetShift()
quint32 VContour::GetShift () const
Definition at line 116 of file vcontour.cpp.
References d.
GetSize()
QSizeF VContour::GetSize () const
Definition at line 152 of file vcontour.cpp.
References d.
GetWidth()
int VContour::GetWidth () const
Definition at line 140 of file vcontour.cpp.
References d.
Referenced by VPosition::DrawDebug(), and VPosition::SheetContains().
GlobalEdge()
QLineF VContour::GlobalEdge (int i) const
Definition at line 252 of file vcontour.cpp.
References d, EmptySheetEdge(), and GlobalEdgesCount().
Referenced by VPosition::CheckCombineEdges(), and VPosition::CheckRotationEdges().
GlobalEdgesCount()
int VContour::GlobalEdgesCount () const
Definition at line 239 of file vcontour.cpp.
References d.
Referenced by CutEmptySheetEdge(), GlobalEdge(), and UniteWithContour().
operator=()
VContour & VContour::operator= (const VContour & contour)
Definition at line 89 of file vcontour.cpp.
References d.
SetContour()
void VContour::SetContour (const QVector< QPointF > & contour)
Definition at line 104 of file vcontour.cpp.
References d.
setHeight()
void VContour::setHeight (int height)
Definition at line 134 of file vcontour.cpp.
References d.
SetShift()
void VContour::SetShift (quint32 shift)
Definition at line 122 of file vcontour.cpp.
References d.
SetWidth()
void VContour::SetWidth (int width)
Definition at line 146 of file vcontour.cpp.
References d.
Swap()
void VContour::Swap (VContour & contour)
Definition at line 70 of file vcontour.cpp.
UniteWithContour()
QVector< QPointF > VContour::UniteWithContour (const VLayoutPiece & detail, int globalI, int detJ, BestFrom type) const
Definition at line 158 of file vcontour.cpp.
References AppendWhole(), CutEdge(), d, GlobalEdgesCount(), VLayoutPiece::LayoutEdge(), VLayoutPiece::LayoutEdgesCount(), and Rotation.
Referenced by VPosition::SaveCandidate().
Member Data Documentation
d
QSharedDataPointer<VContourData> VContour::d private
Definition at line 115 of file vcontour.h.
Referenced by at(), CutEdge(), EmptySheetEdge(), GetContour(), GetHeight(), GetShift(), GetSize(), GetWidth(), GlobalEdge(), GlobalEdgesCount(), operator=(), SetContour(), setHeight(), SetShift(), SetWidth(), and UniteWithContour().
The documentation for this class was generated from the following files:
src/libs/vlayout/vcontour.h
src/libs/vlayout/vcontour.cpp