Seamly2D: VNodeDetail Class Reference
VNodeDetail Class Reference
The VNodeDetail class keep information about detail node.
#include <vnodedetail.h>
Public Member Functions
VNodeDetail ()
VNodeDetail default constructor.
VNodeDetail (quint32 id, Tool typeTool, NodeDetail typeNode, qreal mx=0, qreal my=0, bool reverse=false)
VNodeDetail constructor.
VNodeDetail (const VNodeDetail &node)
VNodeDetail copy constructor.
~VNodeDetail ()
VNodeDetail & operator= (const VNodeDetail &node)
operator = assignment operator
void Swap (VNodeDetail &node) Q_DECL_NOTHROW
quint32 getId () const
getId return object id.
void setId (const quint32 &value)
setId set object id.
Tool getTypeTool () const
getTypeTool return tool type.
void setTypeTool (const Tool &value)
setTypeTool set tool type.
NodeDetail getTypeNode () const
getTypeNode return node type.
void setTypeNode (const NodeDetail &value)
setTypeNode set node type.
qreal getMx () const
getMx return object bias x axis.
void setMx (const qreal &value)
setMx set object bias x axis.
qreal getMy () const
getMy return object bias y axis.
void setMy (const qreal &value)
setMy set object bias y axis.
bool getReverse () const
void setReverse (bool reverse)
Static Public Member Functions
static QVector< VPieceNode > Convert (const VContainer *data, const QVector< VNodeDetail > &nodes, qreal width, bool closed)
Private Attributes
QSharedDataPointer< VNodeDetailData > d
Detailed Description
The VNodeDetail class keep information about detail node.
Definition at line 69 of file vnodedetail.h.
Constructor & Destructor Documentation
VNodeDetail() [1/3]
VNodeDetail::VNodeDetail ()
VNodeDetail default constructor.
Definition at line 131 of file vnodedetail.cpp.
VNodeDetail() [2/3]
VNodeDetail::VNodeDetail (quint32 id, Tool typeTool, NodeDetail typeNode, qreal mx = 0, qreal my = 0, bool reverse = false)
VNodeDetail constructor.
Parameters
id object id
typeTool type tool
typeNode type node
mx object bias x axis
my object bias y axis
Definition at line 136 of file vnodedetail.cpp.
VNodeDetail() [3/3]
VNodeDetail::VNodeDetail (const VNodeDetail & node)
VNodeDetail copy constructor.
Parameters
node node
Definition at line 141 of file vnodedetail.cpp.
~VNodeDetail()
VNodeDetail::~VNodeDetail ()
Definition at line 157 of file vnodedetail.cpp.
Member Function Documentation
Convert()
QVector< VPieceNode > VNodeDetail::Convert (const VContainer * data, const QVector< VNodeDetail > & nodes, qreal width, bool closed) static
Definition at line 249 of file vnodedetail.cpp.
References VPiecePath::Append(), anonymous_namespace{vnodedetail.cpp}::ConvertAfter(), anonymous_namespace{vnodedetail.cpp}::ConvertBefore(), VPiecePath::CountNodes(), VContainer::GeometricObject(), getId(), getMx(), getMy(), VPiecePath::GetNodes(), getReverse(), getTypeTool(), VPiecePath::NodeNextPoint(), NodePoint, VPiecePath::NodePreviousPoint(), and VPiecePath::PathPoints().
Referenced by VPattern::parsePieceNodes().
getId()
quint32 VNodeDetail::getId () const
getId return object id.
Returns
id.
Definition at line 161 of file vnodedetail.cpp.
References d.
Referenced by Convert().
getMx()
qreal VNodeDetail::getMx () const
getMx return object bias x axis.
Returns
bias x axis.
Definition at line 199 of file vnodedetail.cpp.
References d.
Referenced by Convert().
getMy()
qreal VNodeDetail::getMy () const
getMy return object bias y axis.
Returns
bias y axis.
Definition at line 211 of file vnodedetail.cpp.
References d.
Referenced by Convert().
getReverse()
bool VNodeDetail::getReverse () const
Definition at line 223 of file vnodedetail.cpp.
References d, getTypeTool(), and NodePoint.
Referenced by Convert().
getTypeNode()
NodeDetail VNodeDetail::getTypeNode () const
getTypeNode return node type.
Returns
node type.
Definition at line 186 of file vnodedetail.cpp.
References d.
getTypeTool()
Tool VNodeDetail::getTypeTool () const
getTypeTool return tool type.
Returns
tool type.
Definition at line 173 of file vnodedetail.cpp.
References d.
Referenced by Convert(), getReverse(), and setReverse().
operator=()
VNodeDetail & VNodeDetail::operator= (const VNodeDetail & node)
operator = assignment operator
Parameters
node node
Returns
node
Definition at line 146 of file vnodedetail.cpp.
References d.
setId()
void VNodeDetail::setId (const quint32 & value)
setId set object id.
Parameters
value object id.
Definition at line 167 of file vnodedetail.cpp.
References d.
setMx()
void VNodeDetail::setMx (const qreal & value)
setMx set object bias x axis.
Parameters
value bias x axis.
Definition at line 205 of file vnodedetail.cpp.
References d.
setMy()
void VNodeDetail::setMy (const qreal & value)
setMy set object bias y axis.
Parameters
value bias y axis.
Definition at line 217 of file vnodedetail.cpp.
References d.
setReverse()
void VNodeDetail::setReverse (bool reverse)
Definition at line 236 of file vnodedetail.cpp.
References d, getTypeTool(), and NodePoint.
setTypeNode()
void VNodeDetail::setTypeNode (const NodeDetail & value)
setTypeNode set node type.
Parameters
value node type.
Definition at line 193 of file vnodedetail.cpp.
References d.
setTypeTool()
void VNodeDetail::setTypeTool (const Tool & value)
setTypeTool set tool type.
Parameters
value tool type.
Definition at line 180 of file vnodedetail.cpp.
References d.
Swap()
void VNodeDetail::Swap (VNodeDetail & node)
Definition at line 127 of file vnodedetail.cpp.
Member Data Documentation
d
QSharedDataPointer<VNodeDetailData> VNodeDetail::d private
Definition at line 162 of file vnodedetail.h.
Referenced by getId(), getMx(), getMy(), getReverse(), getTypeNode(), getTypeTool(), operator=(), setId(), setMx(), setMy(), setReverse(), setTypeNode(), and setTypeTool().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/vnodedetail.h
src/libs/vpatterndb/vnodedetail.cpp