Seamly2D: VPE::VPointFProperty Class Reference
VPE::VPointFProperty Class Reference
#include <vpointfproperty.h>
Public Member Functions
VPointFProperty (const QString &name)
virtual ~VPointFProperty () Q_DECL_OVERRIDE
virtual QVariant data (int column=DPC_Name, int role=Qt::DisplayRole) const Q_DECL_OVERRIDE
Get the data how it should be displayed.
Qt::ItemFlags flags (int column=DPC_Name) const Q_DECL_OVERRIDE
Returns item flags.
virtual QPointF getPointF () const
Returns the QPointF.
virtual void setPointF (const QPointF &point)
Sets the QPointF.
virtual void setPointF (qreal x, qreal y)
Sets the QPointF.
virtual QString type () const Q_DECL_OVERRIDE
Returns a string containing the type of the property.
virtual Q_REQUIRED_RESULT VProperty * clone (bool include_children=true, VProperty *container=nullptr) const Q_DECL_OVERRIDE
Clones this property.
virtual void setValue (const QVariant &value) Q_DECL_OVERRIDE
Sets the value of the property.
virtual QVariant getValue () const Q_DECL_OVERRIDE
Returns the value of the property as a QVariant.
Public Member Functions inherited from VPE::VProperty
VProperty (const QString &name, QVariant::Type type=QVariant::String)
Standard constructor, takes a name and a parent property as argument.
virtual ~VProperty () Q_DECL_OVERRIDE
Destructor.
virtual bool setData (const QVariant &data, int role=Qt::EditRole)
This is used by the model to set the data.
virtual bool paint (QPainter *, const QStyleOptionViewItem &, const QModelIndex &, const QAbstractItemDelegate *) const
This is called by the delegate when the property value is being drawn. The standard implementation doesn't do anything. If you reimplement this in a sub property, make sure to return true or the delegate will draw the item.
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &, const QAbstractItemDelegate *)
Returns an editor widget, or NULL if it doesn't supply one.
virtual bool setEditorData (QWidget *editor)
Sets the property's data to the editor (returns false, if the standard delegate should do that)
virtual QVariant getEditorData (const QWidget *editor) const
Gets the data from the widget.
virtual QString serialize () const
Serializes the value to a string.
virtual void deserialize (const QString &value)
Deserializes the value from a string.
virtual void setName (const QString &name)
Sets the name of the property.
virtual QString getName () const
Gets the name of the property.
virtual void setDescription (const QString &desc)
Sets the name of the property.
virtual QString getDescription () const
Gets the name of the property.
virtual int addChild (VProperty *child)
Adds a child to this property.
virtual QList< VProperty * > & getChildren ()
Returns a reference to the list of children.
virtual const QList< VProperty * > & getChildren () const
Returns a reference to the list of children.
virtual VProperty * getChild (int row) const
Returns the child at a certain row.
virtual int getRowCount () const
Gets the number of children.
virtual VProperty * getParent () const
Gets the parent of this property.
virtual void setParent (VProperty *parent)
Sets the parent of this property.
virtual void removeChild (VProperty *child)
Removes a child from the children list, doesn't delete the child!
virtual int getChildRow (VProperty *child) const
Returns the row the child has.
virtual bool getUpdateParent () const
Returns whether the views have to update the parent of this property if it changes.
virtual bool getUpdateChildren () const
Returns whether the views have to update the children of this property if it changes.
virtual void setUpdateBehaviour (bool update_parent, bool update_children)
Sets whether the views should update Parents or children after this property changes.
virtual void setSettings (const QMap< QString, QVariant > &settings)
Sets the settings by calling the overloaded setSetting(const QString &key, const QVariant &value) for each item in the map.
virtual QMap< QString, QVariant > getSettings () const
Get the settings.
virtual void setSetting (const QString &key, const QVariant &value)
Sets the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QVariant getSetting (const QString &key) const
Get the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QStringList getSettingKeys () const
Returns the list of keys of the property's settings.
Property propertyType () const
void setPropertyType (const Property &type)
virtual void updateParent (const QVariant &value)
Additional Inherited Members
Public Types inherited from VPE::VProperty
enum DPC_DisplayColumn { DPC_Name = 0 , DPC_Data }
Public Slots inherited from VPE::VProperty
virtual void childValueChanged (const QVariant &value, int typeForParent)
Signals inherited from VPE::VProperty
void childChanged (const QVariant &value, int typeForParent)
Protected Member Functions inherited from VPE::VProperty
VProperty (VPropertyPrivate *d)
Protected constructor.
Protected Attributes inherited from VPE::VProperty
VPropertyPrivate * d_ptr
The protected structure holding the member variables (to assure binary compatibility)
Detailed Description
Definition at line 38 of file vpointfproperty.h.
Constructor & Destructor Documentation
VPointFProperty()
VPE::VPointFProperty::VPointFProperty (const QString & name) explicit
Definition at line 30 of file vpointfproperty.cpp.
References VPE::VProperty::addChild(), VPE::VProperty::d_ptr, VPE::VProperty::setUpdateBehaviour(), setValue(), and VPE::VPropertyPrivate::VariantValue.
~VPointFProperty()
virtual VPE::VPointFProperty::~VPointFProperty () inline virtual
Definition at line 44 of file vpointfproperty.h.
Member Function Documentation
clone()
VPE::VProperty * VPE::VPointFProperty::clone (bool include_children = true, VProperty * container = nullptr) const virtual
Clones this property.
Parameters
include_children Indicates whether to also clone the children
container If a property is being passed here, no new VProperty is being created but instead it is tried to fill all the data into container. This can also be used when subclassing this function.
Returns
Returns the newly created property (or container, if it was not NULL)
Reimplemented from VPE::VProperty.
Definition at line 109 of file vpointfproperty.cpp.
References VPE::VProperty::clone(), VPE::VProperty::getChildren(), and VPE::VProperty::removeChild().
data()
QVariant VPE::VPointFProperty::data (int column = DPC_Name, int role = Qt::DisplayRole) const virtual
Get the data how it should be displayed.
Reimplemented from VPE::VProperty.
Definition at line 47 of file vpointfproperty.cpp.
References VPE::VProperty::data().
flags()
Qt::ItemFlags VPE::VPointFProperty::flags (int column = DPC_Name) const virtual
Returns item flags.
Reimplemented from VPE::VProperty.
Definition at line 57 of file vpointfproperty.cpp.
getPointF()
QPointF VPE::VPointFProperty::getPointF () const virtual
Returns the QPointF.
Definition at line 67 of file vpointfproperty.cpp.
getValue()
QVariant VPE::VPointFProperty::getValue () const virtual
Returns the value of the property as a QVariant.
Reimplemented from VPE::VProperty.
Definition at line 135 of file vpointfproperty.cpp.
setPointF() [1/2]
void VPE::VPointFProperty::setPointF (const QPointF & point) virtual
Sets the QPointF.
Definition at line 82 of file vpointfproperty.cpp.
setPointF() [2/2]
void VPE::VPointFProperty::setPointF (qreal x, qreal y) virtual
Sets the QPointF.
Definition at line 87 of file vpointfproperty.cpp.
setValue()
void VPE::VPointFProperty::setValue (const QVariant & value) virtual
Sets the value of the property.
Reimplemented from VPE::VProperty.
Definition at line 129 of file vpointfproperty.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolSinglePoint(), and VPointFProperty().
type()
QString VPE::VPointFProperty::type () const virtual
Returns a string containing the type of the property.
Reimplemented from VPE::VProperty.
Definition at line 104 of file vpointfproperty.cpp.
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/plugins/vpointfproperty.h
src/libs/vpropertyexplorer/plugins/vpointfproperty.cpp