Seamly2D: Application2D Class Reference
Application2D Class Reference
The Application2D class reimplamentation QApplication class.
#include <application_2d.h>
Public Member Functions
Application2D (int &argc, char **argv)
Application2D constructor.
virtual ~Application2D () Q_DECL_OVERRIDE
virtual bool notify (QObject *receiver, QEvent *event) Q_DECL_OVERRIDE
notify Reimplemented from QApplication::notify().
void initOptions ()
QString seamlyMeFilePath () const
QTimer * getAutoSaveTimer () const
void setAutoSaveTimer (QTimer *value)
void startLogging ()
QTextStream * logFile ()
virtual const VTranslateVars * translateVariables () Q_DECL_OVERRIDE
virtual bool isAppInGUIMode () const Q_DECL_OVERRIDE
isAppInGUIMode little hack that allow to have access to application state from VAbstractApplication class.
virtual void openSettings () Q_DECL_OVERRIDE
openSettings get acsses to application settings.
VSettings * Seamly2DSettings ()
const VCommandLinePtr commandLine () const
Public Member Functions inherited from VAbstractApplication
VAbstractApplication (int &argc, char **argv)
virtual ~VAbstractApplication () Q_DECL_OVERRIDE
QString translationsPath (const QString &locale=QString()) const
translationsPath return path to the root directory that contains QM files.
void loadTranslations (const QString &locale)
Unit patternUnit () const
const Unit * patternUnitP () const
void setPatternUnit (const Unit &patternUnit)
MeasurementsType patternType () const
void setPatternType (const MeasurementsType &patternType)
VCommonSettings * Settings ()
getSettings hide settings constructor.
template<typename T >
QString LocaleToString (const T &value)
QGraphicsScene * getCurrentScene () const
void setCurrentScene (QGraphicsScene **value)
VMainGraphicsView * getSceneView () const
void setSceneView (VMainGraphicsView *value)
double toPixel (double val) const
double fromPixel (double pix) const
void setCurrentDocument (VAbstractPattern *doc)
VAbstractPattern * getCurrentDocument () const
void setCurrentData (VContainer *data)
VContainer * getCurrentData () const
bool getOpeningPattern () const
void setOpeningPattern ()
QWidget * getMainWindow () const
void setMainWindow (QWidget *value)
QUndoStack * getUndoStack () const
QString getFilePath () const
void setFilePath (const QString &value)
Static Public Member Functions
static void startNewSeamly2D (const QString &fileName=QString())
startNewSeamly2D start Seamly2D in new process, send path to pattern file in argument.
static QStringList pointNameLanguages ()
static bool isGUIMode ()
Protected Member Functions
virtual void initTranslateVariables () Q_DECL_OVERRIDE
virtual bool event (QEvent *e) Q_DECL_OVERRIDE
Private Member Functions
QString logDirPath () const
QString logPath () const
bool createLogDir () const
void beginLogging ()
void clearOldLogs () const
Private Attributes
VTranslateVars * m_trVars
QTimer * m_autoSaveTimer
std::shared_ptr< VLockGuard< QFile > > m_lockLog
std::shared_ptr< QTextStream > m_out
Additional Inherited Members
Protected Attributes inherited from VAbstractApplication
QUndoStack * undoStack
QWidget * mainWindow
mainWindow pointer to main window. Usefull if need create modal dialog. Without pointer to main window modality doesn't work.
VCommonSettings * settings
settings pointer to settings. Help hide constructor creation settings. Make make code more readable.
QPointer< QTranslator > qtTranslator
QPointer< QTranslator > qtxmlTranslator
QPointer< QTranslator > qtBaseTranslator
QPointer< QTranslator > appTranslator
QPointer< QTranslator > pmsTranslator
Detailed Description
The Application2D class reimplamentation QApplication class.
Definition at line 73 of file application_2d.h.
Constructor & Destructor Documentation
Application2D()
Application2D::Application2D (int & argc, char ** argv)
Application2D constructor.
Parameters
argc number arguments.
argv command line.
Definition at line 273 of file application_2d.cpp.
References APP_VERSION_STR, VCommandLine::Get(), VAbstractApplication::loadTranslations(), openSettings(), VCommandLine::Reset(), VAbstractApplication::undoStack, VER_COMPANYDOMAIN_STR, VER_COMPANYNAME_STR, and VER_INTERNALNAME_STR.
~Application2D()
Application2D::~Application2D () virtual
Definition at line 297 of file application_2d.cpp.
References m_trVars, and VCommandLine::Reset().
Member Function Documentation
beginLogging()
void Application2D::beginLogging () private
Definition at line 501 of file application_2d.cpp.
References logPath(), m_lockLog, m_out, noisyFailureMsgHandler(), and VlpCreateLock().
Referenced by startLogging().
clearOldLogs()
void Application2D::clearOldLogs () const private
Definition at line 526 of file application_2d.cpp.
References DAYS_TO_KEEP_LOGS, VLockGuard< Guarded >::GetProtected(), and logDirPath().
Referenced by startLogging().
commandLine()
const VCommandLinePtr Application2D::commandLine () const
Definition at line 723 of file application_2d.cpp.
References VCommandLine::instance.
createLogDir()
bool Application2D::createLogDir () const private
Definition at line 490 of file application_2d.cpp.
References logDirPath().
Referenced by startLogging().
event()
bool Application2D::event (QEvent * e) protected virtual
Definition at line 651 of file application_2d.cpp.
References MainWindow::LoadPattern(), and VAbstractApplication::mainWindow.
Referenced by notify().
getAutoSaveTimer()
QTimer * Application2D::getAutoSaveTimer () const inline
Definition at line 126 of file application_2d.h.
References m_autoSaveTimer.
initOptions()
void Application2D::initOptions ()
Definition at line 568 of file application_2d.cpp.
References APP_VERSION_STR, buildCompatibilityString(), VCommonSettings::getDefaultIndividualSizePath(), VCommonSettings::getDefaultLabelTemplatePath(), VCommonSettings::getDefaultMultisizePath(), VCommonSettings::getDefaultTemplatePath(), isGUIMode(), VAbstractApplication::loadTranslations(), openSettings(), Seamly2DSettings(), VAbstractApplication::settings, and startLogging().
Referenced by main().
initTranslateVariables()
void Application2D::initTranslateVariables () protected virtual
Implements VAbstractApplication.
Definition at line 642 of file application_2d.cpp.
References m_trVars.
isAppInGUIMode()
bool Application2D::isAppInGUIMode () const virtual
isAppInGUIMode little hack that allow to have access to application state from VAbstractApplication class.
Implements VAbstractApplication.
Definition at line 717 of file application_2d.cpp.
References isGUIMode().
isGUIMode()
bool Application2D::isGUIMode () static
Definition at line 708 of file application_2d.cpp.
References VCommandLine::instance.
Referenced by MainWindow::changeDraftBlockGlobally(), MainWindow::checkPathToMeasurements(), ExportLayoutDialog::ExportLayoutDialog(), MainWindow::fullParseFile(), MainWindow::IgnoreLocking(), initOptions(), isAppInGUIMode(), MainWindowsNoGUI::LayoutSettings(), VPattern::LiteParseTree(), MainWindow::loadMeasurements(), MainWindow::LoadPattern(), main(), noisyFailureMsgHandler(), MainWindow::openMeasurementFile(), MainWindow::processCommandLine(), MainWindow::setCurrentFile(), MainWindow::setHeight(), MainWindow::setSize(), and MainWindow::updateMeasurements().
logDirPath()
QString Application2D::logDirPath () const private
Definition at line 470 of file application_2d.cpp.
Referenced by clearOldLogs(), createLogDir(), and logPath().
logFile()
QTextStream * Application2D::logFile ()
Definition at line 630 of file application_2d.cpp.
References m_out.
logPath()
QString Application2D::logPath () const private
Definition at line 484 of file application_2d.cpp.
References logDirPath().
Referenced by beginLogging().
notify()
bool Application2D::notify (QObject * receiver, QEvent * event) virtual
notify Reimplemented from QApplication::notify().
Parameters
receiver receiver.
event event.
Returns
value that is returned from the receiver's event handler.
Definition at line 351 of file application_2d.cpp.
References VExceptionObjectError::DetailedInformation(), VExceptionObjectError::ErrorMessage(), event(), V_EX_DATAERR, V_EX_SOFTWARE, and VException::what().
openSettings()
void Application2D::openSettings () virtual
openSettings get acsses to application settings.
Because we can create object in constructor we open file separately.
Implements VAbstractApplication.
Definition at line 694 of file application_2d.cpp.
References VAbstractApplication::settings.
Referenced by Application2D(), and initOptions().
pointNameLanguages()
QStringList Application2D::pointNameLanguages () static
Definition at line 606 of file application_2d.cpp.
Referenced by VPattern::GetCurrentAlphabet(), and PreferencesConfigurationPage::PreferencesConfigurationPage().
Seamly2DSettings()
VSettings * Application2D::Seamly2DSettings ()
Definition at line 701 of file application_2d.cpp.
References SCASSERT, and VAbstractApplication::settings.
Referenced by initOptions().
seamlyMeFilePath()
QString Application2D::seamlyMeFilePath () const
Definition at line 417 of file application_2d.cpp.
setAutoSaveTimer()
void Application2D::setAutoSaveTimer (QTimer * value) inline
Definition at line 132 of file application_2d.h.
References m_autoSaveTimer.
startLogging()
void Application2D::startLogging ()
Definition at line 620 of file application_2d.cpp.
References beginLogging(), clearOldLogs(), and createLogDir().
Referenced by initOptions().
startNewSeamly2D()
void Application2D::startNewSeamly2D (const QString & fileName = QString()) static
startNewSeamly2D start Seamly2D in new process, send path to pattern file in argument.
Parameters
fileName path to pattern file.
Definition at line 310 of file application_2d.cpp.
Referenced by MainWindow::startNewSeamly2D().
translateVariables()
const VTranslateVars * Application2D::translateVariables () virtual
Implements VAbstractApplication.
Definition at line 636 of file application_2d.cpp.
References m_trVars.
Member Data Documentation
m_autoSaveTimer
QTimer* Application2D::m_autoSaveTimer private
Definition at line 109 of file application_2d.h.
Referenced by getAutoSaveTimer(), and setAutoSaveTimer().
m_lockLog
std::shared_ptr<VLockGuard<QFile> > Application2D::m_lockLog private
Definition at line 111 of file application_2d.h.
Referenced by beginLogging().
m_out
std::shared_ptr<QTextStream> Application2D::m_out private
Definition at line 112 of file application_2d.h.
Referenced by beginLogging(), and logFile().
m_trVars
VTranslateVars* Application2D::m_trVars private
Definition at line 108 of file application_2d.h.
Referenced by initTranslateVariables(), translateVariables(), and ~Application2D().
The documentation for this class was generated from the following files:
src/app/seamly2d/core/application_2d.h
src/app/seamly2d/core/application_2d.cpp