Seamly2D: XPathMatcherStack Class Reference
XPathMatcherStack Class Reference
#include <XPathMatcherStack.hpp>
Public Member Functions
XPathMatcherStack (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XPathMatcherStack ()
XPathMatcher * getMatcherAt (const XMLSize_t index) const
XMLSize_t getMatcherCount () const
XMLSize_t size () const
void addMatcher (XPathMatcher *const matcher)
void pushContext ()
void popContext ()
void clear ()
XPathMatcherStack (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XPathMatcherStack ()
XPathMatcher * getMatcherAt (const XMLSize_t index) const
XMLSize_t getMatcherCount () const
XMLSize_t size () const
void addMatcher (XPathMatcher *const matcher)
void pushContext ()
void popContext ()
void clear ()
XPathMatcherStack (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XPathMatcherStack ()
XPathMatcher * getMatcherAt (const XMLSize_t index) const
XMLSize_t getMatcherCount () const
XMLSize_t size () const
void addMatcher (XPathMatcher *const matcher)
void pushContext ()
void popContext ()
void clear ()
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
void cleanUp ()
XPathMatcherStack (const XPathMatcherStack &other)
XPathMatcherStack & operator= (const XPathMatcherStack &other)
void cleanUp ()
XPathMatcherStack (const XPathMatcherStack &other)
XPathMatcherStack & operator= (const XPathMatcherStack &other)
void cleanUp ()
XPathMatcherStack (const XPathMatcherStack &other)
XPathMatcherStack & operator= (const XPathMatcherStack &other)
Private Attributes
unsigned int fMatchersCount
ValueStackOf< int > * fContextStack
RefVectorOf< XPathMatcher > * fMatchers
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 33 of file XPathMatcherStack.hpp.
Constructor & Destructor Documentation
XPathMatcherStack() [1/6]
XPathMatcherStack::XPathMatcherStack (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XPathMatcherStack() [1/3]
XPathMatcherStack::~XPathMatcherStack ()
XPathMatcherStack() [2/6]
XPathMatcherStack::XPathMatcherStack (const XPathMatcherStack & other) private
XPathMatcherStack() [3/6]
XPathMatcherStack::XPathMatcherStack (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XPathMatcherStack() [2/3]
XPathMatcherStack::~XPathMatcherStack ()
XPathMatcherStack() [4/6]
XPathMatcherStack::XPathMatcherStack (const XPathMatcherStack & other) private
XPathMatcherStack() [5/6]
XPathMatcherStack::XPathMatcherStack (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XPathMatcherStack() [3/3]
XPathMatcherStack::~XPathMatcherStack ()
XPathMatcherStack() [6/6]
XPathMatcherStack::XPathMatcherStack (const XPathMatcherStack & other) private
Member Function Documentation
addMatcher() [1/3]
void XPathMatcherStack::addMatcher (XPathMatcher *const matcher) inline
Definition at line 120 of file XPathMatcherStack.hpp.
References BaseRefVectorOf< TElem >::addElement(), fMatchers, fMatchersCount, BaseRefVectorOf< TElem >::setElementAt(), and BaseRefVectorOf< TElem >::size().
addMatcher() [2/3]
void XPathMatcherStack::addMatcher (XPathMatcher *const matcher)
addMatcher() [3/3]
void XPathMatcherStack::addMatcher (XPathMatcher *const matcher)
cleanUp() [1/3]
void XPathMatcherStack::cleanUp () private
cleanUp() [2/3]
void XPathMatcherStack::cleanUp () private
cleanUp() [3/3]
void XPathMatcherStack::cleanUp () private
clear() [1/3]
void XPathMatcherStack::clear ()
clear() [2/3]
void XPathMatcherStack::clear ()
clear() [3/3]
void XPathMatcherStack::clear ()
getMatcherAt() [1/3]
XPathMatcher * XPathMatcherStack::getMatcherAt (const XMLSize_t index) const inline
Definition at line 99 of file XPathMatcherStack.hpp.
References BaseRefVectorOf< TElem >::elementAt(), and fMatchers.
getMatcherAt() [2/3]
XPathMatcher* XPathMatcherStack::getMatcherAt (const XMLSize_t index) const
getMatcherAt() [3/3]
XPathMatcher* XPathMatcherStack::getMatcherAt (const XMLSize_t index) const
getMatcherCount() [1/3]
XMLSize_t XPathMatcherStack::getMatcherCount () const inline
Definition at line 93 of file XPathMatcherStack.hpp.
References fMatchersCount.
Referenced by IdentityConstraintHandler::getMatcherCount().
getMatcherCount() [2/3]
XMLSize_t XPathMatcherStack::getMatcherCount () const
getMatcherCount() [3/3]
XMLSize_t XPathMatcherStack::getMatcherCount () const
operator=() [1/3]
XPathMatcherStack& XPathMatcherStack::operator= (const XPathMatcherStack & other) private
operator=() [2/3]
XPathMatcherStack& XPathMatcherStack::operator= (const XPathMatcherStack & other) private
operator=() [3/3]
XPathMatcherStack& XPathMatcherStack::operator= (const XPathMatcherStack & other) private
popContext() [1/3]
void XPathMatcherStack::popContext () inline
Definition at line 112 of file XPathMatcherStack.hpp.
References fContextStack, fMatchersCount, and ValueStackOf< TElem >::pop().
popContext() [2/3]
void XPathMatcherStack::popContext ()
popContext() [3/3]
void XPathMatcherStack::popContext ()
pushContext() [1/3]
void XPathMatcherStack::pushContext () inline
Definition at line 107 of file XPathMatcherStack.hpp.
References fContextStack, fMatchersCount, and ValueStackOf< TElem >::push().
pushContext() [2/3]
void XPathMatcherStack::pushContext ()
pushContext() [3/3]
void XPathMatcherStack::pushContext ()
size() [1/3]
XMLSize_t XPathMatcherStack::size () const inline
Definition at line 88 of file XPathMatcherStack.hpp.
References fContextStack, and ValueStackOf< TElem >::size().
size() [2/3]
XMLSize_t XPathMatcherStack::size () const
size() [3/3]
XMLSize_t XPathMatcherStack::size () const
Member Data Documentation
fContextStack
ValueStackOf< int > * XPathMatcherStack::fContextStack private
Definition at line 81 of file XPathMatcherStack.hpp.
Referenced by popContext(), pushContext(), and size().
fMatchers
RefVectorOf< XPathMatcher > * XPathMatcherStack::fMatchers private
Definition at line 82 of file XPathMatcherStack.hpp.
Referenced by addMatcher(), and getMatcherAt().
fMatchersCount
unsigned int XPathMatcherStack::fMatchersCount private
Definition at line 80 of file XPathMatcherStack.hpp.
Referenced by addMatcher(), getMatcherCount(), popContext(), and pushContext().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/identity/XPathMatcherStack.hpp