Seamly2D: src/libs/vmisc/projectversion.h File Reference
projectversion.h File Reference
Macros
#define APP_VERSION ((MAJOR_VERSION << 16) + (MINOR_VERSION << 8) + DEBUG_VERSION)
#define VER_FILEVERSION 0,6,0,1
#define VER_FILEVERSION_STR "0.6.0.1"
#define V_PRERELEASE
#define VER_PRODUCTVERSION VER_FILEVERSION
#define VER_PRODUCTVERSION_STR VER_FILEVERSION_STR
#define VER_INTERNALNAME_2D_STR "Seamly2D"
#define VER_COMPANYNAME_STR "Seamly2DTeam"
#define VER_LEGALCOPYRIGHT_STR "Copyright © 2014-2022 Seamly2D Team"
#define VER_LEGALTRADEMARKS1_STR "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_COMPANYDOMAIN_STR "https://seamly.io"
Functions
QString compilerString ()
QString buildCompatibilityString ()
Variables
const int MAJOR_VERSION
const int MINOR_VERSION
const int DEBUG_VERSION
const int SUPER_MINOR__VERSION
const QString APP_VERSION_STR
Macro Definition Documentation
APP_VERSION
#define APP_VERSION ((MAJOR_VERSION << 16) + (MINOR_VERSION << 8) + DEBUG_VERSION)
Definition at line 67 of file projectversion.h.
V_PRERELEASE
#define V_PRERELEASE
Definition at line 74 of file projectversion.h.
VER_COMPANYDOMAIN_STR
#define VER_COMPANYDOMAIN_STR "https://seamly.io"
Definition at line 84 of file projectversion.h.
VER_COMPANYNAME_STR
#define VER_COMPANYNAME_STR "Seamly2DTeam"
Definition at line 80 of file projectversion.h.
VER_FILEVERSION
#define VER_FILEVERSION 0,6,0,1
Definition at line 70 of file projectversion.h.
VER_FILEVERSION_STR
#define VER_FILEVERSION_STR "0.6.0.1"
Definition at line 71 of file projectversion.h.
VER_INTERNALNAME_2D_STR
#define VER_INTERNALNAME_2D_STR "Seamly2D"
Definition at line 79 of file projectversion.h.
VER_LEGALCOPYRIGHT_STR
#define VER_LEGALCOPYRIGHT_STR "Copyright © 2014-2022 Seamly2D Team"
Definition at line 81 of file projectversion.h.
VER_LEGALTRADEMARKS1_STR
#define VER_LEGALTRADEMARKS1_STR "All Rights Reserved"
Definition at line 82 of file projectversion.h.
VER_LEGALTRADEMARKS2_STR
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
Definition at line 83 of file projectversion.h.
VER_PRODUCTVERSION
#define VER_PRODUCTVERSION VER_FILEVERSION
Definition at line 76 of file projectversion.h.
VER_PRODUCTVERSION_STR
#define VER_PRODUCTVERSION_STR VER_FILEVERSION_STR
Definition at line 77 of file projectversion.h.
Function Documentation
buildCompatibilityString()
QString buildCompatibilityString ()
Definition at line 132 of file projectversion.cpp.
References compilerString().
Referenced by DialogAboutApp::DialogAboutApp(), VApplication::InitOptions(), MApplication::InitOptions(), and DialogAboutSeamlyMe::RetranslateUi().
compilerString()
QString compilerString ()
Definition at line 77 of file projectversion.cpp.
Referenced by buildCompatibilityString().
Variable Documentation
APP_VERSION_STR
const QString APP_VERSION_STR extern
Referenced by DialogAboutApp::DialogAboutApp(), anonymous_namespace{vpattern.cpp}::FileComment(), anonymous_namespace{measurements.cpp}::FileComment(), VApplication::InitOptions(), MApplication::InitOptions(), MApplication::MApplication(), DialogAboutSeamlyMe::RetranslateUi(), and VApplication::VApplication().
DEBUG_VERSION
const int DEBUG_VERSION extern
MAJOR_VERSION
const int MAJOR_VERSION extern
MINOR_VERSION
const int MINOR_VERSION extern
SUPER_MINOR__VERSION
const int SUPER_MINOR__VERSION extern