Seamly2D: DialogTool Class Reference
DialogTool Class Reference
The DialogTool class parent for all dialog of tools.
#include <dialogtool.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Signals
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Public Member Functions
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Static Public Member Functions
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
virtual void CheckState ()
CheckState enable, when all is correct, or disable, when something wrong, button ok.
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
virtual void ShowVisualization ()
virtual void SaveData ()
SaveData Put dialog data in local variables.
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Static Protected Member Functions
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Private Member Functions
void FillList (QComboBox *box, const QMap< QString, quint32 > &list) const
FillList fill combobox list.
template<typename T >
void PrepareList (QMap< QString, quint32 > &list, quint32 id) const
bool IsSpline (const QSharedPointer< VGObject > &obj) const
bool IsSplinePath (const QSharedPointer< VGObject > &obj) const
template<typename GObject >
void FillCombo (QComboBox *box, GOType gType, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
Detailed Description
The DialogTool class parent for all dialog of tools.
Definition at line 106 of file dialogtool.h.
Constructor & Destructor Documentation
DialogTool()
DialogTool::DialogTool (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
DialogTool create dialog.
Parameters
data container with data
parent parent widget
Definition at line 133 of file dialogtool.cpp.
References data, EvalFormula(), SCASSERT, and timerFormula.
~DialogTool()
DialogTool::~DialogTool () virtual
Definition at line 163 of file dialogtool.cpp.
References ToolTip(), and vis.
Member Function Documentation
AddVisualization()
template<typename T > void DialogTool::AddVisualization inline protected
Definition at line 407 of file dialogtool.h.
References prepare, qApp, SCASSERT, Show, and vis.
ArrowDown
void DialogTool::ArrowDown () slot
ArrowDown set angle value 270 degree.
Definition at line 1204 of file dialogtool.cpp.
References SCASSERT, and spinBoxAngle.
ArrowLeft
void DialogTool::ArrowLeft () slot
ArrowLeft set angle value 180 degree.
Definition at line 1214 of file dialogtool.cpp.
References SCASSERT, and spinBoxAngle.
ArrowLeftDown
void DialogTool::ArrowLeftDown () slot
ArrowLeftDown set angle value 225 degree.
Definition at line 1244 of file dialogtool.cpp.
References SCASSERT, and spinBoxAngle.
ArrowLeftUp
void DialogTool::ArrowLeftUp () slot
ArrowLeftUp set angle value 135 degree.
Definition at line 1234 of file dialogtool.cpp.
References SCASSERT, and spinBoxAngle.
ArrowRight
void DialogTool::ArrowRight () slot
ArrowRight set angle value 0 degree.
Definition at line 1224 of file dialogtool.cpp.
References SCASSERT, and spinBoxAngle.
ArrowRightDown
void DialogTool::ArrowRightDown () slot
ArrowRightDown set angle value 315 degree.
Definition at line 1264 of file dialogtool.cpp.
References SCASSERT, and spinBoxAngle.
ArrowRightUp
void DialogTool::ArrowRightUp () slot
ArrowRightUp set angle value 45 degree.
Definition at line 1254 of file dialogtool.cpp.
References SCASSERT, and spinBoxAngle.
ArrowUp
void DialogTool::ArrowUp () slot
ArrowUp set angle value 90 degree.
Definition at line 1194 of file dialogtool.cpp.
References SCASSERT, and spinBoxAngle.
Build()
void DialogTool::Build (const Tool & type) virtual
Reimplemented in DialogAlongLine.
Definition at line 1364 of file dialogtool.cpp.
ChangeColor()
void DialogTool::ChangeColor (QWidget * widget, const QColor & color) protected
Definition at line 1134 of file dialogtool.cpp.
References SCASSERT.
Referenced by DialogPointOfIntersectionArcs::ArcChanged(), DialogArc::CheckAngles(), DialogEllipticalArc::CheckAngles(), DialogTrueDarts::CheckName(), AnchorPointDialog::CheckPieces(), AnchorPointDialog::CheckPoint(), DialogCubicBezierPath::currentPointChanged(), DialogSplinePath::currentPointChanged(), DialogPointOfIntersectionCurves::CurveChanged(), DialogSplinePath::DataPoint(), Eval(), IntersectCirclesDialog::EvalCircle1Radius(), IntersectCirclesDialog::EvalCircle2Radius(), IntersectCircleTangentDialog::EvalCircleRadius(), DialogSpline::EvalLength1(), DialogSplinePath::EvalLength1(), DialogSpline::EvalLength2(), DialogSplinePath::EvalLength2(), DialogArc::EvalRadius(), DialogEllipticalArc::EvalRadiuses(), PatternPieceDialog::grainlineAnchorChanged(), DialogArcWithLength::Length(), DialogInternalPath::NameChanged(), NamePointChanged(), PatternPieceDialog::patternLabelAnchorChanged(), PatternPieceDialog::PatternPieceDialog(), PatternPieceDialog::pieceLabelAnchorChanged(), PatternPieceDialog::pieceNameChanged(), DialogAlongLine::PointChanged(), DialogMirrorByAxis::pointChanged(), DialogMirrorByLine::pointChanged(), DialogRotation::pointChanged(), IntersectCirclesDialog::PointChanged(), IntersectCircleTangentDialog::PointChanged(), PointIntersectXYDialog::pointChanged(), DialogArc::pointNameChanged(), DialogArcWithLength::pointNameChanged(), DialogEllipticalArc::pointNameChanged(), DialogBisector::PointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogHeight::PointNameChanged(), DialogLine::PointNameChanged(), DialogLineIntersect::PointNameChanged(), DialogLineIntersectAxis::PointNameChanged(), DialogNormal::PointNameChanged(), DialogPointOfContact::PointNameChanged(), DialogShoulderPoint::PointNameChanged(), DialogSpline::PointNameChanged(), DialogTriangle::PointNameChanged(), DialogTrueDarts::PointNameChanged(), DialogArcWithLength::Radius(), DialogMirrorByAxis::suffixChanged(), DialogMirrorByLine::suffixChanged(), DialogMove::suffixChanged(), DialogRotation::suffixChanged(), PatternPieceDialog::updateGrainlineValues(), PatternPieceDialog::updatePatternLabelValues(), PatternPieceDialog::updatePieceLabelValues(), ValFormulaChanged(), and InsertNodesDialog::validatePieces().
ChangeCurrentData()
void DialogTool::ChangeCurrentData (QComboBox * box, const QVariant & value) const protected
ChangeCurrentData select item in combobox by id.
Parameters
box combobox
value id of item
Definition at line 419 of file dialogtool.cpp.
References SCASSERT.
Referenced by DialogCubicBezierPath::DataPoint(), DialogSplinePath::DataPoint(), DialogArc::setCenter(), DialogArcWithLength::SetCenter(), DialogEllipticalArc::SetCenter(), EditGroupDialog::setColor(), setCurrentArcId(), setCurrentCurveId(), setCurrentPointId(), setCurrentSplineId(), setCurrentSplinePathId(), DialogMirrorByLine::setFirstLinePointId(), DialogAlongLine::setLineColor(), DialogArc::setLineColor(), DialogArcWithLength::setLineColor(), DialogBisector::setLineColor(), DialogCubicBezier::setLineColor(), DialogCubicBezierPath::setLineColor(), DialogCurveIntersectAxis::setLineColor(), DialogEllipticalArc::setLineColor(), DialogEndLine::setLineColor(), DialogHeight::setLineColor(), DialogLine::setLineColor(), DialogLineIntersectAxis::setLineColor(), DialogNormal::setLineColor(), DialogShoulderPoint::setLineColor(), DialogSpline::setLineColor(), DialogSplinePath::setLineColor(), PointIntersectXYDialog::setLineColor(), EditGroupDialog::setLineType(), DialogAlongLine::setLineType(), DialogBisector::setLineType(), DialogCurveIntersectAxis::setLineType(), DialogEndLine::setLineType(), DialogHeight::setLineType(), DialogLine::setLineType(), DialogLineIntersectAxis::setLineType(), DialogNormal::setLineType(), DialogShoulderPoint::setLineType(), PointIntersectXYDialog::setLineType(), DialogAlongLine::setLineWeight(), DialogArc::setLineWeight(), DialogArcWithLength::setLineWeight(), DialogBisector::setLineWeight(), DialogCubicBezier::setLineWeight(), DialogCubicBezierPath::setLineWeight(), DialogCurveIntersectAxis::setLineWeight(), DialogEllipticalArc::setLineWeight(), DialogEndLine::setLineWeight(), DialogHeight::setLineWeight(), DialogLine::setLineWeight(), DialogLineIntersectAxis::setLineWeight(), DialogNormal::setLineWeight(), DialogShoulderPoint::setLineWeight(), DialogSpline::setLineWeight(), DialogSplinePath::setLineWeight(), PointIntersectXYDialog::setLineWeight(), EditGroupDialog::setLineWeight(), DialogMove::setOriginPointId(), DialogRotation::setOriginPointId(), DialogMirrorByAxis::setOriginPointId(), DialogArc::setPenStyle(), DialogArcWithLength::setPenStyle(), DialogCubicBezier::setPenStyle(), DialogCubicBezierPath::setPenStyle(), DialogEllipticalArc::setPenStyle(), DialogSpline::setPenStyle(), DialogSplinePath::setPenStyle(), DialogInternalPath::SetPenType(), PatternPieceDialog::SetPiece(), PatternPieceDialog::setPieceFill(), and DialogMirrorByLine::setSecondLinePointId().
CheckState()
void DialogTool::CheckState () protected virtual
CheckState enable, when all is correct, or disable, when something wrong, button ok.
Reimplemented in PatternPieceDialog, DialogInternalPath, IntersectCircleTangentDialog, IntersectCirclesDialog, DialogTrueDarts, DialogSplinePath, DialogSpline, DialogRotation, DialogPointOfIntersectionCurves, DialogMove, DialogMirrorByLine, DialogMirrorByAxis, DialogLineIntersect, DialogEllipticalArc, DialogArcWithLength, DialogArc, AnchorPointDialog, and EditFormulaDialog.
Definition at line 1075 of file dialogtool.cpp.
References apply_Button, flagError, flagFormula, flagName, ok_Button, and SCASSERT.
Referenced by DialogPointOfIntersectionArcs::ArcChanged(), DialogCubicBezierPath::currentPointChanged(), DialogAlongLine::DialogAlongLine(), DialogBisector::DialogBisector(), DialogCubicBezier::DialogCubicBezier(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogCutArc::DialogCutArc(), DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), DialogEndLine::DialogEndLine(), DialogHeight::DialogHeight(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogNormal::DialogNormal(), DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfContact::DialogPointOfContact(), DialogPointOfIntersectionArcs::DialogPointOfIntersectionArcs(), DialogShoulderPoint::DialogShoulderPoint(), DialogSinglePoint::DialogSinglePoint(), DialogTriangle::DialogTriangle(), EditGroupDialog::EditGroupDialog(), Eval(), EditGroupDialog::NameChanged(), EditGroupDialog::nameChanged(), NamePointChanged(), DialogAlongLine::PointChanged(), PointIntersectXYDialog::pointChanged(), PointIntersectXYDialog::PointIntersectXYDialog(), DialogBisector::PointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogHeight::PointNameChanged(), DialogLine::PointNameChanged(), DialogLineIntersectAxis::PointNameChanged(), DialogNormal::PointNameChanged(), DialogPointOfContact::PointNameChanged(), DialogShoulderPoint::PointNameChanged(), DialogTriangle::PointNameChanged(), and ValFormulaChanged().
ChosenObject
void DialogTool::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
Parameters
id id of point or detail
type type of object
Definition at line 1092 of file dialogtool.cpp.
Referenced by MainWindow::SetToolButton().
closeEvent()
void DialogTool::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented in PatternPieceDialog, DialogInternalPath, IntersectCircleTangentDialog, IntersectCirclesDialog, DialogSplinePath, DialogSpline, DialogShoulderPoint, DialogRotation, DialogPointOfContact, DialogNormal, DialogMove, DialogLineIntersectAxis, DialogEndLine, DialogEllipticalArc, DialogCutSplinePath, DialogCutSpline, DialogCutArc, DialogCurveIntersectAxis, DialogBisector, DialogArcWithLength, DialogArc, DialogAlongLine, EditFormulaDialog, HistoryDialog, and DialogVariables.
Definition at line 192 of file dialogtool.cpp.
References DialogRejected().
Referenced by HistoryDialog::closeEvent(), EditFormulaDialog::closeEvent(), DialogAlongLine::closeEvent(), DialogArc::closeEvent(), DialogArcWithLength::closeEvent(), DialogBisector::closeEvent(), DialogCurveIntersectAxis::closeEvent(), DialogCutArc::closeEvent(), DialogCutSpline::closeEvent(), DialogCutSplinePath::closeEvent(), DialogEllipticalArc::closeEvent(), DialogEndLine::closeEvent(), DialogLineIntersectAxis::closeEvent(), DialogMove::closeEvent(), DialogNormal::closeEvent(), DialogPointOfContact::closeEvent(), DialogRotation::closeEvent(), DialogShoulderPoint::closeEvent(), DialogSpline::closeEvent(), DialogSplinePath::closeEvent(), IntersectCirclesDialog::closeEvent(), IntersectCircleTangentDialog::closeEvent(), DialogInternalPath::closeEvent(), and PatternPieceDialog::closeEvent().
DeployFormula()
void DialogTool::DeployFormula (QPlainTextEdit * formula, QPushButton * buttonGrowLength, int formulaBaseHeight) protected
Definition at line 992 of file dialogtool.cpp.
References DIALOG_MAX_FORMULA_HEIGHT, DIALOG_MIN_WIDTH, and SCASSERT.
Referenced by DialogSpline::DeployAngle1TextEdit(), DialogSplinePath::DeployAngle1TextEdit(), DialogSpline::DeployAngle2TextEdit(), DialogSplinePath::DeployAngle2TextEdit(), DialogCurveIntersectAxis::DeployAngleTextEdit(), DialogEndLine::DeployAngleTextEdit(), DialogLineIntersectAxis::DeployAngleTextEdit(), IntersectCircleTangentDialog::DeployCircleRadiusTextEdit(), DialogArc::DeployF1TextEdit(), DialogArcWithLength::DeployF1TextEdit(), DialogEllipticalArc::DeployF1TextEdit(), DialogArc::DeployF2TextEdit(), DialogEllipticalArc::DeployF2TextEdit(), DialogAlongLine::DeployFormulaTextEdit(), DialogArc::DeployFormulaTextEdit(), DialogBisector::DeployFormulaTextEdit(), DialogCutArc::DeployFormulaTextEdit(), DialogCutSpline::DeployFormulaTextEdit(), DialogCutSplinePath::DeployFormulaTextEdit(), DialogEndLine::DeployFormulaTextEdit(), DialogNormal::DeployFormulaTextEdit(), DialogPointOfContact::DeployFormulaTextEdit(), DialogShoulderPoint::DeployFormulaTextEdit(), DialogSpline::DeployLength1TextEdit(), DialogSplinePath::DeployLength1TextEdit(), DialogSpline::DeployLength2TextEdit(), DialogSplinePath::DeployLength2TextEdit(), DialogArcWithLength::DeployLengthTextEdit(), DialogEllipticalArc::DeployRadius1TextEdit(), DialogEllipticalArc::DeployRadius2TextEdit(), DialogArcWithLength::DeployRadiusTextEdit(), DialogEllipticalArc::DeployRotationAngleTextEdit(), DialogInternalPath::expandWidthAfterFormulaTextEdit(), DialogInternalPath::expandWidthBeforeFormulaTextEdit(), and DialogInternalPath::expandWidthFormulaTextEdit().
DialogAccepted
void DialogTool::DialogAccepted () virtual slot
DialogAccepted save data and emit signal about closed dialog.
Definition at line 1146 of file dialogtool.cpp.
References DialogClosed(), and SaveData().
Referenced by DialogCubicBezier::ChosenObject(), DialogHeight::ChosenObject(), DialogLine::ChosenObject(), DialogLineIntersect::ChosenObject(), DialogPointFromArcAndTangent::ChosenObject(), DialogPointOfIntersectionArcs::ChosenObject(), DialogPointOfIntersectionCurves::ChosenObject(), DialogTriangle::ChosenObject(), DialogTrueDarts::ChosenObject(), PointIntersectXYDialog::ChosenObject(), initializeOkCancel(), DialogCubicBezierPath::ShowDialog(), DialogCurveIntersectAxis::ShowDialog(), DialogLineIntersectAxis::ShowDialog(), DialogSpline::ShowDialog(), and DialogSplinePath::ShowDialog().
DialogApplied
void DialogTool::DialogApplied () signal
DialogApplied emit signal dialog apply changes.
Referenced by VDrawTool::ContextMenu(), DialogApply(), PatternPieceTool::editPieceProperties(), and MainWindow::SetToolButtonWithApply().
DialogApply
void DialogTool::DialogApply () virtual slot
DialogApply save data and emit signal DialogApplied.
Definition at line 1153 of file dialogtool.cpp.
References DialogApplied(), and SaveData().
Referenced by initializeOkCancelApply().
DialogClosed
void DialogTool::DialogClosed (int result) signal
DialogClosed signal dialog closed.
Parameters
result keep result
Referenced by DialogVariables::closeEvent(), VDrawTool::ContextMenu(), DialogAccepted(), HistoryDialog::DialogAccepted(), EditFormulaDialog::DialogAccepted(), DialogRejected(), EditFormulaDialog::DialogRejected(), PatternPieceTool::editPieceProperties(), MainWindow::SetToolButton(), PatternPieceDialog::showCustomSAContextMenu(), and PatternPieceDialog::showInternalPathsContextMenu().
DialogRejected
void DialogTool::DialogRejected () virtual slot
DialogRejected emit signal dialog rejected.
Definition at line 1163 of file dialogtool.cpp.
References DialogClosed().
Referenced by closeEvent(), initializeOkCancel(), and keyPressEvent().
DialogWarningIcon()
QString DialogTool::DialogWarningIcon () static protected
Definition at line 604 of file dialogtool.cpp.
Referenced by PatternPieceDialog::isMainPathValid(), and DialogInternalPath::PathIsValid().
DNumber()
quint32 DialogTool::DNumber (const QString & baseName) const protected
Definition at line 476 of file dialogtool.cpp.
References data, and VContainer::IsUnique().
Referenced by DialogCubicBezierPath::currentPointChanged(), DialogSplinePath::currentPointChanged(), DialogArc::pointNameChanged(), DialogArcWithLength::pointNameChanged(), DialogEllipticalArc::pointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogSpline::PointNameChanged(), DialogCubicBezierPath::ShowDialog(), DialogSpline::ShowDialog(), and DialogSplinePath::ShowDialog().
doublePointsExist()
bool DialogTool::doublePointsExist (QListWidget * listWidget) static protected
Definition at line 565 of file dialogtool.cpp.
References FindNotExcludedNodeDown(), anonymous_namespace{dialogtool.cpp}::RowId(), and SCASSERT.
Referenced by PatternPieceDialog::isMainPathValid(), and DialogInternalPath::PathIsValid().
Eval()
qreal DialogTool::Eval (const QString & text, bool & flag, QLabel * label, const QString & postfix, bool checkZero = true, bool checkLessThanZero = false) protected
Eval evaluate formula and show result.
Parameters
text expresion that we parse
flag flag state of eval formula
label label for signal error
postfix unit name
checkZero true - if formula can't be equal zero
Definition at line 805 of file dialogtool.cpp.
References ChangeColor(), CheckState(), data, VContainer::DataVariables(), qmu::QmuParserError::GetExpr(), qmu::QmuParserError::GetMsg(), labelEditFormula, okColor, qApp, SCASSERT, and ToolTip().
Referenced by DialogCurveIntersectAxis::EvalAngle(), DialogEndLine::EvalAngle(), DialogLineIntersectAxis::EvalAngle(), DialogSpline::EvalAngle1(), DialogSplinePath::EvalAngle1(), DialogSpline::EvalAngle2(), DialogSplinePath::EvalAngle2(), DialogEllipticalArc::EvalAngles(), IntersectCirclesDialog::EvalCircle1Radius(), IntersectCirclesDialog::EvalCircle2Radius(), IntersectCircleTangentDialog::EvalCircleRadius(), DialogArc::EvalF(), DialogArcWithLength::EvalF(), EvalFormula(), EditFormulaDialog::EvalFormula(), DialogSpline::EvalLength1(), DialogSplinePath::EvalLength1(), DialogSpline::EvalLength2(), DialogSplinePath::EvalLength2(), DialogArc::EvalRadius(), DialogEllipticalArc::EvalRadiuses(), DialogInternalPath::evaluateAfterWidth(), PatternPieceDialog::evaluateAfterWidth(), DialogMove::evaluateAngle(), DialogRotation::evaluateAngle(), DialogInternalPath::evaluateBeforeWidth(), PatternPieceDialog::evaluateBeforeWidth(), DialogInternalPath::evaluateDefaultWidth(), PatternPieceDialog::evaluateDefaultWidth(), DialogMove::evaluateLength(), DialogMove::evaluateRotation(), DialogArcWithLength::Length(), and DialogArcWithLength::Radius().
EvalFormula
void DialogTool::EvalFormula () virtual slot
EvalFormula evaluate formula.
Definition at line 1274 of file dialogtool.cpp.
References Eval(), flagFormula, labelResultCalculation, plainTextEditFormula, qApp, SCASSERT, and UnitsToStr().
Referenced by DialogTool().
eventFilter()
bool DialogTool::eventFilter (QObject * object, QEvent * event) protected virtual
Reimplemented in PatternPieceDialog, InsertNodesDialog, HistoryDialog, and DialogVariables.
Definition at line 441 of file dialogtool.cpp.
References qApp.
Referenced by DialogVariables::eventFilter(), HistoryDialog::eventFilter(), InsertNodesDialog::eventFilter(), and PatternPieceDialog::eventFilter().
FillCombo()
template<typename GObject > void DialogTool::FillCombo (QComboBox * box, GOType gType, FillComboBox rule = FillComboBox::Whole, const quint32 & ch1 = NULL_ID, const quint32 & ch2 = NULL_ID) const private
Definition at line 1397 of file dialogtool.cpp.
References Calculation, data, VContainer::DataGObjects(), FillList(), NoChildren, SCASSERT, and toolId.
FillComboBoxArcs()
void DialogTool::FillComboBoxArcs (QComboBox * box, FillComboBox rule = FillComboBox::Whole, const quint32 & ch1 = NULL_ID, const quint32 & ch2 = NULL_ID) const protected
Definition at line 248 of file dialogtool.cpp.
References Arc.
Referenced by DialogCutArc::DialogCutArc(), DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfIntersectionArcs::DialogPointOfIntersectionArcs(), and setCurrentArcId().
FillComboBoxCrossCirclesPoints()
void DialogTool::FillComboBoxCrossCirclesPoints (QComboBox * box) const protected
Definition at line 373 of file dialogtool.cpp.
References FirstPoint, SCASSERT, and SecondPoint.
Referenced by DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfIntersectionArcs::DialogPointOfIntersectionArcs(), IntersectCirclesDialog::IntersectCirclesDialog(), and IntersectCircleTangentDialog::IntersectCircleTangentDialog().
FillComboBoxCurves()
void DialogTool::FillComboBoxCurves (QComboBox * box) const protected
Definition at line 302 of file dialogtool.cpp.
References Arc, Calculation, CubicBezier, CubicBezierPath, data, VContainer::DataGObjects(), EllipticalArc, FillList(), SCASSERT, Spline, SplinePath, and toolId.
Referenced by DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogPointOfIntersectionCurves::DialogPointOfIntersectionCurves(), and setCurrentCurveId().
FillComboBoxHCrossCurvesPoint()
void DialogTool::FillComboBoxHCrossCurvesPoint (QComboBox * box) const protected
Definition at line 391 of file dialogtool.cpp.
References LeftmostPoint, RightmostPoint, and SCASSERT.
Referenced by DialogPointOfIntersectionCurves::DialogPointOfIntersectionCurves().
FillComboBoxLineColors()
void DialogTool::FillComboBoxLineColors (QComboBox * box) const protected
Definition at line 350 of file dialogtool.cpp.
References VAbstractTool::ColorsList(), and SCASSERT.
FillComboBoxPiecesList()
void DialogTool::FillComboBoxPiecesList (QComboBox * box, const QVector< quint32 > & list) protected
Definition at line 224 of file dialogtool.cpp.
References data, VAbstractPiece::GetName(), VContainer::GetPiece(), and SCASSERT.
Referenced by AnchorPointDialog::SetPiecesList(), InsertNodesDialog::SetPiecesList(), and DialogInternalPath::SetPiecesList().
FillComboBoxPoints()
void DialogTool::FillComboBoxPoints (QComboBox * box, FillComboBox rule = FillComboBox::Whole, const quint32 & ch1 = NULL_ID, const quint32 & ch2 = NULL_ID) const protected
FillComboBoxPoints fill comboBox list of points.
Parameters
box comboBox
Definition at line 242 of file dialogtool.cpp.
References Point.
Referenced by AnchorPointDialog::AnchorPointDialog(), DialogAlongLine::DialogAlongLine(), DialogArc::DialogArc(), DialogArcWithLength::DialogArcWithLength(), DialogBisector::DialogBisector(), DialogCubicBezier::DialogCubicBezier(), DialogCubicBezierPath::DialogCubicBezierPath(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogEllipticalArc::DialogEllipticalArc(), DialogEndLine::DialogEndLine(), DialogHeight::DialogHeight(), DialogLine::DialogLine(), DialogLineIntersect::DialogLineIntersect(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogMirrorByAxis::DialogMirrorByAxis(), DialogMirrorByLine::DialogMirrorByLine(), DialogMove::DialogMove(), DialogNormal::DialogNormal(), DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfContact::DialogPointOfContact(), DialogRotation::DialogRotation(), DialogShoulderPoint::DialogShoulderPoint(), DialogSpline::DialogSpline(), DialogSplinePath::DialogSplinePath(), DialogTriangle::DialogTriangle(), DialogTrueDarts::FillComboBoxs(), IntersectCirclesDialog::IntersectCirclesDialog(), IntersectCircleTangentDialog::IntersectCircleTangentDialog(), PointIntersectXYDialog::PointIntersectXYDialog(), and setCurrentPointId().
FillComboBoxSplines()
void DialogTool::FillComboBoxSplines (QComboBox * box) const protected
Definition at line 254 of file dialogtool.cpp.
References data, VContainer::DataGObjects(), FillList(), IsSpline(), SCASSERT, and toolId.
Referenced by DialogCutSpline::DialogCutSpline(), and setCurrentSplineId().
FillComboBoxSplinesPath()
void DialogTool::FillComboBoxSplinesPath (QComboBox * box) const protected
Definition at line 278 of file dialogtool.cpp.
References data, VContainer::DataGObjects(), FillList(), IsSplinePath(), SCASSERT, and toolId.
Referenced by DialogCutSplinePath::DialogCutSplinePath(), and setCurrentSplinePathId().
FillComboBoxTypeLine()
void DialogTool::FillComboBoxTypeLine (QComboBox * box, const QMap< QString, QIcon > & stylesPics) const protected
FillComboBoxTypeLine fill comboBox list of type lines.
Parameters
box comboBox
Definition at line 332 of file dialogtool.cpp.
References LineTypeSolidLine, and SCASSERT.
FillComboBoxVCrossCurvesPoint()
void DialogTool::FillComboBoxVCrossCurvesPoint (QComboBox * box) const protected
Definition at line 382 of file dialogtool.cpp.
References HighestPoint, LowestPoint, and SCASSERT.
Referenced by DialogPointOfIntersectionCurves::DialogPointOfIntersectionCurves().
FillList()
void DialogTool::FillList (QComboBox * box, const QMap< QString, quint32 > & list) const private
FillList fill combobox list.
Parameters
box combobox
list list with ids and names
Definition at line 1032 of file dialogtool.cpp.
References SCASSERT.
Referenced by FillCombo(), FillComboBoxCurves(), FillComboBoxSplines(), and FillComboBoxSplinesPath().
FindNotExcludedNodeDown()
int DialogTool::FindNotExcludedNodeDown (QListWidget * listWidget, int candidate) static protected
Definition at line 490 of file dialogtool.cpp.
References VPieceNode::isExcluded(), and SCASSERT.
Referenced by doublePointsExist(), and isFirstPointSameAsLast().
FindNotExcludedNodeUp()
int DialogTool::FindNotExcludedNodeUp (QListWidget * listWidget, int candidate) static protected
Definition at line 521 of file dialogtool.cpp.
References VPieceNode::isExcluded(), and SCASSERT.
Referenced by isFirstPointSameAsLast().
FormulaChanged
void DialogTool::FormulaChanged () slot
formula check formula
Definition at line 1172 of file dialogtool.cpp.
References flagFormula, qApp, timerFormula, UnitsToStr(), and ValFormulaChanged().
Referenced by DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), and EditFormulaDialog::EditFormulaDialog().
FormulaChangedPlainText
void DialogTool::FormulaChangedPlainText () slot
FormulaChangedPlainText check formula (plain text editor editor)
Definition at line 1181 of file dialogtool.cpp.
References flagFormula, qApp, timerFormula, UnitsToStr(), and ValFormulaChanged().
Referenced by DialogAlongLine::FormulaTextChanged(), DialogBisector::FormulaTextChanged(), DialogCutArc::FormulaTextChanged(), DialogEndLine::FormulaTextChanged(), DialogNormal::FormulaTextChanged(), DialogPointOfContact::FormulaTextChanged(), and DialogShoulderPoint::FormulaTextChanged().
GetAssociatedTool()
VAbstractTool * DialogTool::GetAssociatedTool () inline
Definition at line 354 of file dialogtool.h.
References associatedTool.
GetComboBoxCurrentData()
QString DialogTool::GetComboBoxCurrentData (const QComboBox * box, const QString & def) const protected
Definition at line 400 of file dialogtool.cpp.
References SCASSERT.
Referenced by EditGroupDialog::getColor(), DialogAlongLine::getLineColor(), DialogArc::getLineColor(), DialogArcWithLength::getLineColor(), DialogBisector::getLineColor(), DialogCubicBezier::getLineColor(), DialogCubicBezierPath::getLineColor(), DialogCurveIntersectAxis::getLineColor(), DialogEllipticalArc::getLineColor(), DialogEndLine::getLineColor(), DialogHeight::getLineColor(), DialogLine::getLineColor(), DialogLineIntersectAxis::getLineColor(), DialogNormal::getLineColor(), DialogShoulderPoint::getLineColor(), DialogSpline::getLineColor(), DialogSplinePath::getLineColor(), PointIntersectXYDialog::getLineColor(), DialogAlongLine::getLineType(), DialogBisector::getLineType(), DialogCurveIntersectAxis::getLineType(), DialogEndLine::getLineType(), DialogHeight::getLineType(), DialogLine::getLineType(), DialogLineIntersectAxis::getLineType(), DialogNormal::getLineType(), DialogShoulderPoint::getLineType(), EditGroupDialog::getLineType(), PointIntersectXYDialog::getLineType(), DialogAlongLine::getLineWeight(), DialogArc::getLineWeight(), DialogArcWithLength::getLineWeight(), DialogBisector::getLineWeight(), DialogCubicBezier::getLineWeight(), DialogCubicBezierPath::getLineWeight(), DialogCurveIntersectAxis::getLineWeight(), DialogEllipticalArc::getLineWeight(), DialogEndLine::getLineWeight(), DialogHeight::getLineWeight(), DialogLine::getLineWeight(), DialogLineIntersectAxis::getLineWeight(), DialogNormal::getLineWeight(), DialogShoulderPoint::getLineWeight(), DialogSpline::getLineWeight(), DialogSplinePath::getLineWeight(), EditGroupDialog::getLineWeight(), PointIntersectXYDialog::getLineWeight(), DialogArc::getPenStyle(), DialogArcWithLength::getPenStyle(), DialogCubicBezier::getPenStyle(), DialogCubicBezierPath::getPenStyle(), DialogEllipticalArc::getPenStyle(), DialogSpline::getPenStyle(), DialogSplinePath::getPenStyle(), DialogInternalPath::GetPenType(), and PatternPieceDialog::getPieceFill().
getCurrentCrossPoint()
template<typename T > T DialogTool::getCurrentCrossPoint (QComboBox * box) const inline protected
Definition at line 429 of file dialogtool.h.
getCurrentObjectId()
quint32 DialogTool::getCurrentObjectId (QComboBox * box) const protected
getCurrentPointId return current point id stored in combobox
Parameters
box combobox
Returns
id or 0 if combobox is empty
Definition at line 959 of file dialogtool.cpp.
References SCASSERT.
Referenced by DialogPointOfIntersectionArcs::ArcChanged(), DialogBisector::ChosenObject(), DialogCubicBezier::ChosenObject(), DialogHeight::ChosenObject(), DialogLine::ChosenObject(), DialogLineIntersect::ChosenObject(), DialogLineIntersectAxis::ChosenObject(), DialogMirrorByLine::ChosenObject(), DialogNormal::ChosenObject(), DialogPointOfContact::ChosenObject(), DialogPointOfIntersectionArcs::ChosenObject(), DialogPointOfIntersectionCurves::ChosenObject(), DialogShoulderPoint::ChosenObject(), DialogSpline::ChosenObject(), DialogTriangle::ChosenObject(), DialogTrueDarts::ChosenObject(), IntersectCirclesDialog::ChosenObject(), IntersectCircleTangentDialog::ChosenObject(), PointIntersectXYDialog::ChosenObject(), PatternPieceDialog::CreatePiece(), DialogPointOfIntersectionCurves::CurveChanged(), DialogCutArc::getArcId(), DialogPointFromArcAndTangent::GetArcId(), DialogTriangle::GetAxisP1Id(), DialogTriangle::GetAxisP2Id(), DialogCurveIntersectAxis::GetBasePointId(), DialogEndLine::GetBasePointId(), DialogHeight::GetBasePointId(), DialogLineIntersectAxis::GetBasePointId(), DialogArc::getCenter(), DialogArcWithLength::GetCenter(), DialogEllipticalArc::GetCenter(), DialogPointOfContact::getCenter(), IntersectCircleTangentDialog::GetCircleCenterId(), DialogCurveIntersectAxis::getCurveId(), DialogPointOfIntersectionArcs::GetFirstArcId(), DialogTrueDarts::GetFirstBasePointId(), IntersectCirclesDialog::GetFirstCircleCenterId(), DialogPointOfIntersectionCurves::GetFirstCurveId(), DialogTrueDarts::GetFirstDartPointId(), DialogMirrorByLine::getFirstLinePointId(), DialogPointOfContact::GetFirstPoint(), DialogAlongLine::GetFirstPointId(), DialogBisector::GetFirstPointId(), DialogLineIntersectAxis::GetFirstPointId(), DialogNormal::GetFirstPointId(), DialogTriangle::GetFirstPointId(), PointIntersectXYDialog::getFirstPointId(), DialogMirrorByAxis::getOriginPointId(), DialogMove::getOriginPointId(), DialogRotation::getOriginPointId(), DialogCubicBezier::GetP1(), DialogSpline::GetP1(), DialogShoulderPoint::GetP1Line(), DialogLineIntersect::GetP1Line1(), DialogLineIntersect::GetP1Line2(), DialogHeight::GetP1LineId(), DialogCubicBezier::GetP2(), DialogShoulderPoint::GetP2Line(), DialogLineIntersect::GetP2Line1(), DialogLineIntersect::GetP2Line2(), DialogHeight::GetP2LineId(), DialogCubicBezier::GetP3(), DialogShoulderPoint::GetP3(), DialogCubicBezier::GetP4(), DialogSpline::GetP4(), AnchorPointDialog::GetPieceId(), InsertNodesDialog::getPieceId(), DialogInternalPath::GetPieceId(), AnchorPointDialog::GetPointId(), DialogPointOfIntersectionArcs::GetSecondArcId(), DialogTrueDarts::GetSecondBasePointId(), IntersectCirclesDialog::GetSecondCircleCenterId(), DialogPointOfIntersectionCurves::GetSecondCurveId(), DialogTrueDarts::GetSecondDartPointId(), DialogMirrorByLine::getSecondLinePointId(), DialogPointOfContact::GetSecondPoint(), DialogAlongLine::GetSecondPointId(), DialogBisector::GetSecondPointId(), DialogLineIntersectAxis::GetSecondPointId(), DialogNormal::GetSecondPointId(), DialogTriangle::GetSecondPointId(), PointIntersectXYDialog::getSecondPointId(), DialogCutSpline::getSplineId(), DialogCutSplinePath::getSplinePathId(), DialogPointFromArcAndTangent::GetTangentPointId(), IntersectCircleTangentDialog::GetTangentPointId(), DialogTrueDarts::GetThirdDartPointId(), DialogBisector::GetThirdPointId(), PatternPieceDialog::grainlineAnchorChanged(), DialogMove::originChanged(), PatternPieceDialog::patternLabelAnchorChanged(), PatternPieceDialog::pieceLabelAnchorChanged(), DialogMirrorByAxis::pointChanged(), DialogMirrorByLine::pointChanged(), DialogRotation::pointChanged(), IntersectCirclesDialog::PointChanged(), IntersectCircleTangentDialog::PointChanged(), DialogArc::pointNameChanged(), DialogArcWithLength::pointNameChanged(), DialogEllipticalArc::pointNameChanged(), DialogBisector::PointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogHeight::PointNameChanged(), DialogLine::PointNameChanged(), DialogLineIntersect::PointNameChanged(), DialogLineIntersectAxis::PointNameChanged(), DialogNormal::PointNameChanged(), DialogPointOfContact::PointNameChanged(), DialogShoulderPoint::PointNameChanged(), DialogSpline::PointNameChanged(), DialogTriangle::PointNameChanged(), and DialogTrueDarts::PointNameChanged().
GetListInternals()
template<typename T > QVector< T > DialogTool::GetListInternals (const QListWidget * list) const protected
Definition at line 341 of file dialogtool.h.
References SCASSERT.
getNodeInfo()
NodeInfo DialogTool::getNodeInfo (const VPieceNode & node, bool showNotch = false) const protected
Definition at line 628 of file dialogtool.cpp.
References Castle, data, Diamond, VContainer::GetGObject(), VPieceNode::GetId(), VPieceNode::getNotchType(), VPieceNode::GetReverse(), VPieceNode::GetTypeTool(), NodeInfo::icon, VPieceNode::isNotch(), NodeInfo::name, NodePoint, qApp, Slit, TNotch, UNotch, VExternal, and VInternal.
Referenced by PatternPieceDialog::excludeNode(), PatternPieceDialog::initializeCSAPoint(), DialogInternalPath::initializeNodesList(), PatternPieceDialog::initializeNodesList(), DialogInternalPath::initializeNotchesList(), PatternPieceDialog::initializeNotchesList(), newNodeItem(), DialogInternalPath::notchTypeChanged(), PatternPieceDialog::notchTypeChanged(), PatternPieceDialog::reverseNode(), PatternPieceDialog::setNotch(), InsertNodesDialog::showContextMenu(), and DialogInternalPath::ShowContextMenu().
getPointName()
QString DialogTool::getPointName () const
Definition at line 1296 of file dialogtool.cpp.
References pointName.
GetToolId()
quint32 DialogTool::GetToolId () const
Definition at line 1284 of file dialogtool.cpp.
References toolId.
Referenced by PatternPieceDialog::pathDialogClosed().
initializeFormulaUi()
template<typename T > void DialogTool::initializeFormulaUi (T * ui) inline protected
initializeFormulaUi initialize ui object for the formula field
Parameters
ui Dialog container
Definition at line 398 of file dialogtool.h.
References labelEditFormula, labelResultCalculation, and plainTextEditFormula.
Referenced by DialogAlongLine::DialogAlongLine(), DialogBisector::DialogBisector(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogCutArc::DialogCutArc(), DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), DialogEndLine::DialogEndLine(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogNormal::DialogNormal(), DialogPointOfContact::DialogPointOfContact(), DialogShoulderPoint::DialogShoulderPoint(), and EditFormulaDialog::EditFormulaDialog().
initializeNodeAngles()
void DialogTool::initializeNodeAngles (QComboBox * box) protected
Definition at line 717 of file dialogtool.cpp.
References ByFirstEdgeRightAngle, ByFirstEdgeSymmetry, ByLength, ByPointsIntersection, BySecondEdgeRightAngle, BySecondEdgeSymmetry, and SCASSERT.
Referenced by PatternPieceDialog::initializeSeamAllowanceTab(), and DialogInternalPath::InitSeamAllowanceTab().
initializeOkCancel()
template<typename T > void DialogTool::initializeOkCancel (T * ui) inline protected
initializeOkCancel initialize OK and Cancel buttons
Parameters
ui Dialog container
Definition at line 379 of file dialogtool.h.
References DialogAccepted(), DialogRejected(), ok_Button, qApp, and SCASSERT.
Referenced by AddToGroupDialog::AddToGroupDialog(), AnchorPointDialog::AnchorPointDialog(), DialogInternalPath::DialogInternalPath(), DialogSinglePoint::DialogSinglePoint(), EditFormulaDialog::EditFormulaDialog(), EditGroupDialog::EditGroupDialog(), initializeOkCancelApply(), and UnionDialog::UnionDialog().
initializeOkCancelApply()
template<typename T > void DialogTool::initializeOkCancelApply (T * ui) inline protected
initializeOkCancelApply initialize OK / Cancel and Apply buttons
Parameters
ui Dialog container
Definition at line 365 of file dialogtool.h.
References apply_Button, DialogApply(), initializeOkCancel(), and SCASSERT.
Referenced by DialogAlongLine::DialogAlongLine(), DialogArc::DialogArc(), DialogArcWithLength::DialogArcWithLength(), DialogBisector::DialogBisector(), DialogCubicBezier::DialogCubicBezier(), DialogCubicBezierPath::DialogCubicBezierPath(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogCutArc::DialogCutArc(), DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), DialogEllipticalArc::DialogEllipticalArc(), DialogEndLine::DialogEndLine(), DialogHeight::DialogHeight(), DialogLine::DialogLine(), DialogLineIntersect::DialogLineIntersect(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogMirrorByAxis::DialogMirrorByAxis(), DialogMirrorByLine::DialogMirrorByLine(), DialogMove::DialogMove(), DialogNormal::DialogNormal(), DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfContact::DialogPointOfContact(), DialogPointOfIntersectionArcs::DialogPointOfIntersectionArcs(), DialogPointOfIntersectionCurves::DialogPointOfIntersectionCurves(), DialogRotation::DialogRotation(), DialogShoulderPoint::DialogShoulderPoint(), DialogSpline::DialogSpline(), DialogSplinePath::DialogSplinePath(), DialogTriangle::DialogTriangle(), DialogTrueDarts::DialogTrueDarts(), IntersectCirclesDialog::IntersectCirclesDialog(), IntersectCircleTangentDialog::IntersectCircleTangentDialog(), PatternPieceDialog::PatternPieceDialog(), and PointIntersectXYDialog::PointIntersectXYDialog().
isEachPointNameUnique()
bool DialogTool::isEachPointNameUnique (QListWidget * listWidget) static protected
Definition at line 583 of file dialogtool.cpp.
References VPieceNode::GetId(), VPieceNode::GetTypeTool(), NodePoint, and SCASSERT.
Referenced by PatternPieceDialog::isMainPathValid(), and DialogInternalPath::PathIsValid().
isFirstPointSameAsLast()
bool DialogTool::isFirstPointSameAsLast (QListWidget * listWidget) static protected
Definition at line 552 of file dialogtool.cpp.
References FindNotExcludedNodeDown(), FindNotExcludedNodeUp(), anonymous_namespace{dialogtool.cpp}::RowId(), and SCASSERT.
Referenced by PatternPieceDialog::isMainPathValid(), and DialogInternalPath::PathIsValid().
IsSpline()
bool DialogTool::IsSpline (const QSharedPointer< VGObject > & obj) const private
Definition at line 1065 of file dialogtool.cpp.
References Calculation, CubicBezier, and Spline.
Referenced by FillComboBoxSplines().
IsSplinePath()
bool DialogTool::IsSplinePath (const QSharedPointer< VGObject > & obj) const private
Definition at line 731 of file dialogtool.cpp.
References Calculation, CubicBezierPath, and SplinePath.
Referenced by FillComboBoxSplinesPath().
keyPressEvent()
void DialogTool::keyPressEvent (QKeyEvent * event) protected virtual
Definition at line 174 of file dialogtool.cpp.
References DialogRejected().
MoveCursorToEnd()
void DialogTool::MoveCursorToEnd (QPlainTextEdit * plainTextEdit) const protected
Definition at line 432 of file dialogtool.cpp.
References SCASSERT.
Referenced by DialogSpline::FXAngle1(), DialogSplinePath::FXAngle1(), DialogSpline::FXAngle2(), DialogSplinePath::FXAngle2(), DialogSpline::FXLength1(), DialogSplinePath::FXLength1(), DialogSpline::FXLength2(), DialogSplinePath::FXLength2(), DialogInternalPath::nodeChanged(), PatternPieceDialog::nodeChanged(), DialogCurveIntersectAxis::SetAngle(), DialogEndLine::SetAngle(), DialogLineIntersectAxis::SetAngle(), DialogMove::SetAngle(), DialogRotation::SetAngle(), IntersectCircleTangentDialog::SetCircleRadius(), DialogArc::setF1(), DialogArcWithLength::SetF1(), DialogEllipticalArc::SetF1(), DialogArc::setF2(), DialogEllipticalArc::SetF2(), IntersectCirclesDialog::SetFirstCircleRadius(), EditFormulaDialog::SetFormula(), DialogAlongLine::SetFormula(), DialogBisector::SetFormula(), DialogCutArc::SetFormula(), DialogCutSpline::SetFormula(), DialogCutSplinePath::SetFormula(), DialogEndLine::SetFormula(), DialogNormal::SetFormula(), DialogShoulderPoint::SetFormula(), PatternPieceDialog::setGrainlineAngle(), PatternPieceDialog::setGrainlineLength(), DialogArcWithLength::SetLength(), DialogMove::SetLength(), PatternPieceDialog::setPatternLabelAngle(), PatternPieceDialog::setPatternLabelHeight(), PatternPieceDialog::setPatternLabelWidth(), PatternPieceDialog::setPieceLabelAngle(), PatternPieceDialog::setPieceLabelHeight(), PatternPieceDialog::setPieceLabelWidth(), DialogArc::setRadius(), DialogArcWithLength::SetRadius(), DialogPointOfContact::setRadius(), DialogEllipticalArc::SetRadius1(), DialogEllipticalArc::SetRadius2(), DialogMove::setRotation(), DialogEllipticalArc::SetRotationAngle(), DialogInternalPath::setSeamAllowanceWidthFormula(), PatternPieceDialog::setSeamAllowanceWidthFormula(), and IntersectCirclesDialog::SetSecondCircleRadius().
moveListRowBottom()
void DialogTool::moveListRowBottom (QListWidget * list) static
Definition at line 1346 of file dialogtool.cpp.
References SCASSERT.
moveListRowDown()
void DialogTool::moveListRowDown (QListWidget * list) static
Definition at line 1330 of file dialogtool.cpp.
References SCASSERT.
moveListRowTop()
void DialogTool::moveListRowTop (QListWidget * list) static
Definition at line 1302 of file dialogtool.cpp.
References SCASSERT.
moveListRowUp()
void DialogTool::moveListRowUp (QListWidget * list) static
Definition at line 1314 of file dialogtool.cpp.
References SCASSERT.
NamePointChanged
void DialogTool::NamePointChanged () slot
NamePointChanged check name of point.
Definition at line 1110 of file dialogtool.cpp.
References ChangeColor(), CheckState(), data, flagName, VContainer::IsUnique(), labelEditNamePoint, NameRegExp(), okColor, pointName, and SCASSERT.
Referenced by DialogAlongLine::DialogAlongLine(), DialogBisector::DialogBisector(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogCutArc::DialogCutArc(), DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), DialogEndLine::DialogEndLine(), DialogHeight::DialogHeight(), DialogLineIntersect::DialogLineIntersect(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogNormal::DialogNormal(), DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfContact::DialogPointOfContact(), DialogPointOfIntersectionArcs::DialogPointOfIntersectionArcs(), DialogPointOfIntersectionCurves::DialogPointOfIntersectionCurves(), DialogShoulderPoint::DialogShoulderPoint(), DialogSinglePoint::DialogSinglePoint(), DialogTriangle::DialogTriangle(), IntersectCirclesDialog::IntersectCirclesDialog(), IntersectCircleTangentDialog::IntersectCircleTangentDialog(), and PointIntersectXYDialog::PointIntersectXYDialog().
newNodeItem()
void DialogTool::newNodeItem (QListWidget * listWidget, const VPieceNode & node, bool nodeExcluded = true, bool isDuplicate = false) protected
Definition at line 679 of file dialogtool.cpp.
References VPieceNode::GetId(), getNodeInfo(), VPieceNode::GetTypeTool(), NodeInfo::icon, VPieceNode::isExcluded(), NodeInfo::name, NodeArc, NodeElArc, NodeFont(), NodePoint, NodeSpline, NodeSplinePath, NULL_ID, anonymous_namespace{dialogtool.cpp}::RowId(), and SCASSERT.
Referenced by PatternPieceDialog::duplicateNode(), DialogInternalPath::NewItem(), PatternPieceDialog::newMainPathItem(), and InsertNodesDialog::ShowDialog().
NodeFont()
QFont DialogTool::NodeFont (bool nodeExcluded) static protected
Definition at line 618 of file dialogtool.cpp.
References qApp.
Referenced by PatternPieceDialog::excludeNode(), and newNodeItem().
normalize()
qreal DialogTool::normalize (const qreal value, const qreal start, const qreal end) protected
Definition at line 886 of file dialogtool.cpp.
PointNameChanged
virtual void DialogTool::PointNameChanged () inline virtual slot
Definition at line 171 of file dialogtool.h.
PrepareList()
template<typename T > void DialogTool::PrepareList (QMap< QString, quint32 > & list, quint32 id) const private
Definition at line 1047 of file dialogtool.cpp.
References data, VContainer::GeometricObject(), qApp, and SCASSERT.
SaveData()
virtual void DialogTool::SaveData () inline protected virtual
SaveData Put dialog data in local variables.
Reimplemented in PointIntersectXYDialog, PatternPieceDialog, IntersectCircleTangentDialog, IntersectCirclesDialog, DialogTrueDarts, DialogTriangle, DialogSplinePath, DialogSpline, DialogSinglePoint, DialogShoulderPoint, DialogRotation, DialogPointOfIntersectionCurves, DialogPointOfIntersectionArcs, DialogPointOfContact, DialogPointFromArcAndTangent, DialogNormal, DialogMove, DialogMirrorByLine, DialogMirrorByAxis, DialogLineIntersectAxis, DialogLineIntersect, DialogLine, DialogHeight, DialogEndLine, DialogEllipticalArc, DialogCutSplinePath, DialogCutSpline, DialogCutArc, DialogCurveIntersectAxis, DialogCubicBezierPath, DialogCubicBezier, DialogBisector, DialogArcWithLength, DialogArc, and DialogAlongLine.
Definition at line 304 of file dialogtool.h.
Referenced by DialogAccepted(), and DialogApply().
SelectedObject
void DialogTool::SelectedObject (bool selected, quint32 object, quint32 tool) virtual slot
Definition at line 1099 of file dialogtool.cpp.
Referenced by MainWindow::SetToolButton().
SetAssociatedTool()
void DialogTool::SetAssociatedTool (VAbstractTool * tool)
Definition at line 1376 of file dialogtool.cpp.
References associatedTool, data, VAbstractTool::getData(), VAbstractTool::getId(), NULL_ID, SetToolId(), and vis.
setCurrentArcId()
void DialogTool::setCurrentArcId (QComboBox * box, const quint32 & value, FillComboBox rule = FillComboBox::NoChildren, const quint32 & ch1 = NULL_ID, const quint32 & ch2 = NULL_ID) const protected
setCurrentArcId
Definition at line 924 of file dialogtool.cpp.
References ChangeCurrentData(), FillComboBoxArcs(), and SCASSERT.
Referenced by DialogCutArc::setArcId(), DialogPointFromArcAndTangent::SetArcId(), DialogPointOfIntersectionArcs::SetFirstArcId(), and DialogPointOfIntersectionArcs::SetSecondArcId().
setCurrentCurveId()
void DialogTool::setCurrentCurveId (QComboBox * box, const quint32 & value) const protected
Definition at line 946 of file dialogtool.cpp.
References ChangeCurrentData(), FillComboBoxCurves(), and SCASSERT.
Referenced by DialogCurveIntersectAxis::setCurveId(), DialogPointOfIntersectionCurves::SetFirstCurveId(), and DialogPointOfIntersectionCurves::SetSecondCurveId().
setCurrentPointId()
void DialogTool::setCurrentPointId (QComboBox * box, const quint32 & value, FillComboBox rule = FillComboBox::NoChildren, const quint32 & ch1 = NULL_ID, const quint32 & ch2 = NULL_ID) const protected
Definition at line 896 of file dialogtool.cpp.
References ChangeCurrentData(), FillComboBoxPoints(), and SCASSERT.
Referenced by DialogTriangle::SetAxisP1Id(), DialogTriangle::SetAxisP2Id(), DialogCurveIntersectAxis::SetBasePointId(), DialogEndLine::SetBasePointId(), DialogHeight::SetBasePointId(), DialogLineIntersectAxis::SetBasePointId(), DialogPointOfContact::setCenter(), IntersectCircleTangentDialog::SetCircleCenterId(), DialogTrueDarts::SetFirstBasePointId(), IntersectCirclesDialog::SetFirstCircleCenterId(), DialogTrueDarts::SetFirstDartPointId(), DialogLine::setFirstPoint(), DialogPointOfContact::SetFirstPoint(), DialogAlongLine::SetFirstPointId(), DialogBisector::SetFirstPointId(), DialogLineIntersectAxis::SetFirstPointId(), DialogNormal::SetFirstPointId(), DialogTriangle::SetFirstPointId(), PointIntersectXYDialog::setFirstPointId(), DialogShoulderPoint::SetP1Line(), DialogLineIntersect::SetP1Line1(), DialogLineIntersect::SetP1Line2(), DialogHeight::SetP1LineId(), DialogShoulderPoint::SetP2Line(), DialogLineIntersect::SetP2Line1(), DialogLineIntersect::SetP2Line2(), DialogHeight::SetP2LineId(), DialogShoulderPoint::SetP3(), AnchorPointDialog::SetPointId(), DialogTrueDarts::SetSecondBasePointId(), IntersectCirclesDialog::SetSecondCircleCenterId(), DialogTrueDarts::SetSecondDartPointId(), DialogLine::setSecondPoint(), DialogPointOfContact::SetSecondPoint(), DialogAlongLine::SetSecondPointId(), DialogBisector::SetSecondPointId(), DialogLineIntersectAxis::SetSecondPointId(), DialogNormal::SetSecondPointId(), DialogTriangle::SetSecondPointId(), PointIntersectXYDialog::setSecondPointId(), DialogCubicBezier::SetSpline(), DialogSpline::SetSpline(), DialogPointFromArcAndTangent::SetTangentPointId(), IntersectCircleTangentDialog::SetTangentPointId(), DialogTrueDarts::SetThirdDartPointId(), and DialogBisector::SetThirdPointId().
setCurrentSplineId()
void DialogTool::setCurrentSplineId (QComboBox * box, const quint32 & value) const protected
setCurrentSplineId set current spline id in combobox
Definition at line 913 of file dialogtool.cpp.
References ChangeCurrentData(), FillComboBoxSplines(), and SCASSERT.
Referenced by DialogCutSpline::setSplineId().
setCurrentSplinePathId()
void DialogTool::setCurrentSplinePathId (QComboBox * box, const quint32 & value) const protected
setCurrentSplinePathId set current splinePath id in combobox
Parameters
box combobox
value splinePath id
Definition at line 938 of file dialogtool.cpp.
References ChangeCurrentData(), FillComboBoxSplinesPath(), and SCASSERT.
Referenced by DialogCutSplinePath::setSplinePathId().
SetObject()
bool DialogTool::SetObject (const quint32 & id, QComboBox * box, const QString & toolTip) protected
Definition at line 974 of file dialogtool.cpp.
References SCASSERT, and ToolTip().
Referenced by AnchorPointDialog::ChosenObject(), DialogAlongLine::ChosenObject(), DialogArc::ChosenObject(), DialogArcWithLength::ChosenObject(), DialogBisector::ChosenObject(), DialogCubicBezier::ChosenObject(), DialogCurveIntersectAxis::ChosenObject(), DialogCutArc::ChosenObject(), DialogCutSpline::ChosenObject(), DialogCutSplinePath::ChosenObject(), DialogEllipticalArc::ChosenObject(), DialogEndLine::ChosenObject(), DialogHeight::ChosenObject(), DialogLine::ChosenObject(), DialogLineIntersect::ChosenObject(), DialogLineIntersectAxis::ChosenObject(), DialogMirrorByAxis::ChosenObject(), DialogMirrorByLine::ChosenObject(), DialogMove::ChosenObject(), DialogNormal::ChosenObject(), DialogPointFromArcAndTangent::ChosenObject(), DialogPointOfContact::ChosenObject(), DialogPointOfIntersectionArcs::ChosenObject(), DialogPointOfIntersectionCurves::ChosenObject(), DialogRotation::ChosenObject(), DialogShoulderPoint::ChosenObject(), DialogSpline::ChosenObject(), DialogTriangle::ChosenObject(), DialogTrueDarts::ChosenObject(), IntersectCirclesDialog::ChosenObject(), IntersectCircleTangentDialog::ChosenObject(), PointIntersectXYDialog::ChosenObject(), and DialogMove::ShowDialog().
SetPiecesList()
void DialogTool::SetPiecesList (const QVector< quint32 > & list) virtual
Reimplemented in DialogInternalPath, InsertNodesDialog, and AnchorPointDialog.
Definition at line 1370 of file dialogtool.cpp.
SetToolId()
void DialogTool::SetToolId (const quint32 & value)
Definition at line 1290 of file dialogtool.cpp.
References toolId.
Referenced by SetAssociatedTool().
ShowDialog()
void DialogTool::ShowDialog (bool click) virtual
Reimplemented in InsertNodesDialog, EditGroupDialog, DialogRotation, DialogMove, DialogMirrorByLine, DialogMirrorByAxis, DialogLineIntersectAxis, EditGroupDialog, DialogEndLine, DialogCurveIntersectAxis, and AddToGroupDialog.
Definition at line 1358 of file dialogtool.cpp.
showEvent()
void DialogTool::showEvent (QShowEvent * event) protected virtual
showEvent handle when window show
Parameters
event event
Reimplemented in PatternPieceDialog, EditFormulaDialog, and DialogVariables.
Definition at line 203 of file dialogtool.cpp.
References isInitialized, and ShowVisualization().
ShowVisualization()
virtual void DialogTool::ShowVisualization () inline protected virtual
Reimplemented in PointIntersectXYDialog, DialogInternalPath, IntersectCircleTangentDialog, IntersectCirclesDialog, DialogTrueDarts, DialogTriangle, DialogSplinePath, DialogSpline, DialogShoulderPoint, DialogRotation, DialogPointOfIntersectionCurves, DialogPointOfIntersectionArcs, DialogPointOfContact, DialogPointFromArcAndTangent, DialogNormal, DialogMove, DialogMirrorByLine, DialogMirrorByAxis, DialogLineIntersectAxis, DialogLineIntersect, DialogLine, DialogHeight, DialogEndLine, DialogEllipticalArc, DialogCutSplinePath, DialogCutSpline, DialogCutArc, DialogCurveIntersectAxis, DialogCubicBezierPath, DialogCubicBezier, DialogBisector, DialogArcWithLength, DialogArc, DialogAlongLine, and AnchorPointDialog.
Definition at line 300 of file dialogtool.h.
Referenced by showEvent().
ToolTip
void DialogTool::ToolTip (const QString & toolTip) signal
ToolTip emit tooltipe for tool.
Parameters
toolTip text tooltipe
Referenced by DialogAlongLine::ChosenObject(), DialogMirrorByAxis::ChosenObject(), DialogMirrorByLine::ChosenObject(), DialogRotation::ChosenObject(), DialogSplinePath::ChosenObject(), DialogInternalPath::ChosenObject(), PatternPieceDialog::ChosenObject(), UnionDialog::chosenPiece(), Eval(), SetObject(), MainWindow::SetToolButton(), AddToGroupDialog::ShowDialog(), DialogCubicBezierPath::ShowDialog(), DialogCurveIntersectAxis::ShowDialog(), DialogEndLine::ShowDialog(), EditGroupDialog::ShowDialog(), DialogLineIntersectAxis::ShowDialog(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), DialogRotation::ShowDialog(), DialogSplinePath::ShowDialog(), InsertNodesDialog::ShowDialog(), DialogInternalPath::ShowDialog(), PatternPieceDialog::ShowDialog(), and ~DialogTool().
ValFormulaChanged() [1/2]
void DialogTool::ValFormulaChanged (bool & flag, QLineEdit * edit, QTimer * timer, const QString & postfix = QString()) protected
ValFormulaChanged handle change formula.
Parameters
flag flag state of formula
edit LineEdit
timer timer of formula
Definition at line 744 of file dialogtool.cpp.
References ChangeColor(), CheckState(), labelEditFormula, labelResultCalculation, and SCASSERT.
Referenced by DialogInternalPath::afterWidthChanged(), PatternPieceDialog::afterWidthChanged(), DialogSpline::Angle1Changed(), DialogSpline::Angle2Changed(), DialogMove::angleChanged(), DialogRotation::angleChanged(), DialogCurveIntersectAxis::AngleTextChanged(), DialogEndLine::AngleTextChanged(), DialogLineIntersectAxis::AngleTextChanged(), DialogInternalPath::beforeWidthChanged(), PatternPieceDialog::beforeWidthChanged(), IntersectCirclesDialog::Circle1RadiusChanged(), IntersectCirclesDialog::Circle2RadiusChanged(), IntersectCircleTangentDialog::CircleRadiusChanged(), DialogInternalPath::defaultWidthChanged(), PatternPieceDialog::defaultWidthChanged(), DialogArc::F1Changed(), DialogArcWithLength::F1Changed(), DialogEllipticalArc::F1Changed(), DialogArc::F2Changed(), DialogEllipticalArc::F2Changed(), FormulaChanged(), FormulaChangedPlainText(), DialogSpline::Length1Changed(), DialogSpline::Length2Changed(), DialogArcWithLength::LengthChanged(), DialogMove::lengthChanged(), DialogEllipticalArc::Radius1Changed(), DialogEllipticalArc::Radius2Changed(), DialogArc::RadiusChanged(), DialogArcWithLength::RadiusChanged(), DialogEllipticalArc::RotationAngleChanged(), and DialogMove::rotationChanged().
ValFormulaChanged() [2/2]
void DialogTool::ValFormulaChanged (bool & flag, QPlainTextEdit * edit, QTimer * timer, const QString & postfix = QString()) protected
Definition at line 769 of file dialogtool.cpp.
References ChangeColor(), CheckState(), labelEditFormula, labelResultCalculation, and SCASSERT.
Member Data Documentation
apply_Button
QPushButton* DialogTool::apply_Button protected
apply_Button button apply
Definition at line 202 of file dialogtool.h.
Referenced by CheckState(), DialogArc::CheckState(), DialogArcWithLength::CheckState(), DialogEllipticalArc::CheckState(), DialogMirrorByAxis::CheckState(), DialogMirrorByLine::CheckState(), DialogMove::CheckState(), DialogPointOfIntersectionCurves::CheckState(), DialogRotation::CheckState(), DialogSpline::CheckState(), DialogSplinePath::CheckState(), DialogTrueDarts::CheckState(), IntersectCirclesDialog::CheckState(), IntersectCircleTangentDialog::CheckState(), PatternPieceDialog::CheckState(), PatternPieceDialog::enableApply(), and initializeOkCancelApply().
associatedTool
VAbstractTool* DialogTool::associatedTool protected
associatedTool vdrawtool associated with opened dialog.
Definition at line 224 of file dialogtool.h.
Referenced by GetAssociatedTool(), and SetAssociatedTool().
data
const VContainer* DialogTool::data protected
data container with data
Definition at line 177 of file dialogtool.h.
Referenced by AnchorPointDialog::AnchorPointDialog(), DialogSplinePath::Angle1Changed(), DialogSplinePath::Angle2Changed(), EditFormulaDialog::arcRadii(), DialogLineIntersect::CheckIntersecion(), DialogTrueDarts::CheckName(), UnionDialog::CheckObject(), UnionDialog::checkPiece(), DialogCubicBezierPath::ChosenObject(), DialogSplinePath::ChosenObject(), PatternPieceDialog::ChosenObject(), UnionDialog::chosenPiece(), EditFormulaDialog::controlPointLengths(), InsertNodesDialog::correctCurveDirection(), PatternPieceDialog::CreatePiece(), PatternPieceDialog::createPieceName(), DialogCubicBezierPath::currentPointChanged(), DialogSplinePath::currentPointChanged(), DialogSpline::CurrentSpline(), EditFormulaDialog::curveAngles(), EditFormulaDialog::curveLengths(), EditFormulaDialog::customVariables(), DialogAlongLine::DialogAlongLine(), DialogArc::DialogArc(), DialogArcWithLength::DialogArcWithLength(), DialogBisector::DialogBisector(), DialogCubicBezier::DialogCubicBezier(), DialogCubicBezierPath::DialogCubicBezierPath(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogCutArc::DialogCutArc(), DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), DialogEllipticalArc::DialogEllipticalArc(), DialogEndLine::DialogEndLine(), DialogHeight::DialogHeight(), DialogInternalPath::DialogInternalPath(), DialogLine::DialogLine(), DialogLineIntersect::DialogLineIntersect(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogMirrorByAxis::DialogMirrorByAxis(), DialogMirrorByLine::DialogMirrorByLine(), DialogMove::DialogMove(), DialogNormal::DialogNormal(), DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfContact::DialogPointOfContact(), DialogPointOfIntersectionArcs::DialogPointOfIntersectionArcs(), DialogPointOfIntersectionCurves::DialogPointOfIntersectionCurves(), DialogRotation::DialogRotation(), DialogShoulderPoint::DialogShoulderPoint(), DialogSpline::DialogSpline(), DialogSplinePath::DialogSplinePath(), DialogTool(), DialogTriangle::DialogTriangle(), DialogTrueDarts::DialogTrueDarts(), DNumber(), DialogInternalPath::editAfterSeamAllowanceWidth(), PatternPieceDialog::editAfterSeamAllowanceWidth(), DialogMove::editAngleFormula(), DialogRotation::editAngleFormula(), DialogInternalPath::editBeforeSeamAllowanceWidth(), PatternPieceDialog::editBeforeSeamAllowanceWidth(), DialogInternalPath::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editGrainlineFormula(), DialogMove::editLengthFormula(), PatternPieceDialog::editPatternLabelFormula(), PatternPieceDialog::editPieceLabelFormula(), DialogMove::editRotationFormula(), Eval(), DialogInternalPath::evaluateDefaultWidth(), PatternPieceDialog::evaluateDefaultWidth(), FillCombo(), FillComboBoxCurves(), FillComboBoxPiecesList(), FillComboBoxSplines(), FillComboBoxSplinesPath(), AddToGroupDialog::fillNameBox(), DialogCurveIntersectAxis::FXAngle(), DialogEndLine::FXAngle(), DialogLineIntersectAxis::FXAngle(), DialogSpline::FXAngle1(), DialogSplinePath::FXAngle1(), DialogSpline::FXAngle2(), DialogSplinePath::FXAngle2(), IntersectCirclesDialog::FXCircle1Radius(), IntersectCirclesDialog::FXCircle2Radius(), IntersectCircleTangentDialog::FXCircleRadius(), DialogArc::FXF1(), DialogArcWithLength::FXF1(), DialogEllipticalArc::FXF1(), DialogArc::FXF2(), DialogEllipticalArc::FXF2(), DialogAlongLine::FXLength(), DialogArcWithLength::FXLength(), DialogBisector::FXLength(), DialogCutArc::FXLength(), DialogCutSpline::FXLength(), DialogCutSplinePath::FXLength(), DialogEndLine::FXLength(), DialogNormal::FXLength(), DialogShoulderPoint::FXLength(), DialogSpline::FXLength1(), DialogSplinePath::FXLength1(), DialogSpline::FXLength2(), DialogSplinePath::FXLength2(), DialogArc::FXRadius(), DialogArcWithLength::FXRadius(), DialogPointOfContact::FXRadius(), DialogEllipticalArc::FXRadius1(), DialogEllipticalArc::FXRadius2(), DialogEllipticalArc::FXRotationAngle(), PatternPieceDialog::getFormulaValue(), getNodeInfo(), DialogCubicBezier::GetP1(), DialogSpline::GetP1(), DialogCubicBezier::GetP2(), DialogCubicBezier::GetP3(), DialogCubicBezier::GetP4(), DialogSpline::GetP4(), PatternPieceDialog::getPathName(), HistoryDialog::getPointName(), PatternPieceDialog::initAnchorPoint(), InsertNodesDialog::insertCurveNodes(), IntersectCirclesDialog::IntersectCirclesDialog(), IntersectCircleTangentDialog::IntersectCircleTangentDialog(), PatternPieceDialog::isMainPathClockwise(), PatternPieceDialog::isMainPathValid(), DialogSplinePath::Length1Changed(), DialogSplinePath::Length2Changed(), EditFormulaDialog::lineAngles(), EditFormulaDialog::lineLengths(), EditFormulaDialog::measurements(), NamePointChanged(), PatternPieceDialog::newAnchorPoint(), PatternPieceDialog::pathDialogClosed(), DialogInternalPath::PathIsValid(), PatternPieceDialog::PatternPieceDialog(), PointIntersectXYDialog::PointIntersectXYDialog(), DialogArc::pointNameChanged(), DialogArcWithLength::pointNameChanged(), DialogEllipticalArc::pointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogHeight::PointNameChanged(), DialogLineIntersect::PointNameChanged(), DialogSpline::PointNameChanged(), PrepareList(), InsertNodesDialog::SelectedObject(), SetAssociatedTool(), DialogAlongLine::SetCurrentLength(), PatternPieceDialog::setGrainlineLength(), PatternPieceDialog::setPatternLabelHeight(), PatternPieceDialog::setPatternLabelWidth(), AnchorPointDialog::SetPieceId(), DialogInternalPath::SetPieceId(), PatternPieceDialog::setPieceLabelHeight(), PatternPieceDialog::setPieceLabelWidth(), PatternPieceDialog::showAnchorPoints(), PatternPieceDialog::showCustomSAContextMenu(), DialogCubicBezierPath::ShowDialog(), DialogCurveIntersectAxis::ShowDialog(), DialogEndLine::ShowDialog(), DialogLineIntersectAxis::ShowDialog(), DialogRotation::ShowDialog(), DialogSpline::ShowDialog(), DialogSplinePath::ShowDialog(), PatternPieceDialog::showInternalPathsContextMenu(), DialogMirrorByAxis::suffixChanged(), DialogMirrorByLine::suffixChanged(), DialogMove::suffixChanged(), DialogRotation::suffixChanged(), PatternPieceDialog::updateGrainlineValues(), PatternPieceDialog::updatePatternLabelValues(), PatternPieceDialog::updatePieceLabelValues(), and EditFormulaDialog::valueChanged().
errorColor
const QColor DialogTool::errorColor protected
Definition at line 220 of file dialogtool.h.
Referenced by DialogPointOfIntersectionArcs::ArcChanged(), AnchorPointDialog::CheckPieces(), AnchorPointDialog::CheckPoint(), DialogCubicBezierPath::currentPointChanged(), DialogSplinePath::currentPointChanged(), DialogPointOfIntersectionCurves::CurveChanged(), PatternPieceDialog::grainlineAnchorChanged(), PatternPieceDialog::patternLabelAnchorChanged(), PatternPieceDialog::pieceLabelAnchorChanged(), DialogAlongLine::PointChanged(), DialogMirrorByAxis::pointChanged(), DialogMirrorByLine::pointChanged(), DialogRotation::pointChanged(), IntersectCirclesDialog::PointChanged(), IntersectCircleTangentDialog::PointChanged(), PointIntersectXYDialog::pointChanged(), DialogBisector::PointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogHeight::PointNameChanged(), DialogLine::PointNameChanged(), DialogLineIntersect::PointNameChanged(), DialogLineIntersectAxis::PointNameChanged(), DialogNormal::PointNameChanged(), DialogPointOfContact::PointNameChanged(), DialogShoulderPoint::PointNameChanged(), DialogSpline::PointNameChanged(), DialogTriangle::PointNameChanged(), DialogTrueDarts::PointNameChanged(), and InsertNodesDialog::validatePieces().
flagError
bool DialogTool::flagError protected
flagError use this flag if for you do not enought
See also
flagName and
flagFormula.
In many cases you will need more flags fore checking if all data are valid. By default this flag is true.
Definition at line 193 of file dialogtool.h.
Referenced by AnchorPointDialog::AnchorPointDialog(), DialogCurveIntersectAxis::AngleTextChanged(), DialogEndLine::AngleTextChanged(), DialogLineIntersectAxis::AngleTextChanged(), DialogPointOfIntersectionArcs::ArcChanged(), AnchorPointDialog::CheckPieces(), CheckState(), AnchorPointDialog::CheckState(), DialogMirrorByAxis::CheckState(), DialogMirrorByLine::CheckState(), DialogPointOfIntersectionCurves::CheckState(), DialogRotation::CheckState(), DialogSpline::CheckState(), DialogSplinePath::CheckState(), DialogTrueDarts::CheckState(), IntersectCirclesDialog::CheckState(), IntersectCircleTangentDialog::CheckState(), DialogInternalPath::CheckState(), DialogAlongLine::ChosenObject(), DialogLine::ChosenObject(), DialogMirrorByLine::ChosenObject(), DialogCubicBezierPath::currentPointChanged(), DialogSplinePath::currentPointChanged(), DialogPointOfIntersectionCurves::CurveChanged(), DialogInternalPath::DialogInternalPath(), DialogCurveIntersectAxis::EvalAngle(), DialogEndLine::EvalAngle(), DialogLineIntersectAxis::EvalAngle(), DialogAlongLine::PointChanged(), DialogMirrorByAxis::pointChanged(), DialogMirrorByLine::pointChanged(), DialogRotation::pointChanged(), IntersectCirclesDialog::PointChanged(), IntersectCircleTangentDialog::PointChanged(), PointIntersectXYDialog::pointChanged(), DialogArc::pointNameChanged(), DialogArcWithLength::pointNameChanged(), DialogEllipticalArc::pointNameChanged(), DialogBisector::PointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogHeight::PointNameChanged(), DialogLine::PointNameChanged(), DialogLineIntersect::PointNameChanged(), DialogLineIntersectAxis::PointNameChanged(), DialogNormal::PointNameChanged(), DialogPointOfContact::PointNameChanged(), DialogShoulderPoint::PointNameChanged(), DialogSpline::PointNameChanged(), DialogTriangle::PointNameChanged(), DialogTrueDarts::PointNameChanged(), and DialogInternalPath::ValidObjects().
flagFormula
bool DialogTool::flagFormula protected
flagFormula true if formula correct
Definition at line 186 of file dialogtool.h.
Referenced by DialogInternalPath::afterWidthChanged(), DialogInternalPath::beforeWidthChanged(), CheckState(), EditFormulaDialog::CheckState(), IntersectCirclesDialog::CheckState(), IntersectCircleTangentDialog::CheckState(), PatternPieceDialog::CheckState(), DialogInternalPath::defaultWidthChanged(), PatternPieceDialog::defaultWidthChanged(), DialogAlongLine::DialogAlongLine(), DialogBisector::DialogBisector(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogCutArc::DialogCutArc(), DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), DialogEndLine::DialogEndLine(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogNormal::DialogNormal(), DialogPointOfContact::DialogPointOfContact(), DialogShoulderPoint::DialogShoulderPoint(), EditFormulaDialog::EditFormulaDialog(), EvalFormula(), EditFormulaDialog::EvalFormula(), DialogInternalPath::evaluateAfterWidth(), DialogInternalPath::evaluateBeforeWidth(), DialogInternalPath::evaluateDefaultWidth(), PatternPieceDialog::evaluateDefaultWidth(), FormulaChanged(), and FormulaChangedPlainText().
flagName
bool DialogTool::flagName protected
flagName true if name is correct
Definition at line 183 of file dialogtool.h.
Referenced by DialogTrueDarts::CheckName(), CheckState(), DialogLineIntersect::CheckState(), DialogMirrorByAxis::CheckState(), DialogMirrorByLine::CheckState(), DialogMove::CheckState(), DialogPointOfIntersectionCurves::CheckState(), DialogRotation::CheckState(), IntersectCirclesDialog::CheckState(), IntersectCircleTangentDialog::CheckState(), DialogInternalPath::CheckState(), PatternPieceDialog::CheckState(), DialogInternalPath::DialogInternalPath(), DialogMirrorByAxis::DialogMirrorByAxis(), DialogMirrorByLine::DialogMirrorByLine(), DialogMove::DialogMove(), DialogRotation::DialogRotation(), DialogSinglePoint::DialogSinglePoint(), EditGroupDialog::NameChanged(), EditGroupDialog::nameChanged(), DialogInternalPath::NameChanged(), DialogTrueDarts::NameChanged(), NamePointChanged(), PatternPieceDialog::PatternPieceDialog(), PatternPieceDialog::pieceNameChanged(), DialogMirrorByAxis::suffixChanged(), DialogMirrorByLine::suffixChanged(), DialogMove::suffixChanged(), and DialogRotation::suffixChanged().
isInitialized
bool DialogTool::isInitialized protected
isInitialized true if window is initialized
Definition at line 180 of file dialogtool.h.
Referenced by DialogSinglePoint::mousePress(), DialogVariables::resizeEvent(), EditFormulaDialog::resizeEvent(), PatternPieceDialog::resizeEvent(), DialogSinglePoint::SetData(), DialogVariables::showEvent(), EditFormulaDialog::showEvent(), showEvent(), and PatternPieceDialog::showEvent().
labelEditFormula
QLabel* DialogTool::labelEditFormula protected
labelEditFormula label used when need show wrong formula
Definition at line 217 of file dialogtool.h.
Referenced by DialogInternalPath::afterWidthChanged(), PatternPieceDialog::afterWidthChanged(), DialogSpline::Angle1Changed(), DialogSpline::Angle2Changed(), DialogMove::angleChanged(), DialogRotation::angleChanged(), DialogEndLine::AngleTextChanged(), DialogInternalPath::beforeWidthChanged(), PatternPieceDialog::beforeWidthChanged(), IntersectCirclesDialog::Circle1RadiusChanged(), IntersectCirclesDialog::Circle2RadiusChanged(), IntersectCircleTangentDialog::CircleRadiusChanged(), DialogInternalPath::defaultWidthChanged(), PatternPieceDialog::defaultWidthChanged(), Eval(), DialogEndLine::EvalAngle(), DialogSpline::EvalAngle1(), DialogSplinePath::EvalAngle1(), DialogSpline::EvalAngle2(), DialogSplinePath::EvalAngle2(), DialogEllipticalArc::EvalAngles(), IntersectCirclesDialog::EvalCircle1Radius(), IntersectCirclesDialog::EvalCircle2Radius(), IntersectCircleTangentDialog::EvalCircleRadius(), DialogArc::EvalF(), DialogArcWithLength::EvalF(), DialogSpline::EvalLength1(), DialogSplinePath::EvalLength1(), DialogSpline::EvalLength2(), DialogSplinePath::EvalLength2(), DialogArc::EvalRadius(), DialogEllipticalArc::EvalRadiuses(), DialogInternalPath::evaluateAfterWidth(), PatternPieceDialog::evaluateAfterWidth(), DialogMove::evaluateAngle(), DialogRotation::evaluateAngle(), DialogInternalPath::evaluateBeforeWidth(), PatternPieceDialog::evaluateBeforeWidth(), DialogInternalPath::evaluateDefaultWidth(), PatternPieceDialog::evaluateDefaultWidth(), DialogMove::evaluateLength(), DialogMove::evaluateRotation(), DialogArc::F1Changed(), DialogArcWithLength::F1Changed(), DialogEllipticalArc::F1Changed(), DialogArc::F2Changed(), DialogEllipticalArc::F2Changed(), initializeFormulaUi(), DialogArcWithLength::Length(), DialogSpline::Length1Changed(), DialogSpline::Length2Changed(), DialogArcWithLength::LengthChanged(), DialogMove::lengthChanged(), DialogArcWithLength::Radius(), DialogEllipticalArc::Radius1Changed(), DialogEllipticalArc::Radius2Changed(), DialogArc::RadiusChanged(), DialogArcWithLength::RadiusChanged(), DialogEllipticalArc::RotationAngleChanged(), DialogMove::rotationChanged(), and ValFormulaChanged().
labelEditNamePoint
QLabel* DialogTool::labelEditNamePoint protected
labelEditNamePoint label used when need show wrong name of point
Definition at line 214 of file dialogtool.h.
Referenced by DialogTrueDarts::CheckName(), DialogAlongLine::DialogAlongLine(), DialogBisector::DialogBisector(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogCutArc::DialogCutArc(), DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), DialogEndLine::DialogEndLine(), DialogHeight::DialogHeight(), DialogLineIntersect::DialogLineIntersect(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogNormal::DialogNormal(), DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfContact::DialogPointOfContact(), DialogPointOfIntersectionArcs::DialogPointOfIntersectionArcs(), DialogPointOfIntersectionCurves::DialogPointOfIntersectionCurves(), DialogShoulderPoint::DialogShoulderPoint(), DialogSinglePoint::DialogSinglePoint(), DialogTriangle::DialogTriangle(), IntersectCirclesDialog::IntersectCirclesDialog(), IntersectCircleTangentDialog::IntersectCircleTangentDialog(), DialogTrueDarts::NameChanged(), NamePointChanged(), and PointIntersectXYDialog::PointIntersectXYDialog().
labelResultCalculation
QLabel* DialogTool::labelResultCalculation protected
labelResultCalculation label with result of calculation
Definition at line 211 of file dialogtool.h.
Referenced by DialogInternalPath::afterWidthChanged(), PatternPieceDialog::afterWidthChanged(), DialogSpline::Angle1Changed(), DialogSpline::Angle2Changed(), DialogMove::angleChanged(), DialogRotation::angleChanged(), DialogInternalPath::beforeWidthChanged(), PatternPieceDialog::beforeWidthChanged(), IntersectCirclesDialog::Circle1RadiusChanged(), IntersectCirclesDialog::Circle2RadiusChanged(), IntersectCircleTangentDialog::CircleRadiusChanged(), DialogInternalPath::defaultWidthChanged(), PatternPieceDialog::defaultWidthChanged(), EvalFormula(), EditFormulaDialog::EvalFormula(), DialogArc::F1Changed(), DialogArcWithLength::F1Changed(), DialogEllipticalArc::F1Changed(), DialogArc::F2Changed(), DialogEllipticalArc::F2Changed(), initializeFormulaUi(), DialogSpline::Length1Changed(), DialogSpline::Length2Changed(), DialogArcWithLength::LengthChanged(), DialogMove::lengthChanged(), DialogEllipticalArc::Radius1Changed(), DialogEllipticalArc::Radius2Changed(), DialogArc::RadiusChanged(), DialogArcWithLength::RadiusChanged(), DialogEllipticalArc::RotationAngleChanged(), DialogMove::rotationChanged(), and ValFormulaChanged().
number
qint32 DialogTool::number protected
number number of handled objects
Definition at line 234 of file dialogtool.h.
Referenced by DialogAlongLine::ChosenObject(), DialogBisector::ChosenObject(), DialogCubicBezier::ChosenObject(), DialogCurveIntersectAxis::ChosenObject(), DialogHeight::ChosenObject(), DialogLine::ChosenObject(), DialogLineIntersect::ChosenObject(), DialogLineIntersectAxis::ChosenObject(), DialogMirrorByLine::ChosenObject(), DialogNormal::ChosenObject(), DialogPointFromArcAndTangent::ChosenObject(), DialogPointOfContact::ChosenObject(), DialogPointOfIntersectionArcs::ChosenObject(), DialogPointOfIntersectionCurves::ChosenObject(), DialogShoulderPoint::ChosenObject(), DialogSpline::ChosenObject(), DialogTriangle::ChosenObject(), DialogTrueDarts::ChosenObject(), IntersectCirclesDialog::ChosenObject(), IntersectCircleTangentDialog::ChosenObject(), PointIntersectXYDialog::ChosenObject(), DialogLine::DialogLine(), and DialogLineIntersect::DialogLineIntersect().
ok_Button
QPushButton* DialogTool::ok_Button protected
ok_Button button ok
Definition at line 199 of file dialogtool.h.
Referenced by CheckState(), EditFormulaDialog::CheckState(), AnchorPointDialog::CheckState(), DialogArc::CheckState(), DialogArcWithLength::CheckState(), DialogEllipticalArc::CheckState(), DialogLineIntersect::CheckState(), DialogMirrorByAxis::CheckState(), DialogMirrorByLine::CheckState(), DialogMove::CheckState(), DialogPointOfIntersectionCurves::CheckState(), DialogRotation::CheckState(), DialogSpline::CheckState(), DialogSplinePath::CheckState(), DialogTrueDarts::CheckState(), InsertNodesDialog::checkState(), IntersectCirclesDialog::CheckState(), IntersectCircleTangentDialog::CheckState(), DialogInternalPath::CheckState(), PatternPieceDialog::CheckState(), DialogCubicBezierPath::DialogCubicBezierPath(), DialogSplinePath::DialogSplinePath(), HistoryDialog::HistoryDialog(), initializeOkCancel(), DialogCubicBezierPath::NewItem(), and DialogSplinePath::NewItem().
okColor
const QColor DialogTool::okColor protected
Definition at line 219 of file dialogtool.h.
Referenced by DialogPointOfIntersectionArcs::ArcChanged(), DialogTrueDarts::CheckName(), AnchorPointDialog::CheckPieces(), AnchorPointDialog::CheckPoint(), DialogCubicBezierPath::currentPointChanged(), DialogSplinePath::currentPointChanged(), DialogPointOfIntersectionCurves::CurveChanged(), DialogSplinePath::DataPoint(), Eval(), PatternPieceDialog::grainlineAnchorChanged(), DialogInternalPath::NameChanged(), NamePointChanged(), PatternPieceDialog::patternLabelAnchorChanged(), PatternPieceDialog::PatternPieceDialog(), PatternPieceDialog::pieceLabelAnchorChanged(), PatternPieceDialog::pieceNameChanged(), DialogAlongLine::PointChanged(), DialogMirrorByAxis::pointChanged(), DialogMirrorByLine::pointChanged(), DialogRotation::pointChanged(), IntersectCirclesDialog::PointChanged(), IntersectCircleTangentDialog::PointChanged(), PointIntersectXYDialog::pointChanged(), DialogArc::pointNameChanged(), DialogArcWithLength::pointNameChanged(), DialogEllipticalArc::pointNameChanged(), DialogBisector::PointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogHeight::PointNameChanged(), DialogLine::PointNameChanged(), DialogLineIntersect::PointNameChanged(), DialogLineIntersectAxis::PointNameChanged(), DialogNormal::PointNameChanged(), DialogPointOfContact::PointNameChanged(), DialogShoulderPoint::PointNameChanged(), DialogSpline::PointNameChanged(), DialogTriangle::PointNameChanged(), DialogTrueDarts::PointNameChanged(), DialogMirrorByAxis::suffixChanged(), DialogMirrorByLine::suffixChanged(), DialogMove::suffixChanged(), DialogRotation::suffixChanged(), PatternPieceDialog::updateGrainlineValues(), PatternPieceDialog::updatePatternLabelValues(), PatternPieceDialog::updatePieceLabelValues(), and InsertNodesDialog::validatePieces().
plainTextEditFormula
QPlainTextEdit* DialogTool::plainTextEditFormula protected
plainTextEditFormula formula
Definition at line 208 of file dialogtool.h.
Referenced by DialogCurveIntersectAxis::AngleTextChanged(), DialogCurveIntersectAxis::closeEvent(), DialogCurveIntersectAxis::DeployAngleTextEdit(), DialogArc::DialogArc(), DialogArcWithLength::DialogArcWithLength(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogSpline::DialogSpline(), DialogSplinePath::DialogSplinePath(), EvalFormula(), EditFormulaDialog::EvalFormula(), initializeFormulaUi(), PatternPieceDialog::initializeSeamAllowanceTab(), DialogInternalPath::InitSeamAllowanceTab(), IntersectCirclesDialog::IntersectCirclesDialog(), IntersectCircleTangentDialog::IntersectCircleTangentDialog(), DialogCurveIntersectAxis::SaveData(), and DialogCurveIntersectAxis::SetAngle().
pointName
QString DialogTool::pointName protected
pointName name of point
Definition at line 231 of file dialogtool.h.
Referenced by getPointName(), NamePointChanged(), DialogAlongLine::SaveData(), DialogBisector::SaveData(), DialogCurveIntersectAxis::SaveData(), DialogCutArc::SaveData(), DialogCutSpline::SaveData(), DialogCutSplinePath::SaveData(), DialogEndLine::SaveData(), DialogHeight::SaveData(), DialogLineIntersect::SaveData(), DialogLineIntersectAxis::SaveData(), DialogNormal::SaveData(), DialogPointFromArcAndTangent::SaveData(), DialogPointOfContact::SaveData(), DialogPointOfIntersectionArcs::SaveData(), DialogPointOfIntersectionCurves::SaveData(), DialogShoulderPoint::SaveData(), DialogSinglePoint::SaveData(), DialogTriangle::SaveData(), IntersectCirclesDialog::SaveData(), IntersectCircleTangentDialog::SaveData(), PointIntersectXYDialog::SaveData(), DialogSinglePoint::SetData(), DialogAlongLine::SetPointName(), DialogBisector::SetPointName(), DialogCurveIntersectAxis::SetPointName(), DialogCutArc::SetPointName(), DialogCutSpline::SetPointName(), DialogCutSplinePath::SetPointName(), DialogEndLine::SetPointName(), DialogHeight::SetPointName(), DialogLineIntersect::SetPointName(), DialogLineIntersectAxis::SetPointName(), DialogNormal::SetPointName(), DialogPointFromArcAndTangent::SetPointName(), DialogPointOfContact::SetPointName(), DialogPointOfIntersectionArcs::SetPointName(), DialogPointOfIntersectionCurves::SetPointName(), DialogShoulderPoint::SetPointName(), DialogTriangle::SetPointName(), IntersectCirclesDialog::SetPointName(), IntersectCircleTangentDialog::SetPointName(), and PointIntersectXYDialog::setPointName().
prepare
bool DialogTool::prepare protected
prepare show if we prepare. Show dialog after finish working with visual part of tool
Definition at line 228 of file dialogtool.h.
Referenced by AddVisualization(), AnchorPointDialog::ChosenObject(), DialogAlongLine::ChosenObject(), DialogArc::ChosenObject(), DialogArcWithLength::ChosenObject(), DialogBisector::ChosenObject(), DialogCubicBezier::ChosenObject(), DialogCurveIntersectAxis::ChosenObject(), DialogCutArc::ChosenObject(), DialogCutSpline::ChosenObject(), DialogCutSplinePath::ChosenObject(), DialogEllipticalArc::ChosenObject(), DialogEndLine::ChosenObject(), DialogHeight::ChosenObject(), DialogLine::ChosenObject(), DialogLineIntersect::ChosenObject(), DialogLineIntersectAxis::ChosenObject(), DialogMirrorByAxis::ChosenObject(), DialogMirrorByLine::ChosenObject(), DialogMove::ChosenObject(), DialogNormal::ChosenObject(), DialogPointFromArcAndTangent::ChosenObject(), DialogPointOfContact::ChosenObject(), DialogPointOfIntersectionArcs::ChosenObject(), DialogPointOfIntersectionCurves::ChosenObject(), DialogRotation::ChosenObject(), DialogShoulderPoint::ChosenObject(), DialogSpline::ChosenObject(), DialogTriangle::ChosenObject(), DialogTrueDarts::ChosenObject(), IntersectCirclesDialog::ChosenObject(), IntersectCircleTangentDialog::ChosenObject(), DialogInternalPath::ChosenObject(), PatternPieceDialog::ChosenObject(), PointIntersectXYDialog::ChosenObject(), InsertNodesDialog::SelectedObject(), DialogCurveIntersectAxis::ShowDialog(), DialogEndLine::ShowDialog(), DialogLineIntersectAxis::ShowDialog(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), DialogRotation::ShowDialog(), DialogSpline::ShowDialog(), InsertNodesDialog::ShowDialog(), DialogInternalPath::ShowDialog(), and PatternPieceDialog::ShowDialog().
spinBoxAngle
QDoubleSpinBox* DialogTool::spinBoxAngle protected
spinBoxAngle spinbox for angle
Definition at line 205 of file dialogtool.h.
Referenced by ArrowDown(), ArrowLeft(), ArrowLeftDown(), ArrowLeftUp(), ArrowRight(), ArrowRightDown(), ArrowRightUp(), and ArrowUp().
timerFormula
QTimer* DialogTool::timerFormula protected
timerFormula timer for check formula
Definition at line 196 of file dialogtool.h.
Referenced by DialogCurveIntersectAxis::AngleTextChanged(), DialogEndLine::AngleTextChanged(), DialogLineIntersectAxis::AngleTextChanged(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogEndLine::DialogEndLine(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogTool(), FormulaChanged(), FormulaChangedPlainText(), and DialogEndLine::ShowDialog().
toolId
quint32 DialogTool::toolId protected
Definition at line 225 of file dialogtool.h.
Referenced by DialogInternalPath::editAfterSeamAllowanceWidth(), PatternPieceDialog::editAfterSeamAllowanceWidth(), DialogMove::editAngleFormula(), DialogRotation::editAngleFormula(), DialogInternalPath::editBeforeSeamAllowanceWidth(), PatternPieceDialog::editBeforeSeamAllowanceWidth(), DialogInternalPath::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editDefaultSeamAllowanceWidth(), DialogMove::editLengthFormula(), DialogMove::editRotationFormula(), FillCombo(), FillComboBoxCurves(), FillComboBoxSplines(), FillComboBoxSplinesPath(), DialogCurveIntersectAxis::FXAngle(), DialogEndLine::FXAngle(), DialogLineIntersectAxis::FXAngle(), DialogSpline::FXAngle1(), DialogSplinePath::FXAngle1(), DialogSpline::FXAngle2(), DialogSplinePath::FXAngle2(), IntersectCirclesDialog::FXCircle1Radius(), IntersectCirclesDialog::FXCircle2Radius(), IntersectCircleTangentDialog::FXCircleRadius(), DialogArc::FXF1(), DialogArcWithLength::FXF1(), DialogEllipticalArc::FXF1(), DialogArc::FXF2(), DialogEllipticalArc::FXF2(), DialogAlongLine::FXLength(), DialogArcWithLength::FXLength(), DialogBisector::FXLength(), DialogCutArc::FXLength(), DialogCutSpline::FXLength(), DialogCutSplinePath::FXLength(), DialogEndLine::FXLength(), DialogNormal::FXLength(), DialogShoulderPoint::FXLength(), DialogSpline::FXLength1(), DialogSplinePath::FXLength1(), DialogSpline::FXLength2(), DialogSplinePath::FXLength2(), DialogArc::FXRadius(), DialogArcWithLength::FXRadius(), DialogPointOfContact::FXRadius(), DialogEllipticalArc::FXRadius1(), DialogEllipticalArc::FXRadius2(), DialogEllipticalArc::FXRotationAngle(), GetToolId(), InsertNodesDialog::SelectedObject(), SetToolId(), PatternPieceDialog::showAnchorPoints(), PatternPieceDialog::showCustomSAContextMenu(), PatternPieceDialog::showInternalPathsContextMenu(), EditFormulaDialog::showMeasurements(), and EditFormulaDialog::showVariable().
vis
QPointer<Visualization> DialogTool::vis protected
Definition at line 236 of file dialogtool.h.
Referenced by AddVisualization(), AnchorPointDialog::AnchorPointDialog(), AnchorPointDialog::ChosenObject(), DialogAlongLine::ChosenObject(), DialogArc::ChosenObject(), DialogArcWithLength::ChosenObject(), DialogBisector::ChosenObject(), DialogCubicBezier::ChosenObject(), DialogCubicBezierPath::ChosenObject(), DialogCurveIntersectAxis::ChosenObject(), DialogCutArc::ChosenObject(), DialogCutSpline::ChosenObject(), DialogCutSplinePath::ChosenObject(), DialogEllipticalArc::ChosenObject(), DialogEndLine::ChosenObject(), DialogHeight::ChosenObject(), DialogLine::ChosenObject(), DialogLineIntersect::ChosenObject(), DialogLineIntersectAxis::ChosenObject(), DialogMirrorByAxis::ChosenObject(), DialogMirrorByLine::ChosenObject(), DialogMove::ChosenObject(), DialogNormal::ChosenObject(), DialogPointFromArcAndTangent::ChosenObject(), DialogPointOfContact::ChosenObject(), DialogPointOfIntersectionArcs::ChosenObject(), DialogPointOfIntersectionCurves::ChosenObject(), DialogRotation::ChosenObject(), DialogShoulderPoint::ChosenObject(), DialogSpline::ChosenObject(), DialogSplinePath::ChosenObject(), DialogTriangle::ChosenObject(), DialogTrueDarts::ChosenObject(), IntersectCirclesDialog::ChosenObject(), IntersectCircleTangentDialog::ChosenObject(), DialogInternalPath::ChosenObject(), PatternPieceDialog::ChosenObject(), PointIntersectXYDialog::ChosenObject(), DialogAlongLine::DialogAlongLine(), DialogArc::DialogArc(), DialogArcWithLength::DialogArcWithLength(), DialogBisector::DialogBisector(), DialogCubicBezier::DialogCubicBezier(), DialogCubicBezierPath::DialogCubicBezierPath(), DialogCurveIntersectAxis::DialogCurveIntersectAxis(), DialogCutArc::DialogCutArc(), DialogCutSpline::DialogCutSpline(), DialogCutSplinePath::DialogCutSplinePath(), DialogEllipticalArc::DialogEllipticalArc(), DialogEndLine::DialogEndLine(), DialogHeight::DialogHeight(), DialogInternalPath::DialogInternalPath(), DialogLine::DialogLine(), DialogLineIntersect::DialogLineIntersect(), DialogLineIntersectAxis::DialogLineIntersectAxis(), DialogMirrorByAxis::DialogMirrorByAxis(), DialogMirrorByLine::DialogMirrorByLine(), DialogMove::DialogMove(), DialogNormal::DialogNormal(), DialogPointFromArcAndTangent::DialogPointFromArcAndTangent(), DialogPointOfContact::DialogPointOfContact(), DialogPointOfIntersectionArcs::DialogPointOfIntersectionArcs(), DialogPointOfIntersectionCurves::DialogPointOfIntersectionCurves(), DialogRotation::DialogRotation(), DialogShoulderPoint::DialogShoulderPoint(), DialogSpline::DialogSpline(), DialogSplinePath::DialogSplinePath(), DialogTriangle::DialogTriangle(), DialogTrueDarts::DialogTrueDarts(), IntersectCirclesDialog::IntersectCirclesDialog(), IntersectCircleTangentDialog::IntersectCircleTangentDialog(), DialogInternalPath::ListChanged(), PatternPieceDialog::nodeListChanged(), DialogMove::originChanged(), PatternPieceDialog::PatternPieceDialog(), PointIntersectXYDialog::PointIntersectXYDialog(), DialogAlongLine::SaveData(), DialogArc::SaveData(), DialogArcWithLength::SaveData(), DialogBisector::SaveData(), DialogCubicBezier::SaveData(), DialogCubicBezierPath::SaveData(), DialogCurveIntersectAxis::SaveData(), DialogCutArc::SaveData(), DialogCutSpline::SaveData(), DialogCutSplinePath::SaveData(), DialogEllipticalArc::SaveData(), DialogEndLine::SaveData(), DialogHeight::SaveData(), DialogLine::SaveData(), DialogLineIntersect::SaveData(), DialogLineIntersectAxis::SaveData(), DialogMirrorByAxis::SaveData(), DialogMirrorByLine::SaveData(), DialogMove::SaveData(), DialogNormal::SaveData(), DialogPointFromArcAndTangent::SaveData(), DialogPointOfContact::SaveData(), DialogPointOfIntersectionArcs::SaveData(), DialogPointOfIntersectionCurves::SaveData(), DialogRotation::SaveData(), DialogShoulderPoint::SaveData(), DialogSpline::SaveData(), DialogSplinePath::SaveData(), DialogTriangle::SaveData(), DialogTrueDarts::SaveData(), IntersectCirclesDialog::SaveData(), IntersectCircleTangentDialog::SaveData(), PointIntersectXYDialog::SaveData(), DialogNormal::SetAngle(), DialogCurveIntersectAxis::SetAngle(), DialogEndLine::SetAngle(), DialogLineIntersectAxis::SetAngle(), DialogMove::SetAngle(), DialogRotation::SetAngle(), DialogCutArc::setArcId(), DialogPointFromArcAndTangent::SetArcId(), SetAssociatedTool(), DialogTriangle::SetAxisP1Id(), DialogTriangle::SetAxisP2Id(), DialogMirrorByAxis::setAxisType(), DialogCurveIntersectAxis::SetBasePointId(), DialogEndLine::SetBasePointId(), DialogHeight::SetBasePointId(), DialogLineIntersectAxis::SetBasePointId(), DialogArc::setCenter(), DialogArcWithLength::SetCenter(), DialogEllipticalArc::SetCenter(), DialogPointOfContact::setCenter(), IntersectCircleTangentDialog::SetCircleCenterId(), IntersectCircleTangentDialog::SetCircleRadius(), DialogPointFromArcAndTangent::setCirclesCrossPoint(), IntersectCirclesDialog::setCirclesCrossPoint(), IntersectCircleTangentDialog::setCirclesCrossPoint(), DialogPointOfIntersectionArcs::SetCrossArcPoint(), DialogCurveIntersectAxis::setCurveId(), DialogArc::setF1(), DialogArcWithLength::SetF1(), DialogEllipticalArc::SetF1(), DialogArc::setF2(), DialogEllipticalArc::SetF2(), DialogPointOfIntersectionArcs::SetFirstArcId(), DialogTrueDarts::SetFirstBasePointId(), IntersectCirclesDialog::SetFirstCircleCenterId(), IntersectCirclesDialog::SetFirstCircleRadius(), DialogPointOfIntersectionCurves::SetFirstCurveId(), DialogTrueDarts::SetFirstDartPointId(), DialogMirrorByLine::setFirstLinePointId(), DialogLine::setFirstPoint(), DialogPointOfContact::SetFirstPoint(), DialogAlongLine::SetFirstPointId(), DialogBisector::SetFirstPointId(), DialogLineIntersectAxis::SetFirstPointId(), DialogNormal::SetFirstPointId(), DialogTriangle::SetFirstPointId(), PointIntersectXYDialog::setFirstPointId(), DialogAlongLine::SetFormula(), DialogBisector::SetFormula(), DialogCutArc::SetFormula(), DialogCutSpline::SetFormula(), DialogCutSplinePath::SetFormula(), DialogEndLine::SetFormula(), DialogNormal::SetFormula(), DialogShoulderPoint::SetFormula(), DialogPointOfIntersectionCurves::SetHCrossPoint(), DialogArcWithLength::SetLength(), DialogMove::SetLength(), DialogAlongLine::setLineType(), DialogBisector::setLineType(), DialogCurveIntersectAxis::setLineType(), DialogEndLine::setLineType(), DialogHeight::setLineType(), DialogLine::setLineType(), DialogLineIntersectAxis::setLineType(), DialogNormal::setLineType(), DialogShoulderPoint::setLineType(), PointIntersectXYDialog::setLineType(), DialogAlongLine::setLineWeight(), DialogBisector::setLineWeight(), DialogCurveIntersectAxis::setLineWeight(), DialogEllipticalArc::setLineWeight(), DialogEndLine::setLineWeight(), DialogHeight::setLineWeight(), DialogLine::setLineWeight(), DialogLineIntersectAxis::setLineWeight(), DialogNormal::setLineWeight(), DialogShoulderPoint::setLineWeight(), DialogSpline::setLineWeight(), PointIntersectXYDialog::setLineWeight(), DialogMove::setOriginPointId(), DialogRotation::setOriginPointId(), DialogMirrorByAxis::setOriginPointId(), DialogShoulderPoint::SetP1Line(), DialogLineIntersect::SetP1Line1(), DialogLineIntersect::SetP1Line2(), DialogHeight::SetP1LineId(), DialogShoulderPoint::SetP2Line(), DialogLineIntersect::SetP2Line1(), DialogLineIntersect::SetP2Line2(), DialogHeight::SetP2LineId(), DialogShoulderPoint::SetP3(), DialogCubicBezierPath::SetPath(), DialogSplinePath::SetPath(), DialogInternalPath::SetPenType(), DialogInternalPath::SetPiecePath(), AnchorPointDialog::SetPointId(), DialogArc::setRadius(), DialogArcWithLength::SetRadius(), DialogPointOfContact::setRadius(), DialogEllipticalArc::SetRadius1(), DialogEllipticalArc::SetRadius2(), DialogMove::setRotation(), DialogEllipticalArc::SetRotationAngle(), DialogInternalPath::setSeamAllowanceWidthFormula(), PatternPieceDialog::setSeamAllowanceWidthFormula(), DialogPointOfIntersectionArcs::SetSecondArcId(), DialogTrueDarts::SetSecondBasePointId(), IntersectCirclesDialog::SetSecondCircleCenterId(), IntersectCirclesDialog::SetSecondCircleRadius(), DialogPointOfIntersectionCurves::SetSecondCurveId(), DialogTrueDarts::SetSecondDartPointId(), DialogMirrorByLine::setSecondLinePointId(), DialogLine::setSecondPoint(), DialogPointOfContact::SetSecondPoint(), DialogAlongLine::SetSecondPointId(), DialogBisector::SetSecondPointId(), DialogLineIntersectAxis::SetSecondPointId(), DialogNormal::SetSecondPointId(), DialogTriangle::SetSecondPointId(), PointIntersectXYDialog::setSecondPointId(), DialogMirrorByAxis::setSourceObjects(), DialogMirrorByLine::setSourceObjects(), DialogMove::setSourceObjects(), DialogRotation::setSourceObjects(), DialogCubicBezier::SetSpline(), DialogSpline::SetSpline(), DialogCutSpline::setSplineId(), DialogCutSplinePath::setSplinePathId(), DialogPointFromArcAndTangent::SetTangentPointId(), IntersectCircleTangentDialog::SetTangentPointId(), DialogTrueDarts::SetThirdDartPointId(), DialogBisector::SetThirdPointId(), DialogPointOfIntersectionCurves::SetVCrossPoint(), DialogCurveIntersectAxis::ShowDialog(), DialogEndLine::ShowDialog(), DialogLineIntersectAxis::ShowDialog(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), DialogRotation::ShowDialog(), DialogSpline::ShowDialog(), DialogInternalPath::ShowDialog(), PatternPieceDialog::ShowDialog(), AnchorPointDialog::ShowVisualization(), DialogInternalPath::ShowVisualization(), and ~DialogTool().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogtool.h
src/libs/vtools/dialogs/tools/dialogtool.cpp