Seamly2D: RowData Struct Reference
RowData Struct Reference
#include <history_dialog.h>
Public Attributes
quint32 id {NULL_ID}
QString icon {QString()}
QString name {QString()}
QString tool {QString()}
Detailed Description
Definition at line 67 of file history_dialog.h.
Member Data Documentation
icon
QString RowData::icon {QString()}
Definition at line 70 of file history_dialog.h.
Referenced by HistoryDialog::fillTable(), and HistoryDialog::record().
id
quint32 RowData::id {NULL_ID}
Definition at line 69 of file history_dialog.h.
Referenced by HistoryDialog::fillTable(), and HistoryDialog::record().
name
QString RowData::name {QString()}
Definition at line 71 of file history_dialog.h.
Referenced by HistoryDialog::fillTable(), and HistoryDialog::record().
tool
QString RowData::tool {QString()}
Definition at line 72 of file history_dialog.h.
Referenced by HistoryDialog::fillTable(), and HistoryDialog::record().
The documentation for this struct was generated from the following file:
src/app/seamly2d/dialogs/history_dialog.h