Seamly2D: DialogNewPattern Class Reference
DialogNewPattern Class Reference
#include <dialognewpattern.h>
Public Member Functions
DialogNewPattern (VContainer *data, const QString &patternPieceName, QWidget *parent=nullptr)
virtual ~DialogNewPattern ()
QString name () const
Unit PatternUnit () const
Protected Member Functions
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
Private Slots
void CheckState ()
Private Member Functions
void InitUnits ()
Private Attributes
Ui::DialogNewPattern * ui
VContainer * data
bool isInitialized
Detailed Description
Definition at line 66 of file dialognewpattern.h.
Constructor & Destructor Documentation
DialogNewPattern()
DialogNewPattern::DialogNewPattern (VContainer * data, const QString & patternPieceName, QWidget * parent = nullptr)
Definition at line 67 of file dialognewpattern.cpp.
References CheckState(), InitUnits(), qApp, and ui.
~DialogNewPattern()
DialogNewPattern::~DialogNewPattern () virtual
Definition at line 92 of file dialognewpattern.cpp.
References ui.
Member Function Documentation
CheckState
void DialogNewPattern::CheckState () private slot
Definition at line 105 of file dialognewpattern.cpp.
References SCASSERT, and ui.
Referenced by DialogNewPattern().
InitUnits()
void DialogNewPattern::InitUnits () private
Definition at line 140 of file dialognewpattern.cpp.
References Cm, Inch, Mm, qApp, ui, and UnitsToStr().
Referenced by DialogNewPattern().
name()
QString DialogNewPattern::name () const
Definition at line 155 of file dialognewpattern.cpp.
References ui.
Referenced by MainWindow::New().
PatternUnit()
Unit DialogNewPattern::PatternUnit () const
Definition at line 98 of file dialognewpattern.cpp.
References StrToUnits(), and ui.
Referenced by MainWindow::New().
showEvent()
void DialogNewPattern::showEvent (QShowEvent * event) protected virtual
Definition at line 119 of file dialognewpattern.cpp.
References isInitialized.
Member Data Documentation
data
VContainer* DialogNewPattern::data private
Definition at line 81 of file dialognewpattern.h.
isInitialized
bool DialogNewPattern::isInitialized private
Definition at line 82 of file dialognewpattern.h.
Referenced by showEvent().
ui
Ui::DialogNewPattern* DialogNewPattern::ui private
Definition at line 80 of file dialognewpattern.h.
Referenced by CheckState(), DialogNewPattern(), InitUnits(), name(), PatternUnit(), and ~DialogNewPattern().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/dialognewpattern.h
src/app/seamly2d/dialogs/dialognewpattern.cpp