Seamly2D: TST_VArc Class Reference
TST_VArc Class Reference
#include <tst_varc.h>
Public Member Functions
TST_VArc (QObject *parent=nullptr)
Private Slots
void CompareTwoWays ()
void NegativeArc ()
void TestGetPoints_data ()
void TestGetPoints ()
void TestRotation_data ()
void TestRotation ()
void TestFlip_data ()
void TestFlip ()
Detailed Description
Definition at line 57 of file tst_varc.h.
Constructor & Destructor Documentation
TST_VArc()
TST_VArc::TST_VArc (QObject * parent = nullptr) explicit
Definition at line 60 of file tst_varc.cpp.
Member Function Documentation
CompareTwoWays
void TST_VArc::CompareTwoWays () private slot
Definition at line 66 of file tst_varc.cpp.
References VAbstractArc::GetEndAngle(), and VArc::GetLength().
NegativeArc
void TST_VArc::NegativeArc () private slot
Definition at line 89 of file tst_varc.cpp.
References VAbstractArc::GetEndAngle(), and VArc::GetLength().
TestFlip
void TST_VArc::TestFlip () private slot
Definition at line 322 of file tst_varc.cpp.
References VAbstractArc::AngleArc(), VArc::Flip(), VArc::GetLength(), VArc::GetRadius(), VAbstractArc::IsFlipped(), and VGObject::name().
TestFlip_data
void TST_VArc::TestFlip_data () private slot
Definition at line 274 of file tst_varc.cpp.
TestGetPoints
void TST_VArc::TestGetPoints () private slot
Definition at line 191 of file tst_varc.cpp.
References VAbstractArc::AngleArc(), VArc::getPoints(), VAbstractPiece::sumTrapezoids(), and VFuzzyComparePossibleNulls().
TestGetPoints_data
void TST_VArc::TestGetPoints_data () private slot
Definition at line 104 of file tst_varc.cpp.
TestRotation
void TST_VArc::TestRotation () private slot
Definition at line 253 of file tst_varc.cpp.
References VAbstractArc::AngleArc(), VArc::GetLength(), VArc::GetRadius(), VGObject::name(), and VArc::Rotate().
TestRotation_data
void TST_VArc::TestRotation_data () private slot
Definition at line 239 of file tst_varc.cpp.
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_varc.h
src/test/Seamly2DTest/tst_varc.cpp