Seamly2D: VSpline Class Reference
VSpline Class Reference
VSpline class that implements the spline.
#include <vspline.h>
Public Member Functions
VSpline ()
VSpline default constructor.
VSpline (const VSpline &spline)
VSpline constructor.
VSpline (const VPointF &p1, const VPointF &p4, qreal angle1, qreal angle2, qreal kAsm1, qreal kAsm2, qreal kCurve, quint32 idObject=0, Draw mode=Draw::Calculation)
VSpline constructor.
VSpline (const VPointF &p1, const QPointF &p2, const QPointF &p3, const VPointF &p4, quint32 idObject=0, Draw mode=Draw::Calculation)
VSpline constructor.
VSpline (const VPointF &p1, const VPointF &p4, qreal angle1, const QString &angle1Formula, qreal angle2, const QString &angle2Formula, qreal c1Length, const QString &c1LengthFormula, qreal c2Length, const QString &c2LengthFormula, quint32 idObject=0, Draw mode=Draw::Calculation)
VSpline constructor.
VSpline Rotate (const QPointF &originPoint, qreal degrees, const QString &prefix=QString()) const
VSpline Flip (const QLineF &axis, const QString &prefix=QString()) const
VSpline Move (qreal length, qreal angle, const QString &prefix=QString()) const
virtual ~VSpline ()
VSpline & operator= (const VSpline &spline)
void Swap (VSpline &spline) Q_DECL_NOTHROW
virtual VPointF GetP1 () const Q_DECL_OVERRIDE
GetP1 return first spline point.
void SetP1 (const VPointF &p)
virtual VPointF GetP2 () const Q_DECL_OVERRIDE
GetP2 return first control point.
virtual VPointF GetP3 () const Q_DECL_OVERRIDE
GetP3 return second control point.
virtual VPointF GetP4 () const Q_DECL_OVERRIDE
GetP4 return last spline point.
void SetP4 (const VPointF &p)
virtual qreal GetStartAngle () const Q_DECL_OVERRIDE
GetAngle1 return first angle control line.
virtual qreal GetEndAngle () const Q_DECL_OVERRIDE
GetAngle2 return second angle control line.
QString GetStartAngleFormula () const
QString GetEndAngleFormula () const
void SetStartAngle (qreal angle, const QString &formula)
void SetEndAngle (qreal angle, const QString &formula)
virtual qreal GetC1Length () const Q_DECL_OVERRIDE
virtual qreal GetC2Length () const Q_DECL_OVERRIDE
QString GetC1LengthFormula () const
QString GetC2LengthFormula () const
void SetC1Length (qreal length, const QString &formula)
void SetC2Length (qreal length, const QString &formula)
virtual qreal GetLength () const Q_DECL_OVERRIDE
GetLength return length of spline.
qreal GetKasm1 () const
GetKasm1 return coefficient of length first control line.
qreal GetKasm2 () const
GetKasm2 return coefficient of length second control line.
qreal GetKcurve () const
GetKcurve return coefficient of curvature spline.
QPointF CutSpline (qreal length, VSpline &spl1, VSpline &spl2) const
virtual QVector< QPointF > getPoints () const Q_DECL_OVERRIDE
GetPoints return list with spline points.
qreal ParamT (const QPointF &pBt) const
VSpline::ParamT calculate t coeffient that reprezent point on curve.
QPointF CutSpline (qreal length, QPointF &spl1p2, QPointF &spl1p3, QPointF &spl2p2, QPointF &spl2p3) const
CutSpline cut spline.
Public Member Functions inherited from VAbstractCubicBezier
VAbstractCubicBezier (const GOType &type, const quint32 &idObject=null_id, const Draw &mode=Draw::Calculation)
VAbstractCubicBezier (const VAbstractCubicBezier &curve)
VAbstractCubicBezier & operator= (const VAbstractCubicBezier &curve)
virtual ~VAbstractCubicBezier ()
QPointF CutSpline (qreal length, QPointF &spl1p2, QPointF &spl1p3, QPointF &spl2p2, QPointF &spl2p3) const
CutSpline cut spline.
virtual QString NameForHistory (const QString &toolName) const Q_DECL_OVERRIDE
qreal GetParmT (qreal length) const
qreal LengthT (qreal t) const
Public Member Functions inherited from VAbstractBezier
VAbstractBezier (const GOType &type, const quint32 &idObject=null_id, const Draw &mode=Draw::Calculation)
VAbstractBezier (const VAbstractBezier &curve)
VAbstractBezier & operator= (const VAbstractBezier &curve)
virtual ~VAbstractBezier ()
Public Member Functions inherited from VAbstractCurve
VAbstractCurve (const GOType &type, const quint32 &idObject=null_id, const Draw &mode=Draw::Calculation)
VAbstractCurve (const VAbstractCurve &curve)
virtual ~VAbstractCurve () Q_DECL_OVERRIDE
VAbstractCurve & operator= (const VAbstractCurve &curve)
void Swap (VAbstractCurve &curve) Q_DECL_NOTHROW
QVector< QPointF > GetSegmentPoints (const QPointF &begin, const QPointF &end, bool reverse=false) const
virtual QPainterPath GetPath () const
qreal GetLengthByPoint (const QPointF &point) const
virtual QVector< QPointF > IntersectLine (const QLineF &line) const
IntersectLine return list of points for real intersection with line.
virtual bool IsIntersectLine (const QLineF &line) const
bool isPointOnCurve (const QPointF &p) const
quint32 GetDuplicate () const
void SetDuplicate (quint32 number)
QString getLineColor () const
void setLineColor (const QString &color)
QString GetPenStyle () const
void SetPenStyle (const QString &penStyle)
QString getLineWeight () const
getLineWeight return weight of the lines
void setLineWeight (const QString &lineWeight)
setLineWeight set weight of the lines
QPointF getFirstPoint ()
QPointF getLastPoint ()
virtual QVector< DirectionArrow > DirectionArrows () const
Public Member Functions inherited from VGObject
VGObject ()
VGObject default constructor.
VGObject (const GOType &type, const quint32 &idObject=0, const Draw &mode=Draw::Calculation)
VGObject constructor.
VGObject (const VGObject &obj)
VGObject copy constructor.
virtual ~VGObject ()
VGObject & operator= (const VGObject &obj)
operator = assignment operator.
void Swap (VGObject &obj) Q_DECL_NOTHROW
quint32 getIdObject () const
getIdObject return parent id.
void setIdObject (const quint32 &value)
setIdObject set parent id.
virtual QString name () const
name return name graphical object.
void setName (const QString &name)
setName set name graphical object.
Draw getMode () const
getMode return mode creation.
void setMode (const Draw &value)
setMode set mode creation.
GOType getType () const
getType return object type.
void setType (const GOType &type)
quint32 id () const
id return id object.
virtual void setId (const quint32 &id)
setId set id object.
quint32 getIdTool () const
Static Public Member Functions
static QVector< QPointF > SplinePoints (const QPointF &p1, const QPointF &p4, qreal angle1, qreal angle2, qreal kAsm1, qreal kAsm2, qreal kCurve)
SplinePoints return list with spline points.
Static Public Member Functions inherited from VAbstractCurve
static QVector< QPointF > GetSegmentPoints (const QVector< QPointF > &points, const QPointF &begin, const QPointF &end, bool reverse=false)
static bool isPointOnCurve (const QVector< QPointF > &points, const QPointF &p)
static qreal PathLength (const QVector< QPointF > &path)
static QVector< QPointF > CurveIntersectLine (const QVector< QPointF > &points, const QLineF &line)
static QPainterPath ShowDirection (const QVector< DirectionArrow > &arrows, qreal width)
Static Public Member Functions inherited from VGObject
static QLineF BuildLine (const QPointF &p1, const qreal &length, const qreal &angle)
static QPointF BuildRay (const QPointF &firstPoint, const qreal &angle, const QRectF &scRect)
static QLineF BuildAxis (const QPointF &p, const qreal &angle, const QRectF &scRect)
static QLineF BuildAxis (const QPointF &p1, const QPointF &p2, const QRectF &scRect)
static int ContactPoints (const QPointF &p, const QPointF &center, qreal radius, QPointF &p1, QPointF &p2)
static QPointF LineIntersectRect (const QRectF &rec, const QLineF &line)
LineIntersectRect find point intersection line and rect.
static int IntersectionCircles (const QPointF &c1, double r1, const QPointF &c2, double r2, QPointF &p1, QPointF &p2)
static qint32 LineIntersectCircle (const QPointF &center, qreal radius, const QLineF &line, QPointF &p1, QPointF &p2)
LineIntersectCircle find point intersection line and circle.
static QPointF ClosestPoint (const QLineF &line, const QPointF &point)
ClosestPoint find point projection of point onto line.
static QPointF addVector (const QPointF &p, const QPointF &p1, const QPointF &p2, qreal k)
static void LineCoefficients (const QLineF &line, qreal *a, qreal *b, qreal *c)
LineCoefficients coefficient for equation of segment. Segment equestion ax+by+c=0.
static bool IsPointOnLineSegment (const QPointF &t, const QPointF &p1, const QPointF &p2)
IsPointOnLineSegment Check if the point is on the line segment.
static bool IsPointOnLineviaPDP (const QPointF &t, const QPointF &p1, const QPointF &p2)
IsPointOnLineviaPDP use the perp dot product (PDP) way.
template<typename T >
static QVector< T > GetReversePoints (const QVector< T > &points)
GetReversePoint return revers container of points.
static int GetLengthContour (const QVector< QPointF > &contour, const QVector< QPointF > &newPoints)
GetLengthContour return length of contour.
Protected Member Functions
virtual QPointF GetControlPoint1 () const Q_DECL_OVERRIDE
virtual QPointF GetControlPoint2 () const Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractCubicBezier
virtual void CreateName () Q_DECL_OVERRIDE
Private Member Functions
QVector< qreal > CalcT (qreal curveCoord1, qreal curveCoord2, qreal curveCoord3, qreal curveCoord4, qreal pointCoord) const
Static Private Member Functions
static qint32 Cubic (QVector< qreal > &x, qreal a, qreal b, qreal c)
Cubic Cubic equation solution. Real coefficients case.
static int Sign (long double ld)
Private Attributes
QSharedDataPointer< VSplineData > d
Additional Inherited Members
Static Public Attributes inherited from VAbstractCurve
static const qreal lengthCurveDirectionArrow = 14
Static Public Attributes inherited from VGObject
static const double accuracyPointOnLine = (0.1555 / 25.4) * 96.0
Static Protected Member Functions inherited from VAbstractCubicBezier
static qreal CalcSqDistance (qreal x1, qreal y1, qreal x2, qreal y2)
CalcSqDistance calculate squared distance.
static void PointBezier_r (qreal x1, qreal y1, qreal x2, qreal y2, qreal x3, qreal y3, qreal x4, qreal y4, qint16 level, QVector< qreal > &px, QVector< qreal > &py)
PointBezier_r find spline point using four point of spline.
static QVector< QPointF > GetCubicBezierPoints (const QPointF &p1, const QPointF &p2, const QPointF &p3, const QPointF &p4)
GetCubicBezierPoints return list with cubic bezier curve points.
static qreal LengthBezier (const QPointF &p1, const QPointF &p2, const QPointF &p3, const QPointF &p4)
LengthBezier return spline length using 4 spline point.
Static Protected Member Functions inherited from VGObject
static QTransform flipTransform (const QLineF &axis)
Detailed Description
VSpline class that implements the spline.
Definition at line 74 of file vspline.h.
Constructor & Destructor Documentation
VSpline() [1/5]
VSpline::VSpline ()
VSpline default constructor.
Definition at line 71 of file vspline.cpp.
References Spline.
Referenced by CutSpline().
VSpline() [2/5]
VSpline::VSpline (const VSpline & spline)
VSpline constructor.
Parameters
spline spline from which the copy.
Definition at line 80 of file vspline.cpp.
VSpline() [3/5]
VSpline::VSpline (const VPointF & p1, const VPointF & p4, qreal angle1, qreal angle2, qreal kAsm1, qreal kAsm2, qreal kCurve, quint32 idObject = 0, Draw mode = Draw::Calculation)
VSpline constructor.
Parameters
p1 first point spline.
p4 last point spline.
angle1 angle from first point to first control point.
angle2 angle from second point to second control point.
kCurve coefficient of curvature spline.
kAsm1 coefficient of length first control line.
kAsm2 coefficient of length second control line.
Definition at line 95 of file vspline.cpp.
References VAbstractCubicBezier::CreateName(), and Spline.
VSpline() [4/5]
VSpline::VSpline (const VPointF & p1, const QPointF & p2, const QPointF & p3, const VPointF & p4, quint32 idObject = 0, Draw mode = Draw::Calculation)
VSpline constructor.
Parameters
p1 first point spline.
p2 first control point.
p3 second control point.
p4 second point spline.
Definition at line 111 of file vspline.cpp.
References VAbstractCubicBezier::CreateName(), and Spline.
VSpline() [5/5]
VSpline::VSpline (const VPointF & p1, const VPointF & p4, qreal angle1, const QString & angle1Formula, qreal angle2, const QString & angle2Formula, qreal c1Length, const QString & c1LengthFormula, qreal c2Length, const QString & c2LengthFormula, quint32 idObject = 0, Draw mode = Draw::Calculation)
VSpline constructor.
Parameters
p1 first point spline.
p4 first control point.
angle1 angle from first point to first control point.
angle1Formula formula angle from first point to first control point.
angle2 angle from second point to second control point.
angle2Formula formula angle from second point to second control point.
c1Length length from first point to first control point.
c1LengthFormula formula length from first point to first control point.
c2Length length from second point to first control point.
c2LengthFormula formula length from second point to first control point.
Definition at line 133 of file vspline.cpp.
References VAbstractCubicBezier::CreateName(), and Spline.
~VSpline()
VSpline::~VSpline () virtual
Definition at line 195 of file vspline.cpp.
Member Function Documentation
CalcT()
QVector< qreal > VSpline::CalcT (qreal curveCoord1, qreal curveCoord2, qreal curveCoord3, qreal curveCoord4, qreal pointCoord) const private
Definition at line 508 of file vspline.cpp.
References Cubic(), and d.
Referenced by ParamT().
Cubic()
qint32 VSpline::Cubic (QVector< qreal > & x, qreal a, qreal b, qreal c) static private
Cubic Cubic equation solution. Real coefficients case.
This method use method Vieta-Cardano for eval cubic equations. Cubic equation write in form x3+a*x2+b*x+c=0.
Output: 3 real roots -> then x is filled with them; 1 real + 2 complex -> x[0] is real, x[1] is real part of complex roots, x[2] - non-negative imaginary part.
Parameters
x solution array (size 3).
a coefficient
b coefficient
c coefficient
Returns
3 - 3 real roots; 1 - 1 real root + 2 complex; 2 - 1 real root + complex roots imaginary part is zero (i.e. 2 real roots).
Definition at line 477 of file vspline.cpp.
References M_2PI, and Sign().
Referenced by CalcT().
CutSpline() [1/2]
QPointF VAbstractCubicBezier::CutSpline
CutSpline cut spline.
Parameters
length length first spline
spl1p2 second point of first spline
spl1p3 third point of first spline
spl2p2 second point of second spline
spl2p3 third point of second spline
Returns
point of cutting. This point is forth point of first spline and first point of second spline.
Definition at line 80 of file vabstractcubicbezier.cpp.
Referenced by CutSpline().
CutSpline() [2/2]
QPointF VSpline::CutSpline (qreal length, VSpline & spl1, VSpline & spl2) const
Definition at line 210 of file vspline.cpp.
References CutSpline(), GetP1(), GetP4(), and VSpline().
Referenced by VAbstractCubicBezierPath::CutSplinePath(), and TST_VSpline::TestLengthByPoint_data().
Flip()
VSpline VSpline::Flip (const QLineF & axis, const QString & prefix = QString()) const
Definition at line 161 of file vspline.cpp.
References VPointF::Flip(), VPointF::FlipPF(), VAbstractCurve::getLineColor(), VAbstractCurve::getLineWeight(), GetP1(), GetP2(), GetP3(), GetP4(), VAbstractCurve::GetPenStyle(), VGObject::name(), VAbstractCurve::setLineColor(), VAbstractCurve::setLineWeight(), VGObject::setName(), and VAbstractCurve::SetPenStyle().
Referenced by VSplinePath::Flip(), and TST_VSpline::TestFlip().
GetC1Length()
qreal VSpline::GetC1Length () const virtual
Implements VAbstractBezier.
Definition at line 379 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), TST_VSpline::CompareSplines(), TST_VSpline::CompareThreeWays(), VAbstractSpline::CorrectedSpline(), VisToolSplinePath::Creating(), VToolCutSplinePath::CutSplinePath(), VSplinePath::Flip(), VCubicBezierPath::GetC1Length(), VCubicBezierPath::GetSplinePath(), VSplinePath::Move(), VSplinePath::Rotate(), TST_VSpline::TestFlip(), VToolSplinePath::UpdateControlPoints(), QT_WARNING_POP::UpdateNodeSplinePath(), VCurveCLength::VCurveCLength(), and VSplinePath::VSplinePath().
GetC1LengthFormula()
QString VSpline::GetC1LengthFormula () const
Definition at line 391 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), VAbstractSpline::CorrectedSpline(), VisToolSplinePath::Creating(), VToolCutSplinePath::CutSplinePath(), MoveSpline::Do(), VSplinePath::Flip(), VCubicBezierPath::GetSplinePath(), VSplinePath::Move(), VSplinePath::Rotate(), DialogSpline::SetSpline(), VToolSpline::SetSplineAttributes(), DialogSpline::ShowDialog(), VToolSplinePath::UpdateControlPoints(), QT_WARNING_POP::UpdateNodeSplinePath(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), VSplinePath::VSplinePath(), and VToolSplinePath::VToolSplinePath().
GetC2Length()
qreal VSpline::GetC2Length () const virtual
Implements VAbstractBezier.
Definition at line 385 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), TST_VSpline::CompareSplines(), TST_VSpline::CompareThreeWays(), VAbstractSpline::CorrectedSpline(), VisToolSplinePath::Creating(), VToolCutSplinePath::CutSplinePath(), VSplinePath::Flip(), VCubicBezierPath::GetC2Length(), VCubicBezierPath::GetSplinePath(), VSplinePath::Move(), VSplinePath::Rotate(), TST_VSpline::TestFlip(), VToolSplinePath::UpdateControlPoints(), QT_WARNING_POP::UpdateNodeSplinePath(), VCurveCLength::VCurveCLength(), and VSplinePath::VSplinePath().
GetC2LengthFormula()
QString VSpline::GetC2LengthFormula () const
Definition at line 397 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), VAbstractSpline::CorrectedSpline(), VisToolSplinePath::Creating(), VToolCutSplinePath::CutSplinePath(), MoveSpline::Do(), VSplinePath::Flip(), VCubicBezierPath::GetSplinePath(), VSplinePath::Move(), VSplinePath::Rotate(), DialogSpline::SetSpline(), VToolSpline::SetSplineAttributes(), DialogSpline::ShowDialog(), VToolSplinePath::UpdateControlPoints(), QT_WARNING_POP::UpdateNodeSplinePath(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), VSplinePath::VSplinePath(), and VToolSplinePath::VToolSplinePath().
GetControlPoint1()
QPointF VSpline::GetControlPoint1 () const protected virtual
Implements VAbstractCubicBezier.
Definition at line 580 of file vspline.cpp.
References GetP2().
GetControlPoint2()
QPointF VSpline::GetControlPoint2 () const protected virtual
Implements VAbstractCubicBezier.
Definition at line 586 of file vspline.cpp.
References GetP3().
GetEndAngle()
qreal VSpline::GetEndAngle () const virtual
GetAngle2 return second angle control line.
Returns
angle.
Implements VAbstractCurve.
Definition at line 347 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), TST_VSpline::CompareSplines(), TST_VSpline::CompareThreeWays(), VAbstractSpline::CorrectedSpline(), VToolCutSplinePath::CutSplinePath(), VSplinePath::Flip(), VCubicBezierPath::GetEndAngle(), VCubicBezierPath::GetSplinePath(), VSplinePath::Move(), DialogSpline::PointNameChanged(), VSplinePath::Rotate(), DialogSpline::SaveData(), DialogSpline::SetSpline(), VToolSplinePath::UpdateControlPoints(), QT_WARNING_POP::UpdateNodeSplinePath(), and VCurveAngle::VCurveAngle().
GetEndAngleFormula()
QString VSpline::GetEndAngleFormula () const
Definition at line 359 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), VAbstractSpline::CorrectedSpline(), VToolCutSplinePath::CutSplinePath(), MoveSpline::Do(), VSplinePath::Flip(), VCubicBezierPath::GetSplinePath(), VSplinePath::Move(), VSplinePath::Rotate(), DialogSpline::SetSpline(), VToolSpline::SetSplineAttributes(), DialogSpline::ShowDialog(), VToolSplinePath::UpdateControlPoints(), QT_WARNING_POP::UpdateNodeSplinePath(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), VSplinePath::VSplinePath(), and VToolSplinePath::VToolSplinePath().
GetKasm1()
qreal VSpline::GetKasm1 () const
GetKasm1 return coefficient of length first control line.
Returns
coefficient.
Definition at line 421 of file vspline.cpp.
References d, VSplineData::GetL(), and GetP2().
Referenced by TST_VSpline::CompareSplines(), VSplinePath::GetFSplinePath(), DialogSpline::PointNameChanged(), DialogSpline::SaveData(), and DialogSpline::SetSpline().
GetKasm2()
qreal VSpline::GetKasm2 () const
GetKasm2 return coefficient of length second control line.
Returns
coefficient.
Definition at line 432 of file vspline.cpp.
References d, VSplineData::GetL(), and GetP3().
Referenced by TST_VSpline::CompareSplines(), VSplinePath::GetFSplinePath(), DialogSpline::PointNameChanged(), DialogSpline::SaveData(), and DialogSpline::SetSpline().
GetKcurve()
qreal VSpline::GetKcurve () const
GetKcurve return coefficient of curvature spline.
Returns
coefficient
Definition at line 443 of file vspline.cpp.
References d.
Referenced by TST_VSpline::CompareSplines(), DialogSpline::PointNameChanged(), DialogSpline::SaveData(), and DialogSpline::SetSpline().
GetLength()
qreal VSpline::GetLength () const virtual
GetLength return length of spline.
Returns
length.
Implements VAbstractCurve.
Definition at line 203 of file vspline.cpp.
References GetP1(), GetP2(), GetP3(), GetP4(), and VAbstractCubicBezier::LengthBezier().
Referenced by TST_VSpline::CompareSplines(), VAbstractCubicBezierPath::CutSplinePath(), VAbstractCubicBezierPath::GetLength(), VToolCutSpline::makeToolTip(), TST_VSpline::TestFlip(), TST_VSpline::TestLengthByPoint_data(), TST_VSpline::TestParametrT(), and VCurveLength::VCurveLength().
GetP1()
VPointF VSpline::GetP1 () const virtual
GetP1 return first spline point.
Returns
first point.
Implements VAbstractCubicBezier.
Definition at line 281 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), TST_VSpline::CompareSplines(), TST_VSpline::CompareThreeWays(), VAbstractSpline::CorrectedSpline(), VToolSpline::Create(), VisToolSplinePath::Creating(), CutSpline(), MoveSpline::Do(), Flip(), VSplinePath::Flip(), GetLength(), getPoints(), VCubicBezierPath::GetSplinePath(), VToolSplinePath::mouseMoveEvent(), Move(), VSplinePath::Move(), ParamT(), DialogSpline::PointNameChanged(), VisToolCubicBezierPath::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), Rotate(), VSplinePath::Rotate(), DialogSpline::SetSpline(), VToolSpline::SetSplineAttributes(), QT_WARNING_POP::UpdateNodeSplinePath(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), and VToolSplinePath::VToolSplinePath().
GetP2()
VPointF VSpline::GetP2 () const virtual
GetP2 return first control point.
Returns
first control point.
Implements VAbstractCubicBezier.
Definition at line 297 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), TST_VSpline::CompareSplines(), TST_VSpline::CompareThreeWays(), VisToolSplinePath::Creating(), Flip(), GetControlPoint1(), GetKasm1(), GetLength(), getPoints(), VToolSplinePath::mouseMoveEvent(), Move(), ParamT(), VisToolCubicBezierPath::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), Rotate(), VToolSpline::SaveDialog(), VToolSplinePath::SaveDialog(), QT_WARNING_POP::UpdateNodeSplinePath(), and VToolSplinePath::VToolSplinePath().
GetP3()
VPointF VSpline::GetP3 () const virtual
GetP3 return second control point.
Returns
second control point.
Implements VAbstractCubicBezier.
Definition at line 309 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), TST_VSpline::CompareSplines(), TST_VSpline::CompareThreeWays(), Flip(), GetControlPoint2(), GetKasm2(), GetLength(), getPoints(), VToolSplinePath::mouseMoveEvent(), Move(), ParamT(), VisToolCubicBezierPath::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), Rotate(), VToolSpline::SaveDialog(), VToolSplinePath::SaveDialog(), QT_WARNING_POP::UpdateNodeSplinePath(), and VToolSplinePath::VToolSplinePath().
GetP4()
VPointF VSpline::GetP4 () const virtual
GetP4 return last spline point.
Returns
.
Implements VAbstractCubicBezier.
Definition at line 321 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), TST_VSpline::CompareSplines(), TST_VSpline::CompareThreeWays(), VAbstractSpline::CorrectedSpline(), VToolSpline::Create(), CutSpline(), MoveSpline::Do(), Flip(), VSplinePath::Flip(), GetLength(), getPoints(), VCubicBezierPath::GetSplinePath(), VToolSplinePath::mouseMoveEvent(), Move(), VSplinePath::Move(), ParamT(), DialogSpline::PointNameChanged(), VisToolCubicBezierPath::RefreshGeometry(), VisToolSplinePath::RefreshGeometry(), Rotate(), VSplinePath::Rotate(), DialogSpline::SetSpline(), VToolSpline::SetSplineAttributes(), QT_WARNING_POP::UpdateNodeSplinePath(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), and VToolSplinePath::VToolSplinePath().
getPoints()
QVector< QPointF > VSpline::getPoints () const virtual
GetPoints return list with spline points.
Returns
list of points.
Implements VAbstractCurve.
Definition at line 228 of file vspline.cpp.
References VAbstractCubicBezier::GetCubicBezierPoints(), GetP1(), GetP2(), GetP3(), and GetP4().
Referenced by TST_VSpline::CompareSplines(), VAbstractCubicBezierPath::getPoints(), and VArc::getPoints().
GetStartAngle()
qreal VSpline::GetStartAngle () const virtual
GetAngle1 return first angle control line.
Returns
angle.
Implements VAbstractCurve.
Definition at line 337 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), TST_VSpline::CompareSplines(), TST_VSpline::CompareThreeWays(), VAbstractSpline::CorrectedSpline(), VisToolSplinePath::Creating(), VToolCutSplinePath::CutSplinePath(), VSplinePath::Flip(), VCubicBezierPath::GetSplinePath(), VCubicBezierPath::GetStartAngle(), VSplinePath::Move(), DialogSpline::PointNameChanged(), VSplinePath::Rotate(), DialogSpline::SaveData(), DialogSpline::SetSpline(), VToolSplinePath::UpdateControlPoints(), QT_WARNING_POP::UpdateNodeSplinePath(), and VCurveAngle::VCurveAngle().
GetStartAngleFormula()
QString VSpline::GetStartAngleFormula () const
Definition at line 353 of file vspline.cpp.
References d.
Referenced by QT_WARNING_POP::AddNodeSplinePath(), VAbstractSpline::CorrectedSpline(), VisToolSplinePath::Creating(), VToolCutSplinePath::CutSplinePath(), MoveSpline::Do(), VSplinePath::Flip(), VCubicBezierPath::GetSplinePath(), VSplinePath::Move(), VSplinePath::Rotate(), DialogSpline::SetSpline(), VToolSpline::SetSplineAttributes(), DialogSpline::ShowDialog(), VToolSplinePath::UpdateControlPoints(), QT_WARNING_POP::UpdateNodeSplinePath(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), VSplinePath::VSplinePath(), and VToolSplinePath::VToolSplinePath().
Move()
VSpline VSpline::Move (qreal length, qreal angle, const QString & prefix = QString()) const
Definition at line 178 of file vspline.cpp.
References VAbstractCurve::getLineColor(), VAbstractCurve::getLineWeight(), GetP1(), GetP2(), GetP3(), GetP4(), VAbstractCurve::GetPenStyle(), VPointF::Move(), VPointF::MovePF(), VGObject::name(), VAbstractCurve::setLineColor(), VAbstractCurve::setLineWeight(), VGObject::setName(), and VAbstractCurve::SetPenStyle().
Referenced by VSplinePath::Move().
operator=()
VSpline & VSpline::operator= (const VSpline & spline)
Definition at line 265 of file vspline.cpp.
References d, and VAbstractCubicBezier::operator=().
ParamT()
qreal VSpline::ParamT (const QPointF & pBt) const
VSpline::ParamT calculate t coeffient that reprezent point on curve.
Each point that belongs to Cubic Bzier curve can be shown by coefficient in interval [0; 1].
Parameters
pBt point on curve
Returns
t coeffient that reprezent this point on curve. Return -1 if point doesn't belongs to curve.
Definition at line 540 of file vspline.cpp.
References CalcT(), GetP1(), GetP2(), GetP3(), GetP4(), VPointF::x(), and VPointF::y().
Referenced by VToolSpline::mouseMoveEvent(), VToolSplinePath::mouseMoveEvent(), and VAbstractCubicBezierPath::Segment().
Rotate()
VSpline VSpline::Rotate (const QPointF & originPoint, qreal degrees, const QString & prefix = QString()) const
Definition at line 144 of file vspline.cpp.
References VAbstractCurve::getLineColor(), VAbstractCurve::getLineWeight(), GetP1(), GetP2(), GetP3(), GetP4(), VAbstractCurve::GetPenStyle(), VGObject::name(), VPointF::Rotate(), VPointF::RotatePF(), VAbstractCurve::setLineColor(), VAbstractCurve::setLineWeight(), VGObject::setName(), and VAbstractCurve::SetPenStyle().
Referenced by VSplinePath::Rotate().
SetC1Length()
void VSpline::SetC1Length (qreal length, const QString & formula)
Definition at line 403 of file vspline.cpp.
References d.
SetC2Length()
void VSpline::SetC2Length (qreal length, const QString & formula)
Definition at line 410 of file vspline.cpp.
References d.
SetEndAngle()
void VSpline::SetEndAngle (qreal angle, const QString & formula)
Definition at line 372 of file vspline.cpp.
References d.
SetP1()
void VSpline::SetP1 (const VPointF & p)
Definition at line 287 of file vspline.cpp.
References d.
SetP4()
void VSpline::SetP4 (const VPointF & p)
Definition at line 327 of file vspline.cpp.
References d.
SetStartAngle()
void VSpline::SetStartAngle (qreal angle, const QString & formula)
Definition at line 365 of file vspline.cpp.
References d.
Sign()
int VSpline::Sign (long double ld) static private
Definition at line 449 of file vspline.cpp.
Referenced by Cubic().
SplinePoints()
QVector< QPointF > VSpline::SplinePoints (const QPointF & p1, const QPointF & p4, qreal angle1, qreal angle2, qreal kAsm1, qreal kAsm2, qreal kCurve) static
SplinePoints return list with spline points.
Parameters
p1 first spline point.
p4 last spline point.
angle1 angle from first point to first control point.
angle2 angle from second point to second control point.
kAsm1 coefficient of length first control line.
kAsm2 coefficient of length second control line.
kCurve coefficient of curvature spline.
Returns
list with spline points.
Definition at line 247 of file vspline.cpp.
References VAbstractCubicBezier::GetCubicBezierPoints().
Swap()
void VSpline::Swap (VSpline & spline)
Definition at line 64 of file vspline.cpp.
References VAbstractCurve::Swap().
Member Data Documentation
d
QSharedDataPointer<VSplineData> VSpline::d private
Definition at line 143 of file vspline.h.
Referenced by CalcT(), GetC1Length(), GetC1LengthFormula(), GetC2Length(), GetC2LengthFormula(), GetEndAngle(), GetEndAngleFormula(), GetKasm1(), GetKasm2(), GetKcurve(), GetP1(), GetP2(), GetP3(), GetP4(), GetStartAngle(), GetStartAngleFormula(), operator=(), SetC1Length(), SetC2Length(), SetEndAngle(), SetP1(), SetP4(), and SetStartAngle().
The documentation for this class was generated from the following files:
src/libs/vgeometry/vspline.h
src/libs/vgeometry/vspline.cpp