Seamly2D: CalculatorUtil Class Reference
CalculatorUtil Class Reference
[0]
#include <calculator.h>
Public Member Functions
CalculatorUtil (QWidget *parent=nullptr)
[0]
virtual ~CalculatorUtil ()
[6]
Private Types
enum { NumDigitButtons = 10 }
[9] //! [10]
Private Slots
void digitClicked ()
[7]
void unaryOperatorClicked ()
[7]
void additiveOperatorClicked ()
[9]
void multiplicativeOperatorClicked ()
[17]
void equalClicked ()
[18]
void pointClicked ()
[20]
void changeSignClicked ()
[22]
void backspaceClicked ()
[24]
void clear ()
[26]
void clearAll ()
[28]
void clearMemory ()
[30]
void readMemory ()
void setMemory ()
void addToMemory ()
Private Member Functions
Button * createButton (const QString &text, const char *member)
[0]
void abortOperation ()
[34]
bool calculate (double rightOperand, const QString &pendingOperator)
[36]
Private Attributes
double sumInMemory
[2]
double sumSoFar
[3] //! [4]
double factorSoFar
[4] //! [5]
QString pendingAdditiveOperator
[5] //! [6]
QString pendingMultiplicativeOperator
[6] //! [7]
bool waitingForOperand
[7] //! [8]
QLineEdit * display
[8]
Button * digitButtons [NumDigitButtons]
Detailed Description
[0]
Definition at line 66 of file calculator.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
[9] //! [10]
Enumerator
NumDigitButtons
Definition at line 117 of file calculator.h.
Constructor & Destructor Documentation
CalculatorUtil()
CalculatorUtil::CalculatorUtil (QWidget * parent = nullptr) explicit
[0]
[0] [1] [1] //! [2]
[2]
[4]
[4]
[5]
[5] //! [6]
Definition at line 60 of file calculator.cpp.
References additiveOperatorClicked(), addToMemory(), backspaceClicked(), changeSignClicked(), clear(), clearAll(), clearMemory(), createButton(), digitButtons, digitClicked(), display, equalClicked(), multiplicativeOperatorClicked(), NumDigitButtons, pointClicked(), readMemory(), setMemory(), and unaryOperatorClicked().
~CalculatorUtil()
CalculatorUtil::~CalculatorUtil () virtual
[6]
Definition at line 150 of file calculator.cpp.
Member Function Documentation
abortOperation()
void CalculatorUtil::abortOperation () private
[34]
[36]
Definition at line 391 of file calculator.cpp.
References clearAll(), and display.
Referenced by additiveOperatorClicked(), equalClicked(), multiplicativeOperatorClicked(), and unaryOperatorClicked().
additiveOperatorClicked
void CalculatorUtil::additiveOperatorClicked () private slot
[9]
[10] [10] //! [11]
[11] //! [12]
[12] //! [13]
[13] //! [14]
[14] //! [15]
[15] //! [16]
[16] //! [17]
Definition at line 201 of file calculator.cpp.
References abortOperation(), calculate(), display, factorSoFar, pendingAdditiveOperator, pendingMultiplicativeOperator, sumSoFar, and waitingForOperand.
Referenced by CalculatorUtil().
addToMemory
void CalculatorUtil::addToMemory () private slot
Definition at line 375 of file calculator.cpp.
References display, equalClicked(), and sumInMemory.
Referenced by CalculatorUtil().
backspaceClicked
void CalculatorUtil::backspaceClicked () private slot
[24]
[26]
Definition at line 319 of file calculator.cpp.
References display, and waitingForOperand.
Referenced by CalculatorUtil().
calculate()
bool CalculatorUtil::calculate (double rightOperand, const QString & pendingOperator) private
[36]
[38]
Definition at line 399 of file calculator.cpp.
References factorSoFar, and sumSoFar.
Referenced by additiveOperatorClicked(), equalClicked(), and multiplicativeOperatorClicked().
changeSignClicked
void CalculatorUtil::changeSignClicked () private slot
[22]
[24]
Definition at line 304 of file calculator.cpp.
References display.
Referenced by CalculatorUtil().
clear
void CalculatorUtil::clear () private slot
[26]
[28]
Definition at line 335 of file calculator.cpp.
References display, and waitingForOperand.
Referenced by CalculatorUtil().
clearAll
void CalculatorUtil::clearAll () private slot
[28]
[30]
Definition at line 346 of file calculator.cpp.
References display, factorSoFar, pendingAdditiveOperator, pendingMultiplicativeOperator, sumSoFar, and waitingForOperand.
Referenced by abortOperation(), and CalculatorUtil().
clearMemory
void CalculatorUtil::clearMemory () private slot
[30]
[32]
Definition at line 358 of file calculator.cpp.
References sumInMemory.
Referenced by CalculatorUtil().
createButton()
Button * CalculatorUtil::createButton (const QString & text, const char * member) private
[0]
[32] [34]
[1] [1] //! [2]
Definition at line 382 of file calculator.cpp.
Referenced by CalculatorUtil().
digitClicked
void CalculatorUtil::digitClicked () private slot
[7]
Definition at line 155 of file calculator.cpp.
References display, and waitingForOperand.
Referenced by CalculatorUtil().
equalClicked
void CalculatorUtil::equalClicked () private slot
[18]
[20]
Definition at line 263 of file calculator.cpp.
References abortOperation(), calculate(), display, factorSoFar, pendingAdditiveOperator, pendingMultiplicativeOperator, sumSoFar, and waitingForOperand.
Referenced by addToMemory(), CalculatorUtil(), and setMemory().
multiplicativeOperatorClicked
void CalculatorUtil::multiplicativeOperatorClicked () private slot
[17]
[18]
Definition at line 241 of file calculator.cpp.
References abortOperation(), calculate(), display, factorSoFar, pendingMultiplicativeOperator, and waitingForOperand.
Referenced by CalculatorUtil().
pointClicked
void CalculatorUtil::pointClicked () private slot
[20]
[22]
Definition at line 293 of file calculator.cpp.
References display, and waitingForOperand.
Referenced by CalculatorUtil().
readMemory
void CalculatorUtil::readMemory () private slot
Definition at line 363 of file calculator.cpp.
References display, sumInMemory, and waitingForOperand.
Referenced by CalculatorUtil().
setMemory
void CalculatorUtil::setMemory () private slot
Definition at line 369 of file calculator.cpp.
References display, equalClicked(), and sumInMemory.
Referenced by CalculatorUtil().
unaryOperatorClicked
void CalculatorUtil::unaryOperatorClicked () private slot
[7]
[8] [8] //! [9]
Definition at line 171 of file calculator.cpp.
References abortOperation(), display, and waitingForOperand.
Referenced by CalculatorUtil().
Member Data Documentation
digitButtons
Button* CalculatorUtil::digitButtons[NumDigitButtons] private
Definition at line 118 of file calculator.h.
Referenced by CalculatorUtil().
display
QLineEdit* CalculatorUtil::display private
[8]
[9]
Definition at line 114 of file calculator.h.
Referenced by abortOperation(), additiveOperatorClicked(), addToMemory(), backspaceClicked(), CalculatorUtil(), changeSignClicked(), clear(), clearAll(), digitClicked(), equalClicked(), multiplicativeOperatorClicked(), pointClicked(), readMemory(), setMemory(), and unaryOperatorClicked().
factorSoFar
double CalculatorUtil::factorSoFar private
[4] //! [5]
Definition at line 104 of file calculator.h.
Referenced by additiveOperatorClicked(), calculate(), clearAll(), equalClicked(), and multiplicativeOperatorClicked().
pendingAdditiveOperator
QString CalculatorUtil::pendingAdditiveOperator private
[5] //! [6]
Definition at line 106 of file calculator.h.
Referenced by additiveOperatorClicked(), clearAll(), and equalClicked().
pendingMultiplicativeOperator
QString CalculatorUtil::pendingMultiplicativeOperator private
[6] //! [7]
Definition at line 108 of file calculator.h.
Referenced by additiveOperatorClicked(), clearAll(), equalClicked(), and multiplicativeOperatorClicked().
sumInMemory
double CalculatorUtil::sumInMemory private
[2]
[3]
Definition at line 100 of file calculator.h.
Referenced by addToMemory(), clearMemory(), readMemory(), and setMemory().
sumSoFar
double CalculatorUtil::sumSoFar private
[3] //! [4]
Definition at line 102 of file calculator.h.
Referenced by additiveOperatorClicked(), calculate(), clearAll(), and equalClicked().
waitingForOperand
bool CalculatorUtil::waitingForOperand private
[7] //! [8]
Definition at line 110 of file calculator.h.
Referenced by additiveOperatorClicked(), backspaceClicked(), clear(), clearAll(), digitClicked(), equalClicked(), multiplicativeOperatorClicked(), pointClicked(), readMemory(), and unaryOperatorClicked().
The documentation for this class was generated from the following files:
src/libs/vwidgets/calculator/calculator.h
src/libs/vwidgets/calculator/calculator.cpp