Seamly2D: RefHashTableOf< TVal, THasher > Class Template Reference
RefHashTableOf< TVal, THasher > Class Template Reference
#include <RefHashTableOf.hpp>
Public Member Functions
RefHashTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHashTableOf ()
bool isEmpty () const
bool containsKey (const void *const key) const
void removeKey (const void *const key)
void removeAll ()
void cleanup ()
void reinitialize (const THasher &hasher)
void transferElement (const void *const key1, void *key2)
TVal * orphanKey (const void *const key)
TVal * get (const void *const key)
const TVal * get (const void *const key) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
XMLSize_t getCount () const
void setAdoptElements (const bool aValue)
void put (void *key, TVal *const valueToAdopt)
RefHashTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHashTableOf ()
bool isEmpty () const
bool containsKey (const void *const key) const
void removeKey (const void *const key)
void removeAll ()
void cleanup ()
void reinitialize (const THasher &hasher)
void transferElement (const void *const key1, void *key2)
TVal * orphanKey (const void *const key)
TVal * get (const void *const key)
const TVal * get (const void *const key) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
XMLSize_t getCount () const
void setAdoptElements (const bool aValue)
void put (void *key, TVal *const valueToAdopt)
RefHashTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHashTableOf ()
bool isEmpty () const
bool containsKey (const void *const key) const
void removeKey (const void *const key)
void removeAll ()
void cleanup ()
void reinitialize (const THasher &hasher)
void transferElement (const void *const key1, void *key2)
TVal * orphanKey (const void *const key)
TVal * get (const void *const key)
const TVal * get (const void *const key) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
XMLSize_t getCount () const
void setAdoptElements (const bool aValue)
void put (void *key, TVal *const valueToAdopt)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
RefHashTableOf (const RefHashTableOf< TVal, THasher > &)
RefHashTableOf< TVal, THasher > & operator= (const RefHashTableOf< TVal, THasher > &)
RefHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal)
const RefHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
RefHashTableOf (const RefHashTableOf< TVal, THasher > &)
RefHashTableOf< TVal, THasher > & operator= (const RefHashTableOf< TVal, THasher > &)
RefHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal)
const RefHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
RefHashTableOf (const RefHashTableOf< TVal, THasher > &)
RefHashTableOf< TVal, THasher > & operator= (const RefHashTableOf< TVal, THasher > &)
RefHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal)
const RefHashTableBucketElem< TVal > * findBucketElem (const void *const key, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
Private Attributes
MemoryManager * fMemoryManager
bool fAdoptedElems
RefHashTableBucketElem< TVal > ** fBucketList
XMLSize_t fHashModulus
XMLSize_t fInitialModulus
XMLSize_t fCount
THasher fHasher
Friends
class RefHashTableOfEnumerator< TVal, THasher >
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
template<class TVal, class THasher = StringHasher>
class RefHashTableOf< TVal, THasher >
Definition at line 68 of file RefHashTableOf.hpp.
Constructor & Destructor Documentation
RefHashTableOf() [1/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [2/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [3/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [4/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHashTableOf() [1/3]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::~RefHashTableOf ()
RefHashTableOf() [5/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const RefHashTableOf< TVal, THasher > &) private
RefHashTableOf() [6/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [7/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [8/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [9/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHashTableOf() [2/3]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::~RefHashTableOf ()
RefHashTableOf() [10/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const RefHashTableOf< TVal, THasher > &) private
RefHashTableOf() [11/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [12/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [13/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHashTableOf() [14/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHashTableOf() [3/3]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::~RefHashTableOf ()
RefHashTableOf() [15/15]
template<class TVal , class THasher = StringHasher> RefHashTableOf< TVal, THasher >::RefHashTableOf (const RefHashTableOf< TVal, THasher > &) private
Member Function Documentation
cleanup() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::cleanup ()
cleanup() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::cleanup ()
cleanup() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::cleanup ()
containsKey() [1/3]
template<class TVal , class THasher = StringHasher> bool RefHashTableOf< TVal, THasher >::containsKey (const void *const key) const
Referenced by DatatypeValidatorFactory::getDatatypeValidator().
containsKey() [2/3]
template<class TVal , class THasher = StringHasher> bool RefHashTableOf< TVal, THasher >::containsKey (const void *const key) const
containsKey() [3/3]
template<class TVal , class THasher = StringHasher> bool RefHashTableOf< TVal, THasher >::containsKey (const void *const key) const
findBucketElem() [1/6]
template<class TVal , class THasher = StringHasher> RefHashTableBucketElem<TVal>* RefHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) private
findBucketElem() [2/6]
template<class TVal , class THasher = StringHasher> RefHashTableBucketElem<TVal>* RefHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) private
findBucketElem() [3/6]
template<class TVal , class THasher = StringHasher> RefHashTableBucketElem<TVal>* RefHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) private
findBucketElem() [4/6]
template<class TVal , class THasher = StringHasher> const RefHashTableBucketElem<TVal>* RefHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) const private
findBucketElem() [5/6]
template<class TVal , class THasher = StringHasher> const RefHashTableBucketElem<TVal>* RefHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) const private
findBucketElem() [6/6]
template<class TVal , class THasher = StringHasher> const RefHashTableBucketElem<TVal>* RefHashTableOf< TVal, THasher >::findBucketElem (const void *const key, XMLSize_t & hashVal) const private
get() [1/6]
template<class TVal , class THasher = StringHasher> TVal* RefHashTableOf< TVal, THasher >::get (const void *const key)
Referenced by SchemaGrammar::getAnnotation(), DatatypeValidatorFactory::getDatatypeValidator(), ValueStoreCache::getGlobalValueStoreFor(), and XSObjectFactory::getObjectFromMap().
get() [2/6]
template<class TVal , class THasher = StringHasher> TVal* RefHashTableOf< TVal, THasher >::get (const void *const key)
get() [3/6]
template<class TVal , class THasher = StringHasher> TVal* RefHashTableOf< TVal, THasher >::get (const void *const key)
get() [4/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHashTableOf< TVal, THasher >::get (const void *const key) const
get() [5/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHashTableOf< TVal, THasher >::get (const void *const key) const
get() [6/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHashTableOf< TVal, THasher >::get (const void *const key) const
getCount() [1/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::getCount () const
getCount() [2/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::getCount () const
getCount() [3/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::getCount () const
getHashModulus() [1/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::getHashModulus () const
getHashModulus() [2/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::getHashModulus () const
getHashModulus() [3/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::getHashModulus () const
getMemoryManager() [1/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHashTableOf< TVal, THasher >::getMemoryManager () const
getMemoryManager() [2/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHashTableOf< TVal, THasher >::getMemoryManager () const
getMemoryManager() [3/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHashTableOf< TVal, THasher >::getMemoryManager () const
initialize() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
isEmpty() [1/3]
template<class TVal , class THasher = StringHasher> bool RefHashTableOf< TVal, THasher >::isEmpty () const
isEmpty() [2/3]
template<class TVal , class THasher = StringHasher> bool RefHashTableOf< TVal, THasher >::isEmpty () const
isEmpty() [3/3]
template<class TVal , class THasher = StringHasher> bool RefHashTableOf< TVal, THasher >::isEmpty () const
operator=() [1/3]
template<class TVal , class THasher = StringHasher> RefHashTableOf<TVal, THasher>& RefHashTableOf< TVal, THasher >::operator= (const RefHashTableOf< TVal, THasher > &) private
operator=() [2/3]
template<class TVal , class THasher = StringHasher> RefHashTableOf<TVal, THasher>& RefHashTableOf< TVal, THasher >::operator= (const RefHashTableOf< TVal, THasher > &) private
operator=() [3/3]
template<class TVal , class THasher = StringHasher> RefHashTableOf<TVal, THasher>& RefHashTableOf< TVal, THasher >::operator= (const RefHashTableOf< TVal, THasher > &) private
orphanKey() [1/3]
template<class TVal , class THasher = StringHasher> TVal* RefHashTableOf< TVal, THasher >::orphanKey (const void *const key)
orphanKey() [2/3]
template<class TVal , class THasher = StringHasher> TVal* RefHashTableOf< TVal, THasher >::orphanKey (const void *const key)
orphanKey() [3/3]
template<class TVal , class THasher = StringHasher> TVal* RefHashTableOf< TVal, THasher >::orphanKey (const void *const key)
put() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::put (void * key, TVal *const valueToAdopt)
put() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::put (void * key, TVal *const valueToAdopt)
put() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::put (void * key, TVal *const valueToAdopt)
rehash() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::rehash () private
rehash() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::rehash () private
rehash() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::rehash () private
reinitialize() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::reinitialize (const THasher & hasher)
reinitialize() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::reinitialize (const THasher & hasher)
reinitialize() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::reinitialize (const THasher & hasher)
removeAll() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::removeAll ()
removeAll() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::removeAll ()
removeAll() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::removeAll ()
removeKey() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::removeKey (const void *const key)
removeKey() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::removeKey (const void *const key)
removeKey() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::removeKey (const void *const key)
setAdoptElements() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::setAdoptElements (const bool aValue)
setAdoptElements() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::setAdoptElements (const bool aValue)
setAdoptElements() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::setAdoptElements (const bool aValue)
transferElement() [1/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::transferElement (const void *const key1, void * key2)
transferElement() [2/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::transferElement (const void *const key1, void * key2)
transferElement() [3/3]
template<class TVal , class THasher = StringHasher> void RefHashTableOf< TVal, THasher >::transferElement (const void *const key1, void * key2)
Friends And Related Function Documentation
RefHashTableOfEnumerator< TVal, THasher >
template<class TVal , class THasher = StringHasher> friend class RefHashTableOfEnumerator< TVal, THasher > friend
Definition at line 127 of file RefHashTableOf.hpp.
Member Data Documentation
fAdoptedElems
template<class TVal , class THasher = StringHasher> bool RefHashTableOf< TVal, THasher >::fAdoptedElems private
Definition at line 172 of file RefHashTableOf.hpp.
fBucketList
template<class TVal , class THasher = StringHasher> RefHashTableBucketElem< TVal > ** RefHashTableOf< TVal, THasher >::fBucketList private
Definition at line 173 of file RefHashTableOf.hpp.
Referenced by RefHashTableOfEnumerator< DTDAttDef >::nextElementKey().
fCount
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::fCount private
Definition at line 176 of file RefHashTableOf.hpp.
fHasher
template<class TVal , class THasher = StringHasher> THasher RefHashTableOf< TVal, THasher >::fHasher private
Definition at line 177 of file RefHashTableOf.hpp.
fHashModulus
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::fHashModulus private
Definition at line 174 of file RefHashTableOf.hpp.
fInitialModulus
template<class TVal , class THasher = StringHasher> XMLSize_t RefHashTableOf< TVal, THasher >::fInitialModulus private
Definition at line 175 of file RefHashTableOf.hpp.
fMemoryManager
template<class TVal , class THasher = StringHasher> MemoryManager * RefHashTableOf< TVal, THasher >::fMemoryManager private
Definition at line 171 of file RefHashTableOf.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/RefHashTableOf.hpp