Seamly2D: TST_FindPoint Class Reference
TST_FindPoint Class Reference
#include <tst_findpoint.h>
Public Member Functions
TST_FindPoint (QObject *parent=nullptr)
Private Slots
void TestPointOfIntersectionCurves_data ()
void TestPointOfIntersectionCurves ()
void TestTrueDarts_data ()
void TestTrueDarts ()
void TestLineIntersectAxis_data ()
void TestLineIntersectAxis ()
void TestTriangle_data ()
void TestTriangle ()
void TestShoulderPoint_data ()
void TestShoulderPoint ()
Detailed Description
Definition at line 57 of file tst_findpoint.h.
Constructor & Destructor Documentation
TST_FindPoint()
TST_FindPoint::TST_FindPoint (QObject * parent = nullptr) explicit
Definition at line 62 of file tst_findpoint.cpp.
Member Function Documentation
TestLineIntersectAxis
void TST_FindPoint::TestLineIntersectAxis () private slot
Definition at line 253 of file tst_findpoint.cpp.
References VToolLineIntersectAxis::FindPoint().
TestLineIntersectAxis_data
void TST_FindPoint::TestLineIntersectAxis_data () private slot
Definition at line 239 of file tst_findpoint.cpp.
TestPointOfIntersectionCurves
void TST_FindPoint::TestPointOfIntersectionCurves () private slot
Definition at line 182 of file tst_findpoint.cpp.
References VToolPointOfIntersectionCurves::FindPoint().
TestPointOfIntersectionCurves_data
void TST_FindPoint::TestPointOfIntersectionCurves_data () private slot
Definition at line 68 of file tst_findpoint.cpp.
References HighestPoint, LeftmostPoint, LowestPoint, and RightmostPoint.
TestShoulderPoint
void TST_FindPoint::TestShoulderPoint () private slot
Definition at line 321 of file tst_findpoint.cpp.
References VToolShoulderPoint::FindPoint().
TestShoulderPoint_data
void TST_FindPoint::TestShoulderPoint_data () private slot
Definition at line 295 of file tst_findpoint.cpp.
TestTriangle
void TST_FindPoint::TestTriangle () private slot
Definition at line 282 of file tst_findpoint.cpp.
References VToolTriangle::FindPoint().
TestTriangle_data
void TST_FindPoint::TestTriangle_data () private slot
Definition at line 264 of file tst_findpoint.cpp.
TestTrueDarts
void TST_FindPoint::TestTrueDarts () private slot
Definition at line 219 of file tst_findpoint.cpp.
References VToolTrueDarts::FindPoint().
TestTrueDarts_data
void TST_FindPoint::TestTrueDarts_data () private slot
Definition at line 197 of file tst_findpoint.cpp.
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_findpoint.h
src/test/Seamly2DTest/tst_findpoint.cpp