Seamly2D: XMLDouble Class Reference
XMLDouble Class Reference
#include <XMLDouble.hpp>
Public Member Functions
XMLDouble (const XMLCh *const strValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XMLDouble ()
XMLDouble (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLDouble (const XMLCh *const strValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XMLDouble ()
XMLDouble (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLDouble (const XMLCh *const strValue, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XMLDouble ()
XMLDouble (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Public Member Functions inherited from XMLAbstractDoubleFloat
virtual ~XMLAbstractDoubleFloat ()
virtual XMLCh * getRawData () const
virtual const XMLCh * getFormattedString () const
virtual int getSign () const
MemoryManager * getMemoryManager () const
bool isDataConverted () const
bool isDataOverflowed () const
double getValue () const
LiteralType getType () const
virtual ~XMLAbstractDoubleFloat ()
virtual XMLCh * getRawData () const
virtual const XMLCh * getFormattedString () const
virtual int getSign () const
MemoryManager * getMemoryManager () const
bool isDataConverted () const
bool isDataOverflowed () const
double getValue () const
LiteralType getType () const
virtual ~XMLAbstractDoubleFloat ()
virtual XMLCh * getRawData () const
virtual const XMLCh * getFormattedString () const
virtual int getSign () const
MemoryManager * getMemoryManager () const
bool isDataConverted () const
bool isDataOverflowed () const
double getValue () const
LiteralType getType () const
Public Member Functions inherited from XMLNumber
virtual ~XMLNumber ()
virtual ~XMLNumber ()
virtual ~XMLNumber ()
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Static Public Member Functions
static int compareValues (const XMLDouble *const lValue, const XMLDouble *const rValue)
static int compareValues (const XMLDouble *const lValue, const XMLDouble *const rValue)
static int compareValues (const XMLDouble *const lValue, const XMLDouble *const rValue)
Static Public Member Functions inherited from XMLAbstractDoubleFloat
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
static void normalizeDecimalPoint (char *const toNormal)
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
static void normalizeDecimalPoint (char *const toNormal)
static XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
static void normalizeDecimalPoint (char *const toNormal)
Static Public Member Functions inherited from XMLNumber
static XMLNumber * loadNumber (XMLNumber::NumberType numType, XSerializeEngine &serEng)
static XMLNumber * loadNumber (XMLNumber::NumberType numType, XSerializeEngine &serEng)
static XMLNumber * loadNumber (XMLNumber::NumberType numType, XSerializeEngine &serEng)
Protected Member Functions
virtual void checkBoundary (char *const strValue)
virtual void checkBoundary (char *const strValue)
virtual void checkBoundary (char *const strValue)
Protected Member Functions inherited from XMLAbstractDoubleFloat
XMLAbstractDoubleFloat (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void init (const XMLCh *const strValue)
void convert (char *const strValue)
XMLAbstractDoubleFloat (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void init (const XMLCh *const strValue)
void convert (char *const strValue)
XMLAbstractDoubleFloat (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
void init (const XMLCh *const strValue)
void convert (char *const strValue)
Protected Member Functions inherited from XMLNumber
XMLNumber ()
XMLNumber (const XMLNumber &)
XMLNumber ()
XMLNumber (const XMLNumber &)
XMLNumber ()
XMLNumber (const XMLNumber &)
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Private Member Functions
XMLDouble (const XMLDouble &toCopy)
XMLDouble & operator= (const XMLDouble &toAssign)
XMLDouble (const XMLDouble &toCopy)
XMLDouble & operator= (const XMLDouble &toAssign)
XMLDouble (const XMLDouble &toCopy)
XMLDouble & operator= (const XMLDouble &toAssign)
Additional Inherited Members
Public Types inherited from XMLAbstractDoubleFloat
enum LiteralType {
NegINF , PosINF , NaN , SpecialTypeNum ,
Normal , NegINF , PosINF , NaN ,
SpecialTypeNum , Normal , NegINF , PosINF ,
NaN , SpecialTypeNum , Normal
}
enum LiteralType {
NegINF , PosINF , NaN , SpecialTypeNum ,
Normal , NegINF , PosINF , NaN ,
SpecialTypeNum , Normal , NegINF , PosINF ,
NaN , SpecialTypeNum , Normal
}
enum LiteralType {
NegINF , PosINF , NaN , SpecialTypeNum ,
Normal , NegINF , PosINF , NaN ,
SpecialTypeNum , Normal , NegINF , PosINF ,
NaN , SpecialTypeNum , Normal
}
Public Types inherited from XMLNumber
enum { LESS_THAN = -1 , EQUAL = 0 , GREATER_THAN = 1 , INDETERMINATE = 2 }
enum NumberType {
Float , Double , BigDecimal , DateTime ,
UnKnown , Float , Double , BigDecimal ,
DateTime , UnKnown , Float , Double ,
BigDecimal , DateTime , UnKnown
}
enum { LESS_THAN = -1 , EQUAL = 0 , GREATER_THAN = 1 , INDETERMINATE = 2 }
enum NumberType {
Float , Double , BigDecimal , DateTime ,
UnKnown , Float , Double , BigDecimal ,
DateTime , UnKnown , Float , Double ,
BigDecimal , DateTime , UnKnown
}
enum { LESS_THAN = -1 , EQUAL = 0 , GREATER_THAN = 1 , INDETERMINATE = 2 }
enum NumberType {
Float , Double , BigDecimal , DateTime ,
UnKnown , Float , Double , BigDecimal ,
DateTime , UnKnown , Float , Double ,
BigDecimal , DateTime , UnKnown
}
Static Protected Member Functions inherited from XMLAbstractDoubleFloat
static int compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager)
static int compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager)
static int compareValues (const XMLAbstractDoubleFloat *const lValue, const XMLAbstractDoubleFloat *const rValue, MemoryManager *const manager)
Protected Attributes inherited from XMLAbstractDoubleFloat
double fValue
LiteralType fType
bool fDataConverted
bool fDataOverflowed
Detailed Description
Definition at line 29 of file XMLDouble.hpp.
Constructor & Destructor Documentation
XMLDouble() [1/9]
XMLDouble::XMLDouble (const XMLCh *const strValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a newly allocated XMLDouble object that represents the value represented by the string.
Parameters
strValue the String to be converted to an XMLDouble.
manager Pointer to the memory manager to be used to allocate objects.
Exceptions
NumberFormatException if the String does not contain a parsable XMLDouble.
~XMLDouble() [1/3]
XMLDouble::~XMLDouble ()
XMLDouble() [2/9]
XMLDouble::XMLDouble (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XMLDouble() [3/9]
XMLDouble::XMLDouble (const XMLDouble & toCopy) private
XMLDouble() [4/9]
XMLDouble::XMLDouble (const XMLCh *const strValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a newly allocated XMLDouble object that represents the value represented by the string.
Parameters
strValue the String to be converted to an XMLDouble.
manager Pointer to the memory manager to be used to allocate objects.
Exceptions
NumberFormatException if the String does not contain a parsable XMLDouble.
~XMLDouble() [2/3]
XMLDouble::~XMLDouble ()
XMLDouble() [5/9]
XMLDouble::XMLDouble (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XMLDouble() [6/9]
XMLDouble::XMLDouble (const XMLDouble & toCopy) private
XMLDouble() [7/9]
XMLDouble::XMLDouble (const XMLCh *const strValue, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Constructs a newly allocated XMLDouble object that represents the value represented by the string.
Parameters
strValue the String to be converted to an XMLDouble.
manager Pointer to the memory manager to be used to allocate objects.
Exceptions
NumberFormatException if the String does not contain a parsable XMLDouble.
~XMLDouble() [3/3]
XMLDouble::~XMLDouble ()
XMLDouble() [8/9]
XMLDouble::XMLDouble (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XMLDouble() [9/9]
XMLDouble::XMLDouble (const XMLDouble & toCopy) private
Member Function Documentation
checkBoundary() [1/3]
virtual void XMLDouble::checkBoundary (char *const strValue) protected virtual
Implements XMLAbstractDoubleFloat.
checkBoundary() [2/3]
virtual void XMLDouble::checkBoundary (char *const strValue) protected virtual
Implements XMLAbstractDoubleFloat.
checkBoundary() [3/3]
virtual void XMLDouble::checkBoundary (char *const strValue) protected virtual
Implements XMLAbstractDoubleFloat.
compareValues() [1/3]
int XMLDouble::compareValues (const XMLDouble *const lValue, const XMLDouble *const rValue) inline static
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLDouble object that contains the same int value as this object.
Parameters
lValue the object to compare with.
rValue the object to compare against.
Returns
true if the objects are the same; false otherwise.
Definition at line 88 of file XMLDouble.hpp.
References XMLAbstractDoubleFloat::compareValues(), and XMLAbstractDoubleFloat::getMemoryManager().
compareValues() [2/3]
static int XMLDouble::compareValues (const XMLDouble *const lValue, const XMLDouble *const rValue) inline static
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLDouble object that contains the same int value as this object.
Parameters
lValue the object to compare with.
rValue the object to compare against.
Returns
true if the objects are the same; false otherwise.
compareValues() [3/3]
static int XMLDouble::compareValues (const XMLDouble *const lValue, const XMLDouble *const rValue) inline static
Compares this object to the specified object. The result is true if and only if the argument is not null and is an XMLDouble object that contains the same int value as this object.
Parameters
lValue the object to compare with.
rValue the object to compare against.
Returns
true if the objects are the same; false otherwise.
operator=() [1/3]
XMLDouble& XMLDouble::operator= (const XMLDouble & toAssign) private
operator=() [2/3]
XMLDouble& XMLDouble::operator= (const XMLDouble & toAssign) private
References XMLAbstractDoubleFloat::compareValues(), and XMLAbstractDoubleFloat::getMemoryManager().
operator=() [3/3]
XMLDouble& XMLDouble::operator= (const XMLDouble & toAssign) private
References XMLAbstractDoubleFloat::compareValues(), and XMLAbstractDoubleFloat::getMemoryManager().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/XMLDouble.hpp