Seamly2D: ValueStoreCache Class Reference
ValueStoreCache Class Reference
#include <ValueStoreCache.hpp>
Public Member Functions
ValueStoreCache (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ValueStoreCache ()
void setScanner (XMLScanner *const scanner)
void startDocument ()
void startElement ()
void endElement ()
void endDocument ()
void initValueStoresFor (SchemaElementDecl *const elemDecl, const int initialDepth)
ValueStore * getValueStoreFor (const IC_Field *const field, const int initialDepth)
ValueStore * getValueStoreFor (const IdentityConstraint *const ic, const int initialDepth)
ValueStore * getGlobalValueStoreFor (const IdentityConstraint *const ic)
void transplant (IdentityConstraint *const ic, const int initialDepth)
ValueStoreCache (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ValueStoreCache ()
void setScanner (XMLScanner *const scanner)
void startDocument ()
void startElement ()
void endElement ()
void endDocument ()
void initValueStoresFor (SchemaElementDecl *const elemDecl, const int initialDepth)
ValueStore * getValueStoreFor (const IC_Field *const field, const int initialDepth)
ValueStore * getValueStoreFor (const IdentityConstraint *const ic, const int initialDepth)
ValueStore * getGlobalValueStoreFor (const IdentityConstraint *const ic)
void transplant (IdentityConstraint *const ic, const int initialDepth)
ValueStoreCache (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ValueStoreCache ()
void setScanner (XMLScanner *const scanner)
void startDocument ()
void startElement ()
void endElement ()
void endDocument ()
void initValueStoresFor (SchemaElementDecl *const elemDecl, const int initialDepth)
ValueStore * getValueStoreFor (const IC_Field *const field, const int initialDepth)
ValueStore * getValueStoreFor (const IdentityConstraint *const ic, const int initialDepth)
ValueStore * getGlobalValueStoreFor (const IdentityConstraint *const ic)
void transplant (IdentityConstraint *const ic, const int initialDepth)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
ValueStoreCache (const ValueStoreCache &other)
ValueStoreCache & operator= (const ValueStoreCache &other)
void init ()
void cleanUp ()
ValueStoreCache (const ValueStoreCache &other)
ValueStoreCache & operator= (const ValueStoreCache &other)
void init ()
void cleanUp ()
ValueStoreCache (const ValueStoreCache &other)
ValueStoreCache & operator= (const ValueStoreCache &other)
void init ()
void cleanUp ()
Private Attributes
RefVectorOf< ValueStore > * fValueStores
RefHashTableOf< ValueStore, PtrHasher > * fGlobalICMap
RefHash2KeysTableOf< ValueStore, PtrHasher > * fIC2ValueStoreMap
RefStackOf< RefHashTableOf< ValueStore, PtrHasher > > * fGlobalMapStack
XMLScanner * fScanner
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 63 of file ValueStoreCache.hpp.
Constructor & Destructor Documentation
ValueStoreCache() [1/6]
ValueStoreCache::ValueStoreCache (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ValueStoreCache() [1/3]
ValueStoreCache::~ValueStoreCache ()
ValueStoreCache() [2/6]
ValueStoreCache::ValueStoreCache (const ValueStoreCache & other) private
ValueStoreCache() [3/6]
ValueStoreCache::ValueStoreCache (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ValueStoreCache() [2/3]
ValueStoreCache::~ValueStoreCache ()
ValueStoreCache() [4/6]
ValueStoreCache::ValueStoreCache (const ValueStoreCache & other) private
ValueStoreCache() [5/6]
ValueStoreCache::ValueStoreCache (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ValueStoreCache() [3/3]
ValueStoreCache::~ValueStoreCache ()
ValueStoreCache() [6/6]
ValueStoreCache::ValueStoreCache (const ValueStoreCache & other) private
Member Function Documentation
cleanUp() [1/3]
void ValueStoreCache::cleanUp () private
cleanUp() [2/3]
void ValueStoreCache::cleanUp () private
cleanUp() [3/3]
void ValueStoreCache::cleanUp () private
endDocument() [1/3]
void ValueStoreCache::endDocument () inline
Definition at line 163 of file ValueStoreCache.hpp.
Referenced by IdentityConstraintHandler::endDocument().
endDocument() [2/3]
void ValueStoreCache::endDocument ()
endDocument() [3/3]
void ValueStoreCache::endDocument ()
endElement() [1/3]
void ValueStoreCache::endElement ()
endElement() [2/3]
void ValueStoreCache::endElement ()
endElement() [3/3]
void ValueStoreCache::endElement ()
getGlobalValueStoreFor() [1/3]
ValueStore * ValueStoreCache::getGlobalValueStoreFor (const IdentityConstraint *const ic) inline
Definition at line 155 of file ValueStoreCache.hpp.
References fGlobalICMap, and RefHashTableOf< TVal, THasher >::get().
getGlobalValueStoreFor() [2/3]
ValueStore* ValueStoreCache::getGlobalValueStoreFor (const IdentityConstraint *const ic)
getGlobalValueStoreFor() [3/3]
ValueStore* ValueStoreCache::getGlobalValueStoreFor (const IdentityConstraint *const ic)
getValueStoreFor() [1/6]
ValueStore * ValueStoreCache::getValueStoreFor (const IC_Field *const field, const int initialDepth) inline
Definition at line 143 of file ValueStoreCache.hpp.
References fIC2ValueStoreMap, RefHash2KeysTableOf< TVal, THasher >::get(), and IC_Field::getIdentityConstraint().
getValueStoreFor() [2/6]
ValueStore* ValueStoreCache::getValueStoreFor (const IC_Field *const field, const int initialDepth)
getValueStoreFor() [3/6]
ValueStore* ValueStoreCache::getValueStoreFor (const IC_Field *const field, const int initialDepth)
getValueStoreFor() [4/6]
ValueStore * ValueStoreCache::getValueStoreFor (const IdentityConstraint *const ic, const int initialDepth) inline
Definition at line 149 of file ValueStoreCache.hpp.
References fIC2ValueStoreMap, and RefHash2KeysTableOf< TVal, THasher >::get().
getValueStoreFor() [5/6]
ValueStore* ValueStoreCache::getValueStoreFor (const IdentityConstraint *const ic, const int initialDepth)
getValueStoreFor() [6/6]
ValueStore* ValueStoreCache::getValueStoreFor (const IdentityConstraint *const ic, const int initialDepth)
init() [1/3]
void ValueStoreCache::init () private
init() [2/3]
void ValueStoreCache::init () private
init() [3/3]
void ValueStoreCache::init () private
initValueStoresFor() [1/3]
void ValueStoreCache::initValueStoresFor (SchemaElementDecl *const elemDecl, const int initialDepth)
initValueStoresFor() [2/3]
void ValueStoreCache::initValueStoresFor (SchemaElementDecl *const elemDecl, const int initialDepth)
initValueStoresFor() [3/3]
void ValueStoreCache::initValueStoresFor (SchemaElementDecl *const elemDecl, const int initialDepth)
operator=() [1/3]
ValueStoreCache& ValueStoreCache::operator= (const ValueStoreCache & other) private
operator=() [2/3]
ValueStoreCache& ValueStoreCache::operator= (const ValueStoreCache & other) private
operator=() [3/3]
ValueStoreCache& ValueStoreCache::operator= (const ValueStoreCache & other) private
setScanner() [1/3]
void ValueStoreCache::setScanner (XMLScanner *const scanner) inline
Definition at line 134 of file ValueStoreCache.hpp.
References fScanner.
setScanner() [2/3]
void ValueStoreCache::setScanner (XMLScanner *const scanner)
setScanner() [3/3]
void ValueStoreCache::setScanner (XMLScanner *const scanner)
startDocument() [1/3]
void ValueStoreCache::startDocument ()
startDocument() [2/3]
void ValueStoreCache::startDocument ()
startDocument() [3/3]
void ValueStoreCache::startDocument ()
startElement() [1/3]
void ValueStoreCache::startElement ()
startElement() [2/3]
void ValueStoreCache::startElement ()
startElement() [3/3]
void ValueStoreCache::startElement ()
transplant() [1/3]
void ValueStoreCache::transplant (IdentityConstraint *const ic, const int initialDepth)
This method takes the contents of the (local) ValueStore associated with ic and moves them into the global hashtable, if ic is a <unique> or a <key>. If it's a <keyRef>, then we leave it for later.
transplant() [2/3]
void ValueStoreCache::transplant (IdentityConstraint *const ic, const int initialDepth)
This method takes the contents of the (local) ValueStore associated with ic and moves them into the global hashtable, if ic is a <unique> or a <key>. If it's a <keyRef>, then we leave it for later.
transplant() [3/3]
void ValueStoreCache::transplant (IdentityConstraint *const ic, const int initialDepth)
This method takes the contents of the (local) ValueStore associated with ic and moves them into the global hashtable, if ic is a <unique> or a <key>. If it's a <keyRef>, then we leave it for later.
Member Data Documentation
fGlobalICMap
RefHashTableOf< ValueStore, PtrHasher > * ValueStoreCache::fGlobalICMap private
Definition at line 124 of file ValueStoreCache.hpp.
Referenced by getGlobalValueStoreFor().
fGlobalMapStack
RefStackOf< RefHashTableOf< ValueStore, PtrHasher > > * ValueStoreCache::fGlobalMapStack private
Definition at line 126 of file ValueStoreCache.hpp.
fIC2ValueStoreMap
RefHash2KeysTableOf< ValueStore, PtrHasher > * ValueStoreCache::fIC2ValueStoreMap private
Definition at line 125 of file ValueStoreCache.hpp.
Referenced by getValueStoreFor().
fMemoryManager
MemoryManager * ValueStoreCache::fMemoryManager private
Definition at line 128 of file ValueStoreCache.hpp.
fScanner
XMLScanner * ValueStoreCache::fScanner private
Definition at line 127 of file ValueStoreCache.hpp.
Referenced by setScanner().
fValueStores
RefVectorOf< ValueStore > * ValueStoreCache::fValueStores private
Definition at line 123 of file ValueStoreCache.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/identity/ValueStoreCache.hpp