Seamly2D: src/libs/vmisc/vlockguard.h File Reference
vlockguard.h File Reference
#include <QString>
#include <stdint.h>
#include <memory>
#include "../vmisc/diagnostic.h"
#include <QFileInfo>
#include <QLockFile>
Classes
class VLockGuard< Guarded >
Functions
template<typename Guarded >
QT_WARNING_PUSH void VlpCreateLock (std::shared_ptr< VLockGuard< Guarded >> &r, const QString &lockName, int stale=0, int timeout=0)
template<typename Guarded , typename Alloc >
void VlpCreateLock (std::shared_ptr< VLockGuard< Guarded >> &r, const QString &lockName, Alloc a, int stale=0, int timeout=0)
template<typename Guarded , typename Alloc , typename Del >
void VlpCreateLock (std::shared_ptr< VLockGuard< Guarded >> &r, const QString &lockName, Alloc a, Del d, int stale=0, int timeout=0)
Function Documentation
VlpCreateLock() [1/3]
template<typename Guarded , typename Alloc , typename Del > void VlpCreateLock (std::shared_ptr< VLockGuard< Guarded >> & r, const QString & lockName, Alloc a, Del d, int stale = 0, int timeout = 0)
Definition at line 226 of file vlockguard.h.
VlpCreateLock() [2/3]
template<typename Guarded , typename Alloc > void VlpCreateLock (std::shared_ptr< VLockGuard< Guarded >> & r, const QString & lockName, Alloc a, int stale = 0, int timeout = 0)
Definition at line 219 of file vlockguard.h.
VlpCreateLock() [3/3]
template<typename Guarded > QT_WARNING_PUSH void VlpCreateLock (std::shared_ptr< VLockGuard< Guarded >> & r, const QString & lockName, int stale = 0, int timeout = 0)
Definition at line 213 of file vlockguard.h.
Referenced by VApplication::BeginLogging(), TMainWindow::FileSaveAs(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), MainWindow::LoadPattern(), and MainWindow::SaveAs().