Seamly2D: src/libs/ifc/xml/vpatternconverter.cpp File Reference
vpatternconverter.cpp File Reference
#include "vpatternconverter.h"
#include "vabstractconverter.h"
#include "../exception/vexception.h"
#include "../exception/vexceptionemptyparameter.h"
#include "../qmuparser/qmutokenparser.h"
#include "../vmisc/def.h"
#include "../vmisc/logging.h"
#include <QDir>
#include <QDomNode>
#include <QDomNodeList>
#include <QDomText>
#include <QFile>
#include <QFileInfo>
#include <QLatin1String>
#include <QList>
#include <QStaticStringData>
#include <QStringData>
#include <QStringDataPtr>
#include <algorithm>
Variables
static const QString strUnit = QStringLiteral("unit")
static const QString strVersion = QStringLiteral("version")
static const QString strName = QStringLiteral("name")
static const QString strBase = QStringLiteral("base")
static const QString strFormula = QStringLiteral("formula")
static const QString strId = QStringLiteral("id")
static const QString strKGrowth = QStringLiteral("kgrowth")
static const QString strKSize = QStringLiteral("ksize")
static const QString strPoint = QStringLiteral("point")
static const QString strLength = QStringLiteral("length")
static const QString strAngle = QStringLiteral("angle")
static const QString strC1Radius = QStringLiteral("c1Radius")
static const QString strC2Radius = QStringLiteral("c2Radius")
static const QString strCRadius = QStringLiteral("cRadius")
static const QString strArc = QStringLiteral("arc")
static const QString strAngle1 = QStringLiteral("angle1")
static const QString strAngle2 = QStringLiteral("angle2")
static const QString strRadius = QStringLiteral("radius")
static const QString strPathPoint = QStringLiteral("pathPoint")
static const QString strKAsm1 = QStringLiteral("kAsm1")
static const QString strKAsm2 = QStringLiteral("kAsm2")
static const QString strPath = QStringLiteral("path")
static const QString strType = QStringLiteral("type")
static const QString strCutArc = QStringLiteral("cutArc")
static const QString strSpline = QStringLiteral("spline")
static const QString strSplinePath = QStringLiteral("splinePath")
static const QString strCutSpline = QStringLiteral("cutSpline")
static const QString strCutSplinePath = QStringLiteral("cutSplinePath")
static const QString strColor = QStringLiteral("color")
static const QString strMeasurements = QStringLiteral("measurements")
static const QString strIncrement = QStringLiteral("increment")
static const QString strIncrements = QStringLiteral("increments")
static const QString strModeling = QStringLiteral("modeling")
static const QString strTools = QStringLiteral("tools")
static const QString strIdTool = QStringLiteral("idTool")
static const QString strIdObject = QStringLiteral("idObject")
static const QString strChildren = QStringLiteral("children")
static const QString strChild = QStringLiteral("child")
static const QString strPointOfIntersectionCurves = QStringLiteral("pointOfIntersectionCurves")
static const QString strCurveIntersectAxis = QStringLiteral("curveIntersectAxis")
static const QString strCurve = QStringLiteral("curve")
static const QString strCurve1 = QStringLiteral("curve1")
static const QString strCurve2 = QStringLiteral("curve2")
static const QString strModelingPath = QStringLiteral("modelingPath")
static const QString strModelingSpline = QStringLiteral("modelingSpline")
static const QString strPointFromArcAndTangent = QStringLiteral("pointFromArcAndTangent")
static const QString strPointOfIntersectionArcs = QStringLiteral("pointOfIntersectionArcs")
static const QString strFirstArc = QStringLiteral("firstArc")
static const QString strSecondArc = QStringLiteral("secondArc")
static const QString strDraw = QStringLiteral("draw")
static const QString strDraftBlock = QStringLiteral("draftBlock")
static const QString strDetails = QStringLiteral("details")
static const QString strPieces = QStringLiteral("pieces")
static const QString strDetail = QStringLiteral("detail")
static const QString strPiece = QStringLiteral("piece")
static const QString strUnionDetail = QStringLiteral("unionDetail")
static const QString strUnion = QStringLiteral("union")
static const QString strSupplement = QStringLiteral("supplement")
static const QString strClosed = QStringLiteral("closed")
static const QString strWidth = QStringLiteral("width")
static const QString strHeight = QStringLiteral("height")
static const QString strNode = QStringLiteral("node")
static const QString strNodes = QStringLiteral("nodes")
static const QString strData = QStringLiteral("data")
static const QString strPatternInfo = QStringLiteral("patternInfo")
static const QString strGrainline = QStringLiteral("grainline")
static const QString strReverse = QStringLiteral("reverse")
static const QString strMx = QStringLiteral("mx")
static const QString strMy = QStringLiteral("my")
static const QString strForbidFlipping = QStringLiteral("forbidFlipping")
static const QString strInLayout = QStringLiteral("inLayout")
static const QString strSeamAllowance = QStringLiteral("seamAllowance")
static const QString strNodeType = QStringLiteral("nodeType")
static const QString strDet = QStringLiteral("det")
static const QString strTypeObject = QStringLiteral("typeObject")
static const QString strReadOnly = QStringLiteral("readOnly")
static const QString strPatternLabel = QStringLiteral("patternLabel")
static const QString strImage = QStringLiteral("image")
static const QString strAuthor = QStringLiteral("author")
static const QString strDescription = QStringLiteral("description")
static const QString strNotes = QStringLiteral("notes")
static const QString strGradation = QStringLiteral("gradation")
static const QString strPatternName = QStringLiteral("patternName")
static const QString strPatternNum = QStringLiteral("patternNumber")
static const QString strCompanyName = QStringLiteral("company")
static const QString strCustomerName = QStringLiteral("customer")
static const QString strLine = QStringLiteral("line")
static const QString strText = QStringLiteral("text")
static const QString strBold = QStringLiteral("bold")
static const QString strItalic = QStringLiteral("italic")
static const QString strAlignment = QStringLiteral("alignment")
static const QString strFSIncrement = QStringLiteral("sfIncrement")
static const QString strShowDate = QStringLiteral("showDate")
static const QString strShowMeasurements = QStringLiteral("showMeasurements")
static const QString strSize = QStringLiteral("size")
static const QString strMCP = QStringLiteral("mcp")
static const QString strLetter = QStringLiteral("letter")
static const QString strMaterial = QStringLiteral("material")
static const QString strUserDefined = QStringLiteral("userDef")
static const QString strPlacement = QStringLiteral("placement")
static const QString strPassmark = QStringLiteral("passmark")
static const QString strPassmarkLine = QStringLiteral("passmarkLine")
static const QString strPassmarkAngle = QStringLiteral("passmarkAngle")
static const QString strShowSecondPassmark = QStringLiteral("showSecondPassmark")
static const QString strNotch = QStringLiteral("notch")
static const QString strNotchCount = QStringLiteral("notchCount")
static const QString strNotchAngle = QStringLiteral("notchAngle")
static const QString strNotchType = QStringLiteral("notchType")
static const QString strNotchSubType = QStringLiteral("notchSubtype")
static const QString strShowNotch = QStringLiteral("showNotch")
static const QString strShowSecond = QStringLiteral("showSecondNotch")
static const QString strSlitNotch = QStringLiteral("slit")
static const QString strVMark = QStringLiteral("vMark")
static const QString strV_External = QStringLiteral("vExternal")
static const QString strTMark = QStringLiteral("tMark")
static const QString strT_Notch = QStringLiteral("tNotch")
static const QString strHair = QStringLiteral("hair")
static const QString strSolidLine = QStringLiteral("solidLine")
static const QString strOne = QStringLiteral("one")
static const QString strTwo = QStringLiteral("two")
static const QString strThree = QStringLiteral("three")
static const QString strTypeLine = QStringLiteral("typeLine")
static const QString strLineType = QStringLiteral("lineType")
static const QString strLineWeight = QStringLiteral("lineWeight")
static const QString strLineColor = QStringLiteral("lineColor")
static const QString strPenStyle = QStringLiteral("penStyle")
static const QString strElArc = QStringLiteral("elArc")
static const QString strTrue = QStringLiteral("true")
static const QString strPin = QStringLiteral("pin")
static const QString strPins = QStringLiteral("pins")
static const QString strTopLeftPin = QStringLiteral("topLeftPin")
static const QString strBottomRightPin = QStringLiteral("bottomRightPin")
static const QString strCenterPin = QStringLiteral("centerPin")
static const QString strTopPin = QStringLiteral("topPin")
static const QString strBottomPin = QStringLiteral("bottomPin")
static const QString strAnchor = QStringLiteral("anchor")
static const QString strAnchors = QStringLiteral("anchors")
static const QString strTopLeftAnchor = QStringLiteral("topLeftAnchor")
static const QString strBottomRightAnchor = QStringLiteral("bottomRightAnchor")
static const QString strCenterAnchor = QStringLiteral("centerAnchor")
static const QString strTopAnchor = QStringLiteral("topAnchor")
static const QString strBottomAnchor = QStringLiteral("bottomAnchor")
Variable Documentation
strAlignment
const QString strAlignment = QStringLiteral("alignment") static
Definition at line 186 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddLabelTemplateLineV0_6_0().
strAnchor
const QString strAnchor = QStringLiteral("anchor") static
Definition at line 233 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strAnchors
const QString strAnchors = QStringLiteral("anchors") static
Definition at line 234 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strAngle
const QString strAngle = QStringLiteral("angle") static
Definition at line 106 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertPathPointExpressionsToV0_2_0(), VPatternConverter::ConvertPointExpressionsToV0_2_0(), VPatternConverter::FixPathPointExpressionsToV0_2_0(), and VPatternConverter::FixPointExpressionsToV0_2_0().
strAngle1
const QString strAngle1 = QStringLiteral("angle1") static
Definition at line 111 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertArcExpressionsToV0_2_0(), and VPatternConverter::FixArcExpressionsToV0_2_0().
strAngle2
const QString strAngle2 = QStringLiteral("angle2") static
Definition at line 112 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertArcExpressionsToV0_2_0(), and VPatternConverter::FixArcExpressionsToV0_2_0().
strArc
const QString strArc = QStringLiteral("arc") static
Definition at line 110 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertArcExpressionsToV0_2_0(), VPatternConverter::FixArcExpressionsToV0_2_0(), VPatternConverter::FixCutPoint(), VPatternConverter::FixSubPaths(), and VPatternConverter::toVersion0_6_1().
strAuthor
const QString strAuthor = QStringLiteral("author") static
Definition at line 174 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1(), VPatternConverter::PortPatternLabeltoV0_6_0(), and VPatternConverter::RemoveUnusedTagsV0_6_0().
strBase
const QString strBase = QStringLiteral("base") static
Definition at line 99 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixIncrementsToV0_2_0().
strBold
const QString strBold = QStringLiteral("bold") static
Definition at line 184 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddLabelTemplateLineV0_6_0().
strBottomAnchor
const QString strBottomAnchor = QStringLiteral("bottomAnchor") static
Definition at line 239 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strBottomPin
const QString strBottomPin = QStringLiteral("bottomPin") static
Definition at line 231 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strBottomRightAnchor
const QString strBottomRightAnchor = QStringLiteral("bottomRightAnchor") static
Definition at line 236 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strBottomRightPin
const QString strBottomRightPin = QStringLiteral("bottomRightPin") static
Definition at line 228 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strC1Radius
const QString strC1Radius = QStringLiteral("c1Radius") static
Definition at line 107 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertPointExpressionsToV0_2_0(), and VPatternConverter::FixPointExpressionsToV0_2_0().
strC2Radius
const QString strC2Radius = QStringLiteral("c2Radius") static
Definition at line 108 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertPointExpressionsToV0_2_0(), and VPatternConverter::FixPointExpressionsToV0_2_0().
strCenterAnchor
const QString strCenterAnchor = QStringLiteral("centerAnchor") static
Definition at line 237 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strCenterPin
const QString strCenterPin = QStringLiteral("centerPin") static
Definition at line 229 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strChild
const QString strChild = QStringLiteral("child") static
Definition at line 133 of file vpatternconverter.cpp.
Referenced by VPatternConverter::SaveChildrenToolUnionToV0_2_4().
strChildren
const QString strChildren = QStringLiteral("children") static
Definition at line 132 of file vpatternconverter.cpp.
Referenced by VPatternConverter::SaveChildrenToolUnionToV0_2_4(), and VPatternConverter::TagUnionDetailsToV0_4_0().
strClosed
const QString strClosed = QStringLiteral("closed") static
Definition at line 154 of file vpatternconverter.cpp.
strColor
const QString strColor = QStringLiteral("color") static
Definition at line 124 of file vpatternconverter.cpp.
Referenced by VPatternConverter::RemoveColorToolCutV0_3_1().
strCompanyName
const QString strCompanyName = QStringLiteral("company") static
Definition at line 180 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1(), and VPatternConverter::PortPatternLabeltoV0_6_0().
strCRadius
const QString strCRadius = QStringLiteral("cRadius") static
Definition at line 109 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertPointExpressionsToV0_2_0(), and VPatternConverter::FixPointExpressionsToV0_2_0().
strCurve
const QString strCurve = QStringLiteral("curve") static
Definition at line 136 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strCurve1
const QString strCurve1 = QStringLiteral("curve1") static
Definition at line 137 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strCurve2
const QString strCurve2 = QStringLiteral("curve2") static
Definition at line 138 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strCurveIntersectAxis
const QString strCurveIntersectAxis = QStringLiteral("curveIntersectAxis") static
Definition at line 135 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strCustomerName
const QString strCustomerName = QStringLiteral("customer") static
Definition at line 181 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1(), and VPatternConverter::PortPatternLabeltoV0_6_0().
strCutArc
const QString strCutArc = QStringLiteral("cutArc") static
Definition at line 119 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixCutPoint(), and VPatternConverter::RemoveColorToolCutV0_3_1().
strCutSpline
const QString strCutSpline = QStringLiteral("cutSpline") static
Definition at line 122 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixCutPoint(), VPatternConverter::FixSubPaths(), and VPatternConverter::RemoveColorToolCutV0_3_1().
strCutSplinePath
const QString strCutSplinePath = QStringLiteral("cutSplinePath") static
Definition at line 123 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixCutPoint(), VPatternConverter::FixSubPaths(), and VPatternConverter::RemoveColorToolCutV0_3_1().
strData
const QString strData = QStringLiteral("data") static
Definition at line 159 of file vpatternconverter.cpp.
Referenced by VPatternConverter::PortPieceLabelstoV0_6_0(), VPatternConverter::RemoveUnusedTagsV0_6_0(), VPatternConverter::TagDetailToV0_4_0(), VPatternConverter::toVersion0_4_4(), and VPatternConverter::toVersion0_6_5().
strDescription
const QString strDescription = QStringLiteral("description") static
Definition at line 175 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1().
strDet
const QString strDet = QStringLiteral("det") static
Definition at line 169 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagUnionDetailsToV0_4_0().
strDetail
const QString strDetail = QStringLiteral("detail") static
Definition at line 149 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagDetailToV0_4_0(), and VPatternConverter::toVersion0_6_6().
strDetails
const QString strDetails = QStringLiteral("details") static
Definition at line 147 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_6().
strDraftBlock
const QString strDraftBlock = QStringLiteral("draftBlock") static
Definition at line 146 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_6().
strDraw
const QString strDraw = QStringLiteral("draw") static
Definition at line 145 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_6().
strElArc
const QString strElArc = QStringLiteral("elArc") static
Definition at line 222 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strFirstArc
const QString strFirstArc = QStringLiteral("firstArc") static
Definition at line 143 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strForbidFlipping
const QString strForbidFlipping = QStringLiteral("forbidFlipping") static
Definition at line 165 of file vpatternconverter.cpp.
strFormula
const QString strFormula = QStringLiteral("formula") static
Definition at line 100 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixIncrementsToV0_2_0().
strFSIncrement
const QString strFSIncrement = QStringLiteral("sfIncrement") static
Definition at line 187 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddLabelTemplateLineV0_6_0().
strGradation
const QString strGradation = QStringLiteral("gradation") static
Definition at line 177 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1().
strGrainline
const QString strGrainline = QStringLiteral("grainline") static
Definition at line 161 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagDetailToV0_4_0(), and VPatternConverter::toVersion0_6_5().
strHair
const QString strHair = QStringLiteral("hair") static
Definition at line 212 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strHeight
const QString strHeight = QStringLiteral("height") static
Definition at line 156 of file vpatternconverter.cpp.
Referenced by VPatternConverter::LabelTagToV0_4_4().
strId
const QString strId = QStringLiteral("id") static
Definition at line 101 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixCutPoint(), VPatternConverter::FixIncrementsToV0_2_0(), and VPatternConverter::ParseModelingToV0_2_4().
strIdObject
const QString strIdObject = QStringLiteral("idObject") static
Definition at line 131 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths(), VPatternConverter::GetUnionDetailNodesV0_4_0(), VPatternConverter::ParseModelingToV0_2_4(), and VPatternConverter::TagDetailToV0_4_0().
strIdTool
const QString strIdTool = QStringLiteral("idTool") static
Definition at line 130 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ParseModelingToV0_2_4().
strImage
const QString strImage = QStringLiteral("image") static
Definition at line 173 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1().
strIncrement
const QString strIncrement = QStringLiteral("increment") static
Definition at line 126 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixIncrementsToV0_2_0().
strIncrements
const QString strIncrements = QStringLiteral("increments") static
Definition at line 127 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagIncrementsV0_1_4().
strInLayout
const QString strInLayout = QStringLiteral("inLayout") static
Definition at line 166 of file vpatternconverter.cpp.
strItalic
const QString strItalic = QStringLiteral("italic") static
Definition at line 185 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddLabelTemplateLineV0_6_0().
strKAsm1
const QString strKAsm1 = QStringLiteral("kAsm1") static
Definition at line 115 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertPathPointExpressionsToV0_2_0(), and VPatternConverter::FixPathPointExpressionsToV0_2_0().
strKAsm2
const QString strKAsm2 = QStringLiteral("kAsm2") static
Definition at line 116 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertPathPointExpressionsToV0_2_0(), and VPatternConverter::FixPathPointExpressionsToV0_2_0().
strKGrowth
const QString strKGrowth = QStringLiteral("kgrowth") static
Definition at line 102 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixIncrementsToV0_2_0().
strKSize
const QString strKSize = QStringLiteral("ksize") static
Definition at line 103 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixIncrementsToV0_2_0().
strLength
const QString strLength = QStringLiteral("length") static
Definition at line 105 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertArcExpressionsToV0_2_0(), VPatternConverter::ConvertPointExpressionsToV0_2_0(), VPatternConverter::FixArcExpressionsToV0_2_0(), and VPatternConverter::FixPointExpressionsToV0_2_0().
strLetter
const QString strLetter = QStringLiteral("letter") static
Definition at line 192 of file vpatternconverter.cpp.
Referenced by VPatternConverter::PortPieceLabelstoV0_6_0().
strLine
const QString strLine = QStringLiteral("line") static
Definition at line 182 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddLabelTemplateLineV0_6_0(), and VPatternConverter::toVersion0_6_1().
strLineColor
const QString strLineColor = QStringLiteral("lineColor") static
Definition at line 220 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_4().
strLineType
const QString strLineType = QStringLiteral("lineType") static
Definition at line 218 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1(), and VPatternConverter::toVersion0_6_4().
strLineWeight
const QString strLineWeight = QStringLiteral("lineWeight") static
Definition at line 219 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_4().
strMaterial
const QString strMaterial = QStringLiteral("material") static
Definition at line 193 of file vpatternconverter.cpp.
Referenced by VPatternConverter::PortPieceLabelstoV0_6_0().
strMCP
const QString strMCP = QStringLiteral("mcp") static
Definition at line 191 of file vpatternconverter.cpp.
Referenced by VPatternConverter::RemoveUnusedTagsV0_6_0().
strMeasurements
const QString strMeasurements = QStringLiteral("measurements") static
Definition at line 125 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagMeasurementsV0_1_4().
strModeling
const QString strModeling = QStringLiteral("modeling") static
Definition at line 128 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths(), VPatternConverter::FixToolUnionToV0_2_4(), and VPatternConverter::TagRemoveAttributeTypeObjectInV0_4_0().
strModelingPath
const QString strModelingPath = QStringLiteral("modelingPath") static
Definition at line 139 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strModelingSpline
const QString strModelingSpline = QStringLiteral("modelingSpline") static
Definition at line 140 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strMx
const QString strMx = QStringLiteral("mx") static
Definition at line 163 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagDetailToV0_4_0().
strMy
const QString strMy = QStringLiteral("my") static
Definition at line 164 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagDetailToV0_4_0().
strName
const QString strName = QStringLiteral("name") static
Definition at line 98 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixIncrementsToV0_2_0().
strNode
const QString strNode = QStringLiteral("node") static
Definition at line 157 of file vpatternconverter.cpp.
Referenced by VPatternConverter::GetUnionDetailNodesV0_4_0(), VPatternConverter::TagDetailToV0_4_0(), and VPatternConverter::toVersion0_6_1().
strNodes
const QString strNodes = QStringLiteral("nodes") static
Definition at line 158 of file vpatternconverter.cpp.
Referenced by VPatternConverter::GetUnionChildrenNodesV0_4_0(), VPatternConverter::GetUnionDetailNodesV0_4_0(), and VPatternConverter::TagDetailToV0_4_0().
strNodeType
const QString strNodeType = QStringLiteral("nodeType") static
Definition at line 168 of file vpatternconverter.cpp.
strNotch
const QString strNotch = QStringLiteral("notch") static
Definition at line 200 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strNotchAngle
const QString strNotchAngle = QStringLiteral("notchAngle") static
Definition at line 202 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strNotchCount
const QString strNotchCount = QStringLiteral("notchCount") static
Definition at line 201 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strNotchSubType
const QString strNotchSubType = QStringLiteral("notchSubtype") static
Definition at line 204 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strNotchType
const QString strNotchType = QStringLiteral("notchType") static
Definition at line 203 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strNotes
const QString strNotes = QStringLiteral("notes") static
Definition at line 176 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1().
strOne
const QString strOne = QStringLiteral("one") static
Definition at line 214 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strPassmark
const QString strPassmark = QStringLiteral("passmark") static
Definition at line 196 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strPassmarkAngle
const QString strPassmarkAngle = QStringLiteral("passmarkAngle") static
Definition at line 198 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strPassmarkLine
const QString strPassmarkLine = QStringLiteral("passmarkLine") static
Definition at line 197 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strPath
const QString strPath = QStringLiteral("path") static
Definition at line 117 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagMeasurementsToV0_2_0(), and VPatternConverter::toVersion0_6_1().
strPathPoint
const QString strPathPoint = QStringLiteral("pathPoint") static
Definition at line 114 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertPathPointExpressionsToV0_2_0(), and VPatternConverter::FixPathPointExpressionsToV0_2_0().
strPatternInfo
const QString strPatternInfo = QStringLiteral("patternInfo") static
Definition at line 160 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagDetailToV0_4_0(), VPatternConverter::toVersion0_4_4(), and VPatternConverter::toVersion0_6_5().
strPatternLabel
const QString strPatternLabel = QStringLiteral("patternLabel") static
Definition at line 172 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1().
strPatternName
const QString strPatternName = QStringLiteral("patternName") static
Definition at line 178 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1(), and VPatternConverter::PortPatternLabeltoV0_6_0().
strPatternNum
const QString strPatternNum = QStringLiteral("patternNumber") static
Definition at line 179 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1(), and VPatternConverter::PortPatternLabeltoV0_6_0().
strPenStyle
const QString strPenStyle = QStringLiteral("penStyle") static
Definition at line 221 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strPiece
const QString strPiece = QStringLiteral("piece") static
Definition at line 150 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_6().
strPieces
const QString strPieces = QStringLiteral("pieces") static
Definition at line 148 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_6().
strPin
const QString strPin = QStringLiteral("pin") static
Definition at line 225 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strPins
const QString strPins = QStringLiteral("pins") static
Definition at line 226 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strPlacement
const QString strPlacement = QStringLiteral("placement") static
Definition at line 195 of file vpatternconverter.cpp.
Referenced by VPatternConverter::PortPieceLabelstoV0_6_0().
strPoint
const QString strPoint = QStringLiteral("point") static
Definition at line 104 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertPointExpressionsToV0_2_0(), VPatternConverter::FixCutPoint(), VPatternConverter::FixPointExpressionsToV0_2_0(), VPatternConverter::FixSubPaths(), VPatternConverter::RemoveColorToolCutV0_3_1(), VPatternConverter::toVersion0_6_1(), VPatternConverter::toVersion0_6_4(), and VPatternConverter::toVersion0_6_5().
strPointFromArcAndTangent
const QString strPointFromArcAndTangent = QStringLiteral("pointFromArcAndTangent") static
Definition at line 141 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strPointOfIntersectionArcs
const QString strPointOfIntersectionArcs = QStringLiteral("pointOfIntersectionArcs") static
Definition at line 142 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strPointOfIntersectionCurves
const QString strPointOfIntersectionCurves = QStringLiteral("pointOfIntersectionCurves") static
Definition at line 134 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strRadius
const QString strRadius = QStringLiteral("radius") static
Definition at line 113 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ConvertArcExpressionsToV0_2_0(), and VPatternConverter::FixArcExpressionsToV0_2_0().
strReadOnly
const QString strReadOnly = QStringLiteral("readOnly") static
Definition at line 171 of file vpatternconverter.cpp.
Referenced by VPatternConverter::IsReadOnly().
strReverse
const QString strReverse = QStringLiteral("reverse") static
Definition at line 162 of file vpatternconverter.cpp.
Referenced by VPatternConverter::GetUnionDetailNodesV0_4_0(), and VPatternConverter::TagDetailToV0_4_0().
strSeamAllowance
const QString strSeamAllowance = QStringLiteral("seamAllowance") static
Definition at line 167 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagDetailToV0_4_0().
strSecondArc
const QString strSecondArc = QStringLiteral("secondArc") static
Definition at line 144 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixSubPaths().
strShowDate
const QString strShowDate = QStringLiteral("showDate") static
Definition at line 188 of file vpatternconverter.cpp.
Referenced by VPatternConverter::PortPatternLabeltoV0_6_0(), and VPatternConverter::RemoveUnusedTagsV0_6_0().
strShowMeasurements
const QString strShowMeasurements = QStringLiteral("showMeasurements") static
Definition at line 189 of file vpatternconverter.cpp.
Referenced by VPatternConverter::PortPatternLabeltoV0_6_0(), and VPatternConverter::RemoveUnusedTagsV0_6_0().
strShowNotch
const QString strShowNotch = QStringLiteral("showNotch") static
Definition at line 205 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strShowSecond
const QString strShowSecond = QStringLiteral("showSecondNotch") static
Definition at line 206 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strShowSecondPassmark
const QString strShowSecondPassmark = QStringLiteral("showSecondPassmark") static
Definition at line 199 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strSize
const QString strSize = QStringLiteral("size") static
Definition at line 190 of file vpatternconverter.cpp.
Referenced by VPatternConverter::PortPatternLabeltoV0_6_0(), and VPatternConverter::RemoveUnusedTagsV0_6_0().
strSlitNotch
const QString strSlitNotch = QStringLiteral("slit") static
Definition at line 207 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strSolidLine
const QString strSolidLine = QStringLiteral("solidLine") static
Definition at line 213 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strSpline
const QString strSpline = QStringLiteral("spline") static
Definition at line 120 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixCutPoint(), VPatternConverter::FixSubPaths(), and VPatternConverter::toVersion0_6_1().
strSplinePath
const QString strSplinePath = QStringLiteral("splinePath") static
Definition at line 121 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixCutPoint(), and VPatternConverter::FixSubPaths().
strSupplement
const QString strSupplement = QStringLiteral("supplement") static
Definition at line 153 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagDetailToV0_4_0().
strT_Notch
const QString strT_Notch = QStringLiteral("tNotch") static
Definition at line 211 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strText
const QString strText = QStringLiteral("text") static
Definition at line 183 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddLabelTemplateLineV0_6_0().
strThree
const QString strThree = QStringLiteral("three") static
Definition at line 216 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strTMark
const QString strTMark = QStringLiteral("tMark") static
Definition at line 210 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strTools
const QString strTools = QStringLiteral("tools") static
Definition at line 129 of file vpatternconverter.cpp.
Referenced by VPatternConverter::ParseModelingToV0_2_4(), VPatternConverter::TagUnionDetailsToV0_4_0(), and VPatternConverter::toVersion0_6_6().
strTopAnchor
const QString strTopAnchor = QStringLiteral("topAnchor") static
Definition at line 238 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strTopLeftAnchor
const QString strTopLeftAnchor = QStringLiteral("topLeftAnchor") static
Definition at line 235 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strTopLeftPin
const QString strTopLeftPin = QStringLiteral("topLeftPin") static
Definition at line 227 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strTopPin
const QString strTopPin = QStringLiteral("topPin") static
Definition at line 230 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_5().
strTrue
const QString strTrue = QStringLiteral("true") static
Definition at line 223 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strTwo
const QString strTwo = QStringLiteral("two") static
Definition at line 215 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strType
const QString strType = QStringLiteral("type") static
Definition at line 118 of file vpatternconverter.cpp.
Referenced by VPatternConverter::FixCutPoint(), VPatternConverter::FixSubPaths(), VPatternConverter::GetUnionDetailNodesV0_4_0(), VPatternConverter::RemoveColorToolCutV0_3_1(), VPatternConverter::TagDetailToV0_4_0(), VPatternConverter::TagMeasurementsToV0_2_0(), VPatternConverter::toVersion0_6_4(), VPatternConverter::toVersion0_6_5(), and VPatternConverter::toVersion0_6_6().
strTypeLine
const QString strTypeLine = QStringLiteral("typeLine") static
Definition at line 217 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strTypeObject
const QString strTypeObject = QStringLiteral("typeObject") static
Definition at line 170 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagRemoveAttributeTypeObjectInV0_4_0().
strUnion
const QString strUnion = QStringLiteral("union") static
Definition at line 152 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_6().
strUnionDetail
const QString strUnionDetail = QStringLiteral("unionDetail") static
Definition at line 151 of file vpatternconverter.cpp.
strUnit
const QString strUnit = QStringLiteral("unit") static
Definition at line 96 of file vpatternconverter.cpp.
Referenced by VPatternConverter::AddTagPatternLabelV0_5_1(), VPatternConverter::LabelTagToV0_4_4(), VPatternConverter::MUnitV0_1_4(), VPatternConverter::TagMeasurementsToV0_2_0(), and VPatternConverter::TagUnitToV0_2_0().
strUserDefined
const QString strUserDefined = QStringLiteral("userDef") static
Definition at line 194 of file vpatternconverter.cpp.
Referenced by VPatternConverter::PortPieceLabelstoV0_6_0().
strV_External
const QString strV_External = QStringLiteral("vExternal") static
Definition at line 209 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strVersion
const QString strVersion = QStringLiteral("version") static
Definition at line 97 of file vpatternconverter.cpp.
Referenced by VPatternConverter::TagDetailToV0_4_0(), and VPatternConverter::TagUnitToV0_2_0().
strVMark
const QString strVMark = QStringLiteral("vMark") static
Definition at line 208 of file vpatternconverter.cpp.
Referenced by VPatternConverter::toVersion0_6_1().
strWidth
const QString strWidth = QStringLiteral("width") static
Definition at line 155 of file vpatternconverter.cpp.
Referenced by VPatternConverter::LabelTagToV0_4_4().