Seamly2D: VLabelTemplate Class Reference
VLabelTemplate Class Reference
#include <vlabeltemplate.h>
Public Member Functions
VLabelTemplate ()
virtual ~VLabelTemplate () Q_DECL_EQ_DEFAULT
void CreateEmptyTemplate ()
void AddLines (const QVector< VLabelTemplateLine > &lines)
QVector< VLabelTemplateLine > ReadLines () const
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit MUnit () const
virtual void setXMLContent (const QString &fileName)
virtual bool SaveDocument (const QString &fileName, QString &error)
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Static Public Attributes
static const QString TagTemplate = QStringLiteral("template")
static const QString TagLines = QStringLiteral("lines")
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Additional Inherited Members
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Detailed Description
Definition at line 57 of file vlabeltemplate.h.
Constructor & Destructor Documentation
VLabelTemplate()
VLabelTemplate::VLabelTemplate ()
Definition at line 59 of file vlabeltemplate.cpp.
~VLabelTemplate()
virtual VLabelTemplate::~VLabelTemplate () virtual
Member Function Documentation
AddLines()
void VLabelTemplate::AddLines (const QVector< VLabelTemplateLine > & lines)
Definition at line 81 of file vlabeltemplate.cpp.
References VDomDocument::SetLabelTemplate(), and TagLines.
Referenced by EditLabelTemplateDialog::ExportTemplate().
CreateEmptyTemplate()
void VLabelTemplate::CreateEmptyTemplate ()
Definition at line 64 of file vlabeltemplate.cpp.
References VLabelTemplateConverter::LabelTemplateMaxVerStr, TagLines, TagTemplate, and VDomDocument::TagVersion.
Referenced by EditLabelTemplateDialog::ExportTemplate().
ReadLines()
QVector< VLabelTemplateLine > VLabelTemplate::ReadLines () const
Definition at line 94 of file vlabeltemplate.cpp.
References VDomDocument::GetLabelTemplate(), and TagLines.
Referenced by QT_WARNING_POP::createUnion(), EditLabelTemplateDialog::ImportTemplate(), and PatternPieceDialog::initializeLabelsTab().
Member Data Documentation
TagLines
const QString VLabelTemplate::TagLines = QStringLiteral("lines") static
Definition at line 64 of file vlabeltemplate.h.
Referenced by AddLines(), CreateEmptyTemplate(), and ReadLines().
TagTemplate
const QString VLabelTemplate::TagTemplate = QStringLiteral("template") static
Definition at line 63 of file vlabeltemplate.h.
Referenced by CreateEmptyTemplate().
The documentation for this class was generated from the following files:
src/libs/vformat/vlabeltemplate.h
src/libs/vformat/vlabeltemplate.cpp