Seamly2D: CErrorHandler Class Reference
CErrorHandler Class Reference
Public Member Functions
void warning (const xercesc::SAXParseException &ex)
void error (const xercesc::SAXParseException &ex)
void fatalError (const xercesc::SAXParseException &ex)
void resetErrors ()
Private Member Functions
void throwException (const xercesc::SAXParseException &ex)
Detailed Description
Definition at line 580 of file vdomdocument.cpp.
Member Function Documentation
error()
void CErrorHandler::error (const xercesc::SAXParseException & ex)
Definition at line 600 of file vdomdocument.cpp.
References throwException().
fatalError()
void CErrorHandler::fatalError (const xercesc::SAXParseException & ex)
Definition at line 604 of file vdomdocument.cpp.
References throwException().
resetErrors()
void CErrorHandler::resetErrors ()
Definition at line 608 of file vdomdocument.cpp.
throwException()
void CErrorHandler::throwException (const xercesc::SAXParseException & ex) private
Definition at line 590 of file vdomdocument.cpp.
Referenced by error(), fatalError(), and warning().
warning()
void CErrorHandler::warning (const xercesc::SAXParseException & ex)
Definition at line 596 of file vdomdocument.cpp.
References throwException().
The documentation for this class was generated from the following file:
src/libs/ifc/xml/vdomdocument.cpp