Seamly2D: ShowInfoDialog Class Reference
ShowInfoDialog Class Reference
#include <show_info_dialog.h>
Public Member Functions
ShowInfoDialog (VPattern *doc, QWidget *parent=nullptr)
virtual ~ShowInfoDialog ()
Protected Member Functions
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
Private Member Functions
void copyToClipboard ()
void sendToPrinter ()
void exportPdf ()
Private Attributes
Ui::ShowInfoDialog * ui
VPattern * doc
bool m_isInitialized
Detailed Description
Definition at line 42 of file show_info_dialog.h.
Constructor & Destructor Documentation
ShowInfoDialog()
ShowInfoDialog::ShowInfoDialog (VPattern * doc, QWidget * parent = nullptr) explicit
Definition at line 61 of file show_info_dialog.cpp.
References copyToClipboard(), doc, exportPdf(), VAbstractPattern::GetCompanyName(), VAbstractPattern::GetCustomerName(), VAbstractPattern::GetDescription(), VAbstractPattern::GetImage(), VAbstractPattern::GetNotes(), VAbstractPattern::GetPatternName(), VAbstractPattern::GetPatternNumber(), VAbstractPattern::GetVersion(), VDomDocument::measurementUnits(), VAbstractPattern::MPath(), qApp, sendToPrinter(), ui, and UnitsToStr().
~ShowInfoDialog()
ShowInfoDialog::~ShowInfoDialog () virtual
Definition at line 114 of file show_info_dialog.cpp.
References ui.
Member Function Documentation
copyToClipboard()
void ShowInfoDialog::copyToClipboard () private
Definition at line 148 of file show_info_dialog.cpp.
References ui.
Referenced by ShowInfoDialog().
exportPdf()
void ShowInfoDialog::exportPdf () private
Definition at line 177 of file show_info_dialog.cpp.
References doc, VAbstractPattern::GetPatternName(), and ui.
Referenced by ShowInfoDialog().
sendToPrinter()
void ShowInfoDialog::sendToPrinter () private
Definition at line 161 of file show_info_dialog.cpp.
References ui.
Referenced by ShowInfoDialog().
showEvent()
void ShowInfoDialog::showEvent (QShowEvent * event) protected virtual
Definition at line 125 of file show_info_dialog.cpp.
References m_isInitialized.
Member Data Documentation
doc
VPattern* ShowInfoDialog::doc private
Definition at line 55 of file show_info_dialog.h.
Referenced by exportPdf(), and ShowInfoDialog().
m_isInitialized
bool ShowInfoDialog::m_isInitialized private
Definition at line 56 of file show_info_dialog.h.
Referenced by showEvent().
ui
Ui::ShowInfoDialog* ShowInfoDialog::ui private
Definition at line 54 of file show_info_dialog.h.
Referenced by copyToClipboard(), exportPdf(), sendToPrinter(), ShowInfoDialog(), and ~ShowInfoDialog().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/show_info_dialog.h
src/app/seamly2d/dialogs/show_info_dialog.cpp