Seamly2D: TMainWindow Class Reference
TMainWindow Class Reference
#include <tmainwindow.h>
Public Slots
virtual void ShowToolTip (const QString &toolTip) Q_DECL_OVERRIDE
virtual void zoomToSelected () Q_DECL_OVERRIDE
virtual void updateGroups () Q_DECL_OVERRIDE
Public Slots inherited from VAbstractMainWindow
virtual void ShowToolTip (const QString &toolTip)=0
virtual void updateGroups ()=0
virtual void zoomToSelected ()=0
Public Member Functions
TMainWindow (QWidget *parent=nullptr)
virtual ~TMainWindow () Q_DECL_OVERRIDE
QString CurrentFile () const
void RetranslateTable ()
void SetBaseMHeight (int height)
void SetBaseMSize (int size)
void SetPUnit (Unit unit)
bool LoadFile (const QString &path)
Public Member Functions inherited from VAbstractMainWindow
VAbstractMainWindow (QWidget *parent=nullptr)
virtual ~VAbstractMainWindow () Q_DECL_EQ_DEFAULT
Protected Member Functions
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
virtual void exportToCSVData (const QString &fileName, const DialogExportToCSV &dialog) Q_DECL_FINAL
void handleExportToCSV ()
Protected Member Functions inherited from VAbstractMainWindow
bool ContinueFormatRewrite (const QString &currentFormatVersion, const QString &maxFormatVersion)
void ToolBarStyle (QToolBar *bar)
Private Types
enum { MaxRecentFiles = 5 }
Private Slots
void FileNew ()
void OpenIndividual ()
void OpenMultisize ()
void OpenTemplate ()
void CreateFromExisting ()
void handleBodyScanner2 ()
void Preferences ()
void ToolBarStyles ()
void print ()
void printPages (QPrinter *printer)
bool FileSave ()
bool FileSaveAs ()
void AboutToShowWindowMenu ()
void ShowWindow () const
void SaveGivenName ()
void SaveFamilyName ()
void SaveEmail ()
void SaveGender (int index)
void SaveBirthDate (const QDate &date)
void SaveNotes ()
void SavePMSystem (int index)
void Remove ()
void MoveTop ()
void MoveUp ()
void MoveDown ()
void MoveBottom ()
void Fx ()
void AddCustom ()
void AddKnown ()
void ImportFromPattern ()
void ChangedSize (int index)
void ChangedHeight (int index)
void ShowMData ()
void SaveMName (const QString &text)
void SaveMValue ()
void SaveMBaseValue (double value)
void SaveMSizeIncrease (double value)
void SaveMHeightIncrease (double value)
void SaveMDescription ()
void SaveMFullName ()
void PatternUnitChanged (int index)
Private Member Functions
void SetupMenu ()
void InitWindow ()
void initializeTable ()
void SetDecimals ()
void InitUnits ()
void InitComboBoxUnits ()
void InitGender (QComboBox *gender)
void ShowNewMData (bool fresh)
void ShowUnits ()
void ShowHeaderUnits (QTableWidget *table, int column, const QString &unit)
void UpdateRecentFileActions ()
void MeasurementsWasSaved (bool saved)
void SetCurrentFile (const QString &fileName)
bool SaveMeasurements (const QString &fileName, QString &error)
bool MaybeSave ()
QTableWidgetItem * AddCell (const QString &text, int row, int column, int aligment, bool ok=true)
Q_REQUIRED_RESULT QComboBox * SetGradationList (QLabel *label, const QStringList &list)
void SetDefaultHeight (int value)
void SetDefaultSize (int value)
void RefreshData (bool freshCall=false)
void RefreshTable (bool freshCall=false)
QString GetCustomName () const
QString ClearCustomName (const QString &name) const
bool EvalFormula (const QString &formula, bool fromUser, VContainer *data, QLabel *label)
QString getMeasurementNumber (const QString &name)
void ShowMDiagram (const QString &name)
void Open (const QString &pathTo, const QString &filter)
void UpdatePadlock (bool ro)
void MeasurementGUI ()
void Controls ()
void MFields (bool enabled)
void UpdateWindowTitle ()
void ReadSettings ()
void WriteSettings ()
QStringList FilterMeasurements (const QStringList &mNew, const QStringList &mFilter)
void UpdatePatternUnit ()
bool LoadFromExistingFile (const QString &path)
void CreateWindowMenu (QMenu *menu)
bool IgnoreLocking (int error, const QString &path)
template<class T >
void HackWidget (T **widget)
void copyToClipboard ()
copyToClipboard copy dialog selection to clipboard as comma separated values.
Private Attributes
Ui::TMainWindow * ui
MeasurementDoc * individualMeasurements
VContainer * data
Unit mUnit
Unit pUnit
MeasurementsType mType
qreal currentSize
qreal currentHeight
QString curFile
QComboBox * gradationHeights
QComboBox * gradationSizes
QComboBox * comboBoxUnits
std::shared_ptr< VLockGuard< char > > lock
QSharedPointer< VTableSearch > search
QLabel * labelGradationHeights
QLabel * labelGradationSizes
QLabel * labelPatternUnit
QAction * actionDockDiagram
bool dockDiagramVisible
bool isInitialized
bool m_isReadOnly
QAction * recentFileActs [MaxRecentFiles]
QAction * separatorAct
QVector< QObject * > hackedWidgets
Additional Inherited Members
Protected Slots inherited from VAbstractMainWindow
void WindowsLocale ()
void exportToCSV (QString &file)
Protected Attributes inherited from VAbstractMainWindow
int m_curFileFormatVersion
QString m_curFileFormatVersionStr
Detailed Description
Definition at line 77 of file tmainwindow.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
MaxRecentFiles
Definition at line 190 of file tmainwindow.h.
Constructor & Destructor Documentation
TMainWindow()
TMainWindow::TMainWindow (QWidget * parent = nullptr) explicit
Definition at line 114 of file tmainwindow.cpp.
References Cm, Individual, MaxRecentFiles, qApp, ReadSettings(), recentFileActs, search, SetupMenu(), ui, and UpdateWindowTitle().
~TMainWindow()
TMainWindow::~TMainWindow () virtual
Definition at line 186 of file tmainwindow.cpp.
References data, individualMeasurements, and ui.
Member Function Documentation
AboutToShowWindowMenu
void TMainWindow::AboutToShowWindowMenu () private slot
Definition at line 1217 of file tmainwindow.cpp.
References CreateWindowMenu(), and ui.
AddCell()
QTableWidgetItem * TMainWindow::AddCell (const QString & text, int row, int column, int aligment, bool ok = true) private
Definition at line 2587 of file tmainwindow.cpp.
References ui.
Referenced by RefreshTable().
AddCustom
void TMainWindow::AddCustom () private slot
Definition at line 1546 of file tmainwindow.cpp.
References MeasurementDoc::addEmpty(), MeasurementDoc::AddEmptyAfter(), ColumnName, GetCustomName(), individualMeasurements, MeasurementsWasSaved(), RefreshData(), search, and ui.
AddKnown
void TMainWindow::AddKnown () private slot
Definition at line 1575 of file tmainwindow.cpp.
References MeasurementDoc::addEmpty(), MeasurementDoc::AddEmptyAfter(), ColumnName, Individual, individualMeasurements, MeasurementDoc::listKnown(), MeasurementsWasSaved(), mType, qApp, RefreshData(), search, and ui.
ChangedHeight
void TMainWindow::ChangedHeight (int index) private slot
Definition at line 1721 of file tmainwindow.cpp.
References currentHeight, gradationHeights, RefreshData(), search, and ui.
Referenced by InitWindow().
ChangedSize
void TMainWindow::ChangedSize (int index) private slot
Definition at line 1711 of file tmainwindow.cpp.
References currentSize, gradationSizes, RefreshData(), search, and ui.
Referenced by InitWindow().
changeEvent()
void TMainWindow::changeEvent (QEvent * event) protected virtual
Definition at line 643 of file tmainwindow.cpp.
References MeasurementDoc::BaseHeight(), MeasurementDoc::BaseSize(), comboBoxUnits, individualMeasurements, InitComboBoxUnits(), InitGender(), InitPMSystems(), labelGradationHeights, labelGradationSizes, labelPatternUnit, VDomDocument::measurementUnits(), mType, Multisize, qApp, ui, and UnitsToStr().
ClearCustomName()
QString TMainWindow::ClearCustomName (const QString & name) const private
Definition at line 2917 of file tmainwindow.cpp.
References CustomMSign.
Referenced by ShowNewMData().
closeEvent()
void TMainWindow::closeEvent (QCloseEvent * event) protected virtual
Definition at line 628 of file tmainwindow.cpp.
References MaybeSave(), and WriteSettings().
Controls()
void TMainWindow::Controls () private
Definition at line 2782 of file tmainwindow.cpp.
References ui.
Referenced by MeasurementGUI().
copyToClipboard()
void TMainWindow::copyToClipboard () private
copyToClipboard copy dialog selection to clipboard as comma separated values.
Definition at line 3434 of file tmainwindow.cpp.
References ui.
Referenced by InitWindow().
CreateFromExisting
void TMainWindow::CreateFromExisting () private slot
Definition at line 506 of file tmainwindow.cpp.
References fileDialog(), individualMeasurements, LoadFromExistingFile(), qApp, smisExt, and vitExt.
Referenced by SetupMenu().
CreateWindowMenu()
void TMainWindow::CreateWindowMenu (QMenu * menu) private
Definition at line 3233 of file tmainwindow.cpp.
References qApp, SCASSERT, and ShowWindow().
Referenced by AboutToShowWindowMenu().
CurrentFile()
QString TMainWindow::CurrentFile () const
Definition at line 194 of file tmainwindow.cpp.
References curFile.
Referenced by FileSaveAs(), and printPages().
EvalFormula()
bool TMainWindow::EvalFormula (const QString & formula, bool fromUser, VContainer * data, QLabel * label) private
Definition at line 2929 of file tmainwindow.cpp.
References data, VContainer::DataVariables(), qmu::QmuParserError::GetMsg(), mUnit, pUnit, qApp, UnitConvertor(), and UnitsToStr().
Referenced by SaveMValue(), and ShowNewMData().
eventFilter()
bool TMainWindow::eventFilter (QObject * object, QEvent * event) protected virtual
Definition at line 725 of file tmainwindow.cpp.
References qApp.
exportToCSVData()
void TMainWindow::exportToCSVData (const QString & fileName, const DialogExportToCSV & dialog) protected virtual
Implements VAbstractMainWindow.
Definition at line 779 of file tmainwindow.cpp.
References QxtCsvModel::insertColumn(), QxtCsvModel::insertRow(), mType, Multisize, DialogExportToCSV::SelectedMib(), DialogExportToCSV::Separator(), QxtCsvModel::setHeaderText(), QxtCsvModel::setText(), QxtCsvModel::toCSV(), ui, and DialogExportToCSV::WithHeader().
FileNew
void TMainWindow::FileNew () private slot
Definition at line 395 of file tmainwindow.cpp.
References NewMeasurementsDialog::baseHeight(), NewMeasurementsDialog::baseSize(), currentHeight, currentSize, data, individualMeasurements, InitWindow(), MeasurementDoc::isReadOnly(), VAbstractMainWindow::m_curFileFormatVersion, VAbstractMainWindow::m_curFileFormatVersionStr, m_isReadOnly, MeasurementGUI(), IndividualSizeConverter::MeasurementMaxVer, MultiSizeConverter::MeasurementMaxVer, IndividualSizeConverter::MeasurementMaxVerStr, MultiSizeConverter::MeasurementMaxVerStr, MeasurementsWasSaved(), NewMeasurementsDialog::measurementUnits(), mType, Multisize, mUnit, pUnit, qApp, SetCurrentFile(), MeasurementDoc::setHeight(), MeasurementDoc::setSize(), NewMeasurementsDialog::type(), and UpdatePadlock().
Referenced by SetupMenu().
FileSave
bool TMainWindow::FileSave () private slot
Definition at line 955 of file tmainwindow.cpp.
References VAbstractMainWindow::ContinueFormatRewrite(), curFile, FileSaveAs(), Individual, VAbstractMainWindow::m_curFileFormatVersion, VAbstractMainWindow::m_curFileFormatVersionStr, m_isReadOnly, IndividualSizeConverter::MeasurementMaxVer, MultiSizeConverter::MeasurementMaxVer, IndividualSizeConverter::MeasurementMaxVerStr, MultiSizeConverter::MeasurementMaxVerStr, mType, Multisize, and SaveMeasurements().
Referenced by MaybeSave(), and SetupMenu().
FileSaveAs
bool TMainWindow::FileSaveAs () private slot
Definition at line 1052 of file tmainwindow.cpp.
References curFile, CurrentFile(), fileDialog(), Individual, individualMeasurements, MeasurementDoc::isReadOnly(), lock, m_isReadOnly, mType, VCommonSettings::prepareMultisizeTables(), qApp, SaveMeasurements(), MeasurementDoc::SetReadOnly(), smisExt, smmsExt, UpdatePadlock(), UpdateWindowTitle(), vitExt, VlpCreateLock(), and vstExt.
Referenced by FileSave(), MaybeSave(), and SetupMenu().
FilterMeasurements()
QStringList TMainWindow::FilterMeasurements (const QStringList & mNew, const QStringList & mFilter) private
Definition at line 3057 of file tmainwindow.cpp.
References convertToList().
Referenced by ImportFromPattern().
Fx
void TMainWindow::Fx () private slot
Definition at line 1494 of file tmainwindow.cpp.
References ColumnName, data, VException::DetailedInformation(), VExceptionBadId::ErrorMessage(), EditFormulaDialog::GetFormula(), VContainer::GetVariable(), individualMeasurements, MeasurementsWasSaved(), mUnit, NULL_ID, qApp, RefreshData(), search, EditFormulaDialog::SetFormula(), MeasurementDoc::SetMValue(), EditFormulaDialog::setPostfix(), ui, and UnitsToStr().
Referenced by InitWindow().
GetCustomName()
QString TMainWindow::GetCustomName () const private
Definition at line 2768 of file tmainwindow.cpp.
References CustomMSign, data, VContainer::IsUnique(), measurement_, and qApp.
Referenced by AddCustom(), and SaveMName().
getMeasurementNumber()
QString TMainWindow::getMeasurementNumber (const QString & name) private
Definition at line 1834 of file tmainwindow.cpp.
References qApp.
Referenced by RefreshTable().
HackWidget()
template<class T > void TMainWindow::HackWidget (T ** widget) private
Definition at line 3417 of file tmainwindow.cpp.
References hackedWidgets.
Referenced by InitWindow().
handleBodyScanner2
void TMainWindow::handleBodyScanner2 () private slot
Definition at line 573 of file tmainwindow.cpp.
Referenced by SetupMenu().
handleExportToCSV()
void TMainWindow::handleExportToCSV () protected
Definition at line 835 of file tmainwindow.cpp.
References curFile, and VAbstractMainWindow::exportToCSV().
Referenced by SetupMenu().
IgnoreLocking()
bool TMainWindow::IgnoreLocking (int error, const QString & path) private
Definition at line 3270 of file tmainwindow.cpp.
References qApp, and V_EX_NOINPUT.
Referenced by LoadFile(), and LoadFromExistingFile().
ImportFromPattern
void TMainWindow::ImportFromPattern () private slot
Definition at line 1632 of file tmainwindow.cpp.
References MeasurementDoc::addEmpty(), MeasurementDoc::AddEmptyAfter(), ColumnName, VAbstractConverter::Convert(), VException::DetailedInformation(), VException::ErrorMessage(), fileDialog(), FilterMeasurements(), individualMeasurements, MeasurementDoc::ListAll(), lock, MeasurementsWasSaved(), VCommonSettings::PrepareStandardTemplates(), qApp, RefreshData(), search, sm2dExt, ui, and valExt.
InitComboBoxUnits()
void TMainWindow::InitComboBoxUnits () private
Definition at line 3398 of file tmainwindow.cpp.
References Cm, comboBoxUnits, Inch, Mm, SCASSERT, and UnitsToStr().
Referenced by changeEvent(), and InitUnits().
InitGender()
void TMainWindow::InitGender (QComboBox * gender) private
Definition at line 3407 of file tmainwindow.cpp.
References Female, Male, SCASSERT, and Unknown.
Referenced by changeEvent(), and InitWindow().
initializeTable()
void TMainWindow::initializeTable () private
Definition at line 2436 of file tmainwindow.cpp.
References ColumnBaseValue, ColumnFormula, ColumnInHeights, ColumnInSizes, mType, Multisize, ShowMData(), ShowUnits(), and ui.
Referenced by InitWindow().
InitUnits()
void TMainWindow::InitUnits () private
Definition at line 3376 of file tmainwindow.cpp.
References comboBoxUnits, InitComboBoxUnits(), labelPatternUnit, PatternUnitChanged(), pUnit, and ui.
Referenced by InitWindow().
InitWindow()
void TMainWindow::InitWindow () private
Definition at line 2261 of file tmainwindow.cpp.
References actionDockDiagram, MeasurementDoc::BaseHeight(), MeasurementDoc::BaseSize(), MeasurementDoc::BirthDate(), ChangedHeight(), ChangedSize(), copyToClipboard(), dockDiagramVisible, MeasurementDoc::Email(), MeasurementDoc::FamilyName(), Fx(), MeasurementDoc::Gender(), MeasurementDoc::GivenName(), gradationHeights, gradationSizes, HackWidget(), VTableSearch::HasResult(), VContainer::height(), individualMeasurements, InitGender(), initializeTable(), InitPMSystems(), InitUnits(), labelGradationHeights, labelGradationSizes, VDomDocument::measurementUnits(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), mType, Multisize, mUnit, NameRegExp(), MeasurementDoc::Notes(), MeasurementDoc::PMSystem(), qApp, Remove(), SaveBirthDate(), SaveEmail(), SaveFamilyName(), SaveGender(), SaveGivenName(), SaveMBaseValue(), SaveMDescription(), SaveMFullName(), SaveMHeightIncrease(), SaveMName(), SaveMSizeIncrease(), SaveMValue(), SaveNotes(), SavePMSystem(), SCASSERT, search, SetDecimals(), SetDefaultHeight(), SetDefaultSize(), SetGradationList(), VContainer::size(), ui, UnitsToStr(), MeasurementVariable::WholeListHeights(), and MeasurementVariable::WholeListSizes().
Referenced by FileNew(), LoadFile(), and LoadFromExistingFile().
LoadFile()
bool TMainWindow::LoadFile (const QString & path)
Definition at line 249 of file tmainwindow.cpp.
References MeasurementDoc::BaseHeight(), MeasurementDoc::BaseSize(), VAbstractConverter::Convert(), currentHeight, currentSize, data, VException::DetailedInformation(), MeasurementDoc::eachKnownNameIsValid(), VException::ErrorMessage(), VAbstractConverter::GetCurrentFormatVarsion(), VAbstractConverter::GetVersionStr(), IgnoreLocking(), individualMeasurements, InitWindow(), MeasurementDoc::isReadOnly(), lock, VAbstractMainWindow::m_curFileFormatVersion, VAbstractMainWindow::m_curFileFormatVersionStr, m_isReadOnly, MeasurementGUI(), VDomDocument::measurementUnits(), mType, Multisize, mUnit, pUnit, qApp, RefreshData(), SetCurrentFile(), MeasurementDoc::setHeight(), MeasurementDoc::setSize(), MeasurementDoc::setXMLContent(), MeasurementDoc::Type(), ui, Unknown, UpdatePadlock(), V_EX_NOINPUT, and VlpCreateLock().
Referenced by MApplication::event(), and Open().
LoadFromExistingFile()
bool TMainWindow::LoadFromExistingFile (const QString & path) private
Definition at line 3080 of file tmainwindow.cpp.
References MeasurementDoc::BaseHeight(), MeasurementDoc::BaseSize(), MeasurementDoc::ClearForExport(), VAbstractConverter::Convert(), currentHeight, currentSize, data, VException::DetailedInformation(), MeasurementDoc::eachKnownNameIsValid(), VException::ErrorMessage(), VAbstractConverter::GetCurrentFormatVarsion(), VAbstractConverter::GetVersionStr(), IgnoreLocking(), individualMeasurements, InitWindow(), MeasurementDoc::isReadOnly(), lock, VAbstractMainWindow::m_curFileFormatVersion, VAbstractMainWindow::m_curFileFormatVersionStr, m_isReadOnly, MeasurementGUI(), VDomDocument::measurementUnits(), mType, Multisize, mUnit, pUnit, qApp, RefreshData(), MeasurementDoc::setHeight(), MeasurementDoc::setSize(), MeasurementDoc::setXMLContent(), MeasurementDoc::Type(), ui, Unknown, UpdatePadlock(), V_EX_NOINPUT, and VlpCreateLock().
Referenced by CreateFromExisting().
MaybeSave()
bool TMainWindow::MaybeSave () private
Definition at line 2537 of file tmainwindow.cpp.
References curFile, FileSave(), FileSaveAs(), m_isReadOnly, and ui.
Referenced by closeEvent().
MeasurementGUI()
void TMainWindow::MeasurementGUI () private
Definition at line 3014 of file tmainwindow.cpp.
References ColumnName, Controls(), CustomMSign, and ui.
Referenced by FileNew(), LoadFile(), LoadFromExistingFile(), and ShowNewMData().
MeasurementsWasSaved()
void TMainWindow::MeasurementsWasSaved (bool saved) private
Definition at line 2486 of file tmainwindow.cpp.
References m_isReadOnly, and ui.
Referenced by AddCustom(), AddKnown(), FileNew(), Fx(), ImportFromPattern(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), Remove(), SaveBirthDate(), SaveEmail(), SaveFamilyName(), SaveGender(), SaveGivenName(), SaveMBaseValue(), SaveMDescription(), SaveMeasurements(), SaveMFullName(), SaveMHeightIncrease(), SaveMName(), SaveMSizeIncrease(), SaveMValue(), SaveNotes(), and SavePMSystem().
MFields()
void TMainWindow::MFields (bool enabled) private
Definition at line 2827 of file tmainwindow.cpp.
References mType, Multisize, and ui.
Referenced by Remove(), and ShowNewMData().
MoveBottom
void TMainWindow::MoveBottom () private slot
Definition at line 1476 of file tmainwindow.cpp.
References ColumnName, individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::MoveBottom(), RefreshData(), search, and ui.
Referenced by InitWindow().
MoveDown
void TMainWindow::MoveDown () private slot
Definition at line 1458 of file tmainwindow.cpp.
References ColumnName, individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::MoveDown(), RefreshData(), search, and ui.
Referenced by InitWindow().
MoveTop
void TMainWindow::MoveTop () private slot
Definition at line 1422 of file tmainwindow.cpp.
References ColumnName, individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::MoveTop(), RefreshData(), search, and ui.
Referenced by InitWindow().
MoveUp
void TMainWindow::MoveUp () private slot
Definition at line 1440 of file tmainwindow.cpp.
References ColumnName, individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::MoveUp(), RefreshData(), search, and ui.
Referenced by InitWindow().
Open()
void TMainWindow::Open (const QString & pathTo, const QString & filter) private
Definition at line 2979 of file tmainwindow.cpp.
References fileDialog(), individualMeasurements, LoadFile(), and qApp.
Referenced by OpenIndividual(), OpenMultisize(), and OpenTemplate().
OpenIndividual
void TMainWindow::OpenIndividual () private slot
Definition at line 446 of file tmainwindow.cpp.
References Open(), qApp, smisExt, and vitExt.
Referenced by SetupMenu().
OpenMultisize
void TMainWindow::OpenMultisize () private slot
Definition at line 472 of file tmainwindow.cpp.
References Open(), VCommonSettings::prepareMultisizeTables(), qApp, smmsExt, and vstExt.
Referenced by SetupMenu().
OpenTemplate
void TMainWindow::OpenTemplate () private slot
Definition at line 486 of file tmainwindow.cpp.
References individualMeasurements, lock, Open(), VCommonSettings::PrepareStandardTemplates(), qApp, SetCurrentFile(), smisExt, smmsExt, vitExt, and vstExt.
Referenced by SetupMenu().
PatternUnitChanged
void TMainWindow::PatternUnitChanged (int index) private slot
Definition at line 2150 of file tmainwindow.cpp.
References comboBoxUnits, pUnit, and UpdatePatternUnit().
Referenced by InitUnits().
Preferences
void TMainWindow::Preferences () private slot
Definition at line 601 of file tmainwindow.cpp.
References ToolBarStyles(), DialogSeamlyMePreferences::updateProperties(), and VAbstractMainWindow::WindowsLocale().
print
void TMainWindow::print () private slot
Definition at line 846 of file tmainwindow.cpp.
References mType, Multisize, printPages(), and ui.
Referenced by SetupMenu().
printPages
void TMainWindow::printPages (QPrinter * printer) private slot
Definition at line 877 of file tmainwindow.cpp.
References CurrentFile(), mType, Multisize, mUnit, PrintDPI, ui, and UnitsToStr().
Referenced by print().
ReadSettings()
void TMainWindow::ReadSettings () private
Definition at line 3033 of file tmainwindow.cpp.
References APP_VERSION, VCommonSettings::GetGeometry(), VCommonSettings::GetToolbarsState(), VCommonSettings::GetWindowState(), qApp, and ToolBarStyles().
Referenced by TMainWindow().
RefreshData()
void TMainWindow::RefreshData (bool freshCall = false) private
Definition at line 2651 of file tmainwindow.cpp.
References VContainer::ClearUniqueNames(), VContainer::ClearVariables(), data, individualMeasurements, Measurement, MeasurementDoc::readMeasurements(), and RefreshTable().
Referenced by AddCustom(), AddKnown(), ChangedHeight(), ChangedSize(), Fx(), ImportFromPattern(), LoadFile(), LoadFromExistingFile(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), Remove(), SaveMBaseValue(), SaveMDescription(), SaveMFullName(), SaveMHeightIncrease(), SaveMName(), SaveMSizeIncrease(), SaveMValue(), SetBaseMHeight(), and SetBaseMSize().
RefreshTable()
void TMainWindow::RefreshTable (bool freshCall = false) private
Definition at line 2661 of file tmainwindow.cpp.
References AddCell(), ColumnBaseValue, ColumnCalcValue, ColumnFormula, ColumnFullName, ColumnInHeights, ColumnInSizes, ColumnName, ColumnNumber, data, VContainer::DataMeasurements(), VContainer::DataVariables(), getMeasurementNumber(), Individual, mType, mUnit, pUnit, qApp, ShowUnits(), ui, and UnitConvertor().
Referenced by RefreshData(), RetranslateTable(), and UpdatePatternUnit().
Remove
void TMainWindow::Remove () private slot
Definition at line 1351 of file tmainwindow.cpp.
References individualMeasurements, MeasurementsWasSaved(), MFields(), mType, Multisize, RefreshData(), MeasurementDoc::Remove(), search, and ui.
Referenced by InitWindow().
RetranslateTable()
void TMainWindow::RetranslateTable ()
Definition at line 200 of file tmainwindow.cpp.
References individualMeasurements, RefreshTable(), search, and ui.
SaveBirthDate
void TMainWindow::SaveBirthDate (const QDate & date) private slot
Definition at line 1318 of file tmainwindow.cpp.
References MeasurementDoc::BirthDate(), individualMeasurements, MeasurementsWasSaved(), and MeasurementDoc::SetBirthDate().
Referenced by InitWindow().
SaveEmail
void TMainWindow::SaveEmail () private slot
Definition at line 1297 of file tmainwindow.cpp.
References MeasurementDoc::Email(), individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::SetEmail(), and ui.
Referenced by InitWindow().
SaveFamilyName
void TMainWindow::SaveFamilyName () private slot
Definition at line 1287 of file tmainwindow.cpp.
References MeasurementDoc::FamilyName(), individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::SetFamilyName(), and ui.
Referenced by InitWindow().
SaveGender
void TMainWindow::SaveGender (int index) private slot
Definition at line 1307 of file tmainwindow.cpp.
References MeasurementDoc::Gender(), individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::SetGender(), and ui.
Referenced by InitWindow().
SaveGivenName
void TMainWindow::SaveGivenName () private slot
Definition at line 1277 of file tmainwindow.cpp.
References MeasurementDoc::GivenName(), individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::SetGivenName(), and ui.
Referenced by InitWindow().
SaveMBaseValue
void TMainWindow::SaveMBaseValue (double value) private slot
Definition at line 2002 of file tmainwindow.cpp.
References ColumnName, individualMeasurements, MeasurementsWasSaved(), RefreshData(), search, MeasurementDoc::SetMBaseValue(), ShowNewMData(), and ui.
Referenced by InitWindow().
SaveMDescription
void TMainWindow::SaveMDescription () private slot
Definition at line 2077 of file tmainwindow.cpp.
References ColumnName, individualMeasurements, MeasurementsWasSaved(), RefreshData(), MeasurementDoc::SetMDescription(), and ui.
Referenced by InitWindow().
SaveMeasurements()
bool TMainWindow::SaveMeasurements (const QString & fileName, QString & error) private
Definition at line 2525 of file tmainwindow.cpp.
References individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::SaveDocument(), and SetCurrentFile().
Referenced by FileSave(), and FileSaveAs().
SaveMFullName
void TMainWindow::SaveMFullName () private slot
Definition at line 2104 of file tmainwindow.cpp.
References ColumnName, data, VException::DetailedInformation(), VExceptionBadId::ErrorMessage(), VContainer::GetVariable(), individualMeasurements, MeasurementsWasSaved(), RefreshData(), MeasurementDoc::SetMFullName(), and ui.
Referenced by InitWindow().
SaveMHeightIncrease
void TMainWindow::SaveMHeightIncrease (double value) private slot
Definition at line 2052 of file tmainwindow.cpp.
References ColumnName, individualMeasurements, MeasurementsWasSaved(), RefreshData(), search, MeasurementDoc::SetMHeightIncrease(), ShowNewMData(), and ui.
Referenced by InitWindow().
SaveMName
void TMainWindow::SaveMName (const QString & text) private slot
Definition at line 1864 of file tmainwindow.cpp.
References ColumnName, CustomMSign, data, VException::DetailedInformation(), VExceptionBadId::ErrorMessage(), GetCustomName(), VContainer::GetVariable(), individualMeasurements, VContainer::IsUnique(), MeasurementsWasSaved(), RefreshData(), search, MeasurementDoc::SetMName(), and ui.
Referenced by InitWindow(), and ShowNewMData().
SaveMSizeIncrease
void TMainWindow::SaveMSizeIncrease (double value) private slot
Definition at line 2027 of file tmainwindow.cpp.
References ColumnName, individualMeasurements, MeasurementsWasSaved(), RefreshData(), search, MeasurementDoc::SetMSizeIncrease(), ShowNewMData(), and ui.
Referenced by InitWindow().
SaveMValue
void TMainWindow::SaveMValue () private slot
Definition at line 1925 of file tmainwindow.cpp.
References ColumnCalcValue, ColumnFormula, ColumnName, data, VException::DetailedInformation(), VExceptionBadId::ErrorMessage(), EvalFormula(), VContainer::GetVariable(), individualMeasurements, MeasurementsWasSaved(), mUnit, qApp, RefreshData(), search, MeasurementDoc::SetMValue(), ui, and UnitsToStr().
Referenced by InitWindow().
SaveNotes
void TMainWindow::SaveNotes () private slot
Definition at line 1328 of file tmainwindow.cpp.
References individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::Notes(), MeasurementDoc::SetNotes(), and ui.
Referenced by InitWindow().
SavePMSystem
void TMainWindow::SavePMSystem (int index) private slot
Definition at line 1338 of file tmainwindow.cpp.
References individualMeasurements, MeasurementsWasSaved(), MeasurementDoc::PMSystem(), MeasurementDoc::SetPMSystem(), and ui.
Referenced by InitWindow().
SetBaseMHeight()
void TMainWindow::SetBaseMHeight (int height)
Definition at line 212 of file tmainwindow.cpp.
References Cm, currentHeight, individualMeasurements, mType, Multisize, mUnit, RefreshData(), ui, and UnitConvertor().
Referenced by MApplication::ParseCommandLine().
SetBaseMSize()
void TMainWindow::SetBaseMSize (int size)
Definition at line 227 of file tmainwindow.cpp.
References Cm, currentSize, individualMeasurements, mType, Multisize, mUnit, RefreshData(), ui, and UnitConvertor().
Referenced by MApplication::ParseCommandLine().
SetCurrentFile()
void TMainWindow::SetCurrentFile (const QString & fileName) private
Definition at line 2493 of file tmainwindow.cpp.
References curFile, MaxRecentFiles, qApp, ui, UpdateRecentFileActions(), and UpdateWindowTitle().
Referenced by FileNew(), LoadFile(), OpenTemplate(), and SaveMeasurements().
SetDecimals()
void TMainWindow::SetDecimals () private
Definition at line 3336 of file tmainwindow.cpp.
References Cm, Inch, Mm, mUnit, and ui.
Referenced by InitWindow().
SetDefaultHeight()
void TMainWindow::SetDefaultHeight (int value) private
Definition at line 2623 of file tmainwindow.cpp.
References currentHeight, and gradationHeights.
Referenced by InitWindow().
SetDefaultSize()
void TMainWindow::SetDefaultSize (int value) private
Definition at line 2637 of file tmainwindow.cpp.
References currentSize, and gradationSizes.
Referenced by InitWindow().
SetGradationList()
QComboBox * TMainWindow::SetGradationList (QLabel * label, const QStringList & list) private
Definition at line 2611 of file tmainwindow.cpp.
References ui.
Referenced by InitWindow().
SetPUnit()
void TMainWindow::SetPUnit (Unit unit)
Definition at line 242 of file tmainwindow.cpp.
References pUnit, and UpdatePatternUnit().
Referenced by MApplication::ParseCommandLine().
SetupMenu()
void TMainWindow::SetupMenu () private
Definition at line 2158 of file tmainwindow.cpp.
References CreateFromExisting(), FileNew(), FileSave(), FileSaveAs(), handleBodyScanner2(), handleExportToCSV(), OpenIndividual(), OpenMultisize(), OpenTemplate(), print(), and ui.
Referenced by TMainWindow().
showEvent()
void TMainWindow::showEvent (QShowEvent * event) protected virtual
Definition at line 704 of file tmainwindow.cpp.
References dockDiagramVisible, isInitialized, and ui.
ShowHeaderUnits()
void TMainWindow::ShowHeaderUnits (QTableWidget * table, int column, const QString & unit) private
Definition at line 2471 of file tmainwindow.cpp.
References SCASSERT.
Referenced by ShowUnits().
ShowMData
void TMainWindow::ShowMData () private slot
Definition at line 1731 of file tmainwindow.cpp.
References ShowNewMData().
Referenced by initializeTable().
ShowMDiagram()
void TMainWindow::ShowMDiagram (const QString & name) private
Definition at line 1840 of file tmainwindow.cpp.
References VTranslateMeasurements::guiText(), MeasurementDatabaseDialog::imageUrl(), VTranslateMeasurements::MNumber(), qApp, and ui.
Referenced by ShowNewMData().
ShowNewMData()
void TMainWindow::ShowNewMData (bool fresh) private
Definition at line 1737 of file tmainwindow.cpp.
References ClearCustomName(), ColumnName, data, VContainer::DataVariables(), EvalFormula(), VContainer::GetVariable(), MeasurementGUI(), MFields(), mType, Multisize, mUnit, pUnit, qApp, SaveMName(), ShowMDiagram(), ui, UnitConvertor(), and UnitsToStr().
Referenced by SaveMBaseValue(), SaveMHeightIncrease(), SaveMSizeIncrease(), and ShowMData().
ShowToolTip
void TMainWindow::ShowToolTip (const QString & toolTip) virtual slot
Definition at line 382 of file tmainwindow.cpp.
ShowUnits()
void TMainWindow::ShowUnits () private
Definition at line 2459 of file tmainwindow.cpp.
References ColumnBaseValue, ColumnCalcValue, ColumnFormula, ColumnInHeights, ColumnInSizes, mUnit, pUnit, ShowHeaderUnits(), ui, and UnitsToStr().
Referenced by initializeTable(), and RefreshTable().
ShowWindow
void TMainWindow::ShowWindow () const private slot
Definition at line 1224 of file tmainwindow.cpp.
References qApp.
Referenced by CreateWindowMenu().
ToolBarStyles
void TMainWindow::ToolBarStyles () private slot
Definition at line 621 of file tmainwindow.cpp.
References VAbstractMainWindow::ToolBarStyle(), and ui.
Referenced by Preferences(), and ReadSettings().
updateGroups
void TMainWindow::updateGroups () virtual slot
Definition at line 389 of file tmainwindow.cpp.
UpdatePadlock()
void TMainWindow::UpdatePadlock (bool ro) private
Definition at line 2998 of file tmainwindow.cpp.
References m_isReadOnly, and ui.
Referenced by FileNew(), FileSaveAs(), LoadFile(), and LoadFromExistingFile().
UpdatePatternUnit()
void TMainWindow::UpdatePatternUnit () private
Definition at line 3063 of file tmainwindow.cpp.
References RefreshTable(), search, and ui.
Referenced by PatternUnitChanged(), and SetPUnit().
UpdateRecentFileActions()
void TMainWindow::UpdateRecentFileActions () private
Definition at line 3208 of file tmainwindow.cpp.
References MaxRecentFiles, qApp, recentFileActs, separatorAct, and strippedName().
Referenced by SetCurrentFile().
UpdateWindowTitle()
void TMainWindow::UpdateWindowTitle () private
Definition at line 2859 of file tmainwindow.cpp.
References curFile, darkenPixmap(), m_isReadOnly, mType, Multisize, qApp, smisExt, smmsExt, and VER_INTERNALNAME_ME_STR.
Referenced by FileSaveAs(), SetCurrentFile(), and TMainWindow().
WriteSettings()
void TMainWindow::WriteSettings () private
Definition at line 3048 of file tmainwindow.cpp.
References APP_VERSION, qApp, VCommonSettings::SetGeometry(), VCommonSettings::SetToolbarsState(), and VCommonSettings::SetWindowState().
Referenced by closeEvent().
zoomToSelected
void TMainWindow::zoomToSelected () virtual slot
Definition at line 3425 of file tmainwindow.cpp.
Member Data Documentation
actionDockDiagram
QAction* TMainWindow::actionDockDiagram private
Definition at line 186 of file tmainwindow.h.
Referenced by InitWindow().
comboBoxUnits
QComboBox* TMainWindow::comboBoxUnits private
Definition at line 179 of file tmainwindow.h.
Referenced by changeEvent(), InitComboBoxUnits(), InitUnits(), and PatternUnitChanged().
curFile
QString TMainWindow::curFile private
Definition at line 176 of file tmainwindow.h.
Referenced by CurrentFile(), FileSave(), FileSaveAs(), handleExportToCSV(), MaybeSave(), SetCurrentFile(), and UpdateWindowTitle().
currentHeight
qreal TMainWindow::currentHeight private
Definition at line 175 of file tmainwindow.h.
Referenced by ChangedHeight(), FileNew(), LoadFile(), LoadFromExistingFile(), SetBaseMHeight(), and SetDefaultHeight().
currentSize
qreal TMainWindow::currentSize private
Definition at line 174 of file tmainwindow.h.
Referenced by ChangedSize(), FileNew(), LoadFile(), LoadFromExistingFile(), SetBaseMSize(), and SetDefaultSize().
data
VContainer* TMainWindow::data private
Definition at line 170 of file tmainwindow.h.
Referenced by EvalFormula(), FileNew(), Fx(), GetCustomName(), LoadFile(), LoadFromExistingFile(), RefreshData(), RefreshTable(), SaveMFullName(), SaveMName(), SaveMValue(), ShowNewMData(), and ~TMainWindow().
dockDiagramVisible
bool TMainWindow::dockDiagramVisible private
Definition at line 187 of file tmainwindow.h.
Referenced by InitWindow(), and showEvent().
gradationHeights
QComboBox* TMainWindow::gradationHeights private
Definition at line 177 of file tmainwindow.h.
Referenced by ChangedHeight(), InitWindow(), and SetDefaultHeight().
gradationSizes
QComboBox* TMainWindow::gradationSizes private
Definition at line 178 of file tmainwindow.h.
Referenced by ChangedSize(), InitWindow(), and SetDefaultSize().
hackedWidgets
QVector<QObject *> TMainWindow::hackedWidgets private
Definition at line 193 of file tmainwindow.h.
Referenced by HackWidget().
individualMeasurements
MeasurementDoc* TMainWindow::individualMeasurements private
Definition at line 169 of file tmainwindow.h.
Referenced by AddCustom(), AddKnown(), changeEvent(), CreateFromExisting(), FileNew(), FileSaveAs(), Fx(), ImportFromPattern(), InitWindow(), LoadFile(), LoadFromExistingFile(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), Open(), OpenTemplate(), RefreshData(), Remove(), RetranslateTable(), SaveBirthDate(), SaveEmail(), SaveFamilyName(), SaveGender(), SaveGivenName(), SaveMBaseValue(), SaveMDescription(), SaveMeasurements(), SaveMFullName(), SaveMHeightIncrease(), SaveMName(), SaveMSizeIncrease(), SaveMValue(), SaveNotes(), SavePMSystem(), SetBaseMHeight(), SetBaseMSize(), and ~TMainWindow().
isInitialized
bool TMainWindow::isInitialized private
Definition at line 188 of file tmainwindow.h.
Referenced by showEvent().
labelGradationHeights
QLabel* TMainWindow::labelGradationHeights private
Definition at line 183 of file tmainwindow.h.
Referenced by changeEvent(), and InitWindow().
labelGradationSizes
QLabel* TMainWindow::labelGradationSizes private
Definition at line 184 of file tmainwindow.h.
Referenced by changeEvent(), and InitWindow().
labelPatternUnit
QLabel* TMainWindow::labelPatternUnit private
Definition at line 185 of file tmainwindow.h.
Referenced by changeEvent(), and InitUnits().
lock
std::shared_ptr<VLockGuard<char> > TMainWindow::lock private
Definition at line 181 of file tmainwindow.h.
Referenced by FileSaveAs(), ImportFromPattern(), LoadFile(), LoadFromExistingFile(), and OpenTemplate().
m_isReadOnly
bool TMainWindow::m_isReadOnly private
Definition at line 189 of file tmainwindow.h.
Referenced by FileNew(), FileSave(), FileSaveAs(), LoadFile(), LoadFromExistingFile(), MaybeSave(), MeasurementsWasSaved(), UpdatePadlock(), and UpdateWindowTitle().
mType
MeasurementsType TMainWindow::mType private
Definition at line 173 of file tmainwindow.h.
Referenced by AddKnown(), changeEvent(), exportToCSVData(), FileNew(), FileSave(), FileSaveAs(), initializeTable(), InitWindow(), LoadFile(), LoadFromExistingFile(), MFields(), print(), printPages(), RefreshTable(), Remove(), SetBaseMHeight(), SetBaseMSize(), ShowNewMData(), and UpdateWindowTitle().
mUnit
Unit TMainWindow::mUnit private
Definition at line 171 of file tmainwindow.h.
Referenced by EvalFormula(), FileNew(), Fx(), InitWindow(), LoadFile(), LoadFromExistingFile(), printPages(), RefreshTable(), SaveMValue(), SetBaseMHeight(), SetBaseMSize(), SetDecimals(), ShowNewMData(), and ShowUnits().
pUnit
Unit TMainWindow::pUnit private
Definition at line 172 of file tmainwindow.h.
Referenced by EvalFormula(), FileNew(), InitUnits(), LoadFile(), LoadFromExistingFile(), PatternUnitChanged(), RefreshTable(), SetPUnit(), ShowNewMData(), and ShowUnits().
recentFileActs
QAction* TMainWindow::recentFileActs[MaxRecentFiles] private
Definition at line 191 of file tmainwindow.h.
Referenced by TMainWindow(), and UpdateRecentFileActions().
search
QSharedPointer<VTableSearch> TMainWindow::search private
Definition at line 182 of file tmainwindow.h.
Referenced by AddCustom(), AddKnown(), ChangedHeight(), ChangedSize(), Fx(), ImportFromPattern(), InitWindow(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), Remove(), RetranslateTable(), SaveMBaseValue(), SaveMHeightIncrease(), SaveMName(), SaveMSizeIncrease(), SaveMValue(), TMainWindow(), and UpdatePatternUnit().
separatorAct
QAction* TMainWindow::separatorAct private
Definition at line 192 of file tmainwindow.h.
Referenced by UpdateRecentFileActions().
ui
Ui::TMainWindow* TMainWindow::ui private
Definition at line 168 of file tmainwindow.h.
Referenced by AboutToShowWindowMenu(), AddCell(), AddCustom(), AddKnown(), ChangedHeight(), ChangedSize(), changeEvent(), Controls(), copyToClipboard(), exportToCSVData(), Fx(), ImportFromPattern(), initializeTable(), InitUnits(), InitWindow(), LoadFile(), LoadFromExistingFile(), MaybeSave(), MeasurementGUI(), MeasurementsWasSaved(), MFields(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), print(), printPages(), RefreshTable(), Remove(), RetranslateTable(), SaveEmail(), SaveFamilyName(), SaveGender(), SaveGivenName(), SaveMBaseValue(), SaveMDescription(), SaveMFullName(), SaveMHeightIncrease(), SaveMName(), SaveMSizeIncrease(), SaveMValue(), SaveNotes(), SavePMSystem(), SetBaseMHeight(), SetBaseMSize(), SetCurrentFile(), SetDecimals(), SetGradationList(), SetupMenu(), showEvent(), ShowMDiagram(), ShowNewMData(), ShowUnits(), TMainWindow(), ToolBarStyles(), UpdatePadlock(), UpdatePatternUnit(), and ~TMainWindow().
The documentation for this class was generated from the following files:
src/app/seamlyme/tmainwindow.h
src/app/seamlyme/tmainwindow.cpp