Seamly2D: TST_SeamlyMeCommandLine Class Reference
TST_SeamlyMeCommandLine Class Reference
#include <tst_seamlymecommandline.h>
Public Member Functions
TST_SeamlyMeCommandLine (QObject *parent=nullptr)
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Private Slots
void initTestCase ()
void OpenMeasurements_data () const
void OpenMeasurements ()
void cleanupTestCase ()
Additional Inherited Members
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Detailed Description
Definition at line 57 of file tst_seamlymecommandline.h.
Constructor & Destructor Documentation
TST_SeamlyMeCommandLine()
TST_SeamlyMeCommandLine::TST_SeamlyMeCommandLine (QObject * parent = nullptr) explicit
Definition at line 65 of file tst_seamlymecommandline.cpp.
Member Function Documentation
cleanupTestCase
void TST_SeamlyMeCommandLine::cleanupTestCase () private slot
Definition at line 154 of file tst_seamlymecommandline.cpp.
References tmpTestFolder.
initTestCase
void TST_SeamlyMeCommandLine::initTestCase () private slot
Definition at line 71 of file tst_seamlymecommandline.cpp.
References AbstractTest::CopyRecursively(), and tmpTestFolder.
OpenMeasurements
void TST_SeamlyMeCommandLine::OpenMeasurements () private slot
Definition at line 140 of file tst_seamlymecommandline.cpp.
References AbstractTest::Run(), AbstractTest::SeamlyMePath(), and tmpTestFolder.
OpenMeasurements_data
void TST_SeamlyMeCommandLine::OpenMeasurements_data () const private slot
Definition at line 87 of file tst_seamlymecommandline.cpp.
References V_EX_NOINPUT, and V_EX_OK.
The documentation for this class was generated from the following files:
src/test/CollectionTest/tst_seamlymecommandline.h
src/test/CollectionTest/tst_seamlymecommandline.cpp