Seamly2D: VInternalVariable Class Reference
VInternalVariable Class Reference
#include <vinternalvariable.h>
Public Member Functions
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool Filter (quint32 id)
virtual bool isNotUsed () const
Protected Member Functions
void SetValue (const qreal &value)
Private Attributes
QSharedDataPointer< VInternalVariableData > d
Detailed Description
Definition at line 64 of file vinternalvariable.h.
Constructor & Destructor Documentation
VInternalVariable() [1/2]
VInternalVariable::VInternalVariable ()
Definition at line 63 of file vinternalvariable.cpp.
VInternalVariable() [2/2]
VInternalVariable::VInternalVariable (const VInternalVariable & var)
Definition at line 68 of file vinternalvariable.cpp.
~VInternalVariable()
VInternalVariable::~VInternalVariable () virtual
Definition at line 84 of file vinternalvariable.cpp.
Member Function Documentation
Filter()
bool VInternalVariable::Filter (quint32 id) virtual
Reimplemented in VLengthLine, VLineAngle, and VCurveVariable.
Definition at line 88 of file vinternalvariable.cpp.
GetName()
QString VInternalVariable::GetName () const
Definition at line 119 of file vinternalvariable.cpp.
References d.
Referenced by VContainer::AddArc(), VContainer::AddCurve(), VContainer::AddCurveWithSegments(), VContainer::AddLine(), VContainer::AddSpline(), and VMeasurement::isCustom().
GetType()
VarType VInternalVariable::GetType () const
Definition at line 131 of file vinternalvariable.cpp.
References d.
GetValue() [1/2]
qreal * VInternalVariable::GetValue () virtual
Reimplemented in VMeasurement.
Definition at line 107 of file vinternalvariable.cpp.
References d.
GetValue() [2/2]
qreal VInternalVariable::GetValue () const virtual
Reimplemented in VMeasurement.
Definition at line 101 of file vinternalvariable.cpp.
References d.
Referenced by VMeasurement::CalcValue(), VMeasurement::GetValue(), and EditFormulaDialog::valueChanged().
isNotUsed()
bool VInternalVariable::isNotUsed () const virtual
Reimplemented in VMeasurement.
Definition at line 95 of file vinternalvariable.cpp.
operator=()
VInternalVariable & VInternalVariable::operator= (const VInternalVariable & var)
Definition at line 73 of file vinternalvariable.cpp.
References d.
Referenced by VCurveVariable::operator=(), VLengthLine::operator=(), VLineAngle::operator=(), and VVariable::operator=().
SetName()
void VInternalVariable::SetName (const QString & name)
Definition at line 125 of file vinternalvariable.cpp.
References d.
Referenced by VToolAlongLine::Create(), VArcRadius::VArcRadius(), VCurveAngle::VCurveAngle(), VCurveCLength::VCurveCLength(), VCurveLength::VCurveLength(), VLengthLine::VLengthLine(), VLineAngle::VLineAngle(), and VVariable::VVariable().
SetType()
void VInternalVariable::SetType (const VarType & type)
Definition at line 138 of file vinternalvariable.cpp.
References d.
Referenced by VArcRadius::VArcRadius(), VCurveAngle::VCurveAngle(), VCurveCLength::VCurveCLength(), VCurveLength::VCurveLength(), VCurveVariable::VCurveVariable(), VIncrement::VIncrement(), VLengthLine::VLengthLine(), VLineAngle::VLineAngle(), and VMeasurement::VMeasurement().
SetValue()
void VInternalVariable::SetValue (const qreal & value) protected
Definition at line 113 of file vinternalvariable.cpp.
References d.
Referenced by VMeasurement::GetValue(), VLineAngle::SetValue(), VLengthLine::SetValue(), VArcRadius::VArcRadius(), VCurveAngle::VCurveAngle(), VCurveCLength::VCurveCLength(), VCurveLength::VCurveLength(), VIncrement::VIncrement(), and VMeasurement::VMeasurement().
Swap()
void VInternalVariable::Swap (VInternalVariable & var)
Definition at line 59 of file vinternalvariable.cpp.
Referenced by VCurveVariable::Swap(), VLengthLine::Swap(), VLineAngle::Swap(), and VVariable::Swap().
Member Data Documentation
d
QSharedDataPointer<VInternalVariableData> VInternalVariable::d private
Definition at line 94 of file vinternalvariable.h.
Referenced by GetName(), GetType(), GetValue(), operator=(), SetName(), SetType(), and SetValue().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/vinternalvariable.h
src/libs/vpatterndb/variables/vinternalvariable.cpp