Seamly2D: RefHash2KeysTableOf< TVal, THasher > Class Template Reference
RefHash2KeysTableOf< TVal, THasher > Class Template Reference
#include <RefHash2KeysTableOf.hpp>
Public Member Functions
RefHash2KeysTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHash2KeysTableOf ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2) const
void removeKey (const void *const key1, const int key2)
void removeKey (const void *const key1)
void removeAll ()
void transferElement (const void *const key1, void *key2)
TVal * get (const void *const key1, const int key2)
const TVal * get (const void *const key1, const int key2) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
void put (void *key1, int key2, TVal *const valueToAdopt)
RefHash2KeysTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHash2KeysTableOf ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2) const
void removeKey (const void *const key1, const int key2)
void removeKey (const void *const key1)
void removeAll ()
void transferElement (const void *const key1, void *key2)
TVal * get (const void *const key1, const int key2)
const TVal * get (const void *const key1, const int key2) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
void put (void *key1, int key2, TVal *const valueToAdopt)
RefHash2KeysTableOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~RefHash2KeysTableOf ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2) const
void removeKey (const void *const key1, const int key2)
void removeKey (const void *const key1)
void removeAll ()
void transferElement (const void *const key1, void *key2)
TVal * get (const void *const key1, const int key2)
const TVal * get (const void *const key1, const int key2) const
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
void put (void *key1, int key2, TVal *const valueToAdopt)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
RefHash2KeysTableOf (const RefHash2KeysTableOf< TVal, THasher > &)
RefHash2KeysTableOf< TVal > & operator= (const RefHash2KeysTableOf< TVal, THasher > &)
RefHash2KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal)
const RefHash2KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
RefHash2KeysTableOf (const RefHash2KeysTableOf< TVal, THasher > &)
RefHash2KeysTableOf< TVal > & operator= (const RefHash2KeysTableOf< TVal, THasher > &)
RefHash2KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal)
const RefHash2KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
RefHash2KeysTableOf (const RefHash2KeysTableOf< TVal, THasher > &)
RefHash2KeysTableOf< TVal > & operator= (const RefHash2KeysTableOf< TVal, THasher > &)
RefHash2KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal)
const RefHash2KeysTableBucketElem< TVal > * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
Private Attributes
MemoryManager * fMemoryManager
bool fAdoptedElems
RefHash2KeysTableBucketElem< TVal > ** fBucketList
XMLSize_t fHashModulus
XMLSize_t fCount
THasher fHasher
Friends
class RefHash2KeysTableOfEnumerator< TVal, THasher >
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
template<class TVal, class THasher = StringHasher>
class RefHash2KeysTableOf< TVal, THasher >
Definition at line 69 of file RefHash2KeysTableOf.hpp.
Constructor & Destructor Documentation
RefHash2KeysTableOf() [1/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [2/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [3/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [4/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHash2KeysTableOf() [1/3]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::~RefHash2KeysTableOf ()
RefHash2KeysTableOf() [5/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const RefHash2KeysTableOf< TVal, THasher > &) private
RefHash2KeysTableOf() [6/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [7/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [8/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [9/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHash2KeysTableOf() [2/3]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::~RefHash2KeysTableOf ()
RefHash2KeysTableOf() [10/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const RefHash2KeysTableOf< TVal, THasher > &) private
RefHash2KeysTableOf() [11/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [12/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [13/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
RefHash2KeysTableOf() [14/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~RefHash2KeysTableOf() [3/3]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::~RefHash2KeysTableOf ()
RefHash2KeysTableOf() [15/15]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf< TVal, THasher >::RefHash2KeysTableOf (const RefHash2KeysTableOf< TVal, THasher > &) private
Member Function Documentation
containsKey() [1/3]
template<class TVal , class THasher = StringHasher> bool RefHash2KeysTableOf< TVal, THasher >::containsKey (const void *const key1, const int key2) const
containsKey() [2/3]
template<class TVal , class THasher = StringHasher> bool RefHash2KeysTableOf< TVal, THasher >::containsKey (const void *const key1, const int key2) const
containsKey() [3/3]
template<class TVal , class THasher = StringHasher> bool RefHash2KeysTableOf< TVal, THasher >::containsKey (const void *const key1, const int key2) const
findBucketElem() [1/6]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableBucketElem<TVal>* RefHash2KeysTableOf< TVal, THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) private
findBucketElem() [2/6]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableBucketElem<TVal>* RefHash2KeysTableOf< TVal, THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) private
findBucketElem() [3/6]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableBucketElem<TVal>* RefHash2KeysTableOf< TVal, THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) private
findBucketElem() [4/6]
template<class TVal , class THasher = StringHasher> const RefHash2KeysTableBucketElem<TVal>* RefHash2KeysTableOf< TVal, THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) const private
findBucketElem() [5/6]
template<class TVal , class THasher = StringHasher> const RefHash2KeysTableBucketElem<TVal>* RefHash2KeysTableOf< TVal, THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) const private
findBucketElem() [6/6]
template<class TVal , class THasher = StringHasher> const RefHash2KeysTableBucketElem<TVal>* RefHash2KeysTableOf< TVal, THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) const private
get() [1/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash2KeysTableOf< TVal, THasher >::get (const void *const key1, const int key2)
Referenced by ComplexTypeInfo::getAttDef(), and ValueStoreCache::getValueStoreFor().
get() [2/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash2KeysTableOf< TVal, THasher >::get (const void *const key1, const int key2)
get() [3/6]
template<class TVal , class THasher = StringHasher> TVal* RefHash2KeysTableOf< TVal, THasher >::get (const void *const key1, const int key2)
get() [4/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash2KeysTableOf< TVal, THasher >::get (const void *const key1, const int key2) const
get() [5/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash2KeysTableOf< TVal, THasher >::get (const void *const key1, const int key2) const
get() [6/6]
template<class TVal , class THasher = StringHasher> const TVal* RefHash2KeysTableOf< TVal, THasher >::get (const void *const key1, const int key2) const
getHashModulus() [1/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash2KeysTableOf< TVal, THasher >::getHashModulus () const
getHashModulus() [2/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash2KeysTableOf< TVal, THasher >::getHashModulus () const
getHashModulus() [3/3]
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash2KeysTableOf< TVal, THasher >::getHashModulus () const
getMemoryManager() [1/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHash2KeysTableOf< TVal, THasher >::getMemoryManager () const
getMemoryManager() [2/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHash2KeysTableOf< TVal, THasher >::getMemoryManager () const
getMemoryManager() [3/3]
template<class TVal , class THasher = StringHasher> MemoryManager* RefHash2KeysTableOf< TVal, THasher >::getMemoryManager () const
initialize() [1/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [2/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [3/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::initialize (const XMLSize_t modulus) private
isEmpty() [1/3]
template<class TVal , class THasher = StringHasher> bool RefHash2KeysTableOf< TVal, THasher >::isEmpty () const
Referenced by ComplexTypeInfo::hasAttDefs().
isEmpty() [2/3]
template<class TVal , class THasher = StringHasher> bool RefHash2KeysTableOf< TVal, THasher >::isEmpty () const
isEmpty() [3/3]
template<class TVal , class THasher = StringHasher> bool RefHash2KeysTableOf< TVal, THasher >::isEmpty () const
operator=() [1/3]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf<TVal>& RefHash2KeysTableOf< TVal, THasher >::operator= (const RefHash2KeysTableOf< TVal, THasher > &) private
operator=() [2/3]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf<TVal>& RefHash2KeysTableOf< TVal, THasher >::operator= (const RefHash2KeysTableOf< TVal, THasher > &) private
operator=() [3/3]
template<class TVal , class THasher = StringHasher> RefHash2KeysTableOf<TVal>& RefHash2KeysTableOf< TVal, THasher >::operator= (const RefHash2KeysTableOf< TVal, THasher > &) private
put() [1/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::put (void * key1, int key2, TVal *const valueToAdopt)
put() [2/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::put (void * key1, int key2, TVal *const valueToAdopt)
put() [3/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::put (void * key1, int key2, TVal *const valueToAdopt)
rehash() [1/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::rehash () private
rehash() [2/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::rehash () private
rehash() [3/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::rehash () private
removeAll() [1/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeAll ()
Referenced by XMLScanner::setAttrDupChkRegistry().
removeAll() [2/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeAll ()
removeAll() [3/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeAll ()
removeKey() [1/6]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeKey (const void *const key1)
removeKey() [2/6]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeKey (const void *const key1)
removeKey() [3/6]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeKey (const void *const key1)
removeKey() [4/6]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeKey (const void *const key1, const int key2)
removeKey() [5/6]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeKey (const void *const key1, const int key2)
removeKey() [6/6]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::removeKey (const void *const key1, const int key2)
transferElement() [1/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::transferElement (const void *const key1, void * key2)
transferElement() [2/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::transferElement (const void *const key1, void * key2)
transferElement() [3/3]
template<class TVal , class THasher = StringHasher> void RefHash2KeysTableOf< TVal, THasher >::transferElement (const void *const key1, void * key2)
Friends And Related Function Documentation
RefHash2KeysTableOfEnumerator< TVal, THasher >
template<class TVal , class THasher = StringHasher> friend class RefHash2KeysTableOfEnumerator< TVal, THasher > friend
Definition at line 121 of file RefHash2KeysTableOf.hpp.
Member Data Documentation
fAdoptedElems
template<class TVal , class THasher = StringHasher> bool RefHash2KeysTableOf< TVal, THasher >::fAdoptedElems private
Definition at line 169 of file RefHash2KeysTableOf.hpp.
fBucketList
template<class TVal , class THasher = StringHasher> RefHash2KeysTableBucketElem< TVal > ** RefHash2KeysTableOf< TVal, THasher >::fBucketList private
Definition at line 170 of file RefHash2KeysTableOf.hpp.
Referenced by RefHash2KeysTableOfEnumerator< SchemaAttDef >::findNext().
fCount
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash2KeysTableOf< TVal, THasher >::fCount private
Definition at line 172 of file RefHash2KeysTableOf.hpp.
fHasher
template<class TVal , class THasher = StringHasher> THasher RefHash2KeysTableOf< TVal, THasher >::fHasher private
Definition at line 173 of file RefHash2KeysTableOf.hpp.
Referenced by RefHash2KeysTableOfEnumerator< SchemaAttDef >::Reset(), and RefHash2KeysTableOfEnumerator< SchemaAttDef >::setPrimaryKey().
fHashModulus
template<class TVal , class THasher = StringHasher> XMLSize_t RefHash2KeysTableOf< TVal, THasher >::fHashModulus private
Definition at line 171 of file RefHash2KeysTableOf.hpp.
Referenced by RefHash2KeysTableOfEnumerator< SchemaAttDef >::Reset().
fMemoryManager
template<class TVal , class THasher = StringHasher> MemoryManager * RefHash2KeysTableOf< TVal, THasher >::fMemoryManager private
Definition at line 168 of file RefHash2KeysTableOf.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/RefHash2KeysTableOf.hpp