Seamly2D: SchemaAttDef Class Reference
SchemaAttDef Class Reference
#include <SchemaAttDef.hpp>
Public Member Functions
SchemaAttDef (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLAttDef::AttTypes type=CData, const XMLAttDef::DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLCh *const attValue, const XMLAttDef::AttTypes type, const XMLAttDef::DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const SchemaAttDef *other)
virtual ~SchemaAttDef ()
virtual const XMLCh * getFullName () const
virtual void reset ()
XMLSize_t getElemId () const
QName * getAttName () const
DatatypeValidator * getDatatypeValidator () const
ValueVectorOf< unsigned int > * getNamespaceList () const
const SchemaAttDef * getBaseAttDecl () const
SchemaAttDef * getBaseAttDecl ()
PSVIDefs::PSVIScope getPSVIScope () const
void setElemId (const XMLSize_t newId)
void setAttName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId=-1)
void setDatatypeValidator (DatatypeValidator *newDatatypeValidator)
void setBaseAttDecl (SchemaAttDef *const attDef)
void setPSVIScope (const PSVIDefs::PSVIScope toSet)
void setNamespaceList (const ValueVectorOf< unsigned int > *const toSet)
void resetNamespaceList ()
void setEnclosingCT (ComplexTypeInfo *complexTypeInfo)
SchemaAttDef (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLAttDef::AttTypes type=CData, const XMLAttDef::DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLCh *const attValue, const XMLAttDef::AttTypes type, const XMLAttDef::DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const SchemaAttDef *other)
virtual ~SchemaAttDef ()
virtual const XMLCh * getFullName () const
virtual void reset ()
XMLSize_t getElemId () const
QName * getAttName () const
DatatypeValidator * getDatatypeValidator () const
ValueVectorOf< unsigned int > * getNamespaceList () const
const SchemaAttDef * getBaseAttDecl () const
SchemaAttDef * getBaseAttDecl ()
PSVIDefs::PSVIScope getPSVIScope () const
void setElemId (const XMLSize_t newId)
void setAttName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId=-1)
void setDatatypeValidator (DatatypeValidator *newDatatypeValidator)
void setBaseAttDecl (SchemaAttDef *const attDef)
void setPSVIScope (const PSVIDefs::PSVIScope toSet)
void setNamespaceList (const ValueVectorOf< unsigned int > *const toSet)
void resetNamespaceList ()
void setEnclosingCT (ComplexTypeInfo *complexTypeInfo)
SchemaAttDef (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLAttDef::AttTypes type=CData, const XMLAttDef::DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLCh *const attValue, const XMLAttDef::AttTypes type, const XMLAttDef::DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDef (const SchemaAttDef *other)
virtual ~SchemaAttDef ()
virtual const XMLCh * getFullName () const
virtual void reset ()
XMLSize_t getElemId () const
QName * getAttName () const
DatatypeValidator * getDatatypeValidator () const
ValueVectorOf< unsigned int > * getNamespaceList () const
const SchemaAttDef * getBaseAttDecl () const
SchemaAttDef * getBaseAttDecl ()
PSVIDefs::PSVIScope getPSVIScope () const
void setElemId (const XMLSize_t newId)
void setAttName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId=-1)
void setDatatypeValidator (DatatypeValidator *newDatatypeValidator)
void setBaseAttDecl (SchemaAttDef *const attDef)
void setPSVIScope (const PSVIDefs::PSVIScope toSet)
void setNamespaceList (const ValueVectorOf< unsigned int > *const toSet)
void resetNamespaceList ()
void setEnclosingCT (ComplexTypeInfo *complexTypeInfo)
Public Member Functions inherited from XMLAttDef
virtual ~XMLAttDef ()
virtual ~XMLAttDef ()
virtual ~XMLAttDef ()
DefAttTypes getDefaultType () const
const XMLCh * getEnumeration () const
XMLSize_t getId () const
AttTypes getType () const
const XMLCh * getValue () const
CreateReasons getCreateReason () const
bool isExternal () const
MemoryManager * getMemoryManager () const
DefAttTypes getDefaultType () const
const XMLCh * getEnumeration () const
XMLSize_t getId () const
AttTypes getType () const
const XMLCh * getValue () const
CreateReasons getCreateReason () const
bool isExternal () const
MemoryManager * getMemoryManager () const
DefAttTypes getDefaultType () const
const XMLCh * getEnumeration () const
XMLSize_t getId () const
AttTypes getType () const
const XMLCh * getValue () const
CreateReasons getCreateReason () const
bool isExternal () const
MemoryManager * getMemoryManager () const
void setDefaultType (const XMLAttDef::DefAttTypes newValue)
void setId (const XMLSize_t newId)
void setType (const XMLAttDef::AttTypes newValue)
void setValue (const XMLCh *const newValue)
void setEnumeration (const XMLCh *const newValue)
void setCreateReason (const CreateReasons newReason)
void setExternalAttDeclaration (const bool aValue)
void setDefaultType (const XMLAttDef::DefAttTypes newValue)
void setId (const XMLSize_t newId)
void setType (const XMLAttDef::AttTypes newValue)
void setValue (const XMLCh *const newValue)
void setEnumeration (const XMLCh *const newValue)
void setCreateReason (const CreateReasons newReason)
void setExternalAttDeclaration (const bool aValue)
void setDefaultType (const XMLAttDef::DefAttTypes newValue)
void setId (const XMLSize_t newId)
void setType (const XMLAttDef::AttTypes newValue)
void setValue (const XMLCh *const newValue)
void setEnumeration (const XMLCh *const newValue)
void setCreateReason (const CreateReasons newReason)
void setExternalAttDeclaration (const bool aValue)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
SchemaAttDef (const SchemaAttDef &)
SchemaAttDef & operator= (const SchemaAttDef &)
SchemaAttDef (const SchemaAttDef &)
SchemaAttDef & operator= (const SchemaAttDef &)
SchemaAttDef (const SchemaAttDef &)
SchemaAttDef & operator= (const SchemaAttDef &)
Private Attributes
XMLSize_t fElemId
PSVIDefs::PSVIScope fPSVIScope
QName * fAttName
DatatypeValidator * fDatatypeValidator
ValueVectorOf< unsigned int > * fNamespaceList
SchemaAttDef * fBaseAttDecl
Additional Inherited Members
Public Types inherited from XMLAttDef
enum AttTypes {
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1 , CData = 0 , ID = 1 ,
IDRef = 2 , IDRefs = 3 , Entity = 4 , Entities = 5 ,
NmToken = 6 , NmTokens = 7 , Notation = 8 , Enumeration = 9 ,
Simple = 10 , Any_Any = 11 , Any_Other = 12 , Any_List = 13 ,
AttTypes_Count , AttTypes_Min = 0 , AttTypes_Max = 13 , AttTypes_Unknown = -1 ,
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1
}
enum DefAttTypes {
Default = 0 , Fixed = 1 , Required = 2 , Required_And_Fixed = 3 ,
Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 , ProcessContents_Strict = 7 ,
Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 , DefAttTypes_Max = 8 ,
DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 , Required = 2 ,
Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 ,
ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 ,
DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 ,
Required = 2 , Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 ,
ProcessContents_Lax = 6 , ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count ,
DefAttTypes_Min = 0 , DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1
}
enum CreateReasons {
NoReason , JustFaultIn , NoReason , JustFaultIn ,
NoReason , JustFaultIn
}
enum AttTypes {
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1 , CData = 0 , ID = 1 ,
IDRef = 2 , IDRefs = 3 , Entity = 4 , Entities = 5 ,
NmToken = 6 , NmTokens = 7 , Notation = 8 , Enumeration = 9 ,
Simple = 10 , Any_Any = 11 , Any_Other = 12 , Any_List = 13 ,
AttTypes_Count , AttTypes_Min = 0 , AttTypes_Max = 13 , AttTypes_Unknown = -1 ,
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1
}
enum DefAttTypes {
Default = 0 , Fixed = 1 , Required = 2 , Required_And_Fixed = 3 ,
Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 , ProcessContents_Strict = 7 ,
Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 , DefAttTypes_Max = 8 ,
DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 , Required = 2 ,
Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 ,
ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 ,
DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 ,
Required = 2 , Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 ,
ProcessContents_Lax = 6 , ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count ,
DefAttTypes_Min = 0 , DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1
}
enum CreateReasons {
NoReason , JustFaultIn , NoReason , JustFaultIn ,
NoReason , JustFaultIn
}
enum AttTypes {
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1 , CData = 0 , ID = 1 ,
IDRef = 2 , IDRefs = 3 , Entity = 4 , Entities = 5 ,
NmToken = 6 , NmTokens = 7 , Notation = 8 , Enumeration = 9 ,
Simple = 10 , Any_Any = 11 , Any_Other = 12 , Any_List = 13 ,
AttTypes_Count , AttTypes_Min = 0 , AttTypes_Max = 13 , AttTypes_Unknown = -1 ,
CData = 0 , ID = 1 , IDRef = 2 , IDRefs = 3 ,
Entity = 4 , Entities = 5 , NmToken = 6 , NmTokens = 7 ,
Notation = 8 , Enumeration = 9 , Simple = 10 , Any_Any = 11 ,
Any_Other = 12 , Any_List = 13 , AttTypes_Count , AttTypes_Min = 0 ,
AttTypes_Max = 13 , AttTypes_Unknown = -1
}
enum DefAttTypes {
Default = 0 , Fixed = 1 , Required = 2 , Required_And_Fixed = 3 ,
Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 , ProcessContents_Strict = 7 ,
Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 , DefAttTypes_Max = 8 ,
DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 , Required = 2 ,
Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 , ProcessContents_Lax = 6 ,
ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count , DefAttTypes_Min = 0 ,
DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1 , Default = 0 , Fixed = 1 ,
Required = 2 , Required_And_Fixed = 3 , Implied = 4 , ProcessContents_Skip = 5 ,
ProcessContents_Lax = 6 , ProcessContents_Strict = 7 , Prohibited = 8 , DefAttTypes_Count ,
DefAttTypes_Min = 0 , DefAttTypes_Max = 8 , DefAttTypes_Unknown = -1
}
enum CreateReasons {
NoReason , JustFaultIn , NoReason , JustFaultIn ,
NoReason , JustFaultIn
}
Static Public Member Functions inherited from XMLAttDef
static const XMLCh * getAttTypeString (const AttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getAttTypeString (const AttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getAttTypeString (const AttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static const XMLCh * getDefAttTypeString (const DefAttTypes attrType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Static Public Attributes inherited from XMLAttDef
static const unsigned int fgInvalidAttrId
Protected Member Functions inherited from XMLAttDef
XMLAttDef (const AttTypes type=CData, const DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const AttTypes type=CData, const DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const AttTypes type=CData, const DefAttTypes defType=Implied, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDef (const XMLCh *const attValue, const AttTypes type, const DefAttTypes defType, const XMLCh *const enumValues=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 42 of file SchemaAttDef.hpp.
Constructor & Destructor Documentation
SchemaAttDef() [1/15]
SchemaAttDef::SchemaAttDef (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [2/15]
SchemaAttDef::SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLAttDef::AttTypes type = CData, const XMLAttDef::DefAttTypes defType = Implied, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [3/15]
SchemaAttDef::SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLCh *const attValue, const XMLAttDef::AttTypes type, const XMLAttDef::DefAttTypes defType, const XMLCh *const enumValues = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [4/15]
SchemaAttDef::SchemaAttDef (const SchemaAttDef * other)
~SchemaAttDef() [1/3]
virtual SchemaAttDef::~SchemaAttDef () virtual
SchemaAttDef() [5/15]
SchemaAttDef::SchemaAttDef (const SchemaAttDef &) private
SchemaAttDef() [6/15]
SchemaAttDef::SchemaAttDef (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [7/15]
SchemaAttDef::SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLAttDef::AttTypes type = CData, const XMLAttDef::DefAttTypes defType = Implied, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [8/15]
SchemaAttDef::SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLCh *const attValue, const XMLAttDef::AttTypes type, const XMLAttDef::DefAttTypes defType, const XMLCh *const enumValues = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [9/15]
SchemaAttDef::SchemaAttDef (const SchemaAttDef * other)
~SchemaAttDef() [2/3]
virtual SchemaAttDef::~SchemaAttDef () virtual
SchemaAttDef() [10/15]
SchemaAttDef::SchemaAttDef (const SchemaAttDef &) private
SchemaAttDef() [11/15]
SchemaAttDef::SchemaAttDef (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [12/15]
SchemaAttDef::SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLAttDef::AttTypes type = CData, const XMLAttDef::DefAttTypes defType = Implied, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [13/15]
SchemaAttDef::SchemaAttDef (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId, const XMLCh *const attValue, const XMLAttDef::AttTypes type, const XMLAttDef::DefAttTypes defType, const XMLCh *const enumValues = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDef() [14/15]
SchemaAttDef::SchemaAttDef (const SchemaAttDef * other)
~SchemaAttDef() [3/3]
virtual SchemaAttDef::~SchemaAttDef () virtual
SchemaAttDef() [15/15]
SchemaAttDef::SchemaAttDef (const SchemaAttDef &) private
Member Function Documentation
getAttName() [1/3]
QName * SchemaAttDef::getAttName () const inline
Definition at line 167 of file SchemaAttDef.hpp.
References fAttName.
Referenced by ComplexTypeInfo::contains(), and TraverseSchema::copyWildCardData().
getAttName() [2/3]
QName* SchemaAttDef::getAttName () const
getAttName() [3/3]
QName* SchemaAttDef::getAttName () const
getBaseAttDecl() [1/6]
SchemaAttDef * SchemaAttDef::getBaseAttDecl () inline
Definition at line 182 of file SchemaAttDef.hpp.
References fBaseAttDecl.
getBaseAttDecl() [2/6]
SchemaAttDef* SchemaAttDef::getBaseAttDecl ()
getBaseAttDecl() [3/6]
SchemaAttDef* SchemaAttDef::getBaseAttDecl ()
getBaseAttDecl() [4/6]
const SchemaAttDef * SchemaAttDef::getBaseAttDecl () const inline
Definition at line 187 of file SchemaAttDef.hpp.
References fBaseAttDecl.
Referenced by XercesAttGroupInfo::addAnyAttDef(), and XercesAttGroupInfo::addAttDef().
getBaseAttDecl() [5/6]
const SchemaAttDef* SchemaAttDef::getBaseAttDecl () const
getBaseAttDecl() [6/6]
const SchemaAttDef* SchemaAttDef::getBaseAttDecl () const
getDatatypeValidator() [1/3]
DatatypeValidator * SchemaAttDef::getDatatypeValidator () const inline
Definition at line 172 of file SchemaAttDef.hpp.
References fDatatypeValidator.
getDatatypeValidator() [2/3]
DatatypeValidator* SchemaAttDef::getDatatypeValidator () const
getDatatypeValidator() [3/3]
DatatypeValidator* SchemaAttDef::getDatatypeValidator () const
getElemId() [1/3]
XMLSize_t SchemaAttDef::getElemId () const inline
Definition at line 161 of file SchemaAttDef.hpp.
References fElemId.
getElemId() [2/3]
XMLSize_t SchemaAttDef::getElemId () const
getElemId() [3/3]
XMLSize_t SchemaAttDef::getElemId () const
getFullName() [1/3]
virtual const XMLCh* SchemaAttDef::getFullName () const virtual
Get the full name of this attribute type
The derived class should return a const pointer to the full name of this attribute. This will vary depending on the type of validator in use.
Returns
A const pointer to the full name of this attribute type.
Implements XMLAttDef.
getFullName() [2/3]
virtual const XMLCh* SchemaAttDef::getFullName () const virtual
Get the full name of this attribute type
The derived class should return a const pointer to the full name of this attribute. This will vary depending on the type of validator in use.
Returns
A const pointer to the full name of this attribute type.
Implements XMLAttDef.
getFullName() [3/3]
virtual const XMLCh* SchemaAttDef::getFullName () const virtual
Get the full name of this attribute type
The derived class should return a const pointer to the full name of this attribute. This will vary depending on the type of validator in use.
Returns
A const pointer to the full name of this attribute type.
Implements XMLAttDef.
getNamespaceList() [1/3]
ValueVectorOf< unsigned int > * SchemaAttDef::getNamespaceList () const inline
Definition at line 178 of file SchemaAttDef.hpp.
References fNamespaceList.
getNamespaceList() [2/3]
ValueVectorOf<unsigned int>* SchemaAttDef::getNamespaceList () const
getNamespaceList() [3/3]
ValueVectorOf<unsigned int>* SchemaAttDef::getNamespaceList () const
getPSVIScope() [1/3]
PSVIDefs::PSVIScope SchemaAttDef::getPSVIScope () const inline
Definition at line 192 of file SchemaAttDef.hpp.
References fPSVIScope.
getPSVIScope() [2/3]
PSVIDefs::PSVIScope SchemaAttDef::getPSVIScope () const
getPSVIScope() [3/3]
PSVIDefs::PSVIScope SchemaAttDef::getPSVIScope () const
operator=() [1/3]
SchemaAttDef& SchemaAttDef::operator= (const SchemaAttDef &) private
operator=() [2/3]
SchemaAttDef& SchemaAttDef::operator= (const SchemaAttDef &) private
operator=() [3/3]
SchemaAttDef& SchemaAttDef::operator= (const SchemaAttDef &) private
reset() [1/3]
void SchemaAttDef::reset () inline virtual
The derived class should implement any cleaning up required between each use of an instance of this class for validation
Implements XMLAttDef.
Definition at line 233 of file SchemaAttDef.hpp.
reset() [2/3]
virtual void SchemaAttDef::reset () virtual
The derived class should implement any cleaning up required between each use of an instance of this class for validation
Implements XMLAttDef.
reset() [3/3]
virtual void SchemaAttDef::reset () virtual
The derived class should implement any cleaning up required between each use of an instance of this class for validation
Implements XMLAttDef.
resetNamespaceList() [1/3]
void SchemaAttDef::resetNamespaceList () inline
Definition at line 210 of file SchemaAttDef.hpp.
References fNamespaceList, ValueVectorOf< TElem >::removeAllElements(), and ValueVectorOf< TElem >::size().
Referenced by setNamespaceList().
resetNamespaceList() [2/3]
void SchemaAttDef::resetNamespaceList ()
resetNamespaceList() [3/3]
void SchemaAttDef::resetNamespaceList ()
setAttName() [1/3]
void SchemaAttDef::setAttName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId = -1)
setAttName() [2/3]
void SchemaAttDef::setAttName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId = -1)
setAttName() [3/3]
void SchemaAttDef::setAttName (const XMLCh *const prefix, const XMLCh *const localPart, const int uriId = -1)
setBaseAttDecl() [1/3]
void SchemaAttDef::setBaseAttDecl (SchemaAttDef *const attDef) inline
Definition at line 240 of file SchemaAttDef.hpp.
References fBaseAttDecl.
Referenced by XercesAttGroupInfo::addAnyAttDef(), and XercesAttGroupInfo::addAttDef().
setBaseAttDecl() [2/3]
void SchemaAttDef::setBaseAttDecl (SchemaAttDef *const attDef)
setBaseAttDecl() [3/3]
void SchemaAttDef::setBaseAttDecl (SchemaAttDef *const attDef)
setDatatypeValidator() [1/3]
void SchemaAttDef::setDatatypeValidator (DatatypeValidator * newDatatypeValidator) inline
Definition at line 205 of file SchemaAttDef.hpp.
References fDatatypeValidator.
setDatatypeValidator() [2/3]
void SchemaAttDef::setDatatypeValidator (DatatypeValidator * newDatatypeValidator)
setDatatypeValidator() [3/3]
void SchemaAttDef::setDatatypeValidator (DatatypeValidator * newDatatypeValidator)
setElemId() [1/3]
void SchemaAttDef::setElemId (const XMLSize_t newId) inline
Definition at line 200 of file SchemaAttDef.hpp.
References fElemId.
setElemId() [2/3]
void SchemaAttDef::setElemId (const XMLSize_t newId)
setElemId() [3/3]
void SchemaAttDef::setElemId (const XMLSize_t newId)
setEnclosingCT() [1/3]
void SchemaAttDef::setEnclosingCT (ComplexTypeInfo * complexTypeInfo) inline
Definition at line 236 of file SchemaAttDef.hpp.
setEnclosingCT() [2/3]
void SchemaAttDef::setEnclosingCT (ComplexTypeInfo * complexTypeInfo)
setEnclosingCT() [3/3]
void SchemaAttDef::setEnclosingCT (ComplexTypeInfo * complexTypeInfo)
setNamespaceList() [1/3]
void SchemaAttDef::setNamespaceList (const ValueVectorOf< unsigned int > *const toSet) inline
Definition at line 217 of file SchemaAttDef.hpp.
References fNamespaceList, XMLAttDef::getMemoryManager(), resetNamespaceList(), and ValueVectorOf< TElem >::size().
setNamespaceList() [2/3]
void SchemaAttDef::setNamespaceList (const ValueVectorOf< unsigned int > *const toSet)
setNamespaceList() [3/3]
void SchemaAttDef::setNamespaceList (const ValueVectorOf< unsigned int > *const toSet)
setPSVIScope() [1/3]
void SchemaAttDef::setPSVIScope (const PSVIDefs::PSVIScope toSet) inline
Definition at line 245 of file SchemaAttDef.hpp.
References fPSVIScope.
setPSVIScope() [2/3]
void SchemaAttDef::setPSVIScope (const PSVIDefs::PSVIScope toSet)
setPSVIScope() [3/3]
void SchemaAttDef::setPSVIScope (const PSVIDefs::PSVIScope toSet)
Member Data Documentation
fAttName
QName * SchemaAttDef::fAttName private
Definition at line 151 of file SchemaAttDef.hpp.
Referenced by getAttName().
fBaseAttDecl
SchemaAttDef * SchemaAttDef::fBaseAttDecl private
Definition at line 154 of file SchemaAttDef.hpp.
Referenced by getBaseAttDecl(), and setBaseAttDecl().
fDatatypeValidator
DatatypeValidator * SchemaAttDef::fDatatypeValidator private
Definition at line 152 of file SchemaAttDef.hpp.
Referenced by getDatatypeValidator(), and setDatatypeValidator().
fElemId
XMLSize_t SchemaAttDef::fElemId private
Definition at line 147 of file SchemaAttDef.hpp.
Referenced by getElemId(), and setElemId().
fNamespaceList
ValueVectorOf< unsigned int > * SchemaAttDef::fNamespaceList private
Definition at line 153 of file SchemaAttDef.hpp.
Referenced by getNamespaceList(), resetNamespaceList(), and setNamespaceList().
fPSVIScope
PSVIDefs::PSVIScope SchemaAttDef::fPSVIScope private
Definition at line 149 of file SchemaAttDef.hpp.
Referenced by getPSVIScope(), and setPSVIScope().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/SchemaAttDef.hpp