Seamly2D: CMStateSetEnumerator Class Reference
CMStateSetEnumerator Class Reference
#include <CMStateSet.hpp>
Public Member Functions
CMStateSetEnumerator (const CMStateSet *toEnum, XMLSize_t start=0)
bool hasMoreElements ()
unsigned int nextElement ()
CMStateSetEnumerator (const CMStateSet *toEnum, XMLSize_t start=0)
bool hasMoreElements ()
unsigned int nextElement ()
CMStateSetEnumerator (const CMStateSet *toEnum, XMLSize_t start=0)
bool hasMoreElements ()
unsigned int nextElement ()
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
void findNext ()
void findNext ()
void findNext ()
Private Attributes
const CMStateSet * fToEnum
XMLSize_t fIndexCount
XMLInt32 fLastValue
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 542 of file CMStateSet.hpp.
Constructor & Destructor Documentation
CMStateSetEnumerator() [1/3]
CMStateSetEnumerator::CMStateSetEnumerator (const CMStateSet * toEnum, XMLSize_t start = 0) inline
Definition at line 545 of file CMStateSet.hpp.
References fIndexCount, findNext(), fLastValue, and hasMoreElements().
CMStateSetEnumerator() [2/3]
CMStateSetEnumerator::CMStateSetEnumerator (const CMStateSet * toEnum, XMLSize_t start = 0) inline
Definition at line 545 of file CMStateSet.hpp.
References fIndexCount, findNext(), fLastValue, and hasMoreElements().
CMStateSetEnumerator() [3/3]
CMStateSetEnumerator::CMStateSetEnumerator (const CMStateSet * toEnum, XMLSize_t start = 0) inline
Definition at line 545 of file CMStateSet.hpp.
References fIndexCount, findNext(), fLastValue, and hasMoreElements().
Member Function Documentation
findNext() [1/3]
void CMStateSetEnumerator::findNext () inline private
Definition at line 593 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, CMStateSet::fBits, CMStateSet::fDynamicBuffer, fIndexCount, fLastValue, and fToEnum.
Referenced by CMStateSetEnumerator(), and nextElement().
findNext() [2/3]
void CMStateSetEnumerator::findNext () inline private
Definition at line 593 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, CMStateSet::fBits, CMStateSet::fDynamicBuffer, fIndexCount, fLastValue, and fToEnum.
findNext() [3/3]
void CMStateSetEnumerator::findNext () inline private
Definition at line 593 of file CMStateSet.hpp.
References CMSTATE_BITFIELD_CHUNK, CMSTATE_BITFIELD_INT32_SIZE, CMSTATE_CACHED_INT32_SIZE, CMDynamicBuffer::fArraySize, CMDynamicBuffer::fBitArray, CMStateSet::fBits, CMStateSet::fDynamicBuffer, fIndexCount, fLastValue, and fToEnum.
hasMoreElements() [1/3]
bool CMStateSetEnumerator::hasMoreElements () inline
Definition at line 570 of file CMStateSet.hpp.
References fLastValue.
Referenced by CMStateSetEnumerator().
hasMoreElements() [2/3]
bool CMStateSetEnumerator::hasMoreElements () inline
Definition at line 570 of file CMStateSet.hpp.
References fLastValue.
hasMoreElements() [3/3]
bool CMStateSetEnumerator::hasMoreElements () inline
Definition at line 570 of file CMStateSet.hpp.
References fLastValue.
nextElement() [1/3]
unsigned int CMStateSetEnumerator::nextElement () inline
Definition at line 575 of file CMStateSet.hpp.
References fIndexCount, findNext(), and fLastValue.
nextElement() [2/3]
unsigned int CMStateSetEnumerator::nextElement () inline
Definition at line 575 of file CMStateSet.hpp.
References fIndexCount, findNext(), and fLastValue.
nextElement() [3/3]
unsigned int CMStateSetEnumerator::nextElement () inline
Definition at line 575 of file CMStateSet.hpp.
References fIndexCount, findNext(), and fLastValue.
Member Data Documentation
fIndexCount
XMLSize_t CMStateSetEnumerator::fIndexCount private
Definition at line 630 of file CMStateSet.hpp.
Referenced by CMStateSetEnumerator(), findNext(), and nextElement().
fLastValue
XMLInt32 CMStateSetEnumerator::fLastValue private
Definition at line 631 of file CMStateSet.hpp.
Referenced by CMStateSetEnumerator(), findNext(), hasMoreElements(), and nextElement().
fToEnum
const CMStateSet * CMStateSetEnumerator::fToEnum private
Definition at line 629 of file CMStateSet.hpp.
Referenced by findNext().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/common/CMStateSet.hpp