Seamly2D: DatatypeValidator Class Reference
DatatypeValidator Class Reference abstract
#include <DatatypeValidator.hpp>
Public Types
enum {
FACET_LENGTH = 1 , FACET_MINLENGTH = 1<<1 , FACET_MAXLENGTH = 1<<2 , FACET_PATTERN = 1<<3 ,
FACET_ENUMERATION = 1<<4 , FACET_MAXINCLUSIVE = 1<<5 , FACET_MAXEXCLUSIVE = 1<<6 , FACET_MININCLUSIVE = 1<<7 ,
FACET_MINEXCLUSIVE = 1<<8 , FACET_TOTALDIGITS = 1<<9 , FACET_FRACTIONDIGITS = 1<<10 , FACET_ENCODING = 1<<11 ,
FACET_DURATION = 1<<12 , FACET_PERIOD = 1<<13 , FACET_WHITESPACE = 1<<14
}
enum { PRESERVE = 0 , REPLACE = 1 , COLLAPSE = 2 }
enum ValidatorType {
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown ,
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown ,
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown
}
enum {
FACET_LENGTH = 1 , FACET_MINLENGTH = 1<<1 , FACET_MAXLENGTH = 1<<2 , FACET_PATTERN = 1<<3 ,
FACET_ENUMERATION = 1<<4 , FACET_MAXINCLUSIVE = 1<<5 , FACET_MAXEXCLUSIVE = 1<<6 , FACET_MININCLUSIVE = 1<<7 ,
FACET_MINEXCLUSIVE = 1<<8 , FACET_TOTALDIGITS = 1<<9 , FACET_FRACTIONDIGITS = 1<<10 , FACET_ENCODING = 1<<11 ,
FACET_DURATION = 1<<12 , FACET_PERIOD = 1<<13 , FACET_WHITESPACE = 1<<14
}
enum { PRESERVE = 0 , REPLACE = 1 , COLLAPSE = 2 }
enum ValidatorType {
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown ,
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown ,
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown
}
enum {
FACET_LENGTH = 1 , FACET_MINLENGTH = 1<<1 , FACET_MAXLENGTH = 1<<2 , FACET_PATTERN = 1<<3 ,
FACET_ENUMERATION = 1<<4 , FACET_MAXINCLUSIVE = 1<<5 , FACET_MAXEXCLUSIVE = 1<<6 , FACET_MININCLUSIVE = 1<<7 ,
FACET_MINEXCLUSIVE = 1<<8 , FACET_TOTALDIGITS = 1<<9 , FACET_FRACTIONDIGITS = 1<<10 , FACET_ENCODING = 1<<11 ,
FACET_DURATION = 1<<12 , FACET_PERIOD = 1<<13 , FACET_WHITESPACE = 1<<14
}
enum { PRESERVE = 0 , REPLACE = 1 , COLLAPSE = 2 }
enum ValidatorType {
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown ,
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown ,
String , AnyURI , QName , Name ,
NCName , Boolean , Float , Double ,
Decimal , HexBinary , Base64Binary , Duration ,
DateTime , Date , Time , MonthDay ,
YearMonth , Year , Month , Day ,
ID , IDREF , ENTITY , NOTATION ,
List , Union , AnySimpleType , UnKnown
}
Public Member Functions
Destructor.
virtual ~DatatypeValidator ()
virtual ~DatatypeValidator ()
virtual ~DatatypeValidator ()
Getter Functions
int getFinalSet () const
RefHashTableOf< KVStringPair > * getFacets () const
short getWSFacet () const
DatatypeValidator * getBaseValidator () const
ValidatorType getType () const
virtual bool isAtomic () const
virtual const RefArrayVectorOf< XMLCh > * getEnumString () const =0
bool getAnonymous () const
void setAnonymous ()
XSSimpleTypeDefinition::ORDERING getOrdered () const
bool getFinite () const
bool getBounded () const
bool getNumeric () const
virtual const XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=0, bool toValidate=false) const
int getFinalSet () const
RefHashTableOf< KVStringPair > * getFacets () const
short getWSFacet () const
DatatypeValidator * getBaseValidator () const
ValidatorType getType () const
virtual bool isAtomic () const
virtual const RefArrayVectorOf< XMLCh > * getEnumString () const =0
bool getAnonymous () const
void setAnonymous ()
XSSimpleTypeDefinition::ORDERING getOrdered () const
bool getFinite () const
bool getBounded () const
bool getNumeric () const
virtual const XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=0, bool toValidate=false) const
int getFinalSet () const
RefHashTableOf< KVStringPair > * getFacets () const
short getWSFacet () const
DatatypeValidator * getBaseValidator () const
ValidatorType getType () const
virtual bool isAtomic () const
virtual const RefArrayVectorOf< XMLCh > * getEnumString () const =0
bool getAnonymous () const
void setAnonymous ()
XSSimpleTypeDefinition::ORDERING getOrdered () const
bool getFinite () const
bool getBounded () const
bool getNumeric () const
virtual const XMLCh * getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr=0, bool toValidate=false) const
Validation Function
virtual void validate (const XMLCh *const content, ValidationContext *const context=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)=0
virtual bool isSubstitutableBy (const DatatypeValidator *const toCheck)
virtual void validate (const XMLCh *const content, ValidationContext *const context=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)=0
virtual bool isSubstitutableBy (const DatatypeValidator *const toCheck)
virtual void validate (const XMLCh *const content, ValidationContext *const context=0, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)=0
virtual bool isSubstitutableBy (const DatatypeValidator *const toCheck)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Constructors
class DatatypeValidatorFactory
class XSObjectFactory
bool fAnonymous
bool fFinite
bool fBounded
bool fNumeric
short fWhiteSpace
int fFinalSet
int fFacetsDefined
int fFixed
ValidatorType fType
XSSimpleTypeDefinition::ORDERING fOrdered
DatatypeValidator * fBaseValidator
RefHashTableOf< KVStringPair > * fFacets
XMLCh * fPattern
RegularExpression * fRegex
XMLCh * fTypeName
const XMLCh * fTypeLocalName
const XMLCh * fTypeUri
MemoryManager * fMemoryManager
DatatypeValidator (DatatypeValidator *const baseValidator, RefHashTableOf< KVStringPair > *const facets, const int finalSet, const ValidatorType type, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
int getFacetsDefined () const
void setFacetsDefined (int)
int getFixed () const
void setFixed (int)
const XMLCh * getPattern () const
void setPattern (const XMLCh *)
RegularExpression * getRegex () const
void setRegex (RegularExpression *const)
void setType (ValidatorType)
void setWhiteSpace (short)
const XMLCh * getWSstring (const short WSType) const
void setOrdered (XSSimpleTypeDefinition::ORDERING ordered)
void setFinite (bool finite)
void setBounded (bool bounded)
void setNumeric (bool numeric)
DatatypeValidator (DatatypeValidator *const baseValidator, RefHashTableOf< KVStringPair > *const facets, const int finalSet, const ValidatorType type, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
int getFacetsDefined () const
void setFacetsDefined (int)
int getFixed () const
void setFixed (int)
const XMLCh * getPattern () const
void setPattern (const XMLCh *)
RegularExpression * getRegex () const
void setRegex (RegularExpression *const)
void setType (ValidatorType)
void setWhiteSpace (short)
const XMLCh * getWSstring (const short WSType) const
void setOrdered (XSSimpleTypeDefinition::ORDERING ordered)
void setFinite (bool finite)
void setBounded (bool bounded)
void setNumeric (bool numeric)
DatatypeValidator (DatatypeValidator *const baseValidator, RefHashTableOf< KVStringPair > *const facets, const int finalSet, const ValidatorType type, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
int getFacetsDefined () const
void setFacetsDefined (int)
int getFixed () const
void setFixed (int)
const XMLCh * getPattern () const
void setPattern (const XMLCh *)
RegularExpression * getRegex () const
void setRegex (RegularExpression *const)
void setType (ValidatorType)
void setWhiteSpace (short)
const XMLCh * getWSstring (const short WSType) const
void setOrdered (XSSimpleTypeDefinition::ORDERING ordered)
void setFinite (bool finite)
void setBounded (bool bounded)
void setNumeric (bool numeric)
void cleanUp ()
DatatypeValidator (const DatatypeValidator &)
DatatypeValidator & operator= (const DatatypeValidator &)
void cleanUp ()
DatatypeValidator (const DatatypeValidator &)
DatatypeValidator & operator= (const DatatypeValidator &)
void cleanUp ()
DatatypeValidator (const DatatypeValidator &)
DatatypeValidator & operator= (const DatatypeValidator &)
Compare Function
virtual int compare (const XMLCh *const value1, const XMLCh *const value2, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual DatatypeValidator * newInstance (RefHashTableOf< KVStringPair > *const facets, RefArrayVectorOf< XMLCh > *const enums, const int finalSet, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)=0
const XMLCh * getTypeName () const
void setTypeName (const XMLCh *const typeName)
void setTypeName (const XMLCh *const name, const XMLCh *const uri)
const XMLCh * getTypeUri () const
const XMLCh * getTypeLocalName () const
MemoryManager * getMemoryManager () const
virtual int compare (const XMLCh *const value1, const XMLCh *const value2, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual DatatypeValidator * newInstance (RefHashTableOf< KVStringPair > *const facets, RefArrayVectorOf< XMLCh > *const enums, const int finalSet, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)=0
const XMLCh * getTypeName () const
void setTypeName (const XMLCh *const typeName)
void setTypeName (const XMLCh *const name, const XMLCh *const uri)
const XMLCh * getTypeUri () const
const XMLCh * getTypeLocalName () const
MemoryManager * getMemoryManager () const
virtual int compare (const XMLCh *const value1, const XMLCh *const value2, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual DatatypeValidator * newInstance (RefHashTableOf< KVStringPair > *const facets, RefArrayVectorOf< XMLCh > *const enums, const int finalSet, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)=0
const XMLCh * getTypeName () const
void setTypeName (const XMLCh *const typeName)
void setTypeName (const XMLCh *const name, const XMLCh *const uri)
const XMLCh * getTypeUri () const
const XMLCh * getTypeLocalName () const
MemoryManager * getMemoryManager () const
static void storeDV (XSerializeEngine &serEng, DatatypeValidator *const dv)
static DatatypeValidator * loadDV (XSerializeEngine &serEng)
static void storeDV (XSerializeEngine &serEng, DatatypeValidator *const dv)
static DatatypeValidator * loadDV (XSerializeEngine &serEng)
static void storeDV (XSerializeEngine &serEng, DatatypeValidator *const dv)
static DatatypeValidator * loadDV (XSerializeEngine &serEng)
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
DataTypeValidator defines the interface that data type validators must obey. These validators can be supplied by the application writer and may be useful as standalone code as well as plugins to the validator architecture.
Notice: The datatype validator will own the facets hashtable passed to it during construction, which means that the datatype validator will be responsible for the deletion. The facets hashtable will be created during parsing and passed to the appropriate datatype validator which in turn will delete it upon its destruction.
Definition at line 55 of file DatatypeValidator.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
FACET_LENGTH
FACET_MINLENGTH
FACET_MAXLENGTH
FACET_PATTERN
FACET_ENUMERATION
FACET_MAXINCLUSIVE
FACET_MAXEXCLUSIVE
FACET_MININCLUSIVE
FACET_MINEXCLUSIVE
FACET_TOTALDIGITS
FACET_FRACTIONDIGITS
FACET_ENCODING
FACET_DURATION
FACET_PERIOD
FACET_WHITESPACE
Definition at line 62 of file DatatypeValidator.hpp.
anonymous enum
anonymous enum
Enumerator
PRESERVE
REPLACE
COLLAPSE
Definition at line 81 of file DatatypeValidator.hpp.
anonymous enum
anonymous enum
Enumerator
FACET_LENGTH
FACET_MINLENGTH
FACET_MAXLENGTH
FACET_PATTERN
FACET_ENUMERATION
FACET_MAXINCLUSIVE
FACET_MAXEXCLUSIVE
FACET_MININCLUSIVE
FACET_MINEXCLUSIVE
FACET_TOTALDIGITS
FACET_FRACTIONDIGITS
FACET_ENCODING
FACET_DURATION
FACET_PERIOD
FACET_WHITESPACE
Definition at line 62 of file DatatypeValidator.hpp.
anonymous enum
anonymous enum
Enumerator
PRESERVE
REPLACE
COLLAPSE
Definition at line 81 of file DatatypeValidator.hpp.
anonymous enum
anonymous enum
Enumerator
FACET_LENGTH
FACET_MINLENGTH
FACET_MAXLENGTH
FACET_PATTERN
FACET_ENUMERATION
FACET_MAXINCLUSIVE
FACET_MAXEXCLUSIVE
FACET_MININCLUSIVE
FACET_MINEXCLUSIVE
FACET_TOTALDIGITS
FACET_FRACTIONDIGITS
FACET_ENCODING
FACET_DURATION
FACET_PERIOD
FACET_WHITESPACE
Definition at line 62 of file DatatypeValidator.hpp.
anonymous enum
anonymous enum
Enumerator
PRESERVE
REPLACE
COLLAPSE
Definition at line 81 of file DatatypeValidator.hpp.
ValidatorType [1/3]
enum DatatypeValidator::ValidatorType
Enumerator
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
Definition at line 87 of file DatatypeValidator.hpp.
ValidatorType [2/3]
enum DatatypeValidator::ValidatorType
Enumerator
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
Definition at line 87 of file DatatypeValidator.hpp.
ValidatorType [3/3]
enum DatatypeValidator::ValidatorType
Enumerator
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
String
AnyURI
QName
Name
NCName
Boolean
Float
Double
Decimal
HexBinary
Base64Binary
Duration
DateTime
Date
Time
MonthDay
YearMonth
Year
Month
Day
ID
IDREF
ENTITY
NOTATION
List
Union
AnySimpleType
UnKnown
Definition at line 87 of file DatatypeValidator.hpp.
Constructor & Destructor Documentation
~DatatypeValidator() [1/3]
virtual DatatypeValidator::~DatatypeValidator () virtual
DatatypeValidator() [1/6]
DatatypeValidator::DatatypeValidator (DatatypeValidator *const baseValidator, RefHashTableOf< KVStringPair > *const facets, const int finalSet, const ValidatorType type, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
Parameters
baseValidator The base datatype validator for derived validators. Null if native validator.
facets A hashtable of datatype facets (except enum).
finalSet 'final' value of the simpleType
DatatypeValidator() [2/6]
DatatypeValidator::DatatypeValidator (const DatatypeValidator &) private
~DatatypeValidator() [2/3]
virtual DatatypeValidator::~DatatypeValidator () virtual
DatatypeValidator() [3/6]
DatatypeValidator::DatatypeValidator (DatatypeValidator *const baseValidator, RefHashTableOf< KVStringPair > *const facets, const int finalSet, const ValidatorType type, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
Parameters
baseValidator The base datatype validator for derived validators. Null if native validator.
facets A hashtable of datatype facets (except enum).
finalSet 'final' value of the simpleType
DatatypeValidator() [4/6]
DatatypeValidator::DatatypeValidator (const DatatypeValidator &) private
~DatatypeValidator() [3/3]
virtual DatatypeValidator::~DatatypeValidator () virtual
DatatypeValidator() [5/6]
DatatypeValidator::DatatypeValidator (DatatypeValidator *const baseValidator, RefHashTableOf< KVStringPair > *const facets, const int finalSet, const ValidatorType type, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) protected
Parameters
baseValidator The base datatype validator for derived validators. Null if native validator.
facets A hashtable of datatype facets (except enum).
finalSet 'final' value of the simpleType
DatatypeValidator() [6/6]
DatatypeValidator::DatatypeValidator (const DatatypeValidator &) private
Member Function Documentation
cleanUp() [1/3]
void DatatypeValidator::cleanUp () private
cleanUp() [2/3]
void DatatypeValidator::cleanUp () private
cleanUp() [3/3]
void DatatypeValidator::cleanUp () private
compare() [1/3]
int DatatypeValidator::compare (const XMLCh *const value1, const XMLCh *const value2, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline virtual
Compares content in the Domain value vs. lexical value.
e.g. If type is a float then 1.0 may be equivalent to 1 even though both are lexically different.
Parameters
value1 string to compare
value2 string to compare
We will provide a default behavior that should be redefined at the children level, if necessary (i.e. boolean case).
Reimplemented in UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, DateTimeValidator, AnySimpleTypeDatatypeValidator, DateTimeValidator, AnySimpleTypeDatatypeValidator, DateTimeValidator, and AnySimpleTypeDatatypeValidator.
Definition at line 716 of file DatatypeValidator.hpp.
References XMLString::compareString().
compare() [2/3]
virtual int DatatypeValidator::compare (const XMLCh *const value1, const XMLCh *const value2, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) virtual
Compares content in the Domain value vs. lexical value.
e.g. If type is a float then 1.0 may be equivalent to 1 even though both are lexically different.
Parameters
value1 string to compare
value2 string to compare
We will provide a default behavior that should be redefined at the children level, if necessary (i.e. boolean case).
Reimplemented in UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, DateTimeValidator, AnySimpleTypeDatatypeValidator, DateTimeValidator, AnySimpleTypeDatatypeValidator, DateTimeValidator, and AnySimpleTypeDatatypeValidator.
compare() [3/3]
virtual int DatatypeValidator::compare (const XMLCh *const value1, const XMLCh *const value2, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) virtual
Compares content in the Domain value vs. lexical value.
e.g. If type is a float then 1.0 may be equivalent to 1 even though both are lexically different.
Parameters
value1 string to compare
value2 string to compare
We will provide a default behavior that should be redefined at the children level, if necessary (i.e. boolean case).
Reimplemented in UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, BooleanDatatypeValidator, AbstractStringValidator, DateTimeValidator, AnySimpleTypeDatatypeValidator, DateTimeValidator, AnySimpleTypeDatatypeValidator, DateTimeValidator, and AnySimpleTypeDatatypeValidator.
getAnonymous() [1/3]
bool DatatypeValidator::getAnonymous () const inline
returns true if this type is anonymous
Definition at line 606 of file DatatypeValidator.hpp.
getAnonymous() [2/3]
bool DatatypeValidator::getAnonymous () const
returns true if this type is anonymous
getAnonymous() [3/3]
bool DatatypeValidator::getAnonymous () const
returns true if this type is anonymous
getBaseValidator() [1/3]
DatatypeValidator * DatatypeValidator::getBaseValidator () const inline
Returns the base datatype validator if set.
Definition at line 566 of file DatatypeValidator.hpp.
Referenced by isSubstitutableBy().
getBaseValidator() [2/3]
DatatypeValidator* DatatypeValidator::getBaseValidator () const
Returns the base datatype validator if set.
getBaseValidator() [3/3]
DatatypeValidator* DatatypeValidator::getBaseValidator () const
Returns the base datatype validator if set.
getBounded() [1/3]
bool DatatypeValidator::getBounded () const inline
Fundamental Facet: bounded.
Definition at line 636 of file DatatypeValidator.hpp.
getBounded() [2/3]
bool DatatypeValidator::getBounded () const
Fundamental Facet: bounded.
getBounded() [3/3]
bool DatatypeValidator::getBounded () const
Fundamental Facet: bounded.
getCanonicalRepresentation() [1/3]
virtual const XMLCh* DatatypeValidator::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = 0, bool toValidate = false) const virtual
Canonical Representation
Derivative datatype may overwrite this method once it has its own canonical representation other than the default one.
Parameters
rawData data in raw string
memMgr memory manager
toValiate to validate the raw string or not
Returns
: canonical representation of the data
Note:
the return value is kept in memory allocated by the memory manager passed in or by dv's if no memory manager is provided.
client application is responsible for the proper deallocation of the memory allocated for the returned value.
In the case where the rawData is not valid with regards to the fundamental datatype, a null string is returned.
Reimplemented in UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, AbstractNumericValidator, UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, AbstractNumericValidator, UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, and AbstractNumericValidator.
getCanonicalRepresentation() [2/3]
virtual const XMLCh* DatatypeValidator::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = 0, bool toValidate = false) const virtual
Canonical Representation
Derivative datatype may overwrite this method once it has its own canonical representation other than the default one.
Parameters
rawData data in raw string
memMgr memory manager
toValiate to validate the raw string or not
Returns
: canonical representation of the data
Note:
the return value is kept in memory allocated by the memory manager passed in or by dv's if no memory manager is provided.
client application is responsible for the proper deallocation of the memory allocated for the returned value.
In the case where the rawData is not valid with regards to the fundamental datatype, a null string is returned.
Reimplemented in UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, AbstractNumericValidator, UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, AbstractNumericValidator, UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, and AbstractNumericValidator.
getCanonicalRepresentation() [3/3]
virtual const XMLCh* DatatypeValidator::getCanonicalRepresentation (const XMLCh *const rawData, MemoryManager *const memMgr = 0, bool toValidate = false) const virtual
Canonical Representation
Derivative datatype may overwrite this method once it has its own canonical representation other than the default one.
Parameters
rawData data in raw string
memMgr memory manager
toValiate to validate the raw string or not
Returns
: canonical representation of the data
Note:
the return value is kept in memory allocated by the memory manager passed in or by dv's if no memory manager is provided.
client application is responsible for the proper deallocation of the memory allocated for the returned value.
In the case where the rawData is not valid with regards to the fundamental datatype, a null string is returned.
Reimplemented in UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, AbstractNumericValidator, UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, AbstractNumericValidator, UnionDatatypeValidator, TimeDatatypeValidator, ListDatatypeValidator, DecimalDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, and AbstractNumericValidator.
getEnumString() [1/3]
virtual const RefArrayVectorOf<XMLCh>* DatatypeValidator::getEnumString () const pure virtual
Returns the datatype enumeration if any is set. Derived class shall provide their own copy.
Implemented in UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericFacetValidator, UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericFacetValidator, UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, and AbstractNumericFacetValidator.
getEnumString() [2/3]
virtual const RefArrayVectorOf<XMLCh>* DatatypeValidator::getEnumString () const pure virtual
Returns the datatype enumeration if any is set. Derived class shall provide their own copy.
Implemented in UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericFacetValidator, UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericFacetValidator, UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, and AbstractNumericFacetValidator.
getEnumString() [3/3]
virtual const RefArrayVectorOf<XMLCh>* DatatypeValidator::getEnumString () const pure virtual
Returns the datatype enumeration if any is set. Derived class shall provide their own copy.
Implemented in UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericFacetValidator, UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericFacetValidator, UnionDatatypeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, and AbstractNumericFacetValidator.
getFacets() [1/3]
RefHashTableOf< KVStringPair > * DatatypeValidator::getFacets () const inline
Returns the datatype facet if any is set.
Definition at line 561 of file DatatypeValidator.hpp.
getFacets() [2/3]
RefHashTableOf<KVStringPair>* DatatypeValidator::getFacets () const
Returns the datatype facet if any is set.
getFacets() [3/3]
RefHashTableOf<KVStringPair>* DatatypeValidator::getFacets () const
Returns the datatype facet if any is set.
getFacetsDefined() [1/3]
int DatatypeValidator::getFacetsDefined () const inline protected
facetDefined
Definition at line 581 of file DatatypeValidator.hpp.
getFacetsDefined() [2/3]
int DatatypeValidator::getFacetsDefined () const protected
facetDefined
getFacetsDefined() [3/3]
int DatatypeValidator::getFacetsDefined () const protected
facetDefined
getFinalSet() [1/3]
int DatatypeValidator::getFinalSet () const inline
Returns the final values of the simpleType
Definition at line 556 of file DatatypeValidator.hpp.
getFinalSet() [2/3]
int DatatypeValidator::getFinalSet () const
Returns the final values of the simpleType
getFinalSet() [3/3]
int DatatypeValidator::getFinalSet () const
Returns the final values of the simpleType
getFinite() [1/3]
bool DatatypeValidator::getFinite () const inline
Fundamental Facet: cardinality.
Definition at line 631 of file DatatypeValidator.hpp.
getFinite() [2/3]
bool DatatypeValidator::getFinite () const
Fundamental Facet: cardinality.
getFinite() [3/3]
bool DatatypeValidator::getFinite () const
Fundamental Facet: cardinality.
getFixed() [1/3]
int DatatypeValidator::getFixed () const inline protected
fixed
Definition at line 586 of file DatatypeValidator.hpp.
getFixed() [2/3]
int DatatypeValidator::getFixed () const protected
fixed
getFixed() [3/3]
int DatatypeValidator::getFixed () const protected
fixed
getMemoryManager() [1/3]
MemoryManager * DatatypeValidator::getMemoryManager () const inline
Returns the plugged-in memory manager
Definition at line 621 of file DatatypeValidator.hpp.
getMemoryManager() [2/3]
MemoryManager* DatatypeValidator::getMemoryManager () const
Returns the plugged-in memory manager
getMemoryManager() [3/3]
MemoryManager* DatatypeValidator::getMemoryManager () const
Returns the plugged-in memory manager
getNumeric() [1/3]
bool DatatypeValidator::getNumeric () const inline
Fundamental Facet: numeric.
Definition at line 641 of file DatatypeValidator.hpp.
getNumeric() [2/3]
bool DatatypeValidator::getNumeric () const
Fundamental Facet: numeric.
getNumeric() [3/3]
bool DatatypeValidator::getNumeric () const
Fundamental Facet: numeric.
getOrdered() [1/3]
XSSimpleTypeDefinition::ORDERING DatatypeValidator::getOrdered () const inline
Fundamental Facet: ordered
Definition at line 626 of file DatatypeValidator.hpp.
getOrdered() [2/3]
XSSimpleTypeDefinition::ORDERING DatatypeValidator::getOrdered () const
Fundamental Facet: ordered
getOrdered() [3/3]
XSSimpleTypeDefinition::ORDERING DatatypeValidator::getOrdered () const
Fundamental Facet: ordered
getPattern() [1/3]
const XMLCh * DatatypeValidator::getPattern () const inline protected
fPattern
Definition at line 591 of file DatatypeValidator.hpp.
getPattern() [2/3]
const XMLCh* DatatypeValidator::getPattern () const protected
fPattern
getPattern() [3/3]
const XMLCh* DatatypeValidator::getPattern () const protected
fPattern
getRegex() [1/3]
RegularExpression * DatatypeValidator::getRegex () const inline protected
fRegex
Definition at line 596 of file DatatypeValidator.hpp.
getRegex() [2/3]
RegularExpression* DatatypeValidator::getRegex () const protected
fRegex
getRegex() [3/3]
RegularExpression* DatatypeValidator::getRegex () const protected
fRegex
getType() [1/3]
DatatypeValidator::ValidatorType DatatypeValidator::getType () const inline
Returns the 'class' type of datatype validator
Definition at line 576 of file DatatypeValidator.hpp.
getType() [2/3]
ValidatorType DatatypeValidator::getType () const
Returns the 'class' type of datatype validator
getType() [3/3]
ValidatorType DatatypeValidator::getType () const
Returns the 'class' type of datatype validator
getTypeLocalName() [1/3]
const XMLCh * DatatypeValidator::getTypeLocalName () const inline
Returns the name of the type this validator is for
Definition at line 611 of file DatatypeValidator.hpp.
getTypeLocalName() [2/3]
const XMLCh* DatatypeValidator::getTypeLocalName () const
Returns the name of the type this validator is for
getTypeLocalName() [3/3]
const XMLCh* DatatypeValidator::getTypeLocalName () const
Returns the name of the type this validator is for
getTypeName() [1/3]
const XMLCh * DatatypeValidator::getTypeName () const inline
Returns the uri,name of the type this validator is for
Definition at line 601 of file DatatypeValidator.hpp.
getTypeName() [2/3]
const XMLCh* DatatypeValidator::getTypeName () const
Returns the uri,name of the type this validator is for
getTypeName() [3/3]
const XMLCh* DatatypeValidator::getTypeName () const
Returns the uri,name of the type this validator is for
getTypeUri() [1/3]
const XMLCh * DatatypeValidator::getTypeUri () const inline
Returns the uri of the type this validator is for
Definition at line 616 of file DatatypeValidator.hpp.
getTypeUri() [2/3]
const XMLCh* DatatypeValidator::getTypeUri () const
Returns the uri of the type this validator is for
getTypeUri() [3/3]
const XMLCh* DatatypeValidator::getTypeUri () const
Returns the uri of the type this validator is for
getWSFacet() [1/3]
short DatatypeValidator::getWSFacet () const inline
Returns default value (collapse) for whiteSpace facet. This function is overwritten in StringDatatypeValidator.
Definition at line 571 of file DatatypeValidator.hpp.
getWSFacet() [2/3]
short DatatypeValidator::getWSFacet () const
Returns default value (collapse) for whiteSpace facet. This function is overwritten in StringDatatypeValidator.
getWSFacet() [3/3]
short DatatypeValidator::getWSFacet () const
Returns default value (collapse) for whiteSpace facet. This function is overwritten in StringDatatypeValidator.
getWSstring() [1/3]
const XMLCh* DatatypeValidator::getWSstring (const short WSType) const protected
get WSString
getWSstring() [2/3]
const XMLCh* DatatypeValidator::getWSstring (const short WSType) const protected
get WSString
getWSstring() [3/3]
const XMLCh* DatatypeValidator::getWSstring (const short WSType) const protected
get WSString
isAtomic() [1/3]
bool DatatypeValidator::isAtomic () const inline virtual
Returns whether the type is atomic or not
To be redefined in List/Union validators
Reimplemented in UnionDatatypeValidator, ListDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, ListDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, ListDatatypeValidator, and AnySimpleTypeDatatypeValidator.
Definition at line 684 of file DatatypeValidator.hpp.
isAtomic() [2/3]
virtual bool DatatypeValidator::isAtomic () const virtual
Returns whether the type is atomic or not
To be redefined in List/Union validators
Reimplemented in UnionDatatypeValidator, ListDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, ListDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, ListDatatypeValidator, and AnySimpleTypeDatatypeValidator.
isAtomic() [3/3]
virtual bool DatatypeValidator::isAtomic () const virtual
Returns whether the type is atomic or not
To be redefined in List/Union validators
Reimplemented in UnionDatatypeValidator, ListDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, ListDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, ListDatatypeValidator, and AnySimpleTypeDatatypeValidator.
isSubstitutableBy() [1/3]
bool DatatypeValidator::isSubstitutableBy (const DatatypeValidator *const toCheck) inline virtual
Checks whether a given type can be used as a substitute
Parameters
toCheck A datatype validator of the type to be used as a substitute
To be redefined in UnionDatatypeValidator
Reimplemented in UnionDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, and AnySimpleTypeDatatypeValidator.
Definition at line 727 of file DatatypeValidator.hpp.
References getBaseValidator().
isSubstitutableBy() [2/3]
virtual bool DatatypeValidator::isSubstitutableBy (const DatatypeValidator *const toCheck) virtual
Checks whether a given type can be used as a substitute
Parameters
toCheck A datatype validator of the type to be used as a substitute
To be redefined in UnionDatatypeValidator
Reimplemented in UnionDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, and AnySimpleTypeDatatypeValidator.
isSubstitutableBy() [3/3]
virtual bool DatatypeValidator::isSubstitutableBy (const DatatypeValidator *const toCheck) virtual
Checks whether a given type can be used as a substitute
Parameters
toCheck A datatype validator of the type to be used as a substitute
To be redefined in UnionDatatypeValidator
Reimplemented in UnionDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, AnySimpleTypeDatatypeValidator, UnionDatatypeValidator, and AnySimpleTypeDatatypeValidator.
loadDV() [1/3]
static DatatypeValidator* DatatypeValidator::loadDV (XSerializeEngine & serEng) static
loadDV() [2/3]
static DatatypeValidator* DatatypeValidator::loadDV (XSerializeEngine & serEng) static
loadDV() [3/3]
static DatatypeValidator* DatatypeValidator::loadDV (XSerializeEngine & serEng) static
newInstance() [1/3]
virtual DatatypeValidator* DatatypeValidator::newInstance (RefHashTableOf< KVStringPair > *const facets, RefArrayVectorOf< XMLCh > *const enums, const int finalSet, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) pure virtual
Returns an instance of the base datatype validator class Used by the DatatypeValidatorFactory.
Implemented in YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, AnySimpleTypeDatatypeValidator, YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, AnySimpleTypeDatatypeValidator, YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, and AnySimpleTypeDatatypeValidator.
newInstance() [2/3]
virtual DatatypeValidator* DatatypeValidator::newInstance (RefHashTableOf< KVStringPair > *const facets, RefArrayVectorOf< XMLCh > *const enums, const int finalSet, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) pure virtual
Returns an instance of the base datatype validator class Used by the DatatypeValidatorFactory.
Implemented in YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, AnySimpleTypeDatatypeValidator, YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, AnySimpleTypeDatatypeValidator, YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, and AnySimpleTypeDatatypeValidator.
newInstance() [3/3]
virtual DatatypeValidator* DatatypeValidator::newInstance (RefHashTableOf< KVStringPair > *const facets, RefArrayVectorOf< XMLCh > *const enums, const int finalSet, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) pure virtual
Returns an instance of the base datatype validator class Used by the DatatypeValidatorFactory.
Implemented in YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, AnySimpleTypeDatatypeValidator, YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, AnySimpleTypeDatatypeValidator, YearMonthDatatypeValidator, YearDatatypeValidator, UnionDatatypeValidator, TimeDatatypeValidator, StringDatatypeValidator, QNameDatatypeValidator, NOTATIONDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, MonthDayDatatypeValidator, MonthDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, HexBinaryDatatypeValidator, FloatDatatypeValidator, ENTITYDatatypeValidator, DurationDatatypeValidator, DoubleDatatypeValidator, DecimalDatatypeValidator, DayDatatypeValidator, DateTimeDatatypeValidator, DateDatatypeValidator, BooleanDatatypeValidator, Base64BinaryDatatypeValidator, AnyURIDatatypeValidator, and AnySimpleTypeDatatypeValidator.
operator=() [1/3]
DatatypeValidator& DatatypeValidator::operator= (const DatatypeValidator &) private
operator=() [2/3]
DatatypeValidator& DatatypeValidator::operator= (const DatatypeValidator &) private
operator=() [3/3]
DatatypeValidator& DatatypeValidator::operator= (const DatatypeValidator &) private
setAnonymous() [1/3]
void DatatypeValidator::setAnonymous () inline
sets this type to be anonymous
Definition at line 689 of file DatatypeValidator.hpp.
setAnonymous() [2/3]
void DatatypeValidator::setAnonymous ()
sets this type to be anonymous
setAnonymous() [3/3]
void DatatypeValidator::setAnonymous ()
sets this type to be anonymous
setBounded() [1/3]
void DatatypeValidator::setBounded (bool bounded) inline protected
Fundamental Facet: bounded.
Definition at line 703 of file DatatypeValidator.hpp.
setBounded() [2/3]
void DatatypeValidator::setBounded (bool bounded) protected
Fundamental Facet: bounded.
setBounded() [3/3]
void DatatypeValidator::setBounded (bool bounded) protected
Fundamental Facet: bounded.
setFacetsDefined() [1/3]
void DatatypeValidator::setFacetsDefined (int facets) inline protected
Definition at line 659 of file DatatypeValidator.hpp.
Referenced by AbstractStringValidator::setEnumeration(), and UnionDatatypeValidator::setEnumeration().
setFacetsDefined() [2/3]
void DatatypeValidator::setFacetsDefined (int) protected
setFacetsDefined() [3/3]
void DatatypeValidator::setFacetsDefined (int) protected
setFinite() [1/3]
void DatatypeValidator::setFinite (bool finite) inline protected
Fundamental Facet: cardinality.
Definition at line 698 of file DatatypeValidator.hpp.
Referenced by BooleanDatatypeValidator::BooleanDatatypeValidator().
setFinite() [2/3]
void DatatypeValidator::setFinite (bool finite) protected
Fundamental Facet: cardinality.
setFinite() [3/3]
void DatatypeValidator::setFinite (bool finite) protected
Fundamental Facet: cardinality.
setFixed() [1/3]
void DatatypeValidator::setFixed (int fixed) inline protected
Definition at line 664 of file DatatypeValidator.hpp.
setFixed() [2/3]
void DatatypeValidator::setFixed (int) protected
setFixed() [3/3]
void DatatypeValidator::setFixed (int) protected
setNumeric() [1/3]
void DatatypeValidator::setNumeric (bool numeric) inline protected
Fundamental Facet: numeric.
Definition at line 708 of file DatatypeValidator.hpp.
setNumeric() [2/3]
void DatatypeValidator::setNumeric (bool numeric) protected
Fundamental Facet: numeric.
setNumeric() [3/3]
void DatatypeValidator::setNumeric (bool numeric) protected
Fundamental Facet: numeric.
setOrdered() [1/3]
void DatatypeValidator::setOrdered (XSSimpleTypeDefinition::ORDERING ordered) inline protected
Fundamental Facet: ordered
Definition at line 693 of file DatatypeValidator.hpp.
setOrdered() [2/3]
void DatatypeValidator::setOrdered (XSSimpleTypeDefinition::ORDERING ordered) protected
Fundamental Facet: ordered
setOrdered() [3/3]
void DatatypeValidator::setOrdered (XSSimpleTypeDefinition::ORDERING ordered) protected
Fundamental Facet: ordered
setPattern() [1/3]
void DatatypeValidator::setPattern (const XMLCh * pattern) inline protected
Definition at line 669 of file DatatypeValidator.hpp.
References SchemaSymbols::fgRegEx_XOption, and XMLString::replicate().
setPattern() [2/3]
void DatatypeValidator::setPattern (const XMLCh *) protected
setPattern() [3/3]
void DatatypeValidator::setPattern (const XMLCh *) protected
setRegex() [1/3]
void DatatypeValidator::setRegex (RegularExpression * const regex) inline protected
Definition at line 679 of file DatatypeValidator.hpp.
setRegex() [2/3]
void DatatypeValidator::setRegex (RegularExpression * const) protected
setRegex() [3/3]
void DatatypeValidator::setRegex (RegularExpression * const) protected
setType() [1/3]
void DatatypeValidator::setType (ValidatorType theType) inline protected
set fType
Definition at line 649 of file DatatypeValidator.hpp.
setType() [2/3]
void DatatypeValidator::setType (ValidatorType) protected
set fType
setType() [3/3]
void DatatypeValidator::setType (ValidatorType) protected
set fType
setTypeName() [1/6]
void DatatypeValidator::setTypeName (const XMLCh *const name, const XMLCh *const uri)
sets the uri,name that this validator is for
setTypeName() [2/6]
void DatatypeValidator::setTypeName (const XMLCh *const name, const XMLCh *const uri)
sets the uri,name that this validator is for
setTypeName() [3/6]
void DatatypeValidator::setTypeName (const XMLCh *const name, const XMLCh *const uri)
sets the uri,name that this validator is for
setTypeName() [4/6]
void DatatypeValidator::setTypeName (const XMLCh *const typeName)
sets the uri,name that this validator is for - typeName is uri,name string. due to the internals of xerces this will set the uri to be the schema uri if there is no comma in typeName
setTypeName() [5/6]
void DatatypeValidator::setTypeName (const XMLCh *const typeName)
sets the uri,name that this validator is for - typeName is uri,name string. due to the internals of xerces this will set the uri to be the schema uri if there is no comma in typeName
setTypeName() [6/6]
void DatatypeValidator::setTypeName (const XMLCh *const typeName)
sets the uri,name that this validator is for - typeName is uri,name string. due to the internals of xerces this will set the uri to be the schema uri if there is no comma in typeName
setWhiteSpace() [1/3]
void DatatypeValidator::setWhiteSpace (short newValue) inline protected
set fWhiteSpace
Definition at line 654 of file DatatypeValidator.hpp.
setWhiteSpace() [2/3]
void DatatypeValidator::setWhiteSpace (short) protected
set fWhiteSpace
setWhiteSpace() [3/3]
void DatatypeValidator::setWhiteSpace (short) protected
set fWhiteSpace
storeDV() [1/3]
static void DatatypeValidator::storeDV (XSerializeEngine & serEng, DatatypeValidator *const dv) static
storeDV() [2/3]
static void DatatypeValidator::storeDV (XSerializeEngine & serEng, DatatypeValidator *const dv) static
storeDV() [3/3]
static void DatatypeValidator::storeDV (XSerializeEngine & serEng, DatatypeValidator *const dv) static
validate() [1/3]
virtual void DatatypeValidator::validate (const XMLCh *const content, ValidationContext *const context = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) pure virtual
Checks that the "content" string is valid datatype. If invalid, a Datatype validation exception is thrown.
Parameters
content A string containing the content to be validated
Implemented in UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, and AbstractNumericValidator.
validate() [2/3]
virtual void DatatypeValidator::validate (const XMLCh *const content, ValidationContext *const context = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) pure virtual
Checks that the "content" string is valid datatype. If invalid, a Datatype validation exception is thrown.
Parameters
content A string containing the content to be validated
Implemented in UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, and AbstractNumericValidator.
validate() [3/3]
virtual void DatatypeValidator::validate (const XMLCh *const content, ValidationContext *const context = 0, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) pure virtual
Checks that the "content" string is valid datatype. If invalid, a Datatype validation exception is thrown.
Parameters
content A string containing the content to be validated
Implemented in UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, AbstractNumericValidator, UnionDatatypeValidator, NCNameDatatypeValidator, NameDatatypeValidator, ListDatatypeValidator, IDREFDatatypeValidator, IDDatatypeValidator, ENTITYDatatypeValidator, DateTimeValidator, BooleanDatatypeValidator, AnySimpleTypeDatatypeValidator, AbstractStringValidator, and AbstractNumericValidator.
Friends And Related Function Documentation
DatatypeValidatorFactory
DatatypeValidatorFactory friend
Definition at line 401 of file DatatypeValidator.hpp.
XSObjectFactory
XSObjectFactory friend
Definition at line 402 of file DatatypeValidator.hpp.
Member Data Documentation
fAnonymous
bool DatatypeValidator::fAnonymous private
Definition at line 520 of file DatatypeValidator.hpp.
fBaseValidator
DatatypeValidator * DatatypeValidator::fBaseValidator private
Definition at line 533 of file DatatypeValidator.hpp.
fBounded
bool DatatypeValidator::fBounded private
Definition at line 522 of file DatatypeValidator.hpp.
fFacets
RefHashTableOf< KVStringPair > * DatatypeValidator::fFacets private
Definition at line 534 of file DatatypeValidator.hpp.
fFacetsDefined
int DatatypeValidator::fFacetsDefined private
Definition at line 527 of file DatatypeValidator.hpp.
fFinalSet
int DatatypeValidator::fFinalSet private
Definition at line 526 of file DatatypeValidator.hpp.
fFinite
bool DatatypeValidator::fFinite private
Definition at line 521 of file DatatypeValidator.hpp.
fFixed
int DatatypeValidator::fFixed private
Definition at line 528 of file DatatypeValidator.hpp.
fMemoryManager
MemoryManager * DatatypeValidator::fMemoryManager protected
Definition at line 548 of file DatatypeValidator.hpp.
fNumeric
bool DatatypeValidator::fNumeric private
Definition at line 523 of file DatatypeValidator.hpp.
fOrdered
XSSimpleTypeDefinition::ORDERING DatatypeValidator::fOrdered private
Definition at line 531 of file DatatypeValidator.hpp.
fPattern
XMLCh * DatatypeValidator::fPattern private
Definition at line 535 of file DatatypeValidator.hpp.
fRegex
RegularExpression * DatatypeValidator::fRegex private
Definition at line 536 of file DatatypeValidator.hpp.
fType
ValidatorType DatatypeValidator::fType private
Definition at line 530 of file DatatypeValidator.hpp.
fTypeLocalName
const XMLCh * DatatypeValidator::fTypeLocalName private
Definition at line 538 of file DatatypeValidator.hpp.
fTypeName
XMLCh * DatatypeValidator::fTypeName private
Definition at line 537 of file DatatypeValidator.hpp.
fTypeUri
const XMLCh * DatatypeValidator::fTypeUri private
Definition at line 539 of file DatatypeValidator.hpp.
fWhiteSpace
short DatatypeValidator::fWhiteSpace private
Definition at line 525 of file DatatypeValidator.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/datatype/DatatypeValidator.hpp