Seamly2D: VMainGraphicsScene Class Reference
VMainGraphicsScene Class Reference
The VMainGraphicsScene class main scene.
#include <vmaingraphicsscene.h>
Public Slots
void chosenItem (quint32 id, const SceneObject &type)
chosenItem emit ChosenObject signal.
void SelectedItem (bool selected, quint32 object, quint32 tool)
void EnableItemMove (bool move)
void enablePiecesMode (bool mode)
void ItemsSelection (const SelectionType &type)
void HighlightItem (quint32 id)
void ToggleLabelSelection (bool enabled)
void TogglePointSelection (bool enabled)
void ToggleLineSelection (bool enabled)
void ToggleArcSelection (bool enabled)
void ToggleElArcSelection (bool enabled)
void ToggleSplineSelection (bool enabled)
void ToggleSplinePathSelection (bool enabled)
void ToggleNodeLabelSelection (bool enabled)
void ToggleNodePointSelection (bool enabled)
void togglePieceSelection (bool enabled)
void ToggleLabelHover (bool enabled)
void TogglePointHover (bool enabled)
void ToggleLineHover (bool enabled)
void ToggleArcHover (bool enabled)
void ToggleElArcHover (bool enabled)
void ToggleSplineHover (bool enabled)
void ToggleSplinePathHover (bool enabled)
void ToggleNodeLabelHover (bool enabled)
void ToggleNodePointHover (bool enabled)
void togglePieceHover (bool enabled)
Signals
void mouseMove (const QPointF &scenePos)
mouseMove send new mouse position.
void MouseLeftPressed ()
void MouseLeftReleased ()
void ItemClicked (QGraphicsItem *pItem)
void ChosenObject (quint32 id, SceneObject type)
ChosenObject send option choosed object.
void SelectedObject (bool selected, quint32 object, quint32 tool)
void DisableItem (bool disable, const QString &draftBlockName)
void EnableToolMove (bool move)
void pieceLockedChanged (quint32 id, bool lock)
void curvePiecesMode (bool mode)
void ItemSelection (const SelectionType &type)
void highlightPiece (quint32 id)
void enableTextItemSelection (bool enable)
void EnablePointItemSelection (bool enable)
void EnableLineItemSelection (bool enable)
void EnableArcItemSelection (bool enable)
void EnableElArcItemSelection (bool enable)
void EnableSplineItemSelection (bool enable)
void EnableSplinePathItemSelection (bool enable)
void EnableNodeLabelItemSelection (bool enabled)
void EnableNodePointItemSelection (bool enabled)
void EnableDetailItemSelection (bool enabled)
void enableTextItemHover (bool enable)
void EnablePointItemHover (bool enable)
void EnableArcItemHover (bool enable)
void EnableElArcItemHover (bool enable)
void EnableSplineItemHover (bool enable)
void EnableSplinePathItemHover (bool enable)
void EnableNodeLabelItemHover (bool enabled)
void EnableNodePointItemHover (bool enabled)
void EnableDetailItemHover (bool enabled)
void EnableLineItemHover (bool enabled)
void DimensionsChanged ()
void LanguageChanged ()
Public Member Functions
VMainGraphicsScene (QObject *parent=nullptr)
VMainGraphicsScene default constructor.
VMainGraphicsScene (const QRectF &sceneRect, QObject *parent=nullptr)
VMainGraphicsScene constructor.
qint32 getHorScrollBar () const
getHorScrollBar return scene horizontal scrollbar.
void setHorScrollBar (const qint32 &value)
setHorScrollBar set scene horizontal scrollbar.
qint32 getVerScrollBar () const
getVerScrollBar return scene vertical scrollbar.
void setVerScrollBar (const qint32 &value)
setVerScrollBar set scene vertical scrollbar.
QTransform transform () const
transform return view transformation.
void setCurrentTransform (const QTransform &transform)
setCurrentTransform set view transformation.
void swapTransforms ()
swapTransforms.
void setToolsDisabled (bool disable, const QString &draftBlockName)
QPointF getScenePos () const
QRectF visibleItemsBoundingRect () const
void InitOrigins ()
void setOriginsVisible (bool visible)
Protected Member Functions
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
mouseMoveEvent handle mouse move events.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
mousePressEvent mouse press events.
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
Private Attributes
qint32 horScrollBar
horScrollBar value horizontal scroll bar.
qint32 verScrollBar
verScrollBar value vertical scroll bar.
QTransform m_previousTransform
_transform view transform value.
QTransform m_currentTransform
QPointF scenePos
QVector< QGraphicsItem * > origins
Detailed Description
The VMainGraphicsScene class main scene.
Definition at line 71 of file vmaingraphicsscene.h.
Constructor & Destructor Documentation
VMainGraphicsScene() [1/2]
VMainGraphicsScene::VMainGraphicsScene (QObject * parent = nullptr) explicit
VMainGraphicsScene default constructor.
Definition at line 75 of file vmaingraphicsscene.cpp.
VMainGraphicsScene() [2/2]
VMainGraphicsScene::VMainGraphicsScene (const QRectF & sceneRect, QObject * parent = nullptr) explicit
VMainGraphicsScene constructor.
Parameters
sceneRect scene rect.
parent parent object.
Definition at line 91 of file vmaingraphicsscene.cpp.
Member Function Documentation
chosenItem
void VMainGraphicsScene::chosenItem (quint32 id, const SceneObject & type) slot
chosenItem emit ChosenObject signal.
Parameters
id object id.
type object scene type.
Definition at line 310 of file vmaingraphicsscene.cpp.
References ChosenObject().
Referenced by PatternPieceTool::Create(), VDrawTool::InitDrawToolConnections(), and PatternPieceTool::initializeNode().
ChosenObject
void VMainGraphicsScene::ChosenObject (quint32 id, SceneObject type) signal
ChosenObject send option choosed object.
Parameters
id object id.
type object scene type.
Referenced by chosenItem(), and MainWindow::SetToolButton().
curvePiecesMode
void VMainGraphicsScene::curvePiecesMode (bool mode) signal
Referenced by enablePiecesMode(), and VDrawTool::InitDrawToolConnections().
DimensionsChanged
void VMainGraphicsScene::DimensionsChanged () signal
Referenced by MainWindow::ChangedHeight(), MainWindow::ChangedSize(), and PatternPieceTool::PatternPieceTool().
DisableItem
void VMainGraphicsScene::DisableItem (bool disable, const QString & draftBlockName) signal
Referenced by VDrawTool::InitDrawToolConnections(), and setToolsDisabled().
EnableArcItemHover
void VMainGraphicsScene::EnableArcItemHover (bool enable) signal
Referenced by VAbstractSpline::InitArcToolConnections(), VAbstractOperation::initOperationToolConnections(), and ToggleArcHover().
EnableArcItemSelection
void VMainGraphicsScene::EnableArcItemSelection (bool enable) signal
Referenced by VAbstractSpline::InitArcToolConnections(), VAbstractOperation::initOperationToolConnections(), and ToggleArcSelection().
EnableDetailItemHover
void VMainGraphicsScene::EnableDetailItemHover (bool enabled) signal
Referenced by PatternPieceTool::Create(), and togglePieceHover().
EnableDetailItemSelection
void VMainGraphicsScene::EnableDetailItemSelection (bool enabled) signal
Referenced by PatternPieceTool::Create(), and togglePieceSelection().
EnableElArcItemHover
void VMainGraphicsScene::EnableElArcItemHover (bool enable) signal
Referenced by VAbstractSpline::InitElArcToolConnections(), VAbstractOperation::initOperationToolConnections(), and ToggleElArcHover().
EnableElArcItemSelection
void VMainGraphicsScene::EnableElArcItemSelection (bool enable) signal
Referenced by VAbstractSpline::InitElArcToolConnections(), VAbstractOperation::initOperationToolConnections(), and ToggleElArcSelection().
EnableItemMove
void VMainGraphicsScene::EnableItemMove (bool move) slot
Definition at line 322 of file vmaingraphicsscene.cpp.
References EnableToolMove().
Referenced by MainWindow::InitScenes().
EnableLineItemHover
void VMainGraphicsScene::EnableLineItemHover (bool enabled) signal
Referenced by VToolLine::Create(), and ToggleLineHover().
EnableLineItemSelection
void VMainGraphicsScene::EnableLineItemSelection (bool enable) signal
Referenced by VToolLine::Create(), and ToggleLineSelection().
EnableNodeLabelItemHover
void VMainGraphicsScene::EnableNodeLabelItemHover (bool enabled) signal
Referenced by ToggleNodeLabelHover().
EnableNodeLabelItemSelection
void VMainGraphicsScene::EnableNodeLabelItemSelection (bool enabled) signal
Referenced by ToggleNodeLabelSelection().
EnableNodePointItemHover
void VMainGraphicsScene::EnableNodePointItemHover (bool enabled) signal
Referenced by ToggleNodePointHover().
EnableNodePointItemSelection
void VMainGraphicsScene::EnableNodePointItemSelection (bool enabled) signal
Referenced by ToggleNodePointSelection().
enablePiecesMode
void VMainGraphicsScene::enablePiecesMode (bool mode) slot
Definition at line 328 of file vmaingraphicsscene.cpp.
References curvePiecesMode().
Referenced by MainWindow::addDraftBlock(), and MainWindow::showDraftMode().
EnablePointItemHover
void VMainGraphicsScene::EnablePointItemHover (bool enable) signal
Referenced by VNodePoint::Create(), VAbstractOperation::initOperationToolConnections(), VAbstractPoint::InitToolConnections(), and TogglePointHover().
EnablePointItemSelection
void VMainGraphicsScene::EnablePointItemSelection (bool enable) signal
Referenced by VNodePoint::Create(), VAbstractOperation::initOperationToolConnections(), VAbstractPoint::InitToolConnections(), and TogglePointSelection().
EnableSplineItemHover
void VMainGraphicsScene::EnableSplineItemHover (bool enable) signal
Referenced by VAbstractOperation::initOperationToolConnections(), VAbstractSpline::InitSplineToolConnections(), and ToggleSplineHover().
EnableSplineItemSelection
void VMainGraphicsScene::EnableSplineItemSelection (bool enable) signal
Referenced by VAbstractOperation::initOperationToolConnections(), VAbstractSpline::InitSplineToolConnections(), and ToggleSplineSelection().
EnableSplinePathItemHover
void VMainGraphicsScene::EnableSplinePathItemHover (bool enable) signal
Referenced by VAbstractOperation::initOperationToolConnections(), VAbstractSpline::InitSplinePathToolConnections(), and ToggleSplinePathHover().
EnableSplinePathItemSelection
void VMainGraphicsScene::EnableSplinePathItemSelection (bool enable) signal
Referenced by VAbstractOperation::initOperationToolConnections(), VAbstractSpline::InitSplinePathToolConnections(), and ToggleSplinePathSelection().
enableTextItemHover
void VMainGraphicsScene::enableTextItemHover (bool enable) signal
Referenced by VNodePoint::Create(), VAbstractOperation::initOperationToolConnections(), VAbstractPoint::InitToolConnections(), and ToggleLabelHover().
enableTextItemSelection
void VMainGraphicsScene::enableTextItemSelection (bool enable) signal
Referenced by VNodePoint::Create(), VAbstractOperation::initOperationToolConnections(), VAbstractPoint::InitToolConnections(), and ToggleLabelSelection().
EnableToolMove
void VMainGraphicsScene::EnableToolMove (bool move) signal
Referenced by VNodePoint::Create(), EnableItemMove(), VDrawTool::InitDrawToolConnections(), and PatternPieceTool::PatternPieceTool().
getHorScrollBar()
qint32 VMainGraphicsScene::getHorScrollBar () const inline
getHorScrollBar return scene horizontal scrollbar.
Returns
horizontal scrollbar.
Definition at line 194 of file vmaingraphicsscene.h.
References horScrollBar.
Referenced by MainWindow::RestoreCurrentScene().
getScenePos()
QPointF VMainGraphicsScene::getScenePos () const
Definition at line 246 of file vmaingraphicsscene.cpp.
References scenePos.
Referenced by VToolBasePoint::itemChange(), PatternPieceTool::itemChange(), VControlPointSpline::itemChange(), VGraphicsSimpleTextItem::itemChange(), VToolSpline::mouseMoveEvent(), VToolSplinePath::mouseMoveEvent(), DialogCurveIntersectAxis::ShowDialog(), DialogEndLine::ShowDialog(), DialogLineIntersectAxis::ShowDialog(), DialogRotation::ShowDialog(), IntersectCirclesVisual::VisualMode(), VisToolPointOfIntersectionArcs::VisualMode(), Visualization::VisualMode(), and VisOperation::VisualMode().
getVerScrollBar()
qint32 VMainGraphicsScene::getVerScrollBar () const inline
getVerScrollBar return scene vertical scrollbar.
Returns
vertical scrollbar.
Definition at line 214 of file vmaingraphicsscene.h.
References verScrollBar.
Referenced by MainWindow::RestoreCurrentScene().
HighlightItem
void VMainGraphicsScene::HighlightItem (quint32 id) slot
Definition at line 340 of file vmaingraphicsscene.cpp.
References highlightPiece().
Referenced by MainWindow::InitDocksContain().
highlightPiece
void VMainGraphicsScene::highlightPiece (quint32 id) signal
Referenced by PatternPieceTool::Create(), and HighlightItem().
InitOrigins()
void VMainGraphicsScene::InitOrigins ()
Definition at line 143 of file vmaingraphicsscene.cpp.
References origins, qApp, and widthHairLine.
Referenced by MainWindow::addDraftBlock(), VPattern::PrepareForParse(), and MainWindow::resetOrigins().
ItemClicked
void VMainGraphicsScene::ItemClicked (QGraphicsItem * pItem) signal
Referenced by mousePressEvent(), and PatternPieceTool::PatternPieceTool().
ItemSelection
void VMainGraphicsScene::ItemSelection (const SelectionType & type) signal
Referenced by VDrawTool::InitDrawToolConnections(), and ItemsSelection().
ItemsSelection
void VMainGraphicsScene::ItemsSelection (const SelectionType & type) slot
Definition at line 334 of file vmaingraphicsscene.cpp.
References ItemSelection().
Referenced by MainWindow::InitScenes().
LanguageChanged
void VMainGraphicsScene::LanguageChanged () signal
Referenced by MainWindow::changeEvent(), and PatternPieceTool::PatternPieceTool().
MouseLeftPressed
void VMainGraphicsScene::MouseLeftPressed () signal
Referenced by DialogSpline::DialogSpline(), DialogSplinePath::DialogSplinePath(), and mousePressEvent().
MouseLeftReleased
void VMainGraphicsScene::MouseLeftReleased () signal
Referenced by DialogSpline::DialogSpline(), DialogSplinePath::DialogSplinePath(), and mouseReleaseEvent().
mouseMove
void VMainGraphicsScene::mouseMove (const QPointF & scenePos) signal
mouseMove send new mouse position.
Parameters
scenePos new mouse position.
Referenced by Visualization::addItem(), MainWindow::InitScenes(), and mouseMoveEvent().
mouseMoveEvent()
void VMainGraphicsScene::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
mouseMoveEvent handle mouse move events.
Parameters
event mouse move event.
Definition at line 106 of file vmaingraphicsscene.cpp.
References mouseMove(), and scenePos.
mousePressEvent()
void VMainGraphicsScene::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
mousePressEvent mouse press events.
Parameters
event mouse press event
Definition at line 118 of file vmaingraphicsscene.cpp.
References ItemClicked(), and MouseLeftPressed().
mouseReleaseEvent()
void VMainGraphicsScene::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
Definition at line 133 of file vmaingraphicsscene.cpp.
References MouseLeftReleased().
pieceLockedChanged
void VMainGraphicsScene::pieceLockedChanged (quint32 id, bool lock) signal
Referenced by PiecesWidget::cellClicked(), PatternPieceTool::Create(), PiecesWidget::showContextMenu(), and PiecesWidget::toggleLockedPieces().
SelectedItem
void VMainGraphicsScene::SelectedItem (bool selected, quint32 object, quint32 tool) slot
Definition at line 316 of file vmaingraphicsscene.cpp.
References SelectedObject().
Referenced by VDrawTool::InitDrawToolConnections().
SelectedObject
void VMainGraphicsScene::SelectedObject (bool selected, quint32 object, quint32 tool) signal
Referenced by SelectedItem(), and MainWindow::SetToolButton().
setCurrentTransform()
void VMainGraphicsScene::setCurrentTransform (const QTransform & transform)
setCurrentTransform set view transformation.
Parameters
transform view transformation.
Definition at line 281 of file vmaingraphicsscene.cpp.
References m_currentTransform, m_previousTransform, and transform().
Referenced by GraphicsViewZoom::gentleZoom(), MainWindow::InitScenes(), MainWindow::SaveCurrentScene(), and VMainGraphicsView::updateView().
setHorScrollBar()
void VMainGraphicsScene::setHorScrollBar (const qint32 & value) inline
setHorScrollBar set scene horizontal scrollbar.
Parameters
value horizontal scrollbar.
Definition at line 204 of file vmaingraphicsscene.h.
References horScrollBar.
Referenced by MainWindow::SaveCurrentScene().
setOriginsVisible()
void VMainGraphicsScene::setOriginsVisible (bool visible)
Definition at line 237 of file vmaingraphicsscene.cpp.
References origins.
Referenced by MainWindow::exportDraftBlocksAs(), MainWindow::resetOrigins(), MainWindow::showDraftMode(), MainWindow::showPieceMode(), and VMainGraphicsView::zoomToFit().
setToolsDisabled()
void VMainGraphicsScene::setToolsDisabled (bool disable, const QString & draftBlockName)
Definition at line 299 of file vmaingraphicsscene.cpp.
References DisableItem().
Referenced by MainWindow::setWidgetsEnabled().
setVerScrollBar()
void VMainGraphicsScene::setVerScrollBar (const qint32 & value) inline
setVerScrollBar set scene vertical scrollbar.
Parameters
value vertical scrollbar.
Definition at line 224 of file vmaingraphicsscene.h.
References verScrollBar.
Referenced by MainWindow::SaveCurrentScene().
swapTransforms()
void VMainGraphicsScene::swapTransforms ()
swapTransforms.
Definition at line 291 of file vmaingraphicsscene.cpp.
References m_currentTransform, and m_previousTransform.
Referenced by MainWindow::zoomToPrevious().
ToggleArcHover
void VMainGraphicsScene::ToggleArcHover (bool enabled) slot
Definition at line 424 of file vmaingraphicsscene.cpp.
References EnableArcItemHover().
Referenced by MainWindow::InitScenes(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
ToggleArcSelection
void VMainGraphicsScene::ToggleArcSelection (bool enabled) slot
Definition at line 364 of file vmaingraphicsscene.cpp.
References EnableArcItemSelection().
Referenced by MainWindow::InitScenes(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
ToggleElArcHover
void VMainGraphicsScene::ToggleElArcHover (bool enabled) slot
Definition at line 430 of file vmaingraphicsscene.cpp.
References EnableElArcItemHover().
Referenced by MainWindow::InitScenes(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
ToggleElArcSelection
void VMainGraphicsScene::ToggleElArcSelection (bool enabled) slot
Definition at line 370 of file vmaingraphicsscene.cpp.
References EnableElArcItemSelection().
Referenced by MainWindow::InitScenes(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
ToggleLabelHover
void VMainGraphicsScene::ToggleLabelHover (bool enabled) slot
Definition at line 406 of file vmaingraphicsscene.cpp.
References enableTextItemHover().
Referenced by MainWindow::InitScenes().
ToggleLabelSelection
void VMainGraphicsScene::ToggleLabelSelection (bool enabled) slot
Definition at line 346 of file vmaingraphicsscene.cpp.
References enableTextItemSelection().
Referenced by MainWindow::InitScenes().
ToggleLineHover
void VMainGraphicsScene::ToggleLineHover (bool enabled) slot
Definition at line 418 of file vmaingraphicsscene.cpp.
References EnableLineItemHover().
Referenced by MainWindow::InitScenes().
ToggleLineSelection
void VMainGraphicsScene::ToggleLineSelection (bool enabled) slot
Definition at line 358 of file vmaingraphicsscene.cpp.
References EnableLineItemSelection().
Referenced by MainWindow::InitScenes().
ToggleNodeLabelHover
void VMainGraphicsScene::ToggleNodeLabelHover (bool enabled) slot
Definition at line 448 of file vmaingraphicsscene.cpp.
References EnableNodeLabelItemHover().
Referenced by MainWindow::InitScenes().
ToggleNodeLabelSelection
void VMainGraphicsScene::ToggleNodeLabelSelection (bool enabled) slot
Definition at line 388 of file vmaingraphicsscene.cpp.
References EnableNodeLabelItemSelection().
Referenced by MainWindow::InitScenes().
ToggleNodePointHover
void VMainGraphicsScene::ToggleNodePointHover (bool enabled) slot
Definition at line 454 of file vmaingraphicsscene.cpp.
References EnableNodePointItemHover().
Referenced by MainWindow::InitScenes().
ToggleNodePointSelection
void VMainGraphicsScene::ToggleNodePointSelection (bool enabled) slot
Definition at line 394 of file vmaingraphicsscene.cpp.
References EnableNodePointItemSelection().
Referenced by MainWindow::InitScenes().
togglePieceHover
void VMainGraphicsScene::togglePieceHover (bool enabled) slot
Definition at line 460 of file vmaingraphicsscene.cpp.
References EnableDetailItemHover().
Referenced by MainWindow::InitScenes().
togglePieceSelection
void VMainGraphicsScene::togglePieceSelection (bool enabled) slot
Definition at line 400 of file vmaingraphicsscene.cpp.
References EnableDetailItemSelection().
Referenced by MainWindow::InitScenes().
TogglePointHover
void VMainGraphicsScene::TogglePointHover (bool enabled) slot
Definition at line 412 of file vmaingraphicsscene.cpp.
References EnablePointItemHover().
Referenced by MainWindow::InitScenes().
TogglePointSelection
void VMainGraphicsScene::TogglePointSelection (bool enabled) slot
Definition at line 352 of file vmaingraphicsscene.cpp.
References EnablePointItemSelection().
Referenced by MainWindow::InitScenes().
ToggleSplineHover
void VMainGraphicsScene::ToggleSplineHover (bool enabled) slot
Definition at line 436 of file vmaingraphicsscene.cpp.
References EnableSplineItemHover().
Referenced by MainWindow::InitScenes(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
ToggleSplinePathHover
void VMainGraphicsScene::ToggleSplinePathHover (bool enabled) slot
Definition at line 442 of file vmaingraphicsscene.cpp.
References EnableSplinePathItemHover().
Referenced by MainWindow::InitScenes(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
ToggleSplinePathSelection
void VMainGraphicsScene::ToggleSplinePathSelection (bool enabled) slot
Definition at line 382 of file vmaingraphicsscene.cpp.
References EnableSplinePathItemSelection().
Referenced by MainWindow::InitScenes(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
ToggleSplineSelection
void VMainGraphicsScene::ToggleSplineSelection (bool enabled) slot
Definition at line 376 of file vmaingraphicsscene.cpp.
References EnableSplineItemSelection().
Referenced by MainWindow::InitScenes(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().
transform()
QTransform VMainGraphicsScene::transform () const
transform return view transformation.
Returns
view transformation.
Definition at line 271 of file vmaingraphicsscene.cpp.
References m_currentTransform.
Referenced by MainWindow::RestoreCurrentScene(), setCurrentTransform(), and MainWindow::zoomToPrevious().
visibleItemsBoundingRect()
QRectF VMainGraphicsScene::visibleItemsBoundingRect () const
Definition at line 252 of file vmaingraphicsscene.cpp.
Referenced by MainWindow::draftBlockStartPosition(), VMainGraphicsView::NewSceneRect(), and VMainGraphicsView::zoomToFit().
Member Data Documentation
horScrollBar
qint32 VMainGraphicsScene::horScrollBar private
horScrollBar value horizontal scroll bar.
Definition at line 177 of file vmaingraphicsscene.h.
Referenced by getHorScrollBar(), and setHorScrollBar().
m_currentTransform
QTransform VMainGraphicsScene::m_currentTransform private
Definition at line 184 of file vmaingraphicsscene.h.
Referenced by setCurrentTransform(), swapTransforms(), and transform().
m_previousTransform
QTransform VMainGraphicsScene::m_previousTransform private
_transform view transform value.
Definition at line 183 of file vmaingraphicsscene.h.
Referenced by setCurrentTransform(), and swapTransforms().
origins
QVector<QGraphicsItem *> VMainGraphicsScene::origins private
Definition at line 186 of file vmaingraphicsscene.h.
Referenced by InitOrigins(), and setOriginsVisible().
scenePos
QPointF VMainGraphicsScene::scenePos private
Definition at line 185 of file vmaingraphicsscene.h.
Referenced by getScenePos(), and mouseMoveEvent().
verScrollBar
qint32 VMainGraphicsScene::verScrollBar private
verScrollBar value vertical scroll bar.
Definition at line 180 of file vmaingraphicsscene.h.
Referenced by getVerScrollBar(), and setVerScrollBar().
The documentation for this class was generated from the following files:
src/libs/vwidgets/vmaingraphicsscene.h
src/libs/vwidgets/vmaingraphicsscene.cpp