Seamly2D: VToolOptionsPropertyBrowser Class Reference
VToolOptionsPropertyBrowser Class Reference
#include <vtooloptionspropertybrowser.h>
Public Slots
void itemClicked (QGraphicsItem *item)
void updateOptions ()
void refreshOptions ()
Public Member Functions
VToolOptionsPropertyBrowser (const VContainer *data, QDockWidget *parent)
void clearPropertyBrowser ()
Protected Attributes
const VContainer * m_data
VPE::VPropertyModel * propertyModel
VPE::VPropertyFormView * formView
QGraphicsItem * currentItem
QMap< VPE::VProperty *, QString > propertyToId
QMap< QString, VPE::VProperty * > idToProperty
Private Slots
void userChangedData (VPE::VProperty *property)
Private Member Functions
void addProperty (VPE::VProperty *property, const QString &id)
void showItemOptions (QGraphicsItem *item)
template<class Tool >
QMap< QString, quint32 > getObjectList (Tool *tool, GOType objType)
template<class Tool >
void setPointName (const QString &name)
template<class Tool >
void setPointName1 (const QString &name)
template<class Tool >
void setPointName2 (const QString &name)
template<class Tool >
void setOperationSuffix (const QString &suffix)
template<class Type >
Type getCrossPoint (const QVariant &value)
template<class Tool >
void setCirclesCrossPoint (const QVariant &value)
template<class Tool >
void setCurveVCrossPoint (const QVariant &value)
template<class Tool >
void setCurveHCrossPoint (const QVariant &value)
template<class Tool >
void setAxisType (const QVariant &value)
template<class Tool >
void addPropertyObjectName (Tool *tool, const QString &propertyName, bool readOnly=false)
template<class Tool >
void addPropertyPointName1 (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyPointName2 (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyOperationSuffix (Tool *tool, const QString &propertyName, bool readOnly=false)
template<class Tool >
void addPropertyLineName (Tool *tool, const QString &propertyName, bool readOnly=false)
template<class Tool >
void addPropertyCurveName (Tool *tool, const QString &propertyName, const QString &prefix, const QString &firstPoint, const QString &secondPoint, bool readOnly=false)
template<class Tool >
void addPropertyCrossPoint (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyVCrossPoint (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyHCrossPoint (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyAxisType (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyLineType (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyCurveLineType (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyLineWeight (Tool *tool, const QString &propertyName)
template<class Tool >
void addPropertyLineColor (Tool *tool, const QString &propertyName, const QString &id)
template<class Tool >
void addObjectProperty (Tool *tool, const QString &pointName, const QString &propertyName, const QString &id, GOType objType)
void addPropertyFormula (const QString &propertyName, const VFormula &formula, const QString &attrName)
void addPropertyParentPointName (const QString &pointName, const QString &propertyName, const QString &propertyAttribute)
void addPropertyLabel (const QString &propertyName, const QString &propertyAttribute)
QStringList propertiesList () const
void changeDataToolSinglePoint (VPE::VProperty *property)
void changeDataToolEndLine (VPE::VProperty *property)
void changeDataToolAlongLine (VPE::VProperty *property)
void changeDataToolArc (VPE::VProperty *property)
void changeDataToolArcWithLength (VPE::VProperty *property)
void changeDataToolBisector (VPE::VProperty *property)
void changeDataToolTrueDarts (VPE::VProperty *property)
void changeDataToolCutArc (VPE::VProperty *property)
void changeDataToolCutSpline (VPE::VProperty *property)
void changeDataToolCutSplinePath (VPE::VProperty *property)
void changeDataToolHeight (VPE::VProperty *property)
void changeDataToolLine (VPE::VProperty *property)
void changeDataToolLineIntersect (VPE::VProperty *property)
void changeDataToolNormal (VPE::VProperty *property)
void changeDataToolPointOfContact (VPE::VProperty *property)
void changeDataToolPointOfIntersection (VPE::VProperty *property)
void changeDataToolPointOfIntersectionArcs (VPE::VProperty *property)
void changeDataToolPointOfIntersectionCircles (VPE::VProperty *property)
void changeDataToolPointOfIntersectionCurves (VPE::VProperty *property)
void changeDataToolPointFromCircleAndTangent (VPE::VProperty *property)
void changeDataToolPointFromArcAndTangent (VPE::VProperty *property)
void changeDataToolShoulderPoint (VPE::VProperty *property)
void changeDataToolSpline (VPE::VProperty *property)
void changeDataToolCubicBezier (VPE::VProperty *property)
void changeDataToolSplinePath (VPE::VProperty *property)
void changeDataToolCubicBezierPath (VPE::VProperty *property)
void changeDataToolTriangle (VPE::VProperty *property)
void changeDataToolLineIntersectAxis (VPE::VProperty *property)
void changeDataToolCurveIntersectAxis (VPE::VProperty *property)
void changeDataToolRotation (VPE::VProperty *property)
void changeDataToolMove (VPE::VProperty *property)
void changeDataToolMirrorByLine (VPE::VProperty *property)
void changeDataToolMirrorByAxis (VPE::VProperty *property)
void changeDataToolEllipticalArc (VPE::VProperty *property)
void showOptionsToolSinglePoint (QGraphicsItem *item)
void showOptionsToolEndLine (QGraphicsItem *item)
void showOptionsToolAlongLine (QGraphicsItem *item)
void showOptionsToolArc (QGraphicsItem *item)
void showOptionsToolArcWithLength (QGraphicsItem *item)
void showOptionsToolBisector (QGraphicsItem *item)
void showOptionsToolTrueDarts (QGraphicsItem *item)
void showOptionsToolCutArc (QGraphicsItem *item)
void showOptionsToolCutSpline (QGraphicsItem *item)
void showOptionsToolCutSplinePath (QGraphicsItem *item)
void showOptionsToolHeight (QGraphicsItem *item)
void showOptionsToolLine (QGraphicsItem *item)
void showOptionsToolLineIntersect (QGraphicsItem *item)
void showOptionsToolNormal (QGraphicsItem *item)
void showOptionsToolPointOfContact (QGraphicsItem *item)
void showOptionsToolPointOfIntersection (QGraphicsItem *item)
void showOptionsToolPointOfIntersectionArcs (QGraphicsItem *item)
void showOptionsToolPointOfIntersectionCircles (QGraphicsItem *item)
void showOptionsToolPointOfIntersectionCurves (QGraphicsItem *item)
void showOptionsToolPointFromCircleAndTangent (QGraphicsItem *item)
void showOptionsToolPointFromArcAndTangent (QGraphicsItem *item)
void showOptionsToolShoulderPoint (QGraphicsItem *item)
void showOptionsToolSpline (QGraphicsItem *item)
void showOptionsToolCubicBezier (QGraphicsItem *item)
void showOptionsToolSplinePath (QGraphicsItem *item)
void showOptionsToolCubicBezierPath (QGraphicsItem *item)
void showOptionsToolTriangle (QGraphicsItem *item)
void showOptionsToolLineIntersectAxis (QGraphicsItem *item)
void showOptionsToolCurveIntersectAxis (QGraphicsItem *item)
void showOptionsToolRotation (QGraphicsItem *item)
void showOptionsToolMove (QGraphicsItem *item)
void showOptionsToolMirrorByLine (QGraphicsItem *item)
void showOptionsToolMirrorByAxis (QGraphicsItem *item)
void showOptionsToolEllipticalArc (QGraphicsItem *item)
void updateOptionsToolSinglePoint ()
void updateOptionsToolEndLine ()
void updateOptionsToolAlongLine ()
void updateOptionsToolArc ()
void updateOptionsToolArcWithLength ()
void updateOptionsToolBisector ()
void updateOptionsToolTrueDarts ()
void updateOptionsToolCutArc ()
void updateOptionsToolCutSpline ()
void updateOptionsToolCutSplinePath ()
void updateOptionsToolHeight ()
void updateOptionsToolLine ()
void updateOptionsToolLineIntersect ()
void updateOptionsToolNormal ()
void updateOptionsToolPointOfContact ()
void updateOptionsToolPointOfIntersection ()
void updateOptionsToolPointOfIntersectionArcs ()
void updateOptionsToolPointOfIntersectionCircles ()
void updateOptionsToolPointOfIntersectionCurves ()
void updateOptionsToolPointFromCircleAndTangent ()
void updateOptionsToolPointFromArcAndTangent ()
void updateOptionsToolShoulderPoint ()
void updateOptionsToolSpline ()
void updateOptionsToolCubicBezier ()
void updateOptionsToolSplinePath ()
void updateOptionsToolCubicBezierPath ()
void updateOptionsToolTriangle ()
void updateOptionsToolLineIntersectAxis ()
void updateOptionsToolCurveIntersectAxis ()
void updateOptionsToolRotation ()
void updateOptionsToolMove ()
void updateOptionsToolMirrorByLine ()
void updateOptionsToolMirrorByAxis ()
void updateOptionsToolEllipticalArc ()
Detailed Description
Definition at line 73 of file vtooloptionspropertybrowser.h.
Constructor & Destructor Documentation
VToolOptionsPropertyBrowser()
VToolOptionsPropertyBrowser::VToolOptionsPropertyBrowser (const VContainer * data, QDockWidget * parent) explicit
Definition at line 82 of file vtooloptionspropertybrowser.cpp.
References formView, VPE::VPropertyModel::onDataChangedByEditor(), propertyModel, and userChangedData().
Member Function Documentation
addObjectProperty()
template<class Tool > void VToolOptionsPropertyBrowser::addObjectProperty (Tool * tool, const QString & pointName, const QString & propertyName, const QString & id, GOType objType) private
Definition at line 744 of file vtooloptionspropertybrowser.cpp.
References addProperty(), getObjectList(), VPE::VObjectProperty::indexOfObject(), VPE::VObjectProperty::setObjectsList(), and VPE::VObjectProperty::setValue().
Referenced by showOptionsToolAlongLine(), showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolBisector(), showOptionsToolCubicBezier(), showOptionsToolCurveIntersectAxis(), showOptionsToolCutArc(), showOptionsToolCutSpline(), showOptionsToolCutSplinePath(), showOptionsToolEllipticalArc(), showOptionsToolEndLine(), showOptionsToolHeight(), showOptionsToolLine(), showOptionsToolLineIntersect(), showOptionsToolLineIntersectAxis(), showOptionsToolMirrorByAxis(), showOptionsToolMirrorByLine(), showOptionsToolMove(), showOptionsToolNormal(), showOptionsToolPointFromArcAndTangent(), showOptionsToolPointFromCircleAndTangent(), showOptionsToolPointOfContact(), showOptionsToolPointOfIntersection(), showOptionsToolPointOfIntersectionArcs(), showOptionsToolPointOfIntersectionCircles(), showOptionsToolPointOfIntersectionCurves(), showOptionsToolRotation(), showOptionsToolShoulderPoint(), showOptionsToolSpline(), showOptionsToolTriangle(), and showOptionsToolTrueDarts().
addProperty()
void VToolOptionsPropertyBrowser::addProperty (VPE::VProperty * property, const QString & id) private
Definition at line 1095 of file vtooloptionspropertybrowser.cpp.
References VPE::VPropertyModel::addProperty(), idToProperty, propertyModel, and propertyToId.
Referenced by addObjectProperty(), addPropertyAxisType(), addPropertyCrossPoint(), addPropertyCurveLineType(), addPropertyCurveName(), addPropertyFormula(), addPropertyHCrossPoint(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineName(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), addPropertyOperationSuffix(), addPropertyParentPointName(), addPropertyPointName1(), addPropertyPointName2(), addPropertyVCrossPoint(), showOptionsToolNormal(), and showOptionsToolSinglePoint().
addPropertyAxisType()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyAxisType (Tool * tool, const QString & propertyName) private
Definition at line 667 of file vtooloptionspropertybrowser.cpp.
References addProperty(), and AttrAxisType.
Referenced by showOptionsToolMirrorByAxis().
addPropertyCrossPoint()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyCrossPoint (Tool * tool, const QString & propertyName) private
Definition at line 637 of file vtooloptionspropertybrowser.cpp.
References addProperty(), AttrCrossPoint, VPE::VEnumProperty::setLiterals(), and VPE::VEnumProperty::setValue().
Referenced by showOptionsToolPointFromArcAndTangent(), showOptionsToolPointFromCircleAndTangent(), showOptionsToolPointOfIntersectionArcs(), and showOptionsToolPointOfIntersectionCircles().
addPropertyCurveLineType()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyCurveLineType (Tool * tool, const QString & propertyName) private
Definition at line 699 of file vtooloptionspropertybrowser.cpp.
References addProperty(), AttrPenStyle, curveLineTypeList(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineTypeProperty::setLineTypes(), and VPE::LineTypeProperty::setValue().
Referenced by showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolCubicBezier(), showOptionsToolCubicBezierPath(), showOptionsToolEllipticalArc(), showOptionsToolSpline(), and showOptionsToolSplinePath().
addPropertyCurveName()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyCurveName (Tool * tool, const QString & propertyName, const QString & prefix, const QString & firstPoint, const QString & secondPoint, bool readOnly = false) private
Definition at line 605 of file vtooloptionspropertybrowser.cpp.
References addProperty(), and AttrObjName.
Referenced by showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolCubicBezier(), showOptionsToolCubicBezierPath(), showOptionsToolEllipticalArc(), showOptionsToolSpline(), and showOptionsToolSplinePath().
addPropertyFormula()
void VToolOptionsPropertyBrowser::addPropertyFormula (const QString & propertyName, const VFormula & formula, const QString & attrName) private
Definition at line 543 of file vtooloptionspropertybrowser.cpp.
References addProperty(), and VFormulaProperty::SetFormula().
Referenced by showOptionsToolAlongLine(), showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolBisector(), showOptionsToolCurveIntersectAxis(), showOptionsToolCutArc(), showOptionsToolCutSpline(), showOptionsToolCutSplinePath(), showOptionsToolEllipticalArc(), showOptionsToolEndLine(), showOptionsToolLineIntersectAxis(), showOptionsToolMove(), showOptionsToolNormal(), showOptionsToolPointFromCircleAndTangent(), showOptionsToolPointOfContact(), showOptionsToolPointOfIntersectionCircles(), showOptionsToolRotation(), showOptionsToolShoulderPoint(), and showOptionsToolSpline().
addPropertyHCrossPoint()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyHCrossPoint (Tool * tool, const QString & propertyName) private
Definition at line 657 of file vtooloptionspropertybrowser.cpp.
References addProperty(), and AttrHCrossPoint.
Referenced by showOptionsToolPointOfIntersectionCurves().
addPropertyLabel()
void VToolOptionsPropertyBrowser::addPropertyLabel (const QString & propertyName, const QString & propertyAttribute) private
Definition at line 627 of file vtooloptionspropertybrowser.cpp.
References addProperty(), and VPE::Label.
Referenced by showOptionsToolAlongLine(), showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolBisector(), showOptionsToolCubicBezier(), showOptionsToolCubicBezierPath(), showOptionsToolCurveIntersectAxis(), showOptionsToolCutArc(), showOptionsToolCutSpline(), showOptionsToolCutSplinePath(), showOptionsToolEllipticalArc(), showOptionsToolEndLine(), showOptionsToolHeight(), showOptionsToolLine(), showOptionsToolLineIntersect(), showOptionsToolLineIntersectAxis(), showOptionsToolMirrorByAxis(), showOptionsToolMirrorByLine(), showOptionsToolMove(), showOptionsToolNormal(), showOptionsToolPointFromArcAndTangent(), showOptionsToolPointFromCircleAndTangent(), showOptionsToolPointOfContact(), showOptionsToolPointOfIntersection(), showOptionsToolPointOfIntersectionArcs(), showOptionsToolPointOfIntersectionCircles(), showOptionsToolPointOfIntersectionCurves(), showOptionsToolRotation(), showOptionsToolShoulderPoint(), showOptionsToolSinglePoint(), showOptionsToolSpline(), showOptionsToolSplinePath(), showOptionsToolTriangle(), and showOptionsToolTrueDarts().
addPropertyLineColor()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyLineColor (Tool * tool, const QString & propertyName, const QString & id) private
Definition at line 729 of file vtooloptionspropertybrowser.cpp.
References addProperty(), VAbstractTool::ColorsList(), VPE::VLineColorProperty::indexOfColor(), VPE::VLineColorProperty::setColors(), and VPE::VLineColorProperty::setValue().
Referenced by showOptionsToolAlongLine(), showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolBisector(), showOptionsToolCubicBezier(), showOptionsToolCubicBezierPath(), showOptionsToolCurveIntersectAxis(), showOptionsToolEllipticalArc(), showOptionsToolEndLine(), showOptionsToolHeight(), showOptionsToolLine(), showOptionsToolLineIntersectAxis(), showOptionsToolNormal(), showOptionsToolPointOfIntersection(), showOptionsToolShoulderPoint(), showOptionsToolSpline(), and showOptionsToolSplinePath().
addPropertyLineName()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyLineName (Tool * tool, const QString & propertyName, bool readOnly = false) private
Definition at line 595 of file vtooloptionspropertybrowser.cpp.
References addProperty(), and AttrObjName.
Referenced by showOptionsToolLine().
addPropertyLineType()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyLineType (Tool * tool, const QString & propertyName) private
Definition at line 677 of file vtooloptionspropertybrowser.cpp.
References addProperty(), AttrLineType, VPE::LineTypeProperty::indexOfLineType(), lineTypeList(), LineTypeNone, VPE::LineTypeProperty::setLineTypes(), VPE::LineTypeProperty::setValue(), and VToolLine::Type.
Referenced by showOptionsToolAlongLine(), showOptionsToolBisector(), showOptionsToolCurveIntersectAxis(), showOptionsToolEndLine(), showOptionsToolHeight(), showOptionsToolLine(), showOptionsToolLineIntersectAxis(), showOptionsToolNormal(), showOptionsToolPointOfIntersection(), and showOptionsToolShoulderPoint().
addPropertyLineWeight()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyLineWeight (Tool * tool, const QString & propertyName) private
Definition at line 714 of file vtooloptionspropertybrowser.cpp.
References addProperty(), AttrLineWeight, VPE::LineWeightProperty::indexOfLineWeight(), lineWeightList(), VPE::LineWeightProperty::setLineWeights(), and VPE::LineWeightProperty::setValue().
Referenced by showOptionsToolAlongLine(), showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolBisector(), showOptionsToolCubicBezier(), showOptionsToolCubicBezierPath(), showOptionsToolCurveIntersectAxis(), showOptionsToolEllipticalArc(), showOptionsToolEndLine(), showOptionsToolHeight(), showOptionsToolLine(), showOptionsToolLineIntersectAxis(), showOptionsToolNormal(), showOptionsToolPointOfIntersection(), showOptionsToolShoulderPoint(), showOptionsToolSpline(), and showOptionsToolSplinePath().
addPropertyObjectName()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyObjectName (Tool * tool, const QString & propertyName, bool readOnly = false) private
Definition at line 553 of file vtooloptionspropertybrowser.cpp.
References addProperty(), AttrName, qApp, VPE::VStringProperty::setClearButtonEnable(), VPE::VStringProperty::setReadOnly(), and VPE::VProperty::setValue().
Referenced by showOptionsToolAlongLine(), showOptionsToolBisector(), showOptionsToolCurveIntersectAxis(), showOptionsToolCutArc(), showOptionsToolCutSpline(), showOptionsToolCutSplinePath(), showOptionsToolEndLine(), showOptionsToolHeight(), showOptionsToolLineIntersect(), showOptionsToolLineIntersectAxis(), showOptionsToolNormal(), showOptionsToolPointFromArcAndTangent(), showOptionsToolPointFromCircleAndTangent(), showOptionsToolPointOfContact(), showOptionsToolPointOfIntersection(), showOptionsToolPointOfIntersectionArcs(), showOptionsToolPointOfIntersectionCircles(), showOptionsToolPointOfIntersectionCurves(), showOptionsToolShoulderPoint(), showOptionsToolSinglePoint(), and showOptionsToolTriangle().
addPropertyOperationSuffix()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyOperationSuffix (Tool * tool, const QString & propertyName, bool readOnly = false) private
Definition at line 584 of file vtooloptionspropertybrowser.cpp.
References addProperty(), AttrSuffix, VPE::VStringProperty::setClearButtonEnable(), VPE::VStringProperty::setReadOnly(), and VPE::VProperty::setValue().
Referenced by showOptionsToolMirrorByAxis(), showOptionsToolMirrorByLine(), showOptionsToolMove(), and showOptionsToolRotation().
addPropertyParentPointName()
void VToolOptionsPropertyBrowser::addPropertyParentPointName (const QString & pointName, const QString & propertyName, const QString & propertyAttribute) private
Definition at line 618 of file vtooloptionspropertybrowser.cpp.
References addProperty().
addPropertyPointName1()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyPointName1 (Tool * tool, const QString & propertyName) private
Definition at line 564 of file vtooloptionspropertybrowser.cpp.
References addProperty(), AttrName1, VPE::VStringProperty::setClearButtonEnable(), and VPE::VProperty::setValue().
Referenced by showOptionsToolTrueDarts().
addPropertyPointName2()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyPointName2 (Tool * tool, const QString & propertyName) private
Definition at line 574 of file vtooloptionspropertybrowser.cpp.
References addProperty(), AttrName2, VPE::VStringProperty::setClearButtonEnable(), and VPE::VProperty::setValue().
Referenced by showOptionsToolTrueDarts().
addPropertyVCrossPoint()
template<class Tool > void VToolOptionsPropertyBrowser::addPropertyVCrossPoint (Tool * tool, const QString & propertyName) private
Definition at line 647 of file vtooloptionspropertybrowser.cpp.
References addProperty(), and AttrVCrossPoint.
Referenced by showOptionsToolPointOfIntersectionCurves().
changeDataToolAlongLine()
void VToolOptionsPropertyBrowser::changeDataToolAlongLine (VPE::VProperty * property) private
Definition at line 1166 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLinePoint::SetBasePointId(), VToolLinePoint::SetFormulaLength(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), VDrawTool::setLineWeight(), and VToolAlongLine::SetSecondPointId().
Referenced by userChangedData().
changeDataToolArc()
void VToolOptionsPropertyBrowser::changeDataToolArc (VPE::VProperty * property) private
Definition at line 1205 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolArc::setCenter(), VToolArc::SetFormulaF1(), VToolArc::SetFormulaF2(), VToolArc::SetFormulaRadius(), VAbstractSpline::setLineColor(), VAbstractSpline::setLineWeight(), and VAbstractSpline::SetPenStyle().
Referenced by userChangedData().
changeDataToolArcWithLength()
void VToolOptionsPropertyBrowser::changeDataToolArcWithLength (VPE::VProperty * property) private
Definition at line 1248 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolArcWithLength::setCenter(), VToolArcWithLength::SetFormulaF1(), VToolArcWithLength::SetFormulaLength(), VToolArcWithLength::SetFormulaRadius(), VAbstractSpline::setLineColor(), VAbstractSpline::setLineWeight(), and VAbstractSpline::SetPenStyle().
Referenced by userChangedData().
changeDataToolBisector()
void VToolOptionsPropertyBrowser::changeDataToolBisector (VPE::VProperty * property) private
Definition at line 1290 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLinePoint::SetBasePointId(), VToolBisector::SetFirstPointId(), VToolLinePoint::SetFormulaLength(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), VDrawTool::setLineWeight(), and VToolBisector::SetThirdPointId().
Referenced by userChangedData().
changeDataToolCubicBezier()
void VToolOptionsPropertyBrowser::changeDataToolCubicBezier (VPE::VProperty * property) private
Definition at line 1964 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, VContainer::GeometricObject(), VToolCubicBezier::getSpline(), m_data, propertiesList(), propertyToId, SCASSERT, VAbstractSpline::setLineColor(), VAbstractSpline::setLineWeight(), VAbstractSpline::SetPenStyle(), and VToolCubicBezier::setSpline().
Referenced by userChangedData().
changeDataToolCubicBezierPath()
void VToolOptionsPropertyBrowser::changeDataToolCubicBezierPath (VPE::VProperty * property) private
Definition at line 2048 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VAbstractSpline::setLineColor(), VAbstractSpline::setLineWeight(), and VAbstractSpline::SetPenStyle().
Referenced by userChangedData().
changeDataToolCurveIntersectAxis()
void VToolOptionsPropertyBrowser::changeDataToolCurveIntersectAxis (VPE::VProperty * property) private
Definition at line 2153 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLinePoint::SetBasePointId(), VToolCurveIntersectAxis::setCurveId(), VToolCurveIntersectAxis::SetFormulaAngle(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), and VDrawTool::setLineWeight().
Referenced by userChangedData().
changeDataToolCutArc()
void VToolOptionsPropertyBrowser::changeDataToolCutArc (VPE::VProperty * property) private
Definition at line 1371 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolCut::setCurveCutId(), and VToolCut::SetFormula().
Referenced by userChangedData().
changeDataToolCutSpline()
void VToolOptionsPropertyBrowser::changeDataToolCutSpline (VPE::VProperty * property) private
Definition at line 1398 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolCut::setCurveCutId(), and VToolCut::SetFormula().
Referenced by userChangedData().
changeDataToolCutSplinePath()
void VToolOptionsPropertyBrowser::changeDataToolCutSplinePath (VPE::VProperty * property) private
Definition at line 1425 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolCut::setCurveCutId(), and VToolCut::SetFormula().
Referenced by userChangedData().
changeDataToolEllipticalArc()
void VToolOptionsPropertyBrowser::changeDataToolEllipticalArc (VPE::VProperty * property) private
Definition at line 2309 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolEllipticalArc::setCenter(), VToolEllipticalArc::SetFormulaF1(), VToolEllipticalArc::SetFormulaF2(), VToolEllipticalArc::SetFormulaRadius1(), VToolEllipticalArc::SetFormulaRadius2(), VToolEllipticalArc::SetFormulaRotationAngle(), VAbstractSpline::setLineColor(), VAbstractSpline::setLineWeight(), and VAbstractSpline::SetPenStyle().
Referenced by userChangedData().
changeDataToolEndLine()
void VToolOptionsPropertyBrowser::changeDataToolEndLine (VPE::VProperty * property) private
Definition at line 1127 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLinePoint::SetBasePointId(), VToolEndLine::SetFormulaAngle(), VToolLinePoint::SetFormulaLength(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), and VDrawTool::setLineWeight().
Referenced by userChangedData().
changeDataToolHeight()
void VToolOptionsPropertyBrowser::changeDataToolHeight (VPE::VProperty * property) private
Definition at line 1452 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLinePoint::SetBasePointId(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), VDrawTool::setLineWeight(), VToolHeight::SetP1LineId(), and VToolHeight::SetP2LineId().
Referenced by userChangedData().
changeDataToolLine()
void VToolOptionsPropertyBrowser::changeDataToolLine (VPE::VProperty * property) private
Definition at line 1491 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLine::SetFirstPoint(), VToolLine::setLineColor(), VToolLine::setLineType(), VToolLine::setLineWeight(), and VToolLine::SetSecondPoint().
Referenced by userChangedData().
changeDataToolLineIntersect()
void VToolOptionsPropertyBrowser::changeDataToolLineIntersect (VPE::VProperty * property) private
Definition at line 1524 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLineIntersect::SetP1Line1(), VToolLineIntersect::SetP1Line2(), VToolLineIntersect::SetP2Line1(), and VToolLineIntersect::SetP2Line2().
Referenced by userChangedData().
changeDataToolLineIntersectAxis()
void VToolOptionsPropertyBrowser::changeDataToolLineIntersectAxis (VPE::VProperty * property) private
Definition at line 2111 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLinePoint::SetBasePointId(), VToolLineIntersectAxis::SetFirstPointId(), VToolLineIntersectAxis::SetFormulaAngle(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), VDrawTool::setLineWeight(), and VToolLineIntersectAxis::SetSecondPointId().
Referenced by userChangedData().
changeDataToolMirrorByAxis()
void VToolOptionsPropertyBrowser::changeDataToolMirrorByAxis (VPE::VProperty * property) private
Definition at line 2279 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, and VToolMirrorByAxis::setOriginPointId().
Referenced by userChangedData().
changeDataToolMirrorByLine()
void VToolOptionsPropertyBrowser::changeDataToolMirrorByLine (VPE::VProperty * property) private
Definition at line 2252 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolMirrorByLine::setFirstLinePointId(), and VToolMirrorByLine::setSecondLinePointId().
Referenced by userChangedData().
changeDataToolMove()
void VToolOptionsPropertyBrowser::changeDataToolMove (VPE::VProperty * property) private
Definition at line 2219 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolMove::SetFormulaAngle(), VToolMove::SetFormulaLength(), VToolMove::setFormulaRotation(), and VToolMove::setOriginPointId().
Referenced by userChangedData().
changeDataToolNormal()
void VToolOptionsPropertyBrowser::changeDataToolNormal (VPE::VProperty * property) private
Definition at line 1557 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLinePoint::SetAngle(), VToolLinePoint::SetBasePointId(), VToolLinePoint::SetFormulaLength(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), VDrawTool::setLineWeight(), and VToolNormal::SetSecondPointId().
Referenced by userChangedData().
changeDataToolPointFromArcAndTangent()
void VToolOptionsPropertyBrowser::changeDataToolPointFromArcAndTangent (VPE::VProperty * property) private
Definition at line 1815 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolPointFromArcAndTangent::SetArcId(), and VToolPointFromArcAndTangent::SetTangentPointId().
Referenced by userChangedData().
changeDataToolPointFromCircleAndTangent()
void VToolOptionsPropertyBrowser::changeDataToolPointFromCircleAndTangent (VPE::VProperty * property) private
Definition at line 1779 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, IntersectCircleTangentTool::SetCircleCenterId(), IntersectCircleTangentTool::SetCircleRadius(), and IntersectCircleTangentTool::SetTangentPointId().
Referenced by userChangedData().
changeDataToolPointOfContact()
void VToolOptionsPropertyBrowser::changeDataToolPointOfContact (VPE::VProperty * property) private
Definition at line 1599 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolPointOfContact::setArcRadius(), VToolPointOfContact::setCenter(), VToolPointOfContact::SetFirstPointId(), and VToolPointOfContact::SetSecondPointId().
Referenced by userChangedData().
changeDataToolPointOfIntersection()
void VToolOptionsPropertyBrowser::changeDataToolPointOfIntersection (VPE::VProperty * property) private
Definition at line 1632 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, DoubleLinePointTool::setFirstPointId(), DoubleLinePointTool::setLineColor(), VDrawTool::setLineType(), VDrawTool::setLineWeight(), and DoubleLinePointTool::setSecondPointId().
Referenced by userChangedData().
changeDataToolPointOfIntersectionArcs()
void VToolOptionsPropertyBrowser::changeDataToolPointOfIntersectionArcs (VPE::VProperty * property) private
Definition at line 1668 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolPointOfIntersectionArcs::SetFirstArcId(), and VToolPointOfIntersectionArcs::SetSecondArcId().
Referenced by userChangedData().
changeDataToolPointOfIntersectionCircles()
void VToolOptionsPropertyBrowser::changeDataToolPointOfIntersectionCircles (VPE::VProperty * property) private
Definition at line 1701 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, IntersectCirclesTool::SetFirstCircleCenterId(), IntersectCirclesTool::SetFirstCircleRadius(), IntersectCirclesTool::SetSecondCircleCenterId(), and IntersectCirclesTool::SetSecondCircleRadius().
Referenced by userChangedData().
changeDataToolPointOfIntersectionCurves()
void VToolOptionsPropertyBrowser::changeDataToolPointOfIntersectionCurves (VPE::VProperty * property) private
Definition at line 1740 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolPointOfIntersectionCurves::SetFirstCurveId(), and VToolPointOfIntersectionCurves::SetSecondCurveId().
Referenced by userChangedData().
changeDataToolRotation()
void VToolOptionsPropertyBrowser::changeDataToolRotation (VPE::VProperty * property) private
Definition at line 2192 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolRotation::SetFormulaAngle(), and VToolRotation::setOriginPointId().
Referenced by userChangedData().
changeDataToolShoulderPoint()
void VToolOptionsPropertyBrowser::changeDataToolShoulderPoint (VPE::VProperty * property) private
Definition at line 1848 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolLinePoint::SetBasePointId(), VToolLinePoint::SetFormulaLength(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), VDrawTool::setLineWeight(), VToolShoulderPoint::SetP2Line(), and VToolShoulderPoint::setPShoulder().
Referenced by userChangedData().
changeDataToolSinglePoint()
void VToolOptionsPropertyBrowser::changeDataToolSinglePoint (VPE::VProperty * property) private
Definition at line 1103 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, and VToolBasePoint::SetBasePointPos().
Referenced by userChangedData().
changeDataToolSpline()
void VToolOptionsPropertyBrowser::changeDataToolSpline (VPE::VProperty * property) private
Definition at line 1890 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, VFormula::error(), FromUser, VContainer::GeometricObject(), VFormula::getDoubleValue(), VFormula::GetFormula(), VToolSpline::getSpline(), m_data, propertiesList(), propertyToId, qApp, SCASSERT, VAbstractSpline::setLineColor(), VAbstractSpline::setLineWeight(), VAbstractSpline::SetPenStyle(), VToolSpline::setSpline(), and VFormula::value.
Referenced by userChangedData().
changeDataToolSplinePath()
void VToolOptionsPropertyBrowser::changeDataToolSplinePath (VPE::VProperty * property) private
Definition at line 2018 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VAbstractSpline::setLineColor(), VAbstractSpline::setLineWeight(), and VAbstractSpline::SetPenStyle().
Referenced by userChangedData().
changeDataToolTriangle()
void VToolOptionsPropertyBrowser::changeDataToolTriangle (VPE::VProperty * property) private
Definition at line 2078 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolTriangle::SetAxisP1Id(), VToolTriangle::SetAxisP2Id(), VToolTriangle::SetFirstPointId(), and VToolTriangle::SetSecondPointId().
Referenced by userChangedData().
changeDataToolTrueDarts()
void VToolOptionsPropertyBrowser::changeDataToolTrueDarts (VPE::VProperty * property) private
Definition at line 1332 of file vtooloptionspropertybrowser.cpp.
References currentItem, VPE::VProperty::DPC_Data, propertiesList(), propertyToId, SCASSERT, VToolTrueDarts::SetBaseLineP1Id(), VToolTrueDarts::SetBaseLineP2Id(), VToolTrueDarts::SetDartP1Id(), VToolTrueDarts::SetDartP2Id(), and VToolTrueDarts::SetDartP3Id().
Referenced by userChangedData().
clearPropertyBrowser()
void VToolOptionsPropertyBrowser::clearPropertyBrowser ()
Definition at line 106 of file vtooloptionspropertybrowser.cpp.
References VPE::VPropertyModel::clear(), currentItem, idToProperty, propertyModel, and propertyToId.
Referenced by MainWindow::Clear(), and MainWindow::fullParseFile().
getCrossPoint()
template<class Type > Type VToolOptionsPropertyBrowser::getCrossPoint (const QVariant & value) private
Definition at line 1016 of file vtooloptionspropertybrowser.cpp.
getObjectList()
template<class Tool > QMap< QString, quint32 > VToolOptionsPropertyBrowser::getObjectList (Tool * tool, GOType objType) private
Definition at line 760 of file vtooloptionspropertybrowser.cpp.
References AllCurves, Arc, Calculation, CubicBezier, CubicBezierPath, Curve, VContainer::DataGObjects(), EllipticalArc, VContainer::GetGObject(), VToolRecord::getId(), VToolRecord::getTypeTool(), m_data, NULL_ID, Path, Point, qApp, Spline, SplinePath, VToolMove::Type, and Unknown.
Referenced by addObjectProperty(), updateOptionsToolAlongLine(), updateOptionsToolArc(), updateOptionsToolArcWithLength(), updateOptionsToolBisector(), updateOptionsToolCubicBezier(), updateOptionsToolCurveIntersectAxis(), updateOptionsToolCutArc(), updateOptionsToolCutSpline(), updateOptionsToolCutSplinePath(), updateOptionsToolEllipticalArc(), updateOptionsToolEndLine(), updateOptionsToolHeight(), updateOptionsToolLine(), updateOptionsToolLineIntersect(), updateOptionsToolLineIntersectAxis(), updateOptionsToolMirrorByAxis(), updateOptionsToolMirrorByLine(), updateOptionsToolMove(), updateOptionsToolNormal(), updateOptionsToolPointFromArcAndTangent(), updateOptionsToolPointFromCircleAndTangent(), updateOptionsToolPointOfContact(), updateOptionsToolPointOfIntersection(), updateOptionsToolPointOfIntersectionArcs(), updateOptionsToolPointOfIntersectionCircles(), updateOptionsToolPointOfIntersectionCurves(), updateOptionsToolRotation(), updateOptionsToolShoulderPoint(), updateOptionsToolSpline(), updateOptionsToolTriangle(), and updateOptionsToolTrueDarts().
itemClicked
void VToolOptionsPropertyBrowser::itemClicked (QGraphicsItem * item) slot
Definition at line 503 of file vtooloptionspropertybrowser.cpp.
References VPE::VPropertyModel::clear(), currentItem, formView, idToProperty, propertyModel, propertyToId, showItemOptions(), VAbstractTool::ShowVisualization(), and updateOptions().
Referenced by MainWindow::changeDraftBlock(), MainWindow::Clear(), MainWindow::InitDocksContain(), and refreshOptions().
propertiesList()
QStringList VToolOptionsPropertyBrowser::propertiesList () const private
Definition at line 4071 of file vtooloptionspropertybrowser.cpp.
References AttrAngle, AttrAngle1, AttrAngle2, AttrArc, AttrAxisP1, AttrAxisP2, AttrAxisType, AttrBasePoint, AttrC1Center, AttrC1Radius, AttrC2Center, AttrC2Radius, AttrCCenter, AttrCenter, AttrColor, AttrCRadius, AttrCrossPoint, AttrCurve, AttrCurve1, AttrCurve2, AttrDartP1, AttrDartP2, AttrDartP3, AttrFirstArc, AttrFirstPoint, AttrHCrossPoint, AttrKCurve, AttrLength, AttrLength1, AttrLength2, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrName1, AttrName2, AttrObjName, AttrP1Line, AttrP1Line1, AttrP1Line2, AttrP2Line, AttrP2Line1, AttrP2Line2, AttrPenStyle, AttrPoint1, AttrPoint2, AttrPoint3, AttrPoint4, AttrPShoulder, AttrRadius, AttrRadius1, AttrRadius2, AttrRotationAngle, AttrSecondArc, AttrSecondPoint, VToolCutSpline::AttrSpline, VToolCutSplinePath::AttrSplinePath, AttrSuffix, AttrTangent, AttrThirdPoint, and AttrVCrossPoint.
Referenced by changeDataToolAlongLine(), changeDataToolArc(), changeDataToolArcWithLength(), changeDataToolBisector(), changeDataToolCubicBezier(), changeDataToolCubicBezierPath(), changeDataToolCurveIntersectAxis(), changeDataToolCutArc(), changeDataToolCutSpline(), changeDataToolCutSplinePath(), changeDataToolEllipticalArc(), changeDataToolEndLine(), changeDataToolHeight(), changeDataToolLine(), changeDataToolLineIntersect(), changeDataToolLineIntersectAxis(), changeDataToolMirrorByAxis(), changeDataToolMirrorByLine(), changeDataToolMove(), changeDataToolNormal(), changeDataToolPointFromArcAndTangent(), changeDataToolPointFromCircleAndTangent(), changeDataToolPointOfContact(), changeDataToolPointOfIntersection(), changeDataToolPointOfIntersectionArcs(), changeDataToolPointOfIntersectionCircles(), changeDataToolPointOfIntersectionCurves(), changeDataToolRotation(), changeDataToolShoulderPoint(), changeDataToolSinglePoint(), changeDataToolSpline(), changeDataToolSplinePath(), changeDataToolTriangle(), and changeDataToolTrueDarts().
refreshOptions
void VToolOptionsPropertyBrowser::refreshOptions () slot
Definition at line 361 of file vtooloptionspropertybrowser.cpp.
References currentItem, and itemClicked().
Referenced by MainWindow::CreateMenus(), and MainWindow::Preferences().
setAxisType()
template<class Tool > void VToolOptionsPropertyBrowser::setAxisType (const QVariant & value) private
Definition at line 1082 of file vtooloptionspropertybrowser.cpp.
References currentItem.
setCirclesCrossPoint()
template<class Tool > void VToolOptionsPropertyBrowser::setCirclesCrossPoint (const QVariant & value) private
Definition at line 1040 of file vtooloptionspropertybrowser.cpp.
References currentItem.
setCurveHCrossPoint()
template<class Tool > void VToolOptionsPropertyBrowser::setCurveHCrossPoint (const QVariant & value) private
Definition at line 1068 of file vtooloptionspropertybrowser.cpp.
References currentItem.
setCurveVCrossPoint()
template<class Tool > void VToolOptionsPropertyBrowser::setCurveVCrossPoint (const QVariant & value) private
Definition at line 1054 of file vtooloptionspropertybrowser.cpp.
References currentItem.
setOperationSuffix()
template<class Tool > void VToolOptionsPropertyBrowser::setOperationSuffix (const QString & suffix) private
Definition at line 979 of file vtooloptionspropertybrowser.cpp.
References VContainer::AllUniqueNames(), AttrSuffix, currentItem, idToProperty, VContainer::IsUnique(), and NameRegExp().
setPointName()
template<class Tool > void VToolOptionsPropertyBrowser::setPointName (const QString & name) private
Definition at line 898 of file vtooloptionspropertybrowser.cpp.
References AttrName, currentItem, idToProperty, VContainer::IsUnique(), and NameRegExp().
setPointName1()
template<class Tool > void VToolOptionsPropertyBrowser::setPointName1 (const QString & name) private
Definition at line 925 of file vtooloptionspropertybrowser.cpp.
References AttrName1, currentItem, idToProperty, VContainer::IsUnique(), and NameRegExp().
setPointName2()
template<class Tool > void VToolOptionsPropertyBrowser::setPointName2 (const QString & name) private
Definition at line 952 of file vtooloptionspropertybrowser.cpp.
References AttrName2, currentItem, idToProperty, VContainer::IsUnique(), and NameRegExp().
showItemOptions()
void VToolOptionsPropertyBrowser::showItemOptions (QGraphicsItem * item) private
Definition at line 115 of file vtooloptionspropertybrowser.cpp.
References currentItem, LAST_ONE_DO_NOT_USE, showOptionsToolAlongLine(), showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolBisector(), showOptionsToolCubicBezier(), showOptionsToolCubicBezierPath(), showOptionsToolCurveIntersectAxis(), showOptionsToolCutArc(), showOptionsToolCutSpline(), showOptionsToolCutSplinePath(), showOptionsToolEllipticalArc(), showOptionsToolEndLine(), showOptionsToolHeight(), showOptionsToolLine(), showOptionsToolLineIntersect(), showOptionsToolLineIntersectAxis(), showOptionsToolMirrorByAxis(), showOptionsToolMirrorByLine(), showOptionsToolMove(), showOptionsToolNormal(), showOptionsToolPointFromArcAndTangent(), showOptionsToolPointFromCircleAndTangent(), showOptionsToolPointOfContact(), showOptionsToolPointOfIntersection(), showOptionsToolPointOfIntersectionArcs(), showOptionsToolPointOfIntersectionCircles(), showOptionsToolPointOfIntersectionCurves(), showOptionsToolRotation(), showOptionsToolShoulderPoint(), showOptionsToolSinglePoint(), showOptionsToolSpline(), showOptionsToolSplinePath(), showOptionsToolTriangle(), showOptionsToolTrueDarts(), VToolMirrorByAxis::Type, VToolMirrorByLine::Type, VToolMove::Type, VToolRotation::Type, VToolArc::Type, VToolArcWithLength::Type, VToolCubicBezier::Type, VToolCubicBezierPath::Type, VToolEllipticalArc::Type, VToolSpline::Type, VToolSplinePath::Type, VToolTrueDarts::Type, IntersectCirclesTool::Type, IntersectCircleTangentTool::Type, PointIntersectXYTool::Type, VToolCutArc::Type, VToolCutSpline::Type, VToolCutSplinePath::Type, VToolAlongLine::Type, VToolBisector::Type, VToolCurveIntersectAxis::Type, VToolEndLine::Type, VToolHeight::Type, VToolLineIntersectAxis::Type, VToolNormal::Type, VToolShoulderPoint::Type, VToolBasePoint::Type, VToolLineIntersect::Type, VToolPointFromArcAndTangent::Type, VToolPointOfContact::Type, VToolPointOfIntersectionArcs::Type, VToolPointOfIntersectionCurves::Type, VToolTriangle::Type, VToolLine::Type, VControlPointSpline::Type, VGraphicsSimpleTextItem::Type, VSimpleCurve::Type, and VSimplePoint::Type.
Referenced by itemClicked(), and updateOptions().
showOptionsToolAlongLine()
void VToolOptionsPropertyBrowser::showOptionsToolAlongLine (QGraphicsItem * item) private
Definition at line 2393 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AttrBasePoint, AttrLength, AttrLineColor, AttrName, AttrSecondPoint, VToolLinePoint::BasePointName(), formView, VToolLinePoint::GetFormulaLength(), Point, VToolAlongLine::SecondPointName(), and VToolAlongLine::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolArc()
void VToolOptionsPropertyBrowser::showOptionsToolArc (QGraphicsItem * item) private
Definition at line 2414 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCurveLineType(), addPropertyCurveName(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineWeight(), AttrAngle1, AttrAngle2, AttrCenter, AttrColor, AttrName, AttrRadius, VToolArc::CenterPointName(), formView, VToolArc::GetFormulaF1(), VToolArc::GetFormulaF2(), VToolArc::GetFormulaRadius(), VAbstractTool::getId(), Point, and VToolArc::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolArcWithLength()
void VToolOptionsPropertyBrowser::showOptionsToolArcWithLength (QGraphicsItem * item) private
Definition at line 2436 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCurveLineType(), addPropertyCurveName(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineWeight(), AttrAngle1, AttrCenter, AttrColor, AttrLength, AttrName, AttrRadius, VToolArcWithLength::CenterPointName(), formView, VToolArcWithLength::GetFormulaF1(), VToolArcWithLength::GetFormulaLength(), VToolArcWithLength::GetFormulaRadius(), VAbstractTool::getId(), Point, and VToolArcWithLength::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolBisector()
void VToolOptionsPropertyBrowser::showOptionsToolBisector (QGraphicsItem * item) private
Definition at line 2458 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AttrBasePoint, AttrFirstPoint, AttrLength, AttrLineColor, AttrName, AttrThirdPoint, VToolLinePoint::BasePointName(), VToolBisector::FirstPointName(), formView, VToolLinePoint::GetFormulaLength(), Point, VToolBisector::ShowVisualization(), and VToolBisector::ThirdPointName().
Referenced by showItemOptions().
showOptionsToolCubicBezier()
void VToolOptionsPropertyBrowser::showOptionsToolCubicBezier (QGraphicsItem * item) private
Definition at line 2808 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCurveLineType(), addPropertyCurveName(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineWeight(), AttrColor, AttrName, AttrPoint1, AttrPoint2, AttrPoint3, AttrPoint4, formView, VToolCubicBezier::getSpline(), VAbstractSpline::name(), Point, and VToolCubicBezier::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolCubicBezierPath()
void VToolOptionsPropertyBrowser::showOptionsToolCubicBezierPath (QGraphicsItem * item) private
Definition at line 2846 of file vtooloptionspropertybrowser.cpp.
References addPropertyCurveLineType(), addPropertyCurveName(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineWeight(), AttrColor, AttrName, formView, VToolCubicBezierPath::getSplinePath(), VAbstractSpline::name(), and VToolCubicBezierPath::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolCurveIntersectAxis()
void VToolOptionsPropertyBrowser::showOptionsToolCurveIntersectAxis (QGraphicsItem * item) private
Definition at line 2899 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AllCurves, AttrAngle, AttrBasePoint, AttrCurve, AttrLineColor, AttrName, VToolLinePoint::BasePointName(), VToolCurveIntersectAxis::CurveName(), formView, VToolCurveIntersectAxis::GetFormulaAngle(), Point, and VToolCurveIntersectAxis::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolCutArc()
void VToolOptionsPropertyBrowser::showOptionsToolCutArc (QGraphicsItem * item) private
Definition at line 2497 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyObjectName(), Arc, AttrArc, AttrLength, AttrName, VToolCut::CurveName(), formView, VToolCut::GetFormula(), and VToolCutArc::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolCutSpline()
void VToolOptionsPropertyBrowser::showOptionsToolCutSpline (QGraphicsItem * item) private
Definition at line 2512 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyObjectName(), AttrCurve, AttrLength, AttrName, Curve, VToolCut::CurveName(), formView, VToolCut::GetFormula(), and VToolCutSpline::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolCutSplinePath()
void VToolOptionsPropertyBrowser::showOptionsToolCutSplinePath (QGraphicsItem * item) private
Definition at line 2527 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyObjectName(), AttrCurve, AttrLength, AttrName, VToolCut::CurveName(), formView, VToolCut::GetFormula(), Path, and VToolCutSplinePath::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolEllipticalArc()
void VToolOptionsPropertyBrowser::showOptionsToolEllipticalArc (QGraphicsItem * item) private
Definition at line 2981 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCurveLineType(), addPropertyCurveName(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineWeight(), AttrAngle1, AttrAngle2, AttrCenter, AttrColor, AttrName, AttrRadius1, AttrRadius2, AttrRotationAngle, VToolEllipticalArc::CenterPointName(), formView, VToolEllipticalArc::GetFormulaF1(), VToolEllipticalArc::GetFormulaF2(), VToolEllipticalArc::GetFormulaRadius1(), VToolEllipticalArc::GetFormulaRadius2(), VToolEllipticalArc::GetFormulaRotationAngle(), VAbstractTool::getId(), Point, and VToolEllipticalArc::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolEndLine()
void VToolOptionsPropertyBrowser::showOptionsToolEndLine (QGraphicsItem * item) private
Definition at line 2372 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AttrAngle, AttrBasePoint, AttrLength, AttrLineColor, AttrName, VToolLinePoint::BasePointName(), formView, VToolEndLine::GetFormulaAngle(), VToolLinePoint::GetFormulaLength(), Point, and VToolEndLine::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolHeight()
void VToolOptionsPropertyBrowser::showOptionsToolHeight (QGraphicsItem * item) private
Definition at line 2542 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AttrBasePoint, AttrLineColor, AttrName, AttrP1Line, AttrP2Line, VToolLinePoint::BasePointName(), VToolHeight::FirstLinePointName(), formView, Point, VToolHeight::SecondLinePointName(), and VToolHeight::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolLine()
void VToolOptionsPropertyBrowser::showOptionsToolLine (QGraphicsItem * item) private
Definition at line 2561 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineName(), addPropertyLineType(), addPropertyLineWeight(), AttrFirstPoint, AttrLineColor, AttrName, AttrObjName, AttrSecondPoint, VToolLine::FirstPointName(), formView, Point, VToolLine::SecondPointName(), and VToolLine::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolLineIntersect()
void VToolOptionsPropertyBrowser::showOptionsToolLineIntersect (QGraphicsItem * item) private
Definition at line 2579 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyLabel(), addPropertyObjectName(), AttrName, AttrP1Line1, AttrP1Line2, AttrP2Line1, AttrP2Line2, formView, VToolLineIntersect::Line1P1Name(), VToolLineIntersect::Line1P2Name(), VToolLineIntersect::Line2P1Name(), VToolLineIntersect::Line2P2Name(), Point, and VToolLineIntersect::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolLineIntersectAxis()
void VToolOptionsPropertyBrowser::showOptionsToolLineIntersectAxis (QGraphicsItem * item) private
Definition at line 2877 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AttrAngle, AttrBasePoint, AttrFirstPoint, AttrLineColor, AttrName, AttrSecondPoint, VToolLinePoint::BasePointName(), VToolLineIntersectAxis::FirstLinePoint(), formView, VToolLineIntersectAxis::GetFormulaAngle(), Point, VToolLineIntersectAxis::SecondLinePoint(), and VToolLineIntersectAxis::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolMirrorByAxis()
void VToolOptionsPropertyBrowser::showOptionsToolMirrorByAxis (QGraphicsItem * item) private
Definition at line 2968 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyAxisType(), addPropertyLabel(), addPropertyOperationSuffix(), AttrCenter, AttrName, formView, VToolMirrorByAxis::getOriginPointName(), Point, and VToolMirrorByAxis::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolMirrorByLine()
void VToolOptionsPropertyBrowser::showOptionsToolMirrorByLine (QGraphicsItem * item) private
Definition at line 2953 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyLabel(), addPropertyOperationSuffix(), AttrName, AttrP1Line, AttrP2Line, VToolMirrorByLine::firstLinePointName(), formView, Point, VToolMirrorByLine::secondLinePointName(), and VToolMirrorByLine::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolMove()
void VToolOptionsPropertyBrowser::showOptionsToolMove (QGraphicsItem * item) private
Definition at line 2936 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyOperationSuffix(), AttrAngle, AttrCenter, AttrLength, AttrName, AttrRotationAngle, formView, VToolMove::GetFormulaAngle(), VToolMove::GetFormulaLength(), VToolMove::getFormulaRotation(), VToolMove::getOriginPointName(), Point, and VToolMove::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolNormal()
void VToolOptionsPropertyBrowser::showOptionsToolNormal (QGraphicsItem * item) private
Definition at line 2596 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AttrAngle, AttrBasePoint, AttrLength, AttrLineColor, AttrName, AttrSecondPoint, VToolLinePoint::BasePointName(), formView, VToolLinePoint::GetAngle(), VToolLinePoint::GetFormulaLength(), Point, VToolNormal::SecondPointName(), VPE::DoubleSpinboxProperty::setSetting(), VPE::VProperty::setValue(), and VToolNormal::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolPointFromArcAndTangent()
void VToolOptionsPropertyBrowser::showOptionsToolPointFromArcAndTangent (QGraphicsItem * item) private
Definition at line 2726 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCrossPoint(), addPropertyLabel(), addPropertyObjectName(), Arc, VToolPointFromArcAndTangent::ArcName(), AttrArc, AttrName, AttrTangent, formView, Point, VToolPointFromArcAndTangent::ShowVisualization(), and VToolPointFromArcAndTangent::TangentPointName().
Referenced by showItemOptions().
showOptionsToolPointFromCircleAndTangent()
void VToolOptionsPropertyBrowser::showOptionsToolPointFromCircleAndTangent (QGraphicsItem * item) private
Definition at line 2709 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCrossPoint(), addPropertyFormula(), addPropertyLabel(), addPropertyObjectName(), AttrCCenter, AttrCRadius, AttrName, AttrTangent, IntersectCircleTangentTool::CircleCenterPointName(), formView, IntersectCircleTangentTool::GetCircleRadius(), Point, IntersectCircleTangentTool::ShowVisualization(), and IntersectCircleTangentTool::TangentPointName().
Referenced by showItemOptions().
showOptionsToolPointOfContact()
void VToolOptionsPropertyBrowser::showOptionsToolPointOfContact (QGraphicsItem * item) private
Definition at line 2624 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyObjectName(), VToolPointOfContact::ArcCenterPointName(), AttrCenter, AttrFirstPoint, AttrName, AttrRadius, AttrSecondPoint, VToolPointOfContact::FirstPointName(), formView, VToolPointOfContact::getArcRadius(), Point, VToolPointOfContact::SecondPointName(), and VToolPointOfContact::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolPointOfIntersection()
void VToolOptionsPropertyBrowser::showOptionsToolPointOfIntersection (QGraphicsItem * item) private
Definition at line 2641 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AttrFirstPoint, AttrLineColor, AttrName, AttrSecondPoint, PointIntersectXYTool::firstPointName(), formView, Point, PointIntersectXYTool::secondPointName(), and PointIntersectXYTool::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolPointOfIntersectionArcs()
void VToolOptionsPropertyBrowser::showOptionsToolPointOfIntersectionArcs (QGraphicsItem * item) private
Definition at line 2659 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCrossPoint(), addPropertyLabel(), addPropertyObjectName(), Arc, AttrFirstArc, AttrName, AttrSecondArc, VToolPointOfIntersectionArcs::FirstArcName(), formView, VToolPointOfIntersectionArcs::SecondArcName(), and VToolPointOfIntersectionArcs::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolPointOfIntersectionCircles()
void VToolOptionsPropertyBrowser::showOptionsToolPointOfIntersectionCircles (QGraphicsItem * item) private
Definition at line 2673 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCrossPoint(), addPropertyFormula(), addPropertyLabel(), addPropertyObjectName(), AttrC1Center, AttrC1Radius, AttrC2Center, AttrC2Radius, AttrName, IntersectCirclesTool::FirstCircleCenterPointName(), formView, IntersectCirclesTool::GetFirstCircleRadius(), IntersectCirclesTool::GetSecondCircleRadius(), Point, IntersectCirclesTool::SecondCircleCenterPointName(), and IntersectCirclesTool::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolPointOfIntersectionCurves()
void VToolOptionsPropertyBrowser::showOptionsToolPointOfIntersectionCurves (QGraphicsItem * item) private
Definition at line 2694 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyHCrossPoint(), addPropertyLabel(), addPropertyObjectName(), addPropertyVCrossPoint(), AllCurves, AttrCurve1, AttrCurve2, AttrName, VToolPointOfIntersectionCurves::FirstCurveName(), formView, VToolPointOfIntersectionCurves::SecondCurveName(), and VToolPointOfIntersectionCurves::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolRotation()
void VToolOptionsPropertyBrowser::showOptionsToolRotation (QGraphicsItem * item) private
Definition at line 2921 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyOperationSuffix(), AttrAngle, AttrCenter, AttrName, formView, VToolRotation::GetFormulaAngle(), VToolRotation::getOriginPointName(), Point, and VToolRotation::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolShoulderPoint()
void VToolOptionsPropertyBrowser::showOptionsToolShoulderPoint (QGraphicsItem * item) private
Definition at line 2740 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineType(), addPropertyLineWeight(), addPropertyObjectName(), AttrBasePoint, AttrLength, AttrLineColor, AttrName, AttrSecondPoint, AttrThirdPoint, VToolLinePoint::BasePointName(), formView, VToolLinePoint::GetFormulaLength(), Point, VToolShoulderPoint::SecondPointName(), VToolShoulderPoint::ShoulderPointName(), and VToolShoulderPoint::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolSinglePoint()
void VToolOptionsPropertyBrowser::showOptionsToolSinglePoint (QGraphicsItem * item) private
Definition at line 2357 of file vtooloptionspropertybrowser.cpp.
References addProperty(), addPropertyLabel(), addPropertyObjectName(), AttrName, formView, VToolBasePoint::GetBasePointPos(), VPE::VPointFProperty::setValue(), and VToolBasePoint::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolSpline()
void VToolOptionsPropertyBrowser::showOptionsToolSpline (QGraphicsItem * item) private
Definition at line 2762 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyCurveLineType(), addPropertyCurveName(), addPropertyFormula(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineWeight(), AttrAngle1, AttrAngle2, AttrColor, AttrFirstPoint, AttrLength1, AttrLength2, AttrName, AttrSecondPoint, degreeSymbol, formView, VAbstractTool::getData(), VAbstractTool::getId(), VToolSpline::getSpline(), VAbstractSpline::name(), Point, qApp, VFormula::setCheckZero(), VFormula::setPostfix(), VFormula::setToolId(), VToolSpline::ShowVisualization(), and UnitsToStr().
Referenced by showItemOptions().
showOptionsToolSplinePath()
void VToolOptionsPropertyBrowser::showOptionsToolSplinePath (QGraphicsItem * item) private
Definition at line 2829 of file vtooloptionspropertybrowser.cpp.
References addPropertyCurveLineType(), addPropertyCurveName(), addPropertyLabel(), addPropertyLineColor(), addPropertyLineWeight(), AttrColor, AttrName, formView, VToolSplinePath::getSplinePath(), VAbstractSpline::name(), and VToolSplinePath::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolTriangle()
void VToolOptionsPropertyBrowser::showOptionsToolTriangle (QGraphicsItem * item) private
Definition at line 2862 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyLabel(), addPropertyObjectName(), AttrAxisP1, AttrAxisP2, AttrFirstPoint, AttrName, AttrSecondPoint, VToolTriangle::AxisP1Name(), VToolTriangle::AxisP2Name(), VToolTriangle::FirstPointName(), formView, Point, VToolTriangle::SecondPointName(), and VToolTriangle::ShowVisualization().
Referenced by showItemOptions().
showOptionsToolTrueDarts()
void VToolOptionsPropertyBrowser::showOptionsToolTrueDarts (QGraphicsItem * item) private
Definition at line 2480 of file vtooloptionspropertybrowser.cpp.
References addObjectProperty(), addPropertyLabel(), addPropertyPointName1(), addPropertyPointName2(), AttrDartP1, AttrDartP2, AttrDartP3, AttrFirstPoint, AttrName, AttrSecondPoint, VToolTrueDarts::BaseLineP1Name(), VToolTrueDarts::BaseLineP2Name(), VToolTrueDarts::DartP1Name(), VToolTrueDarts::DartP2Name(), VToolTrueDarts::DartP3Name(), formView, Point, and VToolTrueDarts::ShowVisualization().
Referenced by showItemOptions().
updateOptions
void VToolOptionsPropertyBrowser::updateOptions () slot
Definition at line 237 of file vtooloptionspropertybrowser.cpp.
References currentItem, LAST_ONE_DO_NOT_USE, showItemOptions(), VToolMirrorByAxis::Type, VToolMirrorByLine::Type, VToolMove::Type, VToolRotation::Type, VToolArc::Type, VToolArcWithLength::Type, VToolCubicBezier::Type, VToolCubicBezierPath::Type, VToolEllipticalArc::Type, VToolSpline::Type, VToolSplinePath::Type, VToolTrueDarts::Type, IntersectCirclesTool::Type, IntersectCircleTangentTool::Type, PointIntersectXYTool::Type, VToolCutArc::Type, VToolCutSpline::Type, VToolCutSplinePath::Type, VToolAlongLine::Type, VToolBisector::Type, VToolCurveIntersectAxis::Type, VToolEndLine::Type, VToolHeight::Type, VToolLineIntersectAxis::Type, VToolNormal::Type, VToolShoulderPoint::Type, VToolBasePoint::Type, VToolLineIntersect::Type, VToolPointFromArcAndTangent::Type, VToolPointOfContact::Type, VToolPointOfIntersectionArcs::Type, VToolPointOfIntersectionCurves::Type, VToolTriangle::Type, VToolLine::Type, VControlPointSpline::Type, VGraphicsSimpleTextItem::Type, updateOptionsToolAlongLine(), updateOptionsToolArc(), updateOptionsToolArcWithLength(), updateOptionsToolBisector(), updateOptionsToolCubicBezier(), updateOptionsToolCubicBezierPath(), updateOptionsToolCurveIntersectAxis(), updateOptionsToolCutArc(), updateOptionsToolCutSpline(), updateOptionsToolCutSplinePath(), updateOptionsToolEllipticalArc(), updateOptionsToolEndLine(), updateOptionsToolHeight(), updateOptionsToolLine(), updateOptionsToolLineIntersect(), updateOptionsToolLineIntersectAxis(), updateOptionsToolMirrorByAxis(), updateOptionsToolMirrorByLine(), updateOptionsToolMove(), updateOptionsToolNormal(), updateOptionsToolPointFromArcAndTangent(), updateOptionsToolPointFromCircleAndTangent(), updateOptionsToolPointOfContact(), updateOptionsToolPointOfIntersection(), updateOptionsToolPointOfIntersectionArcs(), updateOptionsToolPointOfIntersectionCircles(), updateOptionsToolPointOfIntersectionCurves(), updateOptionsToolRotation(), updateOptionsToolShoulderPoint(), updateOptionsToolSinglePoint(), updateOptionsToolSpline(), updateOptionsToolSplinePath(), updateOptionsToolTriangle(), and updateOptionsToolTrueDarts().
Referenced by MainWindow::InitDocksContain(), and itemClicked().
updateOptionsToolAlongLine()
void VToolOptionsPropertyBrowser::updateOptionsToolAlongLine () private
Definition at line 3049 of file vtooloptionspropertybrowser.cpp.
References AttrBasePoint, AttrLength, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrSecondPoint, VToolLinePoint::BasePointName(), VAbstractTool::ColorsList(), currentItem, VToolLinePoint::GetFormulaLength(), VToolLinePoint::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), Point, and VToolAlongLine::SecondPointName().
Referenced by updateOptions().
updateOptionsToolArc()
void VToolOptionsPropertyBrowser::updateOptionsToolArc () private
Definition at line 3087 of file vtooloptionspropertybrowser.cpp.
References AttrAngle1, AttrAngle2, AttrCenter, AttrColor, AttrLineWeight, AttrObjName, AttrPenStyle, AttrRadius, VToolArc::CenterPointName(), VAbstractTool::ColorsList(), currentItem, curveLineTypeList(), VToolArc::GetFormulaF1(), VToolArc::GetFormulaF2(), VToolArc::GetFormulaRadius(), VAbstractTool::getId(), VAbstractSpline::getLineColor(), VAbstractSpline::getLineWeight(), getObjectList(), VAbstractSpline::GetPenStyle(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineWeightList(), and Point.
Referenced by updateOptions().
updateOptionsToolArcWithLength()
void VToolOptionsPropertyBrowser::updateOptionsToolArcWithLength () private
Definition at line 3127 of file vtooloptionspropertybrowser.cpp.
References AttrAngle1, AttrCenter, AttrColor, AttrLength, AttrLineWeight, AttrObjName, AttrPenStyle, AttrRadius, VToolArcWithLength::CenterPointName(), VAbstractTool::ColorsList(), currentItem, curveLineTypeList(), VToolArcWithLength::GetFormulaF1(), VToolArcWithLength::GetFormulaLength(), VToolArcWithLength::GetFormulaRadius(), VAbstractTool::getId(), VAbstractSpline::getLineColor(), VAbstractSpline::getLineWeight(), getObjectList(), VAbstractSpline::GetPenStyle(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineWeightList(), and Point.
Referenced by updateOptions().
updateOptionsToolBisector()
void VToolOptionsPropertyBrowser::updateOptionsToolBisector () private
Definition at line 3168 of file vtooloptionspropertybrowser.cpp.
References AttrBasePoint, AttrFirstPoint, AttrLength, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrThirdPoint, VToolLinePoint::BasePointName(), VAbstractTool::ColorsList(), currentItem, VToolBisector::FirstPointName(), VToolLinePoint::GetFormulaLength(), VToolLinePoint::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), Point, and VToolBisector::ThirdPointName().
Referenced by updateOptions().
updateOptionsToolCubicBezier()
void VToolOptionsPropertyBrowser::updateOptionsToolCubicBezier () private
Definition at line 3745 of file vtooloptionspropertybrowser.cpp.
References AttrColor, AttrLineWeight, AttrObjName, AttrPenStyle, AttrPoint1, AttrPoint2, AttrPoint3, AttrPoint4, VAbstractTool::ColorsList(), currentItem, curveLineTypeList(), VAbstractSpline::getLineColor(), VAbstractSpline::getLineWeight(), getObjectList(), VAbstractSpline::GetPenStyle(), VToolCubicBezier::getSpline(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineWeightList(), and Point.
Referenced by updateOptions().
updateOptionsToolCubicBezierPath()
void VToolOptionsPropertyBrowser::updateOptionsToolCubicBezierPath () private
Definition at line 3812 of file vtooloptionspropertybrowser.cpp.
References AttrColor, AttrLineWeight, AttrName, AttrPenStyle, VAbstractTool::ColorsList(), currentItem, curveLineTypeList(), VAbstractSpline::getLineColor(), VAbstractSpline::getLineWeight(), VAbstractSpline::GetPenStyle(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), lineWeightList(), VAbstractSpline::name(), and qApp.
Referenced by updateOptions().
updateOptionsToolCurveIntersectAxis()
void VToolOptionsPropertyBrowser::updateOptionsToolCurveIntersectAxis () private
Definition at line 3909 of file vtooloptionspropertybrowser.cpp.
References AllCurves, AttrAngle, AttrBasePoint, AttrCurve, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, VToolLinePoint::BasePointName(), VAbstractTool::ColorsList(), currentItem, VToolCurveIntersectAxis::CurveName(), VToolCurveIntersectAxis::GetFormulaAngle(), VToolLinePoint::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), and Point.
Referenced by updateOptions().
updateOptionsToolCutArc()
void VToolOptionsPropertyBrowser::updateOptionsToolCutArc () private
Definition at line 3248 of file vtooloptionspropertybrowser.cpp.
References Arc, AttrArc, AttrLength, AttrName, currentItem, VToolCut::CurveName(), VToolCut::GetFormula(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), and VToolSinglePoint::name().
Referenced by updateOptions().
updateOptionsToolCutSpline()
void VToolOptionsPropertyBrowser::updateOptionsToolCutSpline () private
Definition at line 3266 of file vtooloptionspropertybrowser.cpp.
References AttrCurve, AttrLength, AttrName, currentItem, VToolCut::CurveName(), VToolCut::GetFormula(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), and Spline.
Referenced by updateOptions().
updateOptionsToolCutSplinePath()
void VToolOptionsPropertyBrowser::updateOptionsToolCutSplinePath () private
Definition at line 3284 of file vtooloptionspropertybrowser.cpp.
References AttrCurve, AttrLength, AttrName, currentItem, VToolCut::CurveName(), VToolCut::GetFormula(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), and SplinePath.
Referenced by updateOptions().
updateOptionsToolEllipticalArc()
void VToolOptionsPropertyBrowser::updateOptionsToolEllipticalArc () private
Definition at line 4022 of file vtooloptionspropertybrowser.cpp.
References AttrAngle1, AttrAngle2, AttrCenter, AttrColor, AttrLineWeight, AttrObjName, AttrPenStyle, AttrRadius1, AttrRadius2, AttrRotationAngle, VToolEllipticalArc::CenterPointName(), VAbstractTool::ColorsList(), currentItem, curveLineTypeList(), VToolEllipticalArc::GetFormulaF1(), VToolEllipticalArc::GetFormulaF2(), VToolEllipticalArc::GetFormulaRadius1(), VToolEllipticalArc::GetFormulaRadius2(), VToolEllipticalArc::GetFormulaRotationAngle(), VAbstractTool::getId(), VAbstractSpline::getLineColor(), VAbstractSpline::getLineWeight(), getObjectList(), VAbstractSpline::GetPenStyle(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineWeightList(), and Point.
Referenced by updateOptions().
updateOptionsToolEndLine()
void VToolOptionsPropertyBrowser::updateOptionsToolEndLine () private
Definition at line 3013 of file vtooloptionspropertybrowser.cpp.
References AttrAngle, AttrBasePoint, AttrLength, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, VToolLinePoint::BasePointName(), VAbstractTool::ColorsList(), currentItem, VToolEndLine::GetFormulaAngle(), VToolLinePoint::GetFormulaLength(), VToolLinePoint::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), and Point.
Referenced by updateOptions().
updateOptionsToolHeight()
void VToolOptionsPropertyBrowser::updateOptionsToolHeight () private
Definition at line 3302 of file vtooloptionspropertybrowser.cpp.
References AttrBasePoint, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrP1Line, AttrP2Line, VToolLinePoint::BasePointName(), VAbstractTool::ColorsList(), currentItem, VToolHeight::FirstLinePointName(), VToolLinePoint::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), Point, and VToolHeight::SecondLinePointName().
Referenced by updateOptions().
updateOptionsToolLine()
void VToolOptionsPropertyBrowser::updateOptionsToolLine () private
Definition at line 3343 of file vtooloptionspropertybrowser.cpp.
References AttrFirstPoint, AttrLineColor, AttrLineType, AttrLineWeight, AttrObjName, AttrSecondPoint, VAbstractTool::ColorsList(), currentItem, VToolLine::FirstPointName(), VToolLine::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), Point, and VToolLine::SecondPointName().
Referenced by updateOptions().
updateOptionsToolLineIntersect()
void VToolOptionsPropertyBrowser::updateOptionsToolLineIntersect () private
Definition at line 3377 of file vtooloptionspropertybrowser.cpp.
References AttrName, AttrP1Line1, AttrP1Line2, AttrP2Line1, AttrP2Line2, currentItem, getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolLineIntersect::Line1P1Name(), VToolLineIntersect::Line1P2Name(), VToolLineIntersect::Line2P1Name(), VToolLineIntersect::Line2P2Name(), VToolSinglePoint::name(), and Point.
Referenced by updateOptions().
updateOptionsToolLineIntersectAxis()
void VToolOptionsPropertyBrowser::updateOptionsToolLineIntersectAxis () private
Definition at line 3865 of file vtooloptionspropertybrowser.cpp.
References AttrAngle, AttrBasePoint, AttrFirstPoint, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrSecondPoint, VToolLinePoint::BasePointName(), VAbstractTool::ColorsList(), currentItem, VToolLineIntersectAxis::FirstLinePoint(), VToolLineIntersectAxis::GetFormulaAngle(), VToolLinePoint::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), Point, and VToolLineIntersectAxis::SecondLinePoint().
Referenced by updateOptions().
updateOptionsToolMirrorByAxis()
void VToolOptionsPropertyBrowser::updateOptionsToolMirrorByAxis () private
Definition at line 4008 of file vtooloptionspropertybrowser.cpp.
References AttrAxisType, AttrCenter, AttrSuffix, currentItem, VToolMirrorByAxis::getAxisType(), getObjectList(), VToolMirrorByAxis::getOriginPointName(), idToProperty, VPE::VObjectProperty::indexOfObject(), Point, and VAbstractOperation::Suffix().
Referenced by updateOptions().
updateOptionsToolMirrorByLine()
void VToolOptionsPropertyBrowser::updateOptionsToolMirrorByLine () private
Definition at line 3989 of file vtooloptionspropertybrowser.cpp.
References AttrP1Line, AttrP2Line, AttrSuffix, currentItem, VToolMirrorByLine::firstLinePointName(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), Point, VToolMirrorByLine::secondLinePointName(), and VAbstractOperation::Suffix().
Referenced by updateOptions().
updateOptionsToolMove()
void VToolOptionsPropertyBrowser::updateOptionsToolMove () private
Definition at line 3964 of file vtooloptionspropertybrowser.cpp.
References AttrAngle, AttrCenter, AttrLength, AttrRotationAngle, AttrSuffix, currentItem, VToolMove::GetFormulaAngle(), VToolMove::GetFormulaLength(), VToolMove::getFormulaRotation(), getObjectList(), VToolMove::getOriginPointName(), idToProperty, VPE::VObjectProperty::indexOfObject(), Point, and VAbstractOperation::Suffix().
Referenced by updateOptions().
updateOptionsToolNormal()
void VToolOptionsPropertyBrowser::updateOptionsToolNormal () private
Definition at line 3409 of file vtooloptionspropertybrowser.cpp.
References AttrAngle, AttrBasePoint, AttrLength, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrSecondPoint, VToolLinePoint::BasePointName(), VAbstractTool::ColorsList(), currentItem, VToolLinePoint::GetAngle(), VToolLinePoint::GetFormulaLength(), VToolLinePoint::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), Point, and VToolNormal::SecondPointName().
Referenced by updateOptions().
updateOptionsToolPointFromArcAndTangent()
void VToolOptionsPropertyBrowser::updateOptionsToolPointFromArcAndTangent () private
Definition at line 3612 of file vtooloptionspropertybrowser.cpp.
References Arc, VToolPointFromArcAndTangent::ArcName(), AttrArc, AttrCrossPoint, AttrName, AttrTangent, currentItem, VToolPointFromArcAndTangent::GetCrossCirclesPoint(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), Point, and VToolPointFromArcAndTangent::TangentPointName().
Referenced by updateOptions().
updateOptionsToolPointFromCircleAndTangent()
void VToolOptionsPropertyBrowser::updateOptionsToolPointFromCircleAndTangent () private
Definition at line 3587 of file vtooloptionspropertybrowser.cpp.
References AttrCCenter, AttrCRadius, AttrCrossPoint, AttrName, AttrTangent, IntersectCircleTangentTool::CircleCenterPointName(), currentItem, IntersectCircleTangentTool::GetCircleRadius(), IntersectCircleTangentTool::GetCrossCirclesPoint(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), Point, and IntersectCircleTangentTool::TangentPointName().
Referenced by updateOptions().
updateOptionsToolPointOfContact()
void VToolOptionsPropertyBrowser::updateOptionsToolPointOfContact () private
Definition at line 3450 of file vtooloptionspropertybrowser.cpp.
References VToolPointOfContact::ArcCenterPointName(), AttrCenter, AttrFirstPoint, AttrName, AttrRadius, AttrSecondPoint, currentItem, VToolPointOfContact::FirstPointName(), VToolPointOfContact::getArcRadius(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), Point, and VToolPointOfContact::SecondPointName().
Referenced by updateOptions().
updateOptionsToolPointOfIntersection()
void VToolOptionsPropertyBrowser::updateOptionsToolPointOfIntersection () private
Definition at line 3480 of file vtooloptionspropertybrowser.cpp.
References AttrFirstPoint, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrSecondPoint, VAbstractTool::ColorsList(), currentItem, PointIntersectXYTool::firstPointName(), DoubleLinePointTool::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), Point, and PointIntersectXYTool::secondPointName().
Referenced by updateOptions().
updateOptionsToolPointOfIntersectionArcs()
void VToolOptionsPropertyBrowser::updateOptionsToolPointOfIntersectionArcs () private
Definition at line 3515 of file vtooloptionspropertybrowser.cpp.
References Arc, AttrCrossPoint, AttrFirstArc, AttrName, AttrSecondArc, currentItem, VToolPointOfIntersectionArcs::FirstArcName(), VToolPointOfIntersectionArcs::GetCrossCirclesPoint(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), and VToolPointOfIntersectionArcs::SecondArcName().
Referenced by updateOptions().
updateOptionsToolPointOfIntersectionCircles()
void VToolOptionsPropertyBrowser::updateOptionsToolPointOfIntersectionCircles () private
Definition at line 3536 of file vtooloptionspropertybrowser.cpp.
References AttrC1Center, AttrC1Radius, AttrC2Center, AttrC2Radius, AttrCrossPoint, AttrName, currentItem, IntersectCirclesTool::FirstCircleCenterPointName(), IntersectCirclesTool::GetCrossCirclesPoint(), IntersectCirclesTool::GetFirstCircleRadius(), getObjectList(), IntersectCirclesTool::GetSecondCircleRadius(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), Point, and IntersectCirclesTool::SecondCircleCenterPointName().
Referenced by updateOptions().
updateOptionsToolPointOfIntersectionCurves()
void VToolOptionsPropertyBrowser::updateOptionsToolPointOfIntersectionCurves () private
Definition at line 3565 of file vtooloptionspropertybrowser.cpp.
References AttrCurve1, AttrCurve2, AttrHCrossPoint, AttrName, AttrVCrossPoint, currentItem, VToolPointOfIntersectionCurves::FirstCurveName(), VToolPointOfIntersectionCurves::GetHCrossPoint(), getObjectList(), VToolPointOfIntersectionCurves::GetVCrossPoint(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), Point, and VToolPointOfIntersectionCurves::SecondCurveName().
Referenced by updateOptions().
updateOptionsToolRotation()
void VToolOptionsPropertyBrowser::updateOptionsToolRotation () private
Definition at line 3947 of file vtooloptionspropertybrowser.cpp.
References AttrAngle, AttrCenter, AttrSuffix, currentItem, VToolRotation::GetFormulaAngle(), getObjectList(), VToolRotation::getOriginPointName(), idToProperty, VPE::VObjectProperty::indexOfObject(), Point, and VAbstractOperation::Suffix().
Referenced by updateOptions().
updateOptionsToolShoulderPoint()
void VToolOptionsPropertyBrowser::updateOptionsToolShoulderPoint () private
Definition at line 3633 of file vtooloptionspropertybrowser.cpp.
References AttrBasePoint, AttrLength, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrSecondPoint, AttrThirdPoint, VToolLinePoint::BasePointName(), VAbstractTool::ColorsList(), currentItem, VToolLinePoint::GetFormulaLength(), VToolLinePoint::getLineColor(), VDrawTool::getLineType(), VDrawTool::getLineWeight(), getObjectList(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineTypeList(), lineWeightList(), VToolSinglePoint::name(), Point, VToolShoulderPoint::SecondPointName(), and VToolShoulderPoint::ShoulderPointName().
Referenced by updateOptions().
updateOptionsToolSinglePoint()
void VToolOptionsPropertyBrowser::updateOptionsToolSinglePoint () private
Definition at line 3005 of file vtooloptionspropertybrowser.cpp.
References AttrName, currentItem, VToolBasePoint::GetBasePointPos(), idToProperty, and VToolSinglePoint::name().
Referenced by updateOptions().
updateOptionsToolSpline()
void VToolOptionsPropertyBrowser::updateOptionsToolSpline () private
Definition at line 3678 of file vtooloptionspropertybrowser.cpp.
References AttrAngle1, AttrAngle2, AttrColor, AttrFirstPoint, AttrLength1, AttrLength2, AttrLineWeight, AttrObjName, AttrPenStyle, AttrSecondPoint, VAbstractTool::ColorsList(), currentItem, curveLineTypeList(), degreeSymbol, VSpline::GetC1LengthFormula(), VSpline::GetC2LengthFormula(), VAbstractTool::getData(), VSpline::GetEndAngleFormula(), VAbstractTool::getId(), VAbstractSpline::getLineColor(), VAbstractSpline::getLineWeight(), getObjectList(), VSpline::GetP1(), VSpline::GetP4(), VAbstractSpline::GetPenStyle(), VToolSpline::getSpline(), VSpline::GetStartAngleFormula(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), VPE::VObjectProperty::indexOfObject(), lineWeightList(), VGObject::name(), Point, qApp, VFormula::setCheckZero(), VFormula::setPostfix(), VFormula::setToolId(), and UnitsToStr().
Referenced by updateOptions().
updateOptionsToolSplinePath()
void VToolOptionsPropertyBrowser::updateOptionsToolSplinePath () private
Definition at line 3790 of file vtooloptionspropertybrowser.cpp.
References AttrColor, AttrLineWeight, AttrName, AttrPenStyle, VAbstractTool::ColorsList(), currentItem, curveLineTypeList(), VAbstractSpline::getLineColor(), VAbstractSpline::getLineWeight(), VAbstractSpline::GetPenStyle(), idToProperty, VPE::VLineColorProperty::indexOfColor(), VPE::LineTypeProperty::indexOfLineType(), VPE::LineWeightProperty::indexOfLineWeight(), lineWeightList(), VAbstractSpline::name(), and qApp.
Referenced by updateOptions().
updateOptionsToolTriangle()
void VToolOptionsPropertyBrowser::updateOptionsToolTriangle () private
Definition at line 3833 of file vtooloptionspropertybrowser.cpp.
References AttrAxisP1, AttrAxisP2, AttrFirstPoint, AttrName, AttrSecondPoint, VToolTriangle::AxisP1Name(), VToolTriangle::AxisP2Name(), currentItem, VToolTriangle::FirstPointName(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolSinglePoint::name(), Point, and VToolTriangle::SecondPointName().
Referenced by updateOptions().
updateOptionsToolTrueDarts()
void VToolOptionsPropertyBrowser::updateOptionsToolTrueDarts () private
Definition at line 3210 of file vtooloptionspropertybrowser.cpp.
References AttrDartP1, AttrDartP2, AttrDartP3, AttrFirstPoint, AttrName1, AttrName2, AttrSecondPoint, VToolTrueDarts::BaseLineP1Name(), VToolTrueDarts::BaseLineP2Name(), currentItem, VToolTrueDarts::DartP1Name(), VToolTrueDarts::DartP2Name(), VToolTrueDarts::DartP3Name(), getObjectList(), idToProperty, VPE::VObjectProperty::indexOfObject(), VToolDoublePoint::nameP1(), VToolDoublePoint::nameP2(), and Point.
Referenced by updateOptions().
userChangedData
void VToolOptionsPropertyBrowser::userChangedData (VPE::VProperty * property) private slot
Definition at line 369 of file vtooloptionspropertybrowser.cpp.
References changeDataToolAlongLine(), changeDataToolArc(), changeDataToolArcWithLength(), changeDataToolBisector(), changeDataToolCubicBezier(), changeDataToolCubicBezierPath(), changeDataToolCurveIntersectAxis(), changeDataToolCutArc(), changeDataToolCutSpline(), changeDataToolCutSplinePath(), changeDataToolEllipticalArc(), changeDataToolEndLine(), changeDataToolHeight(), changeDataToolLine(), changeDataToolLineIntersect(), changeDataToolLineIntersectAxis(), changeDataToolMirrorByAxis(), changeDataToolMirrorByLine(), changeDataToolMove(), changeDataToolNormal(), changeDataToolPointFromArcAndTangent(), changeDataToolPointFromCircleAndTangent(), changeDataToolPointOfContact(), changeDataToolPointOfIntersection(), changeDataToolPointOfIntersectionArcs(), changeDataToolPointOfIntersectionCircles(), changeDataToolPointOfIntersectionCurves(), changeDataToolRotation(), changeDataToolShoulderPoint(), changeDataToolSinglePoint(), changeDataToolSpline(), changeDataToolSplinePath(), changeDataToolTriangle(), changeDataToolTrueDarts(), currentItem, VPE::VProperty::getParent(), LAST_ONE_DO_NOT_USE, propertyToId, qApp, VToolMirrorByAxis::Type, VToolMirrorByLine::Type, VToolMove::Type, VToolRotation::Type, VToolArc::Type, VToolArcWithLength::Type, VToolCubicBezier::Type, VToolCubicBezierPath::Type, VToolEllipticalArc::Type, VToolSpline::Type, VToolSplinePath::Type, VToolTrueDarts::Type, IntersectCirclesTool::Type, IntersectCircleTangentTool::Type, PointIntersectXYTool::Type, VToolCutArc::Type, VToolCutSpline::Type, VToolCutSplinePath::Type, VToolAlongLine::Type, VToolBisector::Type, VToolCurveIntersectAxis::Type, VToolEndLine::Type, VToolHeight::Type, VToolLineIntersectAxis::Type, VToolNormal::Type, VToolShoulderPoint::Type, VToolBasePoint::Type, VToolLineIntersect::Type, VToolPointFromArcAndTangent::Type, VToolPointOfContact::Type, VToolPointOfIntersectionArcs::Type, VToolPointOfIntersectionCurves::Type, VToolTriangle::Type, and VToolLine::Type.
Referenced by VToolOptionsPropertyBrowser().
Member Data Documentation
currentItem
QGraphicsItem* VToolOptionsPropertyBrowser::currentItem protected
Definition at line 95 of file vtooloptionspropertybrowser.h.
Referenced by changeDataToolAlongLine(), changeDataToolArc(), changeDataToolArcWithLength(), changeDataToolBisector(), changeDataToolCubicBezier(), changeDataToolCubicBezierPath(), changeDataToolCurveIntersectAxis(), changeDataToolCutArc(), changeDataToolCutSpline(), changeDataToolCutSplinePath(), changeDataToolEllipticalArc(), changeDataToolEndLine(), changeDataToolHeight(), changeDataToolLine(), changeDataToolLineIntersect(), changeDataToolLineIntersectAxis(), changeDataToolMirrorByAxis(), changeDataToolMirrorByLine(), changeDataToolMove(), changeDataToolNormal(), changeDataToolPointFromArcAndTangent(), changeDataToolPointFromCircleAndTangent(), changeDataToolPointOfContact(), changeDataToolPointOfIntersection(), changeDataToolPointOfIntersectionArcs(), changeDataToolPointOfIntersectionCircles(), changeDataToolPointOfIntersectionCurves(), changeDataToolRotation(), changeDataToolShoulderPoint(), changeDataToolSinglePoint(), changeDataToolSpline(), changeDataToolSplinePath(), changeDataToolTriangle(), changeDataToolTrueDarts(), clearPropertyBrowser(), itemClicked(), refreshOptions(), setAxisType(), setCirclesCrossPoint(), setCurveHCrossPoint(), setCurveVCrossPoint(), setOperationSuffix(), setPointName(), setPointName1(), setPointName2(), showItemOptions(), updateOptions(), updateOptionsToolAlongLine(), updateOptionsToolArc(), updateOptionsToolArcWithLength(), updateOptionsToolBisector(), updateOptionsToolCubicBezier(), updateOptionsToolCubicBezierPath(), updateOptionsToolCurveIntersectAxis(), updateOptionsToolCutArc(), updateOptionsToolCutSpline(), updateOptionsToolCutSplinePath(), updateOptionsToolEllipticalArc(), updateOptionsToolEndLine(), updateOptionsToolHeight(), updateOptionsToolLine(), updateOptionsToolLineIntersect(), updateOptionsToolLineIntersectAxis(), updateOptionsToolMirrorByAxis(), updateOptionsToolMirrorByLine(), updateOptionsToolMove(), updateOptionsToolNormal(), updateOptionsToolPointFromArcAndTangent(), updateOptionsToolPointFromCircleAndTangent(), updateOptionsToolPointOfContact(), updateOptionsToolPointOfIntersection(), updateOptionsToolPointOfIntersectionArcs(), updateOptionsToolPointOfIntersectionCircles(), updateOptionsToolPointOfIntersectionCurves(), updateOptionsToolRotation(), updateOptionsToolShoulderPoint(), updateOptionsToolSinglePoint(), updateOptionsToolSpline(), updateOptionsToolSplinePath(), updateOptionsToolTriangle(), updateOptionsToolTrueDarts(), and userChangedData().
formView
VPE::VPropertyFormView* VToolOptionsPropertyBrowser::formView protected
Definition at line 93 of file vtooloptionspropertybrowser.h.
Referenced by itemClicked(), showOptionsToolAlongLine(), showOptionsToolArc(), showOptionsToolArcWithLength(), showOptionsToolBisector(), showOptionsToolCubicBezier(), showOptionsToolCubicBezierPath(), showOptionsToolCurveIntersectAxis(), showOptionsToolCutArc(), showOptionsToolCutSpline(), showOptionsToolCutSplinePath(), showOptionsToolEllipticalArc(), showOptionsToolEndLine(), showOptionsToolHeight(), showOptionsToolLine(), showOptionsToolLineIntersect(), showOptionsToolLineIntersectAxis(), showOptionsToolMirrorByAxis(), showOptionsToolMirrorByLine(), showOptionsToolMove(), showOptionsToolNormal(), showOptionsToolPointFromArcAndTangent(), showOptionsToolPointFromCircleAndTangent(), showOptionsToolPointOfContact(), showOptionsToolPointOfIntersection(), showOptionsToolPointOfIntersectionArcs(), showOptionsToolPointOfIntersectionCircles(), showOptionsToolPointOfIntersectionCurves(), showOptionsToolRotation(), showOptionsToolShoulderPoint(), showOptionsToolSinglePoint(), showOptionsToolSpline(), showOptionsToolSplinePath(), showOptionsToolTriangle(), showOptionsToolTrueDarts(), and VToolOptionsPropertyBrowser().
idToProperty
QMap<QString, VPE::VProperty *> VToolOptionsPropertyBrowser::idToProperty protected
Definition at line 97 of file vtooloptionspropertybrowser.h.
Referenced by addProperty(), clearPropertyBrowser(), itemClicked(), setOperationSuffix(), setPointName(), setPointName1(), setPointName2(), updateOptionsToolAlongLine(), updateOptionsToolArc(), updateOptionsToolArcWithLength(), updateOptionsToolBisector(), updateOptionsToolCubicBezier(), updateOptionsToolCubicBezierPath(), updateOptionsToolCurveIntersectAxis(), updateOptionsToolCutArc(), updateOptionsToolCutSpline(), updateOptionsToolCutSplinePath(), updateOptionsToolEllipticalArc(), updateOptionsToolEndLine(), updateOptionsToolHeight(), updateOptionsToolLine(), updateOptionsToolLineIntersect(), updateOptionsToolLineIntersectAxis(), updateOptionsToolMirrorByAxis(), updateOptionsToolMirrorByLine(), updateOptionsToolMove(), updateOptionsToolNormal(), updateOptionsToolPointFromArcAndTangent(), updateOptionsToolPointFromCircleAndTangent(), updateOptionsToolPointOfContact(), updateOptionsToolPointOfIntersection(), updateOptionsToolPointOfIntersectionArcs(), updateOptionsToolPointOfIntersectionCircles(), updateOptionsToolPointOfIntersectionCurves(), updateOptionsToolRotation(), updateOptionsToolShoulderPoint(), updateOptionsToolSinglePoint(), updateOptionsToolSpline(), updateOptionsToolSplinePath(), updateOptionsToolTriangle(), and updateOptionsToolTrueDarts().
m_data
const VContainer* VToolOptionsPropertyBrowser::m_data protected
Definition at line 91 of file vtooloptionspropertybrowser.h.
Referenced by changeDataToolCubicBezier(), changeDataToolSpline(), and getObjectList().
propertyModel
VPE::VPropertyModel* VToolOptionsPropertyBrowser::propertyModel protected
Definition at line 92 of file vtooloptionspropertybrowser.h.
Referenced by addProperty(), clearPropertyBrowser(), itemClicked(), and VToolOptionsPropertyBrowser().
propertyToId
QMap<VPE::VProperty *, QString> VToolOptionsPropertyBrowser::propertyToId protected
Definition at line 96 of file vtooloptionspropertybrowser.h.
Referenced by addProperty(), changeDataToolAlongLine(), changeDataToolArc(), changeDataToolArcWithLength(), changeDataToolBisector(), changeDataToolCubicBezier(), changeDataToolCubicBezierPath(), changeDataToolCurveIntersectAxis(), changeDataToolCutArc(), changeDataToolCutSpline(), changeDataToolCutSplinePath(), changeDataToolEllipticalArc(), changeDataToolEndLine(), changeDataToolHeight(), changeDataToolLine(), changeDataToolLineIntersect(), changeDataToolLineIntersectAxis(), changeDataToolMirrorByAxis(), changeDataToolMirrorByLine(), changeDataToolMove(), changeDataToolNormal(), changeDataToolPointFromArcAndTangent(), changeDataToolPointFromCircleAndTangent(), changeDataToolPointOfContact(), changeDataToolPointOfIntersection(), changeDataToolPointOfIntersectionArcs(), changeDataToolPointOfIntersectionCircles(), changeDataToolPointOfIntersectionCurves(), changeDataToolRotation(), changeDataToolShoulderPoint(), changeDataToolSinglePoint(), changeDataToolSpline(), changeDataToolSplinePath(), changeDataToolTriangle(), changeDataToolTrueDarts(), clearPropertyBrowser(), itemClicked(), and userChangedData().
The documentation for this class was generated from the following files:
src/app/seamly2d/core/vtooloptionspropertybrowser.h
src/app/seamly2d/core/vtooloptionspropertybrowser.cpp