Seamly2D: TST_Misc Class Reference
TST_Misc Class Reference
#include <tst_misc.h>
Public Member Functions
TST_Misc (QObject *parent=nullptr)
Private Slots
void TestRelativeFilePath_data ()
void TestRelativeFilePath ()
void TestAbsoluteFilePath_data ()
void TestAbsoluteFilePath ()
void TestCLocale_data ()
void TestCLocale ()
void TestIssue485 ()
Detailed Description
Definition at line 57 of file tst_misc.h.
Constructor & Destructor Documentation
TST_Misc()
TST_Misc::TST_Misc (QObject * parent = nullptr) explicit
Definition at line 63 of file tst_misc.cpp.
Member Function Documentation
TestAbsoluteFilePath
void TST_Misc::TestAbsoluteFilePath () private slot
Definition at line 204 of file tst_misc.cpp.
References AbsoluteMPath().
TestAbsoluteFilePath_data
void TST_Misc::TestAbsoluteFilePath_data () private slot
Definition at line 116 of file tst_misc.cpp.
TestCLocale
void TST_Misc::TestCLocale () private slot
Definition at line 227 of file tst_misc.cpp.
TestCLocale_data
void TST_Misc::TestCLocale_data () private slot
Definition at line 215 of file tst_misc.cpp.
TestIssue485
void TST_Misc::TestIssue485 () private slot
Definition at line 238 of file tst_misc.cpp.
References VGObject::LineIntersectCircle().
TestRelativeFilePath
void TST_Misc::TestRelativeFilePath () private slot
Definition at line 105 of file tst_misc.cpp.
References RelativeMPath().
TestRelativeFilePath_data
void TST_Misc::TestRelativeFilePath_data () private slot
Definition at line 69 of file tst_misc.cpp.
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_misc.h
src/test/Seamly2DTest/tst_misc.cpp