Seamly2D: VToolRecord Class Reference
VToolRecord Class Reference
The VToolRecord class record about tool in history.
#include <vtoolrecord.h>
Public Member Functions
VToolRecord ()
VToolRecord default constructor.
VToolRecord (const quint32 &id, const Tool &typeTool, const QString &nameDraw)
VToolRecord constructor.
bool operator== (const VToolRecord &record) const
VToolRecord & operator= (const VToolRecord &record)
VToolRecord (const VToolRecord &record)
quint32 getId () const
getId return tool id.
void setId (const quint32 &value)
setId set tool id.
Tool getTypeTool () const
getTypeTool return tool type.
void setTypeTool (const Tool &value)
setTypeTool set tool type.
QString getDraftBlockName () const
getDraftBlockName return pattern peace name.
void setNameDraw (const QString &value)
setNameDraw set pattern peace name.
~VToolRecord () Q_DECL_EQ_DEFAULT
Private Attributes
quint32 id
id tool id.
Tool typeTool
typeTool tool type.
QString nameDraw
nameDraw pattern peace name.
Detailed Description
The VToolRecord class record about tool in history.
Definition at line 63 of file vtoolrecord.h.
Constructor & Destructor Documentation
VToolRecord() [1/3]
VToolRecord::VToolRecord ()
VToolRecord default constructor.
Definition at line 59 of file vtoolrecord.cpp.
References Arrow.
VToolRecord() [2/3]
VToolRecord::VToolRecord (const quint32 & id, const Tool & typeTool, const QString & nameDraw)
VToolRecord constructor.
Parameters
id tool id.
typeTool tool type.
nameDraw pattern peace name.
Definition at line 70 of file vtoolrecord.cpp.
VToolRecord() [3/3]
VToolRecord::VToolRecord (const VToolRecord & record)
Definition at line 89 of file vtoolrecord.cpp.
~VToolRecord()
VToolRecord::~VToolRecord ()
Member Function Documentation
getDraftBlockName()
QString VToolRecord::getDraftBlockName () const inline
getDraftBlockName return pattern peace name.
Returns
pattern peace name.
Definition at line 134 of file vtoolrecord.h.
References nameDraw.
Referenced by VPattern::ActiveDrawBoundingRect(), VAbstractPattern::getBlockHistory(), VAbstractPattern::getGroupObjHistory(), operator=(), and VPattern::setCurrentData().
getId()
quint32 VToolRecord::getId () const inline
getId return tool id.
Returns
id.
Definition at line 94 of file vtoolrecord.h.
References id.
Referenced by VPattern::ActiveDrawBoundingRect(), VAbstractTool::AddRecord(), VAbstractPattern::getGroupObjHistory(), VToolOptionsPropertyBrowser::getObjectList(), operator=(), operator==(), VPattern::setCurrentData(), and VAbstractPattern::SiblingNodeId().
getTypeTool()
Tool VToolRecord::getTypeTool () const inline
getTypeTool return tool type.
Returns
tool type.
Definition at line 114 of file vtoolrecord.h.
References typeTool.
Referenced by VPattern::ActiveDrawBoundingRect(), VAbstractPattern::getGroupObjHistory(), VToolOptionsPropertyBrowser::getObjectList(), operator=(), and VAbstractPattern::SiblingNodeId().
operator=()
VToolRecord & VToolRecord::operator= (const VToolRecord & record)
Definition at line 75 of file vtoolrecord.cpp.
References getDraftBlockName(), getId(), getTypeTool(), nameDraw, and typeTool.
operator==()
bool VToolRecord::operator== (const VToolRecord & record) const inline
Definition at line 150 of file vtoolrecord.h.
References getId().
setId()
void VToolRecord::setId (const quint32 & value) inline
setId set tool id.
Parameters
value id.
Definition at line 104 of file vtoolrecord.h.
setNameDraw()
void VToolRecord::setNameDraw (const QString & value) inline
setNameDraw set pattern peace name.
Parameters
value pattern peace name.
Definition at line 144 of file vtoolrecord.h.
References nameDraw.
setTypeTool()
void VToolRecord::setTypeTool (const Tool & value) inline
setTypeTool set tool type.
Parameters
value tool type.
Definition at line 124 of file vtoolrecord.h.
References typeTool.
Member Data Documentation
id
quint32 VToolRecord::id private
id tool id.
Definition at line 80 of file vtoolrecord.h.
Referenced by getId().
nameDraw
QString VToolRecord::nameDraw private
nameDraw pattern peace name.
Definition at line 86 of file vtoolrecord.h.
Referenced by getDraftBlockName(), operator=(), and setNameDraw().
typeTool
Tool VToolRecord::typeTool private
typeTool tool type.
Definition at line 83 of file vtoolrecord.h.
Referenced by getTypeTool(), operator=(), and setTypeTool().
The documentation for this class was generated from the following files:
src/libs/ifc/xml/vtoolrecord.h
src/libs/ifc/xml/vtoolrecord.cpp