Seamly2D: src/libs/vwidgets/vtextgraphicsitem.cpp File Reference
vtextgraphicsitem.cpp File Reference
#include <QApplication>
#include <QColor>
#include <QFlags>
#include <QFont>
#include <QGraphicsItem>
#include <QGraphicsSceneHoverEvent>
#include <QGraphicsSceneMouseEvent>
#include <QPainter>
#include <QPen>
#include <QPoint>
#include <QStyleOptionGraphicsItem>
#include <Qt>
#include <QDebug>
#include "../vmisc/def.h"
#include "../vmisc/vmath.h"
#include "../vmisc/vcommonsettings.h"
#include "../vmisc/vabstractapplication.h"
#include "vtextgraphicsitem.h"
Namespaces
anonymous_namespace{vtextgraphicsitem.cpp}
Macros
#define ROTATE_RECT 60
#define ROTATE_ARC 50
#define ACTIVE_Z 10
Functions
QRectF anonymous_namespace{vtextgraphicsitem.cpp}::GetBoundingRect (QRectF rectBB, qreal rotation)
GetBoundingRect calculates the bounding box around rectBB rectangle, rotated around its center by rotation degrees.
Variables
const qreal resizeSquare = (3. / 25.4) * PrintDPI
const qreal rotateCircle = (2. / 25.4) * PrintDPI
const qreal minW = (4. / 25.4) * PrintDPI + resizeSquare
const qreal minH = (4. / 25.4) * PrintDPI + resizeSquare
Macro Definition Documentation
ACTIVE_Z
#define ACTIVE_Z 10
Definition at line 55 of file vtextgraphicsitem.cpp.
ROTATE_ARC
#define ROTATE_ARC 50
Definition at line 52 of file vtextgraphicsitem.cpp.
ROTATE_RECT
#define ROTATE_RECT 60
Definition at line 51 of file vtextgraphicsitem.cpp.
Variable Documentation
minH
const qreal minH = (4. / 25.4) * PrintDPI + resizeSquare
Definition at line 54 of file vtextgraphicsitem.cpp.
Referenced by VTextGraphicsItem::paint(), VTextGraphicsItem::setSize(), and VTextGraphicsItem::VTextGraphicsItem().
minW
const qreal minW = (4. / 25.4) * PrintDPI + resizeSquare
Definition at line 53 of file vtextgraphicsitem.cpp.
Referenced by VTextGraphicsItem::paint(), VTextGraphicsItem::setSize(), and VTextGraphicsItem::VTextGraphicsItem().
resizeSquare
const qreal resizeSquare = (3. / 25.4) * PrintDPI
Definition at line 49 of file vtextgraphicsitem.cpp.
Referenced by VTextGraphicsItem::setSize().
rotateCircle
const qreal rotateCircle = (2. / 25.4) * PrintDPI
Definition at line 50 of file vtextgraphicsitem.cpp.
Referenced by VTextGraphicsItem::paint().