Seamly2D: AbstractMConverter Class Reference
AbstractMConverter Class Reference
#include <abstract_m_converter.h>
Public Member Functions
AbstractMConverter (const QString &fileName)
virtual ~AbstractMConverter () Q_DECL_EQ_DEFAULT
Public Member Functions inherited from VAbstractConverter
VAbstractConverter (const QString &fileName)
virtual ~VAbstractConverter () Q_DECL_EQ_DEFAULT
QString Convert ()
int GetCurrentFormatVarsion () const
QString GetVersionStr () const
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit measurementUnits () const
virtual void setXMLContent (const QString &fileName)
virtual bool SaveDocument (const QString &fileName, QString &error)
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Protected Member Functions
void AddRootComment ()
Protected Member Functions inherited from VAbstractConverter
void ValidateInputFile (const QString &currentSchema) const
Q_NORETURN void InvalidVersion (int ver) const
void Save ()
void setVersion (const QString &version)
virtual int minVer () const =0
virtual int maxVer () const =0
virtual QString minVerStr () const =0
virtual QString maxVerStr () const =0
virtual QString getSchema (int ver) const =0
virtual void applyPatches ()=0
virtual void downgradeToCurrentMaxVersion ()=0
virtual bool isReadOnly () const =0
void Replace (QString &formula, const QString &newName, int position, const QString &token, int &bias) const
void CorrectionsPositions (int position, int bias, QMap< int, QString > &tokens) const
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Static Protected Member Functions
static QMultiMap< QString, QString > OldNamesToNewNames_InV0_3_0 ()
static QMap< QString, QString > OldNamesToNewNames_InV0_3_3 ()
Static Protected Member Functions inherited from VAbstractConverter
static void BiasTokens (int position, int bias, QMap< int, QString > &tokens)
Additional Inherited Members
Static Public Member Functions inherited from VAbstractConverter
static int GetVersion (const QString &version)
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Protected Attributes inherited from VAbstractConverter
int m_ver
QString m_convertedFileName
Detailed Description
Definition at line 67 of file abstract_m_converter.h.
Constructor & Destructor Documentation
AbstractMConverter()
AbstractMConverter::AbstractMConverter (const QString & fileName) explicit
Definition at line 66 of file abstract_m_converter.cpp.
~AbstractMConverter()
virtual AbstractMConverter::~AbstractMConverter () virtual
Member Function Documentation
AddRootComment()
void AbstractMConverter::AddRootComment () protected
Definition at line 72 of file abstract_m_converter.cpp.
Referenced by IndividualSizeConverter::convertToVer0_3_0(), and MultiSizeConverter::convertToVer0_4_0().
OldNamesToNewNames_InV0_3_0()
QMultiMap< QString, QString > AbstractMConverter::OldNamesToNewNames_InV0_3_0 () static protected
Definition at line 82 of file abstract_m_converter.cpp.
Referenced by IndividualSizeConverter::convertMeasurementsToV0_3_0(), and MultiSizeConverter::convertMeasurementsToV0_4_0().
OldNamesToNewNames_InV0_3_3()
QMap< QString, QString > AbstractMConverter::OldNamesToNewNames_InV0_3_3 () static protected
Definition at line 269 of file abstract_m_converter.cpp.
Referenced by IndividualSizeConverter::convertMeasurementsToV0_3_3(), and MultiSizeConverter::convertMeasurementsToV0_4_2().
The documentation for this class was generated from the following files:
src/libs/ifc/xml/abstract_m_converter.h
src/libs/ifc/xml/abstract_m_converter.cpp