Seamly2D: PageFormatCombobox Class Reference
PageFormatCombobox Class Reference
#include <page_format_combobox.h>
Signals
void pageFormatChanged (const PaperSizeFormat &format)
Public Member Functions
PageFormatCombobox (QWidget *parent=nullptr, const char *name=nullptr)
virtual ~PageFormatCombobox ()
void init ()
PaperSizeFormat getPageFormat () const
void setPageFormat (PaperSizeFormat &format)
Static Public Member Functions
static QString MakeHelpTemplateList ()
Private Slots
void updatePageFormat (int index)
Static Private Member Functions
static QVector< std::pair< QString, PaperSizeFormat > > initFormats ()
static QString getFormatName (PaperSizeFormat format)
Private Attributes
PaperSizeFormat m_currentFormat
Detailed Description
A comboBox for choosing an export format type.
Definition at line 37 of file page_format_combobox.h.
Constructor & Destructor Documentation
PageFormatCombobox()
PageFormatCombobox::PageFormatCombobox (QWidget * parent = nullptr, const char * name = nullptr)
Constructor with name.
Definition at line 36 of file page_format_combobox.cpp.
References init().
~PageFormatCombobox()
PageFormatCombobox::~PageFormatCombobox () virtual
Destructor
Definition at line 48 of file page_format_combobox.cpp.
Member Function Documentation
getFormatName()
QString PageFormatCombobox::getFormatName (PaperSizeFormat format) static private
Definition at line 139 of file page_format_combobox.cpp.
References A0, A1, A2, A3, A4, AnsiC, AnsiD, AnsiE, Custom, Legal, Letter, Roll24in, Roll30in, Roll36in, Roll42in, Roll44in, and Tabloid.
Referenced by initFormats().
getPageFormat()
PaperSizeFormat PageFormatCombobox::getPageFormat () const
Definition at line 88 of file page_format_combobox.cpp.
References m_currentFormat.
init()
void PageFormatCombobox::init ()
Initialisation called from constructor or manually but only once.
Definition at line 53 of file page_format_combobox.cpp.
References A0, A1, A2, A3, A4, AnsiC, AnsiD, AnsiE, Custom, Legal, Letter, Roll24in, Roll30in, Roll36in, Roll42in, Roll44in, Tabloid, and updatePageFormat().
Referenced by PageFormatCombobox().
initFormats()
QVector< std::pair< QString, PaperSizeFormat > > PageFormatCombobox::initFormats () static private
Definition at line 109 of file page_format_combobox.cpp.
References A0, A1, A2, A3, A4, AnsiC, AnsiD, AnsiE, Custom, getFormatName(), Legal, Letter, Roll24in, Roll30in, Roll36in, Roll42in, Roll44in, and Tabloid.
Referenced by MakeHelpTemplateList().
MakeHelpTemplateList()
QString PageFormatCombobox::MakeHelpTemplateList () static
Definition at line 183 of file page_format_combobox.cpp.
References A0, initFormats(), and Roll44in.
Referenced by VCommandLine::InitOptions().
pageFormatChanged
void PageFormatCombobox::pageFormatChanged (const PaperSizeFormat & format) signal
Referenced by updatePageFormat().
setPageFormat()
void PageFormatCombobox::setPageFormat (PaperSizeFormat & format)
Sets the currently selected format item to the given format.
Definition at line 96 of file page_format_combobox.cpp.
References m_currentFormat, and updatePageFormat().
updatePageFormat
void PageFormatCombobox::updatePageFormat (int index) private slot
Called when the width has changed. This method sets the current width to the value chosen or even offers a dialog to the user that allows him/ her to choose an individual width.
Definition at line 203 of file page_format_combobox.cpp.
References m_currentFormat, and pageFormatChanged().
Referenced by init(), and setPageFormat().
Member Data Documentation
m_currentFormat
PaperSizeFormat PageFormatCombobox::m_currentFormat private
Definition at line 59 of file page_format_combobox.h.
Referenced by getPageFormat(), setPageFormat(), and updatePageFormat().
The documentation for this class was generated from the following files:
src/libs/vwidgets/page_format_combobox.h
src/libs/vwidgets/page_format_combobox.cpp