Seamly2D: PreferencesPatternPage Class Reference
PreferencesPatternPage Class Reference
#include <preferencespatternpage.h>
Public Member Functions
PreferencesPatternPage (QWidget *parent=nullptr)
virtual ~PreferencesPatternPage ()
void Apply ()
void initDefaultSeamAllowance ()
Private Slots
void editDateTimeFormats ()
void setDefaultTemplate ()
Private Member Functions
void initializeLabelsTab ()
void initNotches ()
void initGrainlines ()
void initComboBoxFormats (QComboBox *box, const QStringList &items, const QString &currentFormat)
template<typename T >
void callDateTimeFormatEditor (const T &type, const QStringList &predefinedFormats, const QStringList &userDefinedFormats, QComboBox *box)
Private Attributes
Ui::PreferencesPatternPage * ui
Detailed Description
Definition at line 64 of file preferencespatternpage.h.
Constructor & Destructor Documentation
PreferencesPatternPage()
PreferencesPatternPage::PreferencesPatternPage (QWidget * parent = nullptr) explicit
Definition at line 82 of file preferencespatternpage.cpp.
References initDefaultSeamAllowance(), initGrainlines(), initializeLabelsTab(), initNotches(), and ui.
~PreferencesPatternPage()
PreferencesPatternPage::~PreferencesPatternPage () virtual
Definition at line 96 of file preferencespatternpage.cpp.
References ui.
Member Function Documentation
Apply()
void PreferencesPatternPage::Apply ()
Definition at line 102 of file preferencespatternpage.cpp.
References anonymous_namespace{preferencespatternpage.cpp}::initAllStringsComboBox(), qApp, VCommonSettings::setDefaultCutColor(), VCommonSettings::setDefaultCutLinetype(), VCommonSettings::setDefaultCutLineweight(), VCommonSettings::setDefaultCutoutColor(), VCommonSettings::setDefaultCutoutLinetype(), VCommonSettings::setDefaultCutoutLineweight(), VCommonSettings::setDefaultGrainlineColor(), VCommonSettings::setDefaultGrainlineLength(), VCommonSettings::setDefaultGrainlineLineweight(), VCommonSettings::setDefaultGrainlineVisibilty(), VCommonSettings::setDefaultInternalColor(), VCommonSettings::setDefaultInternalLinetype(), VCommonSettings::setDefaultInternalLineweight(), VCommonSettings::setDefaultLabelColor(), VCommonSettings::setDefaultLabelHeight(), VCommonSettings::setDefaultLabelWidth(), VCommonSettings::setDefaultNotchColor(), VCommonSettings::setDefaultNotchLength(), VCommonSettings::setDefaultNotchType(), VCommonSettings::setDefaultNotchWidth(), VCommonSettings::SetDefaultSeamAllowance(), VCommonSettings::setDefaultSeamAllowanceVisibilty(), VCommonSettings::setDefaultSeamColor(), VCommonSettings::setDefaultSeamLinetype(), VCommonSettings::setDefaultSeamLineweight(), VCommonSettings::setForbidPieceFlipping(), VCommonSettings::setHideSeamLine(), VCommonSettings::SetLabelDateFormat(), VCommonSettings::SetLabelTimeFormat(), VCommonSettings::setShowPatternLabels(), VCommonSettings::setShowPieceLabels(), VCommonSettings::setShowSeamAllowanceNotch(), VCommonSettings::setShowSeamlineNotch(), VCommonSettings::SetUserDefinedDateFormats(), VCommonSettings::SetUserDefinedTimeFormats(), and ui.
Referenced by DialogPreferences::Apply().
callDateTimeFormatEditor()
template<typename T > void PreferencesPatternPage::callDateTimeFormatEditor (const T & type, const QStringList & predefinedFormats, const QStringList & userDefinedFormats, QComboBox * box) private
Definition at line 372 of file preferencespatternpage.cpp.
References DialogDateTimeFormats::GetFormats(), and SCASSERT.
Referenced by editDateTimeFormats().
editDateTimeFormats
void PreferencesPatternPage::editDateTimeFormats () private slot
Definition at line 227 of file preferencespatternpage.cpp.
References callDateTimeFormatEditor(), VCommonSettings::GetUserDefinedDateFormats(), VCommonSettings::GetUserDefinedTimeFormats(), VCommonSettings::PredefinedDateFormats(), VCommonSettings::PredefinedTimeFormats(), qApp, and ui.
Referenced by initializeLabelsTab().
initComboBoxFormats()
void PreferencesPatternPage::initComboBoxFormats (QComboBox * box, const QStringList & items, const QString & currentFormat) private
Definition at line 354 of file preferencespatternpage.cpp.
References SCASSERT.
Referenced by initializeLabelsTab().
initDefaultSeamAllowance()
void PreferencesPatternPage::initDefaultSeamAllowance ()
Definition at line 152 of file preferencespatternpage.cpp.
References qApp, StrToUnits(), ui, and UnitsToStr().
Referenced by DialogPreferences::Apply(), and PreferencesPatternPage().
initGrainlines()
void PreferencesPatternPage::initGrainlines () private
Definition at line 335 of file preferencespatternpage.cpp.
References qApp, StrToUnits(), ui, and UnitsToStr().
Referenced by PreferencesPatternPage().
initializeLabelsTab()
void PreferencesPatternPage::initializeLabelsTab () private
Definition at line 269 of file preferencespatternpage.cpp.
References editDateTimeFormats(), VCommonSettings::getDefaultPatternTemplate(), VCommonSettings::getDefaultPieceTemplate(), VCommonSettings::GetLabelDateFormat(), VCommonSettings::GetLabelTimeFormat(), VCommonSettings::GetUserDefinedDateFormats(), VCommonSettings::GetUserDefinedTimeFormats(), initComboBoxFormats(), VCommonSettings::PredefinedDateFormats(), VCommonSettings::PredefinedTimeFormats(), qApp, setDefaultTemplate(), StrToUnits(), ui, and UnitsToStr().
Referenced by PreferencesPatternPage().
initNotches()
void PreferencesPatternPage::initNotches () private
Definition at line 304 of file preferencespatternpage.cpp.
References qApp, StrToUnits(), ui, and UnitsToStr().
Referenced by PreferencesPatternPage().
setDefaultTemplate
void PreferencesPatternPage::setDefaultTemplate () private slot
Definition at line 245 of file preferencespatternpage.cpp.
References VCommonSettings::GetPathLabelTemplate(), qApp, VCommonSettings::setDefaultPatternTemplate(), VCommonSettings::setDefaultPieceTemplate(), and ui.
Referenced by initializeLabelsTab().
Member Data Documentation
ui
Ui::PreferencesPatternPage* PreferencesPatternPage::ui private
Definition at line 81 of file preferencespatternpage.h.
Referenced by Apply(), editDateTimeFormats(), initDefaultSeamAllowance(), initGrainlines(), initializeLabelsTab(), initNotches(), PreferencesPatternPage(), setDefaultTemplate(), and ~PreferencesPatternPage().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/configpages/preferencespatternpage.h
src/app/seamly2d/dialogs/configpages/preferencespatternpage.cpp