Seamly2D: TST_VPoster Class Reference
TST_VPoster Class Reference
#include <tst_vposter.h>
Public Member Functions
TST_VPoster (QObject *parent=nullptr)
Private Slots
void BigPoster ()
void SmallPoster ()
Private Member Functions
qreal ToPixel (qreal val) const
QRect PageRect (const QPrinter &printer) const
Detailed Description
Definition at line 59 of file tst_vposter.h.
Constructor & Destructor Documentation
TST_VPoster()
TST_VPoster::TST_VPoster (QObject * parent = nullptr) explicit
Definition at line 61 of file tst_vposter.cpp.
Member Function Documentation
BigPoster
void TST_VPoster::BigPoster () private slot
Definition at line 68 of file tst_vposter.cpp.
References VPoster::Calc(), PageRect(), and Portrait.
PageRect()
QRect TST_VPoster::PageRect (const QPrinter & printer) const private
Definition at line 111 of file tst_vposter.cpp.
References ToPixel().
Referenced by BigPoster(), and SmallPoster().
SmallPoster
void TST_VPoster::SmallPoster () private slot
Definition at line 95 of file tst_vposter.cpp.
References VPoster::Calc(), PageRect(), and Portrait.
ToPixel()
qreal TST_VPoster::ToPixel (qreal val) const private
Definition at line 123 of file tst_vposter.cpp.
References PrintDPI.
Referenced by PageRect().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vposter.h
src/test/Seamly2DTest/tst_vposter.cpp