Seamly2D: PiecesWidget Class Reference
PiecesWidget Class Reference
#include <pieces_widget.h>
Public Slots
void togglePiece (quint32 id)
void updateList ()
void selectPiece (quint32 id)
Signals
void Highlight (quint32 id)
Public Member Functions
PiecesWidget (VContainer *data, VAbstractPattern *doc, QWidget *parent=nullptr)
virtual ~PiecesWidget ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
Private Slots
void cellClicked (int row, int column)
void cellDoubleClicked (int row, int column)
void showContextMenu (const QPoint &pos)
Private Member Functions
void fillTable (const QHash< quint32, VPiece > *details)
void toggleInLayoutPieces (bool inLayout)
void toggleLockedPieces (bool lock)
void headerClicked (int index)
headerClicked Sort state whenever header section clicked.
QString formatLetterString (const VPiece piece)
formatLetterString makes name to include piece letter and piece name
void includeAllPieces ()
void invertIncludedPieces ()
void excludeAllPieces ()
void lockAllPieces ()
void invertLockedPieces ()
void unlockAllPieces ()
void editPieceColor (quint32 id)
void editPieceProperties (quint32 id)
Private Attributes
Ui::PiecesWidget * ui
VAbstractPattern * m_doc
VContainer * m_data
const QHash< quint32, VPiece > * m_allPieces
Detailed Description
Definition at line 68 of file pieces_widget.h.
Constructor & Destructor Documentation
PiecesWidget()
PiecesWidget::PiecesWidget (VContainer * data, VAbstractPattern * doc, QWidget * parent = nullptr) explicit
Definition at line 79 of file pieces_widget.cpp.
References VContainer::DataPieces(), editPieceColor(), excludeAllPieces(), fillTable(), Highlight(), includeAllPieces(), lockAllPieces(), m_data, ui, and unlockAllPieces().
~PiecesWidget()
PiecesWidget::~PiecesWidget () virtual
Definition at line 168 of file pieces_widget.cpp.
References ui.
Member Function Documentation
cellClicked
void PiecesWidget::cellClicked (int row, int column) private slot
Definition at line 263 of file pieces_widget.cpp.
References VContainer::DataPieces(), Highlight(), m_data, m_doc, VMainGraphicsScene::pieceLockedChanged(), qApp, SCASSERT, togglePiece(), TogglePieceInLayout, TogglePieceLock, ui, TogglePieceLock::updateList(), and TogglePieceInLayout::updateList().
cellDoubleClicked
void PiecesWidget::cellDoubleClicked (int row, int column) private slot
Definition at line 316 of file pieces_widget.cpp.
References VContainer::DataPieces(), editPieceColor(), editPieceProperties(), Highlight(), m_data, and ui.
changeEvent()
void PiecesWidget::changeEvent (QEvent * event) protected virtual
Definition at line 174 of file pieces_widget.cpp.
References ui.
editPieceColor()
void PiecesWidget::editPieceColor (quint32 id) private
Definition at line 695 of file pieces_widget.cpp.
References Highlight(), m_data, m_doc, qApp, SetPieceColor, togglePiece(), and SetPieceColor::updateList().
Referenced by cellDoubleClicked(), and PiecesWidget().
editPieceProperties()
void PiecesWidget::editPieceProperties (quint32 id) private
Definition at line 707 of file pieces_widget.cpp.
References PatternPieceTool::editPieceProperties(), VAbstractPattern::getTool(), and SCASSERT.
Referenced by cellDoubleClicked().
excludeAllPieces()
void PiecesWidget::excludeAllPieces () private
Definition at line 645 of file pieces_widget.cpp.
References qApp, and toggleInLayoutPieces().
Referenced by PiecesWidget(), and showContextMenu().
fillTable()
void PiecesWidget::fillTable (const QHash< quint32, VPiece > * details) private
Definition at line 346 of file pieces_widget.cpp.
References formatLetterString(), VAbstractPiece::getColor(), VAbstractPiece::GetName(), VPiece::isInLayout(), VPiece::isLocked(), m_data, makeHeaderName(), and ui.
Referenced by PiecesWidget(), and updateList().
formatLetterString()
QString PiecesWidget::formatLetterString (const VPiece piece) private
formatLetterString makes name to include piece letter and piece name
Parameters
piece pattern piece
Definition at line 504 of file pieces_widget.cpp.
References BASE_10, VPieceLabelData::GetLetter(), VPiece::GetPatternPieceData(), and MAX_LENGTH.
Referenced by fillTable(), and togglePiece().
headerClicked()
void PiecesWidget::headerClicked (int index) private
headerClicked Sort state whenever header section clicked.
Parameters
index
Definition at line 494 of file pieces_widget.cpp.
Highlight
void PiecesWidget::Highlight (quint32 id) signal
Referenced by cellClicked(), cellDoubleClicked(), editPieceColor(), MainWindow::InitDocksContain(), and PiecesWidget().
includeAllPieces()
void PiecesWidget::includeAllPieces () private
Definition at line 613 of file pieces_widget.cpp.
References qApp, and toggleInLayoutPieces().
Referenced by PiecesWidget(), and showContextMenu().
invertIncludedPieces()
void PiecesWidget::invertIncludedPieces () private
Definition at line 620 of file pieces_widget.cpp.
References m_allPieces, m_data, m_doc, qApp, togglePiece(), TogglePieceInLayout, ui, and TogglePieceInLayout::updateList().
Referenced by showContextMenu().
invertLockedPieces()
void PiecesWidget::invertLockedPieces () private
Definition at line 659 of file pieces_widget.cpp.
References m_allPieces, m_data, m_doc, VMainGraphicsScene::pieceLockedChanged(), qApp, SCASSERT, togglePiece(), TogglePieceLock, ui, and TogglePieceLock::updateList().
Referenced by showContextMenu().
lockAllPieces()
void PiecesWidget::lockAllPieces () private
Definition at line 652 of file pieces_widget.cpp.
References qApp, and toggleLockedPieces().
Referenced by PiecesWidget(), and showContextMenu().
selectPiece
void PiecesWidget::selectPiece (quint32 id) slot
Definition at line 247 of file pieces_widget.cpp.
References ui.
Referenced by MainWindow::InitDocksContain().
showContextMenu
void PiecesWidget::showContextMenu (const QPoint & pos) private slot
Definition at line 521 of file pieces_widget.cpp.
References VContainer::DataPieces(), excludeAllPieces(), includeAllPieces(), invertIncludedPieces(), invertLockedPieces(), lockAllPieces(), m_allPieces, m_data, ui, and unlockAllPieces().
toggleInLayoutPieces()
void PiecesWidget::toggleInLayoutPieces (bool inLayout) private
Definition at line 435 of file pieces_widget.cpp.
References VContainer::DataPieces(), m_data, m_doc, qApp, togglePiece(), TogglePieceInLayout, ui, and TogglePieceInLayout::updateList().
Referenced by excludeAllPieces(), and includeAllPieces().
toggleLockedPieces()
void PiecesWidget::toggleLockedPieces (bool lock) private
Definition at line 460 of file pieces_widget.cpp.
References VContainer::DataPieces(), m_data, m_doc, VMainGraphicsScene::pieceLockedChanged(), qApp, SCASSERT, togglePiece(), TogglePieceLock, ui, and TogglePieceLock::updateList().
Referenced by lockAllPieces(), and unlockAllPieces().
togglePiece
void PiecesWidget::togglePiece (quint32 id) slot
Definition at line 185 of file pieces_widget.cpp.
References VContainer::DataPieces(), formatLetterString(), VAbstractPiece::getColor(), VAbstractPiece::GetName(), VPiece::isInLayout(), VPiece::isLocked(), m_data, SCASSERT, and ui.
Referenced by cellClicked(), editPieceColor(), MainWindow::InitDocksContain(), invertIncludedPieces(), invertLockedPieces(), toggleInLayoutPieces(), and toggleLockedPieces().
unlockAllPieces()
void PiecesWidget::unlockAllPieces () private
Definition at line 688 of file pieces_widget.cpp.
References qApp, and toggleLockedPieces().
Referenced by PiecesWidget(), and showContextMenu().
updateList
void PiecesWidget::updateList () slot
Definition at line 240 of file pieces_widget.cpp.
References VContainer::DataPieces(), fillTable(), and m_data.
Referenced by MainWindow::fullParseFile(), MainWindow::InitDocksContain(), and MainWindow::showPieceMode().
Member Data Documentation
m_allPieces
const QHash<quint32, VPiece>* PiecesWidget::m_allPieces private
Definition at line 97 of file pieces_widget.h.
Referenced by invertIncludedPieces(), invertLockedPieces(), and showContextMenu().
m_data
VContainer* PiecesWidget::m_data private
Definition at line 96 of file pieces_widget.h.
Referenced by cellClicked(), cellDoubleClicked(), editPieceColor(), fillTable(), invertIncludedPieces(), invertLockedPieces(), PiecesWidget(), showContextMenu(), toggleInLayoutPieces(), toggleLockedPieces(), togglePiece(), and updateList().
m_doc
VAbstractPattern* PiecesWidget::m_doc private
Definition at line 95 of file pieces_widget.h.
Referenced by cellClicked(), editPieceColor(), invertIncludedPieces(), invertLockedPieces(), toggleInLayoutPieces(), and toggleLockedPieces().
ui
Ui::PiecesWidget* PiecesWidget::ui private
Definition at line 94 of file pieces_widget.h.
Referenced by cellClicked(), cellDoubleClicked(), changeEvent(), fillTable(), invertIncludedPieces(), invertLockedPieces(), PiecesWidget(), selectPiece(), showContextMenu(), toggleInLayoutPieces(), toggleLockedPieces(), togglePiece(), and ~PiecesWidget().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/pieces_widget.h
src/app/seamly2d/dialogs/pieces_widget.cpp