Seamly2D: VPieceLabelData Class Reference
VPieceLabelData Class Reference
The VPieceLabelData class holds some information about a single piece like letter, name, material type, cut number and placement.
#include <vpiecelabeldata.h>
Public Member Functions
VPieceLabelData ()
VPieceLabelData (const VPieceLabelData &data)
virtual ~VPieceLabelData ()
VPieceLabelData & operator= (const VPieceLabelData &data)
void Swap (VPieceLabelData &data) Q_DECL_NOTHROW
void Clear ()
QString GetLetter () const
void SetLetter (const QString &qsLetter)
QString GetAnnotation () const
void SetAnnotation (const QString &val)
QString GetOrientation () const
void SetOrientation (const QString &val)
QString GetRotationWay () const
void SetRotationWay (const QString &val)
QString GetTilt () const
void SetTilt (const QString &val)
QString GetFoldPosition () const
void SetFoldPosition (const QString &val)
int GetQuantity () const
void SetQuantity (int val)
bool IsOnFold () const
void SetOnFold (bool onFold)
QVector< VLabelTemplateLine > GetLabelTemplate () const
void SetLabelTemplate (const QVector< VLabelTemplateLine > &lines)
Public Member Functions inherited from VPatternLabelData
VPatternLabelData ()
VPatternLabelData (const VPatternLabelData &data)
virtual ~VPatternLabelData ()
VPatternLabelData & operator= (const VPatternLabelData &data)
void Swap (VPatternLabelData &data) Q_DECL_NOTHROW
QString GetLabelWidth () const
void SetLabelWidth (const QString &dLabelW)
QString GetLabelHeight () const
void SetLabelHeight (const QString &dLabelH)
int getFontSize () const
void SetFontSize (int iSize)
QString GetRotation () const
void SetRotation (const QString &dRot)
quint32 centerAnchorPoint () const
void setCenterAnchorPoint (const quint32 &centerAnchorPoint)
quint32 topLeftAnchorPoint () const
void setTopLeftAnchorPoint (const quint32 &topLeftAnchorPoint)
quint32 bottomRightAnchorPoint () const
void setBottomRightAnchorPoint (const quint32 &bottomRightAnchorPoint)
Public Member Functions inherited from VAbstractFloatItemData
VAbstractFloatItemData ()
VAbstractFloatItemData (const VAbstractFloatItemData &data)
virtual ~VAbstractFloatItemData ()
VAbstractFloatItemData & operator= (const VAbstractFloatItemData &data)
void Swap (VAbstractFloatItemData &data) Q_DECL_NOTHROW
QPointF GetPos () const
void SetPos (const QPointF &ptPos)
bool IsVisible () const
void SetVisible (bool bVisible)
Private Attributes
QSharedDataPointer< VPieceLabelDataPrivate > d
Detailed Description
The VPieceLabelData class holds some information about a single piece like letter, name, material type, cut number and placement.
Definition at line 44 of file vpiecelabeldata.h.
Constructor & Destructor Documentation
VPieceLabelData() [1/2]
VPieceLabelData::VPieceLabelData ()
Definition at line 43 of file vpiecelabeldata.cpp.
VPieceLabelData() [2/2]
VPieceLabelData::VPieceLabelData (const VPieceLabelData & data)
Definition at line 49 of file vpiecelabeldata.cpp.
~VPieceLabelData()
VPieceLabelData::~VPieceLabelData () virtual
Definition at line 67 of file vpiecelabeldata.cpp.
Member Function Documentation
Clear()
void VPieceLabelData::Clear ()
Definition at line 71 of file vpiecelabeldata.cpp.
References d.
GetAnnotation()
QString VPieceLabelData::GetAnnotation () const
Definition at line 89 of file vpiecelabeldata.cpp.
References d.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), EditLabelTemplateDialog::SetPiece(), and PatternPieceDialog::SetPiece().
GetFoldPosition()
QString VPieceLabelData::GetFoldPosition () const
Definition at line 137 of file vpiecelabeldata.cpp.
References d.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), EditLabelTemplateDialog::SetPiece(), and PatternPieceDialog::SetPiece().
GetLabelTemplate()
QVector< VLabelTemplateLine > VPieceLabelData::GetLabelTemplate () const
Definition at line 176 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::SetPiece(), and VTextManager::Update().
GetLetter()
QString VPieceLabelData::GetLetter () const
Definition at line 77 of file vpiecelabeldata.cpp.
References d.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), EditLabelTemplateDialog::SetPiece(), and PatternPieceDialog::SetPiece().
GetOrientation()
QString VPieceLabelData::GetOrientation () const
Definition at line 101 of file vpiecelabeldata.cpp.
References d.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), EditLabelTemplateDialog::SetPiece(), and PatternPieceDialog::SetPiece().
GetQuantity()
int VPieceLabelData::GetQuantity () const
Definition at line 149 of file vpiecelabeldata.cpp.
References d.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), EditLabelTemplateDialog::SetPiece(), and PatternPieceDialog::SetPiece().
GetRotationWay()
QString VPieceLabelData::GetRotationWay () const
Definition at line 113 of file vpiecelabeldata.cpp.
References d.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), EditLabelTemplateDialog::SetPiece(), and PatternPieceDialog::SetPiece().
GetTilt()
QString VPieceLabelData::GetTilt () const
Definition at line 125 of file vpiecelabeldata.cpp.
References d.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), EditLabelTemplateDialog::SetPiece(), and PatternPieceDialog::SetPiece().
IsOnFold()
bool VPieceLabelData::IsOnFold () const
Definition at line 164 of file vpiecelabeldata.cpp.
References d.
Referenced by anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders(), EditLabelTemplateDialog::SetPiece(), and PatternPieceDialog::SetPiece().
operator=()
VPieceLabelData & VPieceLabelData::operator= (const VPieceLabelData & data)
Definition at line 55 of file vpiecelabeldata.cpp.
References d, and VPatternLabelData::operator=().
SetAnnotation()
void VPieceLabelData::SetAnnotation (const QString & val)
Definition at line 95 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceDataTag().
SetFoldPosition()
void VPieceLabelData::SetFoldPosition (const QString & val)
Definition at line 143 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceDataTag().
SetLabelTemplate()
void VPieceLabelData::SetLabelTemplate (const QVector< VLabelTemplateLine > & lines)
Definition at line 182 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), and VPattern::ParsePieceDataTag().
SetLetter()
void VPieceLabelData::SetLetter (const QString & qsLetter)
Definition at line 83 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceDataTag().
SetOnFold()
void VPieceLabelData::SetOnFold (bool onFold)
Definition at line 170 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceDataTag().
SetOrientation()
void VPieceLabelData::SetOrientation (const QString & val)
Definition at line 107 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceDataTag().
SetQuantity()
void VPieceLabelData::SetQuantity (int val)
Definition at line 155 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceDataTag().
SetRotationWay()
void VPieceLabelData::SetRotationWay (const QString & val)
Definition at line 119 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceDataTag().
SetTilt()
void VPieceLabelData::SetTilt (const QString & val)
Definition at line 131 of file vpiecelabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceDataTag().
Swap()
void VPieceLabelData::Swap (VPieceLabelData & data)
Definition at line 39 of file vpiecelabeldata.cpp.
References VPatternLabelData::Swap().
Member Data Documentation
d
QSharedDataPointer<VPieceLabelDataPrivate> VPieceLabelData::d private
Definition at line 90 of file vpiecelabeldata.h.
Referenced by Clear(), GetAnnotation(), GetFoldPosition(), GetLabelTemplate(), GetLetter(), GetOrientation(), GetQuantity(), GetRotationWay(), GetTilt(), IsOnFold(), operator=(), SetAnnotation(), SetFoldPosition(), SetLabelTemplate(), SetLetter(), SetOnFold(), SetOrientation(), SetQuantity(), SetRotationWay(), and SetTilt().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/floatItemData/vpiecelabeldata.h
src/libs/vpatterndb/floatItemData/vpiecelabeldata.cpp