Seamly2D: VFormulaPropertyEditor Class Reference
VFormulaPropertyEditor Class Reference
#include <vformulapropertyeditor.h>
Public Slots
void SetFormula (const VFormula &formula)
Sets the color of the widget.
Signals
void dataChangedByUser (const VFormula &GetFormula, VFormulaPropertyEditor *editor)
This is emitted, when the user changes the color.
void dataChanged ()
Public Member Functions
VFormulaPropertyEditor (QWidget *parent)
Constructor taking a widget as parent.
virtual ~VFormulaPropertyEditor () Q_DECL_EQ_DEFAULT
Destructor.
VFormula GetFormula () const
Returns the formula currently set.
virtual bool eventFilter (QObject *obj, QEvent *ev) Q_DECL_OVERRIDE
Needed for proper event handling.
Private Slots
void onToolButtonClicked ()
Private Attributes
VFormula formula
QToolButton * toolButton
QLabel * textLabel
QSpacerItem * spacer
Detailed Description
Definition at line 68 of file vformulapropertyeditor.h.
Constructor & Destructor Documentation
VFormulaPropertyEditor()
VFormulaPropertyEditor::VFormulaPropertyEditor (QWidget * parent) explicit
Constructor taking a widget as parent.
Definition at line 71 of file vformulapropertyeditor.cpp.
References formula, VFormula::getStringValue(), onToolButtonClicked(), spacer, textLabel, and toolButton.
~VFormulaPropertyEditor()
virtual VFormulaPropertyEditor::~VFormulaPropertyEditor () virtual
Destructor.
Member Function Documentation
dataChanged
void VFormulaPropertyEditor::dataChanged () signal
dataChangedByUser
void VFormulaPropertyEditor::dataChangedByUser (const VFormula & GetFormula, VFormulaPropertyEditor * editor) signal
This is emitted, when the user changes the color.
Referenced by onToolButtonClicked().
eventFilter()
bool VFormulaPropertyEditor::eventFilter (QObject * obj, QEvent * ev) virtual
Needed for proper event handling.
Definition at line 139 of file vformulapropertyeditor.cpp.
References toolButton.
GetFormula()
VFormula VFormulaPropertyEditor::GetFormula () const
Returns the formula currently set.
Definition at line 152 of file vformulapropertyeditor.cpp.
References formula.
Referenced by VFormulaProperty::getEditorData().
onToolButtonClicked
void VFormulaPropertyEditor::onToolButtonClicked () private slot
Definition at line 119 of file vformulapropertyeditor.cpp.
References dataChangedByUser(), formula, FromUser, VFormula::getCheckZero(), VFormula::getData(), EditFormulaDialog::GetFormula(), VFormula::GetFormula(), VFormula::getPostfix(), VFormula::getStringValue(), VFormula::getToolId(), qApp, EditFormulaDialog::setCheckZero(), EditFormulaDialog::SetFormula(), VFormula::SetFormula(), EditFormulaDialog::setPostfix(), textLabel, and ToUser.
Referenced by VFormulaPropertyEditor().
SetFormula
void VFormulaPropertyEditor::SetFormula (const VFormula & formula) slot
Sets the color of the widget.
Definition at line 109 of file vformulapropertyeditor.cpp.
References formula, VFormula::getStringValue(), and textLabel.
Referenced by VFormulaProperty::setEditorData().
Member Data Documentation
formula
VFormula VFormulaPropertyEditor::formula private
Definition at line 100 of file vformulapropertyeditor.h.
Referenced by GetFormula(), onToolButtonClicked(), SetFormula(), and VFormulaPropertyEditor().
spacer
QSpacerItem* VFormulaPropertyEditor::spacer private
Definition at line 103 of file vformulapropertyeditor.h.
Referenced by VFormulaPropertyEditor().
textLabel
QLabel* VFormulaPropertyEditor::textLabel private
Definition at line 102 of file vformulapropertyeditor.h.
Referenced by onToolButtonClicked(), SetFormula(), and VFormulaPropertyEditor().
toolButton
QToolButton* VFormulaPropertyEditor::toolButton private
Definition at line 101 of file vformulapropertyeditor.h.
Referenced by eventFilter(), and VFormulaPropertyEditor().
The documentation for this class was generated from the following files:
src/app/seamly2d/core/vformulapropertyeditor.h
src/app/seamly2d/core/vformulapropertyeditor.cpp