Seamly2D: VContainer Class Reference
VContainer Class Reference
The VContainer class container of all variables.
#include <vcontainer.h>
Public Member Functions
VContainer (const VTranslateVars *trVars, const Unit *patternUnit)
VContainer create empty container.
VContainer (const VContainer &data)
VContainer create container from another container.
~VContainer ()
VContainer & operator= (const VContainer &data)
operator = copy constructor
void Swap (VContainer &data) Q_DECL_NOTHROW
template<typename T >
const QSharedPointer< T > GeometricObject (const quint32 &id) const
const QSharedPointer< VGObject > GetGObject (quint32 id) const
GetGObject returns a point by id.
VPiece GetPiece (quint32 id) const
VPiecePath GetPiecePath (quint32 id) const
template<typename T >
QSharedPointer< T > GetVariable (QString name) const
GetVariable return varible by name.
quint32 AddGObject (VGObject *obj)
AddGObject add new GObject to container.
quint32 AddPiece (const VPiece &piece)
quint32 AddPiecePath (const VPiecePath &path)
void AddLine (const quint32 &firstPointId, const quint32 &secondPointId)
AddLine add line to container.
void AddArc (const QSharedPointer< VAbstractCurve > &arc, const quint32 &id, const quint32 &parentId=null_id)
void AddSpline (const QSharedPointer< VAbstractBezier > &curve, quint32 id, quint32 parentId=null_id)
void AddCurveWithSegments (const QSharedPointer< VAbstractCubicBezierPath > &curve, const quint32 &id, quint32 parentId=null_id)
template<typename T >
void AddVariable (const QString &name, T *var)
template<typename T >
void AddVariable (const QString &name, const QSharedPointer< T > &var)
void RemoveVariable (const QString &name)
void RemovePiece (quint32 id)
template<class T >
void UpdateGObject (quint32 id, T *obj)
UpdateGObject update GObject by id.
template<class T >
void UpdateGObject (quint32 id, const QSharedPointer< T > &obj)
void UpdatePiece (quint32 id, const VPiece &piece)
void UpdatePiecePath (quint32 id, const VPiecePath &path)
void Clear ()
Clear clear data in container. Id will be 0.
void ClearForFullParse ()
void ClearGObjects ()
ClearObject points, splines, arcs, spline paths will be cleared.
void ClearCalculationGObjects ()
void ClearVariables (const VarType &type=VarType::Unknown)
void removeCustomVariable (const QString &name)
removeCustomVariable remove increment by name from increment table
const QHash< quint32, QSharedPointer< VGObject > > * DataGObjects () const
data container with datagObjects return container of gObjects
const QHash< quint32, VPiece > * DataPieces () const
const QHash< QString, QSharedPointer< VInternalVariable > > * DataVariables () const
const QMap< QString, QSharedPointer< VMeasurement > > DataMeasurements () const
const QMap< QString, QSharedPointer< VIncrement > > variablesData () const
const QMap< QString, QSharedPointer< VLengthLine > > lineLengthsData () const
const QMap< QString, QSharedPointer< VCurveLength > > curveLengthsData () const
const QMap< QString, QSharedPointer< VCurveCLength > > controlPointLengthsData () const
const QMap< QString, QSharedPointer< VLineAngle > > lineAnglesData () const
const QMap< QString, QSharedPointer< VArcRadius > > arcRadiusesData () const
const QMap< QString, QSharedPointer< VCurveAngle > > curveAnglesData () const
const Unit * GetPatternUnit () const
const VTranslateVars * GetTrVars () const
Static Public Member Functions
static const QSharedPointer< VGObject > GetFakeGObject (quint32 id)
static quint32 getId ()
static quint32 getNextId ()
getNextId generate next unique id
static void UpdateId (quint32 newId)
UpdateId update id. If new id bigger when current save new like current.
static void ClearUniqueNames ()
static void ClearUniqueIncrementNames ()
static void SetSize (qreal size)
SetSize set value of size.
static void SetHeight (qreal height)
SetGrowth set value of growth.
static qreal size ()
size return size
static qreal * rsize ()
static qreal height ()
height return height
static qreal * rheight ()
static bool IsUnique (const QString &name)
static QStringList AllUniqueNames ()
Private Member Functions
void AddCurve (const QSharedPointer< VAbstractCurve > &curve, const quint32 &id, quint32 parentId=null_id)
template<class T >
uint qHash (const QSharedPointer< T > &p)
template<typename key , typename val >
const val GetObject (const QHash< key, val > &obj, key id) const
GetObject return object from container.
template<typename T >
void UpdateObject (const quint32 &id, const QSharedPointer< T > &point)
UpdateObject update object in container.
template<typename T >
const QMap< QString, QSharedPointer< T > > DataVar (const VarType &type) const
Static Private Member Functions
template<typename key , typename val >
static quint32 AddObject (QHash< key, val > &obj, val value)
AddObject add object to container.
Private Attributes
QSharedDataPointer< VContainerData > d
Static Private Attributes
static quint32 _id = null_id
_id current id. New object will have value +1. For empty class equal 0.
static qreal _size = 50
static qreal _height = 176
static QSet< QString > uniqueNames = QSet<QString>()
Detailed Description
The VContainer class container of all variables.
Definition at line 140 of file vcontainer.h.
Constructor & Destructor Documentation
VContainer() [1/2]
VContainer::VContainer (const VTranslateVars * trVars, const Unit * patternUnit)
VContainer create empty container.
Definition at line 107 of file vcontainer.cpp.
VContainer() [2/2]
VContainer::VContainer (const VContainer & data)
VContainer create container from another container.
Parameters
data container
Definition at line 132 of file vcontainer.cpp.
~VContainer()
VContainer::~VContainer ()
Definition at line 137 of file vcontainer.cpp.
References ClearGObjects(), and ClearVariables().
Member Function Documentation
AddArc()
void VContainer::AddArc (const QSharedPointer< VAbstractCurve > & arc, const quint32 & id, const quint32 & parentId = null_id)
Definition at line 395 of file vcontainer.cpp.
References AddCurve(), AddVariable(), Arc, EllipticalArc, VInternalVariable::GetName(), and GetPatternUnit().
Referenced by VToolCutArc::Create(), VToolArc::Create(), VToolArcWithLength::Create(), VToolEllipticalArc::Create(), VAbstractMirror::createArc(), VToolRotation::createArc(), VToolMove::createArc(), VToolCurveIntersectAxis::InitArc(), VAbstractMirror::updateArc(), VToolRotation::updateArc(), and VToolMove::updateArc().
AddCurve()
void VContainer::AddCurve (const QSharedPointer< VAbstractCurve > & curve, const quint32 & id, quint32 parentId = null_id) private
Definition at line 419 of file vcontainer.cpp.
References AddVariable(), Arc, CubicBezier, CubicBezierPath, EllipticalArc, EndAngle, VInternalVariable::GetName(), GetPatternUnit(), Spline, SplinePath, and StartAngle.
Referenced by AddArc(), and AddSpline().
AddCurveWithSegments()
void VContainer::AddCurveWithSegments (const QSharedPointer< VAbstractCubicBezierPath > & curve, const quint32 & id, quint32 parentId = null_id)
Definition at line 452 of file vcontainer.cpp.
References AddSpline(), AddVariable(), C1, C2, EndAngle, VInternalVariable::GetName(), GetPatternUnit(), and StartAngle.
Referenced by VToolCubicBezierPath::Create(), VToolSplinePath::Create(), VAbstractMirror::createCurveWithSegments(), VToolRotation::createCurveWithSegments(), VToolMove::createCurveWithSegments(), VAbstractMirror::updateCurveWithSegments(), VToolRotation::updateCurveWithSegments(), and VToolMove::updateCurveWithSegments().
AddGObject()
quint32 VContainer::AddGObject (VGObject * obj)
AddGObject add new GObject to container.
Parameters
obj new object
Returns
return id of new object in container
Definition at line 216 of file vcontainer.cpp.
References AddObject(), d, VGObject::name(), SCASSERT, and uniqueNames.
Referenced by QT_WARNING_POP::AddAnchorPoint(), QT_WARNING_POP::AddNodeArc(), QT_WARNING_POP::AddNodeElArc(), QT_WARNING_POP::AddNodePoint(), QT_WARNING_POP::AddNodeSpline(), QT_WARNING_POP::AddNodeSplinePath(), PointIntersectXYTool::Create(), VToolCurveIntersectAxis::Create(), VToolLineIntersectAxis::Create(), VToolEndLine::Create(), VToolHeight::Create(), VToolAlongLine::Create(), VToolPointOfIntersectionArcs::Create(), VToolCutSpline::Create(), VToolCutArc::Create(), VToolCutSplinePath::Create(), VToolPointFromArcAndTangent::Create(), VToolTriangle::Create(), IntersectCircleTangentTool::Create(), IntersectCirclesTool::Create(), VToolPointOfIntersectionCurves::Create(), VToolArc::Create(), VToolArcWithLength::Create(), VToolEllipticalArc::Create(), VToolLineIntersect::Create(), VToolNormal::Create(), VToolBisector::Create(), VToolShoulderPoint::Create(), VToolPointOfContact::Create(), VToolCubicBezier::Create(), VToolCubicBezierPath::Create(), VToolSpline::Create(), VToolSplinePath::Create(), VToolBasePoint::Create(), VToolTrueDarts::Create(), VAbstractMirror::createItem(), VToolRotation::createItem(), VToolMove::createItem(), VAbstractTool::CreateNode(), VAbstractMirror::createPoint(), VToolRotation::createPoint(), and VToolMove::createPoint().
AddLine()
void VContainer::AddLine (const quint32 & firstPointId, const quint32 & secondPointId)
AddLine add line to container.
Parameters
firstPointId id of first point of line
secondPointId id of second point of line
Definition at line 382 of file vcontainer.cpp.
References AddVariable(), VInternalVariable::GetName(), and GetPatternUnit().
Referenced by VToolLine::Create(), PointIntersectXYTool::Create(), VToolCurveIntersectAxis::Create(), VToolLineIntersectAxis::Create(), VToolEndLine::Create(), VToolHeight::Create(), VToolAlongLine::Create(), VToolLineIntersect::Create(), VToolNormal::Create(), VToolBisector::Create(), VToolShoulderPoint::Create(), and VToolPointOfContact::Create().
AddObject()
template<typename key , typename val > quint32 VContainer::AddObject (QHash< key, val > & obj, val value) static private
AddObject add object to container.
Parameters
obj container
value object
Returns
id of object in container
Definition at line 500 of file vcontainer.cpp.
References getNextId(), and SCASSERT.
Referenced by AddGObject().
AddPiece()
quint32 VContainer::AddPiece (const VPiece & piece)
Definition at line 225 of file vcontainer.cpp.
References d, and getNextId().
Referenced by PatternPieceTool::Create().
AddPiecePath()
quint32 VContainer::AddPiecePath (const VPiecePath & path)
Definition at line 233 of file vcontainer.cpp.
References d, and getNextId().
Referenced by VToolInternalPath::Create(), QT_WARNING_POP::createCSAUnion(), and QT_WARNING_POP::createUnionInternalPaths().
AddSpline()
void VContainer::AddSpline (const QSharedPointer< VAbstractBezier > & curve, quint32 id, quint32 parentId = null_id)
Definition at line 440 of file vcontainer.cpp.
References AddCurve(), AddVariable(), C1, C2, VInternalVariable::GetName(), and GetPatternUnit().
Referenced by AddCurveWithSegments(), VToolCutSpline::Create(), VToolCutSplinePath::Create(), VToolCubicBezier::Create(), VToolSpline::Create(), VAbstractMirror::createCurve(), VToolRotation::createCurve(), VToolMove::createCurve(), VAbstractMirror::updateCurve(), VToolRotation::updateCurve(), and VToolMove::updateCurve().
AddVariable() [1/2]
template<typename T > void VContainer::AddVariable (const QString & name, const QSharedPointer< T > & var)
Definition at line 334 of file vcontainer.h.
References d, and uniqueNames.
AddVariable() [2/2]
template<typename T > void VContainer::AddVariable (const QString & name, T * var)
Definition at line 327 of file vcontainer.h.
Referenced by AddArc(), AddCurve(), AddCurveWithSegments(), AddLine(), AddSpline(), VToolAlongLine::Create(), PatternPieceTool::Create(), DialogInternalPath::evaluateDefaultWidth(), PatternPieceDialog::evaluateDefaultWidth(), VPattern::ParseIncrementsElement(), VMeasurements::ReadMeasurements(), and DialogAlongLine::SetCurrentLength().
AllUniqueNames()
QStringList VContainer::AllUniqueNames () static
Definition at line 591 of file vcontainer.cpp.
References builInFunctions, and uniqueNames.
Referenced by VPattern::GenerateSuffix(), VToolOptionsPropertyBrowser::setOperationSuffix(), DialogMirrorByAxis::suffixChanged(), DialogMirrorByLine::suffixChanged(), DialogMove::suffixChanged(), and DialogRotation::suffixChanged().
arcRadiusesData()
const QMap< QString, QSharedPointer< VArcRadius > > VContainer::arcRadiusesData () const
Definition at line 573 of file vcontainer.cpp.
References ArcRadius.
Referenced by EditFormulaDialog::arcRadii(), and DialogVariables::fillArcsRadiuses().
Clear()
void VContainer::Clear ()
Clear clear data in container. Id will be 0.
Definition at line 281 of file vcontainer.cpp.
References _id, ClearGObjects(), ClearUniqueNames(), ClearVariables(), d, and NULL_ID.
Referenced by MainWindow::Clear().
ClearCalculationGObjects()
void VContainer::ClearCalculationGObjects ()
Definition at line 322 of file vcontainer.cpp.
References Calculation, and d.
Referenced by VPattern::parseDraftBlockElement().
ClearForFullParse()
void VContainer::ClearForFullParse ()
Definition at line 294 of file vcontainer.cpp.
References _id, ArcRadius, ClearGObjects(), ClearUniqueNames(), ClearVariables(), CurveAngle, CurveCLength, CurveLength, d, Increment, LineAngle, LineLength, and NULL_ID.
Referenced by VPattern::PrepareForParse().
ClearGObjects()
void VContainer::ClearGObjects ()
ClearObject points, splines, arcs, spline paths will be cleared.
Definition at line 316 of file vcontainer.cpp.
References d.
Referenced by MainWindow::addDraftBlock(), Clear(), ClearForFullParse(), and ~VContainer().
ClearUniqueIncrementNames()
void VContainer::ClearUniqueIncrementNames () static
Definition at line 635 of file vcontainer.cpp.
References ClearUniqueNames(), and uniqueNames.
Referenced by VPattern::LiteParseIncrements().
ClearUniqueNames()
void VContainer::ClearUniqueNames () static
Definition at line 629 of file vcontainer.cpp.
References uniqueNames.
Referenced by Clear(), ClearForFullParse(), ClearUniqueIncrementNames(), VPattern::PrepareForParse(), and TMainWindow::RefreshData().
ClearVariables()
void VContainer::ClearVariables (const VarType & type = VarType::Unknown)
Definition at line 348 of file vcontainer.cpp.
References d, and Unknown.
Referenced by Clear(), ClearForFullParse(), VPattern::LiteParseIncrements(), MainWindow::LoadMeasurements(), VPattern::PrepareForParse(), TMainWindow::RefreshData(), MainWindow::UpdateMeasurements(), and ~VContainer().
controlPointLengthsData()
const QMap< QString, QSharedPointer< VCurveCLength > > VContainer::controlPointLengthsData () const
Definition at line 561 of file vcontainer.cpp.
References CurveCLength.
Referenced by EditFormulaDialog::controlPointLengths(), and DialogVariables::fillControlPointLengths().
curveAnglesData()
const QMap< QString, QSharedPointer< VCurveAngle > > VContainer::curveAnglesData () const
Definition at line 579 of file vcontainer.cpp.
References CurveAngle.
Referenced by EditFormulaDialog::curveAngles(), and DialogVariables::fillCurveAngles().
curveLengthsData()
const QMap< QString, QSharedPointer< VCurveLength > > VContainer::curveLengthsData () const
Definition at line 555 of file vcontainer.cpp.
References CurveLength.
Referenced by EditFormulaDialog::curveLengths(), and DialogVariables::fillCurveLengths().
DataGObjects()
const QHash< quint32, QSharedPointer< VGObject > > * VContainer::DataGObjects () const
data container with datagObjects return container of gObjects
Returns
pointer on container of gObjects
Definition at line 706 of file vcontainer.cpp.
References d.
Referenced by MainWindow::draftPointNamesList(), DialogTool::FillCombo(), DialogTool::FillComboBoxCurves(), DialogTool::FillComboBoxSplines(), DialogTool::FillComboBoxSplinesPath(), VToolOptionsPropertyBrowser::getObjectList(), GroupsWidget::itemDoubleClicked(), VAbstractTool::PointsList(), and MainWindow::zoomToPoint().
DataMeasurements()
const QMap< QString, QSharedPointer< VMeasurement > > VContainer::DataMeasurements () const
Definition at line 537 of file vcontainer.cpp.
References Measurement.
Referenced by EditFormulaDialog::measurements(), and TMainWindow::RefreshTable().
DataPieces()
const QHash< quint32, VPiece > * VContainer::DataPieces () const
Definition at line 712 of file vcontainer.cpp.
References d.
Referenced by PiecesWidget::cellClicked(), PiecesWidget::cellDoubleClicked(), MainWindow::ClosedPiecesDialogWithApply(), PatternPieceDialog::createPieceName(), TogglePieceLock::doCmd(), TogglePieceInLayout::doCmd(), SetPieceColor::doCmd(), MainWindow::DoExport(), MainWindow::exportPiecesAs(), MainWindow::handlePieceMenu(), PiecesWidget::PiecesWidget(), MainWindowsNoGUI::refreshGrainLines(), MainWindowsNoGUI::refreshLabels(), MainWindowsNoGUI::refreshSeamAllowances(), MainWindow::setToolsEnabled(), PiecesWidget::showContextMenu(), MainWindow::showLayoutMode(), MainWindow::showPieceMode(), PiecesWidget::toggleInLayoutPieces(), PiecesWidget::toggleLockedPieces(), PiecesWidget::togglePiece(), PiecesWidget::updateList(), and MainWindow::zoomFirstShow().
DataVar()
template<typename T > const QMap< QString, QSharedPointer< T > > VContainer::DataVar (const VarType & type) const private
Definition at line 612 of file vcontainer.cpp.
References d.
DataVariables()
const QHash< QString, QSharedPointer< VInternalVariable > > * VContainer::DataVariables () const
Definition at line 718 of file vcontainer.cpp.
References d.
Referenced by DialogSplinePath::Angle1Changed(), DialogSplinePath::Angle2Changed(), VAbstractTool::CheckFormula(), DialogSpline::CurrentSpline(), VFormula::Eval(), DialogTool::Eval(), TMainWindow::EvalFormula(), anonymous_namespace{vpiecenode.cpp}::EvalFormula(), VPattern::EvalFormula(), VMeasurements::EvalFormula(), DialogVariables::evalVariableFormula(), anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceDialog::getFormulaValue(), DialogSplinePath::Length1Changed(), DialogSplinePath::Length2Changed(), TMainWindow::RefreshTable(), MainWindowsNoGUI::SetSizeHeightForIndividualM(), TMainWindow::ShowNewMData(), PatternPieceDialog::updateGrainlineValues(), PatternPieceDialog::updatePatternLabelValues(), PatternPieceDialog::updatePieceLabelValues(), and EditFormulaDialog::valueChanged().
GeometricObject()
template<typename T > const QSharedPointer< T > VContainer::GeometricObject (const quint32 & id) const
Definition at line 266 of file vcontainer.h.
References d, NULL_ID, and SCASSERT.
Referenced by QT_WARNING_POP::AddAnchorPoint(), QT_WARNING_POP::AddNodeArc(), QT_WARNING_POP::AddNodeElArc(), QT_WARNING_POP::AddNodePoint(), QT_WARNING_POP::AddNodeSpline(), QT_WARNING_POP::AddNodeSplinePath(), VNodePoint::AddToFile(), VToolOptionsPropertyBrowser::changeDataToolCubicBezier(), VToolOptionsPropertyBrowser::changeDataToolSpline(), DialogLineIntersect::CheckIntersecion(), DialogCubicBezierPath::ChosenObject(), DialogSplinePath::ChosenObject(), PatternPieceDialog::ChosenObject(), VAbstractOperation::complexCurveToolTip(), VAbstractOperation::complexPointToolTip(), VToolDoublePoint::complexToolTip(), VToolSpline::ControlPointChangePosition(), VToolSplinePath::ControlPointChangePosition(), VNodeDetail::Convert(), InsertNodesDialog::correctCurveDirection(), VToolLine::Create(), PointIntersectXYTool::Create(), VToolCurveIntersectAxis::Create(), VToolLineIntersectAxis::Create(), VToolEndLine::Create(), VToolHeight::Create(), VToolAlongLine::Create(), VToolPointOfIntersectionArcs::Create(), VToolCutSpline::Create(), VToolCutArc::Create(), VToolCutSplinePath::Create(), VToolPointFromArcAndTangent::Create(), VToolTriangle::Create(), IntersectCircleTangentTool::Create(), IntersectCirclesTool::Create(), VToolPointOfIntersectionCurves::Create(), VToolArc::Create(), VToolArcWithLength::Create(), VToolEllipticalArc::Create(), VToolRotation::Create(), VToolLineIntersect::Create(), VToolNormal::Create(), VToolBisector::Create(), VToolShoulderPoint::Create(), VToolPointOfContact::Create(), VToolMirrorByLine::Create(), VToolMirrorByAxis::Create(), VToolCubicBezier::Create(), VToolCubicBezierPath::Create(), VToolSpline::Create(), VToolSplinePath::Create(), VToolTrueDarts::Create(), VToolMove::Create(), AnchorPointTool::Create(), VAbstractMirror::createArc(), VToolRotation::createArc(), VToolMove::createArc(), VAbstractMirror::createCurve(), VToolRotation::createCurve(), VToolMove::createCurve(), VAbstractMirror::createCurveWithSegments(), VToolRotation::createCurveWithSegments(), VToolMove::createCurveWithSegments(), VAbstractMirror::createItem(), VToolRotation::createItem(), VToolMove::createItem(), VAbstractTool::CreateNode(), VisToolMove::createOriginObjects(), VAbstractMirror::createPoint(), VToolRotation::createPoint(), VToolMove::createPoint(), VisToolMove::createRotatedObjects(), DialogCubicBezierPath::currentPointChanged(), DialogSplinePath::currentPointChanged(), anonymous_namespace{vpiecepath.cpp}::CurveEndPoint(), anonymous_namespace{vpiecepath.cpp}::CurvePoint(), anonymous_namespace{vpiecepath.cpp}::CurveStartPoint(), DoubleLinePointTool::DoubleLinePointTool(), VPiecePath::EndSegment(), anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), PatternPieceTool::FindGrainlineGeometry(), anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), VToolCubicBezier::FirstPointName(), VToolCubicBezier::ForthPointName(), VToolArc::getArc(), VToolBasePoint::GetBasePointPos(), VToolArc::getCenter(), VToolArcWithLength::getCenter(), VToolEllipticalArc::getCenter(), VToolArc::GetFormulaF1(), VToolArcWithLength::GetFormulaF1(), VToolEllipticalArc::GetFormulaF1(), VToolArc::GetFormulaF2(), VToolEllipticalArc::GetFormulaF2(), VToolArcWithLength::GetFormulaLength(), VToolArc::GetFormulaRadius(), VToolArcWithLength::GetFormulaRadius(), VToolEllipticalArc::GetFormulaRadius1(), VToolEllipticalArc::GetFormulaRadius2(), VToolEllipticalArc::GetFormulaRotationAngle(), VAbstractSpline::getLineColor(), VAbstractSpline::getLineWeight(), VPiece::getNodeSAPoints(), DialogCubicBezier::GetP1(), DialogSpline::GetP1(), DialogCubicBezier::GetP2(), DialogCubicBezier::GetP3(), DialogCubicBezier::GetP4(), DialogSpline::GetP4(), VAbstractSpline::GetPenStyle(), GroupsWidget::getPointName(), HistoryDialog::getPointName(), VToolCubicBezier::getSpline(), VToolSpline::getSpline(), VToolCubicBezierPath::getSplinePath(), VToolSplinePath::getSplinePath(), VToolSplinePath::hoverEnterEvent(), VToolCurveIntersectAxis::InitArc(), VAbstractOperation::InitCurve(), VAbstractSpline::InitDefShape(), InsertNodesDialog::insertCurveNodes(), VToolSpline::IsMovable(), VToolSplinePath::IsMovable(), VAbstractOperation::isPointNameVisible(), VToolDoublePoint::isPointNameVisible(), VToolSinglePoint::isPointNameVisible(), GroupsWidget::itemDoubleClicked(), VAbstractSpline::makeToolTip(), VToolArc::makeToolTip(), VToolArcWithLength::makeToolTip(), VToolEllipticalArc::makeToolTip(), VToolCutArc::makeToolTip(), VToolCutSpline::makeToolTip(), VToolCutSplinePath::makeToolTip(), DoubleLinePointTool::makeToolTip(), VToolAlongLine::makeToolTip(), VToolHeight::makeToolTip(), VToolLineIntersectAxis::makeToolTip(), VToolLinePoint::makeToolTip(), VToolShoulderPoint::makeToolTip(), VToolBasePoint::makeToolTip(), VToolLineIntersect::makeToolTip(), VToolPointOfContact::makeToolTip(), VToolLine::makeToolTip(), VToolSpline::mouseMoveEvent(), VToolSplinePath::mouseMoveEvent(), VToolSplinePath::mousePressEvent(), VPiecePath::NodeNextPoint(), VPiecePath::NodePreviousPoint(), VDrawTool::ObjectName(), VAbstractSpline::paint(), VPattern::ParseNodeArc(), VPattern::ParseNodeEllipticalArc(), VPattern::ParseNodePoint(), VPattern::ParseNodeSpline(), VPattern::ParseNodeSplinePath(), VPattern::ParseOldToolSpline(), VPattern::ParseOldToolSplinePath(), VPattern::ParseToolCubicBezier(), VPattern::ParseToolCubicBezierPath(), VPattern::ParseToolSplinePath(), VPiecePath::PathNodePoints(), VPiecePath::PathPoints(), DialogArc::pointNameChanged(), DialogArcWithLength::pointNameChanged(), DialogEllipticalArc::pointNameChanged(), DialogHeight::PointNameChanged(), DialogLineIntersect::PointNameChanged(), VAbstractTool::PointsList(), QT_WARNING_POP::PointsOnEdge(), DialogTool::PrepareList(), VPiecePath::PreparePointEkv(), VToolSpline::refreshCtrlPoints(), VToolSplinePath::refreshCtrlPoints(), DoubleLinePointTool::RefreshGeometry(), VToolLinePoint::RefreshGeometry(), VToolLine::RefreshGeometry(), VToolCubicBezier::RefreshGeometry(), VToolCubicBezierPath::RefreshGeometry(), AnchorPointVisual::RefreshGeometry(), IntersectCirclesVisual::RefreshGeometry(), IntersectCircleTangentVisual::RefreshGeometry(), VisToolMirrorByAxis::RefreshGeometry(), VisToolMirrorByLine::RefreshGeometry(), VisToolMove::RefreshGeometry(), VisToolRotation::RefreshGeometry(), PointIntersectXYVisual::RefreshGeometry(), VisToolAlongLine::RefreshGeometry(), VisToolBisector::RefreshGeometry(), VisToolCurveIntersectAxis::RefreshGeometry(), VisToolEndLine::RefreshGeometry(), VisToolHeight::RefreshGeometry(), VisToolLine::RefreshGeometry(), VisToolLineIntersect::RefreshGeometry(), VisToolLineIntersectAxis::RefreshGeometry(), VisToolNormal::RefreshGeometry(), VisToolPointFromArcAndTangent::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VisToolPointOfIntersectionArcs::RefreshGeometry(), VisToolShoulderPoint::RefreshGeometry(), VisToolTriangle::RefreshGeometry(), VisToolTrueDarts::RefreshGeometry(), PieceAnchorPointVisual::RefreshGeometry(), VisToolArc::RefreshGeometry(), VisToolArcWithLength::RefreshGeometry(), VisToolCubicBezier::RefreshGeometry(), VisToolCutArc::RefreshGeometry(), VisToolCutSpline::RefreshGeometry(), VisToolCutSplinePath::RefreshGeometry(), VisToolEllipticalArc::RefreshGeometry(), VisToolPointOfIntersectionCurves::RefreshGeometry(), VisToolSpline::RefreshGeometry(), VisOperation::refreshMirroredObjects(), VToolArc::RemoveReferens(), VToolArcWithLength::RemoveReferens(), VToolCubicBezier::RemoveReferens(), VToolCubicBezierPath::RemoveReferens(), VToolEllipticalArc::RemoveReferens(), VToolSpline::RemoveReferens(), VToolSplinePath::RemoveReferens(), VToolDoublePoint::SaveOptions(), VPiece::SeamAllowancePoints(), VPiecePath::SeamAllowancePoints(), VToolCubicBezier::SecondPointName(), InsertNodesDialog::SelectedObject(), VToolBasePoint::SetBasePointPos(), VToolArc::setCenter(), VToolArcWithLength::setCenter(), VToolEllipticalArc::setCenter(), DialogAlongLine::SetCurrentLength(), VToolArc::setDialog(), VToolArcWithLength::setDialog(), VToolCubicBezier::setDialog(), VToolCubicBezierPath::setDialog(), VToolEllipticalArc::setDialog(), VToolSpline::setDialog(), VToolSplinePath::setDialog(), VToolTrueDarts::setDialog(), IntersectCirclesTool::setDialog(), IntersectCircleTangentTool::setDialog(), PointIntersectXYTool::setDialog(), VToolCutArc::setDialog(), VToolCutSpline::setDialog(), VToolCutSplinePath::setDialog(), VToolAlongLine::setDialog(), VToolBisector::setDialog(), VToolCurveIntersectAxis::setDialog(), VToolEndLine::setDialog(), VToolHeight::setDialog(), VToolLineIntersectAxis::setDialog(), VToolNormal::setDialog(), VToolShoulderPoint::setDialog(), VToolBasePoint::setDialog(), VToolLineIntersect::setDialog(), VToolPointFromArcAndTangent::setDialog(), VToolPointOfContact::setDialog(), VToolPointOfIntersectionArcs::setDialog(), VToolPointOfIntersectionCurves::setDialog(), VToolTriangle::setDialog(), VAbstractSpline::setLineColor(), VAbstractSpline::setLineWeight(), VAbstractSpline::SetPenStyle(), VAbstractOperation::setPointNamePosition(), VToolSinglePoint::setPointNamePosition(), VNodePoint::setPointNamePosition(), VAbstractOperation::setPointNameVisiblity(), VToolDoublePoint::setPointNameVisiblity(), VToolSinglePoint::setPointNameVisiblity(), VNodePoint::setPointNameVisiblity(), VToolArc::SetVisualization(), VToolArcWithLength::SetVisualization(), VToolCubicBezier::SetVisualization(), VToolCubicBezierPath::SetVisualization(), VToolEllipticalArc::SetVisualization(), VToolSpline::SetVisualization(), VToolSplinePath::SetVisualization(), VToolCutArc::SetVisualization(), VToolCutSpline::SetVisualization(), VToolCutSplinePath::SetVisualization(), VAbstractSpline::shape(), DialogCurveIntersectAxis::ShowDialog(), DialogEndLine::ShowDialog(), DialogLineIntersectAxis::ShowDialog(), DialogRotation::ShowDialog(), VPiecePath::StartSegment(), VToolCubicBezier::ThirdPointName(), VAbstractMirror::updateArc(), VToolRotation::updateArc(), VToolMove::updateArc(), VAbstractMirror::updateCurve(), VToolRotation::updateCurve(), VToolMove::updateCurve(), VAbstractMirror::updateCurveWithSegments(), VToolRotation::updateCurveWithSegments(), VToolMove::updateCurveWithSegments(), VAbstractMirror::updateItem(), VToolRotation::updateItem(), VToolMove::updateItem(), QT_WARNING_POP::UpdateNodeArc(), QT_WARNING_POP::UpdateNodeElArc(), QT_WARNING_POP::UpdateNodePoint(), QT_WARNING_POP::UpdateNodeSpline(), QT_WARNING_POP::UpdateNodeSplinePath(), VAbstractMirror::updatePoint(), VToolRotation::updatePoint(), VToolMove::updatePoint(), QT_WARNING_POP::updateUnionAnchors(), VToolLinePoint::VToolLinePoint(), VToolSpline::VToolSpline(), and VToolSplinePath::VToolSplinePath().
GetFakeGObject()
const QSharedPointer< VGObject > VContainer::GetFakeGObject (quint32 id) static
Definition at line 156 of file vcontainer.cpp.
References VGObject::setId().
Referenced by VAbstractOperation::AddToFile(), VToolDoublePoint::AddToFile(), VToolMirrorByAxis::setAxisType(), VToolTrueDarts::SetBaseLineP1Id(), VToolTrueDarts::SetBaseLineP2Id(), VToolTrueDarts::SetDartP1Id(), VToolTrueDarts::SetDartP2Id(), VToolTrueDarts::SetDartP3Id(), VToolMirrorByLine::setFirstLinePointId(), VToolMove::SetFormulaAngle(), VToolRotation::SetFormulaAngle(), VToolMove::SetFormulaLength(), VToolMove::setFormulaRotation(), VToolMirrorByAxis::setOriginPointId(), VToolMove::setOriginPointId(), VToolRotation::setOriginPointId(), VToolMirrorByLine::setSecondLinePointId(), and VAbstractOperation::setSuffix().
GetGObject()
const QSharedPointer< VGObject > VContainer::GetGObject (quint32 id) const
GetGObject returns a point by id.
Parameters
id id of point
Returns
point
Definition at line 150 of file vcontainer.cpp.
References d, and GetObject().
Referenced by VDrawTool::addDependence(), VToolBasePoint::AddToFile(), VDrawTool::AddToFile(), VToolPointOfContact::ArcCenterPointName(), VToolPointFromArcAndTangent::ArcName(), VToolTriangle::AxisP1Name(), VToolTriangle::AxisP2Name(), VToolTrueDarts::BaseLineP1Name(), VToolTrueDarts::BaseLineP2Name(), VToolLinePoint::BasePointName(), VToolArc::CenterPointName(), VToolArcWithLength::CenterPointName(), VToolEllipticalArc::CenterPointName(), PatternPieceDialog::ChosenObject(), IntersectCircleTangentTool::CircleCenterPointName(), VDrawTool::ContextMenu(), InsertNodesDialog::correctCurveDirection(), VToolRotation::Create(), VToolMirrorByLine::Create(), VToolMirrorByAxis::Create(), VToolMove::Create(), VAbstractMirror::createDestination(), anonymous_namespace{vabstracttool.cpp}::CreateNodeSpline(), anonymous_namespace{vabstracttool.cpp}::CreateNodeSplinePath(), VisToolMove::createOriginObjects(), VisToolMove::createRotatedObjects(), VToolCut::CurveName(), VToolCurveIntersectAxis::CurveName(), VToolTrueDarts::DartP1Name(), VToolTrueDarts::DartP2Name(), VToolTrueDarts::DartP3Name(), VAbstractNode::decrementReferens(), VToolPointOfIntersectionArcs::FirstArcName(), IntersectCirclesTool::FirstCircleCenterPointName(), VToolPointOfIntersectionCurves::FirstCurveName(), VToolLineIntersectAxis::FirstLinePoint(), VToolMirrorByLine::firstLinePointName(), VToolHeight::FirstLinePointName(), PointIntersectXYTool::firstPointName(), VToolBisector::FirstPointName(), VToolPointOfContact::FirstPointName(), VToolTriangle::FirstPointName(), VToolLine::FirstPointName(), DialogTool::getNodeInfo(), VToolOptionsPropertyBrowser::getObjectList(), GroupsWidget::getObjName(), VToolMirrorByAxis::getOriginPointName(), VToolMove::getOriginPointName(), VToolRotation::getOriginPointName(), VNodePoint::hoverEnterEvent(), VAbstractNode::incrementReferens(), PatternPieceDialog::initAnchorPoint(), PatternPieceTool::initializeNode(), VAbstractOperation::InitOperatedObjects(), InsertNodesDialog::insertCurveNodes(), GroupsWidget::itemDoubleClicked(), VToolLineIntersect::Line1P1Name(), VToolLineIntersect::Line1P2Name(), VToolLineIntersect::Line2P1Name(), VToolLineIntersect::Line2P2Name(), PatternPieceDialog::newAnchorPoint(), VPattern::ParseNodeSpline(), VPattern::ParseNodeSplinePath(), DoubleLinePointTool::point1Name(), DoubleLinePointTool::point2Name(), VisToolRotation::RefreshGeometry(), VisOperation::refreshMirroredObjects(), VToolTrueDarts::RemoveReferens(), IntersectCirclesTool::RemoveReferens(), IntersectCircleTangentTool::RemoveReferens(), PointIntersectXYTool::RemoveReferens(), VToolCut::RemoveReferens(), DoubleLinePointTool::RemoveReferens(), VToolAlongLine::RemoveReferens(), VToolBisector::RemoveReferens(), VToolLinePoint::RemoveReferens(), VToolNormal::RemoveReferens(), VToolShoulderPoint::RemoveReferens(), VToolLineIntersect::RemoveReferens(), VToolPointFromArcAndTangent::RemoveReferens(), VToolPointOfContact::RemoveReferens(), VToolPointOfIntersectionArcs::RemoveReferens(), VToolPointOfIntersectionCurves::RemoveReferens(), VToolTriangle::RemoveReferens(), VToolLine::RemoveReferens(), VToolPointOfIntersectionArcs::SecondArcName(), IntersectCirclesTool::SecondCircleCenterPointName(), VToolPointOfIntersectionCurves::SecondCurveName(), VToolLineIntersectAxis::SecondLinePoint(), VToolMirrorByLine::secondLinePointName(), VToolHeight::SecondLinePointName(), PointIntersectXYTool::secondPointName(), VToolAlongLine::SecondPointName(), VToolNormal::SecondPointName(), VToolShoulderPoint::SecondPointName(), VToolPointOfContact::SecondPointName(), VToolTriangle::SecondPointName(), VToolLine::SecondPointName(), InsertNodesDialog::SelectedObject(), VToolLinePoint::SetAngle(), VToolArc::setArc(), VToolPointFromArcAndTangent::SetArcId(), VToolPointOfContact::setArcRadius(), VToolTriangle::SetAxisP1Id(), VToolTriangle::SetAxisP2Id(), VToolLinePoint::SetBasePointId(), VToolArc::setCenter(), VToolArcWithLength::setCenter(), VToolEllipticalArc::setCenter(), VToolPointOfContact::setCenter(), IntersectCircleTangentTool::SetCircleCenterId(), IntersectCircleTangentTool::SetCircleRadius(), IntersectCirclesTool::setCirclesCrossPoint(), IntersectCircleTangentTool::setCirclesCrossPoint(), VToolPointFromArcAndTangent::setCirclesCrossPoint(), VToolPointOfIntersectionArcs::setCirclesCrossPoint(), VToolCut::setCurveCutId(), VToolCurveIntersectAxis::setCurveId(), VToolPointOfIntersectionArcs::SetFirstArcId(), IntersectCirclesTool::SetFirstCircleCenterId(), IntersectCirclesTool::SetFirstCircleRadius(), VToolPointOfIntersectionCurves::SetFirstCurveId(), DoubleLinePointTool::setFirstPointId(), VToolBisector::SetFirstPointId(), VToolLineIntersectAxis::SetFirstPointId(), VToolPointOfContact::SetFirstPointId(), VToolTriangle::SetFirstPointId(), VToolCut::SetFormula(), VToolCurveIntersectAxis::SetFormulaAngle(), VToolEndLine::SetFormulaAngle(), VToolLineIntersectAxis::SetFormulaAngle(), VToolArc::SetFormulaF1(), VToolArcWithLength::SetFormulaF1(), VToolEllipticalArc::SetFormulaF1(), VToolArc::SetFormulaF2(), VToolEllipticalArc::SetFormulaF2(), VToolArcWithLength::SetFormulaLength(), VToolLinePoint::SetFormulaLength(), VToolArc::SetFormulaRadius(), VToolArcWithLength::SetFormulaRadius(), VToolEllipticalArc::SetFormulaRadius1(), VToolEllipticalArc::SetFormulaRadius2(), VToolEllipticalArc::SetFormulaRotationAngle(), VToolPointOfIntersectionCurves::SetHCrossPoint(), DoubleLinePointTool::setLineColor(), VToolLinePoint::setLineColor(), VDrawTool::setLineType(), VDrawTool::setLineWeight(), VToolLineIntersect::SetP1Line1(), VToolLineIntersect::SetP1Line2(), VToolHeight::SetP1LineId(), VToolShoulderPoint::SetP2Line(), VToolLineIntersect::SetP2Line1(), VToolLineIntersect::SetP2Line2(), VToolHeight::SetP2LineId(), VAbstractPoint::SetPointName(), VToolShoulderPoint::setPShoulder(), VToolPointOfIntersectionArcs::SetSecondArcId(), IntersectCirclesTool::SetSecondCircleCenterId(), IntersectCirclesTool::SetSecondCircleRadius(), VToolPointOfIntersectionCurves::SetSecondCurveId(), DoubleLinePointTool::setSecondPointId(), VToolAlongLine::SetSecondPointId(), VToolLineIntersectAxis::SetSecondPointId(), VToolNormal::SetSecondPointId(), VToolPointOfContact::SetSecondPointId(), VToolTriangle::SetSecondPointId(), VToolCubicBezier::setSpline(), VToolSpline::setSpline(), VToolCubicBezierPath::setSplinePath(), VToolSplinePath::setSplinePath(), IntersectCircleTangentTool::SetTangentPointId(), VToolPointFromArcAndTangent::SetTangentPointId(), VToolBisector::SetThirdPointId(), VToolPointOfIntersectionCurves::SetVCrossPoint(), VToolShoulderPoint::ShoulderPointName(), IntersectCircleTangentTool::TangentPointName(), VToolPointFromArcAndTangent::TangentPointName(), and VToolBisector::ThirdPointName().
getId()
quint32 VContainer::getId () static
Definition at line 241 of file vcontainer.cpp.
References _id.
Referenced by DialogArc::DialogArc(), DialogArcWithLength::DialogArcWithLength(), and DialogEllipticalArc::DialogEllipticalArc().
getNextId()
quint32 VContainer::getNextId () static
getNextId generate next unique id
Returns
next unique id
Definition at line 251 of file vcontainer.cpp.
References _id.
Referenced by GroupsWidget::addGroupToList(), AddObject(), AddPiece(), AddPiecePath(), VToolLine::Create(), VToolCurveIntersectAxis::Create(), VToolCutArc::Create(), VToolRotation::Create(), UnionTool::Create(), VToolTrueDarts::Create(), VToolMove::Create(), and VAbstractMirror::createDestination().
GetObject()
template<typename key , typename val > const val VContainer::GetObject (const QHash< key, val > & obj, key id) const private
GetObject return object from container.
Parameters
obj container
id id of object
Returns
Object
Definition at line 172 of file vcontainer.cpp.
Referenced by GetGObject().
GetPatternUnit()
const Unit * VContainer::GetPatternUnit () const
Definition at line 599 of file vcontainer.cpp.
References d.
Referenced by AddArc(), AddCurve(), AddCurveWithSegments(), AddLine(), AddSpline(), VToolAlongLine::Create(), VPiece::createBuiltInSaNotch(), VPiece::createSeamAllowanceNotch(), anonymous_namespace{vpiecepath.cpp}::CurvePoint(), anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), PatternPieceTool::FindGrainlineGeometry(), anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), PatternPieceDialog::getFormulaValue(), VPiece::getNodeSAPoints(), VPiece::getSeamNotchSAPoint(), DialogPatternProperties::InitComboBox(), VPiecePath::PreparePointEkv(), VMeasurements::ReadMeasurements(), PatternPieceTool::SaveResizePattern(), PatternPieceTool::saveResizePiece(), VPiece::SeamAllowancePoints(), DialogAlongLine::SetCurrentLength(), PatternPieceDialog::setGrainlineLength(), MainWindow::SetHeight(), VLayoutPiece::SetPatternInfo(), PatternPieceDialog::setPatternLabelHeight(), PatternPieceDialog::setPatternLabelWidth(), PatternPieceDialog::setPieceLabelHeight(), PatternPieceDialog::setPieceLabelWidth(), VLayoutPiece::SetPieceText(), and MainWindow::SetSize().
GetPiece()
VPiece VContainer::GetPiece (quint32 id) const
Definition at line 185 of file vcontainer.cpp.
References d.
Referenced by AnchorPointTool::AddToFile(), VToolInternalPath::AddToFile(), PatternPieceTool::AddToFile(), UnionTool::AddToFile(), UnionDialog::CheckObject(), UnionDialog::checkPiece(), UnionDialog::chosenPiece(), PatternPieceTool::contextMenuEvent(), QT_WARNING_POP::createUnion(), PatternPieceTool::EnableToolMove(), DialogTool::FillComboBoxPiecesList(), PatternPieceTool::insertNodes(), PatternPieceTool::itemChange(), PatternPieceTool::keyReleaseEvent(), PieceTableWidgetItem::operator<(), PatternPieceTool::paint(), PatternPieceTool::PatternPieceTool(), PatternPieceTool::pieceLockedChanged(), PatternPieceTool::RefreshDataInFile(), PatternPieceTool::RefreshGeometry(), PatternPieceTool::renamePiece(), PatternPieceTool::ResetChildren(), PatternPieceTool::SaveDialogChange(), PatternPieceTool::SaveMoveGrainline(), PatternPieceTool::SaveMovePattern(), PatternPieceTool::saveMovePiece(), PatternPieceTool::savePieceRotation(), PatternPieceTool::SaveResizeGrainline(), PatternPieceTool::SaveResizePattern(), PatternPieceTool::saveResizePiece(), PatternPieceTool::SaveRotateGrainline(), PatternPieceTool::SaveRotationPattern(), AnchorPointDialog::SetPieceId(), DialogInternalPath::SetPieceId(), PatternPieceTool::toggleFlipping(), PatternPieceTool::toggleGrainline(), PatternPieceTool::togglePatternLabel(), PatternPieceTool::togglePieceLabel(), PatternPieceTool::toggleSeamAllowance(), PatternPieceTool::toggleSeamLine(), QT_WARNING_POP::unitePieces(), PatternPieceTool::UpdateExcludeState(), PatternPieceTool::UpdateGrainline(), PatternPieceTool::UpdatePatternLabel(), and PatternPieceTool::UpdatePieceLabel().
GetPiecePath()
VPiecePath VContainer::GetPiecePath (quint32 id) const
Definition at line 198 of file vcontainer.cpp.
References d.
Referenced by VToolInternalPath::AddToFile(), anonymous_namespace{vlayoutpiece.cpp}::ConvertInternalPaths(), QT_WARNING_POP::createCSAUnion(), QT_WARNING_POP::createUnionInternalPaths(), QT_WARNING_POP::createUnionPaths(), PatternPieceDialog::getPathName(), VPiece::GetUnitedPath(), PatternPieceTool::InitInternalPaths(), PatternPieceDialog::pathDialogClosed(), VToolInternalPath::RefreshGeometry(), VPiece::SeamAllowancePoints(), PatternPieceDialog::showCustomSAContextMenu(), and PatternPieceDialog::showInternalPathsContextMenu().
GetTrVars()
const VTranslateVars * VContainer::GetTrVars () const
Definition at line 605 of file vcontainer.cpp.
References d.
Referenced by VMeasurements::ReadMeasurements().
GetVariable()
template<typename T > QSharedPointer< T > VContainer::GetVariable (QString name) const
GetVariable return varible by name.
Parameters
name variable's name
Returns
variable
Definition at line 303 of file vcontainer.h.
References d, and SCASSERT.
Referenced by DialogVariables::Fx(), TMainWindow::Fx(), DialogVariables::saveCustomVariableFormula(), TMainWindow::SaveMFullName(), TMainWindow::SaveMName(), TMainWindow::SaveMValue(), DialogVariables::showCustomVariableDetails(), TMainWindow::ShowNewMData(), and EditFormulaDialog::valueChanged().
height()
qreal VContainer::height () static
height return height
Returns
height in pattern units
Definition at line 690 of file vcontainer.cpp.
References _height.
Referenced by MainWindow::ChangedHeight(), MainWindow::ChangedSize(), EditLabelTemplateDialog::InitPlaceholders(), TMainWindow::InitWindow(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), MainWindow::SetDefaultHeight(), DialogPatternProperties::SetDefaultHeight(), SetHeight(), MainWindow::ShowMeasurements(), and MainWindow::SyncMeasurements().
IsUnique()
bool VContainer::IsUnique (const QString & name) static
Definition at line 585 of file vcontainer.cpp.
References builInFunctions, and uniqueNames.
Referenced by DialogTrueDarts::CheckName(), DialogCubicBezierPath::currentPointChanged(), DialogSplinePath::currentPointChanged(), DialogTool::DNumber(), VPattern::GenerateLabel(), VPattern::GenerateSuffix(), TMainWindow::GetCustomName(), DialogVariables::getCustomVariableName(), DialogTool::NamePointChanged(), DialogArc::pointNameChanged(), DialogArcWithLength::pointNameChanged(), DialogEllipticalArc::pointNameChanged(), DialogCubicBezier::PointNameChanged(), DialogSpline::PointNameChanged(), DialogVariables::saveCustomVariableName(), TMainWindow::SaveMName(), VToolOptionsPropertyBrowser::setOperationSuffix(), VToolOptionsPropertyBrowser::setPointName(), VToolOptionsPropertyBrowser::setPointName1(), VToolOptionsPropertyBrowser::setPointName2(), DialogCubicBezierPath::ShowDialog(), DialogSpline::ShowDialog(), DialogSplinePath::ShowDialog(), DialogMirrorByAxis::suffixChanged(), DialogMirrorByLine::suffixChanged(), DialogMove::suffixChanged(), and DialogRotation::suffixChanged().
lineAnglesData()
const QMap< QString, QSharedPointer< VLineAngle > > VContainer::lineAnglesData () const
Definition at line 567 of file vcontainer.cpp.
References LineAngle.
Referenced by DialogVariables::fillLineAngles(), and EditFormulaDialog::lineAngles().
lineLengthsData()
const QMap< QString, QSharedPointer< VLengthLine > > VContainer::lineLengthsData () const
Definition at line 549 of file vcontainer.cpp.
References LineLength.
Referenced by DialogVariables::fillLineLengths(), and EditFormulaDialog::lineLengths().
operator=()
VContainer & VContainer::operator= (const VContainer & data)
operator = copy constructor
Parameters
data container
Returns
copy container
Definition at line 117 of file vcontainer.cpp.
References d.
qHash()
template<class T > uint VContainer::qHash (const QSharedPointer< T > & p) private
Definition at line 362 of file vcontainer.h.
removeCustomVariable()
void VContainer::removeCustomVariable (const QString & name)
removeCustomVariable remove increment by name from increment table
Parameters
name name of existing increment
Definition at line 530 of file vcontainer.cpp.
References d.
RemovePiece()
void VContainer::RemovePiece (quint32 id)
Definition at line 487 of file vcontainer.cpp.
References d.
Referenced by QT_WARNING_POP::createUnion().
RemoveVariable()
void VContainer::RemoveVariable (const QString & name)
Definition at line 481 of file vcontainer.cpp.
References d.
Referenced by VToolAlongLine::Create(), PatternPieceTool::Create(), and VPattern::setCurrentData().
rheight()
qreal * VContainer::rheight () static
Definition at line 696 of file vcontainer.cpp.
References _height.
Referenced by MainWindow::CheckPathToMeasurements(), MainWindow::LoadPattern(), and MainWindow::OpenMeasurementFile().
rsize()
qreal * VContainer::rsize () static
Definition at line 680 of file vcontainer.cpp.
References _size.
Referenced by MainWindow::CheckPathToMeasurements(), MainWindow::LoadPattern(), and MainWindow::OpenMeasurementFile().
SetHeight()
void VContainer::SetHeight (qreal height) static
SetGrowth set value of growth.
Parameters
height value of height
Definition at line 664 of file vcontainer.cpp.
References _height, and height().
Referenced by MainWindow::LoadMeasurements(), MainWindow::SetDefaultHeight(), MainWindowsNoGUI::SetSizeHeightForIndividualM(), and MainWindow::UpdateMeasurements().
SetSize()
void VContainer::SetSize (qreal size) static
SetSize set value of size.
Parameters
size value of size
Definition at line 654 of file vcontainer.cpp.
References _size, and size().
Referenced by MainWindow::LoadMeasurements(), MainWindow::SetDefaultSize(), MainWindowsNoGUI::SetSizeHeightForIndividualM(), and MainWindow::UpdateMeasurements().
size()
qreal VContainer::size () static
size return size
Returns
size in mm
Definition at line 674 of file vcontainer.cpp.
References _size.
Referenced by MainWindow::ChangedHeight(), MainWindow::ChangedSize(), EditLabelTemplateDialog::InitPlaceholders(), TMainWindow::InitWindow(), anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders(), MainWindow::SetDefaultSize(), DialogPatternProperties::SetDefaultSize(), SetSize(), MainWindow::ShowMeasurements(), and MainWindow::SyncMeasurements().
Swap()
void VContainer::Swap (VContainer & data)
Definition at line 100 of file vcontainer.cpp.
UpdateGObject() [1/2]
template<class T > void VContainer::UpdateGObject (quint32 id, const QSharedPointer< T > & obj)
Definition at line 382 of file vcontainer.h.
References SCASSERT, uniqueNames, and UpdateObject().
UpdateGObject() [2/2]
template<class T > void VContainer::UpdateGObject (quint32 id, T * obj)
UpdateGObject update GObject by id.
Parameters
id id of existing GObject
obj object
Definition at line 374 of file vcontainer.h.
References SCASSERT.
Referenced by PointIntersectXYTool::Create(), VToolCurveIntersectAxis::Create(), VToolLineIntersectAxis::Create(), VToolEndLine::Create(), VToolHeight::Create(), VToolAlongLine::Create(), VToolPointOfIntersectionArcs::Create(), VToolCutSpline::Create(), VToolCutArc::Create(), VToolCutSplinePath::Create(), VToolPointFromArcAndTangent::Create(), VToolTriangle::Create(), IntersectCircleTangentTool::Create(), IntersectCirclesTool::Create(), VToolPointOfIntersectionCurves::Create(), VToolArc::Create(), VToolArcWithLength::Create(), VToolEllipticalArc::Create(), VToolLineIntersect::Create(), VToolNormal::Create(), VToolBisector::Create(), VToolShoulderPoint::Create(), VToolPointOfContact::Create(), VToolCubicBezier::Create(), VToolCubicBezierPath::Create(), VToolSpline::Create(), VToolSplinePath::Create(), VToolBasePoint::Create(), VToolTrueDarts::Create(), AnchorPointTool::Create(), VPattern::ParseNodeArc(), VPattern::ParseNodeEllipticalArc(), VPattern::ParseNodePoint(), VPattern::ParseNodeSpline(), VPattern::ParseNodeSplinePath(), VAbstractMirror::updateItem(), VToolRotation::updateItem(), VToolMove::updateItem(), QT_WARNING_POP::UpdateNodeArc(), QT_WARNING_POP::UpdateNodeElArc(), QT_WARNING_POP::UpdateNodePoint(), QT_WARNING_POP::UpdateNodeSpline(), QT_WARNING_POP::UpdateNodeSplinePath(), VAbstractMirror::updatePoint(), VToolRotation::updatePoint(), VToolMove::updatePoint(), and QT_WARNING_POP::updateUnionAnchors().
UpdateId()
void VContainer::UpdateId (quint32 newId) static
UpdateId update id. If new id bigger when current save new like current.
Parameters
newId id
Definition at line 269 of file vcontainer.cpp.
References _id.
Referenced by VToolLine::Create(), AnchorPointTool::Create(), VAbstractPattern::parseGroups(), UpdateObject(), UpdatePiece(), and UpdatePiecePath().
UpdateObject()
template<typename T > void VContainer::UpdateObject (const quint32 & id, const QSharedPointer< T > & point) private
UpdateObject update object in container.
Parameters
id id of existing object
point object
Definition at line 396 of file vcontainer.h.
References d, NULL_ID, SCASSERT, and UpdateId().
Referenced by UpdateGObject().
UpdatePiece()
void VContainer::UpdatePiece (quint32 id, const VPiece & piece)
Definition at line 510 of file vcontainer.cpp.
References d, NULL_ID, and UpdateId().
Referenced by AnchorPointTool::AddToFile(), VToolInternalPath::AddToFile(), PatternPieceTool::Create(), TogglePieceLock::doCmd(), TogglePieceInLayout::doCmd(), SetPieceColor::doCmd(), PatternPieceTool::insertNodes(), and PatternPieceTool::itemChange().
UpdatePiecePath()
void VContainer::UpdatePiecePath (quint32 id, const VPiecePath & path)
Definition at line 518 of file vcontainer.cpp.
References d, NULL_ID, and UpdateId().
Referenced by VToolInternalPath::Create(), QT_WARNING_POP::createUnionPaths(), SavePiecePathOptions::redo(), and SavePiecePathOptions::undo().
variablesData()
const QMap< QString, QSharedPointer< VIncrement > > VContainer::variablesData () const
Definition at line 543 of file vcontainer.cpp.
References Increment.
Referenced by EditFormulaDialog::customVariables(), MainWindow::exportToCSVData(), and DialogVariables::fillCustomVariables().
Member Data Documentation
_height
qreal VContainer::_height = 176 static private
Definition at line 234 of file vcontainer.h.
Referenced by height(), rheight(), and SetHeight().
_id
QT_WARNING_PUSH QT_WARNING_POP quint32 VContainer::_id = null_id static private
_id current id. New object will have value +1. For empty class equal 0.
Definition at line 232 of file vcontainer.h.
Referenced by Clear(), ClearForFullParse(), getId(), getNextId(), and UpdateId().
_size
qreal VContainer::_size = 50 static private
Definition at line 233 of file vcontainer.h.
Referenced by rsize(), SetSize(), and size().
d
QSharedDataPointer<VContainerData> VContainer::d private
Definition at line 237 of file vcontainer.h.
Referenced by AddGObject(), AddPiece(), AddPiecePath(), AddVariable(), Clear(), ClearCalculationGObjects(), ClearForFullParse(), ClearGObjects(), ClearVariables(), DataGObjects(), DataPieces(), DataVar(), DataVariables(), GeometricObject(), GetGObject(), GetPatternUnit(), GetPiece(), GetPiecePath(), GetTrVars(), GetVariable(), operator=(), removeCustomVariable(), RemovePiece(), RemoveVariable(), UpdateObject(), UpdatePiece(), and UpdatePiecePath().
uniqueNames
QSet< QString > VContainer::uniqueNames = QSet<QString>() static private
Definition at line 235 of file vcontainer.h.
Referenced by AddGObject(), AddVariable(), AllUniqueNames(), ClearUniqueIncrementNames(), ClearUniqueNames(), IsUnique(), and UpdateGObject().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/vcontainer.h
src/libs/vpatterndb/vcontainer.cpp