Seamly2D: ImageDialog Class Reference
ImageDialog Class Reference
#include <image_dialog.h>
Signals
void lockClicked (bool state)
void lockAspectClicked (bool state)
void imageUpdated (DraftImage image)
void applyClicked (DraftImage image)
Public Member Functions
ImageDialog (DraftImage image, qreal minDimension, qreal maxDimension, qreal pixmapWidth, qreal pixmapHeight, QWidget *parent)
virtual ~ImageDialog ()
DraftImage getImage () const
void setImage (DraftImage image)
void updateImage ()
void enableWidgets ()
QString getName () const
void setName (const QString &name)
void setOriginPoint (const int &index)
qreal getXPos () const
void setXPos (const qreal &value)
qreal getYPos () const
void setYPos (const qreal &value)
qreal getWidth () const
void setWidth (const qreal &value)
qreal getHeight () const
void setHeight (const qreal &value)
qreal getXScale () const
void setXScale (const qreal &value)
qreal getYScale () const
void setYScale (const qreal &value)
bool isAspectLocked () const
void setAspectLocked (const bool &state)
bool isLocked () const
void setLocked (const bool &state)
qreal getRotation () const
void setRotation (const qreal &value)
bool isVisible () const
void setVisibility (const bool &checked)
qreal getOpacity () const
void setOpacity (const qreal &opacity)
Private Slots
void nameChanged (const QString &name)
void originChanged (const QString &text)
void lockChanged (bool checked)
void alignmentChanged ()
void xPosChanged (qreal value)
void yPosChanged (qreal value)
void widthChanged (qreal width)
void heightChanged (qreal height)
void xScaleChanged (qreal value)
void yScaleChanged (qreal value)
void lockAspectChanged (bool checked)
void unitsChanged ()
void rotationChanged (qreal value)
void visibilityChanged (bool checked)
void opacityChanged (qreal value)
void updateUnits ()
void updateSpinboxesRanges ()
void setSuffix (QString suffix)
void setDecimals (int precision)
void dialogApply (QAbstractButton *button)
Private Attributes
Ui::ImageDialog * ui
DraftImage m_image
qreal m_pixmapWidth
qreal m_pixmapHeight
qreal m_maxDimension
qreal m_minDimension
qreal m_minOpacity
qreal m_xScale
qreal m_yScale
bool m_flagName
Detailed Description
Definition at line 48 of file image_dialog.h.
Constructor & Destructor Documentation
ImageDialog()
ImageDialog::ImageDialog (DraftImage image, qreal minDimension, qreal maxDimension, qreal pixmapWidth, qreal pixmapHeight, QWidget * parent) explicit
Definition at line 63 of file image_dialog.cpp.
References dialogApply(), DraftImage::height, heightChanged(), lockAspectChanged(), lockChanged(), m_image, m_pixmapHeight, m_pixmapWidth, nameChanged(), opacityChanged(), rotationChanged(), setXScale(), setYScale(), ui, unitsChanged(), updateImage(), updateUnits(), DraftImage::width, widthChanged(), xPosChanged(), xScaleChanged(), yPosChanged(), and yScaleChanged().
~ImageDialog()
ImageDialog::~ImageDialog () virtual
Definition at line 108 of file image_dialog.cpp.
References ui.
Member Function Documentation
alignmentChanged
void ImageDialog::alignmentChanged () private slot
Definition at line 438 of file image_dialog.cpp.
applyClicked
void ImageDialog::applyClicked (DraftImage image) signal
Referenced by ImageItem::contextMenuEvent(), and dialogApply().
dialogApply
void ImageDialog::dialogApply (QAbstractButton * button) private slot
Definition at line 802 of file image_dialog.cpp.
References applyClicked(), m_image, ui, and updateImage().
Referenced by ImageDialog().
enableWidgets()
void ImageDialog::enableWidgets ()
Definition at line 158 of file image_dialog.cpp.
References DraftImage::locked, m_image, and ui.
Referenced by lockChanged(), and updateImage().
getHeight()
qreal ImageDialog::getHeight () const
Definition at line 264 of file image_dialog.cpp.
References DraftImage::height, and m_image.
getImage()
DraftImage ImageDialog::getImage () const
Definition at line 114 of file image_dialog.cpp.
References m_image.
Referenced by ImageItem::contextMenuEvent().
getName()
QString ImageDialog::getName () const
Definition at line 175 of file image_dialog.cpp.
References m_image, and DraftImage::name.
getOpacity()
qreal ImageDialog::getOpacity () const
Definition at line 374 of file image_dialog.cpp.
References m_image, and DraftImage::opacity.
getRotation()
qreal ImageDialog::getRotation () const
Definition at line 347 of file image_dialog.cpp.
References m_image, and DraftImage::rotation.
getWidth()
qreal ImageDialog::getWidth () const
Definition at line 239 of file image_dialog.cpp.
References m_image, and DraftImage::width.
getXPos()
qreal ImageDialog::getXPos () const
Definition at line 195 of file image_dialog.cpp.
References m_image, and DraftImage::xPos.
getXScale()
qreal ImageDialog::getXScale () const
Definition at line 288 of file image_dialog.cpp.
References m_xScale.
getYPos()
qreal ImageDialog::getYPos () const
Definition at line 217 of file image_dialog.cpp.
References m_image, and DraftImage::yPos.
getYScale()
qreal ImageDialog::getYScale () const
Definition at line 302 of file image_dialog.cpp.
References m_yScale.
heightChanged
void ImageDialog::heightChanged (qreal height) private slot
Definition at line 516 of file image_dialog.cpp.
References DraftImage::aspectLocked, DraftImage::height, imageUpdated(), m_image, m_maxDimension, m_minDimension, m_pixmapHeight, m_pixmapWidth, Px, qApp, setHeight(), setWidth(), setXScale(), setYScale(), DraftImage::units, and DraftImage::width.
Referenced by ImageDialog().
imageUpdated
void ImageDialog::imageUpdated (DraftImage image) signal
Referenced by heightChanged(), opacityChanged(), originChanged(), rotationChanged(), unitsChanged(), visibilityChanged(), widthChanged(), xPosChanged(), xScaleChanged(), yPosChanged(), and yScaleChanged().
isAspectLocked()
bool ImageDialog::isAspectLocked () const
Definition at line 317 of file image_dialog.cpp.
References DraftImage::aspectLocked, and m_image.
isLocked()
bool ImageDialog::isLocked () const
Definition at line 332 of file image_dialog.cpp.
References DraftImage::locked, and m_image.
isVisible()
bool ImageDialog::isVisible () const
Definition at line 362 of file image_dialog.cpp.
References m_image, and DraftImage::visible.
lockAspectChanged
void ImageDialog::lockAspectChanged (bool checked) private slot
Definition at line 645 of file image_dialog.cpp.
References DraftImage::aspectLocked, lockAspectClicked(), m_image, and ui.
Referenced by ImageDialog().
lockAspectClicked
void ImageDialog::lockAspectClicked (bool state) signal
Referenced by lockAspectChanged().
lockChanged
void ImageDialog::lockChanged (bool checked) private slot
Definition at line 634 of file image_dialog.cpp.
References enableWidgets(), lockClicked(), DraftImage::locked, m_image, and ui.
Referenced by ImageDialog().
lockClicked
void ImageDialog::lockClicked (bool state) signal
Referenced by lockChanged().
nameChanged
void ImageDialog::nameChanged (const QString & name) private slot
Definition at line 390 of file image_dialog.cpp.
References VContainer::IsUnique(), m_image, DraftImage::name, NameRegExp(), SCASSERT, setName(), and ui.
Referenced by ImageDialog().
opacityChanged
void ImageDialog::opacityChanged (qreal value) private slot
Definition at line 741 of file image_dialog.cpp.
References imageUpdated(), m_image, m_minOpacity, and DraftImage::opacity.
Referenced by ImageDialog().
originChanged
void ImageDialog::originChanged (const QString & text) private slot
Definition at line 429 of file image_dialog.cpp.
References imageUpdated(), and m_image.
rotationChanged
void ImageDialog::rotationChanged (qreal value) private slot
Definition at line 723 of file image_dialog.cpp.
References imageUpdated(), m_image, and DraftImage::rotation.
Referenced by ImageDialog().
setAspectLocked()
void ImageDialog::setAspectLocked (const bool & state)
Definition at line 323 of file image_dialog.cpp.
References DraftImage::aspectLocked, m_image, and ui.
Referenced by updateImage().
setDecimals
void ImageDialog::setDecimals (int precision) private slot
Definition at line 793 of file image_dialog.cpp.
References ui.
Referenced by updateUnits().
setHeight()
void ImageDialog::setHeight (const qreal & value)
Definition at line 270 of file image_dialog.cpp.
References DraftImage::height, m_image, Px, qApp, ui, and DraftImage::units.
Referenced by heightChanged(), updateImage(), widthChanged(), xScaleChanged(), and yScaleChanged().
setImage()
void ImageDialog::setImage (DraftImage image)
Definition at line 119 of file image_dialog.cpp.
References m_image, and updateImage().
setLocked()
void ImageDialog::setLocked (const bool & state)
Definition at line 338 of file image_dialog.cpp.
References DraftImage::locked, m_image, and ui.
setName()
void ImageDialog::setName (const QString & name)
Definition at line 181 of file image_dialog.cpp.
References m_image, DraftImage::name, and ui.
Referenced by nameChanged().
setOpacity()
void ImageDialog::setOpacity (const qreal & opacity)
Definition at line 380 of file image_dialog.cpp.
References m_image, DraftImage::opacity, and ui.
Referenced by updateImage().
setOriginPoint()
void ImageDialog::setOriginPoint (const int & index)
Definition at line 189 of file image_dialog.cpp.
setRotation()
void ImageDialog::setRotation (const qreal & value)
Definition at line 353 of file image_dialog.cpp.
References m_image, DraftImage::rotation, and ui.
Referenced by updateImage().
setSuffix
void ImageDialog::setSuffix (QString suffix) private slot
Definition at line 785 of file image_dialog.cpp.
References ui.
Referenced by updateUnits().
setVisibility()
void ImageDialog::setVisibility (const bool & checked)
Definition at line 368 of file image_dialog.cpp.
References m_image, and DraftImage::visible.
Referenced by updateImage().
setWidth()
void ImageDialog::setWidth (const qreal & value)
Definition at line 245 of file image_dialog.cpp.
References m_image, Px, qApp, ui, DraftImage::units, and DraftImage::width.
Referenced by heightChanged(), updateImage(), widthChanged(), xScaleChanged(), and yScaleChanged().
setXPos()
void ImageDialog::setXPos (const qreal & value)
Definition at line 201 of file image_dialog.cpp.
References m_image, Px, qApp, ui, DraftImage::units, and DraftImage::xPos.
Referenced by updateImage().
setXScale()
void ImageDialog::setXScale (const qreal & value)
Definition at line 293 of file image_dialog.cpp.
References m_xScale, and ui.
Referenced by heightChanged(), ImageDialog(), widthChanged(), xScaleChanged(), and yScaleChanged().
setYPos()
void ImageDialog::setYPos (const qreal & value)
Definition at line 223 of file image_dialog.cpp.
References m_image, Px, qApp, ui, DraftImage::units, and DraftImage::yPos.
Referenced by updateImage().
setYScale()
void ImageDialog::setYScale (const qreal & value)
Definition at line 308 of file image_dialog.cpp.
References m_yScale, and ui.
Referenced by heightChanged(), ImageDialog(), widthChanged(), xScaleChanged(), and yScaleChanged().
unitsChanged
void ImageDialog::unitsChanged () private slot
Definition at line 690 of file image_dialog.cpp.
References DraftImage::height, imageUpdated(), m_image, Px, qApp, ui, DraftImage::units, updateUnits(), DraftImage::width, DraftImage::xPos, and DraftImage::yPos.
Referenced by ImageDialog().
updateImage()
void ImageDialog::updateImage ()
Definition at line 125 of file image_dialog.cpp.
References DraftImage::aspectLocked, enableWidgets(), DraftImage::filename, DraftImage::height, DraftImage::id, DraftImage::locked, m_image, DraftImage::name, DraftImage::opacity, DraftImage::order, DraftImage::rotation, setAspectLocked(), setHeight(), setOpacity(), setRotation(), setVisibility(), setWidth(), setXPos(), setYPos(), ui, DraftImage::units, DraftImage::visible, DraftImage::width, DraftImage::xPos, and DraftImage::yPos.
Referenced by dialogApply(), ImageDialog(), and setImage().
updateSpinboxesRanges
void ImageDialog::updateSpinboxesRanges () private slot
Definition at line 656 of file image_dialog.cpp.
References m_image, m_maxDimension, m_minDimension, m_pixmapHeight, m_pixmapWidth, Px, qApp, ui, and DraftImage::units.
updateUnits
void ImageDialog::updateUnits () private slot
Definition at line 754 of file image_dialog.cpp.
References Cm, Inch, m_image, Mm, Px, setDecimals(), setSuffix(), ui, and DraftImage::units.
Referenced by ImageDialog(), and unitsChanged().
visibilityChanged
void ImageDialog::visibilityChanged (bool checked) private slot
Definition at line 732 of file image_dialog.cpp.
References imageUpdated(), m_image, and DraftImage::visible.
widthChanged
void ImageDialog::widthChanged (qreal width) private slot
Definition at line 476 of file image_dialog.cpp.
References DraftImage::aspectLocked, DraftImage::height, imageUpdated(), m_image, m_maxDimension, m_minDimension, m_pixmapHeight, m_pixmapWidth, Px, qApp, setHeight(), setWidth(), setXScale(), setYScale(), DraftImage::units, and DraftImage::width.
Referenced by ImageDialog().
xPosChanged
void ImageDialog::xPosChanged (qreal value) private slot
Definition at line 444 of file image_dialog.cpp.
References imageUpdated(), m_image, Px, qApp, DraftImage::units, and DraftImage::xPos.
Referenced by ImageDialog().
xScaleChanged
void ImageDialog::xScaleChanged (qreal value) private slot
Definition at line 556 of file image_dialog.cpp.
References DraftImage::aspectLocked, imageUpdated(), m_image, m_maxDimension, m_minDimension, m_pixmapHeight, m_pixmapWidth, m_xScale, m_yScale, setHeight(), setWidth(), setXScale(), and setYScale().
Referenced by ImageDialog().
yPosChanged
void ImageDialog::yPosChanged (qreal value) private slot
Definition at line 460 of file image_dialog.cpp.
References imageUpdated(), m_image, Px, qApp, DraftImage::units, and DraftImage::yPos.
Referenced by ImageDialog().
yScaleChanged
void ImageDialog::yScaleChanged (qreal value) private slot
Definition at line 595 of file image_dialog.cpp.
References DraftImage::aspectLocked, imageUpdated(), m_image, m_maxDimension, m_minDimension, m_pixmapHeight, m_pixmapWidth, m_xScale, m_yScale, setHeight(), setWidth(), setXScale(), and setYScale().
Referenced by ImageDialog().
Member Data Documentation
m_flagName
bool ImageDialog::m_flagName private
Definition at line 142 of file image_dialog.h.
m_image
DraftImage ImageDialog::m_image private
Definition at line 134 of file image_dialog.h.
Referenced by dialogApply(), enableWidgets(), getHeight(), getImage(), getName(), getOpacity(), getRotation(), getWidth(), getXPos(), getYPos(), heightChanged(), ImageDialog(), isAspectLocked(), isLocked(), isVisible(), lockAspectChanged(), lockChanged(), nameChanged(), opacityChanged(), originChanged(), rotationChanged(), setAspectLocked(), setHeight(), setImage(), setLocked(), setName(), setOpacity(), setRotation(), setVisibility(), setWidth(), setXPos(), setYPos(), unitsChanged(), updateImage(), updateSpinboxesRanges(), updateUnits(), visibilityChanged(), widthChanged(), xPosChanged(), xScaleChanged(), yPosChanged(), and yScaleChanged().
m_maxDimension
qreal ImageDialog::m_maxDimension private
Definition at line 137 of file image_dialog.h.
Referenced by heightChanged(), updateSpinboxesRanges(), widthChanged(), xScaleChanged(), and yScaleChanged().
m_minDimension
qreal ImageDialog::m_minDimension private
Definition at line 138 of file image_dialog.h.
Referenced by heightChanged(), updateSpinboxesRanges(), widthChanged(), xScaleChanged(), and yScaleChanged().
m_minOpacity
qreal ImageDialog::m_minOpacity private
Definition at line 139 of file image_dialog.h.
Referenced by opacityChanged().
m_pixmapHeight
qreal ImageDialog::m_pixmapHeight private
Definition at line 136 of file image_dialog.h.
Referenced by heightChanged(), ImageDialog(), updateSpinboxesRanges(), widthChanged(), xScaleChanged(), and yScaleChanged().
m_pixmapWidth
qreal ImageDialog::m_pixmapWidth private
Definition at line 135 of file image_dialog.h.
Referenced by heightChanged(), ImageDialog(), updateSpinboxesRanges(), widthChanged(), xScaleChanged(), and yScaleChanged().
m_xScale
qreal ImageDialog::m_xScale private
Definition at line 140 of file image_dialog.h.
Referenced by getXScale(), setXScale(), xScaleChanged(), and yScaleChanged().
m_yScale
qreal ImageDialog::m_yScale private
Definition at line 141 of file image_dialog.h.
Referenced by getYScale(), setYScale(), xScaleChanged(), and yScaleChanged().
ui
Ui::ImageDialog* ImageDialog::ui private
Definition at line 133 of file image_dialog.h.
Referenced by dialogApply(), enableWidgets(), ImageDialog(), lockAspectChanged(), lockChanged(), nameChanged(), setAspectLocked(), setDecimals(), setHeight(), setLocked(), setName(), setOpacity(), setRotation(), setSuffix(), setWidth(), setXPos(), setXScale(), setYPos(), setYScale(), unitsChanged(), updateImage(), updateSpinboxesRanges(), updateUnits(), and ~ImageDialog().
The documentation for this class was generated from the following files:
src/libs/tools/images/image_dialog.h
src/libs/tools/images/image_dialog.cpp