Seamly2D: SchemaGrammar Class Reference
SchemaGrammar Class Reference
#include <SchemaGrammar.hpp>
Public Member Functions
SchemaGrammar (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~SchemaGrammar ()
virtual Grammar::GrammarType getGrammarType () const
virtual const XMLCh * getTargetNamespace () const
virtual XMLElementDecl * findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool &wasAdded)
virtual XMLSize_t getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual const XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope)
virtual const XMLElementDecl * getElemDecl (const unsigned int elemId) const
virtual XMLElementDecl * getElemDecl (const unsigned int elemId)
virtual const XMLNotationDecl * getNotationDecl (const XMLCh *const notName) const
virtual XMLNotationDecl * getNotationDecl (const XMLCh *const notName)
virtual bool getValidated () const
virtual XMLElementDecl * putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared=false)
virtual XMLSize_t putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared=false)
virtual XMLSize_t putNotationDecl (XMLNotationDecl *const notationDecl) const
virtual void setValidated (const bool newState)
virtual void reset ()
RefHash3KeysIdPoolEnumerator< SchemaElementDecl > getElemEnumerator () const
NameIdPoolEnumerator< XMLNotationDecl > getNotationEnumerator () const
RefHashTableOf< XMLAttDef > * getAttributeDeclRegistry () const
RefHashTableOf< ComplexTypeInfo > * getComplexTypeRegistry () const
RefHashTableOf< XercesGroupInfo > * getGroupInfoRegistry () const
RefHashTableOf< XercesAttGroupInfo > * getAttGroupInfoRegistry () const
DatatypeValidatorFactory * getDatatypeRegistry ()
RefHash2KeysTableOf< ElemVector > * getValidSubstitutionGroups () const
void setTargetNamespace (const XMLCh *const targetNamespace)
void setAttributeDeclRegistry (RefHashTableOf< XMLAttDef > *const attReg)
void setComplexTypeRegistry (RefHashTableOf< ComplexTypeInfo > *const other)
void setGroupInfoRegistry (RefHashTableOf< XercesGroupInfo > *const other)
void setAttGroupInfoRegistry (RefHashTableOf< XercesAttGroupInfo > *const other)
void setValidSubstitutionGroups (RefHash2KeysTableOf< ElemVector > *const)
virtual void setGrammarDescription (XMLGrammarDescription *)
virtual XMLGrammarDescription * getGrammarDescription () const
XMLSize_t putGroupElemDecl (XMLElementDecl *const elemDecl) const
void putAnnotation (void *key, XSAnnotation *const annotation)
void addAnnotation (XSAnnotation *const annotation)
XSAnnotation * getAnnotation (const void *const key)
const XSAnnotation * getAnnotation (const void *const key) const
XSAnnotation * getAnnotation ()
const XSAnnotation * getAnnotation () const
RefHashTableOf< XSAnnotation, PtrHasher > * getAnnotations ()
const RefHashTableOf< XSAnnotation, PtrHasher > * getAnnotations () const
unsigned int getScopeCount () const
void setScopeCount (unsigned int)
unsigned int getAnonTypeCount () const
void setAnonTypeCount (unsigned int)
SchemaGrammar (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~SchemaGrammar ()
virtual Grammar::GrammarType getGrammarType () const
virtual const XMLCh * getTargetNamespace () const
virtual XMLElementDecl * findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool &wasAdded)
virtual XMLSize_t getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual const XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope)
virtual const XMLElementDecl * getElemDecl (const unsigned int elemId) const
virtual XMLElementDecl * getElemDecl (const unsigned int elemId)
virtual const XMLNotationDecl * getNotationDecl (const XMLCh *const notName) const
virtual XMLNotationDecl * getNotationDecl (const XMLCh *const notName)
virtual bool getValidated () const
virtual XMLElementDecl * putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared=false)
virtual XMLSize_t putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared=false)
virtual XMLSize_t putNotationDecl (XMLNotationDecl *const notationDecl) const
virtual void setValidated (const bool newState)
virtual void reset ()
RefHash3KeysIdPoolEnumerator< SchemaElementDecl > getElemEnumerator () const
NameIdPoolEnumerator< XMLNotationDecl > getNotationEnumerator () const
RefHashTableOf< XMLAttDef > * getAttributeDeclRegistry () const
RefHashTableOf< ComplexTypeInfo > * getComplexTypeRegistry () const
RefHashTableOf< XercesGroupInfo > * getGroupInfoRegistry () const
RefHashTableOf< XercesAttGroupInfo > * getAttGroupInfoRegistry () const
DatatypeValidatorFactory * getDatatypeRegistry ()
RefHash2KeysTableOf< ElemVector > * getValidSubstitutionGroups () const
void setTargetNamespace (const XMLCh *const targetNamespace)
void setAttributeDeclRegistry (RefHashTableOf< XMLAttDef > *const attReg)
void setComplexTypeRegistry (RefHashTableOf< ComplexTypeInfo > *const other)
void setGroupInfoRegistry (RefHashTableOf< XercesGroupInfo > *const other)
void setAttGroupInfoRegistry (RefHashTableOf< XercesAttGroupInfo > *const other)
void setValidSubstitutionGroups (RefHash2KeysTableOf< ElemVector > *const)
virtual void setGrammarDescription (XMLGrammarDescription *)
virtual XMLGrammarDescription * getGrammarDescription () const
XMLSize_t putGroupElemDecl (XMLElementDecl *const elemDecl) const
void putAnnotation (void *key, XSAnnotation *const annotation)
void addAnnotation (XSAnnotation *const annotation)
XSAnnotation * getAnnotation (const void *const key)
const XSAnnotation * getAnnotation (const void *const key) const
XSAnnotation * getAnnotation ()
const XSAnnotation * getAnnotation () const
RefHashTableOf< XSAnnotation, PtrHasher > * getAnnotations ()
const RefHashTableOf< XSAnnotation, PtrHasher > * getAnnotations () const
unsigned int getScopeCount () const
void setScopeCount (unsigned int)
unsigned int getAnonTypeCount () const
void setAnonTypeCount (unsigned int)
SchemaGrammar (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~SchemaGrammar ()
virtual Grammar::GrammarType getGrammarType () const
virtual const XMLCh * getTargetNamespace () const
virtual XMLElementDecl * findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool &wasAdded)
virtual XMLSize_t getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual const XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope)
virtual const XMLElementDecl * getElemDecl (const unsigned int elemId) const
virtual XMLElementDecl * getElemDecl (const unsigned int elemId)
virtual const XMLNotationDecl * getNotationDecl (const XMLCh *const notName) const
virtual XMLNotationDecl * getNotationDecl (const XMLCh *const notName)
virtual bool getValidated () const
virtual XMLElementDecl * putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared=false)
virtual XMLSize_t putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared=false)
virtual XMLSize_t putNotationDecl (XMLNotationDecl *const notationDecl) const
virtual void setValidated (const bool newState)
virtual void reset ()
RefHash3KeysIdPoolEnumerator< SchemaElementDecl > getElemEnumerator () const
NameIdPoolEnumerator< XMLNotationDecl > getNotationEnumerator () const
RefHashTableOf< XMLAttDef > * getAttributeDeclRegistry () const
RefHashTableOf< ComplexTypeInfo > * getComplexTypeRegistry () const
RefHashTableOf< XercesGroupInfo > * getGroupInfoRegistry () const
RefHashTableOf< XercesAttGroupInfo > * getAttGroupInfoRegistry () const
DatatypeValidatorFactory * getDatatypeRegistry ()
RefHash2KeysTableOf< ElemVector > * getValidSubstitutionGroups () const
void setTargetNamespace (const XMLCh *const targetNamespace)
void setAttributeDeclRegistry (RefHashTableOf< XMLAttDef > *const attReg)
void setComplexTypeRegistry (RefHashTableOf< ComplexTypeInfo > *const other)
void setGroupInfoRegistry (RefHashTableOf< XercesGroupInfo > *const other)
void setAttGroupInfoRegistry (RefHashTableOf< XercesAttGroupInfo > *const other)
void setValidSubstitutionGroups (RefHash2KeysTableOf< ElemVector > *const)
virtual void setGrammarDescription (XMLGrammarDescription *)
virtual XMLGrammarDescription * getGrammarDescription () const
XMLSize_t putGroupElemDecl (XMLElementDecl *const elemDecl) const
void putAnnotation (void *key, XSAnnotation *const annotation)
void addAnnotation (XSAnnotation *const annotation)
XSAnnotation * getAnnotation (const void *const key)
const XSAnnotation * getAnnotation (const void *const key) const
XSAnnotation * getAnnotation ()
const XSAnnotation * getAnnotation () const
RefHashTableOf< XSAnnotation, PtrHasher > * getAnnotations ()
const RefHashTableOf< XSAnnotation, PtrHasher > * getAnnotations () const
unsigned int getScopeCount () const
void setScopeCount (unsigned int)
unsigned int getAnonTypeCount () const
void setAnonTypeCount (unsigned int)
Public Member Functions inherited from Grammar
virtual ~Grammar ()
virtual ~Grammar ()
virtual ~Grammar ()
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
SchemaGrammar (const SchemaGrammar &)
SchemaGrammar & operator= (const SchemaGrammar &)
void cleanUp ()
SchemaGrammar (const SchemaGrammar &)
SchemaGrammar & operator= (const SchemaGrammar &)
void cleanUp ()
SchemaGrammar (const SchemaGrammar &)
SchemaGrammar & operator= (const SchemaGrammar &)
void cleanUp ()
Private Attributes
XMLCh * fTargetNamespace
RefHash3KeysIdPool< SchemaElementDecl > * fElemDeclPool
RefHash3KeysIdPool< SchemaElementDecl > * fElemNonDeclPool
RefHash3KeysIdPool< SchemaElementDecl > * fGroupElemDeclPool
NameIdPool< XMLNotationDecl > * fNotationDeclPool
RefHashTableOf< XMLAttDef > * fAttributeDeclRegistry
RefHashTableOf< ComplexTypeInfo > * fComplexTypeRegistry
RefHashTableOf< XercesGroupInfo > * fGroupInfoRegistry
RefHashTableOf< XercesAttGroupInfo > * fAttGroupInfoRegistry
RefHash2KeysTableOf< ElemVector > * fValidSubstitutionGroups
MemoryManager * fMemoryManager
XMLSchemaDescription * fGramDesc
RefHashTableOf< XSAnnotation, PtrHasher > * fAnnotations
bool fValidated
DatatypeValidatorFactory fDatatypeRegistry
unsigned int fScopeCount
unsigned int fAnonTypeCount
Additional Inherited Members
Public Types inherited from Grammar
enum GrammarType {
DTDGrammarType , SchemaGrammarType , UnKnown , DTDGrammarType ,
SchemaGrammarType , UnKnown , DTDGrammarType , SchemaGrammarType ,
UnKnown
}
enum { UNKNOWN_SCOPE = UINT_MAX - 0 , TOP_LEVEL_SCOPE = UINT_MAX - 1 }
enum GrammarType {
DTDGrammarType , SchemaGrammarType , UnKnown , DTDGrammarType ,
SchemaGrammarType , UnKnown , DTDGrammarType , SchemaGrammarType ,
UnKnown
}
enum { UNKNOWN_SCOPE = UINT_MAX - 0 , TOP_LEVEL_SCOPE = UINT_MAX - 1 }
enum GrammarType {
DTDGrammarType , SchemaGrammarType , UnKnown , DTDGrammarType ,
SchemaGrammarType , UnKnown , DTDGrammarType , SchemaGrammarType ,
UnKnown
}
enum { UNKNOWN_SCOPE = UINT_MAX - 0 , TOP_LEVEL_SCOPE = UINT_MAX - 1 }
Static Public Member Functions inherited from Grammar
static void storeGrammar (XSerializeEngine &serEng, Grammar *const grammar)
static Grammar * loadGrammar (XSerializeEngine &serEng)
static void storeGrammar (XSerializeEngine &serEng, Grammar *const grammar)
static Grammar * loadGrammar (XSerializeEngine &serEng)
static void storeGrammar (XSerializeEngine &serEng, Grammar *const grammar)
static Grammar * loadGrammar (XSerializeEngine &serEng)
Protected Member Functions inherited from Grammar
Grammar ()
Grammar ()
Grammar ()
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 61 of file SchemaGrammar.hpp.
Constructor & Destructor Documentation
SchemaGrammar() [1/6]
SchemaGrammar::SchemaGrammar (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaGrammar() [1/3]
virtual SchemaGrammar::~SchemaGrammar () virtual
SchemaGrammar() [2/6]
SchemaGrammar::SchemaGrammar (const SchemaGrammar &) private
SchemaGrammar() [3/6]
SchemaGrammar::SchemaGrammar (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaGrammar() [2/3]
virtual SchemaGrammar::~SchemaGrammar () virtual
SchemaGrammar() [4/6]
SchemaGrammar::SchemaGrammar (const SchemaGrammar &) private
SchemaGrammar() [5/6]
SchemaGrammar::SchemaGrammar (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaGrammar() [3/3]
virtual SchemaGrammar::~SchemaGrammar () virtual
SchemaGrammar() [6/6]
SchemaGrammar::SchemaGrammar (const SchemaGrammar &) private
Member Function Documentation
addAnnotation() [1/3]
void SchemaGrammar::addAnnotation (XSAnnotation *const annotation)
Add global annotation
Note: XSAnnotation acts as a linked list
addAnnotation() [2/3]
void SchemaGrammar::addAnnotation (XSAnnotation *const annotation)
Add global annotation
Note: XSAnnotation acts as a linked list
addAnnotation() [3/3]
void SchemaGrammar::addAnnotation (XSAnnotation *const annotation)
Add global annotation
Note: XSAnnotation acts as a linked list
cleanUp() [1/3]
void SchemaGrammar::cleanUp () private
cleanUp() [2/3]
void SchemaGrammar::cleanUp () private
cleanUp() [3/3]
void SchemaGrammar::cleanUp () private
findOrAddElemDecl() [1/3]
virtual XMLElementDecl* SchemaGrammar::findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool & wasAdded) virtual
Implements Grammar.
findOrAddElemDecl() [2/3]
virtual XMLElementDecl* SchemaGrammar::findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool & wasAdded) virtual
Implements Grammar.
findOrAddElemDecl() [3/3]
virtual XMLElementDecl* SchemaGrammar::findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool & wasAdded) virtual
Implements Grammar.
getAnnotation() [1/12]
XSAnnotation * SchemaGrammar::getAnnotation () inline
Get global annotation
Definition at line 405 of file SchemaGrammar.hpp.
References fAnnotations, and RefHashTableOf< TVal, THasher >::get().
getAnnotation() [2/12]
XSAnnotation* SchemaGrammar::getAnnotation ()
Get global annotation
getAnnotation() [3/12]
XSAnnotation* SchemaGrammar::getAnnotation ()
Get global annotation
getAnnotation() [4/12]
const XSAnnotation * SchemaGrammar::getAnnotation () const inline
Definition at line 410 of file SchemaGrammar.hpp.
References fAnnotations, and RefHashTableOf< TVal, THasher >::get().
getAnnotation() [5/12]
const XSAnnotation* SchemaGrammar::getAnnotation () const
getAnnotation() [6/12]
const XSAnnotation* SchemaGrammar::getAnnotation () const
getAnnotation() [7/12]
XSAnnotation * SchemaGrammar::getAnnotation (const void *const key) inline
Retrieve the annotation that is associated with the specified key
Parameters
key represents a schema component object (i.e. SchemaGrammar)
Returns
XSAnnotation associated with the key object
Definition at line 395 of file SchemaGrammar.hpp.
References fAnnotations, and RefHashTableOf< TVal, THasher >::get().
getAnnotation() [8/12]
XSAnnotation* SchemaGrammar::getAnnotation (const void *const key)
Retrieve the annotation that is associated with the specified key
Parameters
key represents a schema component object (i.e. SchemaGrammar)
Returns
XSAnnotation associated with the key object
getAnnotation() [9/12]
XSAnnotation* SchemaGrammar::getAnnotation (const void *const key)
Retrieve the annotation that is associated with the specified key
Parameters
key represents a schema component object (i.e. SchemaGrammar)
Returns
XSAnnotation associated with the key object
getAnnotation() [10/12]
const XSAnnotation * SchemaGrammar::getAnnotation (const void *const key) const inline
Retrieve the annotation that is associated with the specified key
Parameters
key represents a schema component object (i.e. SchemaGrammar)
Returns
XSAnnotation associated with the key object
Definition at line 400 of file SchemaGrammar.hpp.
References fAnnotations, and RefHashTableOf< TVal, THasher >::get().
getAnnotation() [11/12]
const XSAnnotation* SchemaGrammar::getAnnotation (const void *const key) const
Retrieve the annotation that is associated with the specified key
Parameters
key represents a schema component object (i.e. SchemaGrammar)
Returns
XSAnnotation associated with the key object
getAnnotation() [12/12]
const XSAnnotation* SchemaGrammar::getAnnotation (const void *const key) const
Retrieve the annotation that is associated with the specified key
Parameters
key represents a schema component object (i.e. SchemaGrammar)
Returns
XSAnnotation associated with the key object
getAnnotations() [1/6]
RefHashTableOf< XSAnnotation, PtrHasher > * SchemaGrammar::getAnnotations () inline
Get annotation hash table, to enumerate through them
Definition at line 415 of file SchemaGrammar.hpp.
References fAnnotations.
getAnnotations() [2/6]
RefHashTableOf<XSAnnotation, PtrHasher>* SchemaGrammar::getAnnotations ()
Get annotation hash table, to enumerate through them
getAnnotations() [3/6]
RefHashTableOf<XSAnnotation, PtrHasher>* SchemaGrammar::getAnnotations ()
Get annotation hash table, to enumerate through them
getAnnotations() [4/6]
const RefHashTableOf< XSAnnotation, PtrHasher > * SchemaGrammar::getAnnotations () const inline
Definition at line 420 of file SchemaGrammar.hpp.
References fAnnotations.
getAnnotations() [5/6]
const RefHashTableOf<XSAnnotation, PtrHasher>* SchemaGrammar::getAnnotations () const
getAnnotations() [6/6]
const RefHashTableOf<XSAnnotation, PtrHasher>* SchemaGrammar::getAnnotations () const
getAnonTypeCount() [1/3]
unsigned int SchemaGrammar::getAnonTypeCount () const inline
Get/set anonymous type count.
Definition at line 613 of file SchemaGrammar.hpp.
References fAnonTypeCount.
getAnonTypeCount() [2/3]
unsigned int SchemaGrammar::getAnonTypeCount () const
Get/set anonymous type count.
getAnonTypeCount() [3/3]
unsigned int SchemaGrammar::getAnonTypeCount () const
Get/set anonymous type count.
getAttGroupInfoRegistry() [1/3]
RefHashTableOf< XercesAttGroupInfo > * SchemaGrammar::getAttGroupInfoRegistry () const inline
Definition at line 374 of file SchemaGrammar.hpp.
References fAttGroupInfoRegistry.
getAttGroupInfoRegistry() [2/3]
RefHashTableOf<XercesAttGroupInfo>* SchemaGrammar::getAttGroupInfoRegistry () const
getAttGroupInfoRegistry() [3/3]
RefHashTableOf<XercesAttGroupInfo>* SchemaGrammar::getAttGroupInfoRegistry () const
getAttributeDeclRegistry() [1/3]
RefHashTableOf< XMLAttDef > * SchemaGrammar::getAttributeDeclRegistry () const inline
Definition at line 356 of file SchemaGrammar.hpp.
References fAttributeDeclRegistry.
getAttributeDeclRegistry() [2/3]
RefHashTableOf<XMLAttDef>* SchemaGrammar::getAttributeDeclRegistry () const
getAttributeDeclRegistry() [3/3]
RefHashTableOf<XMLAttDef>* SchemaGrammar::getAttributeDeclRegistry () const
getComplexTypeRegistry() [1/3]
RefHashTableOf< ComplexTypeInfo > * SchemaGrammar::getComplexTypeRegistry () const inline
Definition at line 362 of file SchemaGrammar.hpp.
References fComplexTypeRegistry.
getComplexTypeRegistry() [2/3]
RefHashTableOf<ComplexTypeInfo>* SchemaGrammar::getComplexTypeRegistry () const
getComplexTypeRegistry() [3/3]
RefHashTableOf<ComplexTypeInfo>* SchemaGrammar::getComplexTypeRegistry () const
getDatatypeRegistry() [1/3]
DatatypeValidatorFactory * SchemaGrammar::getDatatypeRegistry () inline
Definition at line 379 of file SchemaGrammar.hpp.
References fDatatypeRegistry.
getDatatypeRegistry() [2/3]
DatatypeValidatorFactory* SchemaGrammar::getDatatypeRegistry ()
getDatatypeRegistry() [3/3]
DatatypeValidatorFactory* SchemaGrammar::getDatatypeRegistry ()
getElemDecl() [1/12]
XMLElementDecl * SchemaGrammar::getElemDecl (const unsigned int elemId) inline virtual
Implements Grammar.
Definition at line 544 of file SchemaGrammar.hpp.
References fElemDeclPool, fGroupElemDeclPool, and RefHash3KeysIdPool< TVal, THasher >::getById().
getElemDecl() [2/12]
virtual XMLElementDecl* SchemaGrammar::getElemDecl (const unsigned int elemId) virtual
Implements Grammar.
getElemDecl() [3/12]
virtual XMLElementDecl* SchemaGrammar::getElemDecl (const unsigned int elemId) virtual
Implements Grammar.
getElemDecl() [4/12]
const XMLElementDecl * SchemaGrammar::getElemDecl (const unsigned int elemId) const inline virtual
Implements Grammar.
Definition at line 533 of file SchemaGrammar.hpp.
References fElemDeclPool, fGroupElemDeclPool, and RefHash3KeysIdPool< TVal, THasher >::getById().
getElemDecl() [5/12]
virtual const XMLElementDecl* SchemaGrammar::getElemDecl (const unsigned int elemId) const virtual
Implements Grammar.
getElemDecl() [6/12]
virtual const XMLElementDecl* SchemaGrammar::getElemDecl (const unsigned int elemId) const virtual
Implements Grammar.
getElemDecl() [7/12]
XMLElementDecl * SchemaGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) inline virtual
Implements Grammar.
Definition at line 515 of file SchemaGrammar.hpp.
References fElemDeclPool, fElemNonDeclPool, fGroupElemDeclPool, and RefHash3KeysIdPool< TVal, THasher >::getByKey().
getElemDecl() [8/12]
virtual XMLElementDecl* SchemaGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) virtual
Implements Grammar.
getElemDecl() [9/12]
virtual XMLElementDecl* SchemaGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) virtual
Implements Grammar.
getElemDecl() [10/12]
const XMLElementDecl * SchemaGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const inline virtual
Implements Grammar.
Definition at line 497 of file SchemaGrammar.hpp.
References fElemDeclPool, fElemNonDeclPool, fGroupElemDeclPool, and RefHash3KeysIdPool< TVal, THasher >::getByKey().
getElemDecl() [11/12]
virtual const XMLElementDecl* SchemaGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const virtual
Implements Grammar.
getElemDecl() [12/12]
virtual const XMLElementDecl* SchemaGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const virtual
Implements Grammar.
getElemEnumerator() [1/3]
RefHash3KeysIdPoolEnumerator< SchemaElementDecl > SchemaGrammar::getElemEnumerator () const inline
Definition at line 345 of file SchemaGrammar.hpp.
References fElemDeclPool, and fMemoryManager.
getElemEnumerator() [2/3]
RefHash3KeysIdPoolEnumerator<SchemaElementDecl> SchemaGrammar::getElemEnumerator () const
getElemEnumerator() [3/3]
RefHash3KeysIdPoolEnumerator<SchemaElementDecl> SchemaGrammar::getElemEnumerator () const
getElemId() [1/3]
XMLSize_t SchemaGrammar::getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const inline virtual
Implements Grammar.
Definition at line 477 of file SchemaGrammar.hpp.
References fElemDeclPool, XMLElementDecl::fgInvalidElemId, fGroupElemDeclPool, RefHash3KeysIdPool< TVal, THasher >::getByKey(), and XMLElementDecl::getId().
getElemId() [2/3]
virtual XMLSize_t SchemaGrammar::getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const virtual
Implements Grammar.
getElemId() [3/3]
virtual XMLSize_t SchemaGrammar::getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const virtual
Implements Grammar.
getGrammarDescription() [1/3]
XMLGrammarDescription * SchemaGrammar::getGrammarDescription () const inline virtual
Implements Grammar.
Definition at line 390 of file SchemaGrammar.hpp.
References fGramDesc.
getGrammarDescription() [2/3]
virtual XMLGrammarDescription* SchemaGrammar::getGrammarDescription () const virtual
Implements Grammar.
getGrammarDescription() [3/3]
virtual XMLGrammarDescription* SchemaGrammar::getGrammarDescription () const virtual
Implements Grammar.
getGrammarType() [1/3]
Grammar::GrammarType SchemaGrammar::getGrammarType () const inline virtual
Implements Grammar.
Definition at line 468 of file SchemaGrammar.hpp.
References Grammar::SchemaGrammarType.
getGrammarType() [2/3]
virtual Grammar::GrammarType SchemaGrammar::getGrammarType () const virtual
Implements Grammar.
getGrammarType() [3/3]
virtual Grammar::GrammarType SchemaGrammar::getGrammarType () const virtual
Implements Grammar.
getGroupInfoRegistry() [1/3]
RefHashTableOf< XercesGroupInfo > * SchemaGrammar::getGroupInfoRegistry () const inline
Definition at line 368 of file SchemaGrammar.hpp.
References fGroupInfoRegistry.
getGroupInfoRegistry() [2/3]
RefHashTableOf<XercesGroupInfo>* SchemaGrammar::getGroupInfoRegistry () const
getGroupInfoRegistry() [3/3]
RefHashTableOf<XercesGroupInfo>* SchemaGrammar::getGroupInfoRegistry () const
getNotationDecl() [1/6]
XMLNotationDecl * SchemaGrammar::getNotationDecl (const XMLCh *const notName) inline virtual
Implements Grammar.
Definition at line 580 of file SchemaGrammar.hpp.
References fNotationDeclPool, and NameIdPool< TElem >::getByKey().
getNotationDecl() [2/6]
virtual XMLNotationDecl* SchemaGrammar::getNotationDecl (const XMLCh *const notName) virtual
Implements Grammar.
getNotationDecl() [3/6]
virtual XMLNotationDecl* SchemaGrammar::getNotationDecl (const XMLCh *const notName) virtual
Implements Grammar.
getNotationDecl() [4/6]
const XMLNotationDecl * SchemaGrammar::getNotationDecl (const XMLCh *const notName) const inline virtual
Implements Grammar.
Definition at line 575 of file SchemaGrammar.hpp.
References fNotationDeclPool, and NameIdPool< TElem >::getByKey().
getNotationDecl() [5/6]
virtual const XMLNotationDecl* SchemaGrammar::getNotationDecl (const XMLCh *const notName) const virtual
Implements Grammar.
getNotationDecl() [6/6]
virtual const XMLNotationDecl* SchemaGrammar::getNotationDecl (const XMLCh *const notName) const virtual
Implements Grammar.
getNotationEnumerator() [1/3]
NameIdPoolEnumerator< XMLNotationDecl > SchemaGrammar::getNotationEnumerator () const inline
Definition at line 351 of file SchemaGrammar.hpp.
References fMemoryManager, and fNotationDeclPool.
getNotationEnumerator() [2/3]
NameIdPoolEnumerator<XMLNotationDecl> SchemaGrammar::getNotationEnumerator () const
getNotationEnumerator() [3/3]
NameIdPoolEnumerator<XMLNotationDecl> SchemaGrammar::getNotationEnumerator () const
getScopeCount() [1/3]
unsigned int SchemaGrammar::getScopeCount () const inline
Get/set scope count.
Definition at line 601 of file SchemaGrammar.hpp.
References fScopeCount.
getScopeCount() [2/3]
unsigned int SchemaGrammar::getScopeCount () const
Get/set scope count.
getScopeCount() [3/3]
unsigned int SchemaGrammar::getScopeCount () const
Get/set scope count.
getTargetNamespace() [1/3]
const XMLCh * SchemaGrammar::getTargetNamespace () const inline virtual
Implements Grammar.
Definition at line 472 of file SchemaGrammar.hpp.
References fTargetNamespace.
getTargetNamespace() [2/3]
virtual const XMLCh* SchemaGrammar::getTargetNamespace () const virtual
Implements Grammar.
getTargetNamespace() [3/3]
virtual const XMLCh* SchemaGrammar::getTargetNamespace () const virtual
Implements Grammar.
getValidated() [1/3]
bool SchemaGrammar::getValidated () const inline virtual
Implements Grammar.
Definition at line 590 of file SchemaGrammar.hpp.
References fValidated.
getValidated() [2/3]
virtual bool SchemaGrammar::getValidated () const virtual
Implements Grammar.
getValidated() [3/3]
virtual bool SchemaGrammar::getValidated () const virtual
Implements Grammar.
getValidSubstitutionGroups() [1/3]
RefHash2KeysTableOf< ElemVector > * SchemaGrammar::getValidSubstitutionGroups () const inline
Definition at line 385 of file SchemaGrammar.hpp.
References fValidSubstitutionGroups.
getValidSubstitutionGroups() [2/3]
RefHash2KeysTableOf<ElemVector>* SchemaGrammar::getValidSubstitutionGroups () const
getValidSubstitutionGroups() [3/3]
RefHash2KeysTableOf<ElemVector>* SchemaGrammar::getValidSubstitutionGroups () const
operator=() [1/3]
SchemaGrammar& SchemaGrammar::operator= (const SchemaGrammar &) private
operator=() [2/3]
SchemaGrammar& SchemaGrammar::operator= (const SchemaGrammar &) private
operator=() [3/3]
SchemaGrammar& SchemaGrammar::operator= (const SchemaGrammar &) private
putAnnotation() [1/3]
void SchemaGrammar::putAnnotation (void * key, XSAnnotation *const annotation)
Add annotation to the list of annotations for a given key
putAnnotation() [2/3]
void SchemaGrammar::putAnnotation (void * key, XSAnnotation *const annotation)
Add annotation to the list of annotations for a given key
putAnnotation() [3/3]
void SchemaGrammar::putAnnotation (void * key, XSAnnotation *const annotation)
Add annotation to the list of annotations for a given key
putElemDecl() [1/6]
virtual XMLElementDecl* SchemaGrammar::putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared = false) virtual
Implements Grammar.
putElemDecl() [2/6]
virtual XMLElementDecl* SchemaGrammar::putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared = false) virtual
Implements Grammar.
putElemDecl() [3/6]
virtual XMLElementDecl* SchemaGrammar::putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared = false) virtual
Implements Grammar.
putElemDecl() [4/6]
XMLSize_t SchemaGrammar::putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared = false) inline virtual
Implements Grammar.
Definition at line 556 of file SchemaGrammar.hpp.
References fElemDeclPool, fElemNonDeclPool, fMemoryManager, XMLElementDecl::getBaseName(), XMLElementDecl::getURI(), and RefHash3KeysIdPool< TVal, THasher >::put().
putElemDecl() [5/6]
virtual XMLSize_t SchemaGrammar::putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared = false) virtual
Implements Grammar.
putElemDecl() [6/6]
virtual XMLSize_t SchemaGrammar::putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared = false) virtual
Implements Grammar.
putGroupElemDecl() [1/3]
XMLSize_t SchemaGrammar::putGroupElemDecl (XMLElementDecl *const elemDecl) const inline
Definition at line 569 of file SchemaGrammar.hpp.
References fGroupElemDeclPool, XMLElementDecl::getBaseName(), XMLElementDecl::getURI(), and RefHash3KeysIdPool< TVal, THasher >::put().
putGroupElemDecl() [2/3]
XMLSize_t SchemaGrammar::putGroupElemDecl (XMLElementDecl *const elemDecl) const
putGroupElemDecl() [3/3]
XMLSize_t SchemaGrammar::putGroupElemDecl (XMLElementDecl *const elemDecl) const
putNotationDecl() [1/3]
XMLSize_t SchemaGrammar::putNotationDecl (XMLNotationDecl *const notationDecl) const inline virtual
Implements Grammar.
Definition at line 585 of file SchemaGrammar.hpp.
References fNotationDeclPool, and NameIdPool< TElem >::put().
putNotationDecl() [2/3]
virtual XMLSize_t SchemaGrammar::putNotationDecl (XMLNotationDecl *const notationDecl) const virtual
Implements Grammar.
putNotationDecl() [3/3]
virtual XMLSize_t SchemaGrammar::putNotationDecl (XMLNotationDecl *const notationDecl) const virtual
Implements Grammar.
reset() [1/3]
virtual void SchemaGrammar::reset () virtual
Implements Grammar.
reset() [2/3]
virtual void SchemaGrammar::reset () virtual
Implements Grammar.
reset() [3/3]
virtual void SchemaGrammar::reset () virtual
Implements Grammar.
setAnonTypeCount() [1/3]
void SchemaGrammar::setAnonTypeCount (unsigned int count) inline
Definition at line 619 of file SchemaGrammar.hpp.
References fAnonTypeCount.
setAnonTypeCount() [2/3]
void SchemaGrammar::setAnonTypeCount (unsigned int)
setAnonTypeCount() [3/3]
void SchemaGrammar::setAnonTypeCount (unsigned int)
setAttGroupInfoRegistry() [1/3]
void SchemaGrammar::setAttGroupInfoRegistry (RefHashTableOf< XercesAttGroupInfo > *const other) inline
Definition at line 453 of file SchemaGrammar.hpp.
References fAttGroupInfoRegistry.
setAttGroupInfoRegistry() [2/3]
void SchemaGrammar::setAttGroupInfoRegistry (RefHashTableOf< XercesAttGroupInfo > *const other)
setAttGroupInfoRegistry() [3/3]
void SchemaGrammar::setAttGroupInfoRegistry (RefHashTableOf< XercesAttGroupInfo > *const other)
setAttributeDeclRegistry() [1/3]
void SchemaGrammar::setAttributeDeclRegistry (RefHashTableOf< XMLAttDef > *const attReg) inline
Definition at line 435 of file SchemaGrammar.hpp.
References fAttributeDeclRegistry.
setAttributeDeclRegistry() [2/3]
void SchemaGrammar::setAttributeDeclRegistry (RefHashTableOf< XMLAttDef > *const attReg)
setAttributeDeclRegistry() [3/3]
void SchemaGrammar::setAttributeDeclRegistry (RefHashTableOf< XMLAttDef > *const attReg)
setComplexTypeRegistry() [1/3]
void SchemaGrammar::setComplexTypeRegistry (RefHashTableOf< ComplexTypeInfo > *const other) inline
Definition at line 441 of file SchemaGrammar.hpp.
References fComplexTypeRegistry.
setComplexTypeRegistry() [2/3]
void SchemaGrammar::setComplexTypeRegistry (RefHashTableOf< ComplexTypeInfo > *const other)
setComplexTypeRegistry() [3/3]
void SchemaGrammar::setComplexTypeRegistry (RefHashTableOf< ComplexTypeInfo > *const other)
setGrammarDescription() [1/3]
virtual void SchemaGrammar::setGrammarDescription (XMLGrammarDescription *) virtual
Implements Grammar.
setGrammarDescription() [2/3]
virtual void SchemaGrammar::setGrammarDescription (XMLGrammarDescription *) virtual
Implements Grammar.
setGrammarDescription() [3/3]
virtual void SchemaGrammar::setGrammarDescription (XMLGrammarDescription *) virtual
Implements Grammar.
setGroupInfoRegistry() [1/3]
void SchemaGrammar::setGroupInfoRegistry (RefHashTableOf< XercesGroupInfo > *const other) inline
Definition at line 447 of file SchemaGrammar.hpp.
References fGroupInfoRegistry.
setGroupInfoRegistry() [2/3]
void SchemaGrammar::setGroupInfoRegistry (RefHashTableOf< XercesGroupInfo > *const other)
setGroupInfoRegistry() [3/3]
void SchemaGrammar::setGroupInfoRegistry (RefHashTableOf< XercesGroupInfo > *const other)
setScopeCount() [1/3]
void SchemaGrammar::setScopeCount (unsigned int scopeCount) inline
Definition at line 607 of file SchemaGrammar.hpp.
References fScopeCount.
setScopeCount() [2/3]
void SchemaGrammar::setScopeCount (unsigned int)
setScopeCount() [3/3]
void SchemaGrammar::setScopeCount (unsigned int)
setTargetNamespace() [1/3]
void SchemaGrammar::setTargetNamespace (const XMLCh *const targetNamespace) inline
Definition at line 427 of file SchemaGrammar.hpp.
References MemoryManager::deallocate(), fMemoryManager, fTargetNamespace, and XMLString::replicate().
setTargetNamespace() [2/3]
void SchemaGrammar::setTargetNamespace (const XMLCh *const targetNamespace)
setTargetNamespace() [3/3]
void SchemaGrammar::setTargetNamespace (const XMLCh *const targetNamespace)
setValidated() [1/3]
void SchemaGrammar::setValidated (const bool newState) inline virtual
Implements Grammar.
Definition at line 595 of file SchemaGrammar.hpp.
References fValidated.
setValidated() [2/3]
virtual void SchemaGrammar::setValidated (const bool newState) virtual
Implements Grammar.
setValidated() [3/3]
virtual void SchemaGrammar::setValidated (const bool newState) virtual
Implements Grammar.
setValidSubstitutionGroups() [1/3]
void SchemaGrammar::setValidSubstitutionGroups (RefHash2KeysTableOf< ElemVector > * const other) inline
Definition at line 459 of file SchemaGrammar.hpp.
References fValidSubstitutionGroups.
setValidSubstitutionGroups() [2/3]
void SchemaGrammar::setValidSubstitutionGroups (RefHash2KeysTableOf< ElemVector > * const)
setValidSubstitutionGroups() [3/3]
void SchemaGrammar::setValidSubstitutionGroups (RefHash2KeysTableOf< ElemVector > * const)
Member Data Documentation
fAnnotations
RefHashTableOf< XSAnnotation, PtrHasher > * SchemaGrammar::fAnnotations private
Definition at line 331 of file SchemaGrammar.hpp.
Referenced by getAnnotation(), and getAnnotations().
fAnonTypeCount
unsigned int SchemaGrammar::fAnonTypeCount private
Definition at line 337 of file SchemaGrammar.hpp.
Referenced by getAnonTypeCount(), and setAnonTypeCount().
fAttGroupInfoRegistry
RefHashTableOf< XercesAttGroupInfo > * SchemaGrammar::fAttGroupInfoRegistry private
Definition at line 327 of file SchemaGrammar.hpp.
Referenced by getAttGroupInfoRegistry(), and setAttGroupInfoRegistry().
fAttributeDeclRegistry
RefHashTableOf< XMLAttDef > * SchemaGrammar::fAttributeDeclRegistry private
Definition at line 324 of file SchemaGrammar.hpp.
Referenced by getAttributeDeclRegistry(), and setAttributeDeclRegistry().
fComplexTypeRegistry
RefHashTableOf< ComplexTypeInfo > * SchemaGrammar::fComplexTypeRegistry private
Definition at line 325 of file SchemaGrammar.hpp.
Referenced by getComplexTypeRegistry(), and setComplexTypeRegistry().
fDatatypeRegistry
DatatypeValidatorFactory SchemaGrammar::fDatatypeRegistry private
Definition at line 334 of file SchemaGrammar.hpp.
Referenced by getDatatypeRegistry().
fElemDeclPool
RefHash3KeysIdPool< SchemaElementDecl > * SchemaGrammar::fElemDeclPool private
Definition at line 320 of file SchemaGrammar.hpp.
Referenced by getElemDecl(), getElemEnumerator(), getElemId(), and putElemDecl().
fElemNonDeclPool
RefHash3KeysIdPool< SchemaElementDecl > * SchemaGrammar::fElemNonDeclPool private
Definition at line 321 of file SchemaGrammar.hpp.
Referenced by getElemDecl(), and putElemDecl().
fGramDesc
XMLSchemaDescription * SchemaGrammar::fGramDesc private
Definition at line 330 of file SchemaGrammar.hpp.
Referenced by getGrammarDescription().
fGroupElemDeclPool
RefHash3KeysIdPool< SchemaElementDecl > * SchemaGrammar::fGroupElemDeclPool private
Definition at line 322 of file SchemaGrammar.hpp.
Referenced by getElemDecl(), getElemId(), and putGroupElemDecl().
fGroupInfoRegistry
RefHashTableOf< XercesGroupInfo > * SchemaGrammar::fGroupInfoRegistry private
Definition at line 326 of file SchemaGrammar.hpp.
Referenced by getGroupInfoRegistry(), and setGroupInfoRegistry().
fMemoryManager
MemoryManager * SchemaGrammar::fMemoryManager private
Definition at line 329 of file SchemaGrammar.hpp.
Referenced by getElemEnumerator(), getNotationEnumerator(), putElemDecl(), and setTargetNamespace().
fNotationDeclPool
NameIdPool< XMLNotationDecl > * SchemaGrammar::fNotationDeclPool private
Definition at line 323 of file SchemaGrammar.hpp.
Referenced by getNotationDecl(), getNotationEnumerator(), and putNotationDecl().
fScopeCount
unsigned int SchemaGrammar::fScopeCount private
Definition at line 336 of file SchemaGrammar.hpp.
Referenced by getScopeCount(), and setScopeCount().
fTargetNamespace
XMLCh * SchemaGrammar::fTargetNamespace private
Definition at line 319 of file SchemaGrammar.hpp.
Referenced by getTargetNamespace(), and setTargetNamespace().
fValidated
bool SchemaGrammar::fValidated private
Definition at line 333 of file SchemaGrammar.hpp.
Referenced by getValidated(), and setValidated().
fValidSubstitutionGroups
RefHash2KeysTableOf< ElemVector > * SchemaGrammar::fValidSubstitutionGroups private
Definition at line 328 of file SchemaGrammar.hpp.
Referenced by getValidSubstitutionGroups(), and setValidSubstitutionGroups().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/SchemaGrammar.hpp