Seamly2D: src/libs/vtools/tools/drawTools/operation/vabstractoperation.h File Reference
vabstractoperation.h File Reference
#include <QtGlobal>
#include <qcompilerdetection.h>
#include <QMap>
#include <QMetaObject>
#include <QObject>
#include <QString>
#include <QVector>
#include <QGraphicsLineItem>
#include "../vdrawtool.h"
#include "../vwidgets/vsimplecurve.h"
#include "../vwidgets/vsimplepoint.h"
Classes
struct SourceItem
struct DestinationItem
class VAbstractOperation
Functions
Q_DECLARE_TYPEINFO (SourceItem, Q_MOVABLE_TYPE)
QVector< quint32 > sourceToObjects (const QVector< SourceItem > &source)
Function Documentation
Q_DECLARE_TYPEINFO()
Q_DECLARE_TYPEINFO (SourceItem , Q_MOVABLE_TYPE)
sourceToObjects()
QVector<quint32> sourceToObjects (const QVector< SourceItem > & source)
Definition at line 63 of file vabstractoperation.cpp.
Referenced by DialogRotation::ChosenObject(), DialogMirrorByAxis::SaveData(), DialogMirrorByLine::SaveData(), DialogMove::SaveData(), DialogRotation::SaveData(), DialogMirrorByAxis::setSourceObjects(), DialogMirrorByLine::setSourceObjects(), DialogMove::setSourceObjects(), DialogRotation::setSourceObjects(), VToolMirrorByAxis::SetVisualization(), VToolMirrorByLine::SetVisualization(), VToolMove::SetVisualization(), VToolRotation::SetVisualization(), DialogMirrorByAxis::ShowDialog(), DialogMirrorByLine::ShowDialog(), DialogMove::ShowDialog(), and DialogRotation::ShowDialog().