Seamly2D: MoveAbstractLabel Class Reference
MoveAbstractLabel Class Reference abstract
#include <moveabstractlabel.h>
Public Member Functions
MoveAbstractLabel (VAbstractPattern *doc, quint32 pointId, const QPointF &pos, QUndoCommand *parent=nullptr)
virtual ~MoveAbstractLabel ()=default
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
quint32 GetPointId () const
QPointF GetNewPos () const
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Protected Member Functions
virtual void Do (const QPointF &pos)=0
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes
QPointF m_oldPos
QPointF m_newPos
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Detailed Description
Definition at line 65 of file moveabstractlabel.h.
Constructor & Destructor Documentation
MoveAbstractLabel()
MoveAbstractLabel::MoveAbstractLabel (VAbstractPattern * doc, quint32 pointId, const QPointF & pos, QUndoCommand * parent = nullptr)
Definition at line 62 of file moveabstractlabel.cpp.
References m_newPos, and VUndoCommand::nodeId.
~MoveAbstractLabel()
virtual MoveAbstractLabel::~MoveAbstractLabel () virtual default
Member Function Documentation
Do()
virtual void MoveAbstractLabel::Do (const QPointF & pos) protected pure virtual
Implemented in MoveOperationLabel, MoveLabel, and MoveDoubleLabel.
Referenced by redo(), and undo().
GetNewPos()
QPointF MoveAbstractLabel::GetNewPos () const inline
Definition at line 96 of file moveabstractlabel.h.
References m_newPos.
Referenced by MoveDoubleLabel::mergeWith(), MoveLabel::mergeWith(), and MoveOperationLabel::mergeWith().
GetPointId()
quint32 MoveAbstractLabel::GetPointId () const inline
Definition at line 90 of file moveabstractlabel.h.
References VUndoCommand::nodeId.
Referenced by MoveDoubleLabel::mergeWith(), MoveLabel::mergeWith(), and MoveOperationLabel::mergeWith().
redo()
void MoveAbstractLabel::redo () virtual
Definition at line 81 of file moveabstractlabel.cpp.
References Do(), and m_newPos.
undo()
void MoveAbstractLabel::undo () virtual
Definition at line 73 of file moveabstractlabel.cpp.
References Do(), and m_oldPos.
Member Data Documentation
m_newPos
QPointF MoveAbstractLabel::m_newPos protected
Definition at line 81 of file moveabstractlabel.h.
Referenced by GetNewPos(), MoveDoubleLabel::mergeWith(), MoveLabel::mergeWith(), MoveOperationLabel::mergeWith(), MoveAbstractLabel(), and redo().
m_oldPos
QPointF MoveAbstractLabel::m_oldPos protected
Definition at line 80 of file moveabstractlabel.h.
Referenced by MoveDoubleLabel::MoveDoubleLabel(), MoveLabel::MoveLabel(), MoveOperationLabel::MoveOperationLabel(), and undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/label/moveabstractlabel.h
src/libs/vtools/undocommands/label/moveabstractlabel.cpp