Seamly2D: VAbstractMConverter Class Reference
VAbstractMConverter Class Reference
#include <vabstractmconverter.h>
Public Member Functions
VAbstractMConverter (const QString &fileName)
virtual ~VAbstractMConverter () Q_DECL_EQ_DEFAULT
Public Member Functions inherited from VAbstractConverter
VAbstractConverter (const QString &fileName)
virtual ~VAbstractConverter () Q_DECL_EQ_DEFAULT
QString Convert ()
int GetCurrentFormatVarsion () const
QString GetVersionStr () const
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit MUnit () const
virtual void setXMLContent (const QString &fileName)
virtual bool SaveDocument (const QString &fileName, QString &error)
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Protected Member Functions
void AddRootComment ()
Protected Member Functions inherited from VAbstractConverter
void ValidateInputFile (const QString &currentSchema) const
Q_NORETURN void InvalidVersion (int ver) const
void Save ()
void SetVersion (const QString &version)
virtual int MinVer () const =0
virtual int MaxVer () const =0
virtual QString MinVerStr () const =0
virtual QString MaxVerStr () const =0
virtual QString XSDSchema (int ver) const =0
virtual void ApplyPatches ()=0
virtual void DowngradeToCurrentMaxVersion ()=0
virtual bool IsReadOnly () const =0
void Replace (QString &formula, const QString &newName, int position, const QString &token, int &bias) const
void CorrectionsPositions (int position, int bias, QMap< int, QString > &tokens) const
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Static Protected Member Functions
static QMultiMap< QString, QString > OldNamesToNewNames_InV0_3_0 ()
static QMap< QString, QString > OldNamesToNewNames_InV0_3_3 ()
Static Protected Member Functions inherited from VAbstractConverter
static void BiasTokens (int position, int bias, QMap< int, QString > &tokens)
Additional Inherited Members
Static Public Member Functions inherited from VAbstractConverter
static int GetVersion (const QString &version)
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Protected Attributes inherited from VAbstractConverter
int m_ver
QString m_convertedFileName
Detailed Description
Definition at line 64 of file vabstractmconverter.h.
Constructor & Destructor Documentation
VAbstractMConverter()
VAbstractMConverter::VAbstractMConverter (const QString & fileName) explicit
Definition at line 63 of file vabstractmconverter.cpp.
~VAbstractMConverter()
virtual VAbstractMConverter::~VAbstractMConverter () virtual
Member Function Documentation
AddRootComment()
void VAbstractMConverter::AddRootComment () protected
Definition at line 69 of file vabstractmconverter.cpp.
Referenced by VVITConverter::ToV0_3_0(), and VVSTConverter::ToV0_4_0().
OldNamesToNewNames_InV0_3_0()
QMultiMap< QString, QString > VAbstractMConverter::OldNamesToNewNames_InV0_3_0 () static protected
Definition at line 79 of file vabstractmconverter.cpp.
Referenced by VVITConverter::ConvertMeasurementsToV0_3_0(), and VVSTConverter::ConvertMeasurementsToV0_4_0().
OldNamesToNewNames_InV0_3_3()
QMap< QString, QString > VAbstractMConverter::OldNamesToNewNames_InV0_3_3 () static protected
Definition at line 266 of file vabstractmconverter.cpp.
Referenced by VVITConverter::ConvertMeasurementsToV0_3_3(), and VVSTConverter::ConvertMeasurementsToV0_4_2().
The documentation for this class was generated from the following files:
src/libs/ifc/xml/vabstractmconverter.h
src/libs/ifc/xml/vabstractmconverter.cpp