Seamly2D: VisToolCubicBezierPath Class Reference
VisToolCubicBezierPath Class Reference
#include <vistoolcubicbezierpath.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolCubicBezierPath) }
Public Types inherited from VisPath
enum { Type = UserType + static_cast<int>(Vis::Path) }
Public Types inherited from VCurvePathItem
enum { Type = UserType + static_cast<int>(Vis::CurvePathItem) }
Public Member Functions
VisToolCubicBezierPath (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolCubicBezierPath ()
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setPath (const VCubicBezierPath &value)
VCubicBezierPath getPath ()
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisPath
VisPath (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisPath ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VCurvePathItem
VCurvePathItem (QGraphicsItem *parent=nullptr)
virtual ~VCurvePathItem ()=default
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
void SetDirectionArrows (const QVector< QPair< QLineF, QLineF >> &arrows)
void SetPoints (const QVector< QPointF > &points)
Protected Attributes
QVector< VScaledEllipse * > mainPoints
QVector< VScaledEllipse * > ctrlPoints
QVector< VScaledLine * > lines
VCurvePathItem * newCurveSegment
VCubicBezierPath path
VScaledLine * helpLine1
VScaledLine * helpLine2
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Private Member Functions
VScaledEllipse * getPoint (QVector< VScaledEllipse * > &points, quint32 i, qreal z=0)
VScaledLine * getLine (quint32 i)
void Creating (const QVector< VPointF > &pathPoints, int pointsLeft)
void RefreshToolTip ()
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisPath
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
VSimplePoint * GetPoint (QVector< VSimplePoint * > &points, quint32 i, const QColor &color)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Protected Member Functions inherited from VCurvePathItem
virtual void ScalePenWidth ()
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Detailed Description
Definition at line 67 of file vistoolcubicbezierpath.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 80 of file vistoolcubicbezierpath.h.
Constructor & Destructor Documentation
VisToolCubicBezierPath()
VisToolCubicBezierPath::VisToolCubicBezierPath (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 70 of file vistoolcubicbezierpath.cpp.
References helpLine1, helpLine2, Visualization::mainColor, and newCurveSegment.
~VisToolCubicBezierPath()
VisToolCubicBezierPath::~VisToolCubicBezierPath () virtual
Definition at line 87 of file vistoolcubicbezierpath.cpp.
References lines, and mainPoints.
Member Function Documentation
Creating()
void VisToolCubicBezierPath::Creating (const QVector< VPointF > & pathPoints, int pointsLeft) private
Definition at line 199 of file vistoolcubicbezierpath.cpp.
References VCubicBezierPath::CountSubSpl(), ctrlPoints, Visualization::DrawLine(), Visualization::DrawPath(), Visualization::DrawPoint(), VAbstractCurve::GetPath(), getPoint(), helpLine1, helpLine2, Visualization::lineWeight, Visualization::mainColor, newCurveSegment, Visualization::scenePos, and VCubicBezierPath::SubSplPointsCount().
Referenced by RefreshGeometry().
getLine()
VScaledLine * VisToolCubicBezierPath::getLine (quint32 i) private
Definition at line 183 of file vistoolcubicbezierpath.cpp.
References lines, and Visualization::mainColor.
Referenced by RefreshGeometry().
getPath()
VCubicBezierPath VisToolCubicBezierPath::getPath ()
Definition at line 162 of file vistoolcubicbezierpath.cpp.
References path.
getPoint()
VScaledEllipse * VisToolCubicBezierPath::getPoint (QVector< VScaledEllipse * > & points, quint32 i, qreal z = 0) private
Definition at line 168 of file vistoolcubicbezierpath.cpp.
References Visualization::InitPoint(), and Visualization::supportColor.
Referenced by Creating(), and RefreshGeometry().
RefreshGeometry()
void VisToolCubicBezierPath::RefreshGeometry () virtual
Implements Visualization.
Definition at line 94 of file vistoolcubicbezierpath.cpp.
References VCubicBezierPath::CountSubSpl(), Creating(), Creation, ctrlPoints, VAbstractCubicBezierPath::DirectionArrows(), Visualization::DrawLine(), Visualization::DrawPath(), Visualization::DrawPoint(), VCubicBezierPath::GetCubicPath(), getLine(), VSpline::GetP1(), VSpline::GetP2(), VSpline::GetP3(), VSpline::GetP4(), VAbstractCubicBezierPath::GetPath(), getPoint(), VCubicBezierPath::GetSpline(), Visualization::lineStyle, Visualization::lineWeight, Visualization::mainColor, mainPoints, Visualization::mode, path, RefreshToolTip(), VCubicBezierPath::SubSplOffset(), and Visualization::supportColor.
RefreshToolTip()
void VisToolCubicBezierPath::RefreshToolTip () private
Definition at line 299 of file vistoolcubicbezierpath.cpp.
References VCubicBezierPath::CountPoints(), VCubicBezierPath::CountSubSpl(), Visualization::mode, path, Show, VCubicBezierPath::SubSplPointsCount(), Visualization::ToolTip(), and Visualization::toolTip.
Referenced by RefreshGeometry(), and setPath().
setPath()
void VisToolCubicBezierPath::setPath (const VCubicBezierPath & value)
Definition at line 153 of file vistoolcubicbezierpath.cpp.
References path, and RefreshToolTip().
type()
virtual int VisToolCubicBezierPath::type () const inline virtual
Reimplemented from VisPath.
Definition at line 79 of file vistoolcubicbezierpath.h.
References Type.
Member Data Documentation
ctrlPoints
QVector<VScaledEllipse *> VisToolCubicBezierPath::ctrlPoints protected
Definition at line 84 of file vistoolcubicbezierpath.h.
Referenced by Creating(), and RefreshGeometry().
helpLine1
VScaledLine* VisToolCubicBezierPath::helpLine1 protected
Definition at line 88 of file vistoolcubicbezierpath.h.
Referenced by Creating(), and VisToolCubicBezierPath().
helpLine2
VScaledLine* VisToolCubicBezierPath::helpLine2 protected
Definition at line 89 of file vistoolcubicbezierpath.h.
Referenced by Creating(), and VisToolCubicBezierPath().
lines
QVector<VScaledLine *> VisToolCubicBezierPath::lines protected
Definition at line 85 of file vistoolcubicbezierpath.h.
Referenced by getLine(), and ~VisToolCubicBezierPath().
mainPoints
QVector<VScaledEllipse *> VisToolCubicBezierPath::mainPoints protected
Definition at line 83 of file vistoolcubicbezierpath.h.
Referenced by RefreshGeometry(), and ~VisToolCubicBezierPath().
newCurveSegment
VCurvePathItem* VisToolCubicBezierPath::newCurveSegment protected
Definition at line 86 of file vistoolcubicbezierpath.h.
Referenced by Creating(), and VisToolCubicBezierPath().
path
VCubicBezierPath VisToolCubicBezierPath::path protected
Definition at line 87 of file vistoolcubicbezierpath.h.
Referenced by getPath(), RefreshGeometry(), RefreshToolTip(), and setPath().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/path/vistoolcubicbezierpath.h
src/libs/vtools/visualization/path/vistoolcubicbezierpath.cpp