Seamly2D: CMLeaf Class Reference
CMLeaf Class Reference
#include <CMLeaf.hpp>
Public Member Functions
CMLeaf (QName *const element, unsigned int position, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
CMLeaf (QName *const element, unsigned int position, bool adopt, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~CMLeaf ()
QName * getElement ()
const QName * getElement () const
unsigned int getPosition () const
virtual bool isRepeatableLeaf () const
void setPosition (const unsigned int newPosition)
virtual void orphanChild ()
CMLeaf (QName *const element, unsigned int position, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
CMLeaf (QName *const element, unsigned int position, bool adopt, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~CMLeaf ()
QName * getElement ()
const QName * getElement () const
unsigned int getPosition () const
virtual bool isRepeatableLeaf () const
void setPosition (const unsigned int newPosition)
virtual void orphanChild ()
CMLeaf (QName *const element, unsigned int position, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
CMLeaf (QName *const element, unsigned int position, bool adopt, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~CMLeaf ()
QName * getElement ()
const QName * getElement () const
unsigned int getPosition () const
virtual bool isRepeatableLeaf () const
void setPosition (const unsigned int newPosition)
virtual void orphanChild ()
Public Member Functions inherited from CMNode
CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~CMNode ()
ContentSpecNode::NodeTypes getType () const
const CMStateSet & getFirstPos ()
const CMStateSet & getLastPos ()
bool isNullable () const
CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~CMNode ()
ContentSpecNode::NodeTypes getType () const
const CMStateSet & getFirstPos ()
const CMStateSet & getLastPos ()
bool isNullable () const
CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~CMNode ()
ContentSpecNode::NodeTypes getType () const
const CMStateSet & getFirstPos ()
const CMStateSet & getLastPos ()
bool isNullable () const
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Protected Member Functions
void calcFirstPos (CMStateSet &toSet) const
void calcLastPos (CMStateSet &toSet) const
void calcFirstPos (CMStateSet &toSet) const
void calcLastPos (CMStateSet &toSet) const
void calcFirstPos (CMStateSet &toSet) const
void calcLastPos (CMStateSet &toSet) const
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Private Member Functions
CMLeaf (const CMLeaf &)
CMLeaf & operator= (const CMLeaf &)
CMLeaf (const CMLeaf &)
CMLeaf & operator= (const CMLeaf &)
CMLeaf (const CMLeaf &)
CMLeaf & operator= (const CMLeaf &)
Private Attributes
QName * fElement
unsigned int fPosition
bool fAdopt
Additional Inherited Members
Public Types inherited from CMNode
enum { epsilonNode = UINT_MAX - 1 }
enum { epsilonNode = UINT_MAX - 1 }
enum { epsilonNode = UINT_MAX - 1 }
Protected Attributes inherited from CMNode
MemoryManager * fMemoryManager
bool fIsNullable
Detailed Description
Definition at line 35 of file CMLeaf.hpp.
Constructor & Destructor Documentation
CMLeaf() [1/9]
CMLeaf::CMLeaf (QName *const element, unsigned int position, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 117 of file CMLeaf.hpp.
References CMNode::epsilonNode, fAdopt, fElement, XMLElementDecl::fgInvalidElemId, XMLUni::fgZeroLenString, CMNode::fIsNullable, CMNode::fMemoryManager, and fPosition.
CMLeaf() [2/9]
CMLeaf::CMLeaf (QName *const element, unsigned int position, bool adopt, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 146 of file CMLeaf.hpp.
References CMNode::epsilonNode, fAdopt, fElement, XMLElementDecl::fgInvalidElemId, XMLUni::fgZeroLenString, CMNode::fIsNullable, CMNode::fMemoryManager, and fPosition.
~CMLeaf() [1/3]
CMLeaf::~CMLeaf () inline
Definition at line 176 of file CMLeaf.hpp.
References fAdopt, and fElement.
CMLeaf() [3/9]
CMLeaf::CMLeaf (const CMLeaf &) private
CMLeaf() [4/9]
CMLeaf::CMLeaf (QName *const element, unsigned int position, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
CMLeaf() [5/9]
CMLeaf::CMLeaf (QName *const element, unsigned int position, bool adopt, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~CMLeaf() [2/3]
CMLeaf::~CMLeaf ()
CMLeaf() [6/9]
CMLeaf::CMLeaf (const CMLeaf &) private
CMLeaf() [7/9]
CMLeaf::CMLeaf (QName *const element, unsigned int position, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
CMLeaf() [8/9]
CMLeaf::CMLeaf (QName *const element, unsigned int position, bool adopt, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~CMLeaf() [3/3]
CMLeaf::~CMLeaf ()
CMLeaf() [9/9]
CMLeaf::CMLeaf (const CMLeaf &) private
Member Function Documentation
calcFirstPos() [1/3]
void CMLeaf::calcFirstPos (CMStateSet & toSet) const inline protected virtual
Implements CMNode.
Definition at line 225 of file CMLeaf.hpp.
References fPosition, CMNode::isNullable(), CMStateSet::setBit(), and CMStateSet::zeroBits().
calcFirstPos() [2/3]
void CMLeaf::calcFirstPos (CMStateSet & toSet) const protected virtual
Implements CMNode.
calcFirstPos() [3/3]
void CMLeaf::calcFirstPos (CMStateSet & toSet) const protected virtual
Implements CMNode.
calcLastPos() [1/3]
void CMLeaf::calcLastPos (CMStateSet & toSet) const inline protected virtual
Implements CMNode.
Definition at line 238 of file CMLeaf.hpp.
References fPosition, CMNode::isNullable(), CMStateSet::setBit(), and CMStateSet::zeroBits().
calcLastPos() [2/3]
void CMLeaf::calcLastPos (CMStateSet & toSet) const protected virtual
Implements CMNode.
calcLastPos() [3/3]
void CMLeaf::calcLastPos (CMStateSet & toSet) const protected virtual
Implements CMNode.
getElement() [1/6]
QName * CMLeaf::getElement () inline
Definition at line 186 of file CMLeaf.hpp.
References fElement.
getElement() [2/6]
QName* CMLeaf::getElement ()
getElement() [3/6]
QName* CMLeaf::getElement ()
getElement() [4/6]
const QName * CMLeaf::getElement () const inline
Definition at line 191 of file CMLeaf.hpp.
References fElement.
getElement() [5/6]
const QName* CMLeaf::getElement () const
getElement() [6/6]
const QName* CMLeaf::getElement () const
getPosition() [1/3]
unsigned int CMLeaf::getPosition () const inline
Definition at line 196 of file CMLeaf.hpp.
References fPosition.
getPosition() [2/3]
unsigned int CMLeaf::getPosition () const
getPosition() [3/3]
unsigned int CMLeaf::getPosition () const
isRepeatableLeaf() [1/3]
bool CMLeaf::isRepeatableLeaf () const inline virtual
Reimplemented in CMRepeatingLeaf, CMRepeatingLeaf, and CMRepeatingLeaf.
Definition at line 201 of file CMLeaf.hpp.
isRepeatableLeaf() [2/3]
virtual bool CMLeaf::isRepeatableLeaf () const virtual
Reimplemented in CMRepeatingLeaf, CMRepeatingLeaf, and CMRepeatingLeaf.
isRepeatableLeaf() [3/3]
virtual bool CMLeaf::isRepeatableLeaf () const virtual
Reimplemented in CMRepeatingLeaf, CMRepeatingLeaf, and CMRepeatingLeaf.
operator=() [1/3]
CMLeaf& CMLeaf::operator= (const CMLeaf &) private
operator=() [2/3]
CMLeaf& CMLeaf::operator= (const CMLeaf &) private
operator=() [3/3]
CMLeaf& CMLeaf::operator= (const CMLeaf &) private
orphanChild() [1/3]
void CMLeaf::orphanChild () inline virtual
Implements CMNode.
Definition at line 218 of file CMLeaf.hpp.
orphanChild() [2/3]
virtual void CMLeaf::orphanChild () virtual
Implements CMNode.
orphanChild() [3/3]
virtual void CMLeaf::orphanChild () virtual
Implements CMNode.
setPosition() [1/3]
void CMLeaf::setPosition (const unsigned int newPosition) inline
Definition at line 209 of file CMLeaf.hpp.
References fPosition.
setPosition() [2/3]
void CMLeaf::setPosition (const unsigned int newPosition)
setPosition() [3/3]
void CMLeaf::setPosition (const unsigned int newPosition)
Member Data Documentation
fAdopt
bool CMLeaf::fAdopt private
Definition at line 104 of file CMLeaf.hpp.
Referenced by CMLeaf(), and ~CMLeaf().
fElement
QName * CMLeaf::fElement private
Definition at line 102 of file CMLeaf.hpp.
Referenced by CMLeaf(), getElement(), and ~CMLeaf().
fPosition
unsigned int CMLeaf::fPosition private
Definition at line 103 of file CMLeaf.hpp.
Referenced by calcFirstPos(), calcLastPos(), CMLeaf(), getPosition(), and setPosition().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/common/CMLeaf.hpp