Seamly2D: GroupTableWidgetItem Class Reference
GroupTableWidgetItem Class Reference
#include <group_tablewidgetitem.h>
Public Member Functions
GroupTableWidgetItem (VAbstractPattern *doc)
virtual bool operator< (const QTableWidgetItem &other) const Q_DECL_OVERRIDE
Private Attributes
VAbstractPattern * m_doc
Detailed Description
Definition at line 35 of file group_tablewidgetitem.h.
Constructor & Destructor Documentation
GroupTableWidgetItem()
GroupTableWidgetItem::GroupTableWidgetItem (VAbstractPattern * doc) explicit
Definition at line 32 of file group_tablewidgetitem.cpp.
Member Function Documentation
operator<()
bool GroupTableWidgetItem::operator< (const QTableWidgetItem & other) const virtual
Definition at line 38 of file group_tablewidgetitem.cpp.
References VAbstractPattern::getGroupLock(), VAbstractPattern::getGroupVisibility(), VAbstractPattern::isGroupEmpty(), and m_doc.
Member Data Documentation
m_doc
VAbstractPattern* GroupTableWidgetItem::m_doc private
Definition at line 43 of file group_tablewidgetitem.h.
Referenced by operator<().
The documentation for this class was generated from the following files:
src/libs/vwidgets/group_tablewidgetitem.h
src/libs/vwidgets/group_tablewidgetitem.cpp