Seamly2D: MessageHandler Class Reference
MessageHandler Class Reference
Public Member Functions
MessageHandler ()
QString statusMessage () const
qint64 line () const
qint64 column () const
Protected Member Functions
virtual void handleMessage (QtMsgType type, const QString &description, const QUrl &identifier, const QSourceLocation &sourceLocation) Q_DECL_OVERRIDE
Private Attributes
QtMsgType m_messageType
QString m_description
QSourceLocation m_sourceLocation
Detailed Description
Definition at line 147 of file vdomdocument.cpp.
Constructor & Destructor Documentation
MessageHandler()
MessageHandler::MessageHandler () inline
Definition at line 150 of file vdomdocument.cpp.
Member Function Documentation
column()
qint64 MessageHandler::column () const inline
Definition at line 185 of file vdomdocument.cpp.
References m_sourceLocation.
Referenced by VDomDocument::ValidateXML().
handleMessage()
void MessageHandler::handleMessage (QtMsgType type, const QString & description, const QUrl & identifier, const QSourceLocation & sourceLocation) protected virtual
Definition at line 192 of file vdomdocument.cpp.
References m_description, m_messageType, and m_sourceLocation.
line()
qint64 MessageHandler::line () const inline
Definition at line 179 of file vdomdocument.cpp.
References m_sourceLocation.
Referenced by VDomDocument::ValidateXML().
statusMessage()
QString MessageHandler::statusMessage () const
Definition at line 171 of file vdomdocument.cpp.
References m_description.
Referenced by VDomDocument::ValidateXML().
Member Data Documentation
m_description
QString MessageHandler::m_description private
Definition at line 166 of file vdomdocument.cpp.
Referenced by handleMessage(), and statusMessage().
m_messageType
QtMsgType MessageHandler::m_messageType private
Definition at line 165 of file vdomdocument.cpp.
Referenced by handleMessage().
m_sourceLocation
QSourceLocation MessageHandler::m_sourceLocation private
Definition at line 167 of file vdomdocument.cpp.
Referenced by column(), handleMessage(), and line().
The documentation for this class was generated from the following file:
src/libs/ifc/xml/vdomdocument.cpp