Seamly2D: DOMBuffer Class Reference
DOMBuffer Class Reference
#include <DOMStringPool.hpp>
Public Member Functions
DOMBuffer (DOMDocumentImpl *doc, XMLSize_t capacity=31)
~DOMBuffer ()
void append (const XMLCh *const chars)
void append (const XMLCh *const chars, const XMLSize_t count)
void appendInPlace (const XMLCh *const chars, const XMLSize_t count)
void set (const XMLCh *const chars)
void set (const XMLCh *const chars, const XMLSize_t count)
const XMLCh * getRawBuffer () const
void reset ()
void chop (const XMLSize_t count)
XMLSize_t getLen () const
XMLSize_t getCapacity () const
void expandCapacity (const XMLSize_t extraNeeded, bool releasePrevious=false)
DOMBuffer (DOMDocumentImpl *doc, XMLSize_t capacity=31)
~DOMBuffer ()
void append (const XMLCh *const chars)
void append (const XMLCh *const chars, const XMLSize_t count)
void appendInPlace (const XMLCh *const chars, const XMLSize_t count)
void set (const XMLCh *const chars)
void set (const XMLCh *const chars, const XMLSize_t count)
const XMLCh * getRawBuffer () const
void reset ()
void chop (const XMLSize_t count)
XMLSize_t getLen () const
XMLSize_t getCapacity () const
void expandCapacity (const XMLSize_t extraNeeded, bool releasePrevious=false)
DOMBuffer (DOMDocumentImpl *doc, XMLSize_t capacity=31)
~DOMBuffer ()
void append (const XMLCh *const chars)
void append (const XMLCh *const chars, const XMLSize_t count)
void appendInPlace (const XMLCh *const chars, const XMLSize_t count)
void set (const XMLCh *const chars)
void set (const XMLCh *const chars, const XMLSize_t count)
const XMLCh * getRawBuffer () const
void reset ()
void chop (const XMLSize_t count)
XMLSize_t getLen () const
XMLSize_t getCapacity () const
void expandCapacity (const XMLSize_t extraNeeded, bool releasePrevious=false)
Private Member Functions
DOMBuffer (const DOMBuffer &)
DOMBuffer & operator= (const DOMBuffer &)
DOMBuffer (const DOMBuffer &)
DOMBuffer & operator= (const DOMBuffer &)
DOMBuffer (const DOMBuffer &)
DOMBuffer & operator= (const DOMBuffer &)
Private Attributes
XMLCh * fBuffer
XMLSize_t fIndex
XMLSize_t fCapacity
DOMDocumentImpl * fDoc
Detailed Description
Definition at line 61 of file DOMStringPool.hpp.
Constructor & Destructor Documentation
DOMBuffer() [1/6]
DOMBuffer::DOMBuffer (DOMDocumentImpl * doc, XMLSize_t capacity = 31)
~DOMBuffer() [1/3]
DOMBuffer::~DOMBuffer () inline
Definition at line 69 of file DOMStringPool.hpp.
DOMBuffer() [2/6]
DOMBuffer::DOMBuffer (const DOMBuffer &) private
DOMBuffer() [3/6]
DOMBuffer::DOMBuffer (DOMDocumentImpl * doc, XMLSize_t capacity = 31)
~DOMBuffer() [2/3]
DOMBuffer::~DOMBuffer () inline
Definition at line 69 of file DOMStringPool.hpp.
DOMBuffer() [4/6]
DOMBuffer::DOMBuffer (const DOMBuffer &) private
DOMBuffer() [5/6]
DOMBuffer::DOMBuffer (DOMDocumentImpl * doc, XMLSize_t capacity = 31)
~DOMBuffer() [3/3]
DOMBuffer::~DOMBuffer () inline
Definition at line 69 of file DOMStringPool.hpp.
DOMBuffer() [6/6]
DOMBuffer::DOMBuffer (const DOMBuffer &) private
Member Function Documentation
append() [1/6]
void DOMBuffer::append (const XMLCh *const chars) inline
Definition at line 155 of file DOMStringPool.hpp.
References expandCapacity(), fBuffer, fCapacity, fIndex, and XMLString::stringLen().
append() [2/6]
void DOMBuffer::append (const XMLCh *const chars)
append() [3/6]
void DOMBuffer::append (const XMLCh *const chars)
append() [4/6]
void DOMBuffer::append (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 169 of file DOMStringPool.hpp.
References expandCapacity(), fBuffer, fCapacity, and fIndex.
append() [5/6]
void DOMBuffer::append (const XMLCh *const chars, const XMLSize_t count)
append() [6/6]
void DOMBuffer::append (const XMLCh *const chars, const XMLSize_t count)
appendInPlace() [1/3]
void DOMBuffer::appendInPlace (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 182 of file DOMStringPool.hpp.
References expandCapacity(), fBuffer, fCapacity, and fIndex.
appendInPlace() [2/3]
void DOMBuffer::appendInPlace (const XMLCh *const chars, const XMLSize_t count)
appendInPlace() [3/3]
void DOMBuffer::appendInPlace (const XMLCh *const chars, const XMLSize_t count)
chop() [1/3]
void DOMBuffer::chop (const XMLSize_t count) inline
Definition at line 95 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
chop() [2/3]
void DOMBuffer::chop (const XMLSize_t count) inline
Definition at line 95 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
chop() [3/3]
void DOMBuffer::chop (const XMLSize_t count) inline
Definition at line 95 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
expandCapacity() [1/3]
void DOMBuffer::expandCapacity (const XMLSize_t extraNeeded, bool releasePrevious = false)
Referenced by append(), appendInPlace(), and set().
expandCapacity() [2/3]
void DOMBuffer::expandCapacity (const XMLSize_t extraNeeded, bool releasePrevious = false)
expandCapacity() [3/3]
void DOMBuffer::expandCapacity (const XMLSize_t extraNeeded, bool releasePrevious = false)
getCapacity() [1/3]
XMLSize_t DOMBuffer::getCapacity () const inline
Definition at line 113 of file DOMStringPool.hpp.
References fCapacity.
getCapacity() [2/3]
XMLSize_t DOMBuffer::getCapacity () const inline
Definition at line 113 of file DOMStringPool.hpp.
References fCapacity.
getCapacity() [3/3]
XMLSize_t DOMBuffer::getCapacity () const inline
Definition at line 113 of file DOMStringPool.hpp.
References fCapacity.
getLen() [1/3]
XMLSize_t DOMBuffer::getLen () const inline
Definition at line 108 of file DOMStringPool.hpp.
References fIndex.
getLen() [2/3]
XMLSize_t DOMBuffer::getLen () const inline
Definition at line 108 of file DOMStringPool.hpp.
References fIndex.
getLen() [3/3]
XMLSize_t DOMBuffer::getLen () const inline
Definition at line 108 of file DOMStringPool.hpp.
References fIndex.
getRawBuffer() [1/3]
const XMLCh* DOMBuffer::getRawBuffer () const inline
Definition at line 83 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
getRawBuffer() [2/3]
const XMLCh* DOMBuffer::getRawBuffer () const inline
Definition at line 83 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
getRawBuffer() [3/3]
const XMLCh* DOMBuffer::getRawBuffer () const inline
Definition at line 83 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
operator=() [1/3]
DOMBuffer& DOMBuffer::operator= (const DOMBuffer &) private
operator=() [2/3]
DOMBuffer& DOMBuffer::operator= (const DOMBuffer &) private
operator=() [3/3]
DOMBuffer& DOMBuffer::operator= (const DOMBuffer &) private
reset() [1/3]
void DOMBuffer::reset () inline
Definition at line 89 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
reset() [2/3]
void DOMBuffer::reset () inline
Definition at line 89 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
reset() [3/3]
void DOMBuffer::reset () inline
Definition at line 89 of file DOMStringPool.hpp.
References fBuffer, and fIndex.
set() [1/6]
void DOMBuffer::set (const XMLCh *const chars) inline
Definition at line 195 of file DOMStringPool.hpp.
References expandCapacity(), fBuffer, fCapacity, fIndex, and XMLString::stringLen().
set() [2/6]
void DOMBuffer::set (const XMLCh *const chars)
set() [3/6]
void DOMBuffer::set (const XMLCh *const chars)
set() [4/6]
void DOMBuffer::set (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 210 of file DOMStringPool.hpp.
References expandCapacity(), fBuffer, fCapacity, and fIndex.
set() [5/6]
void DOMBuffer::set (const XMLCh *const chars, const XMLSize_t count)
set() [6/6]
void DOMBuffer::set (const XMLCh *const chars, const XMLSize_t count)
Member Data Documentation
fBuffer
XMLCh * DOMBuffer::fBuffer private
Definition at line 143 of file DOMStringPool.hpp.
Referenced by append(), appendInPlace(), chop(), getRawBuffer(), reset(), and set().
fCapacity
XMLSize_t DOMBuffer::fCapacity private
Definition at line 145 of file DOMStringPool.hpp.
Referenced by append(), appendInPlace(), getCapacity(), and set().
fDoc
DOMDocumentImpl * DOMBuffer::fDoc private
Definition at line 146 of file DOMStringPool.hpp.
fIndex
XMLSize_t DOMBuffer::fIndex private
Definition at line 144 of file DOMStringPool.hpp.
Referenced by append(), appendInPlace(), chop(), getLen(), getRawBuffer(), reset(), and set().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/dom/impl/DOMStringPool.hpp