Seamly2D: XMLUri Class Reference
XMLUri Class Reference
#include <XMLUri.hpp>
Public Member Functions
XMLUri (const XMLCh *const uriSpec, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLUri (const XMLUri *const baseURI, const XMLCh *const uriSpec, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLUri (const XMLUri &toCopy)
XMLUri & operator= (const XMLUri &toAssign)
virtual ~XMLUri ()
const XMLCh * getUriText () const
const XMLCh * getScheme () const
const XMLCh * getUserInfo () const
const XMLCh * getHost () const
int getPort () const
const XMLCh * getRegBasedAuthority () const
const XMLCh * getPath () const
const XMLCh * getQueryString () const
const XMLCh * getFragment () const
void setScheme (const XMLCh *const newScheme)
void setUserInfo (const XMLCh *const newUserInfo)
void setHost (const XMLCh *const newHost)
void setPort (int newPort)
void setRegBasedAuthority (const XMLCh *const newRegAuth)
void setPath (const XMLCh *const newPath)
void setQueryString (const XMLCh *const newQueryString)
void setFragment (const XMLCh *const newFragment)
XMLUri (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLUri (const XMLCh *const uriSpec, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLUri (const XMLUri *const baseURI, const XMLCh *const uriSpec, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLUri (const XMLUri &toCopy)
XMLUri & operator= (const XMLUri &toAssign)
virtual ~XMLUri ()
const XMLCh * getUriText () const
const XMLCh * getScheme () const
const XMLCh * getUserInfo () const
const XMLCh * getHost () const
int getPort () const
const XMLCh * getRegBasedAuthority () const
const XMLCh * getPath () const
const XMLCh * getQueryString () const
const XMLCh * getFragment () const
void setScheme (const XMLCh *const newScheme)
void setUserInfo (const XMLCh *const newUserInfo)
void setHost (const XMLCh *const newHost)
void setPort (int newPort)
void setRegBasedAuthority (const XMLCh *const newRegAuth)
void setPath (const XMLCh *const newPath)
void setQueryString (const XMLCh *const newQueryString)
void setFragment (const XMLCh *const newFragment)
XMLUri (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLUri (const XMLCh *const uriSpec, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLUri (const XMLUri *const baseURI, const XMLCh *const uriSpec, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLUri (const XMLUri &toCopy)
XMLUri & operator= (const XMLUri &toAssign)
virtual ~XMLUri ()
const XMLCh * getUriText () const
const XMLCh * getScheme () const
const XMLCh * getUserInfo () const
const XMLCh * getHost () const
int getPort () const
const XMLCh * getRegBasedAuthority () const
const XMLCh * getPath () const
const XMLCh * getQueryString () const
const XMLCh * getFragment () const
void setScheme (const XMLCh *const newScheme)
void setUserInfo (const XMLCh *const newUserInfo)
void setHost (const XMLCh *const newHost)
void setPort (int newPort)
void setRegBasedAuthority (const XMLCh *const newRegAuth)
void setPath (const XMLCh *const newPath)
void setQueryString (const XMLCh *const newQueryString)
void setFragment (const XMLCh *const newFragment)
XMLUri (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Static Public Member Functions
static bool isURIString (const XMLCh *const uric)
static bool isValidURI (const XMLUri *const baseURI, const XMLCh *const uriStr, bool bAllowSpaces=false)
static bool isValidURI (bool haveBaseURI, const XMLCh *const uriStr, bool bAllowSpaces=false)
static void normalizeURI (const XMLCh *const systemURI, XMLBuffer &normalizedURI)
static bool isURIString (const XMLCh *const uric)
static bool isValidURI (const XMLUri *const baseURI, const XMLCh *const uriStr, bool bAllowSpaces=false)
static bool isValidURI (bool haveBaseURI, const XMLCh *const uriStr, bool bAllowSpaces=false)
static void normalizeURI (const XMLCh *const systemURI, XMLBuffer &normalizedURI)
static bool isURIString (const XMLCh *const uric)
static bool isValidURI (const XMLUri *const baseURI, const XMLCh *const uriStr, bool bAllowSpaces=false)
static bool isValidURI (bool haveBaseURI, const XMLCh *const uriStr, bool bAllowSpaces=false)
static void normalizeURI (const XMLCh *const systemURI, XMLBuffer &normalizedURI)
Private Member Functions
void buildFullText ()
bool isGenericURI ()
void initialize (const XMLUri &toCopy)
void initialize (const XMLUri *const baseURI, const XMLCh *const uriSpec)
void initializeScheme (const XMLCh *const uriSpec)
void initializeAuthority (const XMLCh *const uriSpec)
void initializePath (const XMLCh *const uriSpec)
void cleanUp ()
void buildFullText ()
bool isGenericURI ()
void initialize (const XMLUri &toCopy)
void initialize (const XMLUri *const baseURI, const XMLCh *const uriSpec)
void initializeScheme (const XMLCh *const uriSpec)
void initializeAuthority (const XMLCh *const uriSpec)
void initializePath (const XMLCh *const uriSpec)
void cleanUp ()
void buildFullText ()
bool isGenericURI ()
void initialize (const XMLUri &toCopy)
void initialize (const XMLUri *const baseURI, const XMLCh *const uriSpec)
void initializeScheme (const XMLCh *const uriSpec)
void initializeAuthority (const XMLCh *const uriSpec)
void initializePath (const XMLCh *const uriSpec)
void cleanUp ()
Static Private Member Functions
static bool isReservedCharacter (const XMLCh theChar)
static bool isPathCharacter (const XMLCh theChar)
static bool isUnreservedCharacter (const XMLCh theChar)
static bool isReservedOrUnreservedCharacter (const XMLCh theChar)
static bool isConformantSchemeName (const XMLCh *const scheme)
static void isConformantUserInfo (const XMLCh *const userInfo, MemoryManager *const manager)
static bool isValidServerBasedAuthority (const XMLCh *const host, const XMLSize_t hostLen, const int port, const XMLCh *const userinfo, const XMLSize_t userLen)
static bool isValidServerBasedAuthority (const XMLCh *const host, const int port, const XMLCh *const userinfo, MemoryManager *const manager)
static bool isValidRegistryBasedAuthority (const XMLCh *const authority, const XMLSize_t authLen)
static bool isValidRegistryBasedAuthority (const XMLCh *const authority)
static bool isWellFormedAddress (const XMLCh *const addr, MemoryManager *const manager)
static bool isWellFormedIPv4Address (const XMLCh *const addr, const XMLSize_t length)
static bool isWellFormedIPv6Reference (const XMLCh *const addr, const XMLSize_t length)
static int scanHexSequence (const XMLCh *const addr, XMLSize_t index, XMLSize_t end, int &counter)
static bool isConformantSchemeName (const XMLCh *const scheme, const XMLSize_t schemeLen)
static bool processScheme (const XMLCh *const uriStr, XMLSize_t &index)
static bool processAuthority (const XMLCh *const uriStr, const XMLSize_t authLen)
static bool isWellFormedAddress (const XMLCh *const addr, const XMLSize_t addrLen)
static bool processPath (const XMLCh *const pathStr, const XMLSize_t pathStrLen, const bool isSchemePresent, const bool bAllowSpaces=false)
static bool isReservedCharacter (const XMLCh theChar)
static bool isPathCharacter (const XMLCh theChar)
static bool isUnreservedCharacter (const XMLCh theChar)
static bool isReservedOrUnreservedCharacter (const XMLCh theChar)
static bool isConformantSchemeName (const XMLCh *const scheme)
static void isConformantUserInfo (const XMLCh *const userInfo, MemoryManager *const manager)
static bool isValidServerBasedAuthority (const XMLCh *const host, const XMLSize_t hostLen, const int port, const XMLCh *const userinfo, const XMLSize_t userLen)
static bool isValidServerBasedAuthority (const XMLCh *const host, const int port, const XMLCh *const userinfo, MemoryManager *const manager)
static bool isValidRegistryBasedAuthority (const XMLCh *const authority, const XMLSize_t authLen)
static bool isValidRegistryBasedAuthority (const XMLCh *const authority)
static bool isWellFormedAddress (const XMLCh *const addr, MemoryManager *const manager)
static bool isWellFormedIPv4Address (const XMLCh *const addr, const XMLSize_t length)
static bool isWellFormedIPv6Reference (const XMLCh *const addr, const XMLSize_t length)
static int scanHexSequence (const XMLCh *const addr, XMLSize_t index, XMLSize_t end, int &counter)
static bool isConformantSchemeName (const XMLCh *const scheme, const XMLSize_t schemeLen)
static bool processScheme (const XMLCh *const uriStr, XMLSize_t &index)
static bool processAuthority (const XMLCh *const uriStr, const XMLSize_t authLen)
static bool isWellFormedAddress (const XMLCh *const addr, const XMLSize_t addrLen)
static bool processPath (const XMLCh *const pathStr, const XMLSize_t pathStrLen, const bool isSchemePresent, const bool bAllowSpaces=false)
static bool isReservedCharacter (const XMLCh theChar)
static bool isPathCharacter (const XMLCh theChar)
static bool isUnreservedCharacter (const XMLCh theChar)
static bool isReservedOrUnreservedCharacter (const XMLCh theChar)
static bool isConformantSchemeName (const XMLCh *const scheme)
static void isConformantUserInfo (const XMLCh *const userInfo, MemoryManager *const manager)
static bool isValidServerBasedAuthority (const XMLCh *const host, const XMLSize_t hostLen, const int port, const XMLCh *const userinfo, const XMLSize_t userLen)
static bool isValidServerBasedAuthority (const XMLCh *const host, const int port, const XMLCh *const userinfo, MemoryManager *const manager)
static bool isValidRegistryBasedAuthority (const XMLCh *const authority, const XMLSize_t authLen)
static bool isValidRegistryBasedAuthority (const XMLCh *const authority)
static bool isWellFormedAddress (const XMLCh *const addr, MemoryManager *const manager)
static bool isWellFormedIPv4Address (const XMLCh *const addr, const XMLSize_t length)
static bool isWellFormedIPv6Reference (const XMLCh *const addr, const XMLSize_t length)
static int scanHexSequence (const XMLCh *const addr, XMLSize_t index, XMLSize_t end, int &counter)
static bool isConformantSchemeName (const XMLCh *const scheme, const XMLSize_t schemeLen)
static bool processScheme (const XMLCh *const uriStr, XMLSize_t &index)
static bool processAuthority (const XMLCh *const uriStr, const XMLSize_t authLen)
static bool isWellFormedAddress (const XMLCh *const addr, const XMLSize_t addrLen)
static bool processPath (const XMLCh *const pathStr, const XMLSize_t pathStrLen, const bool isSchemePresent, const bool bAllowSpaces=false)
Private Attributes
int fPort
XMLCh * fScheme
XMLCh * fUserInfo
XMLCh * fHost
XMLCh * fRegAuth
XMLCh * fPath
XMLCh * fQueryString
XMLCh * fFragment
XMLCh * fURIText
MemoryManager * fMemoryManager
Static Private Attributes
static const XMLCh MARK_OR_RESERVED_CHARACTERS []
static const XMLCh RESERVED_CHARACTERS []
static const XMLCh MARK_CHARACTERS []
static const XMLCh SCHEME_CHARACTERS []
static const XMLCh USERINFO_CHARACTERS []
static const XMLCh REG_NAME_CHARACTERS []
static const XMLCh PATH_CHARACTERS []
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 42 of file XMLUri.hpp.
Constructor & Destructor Documentation
XMLUri() [1/12]
XMLUri::XMLUri (const XMLCh *const uriSpec, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Construct a new URI from a URI specification string.
If the specification follows the "generic URI" syntax, (two slashes following the first colon), the specification will be parsed accordingly - setting the scheme, userinfo, host, port, path, querystring and fragment fields as necessary.
If the specification does not follow the "generic URI" syntax, the specification is parsed into a scheme and scheme-specific part (stored as the path) only.
Parameters
uriSpec the URI specification string (cannot be null or empty)
manager Pointer to the memory manager to be used to allocate objects.
ctor# 2
XMLUri() [2/12]
XMLUri::XMLUri (const XMLUri *const baseURI, const XMLCh *const uriSpec, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Construct a new URI from a base URI and a URI specification string. The URI specification string may be a relative URI.
Parameters
baseURI the base URI (cannot be null if uriSpec is null or empty)
uriSpec the URI specification string (cannot be null or empty if base is null)
manager Pointer to the memory manager to be used to allocate objects.
ctor# 7 relative ctor
XMLUri() [3/12]
XMLUri::XMLUri (const XMLUri & toCopy)
Copy constructor
~XMLUri() [1/3]
virtual XMLUri::~XMLUri () virtual
XMLUri() [4/12]
XMLUri::XMLUri (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XMLUri() [5/12]
XMLUri::XMLUri (const XMLCh *const uriSpec, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Construct a new URI from a URI specification string.
If the specification follows the "generic URI" syntax, (two slashes following the first colon), the specification will be parsed accordingly - setting the scheme, userinfo, host, port, path, querystring and fragment fields as necessary.
If the specification does not follow the "generic URI" syntax, the specification is parsed into a scheme and scheme-specific part (stored as the path) only.
Parameters
uriSpec the URI specification string (cannot be null or empty)
manager Pointer to the memory manager to be used to allocate objects.
ctor# 2
XMLUri() [6/12]
XMLUri::XMLUri (const XMLUri *const baseURI, const XMLCh *const uriSpec, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Construct a new URI from a base URI and a URI specification string. The URI specification string may be a relative URI.
Parameters
baseURI the base URI (cannot be null if uriSpec is null or empty)
uriSpec the URI specification string (cannot be null or empty if base is null)
manager Pointer to the memory manager to be used to allocate objects.
ctor# 7 relative ctor
XMLUri() [7/12]
XMLUri::XMLUri (const XMLUri & toCopy)
Copy constructor
~XMLUri() [2/3]
virtual XMLUri::~XMLUri () virtual
XMLUri() [8/12]
XMLUri::XMLUri (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XMLUri() [9/12]
XMLUri::XMLUri (const XMLCh *const uriSpec, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Construct a new URI from a URI specification string.
If the specification follows the "generic URI" syntax, (two slashes following the first colon), the specification will be parsed accordingly - setting the scheme, userinfo, host, port, path, querystring and fragment fields as necessary.
If the specification does not follow the "generic URI" syntax, the specification is parsed into a scheme and scheme-specific part (stored as the path) only.
Parameters
uriSpec the URI specification string (cannot be null or empty)
manager Pointer to the memory manager to be used to allocate objects.
ctor# 2
XMLUri() [10/12]
XMLUri::XMLUri (const XMLUri *const baseURI, const XMLCh *const uriSpec, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Construct a new URI from a base URI and a URI specification string. The URI specification string may be a relative URI.
Parameters
baseURI the base URI (cannot be null if uriSpec is null or empty)
uriSpec the URI specification string (cannot be null or empty if base is null)
manager Pointer to the memory manager to be used to allocate objects.
ctor# 7 relative ctor
XMLUri() [11/12]
XMLUri::XMLUri (const XMLUri & toCopy)
Copy constructor
~XMLUri() [3/3]
virtual XMLUri::~XMLUri () virtual
XMLUri() [12/12]
XMLUri::XMLUri (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Member Function Documentation
buildFullText() [1/3]
void XMLUri::buildFullText () private
buildFullText() [2/3]
void XMLUri::buildFullText () private
buildFullText() [3/3]
void XMLUri::buildFullText () private
cleanUp() [1/3]
void XMLUri::cleanUp () private
cleanup the data variables
cleanUp() [2/3]
void XMLUri::cleanUp () private
cleanup the data variables
cleanUp() [3/3]
void XMLUri::cleanUp () private
cleanup the data variables
getFragment() [1/3]
const XMLCh * XMLUri::getFragment () const inline
Get the fragment for this URI.
Returns
the fragment for this URI. Null is returned if there was no "#" in the URI spec, empty string if there was a "#" but no fragment following it.
Definition at line 618 of file XMLUri.hpp.
getFragment() [2/3]
const XMLCh* XMLUri::getFragment () const
Get the fragment for this URI.
Returns
the fragment for this URI. Null is returned if there was no "#" in the URI spec, empty string if there was a "#" but no fragment following it.
getFragment() [3/3]
const XMLCh* XMLUri::getFragment () const
Get the fragment for this URI.
Returns
the fragment for this URI. Null is returned if there was no "#" in the URI spec, empty string if there was a "#" but no fragment following it.
getHost() [1/3]
const XMLCh * XMLUri::getHost () const inline
Get the host for this URI.
Returns
the host for this URI (null if not specified).
Definition at line 593 of file XMLUri.hpp.
getHost() [2/3]
const XMLCh* XMLUri::getHost () const
Get the host for this URI.
Returns
the host for this URI (null if not specified).
getHost() [3/3]
const XMLCh* XMLUri::getHost () const
Get the host for this URI.
Returns
the host for this URI (null if not specified).
getPath() [1/3]
const XMLCh * XMLUri::getPath () const inline
Get the path for this URI. Note that the value returned is the path only and does not include the query string or fragment.
Returns
the path for this URI.
Definition at line 608 of file XMLUri.hpp.
getPath() [2/3]
const XMLCh* XMLUri::getPath () const
Get the path for this URI. Note that the value returned is the path only and does not include the query string or fragment.
Returns
the path for this URI.
getPath() [3/3]
const XMLCh* XMLUri::getPath () const
Get the path for this URI. Note that the value returned is the path only and does not include the query string or fragment.
Returns
the path for this URI.
getPort() [1/3]
int XMLUri::getPort () const inline
Get the port for this URI.
Returns
the port for this URI (-1 if not specified).
Definition at line 598 of file XMLUri.hpp.
getPort() [2/3]
int XMLUri::getPort () const
Get the port for this URI.
Returns
the port for this URI (-1 if not specified).
getPort() [3/3]
int XMLUri::getPort () const
Get the port for this URI.
Returns
the port for this URI (-1 if not specified).
getQueryString() [1/3]
const XMLCh * XMLUri::getQueryString () const inline
Get the query string for this URI.
Returns
the query string for this URI. Null is returned if there was no "?" in the URI spec, empty string if there was a "?" but no query string following it.
Definition at line 613 of file XMLUri.hpp.
getQueryString() [2/3]
const XMLCh* XMLUri::getQueryString () const
Get the query string for this URI.
Returns
the query string for this URI. Null is returned if there was no "?" in the URI spec, empty string if there was a "?" but no query string following it.
getQueryString() [3/3]
const XMLCh* XMLUri::getQueryString () const
Get the query string for this URI.
Returns
the query string for this URI. Null is returned if there was no "?" in the URI spec, empty string if there was a "?" but no query string following it.
getRegBasedAuthority() [1/3]
const XMLCh * XMLUri::getRegBasedAuthority () const inline
Get the registry based authority for this URI.
Returns
the registry based authority (null if not specified).
Definition at line 603 of file XMLUri.hpp.
getRegBasedAuthority() [2/3]
const XMLCh* XMLUri::getRegBasedAuthority () const
Get the registry based authority for this URI.
Returns
the registry based authority (null if not specified).
getRegBasedAuthority() [3/3]
const XMLCh* XMLUri::getRegBasedAuthority () const
Get the registry based authority for this URI.
Returns
the registry based authority (null if not specified).
getScheme() [1/3]
const XMLCh * XMLUri::getScheme () const inline
Get the scheme for this URI.
Returns
the scheme for this URI
Definition at line 583 of file XMLUri.hpp.
getScheme() [2/3]
const XMLCh* XMLUri::getScheme () const
Get the scheme for this URI.
Returns
the scheme for this URI
getScheme() [3/3]
const XMLCh* XMLUri::getScheme () const
Get the scheme for this URI.
Returns
the scheme for this URI
getUriText() [1/3]
const XMLCh * XMLUri::getUriText () const inline
Get the URI as a string specification. See RFC 2396 Section 5.2.
Returns
the URI string specification
Definition at line 623 of file XMLUri.hpp.
getUriText() [2/3]
const XMLCh* XMLUri::getUriText () const
Get the URI as a string specification. See RFC 2396 Section 5.2.
Returns
the URI string specification
getUriText() [3/3]
const XMLCh* XMLUri::getUriText () const
Get the URI as a string specification. See RFC 2396 Section 5.2.
Returns
the URI string specification
getUserInfo() [1/3]
const XMLCh * XMLUri::getUserInfo () const inline
Get the userinfo for this URI.
Returns
the userinfo for this URI (null if not specified).
Definition at line 588 of file XMLUri.hpp.
getUserInfo() [2/3]
const XMLCh* XMLUri::getUserInfo () const
Get the userinfo for this URI.
Returns
the userinfo for this URI (null if not specified).
getUserInfo() [3/3]
const XMLCh* XMLUri::getUserInfo () const
Get the userinfo for this URI.
Returns
the userinfo for this URI (null if not specified).
initialize() [1/6]
void XMLUri::initialize (const XMLUri & toCopy) private
Initialize all fields of this URI from another URI.
Parameters
toCopy the URI to copy (cannot be null)
initialize() [2/6]
void XMLUri::initialize (const XMLUri & toCopy) private
Initialize all fields of this URI from another URI.
Parameters
toCopy the URI to copy (cannot be null)
initialize() [3/6]
void XMLUri::initialize (const XMLUri & toCopy) private
Initialize all fields of this URI from another URI.
Parameters
toCopy the URI to copy (cannot be null)
initialize() [4/6]
void XMLUri::initialize (const XMLUri *const baseURI, const XMLCh *const uriSpec) private
Initializes this URI from a base URI and a URI specification string. See RFC 2396 Section 4 and Appendix B for specifications on parsing the URI and Section 5 for specifications on resolving relative URIs and relative paths.
Parameters
baseURI the base URI (may be null if uriSpec is an absolute URI)
uriSpec the URI spec string which may be an absolute or relative URI (can only be null/empty if base is not null)
initialize() [5/6]
void XMLUri::initialize (const XMLUri *const baseURI, const XMLCh *const uriSpec) private
Initializes this URI from a base URI and a URI specification string. See RFC 2396 Section 4 and Appendix B for specifications on parsing the URI and Section 5 for specifications on resolving relative URIs and relative paths.
Parameters
baseURI the base URI (may be null if uriSpec is an absolute URI)
uriSpec the URI spec string which may be an absolute or relative URI (can only be null/empty if base is not null)
initialize() [6/6]
void XMLUri::initialize (const XMLUri *const baseURI, const XMLCh *const uriSpec) private
Initializes this URI from a base URI and a URI specification string. See RFC 2396 Section 4 and Appendix B for specifications on parsing the URI and Section 5 for specifications on resolving relative URIs and relative paths.
Parameters
baseURI the base URI (may be null if uriSpec is an absolute URI)
uriSpec the URI spec string which may be an absolute or relative URI (can only be null/empty if base is not null)
initializeAuthority() [1/3]
void XMLUri::initializeAuthority (const XMLCh *const uriSpec) private
Initialize the authority (userinfo, host and port) for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
initializeAuthority() [2/3]
void XMLUri::initializeAuthority (const XMLCh *const uriSpec) private
Initialize the authority (userinfo, host and port) for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
initializeAuthority() [3/3]
void XMLUri::initializeAuthority (const XMLCh *const uriSpec) private
Initialize the authority (userinfo, host and port) for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
initializePath() [1/3]
void XMLUri::initializePath (const XMLCh *const uriSpec) private
Initialize the path for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
initializePath() [2/3]
void XMLUri::initializePath (const XMLCh *const uriSpec) private
Initialize the path for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
initializePath() [3/3]
void XMLUri::initializePath (const XMLCh *const uriSpec) private
Initialize the path for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
initializeScheme() [1/3]
void XMLUri::initializeScheme (const XMLCh *const uriSpec) private
Initialize the scheme for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
initializeScheme() [2/3]
void XMLUri::initializeScheme (const XMLCh *const uriSpec) private
Initialize the scheme for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
initializeScheme() [3/3]
void XMLUri::initializeScheme (const XMLCh *const uriSpec) private
Initialize the scheme for this URI from a URI string spec.
Parameters
uriSpec the URI specification (cannot be null)
isConformantSchemeName() [1/6]
static bool XMLUri::isConformantSchemeName (const XMLCh *const scheme) static private
Determine whether a scheme conforms to the rules for a scheme name. A scheme is conformant if it starts with an alphanumeric, and contains only alphanumerics, '+','-' and '.'.
Returns
true if the scheme is conformant, false otherwise
isConformantSchemeName() [2/6]
static bool XMLUri::isConformantSchemeName (const XMLCh *const scheme) static private
Determine whether a scheme conforms to the rules for a scheme name. A scheme is conformant if it starts with an alphanumeric, and contains only alphanumerics, '+','-' and '.'.
Returns
true if the scheme is conformant, false otherwise
isConformantSchemeName() [3/6]
static bool XMLUri::isConformantSchemeName (const XMLCh *const scheme) static private
Determine whether a scheme conforms to the rules for a scheme name. A scheme is conformant if it starts with an alphanumeric, and contains only alphanumerics, '+','-' and '.'.
Returns
true if the scheme is conformant, false otherwise
isConformantSchemeName() [4/6]
static bool XMLUri::isConformantSchemeName (const XMLCh *const scheme, const XMLSize_t schemeLen) static private
isConformantSchemeName() [5/6]
static bool XMLUri::isConformantSchemeName (const XMLCh *const scheme, const XMLSize_t schemeLen) static private
isConformantSchemeName() [6/6]
static bool XMLUri::isConformantSchemeName (const XMLCh *const scheme, const XMLSize_t schemeLen) static private
isConformantUserInfo() [1/3]
static void XMLUri::isConformantUserInfo (const XMLCh *const userInfo, MemoryManager *const manager) static private
Determine whether a userInfo conforms to the rules for a userinfo.
Returns
true if the scheme is conformant, false otherwise
isConformantUserInfo() [2/3]
static void XMLUri::isConformantUserInfo (const XMLCh *const userInfo, MemoryManager *const manager) static private
Determine whether a userInfo conforms to the rules for a userinfo.
Returns
true if the scheme is conformant, false otherwise
isConformantUserInfo() [3/3]
static void XMLUri::isConformantUserInfo (const XMLCh *const userInfo, MemoryManager *const manager) static private
Determine whether a userInfo conforms to the rules for a userinfo.
Returns
true if the scheme is conformant, false otherwise
isGenericURI() [1/3]
bool XMLUri::isGenericURI () private
Get the indicator as to whether this URI uses the "generic URI" syntax.
Returns
true if this URI uses the "generic URI" syntax, false otherwise
isGenericURI() [2/3]
bool XMLUri::isGenericURI () private
Get the indicator as to whether this URI uses the "generic URI" syntax.
Returns
true if this URI uses the "generic URI" syntax, false otherwise
isGenericURI() [3/3]
bool XMLUri::isGenericURI () private
Get the indicator as to whether this URI uses the "generic URI" syntax.
Returns
true if this URI uses the "generic URI" syntax, false otherwise
isPathCharacter() [1/3]
bool XMLUri::isPathCharacter (const XMLCh theChar) inline static private
Determine whether a character is a path character:
Returns
true if the character is path character
Definition at line 650 of file XMLUri.hpp.
References XMLString::indexOf().
isPathCharacter() [2/3]
static bool XMLUri::isPathCharacter (const XMLCh theChar) static private
Determine whether a character is a path character:
Returns
true if the character is path character
isPathCharacter() [3/3]
static bool XMLUri::isPathCharacter (const XMLCh theChar) static private
Determine whether a character is a path character:
Returns
true if the character is path character
isReservedCharacter() [1/3]
bool XMLUri::isReservedCharacter (const XMLCh theChar) inline static private
Determine whether a character is a reserved character:
Returns
true if the string contains any reserved characters
Definition at line 645 of file XMLUri.hpp.
References XMLString::indexOf().
isReservedCharacter() [2/3]
static bool XMLUri::isReservedCharacter (const XMLCh theChar) static private
Determine whether a character is a reserved character:
Returns
true if the string contains any reserved characters
isReservedCharacter() [3/3]
static bool XMLUri::isReservedCharacter (const XMLCh theChar) static private
Determine whether a character is a reserved character:
Returns
true if the string contains any reserved characters
isReservedOrUnreservedCharacter() [1/3]
bool XMLUri::isReservedOrUnreservedCharacter (const XMLCh theChar) inline static private
Determine whether a char is an reserved or unreserved character.
Returns
true if the char is reserved or unreserved, false otherwise
Definition at line 639 of file XMLUri.hpp.
References XMLString::indexOf(), and XMLString::isAlphaNum().
isReservedOrUnreservedCharacter() [2/3]
static bool XMLUri::isReservedOrUnreservedCharacter (const XMLCh theChar) static private
Determine whether a char is an reserved or unreserved character.
Returns
true if the char is reserved or unreserved, false otherwise
isReservedOrUnreservedCharacter() [3/3]
static bool XMLUri::isReservedOrUnreservedCharacter (const XMLCh theChar) static private
Determine whether a char is an reserved or unreserved character.
Returns
true if the char is reserved or unreserved, false otherwise
isUnreservedCharacter() [1/3]
bool XMLUri::isUnreservedCharacter (const XMLCh theChar) inline static private
Determine whether a char is an unreserved character.
Returns
true if the char is unreserved, false otherwise
Definition at line 655 of file XMLUri.hpp.
References XMLString::indexOf(), and XMLString::isAlphaNum().
isUnreservedCharacter() [2/3]
static bool XMLUri::isUnreservedCharacter (const XMLCh theChar) static private
Determine whether a char is an unreserved character.
Returns
true if the char is unreserved, false otherwise
isUnreservedCharacter() [3/3]
static bool XMLUri::isUnreservedCharacter (const XMLCh theChar) static private
Determine whether a char is an unreserved character.
Returns
true if the char is unreserved, false otherwise
isURIString() [1/3]
static bool XMLUri::isURIString (const XMLCh *const uric) static
Determine whether a given string contains only URI characters (also called "uric" in RFC 2396). uric consist of all reserved characters, unreserved characters and escaped characters.
Returns
true if the string is comprised of uric, false otherwise
isURIString() [2/3]
static bool XMLUri::isURIString (const XMLCh *const uric) static
Determine whether a given string contains only URI characters (also called "uric" in RFC 2396). uric consist of all reserved characters, unreserved characters and escaped characters.
Returns
true if the string is comprised of uric, false otherwise
isURIString() [3/3]
static bool XMLUri::isURIString (const XMLCh *const uric) static
Determine whether a given string contains only URI characters (also called "uric" in RFC 2396). uric consist of all reserved characters, unreserved characters and escaped characters.
Returns
true if the string is comprised of uric, false otherwise
isValidRegistryBasedAuthority() [1/6]
static bool XMLUri::isValidRegistryBasedAuthority (const XMLCh *const authority) static private
Determines whether the given string is a registry based authority.
Parameters
authority the authority component of a URI
Returns
true if the given string is a registry based authority
isValidRegistryBasedAuthority() [2/6]
static bool XMLUri::isValidRegistryBasedAuthority (const XMLCh *const authority) static private
Determines whether the given string is a registry based authority.
Parameters
authority the authority component of a URI
Returns
true if the given string is a registry based authority
isValidRegistryBasedAuthority() [3/6]
static bool XMLUri::isValidRegistryBasedAuthority (const XMLCh *const authority) static private
Determines whether the given string is a registry based authority.
Parameters
authority the authority component of a URI
Returns
true if the given string is a registry based authority
isValidRegistryBasedAuthority() [4/6]
static bool XMLUri::isValidRegistryBasedAuthority (const XMLCh *const authority, const XMLSize_t authLen) static private
Determines whether the given string is a registry based authority.
Parameters
authority the authority component of a URI
Returns
true if the given string is a registry based authority
isValidRegistryBasedAuthority() [5/6]
static bool XMLUri::isValidRegistryBasedAuthority (const XMLCh *const authority, const XMLSize_t authLen) static private
Determines whether the given string is a registry based authority.
Parameters
authority the authority component of a URI
Returns
true if the given string is a registry based authority
isValidRegistryBasedAuthority() [6/6]
static bool XMLUri::isValidRegistryBasedAuthority (const XMLCh *const authority, const XMLSize_t authLen) static private
Determines whether the given string is a registry based authority.
Parameters
authority the authority component of a URI
Returns
true if the given string is a registry based authority
isValidServerBasedAuthority() [1/6]
static bool XMLUri::isValidServerBasedAuthority (const XMLCh *const host, const int port, const XMLCh *const userinfo, MemoryManager *const manager) static private
Determines whether the components host, port, and user info are valid as a server authority.
Returns
true if the given host, port, and userinfo compose a valid server authority
isValidServerBasedAuthority() [2/6]
static bool XMLUri::isValidServerBasedAuthority (const XMLCh *const host, const int port, const XMLCh *const userinfo, MemoryManager *const manager) static private
Determines whether the components host, port, and user info are valid as a server authority.
Returns
true if the given host, port, and userinfo compose a valid server authority
isValidServerBasedAuthority() [3/6]
static bool XMLUri::isValidServerBasedAuthority (const XMLCh *const host, const int port, const XMLCh *const userinfo, MemoryManager *const manager) static private
Determines whether the components host, port, and user info are valid as a server authority.
Returns
true if the given host, port, and userinfo compose a valid server authority
isValidServerBasedAuthority() [4/6]
static bool XMLUri::isValidServerBasedAuthority (const XMLCh *const host, const XMLSize_t hostLen, const int port, const XMLCh *const userinfo, const XMLSize_t userLen) static private
Determines whether the components host, port, and user info are valid as a server authority.
Returns
true if the given host, port, and userinfo compose a valid server authority
isValidServerBasedAuthority() [5/6]
static bool XMLUri::isValidServerBasedAuthority (const XMLCh *const host, const XMLSize_t hostLen, const int port, const XMLCh *const userinfo, const XMLSize_t userLen) static private
Determines whether the components host, port, and user info are valid as a server authority.
Returns
true if the given host, port, and userinfo compose a valid server authority
isValidServerBasedAuthority() [6/6]
static bool XMLUri::isValidServerBasedAuthority (const XMLCh *const host, const XMLSize_t hostLen, const int port, const XMLCh *const userinfo, const XMLSize_t userLen) static private
Determines whether the components host, port, and user info are valid as a server authority.
Returns
true if the given host, port, and userinfo compose a valid server authority
isValidURI() [1/6]
static bool XMLUri::isValidURI (bool haveBaseURI, const XMLCh *const uriStr, bool bAllowSpaces = false) static
Determine whether a given string is a valid URI
isValidURI() [2/6]
static bool XMLUri::isValidURI (bool haveBaseURI, const XMLCh *const uriStr, bool bAllowSpaces = false) static
Determine whether a given string is a valid URI
isValidURI() [3/6]
static bool XMLUri::isValidURI (bool haveBaseURI, const XMLCh *const uriStr, bool bAllowSpaces = false) static
Determine whether a given string is a valid URI
isValidURI() [4/6]
static bool XMLUri::isValidURI (const XMLUri *const baseURI, const XMLCh *const uriStr, bool bAllowSpaces = false) static
Determine whether a given string is a valid URI
isValidURI() [5/6]
static bool XMLUri::isValidURI (const XMLUri *const baseURI, const XMLCh *const uriStr, bool bAllowSpaces = false) static
Determine whether a given string is a valid URI
isValidURI() [6/6]
static bool XMLUri::isValidURI (const XMLUri *const baseURI, const XMLCh *const uriStr, bool bAllowSpaces = false) static
Determine whether a given string is a valid URI
isWellFormedAddress() [1/6]
static bool XMLUri::isWellFormedAddress (const XMLCh *const addr, const XMLSize_t addrLen) static private
isWellFormedAddress() [2/6]
static bool XMLUri::isWellFormedAddress (const XMLCh *const addr, const XMLSize_t addrLen) static private
isWellFormedAddress() [3/6]
static bool XMLUri::isWellFormedAddress (const XMLCh *const addr, const XMLSize_t addrLen) static private
isWellFormedAddress() [4/6]
static bool XMLUri::isWellFormedAddress (const XMLCh *const addr, MemoryManager *const manager) static private
Determine whether a string is syntactically capable of representing a valid IPv4 address, IPv6 reference or the domain name of a network host.
A valid IPv4 address consists of four decimal digit groups separated by a '.'.
See RFC 2732 Section 3, and RFC 2373 Section 2.2, for the definition of IPv6 references.
A hostname consists of domain labels (each of which must begin and end with an alphanumeric but may contain '-') separated by a '.'. See RFC 2396 Section 3.2.2.
Returns
true if the string is a syntactically valid IPv4 address or hostname
isWellFormedAddress() [5/6]
static bool XMLUri::isWellFormedAddress (const XMLCh *const addr, MemoryManager *const manager) static private
Determine whether a string is syntactically capable of representing a valid IPv4 address, IPv6 reference or the domain name of a network host.
A valid IPv4 address consists of four decimal digit groups separated by a '.'.
See RFC 2732 Section 3, and RFC 2373 Section 2.2, for the definition of IPv6 references.
A hostname consists of domain labels (each of which must begin and end with an alphanumeric but may contain '-') separated by a '.'. See RFC 2396 Section 3.2.2.
Returns
true if the string is a syntactically valid IPv4 address or hostname
isWellFormedAddress() [6/6]
static bool XMLUri::isWellFormedAddress (const XMLCh *const addr, MemoryManager *const manager) static private
Determine whether a string is syntactically capable of representing a valid IPv4 address, IPv6 reference or the domain name of a network host.
A valid IPv4 address consists of four decimal digit groups separated by a '.'.
See RFC 2732 Section 3, and RFC 2373 Section 2.2, for the definition of IPv6 references.
A hostname consists of domain labels (each of which must begin and end with an alphanumeric but may contain '-') separated by a '.'. See RFC 2396 Section 3.2.2.
Returns
true if the string is a syntactically valid IPv4 address or hostname
isWellFormedIPv4Address() [1/3]
static bool XMLUri::isWellFormedIPv4Address (const XMLCh *const addr, const XMLSize_t length) static private
Determines whether a string is an IPv4 address as defined by RFC 2373, and under the further constraint that it must be a 32-bit address. Though not expressed in the grammar, in order to satisfy the 32-bit address constraint, each segment of the address cannot be greater than 255 (8 bits of information).
Returns
true if the string is a syntactically valid IPv4 address
isWellFormedIPv4Address() [2/3]
static bool XMLUri::isWellFormedIPv4Address (const XMLCh *const addr, const XMLSize_t length) static private
Determines whether a string is an IPv4 address as defined by RFC 2373, and under the further constraint that it must be a 32-bit address. Though not expressed in the grammar, in order to satisfy the 32-bit address constraint, each segment of the address cannot be greater than 255 (8 bits of information).
Returns
true if the string is a syntactically valid IPv4 address
isWellFormedIPv4Address() [3/3]
static bool XMLUri::isWellFormedIPv4Address (const XMLCh *const addr, const XMLSize_t length) static private
Determines whether a string is an IPv4 address as defined by RFC 2373, and under the further constraint that it must be a 32-bit address. Though not expressed in the grammar, in order to satisfy the 32-bit address constraint, each segment of the address cannot be greater than 255 (8 bits of information).
Returns
true if the string is a syntactically valid IPv4 address
isWellFormedIPv6Reference() [1/3]
static bool XMLUri::isWellFormedIPv6Reference (const XMLCh *const addr, const XMLSize_t length) static private
Determines whether a string is an IPv6 reference as defined by RFC 2732, where IPv6address is defined in RFC 2373. The IPv6 address is parsed according to Section 2.2 of RFC 2373, with the additional constraint that the address be composed of 128 bits of information.
Note: The BNF expressed in RFC 2373 Appendix B does not accurately describe section 2.2, and was in fact removed from RFC 3513, the successor of RFC 2373.
Returns
true if the string is a syntactically valid IPv6 reference
isWellFormedIPv6Reference() [2/3]
static bool XMLUri::isWellFormedIPv6Reference (const XMLCh *const addr, const XMLSize_t length) static private
Determines whether a string is an IPv6 reference as defined by RFC 2732, where IPv6address is defined in RFC 2373. The IPv6 address is parsed according to Section 2.2 of RFC 2373, with the additional constraint that the address be composed of 128 bits of information.
Note: The BNF expressed in RFC 2373 Appendix B does not accurately describe section 2.2, and was in fact removed from RFC 3513, the successor of RFC 2373.
Returns
true if the string is a syntactically valid IPv6 reference
isWellFormedIPv6Reference() [3/3]
static bool XMLUri::isWellFormedIPv6Reference (const XMLCh *const addr, const XMLSize_t length) static private
Determines whether a string is an IPv6 reference as defined by RFC 2732, where IPv6address is defined in RFC 2373. The IPv6 address is parsed according to Section 2.2 of RFC 2373, with the additional constraint that the address be composed of 128 bits of information.
Note: The BNF expressed in RFC 2373 Appendix B does not accurately describe section 2.2, and was in fact removed from RFC 3513, the successor of RFC 2373.
Returns
true if the string is a syntactically valid IPv6 reference
normalizeURI() [1/3]
static void XMLUri::normalizeURI (const XMLCh *const systemURI, XMLBuffer & normalizedURI) static
normalizeURI() [2/3]
static void XMLUri::normalizeURI (const XMLCh *const systemURI, XMLBuffer & normalizedURI) static
normalizeURI() [3/3]
static void XMLUri::normalizeURI (const XMLCh *const systemURI, XMLBuffer & normalizedURI) static
operator=() [1/3]
XMLUri& XMLUri::operator= (const XMLUri & toAssign)
operator=() [2/3]
XMLUri& XMLUri::operator= (const XMLUri & toAssign)
operator=() [3/3]
XMLUri& XMLUri::operator= (const XMLUri & toAssign)
processAuthority() [1/3]
static bool XMLUri::processAuthority (const XMLCh *const uriStr, const XMLSize_t authLen) static private
processAuthority() [2/3]
static bool XMLUri::processAuthority (const XMLCh *const uriStr, const XMLSize_t authLen) static private
processAuthority() [3/3]
static bool XMLUri::processAuthority (const XMLCh *const uriStr, const XMLSize_t authLen) static private
processPath() [1/3]
static bool XMLUri::processPath (const XMLCh *const pathStr, const XMLSize_t pathStrLen, const bool isSchemePresent, const bool bAllowSpaces = false) static private
processPath() [2/3]
static bool XMLUri::processPath (const XMLCh *const pathStr, const XMLSize_t pathStrLen, const bool isSchemePresent, const bool bAllowSpaces = false) static private
processPath() [3/3]
static bool XMLUri::processPath (const XMLCh *const pathStr, const XMLSize_t pathStrLen, const bool isSchemePresent, const bool bAllowSpaces = false) static private
processScheme() [1/3]
static bool XMLUri::processScheme (const XMLCh *const uriStr, XMLSize_t & index) static private
processScheme() [2/3]
static bool XMLUri::processScheme (const XMLCh *const uriStr, XMLSize_t & index) static private
processScheme() [3/3]
static bool XMLUri::processScheme (const XMLCh *const uriStr, XMLSize_t & index) static private
scanHexSequence() [1/3]
static int XMLUri::scanHexSequence (const XMLCh *const addr, XMLSize_t index, XMLSize_t end, int & counter) static private
Helper function for isWellFormedIPv6Reference which scans the hex sequences of an IPv6 address. It returns the index of the next character to scan in the address, or -1 if the string cannot match a valid IPv6 address.
Parameters
address the string to be scanned
index the beginning index (inclusive)
end the ending index (exclusive)
counter a counter for the number of 16-bit sections read in the address
Returns
the index of the next character to scan, or -1 if the string cannot match a valid IPv6 address
scanHexSequence() [2/3]
static int XMLUri::scanHexSequence (const XMLCh *const addr, XMLSize_t index, XMLSize_t end, int & counter) static private
Helper function for isWellFormedIPv6Reference which scans the hex sequences of an IPv6 address. It returns the index of the next character to scan in the address, or -1 if the string cannot match a valid IPv6 address.
Parameters
address the string to be scanned
index the beginning index (inclusive)
end the ending index (exclusive)
counter a counter for the number of 16-bit sections read in the address
Returns
the index of the next character to scan, or -1 if the string cannot match a valid IPv6 address
scanHexSequence() [3/3]
static int XMLUri::scanHexSequence (const XMLCh *const addr, XMLSize_t index, XMLSize_t end, int & counter) static private
Helper function for isWellFormedIPv6Reference which scans the hex sequences of an IPv6 address. It returns the index of the next character to scan in the address, or -1 if the string cannot match a valid IPv6 address.
Parameters
address the string to be scanned
index the beginning index (inclusive)
end the ending index (exclusive)
counter a counter for the number of 16-bit sections read in the address
Returns
the index of the next character to scan, or -1 if the string cannot match a valid IPv6 address
setFragment() [1/3]
void XMLUri::setFragment (const XMLCh *const newFragment)
Set the fragment for this URI. A non-null value is valid only if this is a URI conforming to the generic URI syntax and the path value is not null.
Parameters
newFragment the fragment for this URI
setFragment() [2/3]
void XMLUri::setFragment (const XMLCh *const newFragment)
Set the fragment for this URI. A non-null value is valid only if this is a URI conforming to the generic URI syntax and the path value is not null.
Parameters
newFragment the fragment for this URI
setFragment() [3/3]
void XMLUri::setFragment (const XMLCh *const newFragment)
Set the fragment for this URI. A non-null value is valid only if this is a URI conforming to the generic URI syntax and the path value is not null.
Parameters
newFragment the fragment for this URI
setHost() [1/3]
void XMLUri::setHost (const XMLCh *const newHost)
Set the host for this URI. If null is passed in, the userinfo field is also set to null and the port is set to -1.
Note: This method overwrites registry based authority if it previously existed in this URI.
Parameters
newHost the host for this URI
setHost() [2/3]
void XMLUri::setHost (const XMLCh *const newHost)
Set the host for this URI. If null is passed in, the userinfo field is also set to null and the port is set to -1.
Note: This method overwrites registry based authority if it previously existed in this URI.
Parameters
newHost the host for this URI
setHost() [3/3]
void XMLUri::setHost (const XMLCh *const newHost)
Set the host for this URI. If null is passed in, the userinfo field is also set to null and the port is set to -1.
Note: This method overwrites registry based authority if it previously existed in this URI.
Parameters
newHost the host for this URI
setPath() [1/3]
void XMLUri::setPath (const XMLCh *const newPath)
Set the path for this URI.
If the supplied path is null, then the query string and fragment are set to null as well.
If the supplied path includes a query string and/or fragment, these fields will be parsed and set as well.
Note:
For URIs following the "generic URI" syntax, the path specified should start with a slash.
For URIs that do not follow the generic URI syntax, this method sets the scheme-specific part.
Parameters
newPath the path for this URI (may be null)
setPath() [2/3]
void XMLUri::setPath (const XMLCh *const newPath)
Set the path for this URI.
If the supplied path is null, then the query string and fragment are set to null as well.
If the supplied path includes a query string and/or fragment, these fields will be parsed and set as well.
Note:
For URIs following the "generic URI" syntax, the path specified should start with a slash.
For URIs that do not follow the generic URI syntax, this method sets the scheme-specific part.
Parameters
newPath the path for this URI (may be null)
setPath() [3/3]
void XMLUri::setPath (const XMLCh *const newPath)
Set the path for this URI.
If the supplied path is null, then the query string and fragment are set to null as well.
If the supplied path includes a query string and/or fragment, these fields will be parsed and set as well.
Note:
For URIs following the "generic URI" syntax, the path specified should start with a slash.
For URIs that do not follow the generic URI syntax, this method sets the scheme-specific part.
Parameters
newPath the path for this URI (may be null)
setPort() [1/3]
void XMLUri::setPort (int newPort)
Set the port for this URI. -1 is used to indicate that the port is not specified, otherwise valid port numbers are between 0 and 65535. If a valid port number is passed in and the host field is null, an exception is thrown.
Parameters
newPort the port number for this URI
setPort() [2/3]
void XMLUri::setPort (int newPort)
Set the port for this URI. -1 is used to indicate that the port is not specified, otherwise valid port numbers are between 0 and 65535. If a valid port number is passed in and the host field is null, an exception is thrown.
Parameters
newPort the port number for this URI
setPort() [3/3]
void XMLUri::setPort (int newPort)
Set the port for this URI. -1 is used to indicate that the port is not specified, otherwise valid port numbers are between 0 and 65535. If a valid port number is passed in and the host field is null, an exception is thrown.
Parameters
newPort the port number for this URI
setQueryString() [1/3]
void XMLUri::setQueryString (const XMLCh *const newQueryString)
Set the query string for this URI. A non-null value is valid only if this is an URI conforming to the generic URI syntax and the path value is not null.
Parameters
newQueryString the query string for this URI
setQueryString() [2/3]
void XMLUri::setQueryString (const XMLCh *const newQueryString)
Set the query string for this URI. A non-null value is valid only if this is an URI conforming to the generic URI syntax and the path value is not null.
Parameters
newQueryString the query string for this URI
setQueryString() [3/3]
void XMLUri::setQueryString (const XMLCh *const newQueryString)
Set the query string for this URI. A non-null value is valid only if this is an URI conforming to the generic URI syntax and the path value is not null.
Parameters
newQueryString the query string for this URI
setRegBasedAuthority() [1/3]
void XMLUri::setRegBasedAuthority (const XMLCh *const newRegAuth)
Sets the registry based authority for this URI.
Note: This method overwrites server based authority if it previously existed in this URI.
Parameters
newRegAuth the registry based authority for this URI
setRegBasedAuthority() [2/3]
void XMLUri::setRegBasedAuthority (const XMLCh *const newRegAuth)
Sets the registry based authority for this URI.
Note: This method overwrites server based authority if it previously existed in this URI.
Parameters
newRegAuth the registry based authority for this URI
setRegBasedAuthority() [3/3]
void XMLUri::setRegBasedAuthority (const XMLCh *const newRegAuth)
Sets the registry based authority for this URI.
Note: This method overwrites server based authority if it previously existed in this URI.
Parameters
newRegAuth the registry based authority for this URI
setScheme() [1/3]
void XMLUri::setScheme (const XMLCh *const newScheme)
Set the scheme for this URI. The scheme is converted to lowercase before it is set.
Parameters
newScheme the scheme for this URI (cannot be null)
setScheme() [2/3]
void XMLUri::setScheme (const XMLCh *const newScheme)
Set the scheme for this URI. The scheme is converted to lowercase before it is set.
Parameters
newScheme the scheme for this URI (cannot be null)
setScheme() [3/3]
void XMLUri::setScheme (const XMLCh *const newScheme)
Set the scheme for this URI. The scheme is converted to lowercase before it is set.
Parameters
newScheme the scheme for this URI (cannot be null)
setUserInfo() [1/3]
void XMLUri::setUserInfo (const XMLCh *const newUserInfo)
Set the userinfo for this URI. If a non-null value is passed in and the host value is null, then an exception is thrown.
Parameters
newUserInfo the userinfo for this URI
setUserInfo() [2/3]
void XMLUri::setUserInfo (const XMLCh *const newUserInfo)
Set the userinfo for this URI. If a non-null value is passed in and the host value is null, then an exception is thrown.
Parameters
newUserInfo the userinfo for this URI
setUserInfo() [3/3]
void XMLUri::setUserInfo (const XMLCh *const newUserInfo)
Set the userinfo for this URI. If a non-null value is passed in and the host value is null, then an exception is thrown.
Parameters
newUserInfo the userinfo for this URI
Member Data Documentation
fFragment
XMLCh * XMLUri::fFragment private
Definition at line 575 of file XMLUri.hpp.
fHost
XMLCh * XMLUri::fHost private
Definition at line 571 of file XMLUri.hpp.
fMemoryManager
MemoryManager * XMLUri::fMemoryManager private
Definition at line 577 of file XMLUri.hpp.
fPath
XMLCh * XMLUri::fPath private
Definition at line 573 of file XMLUri.hpp.
fPort
int XMLUri::fPort private
Definition at line 568 of file XMLUri.hpp.
fQueryString
XMLCh * XMLUri::fQueryString private
Definition at line 574 of file XMLUri.hpp.
fRegAuth
XMLCh * XMLUri::fRegAuth private
Definition at line 572 of file XMLUri.hpp.
fScheme
XMLCh * XMLUri::fScheme private
Definition at line 569 of file XMLUri.hpp.
fURIText
XMLCh * XMLUri::fURIText private
Definition at line 576 of file XMLUri.hpp.
fUserInfo
XMLCh * XMLUri::fUserInfo private
Definition at line 570 of file XMLUri.hpp.
MARK_CHARACTERS
static const XMLCh XMLUri::MARK_CHARACTERS static private
Definition at line 319 of file XMLUri.hpp.
MARK_OR_RESERVED_CHARACTERS
static const XMLCh XMLUri::MARK_OR_RESERVED_CHARACTERS static private
Definition at line 317 of file XMLUri.hpp.
PATH_CHARACTERS
static const XMLCh XMLUri::PATH_CHARACTERS static private
Definition at line 323 of file XMLUri.hpp.
REG_NAME_CHARACTERS
static const XMLCh XMLUri::REG_NAME_CHARACTERS static private
Definition at line 322 of file XMLUri.hpp.
RESERVED_CHARACTERS
static const XMLCh XMLUri::RESERVED_CHARACTERS static private
Definition at line 318 of file XMLUri.hpp.
SCHEME_CHARACTERS
static const XMLCh XMLUri::SCHEME_CHARACTERS static private
Definition at line 320 of file XMLUri.hpp.
USERINFO_CHARACTERS
static const XMLCh XMLUri::USERINFO_CHARACTERS static private
Definition at line 321 of file XMLUri.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/XMLUri.hpp