Seamly2D: SeamlyMePreferencesPathPage Class Reference
SeamlyMePreferencesPathPage Class Reference
#include <seamlymepreferencespathpage.h>
Public Member Functions
SeamlyMePreferencesPathPage (QWidget *parent=nullptr)
virtual ~SeamlyMePreferencesPathPage ()
void Apply ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
Private Slots
void defaultPath ()
void editPath ()
Private Member Functions
void initializeTable ()
Private Attributes
Ui::SeamlyMePreferencesPathPage * ui
Detailed Description
Definition at line 66 of file seamlymepreferencespathpage.h.
Constructor & Destructor Documentation
SeamlyMePreferencesPathPage()
SeamlyMePreferencesPathPage::SeamlyMePreferencesPathPage (QWidget * parent = nullptr) explicit
Definition at line 65 of file seamlymepreferencespathpage.cpp.
References defaultPath(), editPath(), initializeTable(), and ui.
~SeamlyMePreferencesPathPage()
SeamlyMePreferencesPathPage::~SeamlyMePreferencesPathPage () virtual
Definition at line 78 of file seamlymepreferencespathpage.cpp.
References ui.
Member Function Documentation
Apply()
void SeamlyMePreferencesPathPage::Apply ()
Definition at line 94 of file seamlymepreferencespathpage.cpp.
References qApp, VCommonSettings::setBodyScansPath(), VCommonSettings::setIndividualSizePath(), VCommonSettings::setMultisizePath(), VCommonSettings::setTemplatePath(), and ui.
Referenced by DialogSeamlyMePreferences::Apply().
changeEvent()
void SeamlyMePreferencesPathPage::changeEvent (QEvent * event) protected virtual
Definition at line 84 of file seamlymepreferencespathpage.cpp.
References ui.
defaultPath
void SeamlyMePreferencesPathPage::defaultPath () private slot
Definition at line 104 of file seamlymepreferencespathpage.cpp.
References VCommonSettings::getDefaultBodyScansPath(), VCommonSettings::getDefaultIndividualSizePath(), VCommonSettings::getDefaultMultisizePath(), VCommonSettings::getDefaultTemplatePath(), SCASSERT, and ui.
Referenced by SeamlyMePreferencesPathPage().
editPath
void SeamlyMePreferencesPathPage::editPath () private slot
Definition at line 134 of file seamlymepreferencespathpage.cpp.
References fileDialog(), VCommonSettings::prepareMultisizeTables(), qApp, SCASSERT, and ui.
Referenced by SeamlyMePreferencesPathPage().
initializeTable()
void SeamlyMePreferencesPathPage::initializeTable () private
Definition at line 191 of file seamlymepreferencespathpage.cpp.
References VCommonSettings::getBodyScansPath(), VCommonSettings::getIndividualSizePath(), VCommonSettings::getMultisizePath(), VCommonSettings::getTemplatePath(), qApp, and ui.
Referenced by SeamlyMePreferencesPathPage().
Member Data Documentation
ui
Ui::SeamlyMePreferencesPathPage* SeamlyMePreferencesPathPage::ui private
Definition at line 85 of file seamlymepreferencespathpage.h.
Referenced by Apply(), changeEvent(), defaultPath(), editPath(), initializeTable(), SeamlyMePreferencesPathPage(), and ~SeamlyMePreferencesPathPage().
The documentation for this class was generated from the following files:
src/app/seamlyme/dialogs/configpages/seamlymepreferencespathpage.h
src/app/seamlyme/dialogs/configpages/seamlymepreferencespathpage.cpp