Seamly2D: VAbstractBezier Class Reference
VAbstractBezier Class Reference abstract
#include <vabstractbezier.h>
Public Member Functions
VAbstractBezier (const GOType &type, const quint32 &idObject=null_id, const Draw &mode=Draw::Calculation)
VAbstractBezier (const VAbstractBezier &curve)
VAbstractBezier & operator= (const VAbstractBezier &curve)
virtual ~VAbstractBezier ()
virtual qreal GetC1Length () const =0
virtual qreal GetC2Length () const =0
Public Member Functions inherited from VAbstractCurve
VAbstractCurve (const GOType &type, const quint32 &idObject=null_id, const Draw &mode=Draw::Calculation)
VAbstractCurve (const VAbstractCurve &curve)
virtual ~VAbstractCurve () Q_DECL_OVERRIDE
VAbstractCurve & operator= (const VAbstractCurve &curve)
void Swap (VAbstractCurve &curve) Q_DECL_NOTHROW
virtual QVector< QPointF > getPoints () const =0
QVector< QPointF > GetSegmentPoints (const QPointF &begin, const QPointF &end, bool reverse=false) const
virtual QPainterPath GetPath () const
virtual qreal GetLength () const =0
qreal GetLengthByPoint (const QPointF &point) const
virtual QVector< QPointF > IntersectLine (const QLineF &line) const
IntersectLine return list of points for real intersection with line.
virtual bool IsIntersectLine (const QLineF &line) const
bool isPointOnCurve (const QPointF &p) const
virtual qreal GetStartAngle () const =0
virtual qreal GetEndAngle () const =0
quint32 GetDuplicate () const
void SetDuplicate (quint32 number)
QString getLineColor () const
void setLineColor (const QString &color)
QString GetPenStyle () const
void SetPenStyle (const QString &penStyle)
QString getLineWeight () const
getLineWeight return weight of the lines
void setLineWeight (const QString &lineWeight)
setLineWeight set weight of the lines
QPointF getFirstPoint ()
QPointF getLastPoint ()
virtual QString NameForHistory (const QString &toolName) const =0
virtual QVector< DirectionArrow > DirectionArrows () const
Public Member Functions inherited from VGObject
VGObject ()
VGObject default constructor.
VGObject (const GOType &type, const quint32 &idObject=0, const Draw &mode=Draw::Calculation)
VGObject constructor.
VGObject (const VGObject &obj)
VGObject copy constructor.
virtual ~VGObject ()
VGObject & operator= (const VGObject &obj)
operator = assignment operator.
void Swap (VGObject &obj) Q_DECL_NOTHROW
quint32 getIdObject () const
getIdObject return parent id.
void setIdObject (const quint32 &value)
setIdObject set parent id.
virtual QString name () const
name return name graphical object.
void setName (const QString &name)
setName set name graphical object.
Draw getMode () const
getMode return mode creation.
void setMode (const Draw &value)
setMode set mode creation.
GOType getType () const
getType return object type.
void setType (const GOType &type)
quint32 id () const
id return id object.
virtual void setId (const quint32 &id)
setId set id object.
quint32 getIdTool () const
Additional Inherited Members
Static Public Member Functions inherited from VAbstractCurve
static QVector< QPointF > GetSegmentPoints (const QVector< QPointF > &points, const QPointF &begin, const QPointF &end, bool reverse=false)
static bool isPointOnCurve (const QVector< QPointF > &points, const QPointF &p)
static qreal PathLength (const QVector< QPointF > &path)
static QVector< QPointF > CurveIntersectLine (const QVector< QPointF > &points, const QLineF &line)
static QPainterPath ShowDirection (const QVector< DirectionArrow > &arrows, qreal width)
Static Public Member Functions inherited from VGObject
static QLineF BuildLine (const QPointF &p1, const qreal &length, const qreal &angle)
static QPointF BuildRay (const QPointF &firstPoint, const qreal &angle, const QRectF &scRect)
static QLineF BuildAxis (const QPointF &p, const qreal &angle, const QRectF &scRect)
static QLineF BuildAxis (const QPointF &p1, const QPointF &p2, const QRectF &scRect)
static int ContactPoints (const QPointF &p, const QPointF &center, qreal radius, QPointF &p1, QPointF &p2)
static QPointF LineIntersectRect (const QRectF &rec, const QLineF &line)
LineIntersectRect find point intersection line and rect.
static int IntersectionCircles (const QPointF &c1, double r1, const QPointF &c2, double r2, QPointF &p1, QPointF &p2)
static qint32 LineIntersectCircle (const QPointF &center, qreal radius, const QLineF &line, QPointF &p1, QPointF &p2)
LineIntersectCircle find point intersection line and circle.
static QPointF ClosestPoint (const QLineF &line, const QPointF &point)
ClosestPoint find point projection of point onto line.
static QPointF addVector (const QPointF &p, const QPointF &p1, const QPointF &p2, qreal k)
static void LineCoefficients (const QLineF &line, qreal *a, qreal *b, qreal *c)
LineCoefficients coefficient for equation of segment. Segment equestion ax+by+c=0.
static bool IsPointOnLineSegment (const QPointF &t, const QPointF &p1, const QPointF &p2)
IsPointOnLineSegment Check if the point is on the line segment.
static bool IsPointOnLineviaPDP (const QPointF &t, const QPointF &p1, const QPointF &p2)
IsPointOnLineviaPDP use the perp dot product (PDP) way.
template<typename T >
static QVector< T > GetReversePoints (const QVector< T > &points)
GetReversePoint return revers container of points.
static int GetLengthContour (const QVector< QPointF > &contour, const QVector< QPointF > &newPoints)
GetLengthContour return length of contour.
Static Public Attributes inherited from VAbstractCurve
static const qreal lengthCurveDirectionArrow = 14
Static Public Attributes inherited from VGObject
static const double accuracyPointOnLine = (0.1555 / 25.4) * 96.0
Protected Member Functions inherited from VAbstractCurve
virtual void CreateName ()=0
Static Protected Member Functions inherited from VGObject
static QTransform flipTransform (const QLineF &axis)
Detailed Description
Definition at line 59 of file vabstractbezier.h.
Constructor & Destructor Documentation
VAbstractBezier() [1/2]
VAbstractBezier::VAbstractBezier (const GOType & type, const quint32 & idObject = null_id, const Draw & mode = Draw::Calculation)
Definition at line 55 of file vabstractbezier.cpp.
VAbstractBezier() [2/2]
VAbstractBezier::VAbstractBezier (const VAbstractBezier & curve)
Definition at line 61 of file vabstractbezier.cpp.
~VAbstractBezier()
VAbstractBezier::~VAbstractBezier () virtual
Definition at line 78 of file vabstractbezier.cpp.
Member Function Documentation
GetC1Length()
virtual qreal VAbstractBezier::GetC1Length () const pure virtual
Implemented in VSplinePath, VSpline, VCubicBezierPath, and VCubicBezier.
Referenced by VCurveCLength::VCurveCLength().
GetC2Length()
virtual qreal VAbstractBezier::GetC2Length () const pure virtual
Implemented in VSplinePath, VSpline, VCubicBezierPath, and VCubicBezier.
Referenced by VCurveCLength::VCurveCLength().
operator=()
VAbstractBezier & VAbstractBezier::operator= (const VAbstractBezier & curve)
Definition at line 67 of file vabstractbezier.cpp.
References VAbstractCurve::operator=().
Referenced by VAbstractCubicBezierPath::operator=().
The documentation for this class was generated from the following files:
src/libs/vgeometry/vabstractbezier.h
src/libs/vgeometry/vabstractbezier.cpp