Seamly2D: MeasurementDoc Class Reference
MeasurementDoc Class Reference
#include <measurements.h>
Public Member Functions
MeasurementDoc (VContainer *data)
MeasurementDoc (Unit unit, VContainer *data)
MeasurementDoc (Unit unit, int baseSize, int baseHeight, VContainer *data)
virtual ~MeasurementDoc () Q_DECL_EQ_DEFAULT
virtual void setXMLContent (const QString &fileName) Q_DECL_OVERRIDE
virtual bool SaveDocument (const QString &fileName, QString &error) Q_DECL_OVERRIDE
void addEmpty (const QString &name, const QString &formula=QString())
void AddEmptyAfter (const QString &after, const QString &name, const QString &formula=QString())
void Remove (const QString &name)
void MoveTop (const QString &name)
void MoveUp (const QString &name)
void MoveDown (const QString &name)
void MoveBottom (const QString &name)
void readMeasurements () const
void ClearForExport ()
MeasurementsType Type () const
int BaseSize () const
int BaseHeight () const
QString Notes () const
void SetNotes (const QString &text)
QString FamilyName () const
void SetFamilyName (const QString &text)
QString GivenName () const
void SetGivenName (const QString &text)
QDate BirthDate () const
void SetBirthDate (const QDate &date)
GenderType Gender () const
void SetGender (const GenderType &gender)
QString PMSystem () const
void SetPMSystem (const QString &system)
QString Email () const
void SetEmail (const QString &text)
bool isReadOnly () const
void SetReadOnly (bool ro)
void setSize (qreal *size)
void setHeight (qreal *height)
void SetMName (const QString &name, const QString &text)
void SetMValue (const QString &name, const QString &text)
void SetMBaseValue (const QString &name, double value)
void SetMSizeIncrease (const QString &name, double value)
void SetMHeightIncrease (const QString &name, double value)
void SetMDescription (const QString &name, const QString &text)
void SetMFullName (const QString &name, const QString &text)
QStringList ListAll () const
QStringList listKnown () const
bool eachKnownNameIsValid () const
VContainer * GetData () const
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit measurementUnits () const
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Static Public Member Functions
static QString GenderToStr (const GenderType &sex)
static GenderType StrToGender (const QString &sex)
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Static Public Attributes
static const QString TagVST = QStringLiteral("vst")
static const QString TagVIT = QStringLiteral("vit")
static const QString TagSMMS = QStringLiteral("smms")
static const QString TagSMIS = QStringLiteral("smis")
static const QString TagBodyMeasurements = QStringLiteral("body-measurements")
static const QString TagNotes = QStringLiteral("notes")
static const QString TagSize = QStringLiteral("size")
static const QString TagHeight = QStringLiteral("height")
static const QString TagPersonal = QStringLiteral("personal")
static const QString TagFamilyName = QStringLiteral("family-name")
static const QString TagGivenName = QStringLiteral("given-name")
static const QString TagBirthDate = QStringLiteral("birth-date")
static const QString TagGender = QStringLiteral("gender")
static const QString TagPMSystem = QStringLiteral("pm_system")
static const QString TagEmail = QStringLiteral("email")
static const QString TagReadOnly = QStringLiteral("read-only")
static const QString TagMeasurement = QStringLiteral("m")
static const QString AttrBase = QStringLiteral("base")
static const QString AttrValue = QStringLiteral("value")
static const QString AttrSizeIncrease = QStringLiteral("size_increase")
static const QString AttrHeightIncrease = QStringLiteral("height_increase")
static const QString AttrDescription = QStringLiteral("description")
static const QString AttrName = QStringLiteral("name")
static const QString AttrFullName = QStringLiteral("full_name")
static const QString GenderMale = QStringLiteral("male")
static const QString GenderFemale = QStringLiteral("female")
static const QString GenderUnknown = QStringLiteral("unknown")
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Private Member Functions
void CreateEmptyMultisizeFile (Unit unit, int baseSize, int baseHeight)
void CreateEmptyIndividualFile (Unit unit)
qreal UniqueTagAttr (const QString &tag, const QString &attr, qreal defValue) const
QDomElement MakeEmpty (const QString &name, const QString &formula)
QDomElement FindM (const QString &name) const
MeasurementsType ReadType () const
qreal EvalFormula (VContainer *data, const QString &formula, bool *ok) const
QString ClearPMCode (const QString &code) const
Private Attributes
VContainer * data
data container with data.
MeasurementsType type
qreal * m_currentSize
qreal * m_currentHeight
Additional Inherited Members
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Detailed Description
Definition at line 72 of file measurements.h.
Constructor & Destructor Documentation
MeasurementDoc() [1/3]
MeasurementDoc::MeasurementDoc (VContainer * data) explicit
Definition at line 127 of file measurements.cpp.
References data, SCASSERT, and Unknown.
MeasurementDoc() [2/3]
MeasurementDoc::MeasurementDoc (Unit unit, VContainer * data)
Definition at line 138 of file measurements.cpp.
References CreateEmptyIndividualFile(), data, Individual, and SCASSERT.
MeasurementDoc() [3/3]
MeasurementDoc::MeasurementDoc (Unit unit, int baseSize, int baseHeight, VContainer * data)
Definition at line 151 of file measurements.cpp.
References CreateEmptyMultisizeFile(), data, Multisize, and SCASSERT.
~MeasurementDoc()
virtual MeasurementDoc::~MeasurementDoc () virtual
Member Function Documentation
addEmpty()
void MeasurementDoc::addEmpty (const QString & name, const QString & formula = QString())
Definition at line 185 of file measurements.cpp.
References MakeEmpty(), and TagBodyMeasurements.
Referenced by TMainWindow::AddCustom(), TMainWindow::AddKnown(), and TMainWindow::ImportFromPattern().
AddEmptyAfter()
void MeasurementDoc::AddEmptyAfter (const QString & after, const QString & name, const QString & formula = QString())
Definition at line 194 of file measurements.cpp.
References FindM(), MakeEmpty(), and TagBodyMeasurements.
Referenced by TMainWindow::AddCustom(), TMainWindow::AddKnown(), and TMainWindow::ImportFromPattern().
BaseHeight()
int MeasurementDoc::BaseHeight () const
Definition at line 405 of file measurements.cpp.
References AttrBase, Multisize, TagHeight, type, and UniqueTagAttr().
Referenced by TMainWindow::changeEvent(), TMainWindow::InitWindow(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), and readMeasurements().
BaseSize()
int MeasurementDoc::BaseSize () const
Definition at line 392 of file measurements.cpp.
References AttrBase, Multisize, TagSize, type, and UniqueTagAttr().
Referenced by TMainWindow::changeEvent(), TMainWindow::InitWindow(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), and readMeasurements().
BirthDate()
QDate MeasurementDoc::BirthDate () const
Definition at line 463 of file measurements.cpp.
References defBirthDate, TagBirthDate, and VDomDocument::UniqueTagText().
Referenced by TMainWindow::InitWindow(), and TMainWindow::SaveBirthDate().
ClearForExport()
void MeasurementDoc::ClearForExport ()
Definition at line 368 of file measurements.cpp.
References AttrValue, qmu::QmuTokenParser::IsSingle(), VDomDocument::SetAttribute(), and TagMeasurement.
Referenced by TMainWindow::LoadFromExistingFile().
ClearPMCode()
QString MeasurementDoc::ClearPMCode (const QString & code) const private
Definition at line 966 of file measurements.cpp.
Referenced by CreateEmptyIndividualFile(), CreateEmptyMultisizeFile(), PMSystem(), and SetPMSystem().
CreateEmptyIndividualFile()
void MeasurementDoc::CreateEmptyIndividualFile (Unit unit) private
Definition at line 789 of file measurements.cpp.
References ClearPMCode(), defBirthDate, anonymous_namespace{measurements.cpp}::FileComment(), GenderToStr(), IndividualSizeConverter::MeasurementMaxVerStr, p998_S, TagBirthDate, TagBodyMeasurements, TagEmail, TagFamilyName, TagGender, TagGivenName, TagNotes, TagPersonal, TagPMSystem, TagReadOnly, TagSMIS, VDomDocument::TagUnit, VDomDocument::TagVersion, UnitsToStr(), and Unknown.
Referenced by MeasurementDoc().
CreateEmptyMultisizeFile()
void MeasurementDoc::CreateEmptyMultisizeFile (Unit unit, int baseSize, int baseHeight) private
Definition at line 746 of file measurements.cpp.
References AttrBase, ClearPMCode(), anonymous_namespace{measurements.cpp}::FileComment(), MultiSizeConverter::MeasurementMaxVerStr, p998_S, VDomDocument::SetAttribute(), TagBodyMeasurements, TagHeight, TagNotes, TagPMSystem, TagReadOnly, TagSize, TagSMMS, VDomDocument::TagUnit, VDomDocument::TagVersion, and UnitsToStr().
Referenced by MeasurementDoc().
eachKnownNameIsValid()
bool MeasurementDoc::eachKnownNameIsValid () const
Definition at line 717 of file measurements.cpp.
References AllGroupNames(), and listKnown().
Referenced by TMainWindow::LoadFile(), and TMainWindow::LoadFromExistingFile().
Email()
QString MeasurementDoc::Email () const
Definition at line 508 of file measurements.cpp.
References TagEmail, and VDomDocument::UniqueTagText().
Referenced by TMainWindow::InitWindow(), and TMainWindow::SaveEmail().
EvalFormula()
qreal MeasurementDoc::EvalFormula (VContainer * data, const QString & formula, bool * ok) const private
Definition at line 936 of file measurements.cpp.
References data, and VContainer::DataVariables().
Referenced by readMeasurements().
FamilyName()
QString MeasurementDoc::FamilyName () const
Definition at line 433 of file measurements.cpp.
References TagFamilyName, and VDomDocument::UniqueTagText().
Referenced by TMainWindow::InitWindow(), and TMainWindow::SaveFamilyName().
FindM()
QDomElement MeasurementDoc::FindM (const QString & name) const private
Definition at line 891 of file measurements.cpp.
References AttrName, and TagMeasurement.
Referenced by AddEmptyAfter(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), Remove(), SetMBaseValue(), SetMDescription(), SetMFullName(), SetMHeightIncrease(), SetMName(), SetMSizeIncrease(), and SetMValue().
Gender()
GenderType MeasurementDoc::Gender () const
Definition at line 478 of file measurements.cpp.
References GenderUnknown, StrToGender(), TagGender, and VDomDocument::UniqueTagText().
Referenced by TMainWindow::InitWindow(), and TMainWindow::SaveGender().
GenderToStr()
QString MeasurementDoc::GenderToStr (const GenderType & sex) static
Definition at line 652 of file measurements.cpp.
References Female, GenderFemale, GenderMale, GenderUnknown, Male, and Unknown.
Referenced by CreateEmptyIndividualFile(), and SetGender().
GetData()
VContainer * MeasurementDoc::GetData () const
Definition at line 740 of file measurements.cpp.
References data.
GivenName()
QString MeasurementDoc::GivenName () const
Definition at line 448 of file measurements.cpp.
References TagGivenName, and VDomDocument::UniqueTagText().
Referenced by TMainWindow::InitWindow(), and TMainWindow::SaveGivenName().
isReadOnly()
bool MeasurementDoc::isReadOnly () const
Definition at line 523 of file measurements.cpp.
References falseStr, TagReadOnly, trueStr, and VDomDocument::UniqueTagText().
Referenced by TMainWindow::FileNew(), TMainWindow::FileSaveAs(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), SetBirthDate(), SetEmail(), SetFamilyName(), SetGender(), SetGivenName(), SetNotes(), and SetPMSystem().
ListAll()
QStringList MeasurementDoc::ListAll () const
Definition at line 683 of file measurements.cpp.
References AttrName, and TagMeasurement.
Referenced by MainWindow::checkRequiredMeasurements(), TMainWindow::ImportFromPattern(), and listKnown().
listKnown()
QStringList MeasurementDoc::listKnown () const
Definition at line 701 of file measurements.cpp.
References CustomMSign, and ListAll().
Referenced by TMainWindow::AddKnown(), and eachKnownNameIsValid().
MakeEmpty()
QDomElement MeasurementDoc::MakeEmpty (const QString & name, const QString & formula) private
Definition at line 863 of file measurements.cpp.
References AttrBase, AttrHeightIncrease, AttrName, AttrSizeIncrease, AttrValue, Multisize, VDomDocument::SetAttribute(), TagMeasurement, and type.
Referenced by addEmpty(), and AddEmptyAfter().
MoveBottom()
void MeasurementDoc::MoveBottom (const QString & name)
Definition at line 268 of file measurements.cpp.
References FindM(), TagBodyMeasurements, and TagMeasurement.
Referenced by TMainWindow::MoveBottom().
MoveDown()
void MeasurementDoc::MoveDown (const QString & name)
Definition at line 253 of file measurements.cpp.
References FindM(), TagBodyMeasurements, and TagMeasurement.
Referenced by TMainWindow::MoveDown().
MoveTop()
void MeasurementDoc::MoveTop (const QString & name)
Definition at line 219 of file measurements.cpp.
References FindM(), TagBodyMeasurements, and TagMeasurement.
Referenced by TMainWindow::MoveTop().
MoveUp()
void MeasurementDoc::MoveUp (const QString & name)
Definition at line 238 of file measurements.cpp.
References FindM(), TagBodyMeasurements, and TagMeasurement.
Referenced by TMainWindow::MoveUp().
Notes()
QString MeasurementDoc::Notes () const
Definition at line 418 of file measurements.cpp.
References TagNotes, and VDomDocument::UniqueTagText().
Referenced by TMainWindow::InitWindow(), and TMainWindow::SaveNotes().
PMSystem()
QString MeasurementDoc::PMSystem () const
Definition at line 493 of file measurements.cpp.
References ClearPMCode(), p998_S, TagPMSystem, and VDomDocument::UniqueTagText().
Referenced by TMainWindow::InitWindow(), and TMainWindow::SavePMSystem().
readMeasurements()
void MeasurementDoc::readMeasurements () const
Definition at line 287 of file measurements.cpp.
References VContainer::AddVariable(), AttrBase, AttrDescription, AttrFullName, AttrHeightIncrease, AttrName, AttrSizeIncrease, AttrValue, BaseHeight(), BaseSize(), data, EvalFormula(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrString(), VContainer::GetPatternUnit(), VContainer::GetTrVars(), m_currentHeight, m_currentSize, VDomDocument::measurementUnits(), Multisize, TagMeasurement, type, and UnitConvertor().
Referenced by TMainWindow::RefreshData().
ReadType()
MeasurementsType MeasurementDoc::ReadType () const private
Definition at line 918 of file measurements.cpp.
References Individual, Multisize, TagSMIS, TagSMMS, TagVIT, TagVST, and Unknown.
Referenced by setXMLContent().
Remove()
void MeasurementDoc::Remove (const QString & name)
Definition at line 212 of file measurements.cpp.
References FindM(), and TagBodyMeasurements.
Referenced by TMainWindow::Remove().
SaveDocument()
bool MeasurementDoc::SaveDocument (const QString & fileName, QString & error) virtual
Reimplemented from VDomDocument.
Definition at line 171 of file measurements.cpp.
References anonymous_namespace{measurements.cpp}::FileComment(), and VDomDocument::SaveDocument().
Referenced by TMainWindow::SaveMeasurements().
SetBirthDate()
void MeasurementDoc::SetBirthDate (const QDate & date)
Definition at line 469 of file measurements.cpp.
References isReadOnly(), VDomDocument::setTagText(), and TagBirthDate.
Referenced by TMainWindow::SaveBirthDate().
SetEmail()
void MeasurementDoc::SetEmail (const QString & text)
Definition at line 514 of file measurements.cpp.
References isReadOnly(), VDomDocument::setTagText(), and TagEmail.
Referenced by TMainWindow::SaveEmail().
SetFamilyName()
void MeasurementDoc::SetFamilyName (const QString & text)
Definition at line 439 of file measurements.cpp.
References isReadOnly(), VDomDocument::setTagText(), and TagFamilyName.
Referenced by TMainWindow::SaveFamilyName().
SetGender()
void MeasurementDoc::SetGender (const GenderType & gender)
Definition at line 484 of file measurements.cpp.
References GenderToStr(), isReadOnly(), VDomDocument::setTagText(), and TagGender.
Referenced by TMainWindow::SaveGender().
SetGivenName()
void MeasurementDoc::SetGivenName (const QString & text)
Definition at line 454 of file measurements.cpp.
References isReadOnly(), VDomDocument::setTagText(), and TagGivenName.
Referenced by TMainWindow::SaveGivenName().
setHeight()
void MeasurementDoc::setHeight (qreal * height)
Definition at line 548 of file measurements.cpp.
References m_currentHeight.
Referenced by TMainWindow::FileNew(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), and MainWindow::LoadPattern().
SetMBaseValue()
void MeasurementDoc::SetMBaseValue (const QString & name, double value)
Definition at line 582 of file measurements.cpp.
References AttrBase, FindM(), and VDomDocument::SetAttribute().
Referenced by TMainWindow::SaveMBaseValue().
SetMDescription()
void MeasurementDoc::SetMDescription (const QString & name, const QString & text)
Definition at line 624 of file measurements.cpp.
References AttrDescription, FindM(), and VDomDocument::SetAttribute().
Referenced by TMainWindow::SaveMDescription().
SetMFullName()
void MeasurementDoc::SetMFullName (const QString & name, const QString & text)
Definition at line 638 of file measurements.cpp.
References AttrFullName, FindM(), and VDomDocument::SetAttribute().
Referenced by TMainWindow::SaveMFullName().
SetMHeightIncrease()
void MeasurementDoc::SetMHeightIncrease (const QString & name, double value)
Definition at line 610 of file measurements.cpp.
References AttrHeightIncrease, FindM(), and VDomDocument::SetAttribute().
Referenced by TMainWindow::SaveMHeightIncrease().
SetMName()
void MeasurementDoc::SetMName (const QString & name, const QString & text)
Definition at line 554 of file measurements.cpp.
References AttrName, FindM(), and VDomDocument::SetAttribute().
Referenced by TMainWindow::SaveMName().
SetMSizeIncrease()
void MeasurementDoc::SetMSizeIncrease (const QString & name, double value)
Definition at line 596 of file measurements.cpp.
References AttrSizeIncrease, FindM(), and VDomDocument::SetAttribute().
Referenced by TMainWindow::SaveMSizeIncrease().
SetMValue()
void MeasurementDoc::SetMValue (const QString & name, const QString & text)
Definition at line 568 of file measurements.cpp.
References AttrValue, FindM(), and VDomDocument::SetAttribute().
Referenced by TMainWindow::Fx(), and TMainWindow::SaveMValue().
SetNotes()
void MeasurementDoc::SetNotes (const QString & text)
Definition at line 424 of file measurements.cpp.
References isReadOnly(), VDomDocument::setTagText(), and TagNotes.
Referenced by TMainWindow::SaveNotes().
SetPMSystem()
void MeasurementDoc::SetPMSystem (const QString & system)
Definition at line 499 of file measurements.cpp.
References ClearPMCode(), isReadOnly(), VDomDocument::setTagText(), and TagPMSystem.
Referenced by TMainWindow::SavePMSystem().
SetReadOnly()
void MeasurementDoc::SetReadOnly (bool ro)
Definition at line 529 of file measurements.cpp.
References falseStr, VDomDocument::setTagText(), TagReadOnly, and trueStr.
Referenced by TMainWindow::FileSaveAs().
setSize()
void MeasurementDoc::setSize (qreal * size)
Definition at line 542 of file measurements.cpp.
References m_currentSize.
Referenced by TMainWindow::FileNew(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), and MainWindow::LoadPattern().
setXMLContent()
void MeasurementDoc::setXMLContent (const QString & fileName) virtual
Reimplemented from VDomDocument.
Definition at line 164 of file measurements.cpp.
References ReadType(), VDomDocument::setXMLContent(), and type.
Referenced by TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), and MainWindow::LoadPattern().
StrToGender()
GenderType MeasurementDoc::StrToGender (const QString & sex) static
Definition at line 667 of file measurements.cpp.
References Female, GenderFemale, GenderMale, GenderUnknown, Male, and Unknown.
Referenced by Gender().
Type()
MeasurementsType MeasurementDoc::Type () const
Definition at line 386 of file measurements.cpp.
References type.
Referenced by TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), and MainWindow::LoadPattern().
UniqueTagAttr()
qreal MeasurementDoc::UniqueTagAttr (const QString & tag, const QString & attr, qreal defValue) const private
Definition at line 838 of file measurements.cpp.
References Cm, VDomDocument::GetParametrDouble(), VDomDocument::measurementUnits(), and UnitConvertor().
Referenced by BaseHeight(), and BaseSize().
Member Data Documentation
AttrBase
const QString MeasurementDoc::AttrBase = QStringLiteral("base") static
Definition at line 152 of file measurements.h.
Referenced by BaseHeight(), BaseSize(), CreateEmptyMultisizeFile(), MakeEmpty(), readMeasurements(), and SetMBaseValue().
AttrDescription
const QString MeasurementDoc::AttrDescription = QStringLiteral("description") static
Definition at line 156 of file measurements.h.
Referenced by readMeasurements(), and SetMDescription().
AttrFullName
const QString MeasurementDoc::AttrFullName = QStringLiteral("full_name") static
Definition at line 158 of file measurements.h.
Referenced by readMeasurements(), and SetMFullName().
AttrHeightIncrease
const QString MeasurementDoc::AttrHeightIncrease = QStringLiteral("height_increase") static
Definition at line 155 of file measurements.h.
Referenced by MakeEmpty(), readMeasurements(), and SetMHeightIncrease().
AttrName
const QString MeasurementDoc::AttrName = QStringLiteral("name") static
Definition at line 157 of file measurements.h.
Referenced by FindM(), ListAll(), MakeEmpty(), readMeasurements(), and SetMName().
AttrSizeIncrease
const QString MeasurementDoc::AttrSizeIncrease = QStringLiteral("size_increase") static
Definition at line 154 of file measurements.h.
Referenced by MakeEmpty(), readMeasurements(), and SetMSizeIncrease().
AttrValue
const QString MeasurementDoc::AttrValue = QStringLiteral("value") static
Definition at line 153 of file measurements.h.
Referenced by ClearForExport(), MakeEmpty(), readMeasurements(), and SetMValue().
data
VContainer* MeasurementDoc::data private
data container with data.
Definition at line 178 of file measurements.h.
Referenced by EvalFormula(), GetData(), MeasurementDoc(), and readMeasurements().
GenderFemale
const QString MeasurementDoc::GenderFemale = QStringLiteral("female") static
Definition at line 161 of file measurements.h.
Referenced by GenderToStr(), and StrToGender().
GenderMale
const QString MeasurementDoc::GenderMale = QStringLiteral("male") static
Definition at line 160 of file measurements.h.
Referenced by GenderToStr(), and StrToGender().
GenderUnknown
const QString MeasurementDoc::GenderUnknown = QStringLiteral("unknown") static
Definition at line 162 of file measurements.h.
Referenced by Gender(), GenderToStr(), and StrToGender().
m_currentHeight
qreal* MeasurementDoc::m_currentHeight private
Definition at line 182 of file measurements.h.
Referenced by readMeasurements(), and setHeight().
m_currentSize
qreal* MeasurementDoc::m_currentSize private
Definition at line 181 of file measurements.h.
Referenced by readMeasurements(), and setSize().
TagBirthDate
const QString MeasurementDoc::TagBirthDate = QStringLiteral("birth-date") static
Definition at line 145 of file measurements.h.
Referenced by BirthDate(), CreateEmptyIndividualFile(), and SetBirthDate().
TagBodyMeasurements
const QString MeasurementDoc::TagBodyMeasurements = QStringLiteral("body-measurements") static
Definition at line 138 of file measurements.h.
Referenced by addEmpty(), AddEmptyAfter(), CreateEmptyIndividualFile(), CreateEmptyMultisizeFile(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), and Remove().
TagEmail
const QString MeasurementDoc::TagEmail = QStringLiteral("email") static
Definition at line 148 of file measurements.h.
Referenced by CreateEmptyIndividualFile(), Email(), and SetEmail().
TagFamilyName
const QString MeasurementDoc::TagFamilyName = QStringLiteral("family-name") static
Definition at line 143 of file measurements.h.
Referenced by CreateEmptyIndividualFile(), FamilyName(), and SetFamilyName().
TagGender
const QString MeasurementDoc::TagGender = QStringLiteral("gender") static
Definition at line 146 of file measurements.h.
Referenced by CreateEmptyIndividualFile(), Gender(), and SetGender().
TagGivenName
const QString MeasurementDoc::TagGivenName = QStringLiteral("given-name") static
Definition at line 144 of file measurements.h.
Referenced by CreateEmptyIndividualFile(), GivenName(), and SetGivenName().
TagHeight
const QString MeasurementDoc::TagHeight = QStringLiteral("height") static
Definition at line 141 of file measurements.h.
Referenced by BaseHeight(), and CreateEmptyMultisizeFile().
TagMeasurement
const QString MeasurementDoc::TagMeasurement = QStringLiteral("m") static
Definition at line 150 of file measurements.h.
Referenced by ClearForExport(), FindM(), ListAll(), MakeEmpty(), MoveBottom(), MoveDown(), MoveTop(), MoveUp(), and readMeasurements().
TagNotes
const QString MeasurementDoc::TagNotes = QStringLiteral("notes") static
Definition at line 139 of file measurements.h.
Referenced by CreateEmptyIndividualFile(), CreateEmptyMultisizeFile(), Notes(), and SetNotes().
TagPersonal
const QString MeasurementDoc::TagPersonal = QStringLiteral("personal") static
Definition at line 142 of file measurements.h.
Referenced by CreateEmptyIndividualFile().
TagPMSystem
const QString MeasurementDoc::TagPMSystem = QStringLiteral("pm_system") static
Definition at line 147 of file measurements.h.
Referenced by CreateEmptyIndividualFile(), CreateEmptyMultisizeFile(), PMSystem(), and SetPMSystem().
TagReadOnly
const QString MeasurementDoc::TagReadOnly = QStringLiteral("read-only") static
Definition at line 149 of file measurements.h.
Referenced by CreateEmptyIndividualFile(), CreateEmptyMultisizeFile(), isReadOnly(), and SetReadOnly().
TagSize
const QString MeasurementDoc::TagSize = QStringLiteral("size") static
Definition at line 140 of file measurements.h.
Referenced by BaseSize(), and CreateEmptyMultisizeFile().
TagSMIS
const QString MeasurementDoc::TagSMIS = QStringLiteral("smis") static
Definition at line 137 of file measurements.h.
Referenced by CreateEmptyIndividualFile(), and ReadType().
TagSMMS
const QString MeasurementDoc::TagSMMS = QStringLiteral("smms") static
Definition at line 136 of file measurements.h.
Referenced by CreateEmptyMultisizeFile(), and ReadType().
TagVIT
const QString MeasurementDoc::TagVIT = QStringLiteral("vit") static
Definition at line 135 of file measurements.h.
Referenced by ReadType().
TagVST
const QString MeasurementDoc::TagVST = QStringLiteral("vst") static
Definition at line 134 of file measurements.h.
Referenced by ReadType().
type
MeasurementsType MeasurementDoc::type private
Definition at line 179 of file measurements.h.
Referenced by BaseHeight(), BaseSize(), MakeEmpty(), readMeasurements(), setXMLContent(), and Type().
The documentation for this class was generated from the following files:
src/libs/vformat/measurements.h
src/libs/vformat/measurements.cpp