Seamly2D: VExceptionConversionError Class Reference
VExceptionConversionError Class Reference
The VExceptionConversionError class for exception of conversion error.
#include <vexceptionconversionerror.h>
Public Member Functions
VExceptionConversionError (const QString &error, const QString &str)
VExceptionConversionError exception conversion error.
VExceptionConversionError (const VExceptionConversionError &e)
VExceptionConversionError copy constructor.
VExceptionConversionError & operator= (const VExceptionConversionError &e)
virtual ~VExceptionConversionError () Q_DECL_EQ_DEFAULT
virtual QString ErrorMessage () const Q_DECL_OVERRIDE
ErrorMessage return main error message.
QString String () const
String return string, where happend error.
Public Member Functions inherited from VException
VException (const QString &error)
VException constructor exception.
VException (const VException &e)
VException copy constructor.
VException & operator= (const VException &e)
virtual ~VException () Q_DECL_EQ_DEFAULT
virtual Q_NORETURN void raise () const Q_DECL_OVERRIDE
raise method raise for exception
virtual Q_REQUIRED_RESULT VException * clone () const Q_DECL_OVERRIDE
clone clone exception
virtual QString DetailedInformation () const
DetailedInformation return detailed information about error.
QString WhatUtf8 () const
What return string with error.
void AddMoreInformation (const QString &info)
AddMoreInformation add more information for error.
QString MoreInformation () const
MoreInformation return more information for error.
virtual const char * what () const Q_DECL_OVERRIDE
Protected Attributes
QString str
str string, where happend error
Protected Attributes inherited from VException
QString error
error string with error
QString moreInfo
moreInfo more information about error
Additional Inherited Members
Protected Member Functions inherited from VException
QString MoreInfo (const QString &detInfo) const
Detailed Description
The VExceptionConversionError class for exception of conversion error.
Definition at line 64 of file vexceptionconversionerror.h.
Constructor & Destructor Documentation
VExceptionConversionError() [1/2]
VExceptionConversionError::VExceptionConversionError (const QString & error, const QString & str)
VExceptionConversionError exception conversion error.
Parameters
error string with error
str string, where happend error
Definition at line 64 of file vexceptionconversionerror.cpp.
References str.
VExceptionConversionError() [2/2]
VExceptionConversionError::VExceptionConversionError (const VExceptionConversionError & e)
VExceptionConversionError copy constructor.
Parameters
e exception
Definition at line 75 of file vexceptionconversionerror.cpp.
~VExceptionConversionError()
virtual VExceptionConversionError::~VExceptionConversionError () virtual
Member Function Documentation
ErrorMessage()
QString VExceptionConversionError::ErrorMessage () const virtual
ErrorMessage return main error message.
Returns
main error message
Reimplemented from VException.
Definition at line 96 of file vexceptionconversionerror.cpp.
References VException::error, and str.
Referenced by VDomDocument::getParameterId().
operator=()
VExceptionConversionError & VExceptionConversionError::operator= (const VExceptionConversionError & e)
Definition at line 80 of file vexceptionconversionerror.cpp.
References VException::operator=(), str, and String().
String()
QString VExceptionConversionError::String () const inline
String return string, where happend error.
Returns
string
Definition at line 83 of file vexceptionconversionerror.h.
References str.
Referenced by operator=().
Member Data Documentation
str
QString VExceptionConversionError::str protected
str string, where happend error
Definition at line 75 of file vexceptionconversionerror.h.
Referenced by ErrorMessage(), operator=(), String(), and VExceptionConversionError().
The documentation for this class was generated from the following files:
src/libs/ifc/exception/vexceptionconversionerror.h
src/libs/ifc/exception/vexceptionconversionerror.cpp