Seamly2D: DialogLayoutSettings Class Reference
DialogLayoutSettings Class Reference
#include <dialoglayoutsettings.h>
Public Slots
void DialogAccepted ()
Public Member Functions
DialogLayoutSettings (VLayoutGenerator *generator, QWidget *parent=nullptr, bool disableSettings=false)
virtual ~DialogLayoutSettings ()
qreal GetPaperHeight () const
void SetPaperHeight (qreal value)
qreal GetPaperWidth () const
void SetPaperWidth (qreal value)
qreal GetShift () const
void SetShift (qreal value)
qreal GetLayoutWidth () const
void SetLayoutWidth (qreal value)
QMarginsF GetFields () const
void SetFields (const QMarginsF &value)
Cases GetGroup () const
void SetGroup (const Cases &value)
bool GetRotate () const
void SetRotate (bool state)
int GetIncrease () const
bool SetIncrease (int increase)
bool GetAutoCrop () const
void SetAutoCrop (bool autoCrop)
bool IsSaveLength () const
void SetSaveLength (bool save)
bool IsUnitePages () const
void SetUnitePages (bool save)
bool IsStripOptimization () const
void SetStripOptimization (bool save)
quint8 GetMultiplier () const
void SetMultiplier (const quint8 &value)
bool IsIgnoreAllFields () const
void SetIgnoreAllFields (bool value)
bool isTextAsPaths () const
void setTextAsPaths (bool value)
QString SelectedPrinter () const
bool SelectTemplate (const PaperSizeTemplate &id)
bool SelectPaperUnit (const QString &units)
bool SelectLayoutUnit (const QString &units)
qreal LayoutToPixels (qreal value) const
qreal PageToPixels (qreal value) const
Public Member Functions inherited from VAbstractLayoutDialog
VAbstractLayoutDialog (QWidget *parent=nullptr)
Static Public Member Functions
static QString MakeHelpTemplateList ()
static QString MakeGroupsHelp ()
Protected Member Functions
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
QSizeF getTemplateSize (const PaperSizeTemplate &tmpl, const Unit &unit) const
DialogLayoutSettings::TemplateSize.
Protected Member Functions inherited from VAbstractLayoutDialog
QSizeF getTemplateSize (const PaperSizeTemplate &tmpl, const Unit &unit) const
DialogLayoutSettings::TemplateSize.
QSizeF RoundTemplateSize (qreal width, qreal height, Unit unit) const
void initTemplates (QComboBox *comboBoxTemplates)
Private Types
typedef QStringList FormatsVector
typedef int VIndexType
Private Slots
void ConvertPaperSize ()
void ConvertLayoutSize ()
void TemplateSelected ()
void FindTemplate ()
void PaperSizeChanged ()
void Swap (bool checked)
void RestoreDefaults ()
void PrinterMargins ()
void CorrectMaxFileds ()
void IgnoreAllFields (int state)
Private Member Functions
void InitPaperUnits ()
void InitLayoutUnits ()
void InitPrinter ()
QSizeF Template ()
QMarginsF MinPrinterFields () const
QMarginsF GetDefPrinterFields () const
Unit PaperUnit () const
Unit LayoutUnit () const
void CorrectPaperDecimals ()
void CorrectLayoutDecimals ()
void MinimumPaperSize ()
void MinimumLayoutSize ()
void ReadSettings ()
void WriteSettings () const
void SheetSize (const QSizeF &size)
void SetAdditionalOptions (bool value)
Private Attributes
bool disableSettings
Ui::DialogLayoutSettings * ui
Unit oldPaperUnit
Unit oldLayoutUnit
VLayoutGenerator * generator
bool isInitialized
Static Private Attributes
static const FormatsVector pageFormatNames
Additional Inherited Members
Public Types inherited from VAbstractLayoutDialog
enum class PaperSizeTemplate : char {
A0 = 0 , A1 , A2 , A3 ,
A4 , Letter , Legal , Roll24in = 7 ,
Roll30in , Roll36in , Roll42in , Roll44in = 11 ,
Custom = 12
}
Protected Types inherited from VAbstractLayoutDialog
typedef QStringList FormatsVector
typedef int VIndexType
Static Protected Attributes inherited from VAbstractLayoutDialog
static const FormatsVector pageFormatNames
Detailed Description
Definition at line 70 of file dialoglayoutsettings.h.
Member Typedef Documentation
FormatsVector
typedef QStringList DialogLayoutSettings::FormatsVector private
Definition at line 152 of file dialoglayoutsettings.h.
VIndexType
typedef int DialogLayoutSettings::VIndexType private
Definition at line 153 of file dialoglayoutsettings.h.
Constructor & Destructor Documentation
DialogLayoutSettings()
DialogLayoutSettings::DialogLayoutSettings (VLayoutGenerator * generator, QWidget * parent = nullptr, bool disableSettings = false) explicit
Definition at line 65 of file dialoglayoutsettings.cpp.
References ConvertLayoutSize(), ConvertPaperSize(), CorrectMaxFileds(), DialogAccepted(), disableSettings, FindTemplate(), IgnoreAllFields(), InitLayoutUnits(), InitPaperUnits(), InitPrinter(), VAbstractLayoutDialog::initTemplates(), MinimumLayoutSize(), MinimumPaperSize(), Mm, PaperSizeChanged(), PrinterMargins(), qApp, ReadSettings(), RestoreDefaults(), Swap(), TemplateSelected(), and ui.
~DialogLayoutSettings()
DialogLayoutSettings::~DialogLayoutSettings () virtual
Definition at line 131 of file dialoglayoutsettings.cpp.
References ui.
Member Function Documentation
ConvertLayoutSize
void DialogLayoutSettings::ConvertLayoutSize () private slot
Definition at line 510 of file dialoglayoutsettings.cpp.
References CorrectLayoutDecimals(), FromPixel(), LayoutUnit(), MinimumLayoutSize(), oldLayoutUnit, QIMAGE_MAX, ui, and UnitConvertor().
Referenced by DialogLayoutSettings().
ConvertPaperSize
void DialogLayoutSettings::ConvertPaperSize () private slot
Definition at line 408 of file dialoglayoutsettings.cpp.
References CorrectPaperDecimals(), FromPixel(), MinimumPaperSize(), oldPaperUnit, PaperUnit(), QIMAGE_MAX, ui, and UnitConvertor().
Referenced by DialogLayoutSettings().
CorrectLayoutDecimals()
void DialogLayoutSettings::CorrectLayoutDecimals () private
Definition at line 935 of file dialoglayoutsettings.cpp.
References Cm, Inch, Mm, oldLayoutUnit, Px, and ui.
Referenced by ConvertLayoutSize().
CorrectMaxFileds
void DialogLayoutSettings::CorrectMaxFileds () private slot
Definition at line 704 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogLayoutSettings(), ReadSettings(), and RestoreDefaults().
CorrectPaperDecimals()
void DialogLayoutSettings::CorrectPaperDecimals () private
Definition at line 905 of file dialoglayoutsettings.cpp.
References Cm, Inch, Mm, oldPaperUnit, Px, and ui.
Referenced by ConvertPaperSize(), and SheetSize().
DialogAccepted
void DialogLayoutSettings::DialogAccepted () slot
Definition at line 578 of file dialoglayoutsettings.cpp.
References disableSettings, generator, GetAutoCrop(), GetFields(), GetGroup(), GetIncrease(), GetLayoutWidth(), GetMultiplier(), GetPaperHeight(), GetPaperWidth(), GetRotate(), GetShift(), IsIgnoreAllFields(), IsSaveLength(), IsStripOptimization(), isTextAsPaths(), IsUnitePages(), LayoutUnit(), MinPrinterFields(), Px, SCASSERT, VLayoutGenerator::SetAutoCrop(), VLayoutGenerator::SetCaseType(), VLayoutGenerator::SetLayoutWidth(), VLayoutGenerator::SetMultiplier(), VLayoutGenerator::SetPaperHeight(), VLayoutGenerator::SetPaperWidth(), VLayoutGenerator::SetPrinterFields(), VLayoutGenerator::SetRotate(), VLayoutGenerator::SetRotationIncrease(), VLayoutGenerator::SetSaveLength(), VLayoutGenerator::SetShift(), VLayoutGenerator::SetStripOptimization(), VLayoutGenerator::SetTestAsPaths(), VLayoutGenerator::SetUnitePages(), ui, UnitConvertor(), and WriteSettings().
Referenced by VCommandLine::DefaultGenerator(), and DialogLayoutSettings().
FindTemplate
void DialogLayoutSettings::FindTemplate () private slot
Definition at line 373 of file dialoglayoutsettings.cpp.
References VAbstractLayoutDialog::Custom, getTemplateSize(), PaperUnit(), and ui.
Referenced by DialogLayoutSettings(), and ReadSettings().
GetAutoCrop()
bool DialogLayoutSettings::GetAutoCrop () const
Definition at line 277 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
GetDefPrinterFields()
QMarginsF DialogLayoutSettings::GetDefPrinterFields () const private
Definition at line 879 of file dialoglayoutsettings.cpp.
References GetPrinterFields(), and ui.
Referenced by ReadSettings(), and RestoreDefaults().
GetFields()
QMarginsF DialogLayoutSettings::GetFields () const
Definition at line 187 of file dialoglayoutsettings.cpp.
References oldLayoutUnit, Px, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator(), DialogAccepted(), and WriteSettings().
GetGroup()
Cases DialogLayoutSettings::GetGroup () const
Definition at line 207 of file dialoglayoutsettings.cpp.
References CaseDesc, CaseThreeGroup, CaseTwoGroup, and ui.
Referenced by DialogAccepted(), and WriteSettings().
GetIncrease()
int DialogLayoutSettings::GetIncrease () const
Definition at line 255 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
GetLayoutWidth()
qreal DialogLayoutSettings::GetLayoutWidth () const
Definition at line 175 of file dialoglayoutsettings.cpp.
References oldLayoutUnit, Px, ui, and UnitConvertor().
Referenced by DialogAccepted(), and WriteSettings().
GetMultiplier()
quint8 DialogLayoutSettings::GetMultiplier () const
Definition at line 325 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
GetPaperHeight()
qreal DialogLayoutSettings::GetPaperHeight () const
Definition at line 137 of file dialoglayoutsettings.cpp.
References oldPaperUnit, Px, ui, and UnitConvertor().
Referenced by DialogAccepted(), and WriteSettings().
GetPaperWidth()
qreal DialogLayoutSettings::GetPaperWidth () const
Definition at line 150 of file dialoglayoutsettings.cpp.
References oldPaperUnit, Px, ui, and UnitConvertor().
Referenced by DialogAccepted(), and WriteSettings().
GetRotate()
bool DialogLayoutSettings::GetRotate () const
Definition at line 243 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
GetShift()
qreal DialogLayoutSettings::GetShift () const
Definition at line 163 of file dialoglayoutsettings.cpp.
References oldLayoutUnit, Px, ui, and UnitConvertor().
Referenced by DialogAccepted(), and WriteSettings().
getTemplateSize()
QSizeF DialogLayoutSettings::getTemplateSize (const PaperSizeTemplate & tmpl, const Unit & unit) const protected
DialogLayoutSettings::TemplateSize.
Parameters
tmpl
unit
Returns
Definition at line 844 of file dialoglayoutsettings.cpp.
References VAbstractLayoutDialog::Custom, VAbstractLayoutDialog::getTemplateSize(), VAbstractLayoutDialog::RoundTemplateSize(), and ui.
Referenced by FindTemplate(), and Template().
IgnoreAllFields
void DialogLayoutSettings::IgnoreAllFields (int state) private slot
Definition at line 720 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogLayoutSettings(), ReadSettings(), and RestoreDefaults().
InitLayoutUnits()
void DialogLayoutSettings::InitLayoutUnits () private
Definition at line 746 of file dialoglayoutsettings.cpp.
References Cm, Inch, Mm, oldLayoutUnit, qApp, StrToUnits(), ui, and UnitsToStr().
Referenced by DialogLayoutSettings().
InitPaperUnits()
void DialogLayoutSettings::InitPaperUnits () private
Definition at line 729 of file dialoglayoutsettings.cpp.
References Cm, Inch, Mm, oldPaperUnit, Px, qApp, StrToUnits(), ui, and UnitsToStr().
Referenced by DialogLayoutSettings().
InitPrinter()
void DialogLayoutSettings::InitPrinter () private
Definition at line 763 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogLayoutSettings(), and RestoreDefaults().
IsIgnoreAllFields()
bool DialogLayoutSettings::IsIgnoreAllFields () const
Definition at line 337 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
IsSaveLength()
bool DialogLayoutSettings::IsSaveLength () const
Definition at line 289 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
IsStripOptimization()
bool DialogLayoutSettings::IsStripOptimization () const
Definition at line 313 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
isTextAsPaths()
bool DialogLayoutSettings::isTextAsPaths () const
Definition at line 349 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
IsUnitePages()
bool DialogLayoutSettings::IsUnitePages () const
Definition at line 301 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
LayoutToPixels()
qreal DialogLayoutSettings::LayoutToPixels (qreal value) const
Definition at line 470 of file dialoglayoutsettings.cpp.
References LayoutUnit(), Px, and UnitConvertor().
Referenced by VCommandLine::Lo2Px().
LayoutUnit()
Unit DialogLayoutSettings::LayoutUnit () const private
Definition at line 899 of file dialoglayoutsettings.cpp.
References StrToUnits(), and ui.
Referenced by ConvertLayoutSize(), DialogAccepted(), LayoutToPixels(), ReadSettings(), SetFields(), SetLayoutWidth(), and SetShift().
MakeGroupsHelp()
QString DialogLayoutSettings::MakeGroupsHelp () static
Definition at line 482 of file dialoglayoutsettings.cpp.
Referenced by VCommandLine::InitOptions().
MakeHelpTemplateList()
QString DialogLayoutSettings::MakeHelpTemplateList () static
Definition at line 789 of file dialoglayoutsettings.cpp.
References VAbstractLayoutDialog::A0, VAbstractLayoutDialog::pageFormatNames, and VAbstractLayoutDialog::Roll44in.
Referenced by VCommandLine::InitOptions().
MinimumLayoutSize()
void DialogLayoutSettings::MinimumLayoutSize () private
Definition at line 963 of file dialoglayoutsettings.cpp.
References oldLayoutUnit, Px, ui, and UnitConvertor().
Referenced by ConvertLayoutSize(), and DialogLayoutSettings().
MinimumPaperSize()
void DialogLayoutSettings::MinimumPaperSize () private
Definition at line 955 of file dialoglayoutsettings.cpp.
References oldPaperUnit, Px, ui, and UnitConvertor().
Referenced by ConvertPaperSize(), and DialogLayoutSettings().
MinPrinterFields()
QMarginsF DialogLayoutSettings::MinPrinterFields () const private
Definition at line 864 of file dialoglayoutsettings.cpp.
References GetMinPrinterFields(), and ui.
Referenced by DialogAccepted().
PageToPixels()
qreal DialogLayoutSettings::PageToPixels (qreal value) const
Definition at line 476 of file dialoglayoutsettings.cpp.
References PaperUnit(), Px, and UnitConvertor().
Referenced by VCommandLine::Pg2Px().
PaperSizeChanged
void DialogLayoutSettings::PaperSizeChanged () private slot
Definition at line 531 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogLayoutSettings(), and SheetSize().
PaperUnit()
Unit DialogLayoutSettings::PaperUnit () const private
Definition at line 893 of file dialoglayoutsettings.cpp.
References StrToUnits(), and ui.
Referenced by ConvertPaperSize(), FindTemplate(), PageToPixels(), SetPaperHeight(), SetPaperWidth(), SheetSize(), and Template().
PrinterMargins
void DialogLayoutSettings::PrinterMargins () private slot
Definition at line 690 of file dialoglayoutsettings.cpp.
References GetPrinterFields(), SetFields(), and ui.
Referenced by DialogLayoutSettings().
ReadSettings()
void DialogLayoutSettings::ReadSettings () private
Definition at line 970 of file dialoglayoutsettings.cpp.
References CorrectMaxFileds(), FindTemplate(), GetDefPrinterFields(), VSettings::GetFields(), VSettings::GetIgnoreAllFields(), VSettings::GetLayoutAutoCrop(), VSettings::GetLayoutGroup(), VSettings::GetLayoutPaperHeight(), VSettings::GetLayoutPaperWidth(), VSettings::GetLayoutRotate(), VSettings::GetLayoutRotationIncrease(), VSettings::GetLayoutSaveLength(), VSettings::GetLayoutShift(), VSettings::GetLayoutUnitePages(), VSettings::GetLayoutWidth(), VSettings::GetMultiplier(), VSettings::GetStripOptimization(), VSettings::GetTextAsPaths(), IgnoreAllFields(), LayoutUnit(), Px, qApp, SetAutoCrop(), SetFields(), SetGroup(), SetIgnoreAllFields(), SetIncrease(), SetLayoutWidth(), SetMultiplier(), SetRotate(), SetSaveLength(), SetShift(), SetStripOptimization(), setTextAsPaths(), SetUnitePages(), SheetSize(), ui, and UnitConvertor().
Referenced by DialogLayoutSettings().
RestoreDefaults
void DialogLayoutSettings::RestoreDefaults () private slot
Definition at line 663 of file dialoglayoutsettings.cpp.
References CorrectMaxFileds(), VSettings::GetDefIgnoreAllFields(), VSettings::GetDefLayoutGroup(), VSettings::GetDefLayoutRotate(), VSettings::GetDefLayoutRotationIncrease(), VSettings::GetDefLayoutShift(), VSettings::GetDefLayoutWidth(), VSettings::GetDefMultiplier(), GetDefPrinterFields(), IgnoreAllFields(), InitPrinter(), SetFields(), SetGroup(), SetIgnoreAllFields(), SetIncrease(), SetLayoutWidth(), SetMultiplier(), SetRotate(), SetShift(), TemplateSelected(), and ui.
Referenced by DialogLayoutSettings().
SelectedPrinter()
QString DialogLayoutSettings::SelectedPrinter () const
Definition at line 361 of file dialoglayoutsettings.cpp.
References ui.
Referenced by MainWindowsNoGUI::toolLayoutSettings().
SelectLayoutUnit()
bool DialogLayoutSettings::SelectLayoutUnit (const QString & units)
Definition at line 459 of file dialoglayoutsettings.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator().
SelectPaperUnit()
bool DialogLayoutSettings::SelectPaperUnit (const QString & units)
Definition at line 448 of file dialoglayoutsettings.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator().
SelectTemplate()
bool DialogLayoutSettings::SelectTemplate (const PaperSizeTemplate & id)
Definition at line 548 of file dialoglayoutsettings.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator().
SetAdditionalOptions()
void DialogLayoutSettings::SetAdditionalOptions (bool value) private
Definition at line 1033 of file dialoglayoutsettings.cpp.
References SetAutoCrop(), SetSaveLength(), SetStripOptimization(), and SetUnitePages().
Referenced by Template().
SetAutoCrop()
void DialogLayoutSettings::SetAutoCrop (bool autoCrop)
Definition at line 283 of file dialoglayoutsettings.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and SetAdditionalOptions().
SetFields()
void DialogLayoutSettings::SetFields (const QMarginsF & value)
Definition at line 198 of file dialoglayoutsettings.cpp.
References LayoutUnit(), Px, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator(), PrinterMargins(), ReadSettings(), and RestoreDefaults().
SetGroup()
void DialogLayoutSettings::SetGroup (const Cases & value)
Definition at line 225 of file dialoglayoutsettings.cpp.
References CaseDesc, CaseThreeGroup, CaseTwoGroup, and ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetIgnoreAllFields()
void DialogLayoutSettings::SetIgnoreAllFields (bool value)
Definition at line 343 of file dialoglayoutsettings.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetIncrease()
bool DialogLayoutSettings::SetIncrease (int increase)
Definition at line 262 of file dialoglayoutsettings.cpp.
References VSettings::GetDefLayoutRotationIncrease(), and ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetLayoutWidth()
void DialogLayoutSettings::SetLayoutWidth (qreal value)
Definition at line 181 of file dialoglayoutsettings.cpp.
References LayoutUnit(), Px, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetMultiplier()
void DialogLayoutSettings::SetMultiplier (const quint8 & value)
Definition at line 331 of file dialoglayoutsettings.cpp.
References ui.
Referenced by ReadSettings(), and RestoreDefaults().
SetPaperHeight()
void DialogLayoutSettings::SetPaperHeight (qreal value)
Definition at line 143 of file dialoglayoutsettings.cpp.
References FromPixel(), PaperUnit(), Px, QIMAGE_MAX, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator().
SetPaperWidth()
void DialogLayoutSettings::SetPaperWidth (qreal value)
Definition at line 156 of file dialoglayoutsettings.cpp.
References FromPixel(), PaperUnit(), Px, QIMAGE_MAX, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator().
SetRotate()
void DialogLayoutSettings::SetRotate (bool state)
Definition at line 249 of file dialoglayoutsettings.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetSaveLength()
void DialogLayoutSettings::SetSaveLength (bool save)
Definition at line 295 of file dialoglayoutsettings.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and SetAdditionalOptions().
SetShift()
void DialogLayoutSettings::SetShift (qreal value)
Definition at line 169 of file dialoglayoutsettings.cpp.
References LayoutUnit(), Px, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetStripOptimization()
void DialogLayoutSettings::SetStripOptimization (bool save)
Definition at line 319 of file dialoglayoutsettings.cpp.
References ui.
Referenced by ReadSettings(), and SetAdditionalOptions().
setTextAsPaths()
void DialogLayoutSettings::setTextAsPaths (bool value)
Definition at line 355 of file dialoglayoutsettings.cpp.
References ui.
Referenced by ReadSettings().
SetUnitePages()
void DialogLayoutSettings::SetUnitePages (bool save)
Definition at line 307 of file dialoglayoutsettings.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and SetAdditionalOptions().
SheetSize()
void DialogLayoutSettings::SheetSize (const QSizeF & size) private
Definition at line 1019 of file dialoglayoutsettings.cpp.
References CorrectPaperDecimals(), FromPixel(), oldPaperUnit, PaperSizeChanged(), PaperUnit(), QIMAGE_MAX, and ui.
Referenced by ReadSettings(), and TemplateSelected().
showEvent()
void DialogLayoutSettings::showEvent (QShowEvent * event) protected virtual
Definition at line 489 of file dialoglayoutsettings.cpp.
References isInitialized.
Swap
void DialogLayoutSettings::Swap (bool checked) private slot
Definition at line 560 of file dialoglayoutsettings.cpp.
References ui.
Referenced by DialogLayoutSettings().
Template()
QSizeF DialogLayoutSettings::Template () private
Definition at line 805 of file dialoglayoutsettings.cpp.
References VAbstractLayoutDialog::A0, VAbstractLayoutDialog::A1, VAbstractLayoutDialog::A2, VAbstractLayoutDialog::A3, VAbstractLayoutDialog::A4, VAbstractLayoutDialog::Custom, getTemplateSize(), VAbstractLayoutDialog::Legal, VAbstractLayoutDialog::Letter, PaperUnit(), VAbstractLayoutDialog::Roll24in, VAbstractLayoutDialog::Roll30in, VAbstractLayoutDialog::Roll36in, VAbstractLayoutDialog::Roll42in, VAbstractLayoutDialog::Roll44in, SetAdditionalOptions(), and ui.
Referenced by TemplateSelected().
TemplateSelected
void DialogLayoutSettings::TemplateSelected () private slot
Definition at line 367 of file dialoglayoutsettings.cpp.
References SheetSize(), and Template().
Referenced by DialogLayoutSettings(), and RestoreDefaults().
WriteSettings()
void DialogLayoutSettings::WriteSettings () const private
Definition at line 998 of file dialoglayoutsettings.cpp.
References GetAutoCrop(), GetFields(), GetGroup(), GetIncrease(), GetLayoutWidth(), GetMultiplier(), GetPaperHeight(), GetPaperWidth(), GetRotate(), GetShift(), IsIgnoreAllFields(), IsSaveLength(), IsStripOptimization(), isTextAsPaths(), IsUnitePages(), qApp, VSettings::SetFields(), VSettings::SetIgnoreAllFields(), VSettings::SetLayoutAutoCrop(), VSettings::SetLayoutGroup(), VSettings::SetLayoutPaperHeight(), VSettings::SetLayoutPaperWidth(), VSettings::SetLayoutRotate(), VSettings::SetLayoutRotationIncrease(), VSettings::SetLayoutSaveLength(), VSettings::SetLayoutShift(), VSettings::SetLayoutUnitePages(), VSettings::SetLayoutWidth(), VSettings::SetMultiplier(), VSettings::SetStripOptimization(), and VSettings::setTextAsPaths().
Referenced by DialogAccepted().
Member Data Documentation
disableSettings
bool DialogLayoutSettings::disableSettings private
Definition at line 156 of file dialoglayoutsettings.h.
Referenced by DialogAccepted(), and DialogLayoutSettings().
generator
VLayoutGenerator* DialogLayoutSettings::generator private
Definition at line 161 of file dialoglayoutsettings.h.
Referenced by DialogAccepted().
isInitialized
bool DialogLayoutSettings::isInitialized private
Definition at line 162 of file dialoglayoutsettings.h.
Referenced by showEvent().
oldLayoutUnit
Unit DialogLayoutSettings::oldLayoutUnit private
Definition at line 160 of file dialoglayoutsettings.h.
Referenced by ConvertLayoutSize(), CorrectLayoutDecimals(), GetFields(), GetLayoutWidth(), GetShift(), InitLayoutUnits(), and MinimumLayoutSize().
oldPaperUnit
Unit DialogLayoutSettings::oldPaperUnit private
Definition at line 159 of file dialoglayoutsettings.h.
Referenced by ConvertPaperSize(), CorrectPaperDecimals(), GetPaperHeight(), GetPaperWidth(), InitPaperUnits(), MinimumPaperSize(), and SheetSize().
pageFormatNames
const FormatsVector DialogLayoutSettings::pageFormatNames static private
Definition at line 154 of file dialoglayoutsettings.h.
ui
Ui::DialogLayoutSettings* DialogLayoutSettings::ui private
Definition at line 158 of file dialoglayoutsettings.h.
Referenced by ConvertLayoutSize(), ConvertPaperSize(), CorrectLayoutDecimals(), CorrectMaxFileds(), CorrectPaperDecimals(), DialogAccepted(), DialogLayoutSettings(), FindTemplate(), GetAutoCrop(), GetDefPrinterFields(), GetFields(), GetGroup(), GetIncrease(), GetLayoutWidth(), GetMultiplier(), GetPaperHeight(), GetPaperWidth(), GetRotate(), GetShift(), getTemplateSize(), IgnoreAllFields(), InitLayoutUnits(), InitPaperUnits(), InitPrinter(), IsIgnoreAllFields(), IsSaveLength(), IsStripOptimization(), isTextAsPaths(), IsUnitePages(), LayoutUnit(), MinimumLayoutSize(), MinimumPaperSize(), MinPrinterFields(), PaperSizeChanged(), PaperUnit(), PrinterMargins(), ReadSettings(), RestoreDefaults(), SelectedPrinter(), SelectLayoutUnit(), SelectPaperUnit(), SelectTemplate(), SetAutoCrop(), SetFields(), SetGroup(), SetIgnoreAllFields(), SetIncrease(), SetLayoutWidth(), SetMultiplier(), SetPaperHeight(), SetPaperWidth(), SetRotate(), SetSaveLength(), SetShift(), SetStripOptimization(), setTextAsPaths(), SetUnitePages(), SheetSize(), Swap(), Template(), and ~DialogLayoutSettings().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/dialoglayoutsettings.h
src/app/seamly2d/dialogs/dialoglayoutsettings.cpp