Seamly2D: VisToolMirrorByAxis Class Reference
VisToolMirrorByAxis Class Reference
#include <vistoolmirrorbyaxis.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolMirrorByAxis) }
Public Types inherited from VisOperation
enum { Type = UserType + static_cast<int>(Vis::ToolRotation) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolMirrorByAxis (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolMirrorByAxis ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setOriginPointId (quint32 value)
void setAxisType (AxisType value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisOperation
VisOperation (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisOperation ()
void setObjects (QVector< quint32 > objects)
virtual void VisualMode (const quint32 &pointId=NULL_ID) Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Attributes
AxisType m_axisType
VScaledEllipse * point1
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisOperation
VScaledEllipse * GetPoint (quint32 i, const QColor &color)
VCurvePathItem * GetCurve (quint32 i, const QColor &color)
template<class Item >
int addFlippedCurve (const QPointF &firstPoint, const QPointF &secondPoint, quint32 id, int i)
void refreshMirroredObjects (const QPointF &firstPoint, const QPointF &secondPoint)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from VisOperation
QVector< quint32 > objects
QColor supportColor2
QColor supportColor3
QVector< VScaledEllipse * > points
QVector< VCurvePathItem * > curves
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 60 of file vistoolmirrorbyaxis.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 73 of file vistoolmirrorbyaxis.h.
Constructor & Destructor Documentation
VisToolMirrorByAxis()
VisToolMirrorByAxis::VisToolMirrorByAxis (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 56 of file vistoolmirrorbyaxis.cpp.
References Visualization::InitPoint(), point1, VisOperation::supportColor2, and VerticalAxis.
~VisToolMirrorByAxis()
virtual VisToolMirrorByAxis::~VisToolMirrorByAxis () virtual default
Member Function Documentation
RefreshGeometry()
void VisToolMirrorByAxis::RefreshGeometry () virtual
Implements Visualization.
Definition at line 65 of file vistoolmirrorbyaxis.cpp.
References VisLine::Axis(), Visualization::data, Visualization::DrawLine(), Visualization::DrawPoint(), VContainer::GeometricObject(), Visualization::lineWeight, m_axisType, NULL_ID, Visualization::object1Id, VisOperation::objects, point1, VisOperation::refreshMirroredObjects(), VisOperation::supportColor2, and VerticalAxis.
Referenced by DialogMirrorByAxis::ChosenObject(), DialogMirrorByAxis::SaveData(), and VToolMirrorByAxis::SetVisualization().
setAxisType()
void VisToolMirrorByAxis::setAxisType (AxisType value)
Definition at line 102 of file vistoolmirrorbyaxis.cpp.
References m_axisType.
Referenced by DialogMirrorByAxis::SaveData(), and VToolMirrorByAxis::SetVisualization().
setOriginPointId()
void VisToolMirrorByAxis::setOriginPointId (quint32 value)
Definition at line 96 of file vistoolmirrorbyaxis.cpp.
References Visualization::object1Id.
Referenced by DialogMirrorByAxis::ChosenObject(), DialogMirrorByAxis::SaveData(), DialogMirrorByAxis::setOriginPointId(), and VToolMirrorByAxis::SetVisualization().
type()
virtual int VisToolMirrorByAxis::type () const inline virtual
Reimplemented from VisOperation.
Definition at line 72 of file vistoolmirrorbyaxis.h.
References Type.
Member Data Documentation
m_axisType
AxisType VisToolMirrorByAxis::m_axisType private
Definition at line 77 of file vistoolmirrorbyaxis.h.
Referenced by RefreshGeometry(), and setAxisType().
point1
VScaledEllipse* VisToolMirrorByAxis::point1 private
Definition at line 79 of file vistoolmirrorbyaxis.h.
Referenced by RefreshGeometry(), and VisToolMirrorByAxis().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/operation/vistoolmirrorbyaxis.h
src/libs/vtools/visualization/line/operation/vistoolmirrorbyaxis.cpp