Seamly2D: VCurvePathItem Class Reference
VCurvePathItem Class Reference
#include <vcurvepathitem.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::CurvePathItem) }
Public Member Functions
VCurvePathItem (QGraphicsItem *parent=nullptr)
virtual ~VCurvePathItem ()=default
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
virtual int type () const Q_DECL_OVERRIDE
void SetDirectionArrows (const QVector< QPair< QLineF, QLineF >> &arrows)
void SetPoints (const QVector< QPointF > &points)
Protected Member Functions
virtual void ScalePenWidth ()
Private Attributes
QVector< QPair< QLineF, QLineF > > m_directionArrows
QVector< QPointF > m_points
Detailed Description
Definition at line 60 of file vcurvepathitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 72 of file vcurvepathitem.h.
Constructor & Destructor Documentation
VCurvePathItem()
VCurvePathItem::VCurvePathItem (QGraphicsItem * parent = nullptr) explicit
Definition at line 59 of file vcurvepathitem.cpp.
~VCurvePathItem()
virtual VCurvePathItem::~VCurvePathItem () virtual default
Member Function Documentation
paint()
void VCurvePathItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
Definition at line 96 of file vcurvepathitem.cpp.
References VAbstractCurve::lengthCurveDirectionArrow, m_directionArrows, ScalePenWidth(), scaleWidth(), sceneScale(), and VAbstractCurve::ShowDirection().
ScalePenWidth()
void VCurvePathItem::ScalePenWidth () protected virtual
Reimplemented in VSimpleCurve.
Definition at line 134 of file vcurvepathitem.cpp.
References scaleWidth(), sceneScale(), and widthMainLine.
Referenced by paint().
SetDirectionArrows()
void VCurvePathItem::SetDirectionArrows (const QVector< QPair< QLineF, QLineF >> & arrows)
Definition at line 122 of file vcurvepathitem.cpp.
References m_directionArrows.
Referenced by Visualization::DrawPath(), VSimpleCurve::hoverEnterEvent(), VSimpleCurve::hoverLeaveEvent(), and VSimpleCurve::RefreshGeometry().
SetPoints()
void VCurvePathItem::SetPoints (const QVector< QPointF > & points)
Definition at line 128 of file vcurvepathitem.cpp.
References m_points.
Referenced by VSimpleCurve::RefreshGeometry().
shape()
QPainterPath VCurvePathItem::shape () const virtual
Definition at line 67 of file vcurvepathitem.cpp.
References ItemShapeFromPath(), VAbstractCurve::lengthCurveDirectionArrow, m_directionArrows, m_points, scaleWidth(), sceneScale(), and VAbstractCurve::ShowDirection().
type()
virtual int VCurvePathItem::type () const inline virtual
Reimplemented in VSimpleCurve, VisToolSplinePath, VisToolSpline, VisToolPointOfIntersectionCurves, VisToolInternalPath, VisToolEllipticalArc, VisToolCutSplinePath, VisToolCutSpline, VisToolCutArc, VisToolCubicBezierPath, VisToolCubicBezier, VisToolArcWithLength, VisToolArc, VisPath, PieceAnchorPointVisual, and PatternPieceVisual.
Definition at line 71 of file vcurvepathitem.h.
References Type.
Member Data Documentation
m_directionArrows
QVector<QPair<QLineF, QLineF> > VCurvePathItem::m_directionArrows private
Definition at line 81 of file vcurvepathitem.h.
Referenced by paint(), SetDirectionArrows(), and shape().
m_points
QVector<QPointF> VCurvePathItem::m_points private
Definition at line 82 of file vcurvepathitem.h.
Referenced by SetPoints(), and shape().
The documentation for this class was generated from the following files:
src/libs/vwidgets/vcurvepathitem.h
src/libs/vwidgets/vcurvepathitem.cpp