Seamly2D: VToolCurveIntersectAxis Class Reference
VToolCurveIntersectAxis Class Reference
#include <vtoolcurveintersectaxis.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::CurveIntersectAxis) }
Public Types inherited from VToolLinePoint
enum { Type = UserType + static_cast<int>(Tool::LinePoint) }
Public Types inherited from VToolSinglePoint
enum { Type = UserType + static_cast<int>(Tool::SinglePoint) }
Public Types inherited from VScenePoint
enum { Type = UserType + static_cast<int>(Vis::ScenePoint) }
Public Member Functions
virtual ~VToolCurveIntersectAxis () Q_DECL_EQ_DEFAULT
virtual void setDialog () Q_DECL_OVERRIDE
setDialog set dialog when user want change tool option.
virtual int type () const Q_DECL_OVERRIDE
VFormula GetFormulaAngle () const
void SetFormulaAngle (const VFormula &value)
QString CurveName () const
quint32 getCurveId () const
void setCurveId (const quint32 &value)
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
Public Member Functions inherited from VToolLinePoint
VToolLinePoint (VAbstractPattern *doc, VContainer *data, const quint32 &id, const QString &lineType, const QString &lineWeight, const QString &lineColor, const QString &formula, const quint32 &basePointId, const qreal &angle, QGraphicsItem *parent=nullptr)
VToolLinePoint constructor.
virtual ~VToolLinePoint () Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
VFormula GetFormulaLength () const
void SetFormulaLength (const VFormula &value)
QString BasePointName () const
quint32 GetBasePointId () const
void SetBasePointId (const quint32 &value)
qreal GetAngle () const
void SetAngle (const qreal &value)
QString getLineColor () const
void setLineColor (const QString &value)
Public Member Functions inherited from VToolSinglePoint
VToolSinglePoint (VAbstractPattern *doc, VContainer *data, quint32 id, const QColor &lineColor, QGraphicsItem *parent=nullptr)
VToolSinglePoint constructor.
virtual ~VToolSinglePoint () Q_DECL_EQ_DEFAULT
QString name () const
void setName (const QString &name)
void SetEnabled (bool enabled)
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
virtual bool isPointNameVisible (quint32 id) const Q_DECL_OVERRIDE
virtual void setPointNameVisiblity (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void setPointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractPoint
VAbstractPoint (VAbstractPattern *doc, VContainer *data, quint32 id)
virtual ~VAbstractPoint () Q_DECL_EQ_DEFAULT
virtual QString getTagName () const Q_DECL_OVERRIDE
template<typename T >
void ShowToolVisualization (bool show)
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual void setLineWeight (const QString &value)
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Public Member Functions inherited from VScenePoint
VScenePoint (const QColor &lineColor, QGraphicsItem *parent=nullptr)
virtual ~VScenePoint ()=default
virtual void refreshPointGeometry (const VPointF &point)
void refreshLeader ()
Static Public Member Functions
static VToolCurveIntersectAxis * Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static VToolCurveIntersectAxis * Create (const quint32 _id, const QString &pointName, const QString &lineType, const QString &lineWeight, const QString &lineColor, QString &formulaAngle, quint32 basePointId, quint32 curveId, qreal mx, qreal my, bool showPointName, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation)
static bool FindPoint (const QPointF &point, qreal angle, const QSharedPointer< VAbstractCurve > &curve, QPointF *intersectPoint)
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString ToolType = QStringLiteral("curveIntersectAxis")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Slots
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID) Q_DECL_OVERRIDE
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Protected Member Functions
virtual void SaveDialog (QDomElement &domElement) Q_DECL_OVERRIDE
SaveDialog save options into file after change in dialog.
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
virtual void ReadToolAttributes (const QDomElement &domElement) Q_DECL_OVERRIDE
virtual void SetVisualization () Q_DECL_OVERRIDE
Protected Member Functions inherited from VToolLinePoint
virtual void RefreshGeometry ()
lineColor color of a line.
virtual void RemoveReferens () Q_DECL_OVERRIDE
RemoveReferens decrement value of reference.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual QString makeToolTip () const Q_DECL_OVERRIDE
Protected Member Functions inherited from VToolSinglePoint
virtual void updatePointNameVisibility (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void updatePointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
updatePointNamePosition save new position text to the pattern file.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
mouseReleaseEvent handle mouse release events.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) Q_DECL_OVERRIDE
itemChange hadle item change.
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyReleaseEvent handle key release events.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractPoint
void SetPointName (quint32 id, const QString &name)
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialogChange () Q_DECL_FINAL
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
void SaveOption (QSharedPointer< VGObject > &obj)
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
virtual void ToolCreation (const Source &typeCreation)
Protected Member Functions inherited from VScenePoint
void setOnlyPoint (bool value)
bool isOnlyPoint () const
void setPointColor (const QString &value)
Private Member Functions
VToolCurveIntersectAxis (VAbstractPattern *doc, VContainer *data, const quint32 &id, const QString &lineType, const QString &lineWeight, const QString &lineColor, const QString &formulaAngle, const quint32 &basePointId, const quint32 &curveId, const Source &typeCreation, QGraphicsItem *parent=nullptr)
Static Private Member Functions
template<class Item >
static void InitArc (VContainer *data, qreal segLength, const VPointF *p, quint32 curveId)
static void InitSegments (const GOType &curveType, qreal segLength, const VPointF *p, quint32 curveId, VContainer *data)
Private Attributes
QString formulaAngle
quint32 curveId
Additional Inherited Members
Public Slots inherited from VToolLinePoint
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
Public Slots inherited from VToolSinglePoint
void pointnameChangedPosition (const QPointF &pos)
pointnameChangedPosition handle change position point text.
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
void pointChosen ()
void pointSelected (bool selected)
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
void allowTextHover (bool enabled)
void allowTextSelectable (bool enabled)
virtual void ToolSelectionType (const SelectionType &type) Q_DECL_OVERRIDE
Public Slots inherited from VAbstractPoint
virtual void ShowTool (quint32 id, bool enable) Q_DECL_OVERRIDE
ShowTool highlight tool.
void deletePoint ()
Public Slots inherited from VDrawTool
virtual void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Static Protected Member Functions inherited from VAbstractPoint
template<typename T >
static void InitToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VToolLinePoint
QString formulaLength
qreal angle
formula string with length formula.
quint32 basePointId
angle line angle.
VScaledLine * mainLine
basePointId id base line point.
QString lineColor
mainLine line item.
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Protected Attributes inherited from VScenePoint
VGraphicsSimpleTextItem * m_pointName
VScaledLine * m_pointLeader
namePoint point text.
QColor m_pointColor
pointL line that we see if Text is moved too away from point.
bool m_onlyPoint
m_pointColor color of point.
bool m_isHovered
bool m_showPointName
Detailed Description
Definition at line 72 of file vtoolcurveintersectaxis.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 94 of file vtoolcurveintersectaxis.h.
Constructor & Destructor Documentation
~VToolCurveIntersectAxis()
virtual VToolCurveIntersectAxis::~VToolCurveIntersectAxis () virtual
VToolCurveIntersectAxis()
VToolCurveIntersectAxis::VToolCurveIntersectAxis (VAbstractPattern * doc, VContainer * data, const quint32 & id, const QString & lineType, const QString & lineWeight, const QString & lineColor, const QString & formulaAngle, const quint32 & basePointId, const quint32 & curveId, const Source & typeCreation, QGraphicsItem * parent = nullptr) private
Definition at line 97 of file vtoolcurveintersectaxis.cpp.
References VAbstractTool::ToolCreation().
Referenced by Create().
Member Function Documentation
Create() [1/2]
VToolCurveIntersectAxis * VToolCurveIntersectAxis::Create (const quint32 _id, const QString & pointName, const QString & lineType, const QString & lineWeight, const QString & lineColor, QString & formulaAngle, quint32 basePointId, quint32 curveId, qreal mx, qreal my, bool showPointName, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation) static
Definition at line 153 of file vtoolcurveintersectaxis.cpp.
References VContainer::AddGObject(), VContainer::AddLine(), VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), VToolLinePoint::angle, VToolLinePoint::basePointId, VAbstractTool::CheckFormula(), curveId, CurveIntersectAxis, VDataTool::data, VAbstractTool::doc, FindPoint(), formulaAngle, FromGui, FullParse, VContainer::GeometricObject(), VContainer::getNextId(), VAbstractPattern::IncrementReferens(), InitSegments(), VAbstractPoint::InitToolConnections(), VToolLinePoint::lineColor, qApp, VPointF::setShowPointName(), VContainer::UpdateGObject(), VAbstractPattern::UpdateToolData(), and VToolCurveIntersectAxis().
Create() [2/2]
VToolCurveIntersectAxis * VToolCurveIntersectAxis::Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data) static
Definition at line 128 of file vtoolcurveintersectaxis.cpp.
References VToolLinePoint::basePointId, curveId, VDataTool::data, VAbstractTool::doc, formulaAngle, FromGui, FullParse, VToolLinePoint::lineColor, VInteractiveTool::m_dialog, and SCASSERT.
Referenced by VPattern::ParseToolCurveIntersectAxis().
CurveName()
QString VToolCurveIntersectAxis::CurveName () const
Definition at line 296 of file vtoolcurveintersectaxis.cpp.
References curveId, VDataTool::data, and VContainer::GetGObject().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolCurveIntersectAxis(), and VToolOptionsPropertyBrowser::updateOptionsToolCurveIntersectAxis().
FindPoint()
bool VToolCurveIntersectAxis::FindPoint (const QPointF & point, qreal angle, const QSharedPointer< VAbstractCurve > & curve, QPointF * intersectPoint) static
Definition at line 231 of file vtoolcurveintersectaxis.cpp.
References VToolLinePoint::angle, and VGObject::BuildRay().
Referenced by Create(), and VisToolCurveIntersectAxis::RefreshGeometry().
getCurveId()
quint32 VToolCurveIntersectAxis::getCurveId () const
Definition at line 302 of file vtoolcurveintersectaxis.cpp.
References curveId.
GetFormulaAngle()
VFormula VToolCurveIntersectAxis::GetFormulaAngle () const
Definition at line 274 of file vtoolcurveintersectaxis.cpp.
References degreeSymbol, formulaAngle, VAbstractTool::getData(), VAbstractTool::m_id, VFormula::setCheckZero(), VFormula::setPostfix(), and VFormula::setToolId().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolCurveIntersectAxis(), and VToolOptionsPropertyBrowser::updateOptionsToolCurveIntersectAxis().
InitArc()
template<class Item > void VToolCurveIntersectAxis::InitArc (VContainer * data, qreal segLength, const VPointF * p, quint32 curveId) static private
Definition at line 395 of file vtoolcurveintersectaxis.cpp.
References VContainer::AddArc(), curveId, VDataTool::data, VContainer::GeometricObject(), VGObject::id(), Item, and VFuzzyComparePossibleNulls().
InitSegments()
QT_WARNING_PUSH void VToolCurveIntersectAxis::InitSegments (const GOType & curveType, qreal segLength, const VPointF * p, quint32 curveId, VContainer * data) static private
Definition at line 439 of file vtoolcurveintersectaxis.cpp.
References AllCurves, Arc, CubicBezier, CubicBezierPath, Curve, VAbstractCubicBezier::CutSpline(), VToolCutSplinePath::CutSplinePath(), EllipticalArc, VGObject::name(), NULL_ID, Path, Point, SCASSERT, Spline, SplinePath, splPath, Unknown, and VFuzzyComparePossibleNulls().
Referenced by Create().
ReadToolAttributes()
void VToolCurveIntersectAxis::ReadToolAttributes (const QDomElement & domElement) protected virtual
Implements VDrawTool.
Definition at line 366 of file vtoolcurveintersectaxis.cpp.
References AttrAngle, AttrBasePoint, AttrCurve, AttrLineColor, AttrLineType, AttrLineWeight, VToolLinePoint::basePointId, ColorBlack, curveId, VAbstractTool::doc, formulaAngle, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VToolLinePoint::lineColor, LineTypeSolidLine, VDrawTool::m_lineType, VDrawTool::m_lineWeight, and NULL_ID_STR.
SaveDialog()
void VToolCurveIntersectAxis::SaveDialog (QDomElement & domElement) protected virtual
SaveDialog save options into file after change in dialog.
Implements VDrawTool.
Definition at line 340 of file vtoolcurveintersectaxis.cpp.
References AttrAngle, AttrBasePoint, AttrCurve, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, VAbstractTool::doc, VInteractiveTool::m_dialog, SCASSERT, and VDomDocument::SetAttribute().
SaveOptions()
void VToolCurveIntersectAxis::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VToolLinePoint.
Definition at line 355 of file vtoolcurveintersectaxis.cpp.
References AttrAngle, AttrBasePoint, AttrCurve, AttrType, VToolLinePoint::basePointId, curveId, VAbstractTool::doc, formulaAngle, VToolLinePoint::SaveOptions(), VDomDocument::SetAttribute(), and ToolType.
setCurveId()
void VToolCurveIntersectAxis::setCurveId (const quint32 & value)
Definition at line 308 of file vtoolcurveintersectaxis.cpp.
References curveId, VDataTool::data, VContainer::GetGObject(), VAbstractTool::m_id, NULL_ID, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolCurveIntersectAxis().
setDialog()
void VToolCurveIntersectAxis::setDialog () virtual
setDialog set dialog when user want change tool option.
Reimplemented from VInteractiveTool.
Definition at line 111 of file vtoolcurveintersectaxis.cpp.
References VToolLinePoint::basePointId, curveId, VDataTool::data, formulaAngle, VContainer::GeometricObject(), VToolLinePoint::lineColor, VInteractiveTool::m_dialog, VAbstractTool::m_id, VDrawTool::m_lineType, VDrawTool::m_lineWeight, and SCASSERT.
SetFormulaAngle()
void VToolCurveIntersectAxis::SetFormulaAngle (const VFormula & value)
Definition at line 284 of file vtoolcurveintersectaxis.cpp.
References VDataTool::data, VFormula::error(), formulaAngle, FromUser, VFormula::GetFormula(), VContainer::GetGObject(), VAbstractTool::m_id, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolCurveIntersectAxis().
SetVisualization()
void VToolCurveIntersectAxis::SetVisualization () protected virtual
Implements VAbstractTool.
Definition at line 377 of file vtoolcurveintersectaxis.cpp.
References VToolLinePoint::basePointId, curveId, formulaAngle, lineTypeToPenStyle(), VDrawTool::m_lineType, VDrawTool::m_lineWeight, qApp, VisToolCurveIntersectAxis::RefreshGeometry(), SCASSERT, VisToolCurveIntersectAxis::SetAngle(), VisToolCurveIntersectAxis::setAxisPointId(), Visualization::setLineStyle(), Visualization::setLineWeight(), Visualization::setObject1Id(), and VAbstractTool::vis.
showContextMenu
void VToolCurveIntersectAxis::showContextMenu (QGraphicsSceneContextMenuEvent * event, quint32 id = NULL_ID) protected virtual slot
Definition at line 326 of file vtoolcurveintersectaxis.cpp.
ShowVisualization()
void VToolCurveIntersectAxis::ShowVisualization (bool show) virtual
Implements VAbstractTool.
Definition at line 320 of file vtoolcurveintersectaxis.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolCurveIntersectAxis().
type()
virtual int VToolCurveIntersectAxis::type () const inline virtual
Reimplemented from VToolLinePoint.
Definition at line 93 of file vtoolcurveintersectaxis.h.
References Type.
Member Data Documentation
curveId
quint32 VToolCurveIntersectAxis::curveId private
Definition at line 118 of file vtoolcurveintersectaxis.h.
Referenced by Create(), CurveName(), getCurveId(), InitArc(), ReadToolAttributes(), SaveOptions(), setCurveId(), setDialog(), and SetVisualization().
formulaAngle
QString VToolCurveIntersectAxis::formulaAngle private
Definition at line 117 of file vtoolcurveintersectaxis.h.
Referenced by Create(), GetFormulaAngle(), ReadToolAttributes(), SaveOptions(), setDialog(), SetFormulaAngle(), and SetVisualization().
ToolType
const QString VToolCurveIntersectAxis::ToolType = QStringLiteral("curveIntersectAxis") static
Definition at line 92 of file vtoolcurveintersectaxis.h.
Referenced by VPattern::ParsePointElement(), and SaveOptions().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolcurveintersectaxis.h
src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolcurveintersectaxis.cpp