Seamly2D: qmu::QmuTranslation Class Reference
qmu::QmuTranslation Class Reference
#include <qmutranslation.h>
Public Member Functions
QmuTranslation ()
~QmuTranslation ()
QmuTranslation (const QString &context, const QString &sourceText, const QString &disambiguation=nullptr, int n=-1)
QmuTranslation & operator= (const QmuTranslation &tr)
QmuTranslation (const QmuTranslation &tr)
QString translate () const
QString getMcontext () const
QString getMsourceText () const
QString getMdisambiguation () const
int getN () const
Static Public Member Functions
static QmuTranslation translate (const QString &context, const QString &sourceText, const QString &disambiguation=nullptr, int n=-1)
Private Attributes
QString mcontext
QString msourceText
QString mdisambiguation
int mn
Detailed Description
Definition at line 51 of file qmutranslation.h.
Constructor & Destructor Documentation
QmuTranslation() [1/3]
qmu::QmuTranslation::QmuTranslation ()
Definition at line 43 of file qmutranslation.cpp.
~QmuTranslation()
qmu::QmuTranslation::~QmuTranslation () inline
Definition at line 55 of file qmutranslation.h.
QmuTranslation() [2/3]
qmu::QmuTranslation::QmuTranslation (const QString & context, const QString & sourceText, const QString & disambiguation = nullptr, int n = -1)
Definition at line 48 of file qmutranslation.cpp.
QmuTranslation() [3/3]
qmu::QmuTranslation::QmuTranslation (const QmuTranslation & tr)
Definition at line 67 of file qmutranslation.cpp.
Member Function Documentation
getMcontext()
QString qmu::QmuTranslation::getMcontext () const inline
Definition at line 75 of file qmutranslation.h.
References mcontext.
Referenced by operator=().
getMdisambiguation()
QString qmu::QmuTranslation::getMdisambiguation () const inline
Definition at line 87 of file qmutranslation.h.
References mdisambiguation.
Referenced by operator=().
getMsourceText()
QString qmu::QmuTranslation::getMsourceText () const inline
Definition at line 81 of file qmutranslation.h.
References msourceText.
Referenced by operator=().
getN()
int qmu::QmuTranslation::getN () const inline
Definition at line 93 of file qmutranslation.h.
References mn.
Referenced by operator=().
operator=()
QmuTranslation & qmu::QmuTranslation::operator= (const QmuTranslation & tr)
Definition at line 53 of file qmutranslation.cpp.
References getMcontext(), getMdisambiguation(), getMsourceText(), getN(), mcontext, mdisambiguation, mn, and msourceText.
translate() [1/2]
QString qmu::QmuTranslation::translate () const
Definition at line 73 of file qmutranslation.cpp.
References mcontext, mdisambiguation, mn, msourceText, and translate.
Referenced by VTranslateVars::VariablesFromUser().
translate() [2/2]
QmuTranslation qmu::QmuTranslation::translate (const QString & context, const QString & sourceText, const QString & disambiguation = nullptr, int n = -1) static
Definition at line 31 of file qmutranslation.cpp.
Member Data Documentation
mcontext
QString qmu::QmuTranslation::mcontext private
Definition at line 68 of file qmutranslation.h.
Referenced by getMcontext(), operator=(), and translate().
mdisambiguation
QString qmu::QmuTranslation::mdisambiguation private
Definition at line 70 of file qmutranslation.h.
Referenced by getMdisambiguation(), operator=(), and translate().
mn
int qmu::QmuTranslation::mn private
Definition at line 71 of file qmutranslation.h.
Referenced by getN(), operator=(), and translate().
msourceText
QString qmu::QmuTranslation::msourceText private
Definition at line 69 of file qmutranslation.h.
Referenced by getMsourceText(), operator=(), and translate().
The documentation for this class was generated from the following files:
src/libs/qmuparser/qmutranslation.h
src/libs/qmuparser/qmutranslation.cpp