Seamly2D: src/libs/vmisc/projectversion.cpp File Reference
projectversion.cpp File Reference
#include "projectversion.h"
#include <qcompilerdetection.h>
#include <QCoreApplication>
#include <QLatin1Char>
#include <QLatin1String>
#include <QObject>
#include <QStaticStringData>
#include <QString>
#include <QStringData>
#include <QStringDataPtr>
#include <QSysInfo>
#include <QtGlobal>
Functions
const QString APP_VERSION_STR (QStringLiteral("%1.%2.%3.%4").arg(MAJOR_VERSION).arg(MINOR_VERSION) .arg(DEBUG_VERSION).arg(SUPER_MINOR__VERSION))
QString compilerString ()
QString buildCompatibilityString ()
Variables
const int MAJOR_VERSION = 0
const int MINOR_VERSION = 6
const int DEBUG_VERSION = 0
const int SUPER_MINOR__VERSION = 1
Function Documentation
APP_VERSION_STR()
const QString APP_VERSION_STR (QStringLiteral("%1.%2.%3.%4").arg(MAJOR_VERSION).arg(MINOR_VERSION) .arg(DEBUG_VERSION).arg(SUPER_MINOR__VERSION))
buildCompatibilityString()
QString buildCompatibilityString ()
Definition at line 132 of file projectversion.cpp.
References compilerString().
Referenced by DialogAboutApp::DialogAboutApp(), VApplication::InitOptions(), MApplication::InitOptions(), and DialogAboutSeamlyMe::RetranslateUi().
compilerString()
QString compilerString ()
Definition at line 77 of file projectversion.cpp.
Referenced by buildCompatibilityString().
Variable Documentation
DEBUG_VERSION
const int DEBUG_VERSION = 0 extern
MAJOR_VERSION
const int MAJOR_VERSION = 0 extern
MINOR_VERSION
const int MINOR_VERSION = 6 extern
SUPER_MINOR__VERSION
const int SUPER_MINOR__VERSION = 1 extern