Seamly2D: PreferencesPathPage Class Reference
PreferencesPathPage Class Reference
#include <preferencespathpage.h>
Public Member Functions
PreferencesPathPage (QWidget *parent=nullptr)
virtual ~PreferencesPathPage ()
void Apply ()
Private Slots
void DefaultPath ()
void EditPath ()
Private Member Functions
void InitTable ()
Private Attributes
Ui::PreferencesPathPage * ui
Detailed Description
Definition at line 62 of file preferencespathpage.h.
Constructor & Destructor Documentation
PreferencesPathPage()
PreferencesPathPage::PreferencesPathPage (QWidget * parent = nullptr) explicit
Definition at line 62 of file preferencespathpage.cpp.
References DefaultPath(), EditPath(), InitTable(), and ui.
~PreferencesPathPage()
PreferencesPathPage::~PreferencesPathPage () virtual
Definition at line 75 of file preferencespathpage.cpp.
References ui.
Member Function Documentation
Apply()
void PreferencesPathPage::Apply ()
Definition at line 81 of file preferencespathpage.cpp.
References qApp, VCommonSettings::SetPathIndividualMeasurements(), VCommonSettings::SetPathLabelTemplate(), VSettings::SetPathLayout(), VCommonSettings::SetPathMultisizeMeasurements(), VSettings::SetPathPattern(), VCommonSettings::SetPathTemplate(), and ui.
Referenced by DialogPreferences::Apply().
DefaultPath
void PreferencesPathPage::DefaultPath () private slot
Definition at line 93 of file preferencespathpage.cpp.
References VCommonSettings::GetDefPathIndividualMeasurements(), VCommonSettings::GetDefPathLabelTemplate(), VSettings::GetDefPathLayout(), VCommonSettings::GetDefPathMultisizeMeasurements(), VSettings::GetDefPathPattern(), VCommonSettings::GetDefPathTemplate(), SCASSERT, and ui.
Referenced by EditPath(), and PreferencesPathPage().
EditPath
void PreferencesPathPage::EditPath () private slot
Definition at line 130 of file preferencespathpage.cpp.
References DefaultPath(), VCommonSettings::PrepareMultisizeTables(), qApp, SCASSERT, and ui.
Referenced by PreferencesPathPage().
InitTable()
void PreferencesPathPage::InitTable () private
Definition at line 195 of file preferencespathpage.cpp.
References VSettings::getLayoutPath(), VCommonSettings::GetPathIndividualMeasurements(), VCommonSettings::GetPathLabelTemplate(), VCommonSettings::GetPathMultisizeMeasurements(), VSettings::GetPathPattern(), VCommonSettings::GetPathTemplate(), qApp, and ui.
Referenced by PreferencesPathPage().
Member Data Documentation
ui
Ui::PreferencesPathPage* PreferencesPathPage::ui private
Definition at line 78 of file preferencespathpage.h.
Referenced by Apply(), DefaultPath(), EditPath(), InitTable(), PreferencesPathPage(), and ~PreferencesPathPage().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/configpages/preferencespathpage.h
src/app/seamly2d/dialogs/configpages/preferencespathpage.cpp