Seamly2D: VPE::VSerializedProperty Class Reference
VPE::VSerializedProperty Class Reference
#include <vserializedproperty.h>
Public Member Functions
VSerializedProperty ()
Constructor.
VSerializedProperty (const VProperty *property, const VPropertySet *set)
Constructor.
VSerializedProperty (const VProperty *property, const QString &id, const VPropertySet *set)
Constructor.
VSerializedProperty (const QString &id, const QString &type, const QVariant &value)
Constructor.
Public Attributes
QString ID
The property type.
QString Type
The property type.
QVariant Value
The serialized value of the property.
QList< VSerializedProperty > Children
List of child properties.
Private Member Functions
void initChildren (const VProperty *property, const VPropertySet *set)
Detailed Description
Definition at line 34 of file vserializedproperty.h.
Constructor & Destructor Documentation
VSerializedProperty() [1/4]
VPE::VSerializedProperty::VSerializedProperty ()
Constructor.
Definition at line 28 of file vserializedproperty.cpp.
VSerializedProperty() [2/4]
VPE::VSerializedProperty::VSerializedProperty (const VProperty * property, const VPropertySet * set)
Constructor.
Creates a new VSerializedProperty from an existing property
Definition at line 35 of file vserializedproperty.cpp.
References VPE::VPropertySet::getPropertyID(), ID, and initChildren().
VSerializedProperty() [3/4]
VPE::VSerializedProperty::VSerializedProperty (const VProperty * property, const QString & id, const VPropertySet * set)
Constructor.
Definition at line 47 of file vserializedproperty.cpp.
References initChildren().
VSerializedProperty() [4/4]
VPE::VSerializedProperty::VSerializedProperty (const QString & id, const QString & type, const QVariant & value)
Constructor.
Definition at line 54 of file vserializedproperty.cpp.
Member Function Documentation
initChildren()
void VPE::VSerializedProperty::initChildren (const VProperty * property, const VPropertySet * set) private
Definition at line 59 of file vserializedproperty.cpp.
References VPE::VPropertySet::getPropertyID().
Referenced by VSerializedProperty().
Member Data Documentation
Children
QList<VSerializedProperty> VPE::VSerializedProperty::Children
List of child properties.
Definition at line 59 of file vserializedproperty.h.
ID
QString VPE::VSerializedProperty::ID
The property type.
Definition at line 50 of file vserializedproperty.h.
Referenced by VSerializedProperty().
Type
QString VPE::VSerializedProperty::Type
The property type.
Definition at line 53 of file vserializedproperty.h.
Value
QVariant VPE::VSerializedProperty::Value
The serialized value of the property.
Definition at line 56 of file vserializedproperty.h.
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/vserializedproperty.h
src/libs/vpropertyexplorer/vserializedproperty.cpp