Seamly2D: TST_QmuTokenParser Class Reference
TST_QmuTokenParser Class Reference
#include <tst_qmutokenparser.h>
Public Member Functions
TST_QmuTokenParser (QObject *parent=nullptr)
Private Slots
void IsSingle_data ()
void IsSingle ()
void TokenFromUser_data ()
void TokenFromUser ()
void cleanupTestCase ()
Private Member Functions
void PrepareVal (qreal val, const QLocale &locale)
bool IsSingleFromUser (const QString &formula)
Private Attributes
QLocale m_systemLocale
Detailed Description
Definition at line 58 of file tst_qmutokenparser.h.
Constructor & Destructor Documentation
TST_QmuTokenParser()
TST_QmuTokenParser::TST_QmuTokenParser (QObject * parent = nullptr) explicit
Definition at line 59 of file tst_qmutokenparser.cpp.
Member Function Documentation
cleanupTestCase
void TST_QmuTokenParser::cleanupTestCase () private slot
Definition at line 128 of file tst_qmutokenparser.cpp.
References m_systemLocale.
IsSingle
void TST_QmuTokenParser::IsSingle () private slot
Definition at line 90 of file tst_qmutokenparser.cpp.
References qmu::QmuTokenParser::IsSingle().
IsSingle_data
void TST_QmuTokenParser::IsSingle_data () private slot
Definition at line 66 of file tst_qmutokenparser.cpp.
IsSingleFromUser()
bool TST_QmuTokenParser::IsSingleFromUser (const QString & formula) private
Definition at line 155 of file tst_qmutokenparser.cpp.
References qmu::QmuFormulaBase::RemoveAll().
Referenced by TokenFromUser().
PrepareVal()
void TST_QmuTokenParser::PrepareVal (qreal val, const QLocale & locale) private
Definition at line 134 of file tst_qmutokenparser.cpp.
Referenced by TokenFromUser_data().
TokenFromUser
void TST_QmuTokenParser::TokenFromUser () private slot
Definition at line 116 of file tst_qmutokenparser.cpp.
References IsSingleFromUser().
TokenFromUser_data
void TST_QmuTokenParser::TokenFromUser_data () private slot
Definition at line 99 of file tst_qmutokenparser.cpp.
References PrepareVal().
Member Data Documentation
m_systemLocale
QLocale TST_QmuTokenParser::m_systemLocale private
Definition at line 71 of file tst_qmutokenparser.h.
Referenced by cleanupTestCase().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_qmutokenparser.h
src/test/Seamly2DTest/tst_qmutokenparser.cpp