Seamly2D: VException Class Reference
VException Class Reference
The VException class parent for all exception. Could be use for abstract exception.
#include <vexception.h>
Public Member Functions
VException (const QString &error)
VException constructor exception.
VException (const VException &error)
VException copy constructor.
VException & operator= (const VException &error)
virtual ~VException () Q_DECL_EQ_DEFAULT
virtual Q_NORETURN void raise () const Q_DECL_OVERRIDE
raise method raise for exception
virtual Q_REQUIRED_RESULT VException * clone () const Q_DECL_OVERRIDE
clone clone exception
virtual QString ErrorMessage () const
ErrorMessage return main error message.
virtual QString DetailedInformation () const
DetailedInformation return detailed information about error.
QString WhatUtf8 () const
What return string with error.
void AddMoreInformation (const QString &info)
AddMoreInformation add more information for error.
QString MoreInformation () const
MoreInformation return more information for error.
virtual const char * what () const Q_DECL_OVERRIDE
Protected Member Functions
QString MoreInfo (const QString &detInfo) const
Protected Attributes
QString error
error string with error
QString moreInfo
moreInfo more information about error
Detailed Description
The VException class parent for all exception. Could be use for abstract exception.
Definition at line 65 of file vexception.h.
Constructor & Destructor Documentation
VException() [1/2]
VException::VException (const QString & error) explicit
VException constructor exception.
Parameters
error string with error
Definition at line 66 of file vexception.cpp.
References error.
Referenced by clone().
VException() [2/2]
VException::VException (const VException & error)
VException copy constructor.
Parameters
e exception
Definition at line 79 of file vexception.cpp.
~VException()
virtual VException::~VException () virtual
Member Function Documentation
AddMoreInformation()
void VException::AddMoreInformation (const QString & info)
AddMoreInformation add more information for error.
Parameters
info information
Definition at line 109 of file vexception.cpp.
References moreInfo.
Referenced by MainWindow::checkRequiredMeasurements(), VPatternConverter::FixIncrementsToV0_2_0(), VDomDocument::getParameterBool(), VDomDocument::getParameterId(), VDomDocument::GetParametrDouble(), VDomDocument::GetParametrUInt(), VPatternConverter::MUnitV0_1_4(), VPattern::ParseAnchorPoint(), VPattern::parseIntersectXYTool(), VAbstractPattern::parseItemElement(), VPattern::ParseLineElement(), VPattern::ParseNodeArc(), VPattern::ParseNodeEllipticalArc(), VPattern::ParseNodePoint(), VPattern::ParseNodeSpline(), VPattern::ParseNodeSplinePath(), VPattern::ParseOldToolSpline(), VPattern::ParseOldToolSplinePath(), VPattern::ParsePathElement(), VPattern::parsePieceElement(), VPattern::ParseToolAlongLine(), VPattern::ParseToolArc(), VPattern::ParseToolArcWithLength(), VPattern::ParseToolBasePoint(), VPattern::ParseToolBisector(), VPattern::ParseToolCubicBezier(), VPattern::ParseToolCubicBezierPath(), VPattern::ParseToolCurveIntersectAxis(), VPattern::ParseToolCutArc(), VPattern::ParseToolCutSpline(), VPattern::ParseToolCutSplinePath(), VPattern::ParseToolEllipticalArc(), VPattern::ParseToolEndLine(), VPattern::ParseToolHeight(), VPattern::ParseToolLineIntersect(), VPattern::ParseToolLineIntersectAxis(), VPattern::ParseToolMirrorByAxis(), VPattern::ParseToolMirrorByLine(), VPattern::ParseToolMove(), VPattern::ParseToolNormal(), VPattern::ParseToolPointFromArcAndTangent(), VPattern::ParseToolPointFromCircleAndTangent(), VPattern::ParseToolPointOfContact(), VPattern::ParseToolPointOfIntersectionArcs(), VPattern::ParseToolPointOfIntersectionCircles(), VPattern::ParseToolPointOfIntersectionCurves(), VPattern::ParseToolRotation(), VPattern::ParseToolsElement(), VPattern::ParseToolShoulderPoint(), VPattern::ParseToolSpline(), VPattern::ParseToolSplinePath(), VPattern::ParseToolTriangle(), VPattern::ParseToolTrueDarts(), VDomDocument::setXMLContent(), and VDomDocument::ValidateXML().
clone()
VException * VException::clone () const virtual
clone clone exception
Returns
new exception
Reimplemented in VExceptionToolWasDeleted.
Definition at line 147 of file vexception.cpp.
References VException().
DetailedInformation()
QString VException::DetailedInformation () const virtual
DetailedInformation return detailed information about error.
Returns
detailed information
Reimplemented in VExceptionWrongId, VExceptionObjectError, and VExceptionEmptyParameter.
Definition at line 136 of file vexception.cpp.
References moreInfo.
Referenced by MainWindow::changeDraftBlockGlobally(), MainWindow::exportLayoutAs(), MainWindow::exportPiecesAs(), MainWindow::fullParseFile(), TMainWindow::Fx(), GroupsWidget::getObjName(), TMainWindow::ImportFromPattern(), EditLabelTemplateDialog::ImportTemplate(), VPattern::LiteParseIncrements(), VPattern::LiteParseTree(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), MainWindow::LoadPattern(), VDrawTool::ObjectName(), MainWindow::openMeasurementFile(), PatternPieceDialog::pathDialogClosed(), TMainWindow::SaveMFullName(), TMainWindow::SaveMName(), and TMainWindow::SaveMValue().
ErrorMessage()
QString VException::ErrorMessage () const virtual
ErrorMessage return main error message.
Returns
error message
Reimplemented in VExceptionWrongId, VExceptionObjectError, VExceptionEmptyParameter, VExceptionConversionError, and VExceptionBadId.
Definition at line 99 of file vexception.cpp.
References error.
Referenced by TST_Measurements::CreateEmptyIndividualFile(), TST_Measurements::CreateEmptyMultisizeFile(), MainWindow::DoExport(), MainWindow::exportLayoutAs(), MainWindow::exportPiecesAs(), MainWindow::fullParseFile(), TMainWindow::ImportFromPattern(), EditLabelTemplateDialog::ImportTemplate(), VPattern::LiteParseIncrements(), VPattern::LiteParseTree(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), MainWindow::LoadPattern(), MainWindow::openMeasurementFile(), MainWindow::showLayoutMode(), TST_Measurements::ValidPMCodesIndividualFile(), and TST_Measurements::ValidPMCodesMultisizeFile().
MoreInfo()
QString VException::MoreInfo (const QString & detInfo) const protected
Definition at line 119 of file vexception.cpp.
References moreInfo.
Referenced by VExceptionEmptyParameter::DetailedInformation(), VExceptionObjectError::DetailedInformation(), and VExceptionWrongId::DetailedInformation().
MoreInformation()
QString VException::MoreInformation () const inline
MoreInformation return more information for error.
Returns
information
Definition at line 111 of file vexception.h.
References moreInfo.
Referenced by operator=().
operator=()
VException & VException::operator= (const VException & error)
Definition at line 83 of file vexception.cpp.
References error, moreInfo, and MoreInformation().
Referenced by VExceptionBadId::operator=(), VExceptionConversionError::operator=(), VExceptionEmptyParameter::operator=(), VExceptionObjectError::operator=(), VExceptionToolWasDeleted::operator=(), and VExceptionWrongId::operator=().
raise()
Q_NORETURN void VException::raise () const virtual
raise method raise for exception
Reimplemented in VExceptionToolWasDeleted.
Definition at line 157 of file vexception.cpp.
what()
const char * VException::what () const virtual
Definition at line 163 of file vexception.cpp.
References error.
Referenced by VApplication::notify(), and MApplication::notify().
WhatUtf8()
QString VException::WhatUtf8 () const inline
What return string with error.
Returns
string with error
Definition at line 101 of file vexception.h.
References error.
Member Data Documentation
error
QString VException::error protected
error string with error
Definition at line 88 of file vexception.h.
Referenced by ErrorMessage(), VExceptionBadId::ErrorMessage(), VExceptionConversionError::ErrorMessage(), VExceptionEmptyParameter::ErrorMessage(), VExceptionObjectError::ErrorMessage(), VExceptionWrongId::ErrorMessage(), operator=(), VExceptionBadId::operator=(), VExceptionConversionError::operator=(), VExceptionEmptyParameter::operator=(), VExceptionObjectError::operator=(), VExceptionToolWasDeleted::operator=(), VExceptionWrongId::operator=(), VException(), what(), and WhatUtf8().
moreInfo
QString VException::moreInfo protected
moreInfo more information about error
Definition at line 91 of file vexception.h.
Referenced by AddMoreInformation(), DetailedInformation(), MoreInfo(), MoreInformation(), and operator=().
The documentation for this class was generated from the following files:
src/libs/ifc/exception/vexception.h
src/libs/ifc/exception/vexception.cpp