Seamly2D: DialogMove Class Reference
DialogMove Class Reference
#include <dialogmove.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
virtual void SelectedObject (bool selected, quint32 id, quint32 tool) Q_DECL_OVERRIDE
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogMove (const VContainer *data, quint32 toolId, QWidget *parent=nullptr)
virtual ~DialogMove ()
QString GetAngle () const
void SetAngle (const QString &value)
QString GetLength () const
void SetLength (const QString &value)
QString getRotation () const
void setRotation (const QString &value)
QString getSuffix () const
void setSuffix (const QString &value)
quint32 getOriginPointId () const
void setOriginPointId (const quint32 &value)
virtual void ShowDialog (bool click) Q_DECL_OVERRIDE
QVector< SourceItem > getSourceObjects () const
void setSourceObjects (const QVector< SourceItem > &value)
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void CheckState () Q_DECL_FINAL
CheckState enable, when all is correct, or disable, when something wrong, button ok.
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Slots
void angleChanged ()
void lengthChanged ()
void rotationChanged ()
void editAngleFormula ()
void editLengthFormula ()
void editRotationFormula ()
void suffixChanged ()
void originChanged (const QString &text)
Private Member Functions
void evaluateAngle ()
void evaluateLength ()
void evaluateRotation ()
Private Attributes
Ui::DialogMove * ui
bool angleFlag
QString angleFormula
angleFlag true if value of angle is correct *‍/
QTimer * angleTimer
angle formula of angle *‍/
bool lengthFlag
angleTimer timer of check formula of angle *‍/
QString lengthFormula
lengthFlag true if value of length is correct *‍/
QTimer * lengthTimer
length formula of length *‍/
bool rotationFlag
lengthTimer timer of check formula of length *‍/
QString rotationFormula
rotationFlag true if value of length is correct *‍/
QTimer * rotationTimer
rotationFormula of rotation *‍/
QVector< SourceItem > m_objects
rotationTimer timer of check formula of rotation *‍/
bool stage1
bool stage2
QString m_suffix
bool useOriginPoint
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
Definition at line 72 of file dialogmove.h.
Constructor & Destructor Documentation
DialogMove()
DialogMove::DialogMove (const VContainer * data, quint32 toolId, QWidget * parent = nullptr) explicit
Definition at line 90 of file dialogmove.cpp.
References angleChanged(), angleTimer, CheckState(), DialogTool::data, editAngleFormula(), editLengthFormula(), editRotationFormula(), evaluateAngle(), evaluateLength(), evaluateRotation(), DialogTool::FillComboBoxPoints(), DialogTool::flagName, DialogTool::initializeOkCancelApply(), lengthChanged(), lengthTimer, NULL_ID, originChanged(), qApp, rotationChanged(), rotationTimer, setOriginPointId(), suffixChanged(), ui, and DialogTool::vis.
~DialogMove()
DialogMove::~DialogMove () virtual
Definition at line 153 of file dialogmove.cpp.
References ui.
Member Function Documentation
angleChanged
void DialogMove::angleChanged () private slot
Definition at line 377 of file dialogmove.cpp.
References angleFlag, angleTimer, degreeSymbol, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogMove().
CheckState()
void DialogMove::CheckState () protected virtual
CheckState enable, when all is correct, or disable, when something wrong, button ok.
Reimplemented from DialogTool.
Definition at line 501 of file dialogmove.cpp.
References angleFlag, DialogTool::apply_Button, DialogTool::flagName, lengthFlag, DialogTool::ok_Button, rotationFlag, and SCASSERT.
Referenced by DialogMove(), and suffixChanged().
ChosenObject
void DialogMove::ChosenObject (quint32 id, const SceneObject & type) virtual slot
Definition at line 329 of file dialogmove.cpp.
References Point, DialogTool::prepare, VisToolMove::RefreshGeometry(), SCASSERT, DialogTool::SetObject(), VisToolMove::setOriginPointId(), stage1, stage2, ui, useOriginPoint, and DialogTool::vis.
closeEvent()
void DialogMove::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 541 of file dialogmove.cpp.
References DialogTool::closeEvent(), and ui.
editAngleFormula
void DialogMove::editAngleFormula () private slot
Definition at line 401 of file dialogmove.cpp.
References DialogTool::data, degreeSymbol, GetAngle(), EditFormulaDialog::GetFormula(), SetAngle(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), and DialogTool::toolId.
Referenced by DialogMove().
editLengthFormula
void DialogMove::editLengthFormula () private slot
Definition at line 415 of file dialogmove.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), GetLength(), qApp, EditFormulaDialog::SetFormula(), SetLength(), EditFormulaDialog::setPostfix(), DialogTool::toolId, and UnitsToStr().
Referenced by DialogMove().
editRotationFormula
void DialogMove::editRotationFormula () private slot
Definition at line 429 of file dialogmove.cpp.
References DialogTool::data, degreeSymbol, EditFormulaDialog::GetFormula(), getRotation(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), setRotation(), and DialogTool::toolId.
Referenced by DialogMove().
evaluateAngle()
void DialogMove::evaluateAngle () private
Definition at line 566 of file dialogmove.cpp.
References angleFlag, degreeSymbol, DialogTool::Eval(), DialogTool::labelEditFormula, and ui.
Referenced by DialogMove().
evaluateLength()
void DialogMove::evaluateLength () private
Definition at line 573 of file dialogmove.cpp.
References DialogTool::Eval(), DialogTool::labelEditFormula, lengthFlag, qApp, ui, and UnitsToStr().
Referenced by DialogMove().
evaluateRotation()
void DialogMove::evaluateRotation () private
Definition at line 581 of file dialogmove.cpp.
References degreeSymbol, DialogTool::Eval(), DialogTool::labelEditFormula, rotationFlag, and ui.
Referenced by DialogMove().
GetAngle()
QString DialogMove::GetAngle () const
Definition at line 159 of file dialogmove.cpp.
References angleFormula, and qApp.
Referenced by editAngleFormula().
GetLength()
QString DialogMove::GetLength () const
Definition at line 178 of file dialogmove.cpp.
References lengthFormula, and qApp.
Referenced by editLengthFormula().
getOriginPointId()
quint32 DialogMove::getOriginPointId () const
Definition at line 229 of file dialogmove.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
getRotation()
QString DialogMove::getRotation () const
Definition at line 197 of file dialogmove.cpp.
References qApp, and rotationFormula.
Referenced by editRotationFormula().
getSourceObjects()
QVector< SourceItem > DialogMove::getSourceObjects () const
Definition at line 550 of file dialogmove.cpp.
References m_objects.
getSuffix()
QString DialogMove::getSuffix () const
Definition at line 216 of file dialogmove.cpp.
References m_suffix.
lengthChanged
void DialogMove::lengthChanged () private slot
Definition at line 385 of file dialogmove.cpp.
References degreeSymbol, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, lengthFlag, lengthTimer, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogMove().
originChanged
void DialogMove::originChanged (const QString & text) private slot
Definition at line 483 of file dialogmove.cpp.
References DialogTool::getCurrentObjectId(), NULL_ID, VisToolMove::RefreshGeometry(), SCASSERT, VisToolMove::setOriginPointId(), ui, useOriginPoint, and DialogTool::vis.
Referenced by DialogMove().
rotationChanged
void DialogMove::rotationChanged () private slot
Definition at line 393 of file dialogmove.cpp.
References degreeSymbol, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, rotationFlag, rotationTimer, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogMove().
SaveData()
void DialogMove::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 516 of file dialogmove.cpp.
References angleFormula, getOriginPointId(), lengthFormula, m_objects, m_suffix, VisToolMove::RefreshGeometry(), rotationFormula, SCASSERT, VisToolMove::SetAngle(), VisToolMove::SetLength(), VisOperation::setObjects(), VisToolMove::setOriginPointId(), VisToolMove::setRotation(), sourceToObjects(), ui, and DialogTool::vis.
SelectedObject
void DialogMove::SelectedObject (bool selected, quint32 id, quint32 tool) virtual slot
Definition at line 349 of file dialogmove.cpp.
References SourceItem::id, m_objects, and stage1.
SetAngle()
void DialogMove::SetAngle (const QString & value)
Definition at line 165 of file dialogmove.cpp.
References angleFormula, DialogTool::MoveCursorToEnd(), qApp, SCASSERT, VisToolMove::SetAngle(), ui, and DialogTool::vis.
Referenced by editAngleFormula(), and ShowDialog().
SetLength()
void DialogMove::SetLength (const QString & value)
Definition at line 184 of file dialogmove.cpp.
References lengthFormula, DialogTool::MoveCursorToEnd(), qApp, SCASSERT, VisToolMove::SetLength(), ui, and DialogTool::vis.
Referenced by editLengthFormula(), and ShowDialog().
setOriginPointId()
void DialogMove::setOriginPointId (const quint32 & value)
Definition at line 235 of file dialogmove.cpp.
References DialogTool::ChangeCurrentData(), SCASSERT, VisToolMove::setOriginPointId(), ui, and DialogTool::vis.
Referenced by DialogMove().
setRotation()
void DialogMove::setRotation (const QString & value)
Definition at line 203 of file dialogmove.cpp.
References DialogTool::MoveCursorToEnd(), qApp, rotationFormula, SCASSERT, VisToolMove::setRotation(), ui, and DialogTool::vis.
Referenced by editRotationFormula(), and ShowDialog().
setSourceObjects()
void DialogMove::setSourceObjects (const QVector< SourceItem > & value)
Definition at line 556 of file dialogmove.cpp.
References m_objects, SCASSERT, VisOperation::setObjects(), sourceToObjects(), and DialogTool::vis.
setSuffix()
void DialogMove::setSuffix (const QString & value)
Definition at line 222 of file dialogmove.cpp.
References m_suffix, and ui.
ShowDialog()
void DialogMove::ShowDialog (bool click) virtual
Reimplemented from DialogTool.
Definition at line 244 of file dialogmove.cpp.
References VisToolMove::Angle(), angleFormula, angleTimer, Visualization::CurrentToolTip(), VisToolMove::Length(), lengthFormula, lengthTimer, VisToolMove::LengthValue(), m_objects, NULL_ID, DialogTool::prepare, qApp, VisToolMove::RefreshGeometry(), VisToolMove::Rotation(), rotationTimer, SCASSERT, VisToolMove::SetAngle(), SetAngle(), VisToolMove::SetLength(), SetLength(), DialogTool::SetObject(), VisOperation::setObjects(), VisToolMove::setOriginPointId(), setRotation(), VAbstractMainWindow::ShowToolTip(), sourceToObjects(), stage1, stage2, VMainGraphicsScene::ToggleArcHover(), VMainGraphicsScene::ToggleArcSelection(), VMainGraphicsScene::ToggleElArcHover(), VMainGraphicsScene::ToggleElArcSelection(), VMainGraphicsScene::ToggleSplineHover(), VMainGraphicsScene::ToggleSplinePathHover(), VMainGraphicsScene::ToggleSplinePathSelection(), VMainGraphicsScene::ToggleSplineSelection(), DialogTool::ToolTip(), Visualization::ToolTip(), ui, useOriginPoint, DialogTool::vis, and VisOperation::VisualMode().
ShowVisualization()
void DialogMove::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 510 of file dialogmove.cpp.
suffixChanged
void DialogMove::suffixChanged () private slot
Definition at line 443 of file dialogmove.cpp.
References VContainer::AllUniqueNames(), DialogTool::ChangeColor(), CheckState(), DialogTool::data, DialogTool::flagName, VContainer::IsUnique(), m_suffix, NameRegExp(), DialogTool::okColor, and ui.
Referenced by DialogMove().
Member Data Documentation
angleFlag
bool DialogMove::angleFlag private
Definition at line 127 of file dialogmove.h.
Referenced by angleChanged(), CheckState(), and evaluateAngle().
angleFormula
QString DialogMove::angleFormula private
angleFlag true if value of angle is correct *‍/
Definition at line 128 of file dialogmove.h.
Referenced by GetAngle(), SaveData(), SetAngle(), and ShowDialog().
angleTimer
QTimer* DialogMove::angleTimer private
angle formula of angle *‍/
Definition at line 129 of file dialogmove.h.
Referenced by angleChanged(), DialogMove(), and ShowDialog().
lengthFlag
bool DialogMove::lengthFlag private
angleTimer timer of check formula of angle *‍/
Definition at line 130 of file dialogmove.h.
Referenced by CheckState(), evaluateLength(), and lengthChanged().
lengthFormula
QString DialogMove::lengthFormula private
lengthFlag true if value of length is correct *‍/
Definition at line 131 of file dialogmove.h.
Referenced by GetLength(), SaveData(), SetLength(), and ShowDialog().
lengthTimer
QTimer* DialogMove::lengthTimer private
length formula of length *‍/
Definition at line 132 of file dialogmove.h.
Referenced by DialogMove(), lengthChanged(), and ShowDialog().
m_objects
QVector<SourceItem> DialogMove::m_objects private
rotationTimer timer of check formula of rotation *‍/
Definition at line 136 of file dialogmove.h.
Referenced by getSourceObjects(), SaveData(), SelectedObject(), setSourceObjects(), and ShowDialog().
m_suffix
QString DialogMove::m_suffix private
Definition at line 139 of file dialogmove.h.
Referenced by getSuffix(), SaveData(), setSuffix(), and suffixChanged().
rotationFlag
bool DialogMove::rotationFlag private
lengthTimer timer of check formula of length *‍/
Definition at line 133 of file dialogmove.h.
Referenced by CheckState(), evaluateRotation(), and rotationChanged().
rotationFormula
QString DialogMove::rotationFormula private
rotationFlag true if value of length is correct *‍/
Definition at line 134 of file dialogmove.h.
Referenced by getRotation(), SaveData(), and setRotation().
rotationTimer
QTimer* DialogMove::rotationTimer private
rotationFormula of rotation *‍/
Definition at line 135 of file dialogmove.h.
Referenced by DialogMove(), rotationChanged(), and ShowDialog().
stage1
bool DialogMove::stage1 private
Definition at line 137 of file dialogmove.h.
Referenced by ChosenObject(), SelectedObject(), and ShowDialog().
stage2
bool DialogMove::stage2 private
Definition at line 138 of file dialogmove.h.
Referenced by ChosenObject(), and ShowDialog().
ui
Ui::DialogMove* DialogMove::ui private
Definition at line 126 of file dialogmove.h.
Referenced by angleChanged(), ChosenObject(), closeEvent(), DialogMove(), evaluateAngle(), evaluateLength(), evaluateRotation(), getOriginPointId(), lengthChanged(), originChanged(), rotationChanged(), SaveData(), SetAngle(), SetLength(), setOriginPointId(), setRotation(), setSuffix(), ShowDialog(), suffixChanged(), and ~DialogMove().
useOriginPoint
bool DialogMove::useOriginPoint private
Definition at line 140 of file dialogmove.h.
Referenced by ChosenObject(), originChanged(), and ShowDialog().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogmove.h
src/libs/vtools/dialogs/tools/dialogmove.cpp