Seamly2D: VisToolCutSplinePath Class Reference
VisToolCutSplinePath Class Reference
#include <vistoolcutsplinepath.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolCutSpline) }
Public Types inherited from VisPath
enum { Type = UserType + static_cast<int>(Vis::Path) }
Public Types inherited from VCurvePathItem
enum { Type = UserType + static_cast<int>(Vis::CurvePathItem) }
Public Member Functions
VisToolCutSplinePath (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolCutSplinePath () Q_DECL_EQ_DEFAULT
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setLength (const QString &expression)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisPath
VisPath (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisPath ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VCurvePathItem
VCurvePathItem (QGraphicsItem *parent=nullptr)
virtual ~VCurvePathItem ()=default
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
void SetDirectionArrows (const QVector< QPair< QLineF, QLineF >> &arrows)
void SetPoints (const QVector< QPointF > &points)
Protected Attributes
VScaledEllipse * point
VCurvePathItem * splPath1
VCurvePathItem * splPath2
qreal length
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisPath
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
VSimplePoint * GetPoint (QVector< VSimplePoint * > &points, quint32 i, const QColor &color)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Protected Member Functions inherited from VCurvePathItem
virtual void ScalePenWidth ()
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Detailed Description
Definition at line 65 of file vistoolcutsplinepath.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 75 of file vistoolcutsplinepath.h.
Constructor & Destructor Documentation
VisToolCutSplinePath()
VisToolCutSplinePath::VisToolCutSplinePath (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 72 of file vistoolcutsplinepath.cpp.
References Visualization::InitPoint(), Visualization::mainColor, point, splPath1, and splPath2.
~VisToolCutSplinePath()
virtual VisToolCutSplinePath::~VisToolCutSplinePath () virtual
Member Function Documentation
RefreshGeometry()
void VisToolCutSplinePath::RefreshGeometry () virtual
Implements Visualization.
Definition at line 86 of file vistoolcutsplinepath.cpp.
References VToolCutSplinePath::CutSplinePath(), Visualization::data, VAbstractCubicBezierPath::DirectionArrows(), Visualization::DrawPath(), Visualization::DrawPoint(), VContainer::GeometricObject(), VAbstractCubicBezierPath::GetPath(), length, Visualization::lineStyle, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, point, SCASSERT, splPath, splPath1, splPath2, and Visualization::supportColor.
Referenced by DialogCutSplinePath::SaveData(), and VToolCutSplinePath::SetVisualization().
setLength()
void VisToolCutSplinePath::setLength (const QString & expression)
Definition at line 118 of file vistoolcutsplinepath.cpp.
References Visualization::data, Visualization::FindLength(), and length.
Referenced by DialogCutSplinePath::SaveData(), DialogCutSplinePath::SetFormula(), and VToolCutSplinePath::SetVisualization().
type()
virtual int VisToolCutSplinePath::type () const inline virtual
Reimplemented from VisPath.
Definition at line 74 of file vistoolcutsplinepath.h.
References Type.
Member Data Documentation
length
qreal VisToolCutSplinePath::length protected
Definition at line 81 of file vistoolcutsplinepath.h.
Referenced by RefreshGeometry(), and setLength().
point
VScaledEllipse* VisToolCutSplinePath::point protected
Definition at line 78 of file vistoolcutsplinepath.h.
Referenced by RefreshGeometry(), and VisToolCutSplinePath().
splPath1
VCurvePathItem* VisToolCutSplinePath::splPath1 protected
Definition at line 79 of file vistoolcutsplinepath.h.
Referenced by RefreshGeometry(), and VisToolCutSplinePath().
splPath2
VCurvePathItem* VisToolCutSplinePath::splPath2 protected
Definition at line 80 of file vistoolcutsplinepath.h.
Referenced by RefreshGeometry(), and VisToolCutSplinePath().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/path/vistoolcutsplinepath.h
src/libs/vtools/visualization/path/vistoolcutsplinepath.cpp