Seamly2D: PSVIAttributeList Class Reference
PSVIAttributeList Class Reference
#include <PSVIAttributeList.hpp>
Public Member Functions
Constructors
PSVIAttributeList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
PSVIAttributeList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
PSVIAttributeList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Destructor
~PSVIAttributeList ()
~PSVIAttributeList ()
~PSVIAttributeList ()
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
PSVIAttributeList methods
MemoryManager * fMemoryManager
RefVectorOf< PSVIAttributeStorage > * fAttrList
XMLSize_t fAttrPos
XMLSize_t getLength () const
PSVIAttribute * getAttributePSVIAtIndex (const XMLSize_t index)
const XMLCh * getAttributeNameAtIndex (const XMLSize_t index)
const XMLCh * getAttributeNamespaceAtIndex (const XMLSize_t index)
PSVIAttribute * getAttributePSVIByName (const XMLCh *attrName, const XMLCh *attrNamespace)
PSVIAttribute * getPSVIAttributeToFill (const XMLCh *attrName, const XMLCh *attrNS)
void reset ()
XMLSize_t getLength () const
PSVIAttribute * getAttributePSVIAtIndex (const XMLSize_t index)
const XMLCh * getAttributeNameAtIndex (const XMLSize_t index)
const XMLCh * getAttributeNamespaceAtIndex (const XMLSize_t index)
PSVIAttribute * getAttributePSVIByName (const XMLCh *attrName, const XMLCh *attrNamespace)
PSVIAttribute * getPSVIAttributeToFill (const XMLCh *attrName, const XMLCh *attrNS)
void reset ()
XMLSize_t getLength () const
PSVIAttribute * getAttributePSVIAtIndex (const XMLSize_t index)
const XMLCh * getAttributeNameAtIndex (const XMLSize_t index)
const XMLCh * getAttributeNamespaceAtIndex (const XMLSize_t index)
PSVIAttribute * getAttributePSVIByName (const XMLCh *attrName, const XMLCh *attrNamespace)
PSVIAttribute * getPSVIAttributeToFill (const XMLCh *attrName, const XMLCh *attrNS)
void reset ()
PSVIAttributeList (const PSVIAttributeList &)
PSVIAttributeList & operator= (const PSVIAttributeList &)
PSVIAttributeList (const PSVIAttributeList &)
PSVIAttributeList & operator= (const PSVIAttributeList &)
PSVIAttributeList (const PSVIAttributeList &)
PSVIAttributeList & operator= (const PSVIAttributeList &)
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 59 of file PSVIAttributeList.hpp.
Constructor & Destructor Documentation
PSVIAttributeList() [1/6]
PSVIAttributeList::PSVIAttributeList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
The default constructor
Parameters
manager The configurable memory manager
~PSVIAttributeList() [1/3]
PSVIAttributeList::~PSVIAttributeList () inline
Definition at line 182 of file PSVIAttributeList.hpp.
References fAttrList.
PSVIAttributeList() [2/6]
PSVIAttributeList::PSVIAttributeList (const PSVIAttributeList &) private
PSVIAttributeList() [3/6]
PSVIAttributeList::PSVIAttributeList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
The default constructor
Parameters
manager The configurable memory manager
~PSVIAttributeList() [2/3]
PSVIAttributeList::~PSVIAttributeList ()
PSVIAttributeList() [4/6]
PSVIAttributeList::PSVIAttributeList (const PSVIAttributeList &) private
PSVIAttributeList() [5/6]
PSVIAttributeList::PSVIAttributeList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
The default constructor
Parameters
manager The configurable memory manager
~PSVIAttributeList() [3/3]
PSVIAttributeList::~PSVIAttributeList ()
PSVIAttributeList() [6/6]
PSVIAttributeList::PSVIAttributeList (const PSVIAttributeList &) private
Member Function Documentation
getAttributeNameAtIndex() [1/3]
const XMLCh* PSVIAttributeList::getAttributeNameAtIndex (const XMLSize_t index)
getAttributeNameAtIndex() [2/3]
const XMLCh* PSVIAttributeList::getAttributeNameAtIndex (const XMLSize_t index)
getAttributeNameAtIndex() [3/3]
const XMLCh* PSVIAttributeList::getAttributeNameAtIndex (const XMLSize_t index)
getAttributeNamespaceAtIndex() [1/3]
const XMLCh* PSVIAttributeList::getAttributeNamespaceAtIndex (const XMLSize_t index)
getAttributeNamespaceAtIndex() [2/3]
const XMLCh* PSVIAttributeList::getAttributeNamespaceAtIndex (const XMLSize_t index)
getAttributeNamespaceAtIndex() [3/3]
const XMLCh* PSVIAttributeList::getAttributeNamespaceAtIndex (const XMLSize_t index)
getAttributePSVIAtIndex() [1/3]
PSVIAttribute* PSVIAttributeList::getAttributePSVIAtIndex (const XMLSize_t index)
getAttributePSVIAtIndex() [2/3]
PSVIAttribute* PSVIAttributeList::getAttributePSVIAtIndex (const XMLSize_t index)
getAttributePSVIAtIndex() [3/3]
PSVIAttribute* PSVIAttributeList::getAttributePSVIAtIndex (const XMLSize_t index)
getAttributePSVIByName() [1/3]
PSVIAttribute* PSVIAttributeList::getAttributePSVIByName (const XMLCh * attrName, const XMLCh * attrNamespace)
getAttributePSVIByName() [2/3]
PSVIAttribute* PSVIAttributeList::getAttributePSVIByName (const XMLCh * attrName, const XMLCh * attrNamespace)
getAttributePSVIByName() [3/3]
PSVIAttribute* PSVIAttributeList::getAttributePSVIByName (const XMLCh * attrName, const XMLCh * attrNamespace)
getLength() [1/3]
XMLSize_t PSVIAttributeList::getLength () const
getLength() [2/3]
XMLSize_t PSVIAttributeList::getLength () const
getLength() [3/3]
XMLSize_t PSVIAttributeList::getLength () const
getPSVIAttributeToFill() [1/3]
PSVIAttribute * PSVIAttributeList::getPSVIAttributeToFill (const XMLCh * attrName, const XMLCh * attrNS) inline
methods needed by implementation returns a PSVI attribute of undetermined state and given name/namespace and makes that object part of the internal list. Intended to be called during validation of an element.
Parameters
attrName name of this attribute
attrNS URI of the attribute
Returns
new, uninitialized, PSVIAttribute object
Definition at line 187 of file PSVIAttributeList.hpp.
References BaseRefVectorOf< TElem >::addElement(), BaseRefVectorOf< TElem >::elementAt(), PSVIAttributeStorage::fAttributeName, PSVIAttributeStorage::fAttributeNamespace, fAttrList, fAttrPos, fMemoryManager, PSVIAttributeStorage::fPSVIAttribute, and BaseRefVectorOf< TElem >::size().
getPSVIAttributeToFill() [2/3]
PSVIAttribute* PSVIAttributeList::getPSVIAttributeToFill (const XMLCh * attrName, const XMLCh * attrNS)
methods needed by implementation returns a PSVI attribute of undetermined state and given name/namespace and makes that object part of the internal list. Intended to be called during validation of an element.
Parameters
attrName name of this attribute
attrNS URI of the attribute
Returns
new, uninitialized, PSVIAttribute object
getPSVIAttributeToFill() [3/3]
PSVIAttribute* PSVIAttributeList::getPSVIAttributeToFill (const XMLCh * attrName, const XMLCh * attrNS)
methods needed by implementation returns a PSVI attribute of undetermined state and given name/namespace and makes that object part of the internal list. Intended to be called during validation of an element.
Parameters
attrName name of this attribute
attrNS URI of the attribute
Returns
new, uninitialized, PSVIAttribute object
operator=() [1/3]
PSVIAttributeList& PSVIAttributeList::operator= (const PSVIAttributeList &) private
operator=() [2/3]
PSVIAttributeList& PSVIAttributeList::operator= (const PSVIAttributeList &) private
operator=() [3/3]
PSVIAttributeList& PSVIAttributeList::operator= (const PSVIAttributeList &) private
reset() [1/3]
void PSVIAttributeList::reset () inline
reset the list
Definition at line 208 of file PSVIAttributeList.hpp.
References fAttrPos.
reset() [2/3]
void PSVIAttributeList::reset ()
reset the list
reset() [3/3]
void PSVIAttributeList::reset ()
reset the list
Member Data Documentation
fAttrList
RefVectorOf< PSVIAttributeStorage > * PSVIAttributeList::fAttrList private
Definition at line 178 of file PSVIAttributeList.hpp.
Referenced by getPSVIAttributeToFill(), and ~PSVIAttributeList().
fAttrPos
XMLSize_t PSVIAttributeList::fAttrPos private
Definition at line 179 of file PSVIAttributeList.hpp.
Referenced by getPSVIAttributeToFill(), and reset().
fMemoryManager
MemoryManager * PSVIAttributeList::fMemoryManager private
Definition at line 177 of file PSVIAttributeList.hpp.
Referenced by getPSVIAttributeToFill().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/psvi/PSVIAttributeList.hpp