Seamly2D: AnchorPointTool Class Reference
AnchorPointTool Class Reference
#include <anchorpoint_tool.h>
Public Slots
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Public Member Functions
virtual QString getTagName () const Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractNode
VAbstractNode (VAbstractPattern *doc, VContainer *data, const quint32 &id, const quint32 &idNode, const QString &blockName=QString(), const quint32 &idTool=0, QObject *parent=nullptr)
VAbstractNode constructor.
virtual ~VAbstractNode () Q_DECL_EQ_DEFAULT
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
virtual void incrementReferens () Q_DECL_OVERRIDE
incrementReferens increment referens.
virtual void decrementReferens () Q_DECL_OVERRIDE
decrementReferens decrement reference for all parent objects.
ParentType GetParentType () const
void SetParentType (const ParentType &value)
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
bool IsExluded () const
void SetExluded (bool exluded)
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
virtual void setPointNamePosition (quint32 id, const QPointF &pos)
virtual void setPointNameVisiblity (quint32 id, bool visible)
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
Static Public Member Functions
static AnchorPointTool * Create (QSharedPointer< DialogTool > dialog, VAbstractPattern *doc, VContainer *data)
static AnchorPointTool * Create (quint32 _id, quint32 pointId, quint32 pieceId, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation, const QString &blockName=QString(), const quint32 &idTool=0)
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString ToolType = QStringLiteral("anchor")
Static Public Attributes inherited from VAbstractNode
static const QString AttrIdTool = QStringLiteral("idTool")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Member Functions
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
virtual void ShowNode () Q_DECL_OVERRIDE
virtual void HideNode () Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractNode
void AddToModeling (const QDomElement &domElement)
AddToModeling add tag to modeling tag current pattern peace.
virtual void ToolCreation (const Source &typeCreation) Q_DECL_OVERRIDE
virtual void SetVisualization () Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void RemoveReferens ()
RemoveReferens decrement value of reference.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
Private Member Functions
AnchorPointTool (VAbstractPattern *doc, VContainer *data, quint32 id, quint32 pointId, quint32 pieceId, const Source &typeCreation, const QString &blockName=QString(), const quint32 &idTool=0, QObject *qoParent=nullptr)
Private Attributes
quint32 m_pieceId
Additional Inherited Members
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VAbstractNode
ParentType parentType
quint32 idNode
idNodenode id.
quint32 idTool
idTool id tool.
QString m_blockName
bool m_exluded
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Detailed Description
Definition at line 62 of file anchorpoint_tool.h.
Constructor & Destructor Documentation
AnchorPointTool()
AnchorPointTool::AnchorPointTool (VAbstractPattern * doc, VContainer * data, quint32 id, quint32 pointId, quint32 pieceId, const Source & typeCreation, const QString & blockName = QString(), const quint32 & idTool = 0, QObject * qoParent = nullptr) private
Definition at line 181 of file anchorpoint_tool.cpp.
References VAbstractNode::ToolCreation().
Referenced by Create().
Member Function Documentation
AddToFile()
void AnchorPointTool::AddToFile () protected virtual
AddToFile add tag with Information about tool into file.
Implements VAbstractTool.
Definition at line 152 of file anchorpoint_tool.cpp.
References VAbstractNode::AddToModeling(), VDomDocument::AttrId, AttrIdObject, VAbstractNode::AttrIdTool, AttrType, VDataTool::data, VAbstractTool::doc, VPiece::getAnchors(), VContainer::GetPiece(), getTagName(), VAbstractNode::idNode, VAbstractNode::idTool, VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, m_pieceId, VUndoCommand::NeedLiteParsing(), NULL_ID, qApp, SavePieceOptions, VDomDocument::SetAttribute(), ToolType, and VContainer::UpdatePiece().
AllowHover
void AnchorPointTool::AllowHover (bool enabled) virtual slot
Definition at line 138 of file anchorpoint_tool.cpp.
AllowSelecting
void AnchorPointTool::AllowSelecting (bool enabled) virtual slot
Definition at line 145 of file anchorpoint_tool.cpp.
Create() [1/2]
AnchorPointTool * AnchorPointTool::Create (QSharedPointer< DialogTool > dialog, VAbstractPattern * doc, VContainer * data) static
Definition at line 62 of file anchorpoint_tool.cpp.
References VDataTool::data, VAbstractTool::doc, FromGui, FullParse, and SCASSERT.
Referenced by QT_WARNING_POP::AddAnchorPoint(), MainWindow::ClosedDialogAnchorPoint(), and VPattern::ParseAnchorPoint().
Create() [2/2]
AnchorPointTool * AnchorPointTool::Create (quint32 _id, quint32 pointId, quint32 pieceId, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation, const QString & blockName = QString(), const quint32 & idTool = 0) static
Definition at line 74 of file anchorpoint_tool.cpp.
References VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), VAbstractPattern::AddToolOnRemove(), AnchorPoint, AnchorPointTool(), VDataTool::data, VAbstractTool::doc, FromGui, FullParse, VContainer::GeometricObject(), VAbstractPattern::getTool(), VAbstractNode::idTool, Modeling, NULL_ID, SCASSERT, VGObject::setMode(), VContainer::UpdateGObject(), VContainer::UpdateId(), and VAbstractPattern::UpdateToolData().
FullUpdateFromFile
virtual void AnchorPointTool::FullUpdateFromFile () inline virtual slot
Definition at line 75 of file anchorpoint_tool.h.
getTagName()
QString AnchorPointTool::getTagName () const virtual
Implements VAbstractTool.
Definition at line 132 of file anchorpoint_tool.cpp.
References VAbstractPattern::TagPoint.
Referenced by AddToFile().
HideNode()
virtual void AnchorPointTool::HideNode () inline protected virtual
Implements VAbstractNode.
Definition at line 82 of file anchorpoint_tool.h.
ShowNode()
virtual void AnchorPointTool::ShowNode () inline protected virtual
Implements VAbstractNode.
Definition at line 81 of file anchorpoint_tool.h.
Member Data Documentation
m_pieceId
quint32 AnchorPointTool::m_pieceId private
Definition at line 87 of file anchorpoint_tool.h.
Referenced by AddToFile().
ToolType
const QString AnchorPointTool::ToolType = QStringLiteral("anchor") static
Definition at line 71 of file anchorpoint_tool.h.
Referenced by AddToFile(), and VPattern::ParsePointElement().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/nodeDetails/anchorpoint_tool.h
src/libs/vtools/tools/nodeDetails/anchorpoint_tool.cpp