Seamly2D: CustomVariable Class Reference
CustomVariable Class Reference
The CustomVariable class keep data row of variables table.
#include <custom_variable.h>
Public Member Functions
CustomVariable ()
CustomVariable create enpty variable.
CustomVariable (VContainer *data, const QString &name, quint32 index, qreal base, const QString &formula, bool ok, const QString &description=QString())
CustomVariableTableRow create variable.
CustomVariable (const CustomVariable &variable)
virtual ~CustomVariable () override
CustomVariable & operator= (const CustomVariable &variable)
void Swap (CustomVariable &variable) Q_DECL_NOTHROW
quint32 getIndex () const
getIndex return index of row
QString GetFormula () const
bool IsFormulaOk () const
VContainer * GetData ()
Public Member Functions inherited from VVariable
VVariable ()
VVariable (const QString &name, const QString &description=QString())
VVariable (const VVariable &var)
virtual ~VVariable () Q_DECL_OVERRIDE
VVariable & operator= (const VVariable &var)
void Swap (VVariable &var) Q_DECL_NOTHROW
QString GetDescription () const
void SetDescription (const QString &desc)
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool Filter (quint32 id)
virtual bool isNotUsed () const
Private Attributes
QSharedDataPointer< CustomVariableData > d
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
The CustomVariable class keep data row of variables table.
Definition at line 68 of file custom_variable.h.
Constructor & Destructor Documentation
CustomVariable() [1/3]
CustomVariable::CustomVariable ()
CustomVariable create enpty variable.
Definition at line 68 of file custom_variable.cpp.
References VInternalVariable::SetType(), and Variable.
CustomVariable() [2/3]
CustomVariable::CustomVariable (VContainer * data, const QString & name, quint32 index, qreal base, const QString & formula, bool ok, const QString & description = QString())
CustomVariableTableRow create variable.
Parameters
name variable's name
base value
description description of variable
Definition at line 82 of file custom_variable.cpp.
References VInternalVariable::SetType(), VInternalVariable::SetValue(), and Variable.
CustomVariable() [3/3]
CustomVariable::CustomVariable (const CustomVariable & variable)
Definition at line 92 of file custom_variable.cpp.
~CustomVariable()
CustomVariable::~CustomVariable () override virtual
Definition at line 110 of file custom_variable.cpp.
Member Function Documentation
GetData()
VContainer * CustomVariable::GetData ()
Definition at line 136 of file custom_variable.cpp.
References d.
GetFormula()
QString CustomVariable::GetFormula () const
Definition at line 124 of file custom_variable.cpp.
References d.
getIndex()
quint32 CustomVariable::getIndex () const
getIndex return index of row
Returns
index
Definition at line 118 of file custom_variable.cpp.
References d.
IsFormulaOk()
bool CustomVariable::IsFormulaOk () const
Definition at line 130 of file custom_variable.cpp.
References d.
operator=()
CustomVariable & CustomVariable::operator= (const CustomVariable & variable)
Definition at line 98 of file custom_variable.cpp.
References d, and VVariable::operator=().
Swap()
void CustomVariable::Swap (CustomVariable & variable)
Definition at line 61 of file custom_variable.cpp.
References VVariable::Swap().
Member Data Documentation
d
QSharedDataPointer<CustomVariableData> CustomVariable::d private
Definition at line 91 of file custom_variable.h.
Referenced by GetData(), GetFormula(), getIndex(), IsFormulaOk(), and operator=().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/custom_variable.h
src/libs/vpatterndb/variables/custom_variable.cpp