Seamly2D: DialogPreferences Class Reference
DialogPreferences Class Reference
#include <dialogpreferences.h>
Signals
void updateProperties ()
Public Member Functions
DialogPreferences (QWidget *parent=nullptr)
virtual ~DialogPreferences ()
Protected Member Functions
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
virtual void resizeEvent (QResizeEvent *event) Q_DECL_OVERRIDE
Private Slots
void pageChanged (QListWidgetItem *current, QListWidgetItem *previous)
Private Member Functions
void Apply ()
void Ok ()
Private Attributes
Ui::DialogPreferences * ui
bool m_isInitialized
PreferencesConfigurationPage * m_configurePage
PreferencesPatternPage * m_patternPage
PreferencesPathPage * m_pathPage
PreferencesGraphicsViewPage * m_graphicsPage
Detailed Description
Definition at line 69 of file dialogpreferences.h.
Constructor & Destructor Documentation
DialogPreferences()
DialogPreferences::DialogPreferences (QWidget * parent = nullptr) explicit
Definition at line 63 of file dialogpreferences.cpp.
References Apply(), m_configurePage, m_graphicsPage, m_pathPage, m_patternPage, Ok(), pageChanged(), qApp, SCASSERT, and ui.
~DialogPreferences()
DialogPreferences::~DialogPreferences () virtual
Definition at line 96 of file dialogpreferences.cpp.
References ui.
Member Function Documentation
Apply()
void DialogPreferences::Apply () private
Definition at line 152 of file dialogpreferences.cpp.
References PreferencesConfigurationPage::Apply(), PreferencesGraphicsViewPage::Apply(), PreferencesPathPage::Apply(), PreferencesPatternPage::Apply(), PreferencesPatternPage::initDefaultSeamAllowance(), m_configurePage, m_graphicsPage, m_pathPage, m_patternPage, qApp, and updateProperties().
Referenced by DialogPreferences(), and Ok().
Ok()
void DialogPreferences::Ok () private
Definition at line 167 of file dialogpreferences.cpp.
References Apply().
Referenced by DialogPreferences().
pageChanged
void DialogPreferences::pageChanged (QListWidgetItem * current, QListWidgetItem * previous) private slot
Definition at line 141 of file dialogpreferences.cpp.
References ui.
Referenced by DialogPreferences().
resizeEvent()
void DialogPreferences::resizeEvent (QResizeEvent * event) protected virtual
Definition at line 128 of file dialogpreferences.cpp.
References m_isInitialized, and qApp.
showEvent()
void DialogPreferences::showEvent (QShowEvent * event) protected virtual
Definition at line 102 of file dialogpreferences.cpp.
References m_isInitialized, and qApp.
updateProperties
void DialogPreferences::updateProperties () signal
Referenced by Apply(), and MainWindow::Preferences().
Member Data Documentation
m_configurePage
PreferencesConfigurationPage* DialogPreferences::m_configurePage private
Definition at line 87 of file dialogpreferences.h.
Referenced by Apply(), and DialogPreferences().
m_graphicsPage
PreferencesGraphicsViewPage* DialogPreferences::m_graphicsPage private
Definition at line 90 of file dialogpreferences.h.
Referenced by Apply(), and DialogPreferences().
m_isInitialized
bool DialogPreferences::m_isInitialized private
Definition at line 86 of file dialogpreferences.h.
Referenced by resizeEvent(), and showEvent().
m_pathPage
PreferencesPathPage* DialogPreferences::m_pathPage private
Definition at line 89 of file dialogpreferences.h.
Referenced by Apply(), and DialogPreferences().
m_patternPage
PreferencesPatternPage* DialogPreferences::m_patternPage private
Definition at line 88 of file dialogpreferences.h.
Referenced by Apply(), and DialogPreferences().
ui
Ui::DialogPreferences* DialogPreferences::ui private
Definition at line 85 of file dialogpreferences.h.
Referenced by DialogPreferences(), pageChanged(), and ~DialogPreferences().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/dialogpreferences.h
src/app/seamly2d/dialogs/dialogpreferences.cpp