Seamly2D: IntersectCirclesVisual Class Reference
IntersectCirclesVisual Class Reference
#include <intersect_circles_visual.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolPointOfIntersectionCircles) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
IntersectCirclesVisual (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~IntersectCirclesVisual ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
virtual void VisualMode (const quint32 &id) Q_DECL_OVERRIDE
void setObject2Id (const quint32 &value)
void setC1Radius (const QString &value)
void setC2Radius (const QString &value)
void setCrossPoint (const CrossCirclesPoint &value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Attributes
quint32 object2Id
qreal c1Radius
qreal c2Radius
CrossCirclesPoint crossPoint
VScaledEllipse * point
VScaledEllipse * c1Center
VScaledEllipse * c2Center
QGraphicsEllipseItem * c1Path
QGraphicsEllipseItem * c2Path
QColor m_secondrySupportColor
QColor m_tertiarySupportColor
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 48 of file intersect_circles_visual.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 65 of file intersect_circles_visual.h.
Constructor & Destructor Documentation
IntersectCirclesVisual()
IntersectCirclesVisual::IntersectCirclesVisual (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 52 of file intersect_circles_visual.cpp.
References c1Center, c1Path, c2Center, c2Path, FirstPoint, Visualization::InitPoint(), m_secondrySupportColor, m_tertiarySupportColor, Visualization::mainColor, point, and Visualization::supportColor.
~IntersectCirclesVisual()
virtual IntersectCirclesVisual::~IntersectCirclesVisual () virtual default
Member Function Documentation
RefreshGeometry()
void IntersectCirclesVisual::RefreshGeometry () virtual
Implements Visualization.
Definition at line 76 of file intersect_circles_visual.cpp.
References c1Center, c1Path, c1Radius, c2Center, c2Path, c2Radius, crossPoint, Visualization::data, Visualization::DrawPoint(), IntersectCirclesTool::FindPoint(), VContainer::GeometricObject(), m_secondrySupportColor, m_tertiarySupportColor, Visualization::mainColor, NULL_ID, Visualization::object1Id, object2Id, point, PointRect(), and Visualization::supportColor.
Referenced by IntersectCirclesDialog::ChosenObject(), IntersectCirclesDialog::SaveData(), IntersectCirclesTool::SetVisualization(), and VisualMode().
setC1Radius()
void IntersectCirclesVisual::setC1Radius (const QString & value)
Definition at line 125 of file intersect_circles_visual.cpp.
References c1Radius, Visualization::data, and Visualization::FindLength().
Referenced by IntersectCirclesDialog::SaveData(), IntersectCirclesDialog::SetFirstCircleRadius(), and IntersectCirclesTool::SetVisualization().
setC2Radius()
void IntersectCirclesVisual::setC2Radius (const QString & value)
Definition at line 131 of file intersect_circles_visual.cpp.
References c2Radius, Visualization::data, and Visualization::FindLength().
Referenced by IntersectCirclesDialog::SaveData(), IntersectCirclesDialog::SetSecondCircleRadius(), and IntersectCirclesTool::SetVisualization().
setCrossPoint()
void IntersectCirclesVisual::setCrossPoint (const CrossCirclesPoint & value)
Definition at line 137 of file intersect_circles_visual.cpp.
References crossPoint.
Referenced by IntersectCirclesDialog::SaveData(), IntersectCirclesDialog::setCirclesCrossPoint(), and IntersectCirclesTool::SetVisualization().
setObject2Id()
void IntersectCirclesVisual::setObject2Id (const quint32 & value)
Definition at line 119 of file intersect_circles_visual.cpp.
References object2Id.
Referenced by IntersectCirclesDialog::ChosenObject(), IntersectCirclesDialog::SaveData(), IntersectCirclesDialog::SetSecondCircleCenterId(), and IntersectCirclesTool::SetVisualization().
type()
virtual int IntersectCirclesVisual::type () const inline virtual
Reimplemented from VisLine.
Definition at line 64 of file intersect_circles_visual.h.
References Type.
VisualMode()
void IntersectCirclesVisual::VisualMode (const quint32 & id) virtual
Reimplemented from Visualization.
Definition at line 106 of file intersect_circles_visual.cpp.
References VisLine::AddOnScene(), VMainGraphicsScene::getScenePos(), Visualization::object1Id, qApp, RefreshGeometry(), SCASSERT, and Visualization::scenePos.
Referenced by IntersectCirclesDialog::ChosenObject().
Member Data Documentation
c1Center
VScaledEllipse* IntersectCirclesVisual::c1Center private
Definition at line 75 of file intersect_circles_visual.h.
Referenced by IntersectCirclesVisual(), and RefreshGeometry().
c1Path
QGraphicsEllipseItem* IntersectCirclesVisual::c1Path private
Definition at line 77 of file intersect_circles_visual.h.
Referenced by IntersectCirclesVisual(), and RefreshGeometry().
c1Radius
qreal IntersectCirclesVisual::c1Radius private
Definition at line 71 of file intersect_circles_visual.h.
Referenced by RefreshGeometry(), and setC1Radius().
c2Center
VScaledEllipse* IntersectCirclesVisual::c2Center private
Definition at line 76 of file intersect_circles_visual.h.
Referenced by IntersectCirclesVisual(), and RefreshGeometry().
c2Path
QGraphicsEllipseItem* IntersectCirclesVisual::c2Path private
Definition at line 78 of file intersect_circles_visual.h.
Referenced by IntersectCirclesVisual(), and RefreshGeometry().
c2Radius
qreal IntersectCirclesVisual::c2Radius private
Definition at line 72 of file intersect_circles_visual.h.
Referenced by RefreshGeometry(), and setC2Radius().
crossPoint
CrossCirclesPoint IntersectCirclesVisual::crossPoint private
Definition at line 73 of file intersect_circles_visual.h.
Referenced by RefreshGeometry(), and setCrossPoint().
m_secondrySupportColor
QColor IntersectCirclesVisual::m_secondrySupportColor private
Definition at line 79 of file intersect_circles_visual.h.
Referenced by IntersectCirclesVisual(), and RefreshGeometry().
m_tertiarySupportColor
QColor IntersectCirclesVisual::m_tertiarySupportColor private
Definition at line 80 of file intersect_circles_visual.h.
Referenced by IntersectCirclesVisual(), and RefreshGeometry().
object2Id
quint32 IntersectCirclesVisual::object2Id private
Definition at line 70 of file intersect_circles_visual.h.
Referenced by RefreshGeometry(), and setObject2Id().
point
VScaledEllipse* IntersectCirclesVisual::point private
Definition at line 74 of file intersect_circles_visual.h.
Referenced by IntersectCirclesVisual(), and RefreshGeometry().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/intersect_circles_visual.h
src/libs/vtools/visualization/line/intersect_circles_visual.cpp