Seamly2D: VScaledEllipse Class Reference
VScaledEllipse Class Reference
#include <scalesceneitems.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ScaledEllipse) }
Public Member Functions
VScaledEllipse (QGraphicsItem *parent=nullptr)
virtual ~VScaledEllipse ()=default
virtual int type () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
Detailed Description
Definition at line 103 of file scalesceneitems.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 110 of file scalesceneitems.h.
Constructor & Destructor Documentation
VScaledEllipse()
VScaledEllipse::VScaledEllipse (QGraphicsItem * parent = nullptr) explicit
Definition at line 162 of file scalesceneitems.cpp.
~VScaledEllipse()
virtual VScaledEllipse::~VScaledEllipse () virtual default
Member Function Documentation
paint()
void VScaledEllipse::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) virtual
Definition at line 167 of file scalesceneitems.cpp.
References scaleCircleSize(), scaleWidth(), sceneScale(), and widthMainLine.
type()
virtual int VScaledEllipse::type () const inline virtual
Definition at line 109 of file scalesceneitems.h.
References VScaledLine::Type.
The documentation for this class was generated from the following files:
src/libs/vwidgets/scalesceneitems.h
src/libs/vwidgets/scalesceneitems.cpp