Seamly2D: VPE::VPropertyFactoryManager Class Reference
VPE::VPropertyFactoryManager Class Reference
#include <vpropertyfactorymanager.h>
Public Member Functions
VPropertyFactoryManager (QObject *parent=nullptr)
Constructor.
virtual ~VPropertyFactoryManager () Q_DECL_OVERRIDE
Destructor.
void registerFactory (const QString &type, VAbstractPropertyFactory *factory)
Register a factory to the factory manager Note that the manager takes ownership of the factory, so don't delete it. You can unregister a factory using unregisterFactory()
void unregisterFactory (VAbstractPropertyFactory *factory, const QString &type=QString(), bool delete_if_unused=true)
Removes a factory from the manager.
bool isRegistered (VAbstractPropertyFactory *factory)
Returns whether a factory is registered (and thus owned) by this factory manager.
VAbstractPropertyFactory * getFactory (const QString &type)
Returns a pointer to a factory registered for a certain type.
VProperty * createProperty (const QString &type, const QString &name, const QString &description=QString(), const QString &default_value=QString())
Creates a new property of a certain type and assigns a name and description (otionally)
QStringList getSupportedTypes ()
Returns the default manager.
Protected Attributes
VPropertyFactoryManagerPrivate * d_ptr
Static Protected Attributes
static VPropertyFactoryManager * DefaultManager = NULL
The default manager.
Detailed Description
Definition at line 37 of file vpropertyfactorymanager.h.
Constructor & Destructor Documentation
VPropertyFactoryManager()
VPE::VPropertyFactoryManager::VPropertyFactoryManager (QObject * parent = nullptr) explicit
Constructor.
Definition at line 35 of file vpropertyfactorymanager.cpp.
~VPropertyFactoryManager()
VPE::VPropertyFactoryManager::~VPropertyFactoryManager () virtual
Destructor.
Definition at line 41 of file vpropertyfactorymanager.cpp.
Member Function Documentation
createProperty()
VPE::VProperty * VPE::VPropertyFactoryManager::createProperty (const QString & type, const QString & name, const QString & description = QString(), const QString & default_value = QString())
Creates a new property of a certain type and assigns a name and description (otionally)
Parameters
type The type of the property as string
name The name of the property
description The property's description. Optional.
default_value The properties initial value as string. Optional.
Returns
Returns the created property or NULL if it couldn't be be created
Definition at line 120 of file vpropertyfactorymanager.cpp.
References VPE::VAbstractPropertyFactory::createProperty(), VPE::VProperty::deserialize(), and VPE::VProperty::setDescription().
getFactory()
VPE::VAbstractPropertyFactory * VPE::VPropertyFactoryManager::getFactory (const QString & type)
Returns a pointer to a factory registered for a certain type.
Parameters
type The type to return the factory for
Returns
Returns NULL, if there is none registered for this type
Definition at line 114 of file vpropertyfactorymanager.cpp.
getSupportedTypes()
QStringList VPE::VPropertyFactoryManager::getSupportedTypes ()
Returns the default manager.
Returns a list of all supported property types
Definition at line 156 of file vpropertyfactorymanager.cpp.
isRegistered()
bool VPE::VPropertyFactoryManager::isRegistered (VAbstractPropertyFactory * factory)
Returns whether a factory is registered (and thus owned) by this factory manager.
Definition at line 109 of file vpropertyfactorymanager.cpp.
registerFactory()
void VPE::VPropertyFactoryManager::registerFactory (const QString & type, VAbstractPropertyFactory * factory)
Register a factory to the factory manager Note that the manager takes ownership of the factory, so don't delete it. You can unregister a factory using unregisterFactory()
Definition at line 60 of file vpropertyfactorymanager.cpp.
Referenced by VPE::VStandardPropertyFactory::VStandardPropertyFactory().
unregisterFactory()
void VPE::VPropertyFactoryManager::unregisterFactory (VAbstractPropertyFactory * factory, const QString & type = QString(), bool delete_if_unused = true)
Removes a factory from the manager.
Parameters
factory The factory to unregister
type The type from which to remove the factory. If this is empty, all the types the factory is registered for are being removed
delete_if_unused Determines whether the factory should be deleted, if it not used anymore by this manager. Default: true. Otherwise, if the factory is unused by this manager, ownership is being passed on.
Definition at line 73 of file vpropertyfactorymanager.cpp.
Member Data Documentation
d_ptr
VPropertyFactoryManagerPrivate* VPE::VPropertyFactoryManager::d_ptr protected
Definition at line 85 of file vpropertyfactorymanager.h.
DefaultManager
VPE::VPropertyFactoryManager * VPE::VPropertyFactoryManager::DefaultManager = NULL static protected
The default manager.
Definition at line 88 of file vpropertyfactorymanager.h.
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/vpropertyfactorymanager.h
src/libs/vpropertyexplorer/vpropertyfactorymanager.cpp