Seamly2D: TST_VAbstractPiece Class Reference
TST_VAbstractPiece Class Reference
#include <tst_vabstractpiece.h>
Public Member Functions
TST_VAbstractPiece (QObject *parent=nullptr)
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Private Slots
void EquidistantRemoveLoop_data ()
void EquidistantRemoveLoop () const
void sumTrapezoids () const
void PathRemoveLoop_data () const
void PathRemoveLoop () const
void PathLoopsCase_data () const
void PathLoopsCase () const
void BrokenDetailEquidistant_data () const
void BrokenDetailEquidistant () const
void CorrectEquidistantPoints_data () const
void CorrectEquidistantPoints () const
void TestCorrectEquidistantPoints_data ()
void TestCorrectEquidistantPoints () const
void PossibleInfiniteClearLoops_data () const
void PossibleInfiniteClearLoops () const
Private Member Functions
QVector< VSAPoint > InputPointsCase1 () const
QVector< QPointF > OutputPointsCase1 () const
QVector< VSAPoint > InputPointsCase2 () const
QVector< QPointF > OutputPointsCase2 () const
QVector< VSAPoint > InputPointsCase3 () const
QVector< QPointF > OutputPointsCase3 () const
void Case3 () const
void Case4 () const
void Case5 () const
QVector< VSAPoint > InputPointsIssue298Case1 () const
QVector< QPointF > OutputPointsIssue298Case1 () const
QVector< VSAPoint > InputPointsIssue298Case2 () const
QVector< QPointF > OutputPointsIssue298Case2 () const
QVector< VSAPoint > InputPointsIssue548Case1 () const
QVector< QPointF > OutputPointsIssue548Case1 () const
QVector< VSAPoint > InputPointsIssue548Case2 () const
QVector< QPointF > OutputPointsIssue548Case2 () const
QVector< VSAPoint > InputPointsIssue548Case3 () const
QVector< QPointF > OutputPointsIssue548Case3 () const
QVector< QPointF > InputPointsCase3a () const
QVector< QPointF > InputPointsCase4a () const
QVector< QPointF > InputPointsCase5a () const
QVector< VSAPoint > InputPointsIssue646 () const
QVector< QPointF > OutputPointsIssue646 () const
Additional Inherited Members
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Detailed Description
Definition at line 59 of file tst_vabstractpiece.h.
Constructor & Destructor Documentation
TST_VAbstractPiece()
TST_VAbstractPiece::TST_VAbstractPiece (QObject * parent = nullptr) explicit
Definition at line 61 of file tst_vabstractpiece.cpp.
Member Function Documentation
BrokenDetailEquidistant
void TST_VAbstractPiece::BrokenDetailEquidistant () const private slot
Definition at line 2694 of file tst_vabstractpiece.cpp.
References AbstractTest::Comparison(), and VAbstractPiece::Equidistant().
BrokenDetailEquidistant_data
void TST_VAbstractPiece::BrokenDetailEquidistant_data () const private slot
Definition at line 2411 of file tst_vabstractpiece.cpp.
References VSAPoint::SetSAAfter(), and VSAPoint::SetSABefore().
Case3()
void TST_VAbstractPiece::Case3 () const private
Definition at line 3117 of file tst_vabstractpiece.cpp.
References InputPointsCase3a(), and VAbstractPiece::sumTrapezoids().
Referenced by sumTrapezoids().
Case4()
void TST_VAbstractPiece::Case4 () const private
Definition at line 3126 of file tst_vabstractpiece.cpp.
References InputPointsCase4a(), and VAbstractPiece::sumTrapezoids().
Referenced by sumTrapezoids().
Case5()
void TST_VAbstractPiece::Case5 () const private
Definition at line 3135 of file tst_vabstractpiece.cpp.
References InputPointsCase5a(), and VAbstractPiece::sumTrapezoids().
Referenced by sumTrapezoids().
CorrectEquidistantPoints
void TST_VAbstractPiece::CorrectEquidistantPoints () const private slot
Definition at line 2784 of file tst_vabstractpiece.cpp.
References AbstractTest::Comparison(), and VAbstractPiece::CorrectEquidistantPoints().
CorrectEquidistantPoints_data
void TST_VAbstractPiece::CorrectEquidistantPoints_data () const private slot
Definition at line 2707 of file tst_vabstractpiece.cpp.
EquidistantRemoveLoop
void TST_VAbstractPiece::EquidistantRemoveLoop () const private slot
Definition at line 122 of file tst_vabstractpiece.cpp.
References AbstractTest::Comparison(), and VAbstractPiece::Equidistant().
EquidistantRemoveLoop_data
void TST_VAbstractPiece::EquidistantRemoveLoop_data () private slot
Definition at line 66 of file tst_vabstractpiece.cpp.
References InputPointsCase1(), InputPointsCase2(), InputPointsCase3(), InputPointsIssue298Case1(), InputPointsIssue298Case2(), InputPointsIssue548Case1(), InputPointsIssue548Case2(), InputPointsIssue548Case3(), InputPointsIssue646(), OutputPointsCase1(), OutputPointsCase2(), OutputPointsCase3(), OutputPointsIssue298Case1(), OutputPointsIssue298Case2(), OutputPointsIssue548Case1(), OutputPointsIssue548Case2(), OutputPointsIssue548Case3(), and OutputPointsIssue646().
InputPointsCase1()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsCase1 () const private
Definition at line 135 of file tst_vabstractpiece.cpp.
References VSAPoint::SetSAAfter(), and VSAPoint::SetSABefore().
Referenced by EquidistantRemoveLoop_data().
InputPointsCase2()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsCase2 () const private
Definition at line 659 of file tst_vabstractpiece.cpp.
References VSAPoint::SetSAAfter(), and VSAPoint::SetSABefore().
Referenced by EquidistantRemoveLoop_data().
InputPointsCase3()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsCase3 () const private
Definition at line 1092 of file tst_vabstractpiece.cpp.
References VSAPoint::SetSAAfter(), and VSAPoint::SetSABefore().
Referenced by EquidistantRemoveLoop_data().
InputPointsCase3a()
QVector< QPointF > TST_VAbstractPiece::InputPointsCase3a () const private
Definition at line 3480 of file tst_vabstractpiece.cpp.
Referenced by Case3().
InputPointsCase4a()
QVector< QPointF > TST_VAbstractPiece::InputPointsCase4a () const private
Definition at line 3492 of file tst_vabstractpiece.cpp.
Referenced by Case4().
InputPointsCase5a()
QVector< QPointF > TST_VAbstractPiece::InputPointsCase5a () const private
Definition at line 3504 of file tst_vabstractpiece.cpp.
Referenced by Case5().
InputPointsIssue298Case1()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsIssue298Case1 () const private
Definition at line 3144 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
InputPointsIssue298Case2()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsIssue298Case2 () const private
Definition at line 3261 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
InputPointsIssue548Case1()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsIssue548Case1 () const private
Definition at line 3390 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
InputPointsIssue548Case2()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsIssue548Case2 () const private
Definition at line 3422 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
InputPointsIssue548Case3()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsIssue548Case3 () const private
Definition at line 3450 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
InputPointsIssue646()
QVector< VSAPoint > TST_VAbstractPiece::InputPointsIssue646 () const private
Definition at line 3514 of file tst_vabstractpiece.cpp.
References VSAPoint::SetSAAfter(), and VSAPoint::SetSABefore().
Referenced by EquidistantRemoveLoop_data().
OutputPointsCase1()
QVector< QPointF > TST_VAbstractPiece::OutputPointsCase1 () const private
Definition at line 569 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
OutputPointsCase2()
QVector< QPointF > TST_VAbstractPiece::OutputPointsCase2 () const private
Definition at line 1028 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
OutputPointsCase3()
QVector< QPointF > TST_VAbstractPiece::OutputPointsCase3 () const private
Definition at line 1765 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
OutputPointsIssue298Case1()
QVector< QPointF > TST_VAbstractPiece::OutputPointsIssue298Case1 () const private
Definition at line 3218 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
OutputPointsIssue298Case2()
QVector< QPointF > TST_VAbstractPiece::OutputPointsIssue298Case2 () const private
Definition at line 3335 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
OutputPointsIssue548Case1()
QVector< QPointF > TST_VAbstractPiece::OutputPointsIssue548Case1 () const private
Definition at line 3405 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
OutputPointsIssue548Case2()
QVector< QPointF > TST_VAbstractPiece::OutputPointsIssue548Case2 () const private
Definition at line 3436 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
OutputPointsIssue548Case3()
QVector< QPointF > TST_VAbstractPiece::OutputPointsIssue548Case3 () const private
Definition at line 3465 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
OutputPointsIssue646()
QVector< QPointF > TST_VAbstractPiece::OutputPointsIssue646 () const private
Definition at line 3983 of file tst_vabstractpiece.cpp.
Referenced by EquidistantRemoveLoop_data().
PathLoopsCase
void TST_VAbstractPiece::PathLoopsCase () const private slot
Definition at line 2401 of file tst_vabstractpiece.cpp.
References VAbstractPiece::CheckLoops(), and AbstractTest::Comparison().
PathLoopsCase_data
void TST_VAbstractPiece::PathLoopsCase_data () const private slot
Definition at line 2199 of file tst_vabstractpiece.cpp.
PathRemoveLoop
void TST_VAbstractPiece::PathRemoveLoop () const private slot
Definition at line 2189 of file tst_vabstractpiece.cpp.
References VAbstractPiece::CheckLoops(), and AbstractTest::Comparison().
PathRemoveLoop_data
void TST_VAbstractPiece::PathRemoveLoop_data () const private slot
Definition at line 1881 of file tst_vabstractpiece.cpp.
PossibleInfiniteClearLoops
void TST_VAbstractPiece::PossibleInfiniteClearLoops () const private slot
Definition at line 3106 of file tst_vabstractpiece.cpp.
References VAbstractPiece::CheckLoops(), and AbstractTest::Comparison().
PossibleInfiniteClearLoops_data
void TST_VAbstractPiece::PossibleInfiniteClearLoops_data () const private slot
Definition at line 2974 of file tst_vabstractpiece.cpp.
sumTrapezoids
void TST_VAbstractPiece::sumTrapezoids () const private slot
Definition at line 1870 of file tst_vabstractpiece.cpp.
References Case3(), Case4(), and Case5().
TestCorrectEquidistantPoints
void TST_VAbstractPiece::TestCorrectEquidistantPoints () const private slot
Definition at line 2963 of file tst_vabstractpiece.cpp.
References AbstractTest::Comparison(), and VAbstractPiece::CorrectEquidistantPoints().
TestCorrectEquidistantPoints_data
void TST_VAbstractPiece::TestCorrectEquidistantPoints_data () private slot
Definition at line 2797 of file tst_vabstractpiece.cpp.
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vabstractpiece.h
src/test/Seamly2DTest/tst_vabstractpiece.cpp