Seamly2D: DialogCurveIntersectAxis Class Reference
DialogCurveIntersectAxis Class Reference
#include <dialogcurveintersectaxis.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
void EvalAngle ()
void AngleTextChanged ()
void DeployAngleTextEdit ()
void FXAngle ()
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogCurveIntersectAxis (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
virtual ~DialogCurveIntersectAxis () Q_DECL_OVERRIDE
void SetPointName (const QString &value)
QString getLineColor () const
getLineColor get the color of line
void setLineColor (const QString &value)
QString getLineType () const
void setLineType (const QString &value)
QString getLineWeight () const
getLineWeight return weight of the lines
void setLineWeight (const QString &value)
setLineWeight set weight of the lines
QString GetFormula () const
void SetFormula (const QString &value)
QString GetAngle () const
void SetAngle (const QString &value)
quint32 GetBasePointId () const
void SetBasePointId (const quint32 &value)
quint32 getCurveId () const
void setCurveId (const quint32 &value)
virtual void ShowDialog (bool click) Q_DECL_OVERRIDE
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
virtual void CheckState ()
CheckState enable, when all is correct, or disable, when something wrong, button ok.
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Attributes
Ui::DialogCurveIntersectAxis * ui
QString formulaAngle
int formulaBaseHeightAngle
bool m_firstRelease
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
Definition at line 69 of file dialogcurveintersectaxis.h.
Constructor & Destructor Documentation
DialogCurveIntersectAxis()
DialogCurveIntersectAxis::DialogCurveIntersectAxis (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
Definition at line 80 of file dialogcurveintersectaxis.cpp.
References AngleTextChanged(), DialogTool::CheckState(), DialogTool::data, DeployAngleTextEdit(), EvalAngle(), DialogTool::FillComboBoxCurves(), DialogTool::FillComboBoxPoints(), DialogTool::flagFormula, formulaBaseHeightAngle, FXAngle(), DialogTool::initializeFormulaUi(), DialogTool::initializeOkCancelApply(), DialogTool::labelEditNamePoint, DialogTool::NamePointChanged(), NewLabel, DialogTool::plainTextEditFormula, qApp, DialogTool::timerFormula, ui, and DialogTool::vis.
~DialogCurveIntersectAxis()
DialogCurveIntersectAxis::~DialogCurveIntersectAxis () virtual
Definition at line 134 of file dialogcurveintersectaxis.cpp.
References ui.
Member Function Documentation
AngleTextChanged
void DialogCurveIntersectAxis::AngleTextChanged () slot
Definition at line 345 of file dialogcurveintersectaxis.cpp.
References degreeSymbol, DialogTool::flagError, DialogTool::plainTextEditFormula, DialogTool::timerFormula, and DialogTool::ValFormulaChanged().
Referenced by DialogCurveIntersectAxis().
ChosenObject
void DialogCurveIntersectAxis::ChosenObject (quint32 id, const SceneObject & type) virtual slot
Definition at line 295 of file dialogcurveintersectaxis.cpp.
References Arc, ElArc, DialogTool::number, Point, DialogTool::prepare, qApp, VisToolCurveIntersectAxis::RefreshGeometry(), SCASSERT, VisToolCurveIntersectAxis::setAxisPointId(), DialogTool::SetObject(), VAbstractMainWindow::ShowToolTip(), Spline, SplinePath, Visualization::ToolTip(), ui, DialogTool::vis, and Visualization::VisualMode().
closeEvent()
void DialogCurveIntersectAxis::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 396 of file dialogcurveintersectaxis.cpp.
References DialogTool::closeEvent(), and DialogTool::plainTextEditFormula.
DeployAngleTextEdit
void DialogCurveIntersectAxis::DeployAngleTextEdit () slot
Definition at line 351 of file dialogcurveintersectaxis.cpp.
References DialogTool::DeployFormula(), formulaBaseHeightAngle, DialogTool::plainTextEditFormula, and ui.
Referenced by DialogCurveIntersectAxis(), and SetAngle().
EvalAngle
void DialogCurveIntersectAxis::EvalAngle () slot
Definition at line 339 of file dialogcurveintersectaxis.cpp.
References degreeSymbol, DialogTool::Eval(), DialogTool::flagError, and ui.
Referenced by DialogCurveIntersectAxis().
FXAngle
void DialogCurveIntersectAxis::FXAngle () slot
Definition at line 357 of file dialogcurveintersectaxis.cpp.
References DialogTool::data, degreeSymbol, GetAngle(), EditFormulaDialog::GetFormula(), SetAngle(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), and DialogTool::toolId.
Referenced by DialogCurveIntersectAxis().
GetAngle()
QString DialogCurveIntersectAxis::GetAngle () const
Definition at line 181 of file dialogcurveintersectaxis.cpp.
References formulaAngle, and qApp.
Referenced by FXAngle().
GetBasePointId()
quint32 DialogCurveIntersectAxis::GetBasePointId () const
Definition at line 206 of file dialogcurveintersectaxis.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData(), and ShowDialog().
getCurveId()
quint32 DialogCurveIntersectAxis::getCurveId () const
Definition at line 222 of file dialogcurveintersectaxis.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
GetFormula()
QString DialogCurveIntersectAxis::GetFormula () const
getLineColor()
QString DialogCurveIntersectAxis::getLineColor () const
getLineColor get the color of line
Parameters
value type
Definition at line 242 of file dialogcurveintersectaxis.cpp.
References ColorBlack, DialogTool::GetComboBoxCurrentData(), and ui.
getLineType()
QString DialogCurveIntersectAxis::getLineType () const
Definition at line 147 of file dialogcurveintersectaxis.cpp.
References DialogTool::GetComboBoxCurrentData(), LineTypeSolidLine, and ui.
Referenced by SaveData().
getLineWeight()
QString DialogCurveIntersectAxis::getLineWeight () const
getLineWeight return weight of the lines
Returns
type
Definition at line 164 of file dialogcurveintersectaxis.cpp.
References DialogTool::GetComboBoxCurrentData(), and ui.
Referenced by SaveData().
SaveData()
void DialogCurveIntersectAxis::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 377 of file dialogcurveintersectaxis.cpp.
References formulaAngle, GetBasePointId(), getCurveId(), getLineType(), getLineWeight(), lineTypeToPenStyle(), DialogTool::plainTextEditFormula, DialogTool::pointName, VisToolCurveIntersectAxis::RefreshGeometry(), SCASSERT, VisToolCurveIntersectAxis::SetAngle(), VisToolCurveIntersectAxis::setAxisPointId(), Visualization::setLineStyle(), Visualization::setLineWeight(), Visualization::setObject1Id(), ui, and DialogTool::vis.
SetAngle()
void DialogCurveIntersectAxis::SetAngle (const QString & value)
Definition at line 187 of file dialogcurveintersectaxis.cpp.
References DeployAngleTextEdit(), formulaAngle, DialogTool::MoveCursorToEnd(), DialogTool::plainTextEditFormula, qApp, SCASSERT, VisToolCurveIntersectAxis::SetAngle(), and DialogTool::vis.
Referenced by FXAngle(), and ShowDialog().
SetBasePointId()
void DialogCurveIntersectAxis::SetBasePointId (const quint32 & value)
Definition at line 212 of file dialogcurveintersectaxis.cpp.
References SCASSERT, VisToolCurveIntersectAxis::setAxisPointId(), DialogTool::setCurrentPointId(), ui, and DialogTool::vis.
setCurveId()
void DialogCurveIntersectAxis::setCurveId (const quint32 & value)
Definition at line 228 of file dialogcurveintersectaxis.cpp.
References SCASSERT, DialogTool::setCurrentCurveId(), Visualization::setObject1Id(), ui, and DialogTool::vis.
SetFormula()
void DialogCurveIntersectAxis::SetFormula (const QString & value)
setLineColor()
void DialogCurveIntersectAxis::setLineColor (const QString & value)
Definition at line 251 of file dialogcurveintersectaxis.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setLineType()
void DialogCurveIntersectAxis::setLineType (const QString & value)
Definition at line 153 of file dialogcurveintersectaxis.cpp.
References DialogTool::ChangeCurrentData(), lineTypeToPenStyle(), ui, and DialogTool::vis.
setLineWeight()
void DialogCurveIntersectAxis::setLineWeight (const QString & value)
setLineWeight set weight of the lines
Parameters
value type
Definition at line 174 of file dialogcurveintersectaxis.cpp.
References DialogTool::ChangeCurrentData(), ui, and DialogTool::vis.
SetPointName()
void DialogCurveIntersectAxis::SetPointName (const QString & value)
Definition at line 140 of file dialogcurveintersectaxis.cpp.
References DialogTool::pointName, and ui.
ShowDialog()
void DialogCurveIntersectAxis::ShowDialog (bool click) virtual
Reimplemented from DialogTool.
Definition at line 257 of file dialogcurveintersectaxis.cpp.
References VisToolCurveIntersectAxis::Angle(), DialogTool::data, defPointRadiusPixel, DialogTool::DialogAccepted(), VContainer::GeometricObject(), GetBasePointId(), VMainGraphicsScene::getScenePos(), m_firstRelease, DialogTool::prepare, qApp, SCASSERT, SetAngle(), DialogTool::ToolTip(), and DialogTool::vis.
ShowVisualization()
void DialogCurveIntersectAxis::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 371 of file dialogcurveintersectaxis.cpp.
Member Data Documentation
formulaAngle
QString DialogCurveIntersectAxis::formulaAngle private
Definition at line 121 of file dialogcurveintersectaxis.h.
Referenced by GetAngle(), SaveData(), and SetAngle().
formulaBaseHeightAngle
int DialogCurveIntersectAxis::formulaBaseHeightAngle private
Definition at line 122 of file dialogcurveintersectaxis.h.
Referenced by DeployAngleTextEdit(), and DialogCurveIntersectAxis().
m_firstRelease
bool DialogCurveIntersectAxis::m_firstRelease private
Definition at line 124 of file dialogcurveintersectaxis.h.
Referenced by ShowDialog().
ui
Ui::DialogCurveIntersectAxis* DialogCurveIntersectAxis::ui private
Definition at line 119 of file dialogcurveintersectaxis.h.
Referenced by ChosenObject(), DeployAngleTextEdit(), DialogCurveIntersectAxis(), EvalAngle(), GetBasePointId(), getCurveId(), getLineColor(), getLineType(), getLineWeight(), SaveData(), SetBasePointId(), setCurveId(), setLineColor(), setLineType(), setLineWeight(), SetPointName(), and ~DialogCurveIntersectAxis().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogcurveintersectaxis.h
src/libs/vtools/dialogs/tools/dialogcurveintersectaxis.cpp