Seamly2D: DeleteDraftBlock Class Reference
DeleteDraftBlock Class Reference
#include <delete_draftblock.h>
Public Member Functions
DeleteDraftBlock (VAbstractPattern *doc, const QString &draftBlockName, QUndoCommand *parent=nullptr)
virtual ~DeleteDraftBlock () Q_DECL_OVERRIDE
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Attributes
QString draftBlockName
QDomElement draftBlock
QString previousDraftBlockName
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 65 of file delete_draftblock.h.
Constructor & Destructor Documentation
DeleteDraftBlock()
DeleteDraftBlock::DeleteDraftBlock (VAbstractPattern * doc, const QString & draftBlockName, QUndoCommand * parent = nullptr)
Definition at line 63 of file delete_draftblock.cpp.
References VAbstractPattern::AttrName, VUndoCommand::doc, draftBlock, draftBlockName, VAbstractPattern::getDraftBlockElement(), VDomDocument::GetParametrString(), previousDraftBlockName, and VAbstractPattern::TagDraftBlock.
~DeleteDraftBlock()
DeleteDraftBlock::~DeleteDraftBlock () virtual
Definition at line 81 of file delete_draftblock.cpp.
Member Function Documentation
redo()
void DeleteDraftBlock::redo () virtual
Definition at line 115 of file delete_draftblock.cpp.
References VUndoCommand::doc, draftBlock, draftBlockName, VAbstractPattern::getDraftBlockElement(), and VUndoCommand::NeedFullParsing().
undo()
void DeleteDraftBlock::undo () virtual
Definition at line 85 of file delete_draftblock.cpp.
References VAbstractPattern::changeActiveDraftBlock(), VUndoCommand::doc, draftBlock, draftBlockName, VAbstractPattern::getDraftBlockElement(), VUndoCommand::NeedFullParsing(), previousDraftBlockName, and VAbstractPattern::TagDraftBlock.
Member Data Documentation
draftBlock
QDomElement DeleteDraftBlock::draftBlock private
Definition at line 78 of file delete_draftblock.h.
Referenced by DeleteDraftBlock(), redo(), and undo().
draftBlockName
QString DeleteDraftBlock::draftBlockName private
Definition at line 77 of file delete_draftblock.h.
Referenced by DeleteDraftBlock(), redo(), and undo().
previousDraftBlockName
QString DeleteDraftBlock::previousDraftBlockName private
Definition at line 79 of file delete_draftblock.h.
Referenced by DeleteDraftBlock(), and undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/delete_draftblock.h
src/libs/vtools/undocommands/delete_draftblock.cpp