Seamly2D: src/libs/vwidgets/global.cpp File Reference
global.cpp File Reference
#include "global.h"
#include "../vmisc/def.h"
#include <QGraphicsItem>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QtDebug>
Functions
qreal sceneScale (QGraphicsScene *scene)
QColor correctColor (const QGraphicsItem *item, const QColor &color)
QRectF pointRect (qreal radius)
qreal scaledRadius (qreal scale)
void scaleCircleSize (QGraphicsEllipseItem *item, qreal scale)
void scaleRectSize (QGraphicsRectItem *item, qreal scale)
qreal scaleWidth (qreal width, qreal scale)
QPainterPath itemShapeFromPath (const QPainterPath &path, const QPen &pen)
Variables
const qreal defPointRadiusPixel = (2. / 25.4) * PrintDPI
const qreal widthMainLine = (1.2 / 25.4) * PrintDPI
const qreal widthHairLine = widthMainLine/3.0
Function Documentation
correctColor()
QColor correctColor (const QGraphicsItem * item, const QColor & color)
Definition at line 80 of file global.cpp.
References SCASSERT.
Referenced by VGraphicsSimpleTextItem::getTextBrushColor(), VAbstractSpline::paint(), DoubleLinePointTool::paint(), VToolLinePoint::paint(), VToolLine::paint(), VControlPointSpline::paint(), VSimpleCurve::ScalePenWidth(), and VScenePoint::setPointPen().
itemShapeFromPath()
QPainterPath itemShapeFromPath (const QPainterPath & path, const QPen & pen)
Definition at line 147 of file global.cpp.
Referenced by VAbstractSpline::shape(), PatternPieceTool::shape(), and VCurvePathItem::shape().
pointRect()
QRectF pointRect (qreal radius)
Definition at line 96 of file global.cpp.
Referenced by Visualization::initPointItem(), IntersectCirclesVisual::RefreshGeometry(), IntersectCircleTangentVisual::RefreshGeometry(), VisToolPointOfContact::RefreshGeometry(), VScenePoint::refreshLeader(), scaleCircleSize(), and scaleRectSize().
scaleCircleSize()
void scaleCircleSize (QGraphicsEllipseItem * item, qreal scale)
Definition at line 116 of file global.cpp.
References pointRect(), scaledRadius(), and SCASSERT.
Referenced by VScaledEllipse::paint().
scaledRadius()
qreal scaledRadius (qreal scale)
Definition at line 104 of file global.cpp.
References defPointRadiusPixel.
Referenced by VControlPointSpline::paint(), VisToolMove::RefreshGeometry(), VScenePoint::refreshLeader(), scaleCircleSize(), scaleRectSize(), VControlPointSpline::setCtrlLine(), and DialogRotation::ShowDialog().
scaleRectSize()
void scaleRectSize (QGraphicsRectItem * item, qreal scale)
Definition at line 124 of file global.cpp.
References pointRect(), scaledRadius(), and SCASSERT.
Referenced by SceneRect::paint().
scaleWidth()
qreal scaleWidth (qreal width, qreal scale)
Definition at line 132 of file global.cpp.
Referenced by PatternPieceTool::InitInternalPaths(), VAbstractSpline::paint(), PatternPieceTool::paint(), VToolLine::paint(), VToolInternalPath::paint(), VScaledLine::paint(), ArrowedLineItem::paint(), VScaledEllipse::paint(), VCurvePathItem::paint(), VCurvePathItem::ScalePenWidth(), VSimpleCurve::ScalePenWidth(), VScenePoint::setPointPen(), SceneRect::setRectPen(), VAbstractSpline::shape(), and VCurvePathItem::shape().
sceneScale()
qreal sceneScale (QGraphicsScene * scene)
Definition at line 63 of file global.cpp.
Referenced by PatternPieceTool::InitInternalPaths(), PatternPieceTool::itemChange(), VGraphicsSimpleTextItem::itemChange(), VAbstractSpline::paint(), PatternPieceTool::paint(), VToolLine::paint(), VToolInternalPath::paint(), VScaledLine::paint(), ArrowedLineItem::paint(), VScaledEllipse::paint(), SceneRect::paint(), VControlPointSpline::paint(), VCurvePathItem::paint(), VGraphicsSimpleTextItem::paint(), VScenePoint::paint(), VisToolMove::RefreshGeometry(), VScenePoint::refreshLeader(), VCurvePathItem::ScalePenWidth(), VSimpleCurve::ScalePenWidth(), VGraphicsSimpleTextItem::scalePosition(), VControlPointSpline::setCtrlLine(), VAbstractSpline::shape(), VCurvePathItem::shape(), and DialogRotation::ShowDialog().
Variable Documentation
defPointRadiusPixel
const qreal defPointRadiusPixel = (2. / 25.4) * PrintDPI
Definition at line 59 of file global.cpp.
Referenced by VisToolSplinePath::Creating(), Visualization::initPointItem(), VisToolRotation::RefreshGeometry(), VisToolSpline::RefreshGeometry(), scaledRadius(), DialogCurveIntersectAxis::ShowDialog(), DialogEndLine::ShowDialog(), and DialogLineIntersectAxis::ShowDialog().
widthHairLine
const qreal widthHairLine = widthMainLine/3.0
Definition at line 61 of file global.cpp.
Referenced by VLayoutPiece::createLabelItem(), VControlPointSpline::init(), VMainGraphicsScene::initializeOrigins(), VScenePoint::setPointPen(), SceneRect::setRectPen(), and VScenePoint::VScenePoint().
widthMainLine
const qreal widthMainLine = (1.2 / 25.4) * PrintDPI
Definition at line 60 of file global.cpp.
Referenced by MainWindowsNoGUI::exportPDF(), MainWindowsNoGUI::IsLayoutGrayscale(), ArrowedLineItem::paint(), VScaledEllipse::paint(), MainWindowsNoGUI::PrintPages(), MainWindowsNoGUI::RestorePaper(), VCurvePathItem::ScalePenWidth(), VSimpleCurve::ScalePenWidth(), MainWindowsNoGUI::ScenePreview(), VScenePoint::setPointPen(), and SceneRect::setRectPen().