Seamly2D: VPatternLabelData Class Reference
VPatternLabelData Class Reference
The VPatternLabelData class holds the information about pattern info label geometry.
#include <vpatternlabeldata.h>
Public Member Functions
VPatternLabelData ()
VPatternLabelData (const VPatternLabelData &data)
virtual ~VPatternLabelData ()
VPatternLabelData & operator= (const VPatternLabelData &data)
void Swap (VPatternLabelData &data) Q_DECL_NOTHROW
QString GetLabelWidth () const
void SetLabelWidth (const QString &dLabelW)
QString GetLabelHeight () const
void SetLabelHeight (const QString &dLabelH)
int getFontSize () const
void SetFontSize (int iSize)
QString GetRotation () const
void SetRotation (const QString &dRot)
quint32 centerAnchorPoint () const
void setCenterAnchorPoint (const quint32 &centerAnchorPoint)
quint32 topLeftAnchorPoint () const
void setTopLeftAnchorPoint (const quint32 &topLeftAnchorPoint)
quint32 bottomRightAnchorPoint () const
void setBottomRightAnchorPoint (const quint32 &bottomRightAnchorPoint)
Public Member Functions inherited from VAbstractFloatItemData
VAbstractFloatItemData ()
VAbstractFloatItemData (const VAbstractFloatItemData &data)
virtual ~VAbstractFloatItemData ()
VAbstractFloatItemData & operator= (const VAbstractFloatItemData &data)
void Swap (VAbstractFloatItemData &data) Q_DECL_NOTHROW
QPointF GetPos () const
void SetPos (const QPointF &ptPos)
bool IsVisible () const
void SetVisible (bool bVisible)
Private Attributes
QSharedDataPointer< VPatternLabelDataPrivate > d
Detailed Description
The VPatternLabelData class holds the information about pattern info label geometry.
Definition at line 41 of file vpatternlabeldata.h.
Constructor & Destructor Documentation
VPatternLabelData() [1/2]
VPatternLabelData::VPatternLabelData ()
Definition at line 42 of file vpatternlabeldata.cpp.
VPatternLabelData() [2/2]
VPatternLabelData::VPatternLabelData (const VPatternLabelData & data)
Definition at line 48 of file vpatternlabeldata.cpp.
~VPatternLabelData()
VPatternLabelData::~VPatternLabelData () virtual
Definition at line 66 of file vpatternlabeldata.cpp.
Member Function Documentation
bottomRightAnchorPoint()
quint32 VPatternLabelData::bottomRightAnchorPoint () const
Definition at line 142 of file vpatternlabeldata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), setBottomRightAnchorPoint(), and PatternPieceDialog::SetPiece().
centerAnchorPoint()
quint32 VPatternLabelData::centerAnchorPoint () const
Definition at line 118 of file vpatternlabeldata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), setCenterAnchorPoint(), and PatternPieceDialog::SetPiece().
getFontSize()
int VPatternLabelData::getFontSize () const
Definition at line 94 of file vpatternlabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), PatternPieceTool::PrepareLabelData(), VLayoutPiece::SetPatternInfo(), and VLayoutPiece::SetPieceText().
GetLabelHeight()
QString VPatternLabelData::GetLabelHeight () const
Definition at line 82 of file vpatternlabeldata.cpp.
References d.
Referenced by QT_WARNING_POP::createUnion(), anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), and PatternPieceDialog::SetPiece().
GetLabelWidth()
QString VPatternLabelData::GetLabelWidth () const
Definition at line 70 of file vpatternlabeldata.cpp.
References d.
Referenced by QT_WARNING_POP::createUnion(), anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), and PatternPieceDialog::SetPiece().
GetRotation()
QString VPatternLabelData::GetRotation () const
Definition at line 106 of file vpatternlabeldata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), and PatternPieceDialog::SetPiece().
operator=()
VPatternLabelData & VPatternLabelData::operator= (const VPatternLabelData & data)
Definition at line 54 of file vpatternlabeldata.cpp.
References d, and VAbstractFloatItemData::operator=().
Referenced by VPieceLabelData::operator=().
setBottomRightAnchorPoint()
void VPatternLabelData::setBottomRightAnchorPoint (const quint32 & bottomRightAnchorPoint)
Definition at line 148 of file vpatternlabeldata.cpp.
References bottomRightAnchorPoint(), and d.
Referenced by PatternPieceDialog::CreatePiece(), VPattern::ParsePieceDataTag(), and VPattern::ParsePiecePatternInfo().
setCenterAnchorPoint()
void VPatternLabelData::setCenterAnchorPoint (const quint32 & centerAnchorPoint)
Definition at line 124 of file vpatternlabeldata.cpp.
References centerAnchorPoint(), and d.
Referenced by PatternPieceDialog::CreatePiece(), VPattern::ParsePieceDataTag(), and VPattern::ParsePiecePatternInfo().
SetFontSize()
void VPatternLabelData::SetFontSize (int iSize)
Definition at line 100 of file vpatternlabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), VPattern::ParsePieceDataTag(), VPattern::ParsePiecePatternInfo(), PatternPieceTool::savePieceRotation(), PatternPieceTool::SaveResizePattern(), PatternPieceTool::saveResizePiece(), and PatternPieceTool::SaveRotationPattern().
SetLabelHeight()
void VPatternLabelData::SetLabelHeight (const QString & dLabelH)
Definition at line 88 of file vpatternlabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), VPattern::ParsePieceDataTag(), VPattern::ParsePiecePatternInfo(), PatternPieceTool::SaveResizePattern(), and PatternPieceTool::saveResizePiece().
SetLabelWidth()
void VPatternLabelData::SetLabelWidth (const QString & dLabelW)
Definition at line 76 of file vpatternlabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), VPattern::ParsePieceDataTag(), VPattern::ParsePiecePatternInfo(), PatternPieceTool::SaveResizePattern(), and PatternPieceTool::saveResizePiece().
SetRotation()
void VPatternLabelData::SetRotation (const QString & dRot)
Definition at line 112 of file vpatternlabeldata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), VPattern::ParsePieceDataTag(), VPattern::ParsePiecePatternInfo(), PatternPieceTool::savePieceRotation(), and PatternPieceTool::SaveRotationPattern().
setTopLeftAnchorPoint()
void VPatternLabelData::setTopLeftAnchorPoint (const quint32 & topLeftAnchorPoint)
Definition at line 136 of file vpatternlabeldata.cpp.
References d, and topLeftAnchorPoint().
Referenced by PatternPieceDialog::CreatePiece(), VPattern::ParsePieceDataTag(), and VPattern::ParsePiecePatternInfo().
Swap()
void VPatternLabelData::Swap (VPatternLabelData & data)
Definition at line 38 of file vpatternlabeldata.cpp.
References VAbstractFloatItemData::Swap().
Referenced by VPieceLabelData::Swap().
topLeftAnchorPoint()
quint32 VPatternLabelData::topLeftAnchorPoint () const
Definition at line 130 of file vpatternlabeldata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), PatternPieceTool::FindLabelGeometry(), PatternPieceDialog::SetPiece(), and setTopLeftAnchorPoint().
Member Data Documentation
d
QSharedDataPointer<VPatternLabelDataPrivate> VPatternLabelData::d private
Definition at line 79 of file vpatternlabeldata.h.
Referenced by bottomRightAnchorPoint(), centerAnchorPoint(), getFontSize(), GetLabelHeight(), GetLabelWidth(), GetRotation(), operator=(), setBottomRightAnchorPoint(), setCenterAnchorPoint(), SetFontSize(), SetLabelHeight(), SetLabelWidth(), SetRotation(), setTopLeftAnchorPoint(), and topLeftAnchorPoint().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/floatItemData/vpatternlabeldata.h
src/libs/vpatterndb/floatItemData/vpatternlabeldata.cpp