Seamly2D: VAbstractMainWindow Class Reference
VAbstractMainWindow Class Reference abstract
#include <vabstractmainwindow.h>
Public Slots
virtual void ShowToolTip (const QString &toolTip)=0
virtual void updateGroups ()=0
virtual void zoomToSelected ()=0
Public Member Functions
VAbstractMainWindow (QWidget *parent=nullptr)
virtual ~VAbstractMainWindow () Q_DECL_EQ_DEFAULT
Protected Slots
void WindowsLocale ()
void exportToCSV (QString &file)
Protected Member Functions
bool ContinueFormatRewrite (const QString &currentFormatVersion, const QString &maxFormatVersion)
void ToolBarStyle (QToolBar *bar)
virtual void exportToCSVData (const QString &fileName, const DialogExportToCSV &dialog)=0
Protected Attributes
int m_curFileFormatVersion
QString m_curFileFormatVersionStr
Detailed Description
Definition at line 68 of file vabstractmainwindow.h.
Constructor & Destructor Documentation
VAbstractMainWindow()
VAbstractMainWindow::VAbstractMainWindow (QWidget * parent = nullptr) explicit
Definition at line 65 of file vabstractmainwindow.cpp.
~VAbstractMainWindow()
virtual VAbstractMainWindow::~VAbstractMainWindow () virtual
Member Function Documentation
ContinueFormatRewrite()
bool VAbstractMainWindow::ContinueFormatRewrite (const QString & currentFormatVersion, const QString & maxFormatVersion) protected
Definition at line 72 of file vabstractmainwindow.cpp.
References Utils::CheckableMessageBox::isChecked, qApp, Utils::CheckableMessageBox::setDefaultButton(), Utils::CheckableMessageBox::setIconPixmap(), Utils::CheckableMessageBox::setStandardButtons(), and Utils::CheckableMessageBox::setText().
Referenced by TMainWindow::FileSave(), and MainWindow::Save().
exportToCSV
void VAbstractMainWindow::exportToCSV (QString & file) protected slot
Definition at line 123 of file vabstractmainwindow.cpp.
References exportToCSVData(), qApp, DialogExportToCSV::SelectedMib(), DialogExportToCSV::Separator(), and DialogExportToCSV::WithHeader().
Referenced by MainWindow::handleExportToCSV(), and TMainWindow::handleExportToCSV().
exportToCSVData()
virtual void VAbstractMainWindow::exportToCSVData (const QString & fileName, const DialogExportToCSV & dialog) protected pure virtual
Implemented in TMainWindow, and MainWindow.
Referenced by exportToCSV().
ShowToolTip
virtual void VAbstractMainWindow::ShowToolTip (const QString & toolTip) pure virtual slot
Referenced by DialogCubicBezierPath::ChosenObject(), DialogCurveIntersectAxis::ChosenObject(), DialogEndLine::ChosenObject(), DialogLineIntersectAxis::ChosenObject(), DialogRotation::ChosenObject(), DialogSplinePath::ChosenObject(), TogglePieceLock::doCmd(), TogglePieceInLayout::doCmd(), SetPieceColor::doCmd(), VPattern::ParseToolSpline(), VPattern::ParseToolSplinePath(), DialogMove::ShowDialog(), and PatternPieceTool::showStatus().
ToolBarStyle()
void VAbstractMainWindow::ToolBarStyle (QToolBar * bar) protected
Definition at line 103 of file vabstractmainwindow.cpp.
References qApp, and SCASSERT.
Referenced by MainWindow::ToolBarStyles(), and TMainWindow::ToolBarStyles().
updateGroups
virtual void VAbstractMainWindow::updateGroups () pure virtual slot
Referenced by VDrawTool::ContextMenu(), and GroupsWidget::groupItemContextMenu().
WindowsLocale
void VAbstractMainWindow::WindowsLocale () protected slot
Definition at line 117 of file vabstractmainwindow.cpp.
References qApp.
Referenced by MainWindow::Preferences(), and TMainWindow::Preferences().
zoomToSelected
void VAbstractMainWindow::zoomToSelected () pure virtual slot
Definition at line 155 of file vabstractmainwindow.cpp.
Member Data Documentation
m_curFileFormatVersion
int VAbstractMainWindow::m_curFileFormatVersion protected
Definition at line 85 of file vabstractmainwindow.h.
Referenced by TMainWindow::FileNew(), TMainWindow::FileSave(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), MainWindow::LoadPattern(), MainWindow::New(), MainWindow::Save(), and MainWindow::SaveAs().
m_curFileFormatVersionStr
QString VAbstractMainWindow::m_curFileFormatVersionStr protected
Definition at line 86 of file vabstractmainwindow.h.
Referenced by TMainWindow::FileNew(), TMainWindow::FileSave(), TMainWindow::LoadFile(), TMainWindow::LoadFromExistingFile(), MainWindow::LoadPattern(), MainWindow::New(), MainWindow::Save(), and MainWindow::SaveAs().
The documentation for this class was generated from the following files:
src/libs/vwidgets/vabstractmainwindow.h
src/libs/vwidgets/vabstractmainwindow.cpp