Seamly2D: DelGroup Class Reference
DelGroup Class Reference
#include <delgroup.h>
Signals
void updateGroups ()
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Public Member Functions
DelGroup (VAbstractPattern *doc, quint32 id, QUndoCommand *parent=nullptr)
virtual ~DelGroup ()
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Attributes
const QString activeBlockName
Additional Inherited Members
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 63 of file delgroup.h.
Constructor & Destructor Documentation
DelGroup()
DelGroup::DelGroup (VAbstractPattern * doc, quint32 id, QUndoCommand * parent = nullptr)
Definition at line 66 of file delgroup.cpp.
References VDomDocument::CloneNodeById(), VUndoCommand::doc, VUndoCommand::nodeId, and VUndoCommand::xml.
~DelGroup()
DelGroup::~DelGroup () virtual
Definition at line 75 of file delgroup.cpp.
Member Function Documentation
redo()
void DelGroup::redo () virtual
Definition at line 103 of file delgroup.cpp.
References activeBlockName, VAbstractPattern::AttrVisible, VAbstractPattern::createGroups(), VUndoCommand::doc, VDomDocument::elementById(), VMainGraphicsView::NewSceneRect(), VUndoCommand::nodeId, VAbstractPattern::parseGroups(), qApp, VAbstractPattern::setCurrentDraftBlock(), VAbstractPattern::TagGroup, trueStr, and updateGroups().
undo()
void DelGroup::undo () virtual
Definition at line 80 of file delgroup.cpp.
References activeBlockName, VAbstractPattern::createGroups(), VUndoCommand::doc, VMainGraphicsView::NewSceneRect(), VAbstractPattern::parseGroups(), qApp, VAbstractPattern::setCurrentDraftBlock(), updateGroups(), and VUndoCommand::xml.
updateGroups
void DelGroup::updateGroups () signal
Referenced by GroupsWidget::deleteGroupFromList(), GroupsWidget::groupContextMenu(), redo(), and undo().
Member Data Documentation
activeBlockName
const QString DelGroup::activeBlockName private
Definition at line 75 of file delgroup.h.
Referenced by redo(), and undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/delgroup.h
src/libs/vtools/undocommands/delgroup.cpp