Seamly2D: MoveLabel Class Reference
MoveLabel Class Reference
#include <movelabel.h>
Public Member Functions
MoveLabel (VAbstractPattern *doc, const QPointF &pos, const quint32 &id, QUndoCommand *parent=nullptr)
virtual ~MoveLabel ()=default
virtual bool mergeWith (const QUndoCommand *command) Q_DECL_OVERRIDE
virtual int id () const Q_DECL_OVERRIDE
Public Member Functions inherited from MoveAbstractLabel
MoveAbstractLabel (VAbstractPattern *doc, quint32 pointId, const QPointF &pos, QUndoCommand *parent=nullptr)
virtual ~MoveAbstractLabel ()=default
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
quint32 GetPointId () const
QPointF GetNewPos () const
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Protected Member Functions
virtual void Do (const QPointF &pos) Q_DECL_OVERRIDE
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Private Attributes
QGraphicsScene * m_scene
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Protected Attributes inherited from MoveAbstractLabel
QPointF m_oldPos
QPointF m_newPos
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 63 of file movelabel.h.
Constructor & Destructor Documentation
MoveLabel()
MoveLabel::MoveLabel (VAbstractPattern * doc, const QPointF & pos, const quint32 & id, QUndoCommand * parent = nullptr)
Definition at line 67 of file movelabel.cpp.
References AttrMx, AttrMy, VUndoCommand::doc, VDomDocument::elementById(), VDomDocument::GetParametrDouble(), MoveAbstractLabel::m_oldPos, VUndoCommand::nodeId, qApp, and VAbstractPattern::TagPoint.
~MoveLabel()
virtual MoveLabel::~MoveLabel () virtual default
Member Function Documentation
Do()
void MoveLabel::Do (const QPointF & pos) protected virtual
Implements MoveAbstractLabel.
Definition at line 108 of file movelabel.cpp.
References AttrMx, AttrMy, VUndoCommand::doc, VDomDocument::elementById(), VAbstractPattern::getTool(), VUndoCommand::nodeId, qApp, VDomDocument::SetAttribute(), and VAbstractPattern::TagPoint.
id()
int MoveLabel::id () const virtual
Definition at line 102 of file movelabel.cpp.
References MoveLabel.
mergeWith()
bool MoveLabel::mergeWith (const QUndoCommand * command) virtual
Definition at line 86 of file movelabel.cpp.
References MoveAbstractLabel::GetNewPos(), MoveAbstractLabel::GetPointId(), MoveAbstractLabel::m_newPos, VUndoCommand::nodeId, and SCASSERT.
Member Data Documentation
m_scene
QGraphicsScene* MoveLabel::m_scene private
Definition at line 79 of file movelabel.h.
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/label/movelabel.h
src/libs/vtools/undocommands/label/movelabel.cpp