Seamly2D: VPoster Class Reference
VPoster Class Reference
#include <vposter.h>
Public Member Functions
VPoster (const QPrinter *printer)
QVector< PosterData > Calc (const QRect &imageRect, int page, PageOrientation orientation) const
QVector< QGraphicsItem * > Borders (QGraphicsItem *parent, const PosterData &img, int sheets) const
Private Member Functions
int CountRows (int height, PageOrientation orientation) const
int CountColumns (int width, PageOrientation orientation) const
PosterData Cut (int i, int j, const QRect &imageRect, PageOrientation orientation) const
QRect PageRect () const
Static Private Member Functions
static qreal ToPixel (qreal val)
Private Attributes
const QPrinter * printer
quint32 allowance
allowance is the width of the strip that holds the tiled grid information and that is used for the gluing.
Detailed Description
Definition at line 84 of file vposter.h.
Constructor & Destructor Documentation
VPoster()
VPoster::VPoster (const QPrinter * printer) explicit
Definition at line 70 of file vposter.cpp.
Member Function Documentation
Borders()
QVector< QGraphicsItem * > VPoster::Borders (QGraphicsItem * parent, const PosterData & img, int sheets) const
Definition at line 104 of file vposter.cpp.
References allowance, PosterData::column, PosterData::columns, PosterData::index, PosterData::rect, PosterData::row, and PosterData::rows.
Calc()
QVector< PosterData > VPoster::Calc (const QRect & imageRect, int page, PageOrientation orientation) const
Definition at line 76 of file vposter.cpp.
References PosterData::columns, CountColumns(), CountRows(), Cut(), PosterData::index, printer, and PosterData::rows.
Referenced by TST_VPoster::BigPoster(), and TST_VPoster::SmallPoster().
CountColumns()
int VPoster::CountColumns (int width, PageOrientation orientation) const private
Definition at line 239 of file vposter.cpp.
References allowance, Landscape, and PageRect().
Referenced by Calc().
CountRows()
int VPoster::CountRows (int height, PageOrientation orientation) const private
Definition at line 192 of file vposter.cpp.
References allowance, Landscape, and PageRect().
Referenced by Calc().
Cut()
PosterData VPoster::Cut (int i, int j, const QRect & imageRect, PageOrientation orientation) const private
Definition at line 266 of file vposter.cpp.
References allowance, Landscape, PageRect(), PosterData::row, and SCASSERT.
Referenced by Calc().
PageRect()
QRect VPoster::PageRect () const private
Definition at line 298 of file vposter.cpp.
References printer, and ToPixel().
Referenced by CountColumns(), CountRows(), and Cut().
ToPixel()
qreal VPoster::ToPixel (qreal val) static private
Definition at line 320 of file vposter.cpp.
References PrintDPI.
Referenced by PageRect().
Member Data Documentation
allowance
quint32 VPoster::allowance private
allowance is the width of the strip that holds the tiled grid information and that is used for the gluing.
Definition at line 99 of file vposter.h.
Referenced by Borders(), CountColumns(), CountRows(), and Cut().
printer
const QPrinter* VPoster::printer private
Definition at line 94 of file vposter.h.
Referenced by Calc(), and PageRect().
The documentation for this class was generated from the following files:
src/libs/vlayout/vposter.h
src/libs/vlayout/vposter.cpp