Seamly2D: XMLString Class Reference
XMLString Class Reference
#include <XMLString.hpp>
Static Public Member Functions
String concatenation functions
static void catString (char *const target, const char *const src)
static void catString (XMLCh *const target, const XMLCh *const src)
static void catString (char *const target, const char *const src)
static void catString (XMLCh *const target, const XMLCh *const src)
static void catString (char *const target, const char *const src)
static void catString (XMLCh *const target, const XMLCh *const src)
String comparison functions
static int compareIString (const char *const str1, const char *const str2)
static int compareIString (const XMLCh *const str1, const XMLCh *const str2)
static int compareIStringASCII (const XMLCh *const str1, const XMLCh *const str2)
static int compareNString (const char *const str1, const char *const str2, const XMLSize_t count)
static int compareNString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count)
static int compareNIString (const char *const str1, const char *const str2, const XMLSize_t count)
static int compareNIString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count)
static int compareString (const char *const str1, const char *const str2)
static int compareString (const XMLCh *const str1, const XMLCh *const str2)
static bool equals (const XMLCh *str1, const XMLCh *str2)
static bool equalsN (const XMLCh *str1, const XMLCh *str2, XMLSize_t n)
static bool equals (const char *str1, const char *str2)
static bool equalsN (const char *str1, const char *str2, XMLSize_t n)
static bool regionMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
static bool regionIMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
static int compareIString (const char *const str1, const char *const str2)
static int compareIString (const XMLCh *const str1, const XMLCh *const str2)
static int compareIStringASCII (const XMLCh *const str1, const XMLCh *const str2)
static int compareNString (const char *const str1, const char *const str2, const XMLSize_t count)
static int compareNString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count)
static int compareNIString (const char *const str1, const char *const str2, const XMLSize_t count)
static int compareNIString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count)
static int compareString (const char *const str1, const char *const str2)
static int compareString (const XMLCh *const str1, const XMLCh *const str2)
static bool equals (const XMLCh *str1, const XMLCh *str2)
static bool equalsN (const XMLCh *str1, const XMLCh *str2, XMLSize_t n)
static bool equals (const char *str1, const char *str2)
static bool equalsN (const char *str1, const char *str2, XMLSize_t n)
static bool regionMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
static bool regionIMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
static int compareIString (const char *const str1, const char *const str2)
static int compareIString (const XMLCh *const str1, const XMLCh *const str2)
static int compareIStringASCII (const XMLCh *const str1, const XMLCh *const str2)
static int compareNString (const char *const str1, const char *const str2, const XMLSize_t count)
static int compareNString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count)
static int compareNIString (const char *const str1, const char *const str2, const XMLSize_t count)
static int compareNIString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count)
static int compareString (const char *const str1, const char *const str2)
static int compareString (const XMLCh *const str1, const XMLCh *const str2)
static bool equals (const XMLCh *str1, const XMLCh *str2)
static bool equalsN (const XMLCh *str1, const XMLCh *str2, XMLSize_t n)
static bool equals (const char *str1, const char *str2)
static bool equalsN (const char *str1, const char *str2, XMLSize_t n)
static bool regionMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
static bool regionIMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
String copy functions
static void copyString (char *const target, const char *const src)
static void copyString (XMLCh *const target, const XMLCh *const src)
static bool copyNString (XMLCh *const target, const XMLCh *const src, const XMLSize_t maxChars)
static void copyString (char *const target, const char *const src)
static void copyString (XMLCh *const target, const XMLCh *const src)
static bool copyNString (XMLCh *const target, const XMLCh *const src, const XMLSize_t maxChars)
static void copyString (char *const target, const char *const src)
static void copyString (XMLCh *const target, const XMLCh *const src)
static bool copyNString (XMLCh *const target, const XMLCh *const src, const XMLSize_t maxChars)
Hash functions
static XMLSize_t hash (const char *const toHash, const XMLSize_t hashModulus)
static XMLSize_t hash (const XMLCh *const toHash, const XMLSize_t hashModulus)
static XMLSize_t hashN (const XMLCh *const toHash, const XMLSize_t numChars, const XMLSize_t hashModulus)
static XMLSize_t hash (const char *const toHash, const XMLSize_t hashModulus)
static XMLSize_t hash (const XMLCh *const toHash, const XMLSize_t hashModulus)
static XMLSize_t hashN (const XMLCh *const toHash, const XMLSize_t numChars, const XMLSize_t hashModulus)
static XMLSize_t hash (const char *const toHash, const XMLSize_t hashModulus)
static XMLSize_t hash (const XMLCh *const toHash, const XMLSize_t hashModulus)
static XMLSize_t hashN (const XMLCh *const toHash, const XMLSize_t numChars, const XMLSize_t hashModulus)
Search functions
static int indexOf (const char *const toSearch, const char ch)
static int indexOf (const XMLCh *const toSearch, const XMLCh ch)
static int indexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int indexOf (const XMLCh *const toSearch, const XMLCh chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int lastIndexOf (const char *const toSearch, const char ch)
static int lastIndexOf (const XMLCh *const toSearch, const XMLCh ch)
static int lastIndexOf (const XMLCh ch, const XMLCh *const toSearch, const XMLSize_t toSearchLen)
static int lastIndexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int lastIndexOf (const XMLCh *const toSearch, const XMLCh ch, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int indexOf (const char *const toSearch, const char ch)
static int indexOf (const XMLCh *const toSearch, const XMLCh ch)
static int indexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int indexOf (const XMLCh *const toSearch, const XMLCh chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int lastIndexOf (const char *const toSearch, const char ch)
static int lastIndexOf (const XMLCh *const toSearch, const XMLCh ch)
static int lastIndexOf (const XMLCh ch, const XMLCh *const toSearch, const XMLSize_t toSearchLen)
static int lastIndexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int lastIndexOf (const XMLCh *const toSearch, const XMLCh ch, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int indexOf (const char *const toSearch, const char ch)
static int indexOf (const XMLCh *const toSearch, const XMLCh ch)
static int indexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int indexOf (const XMLCh *const toSearch, const XMLCh chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int lastIndexOf (const char *const toSearch, const char ch)
static int lastIndexOf (const XMLCh *const toSearch, const XMLCh ch)
static int lastIndexOf (const XMLCh ch, const XMLCh *const toSearch, const XMLSize_t toSearchLen)
static int lastIndexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int lastIndexOf (const XMLCh *const toSearch, const XMLCh ch, const XMLSize_t fromIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Fixed size string movement
static void moveChars (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t count)
static void moveChars (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t count)
static void moveChars (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t count)
Substring function
static void subString (char *const targetStr, const char *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, const XMLSize_t srcStrLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void subString (char *const targetStr, const char *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, const XMLSize_t srcStrLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void subString (char *const targetStr, const char *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, const XMLSize_t srcStrLength, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Replication function
static char * replicate (const char *const toRep, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static XMLCh * replicate (const XMLCh *const toRep, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static char * replicate (const char *const toRep, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static XMLCh * replicate (const XMLCh *const toRep, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static char * replicate (const char *const toRep, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static XMLCh * replicate (const XMLCh *const toRep, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
String query function
static bool startsWith (const char *const toTest, const char *const prefix)
static bool startsWith (const XMLCh *const toTest, const XMLCh *const prefix)
static bool startsWithI (const char *const toTest, const char *const prefix)
static bool startsWithI (const XMLCh *const toTest, const XMLCh *const prefix)
static bool endsWith (const XMLCh *const toTest, const XMLCh *const suffix)
static const XMLCh * findAny (const XMLCh *const toSearch, const XMLCh *const searchList)
static XMLCh * findAny (XMLCh *const toSearch, const XMLCh *const searchList)
static int patternMatch (const XMLCh *const toSearch, const XMLCh *const pattern)
static XMLSize_t stringLen (const char *const src)
static XMLSize_t stringLen (const XMLCh *const src)
static bool isValidNOTATION (const XMLCh *const name, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool isValidEncName (const XMLCh *const name)
static bool isAlpha (XMLCh const theChar)
static bool isDigit (XMLCh const theChar)
static bool isAlphaNum (XMLCh const theChar)
static bool isHex (XMLCh const theChar)
static bool isInList (const XMLCh *const toFind, const XMLCh *const enumList)
static bool startsWith (const char *const toTest, const char *const prefix)
static bool startsWith (const XMLCh *const toTest, const XMLCh *const prefix)
static bool startsWithI (const char *const toTest, const char *const prefix)
static bool startsWithI (const XMLCh *const toTest, const XMLCh *const prefix)
static bool endsWith (const XMLCh *const toTest, const XMLCh *const suffix)
static const XMLCh * findAny (const XMLCh *const toSearch, const XMLCh *const searchList)
static XMLCh * findAny (XMLCh *const toSearch, const XMLCh *const searchList)
static int patternMatch (const XMLCh *const toSearch, const XMLCh *const pattern)
static XMLSize_t stringLen (const char *const src)
static XMLSize_t stringLen (const XMLCh *const src)
static bool isValidNOTATION (const XMLCh *const name, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool isValidEncName (const XMLCh *const name)
static bool isAlpha (XMLCh const theChar)
static bool isDigit (XMLCh const theChar)
static bool isAlphaNum (XMLCh const theChar)
static bool isHex (XMLCh const theChar)
static bool isInList (const XMLCh *const toFind, const XMLCh *const enumList)
static bool startsWith (const char *const toTest, const char *const prefix)
static bool startsWith (const XMLCh *const toTest, const XMLCh *const prefix)
static bool startsWithI (const char *const toTest, const char *const prefix)
static bool startsWithI (const XMLCh *const toTest, const XMLCh *const prefix)
static bool endsWith (const XMLCh *const toTest, const XMLCh *const suffix)
static const XMLCh * findAny (const XMLCh *const toSearch, const XMLCh *const searchList)
static XMLCh * findAny (XMLCh *const toSearch, const XMLCh *const searchList)
static int patternMatch (const XMLCh *const toSearch, const XMLCh *const pattern)
static XMLSize_t stringLen (const char *const src)
static XMLSize_t stringLen (const XMLCh *const src)
static bool isValidNOTATION (const XMLCh *const name, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool isValidEncName (const XMLCh *const name)
static bool isAlpha (XMLCh const theChar)
static bool isDigit (XMLCh const theChar)
static bool isAlphaNum (XMLCh const theChar)
static bool isHex (XMLCh const theChar)
static bool isInList (const XMLCh *const toFind, const XMLCh *const enumList)
Conversion functions
static void sizeToText (const XMLSize_t toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void sizeToText (const XMLSize_t toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool textToBin (const XMLCh *const toConvert, unsigned int &toFill, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int parseInt (const XMLCh *const toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void cut (XMLCh *const toCutFrom, const XMLSize_t count)
static char * transcode (const XMLCh *const toTranscode, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool transcode (const XMLCh *const toTranscode, char *const toFill, const XMLSize_t maxChars, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static XMLCh * transcode (const char *const toTranscode, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool transcode (const char *const toTranscode, XMLCh *const toFill, const XMLSize_t maxChars, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void trim (char *const toTrim)
static void trim (XMLCh *const toTrim)
static BaseRefVectorOf< XMLCh > * tokenizeString (const XMLCh *const tokenizeSrc, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static BaseRefVectorOf< XMLCh > * tokenizeString (const XMLCh *const tokenizeSrc, XMLCh delimiter, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void sizeToText (const XMLSize_t toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void sizeToText (const XMLSize_t toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool textToBin (const XMLCh *const toConvert, unsigned int &toFill, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int parseInt (const XMLCh *const toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void cut (XMLCh *const toCutFrom, const XMLSize_t count)
static char * transcode (const XMLCh *const toTranscode, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool transcode (const XMLCh *const toTranscode, char *const toFill, const XMLSize_t maxChars, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static XMLCh * transcode (const char *const toTranscode, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool transcode (const char *const toTranscode, XMLCh *const toFill, const XMLSize_t maxChars, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void trim (char *const toTrim)
static void trim (XMLCh *const toTrim)
static BaseRefVectorOf< XMLCh > * tokenizeString (const XMLCh *const tokenizeSrc, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static BaseRefVectorOf< XMLCh > * tokenizeString (const XMLCh *const tokenizeSrc, XMLCh delimiter, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void sizeToText (const XMLSize_t toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void sizeToText (const XMLSize_t toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const unsigned long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void binToText (const long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool textToBin (const XMLCh *const toConvert, unsigned int &toFill, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static int parseInt (const XMLCh *const toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void cut (XMLCh *const toCutFrom, const XMLSize_t count)
static char * transcode (const XMLCh *const toTranscode, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool transcode (const XMLCh *const toTranscode, char *const toFill, const XMLSize_t maxChars, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static XMLCh * transcode (const char *const toTranscode, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static bool transcode (const char *const toTranscode, XMLCh *const toFill, const XMLSize_t maxChars, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void trim (char *const toTrim)
static void trim (XMLCh *const toTrim)
static BaseRefVectorOf< XMLCh > * tokenizeString (const XMLCh *const tokenizeSrc, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static BaseRefVectorOf< XMLCh > * tokenizeString (const XMLCh *const tokenizeSrc, XMLCh delimiter, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Formatting functions
static XMLCh * makeUName (const XMLCh *const pszURI, const XMLCh *const pszName)
static XMLSize_t replaceTokens (XMLCh *const errText, const XMLSize_t maxChars, const XMLCh *const text1, const XMLCh *const text2, const XMLCh *const text3, const XMLCh *const text4, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void upperCase (XMLCh *const toUpperCase)
static void upperCaseASCII (XMLCh *const toUpperCase)
static void lowerCase (XMLCh *const toLowerCase)
static void lowerCaseASCII (XMLCh *const toLowerCase)
static bool isWSReplaced (const XMLCh *const toCheck)
static bool isWSCollapsed (const XMLCh *const toCheck)
static void replaceWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void collapseWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void removeWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void removeChar (const XMLCh *const srcString, const XMLCh &toRemove, XMLBuffer &dstBuffer)
static void fixURI (const XMLCh *const str, XMLCh *const target)
static XMLCh * makeUName (const XMLCh *const pszURI, const XMLCh *const pszName)
static XMLSize_t replaceTokens (XMLCh *const errText, const XMLSize_t maxChars, const XMLCh *const text1, const XMLCh *const text2, const XMLCh *const text3, const XMLCh *const text4, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void upperCase (XMLCh *const toUpperCase)
static void upperCaseASCII (XMLCh *const toUpperCase)
static void lowerCase (XMLCh *const toLowerCase)
static void lowerCaseASCII (XMLCh *const toLowerCase)
static bool isWSReplaced (const XMLCh *const toCheck)
static bool isWSCollapsed (const XMLCh *const toCheck)
static void replaceWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void collapseWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void removeWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void removeChar (const XMLCh *const srcString, const XMLCh &toRemove, XMLBuffer &dstBuffer)
static void fixURI (const XMLCh *const str, XMLCh *const target)
static XMLCh * makeUName (const XMLCh *const pszURI, const XMLCh *const pszName)
static XMLSize_t replaceTokens (XMLCh *const errText, const XMLSize_t maxChars, const XMLCh *const text1, const XMLCh *const text2, const XMLCh *const text3, const XMLCh *const text4, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void upperCase (XMLCh *const toUpperCase)
static void upperCaseASCII (XMLCh *const toUpperCase)
static void lowerCase (XMLCh *const toLowerCase)
static void lowerCaseASCII (XMLCh *const toLowerCase)
static bool isWSReplaced (const XMLCh *const toCheck)
static bool isWSCollapsed (const XMLCh *const toCheck)
static void replaceWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void collapseWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void removeWS (XMLCh *toConvert, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void removeChar (const XMLCh *const srcString, const XMLCh &toRemove, XMLBuffer &dstBuffer)
static void fixURI (const XMLCh *const str, XMLCh *const target)
String Memory Management functions
static void release (char **buf, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void release (XMLCh **buf, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void release (char **buf, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void release (XMLCh **buf, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void release (char **buf, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
static void release (XMLCh **buf, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Private Member Functions
Constructors and Destructor
XMLString ()
~XMLString ()
XMLString ()
~XMLString ()
XMLString ()
~XMLString ()
Initialization
static MemoryManager * fgMemoryManager
class XMLPlatformUtils
static void initString (XMLLCPTranscoder *const defToUse, MemoryManager *const manager)
static void termString ()
static bool validateRegion (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
static void initString (XMLLCPTranscoder *const defToUse, MemoryManager *const manager)
static void termString ()
static bool validateRegion (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
static void initString (XMLLCPTranscoder *const defToUse, MemoryManager *const manager)
static void termString ()
static bool validateRegion (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount)
Detailed Description
Class for representing native character strings and handling common string operations
This class is Unicode compliant. This class is designed primarily for internal use, but due to popular demand, it is being made publicly available. Users of this class must understand that this is not an officially supported class. All public methods of this class are static functions.
Definition at line 45 of file XMLString.hpp.
Constructor & Destructor Documentation
XMLString() [1/3]
XMLString::XMLString () private
Unimplemented default constructor
~XMLString() [1/3]
XMLString::~XMLString () private
Unimplemented destructor
XMLString() [2/3]
XMLString::XMLString () private
Unimplemented default constructor
~XMLString() [2/3]
XMLString::~XMLString () private
Unimplemented destructor
XMLString() [3/3]
XMLString::XMLString () private
Unimplemented default constructor
~XMLString() [3/3]
XMLString::~XMLString () private
Unimplemented destructor
Member Function Documentation
binToText() [1/24]
static void XMLString::binToText (const int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [2/24]
static void XMLString::binToText (const int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [3/24]
static void XMLString::binToText (const int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [4/24]
static void XMLString::binToText (const int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [5/24]
static void XMLString::binToText (const int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [6/24]
static void XMLString::binToText (const int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [7/24]
static void XMLString::binToText (const long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [8/24]
static void XMLString::binToText (const long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [9/24]
static void XMLString::binToText (const long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [10/24]
static void XMLString::binToText (const long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [11/24]
static void XMLString::binToText (const long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [12/24]
static void XMLString::binToText (const long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [13/24]
static void XMLString::binToText (const unsigned int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [14/24]
static void XMLString::binToText (const unsigned int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [15/24]
static void XMLString::binToText (const unsigned int toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [16/24]
static void XMLString::binToText (const unsigned int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [17/24]
static void XMLString::binToText (const unsigned int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [18/24]
static void XMLString::binToText (const unsigned int toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [19/24]
static void XMLString::binToText (const unsigned long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [20/24]
static void XMLString::binToText (const unsigned long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [21/24]
static void XMLString::binToText (const unsigned long toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [22/24]
static void XMLString::binToText (const unsigned long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [23/24]
static void XMLString::binToText (const unsigned long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
binToText() [24/24]
static void XMLString::binToText (const unsigned long toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts binary data to a text string based a given radix
Parameters
toFormat The number to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
catString() [1/6]
static void XMLString::catString (char *const target, const char *const src) static
Concatenates two strings.
catString appends src to target and terminates the resulting string with a null character. The initial character of src overwrites the terminating character of target .
No overflow checking is performed when strings are copied or appended. The behavior of catString is undefined if source and destination strings overlap.
Parameters
target Null-terminated destination string
src Null-terminated source string
Referenced by XMLPlatformUtils::removeDotDotSlash(), and XMLPlatformUtils::weavePaths().
catString() [2/6]
static void XMLString::catString (char *const target, const char *const src) static
Concatenates two strings.
catString appends src to target and terminates the resulting string with a null character. The initial character of src overwrites the terminating character of target .
No overflow checking is performed when strings are copied or appended. The behavior of catString is undefined if source and destination strings overlap.
Parameters
target Null-terminated destination string
src Null-terminated source string
catString() [3/6]
static void XMLString::catString (char *const target, const char *const src) static
Concatenates two strings.
catString appends src to target and terminates the resulting string with a null character. The initial character of src overwrites the terminating character of target .
No overflow checking is performed when strings are copied or appended. The behavior of catString is undefined if source and destination strings overlap.
Parameters
target Null-terminated destination string
src Null-terminated source string
catString() [4/6]
static void XMLString::catString (XMLCh *const target, const XMLCh *const src) static
Concatenates two strings.
catString appends src to target and terminates the resulting string with a null character. The initial character of src overwrites the terminating character of target. No overflow checking is performed when strings are copied or appended. The behavior of catString is undefined if source and destination strings overlap.
Parameters
target Null-terminated destination string
src Null-terminated source string
catString() [5/6]
static void XMLString::catString (XMLCh *const target, const XMLCh *const src) static
Concatenates two strings.
catString appends src to target and terminates the resulting string with a null character. The initial character of src overwrites the terminating character of target. No overflow checking is performed when strings are copied or appended. The behavior of catString is undefined if source and destination strings overlap.
Parameters
target Null-terminated destination string
src Null-terminated source string
catString() [6/6]
static void XMLString::catString (XMLCh *const target, const XMLCh *const src) static
Concatenates two strings.
catString appends src to target and terminates the resulting string with a null character. The initial character of src overwrites the terminating character of target. No overflow checking is performed when strings are copied or appended. The behavior of catString is undefined if source and destination strings overlap.
Parameters
target Null-terminated destination string
src Null-terminated source string
collapseWS() [1/3]
static void XMLString::collapseWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Collapse whitespace
Parameters
toConvert The string which needs to be whitespace collapsed. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
collapseWS() [2/3]
static void XMLString::collapseWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Collapse whitespace
Parameters
toConvert The string which needs to be whitespace collapsed. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
collapseWS() [3/3]
static void XMLString::collapseWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Collapse whitespace
Parameters
toConvert The string which needs to be whitespace collapsed. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
compareIString() [1/6]
static int XMLString::compareIString (const char *const str1, const char *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareIString() [2/6]
static int XMLString::compareIString (const char *const str1, const char *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareIString() [3/6]
static int XMLString::compareIString (const char *const str1, const char *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareIString() [4/6]
static int XMLString::compareIString (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareIString() [5/6]
static int XMLString::compareIString (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareIString() [6/6]
static int XMLString::compareIString (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareIStringASCII() [1/3]
static int XMLString::compareIStringASCII (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship. The routine only lowercases A to Z.
Parameters
str1 Null-terminated ASCII string to compare
str2 Null-terminated ASCII string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareIStringASCII() [2/3]
static int XMLString::compareIStringASCII (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship. The routine only lowercases A to Z.
Parameters
str1 Null-terminated ASCII string to compare
str2 Null-terminated ASCII string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareIStringASCII() [3/3]
static int XMLString::compareIStringASCII (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares lowercase versions of str1 and str2 and returns a value indicating their relationship. The routine only lowercases A to Z.
Parameters
str1 Null-terminated ASCII string to compare
str2 Null-terminated ASCII string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNIString() [1/6]
static int XMLString::compareNIString (const char *const str1, const char *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 without regard to case and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
Referenced by startsWithI().
compareNIString() [2/6]
static int XMLString::compareNIString (const char *const str1, const char *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 without regard to case and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNIString() [3/6]
static int XMLString::compareNIString (const char *const str1, const char *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 without regard to case and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNIString() [4/6]
static int XMLString::compareNIString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 without regard to case and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNIString() [5/6]
static int XMLString::compareNIString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 without regard to case and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNIString() [6/6]
static int XMLString::compareNIString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 without regard to case and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNString() [1/6]
static int XMLString::compareNString (const char *const str1, const char *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
Referenced by startsWith().
compareNString() [2/6]
static int XMLString::compareNString (const char *const str1, const char *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNString() [3/6]
static int XMLString::compareNString (const char *const str1, const char *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNString() [4/6]
static int XMLString::compareNString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNString() [5/6]
static int XMLString::compareNString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareNString() [6/6]
static int XMLString::compareNString (const XMLCh *const str1, const XMLCh *const str2, const XMLSize_t count) static
Lexicographically compares, at most, the first count characters in str1 and str2 and returns a value indicating the relationship between the substrings.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
count The number of characters to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareString() [1/6]
static int XMLString::compareString (const char *const str1, const char *const str2) static
Lexicographically compares str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
Referenced by DatatypeValidator::compare().
compareString() [2/6]
static int XMLString::compareString (const char *const str1, const char *const str2) static
Lexicographically compares str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareString() [3/6]
static int XMLString::compareString (const char *const str1, const char *const str2) static
Lexicographically compares str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareString() [4/6]
static int XMLString::compareString (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareString() [5/6]
static int XMLString::compareString (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
compareString() [6/6]
static int XMLString::compareString (const XMLCh *const str1, const XMLCh *const str2) static
Lexicographically compares str1 and str2 and returns a value indicating their relationship.
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
The return value indicates the relation of str1 to str2 as follows Less than 0 means str1 is less than str2 Equal to 0 means str1 is identical to str2 Greater than 0 means str1 is more than str2
copyNString() [1/3]
static bool XMLString::copyNString (XMLCh *const target, const XMLCh *const src, const XMLSize_t maxChars) static
Copies src, upto a fixed number of characters, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of copyNString is undefined if the source and destination strings overlap.
Parameters
target Destination string. The size of the buffer should atleast be 'maxChars + 1'.
src Null-terminated source string
maxChars The maximum number of characters to copy
Referenced by DOMDocumentImpl::getPooledNString().
copyNString() [2/3]
static bool XMLString::copyNString (XMLCh *const target, const XMLCh *const src, const XMLSize_t maxChars) static
Copies src, upto a fixed number of characters, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of copyNString is undefined if the source and destination strings overlap.
Parameters
target Destination string. The size of the buffer should atleast be 'maxChars + 1'.
src Null-terminated source string
maxChars The maximum number of characters to copy
copyNString() [3/3]
static bool XMLString::copyNString (XMLCh *const target, const XMLCh *const src, const XMLSize_t maxChars) static
Copies src, upto a fixed number of characters, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of copyNString is undefined if the source and destination strings overlap.
Parameters
target Destination string. The size of the buffer should atleast be 'maxChars + 1'.
src Null-terminated source string
maxChars The maximum number of characters to copy
copyString() [1/6]
static void XMLString::copyString (char *const target, const char *const src) static
Copies src, including the terminating null character, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of strcpy is undefined if the source and destination strings overlap.
Parameters
target Destination string
src Null-terminated source string
Referenced by DOMDocumentImpl::getPooledString(), ElemStack::setCurrentSchemaElemName(), and XMLPlatformUtils::weavePaths().
copyString() [2/6]
static void XMLString::copyString (char *const target, const char *const src) static
Copies src, including the terminating null character, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of strcpy is undefined if the source and destination strings overlap.
Parameters
target Destination string
src Null-terminated source string
copyString() [3/6]
static void XMLString::copyString (char *const target, const char *const src) static
Copies src, including the terminating null character, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of strcpy is undefined if the source and destination strings overlap.
Parameters
target Destination string
src Null-terminated source string
copyString() [4/6]
static void XMLString::copyString (XMLCh *const target, const XMLCh *const src) static
Copies src, including the terminating null character, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of copyString is undefined if the source and destination strings overlap.
Parameters
target Destination string
src Null-terminated source string
copyString() [5/6]
static void XMLString::copyString (XMLCh *const target, const XMLCh *const src) static
Copies src, including the terminating null character, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of copyString is undefined if the source and destination strings overlap.
Parameters
target Destination string
src Null-terminated source string
copyString() [6/6]
static void XMLString::copyString (XMLCh *const target, const XMLCh *const src) static
Copies src, including the terminating null character, to the location specified by target.
No overflow checking is performed when strings are copied or appended. The behavior of copyString is undefined if the source and destination strings overlap.
Parameters
target Destination string
src Null-terminated source string
cut() [1/3]
static void XMLString::cut (XMLCh *const toCutFrom, const XMLSize_t count) static
Cut leading chars from a string
Parameters
toCutFrom The string to cut chars from
count The count of leading chars to cut
cut() [2/3]
static void XMLString::cut (XMLCh *const toCutFrom, const XMLSize_t count) static
Cut leading chars from a string
Parameters
toCutFrom The string to cut chars from
count The count of leading chars to cut
cut() [3/3]
static void XMLString::cut (XMLCh *const toCutFrom, const XMLSize_t count) static
Cut leading chars from a string
Parameters
toCutFrom The string to cut chars from
count The count of leading chars to cut
endsWith() [1/3]
bool XMLString::endsWith (const XMLCh *const toTest, const XMLCh *const suffix) inline static
Tells if the sub-string appears within a string at the end.
Parameters
toTest The string to test
suffix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the end of toTest, else false
Definition at line 1498 of file XMLString.hpp.
References regionMatches(), and stringLen().
endsWith() [2/3]
static bool XMLString::endsWith (const XMLCh *const toTest, const XMLCh *const suffix) static
Tells if the sub-string appears within a string at the end.
Parameters
toTest The string to test
suffix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the end of toTest, else false
endsWith() [3/3]
static bool XMLString::endsWith (const XMLCh *const toTest, const XMLCh *const suffix) static
Tells if the sub-string appears within a string at the end.
Parameters
toTest The string to test
suffix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the end of toTest, else false
equals() [1/6]
bool XMLString::equals (const char * str1, const char * str2) inline static
Definition at line 1557 of file XMLString.hpp.
equals() [2/6]
static bool XMLString::equals (const char * str1, const char * str2) static
equals() [3/6]
static bool XMLString::equals (const char * str1, const char * str2) static
equals() [4/6]
bool XMLString::equals (const XMLCh * str1, const XMLCh * str2) inline static
compares str1 and str2
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
Definition at line 1523 of file XMLString.hpp.
Referenced by ComplexTypeInfo::contains(), StringHasher::equals(), DOMDeepNodeListPool< TVal, THasher >::findBucketElem(), DOMDocumentImpl::getPooledString(), TraverseSchema::isAttrOrAttrGroup(), and TraverseSchema::isBaseFromAnotherSchema().
equals() [5/6]
static bool XMLString::equals (const XMLCh * str1, const XMLCh * str2) static
compares str1 and str2
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
equals() [6/6]
static bool XMLString::equals (const XMLCh * str1, const XMLCh * str2) static
compares str1 and str2
Parameters
str1 Null-terminated string to compare
str2 Null-terminated string to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
equalsN() [1/6]
bool XMLString::equalsN (const char * str1, const char * str2, XMLSize_t n) inline static
compares str1 and str2
Parameters
str1 string to compare
str2 string to compare
n number of characters to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
Definition at line 1574 of file XMLString.hpp.
equalsN() [2/6]
static bool XMLString::equalsN (const char * str1, const char * str2, XMLSize_t n) static
compares str1 and str2
Parameters
str1 string to compare
str2 string to compare
n number of characters to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
equalsN() [3/6]
static bool XMLString::equalsN (const char * str1, const char * str2, XMLSize_t n) static
compares str1 and str2
Parameters
str1 string to compare
str2 string to compare
n number of characters to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
equalsN() [4/6]
bool XMLString::equalsN (const XMLCh * str1, const XMLCh * str2, XMLSize_t n) inline static
compares str1 and str2
Parameters
str1 string to compare
str2 string to compare
n number of characters to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
Definition at line 1540 of file XMLString.hpp.
Referenced by DOMDocumentImpl::getPooledNString().
equalsN() [5/6]
static bool XMLString::equalsN (const XMLCh * str1, const XMLCh * str2, XMLSize_t n) static
compares str1 and str2
Parameters
str1 string to compare
str2 string to compare
n number of characters to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
equalsN() [6/6]
static bool XMLString::equalsN (const XMLCh * str1, const XMLCh * str2, XMLSize_t n) static
compares str1 and str2
Parameters
str1 string to compare
str2 string to compare
n number of characters to compare
Returns
true if two strings are equal, false if not If one string is null, while the other is zero-length string, it is considered as equal.
findAny() [1/6]
static const XMLCh* XMLString::findAny (const XMLCh *const toSearch, const XMLCh *const searchList) static
Tells if a string has any occurrence of any character of another string within itself
Parameters
toSearch The string to be searched
searchList The string from which characters to be searched for are drawn
Returns
Returns the pointer to the location where the first occurrence of any character from searchList is found, else returns 0
findAny() [2/6]
static const XMLCh* XMLString::findAny (const XMLCh *const toSearch, const XMLCh *const searchList) static
Tells if a string has any occurrence of any character of another string within itself
Parameters
toSearch The string to be searched
searchList The string from which characters to be searched for are drawn
Returns
Returns the pointer to the location where the first occurrence of any character from searchList is found, else returns 0
findAny() [3/6]
static const XMLCh* XMLString::findAny (const XMLCh *const toSearch, const XMLCh *const searchList) static
Tells if a string has any occurrence of any character of another string within itself
Parameters
toSearch The string to be searched
searchList The string from which characters to be searched for are drawn
Returns
Returns the pointer to the location where the first occurrence of any character from searchList is found, else returns 0
findAny() [4/6]
static XMLCh* XMLString::findAny (XMLCh *const toSearch, const XMLCh *const searchList) static
Tells if a string has any occurrence of any character of another string within itself
Parameters
toSearch The string to be searched
searchList The string from which characters to be searched for are drawn
Returns
Returns the pointer to the location where the first occurrence of any character from searchList is found, else returns 0
findAny() [5/6]
static XMLCh* XMLString::findAny (XMLCh *const toSearch, const XMLCh *const searchList) static
Tells if a string has any occurrence of any character of another string within itself
Parameters
toSearch The string to be searched
searchList The string from which characters to be searched for are drawn
Returns
Returns the pointer to the location where the first occurrence of any character from searchList is found, else returns 0
findAny() [6/6]
static XMLCh* XMLString::findAny (XMLCh *const toSearch, const XMLCh *const searchList) static
Tells if a string has any occurrence of any character of another string within itself
Parameters
toSearch The string to be searched
searchList The string from which characters to be searched for are drawn
Returns
Returns the pointer to the location where the first occurrence of any character from searchList is found, else returns 0
fixURI() [1/3]
static void XMLString::fixURI (const XMLCh *const str, XMLCh *const target) static
Fixes a platform dependent absolute path filename to standard URI form.
Windows: fix 'x:' to 'file:///x:' and convert any backslash to forward slash
UNIX: fix '/blah/blahblah' to 'file:///blah/blahblah'
Parameters
str The string that has the absolute path filename
target The target string pre-allocated to store the fixed uri
fixURI() [2/3]
static void XMLString::fixURI (const XMLCh *const str, XMLCh *const target) static
Fixes a platform dependent absolute path filename to standard URI form.
Windows: fix 'x:' to 'file:///x:' and convert any backslash to forward slash
UNIX: fix '/blah/blahblah' to 'file:///blah/blahblah'
Parameters
str The string that has the absolute path filename
target The target string pre-allocated to store the fixed uri
fixURI() [3/3]
static void XMLString::fixURI (const XMLCh *const str, XMLCh *const target) static
Fixes a platform dependent absolute path filename to standard URI form.
Windows: fix 'x:' to 'file:///x:' and convert any backslash to forward slash
UNIX: fix '/blah/blahblah' to 'file:///blah/blahblah'
Parameters
str The string that has the absolute path filename
target The target string pre-allocated to store the fixed uri
hash() [1/6]
static XMLSize_t XMLString::hash (const char *const toHash, const XMLSize_t hashModulus) static
Hashes a string given a modulus
Parameters
toHash The string to hash
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
Referenced by StringHasher::getHashVal(), and DOMDocumentImpl::getPooledString().
hash() [2/6]
static XMLSize_t XMLString::hash (const char *const toHash, const XMLSize_t hashModulus) static
Hashes a string given a modulus
Parameters
toHash The string to hash
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
hash() [3/6]
static XMLSize_t XMLString::hash (const char *const toHash, const XMLSize_t hashModulus) static
Hashes a string given a modulus
Parameters
toHash The string to hash
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
hash() [4/6]
XMLSize_t XMLString::hash (const XMLCh *const toHash, const XMLSize_t hashModulus) inline static
Hashes a string given a modulus
Parameters
toHash The string to hash
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
Definition at line 1596 of file XMLString.hpp.
hash() [5/6]
static XMLSize_t XMLString::hash (const XMLCh *const toHash, const XMLSize_t hashModulus) static
Hashes a string given a modulus
Parameters
toHash The string to hash
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
hash() [6/6]
static XMLSize_t XMLString::hash (const XMLCh *const toHash, const XMLSize_t hashModulus) static
Hashes a string given a modulus
Parameters
toHash The string to hash
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
hashN() [1/3]
XMLSize_t XMLString::hashN (const XMLCh *const toHash, const XMLSize_t numChars, const XMLSize_t hashModulus) inline static
Hashes a string given a modulus taking a maximum number of characters as the limit
Parameters
toHash The string to hash
numChars The maximum number of characters to consider for hashing
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
Definition at line 1612 of file XMLString.hpp.
Referenced by DOMDocumentImpl::getPooledNString().
hashN() [2/3]
static XMLSize_t XMLString::hashN (const XMLCh *const toHash, const XMLSize_t numChars, const XMLSize_t hashModulus) static
Hashes a string given a modulus taking a maximum number of characters as the limit
Parameters
toHash The string to hash
numChars The maximum number of characters to consider for hashing
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
hashN() [3/3]
static XMLSize_t XMLString::hashN (const XMLCh *const toHash, const XMLSize_t numChars, const XMLSize_t hashModulus) static
Hashes a string given a modulus taking a maximum number of characters as the limit
Parameters
toHash The string to hash
numChars The maximum number of characters to consider for hashing
hashModulus The divisor to be used for hashing
Returns
Returns the hash value
indexOf() [1/12]
static int XMLString::indexOf (const char *const toSearch, const char ch) static
Provides the index of the first occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
Referenced by TraverseSchema::getLocalPart(), TraverseSchema::getPrefix(), XMLStringTokenizer::isDelimeter(), XMLUri::isPathCharacter(), XMLUri::isReservedCharacter(), XMLUri::isReservedOrUnreservedCharacter(), XMLUri::isUnreservedCharacter(), and ComplexTypeInfo::setTypeName().
indexOf() [2/12]
static int XMLString::indexOf (const char *const toSearch, const char ch) static
Provides the index of the first occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [3/12]
static int XMLString::indexOf (const char *const toSearch, const char ch) static
Provides the index of the first occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [4/12]
static int XMLString::indexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the first occurrence of a character within a string starting from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start searching from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [5/12]
static int XMLString::indexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the first occurrence of a character within a string starting from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start searching from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [6/12]
static int XMLString::indexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the first occurrence of a character within a string starting from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start searching from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [7/12]
static int XMLString::indexOf (const XMLCh *const toSearch, const XMLCh ch) static
Provides the index of the first occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [8/12]
static int XMLString::indexOf (const XMLCh *const toSearch, const XMLCh ch) static
Provides the index of the first occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [9/12]
static int XMLString::indexOf (const XMLCh *const toSearch, const XMLCh ch) static
Provides the index of the first occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [10/12]
static int XMLString::indexOf (const XMLCh *const toSearch, const XMLCh chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the first occurrence of a character within a string starting from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start searching from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [11/12]
static int XMLString::indexOf (const XMLCh *const toSearch, const XMLCh chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the first occurrence of a character within a string starting from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start searching from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
indexOf() [12/12]
static int XMLString::indexOf (const XMLCh *const toSearch, const XMLCh chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the first occurrence of a character within a string starting from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start searching from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
initString() [1/3]
static void XMLString::initString (XMLLCPTranscoder *const defToUse, MemoryManager *const manager) static private
Init/Term methods called from XMLPlatformUtils class
initString() [2/3]
static void XMLString::initString (XMLLCPTranscoder *const defToUse, MemoryManager *const manager) static private
Init/Term methods called from XMLPlatformUtils class
initString() [3/3]
static void XMLString::initString (XMLLCPTranscoder *const defToUse, MemoryManager *const manager) static private
Init/Term methods called from XMLPlatformUtils class
isAlpha() [1/3]
static bool XMLString::isAlpha (XMLCh const theChar) static
Checks whether a character is within [a-zA-Z].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isAlpha() [2/3]
static bool XMLString::isAlpha (XMLCh const theChar) static
Checks whether a character is within [a-zA-Z].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isAlpha() [3/3]
static bool XMLString::isAlpha (XMLCh const theChar) static
Checks whether a character is within [a-zA-Z].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isAlphaNum() [1/3]
static bool XMLString::isAlphaNum (XMLCh const theChar) static
Checks whether a character is within [0-9a-zA-Z].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
Referenced by XMLUri::isReservedOrUnreservedCharacter(), and XMLUri::isUnreservedCharacter().
isAlphaNum() [2/3]
static bool XMLString::isAlphaNum (XMLCh const theChar) static
Checks whether a character is within [0-9a-zA-Z].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isAlphaNum() [3/3]
static bool XMLString::isAlphaNum (XMLCh const theChar) static
Checks whether a character is within [0-9a-zA-Z].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isDigit() [1/3]
static bool XMLString::isDigit (XMLCh const theChar) static
Checks whether a character is within [0-9].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isDigit() [2/3]
static bool XMLString::isDigit (XMLCh const theChar) static
Checks whether a character is within [0-9].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isDigit() [3/3]
static bool XMLString::isDigit (XMLCh const theChar) static
Checks whether a character is within [0-9].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isHex() [1/3]
static bool XMLString::isHex (XMLCh const theChar) static
Checks whether a character is within [0-9a-fA-F].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isHex() [2/3]
static bool XMLString::isHex (XMLCh const theChar) static
Checks whether a character is within [0-9a-fA-F].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isHex() [3/3]
static bool XMLString::isHex (XMLCh const theChar) static
Checks whether a character is within [0-9a-fA-F].
Parameters
theChar the character to check
Returns
Returns true if within the range, otherwise false
isInList() [1/3]
static bool XMLString::isInList (const XMLCh *const toFind, const XMLCh *const enumList) static
Find is the string appears in the enum list
Parameters
toFind the string to be found
enumList the list return true if found
isInList() [2/3]
static bool XMLString::isInList (const XMLCh *const toFind, const XMLCh *const enumList) static
Find is the string appears in the enum list
Parameters
toFind the string to be found
enumList the list return true if found
isInList() [3/3]
static bool XMLString::isInList (const XMLCh *const toFind, const XMLCh *const enumList) static
Find is the string appears in the enum list
Parameters
toFind the string to be found
enumList the list return true if found
isValidEncName() [1/3]
static bool XMLString::isValidEncName (const XMLCh *const name) static
Checks whether an name is a valid EncName.
Parameters
name The string to check its EncName validity
Returns
Returns true if name is EncName valid, otherwise false
isValidEncName() [2/3]
static bool XMLString::isValidEncName (const XMLCh *const name) static
Checks whether an name is a valid EncName.
Parameters
name The string to check its EncName validity
Returns
Returns true if name is EncName valid, otherwise false
isValidEncName() [3/3]
static bool XMLString::isValidEncName (const XMLCh *const name) static
Checks whether an name is a valid EncName.
Parameters
name The string to check its EncName validity
Returns
Returns true if name is EncName valid, otherwise false
isValidNOTATION() [1/3]
static bool XMLString::isValidNOTATION (const XMLCh *const name, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Checks whether an name is a valid NOTATION according to XML 1.0
Parameters
name The string to check its NOTATION validity
manager The memory manager
Returns
Returns true if name is NOTATION valid, otherwise false
isValidNOTATION() [2/3]
static bool XMLString::isValidNOTATION (const XMLCh *const name, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Checks whether an name is a valid NOTATION according to XML 1.0
Parameters
name The string to check its NOTATION validity
manager The memory manager
Returns
Returns true if name is NOTATION valid, otherwise false
isValidNOTATION() [3/3]
static bool XMLString::isValidNOTATION (const XMLCh *const name, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Checks whether an name is a valid NOTATION according to XML 1.0
Parameters
name The string to check its NOTATION validity
manager The memory manager
Returns
Returns true if name is NOTATION valid, otherwise false
isWSCollapsed() [1/3]
static bool XMLString::isWSCollapsed (const XMLCh *const toCheck) static
Check if string is WhiteSpace:collapse
Parameters
toCheck The string which needs to be checked.
isWSCollapsed() [2/3]
static bool XMLString::isWSCollapsed (const XMLCh *const toCheck) static
Check if string is WhiteSpace:collapse
Parameters
toCheck The string which needs to be checked.
isWSCollapsed() [3/3]
static bool XMLString::isWSCollapsed (const XMLCh *const toCheck) static
Check if string is WhiteSpace:collapse
Parameters
toCheck The string which needs to be checked.
isWSReplaced() [1/3]
static bool XMLString::isWSReplaced (const XMLCh *const toCheck) static
Check if string is WhiteSpace:replace
Parameters
toCheck The string which needs to be checked.
isWSReplaced() [2/3]
static bool XMLString::isWSReplaced (const XMLCh *const toCheck) static
Check if string is WhiteSpace:replace
Parameters
toCheck The string which needs to be checked.
isWSReplaced() [3/3]
static bool XMLString::isWSReplaced (const XMLCh *const toCheck) static
Check if string is WhiteSpace:replace
Parameters
toCheck The string which needs to be checked.
lastIndexOf() [1/15]
static int XMLString::lastIndexOf (const char *const toSearch, const char ch) static
Provides the index of the last occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
Referenced by lastIndexOf().
lastIndexOf() [2/15]
static int XMLString::lastIndexOf (const char *const toSearch, const char ch) static
Provides the index of the last occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [3/15]
static int XMLString::lastIndexOf (const char *const toSearch, const char ch) static
Provides the index of the last occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [4/15]
static int XMLString::lastIndexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the last occurrence of a character within a string starting backward from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start backward search from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [5/15]
static int XMLString::lastIndexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the last occurrence of a character within a string starting backward from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start backward search from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [6/15]
static int XMLString::lastIndexOf (const char *const toSearch, const char chToFind, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the last occurrence of a character within a string starting backward from a given index
Parameters
toSearch The string to search
chToFind The character to search within the string
fromIndex The index to start backward search from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [7/15]
int XMLString::lastIndexOf (const XMLCh *const toSearch, const XMLCh ch) inline static
Provides the index of the last occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
Definition at line 1591 of file XMLString.hpp.
References lastIndexOf(), and stringLen().
lastIndexOf() [8/15]
static int XMLString::lastIndexOf (const XMLCh *const toSearch, const XMLCh ch) static
Provides the index of the last occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [9/15]
static int XMLString::lastIndexOf (const XMLCh *const toSearch, const XMLCh ch) static
Provides the index of the last occurrence of a character within a string
Parameters
toSearch The string to search
ch The character to search within the string
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [10/15]
static int XMLString::lastIndexOf (const XMLCh *const toSearch, const XMLCh ch, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the last occurrence of a character within a string starting backward from a given index
Parameters
toSearch The string to search
ch The character to search within the string
fromIndex The index to start backward search from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [11/15]
static int XMLString::lastIndexOf (const XMLCh *const toSearch, const XMLCh ch, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the last occurrence of a character within a string starting backward from a given index
Parameters
toSearch The string to search
ch The character to search within the string
fromIndex The index to start backward search from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [12/15]
static int XMLString::lastIndexOf (const XMLCh *const toSearch, const XMLCh ch, const XMLSize_t fromIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Provides the index of the last occurrence of a character within a string starting backward from a given index
Parameters
toSearch The string to search
ch The character to search within the string
fromIndex The index to start backward search from
manager The MemoryManager to use to allocate objects
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [13/15]
static int XMLString::lastIndexOf (const XMLCh ch, const XMLCh *const toSearch, const XMLSize_t toSearchLen) static
Provides the index of the last occurrence of a character within a string
Parameters
ch The character to search within the string
toSearch The string to search
toSearchLen The length of the string to search
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [14/15]
static int XMLString::lastIndexOf (const XMLCh ch, const XMLCh *const toSearch, const XMLSize_t toSearchLen) static
Provides the index of the last occurrence of a character within a string
Parameters
ch The character to search within the string
toSearch The string to search
toSearchLen The length of the string to search
Returns
If found, returns the index of the character within the string, else returns -1.
lastIndexOf() [15/15]
static int XMLString::lastIndexOf (const XMLCh ch, const XMLCh *const toSearch, const XMLSize_t toSearchLen) static
Provides the index of the last occurrence of a character within a string
Parameters
ch The character to search within the string
toSearch The string to search
toSearchLen The length of the string to search
Returns
If found, returns the index of the character within the string, else returns -1.
lowerCase() [1/3]
static void XMLString::lowerCase (XMLCh *const toLowerCase) static
Converts a string to lowercase
Parameters
toLowerCase The string which needs to be converted to lowercase. On return, this buffer also holds the converted lowercase string
lowerCase() [2/3]
static void XMLString::lowerCase (XMLCh *const toLowerCase) static
Converts a string to lowercase
Parameters
toLowerCase The string which needs to be converted to lowercase. On return, this buffer also holds the converted lowercase string
lowerCase() [3/3]
static void XMLString::lowerCase (XMLCh *const toLowerCase) static
Converts a string to lowercase
Parameters
toLowerCase The string which needs to be converted to lowercase. On return, this buffer also holds the converted lowercase string
lowerCaseASCII() [1/3]
static void XMLString::lowerCaseASCII (XMLCh *const toLowerCase) static
Converts a string to lowercase The routine only lowercases a to z (other characters not changed).
Parameters
toLowerCase The string which needs to be converted to lowercase. On return, this buffer also holds the converted lowercase string
lowerCaseASCII() [2/3]
static void XMLString::lowerCaseASCII (XMLCh *const toLowerCase) static
Converts a string to lowercase The routine only lowercases a to z (other characters not changed).
Parameters
toLowerCase The string which needs to be converted to lowercase. On return, this buffer also holds the converted lowercase string
lowerCaseASCII() [3/3]
static void XMLString::lowerCaseASCII (XMLCh *const toLowerCase) static
Converts a string to lowercase The routine only lowercases a to z (other characters not changed).
Parameters
toLowerCase The string which needs to be converted to lowercase. On return, this buffer also holds the converted lowercase string
makeUName() [1/3]
static XMLCh* XMLString::makeUName (const XMLCh *const pszURI, const XMLCh *const pszName) static
Creates a UName from a URI and base name. It is in the form {url}name, and is commonly used internally to represent fully qualified names when namespaces are enabled.
Parameters
pszURI The URI part of the name
pszName The base part of the name
Returns
Returns the complete formatted UName
makeUName() [2/3]
static XMLCh* XMLString::makeUName (const XMLCh *const pszURI, const XMLCh *const pszName) static
Creates a UName from a URI and base name. It is in the form {url}name, and is commonly used internally to represent fully qualified names when namespaces are enabled.
Parameters
pszURI The URI part of the name
pszName The base part of the name
Returns
Returns the complete formatted UName
makeUName() [3/3]
static XMLCh* XMLString::makeUName (const XMLCh *const pszURI, const XMLCh *const pszName) static
Creates a UName from a URI and base name. It is in the form {url}name, and is commonly used internally to represent fully qualified names when namespaces are enabled.
Parameters
pszURI The URI part of the name
pszName The base part of the name
Returns
Returns the complete formatted UName
moveChars() [1/3]
void XMLString::moveChars (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t count) inline static
Moves X number of chars
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
count The number of chars to move
Definition at line 1453 of file XMLString.hpp.
moveChars() [2/3]
static void XMLString::moveChars (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t count) static
Moves X number of chars
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
count The number of chars to move
moveChars() [3/3]
static void XMLString::moveChars (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t count) static
Moves X number of chars
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
count The number of chars to move
parseInt() [1/3]
static int XMLString::parseInt (const XMLCh *const toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts a string of decimal chars to a binary value
Note that leading and trailing whitespace is legal and will be ignored,
Only one and either of (+,-) after the leading whitespace, before any other characters are allowed.
but the remainder must be all decimal digits.
Parameters
toConvert The string of digits to convert
manager The MemoryManager to use to allocate objects
parseInt() [2/3]
static int XMLString::parseInt (const XMLCh *const toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts a string of decimal chars to a binary value
Note that leading and trailing whitespace is legal and will be ignored,
Only one and either of (+,-) after the leading whitespace, before any other characters are allowed.
but the remainder must be all decimal digits.
Parameters
toConvert The string of digits to convert
manager The MemoryManager to use to allocate objects
parseInt() [3/3]
static int XMLString::parseInt (const XMLCh *const toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts a string of decimal chars to a binary value
Note that leading and trailing whitespace is legal and will be ignored,
Only one and either of (+,-) after the leading whitespace, before any other characters are allowed.
but the remainder must be all decimal digits.
Parameters
toConvert The string of digits to convert
manager The MemoryManager to use to allocate objects
patternMatch() [1/3]
static int XMLString::patternMatch (const XMLCh *const toSearch, const XMLCh *const pattern) static
Tells if a string has pattern within itself
Parameters
toSearch The string to be searched
pattern The pattern to be located within the string
Returns
Returns index to the location where the pattern was found, else returns -1
patternMatch() [2/3]
static int XMLString::patternMatch (const XMLCh *const toSearch, const XMLCh *const pattern) static
Tells if a string has pattern within itself
Parameters
toSearch The string to be searched
pattern The pattern to be located within the string
Returns
Returns index to the location where the pattern was found, else returns -1
patternMatch() [3/3]
static int XMLString::patternMatch (const XMLCh *const toSearch, const XMLCh *const pattern) static
Tells if a string has pattern within itself
Parameters
toSearch The string to be searched
pattern The pattern to be located within the string
Returns
Returns index to the location where the pattern was found, else returns -1
regionIMatches() [1/3]
static bool XMLString::regionIMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) static
Lexicographically compares str1 and str2 regions without regard to case and returns true if they are equal, otherwise false.
A substring of str1 is compared to a substring of str2. The result is true if these substrings represent identical character sequences. The substring of str1 to be compared begins at offset1 and has length charCount. The substring of str2 to be compared begins at offset2 and has length charCount. The result is false if and only if at least one of the following is true: offset1 is negative. offset2 is negative. offset1+charCount is greater than the length of str1. offset2+charCount is greater than the length of str2. There is some nonnegative integer k less than charCount such that: str1.charAt(offset1+k) != str2.charAt(offset2+k)
Parameters
str1 Null-terminated string to compare
offset1 Starting offset of str1
str2 Null-terminated string to compare
offset2 Starting offset of str2
charCount The number of characters to compare
Returns
true if the specified subregion of str1 exactly matches the specified subregion of str2>; false otherwise.
regionIMatches() [2/3]
static bool XMLString::regionIMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) static
Lexicographically compares str1 and str2 regions without regard to case and returns true if they are equal, otherwise false.
A substring of str1 is compared to a substring of str2. The result is true if these substrings represent identical character sequences. The substring of str1 to be compared begins at offset1 and has length charCount. The substring of str2 to be compared begins at offset2 and has length charCount. The result is false if and only if at least one of the following is true: offset1 is negative. offset2 is negative. offset1+charCount is greater than the length of str1. offset2+charCount is greater than the length of str2. There is some nonnegative integer k less than charCount such that: str1.charAt(offset1+k) != str2.charAt(offset2+k)
Parameters
str1 Null-terminated string to compare
offset1 Starting offset of str1
str2 Null-terminated string to compare
offset2 Starting offset of str2
charCount The number of characters to compare
Returns
true if the specified subregion of str1 exactly matches the specified subregion of str2>; false otherwise.
regionIMatches() [3/3]
static bool XMLString::regionIMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) static
Lexicographically compares str1 and str2 regions without regard to case and returns true if they are equal, otherwise false.
A substring of str1 is compared to a substring of str2. The result is true if these substrings represent identical character sequences. The substring of str1 to be compared begins at offset1 and has length charCount. The substring of str2 to be compared begins at offset2 and has length charCount. The result is false if and only if at least one of the following is true: offset1 is negative. offset2 is negative. offset1+charCount is greater than the length of str1. offset2+charCount is greater than the length of str2. There is some nonnegative integer k less than charCount such that: str1.charAt(offset1+k) != str2.charAt(offset2+k)
Parameters
str1 Null-terminated string to compare
offset1 Starting offset of str1
str2 Null-terminated string to compare
offset2 Starting offset of str2
charCount The number of characters to compare
Returns
true if the specified subregion of str1 exactly matches the specified subregion of str2>; false otherwise.
regionMatches() [1/3]
static bool XMLString::regionMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) static
Lexicographically compares str1 and str2 regions and returns true if they are equal, otherwise false.
A substring of str1 is compared to a substring of str2. The result is true if these substrings represent identical character sequences. The substring of str1 to be compared begins at offset1 and has length charCount. The substring of str2 to be compared begins at offset2 and has length charCount. The result is false if and only if at least one of the following is true: offset1 is negative. offset2 is negative. offset1+charCount is greater than the length of str1. offset2+charCount is greater than the length of str2. There is some nonnegative integer k less than charCount such that: str1.charAt(offset1+k) != str2.charAt(offset2+k)
Parameters
str1 Null-terminated string to compare
offset1 Starting offset of str1
str2 Null-terminated string to compare
offset2 Starting offset of str2
charCount The number of characters to compare
Returns
true if the specified subregion of str1 exactly matches the specified subregion of str2>; false otherwise.
Referenced by endsWith().
regionMatches() [2/3]
static bool XMLString::regionMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) static
Lexicographically compares str1 and str2 regions and returns true if they are equal, otherwise false.
A substring of str1 is compared to a substring of str2. The result is true if these substrings represent identical character sequences. The substring of str1 to be compared begins at offset1 and has length charCount. The substring of str2 to be compared begins at offset2 and has length charCount. The result is false if and only if at least one of the following is true: offset1 is negative. offset2 is negative. offset1+charCount is greater than the length of str1. offset2+charCount is greater than the length of str2. There is some nonnegative integer k less than charCount such that: str1.charAt(offset1+k) != str2.charAt(offset2+k)
Parameters
str1 Null-terminated string to compare
offset1 Starting offset of str1
str2 Null-terminated string to compare
offset2 Starting offset of str2
charCount The number of characters to compare
Returns
true if the specified subregion of str1 exactly matches the specified subregion of str2>; false otherwise.
regionMatches() [3/3]
static bool XMLString::regionMatches (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) static
Lexicographically compares str1 and str2 regions and returns true if they are equal, otherwise false.
A substring of str1 is compared to a substring of str2. The result is true if these substrings represent identical character sequences. The substring of str1 to be compared begins at offset1 and has length charCount. The substring of str2 to be compared begins at offset2 and has length charCount. The result is false if and only if at least one of the following is true: offset1 is negative. offset2 is negative. offset1+charCount is greater than the length of str1. offset2+charCount is greater than the length of str2. There is some nonnegative integer k less than charCount such that: str1.charAt(offset1+k) != str2.charAt(offset2+k)
Parameters
str1 Null-terminated string to compare
offset1 Starting offset of str1
str2 Null-terminated string to compare
offset2 Starting offset of str2
charCount The number of characters to compare
Returns
true if the specified subregion of str1 exactly matches the specified subregion of str2>; false otherwise.
release() [1/6]
static void XMLString::release (char ** buf, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Release the parameter string that was allocated by XMLString::transcode and XMLString::replicate. The implementation will call MemoryManager::deallocate and then turn the string to a null pointer.
Parameters
buf The string to be deleted and become a null pointer.
manager The MemoryManager used to allocate the string
release() [2/6]
static void XMLString::release (char ** buf, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Release the parameter string that was allocated by XMLString::transcode and XMLString::replicate. The implementation will call MemoryManager::deallocate and then turn the string to a null pointer.
Parameters
buf The string to be deleted and become a null pointer.
manager The MemoryManager used to allocate the string
release() [3/6]
static void XMLString::release (char ** buf, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Release the parameter string that was allocated by XMLString::transcode and XMLString::replicate. The implementation will call MemoryManager::deallocate and then turn the string to a null pointer.
Parameters
buf The string to be deleted and become a null pointer.
manager The MemoryManager used to allocate the string
release() [4/6]
static void XMLString::release (XMLCh ** buf, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Release the parameter string that was allocated by XMLString::transcode and XMLString::replicate. The implementation will call MemoryManager::deallocate and then turn the string to a null pointer.
Parameters
buf The string to be deleted and become a null pointer.
manager The MemoryManager used to allocate the string
release() [5/6]
static void XMLString::release (XMLCh ** buf, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Release the parameter string that was allocated by XMLString::transcode and XMLString::replicate. The implementation will call MemoryManager::deallocate and then turn the string to a null pointer.
Parameters
buf The string to be deleted and become a null pointer.
manager The MemoryManager used to allocate the string
release() [6/6]
static void XMLString::release (XMLCh ** buf, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Release the parameter string that was allocated by XMLString::transcode and XMLString::replicate. The implementation will call MemoryManager::deallocate and then turn the string to a null pointer.
Parameters
buf The string to be deleted and become a null pointer.
manager The MemoryManager used to allocate the string
removeChar() [1/3]
static void XMLString::removeChar (const XMLCh *const srcString, const XMLCh & toRemove, XMLBuffer & dstBuffer) static
Remove character
Parameters
srcString The string
toRemove The character needs to be removed from the string
dstBuffer The buffer containing the result
removeChar() [2/3]
static void XMLString::removeChar (const XMLCh *const srcString, const XMLCh & toRemove, XMLBuffer & dstBuffer) static
Remove character
Parameters
srcString The string
toRemove The character needs to be removed from the string
dstBuffer The buffer containing the result
removeChar() [3/3]
static void XMLString::removeChar (const XMLCh *const srcString, const XMLCh & toRemove, XMLBuffer & dstBuffer) static
Remove character
Parameters
srcString The string
toRemove The character needs to be removed from the string
dstBuffer The buffer containing the result
removeWS() [1/3]
static void XMLString::removeWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Remove whitespace
Parameters
toConvert The string which needs to be whitespace removed. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
removeWS() [2/3]
static void XMLString::removeWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Remove whitespace
Parameters
toConvert The string which needs to be whitespace removed. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
removeWS() [3/3]
static void XMLString::removeWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Remove whitespace
Parameters
toConvert The string which needs to be whitespace removed. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
replaceTokens() [1/3]
static XMLSize_t XMLString::replaceTokens (XMLCh *const errText, const XMLSize_t maxChars, const XMLCh *const text1, const XMLCh *const text2, const XMLCh *const text3, const XMLCh *const text4, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Internal function to perform token replacement for strings.
Parameters
errText The text (NULL terminated) where the replacement is to be done. The size of this buffer should be 'maxChars + 1' to account for the final NULL.
maxChars The size of the output buffer, i.e. the maximum number of characters that it will hold. If the result is larger, it will be truncated.
text1 Replacement text-one
text2 Replacement text-two
text3 Replacement text-three
text4 Replacement text-four
manager The MemoryManager to use to allocate objects
Returns
Returns the count of characters that are outputted
replaceTokens() [2/3]
static XMLSize_t XMLString::replaceTokens (XMLCh *const errText, const XMLSize_t maxChars, const XMLCh *const text1, const XMLCh *const text2, const XMLCh *const text3, const XMLCh *const text4, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Internal function to perform token replacement for strings.
Parameters
errText The text (NULL terminated) where the replacement is to be done. The size of this buffer should be 'maxChars + 1' to account for the final NULL.
maxChars The size of the output buffer, i.e. the maximum number of characters that it will hold. If the result is larger, it will be truncated.
text1 Replacement text-one
text2 Replacement text-two
text3 Replacement text-three
text4 Replacement text-four
manager The MemoryManager to use to allocate objects
Returns
Returns the count of characters that are outputted
replaceTokens() [3/3]
static XMLSize_t XMLString::replaceTokens (XMLCh *const errText, const XMLSize_t maxChars, const XMLCh *const text1, const XMLCh *const text2, const XMLCh *const text3, const XMLCh *const text4, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Internal function to perform token replacement for strings.
Parameters
errText The text (NULL terminated) where the replacement is to be done. The size of this buffer should be 'maxChars + 1' to account for the final NULL.
maxChars The size of the output buffer, i.e. the maximum number of characters that it will hold. If the result is larger, it will be truncated.
text1 Replacement text-one
text2 Replacement text-two
text3 Replacement text-three
text4 Replacement text-four
manager The MemoryManager to use to allocate objects
Returns
Returns the count of characters that are outputted
replaceWS() [1/3]
static void XMLString::replaceWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Replace whitespace
Parameters
toConvert The string which needs to be whitespace replaced. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
replaceWS() [2/3]
static void XMLString::replaceWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Replace whitespace
Parameters
toConvert The string which needs to be whitespace replaced. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
replaceWS() [3/3]
static void XMLString::replaceWS (XMLCh * toConvert, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Replace whitespace
Parameters
toConvert The string which needs to be whitespace replaced. On return , this buffer also holds the converted string
manager The MemoryManager to use to allocate objects
replicate() [1/6]
static char* XMLString::replicate (const char *const toRep, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Replicates a string NOTE: The returned buffer is allocated with the MemoryManager. It is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toRep The string to replicate
manager The MemoryManager to use to allocate the string
Returns
Returns a pointer to the replicated string
See also
XMLString::release(char**, MemoryManager*)
Referenced by DOMDeepNodeListPoolTableBucketElem< TVal >::DOMDeepNodeListPoolTableBucketElem(), SAXException::operator=(), XMLRefInfo::operator=(), FieldValueMap::put(), DOMDeepNodeListPool< TVal, THasher >::put(), XMLPlatformUtils::removeDotSlash(), XMLEntityDecl::setBaseURI(), XMLNotationDecl::setBaseURI(), SchemaElementDecl::setDefaultValue(), XMLAttDef::setEnumeration(), XMLScanner::setExternalNoNamespaceSchemaLocation(), XMLScanner::setExternalSchemaLocation(), XMLEntityDecl::setNotationName(), DatatypeValidator::setPattern(), XMLEntityDecl::setPublicId(), XMLNotationDecl::setPublicId(), XMLScanner::setRootElemName(), StringToken::setString(), XMLEntityDecl::setSystemId(), XMLNotationDecl::setSystemId(), SchemaGrammar::setTargetNamespace(), ComplexTypeInfo::setTypeName(), XMLAttDef::setValue(), XMLEntityDecl::setValue(), AbstractDOMParser::useImplementation(), and XMLRefInfo::XMLRefInfo().
replicate() [2/6]
static char* XMLString::replicate (const char *const toRep, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Replicates a string NOTE: The returned buffer is allocated with the MemoryManager. It is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toRep The string to replicate
manager The MemoryManager to use to allocate the string
Returns
Returns a pointer to the replicated string
See also
XMLString::release(char**, MemoryManager*)
replicate() [3/6]
static char* XMLString::replicate (const char *const toRep, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Replicates a string NOTE: The returned buffer is allocated with the MemoryManager. It is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toRep The string to replicate
manager The MemoryManager to use to allocate the string
Returns
Returns a pointer to the replicated string
See also
XMLString::release(char**, MemoryManager*)
replicate() [4/6]
XMLCh * XMLString::replicate (const XMLCh *const toRep, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline static
Replicates a string NOTE: The returned buffer is allocated with the MemoryManager. It is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toRep The string to replicate
manager The MemoryManager to use to allocate the string
Returns
Returns a pointer to the replicated string
See also
XMLString::release(XMLCh**, MemoryManager*)
Definition at line 1472 of file XMLString.hpp.
References MemoryManager::allocate(), and stringLen().
replicate() [5/6]
static XMLCh* XMLString::replicate (const XMLCh *const toRep, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Replicates a string NOTE: The returned buffer is allocated with the MemoryManager. It is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toRep The string to replicate
manager The MemoryManager to use to allocate the string
Returns
Returns a pointer to the replicated string
See also
XMLString::release(XMLCh**, MemoryManager*)
replicate() [6/6]
static XMLCh* XMLString::replicate (const XMLCh *const toRep, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Replicates a string NOTE: The returned buffer is allocated with the MemoryManager. It is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toRep The string to replicate
manager The MemoryManager to use to allocate the string
Returns
Returns a pointer to the replicated string
See also
XMLString::release(XMLCh**, MemoryManager*)
sizeToText() [1/6]
static void XMLString::sizeToText (const XMLSize_t toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts size to a text string based a given radix
Parameters
toFormat The size to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
Referenced by TraverseSchema::genAnonTypeName().
sizeToText() [2/6]
static void XMLString::sizeToText (const XMLSize_t toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts size to a text string based a given radix
Parameters
toFormat The size to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
sizeToText() [3/6]
static void XMLString::sizeToText (const XMLSize_t toFormat, char *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts size to a text string based a given radix
Parameters
toFormat The size to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
sizeToText() [4/6]
static void XMLString::sizeToText (const XMLSize_t toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts size to a text string based a given radix
Parameters
toFormat The size to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
sizeToText() [5/6]
static void XMLString::sizeToText (const XMLSize_t toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts size to a text string based a given radix
Parameters
toFormat The size to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
sizeToText() [6/6]
static void XMLString::sizeToText (const XMLSize_t toFormat, XMLCh *const toFill, const XMLSize_t maxChars, const unsigned int radix, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts size to a text string based a given radix
Parameters
toFormat The size to convert
toFill The buffer that will hold the output on return. The size of this buffer should at least be 'maxChars + 1'.
maxChars The maximum number of output characters that can be accepted. If the result will not fit, it is an error.
radix The radix of the input data, based on which the conversion
manager The MemoryManager to use to allocate objects will be done
startsWith() [1/6]
static bool XMLString::startsWith (const char *const toTest, const char *const prefix) static
Tells if the sub-string appears within a string at the beginning
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWith() [2/6]
static bool XMLString::startsWith (const char *const toTest, const char *const prefix) static
Tells if the sub-string appears within a string at the beginning
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWith() [3/6]
static bool XMLString::startsWith (const char *const toTest, const char *const prefix) static
Tells if the sub-string appears within a string at the beginning
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWith() [4/6]
bool XMLString::startsWith (const XMLCh *const toTest, const XMLCh *const prefix) inline static
Tells if the sub-string appears within a string at the beginning
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
Definition at line 1486 of file XMLString.hpp.
References compareNString(), and stringLen().
startsWith() [5/6]
static bool XMLString::startsWith (const XMLCh *const toTest, const XMLCh *const prefix) static
Tells if the sub-string appears within a string at the beginning
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWith() [6/6]
static bool XMLString::startsWith (const XMLCh *const toTest, const XMLCh *const prefix) static
Tells if the sub-string appears within a string at the beginning
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWithI() [1/6]
static bool XMLString::startsWithI (const char *const toTest, const char *const prefix) static
Tells if the sub-string appears within a string at the beginning without regard to case
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWithI() [2/6]
static bool XMLString::startsWithI (const char *const toTest, const char *const prefix) static
Tells if the sub-string appears within a string at the beginning without regard to case
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWithI() [3/6]
static bool XMLString::startsWithI (const char *const toTest, const char *const prefix) static
Tells if the sub-string appears within a string at the beginning without regard to case
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWithI() [4/6]
bool XMLString::startsWithI (const XMLCh *const toTest, const XMLCh *const prefix) inline static
Tells if the sub-string appears within a string at the beginning without regard to case
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
Definition at line 1492 of file XMLString.hpp.
References compareNIString(), and stringLen().
startsWithI() [5/6]
static bool XMLString::startsWithI (const XMLCh *const toTest, const XMLCh *const prefix) static
Tells if the sub-string appears within a string at the beginning without regard to case
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
startsWithI() [6/6]
static bool XMLString::startsWithI (const XMLCh *const toTest, const XMLCh *const prefix) static
Tells if the sub-string appears within a string at the beginning without regard to case
Parameters
toTest The string to test
prefix The sub-string that needs to be checked
Returns
Returns true if the sub-string was found at the beginning of toTest, else false
stringLen() [1/6]
static XMLSize_t XMLString::stringLen (const char *const src) static
Get the length of the string
Parameters
src The string whose length is to be determined
Returns
Returns the length of the string
Referenced by DOMBuffer::append(), endsWith(), TraverseSchema::getLocalPart(), DOMDocumentImpl::getPooledString(), XMLBigInteger::getTotalDigit(), lastIndexOf(), XMLPlatformUtils::removeDotDotSlash(), XMLPlatformUtils::removeDotSlash(), replicate(), XMLPlatformUtils::searchSlashDotDotSlash(), DOMBuffer::set(), KVStringPair::set(), XMLDateTime::setBuffer(), ElemStack::setCurrentSchemaElemName(), KVStringPair::setKey(), QName::setLocalPart(), QName::setPrefix(), ComplexTypeInfo::setTypeName(), XMLEntityDecl::setValue(), KVStringPair::setValue(), startsWith(), startsWithI(), validateRegion(), and XMLPlatformUtils::weavePaths().
stringLen() [2/6]
static XMLSize_t XMLString::stringLen (const char *const src) static
Get the length of the string
Parameters
src The string whose length is to be determined
Returns
Returns the length of the string
stringLen() [3/6]
static XMLSize_t XMLString::stringLen (const char *const src) static
Get the length of the string
Parameters
src The string whose length is to be determined
Returns
Returns the length of the string
stringLen() [4/6]
XMLSize_t XMLString::stringLen (const XMLCh *const src) inline static
Get the length of the string
Parameters
src The string whose length is to be determined
Returns
Returns the length of the string
Definition at line 1460 of file XMLString.hpp.
stringLen() [5/6]
static XMLSize_t XMLString::stringLen (const XMLCh *const src) static
Get the length of the string
Parameters
src The string whose length is to be determined
Returns
Returns the length of the string
stringLen() [6/6]
static XMLSize_t XMLString::stringLen (const XMLCh *const src) static
Get the length of the string
Parameters
src The string whose length is to be determined
Returns
Returns the length of the string
subString() [1/9]
static void XMLString::subString (char *const targetStr, const char *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
manager The MemoryManager to use to allocate objects
Referenced by XMLPlatformUtils::removeDotDotSlash(), ComplexTypeInfo::setTypeName(), and XMLPlatformUtils::weavePaths().
subString() [2/9]
static void XMLString::subString (char *const targetStr, const char *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
manager The MemoryManager to use to allocate objects
subString() [3/9]
static void XMLString::subString (char *const targetStr, const char *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
manager The MemoryManager to use to allocate objects
subString() [4/9]
static void XMLString::subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, const XMLSize_t srcStrLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
srcStrLength the length of srcStr
manager The MemoryManager to use to allocate objects
subString() [5/9]
static void XMLString::subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, const XMLSize_t srcStrLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
srcStrLength the length of srcStr
manager The MemoryManager to use to allocate objects
subString() [6/9]
static void XMLString::subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, const XMLSize_t srcStrLength, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
srcStrLength the length of srcStr
manager The MemoryManager to use to allocate objects
subString() [7/9]
static void XMLString::subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
manager The MemoryManager to use to allocate objects
subString() [8/9]
static void XMLString::subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
manager The MemoryManager to use to allocate objects
subString() [9/9]
static void XMLString::subString (XMLCh *const targetStr, const XMLCh *const srcStr, const XMLSize_t startIndex, const XMLSize_t endIndex, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Create a substring of a given string. The substring begins at the specified beginIndex and extends to the character at index endIndex - 1.
Parameters
targetStr The string to copy the chars to
srcStr The string to copy the chars from
startIndex beginning index, inclusive.
endIndex the ending index, exclusive.
manager The MemoryManager to use to allocate objects
termString() [1/3]
static void XMLString::termString () static private
termString() [2/3]
static void XMLString::termString () static private
termString() [3/3]
static void XMLString::termString () static private
textToBin() [1/3]
static bool XMLString::textToBin (const XMLCh *const toConvert, unsigned int & toFill, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts a string of decimal chars to a binary value
Note that leading and trailing whitespace is legal and will be ignored but the remainder must be all decimal digits.
Parameters
toConvert The string of digits to convert
toFill The unsigned int value to fill with the converted value.
manager The MemoryManager to use to allocate objects
textToBin() [2/3]
static bool XMLString::textToBin (const XMLCh *const toConvert, unsigned int & toFill, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts a string of decimal chars to a binary value
Note that leading and trailing whitespace is legal and will be ignored but the remainder must be all decimal digits.
Parameters
toConvert The string of digits to convert
toFill The unsigned int value to fill with the converted value.
manager The MemoryManager to use to allocate objects
textToBin() [3/3]
static bool XMLString::textToBin (const XMLCh *const toConvert, unsigned int & toFill, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Converts a string of decimal chars to a binary value
Note that leading and trailing whitespace is legal and will be ignored but the remainder must be all decimal digits.
Parameters
toConvert The string of digits to convert
toFill The unsigned int value to fill with the converted value.
manager The MemoryManager to use to allocate objects
tokenizeString() [1/6]
static BaseRefVectorOf<XMLCh>* XMLString::tokenizeString (const XMLCh *const tokenizeSrc, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Break a string into tokens with space as delimiter, and stored in a string vector. The caller owns the string vector that is returned, and is responsible for deleting it.
Parameters
tokenizeSrc String to be tokenized
manager The MemoryManager to use to allocate objects
Returns
a vector of all the tokenized string
tokenizeString() [2/6]
static BaseRefVectorOf<XMLCh>* XMLString::tokenizeString (const XMLCh *const tokenizeSrc, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Break a string into tokens with space as delimiter, and stored in a string vector. The caller owns the string vector that is returned, and is responsible for deleting it.
Parameters
tokenizeSrc String to be tokenized
manager The MemoryManager to use to allocate objects
Returns
a vector of all the tokenized string
tokenizeString() [3/6]
static BaseRefVectorOf<XMLCh>* XMLString::tokenizeString (const XMLCh *const tokenizeSrc, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Break a string into tokens with space as delimiter, and stored in a string vector. The caller owns the string vector that is returned, and is responsible for deleting it.
Parameters
tokenizeSrc String to be tokenized
manager The MemoryManager to use to allocate objects
Returns
a vector of all the tokenized string
tokenizeString() [4/6]
static BaseRefVectorOf<XMLCh>* XMLString::tokenizeString (const XMLCh *const tokenizeSrc, XMLCh delimiter, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Break a string into tokens with the given character as delimiter, and stored in a string vector. The caller owns the string vector that is returned, and is responsible for deleting it.
Parameters
tokenizeSrc String to be tokenized
delimiter Delimiter character
manager The MemoryManager to use to allocate objects
Returns
a vector of all the tokenized string
tokenizeString() [5/6]
static BaseRefVectorOf<XMLCh>* XMLString::tokenizeString (const XMLCh *const tokenizeSrc, XMLCh delimiter, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Break a string into tokens with the given character as delimiter, and stored in a string vector. The caller owns the string vector that is returned, and is responsible for deleting it.
Parameters
tokenizeSrc String to be tokenized
delimiter Delimiter character
manager The MemoryManager to use to allocate objects
Returns
a vector of all the tokenized string
tokenizeString() [6/6]
static BaseRefVectorOf<XMLCh>* XMLString::tokenizeString (const XMLCh *const tokenizeSrc, XMLCh delimiter, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Break a string into tokens with the given character as delimiter, and stored in a string vector. The caller owns the string vector that is returned, and is responsible for deleting it.
Parameters
tokenizeSrc String to be tokenized
delimiter Delimiter character
manager The MemoryManager to use to allocate objects
Returns
a vector of all the tokenized string
transcode() [1/12]
static XMLCh* XMLString::transcode (const char *const toTranscode, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page
NOTE: The returned buffer is dynamically allocated and is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toTranscode The string to be transcoded
manager The MemoryManager to use to allocate objects
Returns
Returns the transcoded string
See also
XMLString::release(char**, MemoryManager*)
transcode() [2/12]
static XMLCh* XMLString::transcode (const char *const toTranscode, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page
NOTE: The returned buffer is dynamically allocated and is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toTranscode The string to be transcoded
manager The MemoryManager to use to allocate objects
Returns
Returns the transcoded string
See also
XMLString::release(char**, MemoryManager*)
transcode() [3/12]
static XMLCh* XMLString::transcode (const char *const toTranscode, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page
NOTE: The returned buffer is dynamically allocated and is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toTranscode The string to be transcoded
manager The MemoryManager to use to allocate objects
Returns
Returns the transcoded string
See also
XMLString::release(char**, MemoryManager*)
transcode() [4/12]
static bool XMLString::transcode (const char *const toTranscode, XMLCh *const toFill, const XMLSize_t maxChars, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page (DEPRECATED)
Parameters
toTranscode The string tobe transcoded
toFill The buffer that is filled with the transcoded value. The size of this buffer should atleast be 'maxChars + 1'.
maxChars The maximum number of characters that the output buffer can hold (not including the null, which is why toFill should be at least maxChars+1.).
manager The MemoryManager to use to allocate objects
Returns
Returns true if successful, false if there was an error
transcode() [5/12]
static bool XMLString::transcode (const char *const toTranscode, XMLCh *const toFill, const XMLSize_t maxChars, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page (DEPRECATED)
Parameters
toTranscode The string tobe transcoded
toFill The buffer that is filled with the transcoded value. The size of this buffer should atleast be 'maxChars + 1'.
maxChars The maximum number of characters that the output buffer can hold (not including the null, which is why toFill should be at least maxChars+1.).
manager The MemoryManager to use to allocate objects
Returns
Returns true if successful, false if there was an error
transcode() [6/12]
static bool XMLString::transcode (const char *const toTranscode, XMLCh *const toFill, const XMLSize_t maxChars, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page (DEPRECATED)
Parameters
toTranscode The string tobe transcoded
toFill The buffer that is filled with the transcoded value. The size of this buffer should atleast be 'maxChars + 1'.
maxChars The maximum number of characters that the output buffer can hold (not including the null, which is why toFill should be at least maxChars+1.).
manager The MemoryManager to use to allocate objects
Returns
Returns true if successful, false if there was an error
transcode() [7/12]
static bool XMLString::transcode (const XMLCh *const toTranscode, char *const toFill, const XMLSize_t maxChars, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page (DEPRECATED)
Be aware that when transcoding to an external encoding, that each Unicode char can create multiple output bytes. So you cannot assume a one to one correspondence of input chars to output bytes.
Parameters
toTranscode The string tobe transcoded
toFill The buffer that is filled with the transcoded value. The size of this buffer should atleast be 'maxChars + 1'.
maxChars The maximum number of bytes that the output buffer can hold (not including the null, which is why toFill should be at least maxChars+1.).
manager The MemoryManager to use to allocate objects
Returns
Returns true if successful, false if there was an error
transcode() [8/12]
static bool XMLString::transcode (const XMLCh *const toTranscode, char *const toFill, const XMLSize_t maxChars, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page (DEPRECATED)
Be aware that when transcoding to an external encoding, that each Unicode char can create multiple output bytes. So you cannot assume a one to one correspondence of input chars to output bytes.
Parameters
toTranscode The string tobe transcoded
toFill The buffer that is filled with the transcoded value. The size of this buffer should atleast be 'maxChars + 1'.
maxChars The maximum number of bytes that the output buffer can hold (not including the null, which is why toFill should be at least maxChars+1.).
manager The MemoryManager to use to allocate objects
Returns
Returns true if successful, false if there was an error
transcode() [9/12]
static bool XMLString::transcode (const XMLCh *const toTranscode, char *const toFill, const XMLSize_t maxChars, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page (DEPRECATED)
Be aware that when transcoding to an external encoding, that each Unicode char can create multiple output bytes. So you cannot assume a one to one correspondence of input chars to output bytes.
Parameters
toTranscode The string tobe transcoded
toFill The buffer that is filled with the transcoded value. The size of this buffer should atleast be 'maxChars + 1'.
maxChars The maximum number of bytes that the output buffer can hold (not including the null, which is why toFill should be at least maxChars+1.).
manager The MemoryManager to use to allocate objects
Returns
Returns true if successful, false if there was an error
transcode() [10/12]
static char* XMLString::transcode (const XMLCh *const toTranscode, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page
NOTE: The returned buffer is dynamically allocated and is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toTranscode The string to be transcoded
manager The MemoryManager to use to allocate objects
Returns
Returns the transcoded string
See also
XMLString::release(XMLCh**, MemoryManager*)
Referenced by XMLScanner::setExternalNoNamespaceSchemaLocation(), and XMLScanner::setExternalSchemaLocation().
transcode() [11/12]
static char* XMLString::transcode (const XMLCh *const toTranscode, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page
NOTE: The returned buffer is dynamically allocated and is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toTranscode The string to be transcoded
manager The MemoryManager to use to allocate objects
Returns
Returns the transcoded string
See also
XMLString::release(XMLCh**, MemoryManager*)
transcode() [12/12]
static char* XMLString::transcode (const XMLCh *const toTranscode, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) static
Transcodes a string to native code-page
NOTE: The returned buffer is dynamically allocated and is the responsibility of the caller to delete it when not longer needed. You can call XMLString::release to release this returned buffer.
Parameters
toTranscode The string to be transcoded
manager The MemoryManager to use to allocate objects
Returns
Returns the transcoded string
See also
XMLString::release(XMLCh**, MemoryManager*)
trim() [1/6]
static void XMLString::trim (char *const toTrim) static
Trims off extra space characters from the start and end of the string, moving the non-space string content back to the start.
Parameters
toTrim The string to be trimmed. On return this contains the trimmed string
trim() [2/6]
static void XMLString::trim (char *const toTrim) static
Trims off extra space characters from the start and end of the string, moving the non-space string content back to the start.
Parameters
toTrim The string to be trimmed. On return this contains the trimmed string
trim() [3/6]
static void XMLString::trim (char *const toTrim) static
Trims off extra space characters from the start and end of the string, moving the non-space string content back to the start.
Parameters
toTrim The string to be trimmed. On return this contains the trimmed string
trim() [4/6]
static void XMLString::trim (XMLCh *const toTrim) static
Trims off extra space characters from the start and end of the string, moving the non-space string content back to the start.
Parameters
toTrim The string to be trimmed. On return this contains the trimmed string
trim() [5/6]
static void XMLString::trim (XMLCh *const toTrim) static
Trims off extra space characters from the start and end of the string, moving the non-space string content back to the start.
Parameters
toTrim The string to be trimmed. On return this contains the trimmed string
trim() [6/6]
static void XMLString::trim (XMLCh *const toTrim) static
Trims off extra space characters from the start and end of the string, moving the non-space string content back to the start.
Parameters
toTrim The string to be trimmed. On return this contains the trimmed string
upperCase() [1/3]
static void XMLString::upperCase (XMLCh *const toUpperCase) static
Converts a string to uppercase
Parameters
toUpperCase The string which needs to be converted to uppercase. On return, this buffer also holds the converted uppercase string
upperCase() [2/3]
static void XMLString::upperCase (XMLCh *const toUpperCase) static
Converts a string to uppercase
Parameters
toUpperCase The string which needs to be converted to uppercase. On return, this buffer also holds the converted uppercase string
upperCase() [3/3]
static void XMLString::upperCase (XMLCh *const toUpperCase) static
Converts a string to uppercase
Parameters
toUpperCase The string which needs to be converted to uppercase. On return, this buffer also holds the converted uppercase string
upperCaseASCII() [1/3]
static void XMLString::upperCaseASCII (XMLCh *const toUpperCase) static
Converts a string to uppercase The routine only uppercases A to Z (other characters not changed).
Parameters
toUpperCase The string which needs to be converted to uppercase. On return, this buffer also holds the converted uppercase string
upperCaseASCII() [2/3]
static void XMLString::upperCaseASCII (XMLCh *const toUpperCase) static
Converts a string to uppercase The routine only uppercases A to Z (other characters not changed).
Parameters
toUpperCase The string which needs to be converted to uppercase. On return, this buffer also holds the converted uppercase string
upperCaseASCII() [3/3]
static void XMLString::upperCaseASCII (XMLCh *const toUpperCase) static
Converts a string to uppercase The routine only uppercases A to Z (other characters not changed).
Parameters
toUpperCase The string which needs to be converted to uppercase. On return, this buffer also holds the converted uppercase string
validateRegion() [1/3]
bool XMLString::validateRegion (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) inline static private
Called by regionMatches/regionIMatches to validate that we have a valid input
Definition at line 1508 of file XMLString.hpp.
References stringLen().
validateRegion() [2/3]
static bool XMLString::validateRegion (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) static private
Called by regionMatches/regionIMatches to validate that we have a valid input
validateRegion() [3/3]
static bool XMLString::validateRegion (const XMLCh *const str1, const int offset1, const XMLCh *const str2, const int offset2, const XMLSize_t charCount) static private
Called by regionMatches/regionIMatches to validate that we have a valid input
Friends And Related Function Documentation
XMLPlatformUtils
XMLPlatformUtils friend
Definition at line 1445 of file XMLString.hpp.
Member Data Documentation
fgMemoryManager
static MemoryManager * XMLString::fgMemoryManager static private
Definition at line 1443 of file XMLString.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/XMLString.hpp