Seamly2D: CMNode Class Reference
CMNode Class Reference abstract
#include <CMNode.hpp>
Public Types
enum { epsilonNode = UINT_MAX - 1 }
enum { epsilonNode = UINT_MAX - 1 }
enum { epsilonNode = UINT_MAX - 1 }
Public Member Functions
CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~CMNode ()
virtual void orphanChild ()=0
ContentSpecNode::NodeTypes getType () const
const CMStateSet & getFirstPos ()
const CMStateSet & getLastPos ()
bool isNullable () const
CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~CMNode ()
virtual void orphanChild ()=0
ContentSpecNode::NodeTypes getType () const
const CMStateSet & getFirstPos ()
const CMStateSet & getLastPos ()
bool isNullable () const
CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~CMNode ()
virtual void orphanChild ()=0
ContentSpecNode::NodeTypes getType () const
const CMStateSet & getFirstPos ()
const CMStateSet & getLastPos ()
bool isNullable () const
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Protected Member Functions
virtual void calcFirstPos (CMStateSet &toUpdate) const =0
virtual void calcLastPos (CMStateSet &toUpdate) const =0
virtual void calcFirstPos (CMStateSet &toUpdate) const =0
virtual void calcLastPos (CMStateSet &toUpdate) const =0
virtual void calcFirstPos (CMStateSet &toUpdate) const =0
virtual void calcLastPos (CMStateSet &toUpdate) const =0
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Protected Attributes
MemoryManager * fMemoryManager
bool fIsNullable
Private Member Functions
CMNode ()
CMNode (const CMNode &)
CMNode & operator= (const CMNode &)
CMNode ()
CMNode (const CMNode &)
CMNode & operator= (const CMNode &)
CMNode ()
CMNode (const CMNode &)
CMNode & operator= (const CMNode &)
Private Attributes
ContentSpecNode::NodeTypes fType
CMStateSet * fFirstPos
CMStateSet * fLastPos
unsigned int fMaxStates
Detailed Description
Definition at line 32 of file CMNode.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
epsilonNode
Definition at line 35 of file CMNode.hpp.
anonymous enum
anonymous enum
Enumerator
epsilonNode
Definition at line 35 of file CMNode.hpp.
anonymous enum
anonymous enum
Enumerator
epsilonNode
Definition at line 35 of file CMNode.hpp.
Constructor & Destructor Documentation
CMNode() [1/9]
CMNode::CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 129 of file CMNode.hpp.
~CMNode() [1/3]
CMNode::~CMNode () inline virtual
Definition at line 142 of file CMNode.hpp.
References fFirstPos, and fLastPos.
CMNode() [2/9]
CMNode::CMNode () private
CMNode() [3/9]
CMNode::CMNode (const CMNode &) private
CMNode() [4/9]
CMNode::CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~CMNode() [2/3]
virtual CMNode::~CMNode () virtual
CMNode() [5/9]
CMNode::CMNode () private
CMNode() [6/9]
CMNode::CMNode (const CMNode &) private
CMNode() [7/9]
CMNode::CMNode (const ContentSpecNode::NodeTypes type, unsigned int maxStates, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~CMNode() [3/3]
virtual CMNode::~CMNode () virtual
CMNode() [8/9]
CMNode::CMNode () private
CMNode() [9/9]
CMNode::CMNode (const CMNode &) private
Member Function Documentation
calcFirstPos() [1/3]
virtual void CMNode::calcFirstPos (CMStateSet & toUpdate) const protected pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
Referenced by getFirstPos().
calcFirstPos() [2/3]
virtual void CMNode::calcFirstPos (CMStateSet & toUpdate) const protected pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
calcFirstPos() [3/3]
virtual void CMNode::calcFirstPos (CMStateSet & toUpdate) const protected pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
calcLastPos() [1/3]
virtual void CMNode::calcLastPos (CMStateSet & toUpdate) const protected pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
Referenced by getLastPos().
calcLastPos() [2/3]
virtual void CMNode::calcLastPos (CMStateSet & toUpdate) const protected pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
calcLastPos() [3/3]
virtual void CMNode::calcLastPos (CMStateSet & toUpdate) const protected pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
getFirstPos() [1/3]
const CMStateSet & CMNode::getFirstPos () inline
Definition at line 158 of file CMNode.hpp.
References calcFirstPos(), fFirstPos, fMaxStates, and fMemoryManager.
getFirstPos() [2/3]
const CMStateSet& CMNode::getFirstPos ()
getFirstPos() [3/3]
const CMStateSet& CMNode::getFirstPos ()
getLastPos() [1/3]
const CMStateSet & CMNode::getLastPos () inline
Definition at line 172 of file CMNode.hpp.
References calcLastPos(), fLastPos, fMaxStates, and fMemoryManager.
getLastPos() [2/3]
const CMStateSet& CMNode::getLastPos ()
getLastPos() [3/3]
const CMStateSet& CMNode::getLastPos ()
getType() [1/3]
ContentSpecNode::NodeTypes CMNode::getType () const inline
Definition at line 153 of file CMNode.hpp.
References fType.
getType() [2/3]
ContentSpecNode::NodeTypes CMNode::getType () const
getType() [3/3]
ContentSpecNode::NodeTypes CMNode::getType () const
isNullable() [1/3]
bool CMNode::isNullable () const inline
Definition at line 186 of file CMNode.hpp.
References fIsNullable.
Referenced by CMLeaf::calcFirstPos(), and CMLeaf::calcLastPos().
isNullable() [2/3]
bool CMNode::isNullable () const
isNullable() [3/3]
bool CMNode::isNullable () const
operator=() [1/3]
CMNode& CMNode::operator= (const CMNode &) private
operator=() [2/3]
CMNode& CMNode::operator= (const CMNode &) private
operator=() [3/3]
CMNode& CMNode::operator= (const CMNode &) private
orphanChild() [1/3]
virtual void CMNode::orphanChild () pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
orphanChild() [2/3]
virtual void CMNode::orphanChild () pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
orphanChild() [3/3]
virtual void CMNode::orphanChild () pure virtual
Implemented in CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, CMAny, CMUnaryOp, CMLeaf, CMBinaryOp, and CMAny.
Member Data Documentation
fFirstPos
CMStateSet * CMNode::fFirstPos private
Definition at line 116 of file CMNode.hpp.
Referenced by getFirstPos(), and ~CMNode().
fIsNullable
bool CMNode::fIsNullable protected
Definition at line 121 of file CMNode.hpp.
Referenced by CMLeaf::CMLeaf(), and isNullable().
fLastPos
CMStateSet * CMNode::fLastPos private
Definition at line 117 of file CMNode.hpp.
Referenced by getLastPos(), and ~CMNode().
fMaxStates
unsigned int CMNode::fMaxStates private
Definition at line 118 of file CMNode.hpp.
Referenced by getFirstPos(), and getLastPos().
fMemoryManager
MemoryManager * CMNode::fMemoryManager protected
Definition at line 78 of file CMNode.hpp.
Referenced by CMLeaf::CMLeaf(), getFirstPos(), and getLastPos().
fType
ContentSpecNode::NodeTypes CMNode::fType private
Definition at line 115 of file CMNode.hpp.
Referenced by getType().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/common/CMNode.hpp