Seamly2D: TST_MeasurementRegExp Class Reference
TST_MeasurementRegExp Class Reference
#include <tst_measurementregexp.h>
Public Member Functions
TST_MeasurementRegExp (quint32 systemCode, const QString &locale, QObject *parent=nullptr)
virtual ~TST_MeasurementRegExp ()
Public Member Functions inherited from TST_AbstractRegExp
TST_AbstractRegExp (const QString &locale, QObject *parent=nullptr)
virtual ~TST_AbstractRegExp ()
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Static Public Attributes
static const quint32 systemCounts = 56
Protected Member Functions
virtual void PrepareData () Q_DECL_OVERRIDE
virtual QStringList AllNames () Q_DECL_OVERRIDE
Protected Member Functions inherited from TST_AbstractRegExp
int LoadVariables (const QString &checkedLocale)
void RemoveTrVariables (const QString &checkedLocale)
void InitTrMs ()
void CallTestCheckNoEndLine ()
void CallTestCheckRegExpNames ()
void CallTestCheckIsNamesUnique ()
void CallTestCheckNoOriginalNamesInTranslation ()
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Private Slots
void initTestCase ()
void TestCheckNoEndLine_data ()
void TestCheckNoEndLine ()
void TestCheckRegExpNames_data ()
void TestCheckRegExpNames ()
void TestCheckIsNamesUnique_data ()
void TestCheckIsNamesUnique ()
void TestCheckNoOriginalNamesInTranslation_data ()
void TestCheckNoOriginalNamesInTranslation ()
void cleanupTestCase ()
Private Member Functions
int loadMeasurements (const QString &checkedLocale)
void RemoveTrMeasurements (const QString &checkedLocale)
Private Attributes
quint32 m_systemCode
QPointer< QTranslator > m_pmsTranslator
Additional Inherited Members
Protected Attributes inherited from TST_AbstractRegExp
QString m_locale
QPointer< QTranslator > m_vTranslator
VTranslateVars * m_trMs
Detailed Description
Definition at line 62 of file tst_measurementregexp.h.
Constructor & Destructor Documentation
TST_MeasurementRegExp()
TST_MeasurementRegExp::TST_MeasurementRegExp (quint32 systemCode, const QString & locale, QObject * parent = nullptr)
Definition at line 66 of file tst_measurementregexp.cpp.
~TST_MeasurementRegExp()
TST_MeasurementRegExp::~TST_MeasurementRegExp () virtual
Definition at line 74 of file tst_measurementregexp.cpp.
References m_pmsTranslator.
Member Function Documentation
AllNames()
QStringList TST_MeasurementRegExp::AllNames () protected virtual
Implements TST_AbstractRegExp.
Definition at line 186 of file tst_measurementregexp.cpp.
References AllGroupNames().
Referenced by PrepareData().
cleanupTestCase
void TST_MeasurementRegExp::cleanupTestCase () private slot
Definition at line 165 of file tst_measurementregexp.cpp.
References TST_AbstractRegExp::m_locale, RemoveTrMeasurements(), and TST_AbstractRegExp::RemoveTrVariables().
initTestCase
void TST_MeasurementRegExp::initTestCase () private slot
Definition at line 80 of file tst_measurementregexp.cpp.
References TST_AbstractRegExp::InitTrMs(), loadMeasurements(), TST_AbstractRegExp::LoadVariables(), TST_AbstractRegExp::m_locale, m_systemCode, NoError, SupportedLocales(), and systemCounts.
loadMeasurements()
int TST_MeasurementRegExp::loadMeasurements (const QString & checkedLocale) private
Definition at line 192 of file tst_measurementregexp.cpp.
References ErrorInstall, ErrorLoad, ErrorSize, m_pmsTranslator, NoError, and AbstractTest::TranslationsPath().
Referenced by initTestCase().
PrepareData()
void TST_MeasurementRegExp::PrepareData () protected virtual
Implements TST_AbstractRegExp.
Definition at line 172 of file tst_measurementregexp.cpp.
References AllNames(), and TST_AbstractRegExp::m_locale.
Referenced by TestCheckIsNamesUnique_data(), TestCheckNoEndLine_data(), TestCheckNoOriginalNamesInTranslation_data(), and TestCheckRegExpNames_data().
RemoveTrMeasurements()
void TST_MeasurementRegExp::RemoveTrMeasurements (const QString & checkedLocale) private
Definition at line 241 of file tst_measurementregexp.cpp.
References m_pmsTranslator.
Referenced by cleanupTestCase().
TestCheckIsNamesUnique
void TST_MeasurementRegExp::TestCheckIsNamesUnique () private slot
Definition at line 147 of file tst_measurementregexp.cpp.
References TST_AbstractRegExp::CallTestCheckIsNamesUnique().
TestCheckIsNamesUnique_data
void TST_MeasurementRegExp::TestCheckIsNamesUnique_data () private slot
Definition at line 141 of file tst_measurementregexp.cpp.
References PrepareData().
TestCheckNoEndLine
void TST_MeasurementRegExp::TestCheckNoEndLine () private slot
Definition at line 123 of file tst_measurementregexp.cpp.
References TST_AbstractRegExp::CallTestCheckNoEndLine().
TestCheckNoEndLine_data
void TST_MeasurementRegExp::TestCheckNoEndLine_data () private slot
Definition at line 117 of file tst_measurementregexp.cpp.
References PrepareData().
TestCheckNoOriginalNamesInTranslation
void TST_MeasurementRegExp::TestCheckNoOriginalNamesInTranslation () private slot
Definition at line 159 of file tst_measurementregexp.cpp.
References TST_AbstractRegExp::CallTestCheckNoOriginalNamesInTranslation().
TestCheckNoOriginalNamesInTranslation_data
void TST_MeasurementRegExp::TestCheckNoOriginalNamesInTranslation_data () private slot
Definition at line 153 of file tst_measurementregexp.cpp.
References PrepareData().
TestCheckRegExpNames
void TST_MeasurementRegExp::TestCheckRegExpNames () private slot
Definition at line 135 of file tst_measurementregexp.cpp.
References TST_AbstractRegExp::CallTestCheckRegExpNames().
TestCheckRegExpNames_data
void TST_MeasurementRegExp::TestCheckRegExpNames_data () private slot
Definition at line 129 of file tst_measurementregexp.cpp.
References PrepareData().
Member Data Documentation
m_pmsTranslator
QPointer<QTranslator> TST_MeasurementRegExp::m_pmsTranslator private
Definition at line 91 of file tst_measurementregexp.h.
Referenced by loadMeasurements(), RemoveTrMeasurements(), and ~TST_MeasurementRegExp().
m_systemCode
quint32 TST_MeasurementRegExp::m_systemCode private
Definition at line 90 of file tst_measurementregexp.h.
Referenced by initTestCase().
systemCounts
const quint32 TST_MeasurementRegExp::systemCounts = 56 static
Definition at line 69 of file tst_measurementregexp.h.
Referenced by initTestCase(), and main().
The documentation for this class was generated from the following files:
src/test/TranslationsTest/tst_measurementregexp.h
src/test/TranslationsTest/tst_measurementregexp.cpp