Seamly2D: ShowDoublePointName Class Reference
ShowDoublePointName Class Reference
#include <showdoublepointname.h>
Public Member Functions
ShowDoublePointName (VAbstractPattern *doc, quint32 toolId, quint32 pointId, bool visible, ShowDoublePoint type, QUndoCommand *parent=nullptr)
virtual ~ShowDoublePointName ()=default
virtual void undo () override
virtual void redo () override
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Member Functions
void setVisibility (bool visible)
Private Attributes
bool m_visible
bool m_oldVisible
QGraphicsScene * m_scene
ShowDoublePoint m_type
quint32 m_idTool
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 34 of file showdoublepointname.h.
Constructor & Destructor Documentation
ShowDoublePointName()
ShowDoublePointName::ShowDoublePointName (VAbstractPattern * doc, quint32 toolId, quint32 pointId, bool visible, ShowDoublePoint type, QUndoCommand * parent = nullptr)
Definition at line 35 of file showdoublepointname.cpp.
References AttrShowPointName1, AttrShowPointName2, VUndoCommand::doc, VDomDocument::elementById(), FirstPoint, VDomDocument::getParameterBool(), m_idTool, m_oldVisible, VUndoCommand::nodeId, VAbstractPattern::TagPoint, and trueStr.
~ShowDoublePointName()
virtual ShowDoublePointName::~ShowDoublePointName () virtual default
Member Function Documentation
redo()
void ShowDoublePointName::redo () override virtual
Definition at line 83 of file showdoublepointname.cpp.
References m_visible, and setVisibility().
setVisibility()
void ShowDoublePointName::setVisibility (bool visible) private
Definition at line 91 of file showdoublepointname.cpp.
References AttrShowPointName1, AttrShowPointName2, VUndoCommand::doc, VDomDocument::elementById(), FirstPoint, VAbstractPattern::getTool(), m_idTool, m_scene, m_type, VMainGraphicsView::NewSceneRect(), VUndoCommand::nodeId, qApp, VDomDocument::SetAttribute(), and VAbstractPattern::TagPoint.
Referenced by redo(), and undo().
undo()
void ShowDoublePointName::undo () override virtual
Definition at line 75 of file showdoublepointname.cpp.
References m_oldVisible, and setVisibility().
Member Data Documentation
m_idTool
quint32 ShowDoublePointName::m_idTool private
Definition at line 52 of file showdoublepointname.h.
Referenced by setVisibility(), and ShowDoublePointName().
m_oldVisible
bool ShowDoublePointName::m_oldVisible private
Definition at line 48 of file showdoublepointname.h.
Referenced by ShowDoublePointName(), and undo().
m_scene
QGraphicsScene* ShowDoublePointName::m_scene private
Definition at line 50 of file showdoublepointname.h.
Referenced by setVisibility().
m_type
ShowDoublePoint ShowDoublePointName::m_type private
Definition at line 51 of file showdoublepointname.h.
Referenced by setVisibility().
m_visible
bool ShowDoublePointName::m_visible private
Definition at line 47 of file showdoublepointname.h.
Referenced by redo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/label/showdoublepointname.h
src/libs/vtools/undocommands/label/showdoublepointname.cpp