Seamly2D: qmu::QmuParser Class Reference
qmu::QmuParser Class Reference
Mathematical expressions parser.
#include <qmuparser.h>
Public Member Functions
QmuParser ()
Constructor.
virtual void InitCharSets () Q_DECL_OVERRIDE
Define the character sets.
virtual void InitFun () Q_DECL_OVERRIDE
Initialize the default functions.
virtual void InitConst () Q_DECL_OVERRIDE
Initialize constants.
virtual void InitOprt () Q_DECL_OVERRIDE
Initialize operators.
virtual void OnDetectVar (const QString &pExpr, int &nStart, int &nEnd) Q_DECL_OVERRIDE
qreal Diff (qreal *a_Var, qreal a_fPos, qreal a_fEpsilon=0) const
Numerically differentiate with regard to a variable.
Public Member Functions inherited from qmu::QmuParserBase
QmuParserBase ()
Constructor.
QmuParserBase (const QmuParserBase &a_Parser)
Copy constructor.
QmuParserBase & operator= (const QmuParserBase &a_Parser)
Assignement operator.
virtual ~QmuParserBase ()
qreal Eval () const
Calculate the result.
qreal * Eval (int &nStackSize) const
Evaluate an expression containing comma seperated subexpressions.
void Eval (qreal *results, int nBulkSize) const
int GetNumResults () const
Return the number of results on the calculation stack.
void SetExpr (const QString &a_sExpr)
Set the formula.
void SetVarFactory (facfun_type a_pFactory, void *pUserData=nullptr)
Set a function that can create variable pointer for unknown expression variables.
void ResetLocale ()
Resets the locale.
void EnableOptimizer (bool a_bIsOn=true)
Enable or disable the formula optimization feature.
void EnableBuiltInOprt (bool a_bIsOn=true)
Enable or disable the built in binary operators.
bool HasBuiltInOprt () const
Query status of built in variables.
void AddValIdent (identfun_type a_pCallback)
Add a value parsing function.
void DefineOprt (const QString &a_sName, fun_type2 a_pFun, unsigned a_iPrec=0, EOprtAssociativity a_eAssociativity=oaLEFT, bool a_bAllowOpt=false)
Define a binary operator.
void DefineConst (const QString &a_sName, qreal a_fVal)
Add a user defined constant.
void DefineStrConst (const QString &a_strName, const QString &a_strVal)
Define a new string constant.
void DefineVar (const QString &a_sName, qreal *a_pVar)
Add a user defined variable.
void DefinePostfixOprt (const QString &a_sFun, fun_type1 a_pFun, bool a_bAllowOpt=true)
Add a user defined operator.
void DefineInfixOprt (const QString &a_sName, fun_type1 a_pFun, int a_iPrec=prINFIX, bool a_bAllowOpt=true)
Add a user defined operator.
void ClearVar ()
Clear all user defined variables.
void ClearFun ()
Clear all functions.
void ClearConst ()
Clear all user defined constants.
void ClearInfixOprt ()
Clear the user defined Prefix operators.
void ClearPostfixOprt ()
Clear all user defined postfix operators.
void ClearOprt ()
Clear all user defined binary operators.
void RemoveVar (const QString &a_strVarName)
Remove a variable from internal storage.
const varmap_type & GetUsedVar () const
Return a map containing the used variables only.
const varmap_type & GetVar () const
Return a map containing the used variables only.
const valmap_type & GetConst () const
Return a map containing all parser constants.
const QString & GetExpr () const
Retrieve the formula.
const funmap_type & GetFunDef () const
Return prototypes of all parser functions.
QMap< int, QString > GetTokens () const
QMap< int, QString > GetNumbers () const
void DefineNameChars (const QString &a_szCharset)
Define the set of valid characters to be used in names of functions, variables, constants.
void DefineOprtChars (const QString &a_szCharset)
Define the set of valid characters to be used in names of binary operators and postfix operators.
void DefineInfixOprtChars (const QString &a_szCharset)
Define the set of valid characters to be used in names of infix operators.
const QString & ValidNameChars () const
Virtual function that defines the characters allowed in name identifiers.
const QString & ValidOprtChars () const
Virtual function that defines the characters allowed in operator definitions.
const QString & ValidInfixOprtChars () const
Virtual function that defines the characters allowed in infix operator definitions.
void SetArgSep (char_type cArgSep)
Set argument separator.
QChar GetArgSep () const
Get the argument separator character.
void Q_NORETURN Error (EErrorCodes a_iErrc, int a_iPos=-1, const QString &a_sTok=QString()) const
Create an error containing the parse error position.
template<typename T >
void DefineFun (const QString &a_strName, T a_pFun, bool a_bAllowOpt=true)
Define a parser function without arguments.
void setAllowSubexpressions (bool value)
QLocale getLocale () const
void setLocale (const QLocale &value)
QChar getDecimalPoint () const
void setDecimalPoint (const QChar &c)
QChar getThousandsSeparator () const
void setThousandsSeparator (const QChar &c)
Static Protected Member Functions
static int IsVal (const QString &a_szExpr, int *a_iPos, qreal *a_fVal, const QLocale &locale, const QChar &decimal, const QChar &thousand)
Default value recognition callback.
static qreal Sinh (qreal)
static qreal Cosh (qreal)
static qreal Tanh (qreal)
static qreal ASinh (qreal)
static qreal ACosh (qreal)
static qreal ATanh (qreal)
static qreal DegreeToRadian (qreal)
static qreal RadianToDegree (qreal)
static qreal SinD (qreal)
static qreal CosD (qreal)
static qreal TanD (qreal)
static qreal ASinD (qreal)
static qreal ACosD (qreal)
static qreal ATanD (qreal)
static qreal Log2 (qreal)
static qreal Log10 (qreal)
static qreal Abs (qreal)
static qreal Rint (qreal)
static qreal Sign (qreal)
static qreal FMod (qreal, qreal)
static qreal UnaryMinus (qreal v)
Callback for the unary minus operator.
static qreal Sum (const qreal *, int)
Callback for adding multiple values.
static qreal Avg (const qreal *, int)
Callback for averaging multiple values.
static qreal Min (const qreal *, int)
Callback for determining the minimum value out of a vector.
static qreal Max (const qreal *, int)
Callback for determining the maximum value out of a vector.
Additional Inherited Members
Static Public Member Functions inherited from qmu::QmuParserBase
static void EnableDebugDump (bool bDumpCmd, bool bDumpStack)
Enable the dumping of bytecode amd stack content on the console.
static QString GetVersion (EParserVersionInfo eInfo=pviFULL)
Returns the version of muparser.
static const QStringList & GetOprtDef ()
Get the default symbols used for the built in operators.
Protected Member Functions inherited from qmu::QmuParserBase
void Init ()
Initialize user defined functions.
Protected Attributes inherited from qmu::QmuParserBase
QLocale m_locale
The locale used by the parser.
QChar m_decimalPoint
QChar m_thousandsSeparator
Static Protected Attributes inherited from qmu::QmuParserBase
static const QStringList c_DefaultOprt
Identifiers for built in binary operators.
static bool g_DbgDumpCmdCode = false
static bool g_DbgDumpStack = false
Detailed Description
Mathematical expressions parser.
Standard implementation of the mathematical expressions parser. Can be used as a reference implementation for subclassing the parser.
(C) 2011 Ingo Berg
muparser(at)gmx.de
Definition at line 49 of file qmuparser.h.
Constructor & Destructor Documentation
QmuParser()
qmu::QmuParser::QmuParser ()
Constructor.
Call QmuParserBase class constructor and trigger Function, Operator and Constant initialization.
Definition at line 300 of file qmuparser.cpp.
References qmu::QmuParserBase::AddValIdent(), InitCharSets(), InitConst(), InitFun(), InitOprt(), and IsVal().
Member Function Documentation
Abs()
qreal qmu::QmuParser::Abs (qreal v) static protected
Definition at line 162 of file qmuparser.cpp.
Referenced by InitFun().
ACosD()
qreal qmu::QmuParser::ACosD (qreal v) static protected
Definition at line 114 of file qmuparser.cpp.
Referenced by InitFun().
ACosh()
qreal qmu::QmuParser::ACosh (qreal v) static protected
Definition at line 78 of file qmuparser.cpp.
Referenced by InitFun().
ASinD()
qreal qmu::QmuParser::ASinD (qreal v) static protected
Definition at line 102 of file qmuparser.cpp.
Referenced by InitFun().
ASinh()
qreal qmu::QmuParser::ASinh (qreal v) static protected
Definition at line 66 of file qmuparser.cpp.
Referenced by InitFun().
ATanD()
qreal qmu::QmuParser::ATanD (qreal v) static protected
Definition at line 126 of file qmuparser.cpp.
Referenced by InitFun().
ATanh()
qreal qmu::QmuParser::ATanh (qreal v) static protected
Definition at line 90 of file qmuparser.cpp.
Referenced by InitFun().
Avg()
qreal qmu::QmuParser::Avg (const qreal * a_afArg, int a_iArgc) static protected
Callback for averaging multiple values.
Parameters
[in] a_afArg Vector with the function arguments
[in] a_iArgc The size of a_afArg
Definition at line 212 of file qmuparser.cpp.
References translate.
Referenced by InitFun().
CosD()
qreal qmu::QmuParser::CosD (qreal v) static protected
Definition at line 108 of file qmuparser.cpp.
Referenced by InitFun().
Cosh()
qreal qmu::QmuParser::Cosh (qreal v) static protected
Definition at line 72 of file qmuparser.cpp.
Referenced by InitFun().
DegreeToRadian()
qreal qmu::QmuParser::DegreeToRadian (qreal deg) static protected
Definition at line 48 of file qmuparser.cpp.
Referenced by InitFun().
Diff()
qreal qmu::QmuParser::Diff (qreal * a_Var, qreal a_fPos, qreal a_fEpsilon = 0) const
Numerically differentiate with regard to a variable.
Parameters
[in] a_Var Pointer to the differentiation variable.
[in] a_fPos Position at which the differentiation should take place.
[in] a_fEpsilon Epsilon used for the numerical differentiation.
Numerical differentiation uses a 5 point operator yielding a 4th order formula. The default value for epsilon is 0.00074 which is numeric_limits<double>::epsilon() ^ (1/5) as suggested in the muQmuParser forum:
http://sourceforge.net/forum/forum.php?thread_id=1994611&forum_id=462843
Definition at line 444 of file qmuparser.cpp.
References qmu::QmuParserBase::Eval().
FMod()
qreal qmu::QmuParser::FMod (qreal number, qreal denom) static protected
Definition at line 180 of file qmuparser.cpp.
Referenced by InitFun().
InitCharSets()
void qmu::QmuParser::InitCharSets () virtual
Define the character sets.
See also
DefineNameChars, DefineOprtChars, DefineInfixOprtChars
This function is used for initializing the default character sets that define the characters to be useable in function and variable names and operators.
Implements qmu::QmuParserBase.
Reimplemented in qmu::QmuFormulaBase.
Definition at line 318 of file qmuparser.cpp.
References qmu::QmuParserBase::DefineInfixOprtChars(), qmu::QmuParserBase::DefineNameChars(), and qmu::QmuParserBase::DefineOprtChars().
Referenced by QmuParser().
InitConst()
void qmu::QmuParser::InitConst () virtual
Initialize constants.
By default the QmuParser recognizes two constants. Pi ("pi") and the eulerian number ("_e").
Implements qmu::QmuParserBase.
Definition at line 384 of file qmuparser.cpp.
References qmu::QmuParserBase::DefineConst().
Referenced by QmuParser().
InitFun()
void qmu::QmuParser::InitFun () virtual
Initialize the default functions.
Implements qmu::QmuParserBase.
Definition at line 329 of file qmuparser.cpp.
References Abs(), ACosD(), ACosh(), ASinD(), ASinh(), ATanD(), ATanh(), Avg(), CosD(), Cosh(), qmu::QmuParserBase::DefineFun(), DegreeToRadian(), FMod(), Log10(), Log2(), Max(), Min(), RadianToDegree(), Rint(), Sign(), SinD(), Sinh(), Sum(), TanD(), and Tanh().
Referenced by QmuParser().
InitOprt()
void qmu::QmuParser::InitOprt () virtual
Initialize operators.
By default only the unary minus operator is added.
Implements qmu::QmuParserBase.
Definition at line 396 of file qmuparser.cpp.
References qmu::QmuParserBase::DefineInfixOprt(), qmu::QmuParserBase::m_locale, and UnaryMinus().
Referenced by QmuParser().
IsVal()
int qmu::QmuParser::IsVal (const QString & a_szExpr, int * a_iPos, qreal * a_fVal, const QLocale & locale, const QChar & decimal, const QChar & thousand) static protected
Default value recognition callback.
Parameters
[in] a_szExpr Pointer to the expression
[in,out] a_iPos Pointer to an index storing the current position within the expression
[out] a_fVal Pointer where the value should be stored in case one is found.
Returns
1 if a value was found 0 otherwise.
Definition at line 277 of file qmuparser.cpp.
References ReadVal().
Referenced by QmuParser().
Log10()
qreal qmu::QmuParser::Log10 (qreal v) static protected
Definition at line 149 of file qmuparser.cpp.
References qmu::ecDOMAIN_ERROR.
Referenced by InitFun().
Log2()
qreal qmu::QmuParser::Log2 (qreal v) static protected
Definition at line 136 of file qmuparser.cpp.
References qmu::ecDOMAIN_ERROR.
Referenced by InitFun().
Max()
qreal qmu::QmuParser::Max (const qreal * a_afArg, int a_iArgc) static protected
Callback for determining the maximum value out of a vector.
Parameters
[in] a_afArg Vector with the function arguments
[in] a_iArgc The size of a_afArg
Definition at line 254 of file qmuparser.cpp.
References translate.
Referenced by InitFun().
Min()
qreal qmu::QmuParser::Min (const qreal * a_afArg, int a_iArgc) static protected
Callback for determining the minimum value out of a vector.
Parameters
[in] a_afArg Vector with the function arguments
[in] a_iArgc The size of a_afArg
Definition at line 233 of file qmuparser.cpp.
References translate.
Referenced by InitFun().
OnDetectVar()
void qmu::QmuParser::OnDetectVar (const QString & pExpr, int & nStart, int & nEnd) virtual
Reimplemented from qmu::QmuParserBase.
Definition at line 402 of file qmuparser.cpp.
RadianToDegree()
qreal qmu::QmuParser::RadianToDegree (qreal rad) static protected
Definition at line 54 of file qmuparser.cpp.
Referenced by InitFun().
Rint()
qreal qmu::QmuParser::Rint (qreal v) static protected
Definition at line 168 of file qmuparser.cpp.
Referenced by InitFun().
Sign()
qreal qmu::QmuParser::Sign (qreal v) static protected
Definition at line 174 of file qmuparser.cpp.
Referenced by InitFun().
SinD()
qreal qmu::QmuParser::SinD (qreal v) static protected
Definition at line 96 of file qmuparser.cpp.
Referenced by InitFun().
Sinh()
qreal qmu::QmuParser::Sinh (qreal v) static protected
Definition at line 60 of file qmuparser.cpp.
Referenced by InitFun().
Sum()
qreal qmu::QmuParser::Sum (const qreal * a_afArg, int a_iArgc) static protected
Callback for adding multiple values.
Parameters
[in] a_afArg Vector with the function arguments
[in] a_iArgc The size of a_afArg
Definition at line 191 of file qmuparser.cpp.
References translate.
Referenced by InitFun().
TanD()
qreal qmu::QmuParser::TanD (qreal v) static protected
Definition at line 120 of file qmuparser.cpp.
Referenced by InitFun().
Tanh()
qreal qmu::QmuParser::Tanh (qreal v) static protected
Definition at line 84 of file qmuparser.cpp.
Referenced by InitFun().
UnaryMinus()
qreal qmu::QmuParser::UnaryMinus (qreal v) inline static protected
Callback for the unary minus operator.
Parameters
v The value to negate
Returns
-v
Definition at line 104 of file qmuparser.h.
Referenced by InitOprt().
The documentation for this class was generated from the following files:
src/libs/qmuparser/qmuparser.h
src/libs/qmuparser/qmuparser.cpp