Seamly2D: TST_VPiece Class Reference
TST_VPiece Class Reference
#include <tst_vpiece.h>
Public Member Functions
TST_VPiece (QObject *parent=nullptr)
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Private Slots
void ClearLoop ()
void Issue620 ()
Additional Inherited Members
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Detailed Description
Definition at line 57 of file tst_vpiece.h.
Constructor & Destructor Documentation
TST_VPiece()
TST_VPiece::TST_VPiece (QObject * parent = nullptr) explicit
Definition at line 63 of file tst_vpiece.cpp.
Member Function Documentation
ClearLoop
void TST_VPiece::ClearLoop () private slot
Definition at line 69 of file tst_vpiece.cpp.
References VPiecePath::Append(), AbstractTest::Comparison(), VPiecePath::CountNodes(), VPiece::GetPath(), Mm, NodePoint, NodeSplinePath, qApp, VPiece::SeamAllowancePoints(), VAbstractPiece::SetSAWidth(), and VAbstractPiece::SetSeamAllowance().
Issue620
void TST_VPiece::Issue620 () private slot
Definition at line 175 of file tst_vpiece.cpp.
References VPiecePath::Append(), Cm, AbstractTest::Comparison(), VPiece::GetPath(), VPiece::MainPathPoints(), NodePoint, NodeSpline, NodeSplinePath, qApp, VAbstractPiece::SetSAWidth(), and VAbstractPiece::SetSeamAllowance().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vpiece.h
src/test/Seamly2DTest/tst_vpiece.cpp