Seamly2D: SeamlyWelcomeDialog Class Reference
SeamlyWelcomeDialog Class Reference
#include <welcome_dialog.h>
Public Member Functions
SeamlyWelcomeDialog (QWidget *parent=nullptr)
~SeamlyWelcomeDialog ()
void apply ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
void seperatorChanged ()
Private Member Functions
void initUnits (const MeasurementsType &type)
Private Attributes
Ui::SeamlyWelcomeDialog * ui
bool m_langChanged
bool m_selectionSoundChanged
VSettings * settings
Detailed Description
Definition at line 38 of file welcome_dialog.h.
Constructor & Destructor Documentation
SeamlyWelcomeDialog()
SeamlyWelcomeDialog::SeamlyWelcomeDialog (QWidget * parent = nullptr) explicit
Definition at line 36 of file welcome_dialog.cpp.
References apply(), VCommonSettings::getOsSeparator(), VCommonSettings::getShowWelcome(), VCommonSettings::getSound(), Individual, InitLanguages(), initUnits(), SCASSERT, seperatorChanged(), settings, and ui.
~SeamlyWelcomeDialog()
SeamlyWelcomeDialog::~SeamlyWelcomeDialog ()
Definition at line 82 of file welcome_dialog.cpp.
References ui.
Member Function Documentation
apply()
void SeamlyWelcomeDialog::apply ()
Definition at line 89 of file welcome_dialog.cpp.
References VCommonSettings::getOsSeparator(), m_langChanged, m_selectionSoundChanged, VCommonSettings::setLocale(), VCommonSettings::setOsSeparator(), VCommonSettings::setSelectionSound(), VCommonSettings::setShowWelcome(), settings, VCommonSettings::SetUnit(), and ui.
Referenced by SeamlyWelcomeDialog().
changeEvent()
void SeamlyWelcomeDialog::changeEvent (QEvent * event) protected virtual
Definition at line 116 of file welcome_dialog.cpp.
References ui.
initUnits()
void SeamlyWelcomeDialog::initUnits (const MeasurementsType & type) private
Definition at line 142 of file welcome_dialog.cpp.
References VCommonSettings::getUnit(), settings, ui, unitCM, unitINCH, and unitMM.
Referenced by SeamlyWelcomeDialog().
seperatorChanged()
void SeamlyWelcomeDialog::seperatorChanged () protected
Definition at line 130 of file welcome_dialog.cpp.
References ui.
Referenced by SeamlyWelcomeDialog().
Member Data Documentation
m_langChanged
bool SeamlyWelcomeDialog::m_langChanged private
Definition at line 54 of file welcome_dialog.h.
Referenced by apply().
m_selectionSoundChanged
bool SeamlyWelcomeDialog::m_selectionSoundChanged private
Definition at line 55 of file welcome_dialog.h.
Referenced by apply().
settings
VSettings* SeamlyWelcomeDialog::settings private
Definition at line 56 of file welcome_dialog.h.
Referenced by apply(), initUnits(), and SeamlyWelcomeDialog().
ui
Ui::SeamlyWelcomeDialog* SeamlyWelcomeDialog::ui private
Definition at line 53 of file welcome_dialog.h.
Referenced by apply(), changeEvent(), initUnits(), SeamlyWelcomeDialog(), seperatorChanged(), and ~SeamlyWelcomeDialog().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/welcome_dialog.h
src/app/seamly2d/dialogs/welcome_dialog.cpp