Seamly2D: TST_VTranslateVars Class Reference
TST_VTranslateVars Class Reference
#include <tst_vtranslatevars.h>
Public Member Functions
TST_VTranslateVars (QObject *parent=nullptr)
Private Slots
void initTestCase ()
void TestFormulaFromUser_data ()
void TestFormulaFromUser ()
void TestFormulaToUser_data ()
void TestFormulaToUser ()
void cleanupTestCase ()
Private Member Functions
void PrepareValFromUser (double d, const QLocale &locale)
void PrepareValToUser (double d, const QLocale &locale)
void PrepareVal (const QString &inputFormula, const QString &outputFormula, const QLocale &locale)
Private Attributes
VTranslateVars * m_trMs
QLocale m_systemLocale
Detailed Description
Definition at line 61 of file tst_vtranslatevars.h.
Constructor & Destructor Documentation
TST_VTranslateVars()
TST_VTranslateVars::TST_VTranslateVars (QObject * parent = nullptr) explicit
Definition at line 60 of file tst_vtranslatevars.cpp.
Member Function Documentation
cleanupTestCase
void TST_VTranslateVars::cleanupTestCase () private slot
Definition at line 152 of file tst_vtranslatevars.cpp.
References m_systemLocale, and m_trMs.
initTestCase
void TST_VTranslateVars::initTestCase () private slot
Definition at line 68 of file tst_vtranslatevars.cpp.
References m_trMs.
PrepareVal()
void TST_VTranslateVars::PrepareVal (const QString & inputFormula, const QString & outputFormula, const QLocale & locale) private
Definition at line 177 of file tst_vtranslatevars.cpp.
Referenced by PrepareValFromUser(), and PrepareValToUser().
PrepareValFromUser()
void TST_VTranslateVars::PrepareValFromUser (double d, const QLocale & locale) private
Definition at line 159 of file tst_vtranslatevars.cpp.
References PrepareVal().
Referenced by TestFormulaFromUser_data().
PrepareValToUser()
void TST_VTranslateVars::PrepareValToUser (double d, const QLocale & locale) private
Definition at line 168 of file tst_vtranslatevars.cpp.
References PrepareVal().
Referenced by TestFormulaToUser_data().
TestFormulaFromUser
void TST_VTranslateVars::TestFormulaFromUser () private slot
Definition at line 90 of file tst_vtranslatevars.cpp.
References VTranslateVars::FormulaFromUser(), and m_trMs.
TestFormulaFromUser_data
void TST_VTranslateVars::TestFormulaFromUser_data () private slot
Definition at line 74 of file tst_vtranslatevars.cpp.
References PrepareValFromUser().
TestFormulaToUser
void TST_VTranslateVars::TestFormulaToUser () private slot
Definition at line 129 of file tst_vtranslatevars.cpp.
References VTranslateVars::FormulaToUser(), and m_trMs.
TestFormulaToUser_data
void TST_VTranslateVars::TestFormulaToUser_data () private slot
Definition at line 113 of file tst_vtranslatevars.cpp.
References PrepareValToUser().
Member Data Documentation
m_systemLocale
QLocale TST_VTranslateVars::m_systemLocale private
Definition at line 76 of file tst_vtranslatevars.h.
Referenced by cleanupTestCase().
m_trMs
VTranslateVars* TST_VTranslateVars::m_trMs private
Definition at line 75 of file tst_vtranslatevars.h.
Referenced by cleanupTestCase(), initTestCase(), TestFormulaFromUser(), and TestFormulaToUser().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vtranslatevars.h
src/test/Seamly2DTest/tst_vtranslatevars.cpp