Seamly2D: OpFactory Class Reference
OpFactory Class Reference
#include <OpFactory.hpp>
Public Member Functions
OpFactory (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~OpFactory ()
Op * createDotOp ()
CharOp * createCharOp (XMLInt32 data)
CharOp * createAnchorOp (XMLInt32 data)
CharOp * createCaptureOp (int number, const Op *const next)
UnionOp * createUnionOp (XMLSize_t size)
ChildOp * createClosureOp (int id)
ChildOp * createNonGreedyClosureOp ()
ChildOp * createQuestionOp (bool nonGreedy)
RangeOp * createRangeOp (const Token *const token)
CharOp * createBackReferenceOp (int refNo)
StringOp * createStringOp (const XMLCh *const literal)
void reset ()
OpFactory (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~OpFactory ()
Op * createDotOp ()
CharOp * createCharOp (XMLInt32 data)
CharOp * createAnchorOp (XMLInt32 data)
CharOp * createCaptureOp (int number, const Op *const next)
UnionOp * createUnionOp (XMLSize_t size)
ChildOp * createClosureOp (int id)
ChildOp * createNonGreedyClosureOp ()
ChildOp * createQuestionOp (bool nonGreedy)
RangeOp * createRangeOp (const Token *const token)
CharOp * createBackReferenceOp (int refNo)
StringOp * createStringOp (const XMLCh *const literal)
void reset ()
OpFactory (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~OpFactory ()
Op * createDotOp ()
CharOp * createCharOp (XMLInt32 data)
CharOp * createAnchorOp (XMLInt32 data)
CharOp * createCaptureOp (int number, const Op *const next)
UnionOp * createUnionOp (XMLSize_t size)
ChildOp * createClosureOp (int id)
ChildOp * createNonGreedyClosureOp ()
ChildOp * createQuestionOp (bool nonGreedy)
RangeOp * createRangeOp (const Token *const token)
CharOp * createBackReferenceOp (int refNo)
StringOp * createStringOp (const XMLCh *const literal)
void reset ()
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
OpFactory (const OpFactory &)
OpFactory & operator= (const OpFactory &)
OpFactory (const OpFactory &)
OpFactory & operator= (const OpFactory &)
OpFactory (const OpFactory &)
OpFactory & operator= (const OpFactory &)
Private Attributes
RefVectorOf< Op > * fOpVector
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 53 of file OpFactory.hpp.
Constructor & Destructor Documentation
OpFactory() [1/6]
OpFactory::OpFactory (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~OpFactory() [1/3]
OpFactory::~OpFactory ()
OpFactory() [2/6]
OpFactory::OpFactory (const OpFactory &) private
OpFactory() [3/6]
OpFactory::OpFactory (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~OpFactory() [2/3]
OpFactory::~OpFactory ()
OpFactory() [4/6]
OpFactory::OpFactory (const OpFactory &) private
OpFactory() [5/6]
OpFactory::OpFactory (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~OpFactory() [3/3]
OpFactory::~OpFactory ()
OpFactory() [6/6]
OpFactory::OpFactory (const OpFactory &) private
Member Function Documentation
createAnchorOp() [1/3]
CharOp* OpFactory::createAnchorOp (XMLInt32 data)
createAnchorOp() [2/3]
CharOp* OpFactory::createAnchorOp (XMLInt32 data)
createAnchorOp() [3/3]
CharOp* OpFactory::createAnchorOp (XMLInt32 data)
createBackReferenceOp() [1/3]
CharOp* OpFactory::createBackReferenceOp (int refNo)
createBackReferenceOp() [2/3]
CharOp* OpFactory::createBackReferenceOp (int refNo)
createBackReferenceOp() [3/3]
CharOp* OpFactory::createBackReferenceOp (int refNo)
createCaptureOp() [1/3]
CharOp* OpFactory::createCaptureOp (int number, const Op *const next)
Referenced by RegularExpression::compileParenthesis().
createCaptureOp() [2/3]
CharOp* OpFactory::createCaptureOp (int number, const Op *const next)
createCaptureOp() [3/3]
CharOp* OpFactory::createCaptureOp (int number, const Op *const next)
createCharOp() [1/3]
CharOp* OpFactory::createCharOp (XMLInt32 data)
createCharOp() [2/3]
CharOp* OpFactory::createCharOp (XMLInt32 data)
createCharOp() [3/3]
CharOp* OpFactory::createCharOp (XMLInt32 data)
createClosureOp() [1/3]
ChildOp* OpFactory::createClosureOp (int id)
Referenced by RegularExpression::compileClosure().
createClosureOp() [2/3]
ChildOp* OpFactory::createClosureOp (int id)
createClosureOp() [3/3]
ChildOp* OpFactory::createClosureOp (int id)
createDotOp() [1/3]
Op* OpFactory::createDotOp ()
createDotOp() [2/3]
Op* OpFactory::createDotOp ()
createDotOp() [3/3]
Op* OpFactory::createDotOp ()
createNonGreedyClosureOp() [1/3]
ChildOp* OpFactory::createNonGreedyClosureOp ()
Referenced by RegularExpression::compileClosure().
createNonGreedyClosureOp() [2/3]
ChildOp* OpFactory::createNonGreedyClosureOp ()
createNonGreedyClosureOp() [3/3]
ChildOp* OpFactory::createNonGreedyClosureOp ()
createQuestionOp() [1/3]
ChildOp* OpFactory::createQuestionOp (bool nonGreedy)
Referenced by RegularExpression::compileClosure().
createQuestionOp() [2/3]
ChildOp* OpFactory::createQuestionOp (bool nonGreedy)
createQuestionOp() [3/3]
ChildOp* OpFactory::createQuestionOp (bool nonGreedy)
createRangeOp() [1/3]
RangeOp* OpFactory::createRangeOp (const Token *const token)
createRangeOp() [2/3]
RangeOp* OpFactory::createRangeOp (const Token *const token)
createRangeOp() [3/3]
RangeOp* OpFactory::createRangeOp (const Token *const token)
createStringOp() [1/3]
StringOp* OpFactory::createStringOp (const XMLCh *const literal)
createStringOp() [2/3]
StringOp* OpFactory::createStringOp (const XMLCh *const literal)
createStringOp() [3/3]
StringOp* OpFactory::createStringOp (const XMLCh *const literal)
createUnionOp() [1/3]
UnionOp* OpFactory::createUnionOp (XMLSize_t size)
Referenced by RegularExpression::compileUnion().
createUnionOp() [2/3]
UnionOp* OpFactory::createUnionOp (XMLSize_t size)
createUnionOp() [3/3]
UnionOp* OpFactory::createUnionOp (XMLSize_t size)
operator=() [1/3]
OpFactory& OpFactory::operator= (const OpFactory &) private
operator=() [2/3]
OpFactory& OpFactory::operator= (const OpFactory &) private
operator=() [3/3]
OpFactory& OpFactory::operator= (const OpFactory &) private
reset() [1/3]
void OpFactory::reset () inline
Definition at line 105 of file OpFactory.hpp.
References fOpVector, and BaseRefVectorOf< TElem >::removeAllElements().
reset() [2/3]
void OpFactory::reset ()
reset() [3/3]
void OpFactory::reset ()
Member Data Documentation
fMemoryManager
MemoryManager * OpFactory::fMemoryManager private
Definition at line 99 of file OpFactory.hpp.
fOpVector
RefVectorOf< Op > * OpFactory::fOpVector private
Definition at line 98 of file OpFactory.hpp.
Referenced by reset().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/regx/OpFactory.hpp