Seamly2D: XMLBuffer Class Reference
XMLBuffer Class Reference
#include <XMLBuffer.hpp>
Public Member Functions
Constructor
XMLBuffer (const XMLSize_t capacity=1023, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLBuffer (const XMLSize_t capacity=1023, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLBuffer (const XMLSize_t capacity=1023, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Destructor
class XMLBufBid
XMLSize_t fIndex
XMLSize_t fCapacity
XMLSize_t fFullSize
bool fUsed
MemoryManager *const fMemoryManager
XMLBufferFullHandler * fFullHandler
XMLCh * fBuffer
~XMLBuffer ()
void setFullHandler (XMLBufferFullHandler *handler, const XMLSize_t fullSize)
void append (const XMLCh toAppend)
void append (const XMLCh *const chars, const XMLSize_t count)
void append (const XMLCh *const chars)
void set (const XMLCh *const chars, const XMLSize_t count)
void set (const XMLCh *const chars)
const XMLCh * getRawBuffer () const
XMLCh * getRawBuffer ()
void reset ()
bool getInUse () const
XMLSize_t getLen () const
bool isEmpty () const
void setInUse (const bool newValue)
~XMLBuffer ()
void setFullHandler (XMLBufferFullHandler *handler, const XMLSize_t fullSize)
void append (const XMLCh toAppend)
void append (const XMLCh *const chars, const XMLSize_t count)
void append (const XMLCh *const chars)
void set (const XMLCh *const chars, const XMLSize_t count)
void set (const XMLCh *const chars)
const XMLCh * getRawBuffer () const
XMLCh * getRawBuffer ()
void reset ()
bool getInUse () const
XMLSize_t getLen () const
bool isEmpty () const
void setInUse (const bool newValue)
~XMLBuffer ()
void setFullHandler (XMLBufferFullHandler *handler, const XMLSize_t fullSize)
void append (const XMLCh toAppend)
void append (const XMLCh *const chars, const XMLSize_t count)
void append (const XMLCh *const chars)
void set (const XMLCh *const chars, const XMLSize_t count)
void set (const XMLCh *const chars)
const XMLCh * getRawBuffer () const
XMLCh * getRawBuffer ()
void reset ()
bool getInUse () const
XMLSize_t getLen () const
bool isEmpty () const
void setInUse (const bool newValue)
XMLBuffer (const XMLBuffer &)
XMLBuffer & operator= (const XMLBuffer &)
void ensureCapacity (const XMLSize_t extraNeeded)
XMLBuffer (const XMLBuffer &)
XMLBuffer & operator= (const XMLBuffer &)
void ensureCapacity (const XMLSize_t extraNeeded)
XMLBuffer (const XMLBuffer &)
XMLBuffer & operator= (const XMLBuffer &)
void ensureCapacity (const XMLSize_t extraNeeded)
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
XMLBuffer is a lightweight, expandable Unicode text buffer. Since XML is inherently theoretically unbounded in terms of the sizes of things, we very often need to have expandable buffers. The primary concern here is that appends of characters and other buffers or strings be very fast, so it always maintains the current buffer size.
The buffer is not null terminated until some asks to see the raw buffer contents. This also avoids overhead during append operations.
Definition at line 44 of file XMLBuffer.hpp.
Constructor & Destructor Documentation
XMLBuffer() [1/6]
XMLBuffer::XMLBuffer (const XMLSize_t capacity = 1023, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 53 of file XMLBuffer.hpp.
~XMLBuffer() [1/3]
XMLBuffer::~XMLBuffer () inline
Definition at line 74 of file XMLBuffer.hpp.
XMLBuffer() [2/6]
XMLBuffer::XMLBuffer (const XMLBuffer &) private
XMLBuffer() [3/6]
XMLBuffer::XMLBuffer (const XMLSize_t capacity = 1023, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 53 of file XMLBuffer.hpp.
~XMLBuffer() [2/3]
XMLBuffer::~XMLBuffer () inline
Definition at line 74 of file XMLBuffer.hpp.
XMLBuffer() [4/6]
XMLBuffer::XMLBuffer (const XMLBuffer &) private
XMLBuffer() [5/6]
XMLBuffer::XMLBuffer (const XMLSize_t capacity = 1023, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 53 of file XMLBuffer.hpp.
~XMLBuffer() [3/3]
XMLBuffer::~XMLBuffer () inline
Definition at line 74 of file XMLBuffer.hpp.
XMLBuffer() [6/6]
XMLBuffer::XMLBuffer (const XMLBuffer &) private
Member Function Documentation
append() [1/9]
void XMLBuffer::append (const XMLCh *const chars) inline
Definition at line 134 of file XMLBuffer.hpp.
append() [2/9]
void XMLBuffer::append (const XMLCh *const chars) inline
Definition at line 134 of file XMLBuffer.hpp.
append() [3/9]
void XMLBuffer::append (const XMLCh *const chars) inline
Definition at line 134 of file XMLBuffer.hpp.
append() [4/9]
void XMLBuffer::append (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 120 of file XMLBuffer.hpp.
append() [5/9]
void XMLBuffer::append (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 120 of file XMLBuffer.hpp.
append() [6/9]
void XMLBuffer::append (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 120 of file XMLBuffer.hpp.
append() [7/9]
void XMLBuffer::append (const XMLCh toAppend) inline
Definition at line 112 of file XMLBuffer.hpp.
Referenced by XMLBufBid::append(), TraverseSchema::genAnonTypeName(), TraverseSchema::getRedefineNewTypeName(), XMLReader::movePlainContentChars(), and SchemaValidator::setDatatypeBuffer().
append() [8/9]
void XMLBuffer::append (const XMLCh toAppend) inline
Definition at line 112 of file XMLBuffer.hpp.
append() [9/9]
void XMLBuffer::append (const XMLCh toAppend) inline
Definition at line 112 of file XMLBuffer.hpp.
ensureCapacity() [1/3]
void XMLBuffer::ensureCapacity (const XMLSize_t extraNeeded) private
ensureCapacity() [2/3]
void XMLBuffer::ensureCapacity (const XMLSize_t extraNeeded) private
ensureCapacity() [3/3]
void XMLBuffer::ensureCapacity (const XMLSize_t extraNeeded) private
getInUse() [1/3]
bool XMLBuffer::getInUse () const inline
Definition at line 182 of file XMLBuffer.hpp.
getInUse() [2/3]
bool XMLBuffer::getInUse () const inline
Definition at line 182 of file XMLBuffer.hpp.
getInUse() [3/3]
bool XMLBuffer::getInUse () const inline
Definition at line 182 of file XMLBuffer.hpp.
getLen() [1/3]
XMLSize_t XMLBuffer::getLen () const inline
Definition at line 187 of file XMLBuffer.hpp.
getLen() [2/3]
XMLSize_t XMLBuffer::getLen () const inline
Definition at line 187 of file XMLBuffer.hpp.
getLen() [3/3]
XMLSize_t XMLBuffer::getLen () const inline
Definition at line 187 of file XMLBuffer.hpp.
getRawBuffer() [1/6]
XMLCh* XMLBuffer::getRawBuffer () inline
Definition at line 168 of file XMLBuffer.hpp.
getRawBuffer() [2/6]
XMLCh* XMLBuffer::getRawBuffer () inline
Definition at line 168 of file XMLBuffer.hpp.
getRawBuffer() [3/6]
XMLCh* XMLBuffer::getRawBuffer () inline
Definition at line 168 of file XMLBuffer.hpp.
getRawBuffer() [4/6]
const XMLCh* XMLBuffer::getRawBuffer () const inline
Definition at line 162 of file XMLBuffer.hpp.
Referenced by TraverseSchema::genAnonTypeName(), TraverseSchema::getLocalPart(), SchemaValidator::getNormalizedValue(), and TraverseSchema::getPrefix().
getRawBuffer() [5/6]
const XMLCh* XMLBuffer::getRawBuffer () const inline
Definition at line 162 of file XMLBuffer.hpp.
getRawBuffer() [6/6]
const XMLCh* XMLBuffer::getRawBuffer () const inline
Definition at line 162 of file XMLBuffer.hpp.
isEmpty() [1/3]
bool XMLBuffer::isEmpty () const inline
Definition at line 192 of file XMLBuffer.hpp.
isEmpty() [2/3]
bool XMLBuffer::isEmpty () const inline
Definition at line 192 of file XMLBuffer.hpp.
isEmpty() [3/3]
bool XMLBuffer::isEmpty () const inline
Definition at line 192 of file XMLBuffer.hpp.
operator=() [1/3]
XMLBuffer& XMLBuffer::operator= (const XMLBuffer &) private
operator=() [2/3]
XMLBuffer& XMLBuffer::operator= (const XMLBuffer &) private
operator=() [3/3]
XMLBuffer& XMLBuffer::operator= (const XMLBuffer &) private
reset() [1/3]
void XMLBuffer::reset () inline
Definition at line 174 of file XMLBuffer.hpp.
Referenced by SchemaValidator::clearDatatypeBuffer(), ReaderMgr::getName(), ReaderMgr::getNameToken(), ReaderMgr::getQName(), and XMLBufBid::reset().
reset() [2/3]
void XMLBuffer::reset () inline
Definition at line 174 of file XMLBuffer.hpp.
reset() [3/3]
void XMLBuffer::reset () inline
Definition at line 174 of file XMLBuffer.hpp.
set() [1/6]
void XMLBuffer::set (const XMLCh *const chars) inline
Definition at line 155 of file XMLBuffer.hpp.
set() [2/6]
void XMLBuffer::set (const XMLCh *const chars) inline
Definition at line 155 of file XMLBuffer.hpp.
set() [3/6]
void XMLBuffer::set (const XMLCh *const chars) inline
Definition at line 155 of file XMLBuffer.hpp.
set() [4/6]
void XMLBuffer::set (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 149 of file XMLBuffer.hpp.
Referenced by TraverseSchema::genAnonTypeName(), TraverseSchema::getLocalPart(), TraverseSchema::getPrefix(), TraverseSchema::getRedefineNewTypeName(), and XMLBufBid::set().
set() [5/6]
void XMLBuffer::set (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 149 of file XMLBuffer.hpp.
set() [6/6]
void XMLBuffer::set (const XMLCh *const chars, const XMLSize_t count) inline
Definition at line 149 of file XMLBuffer.hpp.
setFullHandler() [1/3]
void XMLBuffer::setFullHandler (XMLBufferFullHandler * handler, const XMLSize_t fullSize) inline
Definition at line 83 of file XMLBuffer.hpp.
Referenced by XMLScanner::setInputBufferSize().
setFullHandler() [2/3]
void XMLBuffer::setFullHandler (XMLBufferFullHandler * handler, const XMLSize_t fullSize) inline
Definition at line 83 of file XMLBuffer.hpp.
setFullHandler() [3/3]
void XMLBuffer::setFullHandler (XMLBufferFullHandler * handler, const XMLSize_t fullSize) inline
Definition at line 83 of file XMLBuffer.hpp.
setInUse() [1/3]
void XMLBuffer::setInUse (const bool newValue) inline
Definition at line 200 of file XMLBuffer.hpp.
setInUse() [2/3]
void XMLBuffer::setInUse (const bool newValue) inline
Definition at line 200 of file XMLBuffer.hpp.
setInUse() [3/3]
void XMLBuffer::setInUse (const bool newValue) inline
Definition at line 200 of file XMLBuffer.hpp.
Friends And Related Function Documentation
XMLBufBid
XMLBufBid friend
Definition at line 215 of file XMLBuffer.hpp.
Member Data Documentation
fBuffer
XMLCh * XMLBuffer::fBuffer private
Definition at line 253 of file XMLBuffer.hpp.
Referenced by XMLBufBid::getRawBuffer().
fCapacity
XMLSize_t XMLBuffer::fCapacity private
Definition at line 248 of file XMLBuffer.hpp.
fFullHandler
XMLBufferFullHandler * XMLBuffer::fFullHandler private
Definition at line 252 of file XMLBuffer.hpp.
fFullSize
XMLSize_t XMLBuffer::fFullSize private
Definition at line 249 of file XMLBuffer.hpp.
fIndex
XMLSize_t XMLBuffer::fIndex private
Definition at line 247 of file XMLBuffer.hpp.
Referenced by XMLBufBid::getLen(), XMLBufBid::getRawBuffer(), and XMLBufBid::isEmpty().
fMemoryManager
MemoryManager *const XMLBuffer::fMemoryManager private
Definition at line 251 of file XMLBuffer.hpp.
fUsed
bool XMLBuffer::fUsed private
Definition at line 250 of file XMLBuffer.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/XMLBuffer.hpp