Seamly2D: VPE::LineTypeProperty Class Reference
VPE::LineTypeProperty Class Reference
#include <vlinetypeproperty.h>
Public Slots
void currentIndexChanged (int index)
Public Slots inherited from VPE::VProperty
virtual void childValueChanged (const QVariant &value, int typeForParent)
Public Member Functions
LineTypeProperty (const QString &name)
Constructor.
virtual ~LineTypeProperty () Q_DECL_OVERRIDE
Destructor.
virtual QVariant data (int column=DPC_Name, int role=Qt::DisplayRole) const Q_DECL_OVERRIDE
Get the data how it should be displayed.
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &options, const QAbstractItemDelegate *delegate) Q_DECL_OVERRIDE
Returns an editor widget, or NULL if it doesn't supply one.
virtual QVariant getEditorData (const QWidget *editor) const Q_DECL_OVERRIDE
Gets the data from the widget.
virtual void setLineTypes (const QMap< QString, QString > &styles)
Sets the line styles.
virtual QMap< QString, QString > getLineTypes () const
Get the settings. This function has to be implemented in a subclass in order to have an effect.
virtual void setValue (const QVariant &value) Q_DECL_OVERRIDE
Sets the value of the property.
virtual QString type () const Q_DECL_OVERRIDE
Returns a string containing the type of the property.
virtual Q_REQUIRED_RESULT VProperty * clone (bool include_children=true, VProperty *container=nullptr) const Q_DECL_OVERRIDE
Clones this property.
Public Member Functions inherited from VPE::VProperty
VProperty (const QString &name, QVariant::Type type=QVariant::String)
Standard constructor, takes a name and a parent property as argument.
virtual ~VProperty () Q_DECL_OVERRIDE
Destructor.
virtual bool setData (const QVariant &data, int role=Qt::EditRole)
This is used by the model to set the data.
virtual bool paint (QPainter *, const QStyleOptionViewItem &, const QModelIndex &, const QAbstractItemDelegate *) const
This is called by the delegate when the property value is being drawn. The standard implementation doesn't do anything. If you reimplement this in a sub property, make sure to return true or the delegate will draw the item.
virtual bool setEditorData (QWidget *editor)
Sets the property's data to the editor (returns false, if the standard delegate should do that)
virtual Qt::ItemFlags flags (int column=DPC_Name) const
Returns item flags.
virtual QVariant getValue () const
Returns the value of the property as a QVariant.
virtual QString serialize () const
Serializes the value to a string.
virtual void deserialize (const QString &value)
Deserializes the value from a string.
virtual void setName (const QString &name)
Sets the name of the property.
virtual QString getName () const
Gets the name of the property.
virtual void setDescription (const QString &desc)
Sets the name of the property.
virtual QString getDescription () const
Gets the name of the property.
virtual int addChild (VProperty *child)
Adds a child to this property.
virtual QList< VProperty * > & getChildren ()
Returns a reference to the list of children.
virtual const QList< VProperty * > & getChildren () const
Returns a reference to the list of children.
virtual VProperty * getChild (int row) const
Returns the child at a certain row.
virtual int getRowCount () const
Gets the number of children.
virtual VProperty * getParent () const
Gets the parent of this property.
virtual void setParent (VProperty *parent)
Sets the parent of this property.
virtual void removeChild (VProperty *child)
Removes a child from the children list, doesn't delete the child!
virtual int getChildRow (VProperty *child) const
Returns the row the child has.
virtual bool getUpdateParent () const
Returns whether the views have to update the parent of this property if it changes.
virtual bool getUpdateChildren () const
Returns whether the views have to update the children of this property if it changes.
virtual void setUpdateBehaviour (bool update_parent, bool update_children)
Sets whether the views should update Parents or children after this property changes.
virtual void setSettings (const QMap< QString, QVariant > &settings)
Sets the settings by calling the overloaded setSetting(const QString &key, const QVariant &value) for each item in the map.
virtual QMap< QString, QVariant > getSettings () const
Get the settings.
virtual void setSetting (const QString &key, const QVariant &value)
Sets the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QVariant getSetting (const QString &key) const
Get the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QStringList getSettingKeys () const
Returns the list of keys of the property's settings.
Property propertyType () const
void setPropertyType (const Property &type)
virtual void updateParent (const QVariant &value)
Static Public Member Functions
static int indexOfLineType (const QMap< QString, QString > &styles, const QString &style)
Protected Attributes
QMap< QString, QString > m_lineTypes
QVector< QString > m_indexList
int m_iconWidth
int m_iconHeight
Protected Attributes inherited from VPE::VProperty
VPropertyPrivate * d_ptr
The protected structure holding the member variables (to assure binary compatibility)
Private Member Functions
QIcon createIcon (const QString &type)
Additional Inherited Members
Public Types inherited from VPE::VProperty
enum DPC_DisplayColumn { DPC_Name = 0 , DPC_Data }
Signals inherited from VPE::VProperty
void childChanged (const QVariant &value, int typeForParent)
Protected Member Functions inherited from VPE::VProperty
VProperty (VPropertyPrivate *d)
Protected constructor.
Detailed Description
Definition at line 76 of file vlinetypeproperty.h.
Constructor & Destructor Documentation
LineTypeProperty()
VPE::LineTypeProperty::LineTypeProperty (const QString & name) explicit
Constructor.
Definition at line 74 of file vlinetypeproperty.cpp.
References VPE::VProperty::d_ptr, and VPE::VPropertyPrivate::VariantValue.
~LineTypeProperty()
virtual VPE::LineTypeProperty::~LineTypeProperty () inline virtual
Destructor.
Definition at line 84 of file vlinetypeproperty.h.
Member Function Documentation
clone()
VPE::VProperty * VPE::LineTypeProperty::clone (bool include_children = true, VProperty * container = nullptr) const virtual
Clones this property.
Parameters
include_children Indicates whether to also clone the children
container If a property is being passed here, no new VProperty is being created but instead it is tried to fill all the data into container. This can also be used when subclassing this function.
Returns
Returns the newly created property (or container, if it was not NULL)
Reimplemented from VPE::VProperty.
Definition at line 198 of file vlinetypeproperty.cpp.
References VPE::VProperty::clone().
createEditor()
QWidget * VPE::LineTypeProperty::createEditor (QWidget * parent, const QStyleOptionViewItem & options, const QAbstractItemDelegate * delegate) virtual
Returns an editor widget, or NULL if it doesn't supply one.
Parameters
parent The widget to which the editor will be added as a child \options Render options \delegate A pointer to the QAbstractItemDelegate requesting the editor. This can be used to connect signals and slots.
Reimplemented from VPE::VProperty.
Definition at line 113 of file vlinetypeproperty.cpp.
References currentIndexChanged(), VPE::VProperty::d_ptr, and VPE::VPropertyPrivate::editor.
createIcon()
QIcon VPE::LineTypeProperty::createIcon (const QString & type) private
Definition at line 222 of file vlinetypeproperty.cpp.
References lineTypeToPenStyle().
currentIndexChanged
void VPE::LineTypeProperty::currentIndexChanged (int index) slot
Definition at line 215 of file vlinetypeproperty.cpp.
References VPE::VProperty::d_ptr.
Referenced by createEditor().
data()
QVariant VPE::LineTypeProperty::data (int column = DPC_Name, int role = Qt::DisplayRole) const virtual
Get the data how it should be displayed.
Reimplemented from VPE::VProperty.
Definition at line 85 of file vlinetypeproperty.cpp.
References VPE::VProperty::d_ptr, VPE::VProperty::data(), and VPE::VPropertyPrivate::VariantValue.
getEditorData()
QVariant VPE::LineTypeProperty::getEditorData (const QWidget * editor) const virtual
Gets the data from the widget.
Reimplemented from VPE::VProperty.
Definition at line 146 of file vlinetypeproperty.cpp.
getLineTypes()
QMap< QString, QString > VPE::LineTypeProperty::getLineTypes () const virtual
Get the settings. This function has to be implemented in a subclass in order to have an effect.
Definition at line 170 of file vlinetypeproperty.cpp.
indexOfLineType()
int VPE::LineTypeProperty::indexOfLineType (const QMap< QString, QString > & styles, const QString & style) static
Definition at line 203 of file vlinetypeproperty.cpp.
Referenced by VToolOptionsPropertyBrowser::addPropertyCurveLineType(), VToolOptionsPropertyBrowser::addPropertyLineType(), VToolOptionsPropertyBrowser::updateOptionsToolAlongLine(), VToolOptionsPropertyBrowser::updateOptionsToolArc(), VToolOptionsPropertyBrowser::updateOptionsToolArcWithLength(), VToolOptionsPropertyBrowser::updateOptionsToolBisector(), VToolOptionsPropertyBrowser::updateOptionsToolCubicBezier(), VToolOptionsPropertyBrowser::updateOptionsToolCubicBezierPath(), VToolOptionsPropertyBrowser::updateOptionsToolCurveIntersectAxis(), VToolOptionsPropertyBrowser::updateOptionsToolEllipticalArc(), VToolOptionsPropertyBrowser::updateOptionsToolEndLine(), VToolOptionsPropertyBrowser::updateOptionsToolHeight(), VToolOptionsPropertyBrowser::updateOptionsToolLine(), VToolOptionsPropertyBrowser::updateOptionsToolLineIntersectAxis(), VToolOptionsPropertyBrowser::updateOptionsToolNormal(), VToolOptionsPropertyBrowser::updateOptionsToolPointOfIntersection(), VToolOptionsPropertyBrowser::updateOptionsToolShoulderPoint(), VToolOptionsPropertyBrowser::updateOptionsToolSpline(), and VToolOptionsPropertyBrowser::updateOptionsToolSplinePath().
setLineTypes()
void VPE::LineTypeProperty::setLineTypes (const QMap< QString, QString > & styles) virtual
Sets the line styles.
Definition at line 157 of file vlinetypeproperty.cpp.
Referenced by VToolOptionsPropertyBrowser::addPropertyCurveLineType(), and VToolOptionsPropertyBrowser::addPropertyLineType().
setValue()
void VPE::LineTypeProperty::setValue (const QVariant & value) virtual
Sets the value of the property.
Reimplemented from VPE::VProperty.
Definition at line 175 of file vlinetypeproperty.cpp.
References VPE::VProperty::d_ptr, and VPE::VPropertyPrivate::VariantValue.
Referenced by VToolOptionsPropertyBrowser::addPropertyCurveLineType(), and VToolOptionsPropertyBrowser::addPropertyLineType().
type()
QString VPE::LineTypeProperty::type () const virtual
Returns a string containing the type of the property.
Reimplemented from VPE::VProperty.
Definition at line 193 of file vlinetypeproperty.cpp.
Member Data Documentation
m_iconHeight
int VPE::LineTypeProperty::m_iconHeight protected
Definition at line 129 of file vlinetypeproperty.h.
m_iconWidth
int VPE::LineTypeProperty::m_iconWidth protected
Definition at line 128 of file vlinetypeproperty.h.
m_indexList
QVector<QString> VPE::LineTypeProperty::m_indexList protected
Definition at line 127 of file vlinetypeproperty.h.
m_lineTypes
QMap<QString, QString> VPE::LineTypeProperty::m_lineTypes protected
Definition at line 126 of file vlinetypeproperty.h.
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/plugins/vlinetypeproperty.h
src/libs/vpropertyexplorer/plugins/vlinetypeproperty.cpp