Seamly2D: anonymous_namespace{vtextmanager.cpp} Namespace Reference
anonymous_namespace{vtextmanager.cpp} Namespace Reference
Functions
QMap< QString, QString > PreparePlaceholders (const VAbstractPattern *doc)
void InitPiecePlaceholders (QMap< QString, QString > &placeholders, const QString &name, const VPieceLabelData &data)
QString ReplacePlaceholders (const QMap< QString, QString > &placeholders, QString line)
QList< TextLine > PrepareLines (const QVector< VLabelTemplateLine > &lines)
Function Documentation
InitPiecePlaceholders()
void anonymous_namespace{vtextmanager.cpp}::InitPiecePlaceholders (QMap< QString, QString > & placeholders, const QString & name, const VPieceLabelData & data)
Definition at line 125 of file vtextmanager.cpp.
References VPieceLabelData::GetAnnotation(), VPieceLabelData::GetFoldPosition(), VPieceLabelData::GetLetter(), VPieceLabelData::GetOrientation(), VPieceLabelData::GetQuantity(), VPieceLabelData::GetRotationWay(), VPieceLabelData::GetTilt(), VPieceLabelData::IsOnFold(), pl_pAnnotation, pl_pFoldPosition, pl_pLetter, pl_pName, pl_pOrientation, pl_pQuantity, pl_pRotation, pl_pTilt, and pl_wOnFold.
Referenced by VTextManager::Update().
PrepareLines()
QList<TextLine> anonymous_namespace{vtextmanager.cpp}::PrepareLines (const QVector< VLabelTemplateLine > & lines)
Definition at line 156 of file vtextmanager.cpp.
References TextLine::bold, TextLine::italic, TextLine::m_eAlign, TextLine::m_iFontSize, and TextLine::m_text.
Referenced by VTextManager::Update().
PreparePlaceholders()
QMap<QString, QString> anonymous_namespace{vtextmanager.cpp}::PreparePlaceholders (const VAbstractPattern * doc)
Definition at line 62 of file vtextmanager.cpp.
References VAbstractPattern::GetCompanyName(), VAbstractPattern::GetCustomerName(), VAbstractPattern::GetLabelDateFormat(), VAbstractPattern::GetLabelTimeFormat(), VAbstractPattern::GetPatternName(), VAbstractPattern::GetPatternNumber(), VContainer::height(), Individual, VAbstractPattern::MPath(), Multisize, pl_author, pl_customer, pl_date, pl_height, pl_mExt, pl_mFabric, pl_mFileName, pl_mInterfacing, pl_mInterlining, pl_mLining, pl_pAnnotation, pl_patternName, pl_patternNumber, pl_pExt, pl_pFileName, pl_pFoldPosition, pl_pLetter, pl_pName, pl_pOrientation, pl_pQuantity, pl_pRotation, pl_pTilt, pl_size, pl_time, pl_wCut, pl_wOnFold, qApp, SCASSERT, and VContainer::size().
Referenced by VTextManager::Update().
ReplacePlaceholders()
QString anonymous_namespace{vtextmanager.cpp}::ReplacePlaceholders (const QMap< QString, QString > & placeholders, QString line)
Definition at line 143 of file vtextmanager.cpp.
Referenced by VTextManager::Update().