Seamly2D: VCurveVariable Class Reference
VCurveVariable Class Reference
#include <vcurvevariable.h>
Public Member Functions
VCurveVariable ()
VCurveVariable (const quint32 &id, const quint32 &parentId)
VCurveVariable (const VCurveVariable &var)
virtual ~VCurveVariable () Q_DECL_OVERRIDE
VCurveVariable & operator= (const VCurveVariable &var)
void Swap (VCurveVariable &var) Q_DECL_NOTHROW
virtual bool Filter (quint32 id) Q_DECL_OVERRIDE
quint32 GetId () const
void SetId (const quint32 &id)
quint32 GetParentId () const
void SetParentId (const quint32 &value)
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool isNotUsed () const
Private Attributes
QSharedDataPointer< VCurveVariableData > d
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
Definition at line 64 of file vcurvevariable.h.
Constructor & Destructor Documentation
VCurveVariable() [1/3]
VCurveVariable::VCurveVariable ()
Definition at line 68 of file vcurvevariable.cpp.
References VInternalVariable::SetType(), and Unknown.
VCurveVariable() [2/3]
VCurveVariable::VCurveVariable (const quint32 & id, const quint32 & parentId)
Definition at line 75 of file vcurvevariable.cpp.
References VInternalVariable::SetType(), and Unknown.
VCurveVariable() [3/3]
VCurveVariable::VCurveVariable (const VCurveVariable & var)
Definition at line 82 of file vcurvevariable.cpp.
~VCurveVariable()
VCurveVariable::~VCurveVariable () virtual
Definition at line 99 of file vcurvevariable.cpp.
Member Function Documentation
Filter()
bool VCurveVariable::Filter (quint32 id) virtual
Reimplemented from VInternalVariable.
Definition at line 103 of file vcurvevariable.cpp.
References d, and NULL_ID.
GetId()
quint32 VCurveVariable::GetId () const
Definition at line 122 of file vcurvevariable.cpp.
References d.
GetParentId()
quint32 VCurveVariable::GetParentId () const
Definition at line 135 of file vcurvevariable.cpp.
References d.
operator=()
VCurveVariable & VCurveVariable::operator= (const VCurveVariable & var)
Definition at line 87 of file vcurvevariable.cpp.
References d, and VInternalVariable::operator=().
Referenced by VArcRadius::operator=(), VCurveAngle::operator=(), VCurveCLength::operator=(), and VCurveLength::operator=().
SetId()
void VCurveVariable::SetId (const quint32 & id)
Definition at line 128 of file vcurvevariable.cpp.
References d.
SetParentId()
void VCurveVariable::SetParentId (const quint32 & value)
Definition at line 141 of file vcurvevariable.cpp.
References d.
Swap()
void VCurveVariable::Swap (VCurveVariable & var)
Definition at line 64 of file vcurvevariable.cpp.
References VInternalVariable::Swap().
Member Data Documentation
d
QSharedDataPointer<VCurveVariableData> VCurveVariable::d private
Definition at line 88 of file vcurvevariable.h.
Referenced by Filter(), GetId(), GetParentId(), operator=(), SetId(), and SetParentId().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/vcurvevariable.h
src/libs/vpatterndb/variables/vcurvevariable.cpp