Seamly2D: IndividualSizeConverter Class Reference
IndividualSizeConverter Class Reference
#include <individual_size_converter.h>
Public Member Functions
IndividualSizeConverter (const QString &fileName)
virtual ~IndividualSizeConverter () Q_DECL_EQ_DEFAULT
Public Member Functions inherited from AbstractMConverter
AbstractMConverter (const QString &fileName)
virtual ~AbstractMConverter () Q_DECL_EQ_DEFAULT
Public Member Functions inherited from VAbstractConverter
VAbstractConverter (const QString &fileName)
virtual ~VAbstractConverter () Q_DECL_EQ_DEFAULT
QString Convert ()
int GetCurrentFormatVarsion () const
QString GetVersionStr () const
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit measurementUnits () const
virtual void setXMLContent (const QString &fileName)
virtual bool SaveDocument (const QString &fileName, QString &error)
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Static Public Attributes
static const QString MeasurementMaxVerStr = QStringLiteral("0.3.4")
static const QString CurrentSchema = QStringLiteral("://schema/individual_size_measurements/v0.3.4.xsd")
static Q_DECL_CONSTEXPR const int MeasurementMinVer = ((0 <<16)|(2 <<8)|(0))
static Q_DECL_CONSTEXPR const int MeasurementMaxVer = ((0 <<16)|(3 <<8)|(4))
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Protected Member Functions
virtual int minVer () const Q_DECL_OVERRIDE
virtual int maxVer () const Q_DECL_OVERRIDE
virtual QString minVerStr () const Q_DECL_OVERRIDE
virtual QString maxVerStr () const Q_DECL_OVERRIDE
virtual QString getSchema (int ver) const Q_DECL_OVERRIDE
virtual void applyPatches () Q_DECL_OVERRIDE
virtual void downgradeToCurrentMaxVersion () Q_DECL_OVERRIDE
virtual bool isReadOnly () const Q_DECL_OVERRIDE
Protected Member Functions inherited from AbstractMConverter
void AddRootComment ()
Protected Member Functions inherited from VAbstractConverter
void ValidateInputFile (const QString &currentSchema) const
Q_NORETURN void InvalidVersion (int ver) const
void Save ()
void setVersion (const QString &version)
void Replace (QString &formula, const QString &newName, int position, const QString &token, int &bias) const
void CorrectionsPositions (int position, int bias, QMap< int, QString > &tokens) const
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Private Member Functions
void addNewTagsForVer0_3_0 ()
QString convertUnitsToVer0_2_0 ()
void convertMeasurementsToV0_3_0 ()
QDomElement addMeasurementsVer0_3_0 (const QString &name, qreal value)
void convertGenderToVer0_3_1 ()
void convertPmSystemToVer0_3_2 ()
void convertMeasurementsToV0_3_3 ()
void convertToVer0_3_0 ()
void convertToVer0_3_1 ()
void convertToVer0_3_2 ()
void convertToVer0_3_3 ()
void convertToVer0_3_4 ()
Static Private Attributes
static const QString MeasurementMinVerStr = QStringLiteral("0.2.0")
Additional Inherited Members
Static Public Member Functions inherited from VAbstractConverter
static int GetVersion (const QString &version)
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Static Protected Member Functions inherited from AbstractMConverter
static QMultiMap< QString, QString > OldNamesToNewNames_InV0_3_0 ()
static QMap< QString, QString > OldNamesToNewNames_InV0_3_3 ()
Static Protected Member Functions inherited from VAbstractConverter
static void BiasTokens (int position, int bias, QMap< int, QString > &tokens)
Protected Attributes inherited from VAbstractConverter
int m_ver
QString m_convertedFileName
Detailed Description
Definition at line 69 of file individual_size_converter.h.
Constructor & Destructor Documentation
IndividualSizeConverter()
IndividualSizeConverter::IndividualSizeConverter (const QString & fileName) explicit
Definition at line 92 of file individual_size_converter.cpp.
References CurrentSchema, and VAbstractConverter::ValidateInputFile().
~IndividualSizeConverter()
virtual IndividualSizeConverter::~IndividualSizeConverter () virtual
Member Function Documentation
addMeasurementsVer0_3_0()
QDomElement IndividualSizeConverter::addMeasurementsVer0_3_0 (const QString & name, qreal value) private
Definition at line 252 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, MeasurementMinVer, and VDomDocument::SetAttribute().
Referenced by convertMeasurementsToV0_3_0().
addNewTagsForVer0_3_0()
void IndividualSizeConverter::addNewTagsForVer0_3_0 () private
Definition at line 177 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, convertUnitsToVer0_2_0(), and MeasurementMinVer.
Referenced by convertToVer0_3_0().
applyPatches()
void IndividualSizeConverter::applyPatches () protected virtual
Implements VAbstractConverter.
Definition at line 123 of file individual_size_converter.cpp.
References convertToVer0_3_0(), convertToVer0_3_1(), convertToVer0_3_2(), convertToVer0_3_3(), convertToVer0_3_4(), getSchema(), VAbstractConverter::InvalidVersion(), VAbstractConverter::m_convertedFileName, VAbstractConverter::m_ver, V_FALLTHROUGH, and VDomDocument::ValidateXML().
convertGenderToVer0_3_1()
void IndividualSizeConverter::convertGenderToVer0_3_1 () private
Definition at line 269 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, and MeasurementMinVer.
Referenced by convertToVer0_3_1().
convertMeasurementsToV0_3_0()
void IndividualSizeConverter::convertMeasurementsToV0_3_0 () private
Definition at line 209 of file individual_size_converter.cpp.
References addMeasurementsVer0_3_0(), CONVERTER_VERSION_CHECK, VDomDocument::GetParametrDouble(), MeasurementMinVer, and AbstractMConverter::OldNamesToNewNames_InV0_3_0().
Referenced by convertToVer0_3_0().
convertMeasurementsToV0_3_3()
void IndividualSizeConverter::convertMeasurementsToV0_3_3 () private
Definition at line 303 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, VDomDocument::GetParametrString(), MeasurementMinVer, AbstractMConverter::OldNamesToNewNames_InV0_3_3(), and VDomDocument::SetAttribute().
Referenced by convertToVer0_3_3().
convertPmSystemToVer0_3_2()
void IndividualSizeConverter::convertPmSystemToVer0_3_2 () private
Definition at line 286 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, and MeasurementMinVer.
Referenced by convertToVer0_3_2().
convertToVer0_3_0()
void IndividualSizeConverter::convertToVer0_3_0 () private
Definition at line 336 of file individual_size_converter.cpp.
References addNewTagsForVer0_3_0(), AbstractMConverter::AddRootComment(), CONVERTER_VERSION_CHECK, convertMeasurementsToV0_3_0(), MeasurementMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
convertToVer0_3_1()
void IndividualSizeConverter::convertToVer0_3_1 () private
Definition at line 350 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, convertGenderToVer0_3_1(), MeasurementMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
convertToVer0_3_2()
void IndividualSizeConverter::convertToVer0_3_2 () private
Definition at line 362 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, convertPmSystemToVer0_3_2(), MeasurementMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
convertToVer0_3_3()
void IndividualSizeConverter::convertToVer0_3_3 () private
Definition at line 374 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, convertMeasurementsToV0_3_3(), MeasurementMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
convertToVer0_3_4()
void IndividualSizeConverter::convertToVer0_3_4 () private
Definition at line 386 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, MeasurementMinVer, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
Referenced by applyPatches().
convertUnitsToVer0_2_0()
QString IndividualSizeConverter::convertUnitsToVer0_2_0 () private
Definition at line 199 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, MeasurementMinVer, and VDomDocument::UniqueTagText().
Referenced by addNewTagsForVer0_3_0().
downgradeToCurrentMaxVersion()
void IndividualSizeConverter::downgradeToCurrentMaxVersion () protected virtual
Implements VAbstractConverter.
Definition at line 156 of file individual_size_converter.cpp.
References MeasurementMaxVerStr, VAbstractConverter::Save(), and VAbstractConverter::setVersion().
getSchema()
QString IndividualSizeConverter::getSchema (int ver) const protected virtual
Implements VAbstractConverter.
Definition at line 99 of file individual_size_converter.cpp.
References CurrentSchema, and VAbstractConverter::InvalidVersion().
Referenced by applyPatches().
isReadOnly()
bool IndividualSizeConverter::isReadOnly () const protected virtual
Implements VAbstractConverter.
Definition at line 163 of file individual_size_converter.cpp.
References CONVERTER_VERSION_CHECK, falseStr, MeasurementMaxVer, strTagRead_Only, trueStr, and VDomDocument::UniqueTagText().
maxVer()
int IndividualSizeConverter::maxVer () const inline protected virtual
Implements VAbstractConverter.
Definition at line 126 of file individual_size_converter.h.
References MeasurementMaxVer.
maxVerStr()
QString IndividualSizeConverter::maxVerStr () const inline protected virtual
Implements VAbstractConverter.
Definition at line 138 of file individual_size_converter.h.
References MeasurementMaxVerStr.
minVer()
int IndividualSizeConverter::minVer () const inline protected virtual
Implements VAbstractConverter.
Definition at line 120 of file individual_size_converter.h.
References MeasurementMinVer.
minVerStr()
QString IndividualSizeConverter::minVerStr () const inline protected virtual
Implements VAbstractConverter.
Definition at line 132 of file individual_size_converter.h.
References MeasurementMinVerStr.
Member Data Documentation
CurrentSchema
const QString IndividualSizeConverter::CurrentSchema = QStringLiteral("://schema/individual_size_measurements/v0.3.4.xsd") static
Definition at line 77 of file individual_size_converter.h.
Referenced by TST_Measurements::CreateEmptyIndividualFile(), getSchema(), IndividualSizeConverter(), and TST_Measurements::ValidPMCodesIndividualFile().
MeasurementMaxVer
Q_DECL_CONSTEXPR const int IndividualSizeConverter::MeasurementMaxVer = ((0 <<16)|(3 <<8)|(4)) static
Definition at line 85 of file individual_size_converter.h.
Referenced by TMainWindow::FileNew(), TMainWindow::FileSave(), isReadOnly(), and maxVer().
MeasurementMaxVerStr
const QString IndividualSizeConverter::MeasurementMaxVerStr = QStringLiteral("0.3.4") static
Definition at line 76 of file individual_size_converter.h.
Referenced by MeasurementDoc::CreateEmptyIndividualFile(), downgradeToCurrentMaxVersion(), TMainWindow::FileNew(), TMainWindow::FileSave(), and maxVerStr().
MeasurementMinVer
Q_DECL_CONSTEXPR const int IndividualSizeConverter::MeasurementMinVer = ((0 <<16)|(2 <<8)|(0)) static
Definition at line 84 of file individual_size_converter.h.
Referenced by addMeasurementsVer0_3_0(), addNewTagsForVer0_3_0(), convertGenderToVer0_3_1(), convertMeasurementsToV0_3_0(), convertMeasurementsToV0_3_3(), convertPmSystemToVer0_3_2(), convertToVer0_3_0(), convertToVer0_3_1(), convertToVer0_3_2(), convertToVer0_3_3(), convertToVer0_3_4(), convertUnitsToVer0_2_0(), and minVer().
MeasurementMinVerStr
const QString IndividualSizeConverter::MeasurementMinVerStr = QStringLiteral("0.2.0") static private
Definition at line 102 of file individual_size_converter.h.
Referenced by minVerStr().
The documentation for this class was generated from the following files:
src/libs/ifc/xml/individual_size_converter.h
src/libs/ifc/xml/individual_size_converter.cpp