Seamly2D: anonymous_namespace{vlayoutpiece.cpp} Namespace Reference
anonymous_namespace{vlayoutpiece.cpp} Namespace Reference
Functions
QVector< VLayoutPiecePath > ConvertInternalPaths (const VPiece &piece, const VContainer *pattern, const bool isCut)
bool FindLabelGeometry (const VPatternLabelData &labelData, const VContainer *pattern, qreal &rotationAngle, qreal &labelWidth, qreal &labelHeight, QPointF &pos)
bool FindGrainlineGeometry (const VGrainlineData &data, const VContainer *pattern, qreal &length, qreal &rotationAngle, QPointF &pos)
bool IsItemContained (const QRectF &parentBoundingRect, const QVector< QPointF > &shape, qreal &dX, qreal &dY)
QVector< QPointF > CorrectPosition (const QRectF &parentBoundingRect, QVector< QPointF > points)
QVector< VSAPoint > PrepareAllowance (const QVector< QPointF > &points)
QPointF RotatePoint (const QPointF &ptCenter, const QPointF &pt, qreal rotationAngle)
VLayoutPiece::RotatePoint rotates a point around the center for given angle.
QStringList PieceLabelText (const QVector< QPointF > &labelShape, const VTextManager &tm)
Function Documentation
ConvertInternalPaths()
QVector<VLayoutPiecePath> anonymous_namespace{vlayoutpiece.cpp}::ConvertInternalPaths (const VPiece & piece, const VContainer * pattern, const bool isCut)
Definition at line 87 of file vlayoutpiece.cpp.
References VPiece::GetInternalPaths(), VPiecePath::GetPenType(), VContainer::GetPiecePath(), VPiecePath::GetType(), InternalPath, VPiecePath::IsCutPath(), VPiecePath::PathPoints(), and SCASSERT.
Referenced by VLayoutPiece::Create().
CorrectPosition()
QVector<QPointF> anonymous_namespace{vlayoutpiece.cpp}::CorrectPosition (const QRectF & parentBoundingRect, QVector< QPointF > points)
Definition at line 321 of file vlayoutpiece.cpp.
References IsItemContained().
Referenced by VLayoutPiece::setGrainline(), VLayoutPiece::SetPatternInfo(), and VLayoutPiece::SetPieceText().
FindGrainlineGeometry()
bool anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry (const VGrainlineData & data, const VContainer * pattern, qreal & length, qreal & rotationAngle, QPointF & pos)
Definition at line 193 of file vlayoutpiece.cpp.
References VGrainlineData::bottomAnchorPoint(), VGrainlineData::centerAnchorPoint(), VContainer::DataVariables(), Calculator::EvalFormula(), VContainer::GeometricObject(), VGrainlineData::GetLength(), VContainer::GetPatternUnit(), VAbstractFloatItemData::GetPos(), VGrainlineData::GetRotation(), NULL_ID, SCASSERT, VGrainlineData::topAnchorPoint(), ToPixel(), and VFuzzyComparePossibleNulls().
Referenced by VLayoutPiece::setGrainline().
FindLabelGeometry()
bool anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry (const VPatternLabelData & labelData, const VContainer * pattern, qreal & rotationAngle, qreal & labelWidth, qreal & labelHeight, QPointF & pos)
Definition at line 112 of file vlayoutpiece.cpp.
References VPatternLabelData::bottomRightAnchorPoint(), VPatternLabelData::centerAnchorPoint(), VContainer::DataVariables(), Calculator::EvalFormula(), VContainer::GeometricObject(), VPatternLabelData::GetLabelHeight(), VPatternLabelData::GetLabelWidth(), VContainer::GetPatternUnit(), VAbstractFloatItemData::GetPos(), VPatternLabelData::GetRotation(), NULL_ID, SCASSERT, ToPixel(), and VPatternLabelData::topLeftAnchorPoint().
Referenced by VLayoutPiece::SetPatternInfo(), and VLayoutPiece::SetPieceText().
IsItemContained()
bool anonymous_namespace{vlayoutpiece.cpp}::IsItemContained (const QRectF & parentBoundingRect, const QVector< QPointF > & shape, qreal & dX, qreal & dY)
Definition at line 273 of file vlayoutpiece.cpp.
Referenced by CorrectPosition().
PieceLabelText()
QStringList anonymous_namespace{vlayoutpiece.cpp}::PieceLabelText (const QVector< QPointF > & labelShape, const VTextManager & tm)
Definition at line 365 of file vlayoutpiece.cpp.
References VTextManager::GetSourceLine(), VTextManager::GetSourceLinesCount(), and TextLine::m_text.
Referenced by VLayoutPiece::GetPatternText(), and VLayoutPiece::GetPieceText().
PrepareAllowance()
QVector<VSAPoint> anonymous_namespace{vlayoutpiece.cpp}::PrepareAllowance (const QVector< QPointF > & points)
Definition at line 336 of file vlayoutpiece.cpp.
Referenced by VLayoutPiece::SetLayoutAllowancePoints().
RotatePoint()
QPointF anonymous_namespace{vlayoutpiece.cpp}::RotatePoint (const QPointF & ptCenter, const QPointF & pt, qreal rotationAngle)
VLayoutPiece::RotatePoint rotates a point around the center for given angle.
Parameters
ptCenter center around which the point is rotated
pt point, which is rotated around the center
rotationAngle angle of rotation
Returns
position of point pt after rotating it around the center for rotation radians
Definition at line 354 of file vlayoutpiece.cpp.
Referenced by VLayoutPiece::SetPatternInfo(), and VLayoutPiece::SetPieceText().