Seamly2D: DialogSpline Class Reference
DialogSpline Class Reference
The DialogSpline class dialog for ToolSpline. Help create spline and edit option.
#include <dialogspline.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
virtual void PointNameChanged () Q_DECL_OVERRIDE
virtual void ShowDialog (bool click) Q_DECL_OVERRIDE
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogSpline (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogSpline create dialog.
virtual ~DialogSpline () Q_DECL_OVERRIDE
VSpline GetSpline () const
void SetSpline (const VSpline &spline)
QString getPenStyle () const
void setPenStyle (const QString &value)
QString getLineWeight () const
getLineWeight return weight of the lines
void setLineWeight (const QString &value)
setLineWeight set weight of the lines
QString getLineColor () const
void setLineColor (const QString &value)
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void CheckState () Q_DECL_FINAL
CheckState enable, when all is correct, or disable, when something wrong, button ok.
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Slots
void DeployAngle1TextEdit ()
void DeployAngle2TextEdit ()
void DeployLength1TextEdit ()
void DeployLength2TextEdit ()
void Angle1Changed ()
void Angle2Changed ()
void Length1Changed ()
void Length2Changed ()
void FXAngle1 ()
void FXAngle2 ()
void FXLength1 ()
void FXLength2 ()
Private Member Functions
const QSharedPointer< VPointF > GetP1 () const
const QSharedPointer< VPointF > GetP4 () const
void EvalAngle1 ()
void EvalAngle2 ()
void EvalLength1 ()
void EvalLength2 ()
VSpline CurrentSpline () const
Private Attributes
Ui::DialogSpline * ui
VSpline spl
ui keeps information about user interface
qint32 newDuplicate
spl spline
int formulaBaseHeightAngle1
formulaBaseHeight base height defined by dialogui
int formulaBaseHeightAngle2
int formulaBaseHeightLength1
int formulaBaseHeightLength2
QTimer * timerAngle1
timerAngle1 timer of check first angle formula
QTimer * timerAngle2
QTimer * timerLength1
QTimer * timerLength2
bool flagAngle1
flagAngle1 true if value of first angle is correct
bool flagAngle2
bool flagLength1
bool flagLength2
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
The DialogSpline class dialog for ToolSpline. Help create spline and edit option.
Definition at line 76 of file dialogspline.h.
Constructor & Destructor Documentation
DialogSpline()
DialogSpline::DialogSpline (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
DialogSpline create dialog.
Parameters
data container with data
parent parent widget
Definition at line 89 of file dialogspline.cpp.
References Angle1Changed(), Angle2Changed(), CheckState(), DialogTool::data, DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), DeployLength2TextEdit(), EvalAngle1(), EvalAngle2(), EvalLength1(), EvalLength2(), DialogTool::FillComboBoxPoints(), formulaBaseHeightAngle1, formulaBaseHeightAngle2, formulaBaseHeightLength1, formulaBaseHeightLength2, FXAngle1(), FXAngle2(), FXLength1(), FXLength2(), DialogTool::initializeOkCancelApply(), Length1Changed(), Length2Changed(), LineTypeNone, VisToolSpline::MouseLeftPressed(), VMainGraphicsScene::MouseLeftPressed(), VisToolSpline::MouseLeftReleased(), VMainGraphicsScene::MouseLeftReleased(), DialogTool::plainTextEditFormula, PointNameChanged(), qApp, SCASSERT, timerAngle1, timerAngle2, timerLength1, timerLength2, ui, and DialogTool::vis.
~DialogSpline()
DialogSpline::~DialogSpline () virtual
Definition at line 188 of file dialogspline.cpp.
References ui.
Member Function Documentation
Angle1Changed
void DialogSpline::Angle1Changed () private slot
Definition at line 296 of file dialogspline.cpp.
References degreeSymbol, flagAngle1, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, timerAngle1, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogSpline().
Angle2Changed
void DialogSpline::Angle2Changed () private slot
Definition at line 304 of file dialogspline.cpp.
References degreeSymbol, flagAngle2, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, timerAngle2, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogSpline().
CheckState()
void DialogSpline::CheckState () protected virtual
CheckState enable, when all is correct, or disable, when something wrong, button ok.
Reimplemented from DialogTool.
Definition at line 598 of file dialogspline.cpp.
References DialogTool::apply_Button, flagAngle1, flagAngle2, DialogTool::flagError, flagLength1, flagLength2, DialogTool::ok_Button, and SCASSERT.
Referenced by DialogSpline(), EvalLength1(), EvalLength2(), and PointNameChanged().
ChosenObject
void DialogSpline::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
Parameters
id id of point or detail
type type of object
Definition at line 199 of file dialogspline.cpp.
References DialogTool::getCurrentObjectId(), DialogTool::number, Point, DialogTool::prepare, SCASSERT, DialogTool::SetObject(), ui, and DialogTool::vis.
closeEvent()
void DialogSpline::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 262 of file dialogspline.cpp.
References DialogTool::closeEvent(), and ui.
CurrentSpline()
VSpline DialogSpline::CurrentSpline () const private
Definition at line 486 of file dialogspline.cpp.
References DialogTool::data, VContainer::DataVariables(), Visualization::FindLength(), Visualization::FindVal(), GetP1(), GetP4(), qApp, and ui.
Referenced by SaveData().
DeployAngle1TextEdit
void DialogSpline::DeployAngle1TextEdit () private slot
Definition at line 272 of file dialogspline.cpp.
References DialogTool::DeployFormula(), formulaBaseHeightAngle1, and ui.
Referenced by DialogSpline(), FXAngle1(), and FXAngle2().
DeployAngle2TextEdit
void DialogSpline::DeployAngle2TextEdit () private slot
Definition at line 278 of file dialogspline.cpp.
References DialogTool::DeployFormula(), formulaBaseHeightAngle2, and ui.
Referenced by DialogSpline().
DeployLength1TextEdit
void DialogSpline::DeployLength1TextEdit () private slot
Definition at line 284 of file dialogspline.cpp.
References DialogTool::DeployFormula(), formulaBaseHeightLength1, and ui.
Referenced by DialogSpline(), and FXLength1().
DeployLength2TextEdit
void DialogSpline::DeployLength2TextEdit () private slot
Definition at line 290 of file dialogspline.cpp.
References DialogTool::DeployFormula(), formulaBaseHeightLength2, and ui.
Referenced by DialogSpline(), and FXLength2().
EvalAngle1()
void DialogSpline::EvalAngle1 () private
Definition at line 434 of file dialogspline.cpp.
References degreeSymbol, DialogTool::Eval(), flagAngle1, DialogTool::labelEditFormula, and ui.
Referenced by DialogSpline().
EvalAngle2()
void DialogSpline::EvalAngle2 () private
Definition at line 441 of file dialogspline.cpp.
References degreeSymbol, DialogTool::Eval(), flagAngle2, DialogTool::labelEditFormula, and ui.
Referenced by DialogSpline().
EvalLength1()
void DialogSpline::EvalLength1 () private
Definition at line 448 of file dialogspline.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::Eval(), flagLength1, DialogTool::labelEditFormula, qApp, ui, and UnitsToStr().
Referenced by DialogSpline().
EvalLength2()
void DialogSpline::EvalLength2 () private
Definition at line 467 of file dialogspline.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::Eval(), flagLength2, DialogTool::labelEditFormula, qApp, ui, and UnitsToStr().
Referenced by DialogSpline().
FXAngle1
void DialogSpline::FXAngle1 () private slot
Definition at line 330 of file dialogspline.cpp.
References DialogTool::data, degreeSymbol, DeployAngle1TextEdit(), DialogTool::MoveCursorToEnd(), qApp, DialogTool::toolId, and ui.
Referenced by DialogSpline().
FXAngle2
void DialogSpline::FXAngle2 () private slot
Definition at line 353 of file dialogspline.cpp.
References DialogTool::data, degreeSymbol, DeployAngle1TextEdit(), DialogTool::MoveCursorToEnd(), qApp, DialogTool::toolId, and ui.
Referenced by DialogSpline().
FXLength1
void DialogSpline::FXLength1 () private slot
Definition at line 376 of file dialogspline.cpp.
References DialogTool::data, DeployLength1TextEdit(), DialogTool::MoveCursorToEnd(), qApp, DialogTool::toolId, ui, and UnitsToStr().
Referenced by DialogSpline().
FXLength2
void DialogSpline::FXLength2 () private slot
Definition at line 399 of file dialogspline.cpp.
References DialogTool::data, DeployLength2TextEdit(), DialogTool::MoveCursorToEnd(), qApp, DialogTool::toolId, ui, and UnitsToStr().
Referenced by DialogSpline().
getLineColor()
QString DialogSpline::getLineColor () const
Definition at line 671 of file dialogspline.cpp.
References ColorBlack, DialogTool::GetComboBoxCurrentData(), and ui.
Referenced by VToolSpline::setDialog().
getLineWeight()
QString DialogSpline::getLineWeight () const
getLineWeight return weight of the lines
Returns
type
Definition at line 687 of file dialogspline.cpp.
References DialogTool::GetComboBoxCurrentData(), and ui.
Referenced by VToolSpline::setDialog().
GetP1()
const QSharedPointer< VPointF > DialogSpline::GetP1 () const private
Definition at line 422 of file dialogspline.cpp.
References DialogTool::data, VContainer::GeometricObject(), DialogTool::getCurrentObjectId(), and ui.
Referenced by CurrentSpline(), PointNameChanged(), SaveData(), and ShowDialog().
GetP4()
const QSharedPointer< VPointF > DialogSpline::GetP4 () const private
Definition at line 428 of file dialogspline.cpp.
References DialogTool::data, VContainer::GeometricObject(), DialogTool::getCurrentObjectId(), and ui.
Referenced by CurrentSpline(), PointNameChanged(), SaveData(), and ShowDialog().
getPenStyle()
QString DialogSpline::getPenStyle () const
Definition at line 659 of file dialogspline.cpp.
References DialogTool::GetComboBoxCurrentData(), LineTypeSolidLine, and ui.
GetSpline()
VSpline DialogSpline::GetSpline () const
Definition at line 616 of file dialogspline.cpp.
References spl.
Length1Changed
void DialogSpline::Length1Changed () private slot
Definition at line 312 of file dialogspline.cpp.
References flagLength1, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, qApp, timerLength1, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by DialogSpline().
Length2Changed
void DialogSpline::Length2Changed () private slot
Definition at line 321 of file dialogspline.cpp.
References flagLength2, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, qApp, timerLength2, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by DialogSpline().
PointNameChanged
void DialogSpline::PointNameChanged () virtual slot
Definition at line 520 of file dialogspline.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::data, DialogTool::DNumber(), DialogTool::errorColor, DialogTool::flagError, DialogTool::getCurrentObjectId(), VSpline::GetEndAngle(), VSpline::GetKasm1(), VSpline::GetKasm2(), VSpline::GetKcurve(), GetP1(), VSpline::GetP1(), GetP4(), VSpline::GetP4(), VSpline::GetStartAngle(), VGObject::id(), VContainer::IsUnique(), VGObject::name(), newDuplicate, DialogTool::okColor, qApp, VAbstractCurve::SetDuplicate(), spl, and ui.
Referenced by DialogSpline().
SaveData()
void DialogSpline::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 240 of file dialogspline.cpp.
References CurrentSpline(), VAbstractCurve::GetDuplicate(), VSpline::GetEndAngle(), VSpline::GetKasm1(), VSpline::GetKasm2(), VSpline::GetKcurve(), GetP1(), GetP4(), VSpline::GetStartAngle(), newDuplicate, SCASSERT, VAbstractCurve::SetDuplicate(), Show, spl, and DialogTool::vis.
setLineColor()
void DialogSpline::setLineColor (const QString & value)
Definition at line 677 of file dialogspline.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setLineWeight()
void DialogSpline::setLineWeight (const QString & value)
setLineWeight set weight of the lines
Parameters
value type
Definition at line 697 of file dialogspline.cpp.
References DialogTool::ChangeCurrentData(), ui, and DialogTool::vis.
setPenStyle()
void DialogSpline::setPenStyle (const QString & value)
Definition at line 665 of file dialogspline.cpp.
References DialogTool::ChangeCurrentData(), and ui.
SetSpline()
void DialogSpline::SetSpline (const VSpline & spline)
Definition at line 622 of file dialogspline.cpp.
References VSpline::GetC1LengthFormula(), VSpline::GetC2LengthFormula(), VSpline::GetEndAngle(), VSpline::GetEndAngleFormula(), VSpline::GetKasm1(), VSpline::GetKasm2(), VSpline::GetKcurve(), VSpline::GetP1(), VSpline::GetP4(), VSpline::GetStartAngle(), VSpline::GetStartAngleFormula(), VGObject::id(), VGObject::name(), qApp, SCASSERT, DialogTool::setCurrentPointId(), spl, ui, and DialogTool::vis.
ShowDialog
void DialogSpline::ShowDialog (bool click) virtual slot
Definition at line 565 of file dialogspline.cpp.
References DialogTool::data, DialogTool::DialogAccepted(), DialogTool::DNumber(), VSpline::GetC1LengthFormula(), VSpline::GetC2LengthFormula(), VSpline::GetEndAngleFormula(), GetP1(), GetP4(), VSpline::GetStartAngleFormula(), VContainer::IsUnique(), VGObject::name(), DialogTool::prepare, qApp, SCASSERT, VAbstractCurve::SetDuplicate(), spl, ui, and DialogTool::vis.
ShowVisualization()
void DialogSpline::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 610 of file dialogspline.cpp.
Member Data Documentation
flagAngle1
bool DialogSpline::flagAngle1 private
flagAngle1 true if value of first angle is correct
Definition at line 145 of file dialogspline.h.
Referenced by Angle1Changed(), CheckState(), and EvalAngle1().
flagAngle2
bool DialogSpline::flagAngle2 private
Definition at line 146 of file dialogspline.h.
Referenced by Angle2Changed(), CheckState(), and EvalAngle2().
flagLength1
bool DialogSpline::flagLength1 private
Definition at line 147 of file dialogspline.h.
Referenced by CheckState(), EvalLength1(), and Length1Changed().
flagLength2
bool DialogSpline::flagLength2 private
Definition at line 148 of file dialogspline.h.
Referenced by CheckState(), EvalLength2(), and Length2Changed().
formulaBaseHeightAngle1
int DialogSpline::formulaBaseHeightAngle1 private
formulaBaseHeight base height defined by dialogui
Definition at line 133 of file dialogspline.h.
Referenced by DeployAngle1TextEdit(), and DialogSpline().
formulaBaseHeightAngle2
int DialogSpline::formulaBaseHeightAngle2 private
Definition at line 134 of file dialogspline.h.
Referenced by DeployAngle2TextEdit(), and DialogSpline().
formulaBaseHeightLength1
int DialogSpline::formulaBaseHeightLength1 private
Definition at line 135 of file dialogspline.h.
Referenced by DeployLength1TextEdit(), and DialogSpline().
formulaBaseHeightLength2
int DialogSpline::formulaBaseHeightLength2 private
Definition at line 136 of file dialogspline.h.
Referenced by DeployLength2TextEdit(), and DialogSpline().
newDuplicate
qint32 DialogSpline::newDuplicate private
spl spline
Definition at line 130 of file dialogspline.h.
Referenced by PointNameChanged(), and SaveData().
spl
VSpline DialogSpline::spl private
ui keeps information about user interface
Definition at line 129 of file dialogspline.h.
Referenced by GetSpline(), PointNameChanged(), SaveData(), SetSpline(), and ShowDialog().
timerAngle1
QTimer* DialogSpline::timerAngle1 private
timerAngle1 timer of check first angle formula
Definition at line 139 of file dialogspline.h.
Referenced by Angle1Changed(), and DialogSpline().
timerAngle2
QTimer* DialogSpline::timerAngle2 private
Definition at line 140 of file dialogspline.h.
Referenced by Angle2Changed(), and DialogSpline().
timerLength1
QTimer* DialogSpline::timerLength1 private
Definition at line 141 of file dialogspline.h.
Referenced by DialogSpline(), and Length1Changed().
timerLength2
QTimer* DialogSpline::timerLength2 private
Definition at line 142 of file dialogspline.h.
Referenced by DialogSpline(), and Length2Changed().
ui
Ui::DialogSpline* DialogSpline::ui private
Definition at line 128 of file dialogspline.h.
Referenced by Angle1Changed(), Angle2Changed(), ChosenObject(), closeEvent(), CurrentSpline(), DeployAngle1TextEdit(), DeployAngle2TextEdit(), DeployLength1TextEdit(), DeployLength2TextEdit(), DialogSpline(), EvalAngle1(), EvalAngle2(), EvalLength1(), EvalLength2(), FXAngle1(), FXAngle2(), FXLength1(), FXLength2(), getLineColor(), getLineWeight(), GetP1(), GetP4(), getPenStyle(), Length1Changed(), Length2Changed(), PointNameChanged(), setLineColor(), setLineWeight(), setPenStyle(), SetSpline(), ShowDialog(), and ~DialogSpline().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogspline.h
src/libs/vtools/dialogs/tools/dialogspline.cpp