Seamly2D: src/app/seamly2d/mainwindow.cpp File Reference
mainwindow.cpp File Reference
#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "../vgeometry/vspline.h"
#include "../ifc/exception/vexceptionobjecterror.h"
#include "../ifc/exception/vexceptionconversionerror.h"
#include "../ifc/exception/vexceptionemptyparameter.h"
#include "../ifc/exception/vexceptionwrongid.h"
#include "../ifc/exception/vexceptionundo.h"
#include "version.h"
#include "core/vapplication.h"
#include "../vmisc/customevents.h"
#include "../vmisc/vsettings.h"
#include "../vmisc/def.h"
#include "../vmisc/qxtcsvmodel.h"
#include "../vmisc/dialogs/dialogexporttocsv.h"
#include "undocommands/rename_draftblock.h"
#include "core/vtooloptionspropertybrowser.h"
#include "options.h"
#include "../ifc/xml/vpatternconverter.h"
#include "../vmisc/logging.h"
#include "../vformat/measurements.h"
#include "../ifc/xml/multi_size_converter.h"
#include "../ifc/xml/individual_size_converter.h"
#include "../vwidgets/vwidgetpopup.h"
#include "../vwidgets/vmaingraphicsscene.h"
#include "../vwidgets/mouse_coordinates.h"
#include "../vtools/tools/drawTools/drawtools.h"
#include "../vtools/dialogs/tooldialogs.h"
#include "tools/pattern_piece_tool.h"
#include "tools/nodeDetails/vtoolinternalpath.h"
#include "tools/nodeDetails/anchorpoint_tool.h"
#include "tools/union_tool.h"
#include "dialogs/dialogs.h"
#include "../vtools/undocommands/addgroup.h"
#include "../vtools/undocommands/label/showpointname.h"
#include "../vpatterndb/vpiecepath.h"
#include "../qmuparser/qmuparsererror.h"
#include "../vtools/dialogs/support/editlabeltemplate_dialog.h"
#include <QInputDialog>
#include <QtDebug>
#include <QMessageBox>
#include <QShowEvent>
#include <QScrollBar>
#include <QFileDialog>
#include <QSourceLocation>
#include <QUndoStack>
#include <QAction>
#include <QProcess>
#include <QSettings>
#include <QTimer>
#include <QtGlobal>
#include <QDesktopWidget>
#include <QDesktopServices>
#include <chrono>
#include <thread>
#include <QFileSystemWatcher>
#include <QComboBox>
#include <QFontComboBox>
#include <QTextCodec>
#include <QDoubleSpinBox>
#include <QSharedPointer>
Variables
QT_WARNING_PUSH QT_WARNING_POP const QString autosavePrefix = QStringLiteral(".autosave")
const QString strQShortcut = QStringLiteral("QShortcut")
const QString strCtrl = QStringLiteral("Ctrl")
Variable Documentation
autosavePrefix
QT_WARNING_PUSH QT_WARNING_POP const QString autosavePrefix = QStringLiteral(".autosave")
Definition at line 133 of file mainwindow.cpp.
Referenced by MainWindow::AutoSavePattern(), MainWindow::FileClosedCorrect(), MainWindow::ReopenFilesAfterCrash(), MainWindow::Save(), and MainWindow::SaveAs().
strCtrl
const QString strCtrl = QStringLiteral("Ctrl")
Definition at line 137 of file mainwindow.cpp.
Referenced by MainWindow::handleGroupTool(), MainWindow::handleInsertNodesTool(), MainWindow::handleMirrorByAxisTool(), MainWindow::handleMirrorByLineTool(), MainWindow::handleMoveTool(), and MainWindow::handleRotationTool().
strQShortcut
const QString strQShortcut = QStringLiteral("QShortcut")
Definition at line 136 of file mainwindow.cpp.
Referenced by MainWindow::handleGroupTool(), MainWindow::handleInsertNodesTool(), MainWindow::handleMirrorByAxisTool(), MainWindow::handleMirrorByLineTool(), MainWindow::handleMoveTool(), and MainWindow::handleRotationTool().