Seamly2D: SavePiecePathOptions Class Reference
SavePiecePathOptions Class Reference
#include <savepiecepathoptions.h>
Public Member Functions
SavePiecePathOptions (const VPiecePath &oldPath, const VPiecePath &newPath, VAbstractPattern *doc, VContainer *data, quint32 id, QUndoCommand *parent=nullptr)
virtual ~SavePiecePathOptions ()
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
virtual bool mergeWith (const QUndoCommand *command) Q_DECL_OVERRIDE
virtual int id () const Q_DECL_OVERRIDE
quint32 PathId () const
VPiecePath NewPath () const
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Attributes
const VPiecePath m_oldPath
VPiecePath m_newPath
VContainer * m_data
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 60 of file savepiecepathoptions.h.
Constructor & Destructor Documentation
SavePiecePathOptions()
SavePiecePathOptions::SavePiecePathOptions (const VPiecePath & oldPath, const VPiecePath & newPath, VAbstractPattern * doc, VContainer * data, quint32 id, QUndoCommand * parent = nullptr)
Definition at line 63 of file savepiecepathoptions.cpp.
References id(), and VUndoCommand::nodeId.
~SavePiecePathOptions()
SavePiecePathOptions::~SavePiecePathOptions () virtual
Definition at line 76 of file savepiecepathoptions.cpp.
Member Function Documentation
id()
int SavePiecePathOptions::id () const virtual
Definition at line 144 of file savepiecepathoptions.cpp.
References SavePiecePathOptions.
Referenced by SavePiecePathOptions().
mergeWith()
bool SavePiecePathOptions::mergeWith (const QUndoCommand * command) virtual
Definition at line 128 of file savepiecepathoptions.cpp.
References m_newPath, NewPath(), VUndoCommand::nodeId, PathId(), and SCASSERT.
NewPath()
VPiecePath SavePiecePathOptions::NewPath () const
Definition at line 156 of file savepiecepathoptions.cpp.
References m_newPath.
Referenced by mergeWith().
PathId()
quint32 SavePiecePathOptions::PathId () const
Definition at line 150 of file savepiecepathoptions.cpp.
References VUndoCommand::nodeId.
Referenced by mergeWith().
redo()
void SavePiecePathOptions::redo () virtual
Definition at line 104 of file savepiecepathoptions.cpp.
References VToolInternalPath::AddAttributes(), VAbstractTool::AddNodes(), VUndoCommand::DecrementReferences(), VUndoCommand::doc, VDomDocument::elementById(), m_data, m_newPath, m_oldPath, VPiecePath::MissingNodes(), VUndoCommand::nodeId, VDomDocument::RemoveAllChildren(), SCASSERT, VAbstractPattern::TagPath, and VContainer::UpdatePiecePath().
undo()
void SavePiecePathOptions::undo () virtual
Definition at line 80 of file savepiecepathoptions.cpp.
References VToolInternalPath::AddAttributes(), VAbstractTool::AddNodes(), VUndoCommand::doc, VDomDocument::elementById(), VUndoCommand::IncrementReferences(), m_data, m_newPath, m_oldPath, VPiecePath::MissingNodes(), VUndoCommand::nodeId, VDomDocument::RemoveAllChildren(), SCASSERT, VAbstractPattern::TagPath, and VContainer::UpdatePiecePath().
Member Data Documentation
m_data
VContainer* SavePiecePathOptions::m_data private
Definition at line 79 of file savepiecepathoptions.h.
Referenced by redo(), and undo().
m_newPath
VPiecePath SavePiecePathOptions::m_newPath private
Definition at line 77 of file savepiecepathoptions.h.
Referenced by mergeWith(), NewPath(), redo(), and undo().
m_oldPath
const VPiecePath SavePiecePathOptions::m_oldPath private
Definition at line 76 of file savepiecepathoptions.h.
Referenced by redo(), and undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/savepiecepathoptions.h
src/libs/vtools/undocommands/savepiecepathoptions.cpp