Seamly2D: VTranslateMeasurements Class Reference
VTranslateMeasurements Class Reference
Manages the translation of measurement-related strings.
#include <vtranslatemeasurements.h>
Public Member Functions
VTranslateMeasurements ()
Constructs a VTranslateMeasurements object.
virtual ~VTranslateMeasurements ()
Destructor for VTranslateMeasurements.
bool MeasurementsFromUser (QString &newFormula, int position, const QString &token, int &bias) const
Translates a user-provided measurement token into an internal representation.
QString MToUser (const QString &measurement) const
Translates an internal measurement representation to a user-friendly string.
QString MNumber (const QString &measurement) const
Retrieves the number associated with a given measurement.
QString MFormula (const QString &measurement) const
Retrieves the formula associated with a given measurement.
QString guiText (const QString &measurement) const
Retrieves the GUI text associated with a given measurement.
QString Description (const QString &measurement) const
Retrieves the description associated with a given measurement.
virtual void Retranslate ()
Retranslates all measurement-related data.
Protected Attributes
QMap< QString, qmu::QmuTranslation > m_measurements
Private Member Functions
void InitGroupA ()
Initialize group A measurements.
void InitGroupB ()
Initialize group B measurements.
void InitGroupC ()
Initialize group C measurements.
void InitGroupD ()
Initialize group D measurements.
void InitGroupE ()
Initialize group E measurements.
void InitGroupF ()
Initialize group F measurements.
void InitGroupG ()
Initialize group G measurements.
void InitGroupH ()
Initialize group H measurements.
void InitGroupI ()
Initialize group I measurements.
void InitGroupJ ()
Initialize group J measurements.
void InitGroupK ()
Initialize group K measurements.
void InitGroupL ()
Initialize group L measurements.
void InitGroupM ()
Initialize group M measurements.
void InitGroupN ()
Initialize group N measurements.
void InitGroupO ()
Initialize group O measurements.
void InitGroupP ()
Initialize group P measurements.
void InitGroupQ ()
Initialize group Q measurements.
void InitMeasurements ()
Initializes all measurement groups.
void InitMeasurement (const QString &name, const qmu::QmuTranslation &m, const qmu::QmuTranslation &g, const qmu::QmuTranslation &d, const QString &number, const QString &formula=QString())
Initializes a single measurement with its related data.
Private Attributes
QMap< QString, qmu::QmuTranslation > m_guiTexts
QMap< QString, qmu::QmuTranslation > m_descriptions
QMap< QString, QString > m_numbers
QMap< QString, QString > m_formulas
Detailed Description
Manages the translation of measurement-related strings.
The VTranslateMeasurements class provides methods for translating and manipulating measurement-related strings. It includes functionality for converting measurements from user input, retrieving measurement names, numbers, formulas, GUI text, and descriptions, as well as re-translating measurements.
The class stores various translations and mappings related to measurements.
It includes methods for initializing measurement groups and individual measurements.
VTranslateMeasurements();
virtual ~VTranslateMeasurements();
bool MeasurementsFromUser(QString &newFormula, int position, const QString &token, int &bias) const;
QString MToUser(const QString &measurement) const;
QString MNumber(const QString &measurement) const;
QString MFormula(const QString &measurement) const;
QString guiText(const QString &measurement) const;
QString Description(const QString &measurement) const;
virtual void Retranslate();
QMap<QString, qmu::QmuTranslation> m_measurements;
Q_DISABLE_COPY(VTranslateMeasurements)
QMap<QString, qmu::QmuTranslation> m_guiTexts;
QMap<QString, qmu::QmuTranslation> m_descriptions;
QMap<QString, QString> m_numbers;
QMap<QString, QString> m_formulas;
void InitGroupA(); // Direct Height
void InitGroupB(); // Direct Width
void InitGroupC(); // Indentation
void InitGroupD(); // Circumference and Arc
void InitGroupE(); // Vertical
void InitGroupF(); // Horizontal
void InitGroupG(); // Bust
void InitGroupH(); // Balance
void InitGroupI(); // Arm
void InitGroupJ(); // Leg
void InitGroupK(); // Crotch and Rise
void InitGroupL(); // Hand
void InitGroupM(); // Foot
void InitGroupN(); // Head
void InitGroupO(); // Men & Tailoring
void InitGroupP(); // Historical & Specialty
void InitGroupQ(); // Patternmaking measurements
void InitMeasurements();
void InitMeasurement(const QString &name, const qmu::QmuTranslation &m, const qmu::QmuTranslation &g, const qmu::QmuTranslation &d, const QString &number, const QString &formula = QString());
Definition at line 117 of file vtranslatemeasurements.h.
Constructor & Destructor Documentation
VTranslateMeasurements()
VTranslateMeasurements::VTranslateMeasurements ()
Constructs a VTranslateMeasurements object.
This constructor initializes a VTranslateMeasurements instance by setting up the internal maps for measurements, GUI texts, descriptions, numbers, and formulas. It also calls the InitMeasurements method to initialize measurement data.
The constructor initializes the following member variables:
m_measurements: A QMap to store measurement translations.
m_guiTexts: A QMap to store GUI text translations.
m_descriptions: A QMap to store description translations.
m_numbers: A QMap to store measurement numbers.
m_formulas: A QMap to store measurement formulas.
The InitMeasurements method is called to populate these maps with initial data.
Definition at line 75 of file vtranslatemeasurements.cpp.
References InitMeasurements().
~VTranslateMeasurements()
VTranslateMeasurements::~VTranslateMeasurements () virtual
Destructor for VTranslateMeasurements.
This method handles cleanup when a VTranslateMeasurements object is destroyed.
The destructor is defined but currently does not perform any specific actions.
It ensures that any resources managed by VTranslateMeasurements are properly released when the object is destroyed.
Definition at line 94 of file vtranslatemeasurements.cpp.
Member Function Documentation
Description()
QString VTranslateMeasurements::Description (const QString & measurement) const
Retrieves the description associated with a given measurement.
This method returns the description associated with the specified measurement.
Parameters
measurement The measurement for which to retrieve the description.
Returns
QString The description associated with the measurement, or the original measurement string if not found.
The method checks if the m_descriptions map contains the specified measurement.
If the measurement is found, it returns the translated description.
If the measurement is not found, it returns the original measurement string.
Definition at line 237 of file vtranslatemeasurements.cpp.
References m_descriptions.
Referenced by MeasurementDatabaseDialog::showDescription().
guiText()
QString VTranslateMeasurements::guiText (const QString & measurement) const
Retrieves the GUI text associated with a given measurement.
This method returns the GUI text associated with the specified measurement.
Parameters
measurement The measurement for which to retrieve the GUI text.
Returns
QString The GUI text associated with the measurement, or the original measurement string if not found.
The method checks if the m_guiTexts map contains the specified measurement.
If the measurement is found, it returns the translated GUI text.
If the measurement is not found, it returns the original measurement string.
Definition at line 212 of file vtranslatemeasurements.cpp.
References m_guiTexts.
Referenced by MeasurementDatabaseDialog::showDescription(), and TMainWindow::ShowMDiagram().
InitGroupA()
void VTranslateMeasurements::InitGroupA () private
Initialize group A measurements.
This function sets up the translations for various height measurements. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Height: Total: Measures the vertical distance from the crown of the head to the floor.
Height: Neck Back: Measures the vertical distance from the neck back (cervicale vertebra) to the floor.
Height: Scapula: Measures the vertical distance from the scapula (blade point) to the floor.
Height: Armpit: Measures the vertical distance from the armpit to the floor.
Height: Waist Side: Measures the vertical distance from the waist side to the floor.
Height: Hip: Measures the vertical distance from the hip level to the floor.
Height: Gluteal Fold: Measures the vertical distance from the gluteal fold to the floor.
Height: Knee: Measures the vertical distance from the fold at the back of the knee to the floor.
Height: Calf: Measures the vertical distance from the widest point of the calf to the floor.
Height: Ankle High: Measures the vertical distance from the deepest indentation of the back of the ankle to the floor.
Height: Ankle: Measures the vertical distance from the point where the front leg meets the foot to the floor.
Height: Highhip: Measures the vertical distance from the highhip level to the floor.
Height: Waist Front: Measures the vertical distance from the waist front to the floor.
Height: Bustpoint: Measures the vertical distance from the bustpoint to the floor.
Height: Shoulder Tip: Measures the vertical distance from the shoulder tip to the floor.
Height: Neck Front: Measures the vertical distance from the neck front to the floor.
Height: Neck Side: Measures the vertical distance from the neck side to the floor.
Height: Neck Back to Knee: Measures the vertical distance from the neck back to the fold at the back of the knee.
Height: Waist Side to Knee: Measures the vertical distance from the waist side to the fold at the back of the knee.
Height: Waist Side to Hip: Measures the vertical distance from the waist side to the hip level.
Height: Knee to Ankle: Measures the vertical distance from the fold at the back of the knee to the point where the front leg meets the foot.
Height: Neck Back to Waist Side: Measures the vertical distance from the neck back to the waist side.
Height: Waist Back: Measures the vertical height from the waist back to the floor.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 394 of file vtranslatemeasurements.cpp.
References height_M, heightAnkle_M, heightAnkleHigh_M, heightArmpit_M, heightBustpoint_M, heightCalf_M, heightGlutealFold_M, heightHighhip_M, heightHip_M, heightKnee_M, heightKneeToAnkle_M, heightNeckBack_M, heightNeckBackToKnee_M, heightNeckBackToWaistSide_M, heightNeckFront_M, heightNeckSide_M, heightScapula_M, heightShoulderTip_M, heightWaistBack_M, heightWaistFront_M, heightWaistSide_M, heightWaistSideToHip_M, heightWaistSideToKnee_M, InitMeasurement(), and translate.
Referenced by InitMeasurements().
InitGroupB()
void VTranslateMeasurements::InitGroupB () private
Initialize group B measurements.
This function sets up the translations for various body width measurements. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Width: Shoulder: Measures the horizontal distance from shoulder tip to shoulder tip.
Width: Bust: Measures the horizontal distance from bust side to bust side.
Width: Waist: Measures the horizontal distance from waist side to waist side.
Width: Hip: Measures the horizontal distance from hip side to hip side.
Width: Abdomen to Hip: Measures the horizontal distance from the greatest abdomen prominence to the greatest hip prominence.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 583 of file vtranslatemeasurements.cpp.
References InitMeasurement(), translate, widthAbdomenToHip_M, widthBust_M, widthHip_M, widthShoulder_M, and widthWaist_M.
Referenced by InitMeasurements().
InitGroupC()
void VTranslateMeasurements::InitGroupC () private
Initialize group C measurements.
This function sets up the translations for various body indentation measurements. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Indent: Neck Back: Measures the horizontal distance from the scapula (blade point) to the back of the neck.
Indent: Waist Back: Measures the horizontal distance between a flat stick, placed to touch the hip and scapula, and the back of the waist.
Indent: Ankle High: Measures the horizontal distance between a flat stick, placed perpendicular to the heel, and the greatest indentation of the ankle.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 644 of file vtranslatemeasurements.cpp.
References indentAnkleHigh_M, indentNeckBack_M, indentWaistBack_M, InitMeasurement(), and translate.
Referenced by InitMeasurements().
InitGroupD()
void VTranslateMeasurements::InitGroupD () private
Initialize group D measurements.
This function sets up the translations for various hand measurements. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Hand Palm Length: Measures the length from the wrist line to the base of the middle finger.
Hand Length: Measures the length from the wrist line to the end of the middle finger.
Hand Palm Width: Measures the width of the palm at its widest part.
Hand Palm Circumference: Measures the circumference of the palm at its widest part.
Hand Circumference: Measures the circumference around the widest part of the hand with the thumb tucked toward the smallest finger and the fingers close together.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 693 of file vtranslatemeasurements.cpp.
References handCirc_M, handLength_M, handPalmCirc_M, handPalmLength_M, handPalmWidth_M, InitMeasurement(), and translate.
Referenced by InitMeasurements().
InitGroupE()
void VTranslateMeasurements::InitGroupE () private
Initialize group E measurements.
This function sets up the translations for various foot measurements. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Foot Width: Measures the width at the widest part of the foot.
Foot Length: Measures the length from the back of the heel to the end of the longest toe.
Foot Circumference: Measures the circumference around the widest part of the foot.
Foot Instep Circumference: Measures the circumference at the tallest part of the instep.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 753 of file vtranslatemeasurements.cpp.
References footCirc_M, footInstepCirc_M, footLength_M, footWidth_M, InitMeasurement(), and translate.
Referenced by InitMeasurements().
InitGroupF()
void VTranslateMeasurements::InitGroupF () private
Initialize group F measurements.
This function sets up the translations for various head measurements. The function ensures that each measurement has a corresponding translated name and description, which are required for accurate data representation in different languages.
The measurements initialized in this function include:
Head Circumference: Measures the circumference at the largest level of the head.
Head Length: Measures the vertical distance from the head crown to the bottom of the jaw.
Head Depth: Measures the horizontal distance from the front of the forehead to the back of the head.
Head Width: Measures the horizontal distance from one side of the head to the other at its widest part.
Head Crown to Neck Back: Measures the vertical distance from the crown of the head to the back of the neck.
Head Chin to Neck Back: Measures the vertical distance from the chin to the back of the neck.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 810 of file vtranslatemeasurements.cpp.
References headChinToNeckBack_M, headCirc_M, headCrownToNeckBack_M, headDepth_M, headLength_M, headWidth_M, InitMeasurement(), and translate.
Referenced by InitMeasurements().
InitGroupG()
void VTranslateMeasurements::InitGroupG () private
Initialize group G measurements.
This function sets up the translations for various body circumference and arc measurements. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Neck circumference, midsection: Measures the circumference of the neck midsection, about halfway between jaw and torso.
Neck circumference: Measures the neck circumference at the base of the neck, touching the neck back, sides, and front.
Highbust circumference: Measures the circumference at highbust, following the shortest distance between armfolds across the chest, high under armpits.
Bust circumference: Measures the circumference around the bust, parallel to the floor.
Lowbust circumference: Measures the circumference around the lowbust under the breasts, parallel to the floor.
Rib circumference: Measures the circumference around the ribs at the level of the lowest rib at the side, parallel to the floor.
Waist circumference: Measures the circumference around the waist, following natural contours, typically higher in back.
Highhip circumference: Measures the circumference around the highhip where abdomen protrusion is greatest, parallel to the floor.
Hip circumference: Measures the circumference around the hip where hip protrusion is greatest, parallel to the floor.
Various arcs: Measures arcs around the neck, highbust, bust, lowbust, rib, waist, highhip, and hip from side to side across the front and back.
Body circumference at armfold level: Measures around the arms and torso at armfold level.
Body circumference at bust level: Measures around the arms and torso at bust level.
Body circumference of full torso: Measures the circumference around the torso from mid-shoulder around the crotch back up to mid-shoulder.
Hip circumference, including abdomen: Measures at the hip level, including the depth of the abdomen.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 890 of file vtranslatemeasurements.cpp.
References bodyArmfoldCirc_M, bodyBustCirc_M, bodyTorsoCirc_M, bustArcB_M, bustArcF_M, bustArcHalfB_M, bustArcHalfF_M, bustCirc_M, highbustArcB_M, highbustArcF_M, highbustArcHalfB_M, highbustArcHalfF_M, highbustCirc_M, highhipArcB_M, highhipArcF_M, highhipArcHalfB_M, highhipArcHalfF_M, highhipCirc_M, hipArcB_M, hipArcF_M, hipArcHalfB_M, hipArcHalfF_M, hipCirc_M, hipCircWithAbdomen_M, hipWithAbdomenArcF_M, InitMeasurement(), lowbustArcB_M, lowbustArcF_M, lowbustArcHalfB_M, lowbustArcHalfF_M, lowbustCirc_M, neckArcB_M, neckArcF_M, neckArcHalfB_M, neckArcHalfF_M, neckCirc_M, neckMidCirc_M, ribArcB_M, ribArcF_M, ribArcHalfB_M, ribArcHalfF_M, ribCirc_M, size_M, translate, waistArcB_M, waistArcF_M, waistArcHalfB_M, waistArcHalfF_M, and waistCirc_M.
Referenced by InitMeasurements().
InitGroupH()
void VTranslateMeasurements::InitGroupH () private
Initialize group H measurements.
This function sets up the translations for various measurements from the neck, shoulder, and torso regions to other body parts. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Neck Front to Waist Front: Measures from the neck front, over tape between breast points, down to waist front.
Neck Front to Waist Front flat: Measures from the neck front down between breasts to waist front.
Armpit to Waist Side: Measures from the armpit down to the waist side.
Shoulder Tip to Waist Side, front: Measures from the shoulder tip, curving around the armscye front, then down to the waist side.
Neck Side to Waist level, front: Measures from the neck side straight down front to the waist level.
Neck Side to Waist level, through Bustpoint: Measures from the neck side over the bust point to the waist level, forming a straight line.
Neck Front to Highbust Front: Measures from the neck front down to the highbust front.
Highbust Front to Waist Front: Measures from the highbust front to the waist front, using tape to bridge the gap between bust points.
Neck Front to Bust Front: Measures from the neck front down to the bust front, requiring tape to cover the gap between bust points.
Bust Front to Waist Front: Measures from the bust front down to the waist level.
Lowbust Front to Waist Front: Measures from the lowbust front down to the waist front.
Rib Side to Waist Side: Measures from the lowest rib at the side down to the waist side.
Shoulder Tip to Armfold Front: Measures from the shoulder tip around the armscye down to the armfold front.
Neck Side to Bust level, front: Measures from the neck side straight down front to the bust level.
Neck Side to Highbust level, front: Measures from the neck side straight down front to the highbust level.
Shoulder center to Highbust level, front: Measures from the mid-shoulder down front to the highbust level, aimed at the bust point.
Shoulder Tip to Waist Side, back: Measures from the shoulder tip, curving around the armscye back, then down to the waist side.
Neck Side to Waist level, back: Measures from the neck side straight down back to the waist level.
Neck Back to Waist Back: Measures from the neck back down to the waist back.
Neck Side to Waist level, through Scapula: Measures from the neck side across the scapula down to the waist level, forming a straight line.
Neck Back to Highbust Back: Measures from the neck back down to the highbust back.
Highbust Back to Waist Back: Measures from the highbust back down to the waist back.
Neck Back to Bust Back: Measures from the neck back down to the bust back.
Bust Back to Waist Back: Measures from the bust back down to the waist level.
Lowbust Back to Waist Back: Measures from the lowbust back down to the waist back.
Shoulder Tip to Armfold Back: Measures from the shoulder tip around the armscye down to the armfold back.
Neck Side to Bust level, back: Measures from the neck side straight down back to the bust level.
Neck Side to Highbust level, back: Measures from the neck side straight down back to the highbust level.
Shoulder center to Highbust level, back: Measures from the mid-shoulder down back to the highbust level, aimed through the scapula.
Waist Front to Highhip Front: Measures from the waist front to the highhip front.
Waist Front to Hip Front: Measures from the waist front to the hip front.
Waist Side to Highhip Side: Measures from the waist side to the highhip side.
Waist Back to Highhip Back: Measures from the waist back down to the highhip back.
Waist Back to Hip Back: Measures from the waist back down to the hip back, requiring tape to cover the gap between the buttocks.
Waist Side to Hip Side: Measures from the waist side to the hip side.
Shoulder Slope Angle from Neck Side: Measures the angle formed by the line from the neck side to the shoulder tip and the line from the neck side parallel to the floor.
Shoulder Slope length from Neck Side: Measures the vertical distance between the neck side and the shoulder tip.
Shoulder Slope Angle from Neck Back: Measures the angle formed by the line from the neck back to the shoulder tip and the line from the neck back parallel to the floor.
Shoulder Slope length from Neck Back: Measures the vertical distance between the neck back and the shoulder tip.
Shoulder Slope Angle from Shoulder Tip: Measures the angle formed by the line from the neck side to the shoulder tip and the vertical line at the shoulder tip.
Neck Back to Across Back: Measures from the neck back down to the level of the across back measurement.
Across Back to Waist back: Measures from the middle of the across back down to the waist back.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 1303 of file vtranslatemeasurements.cpp.
References acrossBackToWaistB_M, armpitToWaistSide_M, bustToWaistB_M, bustToWaistF_M, highbustToWaistB_M, highbustToWaistF_M, InitMeasurement(), lowbustToWaistB_M, lowbustToWaistF_M, neckBackToAcrossBack_M, neckBackToBustB_M, neckBackToHighbustB_M, neckBackToWaistB_M, neckFrontToBustF_M, neckFrontToHighbustF_M, neckFrontToWaistF_M, neckFrontToWaistFlatF_M, neckSideToBustB_M, neckSideToBustF_M, neckSideToHighbustB_M, neckSideToHighbustF_M, neckSideToWaistB_M, neckSideToWaistBustpointF_M, neckSideToWaistF_M, neckSideToWaistScapulaB_M, ribToWaistSide_M, shoulderCenterToHighbustB_M, shoulderCenterToHighbustF_M, shoulderSlopeNeckBackAngle_M, shoulderSlopeNeckBackHeight_M, shoulderSlopeNeckSideAngle_M, shoulderSlopeNeckSideLength_M, shoulderSlopeShoulderTipAngle_M, shoulderTipToArmfoldB_M, shoulderTipToArmfoldF_M, shoulderTipToWaistSideB_M, shoulderTipToWaistSideF_M, translate, waistToHighhipB_M, waistToHighhipF_M, waistToHighhipSide_M, waistToHipB_M, waistToHipF_M, and waistToHipSide_M.
Referenced by InitMeasurements().
InitGroupI()
void VTranslateMeasurements::InitGroupI () private
Initialize group I measurements.
This function sets up the translations for various measurements related to the shoulders, chest, and back. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Shoulder length: Measures from the neck side to the shoulder tip.
Shoulder Tip to Shoulder Tip, front: Measures from shoulder tip to shoulder tip across the front.
Across Chest: Measures from armscye to armscye at the narrowest width across the chest.
Armfold to Armfold, front: Measures the shortest distance between armfolds across the front.
Shoulder Tip to Shoulder Tip, front, half: Measures half the distance from shoulder tip to shoulder tip across the front.
Across Chest, half: Measures half the width across the chest.
Shoulder Tip to Shoulder Tip, back: Measures from shoulder tip to shoulder tip across the back.
Across Back: Measures from armscye to armscye at the narrowest width of the back.
Armfold to Armfold, back: Measures from armfold to armfold across the back.
Shoulder Tip to Shoulder Tip, back, half: Measures half the distance from shoulder tip to shoulder tip across the back.
Across Back, half: Measures half the width across the back.
Neck Front to Shoulder Tip: Measures from the neck front to the shoulder tip.
Neck Back to Shoulder Tip: Measures from the neck back to the shoulder tip.
Neck Width: Measures the width between the "legs" of an unclosed necklace or chain draped around the neck.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 1634 of file vtranslatemeasurements.cpp.
References acrossBackB_M, acrossBackHalfB_M, acrossChestF_M, acrossChestHalfF_M, armfoldToArmfoldB_M, armfoldToArmfoldF_M, InitMeasurement(), neckBackToShoulderTipB_M, neckFrontToShoulderTipF_M, neckWidth_M, shoulderLength_M, shoulderTipToShoulderTipB_M, shoulderTipToShoulderTipF_M, shoulderTipToShoulderTipHalfB_M, shoulderTipToShoulderTipHalfF_M, and translate.
Referenced by InitMeasurements().
InitGroupJ()
void VTranslateMeasurements::InitGroupJ () private
Initialize group J measurements.
This function sets up the translations for various measurements related to the bust and its position relative to other body parts. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Bustpoint to Bustpoint: Measures the distance from one bustpoint to the other.
Bustpoint to Neck Side: Measures from the neck side to the bustpoint.
Bustpoint to Lowbust: Measures from the bustpoint down to the lowbust level, following the curve of the bust or chest.
Bustpoint to Waist level: Measures from the bustpoint straight down to the waist level, forming a straight line.
Bustpoint to Bustpoint, half: Measures half of the distance from one bustpoint to the other.
Bustpoint, Neck Side to Waist level: Measures from the neck side to the bustpoint, then straight down to the waist level.
Bustpoint to Shoulder Tip: Measures from the bustpoint to the shoulder tip.
Bustpoint to Waist Front: Measures from the bustpoint to the waist front, in a straight line.
Bustpoint to Bustpoint Halter: Measures from one bustpoint around the neck back down to the other bustpoint.
Bustpoint to Shoulder Center: Measures from the center of the shoulder to the bustpoint.
Bustpoint to Neck Front: Measures from the neck front to the bustpoint.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 1768 of file vtranslatemeasurements.cpp.
References bustpointNeckSideToWaist_M, bustpointToBustpoint_M, bustpointToBustpointHalf_M, bustpointToBustpointHalter_M, bustpointToLowbust_M, bustpointToNeckFront_M, bustpointToNeckSide_M, bustpointToShoulderCenter_M, bustpointToShoulderTip_M, bustpointToWaist_M, bustpointToWaistFront_M, InitMeasurement(), and translate.
Referenced by InitMeasurements().
InitGroupK()
void VTranslateMeasurements::InitGroupK () private
Initialize group K measurements.
This function sets up the translations for various diagonal measurements between the neck, shoulder, and waist regions, as well as measurements to armfold and bust side. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Shoulder Tip to Waist Front: Measures from the shoulder tip diagonally to the waist front.
Neck Front to Waist Side: Measures from the neck front diagonally to the waist side.
Neck Side to Waist Side, front: Measures from the neck side diagonally across the front to the waist side.
Shoulder Tip to Waist Back: Measures from the shoulder tip diagonally to the waist back.
Shoulder Tip to Waist Back, with 1in (2.54cm) offset: Measures from the shoulder tip diagonally to a point marked 1in (2.54cm) outward from the waist back.
Neck Back to Waist Side: Measures from the neck back diagonally across the back to the waist side.
Neck Side to Waist Side, back: Measures from the neck side diagonally across the back to the waist side.
Neck Side to Armfold Front: Measures from the neck side diagonally to the armfold front.
Neck Side to Highbust Side, front: Measures from the neck side diagonally across the front to the highbust side (armpit).
Neck Side to Bust Side, front: Measures from the neck side diagonally across the front to the bust side.
Neck Side to Armfold Back: Measures from the neck side diagonally to the armfold back.
Neck Side to Highbust Side, back: Measures from the neck side diagonally across the back to the highbust side (armpit).
Neck Side to Bust Side, back: Measures from the neck side diagonally across the back to the bust side.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 1880 of file vtranslatemeasurements.cpp.
References InitMeasurement(), neckBackToWaistSide_M, neckFrontToWaistSide_M, neckSideToArmfoldB_M, neckSideToArmfoldF_M, neckSideToArmpitB_M, neckSideToArmpitF_M, neckSideToBustSideB_M, neckSideToBustSideF_M, neckSideToWaistSideB_M, neckSideToWaistSideF_M, shoulderTipToWaistB_1inOffset_M, shoulderTipToWaistBack_M, shoulderTipToWaistFront_M, and translate.
Referenced by InitMeasurements().
InitGroupL()
void VTranslateMeasurements::InitGroupL () private
Initialize group L measurements.
This function sets up the translations for various arm measurements. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Arm: Shoulder Tip to Wrist, bent: Measures from the shoulder tip around the elbow to the radial wrist bone with the arm bent.
Arm: Shoulder Tip to Elbow, bent: Measures from the shoulder tip to the elbow tip with the arm bent.
Arm: Elbow to Wrist, bent: Measures from the elbow tip to the wrist with the arm bent.
Arm: Elbow circumference, bent: Measures the circumference of the elbow with the arm bent.
Arm: Shoulder Tip to Wrist: Measures from the shoulder tip to the wrist bone with the arm straight.
Arm: Shoulder Tip to Elbow: Measures from the shoulder tip to the elbow tip with the arm straight.
Arm: Elbow to Wrist: Measures from the elbow to the wrist with the arm straight.
Arm: Armpit to Wrist, inside: Measures from the armpit to the ulna wrist bone with the arm straight.
Arm: Armpit to Elbow, inside: Measures from the armpit to the inner elbow with the arm straight.
Arm: Elbow to Wrist, inside: Measures from the inside elbow to the wrist.
Arm: Upper Arm circumference: Measures the arm circumference at the armpit level.
Arm: Above Elbow circumference: Measures the arm circumference at the bicep level.
Arm: Elbow circumference: Measures the elbow circumference with the arm straight.
Arm: Lower Arm circumference: Measures the arm circumference where the lower arm is widest.
Arm: Wrist circumference: Measures the wrist circumference.
Arm: Shoulder Tip to Armfold line: Measures from the shoulder tip down to the armpit level.
Arm: Neck Side to Wrist: Measures from the neck side to the wrist.
Arm: Neck Side to Finger Tip: Measures from the neck side down the arm to the tip of the middle finger.
Armscye: Circumference: Measures the armscye circumference through the shoulder tip and armpit.
Armscye: Length: Measures the vertical distance from the shoulder tip to the armpit.
Armscye: Width: Measures the horizontal distance between the armscye front and armscye back.
Arm: Neck side to Elbow: Measures from the neck side over the shoulder tip down to the elbow.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 2017 of file vtranslatemeasurements.cpp.
References armAboveElbowCirc_M, armArmpitToElbow_M, armArmpitToWrist_M, armElbowCirc_M, armElbowCircBent_M, armElbowToWrist_M, armElbowToWristBent_M, armElbowToWristInside_M, armLowerCirc_M, armNeckSideToFingerTip_M, armNeckSideToOuterElbow_M, armNeckSideToWrist_M, armscyeCirc_M, armscyeLength_M, armscyeWidth_M, armShoulderTipToArmfoldLine_M, armShoulderTipToElbow_M, armShoulderTipToElbowBent_M, armShoulderTipToWrist_M, armShoulderTipToWristBent_M, armUpperCirc_M, armWristCirc_M, InitMeasurement(), and translate.
Referenced by InitMeasurements().
InitGroupM()
void VTranslateMeasurements::InitGroupM () private
Initialize group M measurements.
This function sets up the translations for various leg measurements. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Leg: Crotch to floor: Measures from crotch level down to the floor with feet close together.
Leg: Waist Side to floor: Measures from the waist side along the curve to the hip level, then straight down to the floor.
Leg: Thigh Upper circumference: Measures the thigh circumference at the fullest part of the upper thigh near the crotch.
Leg: Thigh Middle circumference: Measures the thigh circumference about halfway between the crotch and knee.
Leg: Knee circumference: Measures the knee circumference with a straight leg.
Leg: Knee Small circumference: Measures the leg circumference just below the knee.
Leg: Calf circumference: Measures the calf circumference at the largest part of the lower leg.
Leg: Ankle High circumference: Measures the ankle circumference where the indentation at the back of the ankle is the deepest.
Leg: Ankle circumference: Measures the ankle circumference where the front of the leg meets the top of the foot.
Leg: Knee circumference, bent: Measures the knee circumference with the leg bent.
Leg: Ankle diagonal circumference: Measures the ankle circumference diagonally from the top of the foot to the bottom of the heel.
Leg: Crotch to Ankle: Measures from the crotch to the ankle.
Leg: Waist Side to Ankle: Measures from the waist side to the ankle.
Leg: Waist Side to Knee: Measures from the waist side along the curve to the hip level, then straight down to the knee level.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 2210 of file vtranslatemeasurements.cpp.
References InitMeasurement(), legAnkleCirc_M, legAnkleDiagCirc_M, legAnkleHighCirc_M, legCalfCirc_M, legCrotchToAnkle_M, legCrotchToFloor_M, legKneeCirc_M, legKneeCircBent_M, legKneeSmallCirc_M, legThighMidCirc_M, legThighUpperCirc_M, legWaistSideToAnkle_M, legWaistSideToFloor_M, legWaistSideToKnee_M, and translate.
Referenced by InitMeasurements().
InitGroupN()
void VTranslateMeasurements::InitGroupN () private
Initialize group N measurements.
This function sets up the translations for various measurements related to the crotch and rise lengths. It ensures that each measurement has a corresponding translated name and description, which are essential for accurate data representation in different languages.
The measurements initialized in this function include:
Crotch length: Measures from the waist front down between the legs and up to the waist back with tape across the gap between the buttocks at hip level.
Crotch length, back: Measures from the waist back to mid-crotch.
Crotch length, front: Measures from the waist front to the start of the vagina or the end of the testicles.
Rise length, side, sitting: Measures from the waist side around the hip curve down to the surface while seated on a hard surface.
Rise length, diagonal: Measures from the waist side diagonally to a string tied at the top of the leg while seated on a hard surface.
Rise length, back: Measures the vertical distance from the waist back to the crotch level.
Rise length, front: Measures the vertical distance from the waist front to the crotch level.
Rise length, side: Measures the vertical distance from the waist side down to the crotch level.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 2340 of file vtranslatemeasurements.cpp.
References crotchLength_M, crotchLengthB_M, crotchLengthF_M, InitMeasurement(), riseLengthB_M, riseLengthDiag_M, riseLengthF_M, riseLengthSide_M, riseLengthSideSitting_M, and translate.
Referenced by InitMeasurements().
InitGroupO()
void VTranslateMeasurements::InitGroupO () private
Initialize group O measurements.
This function sets up the translations for various measurements related to the torso and arm, ensuring that each measurement has a corresponding translated name and description. These translations are crucial for accurate data representation in different languages.
The measurements initialized in this function include:
Neck Back to Waist Front: Measures from the neck back around the neck side down to the waist front.
Waist to Waist Halter: Measures from the waist level around the neck back to the waist level.
Natural Waist circumference: Measures the torso circumference at men's natural side abdominal obliques indentation or just below the navel level.
Natural Waist arc, front: Measures from side to side at the natural waist level across the front.
Natural Waist arc, back: Measures from side to side at natural waist level across the back.
Waist Front to Natural Waist Front: Measures the length from the waist front to the natural waist front.
Waist Back to Natural Waist Back: Measures the length from the waist back to the natural waist back.
Arm: Neck Back to Elbow, high bend: Measures from the neck back to the elbow tip with the arm bent and the elbow out.
Arm: Neck Back to Wrist, high bend: Measures from the neck back to the elbow tip to the wrist bone with the arm bent and the elbow out.
Arm: Neck Side to Elbow, high bend: Measures from the neck side to the elbow tip with the arm bent and the elbow out.
Arm: Neck Side to Wrist, high bend: Measures from the neck side to the elbow tip to the wrist bone with the arm bent and the elbow out.
Arm: Across Back Center to Elbow, high bend: Measures from the middle of the back to the elbow tip with the arm bent and the elbow out.
Arm: Across Back Center to Wrist, high bend: Measures from the middle of the back to the elbow tip to the wrist bone with the arm bent and the elbow out.
Arm: Armscye Back Center to Wrist, high bend: Measures from the armscye back to the elbow tip with the arm bent and the elbow out.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 2437 of file vtranslatemeasurements.cpp.
References armAcrossBackCenterToElbowBent_M, armAcrossBackCenterToWristBent_M, armArmscyeBackCenterToWristBent_M, armNeckBackToElbowBent_M, armNeckBackToWristBent_M, armNeckSideToElbowBent_M, armNeckSideToWristBent_M, InitMeasurement(), neckBackToWaistFront_M, translate, waistNaturalArcB_M, waistNaturalArcF_M, waistNaturalCirc_M, waistToNaturalWaistB_M, waistToNaturalWaistF_M, and waistToWaistHalter_M.
Referenced by InitMeasurements().
InitGroupP()
void VTranslateMeasurements::InitGroupP () private
Initialize group P measurements.
This function sets up the translations for various measurements related to different body dimensions, ensuring that each measurement has a corresponding translated name and description. These translations are crucial for accurate data representation in different languages.
The measurements initialized in this function include:
Neck Back to Bust Front: Measures from the neck back, over the shoulder, to the bust front.
Neck Back to Armfold Front: Measures from the neck back, over the shoulder, to the armfold front.
Neck Back, over Shoulder, to Waist Side: Measures from the neck back, over the shoulder, down the chest to the waist side.
Highbust Back, over Shoulder, to Armfold Front: Measures from the highbust back, over the shoulder, to the armfold front.
Highbust Back, over Shoulder, to Waist Front: Measures from the highbust back, over the shoulder touching the neck side, to the waist front.
Neck Back, to Armfold Front, to Neck Back: Measures from the neck back, over the shoulder to the armfold front, under the arm, and return to start.
Across Back Center, circled around Shoulder: Measures from the center of the across back, over the shoulder, under the arm, and return to start.
Neck Back, to Armfold Front, to Highbust Back: Measures from the neck back, over the shoulder to the armfold front, under the arm to the highbust back.
Armfold to Armfold, front, curved through Bust Front: Measures in a curve from the armfold left front through the bust front, curved back up to the armfold right front.
Armfold to Bust Front: Measures from the armfold front to the bust front, the shortest distance between the two, as straight as possible.
Highbust Back, over Shoulder, to Highbust level: Measures from the highbust back, over the shoulder, then aim at the bustpoint, stopping measurement at the highbust level.
Armscye: Arc: Measures from the armscye at across chest over the shoulder tip to the armscye at across back.
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 2576 of file vtranslatemeasurements.cpp.
References acrossBackCenterToArmfoldFrontToAcrossBackCenter_M, armfoldToArmfoldBust_M, armfoldToBustFront_M, armscyeArc_M, highbustBackOverShoulderToArmfoldFront_M, highbustBackOverShoulderToWaistFront_M, highbustBOverShoulderToHighbustF_M, InitMeasurement(), neckBackToArmfoldFront_M, neckBackToArmfoldFrontToHighbustBack_M, neckBackToArmfoldFrontToNeckBack_M, neckBackToArmfoldFrontToWaistSide_M, neckBackToBustFront_M, and translate.
Referenced by InitMeasurements().
InitGroupQ()
void VTranslateMeasurements::InitGroupQ () private
Initialize group Q measurements.
This function sets up the translations for various measurements related to dart widths in patternmaking, ensuring that each measurement has a corresponding translated name and description. These translations are crucial for accurate data representation in different languages.
The measurements initialized in this function include:
Dart Width: Shoulder: Information pulled from pattern charts in some patternmaking systems, such as Winifred P. Aldrich's "Metric Pattern Cutting".
Dart Width: Bust: Information pulled from pattern charts in some patternmaking systems, such as Winifred P. Aldrich's "Metric Pattern Cutting".
Dart Width: Waist: Information pulled from pattern charts in some patternmaking systems, such as Winifred P. Aldrich's "Metric Pattern Cutting".
Note: Variables and functions cannot be used directly in this function because the lupdate tool does not recognize strings contained within variables, which prevents those strings from being marked for translation.
Definition at line 2692 of file vtranslatemeasurements.cpp.
References dartWidthBust_M, dartWidthShoulder_M, dartWidthWaist_M, InitMeasurement(), and translate.
Referenced by InitMeasurements().
InitMeasurement()
void VTranslateMeasurements::InitMeasurement (const QString & name, const qmu::QmuTranslation & m, const qmu::QmuTranslation & g, const qmu::QmuTranslation & d, const QString & number, const QString & formula = QString()) private
Initializes a single measurement with its related data.
This method sets up a measurement by inserting its translations, number, and formula into the corresponding maps.
Parameters
name The name of the measurement.
m The translation for the measurement.
g The GUI text translation for the measurement.
d The description translation for the measurement.
number The number associated with the measurement.
formula The formula associated with the measurement (optional).
The method inserts the provided translation for the measurement into the m_measurements map.
It inserts the provided GUI text translation into the m_guiTexts map.
It inserts the provided description translation into the m_descriptions map.
It inserts the provided number into the m_numbers map.
It inserts the provided formula into the m_formulas map.
Definition at line 333 of file vtranslatemeasurements.cpp.
References m_descriptions, m_formulas, m_guiTexts, m_measurements, and m_numbers.
Referenced by InitGroupA(), InitGroupB(), InitGroupC(), InitGroupD(), InitGroupE(), InitGroupF(), InitGroupG(), InitGroupH(), InitGroupI(), InitGroupJ(), InitGroupK(), InitGroupL(), InitGroupM(), InitGroupN(), InitGroupO(), InitGroupP(), and InitGroupQ().
InitMeasurements()
void VTranslateMeasurements::InitMeasurements () private
Initializes all measurement groups.
This method initializes all predefined groups of measurements.
The method calls initialization functions for each predefined measurement group:
InitGroupA(): Direct Height
InitGroupB(): Direct Width
InitGroupC(): Indentation
InitGroupD(): Circumference and Arc
InitGroupE(): Vertical
InitGroupF(): Horizontal
InitGroupG(): Bust
InitGroupH(): Balance
InitGroupI(): Arm
InitGroupJ(): Leg
InitGroupK(): Crotch and Rise
InitGroupL(): Hand
InitGroupM(): Foot
InitGroupN(): Head
InitGroupO(): Men & Tailoring
InitGroupP(): Historical & Specialty
InitGroupQ(): Patternmaking measurements
Definition at line 293 of file vtranslatemeasurements.cpp.
References InitGroupA(), InitGroupB(), InitGroupC(), InitGroupD(), InitGroupE(), InitGroupF(), InitGroupG(), InitGroupH(), InitGroupI(), InitGroupJ(), InitGroupK(), InitGroupL(), InitGroupM(), InitGroupN(), InitGroupO(), InitGroupP(), and InitGroupQ().
Referenced by Retranslate(), and VTranslateMeasurements().
MeasurementsFromUser()
bool VTranslateMeasurements::MeasurementsFromUser (QString & newFormula, int position, const QString & token, int & bias) const
Translates a user-provided measurement token into an internal representation.
This method translates a user-provided measurement token into an internal representation and updates the provided formula.
Parameters
newFormula The formula to update with the internal representation.
position The position in the formula where the token is located.
token The user-provided measurement token to translate.
bias The bias value to update based on the length difference between the token and its internal representation.
Returns
bool True if the token was successfully translated, false otherwise.
The method iterates over the m_measurements map to find a matching translation for the provided token.
If a match is found, it replaces the token in newFormula with its internal representation.
It updates the bias value to reflect the length difference between the token and its internal representation.
If a match is found and the replacement is made, the method returns true.
If no match is found, the method returns false.
Definition at line 115 of file vtranslatemeasurements.cpp.
References m_measurements.
Referenced by VTranslateVars::FormulaFromUser(), and VTranslateVars::VarFromUser().
MFormula()
QString VTranslateMeasurements::MFormula (const QString & measurement) const
Retrieves the formula associated with a given measurement.
This method returns the formula associated with the specified measurement.
Parameters
measurement The measurement for which to retrieve the formula.
Returns
QString The formula associated with the measurement.
The method retrieves the formula from the m_formulas map using the specified measurement.
If the measurement is not found in the map, it returns an empty string.
Definition at line 194 of file vtranslatemeasurements.cpp.
References m_formulas.
MNumber()
QString VTranslateMeasurements::MNumber (const QString & measurement) const
Retrieves the number associated with a given measurement.
This method returns the number associated with the specified measurement.
Parameters
measurement The measurement for which to retrieve the number.
Returns
QString The number associated with the measurement, or an empty string if the measurement is not found.
The method checks if the m_numbers map contains the specified measurement.
If the measurement is found, it returns the associated number.
If the measurement is not found, it returns an empty string.
Definition at line 170 of file vtranslatemeasurements.cpp.
References m_numbers.
Referenced by ListNumbers(), MeasurementDatabaseDialog::showDescription(), and TMainWindow::ShowMDiagram().
MToUser()
QString VTranslateMeasurements::MToUser (const QString & measurement) const
Translates an internal measurement representation to a user-friendly string.
This method converts an internal measurement representation to its corresponding user-friendly string.
Parameters
measurement The internal measurement representation to translate.
Returns
QString The user-friendly string corresponding to the measurement.
The method checks if the m_measurements map contains the specified measurement.
If the measurement is found, it returns the user-friendly translation.
If the measurement is not found, it returns the original measurement string.
Definition at line 145 of file vtranslatemeasurements.cpp.
References m_measurements.
Retranslate()
void VTranslateMeasurements::Retranslate () virtual
Retranslates all measurement-related data.
This method clears all existing measurement-related data and reinitializes it.
The method clears the m_measurements, m_guiTexts, m_descriptions, m_numbers, and m_formulas maps.
It calls the InitMeasurements method to reinitialize the measurement data.
Reimplemented in VTranslateVars.
Definition at line 258 of file vtranslatemeasurements.cpp.
References InitMeasurements(), m_descriptions, m_formulas, m_guiTexts, m_measurements, and m_numbers.
Referenced by VTranslateVars::Retranslate().
Member Data Documentation
m_descriptions
QMap<QString, qmu::QmuTranslation> VTranslateMeasurements::m_descriptions private
Definition at line 139 of file vtranslatemeasurements.h.
Referenced by Description(), InitMeasurement(), and Retranslate().
m_formulas
QMap<QString, QString> VTranslateMeasurements::m_formulas private
Definition at line 141 of file vtranslatemeasurements.h.
Referenced by InitMeasurement(), MFormula(), and Retranslate().
m_guiTexts
QMap<QString, qmu::QmuTranslation> VTranslateMeasurements::m_guiTexts private
Definition at line 138 of file vtranslatemeasurements.h.
Referenced by guiText(), InitMeasurement(), and Retranslate().
m_measurements
QMap<QString, qmu::QmuTranslation> VTranslateMeasurements::m_measurements protected
Definition at line 134 of file vtranslatemeasurements.h.
Referenced by VTranslateVars::FormulaToUser(), InitMeasurement(), MeasurementsFromUser(), MToUser(), Retranslate(), and VTranslateVars::VarToUser().
m_numbers
QMap<QString, QString> VTranslateMeasurements::m_numbers private
Definition at line 140 of file vtranslatemeasurements.h.
Referenced by InitMeasurement(), MNumber(), and Retranslate().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/vtranslatemeasurements.h
src/libs/vpatterndb/vtranslatemeasurements.cpp