Seamly2D: ImageItem Class Reference
ImageItem Class Reference
The ImageItem class pointer label.
#include <image_item.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::BackgroundImage) }
Signals
void imageNeedsSave ()
void showContextMenu (QGraphicsSceneContextMenuEvent *event)
void deleteImage (quint32 id)
void imageSelected (quint32 id)
void setStatusMessage (QString message)
Public Member Functions
ImageItem (QObject *parent, VAbstractPattern *doc, DraftImage image)
ImageItem default constructor.
virtual ~ImageItem ()=default
virtual int type () const override
virtual QRectF boundingRect () const override
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void moveToBottom ()
void moveToTop ()
void moveUp ()
void moveDown ()
DraftImage getImage ()
void setImage (DraftImage image)
void setOrigin (qreal xOrigin, qreal yOrigin)
void updateImage ()
void updateImageAndHandles (DraftImage image)
void setLock (bool checked)
void enableSelection (bool enable)
void enableHovering (bool enable)
void deleteImageItem ()
Static Public Attributes
static constexpr qint32 maxImageZvalue = -100
Protected Member Functions
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
hoverEnterEvent handle hover enter events.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event) override
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
hoverLeaveEvent handle hover leave events.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) override
contextMenuEvent handle context menu events.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void keyReleaseEvent (QKeyEvent *event) override
Private Member Functions
void initializeItem ()
void updateFromHandles (QRectF rect)
void setPixmap (const QPixmap &pixmap)
void showImageStatusMessage ()
Private Attributes
VAbstractPattern * m_doc
QPointF m_offset
QPointF m_origin
QRectF m_boundingRect
QRectF m_handleRect
QRectF m_actualRect
ResizeHandlesItem * m_resizeHandles
Position m_resizePosition
QLineF m_rotateLine
QPolygonF m_angleHandle
qreal m_angle
bool m_mousePressed
bool m_isHovered
SelectionType m_selectionType
bool m_transformationMode
DraftImage m_image
QPixmap m_pixmap
qreal m_pixmapWidth
qreal m_pixmapHeight
bool m_selectable
qreal m_minDimension
qreal m_maxDimension
bool m_selectNewOrigin
bool m_imageWasMoved
Detailed Description
The ImageItem class pointer label.
Definition at line 50 of file image_item.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 60 of file image_item.h.
Constructor & Destructor Documentation
ImageItem()
ImageItem::ImageItem (QObject * parent, VAbstractPattern * doc, DraftImage image) explicit
ImageItem default constructor.
Parameters
parent parent object.
Definition at line 59 of file image_item.cpp.
References DraftImage::aspectLocked, ByMouseRelease, DraftImage::filename, VAbstractPattern::getBackgroundImageMap(), HANDLE_SIZE, DraftImage::height, imageNeedsSave(), ResizeHandlesItem::imageNeedsSave(), initializeItem(), DraftImage::locked, m_boundingRect, m_doc, m_handleRect, m_image, m_maxDimension, m_minDimension, m_origin, m_pixmap, m_pixmapHeight, m_pixmapWidth, m_resizeHandles, maxImageZvalue, moveToTop(), DraftImage::order, ResizeHandlesItem::parentIsLocked(), ResizeHandlesItem, DraftImage::rotation, ResizeHandlesItem::setLockAspectRatio(), ResizeHandlesItem::setParentRotation(), setStatusMessage(), ResizeHandlesItem::setStatusMessage(), ResizeHandlesItem::sizeChangedFromHandles(), updateFromHandles(), updateImage(), DraftImage::width, DraftImage::xOrigin, DraftImage::xPos, DraftImage::yOrigin, and DraftImage::yPos.
~ImageItem()
virtual ImageItem::~ImageItem () virtual default
Member Function Documentation
boundingRect()
QRectF ImageItem::boundingRect () const override virtual
Definition at line 126 of file image_item.cpp.
References m_boundingRect.
contextMenuEvent()
void ImageItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) override protected virtual
contextMenuEvent handle context menu events.
Parameters
event context menu event.
Definition at line 336 of file image_item.cpp.
References ImageDialog::applyClicked(), cursorImageOrigin, deleteImage(), ImageDialog::getImage(), DraftImage::id, imageNeedsSave(), DraftImage::locked, m_image, m_maxDimension, m_minDimension, m_pixmapHeight, m_pixmapWidth, m_resizeHandles, m_selectable, m_selectNewOrigin, moveDown(), moveToBottom(), moveToTop(), moveUp(), qApp, showContextMenu(), and updateImageAndHandles().
deleteImage
void ImageItem::deleteImage (quint32 id) signal
Referenced by ImageTool::addImage(), contextMenuEvent(), and keyReleaseEvent().
deleteImageItem()
void ImageItem::deleteImageItem ()
Definition at line 635 of file image_item.cpp.
References moveToBottom().
Referenced by ImageTool::handleDeleteImage().
enableHovering()
void ImageItem::enableHovering (bool enable)
Definition at line 258 of file image_item.cpp.
enableSelection()
void ImageItem::enableSelection (bool enable)
Definition at line 250 of file image_item.cpp.
References m_selectable.
getImage()
DraftImage ImageItem::getImage ()
Definition at line 148 of file image_item.cpp.
References m_image.
Referenced by ImageTool::saveChanges(), and ImageTool::saveOptions().
hoverEnterEvent()
void ImageItem::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected virtual
hoverEnterEvent handle hover enter events.
Parameters
event hover enter event.
Definition at line 268 of file image_item.cpp.
References cursorArrowOpenHand, cursorImageOrigin, DraftImage::locked, m_image, m_isHovered, m_resizeHandles, m_selectNewOrigin, qApp, SetItemOverrideCursor(), and showImageStatusMessage().
hoverLeaveEvent()
void ImageItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
hoverLeaveEvent handle hover leave events.
Parameters
event hover leave event.
Definition at line 303 of file image_item.cpp.
References DraftImage::locked, m_image, m_isHovered, m_resizeHandles, and setStatusMessage().
hoverMoveEvent()
void ImageItem::hoverMoveEvent (QGraphicsSceneHoverEvent * event) override protected virtual
Definition at line 321 of file image_item.cpp.
References DraftImage::locked, m_image, and showImageStatusMessage().
imageNeedsSave
void ImageItem::imageNeedsSave () signal
Referenced by ImageTool::addImage(), contextMenuEvent(), ImageItem(), mouseReleaseEvent(), moveDown(), moveToBottom(), moveToTop(), and moveUp().
imageSelected
void ImageItem::imageSelected (quint32 id) signal
Referenced by mousePressEvent(), and mouseReleaseEvent().
initializeItem()
void ImageItem::initializeItem () private
Definition at line 588 of file image_item.cpp.
Referenced by ImageItem().
keyReleaseEvent()
void ImageItem::keyReleaseEvent (QKeyEvent * event) override protected virtual
Definition at line 565 of file image_item.cpp.
References cursorArrowOpenHand, deleteImage(), DraftImage::id, DraftImage::locked, m_image, m_resizeHandles, m_selectNewOrigin, and SetItemOverrideCursor().
mouseMoveEvent()
void ImageItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected virtual
Definition at line 513 of file image_item.cpp.
References m_image, m_imageWasMoved, m_offset, showImageStatusMessage(), updateImage(), DraftImage::xPos, and DraftImage::yPos.
mousePressEvent()
void ImageItem::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected virtual
Definition at line 462 of file image_item.cpp.
References ByMouseRelease, cursorArrowCloseHand, DraftImage::id, imageSelected(), m_boundingRect, m_image, m_mousePressed, m_offset, m_origin, m_selectable, m_selectionType, m_selectNewOrigin, SetItemOverrideCursor(), DraftImage::xOrigin, DraftImage::xPos, DraftImage::yOrigin, and DraftImage::yPos.
mouseReleaseEvent()
void ImageItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected virtual
Definition at line 531 of file image_item.cpp.
References ByMouseRelease, cursorArrowOpenHand, DraftImage::id, imageNeedsSave(), imageSelected(), m_image, m_imageWasMoved, m_mousePressed, m_resizeHandles, m_selectionType, m_selectNewOrigin, and SetItemOverrideCursor().
moveDown()
void ImageItem::moveDown ()
Definition at line 696 of file image_item.cpp.
References VAbstractPattern::getBackgroundImageMap(), imageNeedsSave(), m_doc, m_image, maxImageZvalue, DraftImage::order, and updateImage().
Referenced by contextMenuEvent().
moveToBottom()
void ImageItem::moveToBottom ()
Definition at line 642 of file image_item.cpp.
References VAbstractPattern::getBackgroundImageMap(), imageNeedsSave(), m_doc, m_image, DraftImage::order, and updateImage().
Referenced by contextMenuEvent(), and deleteImageItem().
moveToTop()
void ImageItem::moveToTop ()
Definition at line 660 of file image_item.cpp.
References VAbstractPattern::getBackgroundImageMap(), imageNeedsSave(), m_doc, m_image, maxImageZvalue, DraftImage::order, and updateImage().
Referenced by contextMenuEvent(), and ImageItem().
moveUp()
void ImageItem::moveUp ()
Definition at line 675 of file image_item.cpp.
References VAbstractPattern::getBackgroundImageMap(), imageNeedsSave(), m_doc, m_image, maxImageZvalue, DraftImage::order, and updateImage().
Referenced by contextMenuEvent().
paint()
void ImageItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override virtual
Definition at line 208 of file image_item.cpp.
References DraftImage::height, DraftImage::locked, m_boundingRect, m_image, m_isHovered, m_origin, m_pixmap, m_transformationMode, qApp, and DraftImage::width.
setImage()
void ImageItem::setImage (DraftImage image)
Definition at line 153 of file image_item.cpp.
References m_image.
setLock()
void ImageItem::setLock (bool checked)
Definition at line 190 of file image_item.cpp.
References DraftImage::locked, m_image, and setStatusMessage().
Referenced by updateImage().
setOrigin()
void ImageItem::setOrigin (qreal xOrigin, qreal yOrigin)
Definition at line 159 of file image_item.cpp.
References m_boundingRect, m_image, m_origin, DraftImage::xOrigin, and DraftImage::yOrigin.
setPixmap()
void ImageItem::setPixmap (const QPixmap & pixmap) private
Definition at line 132 of file image_item.cpp.
References HANDLE_SIZE, DraftImage::height, m_boundingRect, m_handleRect, m_image, m_pixmap, m_pixmapHeight, m_pixmapWidth, DraftImage::width, DraftImage::xPos, and DraftImage::yPos.
setStatusMessage
void ImageItem::setStatusMessage (QString message) signal
Referenced by ImageTool::addImage(), hoverLeaveEvent(), ImageItem(), setLock(), and showImageStatusMessage().
showContextMenu
void ImageItem::showContextMenu (QGraphicsSceneContextMenuEvent * event) signal
Referenced by contextMenuEvent().
showImageStatusMessage()
void ImageItem::showImageStatusMessage () private
Definition at line 717 of file image_item.cpp.
References DraftImage::aspectLocked, DraftImage::height, m_image, DraftImage::name, Px, qApp, DraftImage::rotation, setStatusMessage(), DraftImage::units, UnitsToStr(), DraftImage::width, DraftImage::xPos, and DraftImage::yPos.
Referenced by hoverEnterEvent(), hoverMoveEvent(), and mouseMoveEvent().
type()
virtual int ImageItem::type () const inline override virtual
Definition at line 59 of file image_item.h.
References Type.
updateFromHandles()
void ImageItem::updateFromHandles (QRectF rect) private
Definition at line 598 of file image_item.cpp.
References DraftImage::height, m_boundingRect, m_image, m_origin, updateImage(), DraftImage::width, DraftImage::xOrigin, DraftImage::xPos, DraftImage::yOrigin, and DraftImage::yPos.
Referenced by ImageItem().
updateImage()
void ImageItem::updateImage ()
Definition at line 171 of file image_item.cpp.
References DraftImage::height, DraftImage::locked, m_boundingRect, m_image, m_origin, DraftImage::opacity, DraftImage::order, DraftImage::rotation, setLock(), DraftImage::visible, DraftImage::width, DraftImage::xPos, and DraftImage::yPos.
Referenced by ImageItem(), mouseMoveEvent(), moveDown(), moveToBottom(), moveToTop(), moveUp(), updateFromHandles(), and updateImageAndHandles().
updateImageAndHandles()
void ImageItem::updateImageAndHandles (DraftImage image)
Definition at line 623 of file image_item.cpp.
References DraftImage::aspectLocked, DraftImage::locked, m_boundingRect, m_image, m_origin, m_resizeHandles, ResizeHandlesItem::parentIsLocked(), DraftImage::rotation, ResizeHandlesItem::setLockAspectRatio(), ResizeHandlesItem::setParentRect(), ResizeHandlesItem::setParentRotation(), updateImage(), DraftImage::xOrigin, and DraftImage::yOrigin.
Referenced by contextMenuEvent(), and VPattern::parseImageElement().
Member Data Documentation
m_actualRect
QRectF ImageItem::m_actualRect private
Definition at line 111 of file image_item.h.
m_angle
qreal ImageItem::m_angle private
Definition at line 116 of file image_item.h.
m_angleHandle
QPolygonF ImageItem::m_angleHandle private
Definition at line 115 of file image_item.h.
m_boundingRect
QRectF ImageItem::m_boundingRect private
Definition at line 109 of file image_item.h.
Referenced by boundingRect(), ImageItem(), mousePressEvent(), paint(), setOrigin(), setPixmap(), updateFromHandles(), updateImage(), and updateImageAndHandles().
m_doc
VAbstractPattern* ImageItem::m_doc private
Definition at line 106 of file image_item.h.
Referenced by ImageItem(), moveDown(), moveToBottom(), moveToTop(), and moveUp().
m_handleRect
QRectF ImageItem::m_handleRect private
Definition at line 110 of file image_item.h.
Referenced by ImageItem(), and setPixmap().
m_image
DraftImage ImageItem::m_image private
Definition at line 121 of file image_item.h.
Referenced by contextMenuEvent(), getImage(), hoverEnterEvent(), hoverLeaveEvent(), hoverMoveEvent(), ImageItem(), keyReleaseEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveDown(), moveToBottom(), moveToTop(), moveUp(), paint(), setImage(), setLock(), setOrigin(), setPixmap(), showImageStatusMessage(), updateFromHandles(), updateImage(), and updateImageAndHandles().
m_imageWasMoved
bool ImageItem::m_imageWasMoved private
Definition at line 129 of file image_item.h.
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
m_isHovered
bool ImageItem::m_isHovered private
Definition at line 118 of file image_item.h.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and paint().
m_maxDimension
qreal ImageItem::m_maxDimension private
Definition at line 127 of file image_item.h.
Referenced by contextMenuEvent(), and ImageItem().
m_minDimension
qreal ImageItem::m_minDimension private
Definition at line 126 of file image_item.h.
Referenced by contextMenuEvent(), and ImageItem().
m_mousePressed
bool ImageItem::m_mousePressed private
Definition at line 117 of file image_item.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
m_offset
QPointF ImageItem::m_offset private
Definition at line 107 of file image_item.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_origin
QPointF ImageItem::m_origin private
Definition at line 108 of file image_item.h.
Referenced by ImageItem(), mousePressEvent(), paint(), setOrigin(), updateFromHandles(), updateImage(), and updateImageAndHandles().
m_pixmap
QPixmap ImageItem::m_pixmap private
Definition at line 122 of file image_item.h.
Referenced by ImageItem(), paint(), and setPixmap().
m_pixmapHeight
qreal ImageItem::m_pixmapHeight private
Definition at line 124 of file image_item.h.
Referenced by contextMenuEvent(), ImageItem(), and setPixmap().
m_pixmapWidth
qreal ImageItem::m_pixmapWidth private
Definition at line 123 of file image_item.h.
Referenced by contextMenuEvent(), ImageItem(), and setPixmap().
m_resizeHandles
ResizeHandlesItem* ImageItem::m_resizeHandles private
Definition at line 112 of file image_item.h.
Referenced by contextMenuEvent(), hoverEnterEvent(), hoverLeaveEvent(), ImageItem(), keyReleaseEvent(), mouseReleaseEvent(), and updateImageAndHandles().
m_resizePosition
Position ImageItem::m_resizePosition private
Definition at line 113 of file image_item.h.
m_rotateLine
QLineF ImageItem::m_rotateLine private
Definition at line 114 of file image_item.h.
m_selectable
bool ImageItem::m_selectable private
Definition at line 125 of file image_item.h.
Referenced by contextMenuEvent(), enableSelection(), and mousePressEvent().
m_selectionType
SelectionType ImageItem::m_selectionType private
Definition at line 119 of file image_item.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
m_selectNewOrigin
bool ImageItem::m_selectNewOrigin private
Definition at line 128 of file image_item.h.
Referenced by contextMenuEvent(), hoverEnterEvent(), keyReleaseEvent(), mousePressEvent(), and mouseReleaseEvent().
m_transformationMode
bool ImageItem::m_transformationMode private
Definition at line 120 of file image_item.h.
Referenced by paint().
maxImageZvalue
constexpr qint32 ImageItem::maxImageZvalue = -100 static constexpr
Definition at line 67 of file image_item.h.
Referenced by ImageItem(), moveDown(), moveToTop(), and moveUp().
The documentation for this class was generated from the following files:
src/libs/tools/images/image_item.h
src/libs/tools/images/image_item.cpp