Seamly2D: VTranslateVars Class Reference
VTranslateVars Class Reference
#include <vtranslatevars.h>
Public Member Functions
VTranslateVars ()
virtual ~VTranslateVars () Q_DECL_OVERRIDE
bool VariablesFromUser (QString &newFormula, int position, const QString &token, int &bias) const
VariablesFromUser translate variable to internal look.
bool PostfixOperatorsFromUser (QString &newFormula, int position, const QString &token, int &bias) const
PostfixOperatorsFromUser translate postfix operator to internal look.
bool FunctionsFromUser (QString &newFormula, int position, const QString &token, int &bias) const
FunctionsFromUser translate function name to internal look.
bool VariablesToUser (QString &newFormula, int position, const QString &token, int &bias) const
VariablesToUser translate variable name to user.
QString InternalVarToUser (const QString &var) const
QString PlaceholderToUser (const QString &var) const
QString PlaceholderToUserText (QString text) const
QString PlaceholderFromUserText (QString text) const
QString VarToUser (const QString &var) const
QString VarFromUser (const QString &var) const
QString PMSystemName (const QString &code) const
QString PMSystemAuthor (const QString &code) const
QString PMSystemBook (const QString &code) const
QString PostfixOperator (const QString &name) const
QString FormulaFromUser (const QString &formula, bool osSeparator) const
FormulaFromUser replace all known tokens in formula to internal look. Also change decimal separator in numbers.
QString FormulaToUser (const QString &formula, bool osSeparator) const
FormulaToUser replace all known tokens in formula to user look. Also change decimal separator in numbers.
virtual void Retranslate () Q_DECL_OVERRIDE
QMap< QString, qmu::QmuTranslation > getFunctions () const
Public Member Functions inherited from VTranslateMeasurements
VTranslateMeasurements ()
virtual ~VTranslateMeasurements ()
bool MeasurementsFromUser (QString &newFormula, int position, const QString &token, int &bias) const
MeasurementsFromUser translate measurement to internal look.
QString MToUser (const QString &measurement) const
QString MNumber (const QString &measurement) const
QString MFormula (const QString &measurement) const
QString guiText (const QString &measurement) const
QString Description (const QString &measurement) const
Static Public Member Functions
static QString TryFormulaFromUser (const QString &formula, bool osSeparator)
static void BiasTokens (int position, int bias, QMap< int, QString > &tokens)
BiasTokens change position for each token that have position more then "position".
Private Member Functions
void InitPatternMakingSystems ()
void InitVariables ()
void InitFunctions ()
void InitPostfixOperators ()
void InitPlaceholder ()
void InitSystem (const QString &code, const qmu::QmuTranslation &name, const qmu::QmuTranslation &author, const qmu::QmuTranslation &book)
void CorrectionsPositions (int position, int bias, QMap< int, QString > &tokens, QMap< int, QString > &numbers) const
CorrectionsPositions correct position tokens in expression after token translation.
Private Attributes
QMap< QString, qmu::QmuTranslation > PMSystemNames
QMap< QString, qmu::QmuTranslation > PMSystemAuthors
QMap< QString, qmu::QmuTranslation > PMSystemBooks
QMap< QString, qmu::QmuTranslation > variables
QMap< QString, qmu::QmuTranslation > functions
QMap< QString, qmu::QmuTranslation > postfixOperators
QMap< QString, qmu::QmuTranslation > placeholders
QMap< QString, qmu::QmuTranslation > stDescriptions
Additional Inherited Members
Protected Attributes inherited from VTranslateMeasurements
QMap< QString, qmu::QmuTranslation > m_measurements
Detailed Description
Definition at line 60 of file vtranslatevars.h.
Constructor & Destructor Documentation
VTranslateVars()
VTranslateVars::VTranslateVars () explicit
Definition at line 73 of file vtranslatevars.cpp.
References InitFunctions(), InitPatternMakingSystems(), InitPlaceholder(), InitPostfixOperators(), and InitVariables().
~VTranslateVars()
VTranslateVars::~VTranslateVars () virtual
Definition at line 92 of file vtranslatevars.cpp.
Member Function Documentation
BiasTokens()
void VTranslateVars::BiasTokens (int position, int bias, QMap< int, QString > & tokens) static
BiasTokens change position for each token that have position more then "position".
Parameters
position token position
bias difference between original token length and translated
tokens all tokens
Definition at line 554 of file vtranslatevars.cpp.
Referenced by CorrectionsPositions(), and VPattern::replaceNameInFormula().
CorrectionsPositions()
void VTranslateVars::CorrectionsPositions (int position, int bias, QMap< int, QString > & tokens, QMap< int, QString > & numbers) const private
CorrectionsPositions correct position tokens in expression after token translation.
Because translated string can have different length compare to original need make correction after each translation. If bias = 0 correction will not happens.
Parameters
position position currecnt token in expression
bias difference between original token length and translated
tokens all tokens
numbers all numbers
Definition at line 535 of file vtranslatevars.cpp.
References BiasTokens().
Referenced by FormulaFromUser(), and FormulaToUser().
FormulaFromUser()
QString VTranslateVars::FormulaFromUser (const QString & formula, bool osSeparator) const
FormulaFromUser replace all known tokens in formula to internal look. Also change decimal separator in numbers.
Parameters
formula expression that need translate
Exceptions
qmu::QmuParserError in case of a wrong expression
Returns
translated expression
Definition at line 843 of file vtranslatevars.cpp.
References CorrectionsPositions(), FunctionsFromUser(), VTranslateMeasurements::MeasurementsFromUser(), PostfixOperatorsFromUser(), and VariablesFromUser().
Referenced by TST_VTranslateVars::TestFormulaFromUser().
FormulaToUser()
QString VTranslateVars::FormulaToUser (const QString & formula, bool osSeparator) const
FormulaToUser replace all known tokens in formula to user look. Also change decimal separator in numbers.
Parameters
formula expression that need translate
Returns
translated expression
Definition at line 964 of file vtranslatevars.cpp.
References CorrectionsPositions(), functions, qmu::QmuParserError::GetExpr(), qmu::QmuParserError::GetMsg(), VTranslateMeasurements::m_measurements, postfixOperators, and VariablesToUser().
Referenced by VToolArc::SetVisualization(), VToolArcWithLength::SetVisualization(), VToolEllipticalArc::SetVisualization(), and TST_VTranslateVars::TestFormulaToUser().
FunctionsFromUser()
bool VTranslateVars::FunctionsFromUser (QString & newFormula, int position, const QString & token, int & bias) const
FunctionsFromUser translate function name to internal look.
Parameters
newFormula [in|out] expression to translate
position token position
token token to translate
bias hold change of length between translated and origin token string
Returns
true if was found function with same name.
Definition at line 648 of file vtranslatevars.cpp.
References functions.
Referenced by FormulaFromUser(), and VarFromUser().
getFunctions()
QMap< QString, qmu::QmuTranslation > VTranslateVars::getFunctions () const
Definition at line 1105 of file vtranslatevars.cpp.
References functions.
InitFunctions()
void VTranslateVars::InitFunctions () private
Definition at line 434 of file vtranslatevars.cpp.
References abs_F, acos_F, acosD_F, acosh_F, asin_F, asinD_F, asinh_F, atan_F, atanD_F, atanh_F, avg_F, cos_F, cosD_F, cosh_F, degTorad_F, exp_F, fmod_F, functions, ln_F, log10_F, log2_F, log_F, max_F, min_F, radTodeg_F, rint_F, sign_F, sin_F, sinD_F, sinh_F, sqrt_F, sum_F, tan_F, tanD_F, tanh_F, and translate.
Referenced by Retranslate(), and VTranslateVars().
InitPatternMakingSystems()
void VTranslateVars::InitPatternMakingSystems () private
Definition at line 98 of file vtranslatevars.cpp.
References InitSystem(), p0_S, p10_S, p11_S, p12_S, p13_S, p14_S, p15_S, p16_S, p17_S, p18_S, p19_S, p1_S, p20_S, p21_S, p22_S, p23_S, p24_S, p25_S, p26_S, p27_S, p28_S, p29_S, p2_S, p30_S, p31_S, p32_S, p33_S, p34_S, p35_S, p36_S, p37_S, p38_S, p39_S, p3_S, p40_S, p41_S, p42_S, p43_S, p44_S, p45_S, p46_S, p47_S, p48_S, p49_S, p4_S, p50_S, p51_S, p52_S, p53_S, p54_S, p5_S, p6_S, p7_S, p8_S, p998_S, p9_S, and translate.
Referenced by Retranslate(), and VTranslateVars().
InitPlaceholder()
void VTranslateVars::InitPlaceholder () private
Definition at line 482 of file vtranslatevars.cpp.
References pl_author, pl_customer, pl_date, pl_height, pl_mExt, pl_mFabric, pl_mFileName, pl_mInterfacing, pl_mInterlining, pl_mLining, pl_pAnnotation, pl_patternName, pl_patternNumber, pl_pExt, pl_pFileName, pl_pFoldPosition, pl_pLetter, pl_pName, pl_pOrientation, pl_pQuantity, pl_pRotation, pl_pTilt, pl_size, pl_time, pl_wCut, pl_wOnFold, placeholders, and translate.
Referenced by Retranslate(), and VTranslateVars().
InitPostfixOperators()
void VTranslateVars::InitPostfixOperators () private
Definition at line 474 of file vtranslatevars.cpp.
References cm_Oprt, in_Oprt, mm_Oprt, postfixOperators, and translate.
Referenced by Retranslate(), and VTranslateVars().
InitSystem()
void VTranslateVars::InitSystem (const QString & code, const qmu::QmuTranslation & name, const qmu::QmuTranslation & author, const qmu::QmuTranslation & book) private
Definition at line 515 of file vtranslatevars.cpp.
References PMSystemAuthors, PMSystemBooks, and PMSystemNames.
Referenced by InitPatternMakingSystems().
InitVariables()
void VTranslateVars::InitVariables () private
Definition at line 398 of file vtranslatevars.cpp.
References angle1Arc_, angle1ElArc_, angle1Spl_, angle1SplPath, angle2Arc_, angle2ElArc_, angle2Spl_, angle2SplPath, angleLine_, arc_, c1LengthSpl_, c1LengthSplPath, c2LengthSpl_, c2LengthSplPath, currentLength, currentSeamAllowance, elarc_, line_, measurement_, radius1ElArc_, radius2ElArc_, radiusArc_, seg_, spl_, splPath, translate, variable_, and variables.
Referenced by Retranslate(), and VTranslateVars().
InternalVarToUser()
QString VTranslateVars::InternalVarToUser (const QString & var) const
Definition at line 699 of file vtranslatevars.cpp.
References VariablesToUser().
Referenced by TST_BuitInRegExp::TestCheckInternalVaribleRegExp(), TST_BuitInRegExp::TestCheckUnderlineExists(), and VarToUser().
PlaceholderFromUserText()
QString VTranslateVars::PlaceholderFromUserText (QString text) const
Definition at line 744 of file vtranslatevars.cpp.
References placeholders.
PlaceholderToUser()
QString VTranslateVars::PlaceholderToUser (const QString & var) const
Definition at line 714 of file vtranslatevars.cpp.
References placeholders.
Referenced by TST_BuitInRegExp::TestTemplatePlaceholders().
PlaceholderToUserText()
QString VTranslateVars::PlaceholderToUserText (QString text) const
Definition at line 725 of file vtranslatevars.cpp.
References placeholders.
PMSystemAuthor()
QString VTranslateVars::PMSystemAuthor (const QString & code) const
Definition at line 817 of file vtranslatevars.cpp.
References PMSystemAuthors.
PMSystemBook()
QString VTranslateVars::PMSystemBook (const QString & code) const
Definition at line 823 of file vtranslatevars.cpp.
References PMSystemBooks.
PMSystemName()
QString VTranslateVars::PMSystemName (const QString & code) const
Definition at line 811 of file vtranslatevars.cpp.
References PMSystemNames.
PostfixOperator()
QString VTranslateVars::PostfixOperator (const QString & name) const
Definition at line 830 of file vtranslatevars.cpp.
References postfixOperators.
PostfixOperatorsFromUser()
bool VTranslateVars::PostfixOperatorsFromUser (QString & newFormula, int position, const QString & token, int & bias) const
PostfixOperatorsFromUser translate postfix operator to internal look.
Parameters
newFormula [in|out] expression to translate
position token position
token token to translate
bias hold change of length between translated and origin token string
Returns
true if was found postfix operator with same name.
Definition at line 623 of file vtranslatevars.cpp.
References postfixOperators.
Referenced by FormulaFromUser(), and VarFromUser().
Retranslate()
void VTranslateVars::Retranslate () virtual
Reimplemented from VTranslateMeasurements.
Definition at line 1085 of file vtranslatevars.cpp.
References functions, InitFunctions(), InitPatternMakingSystems(), InitPlaceholder(), InitPostfixOperators(), InitVariables(), PMSystemAuthors, PMSystemBooks, PMSystemNames, postfixOperators, VTranslateMeasurements::Retranslate(), stDescriptions, and variables.
Referenced by TST_AbstractRegExp::InitTrMs(), and MApplication::InitTrVars().
TryFormulaFromUser()
QString VTranslateVars::TryFormulaFromUser (const QString & formula, bool osSeparator) static
Definition at line 944 of file vtranslatevars.cpp.
References qApp.
VarFromUser()
QString VTranslateVars::VarFromUser (const QString & var) const
Definition at line 784 of file vtranslatevars.cpp.
References FunctionsFromUser(), VTranslateMeasurements::MeasurementsFromUser(), PostfixOperatorsFromUser(), and VariablesFromUser().
VariablesFromUser()
bool VTranslateVars::VariablesFromUser (QString & newFormula, int position, const QString & token, int & bias) const
VariablesFromUser translate variable to internal look.
Parameters
newFormula [in|out] expression to translate
position token position
token token to translate
bias hold change of length between translated and origin token string
Returns
true if was found variable with same name.
Definition at line 584 of file vtranslatevars.cpp.
References currentLength, currentSeamAllowance, qmu::QmuTranslation::translate(), and variables.
Referenced by FormulaFromUser(), and VarFromUser().
VariablesToUser()
bool VTranslateVars::VariablesToUser (QString & newFormula, int position, const QString & token, int & bias) const
VariablesToUser translate variable name to user.
Parameters
newFormula [in|out] expression to translate
position token position
token token to translate
bias hold change of length between translated and origin token string
Returns
true if was found variable with same name.
Definition at line 673 of file vtranslatevars.cpp.
References currentLength, currentSeamAllowance, and variables.
Referenced by FormulaToUser(), and InternalVarToUser().
VarToUser()
QString VTranslateVars::VarToUser (const QString & var) const
Definition at line 763 of file vtranslatevars.cpp.
References functions, InternalVarToUser(), VTranslateMeasurements::m_measurements, and postfixOperators.
Referenced by TST_AbstractRegExp::CallTestCheckIsNamesUnique(), TST_AbstractRegExp::CallTestCheckNoEndLine(), TST_AbstractRegExp::CallTestCheckNoOriginalNamesInTranslation(), TST_AbstractRegExp::CallTestCheckRegExpNames(), and TST_BuitInRegExp::TestCheckInternalVaribleRegExp().
Member Data Documentation
functions
QMap<QString, qmu::QmuTranslation> VTranslateVars::functions private
Definition at line 102 of file vtranslatevars.h.
Referenced by FormulaToUser(), FunctionsFromUser(), getFunctions(), InitFunctions(), Retranslate(), and VarToUser().
placeholders
QMap<QString, qmu::QmuTranslation> VTranslateVars::placeholders private
Definition at line 104 of file vtranslatevars.h.
Referenced by InitPlaceholder(), PlaceholderFromUserText(), PlaceholderToUser(), and PlaceholderToUserText().
PMSystemAuthors
QMap<QString, qmu::QmuTranslation> VTranslateVars::PMSystemAuthors private
Definition at line 99 of file vtranslatevars.h.
Referenced by InitSystem(), PMSystemAuthor(), and Retranslate().
PMSystemBooks
QMap<QString, qmu::QmuTranslation> VTranslateVars::PMSystemBooks private
Definition at line 100 of file vtranslatevars.h.
Referenced by InitSystem(), PMSystemBook(), and Retranslate().
PMSystemNames
QMap<QString, qmu::QmuTranslation> VTranslateVars::PMSystemNames private
Definition at line 98 of file vtranslatevars.h.
Referenced by InitSystem(), PMSystemName(), and Retranslate().
postfixOperators
QMap<QString, qmu::QmuTranslation> VTranslateVars::postfixOperators private
Definition at line 103 of file vtranslatevars.h.
Referenced by FormulaToUser(), InitPostfixOperators(), PostfixOperator(), PostfixOperatorsFromUser(), Retranslate(), and VarToUser().
stDescriptions
QMap<QString, qmu::QmuTranslation> VTranslateVars::stDescriptions private
Definition at line 105 of file vtranslatevars.h.
Referenced by Retranslate().
variables
QMap<QString, qmu::QmuTranslation> VTranslateVars::variables private
Definition at line 101 of file vtranslatevars.h.
Referenced by InitVariables(), Retranslate(), VariablesFromUser(), and VariablesToUser().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/vtranslatevars.h
src/libs/vpatterndb/vtranslatevars.cpp