Seamly2D: TST_ReadVal Class Reference
TST_ReadVal Class Reference
#include <tst_readval.h>
Public Member Functions
TST_ReadVal (QObject *parent=nullptr)
Private Slots
void TestReadVal_data ()
void TestReadVal ()
void TestInvalidData_data ()
void TestInvalidData ()
void cleanupTestCase ()
Private Member Functions
void PrepareVal (qreal val, const QLocale &locale)
void PrepareString (const QString &str, const QLocale &locale, qreal val=0, int count=-1)
void TestVal ()
Private Attributes
QLocale m_systemLocale
Detailed Description
Definition at line 60 of file tst_readval.h.
Constructor & Destructor Documentation
TST_ReadVal()
TST_ReadVal::TST_ReadVal (QObject * parent = nullptr) explicit
Definition at line 60 of file tst_readval.cpp.
Member Function Documentation
cleanupTestCase
void TST_ReadVal::cleanupTestCase () private slot
Definition at line 134 of file tst_readval.cpp.
References m_systemLocale.
PrepareString()
void TST_ReadVal::PrepareString (const QString & str, const QLocale & locale, qreal val = 0, int count = -1) private
Definition at line 149 of file tst_readval.cpp.
Referenced by PrepareVal(), and TestInvalidData_data().
PrepareVal()
void TST_ReadVal::PrepareVal (qreal val, const QLocale & locale) private
Definition at line 140 of file tst_readval.cpp.
References PrepareString().
Referenced by TestReadVal_data().
TestInvalidData
void TST_ReadVal::TestInvalidData () private slot
Definition at line 128 of file tst_readval.cpp.
References TestVal().
TestInvalidData_data
void TST_ReadVal::TestInvalidData_data () private slot
Definition at line 100 of file tst_readval.cpp.
References PrepareString().
TestReadVal
void TST_ReadVal::TestReadVal () private slot
Definition at line 94 of file tst_readval.cpp.
References TestVal().
TestReadVal_data
void TST_ReadVal::TestReadVal_data () private slot
Definition at line 67 of file tst_readval.cpp.
References PrepareVal().
TestVal()
void TST_ReadVal::TestVal () private
Definition at line 156 of file tst_readval.cpp.
References QmuFuzzyComparePossibleNulls(), and ReadVal().
Referenced by TestInvalidData(), and TestReadVal().
Member Data Documentation
m_systemLocale
QLocale TST_ReadVal::m_systemLocale private
Definition at line 73 of file tst_readval.h.
Referenced by cleanupTestCase().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_readval.h
src/test/Seamly2DTest/tst_readval.cpp