Seamly2D: FvUpdater Class Reference
FvUpdater Class Reference
#include <fvupdater.h>
Public Slots
bool CheckForUpdates (bool silentAsMuchAsItCouldGet=true)
bool CheckForUpdatesSilent ()
bool CheckForUpdatesNotSilent ()
Signals
void setProgress (int)
Public Member Functions
void SetFeedURL (const QUrl &feedURL)
void SetFeedURL (const QString &feedURL)
QString GetFeedURL () const
bool IsDropOnFinish () const
void SetDropOnFinish (bool value)
Static Public Member Functions
static FvUpdater * sharedUpdater ()
static void drop ()
Private Slots
void httpFeedDownloadFinished ()
void networkError (QNetworkReply::NetworkError)
void getFileSize ()
Private Member Functions
FvUpdater ()
virtual ~FvUpdater ()
void startDownloadFeed (const QUrl &url)
void startDownloadFile (QUrl url, QString name)
void fileDownloadFinished (QFile *downloadedFile, QString name)
void cancelDownloadFeed ()
void showErrorDialog (const QString &message, bool showEvenInSilentMode=false)
void showInformationDialog (const QString &message, bool showEvenInSilentMode=false)
bool showConfirmationDialog (const QString &message, bool showEvenInSilentMode=false)
bool releaseIsNewer (const QString &releaseTag)
void getPLatformSpecificInstaller (QJsonArray assets)
Private Attributes
bool m_silentAsMuchAsItCouldGet
QUrl m_feedURL
QNetworkAccessManager m_qnam
QPointer< QNetworkReply > m_reply
bool m_httpRequestAborted
bool m_dropOnFinish
int m_fileSize {}
QString m_releaseName {}
Static Private Attributes
static QPointer< FvUpdater > m_Instance
Friends
class FvUpdateWindow
Detailed Description
Definition at line 48 of file fvupdater.h.
Constructor & Destructor Documentation
FvUpdater()
FvUpdater::FvUpdater () private
Definition at line 106 of file fvupdater.cpp.
Referenced by sharedUpdater().
Member Function Documentation
cancelDownloadFeed()
void FvUpdater::cancelDownloadFeed () private
Definition at line 329 of file fvupdater.cpp.
References m_httpRequestAborted, and m_reply.
Referenced by CheckForUpdates().
CheckForUpdates
bool FvUpdater::CheckForUpdates (bool silentAsMuchAsItCouldGet = true) slot
Definition at line 136 of file fvupdater.cpp.
References cancelDownloadFeed(), m_feedURL, m_httpRequestAborted, m_silentAsMuchAsItCouldGet, and startDownloadFeed().
Referenced by CheckForUpdatesNotSilent(), and CheckForUpdatesSilent().
CheckForUpdatesNotSilent
bool FvUpdater::CheckForUpdatesNotSilent () slot
Definition at line 196 of file fvupdater.cpp.
References CheckForUpdates(), drop(), and m_dropOnFinish.
CheckForUpdatesSilent
bool FvUpdater::CheckForUpdatesSilent () slot
Definition at line 179 of file fvupdater.cpp.
References CheckForUpdates(), drop(), m_dropOnFinish, and qApp.
drop()
void FvUpdater::drop () static
Definition at line 98 of file fvupdater.cpp.
References m_Instance.
Referenced by CheckForUpdatesNotSilent(), CheckForUpdatesSilent(), and httpFeedDownloadFinished().
fileDownloadFinished()
void FvUpdater::fileDownloadFinished (QFile * downloadedFile, QString name) private
Definition at line 261 of file fvupdater.cpp.
References m_feedURL, m_fileSize, m_httpRequestAborted, m_reply, NoError, setProgress(), showErrorDialog(), showInformationDialog(), and startDownloadFile().
GetFeedURL()
QString FvUpdater::GetFeedURL () const
Definition at line 127 of file fvupdater.cpp.
References m_feedURL.
getFileSize
void FvUpdater::getFileSize () private slot
Definition at line 204 of file fvupdater.cpp.
References m_fileSize, and m_reply.
Referenced by startDownloadFile().
getPLatformSpecificInstaller()
void FvUpdater::getPLatformSpecificInstaller (QJsonArray assets) private
Definition at line 381 of file fvupdater.cpp.
References startDownloadFile().
Referenced by httpFeedDownloadFinished().
httpFeedDownloadFinished
void FvUpdater::httpFeedDownloadFinished () private slot
Definition at line 337 of file fvupdater.cpp.
References drop(), getPLatformSpecificInstaller(), m_dropOnFinish, m_feedURL, m_httpRequestAborted, m_reply, NoError, releaseIsNewer(), showConfirmationDialog(), showErrorDialog(), showInformationDialog(), and startDownloadFeed().
IsDropOnFinish()
bool FvUpdater::IsDropOnFinish () const
Definition at line 130 of file fvupdater.cpp.
References m_dropOnFinish.
networkError
void FvUpdater::networkError (QNetworkReply::NetworkError) private slot
Definition at line 474 of file fvupdater.cpp.
References m_fileSize, m_reply, setProgress(), and showErrorDialog().
Referenced by startDownloadFile().
releaseIsNewer()
bool FvUpdater::releaseIsNewer (const QString & releaseTag) private
Definition at line 464 of file fvupdater.cpp.
References m_releaseName.
Referenced by httpFeedDownloadFinished().
SetDropOnFinish()
void FvUpdater::SetDropOnFinish (bool value)
Definition at line 133 of file fvupdater.cpp.
References m_dropOnFinish.
SetFeedURL() [1/2]
void FvUpdater::SetFeedURL (const QString & feedURL)
Definition at line 122 of file fvupdater.cpp.
References SetFeedURL().
SetFeedURL() [2/2]
void FvUpdater::SetFeedURL (const QUrl & feedURL)
Definition at line 119 of file fvupdater.cpp.
References m_feedURL.
Referenced by SetFeedURL().
setProgress
void FvUpdater::setProgress (int) signal
Referenced by fileDownloadFinished(), and networkError().
sharedUpdater()
FvUpdater * FvUpdater::sharedUpdater () static
Definition at line 86 of file fvupdater.cpp.
References FvUpdater(), and m_Instance.
showConfirmationDialog()
bool FvUpdater::showConfirmationDialog (const QString & message, bool showEvenInSilentMode = false) private
Definition at line 444 of file fvupdater.cpp.
References m_silentAsMuchAsItCouldGet.
Referenced by httpFeedDownloadFinished().
showErrorDialog()
void FvUpdater::showErrorDialog (const QString & message, bool showEvenInSilentMode = false) private
Definition at line 411 of file fvupdater.cpp.
References m_silentAsMuchAsItCouldGet.
Referenced by fileDownloadFinished(), httpFeedDownloadFinished(), networkError(), and startDownloadFile().
showInformationDialog()
void FvUpdater::showInformationDialog (const QString & message, bool showEvenInSilentMode = false) private
Definition at line 428 of file fvupdater.cpp.
References m_silentAsMuchAsItCouldGet.
Referenced by fileDownloadFinished(), and httpFeedDownloadFinished().
startDownloadFeed()
void FvUpdater::startDownloadFeed (const QUrl & url) private
Definition at line 302 of file fvupdater.cpp.
References m_qnam, and m_reply.
Referenced by CheckForUpdates(), and httpFeedDownloadFinished().
startDownloadFile()
void FvUpdater::startDownloadFile (QUrl url, QString name) private
Definition at line 211 of file fvupdater.cpp.
References getFileSize(), m_qnam, m_releaseName, m_reply, networkError(), and showErrorDialog().
Referenced by fileDownloadFinished(), and getPLatformSpecificInstaller().
~FvUpdater()
FvUpdater::~FvUpdater () private virtual
Definition at line 114 of file fvupdater.cpp.
References m_reply.
Friends And Related Function Documentation
FvUpdateWindow
friend class FvUpdateWindow friend
Definition at line 74 of file fvupdater.h.
Member Data Documentation
m_dropOnFinish
bool FvUpdater::m_dropOnFinish private
Definition at line 107 of file fvupdater.h.
Referenced by CheckForUpdatesNotSilent(), CheckForUpdatesSilent(), httpFeedDownloadFinished(), IsDropOnFinish(), and SetDropOnFinish().
m_feedURL
QUrl FvUpdater::m_feedURL private
Definition at line 103 of file fvupdater.h.
Referenced by CheckForUpdates(), fileDownloadFinished(), GetFeedURL(), httpFeedDownloadFinished(), and SetFeedURL().
m_fileSize
int FvUpdater::m_fileSize {} private
Definition at line 108 of file fvupdater.h.
Referenced by fileDownloadFinished(), getFileSize(), and networkError().
m_httpRequestAborted
bool FvUpdater::m_httpRequestAborted private
Definition at line 106 of file fvupdater.h.
Referenced by cancelDownloadFeed(), CheckForUpdates(), fileDownloadFinished(), and httpFeedDownloadFinished().
m_Instance
QPointer< FvUpdater > FvUpdater::m_Instance static private
Definition at line 93 of file fvupdater.h.
Referenced by drop(), and sharedUpdater().
m_qnam
QNetworkAccessManager FvUpdater::m_qnam private
Definition at line 104 of file fvupdater.h.
Referenced by startDownloadFeed(), and startDownloadFile().
m_releaseName
QString FvUpdater::m_releaseName {} private
Definition at line 109 of file fvupdater.h.
Referenced by releaseIsNewer(), and startDownloadFile().
m_reply
QPointer<QNetworkReply> FvUpdater::m_reply private
Definition at line 105 of file fvupdater.h.
Referenced by cancelDownloadFeed(), fileDownloadFinished(), getFileSize(), httpFeedDownloadFinished(), networkError(), startDownloadFeed(), startDownloadFile(), and ~FvUpdater().
m_silentAsMuchAsItCouldGet
bool FvUpdater::m_silentAsMuchAsItCouldGet private
Definition at line 98 of file fvupdater.h.
Referenced by CheckForUpdates(), showConfirmationDialog(), showErrorDialog(), and showInformationDialog().
The documentation for this class was generated from the following files:
src/libs/fervor/fvupdater.h
src/libs/fervor/fvupdater.cpp