Seamly2D: VisToolTriangle Class Reference
VisToolTriangle Class Reference
#include <vistooltriangle.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolTriangle) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolTriangle (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolTriangle ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setObject2Id (const quint32 &value)
void setHypotenuseP1Id (const quint32 &value)
void setHypotenuseP2Id (const quint32 &value)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Attributes
quint32 object2Id
quint32 hypotenuseP1Id
quint32 hypotenuseP2Id
VScaledEllipse * point
VScaledEllipse * axisP1
VScaledEllipse * axisP2
ArrowedLineItem * axis
VScaledEllipse * hypotenuseP1
VScaledEllipse * hypotenuseP2
VScaledLine * foot1
VScaledLine * foot2
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 68 of file vistooltriangle.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 82 of file vistooltriangle.h.
Constructor & Destructor Documentation
VisToolTriangle()
VisToolTriangle::VisToolTriangle (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 72 of file vistooltriangle.cpp.
References axis, axisP1, axisP2, foot1, foot2, hypotenuseP1, hypotenuseP2, Visualization::InitPoint(), Visualization::mainColor, point, and Visualization::supportColor.
~VisToolTriangle()
virtual VisToolTriangle::~VisToolTriangle () virtual default
Member Function Documentation
RefreshGeometry()
void VisToolTriangle::RefreshGeometry () virtual
Implements Visualization.
Definition at line 89 of file vistooltriangle.cpp.
References axis, axisP1, axisP2, Visualization::data, Visualization::drawArrowedLine(), Visualization::DrawLine(), Visualization::DrawPoint(), VToolTriangle::FindPoint(), foot1, foot2, VContainer::GeometricObject(), hypotenuseP1, hypotenuseP1Id, hypotenuseP2, hypotenuseP2Id, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, object2Id, point, Visualization::scenePos, and Visualization::supportColor.
Referenced by DialogTriangle::ChosenObject(), DialogTriangle::SaveData(), and VToolTriangle::SetVisualization().
setHypotenuseP1Id()
void VisToolTriangle::setHypotenuseP1Id (const quint32 & value)
Definition at line 161 of file vistooltriangle.cpp.
References hypotenuseP1Id.
Referenced by DialogTriangle::ChosenObject(), DialogTriangle::SaveData(), DialogTriangle::SetFirstPointId(), and VToolTriangle::SetVisualization().
setHypotenuseP2Id()
void VisToolTriangle::setHypotenuseP2Id (const quint32 & value)
Definition at line 167 of file vistooltriangle.cpp.
References hypotenuseP2Id.
Referenced by DialogTriangle::ChosenObject(), DialogTriangle::SaveData(), DialogTriangle::SetSecondPointId(), and VToolTriangle::SetVisualization().
setObject2Id()
void VisToolTriangle::setObject2Id (const quint32 & value)
Definition at line 155 of file vistooltriangle.cpp.
References object2Id.
Referenced by DialogTriangle::ChosenObject(), DialogTriangle::SaveData(), DialogTriangle::SetAxisP2Id(), and VToolTriangle::SetVisualization().
type()
virtual int VisToolTriangle::type () const inline virtual
Reimplemented from VisLine.
Definition at line 81 of file vistooltriangle.h.
References Type.
Member Data Documentation
axis
ArrowedLineItem* VisToolTriangle::axis private
Definition at line 91 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and VisToolTriangle().
axisP1
VScaledEllipse* VisToolTriangle::axisP1 private
Definition at line 89 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and VisToolTriangle().
axisP2
VScaledEllipse* VisToolTriangle::axisP2 private
Definition at line 90 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and VisToolTriangle().
foot1
VScaledLine* VisToolTriangle::foot1 private
Definition at line 94 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and VisToolTriangle().
foot2
VScaledLine* VisToolTriangle::foot2 private
Definition at line 95 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and VisToolTriangle().
hypotenuseP1
VScaledEllipse* VisToolTriangle::hypotenuseP1 private
Definition at line 92 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and VisToolTriangle().
hypotenuseP1Id
quint32 VisToolTriangle::hypotenuseP1Id private
Definition at line 86 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and setHypotenuseP1Id().
hypotenuseP2
VScaledEllipse* VisToolTriangle::hypotenuseP2 private
Definition at line 93 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and VisToolTriangle().
hypotenuseP2Id
quint32 VisToolTriangle::hypotenuseP2Id private
Definition at line 87 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and setHypotenuseP2Id().
object2Id
quint32 VisToolTriangle::object2Id private
Definition at line 85 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and setObject2Id().
point
VScaledEllipse* VisToolTriangle::point private
Definition at line 88 of file vistooltriangle.h.
Referenced by RefreshGeometry(), and VisToolTriangle().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/vistooltriangle.h
src/libs/vtools/visualization/line/vistooltriangle.cpp