Seamly2D: DOMDeepNodeListPool< TVal, THasher > Class Template Reference
DOMDeepNodeListPool< TVal, THasher > Class Template Reference
#include <DOMDeepNodeListPool.hpp>
Public Member Functions
DOMDeepNodeListPool (const XMLSize_t modulus, const XMLSize_t initSize=128)
DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize=128)
DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, const XMLSize_t initSize=128)
~DOMDeepNodeListPool ()
bool isEmpty () const
bool containsKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
void removeAll ()
void cleanup ()
TVal * getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3)
const TVal * getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
TVal * getById (const XMLSize_t elemId)
const TVal * getById (const XMLSize_t elemId) const
XMLSize_t put (void *key1, XMLCh *key2, XMLCh *key3, TVal *const valueToAdopt)
DOMDeepNodeListPool (const XMLSize_t modulus, const XMLSize_t initSize=128)
DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize=128)
DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, const XMLSize_t initSize=128)
~DOMDeepNodeListPool ()
bool isEmpty () const
bool containsKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
void removeAll ()
void cleanup ()
TVal * getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3)
const TVal * getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
TVal * getById (const XMLSize_t elemId)
const TVal * getById (const XMLSize_t elemId) const
XMLSize_t put (void *key1, XMLCh *key2, XMLCh *key3, TVal *const valueToAdopt)
DOMDeepNodeListPool (const XMLSize_t modulus, const XMLSize_t initSize=128)
DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize=128)
DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const THasher &hasher, const XMLSize_t initSize=128)
~DOMDeepNodeListPool ()
bool isEmpty () const
bool containsKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
void removeAll ()
void cleanup ()
TVal * getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3)
const TVal * getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
TVal * getById (const XMLSize_t elemId)
const TVal * getById (const XMLSize_t elemId) const
XMLSize_t put (void *key1, XMLCh *key2, XMLCh *key3, TVal *const valueToAdopt)
Private Member Functions
DOMDeepNodeListPoolTableBucketElem< TVal > * findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t &hashVal)
const DOMDeepNodeListPoolTableBucketElem< TVal > * findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
DOMDeepNodeListPool (const DOMDeepNodeListPool< TVal, THasher > &)
DOMDeepNodeListPool< TVal, THasher > & operator= (const DOMDeepNodeListPool< TVal, THasher > &)
DOMDeepNodeListPoolTableBucketElem< TVal > * findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t &hashVal)
const DOMDeepNodeListPoolTableBucketElem< TVal > * findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
DOMDeepNodeListPool (const DOMDeepNodeListPool< TVal, THasher > &)
DOMDeepNodeListPool< TVal, THasher > & operator= (const DOMDeepNodeListPool< TVal, THasher > &)
DOMDeepNodeListPoolTableBucketElem< TVal > * findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t &hashVal)
const DOMDeepNodeListPoolTableBucketElem< TVal > * findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
DOMDeepNodeListPool (const DOMDeepNodeListPool< TVal, THasher > &)
DOMDeepNodeListPool< TVal, THasher > & operator= (const DOMDeepNodeListPool< TVal, THasher > &)
Private Attributes
bool fAdoptedElems
DOMDeepNodeListPoolTableBucketElem< TVal > ** fBucketList
XMLSize_t fHashModulus
TVal ** fIdPtrs
XMLSize_t fIdPtrsCount
XMLSize_t fIdCounter
MemoryManager * fMemoryManager
THasher fHasher
Detailed Description
template<class TVal, class THasher = PtrHasher>
class DOMDeepNodeListPool< TVal, THasher >
Definition at line 84 of file DOMDeepNodeListPool.hpp.
Constructor & Destructor Documentation
DOMDeepNodeListPool() [1/12]
template<class TVal , class THasher > DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const XMLSize_t initSize = 128)
Definition at line 95 of file DOMDeepNodeListPool.c.
DOMDeepNodeListPool() [2/12]
template<class TVal , class THasher > XERCES_CPP_NAMESPACE_BEGIN DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize = 128)
$Id$
Definition at line 41 of file DOMDeepNodeListPool.c.
References MemoryManager::allocate(), DOMDeepNodeListPool< TVal, THasher >::fIdPtrs, DOMDeepNodeListPool< TVal, THasher >::fIdPtrsCount, DOMDeepNodeListPool< TVal, THasher >::fMemoryManager, and DOMDeepNodeListPool< TVal, THasher >::initialize().
DOMDeepNodeListPool() [3/12]
template<class TVal , class THasher > DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, const XMLSize_t initSize = 128)
Definition at line 67 of file DOMDeepNodeListPool.c.
References DOMDeepNodeListPool< TVal, THasher >::fIdPtrsCount, and DOMDeepNodeListPool< TVal, THasher >::initialize().
~DOMDeepNodeListPool() [1/3]
template<class TVal , class THasher > DOMDeepNodeListPool< TVal, THasher >::~DOMDeepNodeListPool
Definition at line 136 of file DOMDeepNodeListPool.c.
DOMDeepNodeListPool() [4/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const DOMDeepNodeListPool< TVal, THasher > &) private
DOMDeepNodeListPool() [5/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const XMLSize_t initSize = 128)
DOMDeepNodeListPool() [6/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize = 128)
DOMDeepNodeListPool() [7/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, const XMLSize_t initSize = 128)
~DOMDeepNodeListPool() [2/3]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::~DOMDeepNodeListPool ()
DOMDeepNodeListPool() [8/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const DOMDeepNodeListPool< TVal, THasher > &) private
DOMDeepNodeListPool() [9/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const XMLSize_t initSize = 128)
DOMDeepNodeListPool() [10/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const XMLSize_t initSize = 128)
DOMDeepNodeListPool() [11/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const XMLSize_t modulus, const bool adoptElems, const THasher & hasher, const XMLSize_t initSize = 128)
~DOMDeepNodeListPool() [3/3]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::~DOMDeepNodeListPool ()
DOMDeepNodeListPool() [12/12]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool (const DOMDeepNodeListPool< TVal, THasher > &) private
Member Function Documentation
cleanup() [1/3]
template<class TVal , class THasher > void DOMDeepNodeListPool< TVal, THasher >::cleanup
Definition at line 211 of file DOMDeepNodeListPool.c.
cleanup() [2/3]
template<class TVal , class THasher = PtrHasher> void DOMDeepNodeListPool< TVal, THasher >::cleanup ()
cleanup() [3/3]
template<class TVal , class THasher = PtrHasher> void DOMDeepNodeListPool< TVal, THasher >::cleanup ()
containsKey() [1/3]
template<class TVal , class THasher > bool DOMDeepNodeListPool< TVal, THasher >::containsKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
Definition at line 162 of file DOMDeepNodeListPool.c.
containsKey() [2/3]
template<class TVal , class THasher = PtrHasher> bool DOMDeepNodeListPool< TVal, THasher >::containsKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
containsKey() [3/3]
template<class TVal , class THasher = PtrHasher> bool DOMDeepNodeListPool< TVal, THasher >::containsKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
findBucketElem() [1/6]
template<class TVal , class THasher > DOMDeepNodeListPoolTableBucketElem< TVal > * DOMDeepNodeListPool< TVal, THasher >::findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t & hashVal) private
Definition at line 358 of file DOMDeepNodeListPool.c.
References XMLString::equals(), DOMDeepNodeListPoolTableBucketElem< TVal >::fKey1, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey2, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey3, and DOMDeepNodeListPoolTableBucketElem< TVal >::fNext.
findBucketElem() [2/6]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPoolTableBucketElem<TVal>* DOMDeepNodeListPool< TVal, THasher >::findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t & hashVal) private
findBucketElem() [3/6]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPoolTableBucketElem<TVal>* DOMDeepNodeListPool< TVal, THasher >::findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t & hashVal) private
findBucketElem() [4/6]
template<class TVal , class THasher > const DOMDeepNodeListPoolTableBucketElem< TVal > * DOMDeepNodeListPool< TVal, THasher >::findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t & hashVal) const private
Definition at line 394 of file DOMDeepNodeListPool.c.
References XMLString::equals(), DOMDeepNodeListPoolTableBucketElem< TVal >::fKey1, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey2, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey3, and DOMDeepNodeListPoolTableBucketElem< TVal >::fNext.
findBucketElem() [5/6]
template<class TVal , class THasher = PtrHasher> const DOMDeepNodeListPoolTableBucketElem<TVal>* DOMDeepNodeListPool< TVal, THasher >::findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t & hashVal) const private
findBucketElem() [6/6]
template<class TVal , class THasher = PtrHasher> const DOMDeepNodeListPoolTableBucketElem<TVal>* DOMDeepNodeListPool< TVal, THasher >::findBucketElem (const void *const key1, const XMLCh *const key2, const XMLCh *const key3, XMLSize_t & hashVal) const private
getById() [1/6]
template<class TVal , class THasher > TVal * DOMDeepNodeListPool< TVal, THasher >::getById (const XMLSize_t elemId)
Definition at line 249 of file DOMDeepNodeListPool.c.
References XMLExcepts::Pool_InvalidId, and ThrowXMLwithMemMgr.
getById() [2/6]
template<class TVal , class THasher = PtrHasher> TVal* DOMDeepNodeListPool< TVal, THasher >::getById (const XMLSize_t elemId)
getById() [3/6]
template<class TVal , class THasher = PtrHasher> TVal* DOMDeepNodeListPool< TVal, THasher >::getById (const XMLSize_t elemId)
getById() [4/6]
template<class TVal , class THasher > const TVal * DOMDeepNodeListPool< TVal, THasher >::getById (const XMLSize_t elemId) const
Definition at line 260 of file DOMDeepNodeListPool.c.
References XMLExcepts::Pool_InvalidId, and ThrowXMLwithMemMgr.
getById() [5/6]
template<class TVal , class THasher = PtrHasher> const TVal* DOMDeepNodeListPool< TVal, THasher >::getById (const XMLSize_t elemId) const
getById() [6/6]
template<class TVal , class THasher = PtrHasher> const TVal* DOMDeepNodeListPool< TVal, THasher >::getById (const XMLSize_t elemId) const
getByKey() [1/6]
template<class TVal , class THasher > TVal * DOMDeepNodeListPool< TVal, THasher >::getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3)
Definition at line 227 of file DOMDeepNodeListPool.c.
References DOMDeepNodeListPoolTableBucketElem< TVal >::fData.
getByKey() [2/6]
template<class TVal , class THasher = PtrHasher> TVal* DOMDeepNodeListPool< TVal, THasher >::getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3)
getByKey() [3/6]
template<class TVal , class THasher = PtrHasher> TVal* DOMDeepNodeListPool< TVal, THasher >::getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3)
getByKey() [4/6]
template<class TVal , class THasher > const TVal * DOMDeepNodeListPool< TVal, THasher >::getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
Definition at line 238 of file DOMDeepNodeListPool.c.
References DOMDeepNodeListPoolTableBucketElem< TVal >::fData.
getByKey() [5/6]
template<class TVal , class THasher = PtrHasher> const TVal* DOMDeepNodeListPool< TVal, THasher >::getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
getByKey() [6/6]
template<class TVal , class THasher = PtrHasher> const TVal* DOMDeepNodeListPool< TVal, THasher >::getByKey (const void *const key1, const XMLCh *const key2, const XMLCh *const key3) const
initialize() [1/3]
template<class TVal , class THasher > void DOMDeepNodeListPool< TVal, THasher >::initialize (const XMLSize_t modulus) private
Definition at line 120 of file DOMDeepNodeListPool.c.
References XMLExcepts::HshTbl_ZeroModulus, and ThrowXMLwithMemMgr.
Referenced by DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool().
initialize() [2/3]
template<class TVal , class THasher = PtrHasher> void DOMDeepNodeListPool< TVal, THasher >::initialize (const XMLSize_t modulus) private
initialize() [3/3]
template<class TVal , class THasher = PtrHasher> void DOMDeepNodeListPool< TVal, THasher >::initialize (const XMLSize_t modulus) private
isEmpty() [1/3]
template<class TVal , class THasher > bool DOMDeepNodeListPool< TVal, THasher >::isEmpty
Definition at line 150 of file DOMDeepNodeListPool.c.
isEmpty() [2/3]
template<class TVal , class THasher = PtrHasher> bool DOMDeepNodeListPool< TVal, THasher >::isEmpty () const
isEmpty() [3/3]
template<class TVal , class THasher = PtrHasher> bool DOMDeepNodeListPool< TVal, THasher >::isEmpty () const
operator=() [1/3]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool<TVal, THasher>& DOMDeepNodeListPool< TVal, THasher >::operator= (const DOMDeepNodeListPool< TVal, THasher > &) private
operator=() [2/3]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool<TVal, THasher>& DOMDeepNodeListPool< TVal, THasher >::operator= (const DOMDeepNodeListPool< TVal, THasher > &) private
operator=() [3/3]
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPool<TVal, THasher>& DOMDeepNodeListPool< TVal, THasher >::operator= (const DOMDeepNodeListPool< TVal, THasher > &) private
put() [1/3]
template<class TVal , class THasher > XMLSize_t DOMDeepNodeListPool< TVal, THasher >::put (void * key1, XMLCh * key2, XMLCh * key3, TVal *const valueToAdopt)
Definition at line 274 of file DOMDeepNodeListPool.c.
References DOMDeepNodeListPoolTableBucketElem< TVal >::fData, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey1, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey2, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey3, and XMLString::replicate().
put() [2/3]
template<class TVal , class THasher = PtrHasher> XMLSize_t DOMDeepNodeListPool< TVal, THasher >::put (void * key1, XMLCh * key2, XMLCh * key3, TVal *const valueToAdopt)
put() [3/3]
template<class TVal , class THasher = PtrHasher> XMLSize_t DOMDeepNodeListPool< TVal, THasher >::put (void * key1, XMLCh * key2, XMLCh * key3, TVal *const valueToAdopt)
removeAll() [1/3]
template<class TVal , class THasher > void DOMDeepNodeListPool< TVal, THasher >::removeAll
Definition at line 172 of file DOMDeepNodeListPool.c.
References DOMDeepNodeListPoolTableBucketElem< TVal >::fData, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey2, DOMDeepNodeListPoolTableBucketElem< TVal >::fKey3, and DOMDeepNodeListPoolTableBucketElem< TVal >::fNext.
removeAll() [2/3]
template<class TVal , class THasher = PtrHasher> void DOMDeepNodeListPool< TVal, THasher >::removeAll ()
removeAll() [3/3]
template<class TVal , class THasher = PtrHasher> void DOMDeepNodeListPool< TVal, THasher >::removeAll ()
Member Data Documentation
fAdoptedElems
template<class TVal , class THasher = PtrHasher> bool DOMDeepNodeListPool< TVal, THasher >::fAdoptedElems private
Definition at line 184 of file DOMDeepNodeListPool.hpp.
fBucketList
template<class TVal , class THasher = PtrHasher> DOMDeepNodeListPoolTableBucketElem< TVal > ** DOMDeepNodeListPool< TVal, THasher >::fBucketList private
Definition at line 185 of file DOMDeepNodeListPool.hpp.
fHasher
template<class TVal , class THasher = PtrHasher> THasher DOMDeepNodeListPool< TVal, THasher >::fHasher private
Definition at line 191 of file DOMDeepNodeListPool.hpp.
fHashModulus
template<class TVal , class THasher = PtrHasher> XMLSize_t DOMDeepNodeListPool< TVal, THasher >::fHashModulus private
Definition at line 186 of file DOMDeepNodeListPool.hpp.
fIdCounter
template<class TVal , class THasher = PtrHasher> XMLSize_t DOMDeepNodeListPool< TVal, THasher >::fIdCounter private
Definition at line 189 of file DOMDeepNodeListPool.hpp.
fIdPtrs
template<class TVal , class THasher = PtrHasher> TVal ** DOMDeepNodeListPool< TVal, THasher >::fIdPtrs private
Definition at line 187 of file DOMDeepNodeListPool.hpp.
Referenced by DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool().
fIdPtrsCount
template<class TVal , class THasher = PtrHasher> XMLSize_t DOMDeepNodeListPool< TVal, THasher >::fIdPtrsCount private
Definition at line 188 of file DOMDeepNodeListPool.hpp.
Referenced by DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool().
fMemoryManager
template<class TVal , class THasher = PtrHasher> MemoryManager * DOMDeepNodeListPool< TVal, THasher >::fMemoryManager private
Definition at line 190 of file DOMDeepNodeListPool.hpp.
Referenced by DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool().
The documentation for this class was generated from the following files:
src/libs/xerces-c/macx/include/xercesc/dom/impl/DOMDeepNodeListPool.hpp
src/libs/xerces-c/macx/include/xercesc/dom/impl/DOMDeepNodeListPool.c