Seamly2D: DialogTriangle Class Reference
DialogTriangle Class Reference
The DialogTriangle class dialog for ToolTriangle. Help create point and edit option.
#include <dialogtriangle.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
virtual void PointNameChanged () Q_DECL_OVERRIDE
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogTriangle (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTriangle create dialog.
virtual ~DialogTriangle () Q_DECL_OVERRIDE
quint32 GetAxisP1Id () const
GetAxisP1Id return id first point of axis.
void SetAxisP1Id (const quint32 &value)
SetAxisP1Id set id first point of axis.
quint32 GetAxisP2Id () const
GetAxisP2Id return id second point of axis.
void SetAxisP2Id (const quint32 &value)
SetAxisP2Id set id second point of axis.
quint32 GetFirstPointId () const
GetFirstPointId return id of first point.
void SetFirstPointId (const quint32 &value)
SetFirstPointId set id of first point.
quint32 GetSecondPointId () const
GetSecondPointId return id of second point.
void SetSecondPointId (const quint32 &value)
SetSecondPointId set id of second point.
void SetPointName (const QString &value)
SetPointName set name of point.
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
virtual void CheckState ()
CheckState enable, when all is correct, or disable, when something wrong, button ok.
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Attributes
Ui::DialogTriangle * ui
ui keeps information about user interface
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
The DialogTriangle class dialog for ToolTriangle. Help create point and edit option.
Definition at line 72 of file dialogtriangle.h.
Constructor & Destructor Documentation
DialogTriangle()
DialogTriangle::DialogTriangle (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
DialogTriangle create dialog.
Parameters
data container with data
parent parent widget
Definition at line 74 of file dialogtriangle.cpp.
References DialogTool::CheckState(), DialogTool::data, DialogTool::FillComboBoxPoints(), DialogTool::initializeOkCancelApply(), DialogTool::labelEditNamePoint, DialogTool::NamePointChanged(), NewLabel, PointNameChanged(), qApp, ui, and DialogTool::vis.
~DialogTriangle()
DialogTriangle::~DialogTriangle () virtual
Definition at line 105 of file dialogtriangle.cpp.
References ui.
Member Function Documentation
ChosenObject
void DialogTriangle::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
Parameters
id id of point or detail
type type of object
Definition at line 116 of file dialogtriangle.cpp.
References DialogTool::DialogAccepted(), DialogTool::getCurrentObjectId(), DialogTool::number, Point, DialogTool::prepare, VisToolTriangle::RefreshGeometry(), SCASSERT, VisToolTriangle::setHypotenuseP1Id(), VisToolTriangle::setHypotenuseP2Id(), DialogTool::SetObject(), VisToolTriangle::setObject2Id(), ui, DialogTool::vis, and Visualization::VisualMode().
GetAxisP1Id()
quint32 DialogTriangle::GetAxisP1Id () const
GetAxisP1Id return id first point of axis.
Returns
id
Definition at line 310 of file dialogtriangle.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
GetAxisP2Id()
quint32 DialogTriangle::GetAxisP2Id () const
GetAxisP2Id return id second point of axis.
Returns
id
Definition at line 320 of file dialogtriangle.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
GetFirstPointId()
quint32 DialogTriangle::GetFirstPointId () const
GetFirstPointId return id of first point.
Returns
id
Definition at line 330 of file dialogtriangle.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
GetSecondPointId()
quint32 DialogTriangle::GetSecondPointId () const
GetSecondPointId return id of second point.
Returns
id
Definition at line 340 of file dialogtriangle.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
PointNameChanged
void DialogTriangle::PointNameChanged () virtual slot
Definition at line 206 of file dialogtriangle.cpp.
References DialogTool::ChangeColor(), DialogTool::CheckState(), DialogTool::errorColor, DialogTool::flagError, DialogTool::getCurrentObjectId(), DialogTool::okColor, and ui.
Referenced by DialogTriangle().
SaveData()
void DialogTriangle::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 191 of file dialogtriangle.cpp.
References GetAxisP1Id(), GetAxisP2Id(), GetFirstPointId(), GetSecondPointId(), DialogTool::pointName, VisToolTriangle::RefreshGeometry(), SCASSERT, VisToolTriangle::setHypotenuseP1Id(), VisToolTriangle::setHypotenuseP2Id(), Visualization::setObject1Id(), VisToolTriangle::setObject2Id(), ui, and DialogTool::vis.
SetAxisP1Id()
void DialogTriangle::SetAxisP1Id (const quint32 & value)
SetAxisP1Id set id first point of axis.
Parameters
value id
Definition at line 296 of file dialogtriangle.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), Visualization::setObject1Id(), ui, and DialogTool::vis.
SetAxisP2Id()
void DialogTriangle::SetAxisP2Id (const quint32 & value)
SetAxisP2Id set id second point of axis.
Parameters
value id
Definition at line 282 of file dialogtriangle.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), VisToolTriangle::setObject2Id(), ui, and DialogTool::vis.
SetFirstPointId()
void DialogTriangle::SetFirstPointId (const quint32 & value)
SetFirstPointId set id of first point.
Parameters
value id
Definition at line 268 of file dialogtriangle.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), VisToolTriangle::setHypotenuseP1Id(), ui, and DialogTool::vis.
SetPointName()
void DialogTriangle::SetPointName (const QString & value)
SetPointName set name of point.
Parameters
value name
Definition at line 243 of file dialogtriangle.cpp.
References DialogTool::pointName, and ui.
SetSecondPointId()
void DialogTriangle::SetSecondPointId (const quint32 & value)
SetSecondPointId set id of second point.
Parameters
value id
Definition at line 254 of file dialogtriangle.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), VisToolTriangle::setHypotenuseP2Id(), ui, and DialogTool::vis.
ShowVisualization()
void DialogTriangle::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 233 of file dialogtriangle.cpp.
Member Data Documentation
ui
Ui::DialogTriangle* DialogTriangle::ui private
ui keeps information about user interface
Definition at line 105 of file dialogtriangle.h.
Referenced by ChosenObject(), DialogTriangle(), GetAxisP1Id(), GetAxisP2Id(), GetFirstPointId(), GetSecondPointId(), PointNameChanged(), SaveData(), SetAxisP1Id(), SetAxisP2Id(), SetFirstPointId(), SetPointName(), SetSecondPointId(), and ~DialogTriangle().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogtriangle.h
src/libs/vtools/dialogs/tools/dialogtriangle.cpp