Seamly2D: DialogArc Class Reference
DialogArc Class Reference
The DialogArc class dialog for ToolArc. Help create arc and edit option.
#include <dialogarc.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
void DeployFormulaTextEdit ()
DeployFormulaTextEdit grow or shrink formula input.
void DeployF1TextEdit ()
void DeployF2TextEdit ()
void RadiusChanged ()
RadiusChanged after change formula of radius calculate value and show result.
void F1Changed ()
F1Changed after change formula of first angle calculate value and show result.
void F2Changed ()
F2Changed after change formula of second angle calculate value and show result.
void FXRadius ()
void FXF1 ()
void FXF2 ()
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogArc (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogArc create dialog.
virtual ~DialogArc () Q_DECL_OVERRIDE
VArc getArc () const
void setArc (const VArc &arc)
quint32 getCenter () const
getCenter return id of center point
void setCenter (const quint32 &value)
setCenter set id of center point
QString getRadius () const
getRadius return formula of radius
void setRadius (const QString &value)
setRadius set formula of radius
QString getF1 () const
getF1 return formula first angle of arc
void setF1 (const QString &value)
setF1 set formula first angle of arc
QString getF2 () const
getF2 return formula second angle of arc
void setF2 (const QString &value)
setF2 set formula second angle of arc
QString getPenStyle () const
void setPenStyle (const QString &value)
QString getLineWeight () const
getLineWeight return weight of the lines
void setLineWeight (const QString &value)
setLineWeight set weight of the lines
QString getLineColor () const
void setLineColor (const QString &value)
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
void pointNameChanged ()
virtual void CheckState () Q_DECL_FINAL
CheckState if all is right enable button ok.
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Member Functions
void EvalRadius ()
EvalRadius calculate value of radius.
void EvalF ()
EvalF1 calculate value of angle.
void CheckAngles ()
Private Attributes
Ui::DialogArc * ui
ui keeps information about user interface
bool flagRadius
flagRadius true if value of radius is correct
bool flagF1
flagF1 true if value of first angle is correct
bool flagF2
flagF2 true if value of second angle is correct
QTimer * timerRadius
timerRadius timer of check formula of radius
QTimer * timerF1
timerF1 timer of check formula of first angle
QTimer * timerF2
timerF2 timer of check formula of second angle
QString radius
radius formula of radius
QString f1
f1 formula of first angle
QString f2
f2 formula of second angle
int formulaBaseHeight
formulaBaseHeight base height defined by dialogui
int formulaBaseHeightF1
int formulaBaseHeightF2
qreal angleF1
qreal angleF2
VArc m_arc
qint32 m_Id
qint32 newDuplicate
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
The DialogArc class dialog for ToolArc. Help create arc and edit option.
Definition at line 68 of file dialogarc.h.
Constructor & Destructor Documentation
DialogArc()
DialogArc::DialogArc (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
DialogArc create dialog.
Parameters
data container with data
parent parent widget
Definition at line 77 of file dialogarc.cpp.
References CheckState(), DialogTool::data, DeployF1TextEdit(), DeployF2TextEdit(), DeployFormulaTextEdit(), EvalF(), EvalRadius(), F1Changed(), F2Changed(), DialogTool::FillComboBoxPoints(), formulaBaseHeight, formulaBaseHeightF1, formulaBaseHeightF2, FXF1(), FXF2(), FXRadius(), VContainer::getId(), DialogTool::initializeOkCancelApply(), LineTypeNone, m_Id, DialogTool::plainTextEditFormula, pointNameChanged(), qApp, RadiusChanged(), timerF1, timerF2, timerRadius, ui, and DialogTool::vis.
~DialogArc()
DialogArc::~DialogArc () virtual
Definition at line 187 of file dialogarc.cpp.
References ui.
Member Function Documentation
CheckAngles()
void DialogArc::CheckAngles () private
Definition at line 549 of file dialogarc.cpp.
References angleF1, angleF2, DialogTool::ChangeColor(), CheckState(), flagF1, flagF2, ui, and VFuzzyComparePossibleNulls().
Referenced by EvalF().
CheckState()
void DialogArc::CheckState () protected virtual
CheckState if all is right enable button ok.
Reimplemented from DialogTool.
Definition at line 504 of file dialogarc.cpp.
References DialogTool::apply_Button, flagF1, flagF2, flagRadius, DialogTool::ok_Button, and SCASSERT.
Referenced by CheckAngles(), DialogArc(), EvalRadius(), and pointNameChanged().
ChosenObject
void DialogArc::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
Parameters
id id of point or detail
type type of object
Definition at line 332 of file dialogarc.cpp.
References Point, DialogTool::prepare, DialogTool::SetObject(), ui, and DialogTool::vis.
closeEvent()
void DialogArc::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 376 of file dialogarc.cpp.
References DialogTool::closeEvent(), and ui.
DeployF1TextEdit
void DialogArc::DeployF1TextEdit () slot
Definition at line 175 of file dialogarc.cpp.
References DialogTool::DeployFormula(), formulaBaseHeightF1, and ui.
Referenced by DialogArc(), and setF1().
DeployF2TextEdit
void DialogArc::DeployF2TextEdit () slot
Definition at line 181 of file dialogarc.cpp.
References DialogTool::DeployFormula(), formulaBaseHeightF2, and ui.
Referenced by DialogArc(), and setF2().
DeployFormulaTextEdit
void DialogArc::DeployFormulaTextEdit () slot
DeployFormulaTextEdit grow or shrink formula input.
Definition at line 169 of file dialogarc.cpp.
References DialogTool::DeployFormula(), formulaBaseHeight, and ui.
Referenced by DialogArc(), and setRadius().
EvalF()
void DialogArc::EvalF () private
EvalF1 calculate value of angle.
Definition at line 537 of file dialogarc.cpp.
References angleF1, angleF2, CheckAngles(), degreeSymbol, DialogTool::Eval(), flagF1, flagF2, DialogTool::labelEditFormula, and ui.
Referenced by DialogArc().
EvalRadius()
void DialogArc::EvalRadius () private
EvalRadius calculate value of radius.
Definition at line 516 of file dialogarc.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::Eval(), flagRadius, DialogTool::labelEditFormula, qApp, radius, ui, and UnitsToStr().
Referenced by DialogArc().
F1Changed
void DialogArc::F1Changed () slot
F1Changed after change formula of first angle calculate value and show result.
Definition at line 400 of file dialogarc.cpp.
References degreeSymbol, flagF1, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, timerF1, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogArc().
F2Changed
void DialogArc::F2Changed () slot
F2Changed after change formula of second angle calculate value and show result.
Definition at line 411 of file dialogarc.cpp.
References degreeSymbol, flagF2, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, timerF2, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogArc().
FXF1
void DialogArc::FXF1 () slot
Definition at line 433 of file dialogarc.cpp.
References DialogTool::data, degreeSymbol, getF1(), EditFormulaDialog::GetFormula(), setF1(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), and DialogTool::toolId.
Referenced by DialogArc().
FXF2
void DialogArc::FXF2 () slot
Definition at line 447 of file dialogarc.cpp.
References DialogTool::data, degreeSymbol, getF2(), EditFormulaDialog::GetFormula(), setF2(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), and DialogTool::toolId.
Referenced by DialogArc().
FXRadius
void DialogArc::FXRadius () slot
Definition at line 419 of file dialogarc.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), getRadius(), qApp, EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), setRadius(), DialogTool::toolId, and UnitsToStr().
Referenced by DialogArc().
getArc()
VArc DialogArc::getArc () const
Definition at line 193 of file dialogarc.cpp.
References m_arc.
getCenter()
quint32 DialogArc::getCenter () const
getCenter return id of center point
Returns
id id
Definition at line 577 of file dialogarc.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
getF1()
QString DialogArc::getF1 () const
getF1 return formula first angle of arc
Returns
formula
Definition at line 597 of file dialogarc.cpp.
References f1, and qApp.
Referenced by FXF1(), and pointNameChanged().
getF2()
QString DialogArc::getF2 () const
getF2 return formula second angle of arc
Returns
formula
Definition at line 607 of file dialogarc.cpp.
References f2, and qApp.
Referenced by FXF2(), and pointNameChanged().
getLineColor()
QString DialogArc::getLineColor () const
Definition at line 271 of file dialogarc.cpp.
References ColorBlack, DialogTool::GetComboBoxCurrentData(), and ui.
getLineWeight()
QString DialogArc::getLineWeight () const
getLineWeight return weight of the lines
Returns
type
Definition at line 255 of file dialogarc.cpp.
References DialogTool::GetComboBoxCurrentData(), and ui.
getPenStyle()
QString DialogArc::getPenStyle () const
Definition at line 239 of file dialogarc.cpp.
References DialogTool::GetComboBoxCurrentData(), LineTypeSolidLine, and ui.
getRadius()
QString DialogArc::getRadius () const
getRadius return formula of radius
Returns
formula
Definition at line 587 of file dialogarc.cpp.
References qApp, and radius.
Referenced by FXRadius(), and pointNameChanged().
pointNameChanged()
void DialogArc::pointNameChanged () protected
Definition at line 461 of file dialogarc.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::data, DialogTool::DNumber(), DialogTool::flagError, VContainer::GeometricObject(), VAbstractArc::GetCenter(), DialogTool::getCurrentObjectId(), getF1(), getF2(), getRadius(), VGObject::id(), VContainer::IsUnique(), m_arc, m_Id, VGObject::name(), newDuplicate, NULL_ID, DialogTool::okColor, qApp, VAbstractCurve::SetDuplicate(), and ui.
Referenced by DialogArc().
RadiusChanged
void DialogArc::RadiusChanged () slot
RadiusChanged after change formula of radius calculate value and show result.
Definition at line 388 of file dialogarc.cpp.
References flagRadius, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, qApp, timerRadius, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by DialogArc().
SaveData()
void DialogArc::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 356 of file dialogarc.cpp.
References f1, f2, getCenter(), radius, VisToolArc::RefreshGeometry(), SCASSERT, VisToolArc::setF1(), VisToolArc::setF2(), Visualization::setObject1Id(), VisToolArc::setRadius(), ui, and DialogTool::vis.
setArc()
void DialogArc::setArc (const VArc & arc)
Definition at line 199 of file dialogarc.cpp.
References m_arc, VGObject::name(), qApp, and ui.
setCenter()
void DialogArc::setCenter (const quint32 & value)
setCenter set id of center point
Parameters
value id
Definition at line 210 of file dialogarc.cpp.
References DialogTool::ChangeCurrentData(), ui, and DialogTool::vis.
setF1()
void DialogArc::setF1 (const QString & value)
setF1 set formula first angle of arc
Parameters
value formula
Definition at line 287 of file dialogarc.cpp.
References DeployF1TextEdit(), f1, DialogTool::MoveCursorToEnd(), qApp, SCASSERT, VisToolArc::setF1(), ui, and DialogTool::vis.
Referenced by FXF1().
setF2()
void DialogArc::setF2 (const QString & value)
setF2 set formula second angle of arc
Parameters
value formula
Definition at line 221 of file dialogarc.cpp.
References DeployF2TextEdit(), f2, DialogTool::MoveCursorToEnd(), qApp, SCASSERT, VisToolArc::setF2(), ui, and DialogTool::vis.
Referenced by FXF2().
setLineColor()
void DialogArc::setLineColor (const QString & value)
Definition at line 277 of file dialogarc.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setLineWeight()
void DialogArc::setLineWeight (const QString & value)
setLineWeight set weight of the lines
Parameters
value type
Definition at line 265 of file dialogarc.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setPenStyle()
void DialogArc::setPenStyle (const QString & value)
Definition at line 245 of file dialogarc.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setRadius()
void DialogArc::setRadius (const QString & value)
setRadius set formula of radius
Parameters
value formula
Definition at line 309 of file dialogarc.cpp.
References DeployFormulaTextEdit(), DialogTool::MoveCursorToEnd(), qApp, radius, SCASSERT, VisToolArc::setRadius(), ui, and DialogTool::vis.
Referenced by FXRadius().
ShowVisualization()
void DialogArc::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 350 of file dialogarc.cpp.
Member Data Documentation
angleF1
qreal DialogArc::angleF1 private
Definition at line 163 of file dialogarc.h.
Referenced by CheckAngles(), and EvalF().
angleF2
qreal DialogArc::angleF2 private
Definition at line 164 of file dialogarc.h.
Referenced by CheckAngles(), and EvalF().
f1
QString DialogArc::f1 private
f1 formula of first angle
Definition at line 153 of file dialogarc.h.
Referenced by getF1(), SaveData(), and setF1().
f2
QString DialogArc::f2 private
f2 formula of second angle
Definition at line 156 of file dialogarc.h.
Referenced by getF2(), SaveData(), and setF2().
flagF1
bool DialogArc::flagF1 private
flagF1 true if value of first angle is correct
Definition at line 135 of file dialogarc.h.
Referenced by CheckAngles(), CheckState(), EvalF(), and F1Changed().
flagF2
bool DialogArc::flagF2 private
flagF2 true if value of second angle is correct
Definition at line 138 of file dialogarc.h.
Referenced by CheckAngles(), CheckState(), EvalF(), and F2Changed().
flagRadius
bool DialogArc::flagRadius private
flagRadius true if value of radius is correct
Definition at line 132 of file dialogarc.h.
Referenced by CheckState(), EvalRadius(), and RadiusChanged().
formulaBaseHeight
int DialogArc::formulaBaseHeight private
formulaBaseHeight base height defined by dialogui
Definition at line 159 of file dialogarc.h.
Referenced by DeployFormulaTextEdit(), and DialogArc().
formulaBaseHeightF1
int DialogArc::formulaBaseHeightF1 private
Definition at line 160 of file dialogarc.h.
Referenced by DeployF1TextEdit(), and DialogArc().
formulaBaseHeightF2
int DialogArc::formulaBaseHeightF2 private
Definition at line 161 of file dialogarc.h.
Referenced by DeployF2TextEdit(), and DialogArc().
m_arc
VArc DialogArc::m_arc private
Definition at line 165 of file dialogarc.h.
Referenced by getArc(), pointNameChanged(), and setArc().
m_Id
qint32 DialogArc::m_Id private
Definition at line 166 of file dialogarc.h.
Referenced by DialogArc(), and pointNameChanged().
newDuplicate
qint32 DialogArc::newDuplicate private
Definition at line 167 of file dialogarc.h.
Referenced by pointNameChanged().
radius
QString DialogArc::radius private
radius formula of radius
Definition at line 150 of file dialogarc.h.
Referenced by EvalRadius(), getRadius(), SaveData(), and setRadius().
timerF1
QTimer* DialogArc::timerF1 private
timerF1 timer of check formula of first angle
Definition at line 144 of file dialogarc.h.
Referenced by DialogArc(), and F1Changed().
timerF2
QTimer* DialogArc::timerF2 private
timerF2 timer of check formula of second angle
Definition at line 147 of file dialogarc.h.
Referenced by DialogArc(), and F2Changed().
timerRadius
QTimer* DialogArc::timerRadius private
timerRadius timer of check formula of radius
Definition at line 141 of file dialogarc.h.
Referenced by DialogArc(), and RadiusChanged().
ui
Ui::DialogArc* DialogArc::ui private
ui keeps information about user interface
Definition at line 129 of file dialogarc.h.
Referenced by CheckAngles(), ChosenObject(), closeEvent(), DeployF1TextEdit(), DeployF2TextEdit(), DeployFormulaTextEdit(), DialogArc(), EvalF(), EvalRadius(), F1Changed(), F2Changed(), getCenter(), getLineColor(), getLineWeight(), getPenStyle(), pointNameChanged(), RadiusChanged(), SaveData(), setArc(), setCenter(), setF1(), setF2(), setLineColor(), setLineWeight(), setPenStyle(), setRadius(), and ~DialogArc().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogarc.h
src/libs/vtools/dialogs/tools/dialogarc.cpp