Seamly2D: DialogAboutSeamlyMe Class Reference
DialogAboutSeamlyMe Class Reference
#include <dialogaboutseamlyme.h>
Public Slots
void setProgressValue (int val)
Public Member Functions
DialogAboutSeamlyMe (QWidget *parent=nullptr)
virtual ~DialogAboutSeamlyMe ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
Private Member Functions
void FontPointSize (QWidget *w, int pointSize)
void RetranslateUi ()
Private Attributes
Ui::DialogAboutSeamlyMe * ui
bool isInitialized
Detailed Description
Definition at line 62 of file dialogaboutseamlyme.h.
Constructor & Destructor Documentation
DialogAboutSeamlyMe()
DialogAboutSeamlyMe::DialogAboutSeamlyMe (QWidget * parent = nullptr) explicit
Definition at line 66 of file dialogaboutseamlyme.cpp.
References RetranslateUi(), and ui.
~DialogAboutSeamlyMe()
DialogAboutSeamlyMe::~DialogAboutSeamlyMe () virtual
Definition at line 102 of file dialogaboutseamlyme.cpp.
References ui.
Member Function Documentation
changeEvent()
void DialogAboutSeamlyMe::changeEvent (QEvent * event) protected virtual
Definition at line 108 of file dialogaboutseamlyme.cpp.
References RetranslateUi(), and ui.
FontPointSize()
void DialogAboutSeamlyMe::FontPointSize (QWidget * w, int pointSize) private
Definition at line 143 of file dialogaboutseamlyme.cpp.
References SCASSERT.
RetranslateUi()
void DialogAboutSeamlyMe::RetranslateUi () private
Definition at line 153 of file dialogaboutseamlyme.cpp.
References APP_VERSION_STR, buildCompatibilityString(), translate, ui, and VER_COMPANYDOMAIN_STR.
Referenced by changeEvent(), and DialogAboutSeamlyMe().
setProgressValue
void DialogAboutSeamlyMe::setProgressValue (int val) slot
Definition at line 170 of file dialogaboutseamlyme.cpp.
References ui.
showEvent()
void DialogAboutSeamlyMe::showEvent (QShowEvent * event) protected virtual
Definition at line 122 of file dialogaboutseamlyme.cpp.
References isInitialized.
Member Data Documentation
isInitialized
bool DialogAboutSeamlyMe::isInitialized private
Definition at line 80 of file dialogaboutseamlyme.h.
Referenced by showEvent().
ui
Ui::DialogAboutSeamlyMe* DialogAboutSeamlyMe::ui private
Definition at line 79 of file dialogaboutseamlyme.h.
Referenced by changeEvent(), DialogAboutSeamlyMe(), RetranslateUi(), setProgressValue(), and ~DialogAboutSeamlyMe().
The documentation for this class was generated from the following files:
src/app/seamlyme/dialogs/dialogaboutseamlyme.h
src/app/seamlyme/dialogs/dialogaboutseamlyme.cpp