Seamly2D: src/libs/vpatterndb/measurements_def.cpp File Reference
measurements_def.cpp File Reference
#include "measurements_def.h"
#include "vtranslatemeasurements.h"
#include "../vmisc/def.h"
Functions
QStringList ListGroupA ()
QStringList ListGroupB ()
QStringList ListGroupC ()
QStringList ListGroupD ()
QStringList ListGroupE ()
QStringList ListGroupF ()
QStringList ListGroupG ()
QStringList ListGroupH ()
QStringList ListGroupI ()
QStringList ListGroupJ ()
QStringList ListGroupK ()
QStringList ListGroupL ()
QStringList ListGroupM ()
QStringList ListGroupN ()
QStringList ListGroupO ()
QStringList ListGroupP ()
QStringList ListGroupQ ()
QStringList ListNumbers (const VTranslateMeasurements *trM, const QStringList &listMeasurements)
QString MapDiagrams (const VTranslateMeasurements *trM, const QString &number)
QStringList AllGroupNames ()
Variables
const QString height_M = QStringLiteral("height")
const QString heightNeckBack_M = QStringLiteral("height_neck_back")
const QString heightScapula_M = QStringLiteral("height_scapula")
const QString heightArmpit_M = QStringLiteral("height_armpit")
const QString heightWaistSide_M = QStringLiteral("height_waist_side")
const QString heightHip_M = QStringLiteral("height_hip")
const QString heightGlutealFold_M = QStringLiteral("height_gluteal_fold")
const QString heightKnee_M = QStringLiteral("height_knee")
const QString heightCalf_M = QStringLiteral("height_calf")
const QString heightAnkleHigh_M = QStringLiteral("height_ankle_high")
const QString heightAnkle_M = QStringLiteral("height_ankle")
const QString heightHighhip_M = QStringLiteral("height_highhip")
const QString heightWaistFront_M = QStringLiteral("height_waist_front")
const QString heightBustpoint_M = QStringLiteral("height_bustpoint")
const QString heightShoulderTip_M = QStringLiteral("height_shoulder_tip")
const QString heightNeckFront_M = QStringLiteral("height_neck_front")
const QString heightNeckSide_M = QStringLiteral("height_neck_side")
const QString heightNeckBackToKnee_M = QStringLiteral("height_neck_back_to_knee")
const QString heightWaistSideToKnee_M = QStringLiteral("height_waist_side_to_knee")
const QString heightWaistSideToHip_M = QStringLiteral("height_waist_side_to_hip")
const QString heightKneeToAnkle_M = QStringLiteral("height_knee_to_ankle")
const QString heightNeckBackToWaistSide_M = QStringLiteral("height_neck_back_to_waist_side")
const QString heightWaistBack_M = QStringLiteral("height_waist_back")
const QString widthShoulder_M = QStringLiteral("width_shoulder")
const QString widthBust_M = QStringLiteral("width_bust")
const QString widthWaist_M = QStringLiteral("width_waist")
const QString widthHip_M = QStringLiteral("width_hip")
const QString widthAbdomenToHip_M = QStringLiteral("width_abdomen_to_hip")
const QString indentNeckBack_M = QStringLiteral("indent_neck_back")
const QString indentWaistBack_M = QStringLiteral("indent_waist_back")
const QString indentAnkleHigh_M = QStringLiteral("indent_ankle_high")
const QString handPalmLength_M = QStringLiteral("hand_palm_length")
const QString handLength_M = QStringLiteral("hand_length")
const QString handPalmWidth_M = QStringLiteral("hand_palm_width")
const QString handPalmCirc_M = QStringLiteral("hand_palm_circ")
const QString handCirc_M = QStringLiteral("hand_circ")
const QString footWidth_M = QStringLiteral("foot_width")
const QString footLength_M = QStringLiteral("foot_length")
const QString footCirc_M = QStringLiteral("foot_circ")
const QString footInstepCirc_M = QStringLiteral("foot_instep_circ")
const QString headCirc_M = QStringLiteral("head_circ")
const QString headLength_M = QStringLiteral("head_length")
const QString headDepth_M = QStringLiteral("head_depth")
const QString headWidth_M = QStringLiteral("head_width")
const QString headCrownToNeckBack_M = QStringLiteral("head_crown_to_neck_back")
const QString headChinToNeckBack_M = QStringLiteral("head_chin_to_neck_back")
const QString neckMidCirc_M = QStringLiteral("neck_mid_circ")
const QString neckCirc_M = QStringLiteral("neck_circ")
const QString highbustCirc_M = QStringLiteral("highbust_circ")
const QString bustCirc_M = QStringLiteral("bust_circ")
const QString lowbustCirc_M = QStringLiteral("lowbust_circ")
const QString ribCirc_M = QStringLiteral("rib_circ")
const QString waistCirc_M = QStringLiteral("waist_circ")
const QString highhipCirc_M = QStringLiteral("highhip_circ")
const QString hipCirc_M = QStringLiteral("hip_circ")
const QString neckArcF_M = QStringLiteral("neck_arc_f")
const QString highbustArcF_M = QStringLiteral("highbust_arc_f")
const QString size_M = QStringLiteral("size")
const QString bustArcF_M = QStringLiteral("bust_arc_f")
const QString lowbustArcF_M = QStringLiteral("lowbust_arc_f")
const QString ribArcF_M = QStringLiteral("rib_arc_f")
const QString waistArcF_M = QStringLiteral("waist_arc_f")
const QString highhipArcF_M = QStringLiteral("highhip_arc_f")
const QString hipArcF_M = QStringLiteral("hip_arc_f")
const QString neckArcHalfF_M = QStringLiteral("neck_arc_half_f")
const QString highbustArcHalfF_M = QStringLiteral("highbust_arc_half_f")
const QString bustArcHalfF_M = QStringLiteral("bust_arc_half_f")
const QString lowbustArcHalfF_M = QStringLiteral("lowbust_arc_half_f")
const QString ribArcHalfF_M = QStringLiteral("rib_arc_half_f")
const QString waistArcHalfF_M = QStringLiteral("waist_arc_half_f")
const QString highhipArcHalfF_M = QStringLiteral("highhip_arc_half_f")
const QString hipArcHalfF_M = QStringLiteral("hip_arc_half_f")
const QString neckArcB_M = QStringLiteral("neck_arc_b")
const QString highbustArcB_M = QStringLiteral("highbust_arc_b")
const QString bustArcB_M = QStringLiteral("bust_arc_b")
const QString lowbustArcB_M = QStringLiteral("lowbust_arc_b")
const QString ribArcB_M = QStringLiteral("rib_arc_b")
const QString waistArcB_M = QStringLiteral("waist_arc_b")
const QString highhipArcB_M = QStringLiteral("highhip_arc_b")
const QString hipArcB_M = QStringLiteral("hip_arc_b")
const QString neckArcHalfB_M = QStringLiteral("neck_arc_half_b")
const QString highbustArcHalfB_M = QStringLiteral("highbust_arc_half_b")
const QString bustArcHalfB_M = QStringLiteral("bust_arc_half_b")
const QString lowbustArcHalfB_M = QStringLiteral("lowbust_arc_half_b")
const QString ribArcHalfB_M = QStringLiteral("rib_arc_half_b")
const QString waistArcHalfB_M = QStringLiteral("waist_arc_half_b")
const QString highhipArcHalfB_M = QStringLiteral("highhip_arc_half_b")
const QString hipArcHalfB_M = QStringLiteral("hip_arc_half_b")
const QString hipWithAbdomenArcF_M = QStringLiteral("hip_with_abdomen_arc_f")
const QString bodyArmfoldCirc_M = QStringLiteral("body_armfold_circ")
const QString bodyBustCirc_M = QStringLiteral("body_bust_circ")
const QString bodyTorsoCirc_M = QStringLiteral("body_torso_circ")
const QString hipCircWithAbdomen_M = QStringLiteral("hip_circ_with_abdomen")
const QString neckFrontToWaistF_M = QStringLiteral("neck_front_to_waist_f")
const QString neckFrontToWaistFlatF_M = QStringLiteral("neck_front_to_waist_flat_f")
const QString armpitToWaistSide_M = QStringLiteral("armpit_to_waist_side")
const QString shoulderTipToWaistSideF_M = QStringLiteral("shoulder_tip_to_waist_side_f")
const QString neckSideToWaistF_M = QStringLiteral("neck_side_to_waist_f")
const QString neckSideToWaistBustpointF_M = QStringLiteral("neck_side_to_waist_bustpoint_f")
const QString neckFrontToHighbustF_M = QStringLiteral("neck_front_to_highbust_f")
const QString highbustToWaistF_M = QStringLiteral("highbust_to_waist_f")
const QString neckFrontToBustF_M = QStringLiteral("neck_front_to_bust_f")
const QString bustToWaistF_M = QStringLiteral("bust_to_waist_f")
const QString lowbustToWaistF_M = QStringLiteral("lowbust_to_waist_f")
const QString ribToWaistSide_M = QStringLiteral("rib_to_waist_side")
const QString shoulderTipToArmfoldF_M = QStringLiteral("shoulder_tip_to_armfold_f")
const QString neckSideToBustF_M = QStringLiteral("neck_side_to_bust_f")
const QString neckSideToHighbustF_M = QStringLiteral("neck_side_to_highbust_f")
const QString shoulderCenterToHighbustF_M = QStringLiteral("shoulder_center_to_highbust_f")
const QString shoulderTipToWaistSideB_M = QStringLiteral("shoulder_tip_to_waist_side_b")
const QString neckSideToWaistB_M = QStringLiteral("neck_side_to_waist_b")
const QString neckBackToWaistB_M = QStringLiteral("neck_back_to_waist_b")
const QString neckSideToWaistScapulaB_M = QStringLiteral("neck_side_to_waist_scapula_b")
const QString neckBackToHighbustB_M = QStringLiteral("neck_back_to_highbust_b")
const QString highbustToWaistB_M = QStringLiteral("highbust_to_waist_b")
const QString neckBackToBustB_M = QStringLiteral("neck_back_to_bust_b")
const QString bustToWaistB_M = QStringLiteral("bust_to_waist_b")
const QString lowbustToWaistB_M = QStringLiteral("lowbust_to_waist_b")
const QString shoulderTipToArmfoldB_M = QStringLiteral("shoulder_tip_to_armfold_b")
const QString neckSideToBustB_M = QStringLiteral("neck_side_to_bust_b")
const QString neckSideToHighbustB_M = QStringLiteral("neck_side_to_highbust_b")
const QString shoulderCenterToHighbustB_M = QStringLiteral("shoulder_center_to_highbust_b")
const QString waistToHighhipF_M = QStringLiteral("waist_to_highhip_f")
const QString waistToHipF_M = QStringLiteral("waist_to_hip_f")
const QString waistToHighhipSide_M = QStringLiteral("waist_to_highhip_side")
const QString waistToHighhipB_M = QStringLiteral("waist_to_highhip_b")
const QString waistToHipB_M = QStringLiteral("waist_to_hip_b")
const QString waistToHipSide_M = QStringLiteral("waist_to_hip_side")
const QString shoulderSlopeNeckSideAngle_M = QStringLiteral("shoulder_slope_neck_side_angle")
const QString shoulderSlopeNeckSideLength_M = QStringLiteral("shoulder_slope_neck_side_length")
const QString shoulderSlopeNeckBackAngle_M = QStringLiteral("shoulder_slope_neck_back_angle")
const QString shoulderSlopeNeckBackHeight_M = QStringLiteral("shoulder_slope_neck_back_height")
const QString shoulderSlopeShoulderTipAngle_M = QStringLiteral("shoulder_slope_shoulder_tip_angle")
const QString neckBackToAcrossBack_M = QStringLiteral("neck_back_to_across_back")
const QString acrossBackToWaistB_M = QStringLiteral("across_back_to_waist_b")
const QString shoulderLength_M = QStringLiteral("shoulder_length")
const QString shoulderTipToShoulderTipF_M = QStringLiteral("shoulder_tip_to_shoulder_tip_f")
const QString acrossChestF_M = QStringLiteral("across_chest_f")
const QString armfoldToArmfoldF_M = QStringLiteral("armfold_to_armfold_f")
const QString shoulderTipToShoulderTipHalfF_M = QStringLiteral("shoulder_tip_to_shoulder_tip_half_f")
const QString acrossChestHalfF_M = QStringLiteral("across_chest_half_f")
const QString shoulderTipToShoulderTipB_M = QStringLiteral("shoulder_tip_to_shoulder_tip_b")
const QString acrossBackB_M = QStringLiteral("across_back_b")
const QString armfoldToArmfoldB_M = QStringLiteral("armfold_to_armfold_b")
const QString shoulderTipToShoulderTipHalfB_M = QStringLiteral("shoulder_tip_to_shoulder_tip_half_b")
const QString acrossBackHalfB_M = QStringLiteral("across_back_half_b")
const QString neckFrontToShoulderTipF_M = QStringLiteral("neck_front_to_shoulder_tip_f")
const QString neckBackToShoulderTipB_M = QStringLiteral("neck_back_to_shoulder_tip_b")
const QString neckWidth_M = QStringLiteral("neck_width")
const QString bustpointToBustpoint_M = QStringLiteral("bustpoint_to_bustpoint")
const QString bustpointToNeckSide_M = QStringLiteral("bustpoint_to_neck_side")
const QString bustpointToLowbust_M = QStringLiteral("bustpoint_to_lowbust")
const QString bustpointToWaist_M = QStringLiteral("bustpoint_to_waist")
const QString bustpointToBustpointHalf_M = QStringLiteral("bustpoint_to_bustpoint_half")
const QString bustpointNeckSideToWaist_M = QStringLiteral("bustpoint_neck_side_to_waist")
const QString bustpointToShoulderTip_M = QStringLiteral("bustpoint_to_shoulder_tip")
const QString bustpointToWaistFront_M = QStringLiteral("bustpoint_to_waist_front")
const QString bustpointToBustpointHalter_M = QStringLiteral("bustpoint_to_bustpoint_halter")
const QString bustpointToShoulderCenter_M = QStringLiteral("bustpoint_to_shoulder_center")
const QString bustpointToNeckFront_M = QStringLiteral("bustpoint_to_neck_front")
const QString shoulderTipToWaistFront_M = QStringLiteral("shoulder_tip_to_waist_front")
const QString neckFrontToWaistSide_M = QStringLiteral("neck_front_to_waist_side")
const QString neckSideToWaistSideF_M = QStringLiteral("neck_side_to_waist_side_f")
const QString shoulderTipToWaistBack_M = QStringLiteral("shoulder_tip_to_waist_back")
const QString shoulderTipToWaistB_1inOffset_M = QStringLiteral("shoulder_tip_to_waist_b_1in_offset")
const QString neckBackToWaistSide_M = QStringLiteral("neck_back_to_waist_side")
const QString neckSideToWaistSideB_M = QStringLiteral("neck_side_to_waist_side_b")
const QString neckSideToArmfoldF_M = QStringLiteral("neck_side_to_armfold_f")
const QString neckSideToArmpitF_M = QStringLiteral("neck_side_to_armpit_f")
const QString neckSideToBustSideF_M = QStringLiteral("neck_side_to_bust_side_f")
const QString neckSideToArmfoldB_M = QStringLiteral("neck_side_to_armfold_b")
const QString neckSideToArmpitB_M = QStringLiteral("neck_side_to_armpit_b")
const QString neckSideToBustSideB_M = QStringLiteral("neck_side_to_bust_side_b")
const QString armShoulderTipToWristBent_M = QStringLiteral("arm_shoulder_tip_to_wrist_bent")
const QString armShoulderTipToElbowBent_M = QStringLiteral("arm_shoulder_tip_to_elbow_bent")
const QString armElbowToWristBent_M = QStringLiteral("arm_elbow_to_wrist_bent")
const QString armElbowCircBent_M = QStringLiteral("arm_elbow_circ_bent")
const QString armShoulderTipToWrist_M = QStringLiteral("arm_shoulder_tip_to_wrist")
const QString armShoulderTipToElbow_M = QStringLiteral("arm_shoulder_tip_to_elbow")
const QString armElbowToWrist_M = QStringLiteral("arm_elbow_to_wrist")
const QString armArmpitToWrist_M = QStringLiteral("arm_armpit_to_wrist")
const QString armArmpitToElbow_M = QStringLiteral("arm_armpit_to_elbow")
const QString armElbowToWristInside_M = QStringLiteral("arm_elbow_to_wrist_inside")
const QString armUpperCirc_M = QStringLiteral("arm_upper_circ")
const QString armAboveElbowCirc_M = QStringLiteral("arm_above_elbow_circ")
const QString armElbowCirc_M = QStringLiteral("arm_elbow_circ")
const QString armLowerCirc_M = QStringLiteral("arm_lower_circ")
const QString armWristCirc_M = QStringLiteral("arm_wrist_circ")
const QString armShoulderTipToArmfoldLine_M = QStringLiteral("arm_shoulder_tip_to_armfold_line")
const QString armNeckSideToWrist_M = QStringLiteral("arm_neck_side_to_wrist")
const QString armNeckSideToFingerTip_M = QStringLiteral("arm_neck_side_to_finger_tip")
const QString armscyeCirc_M = QStringLiteral("armscye_circ")
const QString armscyeLength_M = QStringLiteral("armscye_length")
const QString armscyeWidth_M = QStringLiteral("armscye_width")
const QString armNeckSideToOuterElbow_M = QStringLiteral("arm_neck_side_to_outer_elbow")
const QString legCrotchToFloor_M = QStringLiteral("leg_crotch_to_floor")
const QString legWaistSideToFloor_M = QStringLiteral("leg_waist_side_to_floor")
const QString legThighUpperCirc_M = QStringLiteral("leg_thigh_upper_circ")
const QString legThighMidCirc_M = QStringLiteral("leg_thigh_mid_circ")
const QString legKneeCirc_M = QStringLiteral("leg_knee_circ")
const QString legKneeSmallCirc_M = QStringLiteral("leg_knee_small_circ")
const QString legCalfCirc_M = QStringLiteral("leg_calf_circ")
const QString legAnkleHighCirc_M = QStringLiteral("leg_ankle_high_circ")
const QString legAnkleCirc_M = QStringLiteral("leg_ankle_circ")
const QString legKneeCircBent_M = QStringLiteral("leg_knee_circ_bent")
const QString legAnkleDiagCirc_M = QStringLiteral("leg_ankle_diag_circ")
const QString legCrotchToAnkle_M = QStringLiteral("leg_crotch_to_ankle")
const QString legWaistSideToAnkle_M = QStringLiteral("leg_waist_side_to_ankle")
const QString legWaistSideToKnee_M = QStringLiteral("leg_waist_side_to_knee")
const QString crotchLength_M = QStringLiteral("crotch_length")
const QString crotchLengthB_M = QStringLiteral("crotch_length_b")
const QString crotchLengthF_M = QStringLiteral("crotch_length_f")
const QString riseLengthSideSitting_M = QStringLiteral("rise_length_side_sitting")
const QString riseLengthDiag_M = QStringLiteral("rise_length_diag")
const QString riseLengthB_M = QStringLiteral("rise_length_b")
const QString riseLengthF_M = QStringLiteral("rise_length_f")
const QString riseLengthSide_M = QStringLiteral("rise_length_side")
const QString neckBackToWaistFront_M = QStringLiteral("neck_back_to_waist_front")
const QString waistToWaistHalter_M = QStringLiteral("waist_to_waist_halter")
const QString waistNaturalCirc_M = QStringLiteral("waist_natural_circ")
const QString waistNaturalArcF_M = QStringLiteral("waist_natural_arc_f")
const QString waistNaturalArcB_M = QStringLiteral("waist_natural_arc_b")
const QString waistToNaturalWaistF_M = QStringLiteral("waist_to_natural_waist_f")
const QString waistToNaturalWaistB_M = QStringLiteral("waist_to_natural_waist_b")
const QString armNeckBackToElbowBent_M = QStringLiteral("arm_neck_back_to_elbow_bent")
const QString armNeckBackToWristBent_M = QStringLiteral("arm_neck_back_to_wrist_bent")
const QString armNeckSideToElbowBent_M = QStringLiteral("arm_neck_side_to_elbow_bent")
const QString armNeckSideToWristBent_M = QStringLiteral("arm_neck_side_to_wrist_bent")
const QString armAcrossBackCenterToElbowBent_M = QStringLiteral("arm_across_back_center_to_elbow_bent")
const QString armAcrossBackCenterToWristBent_M = QStringLiteral("arm_across_back_center_to_wrist_bent")
const QString armArmscyeBackCenterToWristBent_M = QStringLiteral("arm_armscye_back_center_to_wrist_bent")
const QString neckBackToBustFront_M = QStringLiteral("neck_back_to_bust_front")
const QString neckBackToArmfoldFront_M = QStringLiteral("neck_back_to_armfold_front")
const QString neckBackToArmfoldFrontToWaistSide_M = QStringLiteral("neck_back_to_armfold_front_to_waist_side")
const QString highbustBackOverShoulderToArmfoldFront_M = QStringLiteral("highbust_back_over_shoulder_to_armfold_front")
const QString highbustBackOverShoulderToWaistFront_M = QStringLiteral("highbust_back_over_shoulder_to_waist_front")
const QString neckBackToArmfoldFrontToNeckBack_M = QStringLiteral("neck_back_to_armfold_front_to_neck_back")
const QString acrossBackCenterToArmfoldFrontToAcrossBackCenter_M = QStringLiteral("across_back_center_to_armfold_front_to_across_back_center")
const QString neckBackToArmfoldFrontToHighbustBack_M = QStringLiteral("neck_back_to_armfold_front_to_highbust_back")
const QString armfoldToArmfoldBust_M = QStringLiteral("armfold_to_armfold_bust")
const QString armfoldToBustFront_M = QStringLiteral("armfold_to_bust_front")
const QString highbustBOverShoulderToHighbustF_M = QStringLiteral("highbust_b_over_shoulder_to_highbust_f")
const QString armscyeArc_M = QStringLiteral("armscye_arc")
const QString dartWidthShoulder_M = QStringLiteral("dart_width_shoulder")
const QString dartWidthBust_M = QStringLiteral("dart_width_bust")
const QString dartWidthWaist_M = QStringLiteral("dart_width_waist")
Function Documentation
AllGroupNames()
QStringList AllGroupNames ()
Definition at line 1185 of file measurements_def.cpp.
References ListGroupA(), ListGroupB(), ListGroupC(), ListGroupD(), ListGroupE(), ListGroupF(), ListGroupG(), ListGroupH(), ListGroupI(), ListGroupJ(), ListGroupK(), ListGroupL(), ListGroupM(), ListGroupN(), ListGroupO(), ListGroupP(), and ListGroupQ().
Referenced by TST_MeasurementRegExp::AllNames(), MeasurementDoc::eachKnownNameIsValid(), and TST_NameRegExp::TestOriginalMeasurementNamesRegExp_data().
ListGroupA()
QStringList ListGroupA ()
Definition at line 334 of file measurements_def.cpp.
References height_M, heightAnkle_M, heightAnkleHigh_M, heightArmpit_M, heightBustpoint_M, heightCalf_M, heightGlutealFold_M, heightHighhip_M, heightHip_M, heightKnee_M, heightKneeToAnkle_M, heightNeckBack_M, heightNeckBackToKnee_M, heightNeckBackToWaistSide_M, heightNeckFront_M, heightNeckSide_M, heightScapula_M, heightShoulderTip_M, heightWaistBack_M, heightWaistFront_M, heightWaistSide_M, heightWaistSideToHip_M, and heightWaistSideToKnee_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupB()
QStringList ListGroupB ()
Definition at line 363 of file measurements_def.cpp.
References widthAbdomenToHip_M, widthBust_M, widthHip_M, widthShoulder_M, and widthWaist_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupC()
QStringList ListGroupC ()
Definition at line 375 of file measurements_def.cpp.
References indentAnkleHigh_M, indentNeckBack_M, and indentWaistBack_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupD()
QStringList ListGroupD ()
Definition at line 385 of file measurements_def.cpp.
References handCirc_M, handLength_M, handPalmCirc_M, handPalmLength_M, and handPalmWidth_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupE()
QStringList ListGroupE ()
Definition at line 397 of file measurements_def.cpp.
References footCirc_M, footInstepCirc_M, footLength_M, and footWidth_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupF()
QStringList ListGroupF ()
Definition at line 408 of file measurements_def.cpp.
References headChinToNeckBack_M, headCirc_M, headCrownToNeckBack_M, headDepth_M, headLength_M, and headWidth_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupG()
QStringList ListGroupG ()
Definition at line 421 of file measurements_def.cpp.
References bodyArmfoldCirc_M, bodyBustCirc_M, bodyTorsoCirc_M, bustArcB_M, bustArcF_M, bustArcHalfB_M, bustArcHalfF_M, bustCirc_M, highbustArcB_M, highbustArcF_M, highbustArcHalfB_M, highbustArcHalfF_M, highbustCirc_M, highhipArcB_M, highhipArcF_M, highhipArcHalfB_M, highhipArcHalfF_M, highhipCirc_M, hipArcB_M, hipArcF_M, hipArcHalfB_M, hipArcHalfF_M, hipCirc_M, hipCircWithAbdomen_M, hipWithAbdomenArcF_M, lowbustArcB_M, lowbustArcF_M, lowbustArcHalfB_M, lowbustArcHalfF_M, lowbustCirc_M, neckArcB_M, neckArcF_M, neckArcHalfB_M, neckArcHalfF_M, neckCirc_M, neckMidCirc_M, ribArcB_M, ribArcF_M, ribArcHalfB_M, ribArcHalfF_M, ribCirc_M, size_M, waistArcB_M, waistArcF_M, waistArcHalfB_M, waistArcHalfF_M, and waistCirc_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupH()
QStringList ListGroupH ()
Definition at line 475 of file measurements_def.cpp.
References acrossBackToWaistB_M, armpitToWaistSide_M, bustToWaistB_M, bustToWaistF_M, highbustToWaistB_M, highbustToWaistF_M, lowbustToWaistB_M, lowbustToWaistF_M, neckBackToAcrossBack_M, neckBackToBustB_M, neckBackToHighbustB_M, neckBackToWaistB_M, neckFrontToBustF_M, neckFrontToHighbustF_M, neckFrontToWaistF_M, neckFrontToWaistFlatF_M, neckSideToBustB_M, neckSideToBustF_M, neckSideToHighbustB_M, neckSideToHighbustF_M, neckSideToWaistB_M, neckSideToWaistBustpointF_M, neckSideToWaistF_M, neckSideToWaistScapulaB_M, ribToWaistSide_M, shoulderCenterToHighbustB_M, shoulderCenterToHighbustF_M, shoulderSlopeNeckBackAngle_M, shoulderSlopeNeckBackHeight_M, shoulderSlopeNeckSideAngle_M, shoulderSlopeNeckSideLength_M, shoulderSlopeShoulderTipAngle_M, shoulderTipToArmfoldB_M, shoulderTipToArmfoldF_M, shoulderTipToWaistSideB_M, shoulderTipToWaistSideF_M, waistToHighhipB_M, waistToHighhipF_M, waistToHighhipSide_M, waistToHipB_M, waistToHipF_M, and waistToHipSide_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupI()
QStringList ListGroupI ()
Definition at line 524 of file measurements_def.cpp.
References acrossBackB_M, acrossBackHalfB_M, acrossChestF_M, acrossChestHalfF_M, armfoldToArmfoldB_M, armfoldToArmfoldF_M, neckBackToShoulderTipB_M, neckFrontToShoulderTipF_M, neckWidth_M, shoulderLength_M, shoulderTipToShoulderTipB_M, shoulderTipToShoulderTipF_M, shoulderTipToShoulderTipHalfB_M, and shoulderTipToShoulderTipHalfF_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupJ()
QStringList ListGroupJ ()
Definition at line 545 of file measurements_def.cpp.
References bustpointNeckSideToWaist_M, bustpointToBustpoint_M, bustpointToBustpointHalf_M, bustpointToBustpointHalter_M, bustpointToLowbust_M, bustpointToNeckFront_M, bustpointToNeckSide_M, bustpointToShoulderCenter_M, bustpointToShoulderTip_M, bustpointToWaist_M, and bustpointToWaistFront_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupK()
QStringList ListGroupK ()
Definition at line 562 of file measurements_def.cpp.
References neckBackToWaistSide_M, neckFrontToWaistSide_M, neckSideToArmfoldB_M, neckSideToArmfoldF_M, neckSideToArmpitB_M, neckSideToArmpitF_M, neckSideToBustSideB_M, neckSideToBustSideF_M, neckSideToWaistSideB_M, neckSideToWaistSideF_M, shoulderTipToWaistB_1inOffset_M, shoulderTipToWaistBack_M, and shoulderTipToWaistFront_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupL()
QStringList ListGroupL ()
Definition at line 582 of file measurements_def.cpp.
References armAboveElbowCirc_M, armArmpitToElbow_M, armArmpitToWrist_M, armElbowCirc_M, armElbowCircBent_M, armElbowToWrist_M, armElbowToWristBent_M, armElbowToWristInside_M, armLowerCirc_M, armNeckSideToFingerTip_M, armNeckSideToOuterElbow_M, armNeckSideToWrist_M, armscyeCirc_M, armscyeLength_M, armscyeWidth_M, armShoulderTipToArmfoldLine_M, armShoulderTipToElbow_M, armShoulderTipToElbowBent_M, armShoulderTipToWrist_M, armShoulderTipToWristBent_M, armUpperCirc_M, and armWristCirc_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupM()
QStringList ListGroupM ()
Definition at line 611 of file measurements_def.cpp.
References legAnkleCirc_M, legAnkleDiagCirc_M, legAnkleHighCirc_M, legCalfCirc_M, legCrotchToAnkle_M, legCrotchToFloor_M, legKneeCirc_M, legKneeCircBent_M, legKneeSmallCirc_M, legThighMidCirc_M, legThighUpperCirc_M, legWaistSideToAnkle_M, legWaistSideToFloor_M, and legWaistSideToKnee_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupN()
QStringList ListGroupN ()
Definition at line 632 of file measurements_def.cpp.
References crotchLength_M, crotchLengthB_M, crotchLengthF_M, riseLengthB_M, riseLengthDiag_M, riseLengthF_M, riseLengthSide_M, and riseLengthSideSitting_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupO()
QStringList ListGroupO ()
Definition at line 647 of file measurements_def.cpp.
References armAcrossBackCenterToElbowBent_M, armAcrossBackCenterToWristBent_M, armArmscyeBackCenterToWristBent_M, armNeckBackToElbowBent_M, armNeckBackToWristBent_M, armNeckSideToElbowBent_M, armNeckSideToWristBent_M, neckBackToWaistFront_M, waistNaturalArcB_M, waistNaturalArcF_M, waistNaturalCirc_M, waistToNaturalWaistB_M, waistToNaturalWaistF_M, and waistToWaistHalter_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupP()
QStringList ListGroupP ()
Definition at line 668 of file measurements_def.cpp.
References acrossBackCenterToArmfoldFrontToAcrossBackCenter_M, armfoldToArmfoldBust_M, armfoldToBustFront_M, armscyeArc_M, highbustBackOverShoulderToArmfoldFront_M, highbustBackOverShoulderToWaistFront_M, highbustBOverShoulderToHighbustF_M, neckBackToArmfoldFront_M, neckBackToArmfoldFrontToHighbustBack_M, neckBackToArmfoldFrontToNeckBack_M, neckBackToArmfoldFrontToWaistSide_M, and neckBackToBustFront_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListGroupQ()
QStringList ListGroupQ ()
Definition at line 687 of file measurements_def.cpp.
References dartWidthBust_M, dartWidthShoulder_M, and dartWidthWaist_M.
Referenced by AllGroupNames(), MeasurementDatabaseDialog::initDataBase(), MapDiagrams(), and MeasurementDatabaseDialog::retranslateGroups().
ListNumbers()
QStringList ListNumbers (const VTranslateMeasurements * trM, const QStringList & listMeasurements)
Definition at line 697 of file measurements_def.cpp.
References VTranslateMeasurements::MNumber(), and SCASSERT.
Referenced by MapDiagrams().
MapDiagrams()
QString MapDiagrams (const VTranslateMeasurements * trM, const QString & number)
Definition at line 710 of file measurements_def.cpp.
References ListGroupA(), ListGroupB(), ListGroupC(), ListGroupD(), ListGroupE(), ListGroupF(), ListGroupG(), ListGroupH(), ListGroupI(), ListGroupJ(), ListGroupK(), ListGroupL(), ListGroupM(), ListGroupN(), ListGroupO(), ListGroupP(), ListGroupQ(), and ListNumbers().
Referenced by MeasurementDatabaseDialog::imageUrl().
Variable Documentation
acrossBackB_M
const QString acrossBackB_M = QStringLiteral("across_back_b")
Definition at line 216 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
acrossBackCenterToArmfoldFrontToAcrossBackCenter_M
const QString acrossBackCenterToArmfoldFrontToAcrossBackCenter_M = QStringLiteral("across_back_center_to_armfold_front_to_across_back_center")
Definition at line 320 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
acrossBackHalfB_M
const QString acrossBackHalfB_M = QStringLiteral("across_back_half_b")
Definition at line 219 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
acrossBackToWaistB_M
const QString acrossBackToWaistB_M = QStringLiteral("across_back_to_waist_b")
Definition at line 207 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
acrossChestF_M
const QString acrossChestF_M = QStringLiteral("across_chest_f")
Definition at line 211 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
acrossChestHalfF_M
const QString acrossChestHalfF_M = QStringLiteral("across_chest_half_f")
Definition at line 214 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armAboveElbowCirc_M
const QString armAboveElbowCirc_M = QStringLiteral("arm_above_elbow_circ")
Definition at line 261 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armAcrossBackCenterToElbowBent_M
const QString armAcrossBackCenterToElbowBent_M = QStringLiteral("arm_across_back_center_to_elbow_bent")
Definition at line 308 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armAcrossBackCenterToWristBent_M
const QString armAcrossBackCenterToWristBent_M = QStringLiteral("arm_across_back_center_to_wrist_bent")
Definition at line 309 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armArmpitToElbow_M
const QString armArmpitToElbow_M = QStringLiteral("arm_armpit_to_elbow")
Definition at line 258 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armArmpitToWrist_M
const QString armArmpitToWrist_M = QStringLiteral("arm_armpit_to_wrist")
Definition at line 257 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armArmscyeBackCenterToWristBent_M
const QString armArmscyeBackCenterToWristBent_M = QStringLiteral("arm_armscye_back_center_to_wrist_bent")
Definition at line 310 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armElbowCirc_M
const QString armElbowCirc_M = QStringLiteral("arm_elbow_circ")
Definition at line 262 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armElbowCircBent_M
const QString armElbowCircBent_M = QStringLiteral("arm_elbow_circ_bent")
Definition at line 253 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armElbowToWrist_M
const QString armElbowToWrist_M = QStringLiteral("arm_elbow_to_wrist")
Definition at line 256 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armElbowToWristBent_M
const QString armElbowToWristBent_M = QStringLiteral("arm_elbow_to_wrist_bent")
Definition at line 252 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armElbowToWristInside_M
const QString armElbowToWristInside_M = QStringLiteral("arm_elbow_to_wrist_inside")
Definition at line 259 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armfoldToArmfoldB_M
const QString armfoldToArmfoldB_M = QStringLiteral("armfold_to_armfold_b")
Definition at line 217 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armfoldToArmfoldBust_M
const QString armfoldToArmfoldBust_M = QStringLiteral("armfold_to_armfold_bust")
Definition at line 324 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armfoldToArmfoldF_M
const QString armfoldToArmfoldF_M = QStringLiteral("armfold_to_armfold_f")
Definition at line 212 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armfoldToBustFront_M
const QString armfoldToBustFront_M = QStringLiteral("armfold_to_bust_front")
Definition at line 325 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armLowerCirc_M
const QString armLowerCirc_M = QStringLiteral("arm_lower_circ")
Definition at line 263 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armNeckBackToElbowBent_M
const QString armNeckBackToElbowBent_M = QStringLiteral("arm_neck_back_to_elbow_bent")
Definition at line 304 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armNeckBackToWristBent_M
const QString armNeckBackToWristBent_M = QStringLiteral("arm_neck_back_to_wrist_bent")
Definition at line 305 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armNeckSideToElbowBent_M
const QString armNeckSideToElbowBent_M = QStringLiteral("arm_neck_side_to_elbow_bent")
Definition at line 306 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armNeckSideToFingerTip_M
const QString armNeckSideToFingerTip_M = QStringLiteral("arm_neck_side_to_finger_tip")
Definition at line 267 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armNeckSideToOuterElbow_M
const QString armNeckSideToOuterElbow_M = QStringLiteral("arm_neck_side_to_outer_elbow")
Definition at line 271 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armNeckSideToWrist_M
const QString armNeckSideToWrist_M = QStringLiteral("arm_neck_side_to_wrist")
Definition at line 266 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armNeckSideToWristBent_M
const QString armNeckSideToWristBent_M = QStringLiteral("arm_neck_side_to_wrist_bent")
Definition at line 307 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armpitToWaistSide_M
const QString armpitToWaistSide_M = QStringLiteral("armpit_to_waist_side")
Definition at line 168 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armscyeArc_M
const QString armscyeArc_M = QStringLiteral("armscye_arc")
Definition at line 327 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armscyeCirc_M
const QString armscyeCirc_M = QStringLiteral("armscye_circ")
Definition at line 268 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armscyeLength_M
const QString armscyeLength_M = QStringLiteral("armscye_length")
Definition at line 269 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armscyeWidth_M
const QString armscyeWidth_M = QStringLiteral("armscye_width")
Definition at line 270 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armShoulderTipToArmfoldLine_M
const QString armShoulderTipToArmfoldLine_M = QStringLiteral("arm_shoulder_tip_to_armfold_line")
Definition at line 265 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armShoulderTipToElbow_M
const QString armShoulderTipToElbow_M = QStringLiteral("arm_shoulder_tip_to_elbow")
Definition at line 255 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armShoulderTipToElbowBent_M
const QString armShoulderTipToElbowBent_M = QStringLiteral("arm_shoulder_tip_to_elbow_bent")
Definition at line 251 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armShoulderTipToWrist_M
const QString armShoulderTipToWrist_M = QStringLiteral("arm_shoulder_tip_to_wrist")
Definition at line 254 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armShoulderTipToWristBent_M
const QString armShoulderTipToWristBent_M = QStringLiteral("arm_shoulder_tip_to_wrist_bent")
Definition at line 250 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armUpperCirc_M
const QString armUpperCirc_M = QStringLiteral("arm_upper_circ")
Definition at line 260 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
armWristCirc_M
const QString armWristCirc_M = QStringLiteral("arm_wrist_circ")
Definition at line 264 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupL(), ListGroupL(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bodyArmfoldCirc_M
const QString bodyArmfoldCirc_M = QStringLiteral("body_armfold_circ")
Definition at line 161 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bodyBustCirc_M
const QString bodyBustCirc_M = QStringLiteral("body_bust_circ")
Definition at line 162 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bodyTorsoCirc_M
const QString bodyTorsoCirc_M = QStringLiteral("body_torso_circ")
Definition at line 163 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustArcB_M
const QString bustArcB_M = QStringLiteral("bust_arc_b")
Definition at line 146 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustArcF_M
const QString bustArcF_M = QStringLiteral("bust_arc_f")
Definition at line 129 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustArcHalfB_M
const QString bustArcHalfB_M = QStringLiteral("bust_arc_half_b")
Definition at line 154 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustArcHalfF_M
const QString bustArcHalfF_M = QStringLiteral("bust_arc_half_f")
Definition at line 138 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustCirc_M
const QString bustCirc_M = QStringLiteral("bust_circ")
Definition at line 118 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointNeckSideToWaist_M
const QString bustpointNeckSideToWaist_M = QStringLiteral("bustpoint_neck_side_to_waist")
Definition at line 229 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToBustpoint_M
const QString bustpointToBustpoint_M = QStringLiteral("bustpoint_to_bustpoint")
Definition at line 224 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToBustpointHalf_M
const QString bustpointToBustpointHalf_M = QStringLiteral("bustpoint_to_bustpoint_half")
Definition at line 228 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToBustpointHalter_M
const QString bustpointToBustpointHalter_M = QStringLiteral("bustpoint_to_bustpoint_halter")
Definition at line 232 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToLowbust_M
const QString bustpointToLowbust_M = QStringLiteral("bustpoint_to_lowbust")
Definition at line 226 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToNeckFront_M
const QString bustpointToNeckFront_M = QStringLiteral("bustpoint_to_neck_front")
Definition at line 234 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToNeckSide_M
const QString bustpointToNeckSide_M = QStringLiteral("bustpoint_to_neck_side")
Definition at line 225 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToShoulderCenter_M
const QString bustpointToShoulderCenter_M = QStringLiteral("bustpoint_to_shoulder_center")
Definition at line 233 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToShoulderTip_M
const QString bustpointToShoulderTip_M = QStringLiteral("bustpoint_to_shoulder_tip")
Definition at line 230 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToWaist_M
const QString bustpointToWaist_M = QStringLiteral("bustpoint_to_waist")
Definition at line 227 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustpointToWaistFront_M
const QString bustpointToWaistFront_M = QStringLiteral("bustpoint_to_waist_front")
Definition at line 231 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupJ(), ListGroupJ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustToWaistB_M
const QString bustToWaistB_M = QStringLiteral("bust_to_waist_b")
Definition at line 189 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
bustToWaistF_M
const QString bustToWaistF_M = QStringLiteral("bust_to_waist_f")
Definition at line 175 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
crotchLength_M
const QString crotchLength_M = QStringLiteral("crotch_length")
Definition at line 288 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupN(), ListGroupN(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
crotchLengthB_M
const QString crotchLengthB_M = QStringLiteral("crotch_length_b")
Definition at line 289 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupN(), ListGroupN(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
crotchLengthF_M
const QString crotchLengthF_M = QStringLiteral("crotch_length_f")
Definition at line 290 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupN(), ListGroupN(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
dartWidthBust_M
const QString dartWidthBust_M = QStringLiteral("dart_width_bust")
Definition at line 330 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupQ(), ListGroupQ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
dartWidthShoulder_M
const QString dartWidthShoulder_M = QStringLiteral("dart_width_shoulder")
Definition at line 329 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupQ(), ListGroupQ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
dartWidthWaist_M
const QString dartWidthWaist_M = QStringLiteral("dart_width_waist")
Definition at line 331 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupQ(), ListGroupQ(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
footCirc_M
const QString footCirc_M = QStringLiteral("foot_circ")
Definition at line 105 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupE(), ListGroupE(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
footInstepCirc_M
const QString footInstepCirc_M = QStringLiteral("foot_instep_circ")
Definition at line 106 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupE(), ListGroupE(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
footLength_M
const QString footLength_M = QStringLiteral("foot_length")
Definition at line 104 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupE(), ListGroupE(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
footWidth_M
const QString footWidth_M = QStringLiteral("foot_width")
Definition at line 103 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupE(), ListGroupE(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
handCirc_M
const QString handCirc_M = QStringLiteral("hand_circ")
Definition at line 101 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupD(), ListGroupD(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
handLength_M
const QString handLength_M = QStringLiteral("hand_length")
Definition at line 98 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupD(), ListGroupD(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
handPalmCirc_M
const QString handPalmCirc_M = QStringLiteral("hand_palm_circ")
Definition at line 100 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupD(), ListGroupD(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
handPalmLength_M
const QString handPalmLength_M = QStringLiteral("hand_palm_length")
Definition at line 97 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupD(), ListGroupD(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
handPalmWidth_M
const QString handPalmWidth_M = QStringLiteral("hand_palm_width")
Definition at line 99 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupD(), ListGroupD(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
headChinToNeckBack_M
const QString headChinToNeckBack_M = QStringLiteral("head_chin_to_neck_back")
Definition at line 113 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupF(), ListGroupF(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
headCirc_M
const QString headCirc_M = QStringLiteral("head_circ")
Definition at line 108 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupF(), ListGroupF(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
headCrownToNeckBack_M
const QString headCrownToNeckBack_M = QStringLiteral("head_crown_to_neck_back")
Definition at line 112 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupF(), ListGroupF(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
headDepth_M
const QString headDepth_M = QStringLiteral("head_depth")
Definition at line 110 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupF(), ListGroupF(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
headLength_M
const QString headLength_M = QStringLiteral("head_length")
Definition at line 109 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupF(), ListGroupF(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
headWidth_M
const QString headWidth_M = QStringLiteral("head_width")
Definition at line 111 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupF(), ListGroupF(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
height_M
const QString height_M = QStringLiteral("height")
Definition at line 63 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), MainWindowsNoGUI::setSizeHeightForIndividualM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightAnkle_M
const QString heightAnkle_M = QStringLiteral("height_ankle")
Definition at line 73 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightAnkleHigh_M
const QString heightAnkleHigh_M = QStringLiteral("height_ankle_high")
Definition at line 72 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightArmpit_M
const QString heightArmpit_M = QStringLiteral("height_armpit")
Definition at line 66 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightBustpoint_M
const QString heightBustpoint_M = QStringLiteral("height_bustpoint")
Definition at line 76 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightCalf_M
const QString heightCalf_M = QStringLiteral("height_calf")
Definition at line 71 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightGlutealFold_M
const QString heightGlutealFold_M = QStringLiteral("height_gluteal_fold")
Definition at line 69 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightHighhip_M
const QString heightHighhip_M = QStringLiteral("height_highhip")
Definition at line 74 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightHip_M
const QString heightHip_M = QStringLiteral("height_hip")
Definition at line 68 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightKnee_M
const QString heightKnee_M = QStringLiteral("height_knee")
Definition at line 70 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightKneeToAnkle_M
const QString heightKneeToAnkle_M = QStringLiteral("height_knee_to_ankle")
Definition at line 83 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightNeckBack_M
const QString heightNeckBack_M = QStringLiteral("height_neck_back")
Definition at line 64 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightNeckBackToKnee_M
const QString heightNeckBackToKnee_M = QStringLiteral("height_neck_back_to_knee")
Definition at line 80 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightNeckBackToWaistSide_M
const QString heightNeckBackToWaistSide_M = QStringLiteral("height_neck_back_to_waist_side")
Definition at line 84 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightNeckFront_M
const QString heightNeckFront_M = QStringLiteral("height_neck_front")
Definition at line 78 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightNeckSide_M
const QString heightNeckSide_M = QStringLiteral("height_neck_side")
Definition at line 79 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightScapula_M
const QString heightScapula_M = QStringLiteral("height_scapula")
Definition at line 65 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightShoulderTip_M
const QString heightShoulderTip_M = QStringLiteral("height_shoulder_tip")
Definition at line 77 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightWaistBack_M
const QString heightWaistBack_M = QStringLiteral("height_waist_back")
Definition at line 85 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightWaistFront_M
const QString heightWaistFront_M = QStringLiteral("height_waist_front")
Definition at line 75 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightWaistSide_M
const QString heightWaistSide_M = QStringLiteral("height_waist_side")
Definition at line 67 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightWaistSideToHip_M
const QString heightWaistSideToHip_M = QStringLiteral("height_waist_side_to_hip")
Definition at line 82 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
heightWaistSideToKnee_M
const QString heightWaistSideToKnee_M = QStringLiteral("height_waist_side_to_knee")
Definition at line 81 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupA(), ListGroupA(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustArcB_M
const QString highbustArcB_M = QStringLiteral("highbust_arc_b")
Definition at line 145 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustArcF_M
const QString highbustArcF_M = QStringLiteral("highbust_arc_f")
Definition at line 125 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustArcHalfB_M
const QString highbustArcHalfB_M = QStringLiteral("highbust_arc_half_b")
Definition at line 153 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustArcHalfF_M
const QString highbustArcHalfF_M = QStringLiteral("highbust_arc_half_f")
Definition at line 137 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustBackOverShoulderToArmfoldFront_M
const QString highbustBackOverShoulderToArmfoldFront_M = QStringLiteral("highbust_back_over_shoulder_to_armfold_front")
Definition at line 315 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustBackOverShoulderToWaistFront_M
const QString highbustBackOverShoulderToWaistFront_M = QStringLiteral("highbust_back_over_shoulder_to_waist_front")
Definition at line 317 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustBOverShoulderToHighbustF_M
const QString highbustBOverShoulderToHighbustF_M = QStringLiteral("highbust_b_over_shoulder_to_highbust_f")
Definition at line 326 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustCirc_M
const QString highbustCirc_M = QStringLiteral("highbust_circ")
Definition at line 117 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustToWaistB_M
const QString highbustToWaistB_M = QStringLiteral("highbust_to_waist_b")
Definition at line 187 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highbustToWaistF_M
const QString highbustToWaistF_M = QStringLiteral("highbust_to_waist_f")
Definition at line 173 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highhipArcB_M
const QString highhipArcB_M = QStringLiteral("highhip_arc_b")
Definition at line 150 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highhipArcF_M
const QString highhipArcF_M = QStringLiteral("highhip_arc_f")
Definition at line 134 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highhipArcHalfB_M
const QString highhipArcHalfB_M = QStringLiteral("highhip_arc_half_b")
Definition at line 158 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highhipArcHalfF_M
const QString highhipArcHalfF_M = QStringLiteral("highhip_arc_half_f")
Definition at line 142 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
highhipCirc_M
const QString highhipCirc_M = QStringLiteral("highhip_circ")
Definition at line 122 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
hipArcB_M
const QString hipArcB_M = QStringLiteral("hip_arc_b")
Definition at line 151 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
hipArcF_M
const QString hipArcF_M = QStringLiteral("hip_arc_f")
Definition at line 135 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
hipArcHalfB_M
const QString hipArcHalfB_M = QStringLiteral("hip_arc_half_b")
Definition at line 159 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
hipArcHalfF_M
const QString hipArcHalfF_M = QStringLiteral("hip_arc_half_f")
Definition at line 143 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
hipCirc_M
const QString hipCirc_M = QStringLiteral("hip_circ")
Definition at line 123 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
hipCircWithAbdomen_M
const QString hipCircWithAbdomen_M = QStringLiteral("hip_circ_with_abdomen")
Definition at line 164 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
hipWithAbdomenArcF_M
const QString hipWithAbdomenArcF_M = QStringLiteral("hip_with_abdomen_arc_f")
Definition at line 160 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
indentAnkleHigh_M
const QString indentAnkleHigh_M = QStringLiteral("indent_ankle_high")
Definition at line 95 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupC(), ListGroupC(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
indentNeckBack_M
const QString indentNeckBack_M = QStringLiteral("indent_neck_back")
Definition at line 93 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupC(), ListGroupC(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
indentWaistBack_M
const QString indentWaistBack_M = QStringLiteral("indent_waist_back")
Definition at line 94 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupC(), ListGroupC(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legAnkleCirc_M
const QString legAnkleCirc_M = QStringLiteral("leg_ankle_circ")
Definition at line 281 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legAnkleDiagCirc_M
const QString legAnkleDiagCirc_M = QStringLiteral("leg_ankle_diag_circ")
Definition at line 283 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legAnkleHighCirc_M
const QString legAnkleHighCirc_M = QStringLiteral("leg_ankle_high_circ")
Definition at line 280 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legCalfCirc_M
const QString legCalfCirc_M = QStringLiteral("leg_calf_circ")
Definition at line 279 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legCrotchToAnkle_M
const QString legCrotchToAnkle_M = QStringLiteral("leg_crotch_to_ankle")
Definition at line 284 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legCrotchToFloor_M
const QString legCrotchToFloor_M = QStringLiteral("leg_crotch_to_floor")
Definition at line 273 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legKneeCirc_M
const QString legKneeCirc_M = QStringLiteral("leg_knee_circ")
Definition at line 277 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legKneeCircBent_M
const QString legKneeCircBent_M = QStringLiteral("leg_knee_circ_bent")
Definition at line 282 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legKneeSmallCirc_M
const QString legKneeSmallCirc_M = QStringLiteral("leg_knee_small_circ")
Definition at line 278 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legThighMidCirc_M
const QString legThighMidCirc_M = QStringLiteral("leg_thigh_mid_circ")
Definition at line 276 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legThighUpperCirc_M
const QString legThighUpperCirc_M = QStringLiteral("leg_thigh_upper_circ")
Definition at line 275 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legWaistSideToAnkle_M
const QString legWaistSideToAnkle_M = QStringLiteral("leg_waist_side_to_ankle")
Definition at line 285 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legWaistSideToFloor_M
const QString legWaistSideToFloor_M = QStringLiteral("leg_waist_side_to_floor")
Definition at line 274 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
legWaistSideToKnee_M
const QString legWaistSideToKnee_M = QStringLiteral("leg_waist_side_to_knee")
Definition at line 286 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupM(), ListGroupM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
lowbustArcB_M
const QString lowbustArcB_M = QStringLiteral("lowbust_arc_b")
Definition at line 147 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
lowbustArcF_M
const QString lowbustArcF_M = QStringLiteral("lowbust_arc_f")
Definition at line 131 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
lowbustArcHalfB_M
const QString lowbustArcHalfB_M = QStringLiteral("lowbust_arc_half_b")
Definition at line 155 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
lowbustArcHalfF_M
const QString lowbustArcHalfF_M = QStringLiteral("lowbust_arc_half_f")
Definition at line 139 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
lowbustCirc_M
const QString lowbustCirc_M = QStringLiteral("lowbust_circ")
Definition at line 119 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
lowbustToWaistB_M
const QString lowbustToWaistB_M = QStringLiteral("lowbust_to_waist_b")
Definition at line 190 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
lowbustToWaistF_M
const QString lowbustToWaistF_M = QStringLiteral("lowbust_to_waist_f")
Definition at line 176 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckArcB_M
const QString neckArcB_M = QStringLiteral("neck_arc_b")
Definition at line 144 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckArcF_M
const QString neckArcF_M = QStringLiteral("neck_arc_f")
Definition at line 124 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckArcHalfB_M
const QString neckArcHalfB_M = QStringLiteral("neck_arc_half_b")
Definition at line 152 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckArcHalfF_M
const QString neckArcHalfF_M = QStringLiteral("neck_arc_half_f")
Definition at line 136 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToAcrossBack_M
const QString neckBackToAcrossBack_M = QStringLiteral("neck_back_to_across_back")
Definition at line 206 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToArmfoldFront_M
const QString neckBackToArmfoldFront_M = QStringLiteral("neck_back_to_armfold_front")
Definition at line 313 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToArmfoldFrontToHighbustBack_M
const QString neckBackToArmfoldFrontToHighbustBack_M = QStringLiteral("neck_back_to_armfold_front_to_highbust_back")
Definition at line 322 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToArmfoldFrontToNeckBack_M
const QString neckBackToArmfoldFrontToNeckBack_M = QStringLiteral("neck_back_to_armfold_front_to_neck_back")
Definition at line 319 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToArmfoldFrontToWaistSide_M
const QString neckBackToArmfoldFrontToWaistSide_M = QStringLiteral("neck_back_to_armfold_front_to_waist_side")
Definition at line 314 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToBustB_M
const QString neckBackToBustB_M = QStringLiteral("neck_back_to_bust_b")
Definition at line 188 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToBustFront_M
const QString neckBackToBustFront_M = QStringLiteral("neck_back_to_bust_front")
Definition at line 312 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupP(), ListGroupP(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToHighbustB_M
const QString neckBackToHighbustB_M = QStringLiteral("neck_back_to_highbust_b")
Definition at line 186 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToShoulderTipB_M
const QString neckBackToShoulderTipB_M = QStringLiteral("neck_back_to_shoulder_tip_b")
Definition at line 221 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToWaistB_M
const QString neckBackToWaistB_M = QStringLiteral("neck_back_to_waist_b")
Definition at line 184 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToWaistFront_M
const QString neckBackToWaistFront_M = QStringLiteral("neck_back_to_waist_front")
Definition at line 297 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckBackToWaistSide_M
const QString neckBackToWaistSide_M = QStringLiteral("neck_back_to_waist_side")
Definition at line 241 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckCirc_M
const QString neckCirc_M = QStringLiteral("neck_circ")
Definition at line 116 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckFrontToBustF_M
const QString neckFrontToBustF_M = QStringLiteral("neck_front_to_bust_f")
Definition at line 174 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckFrontToHighbustF_M
const QString neckFrontToHighbustF_M = QStringLiteral("neck_front_to_highbust_f")
Definition at line 172 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckFrontToShoulderTipF_M
const QString neckFrontToShoulderTipF_M = QStringLiteral("neck_front_to_shoulder_tip_f")
Definition at line 220 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckFrontToWaistF_M
const QString neckFrontToWaistF_M = QStringLiteral("neck_front_to_waist_f")
Definition at line 166 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckFrontToWaistFlatF_M
const QString neckFrontToWaistFlatF_M = QStringLiteral("neck_front_to_waist_flat_f")
Definition at line 167 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckFrontToWaistSide_M
const QString neckFrontToWaistSide_M = QStringLiteral("neck_front_to_waist_side")
Definition at line 237 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckMidCirc_M
const QString neckMidCirc_M = QStringLiteral("neck_mid_circ")
Definition at line 115 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToArmfoldB_M
const QString neckSideToArmfoldB_M = QStringLiteral("neck_side_to_armfold_b")
Definition at line 246 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToArmfoldF_M
const QString neckSideToArmfoldF_M = QStringLiteral("neck_side_to_armfold_f")
Definition at line 243 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToArmpitB_M
const QString neckSideToArmpitB_M = QStringLiteral("neck_side_to_armpit_b")
Definition at line 247 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToArmpitF_M
const QString neckSideToArmpitF_M = QStringLiteral("neck_side_to_armpit_f")
Definition at line 244 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToBustB_M
const QString neckSideToBustB_M = QStringLiteral("neck_side_to_bust_b")
Definition at line 192 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToBustF_M
const QString neckSideToBustF_M = QStringLiteral("neck_side_to_bust_f")
Definition at line 179 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToBustSideB_M
const QString neckSideToBustSideB_M = QStringLiteral("neck_side_to_bust_side_b")
Definition at line 248 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToBustSideF_M
const QString neckSideToBustSideF_M = QStringLiteral("neck_side_to_bust_side_f")
Definition at line 245 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToHighbustB_M
const QString neckSideToHighbustB_M = QStringLiteral("neck_side_to_highbust_b")
Definition at line 193 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToHighbustF_M
const QString neckSideToHighbustF_M = QStringLiteral("neck_side_to_highbust_f")
Definition at line 180 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToWaistB_M
const QString neckSideToWaistB_M = QStringLiteral("neck_side_to_waist_b")
Definition at line 183 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToWaistBustpointF_M
const QString neckSideToWaistBustpointF_M = QStringLiteral("neck_side_to_waist_bustpoint_f")
Definition at line 171 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToWaistF_M
const QString neckSideToWaistF_M = QStringLiteral("neck_side_to_waist_f")
Definition at line 170 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToWaistScapulaB_M
const QString neckSideToWaistScapulaB_M = QStringLiteral("neck_side_to_waist_scapula_b")
Definition at line 185 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToWaistSideB_M
const QString neckSideToWaistSideB_M = QStringLiteral("neck_side_to_waist_side_b")
Definition at line 242 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckSideToWaistSideF_M
const QString neckSideToWaistSideF_M = QStringLiteral("neck_side_to_waist_side_f")
Definition at line 238 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
neckWidth_M
const QString neckWidth_M = QStringLiteral("neck_width")
Definition at line 222 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
ribArcB_M
const QString ribArcB_M = QStringLiteral("rib_arc_b")
Definition at line 148 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
ribArcF_M
const QString ribArcF_M = QStringLiteral("rib_arc_f")
Definition at line 132 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
ribArcHalfB_M
const QString ribArcHalfB_M = QStringLiteral("rib_arc_half_b")
Definition at line 156 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
ribArcHalfF_M
const QString ribArcHalfF_M = QStringLiteral("rib_arc_half_f")
Definition at line 140 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
ribCirc_M
const QString ribCirc_M = QStringLiteral("rib_circ")
Definition at line 120 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
ribToWaistSide_M
const QString ribToWaistSide_M = QStringLiteral("rib_to_waist_side")
Definition at line 177 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
riseLengthB_M
const QString riseLengthB_M = QStringLiteral("rise_length_b")
Definition at line 293 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupN(), ListGroupN(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
riseLengthDiag_M
const QString riseLengthDiag_M = QStringLiteral("rise_length_diag")
Definition at line 292 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupN(), ListGroupN(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
riseLengthF_M
const QString riseLengthF_M = QStringLiteral("rise_length_f")
Definition at line 294 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupN(), ListGroupN(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
riseLengthSide_M
const QString riseLengthSide_M = QStringLiteral("rise_length_side")
Definition at line 295 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupN(), ListGroupN(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
riseLengthSideSitting_M
const QString riseLengthSideSitting_M = QStringLiteral("rise_length_side_sitting")
Definition at line 291 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupN(), ListGroupN(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderCenterToHighbustB_M
const QString shoulderCenterToHighbustB_M = QStringLiteral("shoulder_center_to_highbust_b")
Definition at line 194 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderCenterToHighbustF_M
const QString shoulderCenterToHighbustF_M = QStringLiteral("shoulder_center_to_highbust_f")
Definition at line 181 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderLength_M
const QString shoulderLength_M = QStringLiteral("shoulder_length")
Definition at line 209 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderSlopeNeckBackAngle_M
const QString shoulderSlopeNeckBackAngle_M = QStringLiteral("shoulder_slope_neck_back_angle")
Definition at line 203 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderSlopeNeckBackHeight_M
const QString shoulderSlopeNeckBackHeight_M = QStringLiteral("shoulder_slope_neck_back_height")
Definition at line 204 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderSlopeNeckSideAngle_M
const QString shoulderSlopeNeckSideAngle_M = QStringLiteral("shoulder_slope_neck_side_angle")
Definition at line 201 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderSlopeNeckSideLength_M
const QString shoulderSlopeNeckSideLength_M = QStringLiteral("shoulder_slope_neck_side_length")
Definition at line 202 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderSlopeShoulderTipAngle_M
const QString shoulderSlopeShoulderTipAngle_M = QStringLiteral("shoulder_slope_shoulder_tip_angle")
Definition at line 205 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToArmfoldB_M
const QString shoulderTipToArmfoldB_M = QStringLiteral("shoulder_tip_to_armfold_b")
Definition at line 191 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToArmfoldF_M
const QString shoulderTipToArmfoldF_M = QStringLiteral("shoulder_tip_to_armfold_f")
Definition at line 178 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToShoulderTipB_M
const QString shoulderTipToShoulderTipB_M = QStringLiteral("shoulder_tip_to_shoulder_tip_b")
Definition at line 215 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToShoulderTipF_M
const QString shoulderTipToShoulderTipF_M = QStringLiteral("shoulder_tip_to_shoulder_tip_f")
Definition at line 210 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToShoulderTipHalfB_M
const QString shoulderTipToShoulderTipHalfB_M = QStringLiteral("shoulder_tip_to_shoulder_tip_half_b")
Definition at line 218 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToShoulderTipHalfF_M
const QString shoulderTipToShoulderTipHalfF_M = QStringLiteral("shoulder_tip_to_shoulder_tip_half_f")
Definition at line 213 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupI(), ListGroupI(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToWaistB_1inOffset_M
const QString shoulderTipToWaistB_1inOffset_M = QStringLiteral("shoulder_tip_to_waist_b_1in_offset")
Definition at line 240 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToWaistBack_M
const QString shoulderTipToWaistBack_M = QStringLiteral("shoulder_tip_to_waist_back")
Definition at line 239 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToWaistFront_M
const QString shoulderTipToWaistFront_M = QStringLiteral("shoulder_tip_to_waist_front")
Definition at line 236 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupK(), ListGroupK(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToWaistSideB_M
const QString shoulderTipToWaistSideB_M = QStringLiteral("shoulder_tip_to_waist_side_b")
Definition at line 182 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
shoulderTipToWaistSideF_M
const QString shoulderTipToWaistSideF_M = QStringLiteral("shoulder_tip_to_waist_side_f")
Definition at line 169 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
size_M
const QString size_M = QStringLiteral("size")
Definition at line 128 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), MainWindowsNoGUI::setSizeHeightForIndividualM(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistArcB_M
const QString waistArcB_M = QStringLiteral("waist_arc_b")
Definition at line 149 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistArcF_M
const QString waistArcF_M = QStringLiteral("waist_arc_f")
Definition at line 133 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistArcHalfB_M
const QString waistArcHalfB_M = QStringLiteral("waist_arc_half_b")
Definition at line 157 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistArcHalfF_M
const QString waistArcHalfF_M = QStringLiteral("waist_arc_half_f")
Definition at line 141 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistCirc_M
const QString waistCirc_M = QStringLiteral("waist_circ")
Definition at line 121 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupG(), ListGroupG(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistNaturalArcB_M
const QString waistNaturalArcB_M = QStringLiteral("waist_natural_arc_b")
Definition at line 301 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistNaturalArcF_M
const QString waistNaturalArcF_M = QStringLiteral("waist_natural_arc_f")
Definition at line 300 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistNaturalCirc_M
const QString waistNaturalCirc_M = QStringLiteral("waist_natural_circ")
Definition at line 299 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToHighhipB_M
const QString waistToHighhipB_M = QStringLiteral("waist_to_highhip_b")
Definition at line 198 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToHighhipF_M
const QString waistToHighhipF_M = QStringLiteral("waist_to_highhip_f")
Definition at line 195 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToHighhipSide_M
const QString waistToHighhipSide_M = QStringLiteral("waist_to_highhip_side")
Definition at line 197 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToHipB_M
const QString waistToHipB_M = QStringLiteral("waist_to_hip_b")
Definition at line 199 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToHipF_M
const QString waistToHipF_M = QStringLiteral("waist_to_hip_f")
Definition at line 196 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToHipSide_M
const QString waistToHipSide_M = QStringLiteral("waist_to_hip_side")
Definition at line 200 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupH(), ListGroupH(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToNaturalWaistB_M
const QString waistToNaturalWaistB_M = QStringLiteral("waist_to_natural_waist_b")
Definition at line 303 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToNaturalWaistF_M
const QString waistToNaturalWaistF_M = QStringLiteral("waist_to_natural_waist_f")
Definition at line 302 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
waistToWaistHalter_M
const QString waistToWaistHalter_M = QStringLiteral("waist_to_waist_halter")
Definition at line 298 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupO(), ListGroupO(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
widthAbdomenToHip_M
const QString widthAbdomenToHip_M = QStringLiteral("width_abdomen_to_hip")
Definition at line 91 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupB(), ListGroupB(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
widthBust_M
const QString widthBust_M = QStringLiteral("width_bust")
Definition at line 88 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupB(), ListGroupB(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
widthHip_M
const QString widthHip_M = QStringLiteral("width_hip")
Definition at line 90 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupB(), ListGroupB(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
widthShoulder_M
const QString widthShoulder_M = QStringLiteral("width_shoulder")
Definition at line 87 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupB(), ListGroupB(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().
widthWaist_M
const QString widthWaist_M = QStringLiteral("width_waist")
Definition at line 89 of file measurements_def.cpp.
Referenced by VTranslateMeasurements::InitGroupB(), ListGroupB(), and TST_NameRegExp::TestCorrectOrderMeasurement_data().