Seamly2D: XMLRefInfo Class Reference
XMLRefInfo Class Reference
#include <XMLRefInfo.hpp>
Public Member Functions
Constructor
XMLRefInfo (const XMLCh *const refName, const bool fDeclared=false, const bool fUsed=false, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLRefInfo (const XMLCh *const refName, const bool fDeclared=false, const bool fUsed=false, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLRefInfo (const XMLCh *const refName, const bool fDeclared=false, const bool fUsed=false, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Destructor
bool fDeclared
bool fUsed
XMLCh * fRefName
MemoryManager * fMemoryManager
~XMLRefInfo ()
bool getDeclared () const
const XMLCh * getRefName () const
bool getUsed () const
void setDeclared (const bool newValue)
void setUsed (const bool newValue)
XMLRefInfo (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XMLRefInfo ()
bool getDeclared () const
const XMLCh * getRefName () const
bool getUsed () const
void setDeclared (const bool newValue)
void setUsed (const bool newValue)
XMLRefInfo (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~XMLRefInfo ()
bool getDeclared () const
const XMLCh * getRefName () const
bool getUsed () const
void setDeclared (const bool newValue)
void setUsed (const bool newValue)
XMLRefInfo (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLRefInfo (const XMLRefInfo &)
XMLRefInfo & operator= (XMLRefInfo &)
XMLRefInfo (const XMLRefInfo &)
XMLRefInfo & operator= (XMLRefInfo &)
XMLRefInfo (const XMLRefInfo &)
XMLRefInfo & operator= (XMLRefInfo &)
Additional Inherited Members
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
This class provides a simple means to track ID Ref usage. Since id/idref semantics are part of XML 1.0, any validator will likely to be able to track them. Instances of this class represent a reference and two markers, one for its being declared and another for its being used. When the document is done, one can look at each instance and, if used but not declared, its an error.
The getKey() method allows it to support keyed collection semantics. It returns the referenced name, so these objects will be stored via the hash of the name. This name will either be a standard QName if namespaces are not enabled/supported by the validator, or it will be in the form {url}name if namespace processing is enabled.
Definition at line 47 of file XMLRefInfo.hpp.
Constructor & Destructor Documentation
XMLRefInfo() [1/9]
XMLRefInfo::XMLRefInfo (const XMLCh *const refName, const bool fDeclared = false, const bool fUsed = false, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager) inline
Definition at line 129 of file XMLRefInfo.hpp.
References XMLString::replicate().
~XMLRefInfo() [1/3]
XMLRefInfo::~XMLRefInfo () inline
Definition at line 141 of file XMLRefInfo.hpp.
XMLRefInfo() [2/9]
XMLRefInfo::XMLRefInfo (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XMLRefInfo() [3/9]
XMLRefInfo::XMLRefInfo (const XMLRefInfo &) private
XMLRefInfo() [4/9]
XMLRefInfo::XMLRefInfo (const XMLCh *const refName, const bool fDeclared = false, const bool fUsed = false, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XMLRefInfo() [2/3]
XMLRefInfo::~XMLRefInfo ()
XMLRefInfo() [5/9]
XMLRefInfo::XMLRefInfo (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XMLRefInfo() [6/9]
XMLRefInfo::XMLRefInfo (const XMLRefInfo &) private
XMLRefInfo() [7/9]
XMLRefInfo::XMLRefInfo (const XMLCh *const refName, const bool fDeclared = false, const bool fUsed = false, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~XMLRefInfo() [3/3]
XMLRefInfo::~XMLRefInfo ()
XMLRefInfo() [8/9]
XMLRefInfo::XMLRefInfo (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
XMLRefInfo() [9/9]
XMLRefInfo::XMLRefInfo (const XMLRefInfo &) private
Member Function Documentation
getDeclared() [1/3]
bool XMLRefInfo::getDeclared () const inline
Definition at line 150 of file XMLRefInfo.hpp.
getDeclared() [2/3]
bool XMLRefInfo::getDeclared () const
getDeclared() [3/3]
bool XMLRefInfo::getDeclared () const
getRefName() [1/3]
const XMLCh * XMLRefInfo::getRefName () const inline
Definition at line 155 of file XMLRefInfo.hpp.
getRefName() [2/3]
const XMLCh* XMLRefInfo::getRefName () const
getRefName() [3/3]
const XMLCh* XMLRefInfo::getRefName () const
getUsed() [1/3]
bool XMLRefInfo::getUsed () const inline
Definition at line 160 of file XMLRefInfo.hpp.
getUsed() [2/3]
bool XMLRefInfo::getUsed () const
getUsed() [3/3]
bool XMLRefInfo::getUsed () const
operator=() [1/3]
XMLRefInfo& XMLRefInfo::operator= (XMLRefInfo &) private
operator=() [2/3]
XMLRefInfo& XMLRefInfo::operator= (XMLRefInfo &) private
References XMLString::replicate().
operator=() [3/3]
XMLRefInfo& XMLRefInfo::operator= (XMLRefInfo &) private
References XMLString::replicate().
setDeclared() [1/3]
void XMLRefInfo::setDeclared (const bool newValue) inline
Definition at line 169 of file XMLRefInfo.hpp.
setDeclared() [2/3]
void XMLRefInfo::setDeclared (const bool newValue)
setDeclared() [3/3]
void XMLRefInfo::setDeclared (const bool newValue)
setUsed() [1/3]
void XMLRefInfo::setUsed (const bool newValue) inline
Definition at line 174 of file XMLRefInfo.hpp.
setUsed() [2/3]
void XMLRefInfo::setUsed (const bool newValue)
setUsed() [3/3]
void XMLRefInfo::setUsed (const bool newValue)
Member Data Documentation
fDeclared
bool XMLRefInfo::fDeclared private
Definition at line 119 of file XMLRefInfo.hpp.
fMemoryManager
MemoryManager * XMLRefInfo::fMemoryManager private
Definition at line 122 of file XMLRefInfo.hpp.
fRefName
XMLCh * XMLRefInfo::fRefName private
Definition at line 121 of file XMLRefInfo.hpp.
fUsed
bool XMLRefInfo::fUsed private
Definition at line 120 of file XMLRefInfo.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/XMLRefInfo.hpp