Seamly2D: DialogLayoutProgress Class Reference
DialogLayoutProgress Class Reference
#include <dialoglayoutprogress.h>
Public Slots
void Start ()
void Arranged (int count)
void Error (const LayoutErrors &state)
void Finished ()
Signals
void Abort ()
Public Member Functions
DialogLayoutProgress (int count, QWidget *parent=nullptr)
~DialogLayoutProgress ()
Protected Member Functions
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
Private Attributes
Ui::DialogLayoutProgress * ui
const int maxCount
QMovie * movie
bool isInitialized
Detailed Description
Definition at line 64 of file dialoglayoutprogress.h.
Constructor & Destructor Documentation
DialogLayoutProgress()
DialogLayoutProgress::DialogLayoutProgress (int count, QWidget * parent = nullptr) explicit
Definition at line 63 of file dialoglayoutprogress.cpp.
References Abort(), maxCount, movie, qApp, SCASSERT, and ui.
~DialogLayoutProgress()
DialogLayoutProgress::~DialogLayoutProgress ()
Definition at line 88 of file dialoglayoutprogress.cpp.
References movie, and ui.
Member Function Documentation
Abort
void DialogLayoutProgress::Abort () signal
Referenced by DialogLayoutProgress(), and MainWindowsNoGUI::LayoutSettings().
Arranged
void DialogLayoutProgress::Arranged (int count) slot
Definition at line 101 of file dialoglayoutprogress.cpp.
References maxCount, and ui.
Referenced by MainWindowsNoGUI::LayoutSettings().
Error
void DialogLayoutProgress::Error (const LayoutErrors & state) slot
Definition at line 108 of file dialoglayoutprogress.cpp.
References EmptyPaperError, NoError, PrepareLayoutError, and ProcessStoped.
Referenced by MainWindowsNoGUI::LayoutSettings().
Finished
void DialogLayoutProgress::Finished () slot
Definition at line 129 of file dialoglayoutprogress.cpp.
Referenced by MainWindowsNoGUI::LayoutSettings().
showEvent()
void DialogLayoutProgress::showEvent (QShowEvent * event) protected virtual
Definition at line 135 of file dialoglayoutprogress.cpp.
References isInitialized.
Start
void DialogLayoutProgress::Start () slot
Definition at line 95 of file dialoglayoutprogress.cpp.
Referenced by MainWindowsNoGUI::LayoutSettings().
Member Data Documentation
isInitialized
bool DialogLayoutProgress::isInitialized private
Definition at line 89 of file dialoglayoutprogress.h.
Referenced by showEvent().
maxCount
const int DialogLayoutProgress::maxCount private
Definition at line 87 of file dialoglayoutprogress.h.
Referenced by Arranged(), and DialogLayoutProgress().
movie
QMovie* DialogLayoutProgress::movie private
Definition at line 88 of file dialoglayoutprogress.h.
Referenced by DialogLayoutProgress(), and ~DialogLayoutProgress().
ui
Ui::DialogLayoutProgress* DialogLayoutProgress::ui private
Definition at line 86 of file dialoglayoutprogress.h.
Referenced by Arranged(), DialogLayoutProgress(), and ~DialogLayoutProgress().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/dialoglayoutprogress.h
src/app/seamly2d/dialogs/dialoglayoutprogress.cpp