Seamly2D: FieldValueMap Class Reference
FieldValueMap Class Reference
#include <FieldValueMap.hpp>
Public Member Functions
FieldValueMap (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
FieldValueMap (const FieldValueMap &other)
~FieldValueMap ()
DatatypeValidator * getDatatypeValidatorAt (const XMLSize_t index) const
DatatypeValidator * getDatatypeValidatorFor (const IC_Field *const key) const
XMLCh * getValueAt (const XMLSize_t index) const
XMLCh * getValueFor (const IC_Field *const key) const
IC_Field * keyAt (const XMLSize_t index) const
void put (IC_Field *const key, DatatypeValidator *const dv, const XMLCh *const value)
XMLSize_t size () const
bool indexOf (const IC_Field *const key, XMLSize_t &location) const
void clear ()
FieldValueMap (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
FieldValueMap (const FieldValueMap &other)
~FieldValueMap ()
DatatypeValidator * getDatatypeValidatorAt (const XMLSize_t index) const
DatatypeValidator * getDatatypeValidatorFor (const IC_Field *const key) const
XMLCh * getValueAt (const XMLSize_t index) const
XMLCh * getValueFor (const IC_Field *const key) const
IC_Field * keyAt (const XMLSize_t index) const
void put (IC_Field *const key, DatatypeValidator *const dv, const XMLCh *const value)
XMLSize_t size () const
bool indexOf (const IC_Field *const key, XMLSize_t &location) const
void clear ()
FieldValueMap (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
FieldValueMap (const FieldValueMap &other)
~FieldValueMap ()
DatatypeValidator * getDatatypeValidatorAt (const XMLSize_t index) const
DatatypeValidator * getDatatypeValidatorFor (const IC_Field *const key) const
XMLCh * getValueAt (const XMLSize_t index) const
XMLCh * getValueFor (const IC_Field *const key) const
IC_Field * keyAt (const XMLSize_t index) const
void put (IC_Field *const key, DatatypeValidator *const dv, const XMLCh *const value)
XMLSize_t size () const
bool indexOf (const IC_Field *const key, XMLSize_t &location) const
void clear ()
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
void cleanUp ()
FieldValueMap & operator= (const FieldValueMap &other)
void cleanUp ()
FieldValueMap & operator= (const FieldValueMap &other)
void cleanUp ()
FieldValueMap & operator= (const FieldValueMap &other)
Private Attributes
ValueVectorOf< IC_Field * > * fFields
ValueVectorOf< DatatypeValidator * > * fValidators
RefArrayVectorOf< XMLCh > * fValues
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 46 of file FieldValueMap.hpp.
Constructor & Destructor Documentation
FieldValueMap() [1/6]
FieldValueMap::FieldValueMap (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
FieldValueMap() [2/6]
FieldValueMap::FieldValueMap (const FieldValueMap & other)
~FieldValueMap() [1/3]
FieldValueMap::~FieldValueMap ()
FieldValueMap() [3/6]
FieldValueMap::FieldValueMap (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
FieldValueMap() [4/6]
FieldValueMap::FieldValueMap (const FieldValueMap & other)
~FieldValueMap() [2/3]
FieldValueMap::~FieldValueMap ()
FieldValueMap() [5/6]
FieldValueMap::FieldValueMap (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
FieldValueMap() [6/6]
FieldValueMap::FieldValueMap (const FieldValueMap & other)
~FieldValueMap() [3/3]
FieldValueMap::~FieldValueMap ()
Member Function Documentation
cleanUp() [1/3]
void FieldValueMap::cleanUp () private
cleanUp() [2/3]
void FieldValueMap::cleanUp () private
cleanUp() [3/3]
void FieldValueMap::cleanUp () private
clear() [1/3]
void FieldValueMap::clear ()
clear() [2/3]
void FieldValueMap::clear ()
clear() [3/3]
void FieldValueMap::clear ()
getDatatypeValidatorAt() [1/3]
DatatypeValidator * FieldValueMap::getDatatypeValidatorAt (const XMLSize_t index) const inline
Definition at line 103 of file FieldValueMap.hpp.
References ValueVectorOf< TElem >::elementAt(), and fValidators.
getDatatypeValidatorAt() [2/3]
DatatypeValidator* FieldValueMap::getDatatypeValidatorAt (const XMLSize_t index) const
getDatatypeValidatorAt() [3/3]
DatatypeValidator* FieldValueMap::getDatatypeValidatorAt (const XMLSize_t index) const
getDatatypeValidatorFor() [1/3]
DatatypeValidator * FieldValueMap::getDatatypeValidatorFor (const IC_Field *const key) const inline
Definition at line 113 of file FieldValueMap.hpp.
References ValueVectorOf< TElem >::elementAt(), fValidators, and indexOf().
getDatatypeValidatorFor() [2/3]
DatatypeValidator* FieldValueMap::getDatatypeValidatorFor (const IC_Field *const key) const
getDatatypeValidatorFor() [3/3]
DatatypeValidator* FieldValueMap::getDatatypeValidatorFor (const IC_Field *const key) const
getValueAt() [1/3]
XMLCh * FieldValueMap::getValueAt (const XMLSize_t index) const inline
Definition at line 123 of file FieldValueMap.hpp.
References BaseRefVectorOf< TElem >::elementAt(), and fValues.
getValueAt() [2/3]
XMLCh* FieldValueMap::getValueAt (const XMLSize_t index) const
getValueAt() [3/3]
XMLCh* FieldValueMap::getValueAt (const XMLSize_t index) const
getValueFor() [1/3]
XMLCh * FieldValueMap::getValueFor (const IC_Field *const key) const inline
Definition at line 132 of file FieldValueMap.hpp.
References BaseRefVectorOf< TElem >::elementAt(), fValues, and indexOf().
getValueFor() [2/3]
XMLCh* FieldValueMap::getValueFor (const IC_Field *const key) const
getValueFor() [3/3]
XMLCh* FieldValueMap::getValueFor (const IC_Field *const key) const
indexOf() [1/3]
bool FieldValueMap::indexOf (const IC_Field *const key, XMLSize_t & location) const
Referenced by getDatatypeValidatorFor(), getValueFor(), and put().
indexOf() [2/3]
bool FieldValueMap::indexOf (const IC_Field *const key, XMLSize_t & location) const
indexOf() [3/3]
bool FieldValueMap::indexOf (const IC_Field *const key, XMLSize_t & location) const
keyAt() [1/3]
IC_Field * FieldValueMap::keyAt (const XMLSize_t index) const inline
Definition at line 142 of file FieldValueMap.hpp.
References ValueVectorOf< TElem >::elementAt(), and fFields.
keyAt() [2/3]
IC_Field* FieldValueMap::keyAt (const XMLSize_t index) const
keyAt() [3/3]
IC_Field* FieldValueMap::keyAt (const XMLSize_t index) const
operator=() [1/3]
FieldValueMap& FieldValueMap::operator= (const FieldValueMap & other) private
operator=() [2/3]
FieldValueMap& FieldValueMap::operator= (const FieldValueMap & other) private
operator=() [3/3]
FieldValueMap& FieldValueMap::operator= (const FieldValueMap & other) private
put() [1/3]
void FieldValueMap::put (IC_Field *const key, DatatypeValidator *const dv, const XMLCh *const value) inline
Definition at line 166 of file FieldValueMap.hpp.
References ValueVectorOf< TElem >::addElement(), BaseRefVectorOf< TElem >::addElement(), fFields, fMemoryManager, fValidators, fValues, indexOf(), XMLString::replicate(), ValueVectorOf< TElem >::setElementAt(), and RefArrayVectorOf< TElem >::setElementAt().
put() [2/3]
void FieldValueMap::put (IC_Field *const key, DatatypeValidator *const dv, const XMLCh *const value)
put() [3/3]
void FieldValueMap::put (IC_Field *const key, DatatypeValidator *const dv, const XMLCh *const value)
size() [1/3]
XMLSize_t FieldValueMap::size () const inline
Definition at line 154 of file FieldValueMap.hpp.
References fFields, and ValueVectorOf< TElem >::size().
size() [2/3]
XMLSize_t FieldValueMap::size () const
size() [3/3]
XMLSize_t FieldValueMap::size () const
Member Data Documentation
fFields
ValueVectorOf< IC_Field * > * FieldValueMap::fFields private
Definition at line 92 of file FieldValueMap.hpp.
Referenced by keyAt(), put(), and size().
fMemoryManager
MemoryManager * FieldValueMap::fMemoryManager private
Definition at line 95 of file FieldValueMap.hpp.
Referenced by put().
fValidators
ValueVectorOf< DatatypeValidator * > * FieldValueMap::fValidators private
Definition at line 93 of file FieldValueMap.hpp.
Referenced by getDatatypeValidatorAt(), getDatatypeValidatorFor(), and put().
fValues
RefArrayVectorOf< XMLCh > * FieldValueMap::fValues private
Definition at line 94 of file FieldValueMap.hpp.
Referenced by getValueAt(), getValueFor(), and put().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/identity/FieldValueMap.hpp