Seamly2D: DialogPatternProperties Class Reference
DialogPatternProperties Class Reference
#include <dialogpatternproperties.h>
Signals
void UpdateGradation ()
Public Member Functions
DialogPatternProperties (VPattern *doc, VContainer *pattern, QWidget *parent=nullptr)
virtual ~DialogPatternProperties () Q_DECL_OVERRIDE
Private Slots
void DefValueChanged ()
void LabelDataChanged ()
void Apply ()
void Ok ()
void SelectAll (int state)
void CheckStateHeight (int state)
void CheckStateSize (int state)
void DescEdited ()
void ChangeImage ()
void SaveImage ()
void EditLabel ()
Private Member Functions
void SetHeightsChecked (bool enabled)
void SetSizesChecked (bool enabled)
void InitHeights ()
void InitSizes ()
template<typename Func >
void Init (QCheckBox *check, int val, Func slot)
template<typename GVal >
void SetOptions (const QMap< GVal, bool > &option)
template<typename GVal >
void InitComboBox (QComboBox *box, const QMap< GVal, bool > &option)
void initComboBoxFormats (QComboBox *box, const QStringList &items, const QString &currentFormat)
void CheckApplyOk ()
void SaveDescription ()
void SaveGradation ()
void SaveDefValues ()
void SaveLabelData ()
void SaveTemplateData ()
void SaveReadOnlyState ()
void SetDefaultHeight (const QString &def)
void SetDefaultSize (const QString &def)
void UpdateDefHeight ()
void UpdateDefSize ()
void InitImage ()
QImage GetImage ()
Private Attributes
Ui::DialogPatternProperties * ui
VPattern * doc
VContainer * pattern
int heightsChecked
int sizesChecked
QMap< GHeights, bool > heights
QMap< GSizes, bool > sizes
QMap< QCheckBox *, int > data
bool descriptionChanged
bool gradationChanged
bool defaultChanged
bool securityChanged
bool labelDataChanged
bool askSaveLabelData
bool templateDataChanged
QAction * deleteAction
QAction * changeImageAction
QAction * saveImageAction
QAction * showImageAction
QVector< VLabelTemplateLine > templateLines
Detailed Description
Definition at line 68 of file dialogpatternproperties.h.
Constructor & Destructor Documentation
DialogPatternProperties()
DialogPatternProperties::DialogPatternProperties (VPattern * doc, VContainer * pattern, QWidget * parent = nullptr) explicit
Definition at line 72 of file dialogpatternproperties.cpp.
References Apply(), defaultChanged, DefValueChanged(), DescEdited(), doc, EditLabel(), VAbstractPattern::GetCompanyName(), VAbstractPattern::GetCustomerName(), VPattern::GetDefCustomHeight(), VPattern::GetDefCustomSize(), VAbstractPattern::GetDescription(), VAbstractPattern::GetGradationHeights(), VAbstractPattern::GetGradationSizes(), VAbstractPattern::GetLabelDateFormat(), VAbstractPattern::GetLabelTimeFormat(), VAbstractPattern::GetNotes(), VCommonSettings::GetOsSeparator(), VAbstractPattern::GetPatternName(), VAbstractPattern::GetPatternNumber(), VCommonSettings::GetUserDefinedDateFormats(), VCommonSettings::GetUserDefinedTimeFormats(), gradationChanged, heights, InitComboBox(), initComboBoxFormats(), InitHeights(), InitImage(), InitSizes(), VPattern::IsDefCustom(), VPattern::IsReadOnly(), LabelDataChanged(), Multisize, Ok(), VCommonSettings::PredefinedDateFormats(), VCommonSettings::PredefinedTimeFormats(), qApp, SCASSERT, securityChanged, SetDefaultHeight(), SetDefaultSize(), SetOptions(), sizes, and ui.
~DialogPatternProperties()
DialogPatternProperties::~DialogPatternProperties () virtual
Definition at line 222 of file dialogpatternproperties.cpp.
References ui.
Member Function Documentation
Apply
void DialogPatternProperties::Apply () private slot
Definition at line 228 of file dialogpatternproperties.cpp.
References doc, SaveDefValues(), SaveDescription(), SaveGradation(), SaveLabelData(), SaveReadOnlyState(), SaveTemplateData(), ui, and VAbstractPattern::UpdatePatternLabel().
Referenced by DialogPatternProperties().
ChangeImage
void DialogPatternProperties::ChangeImage () private slot
Definition at line 831 of file dialogpatternproperties.cpp.
References deleteAction, doc, saveImageAction, VAbstractPattern::SetImage(), showImageAction, and ui.
Referenced by InitImage().
CheckApplyOk()
void DialogPatternProperties::CheckApplyOk () private
Definition at line 558 of file dialogpatternproperties.cpp.
References heightsChecked, sizesChecked, and ui.
Referenced by CheckStateHeight(), and CheckStateSize().
CheckStateHeight
void DialogPatternProperties::CheckStateHeight (int state) private slot
Definition at line 310 of file dialogpatternproperties.cpp.
References ALL, CheckApplyOk(), data, gradationChanged, heights, heightsChecked, heightsCount, ui, and UpdateDefHeight().
Referenced by InitHeights().
CheckStateSize
void DialogPatternProperties::CheckStateSize (int state) private slot
Definition at line 351 of file dialogpatternproperties.cpp.
References ALL, CheckApplyOk(), data, gradationChanged, sizes, sizesChecked, sizesCount, ui, and UpdateDefSize().
Referenced by InitSizes().
DefValueChanged
void DialogPatternProperties::DefValueChanged () private slot
Definition at line 399 of file dialogpatternproperties.cpp.
References defaultChanged.
Referenced by DialogPatternProperties().
DescEdited
void DialogPatternProperties::DescEdited () private slot
Definition at line 393 of file dialogpatternproperties.cpp.
References descriptionChanged.
Referenced by DialogPatternProperties().
EditLabel
void DialogPatternProperties::EditLabel () private slot
Definition at line 898 of file dialogpatternproperties.cpp.
References askSaveLabelData, doc, VAbstractPattern::getPatternLabelTemplate(), EditLabelTemplateDialog::GetTemplate(), labelDataChanged, SaveLabelData(), EditLabelTemplateDialog::SetTemplate(), templateDataChanged, and templateLines.
Referenced by DialogPatternProperties().
GetImage()
QImage DialogPatternProperties::GetImage () private
Definition at line 762 of file dialogpatternproperties.cpp.
References doc, VAbstractPattern::GetImage(), and VAbstractPattern::GetImageExtension().
Referenced by InitImage().
Init()
template<typename Func > void DialogPatternProperties::Init (QCheckBox * check, int val, Func slot) private
Definition at line 713 of file dialogpatternproperties.cpp.
References data.
Referenced by InitHeights(), and InitSizes().
InitComboBox()
template<typename GVal > void DialogPatternProperties::InitComboBox (QComboBox * box, const QMap< GVal, bool > & option) private
Definition at line 743 of file dialogpatternproperties.cpp.
References Cm, VContainer::GetPatternUnit(), pattern, SCASSERT, and UnitConvertor().
Referenced by DialogPatternProperties(), UpdateDefHeight(), and UpdateDefSize().
initComboBoxFormats()
void DialogPatternProperties::initComboBoxFormats (QComboBox * box, const QStringList & items, const QString & currentFormat) private
Definition at line 540 of file dialogpatternproperties.cpp.
References SCASSERT.
Referenced by DialogPatternProperties().
InitHeights()
void DialogPatternProperties::InitHeights () private
Definition at line 474 of file dialogpatternproperties.cpp.
References ALL, CheckStateHeight(), H104, H110, H116, H122, H128, H134, H140, H146, H152, H158, H164, H170, H176, H182, H188, H194, H200, H50, H56, H62, H68, H74, H80, H86, H92, H98, Init(), SelectAll(), and ui.
Referenced by DialogPatternProperties().
InitImage()
void DialogPatternProperties::InitImage () private
Definition at line 777 of file dialogpatternproperties.cpp.
References ChangeImage(), changeImageAction, deleteAction, VAbstractPattern::DeleteImage(), doc, GetImage(), SaveImage(), saveImageAction, showImageAction, and ui.
Referenced by DialogPatternProperties().
InitSizes()
void DialogPatternProperties::InitSizes () private
Definition at line 507 of file dialogpatternproperties.cpp.
References ALL, CheckStateSize(), Init(), S22, S24, S26, S28, S30, S32, S34, S36, S38, S40, S42, S44, S46, S48, S50, S52, S54, S56, S58, S60, S62, S64, S66, S68, S70, S72, SelectAll(), and ui.
Referenced by DialogPatternProperties().
LabelDataChanged
void DialogPatternProperties::LabelDataChanged () private slot
Definition at line 405 of file dialogpatternproperties.cpp.
References askSaveLabelData, and labelDataChanged.
Referenced by DialogPatternProperties().
Ok
void DialogPatternProperties::Ok () private slot
Definition at line 253 of file dialogpatternproperties.cpp.
References doc, SaveDefValues(), SaveDescription(), SaveGradation(), SaveLabelData(), SaveReadOnlyState(), SaveTemplateData(), and VAbstractPattern::UpdatePatternLabel().
Referenced by DialogPatternProperties().
SaveDefValues()
void DialogPatternProperties::SaveDefValues () private
Definition at line 592 of file dialogpatternproperties.cpp.
References defaultChanged, doc, VAbstractPattern::patternChanged(), VPattern::SetDefCustom(), VPattern::SetDefCustomHeight(), VPattern::SetDefCustomSize(), and ui.
Referenced by Apply(), and Ok().
SaveDescription()
void DialogPatternProperties::SaveDescription () private
Definition at line 566 of file dialogpatternproperties.cpp.
References descriptionChanged, doc, VAbstractPattern::patternChanged(), VAbstractPattern::SetDescription(), VAbstractPattern::SetNotes(), and ui.
Referenced by Apply(), and Ok().
SaveGradation()
void DialogPatternProperties::SaveGradation () private
Definition at line 579 of file dialogpatternproperties.cpp.
References doc, gradationChanged, heights, VAbstractPattern::patternChanged(), VAbstractPattern::SetGradationHeights(), VAbstractPattern::SetGradationSizes(), sizes, and UpdateGradation().
Referenced by Apply(), and Ok().
SaveImage
void DialogPatternProperties::SaveImage () private slot
Definition at line 873 of file dialogpatternproperties.cpp.
References doc, VAbstractPattern::GetImage(), and VAbstractPattern::GetImageExtension().
Referenced by InitImage().
SaveLabelData()
void DialogPatternProperties::SaveLabelData () private
Definition at line 612 of file dialogpatternproperties.cpp.
References askSaveLabelData, doc, labelDataChanged, VAbstractPattern::patternChanged(), VAbstractPattern::SetCompanyName(), VAbstractPattern::SetCustomerName(), VAbstractPattern::SetLabelDateFormat(), VAbstractPattern::SetLabelTimeFormat(), VAbstractPattern::SetPatternName(), VAbstractPattern::SetPatternNumber(), ui, and VAbstractPattern::UpdatePatternLabel().
Referenced by Apply(), EditLabel(), and Ok().
SaveReadOnlyState()
void DialogPatternProperties::SaveReadOnlyState () private
Definition at line 643 of file dialogpatternproperties.cpp.
References doc, VAbstractPattern::patternChanged(), securityChanged, VPattern::SetReadOnly(), and ui.
Referenced by Apply(), and Ok().
SaveTemplateData()
void DialogPatternProperties::SaveTemplateData () private
Definition at line 631 of file dialogpatternproperties.cpp.
References doc, VAbstractPattern::patternChanged(), VAbstractPattern::setPatternLabelTemplate(), templateDataChanged, templateLines, and VAbstractPattern::UpdatePatternLabel().
Referenced by Apply(), and Ok().
SelectAll
void DialogPatternProperties::SelectAll (int state) private slot
Definition at line 268 of file dialogpatternproperties.cpp.
References data, heights, SetHeightsChecked(), SetSizesChecked(), sizes, and ui.
Referenced by InitHeights(), and InitSizes().
SetDefaultHeight()
void DialogPatternProperties::SetDefaultHeight (const QString & def) private
Definition at line 654 of file dialogpatternproperties.cpp.
References defaultChanged, VContainer::height(), and ui.
Referenced by DialogPatternProperties(), and UpdateDefHeight().
SetDefaultSize()
void DialogPatternProperties::SetDefaultSize (const QString & def) private
Definition at line 675 of file dialogpatternproperties.cpp.
References defaultChanged, VContainer::size(), and ui.
Referenced by DialogPatternProperties(), and UpdateDefSize().
SetHeightsChecked()
void DialogPatternProperties::SetHeightsChecked (bool enabled) private
Definition at line 412 of file dialogpatternproperties.cpp.
References ui.
Referenced by SelectAll().
SetOptions()
template<typename GVal > void DialogPatternProperties::SetOptions (const QMap< GVal, bool > & option) private
Definition at line 721 of file dialogpatternproperties.cpp.
References data.
Referenced by DialogPatternProperties().
SetSizesChecked()
void DialogPatternProperties::SetSizesChecked (bool enabled) private
Definition at line 443 of file dialogpatternproperties.cpp.
References ui.
Referenced by SelectAll().
UpdateDefHeight()
void DialogPatternProperties::UpdateDefHeight () private
Definition at line 696 of file dialogpatternproperties.cpp.
References heights, InitComboBox(), SetDefaultHeight(), and ui.
Referenced by CheckStateHeight().
UpdateDefSize()
void DialogPatternProperties::UpdateDefSize () private
Definition at line 704 of file dialogpatternproperties.cpp.
References InitComboBox(), SetDefaultSize(), sizes, and ui.
Referenced by CheckStateSize().
UpdateGradation
void DialogPatternProperties::UpdateGradation () signal
Referenced by SaveGradation().
Member Data Documentation
askSaveLabelData
bool DialogPatternProperties::askSaveLabelData private
Definition at line 103 of file dialogpatternproperties.h.
Referenced by EditLabel(), LabelDataChanged(), and SaveLabelData().
changeImageAction
QAction* DialogPatternProperties::changeImageAction private
Definition at line 106 of file dialogpatternproperties.h.
Referenced by InitImage().
data
QMap<QCheckBox *, int> DialogPatternProperties::data private
Definition at line 97 of file dialogpatternproperties.h.
Referenced by CheckStateHeight(), CheckStateSize(), Init(), SelectAll(), and SetOptions().
defaultChanged
bool DialogPatternProperties::defaultChanged private
Definition at line 100 of file dialogpatternproperties.h.
Referenced by DefValueChanged(), DialogPatternProperties(), SaveDefValues(), SetDefaultHeight(), and SetDefaultSize().
deleteAction
QAction* DialogPatternProperties::deleteAction private
Definition at line 105 of file dialogpatternproperties.h.
Referenced by ChangeImage(), and InitImage().
descriptionChanged
bool DialogPatternProperties::descriptionChanged private
Definition at line 98 of file dialogpatternproperties.h.
Referenced by DescEdited(), and SaveDescription().
doc
VPattern* DialogPatternProperties::doc private
Definition at line 91 of file dialogpatternproperties.h.
Referenced by Apply(), ChangeImage(), DialogPatternProperties(), EditLabel(), GetImage(), InitImage(), Ok(), SaveDefValues(), SaveDescription(), SaveGradation(), SaveImage(), SaveLabelData(), SaveReadOnlyState(), and SaveTemplateData().
gradationChanged
bool DialogPatternProperties::gradationChanged private
Definition at line 99 of file dialogpatternproperties.h.
Referenced by CheckStateHeight(), CheckStateSize(), DialogPatternProperties(), and SaveGradation().
heights
QMap<GHeights, bool> DialogPatternProperties::heights private
Definition at line 95 of file dialogpatternproperties.h.
Referenced by CheckStateHeight(), DialogPatternProperties(), SaveGradation(), SelectAll(), and UpdateDefHeight().
heightsChecked
int DialogPatternProperties::heightsChecked private
Definition at line 93 of file dialogpatternproperties.h.
Referenced by CheckApplyOk(), and CheckStateHeight().
labelDataChanged
bool DialogPatternProperties::labelDataChanged private
Definition at line 102 of file dialogpatternproperties.h.
Referenced by EditLabel(), LabelDataChanged(), and SaveLabelData().
pattern
VContainer* DialogPatternProperties::pattern private
Definition at line 92 of file dialogpatternproperties.h.
Referenced by InitComboBox().
saveImageAction
QAction* DialogPatternProperties::saveImageAction private
Definition at line 107 of file dialogpatternproperties.h.
Referenced by ChangeImage(), and InitImage().
securityChanged
bool DialogPatternProperties::securityChanged private
Definition at line 101 of file dialogpatternproperties.h.
Referenced by DialogPatternProperties(), and SaveReadOnlyState().
showImageAction
QAction* DialogPatternProperties::showImageAction private
Definition at line 108 of file dialogpatternproperties.h.
Referenced by ChangeImage(), and InitImage().
sizes
QMap<GSizes, bool> DialogPatternProperties::sizes private
Definition at line 96 of file dialogpatternproperties.h.
Referenced by CheckStateSize(), DialogPatternProperties(), SaveGradation(), SelectAll(), and UpdateDefSize().
sizesChecked
int DialogPatternProperties::sizesChecked private
Definition at line 94 of file dialogpatternproperties.h.
Referenced by CheckApplyOk(), and CheckStateSize().
templateDataChanged
bool DialogPatternProperties::templateDataChanged private
Definition at line 104 of file dialogpatternproperties.h.
Referenced by EditLabel(), and SaveTemplateData().
templateLines
QVector<VLabelTemplateLine> DialogPatternProperties::templateLines private
Definition at line 110 of file dialogpatternproperties.h.
Referenced by EditLabel(), and SaveTemplateData().
ui
Ui::DialogPatternProperties* DialogPatternProperties::ui private
Definition at line 90 of file dialogpatternproperties.h.
Referenced by Apply(), ChangeImage(), CheckApplyOk(), CheckStateHeight(), CheckStateSize(), DialogPatternProperties(), InitHeights(), InitImage(), InitSizes(), SaveDefValues(), SaveDescription(), SaveLabelData(), SaveReadOnlyState(), SelectAll(), SetDefaultHeight(), SetDefaultSize(), SetHeightsChecked(), SetSizesChecked(), UpdateDefHeight(), UpdateDefSize(), and ~DialogPatternProperties().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/dialogpatternproperties.h
src/app/seamly2d/dialogs/dialogpatternproperties.cpp