Seamly2D: TST_VEllipticalArc Class Reference
TST_VEllipticalArc Class Reference
#include <tst_vellipticalarc.h>
Public Member Functions
TST_VEllipticalArc (QObject *parent=nullptr)
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Private Slots
void CompareTwoWays_data ()
void CompareTwoWays ()
void NegativeArc ()
void TestGetPoints1_data ()
void TestGetPoints2_data ()
void TestGetPoints3_data ()
void TestGetPoints4_data ()
void TestGetPoints1 ()
void TestGetPoints2 ()
void TestGetPoints3 ()
void TestGetPoints4 ()
void TestRotation_data ()
void TestRotation ()
void TestFlip_data ()
void TestFlip ()
Private Member Functions
void TestData ()
Additional Inherited Members
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Detailed Description
Definition at line 34 of file tst_vellipticalarc.h.
Constructor & Destructor Documentation
TST_VEllipticalArc()
TST_VEllipticalArc::TST_VEllipticalArc (QObject * parent = nullptr) explicit
Definition at line 37 of file tst_vellipticalarc.cpp.
Member Function Documentation
CompareTwoWays
void TST_VEllipticalArc::CompareTwoWays () private slot
Definition at line 70 of file tst_vellipticalarc.cpp.
References VEllipticalArc::GetEndAngle(), VEllipticalArc::GetLength(), Mm, and ToPixel().
CompareTwoWays_data
void TST_VEllipticalArc::CompareTwoWays_data () private slot
Definition at line 41 of file tst_vellipticalarc.cpp.
NegativeArc
void TST_VEllipticalArc::NegativeArc () private slot
Definition at line 106 of file tst_vellipticalarc.cpp.
References VEllipticalArc::GetEndAngle(), VEllipticalArc::GetLength(), Mm, and ToPixel().
TestData()
void TST_VEllipticalArc::TestData () private
Definition at line 159 of file tst_vellipticalarc.cpp.
Referenced by TestGetPoints1_data(), TestGetPoints2_data(), TestGetPoints3_data(), and TestGetPoints4_data().
TestFlip
void TST_VEllipticalArc::TestFlip () private slot
Definition at line 509 of file tst_vellipticalarc.cpp.
References VEllipticalArc::Flip(), VEllipticalArc::GetLength(), VEllipticalArc::GetRadius1(), VEllipticalArc::GetRadius2(), and VGObject::name().
TestFlip_data
void TST_VEllipticalArc::TestFlip_data () private slot
Definition at line 486 of file tst_vellipticalarc.cpp.
TestGetPoints1
void TST_VEllipticalArc::TestGetPoints1 () private slot
Definition at line 272 of file tst_vellipticalarc.cpp.
References VEllipticalArc::getPoints().
TestGetPoints1_data
void TST_VEllipticalArc::TestGetPoints1_data () private slot
Definition at line 135 of file tst_vellipticalarc.cpp.
References TestData().
TestGetPoints2
void TST_VEllipticalArc::TestGetPoints2 () private slot
Definition at line 302 of file tst_vellipticalarc.cpp.
References VEllipticalArc::getPoints(), VPointF::x(), and VPointF::y().
TestGetPoints2_data
void TST_VEllipticalArc::TestGetPoints2_data () private slot
Definition at line 141 of file tst_vellipticalarc.cpp.
References TestData().
TestGetPoints3
void TST_VEllipticalArc::TestGetPoints3 () private slot
Definition at line 373 of file tst_vellipticalarc.cpp.
References VAbstractArc::AngleArc(), VEllipticalArc::getPoints(), VAbstractPiece::sumTrapezoids(), and VFuzzyComparePossibleNulls().
TestGetPoints3_data
void TST_VEllipticalArc::TestGetPoints3_data () private slot
Definition at line 147 of file tst_vellipticalarc.cpp.
References TestData().
TestGetPoints4
void TST_VEllipticalArc::TestGetPoints4 () private slot
Definition at line 400 of file tst_vellipticalarc.cpp.
References VAbstractArc::AngleArc(), VEllipticalArc::GetLength(), and VFuzzyComparePossibleNulls().
TestGetPoints4_data
void TST_VEllipticalArc::TestGetPoints4_data () private slot
Definition at line 153 of file tst_vellipticalarc.cpp.
References TestData().
TestRotation
void TST_VEllipticalArc::TestRotation () private slot
Definition at line 453 of file tst_vellipticalarc.cpp.
References VAbstractArc::AngleArc(), VEllipticalArc::GetLength(), VEllipticalArc::GetRadius1(), VEllipticalArc::GetRadius2(), VEllipticalArc::GetRotationAngle(), Mm, VGObject::name(), VEllipticalArc::Rotate(), and ToPixel().
TestRotation_data
void TST_VEllipticalArc::TestRotation_data () private slot
Definition at line 427 of file tst_vellipticalarc.cpp.
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vellipticalarc.h
src/test/Seamly2DTest/tst_vellipticalarc.cpp