Seamly2D: EditGroupDialog Class Reference
EditGroupDialog Class Reference
#include <dialoggroup.h>
Public Slots
virtual void SelectedObject (bool selected, quint32 object, quint32 tool) Q_DECL_OVERRIDE
virtual void SelectedObject (bool selected, quint32 object, quint32 tool) Q_DECL_OVERRIDE
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
EditGroupDialog (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
~EditGroupDialog ()
void SetName (const QString &name)
QString GetName () const
QMap< quint32, quint32 > GetGroup () const
virtual void ShowDialog (bool click) Q_DECL_OVERRIDE
EditGroupDialog (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
virtual ~EditGroupDialog ()
void setName (const QString &name)
QString getName () const
QMap< quint32, quint32 > getGroupData () const
QString getColor () const
void setColor (const QString &color)
QString getLineType () const
void setLineType (const QString &type)
QString getLineWeight () const
void setLineWeight (const QString &weight)
virtual void ShowDialog (bool click) Q_DECL_OVERRIDE
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Private Slots
void NameChanged ()
void nameChanged ()
Private Attributes
Ui::EditGroupDialog * ui
QMap< quint32, quint32 > group
VAbstractPattern * m_doc
QMap< quint32, quint32 > m_groupData
QString m_oldGroupName
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
virtual void CheckState ()
CheckState enable, when all is correct, or disable, when something wrong, button ok.
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
virtual void ShowVisualization ()
virtual void SaveData ()
SaveData Put dialog data in local variables.
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
Definition at line 69 of file dialoggroup.h.
Constructor & Destructor Documentation
EditGroupDialog() [1/2]
EditGroupDialog::EditGroupDialog (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr) explicit
Definition at line 59 of file dialoggroup.cpp.
References DialogTool::CheckState(), DialogTool::initializeOkCancel(), NameChanged(), and ui.
~EditGroupDialog() [1/2]
EditGroupDialog::~EditGroupDialog ()
Definition at line 75 of file dialoggroup.cpp.
References ui.
EditGroupDialog() [2/2]
EditGroupDialog::EditGroupDialog (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr) explicit
~EditGroupDialog() [2/2]
virtual EditGroupDialog::~EditGroupDialog () virtual
Member Function Documentation
getColor()
QString EditGroupDialog::getColor () const
Definition at line 159 of file editgroup_dialog.cpp.
References ColorBlack, DialogTool::GetComboBoxCurrentData(), and ui.
GetGroup()
QMap< quint32, quint32 > EditGroupDialog::GetGroup () const
Definition at line 131 of file dialoggroup.cpp.
References group.
getGroupData()
QMap< quint32, quint32 > EditGroupDialog::getGroupData () const
Definition at line 153 of file editgroup_dialog.cpp.
References m_groupData.
getLineType()
QString EditGroupDialog::getLineType () const
Definition at line 171 of file editgroup_dialog.cpp.
References DialogTool::GetComboBoxCurrentData(), LineTypeSolidLine, and ui.
getLineWeight()
QString EditGroupDialog::getLineWeight () const
Definition at line 183 of file editgroup_dialog.cpp.
References DialogTool::GetComboBoxCurrentData(), and ui.
GetName()
QString EditGroupDialog::GetName () const
Definition at line 87 of file dialoggroup.cpp.
References ui.
getName()
QString EditGroupDialog::getName () const
Definition at line 109 of file editgroup_dialog.cpp.
References ui.
NameChanged
void EditGroupDialog::NameChanged () private slot
Definition at line 124 of file dialoggroup.cpp.
References DialogTool::CheckState(), DialogTool::flagName, and ui.
Referenced by EditGroupDialog().
nameChanged
void EditGroupDialog::nameChanged () private slot
Definition at line 146 of file editgroup_dialog.cpp.
References DialogTool::CheckState(), DialogTool::flagName, and ui.
SelectedObject [1/2]
void EditGroupDialog::SelectedObject (bool selected, quint32 object, quint32 tool) virtual slot
Definition at line 111 of file dialoggroup.cpp.
References group.
SelectedObject [2/2]
virtual void EditGroupDialog::SelectedObject (bool selected, quint32 object, quint32 tool) virtual slot
setColor()
void EditGroupDialog::setColor (const QString & color)
Definition at line 165 of file editgroup_dialog.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setLineType()
void EditGroupDialog::setLineType (const QString & type)
Definition at line 177 of file editgroup_dialog.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setLineWeight()
void EditGroupDialog::setLineWeight (const QString & weight)
Definition at line 189 of file editgroup_dialog.cpp.
References DialogTool::ChangeCurrentData(), and ui.
SetName()
void EditGroupDialog::SetName (const QString & name)
Definition at line 81 of file dialoggroup.cpp.
References ui.
Referenced by ShowDialog().
setName()
void EditGroupDialog::setName (const QString & name)
Definition at line 103 of file editgroup_dialog.cpp.
References ui.
ShowDialog() [1/2]
void EditGroupDialog::ShowDialog (bool click) virtual
Reimplemented from DialogTool.
Definition at line 93 of file dialoggroup.cpp.
References group, SetName(), and DialogTool::ToolTip().
ShowDialog() [2/2]
virtual void EditGroupDialog::ShowDialog (bool click) virtual
Reimplemented from DialogTool.
Member Data Documentation
group
QMap<quint32, quint32> EditGroupDialog::group private
Definition at line 93 of file dialoggroup.h.
Referenced by GetGroup(), SelectedObject(), and ShowDialog().
m_doc
VAbstractPattern* EditGroupDialog::m_doc private
Definition at line 100 of file editgroup_dialog.h.
m_groupData
QMap<quint32, quint32> EditGroupDialog::m_groupData private
Definition at line 101 of file editgroup_dialog.h.
Referenced by getGroupData().
m_oldGroupName
QString EditGroupDialog::m_oldGroupName private
Definition at line 102 of file editgroup_dialog.h.
ui
Ui::EditGroupDialog * EditGroupDialog::ui private
Definition at line 92 of file dialoggroup.h.
Referenced by EditGroupDialog(), getColor(), getLineType(), getLineWeight(), GetName(), getName(), NameChanged(), nameChanged(), setColor(), setLineType(), setLineWeight(), SetName(), setName(), and ~EditGroupDialog().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialoggroup.h
src/libs/vtools/dialogs/tools/editgroup_dialog.h
src/libs/vtools/dialogs/tools/dialoggroup.cpp
src/libs/vtools/dialogs/tools/editgroup_dialog.cpp