Seamly2D: Token Class Reference
Token Class Reference
#include <Token.hpp>
Public Types
enum tokType {
T_CHAR = 0 , T_CONCAT = 1 , T_UNION = 2 , T_CLOSURE = 3 ,
T_RANGE = 4 , T_NRANGE = 5 , T_PAREN = 6 , T_EMPTY = 7 ,
T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 , T_STRING = 10 , T_DOT = 11 ,
T_BACKREFERENCE = 12 , T_CHAR = 0 , T_CONCAT = 1 , T_UNION = 2 ,
T_CLOSURE = 3 , T_RANGE = 4 , T_NRANGE = 5 , T_PAREN = 6 ,
T_EMPTY = 7 , T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 , T_STRING = 10 ,
T_DOT = 11 , T_BACKREFERENCE = 12 , T_CHAR = 0 , T_CONCAT = 1 ,
T_UNION = 2 , T_CLOSURE = 3 , T_RANGE = 4 , T_NRANGE = 5 ,
T_PAREN = 6 , T_EMPTY = 7 , T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 ,
T_STRING = 10 , T_DOT = 11 , T_BACKREFERENCE = 12
}
enum firstCharacterOptions {
FC_CONTINUE = 0 , FC_TERMINAL = 1 , FC_ANY = 2 , FC_CONTINUE = 0 ,
FC_TERMINAL = 1 , FC_ANY = 2 , FC_CONTINUE = 0 , FC_TERMINAL = 1 ,
FC_ANY = 2
}
enum tokType {
T_CHAR = 0 , T_CONCAT = 1 , T_UNION = 2 , T_CLOSURE = 3 ,
T_RANGE = 4 , T_NRANGE = 5 , T_PAREN = 6 , T_EMPTY = 7 ,
T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 , T_STRING = 10 , T_DOT = 11 ,
T_BACKREFERENCE = 12 , T_CHAR = 0 , T_CONCAT = 1 , T_UNION = 2 ,
T_CLOSURE = 3 , T_RANGE = 4 , T_NRANGE = 5 , T_PAREN = 6 ,
T_EMPTY = 7 , T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 , T_STRING = 10 ,
T_DOT = 11 , T_BACKREFERENCE = 12 , T_CHAR = 0 , T_CONCAT = 1 ,
T_UNION = 2 , T_CLOSURE = 3 , T_RANGE = 4 , T_NRANGE = 5 ,
T_PAREN = 6 , T_EMPTY = 7 , T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 ,
T_STRING = 10 , T_DOT = 11 , T_BACKREFERENCE = 12
}
enum firstCharacterOptions {
FC_CONTINUE = 0 , FC_TERMINAL = 1 , FC_ANY = 2 , FC_CONTINUE = 0 ,
FC_TERMINAL = 1 , FC_ANY = 2 , FC_CONTINUE = 0 , FC_TERMINAL = 1 ,
FC_ANY = 2
}
enum tokType {
T_CHAR = 0 , T_CONCAT = 1 , T_UNION = 2 , T_CLOSURE = 3 ,
T_RANGE = 4 , T_NRANGE = 5 , T_PAREN = 6 , T_EMPTY = 7 ,
T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 , T_STRING = 10 , T_DOT = 11 ,
T_BACKREFERENCE = 12 , T_CHAR = 0 , T_CONCAT = 1 , T_UNION = 2 ,
T_CLOSURE = 3 , T_RANGE = 4 , T_NRANGE = 5 , T_PAREN = 6 ,
T_EMPTY = 7 , T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 , T_STRING = 10 ,
T_DOT = 11 , T_BACKREFERENCE = 12 , T_CHAR = 0 , T_CONCAT = 1 ,
T_UNION = 2 , T_CLOSURE = 3 , T_RANGE = 4 , T_NRANGE = 5 ,
T_PAREN = 6 , T_EMPTY = 7 , T_ANCHOR = 8 , T_NONGREEDYCLOSURE = 9 ,
T_STRING = 10 , T_DOT = 11 , T_BACKREFERENCE = 12
}
enum firstCharacterOptions {
FC_CONTINUE = 0 , FC_TERMINAL = 1 , FC_ANY = 2 , FC_CONTINUE = 0 ,
FC_TERMINAL = 1 , FC_ANY = 2 , FC_CONTINUE = 0 , FC_TERMINAL = 1 ,
FC_ANY = 2
}
Public Member Functions
Token (const tokType tkType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~Token ()
tokType getTokenType () const
XMLSize_t getMinLength () const
int getMaxLength () const
virtual Token * getChild (const XMLSize_t index) const
virtual XMLSize_t size () const
virtual int getMin () const
virtual int getMax () const
virtual int getNoParen () const
virtual int getReferenceNo () const
virtual const XMLCh * getString () const
virtual XMLInt32 getChar () const
void setTokenType (const tokType tokType)
virtual void setMin (const int minVal)
virtual void setMax (const int maxVal)
virtual void addRange (const XMLInt32 start, const XMLInt32 end)
virtual void mergeRanges (const Token *const tok)
virtual void sortRanges ()
virtual void compactRanges ()
virtual void subtractRanges (RangeToken *const tok)
virtual void intersectRanges (RangeToken *const tok)
virtual void addChild (Token *const child, TokenFactory *const tokFactory)
firstCharacterOptions analyzeFirstCharacter (RangeToken *const rangeTok, const int options, TokenFactory *const tokFactory)
Token * findFixedString (int options, int &outOptions)
Token (const tokType tkType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~Token ()
tokType getTokenType () const
XMLSize_t getMinLength () const
int getMaxLength () const
virtual Token * getChild (const XMLSize_t index) const
virtual XMLSize_t size () const
virtual int getMin () const
virtual int getMax () const
virtual int getNoParen () const
virtual int getReferenceNo () const
virtual const XMLCh * getString () const
virtual XMLInt32 getChar () const
void setTokenType (const tokType tokType)
virtual void setMin (const int minVal)
virtual void setMax (const int maxVal)
virtual void addRange (const XMLInt32 start, const XMLInt32 end)
virtual void mergeRanges (const Token *const tok)
virtual void sortRanges ()
virtual void compactRanges ()
virtual void subtractRanges (RangeToken *const tok)
virtual void intersectRanges (RangeToken *const tok)
virtual void addChild (Token *const child, TokenFactory *const tokFactory)
firstCharacterOptions analyzeFirstCharacter (RangeToken *const rangeTok, const int options, TokenFactory *const tokFactory)
Token * findFixedString (int options, int &outOptions)
Token (const tokType tkType, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~Token ()
tokType getTokenType () const
XMLSize_t getMinLength () const
int getMaxLength () const
virtual Token * getChild (const XMLSize_t index) const
virtual XMLSize_t size () const
virtual int getMin () const
virtual int getMax () const
virtual int getNoParen () const
virtual int getReferenceNo () const
virtual const XMLCh * getString () const
virtual XMLInt32 getChar () const
void setTokenType (const tokType tokType)
virtual void setMin (const int minVal)
virtual void setMax (const int maxVal)
virtual void addRange (const XMLInt32 start, const XMLInt32 end)
virtual void mergeRanges (const Token *const tok)
virtual void sortRanges ()
virtual void compactRanges ()
virtual void subtractRanges (RangeToken *const tok)
virtual void intersectRanges (RangeToken *const tok)
virtual void addChild (Token *const child, TokenFactory *const tokFactory)
firstCharacterOptions analyzeFirstCharacter (RangeToken *const rangeTok, const int options, TokenFactory *const tokFactory)
Token * findFixedString (int options, int &outOptions)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Static Public Attributes
static const XMLInt32 UTF16_MAX
Protected Attributes
MemoryManager *const fMemoryManager
Private Member Functions
Token (const Token &)
Token & operator= (const Token &)
bool isSet (const int options, const unsigned int flag)
bool isShorterThan (Token *const tok)
Token (const Token &)
Token & operator= (const Token &)
bool isSet (const int options, const unsigned int flag)
bool isShorterThan (Token *const tok)
Token (const Token &)
Token & operator= (const Token &)
bool isSet (const int options, const unsigned int flag)
bool isShorterThan (Token *const tok)
Private Attributes
tokType fTokenType
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 40 of file Token.hpp.
Member Enumeration Documentation
firstCharacterOptions [1/3]
enum Token::firstCharacterOptions
Enumerator
FC_CONTINUE
FC_TERMINAL
FC_ANY
FC_CONTINUE
FC_TERMINAL
FC_ANY
FC_CONTINUE
FC_TERMINAL
FC_ANY
Definition at line 73 of file Token.hpp.
firstCharacterOptions [2/3]
enum Token::firstCharacterOptions
Enumerator
FC_CONTINUE
FC_TERMINAL
FC_ANY
FC_CONTINUE
FC_TERMINAL
FC_ANY
FC_CONTINUE
FC_TERMINAL
FC_ANY
Definition at line 73 of file Token.hpp.
firstCharacterOptions [3/3]
enum Token::firstCharacterOptions
Enumerator
FC_CONTINUE
FC_TERMINAL
FC_ANY
FC_CONTINUE
FC_TERMINAL
FC_ANY
FC_CONTINUE
FC_TERMINAL
FC_ANY
Definition at line 73 of file Token.hpp.
tokType [1/3]
enum Token::tokType
Enumerator
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
Definition at line 47 of file Token.hpp.
tokType [2/3]
enum Token::tokType
Enumerator
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
Definition at line 47 of file Token.hpp.
tokType [3/3]
enum Token::tokType
Enumerator
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
T_CHAR
T_CONCAT
T_UNION
T_CLOSURE
T_RANGE
T_NRANGE
T_PAREN
T_EMPTY
T_ANCHOR
T_NONGREEDYCLOSURE
T_STRING
T_DOT
T_BACKREFERENCE
Definition at line 47 of file Token.hpp.
Constructor & Destructor Documentation
Token() [1/6]
Token::Token (const tokType tkType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~Token() [1/3]
virtual Token::~Token () virtual
Token() [2/6]
Token::Token (const Token &) private
Token() [3/6]
Token::Token (const tokType tkType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~Token() [2/3]
virtual Token::~Token () virtual
Token() [4/6]
Token::Token (const Token &) private
Token() [5/6]
Token::Token (const tokType tkType, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~Token() [3/3]
virtual Token::~Token () virtual
Token() [6/6]
Token::Token (const Token &) private
Member Function Documentation
addChild() [1/3]
void Token::addChild (Token *const child, TokenFactory *const tokFactory) inline virtual
Reimplemented in UnionToken, UnionToken, and UnionToken.
Definition at line 217 of file Token.hpp.
References fMemoryManager, XMLExcepts::Regex_NotSupported, and ThrowXMLwithMemMgr.
addChild() [2/3]
virtual void Token::addChild (Token *const child, TokenFactory *const tokFactory) virtual
Reimplemented in UnionToken, UnionToken, and UnionToken.
addChild() [3/3]
virtual void Token::addChild (Token *const child, TokenFactory *const tokFactory) virtual
Reimplemented in UnionToken, UnionToken, and UnionToken.
addRange() [1/3]
void Token::addRange (const XMLInt32 start, const XMLInt32 end) inline virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
Definition at line 225 of file Token.hpp.
References fMemoryManager, XMLExcepts::Regex_NotSupported, and ThrowXMLwithMemMgr.
addRange() [2/3]
virtual void Token::addRange (const XMLInt32 start, const XMLInt32 end) virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
addRange() [3/3]
virtual void Token::addRange (const XMLInt32 start, const XMLInt32 end) virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
analyzeFirstCharacter() [1/3]
firstCharacterOptions Token::analyzeFirstCharacter (RangeToken *const rangeTok, const int options, TokenFactory *const tokFactory)
analyzeFirstCharacter() [2/3]
firstCharacterOptions Token::analyzeFirstCharacter (RangeToken *const rangeTok, const int options, TokenFactory *const tokFactory)
analyzeFirstCharacter() [3/3]
firstCharacterOptions Token::analyzeFirstCharacter (RangeToken *const rangeTok, const int options, TokenFactory *const tokFactory)
compactRanges() [1/3]
void Token::compactRanges () inline virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
Definition at line 240 of file Token.hpp.
References fMemoryManager, XMLExcepts::Regex_NotSupported, and ThrowXMLwithMemMgr.
compactRanges() [2/3]
virtual void Token::compactRanges () virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
compactRanges() [3/3]
virtual void Token::compactRanges () virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
findFixedString() [1/3]
Token* Token::findFixedString (int options, int & outOptions)
findFixedString() [2/3]
Token* Token::findFixedString (int options, int & outOptions)
findFixedString() [3/3]
Token* Token::findFixedString (int options, int & outOptions)
getChar() [1/3]
XMLInt32 Token::getChar () const inline virtual
Reimplemented in CharToken, CharToken, and CharToken.
Definition at line 188 of file Token.hpp.
getChar() [2/3]
virtual XMLInt32 Token::getChar () const virtual
Reimplemented in CharToken, CharToken, and CharToken.
getChar() [3/3]
virtual XMLInt32 Token::getChar () const virtual
Reimplemented in CharToken, CharToken, and CharToken.
getChild() [1/3]
Token * Token::getChild (const XMLSize_t index) const inline virtual
Reimplemented in UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, and ClosureToken.
Definition at line 158 of file Token.hpp.
Referenced by RegularExpression::compileClosure(), RegularExpression::compileConcat(), RegularExpression::compileParenthesis(), and RegularExpression::compileUnion().
getChild() [2/3]
virtual Token* Token::getChild (const XMLSize_t index) const virtual
Reimplemented in UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, and ClosureToken.
getChild() [3/3]
virtual Token* Token::getChild (const XMLSize_t index) const virtual
Reimplemented in UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, and ClosureToken.
getMax() [1/3]
int Token::getMax () const inline virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
Definition at line 168 of file Token.hpp.
Referenced by RegularExpression::compileClosure().
getMax() [2/3]
virtual int Token::getMax () const virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
getMax() [3/3]
virtual int Token::getMax () const virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
getMaxLength() [1/3]
int Token::getMaxLength () const
getMaxLength() [2/3]
int Token::getMaxLength () const
getMaxLength() [3/3]
int Token::getMaxLength () const
getMin() [1/3]
int Token::getMin () const inline virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
Definition at line 163 of file Token.hpp.
Referenced by RegularExpression::compileClosure().
getMin() [2/3]
virtual int Token::getMin () const virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
getMin() [3/3]
virtual int Token::getMin () const virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
getMinLength() [1/3]
XMLSize_t Token::getMinLength () const
Referenced by RegularExpression::compileClosure().
getMinLength() [2/3]
XMLSize_t Token::getMinLength () const
getMinLength() [3/3]
XMLSize_t Token::getMinLength () const
getNoParen() [1/3]
int Token::getNoParen () const inline virtual
Reimplemented in ParenToken, ParenToken, and ParenToken.
Definition at line 178 of file Token.hpp.
Referenced by RegularExpression::compileParenthesis().
getNoParen() [2/3]
virtual int Token::getNoParen () const virtual
Reimplemented in ParenToken, ParenToken, and ParenToken.
getNoParen() [3/3]
virtual int Token::getNoParen () const virtual
Reimplemented in ParenToken, ParenToken, and ParenToken.
getReferenceNo() [1/3]
int Token::getReferenceNo () const inline virtual
Reimplemented in StringToken, StringToken, and StringToken.
Definition at line 173 of file Token.hpp.
getReferenceNo() [2/3]
virtual int Token::getReferenceNo () const virtual
Reimplemented in StringToken, StringToken, and StringToken.
getReferenceNo() [3/3]
virtual int Token::getReferenceNo () const virtual
Reimplemented in StringToken, StringToken, and StringToken.
getString() [1/3]
const XMLCh * Token::getString () const inline virtual
Reimplemented in StringToken, StringToken, and StringToken.
Definition at line 183 of file Token.hpp.
getString() [2/3]
virtual const XMLCh* Token::getString () const virtual
Reimplemented in StringToken, StringToken, and StringToken.
getString() [3/3]
virtual const XMLCh* Token::getString () const virtual
Reimplemented in StringToken, StringToken, and StringToken.
getTokenType() [1/3]
Token::tokType Token::getTokenType () const inline
Definition at line 148 of file Token.hpp.
References fTokenType.
getTokenType() [2/3]
tokType Token::getTokenType () const
getTokenType() [3/3]
tokType Token::getTokenType () const
intersectRanges() [1/3]
void Token::intersectRanges (RangeToken *const tok) inline virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
Definition at line 250 of file Token.hpp.
References fMemoryManager, XMLExcepts::Regex_NotSupported, and ThrowXMLwithMemMgr.
intersectRanges() [2/3]
virtual void Token::intersectRanges (RangeToken *const tok) virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
intersectRanges() [3/3]
virtual void Token::intersectRanges (RangeToken *const tok) virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
isSet() [1/3]
bool Token::isSet (const int options, const unsigned int flag) inline private
Definition at line 209 of file Token.hpp.
isSet() [2/3]
bool Token::isSet (const int options, const unsigned int flag) private
isSet() [3/3]
bool Token::isSet (const int options, const unsigned int flag) private
isShorterThan() [1/3]
bool Token::isShorterThan (Token *const tok) private
isShorterThan() [2/3]
bool Token::isShorterThan (Token *const tok) private
isShorterThan() [3/3]
bool Token::isShorterThan (Token *const tok) private
mergeRanges() [1/3]
void Token::mergeRanges (const Token *const tok) inline virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
Definition at line 230 of file Token.hpp.
References fMemoryManager, XMLExcepts::Regex_NotSupported, and ThrowXMLwithMemMgr.
mergeRanges() [2/3]
virtual void Token::mergeRanges (const Token *const tok) virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
mergeRanges() [3/3]
virtual void Token::mergeRanges (const Token *const tok) virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
operator=() [1/3]
Token& Token::operator= (const Token &) private
operator=() [2/3]
Token& Token::operator= (const Token &) private
operator=() [3/3]
Token& Token::operator= (const Token &) private
setMax() [1/3]
void Token::setMax (const int maxVal) inline virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
Definition at line 201 of file Token.hpp.
setMax() [2/3]
virtual void Token::setMax (const int maxVal) virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
setMax() [3/3]
virtual void Token::setMax (const int maxVal) virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
setMin() [1/3]
void Token::setMin (const int minVal) inline virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
Definition at line 205 of file Token.hpp.
setMin() [2/3]
virtual void Token::setMin (const int minVal) virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
setMin() [3/3]
virtual void Token::setMin (const int minVal) virtual
Reimplemented in ClosureToken, ClosureToken, and ClosureToken.
setTokenType() [1/3]
void Token::setTokenType (const tokType tokType) inline
Definition at line 196 of file Token.hpp.
References fTokenType.
setTokenType() [2/3]
void Token::setTokenType (const tokType tokType)
setTokenType() [3/3]
void Token::setTokenType (const tokType tokType)
size() [1/3]
XMLSize_t Token::size () const inline virtual
Reimplemented in UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, and ClosureToken.
Definition at line 153 of file Token.hpp.
Referenced by RegularExpression::compileConcat(), and RegularExpression::compileUnion().
size() [2/3]
virtual XMLSize_t Token::size () const virtual
Reimplemented in UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, and ClosureToken.
size() [3/3]
virtual XMLSize_t Token::size () const virtual
Reimplemented in UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, ClosureToken, UnionToken, ParenToken, ConcatToken, and ClosureToken.
sortRanges() [1/3]
void Token::sortRanges () inline virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
Definition at line 235 of file Token.hpp.
References fMemoryManager, XMLExcepts::Regex_NotSupported, and ThrowXMLwithMemMgr.
sortRanges() [2/3]
virtual void Token::sortRanges () virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
sortRanges() [3/3]
virtual void Token::sortRanges () virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
subtractRanges() [1/3]
void Token::subtractRanges (RangeToken *const tok) inline virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
Definition at line 245 of file Token.hpp.
References fMemoryManager, XMLExcepts::Regex_NotSupported, and ThrowXMLwithMemMgr.
subtractRanges() [2/3]
virtual void Token::subtractRanges (RangeToken *const tok) virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
subtractRanges() [3/3]
virtual void Token::subtractRanges (RangeToken *const tok) virtual
Reimplemented in RangeToken, RangeToken, and RangeToken.
Member Data Documentation
fMemoryManager
MemoryManager *const Token::fMemoryManager protected
Definition at line 141 of file Token.hpp.
Referenced by addChild(), addRange(), compactRanges(), intersectRanges(), mergeRanges(), sortRanges(), and subtractRanges().
fTokenType
tokType Token::fTokenType private
Definition at line 139 of file Token.hpp.
Referenced by getTokenType(), and setTokenType().
UTF16_MAX
static const XMLInt32 Token::UTF16_MAX static
Definition at line 71 of file Token.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/util/regx/Token.hpp