Seamly2D: src/test/CollectionTest/tst_seamly2dcommandline.cpp File Reference
tst_seamly2dcommandline.cpp File Reference
#include "tst_seamly2dcommandline.h"
#include "../vmisc/vsysexits.h"
#include "../vmisc/logging.h"
#include <QtTest>
Variables
const QString tmpTestFolder = QStringLiteral("tst_seamly2d_tmp")
const QString tmpTestCollectionFolder = QStringLiteral("tst_seamly2d_collection_tmp")
Variable Documentation
tmpTestCollectionFolder
const QString tmpTestCollectionFolder = QStringLiteral("tst_seamly2d_collection_tmp")
Definition at line 63 of file tst_seamly2dcommandline.cpp.
Referenced by TST_Seamly2DCommandLine::cleanupTestCase(), TST_Seamly2DCommandLine::initTestCase(), TST_Seamly2DCommandLine::TestOpenCollection(), and TST_Seamly2DCommandLine::TestOpenCollection_data().
tmpTestFolder
const QString tmpTestFolder = QStringLiteral("tst_seamly2d_tmp")
Definition at line 62 of file tst_seamly2dcommandline.cpp.
Referenced by TST_Seamly2DCommandLine::cleanupTestCase(), TST_Seamly2DCommandLine::ExportMode(), TST_Seamly2DCommandLine::ExportMode_data(), TST_Seamly2DCommandLine::initTestCase(), TST_Seamly2DCommandLine::OpenPatterns(), TST_Seamly2DCommandLine::TestMode(), and TST_Seamly2DCommandLine::TestMode_data().