Seamly2D: VDxfPaintDevice Class Reference
VDxfPaintDevice Class Reference
#include <vdxfpaintdevice.h>
Public Member Functions
VDxfPaintDevice ()
virtual ~VDxfPaintDevice () Q_DECL_OVERRIDE
virtual QPaintEngine * paintEngine () const Q_DECL_OVERRIDE
QString getFileName () const
void setFileName (const QString &value)
QSize getSize ()
void setSize (const QSize &size)
double getResolution () const
void setResolution (double dpi)
DRW::Version GetVersion () const
void SetVersion (DRW::Version version)
void SetBinaryFormat (bool binary)
bool IsBinaryFormat () const
void setMeasurement (const VarMeasurement &var)
void setInsunits (const VarInsunits &var)
bool ExportToAAMA (const QVector< VLayoutPiece > &details) const
Protected Member Functions
virtual int metric (PaintDeviceMetric metric) const Q_DECL_OVERRIDE
Private Attributes
VDxfEngine * engine
QString fileName
Detailed Description
Definition at line 44 of file vdxfpaintdevice.h.
Constructor & Destructor Documentation
VDxfPaintDevice()
VDxfPaintDevice::VDxfPaintDevice ()
Definition at line 37 of file vdxfpaintdevice.cpp.
~VDxfPaintDevice()
VDxfPaintDevice::~VDxfPaintDevice () virtual
Definition at line 43 of file vdxfpaintdevice.cpp.
References engine.
Member Function Documentation
ExportToAAMA()
bool VDxfPaintDevice::ExportToAAMA (const QVector< VLayoutPiece > & details) const
Definition at line 166 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::ExportToAAMA().
Referenced by MainWindowsNoGUI::AAMADxfFile().
getFileName()
QString VDxfPaintDevice::getFileName () const
Definition at line 57 of file vdxfpaintdevice.cpp.
References fileName.
getResolution()
double VDxfPaintDevice::getResolution () const
Definition at line 93 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::getResolution().
getSize()
QSize VDxfPaintDevice::getSize ()
Definition at line 76 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::getSize().
GetVersion()
DRW::Version VDxfPaintDevice::GetVersion () const
Definition at line 110 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::GetVersion().
IsBinaryFormat()
bool VDxfPaintDevice::IsBinaryFormat () const
Definition at line 138 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::IsBinaryFormat().
metric()
int VDxfPaintDevice::metric (PaintDeviceMetric metric) const protected virtual
Definition at line 175 of file vdxfpaintdevice.cpp.
References engine, VDxfEngine::getResolution(), and VDxfEngine::getSize().
paintEngine()
QPaintEngine * VDxfPaintDevice::paintEngine () const virtual
Definition at line 50 of file vdxfpaintdevice.cpp.
References engine.
SetBinaryFormat()
void VDxfPaintDevice::SetBinaryFormat (bool binary)
Definition at line 127 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::SetBinaryFormat().
Referenced by MainWindowsNoGUI::AAMADxfFile(), and MainWindowsNoGUI::FlatDxfFile().
setFileName()
void VDxfPaintDevice::setFileName (const QString & value)
Definition at line 63 of file vdxfpaintdevice.cpp.
References engine, fileName, and VDxfEngine::setFileName().
Referenced by MainWindowsNoGUI::AAMADxfFile(), and MainWindowsNoGUI::FlatDxfFile().
setInsunits()
void VDxfPaintDevice::setInsunits (const VarInsunits & var)
Definition at line 155 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::setInsunits().
Referenced by MainWindowsNoGUI::AAMADxfFile(), and MainWindowsNoGUI::FlatDxfFile().
setMeasurement()
void VDxfPaintDevice::setMeasurement (const VarMeasurement & var)
Definition at line 144 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::setMeasurement().
setResolution()
void VDxfPaintDevice::setResolution (double dpi)
Definition at line 99 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::setResolution().
Referenced by MainWindowsNoGUI::AAMADxfFile(), and MainWindowsNoGUI::FlatDxfFile().
setSize()
void VDxfPaintDevice::setSize (const QSize & size)
Definition at line 82 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::setSize().
Referenced by MainWindowsNoGUI::AAMADxfFile(), and MainWindowsNoGUI::FlatDxfFile().
SetVersion()
void VDxfPaintDevice::SetVersion (DRW::Version version)
Definition at line 116 of file vdxfpaintdevice.cpp.
References engine, and VDxfEngine::SetVersion().
Referenced by MainWindowsNoGUI::AAMADxfFile(), and MainWindowsNoGUI::FlatDxfFile().
Member Data Documentation
engine
VDxfEngine* VDxfPaintDevice::engine private
Definition at line 75 of file vdxfpaintdevice.h.
Referenced by ExportToAAMA(), getResolution(), getSize(), GetVersion(), IsBinaryFormat(), metric(), paintEngine(), SetBinaryFormat(), setFileName(), setInsunits(), setMeasurement(), setResolution(), setSize(), SetVersion(), and ~VDxfPaintDevice().
fileName
QString VDxfPaintDevice::fileName private
Definition at line 76 of file vdxfpaintdevice.h.
Referenced by getFileName(), and setFileName().
The documentation for this class was generated from the following files:
src/libs/vdxf/vdxfpaintdevice.h
src/libs/vdxf/vdxfpaintdevice.cpp