Seamly2D: ApplicationME Class Reference
ApplicationME Class Reference
#include <application_me.h>
Public Slots
void processCommandLine ()
Public Member Functions
ApplicationME (int &argc, char **argv)
virtual ~ApplicationME () Q_DECL_OVERRIDE
virtual bool notify (QObject *receiver, QEvent *event) Q_DECL_OVERRIDE
notify Reimplemented from QApplication::notify().
bool isTestMode () const
virtual bool isAppInGUIMode () const Q_DECL_OVERRIDE
isAppInGUIMode little hack that allow to have access to application state from VAbstractApplication class.
TMainWindow * mainWindow ()
QList< TMainWindow * > mainWindows ()
TMainWindow * newMainWindow ()
void initOptions ()
virtual const VTranslateVars * translateVariables () Q_DECL_OVERRIDE
virtual void openSettings () Q_DECL_OVERRIDE
VSeamlyMeSettings * seamlyMeSettings ()
void showDataBase ()
void retranslateGroups ()
void retranslateTables ()
void parseCommandLine (const SocketConnection &connection, const QStringList &arguments)
Public Member Functions inherited from VAbstractApplication
VAbstractApplication (int &argc, char **argv)
virtual ~VAbstractApplication () Q_DECL_OVERRIDE
QString translationsPath (const QString &locale=QString()) const
translationsPath return path to the root directory that contains QM files.
void loadTranslations (const QString &locale)
Unit patternUnit () const
const Unit * patternUnitP () const
void setPatternUnit (const Unit &patternUnit)
MeasurementsType patternType () const
void setPatternType (const MeasurementsType &patternType)
VCommonSettings * Settings ()
getSettings hide settings constructor.
template<typename T >
QString LocaleToString (const T &value)
QGraphicsScene * getCurrentScene () const
void setCurrentScene (QGraphicsScene **value)
VMainGraphicsView * getSceneView () const
void setSceneView (VMainGraphicsView *value)
double toPixel (double val) const
double fromPixel (double pix) const
void setCurrentDocument (VAbstractPattern *doc)
VAbstractPattern * getCurrentDocument () const
void setCurrentData (VContainer *data)
VContainer * getCurrentData () const
bool getOpeningPattern () const
void setOpeningPattern ()
QWidget * getMainWindow () const
void setMainWindow (QWidget *value)
QUndoStack * getUndoStack () const
QString getFilePath () const
void setFilePath (const QString &value)
Protected Member Functions
virtual void initTranslateVariables () Q_DECL_OVERRIDE
virtual bool event (QEvent *e) Q_DECL_OVERRIDE
Private Slots
void newLocalSocketConnection ()
Private Member Functions
void clean ()
Private Attributes
QList< QPointer< TMainWindow > > m_mainWindows
QLocalServer * m_localServer
VTranslateVars * m_trVars
QPointer< MeasurementDatabaseDialog > m_dataBase
bool m_testMode
Additional Inherited Members
Protected Attributes inherited from VAbstractApplication
QUndoStack * undoStack
QWidget * mainWindow
mainWindow pointer to main window. Usefull if need create modal dialog. Without pointer to main window modality doesn't work.
VCommonSettings * settings
settings pointer to settings. Help hide constructor creation settings. Make make code more readable.
QPointer< QTranslator > qtTranslator
QPointer< QTranslator > qtxmlTranslator
QPointer< QTranslator > qtBaseTranslator
QPointer< QTranslator > appTranslator
QPointer< QTranslator > pmsTranslator
Detailed Description
Definition at line 73 of file application_me.h.
Constructor & Destructor Documentation
ApplicationME()
ApplicationME::ApplicationME (int & argc, char ** argv)
Definition at line 250 of file application_me.cpp.
References APP_VERSION_STR, VER_COMPANYDOMAIN_STR, VER_COMPANYNAME_STR, and VER_INTERNALNAME_ME_STR.
~ApplicationME()
ApplicationME::~ApplicationME () virtual
Definition at line 271 of file application_me.cpp.
References m_dataBase, m_mainWindows, and m_trVars.
Member Function Documentation
clean()
void ApplicationME::clean () private
Definition at line 769 of file application_me.cpp.
References m_mainWindows.
Referenced by event(), mainWindow(), and mainWindows().
event()
bool ApplicationME::event (QEvent * e) protected virtual
Definition at line 448 of file application_me.cpp.
References clean(), TMainWindow::LoadFile(), and mainWindow().
Referenced by notify().
initOptions()
void ApplicationME::initOptions ()
Definition at line 397 of file application_me.cpp.
References APP_VERSION_STR, buildCompatibilityString(), VCommonSettings::getDefaultIndividualSizePath(), VCommonSettings::getDefaultLabelTemplatePath(), VCommonSettings::getDefaultMultisizePath(), VCommonSettings::getDefaultTemplatePath(), VAbstractApplication::loadTranslations(), noisyFailureMsgHandler(), openSettings(), seamlyMeSettings(), and VAbstractApplication::settings.
Referenced by main().
initTranslateVariables()
void ApplicationME::initTranslateVariables () protected virtual
Implements VAbstractApplication.
Definition at line 435 of file application_me.cpp.
References m_trVars, and VTranslateVars::Retranslate().
isAppInGUIMode()
bool ApplicationME::isAppInGUIMode () const virtual
isAppInGUIMode little hack that allow to have access to application state from VAbstractApplication class.
Implements VAbstractApplication.
Definition at line 368 of file application_me.cpp.
References isTestMode().
isTestMode()
bool ApplicationME::isTestMode () const
Definition at line 359 of file application_me.cpp.
References m_testMode.
Referenced by isAppInGUIMode().
mainWindow()
TMainWindow * ApplicationME::mainWindow ()
Definition at line 374 of file application_me.cpp.
References clean(), m_mainWindows, and newMainWindow().
Referenced by event(), newLocalSocketConnection(), and parseCommandLine().
mainWindows()
QList< TMainWindow * > ApplicationME::mainWindows ()
Definition at line 385 of file application_me.cpp.
References clean(), and m_mainWindows.
Referenced by retranslateTables().
newLocalSocketConnection
void ApplicationME::newLocalSocketConnection () private slot
Definition at line 749 of file application_me.cpp.
References m_localServer, mainWindow(), parseCommandLine(), and Server.
Referenced by parseCommandLine().
newMainWindow()
TMainWindow * ApplicationME::newMainWindow ()
Definition at line 731 of file application_me.cpp.
References m_mainWindows, and qApp.
Referenced by mainWindow(), and parseCommandLine().
notify()
bool ApplicationME::notify (QObject * receiver, QEvent * event) virtual
notify Reimplemented from QApplication::notify().
Parameters
receiver receiver.
event event.
Returns
value that is returned from the receiver's event handler.
Definition at line 294 of file application_me.cpp.
References VExceptionObjectError::DetailedInformation(), VExceptionObjectError::ErrorMessage(), event(), V_EX_DATAERR, V_EX_SOFTWARE, and VException::what().
openSettings()
void ApplicationME::openSettings () virtual
Implements VAbstractApplication.
Definition at line 488 of file application_me.cpp.
References VAbstractApplication::settings.
Referenced by initOptions().
parseCommandLine()
void ApplicationME::parseCommandLine (const SocketConnection & connection, const QStringList & arguments)
Definition at line 537 of file application_me.cpp.
References Client, Cm, MeasurementVariable::IsGradationHeightValid(), MeasurementVariable::IsGradationSizeValid(), LONG_OPTION_NO_HDPI_SCALING, m_localServer, m_testMode, mainWindow(), newLocalSocketConnection(), newMainWindow(), qApp, TMainWindow::SetBaseMHeight(), TMainWindow::SetBaseMSize(), TMainWindow::SetPUnit(), StrToUnits(), unitCM, unitINCH, unitMM, V_EX_OK, V_EX_USAGE, MeasurementVariable::WholeListHeights(), and MeasurementVariable::WholeListSizes().
Referenced by newLocalSocketConnection(), and processCommandLine().
processCommandLine
void ApplicationME::processCommandLine () slot
Definition at line 743 of file application_me.cpp.
References Client, and parseCommandLine().
Referenced by main().
retranslateGroups()
void ApplicationME::retranslateGroups ()
Definition at line 518 of file application_me.cpp.
References m_dataBase.
retranslateTables()
void ApplicationME::retranslateTables ()
Definition at line 527 of file application_me.cpp.
References mainWindows().
seamlyMeSettings()
VSeamlyMeSettings * ApplicationME::seamlyMeSettings ()
Definition at line 495 of file application_me.cpp.
References SCASSERT, and VAbstractApplication::settings.
Referenced by initOptions().
showDataBase()
void ApplicationME::showDataBase ()
Definition at line 502 of file application_me.cpp.
References m_dataBase.
translateVariables()
const VTranslateVars * ApplicationME::translateVariables () virtual
Implements VAbstractApplication.
Definition at line 429 of file application_me.cpp.
References m_trVars.
Member Data Documentation
m_dataBase
QPointer<MeasurementDatabaseDialog> ApplicationME::m_dataBase private
Definition at line 117 of file application_me.h.
Referenced by retranslateGroups(), showDataBase(), and ~ApplicationME().
m_localServer
QLocalServer* ApplicationME::m_localServer private
Definition at line 115 of file application_me.h.
Referenced by newLocalSocketConnection(), and parseCommandLine().
m_mainWindows
QList<QPointer<TMainWindow> > ApplicationME::m_mainWindows private
Definition at line 114 of file application_me.h.
Referenced by clean(), mainWindow(), mainWindows(), newMainWindow(), and ~ApplicationME().
m_testMode
bool ApplicationME::m_testMode private
Definition at line 118 of file application_me.h.
Referenced by isTestMode(), and parseCommandLine().
m_trVars
VTranslateVars* ApplicationME::m_trVars private
Definition at line 116 of file application_me.h.
Referenced by initTranslateVariables(), translateVariables(), and ~ApplicationME().
The documentation for this class was generated from the following files:
src/app/seamlyme/application_me.h
src/app/seamlyme/application_me.cpp