Seamly2D: TST_VLayoutDetail Class Reference
TST_VLayoutDetail Class Reference
#include <tst_vlayoutdetail.h>
Public Member Functions
TST_VLayoutDetail (QObject *parent=nullptr)
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Private Slots
void RemoveDublicates () const
Private Member Functions
void Case1 () const
QVector< QPointF > InputPointsCase1 () const
QVector< QPointF > OutputPointsCase1 () const
void Case2 () const
QVector< QPointF > InputPointsCase2 () const
QVector< QPointF > OutputPointsCase2 () const
void Case3 () const
QVector< QPointF > InputPointsCase3 () const
QVector< QPointF > OutputPointsCase3 () const
Additional Inherited Members
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Detailed Description
Definition at line 57 of file tst_vlayoutdetail.h.
Constructor & Destructor Documentation
TST_VLayoutDetail()
TST_VLayoutDetail::TST_VLayoutDetail (QObject * parent = nullptr) explicit
Definition at line 58 of file tst_vlayoutdetail.cpp.
Member Function Documentation
Case1()
void TST_VLayoutDetail::Case1 () const private
Definition at line 77 of file tst_vlayoutdetail.cpp.
References AbstractTest::Comparison(), VLayoutPiece::getContourPoints(), InputPointsCase1(), OutputPointsCase1(), and VLayoutPiece::SetCountourPoints().
Referenced by RemoveDublicates().
Case2()
void TST_VLayoutDetail::Case2 () const private
Definition at line 140 of file tst_vlayoutdetail.cpp.
References AbstractTest::Comparison(), VLayoutPiece::getContourPoints(), InputPointsCase2(), OutputPointsCase2(), and VLayoutPiece::SetCountourPoints().
Referenced by RemoveDublicates().
Case3()
void TST_VLayoutDetail::Case3 () const private
Definition at line 181 of file tst_vlayoutdetail.cpp.
References AbstractTest::Comparison(), VLayoutPiece::getContourPoints(), InputPointsCase3(), OutputPointsCase3(), and VLayoutPiece::SetCountourPoints().
Referenced by RemoveDublicates().
InputPointsCase1()
QVector< QPointF > TST_VLayoutDetail::InputPointsCase1 () const private
Definition at line 88 of file tst_vlayoutdetail.cpp.
Referenced by Case1().
InputPointsCase2()
QVector< QPointF > TST_VLayoutDetail::InputPointsCase2 () const private
Definition at line 150 of file tst_vlayoutdetail.cpp.
Referenced by Case2().
InputPointsCase3()
QVector< QPointF > TST_VLayoutDetail::InputPointsCase3 () const private
Definition at line 191 of file tst_vlayoutdetail.cpp.
Referenced by Case3().
OutputPointsCase1()
QVector< QPointF > TST_VLayoutDetail::OutputPointsCase1 () const private
Definition at line 114 of file tst_vlayoutdetail.cpp.
Referenced by Case1().
OutputPointsCase2()
QVector< QPointF > TST_VLayoutDetail::OutputPointsCase2 () const private
Definition at line 167 of file tst_vlayoutdetail.cpp.
Referenced by Case2().
OutputPointsCase3()
QVector< QPointF > TST_VLayoutDetail::OutputPointsCase3 () const private
Definition at line 201 of file tst_vlayoutdetail.cpp.
Referenced by Case3().
RemoveDublicates
void TST_VLayoutDetail::RemoveDublicates () const private slot
Definition at line 64 of file tst_vlayoutdetail.cpp.
References Case1(), Case2(), and Case3().
The documentation for this class was generated from the following files:
src/test/Seamly2DTest/tst_vlayoutdetail.h
src/test/Seamly2DTest/tst_vlayoutdetail.cpp