Seamly2D: PreferencesGraphicsViewPage Class Reference
PreferencesGraphicsViewPage Class Reference
#include <preferencesgraphicsviewpage.h>
Public Member Functions
PreferencesGraphicsViewPage (QWidget *parent=nullptr)
virtual ~PreferencesGraphicsViewPage ()
void Apply ()
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
Private Attributes
Ui::PreferencesGraphicsViewPage * ui
bool m_zrbPositiveColorChanged
bool m_zrbNegativeColorChanged
bool m_pointNameColorChanged
bool m_pointNameHoverColorChanged
bool m_orginAxisColorChanged
bool m_primarySupportColorChanged
bool m_secondarySupportColorChanged
bool m_tertiarySupportColorChanged
Detailed Description
Definition at line 35 of file preferencesgraphicsviewpage.h.
Constructor & Destructor Documentation
PreferencesGraphicsViewPage()
PreferencesGraphicsViewPage::PreferencesGraphicsViewPage (QWidget * parent = nullptr) explicit
Definition at line 47 of file preferencesgraphicsviewpage.cpp.
References qApp, and VAbstractTool::supportColorsList().
~PreferencesGraphicsViewPage()
PreferencesGraphicsViewPage::~PreferencesGraphicsViewPage () virtual
Definition at line 266 of file preferencesgraphicsviewpage.cpp.
References ui.
Member Function Documentation
Apply()
void PreferencesGraphicsViewPage::Apply ()
Definition at line 282 of file preferencesgraphicsviewpage.cpp.
References m_orginAxisColorChanged, m_pointNameColorChanged, m_pointNameHoverColorChanged, m_primarySupportColorChanged, m_secondarySupportColorChanged, m_tertiarySupportColorChanged, m_zrbNegativeColorChanged, m_zrbPositiveColorChanged, qApp, VCommonSettings::setAxisOrginColor(), VCommonSettings::setConstrainModKey(), VCommonSettings::setConstrainValue(), VCommonSettings::setExportQuality(), VSettings::SetGraphicalOutput(), VCommonSettings::setGuiFont(), VCommonSettings::setGuiFontSize(), VCommonSettings::setLabelFont(), VCommonSettings::setPanActiveSpaceKey(), VCommonSettings::setPointNameColor(), VCommonSettings::setPointNameFont(), VCommonSettings::setPointNameHoverColor(), VCommonSettings::setPointNameSize(), VCommonSettings::setPrimarySupportColor(), VCommonSettings::setScrollBarWidth(), VCommonSettings::setScrollDuration(), VCommonSettings::setScrollSpeedFactor(), VCommonSettings::setScrollUpdateInterval(), VCommonSettings::setSecondarySupportColor(), VCommonSettings::setShowArcToolBar(), VCommonSettings::setShowCurveToolBar(), VCommonSettings::setShowDetailsToolBar(), VCommonSettings::setShowLayoutToolBar(), VCommonSettings::setShowLineToolBar(), VCommonSettings::setShowOpsToolBar(), VCommonSettings::setShowPieceToolBar(), VCommonSettings::setShowPointToolBar(), VCommonSettings::setShowScrollBars(), VCommonSettings::setShowToolsToolBar(), VCommonSettings::setTertiarySupportColor(), VCommonSettings::setToolBarStyle(), VCommonSettings::setZoomDoubleClick(), VCommonSettings::setZoomModKey(), VCommonSettings::setZoomRBNegativeColor(), VCommonSettings::setZoomRBPositiveColor(), VCommonSettings::setZoomSpeedFactor(), and ui.
Referenced by DialogPreferences::Apply().
changeEvent()
void PreferencesGraphicsViewPage::changeEvent (QEvent * event) protected virtual
Definition at line 272 of file preferencesgraphicsviewpage.cpp.
References ui.
Member Data Documentation
m_orginAxisColorChanged
bool PreferencesGraphicsViewPage::m_orginAxisColorChanged private
Definition at line 55 of file preferencesgraphicsviewpage.h.
Referenced by Apply().
m_pointNameColorChanged
bool PreferencesGraphicsViewPage::m_pointNameColorChanged private
Definition at line 53 of file preferencesgraphicsviewpage.h.
Referenced by Apply().
m_pointNameHoverColorChanged
bool PreferencesGraphicsViewPage::m_pointNameHoverColorChanged private
Definition at line 54 of file preferencesgraphicsviewpage.h.
Referenced by Apply().
m_primarySupportColorChanged
bool PreferencesGraphicsViewPage::m_primarySupportColorChanged private
Definition at line 56 of file preferencesgraphicsviewpage.h.
Referenced by Apply().
m_secondarySupportColorChanged
bool PreferencesGraphicsViewPage::m_secondarySupportColorChanged private
Definition at line 57 of file preferencesgraphicsviewpage.h.
Referenced by Apply().
m_tertiarySupportColorChanged
bool PreferencesGraphicsViewPage::m_tertiarySupportColorChanged private
Definition at line 58 of file preferencesgraphicsviewpage.h.
Referenced by Apply().
m_zrbNegativeColorChanged
bool PreferencesGraphicsViewPage::m_zrbNegativeColorChanged private
Definition at line 52 of file preferencesgraphicsviewpage.h.
Referenced by Apply().
m_zrbPositiveColorChanged
bool PreferencesGraphicsViewPage::m_zrbPositiveColorChanged private
Definition at line 51 of file preferencesgraphicsviewpage.h.
Referenced by Apply().
ui
Ui::PreferencesGraphicsViewPage* PreferencesGraphicsViewPage::ui private
Definition at line 50 of file preferencesgraphicsviewpage.h.
Referenced by Apply(), changeEvent(), and ~PreferencesGraphicsViewPage().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/configpages/preferencesgraphicsviewpage.h
src/app/seamly2d/dialogs/configpages/preferencesgraphicsviewpage.cpp