Seamly2D: VToolTriangle Class Reference
VToolTriangle Class Reference
The VToolTriangle class for tool that find point intersection two foots right triangle (triangle with 90 degree).
#include <vtooltriangle.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::Triangle) }
Public Types inherited from VToolSinglePoint
enum { Type = UserType + static_cast<int>(Tool::SinglePoint) }
Public Types inherited from VScenePoint
enum { Type = UserType + static_cast<int>(Vis::ScenePoint) }
Public Member Functions
virtual void setDialog () Q_DECL_OVERRIDE
setDialog set dialog when user want change tool option.
virtual int type () const Q_DECL_OVERRIDE
QString AxisP1Name () const
QString AxisP2Name () const
QString FirstPointName () const
QString SecondPointName () const
quint32 GetAxisP1Id () const
void SetAxisP1Id (const quint32 &value)
quint32 GetAxisP2Id () const
void SetAxisP2Id (const quint32 &value)
quint32 GetFirstPointId () const
void SetFirstPointId (const quint32 &value)
quint32 GetSecondPointId () const
void SetSecondPointId (const quint32 &value)
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
Public Member Functions inherited from VToolSinglePoint
VToolSinglePoint (VAbstractPattern *doc, VContainer *data, quint32 id, const QColor &lineColor, QGraphicsItem *parent=nullptr)
VToolSinglePoint constructor.
virtual ~VToolSinglePoint () Q_DECL_EQ_DEFAULT
QString name () const
void setName (const QString &name)
void SetEnabled (bool enabled)
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
virtual bool isPointNameVisible (quint32 id) const Q_DECL_OVERRIDE
virtual void setPointNameVisiblity (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void setPointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractPoint
VAbstractPoint (VAbstractPattern *doc, VContainer *data, quint32 id)
virtual ~VAbstractPoint () Q_DECL_EQ_DEFAULT
virtual QString getTagName () const Q_DECL_OVERRIDE
template<typename T >
void ShowToolVisualization (bool show)
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual void setLineWeight (const QString &value)
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Public Member Functions inherited from VScenePoint
VScenePoint (const QColor &lineColor, QGraphicsItem *parent=nullptr)
virtual ~VScenePoint ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
virtual void refreshPointGeometry (const VPointF &point)
void refreshLeader ()
Static Public Member Functions
static VToolTriangle * Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Create help create tool from GUI.
static VToolTriangle * Create (const quint32 _id, const QString &pointName, quint32 axisP1Id, quint32 axisP2Id, quint32 firstPointId, quint32 secondPointId, qreal mx, qreal my, bool showPointName, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation)
Create help create tool.
static QPointF FindPoint (const QPointF &axisP1, const QPointF &axisP2, const QPointF &firstPoint, const QPointF &secondPoint)
FindPoint find point intersection two foots right triangle.
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString ToolType = QStringLiteral("triangle")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Slots
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID) Q_DECL_OVERRIDE
contextMenuEvent handle context menu events.
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Protected Member Functions
virtual void RemoveReferens () Q_DECL_OVERRIDE
RemoveReferens decrement value of reference.
virtual void SaveDialog (QDomElement &domElement) Q_DECL_OVERRIDE
SaveDialog save options into file after change in dialog.
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
virtual void ReadToolAttributes (const QDomElement &domElement) Q_DECL_OVERRIDE
virtual void SetVisualization () Q_DECL_OVERRIDE
Protected Member Functions inherited from VToolSinglePoint
virtual void updatePointNameVisibility (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void updatePointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
updatePointNamePosition save new position text to the pattern file.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
mouseReleaseEvent handle mouse release events.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) Q_DECL_OVERRIDE
itemChange hadle item change.
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyReleaseEvent handle key release events.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractPoint
void SetPointName (quint32 id, const QString &name)
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialogChange () Q_DECL_FINAL
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
void SaveOption (QSharedPointer< VGObject > &obj)
virtual QString makeToolTip () const
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
virtual void ToolCreation (const Source &typeCreation)
Protected Member Functions inherited from VScenePoint
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
void setOnlyPoint (bool value)
bool isOnlyPoint () const
void setPointColor (const QString &value)
Private Member Functions
VToolTriangle (VAbstractPattern *doc, VContainer *data, const quint32 &id, const quint32 &axisP1Id, const quint32 &axisP2Id, const quint32 &firstPointId, const quint32 &secondPointId, const Source &typeCreation, QGraphicsItem *parent=nullptr)
VToolTriangle constructor.
Private Attributes
quint32 axisP1Id
axisP1Id id first axis point.
quint32 axisP2Id
axisP2Id id second axis point.
quint32 firstPointId
firstPointId id first triangle point, what lies on the hypotenuse.
quint32 secondPointId
secondPointId id second triangle point, what lies on the hypotenuse.
Additional Inherited Members
Public Slots inherited from VToolSinglePoint
void pointnameChangedPosition (const QPointF &pos)
pointnameChangedPosition handle change position point text.
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
void pointChosen ()
void pointSelected (bool selected)
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
void allowTextHover (bool enabled)
void allowTextSelectable (bool enabled)
virtual void ToolSelectionType (const SelectionType &type) Q_DECL_OVERRIDE
Public Slots inherited from VAbstractPoint
virtual void ShowTool (quint32 id, bool enable) Q_DECL_OVERRIDE
ShowTool highlight tool.
void deletePoint ()
Public Slots inherited from VDrawTool
virtual void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Static Protected Member Functions inherited from VAbstractPoint
template<typename T >
static void InitToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Protected Attributes inherited from VScenePoint
VGraphicsSimpleTextItem * m_pointName
VScaledLine * m_pointLeader
namePoint point text.
QColor m_pointColor
pointL line that we see if Text is moved too away from point.
bool m_onlyPoint
m_pointColor color of point.
bool m_isHovered
bool m_showPointName
Detailed Description
The VToolTriangle class for tool that find point intersection two foots right triangle (triangle with 90 degree).
Definition at line 74 of file vtooltriangle.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 92 of file vtooltriangle.h.
Constructor & Destructor Documentation
VToolTriangle()
VToolTriangle::VToolTriangle (VAbstractPattern * doc, VContainer * data, const quint32 & id, const quint32 & axisP1Id, const quint32 & axisP2Id, const quint32 & firstPointId, const quint32 & secondPointId, const Source & typeCreation, QGraphicsItem * parent = nullptr) private
VToolTriangle constructor.
Parameters
doc dom document container.
data container with variables.
id object id in container.
axisP1Id id first axis point.
axisP2Id id second axis point.
firstPointId id first triangle point, what lies on the hypotenuse.
secondPointId id second triangle point, what lies on the hypotenuse.
typeCreation way we create this tool.
parent parent object.
Definition at line 95 of file vtooltriangle.cpp.
References VAbstractTool::ToolCreation().
Referenced by Create().
Member Function Documentation
AxisP1Name()
QString VToolTriangle::AxisP1Name () const
Definition at line 267 of file vtooltriangle.cpp.
References axisP1Id, VDataTool::data, and VContainer::GetGObject().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolTriangle(), and VToolOptionsPropertyBrowser::updateOptionsToolTriangle().
AxisP2Name()
QString VToolTriangle::AxisP2Name () const
Definition at line 273 of file vtooltriangle.cpp.
References axisP2Id, VDataTool::data, and VContainer::GetGObject().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolTriangle(), and VToolOptionsPropertyBrowser::updateOptionsToolTriangle().
Create() [1/2]
VToolTriangle * VToolTriangle::Create (const quint32 _id, const QString & pointName, quint32 axisP1Id, quint32 axisP2Id, quint32 firstPointId, quint32 secondPointId, qreal mx, qreal my, bool showPointName, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation) static
Create help create tool.
Parameters
_id tool id, 0 if tool doesn't exist yet.
pointName point name.
axisP1Id id first axis point.
axisP2Id id second axis point.
firstPointId id first triangle point, what lies on the hypotenuse.
secondPointId id second triangle point, what lies on the hypotenuse.
mx label bias x axis.
my label bias y axis.
showPointName show/hide point name text.
scene pointer to scene.
doc dom document container.
data container with variables.
parse parser file mode.
typeCreation way we create this tool.
Returns
the created tool
Definition at line 172 of file vtooltriangle.cpp.
References VContainer::AddGObject(), VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), axisP1Id, axisP2Id, VDataTool::data, VAbstractTool::doc, FindPoint(), firstPointId, FromGui, FullParse, VContainer::GeometricObject(), VAbstractPattern::IncrementReferens(), VAbstractPoint::InitToolConnections(), secondPointId, VPointF::setShowPointName(), Triangle, VContainer::UpdateGObject(), VAbstractPattern::UpdateToolData(), and VToolTriangle().
Create() [2/2]
VToolTriangle * VToolTriangle::Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data) static
Create help create tool from GUI.
Parameters
dialog dialog.
scene pointer to scene.
doc dom document container.
data container with variables.
Returns
the created tool
Definition at line 133 of file vtooltriangle.cpp.
References axisP1Id, axisP2Id, VDataTool::data, VAbstractTool::doc, firstPointId, FromGui, FullParse, VInteractiveTool::m_dialog, SCASSERT, and secondPointId.
Referenced by VPattern::ParseToolTriangle().
FindPoint()
QPointF VToolTriangle::FindPoint (const QPointF & axisP1, const QPointF & axisP2, const QPointF & firstPoint, const QPointF & secondPoint) static
FindPoint find point intersection two foots right triangle.
Parameters
axisP1 first axis point.
axisP2 second axis point.
firstPoint first triangle point, what lies on the hypotenuse.
secondPoint second triangle point, what lies on the hypotenuse.
Returns
point intersection two foots right triangle.
Definition at line 227 of file vtooltriangle.cpp.
References VFuzzyComparePossibleNulls().
Referenced by Create(), VisToolTriangle::RefreshGeometry(), and TST_FindPoint::TestTriangle().
FirstPointName()
QString VToolTriangle::FirstPointName () const
Definition at line 279 of file vtooltriangle.cpp.
References VDataTool::data, firstPointId, and VContainer::GetGObject().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolTriangle(), and VToolOptionsPropertyBrowser::updateOptionsToolTriangle().
GetAxisP1Id()
quint32 VToolTriangle::GetAxisP1Id () const
Definition at line 439 of file vtooltriangle.cpp.
References axisP1Id.
GetAxisP2Id()
quint32 VToolTriangle::GetAxisP2Id () const
Definition at line 421 of file vtooltriangle.cpp.
References axisP2Id.
GetFirstPointId()
quint32 VToolTriangle::GetFirstPointId () const
Definition at line 403 of file vtooltriangle.cpp.
References firstPointId.
GetSecondPointId()
quint32 VToolTriangle::GetSecondPointId () const
Definition at line 379 of file vtooltriangle.cpp.
References secondPointId.
ReadToolAttributes()
void VToolTriangle::ReadToolAttributes (const QDomElement & domElement) protected virtual
Implements VDrawTool.
Definition at line 354 of file vtooltriangle.cpp.
References AttrAxisP1, AttrAxisP2, AttrFirstPoint, AttrSecondPoint, axisP1Id, axisP2Id, VAbstractTool::doc, firstPointId, VDomDocument::GetParametrUInt(), NULL_ID_STR, and secondPointId.
RemoveReferens()
void VToolTriangle::RemoveReferens () protected virtual
RemoveReferens decrement value of reference.
Reimplemented from VAbstractTool.
Definition at line 294 of file vtooltriangle.cpp.
References axisP1Id, axisP2Id, VDataTool::data, VAbstractPattern::DecrementReferens(), VAbstractTool::doc, firstPointId, VContainer::GetGObject(), and secondPointId.
SaveDialog()
void VToolTriangle::SaveDialog (QDomElement & domElement) protected virtual
SaveDialog save options into file after change in dialog.
Implements VDrawTool.
Definition at line 329 of file vtooltriangle.cpp.
References AttrAxisP1, AttrAxisP2, AttrFirstPoint, AttrName, AttrSecondPoint, VAbstractTool::doc, VInteractiveTool::m_dialog, SCASSERT, and VDomDocument::SetAttribute().
SaveOptions()
void VToolTriangle::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VToolSinglePoint.
Definition at line 342 of file vtooltriangle.cpp.
References AttrAxisP1, AttrAxisP2, AttrFirstPoint, AttrSecondPoint, AttrType, axisP1Id, axisP2Id, VAbstractTool::doc, firstPointId, VToolSinglePoint::SaveOptions(), secondPointId, VDomDocument::SetAttribute(), and ToolType.
SecondPointName()
QString VToolTriangle::SecondPointName () const
Definition at line 285 of file vtooltriangle.cpp.
References VDataTool::data, VContainer::GetGObject(), and secondPointId.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolTriangle(), and VToolOptionsPropertyBrowser::updateOptionsToolTriangle().
SetAxisP1Id()
void VToolTriangle::SetAxisP1Id (const quint32 & value)
Definition at line 445 of file vtooltriangle.cpp.
References axisP1Id, VDataTool::data, VContainer::GetGObject(), VAbstractTool::m_id, NULL_ID, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolTriangle().
SetAxisP2Id()
void VToolTriangle::SetAxisP2Id (const quint32 & value)
Definition at line 427 of file vtooltriangle.cpp.
References axisP2Id, VDataTool::data, VContainer::GetGObject(), VAbstractTool::m_id, NULL_ID, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolTriangle().
setDialog()
void VToolTriangle::setDialog () virtual
setDialog set dialog when user want change tool option.
Reimplemented from VInteractiveTool.
Definition at line 111 of file vtooltriangle.cpp.
References axisP1Id, axisP2Id, VDataTool::data, firstPointId, VContainer::GeometricObject(), VInteractiveTool::m_dialog, VAbstractTool::m_id, SCASSERT, and secondPointId.
SetFirstPointId()
void VToolTriangle::SetFirstPointId (const quint32 & value)
Definition at line 409 of file vtooltriangle.cpp.
References VDataTool::data, firstPointId, VContainer::GetGObject(), VAbstractTool::m_id, NULL_ID, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolTriangle().
SetSecondPointId()
void VToolTriangle::SetSecondPointId (const quint32 & value)
Definition at line 385 of file vtooltriangle.cpp.
References VDataTool::data, VContainer::GetGObject(), VAbstractTool::m_id, NULL_ID, VDrawTool::SaveOption(), and secondPointId.
Referenced by VToolOptionsPropertyBrowser::changeDataToolTriangle().
SetVisualization()
void VToolTriangle::SetVisualization () protected virtual
Implements VAbstractTool.
Definition at line 363 of file vtooltriangle.cpp.
References axisP1Id, axisP2Id, firstPointId, VisToolTriangle::RefreshGeometry(), SCASSERT, secondPointId, VisToolTriangle::setHypotenuseP1Id(), VisToolTriangle::setHypotenuseP2Id(), Visualization::setObject1Id(), VisToolTriangle::setObject2Id(), and VAbstractTool::vis.
showContextMenu
void VToolTriangle::showContextMenu (QGraphicsSceneContextMenuEvent * event, quint32 id = NULL_ID) protected virtual slot
contextMenuEvent handle context menu events.
Parameters
event context menu event.
Definition at line 312 of file vtooltriangle.cpp.
ShowVisualization()
void VToolTriangle::ShowVisualization (bool show) virtual
Implements VAbstractTool.
Definition at line 397 of file vtooltriangle.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolTriangle().
type()
virtual int VToolTriangle::type () const inline virtual
Reimplemented from VToolSinglePoint.
Definition at line 91 of file vtooltriangle.h.
References Type.
Member Data Documentation
axisP1Id
quint32 VToolTriangle::axisP1Id private
axisP1Id id first axis point.
Definition at line 125 of file vtooltriangle.h.
Referenced by AxisP1Name(), Create(), GetAxisP1Id(), ReadToolAttributes(), RemoveReferens(), SaveOptions(), SetAxisP1Id(), setDialog(), and SetVisualization().
axisP2Id
quint32 VToolTriangle::axisP2Id private
axisP2Id id second axis point.
Definition at line 128 of file vtooltriangle.h.
Referenced by AxisP2Name(), Create(), GetAxisP2Id(), ReadToolAttributes(), RemoveReferens(), SaveOptions(), SetAxisP2Id(), setDialog(), and SetVisualization().
firstPointId
quint32 VToolTriangle::firstPointId private
firstPointId id first triangle point, what lies on the hypotenuse.
Definition at line 131 of file vtooltriangle.h.
Referenced by Create(), FirstPointName(), GetFirstPointId(), ReadToolAttributes(), RemoveReferens(), SaveOptions(), setDialog(), SetFirstPointId(), and SetVisualization().
secondPointId
quint32 VToolTriangle::secondPointId private
secondPointId id second triangle point, what lies on the hypotenuse.
Definition at line 134 of file vtooltriangle.h.
Referenced by Create(), GetSecondPointId(), ReadToolAttributes(), RemoveReferens(), SaveOptions(), SecondPointName(), setDialog(), SetSecondPointId(), and SetVisualization().
ToolType
const QString VToolTriangle::ToolType = QStringLiteral("triangle") static
Definition at line 90 of file vtooltriangle.h.
Referenced by VPattern::ParsePointElement(), and SaveOptions().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtooltriangle.h
src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtooltriangle.cpp