Seamly2D: VExceptionToolWasDeleted Class Reference
VExceptionToolWasDeleted Class Reference
#include <vexception.h>
Public Member Functions
VExceptionToolWasDeleted (const QString &error)
VExceptionToolWasDeleted (const VExceptionToolWasDeleted &e)
VExceptionToolWasDeleted & operator= (const VExceptionToolWasDeleted &e)
virtual ~VExceptionToolWasDeleted () Q_DECL_EQ_DEFAULT
virtual Q_NORETURN void raise () const Q_DECL_OVERRIDE
raise method raise for exception
virtual VExceptionToolWasDeleted * clone () const Q_DECL_OVERRIDE
clone clone exception
Public Member Functions inherited from VException
VException (const QString &error)
VException constructor exception.
VException (const VException &e)
VException copy constructor.
VException & operator= (const VException &e)
virtual ~VException () Q_DECL_EQ_DEFAULT
virtual QString ErrorMessage () const
ErrorMessage return main error message.
virtual QString DetailedInformation () const
DetailedInformation return detailed information about error.
QString WhatUtf8 () const
What return string with error.
void AddMoreInformation (const QString &info)
AddMoreInformation add more information for error.
QString MoreInformation () const
MoreInformation return more information for error.
virtual const char * what () const Q_DECL_OVERRIDE
Additional Inherited Members
Protected Member Functions inherited from VException
QString MoreInfo (const QString &detInfo) const
Protected Attributes inherited from VException
QString error
error string with error
QString moreInfo
moreInfo more information about error
Detailed Description
Definition at line 117 of file vexception.h.
Constructor & Destructor Documentation
VExceptionToolWasDeleted() [1/2]
VExceptionToolWasDeleted::VExceptionToolWasDeleted (const QString & error) explicit
Definition at line 167 of file vexception.cpp.
Referenced by clone().
VExceptionToolWasDeleted() [2/2]
VExceptionToolWasDeleted::VExceptionToolWasDeleted (const VExceptionToolWasDeleted & e)
Definition at line 173 of file vexception.cpp.
~VExceptionToolWasDeleted()
virtual VExceptionToolWasDeleted::~VExceptionToolWasDeleted () virtual
Member Function Documentation
clone()
VExceptionToolWasDeleted * VExceptionToolWasDeleted::clone () const virtual
clone clone exception
Returns
new exception
Reimplemented from VException.
Definition at line 200 of file vexception.cpp.
References VExceptionToolWasDeleted().
operator=()
VExceptionToolWasDeleted & VExceptionToolWasDeleted::operator= (const VExceptionToolWasDeleted & e)
Definition at line 179 of file vexception.cpp.
References VException::operator=().
raise()
Q_NORETURN void VExceptionToolWasDeleted::raise () const virtual
raise method raise for exception
Reimplemented from VException.
Definition at line 194 of file vexception.cpp.
The documentation for this class was generated from the following files:
src/libs/ifc/exception/vexception.h
src/libs/ifc/exception/vexception.cpp