Seamly2D: anonymous_namespace{vabstractpattern.cpp} Namespace Reference
anonymous_namespace{vabstractpattern.cpp} Namespace Reference
Functions
void ReadExpressionAttribute (QVector< VFormulaField > &expressions, const QDomElement &element, const QString &attribute)
Function Documentation
ReadExpressionAttribute()
void anonymous_namespace{vabstractpattern.cpp}::ReadExpressionAttribute (QVector< VFormulaField > & expressions, const QDomElement & element, const QString & attribute)
Definition at line 236 of file vabstractpattern.cpp.
References VFormulaField::attribute, VFormulaField::element, VFormulaField::expression, and VDomDocument::GetParametrString().
Referenced by VAbstractPattern::ListArcExpressions(), VAbstractPattern::ListElArcExpressions(), VAbstractPattern::ListGrainlineExpressions(), VAbstractPattern::ListIncrementExpressions(), VAbstractPattern::ListNodesExpressions(), VAbstractPattern::ListOperationExpressions(), VAbstractPattern::ListPathPointExpressions(), VAbstractPattern::ListPieceExpressions(), and VAbstractPattern::ListPointExpressions().