Seamly2D: VExceptionObjectError Class Reference
VExceptionObjectError Class Reference
The VExceptionObjectError class for exception object error.
#include <vexceptionobjecterror.h>
Public Member Functions
VExceptionObjectError (const QString &what, const QDomElement &domElement)
VExceptionObjectError exception object error.
VExceptionObjectError (const VExceptionObjectError &e)
VExceptionObjectError copy constructor.
VExceptionObjectError & operator= (const VExceptionObjectError &e)
virtual ~VExceptionObjectError () Q_DECL_EQ_DEFAULT
virtual QString ErrorMessage () const Q_DECL_OVERRIDE
ErrorMessage return main error message.
virtual QString DetailedInformation () const Q_DECL_OVERRIDE
DetailedInformation return detailed information about error.
QString TagText () const
TagText return tag text.
QString TagName () const
TagName return tag name.
qint32 LineNumber () const
LineNumber return line number in file.
Public Member Functions inherited from VException
VException (const QString &error)
VException constructor exception.
VException (const VException &e)
VException copy constructor.
VException & operator= (const VException &e)
virtual ~VException () Q_DECL_EQ_DEFAULT
virtual Q_NORETURN void raise () const Q_DECL_OVERRIDE
raise method raise for exception
virtual Q_REQUIRED_RESULT VException * clone () const Q_DECL_OVERRIDE
clone clone exception
QString WhatUtf8 () const
What return string with error.
void AddMoreInformation (const QString &info)
AddMoreInformation add more information for error.
QString MoreInformation () const
MoreInformation return more information for error.
virtual const char * what () const Q_DECL_OVERRIDE
Protected Attributes
QString tagText
tagText tag text
QString tagName
tagName tag name
qint32 lineNumber
lineNumber line number
Protected Attributes inherited from VException
QString error
error string with error
QString moreInfo
moreInfo more information about error
Additional Inherited Members
Protected Member Functions inherited from VException
QString MoreInfo (const QString &detInfo) const
Detailed Description
The VExceptionObjectError class for exception object error.
Definition at line 67 of file vexceptionobjecterror.h.
Constructor & Destructor Documentation
VExceptionObjectError() [1/2]
VExceptionObjectError::VExceptionObjectError (const QString & what, const QDomElement & domElement)
VExceptionObjectError exception object error.
Parameters
what string with error
domElement dom element
Definition at line 65 of file vexceptionobjecterror.cpp.
References lineNumber, tagName, and tagText.
VExceptionObjectError() [2/2]
VExceptionObjectError::VExceptionObjectError (const VExceptionObjectError & e)
VExceptionObjectError copy constructor.
Parameters
e exception
Definition at line 80 of file vexceptionobjecterror.cpp.
~VExceptionObjectError()
virtual VExceptionObjectError::~VExceptionObjectError () virtual
Member Function Documentation
DetailedInformation()
QString VExceptionObjectError::DetailedInformation () const virtual
DetailedInformation return detailed information about error.
Returns
detailed information
Reimplemented from VException.
Definition at line 113 of file vexceptionobjecterror.cpp.
References lineNumber, VException::MoreInfo(), tagName, and tagText.
Referenced by VApplication::notify(), and MApplication::notify().
ErrorMessage()
QString VExceptionObjectError::ErrorMessage () const virtual
ErrorMessage return main error message.
Returns
main error message
Reimplemented from VException.
Definition at line 103 of file vexceptionobjecterror.cpp.
References VException::error.
Referenced by VApplication::notify(), and MApplication::notify().
LineNumber()
qint32 VExceptionObjectError::LineNumber () const inline
LineNumber return line number in file.
Returns
line number
Definition at line 115 of file vexceptionobjecterror.h.
References lineNumber.
Referenced by operator=().
operator=()
VExceptionObjectError & VExceptionObjectError::operator= (const VExceptionObjectError & e)
Definition at line 85 of file vexceptionobjecterror.cpp.
References LineNumber(), lineNumber, VException::operator=(), TagName(), tagName, TagText(), and tagText.
TagName()
QString VExceptionObjectError::TagName () const inline
TagName return tag name.
Returns
tag name
Definition at line 105 of file vexceptionobjecterror.h.
References tagName.
Referenced by operator=().
TagText()
QString VExceptionObjectError::TagText () const inline
TagText return tag text.
Returns
tag text
Definition at line 95 of file vexceptionobjecterror.h.
References tagText.
Referenced by operator=().
Member Data Documentation
lineNumber
qint32 VExceptionObjectError::lineNumber protected
lineNumber line number
Definition at line 87 of file vexceptionobjecterror.h.
Referenced by DetailedInformation(), LineNumber(), operator=(), and VExceptionObjectError().
tagName
QString VExceptionObjectError::tagName protected
tagName tag name
Definition at line 84 of file vexceptionobjecterror.h.
Referenced by DetailedInformation(), operator=(), TagName(), and VExceptionObjectError().
tagText
QString VExceptionObjectError::tagText protected
tagText tag text
Definition at line 81 of file vexceptionobjecterror.h.
Referenced by DetailedInformation(), operator=(), TagText(), and VExceptionObjectError().
The documentation for this class was generated from the following files:
src/libs/ifc/exception/vexceptionobjecterror.h
src/libs/ifc/exception/vexceptionobjecterror.cpp