Seamly2D: ValidationContext Class Reference
ValidationContext Class Reference abstract
#include <ValidationContext.hpp>
Public Member Functions
Virtual destructor for derived classes
virtual ~ValidationContext ()
virtual ~ValidationContext ()
virtual ~ValidationContext ()
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
The ValidationContext Interface
MemoryManager * fMemoryManager
virtual RefHashTableOf< XMLRefInfo > * getIdRefList () const =0
virtual void setIdRefList (RefHashTableOf< XMLRefInfo > *const)=0
virtual void clearIdRefList ()=0
virtual void addId (const XMLCh *const)=0
virtual void addIdRef (const XMLCh *const)=0
virtual void toCheckIdRefList (bool)=0
virtual const NameIdPool< DTDEntityDecl > * getEntityDeclPool () const =0
virtual const NameIdPool< DTDEntityDecl > * setEntityDeclPool (const NameIdPool< DTDEntityDecl > *const)=0
virtual void checkEntity (const XMLCh *const) const =0
virtual DatatypeValidator * getValidatingMemberType () const =0
virtual void setValidatingMemberType (DatatypeValidator *validatingMemberType)=0
virtual bool isPrefixUnknown (XMLCh *)
virtual void setElemStack (ElemStack *)
virtual const XMLCh * getURIForPrefix (XMLCh *)
virtual void setScanner (XMLScanner *)
virtual void setNamespaceScope (NamespaceScope *)
virtual RefHashTableOf< XMLRefInfo > * getIdRefList () const =0
virtual void setIdRefList (RefHashTableOf< XMLRefInfo > *const)=0
virtual void clearIdRefList ()=0
virtual void addId (const XMLCh *const)=0
virtual void addIdRef (const XMLCh *const)=0
virtual void toCheckIdRefList (bool)=0
virtual const NameIdPool< DTDEntityDecl > * getEntityDeclPool () const =0
virtual const NameIdPool< DTDEntityDecl > * setEntityDeclPool (const NameIdPool< DTDEntityDecl > *const)=0
virtual void checkEntity (const XMLCh *const) const =0
virtual DatatypeValidator * getValidatingMemberType () const =0
virtual void setValidatingMemberType (DatatypeValidator *validatingMemberType)=0
virtual bool isPrefixUnknown (XMLCh *)
virtual void setElemStack (ElemStack *)
virtual const XMLCh * getURIForPrefix (XMLCh *)
virtual void setScanner (XMLScanner *)
virtual void setNamespaceScope (NamespaceScope *)
virtual RefHashTableOf< XMLRefInfo > * getIdRefList () const =0
virtual void setIdRefList (RefHashTableOf< XMLRefInfo > *const)=0
virtual void clearIdRefList ()=0
virtual void addId (const XMLCh *const)=0
virtual void addIdRef (const XMLCh *const)=0
virtual void toCheckIdRefList (bool)=0
virtual const NameIdPool< DTDEntityDecl > * getEntityDeclPool () const =0
virtual const NameIdPool< DTDEntityDecl > * setEntityDeclPool (const NameIdPool< DTDEntityDecl > *const)=0
virtual void checkEntity (const XMLCh *const) const =0
virtual DatatypeValidator * getValidatingMemberType () const =0
virtual void setValidatingMemberType (DatatypeValidator *validatingMemberType)=0
virtual bool isPrefixUnknown (XMLCh *)
virtual void setElemStack (ElemStack *)
virtual const XMLCh * getURIForPrefix (XMLCh *)
virtual void setScanner (XMLScanner *)
virtual void setNamespaceScope (NamespaceScope *)
ValidationContext (MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
ValidationContext (MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
ValidationContext (MemoryManager *const memMgr=XMLPlatformUtils::fgMemoryManager)
ValidationContext (const ValidationContext &)
ValidationContext & operator= (const ValidationContext &)
ValidationContext (const ValidationContext &)
ValidationContext & operator= (const ValidationContext &)
ValidationContext (const ValidationContext &)
ValidationContext & operator= (const ValidationContext &)
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 39 of file ValidationContext.hpp.
Constructor & Destructor Documentation
~ValidationContext() [1/3]
virtual ValidationContext::~ValidationContext () inline virtual
virtual destructor
Definition at line 51 of file ValidationContext.hpp.
ValidationContext() [1/6]
ValidationContext::ValidationContext (MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager) inline protected
Hidden Constructors
Definition at line 111 of file ValidationContext.hpp.
ValidationContext() [2/6]
ValidationContext::ValidationContext (const ValidationContext &) private
name Unimplemented copy constructor and operator=
~ValidationContext() [2/3]
virtual ValidationContext::~ValidationContext () inline virtual
virtual destructor
Definition at line 51 of file ValidationContext.hpp.
ValidationContext() [3/6]
ValidationContext::ValidationContext (MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager) inline protected
Hidden Constructors
Definition at line 111 of file ValidationContext.hpp.
ValidationContext() [4/6]
ValidationContext::ValidationContext (const ValidationContext &) private
name Unimplemented copy constructor and operator=
~ValidationContext() [3/3]
virtual ValidationContext::~ValidationContext () inline virtual
virtual destructor
Definition at line 51 of file ValidationContext.hpp.
ValidationContext() [5/6]
ValidationContext::ValidationContext (MemoryManager *const memMgr = XMLPlatformUtils::fgMemoryManager) inline protected
Hidden Constructors
Definition at line 111 of file ValidationContext.hpp.
ValidationContext() [6/6]
ValidationContext::ValidationContext (const ValidationContext &) private
name Unimplemented copy constructor and operator=
Member Function Documentation
addId() [1/3]
virtual void ValidationContext::addId (const XMLCh * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
addId() [2/3]
virtual void ValidationContext::addId (const XMLCh * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
addId() [3/3]
virtual void ValidationContext::addId (const XMLCh * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
addIdRef() [1/3]
virtual void ValidationContext::addIdRef (const XMLCh * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
addIdRef() [2/3]
virtual void ValidationContext::addIdRef (const XMLCh * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
addIdRef() [3/3]
virtual void ValidationContext::addIdRef (const XMLCh * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
checkEntity() [1/3]
virtual void ValidationContext::checkEntity (const XMLCh * const) const pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
checkEntity() [2/3]
virtual void ValidationContext::checkEntity (const XMLCh * const) const pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
checkEntity() [3/3]
virtual void ValidationContext::checkEntity (const XMLCh * const) const pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
clearIdRefList() [1/3]
virtual void ValidationContext::clearIdRefList () pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Referenced by XMLScanner::resetValidationContext().
clearIdRefList() [2/3]
virtual void ValidationContext::clearIdRefList () pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
clearIdRefList() [3/3]
virtual void ValidationContext::clearIdRefList () pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
getEntityDeclPool() [1/3]
virtual const NameIdPool<DTDEntityDecl>* ValidationContext::getEntityDeclPool () const pure virtual
EntityDeclPool
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
getEntityDeclPool() [2/3]
virtual const NameIdPool<DTDEntityDecl>* ValidationContext::getEntityDeclPool () const pure virtual
EntityDeclPool
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
getEntityDeclPool() [3/3]
virtual const NameIdPool<DTDEntityDecl>* ValidationContext::getEntityDeclPool () const pure virtual
EntityDeclPool
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
getIdRefList() [1/3]
virtual RefHashTableOf<XMLRefInfo>* ValidationContext::getIdRefList () const pure virtual
IDRefList
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Referenced by XMLScanner::getIDRefList().
getIdRefList() [2/3]
virtual RefHashTableOf<XMLRefInfo>* ValidationContext::getIdRefList () const pure virtual
IDRefList
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
getIdRefList() [3/3]
virtual RefHashTableOf<XMLRefInfo>* ValidationContext::getIdRefList () const pure virtual
IDRefList
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
getURIForPrefix() [1/3]
virtual const XMLCh* ValidationContext::getURIForPrefix (XMLCh *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 99 of file ValidationContext.hpp.
getURIForPrefix() [2/3]
virtual const XMLCh* ValidationContext::getURIForPrefix (XMLCh *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 99 of file ValidationContext.hpp.
getURIForPrefix() [3/3]
virtual const XMLCh* ValidationContext::getURIForPrefix (XMLCh *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 99 of file ValidationContext.hpp.
getValidatingMemberType() [1/3]
virtual DatatypeValidator* ValidationContext::getValidatingMemberType () const pure virtual
Union datatype handling
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
getValidatingMemberType() [2/3]
virtual DatatypeValidator* ValidationContext::getValidatingMemberType () const pure virtual
Union datatype handling
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
getValidatingMemberType() [3/3]
virtual DatatypeValidator* ValidationContext::getValidatingMemberType () const pure virtual
Union datatype handling
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
isPrefixUnknown() [1/3]
virtual bool ValidationContext::isPrefixUnknown (XMLCh *) inline virtual
QName datatype handling Create default implementations for source code compatibility
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 97 of file ValidationContext.hpp.
isPrefixUnknown() [2/3]
virtual bool ValidationContext::isPrefixUnknown (XMLCh *) inline virtual
QName datatype handling Create default implementations for source code compatibility
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 97 of file ValidationContext.hpp.
isPrefixUnknown() [3/3]
virtual bool ValidationContext::isPrefixUnknown (XMLCh *) inline virtual
QName datatype handling Create default implementations for source code compatibility
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 97 of file ValidationContext.hpp.
operator=() [1/3]
ValidationContext& ValidationContext::operator= (const ValidationContext &) private
operator=() [2/3]
ValidationContext& ValidationContext::operator= (const ValidationContext &) private
operator=() [3/3]
ValidationContext& ValidationContext::operator= (const ValidationContext &) private
setElemStack() [1/3]
virtual void ValidationContext::setElemStack (ElemStack *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 98 of file ValidationContext.hpp.
setElemStack() [2/3]
virtual void ValidationContext::setElemStack (ElemStack *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 98 of file ValidationContext.hpp.
setElemStack() [3/3]
virtual void ValidationContext::setElemStack (ElemStack *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 98 of file ValidationContext.hpp.
setEntityDeclPool() [1/3]
virtual const NameIdPool<DTDEntityDecl>* ValidationContext::setEntityDeclPool (const NameIdPool< DTDEntityDecl > * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Referenced by XMLScanner::getValidationContext(), and XMLScanner::resetValidationContext().
setEntityDeclPool() [2/3]
virtual const NameIdPool<DTDEntityDecl>* ValidationContext::setEntityDeclPool (const NameIdPool< DTDEntityDecl > * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
setEntityDeclPool() [3/3]
virtual const NameIdPool<DTDEntityDecl>* ValidationContext::setEntityDeclPool (const NameIdPool< DTDEntityDecl > * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
setIdRefList() [1/3]
virtual void ValidationContext::setIdRefList (RefHashTableOf< XMLRefInfo > * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
setIdRefList() [2/3]
virtual void ValidationContext::setIdRefList (RefHashTableOf< XMLRefInfo > * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
setIdRefList() [3/3]
virtual void ValidationContext::setIdRefList (RefHashTableOf< XMLRefInfo > * const) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
setNamespaceScope() [1/3]
virtual void ValidationContext::setNamespaceScope (NamespaceScope *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 101 of file ValidationContext.hpp.
setNamespaceScope() [2/3]
virtual void ValidationContext::setNamespaceScope (NamespaceScope *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 101 of file ValidationContext.hpp.
setNamespaceScope() [3/3]
virtual void ValidationContext::setNamespaceScope (NamespaceScope *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 101 of file ValidationContext.hpp.
setScanner() [1/3]
virtual void ValidationContext::setScanner (XMLScanner *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 100 of file ValidationContext.hpp.
setScanner() [2/3]
virtual void ValidationContext::setScanner (XMLScanner *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 100 of file ValidationContext.hpp.
setScanner() [3/3]
virtual void ValidationContext::setScanner (XMLScanner *) inline virtual
Reimplemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Definition at line 100 of file ValidationContext.hpp.
setValidatingMemberType() [1/3]
virtual void ValidationContext::setValidatingMemberType (DatatypeValidator * validatingMemberType) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
setValidatingMemberType() [2/3]
virtual void ValidationContext::setValidatingMemberType (DatatypeValidator * validatingMemberType) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
setValidatingMemberType() [3/3]
virtual void ValidationContext::setValidatingMemberType (DatatypeValidator * validatingMemberType) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
toCheckIdRefList() [1/3]
virtual void ValidationContext::toCheckIdRefList (bool) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
toCheckIdRefList() [2/3]
virtual void ValidationContext::toCheckIdRefList (bool) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
toCheckIdRefList() [3/3]
virtual void ValidationContext::toCheckIdRefList (bool) pure virtual
Implemented in ValidationContextImpl, ValidationContextImpl, and ValidationContextImpl.
Member Data Documentation
fMemoryManager
MemoryManager * ValidationContext::fMemoryManager protected
Definition at line 123 of file ValidationContext.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/ValidationContext.hpp