Seamly2D: EditFormulaDialog Class Reference
EditFormulaDialog Class Reference
The EditFormulaDialog class dialog for editing wrong formula.
#include <edit_formula_dialog.h>
Public Slots
virtual void DialogAccepted () Q_DECL_OVERRIDE
virtual void DialogRejected () Q_DECL_OVERRIDE
virtual void EvalFormula () Q_DECL_OVERRIDE
void valueChanged (int row)
valueChanged show description when current variable changed
void tabChanged (int row)
menu tabChanged
void insertVariable ()
insertVariable insert variable into line edit
void insertValue (QTableWidgetItem *item)
insertValue insert variable into line edit
void measurements ()
measurements show measurements in list
void lineLengths ()
lineLengths show lengths of line variables in list
void arcRadii ()
arcRadii show radii of arc variables in list
void curveAngles ()
curveAngles show angles of curve variables in list
void curveLengths ()
curveLengths show lengths of curve variables in list
void controlPointLengths ()
controlPointLengths show lengths of control point variables in list
void lineAngles ()
lineAngles show angles of line variables in list
void customVariables ()
customVariables show custom variables in list
void functions ()
functions show functions in list
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
EditFormulaDialog (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
virtual ~EditFormulaDialog () Q_DECL_OVERRIDE
QString GetFormula () const
void SetFormula (const QString &value)
void setCheckZero (bool value)
void setCheckLessThanZero (bool value)
void setPostfix (const QString &value)
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void CheckState () Q_DECL_FINAL
CheckState enable, when all is correct, or disable, when something wrong, button ok.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
virtual void resizeEvent (QResizeEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
virtual void ShowVisualization ()
virtual void SaveData ()
SaveData Put dialog data in local variables.
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Slots
void filterVariables (const QString &filter)
Private Member Functions
void initializeVariables ()
template<class key , class val >
void showVariable (const QMap< key, val > &var)
showVariable show variables in list
void showMeasurements (const QMap< QString, QSharedPointer< MeasurementVariable > > &var)
showMeasurements show measurements in table
void showFunctions ()
showFunctions show functions in list
void setDescription (const QString &name, qreal value, const QString &unit, const QString &type, const QString &description)
void clearFormula ()
void undoFormula ()
Private Attributes
Ui::EditFormulaDialog * ui
QString m_formula
QString m_undoFormula
formula string with formula
bool m_checkZero
copy of formula string used to perform undo
bool m_checkLessThanZero
QString m_postfix
bool m_restoreCursor
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
The EditFormulaDialog class dialog for editing wrong formula.
When math parser find in formula error user can try fix issue. Dialog will show all variables that user can use in this formula. Dialog check fixed variant of formula.
Don't implemant button "Apply" for this dialog!!
Definition at line 88 of file edit_formula_dialog.h.
Constructor & Destructor Documentation
EditFormulaDialog()
EditFormulaDialog::EditFormulaDialog (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
Definition at line 111 of file edit_formula_dialog.cpp.
References CheckState(), clearFormula(), filterVariables(), DialogTool::flagFormula, DialogTool::FormulaChanged(), DialogTool::initializeFormulaUi(), DialogTool::initializeOkCancel(), initializeVariables(), insertValue(), insertVariable(), m_restoreCursor, Measurements, ui, and undoFormula().
~EditFormulaDialog()
EditFormulaDialog::~EditFormulaDialog () virtual
Definition at line 160 of file edit_formula_dialog.cpp.
References m_restoreCursor, and ui.
Member Function Documentation
arcRadii
void EditFormulaDialog::arcRadii () slot
arcRadii show radii of arc variables in list
Definition at line 399 of file edit_formula_dialog.cpp.
References VContainer::arcRadiusesData(), DialogTool::data, showVariable(), and ui.
Referenced by tabChanged().
CheckState()
void EditFormulaDialog::CheckState () protected virtual
CheckState enable, when all is correct, or disable, when something wrong, button ok.
Reimplemented from DialogTool.
Definition at line 466 of file edit_formula_dialog.cpp.
References DialogTool::flagFormula, DialogTool::ok_Button, and SCASSERT.
Referenced by EditFormulaDialog().
clearFormula()
void EditFormulaDialog::clearFormula () private
Definition at line 726 of file edit_formula_dialog.cpp.
References ui.
Referenced by EditFormulaDialog().
closeEvent()
void EditFormulaDialog::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 473 of file edit_formula_dialog.cpp.
References DialogTool::closeEvent(), and ui.
controlPointLengths
void EditFormulaDialog::controlPointLengths () slot
controlPointLengths show lengths of control point variables in list
Definition at line 429 of file edit_formula_dialog.cpp.
References VContainer::controlPointLengthsData(), DialogTool::data, showVariable(), and ui.
Referenced by tabChanged().
curveAngles
void EditFormulaDialog::curveAngles () slot
curveAngles show angles of curve variables in list
Definition at line 409 of file edit_formula_dialog.cpp.
References VContainer::curveAnglesData(), DialogTool::data, showVariable(), and ui.
Referenced by tabChanged().
curveLengths
void EditFormulaDialog::curveLengths () slot
curveLengths show lengths of curve variables in list
Definition at line 419 of file edit_formula_dialog.cpp.
References VContainer::curveLengthsData(), DialogTool::data, showVariable(), and ui.
Referenced by tabChanged().
customVariables
void EditFormulaDialog::customVariables () slot
customVariables show custom variables in list
Definition at line 449 of file edit_formula_dialog.cpp.
References DialogTool::data, showVariable(), ui, and VContainer::variablesData().
Referenced by tabChanged().
DialogAccepted
void EditFormulaDialog::DialogAccepted () virtual slot
Definition at line 172 of file edit_formula_dialog.cpp.
References DialogTool::DialogClosed(), m_formula, and ui.
DialogRejected
void EditFormulaDialog::DialogRejected () virtual slot
Definition at line 181 of file edit_formula_dialog.cpp.
References DialogTool::DialogClosed().
EvalFormula
void EditFormulaDialog::EvalFormula () virtual slot
Definition at line 188 of file edit_formula_dialog.cpp.
References DialogTool::Eval(), DialogTool::flagFormula, DialogTool::labelResultCalculation, m_checkLessThanZero, m_checkZero, m_postfix, DialogTool::plainTextEditFormula, and SCASSERT.
filterVariables
void EditFormulaDialog::filterVariables (const QString & filter) private slot
Definition at line 691 of file edit_formula_dialog.cpp.
References ui.
Referenced by EditFormulaDialog().
functions
void EditFormulaDialog::functions () slot
functions show functions in list
Definition at line 459 of file edit_formula_dialog.cpp.
References showFunctions(), and ui.
Referenced by tabChanged().
GetFormula()
QString EditFormulaDialog::GetFormula () const
Definition at line 548 of file edit_formula_dialog.cpp.
References m_formula, and qApp.
Referenced by DialogInternalPath::editAfterSeamAllowanceWidth(), PatternPieceDialog::editAfterSeamAllowanceWidth(), DialogMove::editAngleFormula(), DialogRotation::editAngleFormula(), DialogInternalPath::editBeforeSeamAllowanceWidth(), PatternPieceDialog::editBeforeSeamAllowanceWidth(), DialogInternalPath::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editGrainlineFormula(), DialogMove::editLengthFormula(), PatternPieceDialog::editPatternLabelFormula(), PatternPieceDialog::editPieceLabelFormula(), DialogMove::editRotationFormula(), TMainWindow::Fx(), DialogCurveIntersectAxis::FXAngle(), DialogEndLine::FXAngle(), DialogLineIntersectAxis::FXAngle(), IntersectCirclesDialog::FXCircle1Radius(), IntersectCirclesDialog::FXCircle2Radius(), IntersectCircleTangentDialog::FXCircleRadius(), DialogArc::FXF1(), DialogArcWithLength::FXF1(), DialogEllipticalArc::FXF1(), DialogArc::FXF2(), DialogEllipticalArc::FXF2(), DialogAlongLine::FXLength(), DialogArcWithLength::FXLength(), DialogBisector::FXLength(), DialogCutArc::FXLength(), DialogCutSpline::FXLength(), DialogCutSplinePath::FXLength(), DialogEndLine::FXLength(), DialogNormal::FXLength(), DialogShoulderPoint::FXLength(), DialogArc::FXRadius(), DialogArcWithLength::FXRadius(), DialogPointOfContact::FXRadius(), DialogEllipticalArc::FXRadius1(), DialogEllipticalArc::FXRadius2(), DialogEllipticalArc::FXRotationAngle(), and VFormulaPropertyEditor::onToolButtonClicked().
initializeVariables()
void EditFormulaDialog::initializeVariables () private
Definition at line 554 of file edit_formula_dialog.cpp.
References measurements(), tabChanged(), ui, and valueChanged().
Referenced by EditFormulaDialog().
insertValue
void EditFormulaDialog::insertValue (QTableWidgetItem * item) slot
insertValue insert variable into line edit
Parameters
item chosen item of table widget
Definition at line 345 of file edit_formula_dialog.cpp.
References ColumnName, Functions, and ui.
Referenced by EditFormulaDialog(), and insertVariable().
insertVariable
void EditFormulaDialog::insertVariable () slot
insertVariable insert variable into line edit
Definition at line 335 of file edit_formula_dialog.cpp.
References insertValue(), and ui.
Referenced by EditFormulaDialog().
lineAngles
void EditFormulaDialog::lineAngles () slot
lineAngles show angles of line variables in list
Definition at line 439 of file edit_formula_dialog.cpp.
References DialogTool::data, VContainer::lineAnglesData(), showVariable(), and ui.
Referenced by tabChanged().
lineLengths
void EditFormulaDialog::lineLengths () slot
lineLengths show lengths of line variables in list
Definition at line 389 of file edit_formula_dialog.cpp.
References DialogTool::data, VContainer::lineLengthsData(), showVariable(), and ui.
Referenced by tabChanged().
measurements
void EditFormulaDialog::measurements () slot
measurements show measurements in list
Definition at line 379 of file edit_formula_dialog.cpp.
References DialogTool::data, VContainer::DataMeasurements(), showMeasurements(), and ui.
Referenced by initializeVariables(), tabChanged(), and valueChanged().
resizeEvent()
void EditFormulaDialog::resizeEvent (QResizeEvent * event) protected virtual
Definition at line 509 of file edit_formula_dialog.cpp.
References DialogTool::isInitialized, and qApp.
setCheckLessThanZero()
void EditFormulaDialog::setCheckLessThanZero (bool value)
Definition at line 536 of file edit_formula_dialog.cpp.
References m_checkLessThanZero.
Referenced by DialogInternalPath::editAfterSeamAllowanceWidth(), PatternPieceDialog::editAfterSeamAllowanceWidth(), DialogInternalPath::editBeforeSeamAllowanceWidth(), PatternPieceDialog::editBeforeSeamAllowanceWidth(), DialogInternalPath::editDefaultSeamAllowanceWidth(), and PatternPieceDialog::editDefaultSeamAllowanceWidth().
setCheckZero()
void EditFormulaDialog::setCheckZero (bool value)
Definition at line 530 of file edit_formula_dialog.cpp.
References m_checkZero.
Referenced by PatternPieceDialog::editGrainlineFormula(), PatternPieceDialog::editPatternLabelFormula(), PatternPieceDialog::editPieceLabelFormula(), and VFormulaPropertyEditor::onToolButtonClicked().
setDescription()
void EditFormulaDialog::setDescription (const QString & name, qreal value, const QString & unit, const QString & type, const QString & description) private
Definition at line 575 of file edit_formula_dialog.cpp.
References ui.
Referenced by valueChanged().
SetFormula()
void EditFormulaDialog::SetFormula (const QString & value)
Definition at line 521 of file edit_formula_dialog.cpp.
References m_formula, m_undoFormula, DialogTool::MoveCursorToEnd(), qApp, and ui.
Referenced by DialogInternalPath::editAfterSeamAllowanceWidth(), PatternPieceDialog::editAfterSeamAllowanceWidth(), DialogMove::editAngleFormula(), DialogRotation::editAngleFormula(), DialogInternalPath::editBeforeSeamAllowanceWidth(), PatternPieceDialog::editBeforeSeamAllowanceWidth(), DialogInternalPath::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editGrainlineFormula(), DialogMove::editLengthFormula(), PatternPieceDialog::editPatternLabelFormula(), PatternPieceDialog::editPieceLabelFormula(), DialogMove::editRotationFormula(), TMainWindow::Fx(), DialogCurveIntersectAxis::FXAngle(), DialogEndLine::FXAngle(), DialogLineIntersectAxis::FXAngle(), IntersectCirclesDialog::FXCircle1Radius(), IntersectCirclesDialog::FXCircle2Radius(), IntersectCircleTangentDialog::FXCircleRadius(), DialogArc::FXF1(), DialogArcWithLength::FXF1(), DialogEllipticalArc::FXF1(), DialogArc::FXF2(), DialogEllipticalArc::FXF2(), DialogAlongLine::FXLength(), DialogArcWithLength::FXLength(), DialogBisector::FXLength(), DialogCutArc::FXLength(), DialogCutSpline::FXLength(), DialogCutSplinePath::FXLength(), DialogEndLine::FXLength(), DialogNormal::FXLength(), DialogShoulderPoint::FXLength(), DialogArc::FXRadius(), DialogArcWithLength::FXRadius(), DialogPointOfContact::FXRadius(), DialogEllipticalArc::FXRadius1(), DialogEllipticalArc::FXRadius2(), DialogEllipticalArc::FXRotationAngle(), and VFormulaPropertyEditor::onToolButtonClicked().
setPostfix()
void EditFormulaDialog::setPostfix (const QString & value)
Definition at line 542 of file edit_formula_dialog.cpp.
References m_postfix.
Referenced by DialogInternalPath::editAfterSeamAllowanceWidth(), PatternPieceDialog::editAfterSeamAllowanceWidth(), DialogMove::editAngleFormula(), DialogRotation::editAngleFormula(), DialogInternalPath::editBeforeSeamAllowanceWidth(), PatternPieceDialog::editBeforeSeamAllowanceWidth(), DialogInternalPath::editDefaultSeamAllowanceWidth(), PatternPieceDialog::editDefaultSeamAllowanceWidth(), DialogMove::editLengthFormula(), DialogMove::editRotationFormula(), TMainWindow::Fx(), DialogCurveIntersectAxis::FXAngle(), DialogEndLine::FXAngle(), DialogLineIntersectAxis::FXAngle(), IntersectCirclesDialog::FXCircle1Radius(), IntersectCirclesDialog::FXCircle2Radius(), IntersectCircleTangentDialog::FXCircleRadius(), DialogArc::FXF1(), DialogArcWithLength::FXF1(), DialogEllipticalArc::FXF1(), DialogArc::FXF2(), DialogEllipticalArc::FXF2(), DialogAlongLine::FXLength(), DialogArcWithLength::FXLength(), DialogBisector::FXLength(), DialogCutArc::FXLength(), DialogCutSpline::FXLength(), DialogCutSplinePath::FXLength(), DialogEndLine::FXLength(), DialogNormal::FXLength(), DialogShoulderPoint::FXLength(), DialogArc::FXRadius(), DialogArcWithLength::FXRadius(), DialogPointOfContact::FXRadius(), DialogEllipticalArc::FXRadius1(), DialogEllipticalArc::FXRadius2(), DialogEllipticalArc::FXRotationAngle(), and VFormulaPropertyEditor::onToolButtonClicked().
showEvent()
void EditFormulaDialog::showEvent (QShowEvent * event) protected virtual
showEvent handle when window show
Parameters
event event
Reimplemented from DialogTool.
Definition at line 480 of file edit_formula_dialog.cpp.
References DialogTool::isInitialized, and qApp.
showFunctions()
void EditFormulaDialog::showFunctions () private
showFunctions show functions in list
Definition at line 667 of file edit_formula_dialog.cpp.
References ColumnFullName, ColumnName, qApp, and ui.
Referenced by functions().
showMeasurements()
void EditFormulaDialog::showMeasurements (const QMap< QString, QSharedPointer< MeasurementVariable > > & var) private
showMeasurements show measurements in table
Parameters
var container with measurements
Definition at line 621 of file edit_formula_dialog.cpp.
References ColumnFullName, ColumnName, qApp, DialogTool::toolId, and ui.
Referenced by measurements().
showVariable()
template<class key , class val > void EditFormulaDialog::showVariable (const QMap< key, val > & var) private
showVariable show variables in list
Parameters
var container with variables
Definition at line 588 of file edit_formula_dialog.cpp.
References ColumnFullName, ColumnName, DialogTool::toolId, and ui.
Referenced by arcRadii(), controlPointLengths(), curveAngles(), curveLengths(), customVariables(), lineAngles(), and lineLengths().
tabChanged
void EditFormulaDialog::tabChanged (int row) slot
menu tabChanged
Parameters
row number of row
Definition at line 278 of file edit_formula_dialog.cpp.
References ArcRadii, arcRadii(), controlPointLengths(), CPLengths, CurveAngles, curveAngles(), CurveLengths, curveLengths(), Custom, customVariables(), Functions, functions(), LineAngles, lineAngles(), LineLengths, lineLengths(), Measurements, and measurements().
Referenced by initializeVariables().
undoFormula()
void EditFormulaDialog::undoFormula () private
Definition at line 731 of file edit_formula_dialog.cpp.
References m_undoFormula, and ui.
Referenced by EditFormulaDialog().
valueChanged
void EditFormulaDialog::valueChanged (int row) slot
valueChanged show description when current variable changed
Parameters
row number of row
Definition at line 201 of file edit_formula_dialog.cpp.
References ArcRadii, ColumnName, CurveAngles, CurveLengths, Custom, DialogTool::data, VContainer::DataVariables(), degreeSymbol, Functions, VInternalVariable::GetValue(), VContainer::GetVariable(), LineAngles, LineLengths, Measurements, measurements(), qApp, setDescription(), ui, and UnitsToStr().
Referenced by initializeVariables().
Member Data Documentation
m_checkLessThanZero
bool EditFormulaDialog::m_checkLessThanZero private
Definition at line 135 of file edit_formula_dialog.h.
Referenced by EvalFormula(), and setCheckLessThanZero().
m_checkZero
bool EditFormulaDialog::m_checkZero private
copy of formula string used to perform undo
Definition at line 134 of file edit_formula_dialog.h.
Referenced by EvalFormula(), and setCheckZero().
m_formula
QString EditFormulaDialog::m_formula private
Definition at line 132 of file edit_formula_dialog.h.
Referenced by DialogAccepted(), GetFormula(), and SetFormula().
m_postfix
QString EditFormulaDialog::m_postfix private
Definition at line 136 of file edit_formula_dialog.h.
Referenced by EvalFormula(), and setPostfix().
m_restoreCursor
bool EditFormulaDialog::m_restoreCursor private
Definition at line 137 of file edit_formula_dialog.h.
Referenced by EditFormulaDialog(), and ~EditFormulaDialog().
m_undoFormula
QString EditFormulaDialog::m_undoFormula private
formula string with formula
Definition at line 133 of file edit_formula_dialog.h.
Referenced by SetFormula(), and undoFormula().
ui
Ui::EditFormulaDialog* EditFormulaDialog::ui private
Definition at line 130 of file edit_formula_dialog.h.
Referenced by arcRadii(), clearFormula(), closeEvent(), controlPointLengths(), curveAngles(), curveLengths(), customVariables(), DialogAccepted(), EditFormulaDialog(), filterVariables(), functions(), initializeVariables(), insertValue(), insertVariable(), lineAngles(), lineLengths(), measurements(), setDescription(), SetFormula(), showFunctions(), showMeasurements(), showVariable(), undoFormula(), valueChanged(), and ~EditFormulaDialog().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/support/edit_formula_dialog.h
src/libs/vtools/dialogs/support/edit_formula_dialog.cpp