Seamly2D: anonymous_namespace{vtoolmove.cpp} Namespace Reference
anonymous_namespace{vtoolmove.cpp} Namespace Reference
Functions
QT_WARNING_PUSH QPointF findRotationOrigin (const QVector< SourceItem > objects, const VContainer *data, qreal calcLength, qreal calcAngle)
Function Documentation
findRotationOrigin()
QT_WARNING_PUSH QPointF anonymous_namespace{vtoolmove.cpp}::findRotationOrigin (const QVector< SourceItem > objects, const VContainer * data, qreal calcLength, qreal calcAngle)
Definition at line 106 of file vtoolmove.cpp.
References AllCurves, Arc, CubicBezier, CubicBezierPath, Curve, EllipticalArc, VAbstractCurve::getPoints(), Path, Point, Spline, SplinePath, VPointF::toQPointF(), and Unknown.
Referenced by VToolMove::Create().