Seamly2D: VCommonSettings Class Reference
VCommonSettings Class Reference
#include <vcommonsettings.h>
Public Member Functions
VCommonSettings (Format format, Scope scope, const QString &organization, const QString &application=QString(), QObject *parent=nullptr)
QString getIndividualSizePath () const
void setIndividualSizePath (const QString &value)
QString getMultisizePath () const
void setMultisizePath (const QString &value)
QString getBodyScansPath () const
void setBodyScansPath (const QString &value)
QString getTemplatePath () const
void setTemplatePath (const QString &value)
QString getLabelTemplatePath () const
void SetPathLabelTemplate (const QString &value)
QString getDefaultPatternTemplate () const
void setDefaultPatternTemplate (const QString &text)
QString getDefaultPieceTemplate () const
void setDefaultPieceTemplate (const QString &text)
bool getShowWelcome () const
void setShowWelcome (const bool &value)
bool GetOsSeparator () const
void SetOsSeparator (const bool &value)
bool GetAutosaveState () const
void SetAutosaveState (const bool &value)
int getAutosaveInterval () const
void setAutosaveInterval (const int &value)
bool useModeType () const
void setUseModeType (const bool &value)
bool useLastExportFormat () const
void setUseLastExportFormat (const bool &value)
QString getExportFormat () const
void setExportFormat (const QString &value)
bool GetSendReportState () const
void SetSendReportState (const bool &value)
QString GetLocale () const
void SetLocale (const QString &value)
QString GetPMSystemCode () const
void SetPMSystemCode (const QString &value)
QString GetUnit () const
void SetUnit (const QString &value)
bool getConfirmItemDelete () const
void setConfirmItemDelete (const bool &value)
bool getConfirmFormatRewriting () const
void setConfirmFormatRewriting (const bool &value)
QString getMoveSuffix () const
void setMoveSuffix (const QString &value)
QString getRotateSuffix () const
void setRotateSuffix (const QString &value)
QString getMirrorByAxisSuffix () const
void setMirrorByAxisSuffix (const QString &value)
QString getMirrorByLineSuffix () const
void setMirrorByLineSuffix (const QString &value)
bool getToolBarStyle () const
void setToolBarStyle (const bool &value)
bool getShowToolsToolBar () const
void setShowToolsToolBar (const bool &value)
bool getShowPointToolBar () const
void setShowPointToolBar (const bool &value)
bool getShowLineToolBar () const
void setShowLineToolBar (const bool &value)
bool getShowCurveToolBar () const
void setShowCurveToolBar (const bool &value)
bool getShowArcToolBar () const
void setShowArcToolBar (const bool &value)
bool getShowOpsToolBar () const
void setShowOpsToolBar (const bool &value)
bool getShowPieceToolBar () const
void setShowPieceToolBar (const bool &value)
bool getShowDetailsToolBar () const
void setShowDetailsToolBar (const bool &value)
bool getShowLayoutToolBar () const
void setShowLayoutToolBar (const bool &value)
bool getShowScrollBars () const
void setShowScrollBars (const bool &value)
int getScrollBarWidth () const
void setScrollBarWidth (const int &width)
int getScrollDuration () const
void setScrollDuration (const int &duration)
int getScrollUpdateInterval () const
void setScrollUpdateInterval (const int &interval)
int getScrollSpeedFactor () const
void setScrollSpeedFactor (const int &factor)
bool getZoomModKey () const
void setZoomModKey (const bool &value)
bool isZoomDoubleClick () const
void setZoomDoubleClick (const bool &value)
bool isPanActiveSpaceKey () const
void setPanActiveSpaceKey (const bool &value)
int getZoomSpeedFactor () const
void setZoomSpeedFactor (const int &factor)
int getExportQuality () const
void setExportQuality (const int &value)
QString getZoomRBPositiveColor () const
void setZoomRBPositiveColor (const QString &value)
QString getZoomRBNegativeColor () const
void setZoomRBNegativeColor (const QString &value)
QString getPointNameColor () const
void setPointNameColor (const QString &value)
QString getPointNameHoverColor () const
void setPointNameHoverColor (const QString &value)
QString getAxisOrginColor () const
void setAxisOrginColor (const QString &value)
QString getDefaultLineColor () const
void setDefaultLineColor (const QString &value)
qreal getDefaultLineWeight () const
void setDefaultLineWeight (const qreal &value)
QString getDefaultLineType () const
void setDefaultLineType (const QString &value)
QString getPrimarySupportColor () const
void setPrimarySupportColor (const QString &value)
QString getSecondarySupportColor () const
void setSecondarySupportColor (const QString &value)
QString getTertiarySupportColor () const
void setTertiarySupportColor (const QString &value)
qreal getConstrainValue () const
void setConstrainValue (const qreal &value)
bool getConstrainModKey () const
void setConstrainModKey (const bool &value)
QString getCompanyName () const
void setCompanyName (const QString &value)
QString getContact () const
void setContact (const QString &value)
QString getAddress () const
void setAddress (const QString &value)
QString getCity () const
void setCity (const QString &value)
QString getState () const
void setState (const QString &value)
QString getZipcode () const
void setZipcode (const QString &value)
QString getCountry () const
void setCountry (const QString &value)
QString getTelephone () const
void setTelephone (const QString &value)
QString getFax () const
void setFax (const QString &value)
QString getEmail () const
void setEmail (const QString &value)
QString getWebsite () const
void setWebsite (const QString &value)
int GetUndoCount () const
void SetUndoCount (const int &value)
QString getSound () const
QString getSelectionSound () const
void setSelectionSound (const QString &value)
QStringList GetRecentFileList () const
void SetRecentFileList (const QStringList &value)
QStringList GetRestoreFileList () const
void SetRestoreFileList (const QStringList &value)
QByteArray GetGeometry () const
void SetGeometry (const QByteArray &value)
QByteArray GetWindowState () const
void SetWindowState (const QByteArray &value)
QByteArray GetToolbarsState () const
void SetToolbarsState (const QByteArray &value)
QSize getPreferenceDialogSize () const
void setPreferenceDialogSize (const QSize &sz)
QSize getPatternPieceDialogSize () const
void setPatternPieceDialogSize (const QSize &sz)
QSize GetFormulaWizardDialogSize () const
void SetFormulaWizardDialogSize (const QSize &sz)
QSize GetIncrementsDialogSize () const
void SetIncrementsDialogSize (const QSize &sz)
int GetLatestSkippedVersion () const
void SetLatestSkippedVersion (int value)
QDate GetDateOfLastRemind () const
void SetDateOfLastRemind (const QDate &date)
bool getForbidPieceFlipping () const
void setForbidPieceFlipping (bool value)
bool isHideSeamLine () const
void setHideSeamLine (bool value)
bool showSeamlineNotch () const
void setShowSeamlineNotch (bool value)
bool showSeamAllowanceNotch () const
void setShowSeamAllowanceNotch (bool value)
qreal getDefaultNotchLength () const
void setDefaultNotchLength (const qreal &value)
qreal getDefaultNotchWidth () const
void setDefaultNotchWidth (const qreal &value)
QString getDefaultNotchType () const
void setDefaultNotchType (const QString &value)
QString getDefaultNotchColor () const
void setDefaultNotchColor (const QString &value)
void SetCSVWithHeader (bool withHeader)
bool GetCSVWithHeader () const
bool GetDefCSVWithHeader () const
void SetCSVCodec (int mib)
int GetCSVCodec () const
int GetDefCSVCodec () const
void SetCSVSeparator (const QChar &separator)
QChar GetCSVSeparator () const
QChar GetDefCSVSeparator () const
void SetDefaultSeamAllowance (double value)
double GetDefaultSeamAllowance ()
returns the default seam allowance. The corresponding unit is the default unit.
QString getDefaultSeamColor () const
void setDefaultSeamColor (const QString &value)
QString getDefaultSeamLinetype () const
void setDefaultSeamLinetype (const QString &value)
qreal getDefaultSeamLineweight () const
void setDefaultSeamLineweight (const qreal &value)
QString getDefaultCutColor () const
void setDefaultCutColor (const QString &value)
QString getDefaultCutLinetype () const
void setDefaultCutLinetype (const QString &value)
qreal getDefaultCutLineweight () const
void setDefaultCutLineweight (const qreal &value)
QString getDefaultInternalColor () const
void setDefaultInternalColor (const QString &value)
QString getDefaultInternalLinetype () const
void setDefaultInternalLinetype (const QString &value)
qreal getDefaultInternalLineweight () const
void setDefaultInternalLineweight (const qreal &value)
QString getDefaultCutoutColor () const
void setDefaultCutoutColor (const QString &value)
QString getDefaultCutoutLinetype () const
void setDefaultCutoutLinetype (const QString &value)
qreal getDefaultCutoutLineweight () const
void setDefaultCutoutLineweight (const qreal &value)
bool showSeamAllowances () const
void setShowSeamAllowances (const bool &value)
bool getDefaultSeamAllowanceVisibilty () const
void setDefaultSeamAllowanceVisibilty (const bool &value)
bool showGrainlines () const
void setShowGrainlines (const bool &value)
bool getDefaultGrainlineVisibilty () const
void setDefaultGrainlineVisibilty (const bool &value)
qreal getDefaultGrainlineLength () const
void setDefaultGrainlineLength (const qreal &value)
QString getDefaultGrainlineColor () const
void setDefaultGrainlineColor (const QString &value)
qreal getDefaultGrainlineLineweight () const
void setDefaultGrainlineLineweight (const qreal &value)
bool showLabels () const
void setShowLabels (const bool &value)
bool showPatternLabels () const
void setShowPatternLabels (const bool &value)
bool showPieceLabels () const
void setShowPieceLabels (const bool &value)
qreal getDefaultLabelWidth () const
void setDefaultLabelWidth (const qreal &value)
qreal getDefaultLabelHeight () const
void setDefaultLabelHeight (const qreal &value)
QString getDefaultLabelColor () const
void setDefaultLabelColor (const QString &value)
QFont getLabelFont () const
void setLabelFont (const QFont &f)
QFont getGuiFont () const
void setGuiFont (const QFont &f)
QFont getPointNameFont () const
void setPointNameFont (const QFont &f)
int getPointNameSize () const
void setPointNameSize (int value)
bool getHidePointNames () const
void setHidePointNames (bool value)
bool getShowAxisOrigin () const
void setShowAxisOrigin (bool value)
bool isWireframe () const
void setWireframe (bool value)
bool getShowControlPoints () const
void setShowControlPoints (bool value)
bool getShowAnchorPoints () const
void setShowAnchorPoints (bool value)
bool getUseToolColor () const
void setUseToolColor (bool value)
int getGuiFontSize () const
void setGuiFontSize (int value)
QString GetLabelDateFormat () const
void SetLabelDateFormat (const QString &format)
QStringList GetUserDefinedDateFormats () const
void SetUserDefinedDateFormats (const QStringList &formats)
QString GetLabelTimeFormat () const
void SetLabelTimeFormat (const QString &format)
QStringList GetUserDefinedTimeFormats () const
void SetUserDefinedTimeFormats (const QStringList &formats)
Static Public Member Functions
static QString SharePath (const QString &shareItem)
static QString MultisizeTablesPath ()
static QString StandardTemplatesPath ()
static QString PrepareStandardTemplates (const QString &currentPath)
static QString prepareMultisizeTables (const QString &currentPath)
static QString getDefaultIndividualSizePath ()
static QString getDefaultMultisizePath ()
static QString getDefaultBodyScansPath ()
static QString getDefaultTemplatePath ()
static QString getDefaultLabelTemplatePath ()
static QStringList PredefinedDateFormats ()
static QStringList PredefinedTimeFormats ()
Static Public Attributes
static const QString unixStandardSharePath = QStringLiteral("/usr/share/seamly2d")
Detailed Description
Definition at line 70 of file vcommonsettings.h.
Constructor & Destructor Documentation
VCommonSettings()
VCommonSettings::VCommonSettings (Format format, Scope scope, const QString & organization, const QString & application = QString(), QObject * parent = nullptr)
Definition at line 335 of file vcommonsettings.cpp.
Member Function Documentation
getAddress()
QString VCommonSettings::getAddress () const
Definition at line 1166 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAddress.
getAutosaveInterval()
int VCommonSettings::getAutosaveInterval () const
Definition at line 571 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAutosaveTime.
GetAutosaveState()
bool VCommonSettings::GetAutosaveState () const
Definition at line 559 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAutosaveState.
getAxisOrginColor()
QString VCommonSettings::getAxisOrginColor () const
Definition at line 1038 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewAxisOrginColor.
getBodyScansPath()
QString VCommonSettings::getBodyScansPath () const
Definition at line 478 of file vcommonsettings.cpp.
References commonIniFilename, getDefaultBodyScansPath(), and anonymous_namespace{vcommonsettings.cpp}::settingPathsBodyScans.
Referenced by SeamlyMePreferencesPathPage::initializeTable().
getCity()
QString VCommonSettings::getCity () const
Definition at line 1176 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCity.
getCompanyName()
QString VCommonSettings::getCompanyName () const
Definition at line 1146 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCompanyName.
getConfirmFormatRewriting()
bool VCommonSettings::getConfirmFormatRewriting () const
Definition at line 688 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationConfirmFormatRewriting.
getConfirmItemDelete()
bool VCommonSettings::getConfirmItemDelete () const
Definition at line 676 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationConfirmItemDeletion.
getConstrainModKey()
bool VCommonSettings::getConstrainModKey () const
Definition at line 1134 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewConstrainModKey.
getConstrainValue()
qreal VCommonSettings::getConstrainValue () const
Definition at line 1122 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewConstrainValue.
getContact()
QString VCommonSettings::getContact () const
Definition at line 1156 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationContact.
getCountry()
QString VCommonSettings::getCountry () const
Definition at line 1206 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCountry.
GetCSVCodec()
int VCommonSettings::GetCSVCodec () const
Definition at line 1567 of file vcommonsettings.cpp.
References commonIniFilename, GetDefCSVCodec(), and anonymous_namespace{vcommonsettings.cpp}::settingCSVCodec.
GetCSVSeparator()
QChar VCommonSettings::GetCSVSeparator () const
Definition at line 1601 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingCSVSeparator.
GetCSVWithHeader()
bool VCommonSettings::GetCSVWithHeader () const
Definition at line 1547 of file vcommonsettings.cpp.
References commonIniFilename, GetDefCSVWithHeader(), and anonymous_namespace{vcommonsettings.cpp}::settingCSVWithHeader.
GetDateOfLastRemind()
QDate VCommonSettings::GetDateOfLastRemind () const
Definition at line 1429 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingDateOfLastRemind.
getDefaultBodyScansPath()
QString VCommonSettings::getDefaultBodyScansPath () static
Definition at line 472 of file vcommonsettings.cpp.
Referenced by SeamlyMePreferencesPathPage::defaultPath(), and getBodyScansPath().
getDefaultCutColor()
QString VCommonSettings::getDefaultCutColor () const
Definition at line 1713 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutColor.
getDefaultCutLinetype()
QString VCommonSettings::getDefaultCutLinetype () const
Definition at line 1725 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutLinetype.
getDefaultCutLineweight()
qreal VCommonSettings::getDefaultCutLineweight () const
Definition at line 1737 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutLineweight.
getDefaultCutoutColor()
QString VCommonSettings::getDefaultCutoutColor () const
Definition at line 1785 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutColor.
getDefaultCutoutLinetype()
QString VCommonSettings::getDefaultCutoutLinetype () const
Definition at line 1797 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutLinetype.
getDefaultCutoutLineweight()
qreal VCommonSettings::getDefaultCutoutLineweight () const
Definition at line 1809 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutLineweight.
getDefaultGrainlineColor()
QString VCommonSettings::getDefaultGrainlineColor () const
Definition at line 1881 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineColor.
getDefaultGrainlineLength()
qreal VCommonSettings::getDefaultGrainlineLength () const
Definition at line 1869 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineLength.
getDefaultGrainlineLineweight()
qreal VCommonSettings::getDefaultGrainlineLineweight () const
Definition at line 1893 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineLineweight.
getDefaultGrainlineVisibilty()
bool VCommonSettings::getDefaultGrainlineVisibilty () const
Definition at line 1857 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineVisibilty.
getDefaultIndividualSizePath()
QString VCommonSettings::getDefaultIndividualSizePath () static
Definition at line 409 of file vcommonsettings.cpp.
Referenced by PreferencesPathPage::defaultPath(), SeamlyMePreferencesPathPage::defaultPath(), getIndividualSizePath(), VApplication::InitOptions(), and MApplication::InitOptions().
getDefaultInternalColor()
QString VCommonSettings::getDefaultInternalColor () const
Definition at line 1749 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalColor.
getDefaultInternalLinetype()
QString VCommonSettings::getDefaultInternalLinetype () const
Definition at line 1761 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalLinetype.
getDefaultInternalLineweight()
qreal VCommonSettings::getDefaultInternalLineweight () const
Definition at line 1773 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalLineweight.
getDefaultLabelColor()
QString VCommonSettings::getDefaultLabelColor () const
Definition at line 1965 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelColor.
getDefaultLabelHeight()
qreal VCommonSettings::getDefaultLabelHeight () const
Definition at line 1953 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelHeight.
getDefaultLabelTemplatePath()
QString VCommonSettings::getDefaultLabelTemplatePath () static
Definition at line 493 of file vcommonsettings.cpp.
Referenced by PreferencesPathPage::defaultPath(), getLabelTemplatePath(), VApplication::InitOptions(), and MApplication::InitOptions().
getDefaultLabelWidth()
qreal VCommonSettings::getDefaultLabelWidth () const
Definition at line 1941 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelWidth.
getDefaultLineColor()
QString VCommonSettings::getDefaultLineColor () const
Definition at line 1050 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineColor.
getDefaultLineType()
QString VCommonSettings::getDefaultLineType () const
Definition at line 1074 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineType.
getDefaultLineWeight()
qreal VCommonSettings::getDefaultLineWeight () const
Definition at line 1062 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineWeight.
getDefaultMultisizePath()
QString VCommonSettings::getDefaultMultisizePath () static
Definition at line 430 of file vcommonsettings.cpp.
Referenced by MainWindow::checkPathToMeasurements(), PreferencesPathPage::defaultPath(), SeamlyMePreferencesPathPage::defaultPath(), getMultisizePath(), VApplication::InitOptions(), MApplication::InitOptions(), and prepareMultisizeTables().
getDefaultNotchColor()
QString VCommonSettings::getDefaultNotchColor () const
Definition at line 1528 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchColor.
getDefaultNotchLength()
qreal VCommonSettings::getDefaultNotchLength () const
Definition at line 1492 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchLength.
getDefaultNotchType()
QString VCommonSettings::getDefaultNotchType () const
Definition at line 1516 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchType.
getDefaultNotchWidth()
qreal VCommonSettings::getDefaultNotchWidth () const
Definition at line 1504 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchWidth.
getDefaultPatternTemplate()
QString VCommonSettings::getDefaultPatternTemplate () const
Definition at line 511 of file vcommonsettings.cpp.
References getLabelTemplatePath(), and anonymous_namespace{vcommonsettings.cpp}::settingDefaultPatternTemplate.
Referenced by PreferencesPatternPage::initializeLabelsTab().
getDefaultPieceTemplate()
QString VCommonSettings::getDefaultPieceTemplate () const
Definition at line 523 of file vcommonsettings.cpp.
References getLabelTemplatePath(), and anonymous_namespace{vcommonsettings.cpp}::settingDefaultPieceTemplate.
Referenced by PreferencesPatternPage::initializeLabelsTab().
GetDefaultSeamAllowance()
double VCommonSettings::GetDefaultSeamAllowance ()
returns the default seam allowance. The corresponding unit is the default unit.
Returns
the default seam allowance
Definition at line 1635 of file vcommonsettings.cpp.
References Cm, GetUnit(), Inch, Mm, anonymous_namespace{vcommonsettings.cpp}::settingPatternDefaultSeamAllowance, StrToUnits(), and UnitConvertor().
getDefaultSeamAllowanceVisibilty()
bool VCommonSettings::getDefaultSeamAllowanceVisibilty () const
Definition at line 1833 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamAllowanceVisibilty.
getDefaultSeamColor()
QString VCommonSettings::getDefaultSeamColor () const
Definition at line 1677 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamColor.
getDefaultSeamLinetype()
QString VCommonSettings::getDefaultSeamLinetype () const
Definition at line 1689 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamLinetype.
getDefaultSeamLineweight()
qreal VCommonSettings::getDefaultSeamLineweight () const
Definition at line 1701 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamLineweight.
getDefaultTemplatePath()
QString VCommonSettings::getDefaultTemplatePath () static
Definition at line 451 of file vcommonsettings.cpp.
Referenced by PreferencesPathPage::defaultPath(), SeamlyMePreferencesPathPage::defaultPath(), getTemplatePath(), VApplication::InitOptions(), MApplication::InitOptions(), and PrepareStandardTemplates().
GetDefCSVCodec()
int VCommonSettings::GetDefCSVCodec () const
Definition at line 1574 of file vcommonsettings.cpp.
Referenced by GetCSVCodec().
GetDefCSVSeparator()
QChar VCommonSettings::GetDefCSVSeparator () const
Definition at line 1619 of file vcommonsettings.cpp.
GetDefCSVWithHeader()
bool VCommonSettings::GetDefCSVWithHeader () const
Definition at line 1554 of file vcommonsettings.cpp.
Referenced by GetCSVWithHeader().
getEmail()
QString VCommonSettings::getEmail () const
Definition at line 1236 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationEmail.
getExportFormat()
QString VCommonSettings::getExportFormat () const
Definition at line 615 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationExportFormat.
getExportQuality()
int VCommonSettings::getExportQuality () const
Definition at line 978 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewExportQuality.
Referenced by ExportLayoutDialog::readSettings().
getFax()
QString VCommonSettings::getFax () const
Definition at line 1226 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationFax.
getForbidPieceFlipping()
bool VCommonSettings::getForbidPieceFlipping () const
Definition at line 1444 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternForbidFlipping.
GetFormulaWizardDialogSize()
QSize VCommonSettings::GetFormulaWizardDialogSize () const
Definition at line 1390 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingFormulaWizardDialogSize.
GetGeometry()
QByteArray VCommonSettings::GetGeometry () const
Definition at line 1330 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralGeometry.
Referenced by MainWindow::ReadSettings(), and TMainWindow::ReadSettings().
getGuiFont()
QFont VCommonSettings::getGuiFont () const
Definition at line 1989 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternGuiFont.
getGuiFontSize()
int VCommonSettings::getGuiFontSize () const
Definition at line 2106 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewGuiFontSize.
getHidePointNames()
bool VCommonSettings::getHidePointNames () const
Definition at line 2013 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewHidePointNames.
GetIncrementsDialogSize()
QSize VCommonSettings::GetIncrementsDialogSize () const
Definition at line 1402 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingIncrementsDialogSize.
getIndividualSizePath()
QString VCommonSettings::getIndividualSizePath () const
Definition at line 415 of file vcommonsettings.cpp.
References commonIniFilename, getDefaultIndividualSizePath(), and anonymous_namespace{vcommonsettings.cpp}::settingPathsIndividualMeasurements.
Referenced by PreferencesPathPage::initializeTable(), and SeamlyMePreferencesPathPage::initializeTable().
GetLabelDateFormat()
QString VCommonSettings::GetLabelDateFormat () const
Definition at line 2118 of file vcommonsettings.cpp.
References GetUserDefinedDateFormats(), PredefinedDateFormats(), and anonymous_namespace{vcommonsettings.cpp}::settingLabelDateFormat.
Referenced by PreferencesPatternPage::initializeLabelsTab().
getLabelFont()
QFont VCommonSettings::getLabelFont () const
Definition at line 1977 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternLabelFont.
getLabelTemplatePath()
QString VCommonSettings::getLabelTemplatePath () const
Definition at line 499 of file vcommonsettings.cpp.
References getDefaultLabelTemplatePath(), and anonymous_namespace{vcommonsettings.cpp}::settingPathsLabelTemplate.
Referenced by getDefaultPatternTemplate(), getDefaultPieceTemplate(), PreferencesPathPage::initializeTable(), and PreferencesPatternPage::setDefaultTemplate().
GetLabelTimeFormat()
QString VCommonSettings::GetLabelTimeFormat () const
Definition at line 2178 of file vcommonsettings.cpp.
References GetUserDefinedTimeFormats(), PredefinedTimeFormats(), and anonymous_namespace{vcommonsettings.cpp}::settingLabelTimeFormat.
Referenced by PreferencesPatternPage::initializeLabelsTab().
GetLatestSkippedVersion()
int VCommonSettings::GetLatestSkippedVersion () const
Definition at line 1414 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingLatestSkippedVersion.
GetLocale()
QString VCommonSettings::GetLocale () const
Definition at line 639 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationLocale.
getMirrorByAxisSuffix()
QString VCommonSettings::getMirrorByAxisSuffix () const
Definition at line 725 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMirrorByAxisSuffix.
getMirrorByLineSuffix()
QString VCommonSettings::getMirrorByLineSuffix () const
Definition at line 737 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMirrorByLineSuffix.
getMoveSuffix()
QString VCommonSettings::getMoveSuffix () const
Definition at line 701 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMoveSuffix.
getMultisizePath()
QString VCommonSettings::getMultisizePath () const
Definition at line 436 of file vcommonsettings.cpp.
References commonIniFilename, getDefaultMultisizePath(), and anonymous_namespace{vcommonsettings.cpp}::settingPathsMultisizeMeasurements.
Referenced by PreferencesPathPage::initializeTable(), and SeamlyMePreferencesPathPage::initializeTable().
GetOsSeparator()
bool VCommonSettings::GetOsSeparator () const
Definition at line 547 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationOsSeparator.
Referenced by SeamlyMeWelcomeDialog::apply(), DialogPatternProperties::DialogPatternProperties(), and SeamlyMeWelcomeDialog::SeamlyMeWelcomeDialog().
getPatternPieceDialogSize()
QSize VCommonSettings::getPatternPieceDialogSize () const
Definition at line 1378 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingToolSeamAllowanceDialogSize.
GetPMSystemCode()
QString VCommonSettings::GetPMSystemCode () const
Definition at line 651 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPMSystemCode.
getPointNameColor()
QString VCommonSettings::getPointNameColor () const
Definition at line 1014 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameColor.
getPointNameFont()
QFont VCommonSettings::getPointNameFont () const
Definition at line 2001 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternPointNameFont.
getPointNameHoverColor()
QString VCommonSettings::getPointNameHoverColor () const
Definition at line 1026 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameHoverColor.
getPointNameSize()
int VCommonSettings::getPointNameSize () const
Definition at line 2085 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::pointNameSize, and anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameSize.
getPreferenceDialogSize()
QSize VCommonSettings::getPreferenceDialogSize () const
Definition at line 1366 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPreferenceDialogSize.
getPrimarySupportColor()
QString VCommonSettings::getPrimarySupportColor () const
Definition at line 1086 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPrimaryColor.
GetRecentFileList()
QStringList VCommonSettings::GetRecentFileList () const
Definition at line 1295 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralRecentFileList.
Referenced by MainWindow::setCurrentFile().
GetRestoreFileList()
QStringList VCommonSettings::GetRestoreFileList () const
Definition at line 1318 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralRestoreFileList.
Referenced by MainWindow::setCurrentFile().
getRotateSuffix()
QString VCommonSettings::getRotateSuffix () const
Definition at line 713 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationRotateSuffix.
getScrollBarWidth()
int VCommonSettings::getScrollBarWidth () const
Definition at line 881 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollBarWidth.
getScrollDuration()
int VCommonSettings::getScrollDuration () const
Definition at line 893 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollDuration.
getScrollSpeedFactor()
int VCommonSettings::getScrollSpeedFactor () const
Definition at line 917 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollSpeedFactor.
getScrollUpdateInterval()
int VCommonSettings::getScrollUpdateInterval () const
Definition at line 905 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollUpdateInterval.
getSecondarySupportColor()
QString VCommonSettings::getSecondarySupportColor () const
Definition at line 1098 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewSecondaryColor.
getSelectionSound()
QString VCommonSettings::getSelectionSound () const
Definition at line 1283 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingSelectionSound.
GetSendReportState()
bool VCommonSettings::GetSendReportState () const
Definition at line 627 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationSendReportState.
getShowAnchorPoints()
bool VCommonSettings::getShowAnchorPoints () const
Definition at line 2061 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowAnchorPoints.
getShowArcToolBar()
bool VCommonSettings::getShowArcToolBar () const
Definition at line 809 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowArcToolBar.
getShowAxisOrigin()
bool VCommonSettings::getShowAxisOrigin () const
Definition at line 2025 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowAxisOrigin.
getShowControlPoints()
bool VCommonSettings::getShowControlPoints () const
Definition at line 2049 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowControlPoints.
getShowCurveToolBar()
bool VCommonSettings::getShowCurveToolBar () const
Definition at line 797 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowCurveToolBar.
getShowDetailsToolBar()
bool VCommonSettings::getShowDetailsToolBar () const
Definition at line 845 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowDetailsToolBar.
getShowLayoutToolBar()
bool VCommonSettings::getShowLayoutToolBar () const
Definition at line 857 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowLayoutToolBar.
getShowLineToolBar()
bool VCommonSettings::getShowLineToolBar () const
Definition at line 785 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowLineToolBar.
getShowOpsToolBar()
bool VCommonSettings::getShowOpsToolBar () const
Definition at line 821 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowOpsToolBar.
getShowPieceToolBar()
bool VCommonSettings::getShowPieceToolBar () const
Definition at line 833 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowPieceToolBar.
getShowPointToolBar()
bool VCommonSettings::getShowPointToolBar () const
Definition at line 773 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowPointToolBar.
getShowScrollBars()
bool VCommonSettings::getShowScrollBars () const
Definition at line 869 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowScrollBars.
getShowToolsToolBar()
bool VCommonSettings::getShowToolsToolBar () const
Definition at line 761 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowToolsToolBar.
getShowWelcome()
bool VCommonSettings::getShowWelcome () const
Definition at line 535 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationShowWelcome.
Referenced by SeamlyMeWelcomeDialog::SeamlyMeWelcomeDialog().
getSound()
QString VCommonSettings::getSound () const
Definition at line 1277 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingSelectionSound.
getState()
QString VCommonSettings::getState () const
Definition at line 1186 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationState.
getTelephone()
QString VCommonSettings::getTelephone () const
Definition at line 1216 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationTelephone.
getTemplatePath()
QString VCommonSettings::getTemplatePath () const
Definition at line 457 of file vcommonsettings.cpp.
References commonIniFilename, getDefaultTemplatePath(), and anonymous_namespace{vcommonsettings.cpp}::settingPathsTemplates.
Referenced by PreferencesPathPage::initializeTable(), and SeamlyMePreferencesPathPage::initializeTable().
getTertiarySupportColor()
QString VCommonSettings::getTertiarySupportColor () const
Definition at line 1110 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewTertiaryColor.
GetToolbarsState()
QByteArray VCommonSettings::GetToolbarsState () const
Definition at line 1354 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralToolbarsState.
Referenced by MainWindow::ReadSettings(), and TMainWindow::ReadSettings().
getToolBarStyle()
bool VCommonSettings::getToolBarStyle () const
Definition at line 749 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewToolBarStyle.
GetUndoCount()
int VCommonSettings::GetUndoCount () const
Definition at line 1257 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternUndo.
Referenced by MainWindow::ReadSettings().
GetUnit()
QString VCommonSettings::GetUnit () const
Definition at line 663 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUnit, unitCM, and unitINCH.
Referenced by GetDefaultSeamAllowance(), SeamlyMeWelcomeDialog::initUnits(), and SetDefaultSeamAllowance().
GetUserDefinedDateFormats()
QStringList VCommonSettings::GetUserDefinedDateFormats () const
Definition at line 2166 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingLabelUserDateFormats.
Referenced by DialogPatternProperties::DialogPatternProperties(), PreferencesPatternPage::editDateTimeFormats(), GetLabelDateFormat(), and PreferencesPatternPage::initializeLabelsTab().
GetUserDefinedTimeFormats()
QStringList VCommonSettings::GetUserDefinedTimeFormats () const
Definition at line 2210 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingLabelUserTimeFormats.
Referenced by DialogPatternProperties::DialogPatternProperties(), PreferencesPatternPage::editDateTimeFormats(), GetLabelTimeFormat(), and PreferencesPatternPage::initializeLabelsTab().
getUseToolColor()
bool VCommonSettings::getUseToolColor () const
Definition at line 2073 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsUseToolColor.
getWebsite()
QString VCommonSettings::getWebsite () const
Definition at line 1246 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationWebsite.
GetWindowState()
QByteArray VCommonSettings::GetWindowState () const
Definition at line 1342 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralWindowState.
Referenced by MainWindow::ReadSettings(), and TMainWindow::ReadSettings().
getZipcode()
QString VCommonSettings::getZipcode () const
Definition at line 1196 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationZipcode.
getZoomModKey()
bool VCommonSettings::getZoomModKey () const
Definition at line 930 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomModKey.
getZoomRBNegativeColor()
QString VCommonSettings::getZoomRBNegativeColor () const
Definition at line 1002 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomRBNegativeColor.
getZoomRBPositiveColor()
QString VCommonSettings::getZoomRBPositiveColor () const
Definition at line 990 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomRBPositiveColor.
getZoomSpeedFactor()
int VCommonSettings::getZoomSpeedFactor () const
Definition at line 966 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomSpeedFactor.
isHideSeamLine()
bool VCommonSettings::isHideSeamLine () const
Definition at line 1456 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternHideSeamLine.
isPanActiveSpaceKey()
bool VCommonSettings::isPanActiveSpaceKey () const
Definition at line 954 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPanActiveSpaceKey.
isWireframe()
bool VCommonSettings::isWireframe () const
Definition at line 2037 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewWireframe.
isZoomDoubleClick()
bool VCommonSettings::isZoomDoubleClick () const
Definition at line 942 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomDoubleClick.
MultisizeTablesPath()
QString VCommonSettings::MultisizeTablesPath () static
Definition at line 385 of file vcommonsettings.cpp.
References SharePath().
Referenced by prepareMultisizeTables().
PredefinedDateFormats()
QStringList VCommonSettings::PredefinedDateFormats () static
Definition at line 2140 of file vcommonsettings.cpp.
Referenced by DialogPatternProperties::DialogPatternProperties(), PreferencesPatternPage::editDateTimeFormats(), GetLabelDateFormat(), PreferencesPatternPage::initializeLabelsTab(), and SetUserDefinedDateFormats().
PredefinedTimeFormats()
QStringList VCommonSettings::PredefinedTimeFormats () static
Definition at line 2200 of file vcommonsettings.cpp.
Referenced by DialogPatternProperties::DialogPatternProperties(), PreferencesPatternPage::editDateTimeFormats(), GetLabelTimeFormat(), PreferencesPatternPage::initializeLabelsTab(), and SetUserDefinedTimeFormats().
prepareMultisizeTables()
QString VCommonSettings::prepareMultisizeTables (const QString & currentPath) static
Definition at line 403 of file vcommonsettings.cpp.
References getDefaultMultisizePath(), MultisizeTablesPath(), and anonymous_namespace{vcommonsettings.cpp}::PrepareStandardFiles().
Referenced by MainWindow::checkPathToMeasurements(), PreferencesPathPage::editPath(), SeamlyMePreferencesPathPage::editPath(), TMainWindow::FileSaveAs(), MainWindow::LoadMultisize(), and TMainWindow::OpenMultisize().
PrepareStandardTemplates()
QString VCommonSettings::PrepareStandardTemplates (const QString & currentPath) static
Definition at line 397 of file vcommonsettings.cpp.
References getDefaultTemplatePath(), anonymous_namespace{vcommonsettings.cpp}::PrepareStandardFiles(), and StandardTemplatesPath().
Referenced by TMainWindow::ImportFromPattern(), and TMainWindow::OpenTemplate().
setAddress()
void VCommonSettings::setAddress (const QString & value)
Definition at line 1171 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAddress.
Referenced by PreferencesConfigurationPage::Apply().
setAutosaveInterval()
void VCommonSettings::setAutosaveInterval (const int & value)
Definition at line 585 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAutosaveTime.
Referenced by PreferencesConfigurationPage::Apply().
SetAutosaveState()
void VCommonSettings::SetAutosaveState (const bool & value)
Definition at line 565 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationAutosaveState.
Referenced by PreferencesConfigurationPage::Apply().
setAxisOrginColor()
void VCommonSettings::setAxisOrginColor (const QString & value)
Definition at line 1044 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewAxisOrginColor.
Referenced by PreferencesGraphicsViewPage::Apply().
setBodyScansPath()
void VCommonSettings::setBodyScansPath (const QString & value)
Definition at line 485 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingPathsBodyScans.
Referenced by SeamlyMePreferencesPathPage::Apply().
setCity()
void VCommonSettings::setCity (const QString & value)
Definition at line 1181 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCity.
Referenced by PreferencesConfigurationPage::Apply().
setCompanyName()
void VCommonSettings::setCompanyName (const QString & value)
Definition at line 1151 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCompanyName.
Referenced by PreferencesConfigurationPage::Apply().
setConfirmFormatRewriting()
void VCommonSettings::setConfirmFormatRewriting (const bool & value)
Definition at line 694 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationConfirmFormatRewriting.
Referenced by PreferencesConfigurationPage::Apply().
setConfirmItemDelete()
void VCommonSettings::setConfirmItemDelete (const bool & value)
Definition at line 682 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationConfirmItemDeletion.
Referenced by PreferencesConfigurationPage::Apply().
setConstrainModKey()
void VCommonSettings::setConstrainModKey (const bool & value)
Definition at line 1140 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewConstrainModKey.
Referenced by PreferencesGraphicsViewPage::Apply().
setConstrainValue()
void VCommonSettings::setConstrainValue (const qreal & value)
Definition at line 1128 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewConstrainValue.
Referenced by PreferencesGraphicsViewPage::Apply().
setContact()
void VCommonSettings::setContact (const QString & value)
Definition at line 1161 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationContact.
Referenced by PreferencesConfigurationPage::Apply().
setCountry()
void VCommonSettings::setCountry (const QString & value)
Definition at line 1211 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationCountry.
Referenced by PreferencesConfigurationPage::Apply().
SetCSVCodec()
void VCommonSettings::SetCSVCodec (int mib)
Definition at line 1560 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingCSVCodec.
SetCSVSeparator()
void VCommonSettings::SetCSVSeparator (const QChar & separator)
Definition at line 1580 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingCSVSeparator.
SetCSVWithHeader()
void VCommonSettings::SetCSVWithHeader (bool withHeader)
Definition at line 1540 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingCSVWithHeader.
SetDateOfLastRemind()
void VCommonSettings::SetDateOfLastRemind (const QDate & date)
Definition at line 1436 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingDateOfLastRemind.
setDefaultCutColor()
void VCommonSettings::setDefaultCutColor (const QString & value)
Definition at line 1719 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutColor.
Referenced by PreferencesPatternPage::Apply().
setDefaultCutLinetype()
void VCommonSettings::setDefaultCutLinetype (const QString & value)
Definition at line 1731 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutLinetype.
Referenced by PreferencesPatternPage::Apply().
setDefaultCutLineweight()
void VCommonSettings::setDefaultCutLineweight (const qreal & value)
Definition at line 1743 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutLineweight.
Referenced by PreferencesPatternPage::Apply().
setDefaultCutoutColor()
void VCommonSettings::setDefaultCutoutColor (const QString & value)
Definition at line 1791 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutColor.
Referenced by PreferencesPatternPage::Apply().
setDefaultCutoutLinetype()
void VCommonSettings::setDefaultCutoutLinetype (const QString & value)
Definition at line 1803 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutLinetype.
Referenced by PreferencesPatternPage::Apply().
setDefaultCutoutLineweight()
void VCommonSettings::setDefaultCutoutLineweight (const qreal & value)
Definition at line 1815 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultCutoutLineweight.
Referenced by PreferencesPatternPage::Apply().
setDefaultGrainlineColor()
void VCommonSettings::setDefaultGrainlineColor (const QString & value)
Definition at line 1887 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineColor.
Referenced by PreferencesPatternPage::Apply().
setDefaultGrainlineLength()
void VCommonSettings::setDefaultGrainlineLength (const qreal & value)
Definition at line 1875 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineLength.
Referenced by PreferencesPatternPage::Apply().
setDefaultGrainlineLineweight()
void VCommonSettings::setDefaultGrainlineLineweight (const qreal & value)
Definition at line 1899 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineLineweight.
Referenced by PreferencesPatternPage::Apply().
setDefaultGrainlineVisibilty()
void VCommonSettings::setDefaultGrainlineVisibilty (const bool & value)
Definition at line 1863 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultGrainlineVisibilty.
Referenced by PreferencesPatternPage::Apply().
setDefaultInternalColor()
void VCommonSettings::setDefaultInternalColor (const QString & value)
Definition at line 1755 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalColor.
Referenced by PreferencesPatternPage::Apply().
setDefaultInternalLinetype()
void VCommonSettings::setDefaultInternalLinetype (const QString & value)
Definition at line 1767 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalLinetype.
Referenced by PreferencesPatternPage::Apply().
setDefaultInternalLineweight()
void VCommonSettings::setDefaultInternalLineweight (const qreal & value)
Definition at line 1779 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultInternalLineweight.
Referenced by PreferencesPatternPage::Apply().
setDefaultLabelColor()
void VCommonSettings::setDefaultLabelColor (const QString & value)
Definition at line 1971 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelColor.
Referenced by PreferencesPatternPage::Apply().
setDefaultLabelHeight()
void VCommonSettings::setDefaultLabelHeight (const qreal & value)
Definition at line 1959 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelHeight.
Referenced by PreferencesPatternPage::Apply().
setDefaultLabelWidth()
void VCommonSettings::setDefaultLabelWidth (const qreal & value)
Definition at line 1947 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultLabelWidth.
Referenced by PreferencesPatternPage::Apply().
setDefaultLineColor()
void VCommonSettings::setDefaultLineColor (const QString & value)
Definition at line 1056 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineColor.
setDefaultLineType()
void VCommonSettings::setDefaultLineType (const QString & value)
Definition at line 1080 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineType.
setDefaultLineWeight()
void VCommonSettings::setDefaultLineWeight (const qreal & value)
Definition at line 1068 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewDefaultLineWeight.
setDefaultNotchColor()
void VCommonSettings::setDefaultNotchColor (const QString & value)
Definition at line 1534 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchColor.
Referenced by PreferencesPatternPage::Apply().
setDefaultNotchLength()
void VCommonSettings::setDefaultNotchLength (const qreal & value)
Definition at line 1498 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchLength.
Referenced by PreferencesPatternPage::Apply().
setDefaultNotchType()
void VCommonSettings::setDefaultNotchType (const QString & value)
Definition at line 1522 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchType.
Referenced by PreferencesPatternPage::Apply().
setDefaultNotchWidth()
void VCommonSettings::setDefaultNotchWidth (const qreal & value)
Definition at line 1510 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultNotchWidth.
Referenced by PreferencesPatternPage::Apply().
setDefaultPatternTemplate()
void VCommonSettings::setDefaultPatternTemplate (const QString & text)
Definition at line 517 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultPatternTemplate.
Referenced by PreferencesPatternPage::setDefaultTemplate().
setDefaultPieceTemplate()
void VCommonSettings::setDefaultPieceTemplate (const QString & text)
Definition at line 529 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultPieceTemplate.
Referenced by PreferencesPatternPage::setDefaultTemplate().
SetDefaultSeamAllowance()
void VCommonSettings::SetDefaultSeamAllowance (double value)
Definition at line 1625 of file vcommonsettings.cpp.
References Cm, GetUnit(), anonymous_namespace{vcommonsettings.cpp}::settingPatternDefaultSeamAllowance, StrToUnits(), and UnitConvertor().
Referenced by PreferencesPatternPage::Apply().
setDefaultSeamAllowanceVisibilty()
void VCommonSettings::setDefaultSeamAllowanceVisibilty (const bool & value)
Definition at line 1839 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamAllowanceVisibilty.
Referenced by PreferencesPatternPage::Apply().
setDefaultSeamColor()
void VCommonSettings::setDefaultSeamColor (const QString & value)
Definition at line 1683 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamColor.
Referenced by PreferencesPatternPage::Apply().
setDefaultSeamLinetype()
void VCommonSettings::setDefaultSeamLinetype (const QString & value)
Definition at line 1695 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamLinetype.
Referenced by PreferencesPatternPage::Apply().
setDefaultSeamLineweight()
void VCommonSettings::setDefaultSeamLineweight (const qreal & value)
Definition at line 1707 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingDefaultSeamLineweight.
Referenced by PreferencesPatternPage::Apply().
setEmail()
void VCommonSettings::setEmail (const QString & value)
Definition at line 1241 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationEmail.
Referenced by PreferencesConfigurationPage::Apply().
setExportFormat()
void VCommonSettings::setExportFormat (const QString & value)
Definition at line 621 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationExportFormat.
Referenced by PreferencesConfigurationPage::Apply().
setExportQuality()
void VCommonSettings::setExportQuality (const int & value)
Definition at line 984 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewExportQuality.
Referenced by PreferencesGraphicsViewPage::Apply(), and ExportLayoutDialog::writeSettings().
setFax()
void VCommonSettings::setFax (const QString & value)
Definition at line 1231 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationFax.
Referenced by PreferencesConfigurationPage::Apply().
setForbidPieceFlipping()
void VCommonSettings::setForbidPieceFlipping (bool value)
Definition at line 1450 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternForbidFlipping.
Referenced by PreferencesPatternPage::Apply().
SetFormulaWizardDialogSize()
void VCommonSettings::SetFormulaWizardDialogSize (const QSize & sz)
Definition at line 1396 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingFormulaWizardDialogSize.
SetGeometry()
void VCommonSettings::SetGeometry (const QByteArray & value)
Definition at line 1336 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralGeometry.
Referenced by MainWindow::WriteSettings(), and TMainWindow::WriteSettings().
setGuiFont()
void VCommonSettings::setGuiFont (const QFont & f)
Definition at line 1995 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternGuiFont.
Referenced by PreferencesGraphicsViewPage::Apply().
setGuiFontSize()
void VCommonSettings::setGuiFontSize (int value)
Definition at line 2112 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewGuiFontSize.
Referenced by PreferencesGraphicsViewPage::Apply().
setHidePointNames()
void VCommonSettings::setHidePointNames (bool value)
Definition at line 2019 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewHidePointNames.
setHideSeamLine()
void VCommonSettings::setHideSeamLine (bool value)
Definition at line 1462 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternHideSeamLine.
Referenced by PreferencesPatternPage::Apply().
SetIncrementsDialogSize()
void VCommonSettings::SetIncrementsDialogSize (const QSize & sz)
Definition at line 1408 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingIncrementsDialogSize.
setIndividualSizePath()
void VCommonSettings::setIndividualSizePath (const QString & value)
Definition at line 422 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingPathsIndividualMeasurements.
Referenced by PreferencesPathPage::Apply(), and SeamlyMePreferencesPathPage::Apply().
SetLabelDateFormat()
void VCommonSettings::SetLabelDateFormat (const QString & format)
Definition at line 2134 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingLabelDateFormat.
Referenced by PreferencesPatternPage::Apply().
setLabelFont()
void VCommonSettings::setLabelFont (const QFont & f)
Definition at line 1983 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternLabelFont.
Referenced by PreferencesGraphicsViewPage::Apply().
SetLabelTimeFormat()
void VCommonSettings::SetLabelTimeFormat (const QString & format)
Definition at line 2194 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingLabelTimeFormat.
Referenced by PreferencesPatternPage::Apply().
SetLatestSkippedVersion()
void VCommonSettings::SetLatestSkippedVersion (int value)
Definition at line 1421 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingLatestSkippedVersion.
SetLocale()
void VCommonSettings::SetLocale (const QString & value)
Definition at line 645 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationLocale.
Referenced by PreferencesConfigurationPage::Apply(), SeamlyMePreferencesConfigurationPage::Apply(), and SeamlyMeWelcomeDialog::apply().
setMirrorByAxisSuffix()
void VCommonSettings::setMirrorByAxisSuffix (const QString & value)
Definition at line 731 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMirrorByAxisSuffix.
Referenced by PreferencesConfigurationPage::Apply().
setMirrorByLineSuffix()
void VCommonSettings::setMirrorByLineSuffix (const QString & value)
Definition at line 743 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMirrorByLineSuffix.
Referenced by PreferencesConfigurationPage::Apply().
setMoveSuffix()
void VCommonSettings::setMoveSuffix (const QString & value)
Definition at line 707 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationMoveSuffix.
Referenced by PreferencesConfigurationPage::Apply().
setMultisizePath()
void VCommonSettings::setMultisizePath (const QString & value)
Definition at line 443 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingPathsMultisizeMeasurements.
Referenced by PreferencesPathPage::Apply(), and SeamlyMePreferencesPathPage::Apply().
SetOsSeparator()
void VCommonSettings::SetOsSeparator (const bool & value)
Definition at line 553 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationOsSeparator.
Referenced by PreferencesConfigurationPage::Apply(), SeamlyMePreferencesConfigurationPage::Apply(), and SeamlyMeWelcomeDialog::apply().
setPanActiveSpaceKey()
void VCommonSettings::setPanActiveSpaceKey (const bool & value)
Definition at line 960 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPanActiveSpaceKey.
Referenced by PreferencesGraphicsViewPage::Apply().
SetPathLabelTemplate()
void VCommonSettings::SetPathLabelTemplate (const QString & value)
Definition at line 505 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPathsLabelTemplate.
Referenced by PreferencesPathPage::Apply().
setPatternPieceDialogSize()
void VCommonSettings::setPatternPieceDialogSize (const QSize & sz)
Definition at line 1384 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingToolSeamAllowanceDialogSize.
SetPMSystemCode()
void VCommonSettings::SetPMSystemCode (const QString & value)
Definition at line 657 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPMSystemCode.
Referenced by SeamlyMePreferencesConfigurationPage::Apply().
setPointNameColor()
void VCommonSettings::setPointNameColor (const QString & value)
Definition at line 1020 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameColor.
Referenced by PreferencesGraphicsViewPage::Apply().
setPointNameFont()
void VCommonSettings::setPointNameFont (const QFont & f)
Definition at line 2007 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternPointNameFont.
Referenced by PreferencesGraphicsViewPage::Apply().
setPointNameHoverColor()
void VCommonSettings::setPointNameHoverColor (const QString & value)
Definition at line 1032 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameHoverColor.
Referenced by PreferencesGraphicsViewPage::Apply().
setPointNameSize()
void VCommonSettings::setPointNameSize (int value)
Definition at line 2100 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::pointNameSize, and anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPointNameSize.
Referenced by PreferencesGraphicsViewPage::Apply().
setPreferenceDialogSize()
void VCommonSettings::setPreferenceDialogSize (const QSize & sz)
Definition at line 1372 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPreferenceDialogSize.
setPrimarySupportColor()
void VCommonSettings::setPrimarySupportColor (const QString & value)
Definition at line 1092 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewPrimaryColor.
Referenced by PreferencesGraphicsViewPage::Apply().
SetRecentFileList()
void VCommonSettings::SetRecentFileList (const QStringList & value)
Definition at line 1312 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralRecentFileList.
Referenced by MainWindow::setCurrentFile().
SetRestoreFileList()
void VCommonSettings::SetRestoreFileList (const QStringList & value)
Definition at line 1324 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralRestoreFileList.
Referenced by MainWindow::setCurrentFile().
setRotateSuffix()
void VCommonSettings::setRotateSuffix (const QString & value)
Definition at line 719 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationRotateSuffix.
Referenced by PreferencesConfigurationPage::Apply().
setScrollBarWidth()
void VCommonSettings::setScrollBarWidth (const int & width)
Definition at line 887 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollBarWidth.
Referenced by PreferencesGraphicsViewPage::Apply().
setScrollDuration()
void VCommonSettings::setScrollDuration (const int & duration)
Definition at line 899 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollDuration.
Referenced by PreferencesGraphicsViewPage::Apply().
setScrollSpeedFactor()
void VCommonSettings::setScrollSpeedFactor (const int & factor)
Definition at line 923 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollSpeedFactor.
Referenced by PreferencesGraphicsViewPage::Apply().
setScrollUpdateInterval()
void VCommonSettings::setScrollUpdateInterval (const int & interval)
Definition at line 911 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewScrollUpdateInterval.
Referenced by PreferencesGraphicsViewPage::Apply().
setSecondarySupportColor()
void VCommonSettings::setSecondarySupportColor (const QString & value)
Definition at line 1104 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewSecondaryColor.
Referenced by PreferencesGraphicsViewPage::Apply().
setSelectionSound()
void VCommonSettings::setSelectionSound (const QString & value)
Definition at line 1289 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingSelectionSound.
Referenced by PreferencesConfigurationPage::Apply().
SetSendReportState()
void VCommonSettings::SetSendReportState (const bool & value)
Definition at line 633 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationSendReportState.
setShowAnchorPoints()
void VCommonSettings::setShowAnchorPoints (bool value)
Definition at line 2067 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowAnchorPoints.
setShowArcToolBar()
void VCommonSettings::setShowArcToolBar (const bool & value)
Definition at line 815 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowArcToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowAxisOrigin()
void VCommonSettings::setShowAxisOrigin (bool value)
Definition at line 2031 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowAxisOrigin.
setShowControlPoints()
void VCommonSettings::setShowControlPoints (bool value)
Definition at line 2055 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowControlPoints.
setShowCurveToolBar()
void VCommonSettings::setShowCurveToolBar (const bool & value)
Definition at line 803 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowCurveToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowDetailsToolBar()
void VCommonSettings::setShowDetailsToolBar (const bool & value)
Definition at line 851 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowDetailsToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowGrainlines()
void VCommonSettings::setShowGrainlines (const bool & value)
Definition at line 1851 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowGrainlines.
setShowLabels()
void VCommonSettings::setShowLabels (const bool & value)
Definition at line 1911 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowLabels.
setShowLayoutToolBar()
void VCommonSettings::setShowLayoutToolBar (const bool & value)
Definition at line 863 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowLayoutToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowLineToolBar()
void VCommonSettings::setShowLineToolBar (const bool & value)
Definition at line 791 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowLineToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowOpsToolBar()
void VCommonSettings::setShowOpsToolBar (const bool & value)
Definition at line 827 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowOpsToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowPatternLabels()
void VCommonSettings::setShowPatternLabels (const bool & value)
Definition at line 1923 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowPatternLabels.
Referenced by PreferencesPatternPage::Apply().
setShowPieceLabels()
void VCommonSettings::setShowPieceLabels (const bool & value)
Definition at line 1935 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowPieceLabels.
Referenced by PreferencesPatternPage::Apply().
setShowPieceToolBar()
void VCommonSettings::setShowPieceToolBar (const bool & value)
Definition at line 839 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowPieceToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowPointToolBar()
void VCommonSettings::setShowPointToolBar (const bool & value)
Definition at line 779 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowPointToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowScrollBars()
void VCommonSettings::setShowScrollBars (const bool & value)
Definition at line 875 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowScrollBars.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowSeamAllowanceNotch()
void VCommonSettings::setShowSeamAllowanceNotch (bool value)
Definition at line 1486 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingSeamAllowanceNotch.
Referenced by PreferencesPatternPage::Apply().
setShowSeamAllowances()
void VCommonSettings::setShowSeamAllowances (const bool & value)
Definition at line 1827 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowSeamAllowances.
setShowSeamlineNotch()
void VCommonSettings::setShowSeamlineNotch (bool value)
Definition at line 1474 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingSeamlineNotch.
Referenced by PreferencesPatternPage::Apply().
setShowToolsToolBar()
void VCommonSettings::setShowToolsToolBar (const bool & value)
Definition at line 767 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewShowToolsToolBar.
Referenced by PreferencesGraphicsViewPage::Apply().
setShowWelcome()
void VCommonSettings::setShowWelcome (const bool & value)
Definition at line 541 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationShowWelcome.
Referenced by SeamlyMePreferencesConfigurationPage::Apply(), and SeamlyMeWelcomeDialog::apply().
setState()
void VCommonSettings::setState (const QString & value)
Definition at line 1191 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationState.
Referenced by PreferencesConfigurationPage::Apply().
setTelephone()
void VCommonSettings::setTelephone (const QString & value)
Definition at line 1221 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationTelephone.
Referenced by PreferencesConfigurationPage::Apply().
setTemplatePath()
void VCommonSettings::setTemplatePath (const QString & value)
Definition at line 464 of file vcommonsettings.cpp.
References commonIniFilename, and anonymous_namespace{vcommonsettings.cpp}::settingPathsTemplates.
Referenced by PreferencesPathPage::Apply(), and SeamlyMePreferencesPathPage::Apply().
setTertiarySupportColor()
void VCommonSettings::setTertiarySupportColor (const QString & value)
Definition at line 1116 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewTertiaryColor.
Referenced by PreferencesGraphicsViewPage::Apply().
SetToolbarsState()
void VCommonSettings::SetToolbarsState (const QByteArray & value)
Definition at line 1360 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralToolbarsState.
Referenced by MainWindow::WriteSettings(), and TMainWindow::WriteSettings().
setToolBarStyle()
void VCommonSettings::setToolBarStyle (const bool & value)
Definition at line 755 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewToolBarStyle.
Referenced by PreferencesGraphicsViewPage::Apply(), and SeamlyMePreferencesConfigurationPage::Apply().
SetUndoCount()
void VCommonSettings::SetUndoCount (const int & value)
Definition at line 1271 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingPatternUndo.
Referenced by PreferencesConfigurationPage::Apply().
SetUnit()
void VCommonSettings::SetUnit (const QString & value)
Definition at line 670 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUnit.
Referenced by PreferencesConfigurationPage::Apply(), and SeamlyMeWelcomeDialog::apply().
setUseLastExportFormat()
void VCommonSettings::setUseLastExportFormat (const bool & value)
Definition at line 609 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUseLastExportFormat.
Referenced by PreferencesConfigurationPage::Apply().
setUseModeType()
void VCommonSettings::setUseModeType (const bool & value)
Definition at line 597 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUseModeType.
Referenced by PreferencesConfigurationPage::Apply().
SetUserDefinedDateFormats()
void VCommonSettings::SetUserDefinedDateFormats (const QStringList & formats)
Definition at line 2172 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::ClearFormats(), PredefinedDateFormats(), and anonymous_namespace{vcommonsettings.cpp}::settingLabelUserDateFormats.
Referenced by PreferencesPatternPage::Apply().
SetUserDefinedTimeFormats()
void VCommonSettings::SetUserDefinedTimeFormats (const QStringList & formats)
Definition at line 2216 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::ClearFormats(), PredefinedTimeFormats(), and anonymous_namespace{vcommonsettings.cpp}::settingLabelUserTimeFormats.
Referenced by PreferencesPatternPage::Apply().
setUseToolColor()
void VCommonSettings::setUseToolColor (bool value)
Definition at line 2079 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsUseToolColor.
setWebsite()
void VCommonSettings::setWebsite (const QString & value)
Definition at line 1251 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationWebsite.
Referenced by PreferencesConfigurationPage::Apply().
SetWindowState()
void VCommonSettings::SetWindowState (const QByteArray & value)
Definition at line 1348 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGeneralWindowState.
Referenced by MainWindow::WriteSettings(), and TMainWindow::WriteSettings().
setWireframe()
void VCommonSettings::setWireframe (bool value)
Definition at line 2043 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewWireframe.
setZipcode()
void VCommonSettings::setZipcode (const QString & value)
Definition at line 1201 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationZipcode.
Referenced by PreferencesConfigurationPage::Apply().
setZoomDoubleClick()
void VCommonSettings::setZoomDoubleClick (const bool & value)
Definition at line 948 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomDoubleClick.
Referenced by PreferencesGraphicsViewPage::Apply().
setZoomModKey()
void VCommonSettings::setZoomModKey (const bool & value)
Definition at line 936 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomModKey.
Referenced by PreferencesGraphicsViewPage::Apply().
setZoomRBNegativeColor()
void VCommonSettings::setZoomRBNegativeColor (const QString & value)
Definition at line 1008 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomRBNegativeColor.
Referenced by PreferencesGraphicsViewPage::Apply().
setZoomRBPositiveColor()
void VCommonSettings::setZoomRBPositiveColor (const QString & value)
Definition at line 996 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomRBPositiveColor.
Referenced by PreferencesGraphicsViewPage::Apply().
setZoomSpeedFactor()
void VCommonSettings::setZoomSpeedFactor (const int & factor)
Definition at line 972 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingGraphicsViewZoomSpeedFactor.
Referenced by PreferencesGraphicsViewPage::Apply().
SharePath()
QString VCommonSettings::SharePath (const QString & shareItem) static
Definition at line 341 of file vcommonsettings.cpp.
References qApp, and unixStandardSharePath.
Referenced by MultisizeTablesPath(), and StandardTemplatesPath().
showGrainlines()
bool VCommonSettings::showGrainlines () const
Definition at line 1845 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowGrainlines.
showLabels()
bool VCommonSettings::showLabels () const
Definition at line 1905 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowLabels.
showPatternLabels()
bool VCommonSettings::showPatternLabels () const
Definition at line 1917 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowPatternLabels.
showPieceLabels()
bool VCommonSettings::showPieceLabels () const
Definition at line 1929 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowPieceLabels.
showSeamAllowanceNotch()
bool VCommonSettings::showSeamAllowanceNotch () const
Definition at line 1480 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingSeamAllowanceNotch.
showSeamAllowances()
bool VCommonSettings::showSeamAllowances () const
Definition at line 1821 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingShowSeamAllowances.
showSeamlineNotch()
bool VCommonSettings::showSeamlineNotch () const
Definition at line 1468 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingSeamlineNotch.
StandardTemplatesPath()
QString VCommonSettings::StandardTemplatesPath () static
Definition at line 391 of file vcommonsettings.cpp.
References SharePath().
Referenced by PrepareStandardTemplates().
useLastExportFormat()
bool VCommonSettings::useLastExportFormat () const
Definition at line 603 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUseLastExportFormat.
useModeType()
bool VCommonSettings::useModeType () const
Definition at line 591 of file vcommonsettings.cpp.
References anonymous_namespace{vcommonsettings.cpp}::settingConfigurationUseModeType.
Member Data Documentation
unixStandardSharePath
const QString VCommonSettings::unixStandardSharePath = QStringLiteral("/usr/share/seamly2d") static
Definition at line 457 of file vcommonsettings.h.
Referenced by SharePath().
The documentation for this class was generated from the following files:
src/libs/vmisc/vcommonsettings.h
src/libs/vmisc/vcommonsettings.cpp