Seamly2D: VVariable Class Reference
VVariable Class Reference
#include <vvariable.h>
Public Member Functions
VVariable ()
VVariable (const QString &name, const QString &description=QString())
VVariable (const VVariable &var)
virtual ~VVariable () Q_DECL_OVERRIDE
VVariable & operator= (const VVariable &var)
void Swap (VVariable &var) Q_DECL_NOTHROW
QString GetDescription () const
void SetDescription (const QString &desc)
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool Filter (quint32 id)
virtual bool isNotUsed () const
Private Attributes
QSharedDataPointer< VVariableData > d
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
Definition at line 67 of file vvariable.h.
Constructor & Destructor Documentation
VVariable() [1/3]
VVariable::VVariable ()
Definition at line 69 of file vvariable.cpp.
VVariable() [2/3]
VVariable::VVariable (const QString & name, const QString & description = QString())
Definition at line 74 of file vvariable.cpp.
References VInternalVariable::SetName().
VVariable() [3/3]
VVariable::VVariable (const VVariable & var)
Definition at line 81 of file vvariable.cpp.
~VVariable()
VVariable::~VVariable () virtual
Definition at line 98 of file vvariable.cpp.
Member Function Documentation
GetDescription()
QString VVariable::GetDescription () const
Definition at line 102 of file vvariable.cpp.
References d.
operator=()
VVariable & VVariable::operator= (const VVariable & var)
Definition at line 86 of file vvariable.cpp.
References d, and VInternalVariable::operator=().
Referenced by VIncrement::operator=(), and VMeasurement::operator=().
SetDescription()
void VVariable::SetDescription (const QString & desc)
Definition at line 109 of file vvariable.cpp.
References d.
Swap()
void VVariable::Swap (VVariable & var)
Definition at line 65 of file vvariable.cpp.
References VInternalVariable::Swap().
Referenced by VIncrement::Swap(), and VMeasurement::Swap().
Member Data Documentation
d
QSharedDataPointer<VVariableData> VVariable::d private
Definition at line 87 of file vvariable.h.
Referenced by GetDescription(), operator=(), and SetDescription().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/vvariable.h
src/libs/vpatterndb/variables/vvariable.cpp