Seamly2D: VCurveCLength Class Reference
VCurveCLength Class Reference
#include <vcurveclength.h>
Public Member Functions
VCurveCLength ()
VCurveCLength (const quint32 &id, const quint32 &parentId, const VAbstractBezier *curve, CurveCLength cType, Unit patternUnit)
VCurveCLength (const quint32 &id, const quint32 &parentId, const QString &baseCurveName, const VSpline &spl, CurveCLength cType, Unit patternUnit, qint32 segment)
VCurveCLength (const VCurveCLength &var)
VCurveCLength & operator= (const VCurveCLength &var)
virtual ~VCurveCLength () Q_DECL_OVERRIDE
Public Member Functions inherited from VCurveVariable
VCurveVariable ()
VCurveVariable (const quint32 &id, const quint32 &parentId)
VCurveVariable (const VCurveVariable &var)
virtual ~VCurveVariable () Q_DECL_OVERRIDE
VCurveVariable & operator= (const VCurveVariable &var)
void Swap (VCurveVariable &var) Q_DECL_NOTHROW
virtual bool Filter (quint32 id) Q_DECL_OVERRIDE
quint32 GetId () const
void SetId (const quint32 &id)
quint32 GetParentId () const
void SetParentId (const quint32 &value)
Public Member Functions inherited from VInternalVariable
VInternalVariable ()
VInternalVariable (const VInternalVariable &var)
virtual ~VInternalVariable ()
VInternalVariable & operator= (const VInternalVariable &var)
void Swap (VInternalVariable &var) Q_DECL_NOTHROW
virtual qreal GetValue () const
virtual qreal * GetValue ()
QString GetName () const
void SetName (const QString &name)
VarType GetType () const
void SetType (const VarType &type)
virtual bool isNotUsed () const
Additional Inherited Members
Protected Member Functions inherited from VInternalVariable
void SetValue (const qreal &value)
Detailed Description
Definition at line 66 of file vcurveclength.h.
Constructor & Destructor Documentation
VCurveCLength() [1/4]
VCurveCLength::VCurveCLength ()
Definition at line 64 of file vcurveclength.cpp.
References CurveCLength, and VInternalVariable::SetType().
VCurveCLength() [2/4]
VCurveCLength::VCurveCLength (const quint32 & id, const quint32 & parentId, const VAbstractBezier * curve, CurveCLength cType, Unit patternUnit)
Definition at line 71 of file vcurveclength.cpp.
References C1, c1Length_V, c2Length_V, CurveCLength, FromPixel(), VAbstractBezier::GetC1Length(), VAbstractBezier::GetC2Length(), VGObject::name(), SCASSERT, VInternalVariable::SetName(), VInternalVariable::SetType(), and VInternalVariable::SetValue().
VCurveCLength() [3/4]
VCurveCLength::VCurveCLength (const quint32 & id, const quint32 & parentId, const QString & baseCurveName, const VSpline & spl, CurveCLength cType, Unit patternUnit, qint32 segment)
Definition at line 90 of file vcurveclength.cpp.
References C1, c1Length_V, c2Length_V, CurveCLength, FromPixel(), VSpline::GetC1Length(), VSpline::GetC2Length(), seg_, VInternalVariable::SetName(), VInternalVariable::SetType(), and VInternalVariable::SetValue().
VCurveCLength() [4/4]
VCurveCLength::VCurveCLength (const VCurveCLength & var)
Definition at line 108 of file vcurveclength.cpp.
~VCurveCLength()
VCurveCLength::~VCurveCLength () virtual
Definition at line 125 of file vcurveclength.cpp.
Member Function Documentation
operator=()
VCurveCLength & VCurveCLength::operator= (const VCurveCLength & var)
Definition at line 114 of file vcurveclength.cpp.
References VCurveVariable::operator=().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/variables/vcurveclength.h
src/libs/vpatterndb/variables/vcurveclength.cpp