Seamly2D: VToolBisector Class Reference
VToolBisector Class Reference
The VToolBisector class tool for creation bisector point.
#include <vtoolbisector.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::Bisector) }
Public Types inherited from VToolLinePoint
enum { Type = UserType + static_cast<int>(Tool::LinePoint) }
Public Types inherited from VToolSinglePoint
enum { Type = UserType + static_cast<int>(Tool::SinglePoint) }
Public Types inherited from VScenePoint
enum { Type = UserType + static_cast<int>(Vis::ScenePoint) }
Public Member Functions
virtual void setDialog () Q_DECL_OVERRIDE
setDialog set dialog when user want change tool option.
virtual int type () const Q_DECL_OVERRIDE
QString FirstPointName () const
QString ThirdPointName () const
quint32 GetFirstPointId () const
void SetFirstPointId (const quint32 &value)
quint32 GetThirdPointId () const
void SetThirdPointId (const quint32 &value)
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
Public Member Functions inherited from VToolLinePoint
VToolLinePoint (VAbstractPattern *doc, VContainer *data, const quint32 &id, const QString &lineType, const QString &lineWeight, const QString &lineColor, const QString &formula, const quint32 &basePointId, const qreal &angle, QGraphicsItem *parent=nullptr)
VToolLinePoint constructor.
virtual ~VToolLinePoint () Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
VFormula GetFormulaLength () const
void SetFormulaLength (const VFormula &value)
QString BasePointName () const
quint32 GetBasePointId () const
void SetBasePointId (const quint32 &value)
qreal GetAngle () const
void SetAngle (const qreal &value)
QString getLineColor () const
void setLineColor (const QString &value)
Public Member Functions inherited from VToolSinglePoint
VToolSinglePoint (VAbstractPattern *doc, VContainer *data, quint32 id, const QColor &lineColor, QGraphicsItem *parent=nullptr)
VToolSinglePoint constructor.
virtual ~VToolSinglePoint () Q_DECL_EQ_DEFAULT
QString name () const
void setName (const QString &name)
void SetEnabled (bool enabled)
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
virtual bool isPointNameVisible (quint32 id) const Q_DECL_OVERRIDE
virtual void setPointNameVisiblity (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void setPointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
Public Member Functions inherited from VAbstractPoint
VAbstractPoint (VAbstractPattern *doc, VContainer *data, quint32 id)
virtual ~VAbstractPoint () Q_DECL_EQ_DEFAULT
virtual QString getTagName () const Q_DECL_OVERRIDE
template<typename T >
void ShowToolVisualization (bool show)
Public Member Functions inherited from VDrawTool
VDrawTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VDrawTool constructor.
virtual ~VDrawTool () Q_DECL_EQ_DEFAULT
QString getLineType () const
virtual void setLineType (const QString &value)
QString getLineWeight () const
virtual void setLineWeight (const QString &value)
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Public Member Functions inherited from VScenePoint
VScenePoint (const QColor &lineColor, QGraphicsItem *parent=nullptr)
virtual ~VScenePoint ()=default
virtual void refreshPointGeometry (const VPointF &point)
void refreshLeader ()
Static Public Member Functions
static qreal BisectorAngle (const QPointF &firstPoint, const QPointF &secondPoint, const QPointF &thirdPoint)
static QPointF FindPoint (const QPointF &firstPoint, const QPointF &secondPoint, const QPointF &thirdPoint, const qreal &length)
FindPoint find bisector point.
static VToolBisector * Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Create help create tool form GUI.
static VToolBisector * Create (const quint32 _id, QString &formula, quint32 firstPointId, quint32 secondPointId, quint32 thirdPointId, const QString &lineType, const QString &lineWeight, const QString &lineColor, const QString &pointName, qreal mx, qreal my, bool showPointName, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation)
Create help create tool.
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const QString ToolType = QStringLiteral("bisector")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Slots
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID) Q_DECL_OVERRIDE
contextMenuEvent handle context menu events.
Protected Slots inherited from VDrawTool
virtual void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=NULL_ID)=0
Protected Member Functions
virtual void RemoveReferens () Q_DECL_OVERRIDE
RemoveReferens decrement value of reference.
virtual void SaveDialog (QDomElement &domElement) Q_DECL_OVERRIDE
SaveDialog save options into file after change in dialog.
virtual void SaveOptions (QDomElement &tag, QSharedPointer< VGObject > &obj) Q_DECL_OVERRIDE
virtual void ReadToolAttributes (const QDomElement &domElement) Q_DECL_OVERRIDE
virtual void SetVisualization () Q_DECL_OVERRIDE
Protected Member Functions inherited from VToolLinePoint
virtual void RefreshGeometry ()
lineColor color of a line.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual QString makeToolTip () const Q_DECL_OVERRIDE
Protected Member Functions inherited from VToolSinglePoint
virtual void updatePointNameVisibility (quint32 id, bool visible) Q_DECL_OVERRIDE
virtual void updatePointNamePosition (quint32 id, const QPointF &pos) Q_DECL_OVERRIDE
updatePointNamePosition save new position text to the pattern file.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
mouseReleaseEvent handle mouse release events.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) Q_DECL_OVERRIDE
itemChange hadle item change.
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
keyReleaseEvent handle key release events.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractPoint
void SetPointName (quint32 id, const QString &name)
Protected Member Functions inherited from VDrawTool
void AddToCalculation (const QDomElement &domElement)
typeLine line weight.
void addDependence (QList< quint32 > &list, quint32 objectId) const
virtual void SaveDialogChange () Q_DECL_FINAL
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
void SaveOption (QSharedPointer< VGObject > &obj)
bool CorrectDisable (bool disable, const QString &draftBlockName) const
void ReadAttributes ()
template<typename Dialog >
void ContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 itemId=NULL_ID, const RemoveOption &showRemove=RemoveOption::Enable, const Referens &ref=Referens::Follow)
ContextMenu show context menu for tool.
template<typename Item >
void ShowItem (Item *item, quint32 id, bool enable)
ShowItem highlight tool.
template<typename T >
QString ObjectName (quint32 id) const
ObjectName get object (point, curve, arc) name.
Protected Member Functions inherited from VAbstractTool
virtual void RefreshDataInFile ()
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual void deleteTool (bool ask=true)
deleteTool full delete object form scene and file.
template<typename T >
void AddVisualization ()
virtual void ToolCreation (const Source &typeCreation)
Protected Member Functions inherited from VScenePoint
void setOnlyPoint (bool value)
bool isOnlyPoint () const
void setPointColor (const QString &value)
Private Member Functions
VToolBisector (VAbstractPattern *doc, VContainer *data, const quint32 &id, const QString &lineType, const QString &lineWeight, const QString &lineColor, const QString &formula, const quint32 &firstPointId, const quint32 &secondPointId, const quint32 &thirdPointId, const Source &typeCreation, QGraphicsItem *parent=nullptr)
VToolBisector constructor.
Private Attributes
quint32 firstPointId
firstPointId id first point of angle.
quint32 thirdPointId
thirdPointId id third point of angle.
Additional Inherited Members
Public Slots inherited from VToolLinePoint
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
Public Slots inherited from VToolSinglePoint
void pointnameChangedPosition (const QPointF &pos)
pointnameChangedPosition handle change position point text.
virtual void Disable (bool disable, const QString &draftBlockName) Q_DECL_OVERRIDE
virtual void EnableToolMove (bool move) Q_DECL_OVERRIDE
void pointChosen ()
void pointSelected (bool selected)
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
void allowTextHover (bool enabled)
void allowTextSelectable (bool enabled)
virtual void ToolSelectionType (const SelectionType &type) Q_DECL_OVERRIDE
Public Slots inherited from VAbstractPoint
virtual void ShowTool (quint32 id, bool enable) Q_DECL_OVERRIDE
ShowTool highlight tool.
void deletePoint ()
Public Slots inherited from VDrawTool
virtual void ShowTool (quint32 id, bool enable)
ShowTool highlight tool.
virtual void activeBlockChanged (const QString &newName)
activeBlockChanged disable or enable context menu after change active draft block.
void blockNameChanged (const QString &oldName, const QString &newName)
blockNameChanged save new name active draft block.
virtual void EnableToolMove (bool move)
virtual void Disable (bool disable, const QString &draftBlockName)=0
virtual void piecesMode (bool mode)
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Signals inherited from VDrawTool
void ChangedToolSelection (bool selected, quint32 object, quint32 tool)
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Protected Types inherited from VDrawTool
enum class RemoveOption : bool { Disable = false , Enable = true }
enum class Referens : bool { Follow = true , Ignore = false }
Static Protected Member Functions inherited from VAbstractPoint
template<typename T >
static void InitToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VDrawTool
template<typename T >
static void InitDrawToolConnections (VMainGraphicsScene *scene, T *tool)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VToolLinePoint
QString formulaLength
qreal angle
formula string with length formula.
quint32 basePointId
angle line angle.
VScaledLine * mainLine
basePointId id base line point.
QString lineColor
mainLine line item.
Protected Attributes inherited from VDrawTool
QString activeBlockName
QString m_lineType
activeBlockName name of tool's pattern peace.
QString m_lineWeight
typeLine line type.
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Protected Attributes inherited from VScenePoint
VGraphicsSimpleTextItem * m_pointName
VScaledLine * m_pointLeader
namePoint point text.
QColor m_pointColor
pointL line that we see if Text is moved too away from point.
bool m_onlyPoint
m_pointColor color of point.
bool m_isHovered
bool m_showPointName
Detailed Description
The VToolBisector class tool for creation bisector point.
Definition at line 73 of file vtoolbisector.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 93 of file vtoolbisector.h.
Constructor & Destructor Documentation
VToolBisector()
VToolBisector::VToolBisector (VAbstractPattern * doc, VContainer * data, const quint32 & id, const QString & lineType, const QString & lineWeight, const QString & lineColor, const QString & formula, const quint32 & firstPointId, const quint32 & secondPointId, const quint32 & thirdPointId, const Source & typeCreation, QGraphicsItem * parent = nullptr) private
VToolBisector constructor.
Parameters
doc dom document container.
data container with variables.
id object id in container.
lineType line type.
lineWeight line weight.
lineColor line color.
formula string with formula length of bisector.
firstPointId id first point of angle.
secondPointId id second point of angle.
thirdPointId id third point of angle.
typeCreation way we create this tool.
parent parent object.
Definition at line 98 of file vtoolbisector.cpp.
References VAbstractTool::ToolCreation().
Referenced by Create().
Member Function Documentation
BisectorAngle()
qreal VToolBisector::BisectorAngle (const QPointF & firstPoint, const QPointF & secondPoint, const QPointF & thirdPoint) static
Definition at line 111 of file vtoolbisector.cpp.
References VToolLinePoint::angle.
Referenced by FindPoint(), and VisToolBisector::RefreshGeometry().
Create() [1/2]
VToolBisector * VToolBisector::Create (const quint32 _id, QString & formula, quint32 firstPointId, quint32 secondPointId, quint32 thirdPointId, const QString & lineType, const QString & lineWeight, const QString & lineColor, const QString & pointName, qreal mx, qreal my, bool showPointName, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation) static
Create help create tool.
Parameters
_id tool id, 0 if tool doesn't exist yet.
formula string with formula.
firstPointId id first point of angle.
secondPointId id second point of angle.
thirdPointId id third point of angle.
lineType line type.
lineWeight line weight.
lineColor line color.
pointName point name.
mx label bias x axis.
my label bias y axis.
showPointName show/hide point name text.
scene pointer to scene.
doc dom document container.
data container with variables.
parse parser file mode.
typeCreation way we create this tool.
Definition at line 217 of file vtoolbisector.cpp.
References VContainer::AddGObject(), VContainer::AddLine(), VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), Bisector, VAbstractTool::CheckFormula(), VDataTool::data, VAbstractTool::doc, FindPoint(), firstPointId, FromGui, FullParse, VContainer::GeometricObject(), VAbstractPattern::IncrementReferens(), VAbstractPoint::InitToolConnections(), VToolLinePoint::lineColor, qApp, VPointF::setShowPointName(), thirdPointId, VContainer::UpdateGObject(), VAbstractPattern::UpdateToolData(), and VToolBisector().
Create() [2/2]
VToolBisector * VToolBisector::Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data) static
Create help create tool form GUI.
Parameters
dialog dialog.
scene pointer to scene.
doc dom document container.
data container with variables.
Definition at line 173 of file vtoolbisector.cpp.
References VDataTool::data, VAbstractTool::doc, firstPointId, FromGui, FullParse, VToolLinePoint::lineColor, VInteractiveTool::m_dialog, SCASSERT, and thirdPointId.
Referenced by VPattern::ParseToolBisector().
FindPoint()
QPointF VToolBisector::FindPoint (const QPointF & firstPoint, const QPointF & secondPoint, const QPointF & thirdPoint, const qreal & length) static
FindPoint find bisector point.
Parameters
firstPoint first point of angle.
secondPoint second point of angle.
thirdPoint third point of angle.
length bisector length.
Returns
bisector point.
Definition at line 136 of file vtoolbisector.cpp.
References BisectorAngle().
Referenced by Create().
FirstPointName()
QString VToolBisector::FirstPointName () const
Definition at line 268 of file vtoolbisector.cpp.
References VDataTool::data, firstPointId, and VContainer::GetGObject().
Referenced by VToolOptionsPropertyBrowser::showOptionsToolBisector(), and VToolOptionsPropertyBrowser::updateOptionsToolBisector().
GetFirstPointId()
quint32 VToolBisector::GetFirstPointId () const
Definition at line 397 of file vtoolbisector.cpp.
References firstPointId.
GetThirdPointId()
quint32 VToolBisector::GetThirdPointId () const
Definition at line 373 of file vtoolbisector.cpp.
References thirdPointId.
ReadToolAttributes()
void VToolBisector::ReadToolAttributes (const QDomElement & domElement) protected virtual
Implements VDrawTool.
Definition at line 343 of file vtoolbisector.cpp.
References AttrFirstPoint, AttrLength, AttrLineColor, AttrLineType, AttrLineWeight, AttrSecondPoint, AttrThirdPoint, VToolLinePoint::basePointId, ColorBlack, VAbstractTool::doc, firstPointId, VToolLinePoint::formulaLength, VDomDocument::GetParametrString(), VDomDocument::GetParametrUInt(), VToolLinePoint::lineColor, LineTypeSolidLine, VDrawTool::m_lineType, VDrawTool::m_lineWeight, NULL_ID_STR, and thirdPointId.
RemoveReferens()
void VToolBisector::RemoveReferens () protected virtual
RemoveReferens decrement value of reference.
Reimplemented from VToolLinePoint.
Definition at line 301 of file vtoolbisector.cpp.
References VDataTool::data, VAbstractPattern::DecrementReferens(), VAbstractTool::doc, firstPointId, VContainer::GetGObject(), VToolLinePoint::RemoveReferens(), and thirdPointId.
SaveDialog()
void VToolBisector::SaveDialog (QDomElement & domElement) protected virtual
SaveDialog save options into file after change in dialog.
Implements VDrawTool.
Definition at line 315 of file vtoolbisector.cpp.
References AttrFirstPoint, AttrLength, AttrLineColor, AttrLineType, AttrLineWeight, AttrName, AttrSecondPoint, AttrThirdPoint, VAbstractTool::doc, VInteractiveTool::m_dialog, SCASSERT, and VDomDocument::SetAttribute().
SaveOptions()
void VToolBisector::SaveOptions (QDomElement & tag, QSharedPointer< VGObject > & obj) protected virtual
Reimplemented from VToolLinePoint.
Definition at line 331 of file vtoolbisector.cpp.
References AttrFirstPoint, AttrLength, AttrSecondPoint, AttrThirdPoint, AttrType, VToolLinePoint::basePointId, VAbstractTool::doc, firstPointId, VToolLinePoint::formulaLength, VToolLinePoint::SaveOptions(), VDomDocument::SetAttribute(), thirdPointId, and ToolType.
setDialog()
void VToolBisector::setDialog () virtual
setDialog set dialog when user want change tool option.
Reimplemented from VInteractiveTool.
Definition at line 149 of file vtoolbisector.cpp.
References VToolLinePoint::basePointId, VDataTool::data, firstPointId, VToolLinePoint::formulaLength, VContainer::GeometricObject(), VToolLinePoint::lineColor, VInteractiveTool::m_dialog, VAbstractTool::m_id, VDrawTool::m_lineType, VDrawTool::m_lineWeight, SCASSERT, and thirdPointId.
SetFirstPointId()
void VToolBisector::SetFirstPointId (const quint32 & value)
Definition at line 403 of file vtoolbisector.cpp.
References VDataTool::data, firstPointId, VContainer::GetGObject(), VAbstractTool::m_id, NULL_ID, and VDrawTool::SaveOption().
Referenced by VToolOptionsPropertyBrowser::changeDataToolBisector().
SetThirdPointId()
void VToolBisector::SetThirdPointId (const quint32 & value)
Definition at line 379 of file vtoolbisector.cpp.
References VDataTool::data, VContainer::GetGObject(), VAbstractTool::m_id, NULL_ID, VDrawTool::SaveOption(), and thirdPointId.
Referenced by VToolOptionsPropertyBrowser::changeDataToolBisector().
SetVisualization()
void VToolBisector::SetVisualization () protected virtual
Implements VAbstractTool.
Definition at line 355 of file vtoolbisector.cpp.
References VToolLinePoint::basePointId, firstPointId, VToolLinePoint::formulaLength, lineTypeToPenStyle(), VDrawTool::m_lineType, VDrawTool::m_lineWeight, qApp, VisToolBisector::RefreshGeometry(), SCASSERT, VisToolBisector::setLength(), Visualization::setLineStyle(), Visualization::setLineWeight(), Visualization::setObject1Id(), VisToolBisector::setObject2Id(), VisToolBisector::setObject3Id(), thirdPointId, and VAbstractTool::vis.
showContextMenu
void VToolBisector::showContextMenu (QGraphicsSceneContextMenuEvent * event, quint32 id = NULL_ID) protected virtual slot
contextMenuEvent handle context menu events.
Parameters
event context menu event.
Definition at line 284 of file vtoolbisector.cpp.
ShowVisualization()
void VToolBisector::ShowVisualization (bool show) virtual
Implements VAbstractTool.
Definition at line 391 of file vtoolbisector.cpp.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolBisector().
ThirdPointName()
QString VToolBisector::ThirdPointName () const
Definition at line 274 of file vtoolbisector.cpp.
References VDataTool::data, VContainer::GetGObject(), and thirdPointId.
Referenced by VToolOptionsPropertyBrowser::showOptionsToolBisector(), and VToolOptionsPropertyBrowser::updateOptionsToolBisector().
type()
virtual int VToolBisector::type () const inline virtual
Reimplemented from VToolLinePoint.
Definition at line 92 of file vtoolbisector.h.
References Type.
Member Data Documentation
firstPointId
quint32 VToolBisector::firstPointId private
firstPointId id first point of angle.
Definition at line 119 of file vtoolbisector.h.
Referenced by Create(), FirstPointName(), GetFirstPointId(), ReadToolAttributes(), RemoveReferens(), SaveOptions(), setDialog(), SetFirstPointId(), and SetVisualization().
thirdPointId
quint32 VToolBisector::thirdPointId private
thirdPointId id third point of angle.
Definition at line 122 of file vtoolbisector.h.
Referenced by Create(), GetThirdPointId(), ReadToolAttributes(), RemoveReferens(), SaveOptions(), setDialog(), SetThirdPointId(), SetVisualization(), and ThirdPointName().
ToolType
const QString VToolBisector::ToolType = QStringLiteral("bisector") static
Definition at line 91 of file vtoolbisector.h.
Referenced by VPattern::ParsePointElement(), and SaveOptions().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolbisector.h
src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolbisector.cpp