Seamly2D: VAbstractFloatItemData Class Reference
VAbstractFloatItemData Class Reference
#include <vabstractfloatitemdata.h>
Public Member Functions
VAbstractFloatItemData ()
VAbstractFloatItemData (const VAbstractFloatItemData &data)
virtual ~VAbstractFloatItemData ()
VAbstractFloatItemData & operator= (const VAbstractFloatItemData &data)
void Swap (VAbstractFloatItemData &data) Q_DECL_NOTHROW
QPointF GetPos () const
void SetPos (const QPointF &ptPos)
bool IsVisible () const
void SetVisible (bool bVisible)
Private Attributes
QSharedDataPointer< VAbstractFloatItemDataPrivate > d
Detailed Description
Definition at line 60 of file vabstractfloatitemdata.h.
Constructor & Destructor Documentation
VAbstractFloatItemData() [1/2]
VAbstractFloatItemData::VAbstractFloatItemData ()
Definition at line 64 of file vabstractfloatitemdata.cpp.
VAbstractFloatItemData() [2/2]
VAbstractFloatItemData::VAbstractFloatItemData (const VAbstractFloatItemData & data)
Definition at line 69 of file vabstractfloatitemdata.cpp.
~VAbstractFloatItemData()
VAbstractFloatItemData::~VAbstractFloatItemData () virtual
Definition at line 85 of file vabstractfloatitemdata.cpp.
Member Function Documentation
GetPos()
QPointF VAbstractFloatItemData::GetPos () const
Definition at line 89 of file vabstractfloatitemdata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), anonymous_namespace{vlayoutpiece.cpp}::FindLabelGeometry(), and PatternPieceTool::FindLabelGeometry().
IsVisible()
bool VAbstractFloatItemData::IsVisible () const
Definition at line 101 of file vabstractfloatitemdata.cpp.
References d.
Referenced by PatternPieceTool::contextMenuEvent(), VLayoutPiece::Create(), PatternPieceTool::keyReleaseEvent(), PatternPieceTool::ResetChildren(), PatternPieceDialog::SetPiece(), and PatternPieceTool::UpdatePieceLabel().
operator=()
VAbstractFloatItemData & VAbstractFloatItemData::operator= (const VAbstractFloatItemData & data)
Definition at line 74 of file vabstractfloatitemdata.cpp.
References d.
Referenced by VGrainlineData::operator=(), and VPatternLabelData::operator=().
SetPos()
void VAbstractFloatItemData::SetPos (const QPointF & ptPos)
Definition at line 95 of file vabstractfloatitemdata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), VPattern::ParsePieceDataTag(), VPattern::ParsePieceGrainline(), VPattern::ParsePiecePatternInfo(), PatternPieceTool::SaveMoveGrainline(), PatternPieceTool::SaveMovePattern(), PatternPieceTool::saveMovePiece(), PatternPieceTool::savePieceRotation(), PatternPieceTool::SaveResizeGrainline(), PatternPieceTool::SaveRotateGrainline(), and PatternPieceTool::SaveRotationPattern().
SetVisible()
void VAbstractFloatItemData::SetVisible (bool bVisible)
Definition at line 107 of file vabstractfloatitemdata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), VPattern::ParsePieceDataTag(), VPattern::ParsePieceGrainline(), VPattern::ParsePiecePatternInfo(), PatternPieceTool::toggleGrainline(), PatternPieceTool::togglePatternLabel(), and PatternPieceTool::togglePieceLabel().
Swap()
void VAbstractFloatItemData::Swap (VAbstractFloatItemData & data)
Definition at line 60 of file vabstractfloatitemdata.cpp.
Referenced by VGrainlineData::Swap(), and VPatternLabelData::Swap().
Member Data Documentation
d
QSharedDataPointer<VAbstractFloatItemDataPrivate> VAbstractFloatItemData::d private
Definition at line 83 of file vabstractfloatitemdata.h.
Referenced by GetPos(), IsVisible(), operator=(), SetPos(), and SetVisible().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/floatItemData/vabstractfloatitemdata.h
src/libs/vpatterndb/floatItemData/vabstractfloatitemdata.cpp