Seamly2D: PatternPieceVisual Class Reference
PatternPieceVisual Class Reference
#include <pattern_piece_visual.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolPiece) }
Public Types inherited from VisPath
enum { Type = UserType + static_cast<int>(Vis::Path) }
Public Types inherited from VCurvePathItem
enum { Type = UserType + static_cast<int>(Vis::CurvePathItem) }
Public Member Functions
PatternPieceVisual (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~PatternPieceVisual () Q_DECL_EQ_DEFAULT
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void SetPiece (const VPiece &piece)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisPath
VisPath (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisPath ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VCurvePathItem
VCurvePathItem (QGraphicsItem *parent=nullptr)
virtual ~VCurvePathItem ()=default
virtual QPainterPath shape () const Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
void SetDirectionArrows (const QVector< QPair< QLineF, QLineF >> &arrows)
void SetPoints (const QVector< QPointF > &points)
Private Member Functions
VScaledEllipse * GetPoint (quint32 i, const QColor &color)
void HideAllItems ()
Private Attributes
QVector< VScaledEllipse * > m_points
VScaledLine * m_line1
VScaledLine * m_line2
VPiece m_piece
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisPath
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
VSimplePoint * GetPoint (QVector< VSimplePoint * > &points, quint32 i, const QColor &color)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Protected Member Functions inherited from VCurvePathItem
virtual void ScalePenWidth ()
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 62 of file pattern_piece_visual.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 72 of file pattern_piece_visual.h.
Constructor & Destructor Documentation
PatternPieceVisual()
PatternPieceVisual::PatternPieceVisual (const VContainer * data, QGraphicsItem * parent = nullptr)
Definition at line 59 of file pattern_piece_visual.cpp.
References m_line1, m_line2, and Visualization::supportColor.
~PatternPieceVisual()
virtual PatternPieceVisual::~PatternPieceVisual () virtual
Member Function Documentation
GetPoint()
VScaledEllipse * PatternPieceVisual::GetPoint (quint32 i, const QColor & color) private
Definition at line 97 of file pattern_piece_visual.cpp.
References Visualization::GetPointItem(), and m_points.
Referenced by RefreshGeometry().
HideAllItems()
void PatternPieceVisual::HideAllItems () private
Definition at line 103 of file pattern_piece_visual.cpp.
References m_line1, m_line2, and m_points.
Referenced by RefreshGeometry().
RefreshGeometry()
void PatternPieceVisual::RefreshGeometry () virtual
Implements Visualization.
Definition at line 71 of file pattern_piece_visual.cpp.
References VPiecePath::CountNodes(), Visualization::data, Visualization::DrawPath(), Visualization::DrawPoint(), VPiece::GetPath(), GetPoint(), HideAllItems(), m_piece, Visualization::mainColor, VPiece::MainPathNodePoints(), and VPiece::MainPathPath().
SetPiece()
void PatternPieceVisual::SetPiece (const VPiece & piece)
Definition at line 91 of file pattern_piece_visual.cpp.
References m_piece.
Referenced by PatternPieceDialog::setSeamAllowanceWidthFormula().
type()
virtual int PatternPieceVisual::type () const inline virtual
Reimplemented from VisPath.
Definition at line 71 of file pattern_piece_visual.h.
References Type.
Member Data Documentation
m_line1
VScaledLine* PatternPieceVisual::m_line1 private
Definition at line 78 of file pattern_piece_visual.h.
Referenced by HideAllItems(), and PatternPieceVisual().
m_line2
VScaledLine* PatternPieceVisual::m_line2 private
Definition at line 79 of file pattern_piece_visual.h.
Referenced by HideAllItems(), and PatternPieceVisual().
m_piece
VPiece PatternPieceVisual::m_piece private
Definition at line 80 of file pattern_piece_visual.h.
Referenced by RefreshGeometry(), and SetPiece().
m_points
QVector<VScaledEllipse *> PatternPieceVisual::m_points private
Definition at line 76 of file pattern_piece_visual.h.
Referenced by GetPoint(), and HideAllItems().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/path/pattern_piece_visual.h
src/libs/vtools/visualization/path/pattern_piece_visual.cpp