Seamly2D: VPE::VStringProperty Class Reference
VPE::VStringProperty Class Reference
Class for holding a string property.
#include <vstringproperty.h>
Public Member Functions
VStringProperty (const QString &name, const QMap< QString, QVariant > &settings)
VStringProperty (const QString &name)
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &options, const QAbstractItemDelegate *delegate) Q_DECL_OVERRIDE
Returns an editor widget, or NULL if it doesn't supply one.
virtual QVariant getEditorData (const QWidget *editor) const Q_DECL_OVERRIDE
Gets the data from the widget.
void setReadOnly (bool readOnly)
void setOsSeparator (bool separator)
void setClearButtonEnable (bool value)
virtual void setSetting (const QString &key, const QVariant &value) Q_DECL_OVERRIDE
Sets the settings.
virtual QVariant getSetting (const QString &key) const Q_DECL_OVERRIDE
Get the settings. This function has to be implemented in a subclass in order to have an effect.
virtual QStringList getSettingKeys () const Q_DECL_OVERRIDE
Returns the list of keys of the property's settings.
virtual QString type () const Q_DECL_OVERRIDE
Returns a string containing the type of the property.
virtual Q_REQUIRED_RESULT VProperty * clone (bool include_children=true, VProperty *container=nullptr) const Q_DECL_OVERRIDE
Clones this property.
virtual void updateParent (const QVariant &value) Q_DECL_OVERRIDE
int getTypeForParent () const
void setTypeForParent (int value)
Public Member Functions inherited from VPE::VProperty
VProperty (const QString &name, QVariant::Type type=QVariant::String)
Standard constructor, takes a name and a parent property as argument.
virtual ~VProperty () Q_DECL_OVERRIDE
Destructor.
virtual QVariant data (int column=DPC_Name, int role=Qt::DisplayRole) const
Get the data how it should be displayed.
virtual bool setData (const QVariant &data, int role=Qt::EditRole)
This is used by the model to set the data.
virtual bool paint (QPainter *, const QStyleOptionViewItem &, const QModelIndex &, const QAbstractItemDelegate *) const
This is called by the delegate when the property value is being drawn. The standard implementation doesn't do anything. If you reimplement this in a sub property, make sure to return true or the delegate will draw the item.
virtual bool setEditorData (QWidget *editor)
Sets the property's data to the editor (returns false, if the standard delegate should do that)
virtual Qt::ItemFlags flags (int column=DPC_Name) const
Returns item flags.
virtual void setValue (const QVariant &value)
Sets the value of the property.
virtual QVariant getValue () const
Returns the value of the property as a QVariant.
virtual QString serialize () const
Serializes the value to a string.
virtual void deserialize (const QString &value)
Deserializes the value from a string.
virtual void setName (const QString &name)
Sets the name of the property.
virtual QString getName () const
Gets the name of the property.
virtual void setDescription (const QString &desc)
Sets the name of the property.
virtual QString getDescription () const
Gets the name of the property.
virtual int addChild (VProperty *child)
Adds a child to this property.
virtual QList< VProperty * > & getChildren ()
Returns a reference to the list of children.
virtual const QList< VProperty * > & getChildren () const
Returns a reference to the list of children.
virtual VProperty * getChild (int row) const
Returns the child at a certain row.
virtual int getRowCount () const
Gets the number of children.
virtual VProperty * getParent () const
Gets the parent of this property.
virtual void setParent (VProperty *parent)
Sets the parent of this property.
virtual void removeChild (VProperty *child)
Removes a child from the children list, doesn't delete the child!
virtual int getChildRow (VProperty *child) const
Returns the row the child has.
virtual bool getUpdateParent () const
Returns whether the views have to update the parent of this property if it changes.
virtual bool getUpdateChildren () const
Returns whether the views have to update the children of this property if it changes.
virtual void setUpdateBehaviour (bool update_parent, bool update_children)
Sets whether the views should update Parents or children after this property changes.
virtual void setSettings (const QMap< QString, QVariant > &settings)
Sets the settings by calling the overloaded setSetting(const QString &key, const QVariant &value) for each item in the map.
virtual QMap< QString, QVariant > getSettings () const
Get the settings.
Property propertyType () const
void setPropertyType (const Property &type)
Protected Member Functions
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
Protected Member Functions inherited from VPE::VProperty
VProperty (VPropertyPrivate *d)
Protected constructor.
Protected Attributes
bool readOnly
int typeForParent
bool clearButton
bool m_osSeparator
Protected Attributes inherited from VPE::VProperty
VPropertyPrivate * d_ptr
The protected structure holding the member variables (to assure binary compatibility)
Additional Inherited Members
Public Types inherited from VPE::VProperty
enum DPC_DisplayColumn { DPC_Name = 0 , DPC_Data }
Public Slots inherited from VPE::VProperty
virtual void childValueChanged (const QVariant &value, int typeForParent)
Signals inherited from VPE::VProperty
void childChanged (const QVariant &value, int typeForParent)
Detailed Description
Class for holding a string property.
Definition at line 41 of file vstringproperty.h.
Constructor & Destructor Documentation
VStringProperty() [1/2]
VPE::VStringProperty::VStringProperty (const QString & name, const QMap< QString, QVariant > & settings)
Definition at line 35 of file vstringproperty.cpp.
References VPE::VProperty::d_ptr, VPE::VProperty::setSettings(), and VPE::VPropertyPrivate::VariantValue.
VStringProperty() [2/2]
VPE::VStringProperty::VStringProperty (const QString & name) explicit
Definition at line 47 of file vstringproperty.cpp.
References VPE::VProperty::d_ptr, and VPE::VPropertyPrivate::VariantValue.
Member Function Documentation
clone()
VPE::VProperty * VPE::VStringProperty::clone (bool include_children = true, VPE::VProperty * container = nullptr) const virtual
Clones this property.
Parameters
include_children Indicates whether to also clone the children
container If a property is being passed here, no new VProperty is being created but instead it is tried to fill all the data into container. This can also be used when subclassing this function.
Returns
Returns the newly created property (or container, if it was not NULL)
Reimplemented from VPE::VProperty.
Definition at line 142 of file vstringproperty.cpp.
References VPE::VProperty::clone().
createEditor()
QWidget * VPE::VStringProperty::createEditor (QWidget * parent, const QStyleOptionViewItem & options, const QAbstractItemDelegate * delegate) virtual
Returns an editor widget, or NULL if it doesn't supply one.
Parameters
parent The widget to which the editor will be added as a child \options Render options \delegate A pointer to the QAbstractItemDelegate requesting the editor. This can be used to connect signals and slots.
Reimplemented from VPE::VProperty.
Definition at line 58 of file vstringproperty.cpp.
eventFilter()
bool VPE::VStringProperty::eventFilter (QObject * object, QEvent * event) protected virtual
Definition at line 163 of file vstringproperty.cpp.
getEditorData()
QVariant VPE::VStringProperty::getEditorData (const QWidget * editor) const virtual
Gets the data from the widget.
Reimplemented from VPE::VProperty.
Definition at line 78 of file vstringproperty.cpp.
getSetting()
QVariant VPE::VStringProperty::getSetting (const QString & key) const virtual
Get the settings. This function has to be implemented in a subclass in order to have an effect.
Reimplemented from VPE::VProperty.
Definition at line 116 of file vstringproperty.cpp.
References VPE::VProperty::getSetting().
getSettingKeys()
QStringList VPE::VStringProperty::getSettingKeys () const virtual
Returns the list of keys of the property's settings.
Reimplemented from VPE::VProperty.
Definition at line 130 of file vstringproperty.cpp.
getTypeForParent()
int VPE::VStringProperty::getTypeForParent () const
Definition at line 153 of file vstringproperty.cpp.
setClearButtonEnable()
void VPE::VStringProperty::setClearButtonEnable (bool value)
Definition at line 99 of file vstringproperty.cpp.
Referenced by VToolOptionsPropertyBrowser::addPropertyObjectName(), VToolOptionsPropertyBrowser::addPropertyOperationSuffix(), VToolOptionsPropertyBrowser::addPropertyPointName1(), and VToolOptionsPropertyBrowser::addPropertyPointName2().
setOsSeparator()
void VPE::VStringProperty::setOsSeparator (bool separator)
Definition at line 94 of file vstringproperty.cpp.
setReadOnly()
void VPE::VStringProperty::setReadOnly (bool readOnly)
Definition at line 89 of file vstringproperty.cpp.
Referenced by VToolOptionsPropertyBrowser::addPropertyObjectName(), and VToolOptionsPropertyBrowser::addPropertyOperationSuffix().
setSetting()
void VPE::VStringProperty::setSetting (const QString & key, const QVariant & value) virtual
Sets the settings.
Reimplemented from VPE::VProperty.
Definition at line 104 of file vstringproperty.cpp.
setTypeForParent()
void VPE::VStringProperty::setTypeForParent (int value)
Definition at line 158 of file vstringproperty.cpp.
type()
QString VPE::VStringProperty::type () const virtual
Returns a string containing the type of the property.
Reimplemented from VPE::VProperty.
Definition at line 137 of file vstringproperty.cpp.
updateParent()
void VPE::VStringProperty::updateParent (const QVariant & value) virtual
Reimplemented from VPE::VProperty.
Definition at line 147 of file vstringproperty.cpp.
Member Data Documentation
clearButton
bool VPE::VStringProperty::clearButton protected
Definition at line 92 of file vstringproperty.h.
m_osSeparator
bool VPE::VStringProperty::m_osSeparator protected
Definition at line 93 of file vstringproperty.h.
readOnly
bool VPE::VStringProperty::readOnly protected
Definition at line 90 of file vstringproperty.h.
typeForParent
int VPE::VStringProperty::typeForParent protected
Definition at line 91 of file vstringproperty.h.
The documentation for this class was generated from the following files:
src/libs/vpropertyexplorer/plugins/vstringproperty.h
src/libs/vpropertyexplorer/plugins/vstringproperty.cpp