Seamly2D: DialogEllipticalArc Class Reference
DialogEllipticalArc Class Reference
#include <dialogellipticalarc.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
void DeployRadius1TextEdit ()
DeployFormulaTextEdit grow or shrink formula input.
void DeployRadius2TextEdit ()
void DeployF1TextEdit ()
void DeployF2TextEdit ()
void DeployRotationAngleTextEdit ()
void Radius1Changed ()
Radius1Changed after change formula of radius1 calculate value and show result.
void Radius2Changed ()
Radius2Changed after change formula of radius2 calculate value and show result.
void F1Changed ()
F1Changed after change formula of first angle calculate value and show result.
void F2Changed ()
F2Changed after change formula of second angle calculate value and show result.
void RotationAngleChanged ()
RotationAngleChanged after change formula of rotation angle calculate value and show result.
void FXRadius1 ()
void FXRadius2 ()
void FXF1 ()
void FXF2 ()
void FXRotationAngle ()
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogEllipticalArc (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogEllipticalArc create dialog.
virtual ~DialogEllipticalArc () Q_DECL_OVERRIDE
VEllipticalArc getArc () const
void setArc (const VEllipticalArc &arc)
quint32 GetCenter () const
GetCenter return id of center point.
void SetCenter (const quint32 &value)
SetCenter set id of center point.
QString GetRadius1 () const
GetRadius1 return formula of radius1.
void SetRadius1 (const QString &value)
SetRadius1 set formula of radius1.
QString GetRadius2 () const
GetRadius2 return formula of radius2.
void SetRadius2 (const QString &value)
SetRadius2 set formula of radius2.
QString GetF1 () const
GetF1 return formula first angle of elliptical arc.
void SetF1 (const QString &value)
SetF1 set formula first angle of elliptical arc.
QString GetF2 () const
GetF2 return formula second angle of elliptical arc.
void SetF2 (const QString &value)
SetF2 set formula second angle of elliptical arc.
QString GetRotationAngle () const
GetRotationAngle return formula rotation angle of elliptical arc.
void SetRotationAngle (const QString &value)
SetRotationAngle set formula rotation angle of elliptical arc.
QString getPenStyle () const
void setPenStyle (const QString &value)
QString getLineWeight () const
getLineWeight return weight of the lines
void setLineWeight (const QString &value)
setLineWeight set weight of the lines
QString getLineColor () const
GetColor return color of elliptical arc.
void setLineColor (const QString &value)
setLineColor set color of elliptical arc
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
void pointNameChanged ()
virtual void CheckState () Q_DECL_FINAL
CheckState if all is right enable button ok.
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Member Functions
void EvalRadiuses ()
EvalRadiuses calculate value of radiuses.
void EvalAngles ()
EvalAngles calculate value of angles.
void CheckAngles ()
void collapseFormula (QPlainTextEdit *textEdit, QPushButton *pushButton, int height)
Private Attributes
Ui::DialogEllipticalArc * ui
ui keeps information about user interface
bool flagRadius1
flagRadius1 true if value of radius1 is correct
bool flagRadius2
flagRadius2 true if value of radius2 is correct
bool flagF1
flagF1 true if value of first angle is correct
bool flagF2
flagF2 true if value of second angle is correct
bool flagRotationAngle
flagRotationAngle true if value of rotation angle is correct
QTimer * timerRadius1
timerRadius1 timer of check formula of radius1
QTimer * timerRadius2
timerRadius2 timer of check formula of radius2
QTimer * timerF1
timerF1 timer of check formula of first angle
QTimer * timerF2
timerF2 timer of check formula of second angle
QTimer * timerRotationAngle
timerRotationAngle timer of check formula of rotation angle
QString radius1
radius1 formula of radius1
QString radius2
radius2 formula of radius2
QString f1
f1 formula of first angle
QString f2
f2 formula of second angle
QString rotationAngle
rotationAngle formula of rotation angle
int formulaBaseHeightRadius1
formulaBaseHeight base height defined by dialogui
int formulaBaseHeightRadius2
int formulaBaseHeightF1
int formulaBaseHeightF2
int formulaBaseHeightRotationAngle
qreal angleF1
qreal angleF2
qreal angleRotation
VEllipticalArc m_arc
qint32 m_Id
qint32 newDuplicate
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
Definition at line 64 of file dialogellipticalarc.h.
Constructor & Destructor Documentation
DialogEllipticalArc()
DialogEllipticalArc::DialogEllipticalArc (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
DialogEllipticalArc create dialog.
Parameters
data container with data
parent parent widget
Definition at line 74 of file dialogellipticalarc.cpp.
References CheckState(), DialogTool::data, DeployF1TextEdit(), DeployF2TextEdit(), DeployRadius1TextEdit(), DeployRadius2TextEdit(), DeployRotationAngleTextEdit(), EvalAngles(), EvalRadiuses(), F1Changed(), F2Changed(), DialogTool::FillComboBoxPoints(), formulaBaseHeightF1, formulaBaseHeightF2, formulaBaseHeightRadius1, formulaBaseHeightRadius2, formulaBaseHeightRotationAngle, FXF1(), FXF2(), FXRadius1(), FXRadius2(), FXRotationAngle(), VContainer::getId(), DialogTool::initializeOkCancelApply(), LineTypeNone, m_Id, pointNameChanged(), qApp, Radius1Changed(), Radius2Changed(), RotationAngleChanged(), timerF1, timerF2, timerRadius1, timerRadius2, timerRotationAngle, ui, and DialogTool::vis.
~DialogEllipticalArc()
DialogEllipticalArc::~DialogEllipticalArc () virtual
Definition at line 193 of file dialogellipticalarc.cpp.
References ui.
Member Function Documentation
CheckAngles()
void DialogEllipticalArc::CheckAngles () private
Definition at line 497 of file dialogellipticalarc.cpp.
References angleF1, angleF2, DialogTool::ChangeColor(), CheckState(), flagF1, flagF2, ui, and VFuzzyComparePossibleNulls().
Referenced by EvalAngles().
CheckState()
void DialogEllipticalArc::CheckState () protected virtual
CheckState if all is right enable button ok.
Reimplemented from DialogTool.
Definition at line 759 of file dialogellipticalarc.cpp.
References DialogTool::apply_Button, flagF1, flagF2, flagRadius1, flagRadius2, flagRotationAngle, DialogTool::ok_Button, and SCASSERT.
Referenced by CheckAngles(), DialogEllipticalArc(), EvalRadiuses(), and pointNameChanged().
ChosenObject
void DialogEllipticalArc::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
Parameters
id id of point or detail
type type of object
Definition at line 703 of file dialogellipticalarc.cpp.
References Point, DialogTool::prepare, DialogTool::SetObject(), ui, and DialogTool::vis.
closeEvent()
void DialogEllipticalArc::closeEvent (QCloseEvent * event) protected virtual
closeEvent handle when dialog cloded
Parameters
event event
Reimplemented from DialogTool.
Definition at line 800 of file dialogellipticalarc.cpp.
References DialogTool::closeEvent(), and ui.
collapseFormula()
void DialogEllipticalArc::collapseFormula (QPlainTextEdit * textEdit, QPushButton * pushButton, int height) private
Definition at line 811 of file dialogellipticalarc.cpp.
References SCASSERT.
Referenced by DeployF1TextEdit(), DeployF2TextEdit(), DeployRadius1TextEdit(), DeployRadius2TextEdit(), and DeployRotationAngleTextEdit().
DeployF1TextEdit
void DialogEllipticalArc::DeployF1TextEdit () slot
Definition at line 668 of file dialogellipticalarc.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightF1, formulaBaseHeightF2, formulaBaseHeightRadius1, formulaBaseHeightRadius2, formulaBaseHeightRotationAngle, and ui.
Referenced by DialogEllipticalArc(), and SetF1().
DeployF2TextEdit
void DialogEllipticalArc::DeployF2TextEdit () slot
Definition at line 678 of file dialogellipticalarc.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightF1, formulaBaseHeightF2, formulaBaseHeightRadius1, formulaBaseHeightRadius2, formulaBaseHeightRotationAngle, and ui.
Referenced by DialogEllipticalArc(), and SetF2().
DeployRadius1TextEdit
void DialogEllipticalArc::DeployRadius1TextEdit () slot
DeployFormulaTextEdit grow or shrink formula input.
Definition at line 648 of file dialogellipticalarc.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightF1, formulaBaseHeightF2, formulaBaseHeightRadius1, formulaBaseHeightRadius2, formulaBaseHeightRotationAngle, and ui.
Referenced by DialogEllipticalArc(), and SetRadius1().
DeployRadius2TextEdit
void DialogEllipticalArc::DeployRadius2TextEdit () slot
Definition at line 658 of file dialogellipticalarc.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightF1, formulaBaseHeightF2, formulaBaseHeightRadius1, formulaBaseHeightRadius2, formulaBaseHeightRotationAngle, and ui.
Referenced by DialogEllipticalArc(), and SetRadius2().
DeployRotationAngleTextEdit
void DialogEllipticalArc::DeployRotationAngleTextEdit () slot
Definition at line 688 of file dialogellipticalarc.cpp.
References collapseFormula(), DialogTool::DeployFormula(), formulaBaseHeightF1, formulaBaseHeightF2, formulaBaseHeightRadius1, formulaBaseHeightRadius2, formulaBaseHeightRotationAngle, and ui.
Referenced by DialogEllipticalArc(), and SetRotationAngle().
EvalAngles()
void DialogEllipticalArc::EvalAngles () private
EvalAngles calculate value of angles.
Definition at line 481 of file dialogellipticalarc.cpp.
References angleF1, angleF2, angleRotation, CheckAngles(), degreeSymbol, DialogTool::Eval(), flagF1, flagF2, flagRotationAngle, DialogTool::labelEditFormula, and ui.
Referenced by DialogEllipticalArc().
EvalRadiuses()
void DialogEllipticalArc::EvalRadiuses () private
EvalRadiuses calculate value of radiuses.
Definition at line 448 of file dialogellipticalarc.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::Eval(), flagRadius1, flagRadius2, DialogTool::labelEditFormula, qApp, ui, and UnitsToStr().
Referenced by DialogEllipticalArc().
F1Changed
void DialogEllipticalArc::F1Changed () slot
F1Changed after change formula of first angle calculate value and show result.
Definition at line 618 of file dialogellipticalarc.cpp.
References degreeSymbol, flagF1, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, timerF1, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogEllipticalArc().
F2Changed
void DialogEllipticalArc::F2Changed () slot
F2Changed after change formula of second angle calculate value and show result.
Definition at line 629 of file dialogellipticalarc.cpp.
References degreeSymbol, flagF2, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, timerF2, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogEllipticalArc().
FXF1
void DialogEllipticalArc::FXF1 () slot
Definition at line 549 of file dialogellipticalarc.cpp.
References DialogTool::data, degreeSymbol, GetF1(), EditFormulaDialog::GetFormula(), SetF1(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), and DialogTool::toolId.
Referenced by DialogEllipticalArc().
FXF2
void DialogEllipticalArc::FXF2 () slot
Definition at line 563 of file dialogellipticalarc.cpp.
References DialogTool::data, degreeSymbol, GetF2(), EditFormulaDialog::GetFormula(), SetF2(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), and DialogTool::toolId.
Referenced by DialogEllipticalArc().
FXRadius1
void DialogEllipticalArc::FXRadius1 () slot
Definition at line 521 of file dialogellipticalarc.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), GetRadius1(), qApp, EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), SetRadius1(), DialogTool::toolId, and UnitsToStr().
Referenced by DialogEllipticalArc().
FXRadius2
void DialogEllipticalArc::FXRadius2 () slot
Definition at line 535 of file dialogellipticalarc.cpp.
References DialogTool::data, EditFormulaDialog::GetFormula(), GetRadius2(), qApp, EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), SetRadius2(), DialogTool::toolId, and UnitsToStr().
Referenced by DialogEllipticalArc().
FXRotationAngle
void DialogEllipticalArc::FXRotationAngle () slot
Definition at line 577 of file dialogellipticalarc.cpp.
References DialogTool::data, degreeSymbol, EditFormulaDialog::GetFormula(), GetRotationAngle(), EditFormulaDialog::SetFormula(), EditFormulaDialog::setPostfix(), SetRotationAngle(), and DialogTool::toolId.
Referenced by DialogEllipticalArc().
getArc()
VEllipticalArc DialogEllipticalArc::getArc () const
Definition at line 199 of file dialogellipticalarc.cpp.
References m_arc.
GetCenter()
quint32 DialogEllipticalArc::GetCenter () const
GetCenter return id of center point.
Returns
id id
Definition at line 216 of file dialogellipticalarc.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by SaveData().
GetF1()
QString DialogEllipticalArc::GetF1 () const
GetF1 return formula first angle of elliptical arc.
Returns
formula
Definition at line 301 of file dialogellipticalarc.cpp.
References f1, and qApp.
Referenced by FXF1(), and pointNameChanged().
GetF2()
QString DialogEllipticalArc::GetF2 () const
GetF2 return formula second angle of elliptical arc.
Returns
formula
Definition at line 333 of file dialogellipticalarc.cpp.
References f2, and qApp.
Referenced by FXF2(), and pointNameChanged().
getLineColor()
QString DialogEllipticalArc::getLineColor () const
GetColor return color of elliptical arc.
Returns
formula
Definition at line 429 of file dialogellipticalarc.cpp.
References ColorBlack, DialogTool::GetComboBoxCurrentData(), and ui.
getLineWeight()
QString DialogEllipticalArc::getLineWeight () const
getLineWeight return weight of the lines
Returns
type
Definition at line 409 of file dialogellipticalarc.cpp.
References DialogTool::GetComboBoxCurrentData(), and ui.
getPenStyle()
QString DialogEllipticalArc::getPenStyle () const
Definition at line 393 of file dialogellipticalarc.cpp.
References DialogTool::GetComboBoxCurrentData(), LineTypeSolidLine, and ui.
GetRadius1()
QString DialogEllipticalArc::GetRadius1 () const
GetRadius1 return formula of radius1.
Returns
formula
Definition at line 237 of file dialogellipticalarc.cpp.
References qApp, and radius1.
Referenced by FXRadius1(), and pointNameChanged().
GetRadius2()
QString DialogEllipticalArc::GetRadius2 () const
GetRadius2 return formula of radius2.
Returns
formula
Definition at line 269 of file dialogellipticalarc.cpp.
References qApp, and radius2.
Referenced by FXRadius2(), and pointNameChanged().
GetRotationAngle()
QString DialogEllipticalArc::GetRotationAngle () const
GetRotationAngle return formula rotation angle of elliptical arc.
Returns
formula
Definition at line 365 of file dialogellipticalarc.cpp.
References qApp, and rotationAngle.
Referenced by FXRotationAngle(), and pointNameChanged().
pointNameChanged()
void DialogEllipticalArc::pointNameChanged () protected
Definition at line 721 of file dialogellipticalarc.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::data, DialogTool::DNumber(), DialogTool::flagError, VContainer::GeometricObject(), VEllipticalArc::GetCenter(), DialogTool::getCurrentObjectId(), GetF1(), GetF2(), GetRadius1(), GetRadius2(), GetRotationAngle(), VGObject::id(), VContainer::IsUnique(), m_arc, m_Id, VGObject::name(), newDuplicate, DialogTool::okColor, qApp, VAbstractCurve::SetDuplicate(), and ui.
Referenced by DialogEllipticalArc().
Radius1Changed
void DialogEllipticalArc::Radius1Changed () slot
Radius1Changed after change formula of radius1 calculate value and show result.
Definition at line 594 of file dialogellipticalarc.cpp.
References flagRadius1, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, qApp, timerRadius1, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by DialogEllipticalArc().
Radius2Changed
void DialogEllipticalArc::Radius2Changed () slot
Radius2Changed after change formula of radius2 calculate value and show result.
Definition at line 606 of file dialogellipticalarc.cpp.
References flagRadius2, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, qApp, timerRadius2, ui, UnitsToStr(), and DialogTool::ValFormulaChanged().
Referenced by DialogEllipticalArc().
RotationAngleChanged
void DialogEllipticalArc::RotationAngleChanged () slot
RotationAngleChanged after change formula of rotation angle calculate value and show result.
Definition at line 640 of file dialogellipticalarc.cpp.
References degreeSymbol, flagRotationAngle, DialogTool::labelEditFormula, DialogTool::labelResultCalculation, timerRotationAngle, ui, and DialogTool::ValFormulaChanged().
Referenced by DialogEllipticalArc().
SaveData()
void DialogEllipticalArc::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 774 of file dialogellipticalarc.cpp.
References f1, f2, GetCenter(), radius1, radius2, VisToolEllipticalArc::RefreshGeometry(), rotationAngle, SCASSERT, VisToolEllipticalArc::setF1(), VisToolEllipticalArc::setF2(), Visualization::setObject1Id(), VisToolEllipticalArc::setRadius1(), VisToolEllipticalArc::setRadius2(), VisToolEllipticalArc::setRotationAngle(), ui, and DialogTool::vis.
setArc()
void DialogEllipticalArc::setArc (const VEllipticalArc & arc)
Definition at line 205 of file dialogellipticalarc.cpp.
References m_arc, VGObject::name(), qApp, and ui.
SetCenter()
void DialogEllipticalArc::SetCenter (const quint32 & value)
SetCenter set id of center point.
Parameters
value id
Definition at line 226 of file dialogellipticalarc.cpp.
References DialogTool::ChangeCurrentData(), ui, and DialogTool::vis.
SetF1()
void DialogEllipticalArc::SetF1 (const QString & value)
SetF1 set formula first angle of elliptical arc.
Parameters
value formula
Definition at line 311 of file dialogellipticalarc.cpp.
References DeployF1TextEdit(), f1, DialogTool::MoveCursorToEnd(), qApp, SCASSERT, VisToolEllipticalArc::setF1(), ui, and DialogTool::vis.
Referenced by FXF1().
SetF2()
void DialogEllipticalArc::SetF2 (const QString & value)
SetF2 set formula second angle of elliptical arc.
Parameters
value formula
Definition at line 343 of file dialogellipticalarc.cpp.
References DeployF2TextEdit(), f2, DialogTool::MoveCursorToEnd(), qApp, SCASSERT, VisToolEllipticalArc::setF2(), ui, and DialogTool::vis.
Referenced by FXF2().
setLineColor()
void DialogEllipticalArc::setLineColor (const QString & value)
setLineColor set color of elliptical arc
Parameters
value formula
Definition at line 439 of file dialogellipticalarc.cpp.
References DialogTool::ChangeCurrentData(), and ui.
setLineWeight()
void DialogEllipticalArc::setLineWeight (const QString & value)
setLineWeight set weight of the lines
Parameters
value type
Definition at line 419 of file dialogellipticalarc.cpp.
References DialogTool::ChangeCurrentData(), ui, and DialogTool::vis.
setPenStyle()
void DialogEllipticalArc::setPenStyle (const QString & value)
Definition at line 399 of file dialogellipticalarc.cpp.
References DialogTool::ChangeCurrentData(), and ui.
SetRadius1()
void DialogEllipticalArc::SetRadius1 (const QString & value)
SetRadius1 set formula of radius1.
Parameters
value formula
Definition at line 247 of file dialogellipticalarc.cpp.
References DeployRadius1TextEdit(), DialogTool::MoveCursorToEnd(), qApp, radius1, SCASSERT, VisToolEllipticalArc::setRadius1(), ui, and DialogTool::vis.
Referenced by FXRadius1().
SetRadius2()
void DialogEllipticalArc::SetRadius2 (const QString & value)
SetRadius2 set formula of radius2.
Parameters
value formula
Definition at line 279 of file dialogellipticalarc.cpp.
References DeployRadius2TextEdit(), DialogTool::MoveCursorToEnd(), qApp, radius2, SCASSERT, VisToolEllipticalArc::setRadius2(), ui, and DialogTool::vis.
Referenced by FXRadius2().
SetRotationAngle()
void DialogEllipticalArc::SetRotationAngle (const QString & value)
SetRotationAngle set formula rotation angle of elliptical arc.
Parameters
value formula
Definition at line 375 of file dialogellipticalarc.cpp.
References DeployRotationAngleTextEdit(), DialogTool::MoveCursorToEnd(), qApp, rotationAngle, SCASSERT, VisToolEllipticalArc::setRotationAngle(), ui, and DialogTool::vis.
Referenced by FXRotationAngle().
ShowVisualization()
void DialogEllipticalArc::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 768 of file dialogellipticalarc.cpp.
Member Data Documentation
angleF1
qreal DialogEllipticalArc::angleF1 private
Definition at line 193 of file dialogellipticalarc.h.
Referenced by CheckAngles(), and EvalAngles().
angleF2
qreal DialogEllipticalArc::angleF2 private
Definition at line 194 of file dialogellipticalarc.h.
Referenced by CheckAngles(), and EvalAngles().
angleRotation
qreal DialogEllipticalArc::angleRotation private
Definition at line 195 of file dialogellipticalarc.h.
Referenced by EvalAngles().
f1
QString DialogEllipticalArc::f1 private
f1 formula of first angle
Definition at line 178 of file dialogellipticalarc.h.
Referenced by GetF1(), SaveData(), and SetF1().
f2
QString DialogEllipticalArc::f2 private
f2 formula of second angle
Definition at line 181 of file dialogellipticalarc.h.
Referenced by GetF2(), SaveData(), and SetF2().
flagF1
bool DialogEllipticalArc::flagF1 private
flagF1 true if value of first angle is correct
Definition at line 148 of file dialogellipticalarc.h.
Referenced by CheckAngles(), CheckState(), EvalAngles(), and F1Changed().
flagF2
bool DialogEllipticalArc::flagF2 private
flagF2 true if value of second angle is correct
Definition at line 151 of file dialogellipticalarc.h.
Referenced by CheckAngles(), CheckState(), EvalAngles(), and F2Changed().
flagRadius1
bool DialogEllipticalArc::flagRadius1 private
flagRadius1 true if value of radius1 is correct
Definition at line 142 of file dialogellipticalarc.h.
Referenced by CheckState(), EvalRadiuses(), and Radius1Changed().
flagRadius2
bool DialogEllipticalArc::flagRadius2 private
flagRadius2 true if value of radius2 is correct
Definition at line 145 of file dialogellipticalarc.h.
Referenced by CheckState(), EvalRadiuses(), and Radius2Changed().
flagRotationAngle
bool DialogEllipticalArc::flagRotationAngle private
flagRotationAngle true if value of rotation angle is correct
Definition at line 154 of file dialogellipticalarc.h.
Referenced by CheckState(), EvalAngles(), and RotationAngleChanged().
formulaBaseHeightF1
int DialogEllipticalArc::formulaBaseHeightF1 private
Definition at line 189 of file dialogellipticalarc.h.
Referenced by DeployF1TextEdit(), DeployF2TextEdit(), DeployRadius1TextEdit(), DeployRadius2TextEdit(), DeployRotationAngleTextEdit(), and DialogEllipticalArc().
formulaBaseHeightF2
int DialogEllipticalArc::formulaBaseHeightF2 private
Definition at line 190 of file dialogellipticalarc.h.
Referenced by DeployF1TextEdit(), DeployF2TextEdit(), DeployRadius1TextEdit(), DeployRadius2TextEdit(), DeployRotationAngleTextEdit(), and DialogEllipticalArc().
formulaBaseHeightRadius1
int DialogEllipticalArc::formulaBaseHeightRadius1 private
formulaBaseHeight base height defined by dialogui
Definition at line 187 of file dialogellipticalarc.h.
Referenced by DeployF1TextEdit(), DeployF2TextEdit(), DeployRadius1TextEdit(), DeployRadius2TextEdit(), DeployRotationAngleTextEdit(), and DialogEllipticalArc().
formulaBaseHeightRadius2
int DialogEllipticalArc::formulaBaseHeightRadius2 private
Definition at line 188 of file dialogellipticalarc.h.
Referenced by DeployF1TextEdit(), DeployF2TextEdit(), DeployRadius1TextEdit(), DeployRadius2TextEdit(), DeployRotationAngleTextEdit(), and DialogEllipticalArc().
formulaBaseHeightRotationAngle
int DialogEllipticalArc::formulaBaseHeightRotationAngle private
Definition at line 191 of file dialogellipticalarc.h.
Referenced by DeployF1TextEdit(), DeployF2TextEdit(), DeployRadius1TextEdit(), DeployRadius2TextEdit(), DeployRotationAngleTextEdit(), and DialogEllipticalArc().
m_arc
VEllipticalArc DialogEllipticalArc::m_arc private
Definition at line 196 of file dialogellipticalarc.h.
Referenced by getArc(), pointNameChanged(), and setArc().
m_Id
qint32 DialogEllipticalArc::m_Id private
Definition at line 197 of file dialogellipticalarc.h.
Referenced by DialogEllipticalArc(), and pointNameChanged().
newDuplicate
qint32 DialogEllipticalArc::newDuplicate private
Definition at line 198 of file dialogellipticalarc.h.
Referenced by pointNameChanged().
radius1
QString DialogEllipticalArc::radius1 private
radius1 formula of radius1
Definition at line 172 of file dialogellipticalarc.h.
Referenced by GetRadius1(), SaveData(), and SetRadius1().
radius2
QString DialogEllipticalArc::radius2 private
radius2 formula of radius2
Definition at line 175 of file dialogellipticalarc.h.
Referenced by GetRadius2(), SaveData(), and SetRadius2().
rotationAngle
QString DialogEllipticalArc::rotationAngle private
rotationAngle formula of rotation angle
Definition at line 184 of file dialogellipticalarc.h.
Referenced by GetRotationAngle(), SaveData(), and SetRotationAngle().
timerF1
QTimer* DialogEllipticalArc::timerF1 private
timerF1 timer of check formula of first angle
Definition at line 163 of file dialogellipticalarc.h.
Referenced by DialogEllipticalArc(), and F1Changed().
timerF2
QTimer* DialogEllipticalArc::timerF2 private
timerF2 timer of check formula of second angle
Definition at line 166 of file dialogellipticalarc.h.
Referenced by DialogEllipticalArc(), and F2Changed().
timerRadius1
QTimer* DialogEllipticalArc::timerRadius1 private
timerRadius1 timer of check formula of radius1
Definition at line 157 of file dialogellipticalarc.h.
Referenced by DialogEllipticalArc(), and Radius1Changed().
timerRadius2
QTimer* DialogEllipticalArc::timerRadius2 private
timerRadius2 timer of check formula of radius2
Definition at line 160 of file dialogellipticalarc.h.
Referenced by DialogEllipticalArc(), and Radius2Changed().
timerRotationAngle
QTimer* DialogEllipticalArc::timerRotationAngle private
timerRotationAngle timer of check formula of rotation angle
Definition at line 169 of file dialogellipticalarc.h.
Referenced by DialogEllipticalArc(), and RotationAngleChanged().
ui
Ui::DialogEllipticalArc* DialogEllipticalArc::ui private
ui keeps information about user interface
Definition at line 139 of file dialogellipticalarc.h.
Referenced by CheckAngles(), ChosenObject(), closeEvent(), DeployF1TextEdit(), DeployF2TextEdit(), DeployRadius1TextEdit(), DeployRadius2TextEdit(), DeployRotationAngleTextEdit(), DialogEllipticalArc(), EvalAngles(), EvalRadiuses(), F1Changed(), F2Changed(), GetCenter(), getLineColor(), getLineWeight(), getPenStyle(), pointNameChanged(), Radius1Changed(), Radius2Changed(), RotationAngleChanged(), SaveData(), setArc(), SetCenter(), SetF1(), SetF2(), setLineColor(), setLineWeight(), setPenStyle(), SetRadius1(), SetRadius2(), SetRotationAngle(), and ~DialogEllipticalArc().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialogellipticalarc.h
src/libs/vtools/dialogs/tools/dialogellipticalarc.cpp