Seamly2D: LayoutSettingsDialog Class Reference
LayoutSettingsDialog Class Reference
#include <layoutsettings_dialog.h>
Public Slots
void DialogAccepted ()
Public Member Functions
LayoutSettingsDialog (VLayoutGenerator *generator, QWidget *parent=nullptr, bool disableSettings=false)
virtual ~LayoutSettingsDialog ()
qreal GetPaperHeight () const
void SetPaperHeight (qreal value)
qreal GetPaperWidth () const
void SetPaperWidth (qreal value)
qreal GetShift () const
void SetShift (qreal value)
qreal GetLayoutWidth () const
void SetLayoutWidth (qreal value)
QMarginsF GetFields () const
void SetFields (const QMarginsF &value)
Cases GetGroup () const
void SetGroup (const Cases &value)
bool GetRotate () const
void SetRotate (bool state)
int GetIncrease () const
bool SetIncrease (int increase)
bool GetAutoCrop () const
void SetAutoCrop (bool autoCrop)
bool IsSaveLength () const
void SetSaveLength (bool save)
bool IsUnitePages () const
void SetUnitePages (bool save)
bool IsStripOptimization () const
void SetStripOptimization (bool save)
quint8 GetMultiplier () const
void SetMultiplier (const quint8 &value)
bool IsIgnoreAllFields () const
void SetIgnoreAllFields (bool value)
bool isTextAsPaths () const
void setTextAsPaths (bool value)
QString SelectedPrinter () const
bool SelectTemplate (const PaperSizeFormat &id)
bool SelectPaperUnit (const QString &units)
bool SelectLayoutUnit (const QString &units)
qreal LayoutToPixels (qreal value) const
qreal PageToPixels (qreal value) const
Public Member Functions inherited from AbstractLayoutDialog
AbstractLayoutDialog (QWidget *parent=nullptr)
Static Public Member Functions
static QString MakeGroupsHelp ()
Protected Member Functions
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
QSizeF getTemplateSize (const PaperSizeFormat &tmpl, const Unit &unit) const
LayoutSettingsDialog::TemplateSize.
Protected Member Functions inherited from AbstractLayoutDialog
QSizeF getTemplateSize (const PaperSizeFormat &tmpl, const Unit &unit) const
LayoutSettingsDialog::TemplateSize.
QSizeF RoundTemplateSize (qreal width, qreal height, Unit unit) const
Private Slots
void ConvertPaperSize ()
void ConvertLayoutSize ()
void TemplateSelected ()
void FindTemplate ()
void PaperSizeChanged ()
void Swap (bool checked)
void RestoreDefaults ()
void PrinterMargins ()
void CorrectMaxFileds ()
void IgnoreAllFields (int state)
Private Member Functions
void InitPaperUnits ()
void InitLayoutUnits ()
void InitPrinter ()
QSizeF Template ()
QMarginsF MinPrinterFields () const
QMarginsF GetDefPrinterFields () const
Unit PaperUnit () const
Unit LayoutUnit () const
void CorrectPaperDecimals ()
void CorrectLayoutDecimals ()
void MinimumPaperSize ()
void MinimumLayoutSize ()
void ReadSettings ()
void WriteSettings () const
void SheetSize (const QSizeF &size)
void SetAdditionalOptions (bool value)
Private Attributes
Ui::LayoutSettingsDialog * ui
bool disableSettings
Unit oldPaperUnit
Unit oldLayoutUnit
VLayoutGenerator * generator
bool isInitialized
Detailed Description
Definition at line 66 of file layoutsettings_dialog.h.
Constructor & Destructor Documentation
LayoutSettingsDialog()
LayoutSettingsDialog::LayoutSettingsDialog (VLayoutGenerator * generator, QWidget * parent = nullptr, bool disableSettings = false) explicit
Definition at line 61 of file layoutsettings_dialog.cpp.
References ConvertLayoutSize(), ConvertPaperSize(), CorrectMaxFileds(), DialogAccepted(), disableSettings, FindTemplate(), IgnoreAllFields(), InitLayoutUnits(), InitPaperUnits(), InitPrinter(), MinimumLayoutSize(), MinimumPaperSize(), Mm, PaperSizeChanged(), PrinterMargins(), qApp, ReadSettings(), RestoreDefaults(), Swap(), TemplateSelected(), and ui.
~LayoutSettingsDialog()
LayoutSettingsDialog::~LayoutSettingsDialog () virtual
Definition at line 131 of file layoutsettings_dialog.cpp.
References ui.
Member Function Documentation
ConvertLayoutSize
void LayoutSettingsDialog::ConvertLayoutSize () private slot
Definition at line 510 of file layoutsettings_dialog.cpp.
References CorrectLayoutDecimals(), FromPixel(), LayoutUnit(), MinimumLayoutSize(), oldLayoutUnit, QIMAGE_MAX, ui, and UnitConvertor().
Referenced by LayoutSettingsDialog().
ConvertPaperSize
void LayoutSettingsDialog::ConvertPaperSize () private slot
Definition at line 408 of file layoutsettings_dialog.cpp.
References CorrectPaperDecimals(), FromPixel(), MinimumPaperSize(), oldPaperUnit, PaperUnit(), QIMAGE_MAX, ui, and UnitConvertor().
Referenced by LayoutSettingsDialog().
CorrectLayoutDecimals()
void LayoutSettingsDialog::CorrectLayoutDecimals () private
Definition at line 920 of file layoutsettings_dialog.cpp.
References Cm, Inch, Mm, oldLayoutUnit, Px, and ui.
Referenced by ConvertLayoutSize().
CorrectMaxFileds
void LayoutSettingsDialog::CorrectMaxFileds () private slot
Definition at line 704 of file layoutsettings_dialog.cpp.
References ui.
Referenced by LayoutSettingsDialog(), ReadSettings(), and RestoreDefaults().
CorrectPaperDecimals()
void LayoutSettingsDialog::CorrectPaperDecimals () private
Definition at line 890 of file layoutsettings_dialog.cpp.
References Cm, Inch, Mm, oldPaperUnit, Px, and ui.
Referenced by ConvertPaperSize(), and SheetSize().
DialogAccepted
void LayoutSettingsDialog::DialogAccepted () slot
Definition at line 578 of file layoutsettings_dialog.cpp.
References disableSettings, generator, GetAutoCrop(), GetFields(), GetGroup(), GetIncrease(), GetLayoutWidth(), GetMultiplier(), GetPaperHeight(), GetPaperWidth(), GetRotate(), GetShift(), IsIgnoreAllFields(), IsSaveLength(), IsStripOptimization(), isTextAsPaths(), IsUnitePages(), LayoutUnit(), MinPrinterFields(), Px, SCASSERT, VLayoutGenerator::SetAutoCrop(), VLayoutGenerator::SetCaseType(), VLayoutGenerator::SetLayoutWidth(), VLayoutGenerator::SetMultiplier(), VLayoutGenerator::SetPaperHeight(), VLayoutGenerator::SetPaperWidth(), VLayoutGenerator::SetPrinterFields(), VLayoutGenerator::SetRotate(), VLayoutGenerator::SetRotationIncrease(), VLayoutGenerator::SetSaveLength(), VLayoutGenerator::SetShift(), VLayoutGenerator::SetStripOptimization(), VLayoutGenerator::SetTestAsPaths(), VLayoutGenerator::SetUnitePages(), ui, UnitConvertor(), and WriteSettings().
Referenced by VCommandLine::DefaultGenerator(), and LayoutSettingsDialog().
FindTemplate
void LayoutSettingsDialog::FindTemplate () private slot
Definition at line 373 of file layoutsettings_dialog.cpp.
References Custom, getTemplateSize(), PaperUnit(), and ui.
Referenced by LayoutSettingsDialog(), and ReadSettings().
GetAutoCrop()
bool LayoutSettingsDialog::GetAutoCrop () const
Definition at line 277 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
GetDefPrinterFields()
QMarginsF LayoutSettingsDialog::GetDefPrinterFields () const private
Definition at line 864 of file layoutsettings_dialog.cpp.
References GetPrinterFields(), and ui.
Referenced by ReadSettings(), and RestoreDefaults().
GetFields()
QMarginsF LayoutSettingsDialog::GetFields () const
Definition at line 187 of file layoutsettings_dialog.cpp.
References oldLayoutUnit, Px, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator(), DialogAccepted(), and WriteSettings().
GetGroup()
Cases LayoutSettingsDialog::GetGroup () const
Definition at line 207 of file layoutsettings_dialog.cpp.
References CaseDesc, CaseThreeGroup, CaseTwoGroup, and ui.
Referenced by DialogAccepted(), and WriteSettings().
GetIncrease()
int LayoutSettingsDialog::GetIncrease () const
Definition at line 255 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
GetLayoutWidth()
qreal LayoutSettingsDialog::GetLayoutWidth () const
Definition at line 175 of file layoutsettings_dialog.cpp.
References oldLayoutUnit, Px, ui, and UnitConvertor().
Referenced by DialogAccepted(), and WriteSettings().
GetMultiplier()
quint8 LayoutSettingsDialog::GetMultiplier () const
Definition at line 325 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
GetPaperHeight()
qreal LayoutSettingsDialog::GetPaperHeight () const
Definition at line 137 of file layoutsettings_dialog.cpp.
References oldPaperUnit, Px, ui, and UnitConvertor().
Referenced by DialogAccepted(), and WriteSettings().
GetPaperWidth()
qreal LayoutSettingsDialog::GetPaperWidth () const
Definition at line 150 of file layoutsettings_dialog.cpp.
References oldPaperUnit, Px, ui, and UnitConvertor().
Referenced by DialogAccepted(), and WriteSettings().
GetRotate()
bool LayoutSettingsDialog::GetRotate () const
Definition at line 243 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
GetShift()
qreal LayoutSettingsDialog::GetShift () const
Definition at line 163 of file layoutsettings_dialog.cpp.
References oldLayoutUnit, Px, ui, and UnitConvertor().
Referenced by DialogAccepted(), and WriteSettings().
getTemplateSize()
QSizeF LayoutSettingsDialog::getTemplateSize (const PaperSizeFormat & tmpl, const Unit & unit) const protected
LayoutSettingsDialog::TemplateSize.
Parameters
tmpl
unit
Returns
Definition at line 832 of file layoutsettings_dialog.cpp.
References Custom, AbstractLayoutDialog::getTemplateSize(), AbstractLayoutDialog::RoundTemplateSize(), and ui.
Referenced by FindTemplate(), and Template().
IgnoreAllFields
void LayoutSettingsDialog::IgnoreAllFields (int state) private slot
Definition at line 720 of file layoutsettings_dialog.cpp.
References ui.
Referenced by LayoutSettingsDialog(), ReadSettings(), and RestoreDefaults().
InitLayoutUnits()
void LayoutSettingsDialog::InitLayoutUnits () private
Definition at line 746 of file layoutsettings_dialog.cpp.
References Cm, Inch, Mm, oldLayoutUnit, qApp, StrToUnits(), ui, and UnitsToStr().
Referenced by LayoutSettingsDialog().
InitPaperUnits()
void LayoutSettingsDialog::InitPaperUnits () private
Definition at line 729 of file layoutsettings_dialog.cpp.
References Cm, Inch, Mm, oldPaperUnit, Px, qApp, StrToUnits(), ui, and UnitsToStr().
Referenced by LayoutSettingsDialog().
InitPrinter()
void LayoutSettingsDialog::InitPrinter () private
Definition at line 763 of file layoutsettings_dialog.cpp.
References ui.
Referenced by LayoutSettingsDialog(), and RestoreDefaults().
IsIgnoreAllFields()
bool LayoutSettingsDialog::IsIgnoreAllFields () const
Definition at line 337 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
IsSaveLength()
bool LayoutSettingsDialog::IsSaveLength () const
Definition at line 289 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
IsStripOptimization()
bool LayoutSettingsDialog::IsStripOptimization () const
Definition at line 313 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
isTextAsPaths()
bool LayoutSettingsDialog::isTextAsPaths () const
Definition at line 349 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
IsUnitePages()
bool LayoutSettingsDialog::IsUnitePages () const
Definition at line 301 of file layoutsettings_dialog.cpp.
References ui.
Referenced by DialogAccepted(), and WriteSettings().
LayoutToPixels()
qreal LayoutSettingsDialog::LayoutToPixels (qreal value) const
Definition at line 470 of file layoutsettings_dialog.cpp.
References LayoutUnit(), Px, and UnitConvertor().
Referenced by VCommandLine::Lo2Px().
LayoutUnit()
Unit LayoutSettingsDialog::LayoutUnit () const private
Definition at line 884 of file layoutsettings_dialog.cpp.
References StrToUnits(), and ui.
Referenced by ConvertLayoutSize(), DialogAccepted(), LayoutToPixels(), ReadSettings(), SetFields(), SetLayoutWidth(), and SetShift().
MakeGroupsHelp()
QString LayoutSettingsDialog::MakeGroupsHelp () static
Definition at line 482 of file layoutsettings_dialog.cpp.
Referenced by VCommandLine::InitOptions().
MinimumLayoutSize()
void LayoutSettingsDialog::MinimumLayoutSize () private
Definition at line 948 of file layoutsettings_dialog.cpp.
References oldLayoutUnit, Px, ui, and UnitConvertor().
Referenced by ConvertLayoutSize(), and LayoutSettingsDialog().
MinimumPaperSize()
void LayoutSettingsDialog::MinimumPaperSize () private
Definition at line 940 of file layoutsettings_dialog.cpp.
References oldPaperUnit, Px, ui, and UnitConvertor().
Referenced by ConvertPaperSize(), and LayoutSettingsDialog().
MinPrinterFields()
QMarginsF LayoutSettingsDialog::MinPrinterFields () const private
Definition at line 849 of file layoutsettings_dialog.cpp.
References GetMinPrinterFields(), and ui.
Referenced by DialogAccepted().
PageToPixels()
qreal LayoutSettingsDialog::PageToPixels (qreal value) const
Definition at line 476 of file layoutsettings_dialog.cpp.
References PaperUnit(), Px, and UnitConvertor().
Referenced by VCommandLine::Pg2Px().
PaperSizeChanged
void LayoutSettingsDialog::PaperSizeChanged () private slot
Definition at line 531 of file layoutsettings_dialog.cpp.
References ui.
Referenced by LayoutSettingsDialog(), and SheetSize().
PaperUnit()
Unit LayoutSettingsDialog::PaperUnit () const private
Definition at line 878 of file layoutsettings_dialog.cpp.
References StrToUnits(), and ui.
Referenced by ConvertPaperSize(), FindTemplate(), PageToPixels(), SetPaperHeight(), SetPaperWidth(), SheetSize(), and Template().
PrinterMargins
void LayoutSettingsDialog::PrinterMargins () private slot
Definition at line 690 of file layoutsettings_dialog.cpp.
References GetPrinterFields(), SetFields(), and ui.
Referenced by LayoutSettingsDialog().
ReadSettings()
void LayoutSettingsDialog::ReadSettings () private
Definition at line 955 of file layoutsettings_dialog.cpp.
References CorrectMaxFileds(), FindTemplate(), GetDefPrinterFields(), VSettings::GetFields(), VSettings::GetIgnoreAllFields(), VSettings::GetLayoutAutoCrop(), VSettings::GetLayoutGroup(), VSettings::GetLayoutPaperHeight(), VSettings::GetLayoutPaperWidth(), VSettings::GetLayoutRotate(), VSettings::GetLayoutRotationIncrease(), VSettings::GetLayoutSaveLength(), VSettings::GetLayoutShift(), VSettings::GetLayoutUnitePages(), VSettings::GetLayoutWidth(), VSettings::GetMultiplier(), VSettings::GetStripOptimization(), VSettings::GetTextAsPaths(), IgnoreAllFields(), LayoutUnit(), Px, qApp, SetAutoCrop(), SetFields(), SetGroup(), SetIgnoreAllFields(), SetIncrease(), SetLayoutWidth(), SetMultiplier(), SetRotate(), SetSaveLength(), SetShift(), SetStripOptimization(), setTextAsPaths(), SetUnitePages(), SheetSize(), ui, and UnitConvertor().
Referenced by LayoutSettingsDialog().
RestoreDefaults
void LayoutSettingsDialog::RestoreDefaults () private slot
Definition at line 663 of file layoutsettings_dialog.cpp.
References CorrectMaxFileds(), VSettings::GetDefIgnoreAllFields(), VSettings::GetDefLayoutGroup(), VSettings::GetDefLayoutRotate(), VSettings::GetDefLayoutRotationIncrease(), VSettings::GetDefLayoutShift(), VSettings::GetDefLayoutWidth(), VSettings::GetDefMultiplier(), GetDefPrinterFields(), IgnoreAllFields(), InitPrinter(), SetFields(), SetGroup(), SetIgnoreAllFields(), SetIncrease(), SetLayoutWidth(), SetMultiplier(), SetRotate(), SetShift(), TemplateSelected(), and ui.
Referenced by LayoutSettingsDialog().
SelectedPrinter()
QString LayoutSettingsDialog::SelectedPrinter () const
Definition at line 361 of file layoutsettings_dialog.cpp.
References ui.
Referenced by MainWindowsNoGUI::toolLayoutSettings().
SelectLayoutUnit()
bool LayoutSettingsDialog::SelectLayoutUnit (const QString & units)
Definition at line 459 of file layoutsettings_dialog.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator().
SelectPaperUnit()
bool LayoutSettingsDialog::SelectPaperUnit (const QString & units)
Definition at line 448 of file layoutsettings_dialog.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator().
SelectTemplate()
bool LayoutSettingsDialog::SelectTemplate (const PaperSizeFormat & id)
Definition at line 548 of file layoutsettings_dialog.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator().
SetAdditionalOptions()
void LayoutSettingsDialog::SetAdditionalOptions (bool value) private
Definition at line 1018 of file layoutsettings_dialog.cpp.
References SetAutoCrop(), SetSaveLength(), SetStripOptimization(), and SetUnitePages().
Referenced by Template().
SetAutoCrop()
void LayoutSettingsDialog::SetAutoCrop (bool autoCrop)
Definition at line 283 of file layoutsettings_dialog.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and SetAdditionalOptions().
SetFields()
void LayoutSettingsDialog::SetFields (const QMarginsF & value)
Definition at line 198 of file layoutsettings_dialog.cpp.
References LayoutUnit(), Px, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator(), PrinterMargins(), ReadSettings(), and RestoreDefaults().
SetGroup()
void LayoutSettingsDialog::SetGroup (const Cases & value)
Definition at line 225 of file layoutsettings_dialog.cpp.
References CaseDesc, CaseThreeGroup, CaseTwoGroup, and ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetIgnoreAllFields()
void LayoutSettingsDialog::SetIgnoreAllFields (bool value)
Definition at line 343 of file layoutsettings_dialog.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetIncrease()
bool LayoutSettingsDialog::SetIncrease (int increase)
Definition at line 262 of file layoutsettings_dialog.cpp.
References VSettings::GetDefLayoutRotationIncrease(), and ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetLayoutWidth()
void LayoutSettingsDialog::SetLayoutWidth (qreal value)
Definition at line 181 of file layoutsettings_dialog.cpp.
References LayoutUnit(), Px, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetMultiplier()
void LayoutSettingsDialog::SetMultiplier (const quint8 & value)
Definition at line 331 of file layoutsettings_dialog.cpp.
References ui.
Referenced by ReadSettings(), and RestoreDefaults().
SetPaperHeight()
void LayoutSettingsDialog::SetPaperHeight (qreal value)
Definition at line 143 of file layoutsettings_dialog.cpp.
References FromPixel(), PaperUnit(), Px, QIMAGE_MAX, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator().
SetPaperWidth()
void LayoutSettingsDialog::SetPaperWidth (qreal value)
Definition at line 156 of file layoutsettings_dialog.cpp.
References FromPixel(), PaperUnit(), Px, QIMAGE_MAX, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator().
SetRotate()
void LayoutSettingsDialog::SetRotate (bool state)
Definition at line 249 of file layoutsettings_dialog.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetSaveLength()
void LayoutSettingsDialog::SetSaveLength (bool save)
Definition at line 295 of file layoutsettings_dialog.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and SetAdditionalOptions().
SetShift()
void LayoutSettingsDialog::SetShift (qreal value)
Definition at line 169 of file layoutsettings_dialog.cpp.
References LayoutUnit(), Px, ui, and UnitConvertor().
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and RestoreDefaults().
SetStripOptimization()
void LayoutSettingsDialog::SetStripOptimization (bool save)
Definition at line 319 of file layoutsettings_dialog.cpp.
References ui.
Referenced by ReadSettings(), and SetAdditionalOptions().
setTextAsPaths()
void LayoutSettingsDialog::setTextAsPaths (bool value)
Definition at line 355 of file layoutsettings_dialog.cpp.
References ui.
Referenced by ReadSettings().
SetUnitePages()
void LayoutSettingsDialog::SetUnitePages (bool save)
Definition at line 307 of file layoutsettings_dialog.cpp.
References ui.
Referenced by VCommandLine::DefaultGenerator(), ReadSettings(), and SetAdditionalOptions().
SheetSize()
void LayoutSettingsDialog::SheetSize (const QSizeF & size) private
Definition at line 1004 of file layoutsettings_dialog.cpp.
References CorrectPaperDecimals(), FromPixel(), oldPaperUnit, PaperSizeChanged(), PaperUnit(), QIMAGE_MAX, and ui.
Referenced by ReadSettings(), and TemplateSelected().
showEvent()
void LayoutSettingsDialog::showEvent (QShowEvent * event) protected virtual
Definition at line 489 of file layoutsettings_dialog.cpp.
References isInitialized.
Swap
void LayoutSettingsDialog::Swap (bool checked) private slot
Definition at line 560 of file layoutsettings_dialog.cpp.
References ui.
Referenced by LayoutSettingsDialog().
Template()
QSizeF LayoutSettingsDialog::Template () private
Definition at line 789 of file layoutsettings_dialog.cpp.
References A0, A1, A2, A3, A4, AnsiC, AnsiD, AnsiE, Custom, getTemplateSize(), Legal, Letter, PaperUnit(), Roll24in, Roll30in, Roll36in, Roll42in, Roll44in, SetAdditionalOptions(), Tabloid, and ui.
Referenced by TemplateSelected().
TemplateSelected
void LayoutSettingsDialog::TemplateSelected () private slot
Definition at line 367 of file layoutsettings_dialog.cpp.
References SheetSize(), and Template().
Referenced by LayoutSettingsDialog(), and RestoreDefaults().
WriteSettings()
void LayoutSettingsDialog::WriteSettings () const private
Definition at line 983 of file layoutsettings_dialog.cpp.
References GetAutoCrop(), GetFields(), GetGroup(), GetIncrease(), GetLayoutWidth(), GetMultiplier(), GetPaperHeight(), GetPaperWidth(), GetRotate(), GetShift(), IsIgnoreAllFields(), IsSaveLength(), IsStripOptimization(), isTextAsPaths(), IsUnitePages(), qApp, VSettings::SetFields(), VSettings::SetIgnoreAllFields(), VSettings::SetLayoutAutoCrop(), VSettings::SetLayoutGroup(), VSettings::SetLayoutPaperHeight(), VSettings::SetLayoutPaperWidth(), VSettings::SetLayoutRotate(), VSettings::SetLayoutRotationIncrease(), VSettings::SetLayoutSaveLength(), VSettings::SetLayoutShift(), VSettings::SetLayoutUnitePages(), VSettings::SetLayoutWidth(), VSettings::SetMultiplier(), VSettings::SetStripOptimization(), and VSettings::setTextAsPaths().
Referenced by DialogAccepted().
Member Data Documentation
disableSettings
bool LayoutSettingsDialog::disableSettings private
Definition at line 153 of file layoutsettings_dialog.h.
Referenced by DialogAccepted(), and LayoutSettingsDialog().
generator
VLayoutGenerator* LayoutSettingsDialog::generator private
Definition at line 156 of file layoutsettings_dialog.h.
Referenced by DialogAccepted().
isInitialized
bool LayoutSettingsDialog::isInitialized private
Definition at line 157 of file layoutsettings_dialog.h.
Referenced by showEvent().
oldLayoutUnit
Unit LayoutSettingsDialog::oldLayoutUnit private
Definition at line 155 of file layoutsettings_dialog.h.
Referenced by ConvertLayoutSize(), CorrectLayoutDecimals(), GetFields(), GetLayoutWidth(), GetShift(), InitLayoutUnits(), and MinimumLayoutSize().
oldPaperUnit
Unit LayoutSettingsDialog::oldPaperUnit private
Definition at line 154 of file layoutsettings_dialog.h.
Referenced by ConvertPaperSize(), CorrectPaperDecimals(), GetPaperHeight(), GetPaperWidth(), InitPaperUnits(), MinimumPaperSize(), and SheetSize().
ui
Ui::LayoutSettingsDialog* LayoutSettingsDialog::ui private
Definition at line 152 of file layoutsettings_dialog.h.
Referenced by ConvertLayoutSize(), ConvertPaperSize(), CorrectLayoutDecimals(), CorrectMaxFileds(), CorrectPaperDecimals(), DialogAccepted(), FindTemplate(), GetAutoCrop(), GetDefPrinterFields(), GetFields(), GetGroup(), GetIncrease(), GetLayoutWidth(), GetMultiplier(), GetPaperHeight(), GetPaperWidth(), GetRotate(), GetShift(), getTemplateSize(), IgnoreAllFields(), InitLayoutUnits(), InitPaperUnits(), InitPrinter(), IsIgnoreAllFields(), IsSaveLength(), IsStripOptimization(), isTextAsPaths(), IsUnitePages(), LayoutSettingsDialog(), LayoutUnit(), MinimumLayoutSize(), MinimumPaperSize(), MinPrinterFields(), PaperSizeChanged(), PaperUnit(), PrinterMargins(), ReadSettings(), RestoreDefaults(), SelectedPrinter(), SelectLayoutUnit(), SelectPaperUnit(), SelectTemplate(), SetAutoCrop(), SetFields(), SetGroup(), SetIgnoreAllFields(), SetIncrease(), SetLayoutWidth(), SetMultiplier(), SetPaperHeight(), SetPaperWidth(), SetRotate(), SetSaveLength(), SetShift(), SetStripOptimization(), setTextAsPaths(), SetUnitePages(), SheetSize(), Swap(), Template(), and ~LayoutSettingsDialog().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/layoutsettings_dialog.h
src/app/seamly2d/dialogs/layoutsettings_dialog.cpp