Seamly2D: MoveDoubleLabel Class Reference
MoveDoubleLabel Class Reference
#include <movedoublelabel.h>
Public Member Functions
MoveDoubleLabel (VAbstractPattern *doc, const QPointF &pos, MoveDoublePoint type, quint32 toolId, quint32 pointId, QUndoCommand *parent=nullptr)
virtual ~MoveDoubleLabel ()=default
virtual bool mergeWith (const QUndoCommand *command) Q_DECL_OVERRIDE
virtual int id () const Q_DECL_OVERRIDE
quint32 GetToolId () const
MoveDoublePoint GetPointType () const
Public Member Functions inherited from MoveAbstractLabel
MoveAbstractLabel (VAbstractPattern *doc, quint32 pointId, const QPointF &pos, QUndoCommand *parent=nullptr)
virtual ~MoveAbstractLabel ()=default
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
quint32 GetPointId () const
QPointF GetNewPos () const
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Protected Member Functions
virtual void Do (const QPointF &pos) Q_DECL_OVERRIDE
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Private Attributes
MoveDoublePoint m_type
quint32 m_idTool
QGraphicsScene * m_scene
Additional Inherited Members
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Protected Attributes inherited from MoveAbstractLabel
QPointF m_oldPos
QPointF m_newPos
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 65 of file movedoublelabel.h.
Constructor & Destructor Documentation
MoveDoubleLabel()
MoveDoubleLabel::MoveDoubleLabel (VAbstractPattern * doc, const QPointF & pos, MoveDoublePoint type, quint32 toolId, quint32 pointId, QUndoCommand * parent = nullptr)
Definition at line 67 of file movedoublelabel.cpp.
References AttrMx1, AttrMx2, AttrMy1, AttrMy2, VUndoCommand::doc, VDomDocument::elementById(), FirstPoint, VDomDocument::GetParametrDouble(), m_idTool, MoveAbstractLabel::m_oldPos, VUndoCommand::nodeId, qApp, and VAbstractPattern::TagPoint.
~MoveDoubleLabel()
virtual MoveDoubleLabel::~MoveDoubleLabel () virtual default
Member Function Documentation
Do()
void MoveDoubleLabel::Do (const QPointF & pos) protected virtual
Implements MoveAbstractLabel.
Definition at line 145 of file movedoublelabel.cpp.
References AttrMx1, AttrMx2, AttrMy1, AttrMy2, VUndoCommand::doc, VDomDocument::elementById(), FirstPoint, VAbstractPattern::getTool(), m_idTool, m_type, VUndoCommand::nodeId, qApp, VDomDocument::SetAttribute(), and VAbstractPattern::TagPoint.
GetPointType()
MoveDoublePoint MoveDoubleLabel::GetPointType () const inline
Definition at line 91 of file movedoublelabel.h.
References m_type.
Referenced by mergeWith().
GetToolId()
quint32 MoveDoubleLabel::GetToolId () const inline
Definition at line 97 of file movedoublelabel.h.
References m_idTool.
Referenced by mergeWith().
id()
int MoveDoubleLabel::id () const virtual
Definition at line 139 of file movedoublelabel.cpp.
References MoveDoubleLabel.
mergeWith()
bool MoveDoubleLabel::mergeWith (const QUndoCommand * command) virtual
Definition at line 111 of file movedoublelabel.cpp.
References FirstPoint, MoveAbstractLabel::GetNewPos(), MoveAbstractLabel::GetPointId(), GetPointType(), GetToolId(), m_idTool, MoveAbstractLabel::m_newPos, m_type, VUndoCommand::nodeId, and SCASSERT.
Member Data Documentation
m_idTool
quint32 MoveDoubleLabel::m_idTool private
Definition at line 85 of file movedoublelabel.h.
Referenced by Do(), GetToolId(), mergeWith(), and MoveDoubleLabel().
m_scene
QGraphicsScene* MoveDoubleLabel::m_scene private
Definition at line 87 of file movedoublelabel.h.
m_type
MoveDoublePoint MoveDoubleLabel::m_type private
Definition at line 84 of file movedoublelabel.h.
Referenced by Do(), GetPointType(), and mergeWith().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/label/movedoublelabel.h
src/libs/vtools/undocommands/label/movedoublelabel.cpp