Seamly2D: TST_BuitInRegExp Class Reference
TST_BuitInRegExp Class Reference
#include <tst_buitinregexp.h>
Public Member Functions
TST_BuitInRegExp (const QString &locale, QObject *parent=nullptr)
virtual ~TST_BuitInRegExp () Q_DECL_EQ_DEFAULT
Public Member Functions inherited from TST_AbstractRegExp
TST_AbstractRegExp (const QString &locale, QObject *parent=nullptr)
virtual ~TST_AbstractRegExp ()
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Protected Member Functions
virtual void PrepareData () Q_DECL_OVERRIDE
virtual QStringList AllNames () Q_DECL_OVERRIDE
Protected Member Functions inherited from TST_AbstractRegExp
int LoadVariables (const QString &checkedLocale)
void RemoveTrVariables (const QString &checkedLocale)
void InitTrMs ()
void CallTestCheckNoEndLine ()
void CallTestCheckRegExpNames ()
void CallTestCheckIsNamesUnique ()
void CallTestCheckNoOriginalNamesInTranslation ()
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Private Slots
void initTestCase ()
void TestCheckNoEndLine_data ()
void TestCheckNoEndLine ()
void TestCheckRegExpNames_data ()
void TestCheckRegExpNames ()
void TestCheckIsNamesUnique_data ()
void TestCheckIsNamesUnique ()
void TestCheckNoOriginalNamesInTranslation_data ()
void TestCheckNoOriginalNamesInTranslation ()
void TestCheckUnderlineExists_data ()
void TestCheckUnderlineExists ()
void TestCheckInternalVaribleRegExp_data ()
void TestCheckInternalVaribleRegExp ()
void TestTemplatePlaceholders ()
void cleanupTestCase ()
Additional Inherited Members
Protected Attributes inherited from TST_AbstractRegExp
QString m_locale
QPointer< QTranslator > m_vTranslator
VTranslateVars * m_trMs
Detailed Description
Definition at line 62 of file tst_buitinregexp.h.
Constructor & Destructor Documentation
TST_BuitInRegExp()
TST_BuitInRegExp::TST_BuitInRegExp (const QString & locale, QObject * parent = nullptr) explicit
Definition at line 63 of file tst_buitinregexp.cpp.
~TST_BuitInRegExp()
virtual TST_BuitInRegExp::~TST_BuitInRegExp () virtual
Member Function Documentation
AllNames()
QStringList TST_BuitInRegExp::AllNames () protected virtual
Implements TST_AbstractRegExp.
Definition at line 287 of file tst_buitinregexp.cpp.
References builInFunctions, and builInVariables.
Referenced by PrepareData(), and TestCheckInternalVaribleRegExp_data().
cleanupTestCase
void TST_BuitInRegExp::cleanupTestCase () private slot
Definition at line 267 of file tst_buitinregexp.cpp.
References TST_AbstractRegExp::m_locale, and TST_AbstractRegExp::RemoveTrVariables().
initTestCase
void TST_BuitInRegExp::initTestCase () private slot
Definition at line 69 of file tst_buitinregexp.cpp.
References TST_AbstractRegExp::InitTrMs(), TST_AbstractRegExp::LoadVariables(), TST_AbstractRegExp::m_locale, NoError, and SupportedLocales().
PrepareData()
void TST_BuitInRegExp::PrepareData () protected virtual
Implements TST_AbstractRegExp.
Definition at line 273 of file tst_buitinregexp.cpp.
References AllNames(), and TST_AbstractRegExp::m_locale.
Referenced by TestCheckIsNamesUnique_data(), TestCheckNoEndLine_data(), TestCheckNoOriginalNamesInTranslation_data(), and TestCheckRegExpNames_data().
TestCheckInternalVaribleRegExp
void TST_BuitInRegExp::TestCheckInternalVaribleRegExp () private slot
Definition at line 220 of file tst_buitinregexp.cpp.
References VTranslateVars::InternalVarToUser(), TST_AbstractRegExp::m_trMs, and VTranslateVars::VarToUser().
TestCheckInternalVaribleRegExp_data
void TST_BuitInRegExp::TestCheckInternalVaribleRegExp_data () private slot
Definition at line 203 of file tst_buitinregexp.cpp.
References AllNames(), builInVariables, and TST_AbstractRegExp::m_locale.
TestCheckIsNamesUnique
void TST_BuitInRegExp::TestCheckIsNamesUnique () private slot
Definition at line 123 of file tst_buitinregexp.cpp.
References TST_AbstractRegExp::CallTestCheckIsNamesUnique().
TestCheckIsNamesUnique_data
void TST_BuitInRegExp::TestCheckIsNamesUnique_data () private slot
Definition at line 117 of file tst_buitinregexp.cpp.
References PrepareData().
TestCheckNoEndLine
void TST_BuitInRegExp::TestCheckNoEndLine () private slot
Definition at line 99 of file tst_buitinregexp.cpp.
References TST_AbstractRegExp::CallTestCheckNoEndLine().
TestCheckNoEndLine_data
void TST_BuitInRegExp::TestCheckNoEndLine_data () private slot
Definition at line 93 of file tst_buitinregexp.cpp.
References PrepareData().
TestCheckNoOriginalNamesInTranslation
void TST_BuitInRegExp::TestCheckNoOriginalNamesInTranslation () private slot
Definition at line 135 of file tst_buitinregexp.cpp.
References TST_AbstractRegExp::CallTestCheckNoOriginalNamesInTranslation().
TestCheckNoOriginalNamesInTranslation_data
void TST_BuitInRegExp::TestCheckNoOriginalNamesInTranslation_data () private slot
Definition at line 129 of file tst_buitinregexp.cpp.
References PrepareData().
TestCheckRegExpNames
void TST_BuitInRegExp::TestCheckRegExpNames () private slot
Definition at line 111 of file tst_buitinregexp.cpp.
References TST_AbstractRegExp::CallTestCheckRegExpNames().
TestCheckRegExpNames_data
void TST_BuitInRegExp::TestCheckRegExpNames_data () private slot
Definition at line 105 of file tst_buitinregexp.cpp.
References PrepareData().
TestCheckUnderlineExists
void TST_BuitInRegExp::TestCheckUnderlineExists () private slot
Definition at line 188 of file tst_buitinregexp.cpp.
References VTranslateVars::InternalVarToUser(), and TST_AbstractRegExp::m_trMs.
TestCheckUnderlineExists_data
void TST_BuitInRegExp::TestCheckUnderlineExists_data () private slot
Definition at line 141 of file tst_buitinregexp.cpp.
References angle1Arc_, angle1ElArc_, angle1Spl_, angle1SplPath, angle2Arc_, angle2ElArc_, angle2Spl_, angle2SplPath, angleLine_, arc_, builInVariables, c1LengthSpl_, c1LengthSplPath, c2LengthSpl_, c2LengthSplPath, currentLength, currentSeamAllowance, elarc_, line_, TST_AbstractRegExp::m_locale, measurement_, radius1ElArc_, radius2ElArc_, radiusArc_, seg_, spl_, splPath, and variable_.
TestTemplatePlaceholders
void TST_BuitInRegExp::TestTemplatePlaceholders () private slot
Definition at line 251 of file tst_buitinregexp.cpp.
References labelTemplatePlaceholders, TST_AbstractRegExp::m_trMs, and VTranslateVars::PlaceholderToUser().
The documentation for this class was generated from the following files:
src/test/TranslationsTest/tst_buitinregexp.h
src/test/TranslationsTest/tst_buitinregexp.cpp