Seamly2D: VBestSquare Class Reference
VBestSquare Class Reference
#include <vbestsquare.h>
Public Member Functions
VBestSquare (const QSizeF &sheetSize, bool saveLength)
void NewResult (const QSizeF &candidate, int i, int j, const QTransform &transform, bool mirror, BestFrom type)
void NewResult (const VBestSquare &best)
QSizeF BestSize () const
int GContourEdge () const
int pieceEdge () const
QTransform Transform () const
bool ValidResult () const
bool isMirror () const
BestFrom Type () const
bool IsSaveLength () const
Static Private Member Functions
static qint64 Square (const QSizeF &size)
Private Attributes
int resI
int resJ
QTransform resTransform
QSizeF bestSize
qreal sheetWidth
bool valideResult
bool resMirror
BestFrom type
bool saveLength
Detailed Description
Definition at line 61 of file vbestsquare.h.
Constructor & Destructor Documentation
VBestSquare()
VBestSquare::VBestSquare (const QSizeF & sheetSize, bool saveLength)
Definition at line 57 of file vbestsquare.cpp.
References Rotation.
Member Function Documentation
BestSize()
QSizeF VBestSquare::BestSize () const
Definition at line 113 of file vbestsquare.cpp.
References bestSize.
Referenced by NewResult().
GContourEdge()
int VBestSquare::GContourEdge () const
Definition at line 119 of file vbestsquare.cpp.
References resI.
Referenced by NewResult(), and VLayoutPaper::SaveResult().
isMirror()
bool VBestSquare::isMirror () const
Definition at line 143 of file vbestsquare.cpp.
References resMirror.
Referenced by NewResult(), and VLayoutPaper::SaveResult().
IsSaveLength()
bool VBestSquare::IsSaveLength () const
Definition at line 155 of file vbestsquare.cpp.
References saveLength.
Referenced by NewResult().
NewResult() [1/2]
void VBestSquare::NewResult (const QSizeF & candidate, int i, int j, const QTransform & transform, bool mirror, BestFrom type)
Definition at line 69 of file vbestsquare.cpp.
References bestSize, resI, resJ, resMirror, resTransform, saveLength, sheetWidth, Square(), type, and valideResult.
Referenced by VLayoutPaper::AddToSheet(), NewResult(), and VPosition::SaveCandidate().
NewResult() [2/2]
void VBestSquare::NewResult (const VBestSquare & best)
Definition at line 104 of file vbestsquare.cpp.
References BestSize(), GContourEdge(), isMirror(), IsSaveLength(), NewResult(), pieceEdge(), saveLength, Transform(), Type(), and ValidResult().
pieceEdge()
int VBestSquare::pieceEdge () const
Definition at line 125 of file vbestsquare.cpp.
References resJ.
Referenced by NewResult(), and VLayoutPaper::SaveResult().
Square()
qint64 VBestSquare::Square (const QSizeF & size) static private
Definition at line 161 of file vbestsquare.cpp.
Referenced by NewResult().
Transform()
QTransform VBestSquare::Transform () const
Definition at line 131 of file vbestsquare.cpp.
References resTransform.
Referenced by NewResult(), and VLayoutPaper::SaveResult().
Type()
BestFrom VBestSquare::Type () const
Definition at line 149 of file vbestsquare.cpp.
References type.
Referenced by NewResult(), and VLayoutPaper::SaveResult().
ValidResult()
bool VBestSquare::ValidResult () const
Definition at line 137 of file vbestsquare.cpp.
References valideResult.
Referenced by NewResult(), and VLayoutPaper::SaveResult().
Member Data Documentation
bestSize
QSizeF VBestSquare::bestSize private
Definition at line 84 of file vbestsquare.h.
Referenced by BestSize(), and NewResult().
resI
int VBestSquare::resI private
Definition at line 81 of file vbestsquare.h.
Referenced by GContourEdge(), and NewResult().
resJ
int VBestSquare::resJ private
Definition at line 82 of file vbestsquare.h.
Referenced by NewResult(), and pieceEdge().
resMirror
bool VBestSquare::resMirror private
Definition at line 87 of file vbestsquare.h.
Referenced by isMirror(), and NewResult().
resTransform
QTransform VBestSquare::resTransform private
Definition at line 83 of file vbestsquare.h.
Referenced by NewResult(), and Transform().
saveLength
bool VBestSquare::saveLength private
Definition at line 89 of file vbestsquare.h.
Referenced by IsSaveLength(), and NewResult().
sheetWidth
qreal VBestSquare::sheetWidth private
Definition at line 85 of file vbestsquare.h.
Referenced by NewResult().
type
BestFrom VBestSquare::type private
Definition at line 88 of file vbestsquare.h.
Referenced by NewResult(), and Type().
valideResult
bool VBestSquare::valideResult private
Definition at line 86 of file vbestsquare.h.
Referenced by NewResult(), and ValidResult().
The documentation for this class was generated from the following files:
src/libs/vlayout/vbestsquare.h
src/libs/vlayout/vbestsquare.cpp