Seamly2D: DialogNewMeasurements Class Reference
DialogNewMeasurements Class Reference
#include <dialognewmeasurements.h>
Public Member Functions
DialogNewMeasurements (QWidget *parent=nullptr)
~DialogNewMeasurements ()
MeasurementsType Type () const
Unit MUnit () const
int BaseSize () const
int BaseHeight () const
Protected Member Functions
virtual void changeEvent (QEvent *event) Q_DECL_OVERRIDE
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
Private Slots
void CurrentTypeChanged (int index)
void CurrentUnitChanged (int index)
Private Member Functions
void InitMTypes ()
void InitHeightsList ()
void InitSizesList ()
void InitUnits (const MeasurementsType &type)
Private Attributes
Ui::DialogNewMeasurements * ui
bool isInitialized
Detailed Description
Definition at line 64 of file dialognewmeasurements.h.
Constructor & Destructor Documentation
DialogNewMeasurements()
DialogNewMeasurements::DialogNewMeasurements (QWidget * parent = nullptr) explicit
Definition at line 62 of file dialognewmeasurements.cpp.
References Cm, CurrentTypeChanged(), CurrentUnitChanged(), VSeamlyMeSettings::GetDefHeight(), VSeamlyMeSettings::GetDefSize(), Individual, InitHeightsList(), InitMTypes(), InitSizesList(), InitUnits(), MUnit(), qApp, ui, and UnitConvertor().
~DialogNewMeasurements()
DialogNewMeasurements::~DialogNewMeasurements ()
Definition at line 98 of file dialognewmeasurements.cpp.
References ui.
Member Function Documentation
BaseHeight()
int DialogNewMeasurements::BaseHeight () const
Definition at line 122 of file dialognewmeasurements.cpp.
References ui.
Referenced by TMainWindow::FileNew().
BaseSize()
int DialogNewMeasurements::BaseSize () const
Definition at line 116 of file dialognewmeasurements.cpp.
References ui.
Referenced by TMainWindow::FileNew().
changeEvent()
void DialogNewMeasurements::changeEvent (QEvent * event) protected virtual
Definition at line 128 of file dialognewmeasurements.cpp.
References InitMTypes(), InitUnits(), and ui.
CurrentTypeChanged
void DialogNewMeasurements::CurrentTypeChanged (int index) private slot
Definition at line 164 of file dialognewmeasurements.cpp.
References InitUnits(), Multisize, and ui.
Referenced by DialogNewMeasurements().
CurrentUnitChanged
void DialogNewMeasurements::CurrentUnitChanged (int index) private slot
Definition at line 181 of file dialognewmeasurements.cpp.
References Inch, InitHeightsList(), InitSizesList(), MUnit(), and ui.
Referenced by DialogNewMeasurements().
InitHeightsList()
void DialogNewMeasurements::InitHeightsList () private
Definition at line 220 of file dialognewmeasurements.cpp.
References MUnit(), ui, and VMeasurement::WholeListHeights().
Referenced by CurrentUnitChanged(), and DialogNewMeasurements().
InitMTypes()
void DialogNewMeasurements::InitMTypes () private
Definition at line 198 of file dialognewmeasurements.cpp.
References Individual, Multisize, ui, and Unknown.
Referenced by changeEvent(), and DialogNewMeasurements().
InitSizesList()
void DialogNewMeasurements::InitSizesList () private
Definition at line 228 of file dialognewmeasurements.cpp.
References MUnit(), ui, and VMeasurement::WholeListSizes().
Referenced by CurrentUnitChanged(), and DialogNewMeasurements().
InitUnits()
void DialogNewMeasurements::InitUnits (const MeasurementsType & type) private
Definition at line 236 of file dialognewmeasurements.cpp.
References Cm, Inch, Individual, Mm, and ui.
Referenced by changeEvent(), CurrentTypeChanged(), and DialogNewMeasurements().
MUnit()
Unit DialogNewMeasurements::MUnit () const
Definition at line 110 of file dialognewmeasurements.cpp.
References ui.
Referenced by CurrentUnitChanged(), DialogNewMeasurements(), TMainWindow::FileNew(), InitHeightsList(), and InitSizesList().
showEvent()
void DialogNewMeasurements::showEvent (QShowEvent * event) protected virtual
Definition at line 143 of file dialognewmeasurements.cpp.
References isInitialized.
Type()
MeasurementsType DialogNewMeasurements::Type () const
Definition at line 104 of file dialognewmeasurements.cpp.
References ui.
Referenced by TMainWindow::FileNew().
Member Data Documentation
isInitialized
bool DialogNewMeasurements::isInitialized private
Definition at line 88 of file dialognewmeasurements.h.
Referenced by showEvent().
ui
Ui::DialogNewMeasurements* DialogNewMeasurements::ui private
Definition at line 87 of file dialognewmeasurements.h.
Referenced by BaseHeight(), BaseSize(), changeEvent(), CurrentTypeChanged(), CurrentUnitChanged(), DialogNewMeasurements(), InitHeightsList(), InitMTypes(), InitSizesList(), InitUnits(), MUnit(), Type(), and ~DialogNewMeasurements().
The documentation for this class was generated from the following files:
src/app/seamlyme/dialogs/dialognewmeasurements.h
src/app/seamlyme/dialogs/dialognewmeasurements.cpp