Seamly2D: DTDGrammar Class Reference
DTDGrammar Class Reference
#include <DTDGrammar.hpp>
Public Member Functions
DTDGrammar (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~DTDGrammar ()
virtual Grammar::GrammarType getGrammarType () const
virtual const XMLCh * getTargetNamespace () const
virtual XMLElementDecl * findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool &wasAdded)
virtual XMLSize_t getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual const XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope)
virtual const XMLElementDecl * getElemDecl (const unsigned int elemId) const
virtual XMLElementDecl * getElemDecl (const unsigned int elemId)
virtual const XMLNotationDecl * getNotationDecl (const XMLCh *const notName) const
virtual XMLNotationDecl * getNotationDecl (const XMLCh *const notName)
virtual bool getValidated () const
virtual XMLElementDecl * putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared=false)
virtual XMLSize_t putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared=false)
virtual XMLSize_t putNotationDecl (XMLNotationDecl *const notationDecl) const
virtual void setValidated (const bool newState)
virtual void reset ()
const DTDEntityDecl * getEntityDecl (const XMLCh *const entName) const
DTDEntityDecl * getEntityDecl (const XMLCh *const entName)
NameIdPool< DTDEntityDecl > * getEntityDeclPool ()
const NameIdPool< DTDEntityDecl > * getEntityDeclPool () const
NameIdPoolEnumerator< DTDElementDecl > getElemEnumerator () const
NameIdPoolEnumerator< DTDEntityDecl > getEntityEnumerator () const
NameIdPoolEnumerator< XMLNotationDecl > getNotationEnumerator () const
virtual void setGrammarDescription (XMLGrammarDescription *)
virtual XMLGrammarDescription * getGrammarDescription () const
XMLSize_t putEntityDecl (DTDEntityDecl *const entityDecl) const
DTDGrammar (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~DTDGrammar ()
virtual Grammar::GrammarType getGrammarType () const
virtual const XMLCh * getTargetNamespace () const
virtual XMLElementDecl * findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool &wasAdded)
virtual XMLSize_t getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual const XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope)
virtual const XMLElementDecl * getElemDecl (const unsigned int elemId) const
virtual XMLElementDecl * getElemDecl (const unsigned int elemId)
virtual const XMLNotationDecl * getNotationDecl (const XMLCh *const notName) const
virtual XMLNotationDecl * getNotationDecl (const XMLCh *const notName)
virtual bool getValidated () const
virtual XMLElementDecl * putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared=false)
virtual XMLSize_t putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared=false)
virtual XMLSize_t putNotationDecl (XMLNotationDecl *const notationDecl) const
virtual void setValidated (const bool newState)
virtual void reset ()
const DTDEntityDecl * getEntityDecl (const XMLCh *const entName) const
DTDEntityDecl * getEntityDecl (const XMLCh *const entName)
NameIdPool< DTDEntityDecl > * getEntityDeclPool ()
const NameIdPool< DTDEntityDecl > * getEntityDeclPool () const
NameIdPoolEnumerator< DTDElementDecl > getElemEnumerator () const
NameIdPoolEnumerator< DTDEntityDecl > getEntityEnumerator () const
NameIdPoolEnumerator< XMLNotationDecl > getNotationEnumerator () const
virtual void setGrammarDescription (XMLGrammarDescription *)
virtual XMLGrammarDescription * getGrammarDescription () const
XMLSize_t putEntityDecl (DTDEntityDecl *const entityDecl) const
DTDGrammar (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
virtual ~DTDGrammar ()
virtual Grammar::GrammarType getGrammarType () const
virtual const XMLCh * getTargetNamespace () const
virtual XMLElementDecl * findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool &wasAdded)
virtual XMLSize_t getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual const XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const
virtual XMLElementDecl * getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope)
virtual const XMLElementDecl * getElemDecl (const unsigned int elemId) const
virtual XMLElementDecl * getElemDecl (const unsigned int elemId)
virtual const XMLNotationDecl * getNotationDecl (const XMLCh *const notName) const
virtual XMLNotationDecl * getNotationDecl (const XMLCh *const notName)
virtual bool getValidated () const
virtual XMLElementDecl * putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared=false)
virtual XMLSize_t putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared=false)
virtual XMLSize_t putNotationDecl (XMLNotationDecl *const notationDecl) const
virtual void setValidated (const bool newState)
virtual void reset ()
const DTDEntityDecl * getEntityDecl (const XMLCh *const entName) const
DTDEntityDecl * getEntityDecl (const XMLCh *const entName)
NameIdPool< DTDEntityDecl > * getEntityDeclPool ()
const NameIdPool< DTDEntityDecl > * getEntityDeclPool () const
NameIdPoolEnumerator< DTDElementDecl > getElemEnumerator () const
NameIdPoolEnumerator< DTDEntityDecl > getEntityEnumerator () const
NameIdPoolEnumerator< XMLNotationDecl > getNotationEnumerator () const
virtual void setGrammarDescription (XMLGrammarDescription *)
virtual XMLGrammarDescription * getGrammarDescription () const
XMLSize_t putEntityDecl (DTDEntityDecl *const entityDecl) const
Public Member Functions inherited from Grammar
virtual ~Grammar ()
virtual ~Grammar ()
virtual ~Grammar ()
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
DTDGrammar (const DTDGrammar &)
DTDGrammar & operator= (const DTDGrammar &)
DTDGrammar (const DTDGrammar &)
DTDGrammar & operator= (const DTDGrammar &)
DTDGrammar (const DTDGrammar &)
DTDGrammar & operator= (const DTDGrammar &)
Private Attributes
MemoryManager * fMemoryManager
NameIdPool< DTDElementDecl > * fElemDeclPool
NameIdPool< DTDElementDecl > * fElemNonDeclPool
NameIdPool< DTDEntityDecl > * fEntityDeclPool
NameIdPool< XMLNotationDecl > * fNotationDeclPool
XMLDTDDescription * fGramDesc
bool fValidated
Static Private Attributes
static NameIdPool< DTDEntityDecl > * fDefaultEntities
Friends
class XMLInitializer
Additional Inherited Members
Public Types inherited from Grammar
enum GrammarType {
DTDGrammarType , SchemaGrammarType , UnKnown , DTDGrammarType ,
SchemaGrammarType , UnKnown , DTDGrammarType , SchemaGrammarType ,
UnKnown
}
enum { UNKNOWN_SCOPE = UINT_MAX - 0 , TOP_LEVEL_SCOPE = UINT_MAX - 1 }
enum GrammarType {
DTDGrammarType , SchemaGrammarType , UnKnown , DTDGrammarType ,
SchemaGrammarType , UnKnown , DTDGrammarType , SchemaGrammarType ,
UnKnown
}
enum { UNKNOWN_SCOPE = UINT_MAX - 0 , TOP_LEVEL_SCOPE = UINT_MAX - 1 }
enum GrammarType {
DTDGrammarType , SchemaGrammarType , UnKnown , DTDGrammarType ,
SchemaGrammarType , UnKnown , DTDGrammarType , SchemaGrammarType ,
UnKnown
}
enum { UNKNOWN_SCOPE = UINT_MAX - 0 , TOP_LEVEL_SCOPE = UINT_MAX - 1 }
Static Public Member Functions inherited from Grammar
static void storeGrammar (XSerializeEngine &serEng, Grammar *const grammar)
static Grammar * loadGrammar (XSerializeEngine &serEng)
static void storeGrammar (XSerializeEngine &serEng, Grammar *const grammar)
static Grammar * loadGrammar (XSerializeEngine &serEng)
static void storeGrammar (XSerializeEngine &serEng, Grammar *const grammar)
static Grammar * loadGrammar (XSerializeEngine &serEng)
Protected Member Functions inherited from Grammar
Grammar ()
Grammar ()
Grammar ()
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 45 of file DTDGrammar.hpp.
Constructor & Destructor Documentation
DTDGrammar() [1/6]
DTDGrammar::DTDGrammar (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~DTDGrammar() [1/3]
virtual DTDGrammar::~DTDGrammar () virtual
DTDGrammar() [2/6]
DTDGrammar::DTDGrammar (const DTDGrammar &) private
DTDGrammar() [3/6]
DTDGrammar::DTDGrammar (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~DTDGrammar() [2/3]
virtual DTDGrammar::~DTDGrammar () virtual
DTDGrammar() [4/6]
DTDGrammar::DTDGrammar (const DTDGrammar &) private
DTDGrammar() [5/6]
DTDGrammar::DTDGrammar (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~DTDGrammar() [3/3]
virtual DTDGrammar::~DTDGrammar () virtual
DTDGrammar() [6/6]
DTDGrammar::DTDGrammar (const DTDGrammar &) private
Member Function Documentation
findOrAddElemDecl() [1/3]
virtual XMLElementDecl* DTDGrammar::findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool & wasAdded) virtual
Implements Grammar.
findOrAddElemDecl() [2/3]
virtual XMLElementDecl* DTDGrammar::findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool & wasAdded) virtual
Implements Grammar.
findOrAddElemDecl() [3/3]
virtual XMLElementDecl* DTDGrammar::findOrAddElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, bool & wasAdded) virtual
Implements Grammar.
getElemDecl() [1/12]
XMLElementDecl * DTDGrammar::getElemDecl (const unsigned int elemId) inline virtual
Implements Grammar.
Definition at line 343 of file DTDGrammar.hpp.
References fElemDeclPool, and NameIdPool< TElem >::getById().
getElemDecl() [2/12]
virtual XMLElementDecl* DTDGrammar::getElemDecl (const unsigned int elemId) virtual
Implements Grammar.
getElemDecl() [3/12]
virtual XMLElementDecl* DTDGrammar::getElemDecl (const unsigned int elemId) virtual
Implements Grammar.
getElemDecl() [4/12]
const XMLElementDecl * DTDGrammar::getElemDecl (const unsigned int elemId) const inline virtual
Implements Grammar.
Definition at line 337 of file DTDGrammar.hpp.
References fElemDeclPool, and NameIdPool< TElem >::getById().
getElemDecl() [5/12]
virtual const XMLElementDecl* DTDGrammar::getElemDecl (const unsigned int elemId) const virtual
Implements Grammar.
getElemDecl() [6/12]
virtual const XMLElementDecl* DTDGrammar::getElemDecl (const unsigned int elemId) const virtual
Implements Grammar.
getElemDecl() [7/12]
XMLElementDecl * DTDGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) inline virtual
Implements Grammar.
Definition at line 324 of file DTDGrammar.hpp.
References fElemDeclPool, fElemNonDeclPool, and NameIdPool< TElem >::getByKey().
getElemDecl() [8/12]
virtual XMLElementDecl* DTDGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) virtual
Implements Grammar.
getElemDecl() [9/12]
virtual XMLElementDecl* DTDGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) virtual
Implements Grammar.
getElemDecl() [10/12]
const XMLElementDecl * DTDGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const inline virtual
Implements Grammar.
Definition at line 311 of file DTDGrammar.hpp.
References fElemDeclPool, fElemNonDeclPool, and NameIdPool< TElem >::getByKey().
getElemDecl() [11/12]
virtual const XMLElementDecl* DTDGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const virtual
Implements Grammar.
getElemDecl() [12/12]
virtual const XMLElementDecl* DTDGrammar::getElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const virtual
Implements Grammar.
getElemEnumerator() [1/3]
NameIdPoolEnumerator< DTDElementDecl > DTDGrammar::getElemEnumerator () const inline
Definition at line 226 of file DTDGrammar.hpp.
References fElemDeclPool, and fMemoryManager.
getElemEnumerator() [2/3]
NameIdPoolEnumerator<DTDElementDecl> DTDGrammar::getElemEnumerator () const
getElemEnumerator() [3/3]
NameIdPoolEnumerator<DTDElementDecl> DTDGrammar::getElemEnumerator () const
getElemId() [1/3]
XMLSize_t DTDGrammar::getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const inline virtual
Implements Grammar.
Definition at line 296 of file DTDGrammar.hpp.
References fElemDeclPool, XMLElementDecl::fgInvalidElemId, NameIdPool< TElem >::getByKey(), and XMLElementDecl::getId().
getElemId() [2/3]
virtual XMLSize_t DTDGrammar::getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const virtual
Implements Grammar.
getElemId() [3/3]
virtual XMLSize_t DTDGrammar::getElemId (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const qName, unsigned int scope) const virtual
Implements Grammar.
getEntityDecl() [1/6]
DTDEntityDecl * DTDGrammar::getEntityDecl (const XMLCh *const entName) inline
Definition at line 254 of file DTDGrammar.hpp.
References fDefaultEntities, fEntityDeclPool, and NameIdPool< TElem >::getByKey().
getEntityDecl() [2/6]
DTDEntityDecl* DTDGrammar::getEntityDecl (const XMLCh *const entName)
getEntityDecl() [3/6]
DTDEntityDecl* DTDGrammar::getEntityDecl (const XMLCh *const entName)
getEntityDecl() [4/6]
const DTDEntityDecl * DTDGrammar::getEntityDecl (const XMLCh *const entName) const inline
Definition at line 244 of file DTDGrammar.hpp.
References fDefaultEntities, fEntityDeclPool, and NameIdPool< TElem >::getByKey().
getEntityDecl() [5/6]
const DTDEntityDecl* DTDGrammar::getEntityDecl (const XMLCh *const entName) const
getEntityDecl() [6/6]
const DTDEntityDecl* DTDGrammar::getEntityDecl (const XMLCh *const entName) const
getEntityDeclPool() [1/6]
NameIdPool< DTDEntityDecl > * DTDGrammar::getEntityDeclPool () inline
Definition at line 265 of file DTDGrammar.hpp.
References fEntityDeclPool.
getEntityDeclPool() [2/6]
NameIdPool<DTDEntityDecl>* DTDGrammar::getEntityDeclPool ()
getEntityDeclPool() [3/6]
NameIdPool<DTDEntityDecl>* DTDGrammar::getEntityDeclPool ()
getEntityDeclPool() [4/6]
const NameIdPool< DTDEntityDecl > * DTDGrammar::getEntityDeclPool () const inline
Definition at line 270 of file DTDGrammar.hpp.
References fEntityDeclPool.
getEntityDeclPool() [5/6]
const NameIdPool<DTDEntityDecl>* DTDGrammar::getEntityDeclPool () const
getEntityDeclPool() [6/6]
const NameIdPool<DTDEntityDecl>* DTDGrammar::getEntityDeclPool () const
getEntityEnumerator() [1/3]
NameIdPoolEnumerator< DTDEntityDecl > DTDGrammar::getEntityEnumerator () const inline
Definition at line 232 of file DTDGrammar.hpp.
References fEntityDeclPool, and fMemoryManager.
getEntityEnumerator() [2/3]
NameIdPoolEnumerator<DTDEntityDecl> DTDGrammar::getEntityEnumerator () const
getEntityEnumerator() [3/3]
NameIdPoolEnumerator<DTDEntityDecl> DTDGrammar::getEntityEnumerator () const
getGrammarDescription() [1/3]
virtual XMLGrammarDescription* DTDGrammar::getGrammarDescription () const virtual
Implements Grammar.
getGrammarDescription() [2/3]
virtual XMLGrammarDescription* DTDGrammar::getGrammarDescription () const virtual
Implements Grammar.
getGrammarDescription() [3/3]
virtual XMLGrammarDescription* DTDGrammar::getGrammarDescription () const virtual
Implements Grammar.
getGrammarType() [1/3]
Grammar::GrammarType DTDGrammar::getGrammarType () const inline virtual
Implements Grammar.
Definition at line 287 of file DTDGrammar.hpp.
References Grammar::DTDGrammarType.
getGrammarType() [2/3]
virtual Grammar::GrammarType DTDGrammar::getGrammarType () const virtual
Implements Grammar.
getGrammarType() [3/3]
virtual Grammar::GrammarType DTDGrammar::getGrammarType () const virtual
Implements Grammar.
getNotationDecl() [1/6]
XMLNotationDecl * DTDGrammar::getNotationDecl (const XMLCh *const notName) inline virtual
Implements Grammar.
Definition at line 369 of file DTDGrammar.hpp.
References fNotationDeclPool, and NameIdPool< TElem >::getByKey().
getNotationDecl() [2/6]
virtual XMLNotationDecl* DTDGrammar::getNotationDecl (const XMLCh *const notName) virtual
Implements Grammar.
getNotationDecl() [3/6]
virtual XMLNotationDecl* DTDGrammar::getNotationDecl (const XMLCh *const notName) virtual
Implements Grammar.
getNotationDecl() [4/6]
const XMLNotationDecl * DTDGrammar::getNotationDecl (const XMLCh *const notName) const inline virtual
Implements Grammar.
Definition at line 364 of file DTDGrammar.hpp.
References fNotationDeclPool, and NameIdPool< TElem >::getByKey().
getNotationDecl() [5/6]
virtual const XMLNotationDecl* DTDGrammar::getNotationDecl (const XMLCh *const notName) const virtual
Implements Grammar.
getNotationDecl() [6/6]
virtual const XMLNotationDecl* DTDGrammar::getNotationDecl (const XMLCh *const notName) const virtual
Implements Grammar.
getNotationEnumerator() [1/3]
NameIdPoolEnumerator< XMLNotationDecl > DTDGrammar::getNotationEnumerator () const inline
Definition at line 238 of file DTDGrammar.hpp.
References fMemoryManager, and fNotationDeclPool.
getNotationEnumerator() [2/3]
NameIdPoolEnumerator<XMLNotationDecl> DTDGrammar::getNotationEnumerator () const
getNotationEnumerator() [3/3]
NameIdPoolEnumerator<XMLNotationDecl> DTDGrammar::getNotationEnumerator () const
getTargetNamespace() [1/3]
const XMLCh * DTDGrammar::getTargetNamespace () const inline virtual
Implements Grammar.
Definition at line 291 of file DTDGrammar.hpp.
References XMLUni::fgZeroLenString.
getTargetNamespace() [2/3]
virtual const XMLCh* DTDGrammar::getTargetNamespace () const virtual
Implements Grammar.
getTargetNamespace() [3/3]
virtual const XMLCh* DTDGrammar::getTargetNamespace () const virtual
Implements Grammar.
getValidated() [1/3]
bool DTDGrammar::getValidated () const inline virtual
Implements Grammar.
Definition at line 379 of file DTDGrammar.hpp.
References fValidated.
getValidated() [2/3]
virtual bool DTDGrammar::getValidated () const virtual
Implements Grammar.
getValidated() [3/3]
virtual bool DTDGrammar::getValidated () const virtual
Implements Grammar.
operator=() [1/3]
DTDGrammar& DTDGrammar::operator= (const DTDGrammar &) private
operator=() [2/3]
DTDGrammar& DTDGrammar::operator= (const DTDGrammar &) private
operator=() [3/3]
DTDGrammar& DTDGrammar::operator= (const DTDGrammar &) private
putElemDecl() [1/6]
virtual XMLElementDecl* DTDGrammar::putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared = false) virtual
Implements Grammar.
putElemDecl() [2/6]
virtual XMLElementDecl* DTDGrammar::putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared = false) virtual
Implements Grammar.
putElemDecl() [3/6]
virtual XMLElementDecl* DTDGrammar::putElemDecl (const unsigned int uriId, const XMLCh *const baseName, const XMLCh *const prefixName, const XMLCh *const qName, unsigned int scope, const bool notDeclared = false) virtual
Implements Grammar.
putElemDecl() [4/6]
XMLSize_t DTDGrammar::putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared = false) inline virtual
Implements Grammar.
Definition at line 350 of file DTDGrammar.hpp.
References fElemDeclPool, fElemNonDeclPool, fMemoryManager, and NameIdPool< TElem >::put().
putElemDecl() [5/6]
virtual XMLSize_t DTDGrammar::putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared = false) virtual
Implements Grammar.
putElemDecl() [6/6]
virtual XMLSize_t DTDGrammar::putElemDecl (XMLElementDecl *const elemDecl, const bool notDeclared = false) virtual
Implements Grammar.
putEntityDecl() [1/3]
XMLSize_t DTDGrammar::putEntityDecl (DTDEntityDecl *const entityDecl) const inline
Definition at line 278 of file DTDGrammar.hpp.
References fEntityDeclPool, and NameIdPool< TElem >::put().
putEntityDecl() [2/3]
XMLSize_t DTDGrammar::putEntityDecl (DTDEntityDecl *const entityDecl) const
putEntityDecl() [3/3]
XMLSize_t DTDGrammar::putEntityDecl (DTDEntityDecl *const entityDecl) const
putNotationDecl() [1/3]
XMLSize_t DTDGrammar::putNotationDecl (XMLNotationDecl *const notationDecl) const inline virtual
Implements Grammar.
Definition at line 374 of file DTDGrammar.hpp.
References fNotationDeclPool, and NameIdPool< TElem >::put().
putNotationDecl() [2/3]
virtual XMLSize_t DTDGrammar::putNotationDecl (XMLNotationDecl *const notationDecl) const virtual
Implements Grammar.
putNotationDecl() [3/3]
virtual XMLSize_t DTDGrammar::putNotationDecl (XMLNotationDecl *const notationDecl) const virtual
Implements Grammar.
reset() [1/3]
virtual void DTDGrammar::reset () virtual
Implements Grammar.
reset() [2/3]
virtual void DTDGrammar::reset () virtual
Implements Grammar.
reset() [3/3]
virtual void DTDGrammar::reset () virtual
Implements Grammar.
setGrammarDescription() [1/3]
virtual void DTDGrammar::setGrammarDescription (XMLGrammarDescription *) virtual
Implements Grammar.
setGrammarDescription() [2/3]
virtual void DTDGrammar::setGrammarDescription (XMLGrammarDescription *) virtual
Implements Grammar.
setGrammarDescription() [3/3]
virtual void DTDGrammar::setGrammarDescription (XMLGrammarDescription *) virtual
Implements Grammar.
setValidated() [1/3]
void DTDGrammar::setValidated (const bool newState) inline virtual
Implements Grammar.
Definition at line 384 of file DTDGrammar.hpp.
References fValidated.
setValidated() [2/3]
virtual void DTDGrammar::setValidated (const bool newState) virtual
Implements Grammar.
setValidated() [3/3]
virtual void DTDGrammar::setValidated (const bool newState) virtual
Implements Grammar.
Friends And Related Function Documentation
XMLInitializer
XMLInitializer friend
Definition at line 219 of file DTDGrammar.hpp.
Member Data Documentation
fDefaultEntities
static NameIdPool< DTDEntityDecl > * DTDGrammar::fDefaultEntities static private
Definition at line 209 of file DTDGrammar.hpp.
Referenced by getEntityDecl().
fElemDeclPool
NameIdPool< DTDElementDecl > * DTDGrammar::fElemDeclPool private
Definition at line 211 of file DTDGrammar.hpp.
Referenced by getElemDecl(), getElemEnumerator(), getElemId(), and putElemDecl().
fElemNonDeclPool
NameIdPool< DTDElementDecl > * DTDGrammar::fElemNonDeclPool private
Definition at line 212 of file DTDGrammar.hpp.
Referenced by getElemDecl(), and putElemDecl().
fEntityDeclPool
NameIdPool< DTDEntityDecl > * DTDGrammar::fEntityDeclPool private
Definition at line 213 of file DTDGrammar.hpp.
Referenced by getEntityDecl(), getEntityDeclPool(), getEntityEnumerator(), and putEntityDecl().
fGramDesc
XMLDTDDescription * DTDGrammar::fGramDesc private
Definition at line 215 of file DTDGrammar.hpp.
fMemoryManager
MemoryManager * DTDGrammar::fMemoryManager private
Definition at line 210 of file DTDGrammar.hpp.
Referenced by getElemEnumerator(), getEntityEnumerator(), getNotationEnumerator(), and putElemDecl().
fNotationDeclPool
NameIdPool< XMLNotationDecl > * DTDGrammar::fNotationDeclPool private
Definition at line 214 of file DTDGrammar.hpp.
Referenced by getNotationDecl(), getNotationEnumerator(), and putNotationDecl().
fValidated
bool DTDGrammar::fValidated private
Definition at line 217 of file DTDGrammar.hpp.
Referenced by getValidated(), and setValidated().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/DTD/DTDGrammar.hpp