Seamly2D: MoveGroupItem Class Reference
MoveGroupItem Class Reference
#include <move_groupitem.h>
Signals
void updateGroups ()
Signals inherited from VUndoCommand
void ClearScene ()
void NeedFullParsing ()
void NeedLiteParsing (const Document &parse)
Public Member Functions
MoveGroupItem (const QDomElement &source, const QDomElement &dest, VAbstractPattern *doc, quint32 sourceId, quint32 destinationId, QUndoCommand *parent=nullptr)
virtual ~MoveGroupItem ()
virtual void undo () Q_DECL_OVERRIDE
virtual void redo () Q_DECL_OVERRIDE
Public Member Functions inherited from VUndoCommand
VUndoCommand (const QDomElement &xml, VAbstractPattern *doc, QUndoCommand *parent=nullptr)
virtual ~VUndoCommand ()=default
Private Attributes
QDomElement m_source
QDomElement m_dest
const QString m_activeDraftblockName
quint32 m_sourceGroupId
quint32 m_destinationGroupId
Additional Inherited Members
Protected Member Functions inherited from VUndoCommand
virtual void RedoFullParsing ()
void UndoDeleteAfterSibling (QDomNode &parentNode, const quint32 &siblingId) const
void IncrementReferences (const QVector< quint32 > &nodes) const
void DecrementReferences (const QVector< quint32 > &nodes) const
void IncrementReferences (const QVector< CustomSARecord > &nodes) const
void DecrementReferences (const QVector< CustomSARecord > &nodes) const
void IncrementReferences (const QVector< VPieceNode > &nodes) const
void DecrementReferences (const QVector< VPieceNode > &nodes) const
QDomElement getDestinationObject (quint32 idTool, quint32 idPoint) const
Protected Attributes inherited from VUndoCommand
QDomElement xml
VAbstractPattern * doc
quint32 nodeId
bool redoFlag
Detailed Description
Definition at line 37 of file move_groupitem.h.
Constructor & Destructor Documentation
MoveGroupItem()
MoveGroupItem::MoveGroupItem (const QDomElement & source, const QDomElement & dest, VAbstractPattern * doc, quint32 sourceId, quint32 destinationId, QUndoCommand * parent = nullptr)
Definition at line 39 of file move_groupitem.cpp.
~MoveGroupItem()
MoveGroupItem::~MoveGroupItem () virtual
Definition at line 52 of file move_groupitem.cpp.
Member Function Documentation
redo()
void MoveGroupItem::redo () virtual
Definition at line 106 of file move_groupitem.cpp.
References VAbstractPattern::changeActiveDraftBlock(), VAbstractPattern::createGroups(), VUndoCommand::doc, VDomDocument::elementById(), m_activeDraftblockName, m_dest, m_destinationGroupId, m_source, m_sourceGroupId, VMainGraphicsView::NewSceneRect(), VAbstractPattern::parseGroups(), qApp, VAbstractPattern::setCurrentDraftBlock(), VAbstractPattern::SetModified(), VAbstractPattern::TagGroup, and updateGroups().
undo()
void MoveGroupItem::undo () virtual
Definition at line 57 of file move_groupitem.cpp.
References VAbstractPattern::changeActiveDraftBlock(), VAbstractPattern::createGroups(), VUndoCommand::doc, VDomDocument::elementById(), m_activeDraftblockName, m_dest, m_destinationGroupId, m_source, m_sourceGroupId, VMainGraphicsView::NewSceneRect(), VAbstractPattern::parseGroups(), qApp, VAbstractPattern::setCurrentDraftBlock(), VAbstractPattern::SetModified(), VAbstractPattern::TagGroup, and updateGroups().
updateGroups
void MoveGroupItem::updateGroups () signal
Referenced by GroupsWidget::groupItemContextMenu(), redo(), and undo().
Member Data Documentation
m_activeDraftblockName
const QString MoveGroupItem::m_activeDraftblockName private
Definition at line 54 of file move_groupitem.h.
Referenced by redo(), and undo().
m_dest
QDomElement MoveGroupItem::m_dest private
Definition at line 53 of file move_groupitem.h.
Referenced by redo(), and undo().
m_destinationGroupId
quint32 MoveGroupItem::m_destinationGroupId private
Definition at line 56 of file move_groupitem.h.
Referenced by redo(), and undo().
m_source
QDomElement MoveGroupItem::m_source private
Definition at line 52 of file move_groupitem.h.
Referenced by redo(), and undo().
m_sourceGroupId
quint32 MoveGroupItem::m_sourceGroupId private
Definition at line 55 of file move_groupitem.h.
Referenced by redo(), and undo().
The documentation for this class was generated from the following files:
src/libs/vtools/undocommands/move_groupitem.h
src/libs/vtools/undocommands/move_groupitem.cpp