Seamly2D: anonymous_namespace{pattern_piece_dialog.cpp} Namespace Reference
anonymous_namespace{pattern_piece_dialog.cpp} Namespace Reference
Functions
void enableDefaultButton (QPushButton *defButton, const QString &formula)
QString getFormulaFromUser (QPlainTextEdit *textEdit)
Function Documentation
enableDefaultButton()
void anonymous_namespace{pattern_piece_dialog.cpp}::enableDefaultButton (QPushButton * defButton, const QString & formula)
Definition at line 88 of file pattern_piece_dialog.cpp.
References currentSeamAllowance, and SCASSERT.
Referenced by PatternPieceDialog::evaluateAfterWidth(), PatternPieceDialog::evaluateBeforeWidth(), and PatternPieceDialog::nodeChanged().
getFormulaFromUser()
QString anonymous_namespace{pattern_piece_dialog.cpp}::getFormulaFromUser (QPlainTextEdit * textEdit)
Definition at line 99 of file pattern_piece_dialog.cpp.
References qApp, and SCASSERT.
Referenced by PatternPieceDialog::CreatePiece(), PatternPieceDialog::editAfterSeamAllowanceWidth(), PatternPieceDialog::editBeforeSeamAllowanceWidth(), PatternPieceDialog::evaluateAfterWidth(), and PatternPieceDialog::evaluateBeforeWidth().