Seamly2D: anonymous_namespace{vnodedetail.cpp} Namespace Reference
anonymous_namespace{vnodedetail.cpp} Namespace Reference
Functions
bool IsOX (const QLineF &line)
bool IsOY (const QLineF &line)
QString LocalWidth (const QLineF &line, const QLineF &movedLine)
void ConvertBefore (VPieceNode &node, const QLineF &line, qreal mX, qreal mY)
void ConvertAfter (VPieceNode &node, const QLineF &line, qreal mX, qreal mY)
Function Documentation
ConvertAfter()
void anonymous_namespace{vnodedetail.cpp}::ConvertAfter (VPieceNode & node, const QLineF & line, qreal mX, qreal mY)
Definition at line 107 of file vnodedetail.cpp.
References IsOX(), IsOY(), LocalWidth(), and VPieceNode::setAfterSAFormula().
Referenced by VNodeDetail::Convert().
ConvertBefore()
void anonymous_namespace{vnodedetail.cpp}::ConvertBefore (VPieceNode & node, const QLineF & line, qreal mX, qreal mY)
Definition at line 92 of file vnodedetail.cpp.
References IsOX(), IsOY(), LocalWidth(), and VPieceNode::setBeforeSAFormula().
Referenced by VNodeDetail::Convert().
IsOX()
bool anonymous_namespace{vnodedetail.cpp}::IsOX (const QLineF & line)
Definition at line 65 of file vnodedetail.cpp.
References VFuzzyComparePossibleNulls().
Referenced by ConvertAfter(), and ConvertBefore().
IsOY()
bool anonymous_namespace{vnodedetail.cpp}::IsOY (const QLineF & line)
Definition at line 73 of file vnodedetail.cpp.
References VFuzzyComparePossibleNulls().
Referenced by ConvertAfter(), and ConvertBefore().
LocalWidth()
QString anonymous_namespace{vnodedetail.cpp}::LocalWidth (const QLineF & line, const QLineF & movedLine)
Definition at line 79 of file vnodedetail.cpp.
References VFuzzyComparePossibleNulls().
Referenced by ConvertAfter(), and ConvertBefore().