Seamly2D: DialogLineIntersect Class Reference
DialogLineIntersect Class Reference
The DialogLineIntersect class dialog for ToolLineIntersect. Help create point and edit option.
#include <dialoglineintersect.h>
Public Slots
virtual void ChosenObject (quint32 id, const SceneObject &type) Q_DECL_OVERRIDE
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
void PointChanged ()
P1Line1Changed changed first point of first line.
virtual void PointNameChanged () Q_DECL_OVERRIDE
Public Slots inherited from DialogTool
virtual void ChosenObject (quint32 id, const SceneObject &type)
ChosenObject gets id and type of selected object. Save right data and ignore wrong.
virtual void SelectedObject (bool selected, quint32 object, quint32 tool)
void NamePointChanged ()
NamePointChanged check name of point.
virtual void DialogAccepted ()
DialogAccepted save data and emit signal about closed dialog.
virtual void DialogApply ()
DialogApply save data and emit signal DialogApplied.
virtual void DialogRejected ()
DialogRejected emit signal dialog rejected.
void FormulaChanged ()
formula check formula
void FormulaChangedPlainText ()
FormulaChangedPlainText check formula (plain text editor editor)
void ArrowUp ()
ArrowUp set angle value 90 degree.
void ArrowDown ()
ArrowDown set angle value 270 degree.
void ArrowLeft ()
ArrowLeft set angle value 180 degree.
void ArrowRight ()
ArrowRight set angle value 0 degree.
void ArrowLeftUp ()
ArrowLeftUp set angle value 135 degree.
void ArrowLeftDown ()
ArrowLeftDown set angle value 225 degree.
void ArrowRightUp ()
ArrowRightUp set angle value 45 degree.
void ArrowRightDown ()
ArrowRightDown set angle value 315 degree.
virtual void EvalFormula ()
EvalFormula evaluate formula.
virtual void PointNameChanged ()
Public Member Functions
DialogLineIntersect (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogLineIntersect create dialog.
virtual ~DialogLineIntersect () Q_DECL_OVERRIDE
quint32 GetP1Line1 () const
GetP1Line1 return id first point of first line.
void SetP1Line1 (const quint32 &value)
SetP1Line1 set id first point of first line.
quint32 GetP2Line1 () const
GetP2Line1 return id second point of first line.
void SetP2Line1 (const quint32 &value)
SetP2Line1 set id second point of first line.
quint32 GetP1Line2 () const
GetP1Line2 return id first point of second line.
void SetP1Line2 (const quint32 &value)
SetP1Line2 set id first point of second line.
quint32 GetP2Line2 () const
GetP2Line2 return id second point of second line.
void SetP2Line2 (const quint32 &value)
SetP2Line2 set id second point of second line.
void SetPointName (const QString &value)
SetPointName set name of point.
Public Member Functions inherited from DialogTool
DialogTool (const VContainer *data, const quint32 &toolId, QWidget *parent=nullptr)
DialogTool create dialog.
virtual ~DialogTool () Q_DECL_OVERRIDE
VAbstractTool * GetAssociatedTool ()
void SetAssociatedTool (VAbstractTool *tool)
virtual void ShowDialog (bool click)
virtual void Build (const Tool &type)
virtual void SetPiecesList (const QVector< quint32 > &list)
quint32 GetToolId () const
void SetToolId (const quint32 &value)
QString getPointName () const
Protected Member Functions
virtual void ShowVisualization () Q_DECL_OVERRIDE
virtual void SaveData () Q_DECL_OVERRIDE
SaveData Put dialog data in local variables.
Protected Member Functions inherited from DialogTool
virtual void keyPressEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
closeEvent handle when dialog cloded
virtual void showEvent (QShowEvent *event) Q_DECL_OVERRIDE
showEvent handle when window show
void FillComboBoxPiecesList (QComboBox *box, const QVector< quint32 > &list)
void FillComboBoxPoints (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
FillComboBoxPoints fill comboBox list of points.
void FillComboBoxArcs (QComboBox *box, FillComboBox rule=FillComboBox::Whole, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void FillComboBoxSplines (QComboBox *box) const
void FillComboBoxSplinesPath (QComboBox *box) const
void FillComboBoxCurves (QComboBox *box) const
void FillComboBoxTypeLine (QComboBox *box, const QMap< QString, QIcon > &stylesPics) const
FillComboBoxTypeLine fill comboBox list of type lines.
void FillComboBoxLineColors (QComboBox *box) const
void FillComboBoxCrossCirclesPoints (QComboBox *box) const
void FillComboBoxVCrossCurvesPoint (QComboBox *box) const
void FillComboBoxHCrossCurvesPoint (QComboBox *box) const
QString GetComboBoxCurrentData (const QComboBox *box, const QString &def) const
void ChangeCurrentData (QComboBox *box, const QVariant &value) const
ChangeCurrentData select item in combobox by id.
void ValFormulaChanged (bool &flag, QLineEdit *edit, QTimer *timer, const QString &postfix=QString())
ValFormulaChanged handle change formula.
void ValFormulaChanged (bool &flag, QPlainTextEdit *edit, QTimer *timer, const QString &postfix=QString())
qreal Eval (const QString &text, bool &flag, QLabel *label, const QString &postfix, bool checkZero=true, bool checkLessThanZero=false)
Eval evaluate formula and show result.
qreal normalize (const qreal value, const qreal start, const qreal end)
void setCurrentPointId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
void setCurrentSplineId (QComboBox *box, const quint32 &value) const
setCurrentSplineId set current spline id in combobox
void setCurrentArcId (QComboBox *box, const quint32 &value, FillComboBox rule=FillComboBox::NoChildren, const quint32 &ch1=NULL_ID, const quint32 &ch2=NULL_ID) const
setCurrentArcId
void setCurrentSplinePathId (QComboBox *box, const quint32 &value) const
setCurrentSplinePathId set current splinePath id in combobox
void setCurrentCurveId (QComboBox *box, const quint32 &value) const
quint32 getCurrentObjectId (QComboBox *box) const
getCurrentPointId return current point id stored in combobox
template<typename T >
T getCurrentCrossPoint (QComboBox *box) const
bool SetObject (const quint32 &id, QComboBox *box, const QString &toolTip)
void DeployFormula (QPlainTextEdit *formula, QPushButton *buttonGrowLength, int formulaBaseHeight)
template<typename T >
void initializeOkCancelApply (T *ui)
initializeOkCancelApply initialize OK / Cancel and Apply buttons
template<typename T >
void initializeOkCancel (T *ui)
initializeOkCancel initialize OK and Cancel buttons
template<typename T >
void initializeFormulaUi (T *ui)
initializeFormulaUi initialize ui object for the formula field
template<typename T >
void AddVisualization ()
template<typename T >
QVector< T > GetListInternals (const QListWidget *list) const
void ChangeColor (QWidget *widget, const QColor &color)
void MoveCursorToEnd (QPlainTextEdit *plainTextEdit) const
virtual bool eventFilter (QObject *object, QEvent *event) Q_DECL_OVERRIDE
quint32 DNumber (const QString &baseName) const
NodeInfo getNodeInfo (const VPieceNode &node, bool showNotch=false) const
void newNodeItem (QListWidget *listWidget, const VPieceNode &node, bool nodeExcluded=true, bool isDuplicate=false)
void initializeNodeAngles (QComboBox *box)
Private Member Functions
virtual void CheckState () Q_DECL_FINAL
CheckState check state of dialog. Enable or disable button ok.
bool CheckIntersecion ()
CheckIntersecion check intersection of points.
Private Attributes
Ui::DialogLineIntersect * ui
ui keeps information about user interface
bool flagPoint
flagPoint keep state of point
Additional Inherited Members
Signals inherited from DialogTool
void DialogClosed (int result)
DialogClosed signal dialog closed.
void DialogApplied ()
DialogApplied emit signal dialog apply changes.
void ToolTip (const QString &toolTip)
ToolTip emit tooltipe for tool.
Static Public Member Functions inherited from DialogTool
static void moveListRowTop (QListWidget *list)
static void moveListRowUp (QListWidget *list)
static void moveListRowDown (QListWidget *list)
static void moveListRowBottom (QListWidget *list)
Static Protected Member Functions inherited from DialogTool
static int FindNotExcludedNodeDown (QListWidget *listWidget, int candidate)
static int FindNotExcludedNodeUp (QListWidget *listWidget, int candidate)
static bool isFirstPointSameAsLast (QListWidget *listWidget)
static bool doublePointsExist (QListWidget *listWidget)
static bool isEachPointNameUnique (QListWidget *listWidget)
static QString DialogWarningIcon ()
static QFont NodeFont (bool nodeExcluded)
Protected Attributes inherited from DialogTool
const VContainer * data
data container with data
bool isInitialized
isInitialized true if window is initialized
bool flagName
flagName true if name is correct
bool flagFormula
flagFormula true if formula correct
bool flagError
flagError use this flag if for you do not enought
QTimer * timerFormula
timerFormula timer for check formula
QPushButton * ok_Button
ok_Button button ok
QPushButton * apply_Button
apply_Button button apply
QDoubleSpinBox * spinBoxAngle
spinBoxAngle spinbox for angle
QPlainTextEdit * plainTextEditFormula
plainTextEditFormula formula
QLabel * labelResultCalculation
labelResultCalculation label with result of calculation
QLabel * labelEditNamePoint
labelEditNamePoint label used when need show wrong name of point
QLabel * labelEditFormula
labelEditFormula label used when need show wrong formula
const QColor okColor
const QColor errorColor
VAbstractTool * associatedTool
associatedTool vdrawtool associated with opened dialog.
quint32 toolId
bool prepare
prepare show if we prepare. Show dialog after finish working with visual part of tool
QString pointName
pointName name of point
qint32 number
number number of handled objects
QPointer< Visualization > vis
Detailed Description
The DialogLineIntersect class dialog for ToolLineIntersect. Help create point and edit option.
Definition at line 72 of file dialoglineintersect.h.
Constructor & Destructor Documentation
DialogLineIntersect()
DialogLineIntersect::DialogLineIntersect (const VContainer * data, const quint32 & toolId, QWidget * parent = nullptr)
DialogLineIntersect create dialog.
Parameters
data container with data
parent parent widget
Definition at line 82 of file dialoglineintersect.cpp.
References DialogTool::data, DialogTool::FillComboBoxPoints(), DialogTool::initializeOkCancelApply(), DialogTool::labelEditNamePoint, DialogTool::NamePointChanged(), NewLabel, DialogTool::number, PointNameChanged(), qApp, ui, and DialogTool::vis.
~DialogLineIntersect()
DialogLineIntersect::~DialogLineIntersect () virtual
Definition at line 113 of file dialoglineintersect.cpp.
References ui.
Member Function Documentation
CheckIntersecion()
bool DialogLineIntersect::CheckIntersecion () private
CheckIntersecion check intersection of points.
Returns
true - line have intersection, false = don't have
Definition at line 295 of file dialoglineintersect.cpp.
References DialogTool::data, VContainer::GeometricObject(), GetP1Line1(), GetP1Line2(), GetP2Line1(), and GetP2Line2().
Referenced by ChosenObject(), and PointChanged().
CheckState()
void DialogLineIntersect::CheckState () private virtual
CheckState check state of dialog. Enable or disable button ok.
Reimplemented from DialogTool.
Definition at line 284 of file dialoglineintersect.cpp.
References DialogTool::flagName, flagPoint, DialogTool::ok_Button, and SCASSERT.
Referenced by ChosenObject(), PointChanged(), and PointNameChanged().
ChosenObject
void DialogLineIntersect::ChosenObject (quint32 id, const SceneObject & type) virtual slot
ChoosedObject gets id and type of selected object. Save right data and ignore wrong.
Parameters
id id of point or detail
type type of object
Definition at line 124 of file dialoglineintersect.cpp.
References CheckIntersecion(), CheckState(), DialogTool::DialogAccepted(), flagPoint, DialogTool::getCurrentObjectId(), DialogTool::number, Point, PointChanged(), DialogTool::prepare, VisToolLineIntersect::RefreshGeometry(), SCASSERT, VisToolLineIntersect::setLine1P2Id(), VisToolLineIntersect::setLine2P1Id(), VisToolLineIntersect::setLine2P2Id(), DialogTool::SetObject(), ui, DialogTool::vis, and Visualization::VisualMode().
GetP1Line1()
quint32 DialogLineIntersect::GetP1Line1 () const
GetP1Line1 return id first point of first line.
Returns
id
Definition at line 388 of file dialoglineintersect.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by CheckIntersecion(), and SaveData().
GetP1Line2()
quint32 DialogLineIntersect::GetP1Line2 () const
GetP1Line2 return id first point of second line.
Returns
id
Definition at line 408 of file dialoglineintersect.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by CheckIntersecion(), and SaveData().
GetP2Line1()
quint32 DialogLineIntersect::GetP2Line1 () const
GetP2Line1 return id second point of first line.
Returns
id
Definition at line 398 of file dialoglineintersect.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by CheckIntersecion(), and SaveData().
GetP2Line2()
quint32 DialogLineIntersect::GetP2Line2 () const
GetP2Line2 return id second point of second line.
Returns
id
Definition at line 418 of file dialoglineintersect.cpp.
References DialogTool::getCurrentObjectId(), and ui.
Referenced by CheckIntersecion(), and SaveData().
PointChanged
void DialogLineIntersect::PointChanged () slot
P1Line1Changed changed first point of first line.
Definition at line 226 of file dialoglineintersect.cpp.
References CheckIntersecion(), CheckState(), and flagPoint.
Referenced by ChosenObject().
PointNameChanged
void DialogLineIntersect::PointNameChanged () virtual slot
Definition at line 233 of file dialoglineintersect.cpp.
References DialogTool::ChangeColor(), CheckState(), DialogTool::data, DialogTool::errorColor, DialogTool::flagError, VContainer::GeometricObject(), DialogTool::getCurrentObjectId(), DialogTool::okColor, and ui.
Referenced by DialogLineIntersect().
SaveData()
void DialogLineIntersect::SaveData () protected virtual
SaveData Put dialog data in local variables.
Reimplemented from DialogTool.
Definition at line 208 of file dialoglineintersect.cpp.
References GetP1Line1(), GetP1Line2(), GetP2Line1(), GetP2Line2(), DialogTool::pointName, VisToolLineIntersect::RefreshGeometry(), SCASSERT, VisToolLineIntersect::setLine1P2Id(), VisToolLineIntersect::setLine2P1Id(), VisToolLineIntersect::setLine2P2Id(), Visualization::setObject1Id(), ui, and DialogTool::vis.
SetP1Line1()
void DialogLineIntersect::SetP1Line1 (const quint32 & value)
SetP1Line1 set id first point of first line.
Parameters
value id
Definition at line 363 of file dialoglineintersect.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), Visualization::setObject1Id(), ui, and DialogTool::vis.
SetP1Line2()
void DialogLineIntersect::SetP1Line2 (const quint32 & value)
SetP1Line2 set id first point of second line.
Parameters
value id
Definition at line 335 of file dialoglineintersect.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), VisToolLineIntersect::setLine2P1Id(), ui, and DialogTool::vis.
SetP2Line1()
void DialogLineIntersect::SetP2Line1 (const quint32 & value)
SetP2Line1 set id second point of first line.
Parameters
value id
Definition at line 349 of file dialoglineintersect.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), VisToolLineIntersect::setLine1P2Id(), ui, and DialogTool::vis.
SetP2Line2()
void DialogLineIntersect::SetP2Line2 (const quint32 & value)
SetP2Line2 set id second point of second line.
Parameters
value id
Definition at line 321 of file dialoglineintersect.cpp.
References SCASSERT, DialogTool::setCurrentPointId(), VisToolLineIntersect::setLine2P2Id(), ui, and DialogTool::vis.
SetPointName()
void DialogLineIntersect::SetPointName (const QString & value)
SetPointName set name of point.
Parameters
value name of point
Definition at line 377 of file dialoglineintersect.cpp.
References DialogTool::pointName, and ui.
ShowVisualization()
void DialogLineIntersect::ShowVisualization () protected virtual
Reimplemented from DialogTool.
Definition at line 275 of file dialoglineintersect.cpp.
Member Data Documentation
flagPoint
bool DialogLineIntersect::flagPoint private
flagPoint keep state of point
Definition at line 109 of file dialoglineintersect.h.
Referenced by CheckState(), ChosenObject(), and PointChanged().
ui
Ui::DialogLineIntersect* DialogLineIntersect::ui private
ui keeps information about user interface
Definition at line 106 of file dialoglineintersect.h.
Referenced by ChosenObject(), DialogLineIntersect(), GetP1Line1(), GetP1Line2(), GetP2Line1(), GetP2Line2(), PointNameChanged(), SaveData(), SetP1Line1(), SetP1Line2(), SetP2Line1(), SetP2Line2(), SetPointName(), and ~DialogLineIntersect().
The documentation for this class was generated from the following files:
src/libs/vtools/dialogs/tools/dialoglineintersect.h
src/libs/vtools/dialogs/tools/dialoglineintersect.cpp