Seamly2D: AbstractLayoutDialog Class Reference
AbstractLayoutDialog Class Reference
#include <abstractlayout_dialog.h>
Public Member Functions
AbstractLayoutDialog (QWidget *parent=nullptr)
Protected Member Functions
QSizeF getTemplateSize (const PaperSizeFormat &tmpl, const Unit &unit) const
LayoutSettingsDialog::TemplateSize.
QSizeF RoundTemplateSize (qreal width, qreal height, Unit unit) const
Detailed Description
Definition at line 27 of file abstractlayout_dialog.h.
Constructor & Destructor Documentation
AbstractLayoutDialog()
AbstractLayoutDialog::AbstractLayoutDialog (QWidget * parent = nullptr) explicit
Definition at line 23 of file abstractlayout_dialog.cpp.
Member Function Documentation
getTemplateSize()
QSizeF AbstractLayoutDialog::getTemplateSize (const PaperSizeFormat & tmpl, const Unit & unit) const protected
LayoutSettingsDialog::TemplateSize.
Parameters
tmpl
unit
Returns
Definition at line 34 of file abstractlayout_dialog.cpp.
References A0, A1, A2, A3, A4, AnsiC, AnsiD, AnsiE, Inch, Legal, Letter, Mm, Px, QIMAGE_MAX, Roll24in, Roll30in, Roll36in, Roll42in, Roll44in, RoundTemplateSize(), Tabloid, and UnitConvertor().
Referenced by LayoutSettingsDialog::getTemplateSize(), ExportLayoutDialog::readSettings(), and ExportLayoutDialog::writeSettings().
RoundTemplateSize()
QSizeF AbstractLayoutDialog::RoundTemplateSize (qreal width, qreal height, Unit unit) const protected
Definition at line 112 of file abstractlayout_dialog.cpp.
References Cm, Inch, Mm, and Px.
Referenced by getTemplateSize(), and LayoutSettingsDialog::getTemplateSize().
The documentation for this class was generated from the following files:
src/app/seamly2d/dialogs/abstractlayout_dialog.h
src/app/seamly2d/dialogs/abstractlayout_dialog.cpp