Seamly2D: VAbstractSimple Class Reference
VAbstractSimple Class Reference
#include <vabstractsimple.h>
Signals
void showContextMenu (QGraphicsSceneContextMenuEvent *event, quint32 id=null_id)
void Delete ()
Public Member Functions
VAbstractSimple (quint32 id, QObject *parent=nullptr)
virtual ~VAbstractSimple ()=default
virtual void ToolSelectionType (const SelectionType &type)
GOType GetType () const
void SetType (const GOType &value)
Protected Attributes
quint32 id
id spline id.
SelectionType selectionType
GOType type
Detailed Description
Definition at line 69 of file vabstractsimple.h.
Constructor & Destructor Documentation
VAbstractSimple()
VAbstractSimple::VAbstractSimple (quint32 id, QObject * parent = nullptr)
Definition at line 55 of file vabstractsimple.cpp.
References ByMouseRelease, and Unknown.
~VAbstractSimple()
virtual VAbstractSimple::~VAbstractSimple () virtual default
Member Function Documentation
Delete
void VAbstractSimple::Delete () signal
Referenced by VSimplePoint::deletePoint(), VAbstractOperation::InitCurve(), VAbstractOperation::InitOperatedObjects(), VSimpleCurve::keyReleaseEvent(), VSimplePoint::keyReleaseEvent(), and VToolDoublePoint::VToolDoublePoint().
GetType()
GOType VAbstractSimple::GetType () const
Definition at line 70 of file vabstractsimple.cpp.
References type.
Referenced by VAbstractOperation::AllowCurveHover(), VAbstractOperation::AllowCurveSelecting(), VAbstractOperation::GroupVisibility(), VAbstractOperation::isPointNameVisible(), VAbstractOperation::pointNamePositionChanged(), VAbstractOperation::setPointNamePosition(), VAbstractOperation::setPointNameVisiblity(), VAbstractOperation::updatePointNamePosition(), and VAbstractOperation::updatePointNameVisibility().
SetType()
void VAbstractSimple::SetType (const GOType & value)
Definition at line 76 of file vabstractsimple.cpp.
References type.
Referenced by VAbstractOperation::InitOperatedObjects().
showContextMenu
void VAbstractSimple::showContextMenu (QGraphicsSceneContextMenuEvent * event, quint32 id = null_id) signal
Referenced by VSimpleCurve::contextMenuEvent(), VSimplePoint::contextMenuEvent(), VAbstractOperation::InitCurve(), VAbstractOperation::InitOperatedObjects(), and VToolDoublePoint::VToolDoublePoint().
ToolSelectionType()
void VAbstractSimple::ToolSelectionType (const SelectionType & type) virtual
Reimplemented in VSimplePoint.
Definition at line 64 of file vabstractsimple.cpp.
References selectionType, and type.
Referenced by VSimplePoint::ToolSelectionType().
Member Data Documentation
id
quint32 VAbstractSimple::id protected
id spline id.
Definition at line 87 of file vabstractsimple.h.
selectionType
SelectionType VAbstractSimple::selectionType protected
Definition at line 89 of file vabstractsimple.h.
Referenced by VSimpleCurve::mousePressEvent(), VSimplePoint::mousePressEvent(), VSimpleCurve::mouseReleaseEvent(), VSimplePoint::mouseReleaseEvent(), and ToolSelectionType().
type
GOType VAbstractSimple::type protected
Definition at line 91 of file vabstractsimple.h.
Referenced by GetType(), SetType(), and ToolSelectionType().
The documentation for this class was generated from the following files:
src/libs/vwidgets/vabstractsimple.h
src/libs/vwidgets/vabstractsimple.cpp