Seamly2D: ReaderMgr Class Reference
ReaderMgr Class Reference
#include <ReaderMgr.hpp>
Classes
struct LastExtEntityInfo
Public Member Functions
ReaderMgr (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ReaderMgr ()
bool atEOF () const
bool getName (XMLBuffer &toFill)
bool getQName (XMLBuffer &toFill, int *colonPosition)
bool getNameToken (XMLBuffer &toFill)
XMLCh getNextChar ()
bool getNextCharIfNot (const XMLCh chNotToGet, XMLCh &chGotten)
void movePlainContentChars (XMLBuffer &dest)
void getSpaces (XMLBuffer &toFill)
void getUpToCharOrWS (XMLBuffer &toFill, const XMLCh toCheck)
bool isEmpty () const
bool lookingAtChar (const XMLCh toCheck)
bool lookingAtSpace ()
XMLCh peekNextChar ()
bool skipIfQuote (XMLCh &chGotten)
void skipPastChar (const XMLCh toSkip)
void skipPastSpaces (bool &skippedSomething, bool inDecl=false)
void skipPastSpaces ()
void skipToChar (const XMLCh toSkipTo)
bool skippedChar (const XMLCh toSkip)
bool skippedSpace ()
bool skippedString (const XMLCh *const toSkip)
bool skippedStringLong (const XMLCh *const toSkip)
void skipQuotedString (const XMLCh quoteCh)
XMLCh skipUntilIn (const XMLCh *const listToSkip)
XMLCh skipUntilInOrWS (const XMLCh *const listToSkip)
bool peekString (const XMLCh *const toPeek)
void cleanStackBackTo (const XMLSize_t readerNum)
XMLReader * createReader (const InputSource &src, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, const bool calcSrsOfs=true, XMLSize_t lowWaterMark=100)
XMLReader * createReader (const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *&srcToFill, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100, const bool disableDefaultEntityResolution=false)
XMLReader * createReader (const XMLCh *const baseURI, const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *&srcToFill, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100, const bool disableDefaultEntityResolution=false)
XMLReader * createIntEntReader (const XMLCh *const sysId, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLCh *const dataBuf, const XMLSize_t dataLen, const bool copyBuf, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100)
bool isScanningPERefOutOfLiteral () const
bool pushReader (XMLReader *const reader, XMLEntityDecl *const entity)
void reset ()
const XMLCh * getCurrentEncodingStr () const
const XMLEntityDecl * getCurrentEntity () const
XMLEntityDecl * getCurrentEntity ()
const XMLReader * getCurrentReader () const
XMLReader * getCurrentReader ()
XMLSize_t getCurrentReaderNum () const
XMLSize_t getReaderDepth () const
void getLastExtEntityInfo (LastExtEntityInfo &lastInfo) const
XMLFilePos getSrcOffset () const
bool getThrowEOE () const
void setEntityHandler (XMLEntityHandler *const newHandler)
void setThrowEOE (const bool newValue)
void setXMLVersion (const XMLReader::XMLVersion version)
void setStandardUriConformant (const bool newValue)
virtual const XMLCh * getPublicId () const
virtual const XMLCh * getSystemId () const
virtual XMLFileLoc getLineNumber () const
virtual XMLFileLoc getColumnNumber () const
ReaderMgr (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ReaderMgr ()
bool atEOF () const
bool getName (XMLBuffer &toFill)
bool getQName (XMLBuffer &toFill, int *colonPosition)
bool getNameToken (XMLBuffer &toFill)
XMLCh getNextChar ()
bool getNextCharIfNot (const XMLCh chNotToGet, XMLCh &chGotten)
void movePlainContentChars (XMLBuffer &dest)
void getSpaces (XMLBuffer &toFill)
void getUpToCharOrWS (XMLBuffer &toFill, const XMLCh toCheck)
bool isEmpty () const
bool lookingAtChar (const XMLCh toCheck)
bool lookingAtSpace ()
XMLCh peekNextChar ()
bool skipIfQuote (XMLCh &chGotten)
void skipPastChar (const XMLCh toSkip)
void skipPastSpaces (bool &skippedSomething, bool inDecl=false)
void skipPastSpaces ()
void skipToChar (const XMLCh toSkipTo)
bool skippedChar (const XMLCh toSkip)
bool skippedSpace ()
bool skippedString (const XMLCh *const toSkip)
bool skippedStringLong (const XMLCh *const toSkip)
void skipQuotedString (const XMLCh quoteCh)
XMLCh skipUntilIn (const XMLCh *const listToSkip)
XMLCh skipUntilInOrWS (const XMLCh *const listToSkip)
bool peekString (const XMLCh *const toPeek)
void cleanStackBackTo (const XMLSize_t readerNum)
XMLReader * createReader (const InputSource &src, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, const bool calcSrsOfs=true, XMLSize_t lowWaterMark=100)
XMLReader * createReader (const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *&srcToFill, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100, const bool disableDefaultEntityResolution=false)
XMLReader * createReader (const XMLCh *const baseURI, const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *&srcToFill, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100, const bool disableDefaultEntityResolution=false)
XMLReader * createIntEntReader (const XMLCh *const sysId, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLCh *const dataBuf, const XMLSize_t dataLen, const bool copyBuf, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100)
bool isScanningPERefOutOfLiteral () const
bool pushReader (XMLReader *const reader, XMLEntityDecl *const entity)
void reset ()
const XMLCh * getCurrentEncodingStr () const
const XMLEntityDecl * getCurrentEntity () const
XMLEntityDecl * getCurrentEntity ()
const XMLReader * getCurrentReader () const
XMLReader * getCurrentReader ()
XMLSize_t getCurrentReaderNum () const
XMLSize_t getReaderDepth () const
void getLastExtEntityInfo (LastExtEntityInfo &lastInfo) const
XMLFilePos getSrcOffset () const
bool getThrowEOE () const
void setEntityHandler (XMLEntityHandler *const newHandler)
void setThrowEOE (const bool newValue)
void setXMLVersion (const XMLReader::XMLVersion version)
void setStandardUriConformant (const bool newValue)
virtual const XMLCh * getPublicId () const
virtual const XMLCh * getSystemId () const
virtual XMLFileLoc getLineNumber () const
virtual XMLFileLoc getColumnNumber () const
ReaderMgr (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~ReaderMgr ()
bool atEOF () const
bool getName (XMLBuffer &toFill)
bool getQName (XMLBuffer &toFill, int *colonPosition)
bool getNameToken (XMLBuffer &toFill)
XMLCh getNextChar ()
bool getNextCharIfNot (const XMLCh chNotToGet, XMLCh &chGotten)
void movePlainContentChars (XMLBuffer &dest)
void getSpaces (XMLBuffer &toFill)
void getUpToCharOrWS (XMLBuffer &toFill, const XMLCh toCheck)
bool isEmpty () const
bool lookingAtChar (const XMLCh toCheck)
bool lookingAtSpace ()
XMLCh peekNextChar ()
bool skipIfQuote (XMLCh &chGotten)
void skipPastChar (const XMLCh toSkip)
void skipPastSpaces (bool &skippedSomething, bool inDecl=false)
void skipPastSpaces ()
void skipToChar (const XMLCh toSkipTo)
bool skippedChar (const XMLCh toSkip)
bool skippedSpace ()
bool skippedString (const XMLCh *const toSkip)
bool skippedStringLong (const XMLCh *const toSkip)
void skipQuotedString (const XMLCh quoteCh)
XMLCh skipUntilIn (const XMLCh *const listToSkip)
XMLCh skipUntilInOrWS (const XMLCh *const listToSkip)
bool peekString (const XMLCh *const toPeek)
void cleanStackBackTo (const XMLSize_t readerNum)
XMLReader * createReader (const InputSource &src, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, const bool calcSrsOfs=true, XMLSize_t lowWaterMark=100)
XMLReader * createReader (const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *&srcToFill, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100, const bool disableDefaultEntityResolution=false)
XMLReader * createReader (const XMLCh *const baseURI, const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *&srcToFill, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100, const bool disableDefaultEntityResolution=false)
XMLReader * createIntEntReader (const XMLCh *const sysId, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLCh *const dataBuf, const XMLSize_t dataLen, const bool copyBuf, const bool calcSrcOfs=true, XMLSize_t lowWaterMark=100)
bool isScanningPERefOutOfLiteral () const
bool pushReader (XMLReader *const reader, XMLEntityDecl *const entity)
void reset ()
const XMLCh * getCurrentEncodingStr () const
const XMLEntityDecl * getCurrentEntity () const
XMLEntityDecl * getCurrentEntity ()
const XMLReader * getCurrentReader () const
XMLReader * getCurrentReader ()
XMLSize_t getCurrentReaderNum () const
XMLSize_t getReaderDepth () const
void getLastExtEntityInfo (LastExtEntityInfo &lastInfo) const
XMLFilePos getSrcOffset () const
bool getThrowEOE () const
void setEntityHandler (XMLEntityHandler *const newHandler)
void setThrowEOE (const bool newValue)
void setXMLVersion (const XMLReader::XMLVersion version)
void setStandardUriConformant (const bool newValue)
virtual const XMLCh * getPublicId () const
virtual const XMLCh * getSystemId () const
virtual XMLFileLoc getLineNumber () const
virtual XMLFileLoc getColumnNumber () const
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Public Member Functions inherited from Locator
Locator ()
virtual ~Locator ()
Locator ()
virtual ~Locator ()
Locator ()
virtual ~Locator ()
Private Member Functions
const XMLReader * getLastExtEntity (const XMLEntityDecl *&itsEntity) const
bool popReader ()
ReaderMgr (const ReaderMgr &)
ReaderMgr & operator= (const ReaderMgr &)
const XMLReader * getLastExtEntity (const XMLEntityDecl *&itsEntity) const
bool popReader ()
ReaderMgr (const ReaderMgr &)
ReaderMgr & operator= (const ReaderMgr &)
const XMLReader * getLastExtEntity (const XMLEntityDecl *&itsEntity) const
bool popReader ()
ReaderMgr (const ReaderMgr &)
ReaderMgr & operator= (const ReaderMgr &)
Private Attributes
XMLEntityDecl * fCurEntity
XMLReader * fCurReader
XMLEntityHandler * fEntityHandler
RefStackOf< XMLEntityDecl > * fEntityStack
unsigned int fNextReaderNum
RefStackOf< XMLReader > * fReaderStack
bool fThrowEOE
XMLReader::XMLVersion fXMLVersion
bool fStandardUriConformant
MemoryManager * fMemoryManager
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 48 of file ReaderMgr.hpp.
Constructor & Destructor Documentation
ReaderMgr() [1/6]
ReaderMgr::ReaderMgr (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ReaderMgr() [1/3]
ReaderMgr::~ReaderMgr ()
ReaderMgr() [2/6]
ReaderMgr::ReaderMgr (const ReaderMgr &) private
ReaderMgr() [3/6]
ReaderMgr::ReaderMgr (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ReaderMgr() [2/3]
ReaderMgr::~ReaderMgr ()
ReaderMgr() [4/6]
ReaderMgr::ReaderMgr (const ReaderMgr &) private
ReaderMgr() [5/6]
ReaderMgr::ReaderMgr (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~ReaderMgr() [3/3]
ReaderMgr::~ReaderMgr ()
ReaderMgr() [6/6]
ReaderMgr::ReaderMgr (const ReaderMgr &) private
Member Function Documentation
atEOF() [1/3]
bool ReaderMgr::atEOF () const
atEOF() [2/3]
bool ReaderMgr::atEOF () const
atEOF() [3/3]
bool ReaderMgr::atEOF () const
cleanStackBackTo() [1/3]
void ReaderMgr::cleanStackBackTo (const XMLSize_t readerNum)
cleanStackBackTo() [2/3]
void ReaderMgr::cleanStackBackTo (const XMLSize_t readerNum)
cleanStackBackTo() [3/3]
void ReaderMgr::cleanStackBackTo (const XMLSize_t readerNum)
createIntEntReader() [1/3]
XMLReader* ReaderMgr::createIntEntReader (const XMLCh *const sysId, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLCh *const dataBuf, const XMLSize_t dataLen, const bool copyBuf, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100)
createIntEntReader() [2/3]
XMLReader* ReaderMgr::createIntEntReader (const XMLCh *const sysId, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLCh *const dataBuf, const XMLSize_t dataLen, const bool copyBuf, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100)
createIntEntReader() [3/3]
XMLReader* ReaderMgr::createIntEntReader (const XMLCh *const sysId, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLCh *const dataBuf, const XMLSize_t dataLen, const bool copyBuf, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100)
createReader() [1/9]
XMLReader* ReaderMgr::createReader (const InputSource & src, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, const bool calcSrsOfs = true, XMLSize_t lowWaterMark = 100)
createReader() [2/9]
XMLReader* ReaderMgr::createReader (const InputSource & src, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, const bool calcSrsOfs = true, XMLSize_t lowWaterMark = 100)
createReader() [3/9]
XMLReader* ReaderMgr::createReader (const InputSource & src, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, const bool calcSrsOfs = true, XMLSize_t lowWaterMark = 100)
createReader() [4/9]
XMLReader* ReaderMgr::createReader (const XMLCh *const baseURI, const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *& srcToFill, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100, const bool disableDefaultEntityResolution = false)
createReader() [5/9]
XMLReader* ReaderMgr::createReader (const XMLCh *const baseURI, const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *& srcToFill, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100, const bool disableDefaultEntityResolution = false)
createReader() [6/9]
XMLReader* ReaderMgr::createReader (const XMLCh *const baseURI, const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *& srcToFill, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100, const bool disableDefaultEntityResolution = false)
createReader() [7/9]
XMLReader* ReaderMgr::createReader (const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *& srcToFill, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100, const bool disableDefaultEntityResolution = false)
createReader() [8/9]
XMLReader* ReaderMgr::createReader (const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *& srcToFill, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100, const bool disableDefaultEntityResolution = false)
createReader() [9/9]
XMLReader* ReaderMgr::createReader (const XMLCh *const sysId, const XMLCh *const pubId, const bool xmlDecl, const XMLReader::RefFrom refFrom, const XMLReader::Types type, const XMLReader::Sources source, InputSource *& srcToFill, const bool calcSrcOfs = true, XMLSize_t lowWaterMark = 100, const bool disableDefaultEntityResolution = false)
getColumnNumber() [1/3]
virtual XMLFileLoc ReaderMgr::getColumnNumber () const virtual
Return the column number where the current document event ends. Note that this is the column number of the first character after the text associated with the document event. The first column in a line is position 1.
Returns
The column number, or 0 if none is available.
See also
getLineNumber
Implements Locator.
getColumnNumber() [2/3]
virtual XMLFileLoc ReaderMgr::getColumnNumber () const virtual
Return the column number where the current document event ends. Note that this is the column number of the first character after the text associated with the document event. The first column in a line is position 1.
Returns
The column number, or 0 if none is available.
See also
getLineNumber
Implements Locator.
getColumnNumber() [3/3]
virtual XMLFileLoc ReaderMgr::getColumnNumber () const virtual
Return the column number where the current document event ends. Note that this is the column number of the first character after the text associated with the document event. The first column in a line is position 1.
Returns
The column number, or 0 if none is available.
See also
getLineNumber
Implements Locator.
getCurrentEncodingStr() [1/3]
const XMLCh* ReaderMgr::getCurrentEncodingStr () const
getCurrentEncodingStr() [2/3]
const XMLCh* ReaderMgr::getCurrentEncodingStr () const
getCurrentEncodingStr() [3/3]
const XMLCh* ReaderMgr::getCurrentEncodingStr () const
getCurrentEntity() [1/6]
XMLEntityDecl* ReaderMgr::getCurrentEntity ()
getCurrentEntity() [2/6]
XMLEntityDecl* ReaderMgr::getCurrentEntity ()
getCurrentEntity() [3/6]
XMLEntityDecl* ReaderMgr::getCurrentEntity ()
getCurrentEntity() [4/6]
const XMLEntityDecl* ReaderMgr::getCurrentEntity () const
getCurrentEntity() [5/6]
const XMLEntityDecl* ReaderMgr::getCurrentEntity () const
getCurrentEntity() [6/6]
const XMLEntityDecl* ReaderMgr::getCurrentEntity () const
getCurrentReader() [1/6]
XMLReader * ReaderMgr::getCurrentReader () inline
Definition at line 286 of file ReaderMgr.hpp.
References fCurReader.
getCurrentReader() [2/6]
XMLReader* ReaderMgr::getCurrentReader ()
getCurrentReader() [3/6]
XMLReader* ReaderMgr::getCurrentReader ()
getCurrentReader() [4/6]
const XMLReader * ReaderMgr::getCurrentReader () const inline
Definition at line 281 of file ReaderMgr.hpp.
References fCurReader.
getCurrentReader() [5/6]
const XMLReader* ReaderMgr::getCurrentReader () const
getCurrentReader() [6/6]
const XMLReader* ReaderMgr::getCurrentReader () const
getCurrentReaderNum() [1/3]
XMLSize_t ReaderMgr::getCurrentReaderNum () const inline
Definition at line 276 of file ReaderMgr.hpp.
References fCurReader, and XMLReader::getReaderNum().
Referenced by DTDScanner::isReadingExternalEntity().
getCurrentReaderNum() [2/3]
XMLSize_t ReaderMgr::getCurrentReaderNum () const
getCurrentReaderNum() [3/3]
XMLSize_t ReaderMgr::getCurrentReaderNum () const
getLastExtEntity() [1/3]
const XMLReader* ReaderMgr::getLastExtEntity (const XMLEntityDecl *& itsEntity) const private
getLastExtEntity() [2/3]
const XMLReader* ReaderMgr::getLastExtEntity (const XMLEntityDecl *& itsEntity) const private
getLastExtEntity() [3/3]
const XMLReader* ReaderMgr::getLastExtEntity (const XMLEntityDecl *& itsEntity) const private
getLastExtEntityInfo() [1/3]
void ReaderMgr::getLastExtEntityInfo (LastExtEntityInfo & lastInfo) const
getLastExtEntityInfo() [2/3]
void ReaderMgr::getLastExtEntityInfo (LastExtEntityInfo & lastInfo) const
getLastExtEntityInfo() [3/3]
void ReaderMgr::getLastExtEntityInfo (LastExtEntityInfo & lastInfo) const
getLineNumber() [1/3]
virtual XMLFileLoc ReaderMgr::getLineNumber () const virtual
Return the line number where the current document event ends. Note that this is the line position of the first character after the text associated with the document event.
Returns
The line number, or 0 if none is available.
See also
getColumnNumber
Implements Locator.
getLineNumber() [2/3]
virtual XMLFileLoc ReaderMgr::getLineNumber () const virtual
Return the line number where the current document event ends. Note that this is the line position of the first character after the text associated with the document event.
Returns
The line number, or 0 if none is available.
See also
getColumnNumber
Implements Locator.
getLineNumber() [3/3]
virtual XMLFileLoc ReaderMgr::getLineNumber () const virtual
Return the line number where the current document event ends. Note that this is the line position of the first character after the text associated with the document event.
Returns
The line number, or 0 if none is available.
See also
getColumnNumber
Implements Locator.
getName() [1/3]
bool ReaderMgr::getName (XMLBuffer & toFill) inline
Definition at line 291 of file ReaderMgr.hpp.
References fCurReader, XMLReader::getName(), and XMLBuffer::reset().
getName() [2/3]
bool ReaderMgr::getName (XMLBuffer & toFill)
getName() [3/3]
bool ReaderMgr::getName (XMLBuffer & toFill)
getNameToken() [1/3]
bool ReaderMgr::getNameToken (XMLBuffer & toFill) inline
Definition at line 303 of file ReaderMgr.hpp.
References fCurReader, XMLReader::getName(), and XMLBuffer::reset().
getNameToken() [2/3]
bool ReaderMgr::getNameToken (XMLBuffer & toFill)
getNameToken() [3/3]
bool ReaderMgr::getNameToken (XMLBuffer & toFill)
getNextChar() [1/3]
XMLCh ReaderMgr::getNextChar ()
Referenced by skipPastChar(), and skipToChar().
getNextChar() [2/3]
XMLCh ReaderMgr::getNextChar ()
getNextChar() [3/3]
XMLCh ReaderMgr::getNextChar ()
getNextCharIfNot() [1/3]
bool ReaderMgr::getNextCharIfNot (const XMLCh chNotToGet, XMLCh & chGotten) inline
Definition at line 309 of file ReaderMgr.hpp.
References fCurReader, and XMLReader::getNextCharIfNot().
getNextCharIfNot() [2/3]
bool ReaderMgr::getNextCharIfNot (const XMLCh chNotToGet, XMLCh & chGotten)
getNextCharIfNot() [3/3]
bool ReaderMgr::getNextCharIfNot (const XMLCh chNotToGet, XMLCh & chGotten)
getPublicId() [1/3]
virtual const XMLCh* ReaderMgr::getPublicId () const virtual
Return the public identifier for the current document event.
This will be the public identifier
Returns
A string containing the public identifier, or null if none is available.
See also
getSystemId
Implements Locator.
getPublicId() [2/3]
virtual const XMLCh* ReaderMgr::getPublicId () const virtual
Return the public identifier for the current document event.
This will be the public identifier
Returns
A string containing the public identifier, or null if none is available.
See also
getSystemId
Implements Locator.
getPublicId() [3/3]
virtual const XMLCh* ReaderMgr::getPublicId () const virtual
Return the public identifier for the current document event.
This will be the public identifier
Returns
A string containing the public identifier, or null if none is available.
See also
getSystemId
Implements Locator.
getQName() [1/3]
bool ReaderMgr::getQName (XMLBuffer & toFill, int * colonPosition) inline
Definition at line 297 of file ReaderMgr.hpp.
References fCurReader, XMLReader::getQName(), and XMLBuffer::reset().
getQName() [2/3]
bool ReaderMgr::getQName (XMLBuffer & toFill, int * colonPosition)
getQName() [3/3]
bool ReaderMgr::getQName (XMLBuffer & toFill, int * colonPosition)
getReaderDepth() [1/3]
XMLSize_t ReaderMgr::getReaderDepth () const
getReaderDepth() [2/3]
XMLSize_t ReaderMgr::getReaderDepth () const
getReaderDepth() [3/3]
XMLSize_t ReaderMgr::getReaderDepth () const
getSpaces() [1/3]
void ReaderMgr::getSpaces (XMLBuffer & toFill)
getSpaces() [2/3]
void ReaderMgr::getSpaces (XMLBuffer & toFill)
getSpaces() [3/3]
void ReaderMgr::getSpaces (XMLBuffer & toFill)
getSrcOffset() [1/3]
XMLFilePos ReaderMgr::getSrcOffset () const inline
Definition at line 324 of file ReaderMgr.hpp.
References fCurReader, and XMLReader::getSrcOffset().
Referenced by XMLScanner::getSrcOffset().
getSrcOffset() [2/3]
XMLFilePos ReaderMgr::getSrcOffset () const
getSrcOffset() [3/3]
XMLFilePos ReaderMgr::getSrcOffset () const
getSystemId() [1/3]
virtual const XMLCh* ReaderMgr::getSystemId () const virtual
Return the system identifier for the current document event.
If the system identifier is a URL, the parser must resolve it fully before passing it to the application.
Returns
A string containing the system identifier, or null if none is available.
See also
getPublicId
Implements Locator.
getSystemId() [2/3]
virtual const XMLCh* ReaderMgr::getSystemId () const virtual
Return the system identifier for the current document event.
If the system identifier is a URL, the parser must resolve it fully before passing it to the application.
Returns
A string containing the system identifier, or null if none is available.
See also
getPublicId
Implements Locator.
getSystemId() [3/3]
virtual const XMLCh* ReaderMgr::getSystemId () const virtual
Return the system identifier for the current document event.
If the system identifier is a URL, the parser must resolve it fully before passing it to the application.
Returns
A string containing the system identifier, or null if none is available.
See also
getPublicId
Implements Locator.
getThrowEOE() [1/3]
bool ReaderMgr::getThrowEOE () const inline
Definition at line 319 of file ReaderMgr.hpp.
References fThrowEOE.
getThrowEOE() [2/3]
bool ReaderMgr::getThrowEOE () const
getThrowEOE() [3/3]
bool ReaderMgr::getThrowEOE () const
getUpToCharOrWS() [1/3]
void ReaderMgr::getUpToCharOrWS (XMLBuffer & toFill, const XMLCh toCheck)
getUpToCharOrWS() [2/3]
void ReaderMgr::getUpToCharOrWS (XMLBuffer & toFill, const XMLCh toCheck)
getUpToCharOrWS() [3/3]
void ReaderMgr::getUpToCharOrWS (XMLBuffer & toFill, const XMLCh toCheck)
isEmpty() [1/3]
bool ReaderMgr::isEmpty () const
isEmpty() [2/3]
bool ReaderMgr::isEmpty () const
isEmpty() [3/3]
bool ReaderMgr::isEmpty () const
isScanningPERefOutOfLiteral() [1/3]
bool ReaderMgr::isScanningPERefOutOfLiteral () const
isScanningPERefOutOfLiteral() [2/3]
bool ReaderMgr::isScanningPERefOutOfLiteral () const
isScanningPERefOutOfLiteral() [3/3]
bool ReaderMgr::isScanningPERefOutOfLiteral () const
lookingAtChar() [1/3]
bool ReaderMgr::lookingAtChar (const XMLCh toCheck) inline
Definition at line 329 of file ReaderMgr.hpp.
References peekNextChar().
lookingAtChar() [2/3]
bool ReaderMgr::lookingAtChar (const XMLCh toCheck)
lookingAtChar() [3/3]
bool ReaderMgr::lookingAtChar (const XMLCh toCheck)
lookingAtSpace() [1/3]
bool ReaderMgr::lookingAtSpace () inline
Definition at line 334 of file ReaderMgr.hpp.
References fCurReader, XMLReader::isWhitespace(), and peekNextChar().
lookingAtSpace() [2/3]
bool ReaderMgr::lookingAtSpace ()
lookingAtSpace() [3/3]
bool ReaderMgr::lookingAtSpace ()
movePlainContentChars() [1/3]
void ReaderMgr::movePlainContentChars (XMLBuffer & dest) inline
Definition at line 314 of file ReaderMgr.hpp.
References fCurReader, and XMLReader::movePlainContentChars().
movePlainContentChars() [2/3]
void ReaderMgr::movePlainContentChars (XMLBuffer & dest)
movePlainContentChars() [3/3]
void ReaderMgr::movePlainContentChars (XMLBuffer & dest)
operator=() [1/3]
ReaderMgr& ReaderMgr::operator= (const ReaderMgr &) private
operator=() [2/3]
ReaderMgr& ReaderMgr::operator= (const ReaderMgr &) private
operator=() [3/3]
ReaderMgr& ReaderMgr::operator= (const ReaderMgr &) private
peekNextChar() [1/3]
XMLCh ReaderMgr::peekNextChar ()
Referenced by lookingAtChar(), and lookingAtSpace().
peekNextChar() [2/3]
XMLCh ReaderMgr::peekNextChar ()
peekNextChar() [3/3]
XMLCh ReaderMgr::peekNextChar ()
peekString() [1/3]
bool ReaderMgr::peekString (const XMLCh *const toPeek) inline
Definition at line 383 of file ReaderMgr.hpp.
References fCurReader, and XMLReader::peekString().
peekString() [2/3]
bool ReaderMgr::peekString (const XMLCh *const toPeek)
peekString() [3/3]
bool ReaderMgr::peekString (const XMLCh *const toPeek)
popReader() [1/3]
bool ReaderMgr::popReader () private
popReader() [2/3]
bool ReaderMgr::popReader () private
popReader() [3/3]
bool ReaderMgr::popReader () private
pushReader() [1/3]
bool ReaderMgr::pushReader (XMLReader *const reader, XMLEntityDecl *const entity)
pushReader() [2/3]
bool ReaderMgr::pushReader (XMLReader *const reader, XMLEntityDecl *const entity)
pushReader() [3/3]
bool ReaderMgr::pushReader (XMLReader *const reader, XMLEntityDecl *const entity)
reset() [1/3]
void ReaderMgr::reset ()
reset() [2/3]
void ReaderMgr::reset ()
reset() [3/3]
void ReaderMgr::reset ()
setEntityHandler() [1/3]
void ReaderMgr::setEntityHandler (XMLEntityHandler *const newHandler) inline
Definition at line 388 of file ReaderMgr.hpp.
References fEntityHandler.
Referenced by XMLScanner::setEntityHandler().
setEntityHandler() [2/3]
void ReaderMgr::setEntityHandler (XMLEntityHandler *const newHandler)
setEntityHandler() [3/3]
void ReaderMgr::setEntityHandler (XMLEntityHandler *const newHandler)
setStandardUriConformant() [1/3]
void ReaderMgr::setStandardUriConformant (const bool newValue) inline
Definition at line 345 of file ReaderMgr.hpp.
References fStandardUriConformant.
Referenced by XMLScanner::setStandardUriConformant().
setStandardUriConformant() [2/3]
void ReaderMgr::setStandardUriConformant (const bool newValue)
setStandardUriConformant() [3/3]
void ReaderMgr::setStandardUriConformant (const bool newValue)
setThrowEOE() [1/3]
void ReaderMgr::setThrowEOE (const bool newValue) inline
Definition at line 340 of file ReaderMgr.hpp.
References fThrowEOE.
Referenced by ThrowEOEJanitor::ThrowEOEJanitor().
setThrowEOE() [2/3]
void ReaderMgr::setThrowEOE (const bool newValue)
setThrowEOE() [3/3]
void ReaderMgr::setThrowEOE (const bool newValue)
setXMLVersion() [1/3]
void ReaderMgr::setXMLVersion (const XMLReader::XMLVersion version) inline
Definition at line 393 of file ReaderMgr.hpp.
References fCurReader, fXMLVersion, and XMLReader::setXMLVersion().
setXMLVersion() [2/3]
void ReaderMgr::setXMLVersion (const XMLReader::XMLVersion version)
setXMLVersion() [3/3]
void ReaderMgr::setXMLVersion (const XMLReader::XMLVersion version)
skipIfQuote() [1/3]
bool ReaderMgr::skipIfQuote (XMLCh & chGotten)
skipIfQuote() [2/3]
bool ReaderMgr::skipIfQuote (XMLCh & chGotten)
skipIfQuote() [3/3]
bool ReaderMgr::skipIfQuote (XMLCh & chGotten)
skipPastChar() [1/3]
void ReaderMgr::skipPastChar (const XMLCh toSkip) inline
Definition at line 372 of file ReaderMgr.hpp.
References getNextChar().
skipPastChar() [2/3]
void ReaderMgr::skipPastChar (const XMLCh toSkip)
skipPastChar() [3/3]
void ReaderMgr::skipPastChar (const XMLCh toSkip)
skipPastSpaces() [1/6]
void ReaderMgr::skipPastSpaces ()
skipPastSpaces() [2/6]
void ReaderMgr::skipPastSpaces ()
skipPastSpaces() [3/6]
void ReaderMgr::skipPastSpaces ()
skipPastSpaces() [4/6]
void ReaderMgr::skipPastSpaces (bool & skippedSomething, bool inDecl = false)
skipPastSpaces() [5/6]
void ReaderMgr::skipPastSpaces (bool & skippedSomething, bool inDecl = false)
skipPastSpaces() [6/6]
void ReaderMgr::skipPastSpaces (bool & skippedSomething, bool inDecl = false)
skippedChar() [1/3]
bool ReaderMgr::skippedChar (const XMLCh toSkip)
skippedChar() [2/3]
bool ReaderMgr::skippedChar (const XMLCh toSkip)
skippedChar() [3/3]
bool ReaderMgr::skippedChar (const XMLCh toSkip)
skippedSpace() [1/3]
bool ReaderMgr::skippedSpace ()
skippedSpace() [2/3]
bool ReaderMgr::skippedSpace ()
skippedSpace() [3/3]
bool ReaderMgr::skippedSpace ()
skippedString() [1/3]
bool ReaderMgr::skippedString (const XMLCh *const toSkip) inline
Definition at line 350 of file ReaderMgr.hpp.
References fCurReader, and XMLReader::skippedString().
skippedString() [2/3]
bool ReaderMgr::skippedString (const XMLCh *const toSkip)
skippedString() [3/3]
bool ReaderMgr::skippedString (const XMLCh *const toSkip)
skippedStringLong() [1/3]
bool ReaderMgr::skippedStringLong (const XMLCh *const toSkip) inline
Definition at line 355 of file ReaderMgr.hpp.
References fCurReader, and XMLReader::skippedStringLong().
skippedStringLong() [2/3]
bool ReaderMgr::skippedStringLong (const XMLCh *const toSkip)
skippedStringLong() [3/3]
bool ReaderMgr::skippedStringLong (const XMLCh *const toSkip)
skipQuotedString() [1/3]
void ReaderMgr::skipQuotedString (const XMLCh quoteCh)
skipQuotedString() [2/3]
void ReaderMgr::skipQuotedString (const XMLCh quoteCh)
skipQuotedString() [3/3]
void ReaderMgr::skipQuotedString (const XMLCh quoteCh)
skipToChar() [1/3]
void ReaderMgr::skipToChar (const XMLCh toSkipTo) inline
Definition at line 360 of file ReaderMgr.hpp.
References getNextChar().
skipToChar() [2/3]
void ReaderMgr::skipToChar (const XMLCh toSkipTo)
skipToChar() [3/3]
void ReaderMgr::skipToChar (const XMLCh toSkipTo)
skipUntilIn() [1/3]
XMLCh ReaderMgr::skipUntilIn (const XMLCh *const listToSkip)
skipUntilIn() [2/3]
XMLCh ReaderMgr::skipUntilIn (const XMLCh *const listToSkip)
skipUntilIn() [3/3]
XMLCh ReaderMgr::skipUntilIn (const XMLCh *const listToSkip)
skipUntilInOrWS() [1/3]
XMLCh ReaderMgr::skipUntilInOrWS (const XMLCh *const listToSkip)
skipUntilInOrWS() [2/3]
XMLCh ReaderMgr::skipUntilInOrWS (const XMLCh *const listToSkip)
skipUntilInOrWS() [3/3]
XMLCh ReaderMgr::skipUntilInOrWS (const XMLCh *const listToSkip)
Member Data Documentation
fCurEntity
XMLEntityDecl * ReaderMgr::fCurEntity private
Definition at line 255 of file ReaderMgr.hpp.
fCurReader
XMLReader * ReaderMgr::fCurReader private
Definition at line 256 of file ReaderMgr.hpp.
Referenced by getCurrentReader(), getCurrentReaderNum(), getName(), getNameToken(), getNextCharIfNot(), getQName(), getSrcOffset(), lookingAtSpace(), movePlainContentChars(), peekString(), setXMLVersion(), skippedString(), and skippedStringLong().
fEntityHandler
XMLEntityHandler * ReaderMgr::fEntityHandler private
Definition at line 257 of file ReaderMgr.hpp.
Referenced by setEntityHandler().
fEntityStack
RefStackOf< XMLEntityDecl > * ReaderMgr::fEntityStack private
Definition at line 258 of file ReaderMgr.hpp.
fMemoryManager
MemoryManager * ReaderMgr::fMemoryManager private
Definition at line 264 of file ReaderMgr.hpp.
fNextReaderNum
unsigned int ReaderMgr::fNextReaderNum private
Definition at line 259 of file ReaderMgr.hpp.
fReaderStack
RefStackOf< XMLReader > * ReaderMgr::fReaderStack private
Definition at line 260 of file ReaderMgr.hpp.
fStandardUriConformant
bool ReaderMgr::fStandardUriConformant private
Definition at line 263 of file ReaderMgr.hpp.
Referenced by setStandardUriConformant().
fThrowEOE
bool ReaderMgr::fThrowEOE private
Definition at line 261 of file ReaderMgr.hpp.
Referenced by getThrowEOE(), and setThrowEOE().
fXMLVersion
XMLReader::XMLVersion ReaderMgr::fXMLVersion private
Definition at line 262 of file ReaderMgr.hpp.
Referenced by setXMLVersion().
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/internal/ReaderMgr.hpp