Seamly2D: ThrowEOEJanitor Class Reference
ThrowEOEJanitor Class Reference
#include <ReaderMgr.hpp>
Public Member Functions
ThrowEOEJanitor (ReaderMgr *mgrTarget, const bool newValue)
~ThrowEOEJanitor ()
ThrowEOEJanitor (ReaderMgr *mgrTarget, const bool newValue)
~ThrowEOEJanitor ()
ThrowEOEJanitor (ReaderMgr *mgrTarget, const bool newValue)
~ThrowEOEJanitor ()
Private Member Functions
ThrowEOEJanitor (const ThrowEOEJanitor &)
ThrowEOEJanitor & operator= (const ThrowEOEJanitor &)
ThrowEOEJanitor (const ThrowEOEJanitor &)
ThrowEOEJanitor & operator= (const ThrowEOEJanitor &)
ThrowEOEJanitor (const ThrowEOEJanitor &)
ThrowEOEJanitor & operator= (const ThrowEOEJanitor &)
Private Attributes
bool fOld
ReaderMgr * fMgr
Detailed Description
Definition at line 404 of file ReaderMgr.hpp.
Constructor & Destructor Documentation
ThrowEOEJanitor() [1/6]
ThrowEOEJanitor::ThrowEOEJanitor (ReaderMgr * mgrTarget, const bool newValue) inline
Definition at line 410 of file ReaderMgr.hpp.
References ReaderMgr::setThrowEOE().
~ThrowEOEJanitor() [1/3]
ThrowEOEJanitor::~ThrowEOEJanitor () inline
Definition at line 418 of file ReaderMgr.hpp.
ThrowEOEJanitor() [2/6]
ThrowEOEJanitor::ThrowEOEJanitor (const ThrowEOEJanitor &) private
ThrowEOEJanitor() [3/6]
ThrowEOEJanitor::ThrowEOEJanitor (ReaderMgr * mgrTarget, const bool newValue) inline
Definition at line 410 of file ReaderMgr.hpp.
References ReaderMgr::setThrowEOE().
~ThrowEOEJanitor() [2/3]
ThrowEOEJanitor::~ThrowEOEJanitor () inline
Definition at line 418 of file ReaderMgr.hpp.
ThrowEOEJanitor() [4/6]
ThrowEOEJanitor::ThrowEOEJanitor (const ThrowEOEJanitor &) private
ThrowEOEJanitor() [5/6]
ThrowEOEJanitor::ThrowEOEJanitor (ReaderMgr * mgrTarget, const bool newValue) inline
Definition at line 410 of file ReaderMgr.hpp.
References ReaderMgr::setThrowEOE().
~ThrowEOEJanitor() [3/3]
ThrowEOEJanitor::~ThrowEOEJanitor () inline
Definition at line 418 of file ReaderMgr.hpp.
ThrowEOEJanitor() [6/6]
ThrowEOEJanitor::ThrowEOEJanitor (const ThrowEOEJanitor &) private
Member Function Documentation
operator=() [1/3]
ThrowEOEJanitor& ThrowEOEJanitor::operator= (const ThrowEOEJanitor &) private
operator=() [2/3]
ThrowEOEJanitor& ThrowEOEJanitor::operator= (const ThrowEOEJanitor &) private
operator=() [3/3]
ThrowEOEJanitor& ThrowEOEJanitor::operator= (const ThrowEOEJanitor &) private
Member Data Documentation
fMgr
ReaderMgr * ThrowEOEJanitor::fMgr private
Definition at line 442 of file ReaderMgr.hpp.
fOld
bool ThrowEOEJanitor::fOld private
Definition at line 441 of file ReaderMgr.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/internal/ReaderMgr.hpp