Seamly2D: QT_WARNING_POP Namespace Reference
QT_WARNING_POP Namespace Reference
Functions
VPiecePath GetPiecePath (int piece, VAbstractPattern *doc, quint32 id)
VPiecePath GetPiece1MainPath (VAbstractPattern *doc, quint32 id)
VPiecePath GetPiece2MainPath (VAbstractPattern *doc, quint32 id)
QVector< CustomSARecord > GetPiece2CSAPaths (VAbstractPattern *doc, quint32 id)
QVector< quint32 > GetPiece2InternalPaths (VAbstractPattern *doc, quint32 id)
QVector< quint32 > GetPiece2Anchors (VAbstractPattern *doc, quint32 id)
QString getBlockName (VAbstractPattern *doc, quint32 piece1_Id, quint32 piece2_Id)
void BiasRotatePoint (VPointF *point, qreal dx, qreal dy, const QPointF &pRotate, qreal angle)
BiasRotatePoint bias and rotate point.
void PointsOnEdge (const VPiecePath &path, quint32 index, VPointF &p1, VPointF &p2, VContainer *data)
void UnionInitParameters (const UnionToolInitData &initData, const VPiecePath &piece1Path, const VPiecePath &piece2Path, VPieceNode &piece1_Pt1, qreal &dx, qreal &dy, qreal &angle)
quint32 AddNodePoint (const VPieceNode &node, const UnionToolInitData &initData, quint32 idTool, QVector< quint32 > &children, const QString &blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
quint32 AddAnchorPoint (quint32 id, const UnionToolInitData &initData, quint32 idTool, QVector< quint32 > &children, const QString &blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
quint32 AddNodeArc (const VPieceNode &node, const UnionToolInitData &initData, quint32 idTool, QVector< quint32 > &children, const QString &blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
quint32 AddNodeElArc (const VPieceNode &node, const UnionToolInitData &initData, quint32 idTool, QVector< quint32 > &children, const QString &blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
quint32 AddNodeSpline (const VPieceNode &node, const UnionToolInitData &initData, quint32 idTool, QVector< quint32 > &children, const QString &blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
quint32 AddNodeSplinePath (const VPieceNode &node, const UnionToolInitData &initData, quint32 idTool, QVector< quint32 > &children, const QString &blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void AddNodeToNewPath (const UnionToolInitData &initData, VPiecePath &newPath, VPieceNode node, quint32 idTool, QVector< quint32 > &children, const QString &blockName, qreal dx=0, qreal dy=0, quint32 pRotate=NULL_ID, qreal angle=0)
AddNodeToNewPath create union adding one node at a time.
void FindIndexJ (qint32 piece2Points, const VPiecePath &piece2Path, quint32 piece2_Index, qint32 &j)
QDomElement GetTagChildren (VAbstractPattern *doc, quint32 id)
void SaveChildren (VAbstractPattern *doc, quint32 id, QDomElement section, const QVector< quint32 > &children)
void SaveNodesChildren (VAbstractPattern *doc, quint32 id, const QVector< quint32 > &children)
void SaveCSAChildren (VAbstractPattern *doc, quint32 id, const QVector< quint32 > &children)
void SaveInternalPathsChildren (VAbstractPattern *doc, quint32 id, const QVector< quint32 > &children)
void SaveAnchorsChildren (VAbstractPattern *doc, quint32 id, const QVector< quint32 > &children)
QVector< quint32 > GetChildren (VAbstractPattern *doc, quint32 id, const QString &tagName)
QVector< quint32 > GetNodesChildren (VAbstractPattern *doc, quint32 id)
QVector< quint32 > GetCSAChildren (VAbstractPattern *doc, quint32 id)
QVector< quint32 > GetInternalPathsChildren (VAbstractPattern *doc, quint32 id)
QVector< quint32 > getAnchorChildren (VAbstractPattern *doc, quint32 id)
quint32 TakeNextId (QVector< quint32 > &children)
void UpdateNodePoint (VContainer *data, const VPieceNode &node, QVector< quint32 > &children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void UpdateNodeArc (VContainer *data, const VPieceNode &node, QVector< quint32 > &children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void UpdateNodeElArc (VContainer *data, const VPieceNode &node, QVector< quint32 > &children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void UpdateNodeSpline (VContainer *data, const VPieceNode &node, QVector< quint32 > &children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void UpdateNodeSplinePath (VContainer *data, const VPieceNode &node, QVector< quint32 > &children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void UpdatePathNode (VContainer *data, const VPieceNode &node, QVector< quint32 > &children, qreal dx=0, qreal dy=0, quint32 pRotate=NULL_ID, qreal angle=0)
UpdateNodes update nodes of union.
void CreateUnitedNodes (VPiece &newPiece, const VPiece &piece1, const VPiece &piece2, quint32 id, const QString &blockName, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void createCSAUnion (VPiece &newPiece, const VPiece &d, QVector< quint32 > &children, quint32 id, const QString &blockName, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void CreateUnitedCSA (VPiece &newPiece, const VPiece &piece1, const VPiece &piece2, quint32 id, const QString &blockName, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void createUnionInternalPaths (VPiece &newPiece, const VPiece &d, QVector< quint32 > &children, quint32 id, const QString &blockName, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void CreateUnitedInternalPaths (VPiece &newPiece, const VPiece &piece1, const VPiece &piece2, quint32 id, const QString &blockName, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void createUnionAnchors (VPiece &newPiece, const VPiece &d, QVector< quint32 > &children, quint32 idTool, const QString &blockName, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void createUnitedAnchors (VPiece &newPiece, const VPiece &piece1, const VPiece &piece2, quint32 id, const QString &blockName, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void UpdateUnitedNodes (quint32 id, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void createUnionPaths (const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle, const QVector< quint32 > &records, QVector< quint32 > children)
void updateUnionCSA (quint32 id, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle, const QVector< CustomSARecord > &records)
void updateUnionInternalPaths (quint32 id, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle, const QVector< quint32 > &records)
void updateUnionAnchors (quint32 id, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle, const QVector< quint32 > &records)
void createUnion (quint32 id, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void updateUnion (quint32 id, const UnionToolInitData &initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
void unitePieces (quint32 id, const UnionToolInitData &initData)
Function Documentation
AddAnchorPoint()
quint32 QT_WARNING_POP::AddAnchorPoint (quint32 id, const UnionToolInitData & initData, quint32 idTool, QVector< quint32 > & children, const QString & blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 418 of file union_tool.cpp.
References VContainer::AddGObject(), BiasRotatePoint(), AnchorPointTool::Create(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, FullParse, VContainer::GeometricObject(), Modeling, and NULL_ID.
Referenced by createUnionAnchors().
AddNodeArc()
quint32 QT_WARNING_POP::AddNodeArc (const VPieceNode & node, const UnionToolInitData & initData, quint32 idTool, QVector< quint32 > & children, const QString & blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 442 of file union_tool.cpp.
References VContainer::AddGObject(), BiasRotatePoint(), VNodeArc::Create(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, FullParse, VContainer::GeometricObject(), VPieceNode::GetId(), Modeling, and NULL_ID.
Referenced by AddNodeToNewPath().
AddNodeElArc()
quint32 QT_WARNING_POP::AddNodeElArc (const VPieceNode & node, const UnionToolInitData & initData, quint32 idTool, QVector< quint32 > & children, const QString & blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 484 of file union_tool.cpp.
References VContainer::AddGObject(), BiasRotatePoint(), VNodeEllipticalArc::Create(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, FullParse, VContainer::GeometricObject(), VPieceNode::GetId(), Modeling, and NULL_ID.
Referenced by AddNodeToNewPath().
AddNodePoint()
quint32 QT_WARNING_POP::AddNodePoint (const VPieceNode & node, const UnionToolInitData & initData, quint32 idTool, QVector< quint32 > & children, const QString & blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 393 of file union_tool.cpp.
References VContainer::AddGObject(), BiasRotatePoint(), VNodePoint::Create(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, FullParse, VContainer::GeometricObject(), VPieceNode::GetId(), Modeling, NULL_ID, and UnionToolInitData::scene.
Referenced by AddNodeToNewPath().
AddNodeSpline()
quint32 QT_WARNING_POP::AddNodeSpline (const VPieceNode & node, const UnionToolInitData & initData, quint32 idTool, QVector< quint32 > & children, const QString & blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 528 of file union_tool.cpp.
References VContainer::AddGObject(), BiasRotatePoint(), VNodeSpline::Create(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, FullParse, VContainer::GeometricObject(), VPieceNode::GetId(), Modeling, NULL_ID, and VGObject::setMode().
Referenced by AddNodeToNewPath().
AddNodeSplinePath()
quint32 QT_WARNING_POP::AddNodeSplinePath (const VPieceNode & node, const UnionToolInitData & initData, quint32 idTool, QVector< quint32 > & children, const QString & blockName, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 563 of file union_tool.cpp.
References VContainer::AddGObject(), BiasRotatePoint(), VNodeSplinePath::Create(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, FullParse, VContainer::GeometricObject(), VSpline::GetC1Length(), VSpline::GetC1LengthFormula(), VSpline::GetC2Length(), VSpline::GetC2LengthFormula(), VSpline::GetEndAngle(), VSpline::GetEndAngleFormula(), VPieceNode::GetId(), VSpline::GetP1(), VSpline::GetP2(), VSpline::GetP3(), VSpline::GetP4(), VSpline::GetStartAngle(), VSpline::GetStartAngleFormula(), Modeling, and NULL_ID.
Referenced by AddNodeToNewPath().
AddNodeToNewPath()
void QT_WARNING_POP::AddNodeToNewPath (const UnionToolInitData & initData, VPiecePath & newPath, VPieceNode node, quint32 idTool, QVector< quint32 > & children, const QString & blockName, qreal dx = 0, qreal dy = 0, quint32 pRotate = NULL_ID, qreal angle = 0)
AddNodeToNewPath create union adding one node at a time.
Definition at line 634 of file union_tool.cpp.
References AddNodeArc(), AddNodeElArc(), AddNodePoint(), AddNodeSpline(), AddNodeSplinePath(), VPiecePath::Append(), VPieceNode::GetTypeTool(), NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, and VPieceNode::SetId().
Referenced by createCSAUnion(), createUnionInternalPaths(), and CreateUnitedNodes().
BiasRotatePoint()
void QT_WARNING_POP::BiasRotatePoint (VPointF * point, qreal dx, qreal dy, const QPointF & pRotate, qreal angle)
BiasRotatePoint bias and rotate point.
Parameters
point point.
dx bias x axis.
dy bias y axis.
pRotate point rotation.
angle angle rotation.
Definition at line 341 of file union_tool.cpp.
References VPointF::setX(), VPointF::setY(), VPointF::x(), and VPointF::y().
Referenced by AddAnchorPoint(), AddNodeArc(), AddNodeElArc(), AddNodePoint(), AddNodeSpline(), AddNodeSplinePath(), UpdateNodeArc(), UpdateNodeElArc(), UpdateNodePoint(), UpdateNodeSpline(), UpdateNodeSplinePath(), and updateUnionAnchors().
createCSAUnion()
void QT_WARNING_POP::createCSAUnion (VPiece & newPiece, const VPiece & d, QVector< quint32 > & children, quint32 id, const QString & blockName, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1055 of file union_tool.cpp.
References AddNodeToNewPath(), VContainer::AddPiecePath(), VPiecePath::at(), VPiecePath::Clear(), VPiecePath::CountNodes(), VToolInternalPath::Create(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, VPiece::GetCustomSARecords(), VContainer::GetPiecePath(), NULL_ID, UnionToolInitData::parse, CustomSARecord::path, and UnionToolInitData::scene.
Referenced by CreateUnitedCSA().
createUnion()
void QT_WARNING_POP::createUnion (quint32 id, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1303 of file union_tool.cpp.
References VAbstractConverter::Convert(), PatternPieceTool::Create(), createUnitedAnchors(), CreateUnitedCSA(), CreateUnitedInternalPaths(), CreateUnitedNodes(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, getBlockName(), VPiece::GetGrainlineGeometry(), VPatternLabelData::GetLabelHeight(), VPatternLabelData::GetLabelWidth(), VGrainlineData::GetLength(), VAbstractPiece::GetMx(), VAbstractPiece::GetMy(), VPiece::GetPath(), VPiece::GetPatternInfo(), VPiece::GetPatternPieceData(), VContainer::GetPiece(), VAbstractPiece::GetSAWidth(), VPiece::getSeamAllowanceWidthFormula(), VAbstractPattern::getTool(), VPiece::isLocked(), UnionToolInitData::parse, VPiecePath::PathPoints(), UnionToolInitData::piece1_Id, UnionToolInitData::piece2_Id, qApp, VLabelTemplate::ReadLines(), PatternPieceTool::Remove(), VContainer::RemovePiece(), VAbstractPattern::RemoveTool(), UnionToolInitData::retainPieces, SCASSERT, UnionToolInitData::scene, VPatternLabelData::SetLabelHeight(), VPieceLabelData::SetLabelTemplate(), VPatternLabelData::SetLabelWidth(), VGrainlineData::SetLength(), VAbstractPiece::SetMx(), VAbstractPiece::SetMy(), VAbstractPiece::SetName(), VAbstractFloatItemData::SetPos(), VAbstractPiece::SetSeamAllowance(), VPiece::setSeamAllowanceWidthFormula(), VPiece::SetUnited(), VAbstractFloatItemData::SetVisible(), and VDomDocument::setXMLContent().
Referenced by unitePieces().
createUnionAnchors()
void QT_WARNING_POP::createUnionAnchors (VPiece & newPiece, const VPiece & d, QVector< quint32 > & children, quint32 idTool, const QString & blockName, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1136 of file union_tool.cpp.
References AddAnchorPoint(), and VPiece::getAnchors().
Referenced by createUnitedAnchors().
createUnionInternalPaths()
void QT_WARNING_POP::createUnionInternalPaths (VPiece & newPiece, const VPiece & d, QVector< quint32 > & children, quint32 id, const QString & blockName, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1095 of file union_tool.cpp.
References AddNodeToNewPath(), VContainer::AddPiecePath(), VPiecePath::at(), VPiecePath::Clear(), VPiecePath::CountNodes(), VToolInternalPath::Create(), UnionToolInitData::data, UnionToolInitData::doc, FromTool, VPiece::GetInternalPaths(), VContainer::GetPiecePath(), NULL_ID, UnionToolInitData::parse, and UnionToolInitData::scene.
Referenced by CreateUnitedInternalPaths().
createUnionPaths()
void QT_WARNING_POP::createUnionPaths (const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle, const QVector< quint32 > & records, QVector< quint32 > children)
Definition at line 1241 of file union_tool.cpp.
References VPiecePath::Append(), VPiecePath::at(), VPiecePath::Clear(), VPiecePath::CountNodes(), UnionToolInitData::data, VContainer::GetPiecePath(), VPieceNode::GetReverse(), VPieceNode::GetTypeTool(), TakeNextId(), UpdatePathNode(), and VContainer::UpdatePiecePath().
Referenced by updateUnionCSA(), and updateUnionInternalPaths().
createUnitedAnchors()
void QT_WARNING_POP::createUnitedAnchors (VPiece & newPiece, const VPiece & piece1, const VPiece & piece2, quint32 id, const QString & blockName, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1151 of file union_tool.cpp.
References createUnionAnchors(), UnionToolInitData::doc, VPiece::getAnchors(), and SaveAnchorsChildren().
Referenced by createUnion().
CreateUnitedCSA()
void QT_WARNING_POP::CreateUnitedCSA (VPiece & newPiece, const VPiece & piece1, const VPiece & piece2, quint32 id, const QString & blockName, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1081 of file union_tool.cpp.
References createCSAUnion(), UnionToolInitData::doc, VPiece::GetCustomSARecords(), and SaveCSAChildren().
Referenced by createUnion().
CreateUnitedInternalPaths()
void QT_WARNING_POP::CreateUnitedInternalPaths (VPiece & newPiece, const VPiece & piece1, const VPiece & piece2, quint32 id, const QString & blockName, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1120 of file union_tool.cpp.
References createUnionInternalPaths(), UnionToolInitData::doc, VPiece::GetInternalPaths(), and SaveInternalPathsChildren().
Referenced by createUnion().
CreateUnitedNodes()
void QT_WARNING_POP::CreateUnitedNodes (VPiece & newPiece, const VPiece & piece1, const VPiece & piece2, quint32 id, const QString & blockName, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1013 of file union_tool.cpp.
References AddNodeToNewPath(), VPiecePath::at(), VPiecePath::CountNodes(), UnionToolInitData::doc, FindIndexJ(), VPiece::GetPath(), VPiecePath::indexOfNode(), UnionToolInitData::piece1_Index, UnionToolInitData::piece2_Index, VPiecePath::RemoveEdge(), SaveNodesChildren(), SCASSERT, and VPiece::SetPath().
Referenced by createUnion().
FindIndexJ()
void QT_WARNING_POP::FindIndexJ (qint32 piece2Points, const VPiecePath & piece2Path, quint32 piece2_Index, qint32 & j)
Definition at line 666 of file union_tool.cpp.
References VPiecePath::CountNodes(), VPieceNode::GetId(), VPiecePath::indexOfNode(), VPiecePath::NodeOnEdge(), VPiecePath::RemoveEdge(), and SCASSERT.
Referenced by CreateUnitedNodes(), and UpdateUnitedNodes().
getAnchorChildren()
QVector<quint32> QT_WARNING_POP::getAnchorChildren (VAbstractPattern * doc, quint32 id)
Definition at line 801 of file union_tool.cpp.
References GetChildren(), and PatternPieceTool::TagAnchors.
Referenced by updateUnionAnchors().
getBlockName()
QString QT_WARNING_POP::getBlockName (VAbstractPattern * doc, quint32 piece1_Id, quint32 piece2_Id)
Definition at line 265 of file union_tool.cpp.
References VAbstractPattern::AttrName, VDomDocument::elementById(), VAbstractPattern::TagDraftBlock, and VAbstractPattern::TagPiece.
Referenced by UnionTool::AddToModeling(), and createUnion().
GetChildren()
QVector<quint32> QT_WARNING_POP::GetChildren (VAbstractPattern * doc, quint32 id, const QString & tagName)
Definition at line 749 of file union_tool.cpp.
References VDomDocument::elementById(), UnionTool::TagChild, UnionTool::TagChildren, and VAbstractPattern::TagTools.
Referenced by getAnchorChildren(), GetCSAChildren(), GetInternalPathsChildren(), and GetNodesChildren().
GetCSAChildren()
QVector<quint32> QT_WARNING_POP::GetCSAChildren (VAbstractPattern * doc, quint32 id)
Definition at line 789 of file union_tool.cpp.
References GetChildren(), and PatternPieceTool::TagCSA.
Referenced by updateUnionCSA().
GetInternalPathsChildren()
QVector<quint32> QT_WARNING_POP::GetInternalPathsChildren (VAbstractPattern * doc, quint32 id)
Definition at line 795 of file union_tool.cpp.
References GetChildren(), and PatternPieceTool::TagIPaths.
Referenced by updateUnionInternalPaths().
GetNodesChildren()
QVector<quint32> QT_WARNING_POP::GetNodesChildren (VAbstractPattern * doc, quint32 id)
Definition at line 783 of file union_tool.cpp.
References GetChildren(), and VAbstractPattern::TagNodes.
Referenced by UpdateUnitedNodes().
GetPiece1MainPath()
VPiecePath QT_WARNING_POP::GetPiece1MainPath (VAbstractPattern * doc, quint32 id)
Definition at line 160 of file union_tool.cpp.
References GetPiecePath().
Referenced by unitePieces(), and UpdateUnitedNodes().
GetPiece2Anchors()
QVector<quint32> QT_WARNING_POP::GetPiece2Anchors (VAbstractPattern * doc, quint32 id)
Definition at line 234 of file union_tool.cpp.
References VDomDocument::elementById(), VAbstractPattern::ParsePieceAnchors(), PatternPieceTool::TagAnchors, VAbstractPattern::TagTools, and UnionTool::TagUnionPiece.
Referenced by updateUnion().
GetPiece2CSAPaths()
QVector<CustomSARecord> QT_WARNING_POP::GetPiece2CSAPaths (VAbstractPattern * doc, quint32 id)
Definition at line 172 of file union_tool.cpp.
References VDomDocument::elementById(), VAbstractPattern::ParsePieceCSARecords(), PatternPieceTool::TagCSA, VAbstractPattern::TagTools, and UnionTool::TagUnionPiece.
Referenced by updateUnion().
GetPiece2InternalPaths()
QVector<quint32> QT_WARNING_POP::GetPiece2InternalPaths (VAbstractPattern * doc, quint32 id)
Definition at line 203 of file union_tool.cpp.
References VDomDocument::elementById(), VAbstractPattern::ParsePieceInternalPaths(), PatternPieceTool::TagIPaths, VAbstractPattern::TagTools, and UnionTool::TagUnionPiece.
Referenced by updateUnion().
GetPiece2MainPath()
VPiecePath QT_WARNING_POP::GetPiece2MainPath (VAbstractPattern * doc, quint32 id)
Definition at line 166 of file union_tool.cpp.
References GetPiecePath().
Referenced by unitePieces(), and UpdateUnitedNodes().
GetPiecePath()
VPiecePath QT_WARNING_POP::GetPiecePath (int piece, VAbstractPattern * doc, quint32 id)
Definition at line 129 of file union_tool.cpp.
References VDomDocument::elementById(), VAbstractPattern::ParsePieceNodes(), VAbstractPattern::TagNodes, VAbstractPattern::TagTools, and UnionTool::TagUnionPiece.
Referenced by VToolInternalPath::decrementReferens(), GetPiece1MainPath(), GetPiece2MainPath(), VToolInternalPath::incrementReferens(), and VToolInternalPath::VToolInternalPath().
GetTagChildren()
QDomElement QT_WARNING_POP::GetTagChildren (VAbstractPattern * doc, quint32 id)
Definition at line 688 of file union_tool.cpp.
References VDomDocument::elementById(), UnionTool::TagChildren, and VAbstractPattern::TagTools.
Referenced by SaveChildren().
PointsOnEdge()
void QT_WARNING_POP::PointsOnEdge (const VPiecePath & path, quint32 index, VPointF & p1, VPointF & p2, VContainer * data)
Definition at line 352 of file union_tool.cpp.
References VContainer::GeometricObject(), VPieceNode::GetId(), and VPiecePath::NodeOnEdge().
Referenced by UnionInitParameters().
SaveAnchorsChildren()
void QT_WARNING_POP::SaveAnchorsChildren (VAbstractPattern * doc, quint32 id, const QVector< quint32 > & children)
Definition at line 743 of file union_tool.cpp.
References SaveChildren(), and PatternPieceTool::TagAnchors.
Referenced by createUnitedAnchors().
SaveChildren()
void QT_WARNING_POP::SaveChildren (VAbstractPattern * doc, quint32 id, QDomElement section, const QVector< quint32 > & children)
Definition at line 709 of file union_tool.cpp.
References GetTagChildren(), and UnionTool::TagChild.
Referenced by SaveAnchorsChildren(), SaveCSAChildren(), SaveInternalPathsChildren(), and SaveNodesChildren().
SaveCSAChildren()
void QT_WARNING_POP::SaveCSAChildren (VAbstractPattern * doc, quint32 id, const QVector< quint32 > & children)
Definition at line 731 of file union_tool.cpp.
References SaveChildren(), and PatternPieceTool::TagCSA.
Referenced by CreateUnitedCSA().
SaveInternalPathsChildren()
void QT_WARNING_POP::SaveInternalPathsChildren (VAbstractPattern * doc, quint32 id, const QVector< quint32 > & children)
Definition at line 737 of file union_tool.cpp.
References SaveChildren(), and PatternPieceTool::TagIPaths.
Referenced by CreateUnitedInternalPaths().
SaveNodesChildren()
void QT_WARNING_POP::SaveNodesChildren (VAbstractPattern * doc, quint32 id, const QVector< quint32 > & children)
Definition at line 725 of file union_tool.cpp.
References SaveChildren(), and VAbstractPattern::TagNodes.
Referenced by CreateUnitedNodes().
TakeNextId()
quint32 QT_WARNING_POP::TakeNextId (QVector< quint32 > & children)
Definition at line 807 of file union_tool.cpp.
References NULL_ID.
Referenced by createUnionPaths(), UpdateNodeArc(), UpdateNodeElArc(), UpdateNodePoint(), UpdateNodeSpline(), UpdateNodeSplinePath(), and updateUnionAnchors().
UnionInitParameters()
void QT_WARNING_POP::UnionInitParameters (const UnionToolInitData & initData, const VPiecePath & piece1Path, const VPiecePath & piece2Path, VPieceNode & piece1_Pt1, qreal & dx, qreal & dy, qreal & angle)
Definition at line 362 of file union_tool.cpp.
References UnionToolInitData::data, VPiecePath::NodeOnEdge(), UnionToolInitData::piece1_Index, UnionToolInitData::piece2_Index, PointsOnEdge(), VPointF::setX(), VPointF::setY(), VPointF::x(), and VPointF::y().
Referenced by unitePieces().
unitePieces()
void QT_WARNING_POP::unitePieces (quint32 id, const UnionToolInitData & initData)
Definition at line 1394 of file union_tool.cpp.
References createUnion(), UnionToolInitData::data, UnionToolInitData::doc, FromGui, VPieceNode::GetId(), VPiece::GetPath(), VContainer::GetPiece(), GetPiece1MainPath(), GetPiece2MainPath(), UnionToolInitData::piece1_Id, UnionToolInitData::piece2_Id, UnionToolInitData::typeCreation, UnionInitParameters(), and updateUnion().
Referenced by UnionTool::Create().
UpdateNodeArc()
void QT_WARNING_POP::UpdateNodeArc (VContainer * data, const VPieceNode & node, QVector< quint32 > & children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 835 of file union_tool.cpp.
References BiasRotatePoint(), VContainer::GeometricObject(), VPieceNode::GetId(), Modeling, NULL_ID, TakeNextId(), and VContainer::UpdateGObject().
Referenced by UpdatePathNode().
UpdateNodeElArc()
void QT_WARNING_POP::UpdateNodeElArc (VContainer * data, const VPieceNode & node, QVector< quint32 > & children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 862 of file union_tool.cpp.
References BiasRotatePoint(), VContainer::GeometricObject(), VPieceNode::GetId(), Modeling, NULL_ID, TakeNextId(), and VContainer::UpdateGObject().
Referenced by UpdatePathNode().
UpdateNodePoint()
void QT_WARNING_POP::UpdateNodePoint (VContainer * data, const VPieceNode & node, QVector< quint32 > & children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 822 of file union_tool.cpp.
References BiasRotatePoint(), VContainer::GeometricObject(), VPieceNode::GetId(), Modeling, NULL_ID, TakeNextId(), and VContainer::UpdateGObject().
Referenced by UpdatePathNode().
UpdateNodeSpline()
void QT_WARNING_POP::UpdateNodeSpline (VContainer * data, const VPieceNode & node, QVector< quint32 > & children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 891 of file union_tool.cpp.
References BiasRotatePoint(), VContainer::GeometricObject(), VPieceNode::GetId(), Modeling, NULL_ID, TakeNextId(), and VContainer::UpdateGObject().
Referenced by UpdatePathNode().
UpdateNodeSplinePath()
void QT_WARNING_POP::UpdateNodeSplinePath (VContainer * data, const VPieceNode & node, QVector< quint32 > & children, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 918 of file union_tool.cpp.
References BiasRotatePoint(), VContainer::GeometricObject(), VSpline::GetC1Length(), VSpline::GetC1LengthFormula(), VSpline::GetC2Length(), VSpline::GetC2LengthFormula(), VSpline::GetEndAngle(), VSpline::GetEndAngleFormula(), VPieceNode::GetId(), VSpline::GetP1(), VSpline::GetP2(), VSpline::GetP3(), VSpline::GetP4(), VSpline::GetStartAngle(), VSpline::GetStartAngleFormula(), Modeling, NULL_ID, SCASSERT, TakeNextId(), and VContainer::UpdateGObject().
Referenced by UpdatePathNode().
UpdatePathNode()
void QT_WARNING_POP::UpdatePathNode (VContainer * data, const VPieceNode & node, QVector< quint32 > & children, qreal dx = 0, qreal dy = 0, quint32 pRotate = NULL_ID, qreal angle = 0)
UpdateNodes update nodes of union.
Parameters
data container with variables.
node piece's node.
children list ids of all children.
dx bias node x axis.
dy bias node y axis.
pRotate point rotation.
angle angle rotation.
Definition at line 986 of file union_tool.cpp.
References VPieceNode::GetTypeTool(), NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, UpdateNodeArc(), UpdateNodeElArc(), UpdateNodePoint(), UpdateNodeSpline(), and UpdateNodeSplinePath().
Referenced by createUnionPaths(), and UpdateUnitedNodes().
updateUnion()
void QT_WARNING_POP::updateUnion (quint32 id, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1384 of file union_tool.cpp.
References UnionToolInitData::doc, GetPiece2Anchors(), GetPiece2CSAPaths(), GetPiece2InternalPaths(), updateUnionAnchors(), updateUnionCSA(), updateUnionInternalPaths(), and UpdateUnitedNodes().
Referenced by unitePieces().
updateUnionAnchors()
void QT_WARNING_POP::updateUnionAnchors (quint32 id, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle, const QVector< quint32 > & records)
Definition at line 1284 of file union_tool.cpp.
References BiasRotatePoint(), UnionToolInitData::data, UnionToolInitData::doc, VContainer::GeometricObject(), getAnchorChildren(), Modeling, NULL_ID, TakeNextId(), and VContainer::UpdateGObject().
Referenced by updateUnion().
updateUnionCSA()
void QT_WARNING_POP::updateUnionCSA (quint32 id, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle, const QVector< CustomSARecord > & records)
Definition at line 1265 of file union_tool.cpp.
References createUnionPaths(), UnionToolInitData::doc, and GetCSAChildren().
Referenced by updateUnion().
updateUnionInternalPaths()
void QT_WARNING_POP::updateUnionInternalPaths (quint32 id, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle, const QVector< quint32 > & records)
Definition at line 1277 of file union_tool.cpp.
References createUnionPaths(), UnionToolInitData::doc, and GetInternalPathsChildren().
Referenced by updateUnion().
UpdateUnitedNodes()
void QT_WARNING_POP::UpdateUnitedNodes (quint32 id, const UnionToolInitData & initData, qreal dx, qreal dy, quint32 pRotate, qreal angle)
Definition at line 1165 of file union_tool.cpp.
References VPiecePath::at(), CONVERTER_VERSION_CHECK, VPiecePath::CountNodes(), UnionToolInitData::data, UnionToolInitData::doc, FindIndexJ(), GetNodesChildren(), GetPiece1MainPath(), GetPiece2MainPath(), VPiecePath::indexOfNode(), VPatternConverter::PatternMinVer, UnionToolInitData::piece1_Index, UnionToolInitData::piece2_Index, VPiecePath::RemoveEdge(), and UpdatePathNode().
Referenced by updateUnion().