Seamly2D: anonymous_namespace{vsettings.cpp} Namespace Reference
anonymous_namespace{vsettings.cpp} Namespace Reference
Variables
const QString settingConfigurationLabelLanguage = QStringLiteral("configuration/label_language")
const QString settingPathsPattern = QStringLiteral("paths/pattern")
const QString settingPathsLayout = QStringLiteral("paths/layout")
const QString settingPatternGraphicalOutput = QStringLiteral("pattern/graphicalOutput")
const QString settingCommunityServer = QStringLiteral("community/server")
const QString settingCommunityServerSecure = QStringLiteral("community/serverSecure")
const QString settingCommunityUseProxy = QStringLiteral("community/useProxy")
const QString settingCommunityProxyAddress = QStringLiteral("community/proxyAddress")
const QString settingCommunityProxyPort = QStringLiteral("community/proxyPort")
const QString settingCommunityProxyUser = QStringLiteral("community/proxyUser")
const QString settingCommunityProxyPass = QStringLiteral("community/proxyPass")
const QString settingCommunityUsername = QStringLiteral("community/username")
const QString settingCommunitySavePassword = QStringLiteral("community/savePassword")
const QString settingCommunityUserPassword = QStringLiteral("community/userpassword")
const QString settingLayoutWidth = QStringLiteral("layout/width")
const QString settingLayoutSorting = QStringLiteral("layout/sorting")
const QString settingLayoutPaperHeight = QStringLiteral("layout/paperHeight")
const QString settingLayoutPaperWidth = QStringLiteral("layout/paperWidth")
const QString settingLayoutShift = QStringLiteral("layout/shift")
const QString settingLayoutRotate = QStringLiteral("layout/Rotate")
const QString settingLayoutRotationIncrease = QStringLiteral("layout/rotationIncrease")
const QString settingLayoutAutoCrop = QStringLiteral("layout/autoCrop")
const QString settingLayoutSaveLength = QStringLiteral("layout/saveLength")
const QString settingLayoutUnitePages = QStringLiteral("layout/unitePages")
const QString settingFields = QStringLiteral("layout/fields")
const QString settingIgnoreFields = QStringLiteral("layout/ignoreFields")
const QString settingStripOptimization = QStringLiteral("layout/stripOptimization")
const QString settingMultiplier = QStringLiteral("layout/multiplier")
const QString settingTextAsPaths = QStringLiteral("layout/textAsPaths")
const QString settingTiledPDFMargins = QStringLiteral("tiledPDF/margins")
const QString settingTiledPDFPaperHeight = QStringLiteral("tiledPDF/paperHeight")
const QString settingTiledPDFPaperWidth = QStringLiteral("tiledPDF/paperWidth")
const QString settingTiledPDFOrientation = QStringLiteral("tiledPDF/orientation")
Variable Documentation
settingCommunityProxyAddress
const QString anonymous_namespace{vsettings.cpp}::settingCommunityProxyAddress = QStringLiteral("community/proxyAddress")
Definition at line 83 of file vsettings.cpp.
Referenced by VSettings::GetProxyAddress(), and VSettings::SetProxyAddress().
settingCommunityProxyPass
const QString anonymous_namespace{vsettings.cpp}::settingCommunityProxyPass = QStringLiteral("community/proxyPass")
Definition at line 86 of file vsettings.cpp.
Referenced by VSettings::GetProxyPass(), and VSettings::SetProxyPass().
settingCommunityProxyPort
const QString anonymous_namespace{vsettings.cpp}::settingCommunityProxyPort = QStringLiteral("community/proxyPort")
Definition at line 84 of file vsettings.cpp.
Referenced by VSettings::GetProxyPort(), and VSettings::SetProxyPort().
settingCommunityProxyUser
const QString anonymous_namespace{vsettings.cpp}::settingCommunityProxyUser = QStringLiteral("community/proxyUser")
Definition at line 85 of file vsettings.cpp.
Referenced by VSettings::GetProxyUser(), and VSettings::SetProxyUser().
settingCommunitySavePassword
const QString anonymous_namespace{vsettings.cpp}::settingCommunitySavePassword = QStringLiteral("community/savePassword")
Definition at line 88 of file vsettings.cpp.
Referenced by VSettings::GetSavePassword(), and VSettings::SetSavePassword().
settingCommunityServer
const QString anonymous_namespace{vsettings.cpp}::settingCommunityServer = QStringLiteral("community/server")
Definition at line 80 of file vsettings.cpp.
Referenced by VSettings::GetServer(), and VSettings::SetServer().
settingCommunityServerSecure
const QString anonymous_namespace{vsettings.cpp}::settingCommunityServerSecure = QStringLiteral("community/serverSecure")
Definition at line 81 of file vsettings.cpp.
Referenced by VSettings::GetServerSecure(), and VSettings::SetServerSecure().
settingCommunityUseProxy
const QString anonymous_namespace{vsettings.cpp}::settingCommunityUseProxy = QStringLiteral("community/useProxy")
Definition at line 82 of file vsettings.cpp.
Referenced by VSettings::GetProxy(), and VSettings::SetProxy().
settingCommunityUsername
const QString anonymous_namespace{vsettings.cpp}::settingCommunityUsername = QStringLiteral("community/username")
Definition at line 87 of file vsettings.cpp.
Referenced by VSettings::GetUsername(), and VSettings::SetUsername().
settingCommunityUserPassword
const QString anonymous_namespace{vsettings.cpp}::settingCommunityUserPassword = QStringLiteral("community/userpassword")
Definition at line 89 of file vsettings.cpp.
Referenced by VSettings::GetUserPassword(), and VSettings::SetUserPassword().
settingConfigurationLabelLanguage
const QString anonymous_namespace{vsettings.cpp}::settingConfigurationLabelLanguage = QStringLiteral("configuration/label_language")
Definition at line 73 of file vsettings.cpp.
Referenced by VSettings::GetLabelLanguage(), and VSettings::SetLabelLanguage().
settingFields
const QString anonymous_namespace{vsettings.cpp}::settingFields = QStringLiteral("layout/fields")
Definition at line 101 of file vsettings.cpp.
Referenced by VSettings::GetFields(), and VSettings::SetFields().
settingIgnoreFields
const QString anonymous_namespace{vsettings.cpp}::settingIgnoreFields = QStringLiteral("layout/ignoreFields")
Definition at line 102 of file vsettings.cpp.
Referenced by VSettings::GetIgnoreAllFields(), and VSettings::SetIgnoreAllFields().
settingLayoutAutoCrop
const QString anonymous_namespace{vsettings.cpp}::settingLayoutAutoCrop = QStringLiteral("layout/autoCrop")
Definition at line 98 of file vsettings.cpp.
Referenced by VSettings::GetLayoutAutoCrop(), and VSettings::SetLayoutAutoCrop().
settingLayoutPaperHeight
const QString anonymous_namespace{vsettings.cpp}::settingLayoutPaperHeight = QStringLiteral("layout/paperHeight")
Definition at line 93 of file vsettings.cpp.
Referenced by VSettings::GetLayoutPaperHeight(), and VSettings::SetLayoutPaperHeight().
settingLayoutPaperWidth
const QString anonymous_namespace{vsettings.cpp}::settingLayoutPaperWidth = QStringLiteral("layout/paperWidth")
Definition at line 94 of file vsettings.cpp.
Referenced by VSettings::GetLayoutPaperWidth(), and VSettings::SetLayoutPaperWidth().
settingLayoutRotate
const QString anonymous_namespace{vsettings.cpp}::settingLayoutRotate = QStringLiteral("layout/Rotate")
Definition at line 96 of file vsettings.cpp.
Referenced by VSettings::GetLayoutRotate(), and VSettings::SetLayoutRotate().
settingLayoutRotationIncrease
const QString anonymous_namespace{vsettings.cpp}::settingLayoutRotationIncrease = QStringLiteral("layout/rotationIncrease")
Definition at line 97 of file vsettings.cpp.
Referenced by VSettings::GetLayoutRotationIncrease(), and VSettings::SetLayoutRotationIncrease().
settingLayoutSaveLength
const QString anonymous_namespace{vsettings.cpp}::settingLayoutSaveLength = QStringLiteral("layout/saveLength")
Definition at line 99 of file vsettings.cpp.
Referenced by VSettings::GetLayoutSaveLength(), and VSettings::SetLayoutSaveLength().
settingLayoutShift
const QString anonymous_namespace{vsettings.cpp}::settingLayoutShift = QStringLiteral("layout/shift")
Definition at line 95 of file vsettings.cpp.
Referenced by VSettings::GetLayoutShift(), and VSettings::SetLayoutShift().
settingLayoutSorting
const QString anonymous_namespace{vsettings.cpp}::settingLayoutSorting = QStringLiteral("layout/sorting")
Definition at line 92 of file vsettings.cpp.
Referenced by VSettings::GetLayoutGroup(), and VSettings::SetLayoutGroup().
settingLayoutUnitePages
const QString anonymous_namespace{vsettings.cpp}::settingLayoutUnitePages = QStringLiteral("layout/unitePages")
Definition at line 100 of file vsettings.cpp.
Referenced by VSettings::GetLayoutUnitePages(), and VSettings::SetLayoutUnitePages().
settingLayoutWidth
const QString anonymous_namespace{vsettings.cpp}::settingLayoutWidth = QStringLiteral("layout/width")
Definition at line 91 of file vsettings.cpp.
Referenced by VSettings::GetLayoutWidth(), and VSettings::SetLayoutWidth().
settingMultiplier
const QString anonymous_namespace{vsettings.cpp}::settingMultiplier = QStringLiteral("layout/multiplier")
Definition at line 104 of file vsettings.cpp.
Referenced by VSettings::GetMultiplier(), and VSettings::SetMultiplier().
settingPathsLayout
const QString anonymous_namespace{vsettings.cpp}::settingPathsLayout = QStringLiteral("paths/layout")
Definition at line 76 of file vsettings.cpp.
Referenced by VSettings::getLayoutPath(), and VSettings::SetPathLayout().
settingPathsPattern
const QString anonymous_namespace{vsettings.cpp}::settingPathsPattern = QStringLiteral("paths/pattern")
Definition at line 75 of file vsettings.cpp.
Referenced by VSettings::getPatternPath(), and VSettings::SetPathPattern().
settingPatternGraphicalOutput
const QString anonymous_namespace{vsettings.cpp}::settingPatternGraphicalOutput = QStringLiteral("pattern/graphicalOutput")
Definition at line 78 of file vsettings.cpp.
Referenced by VSettings::GetGraphicalOutput(), and VSettings::SetGraphicalOutput().
settingStripOptimization
const QString anonymous_namespace{vsettings.cpp}::settingStripOptimization = QStringLiteral("layout/stripOptimization")
Definition at line 103 of file vsettings.cpp.
Referenced by VSettings::GetStripOptimization(), and VSettings::SetStripOptimization().
settingTextAsPaths
const QString anonymous_namespace{vsettings.cpp}::settingTextAsPaths = QStringLiteral("layout/textAsPaths")
Definition at line 105 of file vsettings.cpp.
Referenced by VSettings::GetTextAsPaths(), and VSettings::setTextAsPaths().
settingTiledPDFMargins
const QString anonymous_namespace{vsettings.cpp}::settingTiledPDFMargins = QStringLiteral("tiledPDF/margins")
Definition at line 107 of file vsettings.cpp.
Referenced by VSettings::GetTiledPDFMargins(), and VSettings::setTiledPDFMargins().
settingTiledPDFOrientation
const QString anonymous_namespace{vsettings.cpp}::settingTiledPDFOrientation = QStringLiteral("tiledPDF/orientation")
Definition at line 110 of file vsettings.cpp.
Referenced by VSettings::getTiledPDFOrientation(), and VSettings::setTiledPDFOrientation().
settingTiledPDFPaperHeight
const QString anonymous_namespace{vsettings.cpp}::settingTiledPDFPaperHeight = QStringLiteral("tiledPDF/paperHeight")
Definition at line 108 of file vsettings.cpp.
Referenced by VSettings::getTiledPDFPaperHeight(), and VSettings::setTiledPDFPaperHeight().
settingTiledPDFPaperWidth
const QString anonymous_namespace{vsettings.cpp}::settingTiledPDFPaperWidth = QStringLiteral("tiledPDF/paperWidth")
Definition at line 109 of file vsettings.cpp.
Referenced by VSettings::getTiledPDFPaperWidth(), and VSettings::setTiledPDFPaperWidth().