Seamly2D: VisToolPointOfContact Class Reference
VisToolPointOfContact Class Reference
#include <vistoolpointofcontact.h>
Public Types
enum { Type = UserType + static_cast<int>(Vis::ToolPointOfContact) }
Public Types inherited from VisLine
enum { Type = UserType + static_cast<int>(Vis::Line) }
Public Types inherited from VScaledLine
enum { Type = UserType + static_cast<int>(Vis::ScaledLine) }
Public Member Functions
VisToolPointOfContact (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisToolPointOfContact ()=default
virtual void RefreshGeometry () Q_DECL_OVERRIDE
void setLineP2Id (const quint32 &value)
void setRadiusId (const quint32 &value)
void setRadius (const QString &expression)
virtual int type () const Q_DECL_OVERRIDE
Public Member Functions inherited from VisLine
VisLine (const VContainer *data, QGraphicsItem *parent=nullptr)
virtual ~VisLine ()=default
Public Member Functions inherited from Visualization
Visualization (const VContainer *data)
virtual ~Visualization () Q_DECL_EQ_DEFAULT
void setObject1Id (const quint32 &value)
void setLineStyle (const Qt::PenStyle &value)
void setLineWeight (const QString &value)
void setScenePos (const QPointF &value)
virtual void VisualMode (const quint32 &pointId)
void setMainColor (const QColor &value)
const VContainer * getData () const
void setData (const VContainer *data)
Mode GetMode () const
void SetMode (const Mode &value)
QString CurrentToolTip () const
Public Member Functions inherited from VScaledLine
VScaledLine (QGraphicsItem *parent=nullptr)
VScaledLine (const QLineF &line, QGraphicsItem *parent=nullptr)
virtual ~VScaledLine ()=default
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) Q_DECL_OVERRIDE
qreal GetBasicWidth () const
void setBasicWidth (const qreal &value)
Private Attributes
quint32 lineP2Id
quint32 radiusId
VScaledEllipse * point
VScaledEllipse * lineP1
VScaledEllipse * lineP2
VScaledEllipse * arc_point
VScaledEllipse * circle
qreal radius
Additional Inherited Members
Public Slots inherited from Visualization
void mousePos (const QPointF &scenePos)
Signals inherited from Visualization
void ToolTip (const QString &toolTip)
Static Public Member Functions inherited from VisLine
static qreal CorrectAngle (const qreal &angle)
Static Public Member Functions inherited from Visualization
static qreal FindLength (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
static qreal FindVal (const QString &expression, const QHash< QString, QSharedPointer< VInternalVariable > > *vars)
Protected Member Functions inherited from VisLine
QPointF Ray (const QPointF &firstPoint, const qreal &angle) const
QPointF Ray (const QPointF &firstPoint) const
QLineF Axis (const QPointF &p, const qreal &angle) const
QLineF Axis (const QPointF &p1, const QPointF &p2) const
virtual void initPen () Q_DECL_OVERRIDE
virtual void AddOnScene () Q_DECL_OVERRIDE
void DrawRay (VScaledLine *lineItem, const QPointF &p, const QPointF &pTangent, const QColor &color, Qt::PenStyle style)
Protected Member Functions inherited from Visualization
VScaledEllipse * InitPoint (const QColor &color, QGraphicsItem *parent, qreal z=0) const
void DrawPoint (QGraphicsEllipseItem *point, const QPointF &pos, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
virtual void DrawLine (VScaledLine *lineItem, const QLineF &line, const QColor &color, const qreal &lineWeight, Qt::PenStyle style=Qt::SolidLine)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void DrawPath (VCurvePathItem *pathItem, const QPainterPath &path, const QVector< DirectionArrow > &directionArrows, const QColor &color, Qt::PenStyle style=Qt::SolidLine, const qreal &weight=0.35, Qt::PenCapStyle cap=Qt::SquareCap)
void drawArrowedLine (ArrowedLineItem *item, const QLineF &line, const QColor &color, Qt::PenStyle style=Qt::SolidLine)
void drawArrow (const QLineF &axis, QPainterPath &path, const qreal &arrow_size)
template<typename Item >
void addItem (Item *item)
template<class Item >
Item * InitItem (const QColor &color, QGraphicsItem *parent)
Static Protected Member Functions inherited from Visualization
static VScaledEllipse * GetPointItem (QVector< VScaledEllipse * > &points, quint32 i, const QColor &color, QGraphicsItem *parent)
Protected Attributes inherited from Visualization
const VContainer * data
QPointF scenePos
QColor mainColor
QColor supportColor
Qt::PenStyle lineStyle
qreal lineWeight
quint32 object1Id
QString toolTip
Mode mode
Detailed Description
Definition at line 65 of file vistoolpointofcontact.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 77 of file vistoolpointofcontact.h.
Constructor & Destructor Documentation
VisToolPointOfContact()
VisToolPointOfContact::VisToolPointOfContact (const VContainer * data, QGraphicsItem * parent = nullptr) explicit
Definition at line 69 of file vistoolpointofcontact.cpp.
References arc_point, circle, Visualization::InitPoint(), lineP1, lineP2, Visualization::mainColor, point, and Visualization::supportColor.
~VisToolPointOfContact()
virtual VisToolPointOfContact::~VisToolPointOfContact () virtual default
Member Function Documentation
RefreshGeometry()
void VisToolPointOfContact::RefreshGeometry () virtual
Implements Visualization.
Definition at line 82 of file vistoolpointofcontact.cpp.
References arc_point, circle, Visualization::data, Visualization::DrawLine(), Visualization::DrawPoint(), VToolPointOfContact::FindPoint(), VContainer::GeometricObject(), lineP1, lineP2, lineP2Id, Visualization::lineWeight, Visualization::mainColor, NULL_ID, Visualization::object1Id, point, PointRect(), radius, radiusId, Visualization::scenePos, and Visualization::supportColor.
Referenced by DialogPointOfContact::ChosenObject(), DialogPointOfContact::SaveData(), and VToolPointOfContact::SetVisualization().
setLineP2Id()
void VisToolPointOfContact::setLineP2Id (const quint32 & value)
Definition at line 125 of file vistoolpointofcontact.cpp.
References lineP2Id.
Referenced by DialogPointOfContact::ChosenObject(), DialogPointOfContact::SaveData(), DialogPointOfContact::SetSecondPoint(), and VToolPointOfContact::SetVisualization().
setRadius()
void VisToolPointOfContact::setRadius (const QString & expression)
Definition at line 137 of file vistoolpointofcontact.cpp.
References Visualization::data, Visualization::FindLength(), and radius.
Referenced by DialogPointOfContact::SaveData(), DialogPointOfContact::setRadius(), and VToolPointOfContact::SetVisualization().
setRadiusId()
void VisToolPointOfContact::setRadiusId (const quint32 & value)
Definition at line 131 of file vistoolpointofcontact.cpp.
References radiusId.
Referenced by DialogPointOfContact::ChosenObject(), DialogPointOfContact::SaveData(), DialogPointOfContact::setCenter(), and VToolPointOfContact::SetVisualization().
type()
virtual int VisToolPointOfContact::type () const inline virtual
Reimplemented from VisLine.
Definition at line 76 of file vistoolpointofcontact.h.
References Type.
Member Data Documentation
arc_point
VScaledEllipse* VisToolPointOfContact::arc_point private
Definition at line 85 of file vistoolpointofcontact.h.
Referenced by RefreshGeometry(), and VisToolPointOfContact().
circle
VScaledEllipse* VisToolPointOfContact::circle private
Definition at line 86 of file vistoolpointofcontact.h.
Referenced by RefreshGeometry(), and VisToolPointOfContact().
lineP1
VScaledEllipse* VisToolPointOfContact::lineP1 private
Definition at line 83 of file vistoolpointofcontact.h.
Referenced by RefreshGeometry(), and VisToolPointOfContact().
lineP2
VScaledEllipse* VisToolPointOfContact::lineP2 private
Definition at line 84 of file vistoolpointofcontact.h.
Referenced by RefreshGeometry(), and VisToolPointOfContact().
lineP2Id
quint32 VisToolPointOfContact::lineP2Id private
Definition at line 80 of file vistoolpointofcontact.h.
Referenced by RefreshGeometry(), and setLineP2Id().
point
VScaledEllipse* VisToolPointOfContact::point private
Definition at line 82 of file vistoolpointofcontact.h.
Referenced by RefreshGeometry(), and VisToolPointOfContact().
radius
qreal VisToolPointOfContact::radius private
Definition at line 87 of file vistoolpointofcontact.h.
Referenced by RefreshGeometry(), and setRadius().
radiusId
quint32 VisToolPointOfContact::radiusId private
Definition at line 81 of file vistoolpointofcontact.h.
Referenced by RefreshGeometry(), and setRadiusId().
The documentation for this class was generated from the following files:
src/libs/vtools/visualization/line/vistoolpointofcontact.h
src/libs/vtools/visualization/line/vistoolpointofcontact.cpp