Seamly2D: TST_QmuParserErrorMsg Class Reference
TST_QmuParserErrorMsg Class Reference
#include <tst_qmuparsererrormsg.h>
Public Member Functions
TST_QmuParserErrorMsg (const QString &locale, QObject *parent=nullptr)
virtual ~TST_QmuParserErrorMsg () Q_DECL_OVERRIDE
Public Member Functions inherited from AbstractTest
AbstractTest (QObject *parent=nullptr)
Private Slots
void initTestCase ()
void TestEErrorCodes_data ()
void TestEErrorCodes ()
void cleanupTestCase ()
Private Member Functions
void AddCase (int code, bool tok, bool pos)
int loadTranslations (const QString &checkedLocale)
void RemoveTranslation ()
Private Attributes
QString m_locale
QPointer< QTranslator > appTranslator
qmu::QmuParserErrorMsg * msg
Additional Inherited Members
Protected Member Functions inherited from AbstractTest
void Comparison (const QVector< QPointF > &ekv, const QVector< QPointF > &ekvOrig) const
void Comparison (const QPointF &result, const QPointF &expected, qreal testAccuracy) const
QString Seamly2DPath () const
QString SeamlyMePath () const
QString TranslationsPath () const
int Run (int exit, const QString &program, const QStringList &arguments, QString &error, int msecs=120000)
bool CopyRecursively (const QString &srcFilePath, const QString &tgtFilePath) const
Detailed Description
Definition at line 61 of file tst_qmuparsererrormsg.h.
Constructor & Destructor Documentation
TST_QmuParserErrorMsg()
TST_QmuParserErrorMsg::TST_QmuParserErrorMsg (const QString & locale, QObject * parent = nullptr) explicit
Definition at line 59 of file tst_qmuparsererrormsg.cpp.
~TST_QmuParserErrorMsg()
TST_QmuParserErrorMsg::~TST_QmuParserErrorMsg () virtual
Definition at line 68 of file tst_qmuparsererrormsg.cpp.
References appTranslator, and msg.
Member Function Documentation
AddCase()
void TST_QmuParserErrorMsg::AddCase (int code, bool tok, bool pos) private
Definition at line 166 of file tst_qmuparsererrormsg.cpp.
References m_locale.
Referenced by TestEErrorCodes_data().
cleanupTestCase
void TST_QmuParserErrorMsg::cleanupTestCase () private slot
Definition at line 160 of file tst_qmuparsererrormsg.cpp.
References RemoveTranslation().
initTestCase
void TST_QmuParserErrorMsg::initTestCase () private slot
Definition at line 75 of file tst_qmuparsererrormsg.cpp.
References loadTranslations(), m_locale, NoError, SupportedLocales(), and AbstractTest::TranslationsPath().
loadTranslations()
int TST_QmuParserErrorMsg::loadTranslations (const QString & checkedLocale) private
Definition at line 173 of file tst_qmuparsererrormsg.cpp.
References appTranslator, ErrorInstall, ErrorLoad, ErrorSize, msg, NoError, and AbstractTest::TranslationsPath().
Referenced by initTestCase().
RemoveTranslation()
void TST_QmuParserErrorMsg::RemoveTranslation () private
Definition at line 224 of file tst_qmuparsererrormsg.cpp.
References appTranslator, and m_locale.
Referenced by cleanupTestCase().
TestEErrorCodes
void TST_QmuParserErrorMsg::TestEErrorCodes () private slot
Definition at line 146 of file tst_qmuparsererrormsg.cpp.
TestEErrorCodes_data
void TST_QmuParserErrorMsg::TestEErrorCodes_data () private slot
Definition at line 101 of file tst_qmuparsererrormsg.cpp.
References AddCase(), qmu::ecBUILTIN_OVERLOAD, qmu::ecDIV_BY_ZERO, qmu::ecDOMAIN_ERROR, qmu::ecEMPTY_EXPRESSION, qmu::ecGENERIC, qmu::ecINTERNAL_ERROR, qmu::ecINVALID_BINOP_IDENT, qmu::ecINVALID_FUN_PTR, qmu::ecINVALID_INFIX_IDENT, qmu::ecINVALID_NAME, qmu::ecINVALID_POSTFIX_IDENT, qmu::ecINVALID_VAR_PTR, qmu::ecLOCALE, qmu::ecMISPLACED_COLON, qmu::ecMISSING_ELSE_CLAUSE, qmu::ecMISSING_PARENS, qmu::ecNAME_CONFLICT, qmu::ecOPRT_TYPE_CONFLICT, qmu::ecOPT_PRI, qmu::ecSTR_RESULT, qmu::ecSTRING_EXPECTED, qmu::ecTOO_FEW_PARAMS, qmu::ecTOO_MANY_PARAMS, qmu::ecUNASSIGNABLE_TOKEN, qmu::ecUNEXPECTED_ARG, qmu::ecUNEXPECTED_ARG_SEP, qmu::ecUNEXPECTED_CONDITIONAL, qmu::ecUNEXPECTED_EOF, qmu::ecUNEXPECTED_FUN, qmu::ecUNEXPECTED_OPERATOR, qmu::ecUNEXPECTED_PARENS, qmu::ecUNEXPECTED_STR, qmu::ecUNEXPECTED_VAL, qmu::ecUNEXPECTED_VAR, qmu::ecUNTERMINATED_STRING, and qmu::ecVAL_EXPECTED.
Member Data Documentation
appTranslator
QPointer<QTranslator> TST_QmuParserErrorMsg::appTranslator private
Definition at line 78 of file tst_qmuparsererrormsg.h.
Referenced by loadTranslations(), RemoveTranslation(), and ~TST_QmuParserErrorMsg().
m_locale
QString TST_QmuParserErrorMsg::m_locale private
Definition at line 77 of file tst_qmuparsererrormsg.h.
Referenced by AddCase(), initTestCase(), and RemoveTranslation().
msg
qmu::QmuParserErrorMsg* TST_QmuParserErrorMsg::msg private
Definition at line 79 of file tst_qmuparsererrormsg.h.
Referenced by loadTranslations(), and ~TST_QmuParserErrorMsg().
The documentation for this class was generated from the following files:
src/test/TranslationsTest/tst_qmuparsererrormsg.h
src/test/TranslationsTest/tst_qmuparsererrormsg.cpp