Seamly2D: MemoryManager Class Reference
MemoryManager Class Reference abstract
#include <MemoryManager.hpp>
Public Member Functions
Destructor
virtual ~MemoryManager ()
virtual MemoryManager * getExceptionMemoryManager ()=0
virtual ~MemoryManager ()
virtual MemoryManager * getExceptionMemoryManager ()=0
virtual ~MemoryManager ()
virtual MemoryManager * getExceptionMemoryManager ()=0
The pure virtual methods in this interface.
virtual void * allocate (XMLSize_t size)=0
virtual void deallocate (void *p)=0
virtual void * allocate (XMLSize_t size)=0
virtual void deallocate (void *p)=0
virtual void * allocate (XMLSize_t size)=0
virtual void deallocate (void *p)=0
Constructor
MemoryManager ()
MemoryManager ()
MemoryManager ()
MemoryManager (const MemoryManager &)
MemoryManager & operator= (const MemoryManager &)
MemoryManager (const MemoryManager &)
MemoryManager & operator= (const MemoryManager &)
MemoryManager (const MemoryManager &)
MemoryManager & operator= (const MemoryManager &)
Detailed Description
Configurable memory manager
This interface allows outside applications to plug in their own memory manager to be used by Xerces for memory allocation/deallocation.
Definition at line 39 of file MemoryManager.hpp.
Constructor & Destructor Documentation
~MemoryManager() [1/3]
virtual MemoryManager::~MemoryManager () inline virtual
Default destructor
Definition at line 52 of file MemoryManager.hpp.
MemoryManager() [1/6]
MemoryManager::MemoryManager () inline protected
Protected default constructor
Definition at line 108 of file MemoryManager.hpp.
MemoryManager() [2/6]
MemoryManager::MemoryManager (const MemoryManager &) private
~MemoryManager() [2/3]
virtual MemoryManager::~MemoryManager () inline virtual
Default destructor
Definition at line 52 of file MemoryManager.hpp.
MemoryManager() [3/6]
MemoryManager::MemoryManager () inline protected
Protected default constructor
Definition at line 108 of file MemoryManager.hpp.
MemoryManager() [4/6]
MemoryManager::MemoryManager (const MemoryManager &) private
~MemoryManager() [3/3]
virtual MemoryManager::~MemoryManager () inline virtual
Default destructor
Definition at line 52 of file MemoryManager.hpp.
MemoryManager() [5/6]
MemoryManager::MemoryManager () inline protected
Protected default constructor
Definition at line 108 of file MemoryManager.hpp.
MemoryManager() [6/6]
MemoryManager::MemoryManager (const MemoryManager &) private
Member Function Documentation
allocate() [1/3]
virtual void* MemoryManager::allocate (XMLSize_t size) pure virtual
This method allocates requested memory.
Parameters
size The requested memory size
Returns
A pointer to the allocated memory
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
Referenced by CMStateSet::allocateChunk(), BaseRefVectorOf< TElem >::BaseRefVectorOf(), CMStateSet::CMStateSet(), XMLDateTime::copy(), DOMDeepNodeListPool< TVal, THasher >::DOMDeepNodeListPool(), ContentLeafNameTypeVector::init(), NameIdPool< TElem >::NameIdPool(), XMLPlatformUtils::removeDotDotSlash(), XMLString::replicate(), XMLDateTime::setBuffer(), ElemStack::setCurrentSchemaElemName(), KVStringPair::setKey(), ComplexTypeInfo::setTypeName(), KVStringPair::setValue(), ValueArrayOf< TElem >::ValueArrayOf(), and XMLPlatformUtils::weavePaths().
allocate() [2/3]
virtual void* MemoryManager::allocate (XMLSize_t size) pure virtual
This method allocates requested memory.
Parameters
size The requested memory size
Returns
A pointer to the allocated memory
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
allocate() [3/3]
virtual void* MemoryManager::allocate (XMLSize_t size) pure virtual
This method allocates requested memory.
Parameters
size The requested memory size
Returns
A pointer to the allocated memory
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
deallocate() [1/3]
virtual void MemoryManager::deallocate (void * p) pure virtual
This method deallocates memory
Parameters
p The pointer to the allocated memory to be deleted
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
Referenced by RegularExpression::cleanUp(), ContentLeafNameTypeVector::cleanUp(), XPathMatcher::cleanUp(), CMStateSet::CMStateSet(), XMLDateTime::copy(), CMStateSet::deallocateChunk(), XMLEntityDecl::setBaseURI(), XMLNotationDecl::setBaseURI(), XMLDateTime::setBuffer(), DTDElementDecl::setContentModel(), ElemStack::setCurrentSchemaElemName(), SchemaElementDecl::setDefaultValue(), XMLAttDef::setEnumeration(), XMLScanner::setExternalNoNamespaceSchemaLocation(), XMLScanner::setExternalSchemaLocation(), KVStringPair::setKey(), XMLEntityDecl::setNotationName(), XMLEntityDecl::setPublicId(), XMLNotationDecl::setPublicId(), XMLScanner::setRootElemName(), StringToken::setString(), XMLEntityDecl::setSystemId(), XMLNotationDecl::setSystemId(), SchemaGrammar::setTargetNamespace(), ComplexTypeInfo::setTypeName(), XMLAttDef::setValue(), XMLEntityDecl::setValue(), KVStringPair::setValue(), AbstractDOMParser::useImplementation(), CMStateSet::~CMStateSet(), ENameMap::~ENameMap(), and PSVIAttribute::~PSVIAttribute().
deallocate() [2/3]
virtual void MemoryManager::deallocate (void * p) pure virtual
This method deallocates memory
Parameters
p The pointer to the allocated memory to be deleted
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
deallocate() [3/3]
virtual void MemoryManager::deallocate (void * p) pure virtual
This method deallocates memory
Parameters
p The pointer to the allocated memory to be deleted
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
getExceptionMemoryManager() [1/3]
virtual MemoryManager* MemoryManager::getExceptionMemoryManager () pure virtual
This method is called to obtain the memory manager that should be used to allocate memory used in exceptions. If the same memory manager can be used, simply return 'this' from this function. Note, however, that if there is a possibility that an exception thrown can outlive the memory manager (for example, because the memory manager object is allocated on the stack or is managed by a stack-bound object), it is recommended that you return XMLPlatformUtils::fgMemoryManager.
Returns
A pointer to the memory manager
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
getExceptionMemoryManager() [2/3]
virtual MemoryManager* MemoryManager::getExceptionMemoryManager () pure virtual
This method is called to obtain the memory manager that should be used to allocate memory used in exceptions. If the same memory manager can be used, simply return 'this' from this function. Note, however, that if there is a possibility that an exception thrown can outlive the memory manager (for example, because the memory manager object is allocated on the stack or is managed by a stack-bound object), it is recommended that you return XMLPlatformUtils::fgMemoryManager.
Returns
A pointer to the memory manager
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
getExceptionMemoryManager() [3/3]
virtual MemoryManager* MemoryManager::getExceptionMemoryManager () pure virtual
This method is called to obtain the memory manager that should be used to allocate memory used in exceptions. If the same memory manager can be used, simply return 'this' from this function. Note, however, that if there is a possibility that an exception thrown can outlive the memory manager (for example, because the memory manager object is allocated on the stack or is managed by a stack-bound object), it is recommended that you return XMLPlatformUtils::fgMemoryManager.
Returns
A pointer to the memory manager
Implemented in MemoryManagerImpl, MemoryManagerImpl, and MemoryManagerImpl.
operator=() [1/3]
MemoryManager& MemoryManager::operator= (const MemoryManager &) private
operator=() [2/3]
MemoryManager& MemoryManager::operator= (const MemoryManager &) private
operator=() [3/3]
MemoryManager& MemoryManager::operator= (const MemoryManager &) private
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/framework/MemoryManager.hpp