Seamly2D: VVITConverter Class Reference
VVITConverter Class Reference
#include <vvitconverter.h>
Public Member Functions
VVITConverter (const QString &fileName)
virtual ~VVITConverter () Q_DECL_EQ_DEFAULT
Public Member Functions inherited from VAbstractMConverter
VAbstractMConverter (const QString &fileName)
virtual ~VAbstractMConverter () Q_DECL_EQ_DEFAULT
Public Member Functions inherited from VAbstractConverter
VAbstractConverter (const QString &fileName)
virtual ~VAbstractConverter () Q_DECL_EQ_DEFAULT
QString Convert ()
int GetCurrentFormatVarsion () const
QString GetVersionStr () const
Public Member Functions inherited from VDomDocument
VDomDocument ()
virtual ~VDomDocument () Q_DECL_EQ_DEFAULT
QDomElement elementById (quint32 id, const QString &tagName=QString())
template<typename T >
void SetAttribute (QDomElement &domElement, const QString &name, const T &value) const
SetAttribute set attribute in pattern file. Replace "," by ".".
Unit MUnit () const
virtual void setXMLContent (const QString &fileName)
virtual bool SaveDocument (const QString &fileName, QString &error)
QString Major () const
QString Minor () const
QString Patch () const
QDomNode ParentNodeById (const quint32 &nodeId)
QDomElement CloneNodeById (const quint32 &nodeId)
QDomElement NodeById (const quint32 &nodeId)
QVector< VLabelTemplateLine > GetLabelTemplate (const QDomElement &element) const
void SetLabelTemplate (QDomElement &element, const QVector< VLabelTemplateLine > &lines)
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const QString &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const bool &value) const
template<>
void SetAttribute (QDomElement &domElement, const QString &name, const MeasurementsType &value) const
Static Public Attributes
static const QString MeasurementMaxVerStr = QStringLiteral("0.3.3")
static const QString CurrentSchema = QStringLiteral("://schema/individual_measurements/v0.3.3.xsd")
static Q_DECL_CONSTEXPR const int MeasurementMinVer = ((0 <<16)|(2 <<8)|(0))
static Q_DECL_CONSTEXPR const int MeasurementMaxVer = ((0 <<16)|(3 <<8)|(3))
Static Public Attributes inherited from VDomDocument
static const QString AttrId = QStringLiteral("id")
static const QString AttrText = QStringLiteral("text")
static const QString AttrBold = QStringLiteral("bold")
static const QString AttrItalic = QStringLiteral("italic")
static const QString AttrAlignment = QStringLiteral("alignment")
static const QString AttrFSIncrement = QStringLiteral("sfIncrement")
static const QString TagVersion = QStringLiteral("version")
static const QString TagUnit = QStringLiteral("unit")
static const QString TagLine = QStringLiteral("line")
Protected Member Functions
virtual int MinVer () const Q_DECL_OVERRIDE
virtual int MaxVer () const Q_DECL_OVERRIDE
virtual QString MinVerStr () const Q_DECL_OVERRIDE
virtual QString MaxVerStr () const Q_DECL_OVERRIDE
virtual QString XSDSchema (int ver) const Q_DECL_OVERRIDE
virtual void ApplyPatches () Q_DECL_OVERRIDE
virtual void DowngradeToCurrentMaxVersion () Q_DECL_OVERRIDE
virtual bool IsReadOnly () const Q_DECL_OVERRIDE
Protected Member Functions inherited from VAbstractMConverter
void AddRootComment ()
Protected Member Functions inherited from VAbstractConverter
void ValidateInputFile (const QString &currentSchema) const
Q_NORETURN void InvalidVersion (int ver) const
void Save ()
void SetVersion (const QString &version)
void Replace (QString &formula, const QString &newName, int position, const QString &token, int &bias) const
void CorrectionsPositions (int position, int bias, QMap< int, QString > &tokens) const
Protected Member Functions inherited from VDomDocument
bool setTagText (const QString &tag, const QString &text)
bool setTagText (const QDomElement &domElement, const QString &text)
QString UniqueTagText (const QString &tagName, const QString &defVal=QString()) const
void TestUniqueId () const
TestUniqueId test exist unique id in pattern file. Each id must be unique.
void CollectId (const QDomElement &node, QVector< quint32 > &vector) const
Private Member Functions
void AddNewTagsForV0_3_0 ()
QString MUnitV0_2_0 ()
void ConvertMeasurementsToV0_3_0 ()
QDomElement AddMV0_3_0 (const QString &name, qreal value)
void GenderV0_3_1 ()
void PM_SystemV0_3_2 ()
void ConvertMeasurementsToV0_3_3 ()
void ToV0_3_0 ()
void ToV0_3_1 ()
void ToV0_3_2 ()
void ToV0_3_3 ()
Static Private Attributes
static const QString MeasurementMinVerStr = QStringLiteral("0.2.0")
Additional Inherited Members
Static Public Member Functions inherited from VAbstractConverter
static int GetVersion (const QString &version)
Static Public Member Functions inherited from VDomDocument
static quint32 GetParametrUInt (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the long long value of the given attribute. RENAME: GetParameterLongLong?
static bool getParameterBool (const QDomElement &domElement, const QString &name, const QString &defValue)
static NodeUsage GetParametrUsage (const QDomElement &domElement, const QString &name)
static void SetParametrUsage (QDomElement &domElement, const QString &name, const NodeUsage &value)
static QString GetParametrString (const QDomElement &domElement, const QString &name, const QString &defValue=QString())
Returns the string value of the given attribute. RENAME: see above.
static QString GetParametrEmptyString (const QDomElement &domElement, const QString &name)
static qreal GetParametrDouble (const QDomElement &domElement, const QString &name, const QString &defValue)
Returns the double value of the given attribute.
static quint32 getParameterId (const QDomElement &domElement)
getParameterId return value id attribute.
static void ValidateXML (const QString &schema, const QString &fileName)
ValidateXML validate xml file by xsd schema.
static QString UnitsHelpString ()
static void RemoveAllChildren (QDomElement &domElement)
RemoveAllChildren remove all children from file.
static bool SafeCopy (const QString &source, const QString &destination, QString &error)
Static Protected Member Functions inherited from VAbstractMConverter
static QMultiMap< QString, QString > OldNamesToNewNames_InV0_3_0 ()
static QMap< QString, QString > OldNamesToNewNames_InV0_3_3 ()
Static Protected Member Functions inherited from VAbstractConverter
static void BiasTokens (int position, int bias, QMap< int, QString > &tokens)
Protected Attributes inherited from VAbstractConverter
int m_ver
QString m_convertedFileName
Detailed Description
Definition at line 65 of file vvitconverter.h.
Constructor & Destructor Documentation
VVITConverter()
VVITConverter::VVITConverter (const QString & fileName) explicit
Definition at line 88 of file vvitconverter.cpp.
References CurrentSchema, and VAbstractConverter::ValidateInputFile().
~VVITConverter()
virtual VVITConverter::~VVITConverter () virtual
Member Function Documentation
AddMV0_3_0()
QDomElement VVITConverter::AddMV0_3_0 (const QString & name, qreal value) private
Definition at line 242 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, MeasurementMinVer, and VDomDocument::SetAttribute().
Referenced by ConvertMeasurementsToV0_3_0().
AddNewTagsForV0_3_0()
void VVITConverter::AddNewTagsForV0_3_0 () private
Definition at line 167 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, MeasurementMinVer, and MUnitV0_2_0().
Referenced by ToV0_3_0().
ApplyPatches()
void VVITConverter::ApplyPatches () protected virtual
Implements VAbstractConverter.
Definition at line 117 of file vvitconverter.cpp.
References VAbstractConverter::InvalidVersion(), VAbstractConverter::m_convertedFileName, VAbstractConverter::m_ver, ToV0_3_0(), ToV0_3_1(), ToV0_3_2(), ToV0_3_3(), V_FALLTHROUGH, VDomDocument::ValidateXML(), and XSDSchema().
ConvertMeasurementsToV0_3_0()
void VVITConverter::ConvertMeasurementsToV0_3_0 () private
Definition at line 199 of file vvitconverter.cpp.
References AddMV0_3_0(), CONVERTER_VERSION_CHECK, VDomDocument::GetParametrDouble(), MeasurementMinVer, and VAbstractMConverter::OldNamesToNewNames_InV0_3_0().
Referenced by ToV0_3_0().
ConvertMeasurementsToV0_3_3()
void VVITConverter::ConvertMeasurementsToV0_3_3 () private
Definition at line 293 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, VDomDocument::GetParametrString(), MeasurementMinVer, VAbstractMConverter::OldNamesToNewNames_InV0_3_3(), and VDomDocument::SetAttribute().
Referenced by ToV0_3_3().
DowngradeToCurrentMaxVersion()
void VVITConverter::DowngradeToCurrentMaxVersion () protected virtual
Implements VAbstractConverter.
Definition at line 146 of file vvitconverter.cpp.
References MeasurementMaxVerStr, VAbstractConverter::Save(), and VAbstractConverter::SetVersion().
GenderV0_3_1()
void VVITConverter::GenderV0_3_1 () private
Definition at line 259 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, and MeasurementMinVer.
Referenced by ToV0_3_1().
IsReadOnly()
bool VVITConverter::IsReadOnly () const protected virtual
Implements VAbstractConverter.
Definition at line 153 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, falseStr, MeasurementMaxVer, strTagRead_Only, trueStr, and VDomDocument::UniqueTagText().
MaxVer()
int VVITConverter::MaxVer () const inline protected virtual
Implements VAbstractConverter.
Definition at line 120 of file vvitconverter.h.
References MeasurementMaxVer.
MaxVerStr()
QString VVITConverter::MaxVerStr () const inline protected virtual
Implements VAbstractConverter.
Definition at line 132 of file vvitconverter.h.
References MeasurementMaxVerStr.
MinVer()
int VVITConverter::MinVer () const inline protected virtual
Implements VAbstractConverter.
Definition at line 114 of file vvitconverter.h.
References MeasurementMinVer.
MinVerStr()
QString VVITConverter::MinVerStr () const inline protected virtual
Implements VAbstractConverter.
Definition at line 126 of file vvitconverter.h.
References MeasurementMinVerStr.
MUnitV0_2_0()
QString VVITConverter::MUnitV0_2_0 () private
Definition at line 189 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, MeasurementMinVer, and VDomDocument::UniqueTagText().
Referenced by AddNewTagsForV0_3_0().
PM_SystemV0_3_2()
void VVITConverter::PM_SystemV0_3_2 () private
Definition at line 276 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, and MeasurementMinVer.
Referenced by ToV0_3_2().
ToV0_3_0()
void VVITConverter::ToV0_3_0 () private
Definition at line 326 of file vvitconverter.cpp.
References AddNewTagsForV0_3_0(), VAbstractMConverter::AddRootComment(), CONVERTER_VERSION_CHECK, ConvertMeasurementsToV0_3_0(), MeasurementMinVer, VAbstractConverter::Save(), and VAbstractConverter::SetVersion().
Referenced by ApplyPatches().
ToV0_3_1()
void VVITConverter::ToV0_3_1 () private
Definition at line 340 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, GenderV0_3_1(), MeasurementMinVer, VAbstractConverter::Save(), and VAbstractConverter::SetVersion().
Referenced by ApplyPatches().
ToV0_3_2()
void VVITConverter::ToV0_3_2 () private
Definition at line 352 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, MeasurementMinVer, PM_SystemV0_3_2(), VAbstractConverter::Save(), and VAbstractConverter::SetVersion().
Referenced by ApplyPatches().
ToV0_3_3()
void VVITConverter::ToV0_3_3 () private
Definition at line 364 of file vvitconverter.cpp.
References CONVERTER_VERSION_CHECK, ConvertMeasurementsToV0_3_3(), MeasurementMinVer, VAbstractConverter::Save(), and VAbstractConverter::SetVersion().
Referenced by ApplyPatches().
XSDSchema()
QString VVITConverter::XSDSchema (int ver) const protected virtual
Implements VAbstractConverter.
Definition at line 95 of file vvitconverter.cpp.
References CurrentSchema, and VAbstractConverter::InvalidVersion().
Referenced by ApplyPatches().
Member Data Documentation
CurrentSchema
const QString VVITConverter::CurrentSchema = QStringLiteral("://schema/individual_measurements/v0.3.3.xsd") static
Definition at line 73 of file vvitconverter.h.
Referenced by VVITConverter(), and XSDSchema().
MeasurementMaxVer
Q_DECL_CONSTEXPR const int VVITConverter::MeasurementMaxVer = ((0 <<16)|(3 <<8)|(3)) static
Definition at line 80 of file vvitconverter.h.
Referenced by TMainWindow::FileNew(), TMainWindow::FileSave(), IsReadOnly(), and MaxVer().
MeasurementMaxVerStr
const QString VVITConverter::MeasurementMaxVerStr = QStringLiteral("0.3.3") static
Definition at line 72 of file vvitconverter.h.
Referenced by VMeasurements::CreateEmptyIndividualFile(), DowngradeToCurrentMaxVersion(), TMainWindow::FileNew(), TMainWindow::FileSave(), and MaxVerStr().
MeasurementMinVer
Q_DECL_CONSTEXPR const int VVITConverter::MeasurementMinVer = ((0 <<16)|(2 <<8)|(0)) static
Definition at line 79 of file vvitconverter.h.
Referenced by AddMV0_3_0(), AddNewTagsForV0_3_0(), ConvertMeasurementsToV0_3_0(), ConvertMeasurementsToV0_3_3(), GenderV0_3_1(), MinVer(), MUnitV0_2_0(), PM_SystemV0_3_2(), ToV0_3_0(), ToV0_3_1(), ToV0_3_2(), and ToV0_3_3().
MeasurementMinVerStr
const QString VVITConverter::MeasurementMinVerStr = QStringLiteral("0.2.0") static private
Definition at line 97 of file vvitconverter.h.
Referenced by MinVerStr().
The documentation for this class was generated from the following files:
src/libs/ifc/xml/vvitconverter.h
src/libs/ifc/xml/vvitconverter.cpp