Seamly2D: SchemaAttDefList Class Reference
SchemaAttDefList Class Reference
#include <SchemaAttDefList.hpp>
Public Member Functions
SchemaAttDefList (RefHash2KeysTableOf< SchemaAttDef > *const listToUse, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~SchemaAttDefList ()
virtual bool isEmpty () const
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const
XMLAttDef * findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart)
const XMLAttDef * findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart) const
virtual XMLSize_t getAttDefCount () const
virtual XMLAttDef & getAttDef (XMLSize_t index)
virtual const XMLAttDef & getAttDef (XMLSize_t index) const
SchemaAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDefList (RefHash2KeysTableOf< SchemaAttDef > *const listToUse, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~SchemaAttDefList ()
virtual bool isEmpty () const
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const
XMLAttDef * findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart)
const XMLAttDef * findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart) const
virtual XMLSize_t getAttDefCount () const
virtual XMLAttDef & getAttDef (XMLSize_t index)
virtual const XMLAttDef & getAttDef (XMLSize_t index) const
SchemaAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
SchemaAttDefList (RefHash2KeysTableOf< SchemaAttDef > *const listToUse, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~SchemaAttDefList ()
virtual bool isEmpty () const
virtual XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const unsigned int uriID, const XMLCh *const attName) const
virtual XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName)
virtual const XMLAttDef * findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const
XMLAttDef * findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart)
const XMLAttDef * findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart) const
virtual XMLSize_t getAttDefCount () const
virtual XMLAttDef & getAttDef (XMLSize_t index)
virtual const XMLAttDef & getAttDef (XMLSize_t index) const
SchemaAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Public Member Functions inherited from XMLAttDefList
virtual ~XMLAttDefList ()
virtual ~XMLAttDefList ()
virtual ~XMLAttDefList ()
MemoryManager * getMemoryManager () const
MemoryManager * getMemoryManager () const
MemoryManager * getMemoryManager () const
Public Member Functions inherited from XSerializable
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
virtual ~XSerializable ()
virtual bool isSerializable () const =0
virtual void serialize (XSerializeEngine &)=0
virtual XProtoType * getProtoType () const =0
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
SchemaAttDefList (const SchemaAttDefList &)
SchemaAttDefList & operator= (const SchemaAttDefList &)
void addAttDef (SchemaAttDef *toAdd)
SchemaAttDefList (const SchemaAttDefList &)
SchemaAttDefList & operator= (const SchemaAttDefList &)
void addAttDef (SchemaAttDef *toAdd)
SchemaAttDefList (const SchemaAttDefList &)
SchemaAttDefList & operator= (const SchemaAttDefList &)
void addAttDef (SchemaAttDef *toAdd)
Private Attributes
RefHash2KeysTableOfEnumerator< SchemaAttDef > * fEnum
RefHash2KeysTableOf< SchemaAttDef > * fList
SchemaAttDef ** fArray
XMLSize_t fSize
XMLSize_t fCount
Friends
class ComplexTypeInfo
Additional Inherited Members
Protected Member Functions inherited from XMLAttDefList
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
XMLAttDefList (MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Protected Member Functions inherited from XSerializable
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
XSerializable ()
XSerializable (const XSerializable &)
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 43 of file SchemaAttDefList.hpp.
Constructor & Destructor Documentation
SchemaAttDefList() [1/9]
SchemaAttDefList::SchemaAttDefList (RefHash2KeysTableOf< SchemaAttDef > *const listToUse, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaAttDefList() [1/3]
SchemaAttDefList::~SchemaAttDefList ()
SchemaAttDefList() [2/9]
SchemaAttDefList::SchemaAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDefList() [3/9]
SchemaAttDefList::SchemaAttDefList (const SchemaAttDefList &) private
SchemaAttDefList() [4/9]
SchemaAttDefList::SchemaAttDefList (RefHash2KeysTableOf< SchemaAttDef > *const listToUse, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaAttDefList() [2/3]
SchemaAttDefList::~SchemaAttDefList ()
SchemaAttDefList() [5/9]
SchemaAttDefList::SchemaAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDefList() [6/9]
SchemaAttDefList::SchemaAttDefList (const SchemaAttDefList &) private
SchemaAttDefList() [7/9]
SchemaAttDefList::SchemaAttDefList (RefHash2KeysTableOf< SchemaAttDef > *const listToUse, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~SchemaAttDefList() [3/3]
SchemaAttDefList::~SchemaAttDefList ()
SchemaAttDefList() [8/9]
SchemaAttDefList::SchemaAttDefList (MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
SchemaAttDefList() [9/9]
SchemaAttDefList::SchemaAttDefList (const SchemaAttDefList &) private
Member Function Documentation
addAttDef() [1/3]
void SchemaAttDefList::addAttDef (SchemaAttDef * toAdd) inline private
Definition at line 153 of file SchemaAttDefList.hpp.
References XMLAttDefList::getMemoryManager().
addAttDef() [2/3]
void SchemaAttDefList::addAttDef (SchemaAttDef * toAdd) private
References XMLAttDefList::getMemoryManager().
addAttDef() [3/3]
void SchemaAttDefList::addAttDef (SchemaAttDef * toAdd) private
References XMLAttDefList::getMemoryManager().
findAttDef() [1/12]
virtual XMLAttDef* SchemaAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [2/12]
virtual XMLAttDef* SchemaAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [3/12]
virtual XMLAttDef* SchemaAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [4/12]
virtual const XMLAttDef* SchemaAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [5/12]
virtual const XMLAttDef* SchemaAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [6/12]
virtual const XMLAttDef* SchemaAttDefList::findAttDef (const unsigned int uriID, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [7/12]
virtual XMLAttDef* SchemaAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [8/12]
virtual XMLAttDef* SchemaAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [9/12]
virtual XMLAttDef* SchemaAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) virtual
Implements XMLAttDefList.
findAttDef() [10/12]
virtual const XMLAttDef* SchemaAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [11/12]
virtual const XMLAttDef* SchemaAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDef() [12/12]
virtual const XMLAttDef* SchemaAttDefList::findAttDef (const XMLCh *const attURI, const XMLCh *const attName) const virtual
Implements XMLAttDefList.
findAttDefLocalPart() [1/6]
XMLAttDef * SchemaAttDefList::findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart) inline
Definition at line 167 of file SchemaAttDefList.hpp.
findAttDefLocalPart() [2/6]
XMLAttDef* SchemaAttDefList::findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart)
findAttDefLocalPart() [3/6]
XMLAttDef* SchemaAttDefList::findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart)
findAttDefLocalPart() [4/6]
const XMLAttDef * SchemaAttDefList::findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart) const inline
Definition at line 173 of file SchemaAttDefList.hpp.
findAttDefLocalPart() [5/6]
const XMLAttDef* SchemaAttDefList::findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart) const
findAttDefLocalPart() [6/6]
const XMLAttDef* SchemaAttDefList::findAttDefLocalPart (const unsigned int uriID, const XMLCh *const attLocalPart) const
getAttDef() [1/6]
virtual XMLAttDef& SchemaAttDefList::getAttDef (XMLSize_t index) virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [2/6]
virtual XMLAttDef& SchemaAttDefList::getAttDef (XMLSize_t index) virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [3/6]
virtual XMLAttDef& SchemaAttDefList::getAttDef (XMLSize_t index) virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [4/6]
virtual const XMLAttDef& SchemaAttDefList::getAttDef (XMLSize_t index) const virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [5/6]
virtual const XMLAttDef& SchemaAttDefList::getAttDef (XMLSize_t index) const virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDef() [6/6]
virtual const XMLAttDef& SchemaAttDefList::getAttDef (XMLSize_t index) const virtual
return attribute at the index-th position in the list.
Implements XMLAttDefList.
getAttDefCount() [1/3]
virtual XMLSize_t SchemaAttDefList::getAttDefCount () const virtual
return total number of attributes in this list
Implements XMLAttDefList.
getAttDefCount() [2/3]
virtual XMLSize_t SchemaAttDefList::getAttDefCount () const virtual
return total number of attributes in this list
Implements XMLAttDefList.
getAttDefCount() [3/3]
virtual XMLSize_t SchemaAttDefList::getAttDefCount () const virtual
return total number of attributes in this list
Implements XMLAttDefList.
isEmpty() [1/3]
virtual bool SchemaAttDefList::isEmpty () const virtual
Implements XMLAttDefList.
isEmpty() [2/3]
virtual bool SchemaAttDefList::isEmpty () const virtual
Implements XMLAttDefList.
isEmpty() [3/3]
virtual bool SchemaAttDefList::isEmpty () const virtual
Implements XMLAttDefList.
operator=() [1/3]
SchemaAttDefList& SchemaAttDefList::operator= (const SchemaAttDefList &) private
operator=() [2/3]
SchemaAttDefList& SchemaAttDefList::operator= (const SchemaAttDefList &) private
operator=() [3/3]
SchemaAttDefList& SchemaAttDefList::operator= (const SchemaAttDefList &) private
Friends And Related Function Documentation
ComplexTypeInfo
ComplexTypeInfo friend
Definition at line 150 of file SchemaAttDefList.hpp.
Member Data Documentation
fArray
SchemaAttDef ** SchemaAttDefList::fArray private
Definition at line 146 of file SchemaAttDefList.hpp.
fCount
XMLSize_t SchemaAttDefList::fCount private
Definition at line 148 of file SchemaAttDefList.hpp.
fEnum
RefHash2KeysTableOfEnumerator< SchemaAttDef > * SchemaAttDefList::fEnum private
Definition at line 144 of file SchemaAttDefList.hpp.
fList
RefHash2KeysTableOf< SchemaAttDef > * SchemaAttDefList::fList private
Definition at line 145 of file SchemaAttDefList.hpp.
fSize
XMLSize_t SchemaAttDefList::fSize private
Definition at line 147 of file SchemaAttDefList.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/SchemaAttDefList.hpp