name: Build manual MacOs

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Build manual MacOS'

env:
  QT_SELECT: 5
  QT_VERSION: '5.15.2' # quotes required or YAML parser will interpret as float

# The tag name is Test-macos-manual-YYmmdd-HHMM to enable multiple tests per day
jobs:

  release-data:
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create-release-data.outputs.upload_url }}

    steps:
      - name: create name and tag
        id: create-name-and-tag
        run: |
          echo "TAG_NAME=Test-macos-manual-`date +"%F%H%M"`" >> $GITHUB_ENV
          echo "RELEASE_NAME=Test macos manual `date +"%F%H%M"`" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create release data
        id: create-release-data
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: Manual test of MacOs build, creates pre-release
          # create unpublished
          draft: false
          # create pre-release
          prerelease: true

      - name: show UPLOAD_URL
        #display upload_url then save it as a GITHUB ENV VARIABLE
        run: |
          echo ${{ steps.create-release-data.outputs.upload_url }} 
  
  macos:
    runs-on: macos-latest
    needs: release-data
    env:
      UPLOAD_URL: "${{ needs.release-data.outputs.upload_url }}"

    steps:
      - name: check upload URL
        # display upload_url
        run: |
          echo "${{ needs.release-data.outputs.upload_url }}"
          echo "${{ env.UPLOAD_URL }}"

      - name: checkout code
        uses: actions/checkout@v3

      - name: install qt
        uses: jurplel/install-qt-action@v3.0.0
        with:
          version: ${{ env.QT_VERSION }}

      - name: qmake Seamly2D and SeamlyMe
        run: |
          qmake Seamly2D.pro -r CONFIG+=no_ccache CONFIG+=noDebugSymbols
          make

      - name: build dmg packages
        run: |
          hdiutil create -fs HFS+ -srcfolder src/app/seamly2d/bin/Seamly2D.app -volname "Seamly2D" Seamly2D.dmg
          hdiutil create -fs HFS+ -srcfolder src/app/seamlyme/bin/seamlyme.app -volname "SeamlyME" SeamlyME.dmg

      - name: pack package files into .zip
        run: |
          zip Seamly2D-macos.zip Seamly2D.dmg SeamlyME.dmg

      - name: upload Seamly2D-macos.zip as pre-release to Github Releases
        uses: actions/upload-release-asset@v1.0.2
        # uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./Seamly2D-macos.zip
          asset_name: Seamly2D-macos.zip
          asset_content_type: application/zip
