Seamly2D: Hash2KeysSetOf< THasher > Class Template Reference
Hash2KeysSetOf< THasher > Class Template Reference
#include <Hash2KeysSetOf.hpp>
Public Member Functions
Hash2KeysSetOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Hash2KeysSetOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~Hash2KeysSetOf ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2) const
void removeKey (const void *const key1, const int key2)
void removeKey (const void *const key1)
void removeAll ()
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
void put (const void *key1, int key2)
bool putIfNotPresent (const void *key1, int key2)
Hash2KeysSetOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Hash2KeysSetOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~Hash2KeysSetOf ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2) const
void removeKey (const void *const key1, const int key2)
void removeKey (const void *const key1)
void removeAll ()
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
void put (const void *key1, int key2)
bool putIfNotPresent (const void *key1, int key2)
Hash2KeysSetOf (const XMLSize_t modulus, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
Hash2KeysSetOf (const XMLSize_t modulus, const THasher &hasher, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager)
~Hash2KeysSetOf ()
bool isEmpty () const
bool containsKey (const void *const key1, const int key2) const
void removeKey (const void *const key1, const int key2)
void removeKey (const void *const key1)
void removeAll ()
MemoryManager * getMemoryManager () const
XMLSize_t getHashModulus () const
void put (const void *key1, int key2)
bool putIfNotPresent (const void *key1, int key2)
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Member Functions
Hash2KeysSetOf (const Hash2KeysSetOf< THasher > &)
Hash2KeysSetOf< THasher > & operator= (const Hash2KeysSetOf< THasher > &)
Hash2KeysSetBucketElem * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal)
const Hash2KeysSetBucketElem * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
Hash2KeysSetOf (const Hash2KeysSetOf< THasher > &)
Hash2KeysSetOf< THasher > & operator= (const Hash2KeysSetOf< THasher > &)
Hash2KeysSetBucketElem * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal)
const Hash2KeysSetBucketElem * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
Hash2KeysSetOf (const Hash2KeysSetOf< THasher > &)
Hash2KeysSetOf< THasher > & operator= (const Hash2KeysSetOf< THasher > &)
Hash2KeysSetBucketElem * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal)
const Hash2KeysSetBucketElem * findBucketElem (const void *const key1, const int key2, XMLSize_t &hashVal) const
void initialize (const XMLSize_t modulus)
void rehash ()
Private Attributes
MemoryManager * fMemoryManager
Hash2KeysSetBucketElem ** fBucketList
XMLSize_t fHashModulus
XMLSize_t fCount
Hash2KeysSetBucketElem * fAvailable
THasher fHasher
Friends
class Hash2KeysSetOfEnumerator< THasher >
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
template<class THasher>
class Hash2KeysSetOf< THasher >
Definition at line 54 of file Hash2KeysSetOf.hpp.
Constructor & Destructor Documentation
Hash2KeysSetOf() [1/9]
template<class THasher > XERCES_CPP_NAMESPACE_BEGIN Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Definition at line 42 of file Hash2KeysSetOf.c.
References Hash2KeysSetOf< THasher >::initialize().
Hash2KeysSetOf() [2/9]
template<class THasher > Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Definition at line 56 of file Hash2KeysSetOf.c.
~Hash2KeysSetOf() [1/3]
template<class THasher > Hash2KeysSetOf< THasher >::~Hash2KeysSetOf
Definition at line 86 of file Hash2KeysSetOf.c.
Hash2KeysSetOf() [3/9]
template<class THasher > Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const Hash2KeysSetOf< THasher > &) private
Hash2KeysSetOf() [4/9]
template<class THasher > Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Hash2KeysSetOf() [5/9]
template<class THasher > Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~Hash2KeysSetOf() [2/3]
template<class THasher > Hash2KeysSetOf< THasher >::~Hash2KeysSetOf ()
Hash2KeysSetOf() [6/9]
template<class THasher > Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const Hash2KeysSetOf< THasher > &) private
Hash2KeysSetOf() [7/9]
template<class THasher > Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const XMLSize_t modulus, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
Hash2KeysSetOf() [8/9]
template<class THasher > Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const XMLSize_t modulus, const THasher & hasher, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager)
~Hash2KeysSetOf() [3/3]
template<class THasher > Hash2KeysSetOf< THasher >::~Hash2KeysSetOf ()
Hash2KeysSetOf() [9/9]
template<class THasher > Hash2KeysSetOf< THasher >::Hash2KeysSetOf (const Hash2KeysSetOf< THasher > &) private
Member Function Documentation
containsKey() [1/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::containsKey (const void *const key1, const int key2) const
Definition at line 135 of file Hash2KeysSetOf.c.
containsKey() [2/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::containsKey (const void *const key1, const int key2) const
containsKey() [3/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::containsKey (const void *const key1, const int key2) const
findBucketElem() [1/6]
template<class THasher > Hash2KeysSetBucketElem * Hash2KeysSetOf< THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) inline private
Definition at line 358 of file Hash2KeysSetOf.c.
References Hash2KeysSetBucketElem::fKey1, Hash2KeysSetBucketElem::fKey2, and Hash2KeysSetBucketElem::fNext.
findBucketElem() [2/6]
template<class THasher > Hash2KeysSetBucketElem* Hash2KeysSetOf< THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) private
findBucketElem() [3/6]
template<class THasher > Hash2KeysSetBucketElem* Hash2KeysSetOf< THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) private
findBucketElem() [4/6]
template<class THasher > const Hash2KeysSetBucketElem * Hash2KeysSetOf< THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) const inline private
Definition at line 378 of file Hash2KeysSetOf.c.
References Hash2KeysSetBucketElem::fKey1, Hash2KeysSetBucketElem::fKey2, and Hash2KeysSetBucketElem::fNext.
findBucketElem() [5/6]
template<class THasher > const Hash2KeysSetBucketElem* Hash2KeysSetOf< THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) const private
findBucketElem() [6/6]
template<class THasher > const Hash2KeysSetBucketElem* Hash2KeysSetOf< THasher >::findBucketElem (const void *const key1, const int key2, XMLSize_t & hashVal) const private
getHashModulus() [1/3]
template<class THasher > XMLSize_t Hash2KeysSetOf< THasher >::getHashModulus
Definition at line 269 of file Hash2KeysSetOf.c.
getHashModulus() [2/3]
template<class THasher > XMLSize_t Hash2KeysSetOf< THasher >::getHashModulus () const
getHashModulus() [3/3]
template<class THasher > XMLSize_t Hash2KeysSetOf< THasher >::getHashModulus () const
getMemoryManager() [1/3]
template<class THasher > MemoryManager * Hash2KeysSetOf< THasher >::getMemoryManager
Definition at line 263 of file Hash2KeysSetOf.c.
getMemoryManager() [2/3]
template<class THasher > MemoryManager* Hash2KeysSetOf< THasher >::getMemoryManager () const
getMemoryManager() [3/3]
template<class THasher > MemoryManager* Hash2KeysSetOf< THasher >::getMemoryManager () const
initialize() [1/3]
template<class THasher > void Hash2KeysSetOf< THasher >::initialize (const XMLSize_t modulus) private
Definition at line 72 of file Hash2KeysSetOf.c.
References XMLExcepts::HshTbl_ZeroModulus, and ThrowXMLwithMemMgr.
Referenced by Hash2KeysSetOf< THasher >::Hash2KeysSetOf().
initialize() [2/3]
template<class THasher > void Hash2KeysSetOf< THasher >::initialize (const XMLSize_t modulus) private
initialize() [3/3]
template<class THasher > void Hash2KeysSetOf< THasher >::initialize (const XMLSize_t modulus) private
isEmpty() [1/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::isEmpty
Definition at line 129 of file Hash2KeysSetOf.c.
isEmpty() [2/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::isEmpty () const
isEmpty() [3/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::isEmpty () const
operator=() [1/3]
template<class THasher > Hash2KeysSetOf<THasher>& Hash2KeysSetOf< THasher >::operator= (const Hash2KeysSetOf< THasher > &) private
operator=() [2/3]
template<class THasher > Hash2KeysSetOf<THasher>& Hash2KeysSetOf< THasher >::operator= (const Hash2KeysSetOf< THasher > &) private
operator=() [3/3]
template<class THasher > Hash2KeysSetOf<THasher>& Hash2KeysSetOf< THasher >::operator= (const Hash2KeysSetOf< THasher > &) private
put() [1/3]
template<class THasher > void Hash2KeysSetOf< THasher >::put (const void * key1, int key2)
Definition at line 278 of file Hash2KeysSetOf.c.
References Hash2KeysSetBucketElem::fKey1, Hash2KeysSetBucketElem::fKey2, and Hash2KeysSetBucketElem::fNext.
put() [2/3]
template<class THasher > void Hash2KeysSetOf< THasher >::put (const void * key1, int key2)
put() [3/3]
template<class THasher > void Hash2KeysSetOf< THasher >::put (const void * key1, int key2)
putIfNotPresent() [1/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::putIfNotPresent (const void * key1, int key2)
Definition at line 318 of file Hash2KeysSetOf.c.
References Hash2KeysSetBucketElem::fKey1, Hash2KeysSetBucketElem::fKey2, and Hash2KeysSetBucketElem::fNext.
putIfNotPresent() [2/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::putIfNotPresent (const void * key1, int key2)
putIfNotPresent() [3/3]
template<class THasher > bool Hash2KeysSetOf< THasher >::putIfNotPresent (const void * key1, int key2)
rehash() [1/3]
template<class THasher > void Hash2KeysSetOf< THasher >::rehash private
Definition at line 399 of file Hash2KeysSetOf.c.
References Hash2KeysSetBucketElem::fKey1, Hash2KeysSetBucketElem::fNext, and ArrayJanitor< T >::release().
rehash() [2/3]
template<class THasher > void Hash2KeysSetOf< THasher >::rehash () private
rehash() [3/3]
template<class THasher > void Hash2KeysSetOf< THasher >::rehash () private
removeAll() [1/3]
template<class THasher > void Hash2KeysSetOf< THasher >::removeAll
Definition at line 237 of file Hash2KeysSetOf.c.
References Hash2KeysSetBucketElem::fNext.
removeAll() [2/3]
template<class THasher > void Hash2KeysSetOf< THasher >::removeAll ()
removeAll() [3/3]
template<class THasher > void Hash2KeysSetOf< THasher >::removeAll ()
removeKey() [1/6]
template<class THasher > void Hash2KeysSetOf< THasher >::removeKey (const void *const key1)
Definition at line 189 of file Hash2KeysSetOf.c.
References Hash2KeysSetBucketElem::fKey1, and Hash2KeysSetBucketElem::fNext.
removeKey() [2/6]
template<class THasher > void Hash2KeysSetOf< THasher >::removeKey (const void *const key1)
removeKey() [3/6]
template<class THasher > void Hash2KeysSetOf< THasher >::removeKey (const void *const key1)
removeKey() [4/6]
template<class THasher > void Hash2KeysSetOf< THasher >::removeKey (const void *const key1, const int key2)
Definition at line 143 of file Hash2KeysSetOf.c.
References Hash2KeysSetBucketElem::fKey1, Hash2KeysSetBucketElem::fKey2, Hash2KeysSetBucketElem::fNext, XMLExcepts::HshTbl_NoSuchKeyExists, and ThrowXMLwithMemMgr.
removeKey() [5/6]
template<class THasher > void Hash2KeysSetOf< THasher >::removeKey (const void *const key1, const int key2)
removeKey() [6/6]
template<class THasher > void Hash2KeysSetOf< THasher >::removeKey (const void *const key1, const int key2)
Friends And Related Function Documentation
Hash2KeysSetOfEnumerator< THasher >
template<class THasher > friend class Hash2KeysSetOfEnumerator< THasher > friend
Definition at line 92 of file Hash2KeysSetOf.hpp.
Member Data Documentation
fAvailable
template<class THasher > Hash2KeysSetBucketElem * Hash2KeysSetOf< THasher >::fAvailable private
Definition at line 138 of file Hash2KeysSetOf.hpp.
fBucketList
template<class THasher > Hash2KeysSetBucketElem ** Hash2KeysSetOf< THasher >::fBucketList private
Definition at line 135 of file Hash2KeysSetOf.hpp.
fCount
template<class THasher > XMLSize_t Hash2KeysSetOf< THasher >::fCount private
Definition at line 137 of file Hash2KeysSetOf.hpp.
fHasher
template<class THasher > THasher Hash2KeysSetOf< THasher >::fHasher private
Definition at line 139 of file Hash2KeysSetOf.hpp.
fHashModulus
template<class THasher > XMLSize_t Hash2KeysSetOf< THasher >::fHashModulus private
Definition at line 136 of file Hash2KeysSetOf.hpp.
fMemoryManager
template<class THasher > MemoryManager * Hash2KeysSetOf< THasher >::fMemoryManager private
Definition at line 134 of file Hash2KeysSetOf.hpp.
The documentation for this class was generated from the following files:
src/libs/xerces-c/macx/include/xercesc/util/Hash2KeysSetOf.hpp
src/libs/xerces-c/macx/include/xercesc/util/Hash2KeysSetOf.c