Seamly2D: PatternPieceTool Class Reference
PatternPieceTool Class Reference
#include <pattern_piece_tool.h>
Public Types
enum { Type = UserType + static_cast<int>(Tool::Piece) }
Public Slots
virtual void FullUpdateFromFile () Q_DECL_OVERRIDE
void EnableToolMove (bool move)
void pieceLockedChanged (quint32 id, bool lock)
virtual void AllowHover (bool enabled) Q_DECL_OVERRIDE
virtual void AllowSelecting (bool enabled) Q_DECL_OVERRIDE
virtual void ResetChildren (QGraphicsItem *pItem)
virtual void UpdateAll ()
virtual void retranslateUi ()
void Highlight (quint32 id)
void updatePieceDetails ()
void UpdatePieceLabel ()
UpdateLabel updates the text label, making it just big enough for the text to fit it.
void UpdatePatternLabel ()
UpdatePatternLabel updates the pattern info label.
void UpdateGrainline ()
VToolDetail::UpdateGrainline updates the grain line item.
void editPieceProperties ()
editPieceProperties - routine to edit pattern piece properties .
Public Slots inherited from VInteractiveTool
void FullUpdateFromGuiOk (int result)
FullUpdateFromGuiOk refresh tool data after change in options.
void FullUpdateFromGuiApply ()
FullUpdateFromGuiApply refresh tool data after change in options but do not delete dialog.
Public Slots inherited from VAbstractTool
virtual void FullUpdateFromFile ()=0
FullUpdateFromFile update tool data form file.
virtual void AllowHover (bool enabled)=0
virtual void AllowSelecting (bool enabled)=0
virtual void ToolSelectionType (const SelectionType &type)
Public Member Functions
virtual ~PatternPieceTool () Q_DECL_EQ_DEFAULT
void Remove (bool ask)
void RefreshGeometry ()
virtual int type () const Q_DECL_OVERRIDE
virtual QString getTagName () const Q_DECL_OVERRIDE
virtual void ShowVisualization (bool show) Q_DECL_OVERRIDE
virtual void GroupVisibility (quint32 object, bool visible) Q_DECL_OVERRIDE
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget) Q_DECL_OVERRIDE
VToolDetail::paint draws a bounding box around piece, if one of its text or grainline items is not idle.
virtual QRectF boundingRect () const Q_DECL_OVERRIDE
virtual QPainterPath shape () const Q_DECL_OVERRIDE
Public Member Functions inherited from VInteractiveTool
VInteractiveTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
virtual ~VInteractiveTool () Q_DECL_EQ_DEFAULT
void DialogLinkDestroy ()
Public Member Functions inherited from VAbstractTool
VAbstractTool (VAbstractPattern *doc, VContainer *data, quint32 id, QObject *parent=nullptr)
VAbstractTool container.
virtual ~VAbstractTool () Q_DECL_OVERRIDE
quint32 getId () const
getId return object id.
const VContainer * getData () const
getData return pointer to data container.
QMap< QString, quint32 > PointsList () const
virtual void setPointNamePosition (quint32 id, const QPointF &pos)
virtual void setPointNameVisiblity (quint32 id, bool visible)
Public Member Functions inherited from VDataTool
VDataTool (VContainer *data, QObject *parent=nullptr)
VDataTool constructor.
virtual ~VDataTool () Q_DECL_EQ_DEFAULT
VContainer getData () const
getData return data container.
void setData (const VContainer *value)
setData set data container.
virtual quint32 referens () const
referens return count of referens.
virtual void incrementReferens ()
incrementReferens increment referens.
virtual void decrementReferens ()
decrementReferens decrement referens.
Static Public Member Functions
static PatternPieceTool * Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static PatternPieceTool * Create (quint32 id, VPiece newPiece, QString &width, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data, const Document &parse, const Source &typeCreation, const QString &blockName=QString())
static void insertNodes (const QVector< VPieceNode > &nodes, quint32 pieceId, VMainGraphicsScene *scene, VContainer *data, VAbstractPattern *doc)
static void AddAttributes (VAbstractPattern *doc, QDomElement &domElement, quint32 id, const VPiece &piece)
static void AddCSARecord (VAbstractPattern *doc, QDomElement &domElement, const CustomSARecord &record)
static void AddCSARecords (VAbstractPattern *doc, QDomElement &domElement, const QVector< CustomSARecord > &records)
static void AddInternalPaths (VAbstractPattern *doc, QDomElement &domElement, const QVector< quint32 > &paths)
static void addAnchors (VAbstractPattern *doc, QDomElement &domElement, const QVector< quint32 > &anchors)
static void AddPatternPieceData (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
static void AddPatternInfo (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
static void AddGrainline (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
Static Public Member Functions inherited from VAbstractTool
static qreal CheckFormula (const quint32 &toolId, QString &formula, VContainer *data)
CheckFormula check formula.
static const QStringList Colors ()
static QMap< QString, QString > ColorsList ()
static QMap< QString, QString > supportColorsList ()
static QMap< QString, QString > backgroundColorsList ()
static QPixmap createColorIcon (const int w, const int h, const QString &color)
static const QStringList fills ()
static void AddRecord (const quint32 id, const Tool &toolType, VAbstractPattern *doc)
AddRecord add record about tool in history.
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiecePath &path)
static void AddNodes (VAbstractPattern *doc, QDomElement &domElement, const VPiece &piece)
template<typename T >
static quint32 CreateNode (VContainer *data, quint32 id)
CreateNode create new node for detail.
Static Public Attributes
static const quint8 pieceVersion = 2
static const QString TagCSA = QStringLiteral("csa")
static const QString TagRecord = QStringLiteral("record")
static const QString TagIPaths = QStringLiteral("iPaths")
static const QString TagAnchors = QStringLiteral("anchors")
static const QString AttrVersion = QStringLiteral("version")
static const QString AttrForbidFlipping = QStringLiteral("forbidFlipping")
static const QString AttrPieceColor = QStringLiteral("color")
static const QString AttrPieceFill = QStringLiteral("fill")
static const QString AttrPieceLock = QStringLiteral("locked")
static const QString AttrSeamAllowance = QStringLiteral("seamAllowance")
static const QString AttrHideSeamLine = QStringLiteral("hideMainPath")
static const QString AttrSeamAllowanceBuiltIn = QStringLiteral("seamAllowanceBuiltIn")
static const QString AttrHeight = QStringLiteral("height")
static const QString AttrUnited = QStringLiteral("united")
static const QString AttrFont = QStringLiteral("fontSize")
static const QString AttrTopLeftAnchor = QStringLiteral("topLeftAnchor")
static const QString AttrBottomRightAnchor = QStringLiteral("bottomRightAnchor")
static const QString AttrCenterAnchor = QStringLiteral("centerAnchor")
static const QString AttrTopAnchorPoint = QStringLiteral("topAnchor")
static const QString AttrBottomAnchorPoint = QStringLiteral("bottomAnchor")
Static Public Attributes inherited from VAbstractTool
static bool m_suppressContextMenu = false
static const QString AttrInUse = QStringLiteral("inUse")
Protected Slots
void saveMovePiece (const QPointF &ptPos)
saveMovePiece saves the move piece operation to the undo stack
void saveResizePiece (qreal dLabelW, int iFontSize)
saveResizePiece saves the resize piece label operation to the undo stack
void savePieceRotation (qreal dRot)
savePieceRotation saves the rotation piece label operation to the undo stack
void SaveMovePattern (const QPointF &ptPos)
SaveMovePattern saves the pattern label position.
void SaveResizePattern (qreal dLabelW, int iFontSize)
: SaveResizePattern saves the pattern label width and font size
void SaveRotationPattern (qreal dRot)
void SaveMoveGrainline (const QPointF &ptPos)
void SaveResizeGrainline (qreal dLength)
void SaveRotateGrainline (qreal dRot, const QPointF &ptPos)
Protected Member Functions
virtual void AddToFile () Q_DECL_OVERRIDE
AddToFile add tag with Information about tool into file.
virtual void RefreshDataInFile () Q_DECL_OVERRIDE
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value) Q_DECL_OVERRIDE
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) Q_DECL_OVERRIDE
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) Q_DECL_OVERRIDE
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) Q_DECL_OVERRIDE
virtual void keyReleaseEvent (QKeyEvent *event) Q_DECL_OVERRIDE
virtual void SetVisualization () Q_DECL_OVERRIDE
virtual void deleteTool (bool ask=true) Q_DECL_OVERRIDE
deleteTool full delete object form scene and file.
virtual void ToolCreation (const Source &typeCreation) Q_DECL_OVERRIDE
virtual void SetDialog () Q_DECL_FINAL
virtual void SaveDialogChange () Q_DECL_FINAL
Protected Member Functions inherited from VInteractiveTool
virtual void setDialog ()
setDialog set dialog when user want change tool option.
Protected Member Functions inherited from VAbstractTool
virtual void RemoveReferens ()
RemoveReferens decrement value of reference.
template<typename T >
void AddVisualization ()
Private Member Functions
PatternPieceTool (VAbstractPattern *doc, VContainer *data, const quint32 &id, const Source &typeCreation, VMainGraphicsScene *scene, const QString &blockName, QGraphicsItem *parent=nullptr)
void UpdateExcludeState ()
VPieceItem::MoveTypes FindLabelGeometry (const VPatternLabelData &labelData, qreal &rotationAngle, qreal &labelWidth, qreal &labelHeight, QPointF &pos)
VPieceItem::MoveTypes FindGrainlineGeometry (const VGrainlineData &geom, qreal &length, qreal &rotationAngle, QPointF &pos)
void initializeNodes (const VPiece &piece, VMainGraphicsScene *scene)
void InitCSAPaths (const VPiece &piece)
void InitInternalPaths (const VPiece &piece)
void initializeAnchorPoints (const VPiece &piece)
bool PrepareLabelData (const VPatternLabelData &labelData, VTextGraphicsItem *labelItem, QPointF &pos, qreal &labelAngle)
void UpdateLabelItem (VTextGraphicsItem *labelItem, QPointF pos, qreal labelAngle)
void toggleInLayout (bool checked)
toggleInLayout - routine to toggle if pattern piece is included and visible in layout.
void togglePieceLock (bool checked)
togglePieceLock - routine to toggle if pattern piece is locked and editiable.
void toggleFlipping (bool checked)
toggleFlipping - routine to toggle forbidding flipping.
void toggleSeamLine (bool checked)
toggleSeamLine - routine to toggle the visibility of the seam line.
void toggleSeamAllowance (bool checked)
toggleSeamAllowance - routine to toggle the visibility of the seam allowance.
void toggleGrainline (bool checked)
toggleGrainline - routine to toggle the visibility of the piece grainline.
void togglePatternLabel (bool checked)
togglePatternLabel - routine to toggle the visibility of the pattern label.
void togglePieceLabel (bool checked)
togglePieceLabel - routine to toggle the visibility of the piece label.
void renamePiece (VPiece piece)
renamePiece - routine to rename pattern piece.
void showStatus (QString toolTip)
void raiseItemToTop (QGraphicsItem *item)
void lowerItemToBottom (QGraphicsItem *item)
Static Private Member Functions
static void initializeNode (const VPieceNode &node, VMainGraphicsScene *scene, VContainer *data, VAbstractPattern *doc, PatternPieceTool *parent)
Private Attributes
QPainterPath m_mainPath
QRectF m_pieceRect
QPainterPath m_cutPath
VMainGraphicsScene * m_pieceScene
QString m_blockName
pieceScene pointer to the scene.
NonScalingFillPathItem * m_cutLine
NonScalingFillPathItem * m_seamLine
VTextGraphicsItem * m_dataLabel
VTextGraphicsItem * m_patternInfo
VGrainlineItem * m_grainLine
QGraphicsPathItem * m_notches
Additional Inherited Members
Signals inherited from VAbstractTool
void toolHasChanges ()
toolHasChanges emit if tool create change that need save.
void chosenTool (quint32 id, SceneObject type)
chosenTool emit if object was clicked.
void LiteUpdateTree (const Document &parse)
FullUpdateTree emit if need reparse pattern file.
void ToolTip (const QString &toolTip)
Static Protected Member Functions inherited from VAbstractTool
static int ConfirmDeletion ()
static QDomElement AddSANode (VAbstractPattern *doc, const QString &tagName, const VPieceNode &node)
static void AddNode (VAbstractPattern *doc, QDomElement &domElement, const VPieceNode &node)
static QVector< VPieceNode > PrepareNodes (const VPiecePath &path, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
static quint32 PrepareNode (const VPieceNode &node, VMainGraphicsScene *scene, VAbstractPattern *doc, VContainer *data)
Protected Attributes inherited from VInteractiveTool
QSharedPointer< DialogTool > m_dialog
m_dialog tool's dialog options.
Protected Attributes inherited from VAbstractTool
VAbstractPattern * doc
doc dom document container
const quint32 m_id
id object id.
QPointer< Visualization > vis
SelectionType selectionType
Protected Attributes inherited from VDataTool
VContainer data
data container with data
quint32 _referens
_referens keep count tools what use this tool. If value more than 1 you can't delete tool.
Detailed Description
Definition at line 69 of file pattern_piece_tool.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 120 of file pattern_piece_tool.h.
Constructor & Destructor Documentation
~PatternPieceTool()
virtual PatternPieceTool::~PatternPieceTool () virtual
PatternPieceTool()
PatternPieceTool::PatternPieceTool (VAbstractPattern * doc, VContainer * data, const quint32 & id, const Source & typeCreation, VMainGraphicsScene * scene, const QString & blockName, QGraphicsItem * parent = nullptr) private
Definition at line 1433 of file pattern_piece_tool.cpp.
References VAbstractPattern::CheckLayout(), VDataTool::data, VMainGraphicsScene::DimensionsChanged(), VAbstractTool::doc, EnableToolMove(), VMainGraphicsScene::EnableToolMove(), VContainer::GetPiece(), InitCSAPaths(), initializeAnchorPoints(), initializeNodes(), InitInternalPaths(), VPiece::isLocked(), VMainGraphicsScene::ItemClicked(), VPieceItem::itemMoved(), VGrainlineItem::itemResized(), VTextGraphicsItem::itemResized(), VTextGraphicsItem::itemRotated(), VGrainlineItem::itemRotated(), VMainGraphicsScene::LanguageChanged(), m_dataLabel, m_grainLine, m_patternInfo, m_pieceScene, RefreshGeometry(), ResetChildren(), retranslateUi(), SaveMoveGrainline(), SaveMovePattern(), saveMovePiece(), savePieceRotation(), SaveResizeGrainline(), SaveResizePattern(), saveResizePiece(), SaveRotateGrainline(), SaveRotationPattern(), ToolCreation(), VAbstractPattern::UpdatePatternLabel(), UpdatePatternLabel(), and updatePieceDetails().
Referenced by Create().
Member Function Documentation
addAnchors()
void PatternPieceTool::addAnchors (VAbstractPattern * doc, QDomElement & domElement, const QVector< quint32 > & anchors) static
Definition at line 328 of file pattern_piece_tool.cpp.
References VAbstractTool::doc, TagAnchors, and TagRecord.
Referenced by UnionTool::addPiece(), AddToFile(), SavePieceOptions::redo(), RefreshDataInFile(), and SavePieceOptions::undo().
AddAttributes()
void PatternPieceTool::AddAttributes (VAbstractPattern * doc, QDomElement & domElement, quint32 id, const VPiece & piece) static
Definition at line 251 of file pattern_piece_tool.cpp.
References AttrForbidFlipping, AttrHideSeamLine, VDomDocument::AttrId, AttrInLayout, AttrMx, AttrMy, AttrName, AttrPieceColor, AttrPieceFill, AttrPieceLocked, AttrSeamAllowance, AttrSeamAllowanceBuiltIn, AttrUnited, AttrVersion, VAbstractPattern::AttrWidth, VAbstractTool::doc, VAbstractPiece::getColor(), VAbstractPiece::getFill(), VAbstractPiece::GetMx(), VAbstractPiece::GetMy(), VAbstractPiece::GetName(), VPiece::getSeamAllowanceWidthFormula(), VAbstractPiece::IsForbidFlipping(), VAbstractPiece::isHideSeamLine(), VPiece::isInLayout(), VPiece::isLocked(), VAbstractPiece::IsSeamAllowance(), VAbstractPiece::IsSeamAllowanceBuiltIn(), VPiece::IsUnited(), pieceVersion, qApp, SCASSERT, and VDomDocument::SetAttribute().
Referenced by AddToFile(), SavePieceOptions::redo(), and SavePieceOptions::undo().
AddCSARecord()
void PatternPieceTool::AddCSARecord (VAbstractPattern * doc, QDomElement & domElement, const CustomSARecord & record) static
Definition at line 283 of file pattern_piece_tool.cpp.
References VAbstractPattern::AttrEnd, VAbstractPattern::AttrIncludeAs, VAbstractPattern::AttrNodeReverse, VAbstractPattern::AttrPath, VAbstractPattern::AttrStart, VAbstractTool::doc, CustomSARecord::endPoint, CustomSARecord::includeType, CustomSARecord::path, CustomSARecord::reverse, VDomDocument::SetAttribute(), CustomSARecord::startPoint, and TagRecord.
Referenced by AddCSARecords().
AddCSARecords()
void PatternPieceTool::AddCSARecords (VAbstractPattern * doc, QDomElement & domElement, const QVector< CustomSARecord > & records) static
Definition at line 297 of file pattern_piece_tool.cpp.
References AddCSARecord(), VAbstractTool::doc, and TagCSA.
Referenced by UnionTool::addPiece(), AddToFile(), SavePieceOptions::redo(), RefreshDataInFile(), and SavePieceOptions::undo().
AddGrainline()
void PatternPieceTool::AddGrainline (VAbstractPattern * doc, QDomElement & domElement, const VPiece & piece) static
Definition at line 440 of file pattern_piece_tool.cpp.
References VAbstractPattern::AttrArrows, AttrBottomAnchorPoint, AttrCenterAnchor, AttrLength, AttrMx, AttrMy, VAbstractPattern::AttrRotation, AttrTopAnchorPoint, VAbstractPattern::AttrVisible, VDataTool::data, VAbstractTool::doc, VPiece::GetGrainlineGeometry(), NULL_ID, VDomDocument::SetAttribute(), and VAbstractPattern::TagGrainline.
Referenced by AddToFile(), SavePieceOptions::redo(), RefreshDataInFile(), and SavePieceOptions::undo().
AddInternalPaths()
void PatternPieceTool::AddInternalPaths (VAbstractPattern * doc, QDomElement & domElement, const QVector< quint32 > & paths) static
Definition at line 312 of file pattern_piece_tool.cpp.
References VAbstractPattern::AttrPath, VAbstractTool::doc, VDomDocument::SetAttribute(), TagIPaths, and TagRecord.
Referenced by UnionTool::addPiece(), AddToFile(), SavePieceOptions::redo(), RefreshDataInFile(), and SavePieceOptions::undo().
AddPatternInfo()
void PatternPieceTool::AddPatternInfo (VAbstractPattern * doc, QDomElement & domElement, const VPiece & piece) static
Definition at line 397 of file pattern_piece_tool.cpp.
References AttrBottomRightAnchor, AttrCenterAnchor, AttrFont, AttrHeight, AttrMx, AttrMy, VAbstractPattern::AttrRotation, AttrTopLeftAnchor, VAbstractPattern::AttrVisible, VAbstractPattern::AttrWidth, VDataTool::data, VAbstractTool::doc, VPiece::GetPatternInfo(), NULL_ID, VDomDocument::SetAttribute(), and VAbstractPattern::TagPatternInfo.
Referenced by AddToFile(), SavePieceOptions::redo(), RefreshDataInFile(), and SavePieceOptions::undo().
AddPatternPieceData()
void PatternPieceTool::AddPatternPieceData (VAbstractPattern * doc, QDomElement & domElement, const VPiece & piece) static
Definition at line 344 of file pattern_piece_tool.cpp.
References VAbstractPattern::AttrAnnotation, AttrBottomRightAnchor, AttrCenterAnchor, VAbstractPattern::AttrFoldPosition, AttrFont, AttrHeight, VAbstractPattern::AttrLetter, AttrMx, AttrMy, VAbstractPattern::AttrOnFold, VAbstractPattern::AttrOrientation, VAbstractPattern::AttrQuantity, VAbstractPattern::AttrRotation, VAbstractPattern::AttrRotationWay, VAbstractPattern::AttrTilt, AttrTopLeftAnchor, VAbstractPattern::AttrVisible, VAbstractPattern::AttrWidth, VDataTool::data, VAbstractTool::doc, VPiece::GetPatternPieceData(), NULL_ID, VDomDocument::SetAttribute(), VDomDocument::SetLabelTemplate(), and VAbstractPattern::TagData.
Referenced by AddToFile(), SavePieceOptions::redo(), RefreshDataInFile(), and SavePieceOptions::undo().
AddToFile()
void PatternPieceTool::AddToFile () protected virtual
AddToFile add tag with Information about tool into file.
Implements VAbstractTool.
Definition at line 967 of file pattern_piece_tool.cpp.
References addAnchors(), AddAttributes(), AddCSARecords(), AddGrainline(), AddInternalPaths(), VAbstractTool::AddNodes(), AddPatternInfo(), AddPatternPieceData(), VDataTool::data, VAbstractTool::doc, VPiece::getAnchors(), VPiece::GetCustomSARecords(), VPiece::GetInternalPaths(), VContainer::GetPiece(), getTagName(), m_blockName, VAbstractTool::m_id, VAbstractPattern::NeedFullParsing(), VUndoCommand::NeedFullParsing(), and qApp.
Referenced by ToolCreation().
AllowHover
void PatternPieceTool::AllowHover (bool enabled) virtual slot
Definition at line 555 of file pattern_piece_tool.cpp.
Referenced by Create().
AllowSelecting
void PatternPieceTool::AllowSelecting (bool enabled) virtual slot
Definition at line 561 of file pattern_piece_tool.cpp.
Referenced by Create().
boundingRect()
QRectF PatternPieceTool::boundingRect () const virtual
Definition at line 941 of file pattern_piece_tool.cpp.
References m_pieceRect.
Referenced by itemChange().
contextMenuEvent()
void PatternPieceTool::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected virtual
Definition at line 1160 of file pattern_piece_tool.cpp.
References VDataTool::_referens, VDataTool::data, deleteTool(), editPieceProperties(), VPiece::GetGrainlineGeometry(), VPiece::GetPatternInfo(), VPiece::GetPatternPieceData(), VContainer::GetPiece(), VAbstractPiece::IsForbidFlipping(), VAbstractPiece::isHideSeamLine(), VPiece::isInLayout(), VPiece::isLocked(), VAbstractPiece::IsSeamAllowance(), VAbstractFloatItemData::IsVisible(), lowerItemToBottom(), VAbstractTool::m_id, VAbstractTool::m_suppressContextMenu, qApp, raiseItemToTop(), renamePiece(), toggleFlipping(), toggleGrainline(), toggleInLayout(), togglePatternLabel(), togglePieceLabel(), togglePieceLock(), toggleSeamAllowance(), and toggleSeamLine().
Create() [1/2]
PatternPieceTool * PatternPieceTool::Create (QSharedPointer< DialogTool > dialog, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data) static
Definition at line 123 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, FromGui, FullParse, VInteractiveTool::m_dialog, VAbstractTool::PrepareNodes(), qApp, and SCASSERT.
Referenced by QT_WARNING_POP::createUnion(), and VPattern::parsePieceElement().
Create() [2/2]
PatternPieceTool * PatternPieceTool::Create (quint32 id, VPiece newPiece, QString & width, VMainGraphicsScene * scene, VAbstractPattern * doc, VContainer * data, const Document & parse, const Source & typeCreation, const QString & blockName = QString()) static
Definition at line 145 of file pattern_piece_tool.cpp.
References VContainer::AddPiece(), VAbstractTool::AddRecord(), VAbstractPattern::AddTool(), VContainer::AddVariable(), AllowHover(), AllowSelecting(), VAbstractTool::CheckFormula(), VMainGraphicsScene::chosenItem(), VAbstractTool::chosenTool(), currentSeamAllowance, VDataTool::data, VAbstractTool::doc, VMainGraphicsScene::EnableDetailItemHover(), VMainGraphicsScene::EnableDetailItemSelection(), FromGui, FromTool, FullParse, VAbstractPiece::GetSAWidth(), Highlight(), VMainGraphicsScene::highlightPiece(), PatternPieceTool(), Piece, pieceLockedChanged(), VMainGraphicsScene::pieceLockedChanged(), VContainer::RemoveVariable(), VPiece::setSeamAllowanceWidthFormula(), VContainer::UpdatePiece(), and VAbstractPattern::UpdateToolData().
deleteTool()
void PatternPieceTool::deleteTool (bool ask = true) protected virtual
deleteTool full delete object form scene and file.
Reimplemented from VAbstractTool.
Definition at line 1866 of file pattern_piece_tool.cpp.
References VAbstractTool::ConfirmDeletion(), VDataTool::data, VAbstractTool::doc, m_dataLabel, m_grainLine, VAbstractTool::m_id, m_patternInfo, m_pieceScene, VAbstractPattern::NeedFullParsing(), VUndoCommand::NeedFullParsing(), and qApp.
Referenced by contextMenuEvent(), keyReleaseEvent(), and Remove().
editPieceProperties
void PatternPieceTool::editPieceProperties () slot
editPieceProperties - routine to edit pattern piece properties .
Definition at line 1983 of file pattern_piece_tool.cpp.
References DialogTool::DialogApplied(), DialogTool::DialogClosed(), VInteractiveTool::FullUpdateFromGuiApply(), VInteractiveTool::FullUpdateFromGuiOk(), VAbstractTool::getData(), VInteractiveTool::m_dialog, VAbstractTool::m_id, qApp, and SetDialog().
Referenced by PiecesWidget::cellDoubleClicked(), contextMenuEvent(), and keyReleaseEvent().
EnableToolMove
void PatternPieceTool::EnableToolMove (bool move) slot
Definition at line 509 of file pattern_piece_tool.cpp.
References VPiecePath::at(), VDataTool::data, VNodePoint::EnableToolMove(), VPieceNode::GetId(), VPiece::GetPath(), VContainer::GetPiece(), VAbstractPattern::getTool(), VPieceNode::GetTypeTool(), m_dataLabel, m_grainLine, VAbstractTool::m_id, m_patternInfo, NodePoint, and SCASSERT.
Referenced by PatternPieceTool(), and togglePieceLock().
FindGrainlineGeometry()
VPieceItem::MoveTypes PatternPieceTool::FindGrainlineGeometry (const VGrainlineData & geom, qreal & length, qreal & rotationAngle, QPointF & pos) private
Definition at line 1685 of file pattern_piece_tool.cpp.
References VPieceItem::AllModifications, VDataTool::data, VPieceItem::Error, Calculator::EvalFormula(), FromPixel(), VContainer::GeometricObject(), VContainer::GetPatternUnit(), qmu::QmuTokenParser::IsSingle(), VPieceItem::NotMovable, NULL_ID, ToPixel(), and VFuzzyComparePossibleNulls().
Referenced by UpdateGrainline().
FindLabelGeometry()
VPieceItem::MoveTypes PatternPieceTool::FindLabelGeometry (const VPatternLabelData & labelData, qreal & rotationAngle, qreal & labelWidth, qreal & labelHeight, QPointF & pos) private
Definition at line 1582 of file pattern_piece_tool.cpp.
References VPieceItem::AllModifications, VPatternLabelData::bottomRightAnchorPoint(), VPatternLabelData::centerAnchorPoint(), VDataTool::data, VPieceItem::Error, Calculator::EvalFormula(), FromPixel(), VContainer::GeometricObject(), VPatternLabelData::GetLabelHeight(), VPatternLabelData::GetLabelWidth(), VContainer::GetPatternUnit(), VAbstractFloatItemData::GetPos(), VPatternLabelData::GetRotation(), qmu::QmuTokenParser::IsSingle(), NULL_ID, ToPixel(), and VPatternLabelData::topLeftAnchorPoint().
Referenced by PrepareLabelData().
FullUpdateFromFile
void PatternPieceTool::FullUpdateFromFile () virtual slot
Definition at line 502 of file pattern_piece_tool.cpp.
References RefreshGeometry(), and UpdateExcludeState().
getTagName()
QString PatternPieceTool::getTagName () const virtual
Implements VAbstractTool.
Definition at line 483 of file pattern_piece_tool.cpp.
References VAbstractPattern::TagPiece.
Referenced by AddToFile(), and RefreshDataInFile().
GroupVisibility()
void PatternPieceTool::GroupVisibility (quint32 object, bool visible) virtual
Implements VDataTool.
Definition at line 495 of file pattern_piece_tool.cpp.
Highlight
void PatternPieceTool::Highlight (quint32 id) slot
Definition at line 614 of file pattern_piece_tool.cpp.
References VAbstractTool::m_id, and RefreshGeometry().
Referenced by Create().
hoverEnterEvent()
void PatternPieceTool::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected virtual
Definition at line 1139 of file pattern_piece_tool.cpp.
References cursorArrowOpenHand, and SetItemOverrideCursor().
hoverLeaveEvent()
void PatternPieceTool::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected virtual
Definition at line 1149 of file pattern_piece_tool.cpp.
InitCSAPaths()
void PatternPieceTool::InitCSAPaths (const VPiece & piece) private
Definition at line 1819 of file pattern_piece_tool.cpp.
References VAbstractTool::doc, VPiece::GetCustomSARecords(), and VAbstractPattern::IncrementReferens().
Referenced by PatternPieceTool().
initializeAnchorPoints()
void PatternPieceTool::initializeAnchorPoints (const VPiece & piece) private
Definition at line 1857 of file pattern_piece_tool.cpp.
References VAbstractTool::doc, VPiece::getAnchors(), and VAbstractPattern::IncrementReferens().
Referenced by PatternPieceTool().
initializeNode()
void PatternPieceTool::initializeNode (const VPieceNode & node, VMainGraphicsScene * scene, VContainer * data, VAbstractPattern * doc, PatternPieceTool * parent) static private
Definition at line 1783 of file pattern_piece_tool.cpp.
References VMainGraphicsScene::chosenItem(), VAbstractTool::chosenTool(), VDataTool::data, VAbstractTool::doc, VContainer::GetGObject(), VPieceNode::GetId(), VAbstractPattern::getTool(), VPieceNode::GetTypeTool(), VAbstractPattern::IncrementReferens(), VPieceNode::isExcluded(), Item, NodeArc, NodeElArc, NodePoint, NodeSpline, NodeSplinePath, SCASSERT, VAbstractNode::SetExluded(), and VAbstractNode::SetParentType().
Referenced by initializeNodes(), and insertNodes().
initializeNodes()
void PatternPieceTool::initializeNodes (const VPiece & piece, VMainGraphicsScene * scene) private
Definition at line 1774 of file pattern_piece_tool.cpp.
References VPiecePath::at(), VDataTool::data, VAbstractTool::doc, VPiece::GetPath(), and initializeNode().
Referenced by PatternPieceTool().
InitInternalPaths()
void PatternPieceTool::InitInternalPaths (const VPiece & piece) private
Definition at line 1828 of file pattern_piece_tool.cpp.
References VAbstractTool::doc, VAbstractTool::getData(), VPiece::GetInternalPaths(), VPiecePath::GetPenType(), VContainer::GetPiecePath(), VAbstractPattern::getTool(), VAbstractPattern::IncrementReferens(), VPiecePath::IsCutPath(), Item, Mm, qApp, scaleWidth(), SCASSERT, sceneScale(), and ToPixel().
Referenced by PatternPieceTool().
insertNodes()
void PatternPieceTool::insertNodes (const QVector< VPieceNode > & nodes, quint32 pieceId, VMainGraphicsScene * scene, VContainer * data, VAbstractPattern * doc) static
Definition at line 204 of file pattern_piece_tool.cpp.
References VPiecePath::Append(), VDataTool::data, VAbstractTool::doc, VPiece::GetPath(), VContainer::GetPiece(), VAbstractPattern::getTool(), initializeNode(), VAbstractPattern::LiteParseTree(), VUndoCommand::NeedLiteParsing(), NULL_ID, VAbstractTool::PrepareNode(), qApp, SavePieceOptions, SCASSERT, and VContainer::UpdatePiece().
Referenced by MainWindow::ClosedInsertNodesDialog().
itemChange()
QVariant PatternPieceTool::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Definition at line 1023 of file pattern_piece_tool.cpp.
References boundingRect(), VDataTool::data, VAbstractTool::doc, VContainer::GetPiece(), VMainGraphicsScene::getScenePos(), VAbstractTool::m_id, MovePiece, qApp, RefreshGeometry(), SCASSERT, sceneScale(), VMainGraphicsView::SceneVisibleArea(), VAbstractPiece::SetMx(), VAbstractPiece::SetMy(), and VContainer::UpdatePiece().
keyReleaseEvent()
void PatternPieceTool::keyReleaseEvent (QKeyEvent * event) protected virtual
Definition at line 1302 of file pattern_piece_tool.cpp.
References VDataTool::data, deleteTool(), editPieceProperties(), VPiece::GetGrainlineGeometry(), VPiece::GetPatternInfo(), VPiece::GetPatternPieceData(), VContainer::GetPiece(), VAbstractPiece::IsForbidFlipping(), VAbstractPiece::isHideSeamLine(), VPiece::isInLayout(), VPiece::isLocked(), VAbstractPiece::IsSeamAllowance(), VAbstractFloatItemData::IsVisible(), lowerItemToBottom(), VAbstractTool::m_id, qApp, raiseItemToTop(), renamePiece(), toggleFlipping(), toggleGrainline(), toggleInLayout(), togglePatternLabel(), togglePieceLabel(), togglePieceLock(), toggleSeamAllowance(), and toggleSeamLine().
lowerItemToBottom()
void PatternPieceTool::lowerItemToBottom (QGraphicsItem * item) private
Definition at line 2182 of file pattern_piece_tool.cpp.
References m_pieceScene.
Referenced by contextMenuEvent(), and keyReleaseEvent().
mousePressEvent()
void PatternPieceTool::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
Definition at line 1100 of file pattern_piece_tool.cpp.
References VAbstractTool::chosenTool(), cursorArrowCloseHand, VAbstractTool::doc, VAbstractTool::m_id, Piece, VAbstractPattern::selectedPiece(), and SetItemOverrideCursor().
mouseReleaseEvent()
void PatternPieceTool::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
Definition at line 1129 of file pattern_piece_tool.cpp.
References cursorArrowOpenHand, and SetItemOverrideCursor().
paint()
void PatternPieceTool::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
VToolDetail::paint draws a bounding box around piece, if one of its text or grainline items is not idle.
Definition at line 881 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::fills(), VAbstractPiece::getColor(), VAbstractPiece::getFill(), VContainer::GetPiece(), VPieceItem::IsIdle(), VAbstractPiece::IsSeamAllowance(), VAbstractPiece::IsSeamAllowanceBuiltIn(), lineTypeToPenStyle(), m_cutLine, m_dataLabel, m_grainLine, VAbstractTool::m_id, m_notches, m_patternInfo, m_seamLine, Mm, qApp, scaleWidth(), sceneScale(), and ToPixel().
pieceLockedChanged
void PatternPieceTool::pieceLockedChanged (quint32 id, bool lock) slot
Definition at line 531 of file pattern_piece_tool.cpp.
References VPiecePath::at(), VDataTool::data, VNodePoint::EnableToolMove(), VPieceNode::GetId(), VPiece::GetPath(), VContainer::GetPiece(), VAbstractPattern::getTool(), VPieceNode::GetTypeTool(), m_dataLabel, m_grainLine, VAbstractTool::m_id, m_patternInfo, NodePoint, and SCASSERT.
Referenced by Create().
PrepareLabelData()
bool PatternPieceTool::PrepareLabelData (const VPatternLabelData & labelData, VTextGraphicsItem * labelItem, QPointF & pos, qreal & labelAngle) private
Definition at line 1920 of file pattern_piece_tool.cpp.
References VDataTool::data, VPieceItem::Error, FindLabelGeometry(), VPatternLabelData::getFontSize(), MIN_FONT_SIZE, qApp, SCASSERT, VTextGraphicsItem::setFont(), VPieceItem::SetMoveType(), VTextGraphicsItem::setSize(), ToPixel(), and type().
Referenced by UpdatePatternLabel(), and UpdatePieceLabel().
raiseItemToTop()
void PatternPieceTool::raiseItemToTop (QGraphicsItem * item) private
Definition at line 2173 of file pattern_piece_tool.cpp.
References m_pieceScene.
Referenced by contextMenuEvent(), and keyReleaseEvent().
RefreshDataInFile()
void PatternPieceTool::RefreshDataInFile () protected virtual
RefreshDataInFile refresh attributes in file. If attributes don't exist create them.
Reimplemented from VAbstractTool.
Definition at line 991 of file pattern_piece_tool.cpp.
References addAnchors(), AddCSARecords(), AddGrainline(), AddInternalPaths(), VAbstractTool::AddNodes(), AddPatternInfo(), AddPatternPieceData(), AttrVersion, CONVERTER_VERSION_CHECK, VDataTool::data, VAbstractTool::doc, VDomDocument::elementById(), VPiece::getAnchors(), VPiece::GetCustomSARecords(), VPiece::GetInternalPaths(), VDomDocument::GetParametrUInt(), VContainer::GetPiece(), getTagName(), VAbstractTool::m_id, VPatternConverter::PatternMinVer, pieceVersion, VDomDocument::RemoveAllChildren(), and VDomDocument::SetAttribute().
Referenced by ToolCreation().
RefreshGeometry()
void PatternPieceTool::RefreshGeometry ()
Definition at line 1507 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::getData(), VAbstractPiece::GetMx(), VAbstractPiece::GetMy(), VPiece::getNotchesPath(), VContainer::GetPiece(), VAbstractPiece::isHideSeamLine(), VAbstractPiece::IsSeamAllowance(), VAbstractPiece::IsSeamAllowanceBuiltIn(), m_cutLine, m_cutPath, VAbstractTool::m_id, m_mainPath, m_notches, m_pieceRect, m_seamLine, VPiece::MainPathPath(), qApp, VPiece::SeamAllowancePath(), and VPiece::SeamAllowancePoints().
Referenced by FullUpdateFromFile(), Highlight(), itemChange(), and PatternPieceTool().
Remove()
void PatternPieceTool::Remove (bool ask)
Definition at line 190 of file pattern_piece_tool.cpp.
References deleteTool().
Referenced by QT_WARNING_POP::createUnion().
renamePiece()
void PatternPieceTool::renamePiece (VPiece piece) private
renamePiece - routine to rename pattern piece.
Definition at line 2132 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VAbstractPiece::GetName(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VAbstractPiece::SetName(), and showStatus().
Referenced by contextMenuEvent(), and keyReleaseEvent().
ResetChildren
void PatternPieceTool::ResetChildren (QGraphicsItem * pItem) virtual slot
Definition at line 567 of file pattern_piece_tool.cpp.
References VDataTool::data, VPiece::GetGrainlineGeometry(), VPiece::GetPatternInfo(), VPiece::GetPatternPieceData(), VContainer::GetPiece(), VAbstractFloatItemData::IsVisible(), m_dataLabel, m_grainLine, VAbstractTool::m_id, m_patternInfo, and VPieceItem::Reset().
Referenced by PatternPieceTool().
retranslateUi
void PatternPieceTool::retranslateUi () virtual slot
Definition at line 607 of file pattern_piece_tool.cpp.
References UpdatePatternLabel(), and UpdatePieceLabel().
Referenced by PatternPieceTool().
SaveDialogChange()
void PatternPieceTool::SaveDialogChange () protected virtual
Implements VInteractiveTool.
Definition at line 1567 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, PatternPieceDialog::GetPiece(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VInteractiveTool::m_dialog, VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, SCASSERT, and UpdatePieceLabel().
SaveMoveGrainline
void PatternPieceTool::SaveMoveGrainline (const QPointF & ptPos) protected slot
Definition at line 835 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VPiece::GetGrainlineGeometry(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, and VAbstractFloatItemData::SetPos().
Referenced by PatternPieceTool().
SaveMovePattern
void PatternPieceTool::SaveMovePattern (const QPointF & ptPos) protected slot
SaveMovePattern saves the pattern label position.
Definition at line 780 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VPiece::GetPatternInfo(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, and VAbstractFloatItemData::SetPos().
Referenced by PatternPieceTool().
saveMovePiece
void PatternPieceTool::saveMovePiece (const QPointF & ptPos) protected slot
saveMovePiece saves the move piece operation to the undo stack
Definition at line 720 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VPiece::GetPatternPieceData(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, and VAbstractFloatItemData::SetPos().
Referenced by PatternPieceTool().
savePieceRotation
void PatternPieceTool::savePieceRotation (qreal dRot) protected slot
savePieceRotation saves the rotation piece label operation to the undo stack
Definition at line 757 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VTextGraphicsItem::getFontSize(), VPiece::GetPatternPieceData(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), m_dataLabel, VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VPatternLabelData::SetFontSize(), VAbstractFloatItemData::SetPos(), and VPatternLabelData::SetRotation().
Referenced by PatternPieceTool().
SaveResizeGrainline
void PatternPieceTool::SaveResizeGrainline (qreal dLength) protected slot
Definition at line 849 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, FromPixel(), VPiece::GetGrainlineGeometry(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), m_grainLine, VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VGrainlineData::SetLength(), and VAbstractFloatItemData::SetPos().
Referenced by PatternPieceTool().
SaveResizePattern
void PatternPieceTool::SaveResizePattern (qreal dLabelW, int iFontSize) protected slot
: SaveResizePattern saves the pattern label width and font size
Definition at line 796 of file pattern_piece_tool.cpp.
References VPieceItem::boundingRect(), VDataTool::data, VAbstractTool::doc, FromPixel(), VPiece::GetPatternInfo(), VContainer::GetPatternUnit(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, m_patternInfo, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VPatternLabelData::SetFontSize(), VPatternLabelData::SetLabelHeight(), and VPatternLabelData::SetLabelWidth().
Referenced by PatternPieceTool().
saveResizePiece
void PatternPieceTool::saveResizePiece (qreal dLabelW, int iFontSize) protected slot
saveResizePiece saves the resize piece label operation to the undo stack
Definition at line 736 of file pattern_piece_tool.cpp.
References VPieceItem::boundingRect(), VDataTool::data, VAbstractTool::doc, FromPixel(), VPiece::GetPatternPieceData(), VContainer::GetPatternUnit(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), m_dataLabel, VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VPatternLabelData::SetFontSize(), VPatternLabelData::SetLabelHeight(), and VPatternLabelData::SetLabelWidth().
Referenced by PatternPieceTool().
SaveRotateGrainline
void PatternPieceTool::SaveRotateGrainline (qreal dRot, const QPointF & ptPos) protected slot
Definition at line 864 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VPiece::GetGrainlineGeometry(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VAbstractFloatItemData::SetPos(), and VGrainlineData::SetRotation().
Referenced by PatternPieceTool().
SaveRotationPattern
void PatternPieceTool::SaveRotationPattern (qreal dRot) protected slot
Definition at line 814 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VTextGraphicsItem::getFontSize(), VPiece::GetPatternInfo(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, m_patternInfo, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VPatternLabelData::SetFontSize(), VAbstractFloatItemData::SetPos(), and VPatternLabelData::SetRotation().
Referenced by PatternPieceTool().
SetDialog()
void PatternPieceTool::SetDialog () protected virtual
Definition at line 1423 of file pattern_piece_tool.cpp.
References VDataTool::data, VInteractiveTool::m_dialog, VAbstractTool::m_id, and SCASSERT.
Referenced by editPieceProperties().
SetVisualization()
virtual void PatternPieceTool::SetVisualization () inline protected virtual
Implements VAbstractTool.
Definition at line 168 of file pattern_piece_tool.h.
shape()
QPainterPath PatternPieceTool::shape () const virtual
Definition at line 954 of file pattern_piece_tool.cpp.
References ItemShapeFromPath(), m_cutPath, and m_mainPath.
showStatus()
void PatternPieceTool::showStatus (QString toolTip) private
Definition at line 2164 of file pattern_piece_tool.cpp.
References qApp, SCASSERT, and VAbstractMainWindow::ShowToolTip().
Referenced by renamePiece(), toggleFlipping(), toggleGrainline(), togglePatternLabel(), togglePieceLabel(), toggleSeamAllowance(), and toggleSeamLine().
ShowVisualization()
void PatternPieceTool::ShowVisualization (bool show) virtual
Implements VAbstractTool.
Definition at line 489 of file pattern_piece_tool.cpp.
toggleFlipping()
void PatternPieceTool::toggleFlipping (bool checked) private
toggleFlipping - routine to toggle forbidding flipping.
Parameters
checked - true if flipping is forbidden.
Definition at line 2024 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VAbstractPiece::SetForbidFlipping(), and showStatus().
Referenced by contextMenuEvent(), and keyReleaseEvent().
toggleGrainline()
void PatternPieceTool::toggleGrainline (bool checked) private
toggleGrainline - routine to toggle the visibility of the piece grainline.
Parameters
checked - true if grainline is visible.
Definition at line 2078 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VPiece::GetGrainlineGeometry(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VAbstractFloatItemData::SetVisible(), and showStatus().
Referenced by contextMenuEvent(), and keyReleaseEvent().
toggleInLayout()
void PatternPieceTool::toggleInLayout (bool checked) private
toggleInLayout - routine to toggle if pattern piece is included and visible in layout.
Parameters
checked - true if piece is included.
Definition at line 2000 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VAbstractTool::m_id, qApp, TogglePieceInLayout, TogglePieceInLayout::updateList(), and VAbstractPattern::updatePieceList().
Referenced by contextMenuEvent(), and keyReleaseEvent().
togglePatternLabel()
void PatternPieceTool::togglePatternLabel (bool checked) private
togglePatternLabel - routine to toggle the visibility of the pattern label.
Parameters
checked - true if pattern label is visible.
Definition at line 2096 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VPiece::GetPatternInfo(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VAbstractFloatItemData::SetVisible(), and showStatus().
Referenced by contextMenuEvent(), and keyReleaseEvent().
togglePieceLabel()
void PatternPieceTool::togglePieceLabel (bool checked) private
togglePieceLabel - routine to toggle the visibility of the piece label.
Parameters
checked - true if piece label is visible.
Definition at line 2114 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VPiece::GetPatternPieceData(), VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VAbstractFloatItemData::SetVisible(), and showStatus().
Referenced by contextMenuEvent(), and keyReleaseEvent().
togglePieceLock()
void PatternPieceTool::togglePieceLock (bool checked) private
togglePieceLock - routine to toggle if pattern piece is locked and editiable.
Parameters
checked - true if piece is locked.
Definition at line 2011 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, EnableToolMove(), VAbstractTool::m_id, qApp, TogglePieceLock, TogglePieceLock::updateList(), and VAbstractPattern::updatePieceList().
Referenced by contextMenuEvent(), and keyReleaseEvent().
toggleSeamAllowance()
void PatternPieceTool::toggleSeamAllowance (bool checked) private
toggleSeamAllowance - routine to toggle the visibility of the seam allowance.
Parameters
checked - true if seam allowance is visible.
Definition at line 2060 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VAbstractPiece::SetSeamAllowance(), and showStatus().
Referenced by contextMenuEvent(), and keyReleaseEvent().
toggleSeamLine()
void PatternPieceTool::toggleSeamLine (bool checked) private
toggleSeamLine - routine to toggle the visibility of the seam line.
Parameters
checked - true if seam line is visible.
Definition at line 2042 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VContainer::GetPiece(), VAbstractPattern::LiteParseTree(), VAbstractTool::m_id, VUndoCommand::NeedLiteParsing(), qApp, SavePieceOptions, VAbstractPiece::setHideSeamLine(), and showStatus().
Referenced by contextMenuEvent(), and keyReleaseEvent().
ToolCreation()
void PatternPieceTool::ToolCreation (const Source & typeCreation) protected virtual
Reimplemented from VAbstractTool.
Definition at line 1903 of file pattern_piece_tool.cpp.
References AddToFile(), FromGui, FromTool, qApp, and RefreshDataInFile().
Referenced by PatternPieceTool().
type()
virtual int PatternPieceTool::type () const inline virtual
Definition at line 119 of file pattern_piece_tool.h.
References Type.
Referenced by PrepareLabelData(), and UpdateGrainline().
UpdateAll
void PatternPieceTool::UpdateAll () virtual slot
Definition at line 600 of file pattern_piece_tool.cpp.
References m_pieceScene.
UpdateExcludeState()
void PatternPieceTool::UpdateExcludeState () private
Definition at line 1489 of file pattern_piece_tool.cpp.
References VPiecePath::at(), VDataTool::data, VPieceNode::GetId(), VPiece::GetPath(), VContainer::GetPiece(), VAbstractPattern::getTool(), VPieceNode::GetTypeTool(), VPieceNode::isExcluded(), VAbstractTool::m_id, NodePoint, SCASSERT, and VAbstractNode::SetExluded().
Referenced by FullUpdateFromFile().
UpdateGrainline
void PatternPieceTool::UpdateGrainline () slot
VToolDetail::UpdateGrainline updates the grain line item.
Definition at line 685 of file pattern_piece_tool.cpp.
References VDataTool::data, VPieceItem::Error, FindGrainlineGeometry(), VPiece::GetGrainlineGeometry(), VContainer::GetPiece(), m_grainLine, VAbstractTool::m_id, qApp, VPieceItem::SetMoveType(), ToPixel(), type(), and VGrainlineItem::UpdateGeometry().
Referenced by updatePieceDetails().
UpdateLabelItem()
void PatternPieceTool::UpdateLabelItem (VTextGraphicsItem * labelItem, QPointF pos, qreal labelAngle) private
Definition at line 1958 of file pattern_piece_tool.cpp.
References VPieceItem::boundingRect(), VTextGraphicsItem::getTextLines(), VTextGraphicsItem::isContained(), SCASSERT, and VTextGraphicsItem::Update().
Referenced by UpdatePatternLabel(), and UpdatePieceLabel().
UpdatePatternLabel
void PatternPieceTool::UpdatePatternLabel () slot
UpdatePatternLabel updates the pattern info label.
Definition at line 658 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractTool::doc, VAbstractPiece::GetName(), VPiece::GetPatternInfo(), VContainer::GetPiece(), VAbstractTool::m_id, m_patternInfo, PrepareLabelData(), qApp, VTextGraphicsItem::updateData(), and UpdateLabelItem().
Referenced by PatternPieceTool(), retranslateUi(), and updatePieceDetails().
updatePieceDetails
void PatternPieceTool::updatePieceDetails () slot
Definition at line 620 of file pattern_piece_tool.cpp.
References UpdateGrainline(), UpdatePatternLabel(), and UpdatePieceLabel().
Referenced by PatternPieceTool().
UpdatePieceLabel
void PatternPieceTool::UpdatePieceLabel () slot
UpdateLabel updates the text label, making it just big enough for the text to fit it.
Definition at line 630 of file pattern_piece_tool.cpp.
References VDataTool::data, VAbstractPiece::GetName(), VPiece::GetPatternPieceData(), VContainer::GetPiece(), VAbstractFloatItemData::IsVisible(), m_dataLabel, VAbstractTool::m_id, PrepareLabelData(), qApp, VTextGraphicsItem::updateData(), and UpdateLabelItem().
Referenced by retranslateUi(), SaveDialogChange(), and updatePieceDetails().
Member Data Documentation
AttrBottomAnchorPoint
const QString PatternPieceTool::AttrBottomAnchorPoint = QStringLiteral("bottomAnchor") static
Definition at line 101 of file pattern_piece_tool.h.
Referenced by AddGrainline(), and VPattern::ParsePieceGrainline().
AttrBottomRightAnchor
const QString PatternPieceTool::AttrBottomRightAnchor = QStringLiteral("bottomRightAnchor") static
Definition at line 98 of file pattern_piece_tool.h.
Referenced by AddPatternInfo(), AddPatternPieceData(), VPattern::ParsePieceDataTag(), and VPattern::ParsePiecePatternInfo().
AttrCenterAnchor
const QString PatternPieceTool::AttrCenterAnchor = QStringLiteral("centerAnchor") static
Definition at line 99 of file pattern_piece_tool.h.
Referenced by AddGrainline(), AddPatternInfo(), AddPatternPieceData(), VPattern::ParsePieceDataTag(), VPattern::ParsePieceGrainline(), and VPattern::ParsePiecePatternInfo().
AttrFont
const QString PatternPieceTool::AttrFont = QStringLiteral("fontSize") static
Definition at line 96 of file pattern_piece_tool.h.
Referenced by AddPatternInfo(), AddPatternPieceData(), VPattern::ParsePieceDataTag(), and VPattern::ParsePiecePatternInfo().
AttrForbidFlipping
const QString PatternPieceTool::AttrForbidFlipping = QStringLiteral("forbidFlipping") static
Definition at line 87 of file pattern_piece_tool.h.
Referenced by AddAttributes(), and VPattern::parsePieceElement().
AttrHeight
const QString PatternPieceTool::AttrHeight = QStringLiteral("height") static
Definition at line 94 of file pattern_piece_tool.h.
Referenced by AddPatternInfo(), AddPatternPieceData(), VPattern::ParsePieceDataTag(), and VPattern::ParsePiecePatternInfo().
AttrHideSeamLine
const QString PatternPieceTool::AttrHideSeamLine = QStringLiteral("hideMainPath") static
Definition at line 92 of file pattern_piece_tool.h.
Referenced by AddAttributes(), and VPattern::parsePieceElement().
AttrPieceColor
const QString PatternPieceTool::AttrPieceColor = QStringLiteral("color") static
Definition at line 88 of file pattern_piece_tool.h.
Referenced by AddAttributes(), and VPattern::parsePieceElement().
AttrPieceFill
const QString PatternPieceTool::AttrPieceFill = QStringLiteral("fill") static
Definition at line 89 of file pattern_piece_tool.h.
Referenced by AddAttributes(), and VPattern::parsePieceElement().
AttrPieceLock
const QString PatternPieceTool::AttrPieceLock = QStringLiteral("locked") static
Definition at line 90 of file pattern_piece_tool.h.
AttrSeamAllowance
const QString PatternPieceTool::AttrSeamAllowance = QStringLiteral("seamAllowance") static
Definition at line 91 of file pattern_piece_tool.h.
Referenced by AddAttributes(), and VPattern::parsePieceElement().
AttrSeamAllowanceBuiltIn
const QString PatternPieceTool::AttrSeamAllowanceBuiltIn = QStringLiteral("seamAllowanceBuiltIn") static
Definition at line 93 of file pattern_piece_tool.h.
Referenced by AddAttributes(), and VPattern::parsePieceElement().
AttrTopAnchorPoint
const QString PatternPieceTool::AttrTopAnchorPoint = QStringLiteral("topAnchor") static
Definition at line 100 of file pattern_piece_tool.h.
Referenced by AddGrainline(), and VPattern::ParsePieceGrainline().
AttrTopLeftAnchor
const QString PatternPieceTool::AttrTopLeftAnchor = QStringLiteral("topLeftAnchor") static
Definition at line 97 of file pattern_piece_tool.h.
Referenced by AddPatternInfo(), AddPatternPieceData(), VPattern::ParsePieceDataTag(), and VPattern::ParsePiecePatternInfo().
AttrUnited
const QString PatternPieceTool::AttrUnited = QStringLiteral("united") static
Definition at line 95 of file pattern_piece_tool.h.
Referenced by AddAttributes(), VPattern::getActivePatternPieces(), and VPattern::parsePieceElement().
AttrVersion
const QString PatternPieceTool::AttrVersion = QStringLiteral("version") static
Definition at line 86 of file pattern_piece_tool.h.
Referenced by AddAttributes(), VPattern::parsePieceElement(), and RefreshDataInFile().
m_blockName
QString PatternPieceTool::m_blockName private
pieceScene pointer to the scene.
Definition at line 181 of file pattern_piece_tool.h.
Referenced by AddToFile().
m_cutLine
NonScalingFillPathItem* PatternPieceTool::m_cutLine private
Definition at line 182 of file pattern_piece_tool.h.
Referenced by paint(), and RefreshGeometry().
m_cutPath
QPainterPath PatternPieceTool::m_cutPath private
Definition at line 179 of file pattern_piece_tool.h.
Referenced by RefreshGeometry(), and shape().
m_dataLabel
VTextGraphicsItem* PatternPieceTool::m_dataLabel private
Definition at line 184 of file pattern_piece_tool.h.
Referenced by deleteTool(), EnableToolMove(), paint(), PatternPieceTool(), pieceLockedChanged(), ResetChildren(), savePieceRotation(), saveResizePiece(), and UpdatePieceLabel().
m_grainLine
VGrainlineItem* PatternPieceTool::m_grainLine private
Definition at line 186 of file pattern_piece_tool.h.
Referenced by deleteTool(), EnableToolMove(), paint(), PatternPieceTool(), pieceLockedChanged(), ResetChildren(), SaveResizeGrainline(), and UpdateGrainline().
m_mainPath
QPainterPath PatternPieceTool::m_mainPath private
Definition at line 177 of file pattern_piece_tool.h.
Referenced by RefreshGeometry(), and shape().
m_notches
QGraphicsPathItem* PatternPieceTool::m_notches private
Definition at line 187 of file pattern_piece_tool.h.
Referenced by paint(), and RefreshGeometry().
m_patternInfo
VTextGraphicsItem* PatternPieceTool::m_patternInfo private
Definition at line 185 of file pattern_piece_tool.h.
Referenced by deleteTool(), EnableToolMove(), paint(), PatternPieceTool(), pieceLockedChanged(), ResetChildren(), SaveResizePattern(), SaveRotationPattern(), and UpdatePatternLabel().
m_pieceRect
QRectF PatternPieceTool::m_pieceRect private
Definition at line 178 of file pattern_piece_tool.h.
Referenced by boundingRect(), and RefreshGeometry().
m_pieceScene
VMainGraphicsScene* PatternPieceTool::m_pieceScene private
Definition at line 180 of file pattern_piece_tool.h.
Referenced by deleteTool(), lowerItemToBottom(), PatternPieceTool(), raiseItemToTop(), and UpdateAll().
m_seamLine
NonScalingFillPathItem* PatternPieceTool::m_seamLine private
Definition at line 183 of file pattern_piece_tool.h.
Referenced by paint(), and RefreshGeometry().
pieceVersion
const quint8 PatternPieceTool::pieceVersion = 2 static
Definition at line 81 of file pattern_piece_tool.h.
Referenced by AddAttributes(), and RefreshDataInFile().
TagAnchors
const QString PatternPieceTool::TagAnchors = QStringLiteral("anchors") static
Definition at line 85 of file pattern_piece_tool.h.
Referenced by addAnchors(), QT_WARNING_POP::getAnchorChildren(), QT_WARNING_POP::GetPiece2Anchors(), UnionTool::GetReferenceObjects(), VPattern::parsePieceElement(), and QT_WARNING_POP::SaveAnchorsChildren().
TagCSA
const QString PatternPieceTool::TagCSA = QStringLiteral("csa") static
Definition at line 82 of file pattern_piece_tool.h.
Referenced by AddCSARecords(), QT_WARNING_POP::GetCSAChildren(), QT_WARNING_POP::GetPiece2CSAPaths(), UnionTool::GetReferenceObjects(), VPattern::parsePieceElement(), and QT_WARNING_POP::SaveCSAChildren().
TagIPaths
const QString PatternPieceTool::TagIPaths = QStringLiteral("iPaths") static
Definition at line 84 of file pattern_piece_tool.h.
Referenced by AddInternalPaths(), QT_WARNING_POP::GetInternalPathsChildren(), QT_WARNING_POP::GetPiece2InternalPaths(), UnionTool::GetReferenceObjects(), VPattern::parsePieceElement(), and QT_WARNING_POP::SaveInternalPathsChildren().
TagRecord
const QString PatternPieceTool::TagRecord = QStringLiteral("record") static
Definition at line 83 of file pattern_piece_tool.h.
Referenced by addAnchors(), AddCSARecord(), AddInternalPaths(), and UnionTool::GetReferenceObjects().
The documentation for this class was generated from the following files:
src/libs/vtools/tools/pattern_piece_tool.h
src/libs/vtools/tools/pattern_piece_tool.cpp