Seamly2D: src/app/seamlyme/mapplication.cpp File Reference
mapplication.cpp File Reference
#include "mapplication.h"
#include "version.h"
#include "tmainwindow.h"
#include "../ifc/exception/vexceptionobjecterror.h"
#include "../ifc/exception/vexceptionbadid.h"
#include "../ifc/exception/vexceptionconversionerror.h"
#include "../ifc/exception/vexceptionemptyparameter.h"
#include "../ifc/exception/vexceptionwrongid.h"
#include "../vmisc/logging.h"
#include "../vmisc/vsysexits.h"
#include "../vmisc/diagnostic.h"
#include "../qmuparser/qmuparsererror.h"
#include <Qt>
#include <QDir>
#include <QFileOpenEvent>
#include <QLocalSocket>
#include <QResource>
#include <QTranslator>
#include <QPointer>
#include <QLocalServer>
#include <QMessageBox>
#include <iostream>
#include <QGridLayout>
#include <QSpacerItem>
#include <QThread>
#include <QStandardPaths>
#include <QCommandLineParser>
Functions
QT_WARNING_PUSH QT_WARNING_POP void noisyFailureMsgHandler (QtMsgType type, const QMessageLogContext &context, const QString &msg)
Function Documentation
noisyFailureMsgHandler()
QT_WARNING_PUSH QT_WARNING_POP void noisyFailureMsgHandler (QtMsgType type, const QMessageLogContext & context, const QString & msg) inline
Definition at line 91 of file mapplication.cpp.
References qApp, translate, vStdErr(), and vStdOut().
Referenced by MApplication::InitOptions().