Seamly2D: qmu::QmuParserBase Class Reference
qmu::QmuParserBase Class Reference abstract
Mathematical expressions parser (base parser engine).
#include <qmuparserbase.h>
Classes
class change_dec_sep
A facet class used to change decimal and thousands separator.
Public Member Functions
QmuParserBase ()
Constructor.
QmuParserBase (const QmuParserBase &a_Parser)
Copy constructor.
QmuParserBase & operator= (const QmuParserBase &a_Parser)
Assignement operator.
virtual ~QmuParserBase ()
qreal Eval () const
Calculate the result.
qreal * Eval (int &nStackSize) const
Evaluate an expression containing comma seperated subexpressions.
void Eval (qreal *results, int nBulkSize) const
int GetNumResults () const
Return the number of results on the calculation stack.
void SetExpr (const QString &a_sExpr)
Set the formula.
void SetVarFactory (facfun_type a_pFactory, void *pUserData=nullptr)
Set a function that can create variable pointer for unknown expression variables.
void ResetLocale ()
Resets the locale.
void EnableOptimizer (bool a_bIsOn=true)
Enable or disable the formula optimization feature.
void EnableBuiltInOprt (bool a_bIsOn=true)
Enable or disable the built in binary operators.
bool HasBuiltInOprt () const
Query status of built in variables.
void AddValIdent (identfun_type a_pCallback)
Add a value parsing function.
void DefineOprt (const QString &a_sName, fun_type2 a_pFun, unsigned a_iPrec=0, EOprtAssociativity a_eAssociativity=oaLEFT, bool a_bAllowOpt=false)
Define a binary operator.
void DefineConst (const QString &a_sName, qreal a_fVal)
Add a user defined constant.
void DefineStrConst (const QString &a_strName, const QString &a_strVal)
Define a new string constant.
void DefineVar (const QString &a_sName, qreal *a_pVar)
Add a user defined variable.
void DefinePostfixOprt (const QString &a_sFun, fun_type1 a_pFun, bool a_bAllowOpt=true)
Add a user defined operator.
void DefineInfixOprt (const QString &a_sName, fun_type1 a_pFun, int a_iPrec=prINFIX, bool a_bAllowOpt=true)
Add a user defined operator.
void ClearVar ()
Clear all user defined variables.
void ClearFun ()
Clear all functions.
void ClearConst ()
Clear all user defined constants.
void ClearInfixOprt ()
Clear the user defined Prefix operators.
void ClearPostfixOprt ()
Clear all user defined postfix operators.
void ClearOprt ()
Clear all user defined binary operators.
void RemoveVar (const QString &a_strVarName)
Remove a variable from internal storage.
const varmap_type & GetUsedVar () const
Return a map containing the used variables only.
const varmap_type & GetVar () const
Return a map containing the used variables only.
const valmap_type & GetConst () const
Return a map containing all parser constants.
const QString & GetExpr () const
Retrieve the formula.
const funmap_type & GetFunDef () const
Return prototypes of all parser functions.
QMap< int, QString > GetTokens () const
QMap< int, QString > GetNumbers () const
void DefineNameChars (const QString &a_szCharset)
Define the set of valid characters to be used in names of functions, variables, constants.
void DefineOprtChars (const QString &a_szCharset)
Define the set of valid characters to be used in names of binary operators and postfix operators.
void DefineInfixOprtChars (const QString &a_szCharset)
Define the set of valid characters to be used in names of infix operators.
const QString & ValidNameChars () const
Virtual function that defines the characters allowed in name identifiers.
const QString & ValidOprtChars () const
Virtual function that defines the characters allowed in operator definitions.
const QString & ValidInfixOprtChars () const
Virtual function that defines the characters allowed in infix operator definitions.
void SetArgSep (char_type cArgSep)
Set argument separator.
QChar GetArgSep () const
Get the argument separator character.
void Q_NORETURN Error (EErrorCodes a_iErrc, int a_iPos=-1, const QString &a_sTok=QString()) const
Create an error containing the parse error position.
template<typename T >
void DefineFun (const QString &a_strName, T a_pFun, bool a_bAllowOpt=true)
Define a parser function without arguments.
void setAllowSubexpressions (bool value)
QLocale getLocale () const
void setLocale (const QLocale &value)
QChar getDecimalPoint () const
void setDecimalPoint (const QChar &c)
QChar getThousandsSeparator () const
void setThousandsSeparator (const QChar &c)
Static Public Member Functions
static void EnableDebugDump (bool bDumpCmd, bool bDumpStack)
Enable the dumping of bytecode amd stack content on the console.
static QString GetVersion (EParserVersionInfo eInfo=pviFULL)
Returns the version of muparser.
static const QStringList & GetOprtDef ()
Get the default symbols used for the built in operators.
Protected Member Functions
void Init ()
Initialize user defined functions.
virtual void InitCharSets ()=0
virtual void InitFun ()=0
virtual void InitConst ()=0
virtual void InitOprt ()=0
virtual void OnDetectVar (const QString &pExpr, int &nStart, int &nEnd)
Protected Attributes
QLocale m_locale
The locale used by the parser.
QChar m_decimalPoint
QChar m_thousandsSeparator
Static Protected Attributes
static const QStringList c_DefaultOprt
Identifiers for built in binary operators.
static bool g_DbgDumpCmdCode = false
static bool g_DbgDumpStack = false
Private Types
typedef qreal(QmuParserBase::* ParseFunction) () const
Typedef for the parse functions.
typedef QVector< qreal > valbuf_type
Type used for storing an array of values.
typedef QVector< QString > stringbuf_type
Type for a vector of strings.
typedef QmuParserTokenReader token_reader_type
Typedef for the token reader.
typedef QmuParserToken< qreal, QString > token_type
Type used for parser tokens.
Private Member Functions
void Assign (const QmuParserBase &a_Parser)
Copy state of a parser object to this.
void InitTokenReader ()
Initialize the token reader.
void ReInit () const
Reset parser to string parsing mode and clear internal buffers.
void AddCallback (const QString &a_strName, const QmuParserCallback &a_Callback, funmap_type &a_Storage, const QString &a_szCharSet)
Add a function or operator callback to the parser.
void ApplyRemainingOprt (QStack< token_type > &a_stOpt, QStack< token_type > &a_stVal) const
Apply a binary operator.
void ApplyBinOprt (QStack< token_type > &a_stOpt, QStack< token_type > &a_stVal) const
Performs the necessary steps to write code for the execution of binary operators into the bytecode.
void ApplyIfElse (QStack< token_type > &a_stOpt, QStack< token_type > &a_stVal) const
void ApplyFunc (QStack< token_type > &a_stOpt, QStack< token_type > &a_stVal, int iArgCount) const
Apply a function token.
token_type ApplyStrFunc (const token_type &a_FunTok, const QVector< token_type > &a_vArg) const
Execute a function that takes a single string argument.
int GetOprtPrecedence (const token_type &a_Tok) const
Get operator priority.
EOprtAssociativity GetOprtAssociativity (const token_type &a_Tok) const
Get operator priority.
void CreateRPN () const
qreal ParseString () const
One of the two main parse functions.
qreal ParseCmdCode () const
Parse the command code.
qreal ParseCmdCodeBulk (int nOffset, int nThreadID) const
Evaluate the RPN.
void CheckName (const QString &a_sName, const QString &a_szCharSet) const
Check if a name contains invalid characters.
void CheckOprt (const QString &a_sName, const QmuParserCallback &a_Callback, const QString &a_szCharSet) const
Check if a name contains invalid characters.
void StackDump (const QStack< token_type > &a_stVal, const QStack< token_type > &a_stOprt) const
Dump stack content.
Private Attributes
ParseFunction m_pParseFormula
Pointer to the parser function.
QmuParserByteCode m_vRPN
The Bytecode class.
stringbuf_type m_vStringBuf
String buffer, used for storing string function arguments.
stringbuf_type m_vStringVarBuf
std::unique_ptr< token_reader_type > m_pTokenReader
Managed pointer to the token reader object.
funmap_type m_FunDef
Map of function names and pointers.
funmap_type m_PostOprtDef
Postfix operator callbacks.
funmap_type m_InfixOprtDef
unary infix operator.
funmap_type m_OprtDef
Binary operator callbacks.
valmap_type m_ConstDef
user constants.
strmap_type m_StrVarDef
user defined string constants
varmap_type m_VarDef
user defind variables.
bool m_bBuiltInOp
Flag that can be used for switching built in operators on and off.
QString m_sNameChars
Charset for names.
QString m_sOprtChars
Charset for postfix/ binary operator tokens.
QString m_sInfixOprtChars
Charset for infix operator tokens.
int m_nIfElseCounter
Internal counter for keeping track of nested if-then-else clauses.
valbuf_type m_vStackBuffer
This is merely a buffer used for the stack in the cmd parsing routine.
int m_nFinalResultIdx
QMap< int, QString > m_Tokens
Keep all tokens that we can translate.
QMap< int, QString > m_Numbers
Keep all numbers what exist in formula.
bool allowSubexpressions
Static Private Attributes
static const int s_MaxNumOpenMPThreads = 4
Maximum number of threads spawned by OpenMP when using the bulk mode.
Friends
class QmuParserTokenReader
Detailed Description
Mathematical expressions parser (base parser engine).
Author
(C) 2013 Ingo Berg
This is the implementation of a bytecode based mathematical expressions parser. The formula will be parsed from string and converted into a bytecode. Future calculations will be done with the bytecode instead the formula string resulting in a significant performance increase. Complementary to a set of internally implemented functions the parser is able to handle user defined functions and variables.
Definition at line 65 of file qmuparserbase.h.
Member Typedef Documentation
ParseFunction
typedef qreal(QmuParserBase::* qmu::QmuParserBase::ParseFunction) () const private
Typedef for the parse functions.
The parse function do the actual work. The parser exchanges the function pointer to the parser function depending on which state it is in. (i.e. bytecode parser vs. string parser)
Definition at line 191 of file qmuparserbase.h.
stringbuf_type
typedef QVector<QString> qmu::QmuParserBase::stringbuf_type private
Type for a vector of strings.
Definition at line 201 of file qmuparserbase.h.
token_reader_type
typedef QmuParserTokenReader qmu::QmuParserBase::token_reader_type private
Typedef for the token reader.
Definition at line 206 of file qmuparserbase.h.
token_type
typedef QmuParserToken<qreal, QString> qmu::QmuParserBase::token_type private
Type used for parser tokens.
Definition at line 211 of file qmuparserbase.h.
valbuf_type
typedef QVector<qreal> qmu::QmuParserBase::valbuf_type private
Type used for storing an array of values.
Definition at line 196 of file qmuparserbase.h.
Constructor & Destructor Documentation
QmuParserBase() [1/2]
qmu::QmuParserBase::QmuParserBase ()
Constructor.
Definition at line 87 of file qmuparserbase.cpp.
References InitTokenReader().
QmuParserBase() [2/2]
qmu::QmuParserBase::QmuParserBase (const QmuParserBase & a_Parser) explicit
Copy constructor.
Tha parser can be safely copy constructed but the bytecode is reset during copy construction.
Definition at line 123 of file qmuparserbase.cpp.
References Assign(), and m_pTokenReader.
~QmuParserBase()
qmu::QmuParserBase::~QmuParserBase () virtual
Definition at line 155 of file qmuparserbase.cpp.
Member Function Documentation
AddCallback()
void qmu::QmuParserBase::AddCallback (const QString & a_strName, const QmuParserCallback & a_Callback, funmap_type & a_Storage, const QString & a_szCharSet) private
Add a function or operator callback to the parser.
Definition at line 361 of file qmuparserbase.cpp.
References CheckOprt(), qmu::ecINVALID_FUN_PTR, qmu::ecNAME_CONFLICT, Error(), qmu::QmuParserCallback::GetAddr(), m_FunDef, m_InfixOprtDef, m_OprtDef, m_PostOprtDef, and ReInit().
Referenced by DefineFun(), DefineInfixOprt(), DefineOprt(), and DefinePostfixOprt().
AddValIdent()
void qmu::QmuParserBase::AddValIdent (identfun_type a_pCallback) inline
Add a value parsing function.
When parsing an expression muParser tries to detect values in the expression string using different valident callbacks. Thuis it's possible to parse for hex values, binary values and floating point values.
Definition at line 313 of file qmuparserbase.h.
References m_pTokenReader.
Referenced by qmu::QmuParser::QmuParser().
ApplyBinOprt()
void qmu::QmuParserBase::ApplyBinOprt (QStack< token_type > & a_stOpt, QStack< token_type > & a_stVal) const private
Performs the necessary steps to write code for the execution of binary operators into the bytecode.
Definition at line 938 of file qmuparserbase.cpp.
References qmu::QmuParserByteCode::AddAssignOp(), qmu::QmuParserByteCode::AddOp(), ApplyFunc(), qmu::cmASSIGN, qmu::cmOPRT_BIN, qmu::cmVAR, qmu::ecOPRT_TYPE_CONFLICT, qmu::ecUNEXPECTED_OPERATOR, Error(), qmu::QmuParserToken< TBase, TString >::GetType(), m_pTokenReader, m_vRPN, and qmu::tpSTR.
Referenced by ApplyRemainingOprt().
ApplyFunc()
void qmu::QmuParserBase::ApplyFunc (QStack< token_type > & a_stOpt, QStack< token_type > & a_stVal, int a_iArgCount) const private
Apply a function token.
Parameters
a_iArgCount Number of Arguments actually gathered used only for multiarg functions.
Postcondition
The result is pushed to the value stack
The function token is removed from the stack
Exceptions
QmuParserError if Argument count does not mach function requirements.
Definition at line 808 of file qmuparserbase.cpp.
References qmu::QmuParserByteCode::AddBulkFun(), qmu::QmuParserByteCode::AddFun(), ApplyStrFunc(), qmu::cmFUNC, qmu::cmFUNC_BULK, qmu::cmFUNC_STR, qmu::cmOPRT_BIN, qmu::cmOPRT_INFIX, qmu::cmOPRT_POSTFIX, qmu::ecINTERNAL_ERROR, qmu::ecTOO_FEW_PARAMS, qmu::ecTOO_MANY_PARAMS, qmu::ecUNASSIGNABLE_TOKEN, qmu::ecVAL_EXPECTED, Error(), qmu::QmuParserToken< TBase, TString >::GetArgCount(), qmu::QmuParserToken< TBase, TString >::GetAsString(), qmu::QmuParserToken< TBase, TString >::GetCode(), qmu::QmuParserToken< TBase, TString >::GetFuncAddr(), qmu::QmuParserToken< TBase, TString >::GetType(), m_pTokenReader, m_vRPN, qmu::QmuParserToken< TBase, TString >::SetVal(), and qmu::tpSTR.
Referenced by ApplyBinOprt(), and ApplyRemainingOprt().
ApplyIfElse()
void qmu::QmuParserBase::ApplyIfElse (QStack< token_type > & a_stOpt, QStack< token_type > & a_stVal) const private
Definition at line 905 of file qmuparserbase.cpp.
References qmu::QmuParserByteCode::AddIfElse(), qmu::cmELSE, qmu::cmENDIF, qmu::cmIF, qmu::QmuParserToken< TBase, TString >::GetCode(), qmu::QmuParserToken< TBase, TString >::GetVal(), and m_vRPN.
Referenced by ApplyRemainingOprt().
ApplyRemainingOprt()
void qmu::QmuParserBase::ApplyRemainingOprt (QStack< token_type > & stOpt, QStack< token_type > & stVal) const private
Apply a binary operator.
Parameters
stOpt The operator stack
stVal The value stack
Definition at line 985 of file qmuparserbase.cpp.
References ApplyBinOprt(), ApplyFunc(), ApplyIfElse(), qmu::cmASSIGN, qmu::cmBO, qmu::cmELSE, qmu::cmIF, qmu::cmLE, qmu::cmOPRT_BIN, qmu::cmOPRT_INFIX, qmu::ecINTERNAL_ERROR, and Error().
ApplyStrFunc()
QmuParserBase::token_type qmu::QmuParserBase::ApplyStrFunc (const token_type & a_FunTok, const QVector< token_type > & a_vArg) const private
Execute a function that takes a single string argument.
Parameters
a_FunTok Function token.
Exceptions
QmuParserError If the function token is not a string function
Definition at line 751 of file qmuparserbase.cpp.
References qmu::QmuParserByteCode::AddStrFun(), qmu::cmSTRING, qmu::ecINTERNAL_ERROR, qmu::ecSTRING_EXPECTED, qmu::ecVAL_EXPECTED, Error(), qmu::QmuParserToken< TBase, TString >::GetArgCount(), qmu::QmuParserToken< TBase, TString >::GetAsString(), qmu::QmuParserToken< TBase, TString >::GetFuncAddr(), m_pTokenReader, m_vRPN, and qmu::QmuParserToken< TBase, TString >::SetVal().
Referenced by ApplyFunc().
Assign()
void qmu::QmuParserBase::Assign (const QmuParserBase & a_Parser) private
Copy state of a parser object to this.
Clears Variables and Functions of this parser. Copies the states of all internal variables. Resets parse function to string parse mode.
Parameters
a_Parser the source object.
Definition at line 186 of file qmuparserbase.cpp.
References m_bBuiltInOp, m_ConstDef, m_FunDef, m_InfixOprtDef, m_nFinalResultIdx, m_nIfElseCounter, m_OprtDef, m_PostOprtDef, m_pTokenReader, m_sInfixOprtChars, m_sNameChars, m_sOprtChars, m_StrVarDef, m_VarDef, m_vStackBuffer, m_vStringBuf, m_vStringVarBuf, and ReInit().
Referenced by operator=(), and QmuParserBase().
CheckName()
void qmu::QmuParserBase::CheckName (const QString & a_sName, const QString & a_szCharSet) const private
Check if a name contains invalid characters.
Exceptions
ParserException if the name contains invalid characters.
Definition at line 434 of file qmuparserbase.cpp.
References qmu::ecINVALID_NAME, and Error().
Referenced by DefineConst(), DefineStrConst(), and DefineVar().
CheckOprt()
void qmu::QmuParserBase::CheckOprt (const QString & a_sName, const QmuParserCallback & a_Callback, const QString & a_szCharSet) const private
Check if a name contains invalid characters.
Exceptions
ParserException if the name contains invalid charakters.
Definition at line 404 of file qmuparserbase.cpp.
References qmu::cmOPRT_INFIX, qmu::cmOPRT_POSTFIX, qmu::ecINVALID_INFIX_IDENT, qmu::ecINVALID_NAME, qmu::ecINVALID_POSTFIX_IDENT, Error(), and qmu::QmuParserCallback::GetCode().
Referenced by AddCallback().
ClearConst()
void qmu::QmuParserBase::ClearConst ()
Clear all user defined constants.
Both numeric and string constants will be removed from the internal storage.
Postcondition
Resets the parser to string parsing mode.
Exceptions
nothrow
Definition at line 1725 of file qmuparserbase.cpp.
Referenced by qmu::Test::QmuParserTester::TestNames().
ClearFun()
void qmu::QmuParserBase::ClearFun ()
Clear all functions.
Postcondition
Resets the parser to string parsing mode.
Exceptions
nothrow
Definition at line 1711 of file qmuparserbase.cpp.
ClearInfixOprt()
void qmu::QmuParserBase::ClearInfixOprt ()
Clear the user defined Prefix operators.
Postcondition
Resets the parser to string parser mode.
Exceptions
nothrow
Definition at line 1764 of file qmuparserbase.cpp.
ClearOprt()
void qmu::QmuParserBase::ClearOprt ()
Clear all user defined binary operators.
Postcondition
Resets the parser to string parsing mode.
Exceptions
nothrow
Definition at line 1751 of file qmuparserbase.cpp.
ClearPostfixOprt()
void qmu::QmuParserBase::ClearPostfixOprt ()
Clear all user defined postfix operators.
Postcondition
Resets the parser to string parsing mode.
Exceptions
nothrow
Definition at line 1738 of file qmuparserbase.cpp.
Referenced by qmu::Test::QmuParserTester::TestNames().
ClearVar()
void qmu::QmuParserBase::ClearVar ()
Clear all user defined variables.
Exceptions
nothrow Resets the parser to string parsing mode by calling ReInit.
Definition at line 1681 of file qmuparserbase.cpp.
CreateRPN()
void qmu::QmuParserBase::CreateRPN () const private
Definition at line 1368 of file qmuparserbase.cpp.
References qmu::cmADD, qmu::cmARG_SEP, qmu::cmASSIGN, qmu::cmBC, qmu::cmBO, qmu::cmDIV, qmu::cmELSE, qmu::cmEND, qmu::cmENDIF, qmu::cmEQ, qmu::cmFUNC, qmu::cmFUNC_BULK, qmu::cmFUNC_STR, qmu::cmGE, qmu::cmGT, qmu::cmIF, qmu::cmLAND, qmu::cmLE, qmu::cmLOR, qmu::cmLT, qmu::cmMUL, qmu::cmNEQ, qmu::cmOPRT_BIN, qmu::cmOPRT_INFIX, qmu::cmOPRT_POSTFIX, qmu::cmPOW, qmu::cmPOW2, qmu::cmSTRING, qmu::cmSUB, qmu::cmUNKNOWN, qmu::cmVAL, qmu::cmVAR, qmu::cmVARMUL, qmu::cmVARPOW2, qmu::cmVARPOW3, qmu::cmVARPOW4, qmu::ecEMPTY_EXPRESSION, qmu::ecINTERNAL_ERROR, qmu::ecMISPLACED_COLON, qmu::ecMISSING_ELSE_CLAUSE, qmu::ecSTR_RESULT, qmu::ecUNEXPECTED_ARG, qmu::ecUNEXPECTED_ARG_SEP, qmu::ecUNEXPECTED_EOF, qmu::QmuParserToken< TBase, TString >::GetAsString(), qmu::QmuParserToken< TBase, TString >::GetCode(), qmu::QmuParserToken< TBase, TString >::GetVal(), qmu::QmuParserToken< TBase, TString >::GetVar(), qmu::oaLEFT, qmu::oaRIGHT, QMUP_FALLTHROUGH, qmu::QmuParserToken< TBase, TString >::SetIdx(), and qmu::tpDBL.
Referenced by GetUsedVar().
DefineConst()
void qmu::QmuParserBase::DefineConst (const QString & a_sName, qreal a_fVal)
Add a user defined constant.
Parameters
[in] a_sName The name of the constant.
[in] a_fVal the value of the constant.
Postcondition
Will reset the Parser to string parsing mode.
Exceptions
ParserException in case the name contains invalid signs.
Definition at line 632 of file qmuparserbase.cpp.
References CheckName(), m_ConstDef, ReInit(), and ValidNameChars().
Referenced by qmu::Test::QmuParserTester::EqnTest(), qmu::Test::QmuParserTester::EqnTestBulk(), and qmu::QmuParser::InitConst().
DefineFun()
template<typename T > void qmu::QmuParserBase::DefineFun (const QString & a_strName, T a_pFun, bool a_bAllowOpt = true) inline
Define a parser function without arguments.
Parameters
a_strName Name of the function
a_pFun Pointer to the callback function
a_bAllowOpt A flag indicating this function may be optimized
Definition at line 288 of file qmuparserbase.h.
References AddCallback(), m_FunDef, and ValidNameChars().
Referenced by qmu::QmuParser::InitFun(), and qmu::Test::QmuParserTester::ThrowTest().
DefineInfixOprt()
void qmu::QmuParserBase::DefineInfixOprt (const QString & a_sName, fun_type1 a_pFun, int a_iPrec = prINFIX, bool a_bAllowOpt = true)
Add a user defined operator.
Postcondition
Will reset the Parser to string parsing mode.
Parameters
[in] a_sName operator Identifier
[in] a_pFun Operator callback function
[in] a_iPrec Operator Precedence (default=prSIGN)
[in] a_bAllowOpt True if operator is volatile (default=false)
See also
EPrec
Definition at line 542 of file qmuparserbase.cpp.
References AddCallback(), qmu::cmOPRT_INFIX, m_InfixOprtDef, and ValidInfixOprtChars().
Referenced by qmu::QmuParser::InitOprt().
DefineInfixOprtChars()
void qmu::QmuParserBase::DefineInfixOprtChars (const QString & a_szCharset) inline
Define the set of valid characters to be used in names of infix operators.
Definition at line 362 of file qmuparserbase.h.
References m_sInfixOprtChars.
Referenced by qmu::QmuFormulaBase::InitCharSets(), and qmu::QmuParser::InitCharSets().
DefineNameChars()
void qmu::QmuParserBase::DefineNameChars (const QString & a_szCharset) inline
Define the set of valid characters to be used in names of functions, variables, constants.
Definition at line 344 of file qmuparserbase.h.
References m_sNameChars.
Referenced by qmu::QmuFormulaBase::InitCharSets(), and qmu::QmuParser::InitCharSets().
DefineOprt()
void qmu::QmuParserBase::DefineOprt (const QString & a_sName, fun_type2 a_pFun, unsigned a_iPrec = 0, EOprtAssociativity a_eAssociativity = oaLEFT, bool a_bAllowOpt = false)
Define a binary operator.
Parameters
[in] a_sName The identifier of the operator.
[in] a_pFun Pointer to the callback function.
[in] a_iPrec Precedence of the operator.
[in] a_eAssociativity The associativity of the operator.
[in] a_bAllowOpt If this is true the operator may be optimized away.
Adds a new Binary operator the the parser instance.
Definition at line 559 of file qmuparserbase.cpp.
References AddCallback(), c_DefaultOprt, qmu::cmENDIF, qmu::ecBUILTIN_OVERLOAD, Error(), m_bBuiltInOp, m_OprtDef, and ValidOprtChars().
DefineOprtChars()
void qmu::QmuParserBase::DefineOprtChars (const QString & a_szCharset) inline
Define the set of valid characters to be used in names of binary operators and postfix operators.
Definition at line 353 of file qmuparserbase.h.
References m_sOprtChars.
Referenced by qmu::QmuFormulaBase::InitCharSets(), and qmu::QmuParser::InitCharSets().
DefinePostfixOprt()
void qmu::QmuParserBase::DefinePostfixOprt (const QString & a_sFun, fun_type1 a_pFun, bool a_bAllowOpt = true)
Add a user defined operator.
Postcondition
Will reset the Parser to string parsing mode.
Definition at line 511 of file qmuparserbase.cpp.
References AddCallback(), qmu::cmOPRT_POSTFIX, m_PostOprtDef, qmu::prPOSTFIX, and ValidOprtChars().
Referenced by qmu::Test::QmuParserTester::ThrowTest().
DefineStrConst()
void qmu::QmuParserBase::DefineStrConst (const QString & a_strName, const QString & a_strVal)
Define a new string constant.
Parameters
[in] a_strName The name of the constant.
[in] a_strVal the value of the constant.
Definition at line 582 of file qmuparserbase.cpp.
References CheckName(), qmu::ecNAME_CONFLICT, Error(), m_StrVarDef, m_vStringBuf, m_vStringVarBuf, ReInit(), and ValidNameChars().
DefineVar()
void qmu::QmuParserBase::DefineVar (const QString & a_sName, qreal * a_pVar)
Add a user defined variable.
Parameters
[in] a_sName the variable name
[in] a_pVar A pointer to the variable vaule.
Postcondition
Will reset the Parser to string parsing mode.
Exceptions
ParserException in case the name contains invalid signs or a_pVar is NULL.
Definition at line 606 of file qmuparserbase.cpp.
References CheckName(), qmu::ecINVALID_VAR_PTR, qmu::ecNAME_CONFLICT, Error(), m_ConstDef, m_VarDef, ReInit(), and ValidNameChars().
Referenced by qmu::Test::QmuParserTester::EqnTestBulk(), qmu::Test::QmuParserTester::EqnTestWithVarChange(), Calculator::InitVariables(), qmu::Test::QmuParserTester::TestInterface(), qmu::Test::QmuParserTester::TestVarConst(), and qmu::Test::QmuParserTester::ThrowTest().
EnableBuiltInOprt()
void qmu::QmuParserBase::EnableBuiltInOprt (bool a_bIsOn = true)
Enable or disable the built in binary operators.
Exceptions
nothrow
See also
m_bBuiltInOp, ReInit()
If you disable the built in binary operators there will be no binary operators defined. Thus you must add them manually one by one. It is not possible to disable built in operators selectively. This function will Reinitialize the parser by calling ReInit().
Definition at line 1807 of file qmuparserbase.cpp.
Referenced by qmu::Test::QmuParserTester::TestNames().
EnableDebugDump()
void qmu::QmuParserBase::EnableDebugDump (bool bDumpCmd, bool bDumpStack) static
Enable the dumping of bytecode amd stack content on the console.
Parameters
bDumpCmd Flag to enable dumping of the current bytecode to the console.
bDumpStack Flag to enable dumping of the stack content is written to the console.
This function is for debug purposes only!
Definition at line 1791 of file qmuparserbase.cpp.
EnableOptimizer()
void qmu::QmuParserBase::EnableOptimizer (bool a_bIsOn = true)
Enable or disable the formula optimization feature.
Postcondition
Resets the parser to string parser mode.
Exceptions
nothrow
Definition at line 1776 of file qmuparserbase.cpp.
Referenced by qmu::Test::QmuParserTester::EqnTest().
Error()
void Q_NORETURN qmu::QmuParserBase::Error (EErrorCodes a_iErrc, int a_iPos = -1, const QString & a_sTok = QString()) const
Create an error containing the parse error position.
This function will create an Parser Exception object containing the error text and its position.
Parameters
a_iErrc [in] The error code of type EErrorCodes.
a_iPos [in] The position where the error was detected.
a_sTok [in] The token string representation associated with the error.
Exceptions
ParserException always throws thats the only purpose of this function.
Definition at line 1668 of file qmuparserbase.cpp.
Referenced by AddCallback(), ApplyBinOprt(), ApplyFunc(), ApplyRemainingOprt(), ApplyStrFunc(), CheckName(), CheckOprt(), DefineOprt(), DefineStrConst(), DefineVar(), qmu::QmuParserTokenReader::Error(), GetOprtPrecedence(), ParseCmdCodeBulk(), and SetExpr().
Eval() [1/3]
qreal qmu::QmuParserBase::Eval () const inline
Calculate the result.
A note on const correctness: I consider it important that Calc is a const function. Due to caching operations Calc changes only the state of internal variables with one exception m_UsedVar this is reset during string parsing and accessible from the outside. Instead of making Calc non const GetUsedVar is non const because it explicitely calls Eval() forcing this update.
Precondition
A formula must be set.
Variables must have been set (if needed)
See also
m_pParseFormula
Returns
The evaluation result
Exceptions
ParseException if no Formula is set or in case of any other error related to the formula.
Definition at line 451 of file qmuparserbase.h.
References m_pParseFormula.
Referenced by qmu::QmuParser::Diff(), qmu::Test::QmuParserTester::EqnTest(), qmu::Test::QmuParserTester::EqnTestBulk(), qmu::Test::QmuParserTester::EqnTestWithVarChange(), Calculator::EvalFormula(), qmu::QmuTokenParser::QmuTokenParser(), qmu::Test::QmuParserTester::TestInterface(), and qmu::Test::QmuParserTester::ThrowTest().
Eval() [2/3]
qreal * qmu::QmuParserBase::Eval (int & nStackSize) const
Evaluate an expression containing comma seperated subexpressions.
Parameters
[out] nStackSize The total number of results available
Returns
Pointer to the array containing all expression results
This member function can be used to retriev all results of an expression made up of multiple comma seperated subexpressions (i.e. "x+y,sin(x),cos(y)")
Definition at line 1929 of file qmuparserbase.cpp.
Eval() [3/3]
void qmu::QmuParserBase::Eval (qreal * results, int nBulkSize) const
Definition at line 1939 of file qmuparserbase.cpp.
GetArgSep()
QChar qmu::QmuParserBase::GetArgSep () const
Get the argument separator character.
Definition at line 1817 of file qmuparserbase.cpp.
GetConst()
const valmap_type & qmu::QmuParserBase::GetConst () const inline
Return a map containing all parser constants.
Definition at line 380 of file qmuparserbase.h.
References m_ConstDef.
getDecimalPoint()
QChar qmu::QmuParserBase::getDecimalPoint () const
Definition at line 281 of file qmuparserbase.cpp.
References m_decimalPoint.
GetExpr()
const QString & qmu::QmuParserBase::GetExpr () const inline
Retrieve the formula.
Definition at line 405 of file qmuparserbase.h.
References m_pTokenReader.
GetFunDef()
const funmap_type & qmu::QmuParserBase::GetFunDef () const inline
Return prototypes of all parser functions.
Returns
m_FunDef
See also
FunProt
Exceptions
nothrow The return type is a map of the public type funmap_type containing the prototype definitions for all numerical parser functions. String functions are not part of this map. The Prototype definition is encapsulated in objects of the class FunProt one per parser function each associated with function names via a map construct.
Definition at line 396 of file qmuparserbase.h.
References m_FunDef.
getLocale()
QLocale qmu::QmuParserBase::getLocale () const
Definition at line 267 of file qmuparserbase.cpp.
References m_locale.
GetNumbers()
QMap< int, QString > qmu::QmuParserBase::GetNumbers () const inline
Definition at line 335 of file qmuparserbase.h.
References m_Numbers.
GetNumResults()
int qmu::QmuParserBase::GetNumResults () const inline
Return the number of results on the calculation stack.
If the expression contains comma seperated subexpressions (i.e. "sin(y), x+y"). There mey be more than one return value. This function returns the number of available results.
Definition at line 429 of file qmuparserbase.h.
References m_nFinalResultIdx.
GetOprtAssociativity()
EOprtAssociativity qmu::QmuParserBase::GetOprtAssociativity (const token_type & a_Tok) const private
Get operator priority.
Exceptions
ParserException if a_Oprt is no operator code
Definition at line 692 of file qmuparserbase.cpp.
References qmu::cmADD, qmu::cmASSIGN, qmu::cmDIV, qmu::cmEQ, qmu::cmGE, qmu::cmGT, qmu::cmLAND, qmu::cmLE, qmu::cmLOR, qmu::cmLT, qmu::cmMUL, qmu::cmNEQ, qmu::cmOPRT_BIN, qmu::cmPOW, qmu::cmSUB, qmu::QmuParserToken< TBase, TString >::GetAssociativity(), qmu::QmuParserToken< TBase, TString >::GetCode(), qmu::oaLEFT, qmu::oaNONE, and qmu::oaRIGHT.
GetOprtDef()
const QStringList & qmu::QmuParserBase::GetOprtDef () inline static
Get the default symbols used for the built in operators.
See also
c_DefaultOprt
Definition at line 323 of file qmuparserbase.h.
References c_DefaultOprt.
Referenced by qmu::QmuParserTokenReader::IsBuiltIn(), and qmu::QmuParserTokenReader::IsOprt().
GetOprtPrecedence()
int qmu::QmuParserBase::GetOprtPrecedence (const token_type & a_Tok) const private
Get operator priority.
Exceptions
ParserException if a_Oprt is no operator code
Definition at line 644 of file qmuparserbase.cpp.
References qmu::cmADD, qmu::cmARG_SEP, qmu::cmASSIGN, qmu::cmDIV, qmu::cmELSE, qmu::cmEND, qmu::cmEQ, qmu::cmGE, qmu::cmGT, qmu::cmIF, qmu::cmLAND, qmu::cmLE, qmu::cmLOR, qmu::cmLT, qmu::cmMUL, qmu::cmNEQ, qmu::cmOPRT_BIN, qmu::cmOPRT_INFIX, qmu::cmPOW, qmu::cmSUB, qmu::ecINTERNAL_ERROR, Error(), qmu::QmuParserToken< TBase, TString >::GetCode(), qmu::QmuParserToken< TBase, TString >::GetPri(), qmu::prADD_SUB, qmu::prCMP, qmu::prLAND, qmu::prLOR, qmu::prMUL_DIV, and qmu::prPOW.
getThousandsSeparator()
QChar qmu::QmuParserBase::getThousandsSeparator () const
Definition at line 293 of file qmuparserbase.cpp.
References m_thousandsSeparator.
GetTokens()
QMap< int, QString > qmu::QmuParserBase::GetTokens () const inline
Definition at line 329 of file qmuparserbase.h.
References m_Tokens.
Referenced by Calculator::EvalFormula(), and VPatternConverter::FixIncrementInFormulaToV0_2_0().
GetUsedVar()
const varmap_type & qmu::QmuParserBase::GetUsedVar () const
Return a map containing the used variables only.
Definition at line 723 of file qmuparserbase.cpp.
References CreateRPN(), m_pParseFormula, m_pTokenReader, and ParseString().
Referenced by qmu::Test::QmuParserTester::TestVarConst().
GetVar()
const varmap_type & qmu::QmuParserBase::GetVar () const inline
Return a map containing the used variables only.
Definition at line 371 of file qmuparserbase.h.
References m_VarDef.
Referenced by qmu::Test::QmuParserTester::TestVarConst().
GetVersion()
QString qmu::QmuParserBase::GetVersion (EParserVersionInfo eInfo = pviFULL) static
Returns the version of muparser.
Parameters
eInfo A flag indicating whether the full version info should be returned or not.
Format is as follows: "MAJOR.MINOR (COMPILER_FLAGS)" The COMPILER_FLAGS are returned only if eInfo==pviFULL.
Definition at line 312 of file qmuparserbase.cpp.
References qmu::pviFULL, QMUP_VERSION, and QMUP_VERSION_DATE.
HasBuiltInOprt()
bool qmu::QmuParserBase::HasBuiltInOprt () const inline
Query status of built in variables.
Returns
m_bBuiltInOp; true if built in operators are enabled.
Exceptions
nothrow
Definition at line 416 of file qmuparserbase.h.
References m_bBuiltInOp.
Referenced by qmu::QmuParserTokenReader::IsBuiltIn(), and qmu::QmuParserTokenReader::IsOprt().
Init()
void qmu::QmuParserBase::Init () protected
Initialize user defined functions.
Calls the virtual functions InitFun(), InitConst() and InitOprt().
Definition at line 524 of file qmuparserbase.cpp.
References InitCharSets(), InitConst(), InitFun(), and InitOprt().
InitCharSets()
virtual void qmu::QmuParserBase::InitCharSets () protected pure virtual
Implemented in qmu::QmuParser, and qmu::QmuFormulaBase.
Referenced by Init(), and setLocale().
InitConst()
virtual void qmu::QmuParserBase::InitConst () protected pure virtual
Implemented in qmu::QmuParser.
Referenced by Init().
InitFun()
virtual void qmu::QmuParserBase::InitFun () protected pure virtual
Implemented in qmu::QmuParser.
Referenced by Init().
InitOprt()
virtual void qmu::QmuParserBase::InitOprt () protected pure virtual
Implemented in qmu::QmuParser.
Referenced by Init(), and setLocale().
InitTokenReader()
void qmu::QmuParserBase::InitTokenReader () inline private
Initialize the token reader.
Create new token reader object and submit pointers to function, operator, constant and variable definitions.
Postcondition
m_pTokenReader.get()!=0
Definition at line 301 of file qmuparserbase.h.
References m_pTokenReader.
Referenced by QmuParserBase().
OnDetectVar()
void qmu::QmuParserBase::OnDetectVar (const QString & pExpr, int & nStart, int & nEnd) protected virtual
Reimplemented in qmu::QmuParser.
Definition at line 253 of file qmuparserbase.cpp.
Referenced by qmu::QmuParserTokenReader::IsVarTok().
operator=()
QmuParserBase & qmu::QmuParserBase::operator= (const QmuParserBase & a_Parser)
Assignement operator.
Implemented by calling Assign(a_Parser). Self assignement is suppressed.
Parameters
a_Parser Object to copy to this.
Returns
*this
Exceptions
nothrow
Definition at line 167 of file qmuparserbase.cpp.
References Assign().
ParseCmdCode()
qreal qmu::QmuParserBase::ParseCmdCode () const private
Parse the command code.
See also
ParseString(...)
Command code contains precalculated stack positions of the values and the associated operators. The Stack is filled beginning from index one the value at index zero is not used at all.
Definition at line 1021 of file qmuparserbase.cpp.
References ParseCmdCodeBulk().
ParseCmdCodeBulk()
qreal qmu::QmuParserBase::ParseCmdCodeBulk (int nOffset, int nThreadID) const private
Evaluate the RPN.
Parameters
nOffset The offset added to variable addresses (for bulk mode)
nThreadID OpenMP Thread id of the calling thread
Definition at line 1032 of file qmuparserbase.cpp.
References qmu::cmADD, qmu::cmARG_SEP, qmu::cmASSIGN, qmu::cmBC, qmu::cmBO, qmu::SToken::Cmd, qmu::cmDIV, qmu::cmELSE, qmu::cmEND, qmu::cmENDIF, qmu::cmEQ, qmu::cmFUNC, qmu::cmFUNC_BULK, qmu::cmFUNC_STR, qmu::cmGE, qmu::cmGT, qmu::cmIF, qmu::cmLAND, qmu::cmLE, qmu::cmLOR, qmu::cmLT, qmu::cmMUL, qmu::cmNEQ, qmu::cmOPRT_BIN, qmu::cmOPRT_INFIX, qmu::cmOPRT_POSTFIX, qmu::cmPOW, qmu::cmPOW2, qmu::cmSTRING, qmu::cmSUB, qmu::cmUNKNOWN, qmu::cmVAL, qmu::cmVAR, qmu::cmVARMUL, qmu::cmVARPOW2, qmu::cmVARPOW3, qmu::cmVARPOW4, qmu::ecDIV_BY_ZERO, qmu::ecINTERNAL_ERROR, Error(), qmu::QmuParserByteCode::GetBase(), m_vRPN, m_vStackBuffer, m_vStringBuf, QmuFuzzyComparePossibleNulls(), and s_MaxNumOpenMPThreads.
Referenced by ParseCmdCode().
ParseString()
qreal qmu::QmuParserBase::ParseString () const private
One of the two main parse functions.
See also
ParseCmdCode(...)
Parse expression from input string. Perform syntax checking and create bytecode. After parsing the string and creating the bytecode the function pointer m_pParseFormula will be changed to the second parse routine the uses bytecode instead of string parsing.
Definition at line 1642 of file qmuparserbase.cpp.
References qmu::QmuParserError::SetFormula().
Referenced by GetUsedVar(), and ReInit().
ReInit()
void qmu::QmuParserBase::ReInit () const private
Reset parser to string parsing mode and clear internal buffers.
Clear bytecode, reset the token reader.
Exceptions
nothrow
Definition at line 241 of file qmuparserbase.cpp.
References qmu::QmuParserByteCode::clear(), m_nIfElseCounter, m_Numbers, m_pParseFormula, m_pTokenReader, m_Tokens, m_vRPN, m_vStringBuf, and ParseString().
Referenced by AddCallback(), Assign(), DefineConst(), DefineStrConst(), DefineVar(), and SetExpr().
RemoveVar()
void qmu::QmuParserBase::RemoveVar (const QString & a_strVarName)
Remove a variable from internal storage.
Exceptions
nothrow Removes a variable if it exists. If the Variable does not exist nothing will be done.
Definition at line 1694 of file qmuparserbase.cpp.
Referenced by qmu::Test::QmuParserTester::TestInterface().
ResetLocale()
void qmu::QmuParserBase::ResetLocale ()
Resets the locale.
The default locale used "." as decimal separator, no thousands separator and "," as function argument separator.
Definition at line 226 of file qmuparserbase.cpp.
References m_decimalPoint, m_locale, m_thousandsSeparator, SetArgSep(), and setLocale().
setAllowSubexpressions()
void qmu::QmuParserBase::setAllowSubexpressions (bool value)
Definition at line 261 of file qmuparserbase.cpp.
References allowSubexpressions.
Referenced by Calculator::Calculator(), and qmu::QmuTokenParser::QmuTokenParser().
SetArgSep()
void qmu::QmuParserBase::SetArgSep (char_type cArgSep)
Set argument separator.
Parameters
cArgSep the argument separator character.
Definition at line 1827 of file qmuparserbase.cpp.
Referenced by ResetLocale(), qmu::QmuFormulaBase::SetSepForEval(), and qmu::QmuFormulaBase::SetSepForTr().
setDecimalPoint()
void qmu::QmuParserBase::setDecimalPoint (const QChar & c)
Definition at line 287 of file qmuparserbase.cpp.
References m_decimalPoint.
Referenced by qmu::QmuFormulaBase::SetSepForEval(), and qmu::QmuFormulaBase::SetSepForTr().
SetExpr()
void qmu::QmuParserBase::SetExpr (const QString & a_sExpr)
Set the formula.
Parameters
a_sExpr Formula as string_type
Exceptions
ParserException in case of syntax errors.
Triggers first time calculation thus the creation of the bytecode and scanning of used variables.
Definition at line 454 of file qmuparserbase.cpp.
References qmu::ecLOCALE, Error(), m_pTokenReader, and ReInit().
Referenced by qmu::Test::QmuParserTester::EqnTestBulk(), qmu::Test::QmuParserTester::EqnTestWithVarChange(), Calculator::EvalFormula(), qmu::QmuTokenParser::QmuTokenParser(), qmu::Test::QmuParserTester::TestInterface(), qmu::Test::QmuParserTester::TestVarConst(), and qmu::Test::QmuParserTester::ThrowTest().
setLocale()
void qmu::QmuParserBase::setLocale (const QLocale & value)
Definition at line 273 of file qmuparserbase.cpp.
References InitCharSets(), InitOprt(), and m_locale.
Referenced by ResetLocale(), and qmu::QmuFormulaBase::SetSepForTr().
setThousandsSeparator()
void qmu::QmuParserBase::setThousandsSeparator (const QChar & c)
Definition at line 299 of file qmuparserbase.cpp.
References m_thousandsSeparator.
Referenced by qmu::QmuFormulaBase::SetSepForEval(), and qmu::QmuFormulaBase::SetSepForTr().
SetVarFactory()
void qmu::QmuParserBase::SetVarFactory (facfun_type a_pFactory, void * pUserData = nullptr)
Set a function that can create variable pointer for unknown expression variables.
Parameters
a_pFactory A pointer to the variable factory.
pUserData A user defined context pointer.
Definition at line 2001 of file qmuparserbase.cpp.
References m_pTokenReader.
Referenced by Calculator::EvalFormula(), and qmu::QmuTokenParser::QmuTokenParser().
StackDump()
void qmu::QmuParserBase::StackDump (const QStack< token_type > & a_stVal, const QStack< token_type > & a_stOprt) const private
Dump stack content.
This function is used for debugging only.
Definition at line 1838 of file qmuparserbase.cpp.
References qmu::cmASSIGN, qmu::cmBC, qmu::cmBO, qmu::cmELSE, qmu::cmEND, qmu::cmENDIF, qmu::cmFUNC, qmu::cmFUNC_BULK, qmu::cmFUNC_STR, qmu::cmIF, qmu::cmOPRT_BIN, qmu::cmOPRT_INFIX, qmu::cmUNKNOWN, qmu::cmVAL, qmu::cmVAR, qmu::QmuParserToken< TBase, TString >::GetAsString(), qmu::QmuParserToken< TBase, TString >::GetCode(), qmu::QmuParserToken< TBase, TString >::GetType(), qmu::QmuParserToken< TBase, TString >::GetVal(), and qmu::tpSTR.
ValidInfixOprtChars()
const QString & qmu::QmuParserBase::ValidInfixOprtChars () const
Virtual function that defines the characters allowed in infix operator definitions.
See also
ValidNameChars, ValidOprtChars
Definition at line 500 of file qmuparserbase.cpp.
References m_sInfixOprtChars.
Referenced by DefineInfixOprt(), and qmu::QmuParserTokenReader::IsInfixOpTok().
ValidNameChars()
const QString & qmu::QmuParserBase::ValidNameChars () const
Virtual function that defines the characters allowed in name identifiers.
See also
ValidOprtChars, #ValidPrefixOprtChars
Definition at line 478 of file qmuparserbase.cpp.
References m_sNameChars.
Referenced by DefineConst(), DefineFun(), DefineStrConst(), DefineVar(), qmu::QmuParserTokenReader::IsFunTok(), qmu::QmuParserTokenReader::IsStrVarTok(), qmu::QmuParserTokenReader::IsUndefVarTok(), qmu::QmuParserTokenReader::IsValTok(), qmu::QmuParserTokenReader::IsVarTok(), and qmu::QmuParserTokenReader::ReadNextToken().
ValidOprtChars()
const QString & qmu::QmuParserBase::ValidOprtChars () const
Virtual function that defines the characters allowed in operator definitions.
See also
ValidNameChars, #ValidPrefixOprtChars
Definition at line 489 of file qmuparserbase.cpp.
References m_sOprtChars.
Referenced by DefineOprt(), DefinePostfixOprt(), qmu::QmuParserTokenReader::ExtractOperatorToken(), and qmu::QmuParserTokenReader::IsPostOpTok().
Friends And Related Function Documentation
QmuParserTokenReader
friend class QmuParserTokenReader friend
Definition at line 67 of file qmuparserbase.h.
Member Data Documentation
allowSubexpressions
bool qmu::QmuParserBase::allowSubexpressions private
Definition at line 252 of file qmuparserbase.h.
Referenced by setAllowSubexpressions().
c_DefaultOprt
const QStringList qmu::QmuParserBase::c_DefaultOprt static protected
Initial value:
= QStringList() << "<=" << ">=" << "!=" << "==" << "<"  << ">"  << "+"
                                                               << "-"  << "*"  << "/"  << "^"  << "&&" << "||" << "="
                                                               << "("  << ")"  << "?"  << ":"
Identifiers for built in binary operators.
When defining custom binary operators with #AddOprt(...) make sure not to choose names conflicting with these definitions.
Definition at line 136 of file qmuparserbase.h.
Referenced by DefineOprt(), and GetOprtDef().
g_DbgDumpCmdCode
bool qmu::QmuParserBase::g_DbgDumpCmdCode = false static protected
Definition at line 140 of file qmuparserbase.h.
g_DbgDumpStack
bool qmu::QmuParserBase::g_DbgDumpStack = false static protected
Definition at line 141 of file qmuparserbase.h.
m_bBuiltInOp
bool qmu::QmuParserBase::m_bBuiltInOp private
Flag that can be used for switching built in operators on and off.
Definition at line 238 of file qmuparserbase.h.
Referenced by Assign(), DefineOprt(), and HasBuiltInOprt().
m_ConstDef
valmap_type qmu::QmuParserBase::m_ConstDef private
user constants.
Definition at line 234 of file qmuparserbase.h.
Referenced by Assign(), DefineConst(), DefineVar(), GetConst(), and qmu::QmuParserTokenReader::SetParent().
m_decimalPoint
QChar qmu::QmuParserBase::m_decimalPoint protected
Definition at line 138 of file qmuparserbase.h.
Referenced by getDecimalPoint(), ResetLocale(), and setDecimalPoint().
m_FunDef
funmap_type qmu::QmuParserBase::m_FunDef private
Map of function names and pointers.
Definition at line 230 of file qmuparserbase.h.
Referenced by AddCallback(), Assign(), DefineFun(), GetFunDef(), and qmu::QmuParserTokenReader::SetParent().
m_InfixOprtDef
funmap_type qmu::QmuParserBase::m_InfixOprtDef private
unary infix operator.
Definition at line 232 of file qmuparserbase.h.
Referenced by AddCallback(), Assign(), DefineInfixOprt(), and qmu::QmuParserTokenReader::SetParent().
m_locale
QLocale qmu::QmuParserBase::m_locale protected
The locale used by the parser.
Definition at line 137 of file qmuparserbase.h.
Referenced by getLocale(), qmu::QmuFormulaBase::InitCharSets(), qmu::QmuParser::InitOprt(), ResetLocale(), and setLocale().
m_nFinalResultIdx
int qmu::QmuParserBase::m_nFinalResultIdx mutable private
Definition at line 248 of file qmuparserbase.h.
Referenced by Assign(), and GetNumResults().
m_nIfElseCounter
int qmu::QmuParserBase::m_nIfElseCounter mutable private
Internal counter for keeping track of nested if-then-else clauses.
Definition at line 244 of file qmuparserbase.h.
Referenced by Assign(), and ReInit().
m_Numbers
QMap<int, QString> qmu::QmuParserBase::m_Numbers mutable private
Keep all numbers what exist in formula.
Definition at line 250 of file qmuparserbase.h.
Referenced by GetNumbers(), and ReInit().
m_OprtDef
funmap_type qmu::QmuParserBase::m_OprtDef private
Binary operator callbacks.
Definition at line 233 of file qmuparserbase.h.
Referenced by AddCallback(), Assign(), DefineOprt(), and qmu::QmuParserTokenReader::SetParent().
m_PostOprtDef
funmap_type qmu::QmuParserBase::m_PostOprtDef private
Postfix operator callbacks.
Definition at line 231 of file qmuparserbase.h.
Referenced by AddCallback(), Assign(), DefinePostfixOprt(), and qmu::QmuParserTokenReader::SetParent().
m_pParseFormula
ParseFunction qmu::QmuParserBase::m_pParseFormula mutable private
Pointer to the parser function.
Eval() calls the function whose address is stored there.
Definition at line 223 of file qmuparserbase.h.
Referenced by Eval(), GetUsedVar(), and ReInit().
m_pTokenReader
std::unique_ptr<token_reader_type> qmu::QmuParserBase::m_pTokenReader private
Managed pointer to the token reader object.
Definition at line 228 of file qmuparserbase.h.
Referenced by AddValIdent(), ApplyBinOprt(), ApplyFunc(), ApplyStrFunc(), Assign(), GetExpr(), GetUsedVar(), InitTokenReader(), QmuParserBase(), ReInit(), SetExpr(), and SetVarFactory().
m_sInfixOprtChars
QString qmu::QmuParserBase::m_sInfixOprtChars private
Charset for infix operator tokens.
Definition at line 242 of file qmuparserbase.h.
Referenced by Assign(), DefineInfixOprtChars(), and ValidInfixOprtChars().
m_sNameChars
QString qmu::QmuParserBase::m_sNameChars private
Charset for names.
Definition at line 240 of file qmuparserbase.h.
Referenced by Assign(), DefineNameChars(), and ValidNameChars().
m_sOprtChars
QString qmu::QmuParserBase::m_sOprtChars private
Charset for postfix/ binary operator tokens.
Definition at line 241 of file qmuparserbase.h.
Referenced by Assign(), DefineOprtChars(), and ValidOprtChars().
m_StrVarDef
strmap_type qmu::QmuParserBase::m_StrVarDef private
user defined string constants
Definition at line 235 of file qmuparserbase.h.
Referenced by Assign(), DefineStrConst(), and qmu::QmuParserTokenReader::SetParent().
m_thousandsSeparator
QChar qmu::QmuParserBase::m_thousandsSeparator protected
Definition at line 139 of file qmuparserbase.h.
Referenced by getThousandsSeparator(), ResetLocale(), and setThousandsSeparator().
m_Tokens
QMap<int, QString> qmu::QmuParserBase::m_Tokens mutable private
Keep all tokens that we can translate.
Definition at line 249 of file qmuparserbase.h.
Referenced by GetTokens(), and ReInit().
m_VarDef
varmap_type qmu::QmuParserBase::m_VarDef private
user defind variables.
Definition at line 236 of file qmuparserbase.h.
Referenced by Assign(), DefineVar(), GetVar(), and qmu::QmuParserTokenReader::SetParent().
m_vRPN
QmuParserByteCode qmu::QmuParserBase::m_vRPN mutable private
The Bytecode class.
Definition at line 224 of file qmuparserbase.h.
Referenced by ApplyBinOprt(), ApplyFunc(), ApplyIfElse(), ApplyStrFunc(), ParseCmdCodeBulk(), and ReInit().
m_vStackBuffer
valbuf_type qmu::QmuParserBase::m_vStackBuffer mutable private
This is merely a buffer used for the stack in the cmd parsing routine.
Definition at line 247 of file qmuparserbase.h.
Referenced by Assign(), and ParseCmdCodeBulk().
m_vStringBuf
stringbuf_type qmu::QmuParserBase::m_vStringBuf mutable private
String buffer, used for storing string function arguments.
Definition at line 225 of file qmuparserbase.h.
Referenced by Assign(), DefineStrConst(), qmu::QmuParserTokenReader::IsString(), ParseCmdCodeBulk(), and ReInit().
m_vStringVarBuf
stringbuf_type qmu::QmuParserBase::m_vStringVarBuf private
Definition at line 226 of file qmuparserbase.h.
Referenced by Assign(), DefineStrConst(), and qmu::QmuParserTokenReader::IsStrVarTok().
s_MaxNumOpenMPThreads
const int qmu::QmuParserBase::s_MaxNumOpenMPThreads = 4 static private
Maximum number of threads spawned by OpenMP when using the bulk mode.
Definition at line 216 of file qmuparserbase.h.
Referenced by ParseCmdCodeBulk().
The documentation for this class was generated from the following files:
src/libs/qmuparser/qmuparserbase.h
src/libs/qmuparser/qmuparserbase.cpp