Seamly2D: VGrainlineData Class Reference
VGrainlineData Class Reference
The VGrainlineData class holds information about a grainline like position, size, rotation and visibility.
#include <vgrainlinedata.h>
Public Member Functions
VGrainlineData ()
VGrainlineData (const VGrainlineData &data)
virtual ~VGrainlineData ()
VGrainlineData & operator= (const VGrainlineData &data)
void Swap (VGrainlineData &data) Q_DECL_NOTHROW
QString GetLength () const
void SetLength (const QString &qsLen)
QString GetRotation () const
void SetRotation (const QString &qsRot)
ArrowType GetArrowType () const
void SetArrowType (ArrowType eAT)
quint32 centerAnchorPoint () const
void setCenterAnchorPoint (quint32 centerAnchor)
quint32 topAnchorPoint () const
void setTopAnchorPoint (quint32 topAnchorPoint)
quint32 bottomAnchorPoint () const
void setBottomAnchorPoint (quint32 bottomAnchorPoint)
Public Member Functions inherited from VAbstractFloatItemData
VAbstractFloatItemData ()
VAbstractFloatItemData (const VAbstractFloatItemData &data)
virtual ~VAbstractFloatItemData ()
VAbstractFloatItemData & operator= (const VAbstractFloatItemData &data)
void Swap (VAbstractFloatItemData &data) Q_DECL_NOTHROW
QPointF GetPos () const
void SetPos (const QPointF &ptPos)
bool IsVisible () const
void SetVisible (bool bVisible)
Private Attributes
QSharedDataPointer< VGrainlineDataPrivate > d
Detailed Description
The VGrainlineData class holds information about a grainline like position, size, rotation and visibility.
Definition at line 44 of file vgrainlinedata.h.
Constructor & Destructor Documentation
VGrainlineData() [1/2]
VGrainlineData::VGrainlineData ()
Definition at line 42 of file vgrainlinedata.cpp.
VGrainlineData() [2/2]
VGrainlineData::VGrainlineData (const VGrainlineData & data)
Definition at line 48 of file vgrainlinedata.cpp.
~VGrainlineData()
VGrainlineData::~VGrainlineData () virtual
Definition at line 66 of file vgrainlinedata.cpp.
Member Function Documentation
bottomAnchorPoint()
quint32 VGrainlineData::bottomAnchorPoint () const
Definition at line 130 of file vgrainlinedata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), setBottomAnchorPoint(), and PatternPieceDialog::SetPiece().
centerAnchorPoint()
quint32 VGrainlineData::centerAnchorPoint () const
Definition at line 106 of file vgrainlinedata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), and PatternPieceDialog::SetPiece().
GetArrowType()
ArrowType VGrainlineData::GetArrowType () const
Definition at line 94 of file vgrainlinedata.cpp.
References d.
Referenced by VLayoutPiece::setGrainline(), and PatternPieceDialog::SetPiece().
GetLength()
QString VGrainlineData::GetLength () const
Definition at line 70 of file vgrainlinedata.cpp.
References d.
Referenced by QT_WARNING_POP::createUnion(), anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), and PatternPieceDialog::SetPiece().
GetRotation()
QString VGrainlineData::GetRotation () const
Definition at line 82 of file vgrainlinedata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), and PatternPieceDialog::SetPiece().
operator=()
VGrainlineData & VGrainlineData::operator= (const VGrainlineData & data)
Definition at line 54 of file vgrainlinedata.cpp.
References d, and VAbstractFloatItemData::operator=().
SetArrowType()
void VGrainlineData::SetArrowType (ArrowType eAT)
Definition at line 100 of file vgrainlinedata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceGrainline().
setBottomAnchorPoint()
void VGrainlineData::setBottomAnchorPoint (quint32 bottomAnchorPoint)
Definition at line 136 of file vgrainlinedata.cpp.
References bottomAnchorPoint(), and d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceGrainline().
setCenterAnchorPoint()
void VGrainlineData::setCenterAnchorPoint (quint32 centerAnchor)
Definition at line 112 of file vgrainlinedata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceGrainline().
SetLength()
void VGrainlineData::SetLength (const QString & qsLen)
Definition at line 76 of file vgrainlinedata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), QT_WARNING_POP::createUnion(), VPattern::ParsePieceGrainline(), and PatternPieceTool::SaveResizeGrainline().
SetRotation()
void VGrainlineData::SetRotation (const QString & qsRot)
Definition at line 88 of file vgrainlinedata.cpp.
References d.
Referenced by PatternPieceDialog::CreatePiece(), VPattern::ParsePieceGrainline(), and PatternPieceTool::SaveRotateGrainline().
setTopAnchorPoint()
void VGrainlineData::setTopAnchorPoint (quint32 topAnchorPoint)
Definition at line 124 of file vgrainlinedata.cpp.
References d, and topAnchorPoint().
Referenced by PatternPieceDialog::CreatePiece(), and VPattern::ParsePieceGrainline().
Swap()
void VGrainlineData::Swap (VGrainlineData & data)
Definition at line 38 of file vgrainlinedata.cpp.
References VAbstractFloatItemData::Swap().
topAnchorPoint()
quint32 VGrainlineData::topAnchorPoint () const
Definition at line 118 of file vgrainlinedata.cpp.
References d.
Referenced by anonymous_namespace{vlayoutpiece.cpp}::FindGrainlineGeometry(), PatternPieceDialog::SetPiece(), and setTopAnchorPoint().
Member Data Documentation
d
QSharedDataPointer<VGrainlineDataPrivate> VGrainlineData::d private
Definition at line 79 of file vgrainlinedata.h.
Referenced by bottomAnchorPoint(), centerAnchorPoint(), GetArrowType(), GetLength(), GetRotation(), operator=(), SetArrowType(), setBottomAnchorPoint(), setCenterAnchorPoint(), SetLength(), SetRotation(), setTopAnchorPoint(), and topAnchorPoint().
The documentation for this class was generated from the following files:
src/libs/vpatterndb/floatItemData/vgrainlinedata.h
src/libs/vpatterndb/floatItemData/vgrainlinedata.cpp