Seamly2D: TraverseSchema Class Reference
TraverseSchema Class Reference
#include <TraverseSchema.hpp>
Public Member Functions
TraverseSchema (DOMElement *const schemaRoot, XMLStringPool *const uriStringPool, SchemaGrammar *const schemaGrammar, GrammarResolver *const grammarResolver, RefHash2KeysTableOf< SchemaInfo > *cachedSchemaInfoList, RefHash2KeysTableOf< SchemaInfo > *schemaInfoList, XMLScanner *const xmlScanner, const XMLCh *const schemaURL, XMLEntityHandler *const entityHandler, XMLErrorReporter *const errorReporter, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, bool multipleImport=false)
~TraverseSchema ()
TraverseSchema (DOMElement *const schemaRoot, XMLStringPool *const uriStringPool, SchemaGrammar *const schemaGrammar, GrammarResolver *const grammarResolver, RefHash2KeysTableOf< SchemaInfo > *cachedSchemaInfoList, RefHash2KeysTableOf< SchemaInfo > *schemaInfoList, XMLScanner *const xmlScanner, const XMLCh *const schemaURL, XMLEntityHandler *const entityHandler, XMLErrorReporter *const errorReporter, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, bool multipleImport=false)
~TraverseSchema ()
TraverseSchema (DOMElement *const schemaRoot, XMLStringPool *const uriStringPool, SchemaGrammar *const schemaGrammar, GrammarResolver *const grammarResolver, RefHash2KeysTableOf< SchemaInfo > *cachedSchemaInfoList, RefHash2KeysTableOf< SchemaInfo > *schemaInfoList, XMLScanner *const xmlScanner, const XMLCh *const schemaURL, XMLEntityHandler *const entityHandler, XMLErrorReporter *const errorReporter, MemoryManager *const manager=XMLPlatformUtils::fgMemoryManager, bool multipleImport=false)
~TraverseSchema ()
Public Member Functions inherited from XMemory
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
void * operator new (size_t size)
void * operator new (size_t size, MemoryManager *memMgr)
void * operator new (size_t size, void *ptr)
void operator delete (void *p)
void operator delete (void *p, MemoryManager *memMgr)
void operator delete (void *p, void *ptr)
Private Types
enum { Not_All_Context = 0 , All_Element = 1 , Group_Ref_With_All = 2 , All_Group = 4 }
enum {
ES_Block , C_Block , S_Final , EC_Final ,
ECS_Final
}
enum ExceptionCodes {
NoException = 0 , InvalidComplexTypeInfo = 1 , RecursingElement = 2 , NoException = 0 ,
InvalidComplexTypeInfo = 1 , RecursingElement = 2 , NoException = 0 , InvalidComplexTypeInfo = 1 ,
RecursingElement = 2
}
enum { Elem_Def_Qualified = 1 , Attr_Def_Qualified = 2 }
enum { Not_All_Context = 0 , All_Element = 1 , Group_Ref_With_All = 2 , All_Group = 4 }
enum {
ES_Block , C_Block , S_Final , EC_Final ,
ECS_Final
}
enum ExceptionCodes {
NoException = 0 , InvalidComplexTypeInfo = 1 , RecursingElement = 2 , NoException = 0 ,
InvalidComplexTypeInfo = 1 , RecursingElement = 2 , NoException = 0 , InvalidComplexTypeInfo = 1 ,
RecursingElement = 2
}
enum { Elem_Def_Qualified = 1 , Attr_Def_Qualified = 2 }
enum { Not_All_Context = 0 , All_Element = 1 , Group_Ref_With_All = 2 , All_Group = 4 }
enum {
ES_Block , C_Block , S_Final , EC_Final ,
ECS_Final
}
enum ExceptionCodes {
NoException = 0 , InvalidComplexTypeInfo = 1 , RecursingElement = 2 , NoException = 0 ,
InvalidComplexTypeInfo = 1 , RecursingElement = 2 , NoException = 0 , InvalidComplexTypeInfo = 1 ,
RecursingElement = 2
}
enum { Elem_Def_Qualified = 1 , Attr_Def_Qualified = 2 }
Private Member Functions
TraverseSchema (const TraverseSchema &)
TraverseSchema & operator= (const TraverseSchema &)
void init ()
void cleanUp ()
void doTraverseSchema (const DOMElement *const schemaRoot)
void preprocessSchema (DOMElement *const schemaRoot, const XMLCh *const schemaURL, bool multipleImport=false)
void traverseSchemaHeader (const DOMElement *const schemaRoot)
XSAnnotation * traverseAnnotationDecl (const DOMElement *const childElem, ValueVectorOf< DOMNode * > *const nonXSAttList, const bool topLevel=false)
void traverseInclude (const DOMElement *const childElem)
void traverseImport (const DOMElement *const childElem)
void traverseRedefine (const DOMElement *const childElem)
void traverseAttributeDecl (const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const bool topLevel=false)
void traverseSimpleContentDecl (const XMLCh *const typeName, const XMLCh *const qualifiedName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, Janitor< XSAnnotation > *const janAnnot)
void traverseComplexContentDecl (const XMLCh *const typeName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, const bool isMixed, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseSimpleTypeDecl (const DOMElement *const childElem, const bool topLevel=true, int baseRefContext=SchemaSymbols::XSD_EMPTYSET)
int traverseComplexTypeDecl (const DOMElement *const childElem, const bool topLevel=true, const XMLCh *const recursingTypeName=0)
DatatypeValidator * traverseByList (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseByRestriction (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseByUnion (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, int baseRefContext, Janitor< XSAnnotation > *const janAnnot)
SchemaElementDecl * traverseElementDecl (const DOMElement *const childElem, const bool topLevel=false)
const XMLCh * traverseNotationDecl (const DOMElement *const childElem)
const XMLCh * traverseNotationDecl (const DOMElement *const childElem, const XMLCh *const name, const XMLCh *const uriStr)
ContentSpecNode * traverseChoiceSequence (const DOMElement *const elemDecl, const int modelGroupType, bool &hasChildren)
ContentSpecNode * traverseAny (const DOMElement *const anyDecl)
ContentSpecNode * traverseAll (const DOMElement *const allElem, bool &hasChildren)
XercesGroupInfo * traverseGroupDecl (const DOMElement *const childElem, const bool topLevel=true)
XercesAttGroupInfo * traverseAttributeGroupDecl (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const bool topLevel=false)
XercesAttGroupInfo * traverseAttributeGroupDeclNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const name)
SchemaAttDef * traverseAnyAttribute (const DOMElement *const elem)
void traverseKey (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
void traverseUnique (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
void traverseKeyRef (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
bool traverseIdentityConstraint (IdentityConstraint *const ic, const DOMElement *const icElem)
void reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode)
void reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2=0, const XMLCh *const text3=0, const XMLCh *const text4=0)
void reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode)
void reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2=0, const XMLCh *const text3=0, const XMLCh *const text4=0)
void reportSchemaError (const DOMElement *const elem, const XMLException &except)
bool isImportingNS (const int namespaceURI)
void addImportedNS (const int namespaceURI)
bool retrieveNamespaceMapping (const DOMElement *const elem)
void processChildren (const DOMElement *const root)
void preprocessChildren (const DOMElement *const root)
void preprocessImport (const DOMElement *const elemNode)
void preprocessInclude (const DOMElement *const elemNode)
void preprocessRedefine (const DOMElement *const elemNode)
DOMElement * checkContent (const DOMElement *const rootElem, DOMElement *const contentElem, const bool isEmpty, bool processAnnot=true)
const DOMElement * checkIdentityConstraintContent (const DOMElement *const contentElem)
DatatypeValidator * getDatatypeValidator (const XMLCh *const uriStr, const XMLCh *const localPartStr)
DatatypeValidator * checkForSimpleTypeValidator (const DOMElement *const content, int baseRefContext=SchemaSymbols::XSD_EMPTYSET)
ComplexTypeInfo * checkForComplexTypeInfo (const DOMElement *const content)
DatatypeValidator * findDTValidator (const DOMElement *const elem, const XMLCh *const derivedTypeName, const XMLCh *const baseTypeName, const int baseRefContext)
const XMLCh * resolvePrefixToURI (const DOMElement *const elem, const XMLCh *const prefix)
const XMLCh * getPrefix (const XMLCh *const rawName)
const XMLCh * getLocalPart (const XMLCh *const rawName)
SchemaElementDecl * processElementDeclRef (const DOMElement *const elem, const XMLCh *const refName)
void processElemDeclAttrs (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *&valConstraint, bool isTopLevel=false)
void processElemDeclIC (DOMElement *const elem, SchemaElementDecl *const elemDecl)
bool checkElemDeclValueConstraint (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *const valConstraint, ComplexTypeInfo *const typeInfo, DatatypeValidator *const validator)
void processAttributeDeclRef (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const XMLCh *const refName, const XMLCh *const useVal, const XMLCh *const defaultVal, const XMLCh *const fixedVal)
XercesGroupInfo * processGroupRef (const DOMElement *const elem, const XMLCh *const refName)
XercesAttGroupInfo * processAttributeGroupRef (const DOMElement *const elem, const XMLCh *const refName, ComplexTypeInfo *const typeInfo)
int parseBlockSet (const DOMElement *const elem, const int blockType, const bool isRoot=false)
int parseFinalSet (const DOMElement *const elem, const int finalType, const bool isRoot=false)
bool isIdentityConstraintName (const XMLCh *const constraintName)
const XMLCh * checkTypeFromAnotherSchema (const DOMElement *const elem, const XMLCh *const typeStr)
DatatypeValidator * getElementTypeValidator (const DOMElement *const elem, const XMLCh *const typeStr, bool &noErrorDetected, const XMLCh *const otherSchemaURI)
ComplexTypeInfo * getElementComplexTypeInfo (const DOMElement *const elem, const XMLCh *const typeStr, const XMLCh *const otherSchemaURI)
SchemaElementDecl * getGlobalElemDecl (const DOMElement *const elem, const XMLCh *const name)
bool isSubstitutionGroupValid (const DOMElement *const elem, const SchemaElementDecl *const elemDecl, const ComplexTypeInfo *const typeInfo, const DatatypeValidator *const validator, const XMLCh *const elemName, const bool toEmit=true)
bool isSubstitutionGroupCircular (SchemaElementDecl *const elemDecl, SchemaElementDecl *const subsElemDecl)
void processSubstitutionGroup (const DOMElement *const elem, SchemaElementDecl *const elemDecl, ComplexTypeInfo *&typeInfo, DatatypeValidator *&validator, const XMLCh *const subsElemQName)
SchemaElementDecl * createSchemaElementDecl (const DOMElement *const elem, const XMLCh *const name, bool &isDuplicate, const XMLCh *&valConstraint, const bool topLevel)
const XMLCh * getElementAttValue (const DOMElement *const elem, const XMLCh *const attName, const DatatypeValidator::ValidatorType attType=DatatypeValidator::UnKnown)
int checkMinMax (ContentSpecNode *const specNode, const DOMElement *const elem, const int allContext=Not_All_Context)
void processComplexContent (const DOMElement *const elem, const XMLCh *const typeName, const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const XMLCh *const baseLocalPart, const bool isMixed, const bool isBaseAnyType=false)
void processBaseTypeInfo (const DOMElement *const elem, const XMLCh *const baseName, const XMLCh *const localPart, const XMLCh *const uriStr, ComplexTypeInfo *const typeInfo)
bool isBaseFromAnotherSchema (const XMLCh *const baseURI)
ComplexTypeInfo * getTypeInfoFromNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const localPart)
DatatypeValidator * getAttrDatatypeValidatorNS (const DOMElement *const elem, const XMLCh *localPart, const XMLCh *typeURI)
bool isAttrOrAttrGroup (const DOMElement *const elem)
void processAttributes (const DOMElement *const elem, const DOMElement *const attElem, ComplexTypeInfo *const typeInfo, const bool isBaseAnyType=false)
const XMLCh * genAnonTypeName (const XMLCh *const prefix)
void defaultComplexTypeInfo (ComplexTypeInfo *const typeInfo)
InputSource * resolveSchemaLocation (const XMLCh *const loc, const XMLResourceIdentifier::ResourceIdentifierType resourceIdentitiferType, const XMLCh *const nameSpace=0)
void restoreSchemaInfo (SchemaInfo *const toRestore, SchemaInfo::ListType const aListType=SchemaInfo::INCLUDE, const unsigned int saveScope=Grammar::TOP_LEVEL_SCOPE)
void popCurrentTypeNameStack ()
bool emptiableParticle (const ContentSpecNode *const specNode)
void checkFixedFacet (const DOMElement *const, const XMLCh *const, const DatatypeValidator *const, unsigned int &)
void buildValidSubstitutionListF (const DOMElement *const elem, SchemaElementDecl *const, SchemaElementDecl *const)
void buildValidSubstitutionListB (const DOMElement *const elem, SchemaElementDecl *const, SchemaElementDecl *const)
void checkEnumerationRequiredNotation (const DOMElement *const elem, const XMLCh *const name, const XMLCh *const typeStr)
void processElements (const DOMElement *const elem, ComplexTypeInfo *const baseTypeInfo, ComplexTypeInfo *const newTypeInfo)
void processElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, ComplexTypeInfo *const typeInfo)
void copyGroupElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, XercesGroupInfo *const toGroup, ComplexTypeInfo *const typeInfo)
void copyAttGroupAttributes (const DOMElement *const elem, XercesAttGroupInfo *const fromAttGroup, XercesAttGroupInfo *const toAttGroup, ComplexTypeInfo *const typeInfo)
void checkForEmptyTargetNamespace (const DOMElement *const elem)
void attWildCardIntersection (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard)
void attWildCardUnion (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard)
void copyWildCardData (const SchemaAttDef *const srcWildCard, SchemaAttDef *const destWildCard)
void checkAttDerivationOK (const DOMElement *const elem, const ComplexTypeInfo *const baseTypeInfo, const ComplexTypeInfo *const childTypeInfo)
void checkAttDerivationOK (const DOMElement *const elem, const XercesAttGroupInfo *const baseAttGrpInfo, const XercesAttGroupInfo *const childAttGrpInfo)
bool wildcardAllowsNamespace (const SchemaAttDef *const baseAttWildCard, const unsigned int nameURI)
bool isWildCardSubset (const SchemaAttDef *const baseAttWildCard, const SchemaAttDef *const childAttWildCard)
bool openRedefinedSchema (const DOMElement *const redefineElem)
void renameRedefinedComponents (const DOMElement *const redefineElem, SchemaInfo *const redefiningSchemaInfo, SchemaInfo *const redefinedSchemaInfo)
bool validateRedefineNameChange (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildElemName, const XMLCh *const redefineChildDeclName, const int redefineNameCounter, SchemaInfo *const redefiningSchemaInfo)
int changeRedefineGroup (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter)
void fixRedefinedSchema (const DOMElement *const elem, SchemaInfo *const redefinedSchemaInfo, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter)
void getRedefineNewTypeName (const XMLCh *const oldTypeName, const int redefineCounter, XMLBuffer &newTypeName)
void preprocessRedefineInclude (SchemaInfo *const currSchemaInfo)
void updateCircularSubstitutionList (SchemaInfo *const aSchemaInfo)
void processKeyRefFor (SchemaInfo *const aSchemaInfo, ValueVectorOf< SchemaInfo * > *const infoList)
void processAttValue (const XMLCh *const attVal, XMLBuffer &aBuf)
XSAnnotation * generateSyntheticAnnotation (const DOMElement *const elem, ValueVectorOf< DOMNode * > *nonXSAttList)
void validateAnnotations ()
TraverseSchema (const TraverseSchema &)
TraverseSchema & operator= (const TraverseSchema &)
void init ()
void cleanUp ()
void doTraverseSchema (const DOMElement *const schemaRoot)
void preprocessSchema (DOMElement *const schemaRoot, const XMLCh *const schemaURL, bool multipleImport=false)
void traverseSchemaHeader (const DOMElement *const schemaRoot)
XSAnnotation * traverseAnnotationDecl (const DOMElement *const childElem, ValueVectorOf< DOMNode * > *const nonXSAttList, const bool topLevel=false)
void traverseInclude (const DOMElement *const childElem)
void traverseImport (const DOMElement *const childElem)
void traverseRedefine (const DOMElement *const childElem)
void traverseAttributeDecl (const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const bool topLevel=false)
void traverseSimpleContentDecl (const XMLCh *const typeName, const XMLCh *const qualifiedName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, Janitor< XSAnnotation > *const janAnnot)
void traverseComplexContentDecl (const XMLCh *const typeName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, const bool isMixed, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseSimpleTypeDecl (const DOMElement *const childElem, const bool topLevel=true, int baseRefContext=SchemaSymbols::XSD_EMPTYSET)
int traverseComplexTypeDecl (const DOMElement *const childElem, const bool topLevel=true, const XMLCh *const recursingTypeName=0)
DatatypeValidator * traverseByList (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseByRestriction (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseByUnion (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, int baseRefContext, Janitor< XSAnnotation > *const janAnnot)
SchemaElementDecl * traverseElementDecl (const DOMElement *const childElem, const bool topLevel=false)
const XMLCh * traverseNotationDecl (const DOMElement *const childElem)
const XMLCh * traverseNotationDecl (const DOMElement *const childElem, const XMLCh *const name, const XMLCh *const uriStr)
ContentSpecNode * traverseChoiceSequence (const DOMElement *const elemDecl, const int modelGroupType, bool &hasChildren)
ContentSpecNode * traverseAny (const DOMElement *const anyDecl)
ContentSpecNode * traverseAll (const DOMElement *const allElem, bool &hasChildren)
XercesGroupInfo * traverseGroupDecl (const DOMElement *const childElem, const bool topLevel=true)
XercesAttGroupInfo * traverseAttributeGroupDecl (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const bool topLevel=false)
XercesAttGroupInfo * traverseAttributeGroupDeclNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const name)
SchemaAttDef * traverseAnyAttribute (const DOMElement *const elem)
void traverseKey (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
void traverseUnique (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
void traverseKeyRef (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
bool traverseIdentityConstraint (IdentityConstraint *const ic, const DOMElement *const icElem)
void reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode)
void reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2=0, const XMLCh *const text3=0, const XMLCh *const text4=0)
void reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode)
void reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2=0, const XMLCh *const text3=0, const XMLCh *const text4=0)
void reportSchemaError (const DOMElement *const elem, const XMLException &except)
bool isImportingNS (const int namespaceURI)
void addImportedNS (const int namespaceURI)
bool retrieveNamespaceMapping (const DOMElement *const elem)
void processChildren (const DOMElement *const root)
void preprocessChildren (const DOMElement *const root)
void preprocessImport (const DOMElement *const elemNode)
void preprocessInclude (const DOMElement *const elemNode)
void preprocessRedefine (const DOMElement *const elemNode)
DOMElement * checkContent (const DOMElement *const rootElem, DOMElement *const contentElem, const bool isEmpty, bool processAnnot=true)
const DOMElement * checkIdentityConstraintContent (const DOMElement *const contentElem)
DatatypeValidator * getDatatypeValidator (const XMLCh *const uriStr, const XMLCh *const localPartStr)
DatatypeValidator * checkForSimpleTypeValidator (const DOMElement *const content, int baseRefContext=SchemaSymbols::XSD_EMPTYSET)
ComplexTypeInfo * checkForComplexTypeInfo (const DOMElement *const content)
DatatypeValidator * findDTValidator (const DOMElement *const elem, const XMLCh *const derivedTypeName, const XMLCh *const baseTypeName, const int baseRefContext)
const XMLCh * resolvePrefixToURI (const DOMElement *const elem, const XMLCh *const prefix)
const XMLCh * getPrefix (const XMLCh *const rawName)
const XMLCh * getLocalPart (const XMLCh *const rawName)
SchemaElementDecl * processElementDeclRef (const DOMElement *const elem, const XMLCh *const refName)
void processElemDeclAttrs (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *&valConstraint, bool isTopLevel=false)
void processElemDeclIC (DOMElement *const elem, SchemaElementDecl *const elemDecl)
bool checkElemDeclValueConstraint (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *const valConstraint, ComplexTypeInfo *const typeInfo, DatatypeValidator *const validator)
void processAttributeDeclRef (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const XMLCh *const refName, const XMLCh *const useVal, const XMLCh *const defaultVal, const XMLCh *const fixedVal)
XercesGroupInfo * processGroupRef (const DOMElement *const elem, const XMLCh *const refName)
XercesAttGroupInfo * processAttributeGroupRef (const DOMElement *const elem, const XMLCh *const refName, ComplexTypeInfo *const typeInfo)
int parseBlockSet (const DOMElement *const elem, const int blockType, const bool isRoot=false)
int parseFinalSet (const DOMElement *const elem, const int finalType, const bool isRoot=false)
bool isIdentityConstraintName (const XMLCh *const constraintName)
const XMLCh * checkTypeFromAnotherSchema (const DOMElement *const elem, const XMLCh *const typeStr)
DatatypeValidator * getElementTypeValidator (const DOMElement *const elem, const XMLCh *const typeStr, bool &noErrorDetected, const XMLCh *const otherSchemaURI)
ComplexTypeInfo * getElementComplexTypeInfo (const DOMElement *const elem, const XMLCh *const typeStr, const XMLCh *const otherSchemaURI)
SchemaElementDecl * getGlobalElemDecl (const DOMElement *const elem, const XMLCh *const name)
bool isSubstitutionGroupValid (const DOMElement *const elem, const SchemaElementDecl *const elemDecl, const ComplexTypeInfo *const typeInfo, const DatatypeValidator *const validator, const XMLCh *const elemName, const bool toEmit=true)
bool isSubstitutionGroupCircular (SchemaElementDecl *const elemDecl, SchemaElementDecl *const subsElemDecl)
void processSubstitutionGroup (const DOMElement *const elem, SchemaElementDecl *const elemDecl, ComplexTypeInfo *&typeInfo, DatatypeValidator *&validator, const XMLCh *const subsElemQName)
SchemaElementDecl * createSchemaElementDecl (const DOMElement *const elem, const XMLCh *const name, bool &isDuplicate, const XMLCh *&valConstraint, const bool topLevel)
const XMLCh * getElementAttValue (const DOMElement *const elem, const XMLCh *const attName, const DatatypeValidator::ValidatorType attType=DatatypeValidator::UnKnown)
int checkMinMax (ContentSpecNode *const specNode, const DOMElement *const elem, const int allContext=Not_All_Context)
void processComplexContent (const DOMElement *const elem, const XMLCh *const typeName, const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const XMLCh *const baseLocalPart, const bool isMixed, const bool isBaseAnyType=false)
void processBaseTypeInfo (const DOMElement *const elem, const XMLCh *const baseName, const XMLCh *const localPart, const XMLCh *const uriStr, ComplexTypeInfo *const typeInfo)
bool isBaseFromAnotherSchema (const XMLCh *const baseURI)
ComplexTypeInfo * getTypeInfoFromNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const localPart)
DatatypeValidator * getAttrDatatypeValidatorNS (const DOMElement *const elem, const XMLCh *localPart, const XMLCh *typeURI)
bool isAttrOrAttrGroup (const DOMElement *const elem)
void processAttributes (const DOMElement *const elem, const DOMElement *const attElem, ComplexTypeInfo *const typeInfo, const bool isBaseAnyType=false)
const XMLCh * genAnonTypeName (const XMLCh *const prefix)
void defaultComplexTypeInfo (ComplexTypeInfo *const typeInfo)
InputSource * resolveSchemaLocation (const XMLCh *const loc, const XMLResourceIdentifier::ResourceIdentifierType resourceIdentitiferType, const XMLCh *const nameSpace=0)
void restoreSchemaInfo (SchemaInfo *const toRestore, SchemaInfo::ListType const aListType=SchemaInfo::INCLUDE, const unsigned int saveScope=Grammar::TOP_LEVEL_SCOPE)
void popCurrentTypeNameStack ()
bool emptiableParticle (const ContentSpecNode *const specNode)
void checkFixedFacet (const DOMElement *const, const XMLCh *const, const DatatypeValidator *const, unsigned int &)
void buildValidSubstitutionListF (const DOMElement *const elem, SchemaElementDecl *const, SchemaElementDecl *const)
void buildValidSubstitutionListB (const DOMElement *const elem, SchemaElementDecl *const, SchemaElementDecl *const)
void checkEnumerationRequiredNotation (const DOMElement *const elem, const XMLCh *const name, const XMLCh *const typeStr)
void processElements (const DOMElement *const elem, ComplexTypeInfo *const baseTypeInfo, ComplexTypeInfo *const newTypeInfo)
void processElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, ComplexTypeInfo *const typeInfo)
void copyGroupElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, XercesGroupInfo *const toGroup, ComplexTypeInfo *const typeInfo)
void copyAttGroupAttributes (const DOMElement *const elem, XercesAttGroupInfo *const fromAttGroup, XercesAttGroupInfo *const toAttGroup, ComplexTypeInfo *const typeInfo)
void checkForEmptyTargetNamespace (const DOMElement *const elem)
void attWildCardIntersection (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard)
void attWildCardUnion (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard)
void copyWildCardData (const SchemaAttDef *const srcWildCard, SchemaAttDef *const destWildCard)
void checkAttDerivationOK (const DOMElement *const elem, const ComplexTypeInfo *const baseTypeInfo, const ComplexTypeInfo *const childTypeInfo)
void checkAttDerivationOK (const DOMElement *const elem, const XercesAttGroupInfo *const baseAttGrpInfo, const XercesAttGroupInfo *const childAttGrpInfo)
bool wildcardAllowsNamespace (const SchemaAttDef *const baseAttWildCard, const unsigned int nameURI)
bool isWildCardSubset (const SchemaAttDef *const baseAttWildCard, const SchemaAttDef *const childAttWildCard)
bool openRedefinedSchema (const DOMElement *const redefineElem)
void renameRedefinedComponents (const DOMElement *const redefineElem, SchemaInfo *const redefiningSchemaInfo, SchemaInfo *const redefinedSchemaInfo)
bool validateRedefineNameChange (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildElemName, const XMLCh *const redefineChildDeclName, const int redefineNameCounter, SchemaInfo *const redefiningSchemaInfo)
int changeRedefineGroup (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter)
void fixRedefinedSchema (const DOMElement *const elem, SchemaInfo *const redefinedSchemaInfo, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter)
void getRedefineNewTypeName (const XMLCh *const oldTypeName, const int redefineCounter, XMLBuffer &newTypeName)
void preprocessRedefineInclude (SchemaInfo *const currSchemaInfo)
void updateCircularSubstitutionList (SchemaInfo *const aSchemaInfo)
void processKeyRefFor (SchemaInfo *const aSchemaInfo, ValueVectorOf< SchemaInfo * > *const infoList)
void processAttValue (const XMLCh *const attVal, XMLBuffer &aBuf)
XSAnnotation * generateSyntheticAnnotation (const DOMElement *const elem, ValueVectorOf< DOMNode * > *nonXSAttList)
void validateAnnotations ()
TraverseSchema (const TraverseSchema &)
TraverseSchema & operator= (const TraverseSchema &)
void init ()
void cleanUp ()
void doTraverseSchema (const DOMElement *const schemaRoot)
void preprocessSchema (DOMElement *const schemaRoot, const XMLCh *const schemaURL, bool multipleImport=false)
void traverseSchemaHeader (const DOMElement *const schemaRoot)
XSAnnotation * traverseAnnotationDecl (const DOMElement *const childElem, ValueVectorOf< DOMNode * > *const nonXSAttList, const bool topLevel=false)
void traverseInclude (const DOMElement *const childElem)
void traverseImport (const DOMElement *const childElem)
void traverseRedefine (const DOMElement *const childElem)
void traverseAttributeDecl (const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const bool topLevel=false)
void traverseSimpleContentDecl (const XMLCh *const typeName, const XMLCh *const qualifiedName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, Janitor< XSAnnotation > *const janAnnot)
void traverseComplexContentDecl (const XMLCh *const typeName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, const bool isMixed, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseSimpleTypeDecl (const DOMElement *const childElem, const bool topLevel=true, int baseRefContext=SchemaSymbols::XSD_EMPTYSET)
int traverseComplexTypeDecl (const DOMElement *const childElem, const bool topLevel=true, const XMLCh *const recursingTypeName=0)
DatatypeValidator * traverseByList (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseByRestriction (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot)
DatatypeValidator * traverseByUnion (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, int baseRefContext, Janitor< XSAnnotation > *const janAnnot)
SchemaElementDecl * traverseElementDecl (const DOMElement *const childElem, const bool topLevel=false)
const XMLCh * traverseNotationDecl (const DOMElement *const childElem)
const XMLCh * traverseNotationDecl (const DOMElement *const childElem, const XMLCh *const name, const XMLCh *const uriStr)
ContentSpecNode * traverseChoiceSequence (const DOMElement *const elemDecl, const int modelGroupType, bool &hasChildren)
ContentSpecNode * traverseAny (const DOMElement *const anyDecl)
ContentSpecNode * traverseAll (const DOMElement *const allElem, bool &hasChildren)
XercesGroupInfo * traverseGroupDecl (const DOMElement *const childElem, const bool topLevel=true)
XercesAttGroupInfo * traverseAttributeGroupDecl (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const bool topLevel=false)
XercesAttGroupInfo * traverseAttributeGroupDeclNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const name)
SchemaAttDef * traverseAnyAttribute (const DOMElement *const elem)
void traverseKey (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
void traverseUnique (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
void traverseKeyRef (const DOMElement *const icElem, SchemaElementDecl *const elemDecl)
bool traverseIdentityConstraint (IdentityConstraint *const ic, const DOMElement *const icElem)
void reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode)
void reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2=0, const XMLCh *const text3=0, const XMLCh *const text4=0)
void reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode)
void reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2=0, const XMLCh *const text3=0, const XMLCh *const text4=0)
void reportSchemaError (const DOMElement *const elem, const XMLException &except)
bool isImportingNS (const int namespaceURI)
void addImportedNS (const int namespaceURI)
bool retrieveNamespaceMapping (const DOMElement *const elem)
void processChildren (const DOMElement *const root)
void preprocessChildren (const DOMElement *const root)
void preprocessImport (const DOMElement *const elemNode)
void preprocessInclude (const DOMElement *const elemNode)
void preprocessRedefine (const DOMElement *const elemNode)
DOMElement * checkContent (const DOMElement *const rootElem, DOMElement *const contentElem, const bool isEmpty, bool processAnnot=true)
const DOMElement * checkIdentityConstraintContent (const DOMElement *const contentElem)
DatatypeValidator * getDatatypeValidator (const XMLCh *const uriStr, const XMLCh *const localPartStr)
DatatypeValidator * checkForSimpleTypeValidator (const DOMElement *const content, int baseRefContext=SchemaSymbols::XSD_EMPTYSET)
ComplexTypeInfo * checkForComplexTypeInfo (const DOMElement *const content)
DatatypeValidator * findDTValidator (const DOMElement *const elem, const XMLCh *const derivedTypeName, const XMLCh *const baseTypeName, const int baseRefContext)
const XMLCh * resolvePrefixToURI (const DOMElement *const elem, const XMLCh *const prefix)
const XMLCh * getPrefix (const XMLCh *const rawName)
const XMLCh * getLocalPart (const XMLCh *const rawName)
SchemaElementDecl * processElementDeclRef (const DOMElement *const elem, const XMLCh *const refName)
void processElemDeclAttrs (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *&valConstraint, bool isTopLevel=false)
void processElemDeclIC (DOMElement *const elem, SchemaElementDecl *const elemDecl)
bool checkElemDeclValueConstraint (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *const valConstraint, ComplexTypeInfo *const typeInfo, DatatypeValidator *const validator)
void processAttributeDeclRef (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const XMLCh *const refName, const XMLCh *const useVal, const XMLCh *const defaultVal, const XMLCh *const fixedVal)
XercesGroupInfo * processGroupRef (const DOMElement *const elem, const XMLCh *const refName)
XercesAttGroupInfo * processAttributeGroupRef (const DOMElement *const elem, const XMLCh *const refName, ComplexTypeInfo *const typeInfo)
int parseBlockSet (const DOMElement *const elem, const int blockType, const bool isRoot=false)
int parseFinalSet (const DOMElement *const elem, const int finalType, const bool isRoot=false)
bool isIdentityConstraintName (const XMLCh *const constraintName)
const XMLCh * checkTypeFromAnotherSchema (const DOMElement *const elem, const XMLCh *const typeStr)
DatatypeValidator * getElementTypeValidator (const DOMElement *const elem, const XMLCh *const typeStr, bool &noErrorDetected, const XMLCh *const otherSchemaURI)
ComplexTypeInfo * getElementComplexTypeInfo (const DOMElement *const elem, const XMLCh *const typeStr, const XMLCh *const otherSchemaURI)
SchemaElementDecl * getGlobalElemDecl (const DOMElement *const elem, const XMLCh *const name)
bool isSubstitutionGroupValid (const DOMElement *const elem, const SchemaElementDecl *const elemDecl, const ComplexTypeInfo *const typeInfo, const DatatypeValidator *const validator, const XMLCh *const elemName, const bool toEmit=true)
bool isSubstitutionGroupCircular (SchemaElementDecl *const elemDecl, SchemaElementDecl *const subsElemDecl)
void processSubstitutionGroup (const DOMElement *const elem, SchemaElementDecl *const elemDecl, ComplexTypeInfo *&typeInfo, DatatypeValidator *&validator, const XMLCh *const subsElemQName)
SchemaElementDecl * createSchemaElementDecl (const DOMElement *const elem, const XMLCh *const name, bool &isDuplicate, const XMLCh *&valConstraint, const bool topLevel)
const XMLCh * getElementAttValue (const DOMElement *const elem, const XMLCh *const attName, const DatatypeValidator::ValidatorType attType=DatatypeValidator::UnKnown)
int checkMinMax (ContentSpecNode *const specNode, const DOMElement *const elem, const int allContext=Not_All_Context)
void processComplexContent (const DOMElement *const elem, const XMLCh *const typeName, const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const XMLCh *const baseLocalPart, const bool isMixed, const bool isBaseAnyType=false)
void processBaseTypeInfo (const DOMElement *const elem, const XMLCh *const baseName, const XMLCh *const localPart, const XMLCh *const uriStr, ComplexTypeInfo *const typeInfo)
bool isBaseFromAnotherSchema (const XMLCh *const baseURI)
ComplexTypeInfo * getTypeInfoFromNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const localPart)
DatatypeValidator * getAttrDatatypeValidatorNS (const DOMElement *const elem, const XMLCh *localPart, const XMLCh *typeURI)
bool isAttrOrAttrGroup (const DOMElement *const elem)
void processAttributes (const DOMElement *const elem, const DOMElement *const attElem, ComplexTypeInfo *const typeInfo, const bool isBaseAnyType=false)
const XMLCh * genAnonTypeName (const XMLCh *const prefix)
void defaultComplexTypeInfo (ComplexTypeInfo *const typeInfo)
InputSource * resolveSchemaLocation (const XMLCh *const loc, const XMLResourceIdentifier::ResourceIdentifierType resourceIdentitiferType, const XMLCh *const nameSpace=0)
void restoreSchemaInfo (SchemaInfo *const toRestore, SchemaInfo::ListType const aListType=SchemaInfo::INCLUDE, const unsigned int saveScope=Grammar::TOP_LEVEL_SCOPE)
void popCurrentTypeNameStack ()
bool emptiableParticle (const ContentSpecNode *const specNode)
void checkFixedFacet (const DOMElement *const, const XMLCh *const, const DatatypeValidator *const, unsigned int &)
void buildValidSubstitutionListF (const DOMElement *const elem, SchemaElementDecl *const, SchemaElementDecl *const)
void buildValidSubstitutionListB (const DOMElement *const elem, SchemaElementDecl *const, SchemaElementDecl *const)
void checkEnumerationRequiredNotation (const DOMElement *const elem, const XMLCh *const name, const XMLCh *const typeStr)
void processElements (const DOMElement *const elem, ComplexTypeInfo *const baseTypeInfo, ComplexTypeInfo *const newTypeInfo)
void processElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, ComplexTypeInfo *const typeInfo)
void copyGroupElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, XercesGroupInfo *const toGroup, ComplexTypeInfo *const typeInfo)
void copyAttGroupAttributes (const DOMElement *const elem, XercesAttGroupInfo *const fromAttGroup, XercesAttGroupInfo *const toAttGroup, ComplexTypeInfo *const typeInfo)
void checkForEmptyTargetNamespace (const DOMElement *const elem)
void attWildCardIntersection (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard)
void attWildCardUnion (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard)
void copyWildCardData (const SchemaAttDef *const srcWildCard, SchemaAttDef *const destWildCard)
void checkAttDerivationOK (const DOMElement *const elem, const ComplexTypeInfo *const baseTypeInfo, const ComplexTypeInfo *const childTypeInfo)
void checkAttDerivationOK (const DOMElement *const elem, const XercesAttGroupInfo *const baseAttGrpInfo, const XercesAttGroupInfo *const childAttGrpInfo)
bool wildcardAllowsNamespace (const SchemaAttDef *const baseAttWildCard, const unsigned int nameURI)
bool isWildCardSubset (const SchemaAttDef *const baseAttWildCard, const SchemaAttDef *const childAttWildCard)
bool openRedefinedSchema (const DOMElement *const redefineElem)
void renameRedefinedComponents (const DOMElement *const redefineElem, SchemaInfo *const redefiningSchemaInfo, SchemaInfo *const redefinedSchemaInfo)
bool validateRedefineNameChange (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildElemName, const XMLCh *const redefineChildDeclName, const int redefineNameCounter, SchemaInfo *const redefiningSchemaInfo)
int changeRedefineGroup (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter)
void fixRedefinedSchema (const DOMElement *const elem, SchemaInfo *const redefinedSchemaInfo, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter)
void getRedefineNewTypeName (const XMLCh *const oldTypeName, const int redefineCounter, XMLBuffer &newTypeName)
void preprocessRedefineInclude (SchemaInfo *const currSchemaInfo)
void updateCircularSubstitutionList (SchemaInfo *const aSchemaInfo)
void processKeyRefFor (SchemaInfo *const aSchemaInfo, ValueVectorOf< SchemaInfo * > *const infoList)
void processAttValue (const XMLCh *const attVal, XMLBuffer &aBuf)
XSAnnotation * generateSyntheticAnnotation (const DOMElement *const elem, ValueVectorOf< DOMNode * > *nonXSAttList)
void validateAnnotations ()
Private Attributes
bool fFullConstraintChecking
int fTargetNSURI
int fEmptyNamespaceURI
unsigned int fCurrentScope
unsigned int fScopeCount
unsigned int fAnonXSTypeCount
XMLSize_t fCircularCheckIndex
const XMLCh * fTargetNSURIString
DatatypeValidatorFactory * fDatatypeRegistry
GrammarResolver * fGrammarResolver
SchemaGrammar * fSchemaGrammar
XMLEntityHandler * fEntityHandler
XMLErrorReporter * fErrorReporter
XMLStringPool * fURIStringPool
XMLStringPool * fStringPool
XMLBuffer fBuffer
XMLScanner * fScanner
RefHashTableOf< XMLAttDef > * fAttributeDeclRegistry
RefHashTableOf< ComplexTypeInfo > * fComplexTypeRegistry
RefHashTableOf< XercesGroupInfo > * fGroupRegistry
RefHashTableOf< XercesAttGroupInfo > * fAttGroupRegistry
RefHashTableOf< ElemVector > * fIC_ElementsNS
RefHashTableOf< SchemaInfo, PtrHasher > * fPreprocessedNodes
SchemaInfo * fSchemaInfo
XercesGroupInfo * fCurrentGroupInfo
XercesAttGroupInfo * fCurrentAttGroupInfo
ComplexTypeInfo * fCurrentComplexType
ValueVectorOf< unsigned int > * fCurrentTypeNameStack
ValueVectorOf< unsigned int > * fCurrentGroupStack
ValueVectorOf< SchemaElementDecl * > * fIC_Elements
ValueVectorOf< const DOMElement * > * fDeclStack
ValueVectorOf< unsigned int > ** fGlobalDeclarations
ValueVectorOf< DOMNode * > * fNonXSAttList
ValueVectorOf< int > * fImportedNSList
RefHashTableOf< ValueVectorOf< DOMElement * >, PtrHasher > * fIC_NodeListNS
RefHash2KeysTableOf< XMLCh > * fNotationRegistry
RefHash2KeysTableOf< XMLCh > * fRedefineComponents
RefHash2KeysTableOf< IdentityConstraint > * fIdentityConstraintNames
RefHash2KeysTableOf< ElemVector > * fValidSubstitutionGroups
RefHash2KeysTableOf< SchemaInfo > * fSchemaInfoList
RefHash2KeysTableOf< SchemaInfo > * fCachedSchemaInfoList
XSDDOMParser * fParser
XSDErrorReporter fXSDErrorReporter
XSDLocator * fLocator
MemoryManager * fMemoryManager
MemoryManager * fGrammarPoolMemoryManager
XSAnnotation * fAnnotation
GeneralAttributeCheck fAttributeCheck
Friends
class GeneralAttributeCheck
class NamespaceScopeManager
Additional Inherited Members
Protected Member Functions inherited from XMemory
XMemory ()
XMemory ()
XMemory ()
Detailed Description
Definition at line 72 of file TraverseSchema.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
Not_All_Context
All_Element
Group_Ref_With_All
All_Group
Definition at line 108 of file TraverseSchema.hpp.
anonymous enum
anonymous enum private
Enumerator
ES_Block
C_Block
S_Final
EC_Final
ECS_Final
Definition at line 710 of file TraverseSchema.hpp.
anonymous enum
anonymous enum private
Enumerator
Elem_Def_Qualified
Attr_Def_Qualified
Definition at line 726 of file TraverseSchema.hpp.
anonymous enum
anonymous enum private
Enumerator
Not_All_Context
All_Element
Group_Ref_With_All
All_Group
Definition at line 108 of file TraverseSchema.hpp.
anonymous enum
anonymous enum private
Enumerator
ES_Block
C_Block
S_Final
EC_Final
ECS_Final
Definition at line 710 of file TraverseSchema.hpp.
anonymous enum
anonymous enum private
Enumerator
Elem_Def_Qualified
Attr_Def_Qualified
Definition at line 726 of file TraverseSchema.hpp.
anonymous enum
anonymous enum private
Enumerator
Not_All_Context
All_Element
Group_Ref_With_All
All_Group
Definition at line 108 of file TraverseSchema.hpp.
anonymous enum
anonymous enum private
Enumerator
ES_Block
C_Block
S_Final
EC_Final
ECS_Final
Definition at line 710 of file TraverseSchema.hpp.
anonymous enum
anonymous enum private
Enumerator
Elem_Def_Qualified
Attr_Def_Qualified
Definition at line 726 of file TraverseSchema.hpp.
ExceptionCodes [1/3]
enum TraverseSchema::ExceptionCodes private
Enumerator
NoException
InvalidComplexTypeInfo
RecursingElement
NoException
InvalidComplexTypeInfo
RecursingElement
NoException
InvalidComplexTypeInfo
RecursingElement
Definition at line 719 of file TraverseSchema.hpp.
ExceptionCodes [2/3]
enum TraverseSchema::ExceptionCodes private
Enumerator
NoException
InvalidComplexTypeInfo
RecursingElement
NoException
InvalidComplexTypeInfo
RecursingElement
NoException
InvalidComplexTypeInfo
RecursingElement
Definition at line 719 of file TraverseSchema.hpp.
ExceptionCodes [3/3]
enum TraverseSchema::ExceptionCodes private
Enumerator
NoException
InvalidComplexTypeInfo
RecursingElement
NoException
InvalidComplexTypeInfo
RecursingElement
NoException
InvalidComplexTypeInfo
RecursingElement
Definition at line 719 of file TraverseSchema.hpp.
Constructor & Destructor Documentation
TraverseSchema() [1/6]
TraverseSchema::TraverseSchema (DOMElement *const schemaRoot, XMLStringPool *const uriStringPool, SchemaGrammar *const schemaGrammar, GrammarResolver *const grammarResolver, RefHash2KeysTableOf< SchemaInfo > * cachedSchemaInfoList, RefHash2KeysTableOf< SchemaInfo > * schemaInfoList, XMLScanner *const xmlScanner, const XMLCh *const schemaURL, XMLEntityHandler *const entityHandler, XMLErrorReporter *const errorReporter, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, bool multipleImport = false)
~TraverseSchema() [1/3]
TraverseSchema::~TraverseSchema ()
TraverseSchema() [2/6]
TraverseSchema::TraverseSchema (const TraverseSchema &) private
TraverseSchema() [3/6]
TraverseSchema::TraverseSchema (DOMElement *const schemaRoot, XMLStringPool *const uriStringPool, SchemaGrammar *const schemaGrammar, GrammarResolver *const grammarResolver, RefHash2KeysTableOf< SchemaInfo > * cachedSchemaInfoList, RefHash2KeysTableOf< SchemaInfo > * schemaInfoList, XMLScanner *const xmlScanner, const XMLCh *const schemaURL, XMLEntityHandler *const entityHandler, XMLErrorReporter *const errorReporter, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, bool multipleImport = false)
~TraverseSchema() [2/3]
TraverseSchema::~TraverseSchema ()
TraverseSchema() [4/6]
TraverseSchema::TraverseSchema (const TraverseSchema &) private
TraverseSchema() [5/6]
TraverseSchema::TraverseSchema (DOMElement *const schemaRoot, XMLStringPool *const uriStringPool, SchemaGrammar *const schemaGrammar, GrammarResolver *const grammarResolver, RefHash2KeysTableOf< SchemaInfo > * cachedSchemaInfoList, RefHash2KeysTableOf< SchemaInfo > * schemaInfoList, XMLScanner *const xmlScanner, const XMLCh *const schemaURL, XMLEntityHandler *const entityHandler, XMLErrorReporter *const errorReporter, MemoryManager *const manager = XMLPlatformUtils::fgMemoryManager, bool multipleImport = false)
~TraverseSchema() [3/3]
TraverseSchema::~TraverseSchema ()
TraverseSchema() [6/6]
TraverseSchema::TraverseSchema (const TraverseSchema &) private
Member Function Documentation
addImportedNS() [1/3]
void TraverseSchema::addImportedNS (const int namespaceURI) inline private
Definition at line 909 of file TraverseSchema.hpp.
References ValueVectorOf< TElem >::addElement(), ValueVectorOf< TElem >::containsElement(), fImportedNSList, and fMemoryManager.
addImportedNS() [2/3]
void TraverseSchema::addImportedNS (const int namespaceURI) private
addImportedNS() [3/3]
void TraverseSchema::addImportedNS (const int namespaceURI) private
attWildCardIntersection() [1/3]
void TraverseSchema::attWildCardIntersection (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard) private
Attribute wild card intersection.
Note: The first parameter will be the result of the intersection, so we need to make sure that first parameter is a copy of the actual attribute definition we need to intersect with.
What we need to wory about is: type, defaultType, namespace, and URI. All remaining data members should be the same.
attWildCardIntersection() [2/3]
void TraverseSchema::attWildCardIntersection (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard) private
Attribute wild card intersection.
Note: The first parameter will be the result of the intersection, so we need to make sure that first parameter is a copy of the actual attribute definition we need to intersect with.
What we need to wory about is: type, defaultType, namespace, and URI. All remaining data members should be the same.
attWildCardIntersection() [3/3]
void TraverseSchema::attWildCardIntersection (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard) private
Attribute wild card intersection.
Note: The first parameter will be the result of the intersection, so we need to make sure that first parameter is a copy of the actual attribute definition we need to intersect with.
What we need to wory about is: type, defaultType, namespace, and URI. All remaining data members should be the same.
attWildCardUnion() [1/3]
void TraverseSchema::attWildCardUnion (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard) private
Attribute wild card union.
Note: The first parameter will be the result of the union, so we need to make sure that first parameter is a copy of the actual attribute definition we need to intersect with.
What we need to wory about is: type, defaultType, namespace, and URI. All remaining data members should be the same.
attWildCardUnion() [2/3]
void TraverseSchema::attWildCardUnion (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard) private
Attribute wild card union.
Note: The first parameter will be the result of the union, so we need to make sure that first parameter is a copy of the actual attribute definition we need to intersect with.
What we need to wory about is: type, defaultType, namespace, and URI. All remaining data members should be the same.
attWildCardUnion() [3/3]
void TraverseSchema::attWildCardUnion (SchemaAttDef *const resultWildCart, const SchemaAttDef *const toCompareWildCard) private
Attribute wild card union.
Note: The first parameter will be the result of the union, so we need to make sure that first parameter is a copy of the actual attribute definition we need to intersect with.
What we need to wory about is: type, defaultType, namespace, and URI. All remaining data members should be the same.
buildValidSubstitutionListB() [1/3]
void TraverseSchema::buildValidSubstitutionListB (const DOMElement *const elem, SchemaElementDecl * const , SchemaElementDecl * const) private
buildValidSubstitutionListB() [2/3]
void TraverseSchema::buildValidSubstitutionListB (const DOMElement *const elem, SchemaElementDecl * const , SchemaElementDecl * const) private
buildValidSubstitutionListB() [3/3]
void TraverseSchema::buildValidSubstitutionListB (const DOMElement *const elem, SchemaElementDecl * const , SchemaElementDecl * const) private
buildValidSubstitutionListF() [1/3]
void TraverseSchema::buildValidSubstitutionListF (const DOMElement *const elem, SchemaElementDecl * const , SchemaElementDecl * const) private
buildValidSubstitutionListF() [2/3]
void TraverseSchema::buildValidSubstitutionListF (const DOMElement *const elem, SchemaElementDecl * const , SchemaElementDecl * const) private
buildValidSubstitutionListF() [3/3]
void TraverseSchema::buildValidSubstitutionListF (const DOMElement *const elem, SchemaElementDecl * const , SchemaElementDecl * const) private
changeRedefineGroup() [1/3]
int TraverseSchema::changeRedefineGroup (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter) private
This function looks among the children of 'redefineChildElem' for a component of type 'redefineChildComponentName'. If it finds one, it evaluates whether its ref attribute contains a reference to 'refChildTypeName'. If it does, it returns 1 + the value returned by calls to itself on all other children. In all other cases it returns 0 plus the sum of the values returned by calls to itself on redefineChildElem's children. It also resets the value of ref so that it will refer to the renamed type from the schema being redefined.
changeRedefineGroup() [2/3]
int TraverseSchema::changeRedefineGroup (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter) private
This function looks among the children of 'redefineChildElem' for a component of type 'redefineChildComponentName'. If it finds one, it evaluates whether its ref attribute contains a reference to 'refChildTypeName'. If it does, it returns 1 + the value returned by calls to itself on all other children. In all other cases it returns 0 plus the sum of the values returned by calls to itself on redefineChildElem's children. It also resets the value of ref so that it will refer to the renamed type from the schema being redefined.
changeRedefineGroup() [3/3]
int TraverseSchema::changeRedefineGroup (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter) private
This function looks among the children of 'redefineChildElem' for a component of type 'redefineChildComponentName'. If it finds one, it evaluates whether its ref attribute contains a reference to 'refChildTypeName'. If it does, it returns 1 + the value returned by calls to itself on all other children. In all other cases it returns 0 plus the sum of the values returned by calls to itself on redefineChildElem's children. It also resets the value of ref so that it will refer to the renamed type from the schema being redefined.
checkAttDerivationOK() [1/6]
void TraverseSchema::checkAttDerivationOK (const DOMElement *const elem, const ComplexTypeInfo *const baseTypeInfo, const ComplexTypeInfo *const childTypeInfo) private
Check that the attributes of a type derived by restriction satisfy the constraints of derivation valid restriction
checkAttDerivationOK() [2/6]
void TraverseSchema::checkAttDerivationOK (const DOMElement *const elem, const ComplexTypeInfo *const baseTypeInfo, const ComplexTypeInfo *const childTypeInfo) private
Check that the attributes of a type derived by restriction satisfy the constraints of derivation valid restriction
checkAttDerivationOK() [3/6]
void TraverseSchema::checkAttDerivationOK (const DOMElement *const elem, const ComplexTypeInfo *const baseTypeInfo, const ComplexTypeInfo *const childTypeInfo) private
Check that the attributes of a type derived by restriction satisfy the constraints of derivation valid restriction
checkAttDerivationOK() [4/6]
void TraverseSchema::checkAttDerivationOK (const DOMElement *const elem, const XercesAttGroupInfo *const baseAttGrpInfo, const XercesAttGroupInfo *const childAttGrpInfo) private
checkAttDerivationOK() [5/6]
void TraverseSchema::checkAttDerivationOK (const DOMElement *const elem, const XercesAttGroupInfo *const baseAttGrpInfo, const XercesAttGroupInfo *const childAttGrpInfo) private
checkAttDerivationOK() [6/6]
void TraverseSchema::checkAttDerivationOK (const DOMElement *const elem, const XercesAttGroupInfo *const baseAttGrpInfo, const XercesAttGroupInfo *const childAttGrpInfo) private
checkContent() [1/3]
DOMElement* TraverseSchema::checkContent (const DOMElement *const rootElem, DOMElement *const contentElem, const bool isEmpty, bool processAnnot = true) private
Parameters: rootElem - top element for a given type declaration contentElem - content must be annotation? or some other simple content isEmpty: - true if (annotation?, smth_else), false if (annotation?) processAnnot - default is true, false if reprocessing a complex type since we have already processed the annotation.
Check for Annotation if it is present, traverse it. If a sibling is found and it is not an annotation return it, otherwise return 0. Used by traverseSimpleTypeDecl.
checkContent() [2/3]
DOMElement* TraverseSchema::checkContent (const DOMElement *const rootElem, DOMElement *const contentElem, const bool isEmpty, bool processAnnot = true) private
Parameters: rootElem - top element for a given type declaration contentElem - content must be annotation? or some other simple content isEmpty: - true if (annotation?, smth_else), false if (annotation?) processAnnot - default is true, false if reprocessing a complex type since we have already processed the annotation.
Check for Annotation if it is present, traverse it. If a sibling is found and it is not an annotation return it, otherwise return 0. Used by traverseSimpleTypeDecl.
checkContent() [3/3]
DOMElement* TraverseSchema::checkContent (const DOMElement *const rootElem, DOMElement *const contentElem, const bool isEmpty, bool processAnnot = true) private
Parameters: rootElem - top element for a given type declaration contentElem - content must be annotation? or some other simple content isEmpty: - true if (annotation?, smth_else), false if (annotation?) processAnnot - default is true, false if reprocessing a complex type since we have already processed the annotation.
Check for Annotation if it is present, traverse it. If a sibling is found and it is not an annotation return it, otherwise return 0. Used by traverseSimpleTypeDecl.
checkElemDeclValueConstraint() [1/3]
bool TraverseSchema::checkElemDeclValueConstraint (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *const valConstraint, ComplexTypeInfo *const typeInfo, DatatypeValidator *const validator) private
checkElemDeclValueConstraint() [2/3]
bool TraverseSchema::checkElemDeclValueConstraint (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *const valConstraint, ComplexTypeInfo *const typeInfo, DatatypeValidator *const validator) private
checkElemDeclValueConstraint() [3/3]
bool TraverseSchema::checkElemDeclValueConstraint (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *const valConstraint, ComplexTypeInfo *const typeInfo, DatatypeValidator *const validator) private
checkEnumerationRequiredNotation() [1/3]
void TraverseSchema::checkEnumerationRequiredNotation (const DOMElement *const elem, const XMLCh *const name, const XMLCh *const typeStr) private
checkEnumerationRequiredNotation() [2/3]
void TraverseSchema::checkEnumerationRequiredNotation (const DOMElement *const elem, const XMLCh *const name, const XMLCh *const typeStr) private
checkEnumerationRequiredNotation() [3/3]
void TraverseSchema::checkEnumerationRequiredNotation (const DOMElement *const elem, const XMLCh *const name, const XMLCh *const typeStr) private
checkFixedFacet() [1/3]
void TraverseSchema::checkFixedFacet (const DOMElement * const , const XMLCh * const , const DatatypeValidator * const , unsigned int &) private
checkFixedFacet() [2/3]
void TraverseSchema::checkFixedFacet (const DOMElement * const , const XMLCh * const , const DatatypeValidator * const , unsigned int &) private
checkFixedFacet() [3/3]
void TraverseSchema::checkFixedFacet (const DOMElement * const , const XMLCh * const , const DatatypeValidator * const , unsigned int &) private
checkForComplexTypeInfo() [1/3]
ComplexTypeInfo* TraverseSchema::checkForComplexTypeInfo (const DOMElement *const content) private
Process complexType content of an element Return a ComplexTypeInfo if valid type, otherwise 0.
checkForComplexTypeInfo() [2/3]
ComplexTypeInfo* TraverseSchema::checkForComplexTypeInfo (const DOMElement *const content) private
Process complexType content of an element Return a ComplexTypeInfo if valid type, otherwise 0.
checkForComplexTypeInfo() [3/3]
ComplexTypeInfo* TraverseSchema::checkForComplexTypeInfo (const DOMElement *const content) private
Process complexType content of an element Return a ComplexTypeInfo if valid type, otherwise 0.
checkForEmptyTargetNamespace() [1/3]
void TraverseSchema::checkForEmptyTargetNamespace (const DOMElement *const elem) inline private
Definition at line 826 of file TraverseSchema.hpp.
References SchemaSymbols::fgATT_TARGETNAMESPACE, XMLUni::fgXMLErrDomain, getElementAttValue(), XMLErrs::InvalidTargetNSValue, and reportSchemaError().
checkForEmptyTargetNamespace() [2/3]
void TraverseSchema::checkForEmptyTargetNamespace (const DOMElement *const elem) private
checkForEmptyTargetNamespace() [3/3]
void TraverseSchema::checkForEmptyTargetNamespace (const DOMElement *const elem) private
checkForSimpleTypeValidator() [1/3]
DatatypeValidator* TraverseSchema::checkForSimpleTypeValidator (const DOMElement *const content, int baseRefContext = SchemaSymbols::XSD_EMPTYSET) private
Process simpleType content of a list|restriction|union Return a dataype validator if valid type, otherwise 0.
checkForSimpleTypeValidator() [2/3]
DatatypeValidator* TraverseSchema::checkForSimpleTypeValidator (const DOMElement *const content, int baseRefContext = SchemaSymbols::XSD_EMPTYSET) private
Process simpleType content of a list|restriction|union Return a dataype validator if valid type, otherwise 0.
checkForSimpleTypeValidator() [3/3]
DatatypeValidator* TraverseSchema::checkForSimpleTypeValidator (const DOMElement *const content, int baseRefContext = SchemaSymbols::XSD_EMPTYSET) private
Process simpleType content of a list|restriction|union Return a dataype validator if valid type, otherwise 0.
checkIdentityConstraintContent() [1/3]
const DOMElement* TraverseSchema::checkIdentityConstraintContent (const DOMElement *const contentElem) private
Parameters: contentElem - content element to check
Check for identity constraints content.
checkIdentityConstraintContent() [2/3]
const DOMElement* TraverseSchema::checkIdentityConstraintContent (const DOMElement *const contentElem) private
Parameters: contentElem - content element to check
Check for identity constraints content.
checkIdentityConstraintContent() [3/3]
const DOMElement* TraverseSchema::checkIdentityConstraintContent (const DOMElement *const contentElem) private
Parameters: contentElem - content element to check
Check for identity constraints content.
checkMinMax() [1/3]
int TraverseSchema::checkMinMax (ContentSpecNode *const specNode, const DOMElement *const elem, const int allContext = Not_All_Context) private
checkMinMax() [2/3]
int TraverseSchema::checkMinMax (ContentSpecNode *const specNode, const DOMElement *const elem, const int allContext = Not_All_Context) private
checkMinMax() [3/3]
int TraverseSchema::checkMinMax (ContentSpecNode *const specNode, const DOMElement *const elem, const int allContext = Not_All_Context) private
checkTypeFromAnotherSchema() [1/3]
const XMLCh* TraverseSchema::checkTypeFromAnotherSchema (const DOMElement *const elem, const XMLCh *const typeStr) private
If 'typeStr' belongs to a different schema, return that schema URI, otherwise return 0;
checkTypeFromAnotherSchema() [2/3]
const XMLCh* TraverseSchema::checkTypeFromAnotherSchema (const DOMElement *const elem, const XMLCh *const typeStr) private
If 'typeStr' belongs to a different schema, return that schema URI, otherwise return 0;
checkTypeFromAnotherSchema() [3/3]
const XMLCh* TraverseSchema::checkTypeFromAnotherSchema (const DOMElement *const elem, const XMLCh *const typeStr) private
If 'typeStr' belongs to a different schema, return that schema URI, otherwise return 0;
cleanUp() [1/3]
void TraverseSchema::cleanUp () private
cleanUp() [2/3]
void TraverseSchema::cleanUp () private
cleanUp() [3/3]
void TraverseSchema::cleanUp () private
copyAttGroupAttributes() [1/3]
void TraverseSchema::copyAttGroupAttributes (const DOMElement *const elem, XercesAttGroupInfo *const fromAttGroup, XercesAttGroupInfo *const toAttGroup, ComplexTypeInfo *const typeInfo) private
copyAttGroupAttributes() [2/3]
void TraverseSchema::copyAttGroupAttributes (const DOMElement *const elem, XercesAttGroupInfo *const fromAttGroup, XercesAttGroupInfo *const toAttGroup, ComplexTypeInfo *const typeInfo) private
copyAttGroupAttributes() [3/3]
void TraverseSchema::copyAttGroupAttributes (const DOMElement *const elem, XercesAttGroupInfo *const fromAttGroup, XercesAttGroupInfo *const toAttGroup, ComplexTypeInfo *const typeInfo) private
copyGroupElements() [1/3]
void TraverseSchema::copyGroupElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, XercesGroupInfo *const toGroup, ComplexTypeInfo *const typeInfo) private
copyGroupElements() [2/3]
void TraverseSchema::copyGroupElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, XercesGroupInfo *const toGroup, ComplexTypeInfo *const typeInfo) private
copyGroupElements() [3/3]
void TraverseSchema::copyGroupElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, XercesGroupInfo *const toGroup, ComplexTypeInfo *const typeInfo) private
copyWildCardData() [1/3]
void TraverseSchema::copyWildCardData (const SchemaAttDef *const srcWildCard, SchemaAttDef *const destWildCard) inline private
Definition at line 882 of file TraverseSchema.hpp.
References SchemaAttDef::getAttName(), XMLAttDef::getDefaultType(), XMLAttDef::getType(), QName::getURI(), XMLAttDef::setDefaultType(), XMLAttDef::setType(), and QName::setURI().
copyWildCardData() [2/3]
void TraverseSchema::copyWildCardData (const SchemaAttDef *const srcWildCard, SchemaAttDef *const destWildCard) private
copyWildCardData() [3/3]
void TraverseSchema::copyWildCardData (const SchemaAttDef *const srcWildCard, SchemaAttDef *const destWildCard) private
createSchemaElementDecl() [1/3]
SchemaElementDecl* TraverseSchema::createSchemaElementDecl (const DOMElement *const elem, const XMLCh *const name, bool & isDuplicate, const XMLCh *& valConstraint, const bool topLevel) private
Create a 'SchemaElementDecl' object and add it to SchemaGrammar
createSchemaElementDecl() [2/3]
SchemaElementDecl* TraverseSchema::createSchemaElementDecl (const DOMElement *const elem, const XMLCh *const name, bool & isDuplicate, const XMLCh *& valConstraint, const bool topLevel) private
Create a 'SchemaElementDecl' object and add it to SchemaGrammar
createSchemaElementDecl() [3/3]
SchemaElementDecl* TraverseSchema::createSchemaElementDecl (const DOMElement *const elem, const XMLCh *const name, bool & isDuplicate, const XMLCh *& valConstraint, const bool topLevel) private
Create a 'SchemaElementDecl' object and add it to SchemaGrammar
defaultComplexTypeInfo() [1/3]
void TraverseSchema::defaultComplexTypeInfo (ComplexTypeInfo *const typeInfo) private
defaultComplexTypeInfo() [2/3]
void TraverseSchema::defaultComplexTypeInfo (ComplexTypeInfo *const typeInfo) private
defaultComplexTypeInfo() [3/3]
void TraverseSchema::defaultComplexTypeInfo (ComplexTypeInfo *const typeInfo) private
doTraverseSchema() [1/3]
void TraverseSchema::doTraverseSchema (const DOMElement *const schemaRoot) private
Traverse the Schema DOM tree
doTraverseSchema() [2/3]
void TraverseSchema::doTraverseSchema (const DOMElement *const schemaRoot) private
Traverse the Schema DOM tree
doTraverseSchema() [3/3]
void TraverseSchema::doTraverseSchema (const DOMElement *const schemaRoot) private
Traverse the Schema DOM tree
emptiableParticle() [1/3]
bool TraverseSchema::emptiableParticle (const ContentSpecNode *const specNode) private
Check whether a mixed content is emptiable or not. Needed to validate element constraint values (defualt, fixed)
emptiableParticle() [2/3]
bool TraverseSchema::emptiableParticle (const ContentSpecNode *const specNode) private
Check whether a mixed content is emptiable or not. Needed to validate element constraint values (defualt, fixed)
emptiableParticle() [3/3]
bool TraverseSchema::emptiableParticle (const ContentSpecNode *const specNode) private
Check whether a mixed content is emptiable or not. Needed to validate element constraint values (defualt, fixed)
findDTValidator() [1/3]
DatatypeValidator* TraverseSchema::findDTValidator (const DOMElement *const elem, const XMLCh *const derivedTypeName, const XMLCh *const baseTypeName, const int baseRefContext) private
Return DatatypeValidator available for the baseTypeStr.
findDTValidator() [2/3]
DatatypeValidator* TraverseSchema::findDTValidator (const DOMElement *const elem, const XMLCh *const derivedTypeName, const XMLCh *const baseTypeName, const int baseRefContext) private
Return DatatypeValidator available for the baseTypeStr.
findDTValidator() [3/3]
DatatypeValidator* TraverseSchema::findDTValidator (const DOMElement *const elem, const XMLCh *const derivedTypeName, const XMLCh *const baseTypeName, const int baseRefContext) private
Return DatatypeValidator available for the baseTypeStr.
fixRedefinedSchema() [1/3]
void TraverseSchema::fixRedefinedSchema (const DOMElement *const elem, SchemaInfo *const redefinedSchemaInfo, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter) private
This simple function looks for the first occurrence of a 'redefineChildTypeName' item in the redefined schema and appropriately changes the value of its name. If it turns out that what we're looking for is in a <redefine> though, then we just rename it–and it's reference–to be the same.
fixRedefinedSchema() [2/3]
void TraverseSchema::fixRedefinedSchema (const DOMElement *const elem, SchemaInfo *const redefinedSchemaInfo, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter) private
This simple function looks for the first occurrence of a 'redefineChildTypeName' item in the redefined schema and appropriately changes the value of its name. If it turns out that what we're looking for is in a <redefine> though, then we just rename it–and it's reference–to be the same.
fixRedefinedSchema() [3/3]
void TraverseSchema::fixRedefinedSchema (const DOMElement *const elem, SchemaInfo *const redefinedSchemaInfo, const XMLCh *const redefineChildComponentName, const XMLCh *const redefineChildTypeName, const int redefineNameCounter) private
This simple function looks for the first occurrence of a 'redefineChildTypeName' item in the redefined schema and appropriately changes the value of its name. If it turns out that what we're looking for is in a <redefine> though, then we just rename it–and it's reference–to be the same.
genAnonTypeName() [1/3]
const XMLCh * TraverseSchema::genAnonTypeName (const XMLCh *const prefix) inline private
Generate a name for an anonymous type
Definition at line 861 of file TraverseSchema.hpp.
References XMLStringPool::addOrFind(), XMLBuffer::append(), fAnonXSTypeCount, fBuffer, fMemoryManager, fStringPool, XMLBuffer::getRawBuffer(), XMLStringPool::getValueForId(), XMLBuffer::set(), and XMLString::sizeToText().
genAnonTypeName() [2/3]
const XMLCh* TraverseSchema::genAnonTypeName (const XMLCh *const prefix) private
Generate a name for an anonymous type
genAnonTypeName() [3/3]
const XMLCh* TraverseSchema::genAnonTypeName (const XMLCh *const prefix) private
Generate a name for an anonymous type
generateSyntheticAnnotation() [1/3]
XSAnnotation* TraverseSchema::generateSyntheticAnnotation (const DOMElement *const elem, ValueVectorOf< DOMNode * > * nonXSAttList) private
generateSyntheticAnnotation() [2/3]
XSAnnotation* TraverseSchema::generateSyntheticAnnotation (const DOMElement *const elem, ValueVectorOf< DOMNode * > * nonXSAttList) private
generateSyntheticAnnotation() [3/3]
XSAnnotation* TraverseSchema::generateSyntheticAnnotation (const DOMElement *const elem, ValueVectorOf< DOMNode * > * nonXSAttList) private
getAttrDatatypeValidatorNS() [1/3]
DatatypeValidator* TraverseSchema::getAttrDatatypeValidatorNS (const DOMElement *const elem, const XMLCh * localPart, const XMLCh * typeURI) private
getAttrDatatypeValidatorNS() [2/3]
DatatypeValidator* TraverseSchema::getAttrDatatypeValidatorNS (const DOMElement *const elem, const XMLCh * localPart, const XMLCh * typeURI) private
getAttrDatatypeValidatorNS() [3/3]
DatatypeValidator* TraverseSchema::getAttrDatatypeValidatorNS (const DOMElement *const elem, const XMLCh * localPart, const XMLCh * typeURI) private
getDatatypeValidator() [1/3]
DatatypeValidator* TraverseSchema::getDatatypeValidator (const XMLCh *const uriStr, const XMLCh *const localPartStr) private
getDatatypeValidator() [2/3]
DatatypeValidator* TraverseSchema::getDatatypeValidator (const XMLCh *const uriStr, const XMLCh *const localPartStr) private
getDatatypeValidator() [3/3]
DatatypeValidator* TraverseSchema::getDatatypeValidator (const XMLCh *const uriStr, const XMLCh *const localPartStr) private
getElementAttValue() [1/3]
const XMLCh* TraverseSchema::getElementAttValue (const DOMElement *const elem, const XMLCh *const attName, const DatatypeValidator::ValidatorType attType = DatatypeValidator::UnKnown) private
Return the value of a given attribute name from an element node
Referenced by checkForEmptyTargetNamespace().
getElementAttValue() [2/3]
const XMLCh* TraverseSchema::getElementAttValue (const DOMElement *const elem, const XMLCh *const attName, const DatatypeValidator::ValidatorType attType = DatatypeValidator::UnKnown) private
Return the value of a given attribute name from an element node
getElementAttValue() [3/3]
const XMLCh* TraverseSchema::getElementAttValue (const DOMElement *const elem, const XMLCh *const attName, const DatatypeValidator::ValidatorType attType = DatatypeValidator::UnKnown) private
Return the value of a given attribute name from an element node
getElementComplexTypeInfo() [1/3]
ComplexTypeInfo* TraverseSchema::getElementComplexTypeInfo (const DOMElement *const elem, const XMLCh *const typeStr, const XMLCh *const otherSchemaURI) private
Return the complexType info for a given element type attribute if the type is a complex type
getElementComplexTypeInfo() [2/3]
ComplexTypeInfo* TraverseSchema::getElementComplexTypeInfo (const DOMElement *const elem, const XMLCh *const typeStr, const XMLCh *const otherSchemaURI) private
Return the complexType info for a given element type attribute if the type is a complex type
getElementComplexTypeInfo() [3/3]
ComplexTypeInfo* TraverseSchema::getElementComplexTypeInfo (const DOMElement *const elem, const XMLCh *const typeStr, const XMLCh *const otherSchemaURI) private
Return the complexType info for a given element type attribute if the type is a complex type
getElementTypeValidator() [1/3]
DatatypeValidator* TraverseSchema::getElementTypeValidator (const DOMElement *const elem, const XMLCh *const typeStr, bool & noErrorDetected, const XMLCh *const otherSchemaURI) private
Return the datatype validator for a given element type attribute if the type is a simple type
getElementTypeValidator() [2/3]
DatatypeValidator* TraverseSchema::getElementTypeValidator (const DOMElement *const elem, const XMLCh *const typeStr, bool & noErrorDetected, const XMLCh *const otherSchemaURI) private
Return the datatype validator for a given element type attribute if the type is a simple type
getElementTypeValidator() [3/3]
DatatypeValidator* TraverseSchema::getElementTypeValidator (const DOMElement *const elem, const XMLCh *const typeStr, bool & noErrorDetected, const XMLCh *const otherSchemaURI) private
Return the datatype validator for a given element type attribute if the type is a simple type
getGlobalElemDecl() [1/3]
SchemaElementDecl* TraverseSchema::getGlobalElemDecl (const DOMElement *const elem, const XMLCh *const name) private
Return global schema element declaration for a given element name
getGlobalElemDecl() [2/3]
SchemaElementDecl* TraverseSchema::getGlobalElemDecl (const DOMElement *const elem, const XMLCh *const name) private
Return global schema element declaration for a given element name
getGlobalElemDecl() [3/3]
SchemaElementDecl* TraverseSchema::getGlobalElemDecl (const DOMElement *const elem, const XMLCh *const name) private
Return global schema element declaration for a given element name
getLocalPart() [1/3]
const XMLCh * TraverseSchema::getLocalPart (const XMLCh *const rawName) inline private
Return the local for a given rawname string
caller allocated, caller managed (cacm)
Definition at line 805 of file TraverseSchema.hpp.
References XMLStringPool::addOrFind(), chColon, fBuffer, XMLUni::fgZeroLenString, fStringPool, XMLBuffer::getRawBuffer(), XMLStringPool::getValueForId(), XMLString::indexOf(), XMLBuffer::set(), and XMLString::stringLen().
getLocalPart() [2/3]
const XMLCh* TraverseSchema::getLocalPart (const XMLCh *const rawName) private
Return the local for a given rawname string
caller allocated, caller managed (cacm)
getLocalPart() [3/3]
const XMLCh* TraverseSchema::getLocalPart (const XMLCh *const rawName) private
Return the local for a given rawname string
caller allocated, caller managed (cacm)
getPrefix() [1/3]
const XMLCh * TraverseSchema::getPrefix (const XMLCh *const rawName) inline private
Return the prefix for a given rawname string
Function allocated, caller managed (facm) - pointer to be deleted by caller.
Definition at line 792 of file TraverseSchema.hpp.
References XMLStringPool::addOrFind(), chColon, fBuffer, XMLUni::fgZeroLenString, fStringPool, XMLBuffer::getRawBuffer(), XMLStringPool::getValueForId(), XMLString::indexOf(), and XMLBuffer::set().
getPrefix() [2/3]
const XMLCh* TraverseSchema::getPrefix (const XMLCh *const rawName) private
Return the prefix for a given rawname string
Function allocated, caller managed (facm) - pointer to be deleted by caller.
getPrefix() [3/3]
const XMLCh* TraverseSchema::getPrefix (const XMLCh *const rawName) private
Return the prefix for a given rawname string
Function allocated, caller managed (facm) - pointer to be deleted by caller.
getRedefineNewTypeName() [1/3]
void TraverseSchema::getRedefineNewTypeName (const XMLCh *const oldTypeName, const int redefineCounter, XMLBuffer & newTypeName) inline private
Definition at line 890 of file TraverseSchema.hpp.
References XMLBuffer::append(), SchemaSymbols::fgRedefIdentifier, and XMLBuffer::set().
getRedefineNewTypeName() [2/3]
void TraverseSchema::getRedefineNewTypeName (const XMLCh *const oldTypeName, const int redefineCounter, XMLBuffer & newTypeName) private
getRedefineNewTypeName() [3/3]
void TraverseSchema::getRedefineNewTypeName (const XMLCh *const oldTypeName, const int redefineCounter, XMLBuffer & newTypeName) private
getTypeInfoFromNS() [1/3]
ComplexTypeInfo* TraverseSchema::getTypeInfoFromNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const localPart) private
Get complexType infp from another schema
getTypeInfoFromNS() [2/3]
ComplexTypeInfo* TraverseSchema::getTypeInfoFromNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const localPart) private
Get complexType infp from another schema
getTypeInfoFromNS() [3/3]
ComplexTypeInfo* TraverseSchema::getTypeInfoFromNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const localPart) private
Get complexType infp from another schema
init() [1/3]
void TraverseSchema::init () private
init() [2/3]
void TraverseSchema::init () private
init() [3/3]
void TraverseSchema::init () private
isAttrOrAttrGroup() [1/3]
bool TraverseSchema::isAttrOrAttrGroup (const DOMElement *const elem) inline private
Returns true if a DOM Element is an attribute or attribute group
Definition at line 848 of file TraverseSchema.hpp.
References XMLString::equals(), SchemaSymbols::fgELT_ANYATTRIBUTE, SchemaSymbols::fgELT_ATTRIBUTE, SchemaSymbols::fgELT_ATTRIBUTEGROUP, and DOMNode::getLocalName().
isAttrOrAttrGroup() [2/3]
bool TraverseSchema::isAttrOrAttrGroup (const DOMElement *const elem) private
Returns true if a DOM Element is an attribute or attribute group
isAttrOrAttrGroup() [3/3]
bool TraverseSchema::isAttrOrAttrGroup (const DOMElement *const elem) private
Returns true if a DOM Element is an attribute or attribute group
isBaseFromAnotherSchema() [1/3]
bool TraverseSchema::isBaseFromAnotherSchema (const XMLCh *const baseURI) inline private
Check if base is from another schema
Definition at line 835 of file TraverseSchema.hpp.
References XMLString::equals(), SchemaSymbols::fgURI_SCHEMAFORSCHEMA, and fTargetNSURIString.
isBaseFromAnotherSchema() [2/3]
bool TraverseSchema::isBaseFromAnotherSchema (const XMLCh *const baseURI) private
Check if base is from another schema
isBaseFromAnotherSchema() [3/3]
bool TraverseSchema::isBaseFromAnotherSchema (const XMLCh *const baseURI) private
Check if base is from another schema
isIdentityConstraintName() [1/3]
bool TraverseSchema::isIdentityConstraintName (const XMLCh *const constraintName) private
Return true if a name is an identity constraint, otherwise false
isIdentityConstraintName() [2/3]
bool TraverseSchema::isIdentityConstraintName (const XMLCh *const constraintName) private
Return true if a name is an identity constraint, otherwise false
isIdentityConstraintName() [3/3]
bool TraverseSchema::isIdentityConstraintName (const XMLCh *const constraintName) private
Return true if a name is an identity constraint, otherwise false
isImportingNS() [1/3]
bool TraverseSchema::isImportingNS (const int namespaceURI) inline private
Keep track of the xs:import found
Definition at line 901 of file TraverseSchema.hpp.
References ValueVectorOf< TElem >::containsElement(), and fImportedNSList.
isImportingNS() [2/3]
bool TraverseSchema::isImportingNS (const int namespaceURI) private
Keep track of the xs:import found
isImportingNS() [3/3]
bool TraverseSchema::isImportingNS (const int namespaceURI) private
Keep track of the xs:import found
isSubstitutionGroupCircular() [1/3]
bool TraverseSchema::isSubstitutionGroupCircular (SchemaElementDecl *const elemDecl, SchemaElementDecl *const subsElemDecl) private
isSubstitutionGroupCircular() [2/3]
bool TraverseSchema::isSubstitutionGroupCircular (SchemaElementDecl *const elemDecl, SchemaElementDecl *const subsElemDecl) private
isSubstitutionGroupCircular() [3/3]
bool TraverseSchema::isSubstitutionGroupCircular (SchemaElementDecl *const elemDecl, SchemaElementDecl *const subsElemDecl) private
isSubstitutionGroupValid() [1/3]
bool TraverseSchema::isSubstitutionGroupValid (const DOMElement *const elem, const SchemaElementDecl *const elemDecl, const ComplexTypeInfo *const typeInfo, const DatatypeValidator *const validator, const XMLCh *const elemName, const bool toEmit = true) private
Check validity constraint of a substitutionGroup attribute in an element declaration
isSubstitutionGroupValid() [2/3]
bool TraverseSchema::isSubstitutionGroupValid (const DOMElement *const elem, const SchemaElementDecl *const elemDecl, const ComplexTypeInfo *const typeInfo, const DatatypeValidator *const validator, const XMLCh *const elemName, const bool toEmit = true) private
Check validity constraint of a substitutionGroup attribute in an element declaration
isSubstitutionGroupValid() [3/3]
bool TraverseSchema::isSubstitutionGroupValid (const DOMElement *const elem, const SchemaElementDecl *const elemDecl, const ComplexTypeInfo *const typeInfo, const DatatypeValidator *const validator, const XMLCh *const elemName, const bool toEmit = true) private
Check validity constraint of a substitutionGroup attribute in an element declaration
isWildCardSubset() [1/3]
bool TraverseSchema::isWildCardSubset (const SchemaAttDef *const baseAttWildCard, const SchemaAttDef *const childAttWildCard) private
Check whether a namespace constraint is an intensional subset of another namespace constraint
isWildCardSubset() [2/3]
bool TraverseSchema::isWildCardSubset (const SchemaAttDef *const baseAttWildCard, const SchemaAttDef *const childAttWildCard) private
Check whether a namespace constraint is an intensional subset of another namespace constraint
isWildCardSubset() [3/3]
bool TraverseSchema::isWildCardSubset (const SchemaAttDef *const baseAttWildCard, const SchemaAttDef *const childAttWildCard) private
Check whether a namespace constraint is an intensional subset of another namespace constraint
openRedefinedSchema() [1/3]
bool TraverseSchema::openRedefinedSchema (const DOMElement *const redefineElem) private
openRedefinedSchema() [2/3]
bool TraverseSchema::openRedefinedSchema (const DOMElement *const redefineElem) private
openRedefinedSchema() [3/3]
bool TraverseSchema::openRedefinedSchema (const DOMElement *const redefineElem) private
operator=() [1/3]
TraverseSchema& TraverseSchema::operator= (const TraverseSchema &) private
operator=() [2/3]
TraverseSchema& TraverseSchema::operator= (const TraverseSchema &) private
operator=() [3/3]
TraverseSchema& TraverseSchema::operator= (const TraverseSchema &) private
parseBlockSet() [1/3]
int TraverseSchema::parseBlockSet (const DOMElement *const elem, const int blockType, const bool isRoot = false) private
Parse block & final items
parseBlockSet() [2/3]
int TraverseSchema::parseBlockSet (const DOMElement *const elem, const int blockType, const bool isRoot = false) private
Parse block & final items
parseBlockSet() [3/3]
int TraverseSchema::parseBlockSet (const DOMElement *const elem, const int blockType, const bool isRoot = false) private
Parse block & final items
parseFinalSet() [1/3]
int TraverseSchema::parseFinalSet (const DOMElement *const elem, const int finalType, const bool isRoot = false) private
parseFinalSet() [2/3]
int TraverseSchema::parseFinalSet (const DOMElement *const elem, const int finalType, const bool isRoot = false) private
parseFinalSet() [3/3]
int TraverseSchema::parseFinalSet (const DOMElement *const elem, const int finalType, const bool isRoot = false) private
popCurrentTypeNameStack() [1/3]
void TraverseSchema::popCurrentTypeNameStack () inline private
Definition at line 872 of file TraverseSchema.hpp.
References fCurrentTypeNameStack, ValueVectorOf< TElem >::removeElementAt(), and ValueVectorOf< TElem >::size().
popCurrentTypeNameStack() [2/3]
void TraverseSchema::popCurrentTypeNameStack () private
popCurrentTypeNameStack() [3/3]
void TraverseSchema::popCurrentTypeNameStack () private
preprocessChildren() [1/3]
void TraverseSchema::preprocessChildren (const DOMElement *const root) private
preprocessChildren() [2/3]
void TraverseSchema::preprocessChildren (const DOMElement *const root) private
preprocessChildren() [3/3]
void TraverseSchema::preprocessChildren (const DOMElement *const root) private
preprocessImport() [1/3]
void TraverseSchema::preprocessImport (const DOMElement *const elemNode) private
preprocessImport() [2/3]
void TraverseSchema::preprocessImport (const DOMElement *const elemNode) private
preprocessImport() [3/3]
void TraverseSchema::preprocessImport (const DOMElement *const elemNode) private
preprocessInclude() [1/3]
void TraverseSchema::preprocessInclude (const DOMElement *const elemNode) private
preprocessInclude() [2/3]
void TraverseSchema::preprocessInclude (const DOMElement *const elemNode) private
preprocessInclude() [3/3]
void TraverseSchema::preprocessInclude (const DOMElement *const elemNode) private
preprocessRedefine() [1/3]
void TraverseSchema::preprocessRedefine (const DOMElement *const elemNode) private
preprocessRedefine() [2/3]
void TraverseSchema::preprocessRedefine (const DOMElement *const elemNode) private
preprocessRedefine() [3/3]
void TraverseSchema::preprocessRedefine (const DOMElement *const elemNode) private
preprocessRedefineInclude() [1/3]
void TraverseSchema::preprocessRedefineInclude (SchemaInfo *const currSchemaInfo) private
This purpose of this method is threefold:
To extract the schema information of included/redefined schema.
Rename redefined components.
Process components of included/redefined schemas
preprocessRedefineInclude() [2/3]
void TraverseSchema::preprocessRedefineInclude (SchemaInfo *const currSchemaInfo) private
This purpose of this method is threefold:
To extract the schema information of included/redefined schema.
Rename redefined components.
Process components of included/redefined schemas
preprocessRedefineInclude() [3/3]
void TraverseSchema::preprocessRedefineInclude (SchemaInfo *const currSchemaInfo) private
This purpose of this method is threefold:
To extract the schema information of included/redefined schema.
Rename redefined components.
Process components of included/redefined schemas
preprocessSchema() [1/3]
void TraverseSchema::preprocessSchema (DOMElement *const schemaRoot, const XMLCh *const schemaURL, bool multipleImport = false) private
preprocessSchema() [2/3]
void TraverseSchema::preprocessSchema (DOMElement *const schemaRoot, const XMLCh *const schemaURL, bool multipleImport = false) private
preprocessSchema() [3/3]
void TraverseSchema::preprocessSchema (DOMElement *const schemaRoot, const XMLCh *const schemaURL, bool multipleImport = false) private
processAttributeDeclRef() [1/3]
void TraverseSchema::processAttributeDeclRef (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const XMLCh *const refName, const XMLCh *const useVal, const XMLCh *const defaultVal, const XMLCh *const fixedVal) private
Process a 'ref' of an Attribute declaration
processAttributeDeclRef() [2/3]
void TraverseSchema::processAttributeDeclRef (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const XMLCh *const refName, const XMLCh *const useVal, const XMLCh *const defaultVal, const XMLCh *const fixedVal) private
Process a 'ref' of an Attribute declaration
processAttributeDeclRef() [3/3]
void TraverseSchema::processAttributeDeclRef (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const XMLCh *const refName, const XMLCh *const useVal, const XMLCh *const defaultVal, const XMLCh *const fixedVal) private
Process a 'ref' of an Attribute declaration
processAttributeGroupRef() [1/3]
XercesAttGroupInfo* TraverseSchema::processAttributeGroupRef (const DOMElement *const elem, const XMLCh *const refName, ComplexTypeInfo *const typeInfo) private
Process a 'ref' on a attributeGroup
processAttributeGroupRef() [2/3]
XercesAttGroupInfo* TraverseSchema::processAttributeGroupRef (const DOMElement *const elem, const XMLCh *const refName, ComplexTypeInfo *const typeInfo) private
Process a 'ref' on a attributeGroup
processAttributeGroupRef() [3/3]
XercesAttGroupInfo* TraverseSchema::processAttributeGroupRef (const DOMElement *const elem, const XMLCh *const refName, ComplexTypeInfo *const typeInfo) private
Process a 'ref' on a attributeGroup
processAttributes() [1/3]
void TraverseSchema::processAttributes (const DOMElement *const elem, const DOMElement *const attElem, ComplexTypeInfo *const typeInfo, const bool isBaseAnyType = false) private
Process attributes of a complex type
processAttributes() [2/3]
void TraverseSchema::processAttributes (const DOMElement *const elem, const DOMElement *const attElem, ComplexTypeInfo *const typeInfo, const bool isBaseAnyType = false) private
Process attributes of a complex type
processAttributes() [3/3]
void TraverseSchema::processAttributes (const DOMElement *const elem, const DOMElement *const attElem, ComplexTypeInfo *const typeInfo, const bool isBaseAnyType = false) private
Process attributes of a complex type
processAttValue() [1/3]
void TraverseSchema::processAttValue (const XMLCh *const attVal, XMLBuffer & aBuf) private
processAttValue() [2/3]
void TraverseSchema::processAttValue (const XMLCh *const attVal, XMLBuffer & aBuf) private
processAttValue() [3/3]
void TraverseSchema::processAttValue (const XMLCh *const attVal, XMLBuffer & aBuf) private
processBaseTypeInfo() [1/3]
void TraverseSchema::processBaseTypeInfo (const DOMElement *const elem, const XMLCh *const baseName, const XMLCh *const localPart, const XMLCh *const uriStr, ComplexTypeInfo *const typeInfo) private
Process "base" information for a complexType
processBaseTypeInfo() [2/3]
void TraverseSchema::processBaseTypeInfo (const DOMElement *const elem, const XMLCh *const baseName, const XMLCh *const localPart, const XMLCh *const uriStr, ComplexTypeInfo *const typeInfo) private
Process "base" information for a complexType
processBaseTypeInfo() [3/3]
void TraverseSchema::processBaseTypeInfo (const DOMElement *const elem, const XMLCh *const baseName, const XMLCh *const localPart, const XMLCh *const uriStr, ComplexTypeInfo *const typeInfo) private
Process "base" information for a complexType
processChildren() [1/3]
void TraverseSchema::processChildren (const DOMElement *const root) private
Loop through the children, and traverse the corresponding schema type type declaration (simpleType, complexType, import, ....)
processChildren() [2/3]
void TraverseSchema::processChildren (const DOMElement *const root) private
Loop through the children, and traverse the corresponding schema type type declaration (simpleType, complexType, import, ....)
processChildren() [3/3]
void TraverseSchema::processChildren (const DOMElement *const root) private
Loop through the children, and traverse the corresponding schema type type declaration (simpleType, complexType, import, ....)
processComplexContent() [1/3]
void TraverseSchema::processComplexContent (const DOMElement *const elem, const XMLCh *const typeName, const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const XMLCh *const baseLocalPart, const bool isMixed, const bool isBaseAnyType = false) private
Process complex content for a complexType
processComplexContent() [2/3]
void TraverseSchema::processComplexContent (const DOMElement *const elem, const XMLCh *const typeName, const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const XMLCh *const baseLocalPart, const bool isMixed, const bool isBaseAnyType = false) private
Process complex content for a complexType
processComplexContent() [3/3]
void TraverseSchema::processComplexContent (const DOMElement *const elem, const XMLCh *const typeName, const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const XMLCh *const baseLocalPart, const bool isMixed, const bool isBaseAnyType = false) private
Process complex content for a complexType
processElemDeclAttrs() [1/3]
void TraverseSchema::processElemDeclAttrs (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *& valConstraint, bool isTopLevel = false) private
processElemDeclAttrs() [2/3]
void TraverseSchema::processElemDeclAttrs (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *& valConstraint, bool isTopLevel = false) private
processElemDeclAttrs() [3/3]
void TraverseSchema::processElemDeclAttrs (const DOMElement *const elem, SchemaElementDecl *const elemDecl, const XMLCh *& valConstraint, bool isTopLevel = false) private
processElemDeclIC() [1/3]
void TraverseSchema::processElemDeclIC (DOMElement *const elem, SchemaElementDecl *const elemDecl) private
processElemDeclIC() [2/3]
void TraverseSchema::processElemDeclIC (DOMElement *const elem, SchemaElementDecl *const elemDecl) private
processElemDeclIC() [3/3]
void TraverseSchema::processElemDeclIC (DOMElement *const elem, SchemaElementDecl *const elemDecl) private
processElementDeclRef() [1/3]
SchemaElementDecl* TraverseSchema::processElementDeclRef (const DOMElement *const elem, const XMLCh *const refName) private
Process a 'ref' of an Element declaration
processElementDeclRef() [2/3]
SchemaElementDecl* TraverseSchema::processElementDeclRef (const DOMElement *const elem, const XMLCh *const refName) private
Process a 'ref' of an Element declaration
processElementDeclRef() [3/3]
SchemaElementDecl* TraverseSchema::processElementDeclRef (const DOMElement *const elem, const XMLCh *const refName) private
Process a 'ref' of an Element declaration
processElements() [1/6]
void TraverseSchema::processElements (const DOMElement *const elem, ComplexTypeInfo *const baseTypeInfo, ComplexTypeInfo *const newTypeInfo) private
processElements() [2/6]
void TraverseSchema::processElements (const DOMElement *const elem, ComplexTypeInfo *const baseTypeInfo, ComplexTypeInfo *const newTypeInfo) private
processElements() [3/6]
void TraverseSchema::processElements (const DOMElement *const elem, ComplexTypeInfo *const baseTypeInfo, ComplexTypeInfo *const newTypeInfo) private
processElements() [4/6]
void TraverseSchema::processElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, ComplexTypeInfo *const typeInfo) private
processElements() [5/6]
void TraverseSchema::processElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, ComplexTypeInfo *const typeInfo) private
processElements() [6/6]
void TraverseSchema::processElements (const DOMElement *const elem, XercesGroupInfo *const fromGroup, ComplexTypeInfo *const typeInfo) private
processGroupRef() [1/3]
XercesGroupInfo* TraverseSchema::processGroupRef (const DOMElement *const elem, const XMLCh *const refName) private
Process a 'ref' on a group
processGroupRef() [2/3]
XercesGroupInfo* TraverseSchema::processGroupRef (const DOMElement *const elem, const XMLCh *const refName) private
Process a 'ref' on a group
processGroupRef() [3/3]
XercesGroupInfo* TraverseSchema::processGroupRef (const DOMElement *const elem, const XMLCh *const refName) private
Process a 'ref' on a group
processKeyRefFor() [1/3]
void TraverseSchema::processKeyRefFor (SchemaInfo *const aSchemaInfo, ValueVectorOf< SchemaInfo * > *const infoList) private
processKeyRefFor() [2/3]
void TraverseSchema::processKeyRefFor (SchemaInfo *const aSchemaInfo, ValueVectorOf< SchemaInfo * > *const infoList) private
processKeyRefFor() [3/3]
void TraverseSchema::processKeyRefFor (SchemaInfo *const aSchemaInfo, ValueVectorOf< SchemaInfo * > *const infoList) private
processSubstitutionGroup() [1/3]
void TraverseSchema::processSubstitutionGroup (const DOMElement *const elem, SchemaElementDecl *const elemDecl, ComplexTypeInfo *& typeInfo, DatatypeValidator *& validator, const XMLCh *const subsElemQName) private
processSubstitutionGroup() [2/3]
void TraverseSchema::processSubstitutionGroup (const DOMElement *const elem, SchemaElementDecl *const elemDecl, ComplexTypeInfo *& typeInfo, DatatypeValidator *& validator, const XMLCh *const subsElemQName) private
processSubstitutionGroup() [3/3]
void TraverseSchema::processSubstitutionGroup (const DOMElement *const elem, SchemaElementDecl *const elemDecl, ComplexTypeInfo *& typeInfo, DatatypeValidator *& validator, const XMLCh *const subsElemQName) private
renameRedefinedComponents() [1/3]
void TraverseSchema::renameRedefinedComponents (const DOMElement *const redefineElem, SchemaInfo *const redefiningSchemaInfo, SchemaInfo *const redefinedSchemaInfo) private
The purpose of this method is twofold:
To find and appropriately modify all information items in redefinedSchema with names that are redefined by children of redefineElem.
To make sure the redefine element represented by redefineElem is valid as far as content goes and with regard to properly referencing components to be redefined.
No traversing is done here! This method also takes actions to find and, if necessary, modify the names of elements in <redefine>'s in the schema that's being redefined.
renameRedefinedComponents() [2/3]
void TraverseSchema::renameRedefinedComponents (const DOMElement *const redefineElem, SchemaInfo *const redefiningSchemaInfo, SchemaInfo *const redefinedSchemaInfo) private
The purpose of this method is twofold:
To find and appropriately modify all information items in redefinedSchema with names that are redefined by children of redefineElem.
To make sure the redefine element represented by redefineElem is valid as far as content goes and with regard to properly referencing components to be redefined.
No traversing is done here! This method also takes actions to find and, if necessary, modify the names of elements in <redefine>'s in the schema that's being redefined.
renameRedefinedComponents() [3/3]
void TraverseSchema::renameRedefinedComponents (const DOMElement *const redefineElem, SchemaInfo *const redefiningSchemaInfo, SchemaInfo *const redefinedSchemaInfo) private
The purpose of this method is twofold:
To find and appropriately modify all information items in redefinedSchema with names that are redefined by children of redefineElem.
To make sure the redefine element represented by redefineElem is valid as far as content goes and with regard to properly referencing components to be redefined.
No traversing is done here! This method also takes actions to find and, if necessary, modify the names of elements in <redefine>'s in the schema that's being redefined.
reportSchemaError() [1/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode) private
reportSchemaError() [2/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode) private
reportSchemaError() [3/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode) private
reportSchemaError() [4/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2 = 0, const XMLCh *const text3 = 0, const XMLCh *const text4 = 0) private
reportSchemaError() [5/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2 = 0, const XMLCh *const text3 = 0, const XMLCh *const text4 = 0) private
reportSchemaError() [6/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2 = 0, const XMLCh *const text3 = 0, const XMLCh *const text4 = 0) private
reportSchemaError() [7/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLException & except) private
reportSchemaError() [8/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLException & except) private
reportSchemaError() [9/15]
void TraverseSchema::reportSchemaError (const DOMElement *const elem, const XMLException & except) private
reportSchemaError() [10/15]
void TraverseSchema::reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode) private
Referenced by checkForEmptyTargetNamespace().
reportSchemaError() [11/15]
void TraverseSchema::reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode) private
reportSchemaError() [12/15]
void TraverseSchema::reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode) private
reportSchemaError() [13/15]
void TraverseSchema::reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2 = 0, const XMLCh *const text3 = 0, const XMLCh *const text4 = 0) private
reportSchemaError() [14/15]
void TraverseSchema::reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2 = 0, const XMLCh *const text3 = 0, const XMLCh *const text4 = 0) private
reportSchemaError() [15/15]
void TraverseSchema::reportSchemaError (const XSDLocator *const aLocator, const XMLCh *const msgDomain, const int errorCode, const XMLCh *const text1, const XMLCh *const text2 = 0, const XMLCh *const text3 = 0, const XMLCh *const text4 = 0) private
resolvePrefixToURI() [1/3]
const XMLCh* TraverseSchema::resolvePrefixToURI (const DOMElement *const elem, const XMLCh *const prefix) private
resolvePrefixToURI() [2/3]
const XMLCh* TraverseSchema::resolvePrefixToURI (const DOMElement *const elem, const XMLCh *const prefix) private
resolvePrefixToURI() [3/3]
const XMLCh* TraverseSchema::resolvePrefixToURI (const DOMElement *const elem, const XMLCh *const prefix) private
resolveSchemaLocation() [1/3]
InputSource* TraverseSchema::resolveSchemaLocation (const XMLCh *const loc, const XMLResourceIdentifier::ResourceIdentifierType resourceIdentitiferType, const XMLCh *const nameSpace = 0) private
Resolve a schema location attribute value to an input source. Caller to delete the returned object.
resolveSchemaLocation() [2/3]
InputSource* TraverseSchema::resolveSchemaLocation (const XMLCh *const loc, const XMLResourceIdentifier::ResourceIdentifierType resourceIdentitiferType, const XMLCh *const nameSpace = 0) private
Resolve a schema location attribute value to an input source. Caller to delete the returned object.
resolveSchemaLocation() [3/3]
InputSource* TraverseSchema::resolveSchemaLocation (const XMLCh *const loc, const XMLResourceIdentifier::ResourceIdentifierType resourceIdentitiferType, const XMLCh *const nameSpace = 0) private
Resolve a schema location attribute value to an input source. Caller to delete the returned object.
restoreSchemaInfo() [1/3]
void TraverseSchema::restoreSchemaInfo (SchemaInfo *const toRestore, SchemaInfo::ListType const aListType = SchemaInfo::INCLUDE, const unsigned int saveScope = Grammar::TOP_LEVEL_SCOPE) private
restoreSchemaInfo() [2/3]
void TraverseSchema::restoreSchemaInfo (SchemaInfo *const toRestore, SchemaInfo::ListType const aListType = SchemaInfo::INCLUDE, const unsigned int saveScope = Grammar::TOP_LEVEL_SCOPE) private
restoreSchemaInfo() [3/3]
void TraverseSchema::restoreSchemaInfo (SchemaInfo *const toRestore, SchemaInfo::ListType const aListType = SchemaInfo::INCLUDE, const unsigned int saveScope = Grammar::TOP_LEVEL_SCOPE) private
retrieveNamespaceMapping() [1/3]
bool TraverseSchema::retrieveNamespaceMapping (const DOMElement *const elem) private
Retrieved the Namespace mapping from the schema element
retrieveNamespaceMapping() [2/3]
bool TraverseSchema::retrieveNamespaceMapping (const DOMElement *const elem) private
Retrieved the Namespace mapping from the schema element
retrieveNamespaceMapping() [3/3]
bool TraverseSchema::retrieveNamespaceMapping (const DOMElement *const elem) private
Retrieved the Namespace mapping from the schema element
traverseAll() [1/3]
ContentSpecNode* TraverseSchema::traverseAll (const DOMElement *const allElem, bool & hasChildren) private
traverseAll() [2/3]
ContentSpecNode* TraverseSchema::traverseAll (const DOMElement *const allElem, bool & hasChildren) private
traverseAll() [3/3]
ContentSpecNode* TraverseSchema::traverseAll (const DOMElement *const allElem, bool & hasChildren) private
traverseAnnotationDecl() [1/3]
XSAnnotation* TraverseSchema::traverseAnnotationDecl (const DOMElement *const childElem, ValueVectorOf< DOMNode * > *const nonXSAttList, const bool topLevel = false) private
traverseAnnotationDecl() [2/3]
XSAnnotation* TraverseSchema::traverseAnnotationDecl (const DOMElement *const childElem, ValueVectorOf< DOMNode * > *const nonXSAttList, const bool topLevel = false) private
traverseAnnotationDecl() [3/3]
XSAnnotation* TraverseSchema::traverseAnnotationDecl (const DOMElement *const childElem, ValueVectorOf< DOMNode * > *const nonXSAttList, const bool topLevel = false) private
traverseAny() [1/3]
ContentSpecNode* TraverseSchema::traverseAny (const DOMElement *const anyDecl) private
traverseAny() [2/3]
ContentSpecNode* TraverseSchema::traverseAny (const DOMElement *const anyDecl) private
traverseAny() [3/3]
ContentSpecNode* TraverseSchema::traverseAny (const DOMElement *const anyDecl) private
traverseAnyAttribute() [1/3]
SchemaAttDef* TraverseSchema::traverseAnyAttribute (const DOMElement *const elem) private
traverseAnyAttribute() [2/3]
SchemaAttDef* TraverseSchema::traverseAnyAttribute (const DOMElement *const elem) private
traverseAnyAttribute() [3/3]
SchemaAttDef* TraverseSchema::traverseAnyAttribute (const DOMElement *const elem) private
traverseAttributeDecl() [1/3]
void TraverseSchema::traverseAttributeDecl (const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const bool topLevel = false) private
traverseAttributeDecl() [2/3]
void TraverseSchema::traverseAttributeDecl (const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const bool topLevel = false) private
traverseAttributeDecl() [3/3]
void TraverseSchema::traverseAttributeDecl (const DOMElement *const childElem, ComplexTypeInfo *const typeInfo, const bool topLevel = false) private
traverseAttributeGroupDecl() [1/3]
XercesAttGroupInfo* TraverseSchema::traverseAttributeGroupDecl (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const bool topLevel = false) private
traverseAttributeGroupDecl() [2/3]
XercesAttGroupInfo* TraverseSchema::traverseAttributeGroupDecl (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const bool topLevel = false) private
traverseAttributeGroupDecl() [3/3]
XercesAttGroupInfo* TraverseSchema::traverseAttributeGroupDecl (const DOMElement *const elem, ComplexTypeInfo *const typeInfo, const bool topLevel = false) private
traverseAttributeGroupDeclNS() [1/3]
XercesAttGroupInfo* TraverseSchema::traverseAttributeGroupDeclNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const name) private
traverseAttributeGroupDeclNS() [2/3]
XercesAttGroupInfo* TraverseSchema::traverseAttributeGroupDeclNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const name) private
traverseAttributeGroupDeclNS() [3/3]
XercesAttGroupInfo* TraverseSchema::traverseAttributeGroupDeclNS (const DOMElement *const elem, const XMLCh *const uriStr, const XMLCh *const name) private
traverseByList() [1/3]
DatatypeValidator* TraverseSchema::traverseByList (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot) private
traverseByList() [2/3]
DatatypeValidator* TraverseSchema::traverseByList (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot) private
traverseByList() [3/3]
DatatypeValidator* TraverseSchema::traverseByList (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot) private
traverseByRestriction() [1/3]
DatatypeValidator* TraverseSchema::traverseByRestriction (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot) private
traverseByRestriction() [2/3]
DatatypeValidator* TraverseSchema::traverseByRestriction (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot) private
traverseByRestriction() [3/3]
DatatypeValidator* TraverseSchema::traverseByRestriction (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, Janitor< XSAnnotation > *const janAnnot) private
traverseByUnion() [1/3]
DatatypeValidator* TraverseSchema::traverseByUnion (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, int baseRefContext, Janitor< XSAnnotation > *const janAnnot) private
traverseByUnion() [2/3]
DatatypeValidator* TraverseSchema::traverseByUnion (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, int baseRefContext, Janitor< XSAnnotation > *const janAnnot) private
traverseByUnion() [3/3]
DatatypeValidator* TraverseSchema::traverseByUnion (const DOMElement *const rootElem, const DOMElement *const contentElem, const XMLCh *const typeName, const XMLCh *const qualifiedName, const int finalSet, int baseRefContext, Janitor< XSAnnotation > *const janAnnot) private
traverseChoiceSequence() [1/3]
ContentSpecNode* TraverseSchema::traverseChoiceSequence (const DOMElement *const elemDecl, const int modelGroupType, bool & hasChildren) private
traverseChoiceSequence() [2/3]
ContentSpecNode* TraverseSchema::traverseChoiceSequence (const DOMElement *const elemDecl, const int modelGroupType, bool & hasChildren) private
traverseChoiceSequence() [3/3]
ContentSpecNode* TraverseSchema::traverseChoiceSequence (const DOMElement *const elemDecl, const int modelGroupType, bool & hasChildren) private
traverseComplexContentDecl() [1/3]
void TraverseSchema::traverseComplexContentDecl (const XMLCh *const typeName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, const bool isMixed, Janitor< XSAnnotation > *const janAnnot) private
traverseComplexContentDecl() [2/3]
void TraverseSchema::traverseComplexContentDecl (const XMLCh *const typeName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, const bool isMixed, Janitor< XSAnnotation > *const janAnnot) private
traverseComplexContentDecl() [3/3]
void TraverseSchema::traverseComplexContentDecl (const XMLCh *const typeName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, const bool isMixed, Janitor< XSAnnotation > *const janAnnot) private
traverseComplexTypeDecl() [1/3]
int TraverseSchema::traverseComplexTypeDecl (const DOMElement *const childElem, const bool topLevel = true, const XMLCh *const recursingTypeName = 0) private
traverseComplexTypeDecl() [2/3]
int TraverseSchema::traverseComplexTypeDecl (const DOMElement *const childElem, const bool topLevel = true, const XMLCh *const recursingTypeName = 0) private
traverseComplexTypeDecl() [3/3]
int TraverseSchema::traverseComplexTypeDecl (const DOMElement *const childElem, const bool topLevel = true, const XMLCh *const recursingTypeName = 0) private
traverseElementDecl() [1/3]
SchemaElementDecl* TraverseSchema::traverseElementDecl (const DOMElement *const childElem, const bool topLevel = false) private
traverseElementDecl() [2/3]
SchemaElementDecl* TraverseSchema::traverseElementDecl (const DOMElement *const childElem, const bool topLevel = false) private
traverseElementDecl() [3/3]
SchemaElementDecl* TraverseSchema::traverseElementDecl (const DOMElement *const childElem, const bool topLevel = false) private
traverseGroupDecl() [1/3]
XercesGroupInfo* TraverseSchema::traverseGroupDecl (const DOMElement *const childElem, const bool topLevel = true) private
traverseGroupDecl() [2/3]
XercesGroupInfo* TraverseSchema::traverseGroupDecl (const DOMElement *const childElem, const bool topLevel = true) private
traverseGroupDecl() [3/3]
XercesGroupInfo* TraverseSchema::traverseGroupDecl (const DOMElement *const childElem, const bool topLevel = true) private
traverseIdentityConstraint() [1/3]
bool TraverseSchema::traverseIdentityConstraint (IdentityConstraint *const ic, const DOMElement *const icElem) private
traverseIdentityConstraint() [2/3]
bool TraverseSchema::traverseIdentityConstraint (IdentityConstraint *const ic, const DOMElement *const icElem) private
traverseIdentityConstraint() [3/3]
bool TraverseSchema::traverseIdentityConstraint (IdentityConstraint *const ic, const DOMElement *const icElem) private
traverseImport() [1/3]
void TraverseSchema::traverseImport (const DOMElement *const childElem) private
traverseImport() [2/3]
void TraverseSchema::traverseImport (const DOMElement *const childElem) private
traverseImport() [3/3]
void TraverseSchema::traverseImport (const DOMElement *const childElem) private
traverseInclude() [1/3]
void TraverseSchema::traverseInclude (const DOMElement *const childElem) private
traverseInclude() [2/3]
void TraverseSchema::traverseInclude (const DOMElement *const childElem) private
traverseInclude() [3/3]
void TraverseSchema::traverseInclude (const DOMElement *const childElem) private
traverseKey() [1/3]
void TraverseSchema::traverseKey (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
traverseKey() [2/3]
void TraverseSchema::traverseKey (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
traverseKey() [3/3]
void TraverseSchema::traverseKey (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
traverseKeyRef() [1/3]
void TraverseSchema::traverseKeyRef (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
traverseKeyRef() [2/3]
void TraverseSchema::traverseKeyRef (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
traverseKeyRef() [3/3]
void TraverseSchema::traverseKeyRef (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
traverseNotationDecl() [1/6]
const XMLCh* TraverseSchema::traverseNotationDecl (const DOMElement *const childElem) private
traverseNotationDecl() [2/6]
const XMLCh* TraverseSchema::traverseNotationDecl (const DOMElement *const childElem) private
traverseNotationDecl() [3/6]
const XMLCh* TraverseSchema::traverseNotationDecl (const DOMElement *const childElem) private
traverseNotationDecl() [4/6]
const XMLCh* TraverseSchema::traverseNotationDecl (const DOMElement *const childElem, const XMLCh *const name, const XMLCh *const uriStr) private
traverseNotationDecl() [5/6]
const XMLCh* TraverseSchema::traverseNotationDecl (const DOMElement *const childElem, const XMLCh *const name, const XMLCh *const uriStr) private
traverseNotationDecl() [6/6]
const XMLCh* TraverseSchema::traverseNotationDecl (const DOMElement *const childElem, const XMLCh *const name, const XMLCh *const uriStr) private
traverseRedefine() [1/3]
void TraverseSchema::traverseRedefine (const DOMElement *const childElem) private
traverseRedefine() [2/3]
void TraverseSchema::traverseRedefine (const DOMElement *const childElem) private
traverseRedefine() [3/3]
void TraverseSchema::traverseRedefine (const DOMElement *const childElem) private
traverseSchemaHeader() [1/3]
void TraverseSchema::traverseSchemaHeader (const DOMElement *const schemaRoot) private
traverseSchemaHeader() [2/3]
void TraverseSchema::traverseSchemaHeader (const DOMElement *const schemaRoot) private
traverseSchemaHeader() [3/3]
void TraverseSchema::traverseSchemaHeader (const DOMElement *const schemaRoot) private
traverseSimpleContentDecl() [1/3]
void TraverseSchema::traverseSimpleContentDecl (const XMLCh *const typeName, const XMLCh *const qualifiedName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, Janitor< XSAnnotation > *const janAnnot) private
traverseSimpleContentDecl() [2/3]
void TraverseSchema::traverseSimpleContentDecl (const XMLCh *const typeName, const XMLCh *const qualifiedName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, Janitor< XSAnnotation > *const janAnnot) private
traverseSimpleContentDecl() [3/3]
void TraverseSchema::traverseSimpleContentDecl (const XMLCh *const typeName, const XMLCh *const qualifiedName, const DOMElement *const contentDecl, ComplexTypeInfo *const typeInfo, Janitor< XSAnnotation > *const janAnnot) private
traverseSimpleTypeDecl() [1/3]
DatatypeValidator* TraverseSchema::traverseSimpleTypeDecl (const DOMElement *const childElem, const bool topLevel = true, int baseRefContext = SchemaSymbols::XSD_EMPTYSET) private
traverseSimpleTypeDecl() [2/3]
DatatypeValidator* TraverseSchema::traverseSimpleTypeDecl (const DOMElement *const childElem, const bool topLevel = true, int baseRefContext = SchemaSymbols::XSD_EMPTYSET) private
traverseSimpleTypeDecl() [3/3]
DatatypeValidator* TraverseSchema::traverseSimpleTypeDecl (const DOMElement *const childElem, const bool topLevel = true, int baseRefContext = SchemaSymbols::XSD_EMPTYSET) private
traverseUnique() [1/3]
void TraverseSchema::traverseUnique (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
traverseUnique() [2/3]
void TraverseSchema::traverseUnique (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
traverseUnique() [3/3]
void TraverseSchema::traverseUnique (const DOMElement *const icElem, SchemaElementDecl *const elemDecl) private
updateCircularSubstitutionList() [1/3]
void TraverseSchema::updateCircularSubstitutionList (SchemaInfo *const aSchemaInfo) private
Update the list of valid substitution groups in the case of circular import.
updateCircularSubstitutionList() [2/3]
void TraverseSchema::updateCircularSubstitutionList (SchemaInfo *const aSchemaInfo) private
Update the list of valid substitution groups in the case of circular import.
updateCircularSubstitutionList() [3/3]
void TraverseSchema::updateCircularSubstitutionList (SchemaInfo *const aSchemaInfo) private
Update the list of valid substitution groups in the case of circular import.
validateAnnotations() [1/3]
void TraverseSchema::validateAnnotations () private
validateAnnotations() [2/3]
void TraverseSchema::validateAnnotations () private
validateAnnotations() [3/3]
void TraverseSchema::validateAnnotations () private
validateRedefineNameChange() [1/3]
bool TraverseSchema::validateRedefineNameChange (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildElemName, const XMLCh *const redefineChildDeclName, const int redefineNameCounter, SchemaInfo *const redefiningSchemaInfo) private
This method returns true if the redefine component is valid, and if it was possible to revise it correctly.
validateRedefineNameChange() [2/3]
bool TraverseSchema::validateRedefineNameChange (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildElemName, const XMLCh *const redefineChildDeclName, const int redefineNameCounter, SchemaInfo *const redefiningSchemaInfo) private
This method returns true if the redefine component is valid, and if it was possible to revise it correctly.
validateRedefineNameChange() [3/3]
bool TraverseSchema::validateRedefineNameChange (const DOMElement *const redefineChildElem, const XMLCh *const redefineChildElemName, const XMLCh *const redefineChildDeclName, const int redefineNameCounter, SchemaInfo *const redefiningSchemaInfo) private
This method returns true if the redefine component is valid, and if it was possible to revise it correctly.
wildcardAllowsNamespace() [1/3]
bool TraverseSchema::wildcardAllowsNamespace (const SchemaAttDef *const baseAttWildCard, const unsigned int nameURI) private
Check whether a namespace value is valid with respect to wildcard constraint
wildcardAllowsNamespace() [2/3]
bool TraverseSchema::wildcardAllowsNamespace (const SchemaAttDef *const baseAttWildCard, const unsigned int nameURI) private
Check whether a namespace value is valid with respect to wildcard constraint
wildcardAllowsNamespace() [3/3]
bool TraverseSchema::wildcardAllowsNamespace (const SchemaAttDef *const baseAttWildCard, const unsigned int nameURI) private
Check whether a namespace value is valid with respect to wildcard constraint
Friends And Related Function Documentation
GeneralAttributeCheck
GeneralAttributeCheck friend
Definition at line 784 of file TraverseSchema.hpp.
NamespaceScopeManager
NamespaceScopeManager friend
Definition at line 785 of file TraverseSchema.hpp.
Member Data Documentation
fAnnotation
XSAnnotation * TraverseSchema::fAnnotation private
Definition at line 781 of file TraverseSchema.hpp.
fAnonXSTypeCount
unsigned int TraverseSchema::fAnonXSTypeCount private
Definition at line 740 of file TraverseSchema.hpp.
Referenced by genAnonTypeName().
fAttGroupRegistry
RefHashTableOf< XercesAttGroupInfo > * TraverseSchema::fAttGroupRegistry private
Definition at line 755 of file TraverseSchema.hpp.
fAttributeCheck
GeneralAttributeCheck TraverseSchema::fAttributeCheck private
Definition at line 782 of file TraverseSchema.hpp.
fAttributeDeclRegistry
RefHashTableOf< XMLAttDef > * TraverseSchema::fAttributeDeclRegistry private
Definition at line 752 of file TraverseSchema.hpp.
fBuffer
XMLBuffer TraverseSchema::fBuffer private
Definition at line 750 of file TraverseSchema.hpp.
Referenced by genAnonTypeName(), getLocalPart(), and getPrefix().
fCachedSchemaInfoList
RefHash2KeysTableOf< SchemaInfo > * TraverseSchema::fCachedSchemaInfoList private
Definition at line 775 of file TraverseSchema.hpp.
fCircularCheckIndex
XMLSize_t TraverseSchema::fCircularCheckIndex private
Definition at line 741 of file TraverseSchema.hpp.
fComplexTypeRegistry
RefHashTableOf< ComplexTypeInfo > * TraverseSchema::fComplexTypeRegistry private
Definition at line 753 of file TraverseSchema.hpp.
fCurrentAttGroupInfo
XercesAttGroupInfo * TraverseSchema::fCurrentAttGroupInfo private
Definition at line 760 of file TraverseSchema.hpp.
fCurrentComplexType
ComplexTypeInfo * TraverseSchema::fCurrentComplexType private
Definition at line 761 of file TraverseSchema.hpp.
fCurrentGroupInfo
XercesGroupInfo * TraverseSchema::fCurrentGroupInfo private
Definition at line 759 of file TraverseSchema.hpp.
fCurrentGroupStack
ValueVectorOf< unsigned int > * TraverseSchema::fCurrentGroupStack private
Definition at line 763 of file TraverseSchema.hpp.
fCurrentScope
unsigned int TraverseSchema::fCurrentScope private
Definition at line 738 of file TraverseSchema.hpp.
fCurrentTypeNameStack
ValueVectorOf< unsigned int > * TraverseSchema::fCurrentTypeNameStack private
Definition at line 762 of file TraverseSchema.hpp.
Referenced by popCurrentTypeNameStack().
fDatatypeRegistry
DatatypeValidatorFactory * TraverseSchema::fDatatypeRegistry private
Definition at line 743 of file TraverseSchema.hpp.
fDeclStack
ValueVectorOf< const DOMElement * > * TraverseSchema::fDeclStack private
Definition at line 765 of file TraverseSchema.hpp.
fEmptyNamespaceURI
int TraverseSchema::fEmptyNamespaceURI private
Definition at line 737 of file TraverseSchema.hpp.
fEntityHandler
XMLEntityHandler * TraverseSchema::fEntityHandler private
Definition at line 746 of file TraverseSchema.hpp.
fErrorReporter
XMLErrorReporter * TraverseSchema::fErrorReporter private
Definition at line 747 of file TraverseSchema.hpp.
fFullConstraintChecking
bool TraverseSchema::fFullConstraintChecking private
Definition at line 735 of file TraverseSchema.hpp.
fGlobalDeclarations
ValueVectorOf< unsigned int > ** TraverseSchema::fGlobalDeclarations private
Definition at line 766 of file TraverseSchema.hpp.
fGrammarPoolMemoryManager
MemoryManager * TraverseSchema::fGrammarPoolMemoryManager private
Definition at line 780 of file TraverseSchema.hpp.
fGrammarResolver
GrammarResolver * TraverseSchema::fGrammarResolver private
Definition at line 744 of file TraverseSchema.hpp.
fGroupRegistry
RefHashTableOf< XercesGroupInfo > * TraverseSchema::fGroupRegistry private
Definition at line 754 of file TraverseSchema.hpp.
fIC_Elements
ValueVectorOf< SchemaElementDecl * > * TraverseSchema::fIC_Elements private
Definition at line 764 of file TraverseSchema.hpp.
fIC_ElementsNS
RefHashTableOf< ElemVector > * TraverseSchema::fIC_ElementsNS private
Definition at line 756 of file TraverseSchema.hpp.
fIC_NodeListNS
RefHashTableOf< ValueVectorOf< DOMElement * >, PtrHasher > * TraverseSchema::fIC_NodeListNS private
Definition at line 769 of file TraverseSchema.hpp.
fIdentityConstraintNames
RefHash2KeysTableOf< IdentityConstraint > * TraverseSchema::fIdentityConstraintNames private
Definition at line 772 of file TraverseSchema.hpp.
fImportedNSList
ValueVectorOf< int > * TraverseSchema::fImportedNSList private
Definition at line 768 of file TraverseSchema.hpp.
Referenced by addImportedNS(), and isImportingNS().
fLocator
XSDLocator * TraverseSchema::fLocator private
Definition at line 778 of file TraverseSchema.hpp.
fMemoryManager
MemoryManager * TraverseSchema::fMemoryManager private
Definition at line 779 of file TraverseSchema.hpp.
Referenced by addImportedNS(), and genAnonTypeName().
fNonXSAttList
ValueVectorOf< DOMNode * > * TraverseSchema::fNonXSAttList private
Definition at line 767 of file TraverseSchema.hpp.
fNotationRegistry
RefHash2KeysTableOf< XMLCh > * TraverseSchema::fNotationRegistry private
Definition at line 770 of file TraverseSchema.hpp.
fParser
XSDDOMParser * TraverseSchema::fParser private
Definition at line 776 of file TraverseSchema.hpp.
fPreprocessedNodes
RefHashTableOf< SchemaInfo, PtrHasher > * TraverseSchema::fPreprocessedNodes private
Definition at line 757 of file TraverseSchema.hpp.
fRedefineComponents
RefHash2KeysTableOf< XMLCh > * TraverseSchema::fRedefineComponents private
Definition at line 771 of file TraverseSchema.hpp.
fScanner
XMLScanner * TraverseSchema::fScanner private
Definition at line 751 of file TraverseSchema.hpp.
fSchemaGrammar
SchemaGrammar * TraverseSchema::fSchemaGrammar private
Definition at line 745 of file TraverseSchema.hpp.
fSchemaInfo
SchemaInfo * TraverseSchema::fSchemaInfo private
Definition at line 758 of file TraverseSchema.hpp.
fSchemaInfoList
RefHash2KeysTableOf< SchemaInfo > * TraverseSchema::fSchemaInfoList private
Definition at line 774 of file TraverseSchema.hpp.
fScopeCount
unsigned int TraverseSchema::fScopeCount private
Definition at line 739 of file TraverseSchema.hpp.
fStringPool
XMLStringPool * TraverseSchema::fStringPool private
Definition at line 749 of file TraverseSchema.hpp.
Referenced by genAnonTypeName(), getLocalPart(), and getPrefix().
fTargetNSURI
int TraverseSchema::fTargetNSURI private
Definition at line 736 of file TraverseSchema.hpp.
fTargetNSURIString
const XMLCh * TraverseSchema::fTargetNSURIString private
Definition at line 742 of file TraverseSchema.hpp.
Referenced by isBaseFromAnotherSchema().
fURIStringPool
XMLStringPool * TraverseSchema::fURIStringPool private
Definition at line 748 of file TraverseSchema.hpp.
fValidSubstitutionGroups
RefHash2KeysTableOf< ElemVector > * TraverseSchema::fValidSubstitutionGroups private
Definition at line 773 of file TraverseSchema.hpp.
fXSDErrorReporter
XSDErrorReporter TraverseSchema::fXSDErrorReporter private
Definition at line 777 of file TraverseSchema.hpp.
The documentation for this class was generated from the following file:
src/libs/xerces-c/macx/include/xercesc/validators/schema/TraverseSchema.hpp